Fennix: APIC::Timer Class Reference
APIC::Timer Class Reference
#include <apic.hpp>
Public Member Functions
uint64_t GetTicks ()
void OneShot (uint32_t Vector, uint64_t Miliseconds)
Timer (APIC *apic)
~Timer ()
uint64_t GetTicks ()
void OneShot (uint32_t Vector, uint64_t Miliseconds)
Timer (APIC *apic)
~Timer ()
Private Member Functions
void OnInterruptReceived (CPU::x64::TrapFrame *Frame)
void OnInterruptReceived (CPU::x32::TrapFrame *Frame)
Private Attributes
APIC * lapic
uint64_t Ticks = 0
Additional Inherited Members
Protected Member Functions inherited from Interrupts::Handler
void SetInterruptNumber (int InterruptNumber)
Set a new interrupt number.
int GetInterruptNumber ()
Handler (int InterruptNumber)
Create a new interrupt handler.
~Handler ()
Detailed Description
Definition at line 371 of file apic.hpp.
Constructor & Destructor Documentation
Timer() [1/2]
APIC::Timer::Timer (APIC * apic)
Definition at line 427 of file AdvancedProgrammableInterruptController.cpp.
                            : Interrupts::Handler(0) /* IRQ0 */
     {
         SmartCriticalSection(APICLock);
         this->lapic = apic;
         LVTTimerDivide Divider = DivideBy8;
         trace("Initializing APIC timer on CPU %d",
               GetCurrentCPU()->ID);
         if (this->lapic->x2APIC)
         {
             wrmsr(MSR_X2APIC_DIV_CONF, Divider);
             wrmsr(MSR_X2APIC_INIT_COUNT, 0xFFFFFFFF);
         }
         else
         {
             this->lapic->Write(APIC_TDCR, Divider);
             this->lapic->Write(APIC_TICR, 0xFFFFFFFF);
         }
         TimeManager->Sleep(1, Time::Units::Milliseconds);
         // Mask the timer
         if (this->lapic->x2APIC)
         {
             wrmsr(MSR_X2APIC_LVT_TIMER, 0x10000 /* LVTTimer.Mask flag */);
             Ticks = 0xFFFFFFFF - rdmsr(MSR_X2APIC_CUR_COUNT);
         }
         else
         {
             this->lapic->Write(APIC_TIMER, 0x10000 /* LVTTimer.Mask flag */);
             Ticks = 0xFFFFFFFF - this->lapic->Read(APIC_TCCR);
         }
         // Config for IRQ0 timer
         LVTTimer timer{};
         timer.VEC = IRQ0;
         timer.M = Unmasked;
         timer.TMM = LVTTimerMode::OneShot;
         // Initialize APIC timer
         if (this->lapic->x2APIC)
         {
             wrmsr(MSR_X2APIC_DIV_CONF, Divider);
             wrmsr(MSR_X2APIC_INIT_COUNT, Ticks);
             wrmsr(MSR_X2APIC_LVT_TIMER, timer.raw);
         }
         else
         {
             this->lapic->Write(APIC_TDCR, Divider);
             this->lapic->Write(APIC_TICR, uint32_t(Ticks));
             this->lapic->Write(APIC_TIMER, uint32_t(timer.raw));
         }
         trace("%d APIC Timer %d ticks in.",
               GetCurrentCPU()->ID, Ticks);
         KPrint("APIC Timer: \e8888FF%ld\eCCCCCC ticks.", Ticks);
     }
References APIC::APIC_TCCR, APIC::APIC_TDCR, APIC::APIC_TICR, APIC::APIC_TIMER, APIC::DivideBy8, GetCurrentCPU(), ID, CPU::x86::IRQ0, KPrint(), lapic, Time::Milliseconds, CPU::x32::MSR_X2APIC_CUR_COUNT, CPU::x32::MSR_X2APIC_DIV_CONF, CPU::x32::MSR_X2APIC_INIT_COUNT, CPU::x32::MSR_X2APIC_LVT_TIMER, APIC::OneShot, APIC::APIC::Read(), Time::time::Sleep(), Ticks, TimeManager, trace, APIC::Unmasked, APIC::APIC::Write(), and APIC::APIC::x2APIC.
~Timer() [1/2]
APIC::Timer::~Timer ()
Definition at line 486 of file AdvancedProgrammableInterruptController.cpp.
     {
     }
Timer() [2/2]
APIC::Timer::Timer (APIC * apic)
~Timer() [2/2]
APIC::Timer::~Timer ()
Member Function Documentation
GetTicks() [1/2]
uint64_t APIC::Timer::GetTicks () inline
Definition at line 379 of file apic.hpp.
 { return Ticks; }
References Ticks.
GetTicks() [2/2]
uint64_t APIC::Timer::GetTicks () inline
Definition at line 349 of file apic.hpp.
 { return Ticks; }
References Ticks.
OneShot() [1/2]
void APIC::Timer::OneShot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 401 of file AdvancedProgrammableInterruptController.cpp.
     {
         SmartCriticalSection(APICLock);
         LVTTimer timer{};
         timer.VEC = uint8_t(Vector);
         timer.TMM = LVTTimerMode::OneShot;
         LVTTimerDivide Divider = DivideBy8;
         if (unlikely(strcmp(CPU::Hypervisor(), x86_CPUID_VENDOR_TCG) != 0))
             Divider = DivideBy128;
         if (this->lapic->x2APIC)
         {
             wrmsr(MSR_X2APIC_DIV_CONF, Divider);
             wrmsr(MSR_X2APIC_INIT_COUNT, uint32_t(Ticks * Miliseconds));
             wrmsr(MSR_X2APIC_LVT_TIMER, uint32_t(timer.raw));
         }
         else
         {
             this->lapic->Write(APIC_TDCR, Divider);
             this->lapic->Write(APIC_TICR, uint32_t(Ticks * Miliseconds));
             this->lapic->Write(APIC_TIMER, uint32_t(timer.raw));
         }
     }
References APIC::APIC_TDCR, APIC::APIC_TICR, APIC::APIC_TIMER, APIC::DivideBy128, APIC::DivideBy8, CPU::Hypervisor(), CPU::x64::MSR_X2APIC_DIV_CONF, CPU::x64::MSR_X2APIC_INIT_COUNT, CPU::x64::MSR_X2APIC_LVT_TIMER, APIC::OneShot, strcmp, unlikely, and x86_CPUID_VENDOR_TCG.
OneShot() [2/2]
void APIC::Timer::OneShot (uint32_t Vector, uint64_t Miliseconds)
OnInterruptReceived() [1/2]
void APIC::Timer::OnInterruptReceived (CPU::x32::TrapFrame * Frame) private
OnInterruptReceived() [2/2]
void APIC::Timer::OnInterruptReceived (CPU::x64::TrapFrame * Frame) private
Field Documentation
lapic
APIC * APIC::Timer::lapic private
Definition at line 374 of file apic.hpp.
Referenced by Timer().
Ticks
uint64_t APIC::Timer::Ticks = 0 private
Definition at line 375 of file apic.hpp.
Referenced by GetTicks(), and Timer().
The documentation for this class was generated from the following files:
Kernel/Architecture/amd64/cpu/apic.hpp
Kernel/Architecture/amd64/cpu/AdvancedProgrammableInterruptController.cpp