Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/reiserfs.c File Reference
reiserfs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct reiserfs_super_block
struct reiser4_super_block
Macros
#define REISERFS1_SUPERBLOCK_OFFSET 0x2000
#define REISERFS_SUPERBLOCK_OFFSET 0x10000
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_reiserfs (struct volume_id *id)
Variables
struct reiserfs_super_block PACKED
Data Structure Documentation
reiserfs_super_block
struct reiserfs_super_block
Definition at line 49 of file mkfs_reiser.c.
Data Fields
uint32_t blocks_count
uint16_t blocksize
uint32_t dummy2[5]
uint16_t dummy3[3]
uint32_t dummy4[5]
uint32_t free_blocks
uint32_t journal_block
uint32_t journal_dev
uint8_t label[16]
uint8_t magic[12]
uint32_t orig_journal_size
uint32_t root_block
unsigned char s_label[16]
char s_magic[10]
char s_unused[76]
unsigned char s_uuid[16]
uint32_t sb_block_count
uint16_t sb_blocksize
uint16_t sb_bmap_nr
uint32_t sb_check_interval
uint32_t sb_flags
uint32_t sb_free_blocks
uint16_t sb_fs_state
uint32_t sb_hash_function_code
uint32_t sb_inode_generation
struct journal_params sb_journal
uint32_t sb_lastcheck
uint16_t sb_max_mnt_count
uint16_t sb_mnt_count
uint16_t sb_oid_cursize
uint16_t sb_oid_maxsize
uint16_t sb_reserved_for_journal
uint32_t sb_root_block
uint16_t sb_tree_height
uint16_t sb_umount_state
uint16_t sb_version
uint8_t uuid[16]
reiser4_super_block
struct reiser4_super_block
Definition at line 46 of file reiserfs.c.
Data Fields
uint16_t dummy[2]
uint64_t dummy2
uint8_t label[16]
uint8_t magic[16]
uint8_t uuid[16]
Macro Definition Documentation
off
#define off ((uint64_t)0)
REISERFS1_SUPERBLOCK_OFFSET
#define REISERFS1_SUPERBLOCK_OFFSET 0x2000
Definition at line 54 of file reiserfs.c.
REISERFS_SUPERBLOCK_OFFSET
#define REISERFS_SUPERBLOCK_OFFSET 0x10000
Definition at line 55 of file reiserfs.c.
Function Documentation
volume_id_probe_reiserfs()
int FAST_FUNC volume_id_probe_reiserfs (struct volume_id * id)
Definition at line 57 of file reiserfs.c.
 {
 #define off ((uint64_t)0)
     struct reiserfs_super_block *rs;
     struct reiser4_super_block *rs4;
     dbg("reiserfs: probing at offset 0x%llx", (unsigned long long) off);
     rs = volume_id_get_buffer(id, off + REISERFS_SUPERBLOCK_OFFSET, 0x200);
     if (rs == NULL)
         return -1;
     if (memcmp(rs->magic, "ReIsErFs", 8) == 0) {
         dbg("reiserfs: ReIsErFs, no label");
 //      strcpy(id->type_version, "3.5");
         goto found;
     }
     if (memcmp(rs->magic, "ReIsEr2Fs", 9) == 0) {
         dbg("reiserfs: ReIsEr2Fs");
 //      strcpy(id->type_version, "3.6");
         goto found_label;
     }
     if (memcmp(rs->magic, "ReIsEr3Fs", 9) == 0) {
         dbg("reiserfs: ReIsEr3Fs");
 //      strcpy(id->type_version, "JR");
         goto found_label;
     }
     rs4 = (struct reiser4_super_block *) rs;
     if (memcmp(rs4->magic, "ReIsEr4", 7) == 0) {
 //      strcpy(id->type_version, "4");
 //      volume_id_set_label_raw(id, rs4->label, 16);
         volume_id_set_label_string(id, rs4->label, 16);
         volume_id_set_uuid(id, rs4->uuid, UUID_DCE);
         dbg("reiserfs: ReIsEr4, label '%s' uuid '%s'", id->label, id->uuid);
         goto found;
     }
     rs = volume_id_get_buffer(id, off + REISERFS1_SUPERBLOCK_OFFSET, 0x200);
     if (rs == NULL)
         return -1;
     if (memcmp(rs->magic, "ReIsErFs", 8) == 0) {
         dbg("reiserfs: ReIsErFs, no label");
 //      strcpy(id->type_version, "3.5");
         goto found;
     }
     dbg("reiserfs: no signature found");
     return -1;
  found_label:
 //  volume_id_set_label_raw(id, rs->label, 16);
     volume_id_set_label_string(id, rs->label, 16);
     volume_id_set_uuid(id, rs->uuid, UUID_DCE);
     dbg("reiserfs: label '%s' uuid '%s'", id->label, id->uuid);
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "reiserfs";)
     return 0;
 }
References dbg, found, reiserfs_super_block::label, reiser4_super_block::label, volume_id::label, reiserfs_super_block::magic, reiser4_super_block::magic, memcmp(), NULL, off, REISERFS1_SUPERBLOCK_OFFSET, REISERFS_SUPERBLOCK_OFFSET, reiserfs_super_block::uuid, reiser4_super_block::uuid, volume_id::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
Variable Documentation
PACKED
struct reiser4_super_block PACKED