Fennix: Userspace/apps/base/busybox/archival/libarchive/bz/bzlib_private.h File Reference
bzlib_private.h File Reference
Data Structures
struct EState
Macros
#define True ((Bool)1)
#define False ((Bool)0)
#define AssertH(cond, msg) do { } while (0)
#define AssertD(cond, msg) do { } while (0)
#define BZ_HDR_B 0x42 /* 'B' */
#define BZ_HDR_Z 0x5a /* 'Z' */
#define BZ_HDR_h 0x68 /* 'h' */
#define BZ_HDR_0 0x30 /* '0' */
#define BZ_HDR_BZh0 0x425a6830
#define BZ_MAX_ALPHA_SIZE 258
#define BZ_MAX_CODE_LEN 23
#define BZ_RUNA 0
#define BZ_RUNB 1
#define BZ_N_GROUPS 6
#define BZ_G_SIZE 50
#define BZ_N_ITERS 4
#define BZ_MAX_SELECTORS (2 + (900000 / BZ_G_SIZE))
#define BZ_INITIALISE_CRC(crcVar)
#define BZ_FINALISE_CRC(crcVar)
#define BZ_UPDATE_CRC(s, crcVar, cha)
#define BZ_M_IDLE 1
#define BZ_M_RUNNING 2
#define BZ_M_FLUSHING 3
#define BZ_M_FINISHING 4
#define BZ_S_OUTPUT 1
#define BZ_S_INPUT 2
#define BZ_N_RADIX 2
#define BZ_N_QSORT 12
#define BZ_N_SHELL 18
#define BZ_N_OVERSHOOT (BZ_N_RADIX + BZ_N_QSORT + BZ_N_SHELL + 2)
Typedefs
typedef unsigned char Bool
typedef struct EState EState
Functions
static int32_t BZ2_blockSort (EState *)
static void BZ2_compressBlock (EState *, int)
static void BZ2_bsInitWrite (EState *)
static void BZ2_hbAssignCodes (int32_t *, uint8_t *, int32_t, int32_t, int32_t)
static void BZ2_hbMakeCodeLengths (EState *, uint8_t *, int32_t *, int32_t, int32_t)
Macro Definition Documentation
AssertD
#define AssertD (cond, msg) do { } while (0)
Definition at line 53 of file bzlib_private.h.
AssertH
#define AssertH (cond, msg) do { } while (0)
Definition at line 43 of file bzlib_private.h.
BZ_FINALISE_CRC
#define BZ_FINALISE_CRC (crcVar)
Value:
{ \
    crcVar = ~(crcVar); \
}
Definition at line 88 of file bzlib_private.h.
BZ_G_SIZE
#define BZ_G_SIZE 50
Definition at line 75 of file bzlib_private.h.
BZ_HDR_0
#define BZ_HDR_0 0x30 /* '0' */
Definition at line 62 of file bzlib_private.h.
BZ_HDR_B
#define BZ_HDR_B 0x42 /* 'B' */
Definition at line 59 of file bzlib_private.h.
BZ_HDR_BZh0
#define BZ_HDR_BZh0 0x425a6830
Definition at line 64 of file bzlib_private.h.
BZ_HDR_h
#define BZ_HDR_h 0x68 /* 'h' */
Definition at line 61 of file bzlib_private.h.
BZ_HDR_Z
#define BZ_HDR_Z 0x5a /* 'Z' */
Definition at line 60 of file bzlib_private.h.
BZ_INITIALISE_CRC
#define BZ_INITIALISE_CRC (crcVar)
Value:
{ \
    crcVar = 0xffffffffL; \
}
Definition at line 83 of file bzlib_private.h.
BZ_M_FINISHING
#define BZ_M_FINISHING 4
Definition at line 104 of file bzlib_private.h.
BZ_M_FLUSHING
#define BZ_M_FLUSHING 3
Definition at line 103 of file bzlib_private.h.
BZ_M_IDLE
#define BZ_M_IDLE 1
Definition at line 101 of file bzlib_private.h.
BZ_M_RUNNING
#define BZ_M_RUNNING 2
Definition at line 102 of file bzlib_private.h.
BZ_MAX_ALPHA_SIZE
#define BZ_MAX_ALPHA_SIZE 258
Definition at line 68 of file bzlib_private.h.
BZ_MAX_CODE_LEN
#define BZ_MAX_CODE_LEN 23
Definition at line 69 of file bzlib_private.h.
BZ_MAX_SELECTORS
#define BZ_MAX_SELECTORS (2 + (900000 / BZ_G_SIZE))
Definition at line 78 of file bzlib_private.h.
BZ_N_GROUPS
#define BZ_N_GROUPS 6
Definition at line 74 of file bzlib_private.h.
BZ_N_ITERS
#define BZ_N_ITERS 4
Definition at line 76 of file bzlib_private.h.
BZ_N_OVERSHOOT
#define BZ_N_OVERSHOOT (BZ_N_RADIX + BZ_N_QSORT + BZ_N_SHELL + 2)
Definition at line 112 of file bzlib_private.h.
BZ_N_QSORT
#define BZ_N_QSORT 12
Definition at line 110 of file bzlib_private.h.
BZ_N_RADIX
#define BZ_N_RADIX 2
Definition at line 109 of file bzlib_private.h.
BZ_N_SHELL
#define BZ_N_SHELL 18
Definition at line 111 of file bzlib_private.h.
BZ_RUNA
#define BZ_RUNA 0
Definition at line 71 of file bzlib_private.h.
BZ_RUNB
#define BZ_RUNB 1
Definition at line 72 of file bzlib_private.h.
BZ_S_INPUT
#define BZ_S_INPUT 2
Definition at line 107 of file bzlib_private.h.
BZ_S_OUTPUT
#define BZ_S_OUTPUT 1
Definition at line 106 of file bzlib_private.h.
BZ_UPDATE_CRC
#define BZ_UPDATE_CRC (s, crcVar, cha)
Value:
{ \
    crcVar = (crcVar << 8) ^ s->crc32table[(crcVar >> 24) ^ ((uint8_t)cha)]; \
}
Definition at line 93 of file bzlib_private.h.
False
#define False ((Bool)0)
Definition at line 33 of file bzlib_private.h.
True
#define True ((Bool)1)
Definition at line 32 of file bzlib_private.h.
Typedef Documentation
Bool
typedef unsigned char Bool
Definition at line 30 of file bzlib_private.h.
EState
typedef struct EState EState
Function Documentation
BZ2_blockSort()
static int32_t BZ2_blockSort (EState *) static
BZ2_bsInitWrite()
static void BZ2_bsInitWrite (EState *) static
BZ2_compressBlock()
static void BZ2_compressBlock (EState * , int) static
Referenced by handle_compress().
BZ2_hbAssignCodes()
static void BZ2_hbAssignCodes (int32_t * , uint8_t * , int32_t , int32_t , int32_t) static
Referenced by sendMTFValues().
BZ2_hbMakeCodeLengths()
static void BZ2_hbMakeCodeLengths (EState * , uint8_t * , int32_t * , int32_t , int32_t) static
Referenced by sendMTFValues().