Fennix: Userspace/apps/base/busybox/coreutils/od.c File Reference
od.c File Reference
#include "libbb.h"
#include "dump.h"
Macros
#define TYPE_OFFSET 7
Functions
static void odoffset (dumper_t *dumper, int argc, char ***argvp)
int od_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char *const add_strings[] ALIGN_PTR
static const char od_opts[] ALIGN1 = "aBbcDdeFfHhIiLlOoXxv"
Macro Definition Documentation
TYPE_OFFSET
#define TYPE_OFFSET 7
Function Documentation
od_main()
int od_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 173 of file od.c.
 {
     int ch;
     int first = 1;
     char *p;
     dumper_t *dumper = alloc_dumper();
     while ((ch = getopt(argc, argv, od_opts)) > 0) {
         if (ch == 'v') {
             dumper->dump_vflag = ALL;
         } else if (((p = strchr(od_opts, ch)) != NULL) && (*p != '\0')) {
             if (first) {
                 first = 0;
                 bb_dump_add(dumper, "\"%07.7_Ao\n\"");
                 bb_dump_add(dumper, "\"%07.7_ao  \"");
             } else {
                 bb_dump_add(dumper, "\"         \"");
             }
             bb_dump_add(dumper, add_strings[(int)od_o2si[(p - od_opts)]]);
         } else {  /* P, p, s, w, or other unhandled */
             bb_show_usage();
         }
     }
     if (!dumper->fshead) {
         bb_dump_add(dumper, "\"%07.7_Ao\n\"");
         bb_dump_add(dumper, "\"%07.7_ao  \" 8/2 \"%06o \" \"\\n\"");
     }
     argc -= optind;
     argv += optind;
     odoffset(dumper, argc, &argv);
     return bb_dump_dump(dumper, argv);
 }
References ALL, alloc_dumper(), argc, argv, bb_dump_add(), bb_dump_dump(), bb_show_usage(), dumper, first, getopt(), NULL, odoffset(), optind, p, and strchr().
odoffset()
static void odoffset (dumper_t * dumper, int argc, char *** argvp) static
Definition at line 39 of file od.c.
 {
     char *num, *p;
     int base;
     char *end;
     /*
      * The offset syntax of od(1) was genuinely bizarre.  First, if
      * it started with a plus it had to be an offset.  Otherwise, if
      * there were at least two arguments, a number or lower-case 'x'
      * followed by a number makes it an offset.  By default it was
      * octal; if it started with 'x' or '0x' it was hex.  If it ended
      * in a '.', it was decimal.  If a 'b' or 'B' was appended, it
      * multiplied the number by 512 or 1024 byte units.  There was
      * no way to assign a block count to a hex offset.
      *
      * We assumes it's a file if the offset is bad.
      */
     p = **argvp;
     if (!p) {
         /* hey someone is probably piping to us ... */
         return;
     }
     if ((*p != '+')
         && (argc < 2
             || (!isdigit(p[0])
                 && ((p[0] != 'x') || !isxdigit(p[1])))))
         return;
     base = 0;
     /*
      * skip over leading '+', 'x[0-9a-fA-f]' or '0x', and
      * set base.
      */
     if (p[0] == '+')
         ++p;
     if (p[0] == 'x' && isxdigit(p[1])) {
         ++p;
         base = 16;
     } else if (p[0] == '0' && p[1] == 'x') {
         p += 2;
         base = 16;
     }
     /* skip over the number */
     if (base == 16)
         for (num = p; isxdigit(*p); ++p)
             continue;
     else
         for (num = p; isdigit(*p); ++p)
             continue;
     /* check for no number */
     if (num == p)
         return;
     /* if terminates with a '.', base is decimal */
     if (*p == '.') {
         if (base)
             return;
         base = 10;
     }
     dumper->dump_skip = strtol(num, &end, base ? base : 8);
     /* if end isn't the same as p, we got a non-octal digit */
     if (end != p)
         dumper->dump_skip = 0;
     else {
         if (*p) {
             if (*p == 'b') {
                 dumper->dump_skip *= 512;
                 ++p;
             } else if (*p == 'B') {
                 dumper->dump_skip *= 1024;
                 ++p;
             }
         }
         if (*p)
             dumper->dump_skip = 0;
         else {
             ++*argvp;
             /*
              * If the offset uses a non-octal base, the base of
              * the offset is changed as well.  This isn't pretty,
              * but it's easy.
              */
 #define TYPE_OFFSET 7
             {
                 char x_or_d;
                 if (base == 16) {
                     x_or_d = 'x';
                     goto DO_X_OR_D;
                 }
                 if (base == 10) {
                     x_or_d = 'd';
  DO_X_OR_D:
                     dumper->fshead->nextfu->fmt[TYPE_OFFSET]
                         = dumper->fshead->nextfs->nextfu->fmt[TYPE_OFFSET]
                         = x_or_d;
                 }
             }
         }
     }
 }
References argc, base, dumper, end, isdigit, isxdigit, num, p, strtol(), and TYPE_OFFSET.
Referenced by od_main().
Variable Documentation
ALIGN1
const char od_o2si [] ALIGN1 = "aBbcDdeFfHhIiLlOoXxv" static
Definition at line 163 of file od.c.
ALIGN_PTR
const char* const add_strings [] ALIGN_PTR static
Initial value:
= {
    "16/1 \"%3_u \" \"\\n\"",
    "8/2 \" %06o \" \"\\n\"",
    "16/1 \"%03o \" \"\\n\"",
    "16/1 \"%3_c \" \"\\n\"",
    "8/2 \"  %05u \" \"\\n\"",
    "4/4 \"     %010u \" \"\\n\"",
    "2/8 \"          %21.14e \" \"\\n\"",
    "4/4 \" %14.7e \" \"\\n\"",
    "4/4 \"       %08x \" \"\\n\"",
    "8/2 \"   %04x \" \"\\n\"",
    "4/4 \"    %11d \" \"\\n\"",
    "8/2 \" %6d \" \"\\n\"",
    "4/4 \"    %011o \" \"\\n\"",
}
Definition at line 147 of file od.c.