Fennix: Userspace/apps/base/busybox/util-linux/volume_id/luks.c File Reference
luks.c File Reference
#include "volume_id_internal.h"
Data Structures
struct luks_phdr
struct BUG_bad_size_luks_phdr
struct luks_phdr.keyblock
Macros
#define LUKS_MAGIC_L 6
#define UUID_STRING_L 40
#define LUKS_CIPHERNAME_L 32
#define LUKS_CIPHERMODE_L 32
#define LUKS_HASHSPEC_L 32
#define LUKS_DIGESTSIZE 20
#define LUKS_SALTSIZE 32
#define LUKS_NUMKEYS 8
#define off ((uint64_t)0)
Enumerations
enum { EXPECTED_SIZE_luks_phdr }
Functions
int FAST_FUNC volume_id_probe_luks (struct volume_id *id)
Variables
static const uint8_t LUKS_MAGIC[] ALIGN1 = { 'L','U','K','S', 0xba, 0xbe }
Data Structure Documentation
luks_phdr
struct luks_phdr
Definition at line 40 of file luks.c.
Data Fields
uint8_t cipherMode[LUKS_CIPHERMODE_L]
uint8_t cipherName[LUKS_CIPHERNAME_L]
uint8_t hashSpec[LUKS_HASHSPEC_L]
struct luks_phdr keyblock[LUKS_NUMKEYS]
uint32_t keyBytes
uint8_t magic[LUKS_MAGIC_L]
uint8_t mkDigest[LUKS_DIGESTSIZE]
uint32_t mkDigestIterations
uint8_t mkDigestSalt[LUKS_SALTSIZE]
uint32_t payloadOffset
uint8_t uuid[UUID_STRING_L]
uint16_t version
BUG_bad_size_luks_phdr
struct BUG_bad_size_luks_phdr
Definition at line 83 of file luks.c.
Data Fields
char BUG_bad_size_luks_phdr[sizeof(struct luks_phdr)==EXPECTED_SIZE_luks_phdr ? 1 :-1]
luks_phdr.keyblock
struct luks_phdr.keyblock
Definition at line 52 of file luks.c.
Data Fields
uint32_t active
uint32_t keyMaterialOffset
uint32_t passwordIterations
uint8_t passwordSalt[LUKS_SALTSIZE]
uint32_t stripes
Macro Definition Documentation
LUKS_CIPHERMODE_L
#define LUKS_CIPHERMODE_L 32
Definition at line 32 of file luks.c.
LUKS_CIPHERNAME_L
#define LUKS_CIPHERNAME_L 32
Definition at line 31 of file luks.c.
LUKS_DIGESTSIZE
#define LUKS_DIGESTSIZE 20
Definition at line 34 of file luks.c.
LUKS_HASHSPEC_L
#define LUKS_HASHSPEC_L 32
Definition at line 33 of file luks.c.
LUKS_MAGIC_L
#define LUKS_MAGIC_L 6
Definition at line 29 of file luks.c.
LUKS_NUMKEYS
#define LUKS_NUMKEYS 8
Definition at line 36 of file luks.c.
LUKS_SALTSIZE
#define LUKS_SALTSIZE 32
Definition at line 35 of file luks.c.
off
#define off ((uint64_t)0)
UUID_STRING_L
#define UUID_STRING_L 40
Definition at line 30 of file luks.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EXPECTED_SIZE_luks_phdr
Definition at line 61 of file luks.c.
      {
     EXPECTED_SIZE_luks_phdr = 0
         + 1 * LUKS_MAGIC_L
         + 2
         + 1 * LUKS_CIPHERNAME_L
         + 1 * LUKS_CIPHERMODE_L
         + 1 * LUKS_HASHSPEC_L
         + 4
         + 4
         + 1 * LUKS_DIGESTSIZE
         + 1 * LUKS_SALTSIZE
         + 4
         + 1 * UUID_STRING_L
         + LUKS_NUMKEYS * (0
           + 4
           + 4
           + 1 * LUKS_SALTSIZE
           + 4
           + 4
           )
 };
Function Documentation
volume_id_probe_luks()
int FAST_FUNC volume_id_probe_luks (struct volume_id * id)
Definition at line 89 of file luks.c.
 {
 #define off ((uint64_t)0)
     struct luks_phdr *header;
     header = volume_id_get_buffer(id, off, sizeof(*header));
     if (header == NULL)
         return -1;
     if (memcmp(header->magic, LUKS_MAGIC, LUKS_MAGIC_L))
         return -1;
 //  volume_id_set_usage(id, VOLUME_ID_CRYPTO);
     volume_id_set_uuid(id, header->uuid, UUID_DCE_STRING);
     IF_FEATURE_BLKID_TYPE(id->type = "crypto_LUKS";)
     return 0;
 }
References LUKS_MAGIC_L, memcmp(), NULL, off, UUID_DCE_STRING, volume_id_get_buffer(), and volume_id_set_uuid().
Variable Documentation
ALIGN1
const uint8_t LUKS_MAGIC [] ALIGN1 = { 'L','U','K','S', 0xba, 0xbe } static
Definition at line 38 of file luks.c.