Fennix Userspace: Userspace/apps/base/busybox/networking/interface.c File Reference
interface.c File Reference
#include "libbb.h"
#include "inet_common.h"
#include <net/if.h>
#include <net/if_arp.h>
Data Structures
struct user_net_device_stats
struct interface
struct iface_list
Macros
#define _PATH_PROCNET_DEV "/proc/net/dev"
#define _PATH_PROCNET_IFINET6 "/proc/net/if_inet6"
#define SIOCSIFTXQLEN 0x8943
#define SIOCGIFTXQLEN 0x8942
#define ifr_qlen ifr_ifru.ifru_mtu
#define HAVE_TXQUEUELEN 1
#define IFF_DYNAMIC 0x8000 /* dialup device with changing addresses */
#define FIRST_TO_ZERO metric
#define LAST_TO_ZERO hwaddr
#define ife_print6(a) ((void)0)
Functions
static const char *FAST_FUNC INET_sprint (struct sockaddr *sap, int numeric)
static int FAST_FUNC INET_input (const char *bufp, struct sockaddr *sap)
static char *FAST_FUNC UNSPEC_print (unsigned char *ptr)
static const char *FAST_FUNC UNSPEC_sprint (struct sockaddr *sap, int numeric UNUSED_PARAM)
const struct aftype *FAST_FUNC get_aftype (const char *name)
static const struct aftype * get_afntype (int af)
static struct interface * add_interface (struct iface_list *ilist, char *name)
static char * get_name (char name[IFNAMSIZ], char *p)
static void get_dev_fields (char *bp, struct interface *ife, int procnetdev_vsn)
static int procnetdev_version (char *buf)
static void if_readconf (struct iface_list *ilist)
static int if_readlist_proc (struct iface_list *ilist, char *ifname)
static void if_readlist (struct iface_list *ilist, char *ifname)
static int if_fetch (struct interface *ife)
static int do_if_fetch (struct interface *ife)
static char *FAST_FUNC ether_print (unsigned char *ptr)
const struct hwtype *FAST_FUNC get_hwtype (const char *name)
const struct hwtype *FAST_FUNC get_hwntype (int type)
static int hw_null_address (const struct hwtype *hw, void *ap)
static void print_bytes_scaled (unsigned long long ull, const char *end)
static void ife_print (struct interface *ptr)
static int do_if_print (struct interface *ife, int show_downed_too)
int FAST_FUNC display_interfaces (char *ifname)
Variables
static const struct aftype inet_aftype
static const struct aftype unspec_aftype
static const struct aftype *const aftypes []
static const char *const ss_fmt[] ALIGN_PTR
static const struct hwtype unspec_hwtype
static const struct hwtype loop_hwtype
static const struct hwtype ether_hwtype
static const struct hwtype ppp_hwtype
static const char TRext[] ALIGN1 = "\0\0\0Ki\0Mi\0Gi\0Ti"
Data Structure Documentation
user_net_device_stats
struct user_net_device_stats
Definition at line 287 of file interface.c.
Data Fields
unsigned long collisions
unsigned long long rx_bytes
unsigned long rx_compressed
unsigned long rx_crc_errors
unsigned long rx_dropped
unsigned long rx_errors
unsigned long rx_fifo_errors
unsigned long rx_frame_errors
unsigned long rx_length_errors
unsigned long rx_missed_errors
unsigned long rx_multicast
unsigned long rx_over_errors
unsigned long long rx_packets
unsigned long tx_aborted_errors
unsigned long long tx_bytes
unsigned long tx_carrier_errors
unsigned long tx_compressed
unsigned long tx_dropped
unsigned long tx_errors
unsigned long tx_fifo_errors
unsigned long tx_heartbeat_errors
unsigned long long tx_packets
unsigned long tx_window_errors
interface
struct interface
Definition at line 316 of file interface.c.
Data Fields
struct sockaddr addr
struct sockaddr broadaddr
struct sockaddr dstaddr
short flags
smallint has_ip
char hwaddr[32]
struct ifmap map
int metric
int mtu
char name[IFNAMSIZ]
struct sockaddr netmask
struct interface * next
struct interface * prev
smallint statistics_valid
struct user_net_device_stats stats
int tx_queue_len
short type
iface_list
struct iface_list
Definition at line 344 of file interface.c.
Data Fields
struct interface * int_last
struct interface * int_list
Macro Definition Documentation
_PATH_PROCNET_DEV
#define _PATH_PROCNET_DEV "/proc/net/dev"
Definition at line 53 of file interface.c.
_PATH_PROCNET_IFINET6
#define _PATH_PROCNET_IFINET6 "/proc/net/if_inet6"
Definition at line 54 of file interface.c.
FIRST_TO_ZERO
#define FIRST_TO_ZERO metric
Definition at line 324 of file interface.c.
HAVE_TXQUEUELEN
#define HAVE_TXQUEUELEN 1
Definition at line 81 of file interface.c.
ife_print6
#define ife_print6 (a) ((void)0)
Definition at line 901 of file interface.c.
IFF_DYNAMIC
#define IFF_DYNAMIC 0x8000 /* dialup device with changing addresses */
Definition at line 85 of file interface.c.
ifr_qlen
#define ifr_qlen ifr_ifru.ifru_mtu
Definition at line 77 of file interface.c.
LAST_TO_ZERO
#define LAST_TO_ZERO hwaddr
Definition at line 333 of file interface.c.
SIOCGIFTXQLEN
#define SIOCGIFTXQLEN 0x8942
Definition at line 72 of file interface.c.
SIOCSIFTXQLEN
#define SIOCSIFTXQLEN 0x8943
Definition at line 71 of file interface.c.
Function Documentation
add_interface()
static struct interface* add_interface (struct iface_list * ilist, char * name) static
Definition at line 377 of file interface.c.
 {
     struct interface *ife, **nextp, *new;
     for (ife = ilist->int_last; ife; ife = ife->prev) {
         int n = /*n*/strcmp(ife->name, name);
         if (n == 0)
             return ife;
         if (n < 0)
             break;
     }
     new = xzalloc(sizeof(*new));
     strncpy_IFNAMSIZ(new->name, name);
     nextp = ife ? &ife->next : &ilist->int_list;
     new->prev = ife;
     new->next = *nextp;
     if (new->next)
         new->next->prev = new;
     else
         ilist->int_last = new;
     *nextp = new;
     return new;
 }
References iface_list::int_last, iface_list::int_list, n, interface::name, interface::next, interface::prev, strcmp, strncpy_IFNAMSIZ(), and xzalloc().
Referenced by display_interfaces(), if_readconf(), and if_readlist_proc().
display_interfaces()
int FAST_FUNC display_interfaces (char * ifname)
Definition at line 1081 of file interface.c.
 {
     struct interface *ife;
     int res;
     struct iface_list ilist;
     ilist.int_list = NULL;
     ilist.int_last = NULL;
     if_readlist(&ilist, ifname != IFNAME_SHOW_DOWNED_TOO ? ifname : NULL);
     if (!ifname || ifname == IFNAME_SHOW_DOWNED_TOO) {
         for (ife = ilist.int_list; ife; ife = ife->next) {
             BUILD_BUG_ON((int)(intptr_t)IFNAME_SHOW_DOWNED_TOO != 1);
             res = do_if_print(ife, (int)(intptr_t)ifname);
             if (res < 0)
                 goto ret;
         }
         return 0;
     }
     ife = add_interface(&ilist, ifname);
     res = do_if_print(ife, /*show_downed_too:*/ 1);
  ret:
     return (res < 0); /* status < 0 == 1 -- error */
 }
References add_interface(), BUILD_BUG_ON, do_if_print(), if_readlist(), IFNAME_SHOW_DOWNED_TOO, iface_list::int_last, iface_list::int_list, interface::next, and NULL.
Referenced by ifconfig_main().
do_if_fetch()
static int do_if_fetch (struct interface * ife) static
Definition at line 657 of file interface.c.
 {
     if (if_fetch(ife) < 0) {
         const char *errmsg;
         if (errno == ENODEV) {
             /* Give better error message for this case. */
             errmsg = "Device not found";
         } else {
             errmsg = strerror(errno);
         }
         bb_error_msg("%s: error fetching interface information: %s",
                 ife->name, errmsg);
         return -1;
     }
     return 0;
 }
References bb_error_msg(), ENODEV, errmsg(), errno, if_fetch(), interface::name, and strerror().
Referenced by do_if_print().
do_if_print()
static int do_if_print (struct interface * ife, int show_downed_too) static
Definition at line 1069 of file interface.c.
 {
     int res;
     res = do_if_fetch(ife);
     if (res >= 0) {
         if ((ife->flags & IFF_UP) || show_downed_too)
             ife_print(ife);
     }
     return res;
 }
References do_if_fetch(), interface::flags, and ife_print().
Referenced by display_interfaces().
ether_print()
static char* FAST_FUNC ether_print (unsigned char * ptr) static
Definition at line 689 of file interface.c.
 {
     char *buff;
     buff = xasprintf("%02X:%02X:%02X:%02X:%02X:%02X",
         ptr[0], ptr[1], ptr[2], ptr[3], ptr[4], ptr[5]
     );
     return auto_string(buff);
 }
get_afntype()
static const struct aftype* get_afntype (int af) static
Definition at line 274 of file interface.c.
 {
     const struct aftype *const *afp;
     afp = aftypes;
     while (*afp != NULL) {
         if ((*afp)->af == af)
             return *afp;
         afp++;
     }
     return NULL;
 }
References aftype::af, aftypes, and NULL.
Referenced by ife_print().
get_aftype()
const struct aftype* FAST_FUNC get_aftype (const char * name)
Definition at line 260 of file interface.c.
 {
     const struct aftype *const *afp;
     afp = aftypes;
     while (*afp != NULL) {
         if (strcmp((*afp)->name, name) == 0)
             return (*afp);
         afp++;
     }
     return NULL;
 }
References aftypes, aftype::name, NULL, and strcmp.
Referenced by arp_main().
get_dev_fields()
static void get_dev_fields (char * bp, struct interface * ife, int procnetdev_vsn) static
Definition at line 462 of file interface.c.
 {
     memset(&ife->stats, 0, sizeof(struct user_net_device_stats));
     sscanf(bp, ss_fmt[procnetdev_vsn],
            &ife->stats.rx_bytes, /* missing for v0 */
            &ife->stats.rx_packets,
            &ife->stats.rx_errors,
            &ife->stats.rx_dropped,
            &ife->stats.rx_fifo_errors,
            &ife->stats.rx_frame_errors,
            &ife->stats.rx_compressed, /* missing for v0, v1 */
            &ife->stats.rx_multicast, /* missing for v0, v1 */
            &ife->stats.tx_bytes, /* missing for v0 */
            &ife->stats.tx_packets,
            &ife->stats.tx_errors,
            &ife->stats.tx_dropped,
            &ife->stats.tx_fifo_errors,
            &ife->stats.collisions,
            &ife->stats.tx_carrier_errors,
            &ife->stats.tx_compressed /* missing for v0, v1 */
            );
     if (procnetdev_vsn <= 1) {
         if (procnetdev_vsn == 0) {
             ife->stats.rx_bytes = 0;
             ife->stats.tx_bytes = 0;
         }
         ife->stats.rx_multicast = 0;
         ife->stats.rx_compressed = 0;
         ife->stats.tx_compressed = 0;
     }
 }
References bp, user_net_device_stats::collisions, memset(), user_net_device_stats::rx_bytes, user_net_device_stats::rx_compressed, user_net_device_stats::rx_dropped, user_net_device_stats::rx_errors, user_net_device_stats::rx_fifo_errors, user_net_device_stats::rx_frame_errors, user_net_device_stats::rx_multicast, user_net_device_stats::rx_packets, sscanf(), interface::stats, user_net_device_stats::tx_bytes, user_net_device_stats::tx_carrier_errors, user_net_device_stats::tx_compressed, user_net_device_stats::tx_dropped, user_net_device_stats::tx_errors, user_net_device_stats::tx_fifo_errors, and user_net_device_stats::tx_packets.
Referenced by if_readlist_proc().
get_hwntype()
const struct hwtype* FAST_FUNC get_hwntype (int type)
Definition at line 777 of file interface.c.
 {
     const struct hwtype *const *hwp;
     hwp = hwtypes;
     while (*hwp != NULL) {
         if ((*hwp)->type == type)
             return *hwp;
         hwp++;
     }
     return NULL;
 }
References NULL, and type.
Referenced by arp_disp(), arp_getdevhw(), and ife_print().
get_hwtype()
const struct hwtype* FAST_FUNC get_hwtype (const char * name)
Definition at line 763 of file interface.c.
 {
     const struct hwtype *const *hwp;
     hwp = hwtypes;
     while (*hwp != NULL) {
         if (strcmp((*hwp)->name, name) == 0)
             return (*hwp);
         hwp++;
     }
     return NULL;
 }
References hwtype::name, NULL, and strcmp.
Referenced by arp_disp(), and arp_main().
get_name()
static char* get_name (char name[IFNAMSIZ], char * p) static
Definition at line 404 of file interface.c.
 {
     /* Extract NAME from nul-terminated p of the form "<whitespace>NAME:"
      * If match is not made, set NAME to "" and return unchanged p.
      */
     char *nameend;
     char *namestart;
     nameend = namestart = skip_whitespace(p);
     for (;;) {
         if ((nameend - namestart) >= IFNAMSIZ)
             break; /* interface name too large - return "" */
         if (*nameend == ':') {
             memcpy(name, namestart, nameend - namestart);
             name[nameend - namestart] = '\0';
             return nameend + 1;
         }
         nameend++;
         /* isspace, NUL, any control char? */
         if ((unsigned char)*nameend <= (unsigned char)' ')
             break; /* trailing ':' not found - return "" */
     }
     name[0] = '\0';
     return p;
 }
References IFNAMSIZ, memcpy(), interface::name, p, and skip_whitespace().
Referenced by get_lsa(), and if_readlist_proc().
hw_null_address()
static int hw_null_address (const struct hwtype * hw, void * ap) static
Definition at line 791 of file interface.c.
 {
     int i;
     unsigned char *address = (unsigned char *) ap;
     for (i = 0; i < hw->alen; i++)
         if (address[i])
             return 0;
     return 1;
 }
References ap, hw, and i.
Referenced by ife_print().
if_fetch()
static int if_fetch (struct interface * ife) static
Definition at line 585 of file interface.c.
 {
     struct ifreq ifr;
     char *ifname = ife->name;
     int skfd;
     skfd = xsocket(AF_INET, SOCK_DGRAM, 0);
     strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
     if (ioctl(skfd, SIOCGIFFLAGS, &ifr) < 0) {
         close(skfd);
         return -1;
     }
     ife->flags = ifr.ifr_flags;
     /* set up default values if ioctl's would fail */
     ife->tx_queue_len = -1; /* unknown value */
     memset(&ife->FIRST_TO_ZERO, 0,
         offsetof(struct interface, LAST_TO_ZERO)
             - offsetof(struct interface, FIRST_TO_ZERO)
         + sizeof(ife->LAST_TO_ZERO)
     );
     strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
     if (ioctl(skfd, SIOCGIFHWADDR, &ifr) >= 0)
         memcpy(ife->hwaddr, ifr.ifr_hwaddr.sa_data, 8);
 //er.... why this _isnt_ inside if()?
     ife->type = ifr.ifr_hwaddr.sa_family;
     strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
     if (ioctl(skfd, SIOCGIFMETRIC, &ifr) >= 0)
         ife->metric = ifr.ifr_metric;
     strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
     if (ioctl(skfd, SIOCGIFMTU, &ifr) >= 0)
         ife->mtu = ifr.ifr_mtu;
 #ifdef SIOCGIFMAP
     strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
     if (ioctl(skfd, SIOCGIFMAP, &ifr) == 0)
         ife->map = ifr.ifr_map;
 #endif
 #ifdef HAVE_TXQUEUELEN
     strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
     if (ioctl(skfd, SIOCGIFTXQLEN, &ifr) >= 0)
         ife->tx_queue_len = ifr.ifr_qlen;
 #endif
     strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
     ifr.ifr_addr.sa_family = AF_INET;
     if (ioctl(skfd, SIOCGIFADDR, &ifr) == 0) {
         ife->has_ip = 1;
         ife->addr = ifr.ifr_addr;
         strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
         if (ioctl(skfd, SIOCGIFDSTADDR, &ifr) >= 0)
             ife->dstaddr = ifr.ifr_dstaddr;
         strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
         if (ioctl(skfd, SIOCGIFBRDADDR, &ifr) >= 0)
             ife->broadaddr = ifr.ifr_broadaddr;
         strncpy_IFNAMSIZ(ifr.ifr_name, ifname);
         if (ioctl(skfd, SIOCGIFNETMASK, &ifr) >= 0)
             ife->netmask = ifr.ifr_netmask;
     }
     close(skfd);
     return 0;
 }
References interface::addr, AF_INET, interface::broadaddr, close(), interface::dstaddr, FIRST_TO_ZERO, interface::flags, interface::has_ip, interface::hwaddr, ifr, ioctl(), LAST_TO_ZERO, interface::map, memcpy(), memset(), interface::metric, interface::mtu, interface::name, interface::netmask, offsetof, SIOCGIFADDR, SIOCGIFBRDADDR, SIOCGIFDSTADDR, SIOCGIFFLAGS, SIOCGIFHWADDR, SIOCGIFMAP, SIOCGIFMETRIC, SIOCGIFMTU, SIOCGIFNETMASK, SIOCGIFTXQLEN, skfd, SOCK_DGRAM, strncpy_IFNAMSIZ(), interface::tx_queue_len, interface::type, and xsocket().
Referenced by do_if_fetch().
if_readconf()
static void if_readconf (struct iface_list * ilist) static
Definition at line 505 of file interface.c.
 {
     int numreqs = 30;
     struct ifconf ifc;
     struct ifreq *ifr;
     int n;
     int skfd;
     ifc.ifc_buf = NULL;
     /* SIOCGIFCONF currently seems to only work properly on AF_INET sockets
        (as of 2.1.128) */
     skfd = xsocket(AF_INET, SOCK_DGRAM, 0);
     for (;;) {
         ifc.ifc_len = sizeof(struct ifreq) * numreqs;
         ifc.ifc_buf = xrealloc(ifc.ifc_buf, ifc.ifc_len);
         xioctl(skfd, SIOCGIFCONF, &ifc);
         if (ifc.ifc_len == (int)(sizeof(struct ifreq) * numreqs)) {
             /* assume it overflowed and try again */
             numreqs += 10;
             continue;
         }
         break;
     }
     ifr = ifc.ifc_req;
     for (n = 0; n < ifc.ifc_len; n += sizeof(struct ifreq)) {
         add_interface(ilist, ifr->ifr_name);
         ifr++;
     }
     close(skfd);
     free(ifc.ifc_buf);
 }
References add_interface(), AF_INET, close(), free, ifr, n, NULL, SIOCGIFCONF, skfd, SOCK_DGRAM, xioctl, xrealloc, and xsocket().
Referenced by if_readlist().
if_readlist()
static void if_readlist (struct iface_list * ilist, char * ifname) static
Definition at line 576 of file interface.c.
 {
     int found = if_readlist_proc(ilist, ifname);
     /* Needed in order to get ethN:M aliases */
     if (!found)
         if_readconf(ilist);
 }
References found, if_readconf(), and if_readlist_proc().
Referenced by display_interfaces().
if_readlist_proc()
static int if_readlist_proc (struct iface_list * ilist, char * ifname) static
Definition at line 542 of file interface.c.
 {
     FILE *fh;
     char buf[512];
     struct interface *ife;
     int procnetdev_vsn;
     int ret;
     fh = fopen_or_warn(_PATH_PROCNET_DEV, "r");
     if (!fh) {
         return 0; /* "not found" */
     }
     fgets(buf, sizeof buf, fh); /* eat line */
     fgets(buf, sizeof buf, fh);
     procnetdev_vsn = procnetdev_version(buf);
     ret = 0;
     while (fgets(buf, sizeof buf, fh)) {
         char *s, name[IFNAMSIZ];
         s = get_name(name, buf);
         ife = add_interface(ilist, name);
         get_dev_fields(s, ife, procnetdev_vsn);
         ife->statistics_valid = 1;
         if (ifname && strcmp(ifname, name) == 0) {
             ret = 1; /* found */
             break;
         }
     }
     fclose(fh);
     return ret;
 }
References _PATH_PROCNET_DEV, add_interface(), buf, fclose(), fgets, fopen_or_warn(), get_dev_fields(), get_name(), IFNAMSIZ, interface::name, procnetdev_version(), s, interface::statistics_valid, and strcmp.
Referenced by if_readlist().
ife_print()
static void ife_print (struct interface * ptr) static
Definition at line 904 of file interface.c.
 {
     const struct aftype *ap;
     const struct hwtype *hw;
     int hf;
     int can_compress = 0;
     ap = get_afntype(ptr->addr.sa_family);
     if (ap == NULL)
         ap = get_afntype(0);
     hf = ptr->type;
     if (hf == ARPHRD_CSLIP || hf == ARPHRD_CSLIP6)
         can_compress = 1;
     hw = get_hwntype(hf);
     if (hw == NULL)
         hw = get_hwntype(-1);
     printf("%-9s Link encap:%s  ", ptr->name, hw->title);
     /* For some hardware types (eg Ash, ATM) we don't print the
        hardware address if it's null.  */
     if (hw->print != NULL
      && !(hw_null_address(hw, ptr->hwaddr) && hw->suppress_null_addr)
     ) {
         printf("HWaddr %s  ", hw->print((unsigned char *)ptr->hwaddr));
     }
 #ifdef IFF_PORTSEL
     if (ptr->flags & IFF_PORTSEL) {
         printf("Media:%s", if_port_text[ptr->map.port] /* [0] */);
         if (ptr->flags & IFF_AUTOMEDIA)
             printf("(auto)");
     }
 #endif
     bb_putchar('\n');
     if (ptr->has_ip) {
         printf("          %s addr:%s ", ap->name,
             ap->sprint(&ptr->addr, 1));
         if (ptr->flags & IFF_POINTOPOINT) {
             printf(" P-t-P:%s ", ap->sprint(&ptr->dstaddr, 1));
         }
         if (ptr->flags & IFF_BROADCAST) {
             printf(" Bcast:%s ", ap->sprint(&ptr->broadaddr, 1));
         }
         printf(" Mask:%s\n", ap->sprint(&ptr->netmask, 1));
     }
     ife_print6(ptr);
     printf("          ");
     /* DONT FORGET TO ADD THE FLAGS IN ife_print_short, too */
     if (ptr->flags == 0) {
         printf("[NO FLAGS] ");
     } else {
         static const char ife_print_flags_strs[] ALIGN1 =
             "UP\0"
             "BROADCAST\0"
             "DEBUG\0"
             "LOOPBACK\0"
             "POINTOPOINT\0"
             "NOTRAILERS\0"
             "RUNNING\0"
             "NOARP\0"
             "PROMISC\0"
             "ALLMULTI\0"
             "SLAVE\0"
             "MASTER\0"
             "MULTICAST\0"
 #ifdef HAVE_DYNAMIC
             "DYNAMIC\0"
 #endif
             ;
         static const unsigned short ife_print_flags_mask[] ALIGN2 = {
             IFF_UP,
             IFF_BROADCAST,
             IFF_DEBUG,
             IFF_LOOPBACK,
             IFF_POINTOPOINT,
             IFF_NOTRAILERS,
             IFF_RUNNING,
             IFF_NOARP,
             IFF_PROMISC,
             IFF_ALLMULTI,
             IFF_SLAVE,
             IFF_MASTER,
             IFF_MULTICAST
 #ifdef HAVE_DYNAMIC
             ,IFF_DYNAMIC
 #endif
         };
         const unsigned short *mask = ife_print_flags_mask;
         const char *str = ife_print_flags_strs;
         do {
             if (ptr->flags & *mask) {
                 printf("%s ", str);
             }
             mask++;
             str += strlen(str) + 1;
         } while (*str);
     }
     /* DONT FORGET TO ADD THE FLAGS IN ife_print_short */
     printf(" MTU:%d  Metric:%d", ptr->mtu, ptr->metric ? ptr->metric : 1);
 #if 0
 #ifdef SIOCSKEEPALIVE
     if (ptr->outfill || ptr->keepalive)
         printf("  Outfill:%d  Keepalive:%d", ptr->outfill, ptr->keepalive);
 #endif
 #endif
     bb_putchar('\n');
     /* If needed, display the interface statistics. */
     if (ptr->statistics_valid) {
         /* XXX: statistics are currently only printed for the primary address,
          *      not for the aliases, although strictly speaking they're shared
          *      by all addresses.
          */
         printf("          ");
         printf("RX packets:%llu errors:%lu dropped:%lu overruns:%lu frame:%lu\n",
             ptr->stats.rx_packets, ptr->stats.rx_errors,
             ptr->stats.rx_dropped, ptr->stats.rx_fifo_errors,
             ptr->stats.rx_frame_errors);
         if (can_compress)
             printf("             compressed:%lu\n",
                 ptr->stats.rx_compressed);
         printf("          ");
         printf("TX packets:%llu errors:%lu dropped:%lu overruns:%lu carrier:%lu\n",
             ptr->stats.tx_packets, ptr->stats.tx_errors,
             ptr->stats.tx_dropped, ptr->stats.tx_fifo_errors,
             ptr->stats.tx_carrier_errors);
         printf("          collisions:%lu ", ptr->stats.collisions);
         if (can_compress)
             printf("compressed:%lu ", ptr->stats.tx_compressed);
         if (ptr->tx_queue_len != -1)
             printf("txqueuelen:%d ", ptr->tx_queue_len);
         printf("\n          R");
         print_bytes_scaled(ptr->stats.rx_bytes, "  T");
         print_bytes_scaled(ptr->stats.tx_bytes, "\n");
     }
     if (ptr->map.irq || ptr->map.mem_start
      || ptr->map.dma || ptr->map.base_addr
     ) {
         printf("          ");
         if (ptr->map.irq)
             printf("Interrupt:%d ", ptr->map.irq);
         if (ptr->map.base_addr >= 0x100) /* Only print devices using it for I/O maps */
             printf("Base address:0x%lx ",
                 (unsigned long) ptr->map.base_addr);
         if (ptr->map.mem_start) {
             printf("Memory:%lx-%lx ", ptr->map.mem_start,
                 ptr->map.mem_end);
         }
         if (ptr->map.dma)
             printf("DMA chan:%x ", ptr->map.dma);
         bb_putchar('\n');
     }
     bb_putchar('\n');
 }
References interface::addr, ALIGN1, ALIGN2, ap, ARPHRD_CSLIP, ARPHRD_CSLIP6, bb_putchar(), interface::broadaddr, user_net_device_stats::collisions, interface::dstaddr, interface::flags, get_afntype(), get_hwntype(), interface::has_ip, hw, hw_null_address(), interface::hwaddr, ife_print6, IFF_DYNAMIC, interface::map, interface::metric, interface::mtu, interface::name, interface::netmask, NULL, print_bytes_scaled(), printf(), user_net_device_stats::rx_bytes, user_net_device_stats::rx_compressed, user_net_device_stats::rx_dropped, user_net_device_stats::rx_errors, user_net_device_stats::rx_fifo_errors, user_net_device_stats::rx_frame_errors, user_net_device_stats::rx_packets, sockaddr::sa_family, interface::statistics_valid, interface::stats, str, strlen(), user_net_device_stats::tx_bytes, user_net_device_stats::tx_carrier_errors, user_net_device_stats::tx_compressed, user_net_device_stats::tx_dropped, user_net_device_stats::tx_errors, user_net_device_stats::tx_fifo_errors, user_net_device_stats::tx_packets, interface::tx_queue_len, and interface::type.
Referenced by do_if_print().
INET_input()
static int FAST_FUNC INET_input (const char * bufp, struct sockaddr * sap) static
Definition at line 139 of file interface.c.
 {
     return INET_resolve(bufp, (struct sockaddr_in *) sap, 0);
 /*
     switch (type) {
     case 1:
         return (INET_getsock(bufp, sap));
     case 256:
         return (INET_resolve(bufp, (struct sockaddr_in *) sap, 1));
     default:
         return (INET_resolve(bufp, (struct sockaddr_in *) sap, 0));
     }
 */
 }
INET_sprint()
static const char* FAST_FUNC INET_sprint (struct sockaddr * sap, int numeric) static
Definition at line 89 of file interface.c.
 {
     if (sap->sa_family == 0xFFFF || sap->sa_family == 0)
         return "[NONE SET]";
     return auto_string(INET_rresolve((struct sockaddr_in *) sap, numeric, 0xffffff00));
 }
References auto_string(), INET_rresolve(), and sockaddr::sa_family.
print_bytes_scaled()
static void print_bytes_scaled (unsigned long long ull, const char * end) static
Definition at line 804 of file interface.c.
 {
     unsigned long long int_part;
     const char *ext;
     unsigned int frac_part;
     int i;
     frac_part = 0;
     ext = TRext;
     int_part = ull;
     i = 4;
     do {
         if (int_part >= 1024) {
             frac_part = ((((unsigned int) int_part) & (1024-1)) * 10) / 1024;
             int_part /= 1024;
             ext += 3;   /* KiB, MiB, GiB, TiB */
         }
         --i;
     } while (i);
     printf("X bytes:%llu (%llu.%u %sB)%s", ull, int_part, frac_part, ext, end);
 }
References end, i, and printf().
Referenced by ife_print().
procnetdev_version()
static int procnetdev_version (char * buf) static
Definition at line 496 of file interface.c.
 {
     if (strstr(buf, "compressed"))
         return 2;
     if (strstr(buf, "bytes"))
         return 1;
     return 0;
 }
References buf, and strstr().
Referenced by if_readlist_proc().
UNSPEC_print()
static char* FAST_FUNC UNSPEC_print (unsigned char * ptr) static
Definition at line 215 of file interface.c.
 {
     char *buff;
     char *pos;
     unsigned int i;
     buff = auto_string(xmalloc(sizeof(struct sockaddr) * 3 + 1));
     pos = buff;
     for (i = 0; i < sizeof(struct sockaddr); i++) {
         /* careful -- not every libc's sprintf returns # bytes written */
         sprintf(pos, "%02X-", *ptr++);
         pos += 3;
     }
     /* Erase trailing "-".  Works as long as sizeof(struct sockaddr) != 0 */
     *--pos = '\0';
     return buff;
 }
References auto_string(), i, pos, sprintf(), and xmalloc.
UNSPEC_sprint()
static const char* FAST_FUNC UNSPEC_sprint (struct sockaddr * sap, int numeric UNUSED_PARAM) static
Definition at line 234 of file interface.c.
 {
     if (sap->sa_family == 0xFFFF || sap->sa_family == 0)
         return "[NONE SET]";
     return UNSPEC_print((unsigned char *)sap->sa_data);
 }
Variable Documentation
aftypes
const struct aftype* const aftypes[] static
Initial value:
= {
    &inet_aftype,
    &unspec_aftype,
    NULL
}
Definition at line 250 of file interface.c.
Referenced by get_afntype(), and get_aftype().
ALIGN1
const char TRext [] ALIGN1 = "\0\0\0Ki\0Mi\0Gi\0Ti" static
Definition at line 802 of file interface.c.
Referenced by ife_print().
ALIGN_PTR
const struct hwtype* const hwtypes [] ALIGN_PTR static
Initial value:
= {
    "%n%llu%u%u%u%u%n%n%n%llu%u%u%u%u%u",
    "%llu%llu%u%u%u%u%n%n%llu%llu%u%u%u%u%u",
    "%llu%llu%u%u%u%u%u%u%llu%llu%u%u%u%u%u%u"
}
Definition at line 449 of file interface.c.
ether_hwtype
const struct hwtype ether_hwtype static
Initial value:
= {
    .name  = "ether",
    .title = "Ethernet",
    .type  = ARPHRD_ETHER,
    .alen  = ETH_ALEN,
    .print = ether_print,
    .input = in_ether
}
Definition at line 689 of file interface.c.
inet_aftype
const struct aftype inet_aftype static
Initial value:
= {
    .name   = "inet",
    .title  = "DARPA Internet",
    .af     = AF_INET,
    .alen   = 4,
    .sprint = INET_sprint,
    .input  = INET_input,
}
Definition at line 139 of file interface.c.
loop_hwtype
const struct hwtype loop_hwtype static
Initial value:
= {
    .name =     "loop",
    .title =    "Local Loopback",
    .type =     ARPHRD_LOOPBACK
}
Definition at line 657 of file interface.c.
ppp_hwtype
const struct hwtype ppp_hwtype static
Initial value:
= {
    .name =     "ppp",
    .title =    "Point-to-Point Protocol",
    .type =     ARPHRD_PPP
}
Definition at line 689 of file interface.c.
unspec_aftype
const struct aftype unspec_aftype static
Initial value:
= {
    .name   = "unspec",
    .title  = "UNSPEC",
    .af     = AF_UNSPEC,
    .alen   = 0,
    .print  = UNSPEC_print,
    .sprint = UNSPEC_sprint,
}
Definition at line 234 of file interface.c.
unspec_hwtype
const struct hwtype unspec_hwtype static
Initial value:
= {
    .name =     "unspec",
    .title =    "UNSPEC",
    .type =     -1,
    .print =    UNSPEC_print
}
Definition at line 657 of file interface.c.