Fennix Userspace: Userspace/apps/base/bash/lib/sh/strdup.c File Reference
strdup.c File Reference
#include <config.h>
#include <string.h>
#include <stdlib.h>
Functions
char * strdup (char *s) const
Function Documentation
strdup()
char* strdup (char * s) const
Definition at line 29 of file strdup.c.
 {
   size_t len;
   void *new;
   len = strlen (s) + 1;
   if ((new = malloc (len)) == NULL)
     return NULL;
   memcpy (new, s, len);
   return ((char *)new);
 }
References malloc, memcpy(), NULL, s, and strlen().
Referenced by _nl_find_domain(), add_new_file(), add_new_symbol(), CheckDirectoryHasIWAD(), conf_read_simple(), D_FindWADByName(), file_lookup(), get_current_dir_name(), getcwd(), glob(), if(), M_GetSaveGameDir(), M_StringDuplicate(), main(), message__new(), mitos(), ParseLine(), process_includes(), realpath(), set_binding_values(), SetVariable(), sym_lookup(), sym_validate_range(), tempnam(), vasprintf(), wstrdup(), and xstrdup().