Fennix Userspace: Userspace/mlibc/options/linux/generic/mntent-stubs.cpp File Reference
mntent-stubs.cpp File Reference
#include <mntent.h>
#include <stdio.h>
#include <string.h>
#include <bits/ensure.h>
Functions
FILE * setmntent (const char *name, const char *mode)
struct mntent * getmntent (FILE *)
int addmntent (FILE *f, const struct mntent *mnt)
int endmntent (FILE *f)
char * hasmntopt (const struct mntent *mnt, const char *opt)
struct mntent * getmntent_r (FILE *, struct mntent *, char *, int)
Function Documentation
addmntent()
int addmntent (FILE * f, const struct mntent * mnt)
Definition at line 16 of file mntent-stubs.cpp.
{
     if(fseek(f, 0, SEEK_END)) {
         return 1;
     }
     return fprintf(f, "%s\t%s\t%s\t%s\t%d\t%d\n",
         mnt->mnt_fsname, mnt->mnt_dir, mnt->mnt_type, mnt->mnt_opts,
         mnt->mnt_freq, mnt->mnt_passno) < 0;
 }
References fprintf(), fseek(), mntent::mnt_dir, mntent::mnt_freq, mntent::mnt_fsname, mntent::mnt_opts, mntent::mnt_passno, mntent::mnt_type, and SEEK_END.
endmntent()
int endmntent (FILE * f)
Definition at line 25 of file mntent-stubs.cpp.
{
     if(f) {
         fclose(f);
     }
     return 1;
 }
References fclose().
getmntent()
struct mntent* getmntent (FILE *)
Definition at line 11 of file mntent-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getmntent_r()
struct mntent* getmntent_r (FILE * , struct mntent * , char * , int)
Definition at line 36 of file mntent-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
hasmntopt()
char* hasmntopt (const struct mntent * mnt, const char * opt)
Definition at line 32 of file mntent-stubs.cpp.
{
     return strstr(mnt->mnt_opts, opt);
 }
References mntent::mnt_opts, and strstr().
setmntent()
FILE* setmntent (const char * name, const char * mode)
Definition at line 7 of file mntent-stubs.cpp.
{
     return fopen(name, mode);
 }
References fopen(), and name.