Fennix Userspace: Userspace/musl/src/math/cos.c File Reference
cos.c File Reference
#include "libm.h"
Functions
double cos (double x)
Function Documentation
cos()
double cos (double x)
Definition at line 45 of file cos.c.
 {
     double y[2];
     uint32_t ix;
     unsigned n;
     GET_HIGH_WORD(ix, x);
     ix &= 0x7fffffff;
     /* |x| ~< pi/4 */
     if (ix <= 0x3fe921fb) {
         if (ix < 0x3e46a09e) {  /* |x| < 2**-27 * sqrt(2) */
             /* raise inexact if x!=0 */
             FORCE_EVAL(x + 0x1p120f);
             return 1.0;
         }
         return __cos(x, 0);
     }
     /* cos(Inf or NaN) is NaN */
     if (ix >= 0x7ff00000)
         return x-x;
     /* argument reduction */
     n = __rem_pio2(x, y);
     switch (n&3) {
     case 0: return  __cos(y[0], y[1]);
     case 1: return -__sin(y[0], y[1], 1);
     case 2: return -__cos(y[0], y[1]);
     default:
         return  __sin(y[0], y[1], 1);
     }
 }
References __cos(), __rem_pio2(), __sin(), FORCE_EVAL, GET_HIGH_WORD, n, x, and y.