Fennix Userspace: Userspace/musl/src/stdlib/strtod.c File Reference
strtod.c File Reference
#include <stdlib.h>
#include "shgetc.h"
#include "floatscan.h"
#include "stdio_impl.h"
Functions
static long double strtox (const char *s, char **p, int prec)
float strtof (const char *restrict s, char **restrict p)
double strtod (const char *restrict s, char **restrict p)
long double strtold (const char *restrict s, char **restrict p)
Function Documentation
strtod()
double strtod (const char *restrict s, char **restrict p)
Definition at line 22 of file strtod.c.
 {
     return strtox(s, p, 1);
 }
References p, s, and strtox().
strtof()
float strtof (const char *restrict s, char **restrict p)
Definition at line 17 of file strtod.c.
 {
     return strtox(s, p, 0);
 }
References p, s, and strtox().
strtold()
long double strtold (const char *restrict s, char **restrict p)
Definition at line 27 of file strtod.c.
 {
     return strtox(s, p, 2);
 }
References p, s, and strtox().
strtox()
static long double strtox (const char * s, char ** p, int prec) static
Definition at line 6 of file strtod.c.
 {
     FILE f;
     sh_fromstring(&f, s);
     shlim(&f, 0);
     long double y = __floatscan(&f, prec, 1);
     off_t cnt = shcnt(&f);
     if (p) *p = cnt ? (char *)s + cnt : (char *)s;
     return y;
 }
References __floatscan(), cnt, f, off_t, p, prec, s, sh_fromstring, shcnt, shlim, and y.
Referenced by strtod(), strtof(), and strtold().