Fennix: Userspace/apps/base/busybox/libbb/xfuncs_printf.c File Reference
xfuncs_printf.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC bb_die_memory_exhausted (void)
void *FAST_FUNC malloc_or_warn (size_t size)
void *FAST_FUNC xmalloc (size_t size)
void *FAST_FUNC xrealloc (void *ptr, size_t size)
void *FAST_FUNC xzalloc (size_t size)
char *FAST_FUNC xstrdup (const char *s)
char *FAST_FUNC xstrndup (const char *s, size_t n)
void *FAST_FUNC xmemdup (const void *s, size_t n)
void *FAST_FUNC mmap_read (int fd, size_t size)
void *FAST_FUNC mmap_anon (size_t size)
void *FAST_FUNC xmmap_anon (size_t size)
FILE *FAST_FUNC xfopen (const char *path, const char *mode)
int FAST_FUNC xopen3 (const char *pathname, int flags, int mode)
int FAST_FUNC xopen (const char *pathname, int flags)
int FAST_FUNC open3_or_warn (const char *pathname, int flags, int mode)
int FAST_FUNC open_or_warn (const char *pathname, int flags)
int FAST_FUNC xopen_nonblocking (const char *pathname)
int FAST_FUNC xopen_as_uid_gid (const char *pathname, int flags, uid_t u, gid_t g)
void FAST_FUNC xunlink (const char *pathname)
void FAST_FUNC xrename (const char *oldpath, const char *newpath)
int FAST_FUNC rename_or_warn (const char *oldpath, const char *newpath)
void FAST_FUNC xpipe (int *filedes)
void FAST_FUNC xdup2 (int from, int to)
void FAST_FUNC xmove_fd (int from, int to)
void FAST_FUNC xwrite (int fd, const void *buf, size_t count)
void FAST_FUNC xwrite_str (int fd, const char *str)
void FAST_FUNC xclose (int fd)
off_t FAST_FUNC xlseek (int fd, off_t offset, int whence)
int FAST_FUNC xmkstemp (char *template)
void FAST_FUNC die_if_ferror (FILE *fp, const char *fn)
void FAST_FUNC die_if_ferror_stdout (void)
int FAST_FUNC fflush_all (void)
int FAST_FUNC bb_putchar (int ch)
int FAST_FUNC fputs_stdout (const char *s)
void FAST_FUNC xprint_and_close_file (FILE *file)
char *FAST_FUNC xasprintf (const char *format,...)
void FAST_FUNC xsetenv (const char *key, const char *value)
void FAST_FUNC bb_unsetenv (const char *var)
void FAST_FUNC bb_unsetenv_and_free (char *var)
void FAST_FUNC xsetgid (gid_t gid)
void FAST_FUNC xsetuid (uid_t uid)
void FAST_FUNC xsetegid (gid_t egid)
void FAST_FUNC xseteuid (uid_t euid)
int FAST_FUNC chdir_or_warn (const char *path)
void FAST_FUNC xchdir (const char *path)
void FAST_FUNC xfchdir (int fd)
void FAST_FUNC xchroot (const char *path)
DIR *FAST_FUNC warn_opendir (const char *path)
DIR *FAST_FUNC xopendir (const char *path)
int FAST_FUNC xsocket (int domain, int type, int protocol)
void FAST_FUNC xbind (int sockfd, struct sockaddr *my_addr, socklen_t addrlen)
void FAST_FUNC xlisten (int s, int backlog)
ssize_t FAST_FUNC xsendto (int s, const void *buf, size_t len, const struct sockaddr *to, socklen_t tolen)
void FAST_FUNC xstat (const char *name, struct stat *stat_buf)
void FAST_FUNC xfstat (int fd, struct stat *stat_buf, const char *errmsg)
int FAST_FUNC ioctl_or_perror_and_die (int fd, unsigned request, void *argp, const char *fmt,...)
int FAST_FUNC ioctl_or_perror (int fd, unsigned request, void *argp, const char *fmt,...)
int FAST_FUNC bb_ioctl_or_warn (int fd, unsigned request, void *argp)
int FAST_FUNC bb_xioctl (int fd, unsigned request, void *argp)
char *FAST_FUNC xmalloc_ttyname (int fd)
void FAST_FUNC generate_uuid (uint8_t *buf)
void FAST_FUNC xvfork_parent_waits_and_exits (void)
int FAST_FUNC wait_for_exitstatus (pid_t pid)
void FAST_FUNC xsettimeofday (const struct timeval *tv)
void FAST_FUNC xgettimeofday (struct timeval *tv)
Function Documentation
bb_die_memory_exhausted()
void FAST_FUNC bb_die_memory_exhausted (void)
Definition at line 28 of file xfuncs_printf.c.
 {
     bb_simple_error_msg_and_die(bb_msg_memory_exhausted);
 }
References bb_simple_error_msg_and_die().
Referenced by bb_get_chunk_from_file(), download_one_url(), fsrealloc(), open_socket(), perform_glob(), xasprintf(), xfdopen_helper(), xmalloc(), xmmap_anon(), xputenv(), xrealloc(), xsetenv(), xstrdup(), and xstrndup().
bb_ioctl_or_warn()
int FAST_FUNC bb_ioctl_or_warn (int fd, unsigned request, void * argp)
Definition at line 599 of file xfuncs_printf.c.
 {
     int ret;
     ret = ioctl(fd, request, argp);
     if (ret < 0)
         bb_perror_msg("ioctl %#x failed", request);
     return ret;
 }
References bb_perror_msg(), fd, and ioctl().
bb_putchar()
int FAST_FUNC bb_putchar (int ch)
Definition at line 313 of file xfuncs_printf.c.
 {
     return putchar(ch);
 }
References putchar.
Referenced by ask(), bb_ask_noecho(), cal_main(), cbq_print_opt(), cleanup(), colon(), common_traceroute_main(), conspy_main(), depmod_main(), display(), display_boolean(), display_process_list(), display_recoverable(), display_uuid_cache(), dmesg_main(), do_show(), do_stat(), do_tunnels_list(), execute(), factorize(), fatattr_main(), fdisk_main(), fileAction(), flash_eraseall_main(), fuser_main(), generate_output(), get_input_line(), getsebool_main(), header_verbose_list(), hostname_main(), id_main(), ife_print(), ifupdown_main(), iostat_main(), ipcs_main(), less_gets(), list_attributes(), lpqr_main(), lsattr_dir_proc(), mkfs_ext2_main(), number_process(), pidof_main(), powertop_main(), print_addrinfo(), print_base(), print_C_style(), print_class(), print_formatted(), print_inet_line(), print_link_flags(), print_linkinfo(), print_neigh(), print_qdisc(), print_route(), print_rule(), print_sem(), progress_newline(), restore(), scan_and_display_dirs_recur(), screen_dump(), sendmail_main(), seq_main(), server_print(), set_cursor(), show_timerstats(), status_print(), strings_main(), summarize(), top_main(), ttysize_main(), tunctl_main(), unix_do_one(), uuencode_main(), warn_geometry(), who_main(), wrapf(), and write_irqcpu_stats().
bb_unsetenv()
void FAST_FUNC bb_unsetenv (const char * var)
Definition at line 361 of file xfuncs_printf.c.
 {
     char onstack[128 - 16]; /* smaller stack setup code on x86 */
     char *tp;
     tp = strchr(var, '=');
     if (tp) {
         /* In case var was putenv'ed, we can't replace '='
          * with NUL and unsetenv(var) - it won't work,
          * env is modified by the replacement, unsetenv
          * sees "VAR" instead of "VAR=VAL" and does not remove it!
          * Horror :(
          */
         unsigned sz = tp - var;
         if (sz < sizeof(onstack)) {
             ((char*)mempcpy(onstack, var, sz))[0] = '\0';
             tp = NULL;
             var = onstack;
         } else {
             /* unlikely: very long var name */
             var = tp = xstrndup(var, sz);
         }
     }
     unsetenv(var);
     free(tp);
 }
References free, mempcpy(), NULL, strchr(), tp, unsetenv(), and xstrndup().
Referenced by bb_unsetenv_and_free(), remove_nested_vars(), and uevent_main().
bb_unsetenv_and_free()
void FAST_FUNC bb_unsetenv_and_free (char * var)
Definition at line 388 of file xfuncs_printf.c.
 {
     bb_unsetenv(var);
     free(var);
 }
References bb_unsetenv(), and free.
Referenced by d6_run_script(), data_extract_to_command(), fileAction(), make_device(), optitem_unset_env_and_free(), run(), run_script(), safe_setenv(), and undo_xsetenv().
bb_xioctl()
int FAST_FUNC bb_xioctl (int fd, unsigned request, void * argp)
Definition at line 608 of file xfuncs_printf.c.
 {
     int ret;
     ret = ioctl(fd, request, argp);
     if (ret < 0)
         bb_perror_msg_and_die("ioctl %#x failed", request);
     return ret;
 }
References bb_perror_msg_and_die(), fd, and ioctl().
chdir_or_warn()
int FAST_FUNC chdir_or_warn (const char * path)
Definition at line 418 of file xfuncs_printf.c.
 {
     int r = chdir(path);
     if (r != 0)
         bb_perror_msg("can't change directory to '%s'", path);
     return r;
 }
References bb_perror_msg(), and chdir().
Referenced by change_user(), setup_environment(), and xchdir().
die_if_ferror()
void FAST_FUNC die_if_ferror (FILE * fp, const char * fn)
Definition at line 293 of file xfuncs_printf.c.
 {
     if (ferror(fp)) {
         /* ferror doesn't set useful errno */
         bb_error_msg_and_die("%s: I/O error", fn);
     }
 }
References bb_error_msg_and_die(), and ferror.
Referenced by cmp_main(), die_if_ferror_stdout(), tee_main(), and uniq_main().
die_if_ferror_stdout()
void FAST_FUNC die_if_ferror_stdout (void)
Definition at line 302 of file xfuncs_printf.c.
 {
     die_if_ferror(stdout, bb_msg_standard_output);
 }
References die_if_ferror(), and stdout.
Referenced by head_main(), and more_main().
fflush_all()
int FAST_FUNC fflush_all (void)
Definition at line 307 of file xfuncs_printf.c.
 {
     return fflush(NULL);
 }
References fflush(), and NULL.
Referenced by alarm_handler(), alarm_intr(), ask(), bb_ask_noecho(), bb_ask_y_confirmation_FILE(), bb_verror_msg(), cmp_main(), common_traceroute_main(), conspy_main(), cookmode(), dirname_main(), display_process_list(), do_logging(), doit(), edit_file(), evaltree(), evaluate(), exec_builtin(), flush_stdout_stderr(), getch_nowait(), hexedit_main(), hostid_main(), hush_exit(), launch_helper(), logname_main(), logread_main(), make_new_session(), more_main(), motd(), my_fgets80(), mysleep(), patch_main(), print_login_issue(), print_login_prompt(), progress(), pwd_main(), read_line_input(), readit(), recv_pack(), reset_main(), restore(), restore_term(), rtcwake_main(), run_pipe(), send_mail_command(), seq_main(), set_tty_cooked(), shell_builtin_read(), show_progress(), show_status_line(), spawn(), spawn_and_wait(), svlogd_main(), watch_main(), whoami_main(), xprint_and_close_file(), and xvfork_parent_waits_and_exits().
fputs_stdout()
int FAST_FUNC fputs_stdout (const char * s)
Definition at line 318 of file xfuncs_printf.c.
 {
     return fputs(s, stdout);
 }
References fputs, s, and stdout.
Referenced by bb_ask_noecho(), bb_show_usage(), display(), display_process_list(), dump_hexl_mode_trailer(), dump_strings(), dumpleases_main(), httpd_main(), id_main(), logread_main(), paste_files(), paste_files_separate(), powertop_main(), print_addrinfo(), print_ascii(), print_linkinfo(), print_login_issue(), print_login_prompt(), print_name(), print_named_ascii(), print_numbered_lines(), print_rule(), printLines(), putcsi(), read_line_input(), rev_main(), strings_main(), tree_print(), wrapf(), write1(), and yes_main().
generate_uuid()
void FAST_FUNC generate_uuid (uint8_t * buf)
Definition at line 628 of file xfuncs_printf.c.
 {
     /* http://www.ietf.org/rfc/rfc4122.txt
      *  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
      * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      * |                          time_low                             |
      * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      * |       time_mid                |         time_hi_and_version   |
      * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      * |clk_seq_and_variant            |         node (0-1)            |
      * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      * |                         node (2-5)                            |
      * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
      * IOW, uuid has this layout:
      * uint32_t time_low (big endian)
      * uint16_t time_mid (big endian)
      * uint16_t time_hi_and_version (big endian)
      *  version is a 4-bit field:
      *   1 Time-based
      *   2 DCE Security, with embedded POSIX UIDs
      *   3 Name-based (MD5)
      *   4 Randomly generated
      *   5 Name-based (SHA-1)
      * uint16_t clk_seq_and_variant (big endian)
      *  variant is a 3-bit field:
      *   0xx Reserved, NCS backward compatibility
      *   10x The variant specified in rfc4122
      *   110 Reserved, Microsoft backward compatibility
      *   111 Reserved for future definition
      * uint8_t node[6]
      *
      * For version 4, these bits are set/cleared:
      * time_hi_and_version & 0x0fff | 0x4000
      * clk_seq_and_variant & 0x3fff | 0x8000
      */
     pid_t pid;
     int i;
     open_read_close("/dev/urandom", buf, 16);
     /* Paranoia. /dev/urandom may be missing.
      * rand() is guaranteed to generate at least [0, 2^15) range,
      * but lowest bits in some libc are not so "random".
      */
     srand(monotonic_us()); /* pulls in printf */
     pid = getpid();
     while (1) {
         for (i = 0; i < 16; i++)
             buf[i] ^= rand() >> 5;
         if (pid == 0)
             break;
         srand(pid);
         pid = 0;
     }
     /* version = 4 */
     buf[4 + 2    ] = (buf[4 + 2    ] & 0x0f) | 0x40;
     /* variant = 10x */
     buf[4 + 2 + 2] = (buf[4 + 2 + 2] & 0x3f) | 0x80;
 }
References buf, getpid(), i, monotonic_us(), open_read_close(), pid, rand(), and srand().
Referenced by mkfs_ext2_main(), mkfs_reiser_main(), and mkswap_main().
ioctl_or_perror()
int FAST_FUNC ioctl_or_perror (int fd, unsigned request, void * argp, const char * fmt, ...)
Definition at line 566 of file xfuncs_printf.c.
 {
     va_list p;
     int ret = ioctl(fd, request, argp);
     if (ret < 0) {
         va_start(p, fmt);
         bb_verror_msg(fmt, p, strerror(errno));
         va_end(p);
     }
     return ret;
 }
References bb_verror_msg(), errno, fd, ioctl(), p, strerror(), va_end, and va_start.
ioctl_or_perror_and_die()
int FAST_FUNC ioctl_or_perror_and_die (int fd, unsigned request, void * argp, const char * fmt, ...)
Definition at line 550 of file xfuncs_printf.c.
 {
     int ret;
     va_list p;
     ret = ioctl(fd, request, argp);
     if (ret < 0) {
         va_start(p, fmt);
         bb_verror_msg(fmt, p, strerror(errno));
         /* xfunc_die can actually longjmp, so be nice */
         va_end(p);
         xfunc_die();
     }
     return ret;
 }
References bb_verror_msg(), errno, fd, ioctl(), p, strerror(), va_end, va_start, and xfunc_die().
malloc_or_warn()
void* FAST_FUNC malloc_or_warn (size_t size)
Definition at line 39 of file xfuncs_printf.c.
 {
     void *ptr = malloc(size);
     if (ptr == NULL && size != 0)
         bb_simple_error_msg(bb_msg_memory_exhausted);
     return ptr;
 }
References bb_simple_error_msg(), malloc, NULL, and size.
Referenced by start_bunzip(), and unpack_bz2_data().
mmap_anon()
void* FAST_FUNC mmap_anon (size_t size)
Definition at line 116 of file xfuncs_printf.c.
 {
     return mmap(NULL, size,
             PROT_READ | PROT_WRITE,
             MAP_PRIVATE | MAP_ANONYMOUS,
             /* ignored: */ -1, 0);
 }
References MAP_ANONYMOUS, MAP_PRIVATE, mmap(), NULL, PROT_READ, PROT_WRITE, and size.
Referenced by bb_full_fd_action(), and xmmap_anon().
mmap_read()
void* FAST_FUNC mmap_read (int fd, size_t size)
Definition at line 111 of file xfuncs_printf.c.
 {
     return mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, 0);
 }
References fd, MAP_PRIVATE, mmap(), NULL, PROT_READ, and size.
Referenced by rpm_gettags().
open3_or_warn()
int FAST_FUNC open3_or_warn (const char * pathname, int flags, int mode)
Definition at line 161 of file xfuncs_printf.c.
 {
     int ret;
     ret = open(pathname, flags, mode);
     if (ret < 0) {
         bb_perror_msg("can't open '%s'", pathname);
     }
     return ret;
 }
References bb_perror_msg(), flags, and open().
Referenced by copy_file(), lpd_main(), open_or_warn(), and open_to_or_warn().
open_or_warn()
int FAST_FUNC open_or_warn (const char * pathname, int flags)
Definition at line 173 of file xfuncs_printf.c.
 {
     return open3_or_warn(pathname, flags, 0666);
 }
References flags, and open3_or_warn().
Referenced by change_attributes(), copy_file(), cttyhack_main(), diffreg(), iproute_flush_cache(), list_attributes(), microcom_main(), open_or_warn_stdin(), processorstart(), read_leases(), readahead_main(), reopen_logfile_to_stderr(), setup_redirects(), switch_root_main(), and write_leases().
rename_or_warn()
int FAST_FUNC rename_or_warn (const char * oldpath, const char * newpath)
Definition at line 216 of file xfuncs_printf.c.
 {
     int n = rename(oldpath, newpath);
     if (n)
         bb_perror_msg("can't move '%s' to '%s'", oldpath, newpath);
     return n;
 }
References bb_perror_msg(), n, and rename().
Referenced by popmaildir_main(), and update_status().
wait_for_exitstatus()
int FAST_FUNC wait_for_exitstatus (pid_t pid)
Definition at line 717 of file xfuncs_printf.c.
 {
     int exit_status, n;
     n = safe_waitpid(pid, &exit_status, 0);
     if (n < 0)
         bb_simple_perror_msg_and_die("waitpid");
     return exit_status;
 }
References bb_simple_perror_msg_and_die(), exit_status, n, pid, and safe_waitpid().
Referenced by data_extract_to_command(), login_main(), unshare_main(), and xvfork_parent_waits_and_exits().
warn_opendir()
DIR* FAST_FUNC warn_opendir (const char * path)
Definition at line 446 of file xfuncs_printf.c.
 {
     DIR *dp;
     dp = opendir(path);
     if (!dp)
         bb_perror_msg("can't open '%s'", path);
     return dp;
 }
References bb_perror_msg(), and opendir().
Referenced by dir_operation(), du(), and scan_one_dir().
xasprintf()
char* FAST_FUNC xasprintf (const char * format, ...)
Definition at line 337 of file xfuncs_printf.c.
 {
     va_list p;
     int r;
     char *string_ptr;
     va_start(p, format);
     r = vasprintf(&string_ptr, format, p);
     va_end(p);
     if (r < 0)
         bb_die_memory_exhausted();
     return string_ptr;
 }
References bb_die_memory_exhausted(), format(), p, va_end, va_start, and vasprintf().
xbind()
void FAST_FUNC xbind (int sockfd, struct sockaddr * my_addr, socklen_t addrlen)
Definition at line 493 of file xfuncs_printf.c.
 {
     if (bind(sockfd, my_addr, addrlen)) bb_simple_perror_msg_and_die("bind");
 }
References bb_simple_perror_msg_and_die(), bind(), and sockfd.
Referenced by bind_for_passive_mode(), create_and_bind_or_die(), create_socket(), d6_listen_socket(), d6_raw_socket(), dnsd_main(), get_address(), nc_main(), send_query_to_peer(), tcpudpsvd_main(), traceroute_init(), udhcp_listen_socket(), udhcp_raw_socket(), and xrtnl_open().
xchdir()
void FAST_FUNC xchdir (const char * path)
Definition at line 426 of file xfuncs_printf.c.
 {
     if (chdir_or_warn(path) != 0)
         xfunc_die();
 }
References chdir_or_warn(), and xfunc_die().
Referenced by acpid_main(), bb_daemonize_or_rexec(), brctl_main(), change_user(), crond_main(), crontab_main(), depmod_main(), devfsd_main(), dpkg_deb_main(), edir(), ftpd_main(), httpd_main(), init_main(), load_firmware(), lpd_main(), lsscsi_main(), make_tempdir(), mdev_main(), modprobe_main(), nmeter_main(), parse_conf(), popmaildir_main(), rescan_crontab_dir(), rtcwake_main(), runsv_main(), setup_environment(), smemcap_main(), startservice(), switch_root_main(), sysctl_handle_preload_file(), sysctl_main(), tar_main(), top_main(), tree_print(), unzip_main(), and xchroot().
xchroot()
void FAST_FUNC xchroot (const char * path)
Definition at line 438 of file xfuncs_printf.c.
 {
     if (chroot(path))
         bb_perror_msg_and_die("can't change root directory to '%s'", path);
     xchdir("/");
 }
References bb_perror_msg_and_die(), chroot(), and xchdir().
Referenced by chpasswd_main(), chpst_main(), chroot_main(), nsenter_main(), and switch_root_main().
xclose()
void FAST_FUNC xclose (int fd)
Definition at line 268 of file xfuncs_printf.c.
 {
     if (close(fd))
         bb_simple_perror_msg_and_die("close failed");
 }
References bb_simple_perror_msg_and_die(), close(), and fd.
Referenced by bbunpack(), download_one_url(), finish_oldfile(), mkfs_ext2_main(), mkfs_reiser_main(), patch_main(), replace_tempfile(), shred_main(), touch_main(), truncate_main(), tune2fs_main(), and wget_main().
xdup2()
void FAST_FUNC xdup2 (int from, int to)
Definition at line 230 of file xfuncs_printf.c.
 {
     if (dup2(from, to) != to)
         bb_simple_perror_msg_and_die("can't duplicate file descriptor");
         //      " %d to %d", from, to);
 }
References bb_simple_perror_msg_and_die(), and dup2().
Referenced by acpid_main(), bb_daemonize_or_rexec(), data_extract_to_command(), getty_main(), inetd_main(), lpd_main(), make_new_session(), mini_httpd_nommu(), nc_main(), openvt_main(), script_main(), sendmail_main(), setup_redirects(), start_shell_in_child(), startservice(), switch_root_main(), tcpudpsvd_main(), time_main(), unzip_main(), vlock_main(), wget_main(), xargs_exec(), and xmove_fd().
xfchdir()
void FAST_FUNC xfchdir (int fd)
Definition at line 432 of file xfuncs_printf.c.
 {
     if (fchdir(fd))
         bb_simple_perror_msg_and_die("fchdir");
 }
References bb_simple_perror_msg_and_die(), fchdir(), and fd.
Referenced by edir(), nsenter_main(), seedrng_main(), and sysctl_main().
xfopen()
FILE* FAST_FUNC xfopen (const char * path, const char * mode)
Definition at line 134 of file xfuncs_printf.c.
 {
     FILE *fp = fopen(path, mode);
     if (fp == NULL)
         bb_perror_msg_and_die("can't open '%s'", path);
     return fp;
 }
References bb_perror_msg_and_die(), fopen(), and NULL.
Referenced by evaluate(), xfopen_for_read(), and xfopen_for_write().
xfstat()
void FAST_FUNC xfstat (int fd, struct stat * stat_buf, const char * errmsg)
Definition at line 525 of file xfuncs_printf.c.
 {
     /* errmsg is usually a file name, but not always:
      * xfstat may be called in a spot where file name is no longer
      * available, and caller may give e.g. "can't stat input file" string.
      */
     if (fstat(fd, stat_buf))
         bb_simple_perror_msg_and_die(errmsg);
 }
References bb_simple_perror_msg_and_die(), errmsg(), fd, and fstat().
Referenced by add_remove_shell_main(), convert(), do_skip(), mesg_main(), mkfs_ext2_main(), mkfs_minix_main(), mkfs_reiser_main(), mkfs_vfat_main(), and ubi_tools_main().
xgettimeofday()
void FAST_FUNC xgettimeofday (struct timeval * tv)
Definition at line 733 of file xfuncs_printf.c.
 {
 #if 0
     if (gettimeofday(tv, NULL))
         bb_simple_perror_msg_and_die("gettimeofday");
 #else
     /* Never fails on Linux */
     gettimeofday(tv, NULL);
 #endif
 }
References bb_simple_perror_msg_and_die(), gettimeofday(), and NULL.
Referenced by curtime(), fmt_time_bernstein_25(), fmt_time_human_30nul(), from_sys_clock(), get_local_var_value(), gettime1900d(), gettimeofday_ns(), monotonic_ms(), monotonic_ns(), monotonic_us(), nmeter_main(), read_rtc(), script_main(), step_time(), timestamp_and_log(), and ts_main().
xlisten()
void FAST_FUNC xlisten (int s, int backlog)
Definition at line 499 of file xfuncs_printf.c.
 {
     if (listen(s, backlog)) bb_simple_perror_msg_and_die("listen");
 }
References bb_simple_perror_msg_and_die(), listen(), and s.
Referenced by bind_for_passive_mode(), dolisten(), fakeidentd_main(), nc_main(), openServer(), tcpudpsvd_main(), and telnetd_main().
xlseek()
off_t FAST_FUNC xlseek (int fd, off_t offset, int whence)
Definition at line 275 of file xfuncs_printf.c.
 {
     off_t off = lseek(fd, offset, whence);
     if (off == (off_t)-1) {
         bb_perror_msg_and_die("lseek(%"OFF_FMT"u, %d)", offset, whence);
     }
     return off;
 }
References bb_perror_msg_and_die(), fd, lseek(), off, OFF_FMT, off_t, and offset.
Referenced by bad_zone(), check_blocks(), crontab_main(), dd_main(), diffreg(), do_check(), download_one_url(), flash_eraseall_main(), flashcp_main(), get_volume_size_in_bytes(), handle_retr(), hexedit_main(), last_main(), lpqr_main(), mkfs_reiser_main(), mkfs_vfat_main(), mkswap_main(), nandwrite_main(), PUT(), read_block(), read_superblock(), readahead_main(), reset_beg_range_to_zero(), rpm_gettags(), shred_main(), tail_main(), timeout_handler(), tune2fs_main(), unzip_main(), volname_main(), wait_for_seqfile(), write_block(), write_superblock(), and write_tables().
xmalloc()
void* FAST_FUNC xmalloc (size_t size)
Definition at line 48 of file xfuncs_printf.c.
 {
     void *ptr = malloc(size);
     if (ptr == NULL && size != 0)
         bb_die_memory_exhausted();
     return ptr;
 }
References bb_die_memory_exhausted(), malloc, NULL, and size.
Referenced by xmemdup(), and xzalloc().
xmalloc_ttyname()
char* FAST_FUNC xmalloc_ttyname (int fd)
Definition at line 619 of file xfuncs_printf.c.
 {
     char buf[128];
     int r = ttyname_r(fd, buf, sizeof(buf) - 1);
     if (r)
         return NULL;
     return xstrdup(buf);
 }
References buf, fd, NULL, ttyname_r(), and xstrdup().
Referenced by display_verbose(), less_main(), login_main(), open_tty(), su_main(), and tty_main().
xmemdup()
void* FAST_FUNC xmemdup (const void * s, size_t n)
Definition at line 106 of file xfuncs_printf.c.
 {
     return memcpy(xmalloc(n), s, n);
 }
References memcpy, n, s, and xmalloc().
Referenced by d6_copy_option(), forkchild(), last_main(), procps_scan(), and traceroute_init().
xmkstemp()
int FAST_FUNC xmkstemp (char * template)
Definition at line 284 of file xfuncs_printf.c.
 {
     int fd = mkstemp(template);
     if (fd < 0)
         bb_perror_msg_and_die("can't create temp file '%s'", template);
     return fd;
 }
References bb_perror_msg_and_die(), fd, and mkstemp().
Referenced by convert(), diffreg(), lpqr_main(), patch_main(), and sed_main().
xmmap_anon()
void* FAST_FUNC xmmap_anon (size_t size)
Definition at line 124 of file xfuncs_printf.c.
 {
     void *p = mmap_anon(size);
     if (p == MAP_FAILED)
         bb_die_memory_exhausted();
     return p;
 }
References bb_die_memory_exhausted(), MAP_FAILED, mmap_anon(), p, and size.
Referenced by alloc_buf(), and uevent_main().
xmove_fd()
void FAST_FUNC xmove_fd (int from, int to)
Definition at line 238 of file xfuncs_printf.c.
 {
     if (from == to)
         return;
     xdup2(from, to);
     close(from);
 }
References close(), and xdup2().
Referenced by acpid_main(), add_remove_shell_main(), arp_main(), bbunpack(), close_dev_fd(), console_init(), create_icmp_socket(), cryptpw_main(), dd_main(), do_syslogd(), doexec(), dolisten(), eject_main(), fork_transformer(), fsck_minix_main(), get_boot(), ifplugd_main(), inetd_main(), klogd_open(), launch_helper(), mini_httpd_nommu(), mkfs_ext2_main(), mkfs_minix_main(), nandwrite_main(), nc_main(), open_file_and_read_lines(), open_mdev_log(), open_to_or_warn(), parse(), patch_main(), popen_ls(), processorstart(), reopen_logfile_to_stderr(), restore_redirects(), run_pipe(), sendmail_main(), setup_heredoc(), shuf_main(), slattach_main(), sort_main(), split_main(), stty_main(), switch_root_main(), tail_main(), tcpudpsvd_main(), telnet_main(), tls_run_copy_loop(), traceroute_init(), ubi_tools_main(), udhcp_sp_setup(), uniq_main(), unzip_main(), vlock_main(), watchdog_open(), and xargs_main().
xopen()
int FAST_FUNC xopen (const char * pathname, int flags)
Definition at line 155 of file xfuncs_printf.c.
 {
     return xopen3(pathname, flags, 0666);
 }
References flags, and xopen3().
Referenced by acpid_main(), ar_main(), bb_daemonize_or_rexec(), blkdiscard_main(), blockdev_main(), chat_main(), close_dev_fd(), conspy_main(), dd_main(), devfsd_main(), devmem_main(), diffreg(), do_logging(), download_one_url(), dumpleases_main(), edir(), fatattr_main(), fb_open(), fbset_main(), fdformat_main(), fdisk_main(), flash_eraseall_main(), flash_lock_unlock_main(), flashcp_main(), freeramdisk_main(), fsck_minix_main(), fsfreeze_main(), ftpd_main(), getty_main(), hexedit_main(), i2c_dev_open(), init_archive_deb_ar(), klogd_open(), last_main(), losetup_main(), lpd_main(), lpqr_main(), make_new_session(), mkfs_ext2_main(), mkfs_minix_main(), mkfs_reiser_main(), mkfs_vfat_main(), mkswap_main(), mt_main(), nandwrite_main(), nbdclient_main(), nc_main(), nohup_main(), nsenter_main(), open_by_path_or_target(), open_control(), open_file_and_read_lines(), open_loop_on_busy(), open_tty(), openvt_main(), partprobe_main(), patch_main(), popen_ls(), processorstart(), raidautorun_main(), read_new_seed(), readfile_z(), readprofile_main(), resume_main(), rpm_gettags(), rtc_xopen(), run_pipe(), runsv_main(), rx_main(), screen_read_close(), script_main(), scriptreplay_main(), seed_from_file_if_exists(), seedrng_main(), setconsole_main(), setlogcons_main(), shred_main(), shuf_main(), slattach_main(), sort_main(), split_main(), start_shell_in_child(), sulogin_main(), svlogd_main(), sysctl_main(), tar_main(), time_main(), tls_run_copy_loop(), tsort_main(), tunctl_main(), tune2fs_main(), ubi_tools_main(), ubirename_main(), uniq_main(), unzip_main(), uuencode_main(), vlock_main(), volname_main(), watch_main(), watchdog_open(), wget_main(), xargs_main(), xopen_as_uid_gid(), xopen_nonblocking(), and xopen_xwrite_close().
xopen3()
int FAST_FUNC xopen3 (const char * pathname, int flags, int mode)
Definition at line 143 of file xfuncs_printf.c.
 {
     int ret;
     ret = open(pathname, flags, mode);
     if (ret < 0) {
         bb_perror_msg_and_die("can't open '%s'", pathname);
     }
     return ret;
 }
References bb_perror_msg_and_die(), flags, and open().
Referenced by add_remove_shell_main(), crontab_main(), data_extract_all(), fallocate_main(), nohup_main(), runsv_main(), seedrng_main(), unzip_main(), and xopen().
xopen_as_uid_gid()
int FAST_FUNC xopen_as_uid_gid (const char * pathname, int flags, uid_t u, gid_t g)
Definition at line 187 of file xfuncs_printf.c.
 {
     int fd;
     uid_t old_euid = geteuid();
     gid_t old_egid = getegid();
     xsetegid(g);
     xseteuid(u);
     fd = xopen(pathname, flags);
     xseteuid(old_euid);
     xsetegid(old_egid);
     return fd;
 }
References fd, flags, g, getegid, geteuid, xopen(), xsetegid(), and xseteuid().
Referenced by crontab_main(), and wall_main().
xopen_nonblocking()
int FAST_FUNC xopen_nonblocking (const char * pathname)
Definition at line 182 of file xfuncs_printf.c.
 {
     return xopen(pathname, O_RDONLY | O_NONBLOCK);
 }
References O_NONBLOCK, O_RDONLY, and xopen().
Referenced by eject_main(), fstrim_main(), kbd_mode_main(), and stty_main().
xopendir()
DIR* FAST_FUNC xopendir (const char * path)
Definition at line 457 of file xfuncs_printf.c.
 {
     DIR *dp;
     dp = opendir(path);
     if (!dp)
         bb_perror_msg_and_die("can't open '%s'", path);
     return dp;
 }
References bb_perror_msg_and_die(), and opendir().
Referenced by alloc_procps_scan(), brctl_main(), do_procinit(), edir(), lsscsi_main(), read_interfaces(), and smemcap_main().
xpipe()
void FAST_FUNC xpipe (int * filedes)
Definition at line 224 of file xfuncs_printf.c.
 {
     if (pipe(filedes))
         bb_simple_perror_msg_and_die("can't create pipe");
 }
References bb_simple_perror_msg_and_die(), and pipe().
Referenced by data_extract_to_command(), and parse().
xprint_and_close_file()
void FAST_FUNC xprint_and_close_file (FILE * file)
Definition at line 325 of file xfuncs_printf.c.
 {
     fflush_all();
     // copyfd outputs error messages for us.
     if (bb_copyfd_eof(fileno(file), STDOUT_FILENO) == -1)
         xfunc_die();
     fclose(file);
 }
References bb_copyfd_eof(), fclose(), fflush_all(), fileno(), STDOUT_FILENO, and xfunc_die().
Referenced by lsmod_main().
xrealloc()
void* FAST_FUNC xrealloc (void * ptr, size_t size)
Definition at line 59 of file xfuncs_printf.c.
 {
     ptr = realloc(ptr, size);
     if (ptr == NULL && size != 0)
         bb_die_memory_exhausted();
     return ptr;
 }
References bb_die_memory_exhausted(), NULL, realloc, and size.
xrename()
void FAST_FUNC xrename (const char * oldpath, const char * newpath)
Definition at line 210 of file xfuncs_printf.c.
 {
     if (rename(oldpath, newpath))
         bb_perror_msg_and_die("can't move '%s' to '%s'", oldpath, newpath);
 }
References bb_perror_msg_and_die(), and rename().
Referenced by add_remove_shell_main(), convert(), crontab_main(), data_extract_all(), ifupdown_main(), patch_main(), sed_main(), seedrng_main(), and write_status_file().
xsendto()
ssize_t FAST_FUNC xsendto (int s, const void * buf, size_t len, const struct sockaddr * to, socklen_t tolen)
Definition at line 506 of file xfuncs_printf.c.
 {
     ssize_t ret = sendto(s, buf, len, 0, to, tolen);
     if (ret < 0) {
         if (ENABLE_FEATURE_CLEAN_UP)
             close(s);
         bb_simple_perror_msg_and_die("sendto");
     }
     return ret;
 }
References bb_simple_perror_msg_and_die(), buf, close(), len, s, and sendto().
Referenced by ether_wake_main(), ping4(), rtnl_rtcache_request(), send_arp_request(), and send_probe().
xsetegid()
void FAST_FUNC xsetegid (gid_t egid)
Definition at line 408 of file xfuncs_printf.c.
 {
     if (setegid(egid)) bb_simple_perror_msg_and_die("setegid");
 }
References bb_simple_perror_msg_and_die(), egid, and setegid().
Referenced by xopen_as_uid_gid().
xsetenv()
void FAST_FUNC xsetenv (const char * key, const char * value)
Definition at line 352 of file xfuncs_printf.c.
 {
     if (setenv(key, value, 1))
         bb_die_memory_exhausted();
 }
References bb_die_memory_exhausted(), setenv(), and value.
Referenced by chpst_main(), edir(), init_main(), lpd_main(), parse(), parse_args(), popmaildir_main(), set_env_vars(), and setup_environment().
xseteuid()
void FAST_FUNC xseteuid (uid_t euid)
Definition at line 413 of file xfuncs_printf.c.
 {
     if (seteuid(euid)) bb_simple_perror_msg_and_die("seteuid");
 }
References bb_simple_perror_msg_and_die(), euid, and seteuid().
Referenced by xopen_as_uid_gid().
xsetgid()
void FAST_FUNC xsetgid (gid_t gid)
Definition at line 397 of file xfuncs_printf.c.
 {
     if (setgid(gid)) bb_simple_perror_msg_and_die("setgid");
 }
References bb_simple_perror_msg_and_die(), and setgid().
Referenced by change_identity(), chpst_main(), httpd_main(), inetd_main(), nsenter_main(), start_stop_daemon_main(), tcpudpsvd_main(), and traceroute_init().
xsettimeofday()
void FAST_FUNC xsettimeofday (const struct timeval * tv)
Definition at line 727 of file xfuncs_printf.c.
 {
     if (settimeofday(tv, NULL))
         bb_simple_perror_msg_and_die("settimeofday");
 }
References bb_simple_perror_msg_and_die(), NULL, and settimeofday().
Referenced by rdate_main(), set_kernel_timezone_and_clock(), and step_time().
xsetuid()
void FAST_FUNC xsetuid (uid_t uid)
Definition at line 403 of file xfuncs_printf.c.
 {
     if (setuid(uid)) bb_simple_perror_msg_and_die("setuid");
 }
References bb_simple_perror_msg_and_die(), and setuid().
Referenced by change_identity(), chpst_main(), httpd_main(), nsenter_main(), passwd_main(), tcpudpsvd_main(), and traceroute_init().
xsocket()
int FAST_FUNC xsocket (int domain, int type, int protocol)
Definition at line 468 of file xfuncs_printf.c.
 {
     int r = socket(domain, type, protocol);
     if (r < 0) {
         /* Hijack vaguely related config option */
 #if ENABLE_VERBOSE_RESOLUTION_ERRORS
         const char *s = "INET";
 # ifdef AF_PACKET
         if (domain == AF_PACKET) s = "PACKET";
 # endif
 # ifdef AF_NETLINK
         if (domain == AF_NETLINK) s = "NETLINK";
 # endif
 IF_FEATURE_IPV6(if (domain == AF_INET6) s = "INET6";)
         bb_perror_msg_and_die("socket(AF_%s,%d,%d)", s, type, protocol);
 #else
         bb_simple_perror_msg_and_die("socket");
 #endif
     }
     return r;
 }
References AF_INET6, AF_NETLINK, AF_PACKET, bb_perror_msg_and_die(), bb_simple_perror_msg_and_die(), domain, IF_FEATURE_IPV6(), s, socket(), and type.
Referenced by arp_main(), bind_for_passive_mode(), brctl_main(), create_and_bind_or_die(), create_and_connect_stream_or_die(), create_socket(), d6_listen_socket(), d6_raw_socket(), d6_read_interface(), dnsd_main(), do_add_ioctl(), do_del_ioctl(), do_get_ioctl(), do_ioctl_get_ifindex(), do_ioctl_get_ifname(), do_ioctl_get_iftype(), get_address(), get_ctl_fd(), if_fetch(), if_readconf(), ifconfig_main(), ifplugd_main(), INET_setroute(), nameif_main(), nc_main(), pscan_main(), tcpudpsvd_main(), traceroute_init(), udhcp_listen_socket(), udhcp_raw_socket(), udhcp_read_interface(), vconfig_main(), xconnect_stream(), xrtnl_open(), and xsocket_type().
xstat()
void FAST_FUNC xstat (const char * name, struct stat * stat_buf)
Definition at line 519 of file xfuncs_printf.c.
 {
     if (stat(name, stat_buf))
         bb_perror_msg_and_die("can't stat '%s'", name);
 }
References bb_perror_msg_and_die(), and stat().
Referenced by date_main(), diff_main(), fdformat_main(), fuser_main(), initial_scan(), parse_params(), run_pipe(), setfiles_main(), start_stop_daemon_main(), switch_root_main(), and touch_main().
xstrdup()
char* FAST_FUNC xstrdup (const char * s)
Definition at line 77 of file xfuncs_printf.c.
 {
     char *t;
     if (s == NULL)
         return NULL;
     t = strdup(s);
     if (t == NULL)
         bb_die_memory_exhausted();
     return t;
 }
References bb_die_memory_exhausted(), NULL, s, strdup(), and t.
Referenced by xmalloc_ttyname().
xstrndup()
char* FAST_FUNC xstrndup (const char * s, size_t n)
Definition at line 94 of file xfuncs_printf.c.
 {
     char *t;
     t = strndup(s, n);
     if (t == NULL)
         bb_die_memory_exhausted();
     return t;
 }
References bb_die_memory_exhausted(), n, NULL, s, strndup(), and t.
Referenced by add_exclude(), awk_printf(), bb_dump_add(), bb_unsetenv(), compile_fs_type(), do_ioctl_get_ifname(), done_pipe(), eval6(), exec_builtin(), expand(), expand_one_var(), get_header_ar(), get_header_tar(), get_label_uuid(), get_status(), index_status_file(), parse_cmd_args(), parse_file_cmd(), read_package_field(), rewrite(), safe_gethostname(), sha_crypt(), unicode_conv_to_printable2(), and write_status_file().
xunlink()
void FAST_FUNC xunlink (const char * pathname)
Definition at line 204 of file xfuncs_printf.c.
 {
     if (unlink(pathname))
         bb_perror_msg_and_die("can't remove file '%s'", pathname);
 }
References bb_perror_msg_and_die(), and unlink().
Referenced by add_remove_shell_main(), bbunpack(), patch_main(), seed_from_file_if_exists(), shred_main(), and unlink_main().
xvfork_parent_waits_and_exits()
void FAST_FUNC xvfork_parent_waits_and_exits (void)
Definition at line 699 of file xfuncs_printf.c.
 {
     pid_t pid;
     fflush_all();
     pid = xvfork();
     if (pid > 0) {
         /* Parent */
         int exit_status = wait_for_exitstatus(pid);
         if (WIFSIGNALED(exit_status))
             kill_myself_with_sig(WTERMSIG(exit_status));
         _exit(WEXITSTATUS(exit_status));
     }
     /* Child continues */
 }
References _exit(), exit_status, fflush_all(), kill_myself_with_sig(), pid, wait_for_exitstatus(), WEXITSTATUS, WIFSIGNALED, WTERMSIG, and xvfork.
Referenced by nsenter_main(), and unshare_main().
xwrite()
void FAST_FUNC xwrite (int fd, const void * buf, size_t count)
Definition at line 247 of file xfuncs_printf.c.
 {
     if (count) {
         ssize_t size = full_write(fd, buf, count);
         if ((size_t)size != count) {
             /*
              * Two cases: write error immediately;
              * or some writes succeeded, then we hit an error.
              * In either case, errno is set.
              */
             bb_simple_perror_msg_and_die(
                 size >= 0 ? "short write" : "write error"
             );
         }
     }
 }
References bb_simple_perror_msg_and_die(), buf, count, fd, full_write(), and size.
Referenced by archivefile(), chksum_and_xwrite_tar_header(), cmdio_write(), cmdio_write_error(), cmdio_write_ok(), dump_bad(), f_write(), flash_eraseall_main(), flush_outbuf(), get_volume_size_in_bytes(), handle_dir_common(), lzo_compress(), lzo_decompress(), mkfs_ext2_main(), mkfs_reiser_main(), mkfs_vfat_main(), mkswap_main(), nandwrite_main(), nbdclient_main(), nc_main(), openhere(), print_outbuf(), PUT(), readprofile_main(), retrieve_file_data(), rfkill_main(), rtnl_send(), seedrng_main(), send_change_cipher_spec(), split_main(), tac_main(), tail_main(), tls_run_copy_loop(), tr_main(), tune2fs_main(), ubi_tools_main(), uuencode_main(), write32(), write_block(), write_header(), write_tables(), xsendfile(), xwrite_encrypted_aesgcm(), xwrite_encrypted_and_hmac_signed(), xwrite_handshake_record(), and xwrite_str().
xwrite_str()
void FAST_FUNC xwrite_str (int fd, const char * str)
Definition at line 263 of file xfuncs_printf.c.
 {
     xwrite(fd, str, strlen(str));
 }
References fd, str, strlen(), and xwrite().
Referenced by chat_main(), cmdio_write_raw(), process_action(), resume_main(), sysctl_act_on_setting(), wait_for_seqfile(), and xopen_xwrite_close().
xzalloc()
void* FAST_FUNC xzalloc (size_t size)
Definition at line 69 of file xfuncs_printf.c.
 {
     void *ptr = xmalloc(size);
     memset(ptr, 0, size);
     return ptr;
 }
References memset, size, and xmalloc().
Referenced by add_cmd(), add_grep_list_data(), add_inode(), add_interface(), add_peers(), add_split_dependencies(), add_static_lease(), add_to_ino_dev_hashtable(), all_control_list(), alloc_action(), alloc_dumper(), alloc_procps_scan(), alloc_struct(), arch_apply_relocation(), arch_new_file(), arch_new_section(), archivefile(), awk_split(), bb_dump_add(), BZ2_bzCompressInit(), check_deps(), chs_string11(), common_traceroute_main(), compile_fs_type(), concat_option(), config_open2(), convert_dname(), create_fs_device(), cut_file(), data_extract_to_buffer(), dnalloc(), dnsd_main(), do_loadfont(), done_pipe(), dpkg_main(), encode_then_expand_vararg(), exec_shell(), execute(), fetch_till_str(), fill_package_struct(), find_main(), find_pid_by_name(), get(), get_address(), get_cached(), get_header_ar(), get_header_cpio(), get_header_tar(), get_lsa(), get_node(), get_S(), getgrouplist_internal(), grep_main(), gzip_main(), hash_bin_to_hex(), hash_find(), hash_init(), hash_rebuild(), hashwalk_init(), helper_create_alloced_section(), helper_get_module(), huft_build(), hush_main(), IF_DESKTOP(), inetd_mode(), init_blk(), init_cpu(), init_ctx(), init_fd(), init_fork(), init_handle(), init_if(), init_int(), init_literal(), init_mem(), init_swp(), init_text_buffer(), init_time(), install_sighandlers(), int_value(), ipsvd_perhost_init(), isrv_run(), less_gets(), ll_remember_index(), llist_add_to_end(), load_crontab(), lzo_compress(), lzo_decompress(), make_device(), make_iface_list(), make_new_session(), mdev_main(), mkfs_ext2_main(), mkfs_reiser_main(), mkfs_vfat_main(), mount_main(), my_stat(), nc_main(), new_get_kernel_symbols(), new_init_action(), new_node(), new_peer(), new_pipe(), new_proc(), new_servtab(), new_tls_state(), ntp_init(), ntpd_main(), nvalloc(), obj_allocate_commons(), obj_load(), obj_string_patch(), parse_cmd_args(), parse_conf(), parse_conf_file(), parse_expr(), parse_group(), parse_params(), parse_redirect(), parse_stream(), parse_subst_cmd(), partname(), prepend_new_eth_table(), process_config_line(), process_files(), pstm_exptmod(), pstm_init(), pstm_init_size(), pstm_montgomery_reduce(), pstm_mul_comba_gen(), pstm_sqr_comba_gen(), purge_package(), putenvp(), rc_init(), re_execute_shell(), read_interfaces(), read_pte(), read_tables(), remove_package(), rewrite(), rt_addr_n2a(), rtnl_rtdsfield_initialize(), rtnl_rtprot_initialize(), rtnl_rtrealm_initialize(), rtnl_rtscope_initialize(), screen_read_close(), sed_xfopen_w(), send_client_hello_and_alloc_hsd(), send_d6_discover(), set_environ(), set_local_var(), setup_tables(), sha_crypt(), split_main(), start_bunzip(), stats_dev_find_or_new(), stone(), store_nlmsg(), str2sockaddr(), str_value(), strings_main(), svlogd_main(), syslogd_main(), tar_main(), tee_main(), tr_main(), traceroute_init(), tune2fs_main(), ubirename_main(), udhcp_insert_new_option(), udhcp_option_idx(), udhcpd_main(), umount_main(), unicode_conv_to_printable2(), unzip_main(), uuidcache_addentry(), volume_id_open_node(), volume_id_probe_mac_partition_map(), volume_id_probe_msdos_part_table(), xargs_main(), xsocket_type(), and xzalloc_lsa().