Fennix Kernel: vfs::FileDescriptorTable Class Reference
vfs::FileDescriptorTable Class Reference
#include <filesystem.hpp>
Data Structures
struct Fildes
Public Member Functions
struct vfs::FileDescriptorTable::Fildes __attribute__ ((packed)) nullfd
Fildes & GetDescriptor (int FileDescriptor)
const char * GetAbsolutePath (int FileDescriptor)
std::vector< Fildes > & GetFileDescriptors ()
std::vector< Fildes > & GetFileDescriptorsDuplicates ()
RefNode * GetRefNode (int FileDescriptor)
int GetFlags (int FileDescriptor)
int SetFlags (int FileDescriptor, int Flags)
void Fork (FileDescriptorTable *Parent)
int _open (const char *pathname, int flags, mode_t mode)
int _creat (const char *pathname, mode_t mode)
ssize_t _read (int fd, void *buf, size_t count)
ssize_t _write (int fd, const void *buf, size_t count)
int _close (int fd)
off_t _lseek (int fd, off_t offset, int whence)
int _stat (const char *pathname, struct stat *statbuf)
int _fstat (int fd, struct stat *statbuf)
int _lstat (const char *pathname, struct stat *statbuf)
int _dup (int oldfd)
int _dup2 (int oldfd, int newfd)
int _ioctl (int fd, unsigned long request, void *argp)
FileDescriptorTable (void *Owner)
~FileDescriptorTable ()
Private Member Functions
Fildes & GetFileDescriptor (int FileDescriptor)
FileDescriptorTable::Fildes & GetDupFildes (int FileDescriptor)
int ProbeMode (mode_t Mode, int Flags)
int AddFileDescriptor (const char *AbsolutePath, mode_t Mode, int Flags)
int RemoveFileDescriptor (int FileDescriptor)
int GetFreeFileDescriptor ()
Private Attributes
std::vector< Fildes > FileDescriptors
std::vector< Fildes > FildesDuplicates
vfs::Node * fdDir = nullptr
Detailed Description
Definition at line 374 of file filesystem.hpp.
Constructor & Destructor Documentation
FileDescriptorTable()
vfs::FileDescriptorTable::FileDescriptorTable (void * Owner)
Definition at line 638 of file file_descriptor.cpp.
     {
         debug("+ %#lx", this);
         this->fdDir = fs->Create("fd", vfs::NodeType::DIRECTORY,
                                  ((Tasking::PCB *)Owner));
     }
References vfs::Virtual::Create(), debug, vfs::DIRECTORY, fdDir, and fs.
~FileDescriptorTable()
vfs::FileDescriptorTable::~FileDescriptorTable ()
Definition at line 645 of file file_descriptor.cpp.
     {
         debug("- %#lx", this);
         foreach (auto &fd in FileDescriptors)
         {
             debug("Removing fd: %d", fd.Descriptor);
             this->RemoveFileDescriptor(fd.Descriptor);
             delete fd.Handle;
         }
     }
References debug, FileDescriptors, and RemoveFileDescriptor().
Member Function Documentation
__attribute__()
struct vfs::FileDescriptorTable::Fildes vfs::FileDescriptorTable::__attribute__ ((packed))
_close()
int vfs::FileDescriptorTable::_close (int fd)
Definition at line 427 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(_fd);
         if (fd == nullfd)
         {
             debug("invalid fd %d", _fd);
             return -EBADF;
         }
         if (RemoveFileDescriptor(_fd) < 0)
         {
             debug("invalid fd %d", _fd);
             return -EBADF;
         }
         bool Found = false;
         foreach (auto dfd in FileDescriptors)
         {
             if (dfd.Handle == fd.Handle)
             {
                 Found = true;
                 break;
             }
         }
         if (!Found)
             foreach (auto dfd in FildesDuplicates)
             {
                 if (dfd.Handle == fd.Handle)
                 {
                     Found = true;
                     break;
                 }
             }
         /* If the file descriptor is a duplicate,
             we don't need to close the handle,
             because it's a duplicate of another
             file descriptor. */
         if (!Found)
             delete fd.Handle;
         return 0;
     }
References debug, EBADF, FildesDuplicates, FileDescriptors, GetDescriptor(), and RemoveFileDescriptor().
Referenced by _dup2(), fclose(), linux_close(), linux_readlink(), sys_close(), and sys_readlink().
_creat()
int vfs::FileDescriptorTable::_creat (const char * pathname, mode_t mode)
Definition at line 397 of file file_descriptor.cpp.
     {
         return _open(pathname, O_WRONLY | O_CREAT | O_TRUNC, mode);
     }
References _open(), O_CREAT, O_TRUNC, and O_WRONLY.
Referenced by creat(), and linux_creat().
_dup()
int vfs::FileDescriptorTable::_dup (int oldfd)
Definition at line 569 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(oldfd);
         if (fd == nullfd)
         {
             debug("invalid fd %d", oldfd);
             return -EBADF;
         }
         int newfd = this->GetFreeFileDescriptor();
         if (newfd < 0)
             return -EMFILE;
         Fildes new_dfd{};
         new_dfd.Handle = fd.Handle;
         new_dfd.Mode = fd.Mode;
         new_dfd.Descriptor = newfd;
         this->FildesDuplicates.push_back(new_dfd);
         debug("Duplicated file descriptor %d to %d",
               oldfd, newfd);
         return newfd;
     }
References debug, EBADF, EMFILE, FildesDuplicates, GetDescriptor(), GetFreeFileDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, and vfs::FileDescriptorTable::Fildes::Mode.
Referenced by linux_dup().
_dup2()
int vfs::FileDescriptorTable::_dup2 (int oldfd, int newfd)
Definition at line 593 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(oldfd);
         if (fd == nullfd)
         {
             debug("invalid fd %d", oldfd);
             return -EBADF;
         }
         if (newfd < 0)
         {
             debug("invalid fd %d", newfd);
             return -EBADF;
         }
         if (newfd == oldfd)
             return newfd;
         /* Even if it's not valid
             we ignore it. */
         this->_close(newfd);
         Fildes new_dfd{};
         new_dfd.Handle = fd.Handle;
         new_dfd.Mode = fd.Mode;
         new_dfd.Descriptor = newfd;
         this->FildesDuplicates.push_back(new_dfd);
         debug("Duplicated file descriptor %d to %d",
               oldfd, newfd);
         return newfd;
     }
References _close(), debug, EBADF, FildesDuplicates, GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, and vfs::FileDescriptorTable::Fildes::Mode.
Referenced by linux_dup2(), and linux_fcntl().
_fstat()
int vfs::FileDescriptorTable::_fstat (int fd, struct stat * statbuf)
Definition at line 514 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(_fd);
         if (fd == nullfd)
         {
             debug("invalid fd %d", _fd);
             return -EBADF;
         }
         Node *node = fd.Handle->node;
         statbuf->st_dev = 0; /* FIXME: stub */
         statbuf->st_ino = node->IndexNode;
         statbuf->st_mode = node->Type | node->Mode;
         statbuf->st_nlink = 0; /* FIXME: stub */
         statbuf->st_uid = node->UserIdentifier;
         statbuf->st_gid = node->GroupIdentifier;
         statbuf->st_rdev = 0; /* FIXME: stub */
         statbuf->st_size = node->Size;
         statbuf->st_blksize = 0; /* FIXME: stub */
         statbuf->st_blocks = 0;  /* FIXME: stub */
         statbuf->st_attr = 0;    /* FIXME: stub */
         return 0;
     }
References debug, EBADF, GetDescriptor(), vfs::Node::GroupIdentifier, vfs::FileDescriptorTable::Fildes::Handle, vfs::Node::IndexNode, vfs::Node::Mode, vfs::RefNode::node, vfs::Node::Size, stat::st_attr, stat::st_blksize, stat::st_blocks, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, vfs::Node::Type, and vfs::Node::UserIdentifier.
Referenced by fstat(), and linux_fstat().
_ioctl()
int vfs::FileDescriptorTable::_ioctl (int fd, unsigned long request, void * argp)
Definition at line 626 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(_fd);
         if (fd == nullfd)
         {
             debug("invalid fd %d", _fd);
             return -EBADF;
         }
         return fd.Handle->ioctl(request, argp);
     }
References debug, EBADF, GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, and vfs::RefNode::ioctl().
Referenced by linux_ioctl().
_lseek()
off_t vfs::FileDescriptorTable::_lseek (int fd, off_t offset, int whence)
Definition at line 471 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(_fd);
         if (fd == nullfd)
         {
             debug("invalid fd %d", _fd);
             return -EBADF;
         }
         return fd.Handle->seek(offset, whence);
     }
References debug, EBADF, GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, and vfs::RefNode::seek().
Referenced by linux_lseek(), linux_mmap(), linux_read(), linux_write(), lseek(), sys_lseek(), sys_read(), and sys_write().
_lstat()
int vfs::FileDescriptorTable::_lstat (const char * pathname, struct stat * statbuf)
Definition at line 538 of file file_descriptor.cpp.
     {
         if (pathname == nullptr)
             return -EINVAL;
         RefNode *file = fs->Open(pathname,
                                  thisProcess->CurrentWorkingDirectory);
         if (!file)
         {
             error("Failed to open file %s",
                   pathname);
             return -EIO;
         }
         Node *node = file->node;
         statbuf->st_dev = 0; /* FIXME: stub */
         statbuf->st_ino = node->IndexNode;
         statbuf->st_mode = node->Type | node->Mode;
         statbuf->st_nlink = 0; /* FIXME: stub */
         statbuf->st_uid = node->UserIdentifier;
         statbuf->st_gid = node->GroupIdentifier;
         statbuf->st_rdev = 0; /* FIXME: stub */
         statbuf->st_size = node->Size;
         statbuf->st_blksize = 0; /* FIXME: stub */
         statbuf->st_blocks = 0;  /* FIXME: stub */
         statbuf->st_attr = 0;    /* FIXME: stub */
         return 0;
     }
References EINVAL, EIO, error, fs, vfs::Node::GroupIdentifier, vfs::Node::IndexNode, vfs::Node::Mode, vfs::RefNode::node, vfs::Virtual::Open(), vfs::Node::Size, stat::st_attr, stat::st_blksize, stat::st_blocks, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, thisProcess, vfs::Node::Type, and vfs::Node::UserIdentifier.
Referenced by linux_lstat(), and lstat().
_open()
int vfs::FileDescriptorTable::_open (const char * pathname, int flags, mode_t mode)
Definition at line 388 of file file_descriptor.cpp.
     {
         if (pathname == nullptr)
             return -EFAULT;
         return AddFileDescriptor(pathname, mode, flags);
     }
References AddFileDescriptor(), and EFAULT.
Referenced by _creat(), fopen(), linux_open(), linux_readlink(), vfs::PTYDevice::OpenMaster(), Execute::Spawn(), sys_open(), and sys_readlink().
_read()
ssize_t vfs::FileDescriptorTable::_read (int fd, void * buf, size_t count)
Definition at line 402 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(_fd);
         if (fd == nullfd)
         {
             debug("invalid fd %d", _fd);
             return -EBADF;
         }
         return fd.Handle->read((uint8_t *)buf, count);
     }
References debug, EBADF, GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, and vfs::RefNode::read().
Referenced by fread(), linux_mmap(), linux_read(), and sys_read().
_stat()
int vfs::FileDescriptorTable::_stat (const char * pathname, struct stat * statbuf)
Definition at line 483 of file file_descriptor.cpp.
     {
         if (pathname == nullptr)
             return -EINVAL;
         RefNode *file = fs->Open(pathname,
                                  thisProcess->CurrentWorkingDirectory);
         if (!file)
         {
             error("Failed to open file %s",
                   pathname);
             return -EIO;
         }
         Node *node = file->node;
         statbuf->st_dev = 0; /* FIXME: stub */
         statbuf->st_ino = node->IndexNode;
         statbuf->st_mode = node->Type | node->Mode;
         statbuf->st_nlink = 0; /* FIXME: stub */
         statbuf->st_uid = node->UserIdentifier;
         statbuf->st_gid = node->GroupIdentifier;
         statbuf->st_rdev = 0; /* FIXME: stub */
         statbuf->st_size = node->Size;
         statbuf->st_blksize = 0; /* FIXME: stub */
         statbuf->st_blocks = 0;  /* FIXME: stub */
         statbuf->st_attr = 0;    /* FIXME: stub */
         return 0;
     }
References EINVAL, EIO, error, fs, vfs::Node::GroupIdentifier, vfs::Node::IndexNode, vfs::Node::Mode, vfs::RefNode::node, vfs::Virtual::Open(), vfs::Node::Size, stat::st_attr, stat::st_blksize, stat::st_blocks, stat::st_dev, stat::st_gid, stat::st_ino, stat::st_mode, stat::st_nlink, stat::st_rdev, stat::st_size, stat::st_uid, thisProcess, vfs::Node::Type, and vfs::Node::UserIdentifier.
Referenced by linux_newfstatat(), linux_stat(), and stat().
_write()
ssize_t vfs::FileDescriptorTable::_write (int fd, const void * buf, size_t count)
Definition at line 414 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(_fd);
         if (fd == nullfd)
         {
             debug("invalid fd %d", _fd);
             return -EBADF;
         }
         return fd.Handle->write((uint8_t *)buf, count);
     }
References debug, EBADF, GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, and vfs::RefNode::write().
Referenced by fwrite(), linux_write(), and sys_write().
AddFileDescriptor()
int vfs::FileDescriptorTable::AddFileDescriptor (const char * AbsolutePath, mode_t Mode, int Flags) private
Definition at line 176 of file file_descriptor.cpp.
     {
         Tasking::PCB *pcb = thisProcess;
         if (ProbeMode(Mode, Flags) < 0)
             return -EACCES;
         if (Flags & O_CREAT)
         {
             int ret;
             new Node(pcb->CurrentWorkingDirectory,
                      AbsolutePath,
                      NodeType::FILE,
                      cwk_path_is_absolute(AbsolutePath),
                      fs,
                      &ret);
             if (ret == -EEXIST)
             {
                 debug("%s: File already exists, continuing...",
                       AbsolutePath);
             }
             else if (ret < 0)
             {
                 error("Failed to create file %s: %d",
                       AbsolutePath, ret);
                 assert(ret < 0);
             }
         }
         if (Flags & O_EXCL)
         {
             RefNode *File = fs->Open(AbsolutePath,
                                      pcb->CurrentWorkingDirectory);
             if (!File)
             {
                 error("Failed to open file %s",
                       AbsolutePath);
                 return -EIO;
             }
             delete File;
         }
         if (Flags & O_TRUNC)
         {
             fixme("O_TRUNC");
         }
         if (Flags & O_APPEND)
         {
             fixme("O_APPEND");
         }
         if (Flags & O_CLOEXEC)
         {
             fixme("O_CLOEXEC");
         }
         RefNode *File = fs->Open(AbsolutePath,
                                  pcb->CurrentWorkingDirectory);
         if (!File)
         {
             error("Failed to open file %s",
                   AbsolutePath);
             return -EIO;
         }
         Fildes fd = {.Descriptor = GetFreeFileDescriptor()};
         if (fd.Descriptor < 0)
             return -EMFILE;
         fd.Mode = Mode;
         fd.Flags = Flags;
         fd.Handle = File;
         FileDescriptors.push_back(fd);
         char FileName[64];
         itoa(fd.Descriptor, FileName, 10);
         assert(fs->CreateLink(FileName, AbsolutePath, this->fdDir) != nullptr);
         int rfd = File->node->open(Flags, Mode);
         if (rfd <= 0)
             return fd.Descriptor;
         else
             return rfd;
     }
References assert, vfs::Virtual::CreateLink(), Tasking::PCB::CurrentWorkingDirectory, cwk_path_is_absolute(), debug, vfs::FileDescriptorTable::Fildes::Descriptor, EACCES, EEXIST, EIO, EMFILE, error, FileDescriptors, fixme, Flags, vfs::FileDescriptorTable::Fildes::Flags, fs, GetFreeFileDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, itoa(), Mode, vfs::FileDescriptorTable::Fildes::Mode, vfs::RefNode::node, O_APPEND, O_CLOEXEC, O_CREAT, O_EXCL, O_TRUNC, vfs::Virtual::Open(), ProbeMode(), and thisProcess.
Referenced by _open().
Fork()
void vfs::FileDescriptorTable::Fork (FileDescriptorTable * Parent)
Definition at line 355 of file file_descriptor.cpp.
     {
         foreach (auto &fd in Parent->FileDescriptors)
         {
             debug("Forking fd: %d", fd.Descriptor);
             RefNode *node = fs->Open(fd.Handle->node->FullPath,
                                      thisProcess->CurrentWorkingDirectory);
             assert(node != nullptr);
             Fildes new_fd;
             new_fd.Descriptor = fd.Descriptor;
             new_fd.Flags = fd.Flags;
             new_fd.Mode = fd.Mode;
             new_fd.Handle = node;
             this->FileDescriptors.push_back(new_fd);
         }
         foreach (auto &fd in Parent->FildesDuplicates)
         {
             debug("Forking duplicated fd: %d", fd.Descriptor);
             RefNode *node = fs->Open(fd.Handle->node->FullPath,
                                      thisProcess->CurrentWorkingDirectory);
             assert(node != nullptr);
             Fildes new_fd;
             new_fd.Descriptor = fd.Descriptor;
             new_fd.Flags = fd.Flags;
             new_fd.Mode = fd.Mode;
             new_fd.Handle = node;
             this->FildesDuplicates.push_back(new_fd);
         }
     }
References assert, debug, vfs::FileDescriptorTable::Fildes::Descriptor, FildesDuplicates, FileDescriptors, vfs::FileDescriptorTable::Fildes::Flags, fs, vfs::FileDescriptorTable::Fildes::Handle, vfs::FileDescriptorTable::Fildes::Mode, vfs::Virtual::Open(), and thisProcess.
Referenced by linux_fork().
GetAbsolutePath()
const char * vfs::FileDescriptorTable::GetAbsolutePath (int FileDescriptor)
Definition at line 334 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(FileDescriptor);
         if (fd == nullfd)
             return "";
         Node *node = fd.Handle->node;
         const char *path = new char[strlen(node->FullPath) + 1];
         strcpy((char *)path, node->FullPath);
         return path;
     }
References vfs::Node::FullPath, GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, vfs::RefNode::node, strcpy, and strlen().
GetDescriptor()
FileDescriptorTable::Fildes & vfs::FileDescriptorTable::GetDescriptor (int FileDescriptor)
Definition at line 100 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetFileDescriptor(FileDescriptor);
         Fildes &dfd = this->GetDupFildes(FileDescriptor);
         if (fd.Descriptor == -1 &&
             dfd.Descriptor == -1)
             return nullfd;
         if (fd.Descriptor != -1)
             return fd;
         else
             return dfd;
     }
References vfs::FileDescriptorTable::Fildes::Descriptor, GetDupFildes(), and GetFileDescriptor().
Referenced by _close(), _dup(), _dup2(), _fstat(), _ioctl(), _lseek(), _read(), _write(), GetAbsolutePath(), GetFlags(), GetRefNode(), linux_getdents64(), linux_mmap(), linux_newfstatat(), linux_readlink(), SetFlags(), and sys_readlink().
GetDupFildes()
FileDescriptorTable::Fildes & vfs::FileDescriptorTable::GetDupFildes (int FileDescriptor) private
Definition at line 86 of file file_descriptor.cpp.
     {
         foreach (auto &fd in FildesDuplicates)
         {
             if (fd.Descriptor == FileDescriptor)
             {
                 debug("Found duplicated file descriptor %d", FileDescriptor);
                 return fd;
             }
         }
         return nullfd;
     }
References debug, and FildesDuplicates.
Referenced by GetDescriptor().
GetFileDescriptor()
FileDescriptorTable::Fildes & vfs::FileDescriptorTable::GetFileDescriptor (int FileDescriptor) private
Definition at line 72 of file file_descriptor.cpp.
     {
         foreach (auto &fd in FileDescriptors)
         {
             if (fd.Descriptor == FileDescriptor)
             {
                 // debug("Found file descriptor %d", FileDescriptor);
                 return fd;
             }
         }
         return nullfd;
     }
References FileDescriptors.
Referenced by GetDescriptor().
GetFileDescriptors()
std::vector<Fildes>& vfs::FileDescriptorTable::GetFileDescriptors () inline
Definition at line 414 of file filesystem.hpp.
 { return FileDescriptors; }
References FileDescriptors.
Referenced by Execute::Spawn().
GetFileDescriptorsDuplicates()
std::vector<Fildes>& vfs::FileDescriptorTable::GetFileDescriptorsDuplicates () inline
Definition at line 415 of file filesystem.hpp.
 { return FildesDuplicates; }
References FildesDuplicates.
GetFlags()
int vfs::FileDescriptorTable::GetFlags (int FileDescriptor)
Definition at line 115 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(FileDescriptor);
         if (fd == nullfd)
         {
             debug("invalid fd %d", FileDescriptor);
             return -EBADF;
         }
         return fd.Flags;
     }
References debug, EBADF, vfs::FileDescriptorTable::Fildes::Flags, and GetDescriptor().
Referenced by linux_fcntl().
GetFreeFileDescriptor()
int vfs::FileDescriptorTable::GetFreeFileDescriptor () private
Definition at line 299 of file file_descriptor.cpp.
     {
         int i = 0;
         while (true)
         {
             bool Found = false;
             foreach (auto fd in FileDescriptors)
             {
                 if (fd.Descriptor == i)
                 {
                     Found = true;
                     break;
                 }
             }
             if (!Found)
             {
                 foreach (auto fd in FildesDuplicates)
                 {
                     if (fd.Descriptor == i)
                     {
                         Found = true;
                         break;
                     }
                 }
             }
             if (!Found)
                 return i;
             i++;
         }
         return -EMFILE;
     }
References EMFILE, FildesDuplicates, and FileDescriptors.
Referenced by _dup(), and AddFileDescriptor().
GetRefNode()
RefNode * vfs::FileDescriptorTable::GetRefNode (int FileDescriptor)
Definition at line 346 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(FileDescriptor);
         if (fd == nullfd)
             return nullptr;
         return fd.Handle;
     }
References GetDescriptor(), and vfs::FileDescriptorTable::Fildes::Handle.
Referenced by vfs::PTMXDevice::RemovePTY().
ProbeMode()
int vfs::FileDescriptorTable::ProbeMode (mode_t Mode, int Flags) private
Definition at line 140 of file file_descriptor.cpp.
     {
         if (!(Flags & O_CREAT))
             return 0;
         if (Flags & O_RDONLY)
         {
             if (!(Mode & S_IRUSR))
             {
                 debug("No read permission (%d)", Mode);
                 return -EACCES;
             }
         }
         if (Flags & O_WRONLY)
         {
             if (!(Mode & S_IWUSR))
             {
                 debug("No write permission (%d)", Mode);
                 return -EACCES;
             }
         }
         if (Flags & O_RDWR)
         {
             if (!(Mode & S_IRUSR) ||
                 !(Mode & S_IWUSR))
             {
                 debug("No read/write permission (%d)", Mode);
                 return -EACCES;
             }
         }
         return 0;
     }
References debug, EACCES, Flags, Mode, O_CREAT, O_RDONLY, O_RDWR, O_WRONLY, S_IRUSR, and S_IWUSR.
Referenced by AddFileDescriptor().
RemoveFileDescriptor()
int vfs::FileDescriptorTable::RemoveFileDescriptor (int FileDescriptor) private
Definition at line 268 of file file_descriptor.cpp.
     {
         forItr(itr, FileDescriptors)
         {
             if (itr->Descriptor == FileDescriptor)
             {
                 FileDescriptors.erase(itr);
                 char FileName[64];
                 itoa(FileDescriptor, FileName, 10);
                 fs->Delete(FileName, false, this->fdDir);
                 return 0;
             }
         }
         forItr(itr, FildesDuplicates)
         {
             if (itr->Descriptor == FileDescriptor)
             {
                 FildesDuplicates.erase(itr);
                 char FileName[64];
                 itoa(FileDescriptor, FileName, 10);
                 fs->Delete(FileName, false, this->fdDir);
                 return 0;
             }
         }
         return -EBADF;
     }
References vfs::Virtual::Delete(), EBADF, fdDir, FildesDuplicates, FileDescriptors, fs, and itoa().
Referenced by _close(), and ~FileDescriptorTable().
SetFlags()
int vfs::FileDescriptorTable::SetFlags (int FileDescriptor, int Flags)
Definition at line 127 of file file_descriptor.cpp.
     {
         Fildes &fd = this->GetDescriptor(FileDescriptor);
         if (fd == nullfd)
         {
             debug("invalid fd %d", FileDescriptor);
             return -EBADF;
         }
         fd.Flags = Flags;
         return 0;
     }
References debug, EBADF, Flags, vfs::FileDescriptorTable::Fildes::Flags, and GetDescriptor().
Referenced by linux_fcntl().
Field Documentation
fdDir
vfs::Node* vfs::FileDescriptorTable::fdDir = nullptr private
Definition at line 401 of file filesystem.hpp.
Referenced by FileDescriptorTable(), and RemoveFileDescriptor().
FildesDuplicates
std::vector<Fildes> vfs::FileDescriptorTable::FildesDuplicates private
Definition at line 400 of file filesystem.hpp.
Referenced by _close(), _dup(), _dup2(), Fork(), GetDupFildes(), GetFileDescriptorsDuplicates(), GetFreeFileDescriptor(), and RemoveFileDescriptor().
FileDescriptors
std::vector<Fildes> vfs::FileDescriptorTable::FileDescriptors private
Definition at line 399 of file filesystem.hpp.
Referenced by _close(), AddFileDescriptor(), Fork(), GetFileDescriptor(), GetFileDescriptors(), GetFreeFileDescriptor(), RemoveFileDescriptor(), and ~FileDescriptorTable().
The documentation for this class was generated from the following files:
Kernel/include/filesystem.hpp
Kernel/storage/file_descriptor.cpp