Fennix: Kernel/kshell/commands/modinfo.cpp File Reference
modinfo.cpp File Reference
#include "../cmds.hpp"
#include "../../kernel.h"
Functions
void cmd_modinfo (const char *args)
Function Documentation
cmd_modinfo()
void cmd_modinfo (const char * args)
Definition at line 22 of file modinfo.cpp.
 {
     if (args[0] == '\0')
     {
         printf("Usage: modinfo <driver id/name>\n");
         return;
     }
     dev_t id = atoi(args);
     std::unordered_map<dev_t, Driver::DriverObject> drivers =
         DriverManager->GetDrivers();
     if (drivers.find(id) == drivers.end())
     {
         bool found = false;
         foreach (auto var in drivers)
         {
             if (strcmp(var.second.Name, args) == 0)
             {
                 id = var.first;
                 found = true;
                 break;
             }
         }
         if (!found)
         {
             printf("Driver not found\n");
             return;
         }
     }
     Driver::DriverObject drv = drivers[id];
     char drvVersion[32];
     snprintf(drvVersion, sizeof(drvVersion), "%d.%d.%d",
              drv.Version.Major, drv.Version.Minor, drv.Version.Patch);
     printf("Base Info:\n");
     printf(" Name: %s\n", drv.Name);
     printf(" Description: %s\n", drv.Description);
     printf(" Author: %s\n", drv.Author);
     printf(" Version: %s\n", drvVersion);
     printf(" License: %s\n", drv.License);
     printf("Resource Info:\n");
     printf(" Initialized: %s\n", drv.Initialized ? "yes" : "no");
     printf(" Error Code: %i (%s)\n", drv.ErrorCode, strerror(drv.ErrorCode));
     printf(" Path: %s\n", drv.Path.c_str());
     printf(" Used Memory: %ld KiB\n", TO_KiB(drv.vma->GetAllocatedMemorySize()));
     printf(" Used IRQs:%s\n", drv.InterruptHandlers->empty() ? " none" : "");
     foreach (auto var in *drv.InterruptHandlers)
     {
         printf("  IRQ%-2d: %#lx\n",
                var.first, (uintptr_t)var.second);
     }
 }
References atoi(), Driver::DriverObject::Author, Driver::DriverObject::Description, dev_t, DriverManager, Driver::DriverObject::ErrorCode, Memory::VirtualMemoryArea::GetAllocatedMemorySize(), Driver::Manager::GetDrivers(), Driver::DriverObject::Initialized, Driver::DriverObject::InterruptHandlers, Driver::DriverObject::License, Driver::DriverObject::Name, Driver::DriverObject::Path, printf, snprintf(), strcmp, strerror(), TO_KiB, Driver::DriverObject::Version, and Driver::DriverObject::vma.