Fennix Userspace: Userspace/apps/base/bash/lib/readline/examples/manexamp.c File Reference
manexamp.c File Reference
#include <stdio.h>
#include <readline/readline.h>
Functions
char * rl_gets ()
invert_case_line (int count, int key)
Variables
static char * line_read = (char *)NULL
Function Documentation
invert_case_line()
invert_case_line (int count, int key)
Definition at line 63 of file manexamp.c.
 {
   register int start, end;
   start = rl_point;
   if (count < 0)
     {
       direction = -1;
       count = -count;
     }
   else
     direction = 1;
   /* Find the end of the range to modify. */
   end = start + (count * direction);
   /* Force it to be within range. */
   if (end > rl_end)
     end = rl_end;
   else if (end < 0)
     end = -1;
   if (start > end)
     {
       int temp = start;
       start = end;
       end = temp;
     }
   if (start == end)
     return;
   /* Tell readline that we are modifying the line, so save the undo
      information. */
   rl_modifying (start, end);
   for (; start != end; start += direction)
     {
       if (_rl_uppercase_p (rl_line_buffer[start]))
     rl_line_buffer[start] = _rl_to_lower (rl_line_buffer[start]);
       else if (_rl_lowercase_p (rl_line_buffer[start]))
     rl_line_buffer[start] = _rl_to_upper (rl_line_buffer[start]);
     }
   /* Move point to on top of the last character changed. */
   rl_point = end - direction;
 }
References _rl_lowercase_p(), _rl_to_lower(), _rl_to_upper(), _rl_uppercase_p(), count, end, rl_end, rl_line_buffer, rl_modifying(), rl_point, and start.
rl_gets()
char* rl_gets ()
Definition at line 36 of file manexamp.c.
 {
   /* If the buffer has already been allocated, return the memory
      to the free pool. */
   if (line_read)
     {
       free (line_read);
       line_read = (char *)NULL;
     }
   /* Get a line from the user. */
   line_read = readline ("");
   /* If the line has any text in it, save it on the history. */
   if (line_read && *line_read)
     add_history (line_read);
   return (line_read);
 }
References add_history(), free, line_read, NULL, and readline().
Variable Documentation
line_read
char* line_read = (char *)NULL static
Definition at line 32 of file manexamp.c.
Referenced by rl_gets().