Fennix: Userspace/musl/src/misc/uname.c File Reference
uname.c File Reference
#include <sys/utsname.h>
#include "syscall.h"
Functions
int uname (struct utsname *uts)
Function Documentation
uname()
int uname (struct utsname * uts)
Definition at line 4 of file uname.c.
 {
     return syscall(SYS_uname, uts);
 }
References syscall().
Referenced by bb_init_module_24(), depmod_main(), finalize(), get_linux_version_code(), getdomainname(), gethostname(), hush_main(), id_prall(), id_prgroups(), init(), inituser(), linux_uname(), modinfo_main(), modprobe_main(), print_header(), print_login_issue(), safe_gethostname(), sym_get_type(), sys_uname(), and uname_builtin().