Fennix Kernel: Kernel/Architecture/amd64/runtime/crt1.c File Reference
crt1.c File Reference
#include <types.h>
#include <debug.h>
Functions
int Entry (void *Info)
void _start (void *Raw)
Function Documentation
_start()
void _start (void * Raw)
Definition at line 7 of file crt1.c.
 {
     UNUSED(Raw);
     error("ERROR! INVALID BOOT PROTOCOL!");
     while (1)
         asmv("hlt");
     Entry(NULL);
     return;
 }
References asmv, Entry(), error, NULL, and UNUSED.
Entry()
int Entry (void * Info)
Referenced by _start(), InitLimineAfterStack(), and Multiboot2Entry().