Fennix Userspace: Userspace/apps/base/busybox/sysklogd/syslogd.c File Reference
syslogd.c File Reference
#include <sys/un.h>
#include <sys/uio.h>
Data Structures
struct shbuf_ds
struct logFile_t
struct init_globals
struct globals
Macros
#define _PATH_LOG "/dev/log"
#define DEBUG 0
#define GLOBALS
#define G (*ptr_to_globals)
#define INIT_G()
#define OPTION_STR
#define OPTION_DECL
#define OPTION_PARAM
#define recvbuf (G.recvbuf)
Typedefs
typedef struct logFile_t logFile_t
Enumerations
enum { MAX_READ = CONFIG_FEATURE_SYSLOGD_READ_BUFFER_SIZE , DNS_WAIT_SEC = 2 * 60 }
enum {
OPTBIT_mark = 0 , OPTBIT_nofork , OPTBIT_outfile , OPTBIT_loglevel ,
OPTBIT_small , OPTBIT_timestamp , IF_FEATURE_ROTATE_LOGFILE , OPT_nofork = 1 << OPTBIT_nofork ,
OPT_outfile = 1 << OPTBIT_outfile , OPT_loglevel = 1 << OPTBIT_loglevel , OPT_small = 1 << OPTBIT_small , OPT_timestamp = 1 << OPTBIT_timestamp ,
OPT_filesize = IF_FEATURE_ROTATE_LOGFILE((1 << OPTBIT_filesize)) + 0 , OPT_rotatecnt = IF_FEATURE_ROTATE_LOGFILE((1 << OPTBIT_rotatecnt)) + 0 , OPT_remotelog = IF_FEATURE_REMOTE_LOG((1 << OPTBIT_remotelog)) + 0 , OPT_locallog = IF_FEATURE_REMOTE_LOG((1 << OPTBIT_locallog)) + 0 ,
OPT_circularlog = IF_FEATURE_IPC_SYSLOG((1 << OPTBIT_circularlog)) + 0 , OPT_dup = IF_FEATURE_SYSLOGD_DUP((1 << OPTBIT_dup)) + 0 , OPT_cfg = IF_FEATURE_SYSLOGD_CFG((1 << OPTBIT_cfg)) + 0 , OPT_kmsg = IF_FEATURE_KMSG_SYSLOG((1 << OPTBIT_kmsg)) + 0
}
Functions
static const CODE * find_by_val (int val, const CODE *c_set)
static void ipcsyslog_cleanup (void)
static void ipcsyslog_init (void)
void log_to_shmem (const char *msg)
static void kmsg_init (void)
static void kmsg_cleanup (void)
static void log_to_kmsg (int pri UNUSED_PARAM, const char *msg UNUSED_PARAM)
static void log_locally (time_t now, char *msg, logFile_t *log_file)
static void parse_fac_prio_20 (int pri, char *res20)
static void timestamp_and_log (int pri, char *msg, int len)
static void timestamp_and_log_internal (const char *msg)
static void split_escape_and_log (char *tmpbuf, int len)
static NOINLINE int create_socket (void)
static void do_syslogd (void)
int syslogd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const struct init_globals init_data
Data Structure Documentation
shbuf_ds
struct shbuf_ds
Definition at line 56 of file logread.c.
Data Fields
char data[1]
int32_t size
int32_t tail
logFile_t
struct logFile_t
Definition at line 219 of file syslogd.c.
Data Fields
int fd
time_t last_log_time
const char * path
init_globals
struct init_globals
Definition at line 265 of file syslogd.c.
Macro Definition Documentation
_PATH_LOG
#define _PATH_LOG "/dev/log"
Definition at line 171 of file syslogd.c.
DEBUG
#define DEBUG 0
Definition at line 188 of file syslogd.c.
G
#define G (*ptr_to_globals)
Definition at line 314 of file syslogd.c.
GLOBALS
#define GLOBALS
Value:
    logFile_t logFile;                      \
    /* interval between marks in seconds */ \
    /*int markInterval;*/                   \
    /* level of messages to be logged */    \
    int logLevel;                           \
IF_FEATURE_ROTATE_LOGFILE(\
    /* max size of file before rotation */  \
    unsigned logFileSize;                   \
    /* number of rotated message files */   \
    unsigned logFileRotate;                 \
) \
IF_FEATURE_IPC_SYSLOG(\
    int shmid; /* ipc shared memory id */   \
    int s_semid; /* ipc semaphore id */     \
    int shm_size;                           \
    struct sembuf SMwup[1];                 \
    struct sembuf SMwdn[3];                 \
) \
IF_FEATURE_SYSLOGD_CFG(\
    logRule_t *log_rules; \
) \
IF_FEATURE_KMSG_SYSLOG(\
    int kmsgfd; \
    int primask; \
)
Definition at line 238 of file syslogd.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(memcpy(xzalloc(sizeof(G)), &init_data, sizeof(init_data))); \
} while (0)
Definition at line 315 of file syslogd.c.
OPTION_DECL
#define OPTION_DECL
Value:
    *opt_m, *opt_l \
    IF_FEATURE_ROTATE_LOGFILE(,*opt_s) \
    IF_FEATURE_ROTATE_LOGFILE(,*opt_b) \
    IF_FEATURE_IPC_SYSLOG(    ,*opt_C = NULL) \
    IF_FEATURE_SYSLOGD_CFG(   ,*opt_f = NULL)
Definition at line 361 of file syslogd.c.
OPTION_PARAM
#define OPTION_PARAM
Value:
    &opt_m, &(G.logFile.path), &opt_l \
    IF_FEATURE_ROTATE_LOGFILE(,&opt_s) \
    IF_FEATURE_ROTATE_LOGFILE(,&opt_b) \
    IF_FEATURE_REMOTE_LOG(    ,&remoteAddrList) \
    IF_FEATURE_IPC_SYSLOG(    ,&opt_C) \
    IF_FEATURE_SYSLOGD_CFG(   ,&opt_f)
Definition at line 366 of file syslogd.c.
OPTION_STR
#define OPTION_STR
Value:
    "m:nO:l:St" \
    IF_FEATURE_ROTATE_LOGFILE("s:" ) \
    IF_FEATURE_ROTATE_LOGFILE("b:" ) \
    IF_FEATURE_REMOTE_LOG(    "R:*") \
    IF_FEATURE_REMOTE_LOG(    "L"  ) \
    IF_FEATURE_IPC_SYSLOG(    "C::") \
    IF_FEATURE_SYSLOGD_DUP(   "D"  ) \
    IF_FEATURE_SYSLOGD_CFG(   "f:" ) \
    IF_FEATURE_KMSG_SYSLOG(   "K"  )
Definition at line 352 of file syslogd.c.
recvbuf
#define recvbuf (G.recvbuf)
Typedef Documentation
logFile_t
typedef struct logFile_t logFile_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAX_READ
DNS_WAIT_SEC
Definition at line 198 of file syslogd.c.
      {
     MAX_READ = CONFIG_FEATURE_SYSLOGD_READ_BUFFER_SIZE,
     DNS_WAIT_SEC = 2 * 60,
 };
anonymous enum
anonymous enum
Enumerator
OPTBIT_mark
OPTBIT_nofork
OPTBIT_outfile
OPTBIT_loglevel
OPTBIT_small
OPTBIT_timestamp
IF_FEATURE_ROTATE_LOGFILE
OPT_nofork
OPT_outfile
OPT_loglevel
OPT_small
OPT_timestamp
OPT_filesize
OPT_rotatecnt
OPT_remotelog
OPT_locallog
OPT_circularlog
OPT_dup
OPT_cfg
OPT_kmsg
Definition at line 321 of file syslogd.c.
      {
     OPTBIT_mark = 0, // -m
     OPTBIT_nofork, // -n
     OPTBIT_outfile, // -O
     OPTBIT_loglevel, // -l
     OPTBIT_small, // -S
     OPTBIT_timestamp, // -t
     IF_FEATURE_ROTATE_LOGFILE(OPTBIT_filesize   ,)  // -s
     IF_FEATURE_ROTATE_LOGFILE(OPTBIT_rotatecnt  ,)  // -b
     IF_FEATURE_REMOTE_LOG(    OPTBIT_remotelog  ,)  // -R
     IF_FEATURE_REMOTE_LOG(    OPTBIT_locallog   ,)  // -L
     IF_FEATURE_IPC_SYSLOG(    OPTBIT_circularlog,)  // -C
     IF_FEATURE_SYSLOGD_DUP(   OPTBIT_dup        ,)  // -D
     IF_FEATURE_SYSLOGD_CFG(   OPTBIT_cfg        ,)  // -f
     IF_FEATURE_KMSG_SYSLOG(   OPTBIT_kmsg       ,)  // -K
     OPT_mark        = 1 << OPTBIT_mark    ,
     OPT_nofork      = 1 << OPTBIT_nofork  ,
     OPT_outfile     = 1 << OPTBIT_outfile ,
     OPT_loglevel    = 1 << OPTBIT_loglevel,
     OPT_small       = 1 << OPTBIT_small   ,
     OPT_timestamp   = 1 << OPTBIT_timestamp,
     OPT_filesize    = IF_FEATURE_ROTATE_LOGFILE((1 << OPTBIT_filesize   )) + 0,
     OPT_rotatecnt   = IF_FEATURE_ROTATE_LOGFILE((1 << OPTBIT_rotatecnt  )) + 0,
     OPT_remotelog   = IF_FEATURE_REMOTE_LOG(    (1 << OPTBIT_remotelog  )) + 0,
     OPT_locallog    = IF_FEATURE_REMOTE_LOG(    (1 << OPTBIT_locallog   )) + 0,
     OPT_circularlog = IF_FEATURE_IPC_SYSLOG(    (1 << OPTBIT_circularlog)) + 0,
     OPT_dup         = IF_FEATURE_SYSLOGD_DUP(   (1 << OPTBIT_dup        )) + 0,
     OPT_cfg         = IF_FEATURE_SYSLOGD_CFG(   (1 << OPTBIT_cfg        )) + 0,
     OPT_kmsg        = IF_FEATURE_KMSG_SYSLOG(   (1 << OPTBIT_kmsg       )) + 0,
 };
Function Documentation
create_socket()
static NOINLINE int create_socket (void) static
Definition at line 961 of file syslogd.c.
 {
     struct sockaddr_un sunx;
     int sock_fd;
     char *dev_log_name;
     memset(&sunx, 0, sizeof(sunx));
     sunx.sun_family = AF_UNIX;
     /* Unlink old /dev/log or object it points to. */
     /* (if it exists, bind will fail) */
     strcpy(sunx.sun_path, _PATH_LOG);
     dev_log_name = xmalloc_follow_symlinks(_PATH_LOG);
     if (dev_log_name) {
         safe_strncpy(sunx.sun_path, dev_log_name, sizeof(sunx.sun_path));
         free(dev_log_name);
     }
     unlink(sunx.sun_path);
     sock_fd = xsocket(AF_UNIX, SOCK_DGRAM, 0);
     xbind(sock_fd, (struct sockaddr *) &sunx, sizeof(sunx));
     chmod(_PATH_LOG, 0666);
     return sock_fd;
 }
References _PATH_LOG, AF_UNIX, chmod(), free, memset(), safe_strncpy(), SOCK_DGRAM, sock_fd, strcpy(), sockaddr_un::sun_family, sockaddr_un::sun_path, unlink(), xbind(), xmalloc_follow_symlinks(), and xsocket().
Referenced by do_syslogd().
do_syslogd()
static void do_syslogd (void) static
Definition at line 1005 of file syslogd.c.
 {
 #if ENABLE_FEATURE_REMOTE_LOG
     llist_t *item;
 #endif
 #if ENABLE_FEATURE_SYSLOGD_DUP
     int last_sz = -1;
     char *last_buf;
     char *recvbuf = G.recvbuf;
 #else
 #define recvbuf (G.recvbuf)
 #endif
     /* Set up signal handlers (so that they interrupt read()) */
     signal_no_SA_RESTART_empty_mask(SIGTERM, record_signo);
     signal_no_SA_RESTART_empty_mask(SIGINT, record_signo);
     //signal_no_SA_RESTART_empty_mask(SIGQUIT, record_signo);
     signal(SIGHUP, SIG_IGN);
 #ifdef SYSLOGD_MARK
     signal(SIGALRM, do_mark);
     alarm(G.markInterval);
 #endif
     xmove_fd(create_socket(), STDIN_FILENO);
     if (option_mask32 & OPT_circularlog)
         ipcsyslog_init();
     if (option_mask32 & OPT_kmsg)
         kmsg_init();
     timestamp_and_log_internal("syslogd started: BusyBox v" BB_VER);
     write_pidfile_std_path_and_ext("syslogd");
     while (!bb_got_signal) {
         ssize_t sz;
 #if ENABLE_FEATURE_SYSLOGD_DUP
         last_buf = recvbuf;
         if (recvbuf == G.recvbuf)
             recvbuf = G.recvbuf + MAX_READ;
         else
             recvbuf = G.recvbuf;
 #endif
  read_again:
         sz = read(STDIN_FILENO, recvbuf, MAX_READ - 1);
         if (sz < 0) {
             if (!bb_got_signal)
                 bb_perror_msg("read from %s", _PATH_LOG);
             break;
         }
         /* Drop trailing '\n' and NULs (typically there is one NUL) */
         while (1) {
             if (sz == 0)
                 goto read_again;
             /* man 3 syslog says: "A trailing newline is added when needed".
              * However, neither glibc nor uclibc do this:
              * syslog(prio, "test")   sends "test\0" to /dev/log,
              * syslog(prio, "test\n") sends "test\n\0".
              * IOW: newline is passed verbatim!
              * I take it to mean that it's syslogd's job
              * to make those look identical in the log files. */
             if (recvbuf[sz-1] != '\0' && recvbuf[sz-1] != '\n')
                 break;
             sz--;
         }
 #if ENABLE_FEATURE_SYSLOGD_DUP
         if ((option_mask32 & OPT_dup) && (sz == last_sz))
             if (memcmp(last_buf, recvbuf, sz) == 0)
                 continue;
         last_sz = sz;
 #endif
 #if ENABLE_FEATURE_REMOTE_LOG
         /* Stock syslogd sends it '\n'-terminated
          * over network, mimic that */
         recvbuf[sz] = '\n';
         /* We are not modifying log messages in any way before send */
         /* Remote site cannot trust _us_ anyway and need to do validation again */
         for (item = G.remoteHosts; item != NULL; item = item->link) {
             remoteHost_t *rh = (remoteHost_t *)item->data;
             if (rh->remoteFD == -1) {
                 rh->remoteFD = try_to_resolve_remote(rh);
                 if (rh->remoteFD == -1)
                     continue;
             }
             /* Send message to remote logger.
              * On some errors, close and set remoteFD to -1
              * so that DNS resolution is retried.
              */
             if (sendto(rh->remoteFD, recvbuf, sz+1,
                     MSG_DONTWAIT | MSG_NOSIGNAL,
                     &(rh->remoteAddr->u.sa), rh->remoteAddr->len) == -1
             ) {
                 switch (errno) {
                 case ECONNRESET:
                 case ENOTCONN: /* paranoia */
                 case EPIPE:
                     close(rh->remoteFD);
                     rh->remoteFD = -1;
                     free(rh->remoteAddr);
                     rh->remoteAddr = NULL;
                 }
             }
         }
 #endif
         if (!ENABLE_FEATURE_REMOTE_LOG || (option_mask32 & OPT_locallog)) {
             recvbuf[sz] = '\0'; /* ensure it *is* NUL terminated */
             split_escape_and_log(recvbuf, sz);
         }
     } /* while (!bb_got_signal) */
     timestamp_and_log_internal("syslogd exiting");
     remove_pidfile_std_path_and_ext("syslogd");
     ipcsyslog_cleanup();
     if (option_mask32 & OPT_kmsg)
         kmsg_cleanup();
     kill_myself_with_sig(bb_got_signal);
 #undef recvbuf
 }
References _PATH_LOG, alarm(), bb_got_signal, bb_perror_msg(), close(), create_socket(), llist_t::data, ECONNRESET, ENOTCONN, EPIPE, errno, free, G, if(), ipcsyslog_cleanup(), ipcsyslog_init(), kill_myself_with_sig(), kmsg_cleanup(), kmsg_init(), llist_t::link, MAX_READ, memcmp(), MSG_DONTWAIT, MSG_NOSIGNAL, NULL, OPT_circularlog, OPT_dup, OPT_kmsg, OPT_locallog, option_mask32, read(), record_signo(), recvbuf, remove_pidfile_std_path_and_ext(), sendto(), SIG_IGN, SIGALRM, SIGHUP, SIGINT, signal, signal_no_SA_RESTART_empty_mask(), SIGTERM, split_escape_and_log(), STDIN_FILENO, timestamp_and_log_internal(), write_pidfile_std_path_and_ext(), and xmove_fd().
Referenced by syslogd_main().
find_by_val()
static const CODE* find_by_val (int val, const CODE * c_set) static
Definition at line 384 of file syslogd.c.
 {
     for (; c_set->c_name; c_set++) {
         if (c_set->c_val == val)
             return c_set;
     }
     return NULL;
 }
References NULL, and val.
Referenced by parse_fac_prio_20().
ipcsyslog_cleanup()
static void ipcsyslog_cleanup (void) static
Definition at line 647 of file syslogd.c.
 {}
Referenced by do_syslogd().
ipcsyslog_init()
static void ipcsyslog_init (void) static
Definition at line 648 of file syslogd.c.
 {}
Referenced by do_syslogd().
kmsg_cleanup()
static void kmsg_cleanup (void) static
Definition at line 686 of file syslogd.c.
 {}
Referenced by do_syslogd().
kmsg_init()
static void kmsg_init (void) static
Definition at line 685 of file syslogd.c.
 {}
Referenced by do_syslogd().
log_locally()
static void log_locally (time_t now, char * msg, logFile_t * log_file) static
Definition at line 691 of file syslogd.c.
 {
 #ifdef SYSLOGD_WRLOCK
     struct flock fl;
 #endif
     int len = strlen(msg);
     /* fd can't be 0 (we connect fd 0 to /dev/log socket) */
     /* fd is 1 if "-O -" is in use */
     if (log_file->fd > 1) {
         /* Reopen log files every second. This allows admin
          * to delete the files and not worry about restarting us.
          * This costs almost nothing since it happens
          * _at most_ once a second for each file, and happens
          * only when each file is actually written.
          */
         if (!now)
             now = time(NULL);
         if (log_file->last_log_time != now) {
             log_file->last_log_time = now;
             close(log_file->fd);
             goto reopen;
         }
     }
     else if (log_file->fd == 1) {
         /* We are logging to stdout: do nothing */
     }
     else {
         if (LONE_DASH(log_file->path)) {
             log_file->fd = 1;
             /* log_file->isRegular = 0; - already is */
         } else {
  reopen:
             log_file->fd = open(log_file->path, O_WRONLY | O_CREAT
                     | O_NOCTTY | O_APPEND | O_NONBLOCK,
                     0666);
             if (log_file->fd < 0) {
                 /* cannot open logfile? - print to /dev/console then */
                 int fd = device_open(DEV_CONSOLE, O_WRONLY | O_NOCTTY | O_NONBLOCK);
                 if (fd < 0)
                     fd = 2; /* then stderr, dammit */
                 full_write(fd, msg, len);
                 if (fd != 2)
                     close(fd);
                 return;
             }
 #if ENABLE_FEATURE_ROTATE_LOGFILE
             {
                 struct stat statf;
                 log_file->isRegular = (fstat(log_file->fd, &statf) == 0 && S_ISREG(statf.st_mode));
                 /* bug (mostly harmless): can wrap around if file > 4gb */
                 log_file->size = statf.st_size;
             }
 #endif
         }
     }
 #ifdef SYSLOGD_WRLOCK
     fl.l_whence = SEEK_SET;
     fl.l_start = 0;
     fl.l_len = 1;
     fl.l_type = F_WRLCK;
     fcntl(log_file->fd, F_SETLKW, &fl);
 #endif
 #if ENABLE_FEATURE_ROTATE_LOGFILE
     if (G.logFileSize && log_file->isRegular && log_file->size > G.logFileSize) {
         if (G.logFileRotate) { /* always 0..99 */
             int i = strlen(log_file->path) + 3 + 1;
             char oldFile[i];
             char newFile[i];
             i = G.logFileRotate - 1;
             /* rename: f.8 -> f.9; f.7 -> f.8; ... */
             while (1) {
                 sprintf(newFile, "%s.%d", log_file->path, i);
                 if (i == 0) break;
                 sprintf(oldFile, "%s.%d", log_file->path, --i);
                 /* ignore errors - file might be missing */
                 rename(oldFile, newFile);
             }
             /* newFile == "f.0" now */
             rename(log_file->path, newFile);
         }
         /* We may or may not have just renamed the file away;
          * if we didn't rename because we aren't keeping any backlog,
          * then it's time to clobber the file. If we did rename it...,
          * incredibly, if F and F.0 are hardlinks, POSIX _demands_
          * that rename returns 0 but does not remove F!!!
          * (hardlinked F/F.0 pair was observed after
          * power failure during rename()).
          * So ensure old file is gone in any case:
          */
         unlink(log_file->path);
 #ifdef SYSLOGD_WRLOCK
         fl.l_type = F_UNLCK;
         fcntl(log_file->fd, F_SETLKW, &fl);
 #endif
         close(log_file->fd);
         goto reopen;
     }
 /* TODO: what to do on write errors ("disk full")? */
     len = full_write(log_file->fd, msg, len);
     if (len > 0)
         log_file->size += len;
 #else
     full_write(log_file->fd, msg, len);
 #endif
 #ifdef SYSLOGD_WRLOCK
     fl.l_type = F_UNLCK;
     fcntl(log_file->fd, F_SETLKW, &fl);
 #endif
 }
References close(), DEV_CONSOLE, device_open(), F_SETLKW, F_UNLCK, F_WRLCK, fcntl(), fd, logFile_t::fd, fstat(), full_write(), G, i, logFile_t::last_log_time, LONE_DASH, NULL, O_APPEND, O_CREAT, O_NOCTTY, O_NONBLOCK, O_WRONLY, open(), logFile_t::path, rename(), S_ISREG, SEEK_SET, sprintf(), stat::st_mode, stat::st_size, strlen(), time(), and unlink().
Referenced by timestamp_and_log().
log_to_kmsg()
static void log_to_kmsg (int pri UNUSED_PARAM, const char *msg UNUSED_PARAM) static
Definition at line 687 of file syslogd.c.
 {}
Referenced by timestamp_and_log().
log_to_shmem()
void log_to_shmem (const char * msg)
Referenced by timestamp_and_log().
parse_fac_prio_20()
static void parse_fac_prio_20 (int pri, char * res20) static
Definition at line 806 of file syslogd.c.
 {
     const CODE *c_pri, *c_fac;
     c_fac = find_by_val(LOG_FAC(pri) << 3, bb_facilitynames);
     if (c_fac) {
         c_pri = find_by_val(LOG_PRI(pri), bb_prioritynames);
         if (c_pri) {
             snprintf(res20, 20, "%s.%s", c_fac->c_name, c_pri->c_name);
             return;
         }
     }
     snprintf(res20, 20, "<%d>", pri);
 }
References bb_facilitynames, bb_prioritynames, find_by_val(), LOG_FAC, LOG_PRI, and snprintf().
Referenced by timestamp_and_log().
split_escape_and_log()
static void split_escape_and_log (char * tmpbuf, int len) static
Definition at line 914 of file syslogd.c.
 {
     char *p = tmpbuf;
     tmpbuf += len;
     while (p < tmpbuf) {
         char c;
         char *q = G.parsebuf;
         int pri = (LOG_USER | LOG_NOTICE);
         if (*p == '<') {
             /* Parse the magic priority number */
             pri = bb_strtou(p + 1, &p, 10);
             if (*p == '>')
                 p++;
             if (pri & ~(LOG_FACMASK | LOG_PRIMASK))
                 pri = (LOG_USER | LOG_NOTICE);
         }
         while ((c = *p++)) {
             if (c == '\n')
                 c = ' ';
             if (!(c & ~0x1f) && c != '\t') {
                 *q++ = '^';
                 c += '@'; /* ^@, ^A, ^B... */
             }
             *q++ = c;
         }
         *q = '\0';
         /* Now log it */
         timestamp_and_log(pri, G.parsebuf, q - G.parsebuf);
     }
 }
References bb_strtou(), c, G, LOG_FACMASK, LOG_NOTICE, LOG_PRIMASK, LOG_USER, p, and timestamp_and_log().
Referenced by do_syslogd().
syslogd_main()
int syslogd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1130 of file syslogd.c.
 {
     int opts;
     char OPTION_DECL;
 #if ENABLE_FEATURE_REMOTE_LOG
     llist_t *remoteAddrList = NULL;
 #endif
     INIT_G();
     /* No non-option params */
     opts = getopt32(argv, "^"OPTION_STR"\0""=0", OPTION_PARAM);
 #if ENABLE_FEATURE_REMOTE_LOG
     while (remoteAddrList) {
         remoteHost_t *rh = xzalloc(sizeof(*rh));
         rh->remoteHostname = llist_pop(&remoteAddrList);
         rh->remoteFD = -1;
         rh->last_dns_resolve = monotonic_sec() - DNS_WAIT_SEC - 1;
         llist_add_to(&G.remoteHosts, rh);
     }
 #endif
 #ifdef SYSLOGD_MARK
     if (opts & OPT_mark) // -m
         G.markInterval = xatou_range(opt_m, 0, INT_MAX/60) * 60;
 #endif
     //if (opts & OPT_nofork) // -n
     //if (opts & OPT_outfile) // -O
     if (opts & OPT_loglevel) // -l
         G.logLevel = xatou_range(opt_l, 1, 8);
     //if (opts & OPT_small) // -S
 #if ENABLE_FEATURE_ROTATE_LOGFILE
     if (opts & OPT_filesize) // -s
         G.logFileSize = xatou_range(opt_s, 0, INT_MAX/1024) * 1024;
     if (opts & OPT_rotatecnt) // -b
         G.logFileRotate = xatou_range(opt_b, 0, 99);
 #endif
 #if ENABLE_FEATURE_IPC_SYSLOG
     if (opt_C) // -Cn
         G.shm_size = xatoul_range(opt_C, 4, INT_MAX/1024) * 1024;
 #endif
     /* If they have not specified remote logging, then log locally */
     if (ENABLE_FEATURE_REMOTE_LOG && !(opts & OPT_remotelog)) // -R
         option_mask32 |= OPT_locallog;
 #if ENABLE_FEATURE_SYSLOGD_CFG
     parse_syslogdcfg(opt_f);
 #endif
     /* Store away localhost's name before the fork */
     G.hostname = safe_gethostname();
     *strchrnul(G.hostname, '.') = '\0';
     if (!(opts & OPT_nofork)) {
         bb_daemonize_or_rexec(DAEMON_CHDIR_ROOT, argv);
     }
     do_syslogd();
     /* return EXIT_SUCCESS; */
 }
References argv, bb_daemonize_or_rexec, DAEMON_CHDIR_ROOT, DNS_WAIT_SEC, do_syslogd(), G, getopt32(), INIT_G, INT_MAX, llist_add_to(), llist_pop(), monotonic_sec(), NULL, OPT_filesize, OPT_locallog, OPT_loglevel, OPT_nofork, OPT_remotelog, OPT_rotatecnt, OPTION_DECL, option_mask32, OPTION_PARAM, OPTION_STR, safe_gethostname(), strchrnul(), and xzalloc().
timestamp_and_log()
static void timestamp_and_log (int pri, char * msg, int len) static
Definition at line 824 of file syslogd.c.
 {
     char *timestamp = NULL;
     time_t now;
     /* Jan 18 00:11:22 msg... */
     /* 01234567890123456 */
     if (len >= 16 && msg[3] == ' ' && msg[6] == ' '
      && msg[9] == ':' && msg[12] == ':' && msg[15] == ' '
     ) {
         if (!(option_mask32 & OPT_timestamp)) {
             /* use message timestamp */
             timestamp = msg;
             now = 0;
         }
         msg += 16;
     }
 #if ENABLE_FEATURE_SYSLOGD_PRECISE_TIMESTAMPS
     if (!timestamp) {
         struct timeval tv;
         xgettimeofday(&tv);
         now = tv.tv_sec;
         timestamp = ctime(&now) + 4; /* skip day of week */
         /* overwrite year by milliseconds, zero terminate */
         sprintf(timestamp + 15, ".%03u", (unsigned)tv.tv_usec / 1000u);
     } else {
         timestamp[15] = '\0';
     }
 #else
     if (!timestamp) {
         time(&now);
         timestamp = ctime(&now) + 4; /* skip day of week */
     }
     timestamp[15] = '\0';
 #endif
     if (option_mask32 & OPT_kmsg) {
         log_to_kmsg(pri, msg);
         return;
     }
     if (option_mask32 & OPT_small)
         sprintf(G.printbuf, "%s %s\n", timestamp, msg);
     else {
         char res[20];
         parse_fac_prio_20(pri, res);
         sprintf(G.printbuf, "%s %.64s %s %s\n", timestamp, G.hostname, res, msg);
     }
     /* Log message locally (to file or shared mem) */
 #if ENABLE_FEATURE_SYSLOGD_CFG
     {
         bool match = 0;
         logRule_t *rule;
         uint8_t facility = LOG_FAC(pri);
         uint8_t prio_bit = 1 << LOG_PRI(pri);
         for (rule = G.log_rules; rule; rule = rule->next) {
             if (rule->enabled_facility_priomap[facility] & prio_bit) {
                 log_locally(now, G.printbuf, rule->file);
                 match = 1;
             }
         }
         if (match)
             return;
     }
 #endif
     if (LOG_PRI(pri) < G.logLevel) {
 #if ENABLE_FEATURE_IPC_SYSLOG
         if ((option_mask32 & OPT_circularlog) && G.shbuf) {
             log_to_shmem(G.printbuf);
             return;
         }
 #endif
         log_locally(now, G.printbuf, &G.logFile);
     }
 }
References ctime(), G, LOG_FAC, log_locally(), LOG_PRI, log_to_kmsg(), log_to_shmem(), NULL, OPT_circularlog, OPT_kmsg, OPT_small, OPT_timestamp, option_mask32, parse_fac_prio_20(), sprintf(), time(), timeval::tv_sec, timeval::tv_usec, and xgettimeofday().
Referenced by split_escape_and_log(), and timestamp_and_log_internal().
timestamp_and_log_internal()
static void timestamp_and_log_internal (const char * msg) static
Definition at line 903 of file syslogd.c.
 {
     /* -L, or no -R */
     if (ENABLE_FEATURE_REMOTE_LOG && !(option_mask32 & OPT_locallog))
         return;
     timestamp_and_log(LOG_SYSLOG | LOG_INFO, (char*)msg, 0);
 }
References LOG_INFO, LOG_SYSLOG, OPT_locallog, option_mask32, and timestamp_and_log().
Referenced by do_syslogd().
Variable Documentation
init_data
const struct init_globals init_data static
Initial value:
= {
    .logFile = {
        .path = "/var/log/messages",
        .fd = -1,
    },
    .logLevel = 8,
}
Definition at line 1 of file syslogd.c.