Fennix: ACPI Namespace Reference
ACPI Namespace Reference
Data Structures
class ACPI
class MADT
class DSDT
Functions
__no_sanitize ("alignment") void *ACPI
__always_inline bool IsCanonical (uint64_t Address)
if (acpi->FADT->PM1aEventBlock)
debug ("SCI Event: %#lx", Event)
if (Event &ACPI_BUSMASTER)
Variables
uint16_t Event = 0
else
Function Documentation
__no_sanitize()
ACPI::__no_sanitize ("alignment")
Definition at line 27 of file acpi.cpp.
     {
         for (uint64_t t = 0; t < ((ACPIHeader->Length - sizeof(ACPI::ACPIHeader)) / (XSDTSupported ? 8 : 4)); t++)
         {
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wint-to-pointer-cast"
             // TODO: Should I be concerned about unaligned memory access?
             ACPI::ACPIHeader *SDTHdr = nullptr;
             if (XSDTSupported)
                 SDTHdr = (ACPI::ACPIHeader *)(*(uint64_t *)((uint64_t)ACPIHeader + sizeof(ACPI::ACPIHeader) + (t * 8)));
             else
                 SDTHdr = (ACPI::ACPIHeader *)(*(uint32_t *)((uint64_t)ACPIHeader + sizeof(ACPI::ACPIHeader) + (t * 4)));
 #pragma GCC diagnostic pop
             for (short i = 0; i < 4; i++)
             {
                 if (SDTHdr->Signature[i] != Signature[i])
                     break;
                 if (i == 3)
                 {
                     trace("%s found at address %p", Signature, (uintptr_t)SDTHdr);
                     return SDTHdr;
                 }
             }
         }
         // warn("%s not found!", Signature);
         return nullptr;
     }
References i, ACPI::ACPI::ACPIHeader::Signature, Signature, t, and trace.
debug()
ACPI::debug ("SCI Event: %#lx" , Event)
Referenced by ACPI::ACPI::ACPI(), and ACPI::DSDT::DSDT().
if() [1/2]
ACPI::if (acpi->FADT-> PM1aEventBlock)
Definition at line 67 of file dsdt.cpp.
             {
                 a = inw(s_cst(uint16_t, acpi->FADT->PM1aEventBlock));
                 outw(s_cst(uint16_t, acpi->FADT->PM1aEventBlock), a);
             }
References inw(), and outw().
if() [2/2]
else ACPI::if (Event & ACPI_BUSMASTER)
Definition at line 81 of file dsdt.cpp.
         {
             fixme("ACPI Busmaster");
         }
References fixme.
IsCanonical()
__always_inline bool ACPI::IsCanonical (uint64_t Address) inline
Definition at line 43 of file dsdt.cpp.
     {
         return ((Address <= 0x00007FFFFFFFFFFF) ||
                 ((Address >= 0xFFFF800000000000) &&
                  (Address <= 0xFFFFFFFFFFFFFFFF)));
     }
References Address.
Referenced by ACPI::DSDT::DSDT().
Variable Documentation
else
ACPI::else
Initial value:
{
            error("ACPI unknown event %#lx on CPU %d", Event, GetCurrentCPU()->ID)
Definition at line 121 of file dsdt.cpp.
Event
ACPI::Event = 0
Definition at line 64 of file dsdt.cpp.
Referenced by NetworkIPv4::__no_sanitize().