Fennix Userspace: Userspace/musl/src/network/htons.c File Reference
htons.c File Reference
#include <netinet/in.h>
#include <byteswap.h>
Functions
uint16_t htons (uint16_t n)
Function Documentation
htons()
uint16_t htons (uint16_t n)
Definition at line 4 of file htons.c.
 {
     union { int i; char c; } u = { 1 };
     return u.c ? bswap_16(n) : n;
 }
References bswap_16, c, i, and n.
Referenced by __res_msend_rc(), accept_builtin(), add_client_options(), arpping(), common_ping_main(), create_and_bind_or_die(), d4_recv_raw_packet(), d6_listen_socket(), d6_raw_socket(), d6_recv_raw_packet(), d6_send_kernel_packet_from_client_data_ifindex(), d6_send_raw_packet_from_client_data_ifindex(), dhcprelay_main(), do_lzo_compress(), get_address(), getaddrinfo(), getservbyname_r(), handle_port(), init_d6_packet(), init_packet(), ip_port_str(), ll_proto_a2n(), nbdclient_main(), nc_main(), packet4_ok(), parse_args(), port_name(), print_tunnel(), process_packet(), pscan_main(), read_header(), recv_pack(), reread_config_file(), send_arp_request(), send_pack(), send_packet_to_client(), send_probe(), str2sockaddr(), table_lookup(), tcpudpsvd_main(), traceroute_init(), udhcp_listen_socket(), udhcp_raw_socket(), udhcp_send_kernel_packet(), udhcp_send_raw_packet(), udhcp_str2optset(), vlan_parse_opt(), and xconnect_ftpdata().