Fennix: Kernel/include/driver.hpp File Reference
driver.hpp File Reference
#include <types.h>
#include <interface/driver.h>
#include <interface/input.h>
#include <filesystem.hpp>
#include <unordered_map>
#include <memory.hpp>
#include <ints.hpp>
#include <lock.hpp>
#include <task.hpp>
#include <ring.hpp>
#include <debug.h>
#include <cpu.hpp>
#include <pci.hpp>
#include <vector>
#include <bitset>
#include <elf.h>
#include <io.h>
#include <list>
Data Structures
struct Driver::DriverHandlers
struct Driver::DriverObject
class Driver::Manager
struct Driver::Manager::DeviceInode
struct Driver::DriverObject.Version
Namespaces
Driver
Functions
char Driver::GetScanCode (uint8_t ScanCode, bool Upper)
bool Driver::IsValidChar (uint8_t ScanCode)
void Driver::ManagerDaemonWrapper ()
void * GetSymbolByName (const char *Name, int Version)
Data Structure Documentation
Driver::DriverHandlers
struct Driver::DriverHandlers
Definition at line 46 of file driver.hpp.
Data Fields
RingBuffer< InputReport > * InputReports
struct Inode * Node
const InodeOperations * Ops
Driver::Manager::DeviceInode
struct Driver::Manager::DeviceInode
Definition at line 108 of file driver.hpp.
Data Fields
vector< DeviceInode * > Children
string Name
struct Inode Node
FileNode * Parent
Inode * ParentInode
Driver::DriverObject.Version
struct Driver::DriverObject.Version
Definition at line 68 of file driver.hpp.
Data Fields
int Major
int Minor
int Patch
Function Documentation
GetSymbolByName()
void* GetSymbolByName (const char * Name, int Version)
Definition at line 901 of file api.cpp.
 {
     switch (Version)
     {
     case 0:
     {
         for (auto sym : APISymbols_v0)
         {
             if (strcmp(Name, sym.Name) != 0)
                 continue;
             debug("Symbol %s found in API version %d", Name, Version);
             return sym.Function;
         }
         break;
     }
     default:
         assert(!"Invalid API version");
     }
     error("Symbol %s not found in API version %d", Name, Version);
     KPrint("Driver API symbol \"%s\" not found!", Name);
     return (void *)__KernelUndefinedFunction;
 }
References __KernelUndefinedFunction(), APISymbols_v0, assert, debug, error, KPrint(), Name, and strcmp.
Referenced by Driver::Manager::LoadDriverFile().