Fennix: Userspace/apps/base/bash/lib/intl/log.c File Reference
log.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static void print_escaped (FILE *stream, const char *str)
void _nl_log_untranslated (char *logfilename, const char *domainname, const char *msgid1, const char *msgid2, int plural) const
Function Documentation
_nl_log_untranslated()
void _nl_log_untranslated (char * logfilename, const char * domainname, const char * msgid1, const char * msgid2, int plural) const
Definition at line 57 of file log.c.
 {
   static char *last_logfilename = NULL;
   static FILE *last_logfile = NULL;
   FILE *logfile;
   /* Can we reuse the last opened logfile?  */
   if (last_logfilename == NULL || strcmp (logfilename, last_logfilename) != 0)
     {
       /* Close the last used logfile.  */
       if (last_logfilename != NULL)
     {
       if (last_logfile != NULL)
         {
           fclose (last_logfile);
           last_logfile = NULL;
         }
       free (last_logfilename);
       last_logfilename = NULL;
     }
       /* Open the logfile.  */
       last_logfilename = (char *) malloc (strlen (logfilename) + 1);
       if (last_logfilename == NULL)
     return;
       strcpy (last_logfilename, logfilename);
       last_logfile = fopen (logfilename, "a");
       if (last_logfile == NULL)
     return;
     }
   logfile = last_logfile;
   fprintf (logfile, "domain ");
   print_escaped (logfile, domainname);
   fprintf (logfile, "\nmsgid ");
   print_escaped (logfile, msgid1);
   if (plural)
     {
       fprintf (logfile, "\nmsgid_plural ");
       print_escaped (logfile, msgid2);
       fprintf (logfile, "\nmsgstr[0] \"\"\n");
     }
   else
     fprintf (logfile, "\nmsgstr \"\"\n");
   putc ('\n', logfile);
 }
References domainname, fclose(), fopen(), fprintf(), free, malloc, msgid1, msgid2, NULL, plural, print_escaped(), putc(), strcmp, strcpy, and strlen().
Referenced by if().
print_escaped()
static void print_escaped (FILE * stream, const char * str) static
Definition at line 33 of file log.c.
 {
   putc ('"', stream);
   for (; *str != '\0'; str++)
     if (*str == '\n')
       {
     fputs ("\\n\"", stream);
     if (str[1] == '\0')
       return;
     fputs ("\n\"", stream);
       }
     else
       {
     if (*str == '"' || *str == '\\')
       putc ('\\', stream);
     putc (*str, stream);
       }
   putc ('"', stream);
 }
References fputs(), putc(), and str.
Referenced by _nl_log_untranslated().