Fennix Userspace: Userspace/apps/base/busybox/libbb/safe_gethostname.c File Reference
safe_gethostname.c File Reference
#include "libbb.h"
#include <sys/utsname.h>
Functions
char *FAST_FUNC safe_gethostname (void)
Function Documentation
safe_gethostname()
char* FAST_FUNC safe_gethostname (void)
Definition at line 34 of file safe_gethostname.c.
 {
     struct utsname uts;
     /* The length of the arrays in a struct utsname is unspecified;
      * the fields are terminated by a null byte.
      * Note that there is no standard that says that the hostname
      * set by sethostname(2) is the same string as the nodename field of the
      * struct returned by uname (indeed, some systems allow a 256-byte host-
      * name and an 8-byte nodename), but this is true on Linux. The same holds
      * for setdomainname(2) and the domainname field.
      */
     /* Uname can fail only if you pass a bad pointer to it. */
     uname(&uts);
     return xstrndup(!uts.nodename[0] ? "?" : uts.nodename, sizeof(uts.nodename));
 }
References utsname::nodename, uname(), and xstrndup().
Referenced by finalize(), get_variable(), hostname_main(), lpqr_main(), obscure_msg(), popmaildir_main(), print_login_prompt(), sendmail_main(), and syslogd_main().