Fennix: Userspace/apps/base/bash/examples/loadables/strftime.c File Reference
strftime.c File Reference
#include <config.h>
#include "bashtypes.h"
#include "posixtime.h"
#include <stdio.h>
#include "builtins.h"
#include "shell.h"
#include "common.h"
#include "bashgetopt.h"
Functions
int strftime_builtin (WORD_LIST *list)
Variables
char * strftime_doc []
struct builtin strftime_struct
Function Documentation
strftime_builtin()
int strftime_builtin (WORD_LIST * list)
Definition at line 40 of file strftime.c.
 {
   char *format, *tbuf;
   size_t tbsize, tsize;
   time_t secs;
   struct tm *t;
   int n;
   intmax_t i;
   if (no_options (list))
     return (EX_USAGE);
   list = loptend;
   if (list == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   format = list->word->word;
   if (format == 0 || *format == 0)
     {
       printf ("\n");
       return (EXECUTION_SUCCESS);
     }
   list = list->next;
   if (list && list->word->word)
     {
       n = legal_number (list->word->word, &i);
       if (n == 0 || i < 0 || i != (time_t)i)
     {
       sh_invalidnum (list->word->word);
       return (EXECUTION_FAILURE);
     }
       else
         secs = i;
     }
   else
     secs = NOW;
   t = localtime (&secs);
   tbsize = strlen (format) * 4;
   tbuf = 0;
   /* Now try to figure out how big the buffer should really be.  strftime(3)
      will return the number of bytes placed in the buffer unless it's greater
      than MAXSIZE, in which case it returns 0. */
   for (n = 1; n <= 8; n++)
     {
       tbuf = xrealloc (tbuf, tbsize * n);
       tsize = strftime (tbuf, tbsize * n, format, t);
       if (tsize)
         break;
     }
   if (tsize)
     printf ("%s\n", tbuf);
   free (tbuf);
   return (EXECUTION_SUCCESS);
 }
References builtin_usage(), EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, format, free, i, legal_number(), localtime(), loptend, n, word_list::next, no_options(), NOW, printf, sh_invalidnum(), strftime(), strlen(), t, word_desc::word, word_list::word, and xrealloc.
Variable Documentation
strftime_doc
char* strftime_doc[]
Initial value:
= {
    "Display formatted time.",
    "",
    "Converts date and time format to a string and displays it on the",
    "standard output.  If the optional second argument is supplied, it",
    "is used as the number of seconds since the epoch to use in the",
    "conversion, otherwise the current time is used.",
    (char *)NULL
}
Definition at line 108 of file strftime.c.
strftime_struct
struct builtin strftime_struct
Initial value:
= {
    "strftime",
    strftime_builtin,
    BUILTIN_ENABLED,
    strftime_doc,
    "strftime format [seconds]",
    0
}
Definition at line 108 of file strftime.c.