Fennix Userspace: Userspace/musl/src/thread/pthread_setname_np.c File Reference
pthread_setname_np.c File Reference
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
#include <sys/prctl.h>
#include "pthread_impl.h"
Macros
#define _GNU_SOURCE
Functions
int pthread_setname_np (pthread_t thread, const char *name)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file pthread_setname_np.c.
Function Documentation
pthread_setname_np()
int pthread_setname_np (pthread_t thread, const char * name)
Definition at line 9 of file pthread_setname_np.c.
 {
     int fd, cs, status = 0;
     char f[sizeof "/proc/self/task//comm" + 3*sizeof(int)];
     size_t len;
     if ((len = strnlen(name, 16)) > 15) return ERANGE;
     if (thread == pthread_self())
         return prctl(PR_SET_NAME, (unsigned long)name, 0UL, 0UL, 0UL) ? errno : 0;
     snprintf(f, sizeof f, "/proc/self/task/%d/comm", thread->tid);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     if ((fd = open(f, O_WRONLY|O_CLOEXEC)) < 0 || write(fd, name, len) < 0) status = errno;
     if (fd >= 0) close(fd);
     pthread_setcancelstate(cs, 0);
     return status;
 }
References close(), ERANGE, errno, f, fd, O_CLOEXEC, O_WRONLY, open(), PR_SET_NAME, prctl(), PTHREAD_CANCEL_DISABLE, pthread_self(), pthread_setcancelstate(), snprintf(), status, strnlen(), UL, and write().