Fennix: Userspace/musl/src/select/poll.c File Reference
poll.c File Reference
#include <poll.h>
#include <time.h>
#include <signal.h>
#include "syscall.h"
Functions
int poll (struct pollfd *fds, nfds_t n, int timeout)
Function Documentation
poll()
int poll (struct pollfd * fds, nfds_t n, int timeout)
Definition at line 6 of file poll.c.
 {
 #ifdef SYS_poll
     return syscall_cp(SYS_poll, fds, n, timeout);
 #else
 #if SYS_ppoll_time64 == SYS_ppoll
     typedef long long ppoll_ts_t[2];
 #else
     typedef long ppoll_ts_t[2];
 #endif
     return syscall_cp(SYS_ppoll, fds, n, timeout>=0 ?
         ((ppoll_ts_t){ timeout/1000, timeout%1000*1000000 }) : 0,
         0, _NSIG/8);
 #endif
 }
References _NSIG, n, SYS_ppoll, syscall_cp, and timeout().
Referenced by __res_msend_rc(), buffer_pread(), chat_main(), conspy_main(), getch_nowait(), ifplugd_main(), inotifyd_main(), microcom_main(), ntpd_main(), read_key(), read_new_seed(), readwrite(), refill_HFILE_and_getc(), runsv_main(), runsvdir_main(), safe_poll(), script_main(), shell_builtin_read(), telnet_main(), udhcpc6_main(), udhcpc_main(), udhcpd_main(), and wait_for_input().