Fennix Userspace: Userspace/musl/include/semaphore.h File Reference
semaphore.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <fcntl.h>
Data Structures
struct sem_t
Macros
#define __NEED_time_t
#define __NEED_struct_timespec
#define SEM_FAILED ((sem_t *)0)
Functions
int sem_close (sem_t *)
int sem_destroy (sem_t *)
int sem_getvalue (sem_t *__restrict, int *__restrict)
int sem_init (sem_t *, int, unsigned)
sem_t * sem_open (const char *, int,...)
int sem_post (sem_t *)
int sem_timedwait (sem_t *__restrict, const struct timespec *__restrict)
int sem_trywait (sem_t *)
int sem_unlink (const char *)
int sem_wait (sem_t *)
Data Structure Documentation
sem_t
struct sem_t
Definition at line 17 of file semaphore.h.
Data Fields
volatile int __val[4 *sizeof(long)/sizeof(int)]
Macro Definition Documentation
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 10 of file semaphore.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 9 of file semaphore.h.
SEM_FAILED
#define SEM_FAILED ((sem_t *)0)
Definition at line 15 of file semaphore.h.
Function Documentation
sem_close()
int sem_close (sem_t * sem)
Definition at line 85 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, i, LOCK, lock, munmap(), semtab, and UNLOCK.
sem_destroy()
int sem_destroy (sem_t * sem)
Definition at line 28 of file semaphore-stubs.cpp.
{
     return 0;
 }
Referenced by __membarrier(), __synccall(), and mq_notify().
sem_getvalue()
int sem_getvalue (sem_t * __restrict, int * __restrict)
Definition at line 90 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sem_init()
int sem_init (sem_t * sem, int pshared, unsigned value)
Definition at line 5 of file sem_init.c.
 {
     if (value > SEM_VALUE_MAX) {
         errno = EINVAL;
         return -1;
     }
     sem->__val[0] = value;
     sem->__val[1] = 0;
     sem->__val[2] = pshared ? 0 : 128;
     return 0;
 }
References sem_t::__val, EINVAL, errno, SEM_VALUE_MAX, and value.
sem_open()
sem_t* sem_open (const char * name, int flags, ...)
Definition at line 80 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __shm_mapname(), access(), buf, calloc, clock_gettime(), CLOCK_REALTIME, close(), cnt, EEXIST, EINVAL, EMFILE, ENOENT, errno, F_OK, first, flags, FLAGS, fstat(), i, INT_MAX, link(), LOCK, lock, map, MAP_FAILED, MAP_SHARED, mmap, munmap(), name, NAME_MAX, O_CREAT, O_EXCL, open(), PROT_READ, PROT_WRITE, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), SEM_FAILED, sem_init(), SEM_VALUE_MAX, semtab, slot, snprintf(), timespec::tv_nsec, unlink(), UNLOCK, va_arg, va_end(), va_start(), value, and write().
sem_post()
int sem_post (sem_t * sem)
Definition at line 63 of file semaphore-stubs.cpp.
{
     auto old_count = __atomic_load_n(&sem->__mlibc_count, __ATOMIC_RELAXED) & semaphoreCountMask;
     if (old_count + 1 > SEM_VALUE_MAX) {
         errno = EOVERFLOW;
         return -1;
     }
     auto state = __atomic_exchange_n(&sem->__mlibc_count, old_count + 1, __ATOMIC_RELEASE);
     if (state & semaphoreHasWaiters)
         if (int e = mlibc::sys_futex_wake((int *)&sem->__mlibc_count); e)
             __ensure(!"sys_futex_wake() failed");
     return 0;
 }
References __ensure, sem_t::__val, __wake(), a_cas, EOVERFLOW, errno, SEM_VALUE_MAX, semaphoreCountMask, semaphoreHasWaiters, state, mlibc::sys_futex_wake(), and val.
Referenced by __synccall(), bcast_barrier(), handler(), io_thread_func(), and start().
sem_timedwait()
int sem_timedwait (sem_t * __restrict, const struct timespec * __restrict)
Definition at line 58 of file semaphore-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31mmlibc: sem_timedwait is implemented as sem_wait\e[0m" << frg::endlog;
     return sem_wait(sem);
 }
References mlibc::infoLogger, and sem_wait().
Referenced by __sem_timedwait_time32(), and sem_wait().
sem_trywait()
int sem_trywait (sem_t * sem)
Definition at line 100 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, sem_t::__val, a_cas, EAGAIN, errno, SEM_VALUE_MAX, and val.
Referenced by sem_timedwait().
sem_unlink()
int sem_unlink (const char * name)
Definition at line 95 of file semaphore-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, name, and shm_unlink().
sem_wait()
int sem_wait (sem_t * sem)
Definition at line 32 of file semaphore-stubs.cpp.
{
     unsigned int state = 0;
     while (1) {
         if (!(state & semaphoreCountMask)) {
             if (__atomic_compare_exchange_n(&sem->__mlibc_count, &state, semaphoreHasWaiters,
                         false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)) {
                 int e = mlibc::sys_futex_wait((int *)&sem->__mlibc_count, state, nullptr);
                 if (e == 0 || e == EAGAIN) {
                     continue;
                 } else if (e == EINTR) {
                     errno = EINTR;
                     return -1;
                 } else {
                     mlibc::panicLogger() << "sys_futex_wait() failed with error code " << e << frg::endlog;
                 }
             }
         } else {
             unsigned int desired = (state - 1);
             if (__atomic_compare_exchange_n(&sem->__mlibc_count, &state, desired, false,
                         __ATOMIC_RELAXED, __ATOMIC_RELAXED))
                 return 0;
         }
     }
 }
References EAGAIN, EINTR, errno, mlibc::panicLogger, sem_timedwait(), semaphoreCountMask, semaphoreHasWaiters, state, and mlibc::sys_futex_wait().
Referenced by __membarrier(), __synccall(), handler(), mq_notify(), sem_timedwait(), and submit().