Fennix Userspace: Userspace/musl/src/temp/__randname.c File Reference
__randname.c File Reference
#include <time.h>
#include <stdint.h>
#include "pthread_impl.h"
Functions
char * __randname (char *template)
Function Documentation
__randname()
char* __randname (char * template)
Definition at line 7 of file __randname.c.
 {
     int i;
     struct timespec ts;
     unsigned long r;
     __clock_gettime(CLOCK_REALTIME, &ts);
     r = ts.tv_sec + ts.tv_nsec + __pthread_self()->tid * 65537UL;
     for (i=0; i<6; i++, r>>=5)
         template[i] = 'A'+(r&15)+(r&16)*2;
     return template;
 }
References __clock_gettime(), __pthread_self, and i.
Referenced by __mkostemps(), mkdtemp(), mktemp(), tempnam(), tmpfile(), and tmpnam().