Fennix: Userspace/apps/base/busybox/procps/pwdx.c File Reference
pwdx.c File Reference
#include "libbb.h"
Functions
int pwdx_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
pwdx_main()
int pwdx_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 28 of file pwdx.c.
 {
     getopt32(argv, "^" "" "\0" "-1");
     argv += optind;
     do {
         char buf[sizeof("/proc/%u/cwd") + sizeof(int)*3];
         unsigned pid;
         char *s;
         char *arg = *argv;
         // Allowed on the command line:
         // /proc/NUM
         // NUM
         if (is_prefixed_with(arg, "/proc/"))
             arg += 6;
         pid = bb_strtou(arg, NULL, 10);
         if (errno)
             bb_error_msg_and_die("invalid process id: '%s'", arg);
         sprintf(buf, "/proc/%u/cwd", pid);
         /* NOFORK: only one alloc is allowed; must free */
         s = xmalloc_readlink(buf);
         // "pwdx /proc/1" says "/proc/1: DIR", not "1: DIR"
         printf("%s: %s\n", *argv, s ? s : strerror(errno == ENOENT ? ESRCH : errno));
         free(s);
     } while (*++argv);
     return EXIT_SUCCESS;
 }
References argv, bb_error_msg_and_die(), bb_strtou(), buf, ENOENT, errno, ESRCH, EXIT_SUCCESS, free, getopt32(), is_prefixed_with(), NULL, optind, pid, printf, s, sprintf(), strerror(), and xmalloc_readlink().