Fennix: Userspace/musl/src/include/langinfo.h File Reference
langinfo.h File Reference
#include "../../include/langinfo.h"
Functions
char * __nl_langinfo_l (nl_item, locale_t)
Function Documentation
__nl_langinfo_l()
char* __nl_langinfo_l (nl_item item, locale_t loc)
Definition at line 29 of file langinfo.c.
 {
     int cat = item >> 16;
     int idx = item & 65535;
     const char *str;
     if (item == CODESET) return loc->cat[LC_CTYPE] ? "UTF-8" : "ASCII";
     /* _NL_LOCALE_NAME extension */
     if (idx == 65535 && cat < LC_ALL)
         return loc->cat[cat] ? (char *)loc->cat[cat]->name : "C";
     switch (cat) {
     case LC_NUMERIC:
         if (idx > 1) return "";
         str = c_numeric;
         break;
     case LC_TIME:
         if (idx > 0x31) return "";
         str = c_time;
         break;
     case LC_MONETARY:
         if (idx > 0) return "";
         str = "";
         break;
     case LC_MESSAGES:
         if (idx > 3) return "";
         str = c_messages;
         break;
     default:
         return "";
     }
     for (; idx; idx--, str++) for (; *str; str++);
     if (cat != LC_NUMERIC && *str) str = LCTRANS(str, cat, loc);
     return (char *)str;
 }
References c_messages, c_numeric, c_time, CODESET, idx, LC_ALL, LC_CTYPE, LC_MESSAGES, LC_MONETARY, LC_NUMERIC, LC_TIME, LCTRANS, str, and switch().
Referenced by __asctime_r(), __nl_langinfo(), and __strftime_fmt_1().