Fennix: Userspace/apps/base/busybox/applets/usage_pod.c File Reference
usage_pod.c File Reference
#include <unistd.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "autoconf.h"
#include "applet_tables.h"
#include "usage.h"
#include "applets.h"
Data Structures
struct usage_data
Macros
#define SKIP_applet_main
#define ALIGN1 /* nothing, just to placate applet_tables.h */
#define ALIGN2 /* nothing, just to placate applet_tables.h */
#define BB_MMU 1
#define USE_FOR_NOMMU(...)
#define USE_FOR_MMU(...) __VA_ARGS__
#define MAKE_USAGE(aname, usage) { aname, usage },
Functions
static int compare_func (const void *a, const void *b)
int main (void)
Variables
static struct usage_data usage_array []
Data Structure Documentation
usage_data
struct usage_data
Definition at line 26 of file usage.c.
Data Fields
const char * aname
const char * usage
Macro Definition Documentation
ALIGN1
#define ALIGN1 /* nothing, just to placate applet_tables.h */
Definition at line 16 of file usage_pod.c.
ALIGN2
static const struct cp_ext dist ALIGN2 /* nothing, just to placate applet_tables.h */
Definition at line 17 of file usage_pod.c.
Referenced by bb_parse_mode(), ife_print(), ll_type_n2a(), and wcwidth().
BB_MMU
#define BB_MMU 1
Definition at line 26 of file usage_pod.c.
MAKE_USAGE
#define MAKE_USAGE (aname, usage) { aname, usage },
Definition at line 32 of file usage_pod.c.
SKIP_applet_main
#define SKIP_applet_main
Definition at line 15 of file usage_pod.c.
USE_FOR_MMU
#define USE_FOR_MMU (...) __VA_ARGS__
Definition at line 28 of file usage_pod.c.
USE_FOR_NOMMU
#define USE_FOR_NOMMU (...)
Definition at line 27 of file usage_pod.c.
Function Documentation
compare_func()
static int compare_func (const void * a, const void * b) static
Definition at line 40 of file usage_pod.c.
 {
     const struct usage_data *ua = a;
     const struct usage_data *ub = b;
     return strcmp(ua->aname, ub->aname);
 }
References usage_data::aname, and strcmp.
Referenced by main().
main()
int main (void)
Definition at line 47 of file usage_pod.c.
 {
     int col, len2;
     int i;
     int num_messages = sizeof(usage_array) / sizeof(usage_array[0]);
     if (num_messages == 0)
         return 0;
     qsort(usage_array,
         num_messages, sizeof(usage_array[0]),
         compare_func);
     col = 0;
     for (i = 0; i < num_messages; i++) {
         len2 = strlen(usage_array[i].aname) + 2;
         if (col >= 76 - len2) {
             printf(",\n");
             col = 0;
         }
         if (col == 0) {
             col = 6;
             printf("\t");
         } else {
             printf(", ");
         }
         printf("%s", usage_array[i].aname);
         col += len2;
     }
     printf("\n\n");
     printf("=head1 COMMAND DESCRIPTIONS\n\n");
     printf("=over 4\n\n");
     for (i = 0; i < num_messages; i++) {
         if (usage_array[i].aname[0] >= 'a' && usage_array[i].aname[0] <= 'z'
          && usage_array[i].usage[0] != NOUSAGE_STR[0]
         ) {
             printf("=item B<%s>\n\n", usage_array[i].aname);
             if (usage_array[i].usage[0])
                 printf("%s %s\n\n", usage_array[i].aname, usage_array[i].usage);
             else
                 printf("%s\n\n", usage_array[i].aname);
         }
     }
     printf("=back\n\n");
     return 0;
 }
References usage_data::aname, compare_func(), i, NOUSAGE_STR, printf, qsort(), strlen, usage(), and usage_array.
Variable Documentation
usage_array
struct usage_data usage_array[] static
Initial value:
= {
}
Referenced by main().