Fennix Userspace: Userspace/musl/src/termios/tcflush.c File Reference
tcflush.c File Reference
#include <termios.h>
#include <sys/ioctl.h>
Functions
int tcflush (int fd, int queue)
Function Documentation
tcflush()
int tcflush (int fd, int queue)
Definition at line 4 of file tcflush.c.
 {
     return ioctl(fd, TCFLSH, queue);
 }
References fd, ioctl(), queue(), and TCFLSH.
Referenced by bb_ask_noecho(), get_logname(), init_tty_attrs(), login_main(), and receive().