Fennix: Drivers/library/std.c File Reference
std.c File Reference
#include <base.h>
#include <driver.h>
Functions
void * MemoryCopy (void *Destination, const void *Source, size_t Length)
Copy memory.
void * MemorySet (void *Destination, int Value, size_t Length)
Set memory.
void * MemoryMove (void *Destination, const void *Source, size_t Length)
Move memory.
size_t StringLength (const char String[])
String length.
char * strstr (const char *Haystack, const char *Needle)
Variables
__driverAPI * API
Function Documentation
MemoryCopy()
void* MemoryCopy (void * Destination, const void * Source, size_t Length)
Copy memory.
Parameters
Destination The destination
Source The source
Length The length of the memory to copy
Returns
The destination
Definition at line 28 of file std.c.
 {
     return API->memcpy(API->MajorID, Destination, Source, Length);
 }
References API, Length, __driverAPI::MajorID, and __driverAPI::memcpy.
Referenced by MessageReceiveLB(), and MessageSendLB().
MemoryMove()
void* MemoryMove (void * Destination, const void * Source, size_t Length)
Move memory.
Parameters
Destination The destination
Source The source
Length The length of the memory to move
Returns
The destination
Definition at line 38 of file std.c.
 {
     return API->memmove(API->MajorID, Destination, Source, Length);
 }
References API, Length, __driverAPI::MajorID, and __driverAPI::memmove.
MemorySet()
void* MemorySet (void * Destination, int Value, size_t Length)
Set memory.
Parameters
Destination The destination
Value The value to set
Length The length of the memory to set
Returns
The destination
Definition at line 33 of file std.c.
 {
     return API->memset(API->MajorID, Destination, Value, Length);
 }
References API, Length, __driverAPI::MajorID, and __driverAPI::memset.
Referenced by Port::Configure(), Port::Identify(), Port::Port(), and Port::ReadWrite().
StringLength()
size_t StringLength (const char String[])
String length.
Parameters
String The string
Returns
The length of the string
Definition at line 43 of file std.c.
 {
     return API->strlen(API->MajorID, String);
 }
References API, __driverAPI::MajorID, and __driverAPI::strlen.
Referenced by DisplayGetSize(), MessageSend(), MessageSendHB(), and MessageSendLB().
strstr()
char* strstr (const char * Haystack, const char * Needle)
Definition at line 48 of file std.c.
 {
     return API->strstr(API->MajorID, Haystack, Needle);
 }
References API, __driverAPI::MajorID, NULL, and __driverAPI::strstr.
Referenced by __get_resolv_conf(), __lookup_serv(), _nl_init_domain_conv(), add_links(), Driver::api__strstr(), awk_getline(), count_strstr(), create_or_remember_link(), cut_out_ull_opt(), DetectByHPET(), dump_procs(), exec_builtin(), find_action(), find_export_symbols(), get_irqs_from_interrupts(), getjob(), grep_file(), handle_incoming_and_exit(), hasmntopt(), index_status_file(), is_hpet_irq(), is_section_name(), M_StringReplace(), main(), make_device(), MsgEqual(), name_from_hosts(), nmeter_main(), nproc_main(), opt_in_list(), parse_url(), print_direc(), process_includes(), procnetdev_version(), rdval(), read_cstate_counts(), rl_history_search_internal(), rpmalloc_initialize_config(), scan_request(), scan_table(), send_file_and_exit(), singlemount(), strip_unsafe_prefix(), strrstr(), update_passwd(), wget_main(), write_status_file(), and xmalloc_substitute_string().
Variable Documentation
API
__driverAPI* API extern
Definition at line 23 of file base.c.
Referenced by MemoryCopy(), MemoryMove(), MemorySet(), StringLength(), and strstr().