var annotated_dup =
[
    [ "__attribute__", "d9/d97/pci_8h.html#dd/d3f/struct____attribute____", "d9/d97/pci_8h_dd/d3f/struct____attribute____" ],
    [ "__DriverInfo", "db/de4/driver_8h.html#d8/d02/struct____DriverInfo", "db/de4/driver_8h_d8/d02/struct____DriverInfo" ],
    [ "__PCIArray", "db/de4/driver_8h.html#df/d8a/struct____PCIArray", "db/de4/driver_8h_df/d8a/struct____PCIArray" ],
    [ "AccelerometerReport", "de/ded/input_8h.html#d8/d16/structAccelerometerReport", null ],
    [ "FileSystemInfo", "df/d26/fs_8h.html#de/d99/structFileSystemInfo", "df/d26/fs_8h_de/d99/structFileSystemInfo" ],
    [ "GamepadReport", "de/ded/input_8h.html#d6/dda/structGamepadReport", null ],
    [ "GyroscopeReport", "de/ded/input_8h.html#d4/daf/structGyroscopeReport", null ],
    [ "Inode", "df/d26/fs_8h.html#d6/d59/structInode", "df/d26/fs_8h_d6/d59/structInode" ],
    [ "InodeOperations", "db/de6/structInodeOperations.html", "db/de6/structInodeOperations" ],
    [ "InputReport", "de/ded/input_8h.html#d1/d5b/structInputReport", "de/ded/input_8h_d1/d5b/structInputReport" ],
    [ "InputReport.__unnamed23__", "de/ded/input_8h.html#d4/d58/unionInputReport_8____unnamed23____", "de/ded/input_8h_d4/d58/unionInputReport_8____unnamed23____" ],
    [ "InternetProtocol4", "d0/d1e/structInternetProtocol4.html", "d0/d1e/structInternetProtocol4" ],
    [ "JoystickReport", "de/ded/input_8h.html#dd/db1/structJoystickReport", null ],
    [ "kdirent", "df/d26/fs_8h.html#d9/ddf/structkdirent", "df/d26/fs_8h_d9/ddf/structkdirent" ],
    [ "KeyboardReport", "de/ded/input_8h.html#d1/da7/structKeyboardReport", "de/ded/input_8h_d1/da7/structKeyboardReport" ],
    [ "KeyboardReport.__unnamed19__", "de/ded/input_8h.html#de/db9/unionKeyboardReport_8____unnamed19____", "de/ded/input_8h_de/db9/unionKeyboardReport_8____unnamed19____" ],
    [ "KeyboardReport.__unnamed19__.__unnamed21__", "de/ded/input_8h.html#d2/d8e/structKeyboardReport_8____unnamed19_____8____unnamed21____", "de/ded/input_8h_d2/d8e/structKeyboardReport_8____unnamed19_____8____unnamed21____" ],
    [ "kstat", "df/d26/fs_8h.html#d5/df1/structkstat", "df/d26/fs_8h_d5/df1/structkstat" ],
    [ "MagnetometerReport", "de/ded/input_8h.html#d4/d9c/structMagnetometerReport", null ],
    [ "MediaAccessControl", "d0/d48/structMediaAccessControl.html", "d0/d48/structMediaAccessControl" ],
    [ "MouseReport", "de/ded/input_8h.html#db/d9a/structMouseReport", "de/ded/input_8h_db/d9a/structMouseReport" ],
    [ "PS2_CONFIGURATION", "d1/de1/aip_8h.html#d5/d42/unionPS2__CONFIGURATION", "d1/de1/aip_8h_d5/d42/unionPS2__CONFIGURATION" ],
    [ "PS2_CONFIGURATION.__unnamed9__", "d1/de1/aip_8h.html#dd/d65/structPS2__CONFIGURATION_8____unnamed9____", "d1/de1/aip_8h_dd/d65/structPS2__CONFIGURATION_8____unnamed9____" ],
    [ "PS2_KBD_TYPEMATIC", "d1/de1/aip_8h.html#d5/d94/unionPS2__KBD__TYPEMATIC", "d1/de1/aip_8h_d5/d94/unionPS2__KBD__TYPEMATIC" ],
    [ "PS2_KBD_TYPEMATIC.__unnamed13__", "d1/de1/aip_8h.html#d1/d4c/structPS2__KBD__TYPEMATIC_8____unnamed13____", "d1/de1/aip_8h_d1/d4c/structPS2__KBD__TYPEMATIC_8____unnamed13____" ],
    [ "PS2_KBD_TYPEMATIC.__unnamed1__", "d7/df4/kbd_8h.html#df/d7c/structPS2__KBD__TYPEMATIC_8____unnamed1____", "d7/df4/kbd_8h_df/d7c/structPS2__KBD__TYPEMATIC_8____unnamed1____" ],
    [ "PS2_MOUSE_PACKET", "d1/de1/aip_8h.html#d3/d18/structPS2__MOUSE__PACKET", "d1/de1/aip_8h_d3/d18/structPS2__MOUSE__PACKET" ],
    [ "PS2_MOUSE_PACKET.Base", "d1/de1/aip_8h.html#d0/df2/unionPS2__MOUSE__PACKET_8Base", "d1/de1/aip_8h_d0/df2/unionPS2__MOUSE__PACKET_8Base" ],
    [ "PS2_MOUSE_PACKET.ZMovement", "d1/de1/aip_8h.html#d3/d3e/unionPS2__MOUSE__PACKET_8ZMovement", "d1/de1/aip_8h_d3/d3e/unionPS2__MOUSE__PACKET_8ZMovement" ],
    [ "PS2_OUTPUT_PORT", "d1/de1/aip_8h.html#da/dc6/unionPS2__OUTPUT__PORT", "d1/de1/aip_8h_da/dc6/unionPS2__OUTPUT__PORT" ],
    [ "PS2_OUTPUT_PORT.__unnamed11__", "d1/de1/aip_8h.html#db/d00/structPS2__OUTPUT__PORT_8____unnamed11____", "d1/de1/aip_8h_db/d00/structPS2__OUTPUT__PORT_8____unnamed11____" ],
    [ "PS2_STATUSES", "d1/de1/aip_8h.html#d7/d48/unionPS2__STATUSES", "d1/de1/aip_8h_d7/d48/unionPS2__STATUSES" ],
    [ "PS2_STATUSES.__unnamed7__", "d1/de1/aip_8h.html#dd/daa/structPS2__STATUSES_8____unnamed7____", "d1/de1/aip_8h_dd/daa/structPS2__STATUSES_8____unnamed7____" ],
    [ "SuperBlockOperations", "d2/d55/structSuperBlockOperations.html", "d2/d55/structSuperBlockOperations" ],
    [ "TouchScreenReport", "de/ded/input_8h.html#d1/df2/structTouchScreenReport", "de/ded/input_8h_d1/df2/structTouchScreenReport" ]
];