Fennix: Userspace/apps/base/bash/lib/sh/tmpfile.c File Reference
tmpfile.c File Reference
#include <config.h>
#include <bashtypes.h>
#include <posixstat.h>
#include <posixtime.h>
#include <filecntl.h>
#include <bashansi.h>
#include <stdio.h>
#include <errno.h>
#include <shell.h>
Macros
#define BASEOPENFLAGS (O_CREAT | O_TRUNC | O_EXCL | O_BINARY)
#define DEFAULT_TMPDIR "." /* bogus default, should be changed */
#define DEFAULT_NAMEROOT "shtmp"
#define random() rand()
Functions
static char *get_sys_tmpdir PARAMS ((void))
static char *get_tmpdir PARAMS ((int))
static char * get_sys_tmpdir ()
static char * get_tmpdir (int flags)
static void sh_seedrand ()
char * sh_mktmpname (char *nameroot, int flags)
int sh_mktmpfd (char *nameroot, int flags, char **namep)
FILE * sh_mktmpfp (char *nameroot, int flags, char **namep)
char * sh_mktmpdir (char *nameroot, int flags)
Variables
int errno
pid_t dollar_dollar_pid
static char * sys_tmpdir = (char *)NULL
static int ntmpfiles
static int tmpnamelen = -1
static unsigned long filenum = 1L
Macro Definition Documentation
BASEOPENFLAGS
#define BASEOPENFLAGS (O_CREAT | O_TRUNC | O_EXCL | O_BINARY)
Definition at line 45 of file tmpfile.c.
DEFAULT_NAMEROOT
#define DEFAULT_NAMEROOT "shtmp"
Definition at line 48 of file tmpfile.c.
DEFAULT_TMPDIR
#define DEFAULT_TMPDIR "." /* bogus default, should be changed */
Definition at line 47 of file tmpfile.c.
random
#define random (void) rand()
Definition at line 52 of file tmpfile.c.
Function Documentation
get_sys_tmpdir()
static char* get_sys_tmpdir () static
Definition at line 66 of file tmpfile.c.
 {
   if (sys_tmpdir)
     return sys_tmpdir;
 #ifdef P_tmpdir
   sys_tmpdir = P_tmpdir;
   if (file_iswdir (sys_tmpdir))
     return sys_tmpdir;
 #endif
   sys_tmpdir = "/tmp";
   if (file_iswdir (sys_tmpdir))
     return sys_tmpdir;
   sys_tmpdir = "/var/tmp";
   if (file_iswdir (sys_tmpdir))
     return sys_tmpdir;
   sys_tmpdir = "/usr/tmp";
   if (file_iswdir (sys_tmpdir))
     return sys_tmpdir;
   sys_tmpdir = DEFAULT_TMPDIR;
   return sys_tmpdir;
 }
References DEFAULT_TMPDIR, file_iswdir(), and sys_tmpdir.
Referenced by get_tmpdir().
get_tmpdir()
static char* get_tmpdir (int flags) static
Definition at line 95 of file tmpfile.c.
 {
   char *tdir;
   tdir = (flags & MT_USETMPDIR) ? get_string_value ("TMPDIR") : (char *)NULL;
   if (tdir && (file_iswdir (tdir) == 0 || strlen (tdir) > PATH_MAX))
     tdir = 0;
   if (tdir == 0)
     tdir = get_sys_tmpdir ();
 #if defined (HAVE_PATHCONF) && defined (_PC_NAME_MAX)
   if (tmpnamelen == -1)
     tmpnamelen = pathconf (tdir, _PC_NAME_MAX);
 #else
   tmpnamelen = 0;
 #endif
   return tdir;
 }
References _PC_NAME_MAX, file_iswdir(), flags, get_string_value(), get_sys_tmpdir(), MT_USETMPDIR, NULL, PATH_MAX, pathconf(), strlen(), tdir, and tmpnamelen.
Referenced by sh_mktmpdir(), sh_mktmpfd(), and sh_mktmpname().
PARAMS() [1/2]
static char* get_tmpdir PARAMS ((int)) static
PARAMS() [2/2]
static char* get_sys_tmpdir PARAMS ((void)) static
sh_mktmpdir()
char* sh_mktmpdir (char * nameroot, int flags)
Definition at line 266 of file tmpfile.c.
 {
   char *filename, *tdir, *lroot, *dirname;
   int fd, tdlen;
 #ifdef USE_MKDTEMP
   filename = (char *)xmalloc (PATH_MAX + 1);
   tdir = get_tmpdir (flags);
   tdlen = strlen (tdir);
   lroot = nameroot ? nameroot : DEFAULT_NAMEROOT;
   if (nameroot == 0)
     flags &= ~MT_TEMPLATE;
   if ((flags & MT_TEMPLATE) && strlen (nameroot) > PATH_MAX)
     flags &= ~MT_TEMPLATE;
   if (flags & MT_TEMPLATE)
     strcpy (filename, nameroot);
   else
     sprintf (filename, "%s/%s.XXXXXX", tdir, lroot);
   dirname = mkdtemp (filename);
   if (dirname == 0)
     {
       free (filename);
       filename = NULL;
     }
   return dirname;
 #else /* !USE_MKDTEMP */
   filename = (char *)NULL;
   do
     {
       filename = sh_mktmpname (nameroot, flags);
       fd = mkdir (filename, 0700);
       if (fd == 0)
     break;
       free (filename);
       filename = (char *)NULL;
     }
   while (fd < 0 && errno == EEXIST);
   return (filename);
 #endif /* !USE_MKDTEMP */
 }
References DEFAULT_NAMEROOT, dirname, EEXIST, errno, fd, filename, flags, free, get_tmpdir(), mkdir(), mkdtemp(), MT_TEMPLATE, NULL, PATH_MAX, sh_mktmpname(), sprintf(), strcpy, strlen(), tdir, and xmalloc.
Referenced by mktemp_builtin().
sh_mktmpfd()
int sh_mktmpfd (char * nameroot, int flags, char ** namep)
Definition at line 190 of file tmpfile.c.
 {
   char *filename, *tdir, *lroot;
   int fd, tdlen;
   filename = (char *)xmalloc (PATH_MAX + 1);
   tdir = get_tmpdir (flags);
   tdlen = strlen (tdir);
   lroot = nameroot ? nameroot : DEFAULT_NAMEROOT;
   if (nameroot == 0)
     flags &= ~MT_TEMPLATE;
   if ((flags & MT_TEMPLATE) && strlen (nameroot) > PATH_MAX)
     flags &= ~MT_TEMPLATE;
 #ifdef USE_MKSTEMP
   if (flags & MT_TEMPLATE)
     strcpy (filename, nameroot);
   else
     sprintf (filename, "%s/%s.XXXXXX", tdir, lroot);
   fd = mkstemp (filename);
   if (fd < 0 || namep == 0)
     {
       free (filename);
       filename = NULL;
     }
   if (namep)
     *namep = filename;
   return fd;
 #else /* !USE_MKSTEMP */
   sh_seedrand ();
   do
     {
       filenum = (filenum << 1) ^
         (unsigned long) time ((time_t *)0) ^
         (unsigned long) dollar_dollar_pid ^
         (unsigned long) ((flags & MT_USERANDOM) ? random () : ntmpfiles++);
       sprintf (filename, "%s/%s-%lu", tdir, lroot, filenum);
       if (tmpnamelen > 0 && tmpnamelen < 32)
     filename[tdlen + 1 + tmpnamelen] = '\0';
       fd = open (filename, BASEOPENFLAGS | ((flags & MT_READWRITE) ? O_RDWR : O_WRONLY), 0600);
     }
   while (fd < 0 && errno == EEXIST);
   if (namep)
     *namep = filename;
   else
     free (filename);
   return fd;
 #endif /* !USE_MKSTEMP */
 }
References BASEOPENFLAGS, DEFAULT_NAMEROOT, dollar_dollar_pid, EEXIST, errno, fd, filename, filenum, flags, free, get_tmpdir(), mkstemp(), MT_READWRITE, MT_TEMPLATE, MT_USERANDOM, ntmpfiles, NULL, O_RDWR, O_WRONLY, open(), PATH_MAX, random, sh_seedrand(), sprintf(), strcpy, strlen(), tdir, time(), tmpnamelen, and xmalloc.
Referenced by here_document_to_fd(), mktemp_builtin(), and sh_mktmpfp().
sh_mktmpfp()
FILE* sh_mktmpfp (char * nameroot, int flags, char ** namep)
Definition at line 248 of file tmpfile.c.
 {
   int fd;
   FILE *fp;
   fd = sh_mktmpfd (nameroot, flags, namep);
   if (fd < 0)
     return ((FILE *)NULL);
   fp = fdopen (fd, (flags & MT_READWRITE) ? "w+" : "w");
   if (fp == 0)
     close (fd);
   return fp;
 }
References close(), fd, flags, MT_READWRITE, NULL, and sh_mktmpfd().
sh_mktmpname()
char* sh_mktmpname (char * nameroot, int flags)
Definition at line 135 of file tmpfile.c.
 {
   char *filename, *tdir, *lroot;
   struct stat sb;
   int r, tdlen;
   static int seeded = 0;
   filename = (char *)xmalloc (PATH_MAX + 1);
   tdir = get_tmpdir (flags);
   tdlen = strlen (tdir);
   lroot = nameroot ? nameroot : DEFAULT_NAMEROOT;
   if (nameroot == 0)
     flags &= ~MT_TEMPLATE;
   if ((flags & MT_TEMPLATE) && strlen (nameroot) > PATH_MAX)
     flags &= ~MT_TEMPLATE;
 #ifdef USE_MKTEMP
   if (flags & MT_TEMPLATE)
     strcpy (filename, nameroot);
   else
     sprintf (filename, "%s/%s.XXXXXX", tdir, lroot);
   if (mktemp (filename) == 0)
     {
       free (filename);
       filename = NULL;
     }
 #else  /* !USE_MKTEMP */
   sh_seedrand ();
   while (1)
     {
       filenum = (filenum << 1) ^
         (unsigned long) time ((time_t *)0) ^
         (unsigned long) dollar_dollar_pid ^
         (unsigned long) ((flags & MT_USERANDOM) ? random () : ntmpfiles++);
       sprintf (filename, "%s/%s-%lu", tdir, lroot, filenum);
       if (tmpnamelen > 0 && tmpnamelen < 32)
     filename[tdlen + 1 + tmpnamelen] = '\0';
 #  ifdef HAVE_LSTAT
       r = lstat (filename, &sb);
 #  else
       r = stat (filename, &sb);
 #  endif
       if (r < 0 && errno == ENOENT)
     break;
     }
 #endif /* !USE_MKTEMP */
   return filename;
 }
References DEFAULT_NAMEROOT, dollar_dollar_pid, ENOENT, errno, filename, filenum, flags, free, get_tmpdir(), lstat, mktemp(), MT_TEMPLATE, MT_USERANDOM, ntmpfiles, NULL, PATH_MAX, random, sh_seedrand(), sprintf(), stat(), strcpy, strlen(), tdir, time(), tmpnamelen, and xmalloc.
Referenced by sh_mktmpdir().
sh_seedrand()
static void sh_seedrand () static
Definition at line 118 of file tmpfile.c.
 {
 #if HAVE_RANDOM
   int d;
   static int seeded = 0;
   if (seeded == 0)
     {
       struct timeval tv;
       gettimeofday (&tv, NULL);
       srandom (tv.tv_sec ^ tv.tv_usec ^ (getpid () << 16) ^ (uintptr_t)&d);
       seeded = 1;
     }
 #endif
 }
References getpid(), gettimeofday(), NULL, srandom(), timeval::tv_sec, and timeval::tv_usec.
Referenced by sh_mktmpfd(), and sh_mktmpname().
Variable Documentation
dollar_dollar_pid
pid_t dollar_dollar_pid extern
Definition at line 164 of file variables.c.
Referenced by sh_mktmpfd(), and sh_mktmpname().
errno
int errno extern
Referenced by sh_mktmpdir(), sh_mktmpfd(), and sh_mktmpname().
filenum
unsigned long filenum = 1L static
Definition at line 63 of file tmpfile.c.
Referenced by sh_mktmpfd(), and sh_mktmpname().
ntmpfiles
int ntmpfiles static
Definition at line 61 of file tmpfile.c.
Referenced by sh_mktmpfd(), and sh_mktmpname().
sys_tmpdir
char* sys_tmpdir = (char *)NULL static
Definition at line 60 of file tmpfile.c.
Referenced by get_sys_tmpdir().
tmpnamelen
int tmpnamelen = -1 static
Definition at line 62 of file tmpfile.c.
Referenced by get_tmpdir(), sh_mktmpfd(), and sh_mktmpname().