Fennix: Userspace/mlibc/options/posix/include/netinet/in.h File Reference
in.h File Reference
#include <stdint.h>
#include <endian.h>
#include <sys/socket.h>
#include <abi-bits/socket.h>
#include <abi-bits/in.h>
#include <arpa/inet.h>
Macros
#define IN6_IS_ADDR_UNSPECIFIED(a)
#define IN6_IS_ADDR_LOOPBACK(a)
#define IN6_IS_ADDR_MULTICAST(a) (((const uint8_t *) (a))[0] == 0xff)
#define IN6_IS_ADDR_LINKLOCAL(a)
#define IN6_IS_ADDR_SITELOCAL(a)
#define IN6_IS_ADDR_V4MAPPED(a)
#define __ARE_4_BYTE_EQUAL(a, b)
#define IN6_ARE_ADDR_EQUAL(a, b) __ARE_4_BYTE_EQUAL((const uint32_t *)(a), (const uint32_t *)(b))
#define IN6_IS_ADDR_V4COMPAT 7
#define IN6_IS_ADDR_MC_NODELOCAL(a)
#define IN6_IS_ADDR_MC_LINKLOCAL(a)
#define IN6_IS_ADDR_MC_SITELOCAL(a)
#define IN6_IS_ADDR_MC_ORGLOCAL(a)
#define IN6_IS_ADDR_MC_GLOBAL(a)
#define IN_CLASSA(a) ((((in_addr_t)(a)) & 0x80000000) == 0)
#define IN_CLASSA_NET 0xff000000
#define IN_CLASSA_NSHIFT 24
#define IN_CLASSA_HOST (0xffffffff & ~IN_CLASSA_NET)
#define IN_CLASSA_MAX 128
#define IN_CLASSB(a) ((((in_addr_t)(a)) & 0xc0000000) == 0x80000000)
#define IN_CLASSB_NET 0xffff0000
#define IN_CLASSB_NSHIFT 16
#define IN_CLASSB_HOST (0xffffffff & ~IN_CLASSB_NET)
#define IN_CLASSB_MAX 65536
#define IN_CLASSC(a) ((((in_addr_t)(a)) & 0xe0000000) == 0xc0000000)
#define IN_CLASSC_NET 0xffffff00
#define IN_CLASSC_NSHIFT 8
#define IN_CLASSC_HOST (0xffffffff & ~IN_CLASSC_NET)
#define IN_CLASSD(a) ((((in_addr_t)(a)) & 0xf0000000) == 0xe0000000)
#define IN_MULTICAST(a) IN_CLASSD(a)
#define IN_EXPERIMENTAL(a) ((((in_addr_t)(a)) & 0xe0000000) == 0xe0000000)
#define IN_BADCLASS(a) ((((in_addr_t)(a)) & 0xf0000000) == 0xf0000000)
#define IN_LOOPBACKNET 127
#define MCAST_EXCLUDE 0
#define MCAST_INCLUDE 1
Functions
uint32_t htonl (uint32_t)
uint16_t htons (uint16_t)
uint32_t ntohl (uint32_t)
uint16_t ntohs (uint16_t)
Variables
const struct in6_addr in6addr_any
const struct in6_addr in6addr_loopback
Macro Definition Documentation
__ARE_4_BYTE_EQUAL
#define __ARE_4_BYTE_EQUAL (a, b)
Value:
    ((a)[0] == (b)[0] && (a)[1] == (b)[1] && (a)[2] == (b)[2] && \
     (a)[3] == (b)[3] && (a)[4] == (b)[4])
Definition at line 53 of file in.h.
IN6_ARE_ADDR_EQUAL
#define IN6_ARE_ADDR_EQUAL (a, b) __ARE_4_BYTE_EQUAL((const uint32_t *)(a), (const uint32_t *)(b))
Definition at line 56 of file in.h.
IN6_IS_ADDR_LINKLOCAL
#define IN6_IS_ADDR_LINKLOCAL (a)
Value:
    ({ \
    uint32_t *_a = (uint32_t *)(((struct in6_addr *) a)->s6_addr); \
    _a[0] & htonl(0xffc00000) == htonl(0xfe800000); \
})
Definition at line 39 of file in.h.
IN6_IS_ADDR_LOOPBACK
#define IN6_IS_ADDR_LOOPBACK (a)
Value:
    ({ \
    uint32_t *_a = (uint32_t *)(((struct in6_addr *) a)->s6_addr); \
    !_a[0] && \
    !_a[1] && \
    !_a[2] && \
     _a[3] == htonl(0x0001); \
})
Definition at line 31 of file in.h.
IN6_IS_ADDR_MC_GLOBAL
#define IN6_IS_ADDR_MC_GLOBAL (a)
Value:
    ({ \
    (IN6_IS_ADDR_MULTICAST(a) && \
    ((((const uint8_t *)(a))[1] & 0xf) == 0xe)); \
})
Definition at line 76 of file in.h.
IN6_IS_ADDR_MC_LINKLOCAL
#define IN6_IS_ADDR_MC_LINKLOCAL (a)
Value:
    ({ \
    (IN6_IS_ADDR_MULTICAST(a) && \
    ((((const uint8_t *)(a))[1] & 0xf) == 0x2)); \
})
Definition at line 64 of file in.h.
IN6_IS_ADDR_MC_NODELOCAL
#define IN6_IS_ADDR_MC_NODELOCAL (a)
Value:
    ({ \
    (IN6_IS_ADDR_MULTICAST(a) && \
    ((((const uint8_t *)(a))[1] & 0xf) == 0x1)); \
})
Definition at line 60 of file in.h.
IN6_IS_ADDR_MC_ORGLOCAL
#define IN6_IS_ADDR_MC_ORGLOCAL (a)
Value:
    ({ \
    (IN6_IS_ADDR_MULTICAST(a) && \
    ((((const uint8_t *)(a))[1] & 0xf) == 0x8)); \
})
Definition at line 72 of file in.h.
IN6_IS_ADDR_MC_SITELOCAL
#define IN6_IS_ADDR_MC_SITELOCAL (a)
Value:
    ({ \
    (IN6_IS_ADDR_MULTICAST(a) && \
    ((((const uint8_t *)(a))[1] & 0xf) == 0x5)); \
})
Definition at line 68 of file in.h.
IN6_IS_ADDR_MULTICAST
#define IN6_IS_ADDR_MULTICAST (a) (((const uint8_t *) (a))[0] == 0xff)
Definition at line 38 of file in.h.
IN6_IS_ADDR_SITELOCAL
#define IN6_IS_ADDR_SITELOCAL (a)
Value:
    ({ \
    uint32_t *_a = (uint32_t *)(((struct in6_addr *) a)->s6_addr); \
    _a[0] & htonl(0xffc00000) == htonl(0xfec00000); \
})
Definition at line 43 of file in.h.
IN6_IS_ADDR_UNSPECIFIED
#define IN6_IS_ADDR_UNSPECIFIED (a)
Value:
    ({ \
    uint32_t *_a = (uint32_t *)(((struct in6_addr *) a)->s6_addr); \
    !_a[0] && \
    !_a[1] && \
    !_a[2] && \
    !_a[3];  \
})
Definition at line 24 of file in.h.
IN6_IS_ADDR_V4COMPAT
#define IN6_IS_ADDR_V4COMPAT 7
Definition at line 59 of file in.h.
IN6_IS_ADDR_V4MAPPED
#define IN6_IS_ADDR_V4MAPPED (a)
Value:
    ({ \
    uint32_t *_a = (uint32_t *)(((struct in6_addr *) a)->s6_addr); \
    !_a[0] && \
    !_a[1] && \
     _a[2] == htonl(0xffff); \
})
Definition at line 47 of file in.h.
IN_BADCLASS
#define IN_BADCLASS (a) ((((in_addr_t)(a)) & 0xf0000000) == 0xf0000000)
Definition at line 98 of file in.h.
IN_CLASSA
#define IN_CLASSA (a) ((((in_addr_t)(a)) & 0x80000000) == 0)
Definition at line 81 of file in.h.
IN_CLASSA_HOST
#define IN_CLASSA_HOST (0xffffffff & ~IN_CLASSA_NET)
Definition at line 84 of file in.h.
IN_CLASSA_MAX
#define IN_CLASSA_MAX 128
Definition at line 85 of file in.h.
IN_CLASSA_NET
#define IN_CLASSA_NET 0xff000000
Definition at line 82 of file in.h.
IN_CLASSA_NSHIFT
#define IN_CLASSA_NSHIFT 24
Definition at line 83 of file in.h.
IN_CLASSB
#define IN_CLASSB (a) ((((in_addr_t)(a)) & 0xc0000000) == 0x80000000)
Definition at line 86 of file in.h.
IN_CLASSB_HOST
#define IN_CLASSB_HOST (0xffffffff & ~IN_CLASSB_NET)
Definition at line 89 of file in.h.
IN_CLASSB_MAX
#define IN_CLASSB_MAX 65536
Definition at line 90 of file in.h.
IN_CLASSB_NET
#define IN_CLASSB_NET 0xffff0000
Definition at line 87 of file in.h.
IN_CLASSB_NSHIFT
#define IN_CLASSB_NSHIFT 16
Definition at line 88 of file in.h.
IN_CLASSC
#define IN_CLASSC (a) ((((in_addr_t)(a)) & 0xe0000000) == 0xc0000000)
Definition at line 91 of file in.h.
IN_CLASSC_HOST
#define IN_CLASSC_HOST (0xffffffff & ~IN_CLASSC_NET)
Definition at line 94 of file in.h.
IN_CLASSC_NET
#define IN_CLASSC_NET 0xffffff00
Definition at line 92 of file in.h.
IN_CLASSC_NSHIFT
#define IN_CLASSC_NSHIFT 8
Definition at line 93 of file in.h.
IN_CLASSD
#define IN_CLASSD (a) ((((in_addr_t)(a)) & 0xf0000000) == 0xe0000000)
Definition at line 95 of file in.h.
IN_EXPERIMENTAL
#define IN_EXPERIMENTAL (a) ((((in_addr_t)(a)) & 0xe0000000) == 0xe0000000)
Definition at line 97 of file in.h.
IN_LOOPBACKNET
#define IN_LOOPBACKNET 127
Definition at line 100 of file in.h.
IN_MULTICAST
#define IN_MULTICAST (a) IN_CLASSD(a)
Definition at line 96 of file in.h.
MCAST_EXCLUDE
#define MCAST_EXCLUDE 0
Definition at line 102 of file in.h.
MCAST_INCLUDE
#define MCAST_INCLUDE 1
Definition at line 103 of file in.h.
Function Documentation
htonl()
uint32_t htonl (uint32_t x)
Definition at line 15 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint32_t>::byteswap(x);
 #else
     return x;
 #endif
 }
References x.
Referenced by inet_aton(), inet_ntoa(), main(), and socket_setup().
htons()
uint16_t htons (uint16_t x)
Definition at line 22 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint16_t>::byteswap(x);
 #else
     return x;
 #endif
 }
References x.
Referenced by getaddrinfo(), getservbyname(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), main(), and socket_setup().
ntohl()
uint32_t ntohl (uint32_t x)
Definition at line 29 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint32_t>::byteswap(x);
 #else
     return x;
 #endif
 }
References x.
ntohs()
uint16_t ntohs (uint16_t x)
Definition at line 36 of file arpa-inet-stubs.cpp.
{
 #if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
     return mlibc::bit_util<uint16_t>::byteswap(x);
 #else
     return x;
 #endif
 }
References x.
Referenced by getservbyport(), mlibc::lookup_addr_dns(), and mlibc::lookup_name_dns().
Variable Documentation
in6addr_any
const struct in6_addr in6addr_any extern
Definition at line 1 of file arpa-inet-stubs.cpp.
in6addr_loopback
const struct in6_addr in6addr_loopback extern
Definition at line 1 of file arpa-inet-stubs.cpp.