Fennix Userspace: Userspace/apps/base/bash/lib/readline/histlib.h File Reference
histlib.h File Reference
#include <strings.h>
Macros
#define STREQ(a, b) (((a)[0] == (b)[0]) && (strcmp ((a), (b)) == 0))
#define STREQN(a, b, n)
#define savestring(x) strcpy (xmalloc (1 + strlen (x)), (x))
#define whitespace(c) (((c) == ' ') || ((c) == '\t'))
#define _rl_digit_p(c) ((c) >= '0' && (c) <= '9')
#define _rl_digit_value(c) ((c) - '0')
#define member(c, s) ((c) ? ((char *)strchr ((s), (c)) != (char *)NULL) : 0)
#define FREE(x) if (x) free (x)
#define EVENT_NOT_FOUND 0
#define BAD_WORD_SPEC 1
#define SUBST_FAILED 2
#define BAD_MODIFIER 3
#define NO_PREV_SUBST 4
#define NON_ANCHORED_SEARCH 0
#define ANCHORED_SEARCH 0x01
#define PATTERN_SEARCH 0x02
#define HISTORY_APPEND 0
#define HISTORY_OVERWRITE 1
Functions
char * strchr ()
int _hs_history_patsearch (const char *, int, int)
void _hs_replace_history_data (int, histdata_t *, histdata_t *)
int _hs_at_end_of_history (void)
void _hs_append_history_line (int, const char *)
Macro Definition Documentation
_rl_digit_p
#define _rl_digit_p (c) ((c) >= '0' && (c) <= '9')
Definition at line 46 of file histlib.h.
_rl_digit_value
#define _rl_digit_value (c) ((c) - '0')
Definition at line 50 of file histlib.h.
ANCHORED_SEARCH
#define ANCHORED_SEARCH 0x01
Definition at line 73 of file histlib.h.
BAD_MODIFIER
#define BAD_MODIFIER 3
Definition at line 68 of file histlib.h.
BAD_WORD_SPEC
#define BAD_WORD_SPEC 1
Definition at line 66 of file histlib.h.
EVENT_NOT_FOUND
#define EVENT_NOT_FOUND 0
Definition at line 65 of file histlib.h.
FREE
#define FREE (x) if (x) free (x)
Definition at line 61 of file histlib.h.
HISTORY_APPEND
#define HISTORY_APPEND 0
Definition at line 77 of file histlib.h.
HISTORY_OVERWRITE
#define HISTORY_OVERWRITE 1
Definition at line 78 of file histlib.h.
member
#define member (c, s) ((c) ? ((char *)strchr ((s), (c)) != (char *)NULL) : 0)
Definition at line 57 of file histlib.h.
NO_PREV_SUBST
#define NO_PREV_SUBST 4
Definition at line 69 of file histlib.h.
NON_ANCHORED_SEARCH
#define NON_ANCHORED_SEARCH 0
Definition at line 72 of file histlib.h.
PATTERN_SEARCH
#define PATTERN_SEARCH 0x02
Definition at line 74 of file histlib.h.
savestring
#define savestring (x) strcpy (xmalloc (1 + strlen (x)), (x))
Definition at line 38 of file histlib.h.
STREQ
#define STREQ (a, b) (((a)[0] == (b)[0]) && (strcmp ((a), (b)) == 0))
Definition at line 32 of file histlib.h.
STREQN
#define STREQN (a, b, n)
Value:
                    (((n) == 0) ? (1) \
                    : ((a)[0] == (b)[0]) && (strncmp ((a), (b), (n)) == 0))
Definition at line 33 of file histlib.h.
SUBST_FAILED
#define SUBST_FAILED 2
Definition at line 67 of file histlib.h.
whitespace
#define whitespace (c) (((c) == ' ') || ((c) == '\t'))
Definition at line 42 of file histlib.h.
Function Documentation
_hs_append_history_line()
void _hs_append_history_line (int which, const char * line)
Definition at line 410 of file history.c.
 {
   HIST_ENTRY *hent;
   size_t newlen, curlen, minlen;
   char *newline;
   hent = the_history[which];
   curlen = strlen (hent->line);
   minlen = curlen + strlen (line) + 2;  /* min space needed */
   if (curlen > 256)     /* XXX - for now */
     {
       newlen = 512;     /* now realloc in powers of 2 */
       /* we recalcluate every time; the operations are cheap */
       while (newlen < minlen)
     newlen <<= 1;
     }
   else
     newlen = minlen;
   /* Assume that realloc returns the same pointer and doesn't try a new
      alloc/copy if the new size is the same as the one last passed. */
   newline = realloc (hent->line, newlen);
   if (newline)
     {
       hent->line = newline;
       hent->line[curlen++] = '\n';
       strcpy (hent->line + curlen, line);
     }
 }
References _hist_entry::line, newline(), realloc, strcpy(), strlen(), and the_history.
Referenced by read_history_range().
_hs_at_end_of_history()
int _hs_at_end_of_history (void)
Definition at line 171 of file history.c.
 {
   return (the_history == 0 || history_offset == history_length);
 }
References history_length, history_offset, and the_history.
_hs_history_patsearch()
int _hs_history_patsearch (const char * string, int direction, int flags)
Definition at line 199 of file histsearch.c.
 {
   char *pat;
   size_t len, start;
   int ret, unescaped_backslash;
 #if defined (HAVE_FNMATCH)
   /* Assume that the string passed does not have a leading `^' and any
      anchored search request is captured in FLAGS */
   len = strlen (string);
   ret = len - 1;
   /* fnmatch is required to reject a pattern that ends with an unescaped
      backslash */
   if (unescaped_backslash = (string[ret] == '\\'))
     {
       while (ret > 0 && string[--ret] == '\\')
     unescaped_backslash = 1 - unescaped_backslash;
     }
   if (unescaped_backslash)
     return -1;
   pat = (char *)xmalloc (len + 3);
   /* If the search string is not anchored, we'll be calling fnmatch (assuming
      we have it). Prefix a `*' to the front of the search string so we search
      anywhere in the line. */
   if ((flags & ANCHORED_SEARCH) == 0 && string[0] != '*')
     {
       pat[0] = '*';
       start = 1;
       len++;
     }
   else
     {
       start = 0;
     }
   /* Attempt to reduce the number of searches by tacking a `*' onto the end
      of a pattern that doesn't have one.  Assume a pattern that ends in a
      backslash contains an even number of trailing backslashes; we check
      above */
   strcpy (pat + start, string);
   if (pat[len - 1] != '*')
     {
       pat[len] = '*';       /* XXX */
       pat[len+1] = '\0';
     }
 #else
   pat = string;
 #endif
   ret = history_search_internal (pat, direction, flags|PATTERN_SEARCH);
   if (pat != string)
     xfree (pat);
   return ret;
 }
References ANCHORED_SEARCH, flags, history_search_internal(), pat, PATTERN_SEARCH, start, strcpy(), string, strlen(), xfree, and xmalloc.
Referenced by noninc_search_from_pos().
_hs_replace_history_data()
void _hs_replace_history_data (int which, histdata_t * old, histdata_t * new)
Definition at line 446 of file history.c.
 {
   HIST_ENTRY *entry;
   register int i, last;
   if (which < -2 || which >= history_length || history_length == 0 || the_history == 0)
     return;
   if (which >= 0)
     {
       entry = the_history[which];
       if (entry && entry->data == old)
     entry->data = new;
       return;
     }
   last = -1;
   for (i = 0; i < history_length; i++)
     {
       entry = the_history[i];
       if (entry == 0)
     continue;
       if (entry->data == old)
     {
       last = i;
       if (which == -1)
         entry->data = new;
     }
     }
   if (which == -2 && last >= 0)
     {
       entry = the_history[last];
       entry->data = new;    /* XXX - we don't check entry->old */
     }
 }
References entry::data, history_length, i, last, old, and the_history.
Referenced by rl_do_undo(), and rl_free_undo_list().
strchr()
char* strchr ()
Referenced by __execvpe(), __fdopen(), __fmodeflags(), __get_resolv_conf(), __getgrent_a(), __getpwent_a(), __lookup_ipliteral(), __lookup_serv(), __parsespent(), _nl_explode_name(), _nl_init_domain_conv(), _rl_find_completion_word(), _rl_isearch_dispatch(), a64l(), add_cmd_block(), add_links(), add_MANPATH(), add_split_dependencies(), append_mount_options(), argz_next__(), awk_getline(), awk_main(), awk_printf(), bb_dump_size(), bb_unsetenv(), bpad(), builtin_arrayref_flags(), builtin_source(), catopen(), char_insert(), chmod_main(), chpasswd_main(), cmdio_get_cmd_and_arg(), compile_fs_type(), conf_expand_value(), conf_read_simple(), config_read(), create_fs_device(), data_extract_all(), date_main(), dcngettext(), dd_main(), decode_one_format(), decode_prompt_string(), dequote_escapes(), dequote_string(), dialog_menu(), display_single(), do_cmd(), do_glob(), do_logging(), do_tunnels_list(), do_tzset(), dsvsplit(), dump_procs(), edir(), edit_file(), encode_string(), encode_then_append_var_plusminus(), env_main(), escape(), EscapeShellString(), evalvar(), execute_intern_function(), expand_on_ifs(), expand_one_var(), expand_prompt(), expand_string_to_string(), expand_vars_to_list(), exportcmd(), extract_dollar_brace_string(), extract_filename(), extract_heredoc_dolbrace_string(), find_command(), find_dot_file(), find_executable(), find_matching_open(), find_pair(), find_range(), first_alpha(), fix_assignment_words(), fixup_rpath(), fmemopen(), fmt_num(), fmt_url(), fmtmsg(), fopen(), fopencookie(), fsck_device(), fsck_main(), fstype_matches(), generate_output(), get_addr_1(), get_flag(), get_irqs_from_interrupts(), get_linux_version_code(), get_modinfo_value(), get_prefix_1(), get_rt_realms(), get_uidgid(), get_username_or_die(), getmntent_r(), getNum(), getprec(), getspnam_r(), getsubopt(), handle_incoming_and_exit(), hasmeta(), hexdump_main(), hush_main(), ifconfig_main(), ifplugd_main(), ifsbreakup(), ifupdown_main(), index(), INET_setroute(), init(), inotifyd_main(), internal_getopt(), iprule_modify(), ll_addr_a2n(), load_library(), locale_charset(), logdir_open(), lpd_main(), lpqr_main(), lsscsi_main(), main(), make_here_document(), make_path(), make_quoted_replacement(), man_main(), match_opt(), mbschr(), md5_sha1_sum_main(), mklocal(), mknod_main(), name_from_hosts(), name_to_dev_t(), nfsmount(), nmeter_main(), ntp_init(), o_addqchr(), o_addQchr(), obscure_msg(), od_main(), only_changed_user(), parse(), parse_and_add_kcmdline_module_options(), parse_args(), parse_chown_usergroup_or_die(), parse_conf(), parse_datestr(), parse_dollar(), parse_matched_pair(), parse_meminfo(), parse_mount_options(), parse_one_line(), parse_stream(), parse_url(), ParseDMXConfig(), parser_if(), parser_include(), pid_is_name(), plural_lookup(), popen(), popen_ls(), popmaildir_main(), print_autowrap(), print_direc(), print_formatted(), process_config_line(), process_files(), process_includes(), process_irq_counts(), process_timer_stats(), procps_scan(), pseudo_exec_argv(), read_after_slash(), read_alias_file(), read_token_word(), readtoken1(), remove_quoted_nulls(), renice_main(), rescan_crontab_dir(), reverse_hosts(), reverse_services(), rewrite(), rl_alphabetic(), run_pipe(), sane_address(), scan_request(), sendmail_main(), set_local_var(), set_vars_and_save_old(), sh_getopt(), shell_builtin_read(), shellexec(), show_shell_usage(), shuf_main(), singlemount(), sleep_builtin(), sockaddr2str(), sort_main(), stat_char(), str2sockaddr(), strcreplace(), strftime(), strip_ipv6_scope_id(), strstr(), subCommand(), subevalvar(), sysctl_act_on_setting(), sysctl_act_recursive(), tar_main(), tilde_expand(), udhcp_str2optset(), uevent_main(), update_passwd(), validate_path(), version_compare(), vi_change_dispatch(), vi_delete_dispatch(), vi_yank_dispatch(), which_main(), and xxreadtoken().