Fennix Userspace: Userspace/apps/base/busybox/networking/tls_aes.h File Reference
tls_aes.h File Reference
Functions
void aes_setkey (struct tls_aes *aes, const void *key, unsigned key_len) FAST_FUNC
void aes_encrypt_one_block (struct tls_aes *aes, const void *data, void *dst) FAST_FUNC
void aes_cbc_encrypt (struct tls_aes *aes, void *iv, const void *data, size_t len, void *dst) FAST_FUNC
void aes_cbc_decrypt (struct tls_aes *aes, void *iv, const void *data, size_t len, void *dst) FAST_FUNC
Function Documentation
aes_cbc_decrypt()
void aes_cbc_decrypt (struct tls_aes * aes, void * iv, const void * data, size_t len, void * dst)
Definition at line 431 of file tls_aes.c.
 {
     uint8_t iv2[16];
     uint8_t iv3[16];
     uint8_t *ivbuf;
     uint8_t *ivnext;
     const uint8_t *ct = data;
     uint8_t *pt = dst;
     ivbuf = memcpy(iv2, iv, 16);
     while (len) {
         ivnext = (ivbuf==iv2) ? iv3 : iv2;
         {
             /* almost aes_decrypt_one_block(rounds, RoundKey, ct, pt)
              * but xor'ing of ivbuf is combined with astate[] -> plaintext[]
              */
             int i;
             unsigned astate[16];
             for (i = 0; i < 16; i++)
                 ivnext[i] = astate[i] = ct[i];
             aes_decrypt_1(aes, astate);
             for (i = 0; i < 16; i++)
                 pt[i] = astate[i] ^ ivbuf[i];
         }
         ivbuf = ivnext;
         ct += 16;
         pt += 16;
         len -= 16;
     }
 }
References aes_decrypt_1(), dst, i, and memcpy().
Referenced by tls_xread_record().
aes_cbc_encrypt()
void aes_cbc_encrypt (struct tls_aes * aes, void * iv, const void * data, size_t len, void * dst)
Definition at line 366 of file tls_aes.c.
 {
     uint8_t iv2[16];
     const uint8_t *pt = data;
     uint8_t *ct = dst;
     memcpy(iv2, iv, 16);
     while (len > 0) {
         {
             /* almost aes_encrypt_one_block(rounds, RoundKey, pt, ct);
              * but xor'ing of IV with plaintext[] is combined
              * with plaintext[] -> astate[]
              */
             int i;
             unsigned astate[16];
             for (i = 0; i < 16; i++)
                 astate[i] = pt[i] ^ iv2[i];
             aes_encrypt_1(aes, astate);
             for (i = 0; i < 16; i++)
                 iv2[i] = ct[i] = astate[i];
         }
         ct += 16;
         pt += 16;
         len -= 16;
     }
 }
References aes_encrypt_1(), dst, i, and memcpy().
Referenced by xwrite_encrypted_and_hmac_signed().
aes_encrypt_one_block()
void aes_encrypt_one_block (struct tls_aes * aes, const void * data, void * dst)
Definition at line 351 of file tls_aes.c.
 {
     unsigned astate[16];
     unsigned i;
     const uint8_t *pt = data;
     uint8_t *ct = dst;
     for (i = 0; i < 16; i++)
         astate[i] = pt[i];
     aes_encrypt_1(aes, astate);
     for (i = 0; i < 16; i++)
         ct[i] = astate[i];
 }
References aes_encrypt_1(), dst, and i.
Referenced by send_client_key_exchange(), tls_aesgcm_decrypt(), and xwrite_encrypted_aesgcm().
aes_setkey()
void aes_setkey (struct tls_aes * aes, const void * key, unsigned key_len)
Definition at line 346 of file tls_aes.c.
 {
     aes->rounds = KeyExpansion(aes->key, key, key_len);
 }
References tls_aes::key, KeyExpansion(), and tls_aes::rounds.
Referenced by send_client_key_exchange().