Fennix: Userspace/mlibc/options/posix/generic/termios-stubs.cpp File Reference
termios-stubs.cpp File Reference
#include <errno.h>
#include <termios.h>
#include <sys/ioctl.h>
#include <bits/ensure.h>
#include <mlibc/posix-sysdeps.hpp>
Functions
speed_t cfgetispeed (const struct termios *tios)
speed_t cfgetospeed (const struct termios *tios)
int cfsetispeed (struct termios *, speed_t)
int cfsetospeed (struct termios *, speed_t)
void cfmakeraw (struct termios *t)
int tcdrain (int fd)
int tcflow (int fd, int action)
int tcflush (int fd, int queue_selector)
int tcgetattr (int fd, struct termios *attr)
pid_t tcgetsid (int fd)
int tcsendbreak (int, int)
int tcsetattr (int fd, int opts, const struct termios *attr)
Function Documentation
cfgetispeed()
speed_t cfgetispeed (const struct termios * tios)
Definition at line 9 of file termios-stubs.cpp.
{
     return tios->ibaud;
 }
References termios::ibaud.
cfgetospeed()
speed_t cfgetospeed (const struct termios * tios)
Definition at line 12 of file termios-stubs.cpp.
{
     return tios->obaud;
 }
References termios::obaud.
cfmakeraw()
void cfmakeraw (struct termios * t)
Definition at line 24 of file termios-stubs.cpp.
{
     t->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | ISTRIP | INLCR | IGNCR | ICRNL | IXON);
     t->c_oflag &= ~OPOST;
     t->c_lflag &= ~(ECHO | ECHONL | ICANON | ISIG | IEXTEN);
     t->c_cflag &= ~(CSIZE | PARENB);
     t->c_cflag |= CS8;
     t->c_cc[VMIN] = 1;
     t->c_cc[VTIME] = 0;
 }
References BRKINT, termios::c_cc, termios::c_cflag, termios::c_iflag, termios::c_lflag, termios::c_oflag, CS8, CSIZE, ECHO, ECHONL, ICANON, ICRNL, IEXTEN, IGNBRK, IGNCR, INLCR, ISIG, ISTRIP, IXON, OPOST, PARENB, PARMRK, VMIN, and VTIME.
cfsetispeed()
int cfsetispeed (struct termios * , speed_t)
Definition at line 15 of file termios-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
cfsetospeed()
int cfsetospeed (struct termios * , speed_t)
Definition at line 19 of file termios-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
tcdrain()
int tcdrain (int fd)
Definition at line 34 of file termios-stubs.cpp.
                     {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcdrain, -1);
     if(int e = mlibc::sys_tcdrain(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcdrain().
Referenced by getpass().
tcflow()
int tcflow (int fd, int action)
Definition at line 43 of file termios-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcflow, -1);
     if(int e = mlibc::sys_tcflow(fd, action); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcflow().
tcflush()
int tcflush (int fd, int queue_selector)
Definition at line 52 of file termios-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcflush, -1);
     if(int e = mlibc::sys_tcflush(fd, queue_selector); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcflush().
tcgetattr()
int tcgetattr (int fd, struct termios * attr)
Definition at line 61 of file termios-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcgetattr, -1);
     if(int e = mlibc::sys_tcgetattr(fd, attr); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References mlibc::attr, errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcgetattr().
Referenced by getpass().
tcgetsid()
pid_t tcgetsid (int fd)
Definition at line 70 of file termios-stubs.cpp.
{
     int sid;
     if(ioctl(fd, TIOCGSID, &sid) < 0) {
         return -1;
     }
     return sid;
 }
References fd, ioctl(), and TIOCGSID.
tcsendbreak()
int tcsendbreak (int , int)
Definition at line 78 of file termios-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
tcsetattr()
int tcsetattr (int fd, int opts, const struct termios * attr)
Definition at line 83 of file termios-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcsetattr, -1);
     if(int e = mlibc::sys_tcsetattr(fd, opts, attr); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References mlibc::attr, errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcsetattr().
Referenced by getpass().