Fennix: Userspace/musl/include/err.h File Reference
err.h File Reference
#include <features.h>
#include <stdarg.h>
Functions
void warn (const char *,...)
void vwarn (const char *, va_list)
void warnx (const char *,...)
void vwarnx (const char *, va_list)
_Noreturn void err (int, const char *,...)
_Noreturn void verr (int, const char *, va_list)
_Noreturn void errx (int, const char *,...)
_Noreturn void verrx (int, const char *, va_list)
Function Documentation
err()
_Noreturn void err (int status, const char * fmt, ...)
Definition at line 53 of file err.c.
 {
     va_list ap;
     va_start(ap, fmt);
     verr(status, fmt, ap);
     va_end(ap);
 }
References fmt, mlibc::status, va_end(), va_start(), and verr().
Referenced by __ptsname_r(), _remove_directory(), do_nftw(), do_wordexp(), fmaf(), getgrgid(), getgrgid_r(), getgrnam(), getgrnam_r(), gethostbyaddr(), gethostbyaddr_r(), gethostbyname2(), gethostbyname2_r(), gethostbyname_r(), getpwnam(), getpwuid(), iconv(), if_nameindex(), lio_wait(), parse_atom(), parse_bracket(), ptsname(), start(), strerror_r(), system(), tre_parse(), and anonymous_namespace{grp-stubs.cpp}::walk_file().
errx()
_Noreturn void errx (int status, const char * fmt, ...)
Definition at line 61 of file err.c.
 {
     va_list ap;
     va_start(ap, fmt);
     verrx(status, fmt, ap);
     va_end(ap);
 }
References fmt, mlibc::status, va_end(), va_start(), and verrx().
verr()
_Noreturn void verr (int status, const char * fmt, va_list ap)
Definition at line 25 of file err.c.
 {
     vwarn(fmt, ap);
     exit(status);
 }
References exit(), fmt, mlibc::status, and vwarn().
Referenced by err().
verrx()
_Noreturn void verrx (int status, const char * fmt, va_list ap)
Definition at line 31 of file err.c.
 {
     vwarnx(fmt, ap);
     exit(status);
 }
References exit(), fmt, mlibc::status, and vwarnx().
Referenced by errx().
vwarn()
void vwarn (const char * fmt, va_list params)
Definition at line 9 of file err.cpp.
{
     fprintf(stderr, "%s: ", program_invocation_short_name);
     if (fmt) {
         vfprintf(stderr, fmt, params);
                 fwrite(": ", 1, 2, stderr);
     }
     perror(NULL);
 }
References __progname, fmt, fprintf(), fputs(), fwrite(), NULL, params, perror(), program_invocation_short_name, stderr, and vfprintf().
Referenced by verr(), and warn().
vwarnx()
void vwarnx (const char * fmt, va_list params)
Definition at line 18 of file err.cpp.
{
     fprintf(stderr, "%s: ", program_invocation_short_name);
     if (fmt) {
         vfprintf(stderr, fmt, params);
     }
     putc('\n', stderr);
 }
References __progname, fmt, fprintf(), params, program_invocation_short_name, putc(), stderr, and vfprintf().
Referenced by verrx(), and warnx().
warn()
void warn (const char * fmt, ...)
Definition at line 38 of file err.cpp.
{
     va_list params;
     va_start(params, fmt);
     vwarn(fmt, params);
     va_end(params);
 }
References fmt, params, va_end(), va_start(), and vwarn().
warnx()
void warnx (const char * fmt, ...)
Definition at line 45 of file err.cpp.
{
     va_list params;
     va_start(params, fmt);
     vwarnx(fmt, params);
     va_end(params);
 }
References fmt, params, va_end(), va_start(), and vwarnx().