Fennix: Userspace/mlibc/tests/posix/pthread_atfork.c File Reference
pthread_atfork.c File Reference
#include <assert.h>
#include <pthread.h>
#include <signal.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <sys/wait.h>
Functions
static void prepare1 ()
static void prepare2 ()
static void parent1 ()
static void parent2 ()
static void child1 ()
static void child2 ()
int main ()
Variables
_Atomic int prepare_order = 0
_Atomic int parent_order = 0
_Atomic int child_order = 0
Function Documentation
child1()
static void child1 () static
Definition at line 19 of file pthread_atfork.c.
 { child_order = 1; }
References child_order.
Referenced by main().
child2()
static void child2 () static
Definition at line 20 of file pthread_atfork.c.
 { child_order = 2; }
References child_order.
Referenced by main().
main()
int main (void)
Definition at line 22 of file pthread_atfork.c.
            {
     assert(!pthread_atfork(prepare1, parent1, child1));
     assert(!pthread_atfork(prepare2, parent2, child2));
     pid_t pid = fork();
     assert(pid >= 0);
     if (!pid) {
         assert(child_order == 2);
         exit(0);
     } else {
         assert(prepare_order == 1);
         assert(parent_order == 2);
         while (1) {
             int status = 0;
             int ret = waitpid(pid, &status, 0);
             if (ret == -1 && errno == EINTR)
                 continue;
             assert(ret > 0);
             if (WIFSIGNALED(status) && WTERMSIG(status) == SIGABRT)
                 return 1;
             return WEXITSTATUS(status);
         }
     }
     return 0;
 }
References assert, child1(), child2(), child_order, EINTR, errno, exit(), fork(), parent1(), parent2(), parent_order, prepare1(), prepare2(), prepare_order, pthread_atfork(), ret, SIGABRT, mlibc::status, waitpid(), WEXITSTATUS, WIFSIGNALED, and WTERMSIG.
parent1()
static void parent1 () static
Definition at line 16 of file pthread_atfork.c.
 { parent_order = 1; }
References parent_order.
Referenced by main().
parent2()
static void parent2 () static
Definition at line 17 of file pthread_atfork.c.
 { parent_order = 2; }
References parent_order.
Referenced by main().
prepare1()
static void prepare1 () static
Definition at line 13 of file pthread_atfork.c.
 { prepare_order = 1; }
References prepare_order.
Referenced by main().
prepare2()
static void prepare2 () static
Definition at line 14 of file pthread_atfork.c.
 { prepare_order = 2; }
References prepare_order.
Referenced by main().
Variable Documentation
child_order
_Atomic int child_order = 0
Definition at line 11 of file pthread_atfork.c.
Referenced by child1(), child2(), and main().
parent_order
_Atomic int parent_order = 0
Definition at line 10 of file pthread_atfork.c.
Referenced by main(), parent1(), and parent2().
prepare_order
_Atomic int prepare_order = 0
Definition at line 9 of file pthread_atfork.c.
Referenced by main(), prepare1(), and prepare2().