Fennix: Userspace/mlibc/options/internal/generic/ubsan.cpp File Reference
ubsan.cpp File Reference
#include <limits.h>
#include <mlibc/debug.hpp>
Data Structures
struct SourceLocation
struct TypeDescriptor
struct Value
struct TypeMismatch
struct PointerOverflowData
struct InvalidValueData
struct OverflowData
struct ShiftOutOfBoundsData
struct OutOfBoundsData
struct UnreachableData
struct InvalidBuiltinData
struct VLABoundData
Macros
#define FMT(obj) format_object((obj), opts, formatter)
#define LOG_NAME_LOC(name, loc) "ubsan: " name " at " << loc << "\n "
#define LOG_LHS_RHS(lhs, rhs) "LHS = " << (lhs) << ", RHS = " << (rhs)
Typedefs
using ValueHandle = uintptr_t
Functions
template<class F >
void format_object (const SourceLocation &loc, frg::format_options opts, F &formatter)
template<class F >
void format_object (const TypeDescriptor &type, frg::format_options opts, F &formatter)
template<class F >
void format_object (const Value &val, frg::format_options opts, F &formatter)
void __ubsan_handle_type_mismatch_v1 (TypeMismatch *tm, ValueHandle pointer)
void __ubsan_handle_pointer_overflow (PointerOverflowData *pod, ValueHandle base, ValueHandle result)
void __ubsan_handle_load_invalid_value (InvalidValueData *ivd, ValueHandle value)
void __ubsan_handle_add_overflow (OverflowData *od, ValueHandle lhs, ValueHandle rhs)
void __ubsan_handle_sub_overflow (OverflowData *od, ValueHandle lhs, ValueHandle rhs)
void __ubsan_handle_mul_overflow (OverflowData *od, ValueHandle lhs, ValueHandle rhs)
void __ubsan_handle_divrem_overflow (OverflowData *od, ValueHandle lhs, ValueHandle rhs)
void __ubsan_handle_negate_overflow (OverflowData *od, ValueHandle lhs, ValueHandle rhs)
void __ubsan_handle_shift_out_of_bounds (ShiftOutOfBoundsData *soob, ValueHandle lhs, ValueHandle rhs)
void __ubsan_handle_out_of_bounds (OutOfBoundsData *oobd, ValueHandle data)
void __ubsan_handle_builtin_unreachable (UnreachableData *ubd)
void __ubsan_handle_invalid_builtin (InvalidBuiltinData *ibd)
void __ubsan_handle_vla_bound_not_positive (VLABoundData *vlabd)
void __ubsan_handle_missing_return (UnreachableData *data)
Data Structure Documentation
SourceLocation
struct SourceLocation
Definition at line 9 of file ubsan.cpp.
Data Fields
uint32_t column
const char * filename
uint32_t line
TypeMismatch
struct TypeMismatch
Definition at line 84 of file ubsan.cpp.
Data Fields
unsigned char kind
SourceLocation loc
unsigned char logAlignment
const TypeDescriptor & type
PointerOverflowData
struct PointerOverflowData
Definition at line 101 of file ubsan.cpp.
Data Fields
SourceLocation loc
InvalidValueData
struct InvalidValueData
Definition at line 114 of file ubsan.cpp.
Data Fields
SourceLocation loc
const TypeDescriptor & type
OverflowData
struct OverflowData
Definition at line 127 of file ubsan.cpp.
Data Fields
SourceLocation loc
const TypeDescriptor & type
ShiftOutOfBoundsData
struct ShiftOutOfBoundsData
Definition at line 172 of file ubsan.cpp.
Data Fields
const TypeDescriptor & lhsType
SourceLocation loc
const TypeDescriptor & rhsType
OutOfBoundsData
struct OutOfBoundsData
Definition at line 186 of file ubsan.cpp.
Data Fields
const TypeDescriptor & arrayType
const TypeDescriptor & indexType
SourceLocation loc
UnreachableData
struct UnreachableData
Definition at line 200 of file ubsan.cpp.
Data Fields
SourceLocation loc
InvalidBuiltinData
struct InvalidBuiltinData
Definition at line 211 of file ubsan.cpp.
Data Fields
unsigned char kind
SourceLocation loc
VLABoundData
struct VLABoundData
Definition at line 223 of file ubsan.cpp.
Data Fields
SourceLocation loc
const TypeDescriptor & type
Macro Definition Documentation
FMT
#define FMT (obj) format_object((obj), opts, formatter)
Definition at line 4 of file ubsan.cpp.
LOG_LHS_RHS
#define LOG_LHS_RHS (lhs, rhs) "LHS = " << (lhs) << ", RHS = " << (rhs)
Definition at line 7 of file ubsan.cpp.
LOG_NAME_LOC
#define LOG_NAME_LOC (name, loc) "ubsan: " name " at " << loc << "\n "
Definition at line 6 of file ubsan.cpp.
Typedef Documentation
ValueHandle
using ValueHandle = uintptr_t
Definition at line 24 of file ubsan.cpp.
Function Documentation
__ubsan_handle_add_overflow()
void __ubsan_handle_add_overflow (OverflowData * od, ValueHandle lhs, ValueHandle rhs)
Definition at line 133 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("add overflowed ", od->loc)
         << LOG_LHS_RHS(Value(od->type, lhs), Value(od->type, rhs))
         << frg::endlog;
 }
References OverflowData::loc, LOG_LHS_RHS, LOG_NAME_LOC, mlibc::panicLogger, and OverflowData::type.
__ubsan_handle_builtin_unreachable()
void __ubsan_handle_builtin_unreachable (UnreachableData * ubd)
Definition at line 205 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("reached __builtin_unreachable()", ubd->loc)
         << frg::endlog;
 }
References UnreachableData::loc, LOG_NAME_LOC, and mlibc::panicLogger.
__ubsan_handle_divrem_overflow()
void __ubsan_handle_divrem_overflow (OverflowData * od, ValueHandle lhs, ValueHandle rhs)
Definition at line 157 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("divrem overflowed", od->loc)
         << LOG_LHS_RHS(Value(od->type, lhs), Value(od->type, rhs))
         << frg::endlog;
 }
References OverflowData::loc, LOG_LHS_RHS, LOG_NAME_LOC, mlibc::panicLogger, and OverflowData::type.
__ubsan_handle_invalid_builtin()
void __ubsan_handle_invalid_builtin (InvalidBuiltinData * ibd)
Definition at line 217 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("reached invalid builtin", ibd->loc)
         << frg::endlog;
 }
References InvalidBuiltinData::loc, LOG_NAME_LOC, and mlibc::panicLogger.
__ubsan_handle_load_invalid_value()
void __ubsan_handle_load_invalid_value (InvalidValueData * ivd, ValueHandle value)
Definition at line 120 of file ubsan.cpp.
{
     (void)value;
     mlibc::panicLogger()
         << LOG_NAME_LOC("load of invalid value", ivd->loc)
         << frg::endlog;
 }
References InvalidValueData::loc, LOG_NAME_LOC, mlibc::panicLogger, value, and Driver::void().
__ubsan_handle_missing_return()
void __ubsan_handle_missing_return (UnreachableData * data)
Definition at line 236 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("reached end of a value-returning function without returning a value", data->loc)
         << frg::endlog;
 }
References UnreachableData::loc, LOG_NAME_LOC, and mlibc::panicLogger.
__ubsan_handle_mul_overflow()
void __ubsan_handle_mul_overflow (OverflowData * od, ValueHandle lhs, ValueHandle rhs)
Definition at line 149 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("mul overflowed", od->loc)
         << LOG_LHS_RHS(Value(od->type, lhs), Value(od->type, rhs))
         << frg::endlog;
 }
References OverflowData::loc, LOG_LHS_RHS, LOG_NAME_LOC, mlibc::panicLogger, and OverflowData::type.
__ubsan_handle_negate_overflow()
void __ubsan_handle_negate_overflow (OverflowData * od, ValueHandle lhs, ValueHandle rhs)
Definition at line 165 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("negate overflowed", od->loc)
         << LOG_LHS_RHS(Value(od->type, lhs), Value(od->type, rhs))
         << frg::endlog;
 }
References OverflowData::loc, LOG_LHS_RHS, LOG_NAME_LOC, mlibc::panicLogger, and OverflowData::type.
__ubsan_handle_out_of_bounds()
void __ubsan_handle_out_of_bounds (OutOfBoundsData * oobd, ValueHandle data)
Definition at line 193 of file ubsan.cpp.
{
     (void)data;
     mlibc::panicLogger()
         << LOG_NAME_LOC("out of bounds access", oobd->loc)
         << frg::endlog;
 }
References OutOfBoundsData::loc, LOG_NAME_LOC, mlibc::panicLogger, and Driver::void().
__ubsan_handle_pointer_overflow()
void __ubsan_handle_pointer_overflow (PointerOverflowData * pod, ValueHandle base, ValueHandle result)
Definition at line 106 of file ubsan.cpp.
{
     (void)base;
     (void)result;
     mlibc::panicLogger()
         << LOG_NAME_LOC("pointer overflow", pod->loc)
         << frg::endlog;
 }
References base, PointerOverflowData::loc, LOG_NAME_LOC, mlibc::panicLogger, and Driver::void().
__ubsan_handle_shift_out_of_bounds()
void __ubsan_handle_shift_out_of_bounds (ShiftOutOfBoundsData * soob, ValueHandle lhs, ValueHandle rhs)
Definition at line 179 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("shift out of bounds", soob->loc)
         << LOG_LHS_RHS(Value(soob->lhsType, lhs), Value(soob->rhsType, rhs))
         << frg::endlog;
 }
References ShiftOutOfBoundsData::lhsType, ShiftOutOfBoundsData::loc, LOG_LHS_RHS, LOG_NAME_LOC, mlibc::panicLogger, and ShiftOutOfBoundsData::rhsType.
__ubsan_handle_sub_overflow()
void __ubsan_handle_sub_overflow (OverflowData * od, ValueHandle lhs, ValueHandle rhs)
Definition at line 141 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("sub overflowed", od->loc)
         << LOG_LHS_RHS(Value(od->type, lhs), Value(od->type, rhs))
         << frg::endlog;
 }
References OverflowData::loc, LOG_LHS_RHS, LOG_NAME_LOC, mlibc::panicLogger, and OverflowData::type.
__ubsan_handle_type_mismatch_v1()
void __ubsan_handle_type_mismatch_v1 (TypeMismatch * tm, ValueHandle pointer)
Definition at line 92 of file ubsan.cpp.
{
     // TODO: Make this print more information.
     mlibc::panicLogger()
         << LOG_NAME_LOC("type mismatch", tm->loc)
         << "accessed address " << (void *)pointer << " but type "
         << tm->type << " requires alignment " << (1 << tm->logAlignment)
         << frg::endlog;
 }
References LOG_NAME_LOC, and mlibc::panicLogger.
__ubsan_handle_vla_bound_not_positive()
void __ubsan_handle_vla_bound_not_positive (VLABoundData * vlabd)
Definition at line 229 of file ubsan.cpp.
{
     mlibc::panicLogger()
         << LOG_NAME_LOC("VLA bound not positive", vlabd->loc)
         << frg::endlog;
 }
References VLABoundData::loc, LOG_NAME_LOC, and mlibc::panicLogger.
format_object() [1/3]
template<class F > void format_object (const SourceLocation & loc, frg::format_options opts, F & formatter)
Definition at line 16 of file ubsan.cpp.
{
     FMT(loc.filename);
     FMT(":");
     FMT(loc.line);
     FMT(":");
     FMT(loc.column);
 }
References SourceLocation::column, SourceLocation::filename, FMT, and SourceLocation::line.
format_object() [2/3]
template<class F > void format_object (const TypeDescriptor & type, frg::format_options opts, F & formatter)
Definition at line 55 of file ubsan.cpp.
{
     FMT(type.name);
 }
References FMT, and type.
format_object() [3/3]
template<class F > void format_object (const Value & val, frg::format_options opts, F & formatter)
Definition at line 67 of file ubsan.cpp.
{
     if (val.type.isInlineInt() && val.type.isSigned()) {
         auto signedValue = static_cast<int64_t>(val.val);
         FMT(signedValue);
     } else if (val.type.isInlineInt() && !val.type.isSigned()) {
         auto unsignedValue = static_cast<uint64_t>(val.val);
         FMT(unsignedValue);
     }
     FMT(" (");
     FMT(val.type);
     FMT(")");
 }
References FMT, TypeDescriptor::isInlineInt(), TypeDescriptor::isSigned(), Value::type, and Value::val.