Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/p_user.c File Reference
p_user.c File Reference
#include "doomdef.h"
#include "d_event.h"
#include "p_local.h"
#include "doomstat.h"
Macros
#define INVERSECOLORMAP 32
#define MAXBOB 0x100000
#define ANG5 (ANG90/18)
Functions
void P_Thrust (player_t *player, angle_t angle, fixed_t move)
void P_CalcHeight (player_t *player)
void P_MovePlayer (player_t *player)
void P_DeathThink (player_t *player)
void P_PlayerThink (player_t *player)
Variables
boolean onground
Macro Definition Documentation
ANG5
#define ANG5 (ANG90/18)
Definition at line 173 of file p_user.c.
INVERSECOLORMAP
#define INVERSECOLORMAP 32
Definition at line 34 of file p_user.c.
MAXBOB
#define MAXBOB 0x100000
Definition at line 42 of file p_user.c.
Function Documentation
P_CalcHeight()
void P_CalcHeight (player_t * player)
Definition at line 70 of file p_user.c.
 {
     int     angle;
     fixed_t bob;
     // Regular movement bobbing
     // (needs to be calculated for gun swing
     // even if not on ground)
     // OPTIMIZE: tablify angle
     // Note: a LUT allows for effects
     //  like a ramp with low health.
     player->bob =
     FixedMul (player->mo->momx, player->mo->momx)
     + FixedMul (player->mo->momy,player->mo->momy);
     player->bob >>= 2;
     if (player->bob>MAXBOB)
     player->bob = MAXBOB;
     if ((player->cheats & CF_NOMOMENTUM) || !onground)
     {
     player->viewz = player->mo->z + VIEWHEIGHT;
     if (player->viewz > player->mo->ceilingz-4*FRACUNIT)
         player->viewz = player->mo->ceilingz-4*FRACUNIT;
     player->viewz = player->mo->z + player->viewheight;
     return;
     }
     angle = (FINEANGLES/20*leveltime)&FINEMASK;
     bob = FixedMul ( player->bob/2, finesine[angle]);
     // move viewheight
     if (player->playerstate == PST_LIVE)
     {
     player->viewheight += player->deltaviewheight;
     if (player->viewheight > VIEWHEIGHT)
     {
         player->viewheight = VIEWHEIGHT;
         player->deltaviewheight = 0;
     }
     if (player->viewheight < VIEWHEIGHT/2)
     {
         player->viewheight = VIEWHEIGHT/2;
         if (player->deltaviewheight <= 0)
         player->deltaviewheight = 1;
     }
     if (player->deltaviewheight)
     {
         player->deltaviewheight += FRACUNIT/4;
         if (!player->deltaviewheight)
         player->deltaviewheight = 1;
     }
     }
     player->viewz = player->mo->z + player->viewheight + bob;
     if (player->viewz > player->mo->ceilingz-4*FRACUNIT)
     player->viewz = player->mo->ceilingz-4*FRACUNIT;
 }
References player_s::bob, mobj_s::ceilingz, CF_NOMOMENTUM, player_s::cheats, player_s::deltaviewheight, FINEANGLES, FINEMASK, finesine, FixedMul(), FRACUNIT, leveltime, MAXBOB, player_s::mo, mobj_s::momx, mobj_s::momy, onground, player_s::playerstate, PST_LIVE, player_s::viewheight, VIEWHEIGHT, player_s::viewz, and mobj_s::z.
Referenced by P_DeathThink(), and P_PlayerThink().
P_DeathThink()
void P_DeathThink (player_t * player)
Definition at line 175 of file p_user.c.
 {
     angle_t     angle;
     angle_t     delta;
     P_MovePsprites (player);
     // fall to the ground
     if (player->viewheight > 6*FRACUNIT)
     player->viewheight -= FRACUNIT;
     if (player->viewheight < 6*FRACUNIT)
     player->viewheight = 6*FRACUNIT;
     player->deltaviewheight = 0;
     onground = (player->mo->z <= player->mo->floorz);
     P_CalcHeight (player);
     if (player->attacker && player->attacker != player->mo)
     {
     angle = R_PointToAngle2 (player->mo->x,
                  player->mo->y,
                  player->attacker->x,
                  player->attacker->y);
     delta = angle - player->mo->angle;
     if (delta < ANG5 || delta > (unsigned)-ANG5)
     {
         // Looking at killer,
         //  so fade damage flash down.
         player->mo->angle = angle;
         if (player->damagecount)
         player->damagecount--;
     }
     else if (delta < ANG180)
         player->mo->angle += ANG5;
     else
         player->mo->angle -= ANG5;
     }
     else if (player->damagecount)
     player->damagecount--;
     if (player->cmd.buttons & BT_USE)
     player->playerstate = PST_REBORN;
 }
References ANG180, ANG5, mobj_s::angle, player_s::attacker, BT_USE, ticcmd_t::buttons, player_s::cmd, player_s::damagecount, player_s::deltaviewheight, mobj_s::floorz, FRACUNIT, player_s::mo, onground, P_CalcHeight(), P_MovePsprites(), player_s::playerstate, PST_REBORN, R_PointToAngle2(), player_s::viewheight, mobj_s::x, mobj_s::y, and mobj_s::z.
Referenced by P_PlayerThink().
P_MovePlayer()
void P_MovePlayer (player_t * player)
Definition at line 141 of file p_user.c.
 {
     ticcmd_t*       cmd;
     cmd = &player->cmd;
     player->mo->angle += (cmd->angleturn<<16);
     // Do not let the player control movement
     //  if not onground.
     onground = (player->mo->z <= player->mo->floorz);
     if (cmd->forwardmove && onground)
     P_Thrust (player, player->mo->angle, cmd->forwardmove*2048);
     if (cmd->sidemove && onground)
     P_Thrust (player, player->mo->angle-ANG90, cmd->sidemove*2048);
     if ( (cmd->forwardmove || cmd->sidemove)
      && player->mo->state == &states[S_PLAY] )
     {
     P_SetMobjState (player->mo, S_PLAY_RUN1);
     }
 }
References ANG90, mobj_s::angle, cmd, player_s::cmd, mobj_s::floorz, player_s::mo, onground, P_SetMobjState(), P_Thrust(), S_PLAY, S_PLAY_RUN1, mobj_s::state, states, and mobj_s::z.
Referenced by P_PlayerThink().
P_PlayerThink()
void P_PlayerThink (player_t * player)
Definition at line 229 of file p_user.c.
 {
     ticcmd_t*       cmd;
     weapontype_t    newweapon;
     // fixme: do this in the cheat code
     if (player->cheats & CF_NOCLIP)
     player->mo->flags |= MF_NOCLIP;
     else
     player->mo->flags &= ~MF_NOCLIP;
     // chain saw run forward
     cmd = &player->cmd;
     if (player->mo->flags & MF_JUSTATTACKED)
     {
     cmd->angleturn = 0;
     cmd->forwardmove = 0xc800/512;
     cmd->sidemove = 0;
     player->mo->flags &= ~MF_JUSTATTACKED;
     }
     if (player->playerstate == PST_DEAD)
     {
     P_DeathThink (player);
     return;
     }
     // Move around.
     // Reactiontime is used to prevent movement
     //  for a bit after a teleport.
     if (player->mo->reactiontime)
     player->mo->reactiontime--;
     else
     P_MovePlayer (player);
     P_CalcHeight (player);
     if (player->mo->subsector->sector->special)
     P_PlayerInSpecialSector (player);
     // Check for weapon change.
     // A special event has no other buttons.
     if (cmd->buttons & BT_SPECIAL)
     cmd->buttons = 0;
     if (cmd->buttons & BT_CHANGE)
     {
     // The actual changing of the weapon is done
     //  when the weapon psprite can do it
     //  (read: not in the middle of an attack).
     newweapon = (cmd->buttons&BT_WEAPONMASK)>>BT_WEAPONSHIFT;
     if (newweapon == wp_fist
         && player->weaponowned[wp_chainsaw]
         && !(player->readyweapon == wp_chainsaw
          && player->powers[pw_strength]))
     {
         newweapon = wp_chainsaw;
     }
     if ( (gamemode == commercial)
         && newweapon == wp_shotgun
         && player->weaponowned[wp_supershotgun]
         && player->readyweapon != wp_supershotgun)
     {
         newweapon = wp_supershotgun;
     }
     if (player->weaponowned[newweapon]
         && newweapon != player->readyweapon)
     {
         // Do not go to plasma or BFG in shareware,
         //  even if cheated.
         if ((newweapon != wp_plasma
          && newweapon != wp_bfg)
         || (gamemode != shareware) )
         {
         player->pendingweapon = newweapon;
         }
     }
     }
     // check for use
     if (cmd->buttons & BT_USE)
     {
     if (!player->usedown)
     {
         P_UseLines (player);
         player->usedown = true;
     }
     }
     else
     player->usedown = false;
     // cycle psprites
     P_MovePsprites (player);
     // Counters, time dependend power ups.
     // Strength counts up to diminish fade.
     if (player->powers[pw_strength])
     player->powers[pw_strength]++;
     if (player->powers[pw_invulnerability])
     player->powers[pw_invulnerability]--;
     if (player->powers[pw_invisibility])
     if (! --player->powers[pw_invisibility] )
         player->mo->flags &= ~MF_SHADOW;
     if (player->powers[pw_infrared])
     player->powers[pw_infrared]--;
     if (player->powers[pw_ironfeet])
     player->powers[pw_ironfeet]--;
     if (player->damagecount)
     player->damagecount--;
     if (player->bonuscount)
     player->bonuscount--;
     // Handling colormaps.
     if (player->powers[pw_invulnerability])
     {
     if (player->powers[pw_invulnerability] > 4*32
         || (player->powers[pw_invulnerability]&8) )
         player->fixedcolormap = INVERSECOLORMAP;
     else
         player->fixedcolormap = 0;
     }
     else if (player->powers[pw_infrared])
     {
     if (player->powers[pw_infrared] > 4*32
         || (player->powers[pw_infrared]&8) )
     {
         // almost full bright
         player->fixedcolormap = 1;
     }
     else
         player->fixedcolormap = 0;
     }
     else
     player->fixedcolormap = 0;
 }
References player_s::bonuscount, BT_CHANGE, BT_SPECIAL, BT_USE, BT_WEAPONMASK, BT_WEAPONSHIFT, CF_NOCLIP, player_s::cheats, cmd, player_s::cmd, commercial, player_s::damagecount, player_s::fixedcolormap, mobj_s::flags, gamemode, INVERSECOLORMAP, MF_JUSTATTACKED, MF_NOCLIP, MF_SHADOW, player_s::mo, P_CalcHeight(), P_DeathThink(), P_MovePlayer(), P_MovePsprites(), P_PlayerInSpecialSector(), P_UseLines(), player_s::pendingweapon, player_s::playerstate, player_s::powers, PST_DEAD, pw_infrared, pw_invisibility, pw_invulnerability, pw_ironfeet, pw_strength, mobj_s::reactiontime, player_s::readyweapon, subsector_s::sector, shareware, sector_t::special, mobj_s::subsector, player_s::usedown, player_s::weaponowned, wp_bfg, wp_chainsaw, wp_fist, wp_plasma, wp_shotgun, and wp_supershotgun.
Referenced by P_Ticker().
P_Thrust()
void P_Thrust (player_t * player, angle_t angle, fixed_t move)
Definition at line 52 of file p_user.c.
 {
     angle >>= ANGLETOFINESHIFT;
     player->mo->momx += FixedMul(move,finecosine[angle]);
     player->mo->momy += FixedMul(move,finesine[angle]);
 }
References ANGLETOFINESHIFT, finecosine, finesine, FixedMul(), player_s::mo, mobj_s::momx, and mobj_s::momy.
Referenced by P_MovePlayer().
Variable Documentation
onground
boolean onground
Definition at line 44 of file p_user.c.
Referenced by P_CalcHeight(), P_DeathThink(), and P_MovePlayer().