Fennix Userspace: Userspace/mlibc/tests/rtdl/rtld_next/test.c File Reference
test.c File Reference
#include <string.h>
#include <assert.h>
Typedefs
typedef char * charFn(void)
Functions
charFn * fooGetDefault (void)
charFn * fooGetNext (void)
charFn * barGetDefault (void)
charFn * barGetNext (void)
int main ()
Typedef Documentation
charFn
typedef char* charFn(void)
Definition at line 4 of file test.c.
Function Documentation
barGetDefault()
charFn* barGetDefault (void)
Definition at line 10 of file libbar.c.
{
     return (charFn *)dlsym(RTLD_DEFAULT, "definedInBoth");
 }
References dlsym(), and RTLD_DEFAULT.
Referenced by main().
barGetNext()
charFn* barGetNext (void)
Definition at line 14 of file libbar.c.
                      {
     return (charFn *)dlsym(RTLD_NEXT, "definedInBoth");
 }
References dlsym(), and RTLD_NEXT.
Referenced by main().
fooGetDefault()
charFn* fooGetDefault (void)
Definition at line 10 of file libfoo.c.
{
     return (charFn *)dlsym(RTLD_DEFAULT, "definedInBoth");
 }
References dlsym(), and RTLD_DEFAULT.
Referenced by main().
fooGetNext()
charFn* fooGetNext (void)
Definition at line 14 of file libfoo.c.
                      {
     return (charFn *)dlsym(RTLD_NEXT, "definedInBoth");
 }
References dlsym(), and RTLD_NEXT.
Referenced by main().
main()
int main (void)
Definition at line 10 of file test.c.
            {
     charFn *ret;
     ret = fooGetDefault();
     assert(ret != NULL);
     assert(!strcmp(ret(), "foo"));
     ret = fooGetNext();
     assert(ret != NULL);
     assert(!strcmp(ret(), "bar"));
     ret = barGetDefault();
     assert(ret != NULL);
     assert(!strcmp(ret(), "foo"));
     assert(barGetNext() == NULL);
 }
References assert, barGetDefault(), barGetNext(), fooGetDefault(), fooGetNext(), NULL, ret, and strcmp().