Fennix: Userspace/apps/base/busybox/modutils/modutils.c File Reference
modutils.c File Reference
#include "modutils.h"
#include <sys/syscall.h>
Macros
#define init_module(mod, len, opts) syscall(__NR_init_module, mod, len, opts)
#define delete_module(mod, flags) syscall(__NR_delete_module, mod, flags)
Functions
static module_entry * helper_get_module (module_db *db, const char *module, int create)
module_entry *FAST_FUNC moddb_get (module_db *db, const char *module)
module_entry *FAST_FUNC moddb_get_or_create (module_db *db, const char *module)
void FAST_FUNC moddb_free (module_db *db)
void FAST_FUNC replace (char *s, char what, char with)
int FAST_FUNC string_to_llist (char *string, llist_t **llist, const char *delim)
char *FAST_FUNC filename2modname (const char *filename, char *modname)
int FAST_FUNC bb_init_module (const char *filename, const char *options)
int FAST_FUNC bb_delete_module (const char *module, unsigned int flags)
const char *FAST_FUNC moderror (int err)
Macro Definition Documentation
delete_module
#define delete_module (mod, flags) syscall(__NR_delete_module, mod, flags)
Definition at line 16 of file modutils.c.
init_module
#define init_module (mod, len, opts) syscall(__NR_init_module, mod, len, opts)
Definition at line 12 of file modutils.c.
Function Documentation
bb_delete_module()
int FAST_FUNC bb_delete_module (const char * module, unsigned int flags)
Definition at line 250 of file modutils.c.
 {
     errno = 0;
     delete_module(module, flags);
     return errno;
 }
References delete_module, errno, and flags.
Referenced by do_modprobe(), modprobe_main(), and rmmod_main().
bb_init_module()
int FAST_FUNC bb_init_module (const char * filename, const char * options)
Definition at line 194 of file modutils.c.
 {
     size_t image_size;
     char *image;
     int rc;
     bool mmaped;
     if (!options)
         options = "";
 //TODO: audit bb_init_module_24 to match error code convention
 #if ENABLE_FEATURE_2_4_MODULES
     if (get_linux_version_code() < KERNEL_VERSION(2,6,0))
         return bb_init_module_24(filename, options);
 #endif
     /*
      * First we try finit_module if available.  Some kernels are configured
      * to only allow loading of modules off of secure storage (like a read-
      * only rootfs) which needs the finit_module call.  If it fails, we fall
      * back to normal module loading to support compressed modules.
      */
 # ifdef __NR_finit_module
     {
         int fd = open(filename, O_RDONLY | O_CLOEXEC);
         if (fd >= 0) {
             rc = finit_module(fd, options, 0) != 0;
             close(fd);
             if (rc == 0)
                 return rc;
         }
     }
 # endif
     image_size = INT_MAX - 4095;
     mmaped = 0;
     image = try_to_mmap_module(filename, &image_size);
     if (image) {
         mmaped = 1;
     } else {
         errno = ENOMEM; /* may be changed by e.g. open errors below */
         image = xmalloc_open_zipped_read_close(filename, &image_size);
         if (!image)
             return -errno;
     }
     errno = 0;
     init_module(image, image_size, options);
     rc = errno;
     if (mmaped)
         munmap(image, image_size);
     else
         free(image);
     return rc;
 }
References bb_init_module_24(), close(), ENOMEM, errno, fd, filename, free, get_linux_version_code(), init_module, INT_MAX, KERNEL_VERSION, munmap(), O_CLOEXEC, O_RDONLY, open(), rc, try_to_mmap_module, and xmalloc_open_zipped_read_close.
Referenced by do_modprobe(), and insmod_main().
filename2modname()
char* FAST_FUNC filename2modname (const char * filename, char * modname)
Definition at line 92 of file modutils.c.
 {
     char local_modname[MODULE_NAME_LEN];
     int i;
     const char *from;
     if (filename == NULL)
         return NULL;
     if (modname == NULL)
         modname = local_modname;
     // Disabled since otherwise "modprobe dir/name" would work
     // as if it is "modprobe name". It is unclear why
     // 'basenamization' was here in the first place.
     //from = bb_get_last_path_component_nostrip(filename);
     from = filename;
     for (i = 0; i < (MODULE_NAME_LEN-1) && from[i] != '\0' && from[i] != '.'; i++)
         modname[i] = (from[i] == '-') ? '_' : from[i];
     modname[i] = '\0';
     if (modname == local_modname)
         return xstrdup(modname);
     return modname;
 }
References filename, i, module_entry::modname, MODULE_NAME_LEN, NULL, and xstrdup().
Referenced by config_file_action(), helper_get_module(), modinfo_main(), modprobe_main(), and rmmod_main().
helper_get_module()
static module_entry* helper_get_module (module_db * db, const char * module, int create) static
Definition at line 18 of file modutils.c.
 {
     char modname[MODULE_NAME_LEN];
     struct module_entry *e;
     unsigned i, hash;
     filename2modname(module, modname);
     hash = 0;
     for (i = 0; modname[i]; i++)
         hash = ((hash << 5) + hash) + modname[i];
     hash %= MODULE_HASH_SIZE;
     for (e = db->buckets[hash]; e; e = e->next)
         if (strcmp(e->modname, modname) == 0)
             return e;
     if (!create)
         return NULL;
     e = xzalloc(sizeof(*e));
     e->modname = xstrdup(modname);
     e->next = db->buckets[hash];
     db->buckets[hash] = e;
     IF_DEPMOD(e->dnext = e->dprev = e;)
     return e;
 }
References module_db::buckets, module_entry::dnext, module_entry::dprev, filename2modname(), i, module_entry::modname, MODULE_HASH_SIZE, MODULE_NAME_LEN, module_entry::next, NULL, strcmp, xstrdup(), and xzalloc().
Referenced by moddb_get(), and moddb_get_or_create().
moddb_free()
void FAST_FUNC moddb_free (module_db * db)
Definition at line 54 of file modutils.c.
 {
     module_entry *e, *n;
     unsigned i;
     for (i = 0; i < MODULE_HASH_SIZE; i++) {
         for (e = db->buckets[i]; e; e = n) {
             n = e->next;
             free(e->name);
             free(e->modname);
             free(e);
         }
     }
 }
References module_db::buckets, free, i, module_entry::modname, MODULE_HASH_SIZE, n, module_entry::name, and module_entry::next.
Referenced by depmod_main(), and modprobe_main().
moddb_get()
module_entry* FAST_FUNC moddb_get (module_db * db, const char * module)
Definition at line 45 of file modutils.c.
 {
     return helper_get_module(db, module, 0);
 }
References helper_get_module().
Referenced by load_modules_dep(), and order_dep_list().
moddb_get_or_create()
module_entry* FAST_FUNC moddb_get_or_create (module_db * db, const char * module)
Definition at line 49 of file modutils.c.
 {
     return helper_get_module(db, module, 1);
 }
References helper_get_module().
Referenced by get_or_add_modentry(), and parse_module().
moderror()
const char* FAST_FUNC moderror (int err)
Definition at line 262 of file modutils.c.
 {
     switch (err) {
     case -1: /* btw: it's -EPERM */
         return "no such module";
     case ENOEXEC:
         return "invalid module format";
     case ENOENT:
         return "unknown symbol in module, or unknown parameter";
     case ESRCH:
         return "module has wrong symbol version";
     case ENOSYS:
         return "kernel does not support requested operation";
     }
     if (err < 0) /* should always be */
         err = -err;
     return strerror(err);
 }
References ENOENT, ENOEXEC, ENOSYS, err(), ESRCH, and strerror().
Referenced by do_modprobe(), and insmod_main().
replace()
void FAST_FUNC replace (char * s, char what, char with)
Definition at line 69 of file modutils.c.
 {
     while (*s) {
         if (what == *s)
             *s = with;
         ++s;
     }
 }
References s.
string_to_llist()
int FAST_FUNC string_to_llist (char * string, llist_t ** llist, const char * delim)
Definition at line 78 of file modutils.c.
 {
     char *tok;
     int len = 0;
     while ((tok = strsep(&string, delim)) != NULL) {
         if (tok[0] == '\0')
             continue;
         llist_add_to_end(llist, xstrdup(tok));
         len += strlen(tok);
     }
     return len;
 }
References len, llist_add_to_end(), NULL, strlen, strsep(), and xstrdup().
Referenced by load_modules_dep(), and parse_module().