Fennix: Drivers/network/rtl8139/main.c File Reference
main.c File Reference
#include <base.h>
#include "rtl8139.hpp"
Functions
int DriverEntry ()
int DriverFinal ()
int DriverPanic ()
int DriverProbe ()
DriverInfo ("rtl8139", "Realtek RTL8139 Network Driver", "EnderIce2", "0.1", "GPLv3")
Function Documentation
DriverEntry()
int DriverEntry ()
A device may fail, but if the other one works, we can still use it.
This is the main function of the driver. This function is called when the driver is loaded. This function should be used to initialize the PCI device and allocate resources.
If we have another driver using the PS/2 mouse, we need to override its interrupt handler.
Definition at line 22 of file main.c.
 { return cxx_Initialize(); }
References cxx_Initialize().
DriverFinal()
int DriverFinal ()
This function is called when the driver is unloaded. This function should be used to stop the PCI device and free any resources.
Definition at line 23 of file main.c.
 { return cxx_Finalize(); }
References cxx_Finalize().
DriverInfo()
DriverInfo ("rtl8139" , "Realtek RTL8139 Network Driver" , "EnderIce2" , "0.1" , "GPLv3")
DriverPanic()
int DriverPanic ()
This function is called when the kernel panics. This function should be used to stop the driver from receiving interrupts or anything else that is not safe to do when the kernel panics.
Definition at line 24 of file main.c.
 { return cxx_Panic(); }
References cxx_Panic().
DriverProbe()
int DriverProbe ()
This is the first function that is called when the driver is loaded. We can use this function to test if the driver is compatible with the hardware. Like if we have a specific PCI device or if we have a specific CPU feature.
Return 0 if the driver is compatible with the hardware. Otherwise, we return a value from the errno.h header.
Note: In this function you cannot use variables that have constructors or destructors. Before DriverEntry, the constructors are called and after DriverFinalize, the destructors are called.
Definition at line 25 of file main.c.
 { return cxx_Probe(); }
References cxx_Probe().