Fennix: Userspace/musl/src/include/stdlib.h File Reference
stdlib.h File Reference
#include "../../include/stdlib.h"
Functions
hidden int __putenv (char *, size_t, char *)
hidden void __env_rm_add (char *, char *)
hidden int __mkostemps (char *, int, int)
hidden int __ptsname_r (int, char *, size_t)
hidden char * __randname (char *)
hidden void __qsort_r (void *, size_t, size_t, int(*)(const void *, const void *, void *), void *)
hidden void * __libc_malloc (size_t)
hidden void * __libc_malloc_impl (size_t)
hidden void * __libc_calloc (size_t, size_t)
hidden void * __libc_realloc (void *, size_t)
hidden void __libc_free (void *)
Function Documentation
__env_rm_add()
hidden void __env_rm_add (char * old, char * new)
Definition at line 5 of file setenv.c.
 {
     static char **env_alloced;
     static size_t env_alloced_n;
     for (size_t i=0; i < env_alloced_n; i++)
         if (env_alloced[i] == old) {
             env_alloced[i] = new;
             free(old);
             return;
         } else if (!env_alloced[i] && new) {
             env_alloced[i] = new;
             new = 0;
         }
     if (!new) return;
     char **t = realloc(env_alloced, sizeof *t * (env_alloced_n+1));
     if (!t) return;
     (env_alloced = t)[env_alloced_n++] = new;
 }
References free, i, old, realloc, and t.
Referenced by __putenv(), clearenv(), and unsetenv().
__libc_calloc()
hidden void* __libc_calloc (size_t , size_t)
__libc_free()
hidden void __libc_free (void *)
Referenced by free().
__libc_malloc()
hidden void* __libc_malloc (size_t n)
Definition at line 108 of file lite_malloc.c.
 {
     return __libc_malloc_impl(n);
 }
References __libc_malloc_impl(), and n.
__libc_malloc_impl()
hidden void* __libc_malloc_impl (size_t)
Referenced by __libc_malloc(), and default_malloc().
__libc_realloc()
hidden void* __libc_realloc (void * , size_t)
Referenced by realloc().
__mkostemps()
hidden int __mkostemps (char * template, int len, int flags)
Definition at line 8 of file mkostemps.c.
 {
     size_t l = strlen(template);
     if (l<6 || len>l-6 || memcmp(template+l-len-6, "XXXXXX", 6)) {
         errno = EINVAL;
         return -1;
     }
     flags -= flags & O_ACCMODE;
     int fd, retries = 100;
     do {
         __randname(template+l-len-6);
         if ((fd = open(template, flags | O_RDWR | O_CREAT | O_EXCL, 0600))>=0)
             return fd;
     } while (--retries && errno == EEXIST);
     memcpy(template+l-len-6, "XXXXXX", 6);
     return -1;
 }
References __randname(), EEXIST, EINVAL, errno, fd, flags, l, len, memcmp(), memcpy, O_ACCMODE, O_CREAT, O_EXCL, O_RDWR, open(), and strlen.
Referenced by mkostemp(), mkstemp(), and mkstemps().
__ptsname_r()
hidden int __ptsname_r (int fd, char * buf, size_t len)
Definition at line 26 of file pty.c.
 {
     int pty, err;
     if (!buf) len = 0;
     if ((err = __syscall(SYS_ioctl, fd, TIOCGPTN, &pty))) return -err;
     if (snprintf(buf, len, "/dev/pts/%d", pty) >= len) return ERANGE;
     return 0;
 }
References __syscall, buf, ERANGE, err(), fd, len, snprintf(), and TIOCGPTN.
Referenced by ptsname().
__putenv()
hidden int __putenv (char * s, size_t l, char * r)
Definition at line 8 of file putenv.c.
 {
     size_t i=0;
     if (__environ) {
         for (char **e = __environ; *e; e++, i++)
             if (!strncmp(s, *e, l+1)) {
                 char *tmp = *e;
                 *e = s;
                 __env_rm_add(tmp, r);
                 return 0;
             }
     }
     static char **oldenv;
     char **newenv;
     if (__environ == oldenv) {
         newenv = realloc(oldenv, sizeof *newenv * (i+2));
         if (!newenv) goto oom;
     } else {
         newenv = malloc(sizeof *newenv * (i+2));
         if (!newenv) goto oom;
         if (i) memcpy(newenv, __environ, sizeof *newenv * i);
         free(oldenv);
     }
     newenv[i] = s;
     newenv[i+1] = 0;
     __environ = oldenv = newenv;
     if (r) __env_rm_add(0, r);
     return 0;
 oom:
     free(r);
     return -1;
 }
References __env_rm_add(), __environ, free, i, l, malloc, memcpy, realloc, s, and strncmp().
Referenced by putenv(), and setenv().
__qsort_r()
hidden void __qsort_r (void * , size_t , size_t , int(*)(const void *, const void *, void *) , void *)
Referenced by qsort().
__randname()
hidden char* __randname (char * template)
Definition at line 7 of file __randname.c.
 {
     int i;
     struct timespec ts;
     unsigned long r;
     __clock_gettime(CLOCK_REALTIME, &ts);
     r = ts.tv_sec + ts.tv_nsec + __pthread_self()->tid * 65537UL;
     for (i=0; i<6; i++, r>>=5)
         template[i] = 'A'+(r&15)+(r&16)*2;
     return template;
 }
References __clock_gettime(), __pthread_self, CLOCK_REALTIME, i, timespec::tv_nsec, and timespec::tv_sec.
Referenced by __mkostemps(), mkdtemp(), mktemp(), tempnam(), tmpfile(), and tmpnam().