Fennix: Userspace/libc/include/string.h File Reference
string.h File Reference
#include <stddef.h>
Functions
size_t strlen (const char *str)
int strcmp (const char *l, const char *r)
int strncmp (const char *s1, const char *s2, size_t n)
int strcasecmp (const char *s1, const char *s2)
int strncasecmp (const char *string1, const char *string2, size_t count)
char * strstr (const char *haystack, const char *needle)
char * strncpy (char *destination, const char *source, unsigned long num)
char * strdup (const char *s)
char * strchr (char const *s, int c)
char * strrchr (char const *s, int c)
void * memcpy (void *dest, const void *src, size_t n)
void * memset (void *dest, int c, size_t n)
void * memmove (void *dest, const void *src, size_t n)
Function Documentation
memcpy()
void* memcpy (void * dest, const void * src, size_t n)
Definition at line 1030 of file Convert.cpp.
 {
     void *ret = __memcpy_chk(dest, src, len, __builtin_object_size(dest, 0));
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "!memcpy( %p %p %ld )=%p~%p\n\r",
                 dest, src, len,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
References __memcpy_chk(), UniversalAsynchronousReceiverTransmitter::COM3, i, len, n, ret, sprintf(), strcat_unsafe(), strcpy_unsafe(), UniversalAsynchronousReceiverTransmitter::UART::Write(), and x.
Referenced by ELFGetDynamicTag(), and memmove().
memmove()
void* memmove (void * dest, const void * src, size_t n)
Definition at line 288 of file memop.c.
 {
 #ifdef __GNUC__
     typedef __attribute__((__may_alias__)) size_t WT;
 #define WS (sizeof(WT))
 #endif
     char *d = dest;
     const char *s = src;
     if (d == s)
         return d;
     if ((uintptr_t)s - (uintptr_t)d - n <= -2 * n)
         return memcpy(d, s, n);
     if (d < s)
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)d % WS)
             {
                 if (!n--)
                     return dest;
                 *d++ = *s++;
             }
             for (; n >= WS; n -= WS, d += WS, s += WS)
                 *(WT *)d = *(WT *)s;
         }
 #endif
         for (; n; n--)
             *d++ = *s++;
     }
     else
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)(d + n) % WS)
             {
                 if (!n--)
                     return dest;
                 d[n] = s[n];
             }
             while (n >= WS)
                 n -= WS, *(WT *)(d + n) = *(WT *)(s + n);
         }
 #endif
         while (n)
             n--, d[n] = s[n];
     }
     return dest;
 }
References memcpy(), and n.
memset()
void* memset (void * dest, int c, size_t n)
Definition at line 1057 of file Convert.cpp.
 {
     void *ret = __memset_chk(dest, val, len, __builtin_object_size(dest, 0));
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "!memset( %p %d %ld )=%p~%p\n\r",
                 dest, val, len,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
strcasecmp()
int strcasecmp (const char * s1, const char * s2)
Definition at line 444 of file Convert.cpp.
 {
     const unsigned char *p1 = (const unsigned char *)s1;
     const unsigned char *p2 = (const unsigned char *)s2;
     int result;
     if (p1 == p2)
         return 0;
     while ((result = std::tolower(*p1) - std::tolower(*p2++)) == 0)
         if (*p1++ == '\0')
             break;
     return result;
 }
strchr()
char* strchr (char const * s, int c)
Definition at line 144 of file Convert.cpp.
 {
     while (*String != (char)Char)
     {
         if (!*String++)
             return 0;
     }
     return (char *)String;
 }
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 120 of file Convert.cpp.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
strdup()
char* strdup (const char * s)
Definition at line 154 of file Convert.cpp.
 {
     char *OutBuffer = (char *)kmalloc(strlen((char *)String) + 1);
     strncpy(OutBuffer, String, strlen(String) + 1);
     return OutBuffer;
 }
strlen()
size_t strlen (const char * str)
Definition at line 5 of file string.c.
 {
     long unsigned i = 0;
     if (str)
         while (str[i] != '\0')
             ++i;
     return i;
 }
References i.
strncasecmp()
int strncasecmp (const char * string1, const char * string2, size_t count)
Definition at line 47 of file string.c.
 {
     if (count)
     {
         const unsigned char *s1 = (const unsigned char *)string1;
         const unsigned char *s2 = (const unsigned char *)string2;
         int result;
         do
         {
             if ((result = tolower(*s1) - tolower(*s2++)) != 0 || !*s1++)
                 break;
         } while (--count);
         return result;
     }
     return 0;
 }
References count, mlibc::result, s1, s2, and tolower.
strncmp()
int strncmp (const char * s1, const char * s2, size_t n)
Definition at line 51 of file Convert.cpp.
 {
     for (size_t i = 0; i < n; i++)
     {
         char c1 = s1[i], c2 = s2[i];
         if (c1 != c2)
             return c1 - c2;
         if (!c1)
             return 0;
     }
     return 0;
 }
strncpy()
char* strncpy (char * destination, const char * source, unsigned long num)
Definition at line 105 of file Convert.cpp.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source && num--)
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
References NULL.
Referenced by strdup().
strrchr()
char* strrchr (char const * s, int c)
Definition at line 113 of file string.c.
 {
     size_t len = strlen(s);
     size_t pos = len;
     while (s[pos] != c && pos-- != 0)
         ;
     if (pos == len)
         return NULL;
     return (char *)s + pos;
 }
strstr()
char* strstr (const char * haystack, const char * needle)
Definition at line 127 of file Convert.cpp.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }