Fennix Userspace: Userspace/musl/arch/or1k/syscall_arch.h File Reference
syscall_arch.h File Reference
Macros
#define __SYSCALL_LL_E(x)
#define __SYSCALL_LL_O(x) __SYSCALL_LL_E((x))
#define SYSCALL_MMAP2_UNIT 8192ULL
#define IPC_64 0
Functions
static __inline long __syscall0 (long n)
static long __syscall1 (long n, long a)
static long __syscall2 (long n, long a, long b)
static long __syscall3 (long n, long a, long b, long c)
static long __syscall4 (long n, long a, long b, long c, long d)
static long __syscall5 (long n, long a, long b, long c, long d, long e)
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f)
Macro Definition Documentation
__SYSCALL_LL_E
#define __SYSCALL_LL_E (x)
Value:
((union { long long ll; long l[2]; }){ .ll = x }).l[0], \
((union { long long ll; long l[2]; }){ .ll = x }).l[1]
Definition at line 1 of file syscall_arch.h.
__SYSCALL_LL_O
#define __SYSCALL_LL_O (x) __SYSCALL_LL_E((x))
Definition at line 4 of file syscall_arch.h.
IPC_64
#define IPC_64 0
Definition at line 115 of file syscall_arch.h.
SYSCALL_MMAP2_UNIT
#define SYSCALL_MMAP2_UNIT 8192ULL
Definition at line 6 of file syscall_arch.h.
Function Documentation
__syscall0()
static __inline long __syscall0 (long n) static
Definition at line 8 of file syscall_arch.h.
 {
     register unsigned long r11 __asm__("r11") = n;
     __asm__ __volatile__ ("l.sys 1"
                   : "=r"(r11)
                   : "r"(r11)
                   : "memory", "r3", "r4", "r5", "r6", "r7", "r8",
                 "r12", "r13", "r15", "r17", "r19", "r21",
                 "r23", "r25", "r27", "r29", "r31");
     return r11;
 }
References __asm__(), and n.
__syscall1()
static long __syscall1 (long n, long a) inline static
Definition at line 20 of file syscall_arch.h.
 {
     register unsigned long r11 __asm__("r11") = n;
     register unsigned long r3 __asm__("r3") = a;
     __asm__ __volatile__ ("l.sys 1"
                   : "=r"(r11)
                   : "r"(r11), "r"(r3)
                   : "memory", "r4", "r5", "r6", "r7", "r8",
                 "r12", "r13", "r15", "r17", "r19", "r21",
                 "r23", "r25", "r27", "r29", "r31");
     return r11;
 }
References __asm__(), n, and r3.
__syscall2()
static long __syscall2 (long n, long a, long b) inline static
Definition at line 33 of file syscall_arch.h.
 {
     register unsigned long r11 __asm__("r11") = n;
     register unsigned long r3 __asm__("r3") = a;
     register unsigned long r4 __asm__("r4") = b;
     __asm__ __volatile__ ("l.sys 1"
                   : "=r"(r11)
                   : "r"(r11), "r"(r3), "r"(r4)
                   : "memory", "r5", "r6", "r7", "r8",
                 "r12", "r13", "r15", "r17", "r19", "r21",
                 "r23", "r25", "r27", "r29", "r31");
     return r11;
 }
References __asm__(), b, n, r3, and r4.
__syscall3()
static long __syscall3 (long n, long a, long b, long c) inline static
Definition at line 47 of file syscall_arch.h.
 {
     register unsigned long r11 __asm__("r11") = n;
     register unsigned long r3 __asm__("r3") = a;
     register unsigned long r4 __asm__("r4") = b;
     register unsigned long r5 __asm__("r5") = c;
     __asm__ __volatile__ ("l.sys 1"
                   : "=r"(r11)
                   : "r"(r11), "r"(r3), "r"(r4), "r"(r5)
                   : "memory", "r6", "r7", "r8",
                 "r12", "r13", "r15", "r17", "r19", "r21",
                 "r23", "r25", "r27", "r29", "r31");
     return r11;
 }
References __asm__(), b, c, n, r3, r4, and r5.
__syscall4()
static long __syscall4 (long n, long a, long b, long c, long d) inline static
Definition at line 62 of file syscall_arch.h.
 {
     register unsigned long r11 __asm__("r11") = n;
     register unsigned long r3 __asm__("r3") = a;
     register unsigned long r4 __asm__("r4") = b;
     register unsigned long r5 __asm__("r5") = c;
     register unsigned long r6 __asm__("r6") = d;
     __asm__ __volatile__ ("l.sys 1"
                   : "=r"(r11)
                   : "r"(r11), "r"(r3), "r"(r4), "r"(r5), "r"(r6)
                   : "memory", "r7", "r8",
                 "r12", "r13", "r15", "r17", "r19", "r21",
                 "r23", "r25", "r27", "r29", "r31");
     return r11;
 }
References __asm__(), b, c, n, r3, r4, r5, and r6.
__syscall5()
static long __syscall5 (long n, long a, long b, long c, long d, long e) inline static
Definition at line 78 of file syscall_arch.h.
 {
     register unsigned long r11 __asm__("r11") = n;
     register unsigned long r3 __asm__("r3") = a;
     register unsigned long r4 __asm__("r4") = b;
     register unsigned long r5 __asm__("r5") = c;
     register unsigned long r6 __asm__("r6") = d;
     register unsigned long r7 __asm__("r7") = e;
     __asm__ __volatile__ ("l.sys 1"
                   : "=r"(r11)
                   : "r"(r11), "r"(r3), "r"(r4), "r"(r5), "r"(r6),
                 "r"(r7)
                   : "memory", "r8",
                 "r12", "r13", "r15", "r17", "r19", "r21",
                 "r23", "r25", "r27", "r29", "r31");
     return r11;
 }
References __asm__(), b, c, n, r3, r4, r5, and r6.
__syscall6()
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f) inline static
Definition at line 96 of file syscall_arch.h.
 {
     register unsigned long r11 __asm__("r11") = n;
     register unsigned long r3 __asm__("r3") = a;
     register unsigned long r4 __asm__("r4") = b;
     register unsigned long r5 __asm__("r5") = c;
     register unsigned long r6 __asm__("r6") = d;
     register unsigned long r7 __asm__("r7") = e;
     register unsigned long r8 __asm__("r8") = f;
     __asm__ __volatile__ ("l.sys 1"
                   : "=r"(r11)
                   : "r"(r11), "r"(r3), "r"(r4), "r"(r5), "r"(r6),
                 "r"(r7), "r"(r8)
                   : "memory",
                 "r12", "r13", "r15", "r17", "r19", "r21",
                 "r23", "r25", "r27", "r29", "r31");
     return r11;
 }
References __asm__(), b, c, f, n, r3, r4, r5, and r6.