Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/r_data.c File Reference
r_data.c File Reference
#include <stdio.h>
#include "deh_main.h"
#include "i_swap.h"
#include "i_system.h"
#include "z_zone.h"
#include "w_wad.h"
#include "doomdef.h"
#include "m_misc.h"
#include "r_local.h"
#include "p_local.h"
#include "doomstat.h"
#include "r_sky.h"
#include "r_data.h"
Data Structures
struct PACKEDATTR
struct texpatch_t
struct texture_s
Typedefs
typedef struct texture_s texture_t
Functions
void R_DrawColumnInCache (column_t *patch, byte *cache, int originy, int cacheheight)
void R_GenerateComposite (int texnum)
void R_GenerateLookup (int texnum)
byte * R_GetColumn (int tex, int col)
static void GenerateTextureHashTable (void)
void R_InitTextures (void)
void R_InitFlats (void)
void R_InitSpriteLumps (void)
void R_InitColormaps (void)
void R_InitData (void)
int R_FlatNumForName (char *name)
int R_CheckTextureNumForName (char *name)
int R_TextureNumForName (char *name)
void R_PrecacheLevel (void)
Variables
int firstflat
int lastflat
int numflats
int firstpatch
int lastpatch
int numpatches
int firstspritelump
int lastspritelump
int numspritelumps
int numtextures
texture_t ** textures
texture_t ** textures_hashtable
int * texturewidthmask
fixed_t * textureheight
int * texturecompositesize
short ** texturecolumnlump
unsigned short ** texturecolumnofs
byte ** texturecomposite
int * flattranslation
int * texturetranslation
fixed_t * spritewidth
fixed_t * spriteoffset
fixed_t * spritetopoffset
lighttable_t * colormaps
int flatmemory
int texturememory
int spritememory
Data Structure Documentation
PACKEDATTR
struct PACKEDATTR
Definition at line 57 of file doomdata.h.
Data Fields
short angle
short bbox[2][4]
char bits_per_pixel
char bottomtexture[8]
unsigned short bytes_per_line
short ceilingheight
char ceilingpic[8]
unsigned short children[2]
char color_planes
short colormap
int columnofs[8]
unsigned char data
short dx
short dy
char encoding
int filepos
char filler[58]
short firstseg
short flags
short floorheight
char floorpic[8]
short height
unsigned short hres
char identification[4]
int infotableofs
short leftoffset
byte length
short lightlevel
short linedef
char manufacturer
int masked
char midtexture[8]
char name[8]
int numlumps
short numsegs
int obsolete
short offset
short options
short originx
short originy
unsigned char palette[48]
unsigned short palette_type
short patch
short patchcount
mappatch_t patches[1]
char reserved
short rowoffset
short sector
short side
short sidenum[2]
int size
short special
short stepdir
short tag
short textureoffset
byte topdelta
short topoffset
char toptexture[8]
short type
short v1
short v2
char version
unsigned short vres
short width
short x
unsigned short xmax
unsigned short xmin
short y
unsigned short ymax
unsigned short ymin
texpatch_t
struct texpatch_t
Definition at line 89 of file r_data.c.
Data Fields
short originx
short originy
int patch
texture_s
struct texture_s
Definition at line 106 of file r_data.c.
Data Fields
short height
int index
char name[8]
texture_t * next
short patchcount
texpatch_t patches[1]
short width
Typedef Documentation
texture_t
typedef struct texture_s texture_t
Definition at line 1 of file r_data.c.
Function Documentation
GenerateTextureHashTable()
static void GenerateTextureHashTable (void) static
Definition at line 404 of file r_data.c.
 {
     texture_t **rover;
     int i;
     int key;
     textures_hashtable
             = Z_Malloc(sizeof(texture_t *) * numtextures, PU_STATIC, 0);
     memset(textures_hashtable, 0, sizeof(texture_t *) * numtextures);
     // Add all textures to hash table
     for (i=0; i<numtextures; ++i)
     {
         // Store index
         textures[i]->index = i;
         // Vanilla Doom does a linear search of the texures array
         // and stops at the first entry it finds.  If there are two
         // entries with the same name, the first one in the array
         // wins. The new entry must therefore be added at the end
         // of the hash chain, so that earlier entries win.
         key = W_LumpNameHash(textures[i]->name) % numtextures;
         rover = &textures_hashtable[key];
         while (*rover != NULL)
         {
             rover = &(*rover)->next;
         }
         // Hook into hash table
         textures[i]->next = NULL;
         *rover = textures[i];
     }
 }
References i, texture_s::index, memset(), name, texture_s::next, NULL, numtextures, PU_STATIC, textures, textures_hashtable, W_LumpNameHash(), and Z_Malloc().
Referenced by R_InitTextures().
R_CheckTextureNumForName()
int R_CheckTextureNumForName (char * name)
Definition at line 744 of file r_data.c.
 {
     texture_t *texture;
     int key;
     // "NoTexture" marker.
     if (name[0] == '-')
     return 0;
     key = W_LumpNameHash(name) % numtextures;
     texture=textures_hashtable[key];
     while (texture != NULL)
     {
     if (!strncasecmp (texture->name, name, 8) )
         return texture->index;
         texture = texture->next;
     }
     return -1;
 }
References texture_s::index, texture_s::name, name, texture_s::next, NULL, numtextures, strncasecmp(), textures_hashtable, and W_LumpNameHash().
Referenced by P_InitPicAnims(), P_InitSwitchList(), and R_TextureNumForName().
R_DrawColumnInCache()
void R_DrawColumnInCache (column_t * patch, byte * cache, int originy, int cacheheight)
Definition at line 186 of file r_data.c.
 {
     int     count;
     int     position;
     byte*   source;
     while (patch->topdelta != 0xff)
     {
     source = (byte *)patch + 3;
     count = patch->length;
     position = originy + patch->topdelta;
     if (position < 0)
     {
         count += position;
         position = 0;
     }
     if (position + count > cacheheight)
         count = cacheheight - position;
     if (count > 0)
         memcpy (cache + position, source, count);
     patch = (column_t *)(  (byte *)patch + patch->length + 4);
     }
 }
References mlibc::count, and memcpy().
Referenced by R_GenerateComposite().
R_FlatNumForName()
int R_FlatNumForName (char * name)
Definition at line 720 of file r_data.c.
 {
     int     i;
     char    namet[9];
     i = W_CheckNumForName (name);
     if (i == -1)
     {
     namet[8] = 0;
     memcpy (namet, name,8);
     I_Error ("R_FlatNumForName: %s not found",namet);
     }
     return i - firstflat;
 }
References firstflat, i, I_Error(), memcpy(), name, and W_CheckNumForName().
Referenced by G_DoLoadLevel(), P_InitPicAnims(), and P_LoadSectors().
R_GenerateComposite()
void R_GenerateComposite (int texnum)
Definition at line 226 of file r_data.c.
 {
     byte*       block;
     texture_t*      texture;
     texpatch_t*     patch;
     patch_t*        realpatch;
     int         x;
     int         x1;
     int         x2;
     int         i;
     column_t*       patchcol;
     short*      collump;
     unsigned short* colofs;
     texture = textures[texnum];
     block = Z_Malloc (texturecompositesize[texnum],
               PU_STATIC,
               &texturecomposite[texnum]);
     collump = texturecolumnlump[texnum];
     colofs = texturecolumnofs[texnum];
     // Composite the columns together.
     patch = texture->patches;
     for (i=0 , patch = texture->patches;
      i<texture->patchcount;
      i++, patch++)
     {
     realpatch = W_CacheLumpNum (patch->patch, PU_CACHE);
     x1 = patch->originx;
     x2 = x1 + SHORT(realpatch->width);
     if (x1<0)
         x = 0;
     else
         x = x1;
     if (x2 > texture->width)
         x2 = texture->width;
     for ( ; x<x2 ; x++)
     {
         // Column does not have multiple patches?
         if (collump[x] >= 0)
         continue;
         patchcol = (column_t *)((byte *)realpatch
                     + LONG(realpatch->columnofs[x-x1]));
         R_DrawColumnInCache (patchcol,
                  block + colofs[x],
                  patch->originy,
                  texture->height);
     }
     }
     // Now that the texture has been built in column cache,
     //  it is purgable from zone memory.
     Z_ChangeTag (block, PU_CACHE);
 }
References texture_s::height, i, LONG, texpatch_t::originx, texpatch_t::originy, texpatch_t::patch, texture_s::patches, PU_CACHE, PU_STATIC, R_DrawColumnInCache(), SHORT, texturecolumnlump, texturecolumnofs, texturecomposite, texturecompositesize, textures, W_CacheLumpNum(), texture_s::width, x, Z_ChangeTag, and Z_Malloc().
Referenced by R_GetColumn().
R_GenerateLookup()
void R_GenerateLookup (int texnum)
Definition at line 294 of file r_data.c.
 {
     texture_t*      texture;
     byte*       patchcount; // patchcount[texture->width]
     texpatch_t*     patch;
     patch_t*        realpatch;
     int         x;
     int         x1;
     int         x2;
     int         i;
     short*      collump;
     unsigned short* colofs;
     texture = textures[texnum];
     // Composited texture not created yet.
     texturecomposite[texnum] = 0;
     texturecompositesize[texnum] = 0;
     collump = texturecolumnlump[texnum];
     colofs = texturecolumnofs[texnum];
     // Now count the number of columns
     //  that are covered by more than one patch.
     // Fill in the lump / offset, so columns
     //  with only a single patch are all done.
     patchcount = (byte *) Z_Malloc(texture->width, PU_STATIC, &patchcount);
     memset (patchcount, 0, texture->width);
     patch = texture->patches;
     for (i=0 , patch = texture->patches;
      i<texture->patchcount;
      i++, patch++)
     {
     realpatch = W_CacheLumpNum (patch->patch, PU_CACHE);
     x1 = patch->originx;
     x2 = x1 + SHORT(realpatch->width);
     if (x1 < 0)
         x = 0;
     else
         x = x1;
     if (x2 > texture->width)
         x2 = texture->width;
     for ( ; x<x2 ; x++)
     {
         patchcount[x]++;
         collump[x] = patch->patch;
         colofs[x] = LONG(realpatch->columnofs[x-x1])+3;
     }
     }
     for (x=0 ; x<texture->width ; x++)
     {
     if (!patchcount[x])
     {
         printf ("R_GenerateLookup: column without a patch (%s)\n",
             texture->name);
         return;
     }
     // I_Error ("R_GenerateLookup: column without a patch");
     if (patchcount[x] > 1)
     {
         // Use the cached block.
         collump[x] = -1;
         colofs[x] = texturecompositesize[texnum];
         if (texturecompositesize[texnum] > 0x10000-texture->height)
         {
         I_Error ("R_GenerateLookup: texture %i is >64k",
              texnum);
         }
         texturecompositesize[texnum] += texture->height;
     }
     }
     Z_Free(patchcount);
 }
References texture_s::height, i, I_Error(), LONG, memset(), texture_s::name, texpatch_t::originx, texpatch_t::patch, texture_s::patches, printf(), PU_CACHE, PU_STATIC, SHORT, texturecolumnlump, texturecolumnofs, texturecomposite, texturecompositesize, textures, W_CacheLumpNum(), texture_s::width, x, Z_Free(), and Z_Malloc().
Referenced by R_InitTextures().
R_GetColumn()
byte* R_GetColumn (int tex, int col)
Definition at line 383 of file r_data.c.
 {
     int     lump;
     int     ofs;
     col &= texturewidthmask[tex];
     lump = texturecolumnlump[tex][col];
     ofs = texturecolumnofs[tex][col];
     if (lump > 0)
     return (byte *)W_CacheLumpNum(lump,PU_CACHE)+ofs;
     if (!texturecomposite[tex])
     R_GenerateComposite (tex);
     return texturecomposite[tex] + ofs;
 }
References PU_CACHE, R_GenerateComposite(), texturecolumnlump, texturecolumnofs, texturecomposite, texturewidthmask, and W_CacheLumpNum().
Referenced by R_DrawPlanes(), R_RenderMaskedSegRange(), and R_RenderSegLoop().
R_InitColormaps()
void R_InitColormaps (void)
Definition at line 685 of file r_data.c.
 {
     int lump;
     // Load in the light tables,
     //  256 byte align tables.
     lump = W_GetNumForName(DEH_String("COLORMAP"));
     colormaps = W_CacheLumpNum(lump, PU_STATIC);
 }
References colormaps, DEH_String, PU_STATIC, W_CacheLumpNum(), and W_GetNumForName().
Referenced by R_InitData().
R_InitData()
void R_InitData (void)
Definition at line 703 of file r_data.c.
 {
     R_InitTextures ();
     printf (".");
     R_InitFlats ();
     printf (".");
     R_InitSpriteLumps ();
     printf (".");
     R_InitColormaps ();
 }
References printf(), R_InitColormaps(), R_InitFlats(), R_InitSpriteLumps(), and R_InitTextures().
Referenced by R_Init().
R_InitFlats()
void R_InitFlats (void)
Definition at line 633 of file r_data.c.
 {
     int     i;
     firstflat = W_GetNumForName (DEH_String("F_START")) + 1;
     lastflat = W_GetNumForName (DEH_String("F_END")) - 1;
     numflats = lastflat - firstflat + 1;
     // Create translation table for global animation.
     flattranslation = Z_Malloc ((numflats+1)*sizeof(*flattranslation), PU_STATIC, 0);
     for (i=0 ; i<numflats ; i++)
     flattranslation[i] = i;
 }
References DEH_String, firstflat, flattranslation, i, lastflat, numflats, PU_STATIC, W_GetNumForName(), and Z_Malloc().
Referenced by R_InitData().
R_InitSpriteLumps()
void R_InitSpriteLumps (void)
Definition at line 655 of file r_data.c.
 {
     int     i;
     patch_t *patch;
     firstspritelump = W_GetNumForName (DEH_String("S_START")) + 1;
     lastspritelump = W_GetNumForName (DEH_String("S_END")) - 1;
     numspritelumps = lastspritelump - firstspritelump + 1;
     spritewidth = Z_Malloc (numspritelumps*sizeof(*spritewidth), PU_STATIC, 0);
     spriteoffset = Z_Malloc (numspritelumps*sizeof(*spriteoffset), PU_STATIC, 0);
     spritetopoffset = Z_Malloc (numspritelumps*sizeof(*spritetopoffset), PU_STATIC, 0);
     for (i=0 ; i< numspritelumps ; i++)
     {
     if (!(i&63))
         printf (".");
     patch = W_CacheLumpNum (firstspritelump+i, PU_CACHE);
     spritewidth[i] = SHORT(patch->width)<<FRACBITS;
     spriteoffset[i] = SHORT(patch->leftoffset)<<FRACBITS;
     spritetopoffset[i] = SHORT(patch->topoffset)<<FRACBITS;
     }
 }
References DEH_String, firstspritelump, FRACBITS, i, lastspritelump, numspritelumps, printf(), PU_CACHE, PU_STATIC, SHORT, spriteoffset, spritetopoffset, spritewidth, W_CacheLumpNum(), W_GetNumForName(), and Z_Malloc().
Referenced by R_InitData().
R_InitTextures()
void R_InitTextures (void)
Definition at line 451 of file r_data.c.
 {
     maptexture_t*   mtexture;
     texture_t*      texture;
     mappatch_t*     mpatch;
     texpatch_t*     patch;
     int         i;
     int         j;
     int*        maptex;
     int*        maptex2;
     int*        maptex1;
     char        name[9];
     char*       names;
     char*       name_p;
     int*        patchlookup;
     int         totalwidth;
     int         nummappatches;
     int         offset;
     int         maxoff;
     int         maxoff2;
     int         numtextures1;
     int         numtextures2;
     int*        directory;
     int         temp1;
     int         temp2;
     int         temp3;
     // Load the patch names from pnames.lmp.
     name[8] = 0;
     names = W_CacheLumpName (DEH_String("PNAMES"), PU_STATIC);
     nummappatches = LONG ( *((int *)names) );
     name_p = names + 4;
     patchlookup = Z_Malloc(nummappatches*sizeof(*patchlookup), PU_STATIC, NULL);
     for (i = 0; i < nummappatches; i++)
     {
         M_StringCopy(name, name_p + i * 8, sizeof(name));
         patchlookup[i] = W_CheckNumForName(name);
     }
     W_ReleaseLumpName(DEH_String("PNAMES"));
     // Load the map texture definitions from textures.lmp.
     // The data is contained in one or two lumps,
     //  TEXTURE1 for shareware, plus TEXTURE2 for commercial.
     maptex = maptex1 = W_CacheLumpName (DEH_String("TEXTURE1"), PU_STATIC);
     numtextures1 = LONG(*maptex);
     maxoff = W_LumpLength (W_GetNumForName (DEH_String("TEXTURE1")));
     directory = maptex+1;
     if (W_CheckNumForName (DEH_String("TEXTURE2")) != -1)
     {
     maptex2 = W_CacheLumpName (DEH_String("TEXTURE2"), PU_STATIC);
     numtextures2 = LONG(*maptex2);
     maxoff2 = W_LumpLength (W_GetNumForName (DEH_String("TEXTURE2")));
     }
     else
     {
     maptex2 = NULL;
     numtextures2 = 0;
     maxoff2 = 0;
     }
     numtextures = numtextures1 + numtextures2;
     textures = Z_Malloc (numtextures * sizeof(*textures), PU_STATIC, 0);
     texturecolumnlump = Z_Malloc (numtextures * sizeof(*texturecolumnlump), PU_STATIC, 0);
     texturecolumnofs = Z_Malloc (numtextures * sizeof(*texturecolumnofs), PU_STATIC, 0);
     texturecomposite = Z_Malloc (numtextures * sizeof(*texturecomposite), PU_STATIC, 0);
     texturecompositesize = Z_Malloc (numtextures * sizeof(*texturecompositesize), PU_STATIC, 0);
     texturewidthmask = Z_Malloc (numtextures * sizeof(*texturewidthmask), PU_STATIC, 0);
     textureheight = Z_Malloc (numtextures * sizeof(*textureheight), PU_STATIC, 0);
     totalwidth = 0;
     //  Really complex printing shit...
     temp1 = W_GetNumForName (DEH_String("S_START"));  // P_???????
     temp2 = W_GetNumForName (DEH_String("S_END")) - 1;
     temp3 = ((temp2-temp1+63)/64) + ((numtextures+63)/64);
     // If stdout is a real console, use the classic vanilla "filling
     // up the box" effect, which uses backspace to "step back" inside
     // the box.  If stdout is a file, don't draw the box.
     if (I_ConsoleStdout())
     {
         printf("[");
         for (i = 0; i < temp3 + 9; i++)
             printf(" ");
         printf("]");
         for (i = 0; i < temp3 + 10; i++)
             printf("\b");
     }
     for (i=0 ; i<numtextures ; i++, directory++)
     {
     if (!(i&63))
         printf (".");
     if (i == numtextures1)
     {
         // Start looking in second texture file.
         maptex = maptex2;
         maxoff = maxoff2;
         directory = maptex+1;
     }
     offset = LONG(*directory);
     if (offset > maxoff)
         I_Error ("R_InitTextures: bad texture directory");
     mtexture = (maptexture_t *) ( (byte *)maptex + offset);
     texture = textures[i] =
         Z_Malloc (sizeof(texture_t)
               + sizeof(texpatch_t)*(SHORT(mtexture->patchcount)-1),
               PU_STATIC, 0);
     texture->width = SHORT(mtexture->width);
     texture->height = SHORT(mtexture->height);
     texture->patchcount = SHORT(mtexture->patchcount);
     memcpy (texture->name, mtexture->name, sizeof(texture->name));
     mpatch = &mtexture->patches[0];
     patch = &texture->patches[0];
     for (j=0 ; j<texture->patchcount ; j++, mpatch++, patch++)
     {
         patch->originx = SHORT(mpatch->originx);
         patch->originy = SHORT(mpatch->originy);
         patch->patch = patchlookup[SHORT(mpatch->patch)];
         if (patch->patch == -1)
         {
         I_Error ("R_InitTextures: Missing patch in texture %s",
              texture->name);
         }
     }
     texturecolumnlump[i] = Z_Malloc (texture->width*sizeof(**texturecolumnlump), PU_STATIC,0);
     texturecolumnofs[i] = Z_Malloc (texture->width*sizeof(**texturecolumnofs), PU_STATIC,0);
     j = 1;
     while (j*2 <= texture->width)
         j<<=1;
     texturewidthmask[i] = j-1;
     textureheight[i] = texture->height<<FRACBITS;
     totalwidth += texture->width;
     }
     Z_Free(patchlookup);
     W_ReleaseLumpName(DEH_String("TEXTURE1"));
     if (maptex2)
         W_ReleaseLumpName(DEH_String("TEXTURE2"));
     // Precalculate whatever possible.
     for (i=0 ; i<numtextures ; i++)
     R_GenerateLookup (i);
     // Create translation table for global animation.
     texturetranslation = Z_Malloc ((numtextures+1)*sizeof(*texturetranslation), PU_STATIC, 0);
     for (i=0 ; i<numtextures ; i++)
     texturetranslation[i] = i;
     GenerateTextureHashTable();
 }
References DEH_String, FRACBITS, GenerateTextureHashTable(), texture_s::height, i, I_ConsoleStdout(), I_Error(), j, LONG, M_StringCopy(), memcpy(), texture_s::name, name, NULL, numtextures, offset, texpatch_t::originx, texpatch_t::originy, texpatch_t::patch, texture_s::patchcount, texture_s::patches, printf(), PU_STATIC, R_GenerateLookup(), SHORT, texturecolumnlump, texturecolumnofs, texturecomposite, texturecompositesize, textureheight, textures, texturetranslation, texturewidthmask, W_CacheLumpName(), W_CheckNumForName(), W_GetNumForName(), W_LumpLength(), W_ReleaseLumpName(), texture_s::width, Z_Free(), and Z_Malloc().
Referenced by R_InitData().
R_PrecacheLevel()
void R_PrecacheLevel (void)
Definition at line 800 of file r_data.c.
 {
     char*       flatpresent;
     char*       texturepresent;
     char*       spritepresent;
     int         i;
     int         j;
     int         k;
     int         lump;
     texture_t*      texture;
     thinker_t*      th;
     spriteframe_t*  sf;
     if (demoplayback)
     return;
     // Precache flats.
     flatpresent = Z_Malloc(numflats, PU_STATIC, NULL);
     memset (flatpresent,0,numflats);
     for (i=0 ; i<numsectors ; i++)
     {
     flatpresent[sectors[i].floorpic] = 1;
     flatpresent[sectors[i].ceilingpic] = 1;
     }
     flatmemory = 0;
     for (i=0 ; i<numflats ; i++)
     {
     if (flatpresent[i])
     {
         lump = firstflat + i;
         flatmemory += lumpinfo[lump].size;
         W_CacheLumpNum(lump, PU_CACHE);
     }
     }
     Z_Free(flatpresent);
     // Precache textures.
     texturepresent = Z_Malloc(numtextures, PU_STATIC, NULL);
     memset (texturepresent,0, numtextures);
     for (i=0 ; i<numsides ; i++)
     {
     texturepresent[sides[i].toptexture] = 1;
     texturepresent[sides[i].midtexture] = 1;
     texturepresent[sides[i].bottomtexture] = 1;
     }
     // Sky texture is always present.
     // Note that F_SKY1 is the name used to
     //  indicate a sky floor/ceiling as a flat,
     //  while the sky texture is stored like
     //  a wall texture, with an episode dependend
     //  name.
     texturepresent[skytexture] = 1;
     texturememory = 0;
     for (i=0 ; i<numtextures ; i++)
     {
     if (!texturepresent[i])
         continue;
     texture = textures[i];
     for (j=0 ; j<texture->patchcount ; j++)
     {
         lump = texture->patches[j].patch;
         texturememory += lumpinfo[lump].size;
         W_CacheLumpNum(lump , PU_CACHE);
     }
     }
     Z_Free(texturepresent);
     // Precache sprites.
     spritepresent = Z_Malloc(numsprites, PU_STATIC, NULL);
     memset (spritepresent,0, numsprites);
     for (th = thinkercap.next ; th != &thinkercap ; th=th->next)
     {
     if (th->function.acp1 == (actionf_p1)P_MobjThinker)
         spritepresent[((mobj_t *)th)->sprite] = 1;
     }
     spritememory = 0;
     for (i=0 ; i<numsprites ; i++)
     {
     if (!spritepresent[i])
         continue;
     for (j=0 ; j<sprites[i].numframes ; j++)
     {
         sf = &sprites[i].spriteframes[j];
         for (k=0 ; k<8 ; k++)
         {
         lump = firstspritelump + sf->lump[k];
         spritememory += lumpinfo[lump].size;
         W_CacheLumpNum(lump , PU_CACHE);
         }
     }
     }
     Z_Free(spritepresent);
 }
References actionf_t::acp1, side_t::bottomtexture, sector_t::ceilingpic, demoplayback, firstflat, firstspritelump, flatmemory, sector_t::floorpic, thinker_s::function, i, j, k, spriteframe_t::lump, lumpinfo, memset(), side_t::midtexture, thinker_s::next, NULL, numflats, spritedef_t::numframes, numsectors, numsides, numsprites, numtextures, P_MobjThinker(), texpatch_t::patch, texture_s::patchcount, texture_s::patches, PU_CACHE, PU_STATIC, sectors, sides, lumpinfo_s::size, skytexture, spritedef_t::spriteframes, spritememory, sprites, texturememory, textures, thinkercap, side_t::toptexture, W_CacheLumpNum(), Z_Free(), and Z_Malloc().
Referenced by P_SetupLevel().
R_TextureNumForName()
int R_TextureNumForName (char * name)
Definition at line 775 of file r_data.c.
 {
     int     i;
     i = R_CheckTextureNumForName (name);
     if (i==-1)
     {
     I_Error ("R_TextureNumForName: %s not found",
          name);
     }
     return i;
 }
References i, I_Error(), name, and R_CheckTextureNumForName().
Referenced by G_DoLoadLevel(), G_InitNew(), P_InitPicAnims(), P_InitSwitchList(), and P_LoadSideDefs().
Variable Documentation
colormaps
lighttable_t* colormaps
Definition at line 163 of file r_data.c.
Referenced by R_DrawFuzzColumn(), R_DrawFuzzColumnLow(), R_DrawPlanes(), R_DrawPSprite(), R_ExecuteSetViewSize(), R_InitColormaps(), R_InitLightTables(), R_ProjectSprite(), and R_SetupFrame().
firstflat
int firstflat
Definition at line 129 of file r_data.c.
Referenced by R_DrawPlanes(), R_FlatNumForName(), R_InitFlats(), and R_PrecacheLevel().
firstpatch
int firstpatch
Definition at line 133 of file r_data.c.
firstspritelump
int firstspritelump
Definition at line 137 of file r_data.c.
Referenced by F_CastDrawer(), R_DrawVisSprite(), R_InitSpriteDefs(), R_InitSpriteLumps(), R_InstallSpriteLump(), and R_PrecacheLevel().
flatmemory
int flatmemory
Definition at line 796 of file r_data.c.
Referenced by R_PrecacheLevel().
flattranslation
int* flattranslation
Definition at line 155 of file r_data.c.
Referenced by P_UpdateSpecials(), R_DrawPlanes(), and R_InitFlats().
lastflat
int lastflat
Definition at line 130 of file r_data.c.
Referenced by R_InitFlats().
lastpatch
int lastpatch
Definition at line 134 of file r_data.c.
lastspritelump
int lastspritelump
Definition at line 138 of file r_data.c.
Referenced by R_InitSpriteDefs(), and R_InitSpriteLumps().
numflats
int numflats
Definition at line 131 of file r_data.c.
Referenced by DonutOverrun(), R_InitFlats(), and R_PrecacheLevel().
numpatches
int numpatches
Definition at line 135 of file r_data.c.
numspritelumps
int numspritelumps
Definition at line 139 of file r_data.c.
Referenced by R_InitSpriteLumps().
numtextures
int numtextures
Definition at line 141 of file r_data.c.
Referenced by GenerateTextureHashTable(), R_CheckTextureNumForName(), R_InitTextures(), and R_PrecacheLevel().
spritememory
int spritememory
Definition at line 798 of file r_data.c.
Referenced by R_PrecacheLevel().
spriteoffset
fixed_t* spriteoffset
Definition at line 160 of file r_data.c.
Referenced by R_DrawPSprite(), R_InitSpriteLumps(), and R_ProjectSprite().
spritetopoffset
fixed_t* spritetopoffset
Definition at line 161 of file r_data.c.
Referenced by R_DrawPSprite(), R_InitSpriteLumps(), and R_ProjectSprite().
spritewidth
fixed_t* spritewidth
Definition at line 159 of file r_data.c.
Referenced by R_DrawPSprite(), R_InitSpriteLumps(), and R_ProjectSprite().
texturecolumnlump
short** texturecolumnlump
Definition at line 150 of file r_data.c.
Referenced by R_GenerateComposite(), R_GenerateLookup(), R_GetColumn(), and R_InitTextures().
texturecolumnofs
unsigned short** texturecolumnofs
Definition at line 151 of file r_data.c.
Referenced by R_GenerateComposite(), R_GenerateLookup(), R_GetColumn(), and R_InitTextures().
texturecomposite
byte** texturecomposite
Definition at line 152 of file r_data.c.
Referenced by R_GenerateComposite(), R_GenerateLookup(), R_GetColumn(), and R_InitTextures().
texturecompositesize
int* texturecompositesize
Definition at line 149 of file r_data.c.
Referenced by R_GenerateComposite(), R_GenerateLookup(), and R_InitTextures().
textureheight
fixed_t* textureheight
Definition at line 148 of file r_data.c.
Referenced by EV_DoFloor(), R_InitTextures(), R_RenderMaskedSegRange(), and R_StoreWallRange().
texturememory
int texturememory
Definition at line 797 of file r_data.c.
Referenced by R_PrecacheLevel().
textures
texture_t** textures
Definition at line 142 of file r_data.c.
Referenced by GenerateTextureHashTable(), R_GenerateComposite(), R_GenerateLookup(), R_InitTextures(), and R_PrecacheLevel().
textures_hashtable
texture_t** textures_hashtable
Definition at line 143 of file r_data.c.
Referenced by GenerateTextureHashTable(), and R_CheckTextureNumForName().
texturetranslation
int* texturetranslation
Definition at line 156 of file r_data.c.
Referenced by P_UpdateSpecials(), R_InitTextures(), R_RenderMaskedSegRange(), and R_StoreWallRange().
texturewidthmask
int* texturewidthmask
Definition at line 146 of file r_data.c.
Referenced by R_GetColumn(), and R_InitTextures().