Fennix Userspace: ConfigMainWindow Class Reference
ConfigMainWindow Class Reference
#include <qconf.h>
Public Slots
void setHelp (QListViewItem *item)
void changeMenu (struct menu *)
void listFocusChanged (void)
void goBack (void)
void loadConfig (void)
void saveConfig (void)
void saveConfigAs (void)
void showSingleView (void)
void showSplitView (void)
void showFullView (void)
void setShowAll (bool)
void setShowDebug (bool)
void setShowRange (bool)
void setShowName (bool)
void setShowData (bool)
void showIntro (void)
void showAbout (void)
void saveSettings (void)
Public Member Functions
ConfigMainWindow (void)
Protected Member Functions
void closeEvent (QCloseEvent *e)
Protected Attributes
ConfigView * menuView
ConfigList * menuList
ConfigView * configView
ConfigList * configList
QTextView * helpText
QToolBar * toolBar
QAction * backAction
QSplitter * split1
QSplitter * split2
bool showDebug
Detailed Description
Definition at line 225 of file qconf.h.
Constructor & Destructor Documentation
ConfigMainWindow()
ConfigMainWindow::ConfigMainWindow (void)
Definition at line 813 of file qconf.cc.
 {
     QMenuBar* menu;
     bool ok;
     int x, y, width, height;
     QWidget *d = configApp->desktop();
     ConfigSettings* configSettings = new ConfigSettings();
 #if QT_VERSION >= 300
     width = configSettings->readNumEntry("/kconfig/qconf/window width", d->width() - 64);
     height = configSettings->readNumEntry("/kconfig/qconf/window height", d->height() - 64);
     resize(width, height);
     x = configSettings->readNumEntry("/kconfig/qconf/window x", 0, &ok);
     if (ok)
         y = configSettings->readNumEntry("/kconfig/qconf/window y", 0, &ok);
     if (ok)
         move(x, y);
     showDebug = configSettings->readBoolEntry("/kconfig/qconf/showDebug", false);
     // read list settings into configSettings, will be used later for ConfigList setup
     configSettings->readListSettings();
 #else
     width = d->width() - 64;
     height = d->height() - 64;
     resize(width, height);
     showDebug = false;
 #endif
     split1 = new QSplitter(this);
     split1->setOrientation(QSplitter::Horizontal);
     setCentralWidget(split1);
     menuView = new ConfigView(split1, this, configSettings);
     menuList = menuView->list;
     split2 = new QSplitter(split1);
     split2->setOrientation(QSplitter::Vertical);
     // create config tree
     configView = new ConfigView(split2, this, configSettings);
     configList = configView->list;
     helpText = new QTextView(split2);
     helpText->setTextFormat(Qt::RichText);
     setTabOrder(configList, helpText);
     configList->setFocus();
     menu = menuBar();
     toolBar = new QToolBar("Tools", this);
     backAction = new QAction("Back", QPixmap(xpm_back), "Back", 0, this);
       connect(backAction, SIGNAL(activated()), SLOT(goBack()));
       backAction->setEnabled(FALSE);
     QAction *quitAction = new QAction("Quit", "&Quit", CTRL+Key_Q, this);
       connect(quitAction, SIGNAL(activated()), SLOT(close()));
     QAction *loadAction = new QAction("Load", QPixmap(xpm_load), "&Load", CTRL+Key_L, this);
       connect(loadAction, SIGNAL(activated()), SLOT(loadConfig()));
     QAction *saveAction = new QAction("Save", QPixmap(xpm_save), "&Save", CTRL+Key_S, this);
       connect(saveAction, SIGNAL(activated()), SLOT(saveConfig()));
     QAction *saveAsAction = new QAction("Save As...", "Save &As...", 0, this);
       connect(saveAsAction, SIGNAL(activated()), SLOT(saveConfigAs()));
     QAction *singleViewAction = new QAction("Single View", QPixmap(xpm_single_view), "Split View", 0, this);
       connect(singleViewAction, SIGNAL(activated()), SLOT(showSingleView()));
     QAction *splitViewAction = new QAction("Split View", QPixmap(xpm_split_view), "Split View", 0, this);
       connect(splitViewAction, SIGNAL(activated()), SLOT(showSplitView()));
     QAction *fullViewAction = new QAction("Full View", QPixmap(xpm_tree_view), "Full View", 0, this);
       connect(fullViewAction, SIGNAL(activated()), SLOT(showFullView()));
     QAction *showNameAction = new QAction(NULL, "Show Name", 0, this);
       showNameAction->setToggleAction(TRUE);
       showNameAction->setOn(configList->showName);
       connect(showNameAction, SIGNAL(toggled(bool)), SLOT(setShowName(bool)));
     QAction *showRangeAction = new QAction(NULL, "Show Range", 0, this);
       showRangeAction->setToggleAction(TRUE);
       showRangeAction->setOn(configList->showRange);
       connect(showRangeAction, SIGNAL(toggled(bool)), SLOT(setShowRange(bool)));
     QAction *showDataAction = new QAction(NULL, "Show Data", 0, this);
       showDataAction->setToggleAction(TRUE);
       showDataAction->setOn(configList->showData);
       connect(showDataAction, SIGNAL(toggled(bool)), SLOT(setShowData(bool)));
     QAction *showAllAction = new QAction(NULL, "Show All Options", 0, this);
       showAllAction->setToggleAction(TRUE);
       showAllAction->setOn(configList->showAll);
       connect(showAllAction, SIGNAL(toggled(bool)), SLOT(setShowAll(bool)));
     QAction *showDebugAction = new QAction(NULL, "Show Debug Info", 0, this);
       showDebugAction->setToggleAction(TRUE);
       showDebugAction->setOn(showDebug);
       connect(showDebugAction, SIGNAL(toggled(bool)), SLOT(setShowDebug(bool)));
     QAction *showIntroAction = new QAction(NULL, "Introduction", 0, this);
       connect(showIntroAction, SIGNAL(activated()), SLOT(showIntro()));
     QAction *showAboutAction = new QAction(NULL, "About", 0, this);
       connect(showAboutAction, SIGNAL(activated()), SLOT(showAbout()));
     // init tool bar
     backAction->addTo(toolBar);
     toolBar->addSeparator();
     loadAction->addTo(toolBar);
     saveAction->addTo(toolBar);
     toolBar->addSeparator();
     singleViewAction->addTo(toolBar);
     splitViewAction->addTo(toolBar);
     fullViewAction->addTo(toolBar);
     // create config menu
     QPopupMenu* config = new QPopupMenu(this);
     menu->insertItem("&File", config);
     loadAction->addTo(config);
     saveAction->addTo(config);
     saveAsAction->addTo(config);
     config->insertSeparator();
     quitAction->addTo(config);
     // create options menu
     QPopupMenu* optionMenu = new QPopupMenu(this);
     menu->insertItem("&Option", optionMenu);
     showNameAction->addTo(optionMenu);
     showRangeAction->addTo(optionMenu);
     showDataAction->addTo(optionMenu);
     optionMenu->insertSeparator();
     showAllAction->addTo(optionMenu);
     showDebugAction->addTo(optionMenu);
     // create help menu
     QPopupMenu* helpMenu = new QPopupMenu(this);
     menu->insertSeparator();
     menu->insertItem("&Help", helpMenu);
     showIntroAction->addTo(helpMenu);
     showAboutAction->addTo(helpMenu);
     connect(configList, SIGNAL(menuSelected(struct menu *)),
         SLOT(changeMenu(struct menu *)));
     connect(configList, SIGNAL(parentSelected()),
         SLOT(goBack()));
     connect(menuList, SIGNAL(menuSelected(struct menu *)),
         SLOT(changeMenu(struct menu *)));
     connect(configList, SIGNAL(gotFocus(void)),
         SLOT(listFocusChanged(void)));
     connect(menuList, SIGNAL(gotFocus(void)),
         SLOT(listFocusChanged(void)));
 #if QT_VERSION >= 300
     QString listMode = configSettings->readEntry("/kconfig/qconf/listMode", "symbol");
     if (listMode == "single")
         showSingleView();
     else if (listMode == "full")
         showFullView();
     else /*if (listMode == "split")*/
         showSplitView();
     // UI setup done, restore splitter positions
     QValueList<int> sizes = configSettings->readSizes("/kconfig/qconf/split1", &ok);
     if (ok)
         split1->setSizes(sizes);
     sizes = configSettings->readSizes("/kconfig/qconf/split2", &ok);
     if (ok)
         split2->setSizes(sizes);
 #else
     showSplitView();
 #endif
     delete configSettings;
 }
References backAction, changeMenu(), close(), configApp, configList, configView, connect(), CTRL, FALSE, goBack(), height(), helpText, ConfigView::list, listFocusChanged(), loadConfig(), menuList, menuView, NULL, ok, resize(), saveConfig(), saveConfigAs(), setShowAll(), setShowData(), setShowDebug(), setShowName(), setShowRange(), showAbout(), ConfigList::showAll, ConfigList::showData, showDebug, showFullView(), showIntro(), ConfigList::showName, ConfigList::showRange, showSingleView(), showSplitView(), split1, split2, toolBar, TRUE, width, x, xpm_back, xpm_load, xpm_save, xpm_single_view, xpm_split_view, xpm_tree_view, and y.
Member Function Documentation
changeMenu
void ConfigMainWindow::changeMenu (struct menu * menu) slot
Definition at line 1150 of file qconf.cc.
 {
     configList->setRootMenu(menu);
     backAction->setEnabled(TRUE);
 }
References backAction, configList, ConfigList::setRootMenu(), and TRUE.
Referenced by ConfigMainWindow().
closeEvent()
void ConfigMainWindow::closeEvent (QCloseEvent * e) protected
Definition at line 1277 of file qconf.cc.
 {
     if (!sym_change_count) {
         e->accept();
         return;
     }
     QMessageBox mb("qconf", "Save configuration?", QMessageBox::Warning,
             QMessageBox::Yes | QMessageBox::Default, QMessageBox::No, QMessageBox::Cancel | QMessageBox::Escape);
     mb.setButtonText(QMessageBox::Yes, "&Save Changes");
     mb.setButtonText(QMessageBox::No, "&Discard Changes");
     mb.setButtonText(QMessageBox::Cancel, "Cancel Exit");
     switch (mb.exec()) {
     case QMessageBox::Yes:
         conf_write(NULL);
     case QMessageBox::No:
         e->accept();
         break;
     case QMessageBox::Cancel:
         e->ignore();
         break;
     }
 }
References conf_write(), NULL, and sym_change_count.
goBack
void ConfigMainWindow::goBack (void) slot
Definition at line 1167 of file qconf.cc.
 {
     ConfigItem* item;
     configList->setParentMenu();
     if (configList->rootEntry == &rootmenu)
         backAction->setEnabled(FALSE);
     item = (ConfigItem*)menuList->selectedItem();
     while (item) {
         if (item->menu == configList->rootEntry) {
             menuList->setSelected(item, TRUE);
             break;
         }
         item = (ConfigItem*)item->parent();
     }
 }
References backAction, configList, FALSE, ConfigItem::menu, menuList, ConfigList::rootEntry, rootmenu, ConfigList::setParentMenu(), and TRUE.
Referenced by ConfigMainWindow().
listFocusChanged
void ConfigMainWindow::listFocusChanged (void) slot
Definition at line 1156 of file qconf.cc.
 {
     if (menuList->hasFocus()) {
         if (menuList->mode == menuMode)
             configList->clearSelection();
         setHelp(menuList->selectedItem());
     } else if (configList->hasFocus()) {
         setHelp(configList->selectedItem());
     }
 }
References configList, menuList, menuMode, ConfigList::mode, and setHelp().
Referenced by ConfigMainWindow().
loadConfig
void ConfigMainWindow::loadConfig (void) slot
Definition at line 1125 of file qconf.cc.
 {
     QString s = QFileDialog::getOpenFileName(".config", NULL, this);
     if (s.isNull())
         return;
     if (conf_read(QFile::encodeName(s)))
         QMessageBox::information(this, "qconf", "Unable to load configuration!");
     ConfigView::updateListAll();
 }
References conf_read(), NULL, s, and ConfigView::updateListAll().
Referenced by ConfigMainWindow().
saveConfig
void ConfigMainWindow::saveConfig (void) slot
Definition at line 1135 of file qconf.cc.
 {
     if (conf_write(NULL))
         QMessageBox::information(this, "qconf", "Unable to save configuration!");
 }
References conf_write(), and NULL.
Referenced by ConfigMainWindow().
saveConfigAs
void ConfigMainWindow::saveConfigAs (void) slot
Definition at line 1141 of file qconf.cc.
 {
     QString s = QFileDialog::getSaveFileName(".config", NULL, this);
     if (s.isNull())
         return;
     if (conf_write(QFile::encodeName(s)))
         QMessageBox::information(this, "qconf", "Unable to save configuration!");
 }
References conf_write(), NULL, and s.
Referenced by ConfigMainWindow().
saveSettings
void ConfigMainWindow::saveSettings (void) slot
Definition at line 1324 of file qconf.cc.
 {
 #if QT_VERSION >= 300
     ConfigSettings *configSettings = new ConfigSettings;
     configSettings->writeEntry("/kconfig/qconf/window x", pos().x());
     configSettings->writeEntry("/kconfig/qconf/window y", pos().y());
     configSettings->writeEntry("/kconfig/qconf/window width", size().width());
     configSettings->writeEntry("/kconfig/qconf/window height", size().height());
     configSettings->writeEntry("/kconfig/qconf/showName", configList->showName);
     configSettings->writeEntry("/kconfig/qconf/showRange", configList->showRange);
     configSettings->writeEntry("/kconfig/qconf/showData", configList->showData);
     configSettings->writeEntry("/kconfig/qconf/showAll", configList->showAll);
     configSettings->writeEntry("/kconfig/qconf/showDebug", showDebug);
     QString entry;
     switch(configList->mode) {
     case singleMode :
         entry = "single";
         break;
     case symbolMode :
         entry = "split";
         break;
     case fullMode :
         entry = "full";
         break;
     }
     configSettings->writeEntry("/kconfig/qconf/listMode", entry);
     configSettings->writeSizes("/kconfig/qconf/split1", split1->sizes());
     configSettings->writeSizes("/kconfig/qconf/split2", split2->sizes());
     delete configSettings;
 #endif
 }
References configList, fullMode, height(), ConfigList::mode, pos, ConfigList::showAll, ConfigList::showData, showDebug, ConfigList::showName, ConfigList::showRange, singleMode, size, split1, split2, symbolMode, width, x, and y.
setHelp
void ConfigMainWindow::setHelp (QListViewItem * item) slot
Definition at line 1019 of file qconf.cc.
 {
     struct symbol* sym;
     struct menu* menu = 0;
     configList->parent()->lineEdit->hide();
     if (item)
         menu = ((ConfigItem*)item)->menu;
     if (!menu) {
         helpText->setText(QString::null);
         return;
     }
     QString head, debug, help;
     menu = ((ConfigItem*)item)->menu;
     sym = menu->sym;
     if (sym) {
         if (menu->prompt) {
             head += "<big><b>";
             head += print_filter(_(menu->prompt->text));
             head += "</b></big>";
             if (sym->name) {
                 head += " (";
                 head += print_filter(_(sym->name));
                 head += ")";
             }
         } else if (sym->name) {
             head += "<big><b>";
             head += print_filter(_(sym->name));
             head += "</b></big>";
         }
         head += "<br><br>";
         if (showDebug) {
             debug += "type: ";
             debug += print_filter(sym_type_name(sym->type));
             if (sym_is_choice(sym))
                 debug += " (choice)";
             debug += "<br>";
             if (sym->rev_dep.expr) {
                 debug += "reverse dep: ";
                 expr_print(sym->rev_dep.expr, expr_print_help, &debug, E_NONE);
                 debug += "<br>";
             }
             for (struct property *prop = sym->prop; prop; prop = prop->next) {
                 switch (prop->type) {
                 case P_PROMPT:
                 case P_MENU:
                     debug += "prompt: ";
                     debug += print_filter(_(prop->text));
                     debug += "<br>";
                     break;
                 case P_DEFAULT:
                     debug += "default: ";
                     expr_print(prop->expr, expr_print_help, &debug, E_NONE);
                     debug += "<br>";
                     break;
                 case P_CHOICE:
                     if (sym_is_choice(sym)) {
                         debug += "choice: ";
                         expr_print(prop->expr, expr_print_help, &debug, E_NONE);
                         debug += "<br>";
                     }
                     break;
                 case P_SELECT:
                     debug += "select: ";
                     expr_print(prop->expr, expr_print_help, &debug, E_NONE);
                     debug += "<br>";
                     break;
                 case P_RANGE:
                     debug += "range: ";
                     expr_print(prop->expr, expr_print_help, &debug, E_NONE);
                     debug += "<br>";
                     break;
                 default:
                     debug += "unknown property: ";
                     debug += prop_get_type_name(prop->type);
                     debug += "<br>";
                 }
                 if (prop->visible.expr) {
                     debug += "&nbsp;&nbsp;&nbsp;&nbsp;dep: ";
                     expr_print(prop->visible.expr, expr_print_help, &debug, E_NONE);
                     debug += "<br>";
                 }
             }
             debug += "<br>";
         }
         help = print_filter(_(sym->help));
     } else if (menu->prompt) {
         head += "<big><b>";
         head += print_filter(_(menu->prompt->text));
         head += "</b></big><br><br>";
         if (showDebug) {
             if (menu->prompt->visible.expr) {
                 debug += "&nbsp;&nbsp;dep: ";
                 expr_print(menu->prompt->visible.expr, expr_print_help, &debug, E_NONE);
                 debug += "<br><br>";
             }
         }
     }
     if (showDebug)
         debug += QString().sprintf("defined at %s:%d<br><br>", menu->file->name, menu->lineno);
     helpText->setText(head + debug + help);
 }
References _, configList, debug, E_NONE, expr_value::expr, expr_print(), expr_print_help(), menu::file, head, symbol::help, helpText, ConfigView::lineEdit, menu::lineno, file::name, symbol::name, property::next, null(), P_CHOICE, P_DEFAULT, P_MENU, P_PROMPT, P_RANGE, P_SELECT, ConfigList::parent(), print_filter(), menu::prompt, symbol::prop, prop_get_type_name(), symbol::rev_dep, showDebug, menu::sym, sym_is_choice(), sym_type_name(), property::text, symbol::type, and property::visible.
Referenced by listFocusChanged(), and ConfigList::updateSelection().
setShowAll
void ConfigMainWindow::setShowAll (bool b) slot
Definition at line 1226 of file qconf.cc.
 {
     if (configList->showAll == b)
         return;
     configList->showAll = b;
     configList->updateListAll();
     menuList->showAll = b;
     menuList->updateListAll();
 }
References configList, menuList, ConfigList::showAll, and ConfigList::updateListAll().
Referenced by ConfigMainWindow().
setShowData
void ConfigMainWindow::setShowData (bool b) slot
Definition at line 1263 of file qconf.cc.
 {
     if (configList->showData == b)
         return;
     configList->showData = b;
     configList->reinit();
     menuList->showData = b;
     menuList->reinit();
 }
References configList, menuList, ConfigList::reinit(), and ConfigList::showData.
Referenced by ConfigMainWindow().
setShowDebug
void ConfigMainWindow::setShowDebug (bool b) slot
Definition at line 1236 of file qconf.cc.
 {
     if (showDebug == b)
         return;
     showDebug = b;
 }
References showDebug.
Referenced by ConfigMainWindow().
setShowName
void ConfigMainWindow::setShowName (bool b) slot
Definition at line 1243 of file qconf.cc.
 {
     if (configList->showName == b)
         return;
     configList->showName = b;
     configList->reinit();
     menuList->showName = b;
     menuList->reinit();
 }
References configList, menuList, ConfigList::reinit(), and ConfigList::showName.
Referenced by ConfigMainWindow().
setShowRange
void ConfigMainWindow::setShowRange (bool b) slot
Definition at line 1253 of file qconf.cc.
 {
     if (configList->showRange == b)
         return;
     configList->showRange = b;
     configList->reinit();
     menuList->showRange = b;
     menuList->reinit();
 }
References configList, menuList, ConfigList::reinit(), and ConfigList::showRange.
Referenced by ConfigMainWindow().
showAbout
void ConfigMainWindow::showAbout (void) slot
Definition at line 1317 of file qconf.cc.
 {
     static char str[] = "qconf is Copyright (C) 2002 Roman Zippel <zippel@linux-m68k.org>.\n";
     QMessageBox::information(this, "qconf", str);
 }
References str.
Referenced by ConfigMainWindow().
showFullView
void ConfigMainWindow::showFullView (void) slot
Definition at line 1213 of file qconf.cc.
 {
     menuView->hide();
     menuList->setRootMenu(0);
     configList->mode = fullMode;
     if (configList->rootEntry == &rootmenu)
         configList->updateListAll();
     else
         configList->setRootMenu(&rootmenu);
     configList->setAllOpen(FALSE);
     configList->setFocus();
 }
References configList, FALSE, fullMode, menuList, menuView, ConfigList::mode, ConfigList::rootEntry, rootmenu, ConfigList::setAllOpen(), ConfigList::setRootMenu(), and ConfigList::updateListAll().
Referenced by ConfigMainWindow().
showIntro
void ConfigMainWindow::showIntro (void) slot
Definition at line 1300 of file qconf.cc.
 {
     static char str[] = "Welcome to the qconf graphical configuration tool.\n\n"
         "For each option, a blank box indicates the feature is disabled, a check\n"
         "indicates it is enabled, and a dot indicates that it is to be compiled\n"
         "as a module.  Clicking on the box will cycle through the three states.\n\n"
         "If you do not see an option (e.g., a device driver) that you believe\n"
         "should be present, try turning on Show All Options under the Options menu.\n"
         "Although there is no cross reference yet to help you figure out what other\n"
         "options must be enabled to support the option you are interested in, you can\n"
         "still view the help of a grayed-out option.\n\n"
         "Toggling Show Debug Info under the Options menu will show the dependencies,\n"
         "which you can then match by examining other options.\n\n";
     QMessageBox::information(this, "qconf", str);
 }
References str.
Referenced by ConfigMainWindow().
showSingleView
void ConfigMainWindow::showSingleView (void) slot
Definition at line 1184 of file qconf.cc.
 {
     menuView->hide();
     menuList->setRootMenu(0);
     configList->mode = singleMode;
     if (configList->rootEntry == &rootmenu)
         configList->updateListAll();
     else
         configList->setRootMenu(&rootmenu);
     configList->setAllOpen(TRUE);
     configList->setFocus();
 }
References configList, menuList, menuView, ConfigList::mode, ConfigList::rootEntry, rootmenu, ConfigList::setAllOpen(), ConfigList::setRootMenu(), singleMode, TRUE, and ConfigList::updateListAll().
Referenced by ConfigMainWindow().
showSplitView
void ConfigMainWindow::showSplitView (void) slot
Definition at line 1197 of file qconf.cc.
 {
     configList->mode = symbolMode;
     if (configList->rootEntry == &rootmenu)
         configList->updateListAll();
     else
         configList->setRootMenu(&rootmenu);
     configList->setAllOpen(TRUE);
     configApp->processEvents();
     menuList->mode = menuMode;
     menuList->setRootMenu(&rootmenu);
     menuList->setAllOpen(TRUE);
     menuView->show();
     menuList->setFocus();
 }
References configApp, configList, menuList, menuMode, menuView, ConfigList::mode, ConfigList::rootEntry, rootmenu, ConfigList::setAllOpen(), ConfigList::setRootMenu(), symbolMode, TRUE, and ConfigList::updateListAll().
Referenced by ConfigMainWindow().
Field Documentation
backAction
QAction* ConfigMainWindow::backAction protected
Definition at line 258 of file qconf.h.
Referenced by changeMenu(), ConfigMainWindow(), and goBack().
configList
ConfigList* ConfigMainWindow::configList protected
Definition at line 255 of file qconf.h.
Referenced by changeMenu(), ConfigMainWindow(), goBack(), listFocusChanged(), saveSettings(), setHelp(), setShowAll(), setShowData(), setShowName(), setShowRange(), showFullView(), showSingleView(), and showSplitView().
configView
ConfigView* ConfigMainWindow::configView protected
Definition at line 254 of file qconf.h.
Referenced by ConfigMainWindow().
helpText
QTextView* ConfigMainWindow::helpText protected
Definition at line 256 of file qconf.h.
Referenced by ConfigMainWindow(), and setHelp().
menuList
ConfigList* ConfigMainWindow::menuList protected
Definition at line 253 of file qconf.h.
Referenced by ConfigMainWindow(), goBack(), listFocusChanged(), setShowAll(), setShowData(), setShowName(), setShowRange(), showFullView(), showSingleView(), and showSplitView().
menuView
ConfigView* ConfigMainWindow::menuView protected
Definition at line 252 of file qconf.h.
Referenced by ConfigMainWindow(), showFullView(), showSingleView(), and showSplitView().
showDebug
bool ConfigMainWindow::showDebug protected
Definition at line 262 of file qconf.h.
Referenced by ConfigMainWindow(), saveSettings(), setHelp(), and setShowDebug().
split1
QSplitter* ConfigMainWindow::split1 protected
Definition at line 259 of file qconf.h.
Referenced by ConfigMainWindow(), and saveSettings().
split2
QSplitter* ConfigMainWindow::split2 protected
Definition at line 260 of file qconf.h.
Referenced by ConfigMainWindow(), and saveSettings().
toolBar
QToolBar* ConfigMainWindow::toolBar protected
Definition at line 257 of file qconf.h.
Referenced by ConfigMainWindow().
The documentation for this class was generated from the following files:
Userspace/apps/base/busybox/scripts/kconfig/qconf.h
Userspace/apps/base/busybox/scripts/kconfig/qconf.cc