Fennix Userspace: Userspace/musl/src/include/unistd.h File Reference
unistd.h File Reference
#include "../../include/unistd.h"
Functions
hidden int __dup3 (int, int, int)
hidden int __mkostemps (char *, int, int)
hidden int __execvpe (const char *, char *const *, char *const *)
hidden off_t __lseek (int, off_t, int)
Variables
char ** __environ
Function Documentation
__dup3()
hidden int __dup3 (int old, int new, int flags)
Definition at line 7 of file dup3.c.
 {
     int r;
 #ifdef SYS_dup2
     if (old==new) return __syscall_ret(-EINVAL);
     if (flags) {
         while ((r=__syscall(SYS_dup3, old, new, flags))==-EBUSY);
         if (r!=-ENOSYS) return __syscall_ret(r);
         if (flags & ~O_CLOEXEC) return __syscall_ret(-EINVAL);
     }
     while ((r=__syscall(SYS_dup2, old, new))==-EBUSY);
     if (r >= 0 && (flags & O_CLOEXEC))
         __syscall(SYS_fcntl, new, F_SETFD, FD_CLOEXEC);
 #else
     while ((r=__syscall(SYS_dup3, old, new, flags))==-EBUSY);
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), EBUSY, EINVAL, ENOSYS, F_SETFD, FD_CLOEXEC, flags, O_CLOEXEC, and r.
Referenced by freopen().
__execvpe()
hidden int __execvpe (const char * , char *const * , char *const *)
Referenced by posix_spawnp().
__lseek()
hidden off_t __lseek (int fd, off_t offset, int whence)
Definition at line 4 of file lseek.c.
 {
 #ifdef SYS__llseek
     off_t result;
     return syscall(SYS__llseek, fd, offset>>32, offset, &result, whence) ? -1 : result;
 #else
     return syscall(SYS_lseek, fd, offset, whence);
 #endif
 }
References __asm__(), __syscall_ret(), offset, r2, r4, r5, r6, ret, syscall(), SYSCALL_CLOBBERLIST, and mlibc::whence.
Referenced by __stdio_seek().
__mkostemps()
hidden int __mkostemps (char * template, int len, int flags)
Definition at line 8 of file mkostemps.c.
 {
     size_t l = strlen(template);
     if (l<6 || len>l-6 || memcmp(template+l-len-6, "XXXXXX", 6)) {
         errno = EINVAL;
         return -1;
     }
     flags -= flags & O_ACCMODE;
     int fd, retries = 100;
     do {
         __randname(template+l-len-6);
         if ((fd = open(template, flags | O_RDWR | O_CREAT | O_EXCL, 0600))>=0)
             return fd;
     } while (--retries && errno == EEXIST);
     memcpy(template+l-len-6, "XXXXXX", 6);
     return -1;
 }
Variable Documentation
__environ
char** __environ extern
Definition at line 3 of file __environ.c.