Fennix: Userspace/apps/base/busybox/util-linux/volume_id/bcache.c File Reference
bcache.c File Reference
#include "volume_id_internal.h"
Data Structures
struct bcache_super_block
union bcache_super_block.__unnamed1171__
union bcache_super_block.__unnamed1173__
struct bcache_super_block.__unnamed1173__.__unnamed1177__
struct bcache_super_block.__unnamed1173__.__unnamed1179__
union bcache_super_block.__unnamed1175__
Macros
#define SB_LABEL_SIZE 32
#define SB_JOURNAL_BUCKETS 256U
#define BCACHE_SB_MAGIC bcache_magic
#define BCACHE_SB_MAGIC_LEN sizeof (bcache_magic)
#define BCACHE_SB_OFF 0x1000
#define BCACHE_SB_KBOFF (BCACHE_SB_OFF >> 10)
#define BCACHE_SB_MAGIC_OFF offsetof (struct bcache_super_block, magic)
Functions
int FAST_FUNC volume_id_probe_bcache (struct volume_id *id)
Variables
static const char bcache_magic[] ALIGN1
Data Structure Documentation
bcache_super_block
struct bcache_super_block
Definition at line 27 of file bcache.c.
Data Fields
union bcache_super_block __unnamed__
union bcache_super_block __unnamed__
union bcache_super_block __unnamed__
uint64_t csum
uint64_t d[SB_JOURNAL_BUCKETS]
uint16_t first_bucket
uint64_t flags
uint8_t label[SB_LABEL_SIZE]
uint32_t last_mount
uint8_t magic[16]
uint64_t offset
uint64_t pad[8]
uint64_t seq
uint8_t uuid[16]
uint64_t version
bcache_super_block.__unnamed1171__
union bcache_super_block.__unnamed1171__
Definition at line 35 of file bcache.c.
Data Fields
uint64_t set_magic
uint8_t set_uuid[16]
bcache_super_block.__unnamed1173__
union bcache_super_block.__unnamed1173__
Definition at line 45 of file bcache.c.
Data Fields
__unnamed1173__ __unnamed__
__unnamed1173__ __unnamed__
bcache_super_block.__unnamed1173__.__unnamed1177__
struct bcache_super_block.__unnamed1173__.__unnamed1177__
Definition at line 46 of file bcache.c.
Data Fields
uint16_t block_size
uint16_t bucket_size
uint64_t nbuckets
uint16_t nr_in_set
uint16_t nr_this_dev
bcache_super_block.__unnamed1173__.__unnamed1179__
struct bcache_super_block.__unnamed1173__.__unnamed1179__
Definition at line 56 of file bcache.c.
Data Fields
uint64_t data_offset
bcache_super_block.__unnamed1175__
union bcache_super_block.__unnamed1175__
Definition at line 71 of file bcache.c.
Data Fields
uint16_t keys
uint16_t njournal_buckets
Macro Definition Documentation
BCACHE_SB_KBOFF
#define BCACHE_SB_KBOFF (BCACHE_SB_OFF >> 10)
Definition at line 85 of file bcache.c.
BCACHE_SB_MAGIC
#define BCACHE_SB_MAGIC bcache_magic
Definition at line 79 of file bcache.c.
BCACHE_SB_MAGIC_LEN
#define BCACHE_SB_MAGIC_LEN sizeof (bcache_magic)
Definition at line 81 of file bcache.c.
BCACHE_SB_MAGIC_OFF
#define BCACHE_SB_MAGIC_OFF offsetof (struct bcache_super_block, magic)
Definition at line 87 of file bcache.c.
BCACHE_SB_OFF
#define BCACHE_SB_OFF 0x1000
Definition at line 83 of file bcache.c.
SB_JOURNAL_BUCKETS
#define SB_JOURNAL_BUCKETS 256U
Definition at line 20 of file bcache.c.
SB_LABEL_SIZE
#define SB_LABEL_SIZE 32
Definition at line 19 of file bcache.c.
Function Documentation
volume_id_probe_bcache()
int FAST_FUNC volume_id_probe_bcache (struct volume_id * id)
Definition at line 89 of file bcache.c.
 {
     struct bcache_super_block *sb;
     sb = volume_id_get_buffer(id, BCACHE_SB_OFF, sizeof(*sb));
     if (sb == NULL)
         return -1;
     if (memcmp(sb->magic, BCACHE_SB_MAGIC, BCACHE_SB_MAGIC_LEN) != 0)
         return -1;
     volume_id_set_label_string(id, sb->label, SB_LABEL_SIZE);
     volume_id_set_uuid(id, sb->uuid, UUID_DCE);
     IF_FEATURE_BLKID_TYPE(id->type = "bcache";)
     return 0;
 }
References BCACHE_SB_MAGIC, BCACHE_SB_MAGIC_LEN, BCACHE_SB_OFF, bcache_super_block::label, bcache_super_block::magic, memcmp(), NULL, SB_LABEL_SIZE, bcache_super_block::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
Variable Documentation
ALIGN1
const char bcache_magic [] ALIGN1 static
Initial value:
= {
    0xc6, 0x85, 0x73, 0xf6, 0x4e, 0x1a, 0x45, 0xca,
    0x82, 0x65, 0xf5, 0x7f, 0x48, 0xba, 0x6d, 0x81
}
Definition at line 22 of file bcache.c.