Fennix Kernel: Kernel/KernelShell/Commands/kill.cpp File Reference
kill.cpp File Reference
#include "../cmds.hpp"
#include <filesystem.hpp>
#include <task.hpp>
#include "../../kernel.h"
Functions
void cmd_kill (const char *args)
Function Documentation
cmd_kill()
void cmd_kill (const char * args)
Definition at line 28 of file kill.cpp.
 {
     PID pid = atoi(args);
     PCB *pcb = TaskManager->GetProcessByID(pid);
     if (pcb == nullptr)
     {
         printf("No process with PID %d\n", pid);
         return;
     }
     TaskManager->KillProcess(pcb, KILL_BY_OTHER_PROCESS);
 }
References atoi(), Tasking::Task::GetProcessByID(), Tasking::KILL_BY_OTHER_PROCESS, Tasking::Task::KillProcess(), printf, and TaskManager.