Fennix: Userspace/apps/base/busybox/coreutils/md5_sha1_sum.c File Reference
md5_sha1_sum.c File Reference
#include "libbb.h"
Macros
#define FLAG_SILENT 1
#define FLAG_CHECK 2
#define FLAG_WARN 4
#define BUFSZ (CONFIG_FEATURE_COPYBUF_KB < 4 ? 4096 : CONFIG_FEATURE_COPYBUF_KB * 1024)
#define hash_file(b, f, w) hash_file(b,f)
Enumerations
enum {
HASH_MD5 = 's' , HASH_SHA1 = '1' , HASH_SHA256 = '2' , HASH_SHA3 = '3' ,
HASH_SHA512 = '5'
}
Functions
static unsigned char * hash_bin_to_hex (unsigned char *hash_value, unsigned hash_length)
static uint8_t * hash_file (unsigned char *in_buf, const char *filename, unsigned sha3_width)
int md5_sha1_sum_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
BUFSZ
#define BUFSZ (CONFIG_FEATURE_COPYBUF_KB < 4 ? 4096 : CONFIG_FEATURE_COPYBUF_KB * 1024)
Definition at line 154 of file md5_sha1_sum.c.
FLAG_CHECK
#define FLAG_CHECK 2
Definition at line 141 of file md5_sha1_sum.c.
FLAG_SILENT
#define FLAG_SILENT 1
Definition at line 140 of file md5_sha1_sum.c.
FLAG_WARN
#define FLAG_WARN 4
Definition at line 142 of file md5_sha1_sum.c.
hash_file
#define hash_file (b, f, w) hash_file(b,f)
Definition at line 157 of file md5_sha1_sum.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HASH_MD5
HASH_SHA1
HASH_SHA256
HASH_SHA3
HASH_SHA512
Definition at line 131 of file md5_sha1_sum.c.
      {
     /* 4th letter of applet_name is... */
     HASH_MD5 = 's', /* "md5>s<um" */
     HASH_SHA1 = '1',
     HASH_SHA256 = '2',
     HASH_SHA3 = '3',
     HASH_SHA512 = '5',
 };
Function Documentation
hash_bin_to_hex()
static unsigned char* hash_bin_to_hex (unsigned char * hash_value, unsigned hash_length) static
Definition at line 145 of file md5_sha1_sum.c.
 {
     /* xzalloc zero-terminates */
     char *hex_value = xzalloc((hash_length * 2) + 1);
     bin2hex(hex_value, (char*)hash_value, hash_length);
     return (unsigned char *)hex_value;
 }
References bin2hex(), and xzalloc().
Referenced by hash_file().
hash_file()
static uint8_t* hash_file (unsigned char * in_buf, const char * filename, unsigned sha3_width) static
Definition at line 159 of file md5_sha1_sum.c.
 {
     int src_fd, hash_len, count;
     union _ctx_ {
         sha3_ctx_t sha3;
         sha512_ctx_t sha512;
         sha256_ctx_t sha256;
         sha1_ctx_t sha1;
         md5_ctx_t md5;
     } context;
     uint8_t *hash_value;
     void FAST_FUNC (*update)(void*, const void*, size_t);
     unsigned FAST_FUNC (*final)(void*, void*);
     char hash_algo;
     src_fd = open_or_warn_stdin(filename);
     if (src_fd < 0) {
         return NULL;
     }
     hash_algo = applet_name[3];
     /* figure specific hash algorithms */
     if (ENABLE_MD5SUM && hash_algo == HASH_MD5) {
         md5_begin(&context.md5);
         update = (void*)md5_hash;
         final = (void*)md5_end;
         hash_len = 16;
     }
     else if (ENABLE_SHA1SUM && hash_algo == HASH_SHA1) {
         sha1_begin(&context.sha1);
         update = (void*)sha1_hash;
         final = (void*)sha1_end;
         hash_len = 20;
     }
     else if (ENABLE_SHA256SUM && hash_algo == HASH_SHA256) {
         sha256_begin(&context.sha256);
         update = (void*)sha256_hash;
         final = (void*)sha256_end;
         hash_len = 32;
     }
     else if (ENABLE_SHA512SUM && hash_algo == HASH_SHA512) {
         sha512_begin(&context.sha512);
         update = (void*)sha512_hash;
         final = (void*)sha512_end;
         hash_len = 64;
     }
 #if ENABLE_SHA3SUM
     else if (ENABLE_SHA3SUM && hash_algo == HASH_SHA3) {
         sha3_begin(&context.sha3);
         update = (void*)sha3_hash;
         final = (void*)sha3_end;
         /*
          * Should support 224, 256, 384, 512.
          * We allow any value which does not blow the algorithm up.
          */
         if (sha3_width >= 1600/2 /* input block can't be <= 0 */
          || sha3_width == 0      /* hash len can't be 0 */
          || (sha3_width & 0x1f)  /* should be multiple of 32 */
         /* (because input uses up to 8 byte wide word XORs. 32/4=8) */
         ) {
             bb_error_msg_and_die("bad -a%u", sha3_width);
         }
         sha3_width /= 4;
         context.sha3.input_block_bytes = 1600/8 - sha3_width;
         hash_len = sha3_width/2;
     }
 #endif
     else {
         xfunc_die(); /* can't reach this */
     }
     {
         while ((count = safe_read(src_fd, in_buf, BUFSZ)) > 0) {
             update(&context, in_buf, count);
         }
         hash_value = NULL;
         if (count < 0)
             bb_perror_msg("can't read '%s'", filename);
         else /* count == 0 */ {
             final(&context, in_buf);
             hash_value = hash_bin_to_hex(in_buf, hash_len);
         }
     }
     if (src_fd != STDIN_FILENO) {
         close(src_fd);
     }
     return hash_value;
 }
References applet_name, bb_error_msg_and_die(), bb_perror_msg(), BUFSZ, close(), context, count, FAST_FUNC, filename, hash_bin_to_hex(), HASH_MD5, HASH_SHA1, HASH_SHA256, HASH_SHA3, HASH_SHA512, md5_begin(), md5_end(), md5_hash(), NULL, open_or_warn_stdin(), safe_read(), sha1_begin(), sha1_end(), sha1_hash, sha256_begin(), sha256_end, sha256_hash, sha3_begin(), sha3_end(), sha3_hash(), sha512_begin(), sha512_end(), sha512_hash(), STDIN_FILENO, and xfunc_die().
md5_sha1_sum_main()
int md5_sha1_sum_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 252 of file md5_sha1_sum.c.
 {
     unsigned char *in_buf;
     int return_value = EXIT_SUCCESS;
     unsigned flags;
 #if ENABLE_SHA3SUM
     unsigned sha3_width = 224;
 #endif
     if (ENABLE_FEATURE_MD5_SHA1_SUM_CHECK) {
         /* -b "binary", -t "text" are ignored (shaNNNsum compat) */
         /* -s and -w require -c */
 #if ENABLE_SHA3SUM
         if (applet_name[3] == HASH_SHA3)
             flags = getopt32(argv, "^" "scwbta:+" "\0" "s?c:w?c", &sha3_width);
         else
 #endif
             flags = getopt32(argv, "^" "scwbt" "\0" "s?c:w?c");
     } else {
 #if ENABLE_SHA3SUM
         if (applet_name[3] == HASH_SHA3)
             getopt32(argv, "a:+", &sha3_width);
         else
 #endif
             getopt32(argv, "");
     }
     argv += optind;
     //argc -= optind;
     if (!*argv)
         *--argv = (char*)"-";
     /* The buffer is not alloc/freed for each input file:
      * for big values of COPYBUF_KB, this helps to keep its pages
      * pre-faulted and possibly even fully cached on local CPU.
      */
     in_buf = xmalloc(BUFSZ);
     do {
         if (ENABLE_FEATURE_MD5_SHA1_SUM_CHECK && (flags & FLAG_CHECK)) {
             FILE *pre_computed_stream;
             char *line;
             int count_total = 0;
             int count_failed = 0;
             pre_computed_stream = xfopen_stdin(*argv);
             while ((line = xmalloc_fgetline(pre_computed_stream)) != NULL) {
                 uint8_t *hash_value;
                 char *filename_ptr;
                 count_total++;
                 filename_ptr = strchr(line, ' ');
                 if (!filename_ptr) {
                     if (flags & FLAG_WARN) {
                         bb_simple_error_msg("invalid format");
                     }
                     count_failed++;
                     return_value = EXIT_FAILURE;
                     free(line);
                     continue;
                 }
                 *filename_ptr++ = '\0';
                 /* coreutils 9.1 allows "HASH FILENAME" format,
                  * with only one space. Skip the 'correct'
                  * "  " or " *" delimiter if it is there:
                  */
                 if (*filename_ptr == ' ' || *filename_ptr == '*')
                     filename_ptr++;
                 hash_value = hash_file(in_buf, filename_ptr, sha3_width);
                 if (hash_value && (strcmp((char*)hash_value, line) == 0)) {
                     if (!(flags & FLAG_SILENT))
                         printf("%s: OK\n", filename_ptr);
                 } else {
                     if (!(flags & FLAG_SILENT))
                         printf("%s: FAILED\n", filename_ptr);
                     count_failed++;
                     return_value = EXIT_FAILURE;
                 }
                 /* possible free(NULL) */
                 free(hash_value);
                 free(line);
             }
             if (count_failed && !(flags & FLAG_SILENT)) {
                 bb_error_msg("WARNING: %d of %d computed checksums did NOT match",
                         count_failed, count_total);
             }
             if (count_total == 0) {
                 return_value = EXIT_FAILURE;
                 /*
                  * md5sum from GNU coreutils 8.25 says:
                  * md5sum: <FILE>: no properly formatted MD5 checksum lines found
                  */
                 bb_error_msg("%s: no checksum lines found", *argv);
             }
             fclose_if_not_stdin(pre_computed_stream);
         } else {
             uint8_t *hash_value = hash_file(in_buf, *argv, sha3_width);
             if (hash_value == NULL) {
                 return_value = EXIT_FAILURE;
             } else {
                 printf("%s  %s\n", hash_value, *argv);
                 free(hash_value);
             }
         }
     } while (*++argv);
     return return_value;
 }
References applet_name, argv, bb_error_msg(), bb_simple_error_msg(), BUFSZ, EXIT_FAILURE, EXIT_SUCCESS, fclose_if_not_stdin(), FLAG_CHECK, FLAG_SILENT, FLAG_WARN, flags, free, getopt32(), hash_file, HASH_SHA3, line, NULL, optind, printf, strchr(), strcmp, xfopen_stdin(), xmalloc, and xmalloc_fgetline().