Fennix: Userspace/apps/base/busybox/loginutils/login.c File Reference
login.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <syslog.h>
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
#define die_if_nologin() ((void)0)
#define login_pam_end(pamh) ((void)0)
Enumerations
enum { EMPTY_USERNAME_COUNT = 10 , USERNAME_SIZE = 64 , TTYNAME_SIZE = 32 }
Functions
void run_login_script (struct passwd *pw, char *full_tty)
static void get_username_or_die (char *buf, int size_buf)
static void motd (void)
static void alarm_handler (int sig UNUSED_PARAM)
int login_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
die_if_nologin
#define die_if_nologin () ((void)0)
Definition at line 179 of file login.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 148 of file login.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 149 of file login.c.
login_pam_end
#define login_pam_end (pamh) ((void)0)
Definition at line 254 of file login.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMPTY_USERNAME_COUNT
USERNAME_SIZE
TTYNAME_SIZE
Definition at line 137 of file login.c.
      {
     EMPTY_USERNAME_COUNT = 10,
     /* Some users found 32 chars limit to be too low: */
     USERNAME_SIZE = 64,
     TTYNAME_SIZE = 32,
 };
Function Documentation
alarm_handler()
static void alarm_handler (int sig UNUSED_PARAM) static
Definition at line 298 of file login.c.
 {
     /* This is the escape hatch! Poor serial line users and the like
      * arrive here when their connection is broken.
      * We don't want to block here */
     ndelay_on(STDOUT_FILENO);
     /* Test for correct attr restoring:
      * run "getty 0 -" from a shell, enter bogus username, stop at
      * password prompt, let it time out. Without the tcsetattr below,
      * when you are back at shell prompt, echo will be still off.
      */
     tcsetattr_stdin_TCSANOW(&G.tty_attrs);
     printf("\r\nLogin timed out after %u seconds\r\n", G.timeout);
     fflush_all();
     /* unix API is brain damaged regarding O_NONBLOCK,
      * we should undo it, or else we can affect other processes */
     ndelay_off(STDOUT_FILENO);
     _exit_SUCCESS();
 }
References _exit_SUCCESS(), fflush_all(), G, ndelay_off(), ndelay_on(), printf, STDOUT_FILENO, and tcsetattr_stdin_TCSANOW().
Referenced by login_main().
get_username_or_die()
static void get_username_or_die (char * buf, int size_buf) static
Definition at line 257 of file login.c.
 {
     int c, cntdown;
     cntdown = EMPTY_USERNAME_COUNT;
  prompt:
     print_login_prompt();
     /* skip whitespace */
     do {
         c = getchar();
         if (c == EOF)
             exit(EXIT_FAILURE);
         if (c == '\n') {
             if (!--cntdown)
                 exit(EXIT_FAILURE);
             goto prompt;
         }
     } while (isspace(c)); /* maybe isblank? */
     *buf++ = c;
     if (!fgets(buf, size_buf-2, stdin))
         exit(EXIT_FAILURE);
     if (!strchr(buf, '\n'))
         exit(EXIT_FAILURE);
     while ((unsigned char)*buf > ' ')
         buf++;
     *buf = '\0';
 }
References buf, c, EMPTY_USERNAME_COUNT, EOF, exit(), EXIT_FAILURE, fgets, getchar, isspace, print_login_prompt(), prompt, stdin, and strchr().
Referenced by login_main().
login_main()
int login_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 319 of file login.c.
 {
     enum {
         LOGIN_OPT_f = (1<<0),
         LOGIN_OPT_h = (1<<1),
         LOGIN_OPT_p = (1<<2),
     };
     char *fromhost;
     char username[USERNAME_SIZE];
     int run_by_root;
     unsigned opt;
     int count = 0;
     struct passwd *pw;
     char *opt_host = NULL;
     char *opt_user = opt_user; /* for compiler */
     char *full_tty;
     char *short_tty;
     IF_SELINUX(security_context_t user_sid = NULL;)
 #if ENABLE_PAM
     int pamret;
     pam_handle_t *pamh;
     const char *pamuser;
     const char *failed_msg;
     struct passwd pwdstruct;
     char pwdbuf[256];
     char **pamenv;
 #endif
 #if ENABLE_LOGIN_SESSION_AS_CHILD
     pid_t child_pid;
 #endif
     IF_FEATURE_UTMP(pid_t my_pid;)
     INIT_G();
     G.timeout = xatoi_positive(getenv("LOGIN_TIMEOUT") ? : "60");
     /* More of suid paranoia if called by non-root: */
     /* Clear dangerous stuff, set PATH */
     run_by_root = !sanitize_env_if_suid();
     /* Mandatory paranoia for suid applet:
      * ensure that fd# 0,1,2 are opened (at least to /dev/null)
      * and any extra open fd's are closed.
      */
     bb_daemon_helper(DAEMON_CLOSE_EXTRA_FDS);
     username[0] = '\0';
     opt = getopt32(argv, "f:h:p", &opt_user, &opt_host);
     if (opt & LOGIN_OPT_f) {
         if (!run_by_root)
             bb_simple_error_msg_and_die("-f is for root only");
         safe_strncpy(username, opt_user, sizeof(username));
     }
     argv += optind;
     if (argv[0]) /* user from command line (getty) */
         safe_strncpy(username, argv[0], sizeof(username));
     /* Save tty attributes - and by doing it, check that it's indeed a tty */
     if (tcgetattr(STDIN_FILENO, &G.tty_attrs) < 0
      || !isatty(STDOUT_FILENO)
      /*|| !isatty(STDERR_FILENO) - no, guess some people might want to redirect this */
     ) {
         return EXIT_FAILURE;  /* Must be a terminal */
     }
     /* We install timeout handler only _after_ we saved G.tty_attrs */
     signal(SIGALRM, alarm_handler);
     alarm(G.timeout);
     /* Find out and memorize our tty name */
     full_tty = xmalloc_ttyname(STDIN_FILENO);
     if (!full_tty)
         full_tty = xstrdup("UNKNOWN");
     short_tty = skip_dev_pfx(full_tty);
     if (opt_host) {
         fromhost = xasprintf(" on '%s' from '%s'", short_tty, opt_host);
     } else {
         fromhost = xasprintf(" on '%s'", short_tty);
     }
     /* Was breaking "login <username>" from shell command line: */
     /*bb_setpgrp();*/
     openlog(applet_name, LOG_PID | LOG_CONS, LOG_AUTH);
     while (1) {
         /* flush away any type-ahead (as getty does) */
         tcflush(0, TCIFLUSH);
         if (!username[0])
             get_username_or_die(username, sizeof(username));
 #if ENABLE_PAM
         pamret = pam_start("login", username, &conv, &pamh);
         if (pamret != PAM_SUCCESS) {
             failed_msg = "start";
             goto pam_auth_failed;
         }
         /* set TTY (so things like securetty work) */
         pamret = pam_set_item(pamh, PAM_TTY, short_tty);
         if (pamret != PAM_SUCCESS) {
             failed_msg = "set_item(TTY)";
             goto pam_auth_failed;
         }
         /* set RHOST */
         if (opt_host) {
             pamret = pam_set_item(pamh, PAM_RHOST, opt_host);
             if (pamret != PAM_SUCCESS) {
                 failed_msg = "set_item(RHOST)";
                 goto pam_auth_failed;
             }
         }
         if (!(opt & LOGIN_OPT_f)) {
             pamret = pam_authenticate(pamh, 0);
             if (pamret != PAM_SUCCESS) {
                 failed_msg = "authenticate";
                 goto pam_auth_failed;
                 /* TODO: or just "goto auth_failed"
                  * since user seems to enter wrong password
                  * (in this case pamret == 7)
                  */
             }
         }
         /* check that the account is healthy */
         pamret = pam_acct_mgmt(pamh, 0);
         if (pamret == PAM_NEW_AUTHTOK_REQD) {
             pamret = pam_chauthtok(pamh, PAM_CHANGE_EXPIRED_AUTHTOK);
         }
         if (pamret != PAM_SUCCESS) {
             failed_msg = "acct_mgmt";
             goto pam_auth_failed;
         }
         /* read user back */
         pamuser = NULL;
         /* gcc: "dereferencing type-punned pointer breaks aliasing rules..."
          * thus we cast to (void*) */
         if (pam_get_item(pamh, PAM_USER, (void*)&pamuser) != PAM_SUCCESS) {
             failed_msg = "get_item(USER)";
             goto pam_auth_failed;
         }
         if (!pamuser || !pamuser[0])
             goto auth_failed;
         safe_strncpy(username, pamuser, sizeof(username));
         /* Don't use "pw = getpwnam(username);",
          * PAM is said to be capable of destroying static storage
          * used by getpwnam(). We are using safe(r) function */
         pw = NULL;
         getpwnam_r(username, &pwdstruct, pwdbuf, sizeof(pwdbuf), &pw);
         if (!pw)
             goto auth_failed;
         pamret = pam_open_session(pamh, 0);
         if (pamret != PAM_SUCCESS) {
             failed_msg = "open_session";
             goto pam_auth_failed;
         }
         pamret = pam_setcred(pamh, PAM_ESTABLISH_CRED);
         if (pamret != PAM_SUCCESS) {
             failed_msg = "setcred";
             goto pam_auth_failed;
         }
         break; /* success, continue login process */
  pam_auth_failed:
         /* syslog, because we don't want potential attacker
          * to know _why_ login failed */
         syslog(LOG_WARNING, "pam_%s call failed: %s (%d)", failed_msg,
                     pam_strerror(pamh, pamret), pamret);
         login_pam_end(pamh);
         safe_strncpy(username, "UNKNOWN", sizeof(username));
 #else /* not PAM */
         pw = getpwnam(username);
         if (!pw) {
             strcpy(username, "UNKNOWN");
             goto fake_it;
         }
         if (pw->pw_passwd[0] == '!' || pw->pw_passwd[0] == '*')
             goto auth_failed;
         if (opt & LOGIN_OPT_f)
             break; /* -f USER: success without asking passwd */
         if (pw->pw_uid == 0 && !is_tty_secure(short_tty))
             goto auth_failed;
         /* Don't check the password if password entry is empty (!) */
         if (!pw->pw_passwd[0])
             break;
  fake_it:
         /* Password reading and authorization takes place here.
          * Note that reads (in no-echo mode) trash tty attributes.
          * If we get interrupted by SIGALRM, we need to restore attrs.
          */
         if (ask_and_check_password(pw) > 0)
             break;
 #endif /* ENABLE_PAM */
  auth_failed:
         opt &= ~LOGIN_OPT_f;
         pause_after_failed_login();
         /* TODO: doesn't sound like correct English phrase to me */
         puts("Login incorrect");
         syslog(LOG_WARNING, "invalid password for '%s'%s",
                     username, fromhost);
         if (++count == 3) {
             if (ENABLE_FEATURE_CLEAN_UP)
                 free(fromhost);
             return EXIT_FAILURE;
         }
         username[0] = '\0';
     } /* while (1) */
     alarm(0);
     /* We can ignore /etc/nologin if we are logging in as root,
      * it doesn't matter whether we are run by root or not */
     if (pw->pw_uid != 0)
         die_if_nologin();
     IF_FEATURE_UTMP(my_pid = getpid();)
     update_utmp(my_pid, USER_PROCESS, short_tty, username, run_by_root ? opt_host : NULL);
 #if ENABLE_LOGIN_SESSION_AS_CHILD
     child_pid = vfork();
     if (child_pid != 0) {
         if (child_pid < 0)
             bb_simple_perror_msg("vfork");
         else {
             wait_for_exitstatus(child_pid);
         }
         update_utmp_DEAD_PROCESS(my_pid);
         login_pam_end(pamh);
         return 0;
     }
 #endif
     IF_SELINUX(initselinux(username, full_tty, &user_sid);)
     /* Try these, but don't complain if they fail.
      * _f_chown is safe wrt race t=ttyname(0);...;chown(t); */
     fchown(0, pw->pw_uid, pw->pw_gid);
     fchmod(0, 0600);
     /* We trust environment only if we run by root */
     if (ENABLE_LOGIN_SCRIPTS && run_by_root)
         run_login_script(pw, full_tty);
     change_identity(pw);
     setup_environment(pw->pw_shell,
             (!(opt & LOGIN_OPT_p) * SETUP_ENV_CLEARENV)
                 + SETUP_ENV_CHANGEENV
                 + SETUP_ENV_CHDIR,
             pw);
 #if ENABLE_PAM
     /* Modules such as pam_env will setup the PAM environment,
      * which should be copied into the new environment. */
     pamenv = pam_getenvlist(pamh);
     if (pamenv) while (*pamenv) {
         putenv(*pamenv);
         pamenv++;
     }
 #endif
     if (access(".hushlogin", F_OK) != 0)
         motd();
     if (pw->pw_uid == 0)
         syslog(LOG_INFO, "root login%s", fromhost);
     if (ENABLE_FEATURE_CLEAN_UP)
         free(fromhost);
     /* well, a simple setexeccon() here would do the job as well,
      * but let's play the game for now */
     IF_SELINUX(set_current_security_context(user_sid);)
     // util-linux login also does:
     // /* start new session */
     // setsid();
     // /* TIOCSCTTY: steal tty from other process group */
     // if (ioctl(0, TIOCSCTTY, 1)) error_msg...
     // BBox login used to do this (see above):
     // bb_setpgrp();
     // If this stuff is really needed, add it and explain why!
     /* Set signals to defaults */
     /* Non-ignored signals revert to SIG_DFL on exec anyway */
     /*signal(SIGALRM, SIG_DFL);*/
     /* Is this correct? This way user can ctrl-c out of /etc/profile,
      * potentially creating security breach (tested with bash 3.0).
      * But without this, bash 3.0 will not enable ctrl-c either.
      * Maybe bash is buggy?
      * Need to find out what standards say about /bin/login -
      * should we leave SIGINT etc enabled or disabled?
      * Also note: sulogin does not do it! Why?
      */
     signal(SIGINT, SIG_DFL);
     /* Exec login shell with no additional parameters */
     exec_login_shell(pw->pw_shell);
     /* return EXIT_FAILURE; - not reached */
 }
References access(), alarm(), alarm_handler(), applet_name, argv, ask_and_check_password(), bb_daemon_helper, bb_simple_error_msg_and_die(), bb_simple_perror_msg(), change_identity(), count, DAEMON_CLOSE_EXTRA_FDS, die_if_nologin, exec_login_shell(), EXIT_FAILURE, F_OK, fchmod(), fchown(), free, G, get_username_or_die(), getenv, getopt32(), getpid(), getpwnam, getpwnam_r, INIT_G, is_tty_secure(), isatty(), LOG_AUTH, LOG_CONS, LOG_INFO, LOG_PID, LOG_WARNING, login_pam_end, motd(), NULL, openlog(), opt, optind, pause_after_failed_login(), putenv(), puts(), pw, passwd::pw_gid, passwd::pw_passwd, passwd::pw_shell, passwd::pw_uid, run_login_script(), safe_strncpy(), sanitize_env_if_suid(), SETUP_ENV_CHANGEENV, SETUP_ENV_CHDIR, SETUP_ENV_CLEARENV, setup_environment(), SIG_DFL, SIGALRM, SIGINT, signal, skip_dev_pfx(), STDIN_FILENO, STDOUT_FILENO, strcpy, syslog(), tcflush(), tcgetattr(), TCIFLUSH, update_utmp(), update_utmp_DEAD_PROCESS(), USER_PROCESS, USERNAME_SIZE, vfork(), wait_for_exitstatus(), xasprintf(), xatoi_positive(), xmalloc_ttyname(), and xstrdup().
motd()
static void motd (void) static
Definition at line 286 of file login.c.
 {
     int fd;
     fd = open(bb_path_motd_file, O_RDONLY);
     if (fd >= 0) {
         fflush_all();
         bb_copyfd_eof(fd, STDOUT_FILENO);
         close(fd);
     }
 }
References bb_copyfd_eof(), bb_path_motd_file, close(), fd, fflush_all(), O_RDONLY, open(), and STDOUT_FILENO.
Referenced by login_main().
run_login_script()
void run_login_script (struct passwd * pw, char * full_tty)
Referenced by login_main().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING