Fennix: Userspace/musl/src/signal/sighold.c File Reference
sighold.c File Reference
#include <signal.h>
Functions
int sighold (int sig)
Function Documentation
sighold()
int sighold (int sig)
Definition at line 3 of file sighold.c.
 {
     sigset_t mask;
     sigemptyset(&mask);
     if (sigaddset(&mask, sig) < 0) return -1;
     return sigprocmask(SIG_BLOCK, &mask, 0);
 }
References SIG_BLOCK, sigaddset(), sigemptyset(), and sigprocmask().