Fennix: Userspace/mlibc/options/rtdl/generic/linker.cpp File Reference
linker.cpp File Reference
#include <elf.h>
#include <string.h>
#include <frg/manual_box.hpp>
#include <mlibc/allocator.hpp>
#include <mlibc/debug.hpp>
#include <mlibc/rtdl-sysdeps.hpp>
#include <mlibc/rtdl-abi.hpp>
#include <mlibc/thread.hpp>
#include <abi-bits/fcntl.h>
#include <internal-config.h>
#include "linker.hpp"
Functions
void seekOrDie (int fd, int64_t offset)
void readExactlyOrDie (int fd, void *data, size_t length)
void closeOrDie (int fd)
uintptr_t alignUp (uintptr_t address, size_t align)
void processCopyRela (SharedObject *object, Elf64_Rela *reloc)
void processCopyRelocations (SharedObject *object)
void doInitialize (SharedObject *object)
void initTlsObjects (Tcb *tcb, const frg::vector< SharedObject *, MemoryAllocator > &objects, bool checkInitialized)
Tcb * allocateTcb ()
void * accessDtv (SharedObject *object)
void * tryAccessDtv (SharedObject *object)
uint32_t elf64Hash (frg::string_view string)
uint32_t gnuHash (frg::string_view string)
frg::optional< ObjectSymbol > resolveInObject (SharedObject *object, frg::string_view string)
Variables
uintptr_t libraryBase = 0x41000000
constexpr bool verbose = false
constexpr bool stillSlightlyVerbose = false
constexpr bool logBaseAddresses = false
constexpr bool logRpath = false
constexpr bool eagerBinding = true
DebugInterface globalDebugInterface
uintptr_t __stack_chk_guard
size_t tlsMaxAlignment = 16
uint64_t rtsCounter = 2
Function Documentation
accessDtv()
void* accessDtv (SharedObject * object)
Definition at line 927 of file linker.cpp.
{
     Tcb *tcb_ptr = mlibc::get_current_tcb();
     // We might need to reallocate the DTV.
     if(object->tlsIndex >= tcb_ptr->dtvSize) {
         // TODO: need to protect runtimeTlsMap against concurrent access.
         auto ndtv = frg::construct_n<void *>(getAllocator(), runtimeTlsMap->indices.size());
         memset(ndtv, 0, sizeof(void *) * runtimeTlsMap->indices.size());
         memcpy(ndtv, tcb_ptr->dtvPointers, sizeof(void *) * tcb_ptr->dtvSize);
         frg::destruct_n(getAllocator(), tcb_ptr->dtvPointers, tcb_ptr->dtvSize);
         tcb_ptr->dtvSize = runtimeTlsMap->indices.size();
         tcb_ptr->dtvPointers = ndtv;
     }
     // We might need to fill in a new DTV entry.
     if(!tcb_ptr->dtvPointers[object->tlsIndex]) {
         __ensure(object->tlsModel == TlsModel::dynamic);
         auto buffer = getAllocator().allocate(object->tlsSegmentSize);
         __ensure(!(reinterpret_cast<uintptr_t>(buffer) & (object->tlsAlignment - 1)));
         memset(buffer, 0, object->tlsSegmentSize);
         memcpy(buffer, object->tlsImagePtr, object->tlsImageSize);
         tcb_ptr->dtvPointers[object->tlsIndex] = buffer;
         if (verbose) {
             mlibc::infoLogger() << "rtdl: accessDtv wrote tls image at " << buffer
                     << ", size = 0x" << frg::hex_fmt{object->tlsSegmentSize} << frg::endlog;
         }
     }
     return (void *)((char *)tcb_ptr->dtvPointers[object->tlsIndex] + TLS_DTV_OFFSET);
 }
References __ensure, Tcb::dtvPointers, Tcb::dtvSize, dynamic, mlibc::get_current_tcb(), getAllocator(), mlibc::infoLogger, memcpy, memset, runtimeTlsMap, SharedObject::tlsAlignment, SharedObject::tlsImagePtr, SharedObject::tlsImageSize, SharedObject::tlsIndex, SharedObject::tlsModel, SharedObject::tlsSegmentSize, and verbose.
Referenced by __dlapi_get_tls(), and Loader::_processLazyRelocations().
alignUp()
uintptr_t alignUp (uintptr_t address, size_t align)
Definition at line 79 of file linker.cpp.
{
     return (address + align - 1) & ~(align - 1);
 }
Referenced by allocateTcb().
allocateTcb()
Tcb* allocateTcb ()
Definition at line 864 of file linker.cpp.
                    {
     size_t tlsInitialSize = runtimeTlsMap->initialLimit;
     // To make sure that both the TCB and TLS data are sufficiently aligned, allocate
     // slightly more than necessary and adjust alignment afterwards.
     size_t alignOverhead = frg::min(alignof(Tcb), tlsMaxAlignment);
     size_t allocSize = tlsInitialSize + sizeof(Tcb) + alignOverhead;
     auto allocation = reinterpret_cast<uintptr_t>(getAllocator().allocate(allocSize));
     memset(reinterpret_cast<void *>(allocation), 0, allocSize);
     uintptr_t tlsAddress, tcbAddress;
     if constexpr (tlsAboveTp) {
         // Here we must satisfy two requirements of the TCB and the TLS data:
         //   1. One should follow the other immediately in memory. We do this so that
         //      we can simply add or subtract sizeof(Tcb) to obtain the address of the other.
         //   2. Both should be sufficiently aligned.
         // To do this, we will fix whichever address has stricter alignment requirements, and
         // derive the other from it.
         if (tlsMaxAlignment > alignof(Tcb)) {
             tlsAddress = alignUp(allocation + sizeof(Tcb), tlsMaxAlignment);
             tcbAddress = tlsAddress - sizeof(Tcb);
         } else {
             tcbAddress = alignUp(allocation, alignof(Tcb));
             tlsAddress = tcbAddress + sizeof(Tcb);
         }
         __ensure((tlsAddress & (tlsMaxAlignment - 1)) == 0);
         __ensure(tlsAddress == tcbAddress + sizeof(Tcb));
     } else {
         // The TCB should be aligned such that the preceding blocks are aligned too.
         tcbAddress = alignUp(allocation + tlsInitialSize, alignOverhead);
         tlsAddress = tcbAddress - tlsInitialSize;
     }
     __ensure((tcbAddress & (alignof(Tcb) - 1)) == 0);
     if (verbose) {
         mlibc::infoLogger() << "rtdl: tcb allocated at " << (void *)tcbAddress
                 << ", size = 0x" << frg::hex_fmt{sizeof(Tcb)} << frg::endlog;
         mlibc::infoLogger() << "rtdl: tls allocated at " << (void *)tlsAddress
                 << ", size = 0x" << frg::hex_fmt{tlsInitialSize} << frg::endlog;
     }
     Tcb *tcb_ptr = new ((char *)tcbAddress) Tcb;
     tcb_ptr->selfPointer = tcb_ptr;
     tcb_ptr->stackCanary = __stack_chk_guard;
     tcb_ptr->cancelBits = tcbCancelEnableBit;
     tcb_ptr->didExit = 0;
     tcb_ptr->isJoinable = 1;
     tcb_ptr->returnValue = nullptr;
     tcb_ptr->localKeys = frg::construct<frg::array<Tcb::LocalKey, PTHREAD_KEYS_MAX>>(getAllocator());
     tcb_ptr->dtvSize = runtimeTlsMap->indices.size();
     tcb_ptr->dtvPointers = frg::construct_n<void *>(getAllocator(), runtimeTlsMap->indices.size());
     memset(tcb_ptr->dtvPointers, 0, sizeof(void *) * runtimeTlsMap->indices.size());
     for(size_t i = 0; i < runtimeTlsMap->indices.size(); ++i) {
         auto object = runtimeTlsMap->indices[i];
         if(object->tlsModel != TlsModel::initial)
             continue;
         tcb_ptr->dtvPointers[i] = reinterpret_cast<char *>(tcb_ptr) + object->tlsOffset;
     }
     return tcb_ptr;
 }
References __ensure, __stack_chk_guard, alignUp(), Tcb::cancelBits, Tcb::didExit, Tcb::dtvPointers, Tcb::dtvSize, getAllocator(), i, mlibc::infoLogger, initial, Tcb::isJoinable, Tcb::localKeys, memset, Tcb::returnValue, runtimeTlsMap, Tcb::selfPointer, Tcb::stackCanary, anonymous_namespace{tcb.hpp}::tcbCancelEnableBit, tlsMaxAlignment, and verbose.
Referenced by __rtdl_allocateTcb().
closeOrDie()
void closeOrDie (int fd)
Definition at line 74 of file linker.cpp.
{
     if(mlibc::sys_close(fd))
         __ensure(!"sys_close() failed");
 }
References __ensure, fd, and mlibc::sys_close().
Referenced by ObjectRepository::requestObjectAtPath(), and ObjectRepository::requestObjectWithName().
doInitialize()
void doInitialize (SharedObject * object)
Definition at line 807 of file linker.cpp.
{
     __ensure(object->wasLinked);
     __ensure(!object->wasInitialized);
     // if the object has dependencies we initialize them first
     for(size_t i = 0; i < object->dependencies.size(); i++)
         __ensure(object->dependencies[i]->wasInitialized);
     if(verbose)
         mlibc::infoLogger() << "rtdl: Initialize " << object->name << frg::endlog;
     if(verbose)
         mlibc::infoLogger() << "rtdl: Running DT_INIT function" << frg::endlog;
     if(object->initPtr != nullptr)
         object->initPtr();
     if(verbose)
         mlibc::infoLogger() << "rtdl: Running DT_INIT_ARRAY functions" << frg::endlog;
     __ensure((object->initArraySize % sizeof(InitFuncPtr)) == 0);
     for(size_t i = 0; i < object->initArraySize / sizeof(InitFuncPtr); i++)
         object->initArray[i]();
     if(verbose)
         mlibc::infoLogger() << "rtdl: Object initialization complete" << frg::endlog;
     object->wasInitialized = true;
 }
References __ensure, SharedObject::dependencies, i, mlibc::infoLogger, SharedObject::initArray, SharedObject::initArraySize, SharedObject::initPtr, verbose, SharedObject::wasInitialized, and SharedObject::wasLinked.
Referenced by Loader::initObjects().
elf64Hash()
uint32_t elf64Hash (frg::string_view string)
Definition at line 995 of file linker.cpp.
{
     uint32_t h = 0, g;
     for(size_t i = 0; i < string.size(); ++i) {
         h = (h << 4) + (uint32_t)string[i];
         g = h & 0xF0000000;
         if(g)
             h ^= g >> 24;
         h &= 0x0FFFFFFF;
     }
     return h;
 }
References g, and i.
Referenced by resolveInObject().
gnuHash()
uint32_t gnuHash (frg::string_view string)
Definition at line 1009 of file linker.cpp.
{
     uint32_t h = 5381;
     for(size_t i = 0; i < string.size(); ++i)
         h = (h << 5) + h + string[i];
     return h;
 }
References i.
Referenced by resolveInObject().
initTlsObjects()
void initTlsObjects (Tcb * tcb, const frg::vector< SharedObject *, MemoryAllocator > & objects, bool checkInitialized)
Definition at line 841 of file linker.cpp.
{
     // Initialize TLS segments that follow the static model.
     for(auto object : objects) {
         if(object->tlsModel == TlsModel::initial) {
             if(checkInitialized && object->tlsInitialized)
                 continue;
             char *tcb_ptr = reinterpret_cast<char *>(tcb);
             auto tls_ptr = tcb_ptr + object->tlsOffset;
             memset(tls_ptr, 0, object->tlsSegmentSize);
             memcpy(tls_ptr, object->tlsImagePtr, object->tlsImageSize);
             if (verbose) {
                 mlibc::infoLogger() << "rtdl: wrote tls image at " << (void *)tls_ptr
                         << ", size = 0x" << frg::hex_fmt{object->tlsSegmentSize} << frg::endlog;
             }
             if (checkInitialized)
                 object->tlsInitialized = true;
         }
     }
 }
References mlibc::infoLogger, initial, memcpy, memset, and verbose.
Referenced by __rtdl_allocateTcb(), and Loader::initObjects().
processCopyRela()
void processCopyRela (SharedObject * object, Elf64_Rela * reloc)
Definition at line 752 of file linker.cpp.
{
     Elf64_Xword type = ELF64_R_TYPE(reloc->r_info);
     Elf64_Xword symbol_index = ELF64_R_SYM(reloc->r_info);
 #if defined(__x86_64__)
     if(type != R_X86_64_COPY)
         return;
 #elif defined(__aarch64__)
     if(type != R_AARCH64_COPY)
         return;
 #elif defined(__riscv)
     if (type != R_RISCV_COPY)
         return;
 #endif
     uintptr_t rel_addr = object->baseAddress + reloc->r_offset;
     auto symbol = (Elf64_Sym *)(object->baseAddress + object->symbolTableOffset
             + symbol_index * sizeof(Elf64_Sym));
     ObjectSymbol r(object, symbol);
     frg::optional<ObjectSymbol> p = Scope::resolveGlobalOrLocal(*globalScope, object->localScope, r.getString(), object->objectRts, Scope::resolveCopy);
     __ensure(p);
     memcpy((void *)rel_addr, (void *)p->virtualAddress(), symbol->st_size);
 }
References __ensure, SharedObject::baseAddress, ELF64_R_SYM(), ELF64_R_TYPE(), globalScope, SharedObject::localScope, memcpy, SharedObject::objectRts, p, r, R_AARCH64_COPY, Elf64_Rela::r_info, Elf64_Rela::r_offset, R_RISCV_COPY, R_X86_64_COPY, Scope::resolveCopy, Scope::resolveGlobalOrLocal(), SharedObject::symbolTableOffset, and type.
Referenced by processCopyRelocations().
processCopyRelocations()
void processCopyRelocations (SharedObject * object)
Definition at line 777 of file linker.cpp.
{
     frg::optional<uintptr_t> rela_offset;
     frg::optional<size_t> rela_length;
     for(size_t i = 0; object->dynamic[i].d_tag != DT_NULL; i++) {
         Elf64_Dyn *dynamic = &object->dynamic[i];
         switch(dynamic->d_tag) {
         case DT_RELA:
             rela_offset = dynamic->d_un.d_ptr;
             break;
         case DT_RELASZ:
             rela_length = dynamic->d_un.d_val;
             break;
         case DT_RELAENT:
             __ensure(dynamic->d_un.d_val == sizeof(Elf64_Rela));
             break;
         }
     }
     if(rela_offset && rela_length) {
         for(size_t offset = 0; offset < *rela_length; offset += sizeof(Elf64_Rela)) {
             auto reloc = (Elf64_Rela *)(object->baseAddress + *rela_offset + offset);
             processCopyRela(object, reloc);
         }
     }else{
         __ensure(!rela_offset && !rela_length);
     }
 }
References __ensure, SharedObject::baseAddress, DT_NULL, DT_RELA, DT_RELAENT, DT_RELASZ, dynamic, i, offset, and processCopyRela().
Referenced by Loader::linkObjects().
readExactlyOrDie()
void readExactlyOrDie (int fd, void * data, size_t length)
Definition at line 61 of file linker.cpp.
{
     size_t offset = 0;
     while(offset < length) {
         ssize_t chunk;
         if(mlibc::sys_read(fd, reinterpret_cast<char *>(data) + offset,
                 length - offset, &chunk))
             __ensure(!"sys_read() failed");
         __ensure(chunk > 0);
         offset += chunk;
     }
     __ensure(offset == length);
 }
References __ensure, fd, offset, and mlibc::sys_read().
Referenced by ObjectRepository::_fetchFromFile().
resolveInObject()
frg::optional<ObjectSymbol> resolveInObject (SharedObject * object, frg::string_view string)
Definition at line 1017 of file linker.cpp.
{
     // Checks if the symbol can be used to satisfy the dependency.
     auto eligible = [&] (ObjectSymbol cand) {
         if(cand.symbol()->st_shndx == SHN_UNDEF)
             return false;
         auto bind = ELF64_ST_BIND(cand.symbol()->st_info);
         if(bind != STB_GLOBAL && bind != STB_WEAK && bind != STB_GNU_UNIQUE)
             return false;
         return true;
     };
     if (object->hashStyle == HashStyle::systemV) {
         auto hash_table = (Elf64_Word *)(object->baseAddress + object->hashTableOffset);
         Elf64_Word num_buckets = hash_table[0];
         auto bucket = elf64Hash(string) % num_buckets;
         auto index = hash_table[2 + bucket];
         while(index != 0) {
             ObjectSymbol cand{object, (Elf64_Sym *)(object->baseAddress
                     + object->symbolTableOffset + index * sizeof(Elf64_Sym))};
             if(eligible(cand) && frg::string_view{cand.getString()} == string)
                 return cand;
             index = hash_table[2 + num_buckets + index];
         }
         return frg::optional<ObjectSymbol>{};
     }else{
         __ensure(object->hashStyle == HashStyle::gnu);
         struct GnuTable {
             Elf64_Word nBuckets;
             Elf64_Word symbolOffset;
             Elf64_Word bloomSize;
             Elf64_Word bloomShift;
         };
         auto hash_table = reinterpret_cast<const GnuTable *>(object->baseAddress
                 + object->hashTableOffset);
         auto buckets = reinterpret_cast<const Elf64_Word *>(object->baseAddress
                 + object->hashTableOffset + sizeof(GnuTable)
                 + hash_table->bloomSize * sizeof(Elf64_Addr));
         auto chains = reinterpret_cast<const Elf64_Word *>(object->baseAddress
                 + object->hashTableOffset + sizeof(GnuTable)
                 + hash_table->bloomSize * sizeof(Elf64_Addr)
                 + hash_table->nBuckets * sizeof(Elf64_Word));
         // TODO: Use the bloom filter.
         // The symbols of a given bucket are contiguous in the table.
         auto hash = gnuHash(string);
         auto index = buckets[hash % hash_table->nBuckets];
         if(!index)
             return frg::optional<ObjectSymbol>{};
         while(true) {
             // chains[] contains an array of hashes, parallel to the symbol table.
             auto chash = chains[index - hash_table->symbolOffset];
             if ((chash & ~1) == (hash & ~1)) {
                 ObjectSymbol cand{object, (Elf64_Sym *)(object->baseAddress
                         + object->symbolTableOffset + index * sizeof(Elf64_Sym))};
                 if(eligible(cand) && frg::string_view{cand.getString()} == string)
                     return cand;
             }
             // If we hit the end of the chain, the symbol is not present.
             if(chash & 1)
                 return frg::optional<ObjectSymbol>{};
             index++;
         }
     }
 }
References __ensure, SharedObject::baseAddress, bind(), ELF64_ST_BIND, elf64Hash(), gnu, gnuHash(), SharedObject::hashStyle, SharedObject::hashTableOffset, index(), SHN_UNDEF, STB_GLOBAL, STB_GNU_UNIQUE, STB_WEAK, SharedObject::symbolTableOffset, and systemV.
Referenced by Scope::_resolveNext(), and Scope::resolveSymbol().
seekOrDie()
void seekOrDie (int fd, int64_t offset)
Definition at line 55 of file linker.cpp.
{
     off_t noff;
     if(mlibc::sys_seek(fd, offset, SEEK_SET, &noff))
         __ensure(!"sys_seek() failed");
 }
References __ensure, fd, offset, SEEK_SET, and mlibc::sys_seek().
Referenced by ObjectRepository::_fetchFromFile().
tryAccessDtv()
void* tryAccessDtv (SharedObject * object)
Definition at line 960 of file linker.cpp.
{
     Tcb *tcb_ptr = mlibc::get_current_tcb();
     if (object->tlsIndex >= tcb_ptr->dtvSize)
         return nullptr;
     if (!tcb_ptr->dtvPointers[object->tlsIndex])
         return nullptr;
     return (void *)((char *)tcb_ptr->dtvPointers[object->tlsIndex] + TLS_DTV_OFFSET);
 }
References Tcb::dtvPointers, Tcb::dtvSize, mlibc::get_current_tcb(), and SharedObject::tlsIndex.
Referenced by __dlapi_iterate_phdr().
Variable Documentation
__stack_chk_guard
uintptr_t __stack_chk_guard extern
Definition at line 24 of file StackCheck.cpp.
Referenced by __attribute__(), __guard_setup(), __stack_chk_fail(), allocateTcb(), and mlibc::initStackGuard().
eagerBinding
constexpr bool eagerBinding = true constexpr
Definition at line 23 of file linker.cpp.
Referenced by Loader::_processLazyRelocations().
globalDebugInterface
DebugInterface globalDebugInterface extern
Definition at line 52 of file main.cpp.
Referenced by ObjectRepository::_parseDynamic(), interpreterMain(), and Loader::linkObjects().
libraryBase
uintptr_t libraryBase = 0x41000000
Definition at line 16 of file linker.cpp.
Referenced by ObjectRepository::_fetchFromFile().
logBaseAddresses
constexpr bool logBaseAddresses = false constexpr
Definition at line 21 of file linker.cpp.
Referenced by ObjectRepository::_fetchFromFile().
logRpath
constexpr bool logRpath = false constexpr
Definition at line 22 of file linker.cpp.
Referenced by ObjectRepository::requestObjectWithName().
rtsCounter
uint64_t rtsCounter = 2
Definition at line 53 of file linker.cpp.
Referenced by __dlapi_iterate_phdr().
stillSlightlyVerbose
constexpr bool stillSlightlyVerbose = false constexpr
Definition at line 20 of file linker.cpp.
Referenced by Loader::_processRela().
tlsMaxAlignment
size_t tlsMaxAlignment = 16
Definition at line 45 of file linker.cpp.
Referenced by Loader::_buildLinkBfs(), Loader::_buildTlsMaps(), and allocateTcb().
verbose
constexpr bool verbose = false constexpr
Definition at line 19 of file linker.cpp.
Referenced by Loader::_buildTlsMaps(), ObjectRepository::_fetchFromFile(), ObjectRepository::_fetchFromPhdrs(), Loader::_processLazyRelocations(), Loader::_processRela(), accessDtv(), allocateTcb(), doInitialize(), Loader::initObjects(), initTlsObjects(), and Loader::linkObjects().