Fennix: Userspace/apps/base/bash/copy_cmd.c File Reference
copy_cmd.c File Reference
#include "config.h"
#include "bashtypes.h"
#include <stdio.h>
#include "shell.h"
Functions
static PATTERN_LIST *copy_case_clause PARAMS ((PATTERN_LIST *))
static FOR_COM *copy_for_command PARAMS ((FOR_COM *))
static GROUP_COM *copy_group_command PARAMS ((GROUP_COM *))
static SUBSHELL_COM *copy_subshell_command PARAMS ((SUBSHELL_COM *))
static COPROC_COM *copy_coproc_command PARAMS ((COPROC_COM *))
static CASE_COM *copy_case_command PARAMS ((CASE_COM *))
static WHILE_COM *copy_while_command PARAMS ((WHILE_COM *))
static IF_COM *copy_if_command PARAMS ((IF_COM *))
static SIMPLE_COM *copy_simple_command PARAMS ((SIMPLE_COM *))
WORD_DESC * copy_word (WORD_DESC *w)
WORD_LIST * copy_word_list (WORD_LIST *list)
static PATTERN_LIST * copy_case_clause (PATTERN_LIST *clause)
static PATTERN_LIST * copy_case_clauses (PATTERN_LIST *clauses)
REDIRECT * copy_redirect (REDIRECT *redirect)
REDIRECT * copy_redirects (REDIRECT *list)
static FOR_COM * copy_for_command (FOR_COM *com)
static GROUP_COM * copy_group_command (GROUP_COM *com)
static SUBSHELL_COM * copy_subshell_command (SUBSHELL_COM *com)
static COPROC_COM * copy_coproc_command (COPROC_COM *com)
static CASE_COM * copy_case_command (CASE_COM *com)
static WHILE_COM * copy_while_command (WHILE_COM *com)
static IF_COM * copy_if_command (IF_COM *com)
static SIMPLE_COM * copy_simple_command (SIMPLE_COM *com)
FUNCTION_DEF * copy_function_def_contents (FUNCTION_DEF *old, FUNCTION_DEF *new_def)
FUNCTION_DEF * copy_function_def (FUNCTION_DEF *com)
COMMAND * copy_command (COMMAND *command)
Function Documentation
copy_case_clause()
static PATTERN_LIST* copy_case_clause (PATTERN_LIST * clause) static
Definition at line 89 of file copy_cmd.c.
 {
   PATTERN_LIST *new_clause;
   new_clause = (PATTERN_LIST *)xmalloc (sizeof (PATTERN_LIST));
   new_clause->patterns = copy_word_list (clause->patterns);
   new_clause->action = copy_command (clause->action);
   new_clause->flags = clause->flags;
   return (new_clause);
 }
References pattern_list::action, copy_command(), copy_word_list(), pattern_list::flags, pattern_list::patterns, and xmalloc.
Referenced by copy_case_clauses().
copy_case_clauses()
static PATTERN_LIST* copy_case_clauses (PATTERN_LIST * clauses) static
Definition at line 102 of file copy_cmd.c.
 {
   PATTERN_LIST *new_list, *new_clause;
   for (new_list = (PATTERN_LIST *)NULL; clauses; clauses = clauses->next)
     {
       new_clause = copy_case_clause (clauses);
       new_clause->next = new_list;
       new_list = new_clause;
     }
   return (REVERSE_LIST (new_list, PATTERN_LIST *));
 }
References copy_case_clause(), pattern_list::next, NULL, and REVERSE_LIST.
Referenced by copy_case_command().
copy_case_command()
static CASE_COM* copy_case_command (CASE_COM * com) static
Definition at line 250 of file copy_cmd.c.
 {
   CASE_COM *new_case;
   new_case = (CASE_COM *)xmalloc (sizeof (CASE_COM));
   new_case->flags = com->flags;
   new_case->line = com->line;
   new_case->word = copy_word (com->word);
   new_case->clauses = copy_case_clauses (com->clauses);
   return (new_case);
 }
References case_com::clauses, copy_case_clauses(), copy_word(), case_com::flags, case_com::line, case_com::word, and xmalloc.
Referenced by copy_command().
copy_command()
COMMAND* copy_command (COMMAND * command)
Definition at line 366 of file copy_cmd.c.
 {
   COMMAND *new_command;
   if (command == NULL)
     return (command);
   new_command = (COMMAND *)xmalloc (sizeof (COMMAND));
   FASTCOPY ((char *)command, (char *)new_command, sizeof (COMMAND));
   new_command->flags = command->flags;
   new_command->line = command->line;
   if (command->redirects)
     new_command->redirects = copy_redirects (command->redirects);
   switch (command->type)
     {
       case cm_for:
     new_command->value.For = copy_for_command (command->value.For);
     break;
 #if defined (ARITH_FOR_COMMAND)
       case cm_arith_for:
     new_command->value.ArithFor = copy_arith_for_command (command->value.ArithFor);
     break;
 #endif
 #if defined (SELECT_COMMAND)
       case cm_select:
     new_command->value.Select =
       (SELECT_COM *)copy_for_command ((FOR_COM *)command->value.Select);
     break;
 #endif
       case cm_group:
     new_command->value.Group = copy_group_command (command->value.Group);
     break;
       case cm_subshell:
     new_command->value.Subshell = copy_subshell_command (command->value.Subshell);
     break;
       case cm_coproc:
     new_command->value.Coproc = copy_coproc_command (command->value.Coproc);
     break;
       case cm_case:
     new_command->value.Case = copy_case_command (command->value.Case);
     break;
       case cm_until:
       case cm_while:
     new_command->value.While = copy_while_command (command->value.While);
     break;
       case cm_if:
     new_command->value.If = copy_if_command (command->value.If);
     break;
 #if defined (DPAREN_ARITHMETIC)
       case cm_arith:
     new_command->value.Arith = copy_arith_command (command->value.Arith);
     break;
 #endif
 #if defined (COND_COMMAND)
       case cm_cond:
     new_command->value.Cond = copy_cond_command (command->value.Cond);
     break;
 #endif
       case cm_simple:
     new_command->value.Simple = copy_simple_command (command->value.Simple);
     break;
       case cm_connection:
     {
       CONNECTION *new_connection;
       new_connection = (CONNECTION *)xmalloc (sizeof (CONNECTION));
       new_connection->connector = command->value.Connection->connector;
       new_connection->first = copy_command (command->value.Connection->first);
       new_connection->second = copy_command (command->value.Connection->second);
       new_command->value.Connection = new_connection;
       break;
     }
       case cm_function_def:
     new_command->value.Function_def = copy_function_def (command->value.Function_def);
     break;
     }
   return (new_command);
 }
References cm_arith, cm_arith_for, cm_case, cm_cond, cm_connection, cm_coproc, cm_for, cm_function_def, cm_group, cm_if, cm_select, cm_simple, cm_subshell, cm_until, cm_while, connection::connector, copy_case_command(), copy_coproc_command(), copy_for_command(), copy_function_def(), copy_group_command(), copy_if_command(), copy_redirects(), copy_simple_command(), copy_subshell_command(), copy_while_command(), FASTCOPY, connection::first, command::flags, command::line, NULL, command::redirects, connection::second, command::type, command::value, and xmalloc.
Referenced by bind_function(), copy_case_clause(), copy_coproc_command(), copy_for_command(), copy_function_def_contents(), copy_group_command(), copy_if_command(), copy_subshell_command(), copy_while_command(), execute_function(), named_function_string(), and print_function_def().
copy_coproc_command()
static COPROC_COM* copy_coproc_command (COPROC_COM * com) static
Definition at line 237 of file copy_cmd.c.
 {
   COPROC_COM *new_coproc;
   new_coproc = (COPROC_COM *)xmalloc (sizeof (COPROC_COM));
   new_coproc->name = savestring (com->name);
   new_coproc->command = copy_command (com->command);
   new_coproc->flags = com->flags;
   return (new_coproc);
 }
References group_com::command, coproc_com::command, copy_command(), coproc_com::flags, coproc_com::name, savestring(), and xmalloc.
Referenced by copy_command().
copy_for_command()
static FOR_COM* copy_for_command (FOR_COM * com) static
Definition at line 180 of file copy_cmd.c.
 {
   FOR_COM *new_for;
   new_for = (FOR_COM *)xmalloc (sizeof (FOR_COM));
   new_for->flags = com->flags;
   new_for->line = com->line;
   new_for->name = copy_word (com->name);
   new_for->map_list = copy_word_list (com->map_list);
   new_for->action = copy_command (com->action);
   return (new_for);
 }
References for_com::action, copy_command(), copy_word(), copy_word_list(), for_com::flags, for_com::line, for_com::map_list, for_com::name, and xmalloc.
Referenced by copy_command().
copy_function_def()
FUNCTION_DEF* copy_function_def (FUNCTION_DEF * com)
Definition at line 352 of file copy_cmd.c.
 {
   FUNCTION_DEF *new_def;
   new_def = (FUNCTION_DEF *)xmalloc (sizeof (FUNCTION_DEF));
   new_def = copy_function_def_contents (com, new_def);
   return (new_def);
 }
References copy_function_def_contents(), and xmalloc.
Referenced by copy_command().
copy_function_def_contents()
FUNCTION_DEF* copy_function_def_contents (FUNCTION_DEF * old, FUNCTION_DEF * new_def)
Definition at line 340 of file copy_cmd.c.
 {
   new_def->name = copy_word (old->name);
   new_def->command = old->command ? copy_command (old->command) : old->command;
   new_def->flags = old->flags;
   new_def->line = old->line;
   new_def->source_file = old->source_file ? savestring (old->source_file) : old->source_file;
   return (new_def);
 }
References function_def::command, copy_command(), copy_word(), function_def::flags, function_def::line, function_def::name, old, savestring(), and function_def::source_file.
Referenced by copy_function_def().
copy_group_command()
static GROUP_COM* copy_group_command (GROUP_COM * com) static
Definition at line 213 of file copy_cmd.c.
 {
   GROUP_COM *new_group;
   new_group = (GROUP_COM *)xmalloc (sizeof (GROUP_COM));
   new_group->command = copy_command (com->command);
   return (new_group);
 }
References group_com::command, copy_command(), new_group(), and xmalloc.
Referenced by copy_command().
copy_if_command()
static IF_COM* copy_if_command (IF_COM * com) static
Definition at line 277 of file copy_cmd.c.
 {
   IF_COM *new_if;
   new_if = (IF_COM *)xmalloc (sizeof (IF_COM));
   new_if->flags = com->flags;
   new_if->test = copy_command (com->test);
   new_if->true_case = copy_command (com->true_case);
   new_if->false_case = com->false_case ? copy_command (com->false_case) : com->false_case;
   return (new_if);
 }
References copy_command(), if_com::false_case, if_com::flags, if_com::test, if_com::true_case, and xmalloc.
Referenced by copy_command().
copy_redirect()
REDIRECT* copy_redirect (REDIRECT * redirect)
Definition at line 118 of file copy_cmd.c.
 {
   REDIRECT *new_redirect;
   new_redirect = (REDIRECT *)xmalloc (sizeof (REDIRECT));
 #if 0
   FASTCOPY ((char *)redirect, (char *)new_redirect, (sizeof (REDIRECT)));
 #else
   *new_redirect = *redirect;    /* let the compiler do the fast structure copy */
 #endif
   if (redirect->rflags & REDIR_VARASSIGN)
     new_redirect->redirector.filename = copy_word (redirect->redirector.filename);
   switch (redirect->instruction)
     {
     case r_reading_until:
     case r_deblank_reading_until:
       new_redirect->here_doc_eof = redirect->here_doc_eof ? savestring (redirect->here_doc_eof) : 0;
       /*FALLTHROUGH*/
     case r_reading_string:
     case r_appending_to:
     case r_output_direction:
     case r_input_direction:
     case r_inputa_direction:
     case r_err_and_out:
     case r_append_err_and_out:
     case r_input_output:
     case r_output_force:
     case r_duplicating_input_word:
     case r_duplicating_output_word:
     case r_move_input_word:
     case r_move_output_word:
       new_redirect->redirectee.filename = copy_word (redirect->redirectee.filename);
       break;
     case r_duplicating_input:
     case r_duplicating_output:
     case r_move_input:
     case r_move_output:
     case r_close_this:
       break;
     }
   return (new_redirect);
 }
References copy_word(), FASTCOPY, REDIRECTEE::filename, redirect::here_doc_eof, redirect::instruction, r_append_err_and_out, r_appending_to, r_close_this, r_deblank_reading_until, r_duplicating_input, r_duplicating_input_word, r_duplicating_output, r_duplicating_output_word, r_err_and_out, r_input_direction, r_input_output, r_inputa_direction, r_move_input, r_move_input_word, r_move_output, r_move_output_word, r_output_direction, r_output_force, r_reading_string, r_reading_until, REDIR_VARASSIGN, redirect(), redirect::redirectee, redirect::redirector, redirect::rflags, savestring(), and xmalloc.
Referenced by copy_redirects(), and print_redirection_list().
copy_redirects()
REDIRECT* copy_redirects (REDIRECT * list)
Definition at line 165 of file copy_cmd.c.
 {
   REDIRECT *new_list, *temp;
   for (new_list = (REDIRECT *)NULL; list; list = list->next)
     {
       temp = copy_redirect (list);
       temp->next = new_list;
       new_list = temp;
     }
   return (REVERSE_LIST (new_list, REDIRECT *));
 }
References copy_redirect(), list(), redirect::next, node::next, NULL, and REVERSE_LIST.
Referenced by add_undo_redirect(), copy_command(), and copy_simple_command().
copy_simple_command()
static SIMPLE_COM* copy_simple_command (SIMPLE_COM * com) static
Definition at line 326 of file copy_cmd.c.
 {
   SIMPLE_COM *new_simple;
   new_simple = (SIMPLE_COM *)xmalloc (sizeof (SIMPLE_COM));
   new_simple->flags = com->flags;
   new_simple->words = copy_word_list (com->words);
   new_simple->redirects = com->redirects ? copy_redirects (com->redirects) : (REDIRECT *)NULL;
   new_simple->line = com->line;
   return (new_simple);
 }
References copy_redirects(), copy_word_list(), simple_com::flags, simple_com::line, NULL, simple_com::redirects, simple_com::words, and xmalloc.
Referenced by copy_command().
copy_subshell_command()
static SUBSHELL_COM* copy_subshell_command (SUBSHELL_COM * com) static
Definition at line 224 of file copy_cmd.c.
 {
   SUBSHELL_COM *new_subshell;
   new_subshell = (SUBSHELL_COM *)xmalloc (sizeof (SUBSHELL_COM));
   new_subshell->command = copy_command (com->command);
   new_subshell->flags = com->flags;
   new_subshell->line = com->line;
   return (new_subshell);
 }
References group_com::command, subshell_com::command, copy_command(), subshell_com::flags, subshell_com::line, and xmalloc.
Referenced by copy_command().
copy_while_command()
static WHILE_COM* copy_while_command (WHILE_COM * com) static
Definition at line 264 of file copy_cmd.c.
 {
   WHILE_COM *new_while;
   new_while = (WHILE_COM *)xmalloc (sizeof (WHILE_COM));
   new_while->flags = com->flags;
   new_while->test = copy_command (com->test);
   new_while->action = copy_command (com->action);
   return (new_while);
 }
References while_com::action, copy_command(), while_com::flags, while_com::test, and xmalloc.
Referenced by copy_command().
copy_word()
WORD_DESC* copy_word (WORD_DESC * w)
Definition at line 56 of file copy_cmd.c.
 {
   WORD_DESC *new_word;
   new_word = make_bare_word (w->word);
   new_word->flags = w->flags;
   return (new_word);
 }
References word_desc::flags, make_bare_word(), and w.
Referenced by copy_case_command(), copy_for_command(), copy_function_def_contents(), copy_redirect(), copy_word_list(), and redirection_expand().
copy_word_list()
WORD_LIST* copy_word_list (WORD_LIST * list)
Definition at line 69 of file copy_cmd.c.
 {
   WORD_LIST *new_list, *tl;
   for (new_list = tl = (WORD_LIST *)NULL; list; list = list->next)
     {
       if (new_list == 0)
     new_list = tl = make_word_list (copy_word (list->word), new_list);
       else
     {
       tl->next = make_word_list (copy_word (list->word), (WORD_LIST *)NULL);
       tl = tl->next;
     }
     }
   return (new_list);
 }
References copy_word(), list(), make_word_list(), node::next, NULL, and tl.
Referenced by copy_case_clause(), copy_for_command(), copy_simple_command(), execute_simple_command(), expand_word_internal(), expand_word_list_internal(), and remember_args().
PARAMS() [1/9]
static CASE_COM* copy_case_command PARAMS ((CASE_COM *)) static
PARAMS() [2/9]
static COPROC_COM* copy_coproc_command PARAMS ((COPROC_COM *)) static
PARAMS() [3/9]
static FOR_COM* copy_for_command PARAMS ((FOR_COM *)) static
PARAMS() [4/9]
static GROUP_COM* copy_group_command PARAMS ((GROUP_COM *)) static
PARAMS() [5/9]
static IF_COM* copy_if_command PARAMS ((IF_COM *)) static
PARAMS() [6/9]
static PATTERN_LIST* copy_case_clause PARAMS ((PATTERN_LIST *)) static
PARAMS() [7/9]
static SIMPLE_COM* copy_simple_command PARAMS ((SIMPLE_COM *)) static
PARAMS() [8/9]
static SUBSHELL_COM* copy_subshell_command PARAMS ((SUBSHELL_COM *)) static
PARAMS() [9/9]
static WHILE_COM* copy_while_command PARAMS ((WHILE_COM *)) static