Fennix: Userspace/mlibc/options/posix/include/fcntl.h File Reference
fcntl.h File Reference
#include <abi-bits/fcntl.h>
#include <abi-bits/seek-whence.h>
#include <abi-bits/mode_t.h>
#include <abi-bits/pid_t.h>
#include <bits//off_t.h>
Data Structures
struct flock
struct file_handle
Macros
#define O_NDELAY O_NONBLOCK
#define POSIX_FADV_NORMAL 1
#define POSIX_FADV_SEQUENTIAL 2
#define POSIX_FADV_NOREUSE 3
#define POSIX_FADV_DONTNEED 4
#define POSIX_FADV_WILLNEED 5
#define POSIX_FADV_RANDOM 6
Functions
int creat (const char *, mode_t)
int fallocate (int fd, int mode, off_t offset, off_t len)
int fcntl (int fd, int command,...)
int open (const char *path, int flags,...)
int openat (int, const char *, int,...)
int posix_fadvise (int, off_t, off_t, int)
int posix_fallocate (int, off_t, off_t)
int name_to_handle_at (int, const char *, struct file_handle *, int *, int)
int open_by_handle_at (int, struct file_handle *, int)
Data Structure Documentation
flock
struct flock
Definition at line 24 of file fcntl.h.
Data Fields
off_t l_len
pid_t l_pid
off_t l_start
short l_type
short l_whence
file_handle
struct file_handle
Definition at line 42 of file fcntl.h.
Data Fields
unsigned char f_handle[0]
unsigned int handle_bytes
int handle_type
Macro Definition Documentation
O_NDELAY
#define O_NDELAY O_NONBLOCK
Definition at line 15 of file fcntl.h.
POSIX_FADV_DONTNEED
#define POSIX_FADV_DONTNEED 4
Definition at line 20 of file fcntl.h.
POSIX_FADV_NOREUSE
#define POSIX_FADV_NOREUSE 3
Definition at line 19 of file fcntl.h.
POSIX_FADV_NORMAL
#define POSIX_FADV_NORMAL 1
Definition at line 17 of file fcntl.h.
POSIX_FADV_RANDOM
#define POSIX_FADV_RANDOM 6
Definition at line 22 of file fcntl.h.
POSIX_FADV_SEQUENTIAL
#define POSIX_FADV_SEQUENTIAL 2
Definition at line 18 of file fcntl.h.
POSIX_FADV_WILLNEED
#define POSIX_FADV_WILLNEED 5
Definition at line 21 of file fcntl.h.
Function Documentation
creat()
int creat (const char * pathname, mode_t mode)
Definition at line 10 of file fcntl-stubs.cpp.
{
     return open(pathname, O_CREAT|O_WRONLY|O_TRUNC, mode);
 }
References O_CREAT, O_TRUNC, O_WRONLY, and open().
fallocate()
int fallocate (int fd, int mode, off_t offset, off_t len)
Definition at line 14 of file fcntl-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: fallocate() is a no-op" << frg::endlog;
     errno = ENOSYS;
     return -1;
 }
References ENOSYS, errno, and mlibc::infoLogger.
fcntl()
int fcntl (int fd, int command, ...)
Definition at line 20 of file fcntl-stubs.cpp.
{
     va_list args;
     va_start(args, command);
     int result;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fcntl, -1);
     if(int e = mlibc::sys_fcntl(fd, command, args, &result); e) {
         errno = e;
         return -1;
     }
     va_end(args);
     return result;
 }
References args, errno, fd, MLIBC_CHECK_OR_ENOSYS, mlibc::result, mlibc::sys_fcntl(), va_end(), and va_start().
Referenced by accept4(), child(), fdopen(), fdopendir(), lockf(), popen(), run_test(), and we_askshell().
name_to_handle_at()
int name_to_handle_at (int , const char * , struct file_handle * , int * , int)
Definition at line 71 of file fcntl-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
open()
int open (const char * path, int flags, ...)
Definition at line 81 of file fcntl-stubs.cpp.
{
     mode_t mode = 0;
     if ((flags & O_CREAT) || (flags & O_TMPFILE)) {
         va_list args;
         va_start(args, flags);
         mode = va_arg(args, mode_t);
         va_end(args);
     }
     int fd;
     if(int e = mlibc::sys_open(pathname, flags, mode, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References args, errno, fd, flags, O_CREAT, O_TMPFILE, mlibc::sys_open(), va_arg, va_end(), and va_start().
Referenced by _vsyslog(), child(), creat(), update-syscall-list::fetch_kernel(), getpass(), getspnam_r(), main(), update-syscall-list::main(), setutent(), and shm_open().
open_by_handle_at()
int open_by_handle_at (int , struct file_handle * , int)
Definition at line 76 of file fcntl-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
openat()
int openat (int dirfd, const char * pathname, int flags, ...)
Definition at line 33 of file fcntl-stubs.cpp.
{
     va_list args;
     va_start(args, flags);
     mode_t mode = 0;
     int fd;
     if((flags & (O_CREAT | O_TMPFILE)))
         mode = va_arg(args, mode_t);
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_openat, -1);
     if(int e = mlibc::sys_openat(dirfd, pathname, flags, mode, &fd); e) {
         errno = e;
         return -1;
     }
     va_end(args);
     return fd;
 }
References args, dirfd(), errno, fd, flags, MLIBC_CHECK_OR_ENOSYS, O_CREAT, O_TMPFILE, mlibc::sys_openat(), va_arg, va_end(), and va_start().
posix_fadvise()
int posix_fadvise (int fd, off_t offset, off_t length, int advice)
Definition at line 51 of file fcntl-stubs.cpp.
{
     if(!mlibc::sys_fadvise) {
         mlibc::infoLogger() << "mlibc: fadvise() ignored due to missing sysdep" << frg::endlog;
         return 0;
     }
     // posix_fadvise() returns an error instead of setting errno.
     return mlibc::sys_fadvise(fd, offset, length, advice);
 }
References fd, mlibc::infoLogger, offset, and mlibc::sys_fadvise().
posix_fallocate()
int posix_fallocate (int fd, off_t offset, off_t size)
Definition at line 61 of file fcntl-stubs.cpp.
{
     // posix_fallocate() returns an error instead of setting errno.
     if(!mlibc::sys_fallocate) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     return mlibc::sys_fallocate(fd, offset, size);
 }
References ENOSYS, fd, MLIBC_MISSING_SYSDEP, offset, size, and mlibc::sys_fallocate().