Fennix: Userspace/apps/base/bash/examples/loadables/finfo.c File Reference
finfo.c File Reference
#include <sys/types.h>
#include "posixstat.h"
#include <stdio.h>
#include <pwd.h>
#include <grp.h>
#include <errno.h>
#include "posixtime.h"
#include "bashansi.h"
#include "shell.h"
#include "builtins.h"
#include "common.h"
#include "getopt.h"
Macros
#define OPT_UID 0x00001
#define OPT_GID 0x00002
#define OPT_DEV 0x00004
#define OPT_INO 0x00008
#define OPT_PERM 0x00010
#define OPT_LNKNAM 0x00020
#define OPT_FID 0x00040
#define OPT_NLINK 0x00080
#define OPT_RDEV 0x00100
#define OPT_SIZE 0x00200
#define OPT_ATIME 0x00400
#define OPT_MTIME 0x00800
#define OPT_CTIME 0x01000
#define OPT_BLKSIZE 0x02000
#define OPT_BLKS 0x04000
#define OPT_FTYPE 0x08000
#define OPT_PMASK 0x10000
#define OPT_OPERM 0x20000
#define OPT_ASCII 0x1000000
#define OPTIONS "acdgiflmnopsuACGMP:U"
Functions
char ** make_builtin_argv ()
static void perms ()
static int printst ()
static int printsome ()
static void printmode ()
static int printfinfo ()
static int finfo_main ()
static int octal (char *s)
static int finfo_main (int argc, char **argv)
static struct stat * getstat (char *f)
static int printfinfo (char *f)
static int getperm (int m)
static void perms (int m)
static void printmode (int mode)
static int printst (struct stat *st)
static int printsome (char *f, int flags)
int finfo_builtin (WORD_LIST *list)
Variables
int errno
int sh_optind
char * sh_optarg
char * this_command_name
static char * prog
static int pmask
static char * finfo_doc []
struct builtin finfo_struct
Macro Definition Documentation
OPT_ASCII
#define OPT_ASCII 0x1000000
Definition at line 89 of file finfo.c.
OPT_ATIME
#define OPT_ATIME 0x00400
Definition at line 80 of file finfo.c.
OPT_BLKS
#define OPT_BLKS 0x04000
Definition at line 84 of file finfo.c.
OPT_BLKSIZE
#define OPT_BLKSIZE 0x02000
Definition at line 83 of file finfo.c.
OPT_CTIME
#define OPT_CTIME 0x01000
Definition at line 82 of file finfo.c.
OPT_DEV
#define OPT_DEV 0x00004
Definition at line 72 of file finfo.c.
OPT_FID
#define OPT_FID 0x00040
Definition at line 76 of file finfo.c.
OPT_FTYPE
#define OPT_FTYPE 0x08000
Definition at line 85 of file finfo.c.
OPT_GID
#define OPT_GID 0x00002
Definition at line 71 of file finfo.c.
OPT_INO
#define OPT_INO 0x00008
Definition at line 73 of file finfo.c.
OPT_LNKNAM
#define OPT_LNKNAM 0x00020
Definition at line 75 of file finfo.c.
OPT_MTIME
#define OPT_MTIME 0x00800
Definition at line 81 of file finfo.c.
OPT_NLINK
#define OPT_NLINK 0x00080
Definition at line 77 of file finfo.c.
OPT_OPERM
#define OPT_OPERM 0x20000
Definition at line 87 of file finfo.c.
OPT_PERM
#define OPT_PERM 0x00010
Definition at line 74 of file finfo.c.
OPT_PMASK
#define OPT_PMASK 0x10000
Definition at line 86 of file finfo.c.
OPT_RDEV
#define OPT_RDEV 0x00100
Definition at line 78 of file finfo.c.
OPT_SIZE
#define OPT_SIZE 0x00200
Definition at line 79 of file finfo.c.
OPT_UID
#define OPT_UID 0x00001
Definition at line 70 of file finfo.c.
OPTIONS
#define OPTIONS "acdgiflmnopsuACGMP:U"
Definition at line 91 of file finfo.c.
Function Documentation
finfo_builtin()
int finfo_builtin (WORD_LIST * list)
Definition at line 394 of file finfo.c.
 {
   int c, r;
   char **v;
   WORD_LIST *l;
   v = make_builtin_argv (list, &c);
   r = finfo_main (c, v);
   free (v);
   return r;
 }
References c, finfo_main(), free, make_builtin_argv(), and r.
finfo_main() [1/2]
static int finfo_main () static
Referenced by finfo_builtin().
finfo_main() [2/2]
static int finfo_main (int argc, char ** argv) static
Definition at line 106 of file finfo.c.
 {
     register int    i;
     int mode, flags, opt;
     sh_optind = 0;  /* XXX */
     prog = base_pathname(argv[0]);
     if (argc == 1) {
         builtin_usage();
         return(1);
     }
     flags = 0;
     while ((opt = sh_getopt(argc, argv, OPTIONS)) != EOF) {
         switch(opt) {
         case 'a': flags |= OPT_ATIME; break;
         case 'A': flags |= OPT_ATIME|OPT_ASCII; break;
         case 'c': flags |= OPT_CTIME; break;
         case 'C': flags |= OPT_CTIME|OPT_ASCII; break;
         case 'd': flags |= OPT_DEV; break;
         case 'i': flags |= OPT_INO; break;
         case 'f': flags |= OPT_FID; break;
         case 'g': flags |= OPT_GID; break;
         case 'G': flags |= OPT_GID|OPT_ASCII; break;
         case 'l': flags |= OPT_LNKNAM; break;
         case 'm': flags |= OPT_MTIME; break;
         case 'M': flags |= OPT_MTIME|OPT_ASCII; break;
         case 'n': flags |= OPT_NLINK; break;
         case 'o': flags |= OPT_OPERM; break;
         case 'p': flags |= OPT_PERM; break;
         case 'P': flags |= OPT_PMASK; pmask = octal(sh_optarg); break;
         case 's': flags |= OPT_SIZE; break;
         case 'u': flags |= OPT_UID; break;
         case 'U': flags |= OPT_UID|OPT_ASCII; break;
         default: builtin_usage (); return(1);
         }
     }
     argc -= sh_optind;
     argv += sh_optind;
     if (argc == 0) {
         builtin_usage();
         return(1);
     }
     for (i = 0; i < argc; i++)
         opt = flags ? printsome (argv[i], flags) : printfinfo(argv[i]);
     return(opt);
 }
References argc, argv, base_pathname(), builtin_usage(), EOF, flags, i, octal(), OPT_ASCII, OPT_ATIME, OPT_CTIME, OPT_DEV, OPT_FID, OPT_GID, OPT_INO, OPT_LNKNAM, OPT_MTIME, OPT_NLINK, OPT_OPERM, OPT_PERM, OPT_PMASK, OPT_SIZE, OPT_UID, OPTIONS, pmask, printfinfo(), printsome(), prog, sh_getopt(), sh_optarg, and sh_optind.
getperm()
static int getperm (int m) static
Definition at line 198 of file finfo.c.
 {
     return (m & (S_IRWXU|S_IRWXG|S_IRWXO|S_ISUID|S_ISGID));
 }
References S_IRWXG, S_IRWXO, S_IRWXU, S_ISGID, and S_ISUID.
Referenced by printmode(), and printsome().
getstat()
static struct stat* getstat (char * f) static
Definition at line 160 of file finfo.c.
 {
     static struct stat st;
     int fd, r;
     intmax_t lfd;
     if (strncmp(f, "/dev/fd/", 8) == 0) {
         if ((legal_number(f + 8, &lfd) == 0) || (int)lfd != lfd) {
             builtin_error("%s: invalid fd", f + 8);
             return ((struct stat *)0);
         }
         fd = lfd;
         r = fstat(fd, &st);
     } else
 #ifdef HAVE_LSTAT
         r = lstat(f, &st);
 #else
         r = stat(f, &st);
 #endif
     if (r < 0) {
         builtin_error("%s: cannot stat: %s", f, strerror(errno));
         return ((struct stat *)0);
     }
     return (&st);
 }
References builtin_error(), errno, f, fstat(), legal_number(), lstat, r, stat(), strerror(), and strncmp().
Referenced by printfinfo(), and printsome().
make_builtin_argv()
char** make_builtin_argv ()
Referenced by finfo_builtin().
octal()
static int octal (char * s) static
Definition at line 94 of file finfo.c.
 {
     int r;
     r = *s - '0';
     while (*++s >= '0' && *s <= '7')
         r = (r * 8) + (*s - '0');
     return r;
 }
References r.
Referenced by finfo_main().
perms() [1/2]
static void perms () static
Referenced by printmode(), and printsome().
perms() [2/2]
static void perms (int m) static
Definition at line 205 of file finfo.c.
 {
     char ubits[4], gbits[4], obits[4];  /* u=rwx,g=rwx,o=rwx */
     int i;
     i = 0;
     if (m & S_IRUSR)
         ubits[i++] = 'r';
     if (m & S_IWUSR)
         ubits[i++] = 'w';
     if (m & S_IXUSR)
         ubits[i++] = 'x';
     ubits[i] = '\0';
     i = 0;
     if (m & S_IRGRP)
         gbits[i++] = 'r';
     if (m & S_IWGRP)
         gbits[i++] = 'w';
     if (m & S_IXGRP)
         gbits[i++] = 'x';
     gbits[i] = '\0';
     i = 0;
     if (m & S_IROTH)
         obits[i++] = 'r';
     if (m & S_IWOTH)
         obits[i++] = 'w';
     if (m & S_IXOTH)
         obits[i++] = 'x';
     obits[i] = '\0';
     if (m & S_ISUID)
         ubits[2] = (m & S_IXUSR) ? 's' : 'S';
     if (m & S_ISGID)
         gbits[2] = (m & S_IXGRP) ? 's' : 'S';
     if (m & S_ISVTX)
         obits[2] = (m & S_IXOTH) ? 't' : 'T';
     printf ("u=%s,g=%s,o=%s", ubits, gbits, obits);
 }
References i, printf, S_IRGRP, S_IROTH, S_IRUSR, S_ISGID, S_ISUID, S_ISVTX, S_IWGRP, S_IWOTH, S_IWUSR, S_IXGRP, S_IXOTH, and S_IXUSR.
printfinfo() [1/2]
static int printfinfo () static
Referenced by finfo_main().
printfinfo() [2/2]
static int printfinfo (char * f) static
Definition at line 188 of file finfo.c.
 {
     struct stat *st;
     st = getstat(f);
     return (st ? printst(st) : 1);
 }
References f, getstat(), and printst().
printmode() [1/2]
static void printmode () static
Referenced by printst().
printmode() [2/2]
static void printmode (int mode) static
Definition at line 249 of file finfo.c.
 {
     if (S_ISBLK(mode))
         printf("S_IFBLK ");
     if (S_ISCHR(mode))
         printf("S_IFCHR ");
     if (S_ISDIR(mode))
         printf("S_IFDIR ");
     if (S_ISREG(mode))
         printf("S_IFREG ");
     if (S_ISFIFO(mode))
         printf("S_IFIFO ");
     if (S_ISLNK(mode))
         printf("S_IFLNK ");
     if (S_ISSOCK(mode))
         printf("S_IFSOCK ");
 #ifdef S_ISWHT
     if (S_ISWHT(mode))
         printf("S_ISWHT ");
 #endif
     perms(getperm(mode));
     printf("\n");
 }
References getperm(), perms(), printf, S_ISBLK, S_ISCHR, S_ISDIR, S_ISFIFO, S_ISLNK, S_ISREG, and S_ISSOCK.
printsome() [1/2]
static int printsome () static
Referenced by finfo_main().
printsome() [2/2]
static int printsome (char * f, int flags) static
Definition at line 312 of file finfo.c.
 {
     struct stat *st;
     struct passwd *pw;
     struct group *gr;
     int p;
     char    *b;
     st = getstat(f);
     if (st == NULL)
         return (1);
     /* Print requested info */
     if (flags & OPT_ATIME) {
         if (flags & OPT_ASCII)
             printf("%s", ctime(&st->st_atime));
         else
             printf("%ld\n", st->st_atime);
     } else if (flags & OPT_MTIME) {
         if (flags & OPT_ASCII)
             printf("%s", ctime(&st->st_mtime));
         else
             printf("%ld\n", st->st_mtime);
     } else if (flags & OPT_CTIME) {
         if (flags & OPT_ASCII)
             printf("%s", ctime(&st->st_ctime));
         else
             printf("%ld\n", st->st_ctime);
     } else if (flags & OPT_DEV)
         printf("%lu\n", (unsigned long)st->st_dev);
     else if (flags & OPT_INO)
         printf("%lu\n", (unsigned long)st->st_ino);
     else if (flags & OPT_FID)
         printf("%lu:%lu\n", (unsigned long)st->st_dev, (unsigned long)st->st_ino);
     else if (flags & OPT_NLINK)
         printf("%lu\n", (unsigned long)st->st_nlink);
     else if (flags & OPT_LNKNAM) {
 #ifdef S_ISLNK
         b = xmalloc(4096);
         p = readlink(f, b, 4096);
         if (p >= 0 && p < 4096)
             b[p] = '\0';
         else {
             p = errno;
             strcpy(b, prog);
             strcat(b, ": ");
             strcat(b, strerror(p));
         }
         printf("%s\n", b);
         free(b);
 #else
         printf("%s\n", f);
 #endif
     } else if (flags & OPT_PERM) {
         perms(st->st_mode);
         printf("\n");
     } else if (flags & OPT_OPERM)
         printf("%o\n", getperm(st->st_mode));
     else if (flags & OPT_PMASK)
         printf("%o\n", getperm(st->st_mode) & pmask);
     else if (flags & OPT_UID) {
         pw = getpwuid(st->st_uid);
         if (flags & OPT_ASCII)
             printf("%s\n", pw ? pw->pw_name : "unknown");
         else
             printf("%d\n", st->st_uid);
     } else if (flags & OPT_GID) {
         gr = getgrgid(st->st_gid);
         if (flags & OPT_ASCII)
             printf("%s\n", gr ? gr->gr_name : "unknown");
         else
             printf("%d\n", st->st_gid);
     } else if (flags & OPT_SIZE)
         printf("%ld\n", (long) st->st_size);
     return (0);
 }
References b, ctime(), errno, f, flags, free, getgrgid(), getperm(), getpwuid(), getstat(), gr, group::gr_name, NULL, OPT_ASCII, OPT_ATIME, OPT_CTIME, OPT_DEV, OPT_FID, OPT_GID, OPT_INO, OPT_LNKNAM, OPT_MTIME, OPT_NLINK, OPT_OPERM, OPT_PERM, OPT_PMASK, OPT_SIZE, OPT_UID, p, perms(), pmask, printf, prog, pw, passwd::pw_name, readlink(), strcat, strcpy, strerror(), and xmalloc.
printst() [1/2]
static int printst () static
Referenced by printfinfo().
printst() [2/2]
static int printst (struct stat * st) static
Definition at line 275 of file finfo.c.
 {
     struct passwd   *pw;
     struct group    *gr;
     char    *owner;
     int ma, mi, d;
     ma = major (st->st_rdev);
     mi = minor (st->st_rdev);
 #if defined (makedev)
     d = makedev (ma, mi);
 #else
     d = st->st_rdev & 0xFF;
 #endif
     printf("Device (major/minor): %d (%d/%d)\n", d, ma, mi);
     printf("Inode: %d\n", (int) st->st_ino);
     printf("Mode: (%o) ", (int) st->st_mode);
     printmode((int) st->st_mode);
     printf("Link count: %d\n", (int) st->st_nlink);
     pw = getpwuid(st->st_uid);
     owner = pw ? pw->pw_name : "unknown";
     printf("Uid of owner: %d (%s)\n", (int) st->st_uid, owner);
     gr = getgrgid(st->st_gid);
     owner = gr ? gr->gr_name : "unknown";
     printf("Gid of owner: %d (%s)\n", (int) st->st_gid, owner);
     printf("Device type: %d\n", (int) st->st_rdev);
     printf("File size: %ld\n", (long) st->st_size);
     printf("File last access time: %s", ctime (&st->st_atime));
     printf("File last modify time: %s", ctime (&st->st_mtime));
     printf("File last status change time: %s", ctime (&st->st_ctime));
     fflush(stdout);
     return(0);
 }
References ctime(), fflush(), getgrgid(), getpwuid(), gr, group::gr_name, major, makedev, minor, printf, printmode(), pw, passwd::pw_name, and stdout.
Variable Documentation
errno
int errno extern
Referenced by getstat(), and printsome().
finfo_doc
char* finfo_doc[] static
Initial value:
= {
  "Display information about file attributes.",
  "",
  "Display information about each FILE.  Only single operators should",
  "be supplied.  If no options are supplied, a summary of the info",
  "available about each FILE is printed.  If FILE is of the form",
  "/dev/fd/XX, file descriptor XX is described.  Operators, if supplied,",
  "have the following meanings:",
  "",
  " -a  last file access time",
  " -A  last file access time in ctime format",
  " -c  last file status change time",
  " -C  last file status change time in ctime format",
  " -m  last file modification time",
  " -M  last file modification time in ctime format",
  " -d  device",
  " -i  inode",
  " -f  composite file identifier (device:inode)",
  " -g  gid of owner",
  " -G  group name of owner",
  " -l  name of file pointed to by symlink",
  " -n  link count",
  " -o  permissions in octal",
  " -p  permissions in ascii",
  " -P mask permissions ANDed with MASK (like with umask)",
  " -s  file size in bytes",
  " -u  uid of owner",
  " -U  user name of owner",
  (char *)0
}
Definition at line 408 of file finfo.c.
finfo_struct
struct builtin finfo_struct
Initial value:
= {
    "finfo",
    finfo_builtin,
    BUILTIN_ENABLED,
    finfo_doc,
    "finfo [-acdgiflmnopsuACGMPU] file [file...]",
    0
}
Definition at line 408 of file finfo.c.
pmask
int pmask static
Definition at line 68 of file finfo.c.
Referenced by finfo_main(), and printsome().
prog
char* prog static
Definition at line 67 of file finfo.c.
Referenced by finfo_main(), and printsome().
sh_optarg
char* sh_optarg extern
Definition at line 39 of file getopt.c.
Referenced by finfo_main(), sh_getopt(), sh_getopt_restore_istate(), and sh_getopt_save_istate().
sh_optind
int sh_optind extern
Definition at line 54 of file getopt.c.
Referenced by finfo_main(), sh_getopt(), sh_getopt_restore_istate(), and sh_getopt_save_istate().
this_command_name
char* this_command_name extern
Definition at line 204 of file execute_cmd.c.
Referenced by builtin_error_prolog(), builtin_help(), builtin_usage(), do_assignment_statements(), evalerror(), main(), make_builtin_argv(), param_expand(), parameter_brace_casemod(), parameter_brace_patsub(), parameter_brace_remove_pattern(), parameter_brace_substring(), parameter_brace_transform(), and start_job().