Fennix: __cxxabiv1 Namespace Reference
__cxxabiv1 Namespace Reference
Data Structures
struct atexit_func_entry_t
struct __cxa_exception
Typedefs
typedef unsigned uarch_t
Functions
__cxa_eh_globals * __cxa_get_globals () noexcept
int __cxa_atexit (void(*f)(void *), void *objptr, void *dso)
void __cxa_finalize (void *f)
_Unwind_Reason_Code __gxx_personality_v0 (int version, _Unwind_Action actions, _Unwind_Exception_Class exception_class, _Unwind_Exception *ue_header, _Unwind_Context *context)
void * __cxa_begin_catch (void *thrown_object) noexcept
void __cxa_end_catch ()
static __always_inline size_t align_exception_allocation_size (size_t a, size_t b)
static __always_inline void INIT_EXCEPTION_CLASS (_Unwind_Exception_Class *c)
void unexpected_header_stub ()
void terminate_header_stub ()
void exception_cleanup_stub (_Unwind_Reason_Code Code, _Unwind_Exception *Exception)
void * __cxa_allocate_exception (size_t thrown_size) throw ()
__noreturn void __cxa_throw (void *thrown_object, std::type_info *tinfo, void(*dest)(void *))
void __cxa_rethrow ()
void __cxa_pure_virtual ()
void __cxa_throw_bad_array_new_length ()
void __cxa_free_exception (void *thrown_exception)
__extension__ typedef int __guard __attribute__ ((mode(__DI__)))
int __cxa_guard_acquire (__guard *g)
void __cxa_guard_release (__guard *g)
void __cxa_guard_abort (__guard *g)
__noreturn void __cxa_bad_typeid ()
template<typename T >
const T * adjust_pointer (const void *Base, ptrdiff_t Offset)
Variables
atexit_func_entry_t __atexit_funcs [ATEXIT_MAX_FUNCS]
uarch_t __atexit_func_count = 0
Typedef Documentation
uarch_t
typedef unsigned __cxxabiv1::uarch_t
Definition at line 29 of file cxxabi.h.
Function Documentation
__attribute__()
__extension__ typedef int __guard __cxxabiv1::__attribute__ ((mode(__DI__)))
__cxa_allocate_exception()
void* __cxxabiv1::__cxa_allocate_exception (size_t thrown_size) throw ()
Definition at line 170 of file cxxabi.cpp.
     {
         debug("Allocating exception of size %d.", thrown_size);
         size_t alloc_size = align_exception_allocation_size(thrown_size + sizeof(__cxa_exception), alignof(__cxa_exception));
         __cxa_exception *Exception = (__cxa_exception *)kmalloc(alloc_size);
         memset(Exception, 0, alloc_size);
         return Exception + 1;
     }
References align_exception_allocation_size(), debug, kmalloc, and memset.
__cxa_atexit()
int __cxxabiv1::__cxa_atexit (void(*)(void *) f, void * objptr, void * dso)
Parameters
f The destructor
objptr The object to be destructed
dso The DSO from which the object was obtained (unused in our case)
Returns
Zero on success, non-zero on failure
Definition at line 46 of file cxxabi.cpp.
     {
         if (KernelSymbolTable)
         {
             debug("Registering atexit function for \"%s\" with destructor \"%s\"",
                   KernelSymbolTable->GetSymbol((uintptr_t)objptr),
                   KernelSymbolTable->GetSymbol((uintptr_t)f));
         }
         else
         {
             debug("Registering atexit function for %p with destructor %p",
                   objptr, f);
         }
         if (__atexit_func_count >= ATEXIT_MAX_FUNCS)
             return -1;
         __atexit_funcs[__atexit_func_count].destructor_func = f;
         __atexit_funcs[__atexit_func_count].obj_ptr = objptr;
         __atexit_funcs[__atexit_func_count].dso_handle = dso;
         __atexit_func_count++;
         return 0;
     }
References __atexit_func_count, __atexit_funcs, ATEXIT_MAX_FUNCS, debug, __cxxabiv1::atexit_func_entry_t::destructor_func, __cxxabiv1::atexit_func_entry_t::dso_handle, f, SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, and __cxxabiv1::atexit_func_entry_t::obj_ptr.
__cxa_bad_typeid()
__noreturn void __cxxabiv1::__cxa_bad_typeid ()
Definition at line 246 of file cxxabi.cpp.
     {
         fixme("__cxa_bad_typeid() called.");
         CPU::Stop(); /* FIXME: Crash the system */
     }
References fixme, and CPU::Stop().
__cxa_begin_catch()
void* __cxxabiv1::__cxa_begin_catch (void * thrown_object) noexcept
Definition at line 111 of file cxxabi.cpp.
     {
         function("%p", thrown_object);
         __cxa_exception *Exception = (__cxa_exception *)thrown_object - 1;
         __cxa_eh_globals *Globals = __cxa_get_globals();
         Exception->handlerCount++;
         Globals->uncaughtExceptions--;
         Exception->nextException = Globals->caughtExceptions;
         Globals->caughtExceptions = Exception;
         return Exception + 1;
     }
References __cxa_get_globals(), __cxa_eh_globals::caughtExceptions, __cxxabiv1::__cxa_exception::handlerCount, __cxxabiv1::__cxa_exception::nextException, and __cxa_eh_globals::uncaughtExceptions.
Referenced by __cxa_throw().
__cxa_end_catch()
void __cxxabiv1::__cxa_end_catch ()
Definition at line 126 of file cxxabi.cpp.
     {
         fixme("__cxa_end_catch() called.");
     }
References fixme.
__cxa_finalize()
void __cxxabiv1::__cxa_finalize (void * f)
Definition at line 69 of file cxxabi.cpp.
     {
         function("%p", f);
         uarch_t i = __atexit_func_count;
         if (f == nullptr)
         {
             while (i--)
             {
                 if (__atexit_funcs[i].destructor_func)
                 {
                     if (KernelSymbolTable)
                     {
                         debug("Calling atexit function \"%s\"",
                               KernelSymbolTable->GetSymbol((uintptr_t)__atexit_funcs[i].destructor_func));
                     }
                     else
                     {
                         debug("Calling atexit function %p",
                               __atexit_funcs[i].destructor_func);
                     }
                     (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
                 }
             }
             return;
         }
         while (i--)
         {
             if (__atexit_funcs[i].destructor_func == f)
             {
                 (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
                 __atexit_funcs[i].destructor_func = 0;
             }
         }
     }
References __atexit_func_count, __atexit_funcs, debug, __cxxabiv1::atexit_func_entry_t::destructor_func, f, SymbolResolver::Symbols::GetSymbol(), i, and KernelSymbolTable.
__cxa_free_exception()
void __cxxabiv1::__cxa_free_exception (void * thrown_exception)
Definition at line 221 of file cxxabi.cpp.
     {
         fixme("__cxa_free_exception( %p ) called.",
               thrown_exception);
     }
References fixme.
__cxa_get_globals()
__cxa_eh_globals* __cxxabiv1::__cxa_get_globals () noexcept
Definition at line 35 of file cxxabi.cpp.
     {
         return &GetCurrentCPU()->EHGlobals;
     }
References CPUData::EHGlobals, and GetCurrentCPU().
Referenced by __cxa_begin_catch(), and __cxa_throw().
__cxa_guard_abort()
void __cxxabiv1::__cxa_guard_abort (__guard * g)
Definition at line 241 of file cxxabi.cpp.
     {
         fixme("__cxa_guard_abort( %p ) called.", g);
     }
References fixme, and g.
__cxa_guard_acquire()
int __cxxabiv1::__cxa_guard_acquire (__guard * g)
Definition at line 229 of file cxxabi.cpp.
     {
         fixme("__cxa_guard_acquire( %p ) called.", g);
         return !*(char *)(g);
     }
References fixme, and g.
__cxa_guard_release()
void __cxxabiv1::__cxa_guard_release (__guard * g)
Definition at line 235 of file cxxabi.cpp.
     {
         fixme("__cxa_guard_release( %p ) called.", g);
         *(char *)g = 1;
     }
References fixme, and g.
__cxa_pure_virtual()
void __cxxabiv1::__cxa_pure_virtual ()
Definition at line 211 of file cxxabi.cpp.
     {
         fixme("__cxa_pure_virtual() called.");
     }
References fixme.
__cxa_rethrow()
void __cxxabiv1::__cxa_rethrow ()
Definition at line 206 of file cxxabi.cpp.
     {
         fixme("__cxa_rethrow() called.");
     }
References fixme.
__cxa_throw()
__noreturn void __cxxabiv1::__cxa_throw (void * thrown_object, std::type_info * tinfo, void(*)(void *) dest)
Definition at line 180 of file cxxabi.cpp.
     {
         trace("Throwing exception of type \"%s\". ( object: %p, destructor: %p )",
               tinfo->name(), thrown_object, dest);
         __cxa_eh_globals *Globals = __cxa_get_globals();
         Globals->uncaughtExceptions++;
         __cxa_exception *Exception = (__cxa_exception *)thrown_object - 1;
         Exception->exceptionType = (std::type_info *)tinfo;
         Exception->exceptionDestructor = dest;
         Exception->unexpectedHandler = &unexpected_header_stub;
         Exception->terminateHandler = &terminate_header_stub;
         Exception->unwindHeader.exception_cleanup = &exception_cleanup_stub;
         INIT_EXCEPTION_CLASS(&Exception->unwindHeader.exception_class);
         Exception->adjustedPtr = thrown_object;
         _Unwind_RaiseException(&Exception->unwindHeader);
         __cxa_begin_catch(&Exception->unwindHeader);
         error("Uncaught exception!");
         CPU::Stop(); /* FIXME: Panic */
     }
References __cxa_begin_catch(), __cxa_get_globals(), _Unwind_RaiseException(), __cxxabiv1::__cxa_exception::adjustedPtr, error, _Unwind_Exception::exception_class, _Unwind_Exception::exception_cleanup, exception_cleanup_stub(), __cxxabiv1::__cxa_exception::exceptionDestructor, __cxxabiv1::__cxa_exception::exceptionType, INIT_EXCEPTION_CLASS(), CPU::Stop(), terminate_header_stub(), __cxxabiv1::__cxa_exception::terminateHandler, trace, __cxa_eh_globals::uncaughtExceptions, unexpected_header_stub(), __cxxabiv1::__cxa_exception::unexpectedHandler, and __cxxabiv1::__cxa_exception::unwindHeader.
__cxa_throw_bad_array_new_length()
void __cxxabiv1::__cxa_throw_bad_array_new_length ()
Definition at line 216 of file cxxabi.cpp.
     {
         fixme("__cxa_throw_bad_array_new_length() called.");
     }
References fixme.
__gxx_personality_v0()
_Unwind_Reason_Code __cxxabiv1::__gxx_personality_v0 (int version, _Unwind_Action actions, _Unwind_Exception_Class exception_class, _Unwind_Exception * ue_header, _Unwind_Context * context)
Definition at line 105 of file cxxabi.cpp.
     {
         fixme("__gxx_personality_v0( %d %p %p %p %p ) called.", version, actions, exception_class, ue_header, context);
         return _URC_NO_REASON;
     }
References _URC_NO_REASON, context, exception_class, and fixme.
adjust_pointer()
template<typename T > const T* __cxxabiv1::adjust_pointer (const void * Base, ptrdiff_t Offset) inline
Definition at line 24 of file si_class_type_info.cpp.
     {
         return reinterpret_cast<const T *>(reinterpret_cast<const char *>(Base) + Offset);
     }
References T.
align_exception_allocation_size()
static __always_inline size_t __cxxabiv1::align_exception_allocation_size (size_t a, size_t b) inline static
Definition at line 131 of file cxxabi.cpp.
     {
         return (a + b - 1) & ~(b - 1);
     }
Referenced by __cxa_allocate_exception().
exception_cleanup_stub()
void __cxxabiv1::exception_cleanup_stub (_Unwind_Reason_Code Code, _Unwind_Exception * Exception)
Definition at line 163 of file cxxabi.cpp.
     {
         fixme("exception_cleanup( %d %p ) called.",
               Code, Exception);
     }
References Code, and fixme.
Referenced by __cxa_throw().
INIT_EXCEPTION_CLASS()
static __always_inline void __cxxabiv1::INIT_EXCEPTION_CLASS (_Unwind_Exception_Class * c) inline static
Definition at line 136 of file cxxabi.cpp.
     {
         char *ptr = (char *)c;
         ptr[0] = 'G';
         ptr[1] = 'N';
         ptr[2] = 'U';
         ptr[3] = 'C';
         ptr[4] = 'C';
         ptr[5] = '+';
         ptr[6] = '+';
         ptr[7] = '\0';
     }
References c.
Referenced by __cxa_throw().
terminate_header_stub()
void __cxxabiv1::terminate_header_stub ()
Definition at line 151 of file cxxabi.cpp.
     {
         if (TaskManager && !TaskManager->IsPanic())
         {
             TaskManager->KillThread(thisThread, Tasking::KILL_CXXABI_EXCEPTION);
             TaskManager->Yield();
         }
         error("No task manager to kill thread!");
         CPU::Stop(); /* FIXME: Panic */
     }
References error, Tasking::Task::IsPanic(), Tasking::KILL_CXXABI_EXCEPTION, Tasking::Task::KillThread(), CPU::Stop(), TaskManager, thisThread, and Tasking::Task::Yield().
Referenced by __cxa_throw().
unexpected_header_stub()
void __cxxabiv1::unexpected_header_stub ()
Definition at line 149 of file cxxabi.cpp.
 { fixme("unexpected() called."); }
References fixme.
Referenced by __cxa_throw().
Variable Documentation
__atexit_func_count
uarch_t __cxxabiv1::__atexit_func_count = 0
Definition at line 33 of file cxxabi.cpp.
Referenced by __cxa_atexit(), and __cxa_finalize().
__atexit_funcs
atexit_func_entry_t __cxxabiv1::__atexit_funcs[ATEXIT_MAX_FUNCS]
Definition at line 32 of file cxxabi.cpp.
Referenced by __cxa_atexit(), and __cxa_finalize().