Fennix: Userspace/musl/src/locale/catgets.c File Reference
catgets.c File Reference
#include <nl_types.h>
#include <endian.h>
#include <stdlib.h>
#include <stdint.h>
#include <errno.h>
Macros
#define _BSD_SOURCE
#define V(p) be32toh(*(uint32_t *)(p))
Functions
static int cmp (const void *a, const void *b)
char * catgets (nl_catd catd, int set_id, int msg_id, const char *s)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file catgets.c.
V
#define V (p) be32toh(*(uint32_t *)(p))
Definition at line 8 of file catgets.c.
Function Documentation
catgets()
char* catgets (nl_catd catd, int set_id, int msg_id, const char * s)
Definition at line 16 of file catgets.c.
 {
     const char *map = (const char *)catd;
     uint32_t nsets = V(map+4);
     const char *sets = map+20;
     const char *msgs = map+20+V(map+12);
     const char *strings = map+20+V(map+16);
     uint32_t set_id_be = htobe32(set_id);
     uint32_t msg_id_be = htobe32(msg_id);
     const char *set = bsearch(&set_id_be, sets, nsets, 12, cmp);
     if (!set) {
         errno = ENOMSG;
         return (char *)s;
     }
     uint32_t nmsgs = V(set+4);
     msgs += 12*V(set+8);
     const char *msg = bsearch(&msg_id_be, msgs, nmsgs, 12, cmp);
     if (!msg) {
         errno = ENOMSG;
         return (char *)s;
     }
     return (char *)(strings + V(msg+8));
 }
References bsearch(), cmp(), ENOMSG, errno, htobe32, map, msgs, strings, and V.
cmp()
static int cmp (const void * a, const void * b) static
Definition at line 10 of file catgets.c.
 {
     uint32_t x = V(a), y = V(b);
     return x<y ? -1 : x>y ? 1 : 0;
 }
References V, x, and y.
Referenced by __qsort_r(), bsearch(), catgets(), qsort(), scandir(), sift(), tdelete(), tfind(), trinkle(), tsearch(), and wrapper_cmp().