Fennix: v0 Namespace Reference
v0 Namespace Reference
Typedefs
typedef int CriticalState
Functions
void KernelPrint (dev_t DriverID, const char *Format, va_list args)
void KernelLog (dev_t DriverID, const char *Format, va_list args)
CriticalState EnterCriticalSection (dev_t DriverID)
void LeaveCriticalSection (dev_t DriverID, CriticalState PreviousState)
int RegisterInterruptHandler (dev_t DriverID, uint8_t IRQ, void *Handler)
int OverrideInterruptHandler (dev_t DriverID, uint8_t IRQ, void *Handler)
int UnregisterInterruptHandler (dev_t DriverID, uint8_t IRQ, void *Handler)
int UnregisterAllInterruptHandlers (dev_t DriverID, void *Handler)
dev_t RegisterFileSystem (dev_t DriverID, FileSystemInfo *Info, struct Inode *Root)
int UnregisterFileSystem (dev_t DriverID, dev_t Device)
pid_t CreateKernelProcess (dev_t DriverID, const char *Name)
pid_t CreateKernelThread (dev_t DriverID, pid_t pId, const char *Name, void *EntryPoint, void *Argument)
pid_t GetCurrentProcess (dev_t DriverID)
int KillProcess (dev_t DriverID, pid_t pId, int ExitCode)
int KillThread (dev_t DriverID, pid_t tId, pid_t pId, int ExitCode)
void Yield (dev_t DriverID)
void Sleep (dev_t DriverID, uint64_t Milliseconds)
void PIC_EOI (dev_t DriverID, uint8_t IRQ)
void IRQ_MASK (dev_t DriverID, uint8_t IRQ)
void IRQ_UNMASK (dev_t DriverID, uint8_t IRQ)
void PS2Wait (dev_t DriverID, const bool Output)
void PS2WriteCommand (dev_t DriverID, uint8_t Command)
void PS2WriteData (dev_t DriverID, uint8_t Data)
uint8_t PS2ReadData (dev_t DriverID)
uint8_t PS2ReadStatus (dev_t DriverID)
uint8_t PS2ReadAfterACK (dev_t DriverID)
void PS2ClearOutputBuffer (dev_t DriverID)
int PS2ACKTimeout (dev_t DriverID)
void * AllocateMemory (dev_t DriverID, size_t Pages)
void FreeMemory (dev_t DriverID, void *Pointer, size_t Pages)
void * MemoryCopy (dev_t DriverID, void *Destination, const void *Source, size_t Length)
void * MemorySet (dev_t DriverID, void *Destination, int Value, size_t Length)
void * MemoryMove (dev_t DriverID, void *Destination, const void *Source, size_t Length)
size_t StringLength (dev_t DriverID, const char String[])
char * _strstr (dev_t DriverID, const char *Haystack, const char *Needle)
void MapPages (dev_t MajorID, void *PhysicalAddress, void *VirtualAddress, size_t Pages, uint32_t Flags)
void UnmapPages (dev_t MajorID, void *VirtualAddress, size_t Pages)
void AppendMapFlag (dev_t MajorID, void *Address, PageMapFlags Flag)
void RemoveMapFlag (dev_t MajorID, void *Address, PageMapFlags Flag)
void * Znwm (size_t Size)
void ZdlPvm (void *Pointer, size_t Size)
__PCIArray * GetPCIDevices (dev_t DriverID, uint16_t _Vendors[], uint16_t _Devices[])
void InitializePCI (dev_t DriverID, void *_Header)
uint32_t GetBAR (dev_t DriverID, uint8_t i, void *_Header)
uint8_t iLine (dev_t DriverID, PCIDevice *Device)
uint8_t iPin (dev_t DriverID, PCIDevice *Device)
dev_t RegisterDevice (dev_t DriverID, DeviceType Type, const InodeOperations *Operations)
int UnregisterDevice (dev_t DriverID, dev_t Device)
int ReportInputEvent (dev_t DriverID, InputReport *Report)
Typedef Documentation
CriticalState
typedef int v0::CriticalState
Definition at line 38 of file api.cpp.
Function Documentation
_strstr()
char* v0::_strstr (dev_t DriverID, const char * Haystack, const char * Needle)
Definition at line 486 of file api.cpp.
     {
         dbg_api("%d, %s, %s", DriverID, Haystack, Needle);
         return (char *)strstr(Haystack, Needle);
     }
References dbg_api, DriverID, and strstr().
AllocateMemory()
void* v0::AllocateMemory (dev_t DriverID, size_t Pages)
Definition at line 430 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, Pages);
         std::unordered_map<dev_t, Driver::DriverObject> &Drivers =
             DriverManager->GetDrivers();
         auto itr = Drivers.find(DriverID);
         assert(itr != Drivers.end());
         void *ptr = itr->second.vma->RequestPages(Pages);
         memset(ptr, 0, FROM_PAGES(Pages));
         return ptr;
     }
References assert, dbg_api, DriverID, DriverManager, Drivers, FROM_PAGES, Driver::Manager::GetDrivers(), and memset.
AppendMapFlag()
void v0::AppendMapFlag (dev_t MajorID, void * Address, PageMapFlags Flag)
Definition at line 509 of file api.cpp.
     {
         dbg_api("%d, %#lx, %d", MajorID, Address, Flag);
         Memory::Virtual vmm(KernelPageTable);
         vmm.GetPTE(Address)->raw |= Flag;
     }
References Address, dbg_api, Memory::Virtual::GetPTE(), KernelPageTable, and Memory::PageTableEntry::raw.
CreateKernelProcess()
pid_t v0::CreateKernelProcess (dev_t DriverID, const char * Name)
Definition at line 212 of file api.cpp.
     {
         dbg_api("%d, %s", DriverID, Name);
         Tasking::PCB *pcb = TaskManager->CreateProcess(nullptr, Name, Tasking::System,
                                                        true, 0, 0);
         return pcb->ID;
     }
References Tasking::Task::CreateProcess(), dbg_api, DriverID, Name, pcb, Tasking::System, and TaskManager.
CreateKernelThread()
pid_t v0::CreateKernelThread (dev_t DriverID, pid_t pId, const char * Name, void * EntryPoint, void * Argument)
Definition at line 222 of file api.cpp.
     {
         dbg_api("%d, %d, %s, %#lx, %#lx", DriverID, pId, Name, EntryPoint, Argument);
         Tasking::PCB *parent = TaskManager->GetProcessByID(pId);
         if (!parent)
             return -EINVAL;
         CriticalSection cs;
         Tasking::TCB *tcb = TaskManager->CreateThread(parent, (Tasking::IP)EntryPoint);
         if (Argument)
             tcb->SYSV_ABI_Call((uintptr_t)Argument);
         tcb->Rename(Name);
         return tcb->ID;
     }
References Tasking::Task::CreateThread(), dbg_api, DriverID, EINVAL, Tasking::Task::GetProcessByID(), Tasking::TCB::ID, Name, Tasking::TCB::Rename(), Tasking::TCB::SYSV_ABI_Call(), and TaskManager.
EnterCriticalSection()
CriticalState v0::EnterCriticalSection (dev_t DriverID)
Definition at line 58 of file api.cpp.
     {
         dbg_api("%d", DriverID);
         CriticalState cs;
 #if defined(__i386__) || defined(__x86_64__)
         uintptr_t Flags;
 #if defined(__x86_64__)
         asmv("pushfq");
         asmv("popq %0"
              : "=r"(Flags));
 #else
         asmv("pushfl");
         asmv("popl %0"
              : "=r"(Flags));
 #endif
         cs = Flags & (1 << 9);
         asmv("cli");
 #elif defined(__arm__) || defined(__aarch64__)
         uintptr_t Flags;
         asmv("mrs %0, cpsr"
              : "=r"(Flags));
         cs = Flags & (1 << 7);
         asmv("cpsid i");
 #endif
         return cs;
     }
References asmv(), dbg_api, DriverID, and Flags.
FreeMemory()
void v0::FreeMemory (dev_t DriverID, void * Pointer, size_t Pages)
Definition at line 445 of file api.cpp.
     {
         dbg_api("%d, %#lx, %d", DriverID, Pointer, Pages);
         std::unordered_map<dev_t, Driver::DriverObject> &Drivers =
             DriverManager->GetDrivers();
         auto itr = Drivers.find(DriverID);
         assert(itr != Drivers.end());
         itr->second.vma->FreePages(Pointer, Pages);
     }
References assert, dbg_api, DriverID, DriverManager, Drivers, and Driver::Manager::GetDrivers().
GetBAR()
uint32_t v0::GetBAR (dev_t DriverID, uint8_t i, void * _Header)
Definition at line 728 of file api.cpp.
     {
         dbg_api("%d, %d, %#lx", DriverID, i, _Header);
         PCI::PCIDevice *__device = (PCI::PCIDevice *)_Header;
         PCI::PCIDeviceHeader *Header = (PCI::PCIDeviceHeader *)__device->Header;
         switch (Header->HeaderType)
         {
         case 128:
             warn("Unknown header type %d! Guessing PCI Header 0",
                  Header->HeaderType);
             [[fallthrough]];
         case 0: /* PCI Header 0 */
         {
             PCI::PCIHeader0 *hdr0 =
                 (PCI::PCIHeader0 *)Header;
             switch (i)
             {
             case 0:
                 return hdr0->BAR0;
             case 1:
                 return hdr0->BAR1;
             case 2:
                 return hdr0->BAR2;
             case 3:
                 return hdr0->BAR3;
             case 4:
                 return hdr0->BAR4;
             case 5:
                 return hdr0->BAR5;
             default:
                 assert(!"Invalid BAR index");
             }
         }
         case 1: /* PCI Header 1 (PCI-to-PCI Bridge) */
         {
             PCI::PCIHeader1 *hdr1 =
                 (PCI::PCIHeader1 *)Header;
             switch (i)
             {
             case 0:
                 return hdr1->BAR0;
             case 1:
                 return hdr1->BAR1;
             default:
                 assert(!"Invalid BAR index");
             }
         }
         case 2: /* PCI Header 2 (PCI-to-CardBus Bridge) */
         {
             assert(!"PCI-to-CardBus Bridge not supported");
         }
         default:
             assert(!"Invalid PCI header type");
         }
     }
References assert, PCI::PCIHeader0::BAR0, PCI::PCIHeader1::BAR0, PCI::PCIHeader0::BAR1, PCI::PCIHeader1::BAR1, PCI::PCIHeader0::BAR2, PCI::PCIHeader0::BAR3, PCI::PCIHeader0::BAR4, PCI::PCIHeader0::BAR5, dbg_api, DriverID, PCI::PCIDevice::Header, PCI::PCIDeviceHeader::HeaderType, i, and warn.
Referenced by cxx_Initialize().
GetCurrentProcess()
pid_t v0::GetCurrentProcess (dev_t DriverID)
Definition at line 238 of file api.cpp.
     {
         dbg_api("%d", DriverID);
         return TaskManager->GetCurrentProcess()->ID;
     }
References dbg_api, DriverID, Tasking::Task::GetCurrentProcess(), Tasking::PCB::ID, and TaskManager.
GetPCIDevices()
__PCIArray* v0::GetPCIDevices (dev_t DriverID, uint16_t _Vendors[], uint16_t _Devices[])
Definition at line 541 of file api.cpp.
     {
         dbg_api("%d, %#lx, %#lx", DriverID, _Vendors, _Devices);
         std::unordered_map<dev_t, Driver::DriverObject> &Drivers =
             DriverManager->GetDrivers();
         auto itr = Drivers.find(DriverID);
         if (itr == Drivers.end())
             return nullptr;
         std::list<uint16_t> VendorIDs;
         for (int i = 0; _Vendors[i] != 0x0; i++)
             VendorIDs.push_back(_Vendors[i]);
         std::list<uint16_t> DeviceIDs;
         for (int i = 0; _Devices[i] != 0x0; i++)
             DeviceIDs.push_back(_Devices[i]);
         std::list<PCI::PCIDevice> Devices = PCIManager->FindPCIDevice(VendorIDs, DeviceIDs);
         if (Devices.empty())
             return nullptr;
         Memory::VirtualMemoryArea *vma = itr->second.vma;
         __PCIArray *head = nullptr;
         __PCIArray *array = nullptr;
         foreach (auto &dev in Devices)
         {
             /* TODO: optimize memory allocation */
             PCI::PCIDevice *dptr = (PCI::PCIDevice *)vma->RequestPages(TO_PAGES(sizeof(PCI::PCIDevice)));
             memcpy(dptr, &dev, sizeof(PCI::PCIDevice));
             __PCIArray *newArray = (__PCIArray *)vma->RequestPages(TO_PAGES(sizeof(__PCIArray)));
             if (unlikely(head == nullptr))
             {
                 head = newArray;
                 array = head;
             }
             else
             {
                 array->Next = newArray;
                 array = newArray;
             }
             array->Device = dptr;
             array->Next = nullptr;
             debug("Found %02x.%02x.%02x: %04x:%04x",
                   dev.Bus, dev.Device, dev.Function,
                   dev.Header->VendorID, dev.Header->DeviceID);
         }
         return head;
     }
References dbg_api, debug, __PCIArray::Device, Devices, DriverID, DriverManager, Drivers, PCI::Manager::FindPCIDevice(), Driver::Manager::GetDrivers(), head, i, memcpy, PCIManager, Memory::VirtualMemoryArea::RequestPages(), TO_PAGES, unlikely, and vma.
Referenced by cxx_Probe().
iLine()
uint8_t v0::iLine (dev_t DriverID, PCIDevice * Device)
Definition at line 786 of file api.cpp.
     {
         dbg_api("%d, %#lx", DriverID, Device);
         PCIHeader0 *Header = (PCIHeader0 *)Device->Header;
         return Header->InterruptLine;
     }
References dbg_api, and DriverID.
Referenced by cxx_Initialize().
InitializePCI()
void v0::InitializePCI (dev_t DriverID, void * _Header)
Definition at line 598 of file api.cpp.
     {
         dbg_api("%d, %#lx", DriverID, _Header);
         PCI::PCIDevice *__device = (PCI::PCIDevice *)_Header;
         PCI::PCIDeviceHeader *Header = (PCI::PCIDeviceHeader *)__device->Header;
         debug("Header Type: %d", Header->HeaderType);
         switch (Header->HeaderType)
         {
         case 128:
             warn("Unknown header type %d! Guessing PCI Header 0",
                  Header->HeaderType);
             [[fallthrough]];
         case 0: /* PCI Header 0 */
         {
             PCI::PCIHeader0 *hdr0 = (PCI::PCIHeader0 *)Header;
             uint32_t BAR[6];
             size_t BARsSize[6];
             BAR[0] = hdr0->BAR0;
             BAR[1] = hdr0->BAR1;
             BAR[2] = hdr0->BAR2;
             BAR[3] = hdr0->BAR3;
             BAR[4] = hdr0->BAR4;
             BAR[5] = hdr0->BAR5;
             debug("Type: %d; IOBase: %#lx; MemoryBase: %#lx",
                   BAR[0] & 1, BAR[1] & (~3), BAR[0] & (~15));
             /* BARs Size */
             for (short i = 0; i < 6; i++)
             {
                 if (BAR[i] == 0)
                     continue;
                 size_t size;
                 if ((BAR[i] & 1) == 0) /* Memory Base */
                 {
                     hdr0->BAR0 = 0xFFFFFFFF;
                     size = hdr0->BAR0;
                     hdr0->BAR0 = BAR[i];
                     BARsSize[i] = size & (~15);
                     BARsSize[i] = ~BARsSize[i] + 1;
                     BARsSize[i] = BARsSize[i] & 0xFFFFFFFF;
                     debug("BAR%d %#lx size: %d",
                           i, BAR[i], BARsSize[i]);
                 }
                 else if ((BAR[i] & 1) == 1) /* I/O Base */
                 {
                     hdr0->BAR1 = 0xFFFFFFFF;
                     size = hdr0->BAR1;
                     hdr0->BAR1 = BAR[i];
                     BARsSize[i] = size & (~3);
                     BARsSize[i] = ~BARsSize[i] + 1;
                     BARsSize[i] = BARsSize[i] & 0xFFFF;
                     debug("BAR%d %#lx size: %d",
                           i, BAR[i], BARsSize[i]);
                 }
             }
             Memory::Virtual vmm(KernelPageTable);
             /* Mapping the BARs */
             for (short i = 0; i < 6; i++)
             {
                 if (BAR[i] == 0)
                     continue;
                 if ((BAR[i] & 1) == 0) /* Memory Base */
                 {
                     uintptr_t BARBase = BAR[i] & (~15);
                     size_t BARSize = BARsSize[i];
                     debug("Mapping BAR%d %#lx-%#lx",
                           i, BARBase, BARBase + BARSize);
                     if (BARSize == 0)
                     {
                         warn("BAR%d size is zero!", i);
                         BARSize++;
                     }
                     vmm.Map((void *)BARBase, (void *)BARBase,
                             BARSize, Memory::RW | Memory::PWT | Memory::PCD);
                 }
                 else if ((BAR[i] & 1) == 1) /* I/O Base */
                 {
                     uintptr_t BARBase = BAR[i] & (~3);
                     size_t BARSize = BARsSize[i];
                     debug("Mapping BAR%d %#x-%#x",
                           i, BARBase, BARBase + BARSize);
                     if (BARSize == 0)
                     {
                         warn("BAR%d size is zero!", i);
                         BARSize++;
                     }
                     vmm.Map((void *)BARBase, (void *)BARBase,
                             BARSize, Memory::RW | Memory::PWT | Memory::PCD);
                 }
             }
             break;
         }
         case 1: /* PCI Header 1 (PCI-to-PCI Bridge) */
         {
             fixme("PCI Header 1 (PCI-to-PCI Bridge) not implemented yet");
             break;
         }
         case 2: /* PCI Header 2 (PCI-to-CardBus Bridge) */
         {
             fixme("PCI Header 2 (PCI-to-CardBus Bridge) not implemented yet");
             break;
         }
         default:
         {
             error("Unknown header type %d", Header->HeaderType);
             break;
         }
         }
         Header->Command |= PCI_COMMAND_MASTER |
                            PCI_COMMAND_IO |
                            PCI_COMMAND_MEMORY;
         Header->Command &= ~PCI_COMMAND_INTX_DISABLE;
     }
References PCI::PCIHeader0::BAR0, PCI::PCIHeader0::BAR1, PCI::PCIHeader0::BAR2, PCI::PCIHeader0::BAR3, PCI::PCIHeader0::BAR4, PCI::PCIHeader0::BAR5, PCI::PCIDeviceHeader::Command, dbg_api, debug, DriverID, error, fixme, PCI::PCIDevice::Header, PCI::PCIDeviceHeader::HeaderType, i, KernelPageTable, Memory::Virtual::Map(), Memory::PCD, PCI_COMMAND_INTX_DISABLE, PCI_COMMAND_IO, PCI_COMMAND_MASTER, PCI_COMMAND_MEMORY, Memory::PWT, Memory::RW, size, and warn.
Referenced by cxx_Initialize().
iPin()
uint8_t v0::iPin (dev_t DriverID, PCIDevice * Device)
Definition at line 794 of file api.cpp.
     {
         dbg_api("%d, %#lx", DriverID, Device);
         PCIHeader0 *Header = (PCIHeader0 *)Device->Header;
         return Header->InterruptPin;
     }
References dbg_api, and DriverID.
IRQ_MASK()
void v0::IRQ_MASK (dev_t DriverID, uint8_t IRQ)
Definition at line 292 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, IRQ);
         uint16_t port;
         uint8_t value;
         if (IRQ < 8)
             port = PIC1_DATA;
         else
         {
             port = PIC2_DATA;
             IRQ -= 8;
         }
         value = inb(port) | (1 << IRQ);
         outb(port, value);
     }
References dbg_api, DriverID, inb(), outb(), PIC1_DATA, PIC2_DATA, and value.
IRQ_UNMASK()
void v0::IRQ_UNMASK (dev_t DriverID, uint8_t IRQ)
Definition at line 311 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, IRQ);
         uint16_t port;
         uint8_t value;
         if (IRQ < 8)
             port = PIC1_DATA;
         else
         {
             port = PIC2_DATA;
             IRQ -= 8;
         }
         value = inb(port) & ~(1 << IRQ);
         outb(port, value);
     }
References dbg_api, DriverID, inb(), outb(), PIC1_DATA, PIC2_DATA, and value.
KernelLog()
void v0::KernelLog (dev_t DriverID, const char * Format, va_list args)
Definition at line 47 of file api.cpp.
     {
         dbg_api("%d, %s, %#lx", DriverID, Format, args);
         fctprintf(uart_wrapper, nullptr, "DRVER| %ld: ", DriverID);
         vfctprintf(uart_wrapper, nullptr, Format, args);
         uart_wrapper('\n', nullptr);
     }
References dbg_api, DriverID, fctprintf(), uart_wrapper(), and vfctprintf().
KernelPrint()
void v0::KernelPrint (dev_t DriverID, const char * Format, va_list args)
Definition at line 40 of file api.cpp.
     {
         dbg_api("%d, %s, %#lx", DriverID, Format, args);
         _KPrint(Format, args);
     }
References _KPrint(), dbg_api, and DriverID.
KillProcess()
int v0::KillProcess (dev_t DriverID, pid_t pId, int ExitCode)
Definition at line 245 of file api.cpp.
     {
         dbg_api("%d, %d, %d", DriverID, pId, ExitCode);
         Tasking::PCB *pcb = TaskManager->GetProcessByID(pId);
         if (!pcb)
             return -EINVAL;
         TaskManager->KillProcess(pcb, (Tasking::KillCode)ExitCode);
         return 0;
     }
References dbg_api, DriverID, EINVAL, Tasking::Task::GetProcessByID(), Tasking::Task::KillProcess(), pcb, and TaskManager.
KillThread()
int v0::KillThread (dev_t DriverID, pid_t tId, pid_t pId, int ExitCode)
Definition at line 256 of file api.cpp.
     {
         dbg_api("%d, %d, %d", DriverID, tId, ExitCode);
         Tasking::TCB *tcb = TaskManager->GetThreadByID(tId, TaskManager->GetProcessByID(pId));
         if (!tcb)
             return -EINVAL;
         TaskManager->KillThread(tcb, (Tasking::KillCode)ExitCode);
         return 0;
     }
References dbg_api, DriverID, EINVAL, Tasking::Task::GetProcessByID(), Tasking::Task::GetThreadByID(), Tasking::Task::KillThread(), and TaskManager.
LeaveCriticalSection()
void v0::LeaveCriticalSection (dev_t DriverID, CriticalState PreviousState)
Definition at line 92 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, PreviousState);
 #if defined(__i386__) || defined(__x86_64__)
         if (PreviousState)
             asmv("sti");
 #elif defined(__arm__) || defined(__aarch64__)
         if (PreviousState)
             asmv("cpsie i");
 #endif
     }
References asmv(), dbg_api, and DriverID.
MapPages()
void v0::MapPages (dev_t MajorID, void * PhysicalAddress, void * VirtualAddress, size_t Pages, uint32_t Flags)
Definition at line 493 of file api.cpp.
     {
         dbg_api("%d, %#lx, %#lx, %d, %d", MajorID, PhysicalAddress, VirtualAddress, Pages, Flags);
         Memory::Virtual vmm(KernelPageTable);
         vmm.Map(VirtualAddress, PhysicalAddress, Pages, Flags);
     }
References dbg_api, Flags, KernelPageTable, Memory::Virtual::Map(), and PhysicalAddress.
MemoryCopy()
void* v0::MemoryCopy (dev_t DriverID, void * Destination, const void * Source, size_t Length)
Definition at line 458 of file api.cpp.
     {
         dbg_api("%d, %#lx, %#lx, %d", DriverID, Destination, Source, Length);
         return memcpy(Destination, Source, Length);
     }
References dbg_api, DriverID, Length, and memcpy.
MemoryMove()
void* v0::MemoryMove (dev_t DriverID, void * Destination, const void * Source, size_t Length)
Definition at line 472 of file api.cpp.
     {
         dbg_api("%d, %#lx, %#lx, %d", DriverID, Destination, Source, Length);
         return memmove(Destination, Source, Length);
     }
References dbg_api, DriverID, Length, and memmove.
MemorySet()
void* v0::MemorySet (dev_t DriverID, void * Destination, int Value, size_t Length)
Definition at line 465 of file api.cpp.
     {
         dbg_api("%d, %#lx, %d, %d", DriverID, Destination, Value, Length);
         return memset(Destination, Value, Length);
     }
References dbg_api, DriverID, Length, and memset.
OverrideInterruptHandler()
int v0::OverrideInterruptHandler (dev_t DriverID, uint8_t IRQ, void * Handler)
Definition at line 129 of file api.cpp.
     {
         dbg_api("%d, %d, %#lx", DriverID, IRQ, Handler);
         debug("Overriding IRQ %d with %#lx", IRQ, Handler);
         std::unordered_map<dev_t, Driver::DriverObject> &drivers =
             DriverManager->GetDrivers();
         for (auto &var : drivers)
         {
             Driver::DriverObject *drv = &var.second;
             for (const auto &ih : *drv->InterruptHandlers)
             {
                 if (ih.first != IRQ)
                     continue;
                 debug("Removing IRQ %d: %#lx for %s", IRQ, (uintptr_t)ih.second, drv->Path.c_str());
                 Interrupts::RemoveHandler((void (*)(CPU::TrapFrame *))ih.second, IRQ);
                 drv->InterruptHandlers->erase(IRQ);
                 break;
             }
         }
         return RegisterInterruptHandler(DriverID, IRQ, Handler);
     }
References dbg_api, debug, DriverID, DriverManager, Driver::Manager::GetDrivers(), Driver::DriverObject::InterruptHandlers, Driver::DriverObject::Path, RegisterInterruptHandler(), and Interrupts::RemoveHandler().
PIC_EOI()
void v0::PIC_EOI (dev_t DriverID, uint8_t IRQ)
Definition at line 283 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, IRQ);
         if (IRQ >= 8)
             outb(PIC2_CMD, _PIC_EOI);
         outb(PIC1_CMD, _PIC_EOI);
     }
References _PIC_EOI, dbg_api, DriverID, outb(), PIC1_CMD, and PIC2_CMD.
PS2ACKTimeout()
int v0::PS2ACKTimeout (dev_t DriverID)
Definition at line 414 of file api.cpp.
     {
         dbg_api("%d", DriverID);
         int timeout = 0x500;
         while (timeout > 0)
         {
             if (PS2ReadData(DriverID) == PS2_ACK)
                 return 0;
             timeout--;
         }
         return -ETIMEDOUT;
     }
References dbg_api, DriverID, ETIMEDOUT, PS2_ACK, and PS2ReadData().
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), FinalizeKeyboard(), and InitializeKeyboard().
PS2ClearOutputBuffer()
void v0::PS2ClearOutputBuffer (dev_t DriverID)
Definition at line 399 of file api.cpp.
     {
         dbg_api("%d", DriverID);
         PS2_STATUSES Status;
         int timeout = 0x500;
         while (timeout--)
         {
             Status.Raw = inb(PS2_STATUS);
             if (Status.OutputBufferFull == 0)
                 return;
             inb(PS2_DATA);
         }
     }
References dbg_api, DriverID, inb(), PS2_DATA, PS2_STATUS, and PS2_STATUSES::Raw.
Referenced by DriverEntry(), and InitializeKeyboard().
PS2ReadAfterACK()
uint8_t v0::PS2ReadAfterACK (dev_t DriverID)
Definition at line 386 of file api.cpp.
     {
         dbg_api("%d", DriverID);
         uint8_t ret = PS2ReadData(DriverID);
         while (ret == PS2_ACK)
         {
             WaitOutput;
             ret = inb(PS2_DATA);
         }
         return ret;
     }
References dbg_api, DriverID, inb(), PS2_ACK, PS2_DATA, PS2ReadData(), ret, and WaitOutput.
Referenced by InitializeKeyboard().
PS2ReadData()
uint8_t v0::PS2ReadData (dev_t DriverID)
Definition at line 370 of file api.cpp.
     {
         dbg_api("%d", DriverID);
         WaitOutput;
         return inb(PS2_DATA);
     }
References dbg_api, DriverID, inb(), PS2_DATA, and WaitOutput.
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), DriverEntry(), InitializeMouse(), MouseSampleRate(), PS2ACKTimeout(), PS2MouseInterruptHandler(), and PS2ReadAfterACK().
PS2ReadStatus()
uint8_t v0::PS2ReadStatus (dev_t DriverID)
Definition at line 378 of file api.cpp.
     {
         dbg_api("%d", DriverID);
         WaitOutput;
         return inb(PS2_STATUS);
     }
References dbg_api, DriverID, inb(), PS2_STATUS, and WaitOutput.
PS2Wait()
void v0::PS2Wait (dev_t DriverID, const bool Output)
Definition at line 330 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, Output);
         int Timeout = 100000;
         PS2_STATUSES Status = {.Raw = inb(PS2_STATUS)};
         while (Timeout--)
         {
             if (!Output) /* FIXME: Reverse? */
             {
                 if (Status.OutputBufferFull == 0)
                     return;
             }
             else
             {
                 if (Status.InputBufferFull == 0)
                     return;
             }
             Status.Raw = inb(PS2_STATUS);
         }
         warn("PS/2 controller timeout! (Status: %#x, %d)", Status, Output);
     }
References dbg_api, DriverID, inb(), PS2_STATUS, PS2_STATUSES::Raw, and warn.
PS2WriteCommand()
void v0::PS2WriteCommand (dev_t DriverID, uint8_t Command)
Definition at line 354 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, Command);
         WaitInput;
         outb(PS2_CMD, Command);
     }
References dbg_api, DriverID, outb(), PS2_CMD, and WaitInput.
Referenced by DetectPS2Mouse(), DriverEntry(), DriverFinal(), DriverPanic(), FinalizeMouse(), InitializeMouse(), and MouseSampleRate().
PS2WriteData()
void v0::PS2WriteData (dev_t DriverID, uint8_t Data)
Definition at line 362 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, Data);
         WaitInput;
         outb(PS2_DATA, Data);
     }
References Data, dbg_api, DriverID, outb(), PS2_DATA, and WaitInput.
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), DriverEntry(), DriverFinal(), DriverPanic(), FinalizeKeyboard(), FinalizeMouse(), InitializeKeyboard(), InitializeMouse(), and MouseSampleRate().
RegisterDevice()
dev_t v0::RegisterDevice (dev_t DriverID, DeviceType Type, const InodeOperations * Operations)
Definition at line 804 of file api.cpp.
     {
         dbg_api("%d, %d, %#lx", DriverID, Type, Operations);
         return DriverManager->RegisterDevice(DriverID, Type, Operations);
     }
References dbg_api, DriverID, DriverManager, and Driver::Manager::RegisterDevice().
Referenced by cxx_Initialize(), DriverEntry(), InitializeKeyboard(), and InitializeMouse().
RegisterFileSystem()
dev_t v0::RegisterFileSystem (dev_t DriverID, FileSystemInfo * Info, struct Inode * Root)
Definition at line 196 of file api.cpp.
     {
         dbg_api("%d, %#lx, %#lx", DriverID, Info, Root);
         return fs->RegisterFileSystem(Info, Root);
     }
References dbg_api, DriverID, fs, and vfs::Virtual::RegisterFileSystem().
RegisterInterruptHandler()
int v0::RegisterInterruptHandler (dev_t DriverID, uint8_t IRQ, void * Handler)
Definition at line 109 of file api.cpp.
     {
         dbg_api("%d, %d, %#lx", DriverID, IRQ, Handler);
         std::unordered_map<dev_t, Driver::DriverObject> &drivers =
             DriverManager->GetDrivers();
         const auto it = drivers.find(DriverID);
         if (it == drivers.end())
             ReturnLogError(-EINVAL, "Driver %d not found", DriverID);
         const Driver::DriverObject *drv = &it->second;
         if (drv->InterruptHandlers->contains(IRQ))
             return -EEXIST;
         Interrupts::AddHandler((void (*)(CPU::TrapFrame *))Handler, IRQ);
         auto ih = drv->InterruptHandlers;
         ih->insert(std::pair<uint8_t, void *>(IRQ, Handler));
         return 0;
     }
References Interrupts::AddHandler(), dbg_api, DriverID, DriverManager, EEXIST, EINVAL, Driver::Manager::GetDrivers(), Driver::DriverObject::InterruptHandlers, it, and ReturnLogError.
Referenced by OverrideInterruptHandler().
RemoveMapFlag()
void v0::RemoveMapFlag (dev_t MajorID, void * Address, PageMapFlags Flag)
Definition at line 517 of file api.cpp.
     {
         dbg_api("%d, %#lx, %d", MajorID, Address, Flag);
         Memory::Virtual vmm(KernelPageTable);
         vmm.GetPTE(Address)->raw &= ~Flag;
     }
References Address, dbg_api, Memory::Virtual::GetPTE(), KernelPageTable, and Memory::PageTableEntry::raw.
ReportInputEvent()
int v0::ReportInputEvent (dev_t DriverID, InputReport * Report)
Definition at line 818 of file api.cpp.
     {
         dbg_api("%d, %#lx", DriverID, Report);
         return DriverManager->ReportInputEvent(DriverID, Report);
     }
References dbg_api, DriverID, DriverManager, and Driver::Manager::ReportInputEvent().
Referenced by InterruptHandler(), PS2MouseInterruptHandler(), and ReportKeyboardEvent().
Sleep()
void v0::Sleep (dev_t DriverID, uint64_t Milliseconds)
Definition at line 274 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, Milliseconds);
         TaskManager->Sleep(Milliseconds);
     }
References dbg_api, DriverID, Time::Milliseconds, Tasking::Task::Sleep(), and TaskManager.
StringLength()
size_t v0::StringLength (dev_t DriverID, const char String[])
Definition at line 479 of file api.cpp.
     {
         dbg_api("%d, %s", DriverID, String);
         return strlen(String);
     }
References dbg_api, DriverID, and strlen.
UnmapPages()
void v0::UnmapPages (dev_t MajorID, void * VirtualAddress, size_t Pages)
Definition at line 501 of file api.cpp.
     {
         dbg_api("%d, %#lx, %d", MajorID, VirtualAddress, Pages);
         Memory::Virtual vmm(KernelPageTable);
         vmm.Unmap(VirtualAddress, Pages);
     }
References dbg_api, KernelPageTable, and Memory::Virtual::Unmap().
UnregisterAllInterruptHandlers()
int v0::UnregisterAllInterruptHandlers (dev_t DriverID, void * Handler)
Definition at line 173 of file api.cpp.
     {
         dbg_api("%d, %#lx", DriverID, Handler);
         std::unordered_map<dev_t, Driver::DriverObject> &drivers =
             DriverManager->GetDrivers();
         const auto it = drivers.find(DriverID);
         if (it == drivers.end())
             ReturnLogError(-EINVAL, "Driver %d not found", DriverID);
         const Driver::DriverObject *drv = &it->second;
         for (auto &i : *drv->InterruptHandlers)
         {
             Interrupts::RemoveHandler((void (*)(CPU::TrapFrame *))Handler, i.first);
             debug("Removed IRQ %d: %#lx for %s", i.first, (uintptr_t)Handler, drv->Path.c_str());
         }
         auto ih = drv->InterruptHandlers;
         ih->clear();
         return 0;
     }
References dbg_api, debug, DriverID, DriverManager, EINVAL, Driver::Manager::GetDrivers(), i, Driver::DriverObject::InterruptHandlers, it, Driver::DriverObject::Path, Interrupts::RemoveHandler(), and ReturnLogError.
UnregisterDevice()
int v0::UnregisterDevice (dev_t DriverID, dev_t Device)
Definition at line 811 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, Device);
         return DriverManager->UnregisterDevice(DriverID, Device);
     }
References dbg_api, DriverID, DriverManager, and Driver::Manager::UnregisterDevice().
Referenced by cxx_Finalize(), DriverFinal(), FinalizeKeyboard(), and FinalizeMouse().
UnregisterFileSystem()
int v0::UnregisterFileSystem (dev_t DriverID, dev_t Device)
Definition at line 203 of file api.cpp.
     {
         dbg_api("%d, %d", DriverID, Device);
         return fs->UnregisterFileSystem(Device);
     }
References dbg_api, DriverID, fs, and vfs::Virtual::UnregisterFileSystem().
UnregisterInterruptHandler()
int v0::UnregisterInterruptHandler (dev_t DriverID, uint8_t IRQ, void * Handler)
Definition at line 156 of file api.cpp.
     {
         dbg_api("%d, %d, %#lx", DriverID, IRQ, Handler);
         std::unordered_map<dev_t, Driver::DriverObject> &drivers =
             DriverManager->GetDrivers();
         const auto it = drivers.find(DriverID);
         if (it == drivers.end())
             ReturnLogError(-EINVAL, "Driver %d not found", DriverID);
         const Driver::DriverObject *drv = &it->second;
         Interrupts::RemoveHandler((void (*)(CPU::TrapFrame *))Handler, IRQ);
         auto ih = drv->InterruptHandlers;
         ih->erase(IRQ);
         return 0;
     }
References dbg_api, DriverID, DriverManager, EINVAL, Driver::Manager::GetDrivers(), Driver::DriverObject::InterruptHandlers, it, Interrupts::RemoveHandler(), and ReturnLogError.
Yield()
void v0::Yield (dev_t DriverID)
Definition at line 267 of file api.cpp.
     {
         dbg_api("%d", DriverID);
         TaskManager->Yield();
     }
References dbg_api, DriverID, TaskManager, and Tasking::Task::Yield().
ZdlPvm()
void v0::ZdlPvm (void * Pointer, size_t Size)
Definition at line 532 of file api.cpp.
     {
         dbg_api("%d, %#lx", Pointer, Size);
         free(Pointer);
     }
References dbg_api, free, and Driver::Size.
Znwm()
void* v0::Znwm (size_t Size)
Definition at line 525 of file api.cpp.
     {
         dbg_api("%d", Size);
         return malloc(Size);
     }
References dbg_api, malloc, and Driver::Size.