Fennix: Userspace/apps/base/bash/lib/glob/glob.c File Reference
glob.c File Reference
#include <config.h>
#include "bashtypes.h"
#include "bashansi.h"
#include "posixdir.h"
#include "posixstat.h"
#include "shmbutil.h"
#include "xmalloc.h"
#include "filecntl.h"
#include "stdc.h"
#include "memalloc.h"
#include <signal.h>
#include "shell.h"
#include "general.h"
#include "glob.h"
#include "strmatch.h"
#include "glob_loop.c"
Data Structures
struct globval
Macros
#define F_OK 0
#define bcopy(s, d, n) ((void) memcpy ((d), (s), (n)))
#define NULL 0x0
#define FREE(x) if (x) free (x)
#define ALLOCA_MAX 100000
#define dequote_pathname(p) udequote_pathname(p)
#define GCHAR unsigned char
#define CHAR char
#define INT int
#define L(CS) CS
#define INTERNAL_GLOB_PATTERN_P internal_glob_pattern_p
#define GLOB_TESTNAME(name) (sh_eaccess (name, F_OK))
#define NULL_PLACEHOLDER(x) ((x) && *(x) && **(x) == 0)
Functions
void throw_to_top_level PARAMS ((void))
int sh_eaccess PARAMS ((const char *, int))
char *sh_makepath PARAMS ((const char *, const char *, int))
int signal_is_pending PARAMS ((int))
static int skipname PARAMS ((char *, char *, int))
void udequote_pathname PARAMS ((char *))
static int glob_testdir PARAMS ((char *, int))
static char **glob_dir_to_array PARAMS ((char *, char **, int))
wchar_t *glob_patscan_wc PARAMS ((wchar_t *, wchar_t *, int))
int wextglob_pattern_p PARAMS ((wchar_t *))
int glob_pattern_p (char *pattern) const
static int skipname (char *pat, char *dname, int flags)
void udequote_pathname (char *pathname)
static int glob_testdir (char *dir, int flags)
static struct globval * finddirs (char *pat, char *sdir, int flags, struct globval **ep, int *np)
char ** glob_vector (char *pat, char *dir, int flags)
static char ** glob_dir_to_array (char *dir, char **array, int flags)
char ** glob_filename (char *pathname, int flags)
Variables
int extended_glob
int noglob_dot_filenames = 1
int glob_ignore_case = 0
int glob_always_skip_dot_and_dotdot = 1
char * glob_error_return
static struct globval finddirs_error_return
Data Structure Documentation
globval
struct globval
Definition at line 81 of file glob.c.
Data Fields
char * name
struct globval * next
Macro Definition Documentation
ALLOCA_MAX
#define ALLOCA_MAX 100000
Definition at line 78 of file glob.c.
bcopy
#define bcopy (s, d, n) ((void) memcpy ((d), (s), (n)))
Definition at line 60 of file glob.c.
CHAR
#define CHAR char
Definition at line 140 of file glob.c.
dequote_pathname
#define dequote_pathname (p) udequote_pathname(p)
Definition at line 124 of file glob.c.
F_OK
#define F_OK 0
Definition at line 45 of file glob.c.
FREE
#define FREE (x) if (x) free (x)
Definition at line 72 of file glob.c.
GCHAR
#define GCHAR unsigned char
Definition at line 139 of file glob.c.
GLOB_TESTNAME
#define GLOB_TESTNAME (name) (sh_eaccess (name, F_OK))
Definition at line 557 of file glob.c.
INT
#define INT int
Definition at line 141 of file glob.c.
INTERNAL_GLOB_PATTERN_P
#define INTERNAL_GLOB_PATTERN_P internal_glob_pattern_p
Definition at line 143 of file glob.c.
L
#define L (CS) CS
Definition at line 142 of file glob.c.
NULL
#define NULL 0x0
Definition at line 67 of file glob.c.
NULL_PLACEHOLDER
#define NULL_PLACEHOLDER (x) ((x) && *(x) && **(x) == 0)
Function Documentation
finddirs()
static struct globval* finddirs (char * pat, char * sdir, int flags, struct globval ** ep, int * np) static
Definition at line 599 of file glob.c.
 {
   char **r, *n;
   int ndirs;
   struct globval *ret, *e, *g;
 /*itrace("finddirs: pat = `%s' sdir = `%s' flags = 0x%x", pat, sdir, flags);*/
   e = ret = 0;
   r = glob_vector (pat, sdir, flags);
   if (r == 0 || r[0] == 0)
     {
       if (np)
     *np = 0;
       if (ep)
         *ep = 0;
       if (r && r != &glob_error_return)
     free (r);
       return (struct globval *)0;
     }
   for (ndirs = 0; r[ndirs] != 0; ndirs++)
     {
       g = (struct globval *) malloc (sizeof (struct globval));
       if (g == 0)
     {
       while (ret)       /* free list built so far */
         {
           g = ret->next;
           free (ret);
           ret = g;
         }
       free (r);
       if (np)
         *np = 0;
       if (ep)
         *ep = 0;
       return (&finddirs_error_return);
     }
       if (e == 0)
     e = g;
       g->next = ret;
       ret = g;
       g->name = r[ndirs];
     }
   free (r);
   if (ep)
     *ep = e;
   if (np)
     *np = ndirs;
   return ret;
 }
References finddirs_error_return, flags, free, g, glob_error_return, glob_vector(), malloc, n, globval::next, and pat.
Referenced by glob_vector().
glob_dir_to_array()
static char** glob_dir_to_array (char * dir, char ** array, int flags) static
Definition at line 1062 of file glob.c.
 {
   register unsigned int i, l;
   int add_slash;
   char **result, *new;
   struct stat sb;
   l = strlen (dir);
   if (l == 0)
     {
       if (flags & GX_MARKDIRS)
     for (i = 0; array[i]; i++)
       {
         if ((stat (array[i], &sb) == 0) && S_ISDIR (sb.st_mode))
           {
         l = strlen (array[i]);
         new = (char *)realloc (array[i], l + 2);
         if (new == 0)
           return NULL;
         new[l] = '/';
         new[l+1] = '\0';
         array[i] = new;
           }
       }
       return (array);
     }
   add_slash = dir[l - 1] != '/';
   i = 0;
   while (array[i] != NULL)
     ++i;
   result = (char **) malloc ((i + 1) * sizeof (char *));
   if (result == NULL)
     return (NULL);
   for (i = 0; array[i] != NULL; i++)
     {
       /* 3 == 1 for NUL, 1 for slash at end of DIR, 1 for GX_MARKDIRS */
       result[i] = (char *) malloc (l + strlen (array[i]) + 3);
       if (result[i] == NULL)
     {
       int ind;
       for (ind = 0; ind < i; ind++)
         free (result[ind]);
       free (result);
       return (NULL);
     }
       strcpy (result[i], dir);
       if (add_slash)
     result[i][l] = '/';
       if (array[i][0])
     {
       strcpy (result[i] + l + add_slash, array[i]);
       if (flags & GX_MARKDIRS)
         {
           if ((stat (result[i], &sb) == 0) && S_ISDIR (sb.st_mode))
         {
           size_t rlen;
           rlen = strlen (result[i]);
           result[i][rlen] = '/';
           result[i][rlen+1] = '\0';
         }
         }
     }
       else
         result[i][l+add_slash] = '\0';
     }
   result[i] = NULL;
   /* Free the input array.  */
   for (i = 0; array[i] != NULL; i++)
     free (array[i]);
   free ((char *) array);
   return (result);
 }
References dir, flags, free, GX_MARKDIRS, i, l, malloc, NULL, realloc, S_ISDIR, stat::st_mode, strcpy, and strlen.
Referenced by glob_filename().
glob_filename()
char** glob_filename (char * pathname, int flags)
Definition at line 1151 of file glob.c.
 {
   char **result, **new_result;
   unsigned int result_size;
   char *directory_name, *filename, *dname, *fn;
   unsigned int directory_len;
   int free_dirname;         /* flag */
   int dflags, hasglob;
   result = (char **) malloc (sizeof (char *));
   result_size = 1;
   if (result == NULL)
     return (NULL);
   result[0] = NULL;
   directory_name = NULL;
   /* Find the filename.  */
   filename = strrchr (pathname, '/');
 #if defined (EXTENDED_GLOB)
   if (filename && extended_glob)
     {
       fn = glob_dirscan (pathname, '/');
 #if DEBUG_MATCHING
       if (fn != filename)
     fprintf (stderr, "glob_filename: glob_dirscan: fn (%s) != filename (%s)\n", fn ? fn : "(null)", filename);
 #endif
       filename = fn;
     }
 #endif
   if (filename == NULL)
     {
       filename = pathname;
       directory_name = "";
       directory_len = 0;
       free_dirname = 0;
     }
   else
     {
       directory_len = (filename - pathname) + 1;
       directory_name = (char *) malloc (directory_len + 1);
       if (directory_name == 0)      /* allocation failed? */
     {
       free (result);
       return (NULL);
     }
       bcopy (pathname, directory_name, directory_len);
       directory_name[directory_len] = '\0';
       ++filename;
       free_dirname = 1;
     }
   hasglob = 0;
   /* If directory_name contains globbing characters, then we
      have to expand the previous levels.  Just recurse.
      If glob_pattern_p returns != [0,1] we have a pattern that has backslash
      quotes but no unquoted glob pattern characters. We dequote it below. */
   if (directory_len > 0 && (hasglob = glob_pattern_p (directory_name)) == 1)
     {
       char **directories, *d, *p;
       register unsigned int i;
       int all_starstar, last_starstar;
       all_starstar = last_starstar = 0;
       d = directory_name;
       dflags = flags & ~GX_MARKDIRS;
       /* Collapse a sequence of ** patterns separated by one or more slashes
      to a single ** terminated by a slash or NUL */
       if ((flags & GX_GLOBSTAR) && d[0] == '*' && d[1] == '*' && (d[2] == '/' || d[2] == '\0'))
     {
       p = d;
       while (d[0] == '*' && d[1] == '*' && (d[2] == '/' || d[2] == '\0'))
         {
           p = d;
           if (d[2])
         {
           d += 3;
           while (*d == '/')
             d++;
           if (*d == 0)
             break;
         }
         }
       if (*d == 0)
         all_starstar = 1;
       d = p;
       dflags |= GX_ALLDIRS|GX_ADDCURDIR;
       directory_len = strlen (d);
     }
       /* If there is a non [star][star]/ component in directory_name, we
      still need to collapse trailing sequences of [star][star]/ into
      a single one and note that the directory name ends with [star][star],
      so we can compensate if filename is [star][star] */
       if ((flags & GX_GLOBSTAR) && all_starstar == 0)
     {
       int dl, prev;
       prev = dl = directory_len;
       while (dl >= 4 && d[dl - 1] == '/' &&
                d[dl - 2] == '*' &&
                d[dl - 3] == '*' &&
                d[dl - 4] == '/')
         prev = dl, dl -= 3;
       if (dl != directory_len)
         last_starstar = 1;
       directory_len = prev;
     }
       /* If the directory name ends in [star][star]/ but the filename is
      [star][star], just remove the final [star][star] from the directory
      so we don't have to scan everything twice. */
       if (last_starstar && directory_len > 4 &&
         filename[0] == '*' && filename[1] == '*' && filename[2] == 0)
     {
       directory_len -= 3;
     }
       if (d[directory_len - 1] == '/')
     d[directory_len - 1] = '\0';
       directories = glob_filename (d, dflags|GX_RECURSE);
       if (free_dirname)
     {
       free (directory_name);
       directory_name = NULL;
     }
       if (directories == NULL)
     goto memory_error;
       else if (directories == (char **)&glob_error_return)
     {
       free ((char *) result);
       return ((char **) &glob_error_return);
     }
       else if (*directories == NULL)
     {
       free ((char *) directories);
       free ((char *) result);
       return ((char **) &glob_error_return);
     }
       /* If we have something like [star][star]/[star][star], it's no use to
          glob **, then do it again, and throw half the results away.  */
       if (all_starstar && filename[0] == '*' && filename[1] == '*' && filename[2] == 0)
     {
       free ((char *) directories);
       free (directory_name);
       directory_name = NULL;
       directory_len = 0;
       goto only_filename;
     }
       /* We have successfully globbed the preceding directory name.
      For each name in DIRECTORIES, call glob_vector on it and
      FILENAME.  Concatenate the results together.  */
       for (i = 0; directories[i] != NULL; ++i)
     {
       char **temp_results;
       int shouldbreak;
       shouldbreak = 0;
       /* XXX -- we've recursively scanned any directories resulting from
          a `**', so turn off the flag.  We turn it on again below if
          filename is `**' */
       /* Scan directory even on a NULL filename.  That way, `*h/'
          returns only directories ending in `h', instead of all
          files ending in `h' with a `/' appended. */
       dname = directories[i];
       dflags = flags & ~(GX_MARKDIRS|GX_ALLDIRS|GX_ADDCURDIR);
       /* last_starstar? */
       if ((flags & GX_GLOBSTAR) && filename[0] == '*' && filename[1] == '*' && filename[2] == '\0')
         dflags |= GX_ALLDIRS|GX_ADDCURDIR;
       if (dname[0] == '\0' && filename[0])
         {
           dflags |= GX_NULLDIR;
           dname = ".";  /* treat null directory name and non-null filename as current directory */
         }
       /* Special handling for symlinks to directories with globstar on */
       if (all_starstar && (dflags & GX_NULLDIR) == 0)
         {
           int dlen;
           /* If we have a directory name that is not null (GX_NULLDIR above)
          and is a symlink to a directory, we return the symlink if
          we're not `descending' into it (filename[0] == 0) and return
          glob_error_return (which causes the code below to skip the
          name) otherwise. I should fold this into a test that does both
          checks instead of calling stat twice. */
           if (glob_testdir (dname, flags|GX_ALLDIRS) == -2 && glob_testdir (dname, 0) == 0)
         {
           if (filename[0] != 0)
             temp_results = (char **)&glob_error_return;     /* skip */
           else
             {
               /* Construct array to pass to glob_dir_to_array */
               temp_results = (char **)malloc (2 * sizeof (char *));
               if (temp_results == NULL)
             goto memory_error;
               temp_results[0] = (char *)malloc (1);
               if (temp_results[0] == 0)
             {
               free (temp_results);
               goto memory_error;
             }
               **temp_results = '\0';
               temp_results[1] = NULL;
               dflags |= GX_SYMLINK; /* mostly for debugging */
             }
         }
           else
         temp_results = glob_vector (filename, dname, dflags);
         }
       else
         temp_results = glob_vector (filename, dname, dflags);
       /* Handle error cases. */
       if (temp_results == NULL)
         goto memory_error;
       else if (temp_results == (char **)&glob_error_return)
         /* This filename is probably not a directory.  Ignore it.  */
         ;
       else
         {
           char **array;
           register unsigned int l;
           /* If we're expanding **, we don't need to glue the directory
          name to the results; we've already done it in glob_vector */
           if ((dflags & GX_ALLDIRS) && filename[0] == '*' && filename[1] == '*' && (filename[2] == '\0' || filename[2] == '/'))
         {
           /* When do we remove null elements from temp_results?  And
              how to avoid duplicate elements in the final result? */
           /* If (dflags & GX_NULLDIR) glob_filename potentially left a
              NULL placeholder in the temp results just in case
              glob_vector/glob_dir_to_array did something with it, but
              if it didn't, and we're not supposed to be passing them
              through for some reason ((flags & GX_NULLDIR) == 0) we
              need to remove all the NULL elements from the beginning
              of TEMP_RESULTS. */
           /* If we have a null directory name and ** as the filename,
              we have just searched for everything from the current
              directory on down. Break now (shouldbreak = 1) to avoid
              duplicate entries in the final result. */
 #define NULL_PLACEHOLDER(x) ((x) && *(x) && **(x) == 0)
           if ((dflags & GX_NULLDIR) && (flags & GX_NULLDIR) == 0 &&
             NULL_PLACEHOLDER (temp_results))
 #undef NULL_PLACEHOLDER
             {
               register int i, n;
               for (n = 0; temp_results[n] && *temp_results[n] == 0; n++)
             ;
               i = n;
               do
             temp_results[i - n] = temp_results[i];
               while (temp_results[i++] != 0);
               array = temp_results;
               shouldbreak = 1;
             }
               else
             array = temp_results;
         }
           else if (dflags & GX_SYMLINK)
         array = glob_dir_to_array (directories[i], temp_results, flags);
           else
         array = glob_dir_to_array (directories[i], temp_results, flags);
           l = 0;
           while (array[l] != NULL)
         ++l;
           new_result = (char **)realloc (result, (result_size + l) * sizeof (char *));
           if (new_result == NULL)
         {
           for (l = 0; array[l]; ++l)
             free (array[l]);
           free ((char *)array);
           goto memory_error;
         }
           result = new_result;
           for (l = 0; array[l] != NULL; ++l)
         result[result_size++ - 1] = array[l];
           result[result_size - 1] = NULL;
           /* Note that the elements of ARRAY are not freed.  */
           if (array != temp_results)
         free ((char *) array);
           else if ((dflags & GX_ALLDIRS) && filename[0] == '*' && filename[1] == '*' && filename[2] == '\0')
         free (temp_results);    /* expanding ** case above */
           if (shouldbreak)
         break;
         }
     }
       /* Free the directories.  */
       for (i = 0; directories[i]; i++)
     free (directories[i]);
       free ((char *) directories);
       return (result);
     }
 only_filename:
   /* If there is only a directory name, return it. */
   if (*filename == '\0')
     {
       result = (char **) realloc ((char *) result, 2 * sizeof (char *));
       if (result == NULL)
     {
       if (free_dirname)
         free (directory_name);
       return (NULL);
     }
       /* If we have a directory name with quoted characters, and we are
      being called recursively to glob the directory portion of a pathname,
      we need to dequote the directory name before returning it so the
      caller can read the directory */
       if (directory_len > 0 && hasglob == 2 && (flags & GX_RECURSE) != 0)
     {
       dequote_pathname (directory_name);
       directory_len = strlen (directory_name);
     }
       /* We could check whether or not the dequoted directory_name is a
      directory and return it here, returning the original directory_name
      if not, but we don't do that. We do return the dequoted directory
      name if we're not being called recursively and the dequoted name
      corresponds to an actual directory. For better backwards compatibility,
      we can return &glob_error_return unconditionally in this case. */
       if (directory_len > 0 && hasglob == 2 && (flags & GX_RECURSE) == 0)
     {
       dequote_pathname (directory_name);
       if (glob_testdir (directory_name, 0) < 0)
         {
           if (free_dirname)
         free (directory_name);
           free ((char *) result);
           return ((char **)&glob_error_return);
         }
     }
       /* Handle GX_MARKDIRS here. */
       result[0] = (char *) malloc (directory_len + 1);
       if (result[0] == NULL)
     goto memory_error;
       bcopy (directory_name, result[0], directory_len + 1);
       if (free_dirname)
     free (directory_name);
       result[1] = NULL;
       return (result);
     }
   else
     {
       char **temp_results;
       /* There are no unquoted globbing characters in DIRECTORY_NAME.
      Dequote it before we try to open the directory since there may
      be quoted globbing characters which should be treated verbatim. */
       if (directory_len > 0)
     dequote_pathname (directory_name);
       /* We allocated a small array called RESULT, which we won't be using.
      Free that memory now. */
       free (result);
       /* Just return what glob_vector () returns appended to the
      directory name. */
       /* If flags & GX_ALLDIRS, we're called recursively */
       dflags = flags & ~GX_MARKDIRS;
       if (directory_len == 0)
     dflags |= GX_NULLDIR;
       if ((flags & GX_GLOBSTAR) && filename[0] == '*' && filename[1] == '*' && filename[2] == '\0')
     {
       dflags |= GX_ALLDIRS|GX_ADDCURDIR;
 #if 0
       /* If we want all directories (dflags & GX_ALLDIRS) and we're not
          being called recursively as something like `echo [star][star]/[star].o'
          ((flags & GX_ALLDIRS) == 0), we want to prevent glob_vector from
          adding a null directory name to the front of the temp_results
          array.  We turn off ADDCURDIR if not called recursively and
          dlen == 0 */
 #endif
       if (directory_len == 0 && (flags & GX_ALLDIRS) == 0)
         dflags &= ~GX_ADDCURDIR;
     }
       temp_results = glob_vector (filename,
                   (directory_len == 0 ? "." : directory_name),
                   dflags);
       if (temp_results == NULL || temp_results == (char **)&glob_error_return)
     {
       if (free_dirname)
         free (directory_name);
       QUIT;         /* XXX - shell */
       run_pending_traps ();
       return (temp_results);
     }
       result = glob_dir_to_array ((dflags & GX_ALLDIRS) ? "" : directory_name, temp_results, flags);
       if (free_dirname)
     free (directory_name);
       return (result);
     }
   /* We get to memory_error if the program has run out of memory, or
      if this is the shell, and we have been interrupted. */
  memory_error:
   if (result != NULL)
     {
       register unsigned int i;
       for (i = 0; result[i] != NULL; ++i)
     free (result[i]);
       free ((char *) result);
     }
   if (free_dirname && directory_name)
     free (directory_name);
   QUIT;
   run_pending_traps ();
   return (NULL);
 }
References bcopy, dequote_pathname, extended_glob, filename, flags, fprintf(), free, glob_dir_to_array(), glob_error_return, glob_pattern_p(), glob_testdir(), glob_vector(), GX_ADDCURDIR, GX_ALLDIRS, GX_GLOBSTAR, GX_MARKDIRS, GX_NULLDIR, GX_RECURSE, GX_SYMLINK, i, l, malloc, n, NULL, NULL_PLACEHOLDER, p, QUIT, realloc, run_pending_traps(), stderr, strlen, and strrchr().
glob_pattern_p()
int glob_pattern_p (char * pattern) const
Definition at line 161 of file glob.c.
 {
 #if HANDLE_MULTIBYTE
   size_t n;
   wchar_t *wpattern;
   int r;
   if (MB_CUR_MAX == 1 || mbsmbchar (pattern) == 0)
     return (internal_glob_pattern_p ((unsigned char *)pattern));
   /* Convert strings to wide chars, and call the multibyte version. */
   n = xdupmbstowcs (&wpattern, NULL, pattern);
   if (n == (size_t)-1)
     /* Oops.  Invalid multibyte sequence.  Try it as single-byte sequence. */
     return (internal_glob_pattern_p ((unsigned char *)pattern));
   r = internal_glob_wpattern_p (wpattern);
   free (wpattern);
   return r;
 #else
   return (internal_glob_pattern_p ((unsigned char *)pattern));
 #endif
 }
References free, MB_CUR_MAX, n, NULL, and pattern.
Referenced by glob_filename(), glob_vector(), and strcreplace().
glob_testdir()
static int glob_testdir (char * dir, int flags) static
Definition at line 565 of file glob.c.
 {
   struct stat finfo;
   int r;
 /*itrace("glob_testdir: testing %s" flags = %d, dir, flags);*/
 #if defined (HAVE_LSTAT)
   r = (flags & GX_ALLDIRS) ? lstat (dir, &finfo) : stat (dir, &finfo);
 #else
   r = stat (dir, &finfo);
 #endif
   if (r < 0)
     return (-1);
 #if defined (S_ISLNK)
   if (S_ISLNK (finfo.st_mode))
     return (-2);
 #endif
   if (S_ISDIR (finfo.st_mode) == 0)
     return (-1);
   return (0);
 }
References dir, flags, GX_ALLDIRS, lstat, S_ISDIR, S_ISLNK, stat::st_mode, and stat().
Referenced by glob_filename(), and glob_vector().
glob_vector()
char** glob_vector (char * pat, char * dir, int flags)
Definition at line 677 of file glob.c.
 {
   DIR *d;
   register struct dirent *dp;
   struct globval *lastlink, *e, *dirlist;
   register struct globval *nextlink;
   register char *nextname, *npat, *subdir;
   unsigned int count;
   int lose, skip, ndirs, isdir, sdlen, add_current, patlen;
   register char **name_vector;
   register unsigned int i;
   int mflags;       /* Flags passed to strmatch (). */
   int pflags;       /* flags passed to sh_makepath () */
   int hasglob;      /* return value from glob_pattern_p */
   int nalloca;
   struct globval *firstmalloc, *tmplink;
   char *convfn;
   lastlink = 0;
   count = lose = skip = add_current = 0;
   firstmalloc = 0;
   nalloca = 0;
   name_vector = NULL;
 /*itrace("glob_vector: pat = `%s' dir = `%s' flags = 0x%x", pat, dir, flags);*/
   /* If PAT is empty, skip the loop, but return one (empty) filename. */
   if (pat == 0 || *pat == '\0')
     {
       if (glob_testdir (dir, 0) < 0)
     return ((char **) &glob_error_return);
       nextlink = (struct globval *)alloca (sizeof (struct globval));
       if (nextlink == NULL)
     return ((char **) NULL);
       nextlink->next = (struct globval *)0;
       nextname = (char *) malloc (1);
       if (nextname == 0)
     lose = 1;
       else
     {
       lastlink = nextlink;
       nextlink->name = nextname;
       nextname[0] = '\0';
       count = 1;
     }
       skip = 1;
     }
   patlen = (pat && *pat) ? strlen (pat) : 0;
   /* If the filename pattern (PAT) does not contain any globbing characters,
      or contains a pattern with only backslash escapes (hasglob == 2),
      we can dispense with reading the directory, and just see if there is
      a filename `DIR/PAT'.  If there is, and we can access it, just make the
      vector to return and bail immediately. */
   hasglob = 0;
   if (skip == 0 && ((hasglob = glob_pattern_p (pat)) == 0 || hasglob == 2))
     {
       int dirlen;
       struct stat finfo;
       if (glob_testdir (dir, 0) < 0)
     return ((char **) &glob_error_return);
       dirlen = strlen (dir);
       nextname = (char *)malloc (dirlen + patlen + 2);
       npat = (char *)malloc (patlen + 1);
       if (nextname == 0 || npat == 0)
     {
       FREE (nextname);
       FREE (npat);
       lose = 1;
     }
       else
     {
       strcpy (npat, pat);
       dequote_pathname (npat);
       strcpy (nextname, dir);
       nextname[dirlen++] = '/';
       strcpy (nextname + dirlen, npat);
       if (GLOB_TESTNAME (nextname) >= 0)
         {
           free (nextname);
           nextlink = (struct globval *)alloca (sizeof (struct globval));
           if (nextlink)
         {
           nextlink->next = (struct globval *)0;
           lastlink = nextlink;
           nextlink->name = npat;
           count = 1;
         }
           else
         {
           free (npat);
           lose = 1;
         }
         }
       else
         {
           free (nextname);
           free (npat);
         }
     }
       skip = 1;
     }
   if (skip == 0)
     {
       /* Open the directory, punting immediately if we cannot.  If opendir
      is not robust (i.e., it opens non-directories successfully), test
      that DIR is a directory and punt if it's not. */
 #if defined (OPENDIR_NOT_ROBUST)
       if (glob_testdir (dir, 0) < 0)
     return ((char **) &glob_error_return);
 #endif
       d = opendir (dir);
       if (d == NULL)
     return ((char **) &glob_error_return);
       /* Compute the flags that will be passed to strmatch().  We don't
      need to do this every time through the loop. */
       mflags = (noglob_dot_filenames ? FNM_PERIOD : FNM_DOTDOT) | FNM_PATHNAME;
 #ifdef FNM_CASEFOLD
       if (glob_ignore_case)
     mflags |= FNM_CASEFOLD;
 #endif
       if (extended_glob)
     mflags |= FNM_EXTMATCH;
       add_current = ((flags & (GX_ALLDIRS|GX_ADDCURDIR)) == (GX_ALLDIRS|GX_ADDCURDIR));
       /* Scan the directory, finding all names that match    For each name that matches, allocate a struct globval
      on the stack and store the name in it.
      Chain those structs together; lastlink is the front of the chain.  */
       while (1)
     {
       /* Make globbing interruptible in the shell. */
       if (interrupt_state || terminating_signal)
         {
           lose = 1;
           break;
         }
       else if (signal_is_pending (SIGINT))  /* XXX - make SIGINT traps responsive */
         {
           lose = 1;
           break;
         }
       dp = readdir (d);
       if (dp == NULL)
         break;
       /* If this directory entry is not to be used, try again. */
       if (REAL_DIR_ENTRY (dp) == 0)
         continue;
 #if 0
       if (dp->d_name == 0 || *dp->d_name == 0)
         continue;
 #endif
 #if HANDLE_MULTIBYTE
       if (MB_CUR_MAX > 1 && mbskipname (pat, dp->d_name, flags))
         continue;
       else
 #endif
       if (skipname (pat, dp->d_name, flags))
         continue;
       /* If we're only interested in directories, don't bother with files */
       if (flags & (GX_MATCHDIRS|GX_ALLDIRS))
         {
           pflags = (flags & GX_ALLDIRS) ? MP_RMDOT : 0;
           if (flags & GX_NULLDIR)
         pflags |= MP_IGNDOT;
           subdir = sh_makepath (dir, dp->d_name, pflags);
           isdir = glob_testdir (subdir, flags);
           if (isdir < 0 && (flags & GX_MATCHDIRS))
         {
           free (subdir);
           continue;
         }
         }
       if (flags & GX_ALLDIRS)
         {
           if (isdir == 0)
         {
           dirlist = finddirs (pat, subdir, (flags & ~GX_ADDCURDIR), &e, &ndirs);
           if (dirlist == &finddirs_error_return)
             {
               free (subdir);
               lose = 1;
               break;
             }
           if (ndirs)        /* add recursive directories to list */
             {
               if (firstmalloc == 0)
                 firstmalloc = e;
               e->next = lastlink;
               lastlink = dirlist;
               count += ndirs;
             }
         }
           /* XXX - should we even add this if it's not a directory? */
           nextlink = (struct globval *) malloc (sizeof (struct globval));
           if (firstmalloc == 0)
         firstmalloc = nextlink;
           sdlen = strlen (subdir);
           nextname = (char *) malloc (sdlen + 1);
           if (nextlink == 0 || nextname == 0)
         {
           if (firstmalloc && firstmalloc == nextlink)
             firstmalloc = 0;
           /* If we reset FIRSTMALLOC we can free this here. */
           FREE (nextlink);
           FREE (nextname);
           free (subdir);
           lose = 1;
           break;
         }
           nextlink->next = lastlink;
           lastlink = nextlink;
           nextlink->name = nextname;
           bcopy (subdir, nextname, sdlen + 1);
           free (subdir);
           ++count;
           continue;
         }
       else if (flags & GX_MATCHDIRS)
         free (subdir);
       convfn = fnx_fromfs (dp->d_name, D_NAMLEN (dp));
       if (strmatch (pat, convfn, mflags) != FNM_NOMATCH)
         {
           if (nalloca < ALLOCA_MAX)
         {
           nextlink = (struct globval *) alloca (sizeof (struct globval));
           nalloca += sizeof (struct globval);
         }
           else
         {
           nextlink = (struct globval *) malloc (sizeof (struct globval));
           if (firstmalloc == 0)
             firstmalloc = nextlink;
         }
           nextname = (char *) malloc (D_NAMLEN (dp) + 1);
           if (nextlink == 0 || nextname == 0)
         {
           /* We free NEXTLINK here, since it won't be added to the
              LASTLINK chain. If we used malloc, and it returned non-
              NULL, firstmalloc will be set to something valid. If it's
              NEXTLINK, reset it before we free NEXTLINK to avoid
              duplicate frees. If not, it will be taken care of by the
              loop below with TMPLINK. */
           if (firstmalloc)
             {
               if (firstmalloc == nextlink)
             firstmalloc = 0;
               FREE (nextlink);
             }
           FREE (nextname);
           lose = 1;
           break;
         }
           nextlink->next = lastlink;
           lastlink = nextlink;
           nextlink->name = nextname;
           bcopy (dp->d_name, nextname, D_NAMLEN (dp) + 1);
           ++count;
         }
     }
       (void) closedir (d);
     }
   /* compat: if GX_ADDCURDIR, add the passed directory also.  Add an empty
      directory name as a placeholder if GX_NULLDIR (in which case the passed
      directory name is "."). */
   if (add_current && lose == 0)
     {
       sdlen = strlen (dir);
       nextname = (char *)malloc (sdlen + 1);
       nextlink = (struct globval *) malloc (sizeof (struct globval));
       if (nextlink == 0 || nextname == 0)
     {
       FREE (nextlink);
       FREE (nextname);
       lose = 1;
     }
       else
     {
       nextlink->name = nextname;
       nextlink->next = lastlink;
       lastlink = nextlink;
       if (flags & GX_NULLDIR)
         nextname[0] = '\0';
       else
         bcopy (dir, nextname, sdlen + 1);
       ++count;
     }
     }
   if (lose == 0)
     {
       name_vector = (char **) malloc ((count + 1) * sizeof (char *));
       lose |= name_vector == NULL;
     }
   /* Have we run out of memory or been interrupted? */
   if (lose)
     {
       tmplink = 0;
       /* Here free the strings we have got.  */
       while (lastlink)
     {
       /* Since we build the list in reverse order, the first N entries
          will be allocated with malloc, if firstmalloc is set, from
          lastlink to firstmalloc. */
       if (firstmalloc)
         {
           if (lastlink == firstmalloc)
         firstmalloc = 0;
           tmplink = lastlink;
         }
       else
         tmplink = 0;
       free (lastlink->name);
       lastlink = lastlink->next;
       FREE (tmplink);
     }
       /* Don't call QUIT; here; let higher layers deal with it. */
       return ((char **)NULL);
     }
   /* Copy the name pointers from the linked list into the vector.  */
   for (tmplink = lastlink, i = 0; i < count; ++i)
     {
       name_vector[i] = tmplink->name;
       tmplink = tmplink->next;
     }
   name_vector[count] = NULL;
   /* If we allocated some of the struct globvals, free them now. */
   if (firstmalloc)
     {
       tmplink = 0;
       while (lastlink)
     {
       tmplink = lastlink;
       if (lastlink == firstmalloc)
         lastlink = firstmalloc = 0;
       else
         lastlink = lastlink->next;
       free (tmplink);
     }
     }
   return (name_vector);
 }
References alloca, ALLOCA_MAX, bcopy, closedir(), count, dirent::d_name, D_NAMLEN, dequote_pathname, dir, extended_glob, finddirs(), finddirs_error_return, flags, FNM_CASEFOLD, FNM_DOTDOT, FNM_EXTMATCH, FNM_NOMATCH, FNM_PATHNAME, FNM_PERIOD, fnx_fromfs(), FREE, free, glob_error_return, glob_ignore_case, glob_pattern_p(), glob_testdir(), GLOB_TESTNAME, GX_ADDCURDIR, GX_ALLDIRS, GX_MATCHDIRS, GX_NULLDIR, i, interrupt_state, malloc, MB_CUR_MAX, MP_IGNDOT, MP_RMDOT, globval::name, globval::next, noglob_dot_filenames, NULL, opendir(), pat, readdir(), REAL_DIR_ENTRY, sh_makepath(), SIGINT, signal_is_pending(), skip, skipname(), strcpy, strlen, strmatch(), and terminating_signal.
Referenced by finddirs(), and glob_filename().
PARAMS() [1/10]
void udequote_pathname PARAMS ((char *))
PARAMS() [2/10]
static char** glob_dir_to_array PARAMS ((char *, char **, int)) static
PARAMS() [3/10]
static int skipname PARAMS ((char *, char *, int)) static
PARAMS() [4/10]
static int glob_testdir PARAMS ((char *, int)) static
PARAMS() [5/10]
char* sh_makepath PARAMS ((const char *, const char *, int))
PARAMS() [6/10]
int sh_eaccess PARAMS ((const char *, int))
PARAMS() [7/10]
int signal_is_pending PARAMS ((int))
PARAMS() [8/10]
void throw_to_top_level PARAMS ((void))
PARAMS() [9/10]
int wextglob_pattern_p PARAMS ((wchar_t *))
PARAMS() [10/10]
wchar_t* glob_patscan_wc PARAMS ((wchar_t *, wchar_t *, int))
skipname()
static int skipname (char * pat, char * dname, int flags) static
Definition at line 270 of file glob.c.
 {
   int i;
 #if EXTENDED_GLOB
   if (extglob_pattern_p (pat))      /* XXX */
     return (extglob_skipname (pat, dname, flags));
 #endif
   if (glob_always_skip_dot_and_dotdot && DOT_OR_DOTDOT (dname))
     return 1;
   /* If a leading dot need not be explicitly matched, and the pattern
      doesn't start with a `.', don't match `.' or `..' */
   if (noglob_dot_filenames == 0 && pat[0] != '.' &&
     (pat[0] != '\\' || pat[1] != '.') &&
     DOT_OR_DOTDOT (dname))
     return 1;
 #if 0
   /* This is where we check whether the pattern is being negated and
      match all files beginning with `.' if the pattern begins with a
      literal `.'. This is the negation of the next clause. */
   else if ((flags & GX_NEGATE) && noglob_dot_filenames == 0 &&
     dname[0] == '.' &&
     (pat[0] == '.' || (pat[0] == '\\' && pat[1] == '.')))
     return 0;
 #endif
   /* If a dot must be explicitly matched, check to see if they do. */
   else if (noglob_dot_filenames && dname[0] == '.' &&
        pat[0] != '.' && (pat[0] != '\\' || pat[1] != '.'))
     return 1;
   return 0;
 }
References DOT_OR_DOTDOT, flags, glob_always_skip_dot_and_dotdot, GX_NEGATE, i, noglob_dot_filenames, and pat.
Referenced by glob_vector().
udequote_pathname()
void udequote_pathname (char * pathname)
Definition at line 455 of file glob.c.
 {
   register int i, j;
   for (i = j = 0; pathname && pathname[i]; )
     {
       if (pathname[i] == '\\')
     i++;
       pathname[j++] = pathname[i++];
       if (pathname[i - 1] == 0)
     break;
     }
   if (pathname)
     pathname[j] = '\0';
 }
References i, and j.
Variable Documentation
extended_glob
int extended_glob extern
Definition at line 51 of file pathexp.c.
Referenced by glob_filename(), glob_vector(), match_upattern(), parse_comsub(), read_token_word(), reset_parser(), skip_to_delim(), and xparse_dolparen().
finddirs_error_return
struct globval finddirs_error_return static
Definition at line 109 of file glob.c.
Referenced by finddirs(), and glob_vector().
glob_always_skip_dot_and_dotdot
int glob_always_skip_dot_and_dotdot = 1
Definition at line 106 of file glob.c.
Referenced by skipname().
glob_error_return
char* glob_error_return
Definition at line 109 of file glob.c.
Referenced by finddirs(), glob_filename(), and glob_vector().
glob_ignore_case
int glob_ignore_case = 0
Definition at line 101 of file glob.c.
Referenced by glob_vector().
noglob_dot_filenames
int noglob_dot_filenames = 1
Definition at line 97 of file glob.c.
Referenced by glob_vector(), and skipname().