Fennix Userspace: Userspace/musl/include/dlfcn.h File Reference
dlfcn.h File Reference
#include <features.h>
Macros
#define RTLD_LAZY 1
#define RTLD_NOW 2
#define RTLD_NOLOAD 4
#define RTLD_NODELETE 4096
#define RTLD_GLOBAL 256
#define RTLD_LOCAL 0
#define RTLD_NEXT ((void *)-1)
#define RTLD_DEFAULT ((void *)0)
#define RTLD_DI_LINKMAP 2
Functions
int dlclose (void *)
char * dlerror (void)
void * dlopen (const char *, int)
void * dlsym (void *__restrict, const char *__restrict)
Macro Definition Documentation
RTLD_DEFAULT
#define RTLD_DEFAULT ((void *)0)
Definition at line 18 of file dlfcn.h.
RTLD_DI_LINKMAP
#define RTLD_DI_LINKMAP 2
Definition at line 20 of file dlfcn.h.
RTLD_GLOBAL
#define RTLD_GLOBAL 256
Definition at line 14 of file dlfcn.h.
RTLD_LAZY
#define RTLD_LAZY 1
Definition at line 10 of file dlfcn.h.
RTLD_LOCAL
#define RTLD_LOCAL 0
Definition at line 15 of file dlfcn.h.
RTLD_NEXT
#define RTLD_NEXT ((void *)-1)
Definition at line 17 of file dlfcn.h.
RTLD_NODELETE
#define RTLD_NODELETE 4096
Definition at line 13 of file dlfcn.h.
RTLD_NOLOAD
#define RTLD_NOLOAD 4
Definition at line 12 of file dlfcn.h.
RTLD_NOW
#define RTLD_NOW 2
Definition at line 11 of file dlfcn.h.
Function Documentation
dlclose()
int dlclose (void * handle)
Definition at line 20 of file dlfcn-stubs.cpp.
{
     return __dlapi_close(handle);
 }
References __dl_invalid_handle(), and p.
dlerror()
char* dlerror (void)
Definition at line 24 of file dlfcn-stubs.cpp.
                     {
     return const_cast<char *>(__dlapi_error());
 }
References __pthread_self.
dlopen()
void* dlopen (const char * file, int flags)
Definition at line 29 of file dlfcn-stubs.cpp.
{
     auto ra = __builtin_extract_return_addr(__builtin_return_address(0));
     return __dlapi_open(file, flags, ra);
 }
References __inhibit_ptc(), __release_ptc(), _dl_debug_state(), add_syms(), dso::constructed, do_init_fini(), error, extend_bfs_deps(), free, gencnt, head, i, init_fini_lock, install_new_tls(), lazy_head, libc, load_deps(), load_library(), lock, dso::next, tls_module::next, noload, p, prepare_lazy(), PTHREAD_CANCEL_DISABLE, pthread_mutex_lock(), pthread_mutex_unlock(), pthread_rwlock_unlock(), pthread_rwlock_wrlock(), pthread_setcancelstate(), queue_ctors(), redo_lazy_relocs(), reloc_all(), revert_syms(), rtld_fail, RTLD_GLOBAL, RTLD_LAZY, RTLD_NOLOAD, setjmp, shutting_down, debug::state, syms_tail, tail, tls_align, tls_cnt, tls_offset, tls_tail, unmap_library(), and update_tls_size().
dlsym()
void* dlsym (void * __restrict, const char * __restrict)