Fennix: Userspace/apps/base/busybox/libbb/perror_msg.c File Reference
perror_msg.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC bb_perror_msg (const char *s,...)
void FAST_FUNC bb_perror_msg_and_die (const char *s,...)
void FAST_FUNC bb_simple_perror_msg (const char *s)
void FAST_FUNC bb_simple_perror_msg_and_die (const char *s)
Function Documentation
bb_perror_msg()
void FAST_FUNC bb_perror_msg (const char * s, ...)
Definition at line 11 of file perror_msg.c.
 {
     va_list p;
     va_start(p, s);
     /* Guard against "<error message>: Success" */
     bb_verror_msg(s, p, errno ? strerror(errno) : NULL);
     va_end(p);
 }
References bb_verror_msg(), errno, NULL, p, s, strerror(), va_end, and va_start.
Referenced by bb_perror_nomsg(), and bb_simple_perror_msg().
bb_perror_msg_and_die()
void FAST_FUNC bb_perror_msg_and_die (const char * s, ...)
Definition at line 21 of file perror_msg.c.
 {
     va_list p;
     va_start(p, s);
     /* Guard against "<error message>: Success" */
     bb_verror_msg(s, p, errno ? strerror(errno) : NULL);
     va_end(p);
     xfunc_die();
 }
References bb_verror_msg(), errno, NULL, p, s, strerror(), va_end, va_start, and xfunc_die().
Referenced by bb_perror_nomsg_and_die(), and bb_simple_perror_msg_and_die().
bb_simple_perror_msg()
void FAST_FUNC bb_simple_perror_msg (const char * s)
Definition at line 32 of file perror_msg.c.
 {
     bb_perror_msg("%s", s);
 }
References bb_perror_msg(), and s.
Referenced by adduser_main(), arpping(), bb_full_fd_action(), bbunpack(), builtin_source(), bump_nofile(), check_existence_through_netlink(), checkjobs(), copy_file(), date_main(), dd_main(), df_main(), do_sendto(), do_stat(), du(), echo_main(), ether_wake_main(), execute(), expand_main(), fdformat_main(), file_action_grep(), fileAction(), flock_main(), flush_update(), fold_main(), fopen_or_warn(), get(), grep_main(), head_main(), IF_DESKTOP(), ifplugd_main(), inetd_main(), install_main(), iproute_flush_cache(), isrv_run(), klogd_main(), ln_main(), login_main(), make_new_session(), mkfifo_main(), mount_it_now(), my_stat(), next(), parse_params(), ping4(), popmaildir_main(), prepare_socket_fd(), print_msg(), print_sem(), print_shm(), process_event(), readLines(), readwrite(), realpath_main(), receive(), recursive_action1(), refill_HFILE_and_getc(), resuse_end(), rtcwake_main(), rtnl_dump_filter(), rtnl_talk(), run_pipe(), safe_poll(), sed_main(), send_file_and_exit(), send_headers(), sendto_ip4(), serial_ctl(), serial_open(), setfattr_main(), shell_builtin_ulimit(), signal_handler(), singlemount(), start_one_job(), sum_file(), swap_enable_disable(), tac_main(), tail_read(), tcpudpsvd_main(), tcsetattr_serial_or_warn(), touch_main(), transformer_write(), wait_one(), wc_main(), writeLines(), xargs_exec(), xrealloc_getcwd_or_warn(), and xset1().
bb_simple_perror_msg_and_die()
void FAST_FUNC bb_simple_perror_msg_and_die (const char * s)
Definition at line 37 of file perror_msg.c.
 {
     bb_perror_msg_and_die("%s", s);
 }
References bb_perror_msg_and_die(), and s.
Referenced by acpid_main(), arp_del(), bb_displayroutes(), bb_getgroups(), blockdev_main(), change_identity(), chpst_main(), cksum_main(), convert(), copy_lines(), copy_tempfile(), create_icmp_socket(), d6_listen_socket(), data_extract_all(), devmem_main(), df_main(), dhcprelay_main(), dmesg_main(), do_sethostname(), do_skip(), dolisten(), encode_n_base64(), env_main(), evaluate(), expand_main(), fb_drawimage(), fb_open(), fflush_stdout_and_exit(), fgets_trim_sanitize(), find_free_vtno(), flash_eraseall_main(), get_logname(), getcaps(), getsebool_main(), getty_main(), handle_accept(), httpd_main(), hush_main(), inotifyd_main(), ipneigh_list_or_flush(), iproute_list_or_flush(), last_main(), limit(), load_policy_main(), logname_main(), losetup_main(), make_tempdir(), mknod_main(), mount_main(), my_fgets80(), nbdclient_main(), nc_main(), new_get_kernel_symbols(), nsenter_main(), parse_conf(), print_sem(), remap(), retrieve_file_data(), reverse(), rfkill_main(), rmmod_main(), script_main(), seed_from_file_if_exists(), seek_by_jump(), selinux_preserve_fcontext(), sestatus_main(), set_kernel_tz(), set_tty_attrs(), setenforce_main(), setfiles_main(), slattach_main(), split_main(), start_shell_in_child(), switch_root_main(), tc_main(), tls_run_copy_loop(), tr_main(), traceroute_init(), udhcp_listen_socket(), udhcpc6_main(), udhcpc_main(), udhcpd_main(), uevent_main(), update_local_clock(), uuencode_main(), wait_for_exitstatus(), wait_for_reply(), write_zeros(), xbind(), xclose(), xconnect(), xdup2(), xfchdir(), xfstat(), xgetpty(), xgettimeofday(), xlisten(), xpipe(), xsendto(), xsetegid(), xseteuid(), xsetgid(), xsettimeofday(), xsetuid(), xsocket(), xspawn(), and xwrite().