Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/d_mode.h File Reference
d_mode.h File Reference
#include "doomtype.h"
Enumerations
enum GameMission_t {
doom , doom2 , pack_tnt , pack_plut ,
pack_chex , pack_hacx , heretic , hexen ,
strife , none
}
enum GameMode_t {
shareware , registered , commercial , retail ,
indetermined
}
enum GameVersion_t {
exe_doom_1_2 , exe_doom_1_666 , exe_doom_1_7 , exe_doom_1_8 ,
exe_doom_1_9 , exe_hacx , exe_ultimate , exe_final ,
exe_final2 , exe_chex , exe_heretic_1_3 , exe_hexen_1_1 ,
exe_strife_1_2 , exe_strife_1_31
}
enum skill_t {
sk_noitems = -1 , sk_baby = 0 , sk_easy , sk_medium ,
sk_hard , sk_nightmare
}
Functions
boolean D_ValidGameMode (GameMission_t mission, GameMode_t mode)
boolean D_ValidGameVersion (GameMission_t mission, GameVersion_t version)
boolean D_ValidEpisodeMap (GameMission_t mission, GameMode_t mode, int episode, int map)
int D_GetNumEpisodes (GameMission_t mission, GameMode_t mode)
boolean D_IsEpisodeMap (GameMission_t mission)
char * D_GameMissionString (GameMission_t mission)
Enumeration Type Documentation
GameMission_t
enum GameMission_t
Enumerator
doom
doom2
pack_tnt
pack_plut
pack_chex
pack_hacx
heretic
hexen
strife
none
Definition at line 27 of file d_mode.h.
 {
     doom,            // Doom 1
     doom2,           // Doom 2
     pack_tnt,        // Final Doom: TNT: Evilution
     pack_plut,       // Final Doom: The Plutonia Experiment
     pack_chex,       // Chex Quest (modded doom)
     pack_hacx,       // Hacx (modded doom2)
     heretic,         // Heretic
     hexen,           // Hexen
     strife,          // Strife
     none
 } GameMission_t;
GameMode_t
enum GameMode_t
Enumerator
shareware
registered
commercial
retail
indetermined
Definition at line 46 of file d_mode.h.
 {
     shareware,       // Doom/Heretic shareware
     registered,      // Doom/Heretic registered
     commercial,      // Doom II/Hexen
     retail,          // Ultimate Doom
     indetermined     // Unknown.
 } GameMode_t;
GameVersion_t
enum GameVersion_t
Enumerator
exe_doom_1_2
exe_doom_1_666
exe_doom_1_7
exe_doom_1_8
exe_doom_1_9
exe_hacx
exe_ultimate
exe_final
exe_final2
exe_chex
exe_heretic_1_3
exe_hexen_1_1
exe_strife_1_2
exe_strife_1_31
Definition at line 57 of file d_mode.h.
 {
     exe_doom_1_2,    // Doom 1.2: shareware and registered
     exe_doom_1_666,  // Doom 1.666: for shareware, registered and commercial
     exe_doom_1_7,    // Doom 1.7/1.7a: "
     exe_doom_1_8,    // Doom 1.8: "
     exe_doom_1_9,    // Doom 1.9: "
     exe_hacx,        // Hacx
     exe_ultimate,    // Ultimate Doom (retail)
     exe_final,       // Final Doom
     exe_final2,      // Final Doom (alternate exe)
     exe_chex,        // Chex Quest executable (based on Final Doom)
     exe_heretic_1_3, // Heretic 1.3
     exe_hexen_1_1,   // Hexen 1.1
     exe_strife_1_2,  // Strife v1.2
     exe_strife_1_31  // Strife v1.31
 } GameVersion_t;
skill_t
enum skill_t
Enumerator
sk_noitems
sk_baby
sk_easy
sk_medium
sk_hard
sk_nightmare
Definition at line 79 of file d_mode.h.
 {
     sk_noitems = -1,        // the "-skill 0" hack
     sk_baby = 0,
     sk_easy,
     sk_medium,
     sk_hard,
     sk_nightmare
 } skill_t;
Function Documentation
D_GameMissionString()
char* D_GameMissionString (GameMission_t mission)
Definition at line 182 of file d_mode.c.
 {
     switch (mission)
     {
         case none:
         default:
             return "none";
         case doom:
             return "doom";
         case doom2:
             return "doom2";
         case pack_tnt:
             return "tnt";
         case pack_plut:
             return "plutonia";
         case pack_hacx:
             return "hacx";
         case pack_chex:
             return "chex";
         case heretic:
             return "heretic";
         case hexen:
             return "hexen";
         case strife:
             return "strife";
     }
 }
References doom, doom2, heretic, hexen, none, pack_chex, pack_hacx, pack_plut, pack_tnt, and strife.
Referenced by W_CheckCorrectIWAD().
D_GetNumEpisodes()
int D_GetNumEpisodes (GameMission_t mission, GameMode_t mode)
Definition at line 103 of file d_mode.c.
 {
     int episode;
     episode = 1;
     while (D_ValidEpisodeMap(mission, mode, episode, 1))
     {
         ++episode;
     }
     return episode - 1;
 }
References D_ValidEpisodeMap().
D_IsEpisodeMap()
boolean D_IsEpisodeMap (GameMission_t mission)
Definition at line 161 of file d_mode.c.
 {
     switch (mission)
     {
         case doom:
         case heretic:
         case pack_chex:
             return true;
         case none:
         case hexen:
         case doom2:
         case pack_hacx:
         case pack_tnt:
         case pack_plut:
         case strife:
         default:
             return false;
     }
 }
References doom, doom2, heretic, hexen, none, pack_chex, pack_hacx, pack_plut, pack_tnt, and strife.
D_ValidEpisodeMap()
boolean D_ValidEpisodeMap (GameMission_t mission, GameMode_t mode, int episode, int map)
Definition at line 65 of file d_mode.c.
 {
     int i;
     // Hacks for Heretic secret episodes
     if (mission == heretic)
     {
         if (mode == retail && episode == 6)
         {
             return map >= 1 && map <= 3;
         }
         else if (mode == registered && episode == 4)
         {
             return map == 1;
         }
     }
     // Find the table entry for this mission/mode combination.
     for (i=0; i<arrlen(valid_modes); ++i)
     {
         if (mission == valid_modes[i].mission
          && mode == valid_modes[i].mode)
         {
             return episode >= 1 && episode <= valid_modes[i].episode
                 && map >= 1 && map <= valid_modes[i].map;
         }
     }
     // Unknown mode/mission combination
     return false;
 }
References arrlen, heretic, i, map, registered, retail, and valid_modes.
Referenced by D_GetNumEpisodes().
D_ValidGameMode()
boolean D_ValidGameMode (GameMission_t mission, GameMode_t mode)
Definition at line 50 of file d_mode.c.
 {
     int i;
     for (i=0; i<arrlen(valid_modes); ++i)
     {
         if (valid_modes[i].mode == mode && valid_modes[i].mission == mission)
         {
             return true;
         }
     }
     return false;
 }
References arrlen, i, and valid_modes.
D_ValidGameVersion()
boolean D_ValidGameVersion (GameMission_t mission, GameVersion_t version)
Definition at line 135 of file d_mode.c.
 {
     int i;
     // All Doom variants can use the Doom versions.
     if (mission == doom2 || mission == pack_plut || mission == pack_tnt
      || mission == pack_hacx || mission == pack_chex)
     {
         mission = doom;
     }
     for (i=0; i<arrlen(valid_versions); ++i)
     {
         if (valid_versions[i].mission == mission
          && valid_versions[i].version == version)
         {
             return true;
         }
     }
     return false;
 }
References arrlen, doom, doom2, i, pack_chex, pack_hacx, pack_plut, pack_tnt, and valid_versions.