Fennix: Userspace/musl/arch/s390x/syscall_arch.h File Reference
syscall_arch.h File Reference
Macros
#define __SYSCALL_LL_E(x) (x)
#define __SYSCALL_LL_O(x) (x)
#define __asm_syscall(ret, ...)
Functions
static long __syscall0 (long n)
static long __syscall1 (long n, long a)
static long __syscall2 (long n, long a, long b)
static long __syscall3 (long n, long a, long b, long c)
static long __syscall4 (long n, long a, long b, long c, long d)
static long __syscall5 (long n, long a, long b, long c, long d, long e)
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f)
Macro Definition Documentation
__asm_syscall
#define __asm_syscall (ret, ...)
Value:
    do { \
    __asm__ __volatile__ ("svc 0\n" \
    : ret : __VA_ARGS__ : "memory"); \
    return r2; \
    } while (0)
Definition at line 4 of file syscall_arch.h.
__SYSCALL_LL_E
#define __SYSCALL_LL_E (x) (x)
Definition at line 1 of file syscall_arch.h.
__SYSCALL_LL_O
#define __SYSCALL_LL_O (x) (x)
Definition at line 2 of file syscall_arch.h.
Function Documentation
__syscall0()
static long __syscall0 (long n) inline static
Definition at line 10 of file syscall_arch.h.
 {
     register long r1 __asm__("r1") = n;
     register long r2 __asm__("r2");
     __asm_syscall("=r"(r2), "r"(r1));
 }
References __asm__(), __asm_syscall, n, r1, and r2.
__syscall1()
static long __syscall1 (long n, long a) inline static
Definition at line 17 of file syscall_arch.h.
 {
     register long r1 __asm__("r1") = n;
     register long r2 __asm__("r2") = a;
     __asm_syscall("+r"(r2), "r"(r1));
 }
References __asm__(), __asm_syscall, n, r1, and r2.
Referenced by __syscall6().
__syscall2()
static long __syscall2 (long n, long a, long b) inline static
Definition at line 24 of file syscall_arch.h.
 {
     register long r1 __asm__("r1") = n;
     register long r2 __asm__("r2") = a;
     register long r3 __asm__("r3") = b;
     __asm_syscall("+r"(r2), "r"(r1), "r"(r3));
 }
References __asm__(), __asm_syscall, n, r1, r2, and r3.
__syscall3()
static long __syscall3 (long n, long a, long b, long c) inline static
Definition at line 32 of file syscall_arch.h.
 {
     register long r1 __asm__("r1") = n;
     register long r2 __asm__("r2") = a;
     register long r3 __asm__("r3") = b;
     register long r4 __asm__("r4") = c;
     __asm_syscall("+r"(r2), "r"(r1), "r"(r3), "r"(r4));
 }
References __asm__(), __asm_syscall, n, r1, r2, r3, and r4.
__syscall4()
static long __syscall4 (long n, long a, long b, long c, long d) inline static
Definition at line 41 of file syscall_arch.h.
 {
     register long r1 __asm__("r1") = n;
     register long r2 __asm__("r2") = a;
     register long r3 __asm__("r3") = b;
     register long r4 __asm__("r4") = c;
     register long r5 __asm__("r5") = d;
     __asm_syscall("+r"(r2), "r"(r1), "r"(r3), "r"(r4), "r"(r5));
 }
References __asm__(), __asm_syscall, n, r1, r2, r3, r4, and r5.
__syscall5()
static long __syscall5 (long n, long a, long b, long c, long d, long e) inline static
Definition at line 51 of file syscall_arch.h.
 {
     register long r1 __asm__("r1") = n;
     register long r2 __asm__("r2") = a;
     register long r3 __asm__("r3") = b;
     register long r4 __asm__("r4") = c;
     register long r5 __asm__("r5") = d;
     register long r6 __asm__("r6") = e;
     __asm_syscall("+r"(r2), "r"(r1), "r"(r3), "r"(r4), "r"(r5), "r"(r6));
 }
References __asm__(), __asm_syscall, n, r1, r2, r3, r4, r5, and r6.
__syscall6()
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f) inline static
Definition at line 62 of file syscall_arch.h.
 {
     if (n == SYS_mmap) return __syscall1(n, (long)(long[]){a,b,c,d,e,f});
     register long r1 __asm__("r1") = n;
     register long r2 __asm__("r2") = a;
     register long r3 __asm__("r3") = b;
     register long r4 __asm__("r4") = c;
     register long r5 __asm__("r5") = d;
     register long r6 __asm__("r6") = e;
     register long r7 __asm__("r7") = f;
     __asm_syscall("+r"(r2), "r"(r1), "r"(r3), "r"(r4), "r"(r5), "r"(r6), "r"(r7));
 }
References __asm__(), __asm_syscall, __syscall1(), f, n, r1, r2, r3, r4, r5, and r6.