Fennix: mlibc::char_detail< char > Struct Reference
mlibc::char_detail< char > Struct Reference
#include <strtol.hpp>
Static Public Member Functions
static bool isSpace (char c)
static bool isDigit (char c)
static bool isHexDigit (char c)
static bool isLower (char c)
static bool isUpper (char c)
Detailed Description
Definition at line 40 of file strtol.hpp.
Member Function Documentation
isDigit()
static bool mlibc::char_detail< char >::isDigit (char c) inline static
Definition at line 42 of file strtol.hpp.
 { return isdigit(c); }
References c, and isdigit().
isHexDigit()
static bool mlibc::char_detail< char >::isHexDigit (char c) inline static
Definition at line 43 of file strtol.hpp.
 { return isxdigit(c); }
References c, and isxdigit().
isLower()
static bool mlibc::char_detail< char >::isLower (char c) inline static
Definition at line 44 of file strtol.hpp.
 { return islower(c); }
References c, and islower().
isSpace()
static bool mlibc::char_detail< char >::isSpace (char c) inline static
Definition at line 41 of file strtol.hpp.
 { return isspace(c); }
References c, and isspace().
isUpper()
static bool mlibc::char_detail< char >::isUpper (char c) inline static
Definition at line 45 of file strtol.hpp.
 { return isupper(c); }
References c, and isupper().
The documentation for this struct was generated from the following file:
Userspace/mlibc/options/internal/include/mlibc/strtol.hpp