Fennix Userspace: Userspace/apps/base/bash/lib/glob/ndir.h File Reference
ndir.h File Reference
Data Structures
struct direct
struct DIR
Macros
#define DIRBLKSIZ 512
#define MAXNAMLEN 15 /* Maximum filename length. */
#define rewinddir(dirp) seekdir (dirp, 0L)
Functions
DIR * opendir ()
struct direct * readdir ()
long telldir ()
void seekdir ()
void closedir ()
Data Structure Documentation
direct
struct direct
Definition at line 30 of file ndir.h.
Data Fields
long d_ino
char d_name[MAXNAMLEN+1]
unsigned short d_namlen
unsigned short d_reclen
DIR
struct DIR
Definition at line 38 of file ndir.h.
Data Fields
char dd_buf[DIRBLKSIZ]
int dd_fd
int dd_loc
int dd_size
Macro Definition Documentation
DIRBLKSIZ
#define DIRBLKSIZ 512
Definition at line 18 of file ndir.h.
MAXNAMLEN
#define MAXNAMLEN 15 /* Maximum filename length. */
Definition at line 26 of file ndir.h.
rewinddir
#define rewinddir (dirp) seekdir (dirp, 0L)
Definition at line 50 of file ndir.h.
Function Documentation
closedir()
void closedir ()
Referenced by _remove_directory(), do_glob(), do_nftw(), getcwd(), glob_vector(), mailstat(), mindist(), rl_filename_completion_function(), and scandir().
opendir()
DIR* opendir ()
Referenced by _remove_directory(), do_glob(), getcwd(), glob_vector(), mailstat(), mindist(), rl_filename_completion_function(), and scandir().
readdir()
struct direct* readdir ()
Referenced by _remove_directory(), do_glob(), do_nftw(), getcwd(), glob_vector(), mailstat(), mindist(), readdir_r(), rl_filename_completion_function(), and scandir().
seekdir()
void seekdir ()
telldir()
long telldir ()