Fennix: Userspace/apps/base/bash/examples/loadables/printenv.c File Reference
printenv.c File Reference
#include <config.h>
#include <stdio.h>
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Functions
int printenv_builtin (WORD_LIST *list)
Variables
char ** export_env
char * printenv_doc []
struct builtin printenv_struct
Function Documentation
printenv_builtin()
int printenv_builtin (WORD_LIST * list)
Definition at line 37 of file printenv.c.
 {
   register char **envp;
   int opt;
   SHELL_VAR *var;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "")) != -1)
     {
       switch (opt)
     {
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   /* printenv */
   if (list == 0)
     {
       maybe_make_export_env ();     /* this allows minimal code */
       for (envp = export_env; *envp; envp++)
     printf ("%s\n", *envp);
       return (EXECUTION_SUCCESS);
     }
   /* printenv varname */
   var = find_variable (list->word->word);
   if (var == 0 || (exported_p (var) == 0))
     return (EXECUTION_FAILURE);
   if (function_p (var))
     print_var_function (var);
   else
     print_var_value (var, 0);
   printf("\n");
   return (EXECUTION_SUCCESS);
 }
References builtin_usage(), CASE_HELPOPT, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, export_env, exported_p, find_variable(), function_p, internal_getopt(), loptend, maybe_make_export_env(), print_var_function(), print_var_value(), printf, reset_internal_getopt(), word_desc::word, and word_list::word.
Variable Documentation
export_env
char** export_env extern
Definition at line 176 of file variables.c.
Referenced by printenv_builtin().
printenv_doc
char* printenv_doc[]
Initial value:
= {
    "Display environment.",
    "",
    "Print names and values of environment variables",
    (char *)NULL
}
Definition at line 80 of file printenv.c.
printenv_struct
struct builtin printenv_struct
Initial value:
= {
    "printenv",
    printenv_builtin,
    BUILTIN_ENABLED,
    printenv_doc,
    "printenv [varname]",
    0
}
Definition at line 80 of file printenv.c.