Fennix Userspace: Userspace/apps/base/bash/lib/readline/tcap.h File Reference
tcap.h File Reference
Functions
int tgetent ()
int tgetflag ()
int tgetnum ()
char * tgetstr ()
int tputs ()
char * tgoto ()
Variables
char PC
char * UP
char * BC
short ospeed
Function Documentation
tgetent()
int tgetent ()
Referenced by _rl_init_terminal_io().
tgetflag()
int tgetflag ()
tgetnum()
int tgetnum ()
Referenced by _rl_get_screen_size().
tgetstr()
char* tgetstr ()
Referenced by get_term_capabilities().
tgoto()
char* tgoto ()
Referenced by delete_chars(), and open_some_spaces().
tputs()
int tputs ()
Referenced by _rl_backspace(), _rl_clear_screen(), _rl_clear_to_eol(), _rl_control_keypad(), _rl_cr(), _rl_disable_meta_key(), _rl_enable_meta_key(), _rl_move_cursor_relative(), _rl_move_vert(), _rl_region_color_off(), _rl_region_color_on(), _rl_set_cursor(), _rl_standout_off(), _rl_standout_on(), delete_chars(), open_some_spaces(), rl_crlf(), and rl_ding().
Variable Documentation
BC
char * BC
Definition at line 45 of file tcap.h.
ospeed
short ospeed extern
Definition at line 295 of file termcap.c.
Referenced by display_speed().
PC
char PC extern
Definition at line 109 of file terminal.c.
UP
char* UP extern
Definition at line 109 of file terminal.c.