Fennix Userspace: Userspace/musl/src/internal/aio_impl.h File Reference
aio_impl.h File Reference
Functions
hidden int __aio_close (int)
hidden void __aio_atfork (int)
Variables
hidden volatile int __aio_fut
Function Documentation
__aio_atfork()
hidden void __aio_atfork (int who)
Definition at line 405 of file aio.c.
 {
     if (who<0) {
         pthread_rwlock_rdlock(&maplock);
         return;
     } else if (!who) {
         pthread_rwlock_unlock(&maplock);
         return;
     }
     aio_fd_cnt = 0;
     if (pthread_rwlock_tryrdlock(&maplock)) {
         /* Obtaining lock may fail if _Fork was called nor via
          * fork. In this case, no further aio is possible from
          * child and we can just null out map so __aio_close
          * does not attempt to do anything. */
         map = 0;
         return;
     }
     if (map) for (int a=0; a<(-1U/2+1)>>24; a++)
         if (map[a]) for (int b=0; b<256; b++)
             if (map[a][b]) for (int c=0; c<256; c++)
                 if (map[a][b][c]) for (int d=0; d<256; d++)
                     map[a][b][c][d] = 0;
     /* Re-initialize the rwlock rather than unlocking since there
      * may have been more than one reference on it in the parent.
      * We are not a lock holder anyway; the thread in the parent was. */
     pthread_rwlock_init(&maplock, 0);
 }
References aio_fd_cnt, c, map, maplock, pthread_rwlock_init(), pthread_rwlock_rdlock(), pthread_rwlock_tryrdlock(), and pthread_rwlock_unlock().
Referenced by _Fork(), and fork().
__aio_close()
hidden int __aio_close (int fd)
Definition at line 398 of file aio.c.
 {
     a_barrier();
     if (aio_fd_cnt) aio_cancel(fd, 0);
     return fd;
 }
References a_barrier, aio_cancel(), aio_fd_cnt, and fd.
Referenced by __stdio_close(), and close().
Variable Documentation
__aio_fut
hidden volatile int __aio_fut extern
Definition at line 77 of file aio.c.
Referenced by aio_suspend(), and cleanup().