Fennix: Userspace/apps/base/busybox/scripts/kconfig/qconf.cc File Reference
qconf.cc File Reference
#include <qapplication.h>
#include <qmainwindow.h>
#include <qtoolbar.h>
#include <qvbox.h>
#include <qsplitter.h>
#include <qlistview.h>
#include <qtextview.h>
#include <qlineedit.h>
#include <qmenubar.h>
#include <qmessagebox.h>
#include <qaction.h>
#include <qheader.h>
#include <qfiledialog.h>
#include <qregexp.h>
#include <stdlib.h>
#include "lkc.h"
#include "qconf.h"
#include "qconf.moc"
#include "images.c"
Macros
#define _ qgettext
Functions
static QString qgettext (const char *str)
static QString qgettext (const QString &str)
static QString print_filter (const QString &str)
static void expr_print_help (void *data, const char *str)
void fixup_rootmenu (struct menu *menu)
static void usage (void)
int main (int ac, char **av)
Variables
static QApplication * configApp
static const char * progname
Macro Definition Documentation
_
#define _ qgettext
Definition at line 31 of file qconf.cc.
Function Documentation
expr_print_help()
static void expr_print_help (void * data, const char * str) static
Definition at line 1011 of file qconf.cc.
 {
     reinterpret_cast<QString*>(data)->append(print_filter(str));
 }
References append(), menu::data, print_filter(), and str.
Referenced by ConfigMainWindow::setHelp().
fixup_rootmenu()
void fixup_rootmenu (struct menu * menu)
Definition at line 1361 of file qconf.cc.
 {
     struct menu *child;
     static int menu_cnt = 0;
     menu->flags |= MENU_ROOT;
     for (child = menu->list; child; child = child->next) {
         if (child->prompt && child->prompt->type == P_MENU) {
             menu_cnt++;
             fixup_rootmenu(child);
             menu_cnt--;
         } else if (!menu_cnt)
             fixup_rootmenu(child);
     }
 }
References child(), menu::flags, menu::list, MENU_ROOT, child::next, and P_MENU.
Referenced by main().
main()
int main (int ac, char ** av)
Definition at line 1385 of file qconf.cc.
 {
     ConfigMainWindow* v;
     const char *name;
     bindtextdomain(PACKAGE, LOCALEDIR);
     textdomain(PACKAGE);
 #ifndef LKC_DIRECT_LINK
     kconfig_load();
 #endif
     progname = av[0];
     configApp = new QApplication(ac, av);
     if (ac > 1 && av[1][0] == '-') {
         switch (av[1][1]) {
         case 'h':
         case '?':
             usage();
         }
         name = av[2];
     } else
         name = av[1];
     if (!name)
         usage();
     conf_parse(name);
     fixup_rootmenu(&rootmenu);
     conf_read(NULL);
     //zconfdump(stdout);
     v = new ConfigMainWindow();
     //zconfdump(stdout);
     v->show();
     configApp->connect(configApp, SIGNAL(lastWindowClosed()), SLOT(quit()));
     configApp->connect(configApp, SIGNAL(aboutToQuit()), v, SLOT(saveSettings()));
     configApp->exec();
     return 0;
 }
References bindtextdomain, conf_read(), configApp, fixup_rootmenu(), kconfig_load(), LOCALEDIR, NULL, PACKAGE, progname, rootmenu, textdomain, and usage().
print_filter()
static QString print_filter (const QString & str) static
Definition at line 980 of file qconf.cc.
 {
     QRegExp re("[<>&\"\\n]");
     QString res = str;
     for (int i = 0; (i = res.find(re, i)) >= 0;) {
         switch (res[i].latin1()) {
         case '<':
             res.replace(i, 1, "&lt;");
             i += 4;
             break;
         case '>':
             res.replace(i, 1, "&gt;");
             i += 4;
             break;
         case '&':
             res.replace(i, 1, "&amp;");
             i += 5;
             break;
         case '"':
             res.replace(i, 1, "&quot;");
             i += 6;
             break;
         case '\n':
             res.replace(i, 1, "<br>");
             i += 4;
             break;
         }
     }
     return res;
 }
References i, and str.
Referenced by expr_print_help(), and ConfigMainWindow::setHelp().
qgettext() [1/2]
static QString qgettext (const char * str) inline static
Definition at line 36 of file qconf.cc.
 {
   return QString::fromLocal8Bit(gettext(str));
 }
References gettext, and str.
qgettext() [2/2]
static QString qgettext (const QString & str) inline static
Definition at line 41 of file qconf.cc.
 {
   return QString::fromLocal8Bit(gettext(str.latin1()));
 }
References gettext, and str.
usage()
static void usage (void) static
Definition at line 1379 of file qconf.cc.
 {
     printf("%s <config>\n", progname);
     exit(0);
 }
References exit(), printf, and progname.
Referenced by main().
Variable Documentation
configApp
QApplication* configApp static
Definition at line 34 of file qconf.cc.
Referenced by ConfigMainWindow::ConfigMainWindow(), main(), and ConfigMainWindow::showSplitView().
progname
const char* progname static
Definition at line 1377 of file qconf.cc.
Referenced by main(), and usage().