Fennix: Kernel/core/memory/heap_allocators/Xalloc/Wrapper.cpp File Reference
Wrapper.cpp File Reference
#include "Xalloc.hpp"
#include <memory.hpp>
Functions
void * Xalloc_REQUEST_PAGES (Xsize_t Pages)
void Xalloc_FREE_PAGES (void *Address, Xsize_t Pages)
void Xalloc_MAP_MEMORY (void *VirtualAddress, void *PhysicalAddress, Xsize_t Flags)
void Xalloc_UNMAP_MEMORY (void *VirtualAddress)
Function Documentation
Xalloc_FREE_PAGES()
void Xalloc_FREE_PAGES (void * Address, Xsize_t Pages)
Definition at line 27 of file Wrapper.cpp.
 {
     KernelAllocator.FreePages(Address, Pages);
 }
References Address, and KernelAllocator.
Referenced by Xalloc::V2::FreeHeap(), Xalloc::V2::Block::operator delete(), Xalloc::Block::operator delete(), and Xalloc::Block::~Block().
Xalloc_MAP_MEMORY()
void Xalloc_MAP_MEMORY (void * VirtualAddress, void * PhysicalAddress, Xsize_t Flags)
Definition at line 32 of file Wrapper.cpp.
 {
     Memory::Virtual(KernelPageTable).Map(VirtualAddress, PhysicalAddress, Flags);
 }
References Flags, KernelPageTable, Memory::Virtual::Map(), and PhysicalAddress.
Referenced by Xalloc::V2::AllocateHeap().
Xalloc_REQUEST_PAGES()
void* Xalloc_REQUEST_PAGES (Xsize_t Pages)
Definition at line 22 of file Wrapper.cpp.
 {
     return KernelAllocator.RequestPages(Pages);
 }
References KernelAllocator.
Referenced by Xalloc::V2::AllocateHeap(), Xalloc::Block::Block(), Xalloc::Block::operator new(), and Xalloc::V2::Block::operator new().
Xalloc_UNMAP_MEMORY()
void Xalloc_UNMAP_MEMORY (void * VirtualAddress)
Definition at line 37 of file Wrapper.cpp.
 {
     Memory::Virtual(KernelPageTable).Unmap(VirtualAddress);
 }
References KernelPageTable, and Memory::Virtual::Unmap().
Referenced by Xalloc::V2::FreeHeap().