Fennix Userspace: Userspace/musl/include/malloc.h File Reference
malloc.h File Reference
#include <bits/alltypes.h>
Macros
#define __NEED_size_t
Functions
void * malloc (size_t)
The standard function.
void * calloc (size_t, size_t)
The standard function.
void * realloc (void *, size_t)
The standard function.
void free (void *)
The standard function.
void * valloc (size_t)
void * memalign (size_t, size_t)
size_t malloc_usable_size (void *)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 8 of file malloc.h.
Function Documentation
malloc_usable_size()
size_t malloc_usable_size (void * p)
Definition at line 4 of file malloc_usable_size.c.
 {
     if (!p) return 0;
     struct meta *g = get_meta(p);
     int idx = get_slot_index(p);
     size_t stride = get_stride(g);
     unsigned char *start = g->mem->storage + stride*idx;
     unsigned char *end = start + stride - IB;
     return get_nominal_size(p, end);
 }
References CHUNK_SIZE, get_meta(), get_nominal_size(), get_slot_index(), get_stride(), IB, idx, meta::mem, MEM_TO_CHUNK, OVERHEAD, p, start(), and group::storage.
memalign()
void* memalign (size_t align, size_t len)
Definition at line 4 of file memalign.c.
 {
     return aligned_alloc(align, len);
 }
References aligned_alloc().
Referenced by valloc().
valloc()
void* valloc (size_t size)
Definition at line 5 of file valloc.c.
 {
     return memalign(PAGE_SIZE, size);
 }
References memalign(), PAGE_SIZE, and size.