Fennix: Userspace/musl/src/process/wait.c File Reference
wait.c File Reference
#include <sys/wait.h>
Functions
pid_t wait (int *status)
Function Documentation
wait()
pid_t wait (int * status)
Definition at line 3 of file wait.c.
 {
     return waitpid((pid_t)-1, status, 0);
 }
References waitpid().
Referenced by ExecuteCommand(), HandleSignal(), and main().