Fennix Userspace: Userspace/musl/src/internal/stdio_impl.h File Reference
stdio_impl.h File Reference
#include <stdio.h>
#include "syscall.h"
Data Structures
struct _IO_FILE
Macros
#define UNGET 8
#define FFINALLOCK(f) ((f)->lock>=0 ? __lockfile((f)) : 0)
#define FLOCK(f) int __need_unlock = ((f)->lock>=0 ? __lockfile((f)) : 0)
#define FUNLOCK(f) do { if (__need_unlock) __unlockfile((f)); } while (0)
#define F_PERM 1
#define F_NORD 4
#define F_NOWR 8
#define F_EOF 16
#define F_ERR 32
#define F_SVB 64
#define F_APP 128
#define MAYBE_WAITERS 0x40000000
#define feof(f) ((f)->flags & F_EOF)
#define ferror(f) ((f)->flags & F_ERR)
#define getc_unlocked(f) (((f)->rpos != (f)->rend) ? *(f)->rpos++ : __uflow((f)))
#define putc_unlocked(c, f)
Functions
hidden int __lockfile (FILE *)
hidden void __unlockfile (FILE *)
hidden size_t __stdio_read (FILE *, unsigned char *, size_t)
hidden size_t __stdio_write (FILE *, const unsigned char *, size_t)
hidden size_t __stdout_write (FILE *, const unsigned char *, size_t)
hidden off_t __stdio_seek (FILE *, off_t, int)
hidden int __stdio_close (FILE *)
hidden int __toread (FILE *)
hidden int __towrite (FILE *)
hidden void __stdio_exit (void)
hidden void __stdio_exit_needed (void)
int __overflow (FILE *, int)
int __uflow (FILE *)
hidden int __fseeko (FILE *, off_t, int)
hidden int __fseeko_unlocked (FILE *, off_t, int)
hidden off_t __ftello (FILE *)
hidden off_t __ftello_unlocked (FILE *)
hidden size_t __fwritex (const unsigned char *, size_t, FILE *)
hidden int __putc_unlocked (int, FILE *)
hidden FILE * __fdopen (int, const char *)
hidden int __fmodeflags (const char *)
hidden FILE * __ofl_add (FILE *f)
hidden FILE ** __ofl_lock (void)
hidden void __ofl_unlock (void)
hidden void __register_locked_file (FILE *, struct __pthread *)
hidden void __unlist_locked_file (FILE *)
hidden void __do_orphaned_stdio_locks (void)
hidden void __getopt_msg (const char *, const char *, const char *, size_t)
hidden FILE * __fopen_rb_ca (const char *, FILE *, unsigned char *, size_t)
hidden int __fclose_ca (FILE *)
Variables
hidden FILE *volatile __stdin_used
hidden FILE *volatile __stdout_used
hidden FILE *volatile __stderr_used
Macro Definition Documentation
F_APP
#define F_APP 128
Definition at line 19 of file stdio_impl.h.
F_EOF
#define F_EOF 16
Definition at line 16 of file stdio_impl.h.
F_ERR
#define F_ERR 32
Definition at line 17 of file stdio_impl.h.
F_NORD
#define F_NORD 4
Definition at line 14 of file stdio_impl.h.
F_NOWR
#define F_NOWR 8
Definition at line 15 of file stdio_impl.h.
F_PERM
#define F_PERM 1
Definition at line 13 of file stdio_impl.h.
F_SVB
#define F_SVB 64
Definition at line 18 of file stdio_impl.h.
feof
#define feof (f) ((f)->flags & F_EOF)
Definition at line 97 of file stdio_impl.h.
ferror
#define ferror (f) ((f)->flags & F_ERR)
Definition at line 98 of file stdio_impl.h.
FFINALLOCK
#define FFINALLOCK (f) ((f)->lock>=0 ? __lockfile((f)) : 0)
Definition at line 9 of file stdio_impl.h.
FLOCK
#define FLOCK (f) int __need_unlock = ((f)->lock>=0 ? __lockfile((f)) : 0)
Definition at line 10 of file stdio_impl.h.
FUNLOCK
#define FUNLOCK (f) do { if (__need_unlock) __unlockfile((f)); } while (0)
Definition at line 11 of file stdio_impl.h.
getc_unlocked
#define getc_unlocked (f) (((f)->rpos != (f)->rend) ? *(f)->rpos++ : __uflow((f)))
Definition at line 100 of file stdio_impl.h.
MAYBE_WAITERS
#define MAYBE_WAITERS 0x40000000
Definition at line 93 of file stdio_impl.h.
putc_unlocked
#define putc_unlocked (c, f)
Value:
    ( (((unsigned char)(c)!=(f)->lbf && (f)->wpos!=(f)->wend)) \
    ? *(f)->wpos++ = (unsigned char)(c) \
    : __overflow((f),(unsigned char)(c)) )
Definition at line 103 of file stdio_impl.h.
UNGET
#define UNGET 8
Definition at line 7 of file stdio_impl.h.
Function Documentation
__do_orphaned_stdio_locks()
hidden void __do_orphaned_stdio_locks (void)
Definition at line 5 of file ftrylockfile.c.
 {
     FILE *f;
     for (f=__pthread_self()->stdio_locks; f; f=f->next_locked)
         a_store(&f->lock, 0x40000000);
 }
References __pthread_self, a_store, f, _IO_FILE::lock, and _IO_FILE::next_locked.
Referenced by __pthread_exit().
__fclose_ca()
hidden int __fclose_ca (FILE * f)
Definition at line 3 of file __fclose_ca.c.
 {
     return f->close(f);
 }
References _IO_FILE::close, and f.
Referenced by __get_resolv_conf(), __lookup_serv(), name_from_hosts(), reverse_hosts(), and reverse_services().
__fdopen()
hidden FILE* __fdopen (int fd, const char * mode)
Definition at line 9 of file __fdopen.c.
 {
     FILE *f;
     struct winsize wsz;
     /* Check for valid initial mode character */
     if (!strchr("rwa", *mode)) {
         errno = EINVAL;
         return 0;
     }
     /* Allocate FILE+buffer or fail */
     if (!(f=malloc(sizeof *f + UNGET + BUFSIZ))) return 0;
     /* Zero-fill only the struct, not the buffer */
     memset(f, 0, sizeof *f);
     /* Impose mode restrictions */
     if (!strchr(mode, '+')) f->flags = (*mode == 'r') ? F_NOWR : F_NORD;
     /* Apply close-on-exec flag */
     if (strchr(mode, 'e')) __syscall(SYS_fcntl, fd, F_SETFD, FD_CLOEXEC);
     /* Set append mode on fd if opened for append */
     if (*mode == 'a') {
         int flags = __syscall(SYS_fcntl, fd, F_GETFL);
         if (!(flags & O_APPEND))
             __syscall(SYS_fcntl, fd, F_SETFL, flags | O_APPEND);
         f->flags |= F_APP;
     }
     f->fd = fd;
     f->buf = (unsigned char *)f + sizeof *f + UNGET;
     f->buf_size = BUFSIZ;
     /* Activate line buffered mode for terminals */
     f->lbf = EOF;
     if (!(f->flags & F_NOWR) && !__syscall(SYS_ioctl, fd, TIOCGWINSZ, &wsz))
         f->lbf = '\n';
     /* Initialize op ptrs. No problem if some are unneeded. */
     f->read = __stdio_read;
     f->write = __stdio_write;
     f->seek = __stdio_seek;
     f->close = __stdio_close;
     if (!libc.threaded) f->lock = -1;
     /* Add new FILE to open file list */
     return __ofl_add(f);
 }
References __ofl_add(), __stdio_close(), __stdio_read(), __stdio_seek(), __stdio_write(), __syscall, _IO_FILE::buf, _IO_FILE::buf_size, BUFSIZ, _IO_FILE::close, EINVAL, EOF, errno, f, F_APP, F_GETFL, F_NORD, F_NOWR, F_SETFD, F_SETFL, _IO_FILE::fd, FD_CLOEXEC, flags, _IO_FILE::flags, if(), _IO_FILE::lbf, libc, _IO_FILE::lock, malloc, memset(), O_APPEND, _IO_FILE::read, _IO_FILE::seek, strchr(), TIOCGWINSZ, UNGET, and _IO_FILE::write.
Referenced by fopen(), and tmpfile().
__fmodeflags()
hidden int __fmodeflags (const char * mode)
Definition at line 4 of file __fmodeflags.c.
 {
     int flags;
     if (strchr(mode, '+')) flags = O_RDWR;
     else if (*mode == 'r') flags = O_RDONLY;
     else flags = O_WRONLY;
     if (strchr(mode, 'x')) flags |= O_EXCL;
     if (strchr(mode, 'e')) flags |= O_CLOEXEC;
     if (*mode != 'r') flags |= O_CREAT;
     if (*mode == 'w') flags |= O_TRUNC;
     if (*mode == 'a') flags |= O_APPEND;
     return flags;
 }
References flags, O_APPEND, O_CLOEXEC, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, and strchr().
Referenced by fopen(), and freopen().
__fopen_rb_ca()
hidden FILE* __fopen_rb_ca (const char * filename, FILE * f, unsigned char * buf, size_t len)
Definition at line 5 of file __fopen_rb_ca.c.
 {
     memset(f, 0, sizeof *f);
     f->fd = sys_open(filename, O_RDONLY|O_CLOEXEC);
     if (f->fd < 0) return 0;
     __syscall(SYS_fcntl, f->fd, F_SETFD, FD_CLOEXEC);
     f->flags = F_NOWR | F_PERM;
     f->buf = buf + UNGET;
     f->buf_size = len - UNGET;
     f->read = __stdio_read;
     f->seek = __stdio_seek;
     f->close = __stdio_close;
     f->lock = -1;
     return f;
 }
References __stdio_close(), __stdio_read(), __stdio_seek(), __syscall, buf, _IO_FILE::buf, _IO_FILE::buf_size, _IO_FILE::close, f, F_NOWR, F_PERM, F_SETFD, _IO_FILE::fd, FD_CLOEXEC, _IO_FILE::flags, _IO_FILE::lock, memset(), O_CLOEXEC, O_RDONLY, _IO_FILE::read, _IO_FILE::seek, sys_open, and UNGET.
Referenced by __get_resolv_conf(), __lookup_serv(), name_from_hosts(), reverse_hosts(), and reverse_services().
__fseeko()
hidden int __fseeko (FILE * f, off_t off, int whence)
Definition at line 34 of file fseek.c.
 {
     int result;
     FLOCK(f);
     result = __fseeko_unlocked(f, off, whence);
     FUNLOCK(f);
     return result;
 }
References __fseeko_unlocked(), f, FLOCK, FUNLOCK, mlibc::off, and mlibc::whence.
Referenced by fseek(), and fsetpos().
__fseeko_unlocked()
hidden int __fseeko_unlocked (FILE * f, off_t off, int whence)
Definition at line 4 of file fseek.c.
 {
     /* Fail immediately for invalid whence argument. */
     if (whence != SEEK_CUR && whence != SEEK_SET && whence != SEEK_END) {
         errno = EINVAL;
         return -1;
     }
     /* Adjust relative offset for unread data in buffer, if any. */
     if (whence == SEEK_CUR && f->rend) off -= f->rend - f->rpos;
     /* Flush write buffer, and report error on failure. */
     if (f->wpos != f->wbase) {
         f->write(f, 0, 0);
         if (!f->wpos) return -1;
     }
     /* Leave writing mode */
     f->wpos = f->wbase = f->wend = 0;
     /* Perform the underlying seek. */
     if (f->seek(f, off, whence) < 0) return -1;
     /* If seek succeeded, file is seekable and we discard read buffer. */
     f->rpos = f->rend = 0;
     f->flags &= ~F_EOF;
     return 0;
 }
References EINVAL, errno, f, F_EOF, _IO_FILE::flags, mlibc::off, _IO_FILE::rend, _IO_FILE::rpos, _IO_FILE::seek, SEEK_CUR, SEEK_END, SEEK_SET, _IO_FILE::wbase, _IO_FILE::wend, mlibc::whence, _IO_FILE::wpos, and _IO_FILE::write.
Referenced by __fseeko(), and rewind().
__ftello()
hidden off_t __ftello (FILE * f)
Definition at line 20 of file ftell.c.
 {
     off_t pos;
     FLOCK(f);
     pos = __ftello_unlocked(f);
     FUNLOCK(f);
     return pos;
 }
References __ftello_unlocked(), f, FLOCK, FUNLOCK, and pos.
Referenced by fgetpos(), and ftell().
__ftello_unlocked()
hidden off_t __ftello_unlocked (FILE * f)
Definition at line 5 of file ftell.c.
 {
     off_t pos = f->seek(f, 0,
         (f->flags & F_APP) && f->wpos != f->wbase
         ? SEEK_END : SEEK_CUR);
     if (pos < 0) return pos;
     /* Adjust for data in buffer. */
     if (f->rend)
         pos += f->rpos - f->rend;
     else if (f->wbase)
         pos += f->wpos - f->wbase;
     return pos;
 }
References f, F_APP, _IO_FILE::flags, pos, _IO_FILE::rend, _IO_FILE::rpos, _IO_FILE::seek, SEEK_CUR, SEEK_END, _IO_FILE::wbase, and _IO_FILE::wpos.
Referenced by __ftello().
__fwritex()
hidden size_t __fwritex (const unsigned char * , size_t , FILE *)
Referenced by __fputwc_unlocked(), fputws(), and out().
__getopt_msg()
hidden void __getopt_msg (const char * a, const char * b, const char * c, size_t l)
Definition at line 16 of file getopt.c.
 {
     FILE *f = stderr;
     b = __lctrans_cur(b);
     FLOCK(f);
     fputs(a, f)>=0
     && fwrite(b, strlen(b), 1, f)
     && fwrite(c, 1, l, f)==l
     && putc('\n', f);
     FUNLOCK(f);
 }
References __lctrans_cur(), b, c, f, FLOCK, fputs(), FUNLOCK, fwrite(), putc(), stderr, and strlen().
Referenced by __getopt_long_core(), and getopt().
__lockfile()
hidden int __lockfile (FILE * f)
Definition at line 4 of file __lockfile.c.
 {
     int owner = f->lock, tid = __pthread_self()->tid;
     if ((owner & ~MAYBE_WAITERS) == tid)
         return 0;
     owner = a_cas(&f->lock, 0, tid);
     if (!owner) return 1;
     while ((owner = a_cas(&f->lock, 0, tid|MAYBE_WAITERS))) {
         if ((owner & MAYBE_WAITERS) ||
             a_cas(&f->lock, owner, owner|MAYBE_WAITERS)==owner)
             __futexwait(&f->lock, owner|MAYBE_WAITERS, 1);
     }
     return 1;
 }
References __futexwait(), __pthread_self, a_cas, f, _IO_FILE::lock, and MAYBE_WAITERS.
Referenced by flockfile(), locking_getc(), and locking_putc().
__ofl_add()
hidden FILE* __ofl_add (FILE * f)
Definition at line 3 of file ofl_add.c.
 {
     FILE **head = __ofl_lock();
     f->next = *head;
     if (*head) (*head)->prev = f;
     *head = f;
     __ofl_unlock();
     return f;
 }
References __ofl_lock(), __ofl_unlock(), f, head, and _IO_FILE::next.
Referenced by __fdopen(), fmemopen(), fopencookie(), open_memstream(), and open_wmemstream().
__ofl_lock()
hidden FILE** __ofl_lock (void)
Definition at line 9 of file ofl.c.
 {
     LOCK(ofl_lock);
     return &ofl_head;
 }
References LOCK, ofl_head, and ofl_lock.
Referenced by __ofl_add(), __pthread_create(), __stdio_exit(), fclose(), fflush(), and popen().
__ofl_unlock()
hidden void __ofl_unlock (void)
Definition at line 15 of file ofl.c.
 {
     UNLOCK(ofl_lock);
 }
References ofl_lock, and UNLOCK.
Referenced by __ofl_add(), __pthread_create(), fclose(), fflush(), and popen().
__overflow()
int __overflow (FILE * , int)
__putc_unlocked()
hidden int __putc_unlocked (int , FILE *)
__register_locked_file()
hidden void __register_locked_file (FILE * , struct __pthread *)
Referenced by flockfile().
__stdio_close()
hidden int __stdio_close (FILE * f)
Definition at line 11 of file __stdio_close.c.
 {
     return syscall(SYS_close, __aio_close(f->fd));
 }
References __aio_close(), f, _IO_FILE::fd, and syscall().
Referenced by __fdopen(), and __fopen_rb_ca().
__stdio_exit()
hidden void __stdio_exit (void)
Definition at line 16 of file __stdio_exit.c.
 {
     FILE *f;
     for (f=*__ofl_lock(); f; f=f->next) close_file(f);
     close_file(__stdin_used);
     close_file(__stdout_used);
     close_file(__stderr_used);
 }
References __ofl_lock(), __stderr_used, __stdin_used, __stdout_used, close_file(), f, and _IO_FILE::next.
Referenced by exit().
__stdio_exit_needed()
hidden void __stdio_exit_needed (void)
Referenced by __toread_needs_stdio_exit(), and __towrite_needs_stdio_exit().
__stdio_read()
hidden size_t __stdio_read (FILE * f, unsigned char * buf, size_t len)
Definition at line 4 of file __stdio_read.c.
 {
     struct iovec iov[2] = {
         { .iov_base = buf, .iov_len = len - !!f->buf_size },
         { .iov_base = f->buf, .iov_len = f->buf_size }
     };
     ssize_t cnt;
     cnt = iov[0].iov_len ? syscall(SYS_readv, f->fd, iov, 2)
         : syscall(SYS_read, f->fd, iov[1].iov_base, iov[1].iov_len);
     if (cnt <= 0) {
         f->flags |= cnt ? F_ERR : F_EOF;
         return 0;
     }
     if (cnt <= iov[0].iov_len) return cnt;
     cnt -= iov[0].iov_len;
     f->rpos = f->buf;
     f->rend = f->buf + cnt;
     if (f->buf_size) buf[len-1] = *f->rpos++;
     return len;
 }
References buf, _IO_FILE::buf, _IO_FILE::buf_size, cnt, f, F_EOF, F_ERR, _IO_FILE::fd, _IO_FILE::flags, iovec::iov_base, iovec::iov_len, _IO_FILE::rend, _IO_FILE::rpos, and syscall().
Referenced by __fdopen(), and __fopen_rb_ca().
__stdio_seek()
hidden off_t __stdio_seek (FILE * f, off_t off, int whence)
Definition at line 4 of file __stdio_seek.c.
 {
     return __lseek(f->fd, off, whence);
 }
References __lseek(), f, _IO_FILE::fd, mlibc::off, and mlibc::whence.
Referenced by __fdopen(), and __fopen_rb_ca().
__stdio_write()
hidden size_t __stdio_write (FILE * f, const unsigned char * buf, size_t len)
Definition at line 4 of file __stdio_write.c.
 {
     struct iovec iovs[2] = {
         { .iov_base = f->wbase, .iov_len = f->wpos-f->wbase },
         { .iov_base = (void *)buf, .iov_len = len }
     };
     struct iovec *iov = iovs;
     size_t rem = iov[0].iov_len + iov[1].iov_len;
     int iovcnt = 2;
     ssize_t cnt;
     for (;;) {
         cnt = syscall(SYS_writev, f->fd, iov, iovcnt);
         if (cnt == rem) {
             f->wend = f->buf + f->buf_size;
             f->wpos = f->wbase = f->buf;
             return len;
         }
         if (cnt < 0) {
             f->wpos = f->wbase = f->wend = 0;
             f->flags |= F_ERR;
             return iovcnt == 2 ? 0 : len-iov[0].iov_len;
         }
         rem -= cnt;
         if (cnt > iov[0].iov_len) {
             cnt -= iov[0].iov_len;
             iov++; iovcnt--;
         }
         iov[0].iov_base = (char *)iov[0].iov_base + cnt;
         iov[0].iov_len -= cnt;
     }
 }
References buf, _IO_FILE::buf, _IO_FILE::buf_size, cnt, f, F_ERR, _IO_FILE::fd, _IO_FILE::flags, iovec::iov_base, iovec::iov_len, syscall(), _IO_FILE::wbase, _IO_FILE::wend, and _IO_FILE::wpos.
Referenced by __fdopen(), __stdout_write(), and vdprintf().
__stdout_write()
hidden size_t __stdout_write (FILE * f, const unsigned char * buf, size_t len)
Definition at line 4 of file __stdout_write.c.
 {
     struct winsize wsz;
     f->write = __stdio_write;
     if (!(f->flags & F_SVB) && __syscall(SYS_ioctl, f->fd, TIOCGWINSZ, &wsz))
         f->lbf = -1;
     return __stdio_write(f, buf, len);
 }
References __stdio_write(), __syscall, buf, f, F_SVB, _IO_FILE::fd, _IO_FILE::flags, _IO_FILE::lbf, TIOCGWINSZ, and _IO_FILE::write.
__toread()
hidden int __toread (FILE * f)
Definition at line 3 of file __toread.c.
 {
     f->mode |= f->mode-1;
     if (f->wpos != f->wbase) f->write(f, 0, 0);
     f->wpos = f->wbase = f->wend = 0;
     if (f->flags & F_NORD) {
         f->flags |= F_ERR;
         return EOF;
     }
     f->rpos = f->rend = f->buf + f->buf_size;
     return (f->flags & F_EOF) ? EOF : 0;
 }
References _IO_FILE::buf, _IO_FILE::buf_size, EOF, f, F_EOF, F_ERR, F_NORD, _IO_FILE::flags, _IO_FILE::mode, _IO_FILE::rend, _IO_FILE::rpos, _IO_FILE::wbase, _IO_FILE::wend, _IO_FILE::wpos, and _IO_FILE::write.
Referenced by __uflow(), fread(), ungetc(), ungetwc(), and vfscanf().
__towrite()
hidden int __towrite (FILE * f)
Definition at line 3 of file __towrite.c.
 {
     f->mode |= f->mode-1;
     if (f->flags & F_NOWR) {
         f->flags |= F_ERR;
         return EOF;
     }
     /* Clear read buffer (easier than summoning nasal demons) */
     f->rpos = f->rend = 0;
     /* Activate write through the buffer. */
     f->wpos = f->wbase = f->buf;
     f->wend = f->buf + f->buf_size;
     return 0;
 }
References _IO_FILE::buf, _IO_FILE::buf_size, EOF, f, F_ERR, F_NOWR, _IO_FILE::flags, _IO_FILE::mode, _IO_FILE::rend, _IO_FILE::rpos, _IO_FILE::wbase, _IO_FILE::wend, and _IO_FILE::wpos.
Referenced by __fwritex(), __overflow(), and vfprintf().
__uflow()
int __uflow (FILE * f)
Definition at line 6 of file __uflow.c.
 {
     unsigned char c;
     if (!__toread(f) && f->read(f, &c, 1)==1) return c;
     return EOF;
 }
References __toread(), c, EOF, f, and _IO_FILE::read.
Referenced by __shgetc().
__unlist_locked_file()
hidden void __unlist_locked_file (FILE * f)
Definition at line 12 of file ftrylockfile.c.
 {
     if (f->lockcount) {
         if (f->next_locked) f->next_locked->prev_locked = f->prev_locked;
         if (f->prev_locked) f->prev_locked->next_locked = f->next_locked;
         else __pthread_self()->stdio_locks = f->next_locked;
     }
 }
References __pthread_self, f, _IO_FILE::lockcount, _IO_FILE::next_locked, and _IO_FILE::prev_locked.
Referenced by fclose(), and funlockfile().
__unlockfile()
hidden void __unlockfile (FILE * f)
Definition at line 19 of file __lockfile.c.
 {
     if (a_swap(&f->lock, 0) & MAYBE_WAITERS)
         __wake(&f->lock, 1, 1);
 }
References __wake(), a_swap, f, _IO_FILE::lock, and MAYBE_WAITERS.
Referenced by funlockfile().
Variable Documentation
__stderr_used
hidden FILE* volatile __stderr_used extern
Definition at line 18 of file stderr.c.
Referenced by __pthread_create(), __stdio_exit(), and fflush().
__stdin_used
hidden FILE* volatile __stdin_used extern
Definition at line 17 of file stdin.c.
Referenced by __pthread_create(), and __stdio_exit().
__stdout_used
hidden FILE* volatile __stdout_used extern
Definition at line 18 of file stdout.c.
Referenced by __pthread_create(), __stdio_exit(), and fflush().