Fennix Userspace: Userspace/musl/src/misc/syslog.c File Reference
syslog.c File Reference
#include <stdarg.h>
#include <sys/socket.h>
#include <stdio.h>
#include <unistd.h>
#include <syslog.h>
#include <time.h>
#include <signal.h>
#include <string.h>
#include <pthread.h>
#include <errno.h>
#include <fcntl.h>
#include "lock.h"
#include "fork_impl.h"
Functions
int setlogmask (int maskpri)
void closelog (void)
static void __openlog ()
void openlog (const char *ident, int opt, int facility)
static int is_lost_conn (int e)
static void _vsyslog (int priority, const char *message, va_list ap)
static void __vsyslog (int priority, const char *message, va_list ap)
void syslog (int priority, const char *message,...)
weak_alias (__vsyslog, vsyslog)
Variables
static volatile int lock [1]
static char log_ident [32]
static int log_opt
static int log_facility = LOG_USER
static int log_mask = 0xff
static int log_fd = -1
volatile int *const __syslog_lockptr = lock
struct {
short sun_family
char sun_path [9]
} log_addr
Function Documentation
__openlog()
static void __openlog () static
Definition at line 51 of file syslog.c.
 {
     log_fd = socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0);
     if (log_fd >= 0) connect(log_fd, (void *)&log_addr, sizeof log_addr);
 }
References AF_UNIX, connect(), log_addr, log_fd, SOCK_CLOEXEC, SOCK_DGRAM, and socket().
Referenced by _vsyslog(), and openlog().
__vsyslog()
static void __vsyslog (int priority, const char * message, va_list ap) static
Definition at line 127 of file syslog.c.
 {
     int cs;
     if (!(log_mask & LOG_MASK(priority&7)) || (priority&~0x3ff)) return;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     LOCK(lock);
     _vsyslog(priority, message, ap);
     UNLOCK(lock);
     pthread_setcancelstate(cs, 0);
 }
References _vsyslog(), ap, LOCK, lock, LOG_MASK, log_mask, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), and UNLOCK.
Referenced by syslog().
_vsyslog()
static void _vsyslog (int priority, const char * message, va_list ap) static
Definition at line 84 of file syslog.c.
 {
     char timebuf[16];
     time_t now;
     struct tm tm;
     char buf[1024];
     int errno_save = errno;
     int pid;
     int l, l2;
     int hlen;
     int fd;
     if (log_fd < 0) __openlog();
     if (!(priority & LOG_FACMASK)) priority |= log_facility;
     now = time(NULL);
     gmtime_r(&now, &tm);
     strftime(timebuf, sizeof timebuf, "%b %e %T", &tm);
     pid = (log_opt & LOG_PID) ? getpid() : 0;
     l = snprintf(buf, sizeof buf, "<%d>%s %n%s%s%.0d%s: ",
         priority, timebuf, &hlen, log_ident, "["+!pid, pid, "]"+!pid);
     errno = errno_save;
     l2 = vsnprintf(buf+l, sizeof buf - l, message, ap);
     if (l2 >= 0) {
         if (l2 >= sizeof buf - l) l = sizeof buf - 1;
         else l += l2;
         if (buf[l-1] != '\n') buf[l++] = '\n';
         if (send(log_fd, buf, l, 0) < 0 && (!is_lost_conn(errno)
             || connect(log_fd, (void *)&log_addr, sizeof log_addr) < 0
             || send(log_fd, buf, l, 0) < 0)
             && (log_opt & LOG_CONS)) {
             fd = open("/dev/console", O_WRONLY|O_NOCTTY|O_CLOEXEC);
             if (fd >= 0) {
                 dprintf(fd, "%.*s", l-hlen, buf+hlen);
                 close(fd);
             }
         }
         if (log_opt & LOG_PERROR) dprintf(2, "%.*s", l-hlen, buf+hlen);
     }
 }
References __openlog(), ap, buf, close(), connect(), dprintf(), errno, fd, getpid(), is_lost_conn(), l, log_addr, LOG_CONS, log_facility, LOG_FACMASK, log_fd, log_ident, log_opt, LOG_PERROR, LOG_PID, NULL, O_CLOEXEC, O_NOCTTY, O_WRONLY, open(), pid, send(), snprintf(), strftime(), time(), timebuf, and vsnprintf().
Referenced by __vsyslog().
closelog()
void closelog (void)
Definition at line 40 of file syslog.c.
 {
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     LOCK(lock);
     close(log_fd);
     log_fd = -1;
     UNLOCK(lock);
     pthread_setcancelstate(cs, 0);
 }
References close(), LOCK, lock, log_fd, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), and UNLOCK.
Referenced by logger_main(), message(), and su_main().
is_lost_conn()
static int is_lost_conn (int e) static
Definition at line 79 of file syslog.c.
 {
     return e==ECONNREFUSED || e==ECONNRESET || e==ENOTCONN || e==EPIPE;
 }
References ECONNREFUSED, ECONNRESET, ENOTCONN, and EPIPE.
Referenced by _vsyslog().
openlog()
void openlog (const char * ident, int opt, int facility)
Definition at line 57 of file syslog.c.
 {
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     LOCK(lock);
     if (ident) {
         size_t n = strnlen(ident, sizeof log_ident - 1);
         memcpy(log_ident, ident, n);
         log_ident[n] = 0;
     } else {
         log_ident[0] = 0;
     }
     log_opt = opt;
     log_facility = facility;
     if ((opt & LOG_NDELAY) && log_fd<0) __openlog();
     UNLOCK(lock);
     pthread_setcancelstate(cs, 0);
 }
References __openlog(), ident, LOCK, lock, log_facility, log_fd, log_ident, LOG_NDELAY, log_opt, memcpy(), n, opt, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), strnlen(), and UNLOCK.
Referenced by acpid_main(), crond_main(), dnsd_main(), fakeidentd_main(), ftpd_main(), getty_main(), ifplugd_main(), inetd_main(), klogd_main(), logger_main(), login_main(), mdev_main(), message(), nameif_main(), passwd_main(), su_main(), sulogin_main(), telnetd_main(), udhcpc6_main(), udhcpc_main(), and udhcpd_main().
setlogmask()
int setlogmask (int maskpri)
Definition at line 23 of file syslog.c.
 {
     LOCK(lock);
     int ret = log_mask;
     if (maskpri) log_mask = maskpri;
     UNLOCK(lock);
     return ret;
 }
References LOCK, lock, log_mask, and UNLOCK.
syslog()
void syslog (int priority, const char * message, ...)
Definition at line 138 of file syslog.c.
 {
     va_list ap;
     va_start(ap, message);
     __vsyslog(priority, message, ap);
     va_end(ap);
 }
References __vsyslog(), ap, va_end, and va_start.
Referenced by bb_verror_msg(), klogd_main(), logger_main(), login_main(), message(), new_password(), and su_main().
weak_alias()
weak_alias (__vsyslog , vsyslog)
Variable Documentation
__syslog_lockptr
volatile int* const __syslog_lockptr = lock
Definition at line 21 of file syslog.c.
lock
volatile int lock[1] static
Definition at line 15 of file syslog.c.
Referenced by __vsyslog(), closelog(), openlog(), and setlogmask().
const { ... } log_addr
Initial value:
= {
    AF_UNIX,
    "/dev/log"
}
Referenced by __openlog(), and _vsyslog().
log_facility
int log_facility = LOG_USER static
Definition at line 18 of file syslog.c.
Referenced by _vsyslog(), and openlog().
log_fd
int log_fd = -1 static
Definition at line 20 of file syslog.c.
Referenced by __openlog(), _vsyslog(), closelog(), message(), and openlog().
log_ident
char log_ident[32] static
Definition at line 16 of file syslog.c.
Referenced by _vsyslog(), and openlog().
log_mask
int log_mask = 0xff static
Definition at line 19 of file syslog.c.
Referenced by __vsyslog(), and setlogmask().
log_opt
int log_opt static
Definition at line 17 of file syslog.c.
Referenced by _vsyslog(), and openlog().