Fennix: Userspace/apps/base/bash/lib/readline/nls.c File Reference
nls.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include "ansi_stdlib.h"
#include <ctype.h>
#include "rldefs.h"
#include "readline.h"
#include "rlshell.h"
#include "rlprivate.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define RL_DEFAULT_LOCALE "C"
Functions
static int utf8locale (char *)
static char * normalize_codeset (char *)
static char * find_codeset (char *, size_t *)
static char * _rl_get_locale_var (const char *)
char * _rl_init_locale (void)
static int _rl_set_localevars (char *localestr, int force)
int _rl_init_eightbit (void)
void _rl_reset_locale (void)
Variables
static char * _rl_current_locale = 0
static char * legal_lang_values []
Macro Definition Documentation
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file nls.c.
RL_DEFAULT_LOCALE
#define RL_DEFAULT_LOCALE "C"
Definition at line 60 of file nls.c.
Function Documentation
_rl_get_locale_var()
static char * _rl_get_locale_var (const char * v) static
Definition at line 93 of file nls.c.
 {
   char *lspec;
   lspec = sh_get_env_value ("LC_ALL");
   if (lspec == 0 || *lspec == 0)
     lspec = sh_get_env_value (v);
   if (lspec == 0 || *lspec == 0)
     lspec = sh_get_env_value ("LANG");
   return lspec;
 }
References sh_get_env_value().
Referenced by _rl_init_locale().
_rl_init_eightbit()
int _rl_init_eightbit (void)
Definition at line 226 of file nls.c.
 {
   char *t, *ol;
   ol = _rl_current_locale;
   t = _rl_init_locale ();   /* resets _rl_current_locale, returns static pointer */
   xfree (ol);
   return (_rl_set_localevars (t, 0));
 }
References _rl_current_locale, _rl_init_locale(), _rl_set_localevars(), t, and xfree.
Referenced by readline_initialize_everything().
_rl_init_locale()
char* _rl_init_locale (void)
Definition at line 127 of file nls.c.
 {
   char *ret, *lspec;
   /* Set the LC_CTYPE locale category from environment variables. */
   lspec = _rl_get_locale_var ("LC_CTYPE");
   /* Since _rl_get_locale_var queries the right environment variables,
      we query the current locale settings with setlocale(), and, if
      that doesn't return anything, we set lspec to the empty string to
      force the subsequent call to setlocale() to define the `native'
      environment. */
 #if defined (HAVE_SETLOCALE)
   if (lspec == 0 || *lspec == 0)
     lspec = setlocale (LC_CTYPE, (char *)NULL);
   if (lspec == 0)
     lspec = "";
   ret = setlocale (LC_CTYPE, lspec);    /* ok, since it does not change locale */
   if (ret == 0 || *ret == 0)
     ret = setlocale (LC_CTYPE, (char *)NULL);
   if (ret == 0 || *ret == 0)
     ret = RL_DEFAULT_LOCALE;
 #else
   ret = (lspec == 0 || *lspec == 0) ? RL_DEFAULT_LOCALE : lspec;
 #endif
   _rl_utf8locale = (ret && *ret) ? utf8locale (ret) : 0;
   _rl_current_locale = savestring (ret);
   return ret;
 }
References _rl_current_locale, _rl_get_locale_var(), _rl_utf8locale, LC_CTYPE, NULL, RL_DEFAULT_LOCALE, savestring(), setlocale, and utf8locale().
Referenced by _rl_init_eightbit(), and _rl_reset_locale().
_rl_reset_locale()
void _rl_reset_locale (void)
Definition at line 335 of file nls.c.
 {
   char *ol, *nl;
   /* This should not be NULL; _rl_init_eightbit sets it on the first call to
      readline() or rl_initialize(). */
   ol = _rl_current_locale;
   nl = _rl_init_locale ();      /* resets _rl_current_locale */
   if ((ol == 0 && nl) || (ol && nl && (STREQ (ol, nl) == 0)))
     (void)_rl_set_localevars (nl, 1);
   xfree (ol);
 }
References _rl_current_locale, _rl_init_locale(), _rl_set_localevars(), STREQ, Driver::void(), and xfree.
Referenced by rl_initialize().
_rl_set_localevars()
static int _rl_set_localevars (char * localestr, int force) static
Definition at line 168 of file nls.c.
 {
 #if defined (HAVE_SETLOCALE)
   if (localestr && *localestr && (localestr[0] != 'C' || localestr[1]) && (STREQ (localestr, "POSIX") == 0))
     {
       _rl_meta_flag = 1;
       _rl_convert_meta_chars_to_ascii = 0;
       _rl_output_meta_chars = 1;
       return (1);
     }
   else if (force)
     {
       /* Default "C" locale settings. */
       _rl_meta_flag = 0;
       _rl_convert_meta_chars_to_ascii = 1;
       _rl_output_meta_chars = 0;
       return (0);
     }
   else
     return (0);
 #else /* !HAVE_SETLOCALE */
   char *t;
   int i;
   /* We don't have setlocale.  Finesse it.  Check the environment for the
      appropriate variables and set eight-bit mode if they have the right
      values. */
   if (localestr == 0 || (t = normalize_codeset (localestr)) == 0)
     return (0);
   for (i = 0; t && legal_lang_values[i]; i++)
     if (STREQ (t, legal_lang_values[i]))
       {
     _rl_meta_flag = 1;
     _rl_convert_meta_chars_to_ascii = 0;
     _rl_output_meta_chars = 1;
     break;
       }
   if (force && legal_lang_values[i] == 0)   /* didn't find it */
     {
       /* Default "C" locale settings. */
       _rl_meta_flag = 0;
       _rl_convert_meta_chars_to_ascii = 1;
       _rl_output_meta_chars = 0;
     }
   _rl_utf8locale = *t ? STREQ (t, "utf8") : 0;
   xfree (t);
   return (legal_lang_values[i] ? 1 : 0);
 #endif /* !HAVE_SETLOCALE */
 }
References _rl_convert_meta_chars_to_ascii, _rl_meta_flag, _rl_output_meta_chars, _rl_utf8locale, force, i, legal_lang_values, normalize_codeset(), STREQ, t, and xfree.
Referenced by _rl_init_eightbit(), and _rl_reset_locale().
find_codeset()
static char * find_codeset (char * name, size_t * lenp) static
Definition at line 286 of file nls.c.
 {
   char *cp, *language, *result;
   cp = language = name;
   result = (char *)0;
   while (*cp && *cp != '_' && *cp != '@' && *cp != '+' && *cp != ',')
     cp++;
   /* This does not make sense: language has to be specified.  As
      an exception we allow the variable to contain only the codeset
      name.  Perhaps there are funny codeset names.  */
   if (language == cp)
     {
       *lenp = strlen (language);
       result = language;
     }
   else
     {
       /* Next is the territory. */
       if (*cp == '_')
     do
       ++cp;
     while (*cp && *cp != '.' && *cp != '@' && *cp != '+' && *cp != ',' && *cp != '_');
       /* Now, finally, is the codeset. */
       result = cp;
       if (*cp == '.')
     do
       ++cp;
     while (*cp && *cp != '@');
       if (cp - result > 2)
     {
       result++;
       *lenp = cp - result;
     }
       else
     {
       *lenp = strlen (language);
       result = language;
     }
     }
   return result;
 }
References strlen().
Referenced by normalize_codeset(), and utf8locale().
normalize_codeset()
static char * normalize_codeset (char * codeset) static
Definition at line 239 of file nls.c.
 {
   size_t namelen, i;
   int len, all_digits;
   char *wp, *retval;
   codeset = find_codeset (codeset, &namelen);
   if (codeset == 0)
     return (codeset);
   all_digits = 1;
   for (len = 0, i = 0; i < namelen; i++)
     {
       if (ISALNUM ((unsigned char)codeset[i]))
     {
       len++;
       all_digits &= _rl_digit_p (codeset[i]);
     }
     }
   retval = (char *)malloc ((all_digits ? 3 : 0) + len + 1);
   if (retval == 0)
     return ((char *)0);
   wp = retval;
   /* Add `iso' to beginning of an all-digit codeset */
   if (all_digits)
     {
       *wp++ = 'i';
       *wp++ = 's';
       *wp++ = 'o';
     }
   for (i = 0; i < namelen; i++)
     if (ISALPHA ((unsigned char)codeset[i]))
       *wp++ = _rl_to_lower (codeset[i]);
     else if (_rl_digit_p (codeset[i]))
       *wp++ = codeset[i];
   *wp = '\0';
   return retval;
 }
References _rl_digit_p(), _rl_to_lower(), all_digits(), find_codeset(), i, ISALNUM, ISALPHA, len, malloc, namelen, and retval.
Referenced by _rl_set_localevars().
utf8locale()
static int utf8locale (char * lspec) static
Definition at line 107 of file nls.c.
 {
   char *cp;
   size_t len;
 #if HAVE_LANGINFO_CODESET
   cp = nl_langinfo (CODESET);
   return (STREQ (cp, "UTF-8") || STREQ (cp, "utf8"));
 #else
   cp = find_codeset (lspec, &len);
   if (cp == 0 || len < 4 || len > 5)
     return 0;
   return ((len == 5) ? strncmp (cp, "UTF-8", len) == 0 : strncmp (cp, "utf8", 4) == 0);
 #endif
 }
References CODESET, find_codeset(), len, nl_langinfo(), STREQ, and strncmp().
Referenced by _rl_init_locale().
Variable Documentation
_rl_current_locale
char* _rl_current_locale = 0 static
Definition at line 61 of file nls.c.
Referenced by _rl_init_eightbit(), _rl_init_locale(), and _rl_reset_locale().
legal_lang_values
char* legal_lang_values[] static
Initial value:
=
{
 "iso88591",
 "iso88592",
 "iso88593",
 "iso88594",
 "iso88595",
 "iso88596",
 "iso88597",
 "iso88598",
 "iso88599",
 "iso885910",
 "koi8r",
 "utf8",
  0
}
Definition at line 68 of file nls.c.
Referenced by _rl_set_localevars().