Fennix Userspace: Userspace/musl/src/thread/__timedwait.c File Reference
__timedwait.c File Reference
#include <pthread.h>
#include <time.h>
#include <errno.h>
#include "futex.h"
#include "syscall.h"
#include "pthread_impl.h"
Macros
#define IS32BIT(x) !((x)+0x80000000ULL>>32)
#define CLAMP(x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Functions
static int __futex4_cp (volatile void *addr, int op, int val, const struct timespec *to)
weak_alias (dummy, __eintr_valid_flag)
int __timedwait_cp (volatile int *addr, int val, clockid_t clk, const struct timespec *at, int priv)
int __timedwait (volatile int *addr, int val, clockid_t clk, const struct timespec *at, int priv)
Variables
static volatile int dummy = 0
Macro Definition Documentation
CLAMP
#define CLAMP (x) (int)(IS32BIT(x) ? (x) : 0x7fffffffU+((0ULL+(x))>>63))
Definition at line 9 of file __timedwait.c.
IS32BIT
#define IS32BIT (x) !((x)+0x80000000ULL>>32)
Definition at line 8 of file __timedwait.c.
Function Documentation
__futex4_cp()
static int __futex4_cp (volatile void * addr, int op, int val, const struct timespec * to) static
Definition at line 11 of file __timedwait.c.
 {
     int r;
 #ifdef SYS_futex_time64
     time_t s = to ? to->tv_sec : 0;
     long ns = to ? to->tv_nsec : 0;
     r = -ENOSYS;
     if (SYS_futex == SYS_futex_time64 || !IS32BIT(s))
         r = __syscall_cp(SYS_futex_time64, addr, op, val,
             to ? ((long long[]){s, ns}) : 0);
     if (SYS_futex == SYS_futex_time64 || r!=-ENOSYS) return r;
     to = to ? (void *)(long[]){CLAMP(s), ns} : 0;
 #endif
     r = __syscall_cp(SYS_futex, addr, op, val, to);
     if (r != -ENOSYS) return r;
     return __syscall_cp(SYS_futex, addr, op & ~FUTEX_PRIVATE, val, to);
 }
References __syscall_cp, addr, CLAMP, ENOSYS, FUTEX_PRIVATE, IS32BIT, s, SYS_futex, SYS_futex_time64, timespec::tv_nsec, timespec::tv_sec, and val.
Referenced by __timedwait_cp().
__timedwait()
int __timedwait (volatile int * addr, int val, clockid_t clk, const struct timespec * at, int priv)
Definition at line 63 of file __timedwait.c.
 {
     int cs, r;
     __pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     r = __timedwait_cp(addr, val, clk, at, priv);
     __pthread_setcancelstate(cs, 0);
     return r;
 }
References __pthread_setcancelstate(), __timedwait_cp(), addr, PTHREAD_CANCEL_DISABLE, and val.
Referenced by __pthread_mutex_timedlock(), __pthread_rwlock_timedrdlock(), __pthread_rwlock_timedwrlock(), and pthread_mutex_timedlock_pi().
__timedwait_cp()
int __timedwait_cp (volatile int * addr, int val, clockid_t clk, const struct timespec * at, int priv)
Definition at line 32 of file __timedwait.c.
 {
     int r;
     struct timespec to, *top=0;
     if (priv) priv = FUTEX_PRIVATE;
     if (at) {
         if (at->tv_nsec >= 1000000000UL) return EINVAL;
         if (__clock_gettime(clk, &to)) return EINVAL;
         to.tv_sec = at->tv_sec - to.tv_sec;
         if ((to.tv_nsec = at->tv_nsec - to.tv_nsec) < 0) {
             to.tv_sec--;
             to.tv_nsec += 1000000000;
         }
         if (to.tv_sec < 0) return ETIMEDOUT;
         top = &to;
     }
     r = -__futex4_cp(addr, FUTEX_WAIT|priv, val, top);
     if (r != EINTR && r != ETIMEDOUT && r != ECANCELED) r = 0;
     /* Mitigate bug in old kernels wrongly reporting EINTR for non-
      * interrupting (SA_RESTART) signal handlers. This is only practical
      * when NO interrupting signal handlers have been installed, and
      * works by sigaction tracking whether that's the case. */
     if (r == EINTR && !__eintr_valid_flag) r = 0;
     return r;
 }
References __clock_gettime(), __eintr_valid_flag, __futex4_cp(), addr, ECANCELED, EINTR, EINVAL, ETIMEDOUT, FUTEX_PRIVATE, FUTEX_WAIT, top, timespec::tv_nsec, timespec::tv_sec, and val.
Referenced by __pthread_cond_timedwait(), __pthread_timedjoin_np(), __timedwait(), aio_suspend(), and sem_timedwait().
weak_alias()
weak_alias (dummy , __eintr_valid_flag)
Variable Documentation
dummy
volatile int dummy (void) = 0 static
Definition at line 29 of file __timedwait.c.