Fennix Userspace: Userspace/musl/src/search/hsearch.c File Reference
hsearch.c File Reference
#include <stdlib.h>
#include <string.h>
#include <search.h>
Data Structures
struct __tab
Macros
#define _GNU_SOURCE
#define MINSIZE 8
#define MAXSIZE ((size_t)-1/2 + 1)
Functions
static int __hcreate_r (size_t, struct hsearch_data *)
static void __hdestroy_r (struct hsearch_data *)
static int __hsearch_r (ENTRY, ACTION, ENTRY **, struct hsearch_data *)
static size_t keyhash (char *k)
static int resize (size_t nel, struct hsearch_data *htab)
int hcreate (size_t nel)
void hdestroy (void)
static ENTRY * lookup (char *key, size_t hash, struct hsearch_data *htab)
ENTRY * hsearch (ENTRY item, ACTION action)
weak_alias (__hcreate_r, hcreate_r)
weak_alias (__hdestroy_r, hdestroy_r)
weak_alias (__hsearch_r, hsearch_r)
Variables
static struct hsearch_data htab
Data Structure Documentation
__tab
struct __tab
Definition at line 18 of file hsearch.c.
Data Fields
ENTRY * entries
size_t mask
size_t used
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file hsearch.c.
MAXSIZE
#define MAXSIZE ((size_t)-1/2 + 1)
Definition at line 16 of file hsearch.c.
MINSIZE
#define MINSIZE 8
Definition at line 15 of file hsearch.c.
Function Documentation
__hcreate_r()
static int __hcreate_r (size_t nel, struct hsearch_data * htab) static
Definition at line 103 of file hsearch.c.
 {
     int r;
     htab->__tab = calloc(1, sizeof *htab->__tab);
     if (!htab->__tab)
         return 0;
     r = resize(nel, htab);
     if (r == 0) {
         free(htab->__tab);
         htab->__tab = 0;
     }
     return r;
 }
References calloc, free, htab, and resize().
Referenced by hcreate().
__hdestroy_r()
static void __hdestroy_r (struct hsearch_data * htab) static
Definition at line 119 of file hsearch.c.
 {
     if (htab->__tab) free(htab->__tab->entries);
     free(htab->__tab);
     htab->__tab = 0;
 }
References free, and htab.
Referenced by hdestroy().
__hsearch_r()
static int __hsearch_r (ENTRY item, ACTION action, ENTRY ** retval, struct hsearch_data * htab) static
Definition at line 127 of file hsearch.c.
 {
     size_t hash = keyhash(item.key);
     ENTRY *e = lookup(item.key, hash, htab);
     if (e->key) {
         *retval = e;
         return 1;
     }
     if (action == FIND) {
         *retval = 0;
         return 0;
     }
     *e = item;
     if (++htab->__tab->used > htab->__tab->mask - htab->__tab->mask/4) {
         if (!resize(2*htab->__tab->used, htab)) {
             htab->__tab->used--;
             e->key = 0;
             *retval = 0;
             return 0;
         }
         e = lookup(item.key, hash, htab);
     }
     *retval = e;
     return 1;
 }
References FIND, htab, entry::key, keyhash(), lookup(), resize(), and retval.
Referenced by hsearch().
hcreate()
int hcreate (size_t nel)
Definition at line 72 of file hsearch.c.
 {
     return __hcreate_r(nel, &htab);
 }
References __hcreate_r(), and htab.
hdestroy()
void hdestroy (void)
Definition at line 77 of file hsearch.c.
 {
     __hdestroy_r(&htab);
 }
References __hdestroy_r(), and htab.
hsearch()
ENTRY* hsearch (ENTRY item, ACTION action)
Definition at line 95 of file hsearch.c.
 {
     ENTRY *e;
     __hsearch_r(item, action, &e, &htab);
     return e;
 }
References __hsearch_r(), and htab.
keyhash()
static size_t keyhash (char * k) static
Definition at line 30 of file hsearch.c.
 {
     unsigned char *p = (void *)k;
     size_t h = 0;
     while (*p)
         h = 31*h + *p++;
     return h;
 }
References h, k, and p.
Referenced by __hsearch_r(), and resize().
lookup()
static ENTRY* lookup (char * key, size_t hash, struct hsearch_data * htab) static
Definition at line 82 of file hsearch.c.
 {
     size_t i, j;
     ENTRY *e;
     for (i=hash,j=1; ; i+=j++) {
         e = htab->__tab->entries + (i & htab->__tab->mask);
         if (!e->key || strcmp(e->key, key) == 0)
             break;
     }
     return e;
 }
References htab, i, j, entry::key, and strcmp.
Referenced by __hsearch_r().
resize()
static int resize (size_t nel, struct hsearch_data * htab) static
Definition at line 40 of file hsearch.c.
 {
     size_t newsize;
     size_t i, j;
     size_t oldsize = htab->__tab->mask + 1;
     ENTRY *e, *newe;
     ENTRY *oldtab = htab->__tab->entries;
     if (nel > MAXSIZE)
         nel = MAXSIZE;
     for (newsize = MINSIZE; newsize < nel; newsize *= 2);
     htab->__tab->entries = calloc(newsize, sizeof *htab->__tab->entries);
     if (!htab->__tab->entries) {
         htab->__tab->entries = oldtab;
         return 0;
     }
     htab->__tab->mask = newsize - 1;
     if (!oldtab)
         return 1;
     for (e = oldtab; e < oldtab + oldsize; e++)
         if (e->key) {
             for (i=keyhash(e->key),j=1; ; i+=j++) {
                 newe = htab->__tab->entries + (i & htab->__tab->mask);
                 if (!newe->key)
                     break;
             }
             *newe = *e;
         }
     free(oldtab);
     return 1;
 }
References calloc, free, htab, i, j, entry::key, keyhash(), MAXSIZE, and MINSIZE.
Referenced by __hcreate_r(), __hsearch_r(), and ConfigMainWindow::ConfigMainWindow().
weak_alias() [1/3]
weak_alias (__hcreate_r , hcreate_r)
weak_alias() [2/3]
weak_alias (__hdestroy_r , hdestroy_r)
weak_alias() [3/3]
weak_alias (__hsearch_r , hsearch_r)
Variable Documentation
htab
struct hsearch_data htab static
Definition at line 1 of file hsearch.c.
Referenced by __hcreate_r(), __hdestroy_r(), __hsearch_r(), hcreate(), hdestroy(), hsearch(), IF_DESKTOP(), lookup(), and resize().