Fennix Userspace: Userspace/apps/base/busybox/archival/libarchive/header_list.c File Reference
header_list.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
void FAST_FUNC header_list (const file_header_t *file_header)
Function Documentation
header_list()
void FAST_FUNC header_list (const file_header_t * file_header)
Definition at line 8 of file header_list.c.
 {
 //TODO: cpio -vp DIR should output "DIR/NAME", not just "NAME" */
     puts(file_header->name);
 }
References file_header_t::name, and puts().
Referenced by ar_main(), dpkg_deb_main(), and tar_main().