Fennix Userspace: Userspace/mlibc/options/internal/include/mlibc/allocator.hpp File Reference
allocator.hpp File Reference
#include <mlibc/lock.hpp>
#include <bits/ensure.h>
#include <frg/slab.hpp>
#include <internal-config.h>
Data Structures
struct VirtualAllocator
Typedefs
typedef frg::slab_pool< VirtualAllocator, FutexLock > MemoryPool
typedef frg::slab_allocator< VirtualAllocator, FutexLock > MemoryAllocator
Functions
MemoryAllocator & getAllocator ()
Typedef Documentation
MemoryAllocator
typedef frg::slab_allocator<VirtualAllocator, FutexLock> MemoryAllocator
Definition at line 20 of file allocator.hpp.
MemoryPool
typedef frg::slab_pool<VirtualAllocator, FutexLock> MemoryPool
Definition at line 18 of file allocator.hpp.
Function Documentation
getAllocator()
MemoryAllocator& getAllocator ()
Definition at line 16 of file allocator.cpp.
{
     // use frg::eternal to prevent a call to __cxa_atexit().
     // this is necessary because __cxa_atexit() call this function.
     static frg::eternal<VirtualAllocator> virtualAllocator;
     static frg::eternal<MemoryPool> heap{virtualAllocator.get()};
     static frg::eternal<MemoryAllocator> singleton{&heap.get()};
     return singleton.get();
 }
Referenced by Loader::_buildLinkBfs(), mlibc::abstract_file::_ensure_allocation(), ObjectRepository::_fetchFromFile(), ObjectRepository::_fetchFromPhdrs(), Loader::_processLazyRelocations(), accessDtv(), allocateTcb(), create_slice(), execvpe(), fdopen(), fdopendir(), mlibc::file_dispose_cb(), file_window::file_window(), fopen(), free(), freeaddrinfo(), mlibc::get_nameserver(), anonymous_namespace{environment.cpp}::get_vector(), getaddrinfo(), getdelim(), getExitQueue(), gethostbyname(), getservbyname(), getservbyport(), ObjectRepository::injectObjectFromDts(), ObjectRepository::injectObjectFromPhdrs(), ObjectRepository::injectStaticObject(), interpreterMain(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), mlibc::lookup_serv_file_port(), malloc(), malloc_usable_size(), open_memstream(), opendir(), popen(), posix_memalign(), pthread_atfork(), pthread_cleanup_pop(), pthread_cleanup_push(), pthread_exit(), mlibc::read_dns_name(), realloc(), realpath(), mlibc::fd_file::reopen(), ObjectRepository::requestObjectAtPath(), ObjectRepository::requestObjectWithName(), SharedObject::SharedObject(), tsearch(), writev(), and mlibc::abstract_file::~abstract_file().