Fennix: Userspace/apps/base/busybox/libbb/trim.c File Reference
trim.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC trim (char *s)
Function Documentation
trim()
char* FAST_FUNC trim (char * s)
Definition at line 12 of file trim.c.
 {
     size_t len = strlen(s);
     size_t old = len;
     /* trim trailing whitespace */
     while (len && isspace(s[len-1]))
         --len;
     /* trim leading whitespace */
     if (len) {
         char *nws = skip_whitespace(s);
         if ((nws - s) != 0) {
             len -= (nws - s);
             memmove(s, nws, len);
         }
     }
     s += len;
     /* If it was a "const char*" which does not need trimming,
      * avoid superfluous store */
     if (old != len)
         *s = '\0';
     return s;
 }
References isspace, len, memmove, old, s, skip_whitespace(), and strlen.
Referenced by angle_address(), chat_main(), get_line(), query(), sane_address(), sysctl_handle_preload_file(), and udhcp_str2optset().