Fennix Userspace: Userspace/musl/include/arpa/nameser.h File Reference
nameser.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct __ns_msg
struct _ns_flagdata
struct __ns_rr
struct ns_tsig_key
struct ns_tcp_tsig_state
struct HEADER
Macros
#define __NAMESER 19991006
#define NS_PACKETSZ 512
#define NS_MAXDNAME 1025
#define NS_MAXMSG 65535
#define NS_MAXCDNAME 255
#define NS_MAXLABEL 63
#define NS_HFIXEDSZ 12
#define NS_QFIXEDSZ 4
#define NS_RRFIXEDSZ 10
#define NS_INT32SZ 4
#define NS_INT16SZ 2
#define NS_INT8SZ 1
#define NS_INADDRSZ 4
#define NS_IN6ADDRSZ 16
#define NS_CMPRSFLGS 0xc0
#define NS_DEFAULTPORT 53
#define ns_msg_id(handle) ((handle)._id + 0)
#define ns_msg_base(handle) ((handle)._msg + 0)
#define ns_msg_end(handle) ((handle)._eom + 0)
#define ns_msg_size(handle) ((handle)._eom - (handle)._msg)
#define ns_msg_count(handle, section) ((handle)._counts[section] + 0)
#define ns_msg_getflag(handle, flag) (((handle)._flags & _ns_flagdata[flag].mask) >> _ns_flagdata[flag].shift)
#define ns_rr_name(rr) (((rr).name[0] != '\0') ? (rr).name : ".")
#define ns_rr_type(rr) ((ns_type)((rr).type + 0))
#define ns_rr_class(rr) ((ns_class)((rr).rr_class + 0))
#define ns_rr_ttl(rr) ((rr).ttl + 0)
#define ns_rr_rdlen(rr) ((rr).rdlength + 0)
#define ns_rr_rdata(rr) ((rr).rdata + 0)
#define NS_TSIG_FUDGE 300
#define NS_TSIG_TCP_COUNT 100
#define NS_TSIG_ALG_HMAC_MD5 "HMAC-MD5.SIG-ALG.REG.INT"
#define NS_TSIG_ERROR_NO_TSIG -10
#define NS_TSIG_ERROR_NO_SPACE -11
#define NS_TSIG_ERROR_FORMERR -12
#define ns_t_qt_p(t)
#define ns_t_mrr_p(t) ((t) == ns_t_tsig || (t) == ns_t_opt)
#define ns_t_rr_p(t) (!ns_t_qt_p(t) && !ns_t_mrr_p(t))
#define ns_t_udp_p(t) ((t) != ns_t_axfr && (t) != ns_t_zxfr)
#define ns_t_xfr_p(t)
#define NS_KEY_TYPEMASK 0xC000
#define NS_KEY_TYPE_AUTH_CONF 0x0000
#define NS_KEY_TYPE_CONF_ONLY 0x8000
#define NS_KEY_TYPE_AUTH_ONLY 0x4000
#define NS_KEY_TYPE_NO_KEY 0xC000
#define NS_KEY_NO_AUTH 0x8000
#define NS_KEY_NO_CONF 0x4000
#define NS_KEY_RESERVED2 0x2000
#define NS_KEY_EXTENDED_FLAGS 0x1000
#define NS_KEY_RESERVED4 0x0800
#define NS_KEY_RESERVED5 0x0400
#define NS_KEY_NAME_TYPE 0x0300
#define NS_KEY_NAME_USER 0x0000
#define NS_KEY_NAME_ENTITY 0x0200
#define NS_KEY_NAME_ZONE 0x0100
#define NS_KEY_NAME_RESERVED 0x0300
#define NS_KEY_RESERVED8 0x0080
#define NS_KEY_RESERVED9 0x0040
#define NS_KEY_RESERVED10 0x0020
#define NS_KEY_RESERVED11 0x0010
#define NS_KEY_SIGNATORYMASK 0x000F
#define NS_KEY_RESERVED_BITMASK
#define NS_KEY_RESERVED_BITMASK2 0xFFFF
#define NS_ALG_MD5RSA 1
#define NS_ALG_DH 2
#define NS_ALG_DSA 3
#define NS_ALG_DSS NS_ALG_DSA
#define NS_ALG_EXPIRE_ONLY 253
#define NS_ALG_PRIVATE_OID 254
#define NS_KEY_PROT_TLS 1
#define NS_KEY_PROT_EMAIL 2
#define NS_KEY_PROT_DNSSEC 3
#define NS_KEY_PROT_IPSEC 4
#define NS_KEY_PROT_ANY 255
#define NS_MD5RSA_MIN_BITS 512
#define NS_MD5RSA_MAX_BITS 4096
#define NS_MD5RSA_MAX_BYTES ((NS_MD5RSA_MAX_BITS+7/8)*2+3)
#define NS_MD5RSA_MAX_BASE64 (((NS_MD5RSA_MAX_BYTES+2)/3)*4)
#define NS_MD5RSA_MIN_SIZE ((NS_MD5RSA_MIN_BITS+7)/8)
#define NS_MD5RSA_MAX_SIZE ((NS_MD5RSA_MAX_BITS+7)/8)
#define NS_DSA_SIG_SIZE 41
#define NS_DSA_MIN_SIZE 213
#define NS_DSA_MAX_BYTES 405
#define NS_SIG_TYPE 0
#define NS_SIG_ALG 2
#define NS_SIG_LABELS 3
#define NS_SIG_OTTL 4
#define NS_SIG_EXPIR 8
#define NS_SIG_SIGNED 12
#define NS_SIG_FOOT 16
#define NS_SIG_SIGNER 18
#define NS_NXT_BITS 8
#define NS_NXT_BIT_SET(n, p) (p[(n)/NS_NXT_BITS] |= (0x80>>((n)%NS_NXT_BITS)))
#define NS_NXT_BIT_CLEAR(n, p) (p[(n)/NS_NXT_BITS] &= ~(0x80>>((n)%NS_NXT_BITS)))
#define NS_NXT_BIT_ISSET(n, p) (p[(n)/NS_NXT_BITS] & (0x80>>((n)%NS_NXT_BITS)))
#define NS_NXT_MAX 127
#define NS_OPT_DNSSEC_OK 0x8000U
#define NS_OPT_NSID 3
#define NS_GET16(s, cp) (void)((s) = ns_get16(((cp)+=2)-2))
#define NS_GET32(l, cp) (void)((l) = ns_get32(((cp)+=4)-4))
#define NS_PUT16(s, cp) ns_put16((s), ((cp)+=2)-2)
#define NS_PUT32(l, cp) ns_put32((l), ((cp)+=4)-4)
#define __BIND 19950621
#define PACKETSZ NS_PACKETSZ
#define MAXDNAME NS_MAXDNAME
#define MAXCDNAME NS_MAXCDNAME
#define MAXLABEL NS_MAXLABEL
#define HFIXEDSZ NS_HFIXEDSZ
#define QFIXEDSZ NS_QFIXEDSZ
#define RRFIXEDSZ NS_RRFIXEDSZ
#define INT32SZ NS_INT32SZ
#define INT16SZ NS_INT16SZ
#define INT8SZ NS_INT8SZ
#define INADDRSZ NS_INADDRSZ
#define IN6ADDRSZ NS_IN6ADDRSZ
#define INDIR_MASK NS_CMPRSFLGS
#define NAMESERVER_PORT NS_DEFAULTPORT
#define S_ZONE ns_s_zn
#define S_PREREQ ns_s_pr
#define S_UPDATE ns_s_ud
#define S_ADDT ns_s_ar
#define QUERY ns_o_query
#define IQUERY ns_o_iquery
#define STATUS ns_o_status
#define NS_NOTIFY_OP ns_o_notify
#define NS_UPDATE_OP ns_o_update
#define NOERROR ns_r_noerror
#define FORMERR ns_r_formerr
#define SERVFAIL ns_r_servfail
#define NXDOMAIN ns_r_nxdomain
#define NOTIMP ns_r_notimpl
#define REFUSED ns_r_refused
#define YXDOMAIN ns_r_yxdomain
#define YXRRSET ns_r_yxrrset
#define NXRRSET ns_r_nxrrset
#define NOTAUTH ns_r_notauth
#define NOTZONE ns_r_notzone
#define DELETE ns_uop_delete
#define ADD ns_uop_add
#define T_A ns_t_a
#define T_NS ns_t_ns
#define T_MD ns_t_md
#define T_MF ns_t_mf
#define T_CNAME ns_t_cname
#define T_SOA ns_t_soa
#define T_MB ns_t_mb
#define T_MG ns_t_mg
#define T_MR ns_t_mr
#define T_NULL ns_t_null
#define T_WKS ns_t_wks
#define T_PTR ns_t_ptr
#define T_HINFO ns_t_hinfo
#define T_MINFO ns_t_minfo
#define T_MX ns_t_mx
#define T_TXT ns_t_txt
#define T_RP ns_t_rp
#define T_AFSDB ns_t_afsdb
#define T_X25 ns_t_x25
#define T_ISDN ns_t_isdn
#define T_RT ns_t_rt
#define T_NSAP ns_t_nsap
#define T_NSAP_PTR ns_t_nsap_ptr
#define T_SIG ns_t_sig
#define T_KEY ns_t_key
#define T_PX ns_t_px
#define T_GPOS ns_t_gpos
#define T_AAAA ns_t_aaaa
#define T_LOC ns_t_loc
#define T_NXT ns_t_nxt
#define T_EID ns_t_eid
#define T_NIMLOC ns_t_nimloc
#define T_SRV ns_t_srv
#define T_ATMA ns_t_atma
#define T_NAPTR ns_t_naptr
#define T_A6 ns_t_a6
#define T_DNAME ns_t_dname
#define T_DS ns_t_ds
#define T_SSHFP ns_t_sshfp
#define T_IPSECKEY ns_t_ipseckey
#define T_RRSIG ns_t_rrsig
#define T_NSEC ns_t_nsec
#define T_DNSKEY ns_t_dnskey
#define T_DHCID ns_t_dhcid
#define T_NSEC3 ns_t_nsec3
#define T_NSEC3PARAM ns_t_nsec3param
#define T_TLSA ns_t_tlsa
#define T_SMIMEA ns_t_smimea
#define T_HIP ns_t_hip
#define T_NINFO ns_t_ninfo
#define T_RKEY ns_t_rkey
#define T_TALINK ns_t_talink
#define T_CDS ns_t_cds
#define T_CDNSKEY ns_t_cdnskey
#define T_OPENPGPKEY ns_t_openpgpkey
#define T_CSYNC ns_t_csync
#define T_SPF ns_t_spf
#define T_UINFO ns_t_uinfo
#define T_UID ns_t_uid
#define T_GID ns_t_gid
#define T_UNSPEC ns_t_unspec
#define T_NID ns_t_nid
#define T_L32 ns_t_l32
#define T_L64 ns_t_l64
#define T_LP ns_t_lp
#define T_EUI48 ns_t_eui48
#define T_EUI64 ns_t_eui64
#define T_TKEY ns_t_tkey
#define T_TSIG ns_t_tsig
#define T_IXFR ns_t_ixfr
#define T_AXFR ns_t_axfr
#define T_MAILB ns_t_mailb
#define T_MAILA ns_t_maila
#define T_ANY ns_t_any
#define T_URI ns_t_uri
#define T_CAA ns_t_caa
#define T_AVC ns_t_avc
#define T_TA ns_t_ta
#define T_DLV ns_t_dlv
#define C_IN ns_c_in
#define C_CHAOS ns_c_chaos
#define C_HS ns_c_hs
#define C_NONE ns_c_none
#define C_ANY ns_c_any
#define GETSHORT NS_GET16
#define GETLONG NS_GET32
#define PUTSHORT NS_PUT16
#define PUTLONG NS_PUT32
Typedefs
typedef enum __ns_sect ns_sect
typedef struct __ns_msg ns_msg
typedef struct __ns_rr ns_rr
typedef enum __ns_flag ns_flag
typedef enum __ns_opcode ns_opcode
typedef enum __ns_rcode ns_rcode
typedef enum __ns_update_operation ns_update_operation
typedef struct ns_tsig_key ns_tsig_key
typedef struct ns_tcp_tsig_state ns_tcp_tsig_state
typedef enum __ns_type ns_type
typedef enum __ns_class ns_class
typedef enum __ns_key_types ns_key_types
typedef enum __ns_cert_types ns_cert_types
Enumerations
enum __ns_sect {
ns_s_qd = 0 , ns_s_zn = 0 , ns_s_an = 1 , ns_s_pr = 1 ,
ns_s_ns = 2 , ns_s_ud = 2 , ns_s_ar = 3 , ns_s_max = 4
}
enum __ns_flag {
ns_f_qr , ns_f_opcode , ns_f_aa , ns_f_tc ,
ns_f_rd , ns_f_ra , ns_f_z , ns_f_ad ,
ns_f_cd , ns_f_rcode , ns_f_max
}
enum __ns_opcode {
ns_o_query = 0 , ns_o_iquery = 1 , ns_o_status = 2 , ns_o_notify = 4 ,
ns_o_update = 5 , ns_o_max = 6
}
enum __ns_rcode {
ns_r_noerror = 0 , ns_r_formerr = 1 , ns_r_servfail = 2 , ns_r_nxdomain = 3 ,
ns_r_notimpl = 4 , ns_r_refused = 5 , ns_r_yxdomain = 6 , ns_r_yxrrset = 7 ,
ns_r_nxrrset = 8 , ns_r_notauth = 9 , ns_r_notzone = 10 , ns_r_max = 11 ,
ns_r_badvers = 16 , ns_r_badsig = 16 , ns_r_badkey = 17 , ns_r_badtime = 18 ,
ns_r_noerror = 0 , ns_r_formerr = 1 , ns_r_servfail = 2 , ns_r_nxdomain = 3 ,
ns_r_notimpl = 4 , ns_r_refused = 5 , ns_r_yxdomain = 6 , ns_r_yxrrset = 7 ,
ns_r_nxrrset = 8 , ns_r_notauth = 9 , ns_r_notzone = 10 , ns_r_max = 11 ,
ns_r_badvers = 16 , ns_r_badsig = 16 , ns_r_badkey = 17 , ns_r_badtime = 18
}
enum __ns_update_operation { ns_uop_delete = 0 , ns_uop_add = 1 , ns_uop_max = 2 }
enum __ns_type {
ns_t_invalid = 0 , ns_t_a = 1 , ns_t_ns = 2 , ns_t_md = 3 ,
ns_t_mf = 4 , ns_t_cname = 5 , ns_t_soa = 6 , ns_t_mb = 7 ,
ns_t_mg = 8 , ns_t_mr = 9 , ns_t_null = 10 , ns_t_wks = 11 ,
ns_t_ptr = 12 , ns_t_hinfo = 13 , ns_t_minfo = 14 , ns_t_mx = 15 ,
ns_t_txt = 16 , ns_t_rp = 17 , ns_t_afsdb = 18 , ns_t_x25 = 19 ,
ns_t_isdn = 20 , ns_t_rt = 21 , ns_t_nsap = 22 , ns_t_nsap_ptr = 23 ,
ns_t_sig = 24 , ns_t_key = 25 , ns_t_px = 26 , ns_t_gpos = 27 ,
ns_t_aaaa = 28 , ns_t_loc = 29 , ns_t_nxt = 30 , ns_t_eid = 31 ,
ns_t_nimloc = 32 , ns_t_srv = 33 , ns_t_atma = 34 , ns_t_naptr = 35 ,
ns_t_kx = 36 , ns_t_cert = 37 , ns_t_a6 = 38 , ns_t_dname = 39 ,
ns_t_sink = 40 , ns_t_opt = 41 , ns_t_apl = 42 , ns_t_tkey = 249 ,
ns_t_tsig = 250 , ns_t_ixfr = 251 , ns_t_axfr = 252 , ns_t_mailb = 253 ,
ns_t_maila = 254 , ns_t_any = 255 , ns_t_zxfr = 256 , ns_t_max = 65536 ,
ns_t_invalid = 0 , ns_t_a = 1 , ns_t_ns = 2 , ns_t_md = 3 ,
ns_t_mf = 4 , ns_t_cname = 5 , ns_t_soa = 6 , ns_t_mb = 7 ,
ns_t_mg = 8 , ns_t_mr = 9 , ns_t_null = 10 , ns_t_wks = 11 ,
ns_t_ptr = 12 , ns_t_hinfo = 13 , ns_t_minfo = 14 , ns_t_mx = 15 ,
ns_t_txt = 16 , ns_t_rp = 17 , ns_t_afsdb = 18 , ns_t_x25 = 19 ,
ns_t_isdn = 20 , ns_t_rt = 21 , ns_t_nsap = 22 , ns_t_nsap_ptr = 23 ,
ns_t_sig = 24 , ns_t_key = 25 , ns_t_px = 26 , ns_t_gpos = 27 ,
ns_t_aaaa = 28 , ns_t_loc = 29 , ns_t_nxt = 30 , ns_t_eid = 31 ,
ns_t_nimloc = 32 , ns_t_srv = 33 , ns_t_atma = 34 , ns_t_naptr = 35 ,
ns_t_kx = 36 , ns_t_cert = 37 , ns_t_a6 = 38 , ns_t_dname = 39 ,
ns_t_sink = 40 , ns_t_opt = 41 , ns_t_apl = 42 , ns_t_ds = 43 ,
ns_t_sshfp = 44 , ns_t_ipseckey = 45 , ns_t_rrsig = 46 , ns_t_nsec = 47 ,
ns_t_dnskey = 48 , ns_t_dhcid = 49 , ns_t_nsec3 = 50 , ns_t_nsec3param = 51 ,
ns_t_tlsa = 52 , ns_t_smimea = 53 , ns_t_hip = 55 , ns_t_ninfo = 56 ,
ns_t_rkey = 57 , ns_t_talink = 58 , ns_t_cds = 59 , ns_t_cdnskey = 60 ,
ns_t_openpgpkey = 61 , ns_t_csync = 62 , ns_t_spf = 99 , ns_t_uinfo = 100 ,
ns_t_uid = 101 , ns_t_gid = 102 , ns_t_unspec = 103 , ns_t_nid = 104 ,
ns_t_l32 = 105 , ns_t_l64 = 106 , ns_t_lp = 107 , ns_t_eui48 = 108 ,
ns_t_eui64 = 109 , ns_t_tkey = 249 , ns_t_tsig = 250 , ns_t_ixfr = 251 ,
ns_t_axfr = 252 , ns_t_mailb = 253 , ns_t_maila = 254 , ns_t_any = 255 ,
ns_t_zxfr = 256 , ns_t_uri = 256 , ns_t_caa = 257 , ns_t_avc = 258 ,
ns_t_ta = 32768 , ns_t_dlv = 32769 , ns_t_max = 65536
}
enum __ns_class {
ns_c_invalid = 0 , ns_c_in = 1 , ns_c_2 = 2 , ns_c_chaos = 3 ,
ns_c_hs = 4 , ns_c_none = 254 , ns_c_any = 255 , ns_c_max = 65536 ,
ns_c_invalid = 0 , ns_c_in = 1 , ns_c_2 = 2 , ns_c_chaos = 3 ,
ns_c_hs = 4 , ns_c_none = 254 , ns_c_any = 255 , ns_c_max = 65536
}
enum __ns_key_types { ns_kt_rsa = 1 , ns_kt_dh = 2 , ns_kt_dsa = 3 , ns_kt_private = 254 }
enum __ns_cert_types {
cert_t_pkix = 1 , cert_t_spki = 2 , cert_t_pgp = 3 , cert_t_url = 253 ,
cert_t_oid = 254
}
Functions
unsigned ns_get16 (const unsigned char *)
unsigned long ns_get32 (const unsigned char *)
void ns_put16 (unsigned, unsigned char *)
void ns_put32 (unsigned long, unsigned char *)
int ns_initparse (const unsigned char *, int, ns_msg *)
int ns_parserr (ns_msg *, ns_sect, int, ns_rr *)
int ns_skiprr (const unsigned char *, const unsigned char *, ns_sect, int)
int ns_name_uncompress (const unsigned char *, const unsigned char *, const unsigned char *, char *, size_t)
Variables
const struct _ns_flagdata _ns_flagdata []
Data Structure Documentation
__ns_msg
struct __ns_msg
Definition at line 39 of file nameser.h.
Data Fields
uint16_t _counts[ns_s_max]
const unsigned char * _eom
uint16_t _flags
uint16_t _id
const unsigned char * _msg
const unsigned char * _msg_ptr
int _rrnum
ns_sect _sect
const unsigned char * _sections[ns_s_max]
_ns_flagdata
struct _ns_flagdata
Definition at line 48 of file nameser.h.
Data Fields
int mask
int shift
__ns_rr
struct __ns_rr
Definition at line 59 of file nameser.h.
Data Fields
char name[NS_MAXDNAME]
const unsigned char * rdata
uint16_t rdlength
uint16_t rr_class
uint32_t ttl
uint16_t type
ns_tsig_key
struct ns_tsig_key
Definition at line 123 of file nameser.h.
Data Fields
char alg[NS_MAXDNAME]
unsigned char * data
int len
char name[NS_MAXDNAME]
ns_tcp_tsig_state
struct ns_tcp_tsig_state
Definition at line 130 of file nameser.h.
Data Fields
int counter
void * ctx
struct dst_key * key
unsigned char sig[NS_PACKETSZ]
int siglen
HEADER
struct HEADER
Definition at line 105 of file nameser.h.
Data Fields
unsigned aa: 1
unsigned ad: 1
unsigned ancount:16
unsigned arcount:16
unsigned cd: 1
unsigned id:16
unsigned nscount:16
unsigned opcode: 4
unsigned qdcount:16
unsigned qr: 1
unsigned ra: 1
unsigned rcode:4
unsigned rd: 1
unsigned tc: 1
unsigned unused:1
Macro Definition Documentation
__BIND
#define __BIND 19950621
Definition at line 357 of file nameser.h.
__NAMESER
#define __NAMESER 19991006
Definition at line 11 of file nameser.h.
ADD
#define ADD ns_uop_add
Definition at line 429 of file nameser.h.
C_ANY
#define C_ANY ns_c_any
Definition at line 515 of file nameser.h.
C_CHAOS
#define C_CHAOS ns_c_chaos
Definition at line 512 of file nameser.h.
C_HS
#define C_HS ns_c_hs
Definition at line 513 of file nameser.h.
C_IN
#define C_IN ns_c_in
Definition at line 511 of file nameser.h.
C_NONE
#define C_NONE ns_c_none
Definition at line 514 of file nameser.h.
DELETE
#define DELETE ns_uop_delete
Definition at line 428 of file nameser.h.
FORMERR
#define FORMERR ns_r_formerr
Definition at line 417 of file nameser.h.
GETLONG
#define GETLONG NS_GET32
Definition at line 518 of file nameser.h.
GETSHORT
#define GETSHORT NS_GET16
Definition at line 517 of file nameser.h.
HFIXEDSZ
#define HFIXEDSZ NS_HFIXEDSZ
Definition at line 394 of file nameser.h.
IN6ADDRSZ
#define IN6ADDRSZ NS_IN6ADDRSZ
Definition at line 401 of file nameser.h.
INADDRSZ
#define INADDRSZ NS_INADDRSZ
Definition at line 400 of file nameser.h.
INDIR_MASK
#define INDIR_MASK NS_CMPRSFLGS
Definition at line 402 of file nameser.h.
INT16SZ
#define INT16SZ NS_INT16SZ
Definition at line 398 of file nameser.h.
INT32SZ
#define INT32SZ NS_INT32SZ
Definition at line 397 of file nameser.h.
INT8SZ
#define INT8SZ NS_INT8SZ
Definition at line 399 of file nameser.h.
IQUERY
#define IQUERY ns_o_iquery
Definition at line 411 of file nameser.h.
MAXCDNAME
#define MAXCDNAME NS_MAXCDNAME
Definition at line 392 of file nameser.h.
MAXDNAME
#define MAXDNAME NS_MAXDNAME
Definition at line 391 of file nameser.h.
MAXLABEL
#define MAXLABEL NS_MAXLABEL
Definition at line 393 of file nameser.h.
NAMESERVER_PORT
#define NAMESERVER_PORT NS_DEFAULTPORT
Definition at line 403 of file nameser.h.
NOERROR
#define NOERROR ns_r_noerror
Definition at line 416 of file nameser.h.
NOTAUTH
#define NOTAUTH ns_r_notauth
Definition at line 425 of file nameser.h.
NOTIMP
#define NOTIMP ns_r_notimpl
Definition at line 420 of file nameser.h.
NOTZONE
#define NOTZONE ns_r_notzone
Definition at line 426 of file nameser.h.
NS_ALG_DH
#define NS_ALG_DH 2
Definition at line 301 of file nameser.h.
NS_ALG_DSA
#define NS_ALG_DSA 3
Definition at line 302 of file nameser.h.
NS_ALG_DSS
#define NS_ALG_DSS NS_ALG_DSA
Definition at line 303 of file nameser.h.
NS_ALG_EXPIRE_ONLY
#define NS_ALG_EXPIRE_ONLY 253
Definition at line 304 of file nameser.h.
NS_ALG_MD5RSA
#define NS_ALG_MD5RSA 1
Definition at line 300 of file nameser.h.
NS_ALG_PRIVATE_OID
#define NS_ALG_PRIVATE_OID 254
Definition at line 305 of file nameser.h.
NS_CMPRSFLGS
#define NS_CMPRSFLGS 0xc0
Definition at line 25 of file nameser.h.
NS_DEFAULTPORT
#define NS_DEFAULTPORT 53
Definition at line 26 of file nameser.h.
NS_DSA_MAX_BYTES
#define NS_DSA_MAX_BYTES 405
Definition at line 322 of file nameser.h.
NS_DSA_MIN_SIZE
#define NS_DSA_MIN_SIZE 213
Definition at line 321 of file nameser.h.
NS_DSA_SIG_SIZE
#define NS_DSA_SIG_SIZE 41
Definition at line 320 of file nameser.h.
NS_GET16
#define NS_GET16 (s, cp) (void)((s) = ns_get16(((cp)+=2)-2))
Definition at line 341 of file nameser.h.
NS_GET32
#define NS_GET32 (l, cp) (void)((l) = ns_get32(((cp)+=4)-4))
Definition at line 342 of file nameser.h.
NS_HFIXEDSZ
#define NS_HFIXEDSZ 12
Definition at line 17 of file nameser.h.
NS_IN6ADDRSZ
#define NS_IN6ADDRSZ 16
Definition at line 24 of file nameser.h.
NS_INADDRSZ
#define NS_INADDRSZ 4
Definition at line 23 of file nameser.h.
NS_INT16SZ
#define NS_INT16SZ 2
Definition at line 21 of file nameser.h.
NS_INT32SZ
#define NS_INT32SZ 4
Definition at line 20 of file nameser.h.
NS_INT8SZ
#define NS_INT8SZ 1
Definition at line 22 of file nameser.h.
NS_KEY_EXTENDED_FLAGS
#define NS_KEY_EXTENDED_FLAGS 0x1000
Definition at line 279 of file nameser.h.
NS_KEY_NAME_ENTITY
#define NS_KEY_NAME_ENTITY 0x0200
Definition at line 284 of file nameser.h.
NS_KEY_NAME_RESERVED
#define NS_KEY_NAME_RESERVED 0x0300
Definition at line 286 of file nameser.h.
NS_KEY_NAME_TYPE
#define NS_KEY_NAME_TYPE 0x0300
Definition at line 282 of file nameser.h.
NS_KEY_NAME_USER
#define NS_KEY_NAME_USER 0x0000
Definition at line 283 of file nameser.h.
NS_KEY_NAME_ZONE
#define NS_KEY_NAME_ZONE 0x0100
Definition at line 285 of file nameser.h.
NS_KEY_NO_AUTH
#define NS_KEY_NO_AUTH 0x8000
Definition at line 276 of file nameser.h.
NS_KEY_NO_CONF
#define NS_KEY_NO_CONF 0x4000
Definition at line 277 of file nameser.h.
NS_KEY_PROT_ANY
#define NS_KEY_PROT_ANY 255
Definition at line 311 of file nameser.h.
NS_KEY_PROT_DNSSEC
#define NS_KEY_PROT_DNSSEC 3
Definition at line 309 of file nameser.h.
NS_KEY_PROT_EMAIL
#define NS_KEY_PROT_EMAIL 2
Definition at line 308 of file nameser.h.
NS_KEY_PROT_IPSEC
#define NS_KEY_PROT_IPSEC 4
Definition at line 310 of file nameser.h.
NS_KEY_PROT_TLS
#define NS_KEY_PROT_TLS 1
Definition at line 307 of file nameser.h.
NS_KEY_RESERVED10
#define NS_KEY_RESERVED10 0x0020
Definition at line 289 of file nameser.h.
NS_KEY_RESERVED11
#define NS_KEY_RESERVED11 0x0010
Definition at line 290 of file nameser.h.
NS_KEY_RESERVED2
#define NS_KEY_RESERVED2 0x2000
Definition at line 278 of file nameser.h.
NS_KEY_RESERVED4
#define NS_KEY_RESERVED4 0x0800
Definition at line 280 of file nameser.h.
NS_KEY_RESERVED5
#define NS_KEY_RESERVED5 0x0400
Definition at line 281 of file nameser.h.
NS_KEY_RESERVED8
#define NS_KEY_RESERVED8 0x0080
Definition at line 287 of file nameser.h.
NS_KEY_RESERVED9
#define NS_KEY_RESERVED9 0x0040
Definition at line 288 of file nameser.h.
NS_KEY_RESERVED_BITMASK
#define NS_KEY_RESERVED_BITMASK
Value:
                  ( NS_KEY_RESERVED2 | \
                  NS_KEY_RESERVED4 | \
                  NS_KEY_RESERVED5 | \
                  NS_KEY_RESERVED8 | \
                  NS_KEY_RESERVED9 | \
                  NS_KEY_RESERVED10 | \
                  NS_KEY_RESERVED11 )
Definition at line 292 of file nameser.h.
NS_KEY_RESERVED_BITMASK2
#define NS_KEY_RESERVED_BITMASK2 0xFFFF
Definition at line 299 of file nameser.h.
NS_KEY_SIGNATORYMASK
#define NS_KEY_SIGNATORYMASK 0x000F
Definition at line 291 of file nameser.h.
NS_KEY_TYPE_AUTH_CONF
#define NS_KEY_TYPE_AUTH_CONF 0x0000
Definition at line 272 of file nameser.h.
NS_KEY_TYPE_AUTH_ONLY
#define NS_KEY_TYPE_AUTH_ONLY 0x4000
Definition at line 274 of file nameser.h.
NS_KEY_TYPE_CONF_ONLY
#define NS_KEY_TYPE_CONF_ONLY 0x8000
Definition at line 273 of file nameser.h.
NS_KEY_TYPE_NO_KEY
#define NS_KEY_TYPE_NO_KEY 0xC000
Definition at line 275 of file nameser.h.
NS_KEY_TYPEMASK
#define NS_KEY_TYPEMASK 0xC000
Definition at line 271 of file nameser.h.
NS_MAXCDNAME
#define NS_MAXCDNAME 255
Definition at line 15 of file nameser.h.
NS_MAXDNAME
#define NS_MAXDNAME 1025
Definition at line 13 of file nameser.h.
NS_MAXLABEL
#define NS_MAXLABEL 63
Definition at line 16 of file nameser.h.
NS_MAXMSG
#define NS_MAXMSG 65535
Definition at line 14 of file nameser.h.
NS_MD5RSA_MAX_BASE64
#define NS_MD5RSA_MAX_BASE64 (((NS_MD5RSA_MAX_BYTES+2)/3)*4)
Definition at line 316 of file nameser.h.
NS_MD5RSA_MAX_BITS
#define NS_MD5RSA_MAX_BITS 4096
Definition at line 314 of file nameser.h.
NS_MD5RSA_MAX_BYTES
#define NS_MD5RSA_MAX_BYTES ((NS_MD5RSA_MAX_BITS+7/8)*2+3)
Definition at line 315 of file nameser.h.
NS_MD5RSA_MAX_SIZE
#define NS_MD5RSA_MAX_SIZE ((NS_MD5RSA_MAX_BITS+7)/8)
Definition at line 318 of file nameser.h.
NS_MD5RSA_MIN_BITS
#define NS_MD5RSA_MIN_BITS 512
Definition at line 313 of file nameser.h.
NS_MD5RSA_MIN_SIZE
#define NS_MD5RSA_MIN_SIZE ((NS_MD5RSA_MIN_BITS+7)/8)
Definition at line 317 of file nameser.h.
ns_msg_base
#define ns_msg_base (handle) ((handle)._msg + 0)
Definition at line 52 of file nameser.h.
ns_msg_count
#define ns_msg_count (handle, section) ((handle)._counts[section] + 0)
Definition at line 55 of file nameser.h.
ns_msg_end
#define ns_msg_end (handle) ((handle)._eom + 0)
Definition at line 53 of file nameser.h.
ns_msg_getflag
#define ns_msg_getflag (handle, flag) (((handle)._flags & _ns_flagdata[flag].mask) >> _ns_flagdata[flag].shift)
Definition at line 56 of file nameser.h.
ns_msg_id
#define ns_msg_id (handle) ((handle)._id + 0)
Definition at line 51 of file nameser.h.
ns_msg_size
#define ns_msg_size (handle) ((handle)._eom - (handle)._msg)
Definition at line 54 of file nameser.h.
NS_NOTIFY_OP
#define NS_NOTIFY_OP ns_o_notify
Definition at line 413 of file nameser.h.
NS_NXT_BIT_CLEAR
#define NS_NXT_BIT_CLEAR (n, p) (p[(n)/NS_NXT_BITS] &= ~(0x80>>((n)%NS_NXT_BITS)))
Definition at line 334 of file nameser.h.
NS_NXT_BIT_ISSET
#define NS_NXT_BIT_ISSET (n, p) (p[(n)/NS_NXT_BITS] & (0x80>>((n)%NS_NXT_BITS)))
Definition at line 335 of file nameser.h.
NS_NXT_BIT_SET
#define NS_NXT_BIT_SET (n, p) (p[(n)/NS_NXT_BITS] |= (0x80>>((n)%NS_NXT_BITS)))
Definition at line 333 of file nameser.h.
NS_NXT_BITS
#define NS_NXT_BITS 8
Definition at line 332 of file nameser.h.
NS_NXT_MAX
#define NS_NXT_MAX 127
Definition at line 336 of file nameser.h.
NS_OPT_DNSSEC_OK
#define NS_OPT_DNSSEC_OK 0x8000U
Definition at line 338 of file nameser.h.
NS_OPT_NSID
#define NS_OPT_NSID 3
Definition at line 339 of file nameser.h.
NS_PACKETSZ
#define NS_PACKETSZ 512
Definition at line 12 of file nameser.h.
NS_PUT16
#define NS_PUT16 (s, cp) ns_put16((s), ((cp)+=2)-2)
Definition at line 343 of file nameser.h.
NS_PUT32
#define NS_PUT32 (l, cp) ns_put32((l), ((cp)+=4)-4)
Definition at line 344 of file nameser.h.
NS_QFIXEDSZ
#define NS_QFIXEDSZ 4
Definition at line 18 of file nameser.h.
ns_rr_class
#define ns_rr_class (rr) ((ns_class)((rr).rr_class + 0))
Definition at line 70 of file nameser.h.
ns_rr_name
#define ns_rr_name (rr) (((rr).name[0] != '\0') ? (rr).name : ".")
Definition at line 68 of file nameser.h.
ns_rr_rdata
#define ns_rr_rdata (rr) ((rr).rdata + 0)
Definition at line 73 of file nameser.h.
ns_rr_rdlen
#define ns_rr_rdlen (rr) ((rr).rdlength + 0)
Definition at line 72 of file nameser.h.
ns_rr_ttl
#define ns_rr_ttl (rr) ((rr).ttl + 0)
Definition at line 71 of file nameser.h.
ns_rr_type
#define ns_rr_type (rr) ((ns_type)((rr).type + 0))
Definition at line 69 of file nameser.h.
NS_RRFIXEDSZ
#define NS_RRFIXEDSZ 10
Definition at line 19 of file nameser.h.
NS_SIG_ALG
#define NS_SIG_ALG 2
Definition at line 325 of file nameser.h.
NS_SIG_EXPIR
#define NS_SIG_EXPIR 8
Definition at line 328 of file nameser.h.
NS_SIG_FOOT
#define NS_SIG_FOOT 16
Definition at line 330 of file nameser.h.
NS_SIG_LABELS
#define NS_SIG_LABELS 3
Definition at line 326 of file nameser.h.
NS_SIG_OTTL
#define NS_SIG_OTTL 4
Definition at line 327 of file nameser.h.
NS_SIG_SIGNED
#define NS_SIG_SIGNED 12
Definition at line 329 of file nameser.h.
NS_SIG_SIGNER
#define NS_SIG_SIGNER 18
Definition at line 331 of file nameser.h.
NS_SIG_TYPE
#define NS_SIG_TYPE 0
Definition at line 324 of file nameser.h.
ns_t_mrr_p
#define ns_t_mrr_p (t) ((t) == ns_t_tsig || (t) == ns_t_opt)
Definition at line 239 of file nameser.h.
ns_t_qt_p
#define ns_t_qt_p (t)
Value:
              (ns_t_xfr_p(t) || (t) == ns_t_any || \
              (t) == ns_t_mailb || (t) == ns_t_maila)
Definition at line 237 of file nameser.h.
ns_t_rr_p
#define ns_t_rr_p (t) (!ns_t_qt_p(t) && !ns_t_mrr_p(t))
Definition at line 240 of file nameser.h.
ns_t_udp_p
#define ns_t_udp_p (t) ((t) != ns_t_axfr && (t) != ns_t_zxfr)
Definition at line 241 of file nameser.h.
ns_t_xfr_p
#define ns_t_xfr_p (t)
Value:
               ((t) == ns_t_axfr || (t) == ns_t_ixfr || \
               (t) == ns_t_zxfr)
Definition at line 242 of file nameser.h.
NS_TSIG_ALG_HMAC_MD5
#define NS_TSIG_ALG_HMAC_MD5 "HMAC-MD5.SIG-ALG.REG.INT"
Definition at line 141 of file nameser.h.
NS_TSIG_ERROR_FORMERR
#define NS_TSIG_ERROR_FORMERR -12
Definition at line 145 of file nameser.h.
NS_TSIG_ERROR_NO_SPACE
#define NS_TSIG_ERROR_NO_SPACE -11
Definition at line 144 of file nameser.h.
NS_TSIG_ERROR_NO_TSIG
#define NS_TSIG_ERROR_NO_TSIG -10
Definition at line 143 of file nameser.h.
NS_TSIG_FUDGE
#define NS_TSIG_FUDGE 300
Definition at line 139 of file nameser.h.
NS_TSIG_TCP_COUNT
#define NS_TSIG_TCP_COUNT 100
Definition at line 140 of file nameser.h.
NS_UPDATE_OP
#define NS_UPDATE_OP ns_o_update
Definition at line 414 of file nameser.h.
NXDOMAIN
#define NXDOMAIN ns_r_nxdomain
Definition at line 419 of file nameser.h.
NXRRSET
#define NXRRSET ns_r_nxrrset
Definition at line 424 of file nameser.h.
PACKETSZ
#define PACKETSZ NS_PACKETSZ
Definition at line 390 of file nameser.h.
PUTLONG
#define PUTLONG NS_PUT32
Definition at line 520 of file nameser.h.
PUTSHORT
#define PUTSHORT NS_PUT16
Definition at line 519 of file nameser.h.
QFIXEDSZ
#define QFIXEDSZ NS_QFIXEDSZ
Definition at line 395 of file nameser.h.
QUERY
#define QUERY ns_o_query
Definition at line 410 of file nameser.h.
REFUSED
#define REFUSED ns_r_refused
Definition at line 421 of file nameser.h.
RRFIXEDSZ
#define RRFIXEDSZ NS_RRFIXEDSZ
Definition at line 396 of file nameser.h.
S_ADDT
#define S_ADDT ns_s_ar
Definition at line 408 of file nameser.h.
S_PREREQ
#define S_PREREQ ns_s_pr
Definition at line 406 of file nameser.h.
S_UPDATE
#define S_UPDATE ns_s_ud
Definition at line 407 of file nameser.h.
S_ZONE
#define S_ZONE ns_s_zn
Definition at line 405 of file nameser.h.
SERVFAIL
#define SERVFAIL ns_r_servfail
Definition at line 418 of file nameser.h.
STATUS
#define STATUS ns_o_status
Definition at line 412 of file nameser.h.
T_A
#define T_A ns_t_a
Definition at line 431 of file nameser.h.
T_A6
#define T_A6 ns_t_a6
Definition at line 466 of file nameser.h.
T_AAAA
#define T_AAAA ns_t_aaaa
Definition at line 458 of file nameser.h.
T_AFSDB
#define T_AFSDB ns_t_afsdb
Definition at line 448 of file nameser.h.
T_ANY
#define T_ANY ns_t_any
Definition at line 504 of file nameser.h.
T_ATMA
#define T_ATMA ns_t_atma
Definition at line 464 of file nameser.h.
T_AVC
#define T_AVC ns_t_avc
Definition at line 507 of file nameser.h.
T_AXFR
#define T_AXFR ns_t_axfr
Definition at line 501 of file nameser.h.
T_CAA
#define T_CAA ns_t_caa
Definition at line 506 of file nameser.h.
T_CDNSKEY
#define T_CDNSKEY ns_t_cdnskey
Definition at line 484 of file nameser.h.
T_CDS
#define T_CDS ns_t_cds
Definition at line 483 of file nameser.h.
T_CNAME
#define T_CNAME ns_t_cname
Definition at line 435 of file nameser.h.
T_CSYNC
#define T_CSYNC ns_t_csync
Definition at line 486 of file nameser.h.
T_DHCID
#define T_DHCID ns_t_dhcid
Definition at line 474 of file nameser.h.
T_DLV
#define T_DLV ns_t_dlv
Definition at line 509 of file nameser.h.
T_DNAME
#define T_DNAME ns_t_dname
Definition at line 467 of file nameser.h.
T_DNSKEY
#define T_DNSKEY ns_t_dnskey
Definition at line 473 of file nameser.h.
T_DS
#define T_DS ns_t_ds
Definition at line 468 of file nameser.h.
T_EID
#define T_EID ns_t_eid
Definition at line 461 of file nameser.h.
T_EUI48
#define T_EUI48 ns_t_eui48
Definition at line 496 of file nameser.h.
T_EUI64
#define T_EUI64 ns_t_eui64
Definition at line 497 of file nameser.h.
T_GID
#define T_GID ns_t_gid
Definition at line 490 of file nameser.h.
T_GPOS
#define T_GPOS ns_t_gpos
Definition at line 457 of file nameser.h.
T_HINFO
#define T_HINFO ns_t_hinfo
Definition at line 443 of file nameser.h.
T_HIP
#define T_HIP ns_t_hip
Definition at line 479 of file nameser.h.
T_IPSECKEY
#define T_IPSECKEY ns_t_ipseckey
Definition at line 470 of file nameser.h.
T_ISDN
#define T_ISDN ns_t_isdn
Definition at line 450 of file nameser.h.
T_IXFR
#define T_IXFR ns_t_ixfr
Definition at line 500 of file nameser.h.
T_KEY
#define T_KEY ns_t_key
Definition at line 455 of file nameser.h.
T_L32
#define T_L32 ns_t_l32
Definition at line 493 of file nameser.h.
T_L64
#define T_L64 ns_t_l64
Definition at line 494 of file nameser.h.
T_LOC
#define T_LOC ns_t_loc
Definition at line 459 of file nameser.h.
T_LP
#define T_LP ns_t_lp
Definition at line 495 of file nameser.h.
T_MAILA
#define T_MAILA ns_t_maila
Definition at line 503 of file nameser.h.
T_MAILB
#define T_MAILB ns_t_mailb
Definition at line 502 of file nameser.h.
T_MB
#define T_MB ns_t_mb
Definition at line 437 of file nameser.h.
T_MD
#define T_MD ns_t_md
Definition at line 433 of file nameser.h.
T_MF
#define T_MF ns_t_mf
Definition at line 434 of file nameser.h.
T_MG
#define T_MG ns_t_mg
Definition at line 438 of file nameser.h.
T_MINFO
#define T_MINFO ns_t_minfo
Definition at line 444 of file nameser.h.
T_MR
#define T_MR ns_t_mr
Definition at line 439 of file nameser.h.
T_MX
#define T_MX ns_t_mx
Definition at line 445 of file nameser.h.
T_NAPTR
#define T_NAPTR ns_t_naptr
Definition at line 465 of file nameser.h.
T_NID
#define T_NID ns_t_nid
Definition at line 492 of file nameser.h.
T_NIMLOC
#define T_NIMLOC ns_t_nimloc
Definition at line 462 of file nameser.h.
T_NINFO
#define T_NINFO ns_t_ninfo
Definition at line 480 of file nameser.h.
T_NS
#define T_NS ns_t_ns
Definition at line 432 of file nameser.h.
T_NSAP
#define T_NSAP ns_t_nsap
Definition at line 452 of file nameser.h.
T_NSAP_PTR
#define T_NSAP_PTR ns_t_nsap_ptr
Definition at line 453 of file nameser.h.
T_NSEC
#define T_NSEC ns_t_nsec
Definition at line 472 of file nameser.h.
T_NSEC3
#define T_NSEC3 ns_t_nsec3
Definition at line 475 of file nameser.h.
T_NSEC3PARAM
#define T_NSEC3PARAM ns_t_nsec3param
Definition at line 476 of file nameser.h.
T_NULL
#define T_NULL ns_t_null
Definition at line 440 of file nameser.h.
T_NXT
#define T_NXT ns_t_nxt
Definition at line 460 of file nameser.h.
T_OPENPGPKEY
#define T_OPENPGPKEY ns_t_openpgpkey
Definition at line 485 of file nameser.h.
T_PTR
#define T_PTR ns_t_ptr
Definition at line 442 of file nameser.h.
T_PX
#define T_PX ns_t_px
Definition at line 456 of file nameser.h.
T_RKEY
#define T_RKEY ns_t_rkey
Definition at line 481 of file nameser.h.
T_RP
#define T_RP ns_t_rp
Definition at line 447 of file nameser.h.
T_RRSIG
#define T_RRSIG ns_t_rrsig
Definition at line 471 of file nameser.h.
T_RT
#define T_RT ns_t_rt
Definition at line 451 of file nameser.h.
T_SIG
#define T_SIG ns_t_sig
Definition at line 454 of file nameser.h.
T_SMIMEA
#define T_SMIMEA ns_t_smimea
Definition at line 478 of file nameser.h.
T_SOA
#define T_SOA ns_t_soa
Definition at line 436 of file nameser.h.
T_SPF
#define T_SPF ns_t_spf
Definition at line 487 of file nameser.h.
T_SRV
#define T_SRV ns_t_srv
Definition at line 463 of file nameser.h.
T_SSHFP
#define T_SSHFP ns_t_sshfp
Definition at line 469 of file nameser.h.
T_TA
#define T_TA ns_t_ta
Definition at line 508 of file nameser.h.
T_TALINK
#define T_TALINK ns_t_talink
Definition at line 482 of file nameser.h.
T_TKEY
#define T_TKEY ns_t_tkey
Definition at line 498 of file nameser.h.
T_TLSA
#define T_TLSA ns_t_tlsa
Definition at line 477 of file nameser.h.
T_TSIG
#define T_TSIG ns_t_tsig
Definition at line 499 of file nameser.h.
T_TXT
#define T_TXT ns_t_txt
Definition at line 446 of file nameser.h.
T_UID
#define T_UID ns_t_uid
Definition at line 489 of file nameser.h.
T_UINFO
#define T_UINFO ns_t_uinfo
Definition at line 488 of file nameser.h.
T_UNSPEC
#define T_UNSPEC ns_t_unspec
Definition at line 491 of file nameser.h.
T_URI
#define T_URI ns_t_uri
Definition at line 505 of file nameser.h.
T_WKS
#define T_WKS ns_t_wks
Definition at line 441 of file nameser.h.
T_X25
#define T_X25 ns_t_x25
Definition at line 449 of file nameser.h.
YXDOMAIN
#define YXDOMAIN ns_r_yxdomain
Definition at line 422 of file nameser.h.
YXRRSET
#define YXRRSET ns_r_yxrrset
Definition at line 423 of file nameser.h.
Typedef Documentation
ns_cert_types
typedef enum __ns_cert_types ns_cert_types
ns_class
typedef enum __ns_class ns_class
ns_flag
typedef enum __ns_flag ns_flag
ns_key_types
typedef enum __ns_key_types ns_key_types
ns_msg
typedef struct __ns_msg ns_msg
ns_opcode
typedef enum __ns_opcode ns_opcode
ns_rcode
typedef enum __ns_rcode ns_rcode
ns_rr
typedef struct __ns_rr ns_rr
ns_sect
typedef enum __ns_sect ns_sect
ns_tcp_tsig_state
typedef struct ns_tcp_tsig_state ns_tcp_tsig_state
Definition at line 1 of file nameser.h.
ns_tsig_key
typedef struct ns_tsig_key ns_tsig_key
Definition at line 1 of file nameser.h.
ns_type
typedef enum __ns_type ns_type
ns_update_operation
typedef enum __ns_update_operation ns_update_operation
Enumeration Type Documentation
__ns_cert_types
enum __ns_cert_types
Enumerator
cert_t_pkix
cert_t_spki
cert_t_pgp
cert_t_url
cert_t_oid
Definition at line 263 of file nameser.h.
{
     cert_t_pkix = 1,
     cert_t_spki = 2,
     cert_t_pgp  = 3,
     cert_t_url  = 253,
     cert_t_oid  = 254
 } ns_cert_types;
__ns_class
enum __ns_class
Enumerator
ns_c_invalid
ns_c_in
ns_c_2
ns_c_chaos
ns_c_hs
ns_c_none
ns_c_any
ns_c_max
ns_c_invalid
ns_c_in
ns_c_2
ns_c_chaos
ns_c_hs
ns_c_none
ns_c_any
ns_c_max
Definition at line 245 of file nameser.h.
{
     ns_c_invalid = 0,
     ns_c_in = 1,
     ns_c_2 = 2,
     ns_c_chaos = 3,
     ns_c_hs = 4,
     ns_c_none = 254,
     ns_c_any = 255,
     ns_c_max = 65536
 } ns_class;
__ns_flag
enum __ns_flag
Enumerator
ns_f_qr
ns_f_opcode
ns_f_aa
ns_f_tc
ns_f_rd
ns_f_ra
ns_f_z
ns_f_ad
ns_f_cd
ns_f_rcode
ns_f_max
Definition at line 75 of file nameser.h.
{
     ns_f_qr,
     ns_f_opcode,
     ns_f_aa,
     ns_f_tc,
     ns_f_rd,
     ns_f_ra,
     ns_f_z,
     ns_f_ad,
     ns_f_cd,
     ns_f_rcode,
     ns_f_max
 } ns_flag;
__ns_key_types
enum __ns_key_types
Enumerator
ns_kt_rsa
ns_kt_dh
ns_kt_dsa
ns_kt_private
Definition at line 256 of file nameser.h.
{
     ns_kt_rsa = 1,
     ns_kt_dh  = 2,
     ns_kt_dsa = 3,
     ns_kt_private = 254
 } ns_key_types;
__ns_opcode
enum __ns_opcode
Enumerator
ns_o_query
ns_o_iquery
ns_o_status
ns_o_notify
ns_o_update
ns_o_max
Definition at line 89 of file nameser.h.
{
     ns_o_query = 0,
     ns_o_iquery = 1,
     ns_o_status = 2,
     ns_o_notify = 4,
     ns_o_update = 5,
     ns_o_max = 6
 } ns_opcode;
__ns_rcode
enum __ns_rcode
Enumerator
ns_r_noerror
ns_r_formerr
ns_r_servfail
ns_r_nxdomain
ns_r_notimpl
ns_r_refused
ns_r_yxdomain
ns_r_yxrrset
ns_r_nxrrset
ns_r_notauth
ns_r_notzone
ns_r_max
ns_r_badvers
ns_r_badsig
ns_r_badkey
ns_r_badtime
ns_r_noerror
ns_r_formerr
ns_r_servfail
ns_r_nxdomain
ns_r_notimpl
ns_r_refused
ns_r_yxdomain
ns_r_yxrrset
ns_r_nxrrset
ns_r_notauth
ns_r_notzone
ns_r_max
ns_r_badvers
ns_r_badsig
ns_r_badkey
ns_r_badtime
Definition at line 98 of file nameser.h.
{
     ns_r_noerror = 0,
     ns_r_formerr = 1,
     ns_r_servfail = 2,
     ns_r_nxdomain = 3,
     ns_r_notimpl = 4,
     ns_r_refused = 5,
     ns_r_yxdomain = 6,
     ns_r_yxrrset = 7,
     ns_r_nxrrset = 8,
     ns_r_notauth = 9,
     ns_r_notzone = 10,
     ns_r_max = 11,
     ns_r_badvers = 16,
     ns_r_badsig = 16,
     ns_r_badkey = 17,
     ns_r_badtime = 18
 } ns_rcode;
__ns_sect
enum __ns_sect
Enumerator
ns_s_qd
ns_s_zn
ns_s_an
ns_s_pr
ns_s_ns
ns_s_ud
ns_s_ar
ns_s_max
Definition at line 28 of file nameser.h.
{
     ns_s_qd = 0,
     ns_s_zn = 0,
     ns_s_an = 1,
     ns_s_pr = 1,
     ns_s_ns = 2,
     ns_s_ud = 2,
     ns_s_ar = 3,
     ns_s_max = 4
 } ns_sect;
__ns_type
enum __ns_type
Enumerator
ns_t_invalid
ns_t_a
ns_t_ns
ns_t_md
ns_t_mf
ns_t_cname
ns_t_soa
ns_t_mb
ns_t_mg
ns_t_mr
ns_t_null
ns_t_wks
ns_t_ptr
ns_t_hinfo
ns_t_minfo
ns_t_mx
ns_t_txt
ns_t_rp
ns_t_afsdb
ns_t_x25
ns_t_isdn
ns_t_rt
ns_t_nsap
ns_t_nsap_ptr
ns_t_sig
ns_t_key
ns_t_px
ns_t_gpos
ns_t_aaaa
ns_t_loc
ns_t_nxt
ns_t_eid
ns_t_nimloc
ns_t_srv
ns_t_atma
ns_t_naptr
ns_t_kx
ns_t_cert
ns_t_a6
ns_t_dname
ns_t_sink
ns_t_opt
ns_t_apl
ns_t_tkey
ns_t_tsig
ns_t_ixfr
ns_t_axfr
ns_t_mailb
ns_t_maila
ns_t_any
ns_t_zxfr
ns_t_max
ns_t_invalid
ns_t_a
ns_t_ns
ns_t_md
ns_t_mf
ns_t_cname
ns_t_soa
ns_t_mb
ns_t_mg
ns_t_mr
ns_t_null
ns_t_wks
ns_t_ptr
ns_t_hinfo
ns_t_minfo
ns_t_mx
ns_t_txt
ns_t_rp
ns_t_afsdb
ns_t_x25
ns_t_isdn
ns_t_rt
ns_t_nsap
ns_t_nsap_ptr
ns_t_sig
ns_t_key
ns_t_px
ns_t_gpos
ns_t_aaaa
ns_t_loc
ns_t_nxt
ns_t_eid
ns_t_nimloc
ns_t_srv
ns_t_atma
ns_t_naptr
ns_t_kx
ns_t_cert
ns_t_a6
ns_t_dname
ns_t_sink
ns_t_opt
ns_t_apl
ns_t_ds
ns_t_sshfp
ns_t_ipseckey
ns_t_rrsig
ns_t_nsec
ns_t_dnskey
ns_t_dhcid
ns_t_nsec3
ns_t_nsec3param
ns_t_tlsa
ns_t_smimea
ns_t_hip
ns_t_ninfo
ns_t_rkey
ns_t_talink
ns_t_cds
ns_t_cdnskey
ns_t_openpgpkey
ns_t_csync
ns_t_spf
ns_t_uinfo
ns_t_uid
ns_t_gid
ns_t_unspec
ns_t_nid
ns_t_l32
ns_t_l64
ns_t_lp
ns_t_eui48
ns_t_eui64
ns_t_tkey
ns_t_tsig
ns_t_ixfr
ns_t_axfr
ns_t_mailb
ns_t_maila
ns_t_any
ns_t_zxfr
ns_t_uri
ns_t_caa
ns_t_avc
ns_t_ta
ns_t_dlv
ns_t_max
Definition at line 147 of file nameser.h.
{
     ns_t_invalid = 0,
     ns_t_a = 1,
     ns_t_ns = 2,
     ns_t_md = 3,
     ns_t_mf = 4,
     ns_t_cname = 5,
     ns_t_soa = 6,
     ns_t_mb = 7,
     ns_t_mg = 8,
     ns_t_mr = 9,
     ns_t_null = 10,
     ns_t_wks = 11,
     ns_t_ptr = 12,
     ns_t_hinfo = 13,
     ns_t_minfo = 14,
     ns_t_mx = 15,
     ns_t_txt = 16,
     ns_t_rp = 17,
     ns_t_afsdb = 18,
     ns_t_x25 = 19,
     ns_t_isdn = 20,
     ns_t_rt = 21,
     ns_t_nsap = 22,
     ns_t_nsap_ptr = 23,
     ns_t_sig = 24,
     ns_t_key = 25,
     ns_t_px = 26,
     ns_t_gpos = 27,
     ns_t_aaaa = 28,
     ns_t_loc = 29,
     ns_t_nxt = 30,
     ns_t_eid = 31,
     ns_t_nimloc = 32,
     ns_t_srv = 33,
     ns_t_atma = 34,
     ns_t_naptr = 35,
     ns_t_kx = 36,
     ns_t_cert = 37,
     ns_t_a6 = 38,
     ns_t_dname = 39,
     ns_t_sink = 40,
     ns_t_opt = 41,
     ns_t_apl = 42,
     ns_t_ds = 43,
     ns_t_sshfp = 44,
     ns_t_ipseckey = 45,
     ns_t_rrsig = 46,
     ns_t_nsec = 47,
     ns_t_dnskey = 48,
     ns_t_dhcid = 49,
     ns_t_nsec3 = 50,
     ns_t_nsec3param = 51,
     ns_t_tlsa = 52,
     ns_t_smimea = 53,
     ns_t_hip = 55,
     ns_t_ninfo = 56,
     ns_t_rkey = 57,
     ns_t_talink = 58,
     ns_t_cds = 59,
     ns_t_cdnskey = 60,
     ns_t_openpgpkey = 61,
     ns_t_csync = 62,
     ns_t_spf = 99,
     ns_t_uinfo = 100,
     ns_t_uid = 101,
     ns_t_gid = 102,
     ns_t_unspec = 103,
     ns_t_nid = 104,
     ns_t_l32 = 105,
     ns_t_l64 = 106,
     ns_t_lp = 107,
     ns_t_eui48 = 108,
     ns_t_eui64 = 109,
     ns_t_tkey = 249,
     ns_t_tsig = 250,
     ns_t_ixfr = 251,
     ns_t_axfr = 252,
     ns_t_mailb = 253,
     ns_t_maila = 254,
     ns_t_any = 255,
     ns_t_zxfr = 256,
     ns_t_uri = 256,
     ns_t_caa = 257,
     ns_t_avc = 258,
     ns_t_ta = 32768,
     ns_t_dlv = 32769,
     ns_t_max = 65536
 } ns_type;
__ns_update_operation
enum __ns_update_operation
Enumerator
ns_uop_delete
ns_uop_add
ns_uop_max
Definition at line 117 of file nameser.h.
{
     ns_uop_delete = 0,
     ns_uop_add = 1,
     ns_uop_max = 2
 } ns_update_operation;
Function Documentation
ns_get16()
unsigned ns_get16 (const unsigned char * cp)
Definition at line 4 of file arpa-nameser-stubs.cpp.
{
     return cp[0] << 8 | cp[1];
 }
References cp.
Referenced by main().
ns_get32()
unsigned long ns_get32 (const unsigned char * cp)
Definition at line 8 of file arpa-nameser-stubs.cpp.
{
     return (unsigned)cp[0] << 24 | cp[1] << 16 | cp[2] << 8 | cp[3];
 }
References cp.
Referenced by main().
ns_initparse()
int ns_initparse (const unsigned char * msg, int msglen, ns_msg * handle)
Definition at line 50 of file ns_parse.c.
 {
     int i, r;
     handle->_msg = msg;
     handle->_eom = msg + msglen;
     if (msglen < (2 + ns_s_max) * NS_INT16SZ) goto bad;
     NS_GET16(handle->_id, msg);
     NS_GET16(handle->_flags, msg);
     for (i = 0; i < ns_s_max; i++) NS_GET16(handle->_counts[i], msg);
     for (i = 0; i < ns_s_max; i++) {
         if (handle->_counts[i]) {
             handle->_sections[i] = msg;
             r = ns_skiprr(msg, handle->_eom, i, handle->_counts[i]);
             if (r < 0) return -1;
             msg += r;
         } else {
             handle->_sections[i] = NULL;
         }
     }
     if (msg != handle->_eom) goto bad;
     handle->_sect = ns_s_max;
     handle->_rrnum = -1;
     handle->_msg_ptr = NULL;
     return 0;
 bad:
     errno = EMSGSIZE;
     return -1;
 }
References __ns_msg::_counts, __ns_msg::_eom, __ns_msg::_flags, __ns_msg::_id, __ns_msg::_msg, __ns_msg::_msg_ptr, __ns_msg::_rrnum, __ns_msg::_sect, __ns_msg::_sections, EMSGSIZE, errno, i, NS_GET16, NS_INT16SZ, ns_s_max, ns_skiprr(), NULL, and r.
ns_name_uncompress()
int ns_name_uncompress (const unsigned char * msg, const unsigned char * eom, const unsigned char * src, char * dst, size_t dstsiz)
Definition at line 163 of file ns_parse.c.
 {
     int r;
     r = dn_expand(msg, eom, src, dst, dstsiz);
     if (r < 0) errno = EMSGSIZE;
     return r;
 }
References dn_expand(), EMSGSIZE, errno, and r.
Referenced by ns_parserr().
ns_parserr()
int ns_parserr (ns_msg * handle, ns_sect section, int rrnum, ns_rr * rr)
Definition at line 104 of file ns_parse.c.
 {
     int r;
     if (section < 0 || section >= ns_s_max) goto bad;
     if (section != handle->_sect) {
         handle->_sect = section;
         handle->_rrnum = 0;
         handle->_msg_ptr = handle->_sections[section];
     }
     if (rrnum == -1) rrnum = handle->_rrnum;
     if (rrnum < 0 || rrnum >= handle->_counts[section]) goto bad;
     if (rrnum < handle->_rrnum) {
         handle->_rrnum = 0;
         handle->_msg_ptr = handle->_sections[section];
     }
     if (rrnum > handle->_rrnum) {
         r = ns_skiprr(handle->_msg_ptr, handle->_eom, section, rrnum - handle->_rrnum);
         if (r < 0) return -1;
         handle->_msg_ptr += r;
         handle->_rrnum = rrnum;
     }
     r = ns_name_uncompress(handle->_msg, handle->_eom, handle->_msg_ptr, rr->name, NS_MAXDNAME);
     if (r < 0) return -1;
     handle->_msg_ptr += r;
     if (2 * NS_INT16SZ > handle->_eom - handle->_msg_ptr) goto size;
     NS_GET16(rr->type, handle->_msg_ptr);
     NS_GET16(rr->rr_class, handle->_msg_ptr);
     if (section != ns_s_qd) {
         if (NS_INT32SZ + NS_INT16SZ > handle->_eom - handle->_msg_ptr) goto size;
         NS_GET32(rr->ttl, handle->_msg_ptr);
         NS_GET16(rr->rdlength, handle->_msg_ptr);
         if (rr->rdlength > handle->_eom - handle->_msg_ptr) goto size;
         rr->rdata = handle->_msg_ptr;
         handle->_msg_ptr += rr->rdlength;
     } else {
         rr->ttl = 0;
         rr->rdlength = 0;
         rr->rdata = NULL;
     }
     handle->_rrnum++;
     if (handle->_rrnum > handle->_counts[section]) {
         handle->_sect = section + 1;
         if (handle->_sect == ns_s_max) {
             handle->_rrnum = -1;
             handle->_msg_ptr = NULL;
         } else {
             handle->_rrnum = 0;
         }
     }
     return 0;
 bad:
     errno = ENODEV;
     return -1;
 size:
     errno = EMSGSIZE;
     return -1;
 }
References __ns_msg::_counts, __ns_msg::_eom, __ns_msg::_msg, __ns_msg::_msg_ptr, __ns_msg::_rrnum, __ns_msg::_sect, __ns_msg::_sections, EMSGSIZE, ENODEV, errno, __ns_rr::name, NS_GET16, NS_GET32, NS_INT16SZ, NS_INT32SZ, NS_MAXDNAME, ns_name_uncompress(), ns_s_max, ns_s_qd, ns_skiprr(), NULL, r, __ns_rr::rdata, __ns_rr::rdlength, __ns_rr::rr_class, size, __ns_rr::ttl, and __ns_rr::type.
ns_put16()
void ns_put16 (unsigned s, unsigned char * cp)
Definition at line 12 of file arpa-nameser-stubs.cpp.
{
     *cp++ = s >> 8;
     *cp++ = s;
 }
References cp.
Referenced by main().
ns_put32()
void ns_put32 (unsigned long l, unsigned char * cp)
Definition at line 17 of file arpa-nameser-stubs.cpp.
{
     *cp++ = l >> 24;
     *cp++ = l >> 16;
     *cp++ = l >> 8;
     *cp++ = l;
 }
References cp.
Referenced by main().
ns_skiprr()
int ns_skiprr (const unsigned char * ptr, const unsigned char * eom, ns_sect section, int count)
Definition at line 80 of file ns_parse.c.
 {
     const unsigned char *p = ptr;
     int r;
     while (count--) {
         r = dn_skipname(p, eom);
         if (r < 0) goto bad;
         if (r + 2 * NS_INT16SZ > eom - p) goto bad;
         p += r + 2 * NS_INT16SZ;
         if (section != ns_s_qd) {
             if (NS_INT32SZ + NS_INT16SZ > eom - p) goto bad;
             p += NS_INT32SZ;
             NS_GET16(r, p);
             if (r > eom - p) goto bad;
             p += r;
         }
     }
     return p - ptr;
 bad:
     errno = EMSGSIZE;
     return -1;
 }
References count, dn_skipname(), EMSGSIZE, errno, NS_GET16, NS_INT16SZ, NS_INT32SZ, ns_s_qd, p, and r.
Referenced by ns_initparse(), and ns_parserr().
Variable Documentation
_ns_flagdata
const struct _ns_flagdata _ns_flagdata[] extern
Definition at line 1 of file ns_parse.c.