Fennix: Userspace/apps/base/busybox/archival/gzip.c File Reference
gzip.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Data Structures
struct globals
struct ct_data
struct tree_desc
struct globals2
union ct_data.fc
union ct_data.dl
Macros
#define Assert(cond, msg)
#define Trace(x)
#define Tracev(x)
#define Tracevv(x)
#define Tracec(c, x)
#define Tracecv(c, x)
#define SMALL_MEM
#define INBUFSIZ 0x2000 /* input buffer size */
#define OUTBUFSIZ 8192 /* output buffer size */
#define DIST_BUFSIZE 0x2000 /* buffer for distances, see trees.c */
#define ASCII_FLAG 0x01 /* bit 0 set: file probably ascii text */
#define CONTINUATION 0x02 /* bit 1 set: continuation of multi-part gzip file */
#define EXTRA_FIELD 0x04 /* bit 2 set: extra field present */
#define ORIG_NAME 0x08 /* bit 3 set: original file name present */
#define COMMENT 0x10 /* bit 4 set: file comment present */
#define RESERVED 0xC0 /* bit 6,7: reserved */
#define UNKNOWN 0xffff
#define BINARY 0
#define ASCII 1
#define WSIZE 0x8000 /* window size--must be a power of two, and */
#define MIN_MATCH 3
#define MAX_MATCH 258
#define MIN_LOOKAHEAD (MAX_MATCH+MIN_MATCH+1)
#define MAX_DIST (WSIZE-MIN_LOOKAHEAD)
#define MAX_PATH_LEN 1024 /* max pathname length */
#define seekable() 0 /* force sequential output */
#define translate_eol 0 /* no option -a yet */
#define BITS 16
#define INIT_BITS 9 /* Initial number of bits per code */
#define BIT_MASK 0x1f /* Mask for 'number of compression bits' */
#define MAX_SUFFIX 30
#define HASH_BITS 13 /* Number of bits used to hash strings */
#define HASH_SIZE (unsigned)(1<<HASH_BITS)
#define HASH_MASK (HASH_SIZE-1)
#define WMASK (WSIZE-1)
#define TOO_FAR 4096
#define DECLARE(type, array, size) type * array
#define ALLOC(type, array, size) array = xzalloc((size_t)(((size)+1L)/2) * 2*sizeof(type))
#define FREE(array) do { free(array); array = NULL; } while (0)
#define head (G1.prev + WSIZE) /* hash head (see deflate.c) */
#define H_SHIFT ((HASH_BITS+MIN_MATCH-1) / MIN_MATCH)
#define ifd STDIN_FILENO /* input file descriptor */
#define ofd STDOUT_FILENO /* output file descriptor */
#define BUF_SIZE (int)(8 * sizeof(G1.bi_buf))
#define DEBUG_bits_sent(v) ((void)0)
#define G1 (*(ptr_to_globals - 1))
#define put_8bit(c)
#define OPTIMIZED_PUT_32BIT (CONFIG_GZIP_FAST > 0 && BB_UNALIGNED_MEMACCESS_OK && BB_LITTLE_ENDIAN)
#define check_match(start, match, length) ((void)0)
#define MAX_BITS 15
#define MAX_BL_BITS 7
#define LENGTH_CODES 29
#define LITERALS 256
#define END_BLOCK 256
#define L_CODES (LITERALS+1+LENGTH_CODES)
#define D_CODES 30
#define BL_CODES 19
#define STORED_BLOCK 0
#define STATIC_TREES 1
#define DYN_TREES 2
#define LIT_BUFSIZE 0x2000
#define REP_3_6 16
#define REPZ_3_10 17
#define REPZ_11_138 18
#define Freq fc.freq
#define Code fc.code
#define Dad dl.dad
#define Len dl.len
#define HEAP_SIZE (2*L_CODES + 1)
#define G2ptr ((struct globals2*)(ptr_to_globals))
#define G2 (*G2ptr)
#define SEND_CODE(c, tree) send_bits(tree[c].Code, tree[c].Len)
#define D_CODE(dist) ((dist) < 256 ? G2.dist_code[dist] : G2.dist_code[256 + ((dist)>>7)])
#define SMALLER(tree, n, m)
#define tree desc->dyn_tree
#define SMALLEST 1
#define PQREMOVE(tree, top)
#define UPDATE_HASH(h, c) (h = (((h)<<H_SHIFT) ^ (c)) & HASH_MASK)
#define FLUSH_BLOCK(eof)
#define INSERT_STRING(s, match_head)
Typedefs
typedef uint8_t uch
typedef uint16_t ush
typedef uint32_t ulg
typedef int32_t lng
typedef ush Pos
typedef unsigned IPos
typedef struct ct_data ct_data
typedef struct tree_desc tree_desc
Enumerations
enum {
WINDOW_SIZE = 2 * WSIZE , comp_level_minus4 = 6 - 4 , max_chain_length = 128 , max_lazy_match = 16 ,
max_insert_length = max_lazy_match , good_match = 8 , nice_match = 128
}
Functions
static void flush_outbuf (void)
static void put_16bit (ush w)
static void put_32bit (ulg n)
static ALWAYS_INLINE void flush_outbuf_if_32bit_optimized (void)
static void updcrc (uch *s, unsigned n)
static unsigned file_read (void *buf, unsigned size)
static void send_bits (unsigned value, unsigned length)
static unsigned bi_reverse (unsigned code, int len)
static void bi_windup (void)
static void copy_block (const char *buf, unsigned len, int header)
static void fill_window (void)
static void fill_window_if_needed (void)
static int longest_match (IPos cur_match)
static void init_block (void)
static void pqdownheap (const ct_data *tree, int k)
static void gen_bitlen (const tree_desc *desc)
static void gen_codes (ct_data *tree, int max_code)
static void build_tree (tree_desc *desc)
static void scan_tree (ct_data *tree, int max_code)
static void send_tree (const ct_data *tree, int max_code)
static int build_bl_tree (void)
static void send_all_trees (int lcodes, int dcodes, int blcodes)
static int ct_tally (int dist, int lc)
static void compress_block (const ct_data *ltree, const ct_data *dtree)
static void flush_block (const char *buf, ulg stored_len, int eof)
static NOINLINE void deflate (void)
static void bi_init (void)
static void lm_init (void)
static void ct_init (void)
static void zip (void)
static IF_DESKTOP (long long)
int gzip_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const uint8_t extra_lbits[LENGTH_CODES] ALIGN1
Data Structure Documentation
ct_data
struct ct_data
Definition at line 951 of file gzip.c.
Data Fields
union ct_data dl
union ct_data fc
tree_desc
struct tree_desc
Definition at line 970 of file gzip.c.
Data Fields
ct_data * dyn_tree
int elems
int extra_base
const uint8_t * extra_bits
int max_code
int max_length
ct_data * static_tree
globals2
struct globals2
Definition at line 980 of file gzip.c.
Data Fields
var as_regex__tmpvar
var awk_printf__tmpvar
int base_dist[D_CODES]
int base_length[LENGTH_CODES]
unsigned bl_count[MAX_BITS+1]
tree_desc bl_desc
ct_data bl_tree[2 *BL_CODES+1]
tree_desc d_desc
uch depth[2 *L_CODES+1]
uch dist_code[512]
ct_data dyn_dtree[2 *D_CODES+1]
ct_data dyn_ltree[HEAP_SIZE]
var * evaluate__fnargs
unsigned evaluate__seed
regex_t evaluate__sreg
tsplitter exec_builtin__tspl
var exit__tmpvar
smalluint exitcode
uch flag_bit
uch flag_buf[LIT_BUFSIZE/8]
uch flags
tsplitter fsplitter
char g_buf[MAXVARFMT+1]
ush heap[HEAP_SIZE]
int heap_len
int heap_max
var * intvar[NUM_INTERNAL_VARS]
tree_desc l_desc
unsigned last_dist
unsigned last_flags
unsigned last_lit
uch length_code[MAX_MATCH - MIN_MATCH+1]
var main__tmpvar
smallint next_input_file__files_happen
rstream next_input_file__rsm
ulg opt_len
var ptest__tmpvar
tsplitter rsplitter
char * split_f0__fstrings
ct_data static_dtree[D_CODES]
ulg static_len
ct_data static_ltree[L_CODES+2]
uint32_t t_info
int t_lineno
char * t_string
uint32_t t_tclass
ct_data.fc
union ct_data.fc
Definition at line 952 of file gzip.c.
Data Fields
ush code
ush freq
ct_data.dl
union ct_data.dl
Definition at line 956 of file gzip.c.
Data Fields
ush dad
ush len
Macro Definition Documentation
ALLOC
#define ALLOC (type, array, size) array = xzalloc((size_t)(((size)+1L)/2) * 2*sizeof(type))
Definition at line 305 of file gzip.c.
ASCII
#define ASCII 1
Definition at line 166 of file gzip.c.
ASCII_FLAG
#define ASCII_FLAG 0x01 /* bit 0 set: file probably ascii text */
Definition at line 156 of file gzip.c.
Assert
#define Assert (cond, msg)
Definition at line 111 of file gzip.c.
BINARY
#define BINARY 0
Definition at line 165 of file gzip.c.
BIT_MASK
#define BIT_MASK 0x1f /* Mask for 'number of compression bits' */
Definition at line 198 of file gzip.c.
BITS
#define BITS 16
Definition at line 194 of file gzip.c.
BL_CODES
#define BL_CODES 19
Definition at line 879 of file gzip.c.
BUF_SIZE
#define BUF_SIZE (int)(8 * sizeof(G1.bi_buf))
Definition at line 404 of file gzip.c.
check_match
#define check_match (start, match, length) ((void)0)
Definition at line 805 of file gzip.c.
Code
#define Code fc.code
Definition at line 963 of file gzip.c.
COMMENT
#define COMMENT 0x10 /* bit 4 set: file comment present */
Definition at line 160 of file gzip.c.
CONTINUATION
#define CONTINUATION 0x02 /* bit 1 set: continuation of multi-part gzip file */
Definition at line 157 of file gzip.c.
D_CODE
#define D_CODE (dist) ((dist) < 256 ? G2.dist_code[dist] : G2.dist_code[256 + ((dist)>>7)])
Definition at line 1084 of file gzip.c.
D_CODES
#define D_CODES 30
Definition at line 876 of file gzip.c.
Dad
#define Dad dl.dad
Definition at line 964 of file gzip.c.
DEBUG_bits_sent
#define DEBUG_bits_sent (v) ((void)0)
Definition at line 415 of file gzip.c.
DECLARE
#define DECLARE (type, array, size) type * array
Definition at line 303 of file gzip.c.
DIST_BUFSIZE
#define DIST_BUFSIZE 0x2000 /* buffer for distances, see trees.c */
Definition at line 149 of file gzip.c.
DYN_TREES
#define DYN_TREES 2
Definition at line 904 of file gzip.c.
END_BLOCK
#define END_BLOCK 256
Definition at line 870 of file gzip.c.
EXTRA_FIELD
#define EXTRA_FIELD 0x04 /* bit 2 set: extra field present */
Definition at line 158 of file gzip.c.
FLUSH_BLOCK
#define FLUSH_BLOCK (eof)
Value:
    flush_block( \
        G1.block_start >= 0L \
            ? (char*)&G1.window[(unsigned)G1.block_start] \
            : (char*)NULL, \
        (ulg)G1.strstart - G1.block_start, \
        (eof) \
    )
Definition at line 1788 of file gzip.c.
FREE
#define FREE (array) do { free(array); array = NULL; } while (0)
Definition at line 307 of file gzip.c.
Freq
#define Freq fc.freq
Definition at line 962 of file gzip.c.
G1
#define G1 (*(ptr_to_globals - 1))
Definition at line 419 of file gzip.c.
G2
#define G2 (*G2ptr)
Definition at line 1069 of file gzip.c.
G2ptr
#define G2ptr ((struct globals2*)(ptr_to_globals))
Definition at line 1068 of file gzip.c.
H_SHIFT
#define H_SHIFT ((HASH_BITS+MIN_MATCH-1) / MIN_MATCH)
Definition at line 370 of file gzip.c.
HASH_BITS
#define HASH_BITS 13 /* Number of bits used to hash strings */
Definition at line 223 of file gzip.c.
HASH_MASK
#define HASH_MASK (HASH_SIZE-1)
Definition at line 234 of file gzip.c.
HASH_SIZE
#define HASH_SIZE (unsigned)(1<<HASH_BITS)
Definition at line 233 of file gzip.c.
head
#define head (G1.prev + WSIZE) /* hash head (see deflate.c) */
Definition at line 337 of file gzip.c.
HEAP_SIZE
#define HEAP_SIZE (2*L_CODES + 1)
Definition at line 967 of file gzip.c.
ifd
#define ifd STDIN_FILENO /* input file descriptor */
Definition at line 385 of file gzip.c.
INBUFSIZ
#define INBUFSIZ 0x2000 /* input buffer size */
Definition at line 133 of file gzip.c.
INIT_BITS
#define INIT_BITS 9 /* Initial number of bits per code */
Definition at line 196 of file gzip.c.
INSERT_STRING
#define INSERT_STRING (s, match_head)
Value:
do { \
    UPDATE_HASH(G1.ins_h, G1.window[(s) + MIN_MATCH-1]); \
    G1.prev[(s) & WMASK] = match_head = head[G1.ins_h]; \
    head[G1.ins_h] = (s); \
} while (0)
Definition at line 1803 of file gzip.c.
L_CODES
#define L_CODES (LITERALS+1+LENGTH_CODES)
Definition at line 873 of file gzip.c.
Len
#define Len dl.len
Definition at line 965 of file gzip.c.
LENGTH_CODES
#define LENGTH_CODES 29
Definition at line 864 of file gzip.c.
LIT_BUFSIZE
#define LIT_BUFSIZE 0x2000
Definition at line 909 of file gzip.c.
LITERALS
#define LITERALS 256
Definition at line 867 of file gzip.c.
MAX_BITS
#define MAX_BITS 15
Definition at line 858 of file gzip.c.
MAX_BL_BITS
#define MAX_BL_BITS 7
Definition at line 861 of file gzip.c.
MAX_DIST
#define MAX_DIST (WSIZE-MIN_LOOKAHEAD)
Definition at line 181 of file gzip.c.
MAX_MATCH
#define MAX_MATCH 258
Definition at line 173 of file gzip.c.
MAX_PATH_LEN
#define MAX_PATH_LEN 1024 /* max pathname length */
Definition at line 187 of file gzip.c.
MAX_SUFFIX
#define MAX_SUFFIX 30
Definition at line 211 of file gzip.c.
MIN_LOOKAHEAD
#define MIN_LOOKAHEAD (MAX_MATCH+MIN_MATCH+1)
Definition at line 176 of file gzip.c.
MIN_MATCH
#define MIN_MATCH 3
Definition at line 172 of file gzip.c.
ofd
#define ofd STDOUT_FILENO /* output file descriptor */
Definition at line 386 of file gzip.c.
OPTIMIZED_PUT_32BIT
#define OPTIMIZED_PUT_32BIT (CONFIG_GZIP_FAST > 0 && BB_UNALIGNED_MEMACCESS_OK && BB_LITTLE_ENDIAN)
Definition at line 483 of file gzip.c.
ORIG_NAME
#define ORIG_NAME 0x08 /* bit 3 set: original file name present */
Definition at line 159 of file gzip.c.
OUTBUFSIZ
#define OUTBUFSIZ 8192 /* output buffer size */
Definition at line 141 of file gzip.c.
PQREMOVE
#define PQREMOVE (tree, top)
Value:
do { \
    top = G2.heap[SMALLEST]; \
    G2.heap[SMALLEST] = G2.heap[G2.heap_len--]; \
    pqdownheap(tree, SMALLEST); \
} while (0)
Definition at line 1305 of file gzip.c.
put_8bit
#define put_8bit (c)
Value:
do { \
    G1.outbuf[G1.outcnt++] = (c); \
    if (G1.outcnt == OUTBUFSIZ) \
        flush_outbuf(); \
} while (0)
Definition at line 437 of file gzip.c.
REP_3_6
#define REP_3_6 16
Definition at line 941 of file gzip.c.
REPZ_11_138
#define REPZ_11_138 18
Definition at line 945 of file gzip.c.
REPZ_3_10
#define REPZ_3_10 17
Definition at line 943 of file gzip.c.
RESERVED
#define RESERVED 0xC0 /* bit 6,7: reserved */
Definition at line 161 of file gzip.c.
seekable
#define seekable () 0 /* force sequential output */
Definition at line 190 of file gzip.c.
SEND_CODE
#define SEND_CODE (c, tree) send_bits(tree[c].Code, tree[c].Len)
Definition at line 1075 of file gzip.c.
SMALL_MEM
#define SMALL_MEM
Definition at line 122 of file gzip.c.
SMALLER
#define SMALLER (tree, n, m)
Value:
    (tree[n].Freq < tree[m].Freq \
    || (tree[n].Freq == tree[m].Freq && G2.depth[n] <= G2.depth[m]))
Definition at line 1123 of file gzip.c.
SMALLEST
#define SMALLEST 1
Definition at line 1302 of file gzip.c.
STATIC_TREES
#define STATIC_TREES 1
Definition at line 903 of file gzip.c.
STORED_BLOCK
#define STORED_BLOCK 0
Definition at line 902 of file gzip.c.
TOO_FAR
#define TOO_FAR 4096
Definition at line 238 of file gzip.c.
Trace
#define Trace (x)
Definition at line 112 of file gzip.c.
Tracec
#define Tracec (c, x)
Definition at line 115 of file gzip.c.
Tracecv
#define Tracecv (c, x)
Definition at line 116 of file gzip.c.
Tracev
#define Tracev (x)
Definition at line 113 of file gzip.c.
Tracevv
#define Tracevv (x)
Definition at line 114 of file gzip.c.
translate_eol
#define translate_eol 0 /* no option -a yet */
Definition at line 191 of file gzip.c.
tree
#define tree desc->dyn_tree
UNKNOWN
#define UNKNOWN 0xffff
Definition at line 164 of file gzip.c.
UPDATE_HASH
#define UPDATE_HASH (h, c) (h = (((h)<<H_SHIFT) ^ (c)) & HASH_MASK)
Definition at line 1774 of file gzip.c.
WMASK
#define WMASK (WSIZE-1)
Definition at line 235 of file gzip.c.
WSIZE
#define WSIZE 0x8000 /* window size--must be a power of two, and */
Definition at line 169 of file gzip.c.
Typedef Documentation
ct_data
typedef struct ct_data ct_data
IPos
typedef unsigned IPos
Definition at line 251 of file gzip.c.
lng
typedef int32_t lng
Definition at line 248 of file gzip.c.
Pos
typedef ush Pos
Definition at line 250 of file gzip.c.
tree_desc
typedef struct tree_desc tree_desc
uch
typedef uint8_t uch
Definition at line 245 of file gzip.c.
ulg
typedef uint32_t ulg
Definition at line 247 of file gzip.c.
ush
typedef uint16_t ush
Definition at line 246 of file gzip.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
WINDOW_SIZE
comp_level_minus4
max_chain_length
max_lazy_match
max_insert_length
good_match
nice_match
Definition at line 256 of file gzip.c.
      {
     WINDOW_SIZE = 2 * WSIZE,
 /* window size, 2*WSIZE except for MMAP or BIG_MEM, where it is the
  * input file length plus MIN_LOOKAHEAD.
  */
 #if !ENABLE_FEATURE_GZIP_LEVELS
     comp_level_minus4 = 6 - 4,
     max_chain_length = 128,
 /* To speed up deflation, hash chains are never searched beyond this length.
  * A higher limit improves compression ratio but degrades the speed.
  */
     max_lazy_match = 16,
 /* Attempt to find a better match only when the current match is strictly
  * smaller than this value. This mechanism is used only for compression
  * levels >= 4.
  */
     max_insert_length = max_lazy_match,
 /* Insert new strings in the hash table only if the match length
  * is not greater than this length. This saves time but degrades compression.
  * max_insert_length is used only for compression levels <= 3.
  */
     good_match = 8,
 /* Use a faster search when the previous match is longer than this */
 /* Values for max_lazy_match, good_match and max_chain_length, depending on
  * the desired pack level (0..9). The values given below have been tuned to
  * exclude worst case performance for pathological files. Better values may be
  * found for specific files.
  */
     nice_match = 128,   /* Stop searching when current match exceeds this */
 /* Note: the deflate() code requires max_lazy >= MIN_MATCH and max_chain >= 4
  * For deflate_fast() (levels <= 3) good is ignored and lazy has a different
  * meaning.
  */
 #endif /* ENABLE_FEATURE_GZIP_LEVELS */
 };
Function Documentation
bi_init()
static void bi_init (void) static
Definition at line 1917 of file gzip.c.
 {
     //G1.bi_buf = 0; // globals are zeroed in pack_gzip()
     //G1.bi_valid = 0; // globals are zeroed in pack_gzip()
     //DEBUG_bits_sent(= 0L); // globals are zeroed in pack_gzip()
 }
Referenced by zip().
bi_reverse()
static unsigned bi_reverse (unsigned code, int len) static
Definition at line 581 of file gzip.c.
 {
     unsigned res = 0;
     while (1) {
         res |= code & 1;
         if (--len <= 0) return res;
         code >>= 1;
         res <<= 1;
     }
 }
References code, and len.
Referenced by ct_init(), and gen_codes().
bi_windup()
static void bi_windup (void) static
Definition at line 596 of file gzip.c.
 {
     unsigned bits = G1.bi_buf;
     int cnt = G1.bi_valid;
     while (cnt > 0) {
         put_8bit(bits);
         bits >>= 8;
         cnt -= 8;
     }
     G1.bi_buf = 0;
     G1.bi_valid = 0;
     DEBUG_bits_sent(= (G1.bits_sent + 7) & ~7);
 }
References cnt, DEBUG_bits_sent, G1, and put_8bit.
Referenced by copy_block(), and flush_block().
build_bl_tree()
static int build_bl_tree (void) static
Definition at line 1511 of file gzip.c.
 {
     int max_blindex;    /* index of last bit length code of non zero freq */
     /* Determine the bit length frequencies for literal and distance trees */
     scan_tree(G2.dyn_ltree, G2.l_desc.max_code);
     scan_tree(G2.dyn_dtree, G2.d_desc.max_code);
     /* Build the bit length tree: */
     build_tree(&G2.bl_desc);
     /* opt_len now includes the length of the tree representations, except
      * the lengths of the bit lengths codes and the 5+5+4 bits for the counts.
      */
     /* Determine the number of bit length codes to send. The pkzip format
      * requires that at least 4 bit length codes be sent. (appnote.txt says
      * 3 but the actual value used is 4.)
      */
     for (max_blindex = BL_CODES - 1; max_blindex >= 3; max_blindex--) {
         if (G2.bl_tree[bl_order[max_blindex]].Len != 0)
             break;
     }
     /* Update opt_len to include the bit length tree and counts */
     G2.opt_len += 3 * (max_blindex + 1) + 5 + 5 + 4;
     Tracev((stderr, "\ndyn trees: dyn %ld, stat %ld", (long)G2.opt_len, (long)G2.static_len));
     return max_blindex;
 }
References BL_CODES, build_tree(), G2, scan_tree(), stderr, and Tracev.
Referenced by flush_block().
build_tree()
static void build_tree (tree_desc * desc) static
Definition at line 1312 of file gzip.c.
 {
     ct_data *tree = desc->dyn_tree;
     ct_data *stree = desc->static_tree;
     int elems = desc->elems;
     int n, m;           /* iterate over heap elements */
     int max_code = -1;  /* largest code with non zero frequency */
     int node = elems;   /* next internal node of the tree */
     /* Construct the initial heap, with least frequent element in
      * heap[SMALLEST]. The sons of heap[n] are heap[2*n] and heap[2*n+1].
      * heap[0] is not used.
      */
     G2.heap_len = 0;
     G2.heap_max = HEAP_SIZE;
     for (n = 0; n < elems; n++) {
         if (tree[n].Freq != 0) {
             G2.heap[++G2.heap_len] = max_code = n;
             G2.depth[n] = 0;
         } else {
             tree[n].Len = 0;
         }
     }
     /* The pkzip format requires that at least one distance code exists,
      * and that at least one bit should be sent even if there is only one
      * possible code. So to avoid special checks later on we force at least
      * two codes of non zero frequency.
      */
     while (G2.heap_len < 2) {
         int new = G2.heap[++G2.heap_len] = (max_code < 2 ? ++max_code : 0);
         tree[new].Freq = 1;
         G2.depth[new] = 0;
         G2.opt_len--;
         if (stree)
             G2.static_len -= stree[new].Len;
         /* new is 0 or 1 so it does not have extra bits */
     }
     desc->max_code = max_code;
     /* The elements heap[heap_len/2+1 .. heap_len] are leaves of the tree,
      * establish sub-heaps of increasing lengths:
      */
     for (n = G2.heap_len / 2; n >= 1; n--)
         pqdownheap(tree, n);
     /* Construct the Huffman tree by repeatedly combining the least two
      * frequent nodes.
      */
     do {
         PQREMOVE(tree, n);  /* n = node of least frequency */
         m = G2.heap[SMALLEST];  /* m = node of next least frequency */
         G2.heap[--G2.heap_max] = n; /* keep the nodes sorted by frequency */
         G2.heap[--G2.heap_max] = m;
         /* Create a new node father of n and m */
         tree[node].Freq = tree[n].Freq + tree[m].Freq;
         G2.depth[node] = MAX(G2.depth[n], G2.depth[m]) + 1;
         tree[n].Dad = tree[m].Dad = (ush) node;
 #ifdef DUMP_BL_TREE
         if (tree == G2.bl_tree) {
             bb_error_msg("\nnode %d(%d), sons %d(%d) %d(%d)",
                     node, tree[node].Freq, n, tree[n].Freq, m, tree[m].Freq);
         }
 #endif
         /* and insert the new node in the heap */
         G2.heap[SMALLEST] = node++;
         pqdownheap(tree, SMALLEST);
     } while (G2.heap_len >= 2);
     G2.heap[--G2.heap_max] = G2.heap[SMALLEST];
     /* At this point, the fields freq and dad are set. We can now
      * generate the bit lengths.
      */
     gen_bitlen(desc);
     /* The field len is now set, we can generate the bit codes */
     gen_codes(tree, max_code);
 }
References bb_error_msg(), tree_desc::dyn_tree, tree_desc::elems, Freq, G2, gen_bitlen(), gen_codes(), HEAP_SIZE, MAX, tree_desc::max_code, n, pqdownheap(), PQREMOVE, SMALLEST, tree_desc::static_tree, and tree.
Referenced by build_bl_tree(), and flush_block().
compress_block()
static void compress_block (const ct_data * ltree, const ct_data * dtree) static
Definition at line 1630 of file gzip.c.
 {
     unsigned dist;          /* distance of matched string */
     int lc;                 /* match length or unmatched char (if dist == 0) */
     unsigned lx = 0;        /* running index in l_buf */
     unsigned dx = 0;        /* running index in d_buf */
     unsigned fx = 0;        /* running index in flag_buf */
     uch flag = 0;           /* current flags */
     unsigned code;          /* the code to send */
     int extra;              /* number of extra bits to send */
     if (G2.last_lit != 0) do {
         if ((lx & 7) == 0)
             flag = G2.flag_buf[fx++];
         lc = G1.l_buf[lx++];
         if ((flag & 1) == 0) {
             SEND_CODE(lc, ltree);   /* send a literal byte */
             Tracecv(lc > ' ', (stderr, " '%c' ", lc));
         } else {
             /* Here, lc is the match length - MIN_MATCH */
             code = G2.length_code[lc];
             SEND_CODE(code + LITERALS + 1, ltree);  /* send the length code */
             extra = extra_lbits[code];
             if (extra != 0) {
                 lc -= G2.base_length[code];
                 send_bits(lc, extra);   /* send the extra length bits */
             }
             dist = G1.d_buf[dx++];
             /* Here, dist is the match distance - 1 */
             code = D_CODE(dist);
             Assert(code < D_CODES, "bad d_code");
             SEND_CODE(code, dtree); /* send the distance code */
             extra = extra_dbits[code];
             if (extra != 0) {
                 dist -= G2.base_dist[code];
                 send_bits(dist, extra); /* send the extra distance bits */
             }
         }           /* literal or match pair ? */
         flag >>= 1;
     } while (lx < G2.last_lit);
     SEND_CODE(END_BLOCK, ltree);
 }
References Assert, code, D_CODE, D_CODES, END_BLOCK, fx, G1, G2, LITERALS, send_bits(), SEND_CODE, stderr, and Tracecv.
Referenced by flush_block().
copy_block()
static void copy_block (const char * buf, unsigned len, int header) static
Definition at line 615 of file gzip.c.
 {
     bi_windup();        /* align on byte boundary */
     if (header) {
         unsigned v = ((uint16_t)len) | ((~len) << 16);
         put_32bit(v);
         DEBUG_bits_sent(+= 2 * 16);
     }
     DEBUG_bits_sent(+= (ulg) len << 3);
     while (len--) {
         put_8bit(*buf++);
     }
     /* The above can 32-bit misalign outbuf */
     if (G1.outcnt & 3) /* syscalls are expensive, is it really misaligned? */
         flush_outbuf_if_32bit_optimized();
 }
References bi_windup(), buf, DEBUG_bits_sent, flush_outbuf_if_32bit_optimized(), G1, len, put_32bit(), and put_8bit.
Referenced by flush_block().
ct_init()
static void ct_init (void) static
Definition at line 1969 of file gzip.c.
 {
     int n;              /* iterates over tree elements */
     int length;         /* length value */
     int code;           /* code value */
     int dist;           /* distance index */
 //  //G2.compressed_len = 0L; // globals are zeroed in pack_gzip()
 #ifdef NOT_NEEDED
     if (G2.static_dtree[0].Len != 0)
         return;         /* ct_init already called */
 #endif
     /* Initialize the mapping length (0..255) -> length code (0..28) */
     length = 0;
     for (code = 0; code < LENGTH_CODES - 1; code++) {
         G2.base_length[code] = length;
         for (n = 0; n < (1 << extra_lbits[code]); n++) {
             G2.length_code[length++] = code;
         }
     }
     Assert(length == 256, "ct_init: length != 256");
     /* Note that the length 255 (match length 258) can be represented
      * in two different ways: code 284 + 5 bits or code 285, so we
      * overwrite length_code[255] to use the best encoding:
      */
     G2.length_code[length - 1] = code;
     /* Initialize the mapping dist (0..32K) -> dist code (0..29) */
     dist = 0;
     for (code = 0; code < 16; code++) {
         G2.base_dist[code] = dist;
         for (n = 0; n < (1 << extra_dbits[code]); n++) {
             G2.dist_code[dist++] = code;
         }
     }
     Assert(dist == 256, "ct_init: dist != 256");
     dist >>= 7;         /* from now on, all distances are divided by 128 */
     for (; code < D_CODES; code++) {
         G2.base_dist[code] = dist << 7;
         for (n = 0; n < (1 << (extra_dbits[code] - 7)); n++) {
             G2.dist_code[256 + dist++] = code;
         }
     }
     Assert(dist == 256, "ct_init: 256+dist != 512");
     /* Construct the codes of the static literal tree */
     //for (n = 0; n <= MAX_BITS; n++) // globals are zeroed in pack_gzip()
     //  G2.bl_count[n] = 0;
     n = 0;
     while (n <= 143) {
         G2.static_ltree[n++].Len = 8;
         //G2.bl_count[8]++;
     }
     //G2.bl_count[8] = 143 + 1;
     while (n <= 255) {
         G2.static_ltree[n++].Len = 9;
         //G2.bl_count[9]++;
     }
     //G2.bl_count[9] = 255 - 143;
     while (n <= 279) {
         G2.static_ltree[n++].Len = 7;
         //G2.bl_count[7]++;
     }
     //G2.bl_count[7] = 279 - 255;
     while (n <= 287) {
         G2.static_ltree[n++].Len = 8;
         //G2.bl_count[8]++;
     }
     //G2.bl_count[8] += 287 - 279;
     G2.bl_count[7] = 279 - 255;
     G2.bl_count[8] = (143 + 1) + (287 - 279);
     G2.bl_count[9] = 255 - 143;
     /* Codes 286 and 287 do not exist, but we must include them in the
      * tree construction to get a canonical Huffman tree (longest code
      * all ones)
      */
     gen_codes((ct_data *) G2.static_ltree, L_CODES + 1);
     /* The static distance tree is trivial: */
     for (n = 0; n < D_CODES; n++) {
         G2.static_dtree[n].Len = 5;
         G2.static_dtree[n].Code = bi_reverse(n, 5);
     }
     /* Initialize the first block of the first file: */
     init_block();
 }
References Assert, bi_reverse(), code, D_CODES, G2, gen_codes(), init_block(), L_CODES, LENGTH_CODES, and n.
Referenced by zip().
ct_tally()
static int ct_tally (int dist, int lc) static
Definition at line 1573 of file gzip.c.
 {
     G1.l_buf[G2.last_lit++] = lc;
     if (dist == 0) {
         /* lc is the unmatched char */
         G2.dyn_ltree[lc].Freq++;
     } else {
         /* Here, lc is the match length - MIN_MATCH */
         dist--;         /* dist = match distance - 1 */
         Assert((ush) dist < (ush) MAX_DIST
          && (ush) lc <= (ush) (MAX_MATCH - MIN_MATCH)
          && (ush) D_CODE(dist) < (ush) D_CODES, "ct_tally: bad match"
         );
         G2.dyn_ltree[G2.length_code[lc] + LITERALS + 1].Freq++;
         G2.dyn_dtree[D_CODE(dist)].Freq++;
         G1.d_buf[G2.last_dist++] = dist;
         G2.flags |= G2.flag_bit;
     }
     G2.flag_bit <<= 1;
     /* Output the flags if they fill a byte: */
     if ((G2.last_lit & 7) == 0) {
         G2.flag_buf[G2.last_flags++] = G2.flags;
         G2.flags = 0;
         G2.flag_bit = 1;
     }
     /* Try to guess if it is profitable to stop the current block here */
     if ((G2.last_lit & 0xfff) == 0) {
         /* Compute an upper bound for the compressed length */
         ulg out_length = G2.last_lit * 8L;
         ulg in_length = (ulg) G1.strstart - G1.block_start;
         int dcode;
         for (dcode = 0; dcode < D_CODES; dcode++) {
             out_length += G2.dyn_dtree[dcode].Freq * (5L + extra_dbits[dcode]);
         }
         out_length >>= 3;
         Trace((stderr,
                 "\nlast_lit %u, last_dist %u, in %ld, out ~%ld(%ld%%) ",
                 G2.last_lit, G2.last_dist,
                 (long)in_length, (long)out_length,
                 100L - out_length * 100L / in_length));
         if (G2.last_dist < G2.last_lit / 2 && out_length < in_length / 2)
             return 1;
     }
     return (G2.last_lit == LIT_BUFSIZE - 1 || G2.last_dist == DIST_BUFSIZE);
     /* We avoid equality with LIT_BUFSIZE because of wraparound at 64K
      * on 16 bit machines and because stored blocks are restricted to
      * 64K-1 bytes.
      */
 }
References Assert, D_CODE, D_CODES, DIST_BUFSIZE, for(), G1, G2, LIT_BUFSIZE, LITERALS, MAX_DIST, MAX_MATCH, MIN_MATCH, out_length, stderr, and Trace.
Referenced by deflate().
deflate()
static NOINLINE void deflate (void) static
Definition at line 1810 of file gzip.c.
 {
     IPos hash_head;     /* head of hash chain */
     IPos prev_match;    /* previous match */
     int flush;          /* set if current block must be flushed */
     int match_available = 0;    /* set if previous match exists */
     unsigned match_length = MIN_MATCH - 1;  /* length of best match */
     /* Process the input block. */
     while (G1.lookahead != 0) {
         /* Insert the string window[strstart .. strstart+2] in the
          * dictionary, and set hash_head to the head of the hash chain:
          */
         INSERT_STRING(G1.strstart, hash_head);
         /* Find the longest match, discarding those <= prev_length.
          */
         G1.prev_length = match_length;
         prev_match = G1.match_start;
         match_length = MIN_MATCH - 1;
         if (hash_head != 0 && G1.prev_length < max_lazy_match
          && G1.strstart - hash_head <= MAX_DIST
         ) {
             /* To simplify the code, we prevent matches with the string
              * of window index 0 (in particular we have to avoid a match
              * of the string with itself at the start of the input file).
              */
             match_length = longest_match(hash_head);
             /* longest_match() sets match_start */
             if (match_length > G1.lookahead)
                 match_length = G1.lookahead;
             /* Ignore a length 3 match if it is too distant: */
             if (match_length == MIN_MATCH && G1.strstart - G1.match_start > TOO_FAR) {
                 /* If prev_match is also MIN_MATCH, G1.match_start is garbage
                  * but we will ignore the current match anyway.
                  */
                 match_length--;
             }
         }
         /* If there was a match at the previous step and the current
          * match is not better, output the previous match:
          */
         if (G1.prev_length >= MIN_MATCH && match_length <= G1.prev_length) {
             check_match(G1.strstart - 1, prev_match, G1.prev_length);
             flush = ct_tally(G1.strstart - 1 - prev_match, G1.prev_length - MIN_MATCH);
             /* Insert in hash table all strings up to the end of the match.
              * strstart-1 and strstart are already inserted.
              */
             G1.lookahead -= G1.prev_length - 1;
             G1.prev_length -= 2;
             do {
                 G1.strstart++;
                 INSERT_STRING(G1.strstart, hash_head);
                 /* strstart never exceeds WSIZE-MAX_MATCH, so there are
                  * always MIN_MATCH bytes ahead. If lookahead < MIN_MATCH
                  * these bytes are garbage, but it does not matter since the
                  * next lookahead bytes will always be emitted as literals.
                  */
             } while (--G1.prev_length != 0);
             match_available = 0;
             match_length = MIN_MATCH - 1;
             G1.strstart++;
             if (flush) {
                 FLUSH_BLOCK(0);
                 G1.block_start = G1.strstart;
             }
         } else if (match_available) {
             /* If there was no match at the previous position, output a
              * single literal. If there was a match but the current match
              * is longer, truncate the previous match to a single literal.
              */
             Tracevv((stderr, "%c", G1.window[G1.strstart - 1]));
             if (ct_tally(0, G1.window[G1.strstart - 1])) {
                 FLUSH_BLOCK(0);
                 G1.block_start = G1.strstart;
             }
             G1.strstart++;
             G1.lookahead--;
         } else {
             /* There is no previous match to compare with, wait for
              * the next step to decide.
              */
             match_available = 1;
             G1.strstart++;
             G1.lookahead--;
         }
         Assert(G1.strstart <= G1.isize && G1.lookahead <= G1.isize, "a bit too far");
         /* Make sure that we always have enough lookahead, except
          * at the end of the input file. We need MAX_MATCH bytes
          * for the next match, plus MIN_MATCH bytes to insert the
          * string following the next match.
          */
         fill_window_if_needed();
     }
     if (match_available)
         ct_tally(0, G1.window[G1.strstart - 1]);
     FLUSH_BLOCK(1); /* eof */
 }
References Assert, check_match, ct_tally(), fill_window_if_needed(), flush(), FLUSH_BLOCK, G1, INSERT_STRING, longest_match(), MAX_DIST, max_lazy_match, MIN_MATCH, stderr, TOO_FAR, and Tracevv.
Referenced by zip().
file_read()
static unsigned file_read (void * buf, unsigned size) static
Definition at line 522 of file gzip.c.
 {
     unsigned len;
     Assert(G1.insize == 0, "l_buf not empty");
     len = safe_read(ifd, buf, size);
     if (len == (unsigned)(-1) || len == 0)
         return len;
     updcrc(buf, len);
     G1.isize += len;
     return len;
 }
References Assert, buf, G1, ifd, len, safe_read(), size, and updcrc().
Referenced by fill_window(), and lm_init().
fill_window()
static void fill_window (void) static
Definition at line 641 of file gzip.c.
 {
     unsigned n, m;
     unsigned more = WINDOW_SIZE - G1.lookahead - G1.strstart;
     /* Amount of free space at the end of the window. */
     /* If the window is almost full and there is insufficient lookahead,
      * move the upper half to the lower one to make room in the upper half.
      */
     if (more == (unsigned) -1) {
         /* Very unlikely, but possible on 16 bit machine if strstart == 0
          * and lookahead == 1 (input done one byte at time)
          */
         more--;
     } else if (G1.strstart >= WSIZE + MAX_DIST) {
         /* By the IN assertion, the window is not empty so we can't confuse
          * more == 0 with more == 64K on a 16 bit machine.
          */
         Assert(WINDOW_SIZE == 2 * WSIZE, "no sliding with BIG_MEM");
         memcpy(G1.window, G1.window + WSIZE, WSIZE);
         G1.match_start -= WSIZE;
         G1.strstart -= WSIZE;   /* we now have strstart >= MAX_DIST: */
         G1.block_start -= WSIZE;
         for (n = 0; n < HASH_SIZE; n++) {
             m = head[n];
             head[n] = (Pos) (m >= WSIZE ? m - WSIZE : 0);
         }
         for (n = 0; n < WSIZE; n++) {
             m = G1.prev[n];
             G1.prev[n] = (Pos) (m >= WSIZE ? m - WSIZE : 0);
             /* If n is not on any hash chain, prev[n] is garbage but
              * its value will never be used.
              */
         }
         more += WSIZE;
     }
     /* At this point, more >= 2 */
     if (!G1.eofile) {
         n = file_read(G1.window + G1.strstart + G1.lookahead, more);
         if (n == 0 || n == (unsigned) -1) {
             G1.eofile = 1;
         } else {
             G1.lookahead += n;
         }
     }
 }
References Assert, file_read(), G1, HASH_SIZE, head, MAX_DIST, memcpy, n, WINDOW_SIZE, and WSIZE.
Referenced by fill_window_if_needed().
fill_window_if_needed()
static void fill_window_if_needed (void) static
Definition at line 691 of file gzip.c.
 {
     while (G1.lookahead < MIN_LOOKAHEAD && !G1.eofile)
         fill_window();
 }
References fill_window(), G1, and MIN_LOOKAHEAD.
Referenced by deflate(), and lm_init().
flush_block()
static void flush_block (const char * buf, ulg stored_len, int eof) static
Definition at line 1680 of file gzip.c.
 {
     ulg opt_lenb, static_lenb;      /* opt_len and static_len in bytes */
     int max_blindex;                /* index of last bit length code of non zero freq */
     G2.flag_buf[G2.last_flags] = G2.flags;   /* Save the flags for the last 8 items */
     /* Construct the literal and distance trees */
     build_tree(&G2.l_desc);
     Tracev((stderr, "\nlit data: dyn %ld, stat %ld", (long)G2.opt_len, (long)G2.static_len));
     build_tree(&G2.d_desc);
     Tracev((stderr, "\ndist data: dyn %ld, stat %ld", (long)G2.opt_len, (long)G2.static_len));
     /* At this point, opt_len and static_len are the total bit lengths of
      * the compressed block data, excluding the tree representations.
      */
     /* Build the bit length tree for the above two trees, and get the index
      * in bl_order of the last bit length code to send.
      */
     max_blindex = build_bl_tree();
     /* Determine the best encoding. Compute first the block length in bytes */
     opt_lenb = (G2.opt_len + 3 + 7) >> 3;
     static_lenb = (G2.static_len + 3 + 7) >> 3;
     Trace((stderr,
             "\nopt %lu(%lu) stat %lu(%lu) stored %lu lit %u dist %u ",
             (unsigned long)opt_lenb, (unsigned long)G2.opt_len,
             (unsigned long)static_lenb, (unsigned long)G2.static_len,
             (unsigned long)stored_len,
             G2.last_lit, G2.last_dist));
     if (static_lenb <= opt_lenb)
         opt_lenb = static_lenb;
     /* If compression failed and this is the first and last block,
      * and if the zip file can be seeked (to rewrite the local header),
      * the whole file is transformed into a stored file:
      */
 // seekable() is constant FALSE in busybox, and G2.compressed_len is disabled
 // (this was the only user)
 //  if (stored_len <= opt_lenb && eof && G2.compressed_len == 0L && seekable()) {
 //      /* Since LIT_BUFSIZE <= 2*WSIZE, the input data must be there: */
 //      if (buf == NULL)
 //          bb_error_msg("block vanished");
 //
 //      G2.compressed_len = stored_len << 3;
 //      copy_block(buf, (unsigned) stored_len, 0);  /* without header */
 //  } else
     if (stored_len + 4 <= opt_lenb && buf != NULL) {
         /* 4: two words for the lengths */
         /* The test buf != NULL is only necessary if LIT_BUFSIZE > WSIZE.
          * Otherwise we can't have processed more than WSIZE input bytes since
          * the last block flush, because compression would have been
          * successful. If LIT_BUFSIZE <= WSIZE, it is never too late to
          * transform a block into a stored block.
          */
         send_bits((STORED_BLOCK << 1) + eof, 3);    /* send block type */
 //      G2.compressed_len = ((G2.compressed_len + 3 + 7) & ~7L)
 //              + ((stored_len + 4) << 3);
         copy_block(buf, (unsigned) stored_len, 1);  /* with header */
     } else
     if (static_lenb == opt_lenb) {
         send_bits((STATIC_TREES << 1) + eof, 3);
         compress_block((ct_data *) G2.static_ltree, (ct_data *) G2.static_dtree);
 //      G2.compressed_len += 3 + G2.static_len;
     } else {
         send_bits((DYN_TREES << 1) + eof, 3);
         send_all_trees(G2.l_desc.max_code + 1, G2.d_desc.max_code + 1,
                     max_blindex + 1);
         compress_block((ct_data *) G2.dyn_ltree, (ct_data *) G2.dyn_dtree);
 //      G2.compressed_len += 3 + G2.opt_len;
     }
 //  Assert(G2.compressed_len == G1.bits_sent, "bad compressed size");
     init_block();
     if (eof) {
         bi_windup();
 //      G2.compressed_len += 7; /* align on byte boundary */
     }
 //  Tracev((stderr, "\ncomprlen %lu(%lu) ",
 //          (unsigned long)G2.compressed_len >> 3,
 //          (unsigned long)G2.compressed_len - 7 * eof));
     return; /* was "return G2.compressed_len >> 3;" */
 }
References bi_windup(), buf, build_bl_tree(), build_tree(), compress_block(), copy_block(), DYN_TREES, G2, init_block(), NULL, send_all_trees(), send_bits(), STATIC_TREES, stderr, STORED_BLOCK, Trace, and Tracev.
flush_outbuf()
static void flush_outbuf (void) static
Definition at line 425 of file gzip.c.
 {
     if (G1.outcnt == 0)
         return;
     xwrite(ofd, (char *) G1.outbuf, G1.outcnt);
     G1.outcnt = 0;
 }
References G1, ofd, and xwrite().
Referenced by flush_outbuf_if_32bit_optimized(), put_16bit(), and zip().
flush_outbuf_if_32bit_optimized()
static ALWAYS_INLINE void flush_outbuf_if_32bit_optimized (void) static
Definition at line 500 of file gzip.c.
 {
     /* If put_32bit() performs 32bit stores && it is used in send_bits() */
     if (OPTIMIZED_PUT_32BIT && BUF_SIZE > 16)
         flush_outbuf();
 }
References BUF_SIZE, flush_outbuf(), and OPTIMIZED_PUT_32BIT.
Referenced by copy_block(), and zip().
gen_bitlen()
static void gen_bitlen (const tree_desc * desc) static
Definition at line 1161 of file gzip.c.
 {
 #define tree desc->dyn_tree
     int h;          /* heap index */
     int n, m;       /* iterate over the tree elements */
     int bits;       /* bit length */
     int overflow;   /* number of elements with bit length too large */
     for (bits = 0; bits < ARRAY_SIZE(G2.bl_count); bits++)
         G2.bl_count[bits] = 0;
     /* In a first pass, compute the optimal bit lengths (which may
      * overflow in the case of the bit length tree).
      */
     tree[G2.heap[G2.heap_max]].Len = 0; /* root of the heap */
     overflow = 0;
     for (h = G2.heap_max + 1; h < HEAP_SIZE; h++) {
         ulg f;          /* frequency */
         int xbits;      /* extra bits */
         n = G2.heap[h];
         bits = tree[tree[n].Dad].Len + 1;
         if (bits > desc->max_length) {
             bits = desc->max_length;
             overflow++;
         }
         tree[n].Len = (ush) bits;
         /* We overwrite tree[n].Dad which is no longer needed */
         if (n > desc->max_code)
             continue;   /* not a leaf node */
         G2.bl_count[bits]++;
         xbits = 0;
         if (n >= desc->extra_base)
             xbits = desc->extra_bits[n - desc->extra_base];
         f = tree[n].Freq;
         G2.opt_len += f * (bits + xbits);
         if (desc->static_tree)
             G2.static_len += f * (desc->static_tree[n].Len + xbits);
     }
     if (overflow == 0)
         return;
     Trace((stderr, "\nbit length overflow\n"));
     /* This happens for example on obj2 and pic of the Calgary corpus */
     /* Find the first bit length which could increase: */
     do {
         bits = desc->max_length - 1;
         while (G2.bl_count[bits] == 0)
             bits--;
         G2.bl_count[bits]--;    /* move one leaf down the tree */
         G2.bl_count[bits + 1] += 2; /* move one overflow item as its brother */
         G2.bl_count[desc->max_length]--;
         /* The brother of the overflow item also moves one step up,
          * but this does not affect bl_count[desc->max_length]
          */
         overflow -= 2;
     } while (overflow > 0);
     /* Now recompute all bit lengths, scanning in increasing frequency.
      * h is still equal to HEAP_SIZE. (It is simpler to reconstruct all
      * lengths instead of fixing only the wrong ones. This idea is taken
      * from 'ar' written by Haruhiko Okumura.)
      */
     for (bits = desc->max_length; bits != 0; bits--) {
         n = G2.bl_count[bits];
         while (n != 0) {
             m = G2.heap[--h];
             if (m > desc->max_code)
                 continue;
             if (tree[m].Len != (unsigned) bits) {
                 Trace((stderr, "code %d bits %d->%d\n", m, tree[m].Len, bits));
                 G2.opt_len += ((int32_t) bits - tree[m].Len) * tree[m].Freq;
                 tree[m].Len = bits;
             }
             n--;
         }
     }
 #undef tree
 }
References ARRAY_SIZE, tree_desc::extra_base, tree_desc::extra_bits, f, for(), G2, h, HEAP_SIZE, Len, tree_desc::max_code, tree_desc::max_length, n, tree_desc::static_tree, stderr, Trace, and tree.
Referenced by build_tree().
gen_codes()
static void gen_codes (ct_data * tree, int max_code) static
Definition at line 1254 of file gzip.c.
 {
     /* next_code[] and code used to be "ush", but "unsigned" results in smaller code */
     unsigned next_code[MAX_BITS + 1]; /* next code value for each bit length */
     unsigned code = 0;      /* running code value */
     int bits;               /* bit index */
     int n;                  /* code index */
     /* The distribution counts are first used to generate the code values
      * without bit reversal.
      */
     for (bits = 1; bits <= MAX_BITS; bits++) {
         next_code[bits] = code = (code + G2.bl_count[bits - 1]) << 1;
     }
     /* Check that the bit counts in bl_count are consistent. The last code
      * must be all ones.
      */
     Assert(code + G2.bl_count[MAX_BITS] - 1 == (1 << MAX_BITS) - 1,
             "inconsistent bit counts");
     Tracev((stderr, "\ngen_codes: max_code %d ", max_code));
     for (n = 0; n <= max_code; n++) {
         int len = tree[n].Len;
         if (len == 0)
             continue;
         /* Now reverse the bits */
         tree[n].Code = bi_reverse(next_code[len]++, len);
         Tracec(tree != G2.static_ltree,
                (stderr, "\nn %3d %c l %2d c %4x (%x) ", n,
                 (n > ' ' ? n : ' '), len, tree[n].Code,
                 next_code[len] - 1));
     }
 }
References Assert, bi_reverse(), code, G2, len, MAX_BITS, n, stderr, Tracec, Tracev, and tree.
Referenced by build_tree(), and ct_init().
gzip_main()
int gzip_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 2198 of file gzip.c.
 {
     unsigned opt;
 #if ENABLE_FEATURE_GZIP_LEVELS
     static const struct {
         uint8_t good;
         uint8_t chain_shift;
         uint8_t lazy2;
         uint8_t nice2;
     } gzip_level_config[6] = {
         {4,   4,   4/2,  16/2}, /* Level 4 */
         {8,   5,  16/2,  32/2}, /* Level 5 */
         {8,   7,  16/2, 128/2}, /* Level 6 */
         {8,   8,  32/2, 128/2}, /* Level 7 */
         {32, 10, 128/2, 258/2}, /* Level 8 */
         {32, 12, 258/2, 258/2}, /* Level 9 */
     };
 #endif
     SET_PTR_TO_GLOBALS((char *)xzalloc(sizeof(struct globals)+sizeof(struct globals2))
             + sizeof(struct globals));
     /* Must match bbunzip's constants OPT_STDOUT, OPT_FORCE! */
 #if ENABLE_FEATURE_GZIP_LONG_OPTIONS
     opt = getopt32long(argv, BBUNPK_OPTSTR IF_FEATURE_GZIP_DECOMPRESS("dt") "n123456789", gzip_longopts);
 #else
     opt = getopt32(argv, BBUNPK_OPTSTR IF_FEATURE_GZIP_DECOMPRESS("dt") "n123456789");
 #endif
 #if ENABLE_FEATURE_GZIP_DECOMPRESS /* gunzip_main may not be visible... */
     if (opt & (BBUNPK_OPT_DECOMPRESS|BBUNPK_OPT_TEST)) /* -d and/or -t */
         return gunzip_main(argc, argv);
 #endif
 #if ENABLE_FEATURE_GZIP_LEVELS
     opt >>= (BBUNPK_OPTSTRLEN IF_FEATURE_GZIP_DECOMPRESS(+ 2) + 1); /* drop cfkvq[dt]n bits */
     if (opt == 0)
         opt = 1 << 5; /* default: 6 */
     opt = ffs(opt >> 4); /* Maps -1..-4 to [0], -5 to [1] ... -9 to [5] */
     comp_level_minus4 = opt;
     max_chain_length = 1 << gzip_level_config[opt].chain_shift;
     good_match   = gzip_level_config[opt].good;
     max_lazy_match   = gzip_level_config[opt].lazy2 * 2;
     nice_match   = gzip_level_config[opt].nice2 * 2;
 #endif
     option_mask32 &= BBUNPK_OPTSTRMASK; /* retain only -cfkvq */
     /* Allocate all global buffers (for DYN_ALLOC option) */
     ALLOC(uch, G1.l_buf, INBUFSIZ);
     ALLOC(uch, G1.outbuf, OUTBUFSIZ);
     ALLOC(ush, G1.d_buf, DIST_BUFSIZE);
     ALLOC(uch, G1.window, 2L * WSIZE);
     ALLOC(ush, G1.prev, 1L << BITS);
     /* Initialize the CRC32 table */
     global_crc32_new_table_le();
     argv += optind;
     return bbunpack(argv, pack_gzip, append_ext, "gz");
 }
References ALLOC, append_ext(), argc, argv, bbunpack(), BBUNPK_OPT_DECOMPRESS, BBUNPK_OPT_TEST, BBUNPK_OPTSTR, BBUNPK_OPTSTRLEN, BBUNPK_OPTSTRMASK, BITS, comp_level_minus4, DIST_BUFSIZE, ffs(), G1, getopt32(), getopt32long, global_crc32_new_table_le(), good_match, gunzip_main(), INBUFSIZ, max_chain_length, max_lazy_match, nice_match, opt, optind, option_mask32, OUTBUFSIZ, SET_PTR_TO_GLOBALS, WSIZE, and xzalloc().
IF_DESKTOP()
static IF_DESKTOP (long long) static
Definition at line 2107 of file gzip.c.
 {
     /* Reinit G1.xxx except pointers to allocated buffers, and entire G2 */
     memset(&G1.crc, 0, (sizeof(G1) - offsetof(struct globals, crc)) + sizeof(G2));
     /* Clear input and output buffers */
     //G1.outcnt = 0;
 #ifdef DEBUG
     //G1.insize = 0;
 #endif
     //G1.isize = 0;
     /* Reinit G2.xxx */
     G2.l_desc.dyn_tree     = G2.dyn_ltree;
     G2.l_desc.static_tree  = G2.static_ltree;
     G2.l_desc.extra_bits   = extra_lbits;
     G2.l_desc.extra_base   = LITERALS + 1;
     G2.l_desc.elems        = L_CODES;
     G2.l_desc.max_length   = MAX_BITS;
     //G2.l_desc.max_code     = 0;
     G2.d_desc.dyn_tree     = G2.dyn_dtree;
     G2.d_desc.static_tree  = G2.static_dtree;
     G2.d_desc.extra_bits   = extra_dbits;
     //G2.d_desc.extra_base   = 0;
     G2.d_desc.elems        = D_CODES;
     G2.d_desc.max_length   = MAX_BITS;
     //G2.d_desc.max_code     = 0;
     G2.bl_desc.dyn_tree    = G2.bl_tree;
     //G2.bl_desc.static_tree = NULL;
     G2.bl_desc.extra_bits  = extra_blbits,
     //G2.bl_desc.extra_base  = 0;
     G2.bl_desc.elems       = BL_CODES;
     G2.bl_desc.max_length  = MAX_BL_BITS;
     //G2.bl_desc.max_code    = 0;
 #if 0
     /* Saving of timestamp is disabled. Why?
      * - it is not Y2038-safe.
      * - some people want deterministic results
      *   (normally they'd use -n, but our -n is a nop).
      * - it's bloat.
      * Per RFC 1952, gzfile.time=0 is "no timestamp".
      * If users will demand this to be reinstated,
      * implement -n "don't save timestamp".
      */
     struct stat s;
     s.st_ctime = 0;
     fstat(STDIN_FILENO, &s);
     zip(s.st_ctime);
 #else
     zip();
 #endif
     return 0;
 }
References BL_CODES, D_CODES, fstat(), G1, G2, L_CODES, LITERALS, MAX_BITS, MAX_BL_BITS, memset, offsetof, s, STDIN_FILENO, and zip().
init_block()
static void init_block (void) static
Definition at line 1095 of file gzip.c.
 {
     int n; /* iterates over tree elements */
     /* Initialize the trees. */
     for (n = 0; n < L_CODES; n++)
         G2.dyn_ltree[n].Freq = 0;
     for (n = 0; n < D_CODES; n++)
         G2.dyn_dtree[n].Freq = 0;
     for (n = 0; n < BL_CODES; n++)
         G2.bl_tree[n].Freq = 0;
     G2.dyn_ltree[END_BLOCK].Freq = 1;
     G2.opt_len = G2.static_len = 0;
     G2.last_lit = G2.last_dist = G2.last_flags = 0;
     G2.flags = 0;
     G2.flag_bit = 1;
 }
References BL_CODES, D_CODES, END_BLOCK, for(), G2, L_CODES, and n.
Referenced by ct_init(), and flush_block().
lm_init()
static void lm_init (void) static
Definition at line 1927 of file gzip.c.
 {
     unsigned j;
     /* Initialize the hash table. */
     memset(head, 0, HASH_SIZE * sizeof(*head));
     /* prev will be initialized on the fly */
     /* ??? reduce max_chain_length for binary files */
     //G1.strstart = 0; // globals are zeroed in pack_gzip()
     //G1.block_start = 0L; // globals are zeroed in pack_gzip()
     G1.lookahead = file_read(G1.window,
             sizeof(int) <= 2 ? (unsigned) WSIZE : 2 * WSIZE);
     if (G1.lookahead == 0 || G1.lookahead == (unsigned) -1) {
         G1.eofile = 1;
         G1.lookahead = 0;
         return;
     }
     //G1.eofile = 0; // globals are zeroed in pack_gzip()
     /* Make sure that we always have enough lookahead. This is important
      * if input comes from a device such as a tty.
      */
     fill_window_if_needed();
     //G1.ins_h = 0; // globals are zeroed in pack_gzip()
     for (j = 0; j < MIN_MATCH - 1; j++)
         UPDATE_HASH(G1.ins_h, G1.window[j]);
     /* If lookahead < MIN_MATCH, ins_h is garbage, but this is
      * not important since only literal bytes will be emitted.
      */
 }
References file_read(), fill_window_if_needed(), G1, HASH_SIZE, head, j, memset, MIN_MATCH, UPDATE_HASH, and WSIZE.
Referenced by zip().
longest_match()
static int longest_match (IPos cur_match) static
Definition at line 710 of file gzip.c.
 {
     unsigned chain_length = max_chain_length;   /* max hash chain length */
     uch *scan = G1.window + G1.strstart;    /* current string */
     uch *match; /* matched string */
     int len;    /* length of current match */
     int best_len = G1.prev_length;  /* best match length so far */
     IPos limit = G1.strstart > (IPos) MAX_DIST ? G1.strstart - (IPos) MAX_DIST : 0;
     /* Stop when cur_match becomes <= limit. To simplify the code,
      * we prevent matches with the string of window index 0.
      */
 /* The code is optimized for HASH_BITS >= 8 and MAX_MATCH-2 multiple of 16.
  * It is easy to get rid of this optimization if necessary.
  */
 #if HASH_BITS < 8 || MAX_MATCH != 258
 #  error Code too clever
 #endif
     uch *strend = G1.window + G1.strstart + MAX_MATCH;
     uch scan_end1 = scan[best_len - 1];
     uch scan_end = scan[best_len];
     /* Do not waste too much time if we already have a good match: */
     if (G1.prev_length >= good_match) {
         chain_length >>= 2;
     }
     Assert(G1.strstart <= WINDOW_SIZE - MIN_LOOKAHEAD, "insufficient lookahead");
     do {
         Assert(cur_match < G1.strstart, "no future");
         match = G1.window + cur_match;
         /* Skip to next match if the match length cannot increase
          * or if the match length is less than 2:
          */
         if (match[best_len] != scan_end
          || match[best_len - 1] != scan_end1
          || *match != *scan || *++match != scan[1]
         ) {
             continue;
         }
         /* The check at best_len-1 can be removed because it will be made
          * again later. (This heuristic is not always a win.)
          * It is not necessary to compare scan[2] and match[2] since they
          * are always equal when the other bytes match, given that
          * the hash keys are equal and that HASH_BITS >= 8.
          */
         scan += 2, match++;
         /* We check for insufficient lookahead only every 8th comparison;
          * the 256th check will be made at strstart+258.
          */
         do {
         } while (*++scan == *++match && *++scan == *++match &&
                  *++scan == *++match && *++scan == *++match &&
                  *++scan == *++match && *++scan == *++match &&
                  *++scan == *++match && *++scan == *++match && scan < strend);
         len = MAX_MATCH - (int) (strend - scan);
         scan = strend - MAX_MATCH;
         if (len > best_len) {
             G1.match_start = cur_match;
             best_len = len;
             if (len >= nice_match)
                 break;
             scan_end1 = scan[best_len - 1];
             scan_end = scan[best_len];
         }
     } while ((cur_match = G1.prev[cur_match & WMASK]) > limit
              && --chain_length != 0);
     return best_len;
 }
References Assert, G1, good_match, len, limit(), match(), max_chain_length, MAX_DIST, MAX_MATCH, MIN_LOOKAHEAD, nice_match, WINDOW_SIZE, and WMASK.
Referenced by deflate().
pqdownheap()
static void pqdownheap (const ct_data * tree, int k) static
Definition at line 1127 of file gzip.c.
 {
     int v = G2.heap[k];
     int j = k << 1;     /* left son of k */
     while (j <= G2.heap_len) {
         /* Set j to the smallest of the two sons: */
         if (j < G2.heap_len && SMALLER(tree, G2.heap[j + 1], G2.heap[j]))
             j++;
         /* Exit if v is smaller than both sons */
         if (SMALLER(tree, v, G2.heap[j]))
             break;
         /* Exchange v with the smallest son */
         G2.heap[k] = G2.heap[j];
         k = j;
         /* And continue down the tree, setting j to the left son of k */
         j <<= 1;
     }
     G2.heap[k] = v;
 }
References G2, j, k, SMALLER, and tree.
Referenced by build_tree().
put_16bit()
static void put_16bit (ush w) static
Definition at line 445 of file gzip.c.
 {
     /* GCC 4.2.1 won't optimize out redundant loads of G1.outcnt
      * (probably because of fear of aliasing with G1.outbuf[]
      * stores), do it explicitly:
      */
     unsigned outcnt = G1.outcnt;
     uch *dst = &G1.outbuf[outcnt];
 #if BB_UNALIGNED_MEMACCESS_OK && BB_LITTLE_ENDIAN
     if (outcnt < OUTBUFSIZ-2) {
         /* Common case */
         ush *dst16 = (void*) dst;
         *dst16 = w; /* unaligned LSB 16-bit store */
         G1.outcnt = outcnt + 2;
         return;
     }
     *dst = (uch)w;
     w >>= 8;
     G1.outcnt = ++outcnt;
 #else
     *dst = (uch)w;
     w >>= 8;
     if (outcnt < OUTBUFSIZ-2) {
         /* Common case */
         dst[1] = w;
         G1.outcnt = outcnt + 2;
         return;
     }
     G1.outcnt = ++outcnt;
 #endif
     /* Slowpath: we will need to do flush_outbuf() */
     if (outcnt == OUTBUFSIZ)
         flush_outbuf(); /* here */
     put_8bit(w); /* or here */
 }
References dst, flush_outbuf(), G1, OUTBUFSIZ, put_8bit, and w.
Referenced by put_32bit(), send_bits(), and zip().
put_32bit()
static void put_32bit (ulg n) static
Definition at line 484 of file gzip.c.
 {
     if (OPTIMIZED_PUT_32BIT) {
         unsigned outcnt = G1.outcnt;
         if (outcnt < OUTBUFSIZ-4) {
             /* Common case */
             ulg *dst32 = (void*) &G1.outbuf[outcnt];
             *dst32 = n; /* unaligned LSB 32-bit store */
             //bb_error_msg("%p", dst32); // store alignment debugging
             G1.outcnt = outcnt + 4;
             return;
         }
     }
     put_16bit(n);
     put_16bit(n >> 16);
 }
References G1, n, OPTIMIZED_PUT_32BIT, OUTBUFSIZ, and put_16bit().
Referenced by copy_block(), send_bits(), and zip().
scan_tree()
static void scan_tree (ct_data * tree, int max_code) static
Definition at line 1402 of file gzip.c.
 {
     int n;              /* iterates over all tree elements */
     int prevlen = -1;   /* last emitted length */
     int curlen;         /* length of current code */
     int nextlen = tree[0].Len;  /* length of next code */
     int count = 0;      /* repeat count of the current code */
     int max_count = 7;  /* max repeat count */
     int min_count = 4;  /* min repeat count */
     if (nextlen == 0) {
         max_count = 138;
         min_count = 3;
     }
     tree[max_code + 1].Len = 0xffff; /* guard */
     for (n = 0; n <= max_code; n++) {
         curlen = nextlen;
         nextlen = tree[n + 1].Len;
         if (++count < max_count && curlen == nextlen)
             continue;
         if (count < min_count) {
             G2.bl_tree[curlen].Freq += count;
         } else if (curlen != 0) {
             if (curlen != prevlen)
                 G2.bl_tree[curlen].Freq++;
             G2.bl_tree[REP_3_6].Freq++;
         } else if (count <= 10) {
             G2.bl_tree[REPZ_3_10].Freq++;
         } else {
             G2.bl_tree[REPZ_11_138].Freq++;
         }
         count = 0;
         prevlen = curlen;
         max_count = 7;
         min_count = 4;
         if (nextlen == 0) {
             max_count = 138;
             min_count = 3;
         } else if (curlen == nextlen) {
             max_count = 6;
             min_count = 3;
         }
     }
 }
References count, G2, n, REP_3_6, REPZ_11_138, REPZ_3_10, and tree.
Referenced by build_bl_tree().
send_all_trees()
static void send_all_trees (int lcodes, int dcodes, int blcodes) static
Definition at line 1545 of file gzip.c.
 {
     int rank;           /* index in bl_order */
     Assert(lcodes >= 257 && dcodes >= 1 && blcodes >= 4, "not enough codes");
     Assert(lcodes <= L_CODES && dcodes <= D_CODES
            && blcodes <= BL_CODES, "too many codes");
     Tracev((stderr, "\nbl counts: "));
     send_bits(lcodes - 257, 5); /* not +255 as stated in appnote.txt */
     send_bits(dcodes - 1, 5);
     send_bits(blcodes - 4, 4);  /* not -3 as stated in appnote.txt */
     for (rank = 0; rank < blcodes; rank++) {
         Tracev((stderr, "\nbl code %2d ", bl_order[rank]));
         send_bits(G2.bl_tree[bl_order[rank]].Len, 3);
     }
     Tracev((stderr, "\nbl tree: sent %ld", (long)G1.bits_sent));
     send_tree((ct_data *) G2.dyn_ltree, lcodes - 1);    /* send the literal tree */
     Tracev((stderr, "\nlit tree: sent %ld", (long)G1.bits_sent));
     send_tree((ct_data *) G2.dyn_dtree, dcodes - 1);    /* send the distance tree */
     Tracev((stderr, "\ndist tree: sent %ld", (long)G1.bits_sent));
 }
References Assert, BL_CODES, D_CODES, G1, G2, L_CODES, send_bits(), send_tree(), stderr, and Tracev.
Referenced by flush_block().
send_bits()
static void send_bits (unsigned value, unsigned length) static
Definition at line 541 of file gzip.c.
 {
     unsigned new_buf;
 #ifdef DEBUG
     Tracev((stderr, " l %2d v %4x ", length, value));
     Assert(length > 0 && length <= 15, "invalid length");
     DEBUG_bits_sent(+= length);
 #endif
     BUILD_BUG_ON(BUF_SIZE != 32 && BUF_SIZE != 16);
     new_buf = G1.bi_buf | (value << G1.bi_valid);
     /* NB: the above may sometimes do "<< 32" shift (undefined)
      * if check below is changed to "length > BUF_SIZE" instead of >= */
     length += G1.bi_valid;
     /* If bi_buf is full */
     if (length >= BUF_SIZE) {
         /* ...use (valid) bits from bi_buf and
          * (BUF_SIZE - bi_valid) bits from value,
          *  leaving (width - (BUF_SIZE-bi_valid)) unused bits in value.
          */
         value >>= (BUF_SIZE - G1.bi_valid);
         if (BUF_SIZE == 32) {
             put_32bit(new_buf);
         } else { /* 16 */
             put_16bit(new_buf);
         }
         new_buf = value;
         length -= BUF_SIZE;
     }
     G1.bi_buf = new_buf;
     G1.bi_valid = length;
 }
References Assert, BUF_SIZE, BUILD_BUG_ON, DEBUG_bits_sent, G1, put_16bit(), put_32bit(), stderr, Tracev, and value.
Referenced by compress_block(), flush_block(), send_all_trees(), and send_tree().
send_tree()
static void send_tree (const ct_data * tree, int max_code) static
Definition at line 1454 of file gzip.c.
 {
     int n;              /* iterates over all tree elements */
     int prevlen = -1;   /* last emitted length */
     int curlen;         /* length of current code */
     int nextlen = tree[0].Len;  /* length of next code */
     int count = 0;      /* repeat count of the current code */
     int max_count = 7;  /* max repeat count */
     int min_count = 4;  /* min repeat count */
 /* tree[max_code+1].Len = -1; *//* guard already set */
     if (nextlen == 0)
         max_count = 138, min_count = 3;
     for (n = 0; n <= max_code; n++) {
         curlen = nextlen;
         nextlen = tree[n + 1].Len;
         if (++count < max_count && curlen == nextlen) {
             continue;
         } else if (count < min_count) {
             do {
                 SEND_CODE(curlen, G2.bl_tree);
             } while (--count);
         } else if (curlen != 0) {
             if (curlen != prevlen) {
                 SEND_CODE(curlen, G2.bl_tree);
                 count--;
             }
             Assert(count >= 3 && count <= 6, " 3_6?");
             SEND_CODE(REP_3_6, G2.bl_tree);
             send_bits(count - 3, 2);
         } else if (count <= 10) {
             SEND_CODE(REPZ_3_10, G2.bl_tree);
             send_bits(count - 3, 3);
         } else {
             SEND_CODE(REPZ_11_138, G2.bl_tree);
             send_bits(count - 11, 7);
         }
         count = 0;
         prevlen = curlen;
         if (nextlen == 0) {
             max_count = 138;
             min_count = 3;
         } else if (curlen == nextlen) {
             max_count = 6;
             min_count = 3;
         } else {
             max_count = 7;
             min_count = 4;
         }
     }
 }
References Assert, count, G2, n, REP_3_6, REPZ_11_138, REPZ_3_10, send_bits(), SEND_CODE, and tree.
Referenced by send_all_trees().
updcrc()
static void updcrc (uch * s, unsigned n) static
Definition at line 512 of file gzip.c.
 {
     G1.crc = crc32_block_endian0(G1.crc, s, n, global_crc32_table /*G1.crc_32_tab*/);
 }
References crc32_block_endian0(), G1, global_crc32_table, n, and s.
Referenced by file_read().
zip()
static void zip (void) static
Definition at line 2064 of file gzip.c.
 {
     unsigned deflate_flags;
     //G1.outcnt = 0; // globals are zeroed in pack_gzip()
     /* Write the header to the gzip file. See algorithm.doc for the format */
     /* magic header for gzip files: 1F 8B */
     /* compression method: 8 (DEFLATED) */
     /* general flags: 0 */
     put_32bit(0x00088b1f);
     put_32bit(0);       /* Unix timestamp */
     /* Write deflated file to zip file */
     G1.crc = ~0;
     bi_init();
     ct_init();
     lm_init();
     deflate_flags = 0x300; /* extra flags. OS id = 3 (Unix) */
 #if ENABLE_FEATURE_GZIP_LEVELS
     /* Note that comp_level < 4 do not exist in this version of gzip */
     if (comp_level_minus4 == 9 - 4) {
         deflate_flags |= 0x02; /* SLOW flag */
     }
 #endif
     put_16bit(deflate_flags);
     /* The above 32-bit misaligns outbuf (10 bytes are stored), flush it */
     flush_outbuf_if_32bit_optimized();
     deflate();
     /* Write the crc and uncompressed size */
     put_32bit(~G1.crc);
     put_32bit(G1.isize);
     flush_outbuf();
 }
References bi_init(), comp_level_minus4, ct_init(), deflate(), flush_outbuf(), flush_outbuf_if_32bit_optimized(), G1, lm_init(), put_16bit(), and put_32bit().
Referenced by IF_DESKTOP(), unzip_extract(), and unzip_main().
Variable Documentation
ALIGN1
const uint8_t bl_order [BL_CODES] ALIGN1 static
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4,
    4, 4, 5, 5, 5, 5, 0
}
Definition at line 883 of file gzip.c.