Fennix Kernel: Memory::ProgramBreak Class Reference
Memory::ProgramBreak Class Reference
#include <brk.hpp>
Public Member Functions
void * brk (void *Address)
void InitBrk (uintptr_t Address)
ProgramBreak (PageTable *Table, VirtualMemoryArea *mm)
~ProgramBreak ()
Private Attributes
PageTable * Table = nullptr
VirtualMemoryArea * vma = nullptr
uintptr_t HeapStart = 0x0
uintptr_t Break = 0x0
Detailed Description
Definition at line 29 of file brk.hpp.
Constructor & Destructor Documentation
ProgramBreak()
Memory::ProgramBreak::ProgramBreak (PageTable * Table, VirtualMemoryArea * mm)
Definition at line 80 of file brk.cpp.
     {
         assert(Table != nullptr);
         assert(vma != nullptr);
         this->Table = Table;
         this->vma = vma;
     }
References assert, Table, and vma.
~ProgramBreak()
Memory::ProgramBreak::~ProgramBreak ()
Definition at line 89 of file brk.cpp.
     {
         /* Do nothing because VirtualMemoryArea
             will be destroyed later. */
     }
Member Function Documentation
brk()
void * Memory::ProgramBreak::brk (void * Address)
Definition at line 27 of file brk.cpp.
     {
         if (HeapStart == 0x0 || Break == 0x0)
         {
             error("HeapStart or Break is 0x0");
             return (void *)-EAGAIN;
         }
         /* Get the current program break. */
         if (Address == nullptr)
             return (void *)Break;
         /* Check if the address is valid. */
         if ((uintptr_t)Address < HeapStart)
             return (void *)-ENOMEM;
         Virtual vmm = Virtual(this->Table);
         if ((uintptr_t)Address > Break)
         {
             /* Allocate more memory. */
             size_t Pages = TO_PAGES(uintptr_t(Address) - Break);
             void *Allocated = vma->RequestPages(Pages);
             if (Allocated == nullptr)
                 return (void *)-ENOMEM;
             /* Map the allocated pages. */
             for (size_t i = 0; i < Pages; i++)
             {
                 void *VirtAddr = (void *)(Break + (i * PAGE_SIZE));
                 void *PhysAddr = (void *)(uintptr_t(Allocated) + (i * PAGE_SIZE));
                 vmm.Map(VirtAddr, PhysAddr, RW | US);
             }
             Break = (uint64_t)Address;
             return (void *)Break;
         }
         /* Free memory. */
         size_t Pages = TO_PAGES(uintptr_t(Address) - Break);
         vma->FreePages((void *)Break, Pages);
         /* Unmap the freed pages. */
         for (size_t i = 0; i < Pages; i++)
         {
             uint64_t Page = Break - (i * 0x1000);
             vmm.Remap((void *)Page, (void *)Page, PTFlag::P | PTFlag::RW);
         }
         Break = (uint64_t)Address;
         return (void *)Break;
     }
References Address, Break, EAGAIN, ENOMEM, error, Memory::VirtualMemoryArea::FreePages(), HeapStart, Memory::Virtual::Map(), Memory::P, PAGE_SIZE, Memory::Virtual::Remap(), Memory::VirtualMemoryArea::RequestPages(), Memory::RW, Table, TO_PAGES, Memory::US, and vma.
Referenced by linux_brk().
InitBrk()
void Memory::ProgramBreak::InitBrk (uintptr_t Address) inline
Definition at line 42 of file brk.hpp.
         {
             function("%#lx", Address);
             HeapStart = Address;
             Break = Address;
         }
References Address, Break, and HeapStart.
Field Documentation
Break
uintptr_t Memory::ProgramBreak::Break = 0x0 private
Definition at line 36 of file brk.hpp.
Referenced by brk(), and InitBrk().
HeapStart
uintptr_t Memory::ProgramBreak::HeapStart = 0x0 private
Definition at line 35 of file brk.hpp.
Referenced by brk(), and InitBrk().
Table
PageTable* Memory::ProgramBreak::Table = nullptr private
Definition at line 32 of file brk.hpp.
Referenced by brk(), and ProgramBreak().
vma
VirtualMemoryArea* Memory::ProgramBreak::vma = nullptr private
Definition at line 33 of file brk.hpp.
Referenced by brk(), and ProgramBreak().
The documentation for this class was generated from the following files:
Kernel/include/memory/brk.hpp
Kernel/core/memory/brk.cpp