Fennix Userspace: Userspace/mlibc/options/ansi/generic/complex/clog.c File Reference
clog.c File Reference
#include <complex.h>
#include <math.h>
Functions
double complex clog (double complex z)
Function Documentation
clog()
double complex clog (double complex z)
Definition at line 81 of file clog.c.
 {
     double complex w;
     double p, rr;
     rr = cabs(z);
     p = log(rr);
     rr = atan2(cimag(z), creal(z));
     w = p + rr * I;
     return w;
 }
References atan2(), cabs(), cimag(), complex, creal(), I, log(), and p.
Referenced by cacosh(), and casin().