Fennix Userspace: Userspace/musl/src/string/strlen.c File Reference
strlen.c File Reference
#include <string.h>
#include <stdint.h>
#include <limits.h>
Macros
#define ALIGN (sizeof(size_t))
#define ONES ((size_t)-1/UCHAR_MAX)
#define HIGHS (ONES * (UCHAR_MAX/2+1))
#define HASZERO(x) ((x)-ONES & ~(x) & HIGHS)
Functions
size_t strlen (const char *s)
Macro Definition Documentation
ALIGN
#define ALIGN (sizeof(size_t))
Definition at line 5 of file strlen.c.
HASZERO
#define HASZERO (x) ((x)-ONES & ~(x) & HIGHS)
Definition at line 8 of file strlen.c.
HIGHS
#define HIGHS (ONES * (UCHAR_MAX/2+1))
Definition at line 7 of file strlen.c.
ONES
#define ONES ((size_t)-1/UCHAR_MAX)
Definition at line 6 of file strlen.c.
Function Documentation
strlen()
size_t strlen (const char * s)
Definition at line 10 of file strlen.c.
 {
     const char *a = s;
 #ifdef __GNUC__
     typedef size_t __attribute__((__may_alias__)) word;
     const word *w;
     for (; (uintptr_t)s % ALIGN; s++) if (!*s) return s-a;
     for (w = (const void *)s; !HASZERO(*w); w++);
     s = (const void *)w;
 #endif
     for (; *s; s++);
     return s-a;
 }
References __attribute__(), ALIGN, HASZERO, and i.
Referenced by __dls3(), __get_resolv_conf(), __getopt_long_core(), __getopt_msg(), __lookup_serv(), __mkostemps(), __nscd_query(), __strchrnul(), __strftime_fmt_1(), __strxfrm_l(), atof(), atoi(), basename(), catopen(), cht_CheckCheat(), create_directory(), create_file(), dcngettext(), DirIsFile(), dirname(), do_glob(), do_nftw(), do_tzset(), EscapeShellString(), F_Ticker(), find_charmap(), fixup_rpath(), fputs(), G_RecordDemo(), getaddrinfo(), getdomainname(), getenv(), GetGameName(), gethostbyname2_r(), getlogin_r(), getmntent_r(), getnameinfo(), getprotoent(), getspnam_r(), getsubopt(), glob(), I_Error(), I_PrintBanner(), inet_ntop(), load_library(), LoadDefaultCollection(), M_Drawer(), M_ExtractFileBase(), M_SaveSelect(), M_StrCaseStr(), M_StringConcat(), M_StringCopy(), M_StringDuplicate(), M_StringEndsWith(), M_StringHeight(), M_StringJoin(), M_StringReplace(), M_StringStartsWith(), M_StringWidth(), main(), mbsrtowcs(), mkdtemp(), mktemp(), name_from_hosts(), nftw(), P_SaveGameFile(), perror(), posix_spawn_file_actions_addchdir_np(), posix_spawn_file_actions_addopen(), PrintDehackedBanners(), ptmx_test(), realpath(), regerror(), setenv(), setlocale(), SHA1_UpdateString(), SplitLine(), strcasestr(), strcat(), strdup(), strerror_r(), strlcat(), strlcpy(), strncat(), strptime(), strrchr(), tempnam(), textdomain(), W_AddFile(), and ZenityErrorBox().