Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/i_sound.h File Reference
i_sound.h File Reference
#include "doomtype.h"
Data Structures
struct sfxinfo_struct
struct musicinfo_t
struct sound_module_t
struct music_module_t
Typedefs
typedef struct sfxinfo_struct sfxinfo_t
Enumerations
enum snddevice_t {
SNDDEVICE_NONE = 0 , SNDDEVICE_PCSPEAKER = 1 , SNDDEVICE_ADLIB = 2 , SNDDEVICE_SB = 3 ,
SNDDEVICE_PAS = 4 , SNDDEVICE_GUS = 5 , SNDDEVICE_WAVEBLASTER = 6 , SNDDEVICE_SOUNDCANVAS = 7 ,
SNDDEVICE_GENMIDI = 8 , SNDDEVICE_AWE32 = 9 , SNDDEVICE_CD = 10
}
Functions
void I_InitSound (boolean use_sfx_prefix)
void I_ShutdownSound (void)
int I_GetSfxLumpNum (sfxinfo_t *sfxinfo)
void I_UpdateSound (void)
void I_UpdateSoundParams (int channel, int vol, int sep)
int I_StartSound (sfxinfo_t *sfxinfo, int channel, int vol, int sep)
void I_StopSound (int channel)
boolean I_SoundIsPlaying (int channel)
void I_PrecacheSounds (sfxinfo_t *sounds, int num_sounds)
void I_InitMusic (void)
void I_ShutdownMusic (void)
void I_SetMusicVolume (int volume)
void I_PauseSong (void)
void I_ResumeSong (void)
void * I_RegisterSong (void *data, int len)
void I_UnRegisterSong (void *handle)
void I_PlaySong (void *handle, boolean looping)
void I_StopSong (void)
boolean I_MusicIsPlaying (void)
void I_BindSoundVariables (void)
Variables
int snd_sfxdevice
int snd_musicdevice
int snd_samplerate
int snd_cachesize
int snd_maxslicetime_ms
char * snd_musiccmd
Data Structure Documentation
sfxinfo_struct
struct sfxinfo_struct
Definition at line 31 of file i_sound.h.
Data Fields
void * driver_data
sfxinfo_t * link
int lumpnum
char name[9]
int numchannels
int pitch
int priority
char * tagname
int usefulness
int volume
musicinfo_t
struct musicinfo_t
Definition at line 72 of file i_sound.h.
Data Fields
void * data
void * handle
int lumpnum
char * name
Typedef Documentation
sfxinfo_t
typedef struct sfxinfo_struct sfxinfo_t
Definition at line 1 of file i_sound.h.
Enumeration Type Documentation
snddevice_t
enum snddevice_t
Enumerator
SNDDEVICE_NONE
SNDDEVICE_PCSPEAKER
SNDDEVICE_ADLIB
SNDDEVICE_SB
SNDDEVICE_PAS
SNDDEVICE_GUS
SNDDEVICE_WAVEBLASTER
SNDDEVICE_SOUNDCANVAS
SNDDEVICE_GENMIDI
SNDDEVICE_AWE32
SNDDEVICE_CD
Definition at line 88 of file i_sound.h.
 {
     SNDDEVICE_NONE = 0,
     SNDDEVICE_PCSPEAKER = 1,
     SNDDEVICE_ADLIB = 2,
     SNDDEVICE_SB = 3,
     SNDDEVICE_PAS = 4,
     SNDDEVICE_GUS = 5,
     SNDDEVICE_WAVEBLASTER = 6,
     SNDDEVICE_SOUNDCANVAS = 7,
     SNDDEVICE_GENMIDI = 8,
     SNDDEVICE_AWE32 = 9,
     SNDDEVICE_CD = 10,
 } snddevice_t;
Function Documentation
I_BindSoundVariables()
void I_BindSoundVariables (void)
Definition at line 413 of file i_sound.c.
 {
     extern int use_libsamplerate;
     extern float libsamplerate_scale;
     M_BindVariable("snd_musicdevice",   &snd_musicdevice);
     M_BindVariable("snd_sfxdevice",     &snd_sfxdevice);
     M_BindVariable("snd_sbport",        &snd_sbport);
     M_BindVariable("snd_sbirq",         &snd_sbirq);
     M_BindVariable("snd_sbdma",         &snd_sbdma);
     M_BindVariable("snd_mport",         &snd_mport);
     M_BindVariable("snd_maxslicetime_ms", &snd_maxslicetime_ms);
     M_BindVariable("snd_musiccmd",      &snd_musiccmd);
     M_BindVariable("snd_samplerate",    &snd_samplerate);
     M_BindVariable("snd_cachesize",     &snd_cachesize);
 #ifdef FEATURE_SOUND
     M_BindVariable("use_libsamplerate",   &use_libsamplerate);
     M_BindVariable("libsamplerate_scale", &libsamplerate_scale);
 #endif
     // Before SDL_mixer version 1.2.11, MIDI music caused the game
     // to crash when it looped.  If this is an old SDL_mixer version,
     // disable MIDI.
 }
References M_BindVariable(), snd_cachesize, snd_maxslicetime_ms, snd_mport, snd_musiccmd, snd_musicdevice, snd_samplerate, snd_sbdma, snd_sbirq, snd_sbport, and snd_sfxdevice.
Referenced by D_BindVariables().
I_GetSfxLumpNum()
int I_GetSfxLumpNum (sfxinfo_t * sfxinfo)
Definition at line 231 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         return sound_module->GetSfxLumpNum(sfxinfo);
     }
     else
     {
         return 0;
     }
 }
References sound_module_t::GetSfxLumpNum, NULL, and sound_module.
Referenced by S_StartSound().
I_InitMusic()
void I_InitMusic (void)
Definition at line 327 of file i_sound.c.
 {
     if(music_module != NULL)
     {
         music_module->Init();
     }
 }
References music_module_t::Init, music_module, and NULL.
Referenced by D_DoomMain().
I_InitSound()
void I_InitSound (boolean use_sfx_prefix)
Definition at line 162 of file i_sound.c.
 {
     boolean nosound, nosfx, nomusic;
     // @vanilla
     //
     // Disable all sound output.
     //
     nosound = M_CheckParm("-nosound") > 0;
     // @vanilla
     //
     // Disable sound effects.
     //
     nosfx = M_CheckParm("-nosfx") > 0;
     // @vanilla
     //
     // Disable music.
     //
     nomusic = M_CheckParm("-nomusic") > 0;
     // Initialize the sound and music subsystems.
     if (!nosound && !screensaver_mode)
     {
         // This is kind of a hack. If native MIDI is enabled, set up
         // the TIMIDITY_CFG environment variable here before SDL_mixer
         // is opened.
         if (!nomusic
          && (snd_musicdevice == SNDDEVICE_GENMIDI
           || snd_musicdevice == SNDDEVICE_GUS))
         {
             I_InitTimidityConfig();
         }
         if (!nosfx)
         {
             InitSfxModule(use_sfx_prefix);
         }
         if (!nomusic)
         {
             InitMusicModule();
         }
     }
 }
References I_InitTimidityConfig(), InitMusicModule(), InitSfxModule(), M_CheckParm(), screensaver_mode, snd_musicdevice, SNDDEVICE_GENMIDI, and SNDDEVICE_GUS.
Referenced by D_DoomMain().
I_MusicIsPlaying()
boolean I_MusicIsPlaying (void)
Definition at line 400 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         return music_module->MusicIsPlaying();
     }
     else
     {
         return false;
     }
 }
References music_module, music_module_t::MusicIsPlaying, and NULL.
Referenced by S_MusicPlaying().
I_PauseSong()
void I_PauseSong (void)
Definition at line 348 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->PauseMusic();
     }
 }
References music_module, NULL, and music_module_t::PauseMusic.
Referenced by S_PauseSound().
I_PlaySong()
void I_PlaySong (void * handle, boolean looping)
Definition at line 384 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->PlaySong(handle, looping);
     }
 }
References music_module, NULL, and music_module_t::PlaySong.
Referenced by S_ChangeMusic().
I_PrecacheSounds()
void I_PrecacheSounds (sfxinfo_t * sounds, int num_sounds)
Definition at line 319 of file i_sound.c.
 {
     if (sound_module != NULL && sound_module->CacheSounds != NULL)
     {
     sound_module->CacheSounds(sounds, num_sounds);
     }
 }
References sound_module_t::CacheSounds, NULL, and sound_module.
Referenced by S_Init().
I_RegisterSong()
void* I_RegisterSong (void * data, int len)
Definition at line 364 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         return music_module->RegisterSong(data, len);
     }
     else
     {
         return NULL;
     }
 }
References len, music_module, NULL, and music_module_t::RegisterSong.
Referenced by S_ChangeMusic().
I_ResumeSong()
void I_ResumeSong (void)
Definition at line 356 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->ResumeMusic();
     }
 }
References music_module, NULL, and music_module_t::ResumeMusic.
Referenced by S_ResumeSound(), and S_StopMusic().
I_SetMusicVolume()
void I_SetMusicVolume (int volume)
Definition at line 340 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->SetMusicVolume(volume);
     }
 }
References music_module, NULL, and music_module_t::SetMusicVolume.
Referenced by S_SetMusicVolume().
I_ShutdownMusic()
void I_ShutdownMusic (void)
Definition at line 335 of file i_sound.c.
 {
 }
Referenced by S_Shutdown().
I_ShutdownSound()
void I_ShutdownSound (void)
Definition at line 218 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         sound_module->Shutdown();
     }
     if (music_module != NULL)
     {
         music_module->Shutdown();
     }
 }
References music_module, NULL, sound_module_t::Shutdown, music_module_t::Shutdown, and sound_module.
Referenced by S_Shutdown().
I_SoundIsPlaying()
boolean I_SoundIsPlaying (int channel)
Definition at line 307 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         return sound_module->SoundIsPlaying(channel);
     }
     else
     {
         return false;
     }
 }
References NULL, sound_module, and sound_module_t::SoundIsPlaying.
Referenced by S_StopChannel(), and S_UpdateSounds().
I_StartSound()
int I_StartSound (sfxinfo_t * sfxinfo, int channel, int vol, int sep)
Definition at line 286 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         CheckVolumeSeparation(&vol, &sep);
         return sound_module->StartSound(sfxinfo, channel, vol, sep);
     }
     else
     {
         return 0;
     }
 }
References CheckVolumeSeparation(), NULL, sound_module, and sound_module_t::StartSound.
Referenced by S_StartSound().
I_StopSong()
void I_StopSong (void)
Definition at line 392 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->StopSong();
     }
 }
References music_module, NULL, and music_module_t::StopSong.
Referenced by S_StopMusic().
I_StopSound()
void I_StopSound (int channel)
Definition at line 299 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         sound_module->StopSound(channel);
     }
 }
References NULL, sound_module, and sound_module_t::StopSound.
Referenced by S_StopChannel().
I_UnRegisterSong()
void I_UnRegisterSong (void * handle)
Definition at line 376 of file i_sound.c.
 {
     if (music_module != NULL)
     {
         music_module->UnRegisterSong(handle);
     }
 }
References music_module, NULL, and music_module_t::UnRegisterSong.
Referenced by S_StopMusic().
I_UpdateSound()
void I_UpdateSound (void)
Definition at line 243 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         sound_module->Update();
     }
     if (music_module != NULL && music_module->Poll != NULL)
     {
         music_module->Poll();
     }
 }
References music_module, NULL, music_module_t::Poll, sound_module, and sound_module_t::Update.
Referenced by S_UpdateSounds().
I_UpdateSoundParams()
void I_UpdateSoundParams (int channel, int vol, int sep)
Definition at line 277 of file i_sound.c.
 {
     if (sound_module != NULL)
     {
         CheckVolumeSeparation(&vol, &sep);
         sound_module->UpdateSoundParams(channel, vol, sep);
     }
 }
References CheckVolumeSeparation(), NULL, sound_module, and sound_module_t::UpdateSoundParams.
Referenced by S_UpdateSounds().
Variable Documentation
snd_cachesize
int snd_cachesize extern
Definition at line 44 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_maxslicetime_ms
int snd_maxslicetime_ms extern
Definition at line 49 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_musiccmd
char* snd_musiccmd extern
Definition at line 53 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_musicdevice
int snd_musicdevice extern
Definition at line 60 of file i_sound.c.
Referenced by I_BindSoundVariables(), I_InitSound(), and S_ChangeMusic().
snd_samplerate
int snd_samplerate extern
Definition at line 39 of file i_sound.c.
Referenced by I_BindSoundVariables().
snd_sfxdevice
int snd_sfxdevice extern
Definition at line 61 of file i_sound.c.
Referenced by I_BindSoundVariables(), and InitSfxModule().