Fennix: Userspace/musl/arch/aarch64/fp_arch.h File Reference
fp_arch.h File Reference
Macros
#define fp_barrierf fp_barrierf
#define fp_barrier fp_barrier
#define fp_force_evalf fp_force_evalf
#define fp_force_eval fp_force_eval
Functions
static float fp_barrierf (float x)
static double fp_barrier (double x)
static void fp_force_evalf (float x)
static void fp_force_eval (double x)
Macro Definition Documentation
fp_barrier
#define fp_barrier fp_barrier
Definition at line 8 of file fp_arch.h.
fp_barrierf
#define fp_barrierf fp_barrierf
Definition at line 1 of file fp_arch.h.
fp_force_eval
#define fp_force_eval fp_force_eval
Definition at line 21 of file fp_arch.h.
fp_force_evalf
#define fp_force_evalf fp_force_evalf
Definition at line 15 of file fp_arch.h.
Function Documentation
fp_barrier()
static double fp_barrier (double x) inline static
Definition at line 9 of file fp_arch.h.
 {
     __asm__ __volatile__ ("" : "+w"(x));
     return x;
 }
References __asm__(), and x.
fp_barrierf()
static float fp_barrierf (float x) inline static
Definition at line 2 of file fp_arch.h.
 {
     __asm__ __volatile__ ("" : "+w"(x));
     return x;
 }
References __asm__(), and x.
fp_force_eval()
static void fp_force_eval (double x) inline static
Definition at line 22 of file fp_arch.h.
 {
     __asm__ __volatile__ ("" : "+w"(x));
 }
References __asm__(), and x.
fp_force_evalf()
static void fp_force_evalf (float x) inline static
Definition at line 16 of file fp_arch.h.
 {
     __asm__ __volatile__ ("" : "+w"(x));
 }
References __asm__(), and x.