Fennix Userspace: Userspace/musl/include/sys/klog.h File Reference
klog.h File Reference
Functions
int klogctl (int, char *, int)
Function Documentation
klogctl()
int klogctl (int type, char * bufp, int len)
Definition at line 8 of file sys-klog.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_klogctl, -1);
     int out;
     if (int e = mlibc::sys_klogctl(type, bufp, len, &out); e) {
         errno = e;
         return -1;
     }
     return out;
 }
References buf, errno, MLIBC_CHECK_OR_ENOSYS, out(), mlibc::sys_klogctl(), and syscall().