Fennix Userspace: Userspace/apps/base/busybox/networking/libiproute/ip_common.h File Reference
ip_common.h File Reference
#include "libbb.h"
#include <asm/types.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <linux/if_addr.h>
#include <linux/if_link.h>
Macros
#define INFINITY_LIFE_TIME 0xFFFFFFFFU
Functions
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN char FAST_FUNC ** ip_parse_common_args (char **argv)
int FAST_FUNC ipaddr_list_or_flush (char **argv, int flush)
int FAST_FUNC do_ipaddr (char **argv)
int FAST_FUNC do_iproute (char **argv)
int FAST_FUNC do_iprule (char **argv)
int FAST_FUNC do_ipneigh (char **argv)
int FAST_FUNC do_iptunnel (char **argv)
int FAST_FUNC do_iplink (char **argv)
Macro Definition Documentation
INFINITY_LIFE_TIME
#define INFINITY_LIFE_TIME 0xFFFFFFFFU
Definition at line 37 of file ip_common.h.
Function Documentation
do_ipaddr()
int FAST_FUNC do_ipaddr (char ** argv)
Definition at line 825 of file ipaddress.c.
 {
     static const char commands[] ALIGN1 =
         /* 0    1         2      3          4         5       6       7      8 */
         "add\0""change\0""chg\0""replace\0""delete\0""list\0""show\0""lst\0""flush\0";
     int cmd = 2;
     INIT_G();
     if (*argv) {
         cmd = index_in_substrings(commands, *argv);
         if (cmd < 0)
             invarg_1_to_2(*argv, applet_name);
         argv++;
         if (cmd <= 4) {
             return ipaddr_modify(
                 /*cmd:*/ cmd == 4 ? RTM_DELADDR : RTM_NEWADDR,
                 /*flags:*/
                     cmd == 0 ? NLM_F_CREATE|NLM_F_EXCL : /* add */
                     cmd == 1 || cmd == 2 ? NLM_F_REPLACE : /* change */
                     cmd == 3 ? NLM_F_CREATE|NLM_F_REPLACE : /* replace */
                     0 /* delete */
             , argv);
         }
     }
     return ipaddr_list_or_flush(argv, cmd == 8);
 }
References ALIGN1, applet_name, argv, cmd, commands, index_in_substrings(), INIT_G, invarg_1_to_2(), ipaddr_list_or_flush(), ipaddr_modify(), and RTM_NEWADDR.
do_iplink()
int FAST_FUNC do_iplink (char ** argv)
Definition at line 745 of file iplink.c.
 {
     static const char keywords[] ALIGN1 =
         "add\0""delete\0""set\0""show\0""lst\0""list\0";
     xfunc_error_retval = 2; //TODO: move up to "ip"? Is it the common rule for all "ip" tools?
     if (*argv) {
         int key = index_in_substrings(keywords, *argv);
         if (key < 0) /* invalid argument */
             invarg_1_to_2(*argv, applet_name);
         argv++;
         if (key <= 1) /* add/delete */
             return do_add_or_delete(argv, key ? RTM_DELLINK : RTM_NEWLINK);
         if (key == 2) /* set */
             return do_set(argv);
     }
     /* show, lst, list */
     return ipaddr_list_link(argv);
 }
References ALIGN1, applet_name, argv, do_add_or_delete(), do_set(), index_in_substrings(), invarg_1_to_2(), ipaddr_list_link(), RTM_NEWLINK, and xfunc_error_retval.
do_ipneigh()
int FAST_FUNC do_ipneigh (char ** argv)
Definition at line 339 of file ipneigh.c.
 {
     static const char ip_neigh_commands[] ALIGN1 =
         /*0-1*/ "show\0"  "flush\0";
     int command_num;
     INIT_G();
     if (!*argv)
         return ipneigh_list_or_flush(argv, 0);
     command_num = index_in_substrings(ip_neigh_commands, *argv);
     switch (command_num) {
         case 0: /* show */
             return ipneigh_list_or_flush(argv + 1, 0);
         case 1: /* flush */
             return ipneigh_list_or_flush(argv + 1, 1);
     }
     invarg_1_to_2(*argv, applet_name);
     return 1;
 }
References ALIGN1, applet_name, argv, index_in_substrings(), INIT_G, invarg_1_to_2(), and ipneigh_list_or_flush().
do_iproute()
int FAST_FUNC do_iproute (char ** argv)
Definition at line 1117 of file iproute.c.
 {
     static const char ip_route_commands[] ALIGN1 =
         "a\0""add\0""append\0""change\0""chg\0"
         "delete\0""get\0""list\0""show\0"
         "prepend\0""replace\0""test\0""flush\0"
     ;
     enum {
         CMD_a = 0, CMD_add, CMD_append, CMD_change, CMD_chg,
         CMD_delete, CMD_get, CMD_list, CMD_show,
         CMD_prepend, CMD_replace, CMD_test, CMD_flush,
     };
     int command_num;
     unsigned flags = 0;
     int cmd = RTM_NEWROUTE;
     INIT_G();
     if (!*argv)
         return iproute_list_or_flush(argv, 0);
     /* "Standard" 'ip r a' treats 'a' as 'add', not 'append' */
     /* It probably means that it is using "first match" rule */
     command_num = index_in_substrings(ip_route_commands, *argv);
     switch (command_num) {
         case CMD_a:
         case CMD_add:
             flags = NLM_F_CREATE|NLM_F_EXCL;
             break;
         case CMD_append:
             flags = NLM_F_CREATE|NLM_F_APPEND;
             break;
         case CMD_change:
         case CMD_chg:
             flags = NLM_F_REPLACE;
             break;
         case CMD_delete:
             cmd = RTM_DELROUTE;
             break;
         case CMD_get:
             return iproute_get(argv + 1);
         case CMD_list:
         case CMD_show:
             return iproute_list_or_flush(argv + 1, 0);
         case CMD_prepend:
             flags = NLM_F_CREATE;
             break;
         case CMD_replace:
             flags = NLM_F_CREATE|NLM_F_REPLACE;
             break;
         case CMD_test:
             flags = NLM_F_EXCL;
             break;
         case CMD_flush:
             return iproute_list_or_flush(argv + 1, 1);
         default:
             invarg_1_to_2(*argv, applet_name);
     }
     return iproute_modify(cmd, flags, argv + 1);
 }
References ALIGN1, applet_name, argv, cmd, flags, index_in_substrings(), INIT_G, invarg_1_to_2(), iproute_get(), iproute_list_or_flush(), and iproute_modify().
do_iprule()
int FAST_FUNC do_iprule (char ** argv)
Definition at line 357 of file iprule.c.
 {
     static const char ip_rule_commands[] ALIGN1 =
         "add\0""delete\0""list\0""show\0";
     if (*argv) {
         int cmd = index_in_substrings(ip_rule_commands, *argv);
         if (cmd < 0)
             invarg_1_to_2(*argv, applet_name);
         argv++;
         if (cmd < 2)
             return iprule_modify((cmd == 0) ? RTM_NEWRULE : RTM_DELRULE, argv);
     }
     return iprule_list(argv);
 }
References ALIGN1, applet_name, argv, cmd, index_in_substrings(), invarg_1_to_2(), iprule_list(), and iprule_modify().
do_iptunnel()
int FAST_FUNC do_iptunnel (char ** argv)
Definition at line 553 of file iptunnel.c.
 {
     static const char keywords[] ALIGN1 =
         "add\0""change\0""delete\0""show\0""list\0""lst\0";
     enum { ARG_add = 0, ARG_change, ARG_del, ARG_show, ARG_list, ARG_lst };
     if (*argv) {
         int key = index_in_substrings(keywords, *argv);
         if (key < 0)
             invarg_1_to_2(*argv, applet_name);
         argv++;
         if (key == ARG_add)
             return do_add(SIOCADDTUNNEL, argv);
         if (key == ARG_change)
             return do_add(SIOCCHGTUNNEL, argv);
         if (key == ARG_del)
             return do_del(argv);
     }
     return do_show(argv);
 }
References ALIGN1, applet_name, argv, do_add(), do_del(), do_show(), index_in_substrings(), invarg_1_to_2(), SIOCADDTUNNEL, and SIOCCHGTUNNEL.
ip_parse_common_args()
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN char FAST_FUNC** ip_parse_common_args (char ** argv)
Definition at line 21 of file ip_parse_common_args.c.
 {
     static const char ip_common_commands[] ALIGN1 =
         "oneline" "\0"
         "family" "\0"
         "4" "\0"
         "6" "\0"
         "0" "\0"
         ;
     enum {
         ARG_oneline,
         ARG_family,
         ARG_IPv4,
         ARG_IPv6,
         ARG_packet,
     };
     static const family_t af_numbers[] = { AF_INET, AF_INET6, AF_PACKET };
     int arg;
     while (*argv) {
         char *opt = *argv;
         if (opt[0] != '-')
             break;
         opt++;
         if (opt[0] == '-') {
             opt++;
             if (!opt[0]) { /* "--" */
                 argv++;
                 break;
             }
         }
         arg = index_in_substrings(ip_common_commands, opt);
         if (arg < 0)
             bb_show_usage();
         if (arg == ARG_oneline) {
             oneline = 1;
             argv++;
             continue;
         }
         if (arg == ARG_family) {
             static const char families[] ALIGN1 =
                 "inet" "\0" "inet6" "\0" "link" "\0";
             argv++;
             if (!*argv)
                 bb_show_usage();
             arg = index_in_strings(families, *argv);
             if (arg < 0)
                 invarg_1_to_2(*argv, "family");
             /* now arg == 0, 1 or 2 */
         } else {
             arg -= ARG_IPv4;
             /* now arg == 0, 1 or 2 */
         }
         preferred_family = af_numbers[arg];
         argv++;
     }
     _SL_ = oneline ? '\\' : '\n';
     return argv;
 }
References _SL_, AF_INET, AF_INET6, AF_PACKET, ALIGN1, argv, bb_show_usage(), index_in_strings(), index_in_substrings(), invarg_1_to_2(), oneline, opt, and preferred_family.
ipaddr_list_or_flush()
int FAST_FUNC ipaddr_list_or_flush (char ** argv, int flush)
Definition at line 437 of file ipaddress.c.
 {
     static const char option[] ALIGN1 = "to\0""scope\0""up\0""label\0""dev\0";
     struct nlmsg_list *linfo = NULL;
     struct nlmsg_list *ainfo = NULL;
     struct nlmsg_list *l;
     struct rtnl_handle rth;
     char *filter_dev = NULL;
     ipaddr_reset_filter(oneline);
     G_filter.showqueue = 1;
     if (G_filter.family == AF_UNSPEC)
         G_filter.family = preferred_family;
     if (flush) {
         if (!*argv) {
             bb_error_msg_and_die(bb_msg_requires_arg, "flush");
         }
         if (G_filter.family == AF_PACKET) {
             bb_simple_error_msg_and_die("can't flush link addresses");
         }
     }
     while (*argv) {
         const smalluint key = index_in_strings(option, *argv);
         if (key == 0) { /* to */
             NEXT_ARG();
             get_prefix(&G_filter.pfx, *argv, G_filter.family);
             if (G_filter.family == AF_UNSPEC) {
                 G_filter.family = G_filter.pfx.family;
             }
         } else if (key == 1) { /* scope */
             uint32_t scope = 0;
             NEXT_ARG();
             G_filter.scopemask = -1;
             if (rtnl_rtscope_a2n(&scope, *argv)) {
                 if (strcmp(*argv, "all") != 0) {
                     invarg_1_to_2(*argv, "scope");
                 }
                 scope = RT_SCOPE_NOWHERE;
                 G_filter.scopemask = 0;
             }
             G_filter.scope = scope;
         } else if (key == 2) { /* up */
             G_filter.up = 1;
         } else if (key == 3) { /* label */
             NEXT_ARG();
             G_filter.label = *argv;
         } else {
             if (key == 4) /* dev */
                 NEXT_ARG();
             if (filter_dev)
                 duparg2("dev", *argv);
             filter_dev = *argv;
         }
         argv++;
     }
     xrtnl_open(&rth);
     xrtnl_wilddump_request(&rth, preferred_family, RTM_GETLINK);
     xrtnl_dump_filter(&rth, store_nlmsg, &linfo);
     if (filter_dev) {
         G_filter.ifindex = xll_name_to_index(filter_dev);
     }
     if (flush) {
         char flushb[4096-512];
         G_filter.flushb = flushb;
         G_filter.flushp = 0;
         G_filter.flushe = sizeof(flushb);
         G_filter.rth = &rth;
         for (;;) {
             xrtnl_wilddump_request(&rth, G_filter.family, RTM_GETADDR);
             G_filter.flushed = 0;
             xrtnl_dump_filter(&rth, print_addrinfo, NULL);
             if (G_filter.flushed == 0) {
                 return 0;
             }
             if (flush_update() < 0) {
                 return 1;
             }
         }
     }
     if (G_filter.family != AF_PACKET) {
         xrtnl_wilddump_request(&rth, G_filter.family, RTM_GETADDR);
         xrtnl_dump_filter(&rth, store_nlmsg, &ainfo);
     }
     if (G_filter.family && G_filter.family != AF_PACKET) {
         struct nlmsg_list **lp;
         lp = &linfo;
         while ((l = *lp) != NULL) {
             int ok = 0;
             struct ifinfomsg *ifi = NLMSG_DATA(&l->h);
             struct nlmsg_list *a;
             for (a = ainfo; a; a = a->next) {
                 struct nlmsghdr *n = &a->h;
                 struct ifaddrmsg *ifa = NLMSG_DATA(n);
                 if (ifa->ifa_index != ifi->ifi_index
                  || (G_filter.family && G_filter.family != ifa->ifa_family)
                 ) {
                     continue;
                 }
                 if ((G_filter.scope ^ ifa->ifa_scope) & G_filter.scopemask)
                     continue;
                 if ((G_filter.flags ^ ifa->ifa_flags) & G_filter.flagmask)
                     continue;
                 if (G_filter.pfx.family || G_filter.label) {
                     struct rtattr *tb[IFA_MAX+1];
                     //memset(tb, 0, sizeof(tb)); - parse_rtattr does this
                     parse_rtattr(tb, IFA_MAX, IFA_RTA(ifa), IFA_PAYLOAD(n));
                     if (!tb[IFA_LOCAL])
                         tb[IFA_LOCAL] = tb[IFA_ADDRESS];
                     if (G_filter.pfx.family && tb[IFA_LOCAL]) {
                         inet_prefix dst;
                         memset(&dst, 0, sizeof(dst));
                         dst.family = ifa->ifa_family;
                         memcpy(&dst.data, RTA_DATA(tb[IFA_LOCAL]), RTA_PAYLOAD(tb[IFA_LOCAL]));
                         if (inet_addr_match(&dst, &G_filter.pfx, G_filter.pfx.bitlen))
                             continue;
                     }
                     if (G_filter.label) {
                         const char *label;
                         if (tb[IFA_LABEL])
                             label = RTA_DATA(tb[IFA_LABEL]);
                         else
                             label = ll_index_to_name(ifa->ifa_index);
                         if (fnmatch(G_filter.label, label, 0) != 0)
                             continue;
                     }
                 }
                 ok = 1;
                 break;
             }
             if (!ok)
                 *lp = l->next;
             else
                 lp = &l->next;
         }
     }
     for (l = linfo; l; l = l->next) {
         if ((oneline && G_filter.family != AF_PACKET)
         /* ^^^^^^^^^ "ip -oneline a" does not print link info */
          || (print_linkinfo(&l->h) == 0)
         ) {
             struct ifinfomsg *ifi = NLMSG_DATA(&l->h);
             if (G_filter.family != AF_PACKET)
                 print_selected_addrinfo(ifi->ifi_index, ainfo);
         }
     }
     return 0;
 }
References AF_PACKET, AF_UNSPEC, ALIGN1, argv, bb_error_msg_and_die(), bb_simple_error_msg_and_die(), dst, duparg2(), flush(), flush_update(), fnmatch(), G_filter, get_prefix(), nlmsg_list::h, IFA_ADDRESS, ifaddrmsg::ifa_family, ifaddrmsg::ifa_flags, ifaddrmsg::ifa_index, IFA_LABEL, IFA_LOCAL, IFA_MAX, ifaddrmsg::ifa_scope, ifinfomsg::ifi_index, index_in_strings(), inet_addr_match(), invarg_1_to_2(), ipaddr_reset_filter(), l, label, ll_index_to_name(), memcpy(), memset(), n, nlmsg_list::next, NEXT_ARG, NLMSG_DATA, NULL, ok, oneline, parse_rtattr(), preferred_family, print_addrinfo(), print_linkinfo(), print_selected_addrinfo(), RTA_DATA, RTM_GETADDR, RTM_GETLINK, rtnl_rtscope_a2n(), store_nlmsg(), strcmp, xll_name_to_index(), xrtnl_dump_filter(), xrtnl_open(), and xrtnl_wilddump_request().
Referenced by do_ipaddr(), and ipaddr_list_link().