Fennix: Userspace/apps/base/busybox/debianutils/run_parts.c File Reference
run_parts.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define names (G.names)
#define cur (G.cur)
#define cmd (G.cmd)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
#define GETOPT32 getopt32
#define LONGOPTS
Enumerations
enum { NUM_CMD = (COMMON_BUFSIZE - sizeof(G)) / sizeof(cmd[0]) - 1 }
enum {
OPT_a = (1 << 0) , OPT_u = (1 << 1) , OPT_r = (1 << 2) * ENABLE_FEATURE_RUN_PARTS_LONG_OPTIONS , OPT_t = (1 << 3) * ENABLE_FEATURE_RUN_PARTS_LONG_OPTIONS ,
OPT_e = (1 << 4) * ENABLE_FEATURE_RUN_PARTS_LONG_OPTIONS , OPT_l
}
Functions
static bool invalid_name (const char *c)
static int bb_alphasort (const void *p1, const void *p2)
static int FAST_FUNC act (struct recursive_state *state, const char *file, struct stat *statbuf)
int run_parts_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
cmd
#define cmd (G.cmd)
Definition at line 100 of file run_parts.c.
cur
#define cur (G.cur)
Definition at line 99 of file run_parts.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 97 of file run_parts.c.
GETOPT32
#define GETOPT32 getopt32
Definition at line 181 of file run_parts.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 101 of file run_parts.c.
LONGOPTS
#define LONGOPTS
Definition at line 182 of file run_parts.c.
names
#define names (G.names)
Definition at line 98 of file run_parts.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NUM_CMD
Definition at line 103 of file run_parts.c.
 { NUM_CMD = (COMMON_BUFSIZE - sizeof(G)) / sizeof(cmd[0]) - 1 };
anonymous enum
anonymous enum
Enumerator
OPT_a
OPT_u
OPT_r
OPT_t
OPT_e
OPT_l
Definition at line 105 of file run_parts.c.
      {
     OPT_a = (1 << 0),
     OPT_u = (1 << 1),
     OPT_r = (1 << 2) * ENABLE_FEATURE_RUN_PARTS_LONG_OPTIONS,
     OPT_t = (1 << 3) * ENABLE_FEATURE_RUN_PARTS_LONG_OPTIONS,
     OPT_e = (1 << 4) * ENABLE_FEATURE_RUN_PARTS_LONG_OPTIONS,
     OPT_l = (1 << 5) * ENABLE_FEATURE_RUN_PARTS_LONG_OPTIONS
             * ENABLE_FEATURE_RUN_PARTS_FANCY,
 };
Function Documentation
act()
static int FAST_FUNC act (struct recursive_state * state, const char * file, struct stat * statbuf) static
Definition at line 145 of file run_parts.c.
 {
     if (state->depth == 0)
         return TRUE;
     if (state->depth == 1
      && (  !(statbuf->st_mode & (S_IFREG | S_IFLNK))
         || invalid_name(file)
         || (!(option_mask32 & OPT_l) && access(file, X_OK) != 0))
     ) {
         return SKIP;
     }
     names = xrealloc_vector(names, 4, cur);
     names[cur++] = xstrdup(file);
     /*names[cur] = NULL; - xrealloc_vector did it */
     return TRUE;
 }
References access(), cur, invalid_name(), names, OPT_l, option_mask32, S_IFLNK, S_IFREG, SKIP, stat::st_mode, state, TRUE, X_OK, xrealloc_vector, and xstrdup().
Referenced by _nl_find_msg(), activate_group(), find_command(), initialize_terminating_signals(), reset_terminating_signals(), rl_set_sighandler(), run_parts_main(), setsignal(), sigaction_set(), and tcsetattr().
bb_alphasort()
static int bb_alphasort (const void * p1, const void * p2) static
Definition at line 139 of file run_parts.c.
 {
     int r = strcmp(*(char **) p1, *(char **) p2);
     return (option_mask32 & OPT_r) ? -r : r;
 }
References OPT_r, option_mask32, and strcmp.
Referenced by run_parts_main().
invalid_name()
static bool invalid_name (const char * c) static
Definition at line 118 of file run_parts.c.
 {
     c = bb_basename(c);
     if (*c == '.')
         return *c;
     /* Debian run-parts 4.8.3, manpage:
      * "...the names must consist entirely of ASCII letters,
      * ASCII digits, ASCII underscores, and ASCII minus-hyphens.
      * However, the name must not begin with a period."
      * The last sentence is a giveaway that something is fishy
      * (why mention leading dot if dots are not allowed anyway?).
      * Yes, you guessed it right: in fact non-leading dots ARE allowed.
      */
     while (isalnum(*c) || *c == '_' || *c == '-' || *c == '.')
         c++;
     return *c; /* TRUE (!0) if terminating NUL is not reached */
 }
References bb_basename(), c, and isalnum.
Referenced by act().
run_parts_main()
int run_parts_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 186 of file run_parts.c.
 {
     const char *umask_p = "22";
     llist_t *arg_list = NULL;
     unsigned n;
     int ret;
     INIT_G();
     /* We require exactly one argument: the directory name */
     GETOPT32(argv, "^" "a:*u:" "\0" "=1" LONGOPTS,
             &arg_list, &umask_p
     );
     umask(xstrtou_range(umask_p, 8, 0, 07777));
     n = 1;
     while (arg_list && n < NUM_CMD) {
         cmd[n++] = llist_pop(&arg_list);
     }
     /* cmd[n] = NULL; - is already zeroed out */
     /* run-parts has to sort executables by name before running them */
     recursive_action(argv[optind],
             ACTION_RECURSE|ACTION_FOLLOWLINKS,
             act,            /* file action */
             act,            /* dir action */
             NULL            /* user data */
     );
     if (!names)
         return 0;
     qsort(names, cur, sizeof(char *), bb_alphasort);
     n = 0;
     while (1) {
         char *name = *names++;
         if (!name)
             break;
         if (option_mask32 & (OPT_t | OPT_l)) {
             puts(name);
             continue;
         }
         cmd[0] = name;
         ret = spawn_and_wait(cmd);
         if (ret == 0)
             continue;
         n = 1;
         if (ret < 0)
             bb_perror_msg("can't execute '%s'", name);
         else /* ret > 0 */
             bb_error_msg("%s: exit status %u", name, ret & 0xff);
         if (option_mask32 & OPT_e)
             xfunc_die();
     }
     return n;
 }
References act(), ACTION_FOLLOWLINKS, ACTION_RECURSE, argv, bb_alphasort(), bb_error_msg(), bb_perror_msg(), cmd, cur, GETOPT32, INIT_G, llist_pop(), LONGOPTS, n, names, NULL, NUM_CMD, OPT_e, OPT_l, OPT_t, optind, option_mask32, puts(), qsort(), recursive_action(), spawn_and_wait(), umask(), and xfunc_die().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING