Fennix Userspace: Userspace/mlibc/sysdeps/managarm/generic/file.cpp File Reference
file.cpp File Reference
#include <string.h>
#include <errno.h>
#include <sys/auxv.h>
#include <asm/ioctls.h>
#include <unistd.h>
#include <dirent.h>
#include <fcntl.h>
#include <termios.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/inotify.h>
#include <sys/eventfd.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/timerfd.h>
#include <sys/signalfd.h>
#include <sys/sysmacros.h>
#include <linux/kd.h>
#include <linux/input.h>
#include <linux/cdrom.h>
#include <linux/vt.h>
#include <drm/drm.h>
#include <drm/drm_fourcc.h>
#include <bits/ensure.h>
#include <mlibc/allocator.hpp>
#include <mlibc/debug.hpp>
#include <mlibc/posix-pipe.hpp>
#include <mlibc/all-sysdeps.hpp>
#include <posix.frigg_bragi.hpp>
#include <fs.frigg_bragi.hpp>
Namespaces
mlibc
Functions
HelHandle __mlibc_getPassthrough (int fd)
int mlibc::sys_chdir (const char *path)
int mlibc::sys_fchdir (int fd)
int mlibc::sys_chroot (const char *path)
int mlibc::sys_mkdir (const char *path, mode_t mode)
int mlibc::sys_mkdirat (int dirfd, const char *path, mode_t mode)
int mlibc::sys_symlink (const char *target_path, const char *link_path)
int mlibc::sys_symlinkat (const char *target_path, int dirfd, const char *link_path)
int mlibc::sys_link (const char *old_path, const char *new_path)
int mlibc::sys_linkat (int olddirfd, const char *old_path, int newdirfd, const char *new_path, int flags)
int mlibc::sys_rename (const char *path, const char *new_path)
int mlibc::sys_renameat (int olddirfd, const char *old_path, int newdirfd, const char *new_path)
HelHandle __raw_map (int fd)
int mlibc::sys_fcntl (int fd, int request, va_list args, int *result)
int mlibc::sys_open_dir (const char *path, int *handle)
int mlibc::sys_read_entries (int handle, void *buffer, size_t max_size, size_t *bytes_read)
int mlibc::sys_ttyname (int fd, char *buf, size_t size)
int mlibc::sys_fdatasync (int fd)
int mlibc::sys_getcwd (char *buffer, size_t size)
int mlibc::sys_vm_map (void *hint, size_t size, int prot, int flags, int fd, off_t offset, void **window)
int mlibc::sys_vm_remap (void *pointer, size_t size, size_t new_size, void **window)
int mlibc::sys_vm_protect (void *pointer, size_t size, int prot)
int mlibc::sys_vm_unmap (void *pointer, size_t size)
int mlibc::sys_setsid (pid_t *sid)
int mlibc::sys_tcgetattr (int fd, struct termios *attr)
int mlibc::sys_tcsetattr (int, int, const struct termios *attr)
int mlibc::sys_tcdrain (int)
int mlibc::sys_socket (int family, int type, int protocol, int *fd)
int mlibc::sys_pipe (int *fds, int flags)
int mlibc::sys_socketpair (int domain, int type_and_flags, int proto, int *fds)
int mlibc::sys_msg_send (int fd, const struct msghdr *hdr, int flags, ssize_t *length)
int mlibc::sys_msg_recv (int fd, struct msghdr *hdr, int flags, ssize_t *length)
int mlibc::sys_pselect (int num_fds, fd_set *read_set, fd_set *write_set, fd_set *except_set, const struct timespec *timeout, const sigset_t *sigmask, int *num_events)
int mlibc::sys_poll (struct pollfd *fds, nfds_t count, int timeout, int *num_events)
int mlibc::sys_epoll_create (int flags, int *fd)
int mlibc::sys_epoll_ctl (int epfd, int mode, int fd, struct epoll_event *ev)
int mlibc::sys_epoll_pwait (int epfd, struct epoll_event *ev, int n, int timeout, const sigset_t *sigmask, int *raised)
int mlibc::sys_timerfd_create (int clockid, int flags, int *fd)
int mlibc::sys_timerfd_settime (int fd, int flags, const struct itimerspec *value, struct itimerspec *oldvalue)
int mlibc::sys_signalfd_create (const sigset_t *, int flags, int *fd)
int mlibc::sys_inotify_create (int flags, int *fd)
int mlibc::sys_inotify_add_watch (int ifd, const char *path, uint32_t mask, int *wd)
int mlibc::sys_eventfd_create (unsigned int initval, int flags, int *fd)
int mlibc::sys_ioctl (int fd, unsigned long request, void *arg, int *result)
int mlibc::sys_open (const char *pathname, int flags, mode_t mode, int *fd)
int mlibc::sys_openat (int dirfd, const char *path, int flags, mode_t mode, int *fd)
int mlibc::sys_mkfifoat (int dirfd, const char *path, mode_t mode)
int mlibc::sys_mknodat (int dirfd, const char *path, int mode, int dev)
int mlibc::sys_read (int fd, void *buf, size_t count, ssize_t *bytes_read)
int mlibc::sys_write (int fd, const void *buf, size_t count, ssize_t *bytes_written)
int mlibc::sys_pread (int fd, void *buf, size_t n, off_t off, ssize_t *bytes_read)
int mlibc::sys_pwrite (int fd, const void *buf, size_t n, off_t off, ssize_t *bytes_read)
int mlibc::sys_seek (int fd, off_t offset, int whence, off_t *new_offset)
int mlibc::sys_close (int fd)
int mlibc::sys_dup (int fd, int flags, int *newfd)
int mlibc::sys_dup2 (int fd, int flags, int newfd)
int mlibc::sys_stat (fsfd_target fsfdt, int fd, const char *path, int flags, struct stat *statbuf)
int mlibc::sys_readlink (const char *path, void *buffer, size_t max_size, ssize_t *length)
int mlibc::sys_rmdir (const char *path)
int mlibc::sys_ftruncate (int fd, size_t size)
int mlibc::sys_fallocate (int fd, off_t offset, size_t size)
int mlibc::sys_unlinkat (int dirfd, const char *path, int flags)
int mlibc::sys_access (const char *path, int mode)
int mlibc::sys_faccessat (int dirfd, const char *pathname, int mode, int flags)
int mlibc::sys_flock (int fd, int options)
int mlibc::sys_isatty (int fd)
int mlibc::sys_chmod (const char *pathname, mode_t mode)
int mlibc::sys_fchmod (int fd, mode_t mode)
int mlibc::sys_fchmodat (int fd, const char *pathname, mode_t mode, int flags)
int mlibc::sys_utimensat (int dirfd, const char *pathname, const struct timespec times[2], int flags)
int mlibc::sys_getentropy (void *buffer, size_t length)
int mlibc::sys_gethostname (char *buffer, size_t bufsize)
int mlibc::sys_fsync (int fd)
int mlibc::sys_memfd_create (const char *name, int flags, int *fd)
int mlibc::sys_uname (struct utsname *buf)
int mlibc::sys_madvise (void *addr, size_t length, int advice)
Function Documentation
__mlibc_getPassthrough()
HelHandle __mlibc_getPassthrough (int fd)
Definition at line 43 of file file.cpp.
{
     auto handle = getHandleForFd(fd);
     __ensure(handle);
     return handle;
 }
References __ensure, and getHandleForFd().
__raw_map()
HelHandle __raw_map (int fd)
Definition at line 334 of file file.cpp.
{
     SignalGuard sguard;
     HelAction actions[4];
     globalQueue.trim();
     auto handle = getHandleForFd(fd);
     if (!handle)
         return 0;
     managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_req_type(managarm::fs::CntReqType::MMAP);
     req.set_fd(fd);
     frg::string<MemoryAllocator> ser(getSysdepsAllocator());
     req.SerializeToString(&ser);
     actions[0].type = kHelActionOffer;
     actions[0].flags = kHelItemAncillary;
     actions[1].type = kHelActionSendFromBuffer;
     actions[1].flags = kHelItemChain;
     actions[1].buffer = ser.data();
     actions[1].length = ser.size();
     actions[2].type = kHelActionRecvInline;
     actions[2].flags = kHelItemChain;
     actions[3].type = kHelActionPullDescriptor;
     actions[3].flags = 0;
     HEL_CHECK(helSubmitAsync(handle, actions, 4,
             globalQueue.getQueue(), 0, 0));
     auto element = globalQueue.dequeueSingle();
     auto offer = parseHandle(element);
     auto send_req = parseSimple(element);
     auto recv_resp = parseInline(element);
     auto pull_memory = parseHandle(element);
     HEL_CHECK(offer->error);
     HEL_CHECK(send_req->error);
     HEL_CHECK(recv_resp->error);
     HEL_CHECK(pull_memory->error);
     managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp->data, recv_resp->length);
     __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
     return pull_memory->handle;
 }
References __ensure, Queue::dequeueSingle(), getHandleForFd(), Queue::getQueue(), getSysdepsAllocator(), globalQueue, parseHandle(), parseInline(), parseSimple(), and Queue::trim().