Fennix: Userspace/musl/src/stdio/__stdio_exit.c File Reference
__stdio_exit.c File Reference
#include "stdio_impl.h"
Functions
weak_alias (dummy_file, __stdin_used)
weak_alias (dummy_file, __stdout_used)
weak_alias (dummy_file, __stderr_used)
static void close_file (FILE *f)
void __stdio_exit (void)
weak_alias (__stdio_exit, __stdio_exit_needed)
Variables
static FILE *volatile dummy_file = 0
Function Documentation
__stdio_exit()
void __stdio_exit (void)
Definition at line 16 of file __stdio_exit.c.
 {
     FILE *f;
     for (f=*__ofl_lock(); f; f=f->next) close_file(f);
     close_file(__stdin_used);
     close_file(__stdout_used);
     close_file(__stderr_used);
 }
References __ofl_lock(), __stderr_used, __stdin_used, __stdout_used, close_file(), and f.
Referenced by exit().
close_file()
static void close_file (FILE * f) static
Definition at line 8 of file __stdio_exit.c.
 {
     if (!f) return;
     FFINALLOCK(f);
     if (f->wpos != f->wbase) f->write(f, 0, 0);
     if (f->rpos != f->rend) f->seek(f, f->rpos-f->rend, SEEK_CUR);
 }
References f, FFINALLOCK, and SEEK_CUR.
Referenced by __stdio_exit().
weak_alias() [1/4]
weak_alias (__stdio_exit , __stdio_exit_needed)
weak_alias() [2/4]
weak_alias (dummy_file , __stderr_used)
weak_alias() [3/4]
weak_alias (dummy_file , __stdin_used)
weak_alias() [4/4]
weak_alias (dummy_file , __stdout_used)
Variable Documentation
dummy_file
FILE* volatile dummy_file = 0 static
Definition at line 3 of file __stdio_exit.c.