Fennix: Userspace/musl/compat/time32/__xstat.c File Reference
__xstat.c File Reference
#include "time32.h"
#include <sys/stat.h>
Functions
int __fxstat (int ver, int fd, struct stat32 *buf)
int __fxstatat (int ver, int fd, const char *path, struct stat32 *buf, int flag)
int __lxstat (int ver, const char *path, struct stat32 *buf)
int __xstat (int ver, const char *path, struct stat32 *buf)
Function Documentation
__fxstat()
int __fxstat (int ver, int fd, struct stat32 * buf)
Definition at line 6 of file __xstat.c.
 {
     return __fstat_time32(fd, buf);
 }
References __fstat_time32(), buf, and fd.
__fxstatat()
int __fxstatat (int ver, int fd, const char * path, struct stat32 * buf, int flag)
Definition at line 11 of file __xstat.c.
 {
     return __fstatat_time32(fd, path, buf, flag);
 }
References __fstatat_time32(), buf, and fd.
__lxstat()
int __lxstat (int ver, const char * path, struct stat32 * buf)
Definition at line 16 of file __xstat.c.
 {
     return __lstat_time32(path, buf);
 }
References __lstat_time32(), and buf.
__xstat()
int __xstat (int ver, const char * path, struct stat32 * buf)
Definition at line 21 of file __xstat.c.
 {
     return __stat_time32(path, buf);
 }
References __stat_time32(), and buf.