Fennix: Kernel/arch/amd64/bootstrap/multiboot/Paging/mb_64bit_map.cpp File Reference
mb_64bit_map.cpp File Reference
#include <types.h>
Data Structures
struct PageTable4
class PageMapIndexer
Functions
union __attribute__ ((packed)) PageTableEntry
struct PageTable4 __attribute__ ((aligned(0x1000)))
__attribute__ ((section(".bootstrap.data"))) static PageTable4 *BPTable
__always_inline nsa NIF void * RequestPage ()
__attribute__ ((section(".bootstrap.text"))) nsa NIF void MB2_64_Map(void *VirtualAddress
if (!PML4.Present)
if (!PDPTE.Present)
if (!PDE.Present)
PTE SetAddress ((uintptr_t) PhysicalAddress >> 12)
asmv ("invlpg (%0)" ::"r"(VirtualAddress) :"memory")
Variables
PageMapLevel4 Entries [512] = PML4
char BootPageTable []
uintptr_t _kernel_start
uintptr_t _kernel_end
class PageMapIndexer __attribute__
void * PhysicalAddress
void uint64_t Flags
uint64_t DirectoryFlags = Flags & 0x3F
PageMapLevel4 PML4 = BPTable->Entries[Index.PMLIndex]
PageDirectoryPointerTableEntryPtr * PDPTEPtr = nullptr
PML4 raw = DirectoryFlags
PageDirectoryPointerTableEntry PDPTE = PDPTEPtr->Entries[Index.PDPTEIndex]
PageDirectoryEntryPtr * PDEPtr = nullptr
PageDirectoryEntry PDE = PDEPtr->Entries[Index.PDEIndex]
PageTableEntryPtr * PTEPtr = nullptr
PageTableEntry PTE = PTEPtr->Entries[Index.PTEIndex]
PTE Present = true
Data Structure Documentation
PageTable4
struct PageTable4
Definition at line 153 of file mb_64bit_map.cpp.
Data Fields
PageMapLevel4 Entries[512]
Function Documentation
__attribute__() [1/4]
struct PageTable4 __attribute__ ((aligned(0x1000)))
__attribute__() [2/4]
union __attribute__ ((packed))
Definition at line 1 of file mb_64bit_map.cpp.
 {
     struct
     {
         bool Present : 1;            // 0
         bool ReadWrite : 1;          // 1
         bool UserSupervisor : 1;     // 2
         bool WriteThrough : 1;       // 3
         bool CacheDisable : 1;       // 4
         bool Accessed : 1;           // 5
         bool Dirty : 1;              // 6
         bool PageAttributeTable : 1; // 7
         bool Global : 1;             // 8
         uint8_t Available0 : 3;      // 9-11
         uint64_t Address : 40;       // 12-51
         uint32_t Available1 : 7;     // 52-58
         uint8_t ProtectionKey : 4;   // 59-62
         bool ExecuteDisable : 1;     // 63
     };
     uint64_t raw;
     __always_inline inline nsa NIF void SetAddress(uintptr_t _Address)
     {
         _Address &= 0x000000FFFFFFFFFF;
         this->raw &= 0xFFF0000000000FFF;
         this->raw |= (_Address << 12);
     }
     __always_inline inline nsa NIF uintptr_t GetAddress() { return (this->raw & 0x000FFFFFFFFFF000) >> 12; }
 };
References __always_inline, Address, NIF, nsa, Present, raw, and SetAddress().
__attribute__() [3/4]
__attribute__ ((section(".bootstrap.data")))
__attribute__() [4/4]
__attribute__ ((section(".bootstrap.text")))
Definition at line 283 of file mb_64bit_map.cpp.
 {
     BPTable = (PageTable4 *)BootPageTable;
     uintptr_t KernelStart = (uintptr_t)&_kernel_start;
     uintptr_t KernelEnd = (uintptr_t)&_kernel_end;
     uintptr_t PhysicalStart = KernelStart - 0xFFFFFFFF80000000;
     for (uintptr_t i = KernelStart; i < KernelEnd; i += 0x1000)
     {
         MB2_64_Map((void *)i, (void *)PhysicalStart, 0x3);
         PhysicalStart += 0x1000;
     }
     asmv("mov %%cr3, %%rax\n"
          "mov %%rax, %%cr3\n"
          :
          :
          : "rax");
 }
References _kernel_end, _kernel_start, asmv(), BootPageTable, and i.
asmv()
asmv ("invlpg (%0)" ::"r"(VirtualAddress) :"memory")
Referenced by __aligned(), __attribute__(), __convert_chk_fail(), __cpuid(), __cyg_profile_func_enter(), __cyg_profile_func_exit(), __new_alloc_page(), __stack_chk_fail(), __strlen(), SMAP::_clac(), FXSR::_fxrstor64(), FXSR::_fxsave64(), SMAP::_stac(), AutoSwitchPageTable::AutoSwitchPageTable(), CPU::MemBar::Barrier(), CPU::CheckSIMD(), cmd_panic(), CPU::Counter(), CPU::x32::cpuid(), CPU::x64::cpuid(), EnterCriticalSection(), Entry(), CPU::MemBar::Fence(), CPU::x32::fxrstor(), CPU::x64::fxrstor(), CPU::x32::fxsave(), CPU::x64::fxsave(), CPU::Halt(), GlobalDescriptorTable::Init(), InitLimine(), InitLimineAfterStack(), CPU::Interrupts(), CPU::x32::invlpg(), CPU::x64::invlpg(), IsVMwareBackdoorAvailable(), LeaveCriticalSection(), CPU::x32::lgdt(), CPU::x64::lgdt(), CPU::x32::lidt(), CPU::x64::lidt(), linux_fork_return(), linux_mprotect(), CPU::MemBar::LoadFence(), CPU::x32::ltr(), CPU::x64::ltr(), memcpy_sse(), memcpy_sse2(), memcpy_sse3(), memcpy_sse4_1(), memcpy_sse4_2(), memcpy_ssse3(), memset_sse2(), memset_sse4_2(), CPU::PageTable(), CPU::Pause(), Random::rand16(), Random::rand32(), Random::rand64(), Power::Power::Reboot(), GlobalDescriptorTable::SetKernelStack(), StartCPU(), CPU::Stop(), CPU::MemBar::StoreFence(), strlen_sse4_2(), sys_fork_return(), sys_mprotect(), Memory::PageTable::Update(), Tasking::Task::Yield(), and AutoSwitchPageTable::~AutoSwitchPageTable().
if() [1/3]
if (!PDE. Present)
Definition at line 251 of file mb_64bit_map.cpp.
     {
         PTEPtr = (PageTableEntryPtr *)RequestPage();
         if (PTEPtr == nullptr)
             return;
         {
             void *ptr = PTEPtr;
             uint8_t value = 0;
             size_t num = 0x1000;
             uint8_t *p = (uint8_t *)ptr;
             for (size_t i = 0; i < num; i++)
                 p[i] = value;
         }
         PDE.Present = true;
         PDE.SetAddress((uintptr_t)PTEPtr >> 12);
     }
References i, num, p, PDE, PTEPtr, RequestPage(), and value.
if() [2/3]
if (!PDPTE. Present)
Definition at line 228 of file mb_64bit_map.cpp.
     {
         PDEPtr = (PageDirectoryEntryPtr *)RequestPage();
         if (PDEPtr == nullptr)
             return;
         {
             void *ptr = PDEPtr;
             uint8_t value = 0;
             size_t num = 0x1000;
             uint8_t *p = (uint8_t *)ptr;
             for (size_t i = 0; i < num; i++)
                 p[i] = value;
         }
         PDPTE.Present = true;
         PDPTE.SetAddress((uintptr_t)PDEPtr >> 12);
     }
References i, num, p, PDEPtr, PDPTE, RequestPage(), and value.
if() [3/3]
if (!PML4. Present)
Definition at line 205 of file mb_64bit_map.cpp.
     {
         PDPTEPtr = (PageDirectoryPointerTableEntryPtr *)RequestPage();
         if (PDPTEPtr == nullptr)
             return;
         {
             void *ptr = PDPTEPtr;
             uint8_t value = 0;
             size_t num = 0x1000;
             uint8_t *p = (uint8_t *)ptr;
             for (size_t i = 0; i < num; i++)
                 p[i] = value;
         }
         PML4.Present = true;
         PML4.SetAddress((uintptr_t)PDPTEPtr >> 12);
     }
References i, num, p, PDPTEPtr, PML4, RequestPage(), and value.
Referenced by __dls3(), __fdopen(), Memory::__no_sanitize(), SymbolResolver::__no_sanitize(), _evalfile(), _rl_isearch_dispatch(), _rl_isearch_init(), _rl_read_file(), _rpmalloc_heap_global_finalize(), add_peers(), adjust_poll(), awk_getline(), awk_split(), bgp_resize(), builtin_handler(), concat_option(), config_file_action(), cxx_Finalize(), cxx_Initialize(), cxx_Probe(), dd_main(), do_relocs(), do_syslogd(), execute_function(), execute_in_subshell(), exponent(), extend_bfs_deps(), fix_assignment_words(), fork(), get_local_var_value(), get_server_hello(), getaddrinfo(), glob(), gnu_lookup(), grep_file(), grep_main(), history_truncate_file(), i_getch(), ifupdown_main(), in_ether(), inflate_codes(), ConfigItem::init(), KernelVFS(), last_main(), make_history_line_current(), makunbound(), map_library(), more_main(), nextafter(), nextafterf(), nmeter_main(), ntpd_main(), o_save_ptr_helper(), optimize_shell_function(), P_DamageMobj(), P_SpawnPlayer(), P_ZMovement(), pos_params(), print_neigh(), pstm_div(), read_history_range(), read_interfaces(), redraw(), regexec(), regfree(), restore_parser_state(), rl_do_undo(), scan_request(), server_print(), static_dl_iterate_phdr(), static_init_tls(), sym_calc_value(), Tasking::Task::Task(), tls_xread_handshake_block(), tls_xread_record(), traverses_stack_p(), tre_compute_nfl(), tre_match_empty(), tre_tnfa_run_parallel(), unbind_func(), update_local_clock(), vsnprintf_internal(), WI_updateNetgameStats(), write_builtins(), and write_longdocs().
RequestPage()
__always_inline nsa NIF void* RequestPage () inline
Definition at line 164 of file mb_64bit_map.cpp.
 {
     void *Page = (void *)(BootPageTable + BPT_Allocated);
     BPT_Allocated += 0x1000;
     if (BPT_Allocated >= 0x10000) /* The length of BootPageTable */
     {
         while (true)
             ;
     }
     return Page;
 }
References BootPageTable.
Referenced by if().
SetAddress()
PTE SetAddress ((uintptr_t) PhysicalAddress >> 12)
Referenced by __attribute__().
Variable Documentation
__attribute__
class PageMapIndexer __attribute__
_kernel_end
uintptr_t _kernel_end
Definition at line 159 of file mb_64bit_map.cpp.
Referenced by __attribute__(), DisplayStackScreen(), ExGetKSymbol(), MapKernel(), multiboot2_parse(), multiboot_parse(), and WriteDiagDataToNode().
_kernel_start
uintptr_t _kernel_start extern
Referenced by __attribute__(), DisplayStackScreen(), ExGetKSymbol(), MapKernel(), multiboot2_parse(), multiboot_parse(), and WriteDiagDataToNode().
BootPageTable
char BootPageTable[]
Definition at line 158 of file mb_64bit_map.cpp.
Referenced by __attribute__(), and RequestPage().
DirectoryFlags
uint64_t DirectoryFlags = Flags & 0x3F
Definition at line 201 of file mb_64bit_map.cpp.
Entries
PTEPtr Entries = PML4
Definition at line 0 of file mb_64bit_map.cpp.
Referenced by InterruptDescriptorTable::__aligned(), Disk::Manager::FetchDisks(), Memory::PageTable::Fork(), PCI::Manager::Manager(), and InterruptDescriptorTable::SetEntry().
Flags
void uint64_t Flags
Initial value:
{
    PageMapIndexer Index = PageMapIndexer((uintptr_t)VirtualAddress)
Definition at line 197 of file mb_64bit_map.cpp.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor(), EnterCriticalSection(), Memory::VirtualMemoryArea::Fork(), CPU::Interrupts(), Memory::Virtual::Map(), Driver::MapPages(), MapPages(), vfs::Node::open(), Driver::SlaveDeviceFile::open(), Driver::MasterDeviceFile::open(), vfs::PTMXDevice::open(), Memory::Virtual::OptimizedMap(), vfs::FileDescriptorTable::ProbeMode(), APIC::APIC::RawRedirectIRQ(), Memory::Virtual::Remap(), Memory::VirtualMemoryArea::RequestPages(), vfs::FileDescriptorTable::SetFlags(), and Xalloc_MAP_MEMORY().
PDE
PageDirectoryEntry PDE = PDEPtr->Entries[Index.PDEIndex]
Definition at line 249 of file mb_64bit_map.cpp.
Referenced by Memory::PageTable::Fork(), Memory::Virtual::GetMapType(), Memory::Virtual::GetPDE(), Memory::Virtual::GetPTE(), and if().
PDEPtr
else PDEPtr = nullptr
Definition at line 227 of file mb_64bit_map.cpp.
Referenced by Memory::Virtual::GetPDE(), Memory::Virtual::GetPTE(), and if().
PDPTE
PageDirectoryPointerTableEntry PDPTE = PDPTEPtr->Entries[Index.PDPTEIndex]
Definition at line 226 of file mb_64bit_map.cpp.
Referenced by Memory::Virtual::GetMapType(), Memory::Virtual::GetPDE(), Memory::Virtual::GetPTE(), and if().
PDPTEPtr
else PDPTEPtr = nullptr
Definition at line 204 of file mb_64bit_map.cpp.
Referenced by Memory::Virtual::GetPDE(), Memory::Virtual::GetPTE(), and if().
PhysicalAddress
void* PhysicalAddress
Definition at line 197 of file mb_64bit_map.cpp.
Referenced by Memory::Virtual::Map(), Driver::MapPages(), MapPages(), Memory::Virtual::OptimizedMap(), Memory::Virtual::Remap(), and Xalloc_MAP_MEMORY().
PML4
PageMapLevel4 PML4 = BPTable->Entries[Index.PMLIndex]
Definition at line 203 of file mb_64bit_map.cpp.
Referenced by Memory::PageTable::Fork(), Memory::Virtual::GetMapType(), Memory::Virtual::GetPDE(), Memory::Virtual::GetPTE(), and if().
Present
PTE Present = true
Definition at line 273 of file mb_64bit_map.cpp.
Referenced by __attribute__(), and InterruptDescriptorTable::SetEntry().
PTE
PageTableEntry PTE = PTEPtr->Entries[Index.PTEIndex]
Definition at line 272 of file mb_64bit_map.cpp.
Referenced by Memory::PageTable::Fork(), Memory::Virtual::GetMapType(), and Memory::Virtual::GetPTE().
PTEPtr
else PTEPtr = nullptr
Definition at line 250 of file mb_64bit_map.cpp.
Referenced by Memory::Virtual::GetPTE(), and if().
raw
PTE raw = DirectoryFlags
Definition at line 223 of file mb_64bit_map.cpp.
Referenced by __attribute__(), check_header_gzip(), get_header_ar(), handle_port(), iproute_modify(), print_builtin(), V_DrawRawScreen(), and visible().