Fennix Kernel: Time::time Class Reference
Time::time Class Reference
#include <time.hpp>
Public Types
enum TimeActiveTimer {
NONE = 0b0 , RTC = 0b1 , PIT = 0b10 , HPET = 0b100 ,
ACPI = 0b1000 , APIC = 0b10000 , TSC = 0b100000
}
Public Member Functions
int GetSupportedTimers ()
TimeActiveTimer GetActiveTimer ()
bool ChangeActiveTimer (TimeActiveTimer Timer)
bool Sleep (size_t Duration, Units Unit)
size_t GetCounter ()
size_t CalculateTarget (size_t Target, Units Unit)
size_t GetNanosecondsSinceClassCreation ()
void FindTimers (void *acpi)
time ()
~time ()
Private Attributes
int SupportedTimers = 0
TimeActiveTimer ActiveTimer = NONE
HighPrecisionEventTimer * hpet
TimeStampCounter * tsc
Detailed Description
Definition at line 160 of file time.hpp.
Member Enumeration Documentation
TimeActiveTimer
enum Time::time::TimeActiveTimer
Enumerator
NONE
RTC
PIT
HPET
ACPI
APIC
TSC
Definition at line 163 of file time.hpp.
         {
             NONE = 0b0,
             RTC = 0b1,
             PIT = 0b10,
             HPET = 0b100,
             ACPI = 0b1000,
             APIC = 0b10000,
             TSC = 0b100000
         };
Constructor & Destructor Documentation
time()
Time::time::time ()
Definition at line 208 of file Timer.cpp.
     {
     }
~time()
Time::time::~time ()
Definition at line 212 of file Timer.cpp.
     {
     }
Member Function Documentation
CalculateTarget()
size_t Time::time::CalculateTarget (size_t Target, Units Unit)
Definition at line 93 of file Timer.cpp.
     {
         switch (ActiveTimer)
         {
         case NONE:
             error("No timer is active");
             return false;
         case RTC:
             fixme("RTC sleep not implemented");
             return false;
         case PIT:
             fixme("PIT sleep not implemented");
             return false;
         case HPET:
             return this->hpet->CalculateTarget(Target, Unit);
         case ACPI:
             fixme("ACPI sleep not implemented");
             return false;
         case APIC:
             fixme("APIC sleep not implemented");
             return false;
         case TSC:
             return this->tsc->CalculateTarget(Target, Unit);
         default:
             error("Unknown timer");
             return false;
         }
     }
References ACPI, ActiveTimer, APIC, Time::HighPrecisionEventTimer::CalculateTarget(), Time::TimeStampCounter::CalculateTarget(), error, fixme, HPET, hpet, NONE, PIT, RTC, TSC, and tsc.
Referenced by Execute::AddLibrary(), Execute::LibraryManagerService(), and Tasking::Task::Sleep().
ChangeActiveTimer()
bool Time::time::ChangeActiveTimer (TimeActiveTimer Timer) inline
Definition at line 184 of file time.hpp.
         {
             if (!(SupportedTimers & Timer))
                 return false;
             ActiveTimer = Timer;
             return true;
         }
References ActiveTimer, and SupportedTimers.
FindTimers()
void Time::time::FindTimers (void * acpi)
Definition at line 151 of file Timer.cpp.
     {
 #if defined(a86)
         /* TODO: RTC check */
         /* TODO: PIT check */
         if (acpi)
         {
             if (((ACPI::ACPI *)acpi)->HPET)
             {
                 hpet = new HighPrecisionEventTimer(((ACPI::ACPI *)acpi)->HPET);
                 ActiveTimer = HPET;
                 SupportedTimers |= HPET;
                 KPrint("\e11FF11HPET found");
             }
             else
             {
                 KPrint("\eFF2200HPET not found");
             }
             /* TODO: ACPI check */
             /* TODO: APIC check */
         }
         else
         {
             KPrint("\eFF2200ACPI not found");
         }
         bool TSCInvariant = false;
         if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
         {
             CPU::x86::AMD::CPUID0x80000007 cpuid80000007;
             cpuid80000007.Get();
             if (cpuid80000007.EDX.TscInvariant)
                 TSCInvariant = true;
         }
         else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
         {
             // TODO: Intel 0x80000007
             CPU::x86::AMD::CPUID0x80000007 cpuid80000007;
             cpuid80000007.Get();
             if (cpuid80000007.EDX.TscInvariant)
                 TSCInvariant = true;
         }
         if (TSCInvariant)
         {
             tsc = new TimeStampCounter;
             // FIXME: ActiveTimer = TSC;
             SupportedTimers |= TSC;
             KPrint("\e11FF11Invariant TSC found");
         }
         else
             KPrint("\eFF2200TSC is not invariant");
 #endif
     }
References ActiveTimer, CPU::x86::AMD::CPUID0x80000007::EDX, CPU::x86::AMD::CPUID0x80000007::Get(), HPET, hpet, KPrint(), strcmp(), SupportedTimers, TSC, tsc, CPU::Vendor(), x86_CPUID_VENDOR_AMD, and x86_CPUID_VENDOR_INTEL.
Referenced by Main().
GetActiveTimer()
TimeActiveTimer Time::time::GetActiveTimer () inline
Definition at line 183 of file time.hpp.
 { return ActiveTimer; }
References ActiveTimer.
GetCounter()
size_t Time::time::GetCounter ()
Definition at line 64 of file Timer.cpp.
     {
         switch (ActiveTimer)
         {
         case NONE:
             error("No timer is active");
             return false;
         case RTC:
             fixme("RTC sleep not implemented");
             return false;
         case PIT:
             fixme("PIT sleep not implemented");
             return false;
         case HPET:
             return this->hpet->GetCounter();
         case ACPI:
             fixme("ACPI sleep not implemented");
             return false;
         case APIC:
             fixme("APIC sleep not implemented");
             return false;
         case TSC:
             return this->tsc->GetCounter();
         default:
             error("Unknown timer");
             return false;
         }
     }
References ACPI, ActiveTimer, APIC, error, fixme, Time::HighPrecisionEventTimer::GetCounter(), Time::TimeStampCounter::GetCounter(), HPET, hpet, NONE, PIT, RTC, TSC, and tsc.
Referenced by Tasking::Task::CreateProcess(), Execute::LibraryManagerService(), SystemCallsHandler(), and Tasking::Task::UpdateUsage().
GetNanosecondsSinceClassCreation()
size_t Time::time::GetNanosecondsSinceClassCreation ()
Definition at line 122 of file Timer.cpp.
     {
         switch (ActiveTimer)
         {
         case NONE:
             error("No timer is active");
             return false;
         case RTC:
             fixme("RTC sleep not implemented");
             return false;
         case PIT:
             fixme("PIT sleep not implemented");
             return false;
         case HPET:
             return this->hpet->GetNanosecondsSinceClassCreation();
         case ACPI:
             fixme("ACPI sleep not implemented");
             return false;
         case APIC:
             fixme("APIC sleep not implemented");
             return false;
         case TSC:
             return this->tsc->GetNanosecondsSinceClassCreation();
         default:
             error("Unknown timer");
             return false;
         }
     }
References ACPI, ActiveTimer, APIC, error, fixme, Time::HighPrecisionEventTimer::GetNanosecondsSinceClassCreation(), Time::TimeStampCounter::GetNanosecondsSinceClassCreation(), HPET, hpet, NONE, PIT, RTC, TSC, and tsc.
Referenced by KPrint().
GetSupportedTimers()
int Time::time::GetSupportedTimers () inline
Definition at line 182 of file time.hpp.
 { return SupportedTimers; }
References SupportedTimers.
Sleep()
bool Time::time::Sleep (size_t Duration, Units Unit)
Definition at line 35 of file Timer.cpp.
     {
         switch (ActiveTimer)
         {
         case NONE:
             error("No timer is active");
             return false;
         case RTC:
             fixme("RTC sleep not implemented");
             return false;
         case PIT:
             fixme("PIT sleep not implemented");
             return false;
         case HPET:
             return this->hpet->Sleep(Duration, Unit);
         case ACPI:
             fixme("ACPI sleep not implemented");
             return false;
         case APIC:
             fixme("APIC sleep not implemented");
             return false;
         case TSC:
             return this->tsc->Sleep(Duration, Unit);
         default:
             error("Unknown timer");
             return false;
         }
     }
References ACPI, ActiveTimer, APIC, error, fixme, HPET, hpet, NONE, PIT, RTC, Time::HighPrecisionEventTimer::Sleep(), Time::TimeStampCounter::Sleep(), TSC, and tsc.
Referenced by DriverSleep(), APIC::Timer::Timer(), and Time::TimeStampCounter::TimeStampCounter().
Field Documentation
ActiveTimer
TimeActiveTimer Time::time::ActiveTimer = NONE private
Definition at line 176 of file time.hpp.
Referenced by CalculateTarget(), ChangeActiveTimer(), FindTimers(), GetActiveTimer(), GetCounter(), GetNanosecondsSinceClassCreation(), and Sleep().
hpet
HighPrecisionEventTimer* Time::time::hpet private
Definition at line 178 of file time.hpp.
Referenced by CalculateTarget(), FindTimers(), GetCounter(), GetNanosecondsSinceClassCreation(), and Sleep().
SupportedTimers
int Time::time::SupportedTimers = 0 private
Definition at line 175 of file time.hpp.
Referenced by ChangeActiveTimer(), FindTimers(), and GetSupportedTimers().
tsc
TimeStampCounter* Time::time::tsc private
Definition at line 179 of file time.hpp.
Referenced by CalculateTarget(), FindTimers(), GetCounter(), GetNanosecondsSinceClassCreation(), and Sleep().
The documentation for this class was generated from the following files:
Kernel/include/time.hpp
Kernel/Core/Time/Timer.cpp