Fennix: Userspace/mlibc/options/rtdl/generic/main.cpp File Reference
main.cpp File Reference
#include <elf.h>
#include <link.h>
#include <frg/manual_box.hpp>
#include <abi-bits/auxv.h>
#include <mlibc/debug.hpp>
#include <mlibc/rtdl-sysdeps.hpp>
#include <mlibc/rtdl-config.hpp>
#include <mlibc/rtdl-abi.hpp>
#include <mlibc/stack_protector.hpp>
#include <internal-config.h>
#include "linker.hpp"
Namespaces
mlibc
Macros
#define HIDDEN __attribute__((__visibility__("hidden")))
#define EXPORT __attribute__((__visibility__("default")))
Functions
uintptr_t getLdsoBase ()
void relocateSelf ()
void * lazyRelocate (SharedObject *object, unsigned int rel_index)
void * __rtdl_allocateTcb ()
void dl_debug_state ()
void _dl_debug_state () noexcept
void * interpreterMain (uintptr_t *entry_stack)
uintptr_t * __dlapi_entrystack ()
const char * __dlapi_error ()
void * __dlapi_get_tls (struct __abi_tls_entry *entry)
const mlibc::RtdlConfig & __dlapi_get_config ()
int __dlapi_iterate_phdr (int(*callback)(struct dl_phdr_info *, size_t, void *), void *data)
void __dlapi_enter (uintptr_t *entry_stack)
Variables
static constexpr bool logEntryExit = false
static constexpr bool logStartup = false
static constexpr bool logDlCalls = false
HIDDEN void * _GLOBAL_OFFSET_TABLE_ []
HIDDEN Elf64_Dyn _DYNAMIC []
mlibc::RtdlConfig rtdlConfig
bool ldShowAuxv = false
uintptr_t * entryStack
frg::manual_box< ObjectRepository > initialRepository
frg::manual_box< Scope > globalScope
frg::manual_box< RuntimeTlsMap > runtimeTlsMap
static SharedObject * executableSO
HIDDEN char __ehdr_start []
DebugInterface globalDebugInterface
DebugInterface * _dl_debug_addr = &globalDebugInterface
const char * lastError
Macro Definition Documentation
EXPORT
#define EXPORT __attribute__((__visibility__("default")))
Definition at line 22 of file main.cpp.
HIDDEN
#define HIDDEN __attribute__((__visibility__("hidden")))
Definition at line 21 of file main.cpp.
Function Documentation
__dlapi_enter()
void __dlapi_enter (uintptr_t * entry_stack)
Definition at line 672 of file main.cpp.
{
 #if MLIBC_STATIC_BUILD
     interpreterMain(entry_stack);
 #else
     (void)entry_stack;
 #endif
 }
References interpreterMain(), and Driver::void().
Referenced by __mlibc_entry().
__dlapi_entrystack()
uintptr_t* __dlapi_entrystack ()
Definition at line 398 of file main.cpp.
{
     return entryStack;
 }
References entryStack.
Referenced by LibraryGuard::LibraryGuard(), and peekauxval().
__dlapi_error()
const char* __dlapi_error ()
Definition at line 403 of file main.cpp.
{
     auto error = lastError;
     lastError = nullptr;
     return error;
 }
References error, and lastError.
Referenced by dlerror().
__dlapi_get_config()
const mlibc::RtdlConfig& __dlapi_get_config ()
Definition at line 415 of file main.cpp.
{
     return rtdlConfig;
 }
References rtdlConfig.
Referenced by mlibc::rtdlConfig().
__dlapi_get_tls()
void* __dlapi_get_tls (struct __abi_tls_entry * entry)
Definition at line 410 of file main.cpp.
{
     return reinterpret_cast<char *>(accessDtv(entry->object)) + entry->offset;
 }
References accessDtv().
Referenced by __tls_get_addr().
__dlapi_iterate_phdr()
int __dlapi_iterate_phdr (int(*)(struct dl_phdr_info *, size_t, void *) callback, void * data)
Definition at line 641 of file main.cpp.
{
     int last_return = 0;
     for (auto object : initialRepository->loadedObjects) {
         struct dl_phdr_info info;
         info.dlpi_addr = object->baseAddress;
         info.dlpi_name = object->name.data();
         if(object->isMainObject) {
             info.dlpi_name = "";
         } else {
             info.dlpi_name = object->name.data();
         }
         info.dlpi_phdr = static_cast<ElfW(Phdr)*>(object->phdrPointer);
         info.dlpi_phnum = object->phdrCount;
         info.dlpi_adds = rtsCounter;
         info.dlpi_subs = 0; // TODO(geert): implement dlclose().
         if (object->tlsModel != TlsModel::null)
             info.dlpi_tls_modid = object->tlsIndex;
         else
             info.dlpi_tls_modid = 0;
         info.dlpi_tls_data = tryAccessDtv(object);
         last_return = callback(&info, sizeof(struct dl_phdr_info), data);
         if(last_return)
             return last_return;
     }
     return last_return;
 }
References callback(), ElfW(), info, initialRepository, SharedObject::isMainObject, null, rtsCounter, SharedObject::tlsModel, and tryAccessDtv().
Referenced by dl_iterate_phdr().
__rtdl_allocateTcb()
void* __rtdl_allocateTcb ()
Definition at line 135 of file main.cpp.
{
     auto tcb = allocateTcb();
     initTlsObjects(tcb, globalScope->_objects, false);
     return tcb;
 }
References allocateTcb(), globalScope, and initTlsObjects().
Referenced by pthread_create().
_dl_debug_state()
void _dl_debug_state () noexcept
dl_debug_state()
void dl_debug_state ()
Definition at line 142 of file main.cpp.
{
         // This function is used to signal changes in the debugging link map,
         // GDB just sets a breakpoint on this function and we can call it
         // everytime we update the link map. We don't need to implement
         // anything besides defining and calling it.
     }
getLdsoBase()
uintptr_t getLdsoBase ()
Definition at line 57 of file main.cpp.
{
 #if defined(__x86_64__) || defined(__aarch64__)
     // On x86_64, the first GOT entry holds the link-time address of _DYNAMIC.
     // TODO: This isn't guaranteed on AArch64, so this might fail with some linkers.
     auto linktime_dynamic = reinterpret_cast<uintptr_t>(_GLOBAL_OFFSET_TABLE_[0]);
     auto runtime_dynamic = reinterpret_cast<uintptr_t>(_DYNAMIC);
     return runtime_dynamic - linktime_dynamic;
 #elif defined(__riscv)
     return reinterpret_cast<uintptr_t>(&__ehdr_start);
 #endif
 }
References __ehdr_start, _DYNAMIC, and _GLOBAL_OFFSET_TABLE_.
Referenced by interpreterMain(), and relocateSelf().
interpreterMain()
void* interpreterMain (uintptr_t * entry_stack)
Definition at line 155 of file main.cpp.
{
     if(logEntryExit)
         mlibc::infoLogger() << "Entering ld.so" << frg::endlog;
     entryStack = entry_stack;
     runtimeTlsMap.initialize();
     void *phdr_pointer = 0;
     size_t phdr_entry_size = 0;
     size_t phdr_count = 0;
     void *entry_pointer = 0;
     void *stack_entropy = nullptr;
     const char *execfn = "(executable)";
 #ifndef MLIBC_STATIC_BUILD
     using ctor_fn = void(*)(void);
     ctor_fn *ldso_ctors = nullptr;
     size_t num_ldso_ctors = 0;
     auto ldso_base = getLdsoBase();
     if(logStartup) {
         mlibc::infoLogger() << "ldso: Own base address is: 0x"
                 << frg::hex_fmt(ldso_base) << frg::endlog;
         mlibc::infoLogger() << "ldso: Own dynamic section is at: " << _DYNAMIC << frg::endlog;
     }
 #ifdef __x86_64__
     // These entries are reserved on x86_64.
     // TODO: Use a fake PLT stub that reports an error message?
     _GLOBAL_OFFSET_TABLE_[1] = 0;
     _GLOBAL_OFFSET_TABLE_[2] = 0;
 #endif
     // Validate our own dynamic section.
     // Here, we make sure that the dynamic linker does not need relocations itself.
     uintptr_t strtab_offset = 0;
     uintptr_t soname_str = 0;
     for(size_t i = 0; _DYNAMIC[i].d_tag != DT_NULL; i++) {
         auto ent = &_DYNAMIC[i];
         switch(ent->d_tag) {
         case DT_STRTAB: strtab_offset = ent->d_un.d_ptr; break;
         case DT_SONAME: soname_str = ent->d_un.d_val; break;
         case DT_INIT_ARRAY: ldso_ctors = reinterpret_cast<ctor_fn *>(ent->d_un.d_ptr + ldso_base); break;
         case DT_INIT_ARRAYSZ: num_ldso_ctors = ent->d_un.d_val / sizeof(ctor_fn); break;
         case DT_HASH:
         case DT_GNU_HASH:
         case DT_STRSZ:
         case DT_SYMTAB:
         case DT_SYMENT:
         case DT_RELA:
         case DT_RELASZ:
         case DT_RELAENT:
         case DT_RELACOUNT:
         case DT_DEBUG:
             continue;
         default:
             __ensure(!"Unexpected dynamic entry in program interpreter");
         }
     }
     __ensure(strtab_offset);
     __ensure(soname_str);
     // Find the auxiliary vector by skipping args and environment.
     auto aux = entryStack;
     aux += *aux + 1; // First, we skip argc and all args.
     __ensure(!*aux);
     aux++;
     while(*aux) { // Loop through the environment.
         auto env = reinterpret_cast<char *>(*aux);
         frg::string_view view{env};
         size_t s = view.find_first('=');
         if(s == size_t(-1))
             mlibc::panicLogger() << "rtdl: environment '" << env << "' is missing a '='" << frg::endlog;
         auto value = const_cast<char *>(view.data() + s + 1);
         if(view.sub_string(0, s) == "LD_SHOW_AUXV" && value && *value && *value != '0') {
             ldShowAuxv = true;
         }
         aux++;
     }
     aux++;
     // Parse the actual vector.
     while(true) {
         auto value = aux + 1;
         if(!(*aux))
             break;
         if(ldShowAuxv) {
             switch(*aux) {
                 case AT_PHDR: mlibc::infoLogger() << "AT_PHDR: 0x" << frg::hex_fmt{*value} << frg::endlog; break;
                 case AT_PHENT: mlibc::infoLogger() << "AT_PHENT: " << *value << frg::endlog; break;
                 case AT_PHNUM: mlibc::infoLogger() << "AT_PHNUM: " << *value << frg::endlog; break;
                 case AT_ENTRY: mlibc::infoLogger() << "AT_ENTRY: 0x" << frg::hex_fmt{*value} << frg::endlog; break;
                 case AT_PAGESZ: mlibc::infoLogger() << "AT_PAGESZ: " << *value << frg::endlog; break;
                 case AT_BASE: mlibc::infoLogger() << "AT_BASE: 0x" << frg::hex_fmt{*value} << frg::endlog; break;
                 case AT_FLAGS: mlibc::infoLogger() << "AT_FLAGS: 0x" << frg::hex_fmt{*value} << frg::endlog; break;
                 case AT_NOTELF: mlibc::infoLogger() << "AT_NOTELF: " << frg::hex_fmt{*value} << frg::endlog; break;
                 case AT_UID: mlibc::infoLogger() << "AT_UID: " << *value << frg::endlog; break;
                 case AT_EUID: mlibc::infoLogger() << "AT_EUID: " << *value << frg::endlog; break;
                 case AT_GID: mlibc::infoLogger() << "AT_GID: " << *value << frg::endlog; break;
                 case AT_EGID: mlibc::infoLogger() << "AT_EGID: " << *value << frg::endlog; break;
 #ifdef AT_PLATFORM
                 case AT_PLATFORM: mlibc::infoLogger() << "AT_PLATFORM: " << reinterpret_cast<const char *>(*value) << frg::endlog; break;
 #endif
 #ifdef AT_HWCAP
                 case AT_HWCAP: mlibc::infoLogger() << "AT_HWCAP: " << frg::hex_fmt{*value} << frg::endlog; break;
 #endif
 #ifdef AT_CLKTCK
                 case AT_CLKTCK: mlibc::infoLogger() << "AT_CLKTCK: " << *value << frg::endlog; break;
 #endif
 #ifdef AT_FPUCW
                 case AT_FPUCW: mlibc::infoLogger() << "AT_FPUCW: " << frg::hex_fmt{*value} << frg::endlog; break;
 #endif
 #ifdef AT_SECURE
                 case AT_SECURE: mlibc::infoLogger() << "AT_SECURE: " << *value << frg::endlog; break;
 #endif
 #ifdef AT_RANDOM
                 case AT_RANDOM: mlibc::infoLogger() << "AT_RANDOM: 0x" << frg::hex_fmt{*value} << frg::endlog; break;
 #endif
 #ifdef AT_EXECFN
                 case AT_EXECFN: mlibc::infoLogger() << "AT_EXECFN: " << reinterpret_cast<const char *>(*value) << frg::endlog; break;
 #endif
 #ifdef AT_SYSINFO_EHDR
                 case AT_SYSINFO_EHDR: mlibc::infoLogger() << "AT_SYSINFO_EHDR: 0x" << frg::hex_fmt{*value} << frg::endlog; break;
 #endif
             }
         }
         // TODO: Whitelist auxiliary vector entries here?
         switch(*aux) {
             case AT_PHDR: phdr_pointer = reinterpret_cast<void *>(*value); break;
             case AT_PHENT: phdr_entry_size = *value; break;
             case AT_PHNUM: phdr_count = *value; break;
             case AT_ENTRY: entry_pointer = reinterpret_cast<void *>(*value); break;
             case AT_EXECFN: execfn = reinterpret_cast<const char *>(*value); break;
             case AT_RANDOM: stack_entropy = reinterpret_cast<void*>(*value); break;
             case AT_SECURE: rtdlConfig.secureRequired = reinterpret_cast<uintptr_t>(*value); break;
         }
         aux += 2;
     }
     globalDebugInterface.base = reinterpret_cast<void*>(ldso_base);
 // This is here because libgcc will add a global constructor on glibc Linux
 // (which is what it believes we are due to the aarch64-linux-gnu toolchain)
 // in order to check if LSE atomics are supported.
 //
 // This is not necessary on a custom Linux toolchain and is purely an artifact of
 // using the host toolchain.
 #if defined(__aarch64__) && defined(__gnu_linux__)
     for (size_t i = 0; i < num_ldso_ctors; i++) {
         if(logStartup)
             mlibc::infoLogger() << "ldso: Running own constructor at "
                     << reinterpret_cast<void *>(ldso_ctors[i])
                     << frg::endlog;
         ldso_ctors[i]();
     }
 #else
     if (num_ldso_ctors > 0) {
         mlibc::panicLogger() << "ldso: Found unexpected own global constructor(s), init_array starts at: "
                 << ldso_ctors
                 << frg::endlog;
     }
 #endif
 #else
     auto ehdr = reinterpret_cast<Elf64_Ehdr*>(__ehdr_start);
     phdr_pointer = reinterpret_cast<void*>((uintptr_t)ehdr->e_phoff + (uintptr_t)ehdr);
     phdr_entry_size = ehdr->e_phentsize;
     phdr_count = ehdr->e_phnum;
     entry_pointer = reinterpret_cast<void*>(ehdr->e_entry);
 #endif
     __ensure(phdr_pointer);
     __ensure(entry_pointer);
     if(logStartup)
         mlibc::infoLogger() << "ldso: Executable PHDRs are at " << phdr_pointer
                 << frg::endlog;
     // perform the initial dynamic linking
     initialRepository.initialize();
     globalScope.initialize(true);
     // Add the dynamic linker, as well as the exectuable to the repository.
 #ifndef MLIBC_STATIC_BUILD
     auto ldso_soname = reinterpret_cast<const char *>(ldso_base + strtab_offset + soname_str);
     auto ldso = initialRepository->injectObjectFromDts(ldso_soname,
         frg::string<MemoryAllocator> { getAllocator() },
         ldso_base, _DYNAMIC, 1);
     ldso->phdrPointer = phdr_pointer;
     ldso->phdrCount = phdr_count;
     ldso->phdrEntrySize = phdr_entry_size;
     // TODO: support non-zero base addresses?
     executableSO = initialRepository->injectObjectFromPhdrs(execfn,
         frg::string<MemoryAllocator> { execfn, getAllocator() },
         phdr_pointer, phdr_entry_size, phdr_count, entry_pointer, 1);
     // We can't initialise the ldso object after the executable SO,
     // so we have to set the ldso path after loading both.
     ldso->path = executableSO->interpreterPath;
 #else
     executableSO = initialRepository->injectStaticObject(execfn,
             frg::string<MemoryAllocator>{ execfn, getAllocator() },
             phdr_pointer, phdr_entry_size, phdr_count, entry_pointer, 1);
     globalDebugInterface.base = (void*)executableSO->baseAddress;
 #endif
     globalDebugInterface.head = &executableSO->linkMap;
     executableSO->inLinkMap = true;
     Loader linker{globalScope.get(), executableSO, true, 1};
     linker.linkObjects(executableSO);
     mlibc::initStackGuard(stack_entropy);
     auto tcb = allocateTcb();
     if(mlibc::sys_tcb_set(tcb))
         __ensure(!"sys_tcb_set() failed");
     tcb->tid = mlibc::this_tid();
     mlibc::tcb_available_flag = true;
     globalDebugInterface.ver = 1;
     globalDebugInterface.brk = &dl_debug_state;
     globalDebugInterface.state = 0;
     dl_debug_state();
     linker.initObjects();
     if(logEntryExit)
         mlibc::infoLogger() << "Leaving ld.so, jump to "
                 << (void *)executableSO->entry << frg::endlog;
     return executableSO->entry;
 }
References __ehdr_start, __ensure, _DYNAMIC, _GLOBAL_OFFSET_TABLE_, AT_BASE, AT_CLKTCK, AT_EGID, AT_ENTRY, AT_EUID, AT_EXECFN, AT_FLAGS, AT_FPUCW, AT_GID, AT_HWCAP, AT_NOTELF, AT_PAGESZ, AT_PHDR, AT_PHENT, AT_PHNUM, AT_PLATFORM, AT_RANDOM, AT_SECURE, AT_SYSINFO_EHDR, AT_UID, DebugInterface::base, SharedObject::baseAddress, Elf64_Dyn::d_tag, DT_DEBUG, DT_GNU_HASH, DT_HASH, DT_INIT_ARRAY, DT_INIT_ARRAYSZ, DT_NULL, DT_RELA, DT_RELACOUNT, DT_RELAENT, DT_RELASZ, DT_SONAME, DT_STRSZ, DT_STRTAB, DT_SYMENT, DT_SYMTAB, Elf64_Ehdr::e_phentsize, entryStack, env, executableSO, getAllocator(), getLdsoBase(), globalDebugInterface, globalScope, DebugInterface::head, i, mlibc::infoLogger, initialRepository, SharedObject::inLinkMap, SharedObject::interpreterPath, ldShowAuxv, SharedObject::linkMap, logEntryExit, logStartup, mlibc::panicLogger, rtdlConfig, runtimeTlsMap, mlibc::RtdlConfig::secureRequired, value, and Driver::void().
Referenced by __dlapi_enter().
lazyRelocate()
void* lazyRelocate (SharedObject * object, unsigned int rel_index)
Definition at line 112 of file main.cpp.
{
     __ensure(object->lazyExplicitAddend);
     auto reloc = (Elf64_Rela *)(object->baseAddress + object->lazyRelocTableOffset
             + rel_index * sizeof(Elf64_Rela));
     Elf64_Xword type = ELF64_R_TYPE(reloc->r_info);
     Elf64_Xword symbol_index = ELF64_R_SYM(reloc->r_info);
     __ensure(type == R_X86_64_JUMP_SLOT);
     auto symbol = (Elf64_Sym *)(object->baseAddress + object->symbolTableOffset
             + symbol_index * sizeof(Elf64_Sym));
     ObjectSymbol r(object, symbol);
     auto p = Scope::resolveGlobalOrLocal(*globalScope, object->localScope, r.getString(), object->objectRts, 0);
     if(!p)
         mlibc::panicLogger() << "Unresolved JUMP_SLOT symbol" << frg::endlog;
     //mlibc::infoLogger() << "Lazy relocation to " << symbol_str
     //      << " resolved to " << pointer << frg::endlog;
     *(uint64_t *)(object->baseAddress + reloc->r_offset) = p->virtualAddress();
     return (void *)p->virtualAddress();
 }
References __ensure, SharedObject::baseAddress, ELF64_R_SYM(), ELF64_R_TYPE(), globalScope, SharedObject::lazyExplicitAddend, SharedObject::lazyRelocTableOffset, SharedObject::localScope, SharedObject::objectRts, p, mlibc::panicLogger, r, R_X86_64_JUMP_SLOT, Scope::resolveGlobalOrLocal(), SharedObject::symbolTableOffset, and type.
relocateSelf()
void relocateSelf ()
Definition at line 74 of file main.cpp.
{
     size_t rela_offset = 0;
     size_t rela_size = 0;
     for(size_t i = 0; _DYNAMIC[i].d_tag != DT_NULL; i++) {
         auto ent = &_DYNAMIC[i];
         switch(ent->d_tag) {
         case DT_RELA: rela_offset = ent->d_un.d_ptr; break;
         case DT_RELASZ: rela_size = ent->d_un.d_val; break;
         }
     }
     auto ldso_base = getLdsoBase();
     for(size_t disp = 0; disp < rela_size; disp += sizeof(Elf64_Rela)) {
         auto reloc = reinterpret_cast<Elf64_Rela *>(ldso_base + rela_offset + disp);
         Elf64_Xword type = ELF64_R_TYPE(reloc->r_info);
         if(ELF64_R_SYM(reloc->r_info))
             __builtin_trap();
         auto p = reinterpret_cast<uint64_t *>(ldso_base + reloc->r_offset);
         switch(type) {
 #if defined(__x86_64__)
         case R_X86_64_RELATIVE:
 #elif defined(__aarch64__)
         case R_AARCH64_RELATIVE:
 #elif defined(__riscv)
         case R_RISCV_RELATIVE:
 #endif
             *p = ldso_base + reloc->r_addend;
             break;
         default:
             __builtin_trap();
         }
     }
 }
References _DYNAMIC, Elf64_Dyn::d_tag, DT_NULL, DT_RELA, DT_RELASZ, ELF64_R_SYM(), ELF64_R_TYPE(), getLdsoBase(), i, p, R_AARCH64_RELATIVE, R_RISCV_RELATIVE, R_X86_64_RELATIVE, and type.
Variable Documentation
__ehdr_start
HIDDEN char __ehdr_start[] extern
Referenced by getLdsoBase(), and interpreterMain().
_dl_debug_addr
DebugInterface* _dl_debug_addr = &globalDebugInterface
Definition at line 153 of file main.cpp.
_DYNAMIC
HIDDEN Elf64_Dyn _DYNAMIC[] extern
Referenced by getLdsoBase(), interpreterMain(), and relocateSelf().
_GLOBAL_OFFSET_TABLE_
HIDDEN void* _GLOBAL_OFFSET_TABLE_[] extern
Referenced by getLdsoBase(), and interpreterMain().
entryStack
uintptr_t* entryStack
Definition at line 42 of file main.cpp.
Referenced by __dlapi_entrystack(), and interpreterMain().
executableSO
SharedObject* executableSO static
Definition at line 48 of file main.cpp.
Referenced by interpreterMain().
globalDebugInterface
DebugInterface globalDebugInterface
Definition at line 52 of file main.cpp.
Referenced by ObjectRepository::_parseDynamic(), interpreterMain(), and Loader::linkObjects().
globalScope
frg::manual_box<Scope> globalScope
Definition at line 44 of file main.cpp.
Referenced by __rtdl_allocateTcb(), Loader::_processLazyRelocations(), Loader::_processRela(), ObjectRepository::injectObjectFromDts(), ObjectRepository::injectObjectFromPhdrs(), ObjectRepository::injectStaticObject(), interpreterMain(), lazyRelocate(), processCopyRela(), Scope::resolveGlobalOrLocal(), and Scope::resolveGlobalOrLocalNext().
initialRepository
frg::manual_box<ObjectRepository> initialRepository
Definition at line 43 of file main.cpp.
Referenced by __dlapi_iterate_phdr(), and interpreterMain().
lastError
const char* lastError
Definition at line 396 of file main.cpp.
Referenced by __dlapi_error().
ldShowAuxv
bool ldShowAuxv = false
Definition at line 40 of file main.cpp.
Referenced by interpreterMain().
logDlCalls
constexpr bool logDlCalls = false static constexpr
Definition at line 26 of file main.cpp.
logEntryExit
constexpr bool logEntryExit = false static constexpr
Definition at line 24 of file main.cpp.
Referenced by interpreterMain().
logStartup
constexpr bool logStartup = false static constexpr
Definition at line 25 of file main.cpp.
Referenced by interpreterMain().
rtdlConfig
mlibc::RtdlConfig rtdlConfig
Definition at line 38 of file main.cpp.
Referenced by __dlapi_get_config(), and interpreterMain().
runtimeTlsMap
frg::manual_box<RuntimeTlsMap> runtimeTlsMap
Definition at line 46 of file main.cpp.
Referenced by Loader::_buildTlsMaps(), accessDtv(), allocateTcb(), and interpreterMain().