Fennix Kernel: Kernel/core/stack_check.cpp File Reference
stack_check.cpp File Reference
#include <types.h>
#include <debug.h>
#include <rand.hpp>
#include "../kernel.h"
Functions
__noreturn void HandleStackSmashing ()
__noreturn void HandleBufferOverflow ()
EXTERNC __no_stack_protector uintptr_t __stack_chk_guard_init (void)
EXTERNC __constructor __no_stack_protector void __guard_setup (void)
EXTERNC __noreturn __no_stack_protector void __stack_chk_fail (void)
EXTERNC __noreturn nsa void __chk_fail (void)
Variables
uintptr_t __stack_chk_guard = 0
Function Documentation
__chk_fail()
EXTERNC __noreturn nsa void __chk_fail (void)
Definition at line 79 of file stack_check.cpp.
 {
     CPU::PageTable(KernelPageTable);
     HandleBufferOverflow();
 }
References HandleBufferOverflow(), KernelPageTable, and CPU::PageTable().
Referenced by __memcpy_chk(), __memmove_chk(), __memset_chk(), __strcat_chk(), and __strcpy_chk().
__guard_setup()
EXTERNC __constructor __no_stack_protector void __guard_setup (void)
Definition at line 50 of file stack_check.cpp.
 {
     debug("__guard_setup");
     if (__stack_chk_guard == 0)
         __stack_chk_guard = __stack_chk_guard_init();
     debug("Stack guard value: %ld", __stack_chk_guard);
 }
References __stack_chk_guard, __stack_chk_guard_init(), and debug.
__stack_chk_fail()
EXTERNC __noreturn __no_stack_protector void __stack_chk_fail (void)
Definition at line 58 of file stack_check.cpp.
 {
     CPU::PageTable(KernelPageTable);
     void *Stack = nullptr;
 #if defined(a64)
     asmv("movq %%rsp, %0"
          : "=r"(Stack));
 #elif defined(a32)
     asmv("movl %%esp, %0"
          : "=r"(Stack));
 #elif defined(aa64)
     asmv("mov %%sp, %0"
          : "=r"(Stack));
 #endif
     error("Stack address: %#lx", Stack);
     HandleStackSmashing();
 }
References asmv(), error, HandleStackSmashing(), KernelPageTable, CPU::PageTable(), and Stack.
__stack_chk_guard_init()
EXTERNC __no_stack_protector uintptr_t __stack_chk_guard_init (void)
Definition at line 29 of file stack_check.cpp.
 {
     int MaxRetries = 0;
 #if UINTPTR_MAX == UINT32_MAX
     uint32_t num;
 Retry:
     num = Random::rand32();
     if (num < 0x1000 && MaxRetries++ < 10)
         goto Retry;
     return num;
 #else
     uint64_t num;
 Retry:
     num = Random::rand64();
     if (num < 0x100000 && MaxRetries++ < 10)
         goto Retry;
     return num;
 #endif
 }
References Random::rand32(), and Random::rand64().
Referenced by __guard_setup().
HandleBufferOverflow()
__noreturn void HandleBufferOverflow ()
Definition at line 391 of file handler.cpp.
 {
     BaseBufferStackError(false);
     DisplayBufferOverflow();
     CPU::Stop();
 }
References BaseBufferStackError(), DisplayBufferOverflow(), and CPU::Stop().
Referenced by __chk_fail().
HandleStackSmashing()
__noreturn void HandleStackSmashing ()
Definition at line 384 of file handler.cpp.
 {
     BaseBufferStackError(true);
     DisplayStackSmashing();
     CPU::Stop();
 }
References BaseBufferStackError(), DisplayStackSmashing(), and CPU::Stop().
Referenced by __stack_chk_fail().
Variable Documentation
__stack_chk_guard
uintptr_t __stack_chk_guard = 0
Definition at line 27 of file stack_check.cpp.
Referenced by __guard_setup().