Fennix Userspace: Userspace/apps/base/busybox/util-linux/fstrim.c File Reference
fstrim.c File Reference
#include "libbb.h"
#include <linux/fs.h>
Data Structures
struct fstrim_range
Macros
#define FITRIM _IOWR('X', 121, struct fstrim_range)
Functions
int fstrim_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
fstrim_range
struct fstrim_range
Definition at line 32 of file fstrim.c.
Data Fields
uint64_t len
uint64_t minlen
uint64_t start
Macro Definition Documentation
FITRIM
#define FITRIM _IOWR('X', 121, struct fstrim_range)
Definition at line 37 of file fstrim.c.
Function Documentation
fstrim_main()
int fstrim_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 41 of file fstrim.c.
 {
     struct fstrim_range range;
     char *arg_o, *arg_l, *arg_m, *mp;
     unsigned opts;
     int fd;
     enum {
         OPT_o = (1 << 0),
         OPT_l = (1 << 1),
         OPT_m = (1 << 2),
         OPT_v = (1 << 3),
     };
 #if ENABLE_LONG_OPTS
     static const char fstrim_longopts[] ALIGN1 =
         "offset\0"    Required_argument    "o"
         "length\0"    Required_argument    "l"
         "minimum\0"   Required_argument    "m"
         "verbose\0"   No_argument          "v"
         ;
 #endif
     opts = getopt32long(argv, "^"
             "o:l:m:v"
             "\0" "=1", fstrim_longopts,
             &arg_o, &arg_l, &arg_m
     );
     memset(&range, 0, sizeof(range));
     range.len = ULLONG_MAX;
     if (opts & OPT_o)
         range.start = xatoull_sfx(arg_o, kmg_i_suffixes);
     if (opts & OPT_l)
         range.len = xatoull_sfx(arg_l, kmg_i_suffixes);
     if (opts & OPT_m)
         range.minlen = xatoull_sfx(arg_m, kmg_i_suffixes);
     mp = argv[optind];
 //Wwhy bother checking that it's a blockdev?
 //  if (find_block_device(mp)) {
         fd = xopen_nonblocking(mp);
         /* On ENOTTY error, util-linux 2.31 says:
          * "fstrim: FILE: the discard operation is not supported"
          */
         xioctl(fd, FITRIM, &range);
         if (ENABLE_FEATURE_CLEAN_UP)
             close(fd);
         if (opts & OPT_v)
             printf("%s: %llu bytes trimmed\n", mp, (unsigned long long)range.len);
         return EXIT_SUCCESS;
 //  }
     return EXIT_FAILURE;
 }
References ALIGN1, argv, close(), EXIT_FAILURE, EXIT_SUCCESS, fd, FITRIM, getopt32long, kmg_i_suffixes, memset(), No_argument, OPT_l, OPT_m, OPT_o, OPT_v, optind, printf(), range, Required_argument, ULLONG_MAX, xioctl, and xopen_nonblocking().