Fennix Kernel: vfs::RefNode Class Reference
vfs::RefNode Class Reference
#include <filesystem.hpp>
Public Member Functions
size_t read (uint8_t *Buffer, size_t Size)
size_t write (uint8_t *Buffer, size_t Size)
off_t seek (off_t Offset, int Whence)
int ioctl (unsigned long Request, void *Argp)
RefNode (Node *node)
~RefNode ()
Data Fields
decltype(FileSize) & Size = FileSize
decltype(n) & node = n
Private Attributes
std::atomic_int64_t FileOffset = 0
off_t FileSize = 0
Node * n
RefNode * SymlinkTo
Friends
class Virtual
class FileDescriptorTable
Detailed Description
Definition at line 244 of file filesystem.hpp.
Constructor & Destructor Documentation
RefNode()
vfs::RefNode::RefNode (Node * node)
Definition at line 121 of file ref_node.cpp.
     {
         this->node = node;
         this->FileSize = node->Size;
         if (this->node->Type == SYMLINK)
         {
             if (!this->node->SymlinkTarget)
             {
                 this->node->SymlinkTarget =
                     node->vFS->GetNodeFromPath(this->node->Symlink);
             }
             if (!this->node->SymlinkTarget)
             {
                 error("Symlink target %s not found!",
                       this->node->Symlink);
                 return;
             }
             /* not standard but useful in kernel-space */
             this->node->Size = this->node->SymlinkTarget->Size;
             this->SymlinkTo = this->node->SymlinkTarget->CreateReference();
         }
         debug("Created reference node for %s [%#lx]",
               this->node->FullPath, (uintptr_t)this);
     }
References vfs::Node::CreateReference(), debug, error, FileSize, vfs::Node::FullPath, node, vfs::Node::Size, vfs::SYMLINK, vfs::Node::Symlink, vfs::Node::SymlinkTarget, SymlinkTo, and vfs::Node::Type.
~RefNode()
vfs::RefNode::~RefNode ()
Definition at line 149 of file ref_node.cpp.
     {
         if (this->SymlinkTo)
             this->node->SymlinkTarget->RemoveReference(this);
         this->node->RemoveReference(this);
         debug("Destroyed reference node for %s [%#lx]",
               this->node->FullPath, (uintptr_t)this);
     }
References debug, node, and SymlinkTo.
Member Function Documentation
ioctl()
int vfs::RefNode::ioctl (unsigned long Request, void * Argp)
Definition at line 113 of file ref_node.cpp.
     {
         if (this->SymlinkTo)
             return this->SymlinkTo->ioctl(Request, Argp);
         return this->node->ioctl(Request, Argp);
     }
References ioctl(), node, and SymlinkTo.
Referenced by vfs::FileDescriptorTable::_ioctl(), and ioctl().
read()
size_t vfs::RefNode::read (uint8_t * Buffer, size_t Size)
Definition at line 29 of file ref_node.cpp.
     {
         if (this->SymlinkTo)
             return this->SymlinkTo->read(Buffer, Size);
         return this->node->read(Buffer, Size, this->FileOffset.load());
     }
References FileOffset, node, read(), Size, and SymlinkTo.
Referenced by vfs::FileDescriptorTable::_read(), BootLogoAnimationThread(), read(), and sys_execve().
seek()
off_t vfs::RefNode::seek (off_t Offset, int Whence)
Definition at line 45 of file ref_node.cpp.
     {
         if (this->SymlinkTo)
             return this->SymlinkTo->seek(Offset, Whence);
         // debug("Current offset is %d", this->Offset.load());
         switch (Whence)
         {
         case SEEK_SET:
         {
             if (Offset > this->FileSize)
                 return -EINVAL;
             if (Offset < 0)
             {
                 fixme("Negative offset %d is not implemented", Offset);
                 Offset = 0;
             }
             if (Offset > this->FileSize)
             {
                 fixme("Offset %d is bigger than file size %d",
                       Offset, this->FileSize);
                 Offset = this->FileSize;
             }
             this->FileOffset.store(Offset);
             break;
         }
         case SEEK_CUR:
         {
             off_t NewOffset = off_t(this->FileOffset.load()) + Offset;
             if (NewOffset > this->FileSize ||
                 NewOffset < 0)
             {
                 return -EINVAL;
             }
             this->FileOffset.store(NewOffset);
             break;
         }
         case SEEK_END:
         {
             off_t NewOffset = this->FileSize + Offset;
             if (NewOffset > this->FileSize ||
                 NewOffset < 0)
             {
                 return -EINVAL;
             }
             this->FileOffset.store(NewOffset);
             break;
         }
         default:
         {
             error("Invalid whence!");
             return -EINVAL;
         }
         }
         off_t RetOffset = off_t(this->FileOffset.load());
         // debug("( %d %ld %s[%d] ) -> %d",
         //    Offset, this->Offset.load(),
         //    SeekStrings[Whence], Whence,
         //    RetOffset);
         return RetOffset;
     }
References EINVAL, error, FileOffset, FileSize, fixme, seek(), SEEK_CUR, SEEK_END, SEEK_SET, and SymlinkTo.
Referenced by vfs::FileDescriptorTable::_lseek(), seek(), and sys_execve().
write()
size_t vfs::RefNode::write (uint8_t * Buffer, size_t Size)
Definition at line 37 of file ref_node.cpp.
     {
         if (this->SymlinkTo)
             return this->SymlinkTo->write(Buffer, Size);
         return this->node->write(Buffer, Size, this->FileOffset.load());
     }
References FileOffset, node, Size, SymlinkTo, and write().
Referenced by vfs::FileDescriptorTable::_write(), and write().
Friends And Related Function Documentation
FileDescriptorTable
friend class FileDescriptorTable friend
Definition at line 265 of file filesystem.hpp.
Virtual
friend class Virtual friend
Definition at line 264 of file filesystem.hpp.
Field Documentation
FileOffset
std::atomic_int64_t vfs::RefNode::FileOffset = 0 private
Definition at line 247 of file filesystem.hpp.
Referenced by read(), seek(), and write().
FileSize
off_t vfs::RefNode::FileSize = 0 private
Definition at line 248 of file filesystem.hpp.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor(), RefNode(), and seek().
n
Node* vfs::RefNode::n private
Definition at line 249 of file filesystem.hpp.
node
decltype(n) & vfs::RefNode::node = n
Definition at line 254 of file filesystem.hpp.
Referenced by vfs::FileDescriptorTable::_fstat(), vfs::FileDescriptorTable::_lstat(), vfs::FileDescriptorTable::_stat(), vfs::FileDescriptorTable::GetAbsolutePath(), ioctl(), Main(), read(), RefNode(), sys_execve(), write(), and ~RefNode().
Size
decltype(FileSize) & vfs::RefNode::Size = FileSize
Definition at line 253 of file filesystem.hpp.
Referenced by BootLogoAnimationThread(), read(), and write().
SymlinkTo
RefNode* vfs::RefNode::SymlinkTo private
Definition at line 250 of file filesystem.hpp.
Referenced by ioctl(), read(), RefNode(), seek(), write(), and ~RefNode().
The documentation for this class was generated from the following files:
Kernel/include/filesystem.hpp
Kernel/storage/ref_node.cpp