Fennix: mlibc::mem_file Struct Reference
mlibc::mem_file Struct Reference
#include <posix-file-io.hpp>
Public Member Functions
mem_file (char **ptr, size_t *sizeloc, void(*do_dispose)(abstract_file *)=nullptr)
int close () override
Public Member Functions inherited from mlibc::abstract_file
abstract_file (void(*do_dispose)(abstract_file *)=nullptr)
abstract_file (const abstract_file &)=delete
abstract_file & operator= (const abstract_file &)=delete
virtual ~abstract_file ()
void dispose ()
int read (char *buffer, size_t max_size, size_t *actual_size)
int write (const char *buffer, size_t max_size, size_t *actual_size)
int unget (char c)
int update_bufmode (buffer_mode mode)
void purge ()
int flush ()
int tell (off_t *current_offset)
int seek (off_t offset, int whence)
Protected Member Functions
int determine_type (stream_type *type) override
int determine_bufmode (buffer_mode *mode) override
int io_read (char *buffer, size_t max_size, size_t *actual_size) override
int io_write (const char *buffer, size_t max_size, size_t *actual_size) override
int io_seek (off_t offset, int whence, off_t *new_offset) override
Private Member Functions
void _update_ptrs ()
Private Attributes
char ** _bufloc
size_t * _sizeloc
frg::vector< char, MemoryAllocator > _buf
size_t _pos
Additional Inherited Members
Data Fields inherited from mlibc::abstract_file
RecursiveFutexLock _lock
frg::default_list_hook< abstract_file > _list_hook
Data Fields inherited from __mlibc_file_base
char * __buffer_ptr
size_t __buffer_size
size_t __offset
size_t __io_offset
size_t __valid_limit
size_t __dirty_begin
size_t __dirty_end
char * __unget_ptr
int __io_mode
int __status_bits
Detailed Description
Definition at line 10 of file posix-file-io.hpp.
Constructor & Destructor Documentation
mem_file()
mlibc::mem_file::mem_file (char ** ptr, size_t * sizeloc, void(*)(abstract_file *) do_dispose = nullptr)
Definition at line 9 of file posix-file-io.cpp.
 : abstract_file{do_dispose}, _bufloc{ptr}, _sizeloc{sizeloc}, _buf{getAllocator()}, _pos{0} { }
Member Function Documentation
_update_ptrs()
void mlibc::mem_file::_update_ptrs () private
Definition at line 75 of file posix-file-io.cpp.
{
     *_bufloc = _buf.data();
     *_sizeloc = _buf.size() - 1;
 }
References _buf, _bufloc, and _sizeloc.
Referenced by close(), io_seek(), and io_write().
close()
int mlibc::mem_file::close () override virtual
Implements mlibc::abstract_file.
Definition at line 12 of file posix-file-io.cpp.
                     {
     _update_ptrs();
     _buf.detach();
     return 0;
 }
References _buf, and _update_ptrs().
determine_bufmode()
int mlibc::mem_file::determine_bufmode (buffer_mode * mode) override protected virtual
Implements mlibc::abstract_file.
Definition at line 23 of file posix-file-io.cpp.
{
     *mode = buffer_mode::no_buffer;
     return 0;
 }
References mlibc::no_buffer.
determine_type()
int mlibc::mem_file::determine_type (stream_type * type) override protected virtual
Implements mlibc::abstract_file.
Definition at line 18 of file posix-file-io.cpp.
{
     *type = stream_type::file_like;
     return 0;
 }
References mlibc::file_like.
io_read()
int mlibc::mem_file::io_read (char * buffer, size_t max_size, size_t * actual_size) override protected virtual
Implements mlibc::abstract_file.
Definition at line 28 of file posix-file-io.cpp.
{
     return EINVAL;
 }
References EINVAL.
io_seek()
int mlibc::mem_file::io_seek (off_t offset, int whence, off_t * new_offset) override protected virtual
Implements mlibc::abstract_file.
Definition at line 44 of file posix-file-io.cpp.
{
     switch (whence) {
         case SEEK_SET:
             _pos = offset;
             if (_pos >= _buf.size()) {
                 _buf.resize(_pos + 1, '\0');
                 _update_ptrs();
             }
             *new_offset = _pos;
             break;
         case SEEK_CUR:
             _pos += offset;
             if (_pos >= _buf.size()) {
                 _buf.resize(_pos + 1, '\0');
                 _update_ptrs();
             }
             *new_offset = _pos;
             break;
         case SEEK_END:
             _pos = _buf.size() ? _buf.size() - 1 + offset : _buf.size() + offset;
             _buf.resize(_pos + 1, '\0');
             _update_ptrs();
             *new_offset = _pos;
             break;
         default:
             __ensure(!"Unknown whence value passed!");
             __builtin_unreachable();
     }
     return 0;
 }
References __ensure, _buf, _pos, _update_ptrs(), mlibc::new_offset, mlibc::offset, SEEK_CUR, SEEK_END, SEEK_SET, and mlibc::whence.
io_write()
int mlibc::mem_file::io_write (const char * buffer, size_t max_size, size_t * actual_size) override protected virtual
Implements mlibc::abstract_file.
Definition at line 32 of file posix-file-io.cpp.
{
     if (_pos + max_size >= _buf.size()) {
         _buf.resize(_pos + max_size + 1, '\0');
         _update_ptrs();
     }
     memcpy(_buf.data() + _pos, buffer, max_size);
     _pos += max_size;
     *actual_size = max_size;
     return 0;
 }
References _buf, _pos, _update_ptrs(), max_size, and memcpy.
Field Documentation
_buf
frg::vector<char, MemoryAllocator> mlibc::mem_file::_buf private
Definition at line 28 of file posix-file-io.hpp.
Referenced by _update_ptrs(), close(), io_seek(), and io_write().
_bufloc
char** mlibc::mem_file::_bufloc private
Definition at line 24 of file posix-file-io.hpp.
Referenced by _update_ptrs().
_pos
size_t mlibc::mem_file::_pos private
Definition at line 29 of file posix-file-io.hpp.
Referenced by io_seek(), and io_write().
_sizeloc
size_t* mlibc::mem_file::_sizeloc private
Definition at line 25 of file posix-file-io.hpp.
Referenced by _update_ptrs().
The documentation for this struct was generated from the following files:
Userspace/mlibc/options/posix/include/mlibc/posix-file-io.hpp
Userspace/mlibc/options/posix/generic/posix-file-io.cpp