Fennix: Userspace/apps/base/busybox/libbb/crc32.c File Reference
crc32.c File Reference
#include "libbb.h"
Functions
uint32_t *FAST_FUNC crc32_filltable (uint32_t *crc_table, int endian)
uint32_t *FAST_FUNC crc32_new_table_le (void)
uint32_t *FAST_FUNC global_crc32_new_table_le (void)
uint32_t FAST_FUNC crc32_block_endian1 (uint32_t val, const void *buf, unsigned len, uint32_t *crc_table)
uint32_t FAST_FUNC crc32_block_endian0 (uint32_t val, const void *buf, unsigned len, uint32_t *crc_table)
Variables
uint32_t * global_crc32_table
Function Documentation
crc32_block_endian0()
uint32_t FAST_FUNC crc32_block_endian0 (uint32_t val, const void * buf, unsigned len, uint32_t * crc_table)
Definition at line 66 of file crc32.c.
 {
     const void *end = (uint8_t*)buf + len;
     while (buf != end) {
         val = crc_table[(uint8_t)val ^ *(uint8_t*)buf] ^ (val >> 8);
         buf = (uint8_t*)buf + 1;
     }
     return val;
 }
References buf, end, len, and val.
Referenced by calculate_gunzip_crc(), cksum_main(), flash_eraseall_main(), lzo_crc32(), updcrc(), and xz_crc32().
crc32_block_endian1()
uint32_t FAST_FUNC crc32_block_endian1 (uint32_t val, const void * buf, unsigned len, uint32_t * crc_table)
Definition at line 55 of file crc32.c.
 {
     const void *end = (uint8_t*)buf + len;
     while (buf != end) {
         val = (val << 8) ^ crc_table[(val >> 24) ^ *(uint8_t*)buf];
         buf = (uint8_t*)buf + 1;
     }
     return val;
 }
References buf, end, len, and val.
Referenced by cksum_main().
crc32_filltable()
uint32_t* FAST_FUNC crc32_filltable (uint32_t * crc_table, int endian)
Definition at line 22 of file crc32.c.
 {
     uint32_t polynomial = endian ? 0x04c11db7 : 0xedb88320;
     uint32_t c;
     unsigned i, j;
     if (!crc_table)
         crc_table = xmalloc(256 * sizeof(uint32_t));
     for (i = 0; i < 256; i++) {
         c = endian ? (i << 24) : i;
         for (j = 8; j; j--) {
             if (endian)
                 c = (c&0x80000000) ? ((c << 1) ^ polynomial) : (c << 1);
             else
                 c = (c&1) ? ((c >> 1) ^ polynomial) : (c >> 1);
         }
         *crc_table++ = c;
     }
     return crc_table - 256;
 }
References c, i, j, and xmalloc.
Referenced by BZ2_bzCompressInit(), cksum_main(), crc32_new_table_le(), and start_bunzip().
crc32_new_table_le()
uint32_t* FAST_FUNC crc32_new_table_le (void)
Definition at line 45 of file crc32.c.
 {
     return crc32_filltable(NULL, 0);
 }
References crc32_filltable(), and NULL.
Referenced by flash_eraseall_main(), global_crc32_new_table_le(), and IF_DESKTOP().
global_crc32_new_table_le()
uint32_t* FAST_FUNC global_crc32_new_table_le (void)
Definition at line 49 of file crc32.c.
 {
     global_crc32_table = crc32_new_table_le();
     return global_crc32_table;
 }
References crc32_new_table_le(), and global_crc32_table.
Referenced by gzip_main(), IF_DESKTOP(), and lzop_main().
Variable Documentation
global_crc32_table
uint32_t* global_crc32_table
Definition at line 20 of file crc32.c.
Referenced by global_crc32_new_table_le(), IF_DESKTOP(), lzo_crc32(), updcrc(), and xz_crc32().