Fennix Userspace: Userspace/apps/base/busybox/archival/libarchive/init_handle.c File Reference
init_handle.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
archive_handle_t *FAST_FUNC init_handle (void)
Function Documentation
init_handle()
archive_handle_t* FAST_FUNC init_handle (void)
Definition at line 8 of file init_handle.c.
 {
     archive_handle_t *archive_handle;
     /* Initialize default values */
     archive_handle = xzalloc(sizeof(archive_handle_t));
     archive_handle->file_header = xzalloc(sizeof(file_header_t));
     archive_handle->action_header = header_skip;
     archive_handle->action_data = data_skip;
     archive_handle->filter = filter_accept_all;
     archive_handle->seek = seek_by_jump;
 #if ENABLE_CPIO || ENABLE_RPM2CPIO || ENABLE_RPM
     archive_handle->cpio__owner.uid = (uid_t)-1L;
     archive_handle->cpio__owner.gid = (gid_t)-1L;
 #endif
     return archive_handle;
 }
References archive_handle_t::action_data, archive_handle_t::action_header, data_skip(), archive_handle_t::file_header, archive_handle_t::filter, filter_accept_all(), header_skip(), archive_handle_t::seek, seek_by_jump(), and xzalloc().
Referenced by ar_main(), dpkg_deb_main(), init_archive_deb_ar(), init_archive_deb_control(), init_archive_deb_data(), and tar_main().