Fennix Userspace: Userspace/mlibc/options/linux/generic/sys-ptrace-stubs.cpp File Reference
sys-ptrace-stubs.cpp File Reference
#include <sys/ptrace.h>
#include <stdarg.h>
#include <errno.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/linux-sysdeps.hpp>
Functions
long ptrace (int req,...)
Function Documentation
ptrace()
long ptrace (int req, ...)
Definition at line 10 of file sys-ptrace-stubs.cpp.
{
     va_list ap;
     va_start(ap, req);
     auto pid = va_arg(ap, pid_t);
     auto addr = va_arg(ap, void *);
     auto data = va_arg(ap, void *);
     va_end(ap);
     long ret;
     if(req > 0 && req < 4) {
         data = &ret;
     }
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ptrace, -1);
     long out;
     if(int e = mlibc::sys_ptrace(req, pid, addr, data, &out); e) {
         errno = e;
         return -1;
     } else if(req > 0 && req < 4) {
         errno = 0;
         return ret;
     }
     return out;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, ret, mlibc::sys_ptrace(), va_arg, va_end(), and va_start().