Fennix: Userspace/mlibc/options/linux/include/sys/ptrace.h File Reference
ptrace.h File Reference
#include <abi-bits/ptrace.h>
#include <stdint.h>
Data Structures
struct ptrace_peeksiginfo_args
Macros
#define PTRACE_TRACEME 0
#define PT_TRACE_ME PTRACE_TRACEME
#define PT_READ_I PTRACE_PEEKTEXT
#define PT_READ_D PTRACE_PEEKDATA
#define PT_READ_U PTRACE_PEEKUSER
#define PT_WRITE_I PTRACE_POKETEXT
#define PT_WRITE_D PTRACE_POKEDATA
#define PT_WRITE_U PTRACE_POKEUSER
#define PT_CONTINUE PTRACE_CONT
#define PT_KILL PTRACE_KILL
#define PT_STEP PTRACE_SINGLESTEP
#define PT_GETREGS PTRACE_GETREGS
#define PT_SETREGS PTRACE_SETREGS
#define PT_GETFPREGS PTRACE_GETFPREGS
#define PT_SETFPREGS PTRACE_SETFPREGS
#define PT_ATTACH PTRACE_ATTACH
#define PT_DETACH PTRACE_DETACH
#define PT_GETFPXREGS PTRACE_GETFPXREGS
#define PT_SETFPXREGS PTRACE_SETFPXREGS
#define PT_SYSCALL PTRACE_SYSCALL
#define PT_SETOPTIONS PTRACE_SETOPTIONS
#define PT_GETEVENTMSG PTRACE_GETEVENTMSG
#define PT_GETSIGINFO PTRACE_GETSIGINFO
#define PT_SETSIGINFO PTRACE_SETSIGINFO
Functions
long ptrace (int,...)
Data Structure Documentation
ptrace_peeksiginfo_args
struct ptrace_peeksiginfo_args
Definition at line 38 of file ptrace.h.
Data Fields
uint32_t flags
int32_t nr
uint64_t offset
Macro Definition Documentation
PT_ATTACH
#define PT_ATTACH PTRACE_ATTACH
Definition at line 24 of file ptrace.h.
PT_CONTINUE
#define PT_CONTINUE PTRACE_CONT
Definition at line 17 of file ptrace.h.
PT_DETACH
#define PT_DETACH PTRACE_DETACH
Definition at line 25 of file ptrace.h.
PT_GETEVENTMSG
#define PT_GETEVENTMSG PTRACE_GETEVENTMSG
Definition at line 30 of file ptrace.h.
PT_GETFPREGS
#define PT_GETFPREGS PTRACE_GETFPREGS
Definition at line 22 of file ptrace.h.
PT_GETFPXREGS
#define PT_GETFPXREGS PTRACE_GETFPXREGS
Definition at line 26 of file ptrace.h.
PT_GETREGS
#define PT_GETREGS PTRACE_GETREGS
Definition at line 20 of file ptrace.h.
PT_GETSIGINFO
#define PT_GETSIGINFO PTRACE_GETSIGINFO
Definition at line 31 of file ptrace.h.
PT_KILL
#define PT_KILL PTRACE_KILL
Definition at line 18 of file ptrace.h.
PT_READ_D
#define PT_READ_D PTRACE_PEEKDATA
Definition at line 12 of file ptrace.h.
PT_READ_I
#define PT_READ_I PTRACE_PEEKTEXT
Definition at line 11 of file ptrace.h.
PT_READ_U
#define PT_READ_U PTRACE_PEEKUSER
Definition at line 13 of file ptrace.h.
PT_SETFPREGS
#define PT_SETFPREGS PTRACE_SETFPREGS
Definition at line 23 of file ptrace.h.
PT_SETFPXREGS
#define PT_SETFPXREGS PTRACE_SETFPXREGS
Definition at line 27 of file ptrace.h.
PT_SETOPTIONS
#define PT_SETOPTIONS PTRACE_SETOPTIONS
Definition at line 29 of file ptrace.h.
PT_SETREGS
#define PT_SETREGS PTRACE_SETREGS
Definition at line 21 of file ptrace.h.
PT_SETSIGINFO
#define PT_SETSIGINFO PTRACE_SETSIGINFO
Definition at line 32 of file ptrace.h.
PT_STEP
#define PT_STEP PTRACE_SINGLESTEP
Definition at line 19 of file ptrace.h.
PT_SYSCALL
#define PT_SYSCALL PTRACE_SYSCALL
Definition at line 28 of file ptrace.h.
PT_TRACE_ME
#define PT_TRACE_ME PTRACE_TRACEME
Definition at line 9 of file ptrace.h.
PT_WRITE_D
#define PT_WRITE_D PTRACE_POKEDATA
Definition at line 15 of file ptrace.h.
PT_WRITE_I
#define PT_WRITE_I PTRACE_POKETEXT
Definition at line 14 of file ptrace.h.
PT_WRITE_U
#define PT_WRITE_U PTRACE_POKEUSER
Definition at line 16 of file ptrace.h.
PTRACE_TRACEME
#define PTRACE_TRACEME 0
Definition at line 8 of file ptrace.h.
Function Documentation
ptrace()
long ptrace (int req, ...)
Definition at line 10 of file sys-ptrace-stubs.cpp.
{
     va_list ap;
     va_start(ap, req);
     auto pid = va_arg(ap, pid_t);
     auto addr = va_arg(ap, void *);
     auto data = va_arg(ap, void *);
     va_end(ap);
     long ret;
     if(req > 0 && req < 4) {
         data = &ret;
     }
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_ptrace, -1);
     long out;
     if(int e = mlibc::sys_ptrace(req, pid, addr, data, &out); e) {
         errno = e;
         return -1;
     } else if(req > 0 && req < 4) {
         errno = 0;
         return ret;
     }
     return out;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, ret, mlibc::sys_ptrace(), va_arg, va_end(), and va_start().