Fennix: Userspace/mlibc/options/ansi/generic/complex/cpow.c File Reference
cpow.c File Reference
#include <complex.h>
#include <math.h>
Functions
double complex cpow (double complex a, double complex z)
Function Documentation
cpow()
double complex cpow (double complex a, double complex z)
Definition at line 81 of file cpow.c.
 {
     double complex w;
     double x, y, r, theta, absa, arga;
     x = creal(z);
     y = cimag(z);
     absa = cabs(a);
     if (absa == 0.0) {
         return (0.0 + 0.0 * I);
     }
     arga = carg(a);
     r = pow(absa, x);
     theta = x * arga;
     if (y != 0.0) {
         r = r * exp(-y * arga);
         theta = theta + y * log(absa);
     }
     w = r * cos(theta) + (r * sin(theta)) * I;
     return w;
 }
References cabs(), carg(), cimag(), complex, cos(), creal(), exp(), I(), log(), pow(), r, sin(), x, and y.