Fennix: Userspace/musl/src/locale/dcngettext.c File Reference
dcngettext.c File Reference
#include <libintl.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <ctype.h>
#include "locale_impl.h"
#include "atomic.h"
#include "pleval.h"
#include "lock.h"
#include "fork_impl.h"
Data Structures
struct binding
struct msgcat
Macros
#define malloc __libc_malloc
#define calloc __libc_calloc
#define realloc undef
#define free undef
Functions
static char * gettextdir (const char *domainname, size_t *dirlen)
char * bindtextdomain (const char *domainname, const char *dirname)
static char * dummy_gettextdomain ()
weak_alias (dummy_gettextdomain, __gettextdomain)
char * dcngettext (const char *domainname, const char *msgid1, const char *msgid2, unsigned long int n, int category)
char * dcgettext (const char *domainname, const char *msgid, int category)
char * dngettext (const char *domainname, const char *msgid1, const char *msgid2, unsigned long int n)
char * dgettext (const char *domainname, const char *msgid)
Variables
static void *volatile bindings
static volatile int lock [1]
volatile int *const __gettext_lockptr = lock
static const char catnames [][12]
static const char catlens [] = { 8, 10, 7, 10, 11, 11 }
Data Structure Documentation
binding
struct binding
Definition at line 149 of file gettextP.h.
Data Fields
volatile int active
char buf[]
char * codeset
int codeset_cntr
int dirlen
char * dirname
char domainname[ZERO]
char * domainname
struct binding * next
msgcat
struct msgcat
Definition at line 107 of file dcngettext.c.
Data Fields
struct binding * binding
int cat
const struct __locale_map * lm
const void * map
size_t map_size
struct msgcat * next
int nplurals
const char * plural_rule
Macro Definition Documentation
calloc
#define calloc __libc_calloc
Definition at line 16 of file dcngettext.c.
free
#define free undef
Definition at line 18 of file dcngettext.c.
malloc
#define malloc __libc_malloc
Definition at line 15 of file dcngettext.c.
realloc
#define realloc undef
Definition at line 17 of file dcngettext.c.
Function Documentation
bindtextdomain()
char* bindtextdomain (const char * domainname, const char * dirname)
Definition at line 46 of file dcngettext.c.
 {
     struct binding *p, *q;
     if (!domainname) return 0;
     if (!dirname) return gettextdir(domainname, &(size_t){0});
     size_t domlen = strnlen(domainname, NAME_MAX+1);
     size_t dirlen = strnlen(dirname, PATH_MAX);
     if (domlen > NAME_MAX || dirlen >= PATH_MAX) {
         errno = EINVAL;
         return 0;
     }
     LOCK(lock);
     for (p=bindings; p; p=p->next) {
         if (!strcmp(p->domainname, domainname) &&
             !strcmp(p->dirname, dirname)) {
             break;
         }
     }
     if (!p) {
         p = calloc(sizeof *p + domlen + dirlen + 2, 1);
         if (!p) {
             UNLOCK(lock);
             return 0;
         }
         p->next = bindings;
         p->dirlen = dirlen;
         p->domainname = p->buf;
         p->dirname = p->buf + domlen + 1;
         memcpy(p->domainname, domainname, domlen+1);
         memcpy(p->dirname, dirname, dirlen+1);
         a_cas_p(&bindings, bindings, p);
     }
     a_store(&p->active, 1);
     for (q=bindings; q; q=q->next) {
         if (!strcmp(q->domainname, domainname) && q != p)
             a_store(&q->active, 0);
     }
     UNLOCK(lock);
     return (char *)p->dirname;
 }
References a_cas_p, a_store, binding::active, bindings, calloc, binding::dirlen, dirname, domainname, binding::domainname, EINVAL, errno, gettextdir(), LOCK, lock, memcpy, NAME_MAX, binding::next, p, PATH_MAX, strcmp, strnlen(), and UNLOCK.
dcgettext()
char* dcgettext (const char * domainname, const char * msgid, int category)
Definition at line 270 of file dcngettext.c.
 {
     return dcngettext(domainname, msgid, 0, 1, category);
 }
References category, dcngettext(), domainname, and msgid.
dcngettext()
char* dcngettext (const char * domainname, const char * msgid1, const char * msgid2, unsigned long int n, int category)
Definition at line 125 of file dcngettext.c.
 {
     static struct msgcat *volatile cats;
     struct msgcat *p;
     struct __locale_struct *loc = CURRENT_LOCALE;
     const struct __locale_map *lm;
     size_t domlen;
     struct binding *q;
     int old_errno = errno;
     /* match gnu gettext behaviour */
     if (!msgid1) goto notrans;
     if ((unsigned)category >= LC_ALL) goto notrans;
     if (!domainname) domainname = __gettextdomain();
     domlen = strnlen(domainname, NAME_MAX+1);
     if (domlen > NAME_MAX) goto notrans;
     for (q=bindings; q; q=q->next)
         if (!strcmp(q->domainname, domainname) && q->active)
             break;
     if (!q) goto notrans;
     lm = loc->cat[category];
     if (!lm) {
 notrans:
         errno = old_errno;
         return (char *) ((n == 1) ? msgid1 : msgid2);
     }
     for (p=cats; p; p=p->next)
         if (p->binding == q && p->lm == lm && p->cat == category)
             break;
     if (!p) {
         const char *dirname, *locname, *catname, *modname, *locp;
         size_t dirlen, loclen, catlen, modlen, alt_modlen;
         void *old_cats;
         size_t map_size;
         dirname = q->dirname;
         locname = lm->name;
         catname = catnames[category];
         dirlen = q->dirlen;
         loclen = strlen(locname);
         catlen = catlens[category];
         /* Logically split @mod suffix from locale name. */
         modname = memchr(locname, '@', loclen);
         if (!modname) modname = locname + loclen;
         alt_modlen = modlen = loclen - (modname-locname);
         loclen = modname-locname;
         /* Drop .charset identifier; it is not used. */
         const char *csp = memchr(locname, '.', loclen);
         if (csp) loclen = csp-locname;
         char name[dirlen+1 + loclen+modlen+1 + catlen+1 + domlen+3 + 1];
         const void *map;
         for (;;) {
             snprintf(name, sizeof name, "%s/%.*s%.*s/%s/%s.mo\0",
                 dirname, (int)loclen, locname,
                 (int)alt_modlen, modname, catname, domainname);
             if (map = __map_file(name, &map_size)) break;
             /* Try dropping @mod, _YY, then both. */
             if (alt_modlen) {
                 alt_modlen = 0;
             } else if ((locp = memchr(locname, '_', loclen))) {
                 loclen = locp-locname;
                 alt_modlen = modlen;
             } else {
                 break;
             }
         }
         if (!map) goto notrans;
         p = calloc(sizeof *p, 1);
         if (!p) {
             __munmap((void *)map, map_size);
             goto notrans;
         }
         p->cat = category;
         p->binding = q;
         p->lm = lm;
         p->map = map;
         p->map_size = map_size;
         const char *rule = "n!=1;";
         unsigned long np = 2;
         const char *r = __mo_lookup(p->map, p->map_size, "");
         char *z;
         while (r && strncmp(r, "Plural-Forms:", 13)) {
             z = strchr(r, '\n');
             r = z ? z+1 : 0;
         }
         if (r) {
             r += 13;
             while (isspace(*r)) r++;
             if (!strncmp(r, "nplurals=", 9)) {
                 np = strtoul(r+9, &z, 10);
                 r = z;
             }
             while (*r && *r != ';') r++;
             if (*r) {
                 r++;
                 while (isspace(*r)) r++;
                 if (!strncmp(r, "plural=", 7))
                     rule = r+7;
             }
         }
         p->nplurals = np;
         p->plural_rule = rule;
         do {
             old_cats = cats;
             p->next = old_cats;
         } while (a_cas_p(&cats, old_cats, p) != old_cats);
     }
     const char *trans = __mo_lookup(p->map, p->map_size, msgid1);
     if (!trans) goto notrans;
     /* Non-plural-processing gettext forms pass a null pointer as
      * msgid2 to request that dcngettext suppress plural processing. */
     if (msgid2 && p->nplurals) {
         unsigned long plural = __pleval(p->plural_rule, n);
         if (plural > p->nplurals) goto notrans;
         while (plural--) {
             size_t rem = p->map_size - (trans - (char *)p->map);
             size_t l = strnlen(trans, rem);
             if (l+1 >= rem)
                 goto notrans;
             trans += l+1;
         }
     }
     errno = old_errno;
     return (char *)trans;
 }
References __gettextdomain(), __map_file(), __mo_lookup(), __munmap(), __pleval(), a_cas_p, binding::active, bindings, calloc, __locale_struct::cat, category, catlens, catnames, CURRENT_LOCALE, binding::dirlen, dirname, binding::dirname, domainname, binding::domainname, errno, isspace, l, LC_ALL, map, map_size, memchr(), msgid1, msgid2, n, __locale_map::name, NAME_MAX, binding::next, p, plural, snprintf(), strchr(), strcmp, strlen, strncmp(), strnlen(), strtoul(), and trans.
Referenced by dcgettext(), dgettext(), and dngettext().
dgettext()
char* dgettext (const char * domainname, const char * msgid)
Definition at line 280 of file dcngettext.c.
 {
     return dcngettext(domainname, msgid, 0, 1, LC_MESSAGES);
 }
References dcngettext(), domainname, LC_MESSAGES, and msgid.
dngettext()
char* dngettext (const char * domainname, const char * msgid1, const char * msgid2, unsigned long int n)
Definition at line 275 of file dcngettext.c.
 {
     return dcngettext(domainname, msgid1, msgid2, n, LC_MESSAGES);
 }
References dcngettext(), domainname, LC_MESSAGES, msgid1, msgid2, and n.
dummy_gettextdomain()
static char* dummy_gettextdomain () static
Definition at line 118 of file dcngettext.c.
 {
     return "messages";
 }
gettextdir()
static char* gettextdir (const char * domainname, size_t * dirlen) static
Definition at line 31 of file dcngettext.c.
 {
     struct binding *p;
     for (p=bindings; p; p=p->next) {
         if (!strcmp(p->domainname, domainname) && p->active) {
             *dirlen = p->dirlen;
             return (char *)p->dirname;
         }
     }
     return 0;
 }
References bindings, binding::dirlen, domainname, p, and strcmp.
Referenced by bindtextdomain().
weak_alias()
weak_alias (dummy_gettextdomain , __gettextdomain)
Variable Documentation
__gettext_lockptr
volatile int* const __gettext_lockptr = lock
Definition at line 44 of file dcngettext.c.
bindings
void* volatile bindings static
Definition at line 29 of file dcngettext.c.
Referenced by bindtextdomain(), dcngettext(), and gettextdir().
catlens
const char catlens[] = { 8, 10, 7, 10, 11, 11 } static
Definition at line 105 of file dcngettext.c.
Referenced by dcngettext().
catnames
const char catnames[][12] static
Initial value:
= {
    "LC_CTYPE",
    "LC_NUMERIC",
    "LC_TIME",
    "LC_COLLATE",
    "LC_MONETARY",
    "LC_MESSAGES",
}
Definition at line 96 of file dcngettext.c.
Referenced by dcngettext().
lock
volatile int lock[1] static
Definition at line 43 of file dcngettext.c.
Referenced by bindtextdomain().