Fennix Userspace: Userspace/musl/include/sys/uio.h File Reference
uio.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Macros
#define __NEED_size_t
#define __NEED_ssize_t
#define __NEED_struct_iovec
#define UIO_MAXIOV 1024
Functions
ssize_t readv (int, const struct iovec *, int)
ssize_t writev (int, const struct iovec *, int)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file uio.h.
__NEED_ssize_t
#define __NEED_ssize_t
Definition at line 11 of file uio.h.
__NEED_struct_iovec
#define __NEED_struct_iovec
Definition at line 12 of file uio.h.
UIO_MAXIOV
#define UIO_MAXIOV 1024
Definition at line 24 of file uio.h.
Function Documentation
readv()
ssize_t readv (int fd, const struct iovec * iov, int iovcnt)
Definition at line 14 of file sys-uio.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, count, and syscall_cp.
writev()
ssize_t writev (int fd, const struct iovec * iovs, int iovc)
Definition at line 19 of file sys-uio.cpp.
{
     __ensure(iovc);
     ssize_t written = 0;
     size_t bytes = 0;
     for(int i = 0; i < iovc; i++) {
         if(SSIZE_MAX - bytes < iovs[i].iov_len) {
             errno = EINVAL;
             return -1;
         }
         bytes += iovs[i].iov_len;
     }
     frg::vector<char, MemoryAllocator> buffer{getAllocator()};
     buffer.resize(bytes);
     size_t to_copy = bytes;
     char *bp = buffer.data();
     for(int i = 0; i < iovc; i++) {
         size_t copy = frg::min(iovs[i].iov_len, to_copy);
         bp = (char *)mempcpy((void *)bp, (void *)iovs[i].iov_base, copy);
         to_copy -= copy;
         if(to_copy == 0)
             break;
     }
     written = write(fd, buffer.data(), bytes);
     return written;
 }
References __ensure, bp, count, EINVAL, errno, getAllocator(), i, iovec::iov_len, mempcpy(), min(), SSIZE_MAX, syscall_cp, and write().