Fennix: Userspace/apps/base/bash/builtins/common.c File Reference
common.c File Reference
#include <config.h>
#include <stdio.h>
#include <chartypes.h>
#include "../bashtypes.h"
#include "posixstat.h"
#include <signal.h>
#include <errno.h>
#include <varargs.h>
#include "../bashansi.h"
#include "../bashintl.h"
#include "../shell.h"
#include "maxpath.h"
#include "../flags.h"
#include "../parser.h"
#include "../jobs.h"
#include "../builtins.h"
#include "../input.h"
#include "../execute_cmd.h"
#include "../trap.h"
#include "bashgetopt.h"
#include "common.h"
#include "builtext.h"
#include <tilde/tilde.h>
Macros
#define NEED_FPURGE_DECL
Functions
static void builtin_error_prolog ()
void builtin_error (char *format, va_alist) const
void builtin_warning (char *format, va_alist) const
void builtin_usage ()
void no_args (WORD_LIST *list)
int no_options (WORD_LIST *list)
void sh_needarg (char *s)
void sh_neednumarg (char *s)
void sh_notfound (char *s)
void sh_invalidopt (char *s)
void sh_invalidoptname (char *s)
void sh_invalidid (char *s)
void sh_invalidnum (char *s)
void sh_invalidsig (char *s)
void sh_badpid (char *s)
void sh_readonly (char *s) const
void sh_noassign (char *s) const
void sh_erange (char *s, char *desc)
void sh_notbuiltin (char *s)
void sh_wrerror ()
void sh_ttyerror (int set)
int sh_chkwrite (int s)
char ** make_builtin_argv (WORD_LIST *list, int *ip)
void remember_args (WORD_LIST *list, int destructive)
void shift_args (int times)
int number_of_args ()
int dollar_vars_changed ()
void set_dollar_vars_unchanged ()
void set_dollar_vars_changed ()
int get_numeric_arg (WORD_LIST *list, int fatal, intmax_t *count)
int get_exitstat (WORD_LIST *list)
int read_octal (char *string)
char * get_working_directory (char *for_whom)
void set_working_directory (char *name)
int display_signal_list (WORD_LIST *list, int forcecols)
struct builtin * builtin_address_internal (char *name, int disabled_okay)
sh_builtin_func_t * find_shell_builtin (char *name)
sh_builtin_func_t * builtin_address (char *name)
sh_builtin_func_t * find_special_builtin (char *name)
static int shell_builtin_compare (struct builtin *sbp1, struct builtin *sbp2)
void initialize_shell_builtins ()
void builtin_help ()
SHELL_VAR * builtin_bind_variable (char *name, char *value, int flags)
SHELL_VAR * builtin_bind_var_to_int (char *name, intmax_t val, int flags)
int builtin_unbind_variable (char *vname) const
int builtin_arrayref_flags (WORD_DESC *w, int baseflags)
Variables
int errno
const char *const bash_getcwd_errstr
sh_builtin_func_t * last_shell_builtin = (sh_builtin_func_t *)NULL
sh_builtin_func_t * this_shell_builtin = (sh_builtin_func_t *)NULL
static int changed_dollar_vars
char * the_current_working_directory = (char *)NULL
Macro Definition Documentation
NEED_FPURGE_DECL
#define NEED_FPURGE_DECL
Definition at line 47 of file common.c.
Function Documentation
builtin_address()
sh_builtin_func_t* builtin_address (char * name)
Definition at line 927 of file common.c.
 {
   current_builtin = builtin_address_internal (name, 1);
   return (current_builtin ? current_builtin->function : (sh_builtin_func_t *)NULL);
 }
References builtin_address_internal(), current_builtin, builtin::function, builtin::name, and NULL.
Referenced by execute_simple_command().
builtin_address_internal()
struct builtin* builtin_address_internal (char * name, int disabled_okay)
Definition at line 878 of file common.c.
 {
   int hi, lo, mid, j;
   hi = num_shell_builtins - 1;
   lo = 0;
   while (lo <= hi)
     {
       mid = (lo + hi) / 2;
       j = shell_builtins[mid].name[0] - name[0];
       if (j == 0)
     j = strcmp (shell_builtins[mid].name, name);
       if (j == 0)
     {
       /* It must have a function pointer.  It must be enabled, or we
          must have explicitly allowed disabled functions to be found,
          and it must not have been deleted. */
       if (shell_builtins[mid].function &&
           ((shell_builtins[mid].flags & BUILTIN_DELETED) == 0) &&
           ((shell_builtins[mid].flags & BUILTIN_ENABLED) || disabled_okay))
         return (&shell_builtins[mid]);
       else
         return ((struct builtin *)NULL);
     }
       if (j > 0)
     hi = mid - 1;
       else
     lo = mid + 1;
     }
   return ((struct builtin *)NULL);
 }
References BUILTIN_DELETED, BUILTIN_ENABLED, flags, j, builtin::name, NULL, num_shell_builtins, shell_builtins, and strcmp.
Referenced by builtin_address(), find_shell_builtin(), find_special_builtin(), fix_assignment_words(), and read_token_word().
builtin_arrayref_flags()
int builtin_arrayref_flags (WORD_DESC * w, int baseflags)
Definition at line 1084 of file common.c.
 {
   char *t;
   int vflags;
   vflags = baseflags;
   /* Don't require assoc_expand_once if we have an argument that's already
      passed through valid_array_reference and been expanded once. That
      doesn't protect it from normal expansions like word splitting, so
      proper quoting is still required. */
   if (w->flags & W_ARRAYREF)
     vflags |= VA_ONEWORD|VA_NOEXPAND;
 #  if 0
   /* This is a little sketchier but handles quoted arguments. */
   if (assoc_expand_once && (t =  strchr (w->word, '[')) && t[strlen(t) - 1] == ']')
     vflags |= VA_ONEWORD|VA_NOEXPAND;
 #  endif
   return vflags;
 }
References strchr(), strlen(), t, VA_NOEXPAND, VA_ONEWORD, w, and W_ARRAYREF.
builtin_bind_var_to_int()
SHELL_VAR* builtin_bind_var_to_int (char * name, intmax_t val, int flags)
Definition at line 1016 of file common.c.
 {
   SHELL_VAR *v;
   v = bind_var_to_int (name, val, flags|ASS_ALLOWALLSUB);
   return v;
 }
References ASS_ALLOWALLSUB, bind_var_to_int(), flags, builtin::name, and val.
builtin_bind_variable()
SHELL_VAR* builtin_bind_variable (char * name, char * value, int flags)
Definition at line 983 of file common.c.
 {
   SHELL_VAR *v;
   int vflags, bindflags;
 #if defined (ARRAY_VARS)
   /* Callers are responsible for calling this with array references that have
      already undergone valid_array_reference checks (read, printf). */
   vflags = assoc_expand_once ? (VA_NOEXPAND|VA_ONEWORD) : 0;
   bindflags = flags | (assoc_expand_once ? ASS_NOEXPAND : 0) | ASS_ALLOWALLSUB;
   if (flags & ASS_NOEXPAND)
     vflags |= VA_NOEXPAND;
   if (flags & ASS_ONEWORD)
     vflags |= VA_ONEWORD;
   if (valid_array_reference (name, vflags) == 0)
     v = bind_variable (name, value, flags);
   else
     v = assign_array_element (name, value, bindflags, (array_eltstate_t *)0);
 #else /* !ARRAY_VARS */
   v = bind_variable (name, value, flags);
 #endif /* !ARRAY_VARS */
   if (v && readonly_p (v) == 0 && noassign_p (v) == 0)
     VUNSETATTR (v, att_invisible);
   return v;
 }
References ASS_ALLOWALLSUB, ASS_NOEXPAND, ASS_ONEWORD, att_invisible, bind_variable(), flags, builtin::name, noassign_p, readonly_p, VA_NOEXPAND, VA_ONEWORD, value, and VUNSETATTR.
Referenced by accept_bind_variable(), accept_builtin(), and mktemp_builtin().
builtin_error()
void builtin_error (char * format, va_alist) const
Definition at line 106 of file common.c.
 {
   va_list args;
   builtin_error_prolog ();
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   va_end (args);
   fprintf (stderr, "\n");
 }
References args, builtin_error_prolog(), format(), fprintf(), SH_VA_START, stderr, va_end, and vfprintf().
Referenced by _evalfile(), _remove_directory(), accept_bind_variable(), accept_builtin(), asort_builtin(), builtin_unbind_variable(), csv_builtin(), cut_internal(), dir_ok(), dolink(), dsv_builtin(), fdflags_builtin(), file_head(), getconf_one(), getconf_print(), getflags(), getfloatmax(), getlist(), getstat(), head_builtin(), id_prall(), id_prgroups(), inituser(), ln_builtin(), logname_builtin(), long_double_format(), make_local_variable(), make_path(), mkdir_builtin(), mkfifo_builtin(), mktemp_builtin(), no_args(), parseflags(), portable_chars_only(), push_builtin(), realpath_builtin(), rm_file(), rmdir_builtin(), seq_builtin(), setone(), setpgid_builtin(), sh_badpid(), sh_erange(), sh_invalidid(), sh_invalidnum(), sh_invalidopt(), sh_invalidoptname(), sh_invalidsig(), sh_needarg(), sh_neednumarg(), sh_notbuiltin(), sh_notfound(), sh_readonly(), sh_ttyerror(), sh_wrerror(), sleep_builtin(), sort_index(), sort_inplace(), stat_builtin(), tee_builtin(), uname_builtin(), unlink_builtin(), and validate_path().
builtin_error_prolog()
static void builtin_error_prolog () static
Definition at line 88 of file common.c.
 {
   char *name;
   name = get_name_for_error ();
   fprintf (stderr, "%s: ", name);
   if (interactive_shell == 0)
     fprintf (stderr, _("line %d: "), executing_line_number ());
   if (this_command_name && *this_command_name)
     fprintf (stderr, "%s: ", this_command_name);
 }
References _, executing_line_number(), fprintf(), get_name_for_error(), interactive_shell, stderr, and this_command_name.
Referenced by builtin_error(), and builtin_warning().
builtin_help()
void builtin_help ()
Definition at line 969 of file common.c.
 {
   printf ("%s: %s\n", this_command_name, _("help not available in this version"));
 }
References _, printf, and this_command_name.
Referenced by getconf_builtin(), and no_options().
builtin_unbind_variable()
int builtin_unbind_variable (char * vname) const
Definition at line 1064 of file common.c.
 {
   SHELL_VAR *v;
   v = find_variable (vname);
   if (v && readonly_p (v))
     {
       builtin_error (_("%s: cannot unset: readonly %s"), vname, "variable");
       return -2;
     }
   else if (v && non_unsettable_p (v))
     {
       builtin_error (_("%s: cannot unset"), vname);
       return -2;
     }
   return (unbind_variable (vname));
 }
References _, builtin_error(), find_variable(), non_unsettable_p, readonly_p, and unbind_variable().
Referenced by realpath_builtin().
builtin_usage()
void builtin_usage ()
Definition at line 145 of file common.c.
 {
   if (this_command_name && *this_command_name)
     fprintf (stderr, _("%s: usage: "), this_command_name);
   fprintf (stderr, "%s\n", _(current_builtin->short_doc));
   fflush (stderr);
 }
References _, current_builtin, fflush(), fprintf(), builtin::short_doc, stderr, and this_command_name.
Referenced by accept_builtin(), asort_builtin(), basename_builtin(), csv_builtin(), cut_internal(), dirname_builtin(), dsv_builtin(), fdflags_builtin(), finfo_main(), getconf_builtin(), getconf_one(), head_builtin(), id_builtin(), ln_builtin(), mkdir_builtin(), mkfifo_builtin(), mktemp_builtin(), no_options(), pathchk_builtin(), print_builtin(), printenv_builtin(), push_builtin(), realpath_builtin(), rm_builtin(), seq_builtin(), setpgid_builtin(), sleep_builtin(), stat_builtin(), strftime_builtin(), tee_builtin(), template_builtin(), tty_builtin(), uname_builtin(), unlink_builtin(), and whoami_builtin().
builtin_warning()
void builtin_warning (char * format, va_alist) const
Definition at line 126 of file common.c.
 {
   va_list args;
   builtin_error_prolog ();
   fprintf (stderr, _("warning: "));
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   va_end (args);
   fprintf (stderr, "\n");
 }
References _, args, builtin_error_prolog(), format(), fprintf(), SH_VA_START, stderr, va_end, and vfprintf().
Referenced by seq_builtin(), and wait_for_background_pids().
display_signal_list()
int display_signal_list (WORD_LIST * list, int forcecols)
Definition at line 773 of file common.c.
 {
   register int i, column;
   char *name;
   int result, signum, dflags;
   intmax_t lsignum;
   result = EXECUTION_SUCCESS;
   if (!list)
     {
       for (i = 1, column = 0; i < NSIG; i++)
     {
       name = signal_name (i);
       if (STREQN (name, "SIGJUNK", 7) || STREQN (name, "Unknown", 7))
         continue;
       if (posixly_correct && !forcecols)
         {
           /* This is for the kill builtin.  POSIX.2 says the signal names
          are displayed without the `SIG' prefix. */
           if (STREQN (name, "SIG", 3))
         name += 3;
           printf ("%s%s", name, (i == NSIG - 1) ? "" : " ");
         }
       else
         {
           printf ("%2d) %s", i, name);
           if (++column < 5)
         printf ("\t");
           else
         {
           printf ("\n");
           column = 0;
         }
         }
     }
       if ((posixly_correct && !forcecols) || column != 0)
     printf ("\n");
       return result;
     }
   /* List individual signal names or numbers. */
   while (list)
     {
       if (legal_number (list->word->word, &lsignum))
     {
       /* This is specified by Posix.2 so that exit statuses can be
          mapped into signal numbers. */
       if (lsignum > 128)
         lsignum -= 128;
       if (lsignum < 0 || lsignum >= NSIG)
         {
           sh_invalidsig (list->word->word);
           result = EXECUTION_FAILURE;
           list = list->next;
           continue;
         }
       signum = lsignum;
       name = signal_name (signum);
       if (STREQN (name, "SIGJUNK", 7) || STREQN (name, "Unknown", 7))
         {
           list = list->next;
           continue;
         }
       /* POSIX.2 says that `kill -l signum' prints the signal name without
          the `SIG' prefix. */
       printf ("%s\n", (this_shell_builtin == kill_builtin && signum > 0) ? name + 3 : name);
     }
       else
     {
       dflags = DSIG_NOCASE;
       if (posixly_correct == 0 || this_shell_builtin != kill_builtin)
         dflags |= DSIG_SIGPREFIX;
       signum = decode_signal (list->word->word, dflags);
       if (signum == NO_SIG)
         {
           sh_invalidsig (list->word->word);
           result = EXECUTION_FAILURE;
           list = list->next;
           continue;
         }
       printf ("%d\n", signum);
     }
       list = list->next;
     }
   return (result);
 }
References decode_signal(), DSIG_NOCASE, DSIG_SIGPREFIX, EXECUTION_FAILURE, EXECUTION_SUCCESS, i, legal_number(), list(), node::next, NO_SIG, NSIG, posixly_correct, printf, sh_invalidsig(), signal_name(), STREQN, and this_shell_builtin.
dollar_vars_changed()
int dollar_vars_changed ()
Definition at line 482 of file common.c.
 {
   return (changed_dollar_vars);
 }
References changed_dollar_vars.
find_shell_builtin()
sh_builtin_func_t* find_shell_builtin (char * name)
Definition at line 918 of file common.c.
 {
   current_builtin = builtin_address_internal (name, 0);
   return (current_builtin ? current_builtin->function : (sh_builtin_func_t *)NULL);
 }
References builtin_address_internal(), current_builtin, builtin::function, builtin::name, and NULL.
Referenced by do_assignment_statements(), and execute_simple_command().
find_special_builtin()
sh_builtin_func_t* find_special_builtin (char * name)
Definition at line 937 of file common.c.
 {
   current_builtin = builtin_address_internal (name, 0);
   return ((current_builtin && (current_builtin->flags & SPECIAL_BUILTIN)) ?
             current_builtin->function :
             (sh_builtin_func_t *)NULL);
 }
References builtin_address_internal(), current_builtin, builtin::flags, builtin::function, builtin::name, NULL, and SPECIAL_BUILTIN.
Referenced by do_assignment_statements(), execute_intern_function(), and execute_simple_command().
get_exitstat()
int get_exitstat (WORD_LIST * list)
Definition at line 555 of file common.c.
 {
   int status;
   intmax_t sval;
   char *arg;
   if (list && list->word && ISOPTION (list->word->word, '-'))
     list = list->next;
   if (list == 0)
     {
       /* If we're not running the DEBUG trap, the return builtin, when not
      given any arguments, uses the value of $? before the trap ran.  If
      given an argument, return uses it.  This means that the trap can't
      change $?.  The DEBUG trap gets to change $?, though, since that is
      part of its reason for existing, and because the extended debug mode
      does things with the return value. */
       if (this_shell_builtin == return_builtin && running_trap > 0 && running_trap != DEBUG_TRAP+1)
     return (trap_saved_exit_value);
       return (last_command_exit_value);
     }
   arg = list->word->word;
   if (arg == 0 || legal_number (arg, &sval) == 0)
     {
       sh_neednumarg (list->word->word ? list->word->word : "`'");
       return EX_BADUSAGE;
     }
   no_args (list->next);
   status = sval & 255;
   return status;
 }
References DEBUG_TRAP, EX_BADUSAGE, ISOPTION, last_command_exit_value, legal_number(), list(), node::next, no_args(), running_trap, sh_neednumarg(), status, this_shell_builtin, and trap_saved_exit_value.
get_numeric_arg()
int get_numeric_arg (WORD_LIST * list, int fatal, intmax_t * count)
Definition at line 518 of file common.c.
 {
   char *arg;
   if (count)
     *count = 1;
   if (list && list->word && ISOPTION (list->word->word, '-'))
     list = list->next;
   if (list)
     {
       arg = list->word->word;
       if (arg == 0 || (legal_number (arg, count) == 0))
     {
       sh_neednumarg (list->word->word ? list->word->word : "`'");
       if (fatal == 0)
         return 0;
       else if (fatal == 1)      /* fatal == 1; abort */
         throw_to_top_level ();
       else              /* fatal == 2; discard current command */
         {
           top_level_cleanup ();
           jump_to_top_level (DISCARD);
         }
     }
       no_args (list->next);
     }
   return (1);
 }
References count, DISCARD, ISOPTION, jump_to_top_level(), legal_number(), list(), node::next, no_args(), sh_neednumarg(), throw_to_top_level(), and top_level_cleanup().
get_working_directory()
char* get_working_directory (char * for_whom)
Definition at line 624 of file common.c.
 {
   if (no_symbolic_links)
     {
       FREE (the_current_working_directory);
       the_current_working_directory = (char *)NULL;
     }
   if (the_current_working_directory == 0)
     {
 #if defined (GETCWD_BROKEN)
       the_current_working_directory = getcwd (0, PATH_MAX);
 #else
       the_current_working_directory = getcwd (0, 0);
 #endif
       if (the_current_working_directory == 0)
     {
       fprintf (stderr, _("%s: error retrieving current directory: %s: %s\n"),
            (for_whom && *for_whom) ? for_whom : get_name_for_error (),
            _(bash_getcwd_errstr), strerror (errno));
       return (char *)NULL;
     }
     }
   return (savestring (the_current_working_directory));
 }
References _, bash_getcwd_errstr, errno, fprintf(), FREE, get_name_for_error(), getcwd, no_symbolic_links, NULL, PATH_MAX, savestring(), stderr, strerror(), and the_current_working_directory.
Referenced by job_working_directory(), send_pwd_to_eterm(), set_pwd(), sh_makepath(), and sh_realpath().
initialize_shell_builtins()
void initialize_shell_builtins ()
Definition at line 961 of file common.c.
 {
   qsort (shell_builtins, num_shell_builtins, sizeof (struct builtin),
     (QSFUNC *)shell_builtin_compare);
 }
References num_shell_builtins, qsort(), shell_builtin_compare(), and shell_builtins.
Referenced by shell_initialize().
make_builtin_argv()
char** make_builtin_argv (WORD_LIST * list, int * ip)
Definition at line 370 of file common.c.
 {
   char **argv;
   argv = strvec_from_word_list (list, 0, 1, ip);
   argv[0] = this_command_name;
   return argv;
 }
References argv, list(), strvec_from_word_list(), and this_command_name.
Referenced by bperl_builtin().
no_args()
void no_args (WORD_LIST * list)
Definition at line 156 of file common.c.
 {
   if (list)
     {
       builtin_error (_("too many arguments"));
       top_level_cleanup ();
       jump_to_top_level (DISCARD);
     }
 }
References _, builtin_error(), DISCARD, jump_to_top_level(), list(), and top_level_cleanup().
Referenced by get_exitstat(), and get_numeric_arg().
no_options()
int no_options (WORD_LIST * list)
Definition at line 170 of file common.c.
 {
   int opt;
   reset_internal_getopt ();
   if ((opt = internal_getopt (list, "")) != -1)
     {
       if (opt == GETOPT_HELP)
     {
       builtin_help ();
       return (2);
     }
       builtin_usage ();
       return (1);
     }
   return (0);
 }
References builtin_help(), builtin_usage(), GETOPT_HELP, internal_getopt(), list(), opt, and reset_internal_getopt().
Referenced by basename_builtin(), dirname_builtin(), logname_builtin(), rmdir_builtin(), and strftime_builtin().
number_of_args()
int number_of_args ()
Definition at line 459 of file common.c.
 {
 #if 0
   register WORD_LIST *list;
   int n;
   for (n = 0; n < 9 && dollar_vars[n+1]; n++)
     ;
   for (list = rest_of_args; list; list = list->next)
     n++;
 if (n != posparam_count)
   itrace("number_of_args: n (%d) != posparam_count (%d)", n, posparam_count);
 #else
   return posparam_count;
 #endif
 }
References dollar_vars, list(), n, node::next, posparam_count, and rest_of_args.
Referenced by param_expand(), parameter_brace_expand_length(), unary_test(), and verify_substring_values().
read_octal()
int read_octal (char * string)
Definition at line 593 of file common.c.
 {
   int result, digits;
   result = digits = 0;
   while (*string && ISOCTAL (*string))
     {
       digits++;
       result = (result * 8) + (*string++ - '0');
       if (result > 07777)
     return -1;
     }
   if (digits == 0 || *string)
     result = -1;
   return (result);
 }
References digits, and ISOCTAL.
Referenced by decode_prompt_string(), mkdir_builtin(), and mkfifo_builtin().
remember_args()
void remember_args (WORD_LIST * list, int destructive)
Definition at line 386 of file common.c.
 {
   register int i;
   posparam_count = 0;
   for (i = 1; i < 10; i++)
     {
       if ((destructive || list) && dollar_vars[i])
     {
       free (dollar_vars[i]);
       dollar_vars[i] = (char *)NULL;
     }
       if (list)
     {
       dollar_vars[posparam_count = i] = savestring (list->word->word);
       list = list->next;
     }
     }
   /* If arguments remain, assign them to REST_OF_ARGS.
      Note that copy_word_list (NULL) returns NULL, and
      that dispose_words (NULL) does nothing. */
   if (destructive || list)
     {
       dispose_words (rest_of_args);
       rest_of_args = copy_word_list (list);
       posparam_count += list_length (list);
     }
   if (destructive)
     set_dollar_vars_changed ();
   invalidate_cached_quoted_dollar_at ();
 }
References copy_word_list(), dispose_words(), dollar_vars, free, i, invalidate_cached_quoted_dollar_at(), list(), list_length(), node::next, NULL, posparam_count, rest_of_args, savestring(), and set_dollar_vars_changed().
Referenced by bind_args(), execute_function(), and unbind_args().
set_dollar_vars_changed()
void set_dollar_vars_changed ()
Definition at line 494 of file common.c.
 {
   if (variable_context)
     changed_dollar_vars |= ARGS_FUNC;
   else if (this_shell_builtin == set_builtin)
     changed_dollar_vars |= ARGS_SETBLTIN;
   else
     changed_dollar_vars |= ARGS_INVOC;
 }
References ARGS_FUNC, ARGS_INVOC, ARGS_SETBLTIN, changed_dollar_vars, this_shell_builtin, and variable_context.
Referenced by remember_args().
set_dollar_vars_unchanged()
void set_dollar_vars_unchanged ()
Definition at line 488 of file common.c.
 {
   changed_dollar_vars = 0;
 }
References changed_dollar_vars.
Referenced by pop_dollar_vars().
set_working_directory()
void set_working_directory (char * name)
Definition at line 654 of file common.c.
 {
   FREE (the_current_working_directory);
   the_current_working_directory = savestring (name);
 }
References FREE, savestring(), and the_current_working_directory.
Referenced by set_pwd().
sh_badpid()
void sh_badpid (char * s)
Definition at line 256 of file common.c.
 {
   builtin_error (_("`%s': not a pid or valid job spec"), s);
 }
References _, builtin_error(), and s.
sh_chkwrite()
int sh_chkwrite (int s)
Definition at line 344 of file common.c.
 {
   QUIT;
   fflush (stdout);
   QUIT;
   if (ferror (stdout))
     {
       sh_wrerror ();
       fpurge (stdout);
       clearerr (stdout);
       return (EXECUTION_FAILURE);
     }
   return (s);
 }
References clearerr(), EXECUTION_FAILURE, ferror, fflush(), fpurge(), QUIT, s, sh_wrerror(), and stdout.
Referenced by print_fltseq(), print_intseq(), and seq_builtin().
sh_erange()
void sh_erange (char * s, char * desc)
Definition at line 277 of file common.c.
 {
   if (s)
     builtin_error (_("%s: %s out of range"), s, desc ? desc : _("argument"));
   else
     builtin_error (_("%s out of range"), desc ? desc : _("argument"));
 }
References _, builtin_error(), and s.
sh_invalidid()
void sh_invalidid (char * s)
Definition at line 227 of file common.c.
 {
   builtin_error (_("`%s': not a valid identifier"), s);
 }
References _, builtin_error(), and s.
Referenced by asort_builtin(), assign_in_env(), bind_int_variable(), bind_variable_internal(), csv_builtin(), cut_internal(), dsv_builtin(), execute_for_command(), find_variable_nameref_for_assignment(), find_variable_nameref_for_create(), mktemp_builtin(), realpath_builtin(), and stat_builtin().
sh_invalidnum()
void sh_invalidnum (char * s)
Definition at line 234 of file common.c.
 {
   char *msg;
   if (*s == '0' && isdigit ((unsigned char)s[1]))
     msg = _("invalid octal number");
   else if (*s == '0' && s[1] == 'x')
     msg = _("invalid hex number");
   else
     msg = _("invalid number");
   builtin_error ("%s: %s", s, msg);
 }
References _, builtin_error(), isdigit, and s.
Referenced by getfloatmax(), and strftime_builtin().
sh_invalidopt()
void sh_invalidopt (char * s)
Definition at line 213 of file common.c.
 {
   builtin_error (_("%s: invalid option"), s);
 }
References _, builtin_error(), and s.
Referenced by internal_getopt().
sh_invalidoptname()
void sh_invalidoptname (char * s)
Definition at line 220 of file common.c.
 {
   builtin_error (_("%s: invalid option name"), s);
 }
References _, builtin_error(), and s.
sh_invalidsig()
void sh_invalidsig (char * s)
Definition at line 249 of file common.c.
 {
   builtin_error (_("%s: invalid signal specification"), s);
 }
References _, builtin_error(), and s.
Referenced by display_signal_list().
sh_needarg()
void sh_needarg (char * s)
Definition at line 190 of file common.c.
 {
   builtin_error (_("%s: option requires an argument"), s);
 }
References _, builtin_error(), and s.
Referenced by internal_getopt().
sh_neednumarg()
void sh_neednumarg (char * s)
Definition at line 197 of file common.c.
 {
   builtin_error (_("%s: numeric argument required"), s);
 }
References _, builtin_error(), and s.
Referenced by get_exitstat(), get_numeric_arg(), and internal_getopt().
sh_noassign()
void sh_noassign (char * s) const
Definition at line 270 of file common.c.
 {
   internal_error (_("%s: cannot assign"), s);   /* XXX */
 }
References _, internal_error(), and s.
sh_notbuiltin()
void sh_notbuiltin (char * s)
Definition at line 318 of file common.c.
 {
   builtin_error (_("%s: not a shell builtin"), s);
 }
References _, builtin_error(), and s.
sh_notfound()
void sh_notfound (char * s)
Definition at line 204 of file common.c.
 {
   builtin_error (_("%s: not found"), s);
 }
References _, builtin_error(), and s.
sh_readonly()
void sh_readonly (char * s) const
Definition at line 263 of file common.c.
 {
   builtin_error (_("%s: readonly variable"), s);
 }
References _, builtin_error(), and s.
Referenced by make_local_variable(), and mktemp_builtin().
sh_ttyerror()
void sh_ttyerror (int set)
Definition at line 334 of file common.c.
 {
   if (set)
     builtin_error (_("error setting terminal attributes: %s"), strerror (errno));
   else
     builtin_error (_("error getting terminal attributes: %s"), strerror (errno));
 }
References _, builtin_error(), errno, and strerror().
sh_wrerror()
void sh_wrerror ()
Definition at line 325 of file common.c.
 {
 #if defined (DONT_REPORT_BROKEN_PIPE_WRITE_ERRORS) && defined (EPIPE)
   if (errno != EPIPE)
 #endif /* DONT_REPORT_BROKEN_PIPE_WRITE_ERRORS && EPIPE */
   builtin_error (_("write error: %s"), strerror (errno));
 }
References _, builtin_error(), EPIPE, errno, and strerror().
Referenced by sh_chkwrite().
shell_builtin_compare()
static int shell_builtin_compare (struct builtin * sbp1, struct builtin * sbp2) static
Definition at line 947 of file common.c.
 {
   int result;
   if ((result = sbp1->name[0] - sbp2->name[0]) == 0)
     result = strcmp (sbp1->name, sbp2->name);
   return (result);
 }
References builtin::name, and strcmp.
Referenced by initialize_shell_builtins().
shift_args()
void shift_args (int times)
Definition at line 426 of file common.c.
 {
   WORD_LIST *temp;
   int count;
   if (times <= 0)       /* caller should check */
     return;
   while (times-- > 0)
     {
       if (dollar_vars[1])
     free (dollar_vars[1]);
       for (count = 1; count < 9; count++)
     dollar_vars[count] = dollar_vars[count + 1];
       if (rest_of_args)
     {
       temp = rest_of_args;
       dollar_vars[9] = savestring (temp->word->word);
       rest_of_args = rest_of_args->next;
       temp->next = (WORD_LIST *)NULL;
       dispose_words (temp);
     }
       else
     dollar_vars[9] = (char *)NULL;
       posparam_count--;
     }
 }
References count, dispose_words(), dollar_vars, free, word_list::next, NULL, posparam_count, rest_of_args, savestring(), times(), word_desc::word, and word_list::word.
Variable Documentation
bash_getcwd_errstr
const char* const bash_getcwd_errstr extern
Definition at line 70 of file general.c.
Referenced by get_working_directory().
changed_dollar_vars
int changed_dollar_vars static
Definition at line 477 of file common.c.
Referenced by dollar_vars_changed(), set_dollar_vars_changed(), and set_dollar_vars_unchanged().
errno
int errno extern
Referenced by attach_option(), get_working_directory(), sh_ttyerror(), sh_wrerror(), and udhcp_str2optset().
last_shell_builtin
sh_builtin_func_t* last_shell_builtin = (sh_builtin_func_t *)NULL
Definition at line 74 of file common.c.
Referenced by execute_simple_command(), handle_eof_input_unit(), restore_parser_state(), and save_parser_state().
the_current_working_directory
char* the_current_working_directory = (char *)NULL
Definition at line 621 of file common.c.
Referenced by current_working_directory(), get_working_directory(), and set_working_directory().
this_shell_builtin
sh_builtin_func_t* this_shell_builtin = (sh_builtin_func_t *)NULL
Definition at line 75 of file common.c.
Referenced by display_signal_list(), execute_builtin_or_function(), execute_simple_command(), get_exitstat(), handle_eof_input_unit(), parse_and_execute(), restore_parser_state(), run_sigchld_trap(), save_parser_state(), set_dollar_vars_changed(), termsig_handler(), trap_handler(), wait_for(), wait_sigint_handler(), and waitchld().