Fennix: Userspace/apps/base/busybox/coreutils/stty.c File Reference
stty.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct mode_info
struct control_info
struct globals
Macros
#define _POSIX_VDISABLE ((unsigned char) 0)
#define Control(c) ((c) & 0x1f)
#define CINTR Control('c')
#define CQUIT 28
#define CERASE 127
#define CKILL Control('u')
#define CEOF Control('d')
#define CEOL _POSIX_VDISABLE
#define CSTART Control('q')
#define CSTOP Control('s')
#define CSUSP Control('z')
#define BSDLY 0
#define CIBAUD 0
#define CRDLY 0
#define CMSPAR 0
#define CRTSCTS 0
#define ECHOCTL 0
#define ECHOKE 0
#define ECHOPRT 0
#define FFDLY 0
#define IEXTEN 0
#define IMAXBEL 0
#define IUCLC 0
#define IXANY 0
#define NLDLY 0
#define OCRNL 0
#define OFDEL 0
#define OFILL 0
#define OLCUC 0
#define ONLCR 0
#define ONLRET 0
#define ONOCR 0
#define OXTABS 0
#define TABDLY 0
#define TAB1 0
#define TAB2 0
#define TOSTOP 0
#define VDSUSP 0
#define VEOL2 0
#define VFLUSHO 0
#define VLNEXT 0
#define VREPRINT 0
#define VSTATUS 0
#define VSWTCH 0
#define VTDLY 0
#define VWERASE 0
#define XCASE 0
#define IUTF8 0
#define SANE_SET 1 /* Set in 'sane' mode */
#define SANE_UNSET 2 /* Unset in 'sane' mode */
#define REV 4 /* Can be turned off by prepending '-' */
#define OMIT 8 /* Don't display value */
#define MI_ENTRY(N, T, F, B, M) N "\0"
#define MI_ENTRY(N, T, F, B, M) { T, F, M, B },
#define CI_ENTRY(n, s, o) n "\0"
#define CI_ENTRY(n, s, o) { s, o },
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define STTY_require_set_attr (1 << 0)
#define STTY_speed_was_set (1 << 1)
#define STTY_verbose_output (1 << 2)
#define STTY_recoverable_output (1 << 3)
#define STTY_noargs (1 << 4)
Enumerations
enum speed_setting { input_speed , output_speed , both_speeds }
enum {
control , input , output , local ,
combination
}
enum {
IDX_evenp = 0 , IDX_parity , IDX_oddp , IDX_nl ,
IDX_ek , IDX_sane , IDX_cooked , IDX_raw ,
IDX_pass8 , IDX_litout , IDX_cbreak , IDX_crt ,
IDX_dec
}
enum { NUM_mode_info = ARRAY_SIZE(mode_info) }
enum {
CIDX_intr = 0 , CIDX_quit , CIDX_erase , CIDX_kill ,
CIDX_eof , CIDX_eol , CIDX_start , CIDX_stop ,
CIDX_susp , CIDX_min , CIDX_time
}
enum { NUM_control_info = ARRAY_SIZE(control_info) }
enum {
param_need_arg = 0x80 , param_line = 1 | 0x80 , param_rows = 2 | 0x80 , param_cols = 3 | 0x80 ,
param_columns = 4 | 0x80 , param_size = 5 , param_speed = 6 , param_ispeed = 7 | 0x80 ,
param_ospeed = 8 | 0x80
}
Functions
static tcflag_t * get_ptr_to_tcflag (unsigned type, const struct termios *mode)
static void set_speed_or_die (enum speed_setting type, const char *arg, struct termios *mode)
static NORETURN void perror_on_device_and_die (const char *fmt)
static void perror_on_device (const char *fmt)
static void wrapf (const char *message,...)
static void newline (void)
static void display_window_size (int fancy)
static const struct mode_info * find_mode (const char *name)
static const struct control_info * find_control (const char *name)
static int find_param (const char *name)
static int recover_mode (const char *arg, struct termios *mode)
static void display_recoverable (const struct termios *mode, int UNUSED_PARAM dummy)
static void display_speed (const struct termios *mode, int fancy)
static void do_display (const struct termios *mode, int all)
static void sane_mode (struct termios *mode)
static void set_mode (const struct mode_info *info, int reversed, struct termios *mode)
static void set_control_char_or_die (const struct control_info *info, const char *arg, struct termios *mode)
int stty_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char mode_name[] ALIGN1 =
static const struct mode_info mode_info[] ALIGN4
static const struct control_info control_info[] ALIGN2
struct globals FIX_ALIASING
static const struct suffix_mult stty_suffixes[] ALIGN_SUFFIX
Data Structure Documentation
mode_info
struct mode_info
Definition at line 282 of file stty.c.
Data Fields
const tcflag_t bits
const uint8_t flags
const uint8_t mask
const uint8_t type
control_info
struct control_info
Definition at line 657 of file stty.c.
Data Fields
const uint8_t offset
const uint8_t saneval
Macro Definition Documentation
_POSIX_VDISABLE
#define _POSIX_VDISABLE ((unsigned char) 0)
Definition at line 41 of file stty.c.
BSDLY
#define BSDLY 0
Definition at line 138 of file stty.c.
CEOF
#define CEOF Control('d')
Definition at line 59 of file stty.c.
CEOL
#define CEOL _POSIX_VDISABLE
Definition at line 62 of file stty.c.
CERASE
#define CERASE 127
Definition at line 53 of file stty.c.
CI_ENTRY [1/2]
#define CI_ENTRY (n, s, o) n "\0"
Definition at line 744 of file stty.c.
CI_ENTRY [2/2]
#define CI_ENTRY (n, s, o) { s, o },
Definition at line 744 of file stty.c.
CIBAUD
#define CIBAUD 0
Definition at line 141 of file stty.c.
CINTR
#define CINTR Control('c')
Definition at line 47 of file stty.c.
CKILL
#define CKILL Control('u')
Definition at line 56 of file stty.c.
CMSPAR
#define CMSPAR 0
Definition at line 147 of file stty.c.
Control
#define Control (c) ((c) & 0x1f)
Definition at line 44 of file stty.c.
CQUIT
#define CQUIT 28
Definition at line 50 of file stty.c.
CRDLY
#define CRDLY 0
Definition at line 144 of file stty.c.
CRTSCTS
#define CRTSCTS 0
Definition at line 150 of file stty.c.
CSTART
#define CSTART Control('q')
Definition at line 65 of file stty.c.
CSTOP
#define CSTOP Control('s')
Definition at line 68 of file stty.c.
CSUSP
#define CSUSP Control('z')
Definition at line 71 of file stty.c.
ECHOCTL
#define ECHOCTL 0
Definition at line 153 of file stty.c.
ECHOKE
#define ECHOKE 0
Definition at line 156 of file stty.c.
ECHOPRT
#define ECHOPRT 0
Definition at line 159 of file stty.c.
FFDLY
#define FFDLY 0
Definition at line 162 of file stty.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 798 of file stty.c.
IEXTEN
#define IEXTEN 0
Definition at line 165 of file stty.c.
IMAXBEL
#define IMAXBEL 0
Definition at line 168 of file stty.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    G.device_name = bb_msg_standard_input; \
    G.max_col = 80; \
    G.current_col = 0; /* we are noexec, must clear */ \
} while (0)
Definition at line 799 of file stty.c.
IUCLC
#define IUCLC 0
Definition at line 171 of file stty.c.
IUTF8
#define IUTF8 0
Definition at line 246 of file stty.c.
IXANY
#define IXANY 0
Definition at line 174 of file stty.c.
MI_ENTRY [1/2]
#define MI_ENTRY (N, T, F, B, M) N "\0"
Definition at line 488 of file stty.c.
MI_ENTRY [2/2]
#define MI_ENTRY (N, T, F, B, M) { T, F, M, B },
Definition at line 488 of file stty.c.
NLDLY
#define NLDLY 0
Definition at line 177 of file stty.c.
OCRNL
#define OCRNL 0
Definition at line 180 of file stty.c.
OFDEL
#define OFDEL 0
Definition at line 183 of file stty.c.
OFILL
#define OFILL 0
Definition at line 186 of file stty.c.
OLCUC
#define OLCUC 0
Definition at line 189 of file stty.c.
OMIT
#define OMIT 8 /* Don't display value */
Definition at line 276 of file stty.c.
ONLCR
#define ONLCR 0
Definition at line 192 of file stty.c.
ONLRET
#define ONLRET 0
Definition at line 195 of file stty.c.
ONOCR
#define ONOCR 0
Definition at line 198 of file stty.c.
OXTABS
#define OXTABS 0
Definition at line 201 of file stty.c.
REV
#define REV 4 /* Can be turned off by prepending '-' */
Definition at line 275 of file stty.c.
SANE_SET
#define SANE_SET 1 /* Set in 'sane' mode */
Definition at line 273 of file stty.c.
SANE_UNSET
#define SANE_UNSET 2 /* Unset in 'sane' mode */
Definition at line 274 of file stty.c.
STTY_noargs
#define STTY_noargs (1 << 4)
Definition at line 1273 of file stty.c.
STTY_recoverable_output
#define STTY_recoverable_output (1 << 3)
Definition at line 1272 of file stty.c.
STTY_require_set_attr
#define STTY_require_set_attr (1 << 0)
Definition at line 1269 of file stty.c.
STTY_speed_was_set
#define STTY_speed_was_set (1 << 1)
Definition at line 1270 of file stty.c.
STTY_verbose_output
#define STTY_verbose_output (1 << 2)
Definition at line 1271 of file stty.c.
TAB1
#define TAB1 0
Definition at line 207 of file stty.c.
TAB2
#define TAB2 0
Definition at line 210 of file stty.c.
TABDLY
#define TABDLY 0
Definition at line 204 of file stty.c.
TOSTOP
#define TOSTOP 0
Definition at line 213 of file stty.c.
VDSUSP
#define VDSUSP 0
Definition at line 216 of file stty.c.
VEOL2
#define VEOL2 0
Definition at line 219 of file stty.c.
VFLUSHO
#define VFLUSHO 0
Definition at line 222 of file stty.c.
VLNEXT
#define VLNEXT 0
Definition at line 225 of file stty.c.
VREPRINT
#define VREPRINT 0
Definition at line 228 of file stty.c.
VSTATUS
#define VSTATUS 0
Definition at line 231 of file stty.c.
VSWTCH
#define VSWTCH 0
Definition at line 234 of file stty.c.
VTDLY
#define VTDLY 0
Definition at line 237 of file stty.c.
VWERASE
#define VWERASE 0
Definition at line 240 of file stty.c.
XCASE
#define XCASE 0
Definition at line 243 of file stty.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
control
input
output
local
combination
Definition at line 255 of file stty.c.
      {
     control, input, output, local, combination
 };
anonymous enum
anonymous enum
Enumerator
IDX_evenp
IDX_parity
IDX_oddp
IDX_nl
IDX_ek
IDX_sane
IDX_cooked
IDX_raw
IDX_pass8
IDX_litout
IDX_cbreak
IDX_crt
IDX_dec
Definition at line 297 of file stty.c.
      {
     /* Must match mode_name[] and mode_info[] order! */
     IDX_evenp = 0,
     IDX_parity,
     IDX_oddp,
     IDX_nl,
     IDX_ek,
     IDX_sane,
     IDX_cooked,
     IDX_raw,
     IDX_pass8,
     IDX_litout,
     IDX_cbreak,
     IDX_crt,
     IDX_dec,
 #if IXANY
     IDX_decctlq,
 #endif
 #if TABDLY || OXTABS
     IDX_tabs,
 #endif
 #if XCASE && IUCLC && OLCUC
     IDX_lcase,
     IDX_LCASE,
 #endif
 };
anonymous enum
anonymous enum
Enumerator
NUM_mode_info
Definition at line 651 of file stty.c.
      {
     NUM_mode_info = ARRAY_SIZE(mode_info)
 };
anonymous enum
anonymous enum
Enumerator
CIDX_intr
CIDX_quit
CIDX_erase
CIDX_kill
CIDX_eof
CIDX_eol
CIDX_start
CIDX_stop
CIDX_susp
CIDX_min
CIDX_time
Definition at line 662 of file stty.c.
      {
     /* Must match control_name[] and control_info[] order! */
     CIDX_intr = 0,
     CIDX_quit,
     CIDX_erase,
     CIDX_kill,
     CIDX_eof,
     CIDX_eol,
 #if VEOL2
     CIDX_eol2,
 #endif
 #if VSWTCH
     CIDX_swtch,
 #endif
     CIDX_start,
     CIDX_stop,
     CIDX_susp,
 #if VDSUSP
     CIDX_dsusp,
 #endif
 #if VREPRINT
     CIDX_rprnt,
 #endif
 #if VWERASE
     CIDX_werase,
 #endif
 #if VLNEXT
     CIDX_lnext,
 #endif
 #if VFLUSHO
     CIDX_flush,
 #endif
 #if VSTATUS
     CIDX_status,
 #endif
     CIDX_min,
     CIDX_time,
 };
anonymous enum
anonymous enum
Enumerator
NUM_control_info
Definition at line 786 of file stty.c.
      {
     NUM_control_info = ARRAY_SIZE(control_info)
 };
anonymous enum
anonymous enum
Enumerator
param_need_arg
param_line
param_rows
param_cols
param_columns
param_size
param_speed
param_ispeed
param_ospeed
Definition at line 927 of file stty.c.
      {
     param_need_arg = 0x80,
     param_line    = 1 | 0x80,
     param_rows    = 2 | 0x80,
     param_cols    = 3 | 0x80,
     param_columns = 4 | 0x80,
     param_size    = 5,
     param_speed   = 6,
     param_ispeed  = 7 | 0x80,
     param_ospeed  = 8 | 0x80,
 };
speed_setting
enum speed_setting
Enumerator
input_speed
output_speed
both_speeds
Definition at line 250 of file stty.c.
                    {
     input_speed, output_speed, both_speeds
 };
Function Documentation
display_recoverable()
static void display_recoverable (const struct termios * mode, int UNUSED_PARAM dummy) static
Definition at line 988 of file stty.c.
 {
     int i;
     printf("%lx:%lx:%lx:%lx",
            (unsigned long) mode->c_iflag, (unsigned long) mode->c_oflag,
            (unsigned long) mode->c_cflag, (unsigned long) mode->c_lflag);
     for (i = 0; i < NCCS; ++i)
         printf(":%x", (unsigned int) mode->c_cc[i]);
     bb_putchar('\n');
 }
References bb_putchar(), termios::c_cc, termios::c_cflag, termios::c_iflag, termios::c_lflag, termios::c_oflag, i, NCCS, and printf.
Referenced by stty_main().
display_speed()
static void display_speed (const struct termios * mode, int fancy) static
Definition at line 1000 of file stty.c.
 {
     //____________________ 01234567 8 9
     const char *fmt_str = "%lu %lu\n\0ispeed %lu baud; ospeed %lu baud;";
     unsigned long ispeed, ospeed;
     ispeed = cfgetispeed(mode);
     ospeed = cfgetospeed(mode);
     if (ispeed == 0 || ispeed == ospeed) {
         ispeed = ospeed;                /* in case ispeed was 0 */
         //________ 0123 4 5 6 7 8 9
         fmt_str = "%lu\n\0\0\0\0\0speed %lu baud;";
     }
     if (fancy) fmt_str += 9;
     wrapf(fmt_str, tty_baud_to_value(ispeed), tty_baud_to_value(ospeed));
 }
References cfgetispeed(), cfgetospeed(), fmt_str(), ospeed, tty_baud_to_value(), and wrapf().
Referenced by do_display(), and stty_main().
display_window_size()
static void display_window_size (int fancy) static
Definition at line 893 of file stty.c.
 {
     const char *fmt_str = "%s\0%s: no size information for this device";
     unsigned width, height;
     if (get_terminal_width_height(STDIN_FILENO, &width, &height)) {
         if ((errno != EINVAL) || ((fmt_str += 2), !fancy)) {
             perror_on_device(fmt_str);
         }
     } else {
         wrapf(fancy ? "rows %u; columns %u;" : "%u %u\n",
                 height, width);
     }
 }
References EINVAL, errno, fmt_str(), get_terminal_width_height(), height(), perror_on_device(), STDIN_FILENO, width, and wrapf().
Referenced by do_display(), and stty_main().
do_display()
static void do_display (const struct termios * mode, int all) static
Definition at line 1017 of file stty.c.
 {
     int i;
     tcflag_t *bitsp;
     unsigned long mask;
     int prev_type = control;
     display_speed(mode, 1);
     if (all)
         display_window_size(1);
 #ifdef __linux__
     wrapf("line = %u;\n", mode->c_line);
 #else
     newline();
 #endif
     for (i = 0; i != CIDX_min; ++i) {
         char ch;
         char buf10[10];
         /* If swtch is the same as susp, don't print both */
 #if VSWTCH == VSUSP
         if (i == CIDX_swtch)
             continue;
 #endif
         /* If eof uses the same slot as min, only print whichever applies */
 #if VEOF == VMIN
         if (!(mode->c_lflag & ICANON)
          && (i == CIDX_eof || i == CIDX_eol)
         ) {
             continue;
         }
 #endif
         ch = mode->c_cc[control_info[i].offset];
         if (ch == _POSIX_VDISABLE)
             strcpy(buf10, "<undef>");
         else
             visible(ch, buf10, 0);
         wrapf("%s = %s;", nth_string(control_name, i), buf10);
     }
 #if VEOF == VMIN
     if ((mode->c_lflag & ICANON) == 0)
 #endif
         wrapf("min = %u; time = %u;", mode->c_cc[VMIN], mode->c_cc[VTIME]);
     newline();
     for (i = 0; i < NUM_mode_info; ++i) {
         if (mode_info[i].flags & OMIT)
             continue;
         if (mode_info[i].type != prev_type) {
             newline();
             prev_type = mode_info[i].type;
         }
         bitsp = get_ptr_to_tcflag(mode_info[i].type, mode);
         mask = mode_info[i].mask ? mode_info[i].mask : mode_info[i].bits;
         if ((*bitsp & mask) == mode_info[i].bits) {
             if (all || (mode_info[i].flags & SANE_UNSET))
                 wrapf("-%s"+1, nth_string(mode_name, i));
         } else {
             if ((all && mode_info[i].flags & REV)
              || (!all && (mode_info[i].flags & (SANE_SET | REV)) == (SANE_SET | REV))
             ) {
                 wrapf("-%s", nth_string(mode_name, i));
             }
         }
     }
     newline();
 }
References _POSIX_VDISABLE, mode_info::bits, termios::c_cc, termios::c_lflag, termios::c_line, CIDX_eof, CIDX_eol, CIDX_min, control, display_speed(), display_window_size(), flags, get_ptr_to_tcflag(), i, ICANON, mode_info::mask, newline(), nth_string(), NUM_mode_info, control_info::offset, OMIT, REV, SANE_SET, SANE_UNSET, strcpy, mode_info::type, type, visible(), VMIN, VTIME, and wrapf().
Referenced by stty_main().
find_control()
static const struct control_info* find_control (const char * name) static
Definition at line 921 of file stty.c.
 {
     int i = index_in_strings(control_name, name);
     return i >= 0 ? &control_info[i] : NULL;
 }
References i, index_in_strings(), and NULL.
Referenced by stty_main().
find_mode()
static const struct mode_info* find_mode (const char * name) static
Definition at line 915 of file stty.c.
 {
     int i = index_in_strings(mode_name, name);
     return i >= 0 ? &mode_info[i] : NULL;
 }
References i, index_in_strings(), and NULL.
Referenced by stty_main().
find_param()
static int find_param (const char * name) static
Definition at line 939 of file stty.c.
 {
     static const char params[] ALIGN1 =
         "line\0"    /* 1 */
         "rows\0"    /* 2 */
         "cols\0"    /* 3 */
         "columns\0" /* 4 */
         "size\0"    /* 5 */
         "speed\0"   /* 6 */
         "ispeed\0"
         "ospeed\0";
     int i = index_in_strings(params, name) + 1;
     if (i == 0)
         return 0;
     if (i != 5 && i != 6)
         i |= 0x80;
     return i;
 }
References ALIGN1, i, and index_in_strings().
Referenced by stty_main().
get_ptr_to_tcflag()
static tcflag_t* get_ptr_to_tcflag (unsigned type, const struct termios * mode) static
Definition at line 258 of file stty.c.
 {
     static const uint8_t tcflag_offsets[] ALIGN1 = {
         offsetof(struct termios, c_cflag), /* control */
         offsetof(struct termios, c_iflag), /* input */
         offsetof(struct termios, c_oflag), /* output */
         offsetof(struct termios, c_lflag)  /* local */
     };
     if (type <= local) {
         return (tcflag_t*) (((char*)mode) + tcflag_offsets[type]);
     }
     return NULL;
 }
References ALIGN1, local, NULL, offsetof, and type.
Referenced by do_display(), sane_mode(), and set_mode().
newline()
static void newline (void) static
Definition at line 864 of file stty.c.
 {
     if (G.current_col != 0)
         wrapf("\n");
 }
References G, and wrapf().
Referenced by do_display().
perror_on_device()
static void perror_on_device (const char * fmt) static
Definition at line 826 of file stty.c.
 {
     bb_perror_msg(fmt, G.device_name);
 }
References bb_perror_msg(), and G.
Referenced by display_window_size().
perror_on_device_and_die()
static NORETURN void perror_on_device_and_die (const char * fmt) static
Definition at line 821 of file stty.c.
 {
     bb_perror_msg_and_die(fmt, G.device_name);
 }
References bb_perror_msg_and_die(), and G.
Referenced by stty_main().
recover_mode()
static int recover_mode (const char * arg, struct termios * mode) static
Definition at line 958 of file stty.c.
 {
     int i, n;
     unsigned chr;
     unsigned long iflag, oflag, cflag, lflag;
     /* Scan into temporaries since it is too much trouble to figure out
        the right format for 'tcflag_t' */
     if (sscanf(arg, "%lx:%lx:%lx:%lx%n",
                &iflag, &oflag, &cflag, &lflag, &n) != 4)
         return 0;
     mode->c_iflag = iflag;
     mode->c_oflag = oflag;
     mode->c_cflag = cflag;
     mode->c_lflag = lflag;
     arg += n;
     for (i = 0; i < NCCS; ++i) {
         if (sscanf(arg, ":%x%n", &chr, &n) != 1)
             return 0;
         mode->c_cc[i] = chr;
         arg += n;
     }
     /* Fail if there are too many fields */
     if (*arg != '\0')
         return 0;
     return 1;
 }
References termios::c_cc, termios::c_cflag, termios::c_iflag, termios::c_lflag, termios::c_oflag, cflag, i, iflag, n, NCCS, and sscanf().
Referenced by stty_main().
sane_mode()
static void sane_mode (struct termios * mode) static
Definition at line 1087 of file stty.c.
 {
     int i;
     for (i = 0; i < NUM_control_info; ++i) {
 #if VMIN == VEOF
         if (i == CIDX_min)
             break;
 #endif
         mode->c_cc[control_info[i].offset] = control_info[i].saneval;
     }
     for (i = 0; i < NUM_mode_info; ++i) {
         tcflag_t val;
         tcflag_t *bitsp = get_ptr_to_tcflag(mode_info[i].type, mode);
         if (!bitsp)
             continue;
         val = *bitsp & ~((unsigned long)mode_info[i].mask);
         if (mode_info[i].flags & SANE_SET) {
             *bitsp = val | mode_info[i].bits;
         } else
         if (mode_info[i].flags & SANE_UNSET) {
             *bitsp = val & ~mode_info[i].bits;
         }
     }
 }
References mode_info::bits, termios::c_cc, CIDX_min, flags, get_ptr_to_tcflag(), i, NUM_control_info, NUM_mode_info, control_info::offset, SANE_SET, SANE_UNSET, control_info::saneval, type, and val.
Referenced by set_mode().
set_control_char_or_die()
static void set_control_char_or_die (const struct control_info * info, const char * arg, struct termios * mode) static
Definition at line 1249 of file stty.c.
 {
     unsigned char value;
     if (info == &control_info[CIDX_min] || info == &control_info[CIDX_time])
         value = xatoul_range_sfx(arg, 0, 0xff, stty_suffixes);
     else if (arg[0] == '\0' || arg[1] == '\0')
         value = arg[0];
     else if (strcmp(arg, "^-") == 0 || strcmp(arg, "undef") == 0)
         value = _POSIX_VDISABLE;
     else if (arg[0] == '^') { /* Ignore any trailing junk (^Cjunk) */
         value = arg[1] & 0x1f; /* Non-letters get weird results */
         if (arg[1] == '?')
             value = 127;
     } else
         value = xatoul_range_sfx(arg, 0, 0xff, stty_suffixes);
     mode->c_cc[info->offset] = value;
 }
References _POSIX_VDISABLE, termios::c_cc, CIDX_min, CIDX_time, info, strcmp, and value.
Referenced by stty_main().
set_mode()
static void set_mode (const struct mode_info * info, int reversed, struct termios * mode) static
Definition at line 1115 of file stty.c.
 {
     tcflag_t *bitsp;
     bitsp = get_ptr_to_tcflag(info->type, mode);
     if (bitsp) {
         tcflag_t val = *bitsp & ~info->mask;
         if (reversed)
             *bitsp = val & ~info->bits;
         else
             *bitsp = val | info->bits;
         return;
     }
     /* !bitsp - it's a "combination" mode */
     if (info == &mode_info[IDX_evenp] || info == &mode_info[IDX_parity]) {
         if (reversed)
             mode->c_cflag = (mode->c_cflag & ~PARENB & ~CSIZE) | CS8;
         else
             mode->c_cflag = (mode->c_cflag & ~PARODD & ~CSIZE) | PARENB | CS7;
     } else if (info == &mode_info[IDX_oddp]) {
         if (reversed)
             mode->c_cflag = (mode->c_cflag & ~PARENB & ~CSIZE) | CS8;
         else
             mode->c_cflag = (mode->c_cflag & ~CSIZE) | CS7 | PARODD | PARENB;
     } else if (info == &mode_info[IDX_nl]) {
         if (reversed) {
             mode->c_iflag = (mode->c_iflag | ICRNL) & ~INLCR & ~IGNCR;
             mode->c_oflag = (mode->c_oflag | ONLCR) & ~OCRNL & ~ONLRET;
         } else {
             mode->c_iflag = mode->c_iflag & ~ICRNL;
             if (ONLCR) mode->c_oflag = mode->c_oflag & ~ONLCR;
         }
     } else if (info == &mode_info[IDX_ek]) {
         mode->c_cc[VERASE] = CERASE;
         mode->c_cc[VKILL] = CKILL;
     } else if (info == &mode_info[IDX_sane]) {
         sane_mode(mode);
     } else if (info == &mode_info[IDX_cbreak]) {
         if (reversed)
             mode->c_lflag |= ICANON;
         else
             mode->c_lflag &= ~ICANON;
     } else if (info == &mode_info[IDX_pass8]) {
         if (reversed) {
             mode->c_cflag = (mode->c_cflag & ~CSIZE) | CS7 | PARENB;
             mode->c_iflag |= ISTRIP;
         } else {
             mode->c_cflag = (mode->c_cflag & ~PARENB & ~CSIZE) | CS8;
             mode->c_iflag &= ~ISTRIP;
         }
     } else if (info == &mode_info[IDX_litout]) {
         if (reversed) {
             mode->c_cflag = (mode->c_cflag & ~CSIZE) | CS7 | PARENB;
             mode->c_iflag |= ISTRIP;
             mode->c_oflag |= OPOST;
         } else {
             mode->c_cflag = (mode->c_cflag & ~PARENB & ~CSIZE) | CS8;
             mode->c_iflag &= ~ISTRIP;
             mode->c_oflag &= ~OPOST;
         }
     } else if (info == &mode_info[IDX_raw] || info == &mode_info[IDX_cooked]) {
         if ((info == &mode_info[IDX_raw] && reversed)
          || (info == &mode_info[IDX_cooked] && !reversed)
         ) {
             /* Cooked mode */
             mode->c_iflag |= BRKINT | IGNPAR | ISTRIP | ICRNL | IXON;
             mode->c_oflag |= OPOST;
             mode->c_lflag |= ISIG | ICANON;
 #if VMIN == VEOF
             mode->c_cc[VEOF] = CEOF;
 #endif
 #if VTIME == VEOL
             mode->c_cc[VEOL] = CEOL;
 #endif
         } else {
             /* Raw mode */
             mode->c_iflag = 0;
             mode->c_oflag &= ~OPOST;
             mode->c_lflag &= ~(ISIG | ICANON | XCASE);
             mode->c_cc[VMIN] = 1;
             mode->c_cc[VTIME] = 0;
         }
     }
 #if IXANY
     else if (info == &mode_info[IDX_decctlq]) {
         if (reversed)
             mode->c_iflag |= IXANY;
         else
             mode->c_iflag &= ~IXANY;
     }
 #endif
 #if TABDLY
     else if (info == &mode_info[IDX_tabs]) {
         if (reversed)
             mode->c_oflag = (mode->c_oflag & ~TABDLY) | TAB3;
         else
             mode->c_oflag = (mode->c_oflag & ~TABDLY) | TAB0;
     }
 #endif
 #if OXTABS
     else if (info == &mode_info[IDX_tabs]) {
         if (reversed)
             mode->c_oflag |= OXTABS;
         else
             mode->c_oflag &= ~OXTABS;
     }
 #endif
 #if XCASE && IUCLC && OLCUC
     else if (info==&mode_info[IDX_lcase] || info==&mode_info[IDX_LCASE]) {
         if (reversed) {
             mode->c_lflag &= ~XCASE;
             mode->c_iflag &= ~IUCLC;
             mode->c_oflag &= ~OLCUC;
         } else {
             mode->c_lflag |= XCASE;
             mode->c_iflag |= IUCLC;
             mode->c_oflag |= OLCUC;
         }
     }
 #endif
     else if (info == &mode_info[IDX_crt]) {
         mode->c_lflag |= ECHOE | ECHOCTL | ECHOKE;
     } else if (info == &mode_info[IDX_dec]) {
         mode->c_cc[VINTR] = 3; /* ^C */
         mode->c_cc[VERASE] = 127; /* DEL */
         mode->c_cc[VKILL] = 21; /* ^U */
         mode->c_lflag |= ECHOE | ECHOCTL | ECHOKE;
         if (IXANY) mode->c_iflag &= ~IXANY;
     }
 }
References BRKINT, termios::c_cc, termios::c_cflag, termios::c_iflag, termios::c_lflag, termios::c_oflag, CEOF, CEOL, CERASE, CKILL, CS7, CS8, CSIZE, ECHOCTL, ECHOE, ECHOKE, get_ptr_to_tcflag(), ICANON, ICRNL, IDX_cbreak, IDX_cooked, IDX_crt, IDX_dec, IDX_ek, IDX_evenp, IDX_litout, IDX_nl, IDX_oddp, IDX_parity, IDX_pass8, IDX_raw, IDX_sane, IGNCR, IGNPAR, info, INLCR, ISIG, ISTRIP, IUCLC, IXANY, IXON, OCRNL, OLCUC, ONLCR, ONLRET, OPOST, OXTABS, PARENB, PARODD, sane_mode(), TABDLY, val, VEOF, VEOL, VERASE, VINTR, VKILL, VMIN, VTIME, and XCASE.
Referenced by stty_main().
set_speed_or_die()
static void set_speed_or_die (enum speed_setting type, const char * arg, struct termios * mode) static
Definition at line 806 of file stty.c.
 {
     speed_t baud;
     baud = tty_value_to_baud(xatou(arg));
     if (type != output_speed) {     /* either input or both */
         cfsetispeed(mode, baud);
     }
     if (type != input_speed) {      /* either output or both */
         cfsetospeed(mode, baud);
     }
 }
References cfsetispeed(), cfsetospeed(), input_speed, output_speed, tty_value_to_baud(), type, and xatou().
Referenced by stty_main().
stty_main()
int stty_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1276 of file stty.c.
 {
     struct termios mode;
     void (*output_func)(const struct termios *, int);
     const char *file_name = NULL;
     int display_all = 0;
     int stty_state;
     int k;
     INIT_G();
     stty_state = STTY_noargs;
     output_func = do_display;
     /* First pass: only parse/verify command line params */
     k = 0;
     while (argv[++k]) {
         const struct mode_info *mp;
         const struct control_info *cp;
         const char *arg = argv[k];
         const char *argnext = argv[k+1];
         int param;
         if (arg[0] == '-') {
             int i;
             mp = find_mode(arg+1);
             if (mp) {
                 if (!(mp->flags & REV))
                     goto invalid_argument;
                 stty_state &= ~STTY_noargs;
                 continue;
             }
             /* It is an option - parse it */
             i = 0;
             while (arg[++i]) {
                 switch (arg[i]) {
                 case 'a':
                     stty_state |= STTY_verbose_output;
                     output_func = do_display;
                     display_all = 1;
                     break;
                 case 'g':
                     stty_state |= STTY_recoverable_output;
                     output_func = display_recoverable;
                     break;
                 case 'F':
                     if (file_name)
                         bb_simple_error_msg_and_die("only one device may be specified");
                     file_name = &arg[i+1]; /* "-Fdevice" ? */
                     if (!file_name[0]) { /* nope, "-F device" */
                         int p = k+1; /* argv[p] is argnext */
                         file_name = argnext;
                         if (!file_name)
                             bb_error_msg_and_die(bb_msg_requires_arg, "-F");
                         /* remove -F param from arg[vc] */
                         while (argv[p]) {
                             argv[p] = argv[p+1];
                             ++p;
                         }
                     }
                     goto end_option;
                 default:
                     goto invalid_argument;
                 }
             }
  end_option:
             continue;
         }
         mp = find_mode(arg);
         if (mp) {
             stty_state &= ~STTY_noargs;
             continue;
         }
         cp = find_control(arg);
         if (cp) {
             if (!argnext)
                 bb_error_msg_and_die(bb_msg_requires_arg, arg);
             /* called for the side effect of xfunc death only */
             set_control_char_or_die(cp, argnext, &mode);
             stty_state &= ~STTY_noargs;
             ++k;
             continue;
         }
         param = find_param(arg);
         if (param & param_need_arg) {
             if (!argnext)
                 bb_error_msg_and_die(bb_msg_requires_arg, arg);
             ++k;
         }
         switch (param) {
 #ifdef __linux__
         case param_line:
 # ifndef TIOCGWINSZ
             xatoul_range_sfx(argnext, 1, INT_MAX, stty_suffixes);
             break;
 # endif /* else fall-through */
 #endif
 #ifdef TIOCGWINSZ
         case param_rows:
         case param_cols:
         case param_columns:
             xatoul_range_sfx(argnext, 1, INT_MAX, stty_suffixes);
             break;
         case param_size:
 #endif
         case param_speed:
             break;
         case param_ispeed:
             /* called for the side effect of xfunc death only */
             set_speed_or_die(input_speed, argnext, &mode);
             break;
         case param_ospeed:
             /* called for the side effect of xfunc death only */
             set_speed_or_die(output_speed, argnext, &mode);
             break;
         default:
             if (recover_mode(arg, &mode) == 1) break;
             if (tty_value_to_baud(xatou(arg)) != (speed_t) -1) break;
  invalid_argument:
             bb_error_msg_and_die("invalid argument '%s'", arg);
         }
         stty_state &= ~STTY_noargs;
     }
     /* Specifying both -a and -g is an error */
     if ((stty_state & (STTY_verbose_output | STTY_recoverable_output)) ==
         (STTY_verbose_output | STTY_recoverable_output)
     ) {
         bb_simple_error_msg_and_die("-a and -g are mutually exclusive");
     }
     /* Specifying -a or -g with non-options is an error */
     if ((stty_state & (STTY_verbose_output | STTY_recoverable_output))
      && !(stty_state & STTY_noargs)
     ) {
         bb_simple_error_msg_and_die("modes may not be set when -a or -g is used");
     }
     /* Now it is safe to start doing things */
     if (file_name) {
         G.device_name = file_name;
         xmove_fd(xopen_nonblocking(G.device_name), STDIN_FILENO);
         ndelay_off(STDIN_FILENO);
     }
     /* Initialize to all zeroes so there is no risk memcmp will report a
        spurious difference in an uninitialized portion of the structure */
     memset(&mode, 0, sizeof(mode));
     if (tcgetattr(STDIN_FILENO, &mode))
         perror_on_device_and_die("%s");
     if (stty_state & (STTY_verbose_output | STTY_recoverable_output | STTY_noargs)) {
         G.max_col = get_terminal_width(STDOUT_FILENO);
         output_func(&mode, display_all);
         return EXIT_SUCCESS;
     }
     /* Second pass: perform actions */
     k = 0;
     while (argv[++k]) {
         const struct mode_info *mp;
         const struct control_info *cp;
         const char *arg = argv[k];
         const char *argnext = argv[k+1];
         int param;
         if (arg[0] == '-') {
             mp = find_mode(arg+1);
             if (mp) {
                 set_mode(mp, 1 /* reversed */, &mode);
                 stty_state |= STTY_require_set_attr;
             }
             /* It is an option - already parsed. Skip it */
             continue;
         }
         mp = find_mode(arg);
         if (mp) {
             set_mode(mp, 0 /* non-reversed */, &mode);
             stty_state |= STTY_require_set_attr;
             continue;
         }
         cp = find_control(arg);
         if (cp) {
             ++k;
             set_control_char_or_die(cp, argnext, &mode);
             stty_state |= STTY_require_set_attr;
             continue;
         }
         param = find_param(arg);
         if (param & param_need_arg) {
             ++k;
         }
         switch (param) {
 #ifdef __linux__
         case param_line:
             mode.c_line = xatoul_sfx(argnext, stty_suffixes);
             stty_state |= STTY_require_set_attr;
             break;
 #endif
 #ifdef TIOCGWINSZ
         case param_cols:
         case param_columns:
             set_window_size(-1, xatoul_sfx(argnext, stty_suffixes));
             break;
         case param_size:
             display_window_size(0);
             break;
         case param_rows:
             set_window_size(xatoul_sfx(argnext, stty_suffixes), -1);
             break;
 #endif
         case param_speed:
             display_speed(&mode, 0);
             break;
         case param_ispeed:
             set_speed_or_die(input_speed, argnext, &mode);
             stty_state |= (STTY_require_set_attr | STTY_speed_was_set);
             break;
         case param_ospeed:
             set_speed_or_die(output_speed, argnext, &mode);
             stty_state |= (STTY_require_set_attr | STTY_speed_was_set);
             break;
         default:
             if (recover_mode(arg, &mode) == 1)
                 stty_state |= STTY_require_set_attr;
             else /* true: if (tty_value_to_baud(xatou(arg)) != (speed_t) -1) */{
                 set_speed_or_die(both_speeds, arg, &mode);
                 stty_state |= (STTY_require_set_attr | STTY_speed_was_set);
             } /* else - impossible (caught in the first pass):
                 bb_error_msg_and_die("invalid argument '%s'", arg); */
         }
     }
     if (stty_state & STTY_require_set_attr) {
         struct termios new_mode;
         if (tcsetattr(STDIN_FILENO, TCSADRAIN, &mode))
             perror_on_device_and_die("%s");
         /* POSIX (according to Zlotnick's book) tcsetattr returns zero if
            it performs *any* of the requested operations.  This means it
            can report 'success' when it has actually failed to perform
            some proper subset of the requested operations.  To detect
            this partial failure, get the current terminal attributes and
            compare them to the requested ones */
         /* Initialize to all zeroes so there is no risk memcmp will report a
            spurious difference in an uninitialized portion of the structure */
         memset(&new_mode, 0, sizeof(new_mode));
         if (tcgetattr(STDIN_FILENO, &new_mode))
             perror_on_device_and_die("%s");
         if (memcmp(&mode, &new_mode, sizeof(mode)) != 0) {
 /*
  * I think the below chunk is not necessary on Linux.
  * If you are deleting it, also delete STTY_speed_was_set bit -
  * it is only ever checked here.
  */
 #if 0 /* was "if CIBAUD" */
             /* SunOS 4.1.3 (at least) has the problem that after this sequence,
                tcgetattr (&m1); tcsetattr (&m1); tcgetattr (&m2);
                sometimes (m1 != m2).  The only difference is in the four bits
                of the c_cflag field corresponding to the baud rate.  To save
                Sun users a little confusion, don't report an error if this
                happens.  But suppress the error only if we haven't tried to
                set the baud rate explicitly -- otherwise we'd never give an
                error for a true failure to set the baud rate */
             new_mode.c_cflag &= (~CIBAUD);
             if ((stty_state & STTY_speed_was_set)
              || memcmp(&mode, &new_mode, sizeof(mode)) != 0)
 #endif
                 perror_on_device_and_die("%s: cannot perform all requested operations");
         }
     }
     return EXIT_SUCCESS;
 }
References argv, bb_error_msg_and_die(), bb_simple_error_msg_and_die(), both_speeds, termios::c_cflag, termios::c_line, CIBAUD, display_recoverable(), display_speed(), display_window_size(), do_display(), EXIT_SUCCESS, find_control(), find_mode(), find_param(), mode_info::flags, G, get_terminal_width(), i, INIT_G, input_speed, INT_MAX, k, memcmp(), memset, ndelay_off(), NULL, output_speed, p, param, param_cols, param_columns, param_ispeed, param_line, param_need_arg, param_ospeed, param_rows, param_size, param_speed, perror_on_device_and_die(), recover_mode(), REV, set_control_char_or_die(), set_mode(), set_speed_or_die(), STDIN_FILENO, STDOUT_FILENO, STTY_noargs, STTY_recoverable_output, STTY_require_set_attr, STTY_speed_was_set, STTY_verbose_output, tcgetattr(), TCSADRAIN, tcsetattr(), tty_value_to_baud(), Driver::void(), xatou(), xmove_fd(), and xopen_nonblocking().
Referenced by reset_main().
wrapf()
static void wrapf (const char * message, ...) static
Definition at line 834 of file stty.c.
 {
     char buf[128];
     va_list args;
     unsigned buflen;
     va_start(args, message);
     buflen = vsnprintf(buf, sizeof(buf), message, args);
     va_end(args);
     /* We seem to be called only with suitable lengths, but check if
        somebody failed to adhere to this assumption just to be sure.  */
     if (!buflen || buflen >= sizeof(buf)) return;
     if (G.current_col > 0) {
         G.current_col++;
         if (buf[0] != '\n') {
             if (G.current_col + buflen >= G.max_col) {
                 G.current_col = 0;
                 bb_putchar('\n');
             } else {
                 bb_putchar(' ');
             }
         }
     }
     fputs_stdout(buf);
     G.current_col += buflen;
     if (buf[buflen-1] == '\n')
         G.current_col = 0;
 }
References args, bb_putchar(), buf, buflen, fputs_stdout(), G, va_end, va_start, and vsnprintf().
Referenced by display_speed(), display_window_size(), do_display(), and newline().
Variable Documentation
ALIGN1
const char control_name [] ALIGN1 = static
Definition at line 327 of file stty.c.
Referenced by find_param(), and get_ptr_to_tcflag().
ALIGN2
const struct control_info control_info [] ALIGN2 static
Definition at line 746 of file stty.c.
ALIGN4
const struct mode_info mode_info [] ALIGN4 static
Definition at line 490 of file stty.c.
ALIGN_SUFFIX
const struct suffix_mult stty_suffixes [] ALIGN_SUFFIX static
Initial value:
= {
    { "b",  512 },
    { "k", 1024 },
    { "B", 1024 },
    { "", 0 }
}
Definition at line 908 of file stty.c.
FIX_ALIASING
struct globals FIX_ALIASING