Fennix: Userspace/musl/src/legacy/lutimes.c File Reference
lutimes.c File Reference
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>
Macros
#define _GNU_SOURCE
Functions
int lutimes (const char *filename, const struct timeval tv[2])
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file lutimes.c.
Function Documentation
lutimes()
int lutimes (const char * filename, const struct timeval tv[2])
Definition at line 6 of file lutimes.c.
 {
     struct timespec times[2];
     if (tv) {
         times[0].tv_sec  = tv[0].tv_sec;
         times[0].tv_nsec = tv[0].tv_usec * 1000;
         times[1].tv_sec  = tv[1].tv_sec;
         times[1].tv_nsec = tv[1].tv_usec * 1000;
     }
     return utimensat(AT_FDCWD, filename, tv ? times : 0, AT_SYMLINK_NOFOLLOW);
 }
References AT_FDCWD, AT_SYMLINK_NOFOLLOW, filename, times(), timeval::tv_sec, timeval::tv_usec, and utimensat().
Referenced by __lutimes_time32().