Fennix Userspace: Userspace/mlibc/options/ansi/musl-generic-math/log.c File Reference
log.c File Reference
#include <math.h>
#include <stdint.h>
Functions
double log (double x)
Variables
static const double ln2_hi = 6.93147180369123816490e-01
static const double ln2_lo = 1.90821492927058770002e-10
static const double Lg1 = 6.666666666666735130e-01
static const double Lg2 = 3.999999999940941908e-01
static const double Lg3 = 2.857142874366239149e-01
static const double Lg4 = 2.222219843214978396e-01
static const double Lg5 = 1.818357216161805012e-01
static const double Lg6 = 1.531383769920937332e-01
static const double Lg7 = 1.479819860511658591e-01
Function Documentation
log()
double log (double x)
Definition at line 77 of file log.c.
 {
     union {double f; uint64_t i;} u = {x};
     double_t hfsq,f,s,z,R,w,t1,t2,dk;
     uint32_t hx;
     int k;
     hx = u.i>>32;
     k = 0;
     if (hx < 0x00100000 || hx>>31) {
         if (u.i<<1 == 0)
             return -1/(x*x);  /* log(+-0)=-inf */
         if (hx>>31)
             return (x-x)/0.0; /* log(-#) = NaN */
         /* subnormal number, scale x up */
         k -= 54;
         x *= 0x1p54;
         u.f = x;
         hx = u.i>>32;
     } else if (hx >= 0x7ff00000) {
         return x;
     } else if (hx == 0x3ff00000 && u.i<<32 == 0)
         return 0;
     /* reduce x into [sqrt(2)/2, sqrt(2)] */
     hx += 0x3ff00000 - 0x3fe6a09e;
     k += (int)(hx>>20) - 0x3ff;
     hx = (hx&0x000fffff) + 0x3fe6a09e;
     u.i = (uint64_t)hx<<32 | (u.i&0xffffffff);
     x = u.f;
     f = x - 1.0;
     hfsq = 0.5*f*f;
     s = f/(2.0+f);
     z = s*s;
     w = z*z;
     t1 = w*(Lg2+w*(Lg4+w*Lg6));
     t2 = z*(Lg1+w*(Lg3+w*(Lg5+w*Lg7)));
     R = t2 + t1;
     dk = k;
     return s*(hfsq+R) + dk*ln2_lo - hfsq + f + dk*ln2_hi;
 }
References i, int, k, Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, Lg7, ln2_hi, ln2_lo, R, t1, t2, and x.
Referenced by __lgamma_r(), acosh(), asinh(), catan(), clog(), cpow(), jn(), y0(), and y1().
Variable Documentation
Lg1
const double Lg1 = 6.666666666666735130e-01 static
Definition at line 69 of file log.c.
Referenced by log().
Lg2
const double Lg2 = 3.999999999940941908e-01 static
Definition at line 70 of file log.c.
Referenced by log().
Lg3
const double Lg3 = 2.857142874366239149e-01 static
Definition at line 71 of file log.c.
Referenced by log().
Lg4
const double Lg4 = 2.222219843214978396e-01 static
Definition at line 72 of file log.c.
Referenced by log().
Lg5
const double Lg5 = 1.818357216161805012e-01 static
Definition at line 73 of file log.c.
Referenced by log().
Lg6
const double Lg6 = 1.531383769920937332e-01 static
Definition at line 74 of file log.c.
Referenced by log().
Lg7
const double Lg7 = 1.479819860511658591e-01 static
Definition at line 75 of file log.c.
Referenced by log().
ln2_hi
const double ln2_hi = 6.93147180369123816490e-01 static
Definition at line 67 of file log.c.
Referenced by log().
ln2_lo
const double ln2_lo = 1.90821492927058770002e-10 static
Definition at line 68 of file log.c.
Referenced by log().