Fennix Userspace: Userspace/musl/src/stdlib/qsort.c File Reference
qsort.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "atomic.h"
Macros
#define _BSD_SOURCE
#define ntz(x) a_ctz_l((x))
Typedefs
typedef int(* cmpfun) (const void *, const void *, void *)
Functions
static int pntz (size_t p[2])
static void cycle (size_t width, unsigned char *ar[], int n)
static void shl (size_t p[2], int n)
static void shr (size_t p[2], int n)
static void sift (unsigned char *head, size_t width, cmpfun cmp, void *arg, int pshift, size_t lp[])
static void trinkle (unsigned char *head, size_t width, cmpfun cmp, void *arg, size_t pp[2], int pshift, int trusty, size_t lp[])
void __qsort_r (void *base, size_t nel, size_t width, cmpfun cmp, void *arg)
weak_alias (__qsort_r, qsort_r)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 27 of file qsort.c.
ntz
#define ntz (x) a_ctz_l((x))
Definition at line 33 of file qsort.c.
Typedef Documentation
cmpfun
typedef int(* cmpfun) (const void *, const void *, void *)
Definition at line 35 of file qsort.c.
Function Documentation
__qsort_r()
void __qsort_r (void * base, size_t nel, size_t width, cmpfun cmp, void * arg)
Definition at line 158 of file qsort.c.
 {
     size_t lp[12*sizeof(size_t)];
     size_t i, size = width * nel;
     unsigned char *head, *high;
     size_t p[2] = {1, 0};
     int pshift = 1;
     int trail;
     if (!size) return;
     head = base;
     high = head + size - width;
     /* Precompute Leonardo numbers, scaled by element width */
     for(lp[0]=lp[1]=width, i=2; (lp[i]=lp[i-2]+lp[i-1]+width) < size; i++);
     while(head < high) {
         if((p[0] & 3) == 3) {
             sift(head, width, cmp, arg, pshift, lp);
             shr(p, 2);
             pshift += 2;
         } else {
             if(lp[pshift - 1] >= high - head) {
                 trinkle(head, width, cmp, arg, p, pshift, 0, lp);
             } else {
                 sift(head, width, cmp, arg, pshift, lp);
             }
             if(pshift == 1) {
                 shl(p, 1);
                 pshift = 0;
             } else {
                 shl(p, pshift - 1);
                 pshift = 1;
             }
         }
         p[0] |= 1;
         head += width;
     }
     trinkle(head, width, cmp, arg, p, pshift, 0, lp);
     while(pshift != 1 || p[0] != 1 || p[1] != 0) {
         if(pshift <= 1) {
             trail = pntz(p);
             shr(p, trail);
             pshift += trail;
         } else {
             shl(p, 2);
             pshift -= 2;
             p[0] ^= 7;
             shr(p, 1);
             trinkle(head - lp[pshift] - width, width, cmp, arg, p, pshift + 1, 1, lp);
             shl(p, 1);
             p[0] |= 1;
             trinkle(head - width, width, cmp, arg, p, pshift, 1, lp);
         }
         head -= width;
     }
 }
References base, cmp(), head, i, p, pntz(), shl(), shr(), sift(), size, trinkle(), and width.
cycle()
static void cycle (size_t width, unsigned char * ar[], int n) static
Definition at line 45 of file qsort.c.
 {
     unsigned char tmp[256];
     size_t l;
     int i;
     if(n < 2) {
         return;
     }
     ar[n] = tmp;
     while(width) {
         l = sizeof(tmp) < width ? sizeof(tmp) : width;
         memcpy(ar[n], ar[0], l);
         for(i = 0; i < n; i++) {
             memcpy(ar[i], ar[i + 1], l);
             ar[i] += l;
         }
         width -= l;
     }
 }
References i, memcpy(), n, and width.
Referenced by sift(), and trinkle().
pntz()
static int pntz (size_t p[2]) inline static
Definition at line 37 of file qsort.c.
{
     int r = ntz(p[0] - 1);
     if(r != 0 || (r = 8*sizeof(size_t) + ntz(p[1])) != 8*sizeof(size_t)) {
         return r;
     }
     return 0;
 }
References ntz, p, and r.
Referenced by __qsort_r(), and trinkle().
shl()
static void shl (size_t p[2], int n) inline static
Definition at line 68 of file qsort.c.
 {
     if(n >= 8 * sizeof(size_t)) {
         n -= 8 * sizeof(size_t);
         p[1] = p[0];
         p[0] = 0;
     }
     p[1] <<= n;
     p[1] |= p[0] >> (sizeof(size_t) * 8 - n);
     p[0] <<= n;
 }
References n, and p.
Referenced by __qsort_r().
shr()
static void shr (size_t p[2], int n) inline static
Definition at line 80 of file qsort.c.
 {
     if(n >= 8 * sizeof(size_t)) {
         n -= 8 * sizeof(size_t);
         p[0] = p[1];
         p[1] = 0;
     }
     p[0] >>= n;
     p[0] |= p[1] << (sizeof(size_t) * 8 - n);
     p[1] >>= n;
 }
References n, and p.
Referenced by __qsort_r(), and trinkle().
sift()
static void sift (unsigned char * head, size_t width, cmpfun cmp, void * arg, int pshift, size_t lp[]) static
Definition at line 92 of file qsort.c.
 {
     unsigned char *rt, *lf;
     unsigned char *ar[14 * sizeof(size_t) + 1];
     int i = 1;
     ar[0] = head;
     while(pshift > 1) {
         rt = head - width;
         lf = head - width - lp[pshift - 2];
         if(cmp(ar[0], lf, arg) >= 0 && cmp(ar[0], rt, arg) >= 0) {
             break;
         }
         if(cmp(lf, rt, arg) >= 0) {
             ar[i++] = lf;
             head = lf;
             pshift -= 1;
         } else {
             ar[i++] = rt;
             head = rt;
             pshift -= 2;
         }
     }
     cycle(width, ar, i);
 }
References cmp(), cycle(), head, i, and width.
Referenced by __qsort_r(), and trinkle().
trinkle()
static void trinkle (unsigned char * head, size_t width, cmpfun cmp, void * arg, size_t pp[2], int pshift, int trusty, size_t lp[]) static
Definition at line 119 of file qsort.c.
 {
     unsigned char *stepson,
                   *rt, *lf;
     size_t p[2];
     unsigned char *ar[14 * sizeof(size_t) + 1];
     int i = 1;
     int trail;
     p[0] = pp[0];
     p[1] = pp[1];
     ar[0] = head;
     while(p[0] != 1 || p[1] != 0) {
         stepson = head - lp[pshift];
         if(cmp(stepson, ar[0], arg) <= 0) {
             break;
         }
         if(!trusty && pshift > 1) {
             rt = head - width;
             lf = head - width - lp[pshift - 2];
             if(cmp(rt, stepson, arg) >= 0 || cmp(lf, stepson, arg) >= 0) {
                 break;
             }
         }
         ar[i++] = stepson;
         head = stepson;
         trail = pntz(p);
         shr(p, trail);
         pshift += trail;
         trusty = 0;
     }
     if(!trusty) {
         cycle(width, ar, i);
         sift(head, width, cmp, arg, pshift, lp);
     }
 }
References cmp(), cycle(), head, i, p, pntz(), shr(), sift(), and width.
Referenced by __qsort_r().
weak_alias()
weak_alias (__qsort_r , qsort_r)