Fennix Userspace: Userspace/apps/base/bash/lib/sh/strvis.c File Reference
strvis.c File Reference
#include <config.h>
#include <unistd.h>
#include "bashansi.h"
#include <stdio.h>
#include "chartypes.h"
#include "bashintl.h"
#include "shmbutil.h"
Macros
#define SAFECHAR(c) ((c) == ' ' || (c) == '\t')
#define RUBOUT 0x7f
#define CTRL_CHAR(c) ((c) < 0x20)
#define META_CHAR(c) ((c) > 0x7f && (c) <= UCHAR_MAX)
#define UNCTRL(c) (TOUPPER ((c) | 0x40))
#define UNMETA(c) ((c) & 0x7f)
Functions
int sh_charvis (char *s, size_t *sindp, size_t slen, char *ret, size_t *rindp) const
char * sh_strvis (char *string) const
Macro Definition Documentation
CTRL_CHAR
#define CTRL_CHAR (c) ((c) < 0x20)
Definition at line 40 of file strvis.c.
META_CHAR
#define META_CHAR (c) ((c) > 0x7f && (c) <= UCHAR_MAX)
Definition at line 44 of file strvis.c.
RUBOUT
#define RUBOUT 0x7f
Definition at line 36 of file strvis.c.
SAFECHAR
#define SAFECHAR (c) ((c) == ' ' || (c) == '\t')
Definition at line 33 of file strvis.c.
UNCTRL
#define UNCTRL (c) (TOUPPER ((c) | 0x40))
Definition at line 48 of file strvis.c.
UNMETA
#define UNMETA (c) ((c) & 0x7f)
Definition at line 52 of file strvis.c.
Function Documentation
sh_charvis()
int sh_charvis (char * s, size_t * sindp, size_t slen, char * ret, size_t * rindp) const
Definition at line 56 of file strvis.c.
 {
   unsigned char c;
   size_t si, ri;
   const char *send;
   DECLARE_MBSTATE;
   si = *sindp;
   ri = *rindp;
   c = s[*sindp];
 #if defined (HANDLE_MULTIBYTE)
   send = (locale_mb_cur_max > 1) ? s + slen : 0;
 #else
   send = 0;
 #endif
   if (SAFECHAR (c))
     {
       ret[ri++] = c;
       si++;
     }
   else if (c == RUBOUT)
     {
       ret[ri++] = '^';
       ret[ri++] = '?';
       si++;
     }
   else if (CTRL_CHAR (c))
     {
       ret[ri++] = '^';
       ret[ri++] = UNCTRL (c);
       si++;
     }
 #if defined (HANDLE_MULTIBYTE)
   else if (locale_utf8locale && (c & 0x80))
     COPY_CHAR_I (ret, ri, s, send, si);
   else if (locale_mb_cur_max > 1 && is_basic (c) == 0)
     COPY_CHAR_I (ret, ri, s, send, si);
 #endif
   else if (META_CHAR (c))
     {
       ret[ri++] = 'M';
       ret[ri++] = '-';
       ret[ri++] = UNMETA (c);
       si++;
     }
   else
     ret[ri++] = s[si++];
   *sindp = si;
   *rindp = ri;
   return si;
 }
References c, COPY_CHAR_I, CTRL_CHAR, DECLARE_MBSTATE, locale_mb_cur_max, locale_utf8locale, META_CHAR, ret, RUBOUT, SAFECHAR, send(), UNCTRL, and UNMETA.
Referenced by sh_strvis().
sh_strvis()
char* sh_strvis (char * string) const
Definition at line 120 of file strvis.c.
 {
   size_t slen, sind;
   char *ret;
   size_t retind, retsize;
   unsigned char c;
   DECLARE_MBSTATE;
   if (string == 0)
     return 0;
   if (*string == '\0')
     {
       if ((ret = (char *)malloc (1)) == 0)
     return 0;
       ret[0] = '\0';
       return ret;
     }
   slen = strlen (string);
   retsize = 3 * slen + 1;
   ret = (char *)malloc (retsize);
   if (ret == 0)
     return 0;
   retind = 0;
   sind = 0;
   while (string[sind])
     sind = sh_charvis (string, &sind, slen, ret, &retind);
   ret[retind] = '\0';
   return ret;
 }
References c, DECLARE_MBSTATE, malloc, ret, sh_charvis(), and strlen().
Referenced by decode_prompt_string().