Fennix Kernel: FileNode Class Reference
FileNode Class Reference
#include <filesystem.hpp>
Public Member Functions
std::string GetName ()
std::string GetPath ()
bool IsDirectory ()
bool IsCharacterDevice ()
bool IsBlockDevice ()
bool IsRegularFile ()
bool IsFIFO ()
bool IsSymbolicLink ()
bool IsSocket ()
int Lookup (const char *Name, Inode **Node)
int Create (const char *Name, mode_t Mode, Inode **Node)
int Remove (const char *Name)
int Rename (const char *OldName, const char *NewName)
ssize_t Read (auto Buffer, size_t Size, off_t Offset)
ssize_t Write (const auto Buffer, size_t Size, off_t Offset)
int Truncate (off_t Size)
int Open (int Flags, mode_t Mode)
int Close ()
int Ioctl (unsigned long Request, void *Argp)
ssize_t ReadDir (struct kdirent *Buffer, size_t Size, off_t Offset, off_t Entries)
int MkDir (const char *Name, mode_t Mode, struct Inode **Result)
int RmDir (const char *Name)
int SymLink (const char *Name, const char *Target, struct Inode **Result)
ssize_t ReadLink (auto Buffer, size_t Size)
off_t Seek (off_t Offset)
int Stat (struct kstat *Stat)
~FileNode ()=delete
Data Fields
std::string Name
std::string Path
FileNode * Parent
std::vector< FileNode * > Children
Inode * Node
FileSystemInfo * fsi
Detailed Description
Definition at line 42 of file filesystem.hpp.
Constructor & Destructor Documentation
~FileNode()
FileNode::~FileNode () delete
Member Function Documentation
Close()
int FileNode::Close () inline
Definition at line 70 of file filesystem.hpp.
 { __check_op(Close, ENOTSUP); }
References __check_op, and ENOTSUP.
Create()
int FileNode::Create (const char * Name, mode_t Mode, Inode ** Node) inline
Definition at line 63 of file filesystem.hpp.
 { __check_op(Create, EROFS, Name, Mode, Node); }
References __check_op, EROFS, Name, and Node.
GetName()
std::string FileNode::GetName ()
Definition at line 288 of file filesystem.cpp.
 {
     return this->Name;
 }
References Name.
GetPath()
std::string FileNode::GetPath ()
Definition at line 293 of file filesystem.cpp.
 {
     const char *path = this->Path.c_str();
     if (strncmp(path, "\x06root-", 6) == 0) /* FIXME: deduce the index */
     {
         path += 6;
         while (*path != '\0' && *path != '\x06')
             path++;
         if (*path == '\x06')
             path++;
     }
     else
         return this->Path;
     if (path[0] == '\0')
         return std::string(this->fsi->RootName);
     return std::string(path);
 }
References fsi, Path, FileSystemInfo::RootName, and strncmp().
Referenced by linux_chdir(), linux_getcwd(), and linux_newfstatat().
Ioctl()
int FileNode::Ioctl (unsigned long Request, void * Argp) inline
Definition at line 71 of file filesystem.hpp.
 { __check_op(Ioctl, ENOTSUP, Request, Argp); }
References __check_op, and ENOTSUP.
IsBlockDevice()
bool FileNode::IsBlockDevice () inline
Definition at line 56 of file filesystem.hpp.
 { return S_ISBLK(Node->Mode); }
References Inode::Mode, Node, and S_ISBLK.
Referenced by ColorNodeType().
IsCharacterDevice()
bool FileNode::IsCharacterDevice () inline
Definition at line 55 of file filesystem.hpp.
 { return S_ISCHR(Node->Mode); }
References Inode::Mode, Node, and S_ISCHR.
Referenced by cmd_cat(), and ColorNodeType().
IsDirectory()
bool FileNode::IsDirectory () inline
Definition at line 54 of file filesystem.hpp.
 { return S_ISDIR(Node->Mode); }
References Inode::Mode, Node, and S_ISDIR.
Referenced by cmd_cd(), cmd_ls(), ColorNodeType(), linux_open(), and tree_loop().
IsFIFO()
bool FileNode::IsFIFO () inline
Definition at line 58 of file filesystem.hpp.
 { return S_ISFIFO(Node->Mode); }
References Inode::Mode, Node, and S_ISFIFO.
Referenced by ColorNodeType().
IsRegularFile()
bool FileNode::IsRegularFile () inline
Definition at line 57 of file filesystem.hpp.
 { return S_ISREG(Node->Mode); }
References Inode::Mode, Node, and S_ISREG.
Referenced by cmd_cat(), and ColorNodeType().
IsSocket()
bool FileNode::IsSocket () inline
Definition at line 60 of file filesystem.hpp.
 { return S_ISSOCK(Node->Mode); }
References Inode::Mode, Node, and S_ISSOCK.
IsSymbolicLink()
bool FileNode::IsSymbolicLink () inline
Definition at line 59 of file filesystem.hpp.
 { return S_ISLNK(Node->Mode); }
References Inode::Mode, Node, and S_ISLNK.
Referenced by ColorNodeType(), linux_readlink(), and vfs::FileDescriptorTable::usr_stat().
Lookup()
int FileNode::Lookup (const char * Name, Inode ** Node) inline
Definition at line 62 of file filesystem.hpp.
 { __check_op(Lookup, ENOTSUP, Name, Node); }
References __check_op, ENOTSUP, Name, and Node.
MkDir()
int FileNode::MkDir (const char * Name, mode_t Mode, struct Inode ** Result) inline
Definition at line 73 of file filesystem.hpp.
 { __check_op(MkDir, EROFS, Name, Mode, Result); }
References __check_op, EROFS, and Name.
Open()
int FileNode::Open (int Flags, mode_t Mode) inline
Definition at line 69 of file filesystem.hpp.
 { __check_op(Open, ENOTSUP, Flags, Mode); }
References __check_op, ENOTSUP, and Flags.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor().
Read()
ssize_t FileNode::Read (auto Buffer, size_t Size, off_t Offset) inline
Definition at line 66 of file filesystem.hpp.
 { __check_op(Read, ENOTSUP, (void *)Buffer, Size, Offset); }
References __check_op, Driver::Buffer, ENOTSUP, Driver::Offset, and Size.
Referenced by cmd_cat(), if(), KShellThread(), KernelConsole::LateInit(), linux_uname(), Driver::Manager::LoadDriverFile(), and KernelConsole::SetTheme().
ReadDir()
ssize_t FileNode::ReadDir (struct kdirent * Buffer, size_t Size, off_t Offset, off_t Entries) inline
Definition at line 72 of file filesystem.hpp.
 { __check_op(ReadDir, ENOTSUP, Buffer, Size, Offset, Entries); }
References __check_op, Driver::Buffer, ENOTSUP, Entries, Driver::Offset, and Size.
Referenced by tree_loop().
ReadLink()
ssize_t FileNode::ReadLink (auto Buffer, size_t Size) inline
Definition at line 76 of file filesystem.hpp.
 { __check_op(ReadLink, ENOTSUP, (char *)Buffer, Size); }
References __check_op, Driver::Buffer, ENOTSUP, and Size.
Referenced by linux_readlink(), and vfs::FileDescriptorTable::usr_stat().
Remove()
int FileNode::Remove (const char * Name) inline
Definition at line 64 of file filesystem.hpp.
 { __check_op(Remove, EROFS, Name); }
References __check_op, EROFS, and Name.
Rename()
int FileNode::Rename (const char * OldName, const char * NewName) inline
Definition at line 65 of file filesystem.hpp.
 { __check_op(Rename, EROFS, OldName, NewName); }
References __check_op, and EROFS.
RmDir()
int FileNode::RmDir (const char * Name) inline
Definition at line 74 of file filesystem.hpp.
 { __check_op(RmDir, EROFS, Name); }
References __check_op, EROFS, and Name.
Seek()
off_t FileNode::Seek (off_t Offset) inline
Definition at line 77 of file filesystem.hpp.
 { __check_op(Seek, ENOTSUP, Offset); }
References __check_op, ENOTSUP, and Driver::Offset.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor().
Stat()
int FileNode::Stat (struct kstat * Stat) inline
Definition at line 78 of file filesystem.hpp.
 { __check_op(Stat, ENOTSUP, Stat); }
References __check_op, and ENOTSUP.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor(), cmd_cat(), KernelConsole::LateInit(), linux_uname(), KernelConsole::SetTheme(), vfs::FileDescriptorTable::usr_fstat(), vfs::FileDescriptorTable::usr_lstat(), and vfs::FileDescriptorTable::usr_stat().
SymLink()
int FileNode::SymLink (const char * Name, const char * Target, struct Inode ** Result) inline
Definition at line 75 of file filesystem.hpp.
 { __check_op(SymLink, EROFS, Name, Target, Result); }
References __check_op, EROFS, and Name.
Truncate()
int FileNode::Truncate (off_t Size) inline
Definition at line 68 of file filesystem.hpp.
 { __check_op(Truncate, EROFS, Size); }
References __check_op, EROFS, and Size.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor().
Write()
ssize_t FileNode::Write (const auto Buffer, size_t Size, off_t Offset) inline
Definition at line 67 of file filesystem.hpp.
 { __check_op(Write, EROFS, (const void *)Buffer, Size, Offset); }
References __check_op, Driver::Buffer, EROFS, Driver::Offset, and Size.
Referenced by WriteDiagDataToNode().
Field Documentation
Children
std::vector<FileNode *> FileNode::Children
Definition at line 47 of file filesystem.hpp.
Referenced by vfs::Virtual::CacheRecursiveSearch(), vfs::Virtual::CacheSearchReturnLast(), and vfs::Virtual::CreateCacheNode().
fsi
FileSystemInfo* FileNode::fsi
Definition at line 49 of file filesystem.hpp.
Referenced by vfs::Virtual::CacheRecursiveSearch(), vfs::Virtual::CacheSearchReturnLast(), vfs::Virtual::CreateCacheNode(), and GetPath().
Name
std::string FileNode::Name
Definition at line 45 of file filesystem.hpp.
Referenced by vfs::Virtual::CacheRecursiveSearch(), vfs::Virtual::CacheSearchReturnLast(), cmd_tree(), Create(), vfs::Virtual::CreateCacheNode(), vfs::Virtual::GetByNode(), GetName(), Driver::Manager::LoadDriverFile(), Lookup(), MkDir(), Remove(), RmDir(), Tasking::PCB::SetWorkingDirectory(), and SymLink().
Node
Inode* FileNode::Node
Definition at line 48 of file filesystem.hpp.
Referenced by Create(), vfs::Virtual::Create(), vfs::Virtual::CreateCacheNode(), vfs::Virtual::CreateLink(), vfs::Virtual::GetByPath(), vfs::Virtual::Initialize(), IsBlockDevice(), IsCharacterDevice(), IsDirectory(), IsFIFO(), IsRegularFile(), IsSocket(), IsSymbolicLink(), Lookup(), Driver::Manager::RegisterBlockDevice(), and Driver::Manager::RegisterInputDevice().
Parent
FileNode* FileNode::Parent
Definition at line 46 of file filesystem.hpp.
Referenced by vfs::Virtual::CacheRecursiveSearch(), vfs::Virtual::CacheSearchReturnLast(), vfs::Virtual::CreateCacheNode(), vfs::Virtual::GetByNode(), vfs::Virtual::GetByPath(), Driver::Manager::InitializeDaemonFS(), vfs::USTAR::ReadArchive(), and Execute::Spawn().
Path
std::string FileNode::Path
Definition at line 45 of file filesystem.hpp.
Referenced by vfs::Virtual::CacheRecursiveSearch(), cmd_ls(), vfs::Virtual::CreateCacheNode(), vfs::Virtual::CreateLink(), GetPath(), linux_openat(), vfs::USTAR::ReadArchive(), and WriteDiagDataToNode().
The documentation for this class was generated from the following files:
Kernel/include/filesystem.hpp
Kernel/storage/filesystem.cpp