Fennix Lynx Bootloader: Memory64::Virtual Class Reference
Memory64::Virtual Class Reference
#include <memory.hpp>
Data Structures
class PageMapIndexer
Public Types
enum MapType { NoMapType , FourKB , TwoMB , OneGB }
Public Member Functions
bool Check (void *VirtualAddress, PTFlag Flag=PTFlag::P, MapType Type=MapType::FourKB)
void * GetPhysical (void *VirtualAddress)
void Map (void *VirtualAddress, void *PhysicalAddress, uint64_t Flag=PTFlag::P, MapType Type=MapType::FourKB)
__always_inline void Map (void *VirtualAddress, void *PhysicalAddress, size_t Length, uint64_t Flags, MapType Type=MapType::FourKB)
__always_inline MapType OptimizedMap (void *VirtualAddress, void *PhysicalAddress, size_t Length, uint64_t Flags, bool Fit=false, bool FailOnModulo=false)
void Unmap (void *VirtualAddress, MapType Type=MapType::FourKB)
__always_inline void Unmap (void *VirtualAddress, size_t Length, MapType Type=MapType::FourKB)
__always_inline void Remap (void *VirtualAddress, void *PhysicalAddress, uint64_t Flags, MapType Type=MapType::FourKB)
Virtual (PageTable *Table=nullptr)
~Virtual ()
Private Attributes
PageTable * Table = nullptr
Detailed Description
Definition at line 474 of file memory.hpp.
Member Enumeration Documentation
MapType
enum Memory64::Virtual::MapType
Enumerator
NoMapType
FourKB
TwoMB
OneGB
Definition at line 480 of file memory.hpp.
         {
             NoMapType,
             FourKB,
             TwoMB,
             OneGB
         };
Constructor & Destructor Documentation
Virtual()
Memory64::Virtual::Virtual (PageTable * Table = nullptr)
Definition at line 304 of file VirtualMemoryManager.cpp.
     {
         if (Table)
             this->Table = Table;
         else
         {
             asmv("movl %%cr3, %0" // FIXME: movq
                  : "=r"(this->Table));
         }
     }
References asmv, and Table.
~Virtual()
Memory::Virtual::~Virtual ()
Definition at line 315 of file VirtualMemoryManager.cpp.
 {}
Member Function Documentation
Check()
bool Memory64::Virtual::Check (void * VirtualAddress, PTFlag Flag = PTFlag::P, MapType Type = MapType::FourKB)
Definition at line 58 of file VirtualMemoryManager.cpp.
     {
         // 0x1000 aligned
         uintptr_t Address = (uintptr_t)VirtualAddress;
         Address &= 0xFFFFFFFFFFFFF000;
         PageMapIndexer Index = PageMapIndexer(Address);
         PageMapLevel4 PML4 = this->Table->Entries[Index.PMLIndex];
         PageDirectoryPointerTableEntryPtr *PDPTE = nullptr;
         PageDirectoryEntryPtr *PDE = nullptr;
         PageTableEntryPtr *PTE = nullptr;
         if ((PML4.raw & Flag) > 0)
         {
             PDPTE = (PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4.GetAddress() << 12);
             if (PDPTE)
             {
                 if ((PDPTE->Entries[Index.PDPTEIndex].Present))
                 {
                     if (Type == MapType::OneGB && PDPTE->Entries[Index.PDPTEIndex].PageSize)
                         return true;
                     PDE = (PageDirectoryEntryPtr *)((uintptr_t)PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
                     if (PDE)
                     {
                         if (Type == MapType::TwoMB && PDE->Entries[Index.PDEIndex].PageSize)
                             return true;
                         if ((PDE->Entries[Index.PDEIndex].Present))
{
                             PTE = (PageTableEntryPtr *)((uintptr_t)PDE->Entries[Index.PDEIndex].GetAddress() << 12);
                             if (PTE)
{
                                 if ((PTE->Entries[Index.PTEIndex].Present))
                                     return true;
                             }
                         }
                     }
                 }
             }
         }
         return false;
     }
References Memory64::PageTableEntryPtr::Entries, Memory64::PageDirectoryEntryPtr::Entries, Memory64::PageDirectoryPointerTableEntryPtr::Entries, Memory64::PageTable::Entries, Memory64::PageDirectoryEntry::GetAddress(), Memory64::PageDirectoryPointerTableEntry::GetAddress(), Memory64::PageMapLevel4::GetAddress(), Memory64::Virtual::PageMapIndexer::PDEIndex, Memory64::Virtual::PageMapIndexer::PDPTEIndex, Memory64::Virtual::PageMapIndexer::PMLIndex, Memory64::Virtual::PageMapIndexer::PTEIndex, Memory64::PageMapLevel4::raw, and Table.
Referenced by Map().
GetPhysical()
void * Memory64::Virtual::GetPhysical (void * VirtualAddress)
Definition at line 103 of file VirtualMemoryManager.cpp.
     {
         // 0x1000 aligned
         uintptr_t Address = (uintptr_t)VirtualAddress;
         Address &= 0xFFFFFFFFFFFFF000;
         PageMapIndexer Index = PageMapIndexer(Address);
         PageMapLevel4 PML4 = this->Table->Entries[Index.PMLIndex];
         PageDirectoryPointerTableEntryPtr *PDPTE = nullptr;
         PageDirectoryEntryPtr *PDE = nullptr;
         PageTableEntryPtr *PTE = nullptr;
         if (PML4.Present)
         {
             PDPTE = (PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4.GetAddress() << 12);
             if (PDPTE)
             {
                 if (PDPTE->Entries[Index.PDPTEIndex].Present)
                 {
                     if (PDPTE->Entries[Index.PDPTEIndex].PageSize)
                         return (void *)((uintptr_t)PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
                     PDE = (PageDirectoryEntryPtr *)((uintptr_t)PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
                     if (PDE)
                     {
                         if (PDE->Entries[Index.PDEIndex].Present)
{
                             if (PDE->Entries[Index.PDEIndex].PageSize)
                                 return (void *)((uintptr_t)PDE->Entries[Index.PDEIndex].GetAddress() << 12);
                             PTE = (PageTableEntryPtr *)((uintptr_t)PDE->Entries[Index.PDEIndex].GetAddress() << 12);
                             if (PTE)
{
                                 if (PTE->Entries[Index.PTEIndex].Present)
                                     return (void *)((uintptr_t)PTE->Entries[Index.PTEIndex].GetAddress() << 12);
                             }
                         }
                     }
                 }
             }
         }
         return nullptr;
     }
References Memory64::PageTableEntryPtr::Entries, Memory64::PageDirectoryEntryPtr::Entries, Memory64::PageDirectoryPointerTableEntryPtr::Entries, Memory64::PageTable::Entries, Memory64::PageTableEntry::GetAddress(), Memory64::PageDirectoryEntry::GetAddress(), Memory64::PageDirectoryPointerTableEntry::GetAddress(), Memory64::PageMapLevel4::GetAddress(), Memory64::Virtual::PageMapIndexer::PDEIndex, Memory64::Virtual::PageMapIndexer::PDPTEIndex, Memory64::Virtual::PageMapIndexer::PMLIndex, Memory64::Virtual::PageMapIndexer::PTEIndex, and Table.
Map() [1/2]
__always_inline void Memory64::Virtual::Map (void * VirtualAddress, void * PhysicalAddress, size_t Length, uint64_t Flags, MapType Type = MapType::FourKB) inline
Definition at line 513 of file memory.hpp.
         {
             int PageSize = PAGE_SIZE_4K;
             if (Type == MapType::TwoMB)
                 PageSize = PAGE_SIZE_2M;
             else if (Type == MapType::OneGB)
                 PageSize = PAGE_SIZE_1G;
             for (uintptr_t i = 0; i < Length; i += PageSize)
                 this->Map((void *)((uintptr_t)VirtualAddress + i), (void *)((uintptr_t)PhysicalAddress + i), Flags, Type);
         }
References Length, Map(), PAGE_SIZE_1G, PAGE_SIZE_2M, and PAGE_SIZE_4K.
Map() [2/2]
void Memory64::Virtual::Map (void * VirtualAddress, void * PhysicalAddress, uint64_t Flag = PTFlag::P, MapType Type = MapType::FourKB)
Definition at line 148 of file VirtualMemoryManager.cpp.
     {
         if (unlikely(!this->Table))
         {
             error("No page table");
             return;
         }
         Flags |= PTFlag::P;
         PageMapIndexer Index = PageMapIndexer((uintptr_t)VirtualAddress);
         // Clear any flags that are not 1 << 0 (Present) - 1 << 5 (Accessed) because rest are for page table entries only
         uint64_t DirectoryFlags = Flags & 0x3F;
         PageMapLevel4 *PML4 = &this->Table->Entries[Index.PMLIndex];
         PageDirectoryPointerTableEntryPtr *PDPTEPtr = nullptr;
         if (!PML4->Present)
         {
             PDPTEPtr = (PageDirectoryPointerTableEntryPtr *)KernelAllocator64.RequestPages(TO_PAGES(sizeof(PageDirectoryPointerTableEntryPtr) + 1));
             memset(PDPTEPtr, 0, sizeof(PageDirectoryPointerTableEntryPtr));
             PML4->Present = true;
             PML4->SetAddress((uintptr_t)PDPTEPtr >> 12);
         }
         else
             PDPTEPtr = (PageDirectoryPointerTableEntryPtr *)(PML4->GetAddress() << 12);
         PML4->raw |= DirectoryFlags;
         PageDirectoryPointerTableEntry *PDPTE = &PDPTEPtr->Entries[Index.PDPTEIndex];
         if (Type == MapType::OneGB)
         {
             PDPTE->raw |= Flags;
             PDPTE->PageSize = true;
             PDPTE->SetAddress((uintptr_t)PhysicalAddress >> 12);
             debug("Mapped 1GB page at %p to %p", VirtualAddress, PhysicalAddress);
             return;
         }
         PageDirectoryEntryPtr *PDEPtr = nullptr;
         if (!PDPTE->Present)
         {
             PDEPtr = (PageDirectoryEntryPtr *)KernelAllocator64.RequestPages(TO_PAGES(sizeof(PageDirectoryEntryPtr) + 1));
             memset(PDEPtr, 0, sizeof(PageDirectoryEntryPtr));
             PDPTE->Present = true;
             PDPTE->SetAddress((uintptr_t)PDEPtr >> 12);
         }
         else
             PDEPtr = (PageDirectoryEntryPtr *)(PDPTE->GetAddress() << 12);
         PDPTE->raw |= DirectoryFlags;
         PageDirectoryEntry *PDE = &PDEPtr->Entries[Index.PDEIndex];
         if (Type == MapType::TwoMB)
         {
             PDE->raw |= Flags;
             PDE->PageSize = true;
             PDE->SetAddress((uintptr_t)PhysicalAddress >> 12);
             debug("Mapped 2MB page at %p to %p", VirtualAddress, PhysicalAddress);
             return;
         }
         PageTableEntryPtr *PTEPtr = nullptr;
         if (!PDE->Present)
         {
             PTEPtr = (PageTableEntryPtr *)KernelAllocator64.RequestPages(TO_PAGES(sizeof(PageTableEntryPtr) + 1));
             memset(PTEPtr, 0, sizeof(PageTableEntryPtr));
             PDE->Present = true;
             PDE->SetAddress((uintptr_t)PTEPtr >> 12);
         }
         else
             PTEPtr = (PageTableEntryPtr *)(PDE->GetAddress() << 12);
         PDE->raw |= DirectoryFlags;
         PageTableEntry *PTE = &PTEPtr->Entries[Index.PTEIndex];
         PTE->Present = true;
         PTE->raw |= Flags;
         PTE->SetAddress((uintptr_t)PhysicalAddress >> 12);
         asmv("invlpg (%0)" ::"r"(VirtualAddress)
              : "memory");
 #ifdef DEBUG
 /* https://stackoverflow.com/a/3208376/9352057 */
 #define BYTE_TO_BINARY_PATTERN "%c%c%c%c%c%c%c%c"
 #define BYTE_TO_BINARY(byte)       \
     (byte & 0x80 ? '1' : '0'),     \
         (byte & 0x40 ? '1' : '0'), \
         (byte & 0x20 ? '1' : '0'), \
         (byte & 0x10 ? '1' : '0'), \
         (byte & 0x08 ? '1' : '0'), \
         (byte & 0x04 ? '1' : '0'), \
         (byte & 0x02 ? '1' : '0'), \
         (byte & 0x01 ? '1' : '0')
         if (!this->Check(VirtualAddress, (PTFlag)Flags, Type)) // quick workaround just to see where it fails
             warn("Failed to map v:%#lx p:%#lx with flags: " BYTE_TO_BINARY_PATTERN, VirtualAddress, PhysicalAddress, BYTE_TO_BINARY(Flags));
 #endif
     }
References asmv, Check(), debug, Memory64::PageTableEntryPtr::Entries, Memory64::PageDirectoryEntryPtr::Entries, Memory64::PageDirectoryPointerTableEntryPtr::Entries, Memory64::PageTable::Entries, error, Memory64::PageDirectoryEntry::GetAddress(), Memory64::PageDirectoryPointerTableEntry::GetAddress(), Memory64::PageMapLevel4::GetAddress(), KernelAllocator64, memset(), P, Memory64::Virtual::PageMapIndexer::PDEIndex, Memory64::Virtual::PageMapIndexer::PDPTEIndex, Memory64::Virtual::PageMapIndexer::PMLIndex, Memory64::Virtual::PageMapIndexer::PTEIndex, Memory64::PageTableEntry::raw, Memory64::PageDirectoryEntry::raw, Memory64::PageDirectoryPointerTableEntry::raw, Memory64::PageMapLevel4::raw, Memory64::Physical::RequestPages(), Memory64::PageTableEntry::SetAddress(), Memory64::PageDirectoryEntry::SetAddress(), Memory64::PageDirectoryPointerTableEntry::SetAddress(), Memory64::PageMapLevel4::SetAddress(), Table, TO_PAGES, unlikely, and warn.
Referenced by Map(), OptimizedMap(), and Remap().
OptimizedMap()
__always_inline MapType Memory64::Virtual::OptimizedMap (void * VirtualAddress, void * PhysicalAddress, size_t Length, uint64_t Flags, bool Fit = false, bool FailOnModulo = false) inline
Definition at line 526 of file memory.hpp.
         {
             if (unlikely(Fit))
             {
                 while (Length >= PAGE_SIZE_1G)
                 {
                     this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Virtual::MapType::OneGB);
                     VirtualAddress = (void *)((uintptr_t)VirtualAddress + PAGE_SIZE_1G);
                     PhysicalAddress = (void *)((uintptr_t)PhysicalAddress + PAGE_SIZE_1G);
                     Length -= PAGE_SIZE_1G;
                 }
                 while (Length >= PAGE_SIZE_2M)
                 {
                     this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Virtual::MapType::TwoMB);
                     VirtualAddress = (void *)((uintptr_t)VirtualAddress + PAGE_SIZE_2M);
                     PhysicalAddress = (void *)((uintptr_t)PhysicalAddress + PAGE_SIZE_2M);
                     Length -= PAGE_SIZE_2M;
                 }
                 while (Length >= PAGE_SIZE_4K)
                 {
                     this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Virtual::MapType::FourKB);
                     VirtualAddress = (void *)((uintptr_t)VirtualAddress + PAGE_SIZE_4K);
                     PhysicalAddress = (void *)((uintptr_t)PhysicalAddress + PAGE_SIZE_4K);
                     Length -= PAGE_SIZE_4K;
                 }
                 return Virtual::MapType::FourKB;
             }
             Virtual::MapType Type = Virtual::MapType::FourKB;
             if (Length >= PAGE_SIZE_1G)
             {
                 Type = Virtual::MapType::OneGB;
                 if (Length % PAGE_SIZE_1G != 0)
                 {
                     warn("Length is not a multiple of 1GB.");
                     if (FailOnModulo)
                         return Virtual::MapType::NoMapType;
                 }
             }
             else if (Length >= PAGE_SIZE_2M)
             {
                 Type = Virtual::MapType::TwoMB;
                 if (Length % PAGE_SIZE_2M != 0)
                 {
                     warn("Length is not a multiple of 2MB.");
                     if (FailOnModulo)
                         return Virtual::MapType::NoMapType;
                 }
             }
             this->Map(VirtualAddress, PhysicalAddress, Length, Flags, Type);
             return Type;
         }
References Length, Map(), PAGE_SIZE_1G, PAGE_SIZE_2M, PAGE_SIZE_4K, unlikely, and warn.
Remap()
__always_inline void Memory64::Virtual::Remap (void * VirtualAddress, void * PhysicalAddress, uint64_t Flags, MapType Type = MapType::FourKB) inline
Definition at line 599 of file memory.hpp.
         {
             this->Unmap(VirtualAddress, Type);
             this->Map(VirtualAddress, PhysicalAddress, Flags, Type);
         }
References Map(), and Unmap().
Unmap() [1/2]
void Memory64::Virtual::Unmap (void * VirtualAddress, MapType Type = MapType::FourKB)
Definition at line 245 of file VirtualMemoryManager.cpp.
     {
         if (!this->Table)
         {
             error("No page table");
             return;
         }
         PageMapIndexer Index = PageMapIndexer((uintptr_t)VirtualAddress);
         PageMapLevel4 *PML4 = &this->Table->Entries[Index.PMLIndex];
         if (!PML4->Present)
         {
             error("Page %#lx not present", PML4->GetAddress());
             return;
         }
         PageDirectoryPointerTableEntryPtr *PDPTEPtr = (PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4->Address << 12);
         PageDirectoryPointerTableEntry *PDPTE = &PDPTEPtr->Entries[Index.PDPTEIndex];
         if (!PDPTE->Present)
         {
             error("Page %#lx not present", PDPTE->GetAddress());
             return;
         }
         if (Type == MapType::OneGB && PDPTE->PageSize)
         {
             PDPTE->Present = false;
             return;
         }
         PageDirectoryEntryPtr *PDEPtr = (PageDirectoryEntryPtr *)((uintptr_t)PDPTE->Address << 12);
         PageDirectoryEntry *PDE = &PDEPtr->Entries[Index.PDEIndex];
         if (!PDE->Present)
         {
             error("Page %#lx not present", PDE->GetAddress());
             return;
         }
         if (Type == MapType::TwoMB && PDE->PageSize)
         {
             PDE->Present = false;
             return;
         }
         PageTableEntryPtr *PTEPtr = (PageTableEntryPtr *)((uintptr_t)PDE->Address << 12);
         PageTableEntry PTE = PTEPtr->Entries[Index.PTEIndex];
         if (!PTE.Present)
         {
             error("Page %#lx not present", PTE.GetAddress());
             return;
         }
         PTE.Present = false;
         PTEPtr->Entries[Index.PTEIndex] = PTE;
         asmv("invlpg (%0)" ::"r"(VirtualAddress)
              : "memory");
     }
References asmv, Memory64::PageTableEntryPtr::Entries, Memory64::PageDirectoryEntryPtr::Entries, Memory64::PageDirectoryPointerTableEntryPtr::Entries, Memory64::PageTable::Entries, error, Memory64::PageTableEntry::GetAddress(), Memory64::PageDirectoryEntry::GetAddress(), Memory64::PageDirectoryPointerTableEntry::GetAddress(), Memory64::PageMapLevel4::GetAddress(), Memory64::Virtual::PageMapIndexer::PDEIndex, Memory64::Virtual::PageMapIndexer::PDPTEIndex, Memory64::Virtual::PageMapIndexer::PMLIndex, Memory64::Virtual::PageMapIndexer::PTEIndex, and Table.
Referenced by Remap(), and Unmap().
Unmap() [2/2]
__always_inline void Memory64::Virtual::Unmap (void * VirtualAddress, size_t Length, MapType Type = MapType::FourKB) inline
Definition at line 586 of file memory.hpp.
         {
             int PageSize = PAGE_SIZE_4K;
             if (Type == MapType::TwoMB)
                 PageSize = PAGE_SIZE_2M;
             else if (Type == MapType::OneGB)
                 PageSize = PAGE_SIZE_1G;
             for (uintptr_t i = 0; i < Length; i += PageSize)
                 this->Unmap((void *)((uintptr_t)VirtualAddress + i), Type);
         }
References Length, PAGE_SIZE_1G, PAGE_SIZE_2M, PAGE_SIZE_4K, and Unmap().
Field Documentation
Table
PageTable* Memory64::Virtual::Table = nullptr private
Definition at line 477 of file memory.hpp.
Referenced by Check(), GetPhysical(), Map(), Unmap(), and Virtual().
The documentation for this class was generated from the following files:
Lynx/FennixLoader/include/memory.hpp
Lynx/FennixLoader/Memory/VirtualMemoryManager.cpp