Fennix Userspace: Userspace/apps/base/busybox/libbb/read_printf.c File Reference
read_printf.c File Reference
#include "libbb.h"
Functions
ssize_t FAST_FUNC nonblock_immune_read (int fd, void *buf, size_t count)
char *FAST_FUNC xmalloc_reads (int fd, size_t *maxsz_p)
void *FAST_FUNC xmalloc_read_with_initial_buf (int fd, size_t *maxsz_p, char *buf, size_t total)
void *FAST_FUNC xmalloc_read (int fd, size_t *maxsz_p)
void *FAST_FUNC xmalloc_open_read_close (const char *filename, size_t *maxsz_p)
void FAST_FUNC xread (int fd, void *buf, size_t count)
unsigned char FAST_FUNC xread_char (int fd)
void *FAST_FUNC xmalloc_xopen_read_close (const char *filename, size_t *maxsz_p)
Function Documentation
nonblock_immune_read()
ssize_t FAST_FUNC nonblock_immune_read (int fd, void * buf, size_t count)
Definition at line 48 of file read_printf.c.
 {
     struct pollfd pfd[1];
     ssize_t n;
     while (1) {
         n = safe_read(fd, buf, count);
         if (n >= 0 || errno != EAGAIN)
             return n;
         /* fd is in O_NONBLOCK mode. Wait using poll and repeat */
         pfd[0].fd = fd;
         pfd[0].events = POLLIN;
         /* note: safe_poll pulls in printf */
         safe_poll(pfd, 1, -1);
     }
 }
References buf, count, EAGAIN, errno, fd, n, pfd, POLLIN, safe_poll(), and safe_read().
Referenced by expbackq(), preadfd(), and xmalloc_reads().
xmalloc_open_read_close()
void* FAST_FUNC xmalloc_open_read_close (const char * filename, size_t * maxsz_p)
Definition at line 200 of file read_printf.c.
 {
     char *buf;
     int fd;
     fd = open(filename, O_RDONLY);
     if (fd < 0)
         return NULL;
     buf = xmalloc_read(fd, maxsz_p);
     close(fd);
     return buf;
 }
References buf, close(), fd, filename, NULL, O_RDONLY, open(), and xmalloc_read().
Referenced by finalize(), parse_and_add_kcmdline_module_options(), vi_main(), and xmalloc_xopen_read_close().
xmalloc_read()
void* FAST_FUNC xmalloc_read (int fd, size_t * maxsz_p)
Definition at line 148 of file read_printf.c.
 {
     return xmalloc_read_with_initial_buf(fd, maxsz_p, NULL, 0);
 }
References fd, NULL, and xmalloc_read_with_initial_buf().
Referenced by awk_main(), download_one_url(), sysctl_act_on_setting(), wall_main(), and xmalloc_open_read_close().
xmalloc_read_with_initial_buf()
void* FAST_FUNC xmalloc_read_with_initial_buf (int fd, size_t * maxsz_p, char * buf, size_t total)
Definition at line 105 of file read_printf.c.
 {
     size_t size, rd_size;
     size_t to_read;
     struct stat st;
     to_read = maxsz_p ? *maxsz_p : (INT_MAX - 4095); /* max to read */
     /* Estimate file size */
     st.st_size = 0; /* in case fstat fails, assume 0 */
     fstat(fd, &st);
     /* /proc/N/stat files report st_size 0 */
     /* In order to make such files readable, we add small const */
     size = (st.st_size | 0x3ff) + 1;
     while (1) {
         if (to_read < size)
             size = to_read;
         buf = xrealloc(buf, total + size + 1);
         rd_size = full_read(fd, buf + total, size);
         if ((ssize_t)rd_size == (ssize_t)(-1)) { /* error */
             free(buf);
             return NULL;
         }
         total += rd_size;
         if (rd_size < size) /* EOF */
             break;
         if (to_read <= rd_size)
             break;
         to_read -= rd_size;
         /* grow by 1/8, but in [1k..64k] bounds */
         size = ((total / 8) | 0x3ff) + 1;
         if (size > 64*1024)
             size = 64*1024;
     }
     buf = xrealloc(buf, total + 1);
     buf[total] = '\0';
     if (maxsz_p)
         *maxsz_p = total;
     return buf;
 }
References buf, fd, free, fstat(), full_read(), INT_MAX, NULL, size, to_read, total, and xrealloc.
Referenced by xmalloc_read().
xmalloc_reads()
char* FAST_FUNC xmalloc_reads (int fd, size_t * maxsz_p)
Definition at line 68 of file read_printf.c.
 {
     char *p;
     char *buf = NULL;
     size_t sz = 0;
     size_t maxsz = maxsz_p ? *maxsz_p : (INT_MAX - 4095);
     goto jump_in;
     while (sz < maxsz) {
         if ((size_t)(p - buf) == sz) {
  jump_in:
             buf = xrealloc(buf, sz + 128);
             p = buf + sz;
             sz += 128;
         }
         if (nonblock_immune_read(fd, p, 1) != 1) {
             /* EOF/error */
             if (p == buf) { /* we read nothing */
                 free(buf);
                 return NULL;
             }
             break;
         }
         if (*p == '\n')
             break;
         p++;
     }
     *p = '\0';
     if (maxsz_p)
         *maxsz_p  = p - buf;
     p++;
     return xrealloc(buf, p - buf);
 }
References buf, fd, free, INT_MAX, nonblock_immune_read(), NULL, p, and xrealloc.
Referenced by acpid_main(), apply_one_hunk(), get_cred_or_die(), and xmalloc_read_stdin().
xmalloc_xopen_read_close()
void* FAST_FUNC xmalloc_xopen_read_close (const char * filename, size_t * maxsz_p)
Definition at line 232 of file read_printf.c.
 {
     void *buf = xmalloc_open_read_close(filename, maxsz_p);
     if (!buf)
         bb_perror_msg_and_die("can't read '%s'", filename);
     return buf;
 }
References bb_perror_msg_and_die(), buf, filename, and xmalloc_open_read_close().
Referenced by chat_main(), lpd_main(), and readprofile_main().
xread()
void FAST_FUNC xread (int fd, void * buf, size_t count)
Definition at line 215 of file read_printf.c.
 {
     if (count) {
         ssize_t size = full_read(fd, buf, count);
         if ((size_t)size != count)
             bb_simple_error_msg_and_die("short read");
     }
 }
References bb_simple_error_msg_and_die(), buf, count, fd, full_read(), and size.
Referenced by check_magic(), data_extract_to_buffer(), dumpleases_main(), f_read(), flashcp_main(), get_header_ar(), get_header_cpio(), get_header_tar(), last_main(), loadkmap_main(), lzo_decompress(), nbdclient_main(), process_pax_hdr(), read32(), rpm_gettags(), screen_read_close(), tune2fs_main(), unpack_ar_archive(), unzip_main(), volname_main(), and xread_char().
xread_char()
unsigned char FAST_FUNC xread_char (int fd)
Definition at line 225 of file read_printf.c.
 {
     char tmp;
     xread(fd, &tmp, 1);
     return tmp;
 }
References fd, and xread().
Referenced by get_header_ar().