Fennix: Userspace/musl/include/string.h File Reference
string.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Macros
#define NULL ((void*)0)
#define __NEED_size_t
Functions
void * memcpy (void *__restrict, const void *__restrict, size_t)
void * memmove (void *, const void *, size_t)
void * memset (void *, int, size_t)
int memcmp (const void *, const void *, size_t)
void * memchr (const void *, int, size_t)
char * strcpy (char *__restrict, const char *__restrict)
char * strncpy (char *__restrict, const char *__restrict, size_t)
char * strcat (char *__restrict, const char *__restrict)
char * strncat (char *__restrict, const char *__restrict, size_t)
int strcmp (const char *, const char *)
int strncmp (const char *, const char *, size_t)
int strcoll (const char *, const char *)
size_t strxfrm (char *__restrict, const char *__restrict, size_t)
char * strchr (const char *, int)
char * strrchr (const char *, int)
size_t strcspn (const char *, const char *)
size_t strspn (const char *, const char *)
char * strpbrk (const char *, const char *)
char * strstr (const char *, const char *)
char * strtok (char *__restrict, const char *__restrict)
size_t strlen (const char *)
char * strerror (int)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 18 of file string.h.
NULL
#define NULL ((void*)0)
Definition at line 15 of file string.h.
Function Documentation
memchr()
void* memchr (const void * src, int c, size_t n)
Definition at line 11 of file memchr.c.
 {
     const unsigned char *s = src;
     c = (unsigned char)c;
 #ifdef __GNUC__
     for (; ((uintptr_t)s & ALIGN) && n && *s != c; s++, n--);
     if (n && *s != c) {
         typedef size_t __attribute__((__may_alias__)) word;
         const word *w;
         size_t k = ONES * c;
         for (w = (const void *)s; n>=SS && !HASZERO(*w^k); w++, n-=SS);
         s = (const void *)w;
     }
 #endif
     for (; n && *s != c; s++, n--);
     return n ? (void *)s : 0;
 }
References __attribute__, ALIGN, c, HASZERO, k, n, ONES, s, src, SS, and w.
Referenced by awk_getline(), complement(), dcngettext(), end_line(), fgetln(), fgets(), findString(), getdelim(), inotifyd_main(), logdir_open(), memmem(), modinfo(), parse_dep_file(), process_includes(), readLines(), refresh(), safe_write_double_iac(), safe_write_to_pty_decode_iac(), split_main(), string_read(), strnlen(), svlogd_main(), and twoway_strstr().
memcmp()
int memcmp (const void * vl, const void * vr, size_t n)
Definition at line 30 of file convert.cpp.
 {
     const unsigned char *l = (unsigned char *)vl, *r = (unsigned char *)vr;
     for (; n && *l == *r; n--, l++, r++)
         ;
     return n ? *l - *r : 0;
 }
References l, and n.
memcpy()
void* memcpy (void * __restrict, const void * __restrict, size_t len)
Definition at line 1087 of file convert.cpp.
 {
     void *ret = __memcpy_chk(dest, src, len, __builtin_object_size(dest, 0));
     return ret;
 }
References __attribute__, __memcpy_chk(), len, n, RS, s, src, w, and x.
Referenced by memmove(), and memmove_unsafe().
memmove()
void* memmove (void * dest, const void * src, size_t n)
Definition at line 290 of file memop.c.
 {
 #ifdef __GNUC__
     typedef __attribute__((__may_alias__)) size_t WT;
 #define WS (sizeof(WT))
 #endif
     char *d = dest;
     const char *s = src;
     if (d == s)
         return d;
     if ((uintptr_t)s - (uintptr_t)d - n <= -2 * n)
         return memcpy(d, s, n);
     if (d < s)
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)d % WS)
             {
                 if (!n--)
                     return dest;
                 *d++ = *s++;
             }
             for (; n >= WS; n -= WS, d += WS, s += WS)
                 *(WT *)d = *(WT *)s;
         }
 #endif
         for (; n; n--)
             *d++ = *s++;
     }
     else
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)(d + n) % WS)
             {
                 if (!n--)
                     return dest;
                 d[n] = s[n];
             }
             while (n >= WS)
                 n -= WS, *(WT *)(d + n) = *(WT *)(s + n);
         }
 #endif
         while (n)
             n--, d[n] = s[n];
     }
     return dest;
 }
References memcpy, n, s, and src.
memset()
void* memset (void * dest, int val, size_t len)
Definition at line 1094 of file convert.cpp.
 {
     void *ret = __memset_chk(dest, val, len, __builtin_object_size(dest, 0));
     return ret;
 }
References __attribute__, __memset_chk(), c, i, k, len, n, p, s, and val.
strcat()
char* strcat (char * __restrict, const char * __restrict)
strchr()
char* strchr (const char * String, int Char)
Definition at line 173 of file convert.cpp.
 {
     assert(String != NULL);
     while (*String != (char)Char)
     {
         if (!*String++)
             return 0;
     }
     return (char *)String;
 }
References __strchrnul(), c, i, len, NULL, s, and strlen().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 135 of file convert.cpp.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
References l.
Referenced by ELFLookupSymbol().
strcoll()
int strcoll (const char * l, const char * r)
Definition at line 10 of file strcoll.c.
 {
     return __strcoll_l(l, r, CURRENT_LOCALE);
 }
References __strcoll_l(), CURRENT_LOCALE, and l.
Referenced by _rl_qsort_string_compare(), alphasort(), binary_test(), compare(), compare_keys(), strvec_posixcmp(), and strvec_strcmp().
strcpy()
char* strcpy (char * __restrict, const char * __restrict)
strcspn()
size_t strcspn (const char * s, const char * c)
Definition at line 6 of file strcspn.c.
 {
     const char *a = s;
     size_t byteset[32/sizeof(size_t)];
     if (!c[0] || !c[1]) return __strchrnul(s, *c)-a;
     memset(byteset, 0, sizeof byteset);
     for (; *c && BITOP(byteset, *(unsigned char *)c, |=); c++);
     for (; *s && !BITOP(byteset, *(unsigned char *)s, &); s++);
     return s-a;
 }
References __strchrnul(), BITOP, c, memset, and s.
Referenced by _nl_init_domain_conv(), add_split_dependencies(), argstr(), awk_split(), catopen(), conf_write(), config_read(), csvsplit(), dsvsplit(), encode_then_append_var_plusminus(), eval6(), expand_on_ifs(), expand_one_var(), extract_filename(), fcvt(), get_header_ar(), get_irqcpu_nr(), get_status(), index_status_file(), legal_pathopt(), new_process_module_arguments(), next_word(), o_addqblock(), padvance_magic(), parse_cmd_args(), path_open(), print_ascii(), query(), read_iface_state(), shell_builtin_read(), singlemount(), strpbrk(), strsep(), strtok(), strtok_r(), summarize(), verbose_log(), and write_status_file().
strerror()
char* strerror (int errnum)
Definition at line 35 of file errno.cpp.
 {
     if (errnum < 0)
         errnum = -errnum;
     switch (errnum)
     {
     case 0:
         return "Success";
     case EPERM:
         return "Operation not permitted";
     case ENOENT:
         return "No such file or directory";
     case ESRCH:
         return "No such process";
     case EINTR:
         return "Interrupted system call";
     case EIO:
         return "Input/output error";
     case ENXIO:
         return "No such device or address";
     case E2BIG:
         return "Argument list too long";
     case ENOEXEC:
         return "Exec format error";
     case EBADF:
         return "Bad file descriptor";
     case ECHILD:
         return "No child processes";
     case EAGAIN:
         return "Resource temporarily unavailable";
     case ENOMEM:
         return "Cannot allocate memory";
     case EACCES:
         return "Permission denied";
     case EFAULT:
         return "Bad address";
     case ENOTBLK:
         return "Block device required";
     case EBUSY:
         return "Device or resource busy";
     case EEXIST:
         return "File exists";
     case EXDEV:
         return "Invalid cross-device link";
     case ENODEV:
         return "No such device";
     case ENOTDIR:
         return "Not a directory";
     case EISDIR:
         return "Is a directory";
     case EINVAL:
         return "Invalid argument";
     case ENFILE:
         return "Too many open files in system";
     case EMFILE:
         return "Too many open files";
     case ENOTTY:
         return "Inappropriate ioctl for device";
     case ETXTBSY:
         return "Text file busy";
     case EFBIG:
         return "File too large";
     case ENOSPC:
         return "No space left on device";
     case ESPIPE:
         return "Illegal seek";
     case EROFS:
         return "Read-only file system";
     case EMLINK:
         return "Too many links";
     case EPIPE:
         return "Broken pipe";
     case EDOM:
         return "Numerical argument out of domain";
     case ERANGE:
         return "Numerical result out of range";
     case EDEADLK:
         return "Resource deadlock avoided";
     case ENAMETOOLONG:
         return "File name too long";
     case ENOLCK:
         return "No locks available";
     case ENOSYS:
         return "Function not implemented";
     case ENOTEMPTY:
         return "Directory not empty";
     case ELOOP:
         return "Too many levels of symbolic links";
     case ENOMSG:
         return "No message of desired type";
     case EIDRM:
         return "Identifier removed";
     case ECHRNG:
         return "Channel number out of range";
     case EL2NSYNC:
         return "Level 2 not synchronized";
     case EL3HLT:
         return "Level 3 halted";
     case EL3RST:
         return "Level 3 reset";
     case ELNRNG:
         return "Link number out of range";
     case EUNATCH:
         return "Protocol driver not attached";
     case ENOCSI:
         return "No CSI structure available";
     case EL2HLT:
         return "Level 2 halted";
     case EBADE:
         return "Invalid exchange";
     case EBADR:
         return "Invalid request descriptor";
     case EXFULL:
         return "Exchange full";
     case ENOANO:
         return "No anode";
     case EBADRQC:
         return "Invalid request code";
     case EBADSLT:
         return "Invalid slot";
     case EBFONT:
         return "Bad font file format";
     case ENOSTR:
         return "Device not a stream";
     case ENODATA:
         return "No data available";
     case ETIME:
         return "Timer expired";
     case ENOSR:
         return "Out of streams resources";
     case ENONET:
         return "Machine is not on the network";
     case ENOPKG:
         return "Package not installed";
     case EREMOTE:
         return "Object is remote";
     case ENOLINK:
         return "Link has been severed";
     case EADV:
         return "Advertise error";
     case ESRMNT:
         return "Srmount error";
     case ECOMM:
         return "Communication error on send";
     case EPROTO:
         return "Protocol error";
     case EMULTIHOP:
         return "Multihop attempted";
     case EDOTDOT:
         return "RFS specific error";
     case EBADMSG:
         return "Bad message";
     case EOVERFLOW:
         return "Value too large for defined data type";
     case ENOTUNIQ:
         return "Name not unique on network";
     case EBADFD:
         return "File descriptor in bad state";
     case EREMCHG:
         return "Remote address changed";
     case ELIBACC:
         return "Can not access a needed shared library";
     case ELIBBAD:
         return "Accessing a corrupted shared library";
     case ELIBSCN:
         return ".lib section in a.out corrupted";
     case ELIBMAX:
         return "Attempting to link in too many shared libraries";
     case ELIBEXEC:
         return "Cannot exec a shared library directly";
     case EILSEQ:
         return "Illegal byte sequence";
     case ERESTART:
         return "Interrupted system call should be restarted";
     case ESTRPIPE:
         return "Streams pipe error";
     case EUSERS:
         return "Too many users";
     case ENOTSOCK:
         return "Socket operation on non-socket";
     case EDESTADDRREQ:
         return "Destination address required";
     case EMSGSIZE:
         return "Message too long";
     case EPROTOTYPE:
         return "Protocol wrong type for socket";
     case ENOPROTOOPT:
         return "Protocol not available";
     case EPROTONOSUPPORT:
         return "Protocol not supported";
     case ESOCKTNOSUPPORT:
         return "Socket type not supported";
     case EOPNOTSUPP:
         return "Operation not supported";
     case EPFNOSUPPORT:
         return "Protocol family not supported";
     case EAFNOSUPPORT:
         return "Address family not supported by protocol";
     case EADDRINUSE:
         return "Address already in use";
     case EADDRNOTAVAIL:
         return "Cannot assign requested address";
     case ENETDOWN:
         return "Network is down";
     case ENETUNREACH:
         return "Network is unreachable";
     case ENETRESET:
         return "Network dropped connection on reset";
     case ECONNABORTED:
         return "Software caused connection abort";
     case ECONNRESET:
         return "Connection reset by peer";
     case ENOBUFS:
         return "No buffer space available";
     case EISCONN:
         return "Transport endpoint is already connected";
     case ENOTCONN:
         return "Transport endpoint is not connected";
     case ESHUTDOWN:
         return "Cannot send after transport endpoint shutdown";
     case ETOOMANYREFS:
         return "Too many references: cannot splice";
     case ETIMEDOUT:
         return "Connection timed out";
     case ECONNREFUSED:
         return "Connection refused";
     case EHOSTDOWN:
         return "Host is down";
     case EHOSTUNREACH:
         return "No route to host";
     case EALREADY:
         return "Operation already in progress";
     case EINPROGRESS:
         return "Operation now in progress";
     case ESTALE:
         return "Stale file handle";
     case EUCLEAN:
         return "Structure needs cleaning";
     case ENOTNAM:
         return "Not a XENIX named type file";
     case ENAVAIL:
         return "No XENIX semaphores available";
     case EISNAM:
         return "Is a named type file";
     case EREMOTEIO:
         return "Remote I/O error";
     case EDQUOT:
         return "Quota exceeded";
     case ENOMEDIUM:
         return "No medium found";
     case EMEDIUMTYPE:
         return "Wrong medium type";
     case ECANCELED:
         return "Operation Canceled";
     case ENOKEY:
         return "Required key not available";
     case EKEYEXPIRED:
         return "Key has expired";
     case EKEYREVOKED:
         return "Key has been revoked";
     case EKEYREJECTED:
         return "Key was rejected by service";
     case EOWNERDEAD:
         return "Owner died";
     case ENOTRECOVERABLE:
         return "State not recoverable";
     default:
         return "Unknown error";
     }
 }
References __strerror_l(), CURRENT_LOCALE, errbase, free, itos(), sprintf(), strcat, strcpy, and sys_nerr.
strlen()
size_t strlen (const char * str)
Definition at line 5 of file string.c.
 {
     long unsigned i = 0;
     if (str)
         while (str[i] != '\0')
             ++i;
     return i;
 }
References __attribute__, ALIGN, HASZERO, s, and w.
Referenced by strchr(), strdup(), and strrchr().
strncat()
char* strncat (char * __restrict, const char * __restrict, size_t)
Referenced by conf_expand_value().
strncmp()
int strncmp (const char * s1, const char * s2, size_t n)
Definition at line 51 of file convert.cpp.
 {
     for (size_t i = 0; i < n; i++)
     {
         char c1 = s1[i], c2 = s2[i];
         if (c1 != c2)
             return c1 - c2;
         if (!c1)
             return 0;
     }
     return 0;
 }
References i, l, n, s1, and s2.
strncpy()
char* strncpy (char * __restrict, const char * __restrict, size_t)
strpbrk()
char* strpbrk (const char * s, const char * accept)
Definition at line 34 of file strpbrk.c.
 {
   while (*s != '\0')
     {
       const char *a = accept;
       while (*a != '\0')
     if (*a++ == *s)
       return (char *) s;
       ++s;
     }
   return 0;
 }
References accept(), s, and strcspn().
Referenced by add_cmd(), awk_split(), conf_read_simple(), do_rd(), fix_assignment_words(), hasmeta(), init_exec(), rmescapes(), sleep_builtin(), strsep(), and subevalvar().
strrchr()
char* strrchr (const char * s, int c)
Definition at line 113 of file string.c.
 {
     size_t len = strlen(s);
     size_t pos = len;
     while (s[pos] != c && pos-- != 0)
         ;
     if (pos == len)
         return NULL;
     return (char *)s + pos;
 }
References __memrchr(), c, s, and strlen.
strspn()
size_t strspn (const char * s, const char * c)
Definition at line 6 of file strspn.c.
 {
     const char *a = s;
     size_t byteset[32/sizeof(size_t)] = { 0 };
     if (!c[0]) return 0;
     if (!c[1]) {
         for (; *s == *c; s++);
         return s-a;
     }
     for (; *c && BITOP(byteset, *(unsigned char *)c, |=); c++);
     for (; *s && BITOP(byteset, *(unsigned char *)s, &); s++);
     return s-a;
 }
References BITOP, c, and s.
Referenced by add_cmd(), add_split_dependencies(), config_read(), date_main(), expand_on_ifs(), fcvt(), find_main(), get_status(), getopt_main(), index_status_file(), inet_ntop(), long_double_format(), nc_main(), path_open(), print_ascii(), print_button(), strtok(), strtok_r(), and write_status_file().
strstr()
char* strstr (const char * haystack, const char * needle)
Definition at line 156 of file convert.cpp.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }
strtok()
char* strtok (char * __restrict, const char * __restrict)
Definition at line 435 of file convert.cpp.
 {
     static char *src1;
     if (!src)
         src = src1;
     if (!src)
         return NULL;
     while (1)
     {
         if (isdelim(*src, (char *)delim))
         {
             src++;
             continue;
         }
         if (*src == '\0')
             return NULL;
         break;
     }
     char *ret = src;
     while (1)
     {
         if (*src == '\0')
         {
             src1 = src;
             return ret;
         }
         if (isdelim(*src, (char *)delim))
         {
             *src = '\0';
             src1 = src + 1;
             return ret;
         }
         src++;
     }
     return NULL;
 }
strxfrm()
size_t strxfrm (char * __restrict, const char * __restrict, size_t)