Fennix Kernel: Kernel/syscalls/native/open.cpp File Reference
open.cpp File Reference
#include <syscalls.hpp>
#include <memory.hpp>
#include <lock.hpp>
#include <exec.hpp>
#include <errno.h>
#include <debug.h>
#include "../../syscalls.h"
#include "../../kernel.h"
#include "../../ipc.h"
Macros
#define SysFrm SyscallsFrame
Functions
int sys_open (SysFrm *, const char *path, int oflag, mode_t mode)
Macro Definition Documentation
SysFrm
#define SysFrm SyscallsFrame
Definition at line 38 of file open.cpp.
Function Documentation
sys_open()
int sys_open (SysFrm * , const char * path, int oflag, mode_t mode)
Definition at line 47 of file open.cpp.
 {
     const char *safe_path = nullptr;
     Tasking::PCB *pcb = thisProcess;
     Memory::SmartHeap sh(512, pcb->vma);
     safe_path = (const char *)sh.Get();
     {
         Memory::SwapPT swap(pcb->PageTable);
         size_t len = strlen(path);
         memcpy((void *)safe_path, path, len);
     }
     function("%s, %d, %d", safe_path, oflag, mode);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return fdt->_open(safe_path, oflag, mode);
 }
References vfs::FileDescriptorTable::_open(), Tasking::PCB::FileDescriptors, Memory::SmartHeap::Get(), len, memcpy(), Tasking::PCB::PageTable, strlen(), swap(), thisProcess, and Tasking::PCB::vma.
Referenced by linux_open().