Fennix: Userspace/musl/src/unistd/dup.c File Reference
dup.c File Reference
#include <unistd.h>
#include "syscall.h"
Functions
int dup (int fd)
Function Documentation
dup()
int dup (int fd)
Definition at line 4 of file dup.c.
 {
     return syscall(SYS_dup, fd);
 }
References fd, and syscall().
Referenced by bb_daemonize_or_rexec(), dprintf(), hush_main(), initialize_job_control(), popen_ls(), print_builtin(), sulogin_main(), tre_make_trans(), and xargs_main().