Fennix: Userspace/musl/src/stdio/open_wmemstream.c File Reference
open_wmemstream.c File Reference
#include "stdio_impl.h"
#include <wchar.h>
#include <errno.h>
#include <limits.h>
#include <string.h>
#include <stdlib.h>
#include "libc.h"
Data Structures
struct cookie
struct wms_FILE
Functions
static off_t wms_seek (FILE *f, off_t off, int whence)
static size_t wms_write (FILE *f, const unsigned char *buf, size_t len)
static int wms_close (FILE *f)
FILE * open_wmemstream (wchar_t **bufp, size_t *sizep)
Data Structure Documentation
cookie
struct cookie
Definition at line 9 of file fmemopen.c.
Data Fields
unsigned char * buf
char * buf
wchar_t * buf
char ** bufp
wchar_t ** bufp
size_t l
size_t len
mbstate_t mbs
int mode
size_t n
size_t pos
char * s
size_t size
size_t * sizep
size_t space
wchar_t * ws
wms_FILE
struct wms_FILE
Definition at line 19 of file open_wmemstream.c.
Data Fields
unsigned char buf[1]
struct cookie c
FILE f
Function Documentation
open_wmemstream()
FILE* open_wmemstream (wchar_t ** bufp, size_t * sizep)
Definition at line 72 of file open_wmemstream.c.
 {
     struct wms_FILE *f;
     wchar_t *buf;
     if (!(f=malloc(sizeof *f))) return 0;
     if (!(buf=malloc(sizeof *buf))) {
         free(f);
         return 0;
     }
     memset(&f->f, 0, sizeof f->f);
     memset(&f->c, 0, sizeof f->c);
     f->f.cookie = &f->c;
     f->c.bufp = bufp;
     f->c.sizep = sizep;
     f->c.pos = f->c.len = f->c.space = *sizep = 0;
     f->c.buf = *bufp = buf;
     *buf = 0;
     f->f.flags = F_NORD;
     f->f.fd = -1;
     f->f.buf = f->buf;
     f->f.buf_size = 0;
     f->f.lbf = EOF;
     f->f.write = wms_write;
     f->f.seek = wms_seek;
     f->f.close = wms_close;
     if (!libc.threaded) f->f.lock = -1;
     fwide(&f->f, 1);
     return __ofl_add(&f->f);
 }
References __ofl_add(), buf, EOF, f, F_NORD, free, fwide(), libc, malloc, memset, wms_close(), wms_seek(), and wms_write().
wms_close()
static int wms_close (FILE * f) static
Definition at line 67 of file open_wmemstream.c.
 {
     return 0;
 }
Referenced by open_wmemstream().
wms_seek()
static off_t wms_seek (FILE * f, off_t off, int whence) static
Definition at line 25 of file open_wmemstream.c.
 {
     ssize_t base;
     struct cookie *c = f->cookie;
     if (whence>2U) {
 fail:
         errno = EINVAL;
         return -1;
     }
     base = (size_t [3]){0, c->pos, c->len}[whence];
     if (off < -base || off > SSIZE_MAX/4-base) goto fail;
     memset(&c->mbs, 0, sizeof c->mbs);
     return c->pos = base+off;
 }
References base, c, EINVAL, errno, f, memset, off, and SSIZE_MAX.
Referenced by open_wmemstream().
wms_write()
static size_t wms_write (FILE * f, const unsigned char * buf, size_t len) static
Definition at line 40 of file open_wmemstream.c.
 {
     struct cookie *c = f->cookie;
     size_t len2 = f->wpos - f->wbase;
     wchar_t *newbuf;
     if (len2) {
         f->wpos = f->wbase;
         if (wms_write(f, f->wbase, len2) < len2) return 0;
     }
     if (len + c->pos >= c->space) {
         len2 = 2*c->space+1 | c->pos+len+1;
         if (len2 > SSIZE_MAX/4) return 0;
         newbuf = realloc(c->buf, len2*4);
         if (!newbuf) return 0;
         *c->bufp = c->buf = newbuf;
         memset(c->buf + c->space, 0, 4*(len2 - c->space));
         c->space = len2;
     }
     len2 = mbsnrtowcs(c->buf+c->pos, (void *)&buf, len, c->space-c->pos, &c->mbs);
     if (len2 == -1) return 0;
     c->pos += len2;
     if (c->pos >= c->len) c->len = c->pos;
     *c->sizep = c->pos;
     return len;
 }
References buf, c, f, len, mbsnrtowcs(), memset, realloc, and SSIZE_MAX.
Referenced by open_wmemstream().