Fennix: Userspace/apps/base/bash/examples/loadables/mkdir.c File Reference
mkdir.c File Reference
#include <config.h>
#include "bashtypes.h"
#include "posixstat.h"
#include <errno.h>
#include <stdio.h>
#include "bashansi.h"
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Macros
#define ISOCTAL(c) ((c) >= '0' && (c) <= '7')
Functions
int parse_symbolic_mode ()
static int make_path ()
int mkdir_builtin (WORD_LIST *list)
static int make_path (char *path, int user_mode, int nmode, int parent_mode)
Variables
int errno
static int original_umask
char * mkdir_doc []
struct builtin mkdir_struct
Macro Definition Documentation
ISOCTAL
#define ISOCTAL (c) ((c) >= '0' && (c) <= '7')
Definition at line 43 of file mkdir.c.
Function Documentation
make_path() [1/2]
static int make_path () static
Referenced by mkdir_builtin().
make_path() [2/2]
static int make_path (char * path, int user_mode, int nmode, int parent_mode) static
Definition at line 137 of file mkdir.c.
 {
   int oumask;
   struct stat sb;
   char *p, *npath;
   if (stat (path, &sb) == 0)
     {
       if (S_ISDIR (sb.st_mode) == 0)
     {
       builtin_error ("`%s': file exists but is not a directory", path);
       return 1;
     }
       if (user_mode && chmod (path, nmode))
         {
           builtin_error ("%s: %s", path, strerror (errno));
           return 1;
         }
       return 0;
     }
   oumask = umask (0);
   npath = savestring (path);    /* So we can write to it. */
   /* Check whether or not we need to do anything with intermediate dirs. */
   /* Skip leading slashes. */
   p = npath;
   while (*p == '/')
     p++;
   while (p = strchr (p, '/'))
     {
       *p = '\0';
       if (stat (npath, &sb) != 0)
     {
       if (mkdir (npath, 0))
         {
           builtin_error ("cannot create directory `%s': %s", npath, strerror (errno));
           umask (original_umask);
           free (npath);
           return 1;
         }
       if (chmod (npath, parent_mode) != 0)
         {
           builtin_error ("cannot chmod directory `%s': %s", npath, strerror (errno));
           umask (original_umask);
           free (npath);
           return 1;
         }
     }
       else if (S_ISDIR (sb.st_mode) == 0)
         {
           builtin_error ("`%s': file exists but is not a directory", npath);
           umask (original_umask);
           free (npath);
           return 1;
         }
       *p++ = '/';   /* restore slash */
       while (*p == '/')
     p++;
     }
   /* Create the final directory component. */
   if (stat (npath, &sb) && mkdir (npath, nmode))
     {
       builtin_error ("cannot create directory `%s': %s", npath, strerror (errno));
       umask (original_umask);
       free (npath);
       return 1;
     }
   umask (original_umask);
   free (npath);
   return 0;
 }
References builtin_error(), chmod(), errno, free, mkdir(), original_umask, p, S_ISDIR, savestring(), stat::st_mode, strchr(), strerror(), and umask().
mkdir_builtin()
int mkdir_builtin (WORD_LIST * list)
Definition at line 52 of file mkdir.c.
 {
   int opt, pflag, mflag, omode, rval, nmode, parent_mode;
   char *mode;
   WORD_LIST *l;
   reset_internal_getopt ();
   pflag = mflag = 0;
   mode = (char *)NULL;
   while ((opt = internal_getopt(list, "m:p")) != -1)
     switch (opt)
       {
     case 'p':
       pflag = 1;
       break;
     case 'm':
       mflag = 1;
       mode = list_optarg;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage();
       return (EX_USAGE);
       }
   list = loptend;
   if (list == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   if (mode == NULL)
     omode = S_IRWXU | S_IRWXG | S_IRWXO;    /* a=rwx */
   else if (ISOCTAL (*mode)) /* octal number */
     {
       omode = read_octal (mode);
       if (omode < 0)
     {
       builtin_error ("invalid file mode: %s", mode);
       return (EXECUTION_FAILURE);
     }
     }
   else              /* symbolic mode */
     {
       /* initial bits are a=rwx; the mode argument modifies them */
       omode = parse_symbolic_mode (mode, S_IRWXU | S_IRWXG | S_IRWXO);
       if (omode < 0)
     {
       builtin_error ("invalid file mode: %s", mode);
       return (EXECUTION_FAILURE);
     }
     }
   /* Make the new mode */
   original_umask = umask (0);
   umask (original_umask);
   nmode = (S_IRWXU | S_IRWXG | S_IRWXO) & ~original_umask;
   parent_mode = nmode | (S_IWUSR|S_IXUSR);  /* u+wx */
   /* Adjust new mode based on mode argument */
   nmode &= omode;
   for (rval = EXECUTION_SUCCESS, l = list; l; l = l->next)
     {
       if (pflag && make_path (l->word->word, mflag, nmode, parent_mode))
     {
       rval = EXECUTION_FAILURE;
       continue;
     }
       else if (pflag == 0 && mkdir (l->word->word, nmode) < 0)
         {
           builtin_error ("cannot create directory `%s': %s", l->word->word, strerror (errno));
           rval = EXECUTION_FAILURE;
         }
     }
   return rval;
 }
References builtin_error(), builtin_usage(), CASE_HELPOPT, errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, internal_getopt(), ISOCTAL, l, list(), list_optarg, loptend, make_path(), mflag, mkdir(), NULL, opt, original_umask, parse_symbolic_mode(), read_octal(), reset_internal_getopt(), S_IRWXG, S_IRWXO, S_IRWXU, S_IWUSR, S_IXUSR, strerror(), and umask().
parse_symbolic_mode()
int parse_symbolic_mode ()
Referenced by mkdir_builtin().
Variable Documentation
errno
int errno extern
Referenced by make_path(), and mkdir_builtin().
mkdir_doc
char* mkdir_doc[]
Initial value:
= {
    "Create directories.",
    "",
    "Make directories.  Create the directories named as arguments, in",
    "the order specified, using mode rwxrwxrwx as modified by the current",
    "umask (see `help umask').  The -m option causes the file permission",
    "bits of the final directory to be MODE.  The MODE argument may be",
    "an octal number or a symbolic mode like that used by chmod(1).  If",
    "a symbolic mode is used, the operations are interpreted relative to",
    "an initial mode of \"a=rwx\".  The -p option causes any required",
    "intermediate directories in PATH to be created.  The directories",
    "are created with permission bits of rwxrwxrwx as modified by the current",
    "umask, plus write and search permissions for the owner.  mkdir",
    "returns 0 if the directories are created successfully, and non-zero",
    "if an error occurs.",
    (char *)NULL
}
Definition at line 220 of file mkdir.c.
mkdir_struct
struct builtin mkdir_struct
Initial value:
= {
    "mkdir",
    mkdir_builtin,
    BUILTIN_ENABLED,
    mkdir_doc,
    "mkdir [-p] [-m mode] directory [directory ...]",
    0
}
Definition at line 220 of file mkdir.c.
original_umask
int original_umask static
Definition at line 49 of file mkdir.c.
Referenced by make_path(), and mkdir_builtin().