Fennix Userspace: Userspace/apps/base/bash/examples/loadables/ln.c File Reference
ln.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixstat.h"
#include <stdio.h>
#include <errno.h>
#include "builtins.h"
#include "shell.h"
#include "bashgetopt.h"
#include "common.h"
Macros
#define LN_SYMLINK 0x01
#define LN_UNLINK 0x02
#define LN_NOFOLLOW 0x04
#define LSTAT stat
#define LSTAT_OR_STAT_IF(c, f, b) (stat((f), (b)))
Typedefs
typedef int unix_link_syscall_t PARAMS((const char *, const char *))
Functions
static int dolink ()
int ln_builtin (WORD_LIST *list)
static char * mkdirpath (char *dir, char *file)
static int dolink (char *src, char *dst, int flags)
Variables
int errno
static unix_link_syscall_t * linkfn
char * ln_doc []
struct builtin ln_struct
Macro Definition Documentation
LN_NOFOLLOW
#define LN_NOFOLLOW 0x04
Definition at line 49 of file ln.c.
LN_SYMLINK
#define LN_SYMLINK 0x01
Definition at line 47 of file ln.c.
LN_UNLINK
#define LN_UNLINK 0x02
Definition at line 48 of file ln.c.
LSTAT
#define LSTAT stat
Definition at line 150 of file ln.c.
LSTAT_OR_STAT_IF
#define LSTAT_OR_STAT_IF (c, f, b) (stat((f), (b)))
Definition at line 151 of file ln.c.
Typedef Documentation
PARAMS
typedef int unix_link_syscall_t PARAMS((const char *, const char *))
Definition at line 45 of file ln.c.
Function Documentation
dolink() [1/2]
static int dolink () static
Referenced by ln_builtin().
dolink() [2/2]
static int dolink (char * src, char * dst, int flags) static
Definition at line 155 of file ln.c.
 {
   struct stat ssb, dsb;
   int exists;
   char *dst_path, *p;
   /* If we're not doing symlinks, the source must exist and not be a
      directory. */
   if ((flags & LN_SYMLINK) == 0)
     {
       if (stat (src, &ssb) != 0)
     {
       builtin_error ("%s: %s", src, strerror (errno));
       return (EXECUTION_FAILURE);
     }
       if (S_ISDIR (ssb.st_mode))
     {
       errno = EISDIR;
       builtin_error ("%s: %s", src, strerror (errno));
       return (EXECUTION_FAILURE);
     }
     }
   /* If the destination is a directory, create the final filename by appending
      the basename of the source to the destination. */
   dst_path = 0;
   if ((LSTAT_OR_STAT_IF((flags & LN_NOFOLLOW), dst, &dsb) == 0) && S_ISDIR (dsb.st_mode))
     {
       if ((p = strrchr (src, '/')) == 0)
     p = src;
       else
     p++;
       dst_path = mkdirpath (dst, p);
       dst = dst_path;
     }
   exists = LSTAT (dst, &dsb) == 0;
   /* If -f was specified, and the destination exists, unlink it. */
   if ((flags & LN_UNLINK) && exists && unlink (dst) != 0)
     {
       builtin_error ("%s: cannot unlink: %s", dst, strerror (errno));
       FREE (dst_path);
       return (EXECUTION_FAILURE);
     }
   /* Perform the link. */
   if ((*linkfn) (src, dst) != 0)
     {
       builtin_error ("cannot link %s to %s: %s", dst, src, strerror (errno));
       FREE (dst_path);
       return (EXECUTION_FAILURE);
     }
   FREE (dst_path);
   return (EXECUTION_SUCCESS);
 }
References builtin_error(), dst, EISDIR, errno, EXECUTION_FAILURE, EXECUTION_SUCCESS, flags, FREE, linkfn, LN_NOFOLLOW, LN_SYMLINK, LN_UNLINK, LSTAT, LSTAT_OR_STAT_IF, mkdirpath(), p, S_ISDIR, src, stat::st_mode, strerror(), strrchr(), and unlink().
ln_builtin()
int ln_builtin (WORD_LIST * list)
Definition at line 55 of file ln.c.
 {
   int rval, opt, flags;
   WORD_LIST *l;
   char *sdir;
   struct stat sb;
   flags = 0;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "fs")) != -1)
     {
       switch (opt)
     {
     case 'f':
       flags |= LN_UNLINK;
       break;
     case 's':
       flags |= LN_SYMLINK;
       break;
     case 'h':
     case 'n':
       flags |= LN_NOFOLLOW;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (list == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   linkfn = (flags & LN_SYMLINK) ? symlink : link;
   if (list->next == 0)          /* ln target, equivalent to ln target . */
     return (dolink (list->word->word, ".", flags));
   if (list->next->next == 0)        /* ln target source */
     return (dolink (list->word->word, list->next->word->word, flags));
   /* ln target1 target2 ... directory */
   /* find last argument: target directory, and make sure it's an existing
      directory. */
   for (l = list; l->next; l = l->next)
     ;
   sdir = l->word->word;
   if (stat(sdir, &sb) < 0)
     {
       builtin_error ("%s", sdir);
       return (EXECUTION_FAILURE);
     }
   if (S_ISDIR (sb.st_mode) == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   for (rval = EXECUTION_SUCCESS; list != l; list = list->next)
     rval += dolink (list->word->word, sdir, flags);
   return rval;
 }
References builtin_error(), builtin_usage(), CASE_HELPOPT, dolink(), EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, flags, internal_getopt(), l, link(), linkfn, list(), LN_NOFOLLOW, LN_SYMLINK, LN_UNLINK, loptend, node::next, opt, reset_internal_getopt(), S_ISDIR, stat::st_mode, stat(), and symlink().
mkdirpath()
static char* mkdirpath (char * dir, char * file) static
Definition at line 128 of file ln.c.
 {
   int dlen, flen;
   char *ret;
   dlen = strlen (dir);
   flen = strlen (file);
   ret = xmalloc (2 + dlen + flen);
   strcpy (ret, dir);
   if (ret[dlen - 1] != '/')
     ret[dlen++] = '/';
   strcpy (ret + dlen, file);
   return ret;
 }
References dir, strcpy(), strlen(), and xmalloc.
Referenced by dolink().
Variable Documentation
errno
int errno extern
Referenced by dolink(), and ln_main().
linkfn
unix_link_syscall_t* linkfn static
Definition at line 51 of file ln.c.
Referenced by dolink(), and ln_builtin().
ln_doc
char* ln_doc[]
Initial value:
= {
    "Link files.",
    "",
    "Create a new directory entry with the same modes as the original",
    "file.  The -f option means to unlink any existing file, permitting",
    "the link to occur.  The -s option means to create a symbolic link.",
    "By default, ln makes hard links.  Specifying -n or its synonym -h",
    "causes ln to not resolve symlinks in the target file or directory.",
    (char *)NULL
}
Definition at line 216 of file ln.c.
ln_struct
struct builtin ln_struct
Initial value:
= {
    "ln",
    ln_builtin,
    BUILTIN_ENABLED,
    ln_doc,
    "ln [-fhns] file1 [file2] OR ln [-fhns] file ... directory",
    0
}
Definition at line 216 of file ln.c.