Fennix Userspace: Userspace/musl/src/termios/tcgetattr.c File Reference
tcgetattr.c File Reference
#include <termios.h>
#include <sys/ioctl.h>
Functions
int tcgetattr (int fd, struct termios *tio)
Function Documentation
tcgetattr()
int tcgetattr (int fd, struct termios * tio)
Definition at line 4 of file tcgetattr.c.
 {
     if (ioctl(fd, TCGETS, tio))
         return -1;
     return 0;
 }
References ioctl(), and TCGETS.
Referenced by DisableInputBuffering(), EnableInputBuffering(), getpass(), and ptmx_test().