Fennix: Userspace/mlibc/options/posix/generic/sched-stubs.cpp File Reference
sched-stubs.cpp File Reference
#include <bits/ensure.h>
#include <errno.h>
#include <limits.h>
#include <sched.h>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
Functions
int sched_yield (void)
int sched_getaffinity (pid_t pid, size_t cpusetsize, cpu_set_t *mask)
int sched_get_priority_max (int)
int sched_get_priority_min (int policy)
int __mlibc_cpu_isset (int, cpu_set_t *)
int __mlibc_cpu_count (const cpu_set_t *set)
int unshare (int)
int clone (int(*)(void *), void *, int, void *,...)
Function Documentation
__mlibc_cpu_count()
int __mlibc_cpu_count (const cpu_set_t * set)
Definition at line 50 of file sched-stubs.cpp.
{
     size_t count = 0;
     const unsigned char *ptr = reinterpret_cast<const unsigned char *>(set);
     for(size_t i = 0; i < sizeof(cpu_set_t); i++) {
         for(size_t bit = 0; bit < CHAR_BIT; bit++) {
             if((1 << bit) & ptr[i])
                 count++;
         }
     }
     return count;
 }
References CHAR_BIT, count, and i.
__mlibc_cpu_isset()
int __mlibc_cpu_isset (int cpu, cpu_set_t * set)
Definition at line 45 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
clone()
int clone (int(*)(void *) , void * , int , void * , ...)
Definition at line 69 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sched_get_priority_max()
int sched_get_priority_max (int policy)
Definition at line 29 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sched_get_priority_min()
int sched_get_priority_min (int policy)
Definition at line 34 of file sched-stubs.cpp.
{
     int res = 0;
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_get_min_priority, -1);
     if(int e = sysdep(policy, &res); e) {
         errno = e;
         return -1;
     }
     return res;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_get_min_priority().
sched_getaffinity()
int sched_getaffinity (pid_t pid, size_t cpusetsize, cpu_set_t * mask)
Definition at line 20 of file sched-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getaffinity, -1);
     if(int e = mlibc::sys_getaffinity(pid, cpusetsize, mask); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getaffinity().
sched_yield()
int sched_yield (void)
Definition at line 10 of file sched-stubs.cpp.
                       {
     if(mlibc::sys_yield) {
         mlibc::sys_yield();
     }else{
         // Missing sched_yield() is not an error.
         MLIBC_MISSING_SYSDEP();
     }
     return 0;
 }
References MLIBC_MISSING_SYSDEP, and mlibc::sys_yield().
unshare()
int unshare (int flags)
Definition at line 64 of file sched-stubs.cpp.
                  {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.