Fennix Userspace: Userspace/apps/base/busybox/archival/libarchive/unxz/xz_dec_lzma2.c File Reference
xz_dec_lzma2.c File Reference
#include "xz_private.h"
#include "xz_lzma2.h"
Data Structures
struct dictionary
struct rc_dec
struct lzma_len_dec
struct lzma_dec
struct lzma2_dec
struct xz_dec_lzma2
struct xz_dec_lzma2.temp
Macros
#define RC_INIT_BYTES 5
#define LZMA_IN_REQUIRED 21
Functions
static void XZ_FUNC dict_reset (struct dictionary *dict, struct xz_buf *b)
static void XZ_FUNC dict_limit (struct dictionary *dict, size_t out_max)
static __always_inline bool XZ_FUNC dict_has_space (const struct dictionary *dict)
static __always_inline uint32_t XZ_FUNC dict_get (const struct dictionary *dict, uint32_t dist)
static void XZ_FUNC dict_put (struct dictionary *dict, uint8_t byte)
static bool XZ_FUNC dict_repeat (struct dictionary *dict, uint32_t *len, uint32_t dist)
static void XZ_FUNC dict_uncompressed (struct dictionary *dict, struct xz_buf *b, uint32_t *left)
static uint32_t XZ_FUNC dict_flush (struct dictionary *dict, struct xz_buf *b)
static void XZ_FUNC rc_reset (struct rc_dec *rc)
static bool XZ_FUNC rc_read_init (struct rc_dec *rc, struct xz_buf *b)
static bool XZ_FUNC rc_limit_exceeded (const struct rc_dec *rc)
static bool XZ_FUNC rc_is_finished (const struct rc_dec *rc)
static __always_inline void XZ_FUNC rc_normalize (struct rc_dec *rc)
static __always_inline int XZ_FUNC rc_bit (struct rc_dec *rc, uint16_t *prob)
static __always_inline uint32_t XZ_FUNC rc_bittree (struct rc_dec *rc, uint16_t *probs, uint32_t limit)
static __always_inline void XZ_FUNC rc_bittree_reverse (struct rc_dec *rc, uint16_t *probs, uint32_t *dest, uint32_t limit)
static void XZ_FUNC rc_direct (struct rc_dec *rc, uint32_t *dest, uint32_t limit)
static uint16_t *XZ_FUNC lzma_literal_probs (struct xz_dec_lzma2 *s)
static void XZ_FUNC lzma_literal (struct xz_dec_lzma2 *s)
static void XZ_FUNC lzma_len (struct xz_dec_lzma2 *s, struct lzma_len_dec *l, uint32_t pos_state)
static void XZ_FUNC lzma_match (struct xz_dec_lzma2 *s, uint32_t pos_state)
static void XZ_FUNC lzma_rep_match (struct xz_dec_lzma2 *s, uint32_t pos_state)
static bool XZ_FUNC lzma_main (struct xz_dec_lzma2 *s)
static void XZ_FUNC lzma_reset (struct xz_dec_lzma2 *s)
static bool XZ_FUNC lzma_props (struct xz_dec_lzma2 *s, uint8_t props)
static bool XZ_FUNC lzma2_lzma (struct xz_dec_lzma2 *s, struct xz_buf *b)
XZ_EXTERN NOINLINE enum xz_ret XZ_FUNC xz_dec_lzma2_run (struct xz_dec_lzma2 *s, struct xz_buf *b)
XZ_EXTERN struct xz_dec_lzma2 *XZ_FUNC xz_dec_lzma2_create (enum xz_mode mode, uint32_t dict_max)
XZ_EXTERN enum xz_ret XZ_FUNC xz_dec_lzma2_reset (struct xz_dec_lzma2 *s, uint8_t props)
XZ_EXTERN void XZ_FUNC xz_dec_lzma2_end (struct xz_dec_lzma2 *s)
Data Structure Documentation
dictionary
struct dictionary
Definition at line 44 of file xz_dec_lzma2.c.
Data Fields
uint32_t allocated
uint8_t * buf
size_t end
size_t full
size_t limit
enum xz_mode mode
size_t pos
uint32_t size
uint32_t size_max
size_t start
rc_dec
struct rc_dec
Definition at line 95 of file xz_dec_lzma2.c.
Data Fields
uint32_t code
const uint8_t * in
size_t in_limit
size_t in_pos
uint32_t init_bytes_left
uint32_t range
lzma_len_dec
struct lzma_len_dec
Definition at line 115 of file xz_dec_lzma2.c.
Data Fields
uint16_t choice
uint16_t choice2
uint16_t high[LEN_HIGH_SYMBOLS]
uint16_t low[POS_STATES_MAX][LEN_LOW_SYMBOLS]
uint16_t mid[POS_STATES_MAX][LEN_MID_SYMBOLS]
lzma_dec
struct lzma_dec
Definition at line 132 of file xz_dec_lzma2.c.
Data Fields
uint16_t dist_align[ALIGN_SIZE]
uint16_t dist_slot[DIST_STATES][DIST_SLOTS]
uint16_t dist_special[FULL_DISTANCES - DIST_MODEL_END]
uint16_t is_match[STATES][POS_STATES_MAX]
uint16_t is_rep[STATES]
uint16_t is_rep0[STATES]
uint16_t is_rep0_long[STATES][POS_STATES_MAX]
uint16_t is_rep1[STATES]
uint16_t is_rep2[STATES]
uint32_t lc
uint32_t len
uint16_t literal[LITERAL_CODERS_MAX][LITERAL_CODER_SIZE]
uint32_t literal_pos_mask
struct lzma_len_dec match_len_dec
uint32_t pos_mask
uint32_t rep0
uint32_t rep1
uint32_t rep2
uint32_t rep3
struct lzma_len_dec rep_len_dec
enum lzma_state state
xz_dec_lzma2
struct xz_dec_lzma2
Definition at line 253 of file xz_dec_lzma2.c.
Data Fields
struct dictionary dict
struct lzma_dec lzma
struct lzma2_dec lzma2
struct rc_dec rc
struct xz_dec_lzma2 temp
xz_dec_lzma2.temp
struct xz_dec_lzma2.temp
Definition at line 272 of file xz_dec_lzma2.c.
Data Fields
uint8_t buf[3 *LZMA_IN_REQUIRED]
uint32_t size
Macro Definition Documentation
LZMA_IN_REQUIRED
#define LZMA_IN_REQUIRED 21
Definition at line 26 of file xz_dec_lzma2.c.
RC_INIT_BYTES
#define RC_INIT_BYTES 5
Definition at line 17 of file xz_dec_lzma2.c.
Function Documentation
dict_flush()
static uint32_t XZ_FUNC dict_flush (struct dictionary * dict, struct xz_buf * b) static
Definition at line 418 of file xz_dec_lzma2.c.
 {
     size_t copy_size = dict->pos - dict->start;
     if (DEC_IS_MULTI(dict->mode)) {
         if (dict->pos == dict->end)
             dict->pos = 0;
         memcpy(b->out + b->out_pos, dict->buf + dict->start,
                 copy_size);
     }
     dict->start = dict->pos;
     b->out_pos += copy_size;
     return copy_size;
 }
References dictionary::buf, DEC_IS_MULTI, dictionary::end, memcpy(), dictionary::mode, xz_buf::out, xz_buf::out_pos, dictionary::pos, and dictionary::start.
Referenced by xz_dec_lzma2_run().
dict_get()
static __always_inline uint32_t XZ_FUNC dict_get (const struct dictionary * dict, uint32_t dist) static
Definition at line 320 of file xz_dec_lzma2.c.
 {
     size_t offset = dict->pos - dist - 1;
     if (dist >= dict->pos)
         offset += dict->end;
     return dict->full > 0 ? dict->buf[offset] : 0;
 }
References dictionary::buf, dictionary::end, dictionary::full, offset, and dictionary::pos.
Referenced by lzma_literal(), and lzma_literal_probs().
dict_has_space()
static __always_inline bool XZ_FUNC dict_has_space (const struct dictionary * dict) static
Definition at line 309 of file xz_dec_lzma2.c.
 {
     return dict->pos < dict->limit;
 }
References dictionary::limit, and dictionary::pos.
Referenced by lzma_main().
dict_limit()
static void XZ_FUNC dict_limit (struct dictionary * dict, size_t out_max) static
Definition at line 300 of file xz_dec_lzma2.c.
 {
     if (dict->end - dict->pos <= out_max)
         dict->limit = dict->end;
     else
         dict->limit = dict->pos + out_max;
 }
References dictionary::end, dictionary::limit, and dictionary::pos.
Referenced by xz_dec_lzma2_run().
dict_put()
static void XZ_FUNC dict_put (struct dictionary * dict, uint8_t byte) inline static
Definition at line 334 of file xz_dec_lzma2.c.
 {
     dict->buf[dict->pos++] = byte;
     if (dict->full < dict->pos)
         dict->full = dict->pos;
 }
References dictionary::buf, dictionary::full, and dictionary::pos.
Referenced by lzma_literal().
dict_repeat()
static bool XZ_FUNC dict_repeat (struct dictionary * dict, uint32_t * len, uint32_t dist) static
Definition at line 347 of file xz_dec_lzma2.c.
 {
     size_t back;
     uint32_t left;
     if (dist >= dict->full || dist >= dict->size)
         return false;
     left = min_t(size_t, dict->limit - dict->pos, *len);
     *len -= left;
     back = dict->pos - dist - 1;
     if (dist >= dict->pos)
         back += dict->end;
     do {
         dict->buf[dict->pos++] = dict->buf[back++];
         if (back == dict->end)
             back = 0;
     } while (--left > 0);
     if (dict->full < dict->pos)
         dict->full = dict->pos;
     return true;
 }
References dictionary::buf, dictionary::end, dictionary::full, dictionary::limit, min_t, dictionary::pos, and dictionary::size.
Referenced by lzma_main().
dict_reset()
static void XZ_FUNC dict_reset (struct dictionary * dict, struct xz_buf * b) static
Definition at line 286 of file xz_dec_lzma2.c.
 {
     if (DEC_IS_SINGLE(dict->mode)) {
         dict->buf = b->out + b->out_pos;
         dict->end = b->out_size - b->out_pos;
     }
     dict->start = 0;
     dict->pos = 0;
     dict->limit = 0;
     dict->full = 0;
 }
References dictionary::buf, DEC_IS_SINGLE, dictionary::end, dictionary::full, dictionary::limit, dictionary::mode, xz_buf::out, xz_buf::out_pos, xz_buf::out_size, dictionary::pos, and dictionary::start.
Referenced by xz_dec_lzma2_run().
dict_uncompressed()
static void XZ_FUNC dict_uncompressed (struct dictionary * dict, struct xz_buf * b, uint32_t * left) static
Definition at line 376 of file xz_dec_lzma2.c.
 {
     size_t copy_size;
     while (*left > 0 && b->in_pos < b->in_size
             && b->out_pos < b->out_size) {
         copy_size = min(b->in_size - b->in_pos,
                 b->out_size - b->out_pos);
         if (copy_size > dict->end - dict->pos)
             copy_size = dict->end - dict->pos;
         if (copy_size > *left)
             copy_size = *left;
         *left -= copy_size;
         memcpy(dict->buf + dict->pos, b->in + b->in_pos, copy_size);
         dict->pos += copy_size;
         if (dict->full < dict->pos)
             dict->full = dict->pos;
         if (DEC_IS_MULTI(dict->mode)) {
             if (dict->pos == dict->end)
                 dict->pos = 0;
             memcpy(b->out + b->out_pos, b->in + b->in_pos,
                     copy_size);
         }
         dict->start = dict->pos;
         b->out_pos += copy_size;
         b->in_pos += copy_size;
     }
 }
References dictionary::buf, DEC_IS_MULTI, dictionary::end, dictionary::full, xz_buf::in, xz_buf::in_pos, xz_buf::in_size, memcpy(), min, dictionary::mode, xz_buf::out, xz_buf::out_pos, xz_buf::out_size, dictionary::pos, and dictionary::start.
Referenced by xz_dec_lzma2_run().
lzma2_lzma()
static bool XZ_FUNC lzma2_lzma (struct xz_dec_lzma2 * s, struct xz_buf * b) static
Definition at line 848 of file xz_dec_lzma2.c.
 {
     size_t in_avail;
     uint32_t tmp;
     in_avail = b->in_size - b->in_pos;
     if (s->temp.size > 0 || s->lzma2.compressed == 0) {
         tmp = 2 * LZMA_IN_REQUIRED - s->temp.size;
         if (tmp > s->lzma2.compressed - s->temp.size)
             tmp = s->lzma2.compressed - s->temp.size;
         if (tmp > in_avail)
             tmp = in_avail;
         memcpy(s->temp.buf + s->temp.size, b->in + b->in_pos, tmp);
         if (s->temp.size + tmp == s->lzma2.compressed) {
             memzero(s->temp.buf + s->temp.size + tmp,
                     sizeof(s->temp.buf)
                         - s->temp.size - tmp);
             s->rc.in_limit = s->temp.size + tmp;
         } else if (s->temp.size + tmp < LZMA_IN_REQUIRED) {
             s->temp.size += tmp;
             b->in_pos += tmp;
             return true;
         } else {
             s->rc.in_limit = s->temp.size + tmp - LZMA_IN_REQUIRED;
         }
         s->rc.in = s->temp.buf;
         s->rc.in_pos = 0;
         if (!lzma_main(s) || s->rc.in_pos > s->temp.size + tmp)
             return false;
         s->lzma2.compressed -= s->rc.in_pos;
         if (s->rc.in_pos < s->temp.size) {
             s->temp.size -= s->rc.in_pos;
             memmove(s->temp.buf, s->temp.buf + s->rc.in_pos,
                     s->temp.size);
             return true;
         }
         b->in_pos += s->rc.in_pos - s->temp.size;
         s->temp.size = 0;
     }
     in_avail = b->in_size - b->in_pos;
     if (in_avail >= LZMA_IN_REQUIRED) {
         s->rc.in = b->in;
         s->rc.in_pos = b->in_pos;
         if (in_avail >= s->lzma2.compressed + LZMA_IN_REQUIRED)
             s->rc.in_limit = b->in_pos + s->lzma2.compressed;
         else
             s->rc.in_limit = b->in_size - LZMA_IN_REQUIRED;
         if (!lzma_main(s))
             return false;
         in_avail = s->rc.in_pos - b->in_pos;
         if (in_avail > s->lzma2.compressed)
             return false;
         s->lzma2.compressed -= in_avail;
         b->in_pos = s->rc.in_pos;
     }
     in_avail = b->in_size - b->in_pos;
     if (in_avail < LZMA_IN_REQUIRED) {
         if (in_avail > s->lzma2.compressed)
             in_avail = s->lzma2.compressed;
         memcpy(s->temp.buf, b->in + b->in_pos, in_avail);
         s->temp.size = in_avail;
         b->in_pos += in_avail;
     }
     return true;
 }
References xz_buf::in, xz_buf::in_pos, xz_buf::in_size, LZMA_IN_REQUIRED, lzma_main(), memcpy(), memmove(), memzero, and s.
Referenced by xz_dec_lzma2_run().
lzma_len()
static void XZ_FUNC lzma_len (struct xz_dec_lzma2 * s, struct lzma_len_dec * l, uint32_t pos_state) static
Definition at line 621 of file xz_dec_lzma2.c.
 {
     uint16_t *probs;
     uint32_t limit;
     if (!rc_bit(&s->rc, &l->choice)) {
         probs = l->low[pos_state];
         limit = LEN_LOW_SYMBOLS;
         s->lzma.len = MATCH_LEN_MIN;
     } else {
         if (!rc_bit(&s->rc, &l->choice2)) {
             probs = l->mid[pos_state];
             limit = LEN_MID_SYMBOLS;
             s->lzma.len = MATCH_LEN_MIN + LEN_LOW_SYMBOLS;
         } else {
             probs = l->high;
             limit = LEN_HIGH_SYMBOLS;
             s->lzma.len = MATCH_LEN_MIN + LEN_LOW_SYMBOLS
                     + LEN_MID_SYMBOLS;
         }
     }
     s->lzma.len += rc_bittree(&s->rc, probs, limit) - limit;
 }
References l, LEN_HIGH_SYMBOLS, LEN_LOW_SYMBOLS, LEN_MID_SYMBOLS, limit(), MATCH_LEN_MIN, rc_bit(), rc_bittree(), and s.
Referenced by lzma_match(), and lzma_rep_match().
lzma_literal()
static void XZ_FUNC lzma_literal (struct xz_dec_lzma2 * s) static
Definition at line 583 of file xz_dec_lzma2.c.
 {
     uint16_t *probs;
     uint32_t symbol;
     uint32_t match_byte;
     uint32_t match_bit;
     uint32_t offset;
     uint32_t i;
     probs = lzma_literal_probs(s);
     if (lzma_state_is_literal(s->lzma.state)) {
         symbol = rc_bittree(&s->rc, probs, 0x100);
     } else {
         symbol = 1;
         match_byte = dict_get(&s->dict, s->lzma.rep0) << 1;
         offset = 0x100;
         do {
             match_bit = match_byte & offset;
             match_byte <<= 1;
             i = offset + match_bit + symbol;
             if (rc_bit(&s->rc, &probs[i])) {
                 symbol = (symbol << 1) + 1;
                 offset &= match_bit;
             } else {
                 symbol <<= 1;
                 offset &= ~match_bit;
             }
         } while (symbol < 0x100);
     }
     dict_put(&s->dict, (uint8_t)symbol);
     lzma_state_literal(&s->lzma.state);
 }
References dict_get(), dict_put(), i, lzma_literal_probs(), lzma_state_is_literal(), lzma_state_literal(), offset, rc_bit(), rc_bittree(), and s.
Referenced by lzma_main().
lzma_literal_probs()
static uint16_t* XZ_FUNC lzma_literal_probs (struct xz_dec_lzma2 * s) static
Definition at line 574 of file xz_dec_lzma2.c.
 {
     uint32_t prev_byte = dict_get(&s->dict, 0);
     uint32_t low = prev_byte >> (8 - s->lzma.lc);
     uint32_t high = (s->dict.pos & s->lzma.literal_pos_mask) << s->lzma.lc;
     return s->lzma.literal[low + high];
 }
References dict_get(), and s.
Referenced by lzma_literal().
lzma_main()
static bool XZ_FUNC lzma_main (struct xz_dec_lzma2 * s) static
Definition at line 724 of file xz_dec_lzma2.c.
 {
     uint32_t pos_state;
     /*
      * If the dictionary was reached during the previous call, try to
      * finish the possibly pending repeat in the dictionary.
      */
     if (dict_has_space(&s->dict) && s->lzma.len > 0)
         dict_repeat(&s->dict, &s->lzma.len, s->lzma.rep0);
     /*
      * Decode more LZMA symbols. One iteration may consume up to
      * LZMA_IN_REQUIRED - 1 bytes.
      */
     while (dict_has_space(&s->dict) && !rc_limit_exceeded(&s->rc)) {
         pos_state = s->dict.pos & s->lzma.pos_mask;
         if (!rc_bit(&s->rc, &s->lzma.is_match[
                 s->lzma.state][pos_state])) {
             lzma_literal(s);
         } else {
             if (rc_bit(&s->rc, &s->lzma.is_rep[s->lzma.state]))
                 lzma_rep_match(s, pos_state);
             else
                 lzma_match(s, pos_state);
             if (!dict_repeat(&s->dict, &s->lzma.len, s->lzma.rep0))
                 return false;
         }
     }
     /*
      * Having the range decoder always normalized when we are outside
      * this function makes it easier to correctly handle end of the chunk.
      */
     rc_normalize(&s->rc);
     return true;
 }
References dict_has_space(), dict_repeat(), lzma_literal(), lzma_match(), lzma_rep_match(), rc_bit(), rc_limit_exceeded(), rc_normalize(), and s.
Referenced by lzma2_lzma().
lzma_match()
static void XZ_FUNC lzma_match (struct xz_dec_lzma2 * s, uint32_t pos_state) static
Definition at line 648 of file xz_dec_lzma2.c.
 {
     uint16_t *probs;
     uint32_t dist_slot;
     uint32_t limit;
     lzma_state_match(&s->lzma.state);
     s->lzma.rep3 = s->lzma.rep2;
     s->lzma.rep2 = s->lzma.rep1;
     s->lzma.rep1 = s->lzma.rep0;
     lzma_len(s, &s->lzma.match_len_dec, pos_state);
     probs = s->lzma.dist_slot[lzma_get_dist_state(s->lzma.len)];
     dist_slot = rc_bittree(&s->rc, probs, DIST_SLOTS) - DIST_SLOTS;
     if (dist_slot < DIST_MODEL_START) {
         s->lzma.rep0 = dist_slot;
     } else {
         limit = (dist_slot >> 1) - 1;
         s->lzma.rep0 = 2 + (dist_slot & 1);
         if (dist_slot < DIST_MODEL_END) {
             s->lzma.rep0 <<= limit;
             probs = s->lzma.dist_special + s->lzma.rep0
                     - dist_slot - 1;
             rc_bittree_reverse(&s->rc, probs,
                     &s->lzma.rep0, limit);
         } else {
             rc_direct(&s->rc, &s->lzma.rep0, limit - ALIGN_BITS);
             s->lzma.rep0 <<= ALIGN_BITS;
             rc_bittree_reverse(&s->rc, s->lzma.dist_align,
                     &s->lzma.rep0, ALIGN_BITS);
         }
     }
 }
References ALIGN_BITS, DIST_MODEL_END, DIST_MODEL_START, DIST_SLOTS, limit(), lzma_get_dist_state(), lzma_len(), lzma_state_match(), rc_bittree(), rc_bittree_reverse(), rc_direct(), and s.
Referenced by lzma_main().
lzma_props()
static bool XZ_FUNC lzma_props (struct xz_dec_lzma2 * s, uint8_t props) static
Definition at line 801 of file xz_dec_lzma2.c.
 {
     if (props > (4 * 5 + 4) * 9 + 8)
         return false;
     s->lzma.pos_mask = 0;
     while (props >= 9 * 5) {
         props -= 9 * 5;
         ++s->lzma.pos_mask;
     }
     s->lzma.pos_mask = (1 << s->lzma.pos_mask) - 1;
     s->lzma.literal_pos_mask = 0;
     while (props >= 9) {
         props -= 9;
         ++s->lzma.literal_pos_mask;
     }
     s->lzma.lc = props;
     if (s->lzma.lc + s->lzma.literal_pos_mask > 4)
         return false;
     s->lzma.literal_pos_mask = (1 << s->lzma.literal_pos_mask) - 1;
     lzma_reset(s);
     return true;
 }
References lzma_reset(), and s.
Referenced by xz_dec_lzma2_run().
lzma_rep_match()
static void XZ_FUNC lzma_rep_match (struct xz_dec_lzma2 * s, uint32_t pos_state) static
Definition at line 690 of file xz_dec_lzma2.c.
 {
     uint32_t tmp;
     if (!rc_bit(&s->rc, &s->lzma.is_rep0[s->lzma.state])) {
         if (!rc_bit(&s->rc, &s->lzma.is_rep0_long[
                 s->lzma.state][pos_state])) {
             lzma_state_short_rep(&s->lzma.state);
             s->lzma.len = 1;
             return;
         }
     } else {
         if (!rc_bit(&s->rc, &s->lzma.is_rep1[s->lzma.state])) {
             tmp = s->lzma.rep1;
         } else {
             if (!rc_bit(&s->rc, &s->lzma.is_rep2[s->lzma.state])) {
                 tmp = s->lzma.rep2;
             } else {
                 tmp = s->lzma.rep3;
                 s->lzma.rep3 = s->lzma.rep2;
             }
             s->lzma.rep2 = s->lzma.rep1;
         }
         s->lzma.rep1 = s->lzma.rep0;
         s->lzma.rep0 = tmp;
     }
     lzma_state_long_rep(&s->lzma.state);
     lzma_len(s, &s->lzma.rep_len_dec, pos_state);
 }
References lzma_len(), lzma_state_long_rep(), lzma_state_short_rep(), rc_bit(), and s.
Referenced by lzma_main().
lzma_reset()
static void XZ_FUNC lzma_reset (struct xz_dec_lzma2 * s) static
Definition at line 769 of file xz_dec_lzma2.c.
 {
     uint16_t *probs;
     size_t i;
     s->lzma.state = STATE_LIT_LIT;
     s->lzma.rep0 = 0;
     s->lzma.rep1 = 0;
     s->lzma.rep2 = 0;
     s->lzma.rep3 = 0;
     /*
      * All probabilities are initialized to the same value. This hack
      * makes the code smaller by avoiding a separate loop for each
      * probability array.
      *
      * This could be optimized so that only that part of literal
      * probabilities that are actually required. In the common case
      * we would write 12 KiB less.
      */
     probs = s->lzma.is_match[0];
     for (i = 0; i < PROBS_TOTAL; ++i)
         probs[i] = RC_BIT_MODEL_TOTAL / 2;
     rc_reset(&s->rc);
 }
References i, PROBS_TOTAL, RC_BIT_MODEL_TOTAL, rc_reset(), s, and STATE_LIT_LIT.
Referenced by lzma_props(), and xz_dec_lzma2_run().
rc_bit()
static __always_inline int XZ_FUNC rc_bit (struct rc_dec * rc, uint16_t * prob) static
Definition at line 499 of file xz_dec_lzma2.c.
 {
     uint32_t bound;
     int bit;
     rc_normalize(rc);
     bound = (rc->range >> RC_BIT_MODEL_TOTAL_BITS) * *prob;
     if (rc->code < bound) {
         rc->range = bound;
         *prob += (RC_BIT_MODEL_TOTAL - *prob) >> RC_MOVE_BITS;
         bit = 0;
     } else {
         rc->range -= bound;
         rc->code -= bound;
         *prob -= *prob >> RC_MOVE_BITS;
         bit = 1;
     }
     return bit;
 }
References rc, RC_BIT_MODEL_TOTAL, RC_BIT_MODEL_TOTAL_BITS, RC_MOVE_BITS, and rc_normalize().
Referenced by lzma_len(), lzma_literal(), lzma_main(), lzma_rep_match(), rc_bittree(), and rc_bittree_reverse().
rc_bittree()
static __always_inline uint32_t XZ_FUNC rc_bittree (struct rc_dec * rc, uint16_t * probs, uint32_t limit) static
Definition at line 521 of file xz_dec_lzma2.c.
 {
     uint32_t symbol = 1;
     do {
         if (rc_bit(rc, &probs[symbol]))
             symbol = (symbol << 1) + 1;
         else
             symbol <<= 1;
     } while (symbol < limit);
     return symbol;
 }
References limit(), rc, and rc_bit().
Referenced by lzma_len(), lzma_literal(), and lzma_match().
rc_bittree_reverse()
static __always_inline void XZ_FUNC rc_bittree_reverse (struct rc_dec * rc, uint16_t * probs, uint32_t * dest, uint32_t limit) static
Definition at line 537 of file xz_dec_lzma2.c.
 {
     uint32_t symbol = 1;
     uint32_t i = 0;
     do {
         if (rc_bit(rc, &probs[symbol])) {
             symbol = (symbol << 1) + 1;
             *dest += 1 << i;
         } else {
             symbol <<= 1;
         }
     } while (++i < limit);
 }
References i, limit(), rc, and rc_bit().
Referenced by lzma_match().
rc_direct()
static void XZ_FUNC rc_direct (struct rc_dec * rc, uint32_t * dest, uint32_t limit) inline static
Definition at line 554 of file xz_dec_lzma2.c.
 {
     uint32_t mask;
     do {
         rc_normalize(rc);
         rc->range >>= 1;
         rc->code -= rc->range;
         mask = (uint32_t)0 - (rc->code >> 31);
         rc->code += rc->range & mask;
         *dest = (*dest << 1) + (mask + 1);
     } while (--limit > 0);
 }
References limit(), rc, and rc_normalize().
Referenced by lzma_match().
rc_is_finished()
static bool XZ_FUNC rc_is_finished (const struct rc_dec * rc) inline static
Definition at line 474 of file xz_dec_lzma2.c.
 {
     return rc->code == 0;
 }
References rc.
Referenced by xz_dec_lzma2_run().
rc_limit_exceeded()
static bool XZ_FUNC rc_limit_exceeded (const struct rc_dec * rc) inline static
Definition at line 465 of file xz_dec_lzma2.c.
 {
     return rc->in_pos > rc->in_limit;
 }
References rc.
Referenced by lzma_main().
rc_normalize()
static __always_inline void XZ_FUNC rc_normalize (struct rc_dec * rc) static
Definition at line 480 of file xz_dec_lzma2.c.
 {
     if (rc->range < RC_TOP_VALUE) {
         rc->range <<= RC_SHIFT_BITS;
         rc->code = (rc->code << RC_SHIFT_BITS) + rc->in[rc->in_pos++];
     }
 }
References rc, RC_SHIFT_BITS, and RC_TOP_VALUE.
Referenced by lzma_main(), rc_bit(), and rc_direct().
rc_read_init()
static bool XZ_FUNC rc_read_init (struct rc_dec * rc, struct xz_buf * b) static
Definition at line 451 of file xz_dec_lzma2.c.
 {
     while (rc->init_bytes_left > 0) {
         if (b->in_pos == b->in_size)
             return false;
         rc->code = (rc->code << 8) + b->in[b->in_pos++];
         --rc->init_bytes_left;
     }
     return true;
 }
References xz_buf::in, xz_buf::in_pos, xz_buf::in_size, and rc.
Referenced by xz_dec_lzma2_run().
rc_reset()
static void XZ_FUNC rc_reset (struct rc_dec * rc) static
Definition at line 440 of file xz_dec_lzma2.c.
 {
     rc->range = (uint32_t)-1;
     rc->code = 0;
     rc->init_bytes_left = RC_INIT_BYTES;
 }
References rc, and RC_INIT_BYTES.
Referenced by lzma_reset(), and xz_dec_lzma2_run().
xz_dec_lzma2_create()
XZ_EXTERN struct xz_dec_lzma2* XZ_FUNC xz_dec_lzma2_create (enum xz_mode mode, uint32_t dict_max)
Definition at line 1103 of file xz_dec_lzma2.c.
 {
     struct xz_dec_lzma2 *s = kmalloc(sizeof(*s), GFP_KERNEL);
     if (s == NULL)
         return NULL;
     s->dict.mode = mode;
     s->dict.size_max = dict_max;
     if (DEC_IS_PREALLOC(mode)) {
         s->dict.buf = vmalloc(dict_max);
         if (s->dict.buf == NULL) {
             kfree(s);
             return NULL;
         }
     } else if (DEC_IS_DYNALLOC(mode)) {
         s->dict.buf = NULL;
         s->dict.allocated = 0;
     }
     return s;
 }
References DEC_IS_DYNALLOC, DEC_IS_PREALLOC, kfree, kmalloc, NULL, s, and vmalloc.
Referenced by xz_dec_init().
xz_dec_lzma2_end()
XZ_EXTERN void XZ_FUNC xz_dec_lzma2_end (struct xz_dec_lzma2 * s)
Definition at line 1165 of file xz_dec_lzma2.c.
 {
     if (DEC_IS_MULTI(s->dict.mode))
         vfree(s->dict.buf);
     kfree(s);
 }
References DEC_IS_MULTI, kfree, s, and vfree.
Referenced by xz_dec_end().
xz_dec_lzma2_reset()
XZ_EXTERN enum xz_ret XZ_FUNC xz_dec_lzma2_reset (struct xz_dec_lzma2 * s, uint8_t props)
Definition at line 1127 of file xz_dec_lzma2.c.
 {
     /* This limits dictionary size to 3 GiB to keep parsing simpler. */
     if (props > 39)
         return XZ_OPTIONS_ERROR;
     s->dict.size = 2 + (props & 1);
     s->dict.size <<= (props >> 1) + 11;
     if (DEC_IS_MULTI(s->dict.mode)) {
         if (s->dict.size > s->dict.size_max)
             return XZ_MEMLIMIT_ERROR;
         s->dict.end = s->dict.size;
         if (DEC_IS_DYNALLOC(s->dict.mode)) {
             if (s->dict.allocated < s->dict.size) {
                 vfree(s->dict.buf);
                 s->dict.buf = vmalloc(s->dict.size);
                 if (s->dict.buf == NULL) {
                     s->dict.allocated = 0;
                     return XZ_MEM_ERROR;
                 }
             }
         }
     }
     s->lzma.len = 0;
     s->lzma2.sequence = SEQ_CONTROL;
     s->lzma2.need_dict_reset = true;
     s->temp.size = 0;
     return XZ_OK;
 }
References DEC_IS_DYNALLOC, DEC_IS_MULTI, NULL, s, vfree, vmalloc, XZ_MEM_ERROR, XZ_MEMLIMIT_ERROR, XZ_OK, and XZ_OPTIONS_ERROR.
xz_dec_lzma2_run()
XZ_EXTERN NOINLINE enum xz_ret XZ_FUNC xz_dec_lzma2_run (struct xz_dec_lzma2 * s, struct xz_buf * b)
Definition at line 933 of file xz_dec_lzma2.c.
 {
     uint32_t tmp;
     while (b->in_pos < b->in_size || s->lzma2.sequence == SEQ_LZMA_RUN) {
         switch (s->lzma2.sequence) {
         case SEQ_CONTROL:
             /*
              * LZMA2 control byte
              *
              * Exact values:
              *   0x00   End marker
              *   0x01   Dictionary reset followed by
              *          an uncompressed chunk
              *   0x02   Uncompressed chunk (no dictionary reset)
              *
              * Highest three bits (s->control & 0xE0):
              *   0xE0   Dictionary reset, new properties and state
              *          reset, followed by LZMA compressed chunk
              *   0xC0   New properties and state reset, followed
              *          by LZMA compressed chunk (no dictionary
              *          reset)
              *   0xA0   State reset using old properties,
              *          followed by LZMA compressed chunk (no
              *          dictionary reset)
              *   0x80   LZMA chunk (no dictionary or state reset)
              *
              * For LZMA compressed chunks, the lowest five bits
              * (s->control & 1F) are the highest bits of the
              * uncompressed size (bits 16-20).
              *
              * A new LZMA2 stream must begin with a dictionary
              * reset. The first LZMA chunk must set new
              * properties and reset the LZMA state.
              *
              * Values that don't match anything described above
              * are invalid and we return XZ_DATA_ERROR.
              */
             tmp = b->in[b->in_pos++];
             if (tmp == 0x00)
                 return XZ_STREAM_END;
             if (tmp >= 0xE0 || tmp == 0x01) {
                 s->lzma2.need_props = true;
                 s->lzma2.need_dict_reset = false;
                 dict_reset(&s->dict, b);
             } else if (s->lzma2.need_dict_reset) {
                 return XZ_DATA_ERROR;
             }
             if (tmp >= 0x80) {
                 s->lzma2.uncompressed = (tmp & 0x1F) << 16;
                 s->lzma2.sequence = SEQ_UNCOMPRESSED_1;
                 if (tmp >= 0xC0) {
                     /*
                      * When there are new properties,
                      * state reset is done at
                      * SEQ_PROPERTIES.
                      */
                     s->lzma2.need_props = false;
                     s->lzma2.next_sequence
                             = SEQ_PROPERTIES;
                 } else if (s->lzma2.need_props) {
                     return XZ_DATA_ERROR;
                 } else {
                     s->lzma2.next_sequence
                             = SEQ_LZMA_PREPARE;
                     if (tmp >= 0xA0)
                         lzma_reset(s);
                 }
             } else {
                 if (tmp > 0x02)
                     return XZ_DATA_ERROR;
                 s->lzma2.sequence = SEQ_COMPRESSED_0;
                 s->lzma2.next_sequence = SEQ_COPY;
             }
             break;
         case SEQ_UNCOMPRESSED_1:
             s->lzma2.uncompressed
                     += (uint32_t)b->in[b->in_pos++] << 8;
             s->lzma2.sequence = SEQ_UNCOMPRESSED_2;
             break;
         case SEQ_UNCOMPRESSED_2:
             s->lzma2.uncompressed
                     += (uint32_t)b->in[b->in_pos++] + 1;
             s->lzma2.sequence = SEQ_COMPRESSED_0;
             break;
         case SEQ_COMPRESSED_0:
             s->lzma2.compressed
                     = (uint32_t)b->in[b->in_pos++] << 8;
             s->lzma2.sequence = SEQ_COMPRESSED_1;
             break;
         case SEQ_COMPRESSED_1:
             s->lzma2.compressed
                     += (uint32_t)b->in[b->in_pos++] + 1;
             s->lzma2.sequence = s->lzma2.next_sequence;
             break;
         case SEQ_PROPERTIES:
             if (!lzma_props(s, b->in[b->in_pos++]))
                 return XZ_DATA_ERROR;
             s->lzma2.sequence = SEQ_LZMA_PREPARE;
         case SEQ_LZMA_PREPARE:
             if (s->lzma2.compressed < RC_INIT_BYTES)
                 return XZ_DATA_ERROR;
             if (!rc_read_init(&s->rc, b))
                 return XZ_OK;
             s->lzma2.compressed -= RC_INIT_BYTES;
             s->lzma2.sequence = SEQ_LZMA_RUN;
         case SEQ_LZMA_RUN:
             /*
              * Set dictionary limit to indicate how much we want
              * to be encoded at maximum. Decode new data into the
              * dictionary. Flush the new data from dictionary to
              * b->out. Check if we finished decoding this chunk.
              * In case the dictionary got full but we didn't fill
              * the output buffer yet, we may run this loop
              * multiple times without changing s->lzma2.sequence.
              */
             dict_limit(&s->dict, min_t(size_t,
                     b->out_size - b->out_pos,
                     s->lzma2.uncompressed));
             if (!lzma2_lzma(s, b))
                 return XZ_DATA_ERROR;
             s->lzma2.uncompressed -= dict_flush(&s->dict, b);
             if (s->lzma2.uncompressed == 0) {
                 if (s->lzma2.compressed > 0 || s->lzma.len > 0
                         || !rc_is_finished(&s->rc))
                     return XZ_DATA_ERROR;
                 rc_reset(&s->rc);
                 s->lzma2.sequence = SEQ_CONTROL;
             } else if (b->out_pos == b->out_size
                     || (b->in_pos == b->in_size
                         && s->temp.size
                         < s->lzma2.compressed)) {
                 return XZ_OK;
             }
             break;
         case SEQ_COPY:
             dict_uncompressed(&s->dict, b, &s->lzma2.compressed);
             if (s->lzma2.compressed > 0)
                 return XZ_OK;
             s->lzma2.sequence = SEQ_CONTROL;
             break;
         }
     }
     return XZ_OK;
 }
References dict_flush(), dict_limit(), dict_reset(), dict_uncompressed(), xz_buf::in, xz_buf::in_pos, xz_buf::in_size, lzma2_lzma(), lzma_props(), lzma_reset(), min_t, xz_buf::out_pos, xz_buf::out_size, RC_INIT_BYTES, rc_is_finished(), rc_read_init(), rc_reset(), s, XZ_DATA_ERROR, XZ_OK, and XZ_STREAM_END.