Fennix Userspace: Userspace/musl/include/iconv.h File Reference
iconv.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Macros
#define __NEED_size_t
Typedefs
typedef void * iconv_t
Functions
iconv_t iconv_open (const char *, const char *)
size_t iconv (iconv_t, char **__restrict, size_t *__restrict, char **__restrict, size_t *__restrict)
int iconv_close (iconv_t)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file iconv.h.
Typedef Documentation
iconv_t
typedef void* iconv_t
Definition at line 14 of file iconv.h.
Function Documentation
iconv()
size_t iconv (iconv_t , char ** __restrict, size_t * __restrict, char ** __restrict, size_t * __restrict)
iconv_close()
int iconv_close (iconv_t cd)
Definition at line 19 of file iconv-stubs.cpp.
{
     return 0;
 }
References free.
Referenced by _nl_free_domain_conv().
iconv_open()
iconv_t iconv_open (const char * tocode, const char * fromcode)
Definition at line 23 of file iconv-stubs.cpp.
{
     mlibc::infoLogger() << "iconv_open() is unimplemented! args: " << tocode << " and: " << fromcode << frg::endlog;
     if(!strcmp(tocode, "UTF-8") && !strcmp(fromcode, "UTF-8")) {
         mlibc::infoLogger() << "iconv_open() with UTF-8 on both is a no-op!" << frg::endlog;
         iconv_t cd = (iconv_t)1;
         return cd;
     }
     __ensure(!"iconv_open() not implemented");
     __builtin_unreachable();
 }
References __ensure, stateful_cd::base_cd, charmaps, combine_to_from(), EINVAL, errno, f, find_charmap(), mlibc::infoLogger, ISO2022_JP, malloc, stateful_cd::state, strcmp, t, UCS2, UTF_16, and UTF_32.
Referenced by _nl_init_domain_conv().