Fennix Userspace: Userspace/apps/base/busybox/networking/hostname.c File Reference
hostname.c File Reference
#include "libbb.h"
Functions
static void do_sethostname (char *s, int isfile)
int hostname_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
do_sethostname()
static void do_sethostname (char * s, int isfile) static
Definition at line 50 of file hostname.c.
 {
 //  if (!s)
 //      return;
     if (isfile) {
         parser_t *parser = config_open2(s, xfopen_for_read);
         while (config_read(parser, &s, 1, 1, "# \t", PARSE_NORMAL & ~PARSE_GREEDY)) {
             do_sethostname(s, 0);
         }
         if (ENABLE_FEATURE_CLEAN_UP)
             config_close(parser);
     } else if (sethostname(s, strlen(s))) {
 //      if (errno == EPERM)
 //          bb_error_msg_and_die(bb_msg_perm_denied_are_you_root);
         bb_simple_perror_msg_and_die("sethostname");
     }
 }
References bb_simple_perror_msg_and_die(), config_close(), config_open2(), config_read, PARSE_GREEDY, PARSE_NORMAL, parser, s, sethostname(), strlen(), and xfopen_for_read().
Referenced by hostname_main().
hostname_main()
int hostname_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 119 of file hostname.c.
 {
     enum {
         OPT_d = 0x1,
         OPT_f = 0x2,
         OPT_i = 0x4,
         OPT_s = 0x8,
         OPT_F = 0x10,
         OPT_dfi = 0x7,
     };
     unsigned opts;
     char *buf;
     char *hostname_str;
     /* dnsdomainname from net-tools 1.60, hostname 1.100 (2001-04-14),
      * supports hostname's options too (not just -v as manpage says) */
     opts = getopt32(argv, "dfisF:v", &hostname_str,
         "domain\0"     No_argument "d"
         "fqdn\0"       No_argument "f"
     //Enable if seen in active use in some distro:
     //  "long\0"       No_argument "f"
     //  "ip-address\0" No_argument "i"
     //  "short\0"      No_argument "s"
     //  "verbose\0"    No_argument "v"
         "file\0"       No_argument "F"
     );
     argv += optind;
     buf = safe_gethostname();
     if (ENABLE_DNSDOMAINNAME) {
         if (!ENABLE_HOSTNAME || applet_name[0] == 'd') {
             /* dnsdomainname */
             opts = OPT_d;
         }
     }
     if (opts & OPT_dfi) {
         /* Cases when we need full hostname (or its part) */
         struct hostent *hp;
         char *p;
         hp = xgethostbyname(buf);
         p = strchrnul(hp->h_name, '.');
         if (opts & OPT_f) {
             puts(hp->h_name);
         } else if (opts & OPT_s) {
             *p = '\0';
             puts(hp->h_name);
         } else if (opts & OPT_d) {
             if (*p)
                 puts(p + 1);
         } else /*if (opts & OPT_i)*/ {
             if (hp->h_length == sizeof(struct in_addr)) {
                 struct in_addr **h_addr_list = (struct in_addr **)hp->h_addr_list;
                 while (*h_addr_list) {
                     printf(h_addr_list[1] ? "%s " : "%s", inet_ntoa(**h_addr_list));
                     h_addr_list++;
                 }
                 bb_putchar('\n');
             }
         }
     } else if (opts & OPT_s) {
         strchrnul(buf, '.')[0] = '\0';
         puts(buf);
     } else if (opts & OPT_F) {
         /* Set the hostname */
         do_sethostname(hostname_str, 1);
     } else if (argv[0]) {
         /* Set the hostname */
         do_sethostname(argv[0], 0);
     } else {
         /* Just print the current hostname */
         puts(buf);
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         free(buf);
     return EXIT_SUCCESS;
 }
References applet_name, argv, bb_putchar(), buf, do_sethostname(), EXIT_SUCCESS, free, getopt32(), hostent::h_addr_list, hostent::h_length, hostent::h_name, inet_ntoa(), No_argument, OPT_d, OPT_F, OPT_f, OPT_i, OPT_s, optind, p, printf(), puts(), safe_gethostname(), strchrnul(), while(), and xgethostbyname().