Fennix Kernel: Memory::VirtualAllocation Class Reference
Memory::VirtualAllocation Class Reference
#include <va.hpp>
Data Structures
struct AllocatedPages
Public Member Functions
AllocatedPages RequestPages (size_t Count)
void FreePages (void *Address, size_t Count)
void MapTo (AllocatedPages ap, PageTable *Table)
VirtualAllocation (void *Base)
~VirtualAllocation ()
Data Fields
PageTable * Table
Private Member Functions
NewLock (MgrLock)
Private Attributes
std::list< AllocatedPages > AllocatedPagesList
void * BaseAddress
void * CurrentBase
Detailed Description
Definition at line 29 of file va.hpp.
Data Structure Documentation
Memory::VirtualAllocation::AllocatedPages
struct Memory::VirtualAllocation::AllocatedPages
Definition at line 32 of file va.hpp.
Data Fields
bool Free
size_t PageCount
void * PhysicalAddress
void * VirtualAddress
Constructor & Destructor Documentation
VirtualAllocation()
Memory::VirtualAllocation::VirtualAllocation (void * Base)
Definition at line 119 of file va.cpp.
         : BaseAddress(Base), CurrentBase(Base),
           Table((PageTable *)CPU::PageTable())
     {
         func("%#lx", Base);
     }
References func().
~VirtualAllocation()
Memory::VirtualAllocation::~VirtualAllocation ()
Definition at line 126 of file va.cpp.
     {
         /* No need to remap pages, the page table will be destroyed */
         Virtual vmm(this->Table);
         foreach (auto ap in AllocatedPagesList)
         {
             KernelAllocator.FreePages(ap.PhysicalAddress, ap.PageCount);
             for (size_t i = 0; i < ap.PageCount; i++)
             {
                 void *AddressToUnmap = (void *)((uintptr_t)ap.VirtualAddress + FROM_PAGES(i));
                 vmm.Unmap(AddressToUnmap);
             }
         }
     }
References AllocatedPagesList, FROM_PAGES, KernelAllocator, and Table.
Member Function Documentation
FreePages()
void Memory::VirtualAllocation::FreePages (void * Address, size_t Count)
Definition at line 80 of file va.cpp.
     {
         func("%#lx, %lld", Address, Count);
         SmartLock(MgrLock);
         foreach (auto &apl in AllocatedPagesList)
         {
             if (apl.VirtualAddress != Address)
                 continue;
             if (apl.PageCount != Count)
             {
                 error("Page count mismatch! (Allocated: %lld, Requested: %lld)",
                       apl.PageCount, Count);
                 return;
             }
             Virtual vmm(this->Table);
             for (size_t i = 0; i < Count; i++)
             {
                 void *AddressToUnmap = (void *)((uintptr_t)Address + FROM_PAGES(i));
                 vmm.Unmap(AddressToUnmap);
             }
             KernelAllocator.FreePages(Address, Count);
             apl.Free = true;
             debug("Freed region %#lx-%#lx", Address, (uintptr_t)Address + FROM_PAGES(Count));
             return;
         }
     }
References Address, AllocatedPagesList, debug, error, FROM_PAGES, func(), KernelAllocator, Table, and Memory::Virtual::Unmap().
MapTo()
void Memory::VirtualAllocation::MapTo (AllocatedPages ap, PageTable * Table)
Definition at line 111 of file va.cpp.
     {
         func("%#lx, %#lx", ap.VirtualAddress, TargetTable);
         Virtual vmm(TargetTable);
         vmm.Map(ap.VirtualAddress, ap.PhysicalAddress, FROM_PAGES(ap.PageCount), RW | KRsv | G);
     }
References FROM_PAGES, func(), Memory::G, Memory::KRsv, Memory::Virtual::Map(), Memory::VirtualAllocation::AllocatedPages::PageCount, Memory::VirtualAllocation::AllocatedPages::PhysicalAddress, Memory::RW, and Memory::VirtualAllocation::AllocatedPages::VirtualAddress.
Referenced by Tasking::TCB::TCB().
NewLock()
Memory::VirtualAllocation::NewLock (MgrLock) private
RequestPages()
VirtualAllocation::AllocatedPages Memory::VirtualAllocation::RequestPages (size_t Count)
Definition at line 28 of file va.cpp.
     {
         func("%lld", Count);
         void *pAddress = KernelAllocator.RequestPages(Count);
         memset(pAddress, 0, FROM_PAGES(Count));
         Virtual vmm(this->Table);
         SmartLock(MgrLock);
         forItr(itr, AllocatedPagesList)
         {
             if (likely(itr->Free == false))
                 continue;
             if (itr->PageCount == Count)
             {
                 itr->Free = false;
                 vmm.Map(itr->VirtualAddress, pAddress, FROM_PAGES(Count), RW | KRsv | G);
                 return *itr;
             }
             if (itr->PageCount > Count)
             {
                 /* Split the block */
                 void *vAddress = itr->VirtualAddress;
                 void *pAddress = itr->PhysicalAddress;
                 size_t PageCount = itr->PageCount;
                 AllocatedPagesList.erase(itr);
                 AllocatedPagesList.push_back({(void *)((uintptr_t)pAddress + FROM_PAGES(Count)),
                                               (void *)((uintptr_t)vAddress + FROM_PAGES(Count)),
                                               PageCount - Count, true});
                 AllocatedPagesList.push_back({pAddress, vAddress, Count, false});
                 vmm.Map(vAddress, pAddress, FROM_PAGES(Count), RW | KRsv | G);
                 debug("Split region %#lx-%#lx", vAddress, (uintptr_t)vAddress + FROM_PAGES(Count));
                 debug("Free region %#lx-%#lx", (uintptr_t)vAddress + FROM_PAGES(Count), (uintptr_t)vAddress + FROM_PAGES(PageCount - Count));
                 return AllocatedPagesList.back();
             }
         }
         /* Allocate new region */
         void *vAddress = CurrentBase;
         vmm.Map(vAddress, pAddress, FROM_PAGES(Count), RW | KRsv | G);
         AllocatedPagesList.push_back({pAddress, vAddress, Count, false});
         debug("New region %#lx-%#lx", vAddress, (uintptr_t)vAddress + FROM_PAGES(Count));
         CurrentBase = (void *)((uintptr_t)CurrentBase + FROM_PAGES(Count));
         assert(USER_ALLOC_END > (uintptr_t)CurrentBase);
         return AllocatedPagesList.back();
     }
References AllocatedPagesList, assert, CurrentBase, debug, FROM_PAGES, func(), Memory::G, KernelAllocator, Memory::KRsv, likely, Memory::Virtual::Map(), memset(), Memory::RW, and Table.
Referenced by Tasking::TCB::TCB().
Field Documentation
AllocatedPagesList
std::list<AllocatedPages> Memory::VirtualAllocation::AllocatedPagesList private
Definition at line 43 of file va.hpp.
Referenced by FreePages(), RequestPages(), and ~VirtualAllocation().
BaseAddress
void* Memory::VirtualAllocation::BaseAddress private
Definition at line 44 of file va.hpp.
CurrentBase
void* Memory::VirtualAllocation::CurrentBase private
Definition at line 45 of file va.hpp.
Referenced by RequestPages().
Table
PageTable* Memory::VirtualAllocation::Table
Definition at line 48 of file va.hpp.
Referenced by FreePages(), RequestPages(), and ~VirtualAllocation().
The documentation for this class was generated from the following files:
Kernel/include/memory/va.hpp
Kernel/core/memory/va.cpp