Fennix Kernel: Kernel/Library/MemorySetSIMD.cpp File Reference
MemorySetSIMD.cpp File Reference
#include <convert.h>
#include <memory.hpp>
#include <limits.h>
#include <debug.h>
#include <cpu.hpp>
Functions
EXTERNC void * memset_sse (void *dest, int c, size_t n)
EXTERNC void * memset_sse2 (void *dest, int c, size_t n)
EXTERNC void * memset_sse3 (void *dest, int c, size_t n)
EXTERNC void * memset_ssse3 (void *dest, int c, size_t n)
EXTERNC void * memset_sse4_1 (void *dest, int c, size_t n)
EXTERNC void * memset_sse4_2 (void *dest, int c, size_t n)
Function Documentation
memset_sse()
EXTERNC void* memset_sse (void * dest, int c, size_t n)
Definition at line 15 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References memset_unsafe().
Referenced by __memset_chk().
memset_sse2()
EXTERNC void* memset_sse2 (void * dest, int c, size_t n)
Definition at line 20 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References memset_unsafe().
Referenced by __memset_chk().
memset_sse3()
EXTERNC void* memset_sse3 (void * dest, int c, size_t n)
Definition at line 25 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References memset_unsafe().
Referenced by __memset_chk().
memset_sse4_1()
EXTERNC void* memset_sse4_1 (void * dest, int c, size_t n)
Definition at line 35 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References memset_unsafe().
Referenced by __memset_chk().
memset_sse4_2()
EXTERNC void* memset_sse4_2 (void * dest, int c, size_t n)
Definition at line 40 of file MemorySetSIMD.cpp.
 {
 #if defined(a64)
     char *d = (char *)dest;
     if (((uintptr_t)d & 0xF) == 0)
     {
         size_t num_vectors = n / 16;
         for (size_t i = 0; i < num_vectors; i++)
         {
             asmv("movd %0, %%xmm0\n"
                  "pshufd $0, %%xmm0, %%xmm0\n"
                  "movdqa %%xmm0, (%1)\n"
                  :
                  : "r"(c), "r"(d)
                  : "xmm0");
             d += 16;
         }
         n -= num_vectors * 16;
     }
     memset_unsafe(d, c, n);
 #endif
     return dest;
 }
References asmv, and memset_unsafe().
Referenced by __memset_chk().
memset_ssse3()
EXTERNC void* memset_ssse3 (void * dest, int c, size_t n)
Definition at line 30 of file MemorySetSIMD.cpp.
 {
     return memset_unsafe(dest, c, n);
 }
References memset_unsafe().
Referenced by __memset_chk().