Fennix Kernel: Memory::SmartHeap Class Reference
Memory::SmartHeap Class Reference
#include <smart_heap.hpp>
Public Member Functions
auto Get ()
SmartHeap (std::size_t Size, VirtualMemoryArea *vma=nullptr)
~SmartHeap ()
void * operator-> ()
void * operator* ()
operator void * ()
operator const char * ()
operator uintptr_t ()
operator uint8_t * ()
void operator= (void *Address)
Private Attributes
VirtualMemoryArea * vma = nullptr
void * Object = nullptr
std::size_t ObjectSize = 0
Detailed Description
Definition at line 28 of file smart_heap.hpp.
Constructor & Destructor Documentation
SmartHeap()
Memory::SmartHeap::SmartHeap (std::size_t Size, VirtualMemoryArea * vma = nullptr)
Definition at line 5 of file smart_heap.cpp.
     {
         if (vma)
         {
             this->vma = vma;
             this->Object = vma->RequestPages(TO_PAGES(Size));
         }
         else
             this->Object = kmalloc(Size);
         this->ObjectSize = Size;
         memset(this->Object, 0, Size);
     }
References kmalloc, memset(), Object, ObjectSize, Memory::VirtualMemoryArea::RequestPages(), Size, TO_PAGES, and vma.
~SmartHeap()
Memory::SmartHeap::~SmartHeap ()
Definition at line 18 of file smart_heap.cpp.
     {
         if (this->vma)
             this->vma->FreePages(this->Object, TO_PAGES(this->ObjectSize));
         else
             kfree(this->Object);
     }
References Memory::VirtualMemoryArea::FreePages(), kfree, Object, ObjectSize, TO_PAGES, and vma.
Member Function Documentation
Get()
auto Memory::SmartHeap::Get () inline
Definition at line 36 of file smart_heap.hpp.
 { return Object; }
References Object.
Referenced by Execute::GetBinaryType(), linux_readv(), linux_writev(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), sys_open(), sys_read(), and sys_write().
operator const char *()
Memory::SmartHeap::operator const char * () inline
Definition at line 45 of file smart_heap.hpp.
         {
             return r_cst(const char *, Object);
         }
References Object.
operator uint8_t *()
Memory::SmartHeap::operator uint8_t * () inline
Definition at line 55 of file smart_heap.hpp.
         {
             return r_cst(uint8_t *, Object);
         }
References Object.
operator uintptr_t()
Memory::SmartHeap::operator uintptr_t () inline
Definition at line 50 of file smart_heap.hpp.
         {
             return r_cst(uintptr_t, Object);
         }
References Object.
operator void *()
Memory::SmartHeap::operator void * () inline
Definition at line 43 of file smart_heap.hpp.
 { return Object; }
References Object.
operator*()
void* Memory::SmartHeap::operator* () inline
Definition at line 42 of file smart_heap.hpp.
 { return Object; }
References Object.
operator->()
void* Memory::SmartHeap::operator-> () inline
Definition at line 41 of file smart_heap.hpp.
 { return Object; }
References Object.
operator=()
void Memory::SmartHeap::operator= (void * Address) inline
Definition at line 60 of file smart_heap.hpp.
         {
             memcpy(Object, Address, ObjectSize);
         }
References Address, memcpy(), Object, and ObjectSize.
Field Documentation
Object
void* Memory::SmartHeap::Object = nullptr private
Definition at line 32 of file smart_heap.hpp.
Referenced by Get(), operator const char *(), operator uint8_t *(), operator uintptr_t(), operator void *(), operator*(), operator->(), operator=(), SmartHeap(), and ~SmartHeap().
ObjectSize
std::size_t Memory::SmartHeap::ObjectSize = 0 private
Definition at line 33 of file smart_heap.hpp.
Referenced by operator=(), SmartHeap(), and ~SmartHeap().
vma
VirtualMemoryArea* Memory::SmartHeap::vma = nullptr private
Definition at line 31 of file smart_heap.hpp.
Referenced by SmartHeap(), and ~SmartHeap().
The documentation for this class was generated from the following files:
Kernel/include/memory/smart_heap.hpp
Kernel/core/memory/smart_heap.cpp