Fennix Userspace: Userspace/mlibc/options/ansi/musl-generic-math/__sindf.c File Reference
__sindf.c File Reference
#include "libm.h"
Functions
float __sindf (double x)
Variables
static const double S1 = -0x15555554cbac77.0p-55
static const double S2 = 0x111110896efbb2.0p-59
static const double S3 = -0x1a00f9e2cae774.0p-65
static const double S4 = 0x16cd878c3b46a7.0p-71
Function Documentation
__sindf()
float __sindf (double x)
Definition at line 26 of file __sindf.c.
 {
     double_t r, s, w, z;
     /* Try to optimize for parallel evaluation as in __tandf.c. */
     z = x*x;
     w = z*z;
     r = S3 + z*S4;
     s = z*x;
     return (x + s*(S1 + z*S2)) + s*w*r;
 }
References r, S1, S2, S3, S4, and x.
Referenced by cosf(), sin_pi(), sincosf(), and sinf().
Variable Documentation
S1
const double S1 = -0x15555554cbac77.0p-55 static
Definition at line 21 of file __sindf.c.
Referenced by __sindf().
S2
const double S2 = 0x111110896efbb2.0p-59 static
Definition at line 22 of file __sindf.c.
Referenced by __sindf().
S3
const double S3 = -0x1a00f9e2cae774.0p-65 static
Definition at line 23 of file __sindf.c.
Referenced by __sindf().
S4
const double S4 = 0x16cd878c3b46a7.0p-71 static
Definition at line 24 of file __sindf.c.
Referenced by __sindf().