Fennix: Kernel/Kernel.cpp File Reference
Kernel.cpp File Reference
#include "kernel.h"
#include <boot/protocols/multiboot2.h>
#include <filesystem/ustar.hpp>
#include <ints.hpp>
#include <memory.hpp>
#include <convert.h>
#include <printf.h>
#include <lock.hpp>
#include <uart.hpp>
#include <debug.h>
#include <smp.hpp>
#include <cargs.h>
#include <io.h>
#include "Core/smbios.hpp"
#include "Tests/t.h"
#include <intrin.hpp>
Typedefs
typedef void(* CallPtr) (void)
Functions
NewLock (KernelLock)
__aligned (16) BootInfo bInfo
EXTERNC void putchar (char c)
EXTERNC void KPrint (const char *Format,...)
EXTERNC NIF void Main (BootInfo *Info)
EXTERNC __no_stack_protector NIF void Entry (BootInfo *Info)
EXTERNC __no_stack_protector void BeforeShutdown (bool Reboot)
EXTERNC void TaskingPanic ()
Variables
bool DebuggerIsAttached = false
Video::Display * Display = nullptr
SymbolResolver::Symbols * KernelSymbolTable = nullptr
Power::Power * PowerManager = nullptr
PCI::PCI * PCIManager = nullptr
Tasking::Task * TaskManager = nullptr
Time::time * TimeManager = nullptr
VirtualFileSystem::Virtual * vfs = nullptr
VirtualFileSystem::Virtual * bootanim_vfs = nullptr
Time::Clock BootClock
KernelConfig Config
bool EnableProfiler
int PutCharBufferIndex = 0
CallPtr __init_array_start [0]
CallPtr __init_array_end [0]
CallPtr __fini_array_start [0]
CallPtr __fini_array_end [0]
Typedef Documentation
CallPtr
typedef void(* CallPtr) (void)
Definition at line 470 of file Kernel.cpp.
Function Documentation
__aligned()
__aligned (16)
Definition at line 193 of file Kernel.cpp.
 {};
BeforeShutdown()
EXTERNC __no_stack_protector void BeforeShutdown (bool Reboot)
Definition at line 505 of file Kernel.cpp.
 {
     UNUSED(Reboot);
     /* TODO: Announce shutdown */
     trace("\n\n\n#################### SYSTEM SHUTTING DOWN ####################\n\n");
     if (RecoveryScreen)
         delete RecoveryScreen, RecoveryScreen = nullptr;
     if (NIManager)
         delete NIManager, NIManager = nullptr;
     if (DiskManager)
         delete DiskManager, DiskManager = nullptr;
     if (DriverManager)
         delete DriverManager, DriverManager = nullptr;
     if (TaskManager)
     {
         TaskManager->SignalShutdown();
         delete TaskManager, TaskManager = nullptr;
     }
     if (vfs)
         delete vfs, vfs = nullptr;
     if (bootanim_vfs)
         delete bootanim_vfs, bootanim_vfs = nullptr;
     if (TimeManager)
         delete TimeManager, TimeManager = nullptr;
     if (Display)
         delete Display, Display = nullptr;
     // PowerManager should not be called
     // https://wiki.osdev.org/Calling_Global_Constructors
     debug("Calling destructors...");
     for (CallPtr *func = __fini_array_start; func != __fini_array_end; func++)
         (*func)();
     debug("Done.");
 }
References __fini_array_end, __fini_array_start, bootanim_vfs, debug, DiskManager, Display, DriverManager, NIManager, RecoveryScreen, Tasking::Task::SignalShutdown(), TaskManager, TimeManager, trace, UNUSED, and vfs.
Referenced by KernelShutdownThread().
Entry()
EXTERNC __no_stack_protector NIF void Entry (BootInfo * Info)
Definition at line 474 of file Kernel.cpp.
 {
     trace("Hello, World!");
     if (strcmp(CPU::Hypervisor(), x86_CPUID_VENDOR_TCG) == 0)
     {
         debug("\n\n----------------------------------------\nDEBUGGER DETECTED\n----------------------------------------\n\n");
         DebuggerIsAttached = true;
     }
     // https://wiki.osdev.org/Calling_Global_Constructors
     for (CallPtr *func = __init_array_start; func != __init_array_end; func++)
         (*func)();
     InitializeMemoryManagement(Info);
 #ifdef DEBUG
     /* I had to do this because KernelAllocator
      * is a global constructor but we need
      * memory management to be initialized first.
      */
     TestString();
     TestMemoryAllocation();
 #endif
     EnableProfiler = true;
     Main(Info);
 }
References __init_array_end, __init_array_start, debug, DebuggerIsAttached, EnableProfiler, CPU::Hypervisor(), Info, InitializeMemoryManagement(), Main(), strcmp(), trace, and x86_CPUID_VENDOR_TCG.
KPrint()
EXTERNC void KPrint (const char * Format, ...)
Definition at line 230 of file Kernel.cpp.
 {
     SmartLock(KernelLock);
     if (TimeManager)
     {
         uint64_t Nanoseconds = TimeManager->GetNanosecondsSinceClassCreation();
         if (Nanoseconds != 0)
         {
             printf("\eCCCCCC[\e00AEFF%lu.%07lu\eCCCCCC] ",
                    Nanoseconds / 10000000,
                    Nanoseconds % 10000000);
         }
     }
     va_list args;
     va_start(args, Format);
     vprintf(Format, args);
     va_end(args);
     printf("\eCCCCCC\n");
     if (!Config.BootAnimation && Display)
         Display->SetBuffer(0);
 }
References args, KernelConfig::BootAnimation, Config, Display, Time::time::GetNanosecondsSinceClassCreation(), Time::Nanoseconds, printf, Video::Display::SetBuffer(), TimeManager, va_end(), va_start(), and vprintf().
Referenced by __chk_fail(), __stack_chk_fail(), Driver::Driver::Driver(), Time::time::FindTimers(), InterruptDescriptorTable::Init(), Interrupts::Initialize(), CPU::InitializeFeatures(), KernelMainThread(), ACPI::MADT::MADT(), Main(), NetworkInterfaceManager::NetworkInterface::NetworkInterface(), ParseConfig(), StartCPU(), Tasking::Task::Task(), and APIC::Timer::Timer().
Main()
EXTERNC NIF void Main (BootInfo * Info)
Definition at line 255 of file Kernel.cpp.
 {
     BootClock = Time::ReadClock();
     memcpy(&bInfo, Info, sizeof(BootInfo));
     debug("BootInfo structure is at %p", bInfo);
     Display = new Video::Display(bInfo.Framebuffer[0]);
     KPrint("%s - %s [\e058C19%s\eFFFFFF]", KERNEL_NAME, KERNEL_VERSION, GIT_COMMIT_SHORT);
     /**************************************************************************************/
     KPrint("CPU: \e058C19%s \e8822AA%s \e8888FF%s", CPU::Hypervisor(), CPU::Vendor(), CPU::Name());
     KPrint("Initializing GDT and IDT");
     Interrupts::Initialize(0);
     KPrint("Reading Kernel Parameters");
     ParseConfig((char *)bInfo.Kernel.CommandLine, &Config);
     if (Config.BootAnimation)
     {
         Display->CreateBuffer(0, 0, 1);
         Display->SetDoNotScroll(true, 1);
         Video::ScreenBuffer *buf = Display->GetBuffer(1);
         Video::FontInfo fi = Display->GetCurrentFont()->GetInfo();
         Display->SetBufferCursor(1, 0, buf->Height - fi.Height);
         PutCharBufferIndex = 1;
         printf("Fennix Operating System - %s [\e058C19%s\eFFFFFF]\n", KERNEL_VERSION, GIT_COMMIT_SHORT);
         Display->SetBuffer(1);
         PutCharBufferIndex = 0;
     }
     KPrint("Initializing CPU Features");
     CPU::InitializeFeatures(0);
     if (DebuggerIsAttached)
         KPrint("\eFFA500Kernel debugger detected.");
     KPrint("Loading Kernel Symbols");
     KernelSymbolTable = new SymbolResolver::Symbols((uintptr_t)Info->Kernel.FileBase);
     KPrint("Initializing Power Manager");
     PowerManager = new Power::Power;
     KPrint("Initializing PCI Manager");
     PCIManager = new PCI::PCI;
     foreach (auto Device in PCIManager->GetDevices())
     {
         KPrint("PCI: \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s",
                PCI::Descriptors::GetVendorName(Device->VendorID),
                PCI::Descriptors::GetDeviceName(Device->VendorID, Device->DeviceID),
                PCI::Descriptors::DeviceClasses[Device->Class],
                PCI::Descriptors::GetSubclassName(Device->Class, Device->Subclass),
                PCI::Descriptors::GetProgIFName(Device->Class, Device->Subclass, Device->ProgIF));
     }
     KPrint("Enabling Interrupts on Bootstrap Processor");
     Interrupts::Enable(0);
 #if defined(a64)
     PowerManager->InitDSDT();
 #elif defined(a32)
     // FIXME: Add ACPI support for i386
 #elif defined(aa64)
 #endif
     KPrint("Initializing Timers");
     TimeManager = new Time::time;
     TimeManager->FindTimers(PowerManager->GetACPI());
     KPrint("Initializing Bootstrap Processor Timer");
     Interrupts::InitializeTimer(0);
     KPrint("Initializing SMP");
     SMP::Initialize(PowerManager->GetMADT());
     if (SMBIOS::CheckSMBIOS())
     {
         SMBIOS::SMBIOSEntryPoint *smbios = SMBIOS::GetSMBIOSEntryPoint();
         SMBIOS::SMBIOSBIOSInformation *bios = SMBIOS::GetBIOSInformation();
         SMBIOS::SMBIOSSystemInformation *system = SMBIOS::GetSystemInformation();
         SMBIOS::SMBIOSBaseBoardInformation *baseboard = SMBIOS::GetBaseBoardInformation();
         debug("SMBIOS: %p", smbios);
         debug("BIOS: %p", bios);
         debug("System: %p", system);
         debug("Baseboard: %p", baseboard);
         if (smbios)
             KPrint("SMBIOS: \eCCCCCCString:\e8888FF%.4s \eCCCCCCVersion (Major Minor):\e8888FF%d %d \eCCCCCCTable:\e8888FF%#x \eCCCCCCLength:\e8888FF%d",
                    smbios->EntryPointString, smbios->MajorVersion, smbios->MinorVersion,
                    smbios->TableAddress, smbios->TableLength);
         else
             KPrint("SMBIOS: \e8888FFSMBIOS found but not supported?");
         if (bios)
         {
             const char *BIOSVendor = bios->GetString(bios->Vendor);
             const char *BIOSVersion = bios->GetString(bios->Version);
             const char *BIOSReleaseDate = bios->GetString(bios->ReleaseDate);
             debug("%d %d %d", bios->Vendor, bios->Version, bios->ReleaseDate);
             KPrint("BIOS: \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s",
                    BIOSVendor, BIOSVersion, BIOSReleaseDate);
         }
         if (system)
         {
             const char *SystemManufacturer = system->GetString(system->Manufacturer);
             const char *SystemProductName = system->GetString(system->ProductName);
             const char *SystemVersion = system->GetString(system->Version);
             const char *SystemSerialNumber = system->GetString(system->SerialNumber);
             const char *SystemSKU = system->GetString(system->SKU);
             const char *SystemFamily = system->GetString(system->Family);
             debug("%d %d %d %d %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c %d %d", system->Manufacturer, system->ProductName, system->Version,
                   system->SerialNumber,
                   system->UUID[0], system->UUID[1], system->UUID[2], system->UUID[3],
                   system->UUID[4], system->UUID[5], system->UUID[6], system->UUID[7],
                   system->UUID[8], system->UUID[9], system->UUID[10], system->UUID[11],
                   system->UUID[12], system->UUID[13], system->UUID[14], system->UUID[15],
                   system->SKU, system->Family);
             KPrint("System: \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s",
                    SystemManufacturer, SystemProductName, SystemVersion, SystemSerialNumber, SystemSKU, SystemFamily);
         }
         if (baseboard)
         {
             const char *Manufacturer = baseboard->GetString(baseboard->Manufacturer);
             const char *Product = baseboard->GetString(baseboard->Product);
             const char *Version = baseboard->GetString(baseboard->Version);
             const char *SerialNumber = baseboard->GetString(baseboard->SerialNumber);
             debug("%d %d %d %d", baseboard->Manufacturer, baseboard->Product, baseboard->Version, baseboard->SerialNumber);
             KPrint("Baseboard: \eCCCCCC\e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s \eCCCCCC/ \e8888FF%s",
                    Manufacturer, Product, Version, SerialNumber);
         }
     }
     else
         KPrint("SMBIOS: \eFF0000Not Found");
     KPrint("Initializing Filesystem...");
     vfs = new VirtualFileSystem::Virtual;
     if (Config.BootAnimation)
         bootanim_vfs = new VirtualFileSystem::Virtual;
     for (size_t i = 0; i < MAX_MODULES; i++)
     {
         if (!bInfo.Modules[i].Address)
             continue;
         if (strcmp(bInfo.Modules[i].CommandLine, "initrd") == 0)
         {
             debug("Found initrd at %p", bInfo.Modules[i].Address);
             static char initrd = 0;
             if (!initrd++)
                 new VirtualFileSystem::USTAR((uintptr_t)bInfo.Modules[i].Address, vfs);
         }
         if (strcmp(bInfo.Modules[i].CommandLine, "bootanim") == 0 && Config.BootAnimation)
         {
             debug("Found bootanim at %p", bInfo.Modules[i].Address);
             static char bootanim = 0;
             if (!bootanim++)
                 new VirtualFileSystem::USTAR((uintptr_t)bInfo.Modules[i].Address, bootanim_vfs);
         }
     }
     if (!vfs->PathExists("/system"))
         vfs->Create("/system", NodeFlags::DIRECTORY);
     if (!vfs->PathExists("/system/dev"))
         DevFS = vfs->Create("/system/dev", NodeFlags::DIRECTORY);
     else
     {
         File dev = vfs->Open("/system/dev");
         if (dev.node->Flags != NodeFlags::DIRECTORY)
         {
             KPrint("\eE85230/system/dev is not a directory! Halting...");
             CPU::Stop();
         }
         vfs->Close(dev);
         DevFS = dev.node;
     }
     if (!vfs->PathExists("/system/mnt"))
         MntFS = vfs->Create("/system/mnt", NodeFlags::DIRECTORY);
     else
     {
         File mnt = vfs->Open("/system/mnt");
         if (mnt.node->Flags != NodeFlags::DIRECTORY)
         {
             KPrint("\eE85230/system/mnt is not a directory! Halting...");
             CPU::Stop();
         }
         vfs->Close(mnt);
         MntFS = mnt.node;
     }
     if (!vfs->PathExists("/system/proc"))
         ProcFS = vfs->Create("/system/proc", NodeFlags::DIRECTORY);
     else
     {
         File proc = vfs->Open("/system/proc", nullptr);
         if (proc.node->Flags != NodeFlags::DIRECTORY)
         {
             KPrint("\eE85230/system/proc is not a directory! Halting...");
             CPU::Stop();
         }
         vfs->Close(proc);
         ProcFS = proc.node;
     }
     KPrint("\e058C19################################");
     TaskManager = new Tasking::Task((Tasking::IP)KernelMainThread);
     CPU::Halt(true);
 }
References BootInfo::ModuleInfo::Address, bInfo, bootanim_vfs, KernelConfig::BootAnimation, BootClock, buf, SMBIOS::CheckSMBIOS(), VirtualFileSystem::Virtual::Close(), BootInfo::ModuleInfo::CommandLine, BootInfo::KernelInfo::CommandLine, Config, VirtualFileSystem::Virtual::Create(), Video::Display::CreateBuffer(), debug, DebuggerIsAttached, DevFS, PCI::Descriptors::DeviceClasses, VirtualFileSystem::DIRECTORY, Display, Interrupts::Enable(), SMBIOS::SMBIOSEntryPoint::EntryPointString, Time::time::FindTimers(), VirtualFileSystem::Node::Flags, BootInfo::Framebuffer, Power::Power::GetACPI(), SMBIOS::GetBaseBoardInformation(), SMBIOS::GetBIOSInformation(), Video::Display::GetBuffer(), Video::Display::GetCurrentFont(), PCI::Descriptors::GetDeviceName(), PCI::PCI::GetDevices(), Video::Font::GetInfo(), Power::Power::GetMADT(), PCI::Descriptors::GetProgIFName(), SMBIOS::GetSMBIOSEntryPoint(), SMBIOS::SMBIOSBIOSInformation::GetString(), SMBIOS::SMBIOSBaseBoardInformation::GetString(), PCI::Descriptors::GetSubclassName(), SMBIOS::GetSystemInformation(), PCI::Descriptors::GetVendorName(), Halt(), Video::FontInfo::Height, CPU::Hypervisor(), i, Info, Power::Power::InitDSDT(), Interrupts::Initialize(), SMP::Initialize(), CPU::InitializeFeatures(), Interrupts::InitializeTimer(), BootInfo::Kernel, KernelMainThread(), KernelSymbolTable, KPrint(), SMBIOS::SMBIOSEntryPoint::MajorVersion, SMBIOS::SMBIOSBaseBoardInformation::Manufacturer, MAX_MODULES, memcpy, SMBIOS::SMBIOSEntryPoint::MinorVersion, MntFS, BootInfo::Modules, CPU::Name(), VirtualFileSystem::File::node, VirtualFileSystem::Virtual::Open(), ParseConfig(), VirtualFileSystem::Virtual::PathExists(), PCI, PCIManager, PowerManager, printf, ProcFS, SMBIOS::SMBIOSBaseBoardInformation::Product, PutCharBufferIndex, Time::ReadClock(), SMBIOS::SMBIOSBIOSInformation::ReleaseDate, SMBIOS::SMBIOSBaseBoardInformation::SerialNumber, Video::Display::SetBuffer(), Video::Display::SetBufferCursor(), Video::Display::SetDoNotScroll(), strcmp(), system(), SMBIOS::SMBIOSEntryPoint::TableAddress, SMBIOS::SMBIOSEntryPoint::TableLength, TaskManager, time(), TimeManager, CPU::Vendor(), SMBIOS::SMBIOSBIOSInformation::Vendor, SMBIOS::SMBIOSBIOSInformation::Version, SMBIOS::SMBIOSBaseBoardInformation::Version, Version, and vfs.
Referenced by Entry().
NewLock()
NewLock (KernelLock)
Fennix Kernel
This is the main kernel file. It contains the main function and the kernel entry point.
LOADING PROCEDURE: [BOOT] -> [Bootloader] -> [Boot Info Parser] -> Entry() -> Main() -> KernelMainThread()
Bootloader
Entry() is the first function to be called by the boot info parser function after getting the boot info from the bootloader.
Main() is the first function to be called by Entry().
KernelMainThread() is the first function to be called by the task manager.
TODO:
[x] Optimize SMP.
[ ] Support IPv6.
[ ] Endianess of the network stack (currently: [HOST](LSB)<=>[NETWORK](MSB)). Not sure if this is a standard or not.
[ ] Support 32-bit applications (ELF, PE, etc).
[ ] Do not map the entire memory. Map only the needed memory address at allocation time.
[ ] Implementation of logging (beside serial) with log rotation.
[ ] Implement a better task manager. (replace struct P/TCB with classes)
[?] Rewrite virtual file system. (it's very bad, I don't know how I wrote it this bad)
[ ] Colors in crash screen are not following the kernel color scheme.
[x] Find a way to add intrinsics.
[ ] Rework PSF1 font loader.
[x] The cleanup should be done by a thread (tasking). This is done to avoid a deadlock.
[ ] Implement a better Display::SetBrightness() function.
[ ] Fix memcpy, memset and memcmp functions (they are not working properly with SIMD).
[ ] Support Aarch64.
[ ] Fully support i386.
[ ] SMP trampoline shouldn't be hardcoded at 0x2000.
[ ] Rework the stack guard.
[ ] Mutex implementation.
[ ] Vector should have a mutex.
ISSUES:
[x] Kernel stack is smashed when an interrupt occurs. (this bug it occurs when an interrupt like IRQ1 or IRQ12 occurs)
[x] After setting the new stack pointer, the kernel crashes with an invalid opcode.
[?] Somewhere in the kernel, the memory is wrongly freed or memcpy/memset.
[ ] GlobalDescriptorTable::SetKernelStack() is not working properly.
[ ] Sometimes while the kernel is inside BeforeShutdown(), we end up in a deadlock.
CREDITS AND REFERENCES:
General: https://wiki.osdev.org/Main_Page https://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.html#x86-Built-in-Functions https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes
Font: http://www.fial.com/~scott/tamsyn-font/
CPU XCR0 structure: https://wiki.osdev.org/CPU_Registers_x86#XCR0
CPUID 0x7: https://en.wikipedia.org/wiki/CPUID
Network: https://web.archive.org/web/20051210132103/http://users.pcnet.ro/dmoroian/beej/Beej.html https://web.archive.org/web/20060229214053/http://www.cs.rutgers.edu/~pxk/417/notes/sockets/udp.html https://en.wikipedia.org/wiki/EtherType https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/performance_tuning_guide/s-network-packet-reception https://linux-kernel-labs.github.io/refs/heads/master/labs/networking.html https://github.com/smoltcp-rs/smoltcp https://www.ciscopress.com/articles/article.asp?p=3089352&seqNum=5 https://www.cs.unh.edu/cnrg/people/gherrin/linux-net.html https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers https://github.com/TheUltimateFoxOS/horizon https://en.wikipedia.org/wiki/Address_Resolution_Protocol https://en.cppreference.com/w/cpp/language/operators https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol https://www.cs.usfca.edu/~cruse/cs326f04/RTL8139D_DataSheet.pdf https://www.javatpoint.com/arp-packet-format https://www.cs.usfca.edu/~cruse/cs326f04/RTL8139_ProgrammersGuide.pdf http://realtek.info/pdf/rtl8139cp.pdf https://en.wikipedia.org/wiki/IPv4 https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml
Loading ELF shared libraries and dynamic linking: https://www.akkadia.org/drepper/dsohowto.pdf https://wiki.osdev.org/Dynamic_Linker https://github.com/tyler569/nightingale https://www.technovelty.org/linux/plt-and-got-the-key-to-code-sharing-and-dynamic-libraries.html https://www.youtube.com/watch?v=kUk5pw4w0h4 https://docs.oracle.com/cd/E19683-01/817-3677/chapter6-42444/index.html https://ir0nstone.gitbook.io/notes/types/stack/aslr/plt_and_got
IPC: https://docs.oracle.com/cd/E19048-01/chorus5/806-6897/architecture-103/index.html https://www.scaler.com/topics/operating-system/inter-process-communication-in-os/ https://en.wikipedia.org/wiki/Inter-process_communication https://www.geeksforgeeks.org/inter-process-communication-ipc/
PCI: https://wiki.osdev.org/PCI https://en.wikipedia.org/wiki/PCI_configuration_space
Audio: https://trac.ffmpeg.org/wiki/audio%20types https://wiki.osdev.org/AC97 https://github.com/LemonOSProject/LemonOS https://inst.eecs.berkeley.edu//~cs150/Documents/ac97_r23.pdf
Intrinsics: https://learn.microsoft.com/en-us/cpp/intrinsics/x86-intrinsics-list https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html
CPUID lists: https://www.amd.com/system/files/TechDocs/40332.pdf
SMBIOS: https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.2.0.pdf
UMIP, SMAP and SMEP: https://en.wikipedia.org/wiki/Control_register https://web.archive.org/web/20160312223150/http://ncsi.com/nsatc11/presentations/wednesday/emerging_technologies/fischer.pdf https://en.wikipedia.org/wiki/Supervisor_Mode_Access_Prevention
Atomic operations: https://en.cppreference.com/w/cpp/atomic/atomic
putchar()
EXTERNC void putchar (char c)
Definition at line 222 of file Kernel.cpp.
 {
     if (Display)
         Display->Print(c, PutCharBufferIndex);
     else
         UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM1).Write(c);
 }
References c, UniversalAsynchronousReceiverTransmitter::COM1, Display, Video::Display::Print(), PutCharBufferIndex, and UniversalAsynchronousReceiverTransmitter::UART::Write().
Referenced by I_PrintBanner(), and I_PrintDivider().
TaskingPanic()
EXTERNC void TaskingPanic ()
Definition at line 550 of file Kernel.cpp.
 {
     if (TaskManager)
         TaskManager->Panic();
 }
References Tasking::Task::Panic(), and TaskManager.
Referenced by __chk_fail(), and __stack_chk_fail().
Variable Documentation
__fini_array_end
CallPtr __fini_array_end[0]
Definition at line 472 of file Kernel.cpp.
Referenced by BeforeShutdown().
__fini_array_start
CallPtr __fini_array_start[0] extern
Referenced by BeforeShutdown().
__init_array_end
CallPtr __init_array_end[0]
Definition at line 471 of file Kernel.cpp.
Referenced by Entry(), and ObjectRepository::injectStaticObject().
__init_array_start
CallPtr __init_array_start[0] extern
Definition at line 10 of file startup.cpp.
Referenced by Entry(), and ObjectRepository::injectStaticObject().
bootanim_vfs
VirtualFileSystem::Virtual* bootanim_vfs = nullptr
Definition at line 201 of file Kernel.cpp.
Referenced by BeforeShutdown(), BootLogoAnimationThread(), and Main().
BootClock
Time::Clock BootClock
Definition at line 203 of file Kernel.cpp.
Referenced by Main().
Config
KernelConfig Config
Initial value:
= {
    .AllocatorType = Memory::MemoryAllocatorType::XallocV1,
    .SchedulerType = 1,
    .DriverDirectory = {'/', 's', 'y', 's', 't', 'e', 'm', '/', 'd', 'r', 'i', 'v', 'e', 'r', 's', '\0'},
    .InitPath = {'/', 's', 'y', 's', 't', 'e', 'm', '/', 'i', 'n', 'i', 't', '\0'},
    .InterruptsOnCrash = true,
    .Cores = 0,
    .IOAPICInterruptCore = 0,
    .UnlockDeadLock = false,
    .SIMD = false,
    .BootAnimation = false,
}
Definition at line 205 of file Kernel.cpp.
Referenced by Driver::Driver::Driver(), Interrupts::Enable(), CrashHandler::Handle(), CPU::InitializeFeatures(), KernelMainThread(), KernelShutdownThread(), KPrint(), Main(), SpawnInit(), and sys_print().
DebuggerIsAttached
bool DebuggerIsAttached = false
Definition at line 36 of file Kernel.cpp.
Referenced by Driver::Driver::CallDriverEntryPoint(), Entry(), InterruptDescriptorTable::Init(), and Main().
Display
Video::Display* Display = nullptr
Definition at line 194 of file Kernel.cpp.
Referenced by BeforeShutdown(), KPrint(), Main(), and putchar().
EnableProfiler
bool EnableProfiler extern
Definition at line 24 of file cyg.cpp.
Referenced by __cyg_profile_func_enter(), __cyg_profile_func_exit(), Entry(), and profiler_uart_wrapper().
KernelSymbolTable
SymbolResolver::Symbols* KernelSymbolTable = nullptr
Definition at line 195 of file Kernel.cpp.
Referenced by __cyg_profile_func_enter(), __cyg_profile_func_exit(), __memcpy_chk(), __memmove_chk(), __memset_chk(), __strcat_chk(), __strcpy_chk(), calloc(), CheckTrust(), CrashHandler::DisplayStackFrameScreen(), free(), CrashHandler::Handle(), Main(), malloc(), operator delete(), operator delete[](), operator new(), operator new[](), realloc(), Tasking::Task::Task(), and CrashHandler::UserInput().
PCIManager
PCI::PCI* PCIManager = nullptr
Definition at line 197 of file Kernel.cpp.
Referenced by Driver::Driver::DriverLoadBindPCI(), and Main().
PowerManager
Power::Power* PowerManager = nullptr
Definition at line 196 of file Kernel.cpp.
Referenced by APIC::APIC::APIC(), Interrupts::Enable(), APIC::APIC::IOGetMaxRedirect(), KernelShutdownThread(), Main(), PCI::PCI::PCI(), APIC::APIC::RawRedirectIRQ(), APIC::APIC::RedirectIRQ(), and CrashHandler::UserInput().
PutCharBufferIndex
int PutCharBufferIndex = 0
Definition at line 221 of file Kernel.cpp.
Referenced by Main(), and putchar().
TaskManager
Tasking::Task* TaskManager = nullptr
Definition at line 198 of file Kernel.cpp.
Referenced by BeforeShutdown(), BootLogoAnimationThread(), CheckTrust(), CleanupProcessesThreadWrapper(), CrashHandler::DisplayTasksScreen(), Driver::Driver::DriverLoadBindInput(), Driver::Driver::DriverLoadBindInterrupt(), Driver::Driver::DriverLoadBindPCI(), DriverSleep(), Execute::ELFInterpreterIPCThread(), Execute::ELFLoad(), ExitLogoAnimationThread(), CrashHandler::Handle(), InterProcessCommunication::IPC::HandleSyscall(), KernelMainThread(), Recovery::KernelRecovery::KernelRecovery(), KernelShutdownThread(), Main(), NetworkInterfaceManager::NetworkInterface::NetworkInterface(), ACPI::DSDT::OnInterruptReceived(), Recovery::PlayAudio(), Recovery::PlayAudioWrapper(), NetworkNTP::NTP::ReadTime(), Recovery::RebootCommandWrapper(), Recovery::KernelRecovery::RecoveryThread(), NetworkDHCP::DHCP::Request(), NetworkARP::ARP::Resolve(), Recovery::ShutdownCommandWrapper(), Execute::Spawn(), Execute::StartExecuteService(), NetworkInterfaceManager::NetworkInterface::StartNetworkStack(), NetworkInterfaceManager::NetworkInterface::StartService(), sys_detach_address(), sys_exit(), sys_file_close(), sys_file_open(), sys_free_pages(), sys_ipc(), sys_kernelctl(), sys_request_pages(), sys_sleep(), SystemCallsHandler(), TaskingPanic(), UserModeExceptionHandler(), and Recovery::KernelRecovery::~KernelRecovery().
TimeManager
Time::time* TimeManager = nullptr
Definition at line 199 of file Kernel.cpp.
Referenced by Execute::AddLibrary(), BeforeShutdown(), DriverSleep(), KPrint(), Main(), Tasking::Task::Sleep(), Execute::StartExecuteService(), APIC::Timer::Timer(), and Time::TimeStampCounter::TimeStampCounter().
vfs
VirtualFileSystem::Virtual* vfs = nullptr
Definition at line 200 of file Kernel.cpp.
Referenced by BeforeShutdown(), InterProcessCommunication::IPC::Create(), Tasking::Task::CreateProcess(), InterProcessCommunication::IPC::Destroy(), Driver::Driver::Driver(), Execute::ELFLoad(), Execute::ELFLoadExec(), Execute::GetBinaryType(), InterProcessCommunication::IPC::IPC(), KernelMainThread(), Execute::LoadELFInterpreter(), Main(), Recovery::PlayAudio(), Tasking::Task::RemoveProcess(), Execute::Spawn(), sys_file_close(), sys_file_open(), sys_file_read(), sys_file_write(), sys_kernelctl(), and InterProcessCommunication::IPC::~IPC().