Fennix: Userspace/musl/include/pty.h File Reference
pty.h File Reference
#include <termios.h>
#include <sys/ioctl.h>
Functions
int openpty (int *, int *, char *, const struct termios *, const struct winsize *)
int forkpty (int *, char *, const struct termios *, const struct winsize *)
Function Documentation
forkpty()
int forkpty (int * pm, char * name, const struct termios * tio, const struct winsize * ws)
Definition at line 9 of file forkpty.c.
 {
     int m, s, ec=0, p[2], cs;
     pid_t pid=-1;
     sigset_t set, oldset;
     if (openpty(&m, &s, name, tio, ws) < 0) return -1;
     sigfillset(&set);
     pthread_sigmask(SIG_BLOCK, &set, &oldset);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     if (pipe2(p, O_CLOEXEC)) {
         close(s);
         goto out;
     }
     pid = fork();
     if (!pid) {
         close(m);
         close(p[0]);
         if (login_tty(s)) {
             write(p[1], &errno, sizeof errno);
             _exit(127);
         }
         close(p[1]);
         pthread_setcancelstate(cs, 0);
         pthread_sigmask(SIG_SETMASK, &oldset, 0);
         return 0;
     }
     close(s);
     close(p[1]);
     if (read(p[0], &ec, sizeof ec) > 0) {
         int status;
         waitpid(pid, &status, 0);
         pid = -1;
         errno = ec;
     }
     close(p[0]);
 out:
     if (pid > 0) *pm = m;
     else close(m);
     pthread_setcancelstate(cs, 0);
     pthread_sigmask(SIG_SETMASK, &oldset, 0);
     return pid;
 }
References _exit(), close(), errno, fork(), login_tty(), O_CLOEXEC, openpty(), out(), p, pid, pipe2(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), pthread_sigmask(), read(), s, SIG_BLOCK, SIG_SETMASK, sigfillset(), status, tio, waitpid(), and write().
openpty()
int openpty (int * pm, int * ps, char * name, const struct termios * tio, const struct winsize * ws)
Definition at line 10 of file openpty.c.
 {
     int m, s, n=0, cs;
     char buf[20];
     m = open("/dev/ptmx", O_RDWR|O_NOCTTY);
     if (m < 0) return -1;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     if (ioctl(m, TIOCSPTLCK, &n) || ioctl (m, TIOCGPTN, &n))
         goto fail;
     if (!name) name = buf;
     snprintf(name, sizeof buf, "/dev/pts/%d", n);
     if ((s = open(name, O_RDWR|O_NOCTTY)) < 0)
         goto fail;
     if (tio) tcsetattr(s, TCSANOW, tio);
     if (ws) ioctl(s, TIOCSWINSZ, ws);
     *pm = m;
     *ps = s;
     pthread_setcancelstate(cs, 0);
     return 0;
 fail:
     close(m);
     pthread_setcancelstate(cs, 0);
     return -1;
 }
References buf, close(), ioctl(), n, O_NOCTTY, O_RDWR, open(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), s, snprintf(), TCSANOW, tcsetattr(), tio, TIOCGPTN, TIOCSPTLCK, and TIOCSWINSZ.
Referenced by forkpty().