Fennix Userspace: Userspace/mlibc/tests/posix/access.c File Reference
access.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <fcntl.h>
Macros
#define TEST_FILE "access.tmp"
Functions
int main ()
Macro Definition Documentation
TEST_FILE
#define TEST_FILE "access.tmp"
Definition at line 10 of file access.c.
Function Documentation
main()
int main (void)
Definition at line 13 of file access.c.
            {
     // Make sure that it wasn't created by a previous test run
     unlink(TEST_FILE);
     assert(access(TEST_FILE, F_OK) == -1);
     assert(access(TEST_FILE, W_OK) == -1);
     assert(access(TEST_FILE, R_OK) == -1);
     assert(access(TEST_FILE, X_OK) == -1);
     close(open(TEST_FILE, O_CREAT | O_RDWR, 0666));
     assert(access(TEST_FILE, F_OK) == 0);
     assert(access(TEST_FILE, W_OK) == 0);
     assert(access(TEST_FILE, R_OK) == 0);
     assert(access(TEST_FILE, X_OK) == -1);
     unlink(TEST_FILE);
 }
References access(), assert, close(), F_OK, O_CREAT, O_RDWR, open(), R_OK, TEST_FILE, unlink(), W_OK, and X_OK.