Fennix Userspace: Userspace/apps/base/bash/builtins/evalfile.c File Reference
evalfile.c File Reference
#include <config.h>
#include "../bashtypes.h"
#include "posixstat.h"
#include "filecntl.h"
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include "../bashansi.h"
#include "../bashintl.h"
#include "../shell.h"
#include "../parser.h"
#include "../jobs.h"
#include "../builtins.h"
#include "../flags.h"
#include "../input.h"
#include "../execute_cmd.h"
#include "../trap.h"
#include <y.tab.h>
#include <typemax.h>
#include "common.h"
Macros
#define FEVAL_ENOENTOK 0x001
#define FEVAL_BUILTIN 0x002
#define FEVAL_UNWINDPROT 0x004
#define FEVAL_NONINT 0x008
#define FEVAL_LONGJMP 0x010
#define FEVAL_HISTORY 0x020
#define FEVAL_CHECKBINARY 0x040
#define FEVAL_REGFILE 0x080
#define FEVAL_NOPUSHARGS 0x100
Functions
static int _evalfile (char *filename, int flags) const
int maybe_execute_file (char *fname, int force_noninteractive) const
int force_execute_file (char *fname, int force_noninteractive) const
int source_file (char *filename, int sflags) const
Variables
int errno
int sourcelevel = 0
Macro Definition Documentation
FEVAL_BUILTIN
#define FEVAL_BUILTIN 0x002
Definition at line 63 of file evalfile.c.
FEVAL_CHECKBINARY
#define FEVAL_CHECKBINARY 0x040
Definition at line 68 of file evalfile.c.
FEVAL_ENOENTOK
#define FEVAL_ENOENTOK 0x001
Definition at line 62 of file evalfile.c.
FEVAL_HISTORY
#define FEVAL_HISTORY 0x020
Definition at line 67 of file evalfile.c.
FEVAL_LONGJMP
#define FEVAL_LONGJMP 0x010
Definition at line 66 of file evalfile.c.
FEVAL_NONINT
#define FEVAL_NONINT 0x008
Definition at line 65 of file evalfile.c.
FEVAL_NOPUSHARGS
#define FEVAL_NOPUSHARGS 0x100
Definition at line 70 of file evalfile.c.
FEVAL_REGFILE
#define FEVAL_REGFILE 0x080
Definition at line 69 of file evalfile.c.
FEVAL_UNWINDPROT
#define FEVAL_UNWINDPROT 0x004
Definition at line 64 of file evalfile.c.
Function Documentation
_evalfile()
static int _evalfile (char * filename, int flags) const static
Definition at line 76 of file evalfile.c.
 {
   volatile int old_interactive;
   procenv_t old_return_catch;
   int return_val, fd, result, pflags, i, nnull;
   ssize_t nr;           /* return value from read(2) */
   char *string;
   struct stat finfo;
   size_t file_size;
   sh_vmsg_func_t *errfunc;
 #if defined (ARRAY_VARS)
   SHELL_VAR *funcname_v, *bash_source_v, *bash_lineno_v;
   ARRAY *funcname_a, *bash_source_a, *bash_lineno_a;
   struct func_array_state *fa;
 #  if defined (DEBUGGER)
   SHELL_VAR *bash_argv_v, *bash_argc_v;
   ARRAY *bash_argv_a, *bash_argc_a;
 #  endif
   char *t, tt[2];
 #endif
   USE_VAR(pflags);
 #if defined (ARRAY_VARS)
   GET_ARRAY_FROM_VAR ("FUNCNAME", funcname_v, funcname_a);
   GET_ARRAY_FROM_VAR ("BASH_SOURCE", bash_source_v, bash_source_a);
   GET_ARRAY_FROM_VAR ("BASH_LINENO", bash_lineno_v, bash_lineno_a);
 #  if defined (DEBUGGER)
   GET_ARRAY_FROM_VAR ("BASH_ARGV", bash_argv_v, bash_argv_a);
   GET_ARRAY_FROM_VAR ("BASH_ARGC", bash_argc_v, bash_argc_a);
 #  endif
 #endif
   fd = open (filename, O_RDONLY);
   if (fd < 0 || (fstat (fd, &finfo) == -1))
     {
       i = errno;
       if (fd >= 0)
     close (fd);
       errno = i;
 file_error_and_exit:
       if (((flags & FEVAL_ENOENTOK) == 0) || errno != ENOENT)
     file_error (filename);
       if (flags & FEVAL_LONGJMP)
     {
       last_command_exit_value = EXECUTION_FAILURE;
       jump_to_top_level (EXITPROG);
     }
       return ((flags & FEVAL_BUILTIN) ? EXECUTION_FAILURE
                           : ((errno == ENOENT && (flags & FEVAL_ENOENTOK) != 0) ? 0 : -1));
     }
   errfunc = ((flags & FEVAL_BUILTIN) ? builtin_error : internal_error);
   if (S_ISDIR (finfo.st_mode))
     {
       (*errfunc) (_("%s: is a directory"), filename);
       close (fd);
       return ((flags & FEVAL_BUILTIN) ? EXECUTION_FAILURE : -1);
     }
   else if ((flags & FEVAL_REGFILE) && S_ISREG (finfo.st_mode) == 0)
     {
       (*errfunc) (_("%s: not a regular file"), filename);
       close (fd);
       return ((flags & FEVAL_BUILTIN) ? EXECUTION_FAILURE : -1);
     }
   file_size = (size_t)finfo.st_size;
   /* Check for overflow with large files. */
   if (file_size != finfo.st_size || file_size + 1 < file_size)
     {
       (*errfunc) (_("%s: file is too large"), filename);
       close (fd);
       return ((flags & FEVAL_BUILTIN) ? EXECUTION_FAILURE : -1);
     }
   if (S_ISREG (finfo.st_mode) && file_size <= SSIZE_MAX)
     {
       string = (char *)xmalloc (1 + file_size);
       nr = read (fd, string, file_size);
       if (nr >= 0)
     string[nr] = '\0';
     }
   else
     nr = zmapfd (fd, &string, 0);
   return_val = errno;
   close (fd);
   errno = return_val;
   if (nr < 0)       /* XXX was != file_size, not < 0 */
     {
       free (string);
       goto file_error_and_exit;
     }
   if (nr == 0)
     {
       free (string);
       return ((flags & FEVAL_BUILTIN) ? EXECUTION_SUCCESS : 1);
     }
   if ((flags & FEVAL_CHECKBINARY) &&
       check_binary_file (string, (nr > 80) ? 80 : nr))
     {
       free (string);
       (*errfunc) (_("%s: cannot execute binary file"), filename);
       return ((flags & FEVAL_BUILTIN) ? EX_BINARY_FILE : -1);
     }
   i = strlen (string);
   if (i < nr)
     {
       for (nnull = i = 0; i < nr; i++)
     if (string[i] == '\0')
           {
         memmove (string+i, string+i+1, nr - i);
         nr--;
         /* Even if the `check binary' flag is not set, we want to avoid
            sourcing files with more than 256 null characters -- that
            probably indicates a binary file. */
         if ((flags & FEVAL_BUILTIN) && ++nnull > 256)
           {
         free (string);
         (*errfunc) (_("%s: cannot execute binary file"), filename);
         return ((flags & FEVAL_BUILTIN) ? EX_BINARY_FILE : -1);
           }
           }
     }
   if (flags & FEVAL_UNWINDPROT)
     {
       begin_unwind_frame ("_evalfile");
       unwind_protect_int (return_catch_flag);
       unwind_protect_jmp_buf (return_catch);
       if (flags & FEVAL_NONINT)
     unwind_protect_int (interactive);
       unwind_protect_int (sourcelevel);
     }
   else
     {
       COPY_PROCENV (return_catch, old_return_catch);
       if (flags & FEVAL_NONINT)
     old_interactive = interactive;
     }
   if (flags & FEVAL_NONINT)
     interactive = 0;
   return_catch_flag++;
   sourcelevel++;
 #if defined (ARRAY_VARS)
   array_push (bash_source_a, (char *)filename);
   t = itos (executing_line_number ());
   array_push (bash_lineno_a, t);
   free (t);
   array_push (funcname_a, "source");    /* not exactly right */
   fa = (struct func_array_state *)xmalloc (sizeof (struct func_array_state));
   fa->source_a = bash_source_a;
   fa->source_v = bash_source_v;
   fa->lineno_a = bash_lineno_a;
   fa->lineno_v = bash_lineno_v;
   fa->funcname_a = funcname_a;
   fa->funcname_v = funcname_v;
   if (flags & FEVAL_UNWINDPROT)
     add_unwind_protect (restore_funcarray_state, fa);
 #  if defined (DEBUGGER)
   /* Have to figure out a better way to do this when `source' is supplied
      arguments */
   if ((flags & FEVAL_NOPUSHARGS) == 0)
     {
       if (shell_compatibility_level <= 44)
     init_bash_argv ();
       array_push (bash_argv_a, (char *)filename);   /* XXX - unconditionally? */
       tt[0] = '1'; tt[1] = '\0';
       array_push (bash_argc_a, tt);
       if (flags & FEVAL_UNWINDPROT)
     add_unwind_protect (pop_args, 0);
     }
 #  endif
 #endif
   /* set the flags to be passed to parse_and_execute */
   pflags = SEVAL_RESETLINE;
   pflags |= (flags & FEVAL_HISTORY) ? 0 : SEVAL_NOHIST;
   if (flags & FEVAL_BUILTIN)
     result = EXECUTION_SUCCESS;
   return_val = setjmp_nosigs (return_catch);
   /* If `return' was seen outside of a function, but in the script, then
      force parse_and_execute () to clean up. */
   if (return_val)
     {
       parse_and_execute_cleanup (-1);
       result = return_catch_value;
     }
   else
     result = parse_and_execute (string, filename, pflags);
   if (flags & FEVAL_UNWINDPROT)
     run_unwind_frame ("_evalfile");
   else
     {
       if (flags & FEVAL_NONINT)
     interactive = old_interactive;
 #if defined (ARRAY_VARS)
       restore_funcarray_state (fa);
 #  if defined (DEBUGGER)
       if ((flags & FEVAL_NOPUSHARGS) == 0)
     {
       /* Don't need to call pop_args here until we do something better
          when source is passed arguments (see above). */
       array_pop (bash_argc_a);
       array_pop (bash_argv_a);
     }
 #  endif
 #endif
       return_catch_flag--;
       sourcelevel--;
       COPY_PROCENV (old_return_catch, return_catch);
     }
   /* If we end up with EOF after sourcing a file, which can happen when the file
      doesn't end with a newline, pretend that it did. */
   if (current_token == yacc_EOF)
     push_token ('\n');      /* XXX */
   return ((flags & FEVAL_BUILTIN) ? result : 1);
 }
References _, add_unwind_protect(), array_pop, array_push, begin_unwind_frame(), builtin_error(), check_binary_file(), close(), COPY_PROCENV, current_token, ENOENT, errno, EX_BINARY_FILE, executing_line_number(), EXECUTION_FAILURE, EXECUTION_SUCCESS, EXITPROG, fd, FEVAL_BUILTIN, FEVAL_CHECKBINARY, FEVAL_ENOENTOK, FEVAL_HISTORY, FEVAL_LONGJMP, FEVAL_NONINT, FEVAL_NOPUSHARGS, FEVAL_REGFILE, FEVAL_UNWINDPROT, file_error(), file_size, filename, flags, free, fstat(), GET_ARRAY_FROM_VAR, i, if(), init_bash_argv(), interactive, internal_error(), itos(), jump_to_top_level(), last_command_exit_value, memmove(), O_RDONLY, open(), parse_and_execute(), parse_and_execute_cleanup(), pop_args(), procenv_t, push_token(), read(), return_catch, return_catch_flag, return_catch_value, run_unwind_frame(), S_ISDIR, S_ISREG, setjmp_nosigs, SEVAL_NOHIST, SEVAL_RESETLINE, shell_compatibility_level, sourcelevel, SSIZE_MAX, stat::st_mode, stat::st_size, string, strlen(), t, tt, unwind_protect_int, unwind_protect_jmp_buf, USE_VAR, xmalloc, yacc_EOF, and zmapfd().
Referenced by force_execute_file(), maybe_execute_file(), and source_file().
force_execute_file()
int force_execute_file (char * fname, int force_noninteractive) const
Definition at line 336 of file evalfile.c.
 {
   char *filename;
   int result, flags;
   filename = bash_tilde_expand (fname, 0);
   flags = 0;
   if (force_noninteractive)
     flags |= FEVAL_NONINT;
   result = _evalfile (filename, flags);
   free (filename);
   return result;
 }
References _evalfile(), bash_tilde_expand(), FEVAL_NONINT, filename, flags, fname, and free.
Referenced by start_debugger().
maybe_execute_file()
int maybe_execute_file (char * fname, int force_noninteractive) const
Definition at line 319 of file evalfile.c.
 {
   char *filename;
   int result, flags;
   filename = bash_tilde_expand (fname, 0);
   flags = FEVAL_ENOENTOK;
   if (force_noninteractive)
     flags |= FEVAL_NONINT;
   result = _evalfile (filename, flags);
   free (filename);
   return result;
 }
References _evalfile(), bash_tilde_expand(), FEVAL_ENOENTOK, FEVAL_NONINT, filename, flags, fname, and free.
Referenced by execute_env_file(), and run_startup_files().
source_file()
int source_file (char * filename, int sflags) const
Definition at line 368 of file evalfile.c.
 {
   int flags, rval;
   flags = FEVAL_BUILTIN|FEVAL_UNWINDPROT|FEVAL_NONINT;
   if (sflags)
     flags |= FEVAL_NOPUSHARGS;
   /* POSIX shells exit if non-interactive and file error. */
   if (posixly_correct && interactive_shell == 0 && executing_command_builtin == 0)
     flags |= FEVAL_LONGJMP;
   rval = _evalfile (filename, flags);
   run_return_trap ();
   return rval;
 }
References _evalfile(), executing_command_builtin, FEVAL_BUILTIN, FEVAL_LONGJMP, FEVAL_NONINT, FEVAL_NOPUSHARGS, FEVAL_UNWINDPROT, filename, flags, interactive_shell, posixly_correct, and run_return_trap().
Variable Documentation
errno
int errno extern
Referenced by _evalfile().
sourcelevel
int sourcelevel = 0
Definition at line 73 of file evalfile.c.
Referenced by _evalfile(), command_substitute(), execute_simple_command(), notify_and_cleanup(), and wait_for().