Fennix Userspace: Userspace/musl/src/stdio/getc.h File Reference
getc.h File Reference
#include "stdio_impl.h"
#include "pthread_impl.h"
Functions
static int locking_getc (FILE *f)
static int do_getc (FILE *f)
Function Documentation
do_getc()
static int do_getc (FILE * f) inline static
Definition at line 16 of file getc.h.
 {
     int l = f->lock;
     if (l < 0 || l && (l & ~MAYBE_WAITERS) == __pthread_self()->tid)
         return getc_unlocked(f);
     return locking_getc(f);
 }
References __pthread_self, f, getc_unlocked(), l, _IO_FILE::lock, locking_getc(), and MAYBE_WAITERS.
Referenced by fgetc(), getc(), and getchar().
locking_getc()
static int locking_getc (FILE * f) static
Definition at line 7 of file getc.h.
 {
     if (a_cas(&f->lock, 0, MAYBE_WAITERS-1)) __lockfile(f);
     int c = getc_unlocked(f);
     if (a_swap(&f->lock, 0) & MAYBE_WAITERS)
         __wake(&f->lock, 1, 1);
     return c;
 }
References __lockfile(), __wake(), a_cas, a_swap, c, f, getc_unlocked(), _IO_FILE::lock, and MAYBE_WAITERS.
Referenced by do_getc().