Fennix: Userspace/musl/src/unistd/chown.c File Reference
chown.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include "syscall.h"
Functions
int chown (const char *path, uid_t uid, gid_t gid)
Function Documentation
chown()
int chown (const char * path, uid_t uid, gid_t gid)
Definition at line 5 of file chown.c.
 {
 #ifdef SYS_chown
     return syscall(SYS_chown, path, uid, gid);
 #else
     return syscall(SYS_fchownat, AT_FDCWD, path, uid, gid, 0);
 #endif
 }
References AT_FDCWD, and syscall().
Referenced by action_permissions(), adduser_main(), copy_file(), copy_inode(), data_extract_all(), history_do_write(), history_truncate_file(), and make_device().