Fennix: Userspace/musl/src/stdio/vfwprintf.c File Reference
vfwprintf.c File Reference
#include "stdio_impl.h"
#include <errno.h>
#include <ctype.h>
#include <limits.h>
#include <string.h>
#include <stdarg.h>
#include <stddef.h>
#include <stdlib.h>
#include <wchar.h>
#include <inttypes.h>
Data Structures
union arg
Macros
#define ALT_FORM (1U<<'#'-' ')
#define ZERO_PAD (1U<<'0'-' ')
#define LEFT_ADJ (1U<<'-'-' ')
#define PAD_POS (1U<<' '-' ')
#define MARK_POS (1U<<'+'-' ')
#define GROUPED (1U<<'\''-' ')
#define FLAGMASK (ALT_FORM|ZERO_PAD|LEFT_ADJ|PAD_POS|MARK_POS|GROUPED)
#define S(x) [(x)-'A']
#define OOB(x) ((unsigned)(x)-'A' > 'z'-'A')
Enumerations
enum {
BARE , LPRE , LLPRE , HPRE ,
HHPRE , BIGLPRE , ZTPRE , JPRE ,
STOP , PTR , INT , UINT ,
ULLONG , LONG , ULONG , SHORT ,
USHORT , CHAR , UCHAR , LLONG ,
SIZET , IMAX , UMAX , PDIFF ,
UIPTR , DBL , LDBL , NOARG ,
MAXSTATE
}
Functions
static void pop_arg (union arg *arg, int type, va_list *ap)
static void out (FILE *f, const wchar_t *s, size_t l)
static void pad (FILE *f, int n, int fl)
static int getint (wchar_t **s)
static int wprintf_core (FILE *f, const wchar_t *fmt, va_list *ap, union arg *nl_arg, int *nl_type)
int vfwprintf (FILE *restrict f, const wchar_t *restrict fmt, va_list ap)
Variables
static const unsigned char states []['z'- 'A'+1]
static const char sizeprefix ['y'- 'a']
Data Structure Documentation
arg
union arg
Definition at line 102 of file vfprintf.c.
Data Fields
long double f
uintmax_t i
void * p
Macro Definition Documentation
ALT_FORM
#define ALT_FORM (1U<<'#'-' ')
Definition at line 15 of file vfwprintf.c.
FLAGMASK
#define FLAGMASK (ALT_FORM|ZERO_PAD|LEFT_ADJ|PAD_POS|MARK_POS|GROUPED)
Definition at line 22 of file vfwprintf.c.
GROUPED
#define GROUPED (1U<<'\''-' ')
Definition at line 20 of file vfwprintf.c.
LEFT_ADJ
#define LEFT_ADJ (1U<<'-'-' ')
Definition at line 17 of file vfwprintf.c.
MARK_POS
#define MARK_POS (1U<<'+'-' ')
Definition at line 19 of file vfwprintf.c.
OOB
#define OOB (x) ((unsigned)(x)-'A' > 'z'-'A')
Definition at line 93 of file vfwprintf.c.
PAD_POS
#define PAD_POS (1U<<' '-' ')
Definition at line 18 of file vfwprintf.c.
S
#define S (x) [(x)-'A']
Definition at line 40 of file vfwprintf.c.
ZERO_PAD
#define ZERO_PAD (1U<<'0'-' ')
Definition at line 16 of file vfwprintf.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BARE
LPRE
LLPRE
HPRE
HHPRE
BIGLPRE
ZTPRE
JPRE
STOP
PTR
INT
UINT
ULLONG
LONG
ULONG
SHORT
USHORT
CHAR
UCHAR
LLONG
SIZET
IMAX
UMAX
PDIFF
UIPTR
DBL
LDBL
NOARG
MAXSTATE
Definition at line 27 of file vfwprintf.c.
      {
     BARE, LPRE, LLPRE, HPRE, HHPRE, BIGLPRE,
     ZTPRE, JPRE,
     STOP,
     PTR, INT, UINT, ULLONG,
     LONG, ULONG,
     SHORT, USHORT, CHAR, UCHAR,
     LLONG, SIZET, IMAX, UMAX, PDIFF, UIPTR,
     DBL, LDBL,
     NOARG,
     MAXSTATE
 };
Function Documentation
getint()
static int getint (wchar_t ** s) static
Definition at line 137 of file vfwprintf.c.
{
     int i;
     for (i=0; iswdigit(**s); (*s)++) {
         if (i > INT_MAX/10U || **s-'0' > INT_MAX-10*i) i = -1;
         else i = 10*i + (**s-'0');
     }
     return i;
 }
References i, INT_MAX, iswdigit, and s.
Referenced by wprintf_core().
out()
static void out (FILE * f, const wchar_t * s, size_t l) static
Definition at line 126 of file vfwprintf.c.
 {
     while (l-- && !ferror(f)) fputwc(*s++, f);
 }
References f, ferror, fputwc(), l, and s.
Referenced by wprintf_core().
pad()
static void pad (FILE * f, int n, int fl) static
Definition at line 131 of file vfwprintf.c.
 {
     if ((fl & LEFT_ADJ) || !n || ferror(f)) return;
     fprintf(f, "%*s", n, "");
 }
References f, ferror, fprintf(), LEFT_ADJ, and n.
Referenced by wprintf_core().
pop_arg()
static void pop_arg (union arg * arg, int type, va_list * ap) static
Definition at line 102 of file vfwprintf.c.
 {
     switch (type) {
            case PTR:    arg->p = va_arg(*ap, void *);
     break; case INT:    arg->i = va_arg(*ap, int);
     break; case UINT:   arg->i = va_arg(*ap, unsigned int);
     break; case LONG:   arg->i = va_arg(*ap, long);
     break; case ULONG:  arg->i = va_arg(*ap, unsigned long);
     break; case ULLONG: arg->i = va_arg(*ap, unsigned long long);
     break; case SHORT:  arg->i = (short)va_arg(*ap, int);
     break; case USHORT: arg->i = (unsigned short)va_arg(*ap, int);
     break; case CHAR:   arg->i = (signed char)va_arg(*ap, int);
     break; case UCHAR:  arg->i = (unsigned char)va_arg(*ap, int);
     break; case LLONG:  arg->i = va_arg(*ap, long long);
     break; case SIZET:  arg->i = va_arg(*ap, size_t);
     break; case IMAX:   arg->i = va_arg(*ap, intmax_t);
     break; case UMAX:   arg->i = va_arg(*ap, uintmax_t);
     break; case PDIFF:  arg->i = va_arg(*ap, ptrdiff_t);
     break; case UIPTR:  arg->i = (uintptr_t)va_arg(*ap, void *);
     break; case DBL:    arg->f = va_arg(*ap, double);
     break; case LDBL:   arg->f = va_arg(*ap, long double);
     }
 }
References ap, CHAR, DBL, arg::f, arg::i, IMAX, INT, LDBL, LLONG, LONG, arg::p, PDIFF, PTR, SHORT, SIZET, type, UCHAR, UINT, UIPTR, ULLONG, ULONG, UMAX, USHORT, and va_arg.
Referenced by wprintf_core().
vfwprintf()
int vfwprintf (FILE *restrict f, const wchar_t *restrict fmt, va_list ap)
Definition at line 347 of file vfwprintf.c.
 {
     va_list ap2;
     int nl_type[NL_ARGMAX+1] = {0};
     union arg nl_arg[NL_ARGMAX+1];
     int olderr;
     int ret;
     /* the copy allows passing va_list* even if va_list is an array */
     va_copy(ap2, ap);
     if (wprintf_core(0, fmt, &ap2, nl_arg, nl_type) < 0) {
         va_end(ap2);
         return -1;
     }
     FLOCK(f);
     fwide(f, 1);
     olderr = f->flags & F_ERR;
     f->flags &= ~F_ERR;
     ret = wprintf_core(f, fmt, &ap2, nl_arg, nl_type);
     if (ferror(f)) ret = -1;
     f->flags |= olderr;
     FUNLOCK(f);
     va_end(ap2);
     return ret;
 }
References ap, f, F_ERR, ferror, FLOCK, FUNLOCK, fwide(), va_copy, va_end, and wprintf_core().
wprintf_core()
static int wprintf_core (FILE * f, const wchar_t * fmt, va_list * ap, union arg * nl_arg, int * nl_type) static
Definition at line 152 of file vfwprintf.c.
 {
     wchar_t *a, *z, *s=(wchar_t *)fmt;
     unsigned l10n=0, fl;
     int w, p, xp;
     union arg arg;
     int argpos;
     unsigned st, ps;
     int cnt=0, l=0;
     int i;
     int t;
     char *bs;
     char charfmt[16];
     wchar_t wc;
     for (;;) {
         /* This error is only specified for snprintf, but since it's
          * unspecified for other forms, do the same. Stop immediately
          * on overflow; otherwise %n could produce wrong results. */
         if (l > INT_MAX - cnt) goto overflow;
         /* Update output count, end loop when fmt is exhausted */
         cnt += l;
         if (!*s) break;
         /* Handle literal text and %% format specifiers */
         for (a=s; *s && *s!='%'; s++);
         for (z=s; s[0]=='%' && s[1]=='%'; z++, s+=2);
         if (z-a > INT_MAX-cnt) goto overflow;
         l = z-a;
         if (f) out(f, a, l);
         if (l) continue;
         if (iswdigit(s[1]) && s[2]=='$') {
             l10n=1;
             argpos = s[1]-'0';
             s+=3;
         } else {
             argpos = -1;
             s++;
         }
         /* Read modifier flags */
         for (fl=0; (unsigned)*s-' '<32 && (FLAGMASK&(1U<<*s-' ')); s++)
             fl |= 1U<<*s-' ';
         /* Read field width */
         if (*s=='*') {
             if (iswdigit(s[1]) && s[2]=='$') {
                 l10n=1;
                 nl_type[s[1]-'0'] = INT;
                 w = nl_arg[s[1]-'0'].i;
                 s+=3;
             } else if (!l10n) {
                 w = f ? va_arg(*ap, int) : 0;
                 s++;
             } else goto inval;
             if (w<0) fl|=LEFT_ADJ, w=-w;
         } else if ((w=getint(&s))<0) goto overflow;
         /* Read precision */
         if (*s=='.' && s[1]=='*') {
             if (isdigit(s[2]) && s[3]=='$') {
                 nl_type[s[2]-'0'] = INT;
                 p = nl_arg[s[2]-'0'].i;
                 s+=4;
             } else if (!l10n) {
                 p = f ? va_arg(*ap, int) : 0;
                 s+=2;
             } else goto inval;
             xp = (p>=0);
         } else if (*s=='.') {
             s++;
             p = getint(&s);
             xp = 1;
         } else {
             p = -1;
             xp = 0;
         }
         /* Format specifier state machine */
         st=0;
         do {
             if (OOB(*s)) goto inval;
             ps=st;
             st=states[st]S(*s++);
         } while (st-1<STOP);
         if (!st) goto inval;
         /* Check validity of argument type (nl/normal) */
         if (st==NOARG) {
             if (argpos>=0) goto inval;
         } else {
             if (argpos>=0) nl_type[argpos]=st, arg=nl_arg[argpos];
             else if (f) pop_arg(&arg, st, ap);
             else return 0;
         }
         if (!f) continue;
         /* Do not process any new directives once in error state. */
         if (ferror(f)) return -1;
         t = s[-1];
         if (ps && (t&15)==3) t&=~32;
         switch (t) {
         case 'n':
             switch(ps) {
             case BARE: *(int *)arg.p = cnt; break;
             case LPRE: *(long *)arg.p = cnt; break;
             case LLPRE: *(long long *)arg.p = cnt; break;
             case HPRE: *(unsigned short *)arg.p = cnt; break;
             case HHPRE: *(unsigned char *)arg.p = cnt; break;
             case ZTPRE: *(size_t *)arg.p = cnt; break;
             case JPRE: *(uintmax_t *)arg.p = cnt; break;
             }
             continue;
         case 'c':
         case 'C':
             if (w<1) w=1;
             pad(f, w-1, fl);
             out(f, &(wchar_t){t=='C' ? arg.i : btowc(arg.i)}, 1);
             pad(f, w-1, fl^LEFT_ADJ);
             l = w;
             continue;
         case 'S':
             a = arg.p;
             z = a + wcsnlen(a, p<0 ? INT_MAX : p);
             if (p<0 && *z) goto overflow;
             p = z-a;
             if (w<p) w=p;
             pad(f, w-p, fl);
             out(f, a, p);
             pad(f, w-p, fl^LEFT_ADJ);
             l=w;
             continue;
         case 'm':
             arg.p = strerror(errno);
         case 's':
             if (!arg.p) arg.p = "(null)";
             bs = arg.p;
             for (i=l=0; l<(p<0?INT_MAX:p) && (i=mbtowc(&wc, bs, MB_LEN_MAX))>0; bs+=i, l++);
             if (i<0) return -1;
             if (p<0 && *bs) goto overflow;
             p=l;
             if (w<p) w=p;
             pad(f, w-p, fl);
             bs = arg.p;
             while (l--) {
                 i=mbtowc(&wc, bs, MB_LEN_MAX);
                 bs+=i;
                 out(f, &wc, 1);
             }
             pad(f, w-p, fl^LEFT_ADJ);
             l=w;
             continue;
         }
         if (xp && p<0) goto overflow;
         snprintf(charfmt, sizeof charfmt, "%%%s%s%s%s%s*.*%c%c",
             "#"+!(fl & ALT_FORM),
             "+"+!(fl & MARK_POS),
             "-"+!(fl & LEFT_ADJ),
             " "+!(fl & PAD_POS),
             "0"+!(fl & ZERO_PAD),
             sizeprefix[(t|32)-'a'], t);
         switch (t|32) {
         case 'a': case 'e': case 'f': case 'g':
             l = fprintf(f, charfmt, w, p, arg.f);
             break;
         case 'd': case 'i': case 'o': case 'u': case 'x': case 'p':
             l = fprintf(f, charfmt, w, p, arg.i);
             break;
         }
     }
     if (f) return cnt;
     if (!l10n) return 0;
     for (i=1; i<=NL_ARGMAX && nl_type[i]; i++)
         pop_arg(nl_arg+i, nl_type[i], ap);
     for (; i<=NL_ARGMAX && !nl_type[i]; i++);
     if (i<=NL_ARGMAX) return -1;
     return 1;
 inval:
     errno = EINVAL;
     return -1;
 overflow:
     errno = EOVERFLOW;
     return -1;
 }
References ALT_FORM, ap, BARE, btowc(), cnt, EINVAL, EOVERFLOW, errno, f, arg::f, ferror, FLAGMASK, fprintf(), getint(), HHPRE, HPRE, i, arg::i, INT, INT_MAX, isdigit, iswdigit, JPRE, l, LEFT_ADJ, LLPRE, LPRE, MARK_POS, MB_LEN_MAX, mbtowc(), NOARG, OOB, out(), p, arg::p, pad(), PAD_POS, pop_arg(), s, S, sizeprefix, snprintf(), states, STOP, strerror(), t, va_arg, w, wcsnlen(), ZERO_PAD, and ZTPRE.
Referenced by vfwprintf().
Variable Documentation
sizeprefix
const char sizeprefix[ 'y'- 'a'] static
Initial value:
= {
['a'-'a']='L', ['e'-'a']='L', ['f'-'a']='L', ['g'-'a']='L',
['d'-'a']='j', ['i'-'a']='j', ['o'-'a']='j', ['u'-'a']='j', ['x'-'a']='j',
['p'-'a']='j'
}
Definition at line 146 of file vfwprintf.c.
Referenced by wprintf_core().
states
const unsigned char states[][ 'z'- 'A'+1] static
Definition at line 42 of file vfwprintf.c.
Referenced by wprintf_core().