Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/i_system.h File Reference
i_system.h File Reference
#include "d_ticcmd.h"
#include "d_event.h"
Typedefs
typedef void(* atexit_func_t) (void)
Functions
void I_Init (void)
byte * I_ZoneBase (int *size)
boolean I_ConsoleStdout (void)
ticcmd_t * I_BaseTiccmd (void)
void I_Quit (void)
void I_Error (char *error,...)
void I_Tactile (int on, int off, int total)
boolean I_GetMemoryValue (unsigned int offset, void *value, int size)
void I_AtExit (atexit_func_t func, boolean run_if_error)
void I_BindVariables (void)
void I_PrintStartupBanner (char *gamedescription)
void I_PrintBanner (char *text)
void I_PrintDivider (void)
Typedef Documentation
atexit_func_t
typedef void(* atexit_func_t) (void)
Definition at line 27 of file i_system.h.
Function Documentation
I_AtExit()
void I_AtExit (atexit_func_t func, boolean run_if_error)
Definition at line 73 of file i_system.c.
 {
     atexit_listentry_t *entry;
     entry = malloc(sizeof(*entry));
     entry->func = func;
     entry->run_on_error = run_on_error;
     entry->next = exit_funcs;
     exit_funcs = entry;
 }
References exit_funcs, atexit_listentry_s::func, malloc(), atexit_listentry_s::next, and atexit_listentry_s::run_on_error.
Referenced by D_DoomMain(), D_InitNetGame(), I_InitJoystick(), and S_Init().
I_BaseTiccmd()
ticcmd_t* I_BaseTiccmd (void)
I_BindVariables()
void I_BindVariables (void)
I_ConsoleStdout()
boolean I_ConsoleStdout (void)
Definition at line 210 of file i_system.c.
 {
 #ifdef _WIN32
     // SDL "helpfully" always redirects stdout to a file.
     return 0;
 #else
 #if ORIGCODE
     return isatty(fileno(stdout));
 #else
     return 0;
 #endif
 #endif
 }
References fileno(), isatty(), and stdout.
Referenced by I_Error(), and R_InitTextures().
I_Error()
void I_Error (char * error, ...)
Definition at line 359 of file i_system.c.
 {
     char msgbuf[512];
     va_list argptr;
     atexit_listentry_t *entry;
     boolean exit_gui_popup;
     if (already_quitting)
     {
         fprintf(stderr, "Warning: recursive call to I_Error detected.\n");
 #if ORIGCODE
         exit(-1);
 #endif
     }
     else
     {
         already_quitting = true;
     }
     // Message first.
     va_start(argptr, error);
     //fprintf(stderr, "\nError: ");
     vfprintf(stderr, error, argptr);
     fprintf(stderr, "\n\n");
     va_end(argptr);
     fflush(stderr);
     // Write a copy of the message into buffer.
     va_start(argptr, error);
     memset(msgbuf, 0, sizeof(msgbuf));
     M_vsnprintf(msgbuf, sizeof(msgbuf), error, argptr);
     va_end(argptr);
     // Shutdown. Here might be other errors.
     entry = exit_funcs;
     while (entry != NULL)
     {
         if (entry->run_on_error)
         {
             entry->func();
         }
         entry = entry->next;
     }
     exit_gui_popup = !M_ParmExists("-nogui");
     // Pop up a GUI dialog box to show the error message, if the
     // game was not run from the console (and the user will
     // therefore be unable to otherwise see the message).
     if (exit_gui_popup && !I_ConsoleStdout())
 #ifdef _WIN32
     {
         wchar_t wmsgbuf[512];
         MultiByteToWideChar(CP_ACP, 0,
                             msgbuf, strlen(msgbuf) + 1,
                             wmsgbuf, sizeof(wmsgbuf));
         MessageBoxW(NULL, wmsgbuf, L"", MB_OK);
     }
 #elif defined(__MACOSX__)
     {
         CFStringRef message;
     int i;
     // The CoreFoundation message box wraps text lines, so replace
     // newline characters with spaces so that multiline messages
     // are continuous.
     for (i = 0; msgbuf[i] != '\0'; ++i)
         {
             if (msgbuf[i] == '\n')
             {
                 msgbuf[i] = ' ';
             }
         }
         message = CFStringCreateWithCString(NULL, msgbuf,
                                             kCFStringEncodingUTF8);
         CFUserNotificationDisplayNotice(0,
                                         kCFUserNotificationCautionAlertLevel,
                                         NULL,
                                         NULL,
                                         NULL,
                                         CFSTR(PACKAGE_STRING),
                                         message,
                                         NULL);
     }
 #else
     {
         ZenityErrorBox(msgbuf);
     }
 #endif
     // abort();
 #if ORIGCODE
     SDL_Quit();
     exit(-1);
 #else
     while (true)
     {
     }
 #endif
 }
References already_quitting, exit(), exit_funcs, fflush(), fprintf(), atexit_listentry_s::func, i, I_ConsoleStdout(), M_ParmExists(), M_vsnprintf(), memset, atexit_listentry_s::next, NULL, PACKAGE_STRING, atexit_listentry_s::run_on_error, stderr, strlen(), va_end(), va_start(), vfprintf(), and ZenityErrorBox().
Referenced by AutoAllocMemory(), D_Disconnected(), D_DoomMain(), D_FindIWAD(), D_IdentifyVersion(), D_InitNetGame(), ExtendLumpInfo(), G_CheckDemoStatus(), G_CheckSpot(), G_DeathMatchSpawnPlayer(), G_DoLoadGame(), G_DoSaveGame(), G_Ticker(), G_VanillaVersionCode(), GetDefaultForName(), InitGameVersion(), LoadResponseFile(), M_DrawReadThis1(), M_ReadFile(), M_StringDuplicate(), M_StringJoin(), M_StringReplace(), P_AddActivePlat(), P_CrossSubsector(), P_FindNextHighestFloor(), P_GiveAmmo(), P_InitPicAnims(), P_InitSwitchList(), P_Move(), P_NewChaseDir(), P_PlayerInSpecialSector(), P_RemoveActivePlat(), P_SpawnMapThing(), P_SpawnSpecials(), P_StartButton(), P_TouchSpecialThing(), P_UnArchiveSpecials(), P_UnArchiveThinkers(), PTR_SlideTraverse(), R_DrawColumn(), R_DrawColumnLow(), R_DrawFuzzColumn(), R_DrawFuzzColumnLow(), R_DrawPlanes(), R_DrawPSprite(), R_DrawSpan(), R_DrawSpanLow(), R_DrawTranslatedColumn(), R_DrawTranslatedColumnLow(), R_DrawVisSprite(), R_FindPlane(), R_FlatNumForName(), R_GenerateLookup(), R_InitSpriteDefs(), R_InitTextures(), R_InstallSpriteLump(), R_MapPlane(), R_ProjectSprite(), R_StoreWallRange(), R_Subsector(), R_TextureNumForName(), S_ChangeMusic(), S_SetMusicVolume(), S_SetSfxVolume(), S_StartSound(), SetMissionForPackName(), STlib_drawNum(), STlib_updateBinIcon(), STlib_updateMultIcon(), TryRunTics(), V_CopyRect(), V_DrawAltTLPatch(), V_DrawBlock(), V_DrawPatch(), V_DrawPatchFlipped(), V_DrawShadowedPatch(), V_DrawTLPatch(), V_ScreenShot(), W_AddFile(), W_CacheLumpNum(), W_CheckCorrectIWAD(), W_GetNumForName(), W_LumpLength(), W_ReadLump(), W_ReleaseLumpNum(), Z_ChangeTag2(), Z_ChangeUser(), Z_CheckHeap(), Z_Free(), and Z_Malloc().
I_GetMemoryValue()
boolean I_GetMemoryValue (unsigned int offset, void * value, int size)
Definition at line 499 of file i_system.c.
 {
     static boolean firsttime = true;
     if (firsttime)
     {
         int p, i, val;
         firsttime = false;
         i = 0;
         // @category compat
         // @arg <version>
         //
         // Specify DOS version to emulate for NULL pointer dereference
         // emulation.  Supported versions are: dos622, dos71, dosbox.
         // The default is to emulate DOS 7.1 (Windows 98).
         //
         p = M_CheckParmWithArgs("-setmem", 1);
         if (p > 0)
         {
             if (!strcasecmp(myargv[p + 1], "dos622"))
             {
                 dos_mem_dump = mem_dump_dos622;
             }
             if (!strcasecmp(myargv[p + 1], "dos71"))
             {
                 dos_mem_dump = mem_dump_win98;
             }
             else if (!strcasecmp(myargv[p + 1], "dosbox"))
             {
                 dos_mem_dump = mem_dump_dosbox;
             }
             else
             {
                 for (i = 0; i < DOS_MEM_DUMP_SIZE; ++i)
                 {
                     ++p;
                     if (p >= myargc || myargv[p][0] == '-')
                     {
                         break;
                     }
                     M_StrToInt(myargv[p], &val);
                     mem_dump_custom[i++] = (unsigned char) val;
                 }
                 dos_mem_dump = mem_dump_custom;
             }
         }
     }
     switch (size)
     {
     case 1:
         *((unsigned char *) value) = dos_mem_dump[offset];
         return true;
     case 2:
         *((unsigned short *) value) = dos_mem_dump[offset]
                                     | (dos_mem_dump[offset + 1] << 8);
         return true;
     case 4:
         *((unsigned int *) value) = dos_mem_dump[offset]
                                   | (dos_mem_dump[offset + 1] << 8)
                                   | (dos_mem_dump[offset + 2] << 16)
                                   | (dos_mem_dump[offset + 3] << 24);
         return true;
     }
     return false;
 }
References dos_mem_dump, DOS_MEM_DUMP_SIZE, i, M_CheckParmWithArgs(), M_StrToInt(), mem_dump_custom, mem_dump_dos622, mem_dump_dosbox, mem_dump_win98, myargc, myargv, offset, p, size, strcasecmp(), and value.
Referenced by GetSectorAtNullAddress().
I_Init()
void I_Init (void)
I_PrintBanner()
void I_PrintBanner (char * text)
Definition at line 166 of file i_system.c.
 {
     int i;
     int spaces = 35 - (strlen(msg) / 2);
     for (i=0; i<spaces; ++i)
         putchar(' ');
     puts(msg);
 }
References i, putchar(), puts(), and strlen().
Referenced by D_DoomMain(), and I_PrintStartupBanner().
I_PrintDivider()
void I_PrintDivider (void)
Definition at line 177 of file i_system.c.
 {
     int i;
     for (i=0; i<75; ++i)
     {
         putchar('=');
     }
     putchar('\n');
 }
References i, and putchar().
Referenced by D_DoomMain(), and I_PrintStartupBanner().
I_PrintStartupBanner()
void I_PrintStartupBanner (char * gamedescription)
Definition at line 189 of file i_system.c.
 {
     I_PrintDivider();
     I_PrintBanner(gamedescription);
     I_PrintDivider();
     printf(
     " " PACKAGE_NAME " is free software, covered by the GNU General Public\n"
     " License.  There is NO warranty; not even for MERCHANTABILITY or FITNESS\n"
     " FOR A PARTICULAR PURPOSE. You are welcome to change and distribute\n"
     " copies under certain conditions. See the source for more information.\n");
     I_PrintDivider();
 }
References gamedescription, I_PrintBanner(), I_PrintDivider(), PACKAGE_NAME, and printf.
Referenced by D_DoomMain().
I_Quit()
void I_Quit (void)
Definition at line 246 of file i_system.c.
 {
     atexit_listentry_t *entry;
     // Run through all exit functions
     entry = exit_funcs;
     while (entry != NULL)
     {
         entry->func();
         entry = entry->next;
     }
 #if ORIGCODE
     SDL_Quit();
     exit(0);
 #endif
 }
References exit(), exit_funcs, atexit_listentry_s::func, atexit_listentry_s::next, and NULL.
Referenced by G_CheckDemoStatus(), M_QuitResponse(), and M_Responder().
I_Tactile()
void I_Tactile (int on, int off, int total)
Definition at line 87 of file i_system.c.
 {
 }
Referenced by P_DamageMobj().
I_ZoneBase()
byte* I_ZoneBase (int * size)
Definition at line 133 of file i_system.c.
 {
     byte *zonemem;
     int min_ram, default_ram;
     int p;
     // @arg <mb>
     //
     // Specify the heap size, in MiB (default 16).
     //
     p = M_CheckParmWithArgs("-mb", 1);
     if (p > 0)
     {
         default_ram = atoi(myargv[p+1]);
         min_ram = default_ram;
     }
     else
     {
         default_ram = DEFAULT_RAM;
         min_ram = MIN_RAM;
     }
     zonemem = AutoAllocMemory(size, default_ram, min_ram);
     printf("zone memory: %p, %x allocated for zone\n",
            zonemem, *size);
     return zonemem;
 }
References atoi(), AutoAllocMemory(), DEFAULT_RAM, M_CheckParmWithArgs(), MIN_RAM, myargv, p, printf, and size.
Referenced by Z_Init().