Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/memio.h File Reference
memio.h File Reference
Typedefs
typedef struct _MEMFILE MEMFILE
Enumerations
enum mem_rel_t { MEM_SEEK_SET , MEM_SEEK_CUR , MEM_SEEK_END }
Functions
MEMFILE * mem_fopen_read (void *buf, size_t buflen)
size_t mem_fread (void *buf, size_t size, size_t nmemb, MEMFILE *stream)
MEMFILE * mem_fopen_write (void)
size_t mem_fwrite (const void *ptr, size_t size, size_t nmemb, MEMFILE *stream)
void mem_get_buf (MEMFILE *stream, void **buf, size_t *buflen)
void mem_fclose (MEMFILE *stream)
long mem_ftell (MEMFILE *stream)
int mem_fseek (MEMFILE *stream, signed long offset, mem_rel_t whence)
Typedef Documentation
MEMFILE
typedef struct _MEMFILE MEMFILE
Definition at line 1 of file memio.h.
Enumeration Type Documentation
mem_rel_t
enum mem_rel_t
Enumerator
MEM_SEEK_SET
MEM_SEEK_CUR
MEM_SEEK_END
Definition at line 21 of file memio.h.
 {
     MEM_SEEK_SET,
     MEM_SEEK_CUR,
     MEM_SEEK_END,
 } mem_rel_t;
Function Documentation
mem_fclose()
void mem_fclose (MEMFILE * stream)
Definition at line 149 of file memio.c.
 {
     if (stream->mode == MODE_WRITE)
     {
         Z_Free(stream->buf);
     }
     Z_Free(stream);
 }
References _MEMFILE::buf, _MEMFILE::mode, MODE_WRITE, and Z_Free().
mem_fopen_read()
MEMFILE* mem_fopen_read (void * buf, size_t buflen)
Definition at line 42 of file memio.c.
 {
     MEMFILE *file;
     file = Z_Malloc(sizeof(MEMFILE), PU_STATIC, 0);
     file->buf = (unsigned char *) buf;
     file->buflen = buflen;
     file->position = 0;
     file->mode = MODE_READ;
     return file;
 }
References buf, buflen, MODE_READ, PU_STATIC, and Z_Malloc().
mem_fopen_write()
MEMFILE* mem_fopen_write (void)
Definition at line 90 of file memio.c.
 {
     MEMFILE *file;
     file = Z_Malloc(sizeof(MEMFILE), PU_STATIC, 0);
     file->alloced = 1024;
     file->buf = Z_Malloc(file->alloced, PU_STATIC, 0);
     file->buflen = 0;
     file->position = 0;
     file->mode = MODE_WRITE;
     return file;
 }
References MODE_WRITE, PU_STATIC, and Z_Malloc().
mem_fread()
size_t mem_fread (void * buf, size_t size, size_t nmemb, MEMFILE * stream)
Definition at line 58 of file memio.c.
 {
     size_t items;
     if (stream->mode != MODE_READ)
     {
         printf("not a read stream\n");
         return -1;
     }
     // Trying to read more bytes than we have left?
     items = nmemb;
     if (items * size > stream->buflen - stream->position)
     {
         items = (stream->buflen - stream->position) / size;
     }
     // Copy bytes to buffer
     memcpy(buf, stream->buf + stream->position, items * size);
     // Update position
     stream->position += items * size;
     return items;
 }
References buf, _MEMFILE::buf, _MEMFILE::buflen, items, memcpy(), _MEMFILE::mode, MODE_READ, _MEMFILE::position, printf(), and size.
Referenced by mus2mid(), and ReadMusHeader().
mem_fseek()
int mem_fseek (MEMFILE * stream, signed long offset, mem_rel_t whence)
Definition at line 164 of file memio.c.
 {
     unsigned int newpos;
     switch (whence)
     {
         case MEM_SEEK_SET:
             newpos = (int) position;
             break;
         case MEM_SEEK_CUR:
             newpos = (int) (stream->position + position);
             break;
         case MEM_SEEK_END:
             newpos = (int) (stream->buflen + position);
             break;
         default:
             return -1;
     }
     if (newpos < stream->buflen)
     {
         stream->position = newpos;
         return 0;
     }
     else
     {
         printf("Error seeking to %i\n", newpos);
         return -1;
     }
 }
References buflen, _MEMFILE::buflen, MEM_SEEK_CUR, MEM_SEEK_END, MEM_SEEK_SET, _MEMFILE::position, and printf().
Referenced by mus2mid().
mem_ftell()
long mem_ftell (MEMFILE * stream)
Definition at line 159 of file memio.c.
 {
     return stream->position;
 }
References _MEMFILE::position.
mem_fwrite()
size_t mem_fwrite (const void * ptr, size_t size, size_t nmemb, MEMFILE * stream)
Definition at line 107 of file memio.c.
 {
     size_t bytes;
     if (stream->mode != MODE_WRITE)
     {
         return -1;
     }
     // More bytes than can fit in the buffer?
     // If so, reallocate bigger.
     bytes = size * nmemb;
     while (bytes > stream->alloced - stream->position)
     {
         unsigned char *newbuf;
         newbuf = Z_Malloc(stream->alloced * 2, PU_STATIC, 0);
         memcpy(newbuf, stream->buf, stream->alloced);
         Z_Free(stream->buf);
         stream->buf = newbuf;
         stream->alloced *= 2;
     }
     // Copy into buffer
     memcpy(stream->buf + stream->position, ptr, bytes);
     stream->position += bytes;
     if (stream->position > stream->buflen)
         stream->buflen = stream->position;
     return nmemb;
 }
References _MEMFILE::alloced, _MEMFILE::buf, _MEMFILE::buflen, memcpy(), _MEMFILE::mode, MODE_WRITE, _MEMFILE::position, PU_STATIC, size, Z_Free(), and Z_Malloc().
Referenced by mus2mid(), WriteChangeController_Valued(), WriteChangePatch(), WriteEndTrack(), WritePitchWheel(), WritePressKey(), WriteReleaseKey(), and WriteTime().
mem_get_buf()
void mem_get_buf (MEMFILE * stream, void ** buf, size_t * buflen)
Definition at line 143 of file memio.c.
 {
     *buf = stream->buf;
     *buflen = stream->buflen;
 }
References buf, _MEMFILE::buf, buflen, and _MEMFILE::buflen.