Fennix: Userspace/apps/base/bash/examples/loadables/rmdir.c File Reference
rmdir.c File Reference
#include "config.h"
#include <stdio.h>
#include <errno.h>
#include "builtins.h"
#include "shell.h"
#include "common.h"
Functions
int rmdir_builtin (WORD_LIST *list)
Variables
int errno
char * rmdir_doc []
struct builtin rmdir_struct
Function Documentation
rmdir_builtin()
int rmdir_builtin (WORD_LIST * list)
Definition at line 36 of file rmdir.c.
 {
   int rval;
   WORD_LIST *l;
   if (no_options (list))
     return (EX_USAGE);
   for (rval = EXECUTION_SUCCESS, l = list; l; l = l->next)
     if (rmdir (l->word->word) < 0)
       {
     builtin_error ("%s: %s", l->word->word, strerror (errno));
     rval = EXECUTION_FAILURE;
       }
   return rval;
 }
References builtin_error(), errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, word_list::next, no_options(), rmdir(), strerror(), word_desc::word, and word_list::word.
Variable Documentation
errno
int errno extern
Referenced by rmdir_builtin().
rmdir_doc
char* rmdir_doc[]
Initial value:
= {
    "Remove directory.",
    "",
    "rmdir removes the directory entry specified by each argument,",
    "provided the directory is empty.",
    (char *)NULL
}
Definition at line 55 of file rmdir.c.
rmdir_struct
struct builtin rmdir_struct
Initial value:
= {
    "rmdir",
    rmdir_builtin,
    BUILTIN_ENABLED,
    rmdir_doc,
    "rmdir directory ...",
    0
}
Definition at line 55 of file rmdir.c.