Fennix: Userspace/apps/base/busybox/coreutils/expr.c File Reference
expr.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include "xregex.h"
Data Structures
struct valinfo
struct globals
union valinfo.u
Macros
#define PF_REZ "l"
#define PF_REZ_TYPE (long)
#define STRTOL(s, e, b) strtol(s, e, b)
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
Typedefs
typedef long arith_t
typedef struct valinfo VALUE
Enumerations
enum { INTEGER , STRING }
Functions
static VALUE * eval (void)
static VALUE * int_value (arith_t i)
static VALUE * str_value (const char *s)
static void freev (VALUE *v)
static int null (VALUE *v)
static void tostring (VALUE *v)
static bool toarith (VALUE *v)
static int nextarg (const char *str)
static int cmp_common (VALUE *l, VALUE *r, int op)
static arith_t arithmetic_common (VALUE *l, VALUE *r, int op)
static VALUE * docolon (VALUE *sv, VALUE *pv)
static VALUE * eval7 (void)
static VALUE * eval6 (void)
static VALUE * eval5 (void)
static VALUE * eval4 (void)
static VALUE * eval3 (void)
static VALUE * eval2 (void)
static VALUE * eval1 (void)
int expr_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Data Structure Documentation
valinfo
struct valinfo
Definition at line 107 of file expr.c.
Data Fields
smallint type
union valinfo u
valinfo.u
union valinfo.u
Definition at line 109 of file expr.c.
Data Fields
arith_t i
char * s
Macro Definition Documentation
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 120 of file expr.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    /* NB: noexec applet - globals not zeroed */ \
} while (0)
Definition at line 121 of file expr.c.
PF_REZ
#define PF_REZ "l"
Definition at line 93 of file expr.c.
PF_REZ_TYPE
#define PF_REZ_TYPE (long)
Definition at line 94 of file expr.c.
STRTOL
#define STRTOL (s, e, b) strtol(s, e, b)
Definition at line 95 of file expr.c.
Typedef Documentation
arith_t
typedef long arith_t
Definition at line 91 of file expr.c.
VALUE
typedef struct valinfo VALUE
Definition at line 91 of file expr.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
INTEGER
STRING
Definition at line 101 of file expr.c.
      {
     INTEGER,
     STRING
 };
Function Documentation
arithmetic_common()
static arith_t arithmetic_common (VALUE * l, VALUE * r, int op) static
Definition at line 247 of file expr.c.
 {
     arith_t li, ri;
     if (!toarith(l) || !toarith(r))
         bb_simple_error_msg_and_die("non-numeric argument");
     li = l->u.i;
     ri = r->u.i;
     if (op == '+')
         return li + ri;
     if (op == '-')
         return li - ri;
     if (op == '*')
         return li * ri;
     if (ri == 0)
         bb_simple_error_msg_and_die("division by zero");
     if (op == '/')
         return li / ri;
     return li % ri;
 }
References bb_simple_error_msg_and_die(), l, toarith(), and valinfo::u.
Referenced by eval3(), and eval4().
cmp_common()
static int cmp_common (VALUE * l, VALUE * r, int op) static
Definition at line 217 of file expr.c.
 {
     arith_t ll, rr;
     ll = l->u.i;
     rr = r->u.i;
     if (l->type == STRING || r->type == STRING) {
         tostring(l);
         tostring(r);
         ll = strcmp(l->u.s, r->u.s);
         rr = 0;
     }
     /* calculating ll - rr and checking the result is prone to overflows.
      * We'll do it differently: */
     if (op == '<')
         return ll < rr;
     if (op == ('<' + '='))
         return ll <= rr;
     if (op == '=' || (op == '=' + '='))
         return ll == rr;
     if (op == '!' + '=')
         return ll != rr;
     if (op == '>')
         return ll > rr;
     /* >= */
     return ll >= rr;
 }
References l, strcmp, STRING, tostring(), valinfo::type, and valinfo::u.
Referenced by eval2().
docolon()
static VALUE* docolon (VALUE * sv, VALUE * pv) static
Definition at line 272 of file expr.c.
 {
     enum { NMATCH = 2 };
     VALUE *v;
     regex_t re_buffer;
     regmatch_t re_regs[NMATCH];
     tostring(sv);
     tostring(pv);
     if (pv->u.s[0] == '^') {
         bb_error_msg(
 "warning: '%s': using '^' as the first character\n"
 "of a basic regular expression is not portable; it is ignored", pv->u.s);
     }
     memset(&re_buffer, 0, sizeof(re_buffer));
     memset(re_regs, 0, sizeof(re_regs));
     xregcomp(&re_buffer, pv->u.s, 0);
     /* expr uses an anchored pattern match, so check that there was a
      * match and that the match starts at offset 0. */
     if (regexec(&re_buffer, sv->u.s, NMATCH, re_regs, 0) != REG_NOMATCH
      && re_regs[0].rm_so == 0
     ) {
         /* Were \‍(...\‍) used? */
         if (re_buffer.re_nsub > 0 && re_regs[1].rm_so >= 0) {
             sv->u.s[re_regs[1].rm_eo] = '\0';
             v = str_value(sv->u.s + re_regs[1].rm_so);
         } else {
             v = int_value(re_regs[0].rm_eo);
         }
     } else {
         /* Match failed -- return the right kind of null.  */
         if (re_buffer.re_nsub > 0)
             v = str_value("");
         else
             v = int_value(0);
     }
     regfree(&re_buffer);
     return v;
 }
References bb_error_msg(), int_value(), memset, re_buffer, REG_NOMATCH, regexec, regfree(), regmatch_t::rm_eo, regmatch_t::rm_so, str_value(), sv, tostring(), valinfo::u, and xregcomp.
Referenced by eval5(), and eval6().
eval()
static VALUE * eval (void) static
Definition at line 522 of file expr.c.
 {
     VALUE *l, *r;
     l = eval1();
     while (nextarg("|")) {
         G.args++;
         r = eval1();
         if (null(l)) {
             freev(l);
             l = r;
         } else
             freev(r);
     }
     return l;
 }
References eval1(), freev(), G, l, and nextarg().
Referenced by eval7(), expr_main(), and main().
eval1()
static VALUE* eval1 (void) static
Definition at line 502 of file expr.c.
 {
     VALUE *l, *r;
     l = eval2();
     while (nextarg("&")) {
         G.args++;
         r = eval2();
         if (null(l) || null(r)) {
             freev(l);
             freev(r);
             l = int_value(0);
         } else
             freev(r);
     }
     return l;
 }
References eval2(), freev(), G, int_value(), l, and nextarg().
Referenced by eval().
eval2()
static VALUE* eval2 (void) static
Definition at line 472 of file expr.c.
 {
     VALUE *l, *r;
     int op;
     arith_t val;
     l = eval3();
     while (1) {
         op = nextarg("<");
         if (!op) { op = nextarg("<=");
          if (!op) { op = nextarg("=");
           if (!op) { op = nextarg("==");
            if (!op) { op = nextarg("!=");
             if (!op) { op = nextarg(">=");
              if (!op) { op = nextarg(">");
               if (!op) return l;
         }}}}}}
         G.args++;
         r = eval3();
         toarith(l);
         toarith(r);
         val = cmp_common(l, r, op);
         freev(l);
         freev(r);
         l = int_value(val);
     }
 }
References cmp_common(), eval3(), freev(), G, int_value(), l, nextarg(), toarith(), and val.
Referenced by eval1().
eval3()
static VALUE* eval3 (void) static
Definition at line 448 of file expr.c.
 {
     VALUE *l, *r;
     int op;
     arith_t val;
     l = eval4();
     while (1) {
         op = nextarg("+");
         if (!op) {
             op = nextarg("-");
             if (!op) return l;
         }
         G.args++;
         r = eval4();
         val = arithmetic_common(l, r, op);
         freev(l);
         freev(r);
         l = int_value(val);
     }
 }
References arithmetic_common(), eval4(), freev(), G, int_value(), l, nextarg(), and val.
Referenced by eval2().
eval4()
static VALUE* eval4 (void) static
Definition at line 424 of file expr.c.
 {
     VALUE *l, *r;
     int op;
     arith_t val;
     l = eval5();
     while (1) {
         op = nextarg("*");
         if (!op) { op = nextarg("/");
          if (!op) { op = nextarg("%");
           if (!op) return l;
         }}
         G.args++;
         r = eval5();
         val = arithmetic_common(l, r, op);
         freev(l);
         freev(r);
         l = int_value(val);
     }
 }
References arithmetic_common(), eval5(), freev(), G, int_value(), l, nextarg(), and val.
Referenced by eval3().
eval5()
static VALUE* eval5 (void) static
Definition at line 406 of file expr.c.
 {
     VALUE *l, *r, *v;
     l = eval6();
     while (nextarg(":")) {
         G.args++;
         r = eval6();
         v = docolon(l, r);
         freev(l);
         freev(r);
         l = v;
     }
     return l;
 }
References docolon(), eval6(), freev(), G, l, and nextarg().
Referenced by eval4().
eval6()
static VALUE* eval6 (void) static
Definition at line 341 of file expr.c.
 {
     static const char keywords[] ALIGN1 =
         "quote\0""length\0""match\0""index\0""substr\0";
     VALUE *r, *i1, *i2;
     VALUE *l = l; /* silence gcc */
     VALUE *v = v; /* silence gcc */
     int key = *G.args ? index_in_strings(keywords, *G.args) + 1 : 0;
     if (key == 0) /* not a keyword */
         return eval7();
     G.args++; /* We have a valid token, so get the next argument.  */
     if (key == 1) { /* quote */
         if (!*G.args)
             bb_simple_error_msg_and_die("syntax error");
         return str_value(*G.args++);
     }
     if (key == 2) { /* length */
         r = eval6();
         tostring(r);
         v = int_value(strlen(r->u.s));
         freev(r);
     } else
         l = eval6();
     if (key == 3) { /* match */
         r = eval6();
         v = docolon(l, r);
         freev(l);
         freev(r);
     }
     if (key == 4) { /* index */
         r = eval6();
         tostring(l);
         tostring(r);
         v = int_value(strcspn(l->u.s, r->u.s) + 1);
         if (v->u.i == (arith_t) strlen(l->u.s) + 1)
             v->u.i = 0;
         freev(l);
         freev(r);
     }
     if (key == 5) { /* substr */
         i1 = eval6();
         i2 = eval6();
         tostring(l);
         if (!toarith(i1) || !toarith(i2)
          || i1->u.i > (arith_t) strlen(l->u.s)
          || i1->u.i <= 0 || i2->u.i <= 0)
             v = str_value("");
         else {
             v = xmalloc(sizeof(VALUE));
             v->type = STRING;
             v->u.s = xstrndup(l->u.s + i1->u.i - 1, i2->u.i);
         }
         freev(l);
         freev(i1);
         freev(i2);
     }
     return v;
 }
References ALIGN1, bb_simple_error_msg_and_die(), docolon(), eval7(), freev(), G, index_in_strings(), int_value(), l, str_value(), strcspn(), STRING, strlen(), toarith(), tostring(), valinfo::type, valinfo::u, xmalloc, and xstrndup().
Referenced by eval5().
eval7()
static VALUE* eval7 (void) static
Definition at line 317 of file expr.c.
 {
     VALUE *v;
     if (!*G.args)
         bb_simple_error_msg_and_die("syntax error");
     if (nextarg("(")) {
         G.args++;
         v = eval();
         if (!nextarg(")"))
             bb_simple_error_msg_and_die("syntax error");
         G.args++;
         return v;
     }
     if (nextarg(")"))
         bb_simple_error_msg_and_die("syntax error");
     return str_value(*G.args++);
 }
References bb_simple_error_msg_and_die(), eval(), G, nextarg(), and str_value().
Referenced by eval6().
expr_main()
int expr_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 540 of file expr.c.
 {
     VALUE *v;
     INIT_G();
     xfunc_error_retval = 2; /* coreutils compat */
     G.args = argv + 1;
     if (*G.args == NULL) {
         bb_simple_error_msg_and_die("too few arguments");
     }
     v = eval();
     if (*G.args)
         bb_simple_error_msg_and_die("syntax error");
     if (v->type == INTEGER)
         printf("%" PF_REZ "d\n", PF_REZ_TYPE v->u.i);
     else
         puts(v->u.s);
     fflush_stdout_and_exit(null(v));
 }
References argv, bb_simple_error_msg_and_die(), eval(), fflush_stdout_and_exit(), G, INIT_G, INTEGER, NULL, PF_REZ, PF_REZ_TYPE, printf, puts(), valinfo::type, valinfo::u, and xfunc_error_retval.
freev()
static void freev (VALUE * v) static
Definition at line 158 of file expr.c.
 {
     if (v->type == STRING)
         free(v->u.s);
     free(v);
 }
References free, STRING, valinfo::type, and valinfo::u.
Referenced by eval(), eval1(), eval2(), eval3(), eval4(), eval5(), and eval6().
int_value()
static VALUE* int_value (arith_t i) static
Definition at line 132 of file expr.c.
 {
     VALUE *v;
     v = xzalloc(sizeof(VALUE));
     if (INTEGER) /* otherwise xzalloc did it already */
         v->type = INTEGER;
     v->u.i = i;
     return v;
 }
References i, INTEGER, valinfo::type, valinfo::u, and xzalloc().
Referenced by docolon(), eval1(), eval2(), eval3(), eval4(), and eval6().
nextarg()
static int nextarg (const char * str) static
Definition at line 208 of file expr.c.
 {
     if (*G.args == NULL || strcmp(*G.args, str) != 0)
         return 0;
     return (unsigned char)str[0] + (unsigned char)str[1];
 }
References G, NULL, str, and strcmp.
Referenced by eval(), eval1(), eval2(), eval3(), eval4(), eval5(), and eval7().
null()
static int null (VALUE * v) static
Definition at line 167 of file expr.c.
 {
     if (v->type == INTEGER)
         return v->u.i == 0;
     /* STRING: */
     return v->u.s[0] == '\0' || LONE_CHAR(v->u.s, '0');
 }
References INTEGER, and LONE_CHAR.
Referenced by ConfigMainWindow::setHelp(), ConfigLineEdit::show(), and ConfigItem::updateMenu().
str_value()
static VALUE* str_value (const char * s) static
Definition at line 145 of file expr.c.
 {
     VALUE *v;
     v = xzalloc(sizeof(VALUE));
     if (STRING) /* otherwise xzalloc did it already */
         v->type = STRING;
     v->u.s = xstrdup(s);
     return v;
 }
References s, STRING, valinfo::type, valinfo::u, xstrdup(), and xzalloc().
Referenced by docolon(), eval6(), and eval7().
toarith()
static bool toarith (VALUE * v) static
Definition at line 187 of file expr.c.
 {
     if (v->type == STRING) {
         arith_t i;
         char *e;
         /* Don't interpret the empty string as an integer.  */
         /* Currently does not worry about overflow or int/long differences. */
         i = STRTOL(v->u.s, &e, 10);
         if ((v->u.s == e) || *e)
             return 0;
         free(v->u.s);
         v->u.i = i;
         v->type = INTEGER;
     }
     return 1;
 }
References free, i, INTEGER, STRING, STRTOL, valinfo::type, and valinfo::u.
Referenced by arithmetic_common(), eval2(), and eval6().
tostring()
static void tostring (VALUE * v) static
Definition at line 177 of file expr.c.
 {
     if (v->type == INTEGER) {
         v->u.s = xasprintf("%" PF_REZ "d", PF_REZ_TYPE v->u.i);
         v->type = STRING;
     }
 }
References INTEGER, PF_REZ, PF_REZ_TYPE, STRING, valinfo::type, valinfo::u, and xasprintf().
Referenced by cmp_common(), docolon(), and eval6().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING