Fennix: Userspace/musl/src/fcntl/open.c File Reference
open.c File Reference
#include <fcntl.h>
#include <stdarg.h>
#include "syscall.h"
Functions
int open (const char *filename, int flags,...)
Function Documentation
open()
int open (const char * filename, int flags, ...)
Definition at line 5 of file open.c.
 {
     mode_t mode = 0;
     if ((flags & O_CREAT) || (flags & O_TMPFILE) == O_TMPFILE) {
         va_list ap;
         va_start(ap, flags);
         mode = va_arg(ap, mode_t);
         va_end(ap);
     }
     int fd = __sys_open_cp(filename, flags, mode);
     if (fd>=0 && (flags & O_CLOEXEC))
         __syscall(SYS_fcntl, fd, F_SETFD, FD_CLOEXEC);
     return __syscall_ret(fd);
 }
References __sys_open_cp, __syscall, __syscall_ret(), ap, F_SETFD, fd, FD_CLOEXEC, filename, flags, mode_t, O_CLOEXEC, O_CREAT, O_TMPFILE, va_arg, va_end, and va_start.
Referenced by __dls3(), __mkostemps(), _evalfile(), _nl_load_domain(), _rl_read_file(), _vsyslog(), acpid_main(), add_to_uuid_cache(), archivefile(), async_redirect_stdin(), bb_daemonize_or_rexec(), bb_init_module(), cat_main(), check_dev_tty(), check_mount(), console_init(), copy_file(), copy_inode(), creat(), create_cdev_if_doesnt_exist(), crontab_main(), cttyhack_main(), cutfile(), daemon(), del_loop(), device_open(), dialog_textbox(), diffreg(), do_config_file(), do_nftw(), download_one_url(), dump_file(), dump_procs(), edir(), extract_info(), fbsplash_main(), file_insert(), file_write(), filter_rename_config(), flock_main(), fmtmsg(), forkchild(), get_boot(), get_free_loop(), get_terminal_width_height(), get_vt_fd(), getpass(), getrandom(), getspnam_r(), getty_main(), handle_retr(), here_document_to_fd(), hfopen(), history_do_write(), history_truncate_file(), i2c_dev_open(), initialize_job_control(), is_whole_disk(), less_main(), load_firmware(), load_library(), log_locally(), logdir_open(), main(), microcom_main(), motd(), nbdclient_main(), noclobber_open(), nohup_main(), open3_or_warn(), open_a_console(), open_loop_on_busy(), open_mdev_log(), open_new_state_file(), open_read_close(), open_redir_file(), open_shell_script(), open_trunc_or_warn(), opendir(), openpty(), openredirect(), parse_comsub(), parse_matched_pair(), path_open(), posix_openpt(), print_deps(), process_includes(), processorstart(), pscan_main(), pthread_getname_np(), pthread_setname_np(), query_loop(), read_history_range(), read_to_buf(), readLines(), redir_open(), redir_special_open(), rotate(), run_pipe(), runsv_main(), runsvdir_main(), sem_open(), send_file_and_exit(), set_loop(), ConfigList::setAllOpen(), setinputfile(), sh_mktmpfd(), shm_open(), shred_main(), skip_matched_pair(), skip_to_delim(), slattach_main(), sysctl_act_on_setting(), tail_main(), tee_builtin(), tgetent(), touch(), touch_main(), truncate_main(), unquoted_glob_pattern_p(), unzip_main(), update_passwd(), wait_for_seqfile(), write_pidfile(), xgetpty(), xmalloc_open_read_close(), and xopen3().