Fennix: Kernel/syscalls/native/uname.cpp File Reference
uname.cpp File Reference
#include <syscalls.hpp>
#include <memory.hpp>
#include <utsname.h>
#include <lock.hpp>
#include <exec.hpp>
#include <errno.h>
#include <debug.h>
#include "../../syscalls.h"
#include "../../kernel.h"
Functions
int sys_uname (SysFrm *, struct utsname *buf)
Function Documentation
sys_uname()
int sys_uname (SysFrm * , struct utsname * buf)
Definition at line 34 of file uname.cpp.
 {
     assert(sizeof(struct utsname) < PAGE_SIZE);
     Tasking::PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check(buf, Memory::US))
     {
         warn("Invalid address %#lx", buf);
         return -EFAULT;
     }
     auto pBuf = pcb->PageTable->Get(buf);
     struct utsname uname =
     {
         /* TODO: This shouldn't be hardcoded */
         .sysname = KERNEL_NAME,
         .nodename = "fennix",
         .release = KERNEL_VERSION,
         .version = KERNEL_VERSION,
 #if defined(a64)
         .machine = "x86_64",
 #elif defined(a32)
         .machine = "i386",
 #elif defined(aa64)
         .machine = "arm64",
 #elif defined(aa32)
         .machine = "arm",
 #endif
     };
     memcpy(pBuf, &uname, sizeof(struct utsname));
     return 0;
 }
References assert, buf, Memory::Virtual::Check(), EFAULT, Memory::PageTable::Get(), KERNEL_VERSION, memcpy, PAGE_SIZE, Tasking::PCB::PageTable, thisProcess, uname(), Memory::US, and warn.