Fennix: Kernel/core/module/module_api.cpp File Reference
module_api.cpp File Reference
#include <module.hpp>
#include <dumper.hpp>
#include <lock.hpp>
#include "../../kernel.h"
#include "../../Fex.hpp"
#include "api.hpp"
Macros
#define modbg(m, ...)
Functions
NewLock (ModuleDisplayPrintLock)
void ModuleDebugPrint (char *String, __UINT64_TYPE__ modUniqueID)
void ModuleDisplayPrint (char *String)
void * RequestPage (__UINT64_TYPE__ Size)
void FreePage (void *Page, __UINT64_TYPE__ Size)
void MapMemory (void *VirtualAddress, void *PhysicalAddress, __UINT64_TYPE__ Flags)
void UnmapMemory (void *VirtualAddress)
void * Modulememcpy (void *Destination, void *Source, __UINT64_TYPE__ Size)
void * Modulememset (void *Destination, int Value, __UINT64_TYPE__ Size)
void ModuleNetSend (__UINT32_TYPE__ ModuleID, __UINT8_TYPE__ *Data, __UINT16_TYPE__ Size)
void ModuleNetReceive (__UINT32_TYPE__ ModuleID, __UINT8_TYPE__ *Data, __UINT16_TYPE__ Size)
void ModuleAHCIDiskRead (__UINT32_TYPE__ ModuleID, __UINT64_TYPE__ Sector, __UINT8_TYPE__ *Data, __UINT32_TYPE__ SectorCount, __UINT8_TYPE__ Port)
void ModuleAHCIDiskWrite (__UINT32_TYPE__ ModuleID, __UINT64_TYPE__ Sector, __UINT8_TYPE__ *Data, __UINT32_TYPE__ SectorCount, __UINT8_TYPE__ Port)
char * ModulePCIGetDeviceName (__UINT32_TYPE__ VendorID, __UINT32_TYPE__ DeviceID)
__UINT32_TYPE__ ModuleGetWidth ()
__UINT32_TYPE__ ModuleGetHeight ()
void ModuleSleep (__UINT64_TYPE__ Milliseconds)
int Modulesprintf (char *Buffer, const char *Format,...)
Variables
KernelAPI KernelAPITemplate
Macro Definition Documentation
modbg
#define modbg (m, ...)
Definition at line 33 of file module_api.cpp.
Function Documentation
FreePage()
void FreePage (void * Page, __UINT64_TYPE__ Size)
Definition at line 59 of file module_api.cpp.
 {
     modbg("Freeing %ld pages (%#lx-%#lx)",
            Size, (__UINT64_TYPE__)Page,
            (__UINT64_TYPE__)Page + FROM_PAGES(Size));
     KernelAllocator.FreePages(Page, size_t(Size + 1));
 }
References FROM_PAGES, KernelAllocator, modbg, and Size.
MapMemory()
void MapMemory (void * VirtualAddress, void * PhysicalAddress, __UINT64_TYPE__ Flags)
Definition at line 67 of file module_api.cpp.
 {
     SmartLock(ModuleDisplayPrintLock);
     modbg("Mapping %#lx to %#lx with flags %#lx...",
            (__UINT64_TYPE__)VirtualAddress,
            (__UINT64_TYPE__)PhysicalAddress, Flags);
     Memory::Virtual(KernelPageTable).Map(VirtualAddress, PhysicalAddress, Flags);
 }
References Flags, KernelPageTable, Memory::Virtual::Map(), modbg, and PhysicalAddress.
ModuleAHCIDiskRead()
void ModuleAHCIDiskRead (__UINT32_TYPE__ ModuleID, __UINT64_TYPE__ Sector, __UINT8_TYPE__ * Data, __UINT32_TYPE__ SectorCount, __UINT8_TYPE__ Port)
Definition at line 119 of file module_api.cpp.
 {
     DumpData("ModuleDiskRead", Data, SectorCount * 512);
     UNUSED(ModuleID);
     UNUSED(Sector);
     UNUSED(Port);
 }
References Data, DumpData(), and UNUSED.
ModuleAHCIDiskWrite()
void ModuleAHCIDiskWrite (__UINT32_TYPE__ ModuleID, __UINT64_TYPE__ Sector, __UINT8_TYPE__ * Data, __UINT32_TYPE__ SectorCount, __UINT8_TYPE__ Port)
Definition at line 131 of file module_api.cpp.
 {
     DumpData("ModuleDiskWrite",
              Data, SectorCount * 512);
     UNUSED(ModuleID);
     UNUSED(Sector);
     UNUSED(Port);
 }
References Data, DumpData(), and UNUSED.
ModuleDebugPrint()
void ModuleDebugPrint (char * String, __UINT64_TYPE__ modUniqueID)
Definition at line 38 of file module_api.cpp.
 {
     trace("[%ld] %s", modUniqueID, String);
 }
References trace.
ModuleDisplayPrint()
void ModuleDisplayPrint (char * String)
Definition at line 43 of file module_api.cpp.
 {
     SmartLock(ModuleDisplayPrintLock);
     for (__UINT64_TYPE__ i = 0; i < strlen(String); i++)
         Display->Print(String[i], 0, true);
 }
References Display, i, Video::Display::Print(), and strlen().
ModuleGetHeight()
__UINT32_TYPE__ ModuleGetHeight ()
Definition at line 157 of file module_api.cpp.
 {
     return Display->GetBuffer(0)->Height;
 }
References Display, Video::Display::GetBuffer(), and Video::ScreenBuffer::Height.
ModuleGetWidth()
__UINT32_TYPE__ ModuleGetWidth ()
Definition at line 152 of file module_api.cpp.
 {
     return Display->GetBuffer(0)->Width;
 }
References Display, Video::Display::GetBuffer(), and Video::ScreenBuffer::Width.
Modulememcpy()
void* Modulememcpy (void * Destination, void * Source, __UINT64_TYPE__ Size)
Definition at line 84 of file module_api.cpp.
 {
     SmartLock(ModuleDisplayPrintLock);
     modbg("Copying %ld bytes from %#lx-%#lx to %#lx-%#lx...", Size,
            (__UINT64_TYPE__)Source, (__UINT64_TYPE__)Source + Size,
            (__UINT64_TYPE__)Destination, (__UINT64_TYPE__)Destination + Size);
     return memcpy(Destination, Source, size_t(Size));
 }
References memcpy, modbg, and Size.
Modulememset()
void* Modulememset (void * Destination, int Value, __UINT64_TYPE__ Size)
Definition at line 93 of file module_api.cpp.
 {
     SmartLock(ModuleDisplayPrintLock);
     modbg("Setting value %#x at %#lx-%#lx (%ld bytes)...", Value,
            (__UINT64_TYPE__)Destination,
            (__UINT64_TYPE__)Destination + Size, Size);
     return memset(Destination, Value, size_t(Size));
 }
References memset, modbg, and Size.
ModuleNetReceive()
void ModuleNetReceive (__UINT32_TYPE__ ModuleID, __UINT8_TYPE__ * Data, __UINT16_TYPE__ Size)
Definition at line 111 of file module_api.cpp.
 {
     if (NIManager)
         NIManager->DrvReceive(ModuleID, Data, Size);
 }
References Data, NetworkInterfaceManager::NetworkInterface::DrvReceive(), NIManager, and Size.
ModuleNetSend()
void ModuleNetSend (__UINT32_TYPE__ ModuleID, __UINT8_TYPE__ * Data, __UINT16_TYPE__ Size)
Definition at line 102 of file module_api.cpp.
 {
     // This is useless I guess...
     if (NIManager)
         NIManager->DrvSend(ModuleID, Data, Size);
 }
References Data, NetworkInterfaceManager::NetworkInterface::DrvSend(), NIManager, and Size.
ModulePCIGetDeviceName()
char* ModulePCIGetDeviceName (__UINT32_TYPE__ VendorID, __UINT32_TYPE__ DeviceID)
Definition at line 144 of file module_api.cpp.
 {
     UNUSED(VendorID);
     UNUSED(DeviceID);
     return (char *)"Unknown";
 }
References UNUSED.
ModuleSleep()
void ModuleSleep (__UINT64_TYPE__ Milliseconds)
Definition at line 162 of file module_api.cpp.
 {
     SmartLock(ModuleDisplayPrintLock);
     modbg("Sleeping for %ld milliseconds...", Milliseconds);
     if (TaskManager)
         TaskManager->Sleep(Milliseconds);
     else
         TimeManager->Sleep(size_t(Milliseconds),
                            Time::Units::Milliseconds);
 }
References Time::Milliseconds, modbg, Time::time::Sleep(), Tasking::Task::Sleep(), TaskManager, and TimeManager.
Modulesprintf()
int Modulesprintf (char * Buffer, const char * Format, ...)
Definition at line 173 of file module_api.cpp.
 {
     va_list args;
     va_start(args, Format);
     int ret = vsprintf(Buffer, Format, args);
     va_end(args);
     return ret;
 }
References args, va_end, va_start, and vsprintf().
NewLock()
NewLock (ModuleDisplayPrintLock)
RequestPage()
void* RequestPage (__UINT64_TYPE__ Size)
Definition at line 50 of file module_api.cpp.
 {
     void *ret = KernelAllocator.RequestPages(size_t(Size + 1));
     modbg("Allocated %ld pages (%#lx-%#lx)",
            Size, (__UINT64_TYPE__)ret,
            (__UINT64_TYPE__)ret + FROM_PAGES(Size));
     return ret;
 }
References FROM_PAGES, KernelAllocator, modbg, and Size.
UnmapMemory()
void UnmapMemory (void * VirtualAddress)
Definition at line 76 of file module_api.cpp.
 {
     SmartLock(ModuleDisplayPrintLock);
     modbg("Unmapping %#lx...",
            (__UINT64_TYPE__)VirtualAddress);
     Memory::Virtual(KernelPageTable).Unmap(VirtualAddress);
 }
References KernelPageTable, modbg, and Memory::Virtual::Unmap().
Variable Documentation
KernelAPITemplate
KernelAPI KernelAPITemplate
Definition at line 182 of file module_api.cpp.
Referenced by Module::Module::CallModuleEntryPoint().