Fennix Userspace: Userspace/apps/base/busybox/util-linux/uevent.c File Reference
uevent.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <linux/netlink.h>
Macros
#define env ((char **)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
Enumerations
enum { MAX_ENV = COMMON_BUFSIZE / sizeof(char*) - 1 , KERN_RCVBUF = 128 * 1024 * 1024 , USER_RCVBUF = 16 * 1024 }
Functions
int uevent_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
env
#define env ((char **)bb_common_bufsiz1)
Definition at line 29 of file uevent.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 30 of file uevent.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAX_ENV
KERN_RCVBUF
USER_RCVBUF
Definition at line 31 of file uevent.c.
      {
     MAX_ENV = COMMON_BUFSIZE / sizeof(char*) - 1,
     // ^^^sizeof(env[0]) instead of sizeof(char*)
     // makes gcc-6.3.0 emit "strict-aliasing" warning.
     // socket receive buffer of 2MiB proved to be too small:
     //  http://lists.busybox.net/pipermail/busybox/2019-December/087665.html
     // udevd seems to use a whooping 128MiB.
     // The socket receive buffer size is just a resource limit.
     // The buffers are allocated lazily so the memory is not wasted.
     KERN_RCVBUF = 128 * 1024 * 1024,
     // Might be made smaller: the kernel v5.4 passes up to 32 environment
     // variables with a total of 2kb on each event.
     // On top of that the action string and device path are added.
     USER_RCVBUF = 16 * 1024,
 };
Function Documentation
uevent_main()
int uevent_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 50 of file uevent.c.
 {
     int fd;
     INIT_G();
     argv++;
     // Subscribe for UEVENT kernel messages.
     // Without a sufficiently big RCVBUF, a ton of simultaneous events
     // can trigger ENOBUFS on read, which is unrecoverable.
     // Reproducer:
     //  uevent mdev &
     //  find /sys -name uevent -exec sh -c 'echo add >"{}"' ';'
  reopen:
     fd = create_and_bind_to_netlink(NETLINK_KOBJECT_UEVENT, /*groups:*/ 1 << 0, KERN_RCVBUF);
     for (;;) {
         char *netbuf;
         char *s, *end;
         ssize_t len;
         int idx;
         // In many cases, a system sits for *days* waiting
         // for a new uevent notification to come in.
         // We use a fresh mmap so that buffer is not allocated
         // until kernel actually starts filling it.
         netbuf = xmmap_anon(USER_RCVBUF);
         // Here we block, possibly for a very long time
         len = safe_read(fd, netbuf, USER_RCVBUF - 1);
         if (len < 0) {
             if (errno == ENOBUFS) {
                 // Ran out of socket receive buffer
                 bb_simple_error_msg("uevent overrun");
                 close(fd);
                 munmap(netbuf, USER_RCVBUF);
                 goto reopen;
             }
             bb_simple_perror_msg_and_die("read");
         }
         end = netbuf + len;
         *end = '\0';
         // Each netlink message starts with "ACTION@/path"
         // (which we currently ignore),
         // followed by environment variables.
         if (!argv[0])
             putchar('\n');
         idx = 0;
         s = netbuf;
         while (s < end) {
             if (!argv[0])
                 puts(s);
             if (strchr(s, '=') && idx < MAX_ENV)
                 env[idx++] = s;
             s += strlen(s) + 1;
         }
         env[idx] = NULL;
         if (argv[0]) {
             idx = 0;
             while (env[idx])
                 putenv(env[idx++]);
             spawn_and_wait(argv);
             idx = 0;
             while (env[idx])
                 bb_unsetenv(env[idx++]);
         }
         munmap(netbuf, USER_RCVBUF);
     }
     return 0; // not reached
 }
References argv, bb_simple_error_msg(), bb_simple_perror_msg_and_die(), bb_unsetenv(), close(), create_and_bind_to_netlink(), end, ENOBUFS, env, errno, fd, idx, INIT_G, KERN_RCVBUF, MAX_ENV, munmap(), NULL, putchar, putenv(), puts(), s, safe_read(), spawn_and_wait(), strchr(), strlen(), USER_RCVBUF, and xmmap_anon().