Fennix Userspace: Userspace/musl/src/unistd/isatty.c File Reference
isatty.c File Reference
#include <unistd.h>
#include <errno.h>
#include <sys/ioctl.h>
#include "syscall.h"
Functions
int isatty (int fd)
Function Documentation
isatty()
int isatty (int fd)
Definition at line 6 of file isatty.c.
 {
     struct winsize wsz;
     unsigned long r = syscall(SYS_ioctl, fd, TIOCGWINSZ, &wsz);
     if (r == 0) return 1;
     if (errno != EBADF) errno = ENOTTY;
     return 0;
 }
References EBADF, ENOTTY, errno, fd, syscall(), and TIOCGWINSZ.
Referenced by _rl_input_available(), bb_progress_update(), bbunpack(), check_mount(), cryptpw_main(), fsck_minix_main(), get_cred_or_die(), get_terminal_width_height(), hdparm_main(), hush_main(), I_ConsoleStdout(), initialize_job_control(), isnetconn(), less_main(), login_main(), ls_main(), main(), man_main(), mesg_main(), microcom_main(), more_main(), mv_main(), nohup_main(), open_shell_script(), primary(), procargs(), remove_file(), reset_main(), rl_gather_tyi(), rl_getc(), shell_builtin_read(), ttyname_r(), and unary_test().