Fennix: Userspace/apps/base/busybox/networking/udhcp/signalpipe.c File Reference
signalpipe.c File Reference
#include "common.h"
Macros
#define READ_FD 3
#define WRITE_FD 4
Functions
static void signal_handler (int sig)
void FAST_FUNC udhcp_sp_setup (void)
void FAST_FUNC udhcp_sp_fd_set (struct pollfd *pfds, int extra_fd)
int FAST_FUNC udhcp_sp_read (void)
Macro Definition Documentation
READ_FD
#define READ_FD 3
Definition at line 23 of file signalpipe.c.
WRITE_FD
#define WRITE_FD 4
Definition at line 24 of file signalpipe.c.
Function Documentation
signal_handler()
static void signal_handler (int sig) static
Definition at line 26 of file signalpipe.c.
 {
     int sv = errno;
     unsigned char ch = sig; /* use char, avoid dealing with partial writes */
     if (write(WRITE_FD, &ch, 1) != 1)
         bb_simple_perror_msg("can't send signal");
     errno = sv;
 }
References bb_simple_perror_msg(), errno, sv, write(), and WRITE_FD.
Referenced by udhcp_sp_setup().
udhcp_sp_fd_set()
void FAST_FUNC udhcp_sp_fd_set (struct pollfd * pfds, int extra_fd)
Definition at line 68 of file signalpipe.c.
 {
     pfds[0].fd = READ_FD;
     pfds[0].events = POLLIN;
     pfds[1].fd = -1;
     if (extra_fd >= 0) {
         close_on_exec_on(extra_fd);
         pfds[1].fd = extra_fd;
         pfds[1].events = POLLIN;
     }
     /* this simplifies "is extra_fd ready?" tests elsewhere: */
     pfds[1].revents = 0;
 }
References close_on_exec_on(), pollfd::events, pollfd::fd, POLLIN, READ_FD, and pollfd::revents.
Referenced by udhcpc6_main(), udhcpc_main(), and udhcpd_main().
udhcp_sp_read()
int FAST_FUNC udhcp_sp_read (void)
Definition at line 85 of file signalpipe.c.
 {
     unsigned char sig;
     /* Can't block here, fd is in nonblocking mode */
     if (safe_read(READ_FD, &sig, 1) != 1)
         return 0;
     return sig;
 }
References READ_FD, and safe_read().
Referenced by udhcpc6_main(), udhcpc_main(), and udhcpd_main().
udhcp_sp_setup()
void FAST_FUNC udhcp_sp_setup (void)
Definition at line 37 of file signalpipe.c.
 {
     struct fd_pair signal_pipe;
     /* All callers also want this, so... */
     bb_sanitize_stdio();
     /* was socketpair, but it needs AF_UNIX in kernel */
     xpiped_pair(signal_pipe);
     /* usually we get fds 3 and 4, but if we get higher ones... */
     if (signal_pipe.rd != READ_FD)
         xmove_fd(signal_pipe.rd, READ_FD);
     if (signal_pipe.wr != WRITE_FD)
         xmove_fd(signal_pipe.wr, WRITE_FD);
     close_on_exec_on(READ_FD);
     close_on_exec_on(WRITE_FD);
     ndelay_on(READ_FD);
     ndelay_on(WRITE_FD);
     bb_signals(0
         + (1 << SIGUSR1)
         + (1 << SIGUSR2)
         + (1 << SIGTERM)
         , signal_handler);
 }
References bb_sanitize_stdio(), bb_signals(), close_on_exec_on(), ndelay_on(), fd_pair::rd, READ_FD, signal_handler(), SIGTERM, SIGUSR1, SIGUSR2, fd_pair::wr, WRITE_FD, xmove_fd(), and xpiped_pair.
Referenced by udhcpc6_main(), udhcpc_main(), and udhcpd_main().