Fennix: Userspace/libc/include/stdio.h File Reference
stdio.h File Reference
#include <stdarg.h>
#include <stddef.h>
Data Structures
struct FILE
Macros
#define SEEK_SET 0
Functions
int fclose (FILE *stream)
int fflush (FILE *stream)
FILE * fopen (const char *filename, const char *mode)
int fprintf (FILE *stream, const char *format,...)
int printf (const char *format,...)
size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
int fseek (FILE *stream, long offset, int whence)
long ftell (FILE *stream)
size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
void setbuf (FILE *stream, char *buf)
int vfprintf (FILE *stream, const char *format, va_list arg)
int puts (const char *s)
int putchar (int c)
Variables
FILE * stdin
FILE * stdout
FILE * stderr
Data Structure Documentation
FILE
struct FILE
Definition at line 9 of file stdio.h.
Data Fields
int unused
Macro Definition Documentation
SEEK_SET
#define SEEK_SET 0
Definition at line 7 of file stdio.h.
Function Documentation
fclose()
int fclose (FILE * stream)
Definition at line 8 of file io.c.
 {
     return 0;
 }
fflush()
int fflush (FILE * stream)
Definition at line 13 of file io.c.
 {
     return 0;
 }
fopen()
FILE* fopen (const char * filename, const char * mode)
Definition at line 18 of file io.c.
 {
     return 0;
 }
fprintf()
int fprintf (FILE * stream, const char * format, ...)
Definition at line 10 of file KConfig.cpp.
 {
     va_list args;
     va_start(args, Format);
     vprintf_(Format, args);
     va_end(args);
 }
References va_end, va_start, and vprintf_().
Referenced by cag_option_print(), cag_option_print_letters(), cag_option_print_name(), and cag_option_print_value().
fread()
size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 33 of file io.c.
 {
     return 0;
 }
fseek()
int fseek (FILE * stream, long offset, int whence)
Definition at line 38 of file io.c.
 {
     return 0;
 }
ftell()
long ftell (FILE * stream)
Definition at line 43 of file io.c.
 {
     return 0;
 }
fwrite()
size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 48 of file io.c.
 {
     return 0;
 }
printf()
int printf (const char * format, ...)
An implementation of the C standard's printf/vprintf
Note
you must implement a putchar_ function for using this function - it invokes putchar_ rather than directly performing any I/O (which insulates it from any dependence on the operating system and external libraries).
Parameters
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each %-specifier in format string
Returns
The number of characters written into s, not counting the terminating null character
Definition at line 53 of file Lynx.c.
 {
     va_list args;
     va_start(args, format);
     printf_(format, args);
     va_end(args);
 }
References Execute::ret, va_end, va_start, and vprintf().
putchar()
int putchar (int c)
Definition at line 67 of file io.c.
 {
     return 0;
 }
puts()
int puts (const char * s)
Definition at line 62 of file io.c.
 {
     return 0;
 }
setbuf()
void setbuf (FILE * stream, char * buf)
Definition at line 53 of file io.c.
 {
 }
vfprintf()
int vfprintf (FILE * stream, const char * format, va_list arg)
Variable Documentation
stderr
FILE* stderr extern
Definition at line 6 of file io.c.
stdin
FILE* stdin extern
Definition at line 4 of file io.c.
stdout
FILE* stdout extern
Definition at line 5 of file io.c.