Fennix: mlibc Namespace Reference
mlibc Namespace Reference
Namespaces
anonymous_namespace{file-io.cpp}
anonymous_namespace{lookup.cpp}
anonymous_namespace{pthread-stubs.cpp}
Data Structures
struct locale_description
struct abstract_file
struct fd_file
struct exec_stack_data
struct utf8_charcode
struct polymorphic_charcode_adapter
struct GlobalConfigGuard
struct bit_util
struct bit_util< uint64_t >
struct bit_util< uint32_t >
struct bit_util< uint16_t >
struct code_seq
struct polymorphic_charcode
struct wide_charcode
struct charset
struct InfoSink
struct PanicSink
struct GlobalConfig
struct int_limits
struct int_limits< long >
struct int_limits< unsigned long >
struct int_limits< long long >
struct int_limits< unsigned long long >
struct char_detail
struct char_detail< char >
struct char_detail< wchar_t >
struct dns_addr_buf
struct lookup_result
struct dns_header
struct ai_buf
struct mem_file
struct nameserver_data
struct service_buf
struct RtdlConfig
struct aero_dir_entry
struct lemon_stat_t
struct lemon_dirent
struct ReadDirState
Typedefs
typedef uint32_t codepoint
using service_result = frg::small_vector< service_buf, SERV_MAX, MemoryAllocator >
typedef struct mlibc::lemon_dirent lemon_dirent_t
Enumerations
enum class stream_type { unknown , file_like , pipe_like }
enum class buffer_mode { unknown , no_buffer , line_buffer , full_buffer }
enum class charcode_error {
null , dirty , illegal_input , input_underflow ,
output_overflow
}
enum class fsfd_target { none , path , fd , fd_path }
enum class sc_result_t : sc_word_t
Functions
int putenv (char *string)
const locale_description * query_locale_description (const char *name)
void sys_exit (int status)
void sys_thread_exit ()
int sys_open (const char *pathname, int flags, mode_t mode, int *fd)
int sys_flock (int fd, int options)
int sys_open_dir (const char *path, int *handle)
int sys_read_entries (int handle, void *buffer, size_t max_size, size_t *bytes_read)
int sys_read (int fd, void *buf, size_t count, ssize_t *bytes_read)
int sys_write (int fd, const void *buf, size_t count, ssize_t *bytes_written)
int sys_pread (int fd, void *buf, size_t n, off_t off, ssize_t *bytes_read)
int sys_seek (int fd, off_t offset, int whence, off_t *new_offset)
int sys_close (int fd)
int sys_clock_get (int clock, time_t *secs, long *nanos)
int sys_clock_getres (int clock, time_t *secs, long *nanos)
int sys_sleep (time_t *secs, long *nanos)
int sys_isatty (int fd)
int sys_rmdir (const char *path)
int sys_unlinkat (int dirfd, const char *path, int flags)
int sys_rename (const char *path, const char *new_path)
int sys_renameat (int olddirfd, const char *old_path, int newdirfd, const char *new_path)
int sys_sigprocmask (int how, const sigset_t *__restrict set, sigset_t *__restrict retrieve)
int sys_sigaction (int, const struct sigaction *__restrict, struct sigaction *__restrict)
int sys_fork (pid_t *child)
int sys_waitpid (pid_t pid, int *status, int flags, struct rusage *ru, pid_t *ret_pid)
int sys_execve (const char *path, char *const argv[], char *const envp[])
pid_t sys_getpid ()
int sys_kill (int, int)
template<typename T >
void file_dispose_cb (abstract_file *base)
void parse_exec_stack (void *opaque_sp, exec_stack_data *data)
void set_startup_data (int argc, char **argv, char **envp)
int sys_ioctl (int fd, unsigned long request, void *arg, int *result)
int sys_tgkill (int tgid, int tid, int sig)
Tcb * get_current_tcb ()
uintptr_t get_sp ()
void initStackGuard (void *entropy)
polymorphic_charcode * current_charcode ()
wide_charcode * platform_wide_charcode ()
charset * current_charset ()
static bool envEnabled (const char *env)
char * nl_langinfo (nl_item item)
int strncasecmp (const char *a, const char *b, size_t size)
bool generic_is_control (codepoint c)
const GlobalConfig & globalConfig ()
void sys_libc_log (const char *message)
void sys_libc_panic ()
int sys_tcb_set (void *pointer)
int sys_futex_tid ()
int sys_futex_wait (int *pointer, int expected, const struct timespec *time)
int sys_futex_wake (int *pointer)
int sys_anon_allocate (size_t size, void **pointer)
int sys_anon_free (void *pointer, size_t size)
int sys_stat (fsfd_target fsfdt, int fd, const char *path, int flags, struct stat *statbuf)
int sys_vm_map (void *hint, size_t size, int prot, int flags, int fd, off_t offset, void **window)
int sys_vm_unmap (void *pointer, size_t size)
int sys_vm_protect (void *pointer, size_t size, int prot)
template<typename T >
T strtofp (const char *str, char **endptr)
template<typename Char >
Char widen (char c)
template<typename Return , typename Char >
Return stringToInteger (const Char *__restrict nptr, Char **__restrict endptr, int baseInt)
static constexpr bool tcb_async_cancelled (int value)
static constexpr bool tcb_async_cancel (int value)
static constexpr bool tcb_cancel_enabled (int value)
static constexpr bool tcb_cancelled (int value)
unsigned int this_tid ()
int sys_dup2 (int fd, int flags, int newfd)
int sys_inotify_create (int flags, int *fd)
int sys_inotify_add_watch (int ifd, const char *path, uint32_t mask, int *wd)
int sys_inotify_rm_watch (int ifd, int wd)
int sys_epoll_create (int flags, int *fd)
int sys_epoll_ctl (int epfd, int mode, int fd, struct epoll_event *ev)
int sys_epoll_pwait (int epfd, struct epoll_event *ev, int n, int timeout, const sigset_t *sigmask, int *raised)
int sys_mount (const char *source, const char *target, const char *fstype, unsigned long flags, const void *data)
int sys_umount2 (const char *target, int flags)
int sys_eventfd_create (unsigned int initval, int flags, int *fd)
int sys_timerfd_create (int clockid, int flags, int *fd)
int sys_timerfd_settime (int fd, int flags, const struct itimerspec *value, struct itimerspec *oldvalue)
int sys_signalfd_create (const sigset_t *, int flags, int *fd)
int sys_reboot (int cmd)
int sys_ptrace (long req, pid_t pid, void *addr, void *data, long *out)
int sys_prctl (int option, va_list va, int *out)
int sys_init_module (void *module, unsigned long length, const char *args)
int sys_delete_module (const char *name, unsigned flags)
int sys_klogctl (int type, char *bufp, int len, int *out)
int sys_getcpu (int *cpu)
int sys_sysinfo (struct sysinfo *info)
int sys_setxattr (const char *path, const char *name, const void *val, size_t size, int flags)
int sys_lsetxattr (const char *path, const char *name, const void *val, size_t size, int flags)
int sys_fsetxattr (int fd, const char *name, const void *val, size_t size, int flags)
int sys_getxattr (const char *path, const char *name, void *val, size_t size, ssize_t *nread)
int sys_lgetxattr (const char *path, const char *name, void *val, size_t size, ssize_t *nread)
int sys_fgetxattr (int fd, const char *name, void *val, size_t size, ssize_t *nread)
int sys_listxattr (const char *path, char *list, size_t size, ssize_t *nread)
int sys_llistxattr (const char *path, char *list, size_t size, ssize_t *nread)
int sys_flistxattr (int fd, char *list, size_t size, ssize_t *nread)
int sys_removexattr (const char *path, const char *name)
int sys_lremovexattr (const char *path, const char *name)
int sys_fremovexattr (int fd, const char *name)
static frg::string< MemoryAllocator > read_dns_name (char *buf, char *&it)
int lookup_name_dns (struct lookup_result &buf, const char *name, frg::string< MemoryAllocator > &canon_name)
int lookup_addr_dns (frg::span< char > name, frg::array< uint8_t, 16 > &addr, int family)
int lookup_name_hosts (struct lookup_result &buf, const char *name, frg::string< MemoryAllocator > &canon_name)
int lookup_addr_hosts (frg::span< char > name, frg::array< uint8_t, 16 > &addr, int family)
int lookup_name_null (struct lookup_result &buf, int flags, int family)
int lookup_name_ip (struct lookup_result &buf, const char *name, int family)
frg::optional< struct nameserver_data > get_nameserver ()
static int parse_rest (service_buf &buf, char *end, int proto)
static int lookup_serv_file_port (service_result &buf, int proto, int port)
static int lookup_serv_file_name (service_result &buf, const char *name, int proto)
int lookup_serv_by_name (service_result &buf, const char *name, int proto, int socktype, int flags)
int lookup_serv_by_port (service_result &buf, int proto, int port)
int sys_readv (int fd, const struct iovec *iovs, int iovc, ssize_t *bytes_read)
int sys_pwrite (int fd, const void *buf, size_t n, off_t off, ssize_t *bytes_read)
int sys_access (const char *path, int mode)
int sys_faccessat (int dirfd, const char *pathname, int mode, int flags)
int sys_dup (int fd, int flags, int *newfd)
int sys_statvfs (const char *path, struct statvfs *out)
int sys_fstatvfs (int fd, struct statvfs *out)
int sys_readlink (const char *path, void *buffer, size_t max_size, ssize_t *length)
int sys_ftruncate (int fd, size_t size)
int sys_fallocate (int fd, off_t offset, size_t size)
int sys_openat (int dirfd, const char *path, int flags, mode_t mode, int *fd)
int sys_socket (int family, int type, int protocol, int *fd)
int sys_msg_send (int fd, const struct msghdr *hdr, int flags, ssize_t *length)
int sys_msg_recv (int fd, struct msghdr *hdr, int flags, ssize_t *length)
int sys_listen (int fd, int backlog)
gid_t sys_getgid ()
gid_t sys_getegid ()
uid_t sys_getuid ()
uid_t sys_geteuid ()
pid_t sys_gettid ()
pid_t sys_getppid ()
pid_t sys_getpgid (pid_t pid, pid_t *pgid)
pid_t sys_getsid (pid_t pid, pid_t *sid)
int sys_setpgid (pid_t pid, pid_t pgid)
int sys_setuid (uid_t uid)
int sys_seteuid (uid_t euid)
int sys_setgid (gid_t gid)
int sys_setegid (gid_t egid)
int sys_getgroups (size_t size, const gid_t *list, int *ret)
void sys_yield ()
int sys_getaffinity (pid_t pid, size_t cpusetsize, cpu_set_t *mask)
int sys_clone (void *tcb, pid_t *pid_out, void *stack)
int sys_prepare_stack (void **stack, void *entry, void *user_arg, void *tcb, size_t *stack_size, size_t *guard_size)
int sys_pselect (int num_fds, fd_set *read_set, fd_set *write_set, fd_set *except_set, const struct timespec *timeout, const sigset_t *sigmask, int *num_events)
int sys_getrusage (int scope, struct rusage *usage)
int sys_getrlimit (int resource, struct rlimit *limit)
int sys_setrlimit (int resource, const struct rlimit *limit)
int sys_getpriority (int which, id_t who, int *value)
int sys_setpriority (int which, id_t who, int prio)
int sys_getschedparam (void *tcb, int *policy, struct sched_param *param)
int sys_setschedparam (void *tcb, int policy, const struct sched_param *param)
int sys_get_min_priority (int policy, int *out)
int sys_getcwd (char *buffer, size_t size)
int sys_chdir (const char *path)
int sys_fchdir (int fd)
int sys_chroot (const char *path)
int sys_mkdir (const char *path, mode_t mode)
int sys_mkdirat (int dirfd, const char *path, mode_t mode)
int sys_link (const char *old_path, const char *new_path)
int sys_linkat (int olddirfd, const char *old_path, int newdirfd, const char *new_path, int flags)
int sys_symlink (const char *target_path, const char *link_path)
int sys_symlinkat (const char *target_path, int dirfd, const char *link_path)
int sys_fcntl (int fd, int request, va_list args, int *result)
int sys_ttyname (int fd, char *buf, size_t size)
int sys_fadvise (int fd, off_t offset, off_t length, int advice)
void sys_sync ()
int sys_fsync (int fd)
int sys_fdatasync (int fd)
int sys_chmod (const char *pathname, mode_t mode)
int sys_fchmod (int fd, mode_t mode)
int sys_fchmodat (int fd, const char *pathname, mode_t mode, int flags)
int sys_utimensat (int dirfd, const char *pathname, const struct timespec times[2], int flags)
int sys_mlockall (int flags)
int sys_mlock (const void *addr, size_t len)
int sys_vm_remap (void *pointer, size_t size, size_t new_size, void **window)
int sys_setsid (pid_t *sid)
int sys_tcgetattr (int fd, struct termios *attr)
int sys_tcsetattr (int, int, const struct termios *attr)
int sys_tcflow (int, int)
int sys_tcflush (int, int)
int sys_tcdrain (int)
int sys_pipe (int *fds, int flags)
int sys_socketpair (int domain, int type_and_flags, int proto, int *fds)
int sys_poll (struct pollfd *fds, nfds_t count, int timeout, int *num_events)
int sys_getsockopt (int fd, int layer, int number, void *__restrict buffer, socklen_t *__restrict size)
int sys_setsockopt (int fd, int layer, int number, const void *buffer, socklen_t size)
int sys_sigtimedwait (const sigset_t *__restrict set, siginfo_t *__restrict info, const struct timespec *__restrict timeout, int *out_signal)
int sys_accept (int fd, int *newfd, struct sockaddr *addr_ptr, socklen_t *addr_length)
int sys_bind (int fd, const struct sockaddr *addr_ptr, socklen_t addr_length)
int sys_connect (int fd, const struct sockaddr *addr_ptr, socklen_t addr_length)
int sys_sockname (int fd, struct sockaddr *addr_ptr, socklen_t max_addr_length, socklen_t *actual_length)
int sys_peername (int fd, struct sockaddr *addr_ptr, socklen_t max_addr_length, socklen_t *actual_length)
int sys_gethostname (char *buffer, size_t bufsize)
int sys_sethostname (const char *buffer, size_t bufsize)
int sys_mkfifoat (int dirfd, const char *path, int mode)
int sys_getentropy (void *buffer, size_t length)
int sys_mknodat (int dirfd, const char *path, int mode, int dev)
int sys_umask (mode_t mode, mode_t *old)
int sys_before_cancellable_syscall (ucontext_t *uctx)
int sys_fchownat (int dirfd, const char *pathname, uid_t owner, gid_t group, int flags)
int sys_sigaltstack (const stack_t *ss, stack_t *oss)
int sys_sigsuspend (const sigset_t *set)
int sys_setgroups (size_t size, const gid_t *list)
int sys_statfs (const char *path, struct statfs *buf)
int sys_fstatfs (int fd, struct statfs *buf)
int sys_memfd_create (const char *name, int flags, int *fd)
int sys_madvise (void *addr, size_t length, int advice)
int sys_msync (void *addr, size_t length, int flags)
int sys_getitimer (int which, struct itimerval *curr_value)
int sys_setitimer (int which, const struct itimerval *new_value, struct itimerval *old_value)
int sys_timer_create (clockid_t clk, struct sigevent *__restrict evp, timer_t *__restrict res)
int sys_timer_settime (timer_t t, int flags, const struct itimerspec *__restrict val, struct itimerspec *__restrict old)
int sys_timer_delete (timer_t t)
int sys_times (struct tms *tms, clock_t *out)
int sys_uname (struct utsname *buf)
int sys_pause ()
int sys_setresuid (uid_t ruid, uid_t euid, uid_t suid)
int sys_setresgid (gid_t rgid, gid_t egid, gid_t sgid)
int sys_setreuid (uid_t ruid, uid_t euid)
int sys_setregid (gid_t rgid, gid_t egid)
int sys_if_indextoname (unsigned int index, char *name)
int sys_if_nametoindex (const char *name, unsigned int *ret)
int sys_ptsname (int fd, char *buffer, size_t length)
int sys_unlockpt (int fd)
const RtdlConfig & rtdlConfig ()
int sys_vm_readahead (void *pointer, size_t size)
if (result< 0)
int void size_t off_t ssize_t *bytes_read UNIMPLEMENTED ("sys_pread") int sys_seek(int fd
struct mlibc::aero_dir_entry __attribute__ ((packed))
int sys_ppoll (struct pollfd *fds, int nfds, const struct timespec *timeout, const sigset_t *sigmask, int *num_events)
int sys_sigaction (int how, const struct sigaction *__restrict action, struct sigaction *__restrict old_action)
int prepare_stack (void **stack, void *entry, void *user_arg, void *tcb, size_t *stack_size, size_t *guard_size)
void * prepare_stack (void *entry, void *user_arg, void *tcb)
int sys_getcwd (const char *buff, size_t size)
int sys_sched_yield (void)
sc_word_t do_nargs_syscall (int sc)
sc_word_t do_nargs_syscall (int sc, sc_word_t arg1)
sc_word_t do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2)
sc_word_t do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3)
sc_word_t do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4)
sc_word_t do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5)
sc_word_t do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5, sc_word_t arg6)
sc_word_t do_nargs_cp_syscall (int sc, sc_word_t arg1)
sc_word_t do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2)
sc_word_t do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3)
sc_word_t do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4)
sc_word_t do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5)
sc_word_t do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5, sc_word_t arg6)
sc_word_t sc_cast (long x)
sc_word_t sc_cast (const void *x)
template<typename... T>
sc_result_t do_syscall (int sc, T... args)
int sc_error (sc_result_t ret)
template<typename... T>
sc_result_t do_cp_syscall (int sc, T... args)
template<typename T >
T sc_int_result (sc_result_t ret)
template<typename T >
T * sc_ptr_result (sc_result_t ret)
void __mlibc_signal_restore (void)
int sys_getrandom (void *buffer, size_t length, int flags, ssize_t *bytes_written)
void * prepare_stack (void *entry, void *user_arg)
int sys_sigentry (void *sigentry)
int sys_sigreturn (void *context, sigset_t old_mask)
void __mlibc_thread_entry ()
if (int r=sys_ioctl(fd, TCGETS, attr, &ret) !=0)
if (fds==NULL)
for (int i=0;i< nfds;i++)
if (ret !=0)
free (fds)
if (read_set)
if (write_set)
if (except_set)
int sys_timerfd_create (int, int *) STUB_ONLY int sys_ioctl(int fd
if ((int) ret.ret==-1) return ret.errno
static ReadDirState * get_dir_state (int fdnum)
if (ret_value==MAP_FAILED)
int sys_sigprocmask (int, const sigset_t *__restrict, sigset_t *__restrict)
int sys_signalfd_create (sigset_t, int, int *) STUB_ONLY int sys_waitpid(pid_t pid
int ioctl_drm (int fd, unsigned long request, void *arg, int *result, HelHandle handle)
int sys_mkfifoat (int dirfd, const char *path, mode_t mode)
Variables
constinit const locale_description c_locale
constinit const locale_description posix_locale
const locale_description * collate_facet
const locale_description * ctype_facet
const locale_description * monetary_facet
const locale_description * numeric_facet
const locale_description * time_facet
const locale_description * messages_facet
constexpr size_t page_size = 0x1000
frg::stack_buffer_logger< InfoSink, 512 > infoLogger
frg::stack_buffer_logger< PanicSink, 512 > panicLogger
GlobalConfigGuard guard
constexpr bool tcb_available_flag = true
void int * status
void int int flags
void int int struct rusage * ru
void int int struct rusage pid_t * ret_pid
return
int void * buf
int void size_t count
int void size_t off_t off
int void size_t off_t ssize_t *bytes_read off_t offset
int void size_t off_t ssize_t *bytes_read off_t int whence
int void size_t off_t ssize_t *bytes_read off_t int off_t * new_offset
int const char * destpath
static constexpr size_t default_stacksize = 0x1000000
static constexpr size_t default_stacksize = 0x200000
static constexpr size_t default_stacksize = 0x200000
static constexpr size_t default_stacksize = 0x200000
int struct termios * attr
int int *STUB_ONLY int fd_set * read_set
int int *STUB_ONLY int fd_set fd_set * write_set
int int *STUB_ONLY int fd_set fd_set fd_set * except_set
int int *STUB_ONLY int fd_set fd_set fd_set const struct timespec * timeout
int int *STUB_ONLY int fd_set fd_set fd_set const struct timespec const sigset_t * sigmask
int int *STUB_ONLY int fd_set fd_set fd_set const struct timespec const sigset_t int * num_events
int ret = sys_ppoll(fds, nfds, timeout, sigmask, num_events)
fd_set res_read_set
fd_set res_write_set
fd_set res_except_set
int unsigned long request
int unsigned long void * arg
int unsigned long void int * result
static frg::hash_map< int, ReadDirState *, frg::hash< int >, MemoryAllocator > open_dirs {frg::hash<int>{}, getAllocator()}
int size_t size
int size_t int prot
int size_t int int int fd
int size_t int int int off_t void ** window
void * ret_value = (void *)ret.ret
int long * nanos
struct timespec rem = {.tv_sec = 0, .tv_nsec = 0}
* secs = rem.tv_sec
static constexpr size_t default_stacksize = 0x200000
static constexpr size_t default_stacksize = 0x200000
Data Structure Documentation
mlibc::locale_description
struct mlibc::locale_description
Definition at line 42 of file locale-stubs.cpp.
Data Fields
lconv lc
const char * name
mlibc::exec_stack_data
struct mlibc::exec_stack_data
Definition at line 8 of file startup.h.
Data Fields
int argc
char ** argv
char ** envp
mlibc::bit_util
struct mlibc::bit_util
template<typename T>
struct mlibc::bit_util< T >
Definition at line 9 of file bitutil.hpp.
mlibc::int_limits
struct mlibc::int_limits
template<typename T>
struct mlibc::int_limits< T >
Definition at line 11 of file strtol.hpp.
mlibc::char_detail
struct mlibc::char_detail
template<typename T>
struct mlibc::char_detail< T >
Definition at line 37 of file strtol.hpp.
mlibc::dns_header
struct mlibc::dns_header
Definition at line 30 of file lookup.hpp.
Data Fields
uint16_t flags
uint16_t identification
uint16_t no_additional
uint16_t no_ans
uint16_t no_auths
uint16_t no_q
mlibc::ai_buf
struct mlibc::ai_buf
Definition at line 39 of file lookup.hpp.
Data Fields
struct addrinfo ai
union sa sa
mlibc::RtdlConfig
struct mlibc::RtdlConfig
Definition at line 6 of file rtdl-config.hpp.
Data Fields
bool secureRequired
mlibc::aero_dir_entry
struct mlibc::aero_dir_entry
Definition at line 204 of file filesystem.cpp.
Data Fields
size_t filetyp
size_t inode
char name[]
size_t offset
size_t reclen
mlibc::lemon_stat_t
struct mlibc::lemon_stat_t
Definition at line 18 of file filesystem.cpp.
Data Fields
int64_t st_blksize
int64_t st_blocks
dev_t st_dev
uid_t st_gid
ino_t st_ino
mode_t st_mode
nlink_t st_nlink
dev_t st_rdev
off_t st_size
uid_t st_uid
mlibc::lemon_dirent
struct mlibc::lemon_dirent
Definition at line 241 of file filesystem.cpp.
Data Fields
uint32_t inode
char name[NAME_MAX]
uint32_t type
mlibc::ReadDirState
struct mlibc::ReadDirState
Definition at line 271 of file generic.cpp.
Data Fields
void * buffer
size_t capacity
size_t offset
Typedef Documentation
codepoint
typedef uint32_t mlibc::codepoint
Definition at line 35 of file charcode.hpp.
lemon_dirent_t
typedef struct mlibc::lemon_dirent mlibc::lemon_dirent_t
service_result
using mlibc::service_result = typedef frg::small_vector<service_buf, SERV_MAX, MemoryAllocator>
Definition at line 23 of file services.hpp.
Enumeration Type Documentation
buffer_mode
enum mlibc::buffer_mode strong
Enumerator
unknown
no_buffer
line_buffer
full_buffer
Definition at line 18 of file file-io.hpp.
{
     unknown,
     no_buffer,
     line_buffer,
     full_buffer
 };
charcode_error
enum mlibc::charcode_error strong
Enumerator
null
dirty
illegal_input
input_underflow
output_overflow
Definition at line 12 of file charcode.hpp.
{
     null,
     dirty,
     illegal_input,
     input_underflow,
     output_overflow
 };
fsfd_target
enum mlibc::fsfd_target strong
Enumerator
none
path
fd
fd_path
Definition at line 6 of file fsfd_target.hpp.
{
     none,
     path,
     fd,
     fd_path
 };
sc_result_t
enum mlibc::sc_result_t : sc_word_t strong
Definition at line 72 of file cxx-syscall.hpp.
 : sc_word_t { };
stream_type
enum mlibc::stream_type strong
Enumerator
unknown
file_like
pipe_like
Definition at line 12 of file file-io.hpp.
{
     unknown,
     file_like,
     pipe_like
 };
Function Documentation
__attribute__()
struct mlibc::aero_dir_entry mlibc::__attribute__ ((packed))
References fd, flags, path, result, strlen(), SYS_UNLINK, and syscall.
__mlibc_signal_restore()
void mlibc::__mlibc_signal_restore (void)
Referenced by sys_sigaction().
__mlibc_thread_entry()
void mlibc::__mlibc_thread_entry ()
current_charcode()
polymorphic_charcode * mlibc::current_charcode ()
Definition at line 227 of file charcode.cpp.
{
     static polymorphic_charcode_adapter<utf8_charcode> global_charcode;
     return &global_charcode;
 }
Referenced by btowc(), isalnum(), isalpha(), isascii(), isblank(), iscntrl(), isdigit(), isgraph(), islower(), isprint(), ispunct(), isspace(), isupper(), isxdigit(), mblen(), mbrlen(), mbrtowc(), mbsnrtowcs(), mbsrtowcs(), mbstowcs(), mbtowc(), tolower(), toupper(), wcrtomb(), wcsnrtombs(), and wcsrtombs().
current_charset()
charset * mlibc::current_charset ()
Definition at line 138 of file charset.cpp.
{
     static charset global_charset;
     return &global_charset;
 }
Referenced by isalnum(), isalpha(), isblank(), isdigit(), isgraph(), islower(), isprint(), ispunct(), isspace(), isupper(), iswalnum(), iswalpha(), iswblank(), iswdigit(), iswgraph(), iswlower(), iswprint(), iswpunct(), iswspace(), iswupper(), iswxdigit(), isxdigit(), tolower(), toupper(), towlower(), and towupper().
do_cp_syscall()
template<typename... T> sc_result_t mlibc::do_cp_syscall (int sc, T... args)
Definition at line 91 of file cxx-syscall.hpp.
{
 #if __MLIBC_POSIX_OPTION && !MLIBC_BUILDING_RTDL
         auto result = static_cast<sc_result_t>(do_nargs_cp_syscall(sc, sc_cast(args)...));
         if (int e = sc_error(result); e) {
             auto tcb = reinterpret_cast<Tcb*>(get_current_tcb());
             if (tcb_cancelled(tcb->cancelBits) && e == EINTR) {
                 __mlibc_do_cancel();
                 __builtin_unreachable();
             }
         }
         return result;
 #else
         return do_syscall(sc, std::forward<T>(args)...);
 #endif // __MLIBC_POSIX_OPTION || !MLIBC_BUILDING_RTDL
     }
References __mlibc_do_cancel(), do_nargs_cp_syscall(), do_syscall(), EINTR, get_current_tcb(), result, sc_cast(), sc_error(), and tcb_cancelled().
Referenced by sys_fchmod(), sys_fchmodat(), sys_fchownat(), sys_fstatfs(), sys_readv(), sys_statfs(), and sys_utimensat().
do_nargs_cp_syscall() [1/6]
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1) inline
Definition at line 48 of file cxx-syscall.hpp.
{
         return __mlibc_do_asm_cp_syscall(sc, arg1, 0, 0, 0, 0, 0);
     }
References __mlibc_do_asm_cp_syscall(), and arg1.
Referenced by do_cp_syscall().
do_nargs_cp_syscall() [2/6]
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2) inline
Definition at line 51 of file cxx-syscall.hpp.
{
         return __mlibc_do_asm_cp_syscall(sc, arg1, arg2, 0, 0, 0, 0);
     }
References __mlibc_do_asm_cp_syscall(), arg1, and arg2.
do_nargs_cp_syscall() [3/6]
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3) inline
Definition at line 54 of file cxx-syscall.hpp.
{
         return __mlibc_do_asm_cp_syscall(sc, arg1, arg2, arg3, 0, 0, 0);
     }
References __mlibc_do_asm_cp_syscall(), arg1, arg2, and arg3.
do_nargs_cp_syscall() [4/6]
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4) inline
Definition at line 58 of file cxx-syscall.hpp.
{
         return __mlibc_do_asm_cp_syscall(sc, arg1, arg2, arg3, arg4, 0, 0);
     }
References __mlibc_do_asm_cp_syscall(), arg1, arg2, arg3, and arg4.
do_nargs_cp_syscall() [5/6]
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5) inline
Definition at line 62 of file cxx-syscall.hpp.
{
         return __mlibc_do_asm_cp_syscall(sc, arg1, arg2, arg3, arg4, arg5, 0);
     }
References __mlibc_do_asm_cp_syscall(), arg1, arg2, arg3, arg4, and arg5.
do_nargs_cp_syscall() [6/6]
sc_word_t mlibc::do_nargs_cp_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5, sc_word_t arg6) inline
Definition at line 66 of file cxx-syscall.hpp.
{
         return __mlibc_do_asm_cp_syscall(sc, arg1, arg2, arg3, arg4, arg5, arg6);
     }
References __mlibc_do_asm_cp_syscall(), arg1, arg2, arg3, arg4, and arg5.
do_nargs_syscall() [1/7]
sc_word_t mlibc::do_nargs_syscall (int sc) inline
Definition at line 23 of file cxx-syscall.hpp.
{
         return __do_syscall0(sc);
     }
References __do_syscall0().
Referenced by do_syscall().
do_nargs_syscall() [2/7]
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1) inline
Definition at line 26 of file cxx-syscall.hpp.
{
         return __do_syscall1(sc, arg1);
     }
References __do_syscall1(), and arg1.
do_nargs_syscall() [3/7]
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2) inline
Definition at line 29 of file cxx-syscall.hpp.
{
         return __do_syscall2(sc, arg1, arg2);
     }
References __do_syscall2(), arg1, and arg2.
do_nargs_syscall() [4/7]
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3) inline
Definition at line 32 of file cxx-syscall.hpp.
{
         return __do_syscall3(sc, arg1, arg2, arg3);
     }
References __do_syscall3(), arg1, arg2, and arg3.
do_nargs_syscall() [5/7]
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4) inline
Definition at line 35 of file cxx-syscall.hpp.
{
         return __do_syscall4(sc, arg1, arg2, arg3, arg4);
     }
References __do_syscall4(), arg1, arg2, arg3, and arg4.
do_nargs_syscall() [6/7]
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5) inline
Definition at line 39 of file cxx-syscall.hpp.
{
         return __do_syscall5(sc, arg1, arg2, arg3, arg4, arg5);
     }
References __do_syscall5(), arg1, arg2, arg3, arg4, and arg5.
do_nargs_syscall() [7/7]
sc_word_t mlibc::do_nargs_syscall (int sc, sc_word_t arg1, sc_word_t arg2, sc_word_t arg3, sc_word_t arg4, sc_word_t arg5, sc_word_t arg6) inline
Definition at line 43 of file cxx-syscall.hpp.
{
         return __do_syscall6(sc, arg1, arg2, arg3, arg4, arg5, arg6);
     }
References __do_syscall6(), arg1, arg2, arg3, arg4, and arg5.
do_syscall()
template<typename... T> sc_result_t mlibc::do_syscall (int sc, T... args)
Definition at line 79 of file cxx-syscall.hpp.
{
         return static_cast<sc_result_t>(do_nargs_syscall(sc, sc_cast(args)...));
     }
References do_nargs_syscall(), and sc_cast().
Referenced by do_cp_syscall(), sys_clock_getres(), sys_fadvise(), sys_fdatasync(), sys_fgetxattr(), sys_flistxattr(), sys_fremovexattr(), sys_fsetxattr(), sys_fsync(), sys_ftruncate(), sys_getgroups(), sys_getrandom(), sys_getrlimit(), sys_getsid(), sys_gettid(), sys_getxattr(), sys_lgetxattr(), sys_listxattr(), sys_llistxattr(), sys_lremovexattr(), sys_lsetxattr(), sys_mkdirat(), sys_mknodat(), sys_openat(), sys_removexattr(), sys_renameat(), sys_setrlimit(), sys_setxattr(), sys_sigaltstack(), sys_sigsuspend(), sys_sigtimedwait(), sys_symlink(), sys_symlinkat(), sys_sync(), sys_times(), and sys_umask().
envEnabled()
static bool mlibc::envEnabled (const char * env) static
Definition at line 18 of file global-config.cpp.
{
     auto value = getenv(env);
     return value && *value && *value != '0';
 }
References env, getenv(), and value.
Referenced by mlibc::GlobalConfig::GlobalConfig().
file_dispose_cb()
template<typename T > void mlibc::file_dispose_cb (abstract_file * base)
Definition at line 103 of file file-io.hpp.
{
     frg::destruct(getAllocator(), static_cast<T *>(base));
 }
References base, getAllocator(), and T.
for()
mlibc::for ()
Definition at line 134 of file generic.cpp.
{
         struct pollfd *fd = &fds[i];
         if (read_set && FD_ISSET(i, read_set)) {
             fd->events |= POLLIN;
         }
         if (write_set && FD_ISSET(i, write_set)) {
             fd->events |= POLLOUT;
         }
         if (except_set && FD_ISSET(i, except_set)) {
             fd->events |= POLLPRI;
         }
         if (!fd->events) {
             fd->fd = -1;
             continue;
         }
         fd->fd = i;
     }
References except_set, fd, FD_ISSET, fds, i, POLLIN, POLLOUT, POLLPRI, read_set, and write_set.
free()
mlibc::free (fds)
Referenced by if().
generic_is_control()
bool mlibc::generic_is_control (codepoint c) inline
Definition at line 34 of file charset.hpp.
{
     return (c <= 0x1F) || (c == 0x7F) || (c >= 0x80 && c <= 0x9F);
 }
References c.
Referenced by iscntrl(), and iswcntrl().
get_current_tcb()
Tcb * mlibc::get_current_tcb () inline
Definition at line 8 of file thread.hpp.
{
     // On AArch64, TPIDR_EL0 points to 0x10 bytes before the first TLS block.
     uintptr_t ptr;
     asm ("mrs %0, tpidr_el0" : "=r"(ptr));
     return reinterpret_cast<Tcb *>(ptr + 0x10 - sizeof(Tcb));
 }
Referenced by __mlibc_enter_thread(), Loader::_processLazyRelocations(), accessDtv(), do_cp_syscall(), fork(), Loader::initObjects(), pthread_atfork(), pthread_cleanup_pop(), pthread_cleanup_push(), pthread_exit(), pthread_getspecific(), pthread_self(), pthread_setcancelstate(), pthread_setcanceltype(), pthread_setspecific(), pthread_testcancel(), anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler(), sys_getschedparam(), sys_setschedparam(), this_tid(), and tryAccessDtv().
get_dir_state()
static ReadDirState* mlibc::get_dir_state (int fdnum) static
Definition at line 279 of file generic.cpp.
{
     ReadDirState *result;
     if (auto value = open_dirs.get(fdnum)) {
         result = *value;
     } else {
         result = (ReadDirState *)malloc(sizeof(ReadDirState));
         result->offset = 0;
         result->capacity = 1024;
         result->buffer = malloc(result->capacity);
         open_dirs.insert(fdnum, result);
     }
     return result;
 }
References malloc(), open_dirs, result, and value.
get_nameserver()
frg::optional< struct nameserver_data > mlibc::get_nameserver ()
Definition at line 8 of file resolv_conf.cpp.
{
     auto file = fopen("/etc/resolv.conf", "r");
     if (!file)
         return frg::null_opt;
     char line[128];
     struct nameserver_data ret;
     while (fgets(line, 128, file)) {
         char *pos;
         if (!strchr(line, '\n') && !feof(file)) {
             // skip truncated lines
             for (int c = getc(file); c != '\n' && c != EOF; c = getc(file));
             continue;
         }
         // TODO(geert): resolv.conf can actually have multiple nameservers
         // but we just pick the first one for now
         if (!strncmp(line, "nameserver", 10) && isspace(line[10])) {
             char *end;
             for (pos = line + 11; isspace(*pos); pos++);
             for (end = pos; *end && !isspace(*end); end++);
             *end = '\0';
             ret.name = frg::string<MemoryAllocator>(
                     pos, end - pos, getAllocator());
             break;
         }
     }
     fclose(file);
     if(ret.name.empty())
         return frg::null_opt;
     return ret;
 }
References c, EOF, fclose(), feof(), fgets(), fopen(), getAllocator(), getc(), isspace(), ret, strchr(), and strncmp().
Referenced by lookup_addr_dns(), and lookup_name_dns().
get_sp()
uintptr_t mlibc::get_sp () inline
Definition at line 15 of file thread.hpp.
{
     uintptr_t sp;
     asm ("mov %0, sp" : "=r"(sp));
     return sp;
 }
Referenced by anonymous_namespace{pthread-stubs.cpp}::get_own_stackinfo().
globalConfig()
const GlobalConfig& mlibc::globalConfig () inline
Definition at line 12 of file global-config.hpp.
{
     static GlobalConfig cached;
     return cached;
 }
Referenced by free(), mlibc::GlobalConfigGuard::GlobalConfigGuard(), malloc(), and realloc().
if() [1/9]
mlibc::if ((int) ret. ret = = -1)
Definition at line 790 of file generic.cpp.
{
         return ret.errno;
     }
References ret.
if() [2/9]
mlibc::if (except_set)
Definition at line 186 of file generic.cpp.
                     {
         *except_set = res_except_set;
     }
References except_set, and res_except_set.
if() [3/9]
mlibc::if (fds = = NULL)
Definition at line 130 of file generic.cpp.
                      {
         return ENOMEM;
     }
References ENOMEM.
if() [4/9]
mlibc::if (int r = sys_ioctl(fd, TCGETS, attr, &ret) != 0)
Definition at line 66 of file generic.cpp.
{
         return r;
     }
References r.
if() [5/9]
mlibc::if (read_set)
Definition at line 180 of file generic.cpp.
                   {
         *read_set = res_read_set;
     }
References read_set, and res_read_set.
if() [6/9]
mlibc::if ()
Definition at line 308 of file aero.cpp.
                     {
         return -result;
     }
References result.
Referenced by sys_inotify_create(), and sys_signalfd_create().
if() [7/9]
mlibc::if (ret ! = 0)
Definition at line 155 of file generic.cpp.
                   {
         free(fds);
         return ret;
     }
References fds, free(), and ret.
if() [8/9]
mlibc::if (ret_value = = MAP_FAILED)
Definition at line 426 of file generic.cpp.
{
         return ret.errno;
     }
References ret.
if() [9/9]
mlibc::if (write_set)
Definition at line 183 of file generic.cpp.
                    {
         *write_set = res_write_set;
     }
References res_write_set, and write_set.
initStackGuard()
void mlibc::initStackGuard (void * entropy)
Definition at line 10 of file stack_protector.cpp.
{
     if(entropy != nullptr) {
         memcpy(&__stack_chk_guard, entropy, sizeof(__stack_chk_guard));
     } else {
         // If no entropy is available, set it to the terminator canary
         __stack_chk_guard = 0;
         __stack_chk_guard |= ('\n' << 16);
         __stack_chk_guard |= (255 << 24);
     }
 }
References __stack_chk_guard, and memcpy.
ioctl_drm()
int mlibc::ioctl_drm (int fd, unsigned long request, void * arg, int * result, HelHandle handle)
Definition at line 14 of file drm.cpp.
{
     switch(request) {
     case DRM_IOCTL_VERSION: {
         auto param = reinterpret_cast<drm_version*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->version_major = resp.drm_version_major();
         param->version_minor = resp.drm_version_minor();
         param->version_patchlevel = resp.drm_version_patchlevel();
         if(param->name)
             memcpy(param->name, resp.drm_driver_name().data(), frg::min(param->name_len,
                     resp.drm_driver_name().size()));
         if(param->date)
             memcpy(param->date, resp.drm_driver_date().data(), frg::min(param->date_len,
                     resp.drm_driver_date().size()));
         if(param->desc)
             memcpy(param->desc, resp.drm_driver_desc().data(), frg::min(param->desc_len,
                     resp.drm_driver_desc().size()));
         param->name_len = resp.drm_driver_name().size();
         param->date_len = resp.drm_driver_date().size();
         param->desc_len = resp.drm_driver_desc().size();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_GET_CAP: {
         auto param = reinterpret_cast<drm_get_cap*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_capability(param->capability);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         if(resp.error() == managarm::fs::Errors::ILLEGAL_ARGUMENT) {
             return EINVAL;
         }else{
             __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
             param->value = resp.drm_value();
             *result = resp.result();
             return 0;
         }
     }
     case DRM_IOCTL_SET_CLIENT_CAP: {
         auto param = reinterpret_cast<drm_set_client_cap *>(arg);
         mlibc::infoLogger() << "\e[35mmlibc: DRM_IOCTL_SET_CLIENT_CAP(" << param->capability << ") ignores its value\e[39m" << frg::endlog;
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_capability(param->capability);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         if(resp.error() == managarm::fs::Errors::ILLEGAL_ARGUMENT) {
             return EINVAL;
         }else{
             __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
             param->value = resp.drm_value();
             *result = resp.result();
             return 0;
         }
     }
     case DRM_IOCTL_GET_MAGIC: {
         auto param = reinterpret_cast<drm_auth *>(arg);
         mlibc::infoLogger() << "\e[31mmlibc: DRM_IOCTL_GET_MAGIC is not implemented correctly\e[39m"
                 << frg::endlog;
         param->magic = 1;
         *result = 0;
         return 0;
     }
     case DRM_IOCTL_AUTH_MAGIC: {
         mlibc::infoLogger() << "\e[31mmlibc: DRM_IOCTL_AUTH_MAGIC is not implemented correctly\e[39m"
                 << frg::endlog;
         *result = 0;
         return 0;
     }
     case DRM_IOCTL_SET_MASTER: {
         mlibc::infoLogger() << "\e[31mmlibc: DRM_IOCTL_SET_MASTER is not implemented correctly\e[39m"
                 << frg::endlog;
         *result = 0;
         return 0;
     }
     case DRM_IOCTL_DROP_MASTER: {
         mlibc::infoLogger() << "\e[31mmlibc: DRM_IOCTL_DROP_MASTER is not implemented correctly\e[39m"
                 << frg::endlog;
         *result = 0;
         return 0;
     }
     case DRM_IOCTL_MODE_GETRESOURCES: {
         auto param = reinterpret_cast<drm_mode_card_res *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         if(recv_resp.error() == kHelErrDismissed) {
             return EINVAL;
         }
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         for(size_t i = 0; i < resp.drm_fb_ids_size(); i++) {
             if(i >= param->count_fbs)
                  break;
             auto dest = reinterpret_cast<uint32_t *>(param->fb_id_ptr);
             dest[i] = resp.drm_fb_ids(i);
         }
         param->count_fbs = resp.drm_fb_ids_size();
         for(size_t i = 0; i < resp.drm_crtc_ids_size(); i++) {
             if(i >= param->count_crtcs)
                  break;
             auto dest = reinterpret_cast<uint32_t *>(param->crtc_id_ptr);
             dest[i] = resp.drm_crtc_ids(i);
         }
         param->count_crtcs = resp.drm_crtc_ids_size();
         for(size_t i = 0; i < resp.drm_connector_ids_size(); i++) {
             if(i >= param->count_connectors)
                  break;
             auto dest = reinterpret_cast<uint32_t *>(param->connector_id_ptr);
             dest[i] = resp.drm_connector_ids(i);
         }
         param->count_connectors = resp.drm_connector_ids_size();
         for(size_t i = 0; i < resp.drm_encoder_ids_size(); i++) {
             if(i >= param->count_encoders)
                  continue;
             auto dest = reinterpret_cast<uint32_t *>(param->encoder_id_ptr);
             dest[i] = resp.drm_encoder_ids(i);
         }
         param->count_encoders = resp.drm_encoder_ids_size();
         param->min_width = resp.drm_min_width();
         param->max_width = resp.drm_max_width();
         param->min_height = resp.drm_min_height();
         param->max_height = resp.drm_max_height();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_GETCONNECTOR: {
         auto param = reinterpret_cast<drm_mode_get_connector*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_connector_id(param->connector_id);
         req.set_drm_max_modes(param->count_modes);
         auto [offer, send_req, recv_resp, recv_list] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline(),
                 helix_ng::recvBuffer(reinterpret_cast<void *>(param->modes_ptr), param->count_modes * sizeof(drm_mode_modeinfo))
             )
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         if(recv_resp.error() == kHelErrDismissed)
             return EINVAL;
         HEL_CHECK(recv_resp.error());
         HEL_CHECK(recv_list.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         for(size_t i = 0; i < resp.drm_encoders_size(); i++) {
             if(i >= param->count_encoders)
                  continue;
             auto dest = reinterpret_cast<uint32_t *>(param->encoders_ptr);
             dest[i] = resp.drm_encoders(i);
         }
         param->count_props = 0;
         param->encoder_id = resp.drm_encoder_id();
         param->connector_type = resp.drm_connector_type();
         param->connector_type_id = resp.drm_connector_type_id();
         param->connection = resp.drm_connection();
         param->mm_width = resp.drm_mm_width();
         param->mm_height = resp.drm_mm_height();
         param->subpixel = resp.drm_subpixel();
         param->pad = 0;
         param->count_encoders = resp.drm_encoders_size();
         param->count_modes = resp.drm_num_modes();
         if(param->props_ptr) {
             auto id_ptr = reinterpret_cast<uint32_t *>(param->props_ptr);
             for(size_t i = 0; i < frg::min(static_cast<size_t>(param->count_props), resp.drm_obj_property_ids_size()); i++) {
                 id_ptr[i] = resp.drm_obj_property_ids(i);
             }
         }
         param->count_props = resp.drm_obj_property_ids_size();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_GETPROPERTY: {
         auto param = reinterpret_cast<drm_mode_get_property*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_property_id(param->prop_id);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         if(resp.error() != managarm::fs::Errors::SUCCESS) {
             mlibc::infoLogger() << "\e[31mmlibc: DRM_IOCTL_MODE_GETPROPERTY(" << param->prop_id << ") error " << (int) resp.error() << "\e[39m"
                 << frg::endlog;
             *result = 0;
             return EINVAL;
         }
         memcpy(param->name, resp.drm_property_name().data(), resp.drm_property_name().size());
         param->count_values = resp.drm_property_vals_size();
         param->flags = resp.drm_property_flags();
         for(size_t i = 0; i < param->count_values && i < resp.drm_property_vals_size() && param->values_ptr; i++) {
             auto dest = reinterpret_cast<uint64_t *>(param->values_ptr);
             dest[i] = resp.drm_property_vals(i);
         }
         __ensure(resp.drm_enum_name_size() == resp.drm_enum_value_size());
         for(size_t i = 0; i < param->count_enum_blobs && i < resp.drm_enum_name_size() && i < resp.drm_enum_value_size(); i++) {
             auto dest = reinterpret_cast<drm_mode_property_enum *>(param->enum_blob_ptr);
             dest[i].value = resp.drm_enum_value(i);
             strncpy(dest[i].name, resp.drm_enum_name(i).data(), DRM_PROP_NAME_LEN);
         }
         param->count_enum_blobs = resp.drm_enum_name_size();
         *result = 0;
         return 0;
     }
     case DRM_IOCTL_MODE_SETPROPERTY: {
         auto param = reinterpret_cast<drm_mode_connector_set_property *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_property_id(param->prop_id);
         req.set_drm_property_value(param->value);
         req.set_drm_obj_id(param->connector_id);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         if(resp.error() != managarm::fs::Errors::SUCCESS) {
             mlibc::infoLogger() << "\e[31mmlibc: DRM_IOCTL_MODE_SETPROPERTY(" << param->prop_id << ") error " << (int) resp.error() << "\e[39m"
                 << frg::endlog;
             *result = 0;
             return EINVAL;
         }
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_GETPROPBLOB: {
         auto param = reinterpret_cast<drm_mode_get_blob *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_blob_id(param->blob_id);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         if(resp.error() != managarm::fs::Errors::SUCCESS) {
             mlibc::infoLogger() << "\e[31mmlibc: DRM_IOCTL_MODE_GETPROPBLOB(" << param->blob_id << ") error " << (int) resp.error() << "\e[39m"
                 << frg::endlog;
             *result = 0;
             return EINVAL;
         }
         uint8_t *dest = reinterpret_cast<uint8_t *>(param->data);
         for(size_t i = 0; i < resp.drm_property_blob_size(); i++) {
             if(i >= param->length) {
                 continue;
             }
             dest[i] = resp.drm_property_blob(i);
         }
         param->length = resp.drm_property_blob_size();
         *result = 0;
         return 0;
     }
     case DRM_IOCTL_MODE_GETPLANE: {
         auto param = reinterpret_cast<drm_mode_get_plane*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_plane_id(param->plane_id);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->crtc_id = resp.drm_crtc_id();
         param->fb_id = resp.drm_fb_id();
         param->possible_crtcs = resp.drm_possible_crtcs();
         param->gamma_size = resp.drm_gamma_size();
         // FIXME: this should be passed as a buffer with helix, but this has no bounded max size?
         for(size_t i = 0; i < resp.drm_format_type_size(); i+= 4) {
             if(i >= param->count_format_types) {
                 break;
             }
             auto dest = reinterpret_cast<uint32_t *>(param->format_type_ptr);
             dest[i] = resp.drm_format_type(i);
         }
         param->count_format_types = resp.drm_format_type_size();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_GETPLANERESOURCES: {
         auto param = reinterpret_cast<drm_mode_get_plane_res *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         frg::string<MemoryAllocator> ser(getSysdepsAllocator());
         req.SerializeToString(&ser);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBuffer(ser.data(), ser.size()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         // FIXME: send this via a helix_ng buffer
         for(size_t i = 0; i < resp.drm_plane_res_size(); i++) {
             if(i >= param->count_planes) {
                 continue;
             }
             auto dest = reinterpret_cast<uint32_t *>(param->plane_id_ptr);
             dest[i] = resp.drm_plane_res(i);
         }
         param->count_planes = resp.drm_plane_res_size();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_GETENCODER: {
         auto param = reinterpret_cast<drm_mode_get_encoder*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_encoder_id(param->encoder_id);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->encoder_type = resp.drm_encoder_type();
         param->crtc_id = resp.drm_crtc_id();
         param->possible_crtcs = resp.drm_possible_crtcs();
         param->possible_clones = resp.drm_possible_clones();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_CREATE_DUMB: {
         auto param = reinterpret_cast<drm_mode_create_dumb*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_width(param->width);
         req.set_drm_height(param->height);
         req.set_drm_bpp(param->bpp);
         req.set_drm_flags(param->flags);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->handle = resp.drm_handle();
         param->pitch = resp.drm_pitch();
         param->size = resp.drm_size();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_ADDFB: {
         auto param = reinterpret_cast<drm_mode_fb_cmd *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_width(param->width);
         req.set_drm_height(param->height);
         req.set_drm_pitch(param->pitch);
         req.set_drm_bpp(param->bpp);
         req.set_drm_depth(param->depth);
         req.set_drm_handle(param->handle);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->fb_id = resp.drm_fb_id();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_ADDFB2: {
         auto param = reinterpret_cast<drm_mode_fb_cmd2 *>(arg);
         if(param->pixel_format != DRM_FORMAT_XRGB8888)
             mlibc::infoLogger() << "mlibc: Unexpected pixel format "
                     << frg::hex_fmt(param->pixel_format) << frg::endlog;
         __ensure(param->pixel_format == DRM_FORMAT_XRGB8888
                 || param->pixel_format == DRM_FORMAT_ARGB8888);
         __ensure(!param->flags || param->flags == DRM_MODE_FB_MODIFIERS);
         __ensure(!param->modifier[0] || param->modifier[0] == DRM_FORMAT_MOD_INVALID);
         __ensure(!param->offsets[0]);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(DRM_IOCTL_MODE_ADDFB);
         req.set_drm_width(param->width);
         req.set_drm_height(param->height);
         req.set_drm_pitch(param->pitches[0]);
         req.set_drm_bpp(32);
         req.set_drm_depth(24);
         req.set_drm_handle(param->handles[0]);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->fb_id = resp.drm_fb_id();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_RMFB: {
         auto param = reinterpret_cast<int *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_fb_id(*param);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_MAP_DUMB: {
         auto param = reinterpret_cast<drm_mode_map_dumb*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_handle(param->handle);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->offset = resp.drm_offset();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_GETCRTC: {
         auto param = reinterpret_cast<drm_mode_crtc*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_crtc_id(param->crtc_id);
         auto [offer, send_req, recv_resp, recv_data] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline(),
                 helix_ng::recvBuffer(&param->mode, sizeof(drm_mode_modeinfo)))
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         HEL_CHECK(recv_data.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->fb_id = resp.drm_fb_id();
         param->x = resp.drm_x();
         param->y = resp.drm_y();
         param->gamma_size = resp.drm_gamma_size();
         param->mode_valid = resp.drm_mode_valid();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_SETCRTC: {
         auto param = reinterpret_cast<drm_mode_crtc*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         for(size_t i = 0; i < param->count_connectors; i++) {
             auto dest = reinterpret_cast<uint32_t *>(param->set_connectors_ptr);
             req.add_drm_connector_ids(dest[i]);
         }
         req.set_drm_x(param->x);
         req.set_drm_y(param->y);
         req.set_drm_crtc_id(param->crtc_id);
         req.set_drm_fb_id(param->fb_id);
         req.set_drm_mode_valid(param->mode_valid);
         auto [offer, send_req, send_mode, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::sendBuffer(&param->mode, sizeof(drm_mode_modeinfo)),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(send_mode.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_OBJ_GETPROPERTIES: {
         auto param = reinterpret_cast<drm_mode_obj_get_properties *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_count_props(param->count_props);
         req.set_drm_obj_id(param->obj_id);
         req.set_drm_obj_type(param->obj_type);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         auto props = reinterpret_cast<uint32_t *>(param->props_ptr);
         auto prop_vals = reinterpret_cast<uint64_t *>(param->prop_values_ptr);
         for(size_t i = 0; i < resp.drm_obj_property_ids_size(); i++) {
             if(i >= param->count_props) {
                 break;
             }
             props[i] = resp.drm_obj_property_ids(i);
             prop_vals[i] = resp.drm_obj_property_values(i);
         }
         param->count_props = resp.drm_obj_property_ids_size();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_PAGE_FLIP: {
         auto param = reinterpret_cast<drm_mode_crtc_page_flip *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         __ensure(!(param->flags & ~DRM_MODE_PAGE_FLIP_EVENT));
         req.set_drm_crtc_id(param->crtc_id);
         req.set_drm_fb_id(param->fb_id);
         req.set_drm_cookie(param->user_data);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_DIRTYFB: {
         auto param = reinterpret_cast<drm_mode_fb_dirty_cmd*>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_fb_id(param->fb_id);
         req.set_drm_flags(param->flags);
         req.set_drm_color(param->color);
         for(size_t i = 0; i < param->num_clips; i++) {
             auto dest = reinterpret_cast<drm_clip_rect *>(param->clips_ptr);
             managarm::fs::Rect<MemoryAllocator> clip(getSysdepsAllocator());
             clip.set_x1(dest->x1);
             clip.set_y1(dest->y1);
             clip.set_x2(dest->x2);
             clip.set_y2(dest->y2);
             req.add_drm_clips(std::move(clip));
         }
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         if(resp.error() == managarm::fs::Errors::ILLEGAL_ARGUMENT) {
             return EINVAL;
         }else{
             __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
             *result = resp.result();
             return 0;
         }
     }
     case DRM_IOCTL_MODE_CURSOR: {
         auto param = reinterpret_cast<drm_mode_cursor *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_flags(param->flags);
         req.set_drm_crtc_id(param->crtc_id);
         if (param->flags == DRM_MODE_CURSOR_MOVE) {
             req.set_drm_x(param->x);
             req.set_drm_y(param->y);
         } else if (param->flags == DRM_MODE_CURSOR_BO) {
             req.set_drm_width(param->width);
             req.set_drm_height(param->height);
             req.set_drm_handle(param->handle);
         } else {
             mlibc::infoLogger() << "\e[35mmlibc: invalid flags in DRM_IOCTL_MODE_CURSOR\e[39m" << frg::endlog;
             return EINVAL;
         }
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         if (resp.error() == managarm::fs::Errors::NO_BACKING_DEVICE) {
             return ENXIO;
         }else if (resp.error() == managarm::fs::Errors::ILLEGAL_ARGUMENT) {
             return EINVAL;
         }else{
             *result = resp.result();
             return 0;
         }
     }
     case DRM_IOCTL_MODE_DESTROY_DUMB: {
         auto param = reinterpret_cast<drm_mode_destroy_dumb *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_handle(param->handle);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_CREATEPROPBLOB: {
         auto param = reinterpret_cast<drm_mode_create_blob *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_blob_size(param->length);
         auto [offer, send_req, blob_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::sendBuffer(reinterpret_cast<void *>(param->data), param->length),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(blob_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->blob_id = resp.drm_blob_id();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_DESTROYPROPBLOB: {
         auto param = reinterpret_cast<drm_mode_destroy_blob *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_blob_id(param->blob_id);
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_ATOMIC: {
         auto param = reinterpret_cast<drm_mode_atomic *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_flags(param->flags);
         req.set_drm_cookie(param->user_data);
         size_t prop_count = 0;
         auto objs_ptr = reinterpret_cast<uint32_t *>(param->objs_ptr);
         auto count_props_ptr = reinterpret_cast<uint32_t *>(param->count_props_ptr);
         auto props_ptr = reinterpret_cast<uint32_t *>(param->props_ptr);
         auto prop_values_ptr = reinterpret_cast<uint64_t *>(param->prop_values_ptr);
         for(size_t i = 0; i < param->count_objs; i++) {
             /* list of modeobjs and their property count */
             req.add_drm_obj_ids(objs_ptr[i]);
             req.add_drm_prop_counts(count_props_ptr[i]);
             prop_count += count_props_ptr[i];
         }
         for(size_t i = 0; i < prop_count; i++) {
             /* array of property IDs */
             req.add_drm_props(props_ptr[i]);
             /* array of property values */
             req.add_drm_prop_values(prop_values_ptr[i]);
         }
         auto [offer, send_req, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_MODE_LIST_LESSEES: {
         mlibc::infoLogger() << "\e[35mmlibc: DRM_IOCTL_MODE_LIST_LESSEES"
                 " is not implemented correctly\e[39m" << frg::endlog;
         return EINVAL;
     }
     case DRM_IOCTL_MODE_SETGAMMA: {
         mlibc::infoLogger() << "\e[35mmlibc: DRM_IOCTL_MODE_SETGAMMA"
                 " is not implemented correctly\e[39m" << frg::endlog;
         return 0;
     }
     case DRM_IOCTL_MODE_CREATE_LEASE: {
         auto param = reinterpret_cast<drm_mode_create_lease *>(arg);
         mlibc::infoLogger() << "\e[35mmlibc: DRM_IOCTL_MODE_CREATE_LEASE"
                 " is a noop\e[39m" << frg::endlog;
         param->lessee_id = 1;
         param->fd = fd;
         *result = 0;
         return 0;
     }
     case DRM_IOCTL_GEM_CLOSE: {
         mlibc::infoLogger() << "\e[35mmlibc: DRM_IOCTL_GEM_CLOSE"
                 " is a noop\e[39m" << frg::endlog;
         return 0;
     }
     case DRM_IOCTL_PRIME_HANDLE_TO_FD: {
         auto param = reinterpret_cast<drm_prime_handle *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_prime_handle(param->handle);
         req.set_drm_flags(param->flags);
         auto [offer, send_req, send_creds, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::imbueCredentials(),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(send_creds.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         param->fd = resp.drm_prime_fd();
         *result = resp.result();
         return 0;
     }
     case DRM_IOCTL_PRIME_FD_TO_HANDLE: {
         auto param = reinterpret_cast<drm_prime_handle *>(arg);
         managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
         req.set_req_type(managarm::fs::CntReqType::PT_IOCTL);
         req.set_command(request);
         req.set_drm_flags(param->flags);
         auto [offer, send_req, send_creds, recv_resp] = exchangeMsgsSync(
             handle,
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::imbueCredentials(getHandleForFd(param->fd)),
                 helix_ng::recvInline())
         );
         HEL_CHECK(offer.error());
         HEL_CHECK(send_req.error());
         HEL_CHECK(send_creds.error());
         HEL_CHECK(recv_resp.error());
         managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
         resp.ParseFromArray(recv_resp.data(), recv_resp.length());
         if(resp.error() == managarm::fs::Errors::FILE_NOT_FOUND) {
             return EBADF;
         } else {
             __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         }
         param->handle = resp.drm_prime_handle();
         *result = resp.result();
         return 0;
     }
     }
     mlibc::infoLogger() << "mlibc: Unexpected DRM ioctl with"
             << ", number: 0x" << frg::hex_fmt(_IOC_NR(request))
             << " (raw request: " << frg::hex_fmt(request) << ")" << frg::endlog;
     __ensure(!"Illegal ioctl request");
     __builtin_unreachable();
 }
References __ensure, arg, EBADF, EINVAL, ENXIO, exchangeMsgsSync(), fd, getHandleForFd(), getSysdepsAllocator(), i, infoLogger, int, memcpy, name, request, and strncpy().
lookup_addr_dns()
int mlibc::lookup_addr_dns (frg::span< char > name, frg::array< uint8_t, 16 > & addr, int family)
Definition at line 163 of file lookup.cpp.
{
     frg::string<MemoryAllocator> request{getAllocator()};
     int num_q = 1;
     struct dns_header header;
     header.identification = htons(123);
     header.flags = htons(0x100);
     header.no_q = htons(num_q);
     header.no_ans = htons(0);
     header.no_auths = htons(0);
     header.no_additional = htons(0);
     request.resize(sizeof(header));
     memcpy(request.data(), &header, sizeof(header));
     char addr_str[64];
     if(!inet_ntop(family, addr.data(), addr_str, sizeof(addr_str))) {
         switch(errno) {
             case EAFNOSUPPORT:
                 return -EAI_FAMILY;
             case ENOSPC:
                 return -EAI_OVERFLOW;
             default:
                 return -EAI_FAIL;
         }
     }
     frg::string<MemoryAllocator> req_str{getAllocator(), addr_str};
     req_str += ".in-addr.arpa";
     frg::string_view req_view{req_str.data(), req_str.size()};
     size_t ptr = 0;
     do {
         size_t next = req_view.find_first('.', ptr);
         size_t length = next != (size_t)-1 ? next - ptr : req_view.size() - ptr;
         frg::string_view substring = req_view.sub_string(ptr, length);
         request += char(length);
         request += substring;
         ptr = next + 1;
     } while(ptr != 0);
     request += char(0);
     // set question type to fetch PTR records
     request += 0;
     request += 12;
     // set CLASS to IN
     request += 0;
     request += 1;
     struct sockaddr_in sin = {};
     sin.sin_family = AF_INET;
     // TODO(geert): we could probably make this use the service lookup
     // for dns
     sin.sin_port = htons(53);
     auto nameserver = get_nameserver();
     if (!inet_aton(nameserver ? nameserver->name.data() : "127.0.0.1", &sin.sin_addr)) {
         mlibc::infoLogger() << "lookup_name_dns(): inet_aton() failed!" << frg::endlog;
         return -EAI_SYSTEM;
     }
     int fd = socket(AF_INET, SOCK_DGRAM, 0);
     if (fd < 0) {
         mlibc::infoLogger() << "lookup_name_dns(): socket() failed" << frg::endlog;
         return -EAI_SYSTEM;
     }
     size_t sent = sendto(fd, request.data(), request.size(), 0,
             (struct sockaddr*)&sin, sizeof(sin));
     if (sent != request.size()) {
         mlibc::infoLogger() << "lookup_name_dns(): sendto() failed to send everything" << frg::endlog;
         return -EAI_SYSTEM;
     }
     char response[256];
     ssize_t rlen;
     int num_ans = 0;
     while ((rlen = recvfrom(fd, response, 256, 0, NULL, NULL)) >= 0) {
         if ((size_t)rlen < sizeof(struct dns_header))
             continue;
         auto response_header = reinterpret_cast<struct dns_header*>(response);
         if (response_header->identification != header.identification)
             return -EAI_FAIL;
         auto it = response + sizeof(struct dns_header);
         for (int i = 0; i < ntohs(response_header->no_q); i++) {
             auto dns_name = read_dns_name(response, it);
             (void) dns_name;
             it += 4;
         }
         for (int i = 0; i < ntohs(response_header->no_ans); i++) {
             struct dns_addr_buf buffer;
             auto dns_name = read_dns_name(response, it);
             uint16_t rr_type = (it[0] << 8) | it[1];
             uint16_t rr_class = (it[2] << 8) | it[3];
             uint16_t rr_length = (it[8] << 8) | it[9];
             it += 10;
             (void)rr_class;
             (void)rr_length;
             (void)dns_name;
             switch (rr_type) {
                 case RECORD_PTR: {
                     auto ptr_name = read_dns_name(response, it);
                     if (ptr_name.size() >= name.size())
                         return -EAI_OVERFLOW;
                     std::copy(ptr_name.begin(), ptr_name.end(), name.data());
                     name.data()[ptr_name.size()] = '\0';
                     return 1;
                 }
                 default:
                     mlibc::infoLogger() << "lookup_addr_dns: unknown rr type "
                         << rr_type << frg::endlog;
                     break;
             }
             num_ans += ntohs(response_header->no_ans);
             if (num_ans >= num_q)
                 break;
         }
     }
     close(fd);
     return 0;
 }
References addr, AF_INET, close(), EAFNOSUPPORT, EAI_FAIL, EAI_FAMILY, EAI_OVERFLOW, EAI_SYSTEM, ENOSPC, errno, fd, mlibc::dns_header::flags, get_nameserver(), getAllocator(), htons(), i, mlibc::dns_header::identification, inet_aton(), inet_ntop(), infoLogger, memcpy, name, mlibc::dns_header::no_additional, mlibc::dns_header::no_ans, mlibc::dns_header::no_auths, mlibc::dns_header::no_q, ntohs(), NULL, read_dns_name(), mlibc::anonymous_namespace{lookup.cpp}::RECORD_PTR, recvfrom(), request, sendto(), sin(), SOCK_DGRAM, socket(), and Driver::void().
Referenced by getnameinfo().
lookup_addr_hosts()
int mlibc::lookup_addr_hosts (frg::span< char > name, frg::array< uint8_t, 16 > & addr, int family)
Definition at line 358 of file lookup.cpp.
{
     auto file = fopen("/etc/hosts", "r");
     if (!file) {
         switch (errno) {
             case ENOENT:
             case ENOTDIR:
             case EACCES:
                 return -EAI_SERVICE;
             default:
                 return -EAI_SYSTEM;
         }
     }
     // Buffer to hold ASCII version of address
     char addr_str[64];
     if(!inet_ntop(family, addr.data(), addr_str, sizeof(addr_str))) {
         switch(errno) {
             case EAFNOSUPPORT:
                 return -EAI_FAMILY;
             case ENOSPC:
                 return -EAI_OVERFLOW;
             default:
                 return -EAI_FAIL;
         }
     }
     int addr_str_len = strlen(addr_str);
     char line[128];
     while (fgets(line, 128, file)) {
         char *pos;
         // same way to deal with comments as in services.cpp
         if ((pos = strchr(line, '#'))) {
             *pos++ = '\n';
             *pos = '\0';
         }
         if (strncmp(line, addr_str, addr_str_len))
             continue;
         for (pos = line + addr_str_len + 1; isspace(*pos); pos++);
         char *begin = pos;
         for (; !isspace(*pos); pos++);
         char *end = pos;
         size_t size = end - begin;
         if (size >= name.size())
             return -EAI_OVERFLOW;
         std::copy(begin, end, name.data());
         name.data()[size] = '\0';
         return 1;
     }
     return 0;
 }
References addr, EACCES, EAFNOSUPPORT, EAI_FAIL, EAI_FAMILY, EAI_OVERFLOW, EAI_SERVICE, EAI_SYSTEM, ENOENT, ENOSPC, ENOTDIR, errno, fgets(), fopen(), inet_ntop(), isspace(), name, size, strchr(), strlen(), and strncmp().
Referenced by getnameinfo().
lookup_name_dns()
int mlibc::lookup_name_dns (struct lookup_result & buf, const char * name, frg::string< MemoryAllocator > & canon_name)
Definition at line 49 of file lookup.cpp.
{
     frg::string<MemoryAllocator> request{getAllocator()};
     int num_q = 1;
     struct dns_header header;
     header.identification = htons(123);
     header.flags = htons(0x100);
     header.no_q = htons(num_q);
     header.no_ans = htons(0);
     header.no_auths = htons(0);
     header.no_additional = htons(0);
     request.resize(sizeof(header));
     memcpy(request.data(), &header, sizeof(header));
     const char *end = name;
     while (*end != '\0') {
         end = strchrnul(name, '.');
         size_t length = end - name;
         frg::string_view substring{name, length};
         name += length + 1;
         request += char(length);
         request += substring;
     }
     request += char(0);
     // set question type to fetch A records
     request += 0;
     request += 1;
     // set CLASS to IN
     request += 0;
     request += 1;
     struct sockaddr_in sin = {};
     sin.sin_family = AF_INET;
     // TODO(geert): we could probably make this use the service lookup
     // for dns
     sin.sin_port = htons(53);
     auto nameserver = get_nameserver();
     if (!inet_aton(nameserver ? nameserver->name.data() : "127.0.0.1", &sin.sin_addr)) {
         mlibc::infoLogger() << "lookup_name_dns(): inet_aton() failed!" << frg::endlog;
         return -EAI_SYSTEM;
     }
     int fd = socket(AF_INET, SOCK_DGRAM, 0);
     if (fd < 0) {
         mlibc::infoLogger() << "lookup_name_dns(): socket() failed" << frg::endlog;
         return -EAI_SYSTEM;
     }
     size_t sent = sendto(fd, request.data(), request.size(), 0,
             (struct sockaddr*)&sin, sizeof(sin));
     if (sent != request.size()) {
         mlibc::infoLogger() << "lookup_name_dns(): sendto() failed to send everything" << frg::endlog;
         return -EAI_SYSTEM;
     }
     char response[256];
     ssize_t rlen;
     int num_ans = 0;
     while ((rlen = recvfrom(fd, response, 256, 0, NULL, NULL)) >= 0) {
         if ((size_t)rlen < sizeof(struct dns_header))
             continue;
         auto response_header = reinterpret_cast<struct dns_header*>(response);
         if (response_header->identification != header.identification)
             return -EAI_FAIL;
         auto it = response + sizeof(struct dns_header);
         for (int i = 0; i < ntohs(response_header->no_q); i++) {
             auto dns_name = read_dns_name(response, it);
             (void) dns_name;
             it += 4;
         }
         for (int i = 0; i < ntohs(response_header->no_ans); i++) {
             struct dns_addr_buf buffer;
             auto dns_name = read_dns_name(response, it);
             uint16_t rr_type = (it[0] << 8) | it[1];
             uint16_t rr_class = (it[2] << 8) | it[3];
             uint16_t rr_length = (it[8] << 8) | it[9];
             it += 10;
             (void)rr_class;
             switch (rr_type) {
                 case RECORD_A:
                     memcpy(buffer.addr, it, rr_length);
                     it += rr_length;
                     buffer.family = AF_INET;
                     buffer.name = std::move(dns_name);
                     buf.buf.push(std::move(buffer));
                     break;
                 case RECORD_CNAME:
                     canon_name = std::move(read_dns_name(response, it));
                     buf.aliases.push(std::move(dns_name));
                     break;
                 default:
                     mlibc::infoLogger() << "lookup_name_dns: unknown rr type "
                         << rr_type << frg::endlog;
                     break;
             }
         }
         num_ans += ntohs(response_header->no_ans);
         if (num_ans >= num_q)
             break;
     }
     close(fd);
     return buf.buf.size();
 }
References mlibc::dns_addr_buf::addr, AF_INET, buf, close(), EAI_FAIL, EAI_SYSTEM, mlibc::dns_addr_buf::family, fd, mlibc::dns_header::flags, get_nameserver(), getAllocator(), htons(), i, mlibc::dns_header::identification, inet_aton(), infoLogger, memcpy, mlibc::dns_addr_buf::name, name, mlibc::dns_header::no_additional, mlibc::dns_header::no_ans, mlibc::dns_header::no_auths, mlibc::dns_header::no_q, ntohs(), NULL, read_dns_name(), mlibc::anonymous_namespace{lookup.cpp}::RECORD_A, mlibc::anonymous_namespace{lookup.cpp}::RECORD_CNAME, recvfrom(), request, sendto(), sin(), SOCK_DGRAM, socket(), strchrnul(), and Driver::void().
Referenced by getaddrinfo(), and gethostbyname().
lookup_name_hosts()
int mlibc::lookup_name_hosts (struct lookup_result & buf, const char * name, frg::string< MemoryAllocator > & canon_name)
Definition at line 292 of file lookup.cpp.
{
     auto file = fopen("/etc/hosts", "r");
     if (!file) {
         switch (errno) {
             case ENOENT:
             case ENOTDIR:
             case EACCES:
                 return -EAI_SERVICE;
             default:
                 return -EAI_SYSTEM;
         }
     }
     char line[128];
     int name_length = strlen(name);
     while (fgets(line, 128, file)) {
         char *pos;
         // same way to deal with comments as in services.cpp
         if ((pos = strchr(line, '#'))) {
             *pos++ = '\n';
             *pos = '\0';
         }
         for(pos = line + 1; (pos = strstr(pos, name)) &&
                 (!isspace(pos[-1]) || !isspace(pos[name_length])); pos++);
         if (!pos)
             continue;
         for (pos = line; !isspace(*pos); pos++);
         *pos = '\0';
         // TODO(geert): we assume ipv4 for now
         struct in_addr addr;
         if (!inet_aton(line, &addr))
             continue;
         pos++;
         for(; *pos && isspace(*pos); pos++);
         char *end;
         for(end = pos; *end && !isspace(*end); end++);
         struct dns_addr_buf buffer;
         memcpy(buffer.addr, &addr, 4);
         buffer.family = AF_INET;
         buffer.name = frg::string<MemoryAllocator>{pos,
             static_cast<size_t>(end - pos), getAllocator()};
         canon_name = buffer.name;
         buf.buf.push(std::move(buffer));
         pos = end;
         while (pos[1]) {
             for (; *pos && isspace(*pos); pos++);
             for (end = pos; *end && !isspace(*end); end++);
             auto name = frg::string<MemoryAllocator>{pos,
                 static_cast<size_t>(end - pos), getAllocator()};
             buf.aliases.push(std::move(name));
             pos = end;
         }
     }
     fclose(file);
     return buf.buf.size();
 }
References addr, mlibc::dns_addr_buf::addr, AF_INET, buf, EACCES, EAI_SERVICE, EAI_SYSTEM, ENOENT, ENOTDIR, errno, mlibc::dns_addr_buf::family, fclose(), fgets(), fopen(), getAllocator(), inet_aton(), isspace(), memcpy, mlibc::dns_addr_buf::name, name, strchr(), strlen(), and strstr().
Referenced by getaddrinfo(), and gethostbyname().
lookup_name_ip()
int mlibc::lookup_name_ip (struct lookup_result & buf, const char * name, int family)
Definition at line 454 of file lookup.cpp.
{
     if (family == AF_INET) {
         in_addr_t addr = 0;
         int res = inet_pton(AF_INET, name, &addr);
         if (res <= 0)
             return -EAI_NONAME;
         struct dns_addr_buf addr_buf;
         addr_buf.family = AF_INET;
         memcpy(&addr_buf.addr, &addr, 4);
         buf.buf.push_back(addr_buf);
         return 1;
     }
     if (family == AF_INET6) {
         struct in6_addr addr{0};
         int res = inet_pton(AF_INET6, name, &addr);
         if (res <= 0)
             return -EAI_NONAME;
         struct dns_addr_buf addr_buf;
         addr_buf.family = AF_INET6;
         memcpy(&addr_buf.addr, &addr, 16);
         buf.buf.push_back(addr_buf);
         return 1;
     }
     // If no family was specified we try ipv4 and then ipv6.
     in_addr_t addr4 = 0;
     int res = inet_pton(AF_INET, name, &addr4);
     if (res > 0) {
         struct dns_addr_buf addr_buf;
         addr_buf.family = AF_INET;
         memcpy(&addr_buf.addr, &addr4, 4);
         buf.buf.push_back(addr_buf);
         return 1;
     }
     struct in6_addr addr6{0};
     res = inet_pton(AF_INET6, name, &addr6);
     if (res <= 0)
         return -EAI_NONAME;
     struct dns_addr_buf addr_buf;
     addr_buf.family = AF_INET6;
     memcpy(&addr_buf.addr, &addr6, 16);
     buf.buf.push_back(addr_buf);
     return 1;
 }
References addr, mlibc::dns_addr_buf::addr, AF_INET, AF_INET6, buf, EAI_NONAME, mlibc::dns_addr_buf::family, inet_pton(), memcpy, and name.
Referenced by getaddrinfo().
lookup_name_null()
int mlibc::lookup_name_null (struct lookup_result & buf, int flags, int family)
Definition at line 411 of file lookup.cpp.
{
     if (flags & AI_PASSIVE) {
         if (family != AF_INET6) {
             struct dns_addr_buf addr_buf;
             addr_buf.family = AF_INET;
             in_addr_t addr = INADDR_ANY;
             memcpy(&addr_buf.addr, &addr, 4);
             buf.buf.push_back(addr_buf);
         }
         if (family != AF_INET) {
             struct dns_addr_buf addr_buf;
             addr_buf.family = AF_INET6;
             struct in6_addr addr = IN6ADDR_ANY_INIT;
             memcpy(&addr_buf.addr, &addr, 16);
             buf.buf.push_back(addr_buf);
         }
     } else {
         if (family != AF_INET6) {
             struct dns_addr_buf addr_buf;
             addr_buf.family = AF_INET;
             in_addr_t addr = INADDR_LOOPBACK;
             memcpy(&addr_buf.addr, &addr, 4);
             buf.buf.push_back(addr_buf);
         }
         if (family != AF_INET) {
             struct dns_addr_buf addr_buf;
             addr_buf.family = AF_INET6;
             struct in6_addr addr = IN6ADDR_LOOPBACK_INIT;
             memcpy(&addr_buf.addr, &addr, 16);
             buf.buf.push_back(addr_buf);
         }
     }
     return buf.buf.size();
 }
References addr, mlibc::dns_addr_buf::addr, AF_INET, AF_INET6, AI_PASSIVE, buf, mlibc::dns_addr_buf::family, flags, IN6ADDR_ANY_INIT, IN6ADDR_LOOPBACK_INIT, INADDR_ANY, INADDR_LOOPBACK, and memcpy.
Referenced by getaddrinfo().
lookup_serv_by_name()
int mlibc::lookup_serv_by_name (service_result & buf, const char * name, int proto, int socktype, int flags)
Definition at line 159 of file services.cpp.
{
     switch(socktype) {
         case SOCK_STREAM:
             if (!proto)
                 proto = IPPROTO_TCP;
             else if (proto != IPPROTO_TCP)
                 return -EAI_SERVICE;
             break;
         case SOCK_DGRAM:
             if (!proto)
                 proto = IPPROTO_UDP;
             else if (proto != IPPROTO_UDP)
                 return -EAI_SERVICE;
             break;
         case 0:
             break;
         default:
             if (name)
                 return -EAI_SERVICE;
             buf[0].port = 0;
             buf[0].socktype = socktype;
             buf[0].protocol = proto;
             return 1;
     }
     char *end = nullptr;
     unsigned int port = 0;
     int count = 0;
     if (name) {
         if (!*name)
             return -EAI_SERVICE;
         port = strtoul(name, &end, 10);
     }
     // The end pointer is a null pointer so the name was a port
     // or the name was not specified.
     if (!end || !*end) {
         if (proto != IPPROTO_UDP) {
             buf[count].port = port;
             buf[count].protocol = IPPROTO_TCP;
             buf[count].socktype = SOCK_STREAM;
             count++;
         }
         if (proto != IPPROTO_TCP) {
             buf[count].port = port;
             buf[count].protocol = IPPROTO_UDP;
             buf[count].socktype = SOCK_DGRAM;
             count++;
         }
         return count;
     }
     if (flags & AI_NUMERICSERV)
         return -EAI_NONAME;
     return lookup_serv_file_name(buf, name, proto);
 }
References AI_NUMERICSERV, buf, count, EAI_NONAME, EAI_SERVICE, flags, IPPROTO_TCP, IPPROTO_UDP, lookup_serv_file_name(), name, SOCK_DGRAM, SOCK_STREAM, and strtoul().
Referenced by getaddrinfo(), and getservbyname().
lookup_serv_by_port()
int mlibc::lookup_serv_by_port (service_result & buf, int proto, int port)
Definition at line 218 of file services.cpp.
{
     return lookup_serv_file_port(buf, proto, port);
 }
References buf, and lookup_serv_file_port().
Referenced by getservbyport().
lookup_serv_file_name()
static int mlibc::lookup_serv_file_name (service_result & buf, const char * name, int proto) static
Definition at line 97 of file services.cpp.
                    {
     auto file = fopen(_PATH_SERVICES, "r");
     if (!file) {
         switch (errno) {
             case ENOENT:
             case ENOTDIR:
             case EACCES:
                 return -EAI_SERVICE;
             default:
                 return -EAI_SYSTEM;
         }
     }
     char line[128];
     int name_length = strlen(name);
     while(fgets(line, 128, file)) {
         char *pos;
         // easy way to handle comments, just move the end of the line
         // to the beginning of the comment
         if ((pos = strchr(line, '#'))) {
             *pos++ = '\n';
             *pos = '\0';
         }
         for (pos = line; (pos = strstr(pos, name)); pos++) {
             // the name must start and end with a space
             if (pos > line && !isspace(pos[-1]))
                 continue;
             if (pos[name_length] && !isspace(pos[name_length]))
                 continue;
             break;
         }
         if (!pos)
             continue;
         // Skip the name at the beginning of the line.
         for(pos = line; *pos && !isspace(*pos); pos++)
             ;
         char *end = NULL;
         int port = strtoul(pos, &end, 10);
         if (port > 65535 || end == pos)
             continue;
         struct service_buf sbuf;
         sbuf.port = port;
         sbuf.name = frg::string<MemoryAllocator>(name, getAllocator());
         if (!parse_rest(sbuf, end, proto))
             continue;
         buf.push_back(sbuf);
     }
     fclose(file);
     return buf.size();
 }
References _PATH_SERVICES, buf, EACCES, EAI_SERVICE, EAI_SYSTEM, ENOENT, ENOTDIR, errno, fclose(), fgets(), fopen(), getAllocator(), isspace(), mlibc::service_buf::name, name, NULL, parse_rest(), mlibc::service_buf::port, strchr(), strlen(), strstr(), and strtoul().
Referenced by lookup_serv_by_name().
lookup_serv_file_port()
static int mlibc::lookup_serv_file_port (service_result & buf, int proto, int port) static
Definition at line 34 of file services.cpp.
{
     auto file = fopen(_PATH_SERVICES, "r");
     if (!file) {
         switch (errno) {
             case ENOENT:
             case ENOTDIR:
             case EACCES:
                 return -EAI_SERVICE;
             default:
                 return -EAI_SYSTEM;
         }
     }
     char line_buf[129] = {0};
     char *line = line_buf + 1;
     while(fgets(line, 128, file)) {
         int name_length = 0;
         char *pos;
         // easy way to handle comments, just move the end of the line
         // to the beginning of the comment
         if ((pos = strchr(line, '#'))) {
             *pos++ = '\n';
             *pos = '\0';
         }
         char *end = NULL;
         for (pos = line; *pos; pos++) {
             for (; isalpha(*pos); pos++);
             int rport = strtoul(pos, &end, 10);
             if (rport != port || rport > 65535) {
                 pos = end;
                 continue;
             }
             // We have found the port, time to rewind to the start
             // of the line.
             for (; pos[-1]; pos--)
                 if(!isspace(pos[-1]))
                     name_length++;
             break;
         }
         if (!pos)
             continue;
         if (!name_length)
             continue;
         auto name = frg::string<MemoryAllocator>(pos, name_length,
                 getAllocator());
         struct service_buf sbuf = {};
         sbuf.port = port;
         sbuf.name = std::move(name);
         if (!parse_rest(sbuf, end, proto))
             continue;
         buf.push_back(std::move(sbuf));
     }
     fclose(file);
     return buf.size();
 }
References _PATH_SERVICES, buf, EACCES, EAI_SERVICE, EAI_SYSTEM, ENOENT, ENOTDIR, errno, fclose(), fgets(), fopen(), getAllocator(), isalpha(), isspace(), mlibc::service_buf::name, name, NULL, parse_rest(), mlibc::service_buf::port, strchr(), and strtoul().
Referenced by lookup_serv_by_port().
nl_langinfo()
char * mlibc::nl_langinfo (nl_item item)
Definition at line 7 of file locale.cpp.
{
     if(item == CODESET) {
         return const_cast<char *>("UTF-8");
     } else if(item >= ABMON_1 && item <= ABMON_12) {
         switch(item) {
             case ABMON_1: return const_cast<char *>("Jan");
             case ABMON_2: return const_cast<char *>("Feb");
             case ABMON_3: return const_cast<char *>("Mar");
             case ABMON_4: return const_cast<char *>("Apr");
             case ABMON_5: return const_cast<char *>("May");
             case ABMON_6: return const_cast<char *>("Jun");
             case ABMON_7: return const_cast<char *>("Jul");
             case ABMON_8: return const_cast<char *>("Aug");
             case ABMON_9: return const_cast<char *>("Sep");
             case ABMON_10: return const_cast<char *>("Oct");
             case ABMON_11: return const_cast<char *>("Nov");
             case ABMON_12: return const_cast<char *>("Dec");
             default:
                 __ensure(!"ABMON_* constants don't seem to be contiguous!");
                 __builtin_unreachable();
         }
     } else if(item >= MON_1 && item <= MON_12) {
         switch(item) {
             case MON_1: return const_cast<char *>("January");
             case MON_2: return const_cast<char *>("Feburary");
             case MON_3: return const_cast<char *>("March");
             case MON_4: return const_cast<char *>("April");
             case MON_5: return const_cast<char *>("May");
             case MON_6: return const_cast<char *>("June");
             case MON_7: return const_cast<char *>("July");
             case MON_8: return const_cast<char *>("August");
             case MON_9: return const_cast<char *>("September");
             case MON_10: return const_cast<char *>("October");
             case MON_11: return const_cast<char *>("November");
             case MON_12: return const_cast<char *>("December");
             default:
                 __ensure(!"MON_* constants don't seem to be contiguous!");
                 __builtin_unreachable();
         }
     } else if(item == AM_STR) {
         return const_cast<char *>("AM");
     } else if(item == PM_STR) {
         return const_cast<char *>("PM");
     } else if(item >= DAY_1 && item <= DAY_7) {
         switch(item) {
             case DAY_1: return const_cast<char *>("Sunday");
             case DAY_2: return const_cast<char *>("Monday");
             case DAY_3: return const_cast<char *>("Tuesday");
             case DAY_4: return const_cast<char *>("Wednesday");
             case DAY_5: return const_cast<char *>("Thursday");
             case DAY_6: return const_cast<char *>("Friday");
             case DAY_7: return const_cast<char *>("Saturday");
             default:
                 __ensure(!"DAY_* constants don't seem to be contiguous!");
                 __builtin_unreachable();
         }
     } else if(item >= ABDAY_1 && item <= ABDAY_7) {
         switch(item) {
             case ABDAY_1: return const_cast<char *>("Sun");
             case ABDAY_2: return const_cast<char *>("Mon");
             case ABDAY_3: return const_cast<char *>("Tue");
             case ABDAY_4: return const_cast<char *>("Wed");
             case ABDAY_5: return const_cast<char *>("Thu");
             case ABDAY_6: return const_cast<char *>("Fri");
             case ABDAY_7: return const_cast<char *>("Sat");
             default:
                 __ensure(!"ABDAY_* constants don't seem to be contiguous!");
                 __builtin_unreachable();
         }
     }else if(item == D_FMT) {
         return const_cast<char *>("%m/%d/%y");
     }else if(item == T_FMT) {
         return const_cast<char *>("%H:%M:%S");
     }else{
         mlibc::infoLogger() << "mlibc: nl_langinfo item "
                 << item << " is not implemented properly" << frg::endlog;
         return const_cast<char *>("");
     }
 }
References __ensure, ABDAY_1, ABDAY_2, ABDAY_3, ABDAY_4, ABDAY_5, ABDAY_6, ABDAY_7, ABMON_1, ABMON_10, ABMON_11, ABMON_12, ABMON_2, ABMON_3, ABMON_4, ABMON_5, ABMON_6, ABMON_7, ABMON_8, ABMON_9, AM_STR, CODESET, D_FMT, DAY_1, DAY_2, DAY_3, DAY_4, DAY_5, DAY_6, DAY_7, infoLogger, MON_1, MON_10, MON_11, MON_12, MON_2, MON_3, MON_4, MON_5, MON_6, MON_7, MON_8, MON_9, PM_STR, and T_FMT.
Referenced by nl_langinfo(), strftime(), and anonymous_namespace{time.cpp}::strptime_internal().
parse_exec_stack()
void mlibc::parse_exec_stack (void * opaque_sp, exec_stack_data * data)
Definition at line 40 of file startup.cpp.
{
     auto sp = reinterpret_cast<uintptr_t *>(opaque_sp);
     data->argc = *sp++;
     data->argv = reinterpret_cast<char **>(sp);
     sp += data->argc; // Skip all arguments.
     __ensure(!*sp); // Skip the terminating null element.
     sp++;
     data->envp = reinterpret_cast<char **>(sp);
 }
References __ensure, mlibc::exec_stack_data::argc, mlibc::exec_stack_data::argv, and mlibc::exec_stack_data::envp.
Referenced by LibraryGuard::LibraryGuard().
parse_rest()
static int mlibc::parse_rest (service_buf & buf, char * end, int proto) static
Definition at line 14 of file services.cpp.
{
     if (!strncmp(end, "/udp", 4)) {
         if (proto == IPPROTO_TCP && proto != -1)
             return 0;
         buf.protocol = IPPROTO_UDP;
         buf.socktype = SOCK_DGRAM;
     } else if (!strncmp(end, "/tcp", 4)) {
         if (proto == IPPROTO_UDP && proto != -1)
             return 0;
         buf.protocol = IPPROTO_TCP;
         buf.socktype = SOCK_STREAM;
     } else {
         return 0;
     }
     //TODO(geert): also parse aliases.
     return 1;
 }
References buf, IPPROTO_TCP, IPPROTO_UDP, SOCK_DGRAM, SOCK_STREAM, and strncmp().
Referenced by lookup_serv_file_name(), and lookup_serv_file_port().
platform_wide_charcode()
wide_charcode * mlibc::platform_wide_charcode ()
Definition at line 238 of file charcode.cpp.
{
     static wide_charcode global_wide_charcode;
     return &global_wide_charcode;
 }
Referenced by iswalnum(), iswalpha(), iswblank(), iswcntrl(), iswdigit(), iswgraph(), iswlower(), iswprint(), iswpunct(), iswspace(), iswupper(), iswxdigit(), towlower(), and towupper().
prepare_stack() [1/3]
int mlibc::prepare_stack (void ** stack, void * entry, void * user_arg, void * tcb, size_t * stack_size, size_t * guard_size)
prepare_stack() [2/3]
void* mlibc::prepare_stack (void * entry, void * user_arg)
prepare_stack() [3/3]
void * mlibc::prepare_stack (void * entry, void * user_arg, void * tcb)
putenv()
int mlibc::putenv (char * string)
Definition at line 111 of file environment.cpp.
{
     frg::string_view view{string};
     size_t s = view.find_first('=');
     if(s == size_t(-1))
         __ensure(!"Environment strings need to contain an equals sign");
     update_vector();
     assign_variable(view.sub_string(0, s), string, true);
     return 0;
 }
References __ensure, anonymous_namespace{environment.cpp}::assign_variable(), and anonymous_namespace{environment.cpp}::update_vector().
Referenced by set_startup_data().
query_locale_description()
const locale_description* mlibc::query_locale_description (const char * name)
Definition at line 58 of file locale-stubs.cpp.
{
         if(!strcmp(name, "C"))
             return &c_locale;
         if(!strcmp(name, "POSIX"))
             return &posix_locale;
         return nullptr;
     }
References c_locale, name, posix_locale, and strcmp().
Referenced by setlocale().
read_dns_name()
static frg::string<MemoryAllocator> mlibc::read_dns_name (char * buf, char *& it) static
Definition at line 23 of file lookup.cpp.
{
     frg::string<MemoryAllocator> res{getAllocator()};
     while (true) {
         char code = *it++;
         if ((code & 0xC0) == 0xC0) {
             // pointer
             uint8_t offset = ((code & 0x3F) << 8) | *it++;
             auto offset_it = buf + offset;
             return res + read_dns_name(buf, offset_it);
         } else if (!(code & 0xC0)) {
             if (!code)
                 break;
             for (int i = 0; i < code; i++)
                 res += (*it++);
             if (*it)
                 res += '.';
         } else {
             break;
         }
     }
     return res;
 }
References buf, getAllocator(), i, and offset.
Referenced by lookup_addr_dns(), and lookup_name_dns().
rtdlConfig()
const RtdlConfig& mlibc::rtdlConfig () inline
Definition at line 17 of file rtdl-config.hpp.
{
     return __dlapi_get_config();
 }
References __dlapi_get_config().
Referenced by secure_getenv().
sc_cast() [1/2]
sc_word_t mlibc::sc_cast (const void * x) inline
Definition at line 76 of file cxx-syscall.hpp.
 { return reinterpret_cast<sc_word_t>(x); }
References x.
sc_cast() [2/2]
sc_word_t mlibc::sc_cast (long x) inline
Definition at line 75 of file cxx-syscall.hpp.
 { return x; }
References x.
Referenced by do_cp_syscall(), and do_syscall().
sc_error()
int mlibc::sc_error (sc_result_t ret) inline
Definition at line 83 of file cxx-syscall.hpp.
{
         auto v = static_cast<sc_word_t>(ret);
         if(static_cast<unsigned long>(v) > -4096UL)
             return -v;
         return 0;
     }
References ret.
Referenced by do_cp_syscall(), sys_clock_getres(), sys_fadvise(), sys_fchmod(), sys_fchmodat(), sys_fchownat(), sys_fdatasync(), sys_fgetxattr(), sys_flistxattr(), sys_fremovexattr(), sys_fsetxattr(), sys_fstatfs(), sys_fsync(), sys_ftruncate(), sys_getgroups(), sys_getrandom(), sys_getrlimit(), sys_getsid(), sys_getxattr(), sys_lgetxattr(), sys_listxattr(), sys_llistxattr(), sys_lremovexattr(), sys_lsetxattr(), sys_mkdirat(), sys_mknodat(), sys_openat(), sys_readv(), sys_removexattr(), sys_renameat(), sys_setrlimit(), sys_setxattr(), sys_sigaltstack(), sys_sigsuspend(), sys_sigtimedwait(), sys_statfs(), sys_symlink(), sys_symlinkat(), sys_times(), sys_umask(), and sys_utimensat().
sc_int_result()
template<typename T > T mlibc::sc_int_result (sc_result_t ret)
Definition at line 108 of file cxx-syscall.hpp.
{
         auto v = static_cast<sc_word_t>(ret);
         return v;
     }
References ret.
sc_ptr_result()
template<typename T > T* mlibc::sc_ptr_result (sc_result_t ret)
Definition at line 114 of file cxx-syscall.hpp.
{
         auto v = static_cast<sc_word_t>(ret);
         return reinterpret_cast<T *>(v);
     }
References ret, and T.
set_startup_data()
void mlibc::set_startup_data (int argc, char ** argv, char ** envp)
Definition at line 51 of file startup.cpp.
{
     if(argc) {
         program_invocation_name = argv[0];
         if(auto slash = strrchr(argv[0], '/'); slash) {
             program_invocation_short_name = slash + 1;
         }else{
             program_invocation_short_name = argv[0];
         }
     }
     // Initialize environ.
     // TODO: Copy the arguments instead of pointing to them?
     auto ev = envp;
     while(*ev) {
         auto fail = mlibc::putenv(*ev);
         __ensure(!fail);
         ev++;
     }
 }
References __ensure, program_invocation_name, program_invocation_short_name, putenv(), and strrchr().
Referenced by LibraryGuard::LibraryGuard().
stringToInteger()
template<typename Return , typename Char > Return mlibc::stringToInteger (const Char *__restrict nptr, Char **__restrict endptr, int baseInt)
Definition at line 60 of file strtol.hpp.
{
     using UnsignedReturn = std::make_unsigned_t<Return>;
     auto base = static_cast<Return>(baseInt);
     auto s = nptr;
     if (base < 0 || base == 1) {
         if (endptr)
             *endptr = const_cast<Char *>(nptr);
         return 0;
     }
     while (char_detail<Char>::isSpace(*s))
         s++;
     bool negative = false;
     if (*s == widen<Char>('-')) {
         negative = true;
         s++;
     } else if (*s == widen<Char>('+')) {
         s++;
     }
     bool hasOctalPrefix = s[0] == widen<Char>('0');
     bool hasHexPrefix = hasOctalPrefix && (s[1] == widen<Char>('x') || s[1] == widen<Char>('X'));
     // There's two tricky cases we need to keep in mind here:
     //   1. We should interpret "0x5" as hex 5 rather than octal 0.
     //   2. We should interpret "0x" as octal 0 (and set endptr correctly).
     // To deal with 2, we check the charcacter following the hex prefix.
     if ((base == 0 || base == 16) && hasHexPrefix && char_detail<Char>::isHexDigit(s[2])) {
         s += 2;
         base = 16;
     } else if ((base == 0 || base == 8) && hasOctalPrefix) {
         base = 8;
     } else if (base == 0) {
         base = 10;
     }
     // Compute the range of acceptable values.
     UnsignedReturn cutoff, cutlim;
     if (std::is_unsigned_v<Return>) {
         cutoff = int_limits<Return>::max() / base;
         cutlim = int_limits<Return>::max() % base;
     } else {
         Return co = negative ? int_limits<Return>::min() : int_limits<Return>::max();
         cutlim = negative ? -(co % base) : co % base;
         co /= negative ? -base : base;
         cutoff = co;
     }
     UnsignedReturn totalValue = 0;
     bool convertedAny = false;
     bool outOfRange = false;
     for (Char c = *s; c != widen<Char>('\0'); c = *++s) {
         UnsignedReturn digitValue;
         if (char_detail<Char>::isDigit(c))
             digitValue = c - widen<Char>('0');
         else if (char_detail<Char>::isUpper(c))
             digitValue = c - widen<Char>('A') + 10;
         else if (char_detail<Char>::isLower(c))
             digitValue = c - widen<Char>('a') + 10;
         else
             break;
         if (digitValue >= static_cast<UnsignedReturn>(base))
             break;
         if (outOfRange) {
             // The value is already known to be out of range, but we need to keep
             // consuming characters until we can't (to set endptr correctly).
         } else if (totalValue > cutoff || (totalValue == cutoff && digitValue > cutlim)) {
             // The value will be out of range if we accumulate digitValue.
             outOfRange = true;
         } else {
             totalValue = (totalValue * base) + digitValue;
             convertedAny = true;
         }
     }
     if (endptr)
         *endptr = const_cast<Char *>(convertedAny ? s : nptr);
     if (outOfRange) {
         errno = ERANGE;
         if (std::is_unsigned_v<Return>) {
             return int_limits<Return>::max();
         } else {
             return negative ? int_limits<Return>::min() : int_limits<Return>::max();
         }
     }
     return negative ? -totalValue : totalValue;
 }
References base, c, endptr, ERANGE, and errno.
strncasecmp()
int mlibc::strncasecmp (const char * a, const char * b, size_t size)
Definition at line 7 of file strings.cpp.
{
     for(size_t i = 0; i < size; i++) {
         unsigned char a_byte = tolower(a[i]);
         unsigned char b_byte = tolower(b[i]);
         if(!a_byte && !b_byte)
             return 0;
         // If only one char is null, one of the following cases applies.
         if(a_byte < b_byte)
             return -1;
         if(a_byte > b_byte)
             return 1;
     }
     return 0;
 }
References b, i, size, and tolower.
Referenced by strncasecmp(), and anonymous_namespace{time.cpp}::strptime_internal().
strtofp()
template<typename T > T mlibc::strtofp (const char * str, char ** endptr)
Definition at line 10 of file strtofp.hpp.
{
     bool negative = *str == '-';
     if (*str == '+' || *str == '-')
         str++;
     if (*str == '0' && (*(str + 1) == 'x' || *(str + 1) == 'X'))
         __ensure(!"hex numbers in strtofp are unsupported");
     T result = static_cast<T>(0);
     const char *tmp = str;
     while (true) {
         if (!isdigit(*tmp))
             break;
         result *= static_cast<T>(10);
         result += static_cast<T>(*tmp - '0');
         tmp++;
     }
     if (*tmp == '.') {
         T d = static_cast<T>(10);
         if (*(tmp + 1) == '0' && (*(tmp + 2) == 'x' || *(tmp + 2) == 'X'))
             __ensure(!"hex numbers in strtofp are unsupported");
         tmp++;
         while (true) {
             if (!isdigit(*tmp))
                 break;
             result += static_cast<T>(*tmp - '0') / d;
             d *= static_cast<T>(10);
             tmp++;
         }
     }
     if (endptr)
         *endptr = const_cast<char *>(tmp);
     if (negative)
         result = -result;
     return result;
 }
References __ensure, endptr, isdigit(), result, and T.
sys_accept()
int mlibc::sys_accept (int fd, int * newfd, struct sockaddr * addr_ptr, socklen_t * addr_length)
Definition at line 52 of file sockets.cpp.
{
     auto result = syscall(SYS_ACCEPT, sockfd, addr_ptr, addr_length);
     if (result < 0) {
         return -result;
     }
     *newfd = result;
     return 0;
 }
References result, SYS_ACCEPT, and syscall.
Referenced by accept(), and accept4().
sys_access()
int mlibc::sys_access (const char * path, int mode)
Definition at line 82 of file filesystem.cpp.
{
     auto result =
         syscall(SYS_ACCESS, AT_FDCWD, filename, strlen(filename), mode, 0);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References AT_FDCWD, result, strlen(), SYS_ACCESS, and syscall.
Referenced by access().
sys_anon_allocate()
int mlibc::sys_anon_allocate (size_t size, void ** pointer)
Definition at line 129 of file aero.cpp.
{
     return sys_vm_map(nullptr, size, PROT_READ | PROT_WRITE,
                       MAP_PRIVATE | MAP_ANONYMOUS, -1, 0, pointer);
 }
References MAP_ANONYMOUS, MAP_PRIVATE, PROT_READ, PROT_WRITE, size, and sys_vm_map().
Referenced by VirtualAllocator::map().
sys_anon_free()
int mlibc::sys_anon_free (void * pointer, size_t size)
Definition at line 134 of file aero.cpp.
{
     return sys_vm_unmap(pointer, size);
 }
References size, and sys_vm_unmap().
Referenced by VirtualAllocator::unmap().
sys_before_cancellable_syscall()
int mlibc::sys_before_cancellable_syscall (ucontext_t * uctx)
Referenced by anonymous_namespace{pthread-stubs.cpp}::sigcancel_handler().
sys_bind()
int mlibc::sys_bind (int fd, const struct sockaddr * addr_ptr, socklen_t addr_length)
Definition at line 21 of file sockets.cpp.
{
     auto result = syscall(SYS_BIND, fd, addr_ptr, (sc_word_t)addr_length);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References fd, result, SYS_BIND, and syscall.
Referenced by bind().
sys_chdir()
int mlibc::sys_chdir (const char * path)
Definition at line 210 of file aero.cpp.
{
     auto result = syscall(SYS_CHDIR, path, strlen(path));
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References path, result, strlen(), SYS_CHDIR, and syscall.
Referenced by chdir().
sys_chmod()
int mlibc::sys_chmod (const char * pathname, mode_t mode)
Definition at line 343 of file filesystem.cpp.
{
     int ret = syscall(SYS_CHMOD, pathname, mode);
     if(ret < 0){
         return -ret;
     }
     return 0;
 }
References ret, SYS_CHMOD, and syscall.
Referenced by chmod().
sys_chroot()
int mlibc::sys_chroot (const char * path)
Definition at line 78 of file file.cpp.
{
     SignalGuard sguard;
     managarm::posix::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_request_type(managarm::posix::CntReqType::CHROOT);
     req.set_path(frg::string<MemoryAllocator>(getSysdepsAllocator(), path));
     auto [offer, send_req, recv_resp] = exchangeMsgsSync(
         getPosixLane(),
         helix_ng::offer(
             helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
             helix_ng::recvInline())
     );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_req.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
     return 0;
 }
References __ensure, exchangeMsgsSync(), getPosixLane(), getSysdepsAllocator(), and path.
Referenced by chroot().
sys_clock_get()
int mlibc::sys_clock_get (int clock, time_t * secs, long * nanos)
Definition at line 186 of file aero.cpp.
{
     struct timespec ts;
     auto result = syscall(SYS_GETTIME, clock, &ts);
     if (result < 0) {
         return -result;
     }
     *secs = ts.tv_sec;
     *nanos = ts.tv_nsec;
     return 0;
 }
References clock(), nanos, result, secs, SYS_GETTIME, syscall, timespec::tv_nsec, and timespec::tv_sec.
Referenced by clock_gettime(), gettimeofday(), pthread_cond_timedwait(), and time().
sys_clock_getres()
int mlibc::sys_clock_getres (int clock, time_t * secs, long * nanos)
Definition at line 204 of file sysdeps.cpp.
{
     struct timespec tp = {};
     auto ret = do_syscall(SYS_clock_getres, clock, &tp);
     if (int e = sc_error(ret); e)
         return e;
     *secs = tp.tv_sec;
     *nanos = tp.tv_nsec;
     return 0;
 }
References clock(), do_syscall(), nanos, ret, sc_error(), secs, timespec::tv_nsec, and timespec::tv_sec.
Referenced by clock_getres().
sys_clone()
int mlibc::sys_clone (void * tcb, pid_t * pid_out, void * stack)
Definition at line 284 of file aero.cpp.
{
     auto result = syscall(SYS_CLONE, (uintptr_t)__mlibc_start_thread, stack);
     if (result < 0) {
         return -result;
     }
     *tid_out = (pid_t)result;
     return 0;
 }
References __mlibc_start_thread(), result, SYS_CLONE, and syscall.
Referenced by pthread_create().
sys_close()
int mlibc::sys_close (int fd)
Definition at line 72 of file filesystem.cpp.
                       {
     auto result = syscall(SYS_CLOSE, fd);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References fd, result, SYS_CLOSE, and syscall.
Referenced by mlibc::fd_file::close(), close(), closeOrDie(), file_window::file_window(), forkpty(), login_tty(), and popen().
sys_connect()
int mlibc::sys_connect (int fd, const struct sockaddr * addr_ptr, socklen_t addr_length)
Definition at line 31 of file sockets.cpp.
{
     auto result = syscall(SYS_CONNECT, fd, addr_ptr, (sc_word_t)addr_length);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References fd, result, SYS_CONNECT, and syscall.
Referenced by connect().
sys_delete_module()
int mlibc::sys_delete_module (const char * name, unsigned flags)
Referenced by delete_module().
sys_dup()
int mlibc::sys_dup (int fd, int flags, int * newfd)
Definition at line 275 of file filesystem.cpp.
{
     auto result = syscall(SYS_DUP, fd, flags);
     if (result < 0) {
         return -result;
     }
     *newfd = result;
     return 0;
 }
References fd, flags, result, SYS_DUP, and syscall.
Referenced by dup().
sys_dup2()
int mlibc::sys_dup2 (int fd, int flags, int newfd)
Definition at line 286 of file filesystem.cpp.
{
     auto result = syscall(SYS_DUP2, fd, newfd, flags);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References fd, flags, result, SYS_DUP2, and syscall.
Referenced by dup2(), login_tty(), and popen().
sys_epoll_create()
int mlibc::sys_epoll_create (int flags, int * fd)
Definition at line 320 of file filesystem.cpp.
{
     auto result = syscall(SYS_EPOLL_CREATE, flags);
     if (result < 0) {
         return -result;
     }
     *fd = result;
     return 0;
 }
References fd, flags, result, SYS_EPOLL_CREATE, and syscall.
Referenced by epoll_create(), and epoll_create1().
sys_epoll_ctl()
int mlibc::sys_epoll_ctl (int epfd, int mode, int fd, struct epoll_event * ev)
Definition at line 331 of file filesystem.cpp.
{
     auto result = syscall(SYS_EPOLL_CTL, epfd, mode, fd, ev);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References fd, result, SYS_EPOLL_CTL, and syscall.
Referenced by epoll_ctl().
sys_epoll_pwait()
int mlibc::sys_epoll_pwait (int epfd, struct epoll_event * ev, int n, int timeout, const sigset_t * sigmask, int * raised)
Definition at line 341 of file filesystem.cpp.
{
     auto result = syscall(SYS_EPOLL_PWAIT, epfd, ev, n, timeout, sigmask);
     if (result < 0) {
         return -result;
     }
     *raised = result;
     return 0;
 }
References n, result, sigmask, SYS_EPOLL_PWAIT, syscall, and timeout.
Referenced by epoll_pwait(), and epoll_wait().
sys_eventfd_create()
int mlibc::sys_eventfd_create (unsigned int initval, int flags, int * fd)
Definition at line 353 of file filesystem.cpp.
{
     auto result = syscall(SYS_EVENT_FD, initval, flags);
     if (result < 0) {
         return -result;
     }
     *fd = result;
     return 0;
 }
References fd, flags, result, SYS_EVENT_FD, and syscall.
Referenced by eventfd().
sys_execve()
int mlibc::sys_execve (const char * path, char *const argv[], char *const envp[])
Definition at line 327 of file aero.cpp.
{
     auto envv_slice = create_slice(envp);
     auto argv_slice = create_slice(argv);
     auto path_ptr = (uintptr_t)path;
     auto path_len = strlen(path);
     auto result =
         syscall(SYS_EXEC, path_ptr, path_len, argv_slice.data(),
                 argv_slice.size(), envv_slice.data(), envv_slice.size());
     if (result < 0) {
         return -result;
     }
     __builtin_unreachable();
 }
References create_slice(), path, result, strlen(), SYS_EXEC, and syscall.
Referenced by execve(), execvpe(), popen(), and system().
sys_exit()
void mlibc::sys_exit (int status)
Definition at line 147 of file aero.cpp.
{
     syscall(SYS_EXIT, status);
     __builtin_unreachable();
 }
References status, SYS_EXIT, and syscall.
Referenced by __mlibc_sigentry(), _Exit(), _exit(), exit(), and sys_libc_panic().
sys_faccessat()
int mlibc::sys_faccessat (int dirfd, const char * pathname, int mode, int flags)
Definition at line 537 of file generic.cpp.
{
     (void)flags;
     struct stat buf;
     if (int r = sys_stat(fsfd_target::fd_path, dirfd, pathname, mode & AT_SYMLINK_FOLLOW, &buf)) {
         return r;
     }
     return 0;
 }
References AT_SYMLINK_FOLLOW, buf, dirfd(), fd_path, flags, r, sys_stat(), and Driver::void().
Referenced by faccessat().
sys_fadvise()
int mlibc::sys_fadvise (int fd, off_t offset, off_t length, int advice)
Definition at line 70 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_fadvise64, fd, offset, length, advice);
     if(int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), fd, offset, ret, and sc_error().
Referenced by posix_fadvise().
sys_fallocate()
int mlibc::sys_fallocate (int fd, off_t offset, size_t size)
Definition at line 2100 of file file.cpp.
{
     SignalGuard sguard;
     auto handle = getHandleForFd(fd);
     if (!handle)
         return EBADF;
     managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_req_type(managarm::fs::CntReqType::PT_FALLOCATE);
     req.set_rel_offset(offset);
     req.set_size(size);
     auto [offer, send_req, recv_resp] = exchangeMsgsSync(
         handle,
         helix_ng::offer(
             helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
             helix_ng::recvInline())
     );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_req.error());
     HEL_CHECK(recv_resp.error());
     managarm::fs::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     if(resp.error() == managarm::fs::Errors::ILLEGAL_OPERATION_TARGET) {
         return EINVAL;
     }else if(resp.error() == managarm::fs::Errors::INSUFFICIENT_PERMISSIONS) {
         return EPERM;
     }else if(resp.error() == managarm::fs::Errors::ILLEGAL_ARGUMENT) {
         return EINVAL;
     }else{
         __ensure(resp.error() == managarm::fs::Errors::SUCCESS);
         return 0;
     }
     return 0;
 }
References __ensure, EBADF, EINVAL, EPERM, exchangeMsgsSync(), fd, getHandleForFd(), getSysdepsAllocator(), offset, and size.
Referenced by posix_fallocate().
sys_fchdir()
int mlibc::sys_fchdir (int fd)
Definition at line 429 of file filesystem.cpp.
{
     return syscall(SYS_FCHDIR, fd);
 }
References fd, SYS_FCHDIR, and syscall.
Referenced by fchdir().
sys_fchmod()
int mlibc::sys_fchmod (int fd, mode_t mode)
Definition at line 146 of file sysdeps.cpp.
{
     auto ret = do_cp_syscall(SYS_fchmod, fd, mode);
     if(int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_cp_syscall(), fd, ret, and sc_error().
Referenced by fchmod().
sys_fchmodat()
int mlibc::sys_fchmodat (int fd, const char * pathname, mode_t mode, int flags)
Definition at line 153 of file sysdeps.cpp.
{
     auto ret = do_cp_syscall(SYS_fchmodat, fd, pathname, mode, flags);
     if(int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_cp_syscall(), fd, flags, ret, sc_error(), and SYS_fchmodat.
Referenced by fchmodat().
sys_fchownat()
int mlibc::sys_fchownat (int dirfd, const char * pathname, uid_t owner, gid_t group, int flags)
Definition at line 160 of file sysdeps.cpp.
{
     auto ret = do_cp_syscall(SYS_fchownat, dirfd, pathname, owner, group, flags);
     if(int e = sc_error(ret); e)
         return e;
     return 0;
 }
References dirfd(), do_cp_syscall(), flags, ret, and sc_error().
Referenced by chown(), fchown(), fchownat(), and lchown().
sys_fcntl()
int mlibc::sys_fcntl (int fd, int request, va_list args, int * result)
Definition at line 296 of file filesystem.cpp.
{
     auto result = syscall(SYS_FCNTL, fd, request, va_arg(args, uint64_t));
     if (result < 0) {
         return -result;
     }
     *result_value = result;
     return 0;
 }
References fd, request, result, SYS_FCNTL, syscall, and va_arg.
Referenced by fcntl().
sys_fdatasync()
int mlibc::sys_fdatasync (int fd)
Definition at line 1434 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_fdatasync, fd);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), fd, ret, and sc_error().
Referenced by fdatasync().
sys_fgetxattr()
int mlibc::sys_fgetxattr (int fd, const char * name, void * val, size_t size, ssize_t * nread)
Definition at line 1494 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_fgetxattr, fd, name, val, size);
     if (int e = sc_error(ret); e) {
         return e;
     }
     *nread = sc_int_result<ssize_t>(ret);
     return 0;
 }
References do_syscall(), fd, name, ret, sc_error(), and size.
Referenced by fgetxattr().
sys_flistxattr()
int mlibc::sys_flistxattr (int fd, char * list, size_t size, ssize_t * nread)
Definition at line 1540 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_flistxattr, fd, list, size);
     if (int e = sc_error(ret); e) {
         return e;
     }
     *nread = sc_int_result<ssize_t>(ret);
     return 0;
 }
References do_syscall(), fd, ret, sc_error(), and size.
Referenced by flistxattr().
sys_flock()
int mlibc::sys_flock (int fd, int options)
Definition at line 2211 of file file.cpp.
{
     SignalGuard sguard;
     managarm::fs::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_req_type(managarm::fs::CntReqType::FLOCK);
     req.set_fd(fd);
     req.set_flock_flags(opts);
     auto handle = getHandleForFd(fd);
     if(!handle) {
         return EBADF;
     }
     auto [offer, send_req, recv_resp] = exchangeMsgsSync(
         handle,
         helix_ng::offer(
             helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
             helix_ng::recvInline())
     );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_req.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     if(resp.error() == managarm::posix::Errors::WOULD_BLOCK) {
         return EWOULDBLOCK;
     }else if(resp.error() == managarm::posix::Errors::ILLEGAL_ARGUMENTS) {
         return EINVAL;
     } else {
         __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
         return 0;
     }
 }
References __ensure, EBADF, EINVAL, EWOULDBLOCK, exchangeMsgsSync(), fd, getHandleForFd(), and getSysdepsAllocator().
Referenced by flock().
sys_fork()
int mlibc::sys_fork (pid_t * child)
Definition at line 316 of file aero.cpp.
{
     auto result = syscall(SYS_FORK);
     if (result < 0) {
         return -result;
     }
     *child = result;
     return 0;
 }
References child, result, SYS_FORK, and syscall.
Referenced by fork(), forkpty(), popen(), system(), and vfork().
sys_fremovexattr()
int mlibc::sys_fremovexattr (int fd, const char * name)
Definition at line 1515 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_fremovexattr, fd, name);
     return sc_error(ret);
 }
References do_syscall(), fd, name, ret, and sc_error().
Referenced by fremovexattr().
sys_fsetxattr()
int mlibc::sys_fsetxattr (int fd, const char * name, const void * val, size_t size, int flags)
Definition at line 1466 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_fsetxattr, fd, name, val, size, flags);
     return sc_error(ret);
 }
References do_syscall(), fd, flags, name, ret, sc_error(), and size.
Referenced by fsetxattr().
sys_fstatfs()
int mlibc::sys_fstatfs (int fd, struct statfs * buf)
Definition at line 235 of file sysdeps.cpp.
{
     auto ret = do_cp_syscall(SYS_fstatfs, fd, buf);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References buf, do_cp_syscall(), fd, ret, and sc_error().
Referenced by fstatfs().
sys_fstatvfs()
int mlibc::sys_fstatvfs (int fd, struct statvfs * out)
Referenced by fstatvfs().
sys_fsync()
int mlibc::sys_fsync (int fd)
Definition at line 1427 of file sysdeps.cpp.
                       {
     auto ret = do_syscall(SYS_fsync, fd);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), fd, ret, and sc_error().
Referenced by fsync().
sys_ftruncate()
int mlibc::sys_ftruncate (int fd, size_t size)
Definition at line 1326 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_ftruncate, fd, size);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), fd, ret, sc_error(), and size.
Referenced by ftruncate().
sys_futex_tid()
int mlibc::sys_futex_tid ()
Definition at line 13 of file lemon.cpp.
                    {
     return syscall(SYS_GETTID);
 }
References SYS_GETTID, and syscall.
Referenced by this_tid().
sys_futex_wait()
int mlibc::sys_futex_wait (int * pointer, int expected, const struct timespec * time)
Definition at line 75 of file aero.cpp.
{
     // auto result = syscall(SYS_FUTEX_WAIT, pointer, expected, time);
     //
     // if (result < 0) {
     //     return -result;
     // }
     //
     return 0;
 }
Referenced by __mlibc_enter_thread(), __mlibc_thread_trampoline(), FutexLockImpl< Recursive >::lock(), pthread_barrier_destroy(), pthread_barrier_wait(), pthread_cond_timedwait(), pthread_join(), pthread_mutex_lock(), pthread_once(), pthread_rwlock_wrlock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock(), and sem_wait().
sys_futex_wake()
int mlibc::sys_futex_wake (int * pointer)
Definition at line 85 of file aero.cpp.
{
     // auto result = syscall(SYS_FUTEX_WAKE, pointer);
     //
     // if (result < 0) {
     //     return -result;
     // }
     //
     return 0;
 }
Referenced by __mlibc_enter_thread(), __mlibc_thread_trampoline(), pthread_barrier_wait(), pthread_cond_broadcast(), pthread_create(), pthread_exit(), pthread_mutex_unlock(), pthread_once(), pthread_rwlock_unlock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), sem_post(), and FutexLockImpl< Recursive >::unlock().
sys_get_min_priority()
int mlibc::sys_get_min_priority (int policy, int * out)
Referenced by sched_get_priority_min().
sys_getaffinity()
int mlibc::sys_getaffinity (pid_t pid, size_t cpusetsize, cpu_set_t * mask)
Referenced by sched_getaffinity().
sys_getcpu()
int mlibc::sys_getcpu (int * cpu)
Referenced by sched_getcpu().
sys_getcwd() [1/2]
int mlibc::sys_getcwd (char * buffer, size_t size)
Definition at line 200 of file aero.cpp.
{
     auto result = syscall(SYS_GETCWD, buffer, size);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References result, size, SYS_GETCWD, and syscall.
Referenced by getcwd(), and realpath().
sys_getcwd() [2/2]
int mlibc::sys_getcwd (const char * buff, size_t size)
Definition at line 293 of file generic.cpp.
{
     char* ret;
     int errno;
     SYSCALL2(SYSCALL_GETCWD, buff, size);
     if (ret == NULL) {
         return errno;
     }
     return 0;
 }
References errno, NULL, ret, size, SYSCALL2, and SYSCALL_GETCWD.
sys_getegid()
gid_t mlibc::sys_getegid (void)
Definition at line 264 of file aero.cpp.
                     {
     mlibc::infoLogger() << "mlibc: sys_getegid is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by getegid().
sys_getentropy()
int mlibc::sys_getentropy (void * buffer, size_t length)
Definition at line 194 of file lemon.cpp.
{
     return -syscall(SYS_GETENTROPY, buffer, length);
 }
References SYS_GETENTROPY, and syscall.
Referenced by getentropy(), and getrandom().
sys_geteuid()
uid_t mlibc::sys_geteuid (void)
Definition at line 247 of file aero.cpp.
                     {
     mlibc::infoLogger() << "mlibc: sys_seteuid is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by geteuid().
sys_getgid()
gid_t mlibc::sys_getgid (void)
Definition at line 199 of file generic.cpp.
                    {
     mlibc::infoLogger() << "getgid() is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by getgid().
sys_getgroups()
int mlibc::sys_getgroups (size_t size, const gid_t * list, int * ret)
Definition at line 1406 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_getgroups, size, list);
     if (int e = sc_error(ret); e)
         return e;
     *retval = sc_int_result<int>(ret);
     return 0;
 }
References do_syscall(), ret, sc_error(), and size.
Referenced by getgroups().
sys_gethostname()
int mlibc::sys_gethostname (char * buffer, size_t bufsize)
Definition at line 220 of file aero.cpp.
{
     auto result = syscall(SYS_GETHOSTNAME, buffer, bufsize);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References result, SYS_GETHOSTNAME, and syscall.
Referenced by gethostname().
sys_getitimer()
int mlibc::sys_getitimer (int which, struct itimerval * curr_value)
Definition at line 16 of file time.cpp.
{
     auto result = syscall(SYS_GETITIMER, which, curr_value);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References result, SYS_GETITIMER, and syscall.
Referenced by getitimer().
sys_getpgid()
pid_t mlibc::sys_getpgid (pid_t pid, pid_t * pgid)
Definition at line 179 of file aero.cpp.
{
     mlibc::infoLogger() << "sys_getpgid() is unimplemented" << frg::endlog;
     *pgid = 0;
     return 0;
 }
References infoLogger.
Referenced by getpgid().
sys_getpid()
pid_t mlibc::sys_getpid ()
Definition at line 155 of file aero.cpp.
                    {
     auto result = syscall(SYS_GETPID);
     __ensure(result >= 0);
     return result;
 }
References __ensure, result, SYS_GETPID, and syscall.
Referenced by getpid(), and raise().
sys_getppid()
pid_t mlibc::sys_getppid ()
Definition at line 162 of file aero.cpp.
                     {
     auto result = syscall(SYS_GETPPID);
     __ensure(result != 0);
     return result;
 }
References __ensure, result, SYS_GETPPID, and syscall.
Referenced by getppid().
sys_getpriority()
int mlibc::sys_getpriority (int which, id_t who, int * value)
Definition at line 416 of file generic.cpp.
{
     int ret, errno;
     SYSCALL2(SYSCALL_GETPRIORITY, which, who);
     if (ret == -1 && errno != 0) {
         return errno;
     } else {
             *value = ret;
         return 0;
    }
 }
References errno, ret, SYSCALL2, SYSCALL_GETPRIORITY, and value.
Referenced by getpriority().
sys_getrandom()
int mlibc::sys_getrandom (void * buffer, size_t length, int flags, ssize_t * bytes_written)
Definition at line 1441 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_getrandom, buffer, length, flags);
     if (int e = sc_error(ret); e)
         return e;
     *bytes_written = sc_int_result<ssize_t>(ret);
     return 0;
 }
References do_syscall(), flags, ret, and sc_error().
sys_getrlimit()
int mlibc::sys_getrlimit (int resource, struct rlimit * limit)
Definition at line 1341 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_getrlimit, resource, limit);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), ret, and sc_error().
Referenced by getrlimit().
sys_getrusage()
int mlibc::sys_getrusage (int scope, struct rusage * usage)
Definition at line 550 of file fork-exec.cpp.
{
     memset(usage, 0, sizeof(struct rusage));
     SignalGuard sguard;
     managarm::posix::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_request_type(managarm::posix::CntReqType::GET_RESOURCE_USAGE);
     req.set_mode(scope);
     auto [offer, send_head, recv_resp] =
         exchangeMsgsSync(
             getPosixLane(),
             helix_ng::offer(
                 helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
                 helix_ng::recvInline()
             )
         );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_head.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
     usage->ru_utime.tv_sec = resp.ru_user_time() / 1'000'000'000;
     usage->ru_utime.tv_usec = (resp.ru_user_time() % 1'000'000'000) / 1'000;
     return 0;
 }
References __ensure, exchangeMsgsSync(), getPosixLane(), getSysdepsAllocator(), memset, rusage::ru_utime, timeval::tv_sec, and timeval::tv_usec.
Referenced by getrusage().
sys_getschedparam()
int mlibc::sys_getschedparam (void * tcb, int * policy, struct sched_param * param)
Definition at line 582 of file fork-exec.cpp.
{
     if(tcb != mlibc::get_current_tcb()) {
         return ESRCH;
     }
     *policy = SCHED_OTHER;
     int prio = 0;
     // TODO(no92): use helGetPriority(kHelThisThread) here
     mlibc::infoLogger() << "\e[31mlibc: sys_getschedparam always returns priority 0\e[39m" << frg::endlog;
     param->sched_priority = prio;
     return 0;
 }
References ESRCH, get_current_tcb(), infoLogger, SCHED_OTHER, and sched_param::sched_priority.
Referenced by pthread_getschedparam().
sys_getsid()
pid_t mlibc::sys_getsid (pid_t pid, pid_t * sid)
Definition at line 1368 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_getsid, pid);
     if (int e = sc_error(ret); e)
         return e;
     *sid = sc_int_result<pid_t>(ret);
     return 0;
 }
References do_syscall(), ret, and sc_error().
Referenced by getsid().
sys_getsockopt()
int mlibc::sys_getsockopt (int fd, int layer, int number, void *__restrict buffer, socklen_t *__restrict size)
Definition at line 95 of file sockets.cpp.
{
     (void)fd;
     (void)size;
     if (layer == SOL_SOCKET && number == SO_PEERCRED) {
         mlibc::infoLogger() << "\e[31mmlibc: getsockopt() call with SOL_SOCKET "
                                "and SO_PEERCRED is unimplemented\e[39m"
                             << frg::endlog;
         *(int *)buffer = 0;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_SNDBUF) {
         mlibc::infoLogger() << "\e[31mmlibc: getsockopt() call with SOL_SOCKET "
                                "and SO_SNDBUF is unimplemented\e[39m"
                             << frg::endlog;
         *(int *)buffer = 4096;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_TYPE) {
         mlibc::infoLogger()
             << "\e[31mmlibc: getsockopt() call with SOL_SOCKET and SO_TYPE is "
                "unimplemented, hardcoding SOCK_STREAM\e[39m"
             << frg::endlog;
         *(int *)buffer = SOCK_STREAM;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_ERROR) {
         mlibc::infoLogger()
             << "\e[31mmlibc: getsockopt() call with SOL_SOCKET and SO_ERROR is "
                "unimplemented, hardcoding 0\e[39m"
             << frg::endlog;
         *(int *)buffer = 0;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_KEEPALIVE) {
         mlibc::infoLogger()
             << "\e[31mmlibc: getsockopt() call with SOL_SOCKET and "
                "SO_KEEPALIVE is unimplemented, hardcoding 0\e[39m"
             << frg::endlog;
         *(int *)buffer = 0;
         return 0;
     } else {
         mlibc::panicLogger()
             << "\e[31mmlibc: Unexpected getsockopt() call, layer: " << layer
             << " number: " << number << "\e[39m" << frg::endlog;
         __builtin_unreachable();
     }
     return 0;
 }
References fd, infoLogger, panicLogger, size, SO_ERROR, SO_KEEPALIVE, SO_PEERCRED, SO_SNDBUF, SO_TYPE, SOCK_STREAM, SOL_SOCKET, and Driver::void().
Referenced by getsockopt().
sys_gettid()
pid_t mlibc::sys_gettid ()
Definition at line 1149 of file sysdeps.cpp.
                    {
     auto ret = do_syscall(SYS_gettid);
     // gettid() always succeeds.
     return sc_int_result<pid_t>(ret);
 }
References do_syscall(), and ret.
Referenced by gettid().
sys_getuid()
uid_t mlibc::sys_getuid (void)
Definition at line 242 of file aero.cpp.
                    {
     mlibc::infoLogger() << "mlibc: sys_setuid is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by getuid().
sys_getxattr()
int mlibc::sys_getxattr (const char * path, const char * name, void * val, size_t size, ssize_t * nread)
Definition at line 1472 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_getxattr, path, name, val, size);
     if (int e = sc_error(ret); e) {
         return e;
     }
     *nread = sc_int_result<ssize_t>(ret);
     return 0;
 }
References do_syscall(), name, path, ret, sc_error(), and size.
Referenced by getxattr().
sys_if_indextoname()
int mlibc::sys_if_indextoname (unsigned int index, char * name)
Definition at line 10 of file net.cpp.
{
     int fd = 0;
     int r = sys_socket(AF_UNIX, SOCK_DGRAM | SOCK_CLOEXEC, AF_UNSPEC, &fd);
     if(r)
         return r;
     struct ifreq ifr;
     ifr.ifr_ifindex = index;
     int res = 0;
     int ret = sys_ioctl(fd, SIOCGIFNAME, &ifr, &res);
     close(fd);
     if(ret) {
         if(ret == ENODEV)
             return ENXIO;
         return ret;
     }
     strncpy(name, ifr.ifr_name, IF_NAMESIZE);
     return 0;
 }
References AF_UNIX, AF_UNSPEC, close(), ENODEV, ENXIO, fd, IF_NAMESIZE, index(), name, r, ret, SIOCGIFNAME, SOCK_CLOEXEC, SOCK_DGRAM, strncpy(), sys_ioctl(), and sys_socket().
Referenced by if_indextoname().
sys_if_nametoindex()
int mlibc::sys_if_nametoindex (const char * name, unsigned int * ret)
Definition at line 35 of file net.cpp.
{
     int fd = 0;
     int r = sys_socket(AF_UNIX, SOCK_DGRAM | SOCK_CLOEXEC, AF_UNSPEC, &fd);
     if(r)
         return r;
     struct ifreq ifr;
     strncpy(ifr.ifr_name, name, sizeof ifr.ifr_name);
     int res = 0;
     r = sys_ioctl(fd, SIOCGIFINDEX, &ifr, &res);
     close(fd);
     if(r)
         return r;
     *ret = ifr.ifr_ifindex;
     return 0;
 }
References AF_UNIX, AF_UNSPEC, close(), fd, name, r, ret, SIOCGIFINDEX, SOCK_CLOEXEC, SOCK_DGRAM, strncpy(), sys_ioctl(), and sys_socket().
Referenced by if_nametoindex().
sys_init_module()
int mlibc::sys_init_module (void * module, unsigned long length, const char * args)
Referenced by init_module().
sys_inotify_add_watch()
int mlibc::sys_inotify_add_watch (int ifd, const char * path, uint32_t mask, int * wd)
Definition at line 1335 of file file.cpp.
{
     SignalGuard sguard;
     managarm::posix::InotifyAddRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_fd(ifd);
     req.set_path(frg::string<MemoryAllocator>(getSysdepsAllocator(), path));
     req.set_flags(mask);
     auto [offer, send_head, send_tail, recv_resp] =
         exchangeMsgsSync(
             getPosixLane(),
             helix_ng::offer(
                 helix_ng::sendBragiHeadTail(req, getSysdepsAllocator()),
                 helix_ng::recvInline()
             )
         );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_head.error());
     HEL_CHECK(send_tail.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     if(resp.error() == managarm::posix::Errors::FILE_NOT_FOUND) {
         return ENOENT;
     }else if(resp.error() == managarm::posix::Errors::BAD_FD) {
         return EBADF;
     }else{
         __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
         *wd = resp.wd();
         return 0;
     }
 }
References __ensure, EBADF, ENOENT, exchangeMsgsSync(), getPosixLane(), getSysdepsAllocator(), and path.
Referenced by inotify_add_watch().
sys_inotify_create()
int mlibc::sys_inotify_create (int flags, int * fd)
Definition at line 687 of file generic.cpp.
{
     __syscall_ret ret = __syscall(SYS_fork);
     pid_t ret_value = (pid_t)ret.ret;
     if (ret_value == -1) {
         return ret.errno;
     }
     *child = ret_value;
     return 0;
 }
References __syscall, child, if(), ret, ret_value, and SYS_fork.
Referenced by inotify_init(), and inotify_init1().
sys_inotify_rm_watch()
int mlibc::sys_inotify_rm_watch (int ifd, int wd)
Referenced by inotify_rm_watch().
sys_ioctl()
int mlibc::sys_ioctl (int fd, unsigned long request, void * arg, int * result)
Definition at line 123 of file filesystem.cpp.
{
     auto sys_res = syscall(SYS_IOCTL, fd, request, arg);
     if (sys_res < 0) {
         return -sys_res;
     }
     if (result)
         *result = sys_res;
     return 0;
 }
References arg, fd, request, SYS_IOCTL, and syscall.
Referenced by ioctl(), sys_if_indextoname(), sys_if_nametoindex(), sys_isatty(), sys_ptsname(), sys_tcgetattr(), sys_tcsetattr(), and sys_unlockpt().
sys_isatty()
int mlibc::sys_isatty (int fd)
Definition at line 135 of file filesystem.cpp.
{
     // NOTE: The easiest way to check if a file descriptor is a TTY is to
     // do an ioctl of TIOCGWINSZ on it and see if it succeeds :^)
     struct winsize ws;
     int result;
     if (!sys_ioctl(fd, TIOCGWINSZ, &ws, &result)) {
         return 0;
     }
     return ENOTTY;
 }
References ENOTTY, fd, result, sys_ioctl(), and TIOCGWINSZ.
Referenced by mlibc::fd_file::determine_bufmode(), and isatty().
sys_kill()
int mlibc::sys_kill (int pid, int sig)
Definition at line 169 of file aero.cpp.
{
     auto result = syscall(SYS_KILL, pid, sig);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References result, SYS_KILL, and syscall.
Referenced by kill(), raise(), and sys_tgkill().
sys_klogctl()
int mlibc::sys_klogctl (int type, char * bufp, int len, int * out)
Referenced by klogctl().
sys_lgetxattr()
int mlibc::sys_lgetxattr (const char * path, const char * name, void * val, size_t size, ssize_t * nread)
Definition at line 1483 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_lgetxattr, path, name, val, size);
     if (int e = sc_error(ret); e) {
         return e;
     }
     *nread = sc_int_result<ssize_t>(ret);
     return 0;
 }
References do_syscall(), name, path, ret, sc_error(), and size.
Referenced by lgetxattr().
sys_libc_log()
void mlibc::sys_libc_log (const char * message)
Definition at line 145 of file aero.cpp.
 { syscall(SYS_LOG, msg, strlen(msg)); }
References strlen(), SYS_LOG, and syscall.
Referenced by __mlibc_do_dtors(), frg_log(), frg_panic(), anonymous_namespace{guard-abi.cpp}::Guard::lock(), mlibc::InfoSink::operator()(), and mlibc::PanicSink::operator()().
sys_libc_panic()
void mlibc::sys_libc_panic ()
Definition at line 138 of file aero.cpp.
                       {
     mlibc::infoLogger() << "libc_panic: panicked at 'unknown'" << frg::endlog;
     __ensure(!syscall(SYS_BACKTRACE));
     sys_exit(1);
 }
References __ensure, infoLogger, SYS_BACKTRACE, sys_exit(), and syscall.
Referenced by frg_panic(), and mlibc::PanicSink::operator()().
sys_link()
int mlibc::sys_link (const char * old_path, const char * new_path)
Definition at line 221 of file filesystem.cpp.
{
     long ret = syscall(SYS_LINK, srcpath, destpath);
     if(ret < 0){
         return -ret;
     }
     return 0;
 }
References destpath, ret, SYS_LINK, and syscall.
Referenced by link().
sys_linkat()
int mlibc::sys_linkat (int olddirfd, const char * old_path, int newdirfd, const char * new_path, int flags)
Definition at line 386 of file generic.cpp.
{
     __syscall_ret ret = __syscall(SYS_linkat, olddirfd, old_path, newdirfd, new_path, flags);
     if ((int)ret.ret == -1) {
         return ret.errno;
     }
     return 0;
 }
References __syscall, flags, ret, and SYS_linkat.
Referenced by linkat().
sys_listen()
int mlibc::sys_listen (int fd, int backlog)
Definition at line 42 of file sockets.cpp.
{
     auto result = syscall(SYS_LISTEN, fd, backlog);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References fd, result, SYS_LISTEN, and syscall.
Referenced by listen().
sys_listxattr()
int mlibc::sys_listxattr (const char * path, char * list, size_t size, ssize_t * nread)
Definition at line 1520 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_listxattr, path, list, size);
     if (int e = sc_error(ret); e) {
         return e;
     }
     *nread = sc_int_result<ssize_t>(ret);
     return 0;
 }
References do_syscall(), path, ret, sc_error(), and size.
Referenced by listxattr().
sys_llistxattr()
int mlibc::sys_llistxattr (const char * path, char * list, size_t size, ssize_t * nread)
Definition at line 1530 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_llistxattr, path, list, size);
     if (int e = sc_error(ret); e) {
         return e;
     }
     *nread = sc_int_result<ssize_t>(ret);
     return 0;
 }
References do_syscall(), path, ret, sc_error(), and size.
Referenced by llistxattr().
sys_lremovexattr()
int mlibc::sys_lremovexattr (const char * path, const char * name)
Definition at line 1510 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_lremovexattr, path, name);
     return sc_error(ret);
 }
References do_syscall(), name, path, ret, and sc_error().
Referenced by lremovexattr().
sys_lsetxattr()
int mlibc::sys_lsetxattr (const char * path, const char * name, const void * val, size_t size, int flags)
Definition at line 1460 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_lsetxattr, path, name, val, size, flags);
     return sc_error(ret);
 }
References do_syscall(), flags, name, path, ret, sc_error(), and size.
Referenced by lsetxattr().
sys_madvise()
int mlibc::sys_madvise (void * addr, size_t length, int advice)
Definition at line 2469 of file file.cpp.
{
     mlibc::infoLogger() << "mlibc: sys_madvise is a stub!" << frg::endlog;
     return 0;
 }
References infoLogger.
sys_memfd_create()
int mlibc::sys_memfd_create (const char * name, int flags, int * fd)
Definition at line 2418 of file file.cpp.
{
     SignalGuard sguard;
     managarm::posix::MemFdCreateRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_name(frg::string<MemoryAllocator>(getSysdepsAllocator(), name));
     req.set_flags(flags);
     auto [offer, send_head, send_tail, recv_resp] =
         exchangeMsgsSync(
             getPosixLane(),
             helix_ng::offer(
                 helix_ng::sendBragiHeadTail(req, getSysdepsAllocator()),
                 helix_ng::recvInline()
             )
         );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_head.error());
     HEL_CHECK(send_tail.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     if(resp.error() == managarm::posix::Errors::ILLEGAL_ARGUMENTS) {
         return EINVAL;
     }
     *fd = resp.fd();
     __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
     return 0;
 }
References __ensure, EINVAL, exchangeMsgsSync(), fd, flags, getPosixLane(), getSysdepsAllocator(), and name.
sys_mkdir()
int mlibc::sys_mkdir (const char * path, mode_t mode)
Definition at line 171 of file filesystem.cpp.
{
     auto result = syscall(SYS_MKDIR, path, strlen(path));
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References path, result, strlen(), SYS_MKDIR, and syscall.
Referenced by mkdir(), and mkdtemp().
sys_mkdirat()
int mlibc::sys_mkdirat (int dirfd, const char * path, mode_t mode)
Definition at line 1250 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_mkdirat, dirfd, path, mode);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References dirfd(), do_syscall(), path, ret, sc_error(), and SYS_mkdirat.
Referenced by mkdirat().
sys_mkfifoat() [1/2]
int mlibc::sys_mkfifoat (int dirfd, const char * path, int mode)
Definition at line 1264 of file sysdeps.cpp.
{
     return sys_mknodat(dirfd, path, mode | S_IFIFO, 0);
 }
References dirfd(), path, S_IFIFO, and sys_mknodat().
Referenced by mkfifoat().
sys_mkfifoat() [2/2]
int mlibc::sys_mkfifoat (int dirfd, const char * path, mode_t mode)
Definition at line 1478 of file file.cpp.
{
     SignalGuard sguard;
     managarm::posix::MkfifoAtRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_fd(dirfd);
     req.set_path(frg::string<MemoryAllocator>(getSysdepsAllocator(), path));
     req.set_mode(mode);
     auto [offer, send_head, send_tail, recv_resp] =
         exchangeMsgsSync(
             getPosixLane(),
             helix_ng::offer(
                 helix_ng::sendBragiHeadTail(req, getSysdepsAllocator()),
                 helix_ng::recvInline()
             )
         );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_head.error());
     HEL_CHECK(send_tail.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     if(resp.error() == managarm::posix::Errors::FILE_NOT_FOUND) {
         return ENOENT;
     }else if(resp.error() == managarm::posix::Errors::ALREADY_EXISTS) {
         return EEXIST;
     }else if(resp.error() == managarm::posix::Errors::BAD_FD) {
         return EBADF;
     }else if(resp.error() == managarm::posix::Errors::ILLEGAL_ARGUMENTS) {
         return EINVAL;
     }else{
         __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
         return 0;
     }
 }
References __ensure, dirfd(), EBADF, EEXIST, EINVAL, ENOENT, exchangeMsgsSync(), getPosixLane(), getSysdepsAllocator(), and path.
sys_mknodat()
int mlibc::sys_mknodat (int dirfd, const char * path, int mode, int dev)
Definition at line 1257 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_mknodat, dirfd, path, mode, dev);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References dirfd(), do_syscall(), path, ret, and sc_error().
Referenced by mknodat(), and sys_mkfifoat().
sys_mlock()
int mlibc::sys_mlock (const void * addr, size_t len)
Referenced by mlock().
sys_mlockall()
int mlibc::sys_mlockall (int flags)
Referenced by mlockall().
sys_mount()
int mlibc::sys_mount (const char * source, const char * target, const char * fstype, unsigned long flags, const void * data)
Definition at line 14 of file mount.cpp.
{
     SignalGuard sguard;
     managarm::posix::MountRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_path(frg::string<MemoryAllocator>(getSysdepsAllocator(), source));
     req.set_target_path(frg::string<MemoryAllocator>(getSysdepsAllocator(), target));
     req.set_fs_type(frg::string<MemoryAllocator>(getSysdepsAllocator(), fstype));
     auto [offer, send_head, send_tail, recv_resp] =
         exchangeMsgsSync(
             getPosixLane(),
             helix_ng::offer(
                 helix_ng::sendBragiHeadTail(req, getSysdepsAllocator()),
                 helix_ng::recvInline()
             )
         );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_head.error());
     HEL_CHECK(send_tail.error());
     HEL_CHECK(recv_resp.error());
     auto resp = *bragi::parse_head_only<managarm::posix::SvrResponse>(recv_resp, getSysdepsAllocator());
     if(resp.error() == managarm::posix::Errors::FILE_NOT_FOUND)
         return ENOENT;
     __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
     return 0;
 }
References __ensure, ENOENT, exchangeMsgsSync(), getPosixLane(), and getSysdepsAllocator().
Referenced by mount().
sys_msg_recv()
int mlibc::sys_msg_recv (int fd, struct msghdr * hdr, int flags, ssize_t * length)
Definition at line 73 of file sockets.cpp.
{
     auto result = syscall(SYS_SOCK_RECV, sockfd, msg_hdr, flags);
     if (result < 0) {
         return -result;
     }
     *length = result;
     return 0;
 }
References flags, result, SYS_SOCK_RECV, and syscall.
Referenced by recvmsg().
sys_msg_send()
int mlibc::sys_msg_send (int fd, const struct msghdr * hdr, int flags, ssize_t * length)
Definition at line 64 of file sockets.cpp.
{
     auto result = syscall(SYS_SOCK_SEND, fd, hdr, flags);
     if (result < 0)
         return -result;
     *length = result;
     return 0;
 }
References fd, flags, result, SYS_SOCK_SEND, and syscall.
Referenced by sendmsg().
sys_msync()
int mlibc::sys_msync (void * addr, size_t length, int flags)
Referenced by msync().
sys_open()
int mlibc::sys_open (const char * pathname, int flags, mode_t mode, int * fd)
Definition at line 61 of file filesystem.cpp.
{
     auto result = syscall(SYS_OPEN, 0, filename, strlen(filename), flags);
     if (result < 0) {
         return -result;
     }
     *fd = result;
     return 0;
 }
References fd, flags, result, strlen(), SYS_OPEN, and syscall.
Referenced by file_window::file_window(), fopen(), mkostemp(), open(), openpty(), posix_openpt(), ObjectRepository::requestObjectAtPath(), ObjectRepository::requestObjectWithName(), and sys_open_dir().
sys_open_dir()
int mlibc::sys_open_dir (const char * path, int * handle)
Definition at line 248 of file filesystem.cpp.
{
     return sys_open(path, O_DIRECTORY, 0, handle);
 }
References O_DIRECTORY, path, and sys_open().
Referenced by opendir().
sys_openat()
int mlibc::sys_openat (int dirfd, const char * path, int flags, mode_t mode, int * fd)
Definition at line 85 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_openat, dirfd, path, flags, mode);
     if (int e = sc_error(ret); e)
         return e;
     *fd = sc_int_result<int>(ret);
     return 0;
 }
References dirfd(), do_syscall(), fd, flags, path, ret, sc_error(), and SYS_openat.
Referenced by openat().
sys_pause()
int mlibc::sys_pause ()
Referenced by pause().
sys_peername()
int mlibc::sys_peername (int fd, struct sockaddr * addr_ptr, socklen_t max_addr_length, socklen_t * actual_length)
Definition at line 100 of file sockets.cpp.
{
     return -syscall(SYS_PEERNAME, fd, addr_ptr, max_addr_length);
 }
References fd, SYS_PEERNAME, and syscall.
Referenced by getpeername().
sys_pipe()
int mlibc::sys_pipe (int * fds, int flags)
Definition at line 309 of file filesystem.cpp.
{
     auto result = syscall(SYS_PIPE, fds, flags);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References fds, flags, result, SYS_PIPE, and syscall.
Referenced by pipe(), pipe2(), and popen().
sys_poll()
int mlibc::sys_poll (struct pollfd * fds, nfds_t count, int timeout, int * num_events)
Definition at line 376 of file filesystem.cpp.
{
     struct timespec ts;
     ts.tv_sec = timeout / 1000;
     ts.tv_nsec = (timeout % 1000) * 1000000;
     return sys_ppoll(fds, count, &ts, NULL, num_events);
 }
References count, fds, NULL, num_events, sys_ppoll(), timeout, timespec::tv_nsec, and timespec::tv_sec.
Referenced by poll().
sys_ppoll()
int mlibc::sys_ppoll (struct pollfd * fds, int nfds, const struct timespec * timeout, const sigset_t * sigmask, int * num_events)
Definition at line 364 of file filesystem.cpp.
{
     auto result = syscall(SYS_POLL, fds, nfds, timeout, sigmask);
     if (result < 0) {
         return -result;
     }
     *num_events = result;
     return 0;
 }
References fds, num_events, result, sigmask, SYS_POLL, syscall, and timeout.
Referenced by sys_poll().
sys_prctl()
int mlibc::sys_prctl (int option, va_list va, int * out)
Referenced by prctl().
sys_pread()
int mlibc::sys_pread (int fd, void * buf, size_t n, off_t off, ssize_t * bytes_read)
Definition at line 65 of file filesystem.cpp.
{
     int ret = syscall(SYS_PREAD, fd, (uintptr_t)buf, count, 0, off);
     if(ret < 0){
         return -ret;
     }
     *bytes_read = ret;
     return 0;
 }
References buf, count, fd, off, ret, SYS_PREAD, and syscall.
Referenced by pread().
sys_prepare_stack()
int mlibc::sys_prepare_stack (void ** stack, void * entry, void * user_arg, void * tcb, size_t * stack_size, size_t * guard_size)
Definition at line 36 of file thread.cpp.
{
     if (!*stack_size)
         *stack_size = default_stacksize;
     *guard_size = 0;
     uintptr_t *sp;
     if (*stack) {
         sp = reinterpret_cast<uintptr_t *>(*stack);
     } else {
         sp = reinterpret_cast<uintptr_t *>(
             reinterpret_cast<uintptr_t>(
                 mmap(nullptr, *stack_size, PROT_READ | PROT_WRITE,
                      MAP_PRIVATE | MAP_ANONYMOUS, -1, 0)) +
             *stack_size);
     }
     *--sp = reinterpret_cast<uintptr_t>(tcb);
     *--sp = reinterpret_cast<uintptr_t>(user_arg);
     *--sp = reinterpret_cast<uintptr_t>(entry);
     *stack = reinterpret_cast<void *>(sp);
     return 0;
 }
References default_stacksize, MAP_ANONYMOUS, MAP_PRIVATE, mmap(), PROT_READ, and PROT_WRITE.
Referenced by pthread_create().
sys_pselect()
int mlibc::sys_pselect (int num_fds, fd_set * read_set, fd_set * write_set, fd_set * except_set, const struct timespec * timeout, const sigset_t * sigmask, int * num_events)
Definition at line 396 of file filesystem.cpp.
{
     int fd = epoll_create1(0);
     if (fd == -1)
         return -1;
     for (int k = 0; k < FD_SETSIZE; k++) {
         struct epoll_event ev;
         memset(&ev, 0, sizeof(struct epoll_event));
         if (read_set && FD_ISSET(k, read_set))
             ev.events |= EPOLLIN;
         if (write_set && FD_ISSET(k, write_set))
             ev.events |= EPOLLOUT;
         if (except_set && FD_ISSET(k, except_set))
             ev.events |= EPOLLPRI;
         if (!ev.events)
             continue;
         ev.data.u32 = k;
         if (epoll_ctl(fd, EPOLL_CTL_ADD, k, &ev))
             return -1;
     }
     struct epoll_event evnts[16];
     int n = epoll_pwait(
         fd, evnts, 16,
         timeout ? (timeout->tv_sec * 1000 + timeout->tv_nsec / 100) : -1,
         sigmask);
     if (n == -1)
         return -1;
     fd_set res_read_set;
     fd_set res_write_set;
     fd_set res_except_set;
     FD_ZERO(&res_read_set);
     FD_ZERO(&res_write_set);
     FD_ZERO(&res_except_set);
     int m = 0;
     for (int i = 0; i < n; i++) {
         int k = evnts[i].data.u32;
         if (read_set && FD_ISSET(k, read_set) &&
             evnts[i].events & (EPOLLIN | EPOLLERR | EPOLLHUP)) {
             FD_SET(k, &res_read_set);
             m++;
         }
         if (write_set && FD_ISSET(k, write_set) &&
             evnts[i].events & (EPOLLOUT | EPOLLERR | EPOLLHUP)) {
             FD_SET(k, &res_write_set);
             m++;
         }
         if (except_set && FD_ISSET(k, except_set) &&
             evnts[i].events & EPOLLPRI) {
             FD_SET(k, &res_except_set);
             m++;
         }
     }
     if (close(fd))
         __ensure("mlibc::pselect: close() failed on epoll file");
     if (read_set)
         memcpy(read_set, &res_read_set, sizeof(fd_set));
     if (write_set)
         memcpy(write_set, &res_write_set, sizeof(fd_set));
     if (except_set)
         memcpy(except_set, &res_except_set, sizeof(fd_set));
     *num_events = m;
     return 0;
 }
References __ensure, close(), epoll_event::data, epoll_create1(), epoll_ctl(), EPOLL_CTL_ADD, epoll_pwait(), EPOLLERR, EPOLLHUP, EPOLLIN, EPOLLOUT, EPOLLPRI, events, epoll_event::events, except_set, fd, FD_ISSET, FD_SET, FD_SETSIZE, FD_ZERO, i, k, memcpy, memset, n, num_events, read_set, res_except_set, res_read_set, res_write_set, sigmask, timeout, epoll_data::u32, and write_set.
Referenced by pselect(), and select().
sys_ptrace()
int mlibc::sys_ptrace (long req, pid_t pid, void * addr, void * data, long * out)
Referenced by ptrace().
sys_ptsname()
int mlibc::sys_ptsname (int fd, char * buffer, size_t length)
Definition at line 386 of file filesystem.cpp.
{
     int index;
     if (int e = sys_ioctl(fd, TIOCGPTN, &index, NULL); e)
         return e;
     if ((size_t)snprintf(buffer, length, "/dev/pts/%d", index) >= length) {
         return ERANGE;
     }
     return 0;
 }
References ERANGE, fd, index(), NULL, snprintf(), and sys_ioctl().
Referenced by ptsname(), and ptsname_r().
sys_pwrite()
int mlibc::sys_pwrite (int fd, const void * buf, size_t n, off_t off, ssize_t * bytes_read)
Definition at line 53 of file filesystem.cpp.
{
     int ret = syscall(SYS_PWRITE, fd, (uintptr_t)buffer, count, 0, off);
     if(ret < 0){
         return -ret;
     }
     *written = ret;
     return 0;
 }
References count, fd, off, ret, SYS_PWRITE, and syscall.
Referenced by pwrite().
sys_read()
int mlibc::sys_read (int fd, void * buf, size_t count, ssize_t * bytes_read)
Definition at line 30 of file filesystem.cpp.
{
     auto result = syscall(SYS_READ, fd, buf, count);
     if (result < 0) {
         *bytes_read = 0;
         return -result;
     }
     *bytes_read = result;
     return 0;
 }
References buf, count, fd, result, SYS_READ, and syscall.
Referenced by eventfd_read(), file_window::file_window(), mlibc::fd_file::io_read(), read(), and readExactlyOrDie().
sys_read_entries()
int mlibc::sys_read_entries (int handle, void * buffer, size_t max_size, size_t * bytes_read)
Definition at line 212 of file filesystem.cpp.
{
     auto result = syscall(SYS_GETDENTS, handle, buffer, max_size);
     // Check if we got an error.
     if (result < 0) {
         *bytes_read = 0;
         return -result;
     }
     // Nothing to read.
     if (result == 0) {
         *bytes_read = 0;
         return 0;
     }
     auto entry = (struct aero_dir_entry *)buffer;
     struct dirent dirent = {
         .d_ino = static_cast<ino_t>(entry->inode),
         .d_off = static_cast<off_t>(entry->offset),
         .d_reclen = static_cast<unsigned short>(entry->reclen),
         .d_type = static_cast<unsigned char>(entry->filetyp),
     };
     // The reclen is the size of the dirent struct, plus the size of the name.
     auto name_size = entry->reclen - sizeof(struct aero_dir_entry);
     __ensure(name_size < 255);
     memcpy(&dirent.d_name, entry->name, name_size);
     *bytes_read = entry->reclen;
     memcpy(buffer, &dirent, sizeof(struct dirent));
     return 0;
 }
References __ensure, dirent::d_ino, dirent::d_name, dirent::d_off, dirent::d_type, max_size, memcpy, result, SYS_GETDENTS, and syscall.
Referenced by readdir(), and readdir_r().
sys_readlink()
int mlibc::sys_readlink (const char * path, void * buffer, size_t max_size, ssize_t * length)
Definition at line 263 of file filesystem.cpp.
{
     auto result = syscall(SYS_READ_LINK, path, strlen(path), buffer, max_size);
     if (result < 0) {
         return -result;
     }
     *length = result;
     return 0;
 }
References max_size, path, result, strlen(), SYS_READ_LINK, and syscall.
Referenced by readlink(), and realpath().
sys_readv()
int mlibc::sys_readv (int fd, const struct iovec * iovs, int iovc, ssize_t * bytes_read)
Definition at line 115 of file sysdeps.cpp.
{
     auto ret = do_cp_syscall(SYS_readv, fd, iovs, iovc);
     if(int e = sc_error(ret); e)
         return e;
     *bytes_read = sc_int_result<ssize_t>(ret);
     return 0;
 }
References do_cp_syscall(), fd, ret, and sc_error().
Referenced by readv().
sys_reboot()
int mlibc::sys_reboot (int cmd)
Referenced by reboot().
sys_removexattr()
int mlibc::sys_removexattr (const char * path, const char * name)
Definition at line 1505 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_removexattr, path, name);
     return sc_error(ret);
 }
References do_syscall(), name, path, ret, and sc_error().
Referenced by removexattr().
sys_rename()
int mlibc::sys_rename (const char * path, const char * new_path)
Definition at line 252 of file filesystem.cpp.
{
     auto result =
         syscall(SYS_RENAME, path, strlen(path), new_path, strlen(new_path));
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References path, result, strlen(), SYS_RENAME, and syscall.
Referenced by rename().
sys_renameat()
int mlibc::sys_renameat (int olddirfd, const char * old_path, int newdirfd, const char * new_path)
Definition at line 1308 of file sysdeps.cpp.
{
 #ifdef SYS_renameat2
     auto ret = do_syscall(SYS_renameat2, old_dirfd, old_path, new_dirfd, new_path, 0);
 #else
     auto ret = do_syscall(SYS_renameat, old_dirfd, old_path, new_dirfd, new_path);
 #endif /* defined(SYS_renameat2) */
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), ret, and sc_error().
Referenced by renameat().
sys_rmdir()
int mlibc::sys_rmdir (const char * path)
Definition at line 211 of file filesystem.cpp.
{
     long ret = syscall(SYS_RMDIR, path);
     if(ret < 0){
         return -ret;
     }
     return 0;
 }
References path, ret, SYS_RMDIR, and syscall.
Referenced by remove(), and rmdir().
sys_sched_yield()
int mlibc::sys_sched_yield (void)
Definition at line 331 of file generic.cpp.
{
     int ret, errno;
     SYSCALL0(SYSCALL_SCHED_YIELD);
     if (ret == -1) {
         return errno;
     }
     return 0;
 }
References errno, ret, SYSCALL0, and SYSCALL_SCHED_YIELD.
sys_seek()
int mlibc::sys_seek (int fd, off_t offset, int whence, off_t * new_offset)
Definition at line 145 of file generic.cpp.
{
     off_t ret;
     int sys_errno;
     asm volatile ("syscall"
             : "=a"(ret), "=d"(sys_errno)
             : "a"(8), "D"(fd), "S"(offset), "d"(whence)
             : "rcx", "r11");
     if (ret == -1)
         return sys_errno;
     *new_offset = ret;
     return 0;
 }
References fd, new_offset, offset, ret, and whence.
Referenced by mlibc::fd_file::determine_type(), mlibc::fd_file::io_seek(), lseek(), lseek64(), and seekOrDie().
sys_setegid()
int mlibc::sys_setegid (gid_t egid)
Definition at line 274 of file aero.cpp.
{
     mlibc::infoLogger() << "mlibc: sys_setegid is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by setegid().
sys_seteuid()
int mlibc::sys_seteuid (uid_t euid)
Definition at line 257 of file aero.cpp.
{
     mlibc::infoLogger() << "mlibc: sys_setgid is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by seteuid().
sys_setgid()
int mlibc::sys_setgid (gid_t gid)
Definition at line 269 of file aero.cpp.
{
     mlibc::infoLogger() << "mlibc: sys_setgid is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by setgid().
sys_setgroups()
int mlibc::sys_setgroups (size_t size, const gid_t * list)
Referenced by setgroups().
sys_sethostname()
int mlibc::sys_sethostname (const char * buffer, size_t bufsize)
Definition at line 281 of file generic.cpp.
{
     int ret, errno;
     SYSCALL2(SYSCALL_SETHOSTNAME, buff, size);
     if (ret == -1) {
         return errno;
     }
     return 0;
 }
References errno, ret, size, SYSCALL2, and SYSCALL_SETHOSTNAME.
Referenced by sethostname().
sys_setitimer()
int mlibc::sys_setitimer (int which, const struct itimerval * new_value, struct itimerval * old_value)
Definition at line 5 of file time.cpp.
{
     auto result = syscall(SYS_SETITIMER, which, new_value, old_value);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References result, SYS_SETITIMER, and syscall.
Referenced by setitimer().
sys_setpgid()
int mlibc::sys_setpgid (pid_t pid, pid_t pgid)
Definition at line 163 of file generic.cpp.
{
     (void)pid;
     (void)pgid;
     mlibc::infoLogger() << "mlibc: " << __func__ << " is a stub!" << frg::endlog;
     return 0;
 }
References infoLogger, and Driver::void().
Referenced by setpgid().
sys_setpriority()
int mlibc::sys_setpriority (int which, id_t who, int prio)
Definition at line 429 of file generic.cpp.
{
     int ret, errno;
     SYSCALL3(SYSCALL_SETPRIORITY, which, who, prio);
     if (ret == -1) {
         return errno;
     } else {
         return 0;
    }
 }
References errno, ret, SYSCALL3, and SYSCALL_SETPRIORITY.
Referenced by setpriority().
sys_setregid()
int mlibc::sys_setregid (gid_t rgid, gid_t egid)
Referenced by setregid().
sys_setresgid()
int mlibc::sys_setresgid (gid_t rgid, gid_t egid, gid_t sgid)
Referenced by setresgid().
sys_setresuid()
int mlibc::sys_setresuid (uid_t ruid, uid_t euid, uid_t suid)
Referenced by setresuid().
sys_setreuid()
int mlibc::sys_setreuid (uid_t ruid, uid_t euid)
Referenced by setreuid().
sys_setrlimit()
int mlibc::sys_setrlimit (int resource, const struct rlimit * limit)
Definition at line 1348 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_setrlimit, resource, limit);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), ret, and sc_error().
Referenced by setrlimit().
sys_setschedparam()
int mlibc::sys_setschedparam (void * tcb, int policy, const struct sched_param * param)
Definition at line 596 of file fork-exec.cpp.
{
     if(tcb != mlibc::get_current_tcb()) {
         return ESRCH;
     }
     if(policy != SCHED_OTHER) {
         return EINVAL;
     }
     HEL_CHECK(helSetPriority(kHelThisThread, param->sched_priority));
     return 0;
 }
References EINVAL, ESRCH, get_current_tcb(), SCHED_OTHER, and sched_param::sched_priority.
Referenced by pthread_setschedparam().
sys_setsid()
int mlibc::sys_setsid (pid_t * sid)
Definition at line 252 of file aero.cpp.
{
     mlibc::infoLogger() << "mlibc: sys_setsid is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by setsid().
sys_setsockopt()
int mlibc::sys_setsockopt (int fd, int layer, int number, const void * buffer, socklen_t size)
Definition at line 142 of file sockets.cpp.
{
     (void)fd;
     (void)buffer;
     (void)size;
     if (layer == SOL_SOCKET && number == SO_PASSCRED) {
         mlibc::infoLogger() << "\e[31mmlibc: setsockopt(SO_PASSCRED) is not "
                                "implemented correctly\e[39m"
                             << frg::endlog;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_ATTACH_FILTER) {
         mlibc::infoLogger() << "\e[31mmlibc: setsockopt(SO_ATTACH_FILTER) is "
                                "not implemented correctly\e[39m"
                             << frg::endlog;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_RCVBUFFORCE) {
         mlibc::infoLogger() << "\e[31mmlibc: setsockopt(SO_RCVBUFFORCE) is not "
                                "implemented correctly\e[39m"
                             << frg::endlog;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_SNDBUF) {
         mlibc::infoLogger() << "\e[31mmlibc: setsockopt() call with SOL_SOCKET "
                                "and SO_SNDBUF is unimplemented\e[39m"
                             << frg::endlog;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_KEEPALIVE) {
         mlibc::infoLogger() << "\e[31mmlibc: setsockopt() call with SOL_SOCKET "
                                "and SO_KEEPALIVE is unimplemented\e[39m"
                             << frg::endlog;
         return 0;
     } else if (layer == SOL_SOCKET && number == SO_REUSEADDR) {
         mlibc::infoLogger() << "\e[31mmlibc: setsockopt() call with SOL_SOCKET "
                                "and SO_REUSEADDR is unimplemented\e[39m"
                             << frg::endlog;
         return 0;
     } else if (layer == AF_NETLINK && number == SO_ACCEPTCONN) {
         mlibc::infoLogger() << "\e[31mmlibc: setsockopt() call with AF_NETLINK "
                                "and SO_ACCEPTCONN is unimplemented\e[39m"
                             << frg::endlog;
         return 0;
     } else {
         mlibc::panicLogger()
             << "\e[31mmlibc: Unexpected setsockopt() call, layer: " << layer
             << " number: " << number << "\e[39m" << frg::endlog;
         __builtin_unreachable();
     }
 }
References AF_NETLINK, fd, infoLogger, panicLogger, size, SO_ACCEPTCONN, SO_ATTACH_FILTER, SO_KEEPALIVE, SO_PASSCRED, SO_RCVBUFFORCE, SO_REUSEADDR, SO_SNDBUF, SOL_SOCKET, and Driver::void().
Referenced by setsockopt().
sys_setuid()
int mlibc::sys_setuid (uid_t uid)
Definition at line 113 of file lemon.cpp.
{
     return -syscall(SYS_SETUID, uid);
 }
References SYS_SETUID, and syscall.
Referenced by setuid().
sys_setxattr()
int mlibc::sys_setxattr (const char * path, const char * name, const void * val, size_t size, int flags)
Definition at line 1454 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_setxattr, path, name, val, size, flags);
     return sc_error(ret);
 }
References do_syscall(), flags, name, path, ret, sc_error(), and size.
Referenced by setxattr().
sys_sigaction() [1/2]
int mlibc::sys_sigaction (int how, const struct sigaction *__restrict action, struct sigaction *__restrict old_action)
Definition at line 12 of file signals.cpp.
{
 #if LOG_SIGACTION_INSTALL
     mlibc::infoLogger() << "sys_sigaction: signal " << how << frg::endlog;
     mlibc::infoLogger() << "sys_sigaction: size: " << sizeof(*action)
                         << frg::endlog;
     if (action != NULL) {
         mlibc::infoLogger() << "sys_sigaction: handler "
                             << (int64_t)action->sa_handler << frg::endlog;
         mlibc::infoLogger() << "sys_sigaction: action "
                             << (int64_t)action->sa_sigaction << frg::endlog;
         mlibc::infoLogger() << "sys_sigaction: flags "
                             << (int64_t)action->sa_flags << frg::endlog;
     }
     mlibc::infoLogger() << frg::endlog;
 #endif
     auto sigreturn = (sc_word_t)__mlibc_signal_restore;
     auto res = syscall(SYS_SIGACTION, how, (sc_word_t)action, sigreturn,
                        (sc_word_t)old_action);
     if (res < 0) {
         return -res;
     }
     return 0;
 }
References __mlibc_signal_restore(), infoLogger, NULL, SYS_SIGACTION, and syscall.
sys_sigaction() [2/2]
int mlibc::sys_sigaction (int signum, const struct sigaction * __restrict, struct sigaction * __restrict)
Definition at line 130 of file generic.cpp.
{
     (void)signum;
     (void)act;
     (void)oldact;
     mlibc::infoLogger() << "sigaction() is a stub" << frg::endlog;
     return 0;
 }
References infoLogger, and Driver::void().
Referenced by abort(), popen(), mlibc::anonymous_namespace{pthread-stubs.cpp}::PthreadSignalInstaller::PthreadSignalInstaller(), sigaction(), signal(), and system().
sys_sigaltstack()
int mlibc::sys_sigaltstack (const stack_t * ss, stack_t * oss)
Definition at line 1235 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_sigaltstack, ss, oss);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), ret, and sc_error().
Referenced by sigaltstack().
sys_sigentry()
int mlibc::sys_sigentry (void * sigentry)
Definition at line 60 of file entry.cpp.
{
         __syscall_ret ret = __syscall(27, sigentry);
         if (ret.errno != 0)
             return ret.errno;
         return 0;
     }
References __syscall, and ret.
sys_signalfd_create() [1/2]
int mlibc::sys_signalfd_create (const sigset_t * masks, int flags, int * fd)
Definition at line 1270 of file file.cpp.
{
     __ensure(!(flags & ~(SFD_CLOEXEC | SFD_NONBLOCK)));
     uint32_t proto_flags = 0;
     if(flags & SFD_CLOEXEC)
         proto_flags |= managarm::posix::OpenFlags::OF_CLOEXEC;
     if(flags & SFD_NONBLOCK)
         proto_flags |= managarm::posix::OpenFlags::OF_NONBLOCK;
     SignalGuard sguard;
     managarm::posix::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_request_type(managarm::posix::CntReqType::SIGNALFD_CREATE);
     req.set_flags(proto_flags);
     req.set_sigset(*masks);
     auto [offer, send_req, recv_resp] = exchangeMsgsSync(
         getPosixLane(),
         helix_ng::offer(
             helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
             helix_ng::recvInline())
     );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_req.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
     *fd = resp.fd();
     return 0;
 }
References __ensure, exchangeMsgsSync(), fd, flags, getPosixLane(), getSysdepsAllocator(), SFD_CLOEXEC, and SFD_NONBLOCK.
Referenced by signalfd().
sys_signalfd_create() [2/2]
int mlibc::sys_signalfd_create (sigset_t , int , int *)
References __syscall, EINTR, ENOSYS, flags, if(), infoLogger, NULL, ret, ret_pid, ret_value, ru, status, and SYS_waitpid.
sys_sigprocmask() [1/2]
int mlibc::sys_sigprocmask (int how, const sigset_t *__restrict set, sigset_t *__restrict retrieve)
Definition at line 43 of file signals.cpp.
{
     auto result = syscall(SYS_SIGPROCMASK, how, set, retrieve);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References result, SYS_SIGPROCMASK, and syscall.
Referenced by abort(), popen(), pthread_sigmask(), sigprocmask(), and system().
sys_sigprocmask() [2/2]
int mlibc::sys_sigprocmask (int how, const sigset_t * __restrict, sigset_t * __restrict)
Definition at line 733 of file generic.cpp.
{
     mlibc::infoLogger() << "mlibc: sys_sigprocmask() is a stub" << frg::endlog;
     return 0;
 }
References infoLogger.
sys_sigreturn()
int mlibc::sys_sigreturn (void * context, sigset_t old_mask)
Definition at line 67 of file entry.cpp.
{
         __syscall(30, context, old_mask);
         __builtin_unreachable();
     }
References __syscall.
Referenced by __mlibc_sigentry().
sys_sigsuspend()
int mlibc::sys_sigsuspend (const sigset_t * set)
Definition at line 1228 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_rt_sigsuspend, set, NSIG / 8);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References do_syscall(), NSIG, ret, and sc_error().
Referenced by sigsuspend().
sys_sigtimedwait()
int mlibc::sys_sigtimedwait (const sigset_t *__restrict set, siginfo_t *__restrict info, const struct timespec *__restrict timeout, int * out_signal)
Definition at line 1550 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_rt_sigtimedwait, set, info, timeout, NSIG / 8);
     if (int e = sc_error(ret); e)
         return e;
     *out_signal = sc_int_result<int>(ret);
     return 0;
 }
References do_syscall(), info, NSIG, ret, sc_error(), and timeout.
Referenced by sigtimedwait().
sys_sleep()
int mlibc::sys_sleep (time_t * secs, long * nanos)
Definition at line 230 of file aero.cpp.
{
     struct timespec ts = {.tv_sec = *sec, .tv_nsec = *nanosec};
     auto result = syscall(SYS_SLEEP, &ts);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References result, SYS_SLEEP, syscall, and timespec::tv_sec.
Referenced by nanosleep(), sleep(), and usleep().
sys_socket()
int mlibc::sys_socket (int family, int type, int protocol, int * fd)
Definition at line 10 of file sockets.cpp.
{
     auto result = syscall(SYS_SOCKET, family, type, protocol);
     if (result < 0) {
         return -result;
     }
     *fd = result;
     return 0;
 }
References fd, result, SYS_SOCKET, syscall, and type.
Referenced by socket(), sys_if_indextoname(), and sys_if_nametoindex().
sys_socketpair()
int mlibc::sys_socketpair (int domain, int type_and_flags, int proto, int * fds)
Definition at line 85 of file sockets.cpp.
{
     auto result = syscall(SYS_SOCKET_PAIR, domain, type_and_flags, proto, fds);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References fds, result, SYS_SOCKET_PAIR, and syscall.
Referenced by socketpair().
sys_sockname()
int mlibc::sys_sockname (int fd, struct sockaddr * addr_ptr, socklen_t max_addr_length, socklen_t * actual_length)
Definition at line 95 of file sockets.cpp.
{
     return -syscall(SYS_SOCKNAME, fd, addr_ptr, max_addr_length);
 }
References fd, SYS_SOCKNAME, and syscall.
Referenced by getsockname().
sys_stat()
int mlibc::sys_stat (fsfd_target fsfdt, int fd, const char * path, int flags, struct stat * statbuf)
Definition at line 93 of file filesystem.cpp.
{
     auto result = 0;
     switch (fsfdt) {
     case fsfd_target::path: {
         result = syscall(SYS_STAT, path, strlen(path), statbuf);
         break;
     }
     case fsfd_target::fd: {
         result = syscall(SYS_FSTAT, fd, statbuf);
         break;
     }
     default: {
         mlibc::infoLogger()
             << "mlibc warning: sys_stat: unsupported fsfd target"
             << frg::endlog;
         return EINVAL;
     }
     }
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References EINVAL, fd, infoLogger, path, result, strlen(), SYS_FSTAT, SYS_STAT, and syscall.
Referenced by file_window::file_window(), fstat(), fstatat(), lstat(), realpath(), stat(), and sys_faccessat().
sys_statfs()
int mlibc::sys_statfs (const char * path, struct statfs * buf)
Definition at line 228 of file sysdeps.cpp.
{
     auto ret = do_cp_syscall(SYS_statfs, path, buf);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References buf, do_cp_syscall(), path, ret, and sc_error().
Referenced by statfs().
sys_statvfs()
int mlibc::sys_statvfs (const char * path, struct statvfs * out)
Referenced by statvfs().
sys_symlink()
int mlibc::sys_symlink (const char * target_path, const char * link_path)
Definition at line 1268 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_symlinkat, target_path, AT_FDCWD, link_path);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References AT_FDCWD, do_syscall(), ret, and sc_error().
Referenced by symlink().
sys_symlinkat()
int mlibc::sys_symlinkat (const char * target_path, int dirfd, const char * link_path)
Definition at line 1275 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_symlinkat, target_path, dirfd, link_path);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References dirfd(), do_syscall(), ret, and sc_error().
Referenced by symlinkat().
sys_sync()
void mlibc::sys_sync ()
Definition at line 1423 of file sysdeps.cpp.
                 {
     do_syscall(SYS_sync);
 }
References do_syscall().
Referenced by sync().
sys_sysinfo()
int mlibc::sys_sysinfo (struct sysinfo * info)
Referenced by sysinfo().
sys_tcb_set()
int mlibc::sys_tcb_set (void * pointer)
Definition at line 95 of file aero.cpp.
{
     auto result = syscall(SYS_ARCH_PRCTL, ARCH_SET_FS, (uint64_t)pointer);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
References ARCH_SET_FS, result, SYS_ARCH_PRCTL, and syscall.
Referenced by __mlibc_enter_thread(), and __mlibc_thread_trampoline().
sys_tcdrain()
int mlibc::sys_tcdrain (int)
Definition at line 728 of file file.cpp.
                      {
     mlibc::infoLogger() << "\e[35mmlibc: tcdrain() is a stub\e[39m" << frg::endlog;
     return 0;
 }
References infoLogger.
Referenced by tcdrain().
sys_tcflow()
int mlibc::sys_tcflow (int , int)
Referenced by tcflow().
sys_tcflush()
int mlibc::sys_tcflush (int , int)
Referenced by tcflush().
sys_tcgetattr()
int mlibc::sys_tcgetattr (int fd, struct termios * attr)
Definition at line 148 of file filesystem.cpp.
{
     int result;
     if (int e = sys_ioctl(fd, TCGETS, (void *)attr, &result); e)
         return e;
     return 0;
 }
References attr, fd, result, and sys_ioctl().
Referenced by tcgetattr().
sys_tcsetattr()
int mlibc::sys_tcsetattr (int fd, int optional_action, const struct termios * attr)
Definition at line 157 of file filesystem.cpp.
{
     if (optional_action)
         mlibc::infoLogger()
             << "mlibc: warning: sys_tcsetattr ignores optional_action"
             << frg::endlog;
     int result;
     if (int e = sys_ioctl(fd, TCSETSF, (void *)attr, &result); e)
         return e;
     return 0;
 }
References attr, fd, infoLogger, result, and sys_ioctl().
Referenced by tcsetattr().
sys_tgkill()
int mlibc::sys_tgkill (int tgid, int tid, int sig)
Definition at line 103 of file signals.cpp.
{
     return sys_kill(tid, number);
 }
References sys_kill().
Referenced by pthread_cancel(), pthread_kill(), and tgkill().
sys_thread_exit()
void mlibc::sys_thread_exit ()
Definition at line 231 of file generic.cpp.
{
     asm volatile ("syscall"
             :
             : "a"(68)
             : "rcx", "r11");
     __builtin_trap();
 }
Referenced by __mlibc_enter_thread(), __mlibc_thread_trampoline(), and pthread_exit().
sys_timer_create()
int mlibc::sys_timer_create (clockid_t clk, struct sigevent *__restrict evp, timer_t *__restrict res)
Referenced by timer_create().
sys_timer_delete()
int mlibc::sys_timer_delete (timer_t t)
Referenced by timer_delete().
sys_timer_settime()
int mlibc::sys_timer_settime (timer_t t, int flags, const struct itimerspec *__restrict val, struct itimerspec *__restrict old)
Referenced by timer_settime().
sys_timerfd_create() [1/2]
int mlibc::sys_timerfd_create (int clockid, int flags, int * fd)
Definition at line 1214 of file file.cpp.
{
     (void) clockid;
     SignalGuard sguard;
     managarm::posix::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_request_type(managarm::posix::CntReqType::TIMERFD_CREATE);
     req.set_flags(flags);
     auto [offer, send_req, recv_resp] = exchangeMsgsSync(
         getPosixLane(),
         helix_ng::offer(
             helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
             helix_ng::recvInline())
     );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_req.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
     *fd = resp.fd();
     return 0;
 }
References __ensure, exchangeMsgsSync(), fd, flags, getPosixLane(), getSysdepsAllocator(), and Driver::void().
Referenced by timerfd_create().
sys_timerfd_create() [2/2]
int mlibc::sys_timerfd_create (int , int *)
sys_timerfd_settime()
int mlibc::sys_timerfd_settime (int fd, int flags, const struct itimerspec * value, struct itimerspec * oldvalue)
Definition at line 1240 of file file.cpp.
{
     __ensure(!oldvalue);
     SignalGuard sguard;
     managarm::posix::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_request_type(managarm::posix::CntReqType::TIMERFD_SETTIME);
     req.set_fd(fd);
     req.set_time_secs(value->it_value.tv_sec);
     req.set_time_nanos(value->it_value.tv_nsec);
     req.set_interval_secs(value->it_interval.tv_sec);
     req.set_interval_nanos(value->it_interval.tv_nsec);
     auto [offer, send_req, recv_resp] = exchangeMsgsSync(
         getPosixLane(),
         helix_ng::offer(
             helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
             helix_ng::recvInline())
     );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_req.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
     return 0;
 }
References __ensure, exchangeMsgsSync(), fd, getPosixLane(), getSysdepsAllocator(), and value.
Referenced by timerfd_settime().
sys_times()
int mlibc::sys_times (struct tms * tms, clock_t * out)
Definition at line 1135 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_times, tms);
     if (int e = sc_error(ret); e)
         return e;
     *out = sc_int_result<long>(ret);
     return 0;
 }
References do_syscall(), ret, and sc_error().
Referenced by times().
sys_ttyname()
int mlibc::sys_ttyname (int fd, char * buf, size_t size)
Definition at line 155 of file generic.cpp.
{
     (void)fd;
     (void)buf;
     (void)size;
     mlibc::infoLogger() << "ttyname() is a stub!" << frg::endlog;
     return ENOSYS;
 }
References buf, ENOSYS, fd, infoLogger, size, and Driver::void().
Referenced by ttyname(), and ttyname_r().
sys_umask()
int mlibc::sys_umask (mode_t mode, mode_t * old)
Definition at line 1282 of file sysdeps.cpp.
{
     auto ret = do_syscall(SYS_umask, mode);
     if (int e = sc_error(ret); e)
         return e;
     *old = sc_int_result<mode_t>(ret);
     return 0;
 }
References do_syscall(), ret, sc_error(), and SYS_umask.
Referenced by umask().
sys_umount2()
int mlibc::sys_umount2 (const char * target, int flags)
Referenced by umount2().
sys_uname()
int mlibc::sys_uname (struct utsname * buf)
Definition at line 65 of file aero.cpp.
{
     auto result = syscall(SYS_UNAME, buf);
     if (result < 0) {
         return -result;
     }
     return result;
 }
References buf, result, SYS_UNAME, and syscall.
Referenced by uname().
sys_unlinkat()
int mlibc::sys_unlinkat (int dirfd, const char * path, int flags)
Definition at line 194 of file filesystem.cpp.
{
     auto result = syscall(SYS_UNLINK, fd, path, strlen(path), flags);
     if (result < 0) {
         return -result;
     }
     return 0;
 }
Referenced by remove(), unlink(), and unlinkat().
sys_unlockpt()
int mlibc::sys_unlockpt (int fd)
Definition at line 2484 of file file.cpp.
{
     int unlock = 0;
     if(int e = sys_ioctl(fd, TIOCSPTLCK, &unlock, NULL); e)
         return e;
     return 0;
 }
References fd, NULL, and sys_ioctl().
Referenced by unlockpt().
sys_utimensat()
int mlibc::sys_utimensat (int dirfd, const char * pathname, const struct timespec times[2], int flags)
Definition at line 167 of file sysdeps.cpp.
{
     auto ret = do_cp_syscall(SYS_utimensat, dirfd, pathname, times, flags);
     if (int e = sc_error(ret); e)
         return e;
     return 0;
 }
References dirfd(), do_cp_syscall(), flags, ret, sc_error(), and times().
Referenced by futimens(), utime(), utimensat(), and utimes().
sys_vm_map()
int mlibc::sys_vm_map (void * hint, size_t size, int prot, int flags, int fd, off_t offset, void ** window)
Definition at line 105 of file aero.cpp.
{
     auto result = syscall(SYS_MMAP, hint, size, prot, flags, fd, offset);
     if (result < 0) {
         return -result;
     }
     *window = (void *)result;
     return 0;
 }
References fd, flags, offset, prot, result, size, SYS_MMAP, syscall, and window.
Referenced by ObjectRepository::_fetchFromFile(), file_window::file_window(), mmap(), and sys_anon_allocate().
sys_vm_protect()
int mlibc::sys_vm_protect (void * pointer, size_t size, int prot)
Definition at line 121 of file aero.cpp.
{
     auto res = syscall(SYS_MPROTECT, pointer, size, prot);
     if (res < 0)
         return -res;
     return 0;
 }
References prot, size, SYS_MPROTECT, and syscall.
Referenced by ObjectRepository::_fetchFromFile(), and mprotect().
sys_vm_readahead()
int mlibc::sys_vm_readahead (void * pointer, size_t size)
Referenced by ObjectRepository::_fetchFromFile().
sys_vm_remap()
int mlibc::sys_vm_remap (void * pointer, size_t size, size_t new_size, void ** window)
Definition at line 605 of file file.cpp.
{
     SignalGuard sguard;
     managarm::posix::CntRequest<MemoryAllocator> req(getSysdepsAllocator());
     req.set_request_type(managarm::posix::CntReqType::VM_REMAP);
     req.set_address(reinterpret_cast<uintptr_t>(pointer));
     req.set_size(size);
     req.set_new_size(new_size);
     auto [offer, send_req, recv_resp] = exchangeMsgsSync(
         getPosixLane(),
         helix_ng::offer(
             helix_ng::sendBragiHeadOnly(req, getSysdepsAllocator()),
             helix_ng::recvInline())
     );
     HEL_CHECK(offer.error());
     HEL_CHECK(send_req.error());
     HEL_CHECK(recv_resp.error());
     managarm::posix::SvrResponse<MemoryAllocator> resp(getSysdepsAllocator());
     resp.ParseFromArray(recv_resp.data(), recv_resp.length());
     __ensure(resp.error() == managarm::posix::Errors::SUCCESS);
     *window = reinterpret_cast<void *>(resp.offset());
     return 0;
 }
References __ensure, exchangeMsgsSync(), getPosixLane(), getSysdepsAllocator(), size, and window.
Referenced by mremap().
sys_vm_unmap()
int mlibc::sys_vm_unmap (void * pointer, size_t size)
Definition at line 117 of file aero.cpp.
{
     return syscall(SYS_MUNMAP, address, size);
 }
References size, SYS_MUNMAP, and syscall.
Referenced by munmap(), and sys_anon_free().
sys_waitpid()
int mlibc::sys_waitpid (pid_t pid, int * status, int flags, struct rusage * ru, pid_t * ret_pid)
Definition at line 250 of file generic.cpp.
{
     pid_t ret;
     int errno;
     if(ru) {
         mlibc::infoLogger() << "mlibc: struct rusage in sys_waitpid is unsupported" << frg::endlog;
         return ENOSYS;
     }
     SYSCALL3(SYSCALL_WAIT, pid, status, flags);
     if (ret == -1) {
         return errno;
     }
     *ret_pid = ret;
     return 0;
 }
References ENOSYS, errno, flags, infoLogger, ret, ret_pid, ru, status, SYSCALL3, and SYSCALL_WAIT.
Referenced by pclose(), system(), wait4(), and waitpid().
sys_write()
int mlibc::sys_write (int fd, const void * buf, size_t count, ssize_t * bytes_written)
Definition at line 19 of file filesystem.cpp.
{
     auto result = syscall(SYS_WRITE, fd, buffer, count);
     if (result < 0) {
         return -result;
     }
     *written = result;
     return 0;
 }
References count, fd, result, SYS_WRITE, and syscall.
Referenced by eventfd_write(), mlibc::fd_file::io_write(), and write().
sys_yield()
void mlibc::sys_yield ()
Definition at line 279 of file aero.cpp.
                  {
     mlibc::infoLogger() << "mlibc: sys_yield is a stub" << frg::endlog;
     __ensure(!syscall(SYS_BACKTRACE));
 }
References __ensure, infoLogger, SYS_BACKTRACE, and syscall.
Referenced by sched_yield().
tcb_async_cancel()
static constexpr bool mlibc::tcb_async_cancel (int value) static constexpr
Definition at line 57 of file tcb.hpp.
{
         return (value & (tcbCancelEnableBit | tcbCancelAsyncBit))
             == (tcbCancelEnableBit | tcbCancelAsyncBit);
     }
References anonymous_namespace{tcb.hpp}::tcbCancelAsyncBit, anonymous_namespace{tcb.hpp}::tcbCancelEnableBit, and value.
tcb_async_cancelled()
static constexpr bool mlibc::tcb_async_cancelled (int value) static constexpr
Definition at line 50 of file tcb.hpp.
{
         return (value & (tcbCancelEnableBit | tcbCancelAsyncBit
                 | tcbCancelTriggerBit)) == (tcbCancelEnableBit
                     | tcbCancelAsyncBit | tcbCancelTriggerBit);
     }
References anonymous_namespace{tcb.hpp}::tcbCancelAsyncBit, anonymous_namespace{tcb.hpp}::tcbCancelEnableBit, anonymous_namespace{tcb.hpp}::tcbCancelTriggerBit, and value.
Referenced by pthread_setcancelstate(), and pthread_setcanceltype().
tcb_cancel_enabled()
static constexpr bool mlibc::tcb_cancel_enabled (int value) static constexpr
Definition at line 63 of file tcb.hpp.
{
         return (value & tcbCancelEnableBit);
     }
References anonymous_namespace{tcb.hpp}::tcbCancelEnableBit, and value.
Referenced by pthread_cancel().
tcb_cancelled()
static constexpr bool mlibc::tcb_cancelled (int value) static constexpr
Definition at line 68 of file tcb.hpp.
{
         return (value & (tcbCancelEnableBit | tcbCancelTriggerBit))
                == (tcbCancelEnableBit | tcbCancelTriggerBit);
     }
References anonymous_namespace{tcb.hpp}::tcbCancelEnableBit, anonymous_namespace{tcb.hpp}::tcbCancelTriggerBit, and value.
Referenced by do_cp_syscall().
this_tid()
unsigned int mlibc::this_tid () inline
Definition at line 7 of file tid.hpp.
{
         // During RTDL initialization, we don't have a TCB.
         if (mlibc::tcb_available_flag) {
             auto tcb = get_current_tcb();
             return tcb->tid;
         } else if (mlibc::sys_futex_tid) {
             return mlibc::sys_futex_tid();
         } else {
             return 1;
         }
     }
References get_current_tcb(), sys_futex_tid(), and tcb_available_flag.
Referenced by FutexLockImpl< Recursive >::lock(), pthread_mutex_lock(), pthread_mutex_trylock(), pthread_mutex_unlock(), FutexLockImpl< Recursive >::try_lock(), and FutexLockImpl< Recursive >::unlock().
UNIMPLEMENTED()
int void size_t off_t ssize_t* bytes_read mlibc::UNIMPLEMENTED ("sys_pread")
widen()
template<typename Char > Char mlibc::widen (char c)
Definition at line 57 of file strtol.hpp.
 { return static_cast<Char>(c); }
References c.
Variable Documentation
arg
int unsigned long void* mlibc::arg
Definition at line 220 of file generic.cpp.
Referenced by ioctl_drm(), and sys_ioctl().
attr
int struct termios* mlibc::attr
Initial value:
{
    int ret
Definition at line 64 of file generic.cpp.
Referenced by child(), main(), posix_spawnattr_init(), posix_spawnattr_setflags(), posix_spawnattr_setpgroup(), posix_spawnattr_setsigdefault(), posix_spawnattr_setsigmask(), pthread_attr_getaffinity_np(), pthread_attr_getdetachstate(), pthread_attr_getguardsize(), pthread_attr_getinheritsched(), pthread_attr_getschedparam(), pthread_attr_getschedpolicy(), pthread_attr_getscope(), pthread_attr_getsigmask_np(), pthread_attr_getstack(), pthread_attr_getstackaddr(), pthread_attr_getstacksize(), pthread_attr_init(), pthread_attr_setaffinity_np(), pthread_attr_setdetachstate(), pthread_attr_setguardsize(), pthread_attr_setinheritsched(), pthread_attr_setschedparam(), pthread_attr_setschedpolicy(), pthread_attr_setscope(), pthread_attr_setsigmask_np(), pthread_attr_setstack(), pthread_attr_setstackaddr(), pthread_attr_setstacksize(), pthread_barrier_init(), pthread_barrierattr_getpshared(), pthread_barrierattr_init(), pthread_barrierattr_setpshared(), pthread_cond_init(), pthread_condattr_destroy(), pthread_condattr_getclock(), pthread_condattr_getpshared(), pthread_condattr_init(), pthread_condattr_setclock(), pthread_condattr_setpshared(), pthread_create(), pthread_getattr_np(), pthread_mutex_init(), pthread_mutexattr_destroy(), pthread_mutexattr_getprioceiling(), pthread_mutexattr_getprotocol(), pthread_mutexattr_getpshared(), pthread_mutexattr_getrobust(), pthread_mutexattr_gettype(), pthread_mutexattr_init(), pthread_mutexattr_setprioceiling(), pthread_mutexattr_setprotocol(), pthread_mutexattr_setpshared(), pthread_mutexattr_setrobust(), pthread_mutexattr_settype(), pthread_rwlock_init(), pthread_rwlockattr_getpshared(), pthread_rwlockattr_init(), pthread_rwlockattr_setpshared(), sys_tcgetattr(), sys_tcsetattr(), tcgetattr(), tcsetattr(), test_affinity(), test_attr(), test_detachstate(), test_getattrnp(), test_guardsize(), test_inheritsched(), test_schedparam(), test_schedpolicy(), test_scope(), test_sigmask(), test_stack(), test_stackaddr(), test_stacksize(), test_timedwait_timedout(), testAttr(), testNormal(), and testRecursive().
buf
int void* mlibc::buf
Definition at line 47 of file filesystem.cpp.
Referenced by lookup_name_dns(), lookup_name_hosts(), lookup_name_ip(), lookup_name_null(), lookup_serv_by_name(), lookup_serv_by_port(), lookup_serv_file_name(), lookup_serv_file_port(), parse_rest(), read_dns_name(), sys_faccessat(), sys_fstatfs(), sys_pread(), sys_read(), sys_statfs(), sys_ttyname(), and sys_uname().
c_locale
constinit const locale_description mlibc::c_locale
Initial value:
{
        .name = "C",
        .lc = c_lconv
    }
Definition at line 48 of file locale-stubs.cpp.
Referenced by __mlibc_initLocale(), and query_locale_description().
collate_facet
const locale_description* mlibc::collate_facet
Definition at line 66 of file locale-stubs.cpp.
Referenced by __mlibc_initLocale(), and setlocale().
count
int void size_t mlibc::count
Definition at line 47 of file filesystem.cpp.
Referenced by lookup_serv_by_name(), sys_poll(), sys_pread(), sys_pwrite(), sys_read(), and sys_write().
ctype_facet
const locale_description* mlibc::ctype_facet
Definition at line 67 of file locale-stubs.cpp.
Referenced by __mlibc_initLocale(), and setlocale().
default_stacksize [1/6]
constexpr size_t mlibc::default_stacksize = 0x1000000 static constexpr
Definition at line 34 of file thread.cpp.
Referenced by sys_prepare_stack().
default_stacksize [2/6]
constexpr size_t mlibc::default_stacksize = 0x200000 static constexpr
Definition at line 31 of file thread.cpp.
default_stacksize [3/6]
constexpr size_t mlibc::default_stacksize = 0x200000 static constexpr
Definition at line 31 of file thread.cpp.
default_stacksize [4/6]
constexpr size_t mlibc::default_stacksize = 0x200000 static constexpr
Definition at line 30 of file thread.cpp.
default_stacksize [5/6]
constexpr size_t mlibc::default_stacksize = 0x200000 static constexpr
Definition at line 31 of file thread.cpp.
default_stacksize [6/6]
constexpr size_t mlibc::default_stacksize = 0x200000 static constexpr
Definition at line 31 of file thread.cpp.
destpath
int const char* mlibc::destpath
Initial value:
{
    auto result =
        syscall(SYS_LINK, srcpath, strlen(srcpath), destpath, strlen(destpath))
Definition at line 183 of file filesystem.cpp.
Referenced by sys_link().
except_set
int int* STUB_ONLY int fd_set fd_set fd_set* mlibc::except_set
Definition at line 127 of file generic.cpp.
Referenced by for(), if(), pselect(), select(), and sys_pselect().
fd
int size_t int int int mlibc::fd
Definition at line 423 of file generic.cpp.
Referenced by __attribute__(), for(), ioctl_drm(), lookup_addr_dns(), lookup_name_dns(), sys_bind(), sys_close(), sys_connect(), sys_dup(), sys_dup2(), sys_epoll_create(), sys_epoll_ctl(), sys_eventfd_create(), sys_fadvise(), sys_fallocate(), sys_fchdir(), sys_fchmod(), sys_fchmodat(), sys_fcntl(), sys_fdatasync(), sys_fgetxattr(), sys_flistxattr(), sys_flock(), sys_fremovexattr(), sys_fsetxattr(), sys_fstatfs(), sys_fsync(), sys_ftruncate(), sys_getsockopt(), sys_if_indextoname(), sys_if_nametoindex(), sys_ioctl(), sys_isatty(), sys_listen(), sys_memfd_create(), sys_msg_send(), sys_open(), sys_openat(), sys_peername(), sys_pread(), sys_pselect(), sys_ptsname(), sys_pwrite(), sys_read(), sys_readv(), sys_seek(), sys_setsockopt(), sys_signalfd_create(), sys_socket(), sys_sockname(), sys_stat(), sys_tcgetattr(), sys_tcsetattr(), sys_timerfd_create(), sys_timerfd_settime(), sys_ttyname(), sys_unlockpt(), sys_vm_map(), and sys_write().
flags
int int int mlibc::flags
Definition at line 297 of file aero.cpp.
Referenced by __attribute__(), _vsnprintf(), accept4(), AM_drawWalls(), delete_module(), dlopen(), do_glob(), epoll_create1(), eventfd(), faccessat(), fchmodat(), fchownat(), fdopen(), fdopendir(), fnmatch(), fnmatch_internal(), fopen(), format_string_loop(), format_string_loop_libint(), fsetxattr(), fstatat(), getaddrinfo(), getnameinfo(), getrandom(), glob(), inotify_init1(), VMwareMouse::InterruptCallback(), linkat(), lookup_name_null(), lookup_serv_by_name(), lsetxattr(), mkostemp(), mlockall(), mmap(), mount(), mremap(), msync(), open(), openat(), out_rev_(), out_rev_libint(), P_LoadSegs(), P_PathTraverse(), P_RespawnSpecials(), P_SpawnMapThing(), parse_flags(), parse_flags_libint(), mlibc::fd_file::parse_modestring(), pat_next(), pipe2(), posix_openpt(), posix_spawnattr_setflags(), print_broken_up_decimal(), print_decimal_number(), print_exponential_number(), print_floating_point(), print_integer(), print_integer_finalization(), print_integer_finalization_libint(), print_integer_libint(), pthread_mutex_unlock(), recv(), recvfrom(), recvmsg(), Scope::resolveGlobalOrLocal(), Scope::resolveSymbol(), run_test(), send(), sendmsg(), sendto(), setxattr(), shm_open(), signalfd(), sys_dup(), sys_dup2(), sys_epoll_create(), sys_eventfd_create(), sys_faccessat(), sys_fchmodat(), sys_fchownat(), sys_fsetxattr(), sys_getrandom(), sys_linkat(), sys_lsetxattr(), sys_memfd_create(), sys_msg_recv(), sys_msg_send(), sys_open(), sys_open(), sys_openat(), sys_pipe(), sys_setxattr(), sys_signalfd_create(), sys_timerfd_create(), sys_utimensat(), sys_vm_map(), sys_waitpid(), timer_settime(), timerfd_create(), timerfd_settime(), tre_copy_ast(), tre_expand_ast(), umount2(), unlinkat(), utimensat(), waitpid(), we_askshell(), we_check(), and wordexp().
guard
GlobalConfigGuard mlibc::guard
Definition at line 11 of file global-config.cpp.
Referenced by __cxa_guard_acquire(), __cxa_guard_release(), pthread_getspecific(), pthread_key_create(), pthread_key_delete(), and pthread_setspecific().
infoLogger
frg::stack_buffer_logger< InfoSink, 512 > mlibc::infoLogger
Definition at line 8 of file debug.cpp.
Referenced by __ensure_warn(), __freadahead(), __fsetlocking(), __mlibc_sigentry(), __openlog(), Loader::_buildTlsMaps(), ObjectRepository::_fetchFromFile(), ObjectRepository::_fetchFromPhdrs(), ObjectRepository::_parseDynamic(), Loader::_processLazyRelocations(), Loader::_processRela(), Scope::_resolveNext(), mlibc::abstract_file::_save_pos(), _vsyslog(), accessDtv(), allocateTcb(), child(), mlibc::fd_file::close(), confstr(), mlibc::fd_file::determine_bufmode(), dlvsym(), do_scanf(), doInitialize(), duplocale(), endspent(), execvpe(), fallocate(), fflush(), fflush_unlocked(), anonymous_namespace{environment.cpp}::find_environ_index(), free(), freeifaddrs(), freelocale(), fwrite_unlocked(), anonymous_namespace{pthread-stubs.cpp}::get_own_stackinfo(), getgrouplist(), getifaddrs(), getnameinfo(), iconv(), iconv_open(), inet_pton(), initgroups(), Loader::initObjects(), initTlsObjects(), interpreterMain(), ioctl_drm(), mlibc::charset::is_alnum(), mlibc::charset::is_alpha(), mlibc::charset::is_blank(), mlibc::charset::is_digit(), mlibc::charset::is_graph(), mlibc::charset::is_lower(), mlibc::charset::is_print(), mlibc::charset::is_punct(), mlibc::charset::is_space(), mlibc::charset::is_upper(), mlibc::charset::is_xdigit(), lckpwdf(), Loader::linkObjects(), lookup_addr_dns(), lookup_name_dns(), malloc(), mkdirat(), mkdtemp(), newlocale(), nl_langinfo(), openpty(), PrintfAgent< F >::operator()(), mlibc::fd_file::parse_modestring(), pathconf(), posix_fadvise(), posix_madvise(), pthread_create(), pthread_getattr_np(), pthread_setname_np(), realloc(), realpath(), ObjectRepository::requestObjectWithName(), res_init(), res_nclose(), res_ninit(), ScopeTrace::ScopeTrace(), sem_init(), sem_timedwait(), setlocale(), setuid(), shmget(), shutdown(), strsignal(), strtod_l(), strtof_l(), sys_getegid(), sys_geteuid(), sys_getgid(), sys_getpgid(), sys_getschedparam(), sys_getsockopt(), sys_getuid(), sys_libc_panic(), sys_madvise(), sys_setegid(), sys_seteuid(), sys_setgid(), sys_setpgid(), sys_setsid(), sys_setsockopt(), sys_sigaction(), sys_signalfd_create(), sys_sigprocmask(), sys_stat(), sys_tcdrain(), sys_tcsetattr(), sys_ttyname(), sys_waitpid(), sys_yield(), sysconf(), mlibc::charset::to_lower(), mlibc::charset::to_upper(), tzset(), ulckpwdf(), anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt(), uselocale(), vsyslog(), wait3(), wcsftime(), wctype(), mlibc::abstract_file::~abstract_file(), ScopeTrace::~ScopeTrace(), and anonymous_namespace{file-io.cpp}::stdio_guard::~stdio_guard().
messages_facet
const locale_description* mlibc::messages_facet
Definition at line 71 of file locale-stubs.cpp.
Referenced by __mlibc_initLocale(), and setlocale().
monetary_facet
const locale_description* mlibc::monetary_facet
Definition at line 68 of file locale-stubs.cpp.
Referenced by __mlibc_initLocale(), localeconv(), and setlocale().
nanos
* mlibc::nanos
Initial value:
{
    struct timespec time = {.tv_sec = *secs, .tv_nsec = *nanos}
Definition at line 786 of file generic.cpp.
Referenced by gettimeofday(), sleep(), sys_clock_get(), sys_clock_getres(), time(), and usleep().
new_offset
* mlibc::new_offset
Initial value:
{
    auto result = syscall(SYS_SEEK, fd, offset, whence)
Definition at line 50 of file filesystem.cpp.
Referenced by mlibc::abstract_file::_save_pos(), mlibc::abstract_file::_write_back(), fseek(), mlibc::fd_file::io_seek(), mlibc::mem_file::io_seek(), lseek(), lseek64(), mlibc::abstract_file::seek(), and sys_seek().
num_events
int int* STUB_ONLY int fd_set fd_set fd_set const struct timespec const sigset_t int* mlibc::num_events
Initial value:
{
    struct pollfd *fds = (struct pollfd *)calloc(nfds, sizeof(struct pollfd))
Definition at line 128 of file generic.cpp.
Referenced by poll(), pselect(), select(), sys_poll(), sys_ppoll(), and sys_pselect().
numeric_facet
const locale_description* mlibc::numeric_facet
Definition at line 69 of file locale-stubs.cpp.
Referenced by __mlibc_initLocale(), localeconv(), and setlocale().
off
int void size_t off_t mlibc::off
Definition at line 48 of file filesystem.cpp.
Referenced by inet_ntop(), pread(), pwrite(), sys_pread(), and sys_pwrite().
offset
int size_t int int int off_t mlibc::offset
Definition at line 50 of file filesystem.cpp.
Referenced by mlibc::fd_file::determine_type(), mlibc::fd_file::io_seek(), mlibc::mem_file::io_seek(), read_dns_name(), mlibc::abstract_file::seek(), sys_fadvise(), sys_fallocate(), sys_seek(), and sys_vm_map().
open_dirs
frg::hash_map<int, ReadDirState *, frg::hash<int>, MemoryAllocator> mlibc::open_dirs {frg::hash<int>{}, getAllocator()} static
Definition at line 277 of file generic.cpp.
Referenced by get_dir_state().
page_size
constexpr size_t mlibc::page_size = 0x1000 inline constexpr
Definition at line 8 of file arch-defs.hpp.
Referenced by getpagesize(), and sysconf().
panicLogger
frg::stack_buffer_logger< PanicSink, 512 > mlibc::panicLogger
Definition at line 9 of file debug.cpp.
Referenced by __cxa_pure_virtual(), __ensure_fail(), __frigg_assert_fail(), __stack_chk_fail(), __ubsan_handle_add_overflow(), __ubsan_handle_builtin_unreachable(), __ubsan_handle_divrem_overflow(), __ubsan_handle_invalid_builtin(), __ubsan_handle_load_invalid_value(), __ubsan_handle_missing_return(), __ubsan_handle_mul_overflow(), __ubsan_handle_negate_overflow(), __ubsan_handle_out_of_bounds(), __ubsan_handle_pointer_overflow(), __ubsan_handle_shift_out_of_bounds(), __ubsan_handle_sub_overflow(), __ubsan_handle_type_mismatch_v1(), __ubsan_handle_vla_bound_not_positive(), Loader::_buildTlsMaps(), ObjectRepository::_discoverDependencies(), ObjectRepository::_fetchFromFile(), ObjectRepository::_parseDynamic(), Loader::_processLazyRelocations(), Loader::_processRela(), abort(), file_window::file_window(), forkpty(), interpreterMain(), lazyRelocate(), FutexLockImpl< Recursive >::lock(), pthread_barrier_destroy(), pthread_barrier_wait(), pthread_cond_timedwait(), pthread_mutex_lock(), pthread_rwlock_rdlock(), pthread_rwlock_tryrdlock(), pthread_rwlock_trywrlock(), pthread_rwlock_wrlock(), mlibc::abstract_file::read(), sem_wait(), strftime(), sys_getsockopt(), sys_setsockopt(), sysconf(), and mlibc::abstract_file::write().
posix_locale
constinit const locale_description mlibc::posix_locale
Initial value:
{
        .name = "POSIX",
        .lc = c_lconv
    }
Definition at line 53 of file locale-stubs.cpp.
Referenced by query_locale_description().
prot
int size_t int mlibc::prot
Definition at line 422 of file generic.cpp.
Referenced by ObjectRepository::_fetchFromFile(), mmap(), mprotect(), sys_vm_map(), and sys_vm_protect().
read_set
int int* STUB_ONLY int fd_set* mlibc::read_set
Definition at line 126 of file generic.cpp.
Referenced by for(), if(), pselect(), select(), and sys_pselect().
rem
struct timespec mlibc::rem = {.tv_sec = 0, .tv_nsec = 0}
Definition at line 786 of file generic.cpp.
Referenced by __divmoddi4().
request
int unsigned long mlibc::request
Definition at line 220 of file generic.cpp.
Referenced by ioctl(), ioctl_drm(), lookup_addr_dns(), lookup_name_dns(), sys_fcntl(), and sys_ioctl().
res_except_set
FD_ZERO & mlibc::res_except_set
Definition at line 160 of file generic.cpp.
Referenced by if(), and sys_pselect().
res_read_set
FD_ZERO & mlibc::res_read_set
Definition at line 160 of file generic.cpp.
Referenced by if(), and sys_pselect().
res_write_set
FD_ZERO & mlibc::res_write_set
Definition at line 160 of file generic.cpp.
Referenced by if(), and sys_pselect().
result
* mlibc::result
Initial value:
{
    __syscall_ret ret = __syscall(SYS_ioctl, fd, request, arg)
Definition at line 220 of file generic.cpp.
Referenced by __attribute__(), __mlibc_enter_thread(), AllocateMIDIChannel(), asprintf(), buffer_gadget(), buffer_gadget_libint(), cag_option_get_print_indention(), Time::ConvertFromUnix(), cwk_path_get_first_segment_joined(), cwk_path_get_next_segment_joined(), cwk_path_get_previous_segment_joined(), D_FindAllIWADs(), D_FindIWAD(), D_InitNetGame(), D_PopEvent(), D_TryFindWADByName(), do_cp_syscall(), dprintf(), EscapeShellString(), fcntl(), FixedDiv(), fmaf(), fprintf(), fscanf(), function_gadget(), function_gadget_libint(), GenerateStretchTable(), get_dir_state(), GetDefaultConfigDir(), GetDefaultForName(), GetFileNumber(), getutent(), GUS_WriteConfig(), I_CDMusPlay(), I_CDMusResume(), I_CDMusStop(), if(), ioctl(), load(), M_snprintf(), M_StringDuplicate(), M_StringJoin(), M_StringReplace(), M_vsnprintf(), main(), MappingIndex(), md5File(), md5String(), std::string::operator+(), parseHandle(), parseInline(), parseLength(), parseSimple(), PlayersInGame(), printf(), ReadMusHeader(), saveg_read16(), saveg_read32(), saveg_read8(), scanf(), snprintf(), sprintf(), sscanf(), strcasecmp(), strncasecmp(), strptime(), strtofp(), sys_accept(), sys_access(), sys_bind(), sys_chdir(), sys_clock_get(), sys_clone(), sys_close(), sys_connect(), sys_dup(), sys_dup2(), sys_epoll_create(), sys_epoll_ctl(), sys_epoll_pwait(), sys_eventfd_create(), sys_execve(), sys_fcntl(), sys_fork(), sys_getcwd(), sys_gethostname(), sys_getitimer(), sys_getpid(), sys_getppid(), sys_isatty(), sys_kill(), sys_listen(), sys_mkdir(), sys_msg_recv(), sys_msg_send(), sys_open(), sys_pipe(), sys_ppoll(), sys_read(), sys_read_entries(), sys_readlink(), sys_rename(), sys_setitimer(), sys_sigprocmask(), sys_sleep(), sys_socket(), sys_socketpair(), sys_stat(), sys_tcb_set(), sys_tcgetattr(), sys_tcsetattr(), sys_uname(), sys_vm_map(), sys_write(), std::transform(), tre_tnfa_run_backtrack(), vsscanf(), W_CacheLumpNum(), W_LumpNameHash(), W_OpenFile(), W_StdC_OpenFile(), W_StdC_Read(), Z_Malloc(), and ZenityErrorBox().
ret
__syscall_ret mlibc::ret = sys_ppoll(fds, nfds, timeout, sigmask, num_events)
Definition at line 154 of file generic.cpp.
Referenced by get_nameserver(), if(), sc_error(), sc_int_result(), sc_ptr_result(), sys_chmod(), sys_clock_getres(), sys_fadvise(), sys_fchmod(), sys_fchmodat(), sys_fchownat(), sys_fdatasync(), sys_fgetxattr(), sys_flistxattr(), sys_fremovexattr(), sys_fsetxattr(), sys_fstatfs(), sys_fsync(), sys_ftruncate(), sys_getcwd(), sys_getgroups(), sys_getpriority(), sys_getrandom(), sys_getrlimit(), sys_getsid(), sys_gettid(), sys_getxattr(), sys_if_indextoname(), sys_if_nametoindex(), sys_inotify_create(), sys_lgetxattr(), sys_link(), sys_linkat(), sys_listxattr(), sys_llistxattr(), sys_lremovexattr(), sys_lsetxattr(), sys_mkdirat(), sys_mknodat(), sys_openat(), sys_pread(), sys_pwrite(), sys_readv(), sys_removexattr(), sys_renameat(), sys_rmdir(), sys_sched_yield(), sys_seek(), sys_sethostname(), sys_setpriority(), sys_setrlimit(), sys_setxattr(), sys_sigaltstack(), sys_sigentry(), sys_signalfd_create(), sys_sigsuspend(), sys_sigtimedwait(), sys_statfs(), sys_symlink(), sys_symlinkat(), sys_times(), sys_umask(), sys_utimensat(), and sys_waitpid().
ret_pid
* mlibc::ret_pid
Initial value:
{
    if (ru) {
        mlibc::infoLogger()
            << "mlibc: struct rusage in sys_waitpid is unsupported"
            << frg::endlog;
        return ENOSYS;
    }
    auto result = syscall(SYS_WAITPID, pid, status, flags)
Definition at line 298 of file aero.cpp.
Referenced by sys_signalfd_create(), and sys_waitpid().
ret_value
pid_t mlibc::ret_value = (void *)ret.ret
Definition at line 425 of file generic.cpp.
Referenced by sys_inotify_create(), and sys_signalfd_create().
return
mlibc::return
Definition at line 313 of file aero.cpp.
ru
int int int struct rusage * mlibc::ru
Definition at line 297 of file aero.cpp.
Referenced by sys_signalfd_create(), sys_waitpid(), sysconf(), and wait4().
secs
* mlibc::secs = rem.tv_sec
Definition at line 793 of file generic.cpp.
Referenced by sleep(), sys_clock_get(), sys_clock_getres(), time(), and timegm().
sigmask
int int* STUB_ONLY int fd_set fd_set fd_set const struct timespec const sigset_t* mlibc::sigmask
Definition at line 128 of file generic.cpp.
Referenced by epoll_pwait(), posix_spawnattr_setsigmask(), ppoll(), pselect(), pthread_attr_getsigmask_np(), pthread_attr_setsigmask_np(), sigsuspend(), sys_epoll_pwait(), sys_ppoll(), and sys_pselect().
size
int size_t mlibc::size
Definition at line 422 of file generic.cpp.
Referenced by lookup_addr_hosts(), strncasecmp(), sys_anon_allocate(), sys_anon_free(), sys_fallocate(), sys_fgetxattr(), sys_flistxattr(), sys_fsetxattr(), sys_ftruncate(), sys_getcwd(), sys_getgroups(), sys_getsockopt(), sys_getxattr(), sys_lgetxattr(), sys_listxattr(), sys_llistxattr(), sys_lsetxattr(), sys_sethostname(), sys_setsockopt(), sys_setxattr(), sys_ttyname(), sys_vm_map(), sys_vm_protect(), sys_vm_remap(), and sys_vm_unmap().
status
int int * mlibc::status
Definition at line 297 of file aero.cpp.
Referenced by _Exit(), _exit(), Recovery::ChangeSampleRate(), Recovery::ChangeVolume(), error(), error_at_line(), EV_StopPlat(), exit(), InitializeMemoryManagement(), Gigabit::InterruptCallback(), main(), P_ActivateInStasis(), pclose(), Recovery::PlayAudio(), regexec(), run_cmd(), sys_exit(), sys_signalfd_create(), sys_waitpid(), system(), tre_add_tags(), tre_compute_nfl(), tre_copy_ast(), tre_expand_ast(), tre_match_empty(), wait(), wait3(), wait4(), Tasking::Task::WaitForProcessStatus(), Tasking::Task::WaitForThreadStatus(), waitpid(), and we_askshell().
tcb_available_flag
bool mlibc::tcb_available_flag = true constexpr
Definition at line 75 of file tcb.hpp.
Referenced by this_tid().
time_facet
const locale_description* mlibc::time_facet
Definition at line 70 of file locale-stubs.cpp.
Referenced by __mlibc_initLocale(), and setlocale().
timeout
int int* STUB_ONLY int fd_set fd_set fd_set const struct timespec* mlibc::timeout
Definition at line 127 of file generic.cpp.
Referenced by epoll_pwait(), epoll_wait(), poll(), ppoll(), pselect(), pthread_cond_timedwait(), select(), sigtimedwait(), sys_epoll_pwait(), sys_poll(), sys_ppoll(), sys_pselect(), and sys_sigtimedwait().
whence
int void size_t off_t ssize_t* bytes_read off_t int mlibc::whence
Definition at line 50 of file filesystem.cpp.
Referenced by fseek(), fseeko(), mlibc::fd_file::io_seek(), mlibc::mem_file::io_seek(), lseek(), lseek64(), mem_fseek(), mlibc::abstract_file::seek(), and sys_seek().
window
* mlibc::window
Initial value:
{
    __syscall_ret ret = __syscall(SYS_mmap, hint, size, (uint64_t)prot << 32 | flags, fd, offset)
Definition at line 423 of file generic.cpp.
Referenced by get_localtime_window(), mmap(), mremap(), sys_vm_map(), and sys_vm_remap().
write_set
int int* STUB_ONLY int fd_set fd_set* mlibc::write_set
Definition at line 126 of file generic.cpp.
Referenced by for(), if(), pselect(), select(), and sys_pselect().