Fennix Userspace: Userspace/apps/base/bash/findcmd.c File Reference
findcmd.c File Reference
#include "config.h"
#include <stdio.h>
#include "chartypes.h"
#include "bashtypes.h"
#include "filecntl.h"
#include "posixstat.h"
#include <errno.h>
#include "bashansi.h"
#include "memalloc.h"
#include "shell.h"
#include "execute_cmd.h"
#include "flags.h"
#include "hashlib.h"
#include "pathexp.h"
#include "hashcmd.h"
#include "findcmd.h"
#include <glob/strmatch.h>
Functions
static char *_find_user_command_internal PARAMS ((const char *, int))
static char *find_user_command_in_path PARAMS ((const char *, char *, int, int *))
static char *find_in_path_element PARAMS ((const char *, char *, int, int, struct stat *, int *))
static char *get_next_path_element PARAMS ((char *, int *))
void setup_exec_ignore (char *varname)
static int exec_name_should_ignore (char *name) const
int file_status (char *name) const
int executable_file (char *file) const
int is_directory (char *file) const
int executable_or_directory (char *file) const
char * find_user_command (char *name) const
char * find_path_file (char *name) const
static char * _find_user_command_internal (char *name, int flags) const
static char * find_user_command_internal (char *name, int flags) const
static char * get_next_path_element (char *path_list, int *path_index_pointer)
char * search_for_command (char *pathname, int flags) const
char * user_command_matches (char *name, int flags, int state) const
static char * find_absolute_program (char *name, int flags) const
static char * find_in_path_element (char *name, char *path, int flags, int name_len, struct stat *dotinfop, int *rflagsp) const
static char * find_user_command_in_path (char *name, char *path_list, int flags, int *rflagsp) const
char * find_in_path (char *name, char *path_list, int flags) const
Variables
int errno
static char * file_to_lose_on
int check_hashed_filenames = CHECKHASH_DEFAULT
int dot_found_in_search = 0
static struct ignorevar execignore
Function Documentation
_find_user_command_internal()
static char* _find_user_command_internal (char * name, int flags) const static
Definition at line 260 of file findcmd.c.
 {
   char *path_list, *cmd;
   SHELL_VAR *var;
   /* Search for the value of PATH in both the temporary environments and
      in the regular list of variables. */
   if (var = find_variable_tempenv ("PATH")) /* XXX could be array? */
     path_list = value_cell (var);
   else
     path_list = (char *)NULL;
   if (path_list == 0 || *path_list == '\0')
     return (savestring (name));
   cmd = find_user_command_in_path (name, path_list, flags, (int *)0);
   return (cmd);
 }
References cmd, find_user_command_in_path(), find_variable_tempenv(), flags, NULL, savestring(), and value_cell.
Referenced by find_user_command_internal().
exec_name_should_ignore()
static int exec_name_should_ignore (char * name) const static
Definition at line 99 of file findcmd.c.
 {
   struct ign *p;
   for (p = execignore.ignores; p && p->val; p++)
     if (strmatch (p->val, (char *)name, FNMATCH_EXTFLAG|FNM_CASEFOLD) != FNM_NOMATCH)
       return 1;
   return 0;
 }
References execignore, FNM_CASEFOLD, FNM_NOMATCH, FNMATCH_EXTFLAG, ignorevar::ignores, p, and strmatch().
Referenced by file_status(), and find_in_path_element().
executable_file()
int executable_file (char * file) const
Definition at line 205 of file findcmd.c.
 {
   int s;
   s = file_status (file);
 #if defined (EISDIR)
   if (s & FS_DIRECTORY)
     errno = EISDIR; /* let's see if we can improve error messages */
 #endif
   return ((s & FS_EXECABLE) && ((s & FS_DIRECTORY) == 0));
 }
References EISDIR, errno, file_status(), FS_DIRECTORY, FS_EXECABLE, and s.
Referenced by phash_search(), and shell_execve().
executable_or_directory()
int executable_or_directory (char * file) const
Definition at line 226 of file findcmd.c.
 {
   int s;
   s = file_status (file);
   return ((s & FS_EXECABLE) || (s & FS_DIRECTORY));
 }
References file_status(), FS_DIRECTORY, FS_EXECABLE, and s.
file_status()
int file_status (char * name) const
Definition at line 115 of file findcmd.c.
 {
   struct stat finfo;
   int r;
   /* Determine whether this file exists or not. */
   if (stat (name, &finfo) < 0)
     return (0);
   /* If the file is a directory, then it is not "executable" in the
      sense of the shell. */
   if (S_ISDIR (finfo.st_mode))
     return (FS_EXISTS|FS_DIRECTORY);
   r = FS_EXISTS;
 #if defined (HAVE_EACCESS)
   /* Use eaccess(2) if we have it to take things like ACLs and other
      file access mechanisms into account.  eaccess uses the effective
      user and group IDs, not the real ones.  We could use sh_eaccess,
      but we don't want any special treatment for /dev/fd. */
   if (exec_name_should_ignore (name) == 0 && eaccess (name, X_OK) == 0)
     r |= FS_EXECABLE;
   if (eaccess (name, R_OK) == 0)
     r |= FS_READABLE;
   return r;
 #elif defined (AFS)
   /* We have to use access(2) to determine access because AFS does not
      support Unix file system semantics.  This may produce wrong
      answers for non-AFS files when ruid != euid.  I hate AFS. */
   if (exec_name_should_ignore (name) == 0 && access (name, X_OK) == 0)
     r |= FS_EXECABLE;
   if (access (name, R_OK) == 0)
     r |= FS_READABLE;
   return r;
 #else /* !HAVE_EACCESS && !AFS */
   /* Find out if the file is actually executable.  By definition, the
      only other criteria is that the file has an execute bit set that
      we can use.  The same with whether or not a file is readable. */
   /* Root only requires execute permission for any of owner, group or
      others to be able to exec a file, and can read any file. */
   if (current_user.euid == (uid_t)0)
     {
       r |= FS_READABLE;
       if (exec_name_should_ignore (name) == 0 && (finfo.st_mode & S_IXUGO))
     r |= FS_EXECABLE;
       return r;
     }
   /* If we are the owner of the file, the owner bits apply. */
   if (current_user.euid == finfo.st_uid)
     {
       if (exec_name_should_ignore (name) == 0 && (finfo.st_mode & S_IXUSR))
     r |= FS_EXECABLE;
       if (finfo.st_mode & S_IRUSR)
     r |= FS_READABLE;
     }
   /* If we are in the owning group, the group permissions apply. */
   else if (group_member (finfo.st_gid))
     {
       if (exec_name_should_ignore (name) == 0 && (finfo.st_mode & S_IXGRP))
     r |= FS_EXECABLE;
       if (finfo.st_mode & S_IRGRP)
     r |= FS_READABLE;
     }
   /* Else we check whether `others' have permission to execute the file */
   else
     {
       if (exec_name_should_ignore (name) == 0 && finfo.st_mode & S_IXOTH)
     r |= FS_EXECABLE;
       if (finfo.st_mode & S_IROTH)
     r |= FS_READABLE;
     }
   return r;
 #endif /* !AFS */
 }
References access(), current_user, user_info::euid, exec_name_should_ignore(), FS_DIRECTORY, FS_EXECABLE, FS_EXISTS, FS_READABLE, group_member(), R_OK, S_IRGRP, S_IROTH, S_IRUSR, S_ISDIR, S_IXGRP, S_IXOTH, S_IXUGO, S_IXUSR, stat::st_gid, stat::st_mode, stat::st_uid, and X_OK.
Referenced by executable_file(), executable_or_directory(), find_absolute_program(), find_in_path_element(), get_bash_name(), is_directory(), and search_for_command().
find_absolute_program()
static char* find_absolute_program (char * name, int flags) const static
Definition at line 501 of file findcmd.c.
 {
   int st;
   st = file_status (name);
   /* If the file doesn't exist, quit now. */
   if ((st & FS_EXISTS) == 0)
     return ((char *)NULL);
   /* If we only care about whether the file exists or not, return
      this filename.  Otherwise, maybe we care about whether this
      file is executable.  If it is, and that is what we want, return it. */
   if ((flags & FS_EXISTS) || ((flags & FS_EXEC_ONLY) && (st & FS_EXECABLE)))
     return (savestring (name));
   return (NULL);
 }
References file_status(), flags, FS_EXEC_ONLY, FS_EXECABLE, FS_EXISTS, NULL, and savestring().
Referenced by find_user_command_in_path(), and user_command_matches().
find_in_path()
char* find_in_path (char * name, char * path_list, int flags) const
Definition at line 690 of file findcmd.c.
 {
   return (find_user_command_in_path (name, path_list, flags, (int *)0));
 }
References find_user_command_in_path(), and flags.
find_in_path_element()
static char* find_in_path_element (char * name, char * path, int flags, int name_len, struct stat * dotinfop, int * rflagsp) const static
Definition at line 523 of file findcmd.c.
 {
   int status;
   char *full_path, *xpath;
   xpath = (posixly_correct == 0 && *path == '~') ? bash_tilde_expand (path, 0) : path;
   /* Remember the location of "." in the path, in all its forms
      (as long as they begin with a `.', e.g. `./.') */
   /* We could also do this or something similar for all relative pathnames
      found while searching PATH. */
   if (dot_found_in_search == 0 && *xpath == '.')
     dot_found_in_search = same_file (".", xpath, dotinfop, (struct stat *)NULL);
   full_path = sh_makepath (xpath, name, 0);
   status = file_status (full_path);
   if (xpath != path)
     free (xpath);
   if (rflagsp)
     *rflagsp = status;
   if ((status & FS_EXISTS) == 0)
     {
       free (full_path);
       return ((char *)NULL);
     }
   /* The file exists.  If the caller simply wants the first file, here it is. */
   if (flags & FS_EXISTS)
     return (full_path);
   /* If we have a readable file, and the caller wants a readable file, this
      is it. */
   if ((flags & FS_READABLE) && (status & FS_READABLE))
     return (full_path);
   /* If the file is executable, then it satisfies the cases of
       EXEC_ONLY and EXEC_PREFERRED.  Return this file unconditionally. */
   if ((status & FS_EXECABLE) && (flags & (FS_EXEC_ONLY|FS_EXEC_PREFERRED)) &&
       (((flags & FS_NODIRS) == 0) || ((status & FS_DIRECTORY) == 0)))
     {
       FREE (file_to_lose_on);
       file_to_lose_on = (char *)NULL;
       return (full_path);
     }
   /* The file is not executable, but it does exist.  If we prefer
      an executable, then remember this one if it is the first one
      we have found. */
   if ((flags & FS_EXEC_PREFERRED) && file_to_lose_on == 0 && exec_name_should_ignore (full_path) == 0)
     file_to_lose_on = savestring (full_path);
   /* If we want only executable files, or we don't want directories and
      this file is a directory, or we want a readable file and this file
      isn't readable, fail. */
   if ((flags & (FS_EXEC_ONLY|FS_EXEC_PREFERRED)) ||
       ((flags & FS_NODIRS) && (status & FS_DIRECTORY)) ||
       ((flags & FS_READABLE) && (status & FS_READABLE) == 0))
     {
       free (full_path);
       return ((char *)NULL);
     }
   else
     return (full_path);
 }
References bash_tilde_expand(), dot_found_in_search, exec_name_should_ignore(), file_status(), file_to_lose_on, flags, FREE, free, FS_DIRECTORY, FS_EXEC_ONLY, FS_EXEC_PREFERRED, FS_EXECABLE, FS_EXISTS, FS_NODIRS, FS_READABLE, NULL, posixly_correct, same_file(), savestring(), sh_makepath(), and status.
Referenced by find_user_command_in_path(), and user_command_matches().
find_path_file()
char* find_path_file (char * name) const
Definition at line 253 of file findcmd.c.
 {
   return (find_user_command_internal (name, FS_READABLE));
 }
References find_user_command_internal(), and FS_READABLE.
Referenced by open_shell_script().
find_user_command()
char* find_user_command (char * name) const
Definition at line 241 of file findcmd.c.
 {
   return (find_user_command_internal (name, FS_EXEC_PREFERRED|FS_NODIRS));
 }
References find_user_command_internal(), FS_EXEC_PREFERRED, and FS_NODIRS.
Referenced by get_bash_name().
find_user_command_in_path()
static char* find_user_command_in_path (char * name, char * path_list, int flags, int * rflagsp) const static
Definition at line 610 of file findcmd.c.
 {
   char *full_path, *path;
   int path_index, name_len, rflags;
   struct stat dotinfo;
   /* We haven't started looking, so we certainly haven't seen
      a `.' as the directory path yet. */
   dot_found_in_search = 0;
   if (rflagsp)
     *rflagsp = 0;
   if (absolute_program (name))
     {
       full_path = find_absolute_program (name, flags);
       return (full_path);
     }
   if (path_list == 0 || *path_list == '\0')
     return (savestring (name));     /* XXX */
   file_to_lose_on = (char *)NULL;
   name_len = strlen (name);
   if (stat (".", &dotinfo) < 0)
     dotinfo.st_dev = dotinfo.st_ino = 0;
   path_index = 0;
   while (path_list[path_index])
     {
       /* Allow the user to interrupt out of a lengthy path search. */
       QUIT;
       path = get_next_path_element (path_list, &path_index);
       if (path == 0)
     break;
       /* Side effects: sets dot_found_in_search, possibly sets
      file_to_lose_on. */
       full_path = find_in_path_element (name, path, flags, name_len, &dotinfo, &rflags);
       free (path);
       /* We use the file status flag bits to check whether full_path is a
      directory, which we reject here. */
       if (full_path && (rflags & FS_DIRECTORY))
     {
       free (full_path);
       continue;
     }
       if (full_path)
     {
       if (rflagsp)
         *rflagsp = rflags;
       FREE (file_to_lose_on);
       return (full_path);
     }
     }
   /* We didn't find exactly what the user was looking for.  Return
      the contents of FILE_TO_LOSE_ON which is NULL when the search
      required an executable, or non-NULL if a file was found and the
      search would accept a non-executable as a last resort.  If the
      caller specified FS_NODIRS, and file_to_lose_on is a directory,
      return NULL. */
   if (file_to_lose_on && (flags & FS_NODIRS) && file_isdir (file_to_lose_on))
     {
       free (file_to_lose_on);
       file_to_lose_on = (char *)NULL;
     }
   return (file_to_lose_on);
 }
References absolute_program(), dot_found_in_search, file_isdir(), file_to_lose_on, find_absolute_program(), find_in_path_element(), flags, FREE, free, FS_DIRECTORY, FS_NODIRS, get_next_path_element(), NULL, QUIT, savestring(), stat::st_dev, stat::st_ino, and strlen().
Referenced by _find_user_command_internal(), find_in_path(), and search_for_command().
find_user_command_internal()
static char* find_user_command_internal (char * name, int flags) const static
Definition at line 283 of file findcmd.c.
 {
 #ifdef __WIN32__
   char *res, *dotexe;
   dotexe = (char *)xmalloc (strlen (name) + 5);
   strcpy (dotexe, name);
   strcat (dotexe, ".exe");
   res = _find_user_command_internal (dotexe, flags);
   free (dotexe);
   if (res == 0)
     res = _find_user_command_internal (name, flags);
   return res;
 #else
   return (_find_user_command_internal (name, flags));
 #endif
 }
References _find_user_command_internal(), flags, free, strcat(), strcpy(), strlen(), and xmalloc.
Referenced by find_path_file(), and find_user_command().
get_next_path_element()
static char* get_next_path_element (char * path_list, int * path_index_pointer) static
Definition at line 308 of file findcmd.c.
 {
   char *path;
   path = extract_colon_unit (path_list, path_index_pointer);
   if (path == 0)
     return (path);
   if (*path == '\0')
     {
       free (path);
       path = savestring (".");
     }
   return (path);
 }
References extract_colon_unit(), free, and savestring().
Referenced by find_user_command_in_path(), and user_command_matches().
is_directory()
int is_directory (char * file) const
Definition at line 219 of file findcmd.c.
 {
   return (file_status (file) & FS_DIRECTORY);
 }
References file_status(), and FS_DIRECTORY.
Referenced by ln_main().
PARAMS() [1/4]
static char* get_next_path_element PARAMS ((char *, int *)) static
PARAMS() [2/4]
static char* find_user_command_in_path PARAMS ((const char *, char *, int, int *)) static
PARAMS() [3/4]
static char* find_in_path_element PARAMS ((const char *, char *, int, int, struct stat *, int *)) static
PARAMS() [4/4]
static char* _find_user_command_internal PARAMS ((const char *, int)) static
search_for_command()
char* search_for_command (char * pathname, int flags) const
Definition at line 336 of file findcmd.c.
 {
   char *hashed_file, *command, *path_list;
   int temp_path, st;
   SHELL_VAR *path;
   hashed_file = command = (char *)NULL;
   /* If PATH is in the temporary environment for this command, don't use the
      hash table to search for the full pathname. */
   path = find_variable_tempenv ("PATH");
   temp_path = path && tempvar_p (path);
   /* Don't waste time trying to find hashed data for a pathname
      that is already completely specified or if we're using a command-
      specific value for PATH. */
   if (temp_path == 0 && (flags & CMDSRCH_STDPATH) == 0 && absolute_program (pathname) == 0)
     hashed_file = phash_search (pathname);
   /* If a command found in the hash table no longer exists, we need to
      look for it in $PATH.  Thank you Posix.2.  This forces us to stat
      every command found in the hash table. */
   if (hashed_file && (posixly_correct || check_hashed_filenames))
     {
       st = file_status (hashed_file);
       if ((st & (FS_EXISTS|FS_EXECABLE)) != (FS_EXISTS|FS_EXECABLE))
     {
       phash_remove (pathname);
       free (hashed_file);
       hashed_file = (char *)NULL;
     }
     }
   if (hashed_file)
     command = hashed_file;
   else if (absolute_program (pathname))
     /* A command containing a slash is not looked up in PATH or saved in
        the hash table. */
     command = savestring (pathname);
   else
     {
       if (flags & CMDSRCH_STDPATH)
     path_list = conf_standard_path ();
       else if (temp_path || path)
     path_list = value_cell (path);
       else
     path_list = 0;
       command = find_user_command_in_path (pathname, path_list, FS_EXEC_PREFERRED|FS_NODIRS, &st);
       if (command && hashing_enabled && temp_path == 0 && (flags & CMDSRCH_HASH))
     {
       /* If we found the full pathname the same as the command name, the
          command probably doesn't exist.  Don't put it into the hash
          table unless it's an executable file in the current directory. */
       if (STREQ (command, pathname))
         {
           if (st & FS_EXECABLE)
             phash_insert ((char *)pathname, command, dot_found_in_search, 1);
         }
       /* If we're in posix mode, don't add files without the execute bit
          to the hash table. */
       else if (posixly_correct || check_hashed_filenames)
         {
           if (st & FS_EXECABLE)
             phash_insert ((char *)pathname, command, dot_found_in_search, 1);
         }
       else
         phash_insert ((char *)pathname, command, dot_found_in_search, 1);
     }
       if (flags & CMDSRCH_STDPATH)
     free (path_list);
     }
   return (command);
 }
References absolute_program(), check_hashed_filenames, CMDSRCH_HASH, CMDSRCH_STDPATH, conf_standard_path(), dot_found_in_search, file_status(), find_user_command_in_path(), find_variable_tempenv(), flags, free, FS_EXEC_PREFERRED, FS_EXECABLE, FS_EXISTS, FS_NODIRS, hashing_enabled, NULL, phash_insert(), phash_remove(), phash_search(), posixly_correct, savestring(), STREQ, tempvar_p, and value_cell.
Referenced by execute_disk_command(), and is_dirname().
setup_exec_ignore()
void setup_exec_ignore (char * varname)
Definition at line 92 of file findcmd.c.
 {
   setup_ignore_patterns (&execignore);
 }
References execignore, and setup_ignore_patterns().
Referenced by sv_execignore().
user_command_matches()
char* user_command_matches (char * name, int flags, int state) const
Definition at line 418 of file findcmd.c.
 {
   register int i;
   int  path_index, name_len;
   char *path_list, *path_element, *match;
   struct stat dotinfo;
   static char **match_list = NULL;
   static int match_list_size = 0;
   static int match_index = 0;
   if (state == 0)
     {
       /* Create the list of matches. */
       if (match_list == 0)
     {
       match_list_size = 5;
       match_list = strvec_create (match_list_size);
     }
       /* Clear out the old match list. */
       for (i = 0; i < match_list_size; i++)
     match_list[i] = 0;
       /* We haven't found any files yet. */
       match_index = 0;
       if (absolute_program (name))
     {
       match_list[0] = find_absolute_program (name, flags);
       match_list[1] = (char *)NULL;
       path_list = (char *)NULL;
     }
       else
     {
       name_len = strlen (name);
       file_to_lose_on = (char *)NULL;
       dot_found_in_search = 0;
       if (stat (".", &dotinfo) < 0)
         dotinfo.st_dev = dotinfo.st_ino = 0;    /* so same_file won't match */
       path_list = get_string_value ("PATH");
           path_index = 0;
     }
       while (path_list && path_list[path_index])
     {
       path_element = get_next_path_element (path_list, &path_index);
       if (path_element == 0)
         break;
       match = find_in_path_element (name, path_element, flags, name_len, &dotinfo, (int *)0);
       free (path_element);
       if (match == 0)
         continue;
       if (match_index + 1 == match_list_size)
         {
           match_list_size += 10;
           match_list = strvec_resize (match_list, (match_list_size + 1));
         }
       match_list[match_index++] = match;
       match_list[match_index] = (char *)NULL;
       FREE (file_to_lose_on);
       file_to_lose_on = (char *)NULL;
     }
       /* We haven't returned any strings yet. */
       match_index = 0;
     }
   match = match_list[match_index];
   if (match)
     match_index++;
   return (match);
 }
References absolute_program(), dot_found_in_search, file_to_lose_on, find_absolute_program(), find_in_path_element(), flags, FREE, free, get_next_path_element(), get_string_value(), i, match(), NULL, stat::st_dev, stat::st_ino, state, strlen(), strvec_create(), and strvec_resize().
Variable Documentation
check_hashed_filenames
int check_hashed_filenames = CHECKHASH_DEFAULT
Definition at line 72 of file findcmd.c.
Referenced by search_for_command().
dot_found_in_search
int dot_found_in_search = 0
Definition at line 78 of file findcmd.c.
Referenced by find_in_path_element(), find_user_command_in_path(), search_for_command(), and user_command_matches().
errno
int errno extern
Referenced by executable_file().
execignore
struct ignorevar execignore static
Initial value:
=
{
  "EXECIGNORE",
  NULL,
  0,
  NULL,
  NULL
}
Definition at line 78 of file findcmd.c.
Referenced by exec_name_should_ignore(), and setup_exec_ignore().
file_to_lose_on
char* file_to_lose_on static
Definition at line 68 of file findcmd.c.
Referenced by find_in_path_element(), find_user_command_in_path(), and user_command_matches().