Fennix Userspace: Userspace/mlibc/tests/ansi/fenv.c File Reference
fenv.c File Reference
#include <assert.h>
#include <stdbool.h>
#include <fenv.h>
#include <math.h>
Macros
#define NO_OPTIMIZE(x) asm volatile("" :: "r,m" (x) : "memory")
Functions
static void div_by_zero ()
static bool float_cmp (float a, float b)
static void test_rounding (float expectation1, float expectation2)
void test0 ()
void test1 ()
void test2 ()
void test3 ()
int main ()
Macro Definition Documentation
NO_OPTIMIZE
#define NO_OPTIMIZE (x) asm volatile("" :: "r,m" (x) : "memory")
Definition at line 6 of file fenv.c.
Function Documentation
div_by_zero()
static void div_by_zero () static
Definition at line 8 of file fenv.c.
{
     volatile float zero = 0.0f;
     NO_OPTIMIZE(69.0f / zero);
 }
References NO_OPTIMIZE.
Referenced by test0(), and test3().
float_cmp()
static bool float_cmp (float a, float b) static
Definition at line 13 of file fenv.c.
{
     return fabs(a - b) < .000000000001;
 }
References b, and fabs().
Referenced by test_rounding().
main()
int main (void)
Definition at line 85 of file fenv.c.
            {
     test0();
     test1();
     test2();
     test3();
 }
References test0(), test1(), test2(), and test3().
test0()
void test0 ()
Definition at line 28 of file fenv.c.
              {
     // test whether the divide-by-zero exception is raised
     feclearexcept(FE_ALL_EXCEPT);
     assert(fetestexcept(FE_ALL_EXCEPT) == 0);
     div_by_zero();
     int raised = fetestexcept(FE_DIVBYZERO);
     assert((raised & FE_DIVBYZERO));
 }
References assert, div_by_zero(), feclearexcept(), and fetestexcept().
Referenced by main().
test1()
void test1 ()
Definition at line 38 of file fenv.c.
              {
     // test various rounding modes
     feclearexcept(FE_DIVBYZERO);
     assert(fetestexcept(FE_ALL_EXCEPT) == 0);
     fesetround(FE_UPWARD);
     assert(fegetround() == FE_UPWARD);
     test_rounding(8388610.0f, 2.0f);
     fesetround(FE_DOWNWARD);
     assert(fegetround() == FE_DOWNWARD);
     test_rounding(8388609.0f, 1.0f);
     fesetround(FE_TONEAREST);
     assert(fegetround() == FE_TONEAREST);
     test_rounding(8388610.0f, 2.0f);
     fesetround(FE_TOWARDZERO);
     assert(fegetround() == FE_TOWARDZERO);
     test_rounding(8388609.0f, 1.0f);
 }
References assert, feclearexcept(), fegetround(), fesetround(), fetestexcept(), and test_rounding().
Referenced by main().
test2()
void test2 ()
Definition at line 60 of file fenv.c.
              {
     // test feraiseexcept
     feclearexcept(FE_ALL_EXCEPT);
     assert(fetestexcept(FE_ALL_EXCEPT) == 0);
     assert(feraiseexcept(FE_DIVBYZERO | FE_OVERFLOW) == 0);
     assert(fetestexcept(FE_ALL_EXCEPT) == (FE_DIVBYZERO | FE_OVERFLOW));
 }
References assert, feclearexcept(), feraiseexcept(), and fetestexcept().
Referenced by main().
test3()
void test3 ()
Definition at line 68 of file fenv.c.
              {
     // test fe{get,set}env
     feclearexcept(FE_ALL_EXCEPT);
     assert(fetestexcept(FE_ALL_EXCEPT) == 0);
     assert(feraiseexcept(FE_OVERFLOW) == 0);
     fenv_t state;
     assert(fegetenv(&state) == 0);
     assert(fetestexcept(FE_ALL_EXCEPT) == FE_OVERFLOW);
     div_by_zero();
     assert(fetestexcept(FE_ALL_EXCEPT) == (FE_DIVBYZERO | FE_OVERFLOW));
     assert(fesetenv(&state) == 0);
     assert(fetestexcept(FE_ALL_EXCEPT) == FE_OVERFLOW);
 }
References assert, div_by_zero(), feclearexcept(), fegetenv(), feraiseexcept(), fesetenv(), fetestexcept(), and state.
Referenced by main().
test_rounding()
static void test_rounding (float expectation1, float expectation2) static
Definition at line 17 of file fenv.c.
{
     float x;
     volatile float f = 1.968750f;
     volatile float m = 0x1.0p23f;
     NO_OPTIMIZE(x = f + m);
     assert(float_cmp(expectation1, x));
     NO_OPTIMIZE(x = x - m);
     assert(x == expectation2);
 }
References assert, float_cmp(), NO_OPTIMIZE, and x.
Referenced by test1().