Fennix: Userspace/musl/src/misc/pty.c File Reference
pty.c File Reference
#include <stdlib.h>
#include <sys/ioctl.h>
#include <stdio.h>
#include <fcntl.h>
#include <errno.h>
#include "syscall.h"
Functions
int posix_openpt (int flags)
int grantpt (int fd)
int unlockpt (int fd)
int __ptsname_r (int fd, char *buf, size_t len)
weak_alias (__ptsname_r, ptsname_r)
Function Documentation
__ptsname_r()
int __ptsname_r (int fd, char * buf, size_t len)
Definition at line 26 of file pty.c.
 {
     int pty, err;
     if (!buf) len = 0;
     if ((err = __syscall(SYS_ioctl, fd, TIOCGPTN, &pty))) return -err;
     if (snprintf(buf, len, "/dev/pts/%d", pty) >= len) return ERANGE;
     return 0;
 }
References __syscall, buf, ERANGE, err(), fd, len, snprintf(), and TIOCGPTN.
Referenced by ptsname().
grantpt()
int grantpt (int fd)
Definition at line 15 of file pty.c.
 {
     return 0;
 }
Referenced by xgetpty().
posix_openpt()
int posix_openpt (int flags)
Definition at line 8 of file pty.c.
 {
     int r = open("/dev/ptmx", flags);
     if (r < 0 && errno == ENOSPC) errno = EAGAIN;
     return r;
 }
References EAGAIN, ENOSPC, errno, flags, and open().
unlockpt()
int unlockpt (int fd)
Definition at line 20 of file pty.c.
 {
     int unlock = 0;
     return ioctl(fd, TIOCSPTLCK, &unlock);
 }
References fd, ioctl(), TIOCSPTLCK, and unlock().
Referenced by xgetpty().
weak_alias()
weak_alias (__ptsname_r , ptsname_r)