Fennix: Userspace/apps/base/busybox/networking/tls_pstm.h File Reference
tls_pstm.h File Reference
Data Structures
struct pstm_int
Macros
#define CHAR_BIT 8
#define PSTM_16BIT
#define DIGIT_BIT 16
#define PSTM_MASK (pstm_digit)(-1)
#define PSTM_DIGIT_MAX PSTM_MASK
#define PSTM_LT -1 /* less than */
#define PSTM_EQ 0 /* equal to */
#define PSTM_GT 1 /* greater than */
#define PSTM_ZPOS 0 /* positive integer */
#define PSTM_NEG 1 /* negative */
#define PSTM_OKAY PS_SUCCESS
#define PSTM_MEM PS_MEM_FAIL
#define PSTM_DEFAULT_INIT 64 /* default (64) digits of allocation */
#define PSTM_MAX_SIZE 4096
#define pstm_iszero(a) (((a)->used == 0) ? PS_TRUE : PS_FALSE)
#define pstm_iseven(a) (((a)->used > 0 && (((a)->dp[0] & 1) == 0)) ? PS_TRUE : PS_FALSE)
#define pstm_isodd(a) (((a)->used > 0 && (((a)->dp[0] & 1) == 1)) ? PS_TRUE : PS_FALSE)
#define pstm_abs(a, b) { pstm_copy(a, b); (b)->sign = 0; }
#define pstm_init(pool, a) pstm_init(a)
#define pstm_init_size(pool, a, size) pstm_init_size(a, size)
#define pstm_init_copy(pool, a, b, toSqr) pstm_init_copy(a, b, toSqr)
#define pstm_init_for_read_unsigned_bin(pool, a, len) pstm_init_for_read_unsigned_bin(a, len)
#define pstm_div(pool, a, b, c, d) pstm_div(a, b, c, d)
#define pstm_div_2d(pool, a, b, c, d) pstm_div_2d(a, b, c, d)
#define pstm_sub_d(pool, a, b, c) pstm_sub_d(a, b, c)
#define pstm_mod(pool, a, b, c) pstm_mod(a, b, c)
#define pstm_mulmod(pool, a, b, c, d) pstm_mulmod(a, b, c, d)
#define pstm_exptmod(pool, G, X, P, Y) pstm_exptmod(G, X, P, Y)
#define pstm_to_unsigned_bin(pool, a, b) pstm_to_unsigned_bin(a, b)
#define pstm_to_unsigned_bin_nr(pool, a, b) pstm_to_unsigned_bin_nr(a, b)
#define pstm_montgomery_reduce(pool, a, m, mp, paD, paDlen) pstm_montgomery_reduce(a, m, mp, paD, paDlen)
#define pstm_mul_comba(pool, A, B, C, paD, paDlen) pstm_mul_comba(A, B, C, paD, paDlen)
#define pstm_sqr_comba(pool, A, B, paD, paDlen) pstm_sqr_comba(A, B, paD, paDlen)
#define pstm_invmod(pool, a, b, c) pstm_invmod(a, b, c)
Typedefs
typedef unsigned short pstm_digit
typedef unsigned long pstm_word
Functions
int32 pstm_init_size (psPool_t *pool, pstm_int *a, uint32 size) FAST_FUNC
int32 pstm_init_for_read_unsigned_bin (psPool_t *pool, pstm_int *a, uint32 len) FAST_FUNC
int32 pstm_read_unsigned_bin (pstm_int *a, unsigned char *b, int32 c) FAST_FUNC
int32 pstm_unsigned_bin_size (pstm_int *a) FAST_FUNC
int32 pstm_copy (pstm_int *a, pstm_int *b)
void pstm_clear (pstm_int *a) FAST_FUNC
void pstm_clear_multi (pstm_int *mp0, pstm_int *mp1, pstm_int *mp2, pstm_int *mp3, pstm_int *mp4, pstm_int *mp5, pstm_int *mp6, pstm_int *mp7) FAST_FUNC
int32 pstm_grow (pstm_int *a, int size) FAST_FUNC
void pstm_clamp (pstm_int *a) FAST_FUNC
int32 pstm_cmp (pstm_int *a, pstm_int *b) FAST_FUNC
int32 pstm_cmp_mag (pstm_int *a, pstm_int *b) FAST_FUNC
int32 pstm_div_2 (pstm_int *a, pstm_int *b) FAST_FUNC
int32 s_pstm_sub (pstm_int *a, pstm_int *b, pstm_int *c) FAST_FUNC
int32 pstm_sub (pstm_int *a, pstm_int *b, pstm_int *c) FAST_FUNC
int32 pstm_sub_d (psPool_t *pool, pstm_int *a, pstm_digit b, pstm_int *c) FAST_FUNC
int32 pstm_mul_2 (pstm_int *a, pstm_int *b) FAST_FUNC
int32 pstm_mulmod (psPool_t *pool, pstm_int *a, pstm_int *b, pstm_int *c, pstm_int *d) FAST_FUNC
int32 pstm_exptmod (psPool_t *pool, pstm_int *G, pstm_int *X, pstm_int *P, pstm_int *Y) FAST_FUNC
int32 pstm_add (pstm_int *a, pstm_int *b, pstm_int *c) FAST_FUNC
int32 pstm_to_unsigned_bin (psPool_t *pool, pstm_int *a, unsigned char *b) FAST_FUNC
int32 pstm_to_unsigned_bin_nr (psPool_t *pool, pstm_int *a, unsigned char *b) FAST_FUNC
int32 pstm_montgomery_reduce (psPool_t *pool, pstm_int *a, pstm_int *m, pstm_digit mp, pstm_digit *paD, uint32 paDlen) FAST_FUNC
int32 pstm_mul_comba (psPool_t *pool, pstm_int *A, pstm_int *B, pstm_int *C, pstm_digit *paD, uint32 paDlen) FAST_FUNC
int32 pstm_sqr_comba (psPool_t *pool, pstm_int *A, pstm_int *B, pstm_digit *paD, uint32 paDlen) FAST_FUNC
int32 pstm_invmod (psPool_t *pool, pstm_int *a, pstm_int *b, pstm_int *c) FAST_FUNC
Data Structure Documentation
pstm_int
struct pstm_int
Definition at line 124 of file tls_pstm.h.
Data Fields
int alloc
pstm_digit * dp
int sign
int used
Macro Definition Documentation
CHAR_BIT
#define CHAR_BIT 8
Definition at line 50 of file tls_pstm.h.
DIGIT_BIT
#define DIGIT_BIT 16
Definition at line 81 of file tls_pstm.h.
PSTM_16BIT
#define PSTM_16BIT
Definition at line 59 of file tls_pstm.h.
pstm_abs
#define pstm_abs (a, b) { pstm_copy(a, b); (b)->sign = 0; }
Definition at line 137 of file tls_pstm.h.
PSTM_DEFAULT_INIT
#define PSTM_DEFAULT_INIT 64 /* default (64) digits of allocation */
Definition at line 121 of file tls_pstm.h.
PSTM_DIGIT_MAX
#define PSTM_DIGIT_MAX PSTM_MASK
Definition at line 101 of file tls_pstm.h.
pstm_div
#define pstm_div (pool, a, b, c, d) pstm_div(a, b, c, d)
Definition at line 194 of file tls_pstm.h.
pstm_div_2d
#define pstm_div_2d (pool, a, b, c, d) pstm_div_2d(a, b, c, d)
Definition at line 200 of file tls_pstm.h.
PSTM_EQ
#define PSTM_EQ 0 /* equal to */
Definition at line 108 of file tls_pstm.h.
pstm_exptmod
#define pstm_exptmod (pool, G, X, P, Y) pstm_exptmod(G, X, P, Y)
Definition at line 230 of file tls_pstm.h.
PSTM_GT
#define PSTM_GT 1 /* greater than */
Definition at line 109 of file tls_pstm.h.
pstm_init
#define pstm_init (pool, a) pstm_init(a)
Definition at line 144 of file tls_pstm.h.
pstm_init_copy
#define pstm_init_copy (pool, a, b, toSqr) pstm_init_copy(a, b, toSqr)
Definition at line 154 of file tls_pstm.h.
pstm_init_for_read_unsigned_bin
#define pstm_init_for_read_unsigned_bin (pool, a, len) pstm_init_for_read_unsigned_bin(a, len)
Definition at line 162 of file tls_pstm.h.
pstm_init_size
#define pstm_init_size (pool, a, size) pstm_init_size(a, size)
Definition at line 149 of file tls_pstm.h.
pstm_invmod
#define pstm_invmod (pool, a, b, c) pstm_invmod(a, b, c)
Definition at line 277 of file tls_pstm.h.
pstm_iseven
#define pstm_iseven (a) (((a)->used > 0 && (((a)->dp[0] & 1) == 0)) ? PS_TRUE : PS_FALSE)
Definition at line 135 of file tls_pstm.h.
pstm_isodd
#define pstm_isodd (a) (((a)->used > 0 && (((a)->dp[0] & 1) == 1)) ? PS_TRUE : PS_FALSE)
Definition at line 136 of file tls_pstm.h.
pstm_iszero
#define pstm_iszero (a) (((a)->used == 0) ? PS_TRUE : PS_FALSE)
Definition at line 134 of file tls_pstm.h.
PSTM_LT
#define PSTM_LT -1 /* less than */
Definition at line 107 of file tls_pstm.h.
PSTM_MASK
#define PSTM_MASK (pstm_digit)(-1)
Definition at line 100 of file tls_pstm.h.
PSTM_MAX_SIZE
#define PSTM_MAX_SIZE 4096
Definition at line 122 of file tls_pstm.h.
PSTM_MEM
#define PSTM_MEM PS_MEM_FAIL
Definition at line 115 of file tls_pstm.h.
pstm_mod
#define pstm_mod (pool, a, b, c) pstm_mod(a, b, c)
Definition at line 219 of file tls_pstm.h.
pstm_montgomery_reduce
#define pstm_montgomery_reduce (pool, a, m, mp, paD, paDlen) pstm_montgomery_reduce(a, m, mp, paD, paDlen)
Definition at line 254 of file tls_pstm.h.
pstm_mul_comba
#define pstm_mul_comba (pool, A, B, C, paD, paDlen) pstm_mul_comba(A, B, C, paD, paDlen)
Definition at line 259 of file tls_pstm.h.
pstm_mulmod
#define pstm_mulmod (pool, a, b, c, d) pstm_mulmod(a, b, c, d)
Definition at line 224 of file tls_pstm.h.
PSTM_NEG
#define PSTM_NEG 1 /* negative */
Definition at line 112 of file tls_pstm.h.
PSTM_OKAY
#define PSTM_OKAY PS_SUCCESS
Definition at line 114 of file tls_pstm.h.
pstm_sqr_comba
#define pstm_sqr_comba (pool, A, B, paD, paDlen) pstm_sqr_comba(A, B, paD, paDlen)
Definition at line 265 of file tls_pstm.h.
pstm_sub_d
#define pstm_sub_d (pool, a, b, c) pstm_sub_d(a, b, c)
Definition at line 212 of file tls_pstm.h.
pstm_to_unsigned_bin
#define pstm_to_unsigned_bin (pool, a, b) pstm_to_unsigned_bin(a, b)
Definition at line 240 of file tls_pstm.h.
pstm_to_unsigned_bin_nr
#define pstm_to_unsigned_bin_nr (pool, a, b) pstm_to_unsigned_bin_nr(a, b)
Definition at line 246 of file tls_pstm.h.
PSTM_ZPOS
#define PSTM_ZPOS 0 /* positive integer */
Definition at line 111 of file tls_pstm.h.
Typedef Documentation
pstm_digit
typedef unsigned short pstm_digit
Definition at line 79 of file tls_pstm.h.
pstm_word
typedef unsigned long pstm_word
Definition at line 80 of file tls_pstm.h.
Function Documentation
pstm_add()
int32 pstm_add (pstm_int * a, pstm_int * b, pstm_int * c)
Definition at line 1844 of file tls_pstm.c.
 {
     int32   res;
     int sa, sb; //bbox: was int16
     /* get sign of both inputs */
     sa = a->sign;
     sb = b->sign;
     /* handle two cases, not four */
     if (sa == sb) {
         /* both positive or both negative, add their mags, copy the sign */
         c->sign = sa;
         if ((res = s_pstm_add (a, b, c)) != PSTM_OKAY) {
             return res;
         }
     } else {
 /*
         one positive, the other negative
         subtract the one with the greater magnitude from the one of the lesser
         magnitude. The result gets the sign of the one with the greater mag.
  */
         if (pstm_cmp_mag (a, b) == PSTM_LT) {
             c->sign = sb;
             if ((res = s_pstm_sub (b, a, c)) != PSTM_OKAY) {
                 return res;
             }
         } else {
             c->sign = sa;
             if ((res = s_pstm_sub (a, b, c)) != PSTM_OKAY) {
                 return res;
             }
         }
     }
     return PS_SUCCESS;
 }
References c, PS_SUCCESS, pstm_cmp_mag(), PSTM_LT, PSTM_OKAY, s_pstm_add(), s_pstm_sub(), and pstm_int::sign.
Referenced by psRsaCrypt(), pstm_div(), and pstm_mod().
pstm_clamp()
void pstm_clamp (pstm_int * a)
Definition at line 223 of file tls_pstm.c.
 {
 /*  decrease used while the most significant digit is zero. */
     while (a->used > 0 && a->dp[a->used - 1] == 0) {
         --(a->used);
     }
 /*  reset the sign flag if used == 0 */
     if (a->used == 0) {
         a->sign = PSTM_ZPOS;
     }
 }
References pstm_int::dp, PSTM_ZPOS, pstm_int::sign, and pstm_int::used.
Referenced by pstm_div(), pstm_div_2d(), pstm_mod_2d(), pstm_montgomery_reduce(), pstm_mul_2d(), pstm_mul_comba_gen(), pstm_mul_d(), pstm_rshd(), pstm_sqr_comba_gen(), s_pstm_add(), and s_pstm_sub().
pstm_clear()
void pstm_clear (pstm_int * a)
Definition at line 239 of file tls_pstm.c.
 {
     int32       i;
 /*
     only do anything if a hasn't been freed previously
  */
     if (a != NULL && a->dp != NULL) {
 /*
         first zero the digits
  */
         for (i = 0; i < a->used; i++) {
             a->dp[i] = 0;
         }
         psFree (a->dp, a->pool);
 /*
         reset members to make debugging easier
  */
         a->dp       = NULL;
         a->alloc    = a->used = 0;
         a->sign     = PSTM_ZPOS;
     }
 }
References pstm_int::alloc, pstm_int::dp, i, NULL, psFree, PSTM_ZPOS, pstm_int::sign, and pstm_int::used.
Referenced by psRsaCrypt(), psRsaKey_clear(), pstm_div(), pstm_div_2d(), pstm_exptmod(), pstm_mod(), pstm_mulmod(), and pstm_to_unsigned_bin().
pstm_clear_multi()
void pstm_clear_multi (pstm_int * mp0, pstm_int * mp1, pstm_int * mp2, pstm_int * mp3, pstm_int * mp4, pstm_int * mp5, pstm_int * mp6, pstm_int * mp7)
pstm_cmp()
int32 pstm_cmp (pstm_int * a, pstm_int * b)
Definition at line 357 of file tls_pstm.c.
 {
 /*
     compare based on sign
  */
     if (a->sign != b->sign) {
         if (a->sign == PSTM_NEG) {
             return PSTM_LT;
         } else {
             return PSTM_GT;
         }
     }
 /*
     compare digits
  */
     if (a->sign == PSTM_NEG) {
         /* if negative compare opposite direction */
         return pstm_cmp_mag(b, a);
     } else {
         return pstm_cmp_mag(a, b);
     }
 }
References pstm_cmp_mag(), PSTM_GT, PSTM_LT, PSTM_NEG, and pstm_int::sign.
Referenced by psRsaCrypt(), and pstm_div().
pstm_cmp_mag()
int32 pstm_cmp_mag (pstm_int * a, pstm_int * b)
Definition at line 317 of file tls_pstm.c.
 {
     int     n; //bbox: was int16
     pstm_digit  *tmpa, *tmpb;
 /*
     compare based on # of non-zero digits
  */
     if (a->used > b->used) {
         return PSTM_GT;
     }
     if (a->used < b->used) {
         return PSTM_LT;
     }
     /* alias for a */
     tmpa = a->dp + (a->used - 1);
     /* alias for b */
     tmpb = b->dp + (a->used - 1);
 /*
     compare based on digits
  */
     for (n = 0; n < a->used; ++n, --tmpa, --tmpb) {
         if (*tmpa > *tmpb) {
             return PSTM_GT;
         }
         if (*tmpa < *tmpb) {
             return PSTM_LT;
         }
     }
     return PSTM_EQ;
 }
References pstm_int::dp, n, PSTM_EQ, PSTM_GT, PSTM_LT, and pstm_int::used.
Referenced by pstm_add(), pstm_cmp(), pstm_div(), pstm_exptmod(), pstm_montgomery_calc_normalization(), pstm_montgomery_reduce(), and pstm_sub().
pstm_copy()
int32 pstm_copy (pstm_int * a, pstm_int * b)
Definition at line 165 of file tls_pstm.c.
 {
     int32   res, n;
 /*
     If dst == src do nothing
  */
     if (a == b) {
         return PSTM_OKAY;
     }
 /*
     Grow dest
  */
     if (b->alloc < a->used) {
         if ((res = pstm_grow (b, a->used)) != PSTM_OKAY) {
             return res;
         }
     }
 /*
     Zero b and copy the parameters over
  */
     {
         register pstm_digit *tmpa, *tmpb;
         /* pointer aliases */
         /* source */
         tmpa = a->dp;
         /* destination */
         tmpb = b->dp;
         /* copy all the digits */
         for (n = 0; n < a->used; n++) {
             *tmpb++ = *tmpa++;
         }
         /* clear high digits */
         for (; n < b->used; n++) {
             *tmpb++ = 0;
         }
     }
 /*
     copy used count and sign
  */
     b->used = a->used;
     b->sign = a->sign;
     return PSTM_OKAY;
 }
References pstm_int::alloc, pstm_int::dp, n, pstm_grow, PSTM_OKAY, pstm_int::sign, and pstm_int::used.
pstm_div_2()
int32 pstm_div_2 (pstm_int * a, pstm_int * b)
pstm_exptmod()
int32 pstm_exptmod (psPool_t * pool, pstm_int * G, pstm_int * X, pstm_int * P, pstm_int * Y)
Definition at line 1603 of file tls_pstm.c.
 {
     pstm_int    M[32], res; /* Keep this winsize based: (1 << max_winsize) */
     pstm_digit  buf, mp;
     pstm_digit  *paD;
     int32       err, bitbuf;
     int     bitcpy, bitcnt, mode, digidx, x, y, winsize; //bbox: was int16
     uint32      paDlen;
     /* set window size from what user set as optimization */
     x = pstm_count_bits(X);
     if (x < 50) {
         winsize = 2;
     } else {
         winsize = PS_EXPTMOD_WINSIZE;
     }
     /* now setup montgomery  */
     if ((err = pstm_montgomery_setup (P, &mp)) != PSTM_OKAY) {
         return err;
     }
     /* setup result */
     if ((err = pstm_init_size(pool, &res, (P->used * 2) + 1)) != PSTM_OKAY) {
         return err;
     }
 /*
     create M table
     The M table contains powers of the input base, e.g. M[x] = G^x mod P
     The first half of the table is not computed though except for M[0] and M[1]
  */
     /* now we need R mod m */
     if ((err = pstm_montgomery_calc_normalization (&res, P)) != PSTM_OKAY) {
         goto LBL_RES;
     }
 /*
     init M array
     init first cell
  */
     if ((err = pstm_init_size(pool, &M[1], res.used)) != PSTM_OKAY) {
         goto LBL_RES;
     }
     /* now set M[1] to G * R mod m */
     if (pstm_cmp_mag(P, G) != PSTM_GT) {
         /* G > P so we reduce it first */
         if ((err = pstm_mod(pool, G, P, &M[1])) != PSTM_OKAY) {
             goto LBL_M;
         }
     } else {
         if ((err = pstm_copy(G, &M[1])) != PSTM_OKAY) {
             goto LBL_M;
         }
     }
     if ((err = pstm_mulmod (pool, &M[1], &res, P, &M[1])) != PSTM_OKAY) {
         goto LBL_M;
     }
 /*
     Pre-allocated digit.  Used for mul, sqr, AND reduce
 */
     paDlen = ((M[1].used + 3) * 2) * sizeof(pstm_digit);
     paD = xzalloc(paDlen);//bbox
 /*
     compute the value at M[1<<(winsize-1)] by squaring M[1] (winsize-1) times
  */
     if (pstm_init_copy(pool, &M[1 << (winsize - 1)], &M[1], 1) != PSTM_OKAY) {
         err = PS_MEM_FAIL;
         goto LBL_PAD;
     }
     for (x = 0; x < (winsize - 1); x++) {
         if ((err = pstm_sqr_comba (pool, &M[1 << (winsize - 1)],
                 &M[1 << (winsize - 1)], paD, paDlen)) != PSTM_OKAY) {
             goto LBL_PAD;
         }
         if ((err = pstm_montgomery_reduce(pool, &M[1 << (winsize - 1)], P, mp,
                 paD, paDlen)) != PSTM_OKAY) {
             goto LBL_PAD;
         }
     }
 /*
     now init the second half of the array
 */
     for (x = (1<<(winsize-1)) + 1; x < (1 << winsize); x++) {
         if ((err = pstm_init_size(pool, &M[x], M[1<<(winsize-1)].alloc + 1))
                 != PSTM_OKAY) {
             for (y = 1<<(winsize-1); y < x; y++) {
                 pstm_clear(&M[y]);
             }
             goto LBL_PAD;
         }
     }
     /* create upper table */
     for (x = (1 << (winsize - 1)) + 1; x < (1 << winsize); x++) {
         if ((err = pstm_mul_comba(pool, &M[x - 1], &M[1], &M[x], paD, paDlen))
                 != PSTM_OKAY) {
             goto LBL_MARRAY;
         }
         if ((err = pstm_montgomery_reduce(pool, &M[x], P, mp, paD, paDlen)) !=
                 PSTM_OKAY) {
             goto LBL_MARRAY;
         }
     }
     /* set initial mode and bit cnt */
     mode   = 0;
     bitcnt = 1;
     buf    = 0;
     digidx = X->used - 1;
     bitcpy = 0;
     bitbuf = 0;
     for (;;) {
         /* grab next digit as required */
         if (--bitcnt == 0) {
             /* if digidx == -1 we are out of digits so break */
             if (digidx == -1) {
                 break;
             }
             /* read next digit and reset bitcnt */
             buf    = X->dp[digidx--];
             bitcnt = (int32)DIGIT_BIT;
         }
         /* grab the next msb from the exponent */
         y     = (pstm_digit)(buf >> (DIGIT_BIT - 1)) & 1;
         buf <<= (pstm_digit)1;
 /*
          If the bit is zero and mode == 0 then we ignore it.
          These represent the leading zero bits before the first 1 bit
          in the exponent.  Technically this opt is not required but it
          does lower the # of trivial squaring/reductions used
 */
         if (mode == 0 && y == 0) {
             continue;
         }
         /* if the bit is zero and mode == 1 then we square */
         if (mode == 1 && y == 0) {
             if ((err = pstm_sqr_comba(pool, &res, &res, paD, paDlen)) !=
                     PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD, paDlen))
                     != PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             continue;
         }
         /* else we add it to the window */
         bitbuf |= (y << (winsize - ++bitcpy));
         mode    = 2;
         if (bitcpy == winsize) {
             /* ok window is filled so square as required and mul square first */
             for (x = 0; x < winsize; x++) {
                 if ((err = pstm_sqr_comba(pool, &res, &res, paD, paDlen)) !=
                         PSTM_OKAY) {
                     goto LBL_MARRAY;
                 }
                 if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD,
                         paDlen)) != PSTM_OKAY) {
                     goto LBL_MARRAY;
                 }
             }
             /* then multiply */
             if ((err = pstm_mul_comba(pool, &res, &M[bitbuf], &res, paD,
                     paDlen)) != PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD, paDlen))
                     != PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             /* empty window and reset */
             bitcpy = 0;
             bitbuf = 0;
             mode   = 1;
         }
     }
     /* if bits remain then square/multiply */
     if (mode == 2 && bitcpy > 0) {
         /* square then multiply if the bit is set */
         for (x = 0; x < bitcpy; x++) {
             if ((err = pstm_sqr_comba(pool, &res, &res, paD, paDlen)) !=
                     PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD, paDlen))
                     != PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             /* get next bit of the window */
             bitbuf <<= 1;
             if ((bitbuf & (1 << winsize)) != 0) {
             /* then multiply */
                 if ((err = pstm_mul_comba(pool, &res, &M[1], &res, paD, paDlen))
                         != PSTM_OKAY) {
                     goto LBL_MARRAY;
                 }
                 if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD,
                         paDlen)) != PSTM_OKAY) {
                     goto LBL_MARRAY;
                 }
             }
         }
     }
 /*
     Fix up result if Montgomery reduction is used recall that any value in a
     Montgomery system is actually multiplied by R mod n.  So we have to reduce
     one more time to cancel out the factor of R.
 */
     if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD, paDlen)) !=
             PSTM_OKAY) {
         goto LBL_MARRAY;
     }
     /* swap res with Y */
     if ((err = pstm_copy (&res, Y)) != PSTM_OKAY) {
         goto LBL_MARRAY;
     }
     err = PSTM_OKAY;
 LBL_MARRAY:
     for (x = 1<<(winsize-1); x < (1 << winsize); x++) {
         pstm_clear(&M[x]);
     }
 LBL_PAD:psFree(paD, pool);
 LBL_M: pstm_clear(&M[1]);
 LBL_RES:pstm_clear(&res);
     return err;
 }
References buf, DIGIT_BIT, err(), G(), M, P, PS_EXPTMOD_WINSIZE, PS_MEM_FAIL, psFree, pstm_clear(), pstm_cmp_mag(), pstm_copy, pstm_count_bits(), PSTM_GT, pstm_init_copy, pstm_init_size, pstm_mod(), pstm_montgomery_calc_normalization(), pstm_montgomery_reduce, pstm_montgomery_setup(), pstm_mul_comba, pstm_mulmod(), PSTM_OKAY, pstm_sqr_comba, pstm_int::used, X, x, xzalloc(), and y.
pstm_grow()
int32 pstm_grow (pstm_int * a, int size)
Definition at line 127 of file tls_pstm.c.
 {
     int         i; //bbox: was int16
     pstm_digit      *tmp;
 /*
     If the alloc size is smaller alloc more ram.
  */
     if (a->alloc < size) {
 /*
         Reallocate the array a->dp
         We store the return in a temporary variable in case the operation
         failed we don't want to overwrite the dp member of a.
 */
         tmp = xrealloc(a->dp, sizeof (pstm_digit) * size);//bbox
 /*
         reallocation succeeded so set a->dp
  */
         a->dp = tmp;
 /*
         zero excess digits
  */
         i           = a->alloc;
         a->alloc    = size;
         for (; i < a->alloc; i++) {
             a->dp[i] = 0;
         }
     }
     return PSTM_OKAY;
 }
References pstm_int::alloc, pstm_int::dp, i, PSTM_OKAY, size, and xrealloc.
pstm_init_for_read_unsigned_bin()
int32 pstm_init_for_read_unsigned_bin (psPool_t * pool, pstm_int * a, uint32 len)
Definition at line 385 of file tls_pstm.c.
 {
     int32 size;
 /*
     Need to set this based on how many words max it will take to store the bin.
     The magic + 2:
         1 to round up for the remainder of this integer math
         1 for the initial carry of '1' bits that fall between DIGIT_BIT and 8
 */
     size = (((len / sizeof(pstm_digit)) * (sizeof(pstm_digit) * CHAR_BIT))
         / DIGIT_BIT) + 2;
     return pstm_init_size(pool, a, size);
 }
References CHAR_BIT, DIGIT_BIT, len, pstm_init_size, and size.
pstm_init_size()
int32 pstm_init_size (psPool_t * pool, pstm_int * a, uint32 size)
Definition at line 61 of file tls_pstm.c.
 {
 //bbox
 //  uint16      x;
 /*
     alloc mem
  */
     a->dp = xzalloc(sizeof (pstm_digit) * size);//bbox
 //bbox  a->pool = pool;
     a->used  = 0;
     a->alloc = size;
     a->sign  = PSTM_ZPOS;
 /*
     zero the digits
  */
 //bbox
 //  for (x = 0; x < size; x++) {
 //      a->dp[x] = 0;
 //  }
     return PSTM_OKAY;
 }
References pstm_int::alloc, pstm_int::dp, PSTM_OKAY, PSTM_ZPOS, pstm_int::sign, size, pstm_int::used, and xzalloc().
pstm_invmod()
int32 pstm_invmod (psPool_t * pool, pstm_int * a, pstm_int * b, pstm_int * c)
pstm_montgomery_reduce()
int32 pstm_montgomery_reduce (psPool_t * pool, pstm_int * a, pstm_int * m, pstm_digit mp, pstm_digit * paD, uint32 paDlen)
Definition at line 367 of file tls_pstm_montgomery_reduce.c.
 {
     pstm_digit  *c, *_c, *tmpm, mu;
     int32       oldused, x, y;
     int     pa; //bbox: was int16
     pa = m->used;
     if (pa > a->alloc) {
         /* Sanity test for bad numbers.  This will confirm no buffer overruns */
         return PS_LIMIT_FAIL;
     }
     if (paD && paDlen >= (uint32)2*pa+1) {
         c = paD;
         memset(c, 0x0, paDlen);
     } else {
         c = xzalloc(2*pa+1);//bbox
     }
     /* copy the input */
     oldused = a->used;
     for (x = 0; x < oldused; x++) {
         c[x] = a->dp[x];
     }
     MONT_START;
     for (x = 0; x < pa; x++) {
         pstm_digit cy = 0;
         /* get Mu for this round */
         LOOP_START;
         _c   = c + x;
         tmpm = m->dp;
         y = 0;
 #ifdef PSTM_X86_64
         for (; y < (pa & ~7); y += 8) {
             INNERMUL8;
             _c   += 8;
             tmpm += 8;
         }
 #endif /* PSTM_X86_64 */
         for (; y < pa; y++) {
             INNERMUL;
             ++_c;
         }
         LOOP_END;
         while (cy) {
             PROPCARRY;
             ++_c;
         }
     }
     /* now copy out */
     _c   = c + pa;
     tmpm = a->dp;
     for (x = 0; x < pa+1; x++) {
         *tmpm++ = *_c++;
     }
     for (; x < oldused; x++)   {
         *tmpm++ = 0;
     }
     MONT_FINI;
     a->used = pa+1;
     pstm_clamp(a);
     /* reuse x as return code */
     x = PSTM_OKAY;
     /* if A >= m then A = A - m */
     if (pstm_cmp_mag (a, m) != PSTM_LT) {
         if (s_pstm_sub (a, m, a) != PSTM_OKAY) {
             x = PS_MEM_FAIL;
         }
     }
     if (paDlen < (uint32)2*pa+1) {
         psFree(c, pool);
     }
     return x;
 }
References pstm_int::alloc, c, pstm_int::dp, INNERMUL, LOOP_END, LOOP_START, memset, MONT_FINI, MONT_START, PROPCARRY, PS_LIMIT_FAIL, PS_MEM_FAIL, psFree, pstm_clamp(), pstm_cmp_mag(), PSTM_LT, PSTM_OKAY, s_pstm_sub(), pstm_int::used, x, xzalloc(), and y.
pstm_mul_2()
int32 pstm_mul_2 (pstm_int * a, pstm_int * b)
Definition at line 639 of file tls_pstm.c.
 {
     int32   res;
     int x, oldused; //bbox: was int16
 /*
     grow to accomodate result
  */
     if (b->alloc < a->used + 1) {
         if ((res = pstm_grow (b, a->used + 1)) != PSTM_OKAY) {
             return res;
         }
     }
     oldused = b->used;
     b->used = a->used;
     {
         register pstm_digit r, rr, *tmpa, *tmpb;
         /* alias for source */
         tmpa = a->dp;
         /* alias for dest */
         tmpb = b->dp;
         /* carry */
         r = 0;
         for (x = 0; x < a->used; x++) {
 /*
             get what will be the *next* carry bit from the
             MSB of the current digit
 */
             rr = *tmpa >> ((pstm_digit)(DIGIT_BIT - 1));
 /*
             now shift up this digit, add in the carry [from the previous]
 */
             *tmpb++ = ((*tmpa++ << ((pstm_digit)1)) | r);
 /*
             copy the carry that would be from the source
             digit into the next iteration
 */
             r = rr;
         }
         /* new leading digit? */
         if (r != 0 && b->used != (PSTM_MAX_SIZE-1)) {
             /* add a MSB which is always 1 at this point */
             *tmpb = 1;
             ++(b->used);
         }
 /*
         now zero any excess digits on the destination that we didn't write to
 */
         tmpb = b->dp + b->used;
         for (x = b->used; x < oldused; x++) {
             *tmpb++ = 0;
         }
     }
     b->sign = a->sign;
     return PSTM_OKAY;
 }
References pstm_int::alloc, DIGIT_BIT, pstm_int::dp, pstm_grow, PSTM_MAX_SIZE, PSTM_OKAY, pstm_int::sign, pstm_int::used, and x.
Referenced by pstm_montgomery_calc_normalization().
pstm_mul_comba()
int32 pstm_mul_comba (psPool_t * pool, pstm_int * A, pstm_int * B, pstm_int * C, pstm_digit * paD, uint32 paDlen)
Definition at line 757 of file tls_pstm_mul_comba.c.
 {
 #ifdef USE_1024_KEY_SPEED_OPTIMIZATIONS
     if (A->used == 16 && B->used == 16) {
         return pstm_mul_comba16(A, B, C);
     } else {
 #ifdef USE_2048_KEY_SPEED_OPTIMIZATIONS
         if (A->used == 32 && B->used == 32) {
             return pstm_mul_comba32(A, B, C);
         }
 #endif /* USE_2048_KEY_SPEED_OPTIMIZATIONS */
         return pstm_mul_comba_gen(pool, A, B, C, paD, paDlen);
     }
 #else
 #ifdef USE_2048_KEY_SPEED_OPTIMIZATIONS
     if (A->used == 32 && B->used == 32) {
         return pstm_mul_comba32(A, B, C);
     }
 #endif /* USE_2048_KEY_SPEED_OPTIMIZATIONS */
     return pstm_mul_comba_gen(pool, A, B, C, paD, paDlen);
 #endif
 }
References A, B, C, and pstm_mul_comba_gen.
pstm_mulmod()
int32 pstm_mulmod (psPool_t * pool, pstm_int * a, pstm_int * b, pstm_int * c, pstm_int * d)
Definition at line 1570 of file tls_pstm.c.
 {
     int32       res;
     int     size; //bbox: was int16
     pstm_int    tmp;
 /*
     Smart-size pstm_inits.  d is an output that is influenced by this local 't'
     so don't shrink 'd' if it wants to becuase this will lead to an pstm_grow
     in RSA operations
 */
     size = a->used + b->used + 1;
     if ((a == d) && (size < a->alloc)) {
         size = a->alloc;
     }
     if ((res = pstm_init_size(pool, &tmp, size)) != PSTM_OKAY) {
         return res;
     }
     if ((res = pstm_mul_comba(pool, a, b, &tmp, NULL, 0)) != PSTM_OKAY) {
         pstm_clear(&tmp);
         return res;
     }
     res = pstm_mod(pool, &tmp, c, d);
     pstm_clear(&tmp);
     return res;
 }
References pstm_int::alloc, c, NULL, pstm_clear(), pstm_init_size, pstm_mod(), pstm_mul_comba, PSTM_OKAY, size, and pstm_int::used.
Referenced by pstm_exptmod().
pstm_read_unsigned_bin()
int32 pstm_read_unsigned_bin (pstm_int * a, unsigned char * b, int32 c)
Definition at line 406 of file tls_pstm.c.
 {
     /* zero the int */
     pstm_zero (a);
 /*
     If we know the endianness of this architecture, and we're using
     32-bit pstm_digits, we can optimize this
 */
 #if (defined(ENDIAN_LITTLE) || defined(ENDIAN_BIG)) && !defined(PSTM_64BIT)
   /* But not for both simultaneously */
 #if defined(ENDIAN_LITTLE) && defined(ENDIAN_BIG)
 #error Both ENDIAN_LITTLE and ENDIAN_BIG defined.
 #endif
     {
         unsigned char *pd;
         if ((unsigned)c > (PSTM_MAX_SIZE * sizeof(pstm_digit))) {
             uint32 excess = c - (PSTM_MAX_SIZE * sizeof(pstm_digit));
             c -= excess;
             b += excess;
         }
         a->used = ((c + sizeof(pstm_digit) - 1)/sizeof(pstm_digit));
         if (a->alloc < a->used) {
             if (pstm_grow(a, a->used) != PSTM_OKAY) {
                 return PSTM_MEM;
             }
         }
         pd = (unsigned char *)a->dp;
         /* read the bytes in */
 #ifdef ENDIAN_BIG
         {
             /* Use Duff's device to unroll the loop. */
             int32 idx = (c - 1) & ~3;
             switch (c % 4) {
                 case 0: do { pd[idx+0] = *b++;
                     case 3: pd[idx+1] = *b++;
                     case 2: pd[idx+2] = *b++;
                     case 1: pd[idx+3] = *b++;
                     idx -= 4;
                 } while ((c -= 4) > 0);
             }
         }
 #else
         for (c -= 1; c >= 0; c -= 1) {
             pd[c] = *b++;
         }
 #endif
     }
 #else
     /* Big enough based on the len? */
     a->used = (((c / sizeof(pstm_digit)) * (sizeof(pstm_digit) * CHAR_BIT))
         / DIGIT_BIT) + 2;
     if (a->alloc < a->used) {
         if (pstm_grow(a, a->used) != PSTM_OKAY) {
             return PSTM_MEM;
         }
     }
     /* read the bytes in */
     for (; c > 0; c--) {
         if (pstm_mul_2d (a, 8, a) != PSTM_OKAY) {
             return PS_MEM_FAIL;
         }
         a->dp[0] |= *b++;
         a->used += 1;
     }
 #endif
     pstm_clamp (a);
     return PS_SUCCESS;
 }
References pstm_int::alloc, c, pstm_int::dp, idx, pd, pstm_grow, PSTM_MAX_SIZE, PSTM_MEM, PSTM_OKAY, pstm_zero(), and pstm_int::used.
Referenced by binary_to_pstm(), and psRsaCrypt().
pstm_sqr_comba()
int32 pstm_sqr_comba (psPool_t * pool, pstm_int * A, pstm_int * B, pstm_digit * paD, uint32 paDlen)
Definition at line 1088 of file tls_pstm_sqr_comba.c.
 {
 #ifdef USE_1024_KEY_SPEED_OPTIMIZATIONS
     if (A->used == 16) {
         return pstm_sqr_comba16(A, B);
     } else {
 #ifdef USE_2048_KEY_SPEED_OPTIMIZATIONS
         if (A->used == 32) {
             return pstm_sqr_comba32(A, B);
         }
 #endif /* USE_2048_KEY_SPEED_OPTIMIZATIONS */
         return pstm_sqr_comba_gen(pool, A, B, paD, paDlen);
     }
 #else
 #ifdef USE_2048_KEY_SPEED_OPTIMIZATIONS
     if (A->used == 32) {
         return pstm_sqr_comba32(A, B);
     }
 #endif /* USE_2048_KEY_SPEED_OPTIMIZATIONS */
     return pstm_sqr_comba_gen(pool, A, B, paD, paDlen);
 #endif
 }
References A, B, and pstm_sqr_comba_gen.
pstm_sub()
int32 pstm_sub (pstm_int * a, pstm_int * b, pstm_int * c)
Definition at line 802 of file tls_pstm.c.
 {
     int32   res;
     int sa, sb; //bbox: was int16
     sa = a->sign;
     sb = b->sign;
     if (sa != sb) {
 /*
         subtract a negative from a positive, OR a positive from a negative.
         For both, ADD their magnitudes, and use the sign of the first number.
  */
         c->sign = sa;
         if ((res = s_pstm_add (a, b, c)) != PSTM_OKAY) {
             return res;
         }
     } else {
 /*
         subtract a positive from a positive, OR a negative from a negative.
         First, take the difference between their magnitudes, then...
  */
         if (pstm_cmp_mag (a, b) != PSTM_LT) {
             /* Copy the sign from the first */
             c->sign = sa;
             /* The first has a larger or equal magnitude */
             if ((res = s_pstm_sub (a, b, c)) != PSTM_OKAY) {
                 return res;
             }
         } else {
             /* The result has the _opposite_ sign from the first number. */
             c->sign = (sa == PSTM_ZPOS) ? PSTM_NEG : PSTM_ZPOS;
             /* The second has a larger magnitude */
             if ((res = s_pstm_sub (b, a, c)) != PSTM_OKAY) {
                 return res;
             }
         }
     }
     return PS_SUCCESS;
 }
References c, PS_SUCCESS, pstm_cmp_mag(), PSTM_LT, PSTM_NEG, PSTM_OKAY, PSTM_ZPOS, s_pstm_add(), s_pstm_sub(), and pstm_int::sign.
Referenced by psRsaCrypt(), and pstm_div().
pstm_sub_d()
int32 pstm_sub_d (psPool_t * pool, pstm_int * a, pstm_digit b, pstm_int * c)
pstm_to_unsigned_bin()
int32 pstm_to_unsigned_bin (psPool_t * pool, pstm_int * a, unsigned char * b)
Definition at line 1932 of file tls_pstm.c.
 {
     int32     res;
     int x; //bbox: was int16
     pstm_int  t = { 0 };
     if ((res = pstm_init_copy(pool, &t, a, 0)) != PSTM_OKAY) {
         return res;
     }
     x = 0;
     while (pstm_iszero (&t) == 0) {
         b[x++] = (unsigned char) (t.dp[0] & 255);
         if ((res = pstm_div_2d (pool, &t, 8, &t, NULL)) != PSTM_OKAY) {
             pstm_clear(&t);
             return res;
         }
     }
     pstm_reverse (b, x);
     pstm_clear(&t);
     return PS_SUCCESS;
 }
References NULL, PS_SUCCESS, pstm_clear(), pstm_div_2d, pstm_init_copy, pstm_iszero, PSTM_OKAY, pstm_reverse(), t, and x.
pstm_to_unsigned_bin_nr()
int32 pstm_to_unsigned_bin_nr (psPool_t * pool, pstm_int * a, unsigned char * b)
pstm_unsigned_bin_size()
int32 pstm_unsigned_bin_size (pstm_int * a)
Definition at line 503 of file tls_pstm.c.
 {
     int32     size = pstm_count_bits (a);
     return (size / 8 + ((size & 7) != 0 ? 1 : 0));
 }
References pstm_count_bits(), and size.
Referenced by find_key_in_der_cert(), and psRsaCrypt().
s_pstm_sub()
int32 s_pstm_sub (pstm_int * a, pstm_int * b, pstm_int * c)
Definition at line 705 of file tls_pstm.c.
 {
     int     oldbused, oldused; //bbox: was int16
     int32       x;
     pstm_word   t;
     if (b->used > a->used) {
         return PS_LIMIT_FAIL;
     }
     if (c->alloc < a->used) {
         if ((x = pstm_grow (c, a->used)) != PSTM_OKAY) {
             return x;
         }
     }
     oldused  = c->used;
     oldbused = b->used;
     c->used  = a->used;
     t = 0;
     for (x = 0; x < oldbused; x++) {
         t = ((pstm_word)a->dp[x]) - (((pstm_word)b->dp[x]) + t);
         c->dp[x] = (pstm_digit)t;
         t = (t >> DIGIT_BIT)&1;
     }
     for (; x < a->used; x++) {
         t = ((pstm_word)a->dp[x]) - t;
         c->dp[x] = (pstm_digit)t;
         t = (t >> DIGIT_BIT);
     }
     for (; x < oldused; x++) {
         c->dp[x] = 0;
     }
     pstm_clamp(c);
     return PSTM_OKAY;
 }
References c, DIGIT_BIT, pstm_int::dp, PS_LIMIT_FAIL, pstm_clamp(), pstm_grow, PSTM_OKAY, t, pstm_int::used, and x.
Referenced by pstm_add(), pstm_montgomery_calc_normalization(), pstm_montgomery_reduce(), and pstm_sub().