Fennix: Userspace/musl/src/signal/sigqueue.c File Reference
sigqueue.c File Reference
#include <signal.h>
#include <string.h>
#include <unistd.h>
#include "syscall.h"
#include "pthread_impl.h"
Functions
int sigqueue (pid_t pid, int sig, const union sigval value)
Function Documentation
sigqueue()
int sigqueue (pid_t pid, int sig, const union sigval value)
Definition at line 7 of file sigqueue.c.
 {
     siginfo_t si;
     sigset_t set;
     int r;
     memset(&si, 0, sizeof si);
     si.si_signo = sig;
     si.si_code = SI_QUEUE;
     si.si_value = value;
     si.si_uid = getuid();
     __block_app_sigs(&set);
     si.si_pid = getpid();
     r = syscall(SYS_rt_sigqueueinfo, pid, sig, &si);
     __restore_sigs(&set);
     return r;
 }
References __block_app_sigs(), __restore_sigs(), getpid(), getuid, memset, pid, syscall(), and value.