Fennix: Userspace/mlibc/tests/posix/pthread_attr.c File Reference
pthread_attr.c File Reference
#include <pthread.h>
#include <assert.h>
#include <errno.h>
#include <alloca.h>
#include <string.h>
#include <sys/mman.h>
#include <signal.h>
Functions
static void test_detachstate ()
static void * stacksize_worker (void *arg)
static void test_stacksize ()
static void test_guardsize ()
static void test_scope ()
static void test_inheritsched ()
static void test_schedparam ()
static void test_schedpolicy ()
static void * stackaddr_worker (void *arg)
static void test_stackaddr ()
static void test_stack ()
static void test_affinity ()
static void test_sigmask ()
static void * getattr_worker (void *arg)
static void test_getattrnp ()
int main ()
Function Documentation
getattr_worker()
static void* getattr_worker (void * arg) static
Definition at line 178 of file pthread_attr.c.
{
     (void)arg;
     return NULL;
 }
References arg, NULL, and Driver::void().
Referenced by test_getattrnp().
main()
int main (void)
Definition at line 210 of file pthread_attr.c.
            {
     test_detachstate();
     test_stacksize();
     test_guardsize();
     test_scope();
     test_inheritsched();
     test_schedparam();
     test_schedpolicy();
     test_stackaddr();
     test_affinity();
 #if !defined(USE_HOST_LIBC) || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 32)
     test_stack();
     test_sigmask();
     test_getattrnp();
 #endif
 }
References test_affinity(), test_detachstate(), test_getattrnp(), test_guardsize(), test_inheritsched(), test_schedparam(), test_schedpolicy(), test_scope(), test_sigmask(), test_stack(), test_stackaddr(), and test_stacksize().
stackaddr_worker()
static void* stackaddr_worker (void * arg) static
Definition at line 87 of file pthread_attr.c.
{
     void *addr = *(void**)arg;
     void *sp;
 #if defined(__x86_64__)
     asm volatile ("mov %%rsp, %0" : "=r"(sp));
 #elif defined(__aarch64__)
     asm volatile ("mov %0, sp" : "=r"(sp));
 #elif defined (__riscv)
     asm volatile ("mv %0, sp" : "=r"(sp));
 #else
 #   error Unknown architecture
 #endif
     // Check if our stack pointer is in a sane range.
     assert(addr >= sp);
     return NULL;
 }
References arg, assert, and NULL.
Referenced by test_stackaddr().
stacksize_worker()
static void* stacksize_worker (void * arg) static
Definition at line 19 of file pthread_attr.c.
{
     size_t default_stacksize = (*(size_t*)arg);
     size_t alloc_size = default_stacksize + default_stacksize/2;
     void *area = alloca(alloc_size);
     // If the allocated stack was not enough this will crash.
     *(volatile int*)(area + alloc_size) = 1;
     return NULL;
 }
References alloca, arg, default_stacksize, and NULL.
Referenced by test_stacksize().
test_affinity()
static void test_affinity () static
Definition at line 141 of file pthread_attr.c.
{
     pthread_attr_t attr;
     cpu_set_t set = {0};
     assert(!pthread_attr_init(&attr));
     assert(!pthread_attr_setaffinity_np(&attr, 1, &set));
     cpu_set_t other_set = {0};
     assert(!pthread_attr_getaffinity_np(&attr, 1, &set));
     assert(!memcmp(&set, &other_set, sizeof(cpu_set_t)));
 }
References assert, mlibc::attr, memcmp(), pthread_attr_getaffinity_np(), pthread_attr_init(), and pthread_attr_setaffinity_np().
Referenced by main().
test_detachstate()
static void test_detachstate () static
Definition at line 9 of file pthread_attr.c.
{
     pthread_attr_t attr;
     assert(!pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED));
     int detachstate;
     assert(!pthread_attr_getdetachstate(&attr, &detachstate));
     assert(detachstate == PTHREAD_CREATE_DETACHED);
     assert(pthread_attr_setdetachstate(&attr, 2* (PTHREAD_CREATE_DETACHED +
                 PTHREAD_CREATE_JOINABLE)) == EINVAL);
 }
References assert, mlibc::attr, EINVAL, pthread_attr_getdetachstate(), pthread_attr_setdetachstate(), PTHREAD_CREATE_DETACHED, and PTHREAD_CREATE_JOINABLE.
Referenced by main().
test_getattrnp()
static void test_getattrnp () static
Definition at line 183 of file pthread_attr.c.
{
     pthread_attr_t attr;
     size_t stacksize = PTHREAD_STACK_MIN;
     assert(!pthread_attr_init(&attr));
     assert(!pthread_attr_setstacksize(&attr, stacksize));
     pthread_t thread;
     assert(!pthread_create(&thread, &attr, getattr_worker, NULL));
     assert(!pthread_getattr_np(thread, &attr));
     size_t other_stacksize;
     assert(!pthread_attr_getstacksize(&attr, &other_stacksize));
     assert(other_stacksize == stacksize);
     assert(!pthread_join(thread, NULL));
     pthread_t own_thread = pthread_self();
     void *stack;
     assert(!pthread_getattr_np(own_thread, &attr));
     assert(!pthread_attr_getstack(&attr, &stack, &other_stacksize));
     assert(stack);
     assert(other_stacksize);
     // Check that we can read from the highest byte returned.
     // pthread_getattr_np() should return the lowest byte
     // of the stack.
     assert(!*(char*)(stack + other_stacksize - 1));
 }
References assert, mlibc::attr, getattr_worker(), NULL, pthread_attr_getstack(), pthread_attr_getstacksize(), pthread_attr_init(), pthread_attr_setstacksize(), pthread_create(), pthread_getattr_np(), pthread_join(), pthread_self(), and PTHREAD_STACK_MIN.
Referenced by main().
test_guardsize()
static void test_guardsize () static
Definition at line 39 of file pthread_attr.c.
{
     pthread_attr_t attr;
     assert(!pthread_attr_init(&attr));
     assert(!pthread_attr_setguardsize(&attr, 0));
     size_t guardsize;
     assert(!pthread_attr_getguardsize(&attr, &guardsize));
     assert(!guardsize);
 }
References assert, mlibc::attr, pthread_attr_getguardsize(), pthread_attr_init(), and pthread_attr_setguardsize().
Referenced by main().
test_inheritsched()
static void test_inheritsched () static
Definition at line 58 of file pthread_attr.c.
{
     pthread_attr_t attr;
     assert(!pthread_attr_setinheritsched(&attr, PTHREAD_INHERIT_SCHED));
     int inheritsched;
     assert(!pthread_attr_getinheritsched(&attr, &inheritsched));
     assert(inheritsched == PTHREAD_INHERIT_SCHED);
     assert(pthread_attr_setinheritsched(&attr, 2* (PTHREAD_INHERIT_SCHED +
                 PTHREAD_EXPLICIT_SCHED)) == EINVAL);
 }
References assert, mlibc::attr, EINVAL, pthread_attr_getinheritsched(), pthread_attr_setinheritsched(), PTHREAD_EXPLICIT_SCHED, and PTHREAD_INHERIT_SCHED.
Referenced by main().
test_schedparam()
static void test_schedparam () static
Definition at line 68 of file pthread_attr.c.
{
     pthread_attr_t attr;
     struct sched_param init_param = {0};
     assert(!pthread_attr_setschedparam(&attr, &init_param));
     struct sched_param param = {1};
     assert(!pthread_attr_getschedparam(&attr, &param));
     assert(param.sched_priority == init_param.sched_priority);
 }
References assert, mlibc::attr, pthread_attr_getschedparam(), pthread_attr_setschedparam(), and sched_param::sched_priority.
Referenced by main().
test_schedpolicy()
static void test_schedpolicy () static
Definition at line 77 of file pthread_attr.c.
{
     pthread_attr_t attr;
     assert(!pthread_attr_setschedpolicy(&attr, SCHED_FIFO));
     int policy;
     assert(!pthread_attr_getschedpolicy(&attr, &policy));
     assert(policy == SCHED_FIFO);
     assert(pthread_attr_setinheritsched(&attr, 2* (SCHED_FIFO + SCHED_RR +
                 SCHED_OTHER)) == EINVAL);
 }
References assert, mlibc::attr, EINVAL, pthread_attr_getschedpolicy(), pthread_attr_setinheritsched(), pthread_attr_setschedpolicy(), SCHED_FIFO, SCHED_OTHER, and SCHED_RR.
Referenced by main().
test_scope()
static void test_scope () static
Definition at line 48 of file pthread_attr.c.
{
     pthread_attr_t attr;
     assert(!pthread_attr_setscope(&attr, PTHREAD_SCOPE_SYSTEM));
     int scope;
     assert(!pthread_attr_getscope(&attr, &scope));
     assert(scope == PTHREAD_SCOPE_SYSTEM);
     assert(pthread_attr_setscope(&attr, 2* (PTHREAD_SCOPE_SYSTEM +
                 PTHREAD_SCOPE_PROCESS)) == EINVAL);
 }
References assert, mlibc::attr, EINVAL, pthread_attr_getscope(), pthread_attr_setscope(), PTHREAD_SCOPE_PROCESS, and PTHREAD_SCOPE_SYSTEM.
Referenced by main().
test_sigmask()
static void test_sigmask () static
Definition at line 154 of file pthread_attr.c.
{
     pthread_attr_t attr;
     sigset_t set;
     sigemptyset(&set);
     sigaddset(&set, SIGUSR1);
 #ifndef USE_HOST_LIBC
     sigaddset(&set, SIGCANCEL);
 #endif
     assert(!pthread_attr_init(&attr));
     assert(!pthread_attr_setsigmask_np(&attr, &set));
     sigset_t other_set;
     sigemptyset(&other_set);
     assert(!pthread_attr_getsigmask_np(&attr, &other_set));
     assert(sigismember(&other_set, SIGUSR1));
 #ifndef USE_HOST_LIBC
     // Test whether internal signals get filtered properly.
     assert(!sigismember(&other_set, SIGCANCEL));
 #endif
 }
References assert, mlibc::attr, pthread_attr_getsigmask_np(), pthread_attr_init(), pthread_attr_setsigmask_np(), sigaddset(), SIGCANCEL, sigemptyset(), sigismember(), and SIGUSR1.
Referenced by main().
test_stack()
static void test_stack () static
Definition at line 127 of file pthread_attr.c.
{
     pthread_attr_t attr;
     void *stackaddr = (void*)1;
     size_t stacksize = PTHREAD_STACK_MIN;
     assert(!pthread_attr_setstack(&attr, stackaddr, stacksize));
     void *new_addr;
     size_t new_size;
     assert(!pthread_attr_getstack(&attr, &new_addr, &new_size));
     assert(new_addr == stackaddr);
     assert(new_size == stacksize);
 }
References assert, mlibc::attr, pthread_attr_getstack(), pthread_attr_setstack(), and PTHREAD_STACK_MIN.
Referenced by main().
test_stackaddr()
static void test_stackaddr () static
Definition at line 107 of file pthread_attr.c.
{
     pthread_attr_t attr;
     assert(!pthread_attr_init(&attr));
     size_t size;
     assert(!pthread_attr_getstacksize(&attr, &size));
     void *addr = mmap(NULL, size, PROT_READ | PROT_WRITE,
                 MAP_PRIVATE | MAP_ANONYMOUS, -1, 0) + size;
     assert(!pthread_attr_setstackaddr(&attr, addr));
     assert(!pthread_attr_setguardsize(&attr, 0));
     void *new_addr;
     assert(!pthread_attr_getstackaddr(&attr, &new_addr));
     assert(new_addr == addr);
     pthread_t thread;
     assert(!pthread_create(&thread, &attr, stackaddr_worker, &addr));
     assert(!pthread_join(thread, NULL));
 }
References assert, mlibc::attr, MAP_ANONYMOUS, MAP_PRIVATE, mmap(), NULL, PROT_READ, PROT_WRITE, pthread_attr_getstackaddr(), pthread_attr_getstacksize(), pthread_attr_init(), pthread_attr_setguardsize(), pthread_attr_setstackaddr(), pthread_create(), pthread_join(), size, and stackaddr_worker().
Referenced by main().
test_stacksize()
static void test_stacksize () static
Definition at line 28 of file pthread_attr.c.
{
     pthread_attr_t attr;
     assert(!pthread_attr_init(&attr));
     size_t stacksize;
     assert(!pthread_attr_getstacksize(&attr, &stacksize));
     assert(!pthread_attr_setstacksize(&attr, stacksize * 2));
     pthread_t thread;
     assert(!pthread_create(&thread, &attr, stacksize_worker, &stacksize));
     assert(!pthread_join(thread, NULL));
 }
References assert, mlibc::attr, NULL, pthread_attr_getstacksize(), pthread_attr_init(), pthread_attr_setstacksize(), pthread_create(), pthread_join(), and stacksize_worker().
Referenced by main().