Fennix: Userspace/apps/base/busybox/util-linux/rdate.c File Reference
rdate.c File Reference
#include "libbb.h"
Enumerations
enum { RFC_868_BIAS = 2208988800UL }
Functions
static void socket_timeout (int sig UNUSED_PARAM)
static time_t askremotedate (const char *host)
int rdate_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RFC_868_BIAS
Definition at line 32 of file rdate.c.
 { RFC_868_BIAS = 2208988800UL };
Function Documentation
askremotedate()
static time_t askremotedate (const char * host) static
Definition at line 39 of file rdate.c.
 {
     uint32_t nett;
     int fd;
     /* Timeout for dead or inaccessible servers */
     alarm(10);
     signal(SIGALRM, socket_timeout);
     fd = create_and_connect_stream_or_die(host, bb_lookup_std_port("time", "tcp", 37));
     if (safe_read(fd, &nett, 4) != 4)    /* read time from server */
         bb_error_msg_and_die("%s: %s", host, "short read");
     if (ENABLE_FEATURE_CLEAN_UP)
         close(fd);
     /* Convert from network byte order to local byte order.
      * RFC 868 time is seconds since 1900-01-01 00:00 GMT.
      * RFC 868 time 2,208,988,800 corresponds to 1970-01-01 00:00 GMT.
      * Subtract the RFC 868 time to get Linux epoch.
      */
     nett = ntohl(nett) - RFC_868_BIAS;
     if (sizeof(time_t) > 4) {
         /* Now we have 32-bit lsb of a wider time_t
          * Imagine that  nett =   0x00000001,
          * current time  cur = 0x123ffffffff.
          * Assuming our time is not some 40 years off,
          * remote time must be 0x12400000001.
          * Need to adjust our time by (int32_t)(nett - cur).
          */
         time_t cur = time(NULL);
         int32_t adjust = (int32_t)(nett - (uint32_t)cur);
         return cur + adjust;
     }
     /* This is not going to work, but what can we do */
     return (time_t)nett;
 }
References alarm(), bb_error_msg_and_die(), bb_lookup_std_port, close(), create_and_connect_stream_or_die(), cur, fd, ntohl(), NULL, RFC_868_BIAS, safe_read(), SIGALRM, signal, socket_timeout(), and time().
Referenced by rdate_main().
rdate_main()
int rdate_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 79 of file rdate.c.
 {
     time_t remote_time;
     unsigned flags;
     flags = getopt32(argv, "^" "sp" "\0" "-1");
     remote_time = askremotedate(argv[optind]);
     /* Manpages of various Unixes are confusing. What happens is:
      * (no opts) set and print time
      * -s: set time ("do not print the time")
      * -p: print time ("do not set, just print the remote time")
      * -sp: print time (that's what we do, not sure this is right)
      */
     if (!(flags & 2)) { /* no -p (-s may be present) */
         if (time(NULL) == remote_time)
             bb_simple_error_msg("current time matches remote time");
         else {
             struct timeval ts;
             ts.tv_sec = remote_time;
             ts.tv_usec = 0;
             xsettimeofday(&ts);
         }
     }
     if (flags != 1) /* not lone -s */
         printf("%s", ctime(&remote_time));
     return EXIT_SUCCESS;
 }
References argv, askremotedate(), bb_simple_error_msg(), ctime(), EXIT_SUCCESS, flags, getopt32(), NULL, optind, printf, time(), timeval::tv_sec, timeval::tv_usec, and xsettimeofday().
socket_timeout()
static void socket_timeout (int sig UNUSED_PARAM) static
Definition at line 34 of file rdate.c.
 {
     bb_simple_error_msg_and_die("timeout connecting to time server");
 }
References bb_simple_error_msg_and_die().
Referenced by askremotedate().