Fennix Userspace: Userspace/apps/base/busybox/libbb/strrstr.c File Reference
strrstr.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC strrstr (const char *haystack, const char *needle)
Function Documentation
strrstr()
char* FAST_FUNC strrstr (const char * haystack, const char * needle)
Definition at line 15 of file strrstr.c.
 {
     char *r = NULL;
     if (!needle[0])
         return (char*)haystack + strlen(haystack);
     while (1) {
         char *p = strstr(haystack, needle);
         if (!p)
             return r;
         r = p;
         haystack = p + 1;
     }
 }
References NULL, p, strlen(), and strstr().
Referenced by parse_module().