Fennix Userspace: Userspace/musl/src/prng/drand48.c File Reference
drand48.c File Reference
#include <stdlib.h>
#include <inttypes.h>
#include "rand48.h"
Functions
double erand48 (unsigned short s[3])
double drand48 (void)
Function Documentation
drand48()
double drand48 (void)
Definition at line 14 of file drand48.c.
 {
     return erand48(__seed48);
 }
References __seed48, and erand48().
erand48()
double erand48 (unsigned short s[3])
Definition at line 5 of file drand48.c.
 {
     union {
         uint64_t u;
         double f;
     } x = { 0x3ff0000000000000ULL | __rand48_step(s, __seed48+3)<<4 };
     return x.f - 1.0;
 }
References __rand48_step(), __seed48, f, s, and x.
Referenced by drand48().