Fennix Userspace: Userspace/libc/ElfInterpreter/fcts.c File Reference
fcts.c File Reference
#include "fcts.h"
#include "../../../Kernel/syscalls.h"
#include "../../../Kernel/ipc.h"
Functions
uintptr_t RequestPages (size_t Count)
int FreePages (uintptr_t Address, size_t Count)
int IPC (int Command, int Type, int ID, int Flags, void *Buffer, size_t Size)
uintptr_t KernelCTL (int Command, uint64_t Arg1, uint64_t Arg2, uint64_t Arg3, uint64_t Arg4)
int abs (int i)
void swap (char *x, char *y)
char * reverse (char *Buffer, int i, int j)
char * ltoa (long Value, char *Buffer, int Base)
void PutCharToKernelConsole (char c)
void Print__ (char *String)
void PrintNL__ (char *String)
void * memcpy (void *dest, const void *src, size_t n)
void * memset (void *s, int c, size_t n)
int strcmp (const char *l, const char *r)
struct Elf64_Dyn ELFGetDynamicTag (char *Path, enum DynamicTags Tag)
Elf64_Shdr * GetELFSheader (Elf64_Ehdr *Header)
Elf64_Shdr * GetELFSection (Elf64_Ehdr *Header, uint64_t Index)
char * GetELFStringTable (Elf64_Ehdr *Header)
Elf64_Sym ELFLookupSymbol (char *Path, const char *Name)
Function Documentation
abs()
int abs (int i)
Definition at line 26 of file fcts.c.
 { return i < 0 ? -i : i; }
References i.
Referenced by FixedDiv(), G_Responder(), ltoa(), main(), P_AproxDistance(), P_NewChaseDir(), P_PathTraverse(), PIT_CheckThing(), PIT_RadiusAttack(), PIT_StompThing(), PIT_VileCheck(), R_DrawPlanes(), R_DrawVisSprite(), R_ExecuteSetViewSize(), R_PointToDist(), R_ProjectSprite(), R_ScaleFromGlobalAngle(), R_StoreWallRange(), and S_AdjustSoundParams().
ELFGetDynamicTag()
struct Elf64_Dyn ELFGetDynamicTag (char * Path, enum DynamicTags Tag)
Definition at line 106 of file fcts.c.
 {
     void *KP = syscall2(_FileOpen, Path, (long)"r");
     if (KP == NULL)
         syscall1(_Exit, -0xF17E);
     Elf64_Ehdr ELFHeader;
     syscall3(_FileRead, KP, &ELFHeader, sizeof(Elf64_Ehdr));
     Elf64_Phdr ItrProgramHeader;
     for (Elf64_Half i = 0; i < ELFHeader.e_phnum; i++)
     {
         // memcpy(&ItrProgramHeader, (uint8_t *)ElfFile + ELFHeader.e_phoff + ELFHeader.e_phentsize * i, sizeof(Elf64_Phdr));
         syscall3(_FileSeek, KP, ELFHeader.e_phoff + ELFHeader.e_phentsize * i, SEEK_SET);
         syscall3(_FileRead, KP, &ItrProgramHeader, sizeof(Elf64_Phdr));
         if (ItrProgramHeader.p_type == PT_DYNAMIC)
         {
             struct Elf64_Dyn Dynamic; // = (struct Elf64_Dyn *)((uint8_t *)ElfFile + ItrProgramHeader.p_offset);
             syscall3(_FileSeek, KP, ItrProgramHeader.p_offset, SEEK_SET);
             syscall3(_FileRead, KP, &Dynamic, ItrProgramHeader.p_filesz);
             for (size_t i = 0; i < ItrProgramHeader.p_filesz / sizeof(struct Elf64_Dyn); i++)
             {
                 if (Dynamic.d_tag == Tag || Dynamic.d_tag == DT_NULL)
                 {
                     syscall1(_FileClose, KP);
                     return Dynamic;
                 }
                 syscall3(_FileSeek, KP, ItrProgramHeader.p_offset + (i + 1) * sizeof(struct Elf64_Dyn), SEEK_SET);
                 syscall3(_FileRead, KP, &Dynamic, sizeof(struct Elf64_Dyn));
             }
         }
     }
     syscall1(_FileClose, KP);
     return (struct Elf64_Dyn){0};
 }
References r.
Referenced by ELFAddLazyResolverToGOT().
ELFLookupSymbol()
Elf64_Sym ELFLookupSymbol (char * Path, const char * Name)
Definition at line 169 of file fcts.c.
 {
     void *KP = syscall2(_FileOpen, Path, (long)"r");
     if (KP == NULL)
         syscall1(_Exit, -0xF17E);
     Elf64_Ehdr ELFHeader;
     syscall3(_FileRead, KP, &ELFHeader, sizeof(Elf64_Ehdr));
     Elf64_Shdr SymbolTable;
     Elf64_Shdr StringTable;
     Elf64_Sym Symbol;
     char *String = NULL;
     for (Elf64_Half i = 0; i < ELFHeader.e_shnum; i++)
     {
         Elf64_Shdr shdr;
         syscall3(_FileSeek, KP,
                  ELFHeader.e_shoff + ELFHeader.e_shentsize * i,
                  SEEK_SET);
         syscall3(_FileRead, KP, &shdr, sizeof(Elf64_Shdr));
         switch (shdr.sh_type)
         {
         case SHT_SYMTAB:
         {
             SymbolTable = shdr;
             syscall3(_FileSeek, KP,
                      ELFHeader.e_shoff + ELFHeader.e_shentsize * shdr.sh_link,
                      SEEK_SET);
             syscall3(_FileRead, KP, &StringTable, sizeof(Elf64_Shdr));
             break;
         }
         default:
         {
             break;
         }
         }
     }
     if (SymbolTable.sh_size == 0 || StringTable.sh_size == 0)
     {
         syscall1(_FileClose, KP);
         return (Elf64_Sym){0};
     }
     for (size_t i = 0; i < (SymbolTable.sh_size / sizeof(Elf64_Sym)); i++)
     {
         // Symbol = (Elf64_Sym *)((uintptr_t)Header + SymbolTable->sh_offset + (i * sizeof(Elf64_Sym)));
         // String = (char *)((uintptr_t)Header + StringTable->sh_offset + Symbol->st_name);
         syscall3(_FileSeek, KP, SymbolTable.sh_offset + (i * sizeof(Elf64_Sym)), SEEK_SET);
         syscall3(_FileRead, KP, &Symbol, sizeof(Elf64_Sym));
         syscall3(_FileSeek, KP, StringTable.sh_offset + Symbol.st_name, SEEK_SET);
         syscall3(_FileRead, KP, &String, sizeof(char *));
         if (strcmp(String, Name) == 0)
         {
             syscall1(_FileClose, KP);
             return Symbol;
         }
     }
     syscall1(_FileClose, KP);
     return (Elf64_Sym){0};
 }
References _Exit(), Elf64_Ehdr::e_shentsize, Elf64_Ehdr::e_shnum, Elf64_Ehdr::e_shoff, i, NULL, SEEK_SET, Elf64_Shdr::sh_link, Elf64_Shdr::sh_offset, Elf64_Shdr::sh_size, Elf64_Shdr::sh_type, SHT_SYMTAB, Elf64_Sym::st_name, strcmp(), syscall1(), syscall2(), and syscall3().
FreePages()
int FreePages (uintptr_t Address, size_t Count)
Definition at line 11 of file fcts.c.
 {
     return syscall2(_FreePages, Address, Count);
 }
References syscall2().
Referenced by ld_load().
GetELFSection()
Elf64_Shdr* GetELFSection (Elf64_Ehdr * Header, uint64_t Index)
Definition at line 156 of file fcts.c.
 {
     Elf64_Shdr *Sheader = GetELFSheader(Header);
     return &Sheader[Index];
 }
References GetELFSheader().
Referenced by GetELFStringTable().
GetELFSheader()
Elf64_Shdr* GetELFSheader (Elf64_Ehdr * Header)
Definition at line 150 of file fcts.c.
 {
     Elf64_Off SheaderOffset = Header->e_shoff;
     return (Elf64_Shdr *)((uintptr_t)Header + SheaderOffset);
 }
References Elf64_Ehdr::e_shoff.
Referenced by GetELFSection().
GetELFStringTable()
char* GetELFStringTable (Elf64_Ehdr * Header)
Definition at line 162 of file fcts.c.
 {
     if (Header->e_shstrndx == SHN_UNDEF)
         return NULL;
     return (char *)Header + GetELFSection(Header, Header->e_shstrndx)->sh_offset;
 }
References Elf64_Ehdr::e_shstrndx, GetELFSection(), NULL, Elf64_Shdr::sh_offset, and SHN_UNDEF.
IPC()
int IPC (int Command, int Type, int ID, int Flags, void * Buffer, size_t Size)
Definition at line 16 of file fcts.c.
 {
     return syscall6(_IPC, (long)Command, (long)Type, (long)ID, (long)Flags, (long)Buffer, (long)Size);
 }
References syscall6().
Referenced by ld_load().
KernelCTL()
uintptr_t KernelCTL (int Command, uint64_t Arg1, uint64_t Arg2, uint64_t Arg3, uint64_t Arg4)
Definition at line 21 of file fcts.c.
 {
     return syscall5(_KernelCTL, Command, Arg1, Arg2, Arg3, Arg4);
 }
References syscall5().
Referenced by ld_load(), and ld_main().
ltoa()
char* ltoa (long Value, char * Buffer, int Base)
Definition at line 42 of file fcts.c.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     long n = (long)abs((int)Value);
     int i = 0;
     while (n)
     {
         int r = n % Base;
         if (r >= 10)
             Buffer[i++] = 65 + (r - 10);
         else
             Buffer[i++] = 48 + r;
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     if (Value < 0 && Base == 10)
         Buffer[i++] = '-';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References abs(), i, n, r, and reverse().
memcpy()
void* memcpy (void * dest, const void * src, size_t n)
Definition at line 90 of file fcts.c.
 {
     uint8_t *d = dest;
     const uint8_t *s = src;
     while (n--)
         *d++ = *s++;
     return dest;
 }
References n.
Referenced by __get_handler_set(), accessDtv(), append(), cht_GetParam(), do_glob(), ResizePrinter::expand(), ExtendLumpInfo(), F_TextWrite(), G_DoCompleted(), G_PlayerReborn(), G_Ticker(), getaddrinfo(), gethostbyname(), getnameinfo(), getutent_r(), I_Endoom(), I_FinishUpdate(), I_ReadScreen(), I_Scale1x(), I_Stretch1x(), iconv(), IncreaseDemoBuffer(), inet_makeaddr(), mlibc::initStackGuard(), initTlsObjects(), mlibc::mem_file::io_write(), mlibc::ioctl_drm(), load(), mlibc::lookup_addr_dns(), mlibc::lookup_name_dns(), mlibc::lookup_name_hosts(), mlibc::lookup_name_ip(), mlibc::lookup_name_null(), main(), match_bracket(), mem_fread(), mem_fwrite(), mempcpy(), openlog(), P_SpawnMapThing(), parse_bracket(), parse_bracket_terms(), processCopyRela(), R_DrawColumnInCache(), R_FillBackScreen(), R_FlatNumForName(), R_InitSpriteDefs(), R_InitTextures(), R_StoreWallRange(), R_VideoErase(), mlibc::abstract_file::read(), readdir(), readdir_r(), realpath(), regcomp(), scandir(), SHA1_Final(), anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname(), StatCopy(), stpcpy(), stpncpy(), strdup(), strndup(), mlibc::sys_pselect(), mlibc::sys_read_entries(), Transform(), TryRunTics(), tzset(), anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt(), V_CopyRect(), V_DrawBlock(), V_DrawRawScreen(), wipe_initColorXForm(), wipe_initMelt(), wipe_shittyColMajorXform(), wmemcpy(), and mlibc::abstract_file::write().
memset()
void* memset (void * s, int c, size_t n)
Definition at line 99 of file fcts.c.
 {
     uint8_t *p = s;
     while (n--)
         *p++ = c;
 }
References c, n, and p.
Referenced by __FD_ZERO(), __mlibc_cpu_zero(), ObjectRepository::_fetchFromFile(), accessDtv(), allocateTcb(), AM_clearFB(), BuildNewTic(), calloc(), DG_Init(), do_scanf(), G_BuildTiccmd(), G_DoLoadLevel(), G_PlayerFinishLevel(), G_PlayerReborn(), GenerateTextureHashTable(), GetSectorAtNullAddress(), I_Error(), I_InitGraphics(), I_Stretch5x(), initTlsObjects(), ld_load(), LoadResponseFile(), M_ExtractFileBase(), main(), P_LoadBlockMap(), P_LoadLineDefs(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_ReadSaveGameHeader(), P_SpawnMobj(), P_SpawnSpecials(), P_UpdateSpecials(), P_WriteSaveGameHeader(), PadRejectArray(), ParseDMXConfig(), pthread_barrier_destroy(), pthread_condattr_destroy(), pthread_mutexattr_destroy(), R_CheckPlane(), R_ClearPlanes(), R_FindPlane(), R_GenerateLookup(), R_InitSpriteDefs(), R_PrecacheLevel(), regcomp(), SHA1_Final(), socket_setup(), stpncpy(), mlibc::sys_getrusage(), mlibc::sys_pselect(), tre_mem_alloc_impl(), tre_mem_new_impl(), tre_tnfa_run_backtrack(), tre_tnfa_run_parallel(), verify_decode(), W_GenerateHashTable(), and WritePCXfile().
Print__()
void Print__ (char * String)
Definition at line 78 of file fcts.c.
 {
     for (short i = 0; String[i] != '\0'; i++)
         PutCharToKernelConsole(String[i]);
 }
References i, and PutCharToKernelConsole().
Referenced by PrintNL__().
PrintNL__()
void PrintNL__ (char * String)
Definition at line 84 of file fcts.c.
 {
     Print__(String);
     Print__("\n");
 }
References Print__().
PutCharToKernelConsole()
void PutCharToKernelConsole (char c)
Definition at line 70 of file fcts.c.
 {
     __asm__ __volatile__("syscall"
                          :
                          : "a"(1), "D"(c), "S"(0)
                          : "rcx", "r11", "memory");
 }
References c.
Referenced by Print__().
RequestPages()
uintptr_t RequestPages (size_t Count)
Definition at line 6 of file fcts.c.
 {
     return syscall1(_RequestPages, Count);
 }
References syscall1().
Referenced by ld_load().
reverse()
char* reverse (char * Buffer, int i, int j)
Definition at line 35 of file fcts.c.
 {
     while (i < j)
         swap(&Buffer[i++], &Buffer[j--]);
     return Buffer;
 }
References i, j, and swap().
Referenced by ltoa().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 106 of file fcts.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
Referenced by callback(), check_root_group(), CheckDirectoryHasIWAD(), cmpstringp(), ELFLookupSymbol(), ends_with(), getgrnam(), getgrnam_r(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), getpwnam(), getpwnam_r(), GUS_WriteConfig(), iconv_open(), InitGameVersion(), M_GetSaveGameDir(), M_SaveSelect(), M_SetConfigDir(), M_StringEndsWith(), main(), P_ReadSaveGameHeader(), mlibc::query_locale_description(), SearchCollection(), sort(), StatDump(), test1(), test3(), test4(), test5(), and test7().
swap()
void swap (char * x, char * y)
Definition at line 28 of file fcts.c.
 {
     char t = *x;
     *x = *y;
     *y = t;
 }
References x, and y.
Referenced by reverse(), and anonymous_namespace{environment.cpp}::unassign_variable().