Fennix Userspace: Userspace/libc/ElfInterpreter/ldstart.c File Reference
ldstart.c File Reference
Functions
void __attribute__ ((naked, used, no_stack_protector))
void _exit (int Code)
Function Documentation
__attribute__()
void __attribute__ ((naked, used, no_stack_protector))
Definition at line 1 of file ldstart.c.
 {
     __asm__("movq $0, %rbp\n"
             "pushq %rbp\n"
             "pushq %rbp\n"
             "movq %rsp, %rbp\n"
             "pushq %rcx\n"
             "pushq %rdx\n"
             "pushq %rsi\n"
             "pushq %rdi\n"
             "call ld_main\n"
             "movl %eax, %edi\n" // Move return value to edi
             "cmp $0, %edi\n" // Check if return value is 0
             "jne _exit\n" // If not, jump to _exit
             "popq %rdi\n"
             "popq %rsi\n"
             "popq %rdx\n"
             "popq %rcx\n"
             "call ld_load\n"
             "movl %eax, %edi\n" // Move return value to edi
             "call _exit"); // Call _exit
 }
References __asm__().
_exit()
void _exit (int Code)
Definition at line 28 of file ldstart.c.
 {
     __asm__ __volatile__("syscall"
                          :
                          : "a"(0), "D"(Code)
                          : "rcx", "r11", "memory");
     while (1)
         ;
 }
References __asm__(), and Code.
Referenced by __attribute__(), __dls3(), _exit_SUCCESS(), child(), daemon(), do_wordexp(), doit(), exec_builtin(), exec_conf(), execvp_or_die(), exit(), fork_transformer(), forkpty(), ftpd_main(), gotsig(), handle_incoming_and_exit(), hush_exit(), hush_main(), inetd_main(), kill_myself_with_sig(), log_and_exit(), make_new_session(), onintr(), popen_ls(), processorstart(), pseudo_exec(), run(), run_pipe(), setup_heredoc(), spawn(), and xvfork_parent_waits_and_exits().