Fennix Kernel: Kernel/Core/Memory/Memory.cpp File Reference
Memory.cpp File Reference
#include <memory.hpp>
#include <convert.h>
#include <lock.hpp>
#include <debug.h>
#include "HeapAllocators/Xalloc/Xalloc.hpp"
#include "../Library/liballoc_1_1.h"
#include "../../kernel.h"
Macros
#define memdbg(m, ...)
Functions
NIF void MapFromZero (PageTable4 *PT, BootInfo *Info)
NIF void MapFramebuffer (PageTable4 *PT, BootInfo *Info)
NIF void MapKernel (PageTable4 *PT, BootInfo *Info)
NIF void InitializeMemoryManagement (BootInfo *Info)
void * HeapMalloc (size_t Size)
void * HeapCalloc (size_t n, size_t Size)
void * HeapRealloc (void *Address, size_t Size)
void HeapFree (void *Address)
void * operator new (size_t Size)
void * operator new[] (size_t Size)
void * operator new (unsigned long Size, std::align_val_t Alignment)
void operator delete (void *Pointer)
void operator delete[] (void *Pointer)
void operator delete (void *Pointer, long unsigned int Size)
void operator delete[] (void *Pointer, long unsigned int Size)
Variables
Physical KernelAllocator
PageTable4 * KernelPageTable = nullptr
PageTable4 * UserspaceKernelOnlyPageTable = nullptr
void * KPT = nullptr
static MemoryAllocatorType AllocatorType = MemoryAllocatorType::None
Xalloc::V1 * XallocV1Allocator = nullptr
Macro Definition Documentation
memdbg
#define memdbg (m, ...)
Definition at line 22 of file Memory.cpp.
Function Documentation
HeapCalloc()
void* HeapCalloc (size_t n, size_t Size)
Definition at line 305 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(AllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("calloc(%d, %d)->[%s]", n, Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     void *ret = nullptr;
     switch (AllocatorType)
     {
     case MemoryAllocatorType::Pages:
     {
         ret = KernelAllocator.RequestPages(TO_PAGES(n * Size));
         memset(ret, 0, n * Size);
         break;
     }
     case MemoryAllocatorType::XallocV1:
     {
         ret = XallocV1Allocator->calloc(n, Size);
         break;
     }
     case MemoryAllocatorType::liballoc11:
     {
         void *ret = PREFIX(calloc)(n, Size);
         memset(ret, 0, Size);
         return ret;
     }
     default:
         throw;
     }
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "calloc( %ld %ld )=%p-%p~%p\n\r", n, Size, ret, (void *)((uintptr_t)ret + (n * Size)), __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
References AllocatorType, calloc(), Xalloc::V1::calloc(), UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), KernelAllocator, KernelSymbolTable, memdbg, memset(), PREFIX, Size, sprintf(), UniversalAsynchronousReceiverTransmitter::UART::Write(), and XallocV1Allocator.
HeapFree()
void HeapFree (void * Address)
Definition at line 403 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(AllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("free(%#lx)->[%s]", Address, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "free( %p )~%p\n\r", Address, __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     switch (AllocatorType)
     {
     case unlikely(MemoryAllocatorType::Pages):
     {
         KernelAllocator.FreePage(Address); // WARNING: Potential memory leak
         break;
     }
     case MemoryAllocatorType::XallocV1:
     {
         XallocV1Allocator->free(Address);
         break;
     }
     case MemoryAllocatorType::liballoc11:
     {
         PREFIX(free)
         (Address);
         break;
     }
     default:
         throw;
     }
 }
References Address, AllocatorType, UniversalAsynchronousReceiverTransmitter::COM3, Xalloc::V1::free(), free(), SymbolResolver::Symbols::GetSymbolFromAddress(), KernelAllocator, KernelSymbolTable, memdbg, PREFIX, sprintf(), unlikely, UniversalAsynchronousReceiverTransmitter::UART::Write(), and XallocV1Allocator.
Referenced by operator delete(), and operator delete[]().
HeapMalloc()
void* HeapMalloc (size_t Size)
Definition at line 256 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(AllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("malloc(%d)->[%s]", Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     void *ret = nullptr;
     switch (AllocatorType)
     {
     case MemoryAllocatorType::Pages:
     {
         ret = KernelAllocator.RequestPages(TO_PAGES(Size));
         memset(ret, 0, Size);
         break;
     }
     case MemoryAllocatorType::XallocV1:
     {
         ret = XallocV1Allocator->malloc(Size);
         break;
     }
     case MemoryAllocatorType::liballoc11:
     {
         ret = PREFIX(malloc)(Size);
         memset(ret, 0, Size);
         break;
     }
     default:
         throw;
     }
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "malloc( %ld )=%p-%p~%p\n\r", Size, ret, (void *)((uintptr_t)ret + Size), __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
References AllocatorType, UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), KernelAllocator, KernelSymbolTable, malloc(), Xalloc::V1::malloc(), memdbg, memset(), PREFIX, Size, sprintf(), UniversalAsynchronousReceiverTransmitter::UART::Write(), and XallocV1Allocator.
Referenced by operator new(), and operator new[]().
HeapRealloc()
void* HeapRealloc (void * Address, size_t Size)
Definition at line 354 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(AllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("realloc(%#lx, %d)->[%s]", Address, Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     void *ret = nullptr;
     switch (AllocatorType)
     {
     case unlikely(MemoryAllocatorType::Pages):
     {
         ret = KernelAllocator.RequestPages(TO_PAGES(Size)); // WARNING: Potential memory leak
         memset(ret, 0, Size);
         break;
     }
     case MemoryAllocatorType::XallocV1:
     {
         ret = XallocV1Allocator->realloc(Address, Size);
         break;
     }
     case MemoryAllocatorType::liballoc11:
     {
         void *ret = PREFIX(realloc)(Address, Size);
         memset(ret, 0, Size);
         return ret;
     }
     default:
         throw;
     }
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "realloc( %p %ld )=%p-%p~%p\n\r", Address, Size, ret, (void *)((uintptr_t)ret + Size), __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
References Address, AllocatorType, UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), KernelAllocator, KernelSymbolTable, memdbg, memset(), PREFIX, Xalloc::V1::realloc(), realloc(), Size, sprintf(), unlikely, UniversalAsynchronousReceiverTransmitter::UART::Write(), and XallocV1Allocator.
InitializeMemoryManagement()
NIF void InitializeMemoryManagement (BootInfo * Info)
Definition at line 149 of file Memory.cpp.
 {
 #ifdef DEBUG
     for (uint64_t i = 0; i < Info->Memory.Entries; i++)
     {
         uintptr_t Base = reinterpret_cast<uintptr_t>(Info->Memory.Entry[i].BaseAddress);
         uintptr_t Length = Info->Memory.Entry[i].Length;
         uintptr_t End = Base + Length;
         const char *Type = "Unknown";
         switch (Info->Memory.Entry[i].Type)
         {
         case likely(Usable):
             Type = "Usable";
             break;
         case Reserved:
             Type = "Reserved";
             break;
         case ACPIReclaimable:
             Type = "ACPI Reclaimable";
             break;
         case ACPINVS:
             Type = "ACPI NVS";
             break;
         case BadMemory:
             Type = "Bad Memory";
             break;
         case BootloaderReclaimable:
             Type = "Bootloader Reclaimable";
             break;
         case KernelAndModules:
             Type = "Kernel and Modules";
             break;
         case Framebuffer:
             Type = "Framebuffer";
             break;
         default:
             break;
         }
         debug("%lld: %#016llx-%#016llx %s",
               i,
               Base,
               End,
               Type);
     }
 #endif
     trace("Initializing Physical Memory Manager");
     // KernelAllocator = Physical(); <- Already called in the constructor
     KernelAllocator.Init(Info);
     debug("Memory Info: %lldMB / %lldMB (%lldMB reserved)",
           TO_MB(KernelAllocator.GetUsedMemory()),
           TO_MB(KernelAllocator.GetTotalMemory()),
           TO_MB(KernelAllocator.GetReservedMemory()));
     AllocatorType = MemoryAllocatorType::Pages;
     trace("Initializing Virtual Memory Manager");
     KernelPageTable = (PageTable4 *)KernelAllocator.RequestPages(TO_PAGES(PAGE_SIZE));
     memset(KernelPageTable, 0, PAGE_SIZE);
     UserspaceKernelOnlyPageTable = (PageTable4 *)KernelAllocator.RequestPages(TO_PAGES(PAGE_SIZE));
     memset(UserspaceKernelOnlyPageTable, 0, PAGE_SIZE);
     debug("Mapping from 0x0 to %#llx", Info->Memory.Size);
     MapFromZero(KernelPageTable, Info);
     debug("Mapping from 0x0 %#llx for Userspace Page Table", Info->Memory.Size);
     UserspaceKernelOnlyPageTable[0] = KernelPageTable[0];
     /* Mapping Framebuffer address */
     debug("Mapping Framebuffer");
     MapFramebuffer(KernelPageTable, Info);
     debug("Mapping Framebuffer for Userspace Page Table");
     MapFramebuffer(UserspaceKernelOnlyPageTable, Info);
     /* Kernel mapping */
     debug("Mapping Kernel");
     MapKernel(KernelPageTable, Info);
     debug("Mapping Kernel for Userspace Page Table");
     MapKernel(UserspaceKernelOnlyPageTable, Info);
     trace("Applying new page table from address %p", KernelPageTable);
 #ifdef DEBUG
     debug("Kernel:");
     tracepagetable(KernelPageTable);
     debug("Userspace:");
     tracepagetable(UserspaceKernelOnlyPageTable);
 #endif
     KPT = KernelPageTable;
 #if defined(a64) || defined(a32)
     asmv("mov %0, %%cr3" ::"r"(KPT));
 #elif defined(aa64)
     asmv("msr ttbr0_el1, %0" ::"r"(KPT));
 #endif
     debug("Page table updated.");
     if (strstr(Info->Kernel.CommandLine, "xallocv1"))
     {
         XallocV1Allocator = new Xalloc::V1((void *)KERNEL_HEAP_BASE, false, false);
         AllocatorType = MemoryAllocatorType::XallocV1;
         trace("XallocV1 Allocator initialized (%p)", XallocV1Allocator);
     }
     else if (strstr(Info->Kernel.CommandLine, "liballoc11"))
     {
         AllocatorType = MemoryAllocatorType::liballoc11;
     }
 }
References ACPINVS, ACPIReclaimable, AllocatorType, asmv, BadMemory, BootloaderReclaimable, debug, Framebuffer, Info, KernelAllocator, KernelAndModules, KernelPageTable, KPT, Length, likely, MapFramebuffer(), MapFromZero(), MapKernel(), memset(), Reserved, strstr(), trace, Type, Usable, UserspaceKernelOnlyPageTable, and XallocV1Allocator.
Referenced by Entry().
MapFramebuffer()
NIF void MapFramebuffer (PageTable4 * PT, BootInfo * Info)
Definition at line 85 of file Memory.cpp.
 {
     Virtual va = Virtual(PT);
     int itrfb = 0;
     while (1)
     {
         if (!Info->Framebuffer[itrfb].BaseAddress)
             break;
         for (uintptr_t fb_base = (uintptr_t)Info->Framebuffer[itrfb].BaseAddress;
              fb_base < ((uintptr_t)Info->Framebuffer[itrfb].BaseAddress + ((Info->Framebuffer[itrfb].Pitch * Info->Framebuffer[itrfb].Height) + PAGE_SIZE));
              fb_base += PAGE_SIZE)
             va.Map((void *)fb_base, (void *)fb_base, PTFlag::RW | PTFlag::US | PTFlag::G);
         itrfb++;
     }
 }
References G(), Info, and RW.
Referenced by InitializeMemoryManagement().
MapFromZero()
NIF void MapFromZero (PageTable4 * PT, BootInfo * Info)
Definition at line 60 of file Memory.cpp.
 {
     static int once = 0;
     if (!once++)
     {
         Virtual va = Virtual(PT);
         void *NullAddress = KernelAllocator.RequestPage();
         memset(NullAddress, 0, PAGE_SIZE); // TODO: If the CPU instruction pointer hits this page, there should be function to handle it. (memcpy assembly code?)
         va.Map((void *)0, (void *)NullAddress, PTFlag::RW | PTFlag::US);
         uintptr_t VirtualOffsetNormalVMA = NORMAL_VMA_OFFSET;
         size_t MemSize = Info->Memory.Size;
         for (size_t t = 0; t < MemSize; t += PAGE_SIZE)
         {
             va.Map((void *)t, (void *)t, PTFlag::RW /* | PTFlag::US */);
             va.Map((void *)VirtualOffsetNormalVMA, (void *)t, PTFlag::RW /* | PTFlag::US */);
             VirtualOffsetNormalVMA += PAGE_SIZE;
         }
     }
     else
     {
         error("MapFromZero() called more than once!");
         CPU::Stop();
     }
 }
References error, Info, KernelAllocator, memset(), RW, and CPU::Stop().
Referenced by InitializeMemoryManagement().
MapKernel()
NIF void MapKernel (PageTable4 * PT, BootInfo * Info)
Definition at line 102 of file Memory.cpp.
 {
     /*    KernelStart             KernelTextEnd       KernelRoDataEnd                  KernelEnd
     Kernel Start & Text Start ------ Text End ------ Kernel Rodata End ------ Kernel Data End & Kernel End
     */
     Virtual va = Virtual(PT);
     uintptr_t KernelStart = (uintptr_t)&_kernel_start;
     uintptr_t KernelTextEnd = (uintptr_t)&_kernel_text_end;
     uintptr_t KernelDataEnd = (uintptr_t)&_kernel_data_end;
     uintptr_t KernelRoDataEnd = (uintptr_t)&_kernel_rodata_end;
     uintptr_t KernelEnd = (uintptr_t)&_kernel_end;
     uintptr_t BaseKernelMapAddress = (uintptr_t)Info->Kernel.PhysicalBase;
     uintptr_t k;
     for (k = KernelStart; k < KernelTextEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     for (k = KernelTextEnd; k < KernelDataEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW | PTFlag::G);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     for (k = KernelDataEnd; k < KernelRoDataEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::P | PTFlag::G);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     for (k = KernelRoDataEnd; k < KernelEnd; k += PAGE_SIZE)
     {
         va.Map((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW | PTFlag::G);
         KernelAllocator.LockPage((void *)BaseKernelMapAddress);
         BaseKernelMapAddress += PAGE_SIZE;
     }
     debug("\nStart: %#llx - Text End: %#llx - RoEnd: %#llx - End: %#llx\nStart Physical: %#llx - End Physical: %#llx",
           KernelStart, KernelTextEnd, KernelRoDataEnd, KernelEnd, Info->Kernel.PhysicalBase, BaseKernelMapAddress - PAGE_SIZE);
 }
References debug, G(), Info, KernelAllocator, P, and RW.
Referenced by InitializeMemoryManagement().
operator delete() [1/2]
void operator delete (void * Pointer)
Definition at line 524 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("delete(%#lx)->[%s]", Pointer, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "delete( %p )~%p\n\r", Pointer, __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     HeapFree(Pointer);
 }
References UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), HeapFree(), KernelSymbolTable, memdbg, sprintf(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator delete() [2/2]
void operator delete (void * Pointer, long unsigned int Size)
Definition at line 574 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("delete(%#lx, %d)->[%s]", Pointer, Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "delete( %p %ld )~%p\n\r", Pointer, Size, __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     HeapFree(Pointer);
     UNUSED(Size);
 }
References UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), HeapFree(), KernelSymbolTable, memdbg, Size, sprintf(), UNUSED, and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator delete[]() [1/2]
void operator delete[] (void * Pointer)
Definition at line 549 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("delete[](%#lx)->[%s]", Pointer, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "delete[]( %p )~%p\n\r", Pointer, __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     HeapFree(Pointer);
 }
References UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), HeapFree(), KernelSymbolTable, memdbg, sprintf(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator delete[]() [2/2]
void operator delete[] (void * Pointer, long unsigned int Size)
Definition at line 600 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("delete[](%#lx, %d)->[%s]", Pointer, Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "delete[]( %p %ld )~%p\n\r", Pointer, Size, __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     HeapFree(Pointer);
     UNUSED(Size);
 }
References UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), HeapFree(), KernelSymbolTable, memdbg, Size, sprintf(), UNUSED, and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator new() [1/2]
void* operator new (size_t Size)
Definition at line 448 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("new(%d)->[%s]", Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "new( %ld )~%p\n\r", Size, __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return HeapMalloc(Size);
 }
References UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), HeapMalloc(), KernelSymbolTable, memdbg, Size, sprintf(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator new() [2/2]
void* operator new (unsigned long Size, std::align_val_t Alignment)
Definition at line 498 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("new(%d, %d)->[%s]", Size, Alignment, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
     fixme("operator new with alignment(%#lx) is not implemented", Alignment);
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "new( %ld %#lx )~%p\n\r", Size, (uintptr_t)Alignment, __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return HeapMalloc(Size);
 }
References UniversalAsynchronousReceiverTransmitter::COM3, fixme, SymbolResolver::Symbols::GetSymbolFromAddress(), HeapMalloc(), KernelSymbolTable, memdbg, Size, sprintf(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
operator new[]()
void* operator new[] (size_t Size)
Definition at line 473 of file Memory.cpp.
 {
 #ifdef DEBUG_ALLOCATIONS_SL
     SmartLockClass lock___COUNTER__(OperatorAllocatorLock, (KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown"));
 #endif
     memdbg("new[](%d)->[%s]", Size, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress((uintptr_t)__builtin_return_address(0)) : "Unknown");
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         mExtTrkLock.TimeoutLock(__FUNCTION__, 100000);
         sprintf(mExtTrkLog, "new[]( %ld )~%p\n\r", Size, __builtin_return_address(0));
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3).Write(mExtTrkLog[i]);
             if (mExtTrkLog[i] == '\r')
                 break;
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return HeapMalloc(Size);
 }
References UniversalAsynchronousReceiverTransmitter::COM3, SymbolResolver::Symbols::GetSymbolFromAddress(), HeapMalloc(), KernelSymbolTable, memdbg, Size, sprintf(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
Variable Documentation
AllocatorType
MemoryAllocatorType AllocatorType = MemoryAllocatorType::None static
Definition at line 37 of file Memory.cpp.
Referenced by HeapCalloc(), HeapFree(), HeapMalloc(), HeapRealloc(), and InitializeMemoryManagement().
KernelAllocator
Physical KernelAllocator
Definition at line 32 of file Memory.cpp.
Referenced by Video::Display::CreateBuffer(), Tasking::Task::CreateProcess(), Video::Display::DeleteBuffer(), CrashHandler::DisplayTopOverlay(), Execute::ELFLoad(), Execute::ELFLoadRel(), Disk::Manager::FetchDisks(), Video::Font::Font(), FreePage(), HeapCalloc(), HeapFree(), HeapMalloc(), HeapRealloc(), GlobalDescriptorTable::Init(), Interrupts::Initialize(), CPU::InitializeFeatures(), InitializeMemoryManagement(), liballoc_alloc(), liballoc_free(), Main(), MapFromZero(), MapKernel(), Recovery::PlayAudio(), Recovery::KernelRecovery::RecoveryThread(), Tasking::Task::RemoveProcess(), RequestPage(), Tasking::Task::RevertProcessCreation(), Execute::Spawn(), CrashHandler::UserInput(), Xalloc_FREE_PAGES(), and Xalloc_REQUEST_PAGES().
KernelPageTable
PageTable4* KernelPageTable = nullptr
Definition at line 33 of file Memory.cpp.
Referenced by InitializeMemoryManagement(), Xalloc_MAP_MEMORY(), and Xalloc_UNMAP_MEMORY().
KPT
void* KPT = nullptr
Definition at line 35 of file Memory.cpp.
Referenced by InitializeMemoryManagement().
UserspaceKernelOnlyPageTable
PageTable4* UserspaceKernelOnlyPageTable = nullptr
Definition at line 34 of file Memory.cpp.
Referenced by Tasking::Task::CreateProcess(), and InitializeMemoryManagement().
XallocV1Allocator
Xalloc::V1* XallocV1Allocator = nullptr
Definition at line 38 of file Memory.cpp.
Referenced by HeapCalloc(), HeapFree(), HeapMalloc(), HeapRealloc(), and InitializeMemoryManagement().