Fennix: Userspace/mlibc/options/ansi/musl-generic-math/__cos.c File Reference
__cos.c File Reference
#include "libm.h"
Functions
double __cos (double x, double y)
Variables
static const double C1 = 4.16666666666666019037e-02
static const double C2 = -1.38888888888741095749e-03
static const double C3 = 2.48015872894767294178e-05
static const double C4 = -2.75573143513906633035e-07
static const double C5 = 2.08757232129817482790e-09
static const double C6 = -1.13596475577881948265e-11
Function Documentation
__cos()
double __cos (double x, double y)
Definition at line 61 of file __cos.c.
 {
     double_t hz,z,r,w;
     z  = x*x;
     w  = z*z;
     r  = z*(C1+z*(C2+z*C3)) + w*w*(C4+z*(C5+z*C6));
     hz = 0.5*z;
     w  = 1.0-hz;
     return w + (((1.0-w)-hz) + (z*r-x*y));
 }
References C1, C2, C3, C4, C5, C6, r, x, and y.
Referenced by cos(), sin(), sin_pi(), sincos(), and sinpi().
Variable Documentation
C1
const double C1 = 4.16666666666666019037e-02 static
Definition at line 54 of file __cos.c.
Referenced by __cos().
C2
const double C2 = -1.38888888888741095749e-03 static
Definition at line 55 of file __cos.c.
Referenced by __cos().
C3
const double C3 = 2.48015872894767294178e-05 static
Definition at line 56 of file __cos.c.
Referenced by __cos().
C4
const double C4 = -2.75573143513906633035e-07 static
Definition at line 57 of file __cos.c.
Referenced by __cos().
C5
const double C5 = 2.08757232129817482790e-09 static
Definition at line 58 of file __cos.c.
Referenced by __cos().
C6
const double C6 = -1.13596475577881948265e-11 static
Definition at line 59 of file __cos.c.
Referenced by __cos().