Fennix: Userspace/musl/include/sys/time.h File Reference
time.h File Reference
#include <features.h>
#include <sys/select.h>
Data Structures
struct itimerval
Macros
#define ITIMER_REAL 0
#define ITIMER_VIRTUAL 1
#define ITIMER_PROF 2
Functions
int gettimeofday (struct timeval *__restrict, void *__restrict)
int getitimer (int, struct itimerval *)
int setitimer (int, const struct itimerval *__restrict, struct itimerval *__restrict)
int utimes (const char *, const struct timeval[2])
Data Structure Documentation
itimerval
struct itimerval
Definition at line 6 of file time.h.
Data Fields
struct timeval it_interval
struct timeval it_value
Macro Definition Documentation
ITIMER_PROF
#define ITIMER_PROF 2
Definition at line 15 of file time.h.
ITIMER_REAL
#define ITIMER_REAL 0
Definition at line 13 of file time.h.
ITIMER_VIRTUAL
#define ITIMER_VIRTUAL 1
Definition at line 14 of file time.h.
Function Documentation
getitimer()
int getitimer (int which, struct itimerval * curr_value)
Definition at line 54 of file sys-time-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getitimer, -1);
     if(int e = mlibc::sys_getitimer(which, curr_value); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __syscall, __syscall_ret(), errno, itimerval::it_interval, itimerval::it_value, MLIBC_CHECK_OR_ENOSYS, r, mlibc::sys_getitimer(), syscall(), timeval::tv_sec, and timeval::tv_usec.
Referenced by __getitimer_time32().
gettimeofday()
int gettimeofday (struct timeval * __restrict, void * __restrict)
Definition at line 29 of file gettimeofday.c.
 {
   tv->tv_sec = (time_t) time ((time_t *)0);
   tv->tv_usec = 0;
   return 0;
 }
References time(), timeval::tv_sec, and timeval::tv_usec.
Referenced by __gettimeofday_time32(), _rl_timeout_handle_sigalrm(), _rl_timeout_init(), assign_seconds(), genseed(), get_epochrealtime(), get_seconds(), main(), rl_timeout_remaining(), sh_seedrand(), shtimer_chktimeout(), shtimer_set(), strftime(), and times().
setitimer()
int setitimer (int which, const struct itimerval * __restrict, struct itimerval * __restrict)
Definition at line 63 of file sys-time-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setitimer, -1);
     if(int e = mlibc::sys_setitimer(which, new_value, old_value); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setitimer().
Referenced by __setitimer_time32(), alarm(), and ualarm().
utimes()
int utimes (const char * filename, const struct timeval times[2])
Definition at line 6 of file posix_time.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_utimensat, -1);
     struct timespec time[2];
     if(times == nullptr) {
         time[0].tv_sec = UTIME_NOW;
         time[0].tv_nsec = UTIME_NOW;
         time[1].tv_sec = UTIME_NOW;
         time[1].tv_nsec = UTIME_NOW;
     } else {
         time[0].tv_sec = times[0].tv_sec;
         time[0].tv_nsec = times[0].tv_usec * 1000;
         time[1].tv_sec = times[1].tv_sec;
         time[1].tv_nsec = times[1].tv_usec * 1000;
     }
     if (int e = mlibc::sys_utimensat(AT_FDCWD, filename, time, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References __futimesat(), AT_FDCWD, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_utimensat(), time(), times(), and UTIME_NOW.
Referenced by __utimes_time32().