Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/m_menu.h File Reference
m_menu.h File Reference
#include "d_event.h"
Functions
boolean M_Responder (event_t *ev)
void M_Ticker (void)
void M_Drawer (void)
void M_Init (void)
void M_StartControlPanel (void)
Variables
int detailLevel
int screenblocks
Function Documentation
M_Drawer()
void M_Drawer (void)
Definition at line 1951 of file m_menu.c.
 {
     static short    x;
     static short    y;
     unsigned int    i;
     unsigned int    max;
     char        string[80];
     char               *name;
     int         start;
     inhelpscreens = false;
     // Horiz. & Vertically center string and print it.
     if (messageToPrint)
     {
     start = 0;
     y = SCREENHEIGHT/2 - M_StringHeight(messageString) / 2;
     while (messageString[start] != '\0')
     {
         int foundnewline = 0;
             for (i = 0; i < strlen(messageString + start); i++)
             {
                 if (messageString[start + i] == '\n')
                 {
                     M_StringCopy(string, messageString + start,
                                  sizeof(string));
                     if (i < sizeof(string))
                     {
                         string[i] = '\0';
                     }
                     foundnewline = 1;
                     start += i + 1;
                     break;
                 }
             }
             if (!foundnewline)
             {
                 M_StringCopy(string, messageString + start, sizeof(string));
                 start += strlen(string);
             }
         x = SCREENWIDTH/2 - M_StringWidth(string) / 2;
         M_WriteText(x, y, string);
         y += SHORT(hu_font[0]->height);
     }
     return;
     }
     //if (opldev)
     //{
     //    M_DrawOPLDev();
     //}
     if (!menuactive)
     return;
     if (currentMenu->routine)
     currentMenu->routine();         // call Draw routine
     // DRAW MENU
     x = currentMenu->x;
     y = currentMenu->y;
     max = currentMenu->numitems;
     for (i=0;i<max;i++)
     {
         name = DEH_String(currentMenu->menuitems[i].name);
     if (name[0])
     {
         V_DrawPatchDirect (x, y, W_CacheLumpName(name, PU_CACHE));
     }
     y += LINEHEIGHT;
     }
     // DRAW SKULL
     V_DrawPatchDirect(x + SKULLXOFF, currentMenu->y - 5 + itemOn*LINEHEIGHT,
               W_CacheLumpName(DEH_String(skullName[whichSkull]),
                       PU_CACHE));
 }
References currentMenu, DEH_String, anonymous_namespace{search.cpp}::height(), hu_font, i, inhelpscreens, itemOn, LINEHEIGHT, M_StringCopy(), M_StringHeight(), M_StringWidth(), M_WriteText(), menuactive, menu_s::menuitems, messageString, messageToPrint, menuitem_t::name, name, menu_s::numitems, PU_CACHE, menu_s::routine, SCREENHEIGHT, SCREENWIDTH, skullName, SKULLXOFF, strlen(), V_DrawPatchDirect(), W_CacheLumpName(), whichSkull, menu_s::x, x, y, and menu_s::y.
Referenced by D_Display().
M_Init()
void M_Init (void)
Definition at line 2077 of file m_menu.c.
 {
     currentMenu = &MainDef;
     menuactive = 0;
     itemOn = currentMenu->lastOn;
     whichSkull = 0;
     skullAnimCounter = 10;
     screenSize = screenblocks - 3;
     messageToPrint = 0;
     messageString = NULL;
     messageLastMenuActive = menuactive;
     quickSaveSlot = -1;
     // Here we could catch other version dependencies,
     //  like HELP1/2, and four episodes.
     switch ( gamemode )
     {
       case commercial:
         // Commercial has no "read this" entry.
     MainMenu[readthis] = MainMenu[quitdoom];
     MainDef.numitems--;
     MainDef.y += 8;
     NewDef.prevMenu = &MainDef;
     break;
       case shareware:
     // Episode 2 and 3 are handled,
     //  branching to an ad screen.
       case registered:
     break;
       case retail:
     // We are fine.
       default:
     break;
     }
     // Versions of doom.exe before the Ultimate Doom release only had
     // three episodes; if we're emulating one of those then don't try
     // to show episode four. If we are, then do show episode four
     // (should crash if missing).
     if (gameversion < exe_ultimate)
     {
     EpiDef.numitems--;
     }
     //opldev = M_CheckParm("-opldev") > 0;
 }
References commercial, currentMenu, EpiDef, exe_ultimate, gamemode, gameversion, itemOn, menu_s::lastOn, MainDef, MainMenu, menuactive, messageLastMenuActive, messageString, messageToPrint, NewDef, NULL, menu_s::numitems, menu_s::prevMenu, quickSaveSlot, quitdoom, readthis, registered, retail, screenblocks, screenSize, shareware, skullAnimCounter, whichSkull, and menu_s::y.
Referenced by D_DoomMain().
M_Responder()
boolean M_Responder (event_t * ev)
Definition at line 1416 of file m_menu.c.
 {
     int             ch;
     int             key;
     int             i;
     static  int     joywait = 0;
     static  int     mousewait = 0;
     static  int     mousey = 0;
     static  int     lasty = 0;
     static  int     mousex = 0;
     static  int     lastx = 0;
     // In testcontrols mode, none of the function keys should do anything
     // - the only key is escape to quit.
     if (testcontrols)
     {
         if (ev->type == ev_quit
          || (ev->type == ev_keydown
           && (ev->data1 == key_menu_activate || ev->data1 == key_menu_quit)))
         {
             I_Quit();
             return true;
         }
         return false;
     }
     // "close" button pressed on window?
     if (ev->type == ev_quit)
     {
         // First click on close button = bring up quit confirm message.
         // Second click on close button = confirm quit
         if (menuactive && messageToPrint && messageRoutine == M_QuitResponse)
         {
             M_QuitResponse(key_menu_confirm);
         }
         else
         {
             S_StartSound(NULL,sfx_swtchn);
             M_QuitDOOM(0);
         }
         return true;
     }
     // key is the key pressed, ch is the actual character typed
     ch = 0;
     key = -1;
     if (ev->type == ev_joystick && joywait < I_GetTime())
     {
     if (ev->data3 < 0)
     {
         key = key_menu_up;
         joywait = I_GetTime() + 5;
     }
     else if (ev->data3 > 0)
     {
         key = key_menu_down;
         joywait = I_GetTime() + 5;
     }
     if (ev->data2 < 0)
     {
         key = key_menu_left;
         joywait = I_GetTime() + 2;
     }
     else if (ev->data2 > 0)
     {
         key = key_menu_right;
         joywait = I_GetTime() + 2;
     }
     if (ev->data1&1)
     {
         key = key_menu_forward;
         joywait = I_GetTime() + 5;
     }
     if (ev->data1&2)
     {
         key = key_menu_back;
         joywait = I_GetTime() + 5;
     }
         if (joybmenu >= 0 && (ev->data1 & (1 << joybmenu)) != 0)
         {
             key = key_menu_activate;
         joywait = I_GetTime() + 5;
         }
     }
     else
     {
     if (ev->type == ev_mouse && mousewait < I_GetTime())
     {
         mousey += ev->data3;
         if (mousey < lasty-30)
         {
         key = key_menu_down;
         mousewait = I_GetTime() + 5;
         mousey = lasty -= 30;
         }
         else if (mousey > lasty+30)
         {
         key = key_menu_up;
         mousewait = I_GetTime() + 5;
         mousey = lasty += 30;
         }
         mousex += ev->data2;
         if (mousex < lastx-30)
         {
         key = key_menu_left;
         mousewait = I_GetTime() + 5;
         mousex = lastx -= 30;
         }
         else if (mousex > lastx+30)
         {
         key = key_menu_right;
         mousewait = I_GetTime() + 5;
         mousex = lastx += 30;
         }
         if (ev->data1&1)
         {
         key = key_menu_forward;
         mousewait = I_GetTime() + 15;
         }
         if (ev->data1&2)
         {
         key = key_menu_back;
         mousewait = I_GetTime() + 15;
         }
     }
     else
     {
         if (ev->type == ev_keydown)
         {
         key = ev->data1;
         ch = ev->data2;
         }
     }
     }
     if (key == -1)
     return false;
     // Save Game string input
     if (saveStringEnter)
     {
     switch(key)
     {
       case KEY_BACKSPACE:
         if (saveCharIndex > 0)
         {
         saveCharIndex--;
         savegamestrings[saveSlot][saveCharIndex] = 0;
         }
         break;
           case KEY_ESCAPE:
             saveStringEnter = 0;
             M_StringCopy(savegamestrings[saveSlot], saveOldString,
                          SAVESTRINGSIZE);
             break;
       case KEY_ENTER:
         saveStringEnter = 0;
         if (savegamestrings[saveSlot][0])
         M_DoSave(saveSlot);
         break;
       default:
             // This is complicated.
             // Vanilla has a bug where the shift key is ignored when entering
             // a savegame name. If vanilla_keyboard_mapping is on, we want
             // to emulate this bug by using 'data1'. But if it's turned off,
             // it implies the user doesn't care about Vanilla emulation: just
             // use the correct 'data2'.
             if (vanilla_keyboard_mapping)
             {
                 ch = key;
             }
             ch = toupper(ch);
             if (ch != ' '
              && (ch - HU_FONTSTART < 0 || ch - HU_FONTSTART >= HU_FONTSIZE))
             {
                 break;
             }
         if (ch >= 32 && ch <= 127 &&
         saveCharIndex < SAVESTRINGSIZE-1 &&
         M_StringWidth(savegamestrings[saveSlot]) <
         (SAVESTRINGSIZE-2)*8)
         {
         savegamestrings[saveSlot][saveCharIndex++] = ch;
         savegamestrings[saveSlot][saveCharIndex] = 0;
         }
         break;
     }
     return true;
     }
     // Take care of any messages that need input
     if (messageToPrint)
     {
     if (messageNeedsInput)
         {
             if (key != ' ' && key != KEY_ESCAPE
              && key != key_menu_confirm && key != key_menu_abort)
             {
                 return false;
             }
     }
     menuactive = messageLastMenuActive;
     messageToPrint = 0;
     if (messageRoutine)
         messageRoutine(key);
     menuactive = false;
     S_StartSound(NULL,sfx_swtchx);
     return true;
     }
     if ((devparm && key == key_menu_help) ||
         (key != 0 && key == key_menu_screenshot))
     {
     G_ScreenShot ();
     return true;
     }
     // F-Keys
     if (!menuactive)
     {
     if (key == key_menu_decscreen)      // Screen size down
         {
         if (automapactive || chat_on)
         return false;
         M_SizeDisplay(0);
         S_StartSound(NULL,sfx_stnmov);
         return true;
     }
         else if (key == key_menu_incscreen) // Screen size up
         {
         if (automapactive || chat_on)
         return false;
         M_SizeDisplay(1);
         S_StartSound(NULL,sfx_stnmov);
         return true;
     }
         else if (key == key_menu_help)     // Help key
         {
         M_StartControlPanel ();
         if ( gamemode == retail )
           currentMenu = &ReadDef2;
         else
           currentMenu = &ReadDef1;
         itemOn = 0;
         S_StartSound(NULL,sfx_swtchn);
         return true;
     }
         else if (key == key_menu_save)     // Save
         {
         M_StartControlPanel();
         S_StartSound(NULL,sfx_swtchn);
         M_SaveGame(0);
         return true;
         }
         else if (key == key_menu_load)     // Load
         {
         M_StartControlPanel();
         S_StartSound(NULL,sfx_swtchn);
         M_LoadGame(0);
         return true;
         }
         else if (key == key_menu_volume)   // Sound Volume
         {
         M_StartControlPanel ();
         currentMenu = &SoundDef;
         itemOn = sfx_vol;
         S_StartSound(NULL,sfx_swtchn);
         return true;
     }
         else if (key == key_menu_detail)   // Detail toggle
         {
         M_ChangeDetail(0);
         S_StartSound(NULL,sfx_swtchn);
         return true;
         }
         else if (key == key_menu_qsave)    // Quicksave
         {
         S_StartSound(NULL,sfx_swtchn);
         M_QuickSave();
         return true;
         }
         else if (key == key_menu_endgame)  // End game
         {
         S_StartSound(NULL,sfx_swtchn);
         M_EndGame(0);
         return true;
         }
         else if (key == key_menu_messages) // Toggle messages
         {
         M_ChangeMessages(0);
         S_StartSound(NULL,sfx_swtchn);
         return true;
         }
         else if (key == key_menu_qload)    // Quickload
         {
         S_StartSound(NULL,sfx_swtchn);
         M_QuickLoad();
         return true;
         }
         else if (key == key_menu_quit)     // Quit DOOM
         {
         S_StartSound(NULL,sfx_swtchn);
         M_QuitDOOM(0);
         return true;
         }
         else if (key == key_menu_gamma)    // gamma toggle
         {
         usegamma++;
         if (usegamma > 4)
         usegamma = 0;
         players[consoleplayer].message = DEH_String(gammamsg[usegamma]);
             I_SetPalette (W_CacheLumpName (DEH_String("PLAYPAL"),PU_CACHE));
         return true;
     }
     }
     // Pop-up menu?
     if (!menuactive)
     {
     if (key == key_menu_activate)
     {
         M_StartControlPanel ();
         S_StartSound(NULL,sfx_swtchn);
         return true;
     }
     return false;
     }
     // Keys usable within menu
     if (key == key_menu_down)
     {
         // Move down to next item
         do
     {
         if (itemOn+1 > currentMenu->numitems-1)
         itemOn = 0;
         else itemOn++;
         S_StartSound(NULL,sfx_pstop);
     } while(currentMenu->menuitems[itemOn].status==-1);
     return true;
     }
     else if (key == key_menu_up)
     {
         // Move back up to previous item
     do
     {
         if (!itemOn)
         itemOn = currentMenu->numitems-1;
         else itemOn--;
         S_StartSound(NULL,sfx_pstop);
     } while(currentMenu->menuitems[itemOn].status==-1);
     return true;
     }
     else if (key == key_menu_left)
     {
         // Slide slider left
     if (currentMenu->menuitems[itemOn].routine &&
         currentMenu->menuitems[itemOn].status == 2)
     {
         S_StartSound(NULL,sfx_stnmov);
         currentMenu->menuitems[itemOn].routine(0);
     }
     return true;
     }
     else if (key == key_menu_right)
     {
         // Slide slider right
     if (currentMenu->menuitems[itemOn].routine &&
         currentMenu->menuitems[itemOn].status == 2)
     {
         S_StartSound(NULL,sfx_stnmov);
         currentMenu->menuitems[itemOn].routine(1);
     }
     return true;
     }
     else if (key == key_menu_forward)
     {
         // Activate menu item
     if (currentMenu->menuitems[itemOn].routine &&
         currentMenu->menuitems[itemOn].status)
     {
         currentMenu->lastOn = itemOn;
         if (currentMenu->menuitems[itemOn].status == 2)
         {
         currentMenu->menuitems[itemOn].routine(1);      // right arrow
         S_StartSound(NULL,sfx_stnmov);
         }
         else
         {
         currentMenu->menuitems[itemOn].routine(itemOn);
         S_StartSound(NULL,sfx_pistol);
         }
     }
     return true;
     }
     else if (key == key_menu_activate)
     {
         // Deactivate menu
     currentMenu->lastOn = itemOn;
     M_ClearMenus ();
     S_StartSound(NULL,sfx_swtchx);
     return true;
     }
     else if (key == key_menu_back)
     {
         // Go back to previous menu
     currentMenu->lastOn = itemOn;
     if (currentMenu->prevMenu)
     {
         currentMenu = currentMenu->prevMenu;
         itemOn = currentMenu->lastOn;
         S_StartSound(NULL,sfx_swtchn);
     }
     return true;
     }
     // Keyboard shortcut?
     // Vanilla Doom has a weird behavior where it jumps to the scroll bars
     // when the certain keys are pressed, so emulate this.
     else if (ch != 0 || IsNullKey(key))
     {
     for (i = itemOn+1;i < currentMenu->numitems;i++)
         {
         if (currentMenu->menuitems[i].alphaKey == ch)
         {
         itemOn = i;
         S_StartSound(NULL,sfx_pstop);
         return true;
         }
         }
     for (i = 0;i <= itemOn;i++)
         {
         if (currentMenu->menuitems[i].alphaKey == ch)
         {
         itemOn = i;
         S_StartSound(NULL,sfx_pstop);
         return true;
         }
         }
     }
     return false;
 }
References menuitem_t::alphaKey, automapactive, chat_on, consoleplayer, currentMenu, event_t::data1, event_t::data2, event_t::data3, DEH_String, devparm, ev_joystick, ev_keydown, ev_mouse, ev_quit, G_ScreenShot(), gamemode, gammamsg, HU_FONTSIZE, i, I_GetTime(), I_Quit(), I_SetPalette(), IsNullKey(), itemOn, joybmenu, CrashHandler::key, KEY_BACKSPACE, KEY_ENTER, KEY_ESCAPE, key_menu_abort, key_menu_activate, key_menu_back, key_menu_confirm, key_menu_decscreen, key_menu_detail, key_menu_down, key_menu_endgame, key_menu_forward, key_menu_gamma, key_menu_help, key_menu_incscreen, key_menu_left, key_menu_load, key_menu_messages, key_menu_qload, key_menu_qsave, key_menu_quit, key_menu_right, key_menu_save, key_menu_screenshot, key_menu_up, key_menu_volume, menu_s::lastOn, M_ChangeDetail(), M_ChangeMessages(), M_ClearMenus(), M_DoSave(), M_EndGame(), M_LoadGame(), M_QuickLoad(), M_QuickSave(), M_QuitDOOM(), M_QuitResponse(), M_SaveGame(), M_SizeDisplay(), M_StartControlPanel(), M_StringCopy(), M_StringWidth(), menuactive, menu_s::menuitems, player_s::message, messageLastMenuActive, messageNeedsInput, messageRoutine, messageToPrint, mousex, mousey, NULL, menu_s::numitems, players, menu_s::prevMenu, PU_CACHE, ReadDef1, ReadDef2, retail, menuitem_t::routine, S_StartSound(), saveCharIndex, savegamestrings, saveOldString, saveSlot, saveStringEnter, SAVESTRINGSIZE, sfx_pistol, sfx_pstop, sfx_stnmov, sfx_swtchn, sfx_swtchx, sfx_vol, SoundDef, menuitem_t::status, testcontrols, toupper, event_t::type, usegamma, vanilla_keyboard_mapping, and W_CacheLumpName().
Referenced by D_ProcessEvents().
M_StartControlPanel()
void M_StartControlPanel (void)
Definition at line 1899 of file m_menu.c.
 {
     // intro might call this repeatedly
     if (menuactive)
     return;
     menuactive = 1;
     currentMenu = &MainDef;         // JDC
     itemOn = currentMenu->lastOn;   // JDC
 }
References currentMenu, itemOn, menu_s::lastOn, MainDef, and menuactive.
Referenced by G_Responder(), M_QuickSave(), and M_Responder().
M_Ticker()
void M_Ticker (void)
Definition at line 2064 of file m_menu.c.
 {
     if (--skullAnimCounter <= 0)
     {
     whichSkull ^= 1;
     skullAnimCounter = 8;
     }
 }
References skullAnimCounter, and whichSkull.
Variable Documentation
detailLevel
int detailLevel extern
Definition at line 77 of file m_menu.c.
Referenced by D_BindVariables(), M_ChangeDetail(), M_DrawOptions(), M_SizeDisplay(), and R_Init().
screenblocks
int screenblocks extern
Definition at line 78 of file m_menu.c.
Referenced by D_BindVariables(), M_ChangeDetail(), M_Init(), M_SizeDisplay(), and R_Init().