Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/sha1.h File Reference
sha1.h File Reference
#include "doomtype.h"
Data Structures
struct sha1_context_s
Typedefs
typedef struct sha1_context_s sha1_context_t
typedef byte sha1_digest_t[20]
Functions
void SHA1_Init (sha1_context_t *context)
void SHA1_Update (sha1_context_t *context, byte *buf, size_t len)
void SHA1_Final (sha1_digest_t digest, sha1_context_t *context)
void SHA1_UpdateInt32 (sha1_context_t *context, unsigned int val)
void SHA1_UpdateString (sha1_context_t *context, char *str)
Data Structure Documentation
sha1_context_s
struct sha1_context_s
Definition at line 26 of file sha1.h.
Data Fields
byte buf[64]
int count
uint32_t h0
uint32_t h1
uint32_t h2
uint32_t h3
uint32_t h4
uint32_t nblocks
Typedef Documentation
sha1_context_t
typedef struct sha1_context_s sha1_context_t
Definition at line 1 of file sha1.h.
sha1_digest_t
typedef byte sha1_digest_t[20]
Definition at line 24 of file sha1.h.
Function Documentation
SHA1_Final()
void SHA1_Final (sha1_digest_t digest, sha1_context_t * context)
Definition at line 238 of file sha1.c.
 {
     uint32_t t, msb, lsb;
     byte *p;
     SHA1_Update(hd, NULL, 0); /* flush */;
     t = hd->nblocks;
     /* multiply by 64 to make a byte count */
     lsb = t << 6;
     msb = t >> 26;
     /* add the count */
     t = lsb;
     if ((lsb += hd->count) < t)
     msb++;
     /* multiply by 8 to make a bit count */
     t = lsb;
     lsb <<= 3;
     msb <<= 3;
     msb |= t >> 29;
     if (hd->count < 56)
     {
         /* enough room */
     hd->buf[hd->count++] = 0x80; /* pad */
     while (hd->count < 56)
         hd->buf[hd->count++] = 0;  /* pad */
     }
     else
     {
         /* need one extra block */
     hd->buf[hd->count++] = 0x80; /* pad character */
     while (hd->count < 64)
         hd->buf[hd->count++] = 0;
     SHA1_Update(hd, NULL, 0);  /* flush */;
     memset(hd->buf, 0, 56 ); /* fill next block with zeroes */
     }
     /* append the 64 bit count */
     hd->buf[56] = msb >> 24;
     hd->buf[57] = msb >> 16;
     hd->buf[58] = msb >>  8;
     hd->buf[59] = msb      ;
     hd->buf[60] = lsb >> 24;
     hd->buf[61] = lsb >> 16;
     hd->buf[62] = lsb >>  8;
     hd->buf[63] = lsb      ;
     Transform(hd, hd->buf);
     p = hd->buf;
 #ifdef SYS_BIG_ENDIAN
 #define X(a) do { *(uint32_t*)p = hd->h##a ; p += 4; } while(0)
 #else /* little endian */
 #define X(a) do { *p++ = hd->h##a >> 24; *p++ = hd->h##a >> 16;  \
               *p++ = hd->h##a >> 8; *p++ = hd->h##a; } while(0)
 #endif
     X(0);
     X(1);
     X(2);
     X(3);
     X(4);
 #undef X
     memcpy(digest, hd->buf, sizeof(sha1_digest_t));
 }
References sha1_context_s::buf, sha1_context_s::count, memcpy(), memset(), sha1_context_s::nblocks, NULL, p, SHA1_Update(), t, Transform(), and X.
Referenced by W_Checksum().
SHA1_Init()
void SHA1_Init (sha1_context_t * context)
Definition at line 40 of file sha1.c.
 {
     hd->h0 = 0x67452301;
     hd->h1 = 0xefcdab89;
     hd->h2 = 0x98badcfe;
     hd->h3 = 0x10325476;
     hd->h4 = 0xc3d2e1f0;
     hd->nblocks = 0;
     hd->count = 0;
 }
References sha1_context_s::count, sha1_context_s::h0, sha1_context_s::h1, sha1_context_s::h2, sha1_context_s::h3, sha1_context_s::h4, and sha1_context_s::nblocks.
Referenced by W_Checksum().
SHA1_Update()
void SHA1_Update (sha1_context_t * context, byte * buf, size_t len)
Definition at line 198 of file sha1.c.
 {
     if (hd->count == 64)
     {
         /* flush the buffer */
     Transform(hd, hd->buf);
     hd->count = 0;
     hd->nblocks++;
     }
     if (!inbuf)
     return;
     if (hd->count)
     {
     for (; inlen && hd->count < 64; inlen--)
         hd->buf[hd->count++] = *inbuf++;
     SHA1_Update(hd, NULL, 0);
     if (!inlen)
         return;
     }
     while (inlen >= 64)
     {
     Transform(hd, inbuf);
     hd->count = 0;
     hd->nblocks++;
     inlen -= 64;
     inbuf += 64;
     }
     for (; inlen && hd->count < 64; inlen--)
     hd->buf[hd->count++] = *inbuf++;
 }
References sha1_context_s::buf, sha1_context_s::count, inbuf, sha1_context_s::nblocks, NULL, and Transform().
Referenced by SHA1_Final(), SHA1_UpdateInt32(), and SHA1_UpdateString().
SHA1_UpdateInt32()
void SHA1_UpdateInt32 (sha1_context_t * context, unsigned int val)
Definition at line 303 of file sha1.c.
 {
     byte buf[4];
     buf[0] = (val >> 24) & 0xff;
     buf[1] = (val >> 16) & 0xff;
     buf[2] = (val >> 8) & 0xff;
     buf[3] = val & 0xff;
     SHA1_Update(context, buf, 4);
 }
References buf, context, SHA1_Update(), and val.
Referenced by ChecksumAddLump().
SHA1_UpdateString()
void SHA1_UpdateString (sha1_context_t * context, char * str)
Definition at line 315 of file sha1.c.
 {
     SHA1_Update(context, (byte *) str, strlen(str) + 1);
 }
References context, SHA1_Update(), str, and strlen().
Referenced by ChecksumAddLump().