Fennix Userspace: Userspace/apps/base/busybox/networking/tls_pstm.c File Reference
tls_pstm.c File Reference
#include "tls.h"
Macros
#define pstm_mul_2d(a, b, c) (pstm_mul_2d(a, b, c), PSTM_OKAY)
#define pstm_init_size(pool, a, size) pstm_init_size(a, size)
#define pstm_init_size(pool, a, size) (pstm_init_size(a, size), PSTM_OKAY)
#define pstm_init(pool, a) pstm_init(a)
#define pstm_init(pool, a) (pstm_init(a), PSTM_OKAY)
#define pstm_grow(a, size) (pstm_grow(a, size), PSTM_OKAY)
#define pstm_copy(a, b) (pstm_copy(a, b), PSTM_OKAY)
#define pstm_lshd(a, b) (pstm_lshd(a, b), PSTM_OKAY)
#define pstm_mul_2d(a, b, c) (pstm_mul_2d(a, b, c), PSTM_OKAY)
#define pstm_mod_2d(a, b, c) (pstm_mod_2d(a, b, c), PSTM_OKAY)
#define pstm_mul_d(a, b, c) (pstm_mul_d(a, b, c), PSTM_OKAY)
#define pstm_div_2d(pool, a, b, c, d) pstm_div_2d(a, b, c, d)
#define pstm_div_2d(pool, a, b, c, d) (pstm_div_2d(a, b, c, d), PSTM_OKAY)
#define pstm_init_copy(pool, a, b, toSqr) pstm_init_copy(a, b, toSqr)
#define pstm_init_copy(pool, a, b, toSqr) (pstm_init_copy(a, b, toSqr), PSTM_OKAY)
Functions
static int32 pstm_mul_2d (pstm_int *a, int b, pstm_int *c)
int32 FAST_FUNC pstm_init_size (psPool_t *pool, pstm_int *a, uint32 size)
static int32 pstm_init (psPool_t *pool, pstm_int *a)
int32 FAST_FUNC pstm_grow (pstm_int *a, int size)
int32 pstm_copy (pstm_int *a, pstm_int *b)
void FAST_FUNC pstm_clamp (pstm_int *a)
void FAST_FUNC pstm_clear (pstm_int *a)
static void pstm_zero (pstm_int *a)
int32 FAST_FUNC pstm_cmp_mag (pstm_int *a, pstm_int *b)
int32 FAST_FUNC pstm_cmp (pstm_int *a, pstm_int *b)
int32 FAST_FUNC pstm_init_for_read_unsigned_bin (psPool_t *pool, pstm_int *a, uint32 len)
int32 FAST_FUNC pstm_read_unsigned_bin (pstm_int *a, unsigned char *b, int32 c)
static int pstm_count_bits (pstm_int *a)
int32 FAST_FUNC pstm_unsigned_bin_size (pstm_int *a)
static void pstm_set (pstm_int *a, pstm_digit b)
static void pstm_rshd (pstm_int *a, int x)
static int32 pstm_lshd (pstm_int *a, int b)
static int32 pstm_2expt (pstm_int *a, int b)
int32 FAST_FUNC pstm_mul_2 (pstm_int *a, pstm_int *b)
int32 FAST_FUNC s_pstm_sub (pstm_int *a, pstm_int *b, pstm_int *c)
static int32 s_pstm_add (pstm_int *a, pstm_int *b, pstm_int *c)
int32 FAST_FUNC pstm_sub (pstm_int *a, pstm_int *b, pstm_int *c)
static int32 pstm_montgomery_setup (pstm_int *a, pstm_digit *rho)
static int32 pstm_montgomery_calc_normalization (pstm_int *a, pstm_int *b)
static int32 pstm_mod_2d (pstm_int *a, int b, pstm_int *c)
static int32 pstm_mul_d (pstm_int *a, pstm_digit b, pstm_int *c)
static int32 pstm_div_2d (psPool_t *pool, pstm_int *a, int b, pstm_int *c, pstm_int *d)
static int32 pstm_init_copy (psPool_t *pool, pstm_int *a, pstm_int *b, int toSqr)
static int32 pstm_div (psPool_t *pool, pstm_int *a, pstm_int *b, pstm_int *c, pstm_int *d)
static void pstm_exch (pstm_int *a, pstm_int *b)
static int32 pstm_mod (psPool_t *pool, pstm_int *a, pstm_int *b, pstm_int *c)
int32 FAST_FUNC pstm_mulmod (psPool_t *pool, pstm_int *a, pstm_int *b, pstm_int *c, pstm_int *d)
int32 FAST_FUNC pstm_exptmod (psPool_t *pool, pstm_int *G, pstm_int *X, pstm_int *P, pstm_int *Y)
int32 FAST_FUNC pstm_add (pstm_int *a, pstm_int *b, pstm_int *c)
static void pstm_reverse (unsigned char *s, int len)
int32 FAST_FUNC pstm_to_unsigned_bin (psPool_t *pool, pstm_int *a, unsigned char *b)
Macro Definition Documentation
pstm_copy
#define pstm_copy (a, b) (pstm_copy(a, b), PSTM_OKAY)
Definition at line 213 of file tls_pstm.c.
pstm_div_2d [1/2]
#define pstm_div_2d (pool, a, b, c, d) pstm_div_2d(a, b, c, d)
Definition at line 1148 of file tls_pstm.c.
pstm_div_2d [2/2]
#define pstm_div_2d (pool, a, b, c, d) (pstm_div_2d(a, b, c, d), PSTM_OKAY)
Definition at line 1148 of file tls_pstm.c.
pstm_grow
#define pstm_grow (a, size) (pstm_grow(a, size), PSTM_OKAY)
Definition at line 158 of file tls_pstm.c.
pstm_init [1/2]
#define pstm_init (pool, a) pstm_init(a)
Definition at line 120 of file tls_pstm.c.
pstm_init [2/2]
#define pstm_init (pool, a) (pstm_init(a), PSTM_OKAY)
Definition at line 120 of file tls_pstm.c.
pstm_init_copy [1/2]
#define pstm_init_copy (pool, a, b, toSqr) pstm_init_copy(a, b, toSqr)
Definition at line 1233 of file tls_pstm.c.
pstm_init_copy [2/2]
#define pstm_init_copy (pool, a, b, toSqr) (pstm_init_copy(a, b, toSqr), PSTM_OKAY)
Definition at line 1233 of file tls_pstm.c.
pstm_init_size [1/2]
#define pstm_init_size (pool, a, size) pstm_init_size(a, size)
Definition at line 84 of file tls_pstm.c.
pstm_init_size [2/2]
#define pstm_init_size (pool, a, size) (pstm_init_size(a, size), PSTM_OKAY)
Definition at line 84 of file tls_pstm.c.
pstm_lshd
#define pstm_lshd (a, b) (pstm_lshd(a, b), PSTM_OKAY)
Definition at line 599 of file tls_pstm.c.
pstm_mod_2d
#define pstm_mod_2d (a, b, c) (pstm_mod_2d(a, b, c), PSTM_OKAY)
Definition at line 1019 of file tls_pstm.c.
pstm_mul_2d [1/2]
#define pstm_mul_2d (a, b, c) (pstm_mul_2d(a, b, c), PSTM_OKAY)
Definition at line 982 of file tls_pstm.c.
pstm_mul_2d [2/2]
#define pstm_mul_2d (a, b, c) (pstm_mul_2d(a, b, c), PSTM_OKAY)
Definition at line 982 of file tls_pstm.c.
pstm_mul_d
#define pstm_mul_d (a, b, c) (pstm_mul_d(a, b, c), PSTM_OKAY)
Definition at line 1057 of file tls_pstm.c.
Function Documentation
pstm_2expt()
static int32 pstm_2expt (pstm_int * a, int b) static
Definition at line 605 of file tls_pstm.c.
 {
     int     z; //bbox: was int16
    /* zero a as per default */
     pstm_zero (a);
     if (b < 0) {
         return PSTM_OKAY;
     }
     z = b / DIGIT_BIT;
     if (z >= PSTM_MAX_SIZE) {
         return PS_LIMIT_FAIL;
     }
     /* set the used count of where the bit will go */
     a->used = z + 1;
     if (a->used > a->alloc) {
         if (pstm_grow(a, a->used) != PSTM_OKAY) {
             return PS_MEM_FAIL;
         }
     }
     /* put the single bit in its place */
     a->dp[z] = ((pstm_digit)1) << (b % DIGIT_BIT);
     return PSTM_OKAY;
 }
References pstm_int::alloc, DIGIT_BIT, pstm_int::dp, PS_LIMIT_FAIL, PS_MEM_FAIL, pstm_grow, PSTM_MAX_SIZE, PSTM_OKAY, pstm_zero(), and pstm_int::used.
Referenced by pstm_montgomery_calc_normalization().
pstm_add()
int32 FAST_FUNC pstm_add (pstm_int * a, pstm_int * b, pstm_int * c)
Definition at line 1844 of file tls_pstm.c.
 {
     int32   res;
     int sa, sb; //bbox: was int16
     /* get sign of both inputs */
     sa = a->sign;
     sb = b->sign;
     /* handle two cases, not four */
     if (sa == sb) {
         /* both positive or both negative, add their mags, copy the sign */
         c->sign = sa;
         if ((res = s_pstm_add (a, b, c)) != PSTM_OKAY) {
             return res;
         }
     } else {
 /*
         one positive, the other negative
         subtract the one with the greater magnitude from the one of the lesser
         magnitude. The result gets the sign of the one with the greater mag.
  */
         if (pstm_cmp_mag (a, b) == PSTM_LT) {
             c->sign = sb;
             if ((res = s_pstm_sub (b, a, c)) != PSTM_OKAY) {
                 return res;
             }
         } else {
             c->sign = sa;
             if ((res = s_pstm_sub (a, b, c)) != PSTM_OKAY) {
                 return res;
             }
         }
     }
     return PS_SUCCESS;
 }
References c, PS_SUCCESS, pstm_cmp_mag(), PSTM_LT, PSTM_OKAY, s_pstm_add(), s_pstm_sub(), and pstm_int::sign.
Referenced by psRsaCrypt(), pstm_div(), and pstm_mod().
pstm_clamp()
void FAST_FUNC pstm_clamp (pstm_int * a)
Definition at line 223 of file tls_pstm.c.
 {
 /*  decrease used while the most significant digit is zero. */
     while (a->used > 0 && a->dp[a->used - 1] == 0) {
         --(a->used);
     }
 /*  reset the sign flag if used == 0 */
     if (a->used == 0) {
         a->sign = PSTM_ZPOS;
     }
 }
References pstm_int::dp, PSTM_ZPOS, pstm_int::sign, and pstm_int::used.
Referenced by pstm_div(), pstm_div_2d(), pstm_mod_2d(), pstm_montgomery_reduce(), pstm_mul_2d(), pstm_mul_comba_gen(), pstm_mul_d(), pstm_rshd(), pstm_sqr_comba_gen(), s_pstm_add(), and s_pstm_sub().
pstm_clear()
void FAST_FUNC pstm_clear (pstm_int * a)
Definition at line 239 of file tls_pstm.c.
 {
     int32       i;
 /*
     only do anything if a hasn't been freed previously
  */
     if (a != NULL && a->dp != NULL) {
 /*
         first zero the digits
  */
         for (i = 0; i < a->used; i++) {
             a->dp[i] = 0;
         }
         psFree (a->dp, a->pool);
 /*
         reset members to make debugging easier
  */
         a->dp       = NULL;
         a->alloc    = a->used = 0;
         a->sign     = PSTM_ZPOS;
     }
 }
References pstm_int::alloc, pstm_int::dp, i, NULL, psFree, PSTM_ZPOS, pstm_int::sign, and pstm_int::used.
Referenced by psRsaCrypt(), psRsaKey_clear(), pstm_div(), pstm_div_2d(), pstm_exptmod(), pstm_mod(), pstm_mulmod(), and pstm_to_unsigned_bin().
pstm_cmp()
int32 FAST_FUNC pstm_cmp (pstm_int * a, pstm_int * b)
Definition at line 357 of file tls_pstm.c.
 {
 /*
     compare based on sign
  */
     if (a->sign != b->sign) {
         if (a->sign == PSTM_NEG) {
             return PSTM_LT;
         } else {
             return PSTM_GT;
         }
     }
 /*
     compare digits
  */
     if (a->sign == PSTM_NEG) {
         /* if negative compare opposite direction */
         return pstm_cmp_mag(b, a);
     } else {
         return pstm_cmp_mag(a, b);
     }
 }
References pstm_cmp_mag(), PSTM_GT, PSTM_LT, PSTM_NEG, and pstm_int::sign.
Referenced by psRsaCrypt(), and pstm_div().
pstm_cmp_mag()
int32 FAST_FUNC pstm_cmp_mag (pstm_int * a, pstm_int * b)
Definition at line 317 of file tls_pstm.c.
 {
     int     n; //bbox: was int16
     pstm_digit  *tmpa, *tmpb;
 /*
     compare based on # of non-zero digits
  */
     if (a->used > b->used) {
         return PSTM_GT;
     }
     if (a->used < b->used) {
         return PSTM_LT;
     }
     /* alias for a */
     tmpa = a->dp + (a->used - 1);
     /* alias for b */
     tmpb = b->dp + (a->used - 1);
 /*
     compare based on digits
  */
     for (n = 0; n < a->used; ++n, --tmpa, --tmpb) {
         if (*tmpa > *tmpb) {
             return PSTM_GT;
         }
         if (*tmpa < *tmpb) {
             return PSTM_LT;
         }
     }
     return PSTM_EQ;
 }
References pstm_int::dp, n, PSTM_EQ, PSTM_GT, PSTM_LT, and pstm_int::used.
Referenced by pstm_add(), pstm_cmp(), pstm_div(), pstm_exptmod(), pstm_montgomery_calc_normalization(), pstm_montgomery_reduce(), and pstm_sub().
pstm_copy()
int32 pstm_copy (pstm_int * a, pstm_int * b)
Definition at line 165 of file tls_pstm.c.
 {
     int32   res, n;
 /*
     If dst == src do nothing
  */
     if (a == b) {
         return PSTM_OKAY;
     }
 /*
     Grow dest
  */
     if (b->alloc < a->used) {
         if ((res = pstm_grow (b, a->used)) != PSTM_OKAY) {
             return res;
         }
     }
 /*
     Zero b and copy the parameters over
  */
     {
         register pstm_digit *tmpa, *tmpb;
         /* pointer aliases */
         /* source */
         tmpa = a->dp;
         /* destination */
         tmpb = b->dp;
         /* copy all the digits */
         for (n = 0; n < a->used; n++) {
             *tmpb++ = *tmpa++;
         }
         /* clear high digits */
         for (; n < b->used; n++) {
             *tmpb++ = 0;
         }
     }
 /*
     copy used count and sign
  */
     b->used = a->used;
     b->sign = a->sign;
     return PSTM_OKAY;
 }
References pstm_int::alloc, pstm_int::dp, n, pstm_grow, PSTM_OKAY, pstm_int::sign, and pstm_int::used.
pstm_count_bits()
static int pstm_count_bits (pstm_int * a) static
Definition at line 481 of file tls_pstm.c.
 {
     int     r; //bbox: was int16
     pstm_digit q;
     if (a->used == 0) {
         return 0;
     }
     /* get number of digits and add that */
     r = (a->used - 1) * DIGIT_BIT;
     /* take the last digit and count the bits in it */
     q = a->dp[a->used - 1];
     while (q > ((pstm_digit) 0)) {
         ++r;
         q >>= ((pstm_digit) 1);
     }
     return r;
 }
References DIGIT_BIT, pstm_int::dp, and pstm_int::used.
Referenced by pstm_div(), pstm_exptmod(), pstm_montgomery_calc_normalization(), and pstm_unsigned_bin_size().
pstm_div()
static int32 pstm_div (psPool_t * pool, pstm_int * a, pstm_int * b, pstm_int * c, pstm_int * d) static
Definition at line 1317 of file tls_pstm.c.
 {
     pstm_int    q, x, y, t1, t2;
     int32       res;
     int     n, t, i, norm, neg; //bbox: was int16
     /* is divisor zero ? */
     if (pstm_iszero (b) == 1) {
         return PS_LIMIT_FAIL;
     }
     /* if a < b then q=0, r = a */
     if (pstm_cmp_mag (a, b) == PSTM_LT) {
         if (d != NULL) {
             if (pstm_copy(a, d) != PSTM_OKAY) {
                 return PS_MEM_FAIL;
             }
         }
         if (c != NULL) {
             pstm_zero (c);
         }
         return PSTM_OKAY;
     }
 /*
     Smart-size inits
 */
     if ((res = pstm_init_size(pool, &t1, a->alloc)) != PSTM_OKAY) {
         return res;
     }
     if ((res = pstm_init_size(pool, &t2, 3)) != PSTM_OKAY) {
         goto LBL_T1;
     }
     if ((res = pstm_init_copy(pool, &x, a, 0)) != PSTM_OKAY) {
         goto LBL_T2;
     }
 /*
     Used to be an init_copy on b but pstm_grow was always hit with triple size
 */
     if ((res = pstm_init_size(pool, &y, b->used * 3)) != PSTM_OKAY) {
         goto LBL_X;
     }
     if ((res = pstm_copy(b, &y)) != PSTM_OKAY) {
         goto LBL_Y;
     }
     /* fix the sign */
     neg = (a->sign == b->sign) ? PSTM_ZPOS : PSTM_NEG;
     x.sign = y.sign = PSTM_ZPOS;
     /* normalize both x and y, ensure that y >= b/2, [b == 2**DIGIT_BIT] */
     norm = pstm_count_bits(&y) % DIGIT_BIT;
     if (norm < (int32)(DIGIT_BIT-1)) {
         norm = (DIGIT_BIT-1) - norm;
         if ((res = pstm_mul_2d(&x, norm, &x)) != PSTM_OKAY) {
             goto LBL_Y;
         }
         if ((res = pstm_mul_2d(&y, norm, &y)) != PSTM_OKAY) {
             goto LBL_Y;
         }
     } else {
         norm = 0;
     }
     /* note hac does 0 based, so if used==5 then its 0,1,2,3,4, e.g. use 4 */
     n = x.used - 1;
     t = y.used - 1;
     if ((res = pstm_init_size(pool, &q, n - t + 1)) != PSTM_OKAY) {
         goto LBL_Y;
     }
     q.used = n - t + 1;
     /* while (x >= y*b**n-t) do { q[n-t] += 1; x -= y*b**{n-t} } */
     if ((res = pstm_lshd(&y, n - t)) != PSTM_OKAY) { /* y = y*b**{n-t} */
         goto LBL_Q;
     }
     while (pstm_cmp (&x, &y) != PSTM_LT) {
         ++(q.dp[n - t]);
         if ((res = pstm_sub(&x, &y, &x)) != PSTM_OKAY) {
             goto LBL_Q;
         }
     }
     /* reset y by shifting it back down */
     pstm_rshd (&y, n - t);
     /* step 3. for i from n down to (t + 1) */
     for (i = n; i >= (t + 1); i--) {
         if (i > x.used) {
             continue;
         }
         /* step 3.1 if xi == yt then set q{i-t-1} to b-1,
          * otherwise set q{i-t-1} to (xi*b + x{i-1})/yt */
         if (x.dp[i] == y.dp[t]) {
             q.dp[i - t - 1] = (pstm_digit)((((pstm_word)1) << DIGIT_BIT) - 1);
         } else {
             pstm_word tmp;
             tmp = ((pstm_word) x.dp[i]) << ((pstm_word) DIGIT_BIT);
             tmp |= ((pstm_word) x.dp[i - 1]);
 #if defined(USE_MATRIX_DIV64) && defined(PSTM_32BIT)
             psDiv64(&tmp, y.dp[t]);
 #elif defined(USE_MATRIX_DIV128) && defined(PSTM_64BIT)
             psDiv128(&tmp, y.dp[t]);
 #else
             tmp /= ((pstm_word) y.dp[t]);
 #endif /* USE_MATRIX_DIV64 */
             q.dp[i - t - 1] = (pstm_digit) (tmp);
         }
         /* while (q{i-t-1} * (yt * b + y{t-1})) >
             xi * b**2 + xi-1 * b + xi-2
             do q{i-t-1} -= 1;
         */
         q.dp[i - t - 1] = (q.dp[i - t - 1] + 1);
         do {
             q.dp[i - t - 1] = (q.dp[i - t - 1] - 1);
             /* find left hand */
             pstm_zero (&t1);
             t1.dp[0] = (t - 1 < 0) ? 0 : y.dp[t - 1];
             t1.dp[1] = y.dp[t];
             t1.used = 2;
             if ((res = pstm_mul_d (&t1, q.dp[i - t - 1], &t1)) != PSTM_OKAY) {
                 goto LBL_Q;
             }
             /* find right hand */
             t2.dp[0] = (i - 2 < 0) ? 0 : x.dp[i - 2];
             t2.dp[1] = (i - 1 < 0) ? 0 : x.dp[i - 1];
             t2.dp[2] = x.dp[i];
             t2.used = 3;
         } while (pstm_cmp_mag(&t1, &t2) == PSTM_GT);
         /* step 3.3 x = x - q{i-t-1} * y * b**{i-t-1} */
         if ((res = pstm_mul_d(&y, q.dp[i - t - 1], &t1)) != PSTM_OKAY) {
             goto LBL_Q;
         }
         if ((res = pstm_lshd(&t1, i - t - 1)) != PSTM_OKAY) {
             goto LBL_Q;
         }
         if ((res = pstm_sub(&x, &t1, &x)) != PSTM_OKAY) {
             goto LBL_Q;
         }
         /* if x < 0 then { x = x + y*b**{i-t-1}; q{i-t-1} -= 1; } */
         if (x.sign == PSTM_NEG) {
             if ((res = pstm_copy(&y, &t1)) != PSTM_OKAY) {
                 goto LBL_Q;
             }
             if ((res = pstm_lshd (&t1, i - t - 1)) != PSTM_OKAY) {
                 goto LBL_Q;
             }
             if ((res = pstm_add (&x, &t1, &x)) != PSTM_OKAY) {
                 goto LBL_Q;
             }
             q.dp[i - t - 1] = q.dp[i - t - 1] - 1;
         }
     }
 /*
     now q is the quotient and x is the remainder (which we have to normalize)
 */
     /* get sign before writing to c */
     x.sign = x.used == 0 ? PSTM_ZPOS : a->sign;
     if (c != NULL) {
         pstm_clamp (&q);
         if (pstm_copy (&q, c) != PSTM_OKAY) {
             res = PS_MEM_FAIL;
             goto LBL_Q;
         }
         c->sign = neg;
     }
     if (d != NULL) {
         if ((res = pstm_div_2d (pool, &x, norm, &x, NULL)) != PSTM_OKAY) {
             goto LBL_Q;
         }
 /*
         the following is a kludge, essentially we were seeing the right
         remainder but with excess digits that should have been zero
  */
         for (i = b->used; i < x.used; i++) {
             x.dp[i] = 0;
         }
         pstm_clamp(&x);
         if (pstm_copy (&x, d) != PSTM_OKAY) {
             res = PS_MEM_FAIL;
             goto LBL_Q;
         }
     }
     res = PSTM_OKAY;
 LBL_Q:pstm_clear (&q);
 LBL_Y:pstm_clear (&y);
 LBL_X:pstm_clear (&x);
 LBL_T2:pstm_clear (&t2);
 LBL_T1:pstm_clear (&t1);
     return res;
 }
References pstm_int::alloc, c, DIGIT_BIT, pstm_int::dp, i, if(), n, NULL, PS_LIMIT_FAIL, PS_MEM_FAIL, pstm_add(), pstm_clamp(), pstm_clear(), pstm_cmp(), pstm_cmp_mag(), pstm_copy, pstm_count_bits(), pstm_div_2d, PSTM_GT, pstm_init_copy, pstm_init_size, pstm_iszero, pstm_lshd, PSTM_LT, pstm_mul_2d, pstm_mul_d, PSTM_NEG, PSTM_OKAY, pstm_rshd(), pstm_sub(), pstm_zero(), PSTM_ZPOS, pstm_int::sign, t, t1, t2, pstm_int::used, x, and y.
Referenced by pstm_mod().
pstm_div_2d()
static int32 pstm_div_2d (psPool_t * pool, pstm_int * a, int b, pstm_int * c, pstm_int * d) static
Definition at line 1066 of file tls_pstm.c.
 {
     pstm_digit  D, r, rr;
     int32       res;
     int     x; //bbox: was int16
     pstm_int    t;
     /* if the shift count is <= 0 then we do no work */
     if (b <= 0) {
         if (pstm_copy (a, c) != PSTM_OKAY) {
             return PS_MEM_FAIL;
         }
         if (d != NULL) {
             pstm_zero (d);
         }
         return PSTM_OKAY;
     }
     /* get the remainder */
     if (d != NULL) {
         if (pstm_init(pool, &t) != PSTM_OKAY) {
             return PS_MEM_FAIL;
         }
         if (pstm_mod_2d (a, b, &t) != PSTM_OKAY) {
             res = PS_MEM_FAIL;
             goto LBL_DONE;
         }
     }
     /* copy */
     if (pstm_copy(a, c) != PSTM_OKAY) {
         res = PS_MEM_FAIL;
         goto LBL_DONE;
     }
     /* shift by as many digits in the bit count */
     if (b >= (int32)DIGIT_BIT) {
         pstm_rshd (c, b / DIGIT_BIT);
     }
     /* shift any bit count < DIGIT_BIT */
     D = (pstm_digit) (b % DIGIT_BIT);
     if (D != 0) {
         register pstm_digit *tmpc, mask, shift;
         /* mask */
         mask = (((pstm_digit)1) << D) - 1;
         /* shift for lsb */
         shift = DIGIT_BIT - D;
         /* alias */
         tmpc = c->dp + (c->used - 1);
         /* carry */
         r = 0;
         for (x = c->used - 1; x >= 0; x--) {
             /* get the lower  bits of this word in a temp */
             rr = *tmpc & mask;
             /* shift the current word and mix in the carry bits from previous */
             *tmpc = (*tmpc >> D) | (r << shift);
             --tmpc;
             /* set the carry to the carry bits of the current word above */
             r = rr;
         }
     }
     pstm_clamp (c);
     res = PSTM_OKAY;
 LBL_DONE:
     if (d != NULL) {
         if (pstm_copy(&t, d) != PSTM_OKAY) {
             res = PS_MEM_FAIL;
         }
         pstm_clear(&t);
     }
     return res;
 }
References c, D, DIGIT_BIT, NULL, PS_MEM_FAIL, pstm_clamp(), pstm_clear(), pstm_copy, pstm_init, pstm_mod_2d, PSTM_OKAY, pstm_rshd(), pstm_zero(), t, and x.
pstm_exch()
static void pstm_exch (pstm_int * a, pstm_int * b) static
Definition at line 1530 of file tls_pstm.c.
 {
     pstm_int        t;
     t   = *a;
     *a  = *b;
     *b  = t;
 }
References t.
Referenced by pstm_mod().
pstm_exptmod()
int32 FAST_FUNC pstm_exptmod (psPool_t * pool, pstm_int * G, pstm_int * X, pstm_int * P, pstm_int * Y)
Definition at line 1603 of file tls_pstm.c.
 {
     pstm_int    M[32], res; /* Keep this winsize based: (1 << max_winsize) */
     pstm_digit  buf, mp;
     pstm_digit  *paD;
     int32       err, bitbuf;
     int     bitcpy, bitcnt, mode, digidx, x, y, winsize; //bbox: was int16
     uint32      paDlen;
     /* set window size from what user set as optimization */
     x = pstm_count_bits(X);
     if (x < 50) {
         winsize = 2;
     } else {
         winsize = PS_EXPTMOD_WINSIZE;
     }
     /* now setup montgomery  */
     if ((err = pstm_montgomery_setup (P, &mp)) != PSTM_OKAY) {
         return err;
     }
     /* setup result */
     if ((err = pstm_init_size(pool, &res, (P->used * 2) + 1)) != PSTM_OKAY) {
         return err;
     }
 /*
     create M table
     The M table contains powers of the input base, e.g. M[x] = G^x mod P
     The first half of the table is not computed though except for M[0] and M[1]
  */
     /* now we need R mod m */
     if ((err = pstm_montgomery_calc_normalization (&res, P)) != PSTM_OKAY) {
         goto LBL_RES;
     }
 /*
     init M array
     init first cell
  */
     if ((err = pstm_init_size(pool, &M[1], res.used)) != PSTM_OKAY) {
         goto LBL_RES;
     }
     /* now set M[1] to G * R mod m */
     if (pstm_cmp_mag(P, G) != PSTM_GT) {
         /* G > P so we reduce it first */
         if ((err = pstm_mod(pool, G, P, &M[1])) != PSTM_OKAY) {
             goto LBL_M;
         }
     } else {
         if ((err = pstm_copy(G, &M[1])) != PSTM_OKAY) {
             goto LBL_M;
         }
     }
     if ((err = pstm_mulmod (pool, &M[1], &res, P, &M[1])) != PSTM_OKAY) {
         goto LBL_M;
     }
 /*
     Pre-allocated digit.  Used for mul, sqr, AND reduce
 */
     paDlen = ((M[1].used + 3) * 2) * sizeof(pstm_digit);
     paD = xzalloc(paDlen);//bbox
 /*
     compute the value at M[1<<(winsize-1)] by squaring M[1] (winsize-1) times
  */
     if (pstm_init_copy(pool, &M[1 << (winsize - 1)], &M[1], 1) != PSTM_OKAY) {
         err = PS_MEM_FAIL;
         goto LBL_PAD;
     }
     for (x = 0; x < (winsize - 1); x++) {
         if ((err = pstm_sqr_comba (pool, &M[1 << (winsize - 1)],
                 &M[1 << (winsize - 1)], paD, paDlen)) != PSTM_OKAY) {
             goto LBL_PAD;
         }
         if ((err = pstm_montgomery_reduce(pool, &M[1 << (winsize - 1)], P, mp,
                 paD, paDlen)) != PSTM_OKAY) {
             goto LBL_PAD;
         }
     }
 /*
     now init the second half of the array
 */
     for (x = (1<<(winsize-1)) + 1; x < (1 << winsize); x++) {
         if ((err = pstm_init_size(pool, &M[x], M[1<<(winsize-1)].alloc + 1))
                 != PSTM_OKAY) {
             for (y = 1<<(winsize-1); y < x; y++) {
                 pstm_clear(&M[y]);
             }
             goto LBL_PAD;
         }
     }
     /* create upper table */
     for (x = (1 << (winsize - 1)) + 1; x < (1 << winsize); x++) {
         if ((err = pstm_mul_comba(pool, &M[x - 1], &M[1], &M[x], paD, paDlen))
                 != PSTM_OKAY) {
             goto LBL_MARRAY;
         }
         if ((err = pstm_montgomery_reduce(pool, &M[x], P, mp, paD, paDlen)) !=
                 PSTM_OKAY) {
             goto LBL_MARRAY;
         }
     }
     /* set initial mode and bit cnt */
     mode   = 0;
     bitcnt = 1;
     buf    = 0;
     digidx = X->used - 1;
     bitcpy = 0;
     bitbuf = 0;
     for (;;) {
         /* grab next digit as required */
         if (--bitcnt == 0) {
             /* if digidx == -1 we are out of digits so break */
             if (digidx == -1) {
                 break;
             }
             /* read next digit and reset bitcnt */
             buf    = X->dp[digidx--];
             bitcnt = (int32)DIGIT_BIT;
         }
         /* grab the next msb from the exponent */
         y     = (pstm_digit)(buf >> (DIGIT_BIT - 1)) & 1;
         buf <<= (pstm_digit)1;
 /*
          If the bit is zero and mode == 0 then we ignore it.
          These represent the leading zero bits before the first 1 bit
          in the exponent.  Technically this opt is not required but it
          does lower the # of trivial squaring/reductions used
 */
         if (mode == 0 && y == 0) {
             continue;
         }
         /* if the bit is zero and mode == 1 then we square */
         if (mode == 1 && y == 0) {
             if ((err = pstm_sqr_comba(pool, &res, &res, paD, paDlen)) !=
                     PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD, paDlen))
                     != PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             continue;
         }
         /* else we add it to the window */
         bitbuf |= (y << (winsize - ++bitcpy));
         mode    = 2;
         if (bitcpy == winsize) {
             /* ok window is filled so square as required and mul square first */
             for (x = 0; x < winsize; x++) {
                 if ((err = pstm_sqr_comba(pool, &res, &res, paD, paDlen)) !=
                         PSTM_OKAY) {
                     goto LBL_MARRAY;
                 }
                 if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD,
                         paDlen)) != PSTM_OKAY) {
                     goto LBL_MARRAY;
                 }
             }
             /* then multiply */
             if ((err = pstm_mul_comba(pool, &res, &M[bitbuf], &res, paD,
                     paDlen)) != PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD, paDlen))
                     != PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             /* empty window and reset */
             bitcpy = 0;
             bitbuf = 0;
             mode   = 1;
         }
     }
     /* if bits remain then square/multiply */
     if (mode == 2 && bitcpy > 0) {
         /* square then multiply if the bit is set */
         for (x = 0; x < bitcpy; x++) {
             if ((err = pstm_sqr_comba(pool, &res, &res, paD, paDlen)) !=
                     PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD, paDlen))
                     != PSTM_OKAY) {
                 goto LBL_MARRAY;
             }
             /* get next bit of the window */
             bitbuf <<= 1;
             if ((bitbuf & (1 << winsize)) != 0) {
             /* then multiply */
                 if ((err = pstm_mul_comba(pool, &res, &M[1], &res, paD, paDlen))
                         != PSTM_OKAY) {
                     goto LBL_MARRAY;
                 }
                 if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD,
                         paDlen)) != PSTM_OKAY) {
                     goto LBL_MARRAY;
                 }
             }
         }
     }
 /*
     Fix up result if Montgomery reduction is used recall that any value in a
     Montgomery system is actually multiplied by R mod n.  So we have to reduce
     one more time to cancel out the factor of R.
 */
     if ((err = pstm_montgomery_reduce(pool, &res, P, mp, paD, paDlen)) !=
             PSTM_OKAY) {
         goto LBL_MARRAY;
     }
     /* swap res with Y */
     if ((err = pstm_copy (&res, Y)) != PSTM_OKAY) {
         goto LBL_MARRAY;
     }
     err = PSTM_OKAY;
 LBL_MARRAY:
     for (x = 1<<(winsize-1); x < (1 << winsize); x++) {
         pstm_clear(&M[x]);
     }
 LBL_PAD:psFree(paD, pool);
 LBL_M: pstm_clear(&M[1]);
 LBL_RES:pstm_clear(&res);
     return err;
 }
References buf, DIGIT_BIT, err(), G, M, P, PS_EXPTMOD_WINSIZE, PS_MEM_FAIL, psFree, pstm_clear(), pstm_cmp_mag(), pstm_copy, pstm_count_bits(), PSTM_GT, pstm_init_copy, pstm_init_size, pstm_mod(), pstm_montgomery_calc_normalization(), pstm_montgomery_reduce, pstm_montgomery_setup(), pstm_mul_comba, pstm_mulmod(), PSTM_OKAY, pstm_sqr_comba, pstm_int::used, X, x, xzalloc(), and y.
pstm_grow()
int32 FAST_FUNC pstm_grow (pstm_int * a, int size)
Definition at line 127 of file tls_pstm.c.
 {
     int         i; //bbox: was int16
     pstm_digit      *tmp;
 /*
     If the alloc size is smaller alloc more ram.
  */
     if (a->alloc < size) {
 /*
         Reallocate the array a->dp
         We store the return in a temporary variable in case the operation
         failed we don't want to overwrite the dp member of a.
 */
         tmp = xrealloc(a->dp, sizeof (pstm_digit) * size);//bbox
 /*
         reallocation succeeded so set a->dp
  */
         a->dp = tmp;
 /*
         zero excess digits
  */
         i           = a->alloc;
         a->alloc    = size;
         for (; i < a->alloc; i++) {
             a->dp[i] = 0;
         }
     }
     return PSTM_OKAY;
 }
References pstm_int::alloc, pstm_int::dp, i, PSTM_OKAY, size, and xrealloc.
pstm_init()
static int32 pstm_init (psPool_t * pool, pstm_int * a) static
Definition at line 93 of file tls_pstm.c.
 {
 //bbox
 //  int32       i;
 /*
     allocate memory required and clear it
  */
     a->dp = xzalloc(sizeof (pstm_digit) * PSTM_DEFAULT_INIT);//bbox
 /*
     set the digits to zero
  */
 //bbox
 //  for (i = 0; i < PSTM_DEFAULT_INIT; i++) {
 //      a->dp[i] = 0;
 //  }
 /*
     set the used to zero, allocated digits to the default precision and sign
     to positive
  */
 //bbox  a->pool = pool;
     a->used  = 0;
     a->alloc = PSTM_DEFAULT_INIT;
     a->sign  = PSTM_ZPOS;
     return PSTM_OKAY;
 }
References pstm_int::alloc, pstm_int::dp, PSTM_DEFAULT_INIT, PSTM_OKAY, PSTM_ZPOS, pstm_int::sign, pstm_int::used, and xzalloc().
pstm_init_copy()
static int32 pstm_init_copy (psPool_t * pool, pstm_int * a, pstm_int * b, int toSqr) static
Definition at line 1207 of file tls_pstm.c.
 {
     int x; //bbox: was int16
     int32   res;
     if (a == b) {
         return PSTM_OKAY;
     }
     x = b->alloc;
     if (toSqr) {
 /*
         Smart-size:  Increasing size of a if b->used is roughly half
         of b->alloc because usage has shown that a lot of these copies
         go on to be squared and need these extra digits
 */
         if ((b->used * 2) + 2 >= x) {
             x = (b->used * 2) + 3;
         }
     }
     if ((res = pstm_init_size(pool, a, x)) != PSTM_OKAY) {
         return res;
     }
     return pstm_copy(b, a);
 }
References pstm_int::alloc, pstm_copy, pstm_init_size, PSTM_OKAY, pstm_int::used, and x.
pstm_init_for_read_unsigned_bin()
int32 FAST_FUNC pstm_init_for_read_unsigned_bin (psPool_t * pool, pstm_int * a, uint32 len)
Definition at line 385 of file tls_pstm.c.
 {
     int32 size;
 /*
     Need to set this based on how many words max it will take to store the bin.
     The magic + 2:
         1 to round up for the remainder of this integer math
         1 for the initial carry of '1' bits that fall between DIGIT_BIT and 8
 */
     size = (((len / sizeof(pstm_digit)) * (sizeof(pstm_digit) * CHAR_BIT))
         / DIGIT_BIT) + 2;
     return pstm_init_size(pool, a, size);
 }
References CHAR_BIT, DIGIT_BIT, pstm_init_size, and size.
pstm_init_size()
int32 FAST_FUNC pstm_init_size (psPool_t * pool, pstm_int * a, uint32 size)
Definition at line 61 of file tls_pstm.c.
 {
 //bbox
 //  uint16      x;
 /*
     alloc mem
  */
     a->dp = xzalloc(sizeof (pstm_digit) * size);//bbox
 //bbox  a->pool = pool;
     a->used  = 0;
     a->alloc = size;
     a->sign  = PSTM_ZPOS;
 /*
     zero the digits
  */
 //bbox
 //  for (x = 0; x < size; x++) {
 //      a->dp[x] = 0;
 //  }
     return PSTM_OKAY;
 }
References pstm_int::alloc, pstm_int::dp, PSTM_OKAY, PSTM_ZPOS, pstm_int::sign, size, pstm_int::used, and xzalloc().
pstm_lshd()
static int32 pstm_lshd (pstm_int * a, int b) static
Definition at line 551 of file tls_pstm.c.
 {
     int x; //bbox: was int16
     int32   res;
 /*
     If its less than zero return.
  */
     if (b <= 0) {
         return PSTM_OKAY;
     }
 /*
     Grow to fit the new digits.
  */
     if (a->alloc < a->used + b) {
         if ((res = pstm_grow (a, a->used + b)) != PSTM_OKAY) {
             return res;
         }
     }
     {
         register pstm_digit *top, *bottom;
 /*
         Increment the used by the shift amount then copy upwards.
  */
         a->used += b;
         /* top */
         top = a->dp + a->used - 1;
         /* base */
         bottom = a->dp + a->used - 1 - b;
 /*
         This is implemented using a sliding window except the window goes the
         other way around.  Copying from the bottom to the top.
  */
         for (x = a->used - 1; x >= b; x--) {
             *top-- = *bottom--;
         }
         /* zero the lower digits */
         top = a->dp;
         for (x = 0; x < b; x++) {
             *top++ = 0;
         }
     }
     return PSTM_OKAY;
 }
References pstm_int::alloc, bottom, pstm_int::dp, pstm_grow, PSTM_OKAY, top, pstm_int::used, and x.
pstm_mod()
static int32 pstm_mod (psPool_t * pool, pstm_int * a, pstm_int * b, pstm_int * c) static
Definition at line 1543 of file tls_pstm.c.
 {
     pstm_int    t;
     int32       err;
 /*
     Smart-size
 */
     if ((err = pstm_init_size(pool, &t, b->alloc)) != PSTM_OKAY) {
         return err;
     }
     if ((err = pstm_div(pool, a, b, NULL, &t)) != PSTM_OKAY) {
         pstm_clear (&t);
         return err;
     }
     if (t.sign != b->sign) {
         err = pstm_add(&t, b, c);
     } else {
         pstm_exch (&t, c);
     }
     pstm_clear (&t);
     return err;
 }
References pstm_int::alloc, c, err(), NULL, pstm_add(), pstm_clear(), pstm_div(), pstm_exch(), pstm_init_size, PSTM_OKAY, pstm_int::sign, and t.
Referenced by pstm_exptmod(), and pstm_mulmod().
pstm_mod_2d()
static int32 pstm_mod_2d (pstm_int * a, int b, pstm_int * c) static
Definition at line 989 of file tls_pstm.c.
 {
     int x; //bbox: was int16
     /* zero if count less than or equal to zero */
     if (b <= 0) {
         pstm_zero(c);
         return PSTM_OKAY;
     }
     /* get copy of input */
     if (pstm_copy(a, c) != PSTM_OKAY) {
         return PS_MEM_FAIL;
     }
     /* if 2**d is larger than we just return */
     if (b >= (DIGIT_BIT * a->used)) {
         return PSTM_OKAY;
     }
     /* zero digits above the last digit of the modulus */
     for (x = (b / DIGIT_BIT) + ((b % DIGIT_BIT) == 0 ? 0 : 1); x < c->used; x++)
     {
         c->dp[x] = 0;
     }
     /* clear the digit that is not completely outside/inside the modulus */
     c->dp[b / DIGIT_BIT] &= ~((pstm_digit)0) >> (DIGIT_BIT - b);
     pstm_clamp (c);
     return PSTM_OKAY;
 }
References c, DIGIT_BIT, PS_MEM_FAIL, pstm_clamp(), pstm_copy, PSTM_OKAY, pstm_zero(), pstm_int::used, and x.
pstm_montgomery_calc_normalization()
static int32 pstm_montgomery_calc_normalization (pstm_int * a, pstm_int * b) static
Definition at line 903 of file tls_pstm.c.
 {
     int32     x;
     int bits; //bbox: was int16
     /* how many bits of last digit does b use */
     bits = pstm_count_bits (b) % DIGIT_BIT;
     if (!bits) bits = DIGIT_BIT;
     /* compute A = B^(n-1) * 2^(bits-1) */
     if (b->used > 1) {
         if ((x = pstm_2expt (a, (b->used - 1) * DIGIT_BIT + bits - 1)) !=
                 PSTM_OKAY) {
             return x;
         }
     } else {
         pstm_set(a, 1);
         bits = 1;
     }
     /* now compute C = A * B mod b */
     for (x = bits - 1; x < (int32)DIGIT_BIT; x++) {
         if (pstm_mul_2 (a, a) != PSTM_OKAY) {
             return PS_MEM_FAIL;
         }
         if (pstm_cmp_mag (a, b) != PSTM_LT) {
             if (s_pstm_sub (a, b, a) != PSTM_OKAY) {
                 return PS_MEM_FAIL;
             }
         }
     }
     return PSTM_OKAY;
 }
References DIGIT_BIT, PS_MEM_FAIL, pstm_2expt(), pstm_cmp_mag(), pstm_count_bits(), PSTM_LT, pstm_mul_2(), PSTM_OKAY, pstm_set(), s_pstm_sub(), pstm_int::used, and x.
Referenced by pstm_exptmod().
pstm_montgomery_setup()
static int32 pstm_montgomery_setup (pstm_int * a, pstm_digit * rho) static
Definition at line 867 of file tls_pstm.c.
 {
     pstm_digit x, b;
 /*
     fast inversion mod 2**k
     Based on the fact that
     XA = 1 (mod 2**n)   =>  (X(2-XA)) A = 1 (mod 2**2n)
                         =>  2*X*A - X*X*A*A = 1
                         =>  2*(1) - (1)     = 1
  */
     b = a->dp[0];
     if ((b & 1) == 0) {
         psTraceCrypto("pstm_montogomery_setup failure\n");
         return PS_ARG_FAIL;
     }
     x = (((b + 2) & 4) << 1) + b; /* here x*a==1 mod 2**4 */
     x *= 2 - b * x;               /* here x*a==1 mod 2**8 */
     x *= 2 - b * x;               /* here x*a==1 mod 2**16 */
     x *= 2 - b * x;               /* here x*a==1 mod 2**32 */
 #ifdef PSTM_64BIT
     x *= 2 - b * x;               /* here x*a==1 mod 2**64 */
 #endif
     /* rho = -1/m mod b */
     *rho = (pstm_digit)(((pstm_word) 1 << ((pstm_word) DIGIT_BIT)) -
         ((pstm_word)x));
     return PSTM_OKAY;
 }
References DIGIT_BIT, pstm_int::dp, PS_ARG_FAIL, PSTM_OKAY, psTraceCrypto, and x.
Referenced by pstm_exptmod().
pstm_mul_2()
int32 FAST_FUNC pstm_mul_2 (pstm_int * a, pstm_int * b)
Definition at line 639 of file tls_pstm.c.
 {
     int32   res;
     int x, oldused; //bbox: was int16
 /*
     grow to accomodate result
  */
     if (b->alloc < a->used + 1) {
         if ((res = pstm_grow (b, a->used + 1)) != PSTM_OKAY) {
             return res;
         }
     }
     oldused = b->used;
     b->used = a->used;
     {
         register pstm_digit r, rr, *tmpa, *tmpb;
         /* alias for source */
         tmpa = a->dp;
         /* alias for dest */
         tmpb = b->dp;
         /* carry */
         r = 0;
         for (x = 0; x < a->used; x++) {
 /*
             get what will be the *next* carry bit from the
             MSB of the current digit
 */
             rr = *tmpa >> ((pstm_digit)(DIGIT_BIT - 1));
 /*
             now shift up this digit, add in the carry [from the previous]
 */
             *tmpb++ = ((*tmpa++ << ((pstm_digit)1)) | r);
 /*
             copy the carry that would be from the source
             digit into the next iteration
 */
             r = rr;
         }
         /* new leading digit? */
         if (r != 0 && b->used != (PSTM_MAX_SIZE-1)) {
             /* add a MSB which is always 1 at this point */
             *tmpb = 1;
             ++(b->used);
         }
 /*
         now zero any excess digits on the destination that we didn't write to
 */
         tmpb = b->dp + b->used;
         for (x = b->used; x < oldused; x++) {
             *tmpb++ = 0;
         }
     }
     b->sign = a->sign;
     return PSTM_OKAY;
 }
References pstm_int::alloc, DIGIT_BIT, pstm_int::dp, pstm_grow, PSTM_MAX_SIZE, PSTM_OKAY, pstm_int::sign, pstm_int::used, and x.
Referenced by pstm_montgomery_calc_normalization().
pstm_mul_2d()
static int32 pstm_mul_2d (pstm_int * a, int b, pstm_int * c) static
Definition at line 942 of file tls_pstm.c.
 {
     pstm_digit  carry, carrytmp, shift;
     int     x; //bbox: was int16
     /* copy it */
     if (pstm_copy(a, c) != PSTM_OKAY) {
         return PS_MEM_FAIL;
     }
     /* handle whole digits */
     if (b >= DIGIT_BIT) {
         if (pstm_lshd(c, b/DIGIT_BIT) != PSTM_OKAY) {
             return PS_MEM_FAIL;
         }
     }
     b %= DIGIT_BIT;
     /* shift the digits */
     if (b != 0) {
         carry = 0;
         shift = DIGIT_BIT - b;
         for (x = 0; x < c->used; x++) {
             carrytmp = c->dp[x] >> shift;
             c->dp[x] = (c->dp[x] << b) + carry;
             carry = carrytmp;
         }
         /* store last carry if room */
         if (carry && x < PSTM_MAX_SIZE) {
             if (c->used == c->alloc) {
                 if (pstm_grow(c, c->alloc + 1) != PSTM_OKAY) {
                     return PS_MEM_FAIL;
                 }
             }
             c->dp[c->used++] = carry;
         }
     }
     pstm_clamp(c);
     return PSTM_OKAY;
 }
References c, DIGIT_BIT, PS_MEM_FAIL, pstm_clamp(), pstm_copy, pstm_grow, pstm_lshd, PSTM_MAX_SIZE, PSTM_OKAY, and x.
pstm_mul_d()
static int32 pstm_mul_d (pstm_int * a, pstm_digit b, pstm_int * c) static
Definition at line 1027 of file tls_pstm.c.
 {
     pstm_word   w;
     int32       res;
     int     x, oldused; //bbox: was int16
     if (c->alloc < a->used + 1) {
         if ((res = pstm_grow (c, a->used + 1)) != PSTM_OKAY) {
             return res;
         }
     }
     oldused = c->used;
     c->used = a->used;
     c->sign = a->sign;
     w       = 0;
     for (x = 0; x < a->used; x++) {
         w         = ((pstm_word)a->dp[x]) * ((pstm_word)b) + w;
         c->dp[x]  = (pstm_digit)w;
         w         = w >> DIGIT_BIT;
     }
     if (w != 0 && (a->used != PSTM_MAX_SIZE)) {
         c->dp[c->used++] = (pstm_digit)w;
         ++x;
     }
     for (; x < oldused; x++) {
         c->dp[x] = 0;
     }
     pstm_clamp(c);
     return PSTM_OKAY;
 }
References c, DIGIT_BIT, pstm_int::dp, pstm_clamp(), pstm_grow, PSTM_MAX_SIZE, PSTM_OKAY, pstm_int::sign, pstm_int::used, w, and x.
pstm_mulmod()
int32 FAST_FUNC pstm_mulmod (psPool_t * pool, pstm_int * a, pstm_int * b, pstm_int * c, pstm_int * d)
Definition at line 1570 of file tls_pstm.c.
 {
     int32       res;
     int     size; //bbox: was int16
     pstm_int    tmp;
 /*
     Smart-size pstm_inits.  d is an output that is influenced by this local 't'
     so don't shrink 'd' if it wants to becuase this will lead to an pstm_grow
     in RSA operations
 */
     size = a->used + b->used + 1;
     if ((a == d) && (size < a->alloc)) {
         size = a->alloc;
     }
     if ((res = pstm_init_size(pool, &tmp, size)) != PSTM_OKAY) {
         return res;
     }
     if ((res = pstm_mul_comba(pool, a, b, &tmp, NULL, 0)) != PSTM_OKAY) {
         pstm_clear(&tmp);
         return res;
     }
     res = pstm_mod(pool, &tmp, c, d);
     pstm_clear(&tmp);
     return res;
 }
References pstm_int::alloc, c, NULL, pstm_clear(), pstm_init_size, pstm_mod(), pstm_mul_comba, PSTM_OKAY, size, and pstm_int::used.
Referenced by pstm_exptmod().
pstm_read_unsigned_bin()
int32 FAST_FUNC pstm_read_unsigned_bin (pstm_int * a, unsigned char * b, int32 c)
Definition at line 406 of file tls_pstm.c.
 {
     /* zero the int */
     pstm_zero (a);
 /*
     If we know the endianness of this architecture, and we're using
     32-bit pstm_digits, we can optimize this
 */
 #if (defined(ENDIAN_LITTLE) || defined(ENDIAN_BIG)) && !defined(PSTM_64BIT)
   /* But not for both simultaneously */
 #if defined(ENDIAN_LITTLE) && defined(ENDIAN_BIG)
 #error Both ENDIAN_LITTLE and ENDIAN_BIG defined.
 #endif
     {
         unsigned char *pd;
         if ((unsigned)c > (PSTM_MAX_SIZE * sizeof(pstm_digit))) {
             uint32 excess = c - (PSTM_MAX_SIZE * sizeof(pstm_digit));
             c -= excess;
             b += excess;
         }
         a->used = ((c + sizeof(pstm_digit) - 1)/sizeof(pstm_digit));
         if (a->alloc < a->used) {
             if (pstm_grow(a, a->used) != PSTM_OKAY) {
                 return PSTM_MEM;
             }
         }
         pd = (unsigned char *)a->dp;
         /* read the bytes in */
 #ifdef ENDIAN_BIG
         {
             /* Use Duff's device to unroll the loop. */
             int32 idx = (c - 1) & ~3;
             switch (c % 4) {
                 case 0: do { pd[idx+0] = *b++;
                     case 3: pd[idx+1] = *b++;
                     case 2: pd[idx+2] = *b++;
                     case 1: pd[idx+3] = *b++;
                     idx -= 4;
                 } while ((c -= 4) > 0);
             }
         }
 #else
         for (c -= 1; c >= 0; c -= 1) {
             pd[c] = *b++;
         }
 #endif
     }
 #else
     /* Big enough based on the len? */
     a->used = (((c / sizeof(pstm_digit)) * (sizeof(pstm_digit) * CHAR_BIT))
         / DIGIT_BIT) + 2;
     if (a->alloc < a->used) {
         if (pstm_grow(a, a->used) != PSTM_OKAY) {
             return PSTM_MEM;
         }
     }
     /* read the bytes in */
     for (; c > 0; c--) {
         if (pstm_mul_2d (a, 8, a) != PSTM_OKAY) {
             return PS_MEM_FAIL;
         }
         a->dp[0] |= *b++;
         a->used += 1;
     }
 #endif
     pstm_clamp (a);
     return PS_SUCCESS;
 }
References pstm_int::alloc, c, pstm_int::dp, idx, pd, pstm_grow, PSTM_MAX_SIZE, PSTM_MEM, PSTM_OKAY, pstm_zero(), and pstm_int::used.
Referenced by binary_to_pstm(), and psRsaCrypt().
pstm_reverse()
static void pstm_reverse (unsigned char * s, int len) static
Definition at line 1885 of file tls_pstm.c.
 {
     int32     ix, iy;
     unsigned char t;
     ix = 0;
     iy = len - 1;
     while (ix < iy) {
         t     = s[ix];
         s[ix] = s[iy];
         s[iy] = t;
         ++ix;
         --iy;
     }
 }
References s, and t.
Referenced by pstm_to_unsigned_bin().
pstm_rshd()
static void pstm_rshd (pstm_int * a, int x) static
Definition at line 521 of file tls_pstm.c.
 {
     int y; //bbox: was int16
     /* too many digits just zero and return */
     if (x >= a->used) {
         pstm_zero(a);
         return;
     }
     /* shift */
     for (y = 0; y < a->used - x; y++) {
         a->dp[y] = a->dp[y+x];
     }
     /* zero rest */
     for (; y < a->used; y++) {
         a->dp[y] = 0;
     }
     /* decrement count */
     a->used -= x;
     pstm_clamp(a);
 }
References pstm_int::dp, pstm_clamp(), pstm_zero(), pstm_int::used, x, and y.
Referenced by pstm_div(), and pstm_div_2d().
pstm_set()
static void pstm_set (pstm_int * a, pstm_digit b) static
Definition at line 510 of file tls_pstm.c.
 {
    pstm_zero(a);
    a->dp[0] = b;
    a->used  = a->dp[0] ? 1 : 0;
 }
References pstm_int::dp, pstm_zero(), and pstm_int::used.
Referenced by pstm_montgomery_calc_normalization().
pstm_sub()
int32 FAST_FUNC pstm_sub (pstm_int * a, pstm_int * b, pstm_int * c)
Definition at line 802 of file tls_pstm.c.
 {
     int32   res;
     int sa, sb; //bbox: was int16
     sa = a->sign;
     sb = b->sign;
     if (sa != sb) {
 /*
         subtract a negative from a positive, OR a positive from a negative.
         For both, ADD their magnitudes, and use the sign of the first number.
  */
         c->sign = sa;
         if ((res = s_pstm_add (a, b, c)) != PSTM_OKAY) {
             return res;
         }
     } else {
 /*
         subtract a positive from a positive, OR a negative from a negative.
         First, take the difference between their magnitudes, then...
  */
         if (pstm_cmp_mag (a, b) != PSTM_LT) {
             /* Copy the sign from the first */
             c->sign = sa;
             /* The first has a larger or equal magnitude */
             if ((res = s_pstm_sub (a, b, c)) != PSTM_OKAY) {
                 return res;
             }
         } else {
             /* The result has the _opposite_ sign from the first number. */
             c->sign = (sa == PSTM_ZPOS) ? PSTM_NEG : PSTM_ZPOS;
             /* The second has a larger magnitude */
             if ((res = s_pstm_sub (b, a, c)) != PSTM_OKAY) {
                 return res;
             }
         }
     }
     return PS_SUCCESS;
 }
References c, PS_SUCCESS, pstm_cmp_mag(), PSTM_LT, PSTM_NEG, PSTM_OKAY, PSTM_ZPOS, s_pstm_add(), s_pstm_sub(), and pstm_int::sign.
Referenced by psRsaCrypt(), and pstm_div().
pstm_to_unsigned_bin()
int32 FAST_FUNC pstm_to_unsigned_bin (psPool_t * pool, pstm_int * a, unsigned char * b)
Definition at line 1932 of file tls_pstm.c.
 {
     int32     res;
     int x; //bbox: was int16
     pstm_int  t = { 0 };
     if ((res = pstm_init_copy(pool, &t, a, 0)) != PSTM_OKAY) {
         return res;
     }
     x = 0;
     while (pstm_iszero (&t) == 0) {
         b[x++] = (unsigned char) (t.dp[0] & 255);
         if ((res = pstm_div_2d (pool, &t, 8, &t, NULL)) != PSTM_OKAY) {
             pstm_clear(&t);
             return res;
         }
     }
     pstm_reverse (b, x);
     pstm_clear(&t);
     return PS_SUCCESS;
 }
References NULL, PS_SUCCESS, pstm_clear(), pstm_div_2d, pstm_init_copy, pstm_iszero, PSTM_OKAY, pstm_reverse(), t, and x.
pstm_unsigned_bin_size()
int32 FAST_FUNC pstm_unsigned_bin_size (pstm_int * a)
Definition at line 503 of file tls_pstm.c.
 {
     int32     size = pstm_count_bits (a);
     return (size / 8 + ((size & 7) != 0 ? 1 : 0));
 }
References pstm_count_bits(), and size.
Referenced by find_key_in_der_cert(), and psRsaCrypt().
pstm_zero()
static void pstm_zero (pstm_int * a) static
Definition at line 298 of file tls_pstm.c.
 {
     int32       n;
     pstm_digit  *tmp;
     a->sign = PSTM_ZPOS;
     a->used = 0;
     tmp = a->dp;
     for (n = 0; n < a->alloc; n++) {
         *tmp++ = 0;
     }
 }
References pstm_int::alloc, pstm_int::dp, n, PSTM_ZPOS, pstm_int::sign, and pstm_int::used.
Referenced by pstm_2expt(), pstm_div(), pstm_div_2d(), pstm_mod_2d(), pstm_read_unsigned_bin(), pstm_rshd(), and pstm_set().
s_pstm_add()
static int32 s_pstm_add (pstm_int * a, pstm_int * b, pstm_int * c) static
Definition at line 745 of file tls_pstm.c.
 {
     int             x, y, oldused; //bbox: was int16
     register pstm_word  t, adp, bdp;
     y = a->used;
     if (b->used > y) {
         y = b->used;
     }
     oldused = c->used;
     c->used = y;
     if (c->used > c->alloc) {
         if (pstm_grow(c, c->used) != PSTM_OKAY) {
             return PS_MEM_FAIL;
         }
     }
     t = 0;
     for (x = 0; x < y; x++) {
         if (a->used < x) {
             adp = 0;
         } else {
             adp = (pstm_word)a->dp[x];
         }
         if (b->used < x) {
             bdp = 0;
         } else {
             bdp = (pstm_word)b->dp[x];
         }
         t         += (adp) + (bdp);
         c->dp[x]   = (pstm_digit)t;
         t        >>= DIGIT_BIT;
     }
     if (t != 0 && x < PSTM_MAX_SIZE) {
         if (c->used == c->alloc) {
             if (pstm_grow(c, c->alloc + 1) != PSTM_OKAY) {
                 return PS_MEM_FAIL;
             }
         }
         c->dp[c->used++] = (pstm_digit)t;
         ++x;
     }
     c->used = x;
     for (; x < oldused; x++) {
         c->dp[x] = 0;
     }
     pstm_clamp(c);
     return PSTM_OKAY;
 }
References c, DIGIT_BIT, pstm_int::dp, PS_MEM_FAIL, pstm_clamp(), pstm_grow, PSTM_MAX_SIZE, PSTM_OKAY, t, pstm_int::used, x, and y.
Referenced by pstm_add(), and pstm_sub().
s_pstm_sub()
int32 FAST_FUNC s_pstm_sub (pstm_int * a, pstm_int * b, pstm_int * c)
Definition at line 705 of file tls_pstm.c.
 {
     int     oldbused, oldused; //bbox: was int16
     int32       x;
     pstm_word   t;
     if (b->used > a->used) {
         return PS_LIMIT_FAIL;
     }
     if (c->alloc < a->used) {
         if ((x = pstm_grow (c, a->used)) != PSTM_OKAY) {
             return x;
         }
     }
     oldused  = c->used;
     oldbused = b->used;
     c->used  = a->used;
     t = 0;
     for (x = 0; x < oldbused; x++) {
         t = ((pstm_word)a->dp[x]) - (((pstm_word)b->dp[x]) + t);
         c->dp[x] = (pstm_digit)t;
         t = (t >> DIGIT_BIT)&1;
     }
     for (; x < a->used; x++) {
         t = ((pstm_word)a->dp[x]) - t;
         c->dp[x] = (pstm_digit)t;
         t = (t >> DIGIT_BIT);
     }
     for (; x < oldused; x++) {
         c->dp[x] = 0;
     }
     pstm_clamp(c);
     return PSTM_OKAY;
 }
References c, DIGIT_BIT, pstm_int::dp, PS_LIMIT_FAIL, pstm_clamp(), pstm_grow, PSTM_OKAY, t, pstm_int::used, and x.
Referenced by pstm_add(), pstm_montgomery_calc_normalization(), pstm_montgomery_reduce(), and pstm_sub().