Fennix: Kernel/include/interface/syscalls.h File Reference
syscalls.h File Reference
Functions
static long syscall0 (long syscall)
static long syscall1 (long syscall, long arg1)
static long syscall2 (long syscall, long arg1, long arg2)
static long syscall3 (long syscall, long arg1, long arg2, long arg3)
static long syscall4 (long syscall, long arg1, long arg2, long arg3, long arg4)
static long syscall5 (long syscall, long arg1, long arg2, long arg3, long arg4, long arg5)
static long syscall6 (long syscall, long arg1, long arg2, long arg3, long arg4, long arg5, long arg6)
Function Documentation
syscall0()
static long syscall0 (long syscall) inline static
Definition at line 22 of file syscalls.h.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), ret, and syscall().
Referenced by fork().
syscall1()
static long syscall1 (long syscall, long arg1) inline static
Definition at line 34 of file syscalls.h.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), ret, and syscall().
Referenced by _exit(), abort(), ELFLookupSymbol(), and fclose().
syscall2()
static long syscall2 (long syscall, long arg1, long arg2) inline static
Definition at line 46 of file syscalls.h.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), ret, and syscall().
Referenced by ELFLookupSymbol(), fopen(), FreePages(), and liballoc_free().
syscall3()
static long syscall3 (long syscall, long arg1, long arg2, long arg3) inline static
Definition at line 58 of file syscalls.h.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2), "d"(arg3)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), ret, and syscall().
Referenced by ELFLookupSymbol(), fread(), fseek(), and fwrite().
syscall4()
static long syscall4 (long syscall, long arg1, long arg2, long arg3, long arg4) inline static
Definition at line 70 of file syscalls.h.
 {
     long ret;
     register long r10 __asm__("r10") = arg4;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2), "d"(arg3), "r"(r10)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), ret, and syscall().
syscall5()
static long syscall5 (long syscall, long arg1, long arg2, long arg3, long arg4, long arg5) inline static
Definition at line 83 of file syscalls.h.
 {
     long ret;
     register long r10 __asm__("r10") = arg4;
     register long r8 __asm__("r8") = arg5;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2), "d"(arg3), "r"(r10), "r"(r8)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), ret, and syscall().
syscall6()
static long syscall6 (long syscall, long arg1, long arg2, long arg3, long arg4, long arg5, long arg6) inline static
Definition at line 97 of file syscalls.h.
 {
     long ret;
     register long r10 __asm__("r10") = arg4;
     register long r8 __asm__("r8") = arg5;
     register long r9 __asm__("r9") = arg6;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(syscall), "D"(arg1), "S"(arg2), "d"(arg3), "r"(r10), "r"(r8), "r"(r9)
                          : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), ret, and syscall().
Referenced by liballoc_alloc(), and RequestPages().