Fennix Userspace: Userspace/apps/base/busybox/libbb/auto_string.c File Reference
auto_string.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC auto_string (char *str)
Function Documentation
auto_string()
char* FAST_FUNC auto_string (char * str)
Definition at line 13 of file auto_string.c.
 {
     static char *saved[4];
     static uint8_t cur_saved; /* = 0 */
     free(saved[cur_saved]);
     saved[cur_saved] = str;
     cur_saved = (cur_saved + 1) & (ARRAY_SIZE(saved)-1);
     return str;
 }
References ARRAY_SIZE, free, and str.
Referenced by chs_string11(), get_variable(), INET_sprint(), ll_idx_n2a(), make_human_readable_str(), normalize(), partname(), print(), printable_string2(), rt_addr_n2a(), and UNSPEC_print().