Fennix Userspace: Userspace/musl/src/include/sys/stat.h File Reference
stat.h File Reference
#include "../../../include/sys/stat.h"
Functions
hidden int __fstat (int, struct stat *)
hidden int __fstatat (int, const char *restrict, struct stat *restrict, int)
Function Documentation
__fstat()
hidden int __fstat (int fd, struct stat * st)
Definition at line 7 of file fstat.c.
 {
     if (fd<0) return __syscall_ret(-EBADF);
     return __fstatat(fd, "", st, AT_EMPTY_PATH);
 }
References __fstatat(), __syscall_ret(), EBADF, and fd.
Referenced by __map_file().
__fstatat()
hidden int __fstatat (int , const char * restrict, struct stat * restrict, int)
Referenced by __fstat().