Fennix: Userspace/musl/src/ctype/iswupper.c File Reference
iswupper.c File Reference
#include <wctype.h>
Functions
int iswupper (wint_t wc)
int __iswupper_l (wint_t c, locale_t l)
weak_alias (__iswupper_l, iswupper_l)
Function Documentation
__iswupper_l()
int __iswupper_l (wint_t c, locale_t l)
Definition at line 8 of file iswupper.c.
 {
     return iswupper(c);
 }
References c, and iswupper().
iswupper()
int iswupper (wint_t wc)
Definition at line 3 of file iswupper.c.
 {
     return towlower(wc) != wc;
 }
References towlower().
Referenced by __iswupper_l(), and iswctype().
weak_alias()
weak_alias (__iswupper_l , iswupper_l)