Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/statdump.h File Reference
statdump.h File Reference
Functions
void StatCopy (wbstartstruct_t *stats)
void StatDump (void)
Function Documentation
StatCopy()
void StatCopy (wbstartstruct_t * stats)
Definition at line 333 of file statdump.c.
 {
     if (M_ParmExists("-statdump") && num_captured_stats < MAX_CAPTURES)
     {
         memcpy(&captured_stats[num_captured_stats], stats,
                sizeof(wbstartstruct_t));
         ++num_captured_stats;
     }
 }
References captured_stats, M_ParmExists(), MAX_CAPTURES, memcpy, and num_captured_stats.
Referenced by G_DoCompleted().
StatDump()
void StatDump (void)
Definition at line 343 of file statdump.c.
 {
 #if ORIGCODE
     FILE *dumpfile;
     int i;
     // @category compat
     // @arg <filename>
     //
     // Dump statistics information to the specified file on the levels
     // that were played. The output from this option matches the output
     // from statdump.exe (see ctrlapi.zip in the /idgames archive).
     //
     i = M_CheckParmWithArgs("-statdump", 1);
     if (i > 0)
     {
         printf("Statistics captured for %i level(s)\n", num_captured_stats);
         // We actually know what the real gamemission is, but this has
         // to match the output from statdump.exe.
         DiscoverGamemode(captured_stats, num_captured_stats);
         // Allow "-" as output file, for stdout.
         if (strcmp(myargv[i + 1], "-") != 0)
         {
             dumpfile = fopen(myargv[i + 1], "w");
         }
         else
         {
             dumpfile = NULL;
         }
         for (i = 0; i < num_captured_stats; ++i)
         {
             PrintStats(dumpfile, &captured_stats[i]);
         }
         if (dumpfile != NULL)
         {
             fclose(dumpfile);
         }
     }
 #endif
 }
References captured_stats, fclose(), fopen(), i, M_CheckParmWithArgs(), myargv, NULL, num_captured_stats, printf, and strcmp().
Referenced by D_DoomMain().