Fennix: Userspace/apps/base/bash/lib/termcap/tparam.c File Reference
tparam.c File Reference
#include "ltcap.h"
Functions
char * malloc ()
char * realloc ()
static void memory_out ()
static char * xmalloc (unsigned size)
static char * xrealloc (char *ptr, unsigned size)
static char * tparam1 ()
char * tparam (char *string, char *outstring, int len, int arg0, int arg1, int arg2, int arg3)
__private_extern__ char * tgoto (char *cm, int hpos, int vpos)
static char * tparam1 (char *string, char *outstring, int len, char *up, char *left, int *argp)
Variables
__private_extern__ char * BC
__private_extern__ char * UP
static char tgoto_buf [50]
Function Documentation
malloc()
char* malloc ()
Referenced by xmalloc().
memory_out()
static void memory_out () static
Definition at line 65 of file tparam.c.
 {
   write (2, "virtual memory exhausted\n", 25);
   exit (1);
 }
References exit(), and write().
Referenced by xmalloc(), and xrealloc().
realloc()
char* realloc ()
Referenced by xrealloc().
tgoto()
__private_extern__ char* tgoto (char * cm, int hpos, int vpos)
Definition at line 133 of file tparam.c.
 {
   int args[2];
   if (!cm)
     return NULL;
   args[0] = vpos;
   args[1] = hpos;
   return tparam1 (cm, tgoto_buf, 50, UP, BC, args);
 }
References BC, NULL, tgoto_buf, tparam1(), and UP.
tparam()
char* tparam (char * string, char * outstring, int len, int arg0, int arg1, int arg2, int arg3)
Definition at line 111 of file tparam.c.
 {
   int arg[4];
   arg[0] = arg0;
   arg[1] = arg1;
   arg[2] = arg2;
   arg[3] = arg3;
   return tparam1 (string, outstring, len, NULL, NULL, arg);
 }
References arg0, len, NULL, and tparam1().
tparam1() [1/2]
static char* tparam1 () static
Referenced by tgoto(), and tparam().
tparam1() [2/2]
static char* tparam1 (char * string, char * outstring, int len, char * up, char * left, int * argp) static
Definition at line 146 of file tparam.c.
 {
   register int c;
   register char *p = string;
   register char *op = outstring;
   char *outend;
   int outlen = 0;
   register int tem;
   int *old_argp = argp;
   int doleft = 0;
   int doup = 0;
   outend = outstring + len;
   while (1)
     {
       /* If the buffer might be too short, make it bigger.  */
       if (op + 5 >= outend)
     {
       register char *new;
       if (outlen == 0)
         {
           outlen = len + 40;
           new = (char *) xmalloc (outlen);
           outend += 40;
           bcopy (outstring, new, op - outstring);
         }
       else
         {
           outend += outlen;
           outlen *= 2;
           new = (char *) xrealloc (outstring, outlen);
         }
       op += new - outstring;
       outend += new - outstring;
       outstring = new;
     }
       c = *p++;
       if (!c)
     break;
       if (c == '%')
     {
       c = *p++;
       tem = *argp;
       switch (c)
         {
         case 'd':       /* %d means output in decimal.  */
           if (tem < 10)
         goto onedigit;
           if (tem < 100)
         goto twodigit;
         case '3':       /* %3 means output in decimal, 3 digits.  */
           if (tem > 999)
         {
           *op++ = tem / 1000 + '0';
           tem %= 1000;
         }
           *op++ = tem / 100 + '0';
         case '2':       /* %2 means output in decimal, 2 digits.  */
         twodigit:
           tem %= 100;
           *op++ = tem / 10 + '0';
         onedigit:
           *op++ = tem % 10 + '0';
           argp++;
           break;
         case 'C':
           /* For c-100: print quotient of value by 96, if nonzero,
          then do like %+.  */
           if (tem >= 96)
         {
           *op++ = tem / 96;
           tem %= 96;
         }
         case '+':       /* %+x means add character code of char x.  */
           tem += *p++;
         case '.':       /* %. means output as character.  */
           if (left)
         {
           /* If want to forbid output of 0 and \n and \t,
              and this is one of them, increment it.  */
           while (tem == 0 || tem == '\n' || tem == '\t')
             {
               tem++;
               if (argp == old_argp)
             doup++, outend -= strlen (up);
               else
             doleft++, outend -= strlen (left);
             }
         }
           *op++ = tem ? tem : 0200;
         case 'f':       /* %f means discard next arg.  */
           argp++;
           break;
         case 'b':       /* %b means back up one arg (and re-use it).  */
           argp--;
           break;
         case 'r':       /* %r means interchange following two args.  */
           argp[0] = argp[1];
           argp[1] = tem;
           old_argp++;
           break;
         case '>':       /* %>xy means if arg is > char code of x, */
           if (argp[0] > *p++) /* then add char code of y to the arg, */
         argp[0] += *p;  /* and in any case don't output.  */
           p++;      /* Leave the arg to be output later.  */
           break;
         case 'a':       /* %a means arithmetic.  */
           /* Next character says what operation.
          Add or subtract either a constant or some other arg.  */
           /* First following character is + to add or - to subtract
          or = to assign.  */
           /* Next following char is 'p' and an arg spec
          (0100 plus position of that arg relative to this one)
          or 'c' and a constant stored in a character.  */
           tem = p[2] & 0177;
           if (p[1] == 'p')
         tem = argp[tem - 0100];
           if (p[0] == '-')
         argp[0] -= tem;
           else if (p[0] == '+')
         argp[0] += tem;
           else if (p[0] == '*')
         argp[0] *= tem;
           else if (p[0] == '/')
         argp[0] /= tem;
           else
         argp[0] = tem;
           p += 3;
           break;
         case 'i':       /* %i means add one to arg, */
           argp[0] ++;   /* and leave it to be output later.  */
           argp[1] ++;   /* Increment the following arg, too!  */
           break;
         case '%':       /* %% means output %; no arg.  */
           goto ordinary;
         case 'n':       /* %n means xor each of next two args with 140.  */
           argp[0] ^= 0140;
           argp[1] ^= 0140;
           break;
         case 'm':       /* %m means xor each of next two args with 177.  */
           argp[0] ^= 0177;
           argp[1] ^= 0177;
           break;
         case 'B':       /* %B means express arg as BCD char code.  */
           argp[0] += 6 * (tem / 10);
           break;
         case 'D':       /* %D means weird Delta Data transformation.  */
           argp[0] -= 2 * (tem % 16);
           break;
         }
     }
       else
     /* Ordinary character in the argument string.  */
       ordinary:
     *op++ = c;
     }
   *op = 0;
   while (doup-- > 0)
     strcat (op, up);
   while (doleft-- > 0)
     strcat (op, left);
   return outstring;
 }
References bcopy, c, len, p, strcat, string, strlen, up, xmalloc(), and xrealloc().
xmalloc()
static char* xmalloc (unsigned size) static
Definition at line 72 of file tparam.c.
 {
   register char *tem = malloc (size);
   if (!tem)
     memory_out ();
   return tem;
 }
References malloc(), memory_out(), and size.
Referenced by tparam1().
xrealloc()
static char* xrealloc (char * ptr, unsigned size) static
Definition at line 83 of file tparam.c.
 {
   register char *tem = realloc (ptr, size);
   if (!tem)
     memory_out ();
   return tem;
 }
References memory_out(), realloc(), and size.
Referenced by tparam1().
Variable Documentation
BC
__private_extern__ char* BC
Definition at line 126 of file tparam.c.
Referenced by tgoto().
tgoto_buf
char tgoto_buf[50] static
Definition at line 129 of file tparam.c.
Referenced by tgoto().
UP
__private_extern__ char* UP
Definition at line 127 of file tparam.c.
Referenced by tgoto().