Fennix: Kernel/Architecture/amd64/SystemCalls.cpp File Reference
SystemCalls.cpp File Reference
#include <syscalls.hpp>
#include <cpu.hpp>
#include "cpu/gdt.hpp"
Functions
__attribute__ ((naked, used, no_stack_protector)) void SystemCallHandlerStub()
uint64_t SystemCallsHandler (SyscallsRegs *regs)
void InitializeSystemCalls ()
Initialize syscalls for the current CPU. (Function is available on x32, x64 & aarch64)
Function Documentation
__attribute__()
__attribute__ ((naked, used, no_stack_protector))
Definition at line 9 of file SystemCalls.cpp.
 {
 }
InitializeSystemCalls()
void InitializeSystemCalls ()
Initialize syscalls for the current CPU. (Function is available on x32, x64 & aarch64)
Definition at line 15 of file SystemCalls.cpp.
 {
     wrmsr(MSR_EFER, rdmsr(MSR_EFER) | 1);
     wrmsr(MSR_STAR, ((uint64_t)(GDT_KERNEL_CODE) << 32) | ((uint64_t)(GDT_KERNEL_DATA | 3) << 48));
     wrmsr(MSR_LSTAR, (uint64_t)SystemCallsHandler);
     wrmsr(MSR_SYSCALL_MASK, 0);
 }
References GDT_KERNEL_CODE, GDT_KERNEL_DATA, CPU::x64::MSR_EFER, CPU::x64::MSR_LSTAR, CPU::x64::MSR_STAR, CPU::x64::MSR_SYSCALL_MASK, CPU::x64::rdmsr(), SystemCallsHandler(), and CPU::x64::wrmsr().
SystemCallsHandler()
uint64_t SystemCallsHandler (SyscallsRegs * regs)
Definition at line 5 of file SystemCalls.cpp.
 {
 #if defined(__amd64__)
     fixme("System call %ld", regs->rax);
 #elif defined(__i386__)
     fixme("System call %ld", regs->eax);
 #elif defined(__aarch64__)
     fixme("System call");
 #endif
     return 0;
 }