Fennix: Kernel/arch/amd64/cpu/smp.cpp File Reference
smp.cpp File Reference
#include <smp.hpp>
#include <memory.hpp>
#include <acpi.hpp>
#include <ints.hpp>
#include <assert.h>
#include <cpu.hpp>
#include <atomic>
#include "../../../kernel.h"
#include "apic.hpp"
Namespaces
SMP
Enumerations
enum SMPTrampolineAddress {
PAGE_TABLE = 0x500 , START_ADDR = 0x520 , STACK = 0x570 , GDT = 0x580 ,
IDT = 0x590 , CORE = 0x600 , TRAMPOLINE_START = 0x2000 , PAGE_TABLE = 0x500 ,
START_ADDR = 0x520 , STACK = 0x570 , GDT = 0x580 , IDT = 0x590 ,
CORE = 0x600 , TRAMPOLINE_START = 0x2000
}
Functions
static __aligned (PAGE_SIZE) CPUData CPUs[MAX_CPU]
nsa CPUData * GetCPU (long id)
nsa CPUData * GetCurrentCPU ()
void StartCPU ()
void SMP::Initialize (void *madt)
Variables
uint64_t _trampoline_start
uint64_t _trampoline_end
std::atomic_bool CPUEnabled = false
Enumeration Type Documentation
SMPTrampolineAddress
enum SMPTrampolineAddress
Enumerator
PAGE_TABLE
START_ADDR
STACK
GDT
IDT
CORE
TRAMPOLINE_START
PAGE_TABLE
START_ADDR
STACK
GDT
IDT
CORE
TRAMPOLINE_START
Definition at line 33 of file smp.cpp.
 {
     PAGE_TABLE = 0x500,
     START_ADDR = 0x520,
     STACK = 0x570,
     GDT = 0x580,
     IDT = 0x590,
     CORE = 0x600,
     TRAMPOLINE_START = 0x2000
 };
Function Documentation
__aligned()
static __aligned (PAGE_SIZE) static
GetCPU()
nsa CPUData* GetCPU (long id)
Definition at line 49 of file smp.cpp.
 { return &CPUs[id]; }
GetCurrentCPU()
nsa CPUData* GetCurrentCPU ()
Definition at line 51 of file smp.cpp.
 {
     if (unlikely(!Interrupts::apic[0]))
         return &CPUs[0]; /* No APIC means we are on the BSP. */
     APIC::APIC *apic = (APIC::APIC *)Interrupts::apic[0];
     int CoreID = 0;
     if (CPUEnabled.load(std::memory_order_acquire) == true)
     {
         Memory::SwapPT swap =
             Memory::SwapPT(KernelPageTable, thisPageTable);
         if (apic->x2APIC)
             CoreID = int(CPU::x64::rdmsr(CPU::x64::MSR_X2APIC_APICID));
         else
             CoreID = apic->Read(APIC::APIC_ID) >> 24;
     }
     if (unlikely((&CPUs[CoreID])->IsActive != true))
     {
         error("CPU %d is not active!", CoreID);
         assert((&CPUs[0])->IsActive == true); /* We can't continue without the BSP. */
         return &CPUs[0];
     }
     assert((&CPUs[CoreID])->Checksum == CPU_DATA_CHECKSUM); /* This should never happen. */
     return &CPUs[CoreID];
 }
References APIC::APIC_ID, assert, Checksum, CPU_DATA_CHECKSUM, CPUEnabled, error, IsActive, KernelPageTable, memory_order_acquire, CPU::x64::MSR_X2APIC_APICID, APIC::APIC::Read(), swap(), thisPageTable, unlikely, and APIC::APIC::x2APIC.
StartCPU()
void StartCPU ()
Definition at line 80 of file smp.cpp.
 {
     CPU::Interrupts(CPU::Disable);
     int CoreID = (int)*reinterpret_cast<int *>(CORE);
     CPU::InitializeFeatures(CoreID);
     // Initialize GDT and IDT
     Interrupts::Initialize(CoreID);
     Interrupts::Enable(CoreID);
     Interrupts::InitializeTimer(CoreID);
     asmv("mov %0, %%rsp" ::"r"((&CPUs[CoreID])->Stack));
     CPU::Interrupts(CPU::Enable);
     KPrint("CPU %d is online", CoreID);
     CPUEnabled.store(true, std::memory_order_release);
     CPU::Halt(true);
 }
References asmv(), CORE, CPUEnabled, CPU::Disable, Interrupts::Enable(), CPU::Enable, CPU::Halt(), Interrupts::Initialize(), CPU::InitializeFeatures(), Interrupts::InitializeTimer(), CPU::Interrupts(), KPrint(), memory_order_release, and Stack.
Variable Documentation
_trampoline_end
uint64_t _trampoline_end
Definition at line 30 of file smp.cpp.
_trampoline_start
uint64_t _trampoline_start
Definition at line 30 of file smp.cpp.
CPUEnabled
std::atomic_bool CPUEnabled = false
Definition at line 44 of file smp.cpp.