Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/ntfs.c File Reference
ntfs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct ntfs_super_block
struct master_file_table_record
struct file_attribute
struct volume_info
Macros
#define MFT_RECORD_VOLUME 3
#define MFT_RECORD_ATTR_VOLUME_NAME 0x60
#define MFT_RECORD_ATTR_VOLUME_INFO 0x70
#define MFT_RECORD_ATTR_OBJECT_ID 0x40
#define MFT_RECORD_ATTR_END 0xffffffffu
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_ntfs (struct volume_id *id)
Variables
struct ntfs_super_block PACKED
Data Structure Documentation
ntfs_super_block
struct ntfs_super_block
Definition at line 29 of file ntfs.c.
Data Fields
uint16_t bytes_per_sector
uint16_t checksum
int8_t cluster_per_index_record
int8_t cluster_per_mft_record
uint8_t fats
uint16_t heads
uint32_t hidden_sectors
uint8_t jump[3]
uint32_t large_sectors
uint8_t media_type
uint64_t mft_cluster_location
uint64_t mft_mirror_cluster_location
uint64_t number_of_sectors
uint8_t oem_id[8]
uint8_t reserved1[3]
uint8_t reserved2[3]
uint16_t reserved_sectors
uint16_t root_entries
uint16_t sectors
uint8_t sectors_per_cluster
uint16_t sectors_per_fat
uint16_t sectors_per_track
uint16_t unused[2]
uint8_t volume_serial[8]
master_file_table_record
struct master_file_table_record
Definition at line 56 of file ntfs.c.
Data Fields
uint16_t attrs_offset
uint32_t bytes_allocated
uint32_t bytes_in_use
uint16_t flags
uint16_t link_count
uint64_t lsn
uint8_t magic[4]
uint16_t sequence_number
uint16_t usa_count
uint16_t usa_ofs
file_attribute
struct file_attribute
Definition at line 69 of file ntfs.c.
Data Fields
uint16_t flags
uint16_t instance
uint32_t len
uint8_t name_len
uint16_t name_offset
uint8_t non_resident
uint32_t type
uint32_t value_len
uint16_t value_offset
volume_info
struct volume_info
Definition at line 81 of file ntfs.c.
Data Fields
uint8_t major_ver
uint8_t minor_ver
uint64_t reserved
Macro Definition Documentation
MFT_RECORD_ATTR_END
#define MFT_RECORD_ATTR_END 0xffffffffu
Definition at line 91 of file ntfs.c.
MFT_RECORD_ATTR_OBJECT_ID
#define MFT_RECORD_ATTR_OBJECT_ID 0x40
Definition at line 90 of file ntfs.c.
MFT_RECORD_ATTR_VOLUME_INFO
#define MFT_RECORD_ATTR_VOLUME_INFO 0x70
Definition at line 89 of file ntfs.c.
MFT_RECORD_ATTR_VOLUME_NAME
#define MFT_RECORD_ATTR_VOLUME_NAME 0x60
Definition at line 88 of file ntfs.c.
MFT_RECORD_VOLUME
#define MFT_RECORD_VOLUME 3
Definition at line 87 of file ntfs.c.
off
#define off ((uint64_t)0)
Function Documentation
volume_id_probe_ntfs()
int FAST_FUNC volume_id_probe_ntfs (struct volume_id * id)
Definition at line 93 of file ntfs.c.
 {
 #define off ((uint64_t)0)
     unsigned sector_size;
     unsigned cluster_size;
     uint64_t mft_cluster;
     uint64_t mft_off;
     unsigned mft_record_size;
     unsigned attr_type;
     unsigned attr_off;
     unsigned attr_len;
     unsigned val_off;
     unsigned val_len;
     struct master_file_table_record *mftr;
     struct ntfs_super_block *ns;
     const uint8_t *buf;
     const uint8_t *val;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     ns = volume_id_get_buffer(id, off, 0x200);
     if (ns == NULL)
         return -1;
     if (memcmp(ns->oem_id, "NTFS", 4) != 0)
         return -1;
     volume_id_set_uuid(id, ns->volume_serial, UUID_NTFS);
     sector_size = le16_to_cpu(ns->bytes_per_sector);
     cluster_size = ns->sectors_per_cluster * sector_size;
     mft_cluster = le64_to_cpu(ns->mft_cluster_location);
     mft_off = mft_cluster * cluster_size;
     if (ns->cluster_per_mft_record < 0)
         /* size = -log2(mft_record_size); normally 1024 Bytes */
         mft_record_size = 1 << -ns->cluster_per_mft_record;
     else
         mft_record_size = ns->cluster_per_mft_record * cluster_size;
     dbg("sectorsize  0x%x", sector_size);
     dbg("clustersize 0x%x", cluster_size);
     dbg("mftcluster  %llu", (unsigned long long) mft_cluster);
     dbg("mftoffset  0x%llx", (unsigned long long) mft_off);
     dbg("cluster per mft_record  %i", ns->cluster_per_mft_record);
     dbg("mft record size  %i", mft_record_size);
     buf = volume_id_get_buffer(id, off + mft_off + (MFT_RECORD_VOLUME * mft_record_size),
             mft_record_size);
     if (buf == NULL)
         goto found;
     mftr = (struct master_file_table_record*) buf;
     dbg("mftr->magic '%c%c%c%c'", mftr->magic[0], mftr->magic[1], mftr->magic[2], mftr->magic[3]);
     if (memcmp(mftr->magic, "FILE", 4) != 0)
         goto found;
     attr_off = le16_to_cpu(mftr->attrs_offset);
     dbg("file $Volume's attributes are at offset %i", attr_off);
     while (1) {
         struct file_attribute *attr;
         attr = (struct file_attribute*) &buf[attr_off];
         attr_type = le32_to_cpu(attr->type);
         attr_len = le32_to_cpu(attr->len);
         val_off = le16_to_cpu(attr->value_offset);
         val_len = le32_to_cpu(attr->value_len);
         attr_off += attr_len;
         if (attr_len == 0)
             break;
         if (attr_off >= mft_record_size)
             break;
         if (attr_type == MFT_RECORD_ATTR_END)
             break;
         dbg("found attribute type 0x%x, len %i, at offset %i",
             attr_type, attr_len, attr_off);
 //      if (attr_type == MFT_RECORD_ATTR_VOLUME_INFO) {
 //          struct volume_info *info;
 //          dbg("found info, len %i", val_len);
 //          info = (struct volume_info*) (((uint8_t *) attr) + val_off);
 //          snprintf(id->type_version, sizeof(id->type_version)-1,
 //               "%u.%u", info->major_ver, info->minor_ver);
 //      }
         if (attr_type == MFT_RECORD_ATTR_VOLUME_NAME) {
             dbg("found label, len %i", val_len);
             if (val_len > VOLUME_ID_LABEL_SIZE)
                 val_len = VOLUME_ID_LABEL_SIZE;
             val = ((uint8_t *) attr) + val_off;
 //          volume_id_set_label_raw(id, val, val_len);
             volume_id_set_label_unicode16(id, val, LE, val_len);
         }
     }
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "ntfs";)
     return 0;
 }
References master_file_table_record::attrs_offset, buf, ntfs_super_block::bytes_per_sector, ntfs_super_block::cluster_per_mft_record, dbg, found, LE, le16_to_cpu, le32_to_cpu, le64_to_cpu, file_attribute::len, master_file_table_record::magic, memcmp(), ntfs_super_block::mft_cluster_location, MFT_RECORD_ATTR_END, MFT_RECORD_ATTR_VOLUME_NAME, MFT_RECORD_VOLUME, NULL, ntfs_super_block::oem_id, off, sector_size, ntfs_super_block::sectors_per_cluster, file_attribute::type, UUID_NTFS, val, file_attribute::value_len, file_attribute::value_offset, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_unicode16(), volume_id_set_uuid(), and ntfs_super_block::volume_serial.
Variable Documentation
PACKED
struct volume_info PACKED