Fennix Userspace: Userspace/apps/base/bash/lib/sh/timers.c File Reference
timers.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixtime.h"
#include "sig.h"
#include "bashjmp.h"
#include "xmalloc.h"
#include "timer.h"
#include <errno.h>
Macros
#define FREE(s) do { if (s) free (s); } while (0)
Functions
unsigned int falarm (unsigned int, unsigned int)
static void shtimer_zero (sh_timer *)
sh_timer * shtimer_alloc (void)
void shtimer_flush (sh_timer *t)
void shtimer_dispose (sh_timer *t)
void shtimer_set (sh_timer *t, time_t sec, long usec)
void shtimer_unset (sh_timer *t)
void shtimer_cleanup (sh_timer *t)
void shtimer_clear (sh_timer *t)
int shtimer_chktimeout (sh_timer *t)
int shtimer_alrm (sh_timer *t)
Variables
int errno
Macro Definition Documentation
FREE
#define FREE (s) do { if (s) free (s); } while (0)
Definition at line 47 of file timers.c.
Function Documentation
falarm()
unsigned int falarm (unsigned int secs, unsigned int usecs)
Definition at line 68 of file ufuncs.c.
 {
   if (secs == 0 && usecs == 0)
     return (alarm (0));
   if (secs == 0 || usecs >= 500000)
     {
       secs++;
       usecs = 0;
     }
   return (alarm (secs));
 }
References alarm().
Referenced by shtimer_set(), and shtimer_unset().
shtimer_alloc()
sh_timer* shtimer_alloc (void)
Definition at line 72 of file timers.c.
 {
   sh_timer *t;
   t = (sh_timer *)xmalloc (sizeof (sh_timer));
   shtimer_zero (t);
   return t;
 }
References shtimer_zero(), t, and xmalloc.
shtimer_alrm()
int shtimer_alrm (sh_timer * t)
Definition at line 259 of file timers.c.
 {
   return 0;
 }
shtimer_chktimeout()
int shtimer_chktimeout (sh_timer * t)
Definition at line 159 of file timers.c.
 {
   struct timeval now;
   int r;
   /* Use the flag to avoid returning sigalrm_seen here */
   if (t->flags & SHTIMER_ALARM)
     return t->alrmflag;
   /* Could check a flag for this */
   if (t->tmout.tv_sec == 0 && t->tmout.tv_usec == 0)
     return 0;
   if (gettimeofday (&now, 0) < 0)
     return 0;
   r = ((now.tv_sec > t->tmout.tv_sec) ||
     (now.tv_sec == t->tmout.tv_sec && now.tv_usec >= t->tmout.tv_usec));
   return r;
 }
References gettimeofday(), SHTIMER_ALARM, t, timeval::tv_sec, and timeval::tv_usec.
shtimer_cleanup()
void shtimer_cleanup (sh_timer * t)
Definition at line 146 of file timers.c.
 {
   shtimer_unset (t);
 }
References shtimer_unset(), and t.
shtimer_clear()
void shtimer_clear (sh_timer * t)
Definition at line 152 of file timers.c.
 {
   shtimer_unset (t);
   shtimer_dispose (t);
 }
References shtimer_dispose(), shtimer_unset(), and t.
shtimer_dispose()
void shtimer_dispose (sh_timer * t)
Definition at line 92 of file timers.c.
 {
   free (t);
 }
References free, and t.
Referenced by shtimer_clear().
shtimer_flush()
void shtimer_flush (sh_timer * t)
Definition at line 82 of file timers.c.
 {
   /* The caller can manage t->data arbitrarily as long as it frees and sets
      t->data to 0 before calling this function. Otherwise, we do what we can
      to avoid memleaks. */
   FREE (t->data);
   shtimer_zero (t);
 }
References FREE, shtimer_zero(), and t.
shtimer_set()
void shtimer_set (sh_timer * t, time_t sec, long usec)
Definition at line 99 of file timers.c.
 {
   struct timeval now;
   if (t->flags & SHTIMER_ALARM)
     {
       t->alrmflag = 0;      /* just paranoia */
       t->old_handler = set_signal_handler (SIGALRM, t->alrm_handler);
       t->flags |= SHTIMER_SIGSET;
       falarm (t->tmout.tv_sec = sec, t->tmout.tv_usec = usec);
       t->flags |= SHTIMER_ALRMSET;
       return;
     }
   if (gettimeofday (&now, 0) < 0)
     timerclear (&now);
   t->tmout.tv_sec = now.tv_sec + sec;
   t->tmout.tv_usec = now.tv_usec + usec;
   if (t->tmout.tv_usec > USEC_PER_SEC)
     {
       t->tmout.tv_sec++;
       t->tmout.tv_usec -= USEC_PER_SEC;
     }
 }
References falarm(), gettimeofday(), set_signal_handler, SHTIMER_ALARM, SHTIMER_ALRMSET, SHTIMER_SIGSET, SIGALRM, t, timerclear, timeval::tv_sec, timeval::tv_usec, and USEC_PER_SEC.
shtimer_unset()
void shtimer_unset (sh_timer * t)
Definition at line 126 of file timers.c.
 {
   t->tmout.tv_sec = 0;
   t->tmout.tv_usec = 0;
   if (t->flags & SHTIMER_ALARM)
     {
       t->alrmflag = 0;
       if (t->flags & SHTIMER_ALRMSET)
     falarm (0, 0);
       if (t->old_handler && (t->flags & SHTIMER_SIGSET))
     {
       set_signal_handler (SIGALRM, t->old_handler);
       t->flags &= ~SHTIMER_SIGSET;
       t->old_handler = 0;
     }
     }
 }
References falarm(), set_signal_handler, SHTIMER_ALARM, SHTIMER_ALRMSET, SHTIMER_SIGSET, SIGALRM, and t.
Referenced by shtimer_cleanup(), and shtimer_clear().
shtimer_zero()
static void shtimer_zero (sh_timer * t) static
Definition at line 55 of file timers.c.
 {
   t->tmout.tv_sec = 0;
   t->tmout.tv_usec = 0;
   t->fd = -1;
   t->flags = t->alrmflag = 0;
   t->alrm_handler = t->old_handler = 0;
   memset (t->jmpenv, '\0', sizeof (t->jmpenv));
   t->tm_handler = 0;
   t->data = 0;
 }
References memset(), and t.
Referenced by shtimer_alloc(), and shtimer_flush().
Variable Documentation
errno
int errno extern