Fennix Userspace: Userspace/apps/base/busybox/networking/telnet.c File Reference
telnet.c File Reference
#include <arpa/telnet.h>
#include <netinet/in.h>
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define put_iac2_x_y(x, y) put_iac2_msb_lsb(((x)<<8) + (y))
#define put_iac3_IAC_x_y(wwdd, c) put_iac3_IAC_x_y_merged(((wwdd)<<8) + (c))
Typedefs
typedef unsigned char byte
Enumerations
enum {
DATABUFSIZE = 128 , IACBUFSIZE = 128 , CHM_TRY = 0 , CHM_ON = 1 ,
CHM_OFF = 2 , UF_ECHO = 0x01 , UF_SGA = 0x02 , TS_NORMAL = 0 ,
TS_COPY = 1 , TS_IAC = 2 , TS_OPT = 3 , TS_SUB1 = 4 ,
TS_SUB2 = 5 , TS_CR = 6
}
enum { netfd = 3 }
Functions
static void rawmode (void)
static void cookmode (void)
static void do_linemode (void)
static void will_charmode (void)
static void telopt (byte c)
static void subneg (byte c)
static void iac_flush (void)
static void doexit (int ev) NORETURN
static void con_escape (void)
static void handle_net_output (int len)
static void handle_net_input (int len)
static void put_iac (int c)
static void put_iac2_msb_lsb (unsigned x_y)
static void put_iac3_IAC_x_y_merged (unsigned wwdd_and_c)
static void setConMode (void)
static void to_notsup (char c)
static void to_echo (void)
static void to_sga (void)
int telnet_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 139 of file telnet.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    BUILD_BUG_ON(sizeof(G) > COMMON_BUFSIZE); \
} while (0)
Definition at line 140 of file telnet.c.
put_iac2_x_y
#define put_iac2_x_y (x, y) put_iac2_msb_lsb(((x)<<8) + (y))
Definition at line 369 of file telnet.c.
put_iac3_IAC_x_y
#define put_iac3_IAC_x_y (wwdd, c) put_iac3_IAC_x_y_merged(((wwdd)<<8) + (c))
Definition at line 387 of file telnet.c.
Typedef Documentation
byte
typedef unsigned char byte
Definition at line 112 of file telnet.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DATABUFSIZE
IACBUFSIZE
CHM_TRY
CHM_ON
CHM_OFF
UF_ECHO
UF_SGA
TS_NORMAL
TS_COPY
TS_IAC
TS_OPT
TS_SUB1
TS_SUB2
TS_CR
Definition at line 92 of file telnet.c.
      {
     DATABUFSIZE = 128,
     IACBUFSIZE  = 128,
     CHM_TRY = 0,
     CHM_ON  = 1,
     CHM_OFF = 2,
     UF_ECHO = 0x01,
     UF_SGA  = 0x02,
     TS_NORMAL = 0,
     TS_COPY = 1,
     TS_IAC  = 2,
     TS_OPT  = 3,
     TS_SUB1 = 4,
     TS_SUB2 = 5,
     TS_CR   = 6,
 };
anonymous enum
anonymous enum
Enumerator
netfd
Definition at line 114 of file telnet.c.
 { netfd = 3 };
Function Documentation
con_escape()
static void con_escape (void) static
Definition at line 168 of file telnet.c.
 {
     char b;
     if (bb_got_signal) /* came from line mode... go raw */
         rawmode();
     full_write1_str("\r\nConsole escape. Commands are:\r\n\n"
             " l go to line mode\r\n"
             " c go to character mode\r\n"
             " z suspend telnet\r\n"
             " e exit telnet\r\n");
     if (read(STDIN_FILENO, &b, 1) <= 0)
         doexit(EXIT_FAILURE);
     switch (b) {
     case 'l':
         if (!bb_got_signal) {
             do_linemode();
             goto ret;
         }
         break;
     case 'c':
         if (bb_got_signal) {
             will_charmode();
             goto ret;
         }
         break;
     case 'z':
         cookmode();
         kill(0, SIGTSTP);
         rawmode();
         break;
     case 'e':
         doexit(EXIT_SUCCESS);
     }
     full_write1_str("continuing...\r\n");
     if (bb_got_signal)
         cookmode();
  ret:
     bb_got_signal = 0;
 }
References bb_got_signal, cookmode(), do_linemode(), doexit(), EXIT_FAILURE, EXIT_SUCCESS, full_write1_str(), kill(), rawmode(), read(), SIGTSTP, STDIN_FILENO, and will_charmode().
Referenced by handle_net_output(), and telnet_main().
cookmode()
static void cookmode (void) static
Definition at line 614 of file telnet.c.
 {
     if (G.do_termios)
         tcsetattr(0, TCSADRAIN, &G.termios_def);
 }
References G, TCSADRAIN, and tcsetattr().
Referenced by con_escape(), doexit(), and setConMode().
do_linemode()
static void do_linemode (void) static
Definition at line 459 of file telnet.c.
 {
     G.charmode = CHM_TRY;
     G.telflags &= ~(UF_ECHO | UF_SGA);
     setConMode();
     put_iac3_IAC_x_y(DONT, TELOPT_ECHO);
     put_iac3_IAC_x_y(DONT, TELOPT_SGA);
     iac_flush();
 }
References CHM_TRY, DONT, G, iac_flush(), put_iac3_IAC_x_y, setConMode(), TELOPT_ECHO, TELOPT_SGA, UF_ECHO, and UF_SGA.
Referenced by con_escape().
doexit()
static void doexit (int ev) static
Definition at line 162 of file telnet.c.
 {
     cookmode();
     exit(ev);
 }
References cookmode(), and exit().
Referenced by con_escape(), and telnet_main().
handle_net_input()
static void handle_net_input (int len) static
Definition at line 259 of file telnet.c.
 {
     byte c;
     int i;
     int cstart = 0;
     i = 0;
     //bb_error_msg("[%u,'%.*s']", G.telstate, len, G.buf);
     if (G.telstate == TS_NORMAL) { /* most typical state */
         while (i < len) {
             c = G.buf[i];
             i++;
             if (c == IAC) /* unlikely */
                 goto got_IAC;
             if (c != '\r') /* likely */
                 continue;
             G.telstate = TS_CR;
             cstart = i;
             goto got_special;
         }
         full_write(STDOUT_FILENO, G.buf, len);
         return;
  got_IAC:
         G.telstate = TS_IAC;
         cstart = i - 1;
  got_special: ;
     }
     for (; i < len; i++) {
         c = G.buf[i];
         switch (G.telstate) {
         case TS_CR:
             /* Prev char was CR. If cur one is NUL, ignore it.
              * See RFC 1123 section 3.3.1 for discussion of telnet EOL handling.
              */
             G.telstate = TS_COPY;
             if (c == '\0')
                 break;
             /* else: fall through - need to handle CR IAC ... properly */
         case TS_COPY: /* Prev char was ordinary */
             /* Similar to NORMAL, but in TS_COPY we need to copy bytes */
             if (c == IAC)
                 G.telstate = TS_IAC;
             else {
                 G.buf[cstart++] = c;
                 if (c == '\r')
                     G.telstate = TS_CR;
             }
             break;
         case TS_IAC: /* Prev char was IAC */
             switch (c) {
             case IAC: /* IAC IAC -> one IAC */
                 G.buf[cstart++] = c;
                 G.telstate = TS_COPY;
                 break;
             case SB:
                 G.telstate = TS_SUB1;
                 break;
             case DO:
             case DONT:
             case WILL:
             case WONT:
                 G.telwish = c;
                 G.telstate = TS_OPT;
                 break;
             /* DATA MARK must be added later */
             default:
                 G.telstate = TS_COPY;
             }
             break;
         case TS_OPT: /* Prev chars were IAC WILL/WONT/DO/DONT */
             telopt(c);
             G.telstate = TS_COPY;
             break;
         case TS_SUB1: /* Subnegotiation */
         case TS_SUB2: /* Subnegotiation */
             subneg(c); /* can change G.telstate */
             break;
         }
     }
     /* We had some IACs, or CR */
     iac_flush();
     if (G.telstate == TS_COPY) /* we aren't in the middle of IAC */
         G.telstate = TS_NORMAL;
     if (cstart != 0)
         full_write(STDOUT_FILENO, G.buf, cstart);
 }
References c, DO, DONT, full_write(), G, i, IAC, iac_flush(), SB, STDOUT_FILENO, subneg(), telopt(), TS_COPY, TS_CR, TS_IAC, TS_NORMAL, TS_OPT, TS_SUB1, TS_SUB2, WILL, and WONT.
Referenced by telnet_main().
handle_net_output()
static void handle_net_output (int len) static
Definition at line 214 of file telnet.c.
 {
     byte outbuf[2 * DATABUFSIZE];
     byte *dst = outbuf;
     byte *src = (byte*)G.buf;
     byte *end = src + len;
     while (src < end) {
         byte c = *src++;
         if (c == 0x1d) {
             con_escape();
             return;
         }
         *dst = c;
         if (c == IAC)
             *++dst = c; /* IAC -> IAC IAC */
         else
         if (c == '\r' || c == '\n') {
             /* Enter key sends '\r' in raw mode and '\n' in cooked one.
              *
              * See RFC 1123 3.3.1 Telnet End-of-Line Convention.
              * Using CR LF instead of other allowed possibilities
              * like CR NUL - easier to talk to HTTP/SMTP servers.
              */
             *dst = '\r'; /* Enter -> CR LF */
             *++dst = '\n';
         }
 #if 0
 /* putty's "special commands" mode does this: */
 /* Korenix 3005 switch needs at least the backspace tweak */
         if (c == 0x08 || c == 0x7f) { /* ctrl+h || backspace */
             *dst = IAC;
             *++dst = EC;
         }
         if (c == 0x03) { /* ctrl+c */
             *dst = IAC;
             *++dst = IP;
         }
 #endif
         dst++;
     }
     if (dst - outbuf != 0)
         full_write(netfd, outbuf, dst - outbuf);
 }
References c, con_escape(), DATABUFSIZE, dst, EC, end, full_write(), G, IAC, IP, netfd, outbuf, src, and while().
Referenced by telnet_main().
iac_flush()
static void iac_flush (void) static
Definition at line 153 of file telnet.c.
 {
     if (G.iaclen != 0) {
         full_write(netfd, G.iacbuf, G.iaclen);
         G.iaclen = 0;
     }
 }
References full_write(), G, and netfd.
Referenced by do_linemode(), handle_net_input(), put_iac(), and will_charmode().
put_iac()
static void put_iac (int c) static
Definition at line 353 of file telnet.c.
 {
     int iaclen = G.iaclen;
     if (iaclen >= IACBUFSIZE) {
         iac_flush();
         iaclen = 0;
     }
     G.iacbuf[iaclen] = c; /* "... & 0xff" is implicit */
     G.iaclen = iaclen + 1;
 }
References c, G, iac_flush(), and IACBUFSIZE.
Referenced by put_iac2_msb_lsb(), and put_iac3_IAC_x_y_merged().
put_iac2_msb_lsb()
static void put_iac2_msb_lsb (unsigned x_y) static
Definition at line 364 of file telnet.c.
 {
     put_iac(x_y >> 8);  /* "... & 0xff" is implicit */
     put_iac(x_y);  /* "... & 0xff" is implicit */
 }
References put_iac().
Referenced by put_iac3_IAC_x_y_merged().
put_iac3_IAC_x_y_merged()
static void put_iac3_IAC_x_y_merged (unsigned wwdd_and_c) static
Definition at line 382 of file telnet.c.
 {
     put_iac(IAC);
     put_iac2_msb_lsb(wwdd_and_c);
 }
References IAC, put_iac(), and put_iac2_msb_lsb().
rawmode()
static void rawmode (void) static
Definition at line 608 of file telnet.c.
 {
     if (G.do_termios)
         tcsetattr(0, TCSADRAIN, &G.termios_raw);
 }
References G, TCSADRAIN, and tcsetattr().
Referenced by con_escape(), and setConMode().
setConMode()
static void setConMode (void) static
Definition at line 429 of file telnet.c.
 {
     if (G.telflags & UF_ECHO) {
         if (G.charmode == CHM_TRY) {
             G.charmode = CHM_ON;
             printf("\r\nEntering %s mode"
                 "\r\nEscape character is '^%c'.\r\n", "character", ']');
             rawmode();
         }
     } else {
         if (G.charmode != CHM_OFF) {
             G.charmode = CHM_OFF;
             printf("\r\nEntering %s mode"
                 "\r\nEscape character is '^%c'.\r\n", "line", 'C');
             cookmode();
         }
     }
 }
References CHM_OFF, CHM_ON, CHM_TRY, cookmode(), G, printf(), rawmode(), and UF_ECHO.
Referenced by do_linemode(), to_echo(), and will_charmode().
subneg()
static void subneg (byte c) static
Definition at line 581 of file telnet.c.
 {
     switch (G.telstate) {
     case TS_SUB1:
         if (c == IAC)
             G.telstate = TS_SUB2;
 #if ENABLE_FEATURE_TELNET_TTYPE
         else
         if (c == TELOPT_TTYPE && G.ttype)
             put_iac_subopt(TELOPT_TTYPE, G.ttype);
 #endif
 #if ENABLE_FEATURE_TELNET_AUTOLOGIN
         else
         if (c == TELOPT_NEW_ENVIRON && G.autologin)
             put_iac_subopt_autologin();
 #endif
         break;
     case TS_SUB2:
         if (c == SE) {
             G.telstate = TS_COPY;
             return;
         }
         G.telstate = TS_SUB1;
         break;
     }
 }
References c, G, IAC, SE, TELOPT_NEW_ENVIRON, TELOPT_TTYPE, TS_COPY, TS_SUB1, and TS_SUB2.
Referenced by handle_net_input().
telnet_main()
int telnet_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 621 of file telnet.c.
 {
     char *host;
     int port;
     int len;
     struct pollfd ufds[2];
     INIT_G();
 #if ENABLE_FEATURE_TELNET_TTYPE
     G.ttype = getenv("TERM");
 #endif
     if (tcgetattr(0, &G.termios_def) >= 0) {
         G.do_termios = 1;
         G.termios_raw = G.termios_def;
         cfmakeraw(&G.termios_raw);
     }
 #if ENABLE_FEATURE_TELNET_AUTOLOGIN
     if (1 == getopt32(argv, "al:", &G.autologin)) {
         /* Only -a without -l USER picks $USER from envvar */
         G.autologin = getenv("USER");
     }
     argv += optind;
 #else
     argv++;
 #endif
     if (!*argv)
         bb_show_usage();
     host = *argv++;
     port = *argv ? bb_lookup_port(*argv++, "tcp", 23)
         : bb_lookup_std_port("telnet", "tcp", 23);
     if (*argv) /* extra params?? */
         bb_show_usage();
     xmove_fd(create_and_connect_stream_or_die(host, port), netfd);
     printf("Connected to %s\n", host);
     setsockopt_keepalive(netfd);
 #if ENABLE_FEATURE_TELNET_WIDTH
     get_terminal_width_height(0, &G.win_width, &G.win_height);
 //TODO: support dynamic resize?
 #endif
     signal(SIGINT, record_signo);
     ufds[0].fd = STDIN_FILENO;
     ufds[0].events = POLLIN;
     ufds[1].fd = netfd;
     ufds[1].events = POLLIN;
     while (1) {
         if (poll(ufds, 2, -1) < 0) {
             /* error, ignore and/or log something, bay go to loop */
             if (bb_got_signal)
                 con_escape();
             else
                 sleep1();
             continue;
         }
 // FIXME: reads can block. Need full bidirectional buffering.
         if (ufds[0].revents) {
             len = safe_read(STDIN_FILENO, G.buf, DATABUFSIZE);
             if (len <= 0)
                 doexit(EXIT_SUCCESS);
             handle_net_output(len);
         }
         if (ufds[1].revents) {
             len = safe_read(netfd, G.buf, DATABUFSIZE);
             if (len <= 0) {
                 full_write1_str("Connection closed by foreign host\r\n");
                 doexit(EXIT_FAILURE);
             }
             handle_net_input(len);
         }
     } /* while (1) */
 }
References argv, bb_got_signal, bb_lookup_port(), bb_lookup_std_port, bb_show_usage(), cfmakeraw(), con_escape(), create_and_connect_stream_or_die(), DATABUFSIZE, doexit(), pollfd::events, EXIT_FAILURE, EXIT_SUCCESS, pollfd::fd, full_write1_str(), G, get_terminal_width_height(), getenv, getopt32(), handle_net_input(), handle_net_output(), INIT_G, netfd, optind, poll(), POLLIN, port, printf(), record_signo(), pollfd::revents, safe_read(), setsockopt_keepalive(), SIGINT, signal, sleep1(), STDIN_FILENO, tcgetattr(), and xmove_fd().
telopt()
static void telopt (byte c) static
Definition at line 553 of file telnet.c.
 {
     switch (c) {
     case TELOPT_ECHO:
         to_echo(); break;
     case TELOPT_SGA:
         to_sga(); break;
 #if ENABLE_FEATURE_TELNET_TTYPE
     case TELOPT_TTYPE:
         to_ttype(); break;
 #endif
 #if ENABLE_FEATURE_TELNET_AUTOLOGIN
     case TELOPT_NEW_ENVIRON:
         to_new_environ(); break;
 #endif
 #if ENABLE_FEATURE_TELNET_WIDTH
     case TELOPT_NAWS:
         to_naws();
         put_iac_naws(c, G.win_width, G.win_height);
         break;
 #endif
     default:
         to_notsup(c);
         break;
     }
 }
References c, G, TELOPT_ECHO, TELOPT_NAWS, TELOPT_NEW_ENVIRON, TELOPT_SGA, TELOPT_TTYPE, to_echo(), to_notsup(), and to_sga().
Referenced by handle_net_input().
to_echo()
static void to_echo (void) static
Definition at line 478 of file telnet.c.
 {
     /* if server requests ECHO, don't agree */
     if (G.telwish == DO) {
         put_iac3_IAC_x_y(WONT, TELOPT_ECHO);
         return;
     }
     if (G.telwish == DONT)
         return;
     if (G.telflags & UF_ECHO) {
         if (G.telwish == WILL)
             return;
     } else if (G.telwish == WONT)
         return;
     if (G.charmode != CHM_OFF)
         G.telflags ^= UF_ECHO;
     if (G.telflags & UF_ECHO)
         put_iac3_IAC_x_y(DO, TELOPT_ECHO);
     else
         put_iac3_IAC_x_y(DONT, TELOPT_ECHO);
     setConMode();
     full_write1_str("\r\n");  /* sudden modec */
 }
References CHM_OFF, DO, DONT, full_write1_str(), G, put_iac3_IAC_x_y, setConMode(), TELOPT_ECHO, UF_ECHO, WILL, and WONT.
Referenced by telopt().
to_notsup()
static void to_notsup (char c) static
Definition at line 470 of file telnet.c.
 {
     if (G.telwish == WILL)
         put_iac3_IAC_x_y(DONT, c);
     else if (G.telwish == DO)
         put_iac3_IAC_x_y(WONT, c);
 }
References c, DO, DONT, G, put_iac3_IAC_x_y, WILL, and WONT.
Referenced by telopt().
to_sga()
static void to_sga (void) static
Definition at line 506 of file telnet.c.
 {
     /* daemon always sends will/wont, client do/dont */
     if (G.telflags & UF_SGA) {
         if (G.telwish == WILL)
             return;
     } else if (G.telwish == WONT)
         return;
     G.telflags ^= UF_SGA; /* toggle */
     if (G.telflags & UF_SGA)
         put_iac3_IAC_x_y(DO, TELOPT_SGA);
     else
         put_iac3_IAC_x_y(DONT, TELOPT_SGA);
 }
References DO, DONT, G, put_iac3_IAC_x_y, TELOPT_SGA, UF_SGA, WILL, and WONT.
Referenced by telopt().
will_charmode()
static void will_charmode (void) static
Definition at line 448 of file telnet.c.
 {
     G.charmode = CHM_TRY;
     G.telflags |= (UF_ECHO | UF_SGA);
     setConMode();
     put_iac3_IAC_x_y(DO, TELOPT_ECHO);
     put_iac3_IAC_x_y(DO, TELOPT_SGA);
     iac_flush();
 }
References CHM_TRY, DO, G, iac_flush(), put_iac3_IAC_x_y, setConMode(), TELOPT_ECHO, TELOPT_SGA, UF_ECHO, and UF_SGA.
Referenced by con_escape().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING