Fennix Drivers: Drivers/Input/VMwareMouse/VMwareMouseDriver.cpp File Reference
VMwareMouseDriver.cpp File Reference
#include <pci.h>
#include <io.h>
#include "../../../Kernel/DAPI.hpp"
#include "../../../Kernel/Fex.hpp"
Data Structures
struct VMwareCommand
union VMwareCommand.__unnamed1__
union VMwareCommand.__unnamed3__
union VMwareCommand.__unnamed5__
union VMwareCommand.__unnamed7__
Macros
#define print(msg) KAPI->Util.DebugPrint((char *)(msg), KAPI->Info.DriverUID)
#define VMWARE_MAGIC 0x564D5868 /* hXMV */
#define VMWARE_PORT 0x5658
#define CMD_GETVERSION 0xA
#define CMD_ABSPOINTER_DATA 0x27
#define CMD_ABSPOINTER_STATUS 0x28
#define CMD_ABSPOINTER_COMMAND 0x29
#define ABSPOINTER_ENABLE 0x45414552 /* Q E A E */
#define ABSPOINTER_RELATIVE 0xF5
#define ABSPOINTER_ABSOLUTE 0x53424152 /* R A B S */
Enumerations
enum Config { READ_CONFIG = 0x20 , WRITE_CONFIG = 0x60 , READ_CONFIG = 0x20 , WRITE_CONFIG = 0x60 }
enum Ports {
DATA = 0x60 , STATUS = 0x64 , COMMAND = 0x64 , DATA = 0x60 ,
STATUS = 0x64 , COMMAND = 0x64
}
enum State {
OUTPUT_FULL = (1 << 0) , INPUT_FULL = (1 << 1) , MOUSE_BYTE = (1 << 5) , OUTPUT_FULL = (1 << 0) ,
INPUT_FULL = (1 << 1) , MOUSE_BYTE = (1 << 5)
}
Functions
int DriverEntry (void *Data)
int CallbackHandler (KernelCallback *Data)
HEAD (FexFormatType_Driver, FexOSType_Fennix, DriverEntry)
__attribute__ ((section(".extended"))) FexExtended ExtendedHeader
void CommandSend (VMwareCommand *cmd)
bool IsVMwareBackdoorAvailable (void)
void Absolute (void)
void Relative (void)
void WaitRead ()
void WaitWrite ()
void Write (uint16_t Port, uint8_t Value)
uint8_t Read ()
Variables
KernelAPI * KAPI
int MouseX = 0
int MouseY = 0
int MouseZ = 0
int MouseButton = 0
Data Structure Documentation
VMwareCommand
struct VMwareCommand
Definition at line 35 of file VMwareMouseDriver.cpp.
Data Fields
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
union VMwareCommand __unnamed__
uint32_t di
uint32_t si
VMwareCommand.__unnamed1__
union VMwareCommand.__unnamed1__
Definition at line 37 of file VMwareMouseDriver.cpp.
Data Fields
uint32_t ax
uint32_t magic
VMwareCommand.__unnamed3__
union VMwareCommand.__unnamed3__
Definition at line 42 of file VMwareMouseDriver.cpp.
Data Fields
uint32_t bx
size_t size
VMwareCommand.__unnamed5__
union VMwareCommand.__unnamed5__
Definition at line 47 of file VMwareMouseDriver.cpp.
Data Fields
uint16_t command
uint32_t cx
VMwareCommand.__unnamed7__
union VMwareCommand.__unnamed7__
Definition at line 52 of file VMwareMouseDriver.cpp.
Data Fields
uint32_t dx
uint16_t port
Macro Definition Documentation
ABSPOINTER_ABSOLUTE
#define ABSPOINTER_ABSOLUTE 0x53424152 /* R A B S */
Definition at line 71 of file VMwareMouseDriver.cpp.
ABSPOINTER_ENABLE
#define ABSPOINTER_ENABLE 0x45414552 /* Q E A E */
Definition at line 69 of file VMwareMouseDriver.cpp.
ABSPOINTER_RELATIVE
#define ABSPOINTER_RELATIVE 0xF5
Definition at line 70 of file VMwareMouseDriver.cpp.
CMD_ABSPOINTER_COMMAND
#define CMD_ABSPOINTER_COMMAND 0x29
Definition at line 67 of file VMwareMouseDriver.cpp.
CMD_ABSPOINTER_DATA
#define CMD_ABSPOINTER_DATA 0x27
Definition at line 65 of file VMwareMouseDriver.cpp.
CMD_ABSPOINTER_STATUS
#define CMD_ABSPOINTER_STATUS 0x28
Definition at line 66 of file VMwareMouseDriver.cpp.
CMD_GETVERSION
#define CMD_GETVERSION 0xA
Definition at line 64 of file VMwareMouseDriver.cpp.
print
#define print (msg) KAPI->Util.DebugPrint((char *)(msg), KAPI->Info.DriverUID)
Definition at line 29 of file VMwareMouseDriver.cpp.
VMWARE_MAGIC
#define VMWARE_MAGIC 0x564D5868 /* hXMV */
Definition at line 61 of file VMwareMouseDriver.cpp.
VMWARE_PORT
#define VMWARE_PORT 0x5658
Definition at line 62 of file VMwareMouseDriver.cpp.
Enumeration Type Documentation
Config
enum Config
Enumerator
READ_CONFIG
WRITE_CONFIG
READ_CONFIG
WRITE_CONFIG
Definition at line 139 of file VMwareMouseDriver.cpp.
 {
     READ_CONFIG = 0x20,
     WRITE_CONFIG = 0x60
 };
Ports
enum Ports
Enumerator
DATA
STATUS
COMMAND
DATA
STATUS
COMMAND
Definition at line 145 of file VMwareMouseDriver.cpp.
 {
     DATA = 0x60,
     STATUS = 0x64,
     COMMAND = 0x64,
 };
State
enum State
Enumerator
OUTPUT_FULL
INPUT_FULL
MOUSE_BYTE
OUTPUT_FULL
INPUT_FULL
MOUSE_BYTE
Definition at line 152 of file VMwareMouseDriver.cpp.
 {
     OUTPUT_FULL = (1 << 0),
     INPUT_FULL = (1 << 1),
     MOUSE_BYTE = (1 << 5)
 };
Function Documentation
__attribute__()
__attribute__ ((section(".extended")))
References CallbackHandler().
Absolute()
void Absolute (void)
Definition at line 106 of file VMwareMouseDriver.cpp.
 {
     VMwareCommand cmd;
     /* Enable */
     cmd.bx = ABSPOINTER_ENABLE;
     cmd.command = CMD_ABSPOINTER_COMMAND;
     CommandSend(&cmd);
     /* Status */
     cmd.bx = 0;
     cmd.command = CMD_ABSPOINTER_STATUS;
     CommandSend(&cmd);
     /* Read data (1) */
     cmd.bx = 1;
     cmd.command = CMD_ABSPOINTER_DATA;
     CommandSend(&cmd);
     /* Enable absolute */
     cmd.bx = ABSPOINTER_ABSOLUTE;
     cmd.command = CMD_ABSPOINTER_COMMAND;
     CommandSend(&cmd);
 }
References ABSPOINTER_ABSOLUTE, ABSPOINTER_ENABLE, CMD_ABSPOINTER_COMMAND, CMD_ABSPOINTER_DATA, CMD_ABSPOINTER_STATUS, and CommandSend().
Referenced by CallbackHandler().
CallbackHandler()
int CallbackHandler (KernelCallback * Data)
Definition at line 190 of file VMwareMouseDriver.cpp.
 {
     switch (Data->Reason)
     {
     case AcknowledgeReason:
     {
         print("Kernel acknowledged the driver.");
         break;
     }
     case ConfigurationReason:
     {
         outb(COMMAND, 0xA8);
         Write(COMMAND, READ_CONFIG);
         uint8_t Status = Read();
         Status |= 0b10;
         Write(COMMAND, WRITE_CONFIG);
         Write(DATA, Status);
         Write(COMMAND, 0xD4);
         Write(DATA, 0xF6);
         Read();
         Write(COMMAND, 0xD4);
         Write(DATA, 0xF4);
         Read();
         Absolute();
         print("VMware mouse configured.");
         break;
     }
     case FetchReason:
     {
         Data->InputCallback.Mouse.X = (MouseX * KAPI->Display.GetWidth()) / 0xFFFF;
         Data->InputCallback.Mouse.Y = (MouseY * KAPI->Display.GetHeight()) / 0xFFFF;
         Data->InputCallback.Mouse.Z = MouseZ;
         Data->InputCallback.Mouse.Buttons.Left = MouseButton & 0x20;
         Data->InputCallback.Mouse.Buttons.Right = MouseButton & 0x10;
         Data->InputCallback.Mouse.Buttons.Middle = MouseButton & 0x08;
         break;
     }
     case StopReason:
     {
         Relative();
         // TODO: UNTESTED!!!
         outb(COMMAND, 0xA8);
         Write(COMMAND, READ_CONFIG);
         uint8_t Status = Read();
         Status &= ~0b10;
         Write(COMMAND, WRITE_CONFIG);
         Write(DATA, Status);
         Write(COMMAND, 0xD4);
         Write(DATA, 0xF5);
         Read();
         print("Driver stopped.");
         break;
     }
     case InterruptReason:
     {
         uint8_t Data = inb(0x60);
         (void)Data;
         VMwareCommand cmd;
         cmd.bx = 0;
         cmd.command = CMD_ABSPOINTER_STATUS;
         CommandSend(&cmd);
         if (cmd.ax == 0xFFFF0000)
         {
             print("VMware mouse is not connected?");
             Relative();
             Absolute();
             return ERROR;
         }
         if ((cmd.ax & 0xFFFF) < 4)
             return ERROR;
         cmd.bx = 4;
         cmd.command = CMD_ABSPOINTER_DATA;
         CommandSend(&cmd);
         int flags = (cmd.ax & 0xFFFF0000) >> 16; /* Not important */
         (void)flags;
         MouseButton = (cmd.ax & 0xFFFF); /* 0x10 = Right, 0x20 = Left, 0x08 = Middle */
         MouseX = cmd.bx;                 /* Both X and Y are scaled from 0 to 0xFFFF */
         MouseY = cmd.cx;                 /* You should map these somewhere to the actual resolution. */
         MouseZ = (int8_t)cmd.dx;         /* Z is a single signed byte indicating scroll direction. */
         break;
     }
     default:
     {
         print("Unknown reason.");
         break;
     }
     }
     return OK;
 }
References Absolute(), CMD_ABSPOINTER_DATA, CMD_ABSPOINTER_STATUS, COMMAND, CommandSend(), DATA, KAPI, MouseButton, MouseX, MouseY, MouseZ, print, Read(), READ_CONFIG, Relative(), Status, Write(), and WRITE_CONFIG.
Referenced by __attribute__().
CommandSend()
void CommandSend (VMwareCommand * cmd)
Definition at line 73 of file VMwareMouseDriver.cpp.
 {
     cmd->magic = VMWARE_MAGIC;
     cmd->port = VMWARE_PORT;
     asm volatile("in %%dx, %0"
                  : "+a"(cmd->ax), "+b"(cmd->bx), "+c"(cmd->cx), "+d"(cmd->dx), "+S"(cmd->si), "+D"(cmd->di));
 }
References VMwareCommand::di, VMwareCommand::si, VMWARE_MAGIC, and VMWARE_PORT.
Referenced by Absolute(), CallbackHandler(), IsVMwareBackdoorAvailable(), and Relative().
DriverEntry()
int DriverEntry (void * Data)
Definition at line 92 of file VMwareMouseDriver.cpp.
 {
     if (!Data)
         return INVALID_KERNEL_API;
     KAPI = (KernelAPI *)Data;
     if (KAPI->Version.Major < 0 || KAPI->Version.Minor < 0 || KAPI->Version.Patch < 0)
         return KERNEL_API_VERSION_NOT_SUPPORTED;
     if (!IsVMwareBackdoorAvailable())
         return SYSTEM_NOT_SUPPORTED;
     return OK;
 }
References IsVMwareBackdoorAvailable(), and KAPI.
HEAD()
HEAD (FexFormatType_Driver , FexOSType_Fennix , DriverEntry)
IsVMwareBackdoorAvailable()
bool IsVMwareBackdoorAvailable (void)
Definition at line 81 of file VMwareMouseDriver.cpp.
 {
     VMwareCommand cmd;
     cmd.bx = ~VMWARE_MAGIC;
     cmd.command = CMD_GETVERSION;
     CommandSend(&cmd);
     if (cmd.bx != VMWARE_MAGIC || cmd.ax == 0xFFFFFFFF)
         return false;
     return true;
 }
References CMD_GETVERSION, CommandSend(), and VMWARE_MAGIC.
Referenced by DriverEntry().
Read()
uint8_t Read ()
Definition at line 181 of file VMwareMouseDriver.cpp.
 {
     WaitRead();
     return inb(Ports::DATA);
 }
References DATA, and WaitRead().
Referenced by CallbackHandler().
Relative()
void Relative (void)
Definition at line 131 of file VMwareMouseDriver.cpp.
 {
     VMwareCommand cmd;
     cmd.bx = ABSPOINTER_RELATIVE;
     cmd.command = CMD_ABSPOINTER_COMMAND;
     CommandSend(&cmd);
 }
References ABSPOINTER_RELATIVE, CMD_ABSPOINTER_COMMAND, and CommandSend().
Referenced by CallbackHandler().
WaitRead()
void WaitRead ()
Definition at line 159 of file VMwareMouseDriver.cpp.
 {
     uint64_t Timeout = 100000;
     while (Timeout--)
         if (inb(Ports::STATUS) & State::OUTPUT_FULL)
             return;
 }
References OUTPUT_FULL, and STATUS.
Referenced by Read().
WaitWrite()
void WaitWrite ()
Definition at line 167 of file VMwareMouseDriver.cpp.
 {
     uint64_t Timeout = 100000;
     while (Timeout--)
         if ((inb(Ports::STATUS) & State::INPUT_FULL) == 0)
             return;
 }
References INPUT_FULL, and STATUS.
Referenced by Write().
Write()
void Write (uint16_t Port, uint8_t Value)
Definition at line 175 of file VMwareMouseDriver.cpp.
 {
     WaitWrite();
     outb(Port, Value);
 }
References WaitWrite().
Referenced by CallbackHandler().
Variable Documentation
KAPI
KernelAPI* KAPI
Definition at line 27 of file VMwareMouseDriver.cpp.
Referenced by CallbackHandler(), and DriverEntry().
MouseButton
int MouseButton = 0
Definition at line 188 of file VMwareMouseDriver.cpp.
Referenced by CallbackHandler().
MouseX
int MouseX = 0
Definition at line 187 of file VMwareMouseDriver.cpp.
Referenced by CallbackHandler().
MouseY
int MouseY = 0
Definition at line 187 of file VMwareMouseDriver.cpp.
Referenced by CallbackHandler().
MouseZ
int MouseZ = 0
Definition at line 187 of file VMwareMouseDriver.cpp.
Referenced by CallbackHandler().