Fennix: Userspace/apps/base/busybox/networking/vconfig.c File Reference
vconfig.c File Reference
#include "libbb.h"
#include <net/if.h>
Data Structures
struct vlan_ioctl_args
union vlan_ioctl_args.u
Macros
#define VLAN_GROUP_ARRAY_LEN 4096
#define SIOCSIFVLAN 0x8983 /* Set 802.1Q VLAN options */
Enumerations
enum vlan_ioctl_cmds {
ADD_VLAN_CMD , DEL_VLAN_CMD , SET_VLAN_INGRESS_PRIORITY_CMD , SET_VLAN_EGRESS_PRIORITY_CMD ,
GET_VLAN_INGRESS_PRIORITY_CMD , GET_VLAN_EGRESS_PRIORITY_CMD , SET_VLAN_NAME_TYPE_CMD , SET_VLAN_FLAG_CMD
}
enum vlan_name_types {
VLAN_NAME_TYPE_PLUS_VID , VLAN_NAME_TYPE_RAW_PLUS_VID , VLAN_NAME_TYPE_PLUS_VID_NO_PAD , VLAN_NAME_TYPE_RAW_PLUS_VID_NO_PAD ,
VLAN_NAME_TYPE_HIGHEST
}
Functions
static const char * xfind_str (const char *table, const char *str)
int vconfig_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char cmds[] ALIGN1
Data Structure Documentation
vlan_ioctl_args
struct vlan_ioctl_args
Definition at line 54 of file vconfig.c.
Data Fields
int cmd
char device1[24]
union vlan_ioctl_args u
short vlan_qos
vlan_ioctl_args.u
union vlan_ioctl_args.u
Definition at line 58 of file vconfig.c.
Data Fields
unsigned int bind_type
char device2[24]
unsigned int flag
unsigned int name_type
unsigned int skb_priority
int VID
Macro Definition Documentation
SIOCSIFVLAN
#define SIOCSIFVLAN 0x8983 /* Set 802.1Q VLAN options */
Definition at line 71 of file vconfig.c.
VLAN_GROUP_ARRAY_LEN
#define VLAN_GROUP_ARRAY_LEN 4096
Definition at line 70 of file vconfig.c.
Enumeration Type Documentation
vlan_ioctl_cmds
enum vlan_ioctl_cmds
Enumerator
ADD_VLAN_CMD
DEL_VLAN_CMD
SET_VLAN_INGRESS_PRIORITY_CMD
SET_VLAN_EGRESS_PRIORITY_CMD
GET_VLAN_INGRESS_PRIORITY_CMD
GET_VLAN_EGRESS_PRIORITY_CMD
SET_VLAN_NAME_TYPE_CMD
SET_VLAN_FLAG_CMD
Definition at line 36 of file vconfig.c.
                      {
     ADD_VLAN_CMD,
     DEL_VLAN_CMD,
     SET_VLAN_INGRESS_PRIORITY_CMD,
     SET_VLAN_EGRESS_PRIORITY_CMD,
     GET_VLAN_INGRESS_PRIORITY_CMD,
     GET_VLAN_EGRESS_PRIORITY_CMD,
     SET_VLAN_NAME_TYPE_CMD,
     SET_VLAN_FLAG_CMD
 };
vlan_name_types
enum vlan_name_types
Enumerator
VLAN_NAME_TYPE_PLUS_VID
VLAN_NAME_TYPE_RAW_PLUS_VID
VLAN_NAME_TYPE_PLUS_VID_NO_PAD
VLAN_NAME_TYPE_RAW_PLUS_VID_NO_PAD
VLAN_NAME_TYPE_HIGHEST
Definition at line 46 of file vconfig.c.
                      {
     VLAN_NAME_TYPE_PLUS_VID, /* Name will look like:  vlan0005 */
     VLAN_NAME_TYPE_RAW_PLUS_VID, /* name will look like:  eth1.0005 */
     VLAN_NAME_TYPE_PLUS_VID_NO_PAD, /* Name will look like:  vlan5 */
     VLAN_NAME_TYPE_RAW_PLUS_VID_NO_PAD, /* Name will look like:  eth0.5 */
     VLAN_NAME_TYPE_HIGHEST
 };
Function Documentation
vconfig_main()
int vconfig_main (int argc, char ** argv)
Definition at line 113 of file vconfig.c.
 {
     struct vlan_ioctl_args ifr;
     const char *p;
     int fd;
     memset(&ifr, 0, sizeof(ifr));
     ++argv;
     if (!argv[0])
         bb_show_usage();
     p = xfind_str(cmds + 2, argv[0]);
     ifr.cmd = *p;
     if (argc != p[-1])
         bb_show_usage();
     if (ifr.cmd == SET_VLAN_NAME_TYPE_CMD) {
         /* set_name_type */
         ifr.u.name_type = *xfind_str(name_types + 1, argv[1]);
     } else {
         strncpy_IFNAMSIZ(ifr.device1, argv[1]);
         p = argv[2];
         /* I suppose one could try to combine some of the function calls below,
          * since ifr.u.flag, ifr.u.VID, and ifr.u.skb_priority are all same-sized
          * (unsigned) int members of a unions.  But because of the range checking,
          * doing so wouldn't save that much space and would also make maintenance
          * more of a pain.
          */
         if (ifr.cmd == SET_VLAN_FLAG_CMD) {
             /* set_flag */
             ifr.u.flag = xatou_range(p, 0, 1);
             /* DM: in order to set reorder header, qos must be set */
             ifr.vlan_qos = xatou_range(argv[3], 0, 7);
         } else if (ifr.cmd == ADD_VLAN_CMD) {
             /* add */
             ifr.u.VID = xatou_range(p, 0, VLAN_GROUP_ARRAY_LEN - 1);
         } else if (ifr.cmd != DEL_VLAN_CMD) {
             /* set_{egress|ingress}_map */
             ifr.u.skb_priority = xatou(p);
             ifr.vlan_qos = xatou_range(argv[3], 0, 7);
         }
     }
     fd = xsocket(AF_INET, SOCK_STREAM, 0);
     ioctl_or_perror_and_die(fd, SIOCSIFVLAN, &ifr,
                         "ioctl error for %s", argv[0]);
     return 0;
 }
References ADD_VLAN_CMD, AF_INET, argc, argv, bb_show_usage(), DEL_VLAN_CMD, fd, ifr, ioctl_or_perror_and_die(), memset, p, SET_VLAN_FLAG_CMD, SET_VLAN_NAME_TYPE_CMD, SIOCSIFVLAN, SOCK_STREAM, strncpy_IFNAMSIZ(), VLAN_GROUP_ARRAY_LEN, xatou(), xfind_str(), and xsocket().
xfind_str()
static const char* xfind_str (const char * table, const char * str) static
Definition at line 76 of file vconfig.c.
 {
     while (strcasecmp(str, table + 1) != 0) {
         if (!table[0])
             bb_show_usage();
         table += table[0];
     }
     return table - 1;
 }
References bb_show_usage(), str, strcasecmp, and table.
Referenced by vconfig_main().
Variable Documentation
ALIGN1
const char name_types [] ALIGN1 static
Initial value:
= {
    4, ADD_VLAN_CMD, 7,
    'a','d','d',0,
    3, DEL_VLAN_CMD, 7,
    'r','e','m',0,
    3, SET_VLAN_NAME_TYPE_CMD, 17,
    's','e','t','_','n','a','m','e','_','t','y','p','e',0,
    5, SET_VLAN_FLAG_CMD, 12,
    's','e','t','_','f','l','a','g',0,
    5, SET_VLAN_EGRESS_PRIORITY_CMD, 18,
    's','e','t','_','e','g','r','e','s','s','_','m','a','p',0,
    5, SET_VLAN_INGRESS_PRIORITY_CMD, 0,
    's','e','t','_','i','n','g','r','e','s','s','_','m','a','p',0,
}
Definition at line 86 of file vconfig.c.