Fennix Userspace: Userspace/apps/base/bash/lib/readline/util.c File Reference
util.c File Reference
#include <sys/types.h>
#include <fcntl.h>
#include "posixjmp.h"
#include "ansi_stdlib.h"
#include <stdio.h>
#include <ctype.h>
#include "rldefs.h"
#include "rlmbutil.h"
#include "readline.h"
#include "rlprivate.h"
#include "xmalloc.h"
#include "rlshell.h"
Macros
#define READLINE_LIBRARY
#define FUNCTION_FOR_MACRO(f) int (f) (int c) { return f (c); }
Functions
int rl_alphabetic (int c)
int _rl_abort_internal (void)
int rl_abort (int count, int key)
int _rl_null_function (int count, int key)
int rl_tty_status (int count, int key)
char * rl_copy_text (int from, int to)
void rl_extend_line_buffer (int len)
int rl_tilde_expand (int ignore, int key)
void _rl_ttymsg (char *format, arg1, arg2)
void _rl_errmsg (char *format, arg1, arg2)
char * _rl_strindex (const char *s1, const char *s2)
char * _rl_strpbrk (const char *string1, const char *string2)
int _rl_strnicmp (const char *string1, const char *string2, int count)
int _rl_stricmp (const char *string1, const char *string2)
int _rl_qsort_string_compare (char **s1, char **s2)
void rl_free (void *mem)
char * _rl_savestring (const char *s)
Variables
int _rl_allow_pathname_alphabetic_chars = 0
static const char *const pathname_alphabetic_chars = "/-_=~.#$"
Macro Definition Documentation
FUNCTION_FOR_MACRO
#define FUNCTION_FOR_MACRO (f) int (f) (int c) { return f (c); }
Definition at line 438 of file util.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file util.c.
Function Documentation
_rl_abort_internal()
int _rl_abort_internal (void)
Definition at line 99 of file util.c.
 {
   if (RL_ISSTATE (RL_STATE_TIMEOUT) == 0)
     rl_ding ();         /* Don't ring the bell on a timeout */
   rl_clear_message ();
   _rl_reset_argument ();
   rl_clear_pending_input ();
   rl_deactivate_mark ();
   while (rl_executing_macro)
     _rl_pop_executing_macro ();
   _rl_kill_kbd_macro ();
   RL_UNSETSTATE (RL_STATE_MULTIKEY);    /* XXX */
   rl_last_func = (rl_command_func_t *)NULL;
   _rl_longjmp (_rl_top_level, 1);
   return (0);
 }
References _rl_kill_kbd_macro(), _rl_longjmp, _rl_pop_executing_macro(), _rl_reset_argument(), _rl_top_level, NULL, rl_clear_message(), rl_clear_pending_input(), rl_deactivate_mark(), rl_ding(), rl_executing_macro, RL_ISSTATE, rl_last_func, RL_STATE_MULTIKEY, RL_STATE_TIMEOUT, and RL_UNSETSTATE.
Referenced by _rl_dispatch_callback(), _rl_dispatch_subseq(), _rl_timeout_handle(), _rl_with_macro_input(), get_y_or_n(), rl_abort(), rl_call_last_kbd_macro(), rl_digit_loop(), rl_end_kbd_macro(), rl_start_kbd_macro(), rl_vi_yank_pop(), rl_yank(), and rl_yank_pop().
_rl_errmsg()
void _rl_errmsg (char * format, arg1 , arg2)
Definition at line 304 of file util.c.
 {
   fprintf (stderr, "readline: ");
   fprintf (stderr, format, arg1, arg2);
   fprintf (stderr, "\n");
 }
References format(), fprintf(), and stderr.
_rl_null_function()
int _rl_null_function (int count, int key)
Definition at line 127 of file util.c.
 {
   return 0;
 }
Referenced by rl_generic_bind().
_rl_qsort_string_compare()
int _rl_qsort_string_compare (char ** s1, char ** s2)
Definition at line 422 of file util.c.
 {
 #if defined (HAVE_STRCOLL)
   return (strcoll (*s1, *s2));
 #else
   int result;
   result = **s1 - **s2;
   if (result == 0)
     result = strcmp (*s1, *s2);
   return result;
 #endif
 }
References s1, s2, strcmp, and strcoll().
Referenced by compute_lcd_of_matches(), remove_duplicate_matches(), rl_display_match_list(), and rl_funmap_names().
_rl_savestring()
char* _rl_savestring (const char * s)
Definition at line 461 of file util.c.
 {
   return (strcpy ((char *)xmalloc (1 + (int)strlen (s)), (s)));
 }
References s, strcpy(), strlen(), and xmalloc.
_rl_stricmp()
int _rl_stricmp (const char * string1, const char * string2)
Definition at line 397 of file util.c.
 {
   register const char *s1;
   register const char *s2;
   register int d;
   s1 = string1;
   s2 = string2;
   if (s1 == s2)
     return 0;
   while ((d = _rl_to_lower (*s1) - _rl_to_lower (*s2)) == 0)
     {
       if (*s1++ == '\0')
         return 0;
       s2++;
     }
   return (d);
 }
References _rl_to_lower(), s1, and s2.
Referenced by _rl_get_keymap_by_name(), _rl_get_string_variable_value(), bool_to_int(), find_boolean_var(), find_string_var(), hack_special_boolean_var(), handle_parser_directive(), parser_if(), rl_named_function(), rl_parse_and_bind(), stat_char(), and sv_bell_style().
_rl_strindex()
char* _rl_strindex (const char * s1, const char * s2)
Definition at line 322 of file util.c.
 {
   register int i, l, len;
   for (i = 0, l = strlen (s2), len = strlen (s1); (len - i) >= l; i++)
     if (_rl_strnicmp (s1 + i, s2, l) == 0)
       return ((char *) (s1 + i));
   return ((char *)NULL);
 }
References _rl_strnicmp(), i, l, NULL, s1, s2, and strlen().
Referenced by substring_member_of_array().
_rl_strnicmp()
int _rl_strnicmp (const char * string1, const char * string2, int count)
Definition at line 370 of file util.c.
 {
   register const char *s1;
   register const char *s2;
   register int d;
   if (count <= 0 || (string1 == string2))
     return 0;
   s1 = string1;
   s2 = string2;
   do
     {
       d = _rl_to_lower (*s1) - _rl_to_lower (*s2);  /* XXX - cast to unsigned char? */
       if (d != 0)
     return d;
       if (*s1++ == '\0')
         break;
       s2++;
     }
   while (--count != 0);
   return (0);
 }
References _rl_to_lower(), count, s1, and s2.
Referenced by _rl_strindex(), complete_fncmp(), parser_if(), and sv_editmode().
_rl_strpbrk()
char* _rl_strpbrk (const char * string1, const char * string2)
Definition at line 336 of file util.c.
 {
   register const char *scan;
 #if defined (HANDLE_MULTIBYTE)
   mbstate_t ps;
   register int i, v;
   memset (&ps, 0, sizeof (mbstate_t));
 #endif
   for (; *string1; string1++)
     {
       for (scan = string2; *scan; scan++)
     {
       if (*string1 == *scan)
         return ((char *)string1);
     }
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       v = _rl_get_char_len (string1, &ps);
       if (v > 1)
         string1 += v - 1;   /* -1 to account for auto-increment in loop */
     }
 #endif
     }
   return ((char *)NULL);
 }
References i, MB_CUR_MAX, memset(), NULL, and rl_byte_oriented.
Referenced by make_quoted_replacement().
_rl_ttymsg()
void _rl_ttymsg (char * format, arg1 , arg2)
Definition at line 293 of file util.c.
 {
   fprintf (stderr, "readline: ");
   fprintf (stderr, format, arg1, arg2);
   fprintf (stderr, "\n");
   rl_forced_update_display ();
 }
References format(), fprintf(), rl_forced_update_display(), and stderr.
rl_abort()
int rl_abort (int count, int key)
Definition at line 121 of file util.c.
 {
   return (_rl_abort_internal ());
 }
References _rl_abort_internal().
Referenced by _rl_isearch_dispatch().
rl_alphabetic()
int rl_alphabetic (int c)
Definition at line 73 of file util.c.
 {
   if (_rl_alphabetic_p (c))
     return (1);
   return (_rl_allow_pathname_alphabetic_chars &&
         strchr (pathname_alphabetic_chars, c) != NULL);
 }
References _rl_allow_pathname_alphabetic_chars, _rl_alphabetic_p, c, NULL, pathname_alphabetic_chars, and strchr().
Referenced by alphabetic().
rl_copy_text()
char* rl_copy_text (int from, int to)
Definition at line 147 of file util.c.
 {
   register int length;
   char *copy;
   /* Fix it if the caller is confused. */
   if (from > to)
     SWAP (from, to);
   length = to - from;
   copy = (char *)xmalloc (1 + length);
   strncpy (copy, rl_line_buffer + from, length);
   copy[length] = '\0';
   return (copy);
 }
References rl_line_buffer, strncpy(), SWAP, and xmalloc.
Referenced by region_kill_internal(), rl_complete_internal(), rl_delete_text(), rl_kill_text(), rl_menu_complete(), rl_modifying(), rl_old_menu_complete(), and rl_transpose_words().
rl_extend_line_buffer()
void rl_extend_line_buffer (int len)
Definition at line 166 of file util.c.
 {
   while (len >= rl_line_buffer_len)
     {
       rl_line_buffer_len += DEFAULT_BUFFER_SIZE;
       rl_line_buffer = (char *)xrealloc (rl_line_buffer, rl_line_buffer_len);
     }
   _rl_set_the_line ();
 }
References _rl_set_the_line(), DEFAULT_BUFFER_SIZE, rl_line_buffer, rl_line_buffer_len, and xrealloc.
Referenced by rl_change_case(), rl_domove_motion_callback(), rl_insert_text(), and rl_replace_line().
rl_free()
void rl_free (void * mem)
Definition at line 451 of file util.c.
 {
   if (mem)
     free (mem);
 }
References free, and mem.
rl_tilde_expand()
int rl_tilde_expand (int ignore, int key)
Definition at line 180 of file util.c.
 {
   register int start, end;
   char *homedir, *temp;
   int len;
   end = rl_point;
   start = end - 1;
   if (rl_point == rl_end && rl_line_buffer[rl_point] == '~')
     {
       homedir = tilde_expand ("~");
       _rl_replace_text (homedir, start, end);
       xfree (homedir);
       return (0);
     }
   else if (start >= 0 && rl_line_buffer[start] != '~')
     {
       for (; start >= 0 && !whitespace (rl_line_buffer[start]); start--)
         ;
       start++;
     }
   else if (start < 0)
     start = 0;
   end = start;
   do
     end++;
   while (whitespace (rl_line_buffer[end]) == 0 && end < rl_end);
   if (whitespace (rl_line_buffer[end]) || end >= rl_end)
     end--;
   /* If the first character of the current word is a tilde, perform
      tilde expansion and insert the result.  If not a tilde, do
      nothing. */
   if (rl_line_buffer[start] == '~')
     {
       len = end - start + 1;
       temp = (char *)xmalloc (len + 1);
       strncpy (temp, rl_line_buffer + start, len);
       temp[len] = '\0';
       homedir = tilde_expand (temp);
       xfree (temp);
       _rl_replace_text (homedir, start, end);
       xfree (homedir);
     }
   return (0);
 }
References _rl_replace_text(), end, rl_end, rl_line_buffer, rl_point, start, strncpy(), tilde_expand(), whitespace, xfree, and xmalloc.
Referenced by rl_vi_tilde_expand().
rl_tty_status()
int rl_tty_status (int count, int key)
Definition at line 133 of file util.c.
 {
 #if defined (TIOCSTAT)
   ioctl (1, TIOCSTAT, (char *)0);
   rl_refresh_line (count, key);
 #else
   rl_ding ();
 #endif
   return 0;
 }
References count, ioctl(), rl_ding(), and rl_refresh_line().
Variable Documentation
_rl_allow_pathname_alphabetic_chars
int _rl_allow_pathname_alphabetic_chars = 0
Definition at line 69 of file util.c.
Referenced by rl_alphabetic().
pathname_alphabetic_chars
const char* const pathname_alphabetic_chars = "/-_=~.#$" static
Definition at line 70 of file util.c.
Referenced by rl_alphabetic().