Fennix Userspace: Userspace/libc/include/sys/stat.h File Reference
stat.h File Reference
Macros
#define dev_t __dev_t
#define ino_t __ino_t
#define mode_t __mode_t
#define off_t __off_t
Typedefs
typedef unsigned int __dev_t
typedef unsigned short __ino_t
typedef unsigned short __mode_t
typedef long __off_t
Functions
int mkdir (const char *path, mode_t mode)
int remove (const char *pathname)
int rename (const char *oldpath, const char *newpath)
Macro Definition Documentation
dev_t
#define dev_t __dev_t
Definition at line 9 of file stat.h.
ino_t
#define ino_t __ino_t
Definition at line 10 of file stat.h.
mode_t
#define mode_t __mode_t
Definition at line 11 of file stat.h.
off_t
#define off_t __off_t
Definition at line 12 of file stat.h.
Typedef Documentation
__dev_t
typedef unsigned int __dev_t
Definition at line 4 of file stat.h.
__ino_t
typedef unsigned short __ino_t
Definition at line 5 of file stat.h.
__mode_t
typedef unsigned short __mode_t
Definition at line 6 of file stat.h.
__off_t
typedef long __off_t
Definition at line 7 of file stat.h.
Function Documentation
mkdir()
int mkdir (const char * path, mode_t mode)
Definition at line 5 of file sys_stat.c.
 {
     return 0;
 }
Referenced by M_MakeDirectory(), and prepare().
remove()
int remove (const char * pathname)
Definition at line 10 of file sys_stat.c.
 {
     return 0;
 }
Referenced by G_DoSaveGame().
rename()
int rename (const char * oldpath, const char * newpath)
Definition at line 15 of file sys_stat.c.
 {
     return 0;
 }
Referenced by G_DoSaveGame().