Fennix Userspace: Userspace/apps/base/bash/lib/sh/setlinebuf.c File Reference
setlinebuf.c File Reference
#include <config.h>
#include <stdio.h>
#include <xmalloc.h>
Macros
#define LBUF_BUFSIZE BUFSIZ
Functions
int sh_setlinebuf (FILE *stream)
Variables
static char * stdoutbuf = 0
static char * stderrbuf = 0
Macro Definition Documentation
LBUF_BUFSIZE
#define LBUF_BUFSIZE BUFSIZ
Definition at line 30 of file setlinebuf.c.
Function Documentation
sh_setlinebuf()
int sh_setlinebuf (FILE * stream)
Definition at line 38 of file setlinebuf.c.
 {
 #if !defined (HAVE_SETLINEBUF) && !defined (HAVE_SETVBUF)
   return (0);
 #endif
 #if defined (HAVE_SETVBUF)
   char *local_linebuf;
 #if defined (USING_BASH_MALLOC)
   if (stream == stdout && stdoutbuf == 0)
     local_linebuf = stdoutbuf = (char *)xmalloc (LBUF_BUFSIZE);
   else if (stream == stderr && stderrbuf == 0)
     local_linebuf = stderrbuf = (char *)xmalloc (LBUF_BUFSIZE);
   else
     local_linebuf = (char *)NULL;   /* let stdio handle it */
 #else
   local_linebuf = (char *)NULL;
 #endif
   return (setvbuf (stream, local_linebuf, _IOLBF, LBUF_BUFSIZE));
 #else /* !HAVE_SETVBUF */
   setlinebuf (stream);
   return (0);
 #endif /* !HAVE_SETVBUF */
 }
References _IOLBF, LBUF_BUFSIZE, NULL, setlinebuf(), setvbuf(), stderr, stderrbuf, stdout, stdoutbuf, and xmalloc.
Referenced by command_substitute(), do_piping(), and shell_initialize().
Variable Documentation
stderrbuf
char* stderrbuf = 0 static
Definition at line 34 of file setlinebuf.c.
Referenced by sh_setlinebuf().
stdoutbuf
char* stdoutbuf = 0 static
Definition at line 33 of file setlinebuf.c.
Referenced by sh_setlinebuf().