Fennix Userspace: Userspace/mlibc/options/posix/include/bits/posix/posix_signal.h File Reference
posix_signal.h File Reference
#include <bits/ansi/time_t.h>
#include <bits/ansi/timespec.h>
#include <bits/posix/pthread_t.h>
#include <bits/sigset_t.h>
#include <stddef.h>
#include <stdint.h>
#include <mlibc-config.h>
Data Structures
struct _libc_fpxreg
struct _libc_xmmreg
struct _libc_fpstate
Macros
#define FPE_INTDIV 1 /* integer divide by zero */
#define FPE_INTOVF 2 /* integer overflow */
#define FPE_FLTDIV 3 /* floating point divide by zero */
#define FPE_FLTOVF 4 /* floating point overflow */
#define FPE_FLTUND 5 /* floating point underflow */
#define FPE_FLTRES 6 /* floating point inexact result */
#define FPE_FLTINV 7 /* floating point invalid operation */
#define FPE_FLTSUB 8 /* subscript out of range */
#define TRAP_BRKPT 1 /* process breakpoint */
#define TRAP_TRACE 2 /* process trace trap */
#define FPE_INTDIV 1 /* integer divide by zero */
#define FPE_INTOVF 2 /* integer overflow */
#define FPE_FLTDIV 3 /* floating point divide by zero */
#define FPE_FLTOVF 4 /* floating point overflow */
#define FPE_FLTUND 5 /* floating point underflow */
#define FPE_FLTRES 6 /* floating point inexact result */
#define FPE_FLTINV 7 /* floating point invalid operation */
#define FPE_FLTSUB 8 /* subscript out of range */
#define TRAP_BRKPT 1 /* process breakpoint */
#define TRAP_TRACE 2 /* process trace trap */
Typedefs
typedef struct _libc_fpstate * fpregset_t
typedef unsigned long int greg_t
Functions
int sigsuspend (const sigset_t *)
int sigprocmask (int, const sigset_t *__restrict, sigset_t *__restrict)
int pthread_sigmask (int, const sigset_t *__restrict, sigset_t *__restrict)
int pthread_kill (pthread_t, int)
int sigaction (int, const struct sigaction *__restrict, struct sigaction *__restrict)
int sigpending (sigset_t *)
int siginterrupt (int sig, int flag)
int sigaltstack (const stack_t *__restrict ss, stack_t *__restrict oss)
int kill (pid_t, int)
int killpg (int, int)
int sigtimedwait (const sigset_t *__restrict set, siginfo_t *__restrict info, const struct timespec *__restrict timeout)
int sigwait (const sigset_t *__restrict set, int *__restrict sig)
int sigwaitinfo (const sigset_t *__restrict set, siginfo_t *__restrict info)
Data Structure Documentation
_libc_fpxreg
struct _libc_fpxreg
Definition at line 31 of file posix_signal.h.
Data Fields
unsigned short int __glibc_reserved1[3]
unsigned short int exponent
unsigned short int significand[4]
_libc_xmmreg
struct _libc_xmmreg
Definition at line 37 of file posix_signal.h.
Data Fields
uint32_t element[4]
_libc_fpstate
struct _libc_fpstate
Definition at line 41 of file posix_signal.h.
Data Fields
uint32_t __glibc_reserved1[24]
struct _libc_fpxreg _st[8]
struct _libc_xmmreg _xmm[16]
uint16_t cwd
uint64_t dp
uint16_t fop
uint16_t ftw
uint32_t mxcr_mask
uint32_t mxcsr
uint64_t rip
int16_t swd
Macro Definition Documentation
FPE_FLTDIV [1/2]
#define FPE_FLTDIV 3 /* floating point divide by zero */
Definition at line 62 of file posix_signal.h.
FPE_FLTDIV [2/2]
#define FPE_FLTDIV 3 /* floating point divide by zero */
Definition at line 62 of file posix_signal.h.
FPE_FLTINV [1/2]
#define FPE_FLTINV 7 /* floating point invalid operation */
Definition at line 66 of file posix_signal.h.
FPE_FLTINV [2/2]
#define FPE_FLTINV 7 /* floating point invalid operation */
Definition at line 66 of file posix_signal.h.
FPE_FLTOVF [1/2]
#define FPE_FLTOVF 4 /* floating point overflow */
Definition at line 63 of file posix_signal.h.
FPE_FLTOVF [2/2]
#define FPE_FLTOVF 4 /* floating point overflow */
Definition at line 63 of file posix_signal.h.
FPE_FLTRES [1/2]
#define FPE_FLTRES 6 /* floating point inexact result */
Definition at line 65 of file posix_signal.h.
FPE_FLTRES [2/2]
#define FPE_FLTRES 6 /* floating point inexact result */
Definition at line 65 of file posix_signal.h.
FPE_FLTSUB [1/2]
#define FPE_FLTSUB 8 /* subscript out of range */
Definition at line 67 of file posix_signal.h.
FPE_FLTSUB [2/2]
#define FPE_FLTSUB 8 /* subscript out of range */
Definition at line 67 of file posix_signal.h.
FPE_FLTUND [1/2]
#define FPE_FLTUND 5 /* floating point underflow */
Definition at line 64 of file posix_signal.h.
FPE_FLTUND [2/2]
#define FPE_FLTUND 5 /* floating point underflow */
Definition at line 64 of file posix_signal.h.
FPE_INTDIV [1/2]
#define FPE_INTDIV 1 /* integer divide by zero */
Definition at line 60 of file posix_signal.h.
FPE_INTDIV [2/2]
#define FPE_INTDIV 1 /* integer divide by zero */
Definition at line 60 of file posix_signal.h.
FPE_INTOVF [1/2]
#define FPE_INTOVF 2 /* integer overflow */
Definition at line 61 of file posix_signal.h.
FPE_INTOVF [2/2]
#define FPE_INTOVF 2 /* integer overflow */
Definition at line 61 of file posix_signal.h.
TRAP_BRKPT [1/2]
#define TRAP_BRKPT 1 /* process breakpoint */
Definition at line 69 of file posix_signal.h.
TRAP_BRKPT [2/2]
#define TRAP_BRKPT 1 /* process breakpoint */
Definition at line 69 of file posix_signal.h.
TRAP_TRACE [1/2]
#define TRAP_TRACE 2 /* process trace trap */
Definition at line 70 of file posix_signal.h.
TRAP_TRACE [2/2]
#define TRAP_TRACE 2 /* process trace trap */
Definition at line 70 of file posix_signal.h.
Typedef Documentation
fpregset_t
typedef struct _libc_fpstate* fpregset_t
Definition at line 55 of file posix_signal.h.
greg_t
typedef unsigned long int greg_t
Definition at line 58 of file posix_signal.h.
Function Documentation
kill()
int kill (pid_t pid, int number)
Definition at line 68 of file posix_signal.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_kill, -1);
     if(int e = mlibc::sys_kill(pid, number); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_kill().
Referenced by child_fn(), killpg(), and main().
killpg()
int killpg (int pgrp, int sig)
Definition at line 77 of file posix_signal.cpp.
{
     if(pgrp > 1) {
         return kill(-pgrp, sig);
     }
     errno = EINVAL;
     return -1;
 }
References EINVAL, errno, and kill().
pthread_kill()
int pthread_kill (pthread_t thread, int sig)
Definition at line 29 of file posix_signal.cpp.
{
     auto tcb = reinterpret_cast<Tcb *>(thread);
     auto pid = getpid();
     if(!mlibc::sys_tgkill) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     if(int e = mlibc::sys_tgkill(pid, tcb->tid, sig); e) {
         return e;
     }
     return 0;
 }
References ENOSYS, getpid(), MLIBC_MISSING_SYSDEP, and mlibc::sys_tgkill().
Referenced by main().
pthread_sigmask()
int pthread_sigmask (int , const sigset_t * __restrict, sigset_t * __restrict)
sigaction()
int sigaction (int , const struct sigaction * __restrict, struct sigaction * __restrict)
sigaltstack()
int sigaltstack (const stack_t *__restrict ss, stack_t *__restrict oss)
Definition at line 120 of file posix_signal.cpp.
{
     if (ss && ss->ss_size < MINSIGSTKSZ && !(ss->ss_flags & SS_DISABLE)) {
         errno = ENOMEM;
         return -1;
     }
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigaltstack, -1);
     if (int e = mlibc::sys_sigaltstack(ss, oss); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References ENOMEM, errno, MINSIGSTKSZ, MLIBC_CHECK_OR_ENOSYS, SS_DISABLE, and mlibc::sys_sigaltstack().
Referenced by main().
siginterrupt()
int siginterrupt (int sig, int flag)
Definition at line 54 of file posix_signal.cpp.
{
     int ret;
     struct sigaction act;
     sigaction(sig, NULL, &act);
     if (flag)
         act.sa_flags &= ~SA_RESTART;
     else
         act.sa_flags |= SA_RESTART;
     ret = sigaction(sig, &act, NULL);
     return ret;
 }
References NULL, ret, sigaction::sa_flags, SA_RESTART, and sigaction().
sigpending()
int sigpending (sigset_t *)
Definition at line 115 of file posix_signal.cpp.
{
     __ensure(!"sigpending() not implemented");
     __builtin_unreachable();
 }
References __ensure.
sigprocmask()
int sigprocmask (int , const sigset_t * __restrict, sigset_t * __restrict)
sigsuspend()
int sigsuspend (const sigset_t * sigmask)
Definition at line 10 of file posix_signal.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigsuspend, -1);
     // This is guaranteed to return an error (EINTR most probably)
     errno = mlibc::sys_sigsuspend(sigmask);
     return -1;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sigmask, and mlibc::sys_sigsuspend().
Referenced by worker().
sigtimedwait()
int sigtimedwait (const sigset_t *__restrict set, siginfo_t *__restrict info, const struct timespec *__restrict timeout)
Definition at line 86 of file posix_signal.cpp.
{
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigtimedwait, -1);
     int signo;
     if (int e = sysdep(set, info, timeout, &signo)) {
         errno = e;
         return -1;
     }
     return signo;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_sigtimedwait(), and mlibc::timeout.
Referenced by parent_fn(), and sigwaitinfo().
sigwait()
int sigwait (const sigset_t *__restrict set, int *__restrict sig)
Definition at line 104 of file posix_signal.cpp.
{
     if (int e = sigwaitinfo(set, nullptr); e < 0) {
         return e;
     } else {
         if (sig)
             *sig = e;
         return 0;
     }
 }
References sigwaitinfo().
Referenced by parent_fn().
sigwaitinfo()
int sigwaitinfo (const sigset_t *__restrict set, siginfo_t *__restrict info)
Definition at line 99 of file posix_signal.cpp.
{
     // NOTE: This assumes the sysdep behavior noted in mlibc/posix-sysdeps.hpp
     return sigtimedwait(set, info, nullptr);
 }
References sigtimedwait().
Referenced by parent_fn(), and sigwait().