Fennix: Memory::PageTable Class Reference
Memory::PageTable Class Reference
#include <table.hpp>
Public Member Functions
void Update ()
Update CR3 with this PageTable.
PageTable * Fork ()
Fork this PageTable.
void * __getPhysical (void *Address)
template<typename T >
T Get (T Address)
Get the Physical Address of a virtual address.
Detailed Description
Definition at line 499 of file table.hpp.
Member Function Documentation
__getPhysical()
void * Memory::PageTable::__getPhysical (void * Address)
Definition at line 84 of file page_table.cpp.
     {
         Virtual vmm(this);
         void *PhysAddr = vmm.GetPhysical((void *)Address);
         return PhysAddr;
     }
References Address, and Memory::Virtual::GetPhysical().
Referenced by Get().
Fork()
PageTable * Memory::PageTable::Fork ()
Fork this PageTable.
Returns
A new PageTable with the same content
Definition at line 19 of file page_table.cpp.
     {
         PageTable *NewTable = (PageTable *)KernelAllocator.RequestPages(TO_PAGES(sizeof(PageTable)));
         // memset(NewTable, 0, sizeof(PageTable));
         // CreatePageTable(NewTable);
         memcpy(NewTable, this, sizeof(PageTable));
         debug("Forking page table %#lx to %#lx", this, NewTable);
 #if defined(a64)
         for (size_t i = 0; i < sizeof(Entries) / sizeof(Entries[0]); i++)
         {
             PageMapLevel4 *PML4 = &Entries[i];
             PageMapLevel4 *NewPML4 = &NewTable->Entries[i];
             if (!PML4->Present)
                 continue;
             PageDirectoryPointerTableEntryPtr *ptrPDPT = (PageDirectoryPointerTableEntryPtr *)(PML4->GetAddress() << 12);
             PageDirectoryPointerTableEntryPtr *ptrNewPDPT = (PageDirectoryPointerTableEntryPtr *)KernelAllocator.RequestPage();
             NewPML4->SetAddress((uintptr_t)ptrNewPDPT >> 12);
             for (size_t j = 0; j < sizeof(ptrPDPT->Entries) / sizeof(ptrPDPT->Entries[0]); j++)
             {
                 PageDirectoryPointerTableEntry *PDPT = &ptrPDPT->Entries[j];
                 PageDirectoryPointerTableEntry *NewPDPT = &ptrNewPDPT->Entries[j];
                 *NewPDPT = *PDPT;
                 if (!PDPT->Present)
                     continue;
                 if (PDPT->PageSize)
                     continue;
                 PageDirectoryEntryPtr *ptrPDE = (PageDirectoryEntryPtr *)(PDPT->GetAddress() << 12);
                 PageDirectoryEntryPtr *ptrNewPDE = (PageDirectoryEntryPtr *)KernelAllocator.RequestPage();
                 NewPDPT->SetAddress((uintptr_t)ptrNewPDE >> 12);
                 for (size_t k = 0; k < sizeof(ptrPDE->Entries) / sizeof(ptrPDE->Entries[0]); k++)
                 {
                     PageDirectoryEntry *PDE = &ptrPDE->Entries[k];
                     PageDirectoryEntry *NewPDE = &ptrNewPDE->Entries[k];
                     *NewPDE = *PDE;
                     if (!PDE->Present)
                         continue;
                     if (PDE->PageSize)
                         continue;
                     PageTableEntryPtr *ptrPTE = (PageTableEntryPtr *)(PDE->GetAddress() << 12);
                     PageTableEntryPtr *ptrNewPTE = (PageTableEntryPtr *)KernelAllocator.RequestPage();
                     NewPDE->SetAddress((uintptr_t)ptrNewPTE >> 12);
                     for (size_t l = 0; l < sizeof(ptrPTE->Entries) / sizeof(ptrPTE->Entries[0]); l++)
                     {
                         PageTableEntry *PTE = &ptrPTE->Entries[l];
                         PageTableEntry *NewPTE = &ptrNewPTE->Entries[l];
                         *NewPTE = *PTE;
                     }
                 }
             }
         }
 #else
 #error "PageTable::Fork() not implemented for other architectures"
 #endif
         debug("Forked page table %#lx to %#lx", this, NewTable);
         return NewTable;
     }
References debug, Entries, Memory::PageDirectoryEntryPtr::Entries, Memory::PageDirectoryPointerTableEntryPtr::Entries, Memory::PageDirectoryPointerTableEntry::GetAddress(), i, j, k, KernelAllocator, l, memcpy, PDE, PML4, PTE, Memory::PageDirectoryEntry::SetAddress(), Memory::PageDirectoryPointerTableEntry::SetAddress(), Memory::PageMapLevel4::SetAddress(), and TO_PAGES.
Referenced by linux_fork(), and sys_fork().
Get()
template<typename T > T Memory::PageTable::Get (T Address) inline
Get the Physical Address of a virtual address.
This function will return the physical address of a virtual address and not the virtual address of the current page table. This is intentional because the kernel page table has 1:1 mapping for the free memory.
Template Parameters
T
Parameters
Address The virtual address
Returns
The physical address
Definition at line 537 of file table.hpp.
         {
             void *PhysAddr = __getPhysical((void *)Address);
             if (PhysAddr == nullptr)
                 return {};
             uintptr_t Diff = uintptr_t(Address);
             Diff &= 0xFFF;
             Diff = uintptr_t(PhysAddr) + Diff;
             return (T)Diff;
         }
References __getPhysical(), Address, and T.
Referenced by linux_clock_gettime(), linux_fstat(), linux_getdents64(), linux_ioctl(), linux_lstat(), linux_mkdir(), linux_nanosleep(), linux_newfstatat(), linux_open(), linux_pipe(), linux_pipe2(), linux_prlimit64(), linux_read(), linux_readlink(), linux_readv(), linux_reboot(), linux_sigaction(), linux_sigprocmask(), linux_stat(), linux_uname(), linux_wait4(), linux_write(), linux_writev(), sys_readlink(), and sys_uname().
Update()
void Memory::PageTable::Update ()
Update CR3 with this PageTable.
Definition at line 10 of file page_table.cpp.
     {
 #if defined(a86)
         asmv("mov %0, %%cr3" ::"r"(this));
 #elif defined(aa64)
         asmv("msr ttbr0_el1, %0" ::"r"(this));
 #endif
     }
References asmv().
Referenced by Memory::SwapPT::SwapPT(), and Memory::SwapPT::~SwapPT().
The documentation for this class was generated from the following files:
Kernel/include/memory/table.hpp
Kernel/core/memory/page_table.cpp