Fennix Userspace: Userspace/apps/base/busybox/coreutils/dos2unix.c File Reference
dos2unix.c File Reference
#include "libbb.h"
Enumerations
enum { CT_UNIX2DOS = 1 , CT_DOS2UNIX }
Functions
static void convert (char *fn, int conv_type)
int dos2unix_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CT_UNIX2DOS
CT_DOS2UNIX
Definition at line 54 of file dos2unix.c.
      {
     CT_UNIX2DOS = 1,
     CT_DOS2UNIX
 };
Function Documentation
convert()
static void convert (char * fn, int conv_type) static
Definition at line 60 of file dos2unix.c.
 {
     FILE *in, *out;
     int ch;
     char *temp_fn = temp_fn; /* for compiler */
     char *resolved_fn = resolved_fn;
     in = stdin;
     out = stdout;
     if (fn != NULL) {
         struct stat st;
         int fd;
         resolved_fn = xmalloc_follow_symlinks(fn);
         if (resolved_fn == NULL)
             bb_simple_perror_msg_and_die(fn);
         in = xfopen_for_read(resolved_fn);
         xfstat(fileno(in), &st, resolved_fn);
         temp_fn = xasprintf("%sXXXXXX", resolved_fn);
         fd = xmkstemp(temp_fn);
         if (fchmod(fd, st.st_mode) == -1)
             bb_simple_perror_msg_and_die(temp_fn);
         fchown(fd, st.st_uid, st.st_gid);
         out = xfdopen_for_write(fd);
     }
     while ((ch = fgetc(in)) != EOF) {
         if (ch == '\r')
             continue;
         if (ch == '\n')
             if (conv_type == CT_UNIX2DOS)
                 fputc('\r', out);
         fputc(ch, out);
     }
     if (fn != NULL) {
         if (fclose(in) < 0 || fclose(out) < 0) {
             unlink(temp_fn);
             bb_perror_nomsg_and_die();
         }
         xrename(temp_fn, resolved_fn);
         free(temp_fn);
         free(resolved_fn);
     }
 }
References bb_perror_nomsg_and_die(), bb_simple_perror_msg_and_die(), CT_UNIX2DOS, EOF, fchmod(), fchown(), fclose(), fd, fgetc, fileno(), fputc, free, NULL, out(), stdin, stdout, unlink(), xasprintf(), xfdopen_for_write(), xfopen_for_read(), xfstat(), xmalloc_follow_symlinks(), xmkstemp(), and xrename().
Referenced by dos2unix_main(), and multiconvert().
dos2unix_main()
int dos2unix_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 109 of file dos2unix.c.
 {
     int o, conv_type;
     /* See if we are supposed to be doing dos2unix or unix2dos */
     if (ENABLE_DOS2UNIX
      && (!ENABLE_UNIX2DOS || applet_name[0] == 'd')
     ) {
         conv_type = CT_DOS2UNIX;
     } else {
         conv_type = CT_UNIX2DOS;
     }
     /* -u convert to unix, -d convert to dos */
     o = getopt32(argv, "^" "du" "\0" "u--d:d--u"); /* mutually exclusive */
     /* Do the conversion requested by an argument else do the default
      * conversion depending on our name.  */
     if (o)
         conv_type = o;
     argv += optind;
     do {
         /* might be convert(NULL) if there is no filename given */
         convert(*argv, conv_type);
     } while (*argv && *++argv);
     return 0;
 }
References applet_name, argv, convert(), CT_DOS2UNIX, CT_UNIX2DOS, getopt32(), and optind.