Fennix Userspace: Userspace/musl/src/thread/clone.c File Reference
clone.c File Reference
#include <errno.h>
#include "pthread_impl.h"
Functions
int __clone (int(*func)(void *), void *stack, int flags, void *arg,...)
Function Documentation
__clone()
int __clone (int(*)(void *) func, void * stack, int flags, void * arg, ...)
Definition at line 4 of file clone.c.
 {
     return -ENOSYS;
 }
References ENOSYS.
Referenced by __pthread_create(), clone(), faccessat(), and posix_spawn().