Fennix Userspace: Userspace/mlibc/options/posix/include/pthread.h File Reference
pthread.h File Reference
#include <abi-bits/clockid_t.h>
#include <bits/size_t.h>
#include <bits/posix/pthread_t.h>
#include <signal.h>
#include <stdint.h>
#include <sched.h>
#include <time.h>
Data Structures
struct __mlibc_threadattr
struct __mlibc_once
struct __mlibc_mutexattr
struct __mlibc_mutex
struct __mlibc_condattr_struct
struct __mlibc_cond
struct __mlibc_barrierattr_struct
struct __mlibc_barrier
struct __mlibc_fair_rwlock
struct __mlibc_rwlockattr
Macros
#define PTHREAD_CREATE_JOINABLE 0
#define PTHREAD_CREATE_DETACHED 1
#define PTHREAD_SCOPE_SYSTEM 0
#define PTHREAD_SCOPE_PROCESS 1
#define PTHREAD_INHERIT_SCHED 0
#define PTHREAD_EXPLICIT_SCHED 1
#define PTHREAD_CANCEL_DEFERRED 0
#define PTHREAD_CANCEL_ASYNCHRONOUS 1
#define PTHREAD_CANCEL_ENABLE 0
#define PTHREAD_CANCEL_DISABLE 1
#define PTHREAD_MUTEX_DEFAULT 0
#define PTHREAD_MUTEX_NORMAL 0
#define PTHREAD_MUTEX_ERRORCHECK 1
#define PTHREAD_MUTEX_RECURSIVE 2
#define PTHREAD_MUTEX_STALLED 0
#define PTHREAD_MUTEX_ROBUST 1
#define PTHREAD_PROCESS_PRIVATE 0
#define PTHREAD_PROCESS_SHARED 1
#define PTHREAD_PRIO_NONE 0
#define PTHREAD_PRIO_INHERIT 1
#define PTHREAD_PRIO_PROTECT 2
#define PTHREAD_ONCE_INIT {0}
#define PTHREAD_COND_INITIALIZER {0}
#define PTHREAD_MUTEX_INITIALIZER {0, 0, 0, 0}
#define PTHREAD_RWLOCK_INITIALIZER {0, 0, 0}
#define PTHREAD_CANCELED ((void*) -1)
#define PTHREAD_BARRIER_SERIAL_THREAD -1
#define PTHREAD_DESTRUCTOR_ITERATIONS 8
#define PTHREAD_INHERIT_SCHED 0
#define PTHREAD_EXPLICIT_SCHED 1
#define PTHREAD_STACK_MIN 16384
#define PTHREAD_ATTR_NO_SIGMASK_NP (-1)
Typedefs
typedef struct __mlibc_threadattr pthread_attr_t
typedef uintptr_t pthread_key_t
typedef struct __mlibc_once pthread_once_t
typedef struct __mlibc_mutexattr pthread_mutexattr_t
typedef struct __mlibc_mutex pthread_mutex_t
typedef struct __mlibc_condattr_struct pthread_condattr_t
typedef struct __mlibc_cond pthread_cond_t
typedef struct __mlibc_barrierattr_struct pthread_barrierattr_t
typedef struct __mlibc_barrier pthread_barrier_t
typedef struct __mlibc_fair_rwlock pthread_rwlock_t
typedef struct __mlibc_rwlockattr pthread_rwlockattr_t
Functions
int pthread_attr_init (pthread_attr_t *)
int pthread_attr_destroy (pthread_attr_t *)
int pthread_attr_getdetachstate (const pthread_attr_t *, int *)
int pthread_attr_setdetachstate (pthread_attr_t *, int)
int pthread_attr_getstacksize (const pthread_attr_t *__restrict, size_t *__restrict)
int pthread_attr_setstacksize (pthread_attr_t *, size_t)
int pthread_attr_getstackaddr (const pthread_attr_t *, void **)
int pthread_attr_setstackaddr (pthread_attr_t *, void *)
int pthread_attr_getstack (const pthread_attr_t *, void **, size_t *)
int pthread_attr_setstack (pthread_attr_t *, void *, size_t)
int pthread_attr_getguardsize (const pthread_attr_t *__restrict, size_t *__restrict)
int pthread_attr_setguardsize (pthread_attr_t *, size_t)
int pthread_attr_getscope (const pthread_attr_t *, int *)
int pthread_attr_setscope (pthread_attr_t *, int)
int pthread_attr_getschedparam (const pthread_attr_t *__restrict, struct sched_param *__restrict)
int pthread_attr_setschedparam (pthread_attr_t *__restrict, const struct sched_param *__restrict)
int pthread_attr_getschedpolicy (const pthread_attr_t *__restrict, int *__restrict)
int pthread_attr_setschedpolicy (pthread_attr_t *__restrict, int)
int pthread_attr_getinheritsched (const pthread_attr_t *__restrict, int *__restrict)
int pthread_attr_setinheritsched (pthread_attr_t *__restrict, int)
int pthread_attr_getaffinity_np (const pthread_attr_t *__restrict, size_t, cpu_set_t *__restrict)
int pthread_attr_setaffinity_np (pthread_attr_t *__restrict, size_t, const cpu_set_t *__restrict)
int pthread_attr_getsigmask_np (const pthread_attr_t *__restrict, sigset_t *__restrict)
int pthread_attr_setsigmask_np (pthread_attr_t *__restrict, const sigset_t *__restrict)
int pthread_getattr_np (pthread_t, pthread_attr_t *)
int pthread_create (pthread_t *__restrict, const pthread_attr_t *__restrict, void *(*)(void *), void *__restrict)
pthread_t pthread_self (void)
int pthread_equal (pthread_t, pthread_t)
int pthread_exit (void *)
int pthread_join (pthread_t, void **)
int pthread_detach (pthread_t)
void pthread_cleanup_push (void(*)(void *), void *)
void pthread_cleanup_pop (int)
int pthread_setname_np (pthread_t, const char *)
int pthread_getname_np (pthread_t, char *, size_t)
int pthread_setschedparam (pthread_t, int, const struct sched_param *)
int pthread_getschedparam (pthread_t, int *, struct sched_param *)
int pthread_setcanceltype (int, int *)
int pthread_setcancelstate (int, int *)
void pthread_testcancel (void)
int pthread_cancel (pthread_t)
int pthread_atfork (void(*)(void), void(*)(void), void(*)(void))
int pthread_key_create (pthread_key_t *, void(*)(void *))
int pthread_key_delete (pthread_key_t)
void * pthread_getspecific (pthread_key_t)
int pthread_setspecific (pthread_key_t, const void *)
int pthread_once (pthread_once_t *, void(*)(void))
int pthread_mutexattr_init (pthread_mutexattr_t *)
int pthread_mutexattr_destroy (pthread_mutexattr_t *)
int pthread_mutexattr_gettype (const pthread_mutexattr_t *__restrict, int *__restrict)
int pthread_mutexattr_settype (pthread_mutexattr_t *, int)
int pthread_mutexattr_getrobust (const pthread_mutexattr_t *__restrict, int *__restrict)
int pthread_mutexattr_setrobust (pthread_mutexattr_t *, int)
int pthread_mutexattr_getpshared (const pthread_mutexattr_t *, int *)
int pthread_mutexattr_setpshared (pthread_mutexattr_t *, int)
int pthread_mutexattr_getprotocol (const pthread_mutexattr_t *__restrict, int *__restrict)
int pthread_mutexattr_setprotocol (pthread_mutexattr_t *, int)
int pthread_mutexattr_getprioceiling (const pthread_mutexattr_t *, int *)
int pthread_mutexattr_setprioceiling (pthread_mutexattr_t *, int)
int pthread_mutex_init (pthread_mutex_t *__restrict, const pthread_mutexattr_t *__restrict)
int pthread_mutex_destroy (pthread_mutex_t *)
int pthread_mutex_lock (pthread_mutex_t *)
int pthread_mutex_trylock (pthread_mutex_t *)
int pthread_mutex_timedlock (pthread_mutex_t *__restrict, const struct timespec *__restrict)
int pthread_mutex_unlock (pthread_mutex_t *)
int pthread_mutex_consistent (pthread_mutex_t *)
int pthread_condattr_init (pthread_condattr_t *)
int pthread_condattr_destroy (pthread_condattr_t *)
int pthread_condattr_getclock (const pthread_condattr_t *__restrict, clockid_t *__restrict)
int pthread_condattr_setclock (pthread_condattr_t *, clockid_t)
int pthread_condattr_getpshared (const pthread_condattr_t *__restrict, int *__restrict)
int pthread_condattr_setpshared (pthread_condattr_t *, int)
int pthread_cond_init (pthread_cond_t *__restrict, const pthread_condattr_t *__restrict)
int pthread_cond_destroy (pthread_cond_t *)
int pthread_cond_wait (pthread_cond_t *__restrict, pthread_mutex_t *__restrict)
int pthread_cond_timedwait (pthread_cond_t *__restrict, pthread_mutex_t *__restrict, const struct timespec *__restrict)
int pthread_cond_signal (pthread_cond_t *)
int pthread_cond_broadcast (pthread_cond_t *)
int pthread_barrierattr_init (pthread_barrierattr_t *)
int pthread_barrierattr_destroy (pthread_barrierattr_t *)
int pthread_barrierattr_setpshared (pthread_barrierattr_t *, int)
int pthread_barrierattr_getpshared (const pthread_barrierattr_t *__restrict, int *__restrict)
int pthread_barrier_init (pthread_barrier_t *__restrict, const pthread_barrierattr_t *__restrict, unsigned int)
int pthread_barrier_destroy (pthread_barrier_t *)
int pthread_barrier_wait (pthread_barrier_t *)
int pthread_rwlockattr_init (pthread_rwlockattr_t *)
int pthread_rwlockattr_destroy (pthread_rwlockattr_t *)
int pthread_rwlockattr_setpshared (pthread_rwlockattr_t *, int)
int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t *__restrict, int *__restrict)
int pthread_rwlock_init (pthread_rwlock_t *__restrict, const pthread_rwlockattr_t *__restrict)
int pthread_rwlock_destroy (pthread_rwlock_t *)
int pthread_rwlock_trywrlock (pthread_rwlock_t *)
int pthread_rwlock_wrlock (pthread_rwlock_t *)
int pthread_rwlock_tryrdlock (pthread_rwlock_t *)
int pthread_rwlock_rdlock (pthread_rwlock_t *)
int pthread_rwlock_unlock (pthread_rwlock_t *)
int pthread_getcpuclockid (pthread_t, clockid_t *)
Data Structure Documentation
__mlibc_threadattr
struct __mlibc_threadattr
Definition at line 80 of file pthread.h.
Data Fields
cpu_set_t * __mlibc_cpuset
size_t __mlibc_cpusetsize
int __mlibc_detachstate
size_t __mlibc_guardsize
int __mlibc_inheritsched
struct sched_param __mlibc_schedparam
int __mlibc_schedpolicy
int __mlibc_scope
sigset_t __mlibc_sigmask
int __mlibc_sigmaskset
void * __mlibc_stackaddr
size_t __mlibc_stacksize
__mlibc_once
struct __mlibc_once
Definition at line 98 of file pthread.h.
Data Fields
unsigned int __mlibc_done
__mlibc_mutexattr
struct __mlibc_mutexattr
Definition at line 103 of file pthread.h.
Data Fields
int __mlibc_prioceiling
int __mlibc_protocol
int __mlibc_pshared
int __mlibc_robust
int __mlibc_type
__mlibc_mutex
struct __mlibc_mutex
Definition at line 112 of file pthread.h.
Data Fields
unsigned int __mlibc_flags
int __mlibc_prioceiling
unsigned int __mlibc_recursion
unsigned int __mlibc_state
__mlibc_condattr_struct
struct __mlibc_condattr_struct
Definition at line 120 of file pthread.h.
Data Fields
clockid_t __mlibc_clock
int __mlibc_pshared
__mlibc_cond
struct __mlibc_cond
Definition at line 126 of file pthread.h.
Data Fields
clockid_t __mlibc_clock
unsigned int __mlibc_flags
unsigned int __mlibc_seq
__mlibc_barrierattr_struct
struct __mlibc_barrierattr_struct
Definition at line 133 of file pthread.h.
Data Fields
int __mlibc_pshared
__mlibc_barrier
struct __mlibc_barrier
Definition at line 138 of file pthread.h.
Data Fields
unsigned int __mlibc_count
unsigned int __mlibc_flags
unsigned int __mlibc_inside
unsigned int __mlibc_seq
unsigned int __mlibc_waiting
__mlibc_fair_rwlock
struct __mlibc_fair_rwlock
Definition at line 147 of file pthread.h.
Data Fields
unsigned int __mlibc_flags
unsigned int __mlibc_m
unsigned int __mlibc_rc
__mlibc_rwlockattr
struct __mlibc_rwlockattr
Definition at line 154 of file pthread.h.
Data Fields
int __mlibc_pshared
Macro Definition Documentation
PTHREAD_ATTR_NO_SIGMASK_NP
#define PTHREAD_ATTR_NO_SIGMASK_NP (-1)
Definition at line 77 of file pthread.h.
PTHREAD_BARRIER_SERIAL_THREAD
#define PTHREAD_BARRIER_SERIAL_THREAD -1
Definition at line 67 of file pthread.h.
PTHREAD_CANCEL_ASYNCHRONOUS
#define PTHREAD_CANCEL_ASYNCHRONOUS 1
Definition at line 35 of file pthread.h.
PTHREAD_CANCEL_DEFERRED
#define PTHREAD_CANCEL_DEFERRED 0
Definition at line 34 of file pthread.h.
PTHREAD_CANCEL_DISABLE
#define PTHREAD_CANCEL_DISABLE 1
Definition at line 39 of file pthread.h.
PTHREAD_CANCEL_ENABLE
#define PTHREAD_CANCEL_ENABLE 0
Definition at line 38 of file pthread.h.
PTHREAD_CANCELED
#define PTHREAD_CANCELED ((void*) -1)
Definition at line 65 of file pthread.h.
PTHREAD_COND_INITIALIZER
#define PTHREAD_COND_INITIALIZER {0}
Definition at line 61 of file pthread.h.
PTHREAD_CREATE_DETACHED
#define PTHREAD_CREATE_DETACHED 1
Definition at line 23 of file pthread.h.
PTHREAD_CREATE_JOINABLE
#define PTHREAD_CREATE_JOINABLE 0
Definition at line 22 of file pthread.h.
PTHREAD_DESTRUCTOR_ITERATIONS
#define PTHREAD_DESTRUCTOR_ITERATIONS 8
Definition at line 70 of file pthread.h.
PTHREAD_EXPLICIT_SCHED [1/2]
#define PTHREAD_EXPLICIT_SCHED 1
Definition at line 73 of file pthread.h.
PTHREAD_EXPLICIT_SCHED [2/2]
#define PTHREAD_EXPLICIT_SCHED 1
Definition at line 73 of file pthread.h.
PTHREAD_INHERIT_SCHED [1/2]
#define PTHREAD_INHERIT_SCHED 0
Definition at line 72 of file pthread.h.
PTHREAD_INHERIT_SCHED [2/2]
#define PTHREAD_INHERIT_SCHED 0
Definition at line 72 of file pthread.h.
PTHREAD_MUTEX_DEFAULT
#define PTHREAD_MUTEX_DEFAULT 0
Definition at line 42 of file pthread.h.
PTHREAD_MUTEX_ERRORCHECK
#define PTHREAD_MUTEX_ERRORCHECK 1
Definition at line 44 of file pthread.h.
PTHREAD_MUTEX_INITIALIZER
#define PTHREAD_MUTEX_INITIALIZER {0, 0, 0, 0}
Definition at line 62 of file pthread.h.
PTHREAD_MUTEX_NORMAL
#define PTHREAD_MUTEX_NORMAL 0
Definition at line 43 of file pthread.h.
PTHREAD_MUTEX_RECURSIVE
#define PTHREAD_MUTEX_RECURSIVE 2
Definition at line 45 of file pthread.h.
PTHREAD_MUTEX_ROBUST
#define PTHREAD_MUTEX_ROBUST 1
Definition at line 49 of file pthread.h.
PTHREAD_MUTEX_STALLED
#define PTHREAD_MUTEX_STALLED 0
Definition at line 48 of file pthread.h.
PTHREAD_ONCE_INIT
#define PTHREAD_ONCE_INIT {0}
Definition at line 60 of file pthread.h.
PTHREAD_PRIO_INHERIT
#define PTHREAD_PRIO_INHERIT 1
Definition at line 57 of file pthread.h.
PTHREAD_PRIO_NONE
#define PTHREAD_PRIO_NONE 0
Definition at line 56 of file pthread.h.
PTHREAD_PRIO_PROTECT
#define PTHREAD_PRIO_PROTECT 2
Definition at line 58 of file pthread.h.
PTHREAD_PROCESS_PRIVATE
#define PTHREAD_PROCESS_PRIVATE 0
Definition at line 52 of file pthread.h.
PTHREAD_PROCESS_SHARED
#define PTHREAD_PROCESS_SHARED 1
Definition at line 53 of file pthread.h.
PTHREAD_RWLOCK_INITIALIZER
#define PTHREAD_RWLOCK_INITIALIZER {0, 0, 0}
Definition at line 63 of file pthread.h.
PTHREAD_SCOPE_PROCESS
#define PTHREAD_SCOPE_PROCESS 1
Definition at line 27 of file pthread.h.
PTHREAD_SCOPE_SYSTEM
#define PTHREAD_SCOPE_SYSTEM 0
Definition at line 26 of file pthread.h.
PTHREAD_STACK_MIN
#define PTHREAD_STACK_MIN 16384
Definition at line 75 of file pthread.h.
Typedef Documentation
pthread_attr_t
typedef struct __mlibc_threadattr pthread_attr_t
Definition at line 1 of file pthread.h.
pthread_barrier_t
typedef struct __mlibc_barrier pthread_barrier_t
Definition at line 96 of file pthread.h.
pthread_barrierattr_t
typedef struct __mlibc_barrierattr_struct pthread_barrierattr_t
Definition at line 96 of file pthread.h.
pthread_cond_t
typedef struct __mlibc_cond pthread_cond_t
Definition at line 96 of file pthread.h.
pthread_condattr_t
typedef struct __mlibc_condattr_struct pthread_condattr_t
Definition at line 96 of file pthread.h.
pthread_key_t
typedef uintptr_t pthread_key_t
Definition at line 96 of file pthread.h.
pthread_mutex_t
typedef struct __mlibc_mutex pthread_mutex_t
Definition at line 96 of file pthread.h.
pthread_mutexattr_t
typedef struct __mlibc_mutexattr pthread_mutexattr_t
Definition at line 96 of file pthread.h.
pthread_once_t
typedef struct __mlibc_once pthread_once_t
Definition at line 96 of file pthread.h.
pthread_rwlock_t
typedef struct __mlibc_fair_rwlock pthread_rwlock_t
Definition at line 96 of file pthread.h.
pthread_rwlockattr_t
typedef struct __mlibc_rwlockattr pthread_rwlockattr_t
Definition at line 96 of file pthread.h.
Function Documentation
pthread_atfork()
int pthread_atfork (void(*)(void) prepare, void(*)(void) parent, void(*)(void) child)
Definition at line 743 of file pthread-stubs.cpp.
{
     auto self = mlibc::get_current_tcb();
     auto hand = frg::construct<Tcb::AtforkHandler>(getAllocator());
     if (!hand)
         return -1;
     hand->prepare = prepare;
     hand->parent = parent;
     hand->child = child;
     hand->next = nullptr;
     hand->prev = self->atforkEnd;
     if (self->atforkEnd)
         self->atforkEnd->next = hand;
     self->atforkEnd = hand;
     if (!self->atforkBegin)
         self->atforkBegin = self->atforkEnd;
     return 0;
 }
References child, mlibc::get_current_tcb(), getAllocator(), parent, and prepare().
Referenced by main().
pthread_attr_destroy()
int pthread_attr_destroy (pthread_attr_t *)
Definition at line 77 of file pthread-stubs.cpp.
{
     return 0;
 }
pthread_attr_getaffinity_np()
int pthread_attr_getaffinity_np (const pthread_attr_t * __restrict, size_t , cpu_set_t * __restrict)
pthread_attr_getdetachstate()
int pthread_attr_getdetachstate (const pthread_attr_t * attr, int * detachstate)
Definition at line 81 of file pthread-stubs.cpp.
{
     *detachstate = attr->__mlibc_detachstate;
     return 0;
 }
References mlibc::attr.
Referenced by test_detachstate().
pthread_attr_getguardsize()
int pthread_attr_getguardsize (const pthread_attr_t * __restrict, size_t * __restrict)
pthread_attr_getinheritsched()
int pthread_attr_getinheritsched (const pthread_attr_t * __restrict, int * __restrict)
Definition at line 151 of file pthread-stubs.cpp.
{
     *inheritsched = attr->__mlibc_inheritsched;
     return 0;
 }
References mlibc::attr.
Referenced by test_inheritsched().
pthread_attr_getschedparam()
int pthread_attr_getschedparam (const pthread_attr_t * __restrict, struct sched_param * __restrict)
pthread_attr_getschedpolicy()
int pthread_attr_getschedpolicy (const pthread_attr_t * __restrict, int * __restrict)
pthread_attr_getscope()
int pthread_attr_getscope (const pthread_attr_t * attr, int * scope)
Definition at line 137 of file pthread-stubs.cpp.
{
     *scope = attr->__mlibc_scope;
     return 0;
 }
References mlibc::attr.
Referenced by test_scope().
pthread_attr_getsigmask_np()
int pthread_attr_getsigmask_np (const pthread_attr_t * __restrict, sigset_t * __restrict)
pthread_attr_getstack()
int pthread_attr_getstack (const pthread_attr_t * attr, void ** stackaddr, size_t * stacksize)
Definition at line 115 of file pthread-stubs.cpp.
{
     *stackaddr = attr->__mlibc_stackaddr;
     *stacksize = attr->__mlibc_stacksize;
     return 0;
 }
References mlibc::attr.
Referenced by test_getattrnp(), and test_stack().
pthread_attr_getstackaddr()
int pthread_attr_getstackaddr (const pthread_attr_t * attr, void ** stackaddr)
Definition at line 106 of file pthread-stubs.cpp.
{
     *stackaddr = attr->__mlibc_stackaddr;
     return 0;
 }
References mlibc::attr.
Referenced by test_stackaddr().
pthread_attr_getstacksize()
int pthread_attr_getstacksize (const pthread_attr_t * __restrict, size_t * __restrict)
pthread_attr_init()
int pthread_attr_init (pthread_attr_t * attr)
Definition at line 69 of file pthread-stubs.cpp.
{
     *attr = pthread_attr_t{};
     attr->__mlibc_stacksize = default_stacksize;
     attr->__mlibc_guardsize = default_guardsize;
     attr->__mlibc_detachstate = PTHREAD_CREATE_JOINABLE;
     return 0;
 }
References mlibc::attr, default_guardsize, default_stacksize, and PTHREAD_CREATE_JOINABLE.
Referenced by pthread_create(), test_affinity(), test_getattrnp(), test_guardsize(), test_sigmask(), test_stackaddr(), and test_stacksize().
pthread_attr_setaffinity_np()
int pthread_attr_setaffinity_np (pthread_attr_t * __restrict, size_t , const cpu_set_t * __restrict)
pthread_attr_setdetachstate()
int pthread_attr_setdetachstate (pthread_attr_t * attr, int detachstate)
Definition at line 85 of file pthread-stubs.cpp.
{
     if (detachstate != PTHREAD_CREATE_DETACHED &&
             detachstate != PTHREAD_CREATE_JOINABLE)
         return EINVAL;
     attr->__mlibc_detachstate = detachstate;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_CREATE_DETACHED, and PTHREAD_CREATE_JOINABLE.
Referenced by test_detachstate().
pthread_attr_setguardsize()
int pthread_attr_setguardsize (pthread_attr_t * attr, size_t guardsize)
Definition at line 132 of file pthread-stubs.cpp.
{
     attr->__mlibc_guardsize = guardsize;
     return 0;
 }
References mlibc::attr.
Referenced by test_guardsize(), and test_stackaddr().
pthread_attr_setinheritsched()
int pthread_attr_setinheritsched (pthread_attr_t * __restrict, int inheritsched)
Definition at line 155 of file pthread-stubs.cpp.
{
     if (inheritsched != PTHREAD_INHERIT_SCHED &&
             inheritsched != PTHREAD_EXPLICIT_SCHED)
         return EINVAL;
     attr->__mlibc_inheritsched = inheritsched;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_EXPLICIT_SCHED, and PTHREAD_INHERIT_SCHED.
Referenced by test_inheritsched(), and test_schedpolicy().
pthread_attr_setschedparam()
int pthread_attr_setschedparam (pthread_attr_t * __restrict, const struct sched_param * __restrict)
pthread_attr_setschedpolicy()
int pthread_attr_setschedpolicy (pthread_attr_t * __restrict, int)
pthread_attr_setscope()
int pthread_attr_setscope (pthread_attr_t * attr, int scope)
Definition at line 141 of file pthread-stubs.cpp.
{
     if (scope != PTHREAD_SCOPE_SYSTEM &&
             scope != PTHREAD_SCOPE_PROCESS)
         return EINVAL;
     if (scope == PTHREAD_SCOPE_PROCESS)
         return ENOTSUP;
     attr->__mlibc_scope = scope;
     return 0;
 }
References mlibc::attr, EINVAL, ENOTSUP, PTHREAD_SCOPE_PROCESS, and PTHREAD_SCOPE_SYSTEM.
Referenced by test_scope().
pthread_attr_setsigmask_np()
int pthread_attr_setsigmask_np (pthread_attr_t * __restrict, const sigset_t * __restrict)
pthread_attr_setstack()
int pthread_attr_setstack (pthread_attr_t * attr, void * stackaddr, size_t stacksize)
Definition at line 120 of file pthread-stubs.cpp.
{
     if (stacksize < PTHREAD_STACK_MIN)
         return EINVAL;
     attr->__mlibc_stacksize = stacksize;
     attr->__mlibc_stackaddr = stackaddr;
     return 0;
 }
References mlibc::attr, EINVAL, and PTHREAD_STACK_MIN.
Referenced by test_stack().
pthread_attr_setstackaddr()
int pthread_attr_setstackaddr (pthread_attr_t * attr, void * stackaddr)
Definition at line 110 of file pthread-stubs.cpp.
{
     attr->__mlibc_stackaddr = stackaddr;
     return 0;
 }
References mlibc::attr.
Referenced by test_stackaddr().
pthread_attr_setstacksize()
int pthread_attr_setstacksize (pthread_attr_t * attr, size_t stacksize)
Definition at line 99 of file pthread-stubs.cpp.
{
     if (stacksize < PTHREAD_STACK_MIN)
         return EINVAL;
     attr->__mlibc_stacksize = stacksize;
     return 0;
 }
References mlibc::attr, EINVAL, and PTHREAD_STACK_MIN.
Referenced by test_getattrnp(), and test_stacksize().
pthread_barrier_destroy()
int pthread_barrier_destroy (pthread_barrier_t * barrier)
Definition at line 1334 of file pthread-stubs.cpp.
{
     // Wait until there are no threads still using the barrier.
     unsigned inside = 0;
     do {
         unsigned expected = __atomic_load_n(&barrier->__mlibc_inside, __ATOMIC_RELAXED);
         if (expected == 0)
             break;
         int e = mlibc::sys_futex_wait((int *)&barrier->__mlibc_inside, expected, nullptr);
         if (e != 0 && e != EAGAIN && e != EINTR)
             mlibc::panicLogger() << "mlibc: sys_futex_wait() returned error " << e << frg::endlog;
     } while (inside > 0);
     memset(barrier, 0, sizeof *barrier);
     return 0;
 }
References __mlibc_barrier::__mlibc_inside, barrier, EAGAIN, EINTR, memset(), mlibc::panicLogger, and mlibc::sys_futex_wait().
Referenced by main().
pthread_barrier_init()
int pthread_barrier_init (pthread_barrier_t * __restrict, const pthread_barrierattr_t * __restrict, unsigned int)
pthread_barrier_wait()
int pthread_barrier_wait (pthread_barrier_t * barrier)
Definition at line 1351 of file pthread-stubs.cpp.
{
     if (barrier->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_barrier_t flags were non-zero"
             << frg::endlog;
     }
     // inside is incremented on entry and decremented on exit.
     // This is used to synchronise with pthread_barrier_destroy, to ensure that a thread doesn't pass
     // the barrier and immediately destroy its state while other threads still rely on it.
     __atomic_fetch_add(&barrier->__mlibc_inside, 1, __ATOMIC_ACQUIRE);
     auto leave = [&](){
         unsigned inside = __atomic_sub_fetch(&barrier->__mlibc_inside, 1, __ATOMIC_RELEASE);
         if (inside == 0)
             mlibc::sys_futex_wake((int *)&barrier->__mlibc_inside);
     };
     unsigned seq = __atomic_load_n(&barrier->__mlibc_seq, __ATOMIC_ACQUIRE);
     while (true) {
         unsigned expected = __atomic_load_n(&barrier->__mlibc_waiting, __ATOMIC_RELAXED);
         bool swapped = __atomic_compare_exchange_n(&barrier->__mlibc_waiting, &expected, expected + 1, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE);
         if (swapped) {
             if (expected + 1 == barrier->__mlibc_count) {
                 // We were the last thread to hit the barrier. Reset waiters and wake the others.
                 __atomic_fetch_add(&barrier->__mlibc_seq, 1, __ATOMIC_ACQUIRE);
                 __atomic_store_n(&barrier->__mlibc_waiting, 0, __ATOMIC_RELEASE);
                 mlibc::sys_futex_wake((int *)&barrier->__mlibc_seq);
                 leave();
                 return PTHREAD_BARRIER_SERIAL_THREAD;
             }
             while (true) {
                 int e = mlibc::sys_futex_wait((int *)&barrier->__mlibc_seq, seq, nullptr);
                 if (e != 0 && e != EAGAIN && e != EINTR)
                     mlibc::panicLogger() << "mlibc: sys_futex_wait() returned error " << e << frg::endlog;
                 unsigned newSeq = __atomic_load_n(&barrier->__mlibc_seq, __ATOMIC_ACQUIRE);
                 if (newSeq > seq) {
                     leave();
                     return 0;
                 }
             }
         }
     }
 }
References __mlibc_barrier::__mlibc_count, __mlibc_barrier::__mlibc_flags, __mlibc_barrier::__mlibc_inside, __mlibc_barrier::__mlibc_seq, __mlibc_barrier::__mlibc_waiting, barrier, EAGAIN, EINTR, mlibc::panicLogger, PTHREAD_BARRIER_SERIAL_THREAD, mlibc::sys_futex_wait(), and mlibc::sys_futex_wake().
Referenced by main(), and worker().
pthread_barrierattr_destroy()
int pthread_barrierattr_destroy (pthread_barrierattr_t *)
Definition at line 1313 of file pthread-stubs.cpp.
{
     return 0;
 }
Referenced by main().
pthread_barrierattr_getpshared()
int pthread_barrierattr_getpshared (const pthread_barrierattr_t * __restrict, int * __restrict)
pthread_barrierattr_init()
int pthread_barrierattr_init (pthread_barrierattr_t * attr)
Definition at line 1294 of file pthread-stubs.cpp.
{
     attr->__mlibc_pshared = PTHREAD_PROCESS_PRIVATE;
     return 0;
 }
References mlibc::attr, and PTHREAD_PROCESS_PRIVATE.
Referenced by main().
pthread_barrierattr_setpshared()
int pthread_barrierattr_setpshared (pthread_barrierattr_t * attr, int pshared)
Definition at line 1305 of file pthread-stubs.cpp.
{
     if (pshared != PTHREAD_PROCESS_SHARED && pshared != PTHREAD_PROCESS_PRIVATE)
         return EINVAL;
     attr->__mlibc_pshared = pshared;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
Referenced by main().
pthread_cancel()
int pthread_cancel (pthread_t thread)
Definition at line 696 of file pthread-stubs.cpp.
{
     if (!mlibc::sys_tgkill) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     auto tcb = reinterpret_cast<Tcb *>(thread);
     // Check if the TCB is valid, somewhat..
     if (tcb->selfPointer != tcb)
         return ESRCH;
     int old_value = __atomic_load_n(&tcb->cancelBits, __ATOMIC_RELAXED);
     while (1) {
         int bitmask = tcbCancelTriggerBit;
         int new_value = old_value | bitmask;
         if (old_value == new_value)
             break;
         int current_value = old_value;
         if (__atomic_compare_exchange_n(&tcb->cancelBits, &current_value,
                     new_value, true, __ATOMIC_RELAXED, __ATOMIC_RELAXED)) {
             if (mlibc::tcb_cancel_enabled(new_value)) {
                 pid_t pid = getpid();
                 int res = mlibc::sys_tgkill(pid, tcb->tid, SIGCANCEL);
                 current_value = __atomic_load_n(&tcb->cancelBits, __ATOMIC_RELAXED);
                 // If we can't find the thread anymore, it's possible that it exited between
                 // us setting the cancel trigger bit, and us sending the signal. Check the
                 // cancelBits for tcbExitingBit to confirm that.
                 // XXX(qookie): This will be an use-after-free once we start freeing TCBs on
                 //              exit. Perhaps the TCB should be refcounted.
                 if (!(res == ESRCH && (current_value & tcbExitingBit)))
                     return res;
             }
             break;
         }
         old_value = current_value;
     }
     return 0;
 }
References ENOSYS, ESRCH, getpid(), MLIBC_MISSING_SYSDEP, SIGCANCEL, mlibc::sys_tgkill(), mlibc::tcb_cancel_enabled(), anonymous_namespace{tcb.hpp}::tcbCancelTriggerBit, and anonymous_namespace{tcb.hpp}::tcbExitingBit.
Referenced by main().
pthread_cleanup_pop()
void pthread_cleanup_pop (int execute)
Definition at line 476 of file pthread-stubs.cpp.
{
     auto self = mlibc::get_current_tcb();
     auto hand = self->cleanupEnd;
     if (self->cleanupEnd)
         self->cleanupEnd = self->cleanupEnd->prev;
     if (self->cleanupEnd)
         self->cleanupEnd->next = nullptr;
     if (execute)
         hand->func(hand->arg);
     frg::destruct(getAllocator(), hand);
 }
References mlibc::get_current_tcb(), and getAllocator().
Referenced by getspnam_r(), and worker().
pthread_cleanup_push()
void pthread_cleanup_push (void(*)(void *) func, void * arg)
Definition at line 458 of file pthread-stubs.cpp.
{
     auto self = mlibc::get_current_tcb();
     auto hand = frg::construct<Tcb::CleanupHandler>(getAllocator());
     hand->func = func;
     hand->arg = arg;
     hand->next = nullptr;
     hand->prev = self->cleanupEnd;
     if (self->cleanupEnd)
         self->cleanupEnd->next = hand;
     self->cleanupEnd = hand;
     if (!self->cleanupBegin)
         self->cleanupBegin = self->cleanupEnd;
 }
References arg, mlibc::get_current_tcb(), and getAllocator().
Referenced by getspnam_r(), and worker().
pthread_cond_broadcast()
int pthread_cond_broadcast (pthread_cond_t * cond)
Definition at line 1281 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     __atomic_fetch_add(&cond->__mlibc_seq, 1, __ATOMIC_RELEASE);
     if(int e = mlibc::sys_futex_wake((int *)&cond->__mlibc_seq); e)
         __ensure(!"sys_futex_wake() failed");
     return 0;
 }
References __ensure, __mlibc_cond::__mlibc_seq, cond, SCOPE_TRACE, and mlibc::sys_futex_wake().
Referenced by pthread_cond_signal(), and test_broadcast_wakes_all().
pthread_cond_destroy()
int pthread_cond_destroy (pthread_cond_t *)
Definition at line 1186 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     return 0;
 }
References SCOPE_TRACE.
Referenced by test_attr().
pthread_cond_init()
int pthread_cond_init (pthread_cond_t * __restrict, const pthread_condattr_t * __restrict)
pthread_cond_signal()
int pthread_cond_signal (pthread_cond_t * cond)
Definition at line 1275 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     return pthread_cond_broadcast(cond);
 }
References cond, pthread_cond_broadcast(), and SCOPE_TRACE.
pthread_cond_timedwait()
int pthread_cond_timedwait (pthread_cond_t * __restrict, pthread_mutex_t * __restrict, const struct timespec * __restrict)
pthread_cond_wait()
int pthread_cond_wait (pthread_cond_t * __restrict, pthread_mutex_t * __restrict)
pthread_condattr_destroy()
int pthread_condattr_destroy (pthread_condattr_t * attr)
Definition at line 1137 of file pthread-stubs.cpp.
{
     memset(attr, 0, sizeof(*attr));
     return 0;
 }
References mlibc::attr, and memset().
Referenced by test_attr().
pthread_condattr_getclock()
int pthread_condattr_getclock (const pthread_condattr_t * __restrict, clockid_t * __restrict)
pthread_condattr_getpshared()
int pthread_condattr_getpshared (const pthread_condattr_t * __restrict, int * __restrict)
pthread_condattr_init()
int pthread_condattr_init (pthread_condattr_t * attr)
Definition at line 1131 of file pthread-stubs.cpp.
{
     attr->__mlibc_pshared = PTHREAD_PROCESS_PRIVATE;
     attr->__mlibc_clock = CLOCK_REALTIME;
     return 0;
 }
References mlibc::attr, CLOCK_REALTIME, and PTHREAD_PROCESS_PRIVATE.
Referenced by test_attr(), and test_timedwait_timedout().
pthread_condattr_setclock()
int pthread_condattr_setclock (pthread_condattr_t * attr, clockid_t clock)
Definition at line 1148 of file pthread-stubs.cpp.
{
     if (clock != CLOCK_REALTIME && clock != CLOCK_MONOTONIC
             && clock != CLOCK_MONOTONIC_RAW && clock != CLOCK_REALTIME_COARSE
             && clock != CLOCK_MONOTONIC_COARSE && clock != CLOCK_BOOTTIME)
         return EINVAL;
     attr->__mlibc_clock = clock;
     return 0;
 }
References mlibc::attr, clock(), CLOCK_BOOTTIME, CLOCK_MONOTONIC, CLOCK_MONOTONIC_COARSE, CLOCK_MONOTONIC_RAW, CLOCK_REALTIME, CLOCK_REALTIME_COARSE, and EINVAL.
Referenced by test_attr(), and test_timedwait_timedout().
pthread_condattr_setpshared()
int pthread_condattr_setpshared (pthread_condattr_t * attr, int pshared)
Definition at line 1164 of file pthread-stubs.cpp.
{
     if (pshared != PTHREAD_PROCESS_PRIVATE && pshared != PTHREAD_PROCESS_SHARED)
         return EINVAL;
     attr->__mlibc_pshared = pshared;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
Referenced by test_attr().
pthread_create()
int pthread_create (pthread_t * __restrict, const pthread_attr_t * __restrict, void * *)(void *, void * __restrict)
pthread_detach()
int pthread_detach (pthread_t thread)
Definition at line 445 of file pthread-stubs.cpp.
{
     auto tcb = reinterpret_cast<Tcb*>(thread);
     if (!__atomic_load_n(&tcb->isJoinable, __ATOMIC_RELAXED))
         return EINVAL;
     int expected = 1;
     if(!__atomic_compare_exchange_n(&tcb->isJoinable, &expected, 0, false, __ATOMIC_RELEASE,
                 __ATOMIC_RELAXED))
         return EINVAL;
     return 0;
 }
References EINVAL.
pthread_equal()
int pthread_equal (pthread_t t1, pthread_t t2)
Definition at line 363 of file pthread-stubs.cpp.
{
     if(t1 == t2)
         return 1;
     return 0;
 }
References t1, and t2.
pthread_exit()
int pthread_exit (void * ret_val)
Definition at line 385 of file pthread-stubs.cpp.
{
     auto self = mlibc::get_current_tcb();
     if (__atomic_load_n(&self->cancelBits, __ATOMIC_RELAXED) & tcbExitingBit)
         return 0; // We are already exiting
     __atomic_fetch_or(&self->cancelBits, tcbExitingBit, __ATOMIC_RELAXED);
     auto hand = self->cleanupEnd;
     while (hand) {
         auto old = hand;
         hand->func(hand->arg);
         hand = hand->prev;
         frg::destruct(getAllocator(), old);
     }
     for (size_t j = 0; j < PTHREAD_DESTRUCTOR_ITERATIONS; j++) {
         for (size_t i = 0; i < PTHREAD_KEYS_MAX; i++) {
             if (auto v = pthread_getspecific(i)) {
                 key_mutex_.lock();
                 auto dtor = key_globals_[i].dtor;
                 key_mutex_.unlock();
                 if (dtor) {
                     dtor(v);
                     (*self->localKeys)[i].value = nullptr;
                 }
             }
         }
     }
     self->returnValue = ret_val;
     __atomic_store_n(&self->didExit, 1, __ATOMIC_RELEASE);
     mlibc::sys_futex_wake(&self->didExit);
     // TODO: clean up thread resources when we are detached.
     // TODO: do exit(0) when we're the only thread instead
     mlibc::sys_thread_exit();
     __builtin_unreachable();
 }
References mlibc::get_current_tcb(), getAllocator(), i, j, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, FutexLockImpl< Recursive >::lock(), PTHREAD_DESTRUCTOR_ITERATIONS, pthread_getspecific(), PTHREAD_KEYS_MAX, mlibc::sys_futex_wake(), mlibc::sys_thread_exit(), anonymous_namespace{tcb.hpp}::tcbExitingBit, FutexLockImpl< Recursive >::unlock(), and value.
Referenced by __mlibc_do_cancel(), worker(), worker1(), and worker2().
pthread_getattr_np()
int pthread_getattr_np (pthread_t thread, pthread_attr_t * attr)
Definition at line 293 of file pthread-stubs.cpp.
{
     auto tcb = reinterpret_cast<Tcb*>(thread);
     *attr = pthread_attr_t{};
     if (!tcb->stackAddr || !tcb->stackSize) {
         get_own_stackinfo(&attr->__mlibc_stackaddr, &attr->__mlibc_stacksize);
     } else {
         attr->__mlibc_stacksize = tcb->stackSize;
         attr->__mlibc_stackaddr = tcb->stackAddr;
     }
     attr->__mlibc_guardsize = tcb->guardSize;
     attr->__mlibc_detachstate = tcb->isJoinable ? PTHREAD_CREATE_JOINABLE : PTHREAD_CREATE_DETACHED;
     mlibc::infoLogger() << "pthread_getattr_np(): Implementation is incomplete!" << frg::endlog;
     return 0;
 }
References mlibc::attr, anonymous_namespace{pthread-stubs.cpp}::get_own_stackinfo(), mlibc::infoLogger, PTHREAD_CREATE_DETACHED, and PTHREAD_CREATE_JOINABLE.
Referenced by test_getattrnp().
pthread_getcpuclockid()
int pthread_getcpuclockid (pthread_t , clockid_t *)
Definition at line 1639 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_getname_np()
int pthread_getname_np (pthread_t , char * , size_t)
Definition at line 497 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_getschedparam()
int pthread_getschedparam (pthread_t thread, int * policy, struct sched_param * param)
Definition at line 513 of file pthread-stubs.cpp.
{
     auto tcb = reinterpret_cast<Tcb*>(thread);
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getschedparam, ENOSYS);
     if(int e = mlibc::sys_getschedparam(tcb, policy, param); e) {
         return e;
     }
     return 0;
 }
References ENOSYS, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getschedparam().
Referenced by main().
pthread_getspecific()
void* pthread_getspecific (pthread_key_t key)
Definition at line 810 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto self = mlibc::get_current_tcb();
     auto g = frg::guard(&key_mutex_);
     if (key >= PTHREAD_KEYS_MAX || !key_globals_[key].in_use)
         return nullptr;
     if (key_globals_[key].generation > (*self->localKeys)[key].generation) {
         (*self->localKeys)[key].value = nullptr;
         (*self->localKeys)[key].generation = key_globals_[key].generation;
     }
     return (*self->localKeys)[key].value;
 }
References g, mlibc::get_current_tcb(), mlibc::guard, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, PTHREAD_KEYS_MAX, SCOPE_TRACE, and value.
Referenced by dtor1(), dtor3(), main(), pthread_exit(), worker1(), and worker2().
pthread_join()
int pthread_join (pthread_t thread, void ** ret)
Definition at line 427 of file pthread-stubs.cpp.
{
     auto tcb = reinterpret_cast<Tcb *>(thread);
     if (!__atomic_load_n(&tcb->isJoinable, __ATOMIC_ACQUIRE))
         return EINVAL;
     while (!__atomic_load_n(&tcb->didExit, __ATOMIC_ACQUIRE)) {
         mlibc::sys_futex_wait(&tcb->didExit, 0, nullptr);
     }
     if (ret)
         *ret = tcb->returnValue;
     // FIXME: destroy tcb here, currently we leak it
     return 0;
 }
References EINVAL, ret, and mlibc::sys_futex_wait().
Referenced by check_result(), main(), test_broadcast_wakes_all(), test_getattrnp(), test_stackaddr(), test_stacksize(), testNormal(), and testRecursive().
pthread_key_create()
int pthread_key_create (pthread_key_t * out, void(*)(void *) destructor)
Definition at line 771 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto g = frg::guard(&key_mutex_);
     pthread_key_t key = PTHREAD_KEYS_MAX;
     for (size_t i = 0; i < PTHREAD_KEYS_MAX; i++) {
         if (!key_globals_[i].in_use) {
             key = i;
             break;
         }
     }
     if (key == PTHREAD_KEYS_MAX)
         return EAGAIN;
     key_globals_[key].in_use = true;
     key_globals_[key].dtor = destructor;
     *out = key;
     return 0;
 }
References EAGAIN, g, mlibc::guard, i, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, PTHREAD_KEYS_MAX, and SCOPE_TRACE.
Referenced by dtor3(), main(), worker1(), and worker2().
pthread_key_delete()
int pthread_key_delete (pthread_key_t key)
Definition at line 795 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto g = frg::guard(&key_mutex_);
     if (key >= PTHREAD_KEYS_MAX || !key_globals_[key].in_use)
         return EINVAL;
     key_globals_[key].in_use = false;
     key_globals_[key].dtor = nullptr;
     key_globals_[key].generation++;
     return 0;
 }
References EINVAL, g, mlibc::guard, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, PTHREAD_KEYS_MAX, and SCOPE_TRACE.
Referenced by dtor3(), and main().
pthread_mutex_consistent()
int pthread_mutex_consistent (pthread_mutex_t *)
Definition at line 1122 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_mutex_destroy()
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Definition at line 999 of file pthread-stubs.cpp.
{
     __ensure(!mutex->__mlibc_state);
     return 0;
 }
References __ensure, __mlibc_mutex::__mlibc_state, and mutex.
Referenced by testNormal(), and testRecursive().
pthread_mutex_init()
int pthread_mutex_init (pthread_mutex_t * __restrict, const pthread_mutexattr_t * __restrict)
pthread_mutex_lock()
int pthread_mutex_lock (pthread_mutex_t * mutex)
Definition at line 1004 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     unsigned int this_tid = mlibc::this_tid();
     unsigned int expected = 0;
     while(true) {
         if(!expected) {
             // Try to take the mutex here.
             if(__atomic_compare_exchange_n(&mutex->__mlibc_state,
                     &expected, this_tid, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)) {
                 __ensure(!mutex->__mlibc_recursion);
                 mutex->__mlibc_recursion = 1;
                 return 0;
             }
         }else{
             // If this (recursive) mutex is already owned by us, increment the recursion level.
             if((expected & mutex_owner_mask) == this_tid) {
                 if(!(mutex->__mlibc_flags & mutexRecursive)) {
                     if (mutex->__mlibc_flags & mutexErrorCheck)
                         return EDEADLK;
                     else
                         mlibc::panicLogger() << "mlibc: pthread_mutex deadlock detected!"
                             << frg::endlog;
                 }
                 ++mutex->__mlibc_recursion;
                 return 0;
             }
             // Wait on the futex if the waiters flag is set.
             if(expected & mutex_waiters_bit) {
                 int e = mlibc::sys_futex_wait((int *)&mutex->__mlibc_state, expected, nullptr);
                 // If the wait returns EAGAIN, that means that the mutex_waiters_bit was just unset by
                 // some other thread. In this case, we should loop back around.
                 if (e && e != EAGAIN)
                     mlibc::panicLogger() << "sys_futex_wait() failed with error code " << e << frg::endlog;
                 // Opportunistically try to take the lock after we wake up.
                 expected = 0;
             }else{
                 // Otherwise we have to set the waiters flag first.
                 unsigned int desired = expected | mutex_waiters_bit;
                 if(__atomic_compare_exchange_n((int *)&mutex->__mlibc_state,
                         reinterpret_cast<int*>(&expected), desired, false, __ATOMIC_RELAXED, __ATOMIC_RELAXED))
                     expected = desired;
             }
         }
     }
 }
References __ensure, __mlibc_mutex::__mlibc_flags, __mlibc_mutex::__mlibc_recursion, __mlibc_mutex::__mlibc_state, EAGAIN, EDEADLK, mutex, mutex_owner_mask, mutex_waiters_bit, mutexErrorCheck, mutexRecursive, mlibc::panicLogger, SCOPE_TRACE, mlibc::sys_futex_wait(), and mlibc::this_tid().
Referenced by pthread_cond_timedwait(), test_timedwait_timedout(), testNormal(), testRecursive(), and worker().
pthread_mutex_timedlock()
int pthread_mutex_timedlock (pthread_mutex_t * __restrict, const struct timespec * __restrict)
Definition at line 1081 of file pthread-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
pthread_mutex_trylock()
int pthread_mutex_trylock (pthread_mutex_t * mutex)
Definition at line 1054 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     unsigned int this_tid = mlibc::this_tid();
     unsigned int expected = __atomic_load_n(&mutex->__mlibc_state, __ATOMIC_RELAXED);
     if(!expected) {
         // Try to take the mutex here.
         if(__atomic_compare_exchange_n(&mutex->__mlibc_state,
                         &expected, this_tid, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)) {
             __ensure(!mutex->__mlibc_recursion);
             mutex->__mlibc_recursion = 1;
             return 0;
         }
     } else {
         // If this (recursive) mutex is already owned by us, increment the recursion level.
         if((expected & mutex_owner_mask) == this_tid) {
             if(!(mutex->__mlibc_flags & mutexRecursive)) {
                 return EBUSY;
             }
             ++mutex->__mlibc_recursion;
             return 0;
         }
     }
     return EBUSY;
 }
References __ensure, __mlibc_mutex::__mlibc_flags, __mlibc_mutex::__mlibc_recursion, __mlibc_mutex::__mlibc_state, EBUSY, mutex, mutex_owner_mask, mutexRecursive, SCOPE_TRACE, and mlibc::this_tid().
Referenced by test_broadcast_wakes_all(), testNormal(), and testRecursive().
pthread_mutex_unlock()
int pthread_mutex_unlock (pthread_mutex_t * mutex)
Definition at line 1087 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     // Decrement the recursion level and unlock if we hit zero.
     __ensure(mutex->__mlibc_recursion);
     if(--mutex->__mlibc_recursion)
         return 0;
     auto flags = mutex->__mlibc_flags;
     // Reset the mutex to the unlocked state.
     auto state = __atomic_exchange_n(&mutex->__mlibc_state, 0, __ATOMIC_RELEASE);
     // After this point the mutex is unlocked, and therefore we cannot access its contents as it
     // may have been destroyed by another thread.
     unsigned int this_tid = mlibc::this_tid();
     if ((flags & mutexErrorCheck) && (state & mutex_owner_mask) != this_tid)
         return EPERM;
     if ((flags & mutexErrorCheck) && !(state & mutex_owner_mask))
         return EINVAL;
     __ensure((state & mutex_owner_mask) == this_tid);
     if(state & mutex_waiters_bit) {
         // Wake the futex if there were waiters. Since the mutex might not exist at this location
         // anymore, we must conservatively ignore EACCES and EINVAL which may occur as a result.
         int e = mlibc::sys_futex_wake((int *)&mutex->__mlibc_state);
         __ensure(e >= 0 || e == EACCES || e == EINVAL);
     }
     return 0;
 }
References __ensure, __mlibc_mutex::__mlibc_flags, __mlibc_mutex::__mlibc_recursion, __mlibc_mutex::__mlibc_state, EACCES, EINVAL, EPERM, mlibc::flags, mutex, mutex_owner_mask, mutex_waiters_bit, mutexErrorCheck, SCOPE_TRACE, state, mlibc::sys_futex_wake(), and mlibc::this_tid().
Referenced by pthread_cond_timedwait(), test_broadcast_wakes_all(), test_timedwait_timedout(), testNormal(), testRecursive(), and worker().
pthread_mutexattr_destroy()
int pthread_mutexattr_destroy (pthread_mutexattr_t * attr)
Definition at line 895 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     memset(attr, 0, sizeof(*attr));
     return 0;
 }
References mlibc::attr, memset(), and SCOPE_TRACE.
Referenced by testAttr(), testNormal(), and testRecursive().
pthread_mutexattr_getprioceiling()
int pthread_mutexattr_getprioceiling (const pthread_mutexattr_t * , int *)
pthread_mutexattr_getprotocol()
int pthread_mutexattr_getprotocol (const pthread_mutexattr_t * __restrict, int * __restrict)
pthread_mutexattr_getpshared()
int pthread_mutexattr_getpshared (const pthread_mutexattr_t * attr, int * pshared)
Definition at line 929 of file pthread-stubs.cpp.
{
     *pshared = attr->__mlibc_pshared;
     return 0;
 }
References mlibc::attr.
pthread_mutexattr_getrobust()
int pthread_mutexattr_getrobust (const pthread_mutexattr_t * __restrict, int * __restrict)
pthread_mutexattr_gettype()
int pthread_mutexattr_gettype (const pthread_mutexattr_t * __restrict, int * __restrict)
pthread_mutexattr_init()
int pthread_mutexattr_init (pthread_mutexattr_t * attr)
Definition at line 886 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     attr->__mlibc_type = PTHREAD_MUTEX_DEFAULT;
     attr->__mlibc_robust = PTHREAD_MUTEX_STALLED;
     attr->__mlibc_pshared = PTHREAD_PROCESS_PRIVATE;
     attr->__mlibc_protocol = PTHREAD_PRIO_NONE;
     return 0;
 }
References mlibc::attr, PTHREAD_MUTEX_DEFAULT, PTHREAD_MUTEX_STALLED, PTHREAD_PRIO_NONE, PTHREAD_PROCESS_PRIVATE, and SCOPE_TRACE.
Referenced by testAttr(), testNormal(), and testRecursive().
pthread_mutexattr_setprioceiling()
int pthread_mutexattr_setprioceiling (pthread_mutexattr_t * attr, int prioceiling)
Definition at line 963 of file pthread-stubs.cpp.
{
     (void)attr;
     (void)prioceiling;
     return EINVAL;
 }
References mlibc::attr, and EINVAL.
pthread_mutexattr_setprotocol()
int pthread_mutexattr_setprotocol (pthread_mutexattr_t * attr, int protocol)
Definition at line 947 of file pthread-stubs.cpp.
{
     if (protocol != PTHREAD_PRIO_NONE && protocol != PTHREAD_PRIO_INHERIT
             && protocol != PTHREAD_PRIO_PROTECT)
         return EINVAL;
     attr->__mlibc_protocol = protocol;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_PRIO_INHERIT, PTHREAD_PRIO_NONE, and PTHREAD_PRIO_PROTECT.
pthread_mutexattr_setpshared()
int pthread_mutexattr_setpshared (pthread_mutexattr_t * attr, int pshared)
Definition at line 933 of file pthread-stubs.cpp.
{
     if (pshared != PTHREAD_PROCESS_PRIVATE && pshared != PTHREAD_PROCESS_SHARED)
         return EINVAL;
     attr->__mlibc_pshared = pshared;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
pthread_mutexattr_setrobust()
int pthread_mutexattr_setrobust (pthread_mutexattr_t * attr, int robust)
Definition at line 921 of file pthread-stubs.cpp.
{
     if (robust != PTHREAD_MUTEX_STALLED && robust != PTHREAD_MUTEX_ROBUST)
         return EINVAL;
     attr->__mlibc_robust = robust;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_MUTEX_ROBUST, and PTHREAD_MUTEX_STALLED.
pthread_mutexattr_settype()
int pthread_mutexattr_settype (pthread_mutexattr_t * attr, int type)
Definition at line 907 of file pthread-stubs.cpp.
{
     if (type != PTHREAD_MUTEX_NORMAL && type != PTHREAD_MUTEX_ERRORCHECK
             && type != PTHREAD_MUTEX_RECURSIVE)
         return EINVAL;
     attr->__mlibc_type = type;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_MUTEX_ERRORCHECK, PTHREAD_MUTEX_NORMAL, and PTHREAD_MUTEX_RECURSIVE.
Referenced by testRecursive().
pthread_once()
int pthread_once (pthread_once_t * once, void(*)(void) function)
Definition at line 849 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto expected = __atomic_load_n(&once->__mlibc_done, __ATOMIC_ACQUIRE);
     // fast path: the function was already run.
     while(!(expected & onceComplete)) {
         if(!expected) {
             // try to acquire the mutex.
             if(!__atomic_compare_exchange_n(&once->__mlibc_done,
                     &expected, onceLocked, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE))
                 continue;
             function();
             // unlock the mutex.
             __atomic_exchange_n(&once->__mlibc_done, onceComplete, __ATOMIC_RELEASE);
             if(int e = mlibc::sys_futex_wake((int *)&once->__mlibc_done); e)
                 __ensure(!"sys_futex_wake() failed");
             return 0;
         }else{
             // a different thread is currently running the initializer.
             __ensure(expected == onceLocked);
             if(int e = mlibc::sys_futex_wait((int *)&once->__mlibc_done, onceLocked, nullptr); e)
                 __ensure(!"sys_futex_wait() failed");
             expected =  __atomic_load_n(&once->__mlibc_done, __ATOMIC_ACQUIRE);
         }
     }
     return 0;
 }
References __ensure, __mlibc_once::__mlibc_done, onceComplete, onceLocked, SCOPE_TRACE, mlibc::sys_futex_wait(), and mlibc::sys_futex_wake().
Referenced by cacheFileTable(), SignalGuard::SignalGuard(), and SignalGuard::~SignalGuard().
pthread_rwlock_destroy()
int pthread_rwlock_destroy (pthread_rwlock_t * rw)
Definition at line 1502 of file pthread-stubs.cpp.
{
     __ensure(!rw->__mlibc_m);
     __ensure(!rw->__mlibc_rc);
     return 0;
 }
References __ensure, __mlibc_fair_rwlock::__mlibc_m, and __mlibc_fair_rwlock::__mlibc_rc.
pthread_rwlock_init()
int pthread_rwlock_init (pthread_rwlock_t * __restrict, const pthread_rwlockattr_t * __restrict)
pthread_rwlock_rdlock()
int pthread_rwlock_rdlock (pthread_rwlock_t * rw)
Definition at line 1586 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     if (rw->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_rwlock_t flags were non-zero"
             << frg::endlog;
     }
     // Increment the reader count while holding the __mlibc_m mutex.
     rwlock_m_lock(rw, false);
     __atomic_fetch_add(&rw->__mlibc_rc, 1, __ATOMIC_ACQUIRE);
     rwlock_m_unlock(rw);
     return 0;
 }
References __mlibc_fair_rwlock::__mlibc_flags, __mlibc_fair_rwlock::__mlibc_rc, mlibc::panicLogger, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), and SCOPE_TRACE.
Referenced by test_read_allows_read(), test_read_lock_unlock(), and test_read_prevents_write().
pthread_rwlock_tryrdlock()
int pthread_rwlock_tryrdlock (pthread_rwlock_t * rw)
Definition at line 1569 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     if (rw->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_rwlock_t flags were non-zero"
             << frg::endlog;
     }
     // Increment the reader count while holding the __mlibc_m mutex.
     if(int e = rwlock_m_trylock(rw, false); e)
         return e;
     __atomic_fetch_add(&rw->__mlibc_rc, 1, __ATOMIC_ACQUIRE);
     rwlock_m_unlock(rw);
     return 0;
 }
References __mlibc_fair_rwlock::__mlibc_flags, __mlibc_fair_rwlock::__mlibc_rc, mlibc::panicLogger, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_trylock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), and SCOPE_TRACE.
Referenced by test_read_allows_read(), test_read_trylock_unlock(), and test_write_prevents_read().
pthread_rwlock_trywrlock()
int pthread_rwlock_trywrlock (pthread_rwlock_t * rw)
Definition at line 1508 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     if (rw->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_rwlock_t flags were non-zero"
             << frg::endlog;
     }
     // Take the __mlibc_m mutex.
     // Will be released in pthread_rwlock_unlock().
     if(int e = rwlock_m_trylock(rw, true))
         return e;
     // Check that there are no readers.
     unsigned int rc_expected = __atomic_load_n(&rw->__mlibc_rc, __ATOMIC_ACQUIRE);
     if(rc_expected) {
         rwlock_m_unlock(rw);
         return EBUSY;
     }
     return 0;
 }
References __mlibc_fair_rwlock::__mlibc_flags, __mlibc_fair_rwlock::__mlibc_rc, EBUSY, mlibc::panicLogger, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_trylock(), anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), and SCOPE_TRACE.
Referenced by test_read_prevents_write(), test_write_prevents_write(), and test_write_trylock_unlock().
pthread_rwlock_unlock()
int pthread_rwlock_unlock (pthread_rwlock_t * rw)
Definition at line 1602 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     unsigned int rc_expected = __atomic_load_n(&rw->__mlibc_rc, __ATOMIC_RELAXED);
     if(!rc_expected) {
         // We are doing a write-unlock.
         rwlock_m_unlock(rw);
         return 0;
     }else{
         // We are doing a read-unlock.
         while(true) {
             unsigned int count = rc_expected & rc_count_mask;
             __ensure(count);
             // Try to decrement the count.
             if(count == 1 && (rc_expected & rc_waiters_bit)) {
                 unsigned int desired = 0;
                 if(!__atomic_compare_exchange_n(&rw->__mlibc_rc,
                         &rc_expected, desired, false, __ATOMIC_RELEASE, __ATOMIC_RELAXED))
                     continue;
                 // Wake the futex.
                 mlibc::sys_futex_wake((int *)&rw->__mlibc_rc);
                 break;
             }else{
                 unsigned int desired = (rc_expected & ~rc_count_mask) | (count - 1);
                 if(!__atomic_compare_exchange_n(&rw->__mlibc_rc,
                         &rc_expected, desired, false, __ATOMIC_RELEASE, __ATOMIC_RELAXED))
                     continue;
                 break;
             }
         }
         return 0;
     }
 }
References __ensure, __mlibc_fair_rwlock::__mlibc_rc, count, rc_count_mask, rc_waiters_bit, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_unlock(), SCOPE_TRACE, and mlibc::sys_futex_wake().
Referenced by test_read_allows_read(), test_read_lock_unlock(), test_read_prevents_write(), test_read_trylock_unlock(), test_write_lock_unlock(), test_write_prevents_read(), test_write_prevents_write(), and test_write_trylock_unlock().
pthread_rwlock_wrlock()
int pthread_rwlock_wrlock (pthread_rwlock_t * rw)
Definition at line 1531 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     if (rw->__mlibc_flags != 0) {
         mlibc::panicLogger() << "mlibc: pthread_rwlock_t flags were non-zero"
             << frg::endlog;
     }
     // Take the __mlibc_m mutex.
     // Will be released in pthread_rwlock_unlock().
     rwlock_m_lock(rw, true);
     // Now wait until there are no more readers.
     unsigned int rc_expected = __atomic_load_n(&rw->__mlibc_rc, __ATOMIC_ACQUIRE);
     while(true) {
         if(!rc_expected)
             break;
         __ensure(rc_expected & rc_count_mask);
         // Try to set the waiters bit.
         if(!(rc_expected & rc_waiters_bit)) {
             unsigned int desired = rc_expected | rc_count_mask;
             if(!__atomic_compare_exchange_n(&rw->__mlibc_rc,
                     &rc_expected, desired, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE))
                 continue;
         }
         // Wait on the futex.
         mlibc::sys_futex_wait((int *)&rw->__mlibc_rc, rc_expected | rc_waiters_bit, nullptr);
         // Re-check the reader counter.
         rc_expected = __atomic_load_n(&rw->__mlibc_rc, __ATOMIC_ACQUIRE);
     }
     return 0;
 }
References __ensure, __mlibc_fair_rwlock::__mlibc_flags, __mlibc_fair_rwlock::__mlibc_rc, mlibc::panicLogger, rc_count_mask, rc_waiters_bit, anonymous_namespace{pthread-stubs.cpp}::rwlock_m_lock(), SCOPE_TRACE, and mlibc::sys_futex_wait().
Referenced by test_write_lock_unlock(), test_write_prevents_read(), and test_write_prevents_write().
pthread_rwlockattr_destroy()
int pthread_rwlockattr_destroy (pthread_rwlockattr_t *)
Definition at line 1487 of file pthread-stubs.cpp.
{
     return 0;
 }
Referenced by test_attr().
pthread_rwlockattr_getpshared()
int pthread_rwlockattr_getpshared (const pthread_rwlockattr_t * __restrict, int * __restrict)
pthread_rwlockattr_init()
int pthread_rwlockattr_init (pthread_rwlockattr_t * attr)
Definition at line 1468 of file pthread-stubs.cpp.
{
     attr->__mlibc_pshared = PTHREAD_PROCESS_PRIVATE;
     return 0;
 }
References mlibc::attr, and PTHREAD_PROCESS_PRIVATE.
Referenced by test_attr().
pthread_rwlockattr_setpshared()
int pthread_rwlockattr_setpshared (pthread_rwlockattr_t * attr, int pshared)
Definition at line 1479 of file pthread-stubs.cpp.
{
     if (pshared != PTHREAD_PROCESS_SHARED && pshared != PTHREAD_PROCESS_PRIVATE)
         return EINVAL;
     attr->__mlibc_pshared = pshared;
     return 0;
 }
References mlibc::attr, EINVAL, PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
Referenced by test_attr().
pthread_self()
pthread_t pthread_self (void)
Definition at line 359 of file pthread-stubs.cpp.
{
     return reinterpret_cast<pthread_t>(mlibc::get_current_tcb());
 }
References mlibc::get_current_tcb().
Referenced by main(), and test_getattrnp().
pthread_setcancelstate()
int pthread_setcancelstate (int state, int * oldstate)
Definition at line 647 of file pthread-stubs.cpp.
{
     if (state != PTHREAD_CANCEL_ENABLE && state != PTHREAD_CANCEL_DISABLE)
         return EINVAL;
     auto self = reinterpret_cast<Tcb *>(mlibc::get_current_tcb());
     int old_value = self->cancelBits;
     while (1) {
         int new_value = old_value & ~tcbCancelEnableBit;
         if (state == PTHREAD_CANCEL_ENABLE)
             new_value |= tcbCancelEnableBit;
         if (oldstate)
             *oldstate = ((old_value & tcbCancelEnableBit)
                     ? PTHREAD_CANCEL_ENABLE
                     : PTHREAD_CANCEL_DISABLE);
         // Avoid unecessary atomic op.
         if (old_value == new_value)
             break;
         int current_value = old_value;
         if (__atomic_compare_exchange_n(&self->cancelBits, &current_value,
                     new_value, true, __ATOMIC_RELAXED, __ATOMIC_RELAXED)) {
             if (mlibc::tcb_async_cancelled(new_value))
                 __mlibc_do_cancel();
             sigset_t set = {};
             sigaddset(&set, SIGCANCEL);
             if (new_value & PTHREAD_CANCEL_ENABLE)
                 sigprocmask(SIG_UNBLOCK, &set, NULL);
             else
                 sigprocmask(SIG_BLOCK, &set, NULL);
             break;
         }
         old_value = current_value;
     }
     return 0;
 }
References __mlibc_do_cancel(), Tcb::cancelBits, EINVAL, mlibc::get_current_tcb(), NULL, PTHREAD_CANCEL_DISABLE, PTHREAD_CANCEL_ENABLE, SIG_BLOCK, SIG_UNBLOCK, sigaddset(), SIGCANCEL, sigprocmask(), state, mlibc::tcb_async_cancelled(), and anonymous_namespace{tcb.hpp}::tcbCancelEnableBit.
Referenced by getspnam_r(), posix_spawn(), shm_open(), vsyslog(), worker1(), worker2(), worker3(), worker4(), and worker5().
pthread_setcanceltype()
int pthread_setcanceltype (int type, int * oldtype)
Definition at line 612 of file pthread-stubs.cpp.
{
     if (type != PTHREAD_CANCEL_DEFERRED && type != PTHREAD_CANCEL_ASYNCHRONOUS)
         return EINVAL;
     auto self = reinterpret_cast<Tcb *>(mlibc::get_current_tcb());
     int old_value = self->cancelBits;
     while (1) {
         int new_value = old_value & ~tcbCancelAsyncBit;
         if (type == PTHREAD_CANCEL_ASYNCHRONOUS)
             new_value |= tcbCancelAsyncBit;
         if (oldtype)
             *oldtype = ((old_value & tcbCancelAsyncBit)
                     ? PTHREAD_CANCEL_ASYNCHRONOUS
                     : PTHREAD_CANCEL_DEFERRED);
         // Avoid unecessary atomic op.
         if (old_value == new_value)
             break;
         int current_value = old_value;
         if (__atomic_compare_exchange_n(&self->cancelBits, &current_value,
                     new_value, true, __ATOMIC_RELAXED, __ATOMIC_RELAXED)) {
             if (mlibc::tcb_async_cancelled(new_value))
                 __mlibc_do_cancel();
             break;
         }
         old_value = current_value;
     }
     return 0;
 }
References __mlibc_do_cancel(), Tcb::cancelBits, EINVAL, mlibc::get_current_tcb(), PTHREAD_CANCEL_ASYNCHRONOUS, PTHREAD_CANCEL_DEFERRED, mlibc::tcb_async_cancelled(), and anonymous_namespace{tcb.hpp}::tcbCancelAsyncBit.
Referenced by worker1().
pthread_setname_np()
int pthread_setname_np (pthread_t , const char *)
Definition at line 492 of file pthread-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: pthread_setname_np is a stub" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
pthread_setschedparam()
int pthread_setschedparam (pthread_t thread, int policy, const struct sched_param * param)
Definition at line 502 of file pthread-stubs.cpp.
{
     auto tcb = reinterpret_cast<Tcb*>(thread);
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setschedparam, ENOSYS);
     if(int e = mlibc::sys_setschedparam(tcb, policy, param); e) {
         return e;
     }
     return 0;
 }
References ENOSYS, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setschedparam().
Referenced by main().
pthread_setspecific()
int pthread_setspecific (pthread_key_t key, const void * value)
Definition at line 827 of file pthread-stubs.cpp.
{
     SCOPE_TRACE();
     auto self = mlibc::get_current_tcb();
     auto g = frg::guard(&key_mutex_);
     if (key >= PTHREAD_KEYS_MAX || !key_globals_[key].in_use)
         return EINVAL;
     (*self->localKeys)[key].value = const_cast<void *>(value);
     (*self->localKeys)[key].generation = key_globals_[key].generation;
     return 0;
 }
References EINVAL, g, mlibc::get_current_tcb(), mlibc::guard, anonymous_namespace{pthread-stubs.cpp}::key_globals_, anonymous_namespace{pthread-stubs.cpp}::key_mutex_, PTHREAD_KEYS_MAX, SCOPE_TRACE, and value.
Referenced by dtor1(), dtor3(), main(), worker1(), and worker2().
pthread_testcancel()
void pthread_testcancel (void)
Definition at line 688 of file pthread-stubs.cpp.
{
     auto self = reinterpret_cast<Tcb *>(mlibc::get_current_tcb());
     int value = self->cancelBits;
     if ((value & tcbCancelEnableBit) && (value & tcbCancelTriggerBit)) {
         __mlibc_do_cancel();
         __builtin_unreachable();
     }
 }
References __mlibc_do_cancel(), mlibc::get_current_tcb(), anonymous_namespace{tcb.hpp}::tcbCancelEnableBit, anonymous_namespace{tcb.hpp}::tcbCancelTriggerBit, and value.
Referenced by system(), worker3(), and worker5().