Fennix Userspace: Userspace/apps/base/busybox/procps/iostat.c File Reference
iostat.c File Reference
#include "libbb.h"
#include <sys/utsname.h>
Data Structures
struct stats_cpu_t
struct stats_cpu_pair_t
struct stats_dev_data_t
struct stats_dev
struct globals
struct globals.unit
Macros
#define debug(fmt, ...) ((void)0)
#define MAX_DEVICE_NAME 12
#define MAX_DEVICE_NAME_STR "12"
#define FMT_DATA "ll"
#define CPUTIME_MAX (~0ULL)
#define G (*ptr_to_globals)
#define INIT_G()
Typedefs
typedef unsigned long long cputime_t
typedef long long icputime_t
typedef struct stats_dev stats_dev_t
Enumerations
enum {
STATS_CPU_USER , STATS_CPU_NICE , STATS_CPU_SYSTEM , STATS_CPU_IDLE ,
STATS_CPU_IOWAIT , STATS_CPU_IRQ , STATS_CPU_SOFTIRQ , STATS_CPU_STEAL ,
STATS_CPU_GUEST , GLOBAL_UPTIME , SMP_UPTIME , N_STATS_CPU
}
enum {
OPT_c = 1 << 0 , OPT_d = 1 << 1 , OPT_t = 1 << 2 , OPT_z = 1 << 3 ,
OPT_k = 1 << 4 , OPT_m = 1 << 5
}
Functions
static ALWAYS_INLINE int this_is_smp (void)
static void print_header (void)
static void get_localtime (struct tm *ptm)
static void print_timestamp (void)
static cputime_t get_smp_uptime (void)
static void get_cpu_statistics (stats_cpu_t *sc)
static ALWAYS_INLINE cputime_t get_interval (cputime_t old, cputime_t new)
static ALWAYS_INLINE cputime_t overflow_safe_sub (cputime_t prev, cputime_t curr)
static double percent_value (cputime_t prev, cputime_t curr, cputime_t itv)
static void print_stats_cpu_struct (stats_cpu_pair_t *stats)
static void cpu_report (stats_cpu_pair_t *stats)
static void print_stats_dev_struct (stats_dev_t *stats_dev, cputime_t itv)
static void print_devstat_header (void)
static int is_partition (const char *dev)
static stats_dev_t * stats_dev_find_or_new (const char *dev_name)
static void stats_dev_free (stats_dev_t *stats_dev)
static void do_disk_statistics (cputime_t itv)
static void dev_report (cputime_t itv)
int iostat_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
stats_cpu_t
struct stats_cpu_t
Definition at line 57 of file iostat.c.
Data Fields
cputime_t vector[N_STATS_CPU]
stats_cpu_pair_t
struct stats_cpu_pair_t
Definition at line 61 of file iostat.c.
Data Fields
stats_cpu_t * curr
cputime_t itv
stats_cpu_t * prev
stats_dev_data_t
struct stats_dev_data_t
Definition at line 67 of file iostat.c.
Data Fields
unsigned long rd_ops
unsigned long long rd_sectors
unsigned long wr_ops
unsigned long long wr_sectors
stats_dev
struct stats_dev
Definition at line 74 of file iostat.c.
Data Fields
stats_dev_data_t curr_data
char dname[MAX_DEVICE_NAME+1]
struct stats_dev * next
stats_dev_data_t prev_data
globals.unit
struct globals.unit
Definition at line 89 of file iostat.c.
Data Fields
unsigned div
const char * str
Macro Definition Documentation
CPUTIME_MAX
#define CPUTIME_MAX (~0ULL)
Definition at line 32 of file iostat.c.
debug
#define debug (fmt, ...) ((void)0)
Definition at line 23 of file iostat.c.
FMT_DATA
#define FMT_DATA "ll"
Definition at line 31 of file iostat.c.
G
#define G (*ptr_to_globals)
Definition at line 94 of file iostat.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    G.unit.str = "Blk"; \
    G.unit.div = 1; \
} while (0)
Definition at line 95 of file iostat.c.
MAX_DEVICE_NAME
#define MAX_DEVICE_NAME 12
Definition at line 25 of file iostat.c.
MAX_DEVICE_NAME_STR
#define MAX_DEVICE_NAME_STR "12"
Definition at line 26 of file iostat.c.
Typedef Documentation
cputime_t
typedef unsigned long long cputime_t
Definition at line 29 of file iostat.c.
icputime_t
typedef long long icputime_t
Definition at line 30 of file iostat.c.
stats_dev_t
typedef struct stats_dev stats_dev_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STATS_CPU_USER
STATS_CPU_NICE
STATS_CPU_SYSTEM
STATS_CPU_IDLE
STATS_CPU_IOWAIT
STATS_CPU_IRQ
STATS_CPU_SOFTIRQ
STATS_CPU_STEAL
STATS_CPU_GUEST
GLOBAL_UPTIME
SMP_UPTIME
N_STATS_CPU
Definition at line 40 of file iostat.c.
      {
     STATS_CPU_USER,
     STATS_CPU_NICE,
     STATS_CPU_SYSTEM,
     STATS_CPU_IDLE,
     STATS_CPU_IOWAIT,
     STATS_CPU_IRQ,
     STATS_CPU_SOFTIRQ,
     STATS_CPU_STEAL,
     STATS_CPU_GUEST,
     GLOBAL_UPTIME,
     SMP_UPTIME,
     N_STATS_CPU,
 };
anonymous enum
anonymous enum
Enumerator
OPT_c
OPT_d
OPT_t
OPT_z
OPT_k
OPT_m
Definition at line 102 of file iostat.c.
      {
     OPT_c = 1 << 0,
     OPT_d = 1 << 1,
     OPT_t = 1 << 2,
     OPT_z = 1 << 3,
     OPT_k = 1 << 4,
     OPT_m = 1 << 5,
 };
Function Documentation
cpu_report()
static void cpu_report (stats_cpu_pair_t * stats) static
Definition at line 252 of file iostat.c.
 {
     /* Always print a header */
     puts("avg-cpu:  %user   %nice %system %iowait  %steal   %idle");
     /* Print current statistics */
     print_stats_cpu_struct(stats);
 }
References print_stats_cpu_struct(), and puts().
Referenced by iostat_main().
dev_report()
static void dev_report (cputime_t itv) static
Definition at line 377 of file iostat.c.
 {
     /* Always print a header */
     print_devstat_header();
     /* Fetch current disk statistics */
     do_disk_statistics(itv);
 }
References do_disk_statistics(), and print_devstat_header().
Referenced by iostat_main().
do_disk_statistics()
static void do_disk_statistics (cputime_t itv) static
Definition at line 320 of file iostat.c.
 {
     char buf[128];
     char dev_name[MAX_DEVICE_NAME + 1];
     unsigned long long rd_sec_or_dummy;
     unsigned long long wr_sec_or_dummy;
     stats_dev_data_t *curr_data;
     stats_dev_t *stats_dev;
     FILE *fp;
     int rc;
     fp = xfopen_for_read("/proc/diskstats");
     /* Read and possibly print stats from /proc/diskstats */
     while (fgets(buf, sizeof(buf), fp)) {
         sscanf(buf, "%*s %*s %"MAX_DEVICE_NAME_STR"s", dev_name);
         if (G.dev_name_list) {
             /* Is device name in list? */
             if (!llist_find_str(G.dev_name_list, dev_name))
                 continue;
         } else if (is_partition(dev_name)) {
             continue;
         }
         stats_dev = stats_dev_find_or_new(dev_name);
         curr_data = &stats_dev->curr_data;
         rc = sscanf(buf, "%*s %*s %*s %lu %llu %llu %llu %lu %*s %llu",
             &curr_data->rd_ops,
             &rd_sec_or_dummy,
             &curr_data->rd_sectors,
             &wr_sec_or_dummy,
             &curr_data->wr_ops,
             &curr_data->wr_sectors);
         if (rc != 6) {
             curr_data->rd_sectors = rd_sec_or_dummy;
             curr_data->wr_sectors = wr_sec_or_dummy;
             //curr_data->rd_ops = ;
             curr_data->wr_ops = (unsigned long)curr_data->rd_sectors;
         }
         if (!G.dev_name_list /* User didn't specify device */
          && !G.show_all
          && curr_data->rd_ops == 0
          && curr_data->wr_ops == 0
         ) {
             /* Don't print unused device */
             continue;
         }
         /* Print current statistics */
         print_stats_dev_struct(stats_dev, itv);
         stats_dev->prev_data = *curr_data;
     }
     fclose(fp);
 }
References buf, stats_dev::curr_data, fclose(), fgets, G, is_partition(), llist_find_str(), MAX_DEVICE_NAME, MAX_DEVICE_NAME_STR, stats_dev::prev_data, print_stats_dev_struct(), rc, stats_dev_data_t::rd_ops, stats_dev_data_t::rd_sectors, sscanf(), stats_dev_find_or_new(), stats_dev_data_t::wr_ops, stats_dev_data_t::wr_sectors, and xfopen_for_read().
Referenced by dev_report().
get_cpu_statistics()
static void get_cpu_statistics (stats_cpu_t * sc) static
Definition at line 163 of file iostat.c.
 {
     FILE *fp;
     char buf[1024];
     fp = xfopen_for_read("/proc/stat");
     memset(sc, 0, sizeof(*sc));
     while (fgets(buf, sizeof(buf), fp)) {
         int i;
         char *ibuf;
         /* Does the line start with "cpu "? */
         if (!starts_with_cpu(buf) || buf[3] != ' ') {
             continue;
         }
         ibuf = buf + 4;
         for (i = STATS_CPU_USER; i <= STATS_CPU_GUEST; i++) {
             ibuf = skip_whitespace(ibuf);
             sscanf(ibuf, "%"FMT_DATA"u", &sc->vector[i]);
             if (i != STATS_CPU_GUEST) {
                 sc->vector[GLOBAL_UPTIME] += sc->vector[i];
             }
             ibuf = skip_non_whitespace(ibuf);
         }
         break;
     }
     if (this_is_smp()) {
         sc->vector[SMP_UPTIME] = get_smp_uptime();
     }
     fclose(fp);
 }
References buf, fclose(), fgets, FMT_DATA, get_smp_uptime(), GLOBAL_UPTIME, i, memset(), skip_non_whitespace(), skip_whitespace(), SMP_UPTIME, sscanf(), starts_with_cpu(), STATS_CPU_GUEST, STATS_CPU_USER, this_is_smp(), stats_cpu_t::vector, and xfopen_for_read().
Referenced by iostat_main().
get_interval()
static ALWAYS_INLINE cputime_t get_interval (cputime_t old, cputime_t new) static
Definition at line 199 of file iostat.c.
 {
     cputime_t itv = new - old;
     return (itv == 0) ? 1 : itv;
 }
References old.
Referenced by iostat_main().
get_localtime()
static void get_localtime (struct tm * ptm) static
Definition at line 131 of file iostat.c.
 {
     time_t timer;
     time(&timer);
     localtime_r(&timer, ptm);
 }
References time().
Referenced by iostat_main().
get_smp_uptime()
static cputime_t get_smp_uptime (void) static
Definition at line 147 of file iostat.c.
 {
     FILE *fp;
     unsigned long sec, dec;
     fp = xfopen_for_read("/proc/uptime");
     if (fscanf(fp, "%lu.%lu", &sec, &dec) != 2)
         bb_error_msg_and_die("can't read '%s'", "/proc/uptime");
     fclose(fp);
     return (cputime_t)sec * G.clk_tck + dec * G.clk_tck / 100;
 }
References bb_error_msg_and_die(), fclose(), fscanf(), G, and xfopen_for_read().
Referenced by get_cpu_statistics().
iostat_main()
int iostat_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 398 of file iostat.c.
 {
     int opt;
     unsigned interval;
     int count;
     stats_cpu_t stats_data[2];
     smallint current_stats;
     INIT_G();
     memset(&stats_data, 0, sizeof(stats_data));
     /* Get number of clock ticks per sec */
     G.clk_tck = bb_clk_tck();
     /* Determine number of CPUs */
     G.total_cpus = get_cpu_count();
     if (G.total_cpus == 0)
         G.total_cpus = 1;
     /* Parse and process arguments */
     /* -k and -m are mutually exclusive */
     opt = getopt32(argv, "^" "cdtzkm" "\0" "k--m:m--k");
     if (!(opt & (OPT_c + OPT_d)))
         /* Default is -cd */
         opt |= OPT_c + OPT_d;
     argv += optind;
     /* Store device names into device list */
     while (*argv && !isdigit(*argv[0])) {
         if (strcmp(*argv, "ALL") != 0) {
             /* If not ALL, save device name */
             char *dev_name = skip_dev_pfx(*argv);
             if (!llist_find_str(G.dev_name_list, dev_name)) {
                 llist_add_to(&G.dev_name_list, dev_name);
             }
         } else {
             G.show_all = 1;
         }
         argv++;
     }
     interval = 0;
     count = 1;
     if (*argv) {
         /* Get interval */
         interval = xatoi_positive(*argv);
         count = (interval != 0 ? -1 : 1);
         argv++;
         if (*argv)
             /* Get count value */
             count = xatoi_positive(*argv);
     }
     if (opt & OPT_m) {
         G.unit.str = " MB";
         G.unit.div = 2048;
     }
     if (opt & OPT_k) {
         G.unit.str = " kB";
         G.unit.div = 2;
     }
     get_localtime(&G.tmtime);
     /* Display header */
     print_header();
     current_stats = 0;
     /* Main loop */
     for (;;) {
         stats_cpu_pair_t stats;
         stats.prev = &stats_data[current_stats ^ 1];
         stats.curr = &stats_data[current_stats];
         /* Fill the time structure */
         get_localtime(&G.tmtime);
         /* Fetch current CPU statistics */
         get_cpu_statistics(stats.curr);
         /* Get interval */
         stats.itv = get_interval(
             stats.prev->vector[GLOBAL_UPTIME],
             stats.curr->vector[GLOBAL_UPTIME]
         );
         if (opt & OPT_t)
             print_timestamp();
         if (opt & OPT_c) {
             cpu_report(&stats);
             if (opt & OPT_d)
                 /* Separate outputs by a newline */
                 bb_putchar('\n');
         }
         if (opt & OPT_d) {
             if (this_is_smp()) {
                 stats.itv = get_interval(
                     stats.prev->vector[SMP_UPTIME],
                     stats.curr->vector[SMP_UPTIME]
                 );
             }
             dev_report(stats.itv);
         }
         bb_putchar('\n');
         if (count > 0) {
             if (--count == 0)
                 break;
         }
         /* Swap stats */
         current_stats ^= 1;
         sleep(interval);
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         llist_free(G.dev_name_list, NULL);
         stats_dev_free(G.stats_dev_list);
         free(&G);
     }
     return EXIT_SUCCESS;
 }
References argv, bb_clk_tck(), bb_putchar(), count, cpu_report(), stats_cpu_pair_t::curr, dev_report(), EXIT_SUCCESS, free, G, get_cpu_count(), get_cpu_statistics(), get_interval(), get_localtime(), getopt32(), GLOBAL_UPTIME, INIT_G, isdigit, stats_cpu_pair_t::itv, llist_add_to(), llist_find_str(), llist_free(), memset(), NULL, opt, OPT_c, OPT_d, OPT_k, OPT_m, OPT_t, optind, stats_cpu_pair_t::prev, print_header(), print_timestamp(), skip_dev_pfx(), sleep(), SMP_UPTIME, stats_dev_free(), strcmp, this_is_smp(), stats_cpu_t::vector, and xatoi_positive().
is_partition()
static int is_partition (const char * dev) static
Definition at line 291 of file iostat.c.
 {
     /* Ok, this is naive... */
     return ((dev[0] - 's') | (dev[1] - 'd') | (dev[2] - 'a')) == 0 && isdigit(dev[3]);
 }
References isdigit.
Referenced by do_disk_statistics().
overflow_safe_sub()
static ALWAYS_INLINE cputime_t overflow_safe_sub (cputime_t prev, cputime_t curr) static
Definition at line 226 of file iostat.c.
 {
     return curr - prev;
 }
Referenced by percent_value().
percent_value()
static double percent_value (cputime_t prev, cputime_t curr, cputime_t itv) static
Definition at line 232 of file iostat.c.
 {
     return ((double)overflow_safe_sub(prev, curr)) / itv * 100;
 }
References overflow_safe_sub().
Referenced by print_stats_cpu_struct(), and print_stats_dev_struct().
print_devstat_header()
static void print_devstat_header (void) static
Definition at line 279 of file iostat.c.
 {
     printf("Device:%15s%6s%s/s%6s%s/s%6s%s%6s%s\n",
         "tps",
         G.unit.str, "_read", G.unit.str, "_wrtn",
         G.unit.str, "_read", G.unit.str, "_wrtn"
     );
 }
References G, and printf().
Referenced by dev_report().
print_header()
static void print_header (void) static
Definition at line 116 of file iostat.c.
 {
     char buf[32];
     struct utsname uts;
     uname(&uts); /* never fails */
     /* Date representation for the current locale */
     strftime(buf, sizeof(buf), "%x", &G.tmtime);
     printf("%s %s (%s) \t%s \t_%s_\t(%u CPU)\n\n",
             uts.sysname, uts.release, uts.nodename,
             buf, uts.machine, G.total_cpus);
 }
References buf, G, utsname::machine, utsname::nodename, printf(), utsname::release, strftime(), utsname::sysname, and uname().
Referenced by iostat_main().
print_stats_cpu_struct()
static void print_stats_cpu_struct (stats_cpu_pair_t * stats) static
Definition at line 237 of file iostat.c.
 {
     cputime_t *p = stats->prev->vector;
     cputime_t *c = stats->curr->vector;
     printf("        %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f\n",
         percent_value(p[STATS_CPU_USER]  , c[STATS_CPU_USER]  , stats->itv),
         percent_value(p[STATS_CPU_NICE]  , c[STATS_CPU_NICE]  , stats->itv),
         percent_value(p[STATS_CPU_SYSTEM] + p[STATS_CPU_SOFTIRQ] + p[STATS_CPU_IRQ],
             c[STATS_CPU_SYSTEM] + c[STATS_CPU_SOFTIRQ] + c[STATS_CPU_IRQ], stats->itv),
         percent_value(p[STATS_CPU_IOWAIT], c[STATS_CPU_IOWAIT], stats->itv),
         percent_value(p[STATS_CPU_STEAL] , c[STATS_CPU_STEAL] , stats->itv),
         percent_value(p[STATS_CPU_IDLE]  , c[STATS_CPU_IDLE]  , stats->itv)
     );
 }
References c, stats_cpu_pair_t::curr, stats_cpu_pair_t::itv, p, percent_value(), stats_cpu_pair_t::prev, printf(), STATS_CPU_IDLE, STATS_CPU_IOWAIT, STATS_CPU_IRQ, STATS_CPU_NICE, STATS_CPU_SOFTIRQ, STATS_CPU_STEAL, STATS_CPU_SYSTEM, STATS_CPU_USER, and stats_cpu_t::vector.
Referenced by cpu_report().
print_stats_dev_struct()
static void print_stats_dev_struct (stats_dev_t * stats_dev, cputime_t itv) static
Definition at line 261 of file iostat.c.
 {
     stats_dev_data_t *p = &stats_dev->prev_data;
     stats_dev_data_t *c = &stats_dev->curr_data;
     if (option_mask32 & OPT_z)
         if (p->rd_ops == c->rd_ops && p->wr_ops == c->wr_ops)
             return;
     printf("%-13s %8.2f %12.2f %12.2f %10llu %10llu\n",
         stats_dev->dname,
         percent_value(p->rd_ops + p->wr_ops, c->rd_ops + c->wr_ops, itv),
         percent_value(p->rd_sectors, c->rd_sectors, itv) / G.unit.div,
         percent_value(p->wr_sectors, c->wr_sectors, itv) / G.unit.div,
         (c->rd_sectors - p->rd_sectors) / G.unit.div,
         (c->wr_sectors - p->wr_sectors) / G.unit.div
     );
 }
References c, stats_dev::curr_data, stats_dev::dname, G, OPT_z, option_mask32, p, percent_value(), stats_dev::prev_data, and printf().
Referenced by do_disk_statistics().
print_timestamp()
static void print_timestamp (void) static
Definition at line 138 of file iostat.c.
 {
     char buf[64];
     /* %x: date representation for the current locale */
     /* %X: time representation for the current locale */
     strftime(buf, sizeof(buf), "%x %X", &G.tmtime);
     puts(buf);
 }
References buf, G, puts(), and strftime().
Referenced by iostat_main().
stats_dev_find_or_new()
static stats_dev_t* stats_dev_find_or_new (const char * dev_name) static
Definition at line 297 of file iostat.c.
 {
     stats_dev_t **curr = &G.stats_dev_list;
     while (*curr != NULL) {
         if (strcmp((*curr)->dname, dev_name) == 0)
             return *curr;
         curr = &(*curr)->next;
     }
     *curr = xzalloc(sizeof(stats_dev_t));
     strncpy((*curr)->dname, dev_name, MAX_DEVICE_NAME);
     return *curr;
 }
References G, MAX_DEVICE_NAME, stats_dev::next, NULL, strcmp, strncpy(), and xzalloc().
Referenced by do_disk_statistics().
stats_dev_free()
static void stats_dev_free (stats_dev_t * stats_dev) static
Definition at line 312 of file iostat.c.
 {
     if (stats_dev) {
         stats_dev_free(stats_dev->next);
         free(stats_dev);
     }
 }
References free, and stats_dev::next.
Referenced by iostat_main().
this_is_smp()
static ALWAYS_INLINE int this_is_smp (void) static
Definition at line 111 of file iostat.c.
 {
     return (G.total_cpus > 1);
 }
References G.
Referenced by get_cpu_statistics(), and iostat_main().