Fennix: Userspace/apps/base/bash/examples/loadables/mypid.c File Reference
mypid.c File Reference
#include <config.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include "builtins.h"
#include "shell.h"
Macros
#define INIT_DYNAMIC_VAR(var, val, gfunc, afunc)
Functions
static SHELL_VAR * assign_mypid (SHELL_VAR *self, char *value, arrayind_t unused, char *key)
static SHELL_VAR * get_mypid (SHELL_VAR *var)
int enable_mypid_builtin (WORD_LIST *list)
void enable_mypid_builtin_unload (char *s)
Variables
char const * enable_mypid_doc []
struct builtin enable_mypid_struct
Macro Definition Documentation
INIT_DYNAMIC_VAR
#define INIT_DYNAMIC_VAR (var, val, gfunc, afunc)
Value:
  do \
    { SHELL_VAR *v = bind_variable (var, (val), 0); \
      if (v) \
    { \
      v->dynamic_value = gfunc; \
      v->assign_func = afunc; \
    } \
    } \
  while (0)
Definition at line 23 of file mypid.c.
Function Documentation
assign_mypid()
static SHELL_VAR* assign_mypid (SHELL_VAR * self, char * value, arrayind_t unused, char * key) static
Definition at line 35 of file mypid.c.
 {
   return (self);
 }
Referenced by enable_mypid_builtin().
enable_mypid_builtin()
int enable_mypid_builtin (WORD_LIST * list)
Definition at line 61 of file mypid.c.
 {
   INIT_DYNAMIC_VAR ("MYPID", (char *)NULL, get_mypid, assign_mypid);
   return 0;
 }
References assign_mypid(), get_mypid(), INIT_DYNAMIC_VAR, and NULL.
enable_mypid_builtin_unload()
void enable_mypid_builtin_unload (char * s)
Definition at line 69 of file mypid.c.
 {
   unbind_variable ("MYPID");
 }
References unbind_variable().
get_mypid()
static SHELL_VAR* get_mypid (SHELL_VAR * var) static
Definition at line 45 of file mypid.c.
 {
   int rv;
   char *p;
   rv = getpid();
   p = itos (rv);
   FREE (value_cell (var));
   VSETATTR (var, att_integer);
   var_setvalue (var, p);
   return (var);
 }
References att_integer, FREE, getpid(), itos(), p, value_cell, var_setvalue, and VSETATTR.
Referenced by enable_mypid_builtin().
Variable Documentation
enable_mypid_doc
char const* enable_mypid_doc[]
Initial value:
= {
  "Enable $MYPID.",
  "",
  "Enables use of the ${MYPID} dynamic variable.  ",
  "It will yield the current pid of a subshell.",
  (char *)0
}
Definition at line 74 of file mypid.c.
enable_mypid_struct
struct builtin enable_mypid_struct
Initial value:
= {
  "enable_mypid",
  enable_mypid_builtin,
  BUILTIN_ENABLED,
  (char**)(void*)enable_mypid_doc,
  "enable_mypid N",
  0
}
Definition at line 74 of file mypid.c.