Fennix Userspace: Userspace/apps/base/busybox/libbb/get_console.c File Reference
get_console.c File Reference
#include "libbb.h"
Enumerations
enum { KDGKBTYPE = 0x4B33 }
enum { VT_ACTIVATE = 0x5606 , VT_WAITACTIVE = 0x5607 }
Functions
static int open_a_console (const char *fnam)
int FAST_FUNC get_console_fd_or_die (void)
void FAST_FUNC console_make_active (int fd, const int vt_num)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
KDGKBTYPE
Definition at line 13 of file get_console.c.
 { KDGKBTYPE = 0x4B33 };  /* get keyboard type */
anonymous enum
anonymous enum
Enumerator
VT_ACTIVATE
VT_WAITACTIVE
Definition at line 69 of file get_console.c.
      {
     VT_ACTIVATE = 0x5606,   /* make vt active */
     VT_WAITACTIVE = 0x5607  /* wait for vt active */
 };
Function Documentation
console_make_active()
void FAST_FUNC console_make_active (int fd, const int vt_num)
Definition at line 74 of file get_console.c.
 {
     xioctl(fd, VT_ACTIVATE, (void *)(ptrdiff_t)vt_num);
     xioctl(fd, VT_WAITACTIVE, (void *)(ptrdiff_t)vt_num);
 }
References fd, VT_ACTIVATE, VT_WAITACTIVE, and xioctl.
Referenced by chvt_main(), and openvt_main().
get_console_fd_or_die()
int FAST_FUNC get_console_fd_or_die (void)
Definition at line 38 of file get_console.c.
 {
     static const char *const console_names[] ALIGN_PTR = {
         DEV_CONSOLE, CURRENT_VC, CURRENT_TTY
     };
     int fd;
     for (fd = 2; fd >= 0; fd--) {
         int fd4name;
         int choice_fd;
         char arg;
         fd4name = open_a_console(console_names[fd]);
  chk_std:
         choice_fd = (fd4name >= 0 ? fd4name : fd);
         arg = 0;
         if (ioctl(choice_fd, KDGKBTYPE, &arg) == 0)
             return choice_fd;
         if (fd4name >= 0) {
             close(fd4name);
             fd4name = -1;
             goto chk_std;
         }
     }
     bb_simple_error_msg_and_die("can't open console");
 }
References ALIGN_PTR, bb_simple_error_msg_and_die(), close(), CURRENT_TTY, CURRENT_VC, DEV_CONSOLE, fd, ioctl(), KDGKBTYPE, and open_a_console().
Referenced by beep_main(), chvt_main(), deallocvt_main(), dumpkmap_main(), fgconsole_main(), kbd_mode_main(), loadkmap_main(), and setkeycodes_main().
open_a_console()
static int open_a_console (const char * fnam) static
Definition at line 15 of file get_console.c.
 {
     int fd;
     /* try read-write */
     fd = open(fnam, O_RDWR);
     /* if failed, try read-only */
     if (fd < 0 && errno == EACCES)
         fd = open(fnam, O_RDONLY);
     /* if failed, try write-only */
     if (fd < 0 && errno == EACCES)
         fd = open(fnam, O_WRONLY);
     return fd;
 }
References EACCES, errno, fd, O_RDONLY, O_RDWR, O_WRONLY, and open().
Referenced by get_console_fd_or_die().