Fennix Userspace: Userspace/apps/base/bash/jobs.h File Reference
jobs.h File Reference
#include "quit.h"
#include "siglist.h"
#include "stdc.h"
#include "posixwait.h"
Data Structures
struct process
struct pipeline_saver
struct job
struct jobstats
struct pidstat
struct bgpids
struct procstat
struct procchain
Macros
#define JLIST_STANDARD 0
#define JLIST_LONG 1
#define JLIST_PID_ONLY 2
#define JLIST_CHANGED_ONLY 3
#define JLIST_NONINTERACTIVE 4
#define LONGEST_SIGNAL_DESC 24
#define JWAIT_PERROR (1 << 0)
#define JWAIT_FORCE (1 << 1)
#define JWAIT_NOWAIT (1 << 2) /* don't waitpid(), just return status if already exited */
#define JWAIT_WAITING (1 << 3) /* wait for jobs marked J_WAITING only */
#define JWAIT_NOTERM (1 << 8) /* wait_for doesn't give terminal away */
#define FORKSLEEP_MAX 16
#define PS_DONE 0
#define PS_RUNNING 1
#define PS_STOPPED 2
#define PS_RECYCLED 4
#define PSTOPPED(p) (WIFSTOPPED((p)->status))
#define PRUNNING(p) ((p)->running == PS_RUNNING)
#define PALIVE(p) (PRUNNING(p) || PSTOPPED(p))
#define PEXITED(p) ((p)->running == PS_DONE)
#define PRECYCLED(p) (0)
#define PDEADPROC(p) (PEXITED(p) || PRECYCLED(p))
#define get_job_by_jid(ind) (jobs[(ind)])
#define JOBSTATE(job) (jobs[(job)]->state)
#define J_JOBSTATE(j) ((j)->state)
#define STOPPED(j) (jobs[(j)]->state == JSTOPPED)
#define RUNNING(j) (jobs[(j)]->state == JRUNNING)
#define DEADJOB(j) (jobs[(j)]->state == JDEAD)
#define INVALID_JOB(j) ((j) < 0 || (j) >= js.j_jobslots || get_job_by_jid(j) == 0)
#define J_FOREGROUND 0x01 /* Non-zero if this is running in the foreground. */
#define J_NOTIFIED 0x02 /* Non-zero if already notified about job state. */
#define J_JOBCONTROL 0x04 /* Non-zero if this job started under job control. */
#define J_NOHUP 0x08 /* Don't send SIGHUP to job if shell gets SIGHUP. */
#define J_STATSAVED 0x10 /* A process in this job had status saved via $! */
#define J_ASYNC 0x20 /* Job was started asynchronously */
#define J_PIPEFAIL 0x40 /* pipefail set when job was started */
#define J_WAITING 0x80 /* one of a list of jobs for which we are waiting */
#define IS_FOREGROUND(j) ((jobs[j]->flags & J_FOREGROUND) != 0)
#define IS_NOTIFIED(j) ((jobs[j]->flags & J_NOTIFIED) != 0)
#define IS_JOBCONTROL(j) ((jobs[j]->flags & J_JOBCONTROL) != 0)
#define IS_ASYNC(j) ((jobs[j]->flags & J_ASYNC) != 0)
#define IS_WAITING(j) ((jobs[j]->flags & J_WAITING) != 0)
#define NO_PIDSTAT (ps_index_t)-1
#define NO_JOB -1 /* An impossible job array index. */
#define DUP_JOB -2 /* A possible return value for get_job_spec (). */
#define BAD_JOBSPEC -3 /* Bad syntax for job spec. */
#define NO_PID (pid_t)-1
#define ANY_PID (pid_t)-1
#define FORK_SYNC 0 /* normal synchronous process */
#define FORK_ASYNC 1 /* background process */
#define FORK_NOJOB 2 /* don't put process in separate pgrp */
#define FORK_NOTERM 4 /* don't give terminal to any pgrp */
Typedefs
typedef struct process PROCESS
typedef struct job JOB
typedef pid_t ps_index_t
Enumerations
enum JOB_STATE {
JNONE = -1 , JRUNNING = 1 , JSTOPPED = 2 , JDEAD = 4 ,
JMIXED = 8
}
Functions
pid_t fork ()
pid_t getpid ()
pid_t getpgrp ()
void making_children PARAMS ((void))
void save_pipeline PARAMS ((int))
int stop_pipeline PARAMS ((int, COMMAND *))
int discard_pipeline PARAMS ((PROCESS *))
void append_process PARAMS ((char *, pid_t, int, int))
void save_proc_status PARAMS ((pid_t, int))
int get_job_by_pid PARAMS ((pid_t, int, PROCESS **))
void list_one_job PARAMS ((JOB *, int, int, int))
pid_t make_child PARAMS ((char *, int))
int wait_for_background_pids PARAMS ((struct procstat *))
int wait_for_job PARAMS ((int, int, struct procstat *))
int wait_for_any_job PARAMS ((int, struct procstat *))
int kill_pid PARAMS ((pid_t, int, int))
void save_pgrp_pipe PARAMS ((int *, int))
void restore_pgrp_pipe PARAMS ((int *))
Variables
struct jobstats js
pid_t original_pgrp
pid_t shell_pgrp
pid_t pipeline_pgrp
volatile pid_t last_made_pid
volatile pid_t last_asynchronous_pid
int asynchronous_notification
int already_making_children
int running_in_background
PROCESS * last_procsub_child
JOB ** jobs
int job_control
Data Structure Documentation
process
struct process
Definition at line 65 of file jobs.h.
Data Fields
char * command
struct process * next
pid_t pid
int running
WAIT status
pipeline_saver
struct pipeline_saver
Definition at line 73 of file jobs.h.
Data Fields
struct pipeline_saver * next
struct process * pipeline
job
struct job
Definition at line 120 of file jobs.h.
Data Fields
unsigned changed: 1
int flags
unsigned nprocs
pid_t pgrp
PROCESS * pipe
struct job * prev_job
struct procstat * ps
struct procstat ps0
JOB_STATE state
unsigned state: 8
unsigned used: 1
unsigned waited: 1
char * wd
jobstats
struct jobstats
Definition at line 133 of file jobs.h.
Data Fields
long c_childmax
int c_injobs
int c_living
int c_reaped
int c_totforked
int c_totreaped
int j_current
int j_firstj
int j_jobslots
JOB * j_lastasync
int j_lastj
JOB * j_lastmade
int j_ndead
int j_njobs
int j_previous
pidstat
struct pidstat
Definition at line 160 of file jobs.h.
Data Fields
ps_index_t bucket_next
ps_index_t bucket_prev
pid_t pid
bits16_t status
bgpids
struct bgpids
Definition at line 168 of file jobs.h.
Data Fields
ps_index_t head
ps_index_t nalloc
int npid
struct pidstat * storage
procstat
struct procstat
Definition at line 180 of file jobs.h.
Data Fields
pid_t pid
char * ps_cmd
pid_t ps_pid
int ps_status
bits16_t status
procchain
struct procchain
Definition at line 187 of file jobs.h.
Data Fields
PROCESS * end
PROCESS * head
int nproc
Macro Definition Documentation
ANY_PID
#define ANY_PID (pid_t)-1
Definition at line 200 of file jobs.h.
BAD_JOBSPEC
#define BAD_JOBSPEC -3 /* Bad syntax for job spec. */
Definition at line 195 of file jobs.h.
DEADJOB
#define DEADJOB (j) (jobs[(j)]->state == JDEAD)
Definition at line 100 of file jobs.h.
DUP_JOB
#define DUP_JOB -2 /* A possible return value for get_job_spec (). */
Definition at line 194 of file jobs.h.
FORK_ASYNC
#define FORK_ASYNC 1 /* background process */
Definition at line 204 of file jobs.h.
FORK_NOJOB
#define FORK_NOJOB 2 /* don't put process in separate pgrp */
Definition at line 205 of file jobs.h.
FORK_NOTERM
#define FORK_NOTERM 4 /* don't give terminal to any pgrp */
Definition at line 206 of file jobs.h.
FORK_SYNC
#define FORK_SYNC 0 /* normal synchronous process */
Definition at line 203 of file jobs.h.
FORKSLEEP_MAX
#define FORKSLEEP_MAX 16
Definition at line 51 of file jobs.h.
get_job_by_jid
#define get_job_by_jid (ind) (jobs[(ind)])
Definition at line 91 of file jobs.h.
INVALID_JOB
#define INVALID_JOB (j) ((j) < 0 || (j) >= js.j_jobslots || get_job_by_jid(j) == 0)
Definition at line 102 of file jobs.h.
IS_ASYNC
#define IS_ASYNC (j) ((jobs[j]->flags & J_ASYNC) != 0)
Definition at line 117 of file jobs.h.
IS_FOREGROUND
#define IS_FOREGROUND (j) ((jobs[j]->flags & J_FOREGROUND) != 0)
Definition at line 114 of file jobs.h.
IS_JOBCONTROL
#define IS_JOBCONTROL (j) ((jobs[j]->flags & J_JOBCONTROL) != 0)
Definition at line 116 of file jobs.h.
IS_NOTIFIED
#define IS_NOTIFIED (j) ((jobs[j]->flags & J_NOTIFIED) != 0)
Definition at line 115 of file jobs.h.
IS_WAITING
#define IS_WAITING (j) ((jobs[j]->flags & J_WAITING) != 0)
Definition at line 118 of file jobs.h.
J_ASYNC
#define J_ASYNC 0x20 /* Job was started asynchronously */
Definition at line 110 of file jobs.h.
J_FOREGROUND
#define J_FOREGROUND 0x01 /* Non-zero if this is running in the foreground. */
Definition at line 105 of file jobs.h.
J_JOBCONTROL
#define J_JOBCONTROL 0x04 /* Non-zero if this job started under job control. */
Definition at line 107 of file jobs.h.
J_JOBSTATE
#define J_JOBSTATE (j) ((j)->state)
Definition at line 96 of file jobs.h.
J_NOHUP
#define J_NOHUP 0x08 /* Don't send SIGHUP to job if shell gets SIGHUP. */
Definition at line 108 of file jobs.h.
J_NOTIFIED
#define J_NOTIFIED 0x02 /* Non-zero if already notified about job state. */
Definition at line 106 of file jobs.h.
J_PIPEFAIL
#define J_PIPEFAIL 0x40 /* pipefail set when job was started */
Definition at line 111 of file jobs.h.
J_STATSAVED
#define J_STATSAVED 0x10 /* A process in this job had status saved via $! */
Definition at line 109 of file jobs.h.
J_WAITING
#define J_WAITING 0x80 /* one of a list of jobs for which we are waiting */
Definition at line 112 of file jobs.h.
JLIST_CHANGED_ONLY
#define JLIST_CHANGED_ONLY 3
Definition at line 35 of file jobs.h.
JLIST_LONG
#define JLIST_LONG 1
Definition at line 33 of file jobs.h.
JLIST_NONINTERACTIVE
#define JLIST_NONINTERACTIVE 4
Definition at line 36 of file jobs.h.
JLIST_PID_ONLY
#define JLIST_PID_ONLY 2
Definition at line 34 of file jobs.h.
JLIST_STANDARD
#define JLIST_STANDARD 0
Definition at line 32 of file jobs.h.
JOBSTATE
#define JOBSTATE (job) (jobs[(job)]->state)
Definition at line 95 of file jobs.h.
JWAIT_FORCE
#define JWAIT_FORCE (1 << 1)
Definition at line 43 of file jobs.h.
JWAIT_NOTERM
#define JWAIT_NOTERM (1 << 8) /* wait_for doesn't give terminal away */
Definition at line 48 of file jobs.h.
JWAIT_NOWAIT
#define JWAIT_NOWAIT (1 << 2) /* don't waitpid(), just return status if already exited */
Definition at line 44 of file jobs.h.
JWAIT_PERROR
#define JWAIT_PERROR (1 << 0)
Definition at line 42 of file jobs.h.
JWAIT_WAITING
#define JWAIT_WAITING (1 << 3) /* wait for jobs marked J_WAITING only */
Definition at line 45 of file jobs.h.
LONGEST_SIGNAL_DESC
#define LONGEST_SIGNAL_DESC 24
Definition at line 39 of file jobs.h.
NO_JOB
#define NO_JOB -1 /* An impossible job array index. */
Definition at line 193 of file jobs.h.
NO_PID
#define NO_PID (pid_t)-1
Definition at line 198 of file jobs.h.
NO_PIDSTAT
#define NO_PIDSTAT (ps_index_t)-1
Definition at line 177 of file jobs.h.
PALIVE
#define PALIVE (p) (PRUNNING(p) || PSTOPPED(p))
Definition at line 81 of file jobs.h.
PDEADPROC
#define PDEADPROC (p) (PEXITED(p) || PRECYCLED(p))
Definition at line 89 of file jobs.h.
PEXITED
#define PEXITED (p) ((p)->running == PS_DONE)
Definition at line 83 of file jobs.h.
PRECYCLED
#define PRECYCLED (p) (0)
Definition at line 87 of file jobs.h.
PRUNNING
#define PRUNNING (p) ((p)->running == PS_RUNNING)
Definition at line 80 of file jobs.h.
PS_DONE
#define PS_DONE 0
Definition at line 58 of file jobs.h.
PS_RECYCLED
#define PS_RECYCLED 4
Definition at line 61 of file jobs.h.
PS_RUNNING
#define PS_RUNNING 1
Definition at line 59 of file jobs.h.
PS_STOPPED
#define PS_STOPPED 2
Definition at line 60 of file jobs.h.
PSTOPPED
#define PSTOPPED (p) (WIFSTOPPED((p)->status))
Definition at line 79 of file jobs.h.
RUNNING
#define RUNNING (j) (jobs[(j)]->state == JRUNNING)
Definition at line 99 of file jobs.h.
STOPPED
#define STOPPED (j) (jobs[(j)]->state == JSTOPPED)
Definition at line 98 of file jobs.h.
Typedef Documentation
JOB
typedef struct job JOB
PROCESS
typedef struct process PROCESS
ps_index_t
typedef pid_t ps_index_t
Definition at line 158 of file jobs.h.
Enumeration Type Documentation
JOB_STATE
enum JOB_STATE
Enumerator
JNONE
JRUNNING
JSTOPPED
JDEAD
JMIXED
Definition at line 94 of file jobs.h.
 { JNONE = -1, JRUNNING = 1, JSTOPPED = 2, JDEAD = 4, JMIXED = 8 } JOB_STATE;
Function Documentation
fork()
pid_t fork (void)
Referenced by daemon(), do_wordexp(), exec_conf(), exec_kernel_doc(), ExecuteCommand(), fork_bomb(), forkpty(), forkshell(), inetd_main(), main(), make_child(), nbdclient_main(), run(), run_pipe(), self_fork_exec(), spawn_and_wait(), test_execve_fork(), test_stdio(), test_watch_directory(), and test_watch_file().
getpgrp()
pid_t getpgrp ()
Definition at line 4 of file getpgrp.c.
 {
     return __syscall(SYS_getpgid, 0);
 }
References __syscall.
Referenced by hush_main().
getpid()
pid_t getpid (void)
Referenced by _rl_handle_signal(), _vsyslog(), ash_main(), assign_random(), bootchartd_main(), builtin_exec(), cleanup(), command_substitute(), common_ping_main(), conf_write(), crontab_main(), crypt_make_salt(), data_extract_all(), expand_variable(), fork_bomb(), fork_bomb_syscall(), forkchild(), free_pipe(), ftpd_main(), generate_uuid(), genseed(), get_bashpid(), get_mypid(), get_random_number(), get_tty_state(), getty_main(), give_terminal_to(), history_tempfile(), hush_main(), init_main(), initialize_job_control(), initialize_shell_variables(), kill_main(), kill_shell(), lockf(), login_main(), lpqr_main(), lsof_main(), main(), make_child(), make_new_session(), maybe_give_terminal_to(), mdev_main(), microcom_main(), next_random(), notify_signal(), ntp_init(), parse(), pgrep_main(), popmaildir_main(), push_builtin(), re_execute_shell(), ReadLine(), run(), run_pending_traps(), run_pipe(), runsvdir_main(), self_fork_exec(), set_tty_state(), sh_seedrand(), sigcont_sighandler(), sigqueue(), sigstop_sighandler(), start_shell_in_child(), sulogin_main(), switch_root_main(), tcpudpsvd_main(), test_signal(), tls_run_copy_loop(), traceroute_init(), trap_handler(), unshare_main(), vi_main(), wait_for(), wait_sigint_handler(), and write_pidfile().
PARAMS() [1/15]
pid_t make_child PARAMS ((char *, int))
PARAMS() [2/15]
void append_process PARAMS ((char *, pid_t, int, int))
PARAMS() [3/15]
void restore_pgrp_pipe PARAMS ((int *))
PARAMS() [4/15]
void save_pgrp_pipe PARAMS ((int *, int))
PARAMS() [5/15]
void save_pipeline PARAMS ((int))
PARAMS() [6/15]
int stop_pipeline PARAMS ((int, COMMAND *))
PARAMS() [7/15]
int wait_for_job PARAMS ((int, int, struct procstat *))
PARAMS() [8/15]
int wait_for_any_job PARAMS ((int, struct procstat *))
PARAMS() [9/15]
void list_one_job PARAMS ((JOB *, int, int, int))
PARAMS() [10/15]
void save_proc_status PARAMS ((pid_t, int))
PARAMS() [11/15]
int kill_pid PARAMS ((pid_t, int, int))
PARAMS() [12/15]
int get_job_by_pid PARAMS ((pid_t, int, PROCESS **))
PARAMS() [13/15]
int discard_pipeline PARAMS ((PROCESS *))
PARAMS() [14/15]
int wait_for_background_pids PARAMS ((struct procstat *))
PARAMS() [15/15]
void making_children PARAMS ((void))
Variable Documentation
already_making_children
int already_making_children extern
Definition at line 228 of file jobs.c.
Referenced by execute_command_internal(), making_children(), restore_pipeline(), save_pipeline(), start_pipeline(), stop_making_children(), and stop_pipeline().
asynchronous_notification
int asynchronous_notification extern
Definition at line 51 of file flags.c.
Referenced by print_pipeline(), reset_shell_flags(), and waitchld().
job_control
int job_control extern
Definition at line 222 of file jobs.c.
Referenced by end_job_control(), execute_connection(), execute_pipeline(), execute_simple_command(), give_terminal_to(), initialize_job_control(), initialize_job_signals(), make_child(), notify_of_job_status(), set_job_control(), set_job_status_and_cleanup(), setup_async_signals(), start_pipeline(), stop_pipeline(), wait_for(), and waitchld().
jobs
JOB** jobs extern
Definition at line 183 of file jobs.c.
Referenced by append_process(), cleanup_dead_jobs(), compact_jobs_list(), count_all_jobs(), delete_all_jobs(), delete_job(), delete_old_job(), find_job(), find_last_proc(), find_pipeline(), hangup_all_jobs(), job_signal_status(), kill_pid(), map_over_jobs(), mark_all_jobs_as_dead(), mark_dead_jobs_as_notified(), most_recent_job_in_state(), nohup_all_jobs(), nohup_job(), notify_of_job_status(), pretty_print_job(), print_pipeline(), processes_in_job(), raw_job_exit_status(), realloc_jobs_list(), reset_current(), reset_job_indices(), set_current_job(), set_job_running(), set_job_status_and_cleanup(), setjstatus(), start_job(), stop_pipeline(), terminate_stopped_jobs(), wait_for(), wait_for_any_job(), wait_for_background_pids(), wait_for_job(), and wait_for_single_pid().
js
struct jobstats js extern
Definition at line 172 of file jobs.c.
Referenced by append_process(), bgp_add(), bgp_getindex(), bgp_resize(), cleanup_dead_jobs(), compact_jobs_list(), count_all_jobs(), delete_all_jobs(), delete_job(), find_job(), hangup_all_jobs(), init_job_stats(), make_child(), map_over_jobs(), mark_all_jobs_as_dead(), mark_dead_jobs_as_notified(), nohup_all_jobs(), nohup_job(), notify_of_job_status(), pretty_print_job(), realloc_jobs_list(), reset_current(), reset_job_indices(), set_current_job(), set_job_status_and_cleanup(), set_maxchild(), start_job(), stop_pipeline(), terminate_stopped_jobs(), volume_id_probe_jfs(), wait_for(), wait_for_any_job(), wait_for_background_pids(), and waitchld().
last_asynchronous_pid
volatile pid_t last_asynchronous_pid
Definition at line 217 of file jobs.h.
last_made_pid
volatile pid_t last_made_pid extern
Definition at line 213 of file jobs.c.
Referenced by command_substitute(), execute_command_internal(), execute_pipeline(), make_child(), run_sigchld_trap(), and without_job_control().
last_procsub_child
PROCESS* last_procsub_child extern
Definition at line 234 of file jobs.c.
Referenced by cleanup_dead_jobs(), and discard_last_procsub_child().
original_pgrp
pid_t original_pgrp extern
Definition at line 200 of file jobs.c.
Referenced by end_job_control(), execute_in_subshell(), and initialize_job_control().
pipeline_pgrp
pid_t pipeline_pgrp
Definition at line 216 of file jobs.h.
running_in_background
int running_in_background extern
Definition at line 225 of file jobs.c.
shell_pgrp
pid_t shell_pgrp
Definition at line 216 of file jobs.h.