Fennix Kernel: NetworkInterfaceManager::NetworkInterface Class Reference
NetworkInterfaceManager::NetworkInterface Class Reference
#include <nc.hpp>
Public Member Functions
NetworkInterface ()
~NetworkInterface ()
void StartService ()
void Send (DeviceInterface *Interface, uint8_t *Data, uint64_t Length)
void Receive (DeviceInterface *Interface, uint8_t *Data, uint64_t Length)
void DrvSend (unsigned int DriverID, unsigned char *Data, unsigned short Size)
void DrvReceive (unsigned int DriverID, unsigned char *Data, unsigned short Size)
void StartNetworkStack ()
Private Member Functions
void StopNetworkStack ()
void FetchNetworkCards (unsigned long DriverUID)
Private Attributes
Memory::MemMgr * mem
int CardIDs = 0
Vector< DeviceInterface * > Interfaces
Tasking::TCB * NetSvcThread
Detailed Description
Definition at line 48 of file nc.hpp.
Constructor & Destructor Documentation
NetworkInterface()
NetworkInterfaceManager::NetworkInterface::NetworkInterface ()
Definition at line 20 of file NetworkController.cpp.
     {
         mem = new Memory::MemMgr(nullptr, TaskManager->GetCurrentProcess()->memDirectory);
         if (DriverManager->GetDrivers().size() > 0)
         {
             foreach (auto Driver in DriverManager->GetDrivers())
                 if (((FexExtended *)((uintptr_t)Driver->Address + EXTENDED_SECTION_ADDRESS))->Driver.Type == FexDriverType::FexDriverType_Network)
                     this->FetchNetworkCards(Driver->DriverUID);
         }
         else
             KPrint("\eE85230No network drivers found! Cannot fetch network cards!");
         DbgNetwork();
     }
References DbgNetwork(), DriverManager, EXTENDED_SECTION_ADDRESS, FetchNetworkCards(), FexDriverType_Network, Tasking::Task::GetCurrentProcess(), Driver::Driver::GetDrivers(), KPrint(), mem, Tasking::PCB::memDirectory, and TaskManager.
~NetworkInterface()
NetworkInterfaceManager::NetworkInterface::~NetworkInterface ()
Definition at line 35 of file NetworkController.cpp.
     {
         // Stop the network stack
         this->StopNetworkStack();
         // Unregister all events
         for (size_t i = 0; i < RegisteredEvents.size(); i++)
             RegisteredEvents.remove(i);
         // Delete all interfaces and their callbacks and free the memory
         delete mem;
     }
References mem, NetworkInterfaceManager::RegisteredEvents, and StopNetworkStack().
Member Function Documentation
DrvReceive()
void NetworkInterfaceManager::NetworkInterface::DrvReceive (unsigned int DriverID, unsigned char * Data, unsigned short Size)
Definition at line 170 of file NetworkController.cpp.
     {
         foreach (auto var in this->Interfaces)
             if (var->DriverID == DriverID)
                 NIManager->Receive(var, Data, Size);
     }
References Data, Interfaces, NIManager, and Receive().
Referenced by DriverNetReceive().
DrvSend()
void NetworkInterfaceManager::NetworkInterface::DrvSend (unsigned int DriverID, unsigned char * Data, unsigned short Size)
Definition at line 163 of file NetworkController.cpp.
     {
         foreach (auto var in this->Interfaces)
             if (var->DriverID == DriverID)
                 NIManager->Send(var, Data, Size);
     }
References Data, Interfaces, NIManager, and Send().
Referenced by DriverNetSend().
FetchNetworkCards()
void NetworkInterfaceManager::NetworkInterface::FetchNetworkCards (unsigned long DriverUID) private
Definition at line 48 of file NetworkController.cpp.
     {
         KernelCallback *cb = (KernelCallback *)mem->RequestPages(TO_PAGES(sizeof(KernelCallback)));
         memset(cb, 0, sizeof(KernelCallback));
         cb->Reason = FetchReason;
         DriverManager->IOCB(DriverUID, (void *)cb);
         DeviceInterface *Iface = (DeviceInterface *)mem->RequestPages(TO_PAGES(sizeof(DeviceInterface)));
         strcpy(Iface->Name, cb->NetworkCallback.Fetch.Name);
         Iface->ID = this->CardIDs++;
         Iface->MAC.FromHex(cb->NetworkCallback.Fetch.MAC);
         Iface->DriverCallBackAddress = cb;
         Iface->DriverID = DriverUID;
         Interfaces.push_back(Iface);
         foreach (auto var in RegisteredEvents)
             var->OnInterfaceAdded(Iface);
         debug("Network Card: %s; MAC: %#lx", Iface->Name, Iface->MAC.ToHex());
     }
References CardIDs, debug, NetworkInterfaceManager::DeviceInterface::DriverCallBackAddress, NetworkInterfaceManager::DeviceInterface::DriverID, DriverManager, FetchReason, MediaAccessControl::FromHex(), NetworkInterfaceManager::DeviceInterface::ID, Interfaces, Driver::Driver::IOCB(), NetworkInterfaceManager::DeviceInterface::MAC, mem, memset(), NetworkInterfaceManager::DeviceInterface::Name, KernelCallback::NetworkCallback, KernelCallback::Reason, NetworkInterfaceManager::RegisteredEvents, and strcpy.
Referenced by NetworkInterface().
Receive()
void NetworkInterfaceManager::NetworkInterface::Receive (DeviceInterface * Interface, uint8_t * Data, uint64_t Length)
Definition at line 195 of file NetworkController.cpp.
     {
         foreach (auto var in RegisteredEvents)
             var->OnInterfaceReceived(Interface, Data, Length);
     }
References Data, Length, and NetworkInterfaceManager::RegisteredEvents.
Referenced by DrvReceive().
Send()
void NetworkInterfaceManager::NetworkInterface::Send (DeviceInterface * Interface, uint8_t * Data, uint64_t Length)
Definition at line 177 of file NetworkController.cpp.
     {
         void *DataToBeSent = mem->RequestPages(TO_PAGES(Length));
         memcpy(DataToBeSent, Data, Length);
         KernelCallback *cb = (KernelCallback *)Interface->DriverCallBackAddress;
         memset(cb, 0, sizeof(KernelCallback));
         cb->Reason = SendReason;
         cb->NetworkCallback.Send.Data = (uint8_t *)DataToBeSent;
         cb->NetworkCallback.Send.Length = Length;
         DriverManager->IOCB(Interface->DriverID, (void *)cb);
         mem->FreePages(DataToBeSent, TO_PAGES(Length));
         foreach (auto var in RegisteredEvents)
             var->OnInterfaceSent(Interface, Data, Length);
     }
References Data, NetworkInterfaceManager::DeviceInterface::DriverCallBackAddress, NetworkInterfaceManager::DeviceInterface::DriverID, DriverManager, Driver::Driver::IOCB(), Length, mem, memcpy(), memset(), KernelCallback::NetworkCallback, KernelCallback::Reason, NetworkInterfaceManager::RegisteredEvents, and SendReason.
Referenced by DrvSend(), NetworkIPv4::IPv4::OnEthernetPacketReceived(), NetworkICMPv4::ICMPv4::Receive(), and NetworkEthernet::Ethernet::Send().
StartNetworkStack()
void NetworkInterfaceManager::NetworkInterface::StartNetworkStack ()
Definition at line 75 of file NetworkController.cpp.
     {
         TaskManager->GetCurrentThread()->SetPriority(Tasking::TaskPriority::Critical);
         DeviceInterface *DefaultDevice = nullptr;
         foreach (auto inf in Interfaces)
             if (inf && inf->DriverCallBackAddress)
             {
                 DefaultDevice = inf;
                 break;
             }
         if (!DefaultDevice)
             error("No network device found!");
         else
         {
             DbgWriteScreen("Using %s (%s) as the default network device", DefaultDevice->Name, DefaultDevice->MAC.ToString());
             NetworkEthernet::Ethernet *eth = new NetworkEthernet::Ethernet(DefaultDevice); // Use the first device found as the ethernet device
             NetworkARP::ARP *arp = new NetworkARP::ARP(eth);
             NetworkIPv4::IPv4 *ipv4 = new NetworkIPv4::IPv4(arp, eth);
             NetworkUDP::UDP *udp = new NetworkUDP::UDP(ipv4, DefaultDevice);
             NetworkUDP::Socket *DHCP_Socket = udp->Connect(InternetProtocol() /* Default value is 255.255.255.255 */, 67);
             NetworkDHCP::DHCP *dhcp = new NetworkDHCP::DHCP(DHCP_Socket, DefaultDevice);
             udp->Bind(DHCP_Socket, dhcp);
             dhcp->Request();
             DefaultDevice->IP.v4.FromHex(dhcp->IP.v4.ToHex());
             ipv4->SubNetworkMaskIP = dhcp->SubNetworkMask;
             ipv4->GatewayIP = dhcp->Gateway;
             arp->Broadcast(dhcp->Gateway);
             TaskManager->Sleep(200);
             DbgWriteScreen("IP: %s", dhcp->IP.v4.ToStringLittleEndian());
             DbgWriteScreen("SubNetwork Mask: %s", dhcp->SubNetworkMask.v4.ToStringLittleEndian());
             DbgWriteScreen("Gateway: %s", dhcp->Gateway.v4.ToStringLittleEndian());
             DbgWriteScreen("DNS: %s", dhcp->DomainNameSystem.v4.ToStringLittleEndian());
             TaskManager->Sleep(200);
             /*
             I HAVE TO REWRITE THE ENTIRE NETWORK STACK BECAUSE IT'S A MESS. I HATE BYTE SWAPPING!!!!!
             Rules to follow:
             - The functions MUST have little endian parameters and return values.
             */
             /* TODO: This is a quick workaround we need DNS resolver asap. IP is time-a-g.nist.gov; https://tf.nist.gov/tf-cgi/servers.cgi */
             InternetProtocol ip = {.v4 = {.Address = {129, 6, 15, 28}},
                                    .v6 = {.Address = {}}};
             NetworkUDP::Socket *NTP_Socket = udp->Connect(ip, 123);
             NetworkNTP::NTP *ntp = new NetworkNTP::NTP(NTP_Socket);
             udp->Bind(NTP_Socket, ntp);
             int UnixTimestamp = ntp->ReadTime();
             Time::Clock time = Time::ConvertFromUnix(UnixTimestamp);
             DbgWriteScreen("NTP: %d - %d.%d.%d %d:%d:%d", UnixTimestamp,
                            time.Day, time.Month, time.Year,
                            time.Hour, time.Minute, time.Second);
             TaskManager->Sleep(200);
             /* TODO: Store everything in an vector and initialize all network cards */
         }
         TaskManager->GetCurrentThread()->SetPriority(Tasking::TaskPriority::Idle);
         CPU::Pause(true);
     }
References InternetProtocol::Version4::Address, NetworkUDP::UDP::Bind(), NetworkARP::ARP::Broadcast(), NetworkUDP::UDP::Connect(), Time::ConvertFromUnix(), Tasking::Critical, Time::Clock::Day, DbgWriteScreen, NetworkDHCP::DHCP::DomainNameSystem, error, NetworkDHCP::DHCP::Gateway, NetworkIPv4::IPv4::GatewayIP, Tasking::Task::GetCurrentThread(), Time::Clock::Hour, APIC::Idle, Interfaces, NetworkDHCP::DHCP::IP, Time::Clock::Minute, Time::Clock::Month, CPU::Pause(), NetworkNTP::NTP::ReadTime(), NetworkDHCP::DHCP::Request(), Time::Clock::Second, Tasking::TCB::SetPriority(), Tasking::Task::Sleep(), NetworkDHCP::DHCP::SubNetworkMask, NetworkIPv4::IPv4::SubNetworkMaskIP, TaskManager, InternetProtocol::Version4::ToHex(), InternetProtocol::Version4::ToStringLittleEndian(), InternetProtocol::v4, and Time::Clock::Year.
Referenced by NetworkInterfaceManager::CallStartNetworkStackWrapper().
StartService()
void NetworkInterfaceManager::NetworkInterface::StartService ()
Definition at line 157 of file NetworkController.cpp.
     {
         this->NetSvcThread = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (Tasking::IP)CallStartNetworkStackWrapper);
         this->NetSvcThread->Rename("Network Service");
     }
References NetworkInterfaceManager::CallStartNetworkStackWrapper(), Tasking::Task::CreateThread(), Tasking::Task::GetCurrentProcess(), NetSvcThread, Tasking::TCB::Rename(), and TaskManager.
Referenced by KernelMainThread().
StopNetworkStack()
void NetworkInterfaceManager::NetworkInterface::StopNetworkStack () private
Definition at line 138 of file NetworkController.cpp.
     {
         fixme("Stop network stack");
     }
References fixme.
Referenced by ~NetworkInterface().
Field Documentation
CardIDs
int NetworkInterfaceManager::NetworkInterface::CardIDs = 0 private
Definition at line 52 of file nc.hpp.
Referenced by FetchNetworkCards().
Interfaces
Vector<DeviceInterface *> NetworkInterfaceManager::NetworkInterface::Interfaces private
Definition at line 53 of file nc.hpp.
Referenced by DrvReceive(), DrvSend(), FetchNetworkCards(), and StartNetworkStack().
mem
Memory::MemMgr* NetworkInterfaceManager::NetworkInterface::mem private
Definition at line 51 of file nc.hpp.
Referenced by FetchNetworkCards(), NetworkInterface(), Send(), and ~NetworkInterface().
NetSvcThread
Tasking::TCB* NetworkInterfaceManager::NetworkInterface::NetSvcThread private
Definition at line 55 of file nc.hpp.
Referenced by StartService().
The documentation for this class was generated from the following files:
Kernel/include/net/nc.hpp
Kernel/Network/NetworkController.cpp