Fennix Kernel: NetworkUDP::UDP Class Reference
NetworkUDP::UDP Class Reference
#include <udp.hpp>
Public Member Functions
NetworkInterfaceManager::DeviceInterface * GetInterface ()
UDP (NetworkIPv4::IPv4 *ipv4, NetworkInterfaceManager::DeviceInterface *Interface)
~UDP ()
virtual Socket * Connect (InternetProtocol IP, uint16_t Port)
virtual Socket * Listen (uint16_t Port)
virtual void Disconnect (Socket *Socket)
virtual void Send (Socket *Socket, uint8_t *Data, uint64_t Length)
virtual void Bind (Socket *Socket, UDPEvents *EventHandler)
virtual bool OnIPv4PacketReceived (InternetProtocol SourceIP, InternetProtocol DestinationIP, uint8_t *Data, uint64_t Length)
Public Member Functions inherited from NetworkIPv4::IPv4Events
uint8_t GetProtocol ()
Private Attributes
NetworkIPv4::IPv4 * ipv4
NetworkInterfaceManager::DeviceInterface * Interface
Additional Inherited Members
Protected Member Functions inherited from NetworkIPv4::IPv4Events
IPv4Events (IPv4Protocols Protocol)
~IPv4Events ()
Detailed Description
Definition at line 40 of file udp.hpp.
Constructor & Destructor Documentation
UDP()
NetworkUDP::UDP::UDP (NetworkIPv4::IPv4 * ipv4, NetworkInterfaceManager::DeviceInterface * Interface)
Definition at line 21 of file UserDatagramProtocol.cpp.
                                                                                      : NetworkIPv4::IPv4Events(NetworkIPv4::PROTOCOL_UDP)
     {
         debug("UDP interface %#lx created.", this);
         this->ipv4 = ipv4;
         this->Interface = Interface;
     }
References debug, Interface, and ipv4.
~UDP()
NetworkUDP::UDP::~UDP ()
Definition at line 28 of file UserDatagramProtocol.cpp.
     {
         debug("UDP interface %#lx destroyed.", this);
     }
References debug.
Member Function Documentation
Bind()
void NetworkUDP::UDP::Bind (Socket * Socket, UDPEvents * EventHandler) virtual
Definition at line 75 of file UserDatagramProtocol.cpp.
     {
         netdbg("Binding socket to %s", Socket->LocalIP.v4.ToStringLittleEndian(), Socket->LocalPort);
         Socket->EventHandler = EventHandler;
     }
References NetworkUDP::Socket::EventHandler, NetworkUDP::Socket::LocalIP, NetworkUDP::Socket::LocalPort, netdbg, InternetProtocol::Version4::ToStringLittleEndian(), and InternetProtocol::v4.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Connect()
Socket * NetworkUDP::UDP::Connect (InternetProtocol IP, uint16_t Port) virtual
Definition at line 35 of file UserDatagramProtocol.cpp.
     {
         netdbg("Connecting to %s", IP.v4.ToStringLittleEndian(), Port);
         Socket *socket = new Socket(this);
         socket->RemoteIP = IP;
         socket->RemotePort = Port;
         socket->LocalPort = UsablePort++; // TODO: track ports
         socket->LocalIP = Interface->IP;
         socket->LocalPort = b16(socket->LocalPort);
         socket->RemotePort = b16(socket->RemotePort);
         RegisteredEvents.push_back({.UDPSocket = socket, .Port = socket->LocalPort});
         return socket;
     }
References b16, Interface, NetworkInterfaceManager::DeviceInterface::IP, NetworkUDP::Socket::LocalIP, NetworkUDP::Socket::LocalPort, netdbg, NetworkUDP::RegisteredEvents, NetworkUDP::Socket::RemoteIP, NetworkUDP::Socket::RemotePort, and NetworkUDP::UsablePort.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Disconnect()
void NetworkUDP::UDP::Disconnect (Socket * Socket) virtual
Definition at line 55 of file UserDatagramProtocol.cpp.
     {
         fixme("Not implemented.");
     }
References fixme.
GetInterface()
NetworkInterfaceManager::DeviceInterface* NetworkUDP::UDP::GetInterface () inline
Definition at line 47 of file udp.hpp.
 { return this->Interface; }
References Interface.
Listen()
Socket * NetworkUDP::UDP::Listen (uint16_t Port) virtual
Definition at line 49 of file UserDatagramProtocol.cpp.
     {
         fixme("Not implemented.");
         return nullptr;
     }
References fixme.
OnIPv4PacketReceived()
bool NetworkUDP::UDP::OnIPv4PacketReceived (InternetProtocol SourceIP, InternetProtocol DestinationIP, uint8_t * Data, uint64_t Length) virtual
Reimplemented from NetworkIPv4::IPv4Events.
Definition at line 81 of file UserDatagramProtocol.cpp.
     {
         netdbg("Received %d bytes from %s", Length, SourceIP.v4.ToStringLittleEndian());
         if (Length < sizeof(UDPHeader))
             return false;
         UDPHeader *udp = (UDPHeader *)Data;
         netdbg("SP:%d | DP:%d | L:%d | CHK:%#x", b16(udp->SourcePort), b16(udp->DestinationPort), b16(udp->Length), b16(udp->Checksum));
         Socket *GoodSocket = nullptr;
         foreach (auto &var in RegisteredEvents)
         {
             netdbg("UDP->SKT[]: LP:%d | LIP:%s | RP:%d | RIP:%s | LST:%d",
                    b16(var.UDPSocket->LocalPort),
                    var.UDPSocket->LocalIP.v4.ToStringLittleEndian(),
                    b16(var.UDPSocket->RemotePort),
                    var.UDPSocket->RemoteIP.v4.ToStringLittleEndian(),
                    b16(var.UDPSocket->Listening));
             if (var.UDPSocket->LocalPort == udp->DestinationPort &&
                 var.UDPSocket->LocalIP.v4 == DestinationIP.v4 &&
                 var.UDPSocket->Listening == true)
             {
                 var.UDPSocket->Listening = false;
                 var.UDPSocket->RemotePort = b16(udp->SourcePort);
                 var.UDPSocket->RemoteIP = SourceIP;
                 netdbg("E1");
                 return true;
             }
             GoodSocket = var.UDPSocket;
         }
         if (GoodSocket)
             GoodSocket->EventHandler->OnUDPPacketReceived(GoodSocket, ((UDPPacket *)Data)->Data, Length);
         netdbg("E0 (Success)");
         return false;
     }
References b16, NetworkUDP::UDPHeader::Checksum, Data, NetworkUDP::UDPHeader::DestinationPort, Length, NetworkUDP::UDPHeader::Length, netdbg, NetworkUDP::RegisteredEvents, NetworkUDP::UDPHeader::SourcePort, InternetProtocol::Version4::ToStringLittleEndian(), and InternetProtocol::v4.
Send()
void NetworkUDP::UDP::Send (Socket * Socket, uint8_t * Data, uint64_t Length) virtual
Definition at line 60 of file UserDatagramProtocol.cpp.
     {
         netdbg("Sending %d bytes to %s", Length, Socket->RemoteIP.v4.ToStringLittleEndian(), Socket->RemotePort);
         uint16_t TotalLength = Length + sizeof(UDPHeader);
         UDPPacket *packet = (UDPPacket *)kmalloc(TotalLength);
         packet->Header.SourcePort = Socket->LocalPort;
         packet->Header.DestinationPort = Socket->RemotePort;
         packet->Header.Length = b16(TotalLength);
         memcpy(packet->Data, Data, Length);
         packet->Header.Checksum = 0; // I totally should do this. Some devices may require it.
         // packet->Header.Checksum = CalculateChecksum((uint16_t *)packet, TotalLength);
         this->ipv4->Send((uint8_t *)packet, TotalLength, 0x11, Socket->RemoteIP);
         kfree(packet);
     }
References b16, Data, ipv4, kfree, kmalloc, Length, NetworkUDP::Socket::LocalPort, memcpy(), netdbg, NetworkUDP::Socket::RemoteIP, NetworkUDP::Socket::RemotePort, NetworkIPv4::IPv4::Send(), InternetProtocol::Version4::ToStringLittleEndian(), and InternetProtocol::v4.
Referenced by NetworkNTP::NTP::ReadTime(), and NetworkDHCP::DHCP::Request().
Field Documentation
Interface
NetworkInterfaceManager::DeviceInterface* NetworkUDP::UDP::Interface private
Definition at line 44 of file udp.hpp.
Referenced by Connect(), GetInterface(), and UDP().
ipv4
NetworkIPv4::IPv4* NetworkUDP::UDP::ipv4 private
Definition at line 43 of file udp.hpp.
Referenced by Send(), and UDP().
The documentation for this class was generated from the following files:
Kernel/include/net/udp.hpp
Kernel/Network/UserDatagramProtocol.cpp