Fennix Userspace: Userspace/musl/arch/aarch64/atomic_arch.h File Reference
atomic_arch.h File Reference
Macros
#define a_ll a_ll
#define a_sc a_sc
#define a_barrier a_barrier
#define a_cas a_cas
#define a_ll_p a_ll_p
#define a_sc_p a_sc_p
#define a_cas_p a_cas_p
#define a_ctz_64 a_ctz_64
#define a_clz_64 a_clz_64
Functions
static int a_ll (volatile int *p)
static int a_sc (volatile int *p, int v)
static int a_cas (volatile int *p, int t, int s)
static void * a_ll_p (volatile void *p)
static int a_sc_p (volatile int *p, void *v)
static void * a_cas_p (volatile void *p, void *t, void *s)
static int a_ctz_64 (uint64_t x)
static int a_clz_64 (uint64_t x)
Macro Definition Documentation
a_barrier
static void a_barrier a_barrier inline
Definition at line 17 of file atomic_arch.h.
Referenced by __aio_close(), __pthread_once(), __tl_sync(), a_cas(), a_cas_p(), aio_error(), and cancel_handler().
a_cas
#define a_cas a_cas
Definition at line 23 of file atomic_arch.h.
a_cas_p
#define a_cas_p a_cas_p
Definition at line 53 of file atomic_arch.h.
a_clz_64
#define a_clz_64 a_clz_64
Definition at line 77 of file atomic_arch.h.
a_ctz_64
#define a_ctz_64 a_ctz_64
Definition at line 67 of file atomic_arch.h.
a_ll
#define a_ll a_ll
Definition at line 1 of file atomic_arch.h.
a_ll_p
#define a_ll_p a_ll_p
Definition at line 37 of file atomic_arch.h.
a_sc
#define a_sc a_sc
Definition at line 9 of file atomic_arch.h.
a_sc_p
#define a_sc_p a_sc_p
Definition at line 45 of file atomic_arch.h.
Function Documentation
a_cas()
static int a_cas (volatile int * p, int t, int s) inline static
Definition at line 24 of file atomic_arch.h.
 {
     int old;
     do {
         old = a_ll(p);
         if (old != t) {
             a_barrier();
             break;
         }
     } while (!a_sc(p, s));
     return old;
 }
References a_barrier, a_ll, a_sc, old, p, s, and t.
a_cas_p()
static void* a_cas_p (volatile void * p, void * t, void * s) inline static
Definition at line 54 of file atomic_arch.h.
 {
     void *old;
     do {
         old = a_ll_p(p);
         if (old != t) {
             a_barrier();
             break;
         }
     } while (!a_sc_p(p, s));
     return old;
 }
References a_barrier, a_ll_p, a_sc_p, old, p, s, and t.
a_clz_64()
static int a_clz_64 (uint64_t x) inline static
Definition at line 78 of file atomic_arch.h.
 {
     __asm__("clz %0, %1" : "=r"(x) : "r"(x));
     return x;
 }
References __asm__(), and x.
a_ctz_64()
static int a_ctz_64 (uint64_t x) inline static
Definition at line 68 of file atomic_arch.h.
 {
     __asm__(
         "   rbit %0, %1\n"
         "   clz %0, %0\n"
         : "=r"(x) : "r"(x));
     return x;
 }
References __asm__(), and x.
a_ll()
static int a_ll (volatile int * p) inline static
Definition at line 2 of file atomic_arch.h.
 {
     int v;
     __asm__ __volatile__ ("ldaxr %w0,%1" : "=r"(v) : "Q"(*p));
     return v;
 }
References __asm__(), and p.
a_ll_p()
static void* a_ll_p (volatile void * p) inline static
Definition at line 38 of file atomic_arch.h.
 {
     void *v;
     __asm__ __volatile__ ("ldaxr %0, %1" : "=r"(v) : "Q"(*(void *volatile *)p));
     return v;
 }
References __asm__(), and p.
a_sc()
static int a_sc (volatile int * p, int v) inline static
Definition at line 10 of file atomic_arch.h.
 {
     int r;
     __asm__ __volatile__ ("stlxr %w0,%w2,%1" : "=&r"(r), "=Q"(*p) : "r"(v) : "memory");
     return !r;
 }
References __asm__(), and p.
a_sc_p()
static int a_sc_p (volatile int * p, void * v) inline static
Definition at line 46 of file atomic_arch.h.
 {
     int r;
     __asm__ __volatile__ ("stlxr %w0,%2,%1" : "=&r"(r), "=Q"(*(void *volatile *)p) : "r"(v) : "memory");
     return !r;
 }
References __asm__(), and p.