Fennix Userspace: Userspace/musl/arch/x86_64/atomic_arch.h File Reference
atomic_arch.h File Reference
Macros
#define a_cas a_cas
#define a_cas_p a_cas_p
#define a_swap a_swap
#define a_fetch_add a_fetch_add
#define a_and a_and
#define a_or a_or
#define a_and_64 a_and_64
#define a_or_64 a_or_64
#define a_inc a_inc
#define a_dec a_dec
#define a_store a_store
#define a_barrier a_barrier
#define a_spin a_spin
#define a_crash a_crash
#define a_ctz_64 a_ctz_64
#define a_clz_64 a_clz_64
Functions
static int a_cas (volatile int *p, int t, int s)
static void * a_cas_p (volatile void *p, void *t, void *s)
static int a_swap (volatile int *p, int v)
static int a_fetch_add (volatile int *p, int v)
static void a_and (volatile int *p, int v)
static void a_or (volatile int *p, int v)
static void a_and_64 (volatile uint64_t *p, uint64_t v)
static void a_or_64 (volatile uint64_t *p, uint64_t v)
static void a_inc (volatile int *p)
static void a_dec (volatile int *p)
static void a_store (volatile int *p, int x)
static int a_ctz_64 (uint64_t x)
static int a_clz_64 (uint64_t x)
Macro Definition Documentation
a_and
#define a_and a_and
Definition at line 37 of file atomic_arch.h.
a_and_64
#define a_and_64 a_and_64
Definition at line 53 of file atomic_arch.h.
a_barrier
#define a_barrier a_barrier
Definition at line 93 of file atomic_arch.h.
a_cas
#define a_cas a_cas
Definition at line 1 of file atomic_arch.h.
a_cas_p
#define a_cas_p a_cas_p
Definition at line 10 of file atomic_arch.h.
a_clz_64
#define a_clz_64 a_clz_64
Definition at line 118 of file atomic_arch.h.
a_crash
#define a_crash a_crash
Definition at line 105 of file atomic_arch.h.
a_ctz_64
#define a_ctz_64 a_ctz_64
Definition at line 111 of file atomic_arch.h.
a_dec
#define a_dec a_dec
Definition at line 77 of file atomic_arch.h.
a_fetch_add
#define a_fetch_add a_fetch_add
Definition at line 28 of file atomic_arch.h.
a_inc
#define a_inc a_inc
Definition at line 69 of file atomic_arch.h.
a_or
#define a_or a_or
Definition at line 45 of file atomic_arch.h.
a_or_64
#define a_or_64 a_or_64
Definition at line 61 of file atomic_arch.h.
a_spin
#define a_spin a_spin
Definition at line 99 of file atomic_arch.h.
a_store
#define a_store a_store
Definition at line 85 of file atomic_arch.h.
a_swap
#define a_swap a_swap
Definition at line 19 of file atomic_arch.h.
Function Documentation
a_and()
static void a_and (volatile int * p, int v) inline static
Definition at line 38 of file atomic_arch.h.
 {
     __asm__ __volatile__(
         "lock ; and %1, %0"
         : "=m"(*p) : "r"(v) : "memory" );
 }
References __asm__(), and p.
a_and_64()
static void a_and_64 (volatile uint64_t * p, uint64_t v) inline static
Definition at line 54 of file atomic_arch.h.
 {
     __asm__ __volatile(
         "lock ; and %1, %0"
          : "=m"(*p) : "r"(v) : "memory" );
 }
References __asm__(), and p.
a_cas()
static int a_cas (volatile int * p, int t, int s) inline static
Definition at line 2 of file atomic_arch.h.
 {
     __asm__ __volatile__ (
         "lock ; cmpxchg %3, %1"
         : "=a"(t), "=m"(*p) : "a"(t), "r"(s) : "memory" );
     return t;
 }
References __asm__(), p, s, and t.
a_cas_p()
static void* a_cas_p (volatile void * p, void * t, void * s) inline static
Definition at line 11 of file atomic_arch.h.
 {
     __asm__( "lock ; cmpxchg %3, %1"
         : "=a"(t), "=m"(*(void *volatile *)p)
         : "a"(t), "r"(s) : "memory" );
     return t;
 }
References __asm__(), p, s, and t.
a_clz_64()
static int a_clz_64 (uint64_t x) inline static
Definition at line 119 of file atomic_arch.h.
 {
     __asm__( "bsr %1,%0 ; xor $63,%0" : "=r"(x) : "r"(x) );
     return x;
 }
References __asm__(), and x.
a_ctz_64()
static int a_ctz_64 (uint64_t x) inline static
Definition at line 112 of file atomic_arch.h.
 {
     __asm__( "bsf %1,%0" : "=r"(x) : "r"(x) );
     return x;
 }
References __asm__(), and x.
a_dec()
static void a_dec (volatile int * p) inline static
Definition at line 78 of file atomic_arch.h.
 {
     __asm__ __volatile__(
         "lock ; decl %0"
         : "=m"(*p) : "m"(*p) : "memory" );
 }
References __asm__(), and p.
a_fetch_add()
static int a_fetch_add (volatile int * p, int v) inline static
Definition at line 29 of file atomic_arch.h.
 {
     __asm__ __volatile__(
         "lock ; xadd %0, %1"
         : "=r"(v), "=m"(*p) : "0"(v) : "memory" );
     return v;
 }
References __asm__(), and p.
a_inc()
static void a_inc (volatile int * p) inline static
Definition at line 70 of file atomic_arch.h.
 {
     __asm__ __volatile__(
         "lock ; incl %0"
         : "=m"(*p) : "m"(*p) : "memory" );
 }
References __asm__(), and p.
a_or()
static void a_or (volatile int * p, int v) inline static
Definition at line 46 of file atomic_arch.h.
 {
     __asm__ __volatile__(
         "lock ; or %1, %0"
         : "=m"(*p) : "r"(v) : "memory" );
 }
References __asm__(), and p.
a_or_64()
static void a_or_64 (volatile uint64_t * p, uint64_t v) inline static
Definition at line 62 of file atomic_arch.h.
 {
     __asm__ __volatile__(
         "lock ; or %1, %0"
          : "=m"(*p) : "r"(v) : "memory" );
 }
References __asm__(), and p.
a_store()
static void a_store (volatile int * p, int x) inline static
Definition at line 86 of file atomic_arch.h.
 {
     __asm__ __volatile__(
         "mov %1, %0 ; lock ; orl $0,(%%rsp)"
         : "=m"(*p) : "r"(x) : "memory" );
 }
References __asm__(), p, and x.
a_swap()
static int a_swap (volatile int * p, int v) inline static
Definition at line 20 of file atomic_arch.h.
 {
     __asm__ __volatile__(
         "xchg %0, %1"
         : "=r"(v), "=m"(*p) : "0"(v) : "memory" );
     return v;
 }
References __asm__(), and p.