Fennix: Userspace/apps/base/busybox/include/dump.h File Reference
dump.h File Reference
Data Structures
struct PR
struct FU
struct FS
struct dumper_t
Typedefs
typedef struct PR PR
typedef struct FU FU
typedef struct FS FS
typedef struct dumper_t dumper_t
Enumerations
enum dump_vflag_t { ALL , DUP , FIRST , WAIT }
Functions
dumper_t * alloc_dumper (void) FAST_FUNC
void bb_dump_add (dumper_t *dumper, const char *fmt) FAST_FUNC
int bb_dump_dump (dumper_t *dumper, char **argv) FAST_FUNC
Data Structure Documentation
PR
struct PR
Definition at line 7 of file dump.h.
Data Fields
int bcnt
char * cchar
unsigned flags
char * fmt
struct PR * nextpr
char * nospace
FU
struct FU
Definition at line 16 of file dump.h.
Data Fields
int bcnt
unsigned flags
char * fmt
struct FU * nextfu
struct PR * nextpr
int reps
FS
struct FS
Definition at line 25 of file dump.h.
Data Fields
int bcnt
struct FS * nextfs
struct FU * nextfu
dumper_t
struct dumper_t
Definition at line 31 of file dump.h.
Data Fields
off_t address
int dump_length
off_t dump_skip
smallint dump_vflag
FS * fshead
long long xxd_displayoff
const char * xxd_eofstring
Typedef Documentation
dumper_t
typedef struct dumper_t dumper_t
FS
typedef struct FS FS
FU
typedef struct FU FU
PR
typedef struct PR PR
Enumeration Type Documentation
dump_vflag_t
enum dump_vflag_t
Enumerator
ALL
DUP
FIRST
WAIT
Definition at line 5 of file dump.h.
 { ALL, DUP, FIRST, WAIT };  /* -v values */
Function Documentation
alloc_dumper()
dumper_t* alloc_dumper (void)
Definition at line 54 of file dump.c.
 {
     priv_dumper_t *dumper = xzalloc(sizeof(*dumper));
     dumper->pub.dump_length = -1;
     dumper->pub.dump_vflag = FIRST;
     dumper->get__ateof = 1;
     return &dumper->pub;
 }
References dumper, FIRST, and xzalloc().
Referenced by hexdump_main(), od_main(), and xxd_main().
bb_dump_add()
void bb_dump_add (dumper_t * dumper, const char * fmt)
Definition at line 717 of file dump.c.
 {
     const char *p;
     FS *tfs;
     FU **nextfupp;
     /* start new linked list of format units */
     tfs = xzalloc(sizeof(FS)); /*DBU:[dave@cray.com] start out NULL */
     if (!dumper->pub.fshead) {
         dumper->pub.fshead = tfs;
     } else {
         FS *fslast = dumper->pub.fshead;
         while (fslast->nextfs)
             fslast = fslast->nextfs;
         fslast->nextfs = tfs;
     }
     nextfupp = &tfs->nextfu;
     /* take the format string and break it up into format units */
     p = fmt;
     for (;;) {
         FU *tfu;
         const char *savep;
         p = skip_whitespace(p);
         if (*p == '\0') {
             break;
         }
         /* allocate a new format unit and link it in */
         /* NOSTRICT */
         /* DBU:[dave@cray.com] zalloc so that forward pointers start out NULL */
         tfu = xzalloc(sizeof(FU));
         *nextfupp = tfu;
         nextfupp = &tfu->nextfu;
         tfu->reps = 1;
         /* if leading digit, repetition count */
         if (isdigit(*p)) {
             for (savep = p; isdigit(*p); ++p)
                 continue;
             if (!isspace(*p) && *p != '/') {
                 bb_error_msg_and_die("bad format {%s}", fmt);
             }
             /* may overwrite either white space or slash */
             tfu->reps = atoi(savep);
             tfu->flags = F_SETREP;
             /* skip trailing white space */
             p = skip_whitespace(++p);
         }
         /* skip slash and trailing white space */
         if (*p == '/') {
             p = skip_whitespace(p + 1);
         }
         /* byte count */
         if (isdigit(*p)) {
 // TODO: use bb_strtou
             savep = p;
             while (isdigit(*++p))
                 continue;
             if (!isspace(*p)) {
                 bb_error_msg_and_die("bad format {%s}", fmt);
             }
 // Above check prohibits formats such as '/1"%02x"' - it requires space after 1.
 // Other than this, formats can be pretty much jammed together:
 // "%07_ax:"8/2 "%04x|""\n"
 // but this space is required. The check *can* be removed, but
 // keeping it to stay compat with util-linux hexdump.
             tfu->bcnt = atoi(savep);
             /* skip trailing white space */
             p = skip_whitespace(p + 1);
         }
         /* format */
         if (*p != '"') {
             bb_error_msg_and_die("bad format {%s}", fmt);
         }
         for (savep = ++p; *p != '"';) {
             if (*p++ == '\0') {
                 bb_error_msg_and_die("bad format {%s}", fmt);
             }
         }
         tfu->fmt = xstrndup(savep, p - savep);
         /* alphabetic escape sequences have to be done in place */
         strcpy_and_process_escape_sequences(tfu->fmt, tfu->fmt);
         /* unknown mappings are not changed: "\z" -> '\\' 'z' */
         /* trailing backslash, if any, is preserved */
 #if 0
         char *p1;
         char *p2;
         p1 = tfu->fmt;
         for (p2 = p1;; ++p1, ++p2) {
             *p2 = *p1;
             if (*p1 == '\0')
                 break;
             if (*p1 == '\\') {
                 const char *cs;
                 p1++;
                 *p2 = *p1;
                 if (*p1 == '\0') {
                     /* "...\" trailing backslash. Eaten. */
                     break;
                 }
                 cs = conv_str + 4; /* skip NUL element */
                 do {
                     /* map e.g. "\n" -> '\n' */
                     if (*p1 == cs[2]) {
                         *p2 = cs[0];
                         break;
                     }
                     cs += 4;
                 } while (*cs);
                 /* unknown mappings remove bkslash: "\z" -> 'z' */
             }
         }
 #endif
         p++;
     }
 }
References atoi(), bb_error_msg_and_die(), FU::bcnt, dumper, F_SETREP, FU::flags, FU::fmt, isdigit, isspace, FS::nextfs, FU::nextfu, FS::nextfu, p, FU::reps, skip_whitespace(), strcpy_and_process_escape_sequences(), xstrndup(), and xzalloc().
Referenced by bb_dump_addfile(), hexdump_main(), od_main(), and xxd_main().
bb_dump_dump()
int bb_dump_dump (dumper_t * dumper, char ** argv)
Definition at line 689 of file dump.c.
 {
     FS *tfs;
     int blocksize;
     /* figure out the data block size */
     blocksize = 0;
     tfs = dumper->pub.fshead;
     while (tfs) {
         tfs->bcnt = bb_dump_size(tfs);
         if (blocksize < tfs->bcnt) {
             blocksize = tfs->bcnt;
         }
         tfs = tfs->nextfs;
     }
     dumper->blocksize = blocksize;
     /* rewrite the rules, do syntax checking */
     for (tfs = dumper->pub.fshead; tfs; tfs = tfs->nextfs) {
         rewrite(dumper, tfs);
     }
     dumper->argv = argv;
     display(dumper);
     return dumper->exitval;
 }
References argv, bb_dump_size(), FS::bcnt, bcnt, display(), dumper, FS::nextfs, and rewrite().
Referenced by hexdump_main(), od_main(), and xxd_main().