Fennix Userspace: Userspace/musl/src/stdio/freopen.c File Reference
freopen.c File Reference
#include "stdio_impl.h"
#include <fcntl.h>
#include <unistd.h>
Functions
FILE * freopen (const char *restrict filename, const char *restrict mode, FILE *restrict f)
Function Documentation
freopen()
FILE* freopen (const char *restrict filename, const char *restrict mode, FILE *restrict f)
Definition at line 13 of file freopen.c.
 {
     int fl = __fmodeflags(mode);
     FILE *f2;
     FLOCK(f);
     fflush(f);
     if (!filename) {
         if (fl&O_CLOEXEC)
             __syscall(SYS_fcntl, f->fd, F_SETFD, FD_CLOEXEC);
         fl &= ~(O_CREAT|O_EXCL|O_CLOEXEC);
         if (syscall(SYS_fcntl, f->fd, F_SETFL, fl) < 0)
             goto fail;
     } else {
         f2 = fopen(filename, mode);
         if (!f2) goto fail;
         if (f2->fd == f->fd) f2->fd = -1; /* avoid closing in fclose */
         else if (__dup3(f2->fd, f->fd, fl&O_CLOEXEC)<0) goto fail2;
         f->flags = (f->flags & F_PERM) | f2->flags;
         f->read = f2->read;
         f->write = f2->write;
         f->seek = f2->seek;
         f->close = f2->close;
         fclose(f2);
     }
     f->mode = 0;
     f->locale = 0;
     FUNLOCK(f);
     return f;
 fail2:
     fclose(f2);
 fail:
     fclose(f);
     return NULL;
 }
References __dup3(), __fmodeflags(), __syscall, _IO_FILE::close, f, F_PERM, F_SETFD, F_SETFL, fclose(), _IO_FILE::fd, FD_CLOEXEC, fflush(), _IO_FILE::flags, FLOCK, fopen(), FUNLOCK, _IO_FILE::locale, _IO_FILE::mode, NULL, O_CLOEXEC, O_CREAT, O_EXCL, _IO_FILE::read, _IO_FILE::seek, syscall(), and _IO_FILE::write.