Fennix Userspace: Userspace/musl/src/time/clock_getres.c File Reference
clock_getres.c File Reference
#include <time.h>
#include "syscall.h"
Functions
int clock_getres (clockid_t clk, struct timespec *ts)
Function Documentation
clock_getres()
int clock_getres (clockid_t clk, struct timespec * ts)
Definition at line 4 of file clock_getres.c.
 {
 #ifdef SYS_clock_getres_time64
     /* On a 32-bit arch, use the old syscall if it exists. */
     if (SYS_clock_getres != SYS_clock_getres_time64) {
         long ts32[2];
         int r = __syscall(SYS_clock_getres, clk, ts32);
         if (!r && ts) {
             ts->tv_sec = ts32[0];
             ts->tv_nsec = ts32[1];
         }
         return __syscall_ret(r);
     }
 #endif
     /* If reaching this point, it's a 64-bit arch or time64-only
      * 32-bit arch and we can get result directly into timespec. */
     return syscall(SYS_clock_getres, clk, ts);
 }
References __syscall, __syscall_ret(), SYS_clock_getres, and syscall().
Referenced by __clock_getres_time32().