Fennix: std::atomic< T > Class Template Reference
std::atomic< T > Class Template Reference
#include <atomic.hpp>
Public Member Functions
atomic () noexcept
atomic (T desired) noexcept
T load (memory_order order=memory_order::seq_cst) const noexcept
Load the value of the atomic variable.
T load (memory_order order=memory_order::seq_cst) const volatile noexcept
Load the value of the atomic variable.
void store (T desired, memory_order order=memory_order::seq_cst) noexcept
Store the value of the atomic variable.
void store (T desired, memory_order order=memory_order::seq_cst) volatile noexcept
Store the value of the atomic variable.
T exchange (T desired, memory_order order=memory_order::seq_cst) noexcept
Exchange the value of the atomic variable.
T exchange (T desired, memory_order order=memory_order::seq_cst) volatile noexcept
Exchange the value of the atomic variable.
bool compare_exchange_weak (T &expected, T desired, std::memory_order success, std::memory_order failure) noexcept
Compare and exchange the value of the atomic variable.
bool compare_exchange_weak (T &expected, T desired, std::memory_order success, std::memory_order failure) volatile noexcept
Compare and exchange the value of the atomic variable.
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
Compare and exchange the value of the atomic variable.
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Compare and exchange the value of the atomic variable.
bool compare_exchange_strong (T &expected, T desired, std::memory_order success, std::memory_order failure) noexcept
Compare and exchange the value of the atomic variable.
bool compare_exchange_strong (T &expected, T desired, std::memory_order success, std::memory_order failure) volatile noexcept
Compare and exchange the value of the atomic variable.
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
Compare and exchange the value of the atomic variable.
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Compare and exchange the value of the atomic variable.
T fetch_add (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
Fetch and add the value of the atomic variable.
T fetch_add (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Fetch and add the value of the atomic variable.
T fetch_sub (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
Fetch and subtract the value of the atomic variable.
T fetch_sub (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Fetch and subtract the value of the atomic variable.
T fetch_and (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
Fetch and bitwise AND the value of the atomic variable.
T fetch_and (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Fetch and bitwise AND the value of the atomic variable.
T fetch_or (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
Fetch and bitwise OR the value of the atomic variable.
T fetch_or (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Fetch and bitwise OR the value of the atomic variable.
T fetch_xor (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
Fetch and bitwise XOR the value of the atomic variable.
T fetch_xor (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Fetch and bitwise XOR the value of the atomic variable.
T fetch_nand (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
Fetch and bitwise NAND the value of the atomic variable.
T fetch_nand (T arg, std::memory_order order=std::memory_order_seq_cst) volatile noexcept
Fetch and bitwise NAND the value of the atomic variable.
void notify_all () noexcept
Notify all threads waiting on this atomic variable.
void notify_all () volatile noexcept
Notify all threads waiting on this atomic variable.
void notify_one () noexcept
Notify one thread waiting on this atomic variable.
void notify_one () volatile noexcept
Notify one thread waiting on this atomic variable.
void wait (T old, std::memory_order order=std::memory_order::seq_cst) const noexcept
Wait for the atomic variable to change.
void wait (T old, std::memory_order order=std::memory_order::seq_cst) const volatile noexcept
Wait for the atomic variable to change.
bool is_lock_free () const noexcept
Check whether this atomic type is lock-free.
bool is_lock_free () const volatile noexcept
Check whether this atomic type is lock-free.
T operator++ () noexcept
T operator-- () noexcept
T operator++ (int) noexcept
T operator-- (int) noexcept
T operator+= (T desired) noexcept
T operator-= (T desired) noexcept
T operator&= (T desired) noexcept
T operator|= (T desired) noexcept
T operator^= (T desired) noexcept
T operator-> () noexcept
T operator~ () noexcept
bool operator== (const atomic &other) const noexcept
bool operator== (T other) const noexcept
atomic & operator= (const atomic &)=delete
T operator= (T desired) noexcept
operator bool () noexcept
operator T () const noexcept
Static Public Attributes
static constexpr bool is_always_lock_free = true
Equals true if this atomic type is always lock-free.
Private Member Functions
_atomic (T) value
Detailed Description
template<typename T>
class std::atomic< T >
Definition at line 87 of file atomic.hpp.
Constructor & Destructor Documentation
atomic() [1/2]
template<typename T > std::atomic< T >::atomic () inline noexcept
Definition at line 92 of file atomic.hpp.
 : value(0) {}
atomic() [2/2]
template<typename T > std::atomic< T >::atomic (T desired) inline noexcept
Definition at line 93 of file atomic.hpp.
 : value(desired) {}
Member Function Documentation
_atomic()
template<typename T > std::atomic< T >::_atomic (T) private
compare_exchange_strong() [1/4]
template<typename T > bool std::atomic< T >::compare_exchange_strong (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Compare and exchange the value of the atomic variable.
Parameters
expected The expected value
desired The desired value
order Memory order constraint to use
Returns
True if the exchange succeeded, false otherwise
Definition at line 231 of file atomic.hpp.
         {
             return builtin_atomic(compare_exchange_strong)(&this->value, &expected, desired, true, order, static_cast<int>(order));
         }
References builtin_atomic, std::atomic< T >::compare_exchange_strong(), and value.
compare_exchange_strong() [2/4]
template<typename T > bool std::atomic< T >::compare_exchange_strong (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Compare and exchange the value of the atomic variable.
Parameters
expected The expected value
desired The desired value
success Memory order constraint to use if the exchange succeeds
failure Memory order constraint to use if the exchange fails
Returns
True if the exchange succeeded, false otherwise
Definition at line 239 of file atomic.hpp.
         {
             return builtin_atomic(compare_exchange_strong)(&this->value, &expected, desired, true, order, static_cast<int>(order));
         }
References builtin_atomic, std::atomic< T >::compare_exchange_strong(), and value.
compare_exchange_strong() [3/4]
template<typename T > bool std::atomic< T >::compare_exchange_strong (T & expected, T desired, std::memory_order success, std::memory_order failure) inline noexcept
Compare and exchange the value of the atomic variable.
Parameters
expected The expected value
desired The desired value
success Memory order constraint to use if the exchange succeeds
failure Memory order constraint to use if the exchange fails
Returns
True if the exchange succeeded, false otherwise
Definition at line 210 of file atomic.hpp.
         {
             return builtin_atomic(compare_exchange_strong)(&this->value, &expected, desired, true, success, failure);
         }
References builtin_atomic, and value.
Referenced by std::atomic< T >::compare_exchange_strong().
compare_exchange_strong() [4/4]
template<typename T > bool std::atomic< T >::compare_exchange_strong (T & expected, T desired, std::memory_order success, std::memory_order failure) volatile inline noexcept
Compare and exchange the value of the atomic variable.
Parameters
expected The expected value
desired The desired value
success Memory order constraint to use if the exchange succeeds
failure Memory order constraint to use if the exchange fails
Returns
True if the exchange succeeded, false otherwise
Definition at line 218 of file atomic.hpp.
         {
             return builtin_atomic(compare_exchange_strong)(&this->value, &expected, desired, true, success, failure);
         }
References builtin_atomic, std::atomic< T >::compare_exchange_strong(), and value.
compare_exchange_weak() [1/4]
template<typename T > bool std::atomic< T >::compare_exchange_weak (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Compare and exchange the value of the atomic variable.
Parameters
expected The expected value
desired The desired value
order Memory order constraint to use
Returns
True if the exchange succeeded, false otherwise
Definition at line 188 of file atomic.hpp.
         {
             return builtin_atomic(compare_exchange_weak)(&this->value, &expected, desired, false, order, static_cast<int>(order));
         }
References builtin_atomic, std::atomic< T >::compare_exchange_weak(), and value.
compare_exchange_weak() [2/4]
template<typename T > bool std::atomic< T >::compare_exchange_weak (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Compare and exchange the value of the atomic variable.
Parameters
expected The expected value
desired The desired value
success Memory order constraint to use if the exchange succeeds
failure Memory order constraint to use if the exchange fails
Returns
True if the exchange succeeded, false otherwise
Definition at line 196 of file atomic.hpp.
         {
             return builtin_atomic(compare_exchange_weak)(&this->value, &expected, desired, false, order, static_cast<int>(order));
         }
References builtin_atomic, std::atomic< T >::compare_exchange_weak(), and value.
compare_exchange_weak() [3/4]
template<typename T > bool std::atomic< T >::compare_exchange_weak (T & expected, T desired, std::memory_order success, std::memory_order failure) inline noexcept
Compare and exchange the value of the atomic variable.
Parameters
expected The expected value
desired The desired value
success Memory order constraint to use if the exchange succeeds
failure Memory order constraint to use if the exchange fails
Returns
True if the exchange succeeded, false otherwise
Definition at line 167 of file atomic.hpp.
         {
             return builtin_atomic(compare_exchange_weak)(&this->value, &expected, desired, false, success, failure);
         }
References builtin_atomic, and value.
Referenced by std::atomic< T >::compare_exchange_weak().
compare_exchange_weak() [4/4]
template<typename T > bool std::atomic< T >::compare_exchange_weak (T & expected, T desired, std::memory_order success, std::memory_order failure) volatile inline noexcept
Compare and exchange the value of the atomic variable.
Parameters
expected The expected value
desired The desired value
success Memory order constraint to use if the exchange succeeds
failure Memory order constraint to use if the exchange fails
Returns
True if the exchange succeeded, false otherwise
Definition at line 175 of file atomic.hpp.
         {
             return builtin_atomic(compare_exchange_weak)(&this->value, &expected, desired, false, success, failure);
         }
References builtin_atomic, std::atomic< T >::compare_exchange_weak(), and value.
exchange() [1/2]
template<typename T > T std::atomic< T >::exchange (T desired, memory_order order = memory_order::seq_cst) inline noexcept
Exchange the value of the atomic variable.
Parameters
desired The value to exchange
order Memory order constraint to use
Returns
The value of the atomic variable before the exchange
Definition at line 145 of file atomic.hpp.
         {
             return builtin_atomic_n(exchange)(&this->value, desired, static_cast<int>(order));
         }
References builtin_atomic_n, and value.
Referenced by std::atomic< T >::exchange().
exchange() [2/2]
template<typename T > T std::atomic< T >::exchange (T desired, memory_order order = memory_order::seq_cst) volatile inline noexcept
Exchange the value of the atomic variable.
Parameters
desired The value to exchange
order Memory order constraint to use
Returns
The value of the atomic variable before the exchange
Definition at line 153 of file atomic.hpp.
         {
             return builtin_atomic_n(exchange)(&this->value, desired, static_cast<int>(order));
         }
References builtin_atomic_n, std::atomic< T >::exchange(), and value.
fetch_add() [1/2]
template<typename T > T std::atomic< T >::fetch_add (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Fetch and add the value of the atomic variable.
Parameters
arg The value to add
order Memory order constraint to use
Returns
The value of the atomic variable before the addition
Definition at line 251 of file atomic.hpp.
         {
             return builtin_atomic(fetch_add)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, and value.
Referenced by std::atomic< T >::fetch_add(), std::atomic< T >::operator++(), and std::atomic< T >::operator+=().
fetch_add() [2/2]
template<typename T > T std::atomic< T >::fetch_add (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Fetch and add the value of the atomic variable.
Parameters
arg The value to add
order Memory order constraint to use
Returns
The value of the atomic variable before the addition
Definition at line 259 of file atomic.hpp.
         {
             return builtin_atomic(fetch_add)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, std::atomic< T >::fetch_add(), and value.
fetch_and() [1/2]
template<typename T > T std::atomic< T >::fetch_and (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Fetch and bitwise AND the value of the atomic variable.
Parameters
arg The value to AND
order Memory order constraint to use
Returns
The value of the atomic variable before the AND
Definition at line 291 of file atomic.hpp.
         {
             return builtin_atomic(fetch_and)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, and value.
Referenced by std::atomic< T >::fetch_and(), and std::atomic< T >::operator&=().
fetch_and() [2/2]
template<typename T > T std::atomic< T >::fetch_and (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Fetch and bitwise AND the value of the atomic variable.
Parameters
arg The value to AND
order Memory order constraint to use
Returns
The value of the atomic variable before the AND
Definition at line 299 of file atomic.hpp.
         {
             return builtin_atomic(fetch_and)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, std::atomic< T >::fetch_and(), and value.
fetch_nand() [1/2]
template<typename T > T std::atomic< T >::fetch_nand (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Fetch and bitwise NAND the value of the atomic variable.
Parameters
arg The value to NAND
order Memory order constraint to use
Returns
The value of the atomic variable before the NAND
Definition at line 351 of file atomic.hpp.
         {
             return builtin_atomic(fetch_nand)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, and value.
Referenced by std::atomic< T >::fetch_nand(), and std::atomic< T >::operator~().
fetch_nand() [2/2]
template<typename T > T std::atomic< T >::fetch_nand (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Fetch and bitwise NAND the value of the atomic variable.
Parameters
arg The value to NAND
order Memory order constraint to use
Returns
The value of the atomic variable before the NAND
Definition at line 359 of file atomic.hpp.
         {
             return builtin_atomic(fetch_nand)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, std::atomic< T >::fetch_nand(), and value.
fetch_or() [1/2]
template<typename T > T std::atomic< T >::fetch_or (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Fetch and bitwise OR the value of the atomic variable.
Parameters
arg The value to OR
order Memory order constraint to use
Returns
The value of the atomic variable before the OR
Definition at line 311 of file atomic.hpp.
         {
             return builtin_atomic(fetch_or)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, and value.
Referenced by std::atomic< T >::fetch_or(), and std::atomic< T >::operator|=().
fetch_or() [2/2]
template<typename T > T std::atomic< T >::fetch_or (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Fetch and bitwise OR the value of the atomic variable.
Parameters
arg The value to OR
order Memory order constraint to use
Returns
The value of the atomic variable before the OR
Definition at line 319 of file atomic.hpp.
         {
             return builtin_atomic(fetch_or)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, std::atomic< T >::fetch_or(), and value.
fetch_sub() [1/2]
template<typename T > T std::atomic< T >::fetch_sub (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Fetch and subtract the value of the atomic variable.
Parameters
arg The value to subtract
order Memory order constraint to use
Returns
The value of the atomic variable before the subtraction
Definition at line 271 of file atomic.hpp.
         {
             return builtin_atomic(fetch_sub)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, and value.
Referenced by std::atomic< T >::fetch_sub(), std::atomic< T >::operator--(), and std::atomic< T >::operator-=().
fetch_sub() [2/2]
template<typename T > T std::atomic< T >::fetch_sub (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Fetch and subtract the value of the atomic variable.
Parameters
arg The value to subtract
order Memory order constraint to use
Returns
The value of the atomic variable before the subtraction
Definition at line 279 of file atomic.hpp.
         {
             return builtin_atomic(fetch_sub)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, std::atomic< T >::fetch_sub(), and value.
fetch_xor() [1/2]
template<typename T > T std::atomic< T >::fetch_xor (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Fetch and bitwise XOR the value of the atomic variable.
Parameters
arg The value to XOR
order Memory order constraint to use
Returns
The value of the atomic variable before the XOR
Definition at line 331 of file atomic.hpp.
         {
             return builtin_atomic(fetch_xor)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, and value.
Referenced by std::atomic< T >::fetch_xor(), and std::atomic< T >::operator^=().
fetch_xor() [2/2]
template<typename T > T std::atomic< T >::fetch_xor (T arg, std::memory_order order = std::memory_order_seq_cst) volatile inline noexcept
Fetch and bitwise XOR the value of the atomic variable.
Parameters
arg The value to XOR
order Memory order constraint to use
Returns
The value of the atomic variable before the XOR
Definition at line 339 of file atomic.hpp.
         {
             return builtin_atomic(fetch_xor)(&this->value, arg, static_cast<int>(order));
         }
References arg, builtin_atomic, std::atomic< T >::fetch_xor(), and value.
is_lock_free() [1/2]
template<typename T > bool std::atomic< T >::is_lock_free () const inline noexcept
Check whether this atomic type is lock-free.
Returns
True if this atomic type is lock-free
Definition at line 419 of file atomic.hpp.
         {
             fixme("not implemented");
             return true;
         }
References fixme.
is_lock_free() [2/2]
template<typename T > bool std::atomic< T >::is_lock_free () const volatile inline noexcept
Check whether this atomic type is lock-free.
Returns
True if this atomic type is lock-free
Definition at line 428 of file atomic.hpp.
         {
             fixme("not implemented");
             return true;
         }
References fixme.
load() [1/2]
template<typename T > T std::atomic< T >::load (memory_order order = memory_order::seq_cst) const inline noexcept
Load the value of the atomic variable.
Note
Order must be one of memory_order::relaxed, memory_order::consume, memory_order::acquire or memory_order::seq_cst
Parameters
order Memory order constraint to use
Returns
The value of the atomic variable
Definition at line 104 of file atomic.hpp.
         {
             return builtin_atomic_n(load)(&this->value, static_cast<int>(order));
         }
References builtin_atomic_n, and value.
Referenced by Tasking::Task::GetCurrentProcess(), Tasking::Task::GetCurrentThread(), Tasking::Task::GetLastCore(), Tasking::Task::GetLastTaskTicks(), GetLocksCount(), Tasking::Task::GetSchedulerTicks(), CrashHandler::Handle(), std::atomic< T >::load(), std::atomic< T >::operator bool(), std::atomic< T >::operator T(), std::atomic< T >::operator->(), std::atomic< T >::operator==(), and Tasking::Task::~Task().
load() [2/2]
template<typename T > T std::atomic< T >::load (memory_order order = memory_order::seq_cst) const volatile inline noexcept
Load the value of the atomic variable.
Note
Order must be one of memory_order::relaxed, memory_order::consume, memory_order::acquire or memory_order::seq_cst
Parameters
order Memory order constraint to use
Returns
The value of the atomic variable
Definition at line 112 of file atomic.hpp.
         {
             return builtin_atomic_n(load)(&this->value, static_cast<int>(order));
         }
References builtin_atomic_n, std::atomic< T >::load(), and value.
notify_all() [1/2]
template<typename T > void std::atomic< T >::notify_all () inline noexcept
Notify all threads waiting on this atomic variable.
Definition at line 367 of file atomic.hpp.
         {
             fixme("not implemented");
         }
References fixme.
notify_all() [2/2]
template<typename T > void std::atomic< T >::notify_all () volatile inline noexcept
Notify all threads waiting on this atomic variable.
Definition at line 375 of file atomic.hpp.
         {
             fixme("not implemented");
         }
References fixme.
notify_one() [1/2]
template<typename T > void std::atomic< T >::notify_one () inline noexcept
Notify one thread waiting on this atomic variable.
Definition at line 383 of file atomic.hpp.
         {
             fixme("not implemented");
         }
References fixme.
notify_one() [2/2]
template<typename T > void std::atomic< T >::notify_one () volatile inline noexcept
Notify one thread waiting on this atomic variable.
Definition at line 391 of file atomic.hpp.
         {
             fixme("not implemented");
         }
References fixme.
operator bool()
template<typename T > std::atomic< T >::operator bool () inline noexcept
Definition at line 466 of file atomic.hpp.
 { return this->load() != 0; }
References std::atomic< T >::load().
operator T()
template<typename T > std::atomic< T >::operator T () const inline noexcept
Definition at line 468 of file atomic.hpp.
 { return this->load(); }
References std::atomic< T >::load().
operator&=()
template<typename T > T std::atomic< T >::operator&= (T desired) inline noexcept
Definition at line 449 of file atomic.hpp.
 { return this->fetch_and(desired) & desired; }
References std::atomic< T >::fetch_and().
operator++() [1/2]
template<typename T > T std::atomic< T >::operator++ () inline noexcept
Definition at line 439 of file atomic.hpp.
 { return this->fetch_add(1) + 1; }
References std::atomic< T >::fetch_add().
operator++() [2/2]
template<typename T > T std::atomic< T >::operator++ (int) inline noexcept
Definition at line 441 of file atomic.hpp.
 { return this->fetch_add(1); }
References std::atomic< T >::fetch_add().
operator+=()
template<typename T > T std::atomic< T >::operator+= (T desired) inline noexcept
Definition at line 444 of file atomic.hpp.
 { return this->fetch_add(desired) + desired; }
References std::atomic< T >::fetch_add().
operator--() [1/2]
template<typename T > T std::atomic< T >::operator-- () inline noexcept
Definition at line 440 of file atomic.hpp.
 { return this->fetch_sub(1) - 1; }
References std::atomic< T >::fetch_sub().
operator--() [2/2]
template<typename T > T std::atomic< T >::operator-- (int) inline noexcept
Definition at line 442 of file atomic.hpp.
 { return this->fetch_sub(1); }
References std::atomic< T >::fetch_sub().
operator-=()
template<typename T > T std::atomic< T >::operator-= (T desired) inline noexcept
Definition at line 445 of file atomic.hpp.
 { return this->fetch_sub(desired) - desired; }
References std::atomic< T >::fetch_sub().
operator->()
template<typename T > T std::atomic< T >::operator-> () inline noexcept
Definition at line 453 of file atomic.hpp.
 { return this->load(); }
References std::atomic< T >::load().
operator=() [1/2]
template<typename T > atomic& std::atomic< T >::operator= (const atomic< T > &) delete
operator=() [2/2]
template<typename T > T std::atomic< T >::operator= (T desired) inline noexcept
Definition at line 460 of file atomic.hpp.
         {
             this->store(desired);
             return desired;
         }
References std::atomic< T >::store().
operator==() [1/2]
template<typename T > bool std::atomic< T >::operator== (const atomic< T > & other) const inline noexcept
Definition at line 456 of file atomic.hpp.
 { return this->load() == other.load(); }
References std::atomic< T >::load().
operator==() [2/2]
template<typename T > bool std::atomic< T >::operator== (T other) const inline noexcept
Definition at line 457 of file atomic.hpp.
 { return this->load() == other; }
References std::atomic< T >::load().
operator^=()
template<typename T > T std::atomic< T >::operator^= (T desired) inline noexcept
Definition at line 451 of file atomic.hpp.
 { return this->fetch_xor(desired) ^ desired; }
References std::atomic< T >::fetch_xor().
operator|=()
template<typename T > T std::atomic< T >::operator|= (T desired) inline noexcept
Definition at line 450 of file atomic.hpp.
 { return this->fetch_or(desired) | desired; }
References std::atomic< T >::fetch_or().
operator~()
template<typename T > T std::atomic< T >::operator~ () inline noexcept
Definition at line 454 of file atomic.hpp.
 { return this->fetch_nand(-1); }
References std::atomic< T >::fetch_nand().
store() [1/2]
template<typename T > void std::atomic< T >::store (T desired, memory_order order = memory_order::seq_cst) inline noexcept
Store the value of the atomic variable.
Note
Order must be one of memory_order::relaxed, memory_order::release or memory_order::seq_cst
Parameters
desired The value to store
order Memory order constraint to use
Definition at line 125 of file atomic.hpp.
         {
             builtin_atomic_n(store)(&this->value, desired, static_cast<int>(order));
         }
References builtin_atomic_n, and value.
Referenced by std::atomic< T >::operator=(), and std::atomic< T >::store().
store() [2/2]
template<typename T > void std::atomic< T >::store (T desired, memory_order order = memory_order::seq_cst) volatile inline noexcept
Store the value of the atomic variable.
Note
Order must be one of memory_order::relaxed, memory_order::release or memory_order::seq_cst
Parameters
desired The value to store
order Memory order constraint to use
Definition at line 133 of file atomic.hpp.
         {
             builtin_atomic_n(store)(&this->value, desired, static_cast<int>(order));
         }
References builtin_atomic_n, std::atomic< T >::store(), and value.
wait() [1/2]
template<typename T > void std::atomic< T >::wait (T old, std::memory_order order = std::memory_order::seq_cst) const inline noexcept
Wait for the atomic variable to change.
Parameters
old The value to wait for
order Memory order constraint to use
Definition at line 402 of file atomic.hpp.
         {
             fixme("not implemented");
         }
References fixme.
wait() [2/2]
template<typename T > void std::atomic< T >::wait (T old, std::memory_order order = std::memory_order::seq_cst) const volatile inline noexcept
Wait for the atomic variable to change.
Parameters
old The value to wait for
order Memory order constraint to use
Definition at line 410 of file atomic.hpp.
         {
             fixme("not implemented");
         }
References fixme.
Field Documentation
is_always_lock_free
template<typename T > constexpr bool std::atomic< T >::is_always_lock_free = true static constexpr
Equals true if this atomic type is always lock-free.
Definition at line 437 of file atomic.hpp.
The documentation for this class was generated from the following file:
Kernel/include_std/std/atomic.hpp