Fennix: Userspace/apps/base/bash/variables.c File Reference
variables.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixstat.h"
#include "posixtime.h"
#include <stdio.h>
#include "chartypes.h"
#include "bashansi.h"
#include "bashintl.h"
#include "filecntl.h"
#include "shell.h"
#include "parser.h"
#include "flags.h"
#include "execute_cmd.h"
#include "findcmd.h"
#include "mailcheck.h"
#include "input.h"
#include "hashcmd.h"
#include "pathexp.h"
#include "alias.h"
#include "jobs.h"
#include "version.h"
#include "builtins/getopt.h"
#include "builtins/common.h"
#include "builtins/builtext.h"
#include <tilde/tilde.h>
Data Structures
struct saved_dollar_vars
struct name_and_function
Macros
#define NEED_XTRACE_SET_DECL
#define VARIABLES_HASH_BUCKETS 1024 /* must be power of two */
#define FUNCTIONS_HASH_BUCKETS 512
#define TEMPENV_HASH_BUCKETS 4 /* must be power of two */
#define BASHFUNC_PREFIX "BASH_FUNC_"
#define BASHFUNC_PREFLEN 10 /* == strlen(BASHFUNC_PREFIX */
#define BASHFUNC_SUFFIX "%%"
#define BASHFUNC_SUFFLEN 2 /* == strlen(BASHFUNC_SUFFIX) */
#define FV_FORCETEMPENV 0x01
#define FV_SKIPINVISIBLE 0x02
#define FV_NODYNAMIC 0x04
#define INIT_DYNAMIC_VAR(var, val, gfunc, afunc)
#define INIT_DYNAMIC_ARRAY_VAR(var, gfunc, afunc)
#define INIT_DYNAMIC_ASSOC_VAR(var, gfunc, afunc)
#define FIND_OR_MAKE_VARIABLE(name, entry)
#define USE_EXPORTSTR (value == var->exportstr)
#define add_to_export_env(envstr, do_alloc)
#define SET_INT_VAR(name, intvar) intvar = find_variable (name) != 0
#define N_SPECIAL_VARS (sizeof (special_vars) / sizeof (special_vars[0]) - 1)
#define MIN_COMPAT_LEVEL 31
Functions
static void create_variable_tables PARAMS ((void))
static SHELL_VAR *null_assign PARAMS ((SHELL_VAR *, char *, arrayind_t, char *))
static SHELL_VAR *get_self PARAMS ((SHELL_VAR *))
static SHELL_VAR * set_int_value (SHELL_VAR *, intmax_t, int)
static SHELL_VAR * set_string_value (SHELL_VAR *, const char *, int)
static SHELL_VAR *bind_invalid_envvar PARAMS ((const char *, char *, int))
static int var_sametype PARAMS ((SHELL_VAR *, SHELL_VAR *))
static SHELL_VAR *hash_lookup PARAMS ((const char *, HASH_TABLE *))
static SHELL_VAR *new_shell_variable PARAMS ((const char *))
static SHELL_VAR *bind_variable_internal PARAMS ((const char *, char *, HASH_TABLE *, int, int))
static void free_variable_hash_data PARAMS ((PTR_T))
static VARLIST *vlist_alloc PARAMS ((int))
static VARLIST *vlist_realloc PARAMS ((VARLIST *, int))
static void vlist_add PARAMS ((VARLIST *, SHELL_VAR *, int))
static void flatten PARAMS ((HASH_TABLE *, sh_var_map_func_t *, VARLIST *, int))
static int qsort_var_comp PARAMS ((SHELL_VAR **, SHELL_VAR **))
static SHELL_VAR **vapply PARAMS ((sh_var_map_func_t *))
static SHELL_VAR *find_variable_internal PARAMS ((const char *, int))
static SHELL_VAR *find_nameref_at_context PARAMS ((SHELL_VAR *, VAR_CONTEXT *))
static SHELL_VAR *find_variable_nameref_context PARAMS ((SHELL_VAR *, VAR_CONTEXT *, VAR_CONTEXT **))
static SHELL_VAR *bind_tempenv_variable PARAMS ((const char *, char *))
static void dispose_temporary_env PARAMS ((sh_free_func_t *))
static char *mk_env_string PARAMS ((const char *, const char *, int))
static char **make_env_array_from_var_list PARAMS ((SHELL_VAR **))
static char **make_var_export_array PARAMS ((VAR_CONTEXT *))
static void add_temp_array_to_env PARAMS ((char **, int, int))
static void push_posix_tempvar_internal PARAMS ((SHELL_VAR *, int))
static void create_variable_tables ()
void initialize_shell_variables (char **env, int privmode)
static void set_machine_vars ()
char * sh_get_home_dir ()
static void set_home_var ()
static void set_shell_var ()
static char * get_bash_name ()
void adjust_shell_level (int change)
static void initialize_shell_level ()
void set_pwd ()
void set_ppid ()
static void uidset ()
void sh_set_lines_and_columns (int lines, int cols)
void print_var_list (SHELL_VAR **list)
void print_func_list (SHELL_VAR **list)
void print_assignment (SHELL_VAR *var)
void print_var_value (SHELL_VAR *var, int quote)
void print_var_function (SHELL_VAR *var)
static SHELL_VAR * null_assign (SHELL_VAR *self, char *value, arrayind_t unused, char *key)
static SHELL_VAR * get_self (SHELL_VAR *self)
static SHELL_VAR * assign_seconds (SHELL_VAR *self, char *value, arrayind_t unused, char *key)
static SHELL_VAR * get_seconds (SHELL_VAR *var)
static SHELL_VAR * init_seconds_var ()
static SHELL_VAR * assign_random (SHELL_VAR *self, char *value, arrayind_t unused, char *key)
int get_random_number ()
static SHELL_VAR * get_random (SHELL_VAR *var)
static SHELL_VAR * get_urandom (SHELL_VAR *var)
static SHELL_VAR * assign_lineno (SHELL_VAR *var, char *value, arrayind_t unused, char *key)
static SHELL_VAR * get_lineno (SHELL_VAR *var)
static SHELL_VAR * assign_subshell (SHELL_VAR *var, char *value, arrayind_t unused, char *key)
static SHELL_VAR * get_subshell (SHELL_VAR *var)
static SHELL_VAR * get_epochseconds (SHELL_VAR *var)
static SHELL_VAR * get_epochrealtime (SHELL_VAR *var)
static SHELL_VAR * get_bashpid (SHELL_VAR *var)
static SHELL_VAR * get_bash_argv0 (SHELL_VAR *var)
static SHELL_VAR * assign_bash_argv0 (SHELL_VAR *var, char *value, arrayind_t unused, char *key)
static void set_argv0 ()
static SHELL_VAR * get_bash_command (SHELL_VAR *var)
static SHELL_VAR * get_funcname (SHELL_VAR *self)
void make_funcname_visible (int on_or_off)
static SHELL_VAR * init_funcname_var ()
static void initialize_dynamic_variables ()
static SHELL_VAR * hash_lookup (char *name, HASH_TABLE *hashed_vars) const
SHELL_VAR * var_lookup (char *name, VAR_CONTEXT *vcontext) const
SHELL_VAR * find_variable_internal (char *name, int flags) const
SHELL_VAR * find_variable_nameref (SHELL_VAR *v)
SHELL_VAR * find_variable_last_nameref (char *name, int vflags) const
SHELL_VAR * find_global_variable_last_nameref (char *name, int vflags) const
static SHELL_VAR * find_nameref_at_context (SHELL_VAR *v, VAR_CONTEXT *vc)
static SHELL_VAR * find_variable_nameref_context (SHELL_VAR *v, VAR_CONTEXT *vc, VAR_CONTEXT **nvcp)
static SHELL_VAR * find_variable_last_nameref_context (SHELL_VAR *v, VAR_CONTEXT *vc, VAR_CONTEXT **nvcp)
SHELL_VAR * find_variable_nameref_for_create (char *name, int flags) const
SHELL_VAR * find_variable_nameref_for_assignment (char *name, int flags) const
char * nameref_transform_name (char *name, int flags)
SHELL_VAR * find_variable_tempenv (char *name) const
SHELL_VAR * find_variable_notempenv (char *name) const
SHELL_VAR * find_global_variable (char *name) const
SHELL_VAR * find_global_variable_noref (char *name) const
SHELL_VAR * find_shell_variable (char *name) const
SHELL_VAR * find_variable (char *name) const
SHELL_VAR * find_variable_no_invisible (char *name) const
SHELL_VAR * find_variable_for_assignment (char *name) const
SHELL_VAR * find_variable_noref (char *name) const
SHELL_VAR * find_function (char *name) const
FUNCTION_DEF * find_function_def (char *name) const
char * get_variable_value (SHELL_VAR *var)
char * get_string_value (char *var_name) const
char * sh_get_env_value (char *v) const
static int var_sametype (SHELL_VAR *v1, SHELL_VAR *v2)
int validate_inherited_value (SHELL_VAR *var, int type)
SHELL_VAR * set_if_not (char *name, char *value)
SHELL_VAR * make_local_variable (char *name, int flags) const
static SHELL_VAR * new_shell_variable (char *name) const
static SHELL_VAR * make_new_variable (char *name, HASH_TABLE *table) const
char * make_variable_value (SHELL_VAR *var, char *value, int flags)
static int can_optimize_assignment (SHELL_VAR *entry, char *value, int aflags)
static SHELL_VAR * optimized_assignment (SHELL_VAR *entry, char *value, int aflags)
static SHELL_VAR * bind_variable_internal (char *name, char *value, HASH_TABLE *table, int hflags, int aflags) const
SHELL_VAR * bind_variable (char *name, char *value, int flags) const
SHELL_VAR * bind_global_variable (char *name, char *value, int flags) const
static SHELL_VAR * bind_invalid_envvar (char *name, char *value, int flags) const
SHELL_VAR * bind_variable_value (SHELL_VAR *var, char *value, int aflags)
SHELL_VAR * bind_int_variable (char *lhs, char *rhs, int flags)
SHELL_VAR * bind_var_to_int (char *var, intmax_t val, int flags)
SHELL_VAR * bind_function (char *name, COMMAND *value) const
int assign_in_env (WORD_DESC *word, int flags)
static void dispose_variable_value (SHELL_VAR *var)
void dispose_variable (SHELL_VAR *var)
int unbind_variable (char *name) const
int unbind_nameref (char *name) const
int unbind_variable_noref (char *name) const
int unbind_global_variable (char *name) const
int unbind_global_variable_noref (char *name) const
int check_unbind_variable (char *name) const
int unbind_func (char *name) const
int delete_var (char *name, VAR_CONTEXT *vc) const
int makunbound (char *name, VAR_CONTEXT *vc) const
void kill_all_local_variables ()
static void free_variable_hash_data (PTR_T data)
void delete_all_variables (HASH_TABLE *hashed_vars)
void set_var_read_only (char *name)
static VARLIST * vlist_alloc (int nentries)
static VARLIST * vlist_realloc (VARLIST *vlist, int n)
static void vlist_add (VARLIST *vlist, SHELL_VAR *var, int flags)
SHELL_VAR ** map_over (sh_var_map_func_t *function, VAR_CONTEXT *vc)
SHELL_VAR ** map_over_funcs (sh_var_map_func_t *function)
static void flatten (HASH_TABLE *var_hash_table, sh_var_map_func_t *func, VARLIST *vlist, int flags)
void sort_variables (SHELL_VAR **array)
static int qsort_var_comp (SHELL_VAR **var1, SHELL_VAR **var2)
static SHELL_VAR ** vapply (sh_var_map_func_t *func)
static SHELL_VAR ** fapply (sh_var_map_func_t *func)
SHELL_VAR ** all_shell_variables ()
SHELL_VAR ** all_shell_functions ()
static int visible_var (SHELL_VAR *var)
SHELL_VAR ** all_visible_functions ()
SHELL_VAR ** all_visible_variables ()
static int visible_and_exported (SHELL_VAR *var)
static int export_environment_candidate (SHELL_VAR *var)
static int local_and_exported (SHELL_VAR *var)
SHELL_VAR ** all_exported_variables ()
SHELL_VAR ** local_exported_variables ()
static int variable_in_context (SHELL_VAR *var)
static int visible_variable_in_context (SHELL_VAR *var)
SHELL_VAR ** all_local_variables (int visible_only)
char ** all_variables_matching_prefix (char *prefix) const
static SHELL_VAR * bind_tempenv_variable (char *name, char *value) const
SHELL_VAR * find_tempenv_variable (char *name) const
static void push_posix_temp_var (PTR_T data)
static void push_temp_var (PTR_T data)
static void propagate_temp_var (PTR_T data)
static void dispose_temporary_env (sh_free_func_t *pushf)
void dispose_used_env_vars ()
void merge_temporary_env ()
void merge_function_temporary_env ()
void flush_temporary_env ()
static char * mk_env_string (char *name, char *value, int attributes) const
static char ** make_env_array_from_var_list (SHELL_VAR **vars)
static char ** make_var_export_array (VAR_CONTEXT *vcxt)
static char ** make_func_export_array ()
char ** add_or_supercede_exported_var (char *assign, int do_alloc)
static void add_temp_array_to_env (char **temp_array, int do_alloc, int do_supercede)
static int n_shell_variables ()
int chkexport (char *name)
void maybe_make_export_env ()
void update_export_env_inplace (char *env_prefix, int preflen, char *value)
void put_command_name_into_env (char *command_name)
VAR_CONTEXT * new_var_context (char *name, int flags)
void dispose_var_context (VAR_CONTEXT *vc)
static int set_context (SHELL_VAR *var)
VAR_CONTEXT * push_var_context (char *name, int flags, HASH_TABLE *tempvars)
static void push_posix_tempvar_internal (SHELL_VAR *var, int isbltin)
static void push_func_var (PTR_T data)
static void push_builtin_var (PTR_T data)
void pop_var_context ()
static void delete_local_contexts (VAR_CONTEXT *vcxt)
void delete_all_contexts (VAR_CONTEXT *vcxt)
void reset_local_contexts ()
VAR_CONTEXT * push_scope (int flags, HASH_TABLE *tmpvars)
static void push_exported_var (PTR_T data)
void pop_scope (int is_special)
static char ** save_dollar_vars ()
static void restore_dollar_vars (char **args)
static void free_dollar_vars ()
static void free_saved_dollar_vars (char **args)
void clear_dollar_vars ()
void push_context (char *name, int is_subshell, HASH_TABLE *tempvars)
void pop_context ()
void push_dollar_vars ()
void pop_dollar_vars ()
void dispose_saved_dollar_vars ()
void init_bash_argv ()
void save_bash_argv ()
void push_args (WORD_LIST *list)
void pop_args ()
static int sv_compare (struct name_and_function *sv1, struct name_and_function *sv2)
static int find_special_var (char *name) const
void stupidly_hack_special_variables (char *name)
void reinit_special_variables ()
void sv_ifs (char *name)
void sv_path (char *name)
void sv_mail (char *name)
void sv_funcnest (char *name)
void sv_execignore (char *name)
void sv_globignore (char *name)
void sv_ignoreeof (char *name)
void sv_optind (char *name)
void sv_opterr (char *name)
void sv_strict_posix (char *name)
void sv_locale (char *name)
void set_pipestatus_from_exit (int s)
void sv_xtracefd (char *name)
void sv_shcompat (char *name)
Variables
char ** environ
time_t shell_start_time
struct timeval shellstart
VAR_CONTEXT * global_variables = (VAR_CONTEXT *)NULL
VAR_CONTEXT * shell_variables = (VAR_CONTEXT *)NULL
HASH_TABLE * shell_functions = (HASH_TABLE *)NULL
HASH_TABLE * invalid_env = (HASH_TABLE *)NULL
int variable_context = 0
int localvar_inherit = 0
int localvar_unset = 0
HASH_TABLE * temporary_env = (HASH_TABLE *)NULL
int tempenv_assign_error
char * dollar_vars [10]
WORD_LIST * rest_of_args = (WORD_LIST *)NULL
int posparam_count = 0
pid_t dollar_dollar_pid
int array_needs_making = 1
int shell_level = 0
char ** export_env = (char **)NULL
static int export_env_index
static int export_env_size
SHELL_VAR nameref_invalid_value
static SHELL_VAR nameref_maxloop_value
static HASH_TABLE * last_table_searched
static VAR_CONTEXT * last_context_searched
static intmax_t seconds_value_assigned
int last_random_value
static int seeded_subshell = 0
static char * static_shell_name = 0
char ** tempvar_list
int tvlist_ind
static struct saved_dollar_vars * dollar_arg_stack = (struct saved_dollar_vars *)NULL
static int dollar_arg_stack_slots
static int dollar_arg_stack_index
static struct name_and_function special_vars []
Data Structure Documentation
saved_dollar_vars
struct saved_dollar_vars
Definition at line 5558 of file variables.c.
Data Fields
int count
char ** first_ten
WORD_LIST * rest
name_and_function
struct name_and_function
Definition at line 5800 of file variables.c.
Data Fields
sh_sv_func_t * function
char * name
Macro Definition Documentation
add_to_export_env
#define add_to_export_env (envstr, do_alloc)
Value:
do \
  { \
    if (export_env_index >= (export_env_size - 1)) \
      { \
    export_env_size += 16; \
    export_env = strvec_resize (export_env, export_env_size); \
    environ = export_env; \
      } \
    export_env[export_env_index++] = (do_alloc) ? savestring (envstr) : envstr; \
    export_env[export_env_index] = (char *)NULL; \
  } while (0)
Definition at line 4997 of file variables.c.
BASHFUNC_PREFIX
#define BASHFUNC_PREFIX "BASH_FUNC_"
Definition at line 88 of file variables.c.
BASHFUNC_PREFLEN
#define BASHFUNC_PREFLEN 10 /* == strlen(BASHFUNC_PREFIX */
Definition at line 89 of file variables.c.
BASHFUNC_SUFFIX
#define BASHFUNC_SUFFIX "%%"
Definition at line 90 of file variables.c.
BASHFUNC_SUFFLEN
#define BASHFUNC_SUFFLEN 2 /* == strlen(BASHFUNC_SUFFIX) */
Definition at line 91 of file variables.c.
FIND_OR_MAKE_VARIABLE
#define FIND_OR_MAKE_VARIABLE (name, entry)
Value:
  do \
    { \
      entry = find_variable (name); \
      if (!entry) \
    { \
      entry = bind_variable (name, "", 0); \
      if (entry) entry->attributes |= att_invisible; \
    } \
    } \
  while (0)
Definition at line 4096 of file variables.c.
FUNCTIONS_HASH_BUCKETS
#define FUNCTIONS_HASH_BUCKETS 512
Definition at line 85 of file variables.c.
FV_FORCETEMPENV
#define FV_FORCETEMPENV 0x01
Definition at line 107 of file variables.c.
FV_NODYNAMIC
#define FV_NODYNAMIC 0x04
Definition at line 109 of file variables.c.
FV_SKIPINVISIBLE
#define FV_SKIPINVISIBLE 0x02
Definition at line 108 of file variables.c.
INIT_DYNAMIC_ARRAY_VAR
#define INIT_DYNAMIC_ARRAY_VAR (var, gfunc, afunc)
Value:
  do \
    { \
      v = make_new_array_variable (var); \
      v->dynamic_value = gfunc; \
      v->assign_func = afunc; \
    } \
  while (0)
Definition at line 1221 of file variables.c.
INIT_DYNAMIC_ASSOC_VAR
#define INIT_DYNAMIC_ASSOC_VAR (var, gfunc, afunc)
Value:
  do \
    { \
      v = make_new_assoc_variable (var); \
      v->dynamic_value = gfunc; \
      v->assign_func = afunc; \
    } \
  while (0)
Definition at line 1230 of file variables.c.
INIT_DYNAMIC_VAR
#define INIT_DYNAMIC_VAR (var, val, gfunc, afunc)
Value:
  do \
    { \
      v = bind_variable (var, (val), 0); \
      v->dynamic_value = gfunc; \
      v->assign_func = afunc; \
    } \
  while (0)
Definition at line 1212 of file variables.c.
MIN_COMPAT_LEVEL
#define MIN_COMPAT_LEVEL 31
Definition at line 6524 of file variables.c.
N_SPECIAL_VARS
#define N_SPECIAL_VARS (sizeof (special_vars) / sizeof (special_vars[0]) - 1)
Definition at line 5889 of file variables.c.
NEED_XTRACE_SET_DECL
#define NEED_XTRACE_SET_DECL
Definition at line 48 of file variables.c.
SET_INT_VAR
#define SET_INT_VAR (name, intvar) intvar = find_variable (name) != 0
Definition at line 5797 of file variables.c.
TEMPENV_HASH_BUCKETS
#define TEMPENV_HASH_BUCKETS 4 /* must be power of two */
Definition at line 86 of file variables.c.
USE_EXPORTSTR
#define USE_EXPORTSTR (value == var->exportstr)
Definition at line 4883 of file variables.c.
VARIABLES_HASH_BUCKETS
#define VARIABLES_HASH_BUCKETS 1024 /* must be power of two */
Definition at line 84 of file variables.c.
Function Documentation
add_or_supercede_exported_var()
char** add_or_supercede_exported_var (char * assign, int do_alloc)
Definition at line 5013 of file variables.c.
 {
   register int i;
   int equal_offset;
   equal_offset = assignment (assign, 0);
   if (equal_offset == 0)
     return (export_env);
   /* If this is a function, then only supersede the function definition.
      We do this by including the `=() {' in the comparison, like
      initialize_shell_variables does. */
   if (assign[equal_offset + 1] == '(' &&
      strncmp (assign + equal_offset + 2, ") {", 3) == 0)        /* } */
     equal_offset += 4;
   for (i = 0; i < export_env_index; i++)
     {
       if (STREQN (assign, export_env[i], equal_offset + 1))
     {
       free (export_env[i]);
       export_env[i] = do_alloc ? savestring (assign) : assign;
       return (export_env);
     }
     }
   add_to_export_env (assign, do_alloc);
   return (export_env);
 }
References add_to_export_env, assignment(), export_env, export_env_index, free, i, savestring(), STREQN, and strncmp().
Referenced by add_temp_array_to_env(), and update_export_env_inplace().
add_temp_array_to_env()
static void add_temp_array_to_env (char ** temp_array, int do_alloc, int do_supercede) static
Definition at line 5045 of file variables.c.
 {
   register int i;
   if (temp_array == 0)
     return;
   for (i = 0; temp_array[i]; i++)
     {
       if (do_supercede)
     export_env = add_or_supercede_exported_var (temp_array[i], do_alloc);
       else
     add_to_export_env (temp_array[i], do_alloc);
     }
   free (temp_array);
 }
References add_or_supercede_exported_var(), add_to_export_env, export_env, free, and i.
Referenced by maybe_make_export_env().
adjust_shell_level()
void adjust_shell_level (int change)
Definition at line 851 of file variables.c.
 {
   char new_level[5], *old_SHLVL;
   intmax_t old_level;
   SHELL_VAR *temp_var;
   old_SHLVL = get_string_value ("SHLVL");
   if (old_SHLVL == 0 || *old_SHLVL == '\0' || legal_number (old_SHLVL, &old_level) == 0)
     old_level = 0;
   shell_level = old_level + change;
   if (shell_level < 0)
     shell_level = 0;
   else if (shell_level >= 1000)
     {
       internal_warning (_("shell level (%d) too high, resetting to 1"), shell_level);
       shell_level = 1;
     }
   /* We don't need the full generality of itos here. */
   if (shell_level < 10)
     {
       new_level[0] = shell_level + '0';
       new_level[1] = '\0';
     }
   else if (shell_level < 100)
     {
       new_level[0] = (shell_level / 10) + '0';
       new_level[1] = (shell_level % 10) + '0';
       new_level[2] = '\0';
     }
   else if (shell_level < 1000)
     {
       new_level[0] = (shell_level / 100) + '0';
       old_level = shell_level % 100;
       new_level[1] = (old_level / 10) + '0';
       new_level[2] = (old_level % 10) + '0';
       new_level[3] = '\0';
     }
   temp_var = bind_variable ("SHLVL", new_level, 0);
   set_auto_export (temp_var);
 }
References _, bind_variable(), get_string_value(), internal_warning(), legal_number(), set_auto_export, and shell_level.
Referenced by execute_disk_command(), initialize_shell_level(), and push_builtin().
all_exported_variables()
SHELL_VAR** all_exported_variables ()
Definition at line 4407 of file variables.c.
 {
   return (vapply (visible_and_exported));
 }
References vapply(), and visible_and_exported().
all_local_variables()
SHELL_VAR** all_local_variables (int visible_only)
Definition at line 4433 of file variables.c.
 {
   VARLIST *vlist;
   SHELL_VAR **ret;
   VAR_CONTEXT *vc;
   vc = shell_variables;
   for (vc = shell_variables; vc; vc = vc->down)
     if (vc_isfuncenv (vc) && vc->scope == variable_context)
       break;
   if (vc == 0)
     {
       internal_error (_("all_local_variables: no function context at current scope"));
       return (SHELL_VAR **)NULL;
     }
   if (vc->table == 0 || HASH_ENTRIES (vc->table) == 0 || vc_haslocals (vc) == 0)
     return (SHELL_VAR **)NULL;
   vlist = vlist_alloc (HASH_ENTRIES (vc->table));
   if (visible_only)
     flatten (vc->table, visible_variable_in_context, vlist, 0);
   else
     flatten (vc->table, variable_in_context, vlist, 0);
   ret = vlist->list;
   free (vlist);
   if (ret)
     sort_variables (ret);
   return ret;
 }
References _, var_context::down, flatten(), free, HASH_ENTRIES, internal_error(), _vlist::list, NULL, var_context::scope, shell_variables, sort_variables(), var_context::table, variable_context, variable_in_context(), vc_haslocals, vc_isfuncenv, visible_variable_in_context(), and vlist_alloc().
all_shell_functions()
SHELL_VAR** all_shell_functions ()
Definition at line 4354 of file variables.c.
 {
   return (fapply ((sh_var_map_func_t *)NULL));
 }
References fapply(), and NULL.
all_shell_variables()
SHELL_VAR** all_shell_variables ()
Definition at line 4347 of file variables.c.
 {
   return (vapply ((sh_var_map_func_t *)NULL));
 }
References NULL, and vapply().
all_variables_matching_prefix()
char** all_variables_matching_prefix (char * prefix) const
Definition at line 4484 of file variables.c.
 {
   SHELL_VAR **varlist;
   char **rlist;
   int vind, rind, plen;
   plen = STRLEN (prefix);
   varlist = all_visible_variables ();
   for (vind = 0; varlist && varlist[vind]; vind++)
     ;
   if (varlist == 0 || vind == 0)
     return ((char **)NULL);
   rlist = strvec_create (vind + 1);
   for (vind = rind = 0; varlist[vind]; vind++)
     {
       if (plen == 0 || STREQN (prefix, varlist[vind]->name, plen))
     rlist[rind++] = savestring (varlist[vind]->name);
     }
   rlist[rind] = (char *)0;
   free (varlist);
   return rlist;
 }
References all_visible_variables(), free, NULL, prefix(), savestring(), STREQN, STRLEN, and strvec_create().
Referenced by parameter_brace_expand().
all_visible_functions()
SHELL_VAR** all_visible_functions ()
Definition at line 4367 of file variables.c.
 {
   return (fapply (visible_var));
 }
References fapply(), and visible_var().
all_visible_variables()
SHELL_VAR** all_visible_variables ()
Definition at line 4373 of file variables.c.
 {
   return (vapply (visible_var));
 }
References vapply(), and visible_var().
Referenced by all_variables_matching_prefix().
assign_bash_argv0()
static SHELL_VAR* assign_bash_argv0 (SHELL_VAR * var, char * value, arrayind_t unused, char * key) static
Definition at line 1555 of file variables.c.
 {
   size_t vlen;
   if (value == 0)
     return var;
   FREE (dollar_vars[0]);
   dollar_vars[0] = savestring (value);
   /* Need these gyrations because shell_name isn't dynamically allocated */
   vlen = STRLEN (value);
   static_shell_name = xrealloc (static_shell_name, vlen + 1);
   strcpy (static_shell_name, value);
   shell_name = static_shell_name;
   return var;
 }
References dollar_vars, FREE, savestring(), shell_name, static_shell_name, strcpy, STRLEN, value, and xrealloc.
Referenced by initialize_dynamic_variables(), and set_argv0().
assign_in_env()
int assign_in_env (WORD_DESC * word, int flags)
Definition at line 3592 of file variables.c.
 {
   int offset, aflags;
   char *name, *temp, *value, *newname;
   SHELL_VAR *var;
   const char *string;
   string = word->word;
   aflags = 0;
   offset = assignment (string, 0);
   newname = name = savestring (string);
   value = (char *)NULL;
   if (name[offset] == '=')
     {
       name[offset] = 0;
       /* don't ignore the `+' when assigning temporary environment */
       if (name[offset - 1] == '+')
     {
       name[offset - 1] = '\0';
       aflags |= ASS_APPEND;
     }
       if (legal_identifier (name) == 0)
     {
       sh_invalidid (name);
       free (name);
       return (0);
     }
       var = find_variable (name);
       if (var == 0)
     {
       var = find_variable_last_nameref (name, 1);
       /* If we're assigning a value to a nameref variable in the temp
          environment, and the value of the nameref is valid for assignment,
          but the variable does not already exist, assign to the nameref
          target and add the target to the temporary environment.  This is
          what ksh93 does */
       /* We use 2 in the call to valid_nameref_value because we don't want
          to allow array references here at all (newname will be used to
          create a variable directly below) */
       if (var && nameref_p (var) && valid_nameref_value (nameref_cell (var), 2))
         {
           newname = nameref_cell (var);
           var = 0;      /* don't use it for append */
         }
     }
       else
         newname = name_cell (var);  /* no-op if not nameref */
       if (var && (readonly_p (var) || noassign_p (var)))
     {
       if (readonly_p (var))
         err_readonly (name);
       free (name);
       return (0);
     }
       temp = name + offset + 1;
       value = expand_assignment_string_to_string (temp, 0);
       if (var && (aflags & ASS_APPEND))
     {
       if (value == 0)
         {
           value = (char *)xmalloc (1);  /* like do_assignment_internal */
           value[0] = '\0';
         }
       temp = make_variable_value (var, value, aflags);
       FREE (value);
       value = temp;
     }
     }
   if (temporary_env == 0)
     temporary_env = hash_create (TEMPENV_HASH_BUCKETS);
   var = hash_lookup (newname, temporary_env);
   if (var == 0)
     var = make_new_variable (newname, temporary_env);
   else
     FREE (value_cell (var));
   if (value == 0)
     {
       value = (char *)xmalloc (1);  /* see above */
       value[0] = '\0';
     }
   var_setvalue (var, value);
   var->attributes |= (att_exported|att_tempvar);
   var->context = variable_context;  /* XXX */
   INVALIDATE_EXPORTSTR (var);
   var->exportstr = mk_env_string (newname, value, 0);
   array_needs_making = 1;
   if (flags)
     {
       if (STREQ (newname, "POSIXLY_CORRECT") || STREQ (newname, "POSIX_PEDANDTIC"))
     save_posix_options ();      /* XXX one level of saving right now */
       stupidly_hack_special_variables (newname);
     }
   if (echo_command_at_execute)
     /* The Korn shell prints the `+ ' in front of assignment statements,
     so we do too. */
     xtrace_print_assignment (name, value, 0, 1);
   free (name);
   return 1;
 }
References array_needs_making, ASS_APPEND, assignment(), att_exported, att_tempvar, echo_command_at_execute, err_readonly(), expand_assignment_string_to_string(), find_variable(), find_variable_last_nameref(), flags, FREE, free, hash_create(), hash_lookup(), INVALIDATE_EXPORTSTR, legal_identifier(), make_new_variable(), make_variable_value(), mk_env_string(), name_cell, nameref_cell, nameref_p, noassign_p, NULL, offset, readonly_p, save_posix_options(), savestring(), sh_invalidid(), STREQ, string, stupidly_hack_special_variables(), TEMPENV_HASH_BUCKETS, temporary_env, valid_nameref_value(), value, value_cell, var_setvalue, variable_context, word_desc::word, xmalloc, and xtrace_print_assignment().
Referenced by do_assignment_statements().
assign_lineno()
static SHELL_VAR* assign_lineno (SHELL_VAR * var, char * value, arrayind_t unused, char * key) static
Definition at line 1463 of file variables.c.
 {
   intmax_t new_value;
   if (value == 0 || *value == '\0' || legal_number (value, &new_value) == 0)
     new_value = 0;
   line_number = line_number_base = new_value;
   return (set_int_value (var, line_number, integer_p (var) != 0));
 }
References integer_p, legal_number(), line_number, line_number_base, set_int_value(), and value.
Referenced by initialize_dynamic_variables().
assign_random()
static SHELL_VAR* assign_random (SHELL_VAR * self, char * value, arrayind_t unused, char * key) static
Definition at line 1401 of file variables.c.
 {
   intmax_t seedval;
   int expok;
   if (integer_p (self))
     seedval = evalexp (value, 0, &expok);
   else
     expok = legal_number (value, &seedval);
   if (expok == 0)
     return (self);
   sbrand (seedval);
   if (subshell_environment)
     seeded_subshell = getpid ();
   return (set_int_value (self, seedval, integer_p (self) != 0));
 }
References evalexp(), getpid(), integer_p, legal_number(), sbrand(), seeded_subshell, set_int_value(), subshell_environment, and value.
Referenced by initialize_dynamic_variables().
assign_seconds()
static SHELL_VAR* assign_seconds (SHELL_VAR * self, char * value, arrayind_t unused, char * key) static
Definition at line 1349 of file variables.c.
 {
   intmax_t nval;
   int expok;
   if (integer_p (self))
     nval = evalexp (value, 0, &expok);
   else
     expok = legal_number (value, &nval);
   seconds_value_assigned = expok ? nval : 0;
   gettimeofday (&shellstart, NULL);
   shell_start_time = shellstart.tv_sec;
   return (set_int_value (self, nval, integer_p (self) != 0));
 }
References evalexp(), gettimeofday(), integer_p, legal_number(), NULL, seconds_value_assigned, set_int_value(), shell_start_time, shellstart, timeval::tv_sec, and value.
Referenced by init_seconds_var().
assign_subshell()
static SHELL_VAR* assign_subshell (SHELL_VAR * var, char * value, arrayind_t unused, char * key) static
Definition at line 1489 of file variables.c.
 {
   intmax_t new_value;
   if (value == 0 || *value == '\0' || legal_number (value, &new_value) == 0)
     new_value = 0;
   subshell_level = new_value;
   return var;
 }
References legal_number(), subshell_level, and value.
Referenced by initialize_dynamic_variables().
bind_function()
SHELL_VAR* bind_function (char * name, COMMAND * value) const
Definition at line 3508 of file variables.c.
 {
   SHELL_VAR *entry;
   entry = find_function (name);
   if (entry == 0)
     {
       BUCKET_CONTENTS *elt;
       elt = hash_insert (savestring (name), shell_functions, HASH_NOSRCH);
       entry = new_shell_variable (name);
       elt->data = (PTR_T)entry;
     }
   else
     INVALIDATE_EXPORTSTR (entry);
   if (var_isset (entry))
     dispose_command (function_cell (entry));
   if (value)
     var_setfunc (entry, copy_command (value));
   else
     var_setfunc (entry, 0);
   VSETATTR (entry, att_function);
   if (mark_modified_vars)
     VSETATTR (entry, att_exported);
   VUNSETATTR (entry, att_invisible);        /* Just to be sure */
   if (exported_p (entry))
     array_needs_making = 1;
 #if defined (PROGRAMMABLE_COMPLETION)
   set_itemlist_dirty (&it_functions);
 #endif
   return (entry);
 }
References array_needs_making, att_exported, att_function, att_invisible, copy_command(), bucket_contents::data, dispose_command(), exported_p, find_function(), function_cell, hash_insert(), HASH_NOSRCH, INVALIDATE_EXPORTSTR, it_functions, mark_modified_vars, new_shell_variable(), PTR_T, savestring(), shell_functions, value, var_isset, var_setfunc, VSETATTR, and VUNSETATTR.
Referenced by execute_intern_function().
bind_global_variable()
SHELL_VAR* bind_global_variable (char * name, char * value, int flags) const
Definition at line 3330 of file variables.c.
 {
   if (shell_variables == 0)
     create_variable_tables ();
   /* bind_variable_internal will handle nameref resolution in this case */
   return (bind_variable_internal (name, value, global_variables->table, 0, flags));
 }
References bind_variable_internal(), create_variable_tables(), flags, global_variables, shell_variables, var_context::table, and value.
Referenced by bind_variable().
bind_int_variable()
SHELL_VAR* bind_int_variable (char * lhs, char * rhs, int flags)
Definition at line 3428 of file variables.c.
 {
   register SHELL_VAR *v;
   int isint, isarr, implicitarray, vflags, avflags;
   isint = isarr = implicitarray = 0;
 #if defined (ARRAY_VARS)
   /* Don't rely on VA_NOEXPAND being 1, set it explicitly */
   vflags = (flags & ASS_NOEXPAND) ? VA_NOEXPAND : 0;
   if (flags & ASS_ONEWORD)
     vflags |= VA_ONEWORD;
   if (valid_array_reference (lhs, vflags))
     {
       isarr = 1;
       avflags = 0;
       /* Common code to translate between assignment and reference flags. */
       if (flags & ASS_NOEXPAND)
     avflags |= AV_NOEXPAND;
       if (flags & ASS_ONEWORD)
     avflags |= AV_ONEWORD;
       v = array_variable_part (lhs, avflags, (char **)0, (int *)0);
     }
   else if (legal_identifier (lhs) == 0)
     {
       sh_invalidid (lhs);
       return ((SHELL_VAR *)NULL);
     }
   else
 #endif
     v = find_variable (lhs);
   if (v)
     {
       isint = integer_p (v);
       VUNSETATTR (v, att_integer);
 #if defined (ARRAY_VARS)
       if (array_p (v) && isarr == 0)
     implicitarray = 1;
 #endif
     }
 #if defined (ARRAY_VARS)
   if (isarr)
     v = assign_array_element (lhs, rhs, flags, (array_eltstate_t *)0);
   else if (implicitarray)
     v = bind_array_variable (lhs, 0, rhs, 0);   /* XXX - check on flags */
   else
 #endif
     v = bind_variable (lhs, rhs, 0);    /* why not use bind_variable_value? */
   if (v)
     {
       if (isint)
     VSETATTR (v, att_integer);
       VUNSETATTR (v, att_invisible);
     }
   if (v && nameref_p (v))
     internal_warning (_("%s: assigning integer to name reference"), lhs);
   return (v);
 }
References _, array_p, ASS_NOEXPAND, ASS_ONEWORD, att_integer, att_invisible, AV_NOEXPAND, AV_ONEWORD, bind_variable(), find_variable(), flags, integer_p, internal_warning(), legal_identifier(), nameref_p, NULL, sh_invalidid(), VA_NOEXPAND, VA_ONEWORD, VSETATTR, and VUNSETATTR.
Referenced by bind_var_to_int(), and expr_bind_variable().
bind_invalid_envvar()
static SHELL_VAR* bind_invalid_envvar (char * name, char * value, int flags) const static
Definition at line 3343 of file variables.c.
 {
   if (invalid_env == 0)
     invalid_env = hash_create (64); /* XXX */
   return (bind_variable_internal (name, value, invalid_env, HASH_NOSRCH, flags));
 }
References bind_variable_internal(), flags, hash_create(), HASH_NOSRCH, invalid_env, and value.
Referenced by initialize_shell_variables().
bind_tempenv_variable()
static SHELL_VAR* bind_tempenv_variable (char * name, char * value) const static
Definition at line 4517 of file variables.c.
 {
   SHELL_VAR *var;
   var = temporary_env ? hash_lookup (name, temporary_env) : (SHELL_VAR *)NULL;
   if (var)
     {
       FREE (value_cell (var));
       var_setvalue (var, savestring (value));
       INVALIDATE_EXPORTSTR (var);
     }
   return (var);
 }
References FREE, hash_lookup(), INVALIDATE_EXPORTSTR, NULL, savestring(), temporary_env, value, value_cell, and var_setvalue.
Referenced by bind_variable().
bind_var_to_int()
SHELL_VAR* bind_var_to_int (char * var, intmax_t val, int flags)
Definition at line 3494 of file variables.c.
 {
   char ibuf[INT_STRLEN_BOUND (intmax_t) + 1], *p;
   p = fmtulong (val, 10, ibuf, sizeof (ibuf), 0);
   return (bind_int_variable (var, p, flags));
 }
References bind_int_variable(), flags, fmtulong(), INT_STRLEN_BOUND, p, and val.
Referenced by builtin_bind_var_to_int(), and redir_varassign().
bind_variable()
SHELL_VAR* bind_variable (char * name, char * value, int flags) const
Definition at line 3256 of file variables.c.
 {
   SHELL_VAR *v, *nv;
   VAR_CONTEXT *vc, *nvc;
   if (shell_variables == 0)
     create_variable_tables ();
   /* If we have a temporary environment, look there first for the variable,
      and, if found, modify the value there before modifying it in the
      shell_variables table.  This allows sourced scripts to modify values
      given to them in a temporary environment while modifying the variable
      value that the caller sees. */
   if (temporary_env && value)       /* XXX - can value be null here? */
     bind_tempenv_variable (name, value);
   /* XXX -- handle local variables here. */
   for (vc = shell_variables; vc; vc = vc->down)
     {
       if (vc_isfuncenv (vc) || vc_isbltnenv (vc))
     {
       v = hash_lookup (name, vc->table);
       nvc = vc;
       if (v && nameref_p (v))
         {
           /* This starts at the context where we found the nameref. If we
          want to start the name resolution over again at the original
          context, this is where we need to change it */
           nv = find_variable_nameref_context (v, vc, &nvc);
           if (nv == 0)
         {
           nv = find_variable_last_nameref_context (v, vc, &nvc);
           if (nv && nameref_p (nv))
             {
               /* If this nameref variable doesn't have a value yet,
              set the value.  Otherwise, assign using the value as
              normal. */
               if (nameref_cell (nv) == 0)
             return (bind_variable_internal (nv->name, value, nvc->table, 0, flags));
 #if defined (ARRAY_VARS)
               else if (valid_array_reference (nameref_cell (nv), 0))
             return (assign_array_element (nameref_cell (nv), value, flags, (array_eltstate_t *)0));
               else
 #endif
               return (bind_variable_internal (nameref_cell (nv), value, nvc->table, 0, flags));
             }
           else if (nv == &nameref_maxloop_value)
             {
               internal_warning (_("%s: circular name reference"), v->name);
               return (bind_global_variable (v->name, value, flags));
             }
           else
             v = nv;
         }
           else if (nv == &nameref_maxloop_value)
         {
           internal_warning (_("%s: circular name reference"), v->name);
           return (bind_global_variable (v->name, value, flags));
         }
           else
             v = nv;
         }
       if (v)
         return (bind_variable_internal (v->name, value, nvc->table, 0, flags));
     }
     }
   /* bind_variable_internal will handle nameref resolution in this case */
   return (bind_variable_internal (name, value, global_variables->table, 0, flags));
 }
References _, bind_global_variable(), bind_tempenv_variable(), bind_variable_internal(), create_variable_tables(), var_context::down, find_variable_last_nameref_context(), find_variable_nameref_context(), flags, global_variables, hash_lookup(), internal_warning(), variable::name, nameref_cell, nameref_maxloop_value, nameref_p, shell_variables, var_context::table, temporary_env, value, vc_isbltnenv, and vc_isfuncenv.
Referenced by adjust_shell_level(), bind_int_variable(), bind_lastarg(), builtin_bind_variable(), check_mail(), do_assignment_internal(), execute_for_command(), execute_variable_command(), initialize_shell_variables(), main(), parameter_brace_expand_rhs(), push_posix_temp_var(), push_posix_tempvar_internal(), set_home_var(), set_ppid(), set_pwd(), set_shell_var(), sh_set_lines_and_columns(), and uidset().
bind_variable_internal()
static SHELL_VAR* bind_variable_internal (char * name, char * value, HASH_TABLE * table, int hflags, int aflags) const static
Definition at line 3081 of file variables.c.
 {
   char *newval, *tname;
   SHELL_VAR *entry, *tentry;
   entry = (hflags & HASH_NOSRCH) ? (SHELL_VAR *)NULL : hash_lookup (name, table);
   /* Follow the nameref chain here if this is the global variables table */
   if (entry && nameref_p (entry) && (invisible_p (entry) == 0) && table == global_variables->table)
     {
       entry = find_global_variable (entry->name);
       /* Let's see if we have a nameref referencing a variable that hasn't yet
      been created. */
       if (entry == 0)
     entry = find_variable_last_nameref (name, 0);   /* XXX */
       if (entry == 0)                   /* just in case */
         return (entry);
     }
   /* The first clause handles `declare -n ref; ref=x;' or `declare -n ref;
      declare -n ref' */
   if (entry && invisible_p (entry) && nameref_p (entry))
     {
       if ((aflags & ASS_FORCE) == 0 && value && valid_nameref_value (value, 0) == 0)
     {
       sh_invalidid (value);
       return ((SHELL_VAR *)NULL);
     }
       goto assign_value;
     }
   else if (entry && nameref_p (entry))
     {
       newval = nameref_cell (entry);    /* XXX - newval can't be NULL here */
       if (valid_nameref_value (newval, 0) == 0)
     {
       sh_invalidid (newval);
       return ((SHELL_VAR *)NULL);
     }
 #if defined (ARRAY_VARS)
       /* declare -n foo=x[2] ; foo=bar */
       if (valid_array_reference (newval, 0))
     {
       tname = array_variable_name (newval, 0, (char **)0, (int *)0);
       if (tname && (tentry = find_variable_noref (tname)) && nameref_p (tentry))
         {
           /* nameref variables can't be arrays */
           internal_warning (_("%s: removing nameref attribute"), name_cell (tentry));
           FREE (value_cell (tentry));       /* XXX - bash-4.3 compat */
           var_setvalue (tentry, (char *)NULL);
           VUNSETATTR (tentry, att_nameref);
         }
       free (tname);
       /* entry == nameref variable; tentry == array variable;
          newval == x[2]; value = bar
          We don't need to call make_variable_value here, since
          assign_array_element will eventually do it itself based on
          newval and aflags. */
       entry = assign_array_element (newval, value, aflags|ASS_NAMEREF, (array_eltstate_t *)0);
       if (entry == 0)
         return entry;
     }
       else
 #endif
     {
       entry = make_new_variable (newval, table);
       var_setvalue (entry, make_variable_value (entry, value, aflags));
     }
     }
   else if (entry == 0)
     {
       entry = make_new_variable (name, table);
       var_setvalue (entry, make_variable_value (entry, value, aflags)); /* XXX */
     }
   else if (entry->assign_func)  /* array vars have assign functions now */
     {
       if ((readonly_p (entry) && (aflags & ASS_FORCE) == 0) || noassign_p (entry))
     {
       if (readonly_p (entry))
         err_readonly (name_cell (entry));
       return (entry);
     }
       INVALIDATE_EXPORTSTR (entry);
       newval = (aflags & ASS_APPEND) ? make_variable_value (entry, value, aflags) : value;
       if (assoc_p (entry))
     entry = (*(entry->assign_func)) (entry, newval, -1, savestring ("0"));
       else if (array_p (entry))
     entry = (*(entry->assign_func)) (entry, newval, 0, 0);
       else
     entry = (*(entry->assign_func)) (entry, newval, -1, 0);
       if (newval != value)
     free (newval);
       return (entry);
     }
   else
     {
 assign_value:
       if ((readonly_p (entry) && (aflags & ASS_FORCE) == 0) || noassign_p (entry))
     {
       if (readonly_p (entry))
         err_readonly (name_cell (entry));
       return (entry);
     }
       /* Variables which are bound are visible. */
       VUNSETATTR (entry, att_invisible);
       /* If we can optimize the assignment, do so and return.  Right now, we
      optimize appends to string variables. */
       if (can_optimize_assignment (entry, value, aflags))
     {
       INVALIDATE_EXPORTSTR (entry);
       optimized_assignment (entry, value, aflags);
       if (mark_modified_vars)
         VSETATTR (entry, att_exported);
       if (exported_p (entry))
         array_needs_making = 1;
       return (entry);
     }
 #if defined (ARRAY_VARS)
       if (assoc_p (entry) || array_p (entry))
         newval = make_array_variable_value (entry, 0, "0", value, aflags);
       else
 #endif
       newval = make_variable_value (entry, value, aflags);  /* XXX */
       /* Invalidate any cached export string */
       INVALIDATE_EXPORTSTR (entry);
 #if defined (ARRAY_VARS)
       /* XXX -- this bears looking at again -- XXX */
       /* If an existing array variable x is being assigned to with x=b or
      `read x' or something of that nature, silently convert it to
      x[0]=b or `read x[0]'. */
       if (assoc_p (entry))
     {
       assoc_insert (assoc_cell (entry), savestring ("0"), newval);
       free (newval);
     }
       else if (array_p (entry))
     {
       array_insert (array_cell (entry), 0, newval);
       free (newval);
     }
       else
 #endif
     {
       FREE (value_cell (entry));
       var_setvalue (entry, newval);
     }
     }
   if (mark_modified_vars)
     VSETATTR (entry, att_exported);
   if (exported_p (entry))
     array_needs_making = 1;
   return (entry);
 }
References _, array_cell, array_needs_making, array_p, ASS_APPEND, ASS_FORCE, ASS_NAMEREF, assoc_cell, assoc_p, att_exported, att_invisible, att_nameref, can_optimize_assignment(), err_readonly(), exported_p, find_global_variable(), find_variable_last_nameref(), find_variable_noref(), FREE, free, global_variables, hash_lookup(), HASH_NOSRCH, internal_warning(), INVALIDATE_EXPORTSTR, invisible_p, make_new_variable(), make_variable_value(), mark_modified_vars, name_cell, nameref_cell, nameref_p, noassign_p, NULL, optimized_assignment(), readonly_p, savestring(), sh_invalidid(), var_context::table, table, valid_nameref_value(), value, value_cell, var_setvalue, VSETATTR, and VUNSETATTR.
Referenced by bind_global_variable(), bind_invalid_envvar(), bind_variable(), push_exported_var(), push_posix_tempvar_internal(), push_temp_var(), and set_if_not().
bind_variable_value()
SHELL_VAR* bind_variable_value (SHELL_VAR * var, char * value, int aflags)
Definition at line 3359 of file variables.c.
 {
   char *t;
   int invis;
   invis = invisible_p (var);
   VUNSETATTR (var, att_invisible);
   if (var->assign_func)
     {
       /* If we're appending, we need the old value, so use
      make_variable_value */
       t = (aflags & ASS_APPEND) ? make_variable_value (var, value, aflags) : value;
       (*(var->assign_func)) (var, t, -1, 0);
       if (t != value && t)
     free (t);
     }
   else
     {
       t = make_variable_value (var, value, aflags);
       if ((aflags & (ASS_NAMEREF|ASS_FORCE)) == ASS_NAMEREF && check_selfref (name_cell (var), t, 0))
     {
       if (variable_context)
         internal_warning (_("%s: circular name reference"), name_cell (var));
       else
         {
           internal_error (_("%s: nameref variable self references not allowed"), name_cell (var));
           free (t);
           if (invis)
         VSETATTR (var, att_invisible);  /* XXX */
           return ((SHELL_VAR *)NULL);
         }
     }
       if ((aflags & ASS_NAMEREF) && (valid_nameref_value (t, 0) == 0))
     {
       free (t);
       if (invis)
         VSETATTR (var, att_invisible);  /* XXX */
       return ((SHELL_VAR *)NULL);
     }
       FREE (value_cell (var));
       var_setvalue (var, t);
     }
   INVALIDATE_EXPORTSTR (var);
   if (mark_modified_vars)
     VSETATTR (var, att_exported);
   if (exported_p (var))
     array_needs_making = 1;
   return (var);
 }
References _, array_needs_making, ASS_APPEND, ASS_FORCE, ASS_NAMEREF, att_exported, att_invisible, check_selfref(), exported_p, FREE, free, internal_error(), internal_warning(), INVALIDATE_EXPORTSTR, invisible_p, make_variable_value(), mark_modified_vars, name_cell, NULL, t, valid_nameref_value(), value, value_cell, var_setvalue, variable_context, VSETATTR, and VUNSETATTR.
Referenced by execute_for_command().
can_optimize_assignment()
static int can_optimize_assignment (SHELL_VAR * entry, char * value, int aflags) static
Definition at line 3033 of file variables.c.
 {
   if ((aflags & ASS_APPEND) == 0)
     return 0;
 #if defined (ARRAY_VARS)
   if (array_p (entry) || assoc_p (entry))
     return 0;
 #endif
   if (integer_p (entry) || uppercase_p (entry) || lowercase_p (entry) || capcase_p (entry))
     return 0;
   if (readonly_p (entry) || noassign_p (entry))
     return 0;
   return 1;
 }
References array_p, ASS_APPEND, assoc_p, capcase_p, integer_p, lowercase_p, noassign_p, readonly_p, and uppercase_p.
Referenced by bind_variable_internal().
check_unbind_variable()
int check_unbind_variable (char * name) const
Definition at line 3874 of file variables.c.
 {
   SHELL_VAR *v;
   v = find_variable (name);
   if (v && readonly_p (v))
     {
       internal_error (_("%s: cannot unset: readonly %s"), name, "variable");
       return -2;
     }
   else if (v && non_unsettable_p (v))
     {
       internal_error (_("%s: cannot unset"), name);
       return -2;
     }
   return (unbind_variable (name));
 }
References _, find_variable(), internal_error(), non_unsettable_p, readonly_p, and unbind_variable().
chkexport()
int chkexport (char * name)
Definition at line 5093 of file variables.c.
 {
   SHELL_VAR *v;
   v = find_variable (name);
   if (v && exported_p (v))
     {
       array_needs_making = 1;
       maybe_make_export_env ();
       return 1;
     }
   return 0;
 }
References array_needs_making, exported_p, find_variable(), and maybe_make_export_env().
clear_dollar_vars()
void clear_dollar_vars ()
Definition at line 5619 of file variables.c.
 {
   free_dollar_vars ();
   dispose_words (rest_of_args);
   rest_of_args = (WORD_LIST *)NULL;
   posparam_count = 0;
 }
References dispose_words(), free_dollar_vars(), NULL, posparam_count, and rest_of_args.
Referenced by pop_dollar_vars().
create_variable_tables()
static void create_variable_tables () static
Definition at line 341 of file variables.c.
 {
   if (shell_variables == 0)
     {
       shell_variables = global_variables = new_var_context ((char *)NULL, 0);
       shell_variables->scope = 0;
       shell_variables->table = hash_create (VARIABLES_HASH_BUCKETS);
     }
   if (shell_functions == 0)
     shell_functions = hash_create (FUNCTIONS_HASH_BUCKETS);
 #if defined (DEBUGGER)
   if (shell_function_defs == 0)
     shell_function_defs = hash_create (FUNCTIONS_HASH_BUCKETS);
 #endif
 }
References FUNCTIONS_HASH_BUCKETS, global_variables, hash_create(), new_var_context(), NULL, var_context::scope, shell_functions, shell_variables, var_context::table, and VARIABLES_HASH_BUCKETS.
Referenced by bind_global_variable(), bind_variable(), initialize_shell_variables(), make_new_variable(), and set_if_not().
delete_all_contexts()
void delete_all_contexts (VAR_CONTEXT * vcxt)
Definition at line 5448 of file variables.c.
 {
   delete_local_contexts (vcxt);
   delete_all_variables (global_variables->table);
   shell_variables = global_variables;
 }
References delete_all_variables(), delete_local_contexts(), global_variables, shell_variables, and var_context::table.
Referenced by shell_reinitialize().
delete_all_variables()
void delete_all_variables (HASH_TABLE * hashed_vars)
Definition at line 4084 of file variables.c.
 {
   hash_flush (hashed_vars, free_variable_hash_data);
 }
References free_variable_hash_data(), and hash_flush().
Referenced by delete_all_contexts(), dispose_var_context(), kill_all_local_variables(), and shell_reinitialize().
delete_local_contexts()
static void delete_local_contexts (VAR_CONTEXT * vcxt) static
Definition at line 5433 of file variables.c.
 {
   VAR_CONTEXT *v, *t;
   for (v = vcxt; v != global_variables; v = t)
     {
       t = v->down;
       dispose_var_context (v);
     }
 }
References dispose_var_context(), var_context::down, global_variables, and t.
Referenced by delete_all_contexts(), and reset_local_contexts().
delete_var()
int delete_var (char * name, VAR_CONTEXT * vc) const
Definition at line 3949 of file variables.c.
 {
   BUCKET_CONTENTS *elt;
   SHELL_VAR *old_var;
   VAR_CONTEXT *v;
   for (elt = (BUCKET_CONTENTS *)NULL, v = vc; v; v = v->down)
     if (elt = hash_remove (name, v->table, 0))
       break;
   if (elt == 0)
     return (-1);
   old_var = (SHELL_VAR *)elt->data;
   free (elt->key);
   free (elt);
   dispose_variable (old_var);
   return (0);
 }
References bucket_contents::data, dispose_variable(), var_context::down, free, hash_remove(), bucket_contents::key, NULL, and var_context::table.
dispose_saved_dollar_vars()
void dispose_saved_dollar_vars ()
Definition at line 5698 of file variables.c.
 {
   if (dollar_arg_stack == 0 || dollar_arg_stack_index == 0)
     return;
   dispose_words (dollar_arg_stack[--dollar_arg_stack_index].rest);
   free_saved_dollar_vars (dollar_arg_stack[dollar_arg_stack_index].first_ten);
   free (dollar_arg_stack[dollar_arg_stack_index].first_ten);
   dollar_arg_stack[dollar_arg_stack_index].first_ten = (char **)NULL;
   dollar_arg_stack[dollar_arg_stack_index].rest = (WORD_LIST *)NULL;
   dollar_arg_stack[dollar_arg_stack_index].count = 0;
 }
References saved_dollar_vars::count, dispose_words(), dollar_arg_stack, dollar_arg_stack_index, saved_dollar_vars::first_ten, free, free_saved_dollar_vars(), NULL, and saved_dollar_vars::rest.
dispose_temporary_env()
static void dispose_temporary_env (sh_free_func_t * pushf) static
Definition at line 4678 of file variables.c.
 {
   int i;
   HASH_TABLE *disposer;
   tempvar_list = strvec_create (HASH_ENTRIES (temporary_env) + 1);
   tempvar_list[tvlist_ind = 0] = 0;
   disposer = temporary_env;
   temporary_env = (HASH_TABLE *)NULL;
   hash_flush (disposer, pushf);
   hash_dispose (disposer);
   tempvar_list[tvlist_ind] = 0;
   array_needs_making = 1;
   for (i = 0; i < tvlist_ind; i++)
     stupidly_hack_special_variables (tempvar_list[i]);
   strvec_dispose (tempvar_list);
   tempvar_list = 0;
   tvlist_ind = 0;
 }
References array_needs_making, hash_dispose(), HASH_ENTRIES, hash_flush(), i, NULL, strvec_create(), strvec_dispose(), stupidly_hack_special_variables(), temporary_env, tempvar_list, and tvlist_ind.
Referenced by dispose_used_env_vars(), merge_function_temporary_env(), and merge_temporary_env().
dispose_used_env_vars()
void dispose_used_env_vars ()
Definition at line 4706 of file variables.c.
 {
   if (temporary_env)
     {
       dispose_temporary_env (propagate_temp_var);
       maybe_make_export_env ();
     }
 }
References dispose_temporary_env(), maybe_make_export_env(), propagate_temp_var(), and temporary_env.
Referenced by execute_command_internal(), and reader_loop().
dispose_var_context()
void dispose_var_context (VAR_CONTEXT * vc)
Definition at line 5241 of file variables.c.
 {
   FREE (vc->name);
   if (vc->table)
     {
       delete_all_variables (vc->table);
       hash_dispose (vc->table);
     }
   free (vc);
 }
References delete_all_variables(), FREE, free, hash_dispose(), var_context::name, and var_context::table.
Referenced by delete_local_contexts(), and pop_var_context().
dispose_variable()
void dispose_variable (SHELL_VAR * var)
Definition at line 3784 of file variables.c.
 {
   if (var == 0)
     return;
   if (nofree_p (var) == 0)
     dispose_variable_value (var);
   FREE_EXPORTSTR (var);
   free (var->name);
   if (exported_p (var))
     array_needs_making = 1;
   free (var);
 }
References array_needs_making, dispose_variable_value(), exported_p, free, FREE_EXPORTSTR, and nofree_p.
Referenced by delete_var(), execute_for_command(), free_variable_hash_data(), makunbound(), propagate_temp_var(), push_exported_var(), push_posix_temp_var(), push_posix_tempvar_internal(), push_temp_var(), and unbind_func().
dispose_variable_value()
static void dispose_variable_value (SHELL_VAR * var) static
Definition at line 3766 of file variables.c.
 {
   if (function_p (var))
     dispose_command (function_cell (var));
 #if defined (ARRAY_VARS)
   else if (array_p (var))
     array_dispose (array_cell (var));
   else if (assoc_p (var))
     assoc_dispose (assoc_cell (var));
 #endif
   else if (nameref_p (var))
     FREE (nameref_cell (var));
   else
     FREE (value_cell (var));
 }
References array_cell, array_p, assoc_cell, assoc_p, dispose_command(), FREE, function_cell, function_p, nameref_cell, nameref_p, and value_cell.
Referenced by dispose_variable().
export_environment_candidate()
static int export_environment_candidate (SHELL_VAR * var) static
Definition at line 4391 of file variables.c.
 {
   return (exported_p (var) && (invisible_p (var) == 0 || imported_p (var)));
 }
References exported_p, imported_p, and invisible_p.
Referenced by make_var_export_array().
fapply()
static SHELL_VAR** fapply (sh_var_map_func_t * func) static
Definition at line 4334 of file variables.c.
 {
   SHELL_VAR **list;
   list = map_over_funcs (func);
   if (list /* && posixly_correct */)
     sort_variables (list);
   return (list);
 }
References list(), map_over_funcs(), and sort_variables().
Referenced by all_shell_functions(), and all_visible_functions().
find_function()
SHELL_VAR* find_function (char * name) const
Definition at line 2487 of file variables.c.
 {
   return (hash_lookup (name, shell_functions));
 }
References hash_lookup(), and shell_functions.
Referenced by bind_function(), do_assignment_statements(), execute_disk_command(), execute_intern_function(), execute_simple_command(), initialize_shell_variables(), pseudo_exec_argv(), and run_pipe().
find_function_def()
FUNCTION_DEF* find_function_def (char * name) const
Definition at line 2496 of file variables.c.
 {
 #if defined (DEBUGGER)
   return ((FUNCTION_DEF *)hash_lookup (name, shell_function_defs));
 #else
   return ((FUNCTION_DEF *)0);
 #endif
 }
References hash_lookup().
Referenced by execute_function().
find_global_variable()
SHELL_VAR* find_global_variable (char * name) const
Definition at line 2368 of file variables.c.
 {
   SHELL_VAR *var;
   var = var_lookup (name, global_variables);
   if (var && nameref_p (var))
     var = find_variable_nameref (var);  /* XXX - find_global_variable_noref? */
   if (var == 0)
     return ((SHELL_VAR *)NULL);
   return (var->dynamic_value ? (*(var->dynamic_value)) (var) : var);
 }
References find_variable_nameref(), global_variables, nameref_p, NULL, and var_lookup().
Referenced by bind_variable_internal().
find_global_variable_last_nameref()
SHELL_VAR* find_global_variable_last_nameref (char * name, int vflags) const
Definition at line 2147 of file variables.c.
 {
   SHELL_VAR *v, *nv;
   char *newname;
   int level;
   nv = v = find_global_variable_noref (name);
   level = 0;
   while (v && nameref_p (v))
     {
       level++;
       if (level > NAMEREF_MAX)
         return ((SHELL_VAR *)0);    /* error message here? */
       newname = nameref_cell (v);
       if (newname == 0 || *newname == '\0')
     return ((vflags && invisible_p (v)) ? v : (SHELL_VAR *)0);
       nv = v;
       /* We don't accommodate array subscripts here. */
       v = find_global_variable_noref (newname);
     }
   return nv;
 }
References find_global_variable_noref(), invisible_p, nameref_cell, NAMEREF_MAX, and nameref_p.
Referenced by nameref_transform_name().
find_global_variable_noref()
SHELL_VAR* find_global_variable_noref (char * name) const
Definition at line 2384 of file variables.c.
 {
   SHELL_VAR *var;
   var = var_lookup (name, global_variables);
   if (var == 0)
     return ((SHELL_VAR *)NULL);
   return (var->dynamic_value ? (*(var->dynamic_value)) (var) : var);
 }
References global_variables, NULL, and var_lookup().
Referenced by find_global_variable_last_nameref(), and find_variable_nameref().
find_nameref_at_context()
static SHELL_VAR* find_nameref_at_context (SHELL_VAR * v, VAR_CONTEXT * vc) static
Definition at line 2173 of file variables.c.
 {
   SHELL_VAR *nv, *nv2;
   char *newname;
   int level;
   nv = v;
   level = 1;
   while (nv && nameref_p (nv))
     {
       level++;
       if (level > NAMEREF_MAX)
         return (&nameref_maxloop_value);
       newname = nameref_cell (nv);
       if (newname == 0 || *newname == '\0')
         return ((SHELL_VAR *)NULL);
       nv2 = hash_lookup (newname, vc->table);
       if (nv2 == 0)
         break;
       nv = nv2;
     }
   return nv;
 }
References hash_lookup(), nameref_cell, NAMEREF_MAX, nameref_maxloop_value, nameref_p, NULL, and var_context::table.
Referenced by find_variable_last_nameref_context(), and find_variable_nameref_context().
find_shell_variable()
SHELL_VAR* find_shell_variable (char * name) const
Definition at line 2398 of file variables.c.
 {
   SHELL_VAR *var;
   var = var_lookup (name, shell_variables);
   if (var && nameref_p (var))
     var = find_variable_nameref (var);
   if (var == 0)
     return ((SHELL_VAR *)NULL);
   return (var->dynamic_value ? (*(var->dynamic_value)) (var) : var);
 }
References find_variable_nameref(), nameref_p, NULL, shell_variables, and var_lookup().
find_special_var()
static int find_special_var (char * name) const inline static
Definition at line 5903 of file variables.c.
 {
   register int i, r;
   for (i = 0; special_vars[i].name; i++)
     {
       r = special_vars[i].name[0] - name[0];
       if (r == 0)
     r = strcmp (special_vars[i].name, name);
       if (r == 0)
     return i;
       else if (r > 0)
     /* Can't match any of rest of elements in sorted list.  Take this out
        if it causes problems in certain environments. */
     break;
     }
   return -1;
 }
References i, name_and_function::name, special_vars, and strcmp.
Referenced by propagate_temp_var(), push_posix_temp_var(), push_temp_var(), and stupidly_hack_special_variables().
find_tempenv_variable()
SHELL_VAR* find_tempenv_variable (char * name) const
Definition at line 4538 of file variables.c.
 {
   return (temporary_env ? hash_lookup (name, temporary_env) : (SHELL_VAR *)NULL);
 }
References hash_lookup(), NULL, and temporary_env.
find_variable()
SHELL_VAR* find_variable (char * name) const
Definition at line 2415 of file variables.c.
 {
   SHELL_VAR *v;
   int flags;
   last_table_searched = 0;
   flags = 0;
   if (expanding_redir == 0 && (assigning_in_environment || executing_builtin))
     flags |= FV_FORCETEMPENV;
   v = find_variable_internal (name, flags);
   if (v && nameref_p (v))
     v = find_variable_nameref (v);
   return v;
 }
References assigning_in_environment, executing_builtin, expanding_redir, find_variable_internal(), find_variable_nameref(), flags, FV_FORCETEMPENV, last_table_searched, and nameref_p.
Referenced by asort_builtin(), assign_in_env(), bind_int_variable(), builtin_unbind_variable(), check_unbind_variable(), chkexport(), execute_for_command(), execute_function(), execute_prompt_command(), expr_streval(), get_name_for_error(), get_string_value(), get_var_and_type(), init_funcname_var(), init_seconds_var(), initialize_shell_variables(), make_funcname_visible(), make_local_variable(), mktemp_builtin(), param_expand(), parameter_brace_expand_length(), parameter_brace_expand_word(), parameter_brace_transform(), printenv_builtin(), read_command(), redir_varvalue(), run_startup_files(), set_argv0(), set_home_var(), set_if_not(), set_ppid(), set_pwd(), set_shell_var(), sv_funcnest(), sv_ifs(), sv_ignoreeof(), sv_optind(), sv_shcompat(), sv_strict_posix(), sv_xtracefd(), uidset(), and unary_test().
find_variable_for_assignment()
SHELL_VAR* find_variable_for_assignment (char * name) const
Definition at line 2454 of file variables.c.
 {
   SHELL_VAR *v;
   int flags;
   last_table_searched = 0;
   flags = 0;
   if (expanding_redir == 0 && (assigning_in_environment || executing_builtin))
     flags |= FV_FORCETEMPENV;
   v = find_variable_internal (name, flags);
   if (v && nameref_p (v))
     v = find_variable_nameref (v);
   return v;
 }
References assigning_in_environment, executing_builtin, expanding_redir, find_variable_internal(), find_variable_nameref(), flags, FV_FORCETEMPENV, last_table_searched, and nameref_p.
find_variable_internal()
SHELL_VAR* find_variable_internal (char * name, int flags) const
Definition at line 2026 of file variables.c.
 {
   SHELL_VAR *var;
   int search_tempenv, force_tempenv;
   VAR_CONTEXT *vc;
   var = (SHELL_VAR *)NULL;
   force_tempenv = (flags & FV_FORCETEMPENV);
   /* If explicitly requested, first look in the temporary environment for
      the variable.  This allows constructs such as "foo=x eval 'echo $foo'"
      to get the `exported' value of $foo.  This happens if we are executing
      a function or builtin, or if we are looking up a variable in a
      "subshell environment". */
   search_tempenv = force_tempenv || (expanding_redir == 0 && subshell_environment);
   if (search_tempenv && temporary_env)
     var = hash_lookup (name, temporary_env);
   if (var == 0)
     {
       if ((flags & FV_SKIPINVISIBLE) == 0)
     var = var_lookup (name, shell_variables);
       else
     {
       /* essentially var_lookup expanded inline so we can check for
          att_invisible */
       for (vc = shell_variables; vc; vc = vc->down)
         {
           var = hash_lookup (name, vc->table);
           if (var && invisible_p (var))
         var = 0;
           if (var)
         break;
         }
     }
     }
   if (var == 0)
     return ((SHELL_VAR *)NULL);
   return (var->dynamic_value ? (*(var->dynamic_value)) (var) : var);
 }
References var_context::down, expanding_redir, flags, FV_FORCETEMPENV, FV_SKIPINVISIBLE, hash_lookup(), invisible_p, NULL, shell_variables, subshell_environment, var_context::table, temporary_env, and var_lookup().
Referenced by find_variable(), find_variable_for_assignment(), find_variable_last_nameref(), find_variable_nameref(), find_variable_no_invisible(), find_variable_noref(), find_variable_notempenv(), and find_variable_tempenv().
find_variable_last_nameref()
SHELL_VAR* find_variable_last_nameref (char * name, int vflags) const
Definition at line 2117 of file variables.c.
 {
   SHELL_VAR *v, *nv;
   char *newname;
   int level, flags;
   nv = v = find_variable_noref (name);
   level = 0;
   while (v && nameref_p (v))
     {
       level++;
       if (level > NAMEREF_MAX)
         return ((SHELL_VAR *)0);    /* error message here? */
       newname = nameref_cell (v);
       if (newname == 0 || *newname == '\0')
     return ((vflags && invisible_p (v)) ? v : (SHELL_VAR *)0);
       nv = v;
       flags = 0;
       if (expanding_redir == 0 && (assigning_in_environment || executing_builtin))
     flags |= FV_FORCETEMPENV;
       /* We don't accommodate array subscripts here. */
       v = find_variable_internal (newname, flags);
     }
   return nv;
 }
References assigning_in_environment, executing_builtin, expanding_redir, find_variable_internal(), find_variable_noref(), flags, FV_FORCETEMPENV, invisible_p, nameref_cell, NAMEREF_MAX, and nameref_p.
Referenced by assign_in_env(), bind_variable_internal(), execute_for_command(), expr_streval(), find_variable_nameref_for_assignment(), find_variable_nameref_for_create(), nameref_transform_name(), param_expand(), parameter_brace_expand_indir(), parameter_brace_expand_word(), parameter_brace_find_indir(), and redir_varvalue().
find_variable_last_nameref_context()
static SHELL_VAR* find_variable_last_nameref_context (SHELL_VAR * v, VAR_CONTEXT * vc, VAR_CONTEXT ** nvcp) static
Definition at line 2236 of file variables.c.
 {
   SHELL_VAR *nv, *nv2;
   VAR_CONTEXT *nvc;
   /* Look starting at the current context all the way `up' */
   for (nv = v, nvc = vc; nvc; nvc = nvc->down)
     {
       nv2 = find_nameref_at_context (nv, nvc);
       if (nv2 == &nameref_maxloop_value)
     return (nv2);           /* XXX */
       if (nv2 == 0)
     continue;
       nv = nv2;
       if (*nvcp)
         *nvcp = nvc;
     }
   return (nameref_p (nv) ? nv : (SHELL_VAR *)NULL);
 }
References var_context::down, find_nameref_at_context(), nameref_maxloop_value, nameref_p, and NULL.
Referenced by bind_variable().
find_variable_nameref()
SHELL_VAR* find_variable_nameref (SHELL_VAR * v)
Definition at line 2076 of file variables.c.
 {
   int level, flags;
   char *newname;
   SHELL_VAR *orig, *oldv;
   level = 0;
   orig = v;
   while (v && nameref_p (v))
     {
       level++;
       if (level > NAMEREF_MAX)
     return ((SHELL_VAR *)0);    /* error message here? */
       newname = nameref_cell (v);
       if (newname == 0 || *newname == '\0')
     return ((SHELL_VAR *)0);
       oldv = v;
       flags = 0;
       if (expanding_redir == 0 && (assigning_in_environment || executing_builtin))
     flags |= FV_FORCETEMPENV;
       /* We don't handle array subscripts here. */
       v = find_variable_internal (newname, flags);
       if (v == orig || v == oldv)
     {
       internal_warning (_("%s: circular name reference"), orig->name);
 #if 1
       /* XXX - provisional change - circular refs go to
          global scope for resolution, without namerefs. */
       if (variable_context && v->context)
         return (find_global_variable_noref (v->name));
       else
 #endif
       return ((SHELL_VAR *)0);
     }
     }
   return v;
 }
References _, assigning_in_environment, variable::context, executing_builtin, expanding_redir, find_global_variable_noref(), find_variable_internal(), flags, FV_FORCETEMPENV, internal_warning(), variable::name, nameref_cell, NAMEREF_MAX, nameref_p, and variable_context.
Referenced by find_global_variable(), find_shell_variable(), find_variable(), find_variable_for_assignment(), find_variable_no_invisible(), find_variable_notempenv(), find_variable_tempenv(), unbind_global_variable(), and unbind_variable().
find_variable_nameref_context()
static SHELL_VAR* find_variable_nameref_context (SHELL_VAR * v, VAR_CONTEXT * vc, VAR_CONTEXT ** nvcp) static
Definition at line 2205 of file variables.c.
 {
   SHELL_VAR *nv, *nv2;
   VAR_CONTEXT *nvc;
   /* Look starting at the current context all the way `up' */
   for (nv = v, nvc = vc; nvc; nvc = nvc->down)
     {
       nv2 = find_nameref_at_context (nv, nvc);
       if (nv2 == &nameref_maxloop_value)
     return (nv2);           /* XXX */
       if (nv2 == 0)
         continue;
       nv = nv2;
       if (*nvcp)
         *nvcp = nvc;
       if (nameref_p (nv) == 0)
         break;
     }
   return (nameref_p (nv) ? (SHELL_VAR *)NULL : nv);
 }
References var_context::down, find_nameref_at_context(), nameref_maxloop_value, nameref_p, and NULL.
Referenced by bind_variable().
find_variable_nameref_for_assignment()
SHELL_VAR* find_variable_nameref_for_assignment (char * name, int flags) const
Definition at line 2286 of file variables.c.
 {
   SHELL_VAR *var;
   /* See if we have a nameref pointing to a variable that hasn't been
      created yet. */
   var = find_variable_last_nameref (name, 1);
   if (var && nameref_p (var) && invisible_p (var))  /* XXX - flags */
     {
       internal_warning (_("%s: removing nameref attribute"), name);
       VUNSETATTR (var, att_nameref);
     }
   if (var && nameref_p (var))
     {
       if (valid_nameref_value (nameref_cell (var), 1) == 0)
     {
       sh_invalidid (nameref_cell (var) ? nameref_cell (var) : "");
       return ((SHELL_VAR *)INVALID_NAMEREF_VALUE);
     }
     }
   return (var);
 }
References _, att_nameref, find_variable_last_nameref(), internal_warning(), INVALID_NAMEREF_VALUE, invisible_p, nameref_cell, nameref_p, sh_invalidid(), valid_nameref_value(), and VUNSETATTR.
find_variable_nameref_for_create()
SHELL_VAR* find_variable_nameref_for_create (char * name, int flags) const
Definition at line 2260 of file variables.c.
 {
   SHELL_VAR *var;
   /* See if we have a nameref pointing to a variable that hasn't been
      created yet. */
   var = find_variable_last_nameref (name, 1);
   if ((flags&1) && var && nameref_p (var) && invisible_p (var))
     {
       internal_warning (_("%s: removing nameref attribute"), name);
       VUNSETATTR (var, att_nameref);
     }
   if (var && nameref_p (var))
     {
       if (legal_identifier (nameref_cell (var)) == 0)
     {
       sh_invalidid (nameref_cell (var) ? nameref_cell (var) : "");
       return ((SHELL_VAR *)INVALID_NAMEREF_VALUE);
     }
     }
   return (var);
 }
References _, att_nameref, find_variable_last_nameref(), flags, internal_warning(), INVALID_NAMEREF_VALUE, invisible_p, legal_identifier(), nameref_cell, nameref_p, sh_invalidid(), and VUNSETATTR.
find_variable_no_invisible()
SHELL_VAR* find_variable_no_invisible (char * name) const
Definition at line 2435 of file variables.c.
 {
   SHELL_VAR *v;
   int flags;
   last_table_searched = 0;
   flags = FV_SKIPINVISIBLE;
   if (expanding_redir == 0 && (assigning_in_environment || executing_builtin))
     flags |= FV_FORCETEMPENV;
   v = find_variable_internal (name, flags);
   if (v && nameref_p (v))
     v = find_variable_nameref (v);
   return v;
 }
References assigning_in_environment, executing_builtin, expanding_redir, find_variable_internal(), find_variable_nameref(), flags, FV_FORCETEMPENV, FV_SKIPINVISIBLE, last_table_searched, and nameref_p.
find_variable_noref()
SHELL_VAR* find_variable_noref (char * name) const
Definition at line 2471 of file variables.c.
 {
   SHELL_VAR *v;
   int flags;
   flags = 0;
   if (expanding_redir == 0 && (assigning_in_environment || executing_builtin))
     flags |= FV_FORCETEMPENV;
   v = find_variable_internal (name, flags);
   return v;
 }
References assigning_in_environment, executing_builtin, expanding_redir, find_variable_internal(), flags, and FV_FORCETEMPENV.
Referenced by bind_variable_internal(), find_variable_last_nameref(), make_local_variable(), and unary_test().
find_variable_notempenv()
SHELL_VAR* find_variable_notempenv (char * name) const
Definition at line 2356 of file variables.c.
 {
   SHELL_VAR *var;
   var = find_variable_internal (name, 0);
   if (var && nameref_p (var))
     var = find_variable_nameref (var);
   return (var);
 }
References find_variable_internal(), find_variable_nameref(), and nameref_p.
find_variable_tempenv()
SHELL_VAR* find_variable_tempenv (char * name) const
Definition at line 2343 of file variables.c.
 {
   SHELL_VAR *var;
   var = find_variable_internal (name, FV_FORCETEMPENV);
   if (var && nameref_p (var))
     var = find_variable_nameref (var);
   return (var);
 }
References find_variable_internal(), find_variable_nameref(), FV_FORCETEMPENV, and nameref_p.
Referenced by _find_user_command_internal(), and search_for_command().
flatten()
static void flatten (HASH_TABLE * var_hash_table, sh_var_map_func_t * func, VARLIST * vlist, int flags) static
Definition at line 4271 of file variables.c.
 {
   register int i;
   register BUCKET_CONTENTS *tlist;
   int r;
   SHELL_VAR *var;
   if (var_hash_table == 0 || (HASH_ENTRIES (var_hash_table) == 0) || (vlist == 0 && func == 0))
     return;
   for (i = 0; i < var_hash_table->nbuckets; i++)
     {
       for (tlist = hash_items (i, var_hash_table); tlist; tlist = tlist->next)
     {
       var = (SHELL_VAR *)tlist->data;
       r = func ? (*func) (var) : 1;
       if (r && vlist)
         vlist_add (vlist, var, flags);
     }
     }
 }
References bucket_contents::data, flags, HASH_ENTRIES, hash_items, i, hash_table::nbuckets, bucket_contents::next, and vlist_add().
Referenced by all_local_variables(), map_over(), map_over_funcs(), and push_var_context().
flush_temporary_env()
void flush_temporary_env ()
Definition at line 4737 of file variables.c.
 {
   if (temporary_env)
     {
       hash_flush (temporary_env, free_variable_hash_data);
       hash_dispose (temporary_env);
       temporary_env = (HASH_TABLE *)NULL;
     }
 }
References free_variable_hash_data(), hash_dispose(), hash_flush(), NULL, and temporary_env.
Referenced by command_substitute().
free_dollar_vars()
static void free_dollar_vars () static
Definition at line 5596 of file variables.c.
 {
   int i;
   for (i = 1; i < 10; i++)
     {
       FREE (dollar_vars[i]);
       dollar_vars[i] = (char *)NULL;
     }
 }
References dollar_vars, FREE, i, and NULL.
Referenced by clear_dollar_vars().
free_saved_dollar_vars()
static void free_saved_dollar_vars (char ** args) static
Definition at line 5608 of file variables.c.
 {
   int i;
   for (i = 1; i < 10; i++)
     FREE (args[i]);
 }
References FREE, and i.
Referenced by dispose_saved_dollar_vars().
free_variable_hash_data()
static void free_variable_hash_data (PTR_T data) static
Definition at line 4073 of file variables.c.
 {
   SHELL_VAR *var;
   var = (SHELL_VAR *)data;
   dispose_variable (var);
 }
References dispose_variable().
Referenced by delete_all_variables(), and flush_temporary_env().
get_bash_argv0()
static SHELL_VAR* get_bash_argv0 (SHELL_VAR * var) static
Definition at line 1546 of file variables.c.
 {
   return (set_string_value (var, dollar_vars[0], 0));
 }
References dollar_vars, and set_string_value().
Referenced by initialize_dynamic_variables().
get_bash_command()
static SHELL_VAR* get_bash_command (SHELL_VAR * var) static
Definition at line 1589 of file variables.c.
 {
   char *p;
   p = the_printed_command_except_trap ? the_printed_command_except_trap : "";
   return (set_string_value (var, p, 0));
 }
References p, set_string_value(), and the_printed_command_except_trap.
Referenced by initialize_dynamic_variables().
get_bash_name()
static char* get_bash_name () static
Definition at line 778 of file variables.c.
 {
   char *name;
   if ((login_shell == 1) && RELPATH(shell_name))
     {
       if (current_user.shell == 0)
     get_current_user_info ();
       name = savestring (current_user.shell);
     }
   else if (ABSPATH(shell_name))
     name = savestring (shell_name);
   else if (shell_name[0] == '.' && shell_name[1] == '/')
     {
       /* Fast path for common case. */
       char *cdir;
       int len;
       cdir = get_string_value ("PWD");
       if (cdir)
     {
       len = strlen (cdir);
       name = (char *)xmalloc (len + strlen (shell_name) + 1);
       strcpy (name, cdir);
       strcpy (name + len, shell_name + 1);
     }
       else
     name = savestring (shell_name);
     }
   else
     {
       char *tname;
       int s;
       tname = find_user_command (shell_name);
       if (tname == 0)
     {
       /* Try the current directory.  If there is not an executable
          there, just punt and use the login shell. */
       s = file_status (shell_name);
       if (s & FS_EXECABLE)
         {
           tname = make_absolute (shell_name, get_string_value ("PWD"));
           if (*shell_name == '.')
         {
           name = sh_canonpath (tname, PATH_CHECKDOTDOT|PATH_CHECKEXISTS);
           if (name == 0)
             name = tname;
           else
             free (tname);
         }
          else
         name = tname;
         }
       else
         {
           if (current_user.shell == 0)
         get_current_user_info ();
           name = savestring (current_user.shell);
         }
     }
       else
     {
       name = full_pathname (tname);
       free (tname);
     }
     }
   return (name);
 }
References ABSPATH, current_user, file_status(), find_user_command(), free, FS_EXECABLE, full_pathname(), get_current_user_info(), get_string_value(), len, login_shell, make_absolute(), PATH_CHECKDOTDOT, PATH_CHECKEXISTS, RELPATH, s, savestring(), sh_canonpath(), user_info::shell, shell_name, strcpy, strlen(), and xmalloc.
Referenced by initialize_shell_variables().
get_bashpid()
static SHELL_VAR* get_bashpid (SHELL_VAR * var) static
Definition at line 1536 of file variables.c.
 {
   int pid;
   pid = getpid ();
   return (set_int_value (var, pid, 1));
 }
References getpid(), pid, and set_int_value().
Referenced by initialize_dynamic_variables().
get_epochrealtime()
static SHELL_VAR* get_epochrealtime (SHELL_VAR * var) static
Definition at line 1521 of file variables.c.
 {
   char buf[32];
   struct timeval tv;
   gettimeofday (&tv, NULL);
   snprintf (buf, sizeof (buf), "%u%c%06u", (unsigned)tv.tv_sec,
                        locale_decpoint (),
                        (unsigned)tv.tv_usec);
   return (set_string_value (var, buf, 0));
 }
References buf, gettimeofday(), locale_decpoint(), NULL, set_string_value(), snprintf(), timeval::tv_sec, and timeval::tv_usec.
Referenced by initialize_dynamic_variables().
get_epochseconds()
static SHELL_VAR* get_epochseconds (SHELL_VAR * var) static
Definition at line 1511 of file variables.c.
 {
   intmax_t now;
   now = NOW;
   return (set_int_value (var, now, 0));
 }
References NOW, and set_int_value().
Referenced by initialize_dynamic_variables().
get_funcname()
static SHELL_VAR* get_funcname (SHELL_VAR * self) static
Definition at line 1859 of file variables.c.
 {
 #if ! defined (ARRAY_VARS)
   if (variable_context && this_shell_function)
     return (set_string_value (self, this_shell_function->name, 0));
 #endif
   return (self);
 }
References variable::name, set_string_value(), this_shell_function, and variable_context.
Referenced by init_funcname_var().
get_lineno()
static SHELL_VAR* get_lineno (SHELL_VAR * var) static
Definition at line 1479 of file variables.c.
 {
   int ln;
   ln = executing_line_number ();
   return (set_int_value (var, ln, 0));
 }
References executing_line_number(), and set_int_value().
Referenced by initialize_dynamic_variables().
get_random()
static SHELL_VAR* get_random (SHELL_VAR * var) static
Definition at line 1443 of file variables.c.
 {
   int rv;
   rv = get_random_number ();
   return (set_int_value (var, rv, 1));
 }
References get_random_number(), and set_int_value().
Referenced by initialize_dynamic_variables().
get_random_number()
int get_random_number ()
Definition at line 1423 of file variables.c.
 {
   int rv, pid;
   /* Reset for command and process substitution. */
   pid = getpid ();
   if (subshell_environment && seeded_subshell != pid)
     {
       seedrand ();
       seeded_subshell = pid;
     }
   do
     rv = brand ();
   while (rv == last_random_value);
   return (last_random_value = rv);
 }
References brand(), getpid(), last_random_value, pid, seeded_subshell, seedrand(), and subshell_environment.
Referenced by get_random().
get_seconds()
static SHELL_VAR* get_seconds (SHELL_VAR * var) static
Definition at line 1369 of file variables.c.
 {
   time_t time_since_start;
   struct timeval tv;
   gettimeofday(&tv, NULL);
   time_since_start = tv.tv_sec - shell_start_time;
   return (set_int_value (var, seconds_value_assigned + time_since_start, 1));
 }
References gettimeofday(), NULL, seconds_value_assigned, set_int_value(), shell_start_time, and timeval::tv_sec.
Referenced by init_seconds_var().
get_self()
static SHELL_VAR* get_self (SHELL_VAR * self) static
Definition at line 1264 of file variables.c.
 {
   return (self);
 }
Referenced by initialize_dynamic_variables().
get_string_value()
char* get_string_value (char * var_name) const
Definition at line 2530 of file variables.c.
 {
   SHELL_VAR *var;
   var = find_variable (var_name);
   return ((var) ? get_variable_value (var) : (char *)NULL);
 }
References find_variable(), get_variable_value(), and NULL.
Referenced by adjust_shell_level(), bash_special_tilde_expansions(), check_mail(), current_working_directory(), decode_prompt_string(), default_columns(), execute_simple_command(), execute_variable_command(), get_bash_name(), get_locale_var(), get_tmpdir(), indirection_level_string(), job_working_directory(), main(), polite_directory_format(), prompt_again(), realpath_builtin(), remember_mail_dates(), run_startup_files(), send_pwd_to_eterm(), set_default_lang(), set_default_locale_vars(), setup_glob_ignore(), setup_ignore_patterns(), sh_get_env_value(), sh_makepath(), strftime(), sv_locale(), sv_opterr(), time_to_check_mail(), trim_pathname(), and user_command_matches().
get_subshell()
static SHELL_VAR* get_subshell (SHELL_VAR * var) static
Definition at line 1504 of file variables.c.
 {
   return (set_int_value (var, subshell_level, 0));
 }
References set_int_value(), and subshell_level.
Referenced by initialize_dynamic_variables().
get_urandom()
static SHELL_VAR* get_urandom (SHELL_VAR * var) static
Definition at line 1453 of file variables.c.
 {
   u_bits32_t rv;
   rv = get_urandom32 ();
   return (set_int_value (var, rv, 1));
 }
References get_urandom32(), and set_int_value().
Referenced by initialize_dynamic_variables().
get_variable_value()
char* get_variable_value (SHELL_VAR * var)
Definition at line 2509 of file variables.c.
 {
   if (var == 0)
     return ((char *)NULL);
 #if defined (ARRAY_VARS)
   else if (array_p (var))
     return (array_reference (array_cell (var), 0));
   else if (assoc_p (var))
     return (assoc_reference (assoc_cell (var), "0"));
 #endif
   else
     return (value_cell (var));
 }
References array_cell, array_p, assoc_cell, assoc_p, NULL, and value_cell.
Referenced by expr_streval(), get_string_value(), make_variable_value(), parameter_brace_expand_rhs(), redir_varvalue(), and sv_optind().
hash_lookup()
static SHELL_VAR* hash_lookup (char * name, HASH_TABLE * hashed_vars) const static
Definition at line 1988 of file variables.c.
 {
   BUCKET_CONTENTS *bucket;
   bucket = hash_search (name, hashed_vars, 0);
   /* If we find the name in HASHED_VARS, set LAST_TABLE_SEARCHED to that
      table. */
   if (bucket)
     last_table_searched = hashed_vars;
   return (bucket ? (SHELL_VAR *)bucket->data : (SHELL_VAR *)NULL);
 }
References bucket_contents::data, hash_search(), last_table_searched, and NULL.
Referenced by assign_in_env(), bind_tempenv_variable(), bind_variable(), bind_variable_internal(), find_function(), find_function_def(), find_nameref_at_context(), find_tempenv_variable(), find_variable_internal(), and var_lookup().
init_bash_argv()
void init_bash_argv ()
Definition at line 5715 of file variables.c.
 {
   if (bash_argv_initialized == 0)
     {
       save_bash_argv ();
       bash_argv_initialized = 1;
     }
 }
References bash_argv_initialized, and save_bash_argv().
Referenced by _evalfile(), and execute_function().
init_funcname_var()
static SHELL_VAR* init_funcname_var () static
Definition at line 1886 of file variables.c.
 {
   SHELL_VAR *v;
   v = find_variable ("FUNCNAME");
   if (v)
     return v;
 #if defined (ARRAY_VARS)
   INIT_DYNAMIC_ARRAY_VAR ("FUNCNAME", get_funcname, null_array_assign);
 #else
   INIT_DYNAMIC_VAR ("FUNCNAME", (char *)NULL, get_funcname, null_assign);
 #endif
   VSETATTR (v, att_invisible|att_noassign);
   return v;
 }
References att_invisible, att_noassign, find_variable(), get_funcname(), INIT_DYNAMIC_ARRAY_VAR, INIT_DYNAMIC_VAR, NULL, null_assign(), and VSETATTR.
Referenced by initialize_dynamic_variables().
init_seconds_var()
static SHELL_VAR* init_seconds_var () static
Definition at line 1381 of file variables.c.
 {
   SHELL_VAR *v;
   v = find_variable ("SECONDS");
   if (v)
     {
       if (legal_number (value_cell(v), &seconds_value_assigned) == 0)
     seconds_value_assigned = 0;
     }
   INIT_DYNAMIC_VAR ("SECONDS", (v ? value_cell (v) : (char *)NULL), get_seconds, assign_seconds);
   return v;
 }
References assign_seconds(), find_variable(), get_seconds(), INIT_DYNAMIC_VAR, legal_number(), NULL, seconds_value_assigned, and value_cell.
Referenced by initialize_dynamic_variables().
initialize_dynamic_variables()
static void initialize_dynamic_variables () static
Definition at line 1903 of file variables.c.
 {
   SHELL_VAR *v;
   v = init_seconds_var ();
   INIT_DYNAMIC_VAR ("BASH_ARGV0", (char *)NULL, get_bash_argv0, assign_bash_argv0);
   INIT_DYNAMIC_VAR ("BASH_COMMAND", (char *)NULL, get_bash_command, (sh_var_assign_func_t *)NULL);
   INIT_DYNAMIC_VAR ("BASH_SUBSHELL", (char *)NULL, get_subshell, assign_subshell);
   INIT_DYNAMIC_VAR ("RANDOM", (char *)NULL, get_random, assign_random);
   VSETATTR (v, att_integer);
   INIT_DYNAMIC_VAR ("SRANDOM", (char *)NULL, get_urandom, (sh_var_assign_func_t *)NULL);
   VSETATTR (v, att_integer);
   INIT_DYNAMIC_VAR ("LINENO", (char *)NULL, get_lineno, assign_lineno);
   VSETATTR (v, att_regenerate);
   INIT_DYNAMIC_VAR ("BASHPID", (char *)NULL, get_bashpid, null_assign);
   VSETATTR (v, att_integer);
   INIT_DYNAMIC_VAR ("EPOCHSECONDS", (char *)NULL, get_epochseconds, null_assign);
   VSETATTR (v, att_regenerate);
   INIT_DYNAMIC_VAR ("EPOCHREALTIME", (char *)NULL, get_epochrealtime, null_assign);
   VSETATTR (v, att_regenerate);
 #if defined (HISTORY)
   INIT_DYNAMIC_VAR ("HISTCMD", (char *)NULL, get_histcmd, (sh_var_assign_func_t *)NULL);
   VSETATTR (v, att_integer);
 #endif
 #if defined (READLINE)
   INIT_DYNAMIC_VAR ("COMP_WORDBREAKS", (char *)NULL, get_comp_wordbreaks, assign_comp_wordbreaks);
 #endif
 #if defined (PUSHD_AND_POPD) && defined (ARRAY_VARS)
   v = init_dynamic_array_var ("DIRSTACK", get_dirstack, assign_dirstack, 0);
 #endif /* PUSHD_AND_POPD && ARRAY_VARS */
 #if defined (ARRAY_VARS)
   v = init_dynamic_array_var ("GROUPS", get_groupset, null_array_assign, att_noassign);
 #  if defined (DEBUGGER)
   v = init_dynamic_array_var ("BASH_ARGC", get_bashargcv, null_array_assign, att_noassign|att_nounset);
   v = init_dynamic_array_var ("BASH_ARGV", get_bashargcv, null_array_assign, att_noassign|att_nounset);
 #  endif /* DEBUGGER */
   v = init_dynamic_array_var ("BASH_SOURCE", get_self, null_array_assign, att_noassign|att_nounset);
   v = init_dynamic_array_var ("BASH_LINENO", get_self, null_array_assign, att_noassign|att_nounset);
   v = init_dynamic_assoc_var ("BASH_CMDS", get_hashcmd, assign_hashcmd, att_nofree);
 #  if defined (ALIAS)
   v = init_dynamic_assoc_var ("BASH_ALIASES", get_aliasvar, assign_aliasvar, att_nofree);
 #  endif
 #endif
   v = init_funcname_var ();
 }
References assign_bash_argv0(), assign_lineno(), assign_random(), assign_subshell(), att_integer, att_noassign, att_nofree, att_nounset, att_regenerate, get_bash_argv0(), get_bash_command(), get_bashpid(), get_epochrealtime(), get_epochseconds(), get_lineno(), get_random(), get_self(), get_subshell(), get_urandom(), INIT_DYNAMIC_VAR, init_funcname_var(), init_seconds_var(), NULL, null_assign(), and VSETATTR.
Referenced by initialize_shell_variables().
initialize_shell_level()
static void initialize_shell_level () static
Definition at line 897 of file variables.c.
 {
   adjust_shell_level (1);
 }
References adjust_shell_level().
Referenced by initialize_shell_variables().
initialize_shell_variables()
void initialize_shell_variables (char ** env, int privmode)
Definition at line 363 of file variables.c.
 {
   char *name, *string, *temp_string;
   int c, char_index, string_index, string_length, ro;
   SHELL_VAR *temp_var;
   create_variable_tables ();
   for (string_index = 0; env && (string = env[string_index++]); )
     {
       char_index = 0;
       name = string;
       while ((c = *string++) && c != '=')
     ;
       if (string[-1] == '=')
     char_index = string - name - 1;
       /* If there are weird things in the environment, like `=xxx' or a
      string without an `=', just skip them. */
       if (char_index == 0)
     continue;
       /* ASSERT(name[char_index] == '=') */
       name[char_index] = '\0';
       /* Now, name = env variable name, string = env variable value, and
      char_index == strlen (name) */
       temp_var = (SHELL_VAR *)NULL;
 #if defined (FUNCTION_IMPORT)
       /* If exported function, define it now.  Don't import functions from
      the environment in privileged mode. */
       if (privmode == 0 && read_but_dont_execute == 0 &&
           STREQN (BASHFUNC_PREFIX, name, BASHFUNC_PREFLEN) &&
           STREQ (BASHFUNC_SUFFIX, name + char_index - BASHFUNC_SUFFLEN) &&
       STREQN ("() {", string, 4))
     {
       size_t namelen;
       char *tname;      /* desired imported function name */
       namelen = char_index - BASHFUNC_PREFLEN - BASHFUNC_SUFFLEN;
       tname = name + BASHFUNC_PREFLEN;  /* start of func name */
       tname[namelen] = '\0';        /* now tname == func name */
       string_length = strlen (string);
       temp_string = (char *)xmalloc (namelen + string_length + 2);
       memcpy (temp_string, tname, namelen);
       temp_string[namelen] = ' ';
       memcpy (temp_string + namelen + 1, string, string_length + 1);
       /* Don't import function names that are invalid identifiers from the
          environment in posix mode, though we still allow them to be defined as
          shell variables. */
       if (absolute_program (tname) == 0 && (posixly_correct == 0 || legal_identifier (tname)))
         parse_and_execute (temp_string, tname, SEVAL_NONINT|SEVAL_NOHIST|SEVAL_FUNCDEF|SEVAL_ONECMD);
       else
         free (temp_string);     /* parse_and_execute does this */
       if (temp_var = find_function (tname))
         {
           VSETATTR (temp_var, (att_exported|att_imported));
           array_needs_making = 1;
         }
       else
         {
           if (temp_var = bind_invalid_envvar (name, string, 0))
         {
           VSETATTR (temp_var, (att_exported | att_imported | att_invisible));
           array_needs_making = 1;
         }
           last_command_exit_value = EXECUTION_FAILURE;
           report_error (_("error importing function definition for `%s'"), tname);
         }
       /* Restore original suffix */
       tname[namelen] = BASHFUNC_SUFFIX[0];
     }
       else
 #endif /* FUNCTION_IMPORT */
 #if defined (ARRAY_VARS)
 #  if ARRAY_EXPORT
       /* Array variables may not yet be exported. */
       if (STREQN (BASHARRAY_PREFIX, name, BASHARRAY_PREFLEN) &&
       STREQN (BASHARRAY_SUFFIX, name + char_index - BASHARRAY_SUFFLEN, BASHARRAY_SUFFLEN) &&
       *string == '(' && string[1] == '[' && string[strlen (string) - 1] == ')')
     {
       size_t namelen;
       char *tname;      /* desired imported array variable name */
       namelen = char_index - BASHARRAY_PREFLEN - BASHARRAY_SUFFLEN;
       tname = name + BASHARRAY_PREFLEN; /* start of variable name */
       tname[namelen] = '\0';        /* now tname == varname */
       string_length = 1;
       temp_string = extract_array_assignment_list (string, &string_length);
       temp_var = assign_array_from_string (tname, temp_string, 0);
       FREE (temp_string);
       if (temp_var)
         {
           VSETATTR (temp_var, (att_exported | att_imported));
           array_needs_making = 1;
         }
     }
       else if (STREQN (BASHASSOC_PREFIX, name, BASHASSOC_PREFLEN) &&
       STREQN (BASHASSOC_SUFFIX, name + char_index - BASHASSOC_SUFFLEN, BASHASSOC_SUFFLEN) &&
       *string == '(' && string[1] == '[' && string[strlen (string) - 1] == ')')
     {
       size_t namelen;
       char *tname;      /* desired imported assoc variable name */
       namelen = char_index - BASHASSOC_PREFLEN - BASHASSOC_SUFFLEN;
       tname = name + BASHASSOC_PREFLEN; /* start of variable name */
       tname[namelen] = '\0';        /* now tname == varname */
       /* need to make sure it exists as an associative array first */
       temp_var = find_or_make_array_variable (tname, 2);
       if (temp_var)
         {
           string_length = 1;
           temp_string = extract_array_assignment_list (string, &string_length);
           temp_var = assign_array_var_from_string (temp_var, temp_string, 0);
         }
       FREE (temp_string);
       if (temp_var)
         {
           VSETATTR (temp_var, (att_exported | att_imported));
           array_needs_making = 1;
         }
     }
       else
 #  endif /* ARRAY_EXPORT */
 #endif
     {
       ro = 0;
       /* If we processed a command-line option that caused SHELLOPTS to be
          set, it may already be set (and read-only) by the time we process
          the shell's environment. */
       if (/* posixly_correct &&*/ STREQ (name, "SHELLOPTS"))
         {
           temp_var = find_variable ("SHELLOPTS");
           ro = temp_var && readonly_p (temp_var);
           if (temp_var)
         VUNSETATTR (temp_var, att_readonly);
         }
       if (legal_identifier (name))
         {
           temp_var = bind_variable (name, string, 0);
           if (temp_var)
         {
           VSETATTR (temp_var, (att_exported | att_imported));
           if (ro)
             VSETATTR (temp_var, att_readonly);
         }
         }
       else
         {
           temp_var = bind_invalid_envvar (name, string, 0);
           if (temp_var)
         VSETATTR (temp_var, (att_exported | att_imported | att_invisible));
         }
       if (temp_var)
         array_needs_making = 1;
     }
       name[char_index] = '=';
       /* temp_var can be NULL if it was an exported function with a syntax
      error (a different bug, but it still shouldn't dump core). */
       if (temp_var && function_p (temp_var) == 0)   /* XXX not yet */
     {
       CACHE_IMPORTSTR (temp_var, name);
     }
     }
   set_pwd ();
   /* Set up initial value of $_ */
   temp_var = set_if_not ("_", dollar_vars[0]);
   /* Remember this pid. */
   dollar_dollar_pid = getpid ();
   /* Now make our own defaults in case the vars that we think are
      important are missing. */
   temp_var = set_if_not ("PATH", DEFAULT_PATH_VALUE);
   temp_var = set_if_not ("TERM", "dumb");
 #if defined (__QNX__)
   /* set node id -- don't import it from the environment */
   {
     char node_name[22];
 #  if defined (__QNXNTO__)
     netmgr_ndtostr(ND2S_LOCAL_STR, ND_LOCAL_NODE, node_name, sizeof(node_name));
 #  else
     qnx_nidtostr (getnid (), node_name, sizeof (node_name));
 #  endif
     temp_var = bind_variable ("NODE", node_name, 0);
     if (temp_var)
       set_auto_export (temp_var);
   }
 #endif
   /* set up the prompts. */
   if (interactive_shell)
     {
 #if defined (PROMPT_STRING_DECODE)
       set_if_not ("PS1", primary_prompt);
 #else
       if (current_user.uid == -1)
     get_current_user_info ();
       set_if_not ("PS1", current_user.euid == 0 ? "# " : primary_prompt);
 #endif
       set_if_not ("PS2", secondary_prompt);
     }
   if (current_user.euid == 0)
     bind_variable ("PS4", "+ ", 0);
   else
     set_if_not ("PS4", "+ ");
   /* Don't allow IFS to be imported from the environment. */
   temp_var = bind_variable ("IFS", " \t\n", 0);
   setifs (temp_var);
   /* Magic machine types.  Pretty convenient. */
   set_machine_vars ();
   /* Default MAILCHECK for interactive shells.  Defer the creation of a
      default MAILPATH until the startup files are read, because MAIL
      names a mail file if MAILPATH is not set, and we should provide a
      default only if neither is set. */
   if (interactive_shell)
     {
       temp_var = set_if_not ("MAILCHECK", posixly_correct ? "600" : "60");
       VSETATTR (temp_var, att_integer);
     }
   /* Do some things with shell level. */
   initialize_shell_level ();
   set_ppid ();
   set_argv0 ();
   /* Initialize the `getopts' stuff. */
   temp_var = bind_variable ("OPTIND", "1", 0);
   VSETATTR (temp_var, att_integer);
   getopts_reset (0);
   bind_variable ("OPTERR", "1", 0);
   sh_opterr = 1;
   if (login_shell == 1 && posixly_correct == 0)
     set_home_var ();
   /* Get the full pathname to THIS shell, and set the BASH variable
      to it. */
   name = get_bash_name ();
   temp_var = bind_variable ("BASH", name, 0);
   free (name);
   /* Make the exported environment variable SHELL be the user's login
      shell.  Note that the `tset' command looks at this variable
      to determine what style of commands to output; if it ends in "csh",
      then C-shell commands are output, else Bourne shell commands. */
   set_shell_var ();
   /* Make a variable called BASH_VERSION which contains the version info. */
   bind_variable ("BASH_VERSION", shell_version_string (), 0);
 #if defined (ARRAY_VARS)
   make_vers_array ();
 #endif
   if (command_execution_string)
     bind_variable ("BASH_EXECUTION_STRING", command_execution_string, 0);
   /* Find out if we're supposed to be in Posix.2 mode via an
      environment variable. */
   temp_var = find_variable ("POSIXLY_CORRECT");
   if (!temp_var)
     temp_var = find_variable ("POSIX_PEDANTIC");
   if (temp_var && imported_p (temp_var))
     sv_strict_posix (temp_var->name);
 #if defined (HISTORY)
   /* Set history variables to defaults, and then do whatever we would
      do if the variable had just been set.  Do this only in the case
      that we are remembering commands on the history list. */
   if (remember_on_history)
     {
       name = bash_tilde_expand (posixly_correct ? "~/.sh_history" : "~/.bash_history", 0);
       set_if_not ("HISTFILE", name);
       free (name);
     }
 #endif /* HISTORY */
   /* Seed the random number generators. */
   seedrand ();
   seedrand32 ();
   /* Handle some "special" variables that we may have inherited from a
      parent shell. */
   if (interactive_shell)
     {
       temp_var = find_variable ("IGNOREEOF");
       if (!temp_var)
     temp_var = find_variable ("ignoreeof");
       if (temp_var && imported_p (temp_var))
     sv_ignoreeof (temp_var->name);
     }
 #if defined (HISTORY)
   if (interactive_shell && remember_on_history)
     {
       sv_history_control ("HISTCONTROL");
       sv_histignore ("HISTIGNORE");
       sv_histtimefmt ("HISTTIMEFORMAT");
     }
 #endif /* HISTORY */
 #if defined (READLINE) && defined (STRICT_POSIX)
   /* POSIXLY_CORRECT will be 1 here if the shell was compiled
      -DSTRICT_POSIX or if POSIXLY_CORRECT was supplied in the shell's
      environment */
   if (interactive_shell && posixly_correct && no_line_editing == 0)
     rl_prefer_env_winsize = 1;
 #endif /* READLINE && STRICT_POSIX */
   /* Get the user's real and effective user ids. */
   uidset ();
   temp_var = set_if_not ("BASH_LOADABLES_PATH", DEFAULT_LOADABLE_BUILTINS_PATH);
   temp_var = find_variable ("BASH_XTRACEFD");
   if (temp_var && imported_p (temp_var))
     sv_xtracefd (temp_var->name);
   sv_shcompat ("BASH_COMPAT");
   /* Allow FUNCNEST to be inherited from the environment. */
   sv_funcnest ("FUNCNEST");
   /* Initialize the dynamic variables, and seed their values. */
   initialize_dynamic_variables ();
 }
References _, absolute_program(), array_needs_making, att_exported, att_imported, att_integer, att_invisible, att_readonly, bash_tilde_expand(), BASHFUNC_PREFIX, BASHFUNC_PREFLEN, BASHFUNC_SUFFIX, BASHFUNC_SUFFLEN, bind_invalid_envvar(), bind_variable(), c, CACHE_IMPORTSTR, command_execution_string, create_variable_tables(), current_user, DEFAULT_LOADABLE_BUILTINS_PATH, DEFAULT_PATH_VALUE, dollar_dollar_pid, dollar_vars, env, user_info::euid, EXECUTION_FAILURE, find_function(), find_variable(), FREE, free, function_p, get_bash_name(), get_current_user_info(), getpid(), imported_p, initialize_dynamic_variables(), initialize_shell_level(), interactive_shell, last_command_exit_value, legal_identifier(), login_shell, memcpy, variable::name, namelen, no_line_editing, NULL, parse_and_execute(), posixly_correct, primary_prompt, read_but_dont_execute, readonly_p, remember_on_history, report_error(), rl_prefer_env_winsize, secondary_prompt, seedrand(), seedrand32(), set_argv0(), set_auto_export, set_home_var(), set_if_not(), set_machine_vars(), set_ppid(), set_pwd(), set_shell_var(), setifs(), SEVAL_FUNCDEF, SEVAL_NOHIST, SEVAL_NONINT, SEVAL_ONECMD, sh_opterr, shell_version_string(), STREQ, STREQN, string, strlen(), sv_funcnest(), sv_ignoreeof(), sv_shcompat(), sv_strict_posix(), sv_xtracefd(), user_info::uid, uidset(), VSETATTR, VUNSETATTR, and xmalloc.
Referenced by shell_initialize().
kill_all_local_variables()
void kill_all_local_variables ()
Definition at line 4054 of file variables.c.
 {
   VAR_CONTEXT *vc;
   for (vc = shell_variables; vc; vc = vc->down)
     if (vc_isfuncenv (vc) && vc->scope == variable_context)
       break;
   if (vc == 0)
     return;     /* XXX */
   if (vc->table && vc_haslocals (vc))
     {
       delete_all_variables (vc->table);
       hash_dispose (vc->table);
     }
   vc->table = (HASH_TABLE *)NULL;
 }
References delete_all_variables(), var_context::down, hash_dispose(), NULL, var_context::scope, shell_variables, var_context::table, variable_context, vc_haslocals, and vc_isfuncenv.
local_and_exported()
static int local_and_exported (SHELL_VAR * var) static
Definition at line 4400 of file variables.c.
 {
   return (invisible_p (var) == 0 && local_p (var) && var->context == variable_context && exported_p (var));
 }
References exported_p, invisible_p, local_p, and variable_context.
Referenced by local_exported_variables().
local_exported_variables()
SHELL_VAR** local_exported_variables ()
Definition at line 4413 of file variables.c.
 {
   return (vapply (local_and_exported));
 }
References local_and_exported(), and vapply().
make_env_array_from_var_list()
static char** make_env_array_from_var_list (SHELL_VAR ** vars) static
Definition at line 4887 of file variables.c.
 {
   register int i, list_index;
   register SHELL_VAR *var;
   char **list, *value;
   list = strvec_create ((1 + strvec_len ((char **)vars)));
   for (i = 0, list_index = 0; var = vars[i]; i++)
     {
 #if defined (__CYGWIN__)
       /* We don't use the exportstr stuff on Cygwin at all. */
       INVALIDATE_EXPORTSTR (var);
 #endif
       /* If the value is generated dynamically, generate it here. */
       if (regen_p (var) && var->dynamic_value)
     {
       var = (*(var->dynamic_value)) (var);
       INVALIDATE_EXPORTSTR (var);
     }
       if (var->exportstr)
     value = var->exportstr;
       else if (function_p (var))
     value = named_function_string ((char *)NULL, function_cell (var), 0);
 #if defined (ARRAY_VARS)
       else if (array_p (var))
 #  if ARRAY_EXPORT
     value = array_to_assign (array_cell (var), 0);
 #  else
     continue;   /* XXX array vars cannot yet be exported */
 #  endif /* ARRAY_EXPORT */
       else if (assoc_p (var))
 #  if ARRAY_EXPORT
     value = assoc_to_assign (assoc_cell (var), 0);
 #  else
     continue;   /* XXX associative array vars cannot yet be exported */
 #  endif /* ARRAY_EXPORT */
 #endif
       else
     value = value_cell (var);
       if (value)
     {
       /* Gee, I'd like to get away with not using savestring() if we're
          using the cached exportstr... */
       list[list_index] = USE_EXPORTSTR ? savestring (value)
                        : mk_env_string (var->name, value, var->attributes);
       if (USE_EXPORTSTR == 0)
         SAVE_EXPORTSTR (var, list[list_index]);
       list_index++;
 #undef USE_EXPORTSTR
 #if defined (ARRAY_VARS) && defined (ARRAY_EXPORT)
       if (array_p (var) || assoc_p (var))
         free (value);
 #endif
     }
     }
   list[list_index] = (char *)NULL;
   return (list);
 }
References array_cell, array_p, assoc_cell, assoc_p, free, function_cell, function_p, i, INVALIDATE_EXPORTSTR, list(), mk_env_string(), named_function_string(), NULL, regen_p, SAVE_EXPORTSTR, savestring(), strvec_create(), strvec_len(), USE_EXPORTSTR, value, value_cell, and vars.
Referenced by make_func_export_array(), and make_var_export_array().
make_func_export_array()
static char** make_func_export_array () static
Definition at line 4981 of file variables.c.
 {
   char **list;
   SHELL_VAR **vars;
   vars = map_over_funcs (visible_and_exported);
   if (vars == 0)
     return (char **)NULL;
   list = make_env_array_from_var_list (vars);
   free (vars);
   return (list);
 }
References free, list(), make_env_array_from_var_list(), map_over_funcs(), NULL, vars, and visible_and_exported().
Referenced by maybe_make_export_env().
make_funcname_visible()
void make_funcname_visible (int on_or_off)
Definition at line 1870 of file variables.c.
 {
   SHELL_VAR *v;
   v = find_variable ("FUNCNAME");
   if (v == 0 || v->dynamic_value == 0)
     return;
   if (on_or_off)
     VUNSETATTR (v, att_invisible);
   else
     VSETATTR (v, att_invisible);
 }
References att_invisible, variable::dynamic_value, find_variable(), VSETATTR, and VUNSETATTR.
Referenced by execute_function().
make_local_variable()
SHELL_VAR* make_local_variable (char * name, int flags) const
Definition at line 2607 of file variables.c.
 {
   SHELL_VAR *new_var, *old_var, *old_ref;
   VAR_CONTEXT *vc;
   int was_tmpvar;
   char *old_value;
   /* We don't want to follow the nameref chain when making local variables; we
      just want to create them. */
   old_ref = find_variable_noref (name);
   if (old_ref && nameref_p (old_ref) == 0)
     old_ref = 0;
   /* local foo; local foo;  is a no-op. */
   old_var = find_variable (name);
   if (old_ref == 0 && old_var && local_p (old_var) && old_var->context == variable_context)
     return (old_var);
   /* local -n foo; local -n foo;  is a no-op. */
   if (old_ref && local_p (old_ref) && old_ref->context == variable_context)
     return (old_ref);
   /* From here on, we want to use the refvar, not the variable it references */
   if (old_ref)
     old_var = old_ref;
   was_tmpvar = old_var && tempvar_p (old_var);
   /* If we're making a local variable in a shell function, the temporary env
      has already been merged into the function's variable context stack.  We
      can assume that a temporary var in the same context appears in the same
      VAR_CONTEXT and can safely be returned without creating a new variable
      (which results in duplicate names in the same VAR_CONTEXT->table */
   /* We can't just test tmpvar_p because variables in the temporary env given
      to a shell function appear in the function's local variable VAR_CONTEXT
      but retain their tempvar attribute.  We want temporary variables that are
      found in temporary_env, hence the test for last_table_searched, which is
      set in hash_lookup and only (so far) checked here. */
   if (was_tmpvar && old_var->context == variable_context && last_table_searched != temporary_env)
     {
       VUNSETATTR (old_var, att_invisible);  /* XXX */
       /* We still want to flag this variable as local, though, and set things
          up so that it gets treated as a local variable. */
       new_var = old_var;
       /* Since we found the variable in a temporary environment, this will
      succeed. */
       for (vc = shell_variables; vc; vc = vc->down)
     if (vc_isfuncenv (vc) && vc->scope == variable_context)
       break;
       goto set_local_var_flags;
       return (old_var);
     }
   /* If we want to change to "inherit the old variable's value" semantics,
      here is where to save the old value. */
   old_value = was_tmpvar ? value_cell (old_var) : (char *)NULL;
   for (vc = shell_variables; vc; vc = vc->down)
     if (vc_isfuncenv (vc) && vc->scope == variable_context)
       break;
   if (vc == 0)
     {
       internal_error (_("make_local_variable: no function context at current scope"));
       return ((SHELL_VAR *)NULL);
     }
   else if (vc->table == 0)
     vc->table = hash_create (TEMPENV_HASH_BUCKETS);
   /* Since this is called only from the local/declare/typeset code, we can
      call builtin_error here without worry (of course, it will also work
      for anything that sets this_command_name).  Variables with the `noassign'
      attribute may not be made local.  The test against old_var's context
      level is to disallow local copies of readonly global variables (since I
      believe that this could be a security hole).  Readonly copies of calling
      function local variables are OK. */
   if (old_var && (noassign_p (old_var) ||
          (readonly_p (old_var) && old_var->context == 0)))
     {
       if (readonly_p (old_var))
     sh_readonly (name);
       else if (noassign_p (old_var))
     builtin_error (_("%s: variable may not be assigned value"), name);
 #if 0
       /* Let noassign variables through with a warning */
       if (readonly_p (old_var))
 #endif
     return ((SHELL_VAR *)NULL);
     }
   if (old_var == 0)
     new_var = make_new_variable (name, vc->table);
   else
     {
       new_var = make_new_variable (name, vc->table);
       /* If we found this variable in one of the temporary environments,
      inherit its value.  Watch to see if this causes problems with
      things like `x=4 local x'. XXX - see above for temporary env
      variables with the same context level as variable_context */
       /* XXX - we should only do this if the variable is not an array. */
       /* If we want to change the local variable semantics to "inherit
      the old variable's value" here is where to set it.  And we would
      need to use copy_variable (currently unused) to do it for all
      possible variable values. */
       if (was_tmpvar)
     var_setvalue (new_var, savestring (old_value));
       else if (localvar_inherit || (flags & MKLOC_INHERIT))
     {
       /* This may not make sense for nameref variables that are shadowing
          variables with the same name, but we don't know that yet. */
 #if defined (ARRAY_VARS)
       if (assoc_p (old_var))
         var_setassoc (new_var, assoc_copy (assoc_cell (old_var)));
       else if (array_p (old_var))
         var_setarray (new_var, array_copy (array_cell (old_var)));
       else if (value_cell (old_var))
 #else
       if (value_cell (old_var))
 #endif
         var_setvalue (new_var, savestring (value_cell (old_var)));
       else
         var_setvalue (new_var, (char *)NULL);
     }
       if (localvar_inherit || (flags & MKLOC_INHERIT))
     {
       /* It doesn't make sense to inherit the nameref attribute */
       new_var->attributes = old_var->attributes & ~att_nameref;
       new_var->dynamic_value = old_var->dynamic_value;
       new_var->assign_func = old_var->assign_func;
     }
       else
     /* We inherit the export attribute, but no others. */
     new_var->attributes = exported_p (old_var) ? att_exported : 0;
     }
 set_local_var_flags:
   vc->flags |= VC_HASLOCAL;
   new_var->context = variable_context;
   VSETATTR (new_var, att_local);
   if (ifsname (name))
     setifs (new_var);
   /* value_cell will be 0 if localvar_inherit == 0 or there was no old variable
      with the same name or the old variable was invisible */
   if (was_tmpvar == 0 && value_cell (new_var) == 0)
     VSETATTR (new_var, att_invisible);  /* XXX */
   return (new_var);
 }
References _, array_cell, array_p, variable::assign_func, assoc_cell, assoc_copy, assoc_p, att_exported, att_invisible, att_local, att_nameref, variable::attributes, builtin_error(), variable::context, var_context::down, variable::dynamic_value, exported_p, find_variable(), find_variable_noref(), var_context::flags, flags, hash_create(), ifsname, internal_error(), last_table_searched, local_p, localvar_inherit, make_new_variable(), MKLOC_INHERIT, nameref_p, noassign_p, NULL, readonly_p, savestring(), var_context::scope, setifs(), sh_readonly(), shell_variables, var_context::table, TEMPENV_HASH_BUCKETS, temporary_env, tempvar_p, value_cell, var_setarray, var_setassoc, var_setvalue, variable_context, VC_HASLOCAL, vc_isfuncenv, VSETATTR, and VUNSETATTR.
make_new_variable()
static SHELL_VAR* make_new_variable (char * name, HASH_TABLE * table) const static
Definition at line 2790 of file variables.c.
 {
   SHELL_VAR *entry;
   BUCKET_CONTENTS *elt;
   entry = new_shell_variable (name);
   /* Make sure we have a shell_variables hash table to add to. */
   if (shell_variables == 0)
     create_variable_tables ();
   elt = hash_insert (savestring (name), table, HASH_NOSRCH);
   elt->data = (PTR_T)entry;
   return entry;
 }
References create_variable_tables(), bucket_contents::data, hash_insert(), HASH_NOSRCH, new_shell_variable(), PTR_T, savestring(), shell_variables, and table.
Referenced by assign_in_env(), bind_variable_internal(), and make_local_variable().
make_var_export_array()
static char** make_var_export_array (VAR_CONTEXT * vcxt) static
Definition at line 4959 of file variables.c.
 {
   char **list;
   SHELL_VAR **vars;
 #if 0
   vars = map_over (visible_and_exported, vcxt);
 #else
   vars = map_over (export_environment_candidate, vcxt);
 #endif
   if (vars == 0)
     return (char **)NULL;
   list = make_env_array_from_var_list (vars);
   free (vars);
   return (list);
 }
References export_environment_candidate(), free, list(), make_env_array_from_var_list(), map_over(), NULL, vars, and visible_and_exported().
Referenced by maybe_make_export_env().
make_variable_value()
char* make_variable_value (SHELL_VAR * var, char * value, int flags)
Definition at line 2924 of file variables.c.
 {
   char *retval, *oval;
   intmax_t lval, rval;
   int expok, olen, op;
   /* If this variable has had its type set to integer (via `declare -i'),
      then do expression evaluation on it and store the result.  The
      functions in expr.c (evalexp()) and bind_int_variable() are responsible
      for turning off the integer flag if they don't want further
      evaluation done.  Callers that find it inconvenient to do this can set
      the ASS_NOEVAL flag.  For the special case of arithmetic expression
      evaluation, the caller can set ASS_NOLONGJMP to avoid jumping out to
      top_level. */
   if ((flags & ASS_NOEVAL) == 0 && integer_p (var))
     {
       if (flags & ASS_APPEND)
     {
       oval = value_cell (var);
       lval = evalexp (oval, 0, &expok); /* ksh93 seems to do this */
       if (expok == 0)
         {
           if (flags & ASS_NOLONGJMP)
         goto make_value;
           else
         {
           top_level_cleanup ();
           jump_to_top_level (DISCARD);
         }
         }
     }
       rval = evalexp (value, 0, &expok);
       if (expok == 0)
     {
       if (flags & ASS_NOLONGJMP)
         goto make_value;
       else
         {
           top_level_cleanup ();
           jump_to_top_level (DISCARD);
         }
     }
       /* This can be fooled if the variable's value changes while evaluating
      `rval'.  We can change it if we move the evaluation of lval to here. */
       if (flags & ASS_APPEND)
     rval += lval;
       retval = itos (rval);
     }
 #if defined (CASEMOD_ATTRS)
   else if ((flags & ASS_NOEVAL) == 0 && (capcase_p (var) || uppercase_p (var) || lowercase_p (var)))
     {
       if (flags & ASS_APPEND)
     {
       oval = get_variable_value (var);
       if (oval == 0)    /* paranoia */
         oval = "";
       olen = STRLEN (oval);
       retval = (char *)xmalloc (olen + (value ? STRLEN (value) : 0) + 1);
       strcpy (retval, oval);
       if (value)
         strcpy (retval+olen, value);
     }
       else if (*value)
     retval = savestring (value);
       else
     {
       retval = (char *)xmalloc (1);
       retval[0] = '\0';
     }
       op = capcase_p (var) ? CASE_CAPITALIZE
              : (uppercase_p (var) ? CASE_UPPER : CASE_LOWER);
       oval = sh_modcase (retval, (char *)0, op);
       free (retval);
       retval = oval;
     }
 #endif /* CASEMOD_ATTRS */
   else if (value)
     {
 make_value:
       if (flags & ASS_APPEND)
     {
       oval = get_variable_value (var);
       if (oval == 0)    /* paranoia */
         oval = "";
       olen = STRLEN (oval);
       retval = (char *)xmalloc (olen + (value ? STRLEN (value) : 0) + 1);
       strcpy (retval, oval);
       if (value)
         strcpy (retval+olen, value);
     }
       else if (*value)
     retval = savestring (value);
       else
     {
       retval = (char *)xmalloc (1);
       retval[0] = '\0';
     }
     }
   else
     retval = (char *)NULL;
   return retval;
 }
References ASS_APPEND, ASS_NOEVAL, ASS_NOLONGJMP, capcase_p, CASE_CAPITALIZE, CASE_LOWER, CASE_UPPER, DISCARD, evalexp(), flags, free, get_variable_value(), integer_p, itos(), jump_to_top_level(), lowercase_p, NULL, retval, savestring(), sh_modcase(), strcpy, STRLEN, top_level_cleanup(), uppercase_p, value, value_cell, and xmalloc.
Referenced by assign_in_env(), bind_variable_internal(), and bind_variable_value().
makunbound()
int makunbound (char * name, VAR_CONTEXT * vc) const
Definition at line 3977 of file variables.c.
 {
   BUCKET_CONTENTS *elt, *new_elt;
   SHELL_VAR *old_var;
   VAR_CONTEXT *v;
   char *t;
   for (elt = (BUCKET_CONTENTS *)NULL, v = vc; v; v = v->down)
     if (elt = hash_remove (name, v->table, 0))
       break;
   if (elt == 0)
     return (-1);
   old_var = (SHELL_VAR *)elt->data;
   if (old_var && exported_p (old_var))
     array_needs_making++;
   /* If we're unsetting a local variable and we're still executing inside
      the function, just mark the variable as invisible.  The function
      eventually called by pop_var_context() will clean it up later.  This
      must be done so that if the variable is subsequently assigned a new
      value inside the function, the `local' attribute is still present.
      We also need to add it back into the correct hash table. */
   if (old_var && local_p (old_var) &&
     (old_var->context == variable_context || (localvar_unset && old_var->context < variable_context)))
     {
       if (nofree_p (old_var))
     var_setvalue (old_var, (char *)NULL);
 #if defined (ARRAY_VARS)
       else if (array_p (old_var))
     array_dispose (array_cell (old_var));
       else if (assoc_p (old_var))
     assoc_dispose (assoc_cell (old_var));
 #endif
       else if (nameref_p (old_var))
     FREE (nameref_cell (old_var));
       else
     FREE (value_cell (old_var));
       /* Reset the attributes.  Preserve the export attribute if the variable
      came from a temporary environment.  Make sure it stays local, and
      make it invisible. */
       old_var->attributes = (exported_p (old_var) && tempvar_p (old_var)) ? att_exported : 0;
       VSETATTR (old_var, att_local);
       VSETATTR (old_var, att_invisible);
       var_setvalue (old_var, (char *)NULL);
       INVALIDATE_EXPORTSTR (old_var);
       new_elt = hash_insert (savestring (old_var->name), v->table, 0);
       new_elt->data = (PTR_T)old_var;
       stupidly_hack_special_variables (old_var->name);
       free (elt->key);
       free (elt);
       return (0);
     }
   /* Have to save a copy of name here, because it might refer to
      old_var->name.  If so, stupidly_hack_special_variables will
      reference freed memory. */
   t = savestring (name);
   free (elt->key);
   free (elt);
   dispose_variable (old_var);
   stupidly_hack_special_variables (t);
   free (t);
   return (0);
 }
References array_cell, array_needs_making, array_p, assoc_cell, assoc_p, att_exported, att_invisible, att_local, variable::attributes, variable::context, bucket_contents::data, dispose_variable(), var_context::down, exported_p, FREE, free, hash_insert(), hash_remove(), if(), INVALIDATE_EXPORTSTR, bucket_contents::key, local_p, localvar_unset, variable::name, nameref_cell, nameref_p, nofree_p, NULL, PTR_T, savestring(), stupidly_hack_special_variables(), t, var_context::table, tempvar_p, value_cell, var_setvalue, variable_context, and VSETATTR.
Referenced by unbind_global_variable(), unbind_global_variable_noref(), unbind_nameref(), unbind_variable(), and unbind_variable_noref().
map_over()
SHELL_VAR** map_over (sh_var_map_func_t * function, VAR_CONTEXT * vc)
Definition at line 4220 of file variables.c.
 {
   VAR_CONTEXT *v;
   VARLIST *vlist;
   SHELL_VAR **ret;
   int nentries;
   for (nentries = 0, v = vc; v; v = v->down)
     nentries += HASH_ENTRIES (v->table);
   if (nentries == 0)
     return (SHELL_VAR **)NULL;
   vlist = vlist_alloc (nentries);
   for (v = vc; v; v = v->down)
     flatten (v->table, function, vlist, 0);
   ret = vlist->list;
   free (vlist);
   return ret;
 }
References var_context::down, flatten(), free, HASH_ENTRIES, _vlist::list, NULL, var_context::table, and vlist_alloc().
Referenced by make_var_export_array(), and vapply().
map_over_funcs()
SHELL_VAR** map_over_funcs (sh_var_map_func_t * function)
Definition at line 4246 of file variables.c.
 {
   VARLIST *vlist;
   SHELL_VAR **ret;
   if (shell_functions == 0 || HASH_ENTRIES (shell_functions) == 0)
     return ((SHELL_VAR **)NULL);
   vlist = vlist_alloc (HASH_ENTRIES (shell_functions));
   flatten (shell_functions, function, vlist, 0);
   ret = vlist->list;
   free (vlist);
   return ret;
 }
References flatten(), free, HASH_ENTRIES, _vlist::list, NULL, shell_functions, and vlist_alloc().
Referenced by fapply(), and make_func_export_array().
maybe_make_export_env()
void maybe_make_export_env ()
Definition at line 5109 of file variables.c.
 {
   register char **temp_array;
   int new_size;
   VAR_CONTEXT *tcxt, *icxt;
   if (array_needs_making)
     {
       if (export_env)
     strvec_flush (export_env);
       /* Make a guess based on how many shell variables and functions we
      have.  Since there will always be array variables, and array
      variables are not (yet) exported, this will always be big enough
      for the exported variables and functions. */
       new_size = n_shell_variables () + HASH_ENTRIES (shell_functions) + 1 +
          HASH_ENTRIES (temporary_env) + HASH_ENTRIES (invalid_env);
       if (new_size > export_env_size)
     {
       export_env_size = new_size;
       export_env = strvec_resize (export_env, export_env_size);
       environ = export_env;
     }
       export_env[export_env_index = 0] = (char *)NULL;
       /* Make a dummy variable context from the temporary_env, stick it on
      the front of shell_variables, call make_var_export_array on the
      whole thing to flatten it, and convert the list of SHELL_VAR *s
      to the form needed by the environment. */
       if (temporary_env)
     {
       tcxt = new_var_context ((char *)NULL, 0);
       tcxt->table = temporary_env;
       tcxt->down = shell_variables;
     }
       else
     tcxt = shell_variables;
       if (invalid_env)
     {
       icxt = new_var_context ((char *)NULL, 0);
       icxt->table = invalid_env;
       icxt->down = tcxt;
     }
       else
     icxt = tcxt;
       temp_array = make_var_export_array (icxt);
       if (temp_array)
     add_temp_array_to_env (temp_array, 0, 0);
       if (icxt != tcxt)
     free (icxt);
       if (tcxt != shell_variables)
     free (tcxt);
 #if defined (RESTRICTED_SHELL)
       /* Restricted shells may not export shell functions. */
       temp_array = restricted ? (char **)0 : make_func_export_array ();
 #else
       temp_array = make_func_export_array ();
 #endif
       if (temp_array)
     add_temp_array_to_env (temp_array, 0, 0);
       array_needs_making = 0;
     }
 }
References add_temp_array_to_env(), array_needs_making, var_context::down, environ, export_env, export_env_index, export_env_size, free, HASH_ENTRIES, invalid_env, make_func_export_array(), make_var_export_array(), n_shell_variables(), new_var_context(), NULL, shell_functions, shell_variables, strvec_flush(), strvec_resize(), var_context::table, and temporary_env.
Referenced by chkexport(), command_substitute(), dispose_used_env_vars(), execute_disk_command(), execute_simple_command(), execute_subshell_builtin_or_function(), printenv_builtin(), and reset_locale_vars().
merge_function_temporary_env()
void merge_function_temporary_env ()
Definition at line 4730 of file variables.c.
 {
   if (temporary_env)
     dispose_temporary_env (push_temp_var);
 }
References dispose_temporary_env(), push_temp_var(), and temporary_env.
merge_temporary_env()
void merge_temporary_env ()
Definition at line 4721 of file variables.c.
 {
   if (temporary_env)
     dispose_temporary_env (posixly_correct ? push_posix_temp_var : push_temp_var);
 }
References dispose_temporary_env(), posixly_correct, push_posix_temp_var(), push_temp_var(), and temporary_env.
Referenced by execute_builtin(), execute_simple_command(), and push_var_context().
mk_env_string()
static char* mk_env_string (char * name, char * value, int attributes) const inline static
Definition at line 4754 of file variables.c.
 {
   size_t name_len, value_len;
   char  *p, *q, *t;
   int isfunc, isarray;
   name_len = strlen (name);
   value_len = STRLEN (value);
   isfunc = attributes & att_function;
 #if defined (ARRAY_VARS) && defined (ARRAY_EXPORT)
   isarray = attributes & (att_array|att_assoc);
 #endif
   /* If we are exporting a shell function, construct the encoded function
      name. */
   if (isfunc && value)
     {
       p = (char *)xmalloc (BASHFUNC_PREFLEN + name_len + BASHFUNC_SUFFLEN + value_len + 2);
       q = p;
       memcpy (q, BASHFUNC_PREFIX, BASHFUNC_PREFLEN);
       q += BASHFUNC_PREFLEN;
       memcpy (q, name, name_len);
       q += name_len;
       memcpy (q, BASHFUNC_SUFFIX, BASHFUNC_SUFFLEN);
       q += BASHFUNC_SUFFLEN;
     }
 #if defined (ARRAY_VARS) && defined (ARRAY_EXPORT)
   else if (isarray && value)
     {
       if (attributes & att_assoc)
     p = (char *)xmalloc (BASHASSOC_PREFLEN + name_len + BASHASSOC_SUFFLEN + value_len + 2);
       else
     p = (char *)xmalloc (BASHARRAY_PREFLEN + name_len + BASHARRAY_SUFFLEN + value_len + 2);
       q = p;
       if (attributes & att_assoc)
     {
       memcpy (q, BASHASSOC_PREFIX, BASHASSOC_PREFLEN);
       q += BASHASSOC_PREFLEN;
     }
       else
     {
       memcpy (q, BASHARRAY_PREFIX, BASHARRAY_PREFLEN);
       q += BASHARRAY_PREFLEN;
     }
       memcpy (q, name, name_len);
       q += name_len;
       /* These are actually the same currently */
       if (attributes & att_assoc)
         {
       memcpy (q, BASHASSOC_SUFFIX, BASHASSOC_SUFFLEN);
       q += BASHARRAY_SUFFLEN;
         }
       else
         {
       memcpy (q, BASHARRAY_SUFFIX, BASHARRAY_SUFFLEN);
       q += BASHARRAY_SUFFLEN;
         }
     }
 #endif
   else
     {
       p = (char *)xmalloc (2 + name_len + value_len);
       memcpy (p, name, name_len);
       q = p + name_len;
     }
   q[0] = '=';
   if (value && *value)
     {
       if (isfunc)
     {
       t = dequote_escapes (value);
       value_len = STRLEN (t);
       memcpy (q + 1, t, value_len + 1);
       free (t);
     }
       else
     memcpy (q + 1, value, value_len + 1);
     }
   else
     q[1] = '\0';
   return (p);
 }
References att_array, att_assoc, att_function, attributes, BASHFUNC_PREFIX, BASHFUNC_PREFLEN, BASHFUNC_SUFFIX, BASHFUNC_SUFFLEN, dequote_escapes(), free, memcpy, p, strlen(), STRLEN, t, value, and xmalloc.
Referenced by assign_in_env(), and make_env_array_from_var_list().
n_shell_variables()
static int n_shell_variables () static
Definition at line 5082 of file variables.c.
 {
   VAR_CONTEXT *vc;
   int n;
   for (n = 0, vc = shell_variables; vc; vc = vc->down)
     n += HASH_ENTRIES (vc->table);
   return n;
 }
References var_context::down, HASH_ENTRIES, n, shell_variables, and var_context::table.
Referenced by maybe_make_export_env().
nameref_transform_name()
char* nameref_transform_name (char * name, int flags)
Definition at line 2317 of file variables.c.
 {
   SHELL_VAR *v;
   char *newname;
   v = 0;
   if (flags & ASS_MKLOCAL)
     {
       v = find_variable_last_nameref (name, 1);
       /* If we're making local variables, only follow namerefs that point to
      non-existent variables at the same variable context. */
       if (v && v->context != variable_context)
     v = 0;
     }
   else if (flags & ASS_MKGLOBAL)
     v = (flags & ASS_CHKLOCAL) ? find_variable_last_nameref (name, 1)
                    : find_global_variable_last_nameref (name, 1);
   if (v && nameref_p (v) && valid_nameref_value (nameref_cell (v), 1))
     return nameref_cell (v);
   return name;
 }
References ASS_CHKLOCAL, ASS_MKGLOBAL, ASS_MKLOCAL, variable::context, find_global_variable_last_nameref(), find_variable_last_nameref(), flags, nameref_cell, nameref_p, valid_nameref_value(), and variable_context.
new_shell_variable()
static SHELL_VAR* new_shell_variable (char * name) const static
Definition at line 2763 of file variables.c.
 {
   SHELL_VAR *entry;
   entry = (SHELL_VAR *)xmalloc (sizeof (SHELL_VAR));
   entry->name = savestring (name);
   var_setvalue (entry, (char *)NULL);
   CLEAR_EXPORTSTR (entry);
   entry->dynamic_value = (sh_var_value_func_t *)NULL;
   entry->assign_func = (sh_var_assign_func_t *)NULL;
   entry->attributes = 0;
   /* Always assume variables are to be made at toplevel!
      make_local_variable has the responsibility of changing the
      variable context. */
   entry->context = 0;
   return (entry);
 }
References CLEAR_EXPORTSTR, NULL, savestring(), var_setvalue, and xmalloc.
Referenced by bind_function(), and make_new_variable().
new_var_context()
VAR_CONTEXT* new_var_context (char * name, int flags)
Definition at line 5221 of file variables.c.
 {
   VAR_CONTEXT *vc;
   vc = (VAR_CONTEXT *)xmalloc (sizeof (VAR_CONTEXT));
   vc->name = name ? savestring (name) : (char *)NULL;
   vc->scope = variable_context;
   vc->flags = flags;
   vc->up = vc->down = (VAR_CONTEXT *)NULL;
   vc->table = (HASH_TABLE *)NULL;
   return vc;
 }
References var_context::down, var_context::flags, flags, var_context::name, NULL, savestring(), var_context::scope, var_context::table, var_context::up, variable_context, and xmalloc.
Referenced by create_variable_tables(), maybe_make_export_env(), and push_var_context().
null_assign()
static SHELL_VAR* null_assign (SHELL_VAR * self, char * value, arrayind_t unused, char * key) static
Definition at line 1240 of file variables.c.
 {
   return (self);
 }
Referenced by init_funcname_var(), and initialize_dynamic_variables().
optimized_assignment()
static SHELL_VAR* optimized_assignment (SHELL_VAR * entry, char * value, int aflags) static
Definition at line 3053 of file variables.c.
 {
   size_t len, vlen;
   char *v, *new;
   v = value_cell (entry);
   len = STRLEN (v);
   vlen = STRLEN (value);
   new = (char *)xrealloc (v, len + vlen + 8);   /* for now */
   if (vlen == 1)
     {
       new[len] = *value;
       new[len+1] = '\0';
     }
   else
     strcpy (new + len, value);
   var_setvalue (entry, new);
   return entry;
 }
References len, strcpy, STRLEN, value, value_cell, var_setvalue, and xrealloc.
Referenced by bind_variable_internal().
PARAMS() [1/25]
static void add_temp_array_to_env PARAMS ((char **, int, int)) static
PARAMS() [2/25]
static SHELL_VAR* new_shell_variable PARAMS ((const char *)) static
PARAMS() [3/25]
static SHELL_VAR* bind_tempenv_variable PARAMS ((const char *, char *)) static
PARAMS() [4/25]
static SHELL_VAR* bind_variable_internal PARAMS ((const char *, char *, HASH_TABLE *, int, int)) static
PARAMS() [5/25]
static SHELL_VAR* bind_invalid_envvar PARAMS ((const char *, char *, int)) static
PARAMS() [6/25]
static char* mk_env_string PARAMS ((const char *, const char *, int)) inline static
PARAMS() [7/25]
static SHELL_VAR* hash_lookup PARAMS ((const char *, HASH_TABLE *)) static
PARAMS() [8/25]
static SHELL_VAR* find_variable_internal PARAMS ((const char *, int)) static
PARAMS() [9/25]
static void flatten PARAMS ((HASH_TABLE *, sh_var_map_func_t *, VARLIST *, int)) static
PARAMS() [10/25]
static VARLIST* vlist_alloc PARAMS ((int)) static
PARAMS() [11/25]
static void free_variable_hash_data PARAMS ((PTR_T)) static
PARAMS() [12/25]
static void dispose_temporary_env PARAMS ((sh_free_func_t *)) static
PARAMS() [13/25]
static SHELL_VAR** vapply PARAMS ((sh_var_map_func_t *)) static
PARAMS() [14/25]
static SHELL_VAR* get_self PARAMS ((SHELL_VAR *)) static
PARAMS() [15/25]
static char** make_env_array_from_var_list PARAMS ((SHELL_VAR **)) static
PARAMS() [16/25]
static int qsort_var_comp PARAMS ((SHELL_VAR **, SHELL_VAR **)) static
PARAMS() [17/25]
static SHELL_VAR* null_assign PARAMS ((SHELL_VAR *, char *, arrayind_t, char *)) static
PARAMS() [18/25]
static void push_posix_tempvar_internal PARAMS ((SHELL_VAR *, int)) inline static
PARAMS() [19/25]
static int var_sametype PARAMS ((SHELL_VAR *, SHELL_VAR *)) static
PARAMS() [20/25]
static SHELL_VAR* find_nameref_at_context PARAMS ((SHELL_VAR *, VAR_CONTEXT *)) static
PARAMS() [21/25]
static SHELL_VAR* find_variable_nameref_context PARAMS ((SHELL_VAR *, VAR_CONTEXT *, VAR_CONTEXT **)) static
PARAMS() [22/25]
static char** make_var_export_array PARAMS ((VAR_CONTEXT *)) static
PARAMS() [23/25]
static VARLIST* vlist_realloc PARAMS ((VARLIST *, int)) static
PARAMS() [24/25]
static void vlist_add PARAMS ((VARLIST *, SHELL_VAR *, int)) static
PARAMS() [25/25]
static void create_variable_tables PARAMS ((void)) static
pop_args()
void pop_args ()
Definition at line 5763 of file variables.c.
 {
 #if defined (ARRAY_VARS) && defined (DEBUGGER)
   SHELL_VAR *bash_argv_v, *bash_argc_v;
   ARRAY *bash_argv_a, *bash_argc_a;
   ARRAY_ELEMENT *ce;
   intmax_t i;
   GET_ARRAY_FROM_VAR ("BASH_ARGV", bash_argv_v, bash_argv_a);
   GET_ARRAY_FROM_VAR ("BASH_ARGC", bash_argc_v, bash_argc_a);
   ce = array_unshift_element (bash_argc_a);
   if (ce == 0 || legal_number (element_value (ce), &i) == 0)
     i = 0;
   for ( ; i > 0; i--)
     array_pop (bash_argv_a);
   array_dispose_element (ce);
 #endif /* ARRAY_VARS && DEBUGGER */
 }
References array_pop, element_value, GET_ARRAY_FROM_VAR, i, and legal_number().
Referenced by _evalfile(), execute_function(), and unbind_args().
pop_context()
void pop_context ()
Definition at line 5644 of file variables.c.
 {
   pop_dollar_vars ();
   variable_context--;
   pop_var_context ();
   sv_ifs ("IFS");       /* XXX here for now */
 }
References pop_dollar_vars(), pop_var_context(), sv_ifs(), and variable_context.
Referenced by execute_function().
pop_dollar_vars()
void pop_dollar_vars ()
Definition at line 5676 of file variables.c.
 {
   if (dollar_arg_stack == 0 || dollar_arg_stack_index == 0)
     return;
   /* Wipe out current values */
   clear_dollar_vars ();
   rest_of_args = dollar_arg_stack[--dollar_arg_stack_index].rest;
   restore_dollar_vars (dollar_arg_stack[dollar_arg_stack_index].first_ten);
   free (dollar_arg_stack[dollar_arg_stack_index].first_ten);
   posparam_count = dollar_arg_stack[dollar_arg_stack_index].count;
   dollar_arg_stack[dollar_arg_stack_index].first_ten = (char **)NULL;
   dollar_arg_stack[dollar_arg_stack_index].rest = (WORD_LIST *)NULL;
   dollar_arg_stack[dollar_arg_stack_index].count = 0;
   set_dollar_vars_unchanged ();
   invalidate_cached_quoted_dollar_at ();
 }
References clear_dollar_vars(), saved_dollar_vars::count, dollar_arg_stack, dollar_arg_stack_index, saved_dollar_vars::first_ten, free, invalidate_cached_quoted_dollar_at(), NULL, posparam_count, saved_dollar_vars::rest, rest_of_args, restore_dollar_vars(), and set_dollar_vars_unchanged().
Referenced by pop_context().
pop_scope()
void pop_scope (int is_special)
Definition at line 5516 of file variables.c.
 {
   VAR_CONTEXT *vcxt, *ret;
   int is_bltinenv;
   vcxt = shell_variables;
   if (vc_istempscope (vcxt) == 0)
     {
       internal_error (_("pop_scope: head of shell_variables not a temporary environment scope"));
       return;
     }
   is_bltinenv = vc_isbltnenv (vcxt);    /* XXX - for later */
   ret = vcxt->down;
   if (ret)
     ret->up = (VAR_CONTEXT *)NULL;
   shell_variables = ret;
   /* Now we can take care of merging variables in VCXT into set of scopes
      whose head is RET (shell_variables). */
   FREE (vcxt->name);
   if (vcxt->table)
     {
       if (is_special)
     hash_flush (vcxt->table, push_builtin_var);
       else
     hash_flush (vcxt->table, push_exported_var);
       hash_dispose (vcxt->table);
     }
   free (vcxt);
   sv_ifs ("IFS");   /* XXX here for now */
 }
References _, var_context::down, FREE, free, hash_dispose(), hash_flush(), internal_error(), is_special, var_context::name, NULL, push_builtin_var(), push_exported_var(), shell_variables, sv_ifs(), var_context::table, var_context::up, vc_isbltnenv, and vc_istempscope.
Referenced by execute_builtin().
pop_var_context()
void pop_var_context ()
Definition at line 5409 of file variables.c.
 {
   VAR_CONTEXT *ret, *vcxt;
   vcxt = shell_variables;
   if (vc_isfuncenv (vcxt) == 0)
     {
       internal_error (_("pop_var_context: head of shell_variables not a function context"));
       return;
     }
   if (ret = vcxt->down)
     {
       ret->up = (VAR_CONTEXT *)NULL;
       shell_variables = ret;
       if (vcxt->table)
     hash_flush (vcxt->table, push_func_var);
       dispose_var_context (vcxt);
     }
   else
     internal_error (_("pop_var_context: no global_variables context"));
 }
References _, dispose_var_context(), var_context::down, hash_flush(), internal_error(), NULL, push_func_var(), shell_variables, var_context::table, var_context::up, and vc_isfuncenv.
Referenced by pop_context().
print_assignment()
void print_assignment (SHELL_VAR * var)
Definition at line 1102 of file variables.c.
 {
   if (var_isset (var) == 0)
     return;
   if (function_p (var))
     {
       printf ("%s", var->name);
       print_var_function (var);
       printf ("\n");
     }
 #if defined (ARRAY_VARS)
   else if (array_p (var))
     print_array_assignment (var, 0);
   else if (assoc_p (var))
     print_assoc_assignment (var, 0);
 #endif /* ARRAY_VARS */
   else
     {
       printf ("%s=", var->name);
       print_var_value (var, 1);
       printf ("\n");
     }
 }
References array_p, assoc_p, function_p, print_var_function(), print_var_value(), printf, and var_isset.
Referenced by print_var_list().
print_func_list()
void print_func_list (SHELL_VAR ** list)
Definition at line 1084 of file variables.c.
 {
   register int i;
   register SHELL_VAR *var;
   for (i = 0; list && (var = list[i]); i++)
     {
       printf ("%s ", var->name);
       print_var_function (var);
       printf ("\n");
     }
 }
References i, list(), print_var_function(), and printf.
print_var_function()
void print_var_function (SHELL_VAR * var)
Definition at line 1161 of file variables.c.
 {
   char *x;
   if (function_p (var) && var_isset (var))
     {
       x = named_function_string ((char *)NULL, function_cell(var), FUNC_MULTILINE|FUNC_EXTERNAL);
       printf ("%s", x);
     }
 }
References FUNC_EXTERNAL, FUNC_MULTILINE, function_cell, function_p, named_function_string(), NULL, printf, var_isset, and x.
Referenced by print_assignment(), print_func_list(), and printenv_builtin().
print_var_list()
void print_var_list (SHELL_VAR ** list)
Definition at line 1070 of file variables.c.
 {
   register int i;
   register SHELL_VAR *var;
   for (i = 0; list && (var = list[i]); i++)
     if (invisible_p (var) == 0)
       print_assignment (var);
 }
References i, invisible_p, list(), and print_assignment().
print_var_value()
void print_var_value (SHELL_VAR * var, int quote)
Definition at line 1133 of file variables.c.
 {
   char *t;
   if (var_isset (var) == 0)
     return;
   if (quote && posixly_correct == 0 && ansic_shouldquote (value_cell (var)))
     {
       t = ansic_quote (value_cell (var), 0, (int *)0);
       printf ("%s", t);
       free (t);
     }
   else if (quote && sh_contains_shell_metas (value_cell (var)))
     {
       t = sh_single_quote (value_cell (var));
       printf ("%s", t);
       free (t);
     }
   else
     printf ("%s", value_cell (var));
 }
References ansic_quote(), ansic_shouldquote(), free, posixly_correct, printf, quote, sh_contains_shell_metas(), sh_single_quote(), t, value_cell, and var_isset.
Referenced by print_assignment(), and printenv_builtin().
propagate_temp_var()
static void propagate_temp_var (PTR_T data) static
Definition at line 4654 of file variables.c.
 {
   SHELL_VAR *var;
   var = (SHELL_VAR *)data;
   if (tempvar_p (var) && (var->attributes & att_propagate))
     push_temp_var (data);
   else
     {
       if (find_special_var (var->name) >= 0)
     tempvar_list[tvlist_ind++] = savestring (var->name);
       dispose_variable (var);
     }
 }
References att_propagate, dispose_variable(), find_special_var(), push_temp_var(), savestring(), tempvar_list, tempvar_p, and tvlist_ind.
Referenced by dispose_used_env_vars().
push_args()
void push_args (WORD_LIST * list)
Definition at line 5737 of file variables.c.
 {
 #if defined (ARRAY_VARS) && defined (DEBUGGER)
   SHELL_VAR *bash_argv_v, *bash_argc_v;
   ARRAY *bash_argv_a, *bash_argc_a;
   WORD_LIST *l;
   arrayind_t i;
   char *t;
   GET_ARRAY_FROM_VAR ("BASH_ARGV", bash_argv_v, bash_argv_a);
   GET_ARRAY_FROM_VAR ("BASH_ARGC", bash_argc_v, bash_argc_a);
   for (l = list, i = 0; l; l = l->next, i++)
     array_push (bash_argv_a, l->word->word);
   t = itos (i);
   array_push (bash_argc_a, t);
   free (t);
 #endif /* ARRAY_VARS && DEBUGGER */
 }
References array_push, free, GET_ARRAY_FROM_VAR, i, itos(), l, list(), and t.
Referenced by bind_args(), execute_function(), and save_bash_argv().
push_builtin_var()
static void push_builtin_var (PTR_T data) static
Definition at line 5397 of file variables.c.
 {
   SHELL_VAR *var;
   var = (SHELL_VAR *)data;
   push_posix_tempvar_internal (var, 1);
 }
References push_posix_tempvar_internal().
Referenced by pop_scope().
push_context()
void push_context (char * name, int is_subshell, HASH_TABLE * tempvars)
Definition at line 5630 of file variables.c.
 {
   if (is_subshell == 0)
     push_dollar_vars ();
   variable_context++;
   push_var_context (name, VC_FUNCENV, tempvars);
 }
References push_dollar_vars(), push_var_context(), variable_context, and VC_FUNCENV.
Referenced by execute_function().
push_dollar_vars()
void push_dollar_vars ()
Definition at line 5655 of file variables.c.
 {
   if (dollar_arg_stack_index + 2 > dollar_arg_stack_slots)
     {
       dollar_arg_stack = (struct saved_dollar_vars *)
     xrealloc (dollar_arg_stack, (dollar_arg_stack_slots += 10)
           * sizeof (struct saved_dollar_vars));
     }
   dollar_arg_stack[dollar_arg_stack_index].count = posparam_count;
   dollar_arg_stack[dollar_arg_stack_index].first_ten = save_dollar_vars ();
   dollar_arg_stack[dollar_arg_stack_index++].rest = rest_of_args;
   rest_of_args = (WORD_LIST *)NULL;
   posparam_count = 0;
   dollar_arg_stack[dollar_arg_stack_index].first_ten = (char **)NULL;
   dollar_arg_stack[dollar_arg_stack_index].rest = (WORD_LIST *)NULL;
 }
References saved_dollar_vars::count, dollar_arg_stack, dollar_arg_stack_index, dollar_arg_stack_slots, saved_dollar_vars::first_ten, NULL, posparam_count, saved_dollar_vars::rest, rest_of_args, save_dollar_vars(), and xrealloc.
Referenced by push_context().
push_exported_var()
static void push_exported_var (PTR_T data) static
Definition at line 5481 of file variables.c.
 {
   SHELL_VAR *var, *v;
   var = (SHELL_VAR *)data;
   /* If a temp var had its export attribute set, or it's marked to be
      propagated, bind it in the previous scope before disposing it. */
   /* XXX - This isn't exactly right, because all tempenv variables have the
     export attribute set. */
   if (tempvar_p (var) && exported_p (var) && (var->attributes & att_propagate))
     {
       var->attributes &= ~att_tempvar;      /* XXX */
       v = bind_variable_internal (var->name, value_cell (var), shell_variables->table, 0, 0);
       if (shell_variables == global_variables)
     var->attributes &= ~att_propagate;
       if (v)
     {
       v->attributes |= var->attributes;
       v->context = shell_variables->scope;
     }
     }
   else
     stupidly_hack_special_variables (var->name);    /* XXX */
   dispose_variable (var);
 }
References att_propagate, att_tempvar, variable::attributes, bind_variable_internal(), variable::context, dispose_variable(), exported_p, global_variables, var_context::scope, shell_variables, stupidly_hack_special_variables(), var_context::table, tempvar_p, and value_cell.
Referenced by pop_scope().
push_func_var()
static void push_func_var (PTR_T data) static
Definition at line 5387 of file variables.c.
 {
   SHELL_VAR *var;
   var = (SHELL_VAR *)data;
   push_posix_tempvar_internal (var, 0);
 }
References push_posix_tempvar_internal().
Referenced by pop_var_context().
push_posix_temp_var()
static void push_posix_temp_var (PTR_T data) static
Definition at line 4552 of file variables.c.
 {
   SHELL_VAR *var, *v;
   HASH_TABLE *binding_table;
   var = (SHELL_VAR *)data;
   /* Just like do_assignment_internal(). This makes assignments preceding
      special builtins act like standalone assignment statements when in
      posix mode, satisfying the posix requirement that this affect the
      "current execution environment." */
   v = bind_variable (var->name, value_cell (var), ASS_FORCE|ASS_NOLONGJMP);
   /* XXX - do we need to worry about array variables here? */
   /* If this modifies an existing local variable, v->context will be non-zero.
      If it comes back with v->context == 0, we bound at the global context.
      Set binding_table appropriately. It doesn't matter whether it's correct
      if the variable is local, only that it's not global_variables->table */
   binding_table = v->context ? shell_variables->table : global_variables->table;
   /* global variables are no longer temporary and don't need propagating. */
   if (v->context == 0)
     var->attributes &= ~(att_tempvar|att_propagate);
   if (v)
     {
       v->attributes |= var->attributes;     /* preserve tempvar attribute if appropriate */
       /* If we don't bind a local variable, propagate the value. If we bind a
      local variable (the "current execution environment"), keep it as local
      and don't propagate it to the calling environment. */
       if (v->context > 0 && local_p (v) == 0)
     v->attributes |= att_propagate;
       else
     v->attributes &= ~att_propagate;
     }
   if (find_special_var (var->name) >= 0)
     tempvar_list[tvlist_ind++] = savestring (var->name);
   dispose_variable (var);
 }
References ASS_FORCE, ASS_NOLONGJMP, att_propagate, att_tempvar, variable::attributes, bind_variable(), variable::context, dispose_variable(), find_special_var(), global_variables, local_p, savestring(), shell_variables, var_context::table, tempvar_list, tvlist_ind, and value_cell.
Referenced by merge_temporary_env().
push_posix_tempvar_internal()
static void push_posix_tempvar_internal (SHELL_VAR * var, int isbltin) inline static
Definition at line 5314 of file variables.c.
 {
   SHELL_VAR *v;
   int posix_var_behavior;
   /* As of IEEE Std 1003.1-2017, assignment statements preceding shell
      functions no longer behave like assignment statements preceding
      special builtins, and do not persist in the current shell environment.
      This is austin group interp #654, though nobody implements it yet. */
   posix_var_behavior = posixly_correct && isbltin;
   v = 0;
   if (local_p (var) && STREQ (var->name, "-"))
     {
       set_current_options (value_cell (var));
       set_shellopts ();
     }
   /* This takes variable assignments preceding special builtins that can execute
      multiple commands (source, eval, etc.) and performs the equivalent of
      an assignment statement to modify the closest enclosing variable (the
      posix "current execution environment"). This makes the behavior the same
      as push_posix_temp_var; but the circumstances of calling are slightly
      different. */
   else if (tempvar_p (var) && posix_var_behavior)
     {
       /* similar to push_posix_temp_var */
       v = bind_variable (var->name, value_cell (var), ASS_FORCE|ASS_NOLONGJMP);
       if (v)
     {
       v->attributes |= var->attributes;
       if (v->context == 0)
         v->attributes &= ~(att_tempvar|att_propagate);
       /* XXX - set att_propagate here if v->context > 0? */
     }
     }
   else if (tempvar_p (var) && propagate_p (var))
     {
       /* Make sure we have a hash table to store the variable in while it is
      being propagated down to the global variables table.  Create one if
      we have to */
       if ((vc_isfuncenv (shell_variables) || vc_istempenv (shell_variables)) && shell_variables->table == 0)
     shell_variables->table = hash_create (VARIABLES_HASH_BUCKETS);
       v = bind_variable_internal (var->name, value_cell (var), shell_variables->table, 0, 0);
       /* XXX - should we set v->context here? */
       if (v)
     v->context = shell_variables->scope;
       if (shell_variables == global_variables)
     var->attributes &= ~(att_tempvar|att_propagate);
       else
     shell_variables->flags |= VC_HASTMPVAR;
       if (v)
     v->attributes |= var->attributes;
     }
   else
     stupidly_hack_special_variables (var->name);    /* XXX */
 #if defined (ARRAY_VARS)
   if (v && (array_p (var) || assoc_p (var)))
     {
       FREE (value_cell (v));
       if (array_p (var))
     var_setarray (v, array_copy (array_cell (var)));
       else
     var_setassoc (v, assoc_copy (assoc_cell (var)));
     }
 #endif
   dispose_variable (var);
 }
References array_cell, array_p, ASS_FORCE, ASS_NOLONGJMP, assoc_cell, assoc_copy, assoc_p, att_propagate, att_tempvar, variable::attributes, bind_variable(), bind_variable_internal(), variable::context, dispose_variable(), var_context::flags, FREE, global_variables, hash_create(), local_p, posixly_correct, propagate_p, var_context::scope, shell_variables, STREQ, stupidly_hack_special_variables(), var_context::table, tempvar_p, value_cell, var_setarray, var_setassoc, VARIABLES_HASH_BUCKETS, VC_HASTMPVAR, vc_isfuncenv, and vc_istempenv.
Referenced by push_builtin_var(), and push_func_var().
push_scope()
VAR_CONTEXT* push_scope (int flags, HASH_TABLE * tmpvars)
Definition at line 5473 of file variables.c.
 {
   return (push_var_context ((char *)NULL, flags, tmpvars));
 }
References flags, NULL, and push_var_context().
Referenced by execute_builtin().
push_temp_var()
static void push_temp_var (PTR_T data) static
Definition at line 4607 of file variables.c.
 {
   SHELL_VAR *var, *v;
   HASH_TABLE *binding_table;
   var = (SHELL_VAR *)data;
   binding_table = shell_variables->table;
   if (binding_table == 0)
     {
       if (shell_variables == global_variables)
     /* shouldn't happen */
     binding_table = shell_variables->table = global_variables->table = hash_create (VARIABLES_HASH_BUCKETS);
       else
     binding_table = shell_variables->table = hash_create (TEMPENV_HASH_BUCKETS);
     }
   v = bind_variable_internal (var->name, value_cell (var), binding_table, 0, ASS_FORCE|ASS_NOLONGJMP);
   /* XXX - should we set the context here?  It shouldn't matter because of how
      assign_in_env works, but we do it anyway. */
   if (v)
     v->context = shell_variables->scope;
   if (binding_table == global_variables->table)     /* XXX */
     var->attributes &= ~(att_tempvar|att_propagate);
   else
     {
       var->attributes |= att_propagate;         /* XXX - propagate more than once? */
       if  (binding_table == shell_variables->table)
     shell_variables->flags |= VC_HASTMPVAR;
     }
   if (v)
     v->attributes |= var->attributes;
   if (find_special_var (var->name) >= 0)
     tempvar_list[tvlist_ind++] = savestring (var->name);
   dispose_variable (var);
 }
References ASS_FORCE, ASS_NOLONGJMP, att_propagate, att_tempvar, variable::attributes, bind_variable_internal(), variable::context, dispose_variable(), find_special_var(), var_context::flags, global_variables, hash_create(), savestring(), var_context::scope, shell_variables, var_context::table, TEMPENV_HASH_BUCKETS, tempvar_list, tvlist_ind, value_cell, VARIABLES_HASH_BUCKETS, and VC_HASTMPVAR.
Referenced by merge_function_temporary_env(), merge_temporary_env(), and propagate_temp_var().
push_var_context()
VAR_CONTEXT* push_var_context (char * name, int flags, HASH_TABLE * tempvars)
Definition at line 5267 of file variables.c.
 {
   VAR_CONTEXT *vc;
   int posix_func_behavior;
   /* As of IEEE Std 1003.1-2017, assignment statements preceding shell
      functions no longer behave like assignment statements preceding
      special builtins, and do not persist in the current shell environment.
      This is austin group interp #654, though nobody implements it yet. */
   posix_func_behavior = 0;
   vc = new_var_context (name, flags);
   /* Posix interp 1009, temporary assignments preceding function calls modify
      the current environment *before* the command is executed. */
   if (posix_func_behavior && (flags & VC_FUNCENV) && tempvars == temporary_env)
     merge_temporary_env ();
   else if (tempvars)
     {
       vc->table = tempvars;
       /* Have to do this because the temp environment was created before
      variable_context was incremented. */
       /* XXX - only need to do it if flags&VC_FUNCENV */
       flatten (tempvars, set_context, (VARLIST *)NULL, 0);
       vc->flags |= VC_HASTMPVAR;
     }
   vc->down = shell_variables;
   shell_variables->up = vc;
   return (shell_variables = vc);
 }
References var_context::down, var_context::flags, flags, flatten(), merge_temporary_env(), new_var_context(), NULL, set_context(), shell_variables, var_context::table, temporary_env, var_context::up, VC_FUNCENV, and VC_HASTMPVAR.
Referenced by push_context(), and push_scope().
put_command_name_into_env()
void put_command_name_into_env (char * command_name)
Definition at line 5205 of file variables.c.
 {
   update_export_env_inplace ("_=", 2, command_name);
 }
References update_export_env_inplace().
Referenced by execute_disk_command().
qsort_var_comp()
static int qsort_var_comp (SHELL_VAR ** var1, SHELL_VAR ** var2) static
Definition at line 4306 of file variables.c.
 {
   int result;
   if ((result = (*var1)->name[0] - (*var2)->name[0]) == 0)
     result = strcmp ((*var1)->name, (*var2)->name);
   return (result);
 }
References strcmp.
Referenced by sort_variables().
reinit_special_variables()
void reinit_special_variables ()
Definition at line 5947 of file variables.c.
 {
 #if defined (READLINE)
   sv_comp_wordbreaks ("COMP_WORDBREAKS");
 #endif
   sv_globignore ("GLOBIGNORE");
   sv_opterr ("OPTERR");
 }
References sv_globignore(), and sv_opterr().
Referenced by shell_reinitialize().
reset_local_contexts()
void reset_local_contexts ()
Definition at line 5459 of file variables.c.
 {
   delete_local_contexts (shell_variables);
   shell_variables = global_variables;
   variable_context = 0;
 }
References delete_local_contexts(), global_variables, shell_variables, and variable_context.
Referenced by parse_and_execute(), and reader_loop().
restore_dollar_vars()
static void restore_dollar_vars (char ** args) static
Definition at line 5586 of file variables.c.
 {
   int i;
   for (i = 1; i < 10; i++)
     dollar_vars[i] = args[i];
 }
References dollar_vars, and i.
Referenced by pop_dollar_vars().
save_bash_argv()
void save_bash_argv ()
Definition at line 5725 of file variables.c.
 {
   WORD_LIST *list;
   list = list_rest_of_args ();
   push_args (list);
   dispose_words (list);
 }
References dispose_words(), list(), list_rest_of_args(), and push_args().
Referenced by init_bash_argv().
save_dollar_vars()
static char** save_dollar_vars () static
Definition at line 5571 of file variables.c.
 {
   char **ret;
   int i;
   ret = strvec_create (10);
   for (i = 1; i < 10; i++)
     {
       ret[i] = dollar_vars[i];
       dollar_vars[i] = (char *)NULL;
     }
   return ret;
 }
References dollar_vars, i, NULL, and strvec_create().
Referenced by push_dollar_vars().
set_argv0()
static void set_argv0 () static
Definition at line 1579 of file variables.c.
 {
   SHELL_VAR *v;
   v = find_variable ("BASH_ARGV0");
   if (v && imported_p (v))
     assign_bash_argv0 (v, value_cell (v), 0, 0);
 }
References assign_bash_argv0(), find_variable(), imported_p, and value_cell.
Referenced by initialize_shell_variables().
set_context()
static int set_context (SHELL_VAR * var) static
Definition at line 5257 of file variables.c.
 {
   return (var->context = variable_context);
 }
References variable_context.
Referenced by push_var_context().
set_home_var()
static void set_home_var () static
Definition at line 746 of file variables.c.
 {
   SHELL_VAR *temp_var;
   temp_var = find_variable ("HOME");
   if (temp_var == 0)
     temp_var = bind_variable ("HOME", sh_get_home_dir (), 0);
 #if 0
   VSETATTR (temp_var, att_exported);
 #endif
 }
References att_exported, bind_variable(), find_variable(), sh_get_home_dir(), and VSETATTR.
Referenced by initialize_shell_variables().
set_if_not()
SHELL_VAR* set_if_not (char * name, char * value)
Definition at line 2591 of file variables.c.
 {
   SHELL_VAR *v;
   if (shell_variables == 0)
     create_variable_tables ();
   v = find_variable (name);
   if (v == 0)
     v = bind_variable_internal (name, value, global_variables->table, HASH_NOSRCH, 0);
   return (v);
 }
References bind_variable_internal(), create_variable_tables(), find_variable(), global_variables, HASH_NOSRCH, shell_variables, var_context::table, and value.
Referenced by initialize_shell_variables(), and set_machine_vars().
set_int_value()
static SHELL_VAR * set_int_value (SHELL_VAR * var, intmax_t value, int flags) inline static
Definition at line 1314 of file variables.c.
 {
   char *p;
   p = itos (value);
   FREE (value_cell (var));
   var_setvalue (var, p);
   if (flags & 1)
     VSETATTR (var, att_integer);
   return (var);
 }
References att_integer, flags, FREE, itos(), p, value, value_cell, var_setvalue, and VSETATTR.
Referenced by assign_lineno(), assign_random(), assign_seconds(), get_bashpid(), get_epochseconds(), get_lineno(), get_random(), get_seconds(), get_subshell(), and get_urandom().
set_machine_vars()
static void set_machine_vars () static
Definition at line 721 of file variables.c.
 {
   SHELL_VAR *temp_var;
   temp_var = set_if_not ("HOSTTYPE", HOSTTYPE);
   temp_var = set_if_not ("OSTYPE", OSTYPE);
   temp_var = set_if_not ("MACHTYPE", MACHTYPE);
   temp_var = set_if_not ("HOSTNAME", current_host_name);
 }
References current_host_name, HOSTTYPE, MACHTYPE, OSTYPE, and set_if_not().
Referenced by initialize_shell_variables().
set_pipestatus_from_exit()
void set_pipestatus_from_exit (int s)
Definition at line 6478 of file variables.c.
 {
 #if defined (ARRAY_VARS)
   static int v[2] = { 0, -1 };
   v[0] = s;
   set_pipestatus_array (v, 1);
 #endif
 }
References s.
Referenced by execute_command_internal(), execute_simple_command(), exp_jump_to_top_level(), parse_and_execute(), report_syntax_error(), set_exit_status(), sigint_sighandler(), and throw_to_top_level().
set_ppid()
void set_ppid ()
Definition at line 973 of file variables.c.
 {
   char namebuf[INT_STRLEN_BOUND(pid_t) + 1], *name;
   SHELL_VAR *temp_var;
   name = inttostr (getppid (), namebuf, sizeof(namebuf));
   temp_var = find_variable ("PPID");
   if (temp_var)
     VUNSETATTR (temp_var, (att_readonly | att_exported));
   temp_var = bind_variable ("PPID", name, 0);
   VSETATTR (temp_var, (att_readonly | att_integer));
 }
References att_exported, att_integer, att_readonly, bind_variable(), find_variable(), getppid(), INT_STRLEN_BOUND, inttostr(), VSETATTR, and VUNSETATTR.
Referenced by initialize_shell_variables(), and push_builtin().
set_pwd()
void set_pwd ()
Definition at line 910 of file variables.c.
 {
   SHELL_VAR *temp_var, *home_var;
   char *temp_string, *home_string, *current_dir;
   home_var = find_variable ("HOME");
   home_string = home_var ? value_cell (home_var) : (char *)NULL;
   temp_var = find_variable ("PWD");
   /* Follow posix rules for importing PWD */
   if (temp_var && imported_p (temp_var) &&
       (temp_string = value_cell (temp_var)) &&
       temp_string[0] == '/' &&
       same_file (temp_string, ".", (struct stat *)NULL, (struct stat *)NULL))
     {
       current_dir = sh_canonpath (temp_string, PATH_CHECKDOTDOT|PATH_CHECKEXISTS);
       if (current_dir == 0)
     current_dir = get_working_directory ("shell_init");
       else
     set_working_directory (current_dir);
       if (posixly_correct && current_dir)
     {
       temp_var = bind_variable ("PWD", current_dir, 0);
       set_auto_export (temp_var);
     }
       free (current_dir);
     }
   else if (home_string && interactive_shell && login_shell &&
        same_file (home_string, ".", (struct stat *)NULL, (struct stat *)NULL))
     {
       set_working_directory (home_string);
       temp_var = bind_variable ("PWD", home_string, 0);
       set_auto_export (temp_var);
     }
   else
     {
       temp_string = get_working_directory ("shell-init");
       if (temp_string)
     {
       temp_var = bind_variable ("PWD", temp_string, 0);
       set_auto_export (temp_var);
       free (temp_string);
     }
     }
   /* According to the Single Unix Specification, v2, $OLDPWD is an
      `environment variable' and therefore should be auto-exported.  If we
      don't find OLDPWD in the environment, or it doesn't name a directory,
      make a dummy invisible variable for OLDPWD, and mark it as exported. */
   temp_var = find_variable ("OLDPWD");
 #if defined (OLDPWD_CHECK_DIRECTORY)
   if (temp_var == 0 || value_cell (temp_var) == 0 || file_isdir (value_cell (temp_var)) == 0)
 #else
   if (temp_var == 0 || value_cell (temp_var) == 0)
 #endif
     {
       temp_var = bind_variable ("OLDPWD", (char *)NULL, 0);
       VSETATTR (temp_var, (att_exported | att_invisible));
     }
 }
References att_exported, att_invisible, bind_variable(), file_isdir(), find_variable(), free, get_working_directory(), imported_p, interactive_shell, login_shell, NULL, PATH_CHECKDOTDOT, PATH_CHECKEXISTS, posixly_correct, same_file(), set_auto_export, set_working_directory(), sh_canonpath(), value_cell, and VSETATTR.
Referenced by initialize_shell_variables().
set_shell_var()
static void set_shell_var () static
Definition at line 761 of file variables.c.
 {
   SHELL_VAR *temp_var;
   temp_var = find_variable ("SHELL");
   if (temp_var == 0)
     {
       if (current_user.shell == 0)
     get_current_user_info ();
       temp_var = bind_variable ("SHELL", current_user.shell, 0);
     }
 #if 0
   VSETATTR (temp_var, att_exported);
 #endif
 }
References att_exported, bind_variable(), current_user, find_variable(), get_current_user_info(), user_info::shell, and VSETATTR.
Referenced by initialize_shell_variables().
set_string_value()
static SHELL_VAR * set_string_value (SHELL_VAR * var, const char * value, int flags) inline static
Definition at line 1327 of file variables.c.
 {
   char *p;
   if (value && *value)
     p = savestring (value);
   else
     {
       p = (char *)xmalloc (1);
       p[0] = '\0';
     }
   FREE (value_cell (var));
   var_setvalue (var, p);
   return (var);
 }
References FREE, p, savestring(), value, value_cell, var_setvalue, and xmalloc.
Referenced by get_bash_argv0(), get_bash_command(), get_epochrealtime(), and get_funcname().
set_var_read_only()
void set_var_read_only (char * name)
Definition at line 4111 of file variables.c.
 {
   SHELL_VAR *entry;
   FIND_OR_MAKE_VARIABLE (name, entry);
   VSETATTR (entry, att_readonly);
 }
References att_readonly, FIND_OR_MAKE_VARIABLE, and VSETATTR.
sh_get_env_value()
char* sh_get_env_value (char * v) const
Definition at line 2541 of file variables.c.
 {
   return get_string_value (v);
 }
References get_string_value().
sh_get_home_dir()
char* sh_get_home_dir (void)
Definition at line 738 of file variables.c.
 {
   if (current_user.home_dir == 0)
     get_current_user_info ();
   return current_user.home_dir;
 }
References current_user, endpwent(), get_current_user_info(), getlogin(), getpwnam, getpwuid(), getuid, user_info::home_dir, NULL, and savestring().
Referenced by set_home_var(), and tilde_expand_word().
sh_set_lines_and_columns()
void sh_set_lines_and_columns (int lines, int cols)
Definition at line 1043 of file variables.c.
 {
   char val[INT_STRLEN_BOUND(int) + 1], *v;
 #if defined (READLINE)
   /* If we are currently assigning to LINES or COLUMNS, don't do anything. */
   if (winsize_assignment)
     return;
 #endif
   v = inttostr (lines, val, sizeof (val));
   bind_variable ("LINES", v, 0);
   v = inttostr (cols, val, sizeof (val));
   bind_variable ("COLUMNS", v, 0);
 }
References bind_variable(), cols, INT_STRLEN_BOUND, inttostr(), lines, putenv(), putenv_buf1, putenv_buf2, setenv(), setenv_buf, sprintf(), and val.
Referenced by _rl_get_screen_size(), and get_new_window_size().
sort_variables()
void sort_variables (SHELL_VAR ** array)
Definition at line 4299 of file variables.c.
 {
   qsort (array, strvec_len ((char **)array), sizeof (SHELL_VAR *), (QSFUNC *)qsort_var_comp);
 }
References qsort(), qsort_var_comp(), and strvec_len().
Referenced by all_local_variables(), fapply(), and vapply().
stupidly_hack_special_variables()
void stupidly_hack_special_variables (char * name)
Definition at line 5926 of file variables.c.
 {
   static int sv_sorted = 0;
   int i;
   if (sv_sorted == 0)   /* shouldn't need, but it's fairly cheap. */
     {
       qsort (special_vars, N_SPECIAL_VARS, sizeof (special_vars[0]),
         (QSFUNC *)sv_compare);
       sv_sorted = 1;
     }
   i = find_special_var (name);
   if (i != -1)
     (*(special_vars[i].function)) (name);
 }
References find_special_var(), name_and_function::function, i, N_SPECIAL_VARS, name_and_function::name, qsort(), special_vars, and sv_compare().
Referenced by assign_in_env(), dispose_temporary_env(), do_assignment_internal(), execute_for_command(), expr_bind_variable(), makunbound(), parameter_brace_expand_rhs(), push_exported_var(), push_posix_tempvar_internal(), and redir_varassign().
sv_compare()
static int sv_compare (struct name_and_function * sv1, struct name_and_function * sv2) static
Definition at line 5892 of file variables.c.
 {
   int r;
   if ((r = sv1->name[0] - sv2->name[0]) == 0)
     r = strcmp (sv1->name, sv2->name);
   return r;
 }
References name_and_function::name, and strcmp.
Referenced by stupidly_hack_special_variables().
sv_execignore()
void sv_execignore (char * name)
Definition at line 6013 of file variables.c.
 {
   setup_exec_ignore (name);
 }
References name_and_function::name, and setup_exec_ignore().
sv_funcnest()
void sv_funcnest (char * name)
Definition at line 5996 of file variables.c.
 {
   SHELL_VAR *v;
   intmax_t num;
   v = find_variable (name);
   if (v == 0)
     funcnest_max = 0;
   else if (legal_number (value_cell (v), &num) == 0)
     funcnest_max = 0;
   else
     funcnest_max = num;
 }
References find_variable(), funcnest_max, legal_number(), name_and_function::name, num, and value_cell.
Referenced by initialize_shell_variables().
sv_globignore()
void sv_globignore (char * name)
Definition at line 6021 of file variables.c.
 {
   if (privileged_mode == 0)
     setup_glob_ignore (name);
 }
References name_and_function::name, privileged_mode, and setup_glob_ignore().
Referenced by reinit_special_variables().
sv_ifs()
void sv_ifs (char * name)
Definition at line 5957 of file variables.c.
 {
   SHELL_VAR *v;
   v = find_variable ("IFS");
   setifs (v);
 }
References find_variable(), and setifs().
Referenced by heredoc_expand(), pop_context(), pop_scope(), and redirection_expand().
sv_ignoreeof()
void sv_ignoreeof (char * name)
Definition at line 6262 of file variables.c.
 {
   SHELL_VAR *tmp_var;
   char *temp;
   eof_encountered = 0;
   tmp_var = find_variable (name);
   ignoreeof = tmp_var && var_isset (tmp_var);
   temp = tmp_var ? value_cell (tmp_var) : (char *)NULL;
   if (temp)
     eof_encountered_limit = (*temp && all_digits (temp)) ? atoi (temp) : 10;
   set_shellopts (); /* make sure `ignoreeof' is/is not in $SHELLOPTS */
 }
References all_digits(), atoi(), eof_encountered, eof_encountered_limit, find_variable(), ignoreeof, name_and_function::name, NULL, value_cell, and var_isset.
Referenced by initialize_shell_variables().
sv_locale()
void sv_locale (char * name)
Definition at line 6333 of file variables.c.
 {
   char *v;
   int r;
   v = get_string_value (name);
   if (name[0] == 'L' && name[1] == 'A') /* LANG */
     r = set_lang (name, v);
   else
     r = set_locale_var (name, v);       /* LC_*, TEXTDOMAIN* */
 #if 1
   if (r == 0 && posixly_correct)
     set_exit_status (EXECUTION_FAILURE);
 #endif
 }
References EXECUTION_FAILURE, get_string_value(), name_and_function::name, posixly_correct, set_exit_status(), set_lang(), and set_locale_var().
sv_mail()
void sv_mail (char * name)
Definition at line 5979 of file variables.c.
 {
   /* If the time interval for checking the files has changed, then
      reset the mail timer.  Otherwise, one of the pathname vars
      to the users mailbox has changed, so rebuild the array of
      filenames. */
   if (name[4] == 'C')  /* if (strcmp (name, "MAILCHECK") == 0) */
     reset_mail_timer ();
   else
     {
       free_mail_files ();
       remember_mail_dates ();
     }
 }
References free_mail_files(), name_and_function::name, remember_mail_dates(), and reset_mail_timer().
sv_opterr()
void sv_opterr (char * name)
Definition at line 6307 of file variables.c.
 {
   char *tt;
   tt = get_string_value ("OPTERR");
   sh_opterr = (tt && *tt) ? atoi (tt) : 1;
 }
References atoi(), get_string_value(), sh_opterr, and tt.
Referenced by reinit_special_variables().
sv_optind()
void sv_optind (char * name)
Definition at line 6279 of file variables.c.
 {
   SHELL_VAR *var;
   char *tt;
   int s;
   var = find_variable ("OPTIND");
   tt = var ? get_variable_value (var) : (char *)NULL;
   /* Assume that if var->context < variable_context and variable_context > 0
      then we are restoring the variables's previous state while returning
      from a function. */
   if (tt && *tt)
     {
       s = atoi (tt);
       /* According to POSIX, setting OPTIND=1 resets the internal state
      of getopt (). */
       if (s < 0 || s == 1)
     s = 0;
     }
   else
     s = 0;
   getopts_reset (s);
 }
References atoi(), find_variable(), get_variable_value(), NULL, s, and tt.
sv_path()
void sv_path (char * name)
Definition at line 5968 of file variables.c.
 {
   /* hash -r */
   phash_flush ();
 }
References phash_flush().
sv_shcompat()
void sv_shcompat (char * name)
Definition at line 6527 of file variables.c.
 {
   SHELL_VAR *v;
   char *val;
   int tens, ones, compatval;
   v = find_variable (name);
   if (v == 0)
     {
       shell_compatibility_level = DEFAULT_COMPAT_LEVEL;
       set_compatibility_opts ();
       return;
     }
   val = value_cell (v);
   if (val == 0 || *val == '\0')
     {
       shell_compatibility_level = DEFAULT_COMPAT_LEVEL;
       set_compatibility_opts ();
       return;
     }
   /* Handle decimal-like compatibility version specifications: 4.2 */
   if (ISDIGIT (val[0]) && val[1] == '.' && ISDIGIT (val[2]) && val[3] == 0)
     {
       tens = val[0] - '0';
       ones = val[2] - '0';
       compatval = tens*10 + ones;
     }
   /* Handle integer-like compatibility version specifications: 42 */
   else if (ISDIGIT (val[0]) && ISDIGIT (val[1]) && val[2] == 0)
     {
       tens = val[0] - '0';
       ones = val[1] - '0';
       compatval = tens*10 + ones;
     }
   else
     {
 compat_error:
       internal_error (_("%s: %s: compatibility value out of range"), name, val);
       shell_compatibility_level = DEFAULT_COMPAT_LEVEL;
       set_compatibility_opts ();
       return;
     }
   if (compatval < MIN_COMPAT_LEVEL || compatval > DEFAULT_COMPAT_LEVEL)
     goto compat_error;
   shell_compatibility_level = compatval;
   set_compatibility_opts ();
 }
References _, find_variable(), internal_error(), ISDIGIT, name_and_function::name, shell_compatibility_level, val, and value_cell.
Referenced by initialize_shell_variables().
sv_strict_posix()
void sv_strict_posix (char * name)
Definition at line 6317 of file variables.c.
 {
   SHELL_VAR *var;
   var = find_variable (name);
   posixly_correct = var && var_isset (var);
   posix_initialize (posixly_correct);
 #if defined (READLINE)
   if (interactive_shell)
     posix_readline_initialize (posixly_correct);
 #endif /* READLINE */
   set_shellopts (); /* make sure `posix' is/is not in $SHELLOPTS */
 }
References find_variable(), interactive_shell, name_and_function::name, posix_initialize(), posixly_correct, and var_isset.
Referenced by initialize_shell_variables(), and main().
sv_xtracefd()
void sv_xtracefd (char * name)
Definition at line 6490 of file variables.c.
 {
   SHELL_VAR *v;
   char *t, *e;
   int fd;
   FILE *fp;
   v = find_variable (name);
   if (v == 0)
     {
       xtrace_reset ();
       return;
     }
   t = value_cell (v);
   if (t == 0 || *t == 0)
     xtrace_reset ();
   else
     {
       fd = (int)strtol (t, &e, 10);
       if (e != t && *e == '\0' && sh_validfd (fd))
     {
       fp = fdopen (fd, "w");
       if (fp == 0)
         internal_error (_("%s: %s: cannot open as FILE"), name, value_cell (v));
       else
         xtrace_set (fd, fp);
     }
       else
     internal_error (_("%s: %s: invalid value for trace file descriptor"), name, value_cell (v));
     }
 }
References _, fd, find_variable(), internal_error(), name_and_function::name, sh_validfd(), strtol(), t, value_cell, xtrace_reset(), and xtrace_set().
Referenced by initialize_shell_variables().
uidset()
static void uidset () static
Definition at line 987 of file variables.c.
 {
   char buff[INT_STRLEN_BOUND(uid_t) + 1], *b;
   register SHELL_VAR *v;
   b = inttostr (current_user.uid, buff, sizeof (buff));
   v = find_variable ("UID");
   if (v == 0)
     {
       v = bind_variable ("UID", b, 0);
       VSETATTR (v, (att_readonly | att_integer));
     }
   if (current_user.euid != current_user.uid)
     b = inttostr (current_user.euid, buff, sizeof (buff));
   v = find_variable ("EUID");
   if (v == 0)
     {
       v = bind_variable ("EUID", b, 0);
       VSETATTR (v, (att_readonly | att_integer));
     }
 }
References att_integer, att_readonly, bind_variable(), current_user, user_info::euid, find_variable(), INT_STRLEN_BOUND, inttostr(), user_info::uid, and VSETATTR.
Referenced by initialize_shell_variables().
unbind_func()
int unbind_func (char * name) const
Definition at line 3895 of file variables.c.
 {
   BUCKET_CONTENTS *elt;
   SHELL_VAR *func;
   elt = hash_remove (name, shell_functions, 0);
   if (elt == 0)
     return -1;
 #if defined (PROGRAMMABLE_COMPLETION)
   set_itemlist_dirty (&it_functions);
 #endif
   func = (SHELL_VAR *)elt->data;
   if (func)
     {
       if (exported_p (func))
     array_needs_making++;
       dispose_variable (func);
     }
   free (elt->key);
   free (elt);
   return 0;
 }
References array_needs_making, bucket_contents::data, dispose_variable(), exported_p, free, hash_remove(), if(), it_functions, bucket_contents::key, and shell_functions.
unbind_global_variable()
int unbind_global_variable (char * name) const
Definition at line 3846 of file variables.c.
 {
   SHELL_VAR *v, *nv;
   int r;
   v = var_lookup (name, global_variables);
   /* This starts at the current scope, just like find_global_variable; should we
      use find_global_variable_nameref here? */
   nv = (v && nameref_p (v)) ? find_variable_nameref (v) : (SHELL_VAR *)NULL;
   r = nv ? makunbound (nv->name, shell_variables) : makunbound (name, global_variables);
   return r;
 }
References find_variable_nameref(), global_variables, makunbound(), variable::name, nameref_p, NULL, shell_variables, and var_lookup().
unbind_global_variable_noref()
int unbind_global_variable_noref (char * name) const
Definition at line 3862 of file variables.c.
 {
   SHELL_VAR *v;
   v = var_lookup (name, global_variables);
   if (v)
     return makunbound (name, global_variables);
   return 0;
 }
References global_variables, makunbound(), and var_lookup().
unbind_nameref()
int unbind_nameref (char * name) const
Definition at line 3821 of file variables.c.
 {
   SHELL_VAR *v;
   v = var_lookup (name, shell_variables);
   if (v && nameref_p (v))
     return makunbound (name, shell_variables);
   return 0;
 }
References makunbound(), nameref_p, shell_variables, and var_lookup().
unbind_variable()
int unbind_variable (char * name) const
Definition at line 3806 of file variables.c.
 {
   SHELL_VAR *v, *nv;
   int r;
   v = var_lookup (name, shell_variables);
   nv = (v && nameref_p (v)) ? find_variable_nameref (v) : (SHELL_VAR *)NULL;
   r = nv ? makunbound (nv->name, shell_variables) : makunbound (name, shell_variables);
   return r;
 }
References find_variable_nameref(), makunbound(), variable::name, nameref_p, NULL, shell_variables, and var_lookup().
Referenced by accept_builtin(), builtin_unbind_variable(), check_mail(), check_unbind_variable(), enable_mypid_builtin_unload(), execute_for_command(), main(), and stat_builtin().
unbind_variable_noref()
int unbind_variable_noref (char * name) const
Definition at line 3834 of file variables.c.
 {
   SHELL_VAR *v;
   v = var_lookup (name, shell_variables);
   if (v)
     return makunbound (name, shell_variables);
   return 0;
 }
References makunbound(), shell_variables, and var_lookup().
update_export_env_inplace()
void update_export_env_inplace (char * env_prefix, int preflen, char * value)
Definition at line 5189 of file variables.c.
 {
   char *evar;
   evar = (char *)xmalloc (STRLEN (value) + preflen + 1);
   strcpy (evar, env_prefix);
   if (value)
     strcpy (evar + preflen, value);
   export_env = add_or_supercede_exported_var (evar, 0);
 }
References add_or_supercede_exported_var(), export_env, strcpy, STRLEN, value, and xmalloc.
Referenced by put_command_name_into_env().
validate_inherited_value()
int validate_inherited_value (SHELL_VAR * var, int type)
Definition at line 2575 of file variables.c.
 {
 #if defined (ARRAY_VARS)
   if (type == att_array && assoc_p (var))
     return 0;
   else if (type == att_assoc && array_p (var))
     return 0;
   else
 #endif
   return 1; /* should we run convert_var_to_array here or let the caller? */
 }
References array_p, assoc_p, att_array, att_assoc, and type.
vapply()
static SHELL_VAR** vapply (sh_var_map_func_t * func) static
Definition at line 4320 of file variables.c.
 {
   SHELL_VAR **list;
   list = map_over (func, shell_variables);
   if (list /* && posixly_correct */)
     sort_variables (list);
   return (list);
 }
References list(), map_over(), shell_variables, and sort_variables().
Referenced by all_exported_variables(), all_shell_variables(), all_visible_variables(), and local_exported_variables().
var_lookup()
SHELL_VAR* var_lookup (char * name, VAR_CONTEXT * vcontext) const
Definition at line 2003 of file variables.c.
 {
   VAR_CONTEXT *vc;
   SHELL_VAR *v;
   v = (SHELL_VAR *)NULL;
   for (vc = vcontext; vc; vc = vc->down)
     if (v = hash_lookup (name, vc->table))
       break;
   return v;
 }
References var_context::down, hash_lookup(), NULL, and var_context::table.
Referenced by find_global_variable(), find_global_variable_noref(), find_shell_variable(), find_variable_internal(), unbind_global_variable(), unbind_global_variable_noref(), unbind_nameref(), unbind_variable(), and unbind_variable_noref().
var_sametype()
static int var_sametype (SHELL_VAR * v1, SHELL_VAR * v2) static
Definition at line 2554 of file variables.c.
 {
   if (v1 == 0 || v2 == 0)
     return 0;
 #if defined (ARRAY_VARS)
   else if (assoc_p (v1) && assoc_p (v2))
     return 1;
   else if (array_p (v1) && array_p (v2))
     return 1;
   else if (array_p (v1) || array_p (v2))
     return 0;
   else if (assoc_p (v1) || assoc_p (v2))
     return 0;
 #endif
   else
     return 1;
 }
References array_p, assoc_p, v1, and v2.
variable_in_context()
static int variable_in_context (SHELL_VAR * var) static
Definition at line 4419 of file variables.c.
 {
   return (local_p (var) && var->context == variable_context);
 }
References local_p, and variable_context.
Referenced by all_local_variables().
visible_and_exported()
static int visible_and_exported (SHELL_VAR * var) static
Definition at line 4381 of file variables.c.
 {
   return (invisible_p (var) == 0 && exported_p (var));
 }
References exported_p, and invisible_p.
Referenced by all_exported_variables(), make_func_export_array(), and make_var_export_array().
visible_var()
static int visible_var (SHELL_VAR * var) static
Definition at line 4360 of file variables.c.
 {
   return (invisible_p (var) == 0);
 }
References invisible_p.
Referenced by all_visible_functions(), and all_visible_variables().
visible_variable_in_context()
static int visible_variable_in_context (SHELL_VAR * var) static
Definition at line 4426 of file variables.c.
 {
   return (invisible_p (var) == 0 && local_p (var) && var->context == variable_context);
 }
References invisible_p, local_p, and variable_context.
Referenced by all_local_variables().
vlist_add()
static void vlist_add (VARLIST * vlist, SHELL_VAR * var, int flags) static
Definition at line 4196 of file variables.c.
 {
   register int i;
   for (i = 0; i < vlist->list_len; i++)
     if (STREQ (var->name, vlist->list[i]->name))
       break;
   if (i < vlist->list_len)
     return;
   if (i >= vlist->list_size)
     vlist = vlist_realloc (vlist, vlist->list_size + 16);
   vlist->list[vlist->list_len++] = var;
   vlist->list[vlist->list_len] = (SHELL_VAR *)NULL;
 }
References i, _vlist::list, _vlist::list_len, _vlist::list_size, variable::name, NULL, STREQ, and vlist_realloc().
Referenced by flatten().
vlist_alloc()
static VARLIST* vlist_alloc (int nentries) static
Definition at line 4166 of file variables.c.
 {
   VARLIST  *vlist;
   vlist = (VARLIST *)xmalloc (sizeof (VARLIST));
   vlist->list = (SHELL_VAR **)xmalloc ((nentries + 1) * sizeof (SHELL_VAR *));
   vlist->list_size = nentries;
   vlist->list_len = 0;
   vlist->list[0] = (SHELL_VAR *)NULL;
   return vlist;
 }
References _vlist::list, _vlist::list_len, _vlist::list_size, NULL, and xmalloc.
Referenced by all_local_variables(), map_over(), map_over_funcs(), and vlist_realloc().
vlist_realloc()
static VARLIST* vlist_realloc (VARLIST * vlist, int n) static
Definition at line 4181 of file variables.c.
 {
   if (vlist == 0)
     return (vlist = vlist_alloc (n));
   if (n > vlist->list_size)
     {
       vlist->list_size = n;
       vlist->list = (SHELL_VAR **)xrealloc (vlist->list, (vlist->list_size + 1) * sizeof (SHELL_VAR *));
     }
   return vlist;
 }
References _vlist::list, _vlist::list_size, n, vlist_alloc(), and xrealloc.
Referenced by vlist_add().
Variable Documentation
array_needs_making
int array_needs_making = 1
Definition at line 167 of file variables.c.
Referenced by assign_in_env(), bind_function(), bind_variable_internal(), bind_variable_value(), chkexport(), dispose_temporary_env(), dispose_variable(), initialize_shell_variables(), makunbound(), maybe_make_export_env(), and unbind_func().
dollar_arg_stack
struct saved_dollar_vars* dollar_arg_stack = (struct saved_dollar_vars *)NULL static
Definition at line 5564 of file variables.c.
Referenced by dispose_saved_dollar_vars(), pop_dollar_vars(), and push_dollar_vars().
dollar_arg_stack_index
int dollar_arg_stack_index static
Definition at line 5566 of file variables.c.
Referenced by dispose_saved_dollar_vars(), pop_dollar_vars(), and push_dollar_vars().
dollar_arg_stack_slots
int dollar_arg_stack_slots static
Definition at line 5565 of file variables.c.
Referenced by push_dollar_vars().
dollar_dollar_pid
pid_t dollar_dollar_pid
Definition at line 164 of file variables.c.
Referenced by command_substitute(), execute_pipeline(), initialize_shell_variables(), kill_shell(), param_expand(), parameter_brace_expand_length(), push_builtin(), sh_mktmpfd(), and sh_mktmpname().
dollar_vars
char* dollar_vars[10]
Definition at line 159 of file variables.c.
Referenced by assign_bash_argv0(), bind_args(), expand_word_internal(), free_dollar_vars(), get_bash_argv0(), get_dollar_var_value(), get_name_for_error(), initialize_shell_variables(), list_rest_of_args(), main(), number_of_args(), open_shell_script(), param_expand(), pos_params(), remember_args(), restore_dollar_vars(), save_dollar_vars(), set_bash_input(), set_shell_name(), and shift_args().
environ
char** environ extern
Definition at line 42 of file lib.c.
Referenced by maybe_make_export_env().
export_env
char** export_env = (char **)NULL
Definition at line 176 of file variables.c.
Referenced by add_or_supercede_exported_var(), add_temp_array_to_env(), bperl_builtin(), execute_disk_command(), maybe_make_export_env(), printenv_builtin(), and update_export_env_inplace().
export_env_index
int export_env_index static
Definition at line 177 of file variables.c.
Referenced by add_or_supercede_exported_var(), and maybe_make_export_env().
export_env_size
int export_env_size static
Definition at line 178 of file variables.c.
Referenced by maybe_make_export_env().
global_variables
VAR_CONTEXT* global_variables = (VAR_CONTEXT *)NULL
Definition at line 119 of file variables.c.
Referenced by bind_global_variable(), bind_variable(), bind_variable_internal(), create_variable_tables(), delete_all_contexts(), delete_local_contexts(), find_global_variable(), find_global_variable_noref(), push_exported_var(), push_posix_temp_var(), push_posix_tempvar_internal(), push_temp_var(), reset_local_contexts(), set_if_not(), unbind_global_variable(), and unbind_global_variable_noref().
invalid_env
HASH_TABLE* invalid_env = (HASH_TABLE *)NULL
Definition at line 128 of file variables.c.
Referenced by bind_invalid_envvar(), and maybe_make_export_env().
last_context_searched
VAR_CONTEXT* last_context_searched static
Definition at line 188 of file variables.c.
last_random_value
int last_random_value
Definition at line 1397 of file variables.c.
Referenced by get_random_number(), and sbrand().
last_table_searched
HASH_TABLE* last_table_searched static
Definition at line 187 of file variables.c.
Referenced by find_variable(), find_variable_for_assignment(), find_variable_no_invisible(), hash_lookup(), and make_local_variable().
localvar_inherit
int localvar_inherit = 0
Definition at line 142 of file variables.c.
Referenced by make_local_variable().
localvar_unset
int localvar_unset = 0
Definition at line 147 of file variables.c.
Referenced by makunbound().
nameref_invalid_value
SHELL_VAR nameref_invalid_value
Definition at line 184 of file variables.c.
nameref_maxloop_value
SHELL_VAR nameref_maxloop_value static
Definition at line 185 of file variables.c.
Referenced by bind_variable(), find_nameref_at_context(), find_variable_last_nameref_context(), and find_variable_nameref_context().
posparam_count
int posparam_count = 0
Definition at line 161 of file variables.c.
Referenced by clear_dollar_vars(), number_of_args(), pop_dollar_vars(), push_dollar_vars(), remember_args(), and shift_args().
rest_of_args
WORD_LIST* rest_of_args = (WORD_LIST *)NULL
Definition at line 160 of file variables.c.
Referenced by clear_dollar_vars(), get_dollar_var_value(), list_rest_of_args(), number_of_args(), pop_dollar_vars(), push_dollar_vars(), remember_args(), and shift_args().
seconds_value_assigned
intmax_t seconds_value_assigned static
Definition at line 1346 of file variables.c.
Referenced by assign_seconds(), get_seconds(), and init_seconds_var().
seeded_subshell
int seeded_subshell = 0 static
Definition at line 1398 of file variables.c.
Referenced by assign_random(), and get_random_number().
shell_functions
HASH_TABLE* shell_functions = (HASH_TABLE *)NULL
Definition at line 126 of file variables.c.
Referenced by bind_function(), create_variable_tables(), find_function(), map_over_funcs(), maybe_make_export_env(), shell_reinitialize(), and unbind_func().
shell_level
int shell_level = 0
Definition at line 171 of file variables.c.
Referenced by adjust_shell_level(), get_tty_state(), run_startup_files(), and set_tty_state().
shell_start_time
time_t shell_start_time extern
Definition at line 183 of file shell.c.
Referenced by assign_seconds(), get_seconds(), and main().
shell_variables
VAR_CONTEXT* shell_variables = (VAR_CONTEXT *)NULL
Definition at line 122 of file variables.c.
Referenced by all_local_variables(), bind_global_variable(), bind_variable(), create_variable_tables(), delete_all_contexts(), find_shell_variable(), find_variable_internal(), initialize_subshell(), kill_all_local_variables(), make_local_variable(), make_new_variable(), maybe_make_export_env(), n_shell_variables(), pop_scope(), pop_var_context(), push_exported_var(), push_posix_temp_var(), push_posix_tempvar_internal(), push_temp_var(), push_var_context(), reset_local_contexts(), set_if_not(), shell_reinitialize(), unbind_global_variable(), unbind_nameref(), unbind_variable(), unbind_variable_noref(), and vapply().
shellstart
struct timeval shellstart extern
Definition at line 183 of file shell.c.
Referenced by assign_seconds(), and main().
special_vars
struct name_and_function special_vars[] static
Definition at line 5763 of file variables.c.
Referenced by find_special_var(), and stupidly_hack_special_variables().
static_shell_name
char* static_shell_name = 0 static
Definition at line 1552 of file variables.c.
Referenced by assign_bash_argv0().
tempenv_assign_error
int tempenv_assign_error
Definition at line 155 of file variables.c.
Referenced by do_assignment_statements(), execute_simple_command(), and expand_word_list_internal().
temporary_env
HASH_TABLE* temporary_env = (HASH_TABLE *)NULL
Definition at line 151 of file variables.c.
Referenced by _run_trap_internal(), assign_in_env(), bind_tempenv_variable(), bind_variable(), dispose_temporary_env(), dispose_used_env_vars(), execute_builtin(), execute_function(), execute_simple_command(), find_tempenv_variable(), find_variable_internal(), flush_temporary_env(), make_local_variable(), maybe_make_export_env(), merge_function_temporary_env(), merge_temporary_env(), push_var_context(), reader_loop(), run_pending_traps(), and run_sigchld_trap().
tempvar_list
char** tempvar_list
Definition at line 4544 of file variables.c.
Referenced by dispose_temporary_env(), propagate_temp_var(), push_posix_temp_var(), and push_temp_var().
tvlist_ind
int tvlist_ind
Definition at line 4545 of file variables.c.
Referenced by dispose_temporary_env(), propagate_temp_var(), push_posix_temp_var(), and push_temp_var().
variable_context
int variable_context = 0
Definition at line 138 of file variables.c.
Referenced by all_local_variables(), assign_in_env(), bind_variable_value(), execute_command(), execute_command_internal(), execute_disk_command(), execute_function(), execute_simple_command(), executing_line_number(), find_variable_nameref(), fix_assignment_words(), get_funcname(), initialize_subshell(), kill_all_local_variables(), local_and_exported(), make_local_variable(), makunbound(), nameref_transform_name(), new_var_context(), parse_and_execute(), pop_context(), push_context(), reset_local_contexts(), set_context(), set_dollar_vars_changed(), variable_in_context(), and visible_variable_in_context().