Fennix: Userspace/apps/base/busybox/coreutils/tac.c File Reference
tac.c File Reference
#include "libbb.h"
Data Structures
struct lstring
Functions
int tac_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
lstring
struct lstring
Definition at line 34 of file tac.c.
Data Fields
char buf[1]
int size
Function Documentation
tac_main()
int tac_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 40 of file tac.c.
 {
     char **name;
     FILE *f;
     struct lstring *line = NULL;
     llist_t *list = NULL;
     int retval = EXIT_SUCCESS;
 #if ENABLE_DESKTOP
 /* tac from coreutils 6.9 supports:
        -b, --before
               attach the separator before instead of after
        -r, --regex
               interpret the separator as a regular expression
        -s, --separator=STRING
               use STRING as the separator instead of newline
 We support none, but at least we will complain or handle "--":
 */
     getopt32(argv, "");
     argv += optind;
 #else
     argv++;
 #endif
     if (!*argv)
         *--argv = (char *)"-";
     /* We will read from last file to first */
     name = argv;
     while (*name)
         name++;
     do {
         int ch, i;
         name--;
         f = fopen_or_warn_stdin(*name);
         if (f == NULL) {
             /* error message is printed by fopen_or_warn_stdin */
             retval = EXIT_FAILURE;
             continue;
         }
         errno = i = 0;
         do {
             ch = fgetc(f);
             if (ch != EOF) {
                 if (!(i & 0x7f))
                     /* Grow on every 128th char */
                     line = xrealloc(line, i + 0x7f + sizeof(int) + 1);
                 line->buf[i++] = ch;
             }
             if (ch == '\n' || (ch == EOF && i != 0)) {
                 line = xrealloc(line, i + sizeof(int));
                 line->size = i;
                 llist_add_to(&list, line);
                 line = NULL;
                 i = 0;
             }
         } while (ch != EOF);
         /* fgetc sets errno to ENOENT on EOF, we don't want
          * to warn on this non-error! */
         if (errno && errno != ENOENT) {
             bb_simple_perror_msg(*name);
             retval = EXIT_FAILURE;
         }
     } while (name != argv);
     while (list) {
         line = (struct lstring *)list->data;
         xwrite(STDOUT_FILENO, line->buf, line->size);
         if (ENABLE_FEATURE_CLEAN_UP) {
             free(llist_pop(&list));
         } else {
             list = list->link;
         }
     }
     return retval;
 }
References argv, bb_simple_perror_msg(), ENOENT, EOF, errno, EXIT_FAILURE, EXIT_SUCCESS, f, fgetc, fopen_or_warn_stdin(), free, getopt32(), i, list(), llist_add_to(), llist_pop(), NULL, optind, retval, STDOUT_FILENO, xrealloc, and xwrite().