Fennix: Userspace/mlibc/options/elf/include/link.h File Reference
link.h File Reference
#include <elf.h>
#include <stddef.h>
Data Structures
struct dl_phdr_info
struct link_map
struct r_debug
Functions
int dl_iterate_phdr (int(*callback)(struct dl_phdr_info *, size_t, void *), void *data)
ElfW (Dyn) _DYNAMIC[]
Function Documentation
dl_iterate_phdr()
int dl_iterate_phdr (int(*)(struct dl_phdr_info *, size_t, void *) callback, void * data)
Definition at line 8 of file phdr.cpp.
{
     return __dlapi_iterate_phdr(callback, data);
 }
ElfW()
ElfW (Dyn)
Referenced by __dlapi_iterate_phdr(), find_exidx(), and static_dl_iterate_phdr().