Fennix: Userspace/apps/base/busybox/miscutils/less.c File Reference
less.c File Reference
#include <sched.h>
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define ESC "\033"
#define HIGHLIGHT ESC"[7m"
#define NORMAL ESC"[m"
#define CLEAR ESC"[H"ESC"[J"
#define CLEAR_2_EOL ESC"[K"
#define G (*ptr_to_globals)
#define cur_fline (G.cur_fline)
#define kbd_fd (G.kbd_fd)
#define less_gets_pos (G.less_gets_pos)
#define last_line_pos (G.last_line_pos)
#define max_fline (G.max_fline)
#define max_lineno (G.max_lineno)
#define max_displayed_line (G.max_displayed_line)
#define width (G.width)
#define winch_counter (G.winch_counter)
#define WINCH_COUNTER (*(volatile unsigned *)&winch_counter)
#define eof_error (G.eof_error)
#define readpos (G.readpos)
#define readeof (G.readeof)
#define buffer (G.buffer)
#define flines (G.flines)
#define empty_line_marker (G.empty_line_marker)
#define num_files (G.num_files)
#define current_file (G.current_file)
#define filename (G.filename)
#define files (G.files)
#define num_lines (G.num_lines)
#define num_marks (G.num_marks)
#define mark_lines (G.mark_lines)
#define terminated (G.terminated)
#define term_orig (G.term_orig)
#define term_less (G.term_less)
#define kbd_input (G.kbd_input)
#define INIT_G()
#define MEMPTR(p) ((char*)(p) - 4)
#define LINENO(p) (*(uint32_t*)((p) - 4))
#define fill_match_lines(pos) ((void)0)
#define readbuf bb_common_bufsiz1
Enumerations
enum { MAXLINES = CONFIG_FEATURE_LESS_MAXLINES , TILDES = 1 }
enum {
FLAG_E = 1 << 0 , FLAG_M = 1 << 1 , FLAG_m = 1 << 2 , FLAG_N = 1 << 3 ,
FLAG_TILDE = 1 << 4 , FLAG_I = 1 << 5 , FLAG_F = 1 << 6 , FLAG_S = (1 << 7) * ENABLE_FEATURE_LESS_TRUNCATE ,
FLAG_R = (1 << 8) * ENABLE_FEATURE_LESS_RAW , LESS_STATE_MATCH_BACKWARDS = 1 << 15
}
enum { pattern_valid = 0 }
Functions
static void set_tty_cooked (void)
static void move_cursor (int line, int col)
static void clear_line (void)
static void print_hilite (const char *str)
static void print_statusline (const char *str)
static void restore_tty (void)
static NOINLINE void less_exit (void)
static int at_end (void)
static void read_lines (void)
static void status_print (void)
static void print_lineno (const char *line)
void print_found (const char *line)
static void print_ascii (const char *str)
static void buffer_print (void)
static void buffer_fill_and_print (void)
static void goto_lineno (int target)
static void cap_cur_fline (void)
static void buffer_down (int nlines)
static void buffer_up (int nlines)
static void buffer_to_line (int linenum, int is_lineno)
static void buffer_line (int linenum)
static void buffer_lineno (int lineno)
static void open_file_and_read_lines (void)
static void reinitialize (void)
static int64_t getch_nowait (void)
static int64_t less_getch (int pos)
static char * less_gets (int sz)
static void examine_file (void)
static void change_file (int direction)
static void remove_current_file (void)
static void colon_process (void)
static void number_process (int first_digit)
static void save_input_to_file (void)
static void keypress_process (int keypress)
static void sig_catcher (int sig)
int less_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char controls[] ALIGN1
Macro Definition Documentation
buffer
#define buffer (G.buffer)
Definition at line 257 of file less.c.
CLEAR
#define CLEAR ESC"[H"ESC"[J"
Definition at line 160 of file less.c.
CLEAR_2_EOL
#define CLEAR_2_EOL ESC"[K"
Definition at line 162 of file less.c.
cur_fline
#define cur_fline (G.cur_fline)
Definition at line 243 of file less.c.
current_file
#define current_file (G.current_file)
Definition at line 261 of file less.c.
empty_line_marker
#define empty_line_marker (G.empty_line_marker)
Definition at line 259 of file less.c.
eof_error
#define eof_error (G.eof_error)
Definition at line 254 of file less.c.
ESC
#define ESC "\033"
Definition at line 155 of file less.c.
filename
#define filename (G.filename)
Definition at line 262 of file less.c.
files
#define files (G.files)
Definition at line 263 of file less.c.
fill_match_lines
#define fill_match_lines (pos) ((void)0)
Definition at line 433 of file less.c.
flines
#define flines (G.flines)
Definition at line 258 of file less.c.
G
#define G (*ptr_to_globals)
Definition at line 242 of file less.c.
HIGHLIGHT
#define HIGHLIGHT ESC"[7m"
Definition at line 157 of file less.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    less_gets_pos = -1; \
    empty_line_marker = "~"; \
    current_file = 1; \
    eof_error = 1; \
    terminated = 1; \
    IF_FEATURE_LESS_REGEXP(wanted_match = -1;) \
} while (0)
Definition at line 279 of file less.c.
kbd_fd
#define kbd_fd (G.kbd_fd)
Definition at line 244 of file less.c.
kbd_input
#define kbd_input (G.kbd_input)
Definition at line 278 of file less.c.
last_line_pos
#define last_line_pos (G.last_line_pos)
Definition at line 246 of file less.c.
less_gets_pos
#define less_gets_pos (G.less_gets_pos)
Definition at line 245 of file less.c.
LINENO
#define LINENO (p) (*(uint32_t*)((p) - 4))
Definition at line 294 of file less.c.
mark_lines
#define mark_lines (G.mark_lines)
Definition at line 266 of file less.c.
max_displayed_line
#define max_displayed_line (G.max_displayed_line)
Definition at line 249 of file less.c.
max_fline
#define max_fline (G.max_fline)
Definition at line 247 of file less.c.
max_lineno
#define max_lineno (G.max_lineno)
Definition at line 248 of file less.c.
MEMPTR
#define MEMPTR (p) ((char*)(p) - 4)
Definition at line 293 of file less.c.
NORMAL
#define NORMAL ESC"[m"
Definition at line 158 of file less.c.
num_files
#define num_files (G.num_files)
Definition at line 260 of file less.c.
num_lines
#define num_lines (G.num_lines)
Definition at line 264 of file less.c.
num_marks
#define num_marks (G.num_marks)
Definition at line 265 of file less.c.
readbuf
#define readbuf bb_common_bufsiz1
readeof
#define readeof (G.readeof)
Definition at line 256 of file less.c.
readpos
#define readpos (G.readpos)
Definition at line 255 of file less.c.
term_less
#define term_less (G.term_less)
Definition at line 277 of file less.c.
term_orig
#define term_orig (G.term_orig)
Definition at line 276 of file less.c.
terminated
#define terminated (G.terminated)
Definition at line 275 of file less.c.
width
#define width (G.width)
Definition at line 250 of file less.c.
winch_counter
#define winch_counter (G.winch_counter)
Definition at line 251 of file less.c.
WINCH_COUNTER
#define WINCH_COUNTER (*(volatile unsigned *)&winch_counter)
Definition at line 253 of file less.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAXLINES
TILDES
Definition at line 164 of file less.c.
      {
 /* Absolute max of lines eaten */
     MAXLINES = CONFIG_FEATURE_LESS_MAXLINES,
 /* This many "after the end" lines we will show (at max) */
     TILDES = 1,
 };
anonymous enum
anonymous enum
Enumerator
FLAG_E
FLAG_M
FLAG_m
FLAG_N
FLAG_TILDE
FLAG_I
FLAG_F
FLAG_S
FLAG_R
LESS_STATE_MATCH_BACKWARDS
Definition at line 172 of file less.c.
      {
     FLAG_E = 1 << 0,
     FLAG_M = 1 << 1,
     FLAG_m = 1 << 2,
     FLAG_N = 1 << 3,
     FLAG_TILDE = 1 << 4,
     FLAG_I = 1 << 5,
     FLAG_F = 1 << 6,
     FLAG_S = (1 << 7) * ENABLE_FEATURE_LESS_TRUNCATE,
     FLAG_R = (1 << 8) * ENABLE_FEATURE_LESS_RAW,
 /* hijack command line options variable for internal state vars */
     LESS_STATE_MATCH_BACKWARDS = 1 << 15,
 };
anonymous enum
anonymous enum
Enumerator
pattern_valid
Definition at line 187 of file less.c.
 { pattern_valid = 0 };
Function Documentation
at_end()
static int at_end (void) static
Definition at line 436 of file less.c.
 {
     return (option_mask32 & FLAG_S)
         ? !(cur_fline <= max_fline &&
             max_lineno > LINENO(flines[cur_fline]) + max_displayed_line)
         : !(max_fline > cur_fline + max_displayed_line);
 }
References cur_fline, FLAG_S, flines, LINENO, max_displayed_line, max_fline, max_lineno, and option_mask32.
Referenced by getch_nowait(), read_lines(), and status_print().
buffer_down()
static void buffer_down (int nlines) static
Definition at line 1001 of file less.c.
 {
     if ((option_mask32 & FLAG_S))
         goto_lineno(LINENO(flines[cur_fline]) + nlines);
     else
         cur_fline += nlines;
     read_lines();
     cap_cur_fline();
     buffer_fill_and_print();
 }
References buffer_fill_and_print(), cap_cur_fline(), cur_fline, FLAG_S, flines, goto_lineno(), LINENO, option_mask32, and read_lines().
Referenced by keypress_process(), and number_process().
buffer_fill_and_print()
static void buffer_fill_and_print (void) static
Definition at line 924 of file less.c.
 {
     unsigned i;
 #if ENABLE_FEATURE_LESS_TRUNCATE
     int fpos = cur_fline;
     if (option_mask32 & FLAG_S) {
         /* Go back to the beginning of this line */
         while (fpos && LINENO(flines[fpos]) == LINENO(flines[fpos-1]))
             fpos--;
     }
     i = 0;
     while (i <= max_displayed_line && fpos <= max_fline) {
         int lineno = LINENO(flines[fpos]);
         buffer[i] = flines[fpos];
         i++;
         do {
             fpos++;
         } while ((fpos <= max_fline)
               && (option_mask32 & FLAG_S)
               && lineno == LINENO(flines[fpos])
         );
     }
 #else
     for (i = 0; i <= max_displayed_line && cur_fline + i <= max_fline; i++) {
         buffer[i] = flines[cur_fline + i];
     }
 #endif
     for (; i <= max_displayed_line; i++) {
         buffer[i] = empty_line_marker;
     }
     buffer_print();
 }
References buffer_print(), cur_fline, empty_line_marker, FLAG_S, flines, i, LINENO, lineno, max_displayed_line, max_fline, and option_mask32.
Referenced by buffer_down(), buffer_to_line(), buffer_up(), getch_nowait(), less_main(), and reinitialize().
buffer_line()
static void buffer_line (int linenum) static
Definition at line 1041 of file less.c.
 {
     buffer_to_line(linenum, FALSE);
 }
References buffer_to_line(), and FALSE.
Referenced by keypress_process().
buffer_lineno()
static void buffer_lineno (int lineno) static
Definition at line 1046 of file less.c.
 {
     buffer_to_line(lineno, TRUE);
 }
References buffer_to_line(), lineno, and TRUE.
Referenced by number_process().
buffer_print()
static void buffer_print (void) static
Definition at line 900 of file less.c.
 {
     unsigned i;
     move_cursor(0, 0);
     for (i = 0; i <= max_displayed_line; i++) {
         printf(CLEAR_2_EOL);
         if (option_mask32 & FLAG_N)
             print_lineno(buffer[i]);
         if (pattern_valid)
             print_found(buffer[i]);
         else
             print_ascii(buffer[i]);
     }
     if ((option_mask32 & (FLAG_E|FLAG_F))
      && eof_error <= 0
     ) {
         i = option_mask32 & FLAG_F ? 0 : cur_fline;
         if (max_fline - i <= max_displayed_line)
             less_exit();
     }
     status_print();
 }
References CLEAR_2_EOL, cur_fline, eof_error, FLAG_E, FLAG_F, FLAG_N, i, less_exit(), max_displayed_line, max_fline, move_cursor(), option_mask32, pattern_valid, print_ascii(), print_found(), print_lineno(), printf, and status_print().
Referenced by buffer_fill_and_print(), keypress_process(), and number_process().
buffer_to_line()
static void buffer_to_line (int linenum, int is_lineno) static
Definition at line 1028 of file less.c.
 {
     if (linenum <= 0)
         cur_fline = 0;
     else if (is_lineno)
         goto_lineno(linenum);
     else
         cur_fline = linenum;
     read_lines();
     cap_cur_fline();
     buffer_fill_and_print();
 }
References buffer_fill_and_print(), cap_cur_fline(), cur_fline, goto_lineno(), and read_lines().
Referenced by buffer_line(), and buffer_lineno().
buffer_up()
static void buffer_up (int nlines) static
Definition at line 1012 of file less.c.
 {
     if ((option_mask32 & FLAG_S)) {
         goto_lineno(LINENO(flines[cur_fline]) - nlines);
     }
     else {
         cur_fline -= nlines;
         if (cur_fline < 0)
             cur_fline = 0;
     }
     read_lines();
     buffer_fill_and_print();
 }
References buffer_fill_and_print(), cur_fline, FLAG_S, flines, goto_lineno(), LINENO, option_mask32, and read_lines().
Referenced by keypress_process(), and number_process().
cap_cur_fline()
static void cap_cur_fline (void) static
Definition at line 982 of file less.c.
 {
     if ((option_mask32 & FLAG_S)) {
         if (cur_fline > max_fline)
             cur_fline = max_fline;
         if (LINENO(flines[cur_fline]) + max_displayed_line > max_lineno + TILDES) {
             goto_lineno(max_lineno - max_displayed_line + TILDES);
             read_lines();
         }
     }
     else {
         if (cur_fline + max_displayed_line > max_fline + TILDES)
             cur_fline = max_fline - max_displayed_line + TILDES;
         if (cur_fline < 0)
             cur_fline = 0;
     }
 }
References cur_fline, FLAG_S, flines, goto_lineno(), LINENO, max_displayed_line, max_fline, max_lineno, option_mask32, read_lines(), and TILDES.
Referenced by buffer_down(), and buffer_to_line().
change_file()
static void change_file (int direction) static
Definition at line 1243 of file less.c.
 {
     if (current_file != ((direction > 0) ? num_files : 1)) {
         current_file = direction ? current_file + direction : 1;
         free(filename);
         filename = xstrdup(files[current_file - 1]);
         reinitialize();
     } else {
         print_statusline(direction > 0 ? "No next file" : "No previous file");
     }
 }
References current_file, filename, files, free, num_files, print_statusline(), reinitialize(), and xstrdup().
Referenced by colon_process(), and remove_current_file().
clear_line()
static void clear_line (void) static
Definition at line 311 of file less.c.
 {
     printf(ESC"[%u;0H" CLEAR_2_EOL, max_displayed_line + 2);
 }
References CLEAR_2_EOL, ESC, max_displayed_line, and printf.
Referenced by number_process(), print_statusline(), restore_tty(), and status_print().
colon_process()
static void colon_process (void) static
Definition at line 1276 of file less.c.
 {
     int keypress;
     /* Clear the current line and print a prompt */
     print_statusline(" :");
     keypress = less_getch(2);
     switch (keypress) {
     case 'd':
         remove_current_file();
         break;
     case 'e':
         examine_file();
         break;
 #if ENABLE_FEATURE_LESS_FLAGS
     case 'f':
         m_status_print();
         break;
 #endif
     case 'n':
         change_file(1);
         break;
     case 'p':
         change_file(-1);
         break;
     case 'q':
         less_exit();
         break;
     case 'x':
         change_file(0);
         break;
     }
 }
References change_file(), examine_file(), less_exit(), less_getch(), print_statusline(), and remove_current_file().
Referenced by keypress_process().
examine_file()
static void examine_file (void) static
Definition at line 1212 of file less.c.
 {
     char *new_fname;
     print_statusline("Examine: ");
     new_fname = less_gets(sizeof("Examine: ") - 1);
     if (!new_fname[0]) {
         status_print();
  err:
         free(new_fname);
         return;
     }
     if (access(new_fname, R_OK) != 0) {
         print_statusline("Cannot read this file");
         goto err;
     }
     free(filename);
     filename = new_fname;
     /* files start by = argv. why we assume that argv is infinitely long??
     files[num_files] = filename;
     current_file = num_files + 1;
     num_files++; */
     files[0] = filename;
     num_files = current_file = 1;
     reinitialize();
 }
References access(), current_file, err(), filename, files, free, less_gets(), num_files, print_statusline(), R_OK, reinitialize(), and status_print().
Referenced by colon_process(), and keypress_process().
getch_nowait()
static int64_t getch_nowait (void) static
Definition at line 1096 of file less.c.
 {
     int rd;
     int64_t key64;
     struct pollfd pfd[2];
     pfd[0].fd = STDIN_FILENO;
     pfd[0].events = POLLIN;
     pfd[1].fd = kbd_fd;
     pfd[1].events = POLLIN;
  again:
     tcsetattr(kbd_fd, TCSANOW, &term_less);
     /* NB: select/poll returns whenever read will not block. Therefore:
      * if eof is reached, select/poll will return immediately
      * because read will immediately return 0 bytes.
      * Even if select/poll says that input is available, read CAN block
      * (switch fd into O_NONBLOCK'ed mode to avoid it)
      */
     rd = 1;
     /* Are we interested in stdin? */
     if (at_end()) {
         if (eof_error > 0) /* did NOT reach eof yet */
             rd = 0; /* yes, we are interested in stdin */
     }
     /* Position cursor if line input is done */
     if (less_gets_pos >= 0)
         move_cursor(max_displayed_line + 2, less_gets_pos + 1);
     fflush_all();
     if (kbd_input[0] == 0) { /* if nothing is buffered */
 #if ENABLE_FEATURE_LESS_WINCH
         while (1) {
             int r;
             /* NB: SIGWINCH interrupts poll() */
             r = poll(pfd + rd, 2 - rd, -1);
             if (/*r < 0 && errno == EINTR &&*/ winch_counter)
                 return '\\'; /* anything which has no defined function */
             if (r) break;
         }
 #else
         safe_poll(pfd + rd, 2 - rd, -1);
 #endif
     }
     /* We have kbd_fd in O_NONBLOCK mode, read inside safe_read_key()
      * would not block even if there is no input available */
     key64 = safe_read_key(kbd_fd, kbd_input, /*timeout off:*/ -2);
     if ((int)key64 == -1) {
         if (errno == EAGAIN) {
             /* No keyboard input available. Since poll() did return,
              * we should have input on stdin */
             read_lines();
             buffer_fill_and_print();
             goto again;
         }
         /* EOF/error (ssh session got killed etc) */
         less_exit();
     }
     set_tty_cooked();
     return key64;
 }
References at_end(), buffer_fill_and_print(), EAGAIN, eof_error, errno, fflush_all(), kbd_fd, kbd_input, less_exit(), less_gets_pos, max_displayed_line, move_cursor(), pfd, poll(), POLLIN, rd, read_lines(), safe_poll(), safe_read_key(), set_tty_cooked(), STDIN_FILENO, TCSANOW, tcsetattr(), term_less, and winch_counter.
Referenced by less_getch(), and less_gets().
goto_lineno()
static void goto_lineno (int target) static
Definition at line 960 of file less.c.
 {
     if (target <= 0 ) {
         cur_fline = 0;
     }
     else if (target > LINENO(flines[cur_fline])) {
  retry:
         while (LINENO(flines[cur_fline]) != target && cur_fline < max_fline)
             ++cur_fline;
         /* target not reached but more input is available */
         if (LINENO(flines[cur_fline]) != target && eof_error > 0) {
             read_lines();
             goto retry;
         }
     }
     else {
         /* search backwards through already-read lines */
         while (LINENO(flines[cur_fline]) != target && cur_fline > 0)
             --cur_fline;
     }
 }
References cur_fline, eof_error, flines, LINENO, max_fline, read_lines(), and target.
Referenced by buffer_down(), buffer_to_line(), buffer_up(), and cap_cur_fline().
keypress_process()
static void keypress_process (int keypress) static
Definition at line 1691 of file less.c.
 {
     switch (keypress) {
     case KEYCODE_DOWN: case 'e': case 'j': case 0x0d:
         buffer_down(1);
         break;
     case KEYCODE_UP: case 'y': case 'k':
         buffer_up(1);
         break;
     case KEYCODE_PAGEDOWN: case ' ': case 'z': case 'f':
         buffer_down(max_displayed_line + 1);
         break;
     case KEYCODE_PAGEUP: case 'w': case 'b':
         buffer_up(max_displayed_line + 1);
         break;
     case 'd':
         buffer_down((max_displayed_line + 1) / 2);
         break;
     case 'u':
         buffer_up((max_displayed_line + 1) / 2);
         break;
     case KEYCODE_HOME: case 'g': case 'p': case '<': case '%':
         buffer_line(0);
         break;
     case KEYCODE_END: case 'G': case '>':
         cur_fline = MAXLINES;
         read_lines();
         buffer_line(cur_fline);
         break;
     case 'q': case 'Q':
         less_exit();
         break;
 #if ENABLE_FEATURE_LESS_MARKS
     case 'm':
         add_mark();
         buffer_print();
         break;
     case '\'':
         goto_mark();
         buffer_print();
         break;
 #endif
     case 'r': case 'R':
         /* TODO: (1) also bind ^R, ^L to this?
          * (2) re-measure window size?
          */
         buffer_print();
         break;
     /*case 'R':
         full_repaint();
         break;*/
     case 's':
         save_input_to_file();
         break;
     case 'E':
         examine_file();
         break;
 #if ENABLE_FEATURE_LESS_FLAGS
     case '=':
         m_status_print();
         break;
 #endif
 #if ENABLE_FEATURE_LESS_REGEXP
     case '/':
         option_mask32 &= ~LESS_STATE_MATCH_BACKWARDS;
         regex_process();
         break;
     case 'n':
         goto_match(match_pos + 1);
         break;
     case 'N':
         goto_match(match_pos - 1);
         break;
     case '?':
         option_mask32 |= LESS_STATE_MATCH_BACKWARDS;
         regex_process();
         break;
 #endif
 #if ENABLE_FEATURE_LESS_DASHCMD
     case '-':
         flag_change();
         buffer_print();
         break;
 #ifdef BLOAT
     case '_':
         show_flag_status();
         break;
 #endif
 #endif
 #if ENABLE_FEATURE_LESS_BRACKETS
     case '{': case '(': case '[':
         match_right_bracket(keypress);
         break;
     case '}': case ')': case ']':
         match_left_bracket(keypress);
         break;
 #endif
     case ':':
         colon_process();
         break;
     }
     if (isdigit(keypress))
         number_process(keypress);
 }
References buffer_down(), buffer_line(), buffer_print(), buffer_up(), colon_process(), cur_fline, examine_file(), isdigit, KEYCODE_DOWN, KEYCODE_END, KEYCODE_HOME, KEYCODE_PAGEDOWN, KEYCODE_PAGEUP, KEYCODE_UP, less_exit(), LESS_STATE_MATCH_BACKWARDS, max_displayed_line, MAXLINES, number_process(), option_mask32, read_lines(), and save_input_to_file().
Referenced by less_main().
less_exit()
static NOINLINE void less_exit (void) static
Definition at line 336 of file less.c.
 {
     restore_tty();
     exit_SUCCESS();
 }
References exit_SUCCESS(), and restore_tty().
Referenced by buffer_print(), colon_process(), getch_nowait(), and keypress_process().
less_getch()
static int64_t less_getch (int pos) static
Definition at line 1161 of file less.c.
 {
     int64_t key64;
     int key;
  again:
     less_gets_pos = pos;
     key = key64 = getch_nowait();
     less_gets_pos = -1;
     /* Discard Ctrl-something chars.
      * (checking only lower 32 bits is a size optimization:
      * upper 32 bits are used only by KEYCODE_CURSOR_POS)
      */
     if (key >= 0 && key < ' ' && key != 0x0d && key != 8)
         goto again;
     return key64;
 }
References getch_nowait(), less_gets_pos, and pos.
Referenced by colon_process(), less_main(), and number_process().
less_gets()
static char* less_gets (int sz) static
Definition at line 1181 of file less.c.
 {
     int c;
     unsigned i = 0;
     char *result = xzalloc(1);
     while (1) {
         c = '\0';
         less_gets_pos = sz + i;
         c = getch_nowait();
         if (c == 0x0d) {
             result[i] = '\0';
             less_gets_pos = -1;
             return result;
         }
         if (c == 0x7f)
             c = 8;
         if (c == 8 && i) {
             printf("\x8 \x8");
             i--;
         }
         if (c < ' ') /* filters out KEYCODE_xxx too (<0) */
             continue;
         if (i >= width - sz - 1)
             continue; /* len limit */
         bb_putchar(c);
         result[i++] = c;
         result = xrealloc(result, i+1);
     }
 }
References bb_putchar(), c, getch_nowait(), i, less_gets_pos, printf, width, xrealloc, and xzalloc().
Referenced by examine_file(), and save_input_to_file().
less_main()
int less_main (int argc, char ** argv)
Definition at line 1811 of file less.c.
 {
     char *tty_name;
     int tty_fd;
     INIT_G();
     /* TODO: -x: do not interpret backspace, -xx: tab also
      * -xxx: newline also
      * -w N: assume width N (-xxx -w 32: hex viewer of sorts)
      * -s: condense many empty lines to one
      *     (used by some setups for manpage display)
      */
     getopt32(argv, "EMmN~IF"
         IF_FEATURE_LESS_TRUNCATE("S")
         IF_FEATURE_LESS_RAW("R")
         /*ignored:*/"sX"
     );
     argv += optind;
     num_files = argc - optind;
     files = argv;
     /* Tools typically pass LESS="FRSXMK".
      * The options we don't understand are ignored. */
     if (ENABLE_FEATURE_LESS_ENV) {
         char *c = getenv("LESS");
         if (c) while (*c) switch (*c++) {
         case 'F':
             option_mask32 |= FLAG_F;
             break;
         case 'M':
             option_mask32 |= FLAG_M;
             break;
         case 'R':
             option_mask32 |= FLAG_R;
             break;
         case 'S':
             option_mask32 |= FLAG_S;
             break;
         default:
             break;
         }
     }
     /* Another popular pager, most, detects when stdout
      * is not a tty and turns into cat. This makes sense. */
     if (!isatty(STDOUT_FILENO))
         return bb_cat(argv);
     if (!num_files) {
         if (isatty(STDIN_FILENO)) {
             /* Just "less"? No args and no redirection? */
             bb_show_usage();
         }
     } else {
         filename = xstrdup(files[0]);
     }
     if (option_mask32 & FLAG_TILDE)
         empty_line_marker = "";
     /* Some versions of less can survive w/o controlling tty,
      * try to do the same. This also allows to specify an alternative
      * tty via "less 1<>TTY".
      *
      * We prefer not to use STDOUT_FILENO directly,
      * since we want to set this fd to non-blocking mode,
      * and not interfere with other processes which share stdout with us.
      */
     tty_name = xmalloc_ttyname(STDOUT_FILENO);
     if (tty_name) {
         tty_fd = open(tty_name, O_RDONLY);
         free(tty_name);
         if (tty_fd < 0)
             goto try_ctty;
     } else {
         /* Try controlling tty */
  try_ctty:
         tty_fd = open(CURRENT_TTY, O_RDONLY);
         if (tty_fd < 0) {
             /* If all else fails, less 481 uses stdout. Mimic that */
             tty_fd = STDOUT_FILENO;
         }
     }
     G.kbd_fd_orig_flags = ndelay_on(tty_fd);
     kbd_fd = tty_fd; /* save in a global */
     get_termios_and_make_raw(tty_fd, &term_less, &term_orig, TERMIOS_RAW_CRNL_INPUT);
     IF_FEATURE_LESS_ASK_TERMINAL(G.winsize_err =) get_terminal_width_height(tty_fd, &width, &max_displayed_line);
     /* 20: two tabstops + 4 */
     if (width < 20 || max_displayed_line < 3)
         return bb_cat(argv);
     max_displayed_line -= 2;
     /* We want to restore term_orig on exit */
     bb_signals(BB_FATAL_SIGS, sig_catcher);
 #if ENABLE_FEATURE_LESS_WINCH
     signal(SIGWINCH, sigwinch_handler);
 #endif
     buffer = xmalloc((max_displayed_line+1) * sizeof(char *));
     reinitialize();
     while (1) {
         int64_t keypress;
 #if ENABLE_FEATURE_LESS_WINCH
         while (WINCH_COUNTER) {
  again:
             winch_counter--;
             IF_FEATURE_LESS_ASK_TERMINAL(G.winsize_err =) get_terminal_width_height(kbd_fd, &width, &max_displayed_line);
  IF_FEATURE_LESS_ASK_TERMINAL(got_size:)
             /* 20: two tabstops + 4 */
             if (width < 20)
                 width = 20;
             if (max_displayed_line < 3)
                 max_displayed_line = 3;
             max_displayed_line -= 2;
             free(buffer);
             buffer = xmalloc((max_displayed_line+1) * sizeof(char *));
             /* Avoid re-wrap and/or redraw if we already know
              * we need to do it again. These ops are expensive */
             if (WINCH_COUNTER)
                 goto again;
             re_wrap();
             if (WINCH_COUNTER)
                 goto again;
             buffer_fill_and_print();
             /* This took some time. Loop back and check,
              * were there another SIGWINCH? */
         }
         keypress = less_getch(-1); /* -1: do not position cursor */
 # if ENABLE_FEATURE_LESS_ASK_TERMINAL
         if ((int32_t)keypress == KEYCODE_CURSOR_POS) {
             uint32_t rc = (keypress >> 32);
             width = (rc & 0x7fff);
             max_displayed_line = ((rc >> 16) & 0x7fff);
             goto got_size;
         }
 # endif
 #else
         keypress = less_getch(-1); /* -1: do not position cursor */
 #endif
         keypress_process(keypress);
     }
 }
References argc, argv, bb_cat(), BB_FATAL_SIGS, bb_show_usage(), bb_signals(), buffer_fill_and_print(), c, CURRENT_TTY, empty_line_marker, filename, files, FLAG_F, FLAG_M, FLAG_R, FLAG_S, FLAG_TILDE, free, G, get_terminal_width_height(), get_termios_and_make_raw(), getenv, getopt32(), INIT_G, isatty(), kbd_fd, KEYCODE_CURSOR_POS, keypress_process(), less_getch(), max_displayed_line, ndelay_on(), num_files, O_RDONLY, open(), optind, option_mask32, rc, reinitialize(), sig_catcher(), signal, SIGWINCH, STDIN_FILENO, STDOUT_FILENO, term_less, term_orig, TERMIOS_RAW_CRNL_INPUT, width, winch_counter, WINCH_COUNTER, xmalloc, xmalloc_ttyname(), and xstrdup().
move_cursor()
static void move_cursor (int line, int col) static
Definition at line 306 of file less.c.
 {
     printf(ESC"[%u;%uH", line, col);
 }
References ESC, and printf.
Referenced by buffer_print(), and getch_nowait().
number_process()
static void number_process (int first_digit) static
Definition at line 1410 of file less.c.
 {
     unsigned i;
     int num;
     int keypress;
     char num_input[sizeof(int)*4]; /* more than enough */
     num_input[0] = first_digit;
     /* Clear the current line, print a prompt, and then print the digit */
     clear_line();
     printf(":%c", first_digit);
     /* Receive input until a letter is given */
     i = 1;
     while (i < sizeof(num_input)-1) {
         keypress = less_getch(i + 1);
         if ((unsigned)keypress > 255 || !isdigit(keypress))
             break;
         num_input[i] = keypress;
         bb_putchar(keypress);
         i++;
     }
     num_input[i] = '\0';
     num = bb_strtou(num_input, NULL, 10);
     /* on format error, num == -1 */
     if (num < 1 || num > MAXLINES) {
         buffer_print();
         return;
     }
     /* We now know the number and the letter entered, so we process them */
     switch (keypress) {
     case KEYCODE_DOWN: case 'z': case 'd': case 'e': case ' ': case '\015':
         buffer_down(num);
         break;
     case KEYCODE_UP: case 'b': case 'w': case 'y': case 'u':
         buffer_up(num);
         break;
     case 'g': case '<': case 'G': case '>':
         buffer_lineno(num - 1);
         break;
     case 'p': case '%':
 #if ENABLE_FEATURE_LESS_FLAGS
         update_num_lines();
         num = num * (num_lines > 0 ? num_lines : max_lineno) / 100;
 #else
         num = num * max_lineno / 100;
 #endif
         buffer_lineno(num);
         break;
 #if ENABLE_FEATURE_LESS_REGEXP
     case 'n':
         goto_match(match_pos + num);
         break;
     case '/':
         option_mask32 &= ~LESS_STATE_MATCH_BACKWARDS;
         regex_process();
         break;
     case '?':
         option_mask32 |= LESS_STATE_MATCH_BACKWARDS;
         regex_process();
         break;
 #endif
     }
 }
References bb_putchar(), bb_strtou(), buffer_down(), buffer_lineno(), buffer_print(), buffer_up(), clear_line(), i, isdigit, KEYCODE_DOWN, KEYCODE_UP, less_getch(), LESS_STATE_MATCH_BACKWARDS, max_lineno, MAXLINES, NULL, num, num_lines, option_mask32, and printf.
Referenced by keypress_process().
open_file_and_read_lines()
static void open_file_and_read_lines (void) static
Definition at line 1051 of file less.c.
 {
     if (filename) {
         xmove_fd(xopen(filename, O_RDONLY), STDIN_FILENO);
 #if ENABLE_FEATURE_LESS_FLAGS
         num_lines = REOPEN_AND_COUNT;
 #endif
     } else {
         /* "less" with no arguments in argv[] */
         /* For status line only */
         filename = xstrdup(bb_msg_standard_input);
 #if ENABLE_FEATURE_LESS_FLAGS
         num_lines = REOPEN_STDIN;
 #endif
     }
     readpos = 0;
     readeof = 0;
     last_line_pos = 0;
     terminated = 1;
     read_lines();
 }
References filename, last_line_pos, num_lines, O_RDONLY, read_lines(), readeof, readpos, STDIN_FILENO, terminated, xmove_fd(), xopen(), and xstrdup().
Referenced by reinitialize().
print_ascii()
static void print_ascii (const char * str) static
Definition at line 867 of file less.c.
 {
     char buf[width+1];
     char *p;
     size_t n;
     while (*str) {
         n = strcspn(str, controls);
         if (n) {
             if (!str[n]) break;
             printf("%.*s", (int) n, str);
             str += n;
         }
         n = strspn(str, controls);
         p = buf;
         do {
             if (*str == 0x7f)
                 *p++ = '?';
             else if (*str == (char)0x9b)
             /* VT100's CSI, aka Meta-ESC. Who's inventor? */
             /* I want to know who committed this sin */
                 *p++ = '{';
             else
                 *p++ = ctrlconv[(unsigned char)*str];
             str++;
         } while (--n);
         *p = '\0';
         print_hilite(buf);
     }
     puts(str);
 }
References buf, n, p, print_hilite(), printf, puts(), str, strcspn(), strspn(), and width.
Referenced by buffer_print().
print_found()
void print_found (const char * line)
Referenced by buffer_print().
print_hilite()
static void print_hilite (const char * str) static
Definition at line 316 of file less.c.
 {
     printf(HIGHLIGHT"%s"NORMAL, str);
 }
References HIGHLIGHT, NORMAL, printf, and str.
Referenced by print_ascii(), and status_print().
print_lineno()
static void print_lineno (const char * line) static
Definition at line 784 of file less.c.
 {
     const char *fmt = "        ";
     unsigned n = n; /* for compiler */
     if (line != empty_line_marker) {
         /* Width of 7 preserves tab spacing in the text */
         fmt = "%7u ";
         n = LINENO(line) + 1;
         if (n > 9999999 && MAXLINES > 9999999) {
             n %= 10000000;
             fmt = "%07u ";
         }
     }
     printf(fmt, n);
 }
References empty_line_marker, LINENO, MAXLINES, n, and printf.
Referenced by buffer_print(), and error_prolog().
print_statusline()
static void print_statusline (const char * str) static
Definition at line 321 of file less.c.
 {
     clear_line();
     printf(HIGHLIGHT"%.*s"NORMAL, width - 1, str);
 }
References clear_line(), HIGHLIGHT, NORMAL, printf, str, and width.
Referenced by change_file(), colon_process(), examine_file(), read_lines(), and save_input_to_file().
read_lines()
static void read_lines (void) static
Definition at line 470 of file less.c.
 {
     char *current_line, *p;
     int w = width;
     char last_terminated = terminated;
     time_t last_time = 0;
     int retry_EAGAIN = 2;
 #if ENABLE_FEATURE_LESS_REGEXP
     unsigned old_max_fline = max_fline;
 #endif
 #define readbuf bb_common_bufsiz1
     setup_common_bufsiz();
     /* (careful: max_fline can be -1) */
     if (max_fline + 1 > MAXLINES)
         return;
     if (option_mask32 & FLAG_N)
         w -= 8;
     p = current_line = ((char*)xmalloc(w + 5)) + 4;
     if (!last_terminated) {
         const char *cp = flines[max_fline];
         p = stpcpy(p, cp);
         free(MEMPTR(cp));
         /* last_line_pos is still valid from previous read_lines() */
     } else {
         max_fline++;
         last_line_pos = 0;
     }
     while (1) { /* read lines until we reach cur_fline or wanted_match */
         *p = '\0';
         terminated = 0;
         while (1) { /* read chars until we have a line */
             char c;
             /* if no unprocessed chars left, eat more */
             if (readpos >= readeof) {
                 int flags = ndelay_on(0);
                 while (1) {
                     time_t t;
                     errno = 0;
                     eof_error = safe_read(STDIN_FILENO, readbuf, COMMON_BUFSIZE);
                     if (errno != EAGAIN)
                         break;
                     t = time(NULL);
                     if (t != last_time) {
                         last_time = t;
                         if (--retry_EAGAIN < 0)
                             break;
                     }
                     sched_yield();
                 }
                 fcntl(0, F_SETFL, flags); /* ndelay_off(0) */
                 readpos = 0;
                 readeof = eof_error;
                 if (eof_error <= 0)
                     goto reached_eof;
                 retry_EAGAIN = 1;
             }
             c = readbuf[readpos];
             /* backspace? [needed for manpages] */
             /* <tab><bs> is (a) insane and */
             /* (b) harder to do correctly, so we refuse to do it */
             if (c == '\x8' && last_line_pos && p[-1] != '\t') {
                 readpos++; /* eat it */
                 last_line_pos--;
             /* was buggy (p could end up <= current_line)... */
                 *--p = '\0';
                 continue;
             }
 #if ENABLE_FEATURE_LESS_RAW
             if (option_mask32 & FLAG_R) {
                 if (c == '\033')
                     goto discard;
                 if (G.in_escape) {
                     if (isdigit(c)
                      || c == '['
                      || c == ';'
                      || c == 'm'
                     ) {
  discard:
                         G.in_escape = (c != 'm');
                         readpos++;
                         continue;
                     }
                     /* Hmm, unexpected end of "ESC [ N ; N m" sequence */
                     G.in_escape = 0;
                 }
             }
 #endif
             {
                 size_t new_last_line_pos = last_line_pos + 1;
                 if (c == '\t') {
                     new_last_line_pos += 7;
                     new_last_line_pos &= (~7);
                 }
                 if ((int)new_last_line_pos > w)
                     break;
                 last_line_pos = new_last_line_pos;
             }
             /* ok, we will eat this char */
             readpos++;
             if (c == '\n') {
                 terminated = 1;
                 last_line_pos = 0;
                 break;
             }
             /* NUL is substituted by '\n'! */
             if (c == '\0') c = '\n';
             *p++ = c;
             *p = '\0';
         } /* end of "read chars until we have a line" loop */
 #if 0
 //BUG: also triggers on this:
 // { printf "\nfoo\n"; sleep 1; printf "\nbar\n"; } | less
 // (resulting in lost empty line between "foo" and "bar" lines)
 // the "terminated" logic needs fixing (or explaining)
         /* Corner case: linewrap with only "" wrapping to next line */
         /* Looks ugly on screen, so we do not store this empty line */
         if (!last_terminated && !current_line[0]) {
             last_terminated = 1;
             max_lineno++;
             continue;
         }
 #endif
  reached_eof:
         last_terminated = terminated;
         flines = xrealloc_vector(flines, 8, max_fline);
         flines[max_fline] = (char*)xrealloc(MEMPTR(current_line), strlen(current_line) + 1 + 4) + 4;
         LINENO(flines[max_fline]) = max_lineno;
         if (terminated)
             max_lineno++;
         if (max_fline >= MAXLINES) {
             eof_error = 0; /* Pretend we saw EOF */
             break;
         }
         if (!at_end()) {
 #if !ENABLE_FEATURE_LESS_REGEXP
             break;
 #else
             if (wanted_match >= num_matches) { /* goto_match called us */
                 fill_match_lines(old_max_fline);
                 old_max_fline = max_fline;
             }
             if (wanted_match < num_matches)
                 break;
 #endif
         }
         if (eof_error <= 0) {
             break;
         }
         max_fline++;
         current_line = ((char*)xmalloc(w + 5)) + 4;
         p = current_line;
         last_line_pos = 0;
     } /* end of "read lines until we reach cur_fline" loop */
     if (eof_error < 0) {
         if (errno == EAGAIN) {
             eof_error = 1;
         } else {
             print_statusline(bb_msg_read_error);
         }
     }
 #if ENABLE_FEATURE_LESS_FLAGS
     else if (eof_error == 0)
         num_lines = max_lineno;
 #endif
     fill_match_lines(old_max_fline);
 #if ENABLE_FEATURE_LESS_REGEXP
     /* prevent us from being stuck in search for a match */
     wanted_match = -1;
 #endif
 #undef readbuf
 }
References at_end(), bb_msg_read_error, c, EAGAIN, eof_error, errno, F_SETFL, fcntl(), fill_match_lines, FLAG_N, FLAG_R, flags, flines, free, G, isdigit, last_line_pos, LINENO, max_fline, max_lineno, MAXLINES, MEMPTR, ndelay_on(), NULL, num_lines, option_mask32, p, print_statusline(), readbuf, readeof, readpos, safe_read(), sched_yield(), STDIN_FILENO, stpcpy(), strlen(), t, terminated, time(), w, width, xmalloc, xrealloc, and xrealloc_vector.
Referenced by buffer_down(), buffer_to_line(), buffer_up(), cap_cur_fline(), getch_nowait(), goto_lineno(), keypress_process(), and open_file_and_read_lines().
reinitialize()
static void reinitialize (void) static
Definition at line 1074 of file less.c.
 {
     unsigned i;
     if (flines) {
         for (i = 0; i <= max_fline; i++)
             free(MEMPTR(flines[i]));
         free(flines);
         flines = NULL;
     }
     max_fline = -1;
     cur_fline = 0;
     max_lineno = 0;
     open_file_and_read_lines();
 #if ENABLE_FEATURE_LESS_ASK_TERMINAL
     if (G.winsize_err)
         printf(ESC"[999;999H" ESC"[6n");
 #endif
     buffer_fill_and_print();
 }
References buffer_fill_and_print(), cur_fline, ESC, flines, free, G, i, max_fline, max_lineno, MEMPTR, NULL, open_file_and_read_lines(), and printf.
Referenced by change_file(), examine_file(), and less_main().
remove_current_file()
static void remove_current_file (void) static
Definition at line 1255 of file less.c.
 {
     unsigned i;
     if (num_files < 2)
         return;
     if (current_file != 1) {
         change_file(-1);
         for (i = 3; i <= num_files; i++)
             files[i - 2] = files[i - 1];
         num_files--;
     } else {
         change_file(1);
         for (i = 2; i <= num_files; i++)
             files[i - 2] = files[i - 1];
         num_files--;
         current_file--;
     }
 }
References change_file(), current_file, files, i, and num_files.
Referenced by colon_process().
restore_tty()
static void restore_tty (void) static
Definition at line 328 of file less.c.
 {
     set_tty_cooked();
     if (!(G.kbd_fd_orig_flags & O_NONBLOCK))
         ndelay_off(kbd_fd);
     clear_line();
 }
References clear_line(), G, kbd_fd, ndelay_off(), O_NONBLOCK, and set_tty_cooked().
Referenced by less_exit(), and sig_catcher().
save_input_to_file()
static void save_input_to_file (void) static
Definition at line 1554 of file less.c.
 {
     const char *msg = "";
     char *current_line;
     unsigned i;
     FILE *fp;
     print_statusline("Log file: ");
     current_line = less_gets(sizeof("Log file: ")-1);
     if (current_line[0]) {
         fp = fopen_for_write(current_line);
         if (!fp) {
             msg = "Error opening log file";
             goto ret;
         }
         for (i = 0; i <= max_fline; i++)
             fprintf(fp, "%s\n", flines[i]);
         fclose(fp);
         msg = "Done";
     }
  ret:
     print_statusline(msg);
     free(current_line);
 }
References fclose(), flines, fopen_for_write(), fprintf(), free, i, less_gets(), max_fline, and print_statusline().
Referenced by keypress_process().
set_tty_cooked()
static void set_tty_cooked (void) static
Definition at line 298 of file less.c.
 {
     fflush_all();
     tcsetattr(kbd_fd, TCSANOW, &term_orig);
 }
References fflush_all(), kbd_fd, TCSANOW, tcsetattr(), and term_orig.
Referenced by getch_nowait(), and restore_tty().
sig_catcher()
static void sig_catcher (int sig) static
Definition at line 1797 of file less.c.
 {
     restore_tty();
     kill_myself_with_sig(sig); /* does not return */
 }
References kill_myself_with_sig(), and restore_tty().
Referenced by less_main().
status_print()
static void status_print (void) static
Definition at line 741 of file less.c.
 {
     const char *p;
     if (less_gets_pos >= 0) /* don't touch statusline while input is done! */
         return;
     /* Change the status if flags have been set */
 #if ENABLE_FEATURE_LESS_FLAGS
     if (option_mask32 & (FLAG_M|FLAG_m)) {
         m_status_print();
         return;
     }
     /* No flags set */
 #endif
     clear_line();
     if (cur_fline && !at_end()) {
         bb_putchar(':');
         return;
     }
     p = "(END)";
     if (!cur_fline)
         p = filename;
     if (num_files > 1) {
         printf(HIGHLIGHT"%s (file %i of %i)"NORMAL,
                 p, current_file, num_files);
         return;
     }
     print_hilite(p);
 }
References at_end(), bb_putchar(), clear_line(), cur_fline, current_file, filename, FLAG_M, FLAG_m, HIGHLIGHT, less_gets_pos, NORMAL, num_files, option_mask32, p, print_hilite(), and printf.
Referenced by buffer_print(), and examine_file().
Variable Documentation
ALIGN1
const char ctrlconv [] ALIGN1 static
Initial value:
=
    "\x01\x02\x03\x04\x05\x06\x07\x08"  "\x0a\x0b\x0c\x0d\x0e\x0f"
    "\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f"
    "\x7f\x9b"
Definition at line 773 of file less.c.