Fennix Userspace: Userspace/apps/base/busybox/networking/dnsd.c File Reference
dnsd.c File Reference
#include "libbb.h"
#include <syslog.h>
Data Structures
struct dns_head
struct type_and_class
struct dns_entry
Macros
#define DEBUG 0
#define OPT_verbose (option_mask32 & 1)
#define OPT_silent (option_mask32 & 2)
Enumerations
enum {
DEFAULT_TTL = 120 , MAX_PACK_LEN = 512 , IP_STRING_LEN = sizeof(".xxx.xxx.xxx.xxx") , MAX_NAME_LEN = IP_STRING_LEN - 1 + sizeof(".in-addr.arpa") ,
REQ_A = 1 , REQ_PTR = 12
}
Functions
static void undot (char *rip)
static struct dns_entry * parse_conf_file (const char *fileconf)
static char * table_lookup (struct dns_entry *d, uint16_t type, char *query_string)
static int process_packet (struct dns_entry *conf_data, uint32_t conf_ttl, uint8_t *buf, unsigned buflen)
int dnsd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct type_and_class PACKED
Data Structure Documentation
dns_head
struct dns_head
Definition at line 63 of file dnsd.c.
Data Fields
uint16_t flags
uint16_t id
uint16_t nadd
uint16_t nansw
uint16_t nauth
uint16_t nquer
type_and_class
struct type_and_class
Definition at line 76 of file dnsd.c.
Data Fields
uint16_t type PACKED
dns_entry
struct dns_entry
Definition at line 81 of file dnsd.c.
Data Fields
uint32_t ip
char name[1]
struct dns_entry * next
char rip[IP_STRING_LEN]
Macro Definition Documentation
DEBUG
#define DEBUG 0
Definition at line 48 of file dnsd.c.
OPT_silent
#define OPT_silent (option_mask32 & 2)
Definition at line 89 of file dnsd.c.
OPT_verbose
#define OPT_verbose (option_mask32 & 1)
Definition at line 88 of file dnsd.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DEFAULT_TTL
MAX_PACK_LEN
IP_STRING_LEN
MAX_NAME_LEN
REQ_A
REQ_PTR
Definition at line 50 of file dnsd.c.
      {
     /* can tweak this */
     DEFAULT_TTL = 120,
     /* cannot get bigger packets than 512 per RFC1035. */
     MAX_PACK_LEN = 512,
     IP_STRING_LEN = sizeof(".xxx.xxx.xxx.xxx"),
     MAX_NAME_LEN = IP_STRING_LEN - 1 + sizeof(".in-addr.arpa"),
     REQ_A = 1,
     REQ_PTR = 12,
 };
Function Documentation
dnsd_main()
int dnsd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 508 of file dnsd.c.
 {
     const char *listen_interface = "0.0.0.0";
     const char *fileconf = "/etc/dnsd.conf";
     struct dns_entry *conf_data;
     uint32_t conf_ttl = DEFAULT_TTL;
     char *sttl, *sport;
     len_and_sockaddr *lsa, *from, *to;
     unsigned lsa_size;
     int udps, opts;
     uint16_t port = 53;
     /* Ensure buf is 32bit aligned (we need 16bit, but 32bit can't hurt) */
     uint8_t buf[MAX_PACK_LEN + 1] ALIGN4;
     opts = getopt32(argv, "vsi:c:t:p:d", &listen_interface, &fileconf, &sttl, &sport);
     //if (opts & (1 << 0)) // -v
     //if (opts & (1 << 1)) // -s
     //if (opts & (1 << 2)) // -i
     //if (opts & (1 << 3)) // -c
     if (opts & (1 << 4)) // -t
         conf_ttl = xatou_range(sttl, 1, 0xffffffff);
     if (opts & (1 << 5)) // -p
         port = xatou_range(sport, 1, 0xffff);
     if (opts & (1 << 6)) { // -d
         bb_daemonize_or_rexec(DAEMON_CLOSE_EXTRA_FDS, argv);
         openlog(applet_name, LOG_PID, LOG_DAEMON);
         logmode = LOGMODE_SYSLOG;
     }
     conf_data = parse_conf_file(fileconf);
     lsa = xdotted2sockaddr(listen_interface, port);
     udps = xsocket(lsa->u.sa.sa_family, SOCK_DGRAM, 0);
     xbind(udps, &lsa->u.sa, lsa->len);
     socket_want_pktinfo(udps); /* needed for recv_from_to to work */
     lsa_size = LSA_LEN_SIZE + lsa->len;
     from = xzalloc(lsa_size);
     to = xzalloc(lsa_size);
     {
         char *p = xmalloc_sockaddr2dotted(&lsa->u.sa);
         bb_info_msg("accepting UDP packets on %s", p);
         free(p);
     }
     while (1) {
         int r;
         /* Try to get *DEST* address (to which of our addresses
          * this query was directed), and reply from the same address.
          * Or else we can exhibit usual UDP ugliness:
          * [ip1.multihomed.ip2] <=  query to ip1  <= peer
          * [ip1.multihomed.ip2] => reply from ip2 => peer (confused) */
         memcpy(to, lsa, lsa_size);
         r = recv_from_to(udps, buf, MAX_PACK_LEN + 1, 0, &from->u.sa, &to->u.sa, lsa->len);
         if (r < 12 || r > MAX_PACK_LEN) {
             bb_error_msg("packet size %d, ignored", r);
             continue;
         }
         if (OPT_verbose)
             bb_simple_info_msg("got UDP packet");
         buf[r] = '\0'; /* paranoia */
         r = process_packet(conf_data, conf_ttl, buf, r);
         if (r <= 0)
             continue;
         send_to_from(udps, buf, r, 0, &from->u.sa, &to->u.sa, lsa->len);
     }
     return 0;
 }
References ALIGN4, applet_name, argv, bb_daemonize_or_rexec, bb_error_msg(), bb_info_msg, bb_simple_info_msg, buf, DAEMON_CLOSE_EXTRA_FDS, DEFAULT_TTL, free, getopt32(), LOG_DAEMON, LOG_PID, logmode, LOGMODE_SYSLOG, lsa, LSA_LEN_SIZE, MAX_PACK_LEN, memcpy(), openlog(), OPT_verbose, p, parse_conf_file(), port, process_packet(), recv_from_to(), send_to_from(), SOCK_DGRAM, socket_want_pktinfo(), len_and_sockaddr::u, xbind(), xdotted2sockaddr(), xmalloc_sockaddr2dotted(), xsocket(), and xzalloc().
parse_conf_file()
static struct dns_entry* parse_conf_file (const char * fileconf) static
Definition at line 115 of file dnsd.c.
 {
     char *token[2];
     parser_t *parser;
     struct dns_entry *m, *conf_data;
     struct dns_entry **nextp;
     conf_data = NULL;
     nextp = &conf_data;
     parser = config_open(fileconf);
     while (config_read(parser, token, 2, 2, "# \t", PARSE_NORMAL)) {
         struct in_addr ip;
         uint32_t v32;
         if (inet_aton(token[1], &ip) == 0) {
             bb_error_msg("error at line %u, skipping", parser->lineno);
             continue;
         }
         if (OPT_verbose)
             bb_info_msg("name:%s, ip:%s", token[0], token[1]);
         /* sizeof(*m) includes 1 byte for m->name[0] */
         m = xzalloc(sizeof(*m) + strlen(token[0]) + 1);
         /*m->next = NULL;*/
         *nextp = m;
         nextp = &m->next;
         m->name[0] = '.';
         strcpy(m->name + 1, token[0]);
         undot(m->name);
         m->ip = ip.s_addr; /* in network order */
         v32 = ntohl(m->ip);
         /* inverted order */
         sprintf(m->rip, ".%u.%u.%u.%u",
             (uint8_t)(v32),
             (uint8_t)(v32 >> 8),
             (uint8_t)(v32 >> 16),
             (v32 >> 24)
         );
         undot(m->rip);
     }
     config_close(parser);
     return conf_data;
 }
References bb_error_msg(), bb_info_msg, config_close(), config_open(), config_read, inet_aton(), dns_entry::ip, dns_entry::name, dns_entry::next, ntohl(), NULL, OPT_verbose, PARSE_NORMAL, parser, dns_entry::rip, sprintf(), strcpy(), strlen(), undot(), and xzalloc().
Referenced by dnsd_main().
process_packet()
static int process_packet (struct dns_entry * conf_data, uint32_t conf_ttl, uint8_t * buf, unsigned buflen) static
Definition at line 380 of file dnsd.c.
 {
     struct dns_head *head;
     struct type_and_class *unaligned_type_class;
     const char *err_msg;
     char *query_string;
     char *answstr;
     uint8_t *answb;
     uint16_t outr_rlen;
     uint16_t outr_flags;
     uint16_t type;
     uint16_t class;
     int query_len;
     head = (struct dns_head *)buf;
     if (head->nquer == 0) {
         bb_simple_error_msg("packet has 0 queries, ignored");
         return 0; /* don't reply */
     }
     if (head->flags & htons(0x8000)) { /* QR bit */
         bb_simple_error_msg("response packet, ignored");
         return 0; /* don't reply */
     }
     /* start of query string */
     query_string = (void *)(head + 1);
     /* caller guarantees strlen is <= MAX_PACK_LEN */
     query_len = strlen(query_string) + 1;
     /* may be unaligned! */
     unaligned_type_class = (void *)(query_string + query_len);
     query_len += sizeof(*unaligned_type_class);
     /* where to append answer block */
     answb = (void *)(unaligned_type_class + 1);
     if (buflen < answb - buf) {
         bb_simple_error_msg("packet too short");
         return 0; /* don't reply */
     }
     /* QR = 1 "response", RCODE = 4 "Not Implemented" */
     outr_flags = htons(0x8000 | 4);
     err_msg = NULL;
     /* OPCODE != 0 "standard query"? */
     if ((head->flags & htons(0x7800)) != 0) {
         err_msg = "opcode != 0";
         goto empty_packet;
     }
     move_from_unaligned16(class, &unaligned_type_class->class);
     if (class != htons(1)) { /* not class INET? */
         err_msg = "class != 1";
         goto empty_packet;
     }
     move_from_unaligned16(type, &unaligned_type_class->type);
     if (type != htons(REQ_A) && type != htons(REQ_PTR)) {
         /* we can't handle this query type */
 //TODO: happens all the time with REQ_AAAA (0x1c) requests - implement those?
         err_msg = "type is !REQ_A and !REQ_PTR";
         goto empty_packet;
     }
     /* look up the name */
     answstr = table_lookup(conf_data, type, query_string);
 #if DEBUG
     /* Shows lengths instead of dots, unusable for !DEBUG */
     bb_info_msg("'%s'->'%s'", query_string, answstr);
 #endif
     outr_rlen = 4;
     if (answstr && type == htons(REQ_PTR)) {
         /* returning a host name */
         outr_rlen = strlen(answstr) + 1;
     }
     if (!answstr
      || (unsigned)(answb - buf) + query_len + 4 + 2 + outr_rlen > MAX_PACK_LEN
     ) {
         /* QR = 1 "response"
          * AA = 1 "Authoritative Answer"
          * RCODE = 3 "Name Error" */
         err_msg = "name is not found";
         outr_flags = htons(0x8000 | 0x0400 | 3);
         goto empty_packet;
     }
     /* Append answer Resource Record */
     memcpy(answb, query_string, query_len); /* name, type, class */
     answb += query_len;
     move_to_unaligned32((uint32_t *)answb, htonl(conf_ttl));
     answb += 4;
     move_to_unaligned16((uint16_t *)answb, htons(outr_rlen));
     answb += 2;
     memcpy(answb, answstr, outr_rlen);
     answb += outr_rlen;
     /* QR = 1 "response",
      * AA = 1 "Authoritative Answer",
      * TODO: need to set RA bit 0x80? One user says nslookup complains
      * "Got recursion not available from SERVER, trying next server"
      * "** server can't find HOSTNAME"
      * RCODE = 0 "success"
      */
     if (OPT_verbose)
         bb_simple_info_msg("returning positive reply");
     outr_flags = htons(0x8000 | 0x0400 | 0);
     /* we have one answer */
     head->nansw = htons(1);
  empty_packet:
     if ((outr_flags & htons(0xf)) != 0) { /* not a positive response */
         if (OPT_verbose) {
             bb_error_msg("%s, %s",
                 err_msg,
                 OPT_silent ? "dropping query" : "sending error reply"
             );
         }
         if (OPT_silent)
             return 0;
     }
     head->flags |= outr_flags;
     head->nauth = head->nadd = 0;
     head->nquer = htons(1); // why???
     return answb - buf;
 }
References bb_error_msg(), bb_info_msg, bb_simple_error_msg(), bb_simple_info_msg, buf, buflen, head, htonl(), htons(), MAX_PACK_LEN, memcpy(), move_from_unaligned16, move_to_unaligned16, move_to_unaligned32, NULL, OPT_silent, OPT_verbose, REQ_A, REQ_PTR, strlen(), table_lookup(), and type.
Referenced by dnsd_main().
table_lookup()
static char* table_lookup (struct dns_entry * d, uint16_t type, char * query_string) static
Definition at line 165 of file dnsd.c.
 {
     while (d) {
         unsigned len = d->name[0];
         /* d->name[len] is the last (non NUL) char */
 #if DEBUG
         char *p, *q;
         q = query_string + 1;
         p = d->name + 1;
         fprintf(stderr, "%d/%d p:%s q:%s %d\n",
             (int)strlen(p), len,
             p, q, (int)strlen(q)
         );
 #endif
         if (type == htons(REQ_A)) {
             /* search by host name */
             if (len != 1 || d->name[1] != '*') {
 /* we are lax, hope no name component is ever >64 so that length
  * (which will be represented as 'A','B'...) matches a lowercase letter.
  * Actually, I think false matches are hard to construct.
  * Example.
  * [31] len is represented as '1', [65] as 'A', [65+32] as 'a'.
  * [65]   <65 same chars>[31]<31 same chars>NUL
  * [65+32]<65 same chars>1   <31 same chars>NUL
  * This example seems to be the minimal case when false match occurs.
  */
                 if (strcasecmp(d->name, query_string) != 0)
                     goto next;
             }
             return (char *)&d->ip;
 #if DEBUG
             fprintf(stderr, "Found IP:%x\n", (int)d->ip);
 #endif
             return 0;
         }
         /* search by IP-address */
         if ((len != 1 || d->name[1] != '*')
         /* we assume (do not check) that query_string
          * ends in ".in-addr.arpa" */
          && is_prefixed_with(query_string, d->rip)
         ) {
 #if DEBUG
             fprintf(stderr, "Found name:%s\n", d->name);
 #endif
             return d->name;
         }
  next:
         d = d->next;
     }
     return NULL;
 }
References fprintf(), htons(), dns_entry::ip, is_prefixed_with(), dns_entry::name, dns_entry::next, next, NULL, p, REQ_A, dns_entry::rip, stderr, strcasecmp, strlen(), and type.
Referenced by process_packet().
undot()
static void undot (char * rip) static
Definition at line 95 of file dnsd.c.
 {
     int i = 0;
     int s = 0;
     while (rip[i])
         i++;
     for (--i; i >= 0; i--) {
         if (rip[i] == '.') {
             rip[i] = s;
             s = 0;
         } else {
             s++;
         }
     }
 }
References i, dns_entry::rip, and s.
Referenced by parse_conf_file().
Variable Documentation
PACKED
struct type_and_class PACKED