Fennix Userspace: Userspace/libc/include/string.h File Reference
string.h File Reference
#include <stddef.h>
Functions
size_t strlen (const char *str)
int strcmp (const char *l, const char *r)
int strncmp (const char *s1, const char *s2, size_t n)
int strcasecmp (const char *s1, const char *s2)
int strncasecmp (const char *string1, const char *string2, size_t count)
char * strstr (const char *haystack, const char *needle)
char * strncpy (char *destination, const char *source, unsigned long num)
char * strdup (const char *s)
char * strchr (char const *s, int c)
char * strrchr (char const *s, int c)
void * memcpy (void *dest, const void *src, size_t n)
void * memset (void *dest, int c, size_t n)
void * memmove (void *dest, const void *src, size_t n)
Function Documentation
memcpy()
void* memcpy (void * dest, const void * src, size_t n)
Definition at line 83 of file fcts.c.
 {
     uint8_t *d = dest;
     const uint8_t *s = src;
     while (n--)
         *d++ = *s++;
     return dest;
 }
memmove()
void* memmove (void * dest, const void * src, size_t n)
Definition at line 290 of file memop.c.
 {
 #ifdef __GNUC__
     typedef __attribute__((__may_alias__)) size_t WT;
 #define WS (sizeof(WT))
 #endif
     char *d = dest;
     const char *s = src;
     if (d == s)
         return d;
     if ((uintptr_t)s - (uintptr_t)d - n <= -2 * n)
         return memcpy(d, s, n);
     if (d < s)
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)d % WS)
             {
                 if (!n--)
                     return dest;
                 *d++ = *s++;
             }
             for (; n >= WS; n -= WS, d += WS, s += WS)
                 *(WT *)d = *(WT *)s;
         }
 #endif
         for (; n; n--)
             *d++ = *s++;
     }
     else
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)(d + n) % WS)
             {
                 if (!n--)
                     return dest;
                 d[n] = s[n];
             }
             while (n >= WS)
                 n -= WS, *(WT *)(d + n) = *(WT *)(s + n);
         }
 #endif
         while (n)
             n--, d[n] = s[n];
     }
     return dest;
 }
References __attribute__, memcpy(), n, s, and src.
Referenced by _evalfile(), _rl_insert_char(), add_history(), awk_getline(), bb_verror_msg(), bcopy(), builtin_shift(), char_insert(), chat_main(), check_header_gzip(), conf_read_simple(), conspy_main(), curve25519(), date_main(), decode_prompt_string(), fold_main(), format_line(), get_header_ar(), get_node(), GetGameName(), groupnum(), header_verbose_list_ar(), inet_ntop(), inet_pton(), LoadDefaultCollection(), lzma2_lzma(), lzo1x_optimize(), massage_data_for_non_r_func(), named_function_string(), o_save_ptr_helper(), pop3_checkr(), preadbuffer(), read_base64(), read_cmdline(), read_key(), realpath(), remove_history(), remove_history_range(), rl_change_case(), safe_write_to_pty_decode_iac(), sh_canonpath(), sh_physpath(), shell_ungets(), strip(), subCommand(), subevalvar(), svlogd_main(), tail_main(), text_hole_delete(), text_hole_make(), tls_xread_record(), top_up(), trim(), trim_pathname(), unescape(), and update_line().
memset()
void* memset (void * dest, int c, size_t n)
Definition at line 92 of file fcts.c.
 {
     uint8_t *p = s;
     while (n--)
         *p++ = c;
 }
strcasecmp()
int strcasecmp (const char * s1, const char * s2)
Definition at line 34 of file string.c.
 {
     const unsigned char *p1 = (const unsigned char *)s1;
     const unsigned char *p2 = (const unsigned char *)s2;
     int result;
     if (p1 == p2)
         return 0;
     while ((result = tolower(*p1) - tolower(*p2++)) == 0)
         if (*p1++ == '\0')
             break;
     return result;
 }
References s1, s2, and tolower.
strchr()
char* strchr (char const * s, int c)
Definition at line 103 of file string.c.
 {
     size_t len = strlen(s);
     for (size_t i = 0; i < len; i++)
         if (s[i] == c)
             return (char *)s + i;
     return NULL;
 }
References c, i, NULL, s, and strlen().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 99 of file fcts.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
strdup()
char* strdup (const char * s)
Definition at line 96 of file string.c.
 {
     char *buf = (char *)__malloc(strlen((char *)s) + 1);
     strncpy(buf, s, strlen(s) + 1);
     return buf;
 }
References buf, l, malloc, memcpy(), NULL, s, strlen(), and strncpy().
strlen()
size_t strlen (const char * str)
Definition at line 5 of file string.c.
 {
     long unsigned i = 0;
     if (str)
         while (str[i] != '\0')
             ++i;
     return i;
 }
References i, and str.
Referenced by __attribute__(), __dls3(), __get_resolv_conf(), __getopt_long_core(), __getopt_msg(), __lookup_serv(), __mkostemps(), __nscd_query(), __strchrnul(), __strftime_fmt_1(), __strxfrm_l(), _evalfile(), _hs_append_history_line(), _hs_history_patsearch(), _nl_find_domain(), _nl_find_msg(), _nl_init_domain_conv(), _nl_load_domain(), _nl_log_untranslated(), _nl_make_l10nflist(), _remove_directory(), _rl_copy_to_kill_ring(), _rl_custom_readline_prefix(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_isearch_init(), _rl_macro_dumper_internal(), _rl_make_prompt_for_search(), _rl_print_color_indicator(), _rl_reset_region_color(), _rl_savestring(), _rl_strindex(), _rl_untranslate_macro_value(), _rl_vi_replace_insert(), acpid_main(), add_cmd(), add_exclude(), add_links(), add_peers(), add_symbols_from(), add_to_ino_dev_hashtable(), adjtimex_main(), alrm_catcher(), ansic_quote(), argz_count__(), argz_stringify__(), atof(), atoi(), awk_printf(), awk_split(), awk_sub(), basename(), basename_builtin(), basename_main(), bb_verror_msg(), bbunpack(), buffer_pwrite(), builtin_arrayref_flags(), builtin_eval(), cal_main(), calcsize(), cat_main(), catopen(), center(), change_to_size(), chat_main(), chcon_main(), check_existence_through_netlink(), cht_CheckCheat(), cmdlookup(), colon(), comm_match(), command_generator(), compare_keys(), compute_lcd_of_matches(), conf_choice(), conf_get_default_confname(), conf_read_simple(), conf_string(), convert_dname(), convert_to_struct(), count_strstr(), cprintf(), create_directory(), create_file(), create_links_from_list(), csvsplit(), cut_file(), cut_out_ull_opt(), cutbytes(), cutchars(), data_extract_all_prefix(), dbg_print_flags(), dcngettext(), de_backslash(), decode_prompt_string(), dequote_escapes(), dialog_checklist(), dialog_inputbox(), die(), DirIsFile(), dirname(), dirname_builtin(), dirspell(), dname_dec(), do_add_or_delete(), do_cmd(), do_glob(), do_nftw(), do_redirection_internal(), do_set(), do_sethostname(), do_tzset(), download_one_url(), dsvsplit(), dupstr(), echo_main(), escape(), escape_input(), escape_text(), EscapeShellString(), eval6(), evaluate(), evaluate_string(), exec_builtin(), exec_kernel_doc(), expand_arith_string(), expand_one_var(), expand_prompt(), expand_string_dollar_quote(), expand_string_if_necessary(), expand_variable(), expand_word_internal(), exponent(), expr_print_file_helper(), extract_colon_unit(), extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), F_Ticker(), fcopy(), fileAction(), fill_package_struct(), filter_rename_config(), find_block_device_in_dir(), find_charmap(), find_codeset(), find_export_symbols(), find_user_command_in_path(), find_user_command_internal(), finish_oldfile(), first_alpha(), fixup_rpath(), floating(), fmt_str(), fnprint(), fnwidth(), fputs(), full_write1_str(), full_write2_str(), G_RecordDemo(), gather_options_str(), get_bash_name(), get_charset_aliases(), get_input_line(), get_local_var_value(), get_mode(), get_modinfo_value(), get_node(), get_tmpdir(), getaddrinfo(), getdomainname(), getenv(), GetGameName(), gethostbyname2_r(), getlogin_r(), getmntent_r(), getnameinfo(), getprotoent(), getspnam_r(), getsubopt(), glob(), glob_dir_to_array(), glob_filename(), glob_vector(), glue_prefix_and_suffix(), grep_file(), groupnum(), handle_dir_common(), handle_incoming_and_exit(), handle_special(), hash_find(), hash_remove(), history_arg_extract(), history_backupfile(), history_do_write(), history_expand(), history_expand_internal(), history_filename(), history_search_internal(), history_tempfile(), hush_main(), I_Error(), I_PrintBanner(), if(), if_redefined(), ife_print(), index_in_strings_case_insensitive(), index_in_substrings(), indirection_level_string(), inet_ntop(), INET_rresolve(), init_exec(), init_main(), initialize_shell_variables(), initialize_siglist(), insert_match(), ipaddr_modify(), iprule_modify(), is_prefixed_with(), is_section_name(), is_suffixed_with(), is_whole_disk(), isolate_tilde_prefix(), kill_main(), kw_lookup(), list_table(), ll_proto_a2n(), ll_type_n2a(), load_library(), LoadDefaultCollection(), locale_charset(), log_locally(), logger_main(), logmatch(), logread_main(), lpqr_main(), lsmod_main(), M_Drawer(), M_ExtractFileBase(), M_SaveSelect(), M_StrCaseStr(), M_StringConcat(), M_StringCopy(), M_StringDuplicate(), M_StringEndsWith(), M_StringHeight(), M_StringJoin(), M_StringReplace(), M_StringStartsWith(), M_StringWidth(), mailstat(), main(), make_all_argv_opts(), make_default_mailpath(), make_device(), make_hash(), make_here_document(), make_redirection(), make_tempdir(), make_word_flags(), match(), mbschr(), mbsrtowcs(), md5_crypt(), mk_env_string(), mkdirpath(), mkdtemp(), mktemp(), modinfo(), mount_it_now(), name_from_hosts(), named_function_string(), nbdclient_main(), new_get_kernel_symbols(), new_init_action(), next_file(), nftw(), nl_main(), nmeter_main(), nodeckstrdup(), noninc_dosearch(), normalize(), nproc_main(), number(), o_addQstr(), o_addstr(), o_addstr_with_NUL(), obj_elf_hash(), obj_load_order_prio(), obj_string_patch(), obscure_msg(), openhere(), opt_in_list(), P_SaveGameFile(), padvance_magic(), param_expand(), parameter_brace_expand(), parameter_brace_expand_word(), parse(), parse_cmd_args(), parse_common(), parse_compound_assignment(), parse_comsub(), parse_conf(), parse_conf_file(), parse_escapes(), parse_group(), parse_matched_pair(), parse_module(), parse_mount_options(), parse_one_line(), parse_subst_cmd(), parser_if(), partname(), pat_subst(), perror(), pgrep_main(), phash_search(), pid_is_name(), pointer(), polite_directory_format(), pop3_checkr(), popmaildir_main(), pos_params_assignment(), posix_spawn_file_actions_addchdir_np(), posix_spawn_file_actions_addopen(), prepend_new_eth_table(), prf_hmac_sha256(), print_addrinfo(), print_autowrap(), print_e2flags_long(), print_filename(), print_flags_separated(), print_line(), print_offending_line(), print_title(), printargs(), PrintDehackedBanners(), printstr_base64(), process_config_line(), process_files(), process_packet(), process_stdin(), purge_package(), pushstring(), quote_escapes_internal(), quote_globbing_chars(), quote_string(), quote_string_for_globbing(), quote_string_for_repl(), rdval(), read_alias_file(), read_base64(), read_cmdline(), read_cstate_counts(), read_line_input(), read_lines(), read_token_word(), realpath(), redraw_prompt(), regerror(), remove_package(), remove_pattern(), remove_quoted_ifs(), remove_quoted_nulls(), remove_trailing_whitespace(), replace_tempfile(), rev_main(), rl_bind_keyseq_if_unbound_in_map(), rl_complete_internal(), rl_display_match_list(), rl_display_search(), rl_expand_prompt(), rl_filename_completion_function(), rl_function_of_keyseq(), rl_generic_bind(), rl_insert_comment(), rl_insert_text(), rl_invoking_keyseqs_in_map(), rl_macro_bind(), rl_menu_complete(), rl_message(), rl_on_new_line_with_prompt(), rl_parse_and_bind(), rl_quote_filename(), rl_redisplay(), rl_replace_line(), rl_username_completion_function(), rl_vi_yank_pop(), rl_yank_pop(), rmescapes(), rmoldest(), rpm_getstr(), rtc_xopen(), run_pipe(), runsvdir_main(), sanitize_env_if_suid(), savestring(), say(), scan_and_match(), scan_inet_proc_line(), scan_proc_net_or_maps(), scan_request(), scan_troff(), scanright(), searchLines(), send_file_and_exit(), sendmail_main(), seq_main(), service(), set_binding_values(), set_mode(), setenv(), setfattr_main(), setfiles_main(), setinputstring(), setlocale(), setup_heredoc(), setup_ignore_patterns(), setvar(), sh_backslash_quote(), sh_canonpath(), sh_double_quote(), sh_makepath(), sh_mktmpdir(), sh_mktmpfd(), sh_mktmpname(), sh_modcase(), sh_physpath(), sh_single_quote(), sh_stat(), sh_strvis(), sh_un_double_quote(), SHA1_UpdateString(), sha_crypt(), shell_builtin_ulimit(), shell_execve(), shell_getc(), shell_ungets(), show_status_line(), show_textbox(), skip_matched_pair(), skip_to_delim(), smtp_checkp(), sort_main(), split_main(), SplitLine(), sstrdup(), st_expr_expand(), stack_putstr(), start_stop_daemon_main(), str_append(), strcasestr(), strcat(), strcreplace(), strdup(), strduplicate(), strerror_r(), strftime(), strftime_builtin(), strgrow(), string_checker(), string_extract(), string_extract_double_quoted(), string_extract_single_quoted(), string_list_internal(), string_option_to_env(), string_quote_removal(), string_to_llist(), string_transform(), string_var_assignment(), strings(), strip(), stripwhite(), strlcat(), strlcpy(), strmaxcat(), strmaxcpy(), strncat(), strptime(), strrchr(), strrcmp(), strrstr(), strsep(), strsub(), strtodest(), subCommand(), subevalvar(), sv_emacs_modestr(), sv_isrchterm(), sv_vicmd_modestr(), sv_viins_modestr(), sym_re_search(), sym_set_string_value(), table_lookup(), tcpudpsvd_main(), tempnam(), textdomain(), tgetent(), tilde_expand(), tilde_find_prefix(), tilde_find_suffix(), tparam1(), trim(), trim_pathname(), udhcp_option_idx(), udhcpc_main(), uevent_main(), unescape(), unicode_strlen(), unquoted_glob_pattern_p(), unzip_main(), update_line(), update_passwd(), updatepwd(), user_command_matches(), validate_path(), vgetopt32(), volume_id_probe_romfs(), W_AddFile(), wget_main(), write_helpfiles(), write_longdocs(), write_new_utmp(), xargs_main(), xmalloc_fgets_internal(), xmalloc_follow_symlinks(), xmalloc_optname_optval(), xmalloc_realpath_coreutils(), xmalloc_substitute_string(), xrealloc_getcwd_or_warn(), xwrite_str(), and ZenityErrorBox().
strncasecmp()
int strncasecmp (const char * string1, const char * string2, size_t count)
Definition at line 47 of file string.c.
 {
     if (count)
     {
         const unsigned char *s1 = (const unsigned char *)string1;
         const unsigned char *s2 = (const unsigned char *)string2;
         int result;
         do
         {
             if ((result = tolower(*s1) - tolower(*s2++)) != 0 || !*s1++)
                 break;
         } while (--count);
         return result;
     }
     return 0;
 }
References count, s1, s2, and tolower.
strncmp()
int strncmp (const char * s1, const char * s2, size_t n)
Definition at line 21 of file string.c.
 {
     for (size_t i = 0; i < n; i++)
     {
         char c1 = s1[i], c2 = s2[i];
         if (c1 != c2)
             return c1 - c2;
         if (!c1)
             return 0;
     }
     return 0;
 }
References i, n, s1, and s2.
Referenced by __dls3(), __get_resolv_conf(), __lookup_serv(), __putenv(), _rl_print_color_indicator(), add_or_supercede_exported_var(), add_split_dependencies(), append_mount_options(), bb_init_module_24(), check_existence_through_netlink(), colon(), comm_match(), command_generator(), complete_fncmp(), compute_lcd_of_matches(), conf_read_simple(), D_DoomMain(), dcngettext(), exclude(), extract_filename(), fixup_rpath(), get_local_var_value(), get_modinfo_value(), get_ptr_to_local_var(), getconf_one(), getenv(), getspnam_r(), getstat(), getsubopt(), handle_incoming_and_exit(), index_in_substrings(), is_colored(), is_prefixed_with(), last_main(), load_library(), M_StringReplace(), M_StringStartsWith(), main(), match(), match_opt(), md5crypt(), name_to_dev_t(), next_token(), ntp_init(), parse(), parse_one_line(), patch_main(), path_is_devfd(), polite_directory_format(), process_includes(), rdval_diskstats(), read_cmdline(), reverse_services(), scan_expression(), scan_request(), scan_table(), set_local_var(), sh_stat(), sha256crypt(), sha512crypt(), sha_crypt(), subevalvar(), tilde_find_prefix(), tilde_find_suffix(), tre_tnfa_run_backtrack(), uniq_main(), unsetenv(), utf8locale(), uuidcache_check_device(), and W_AddFile().
strncpy()
char* strncpy (char * destination, const char * source, unsigned long num)
Definition at line 81 of file string.c.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source && num--)
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
References NULL, and source.
Referenced by _rl_get_string_variable_value(), _rl_insert_char(), _rl_vi_callback_change_char(), add_server_options(), bash_tilde_find_word(), cal_main(), compute_lcd_of_matches(), decode_prompt_string(), dfallback(), do_print_item(), expand_char(), expand_regexp(), expand_string_dollar_quote(), extract_delimited_string(), extract_heredoc_dolbrace_string(), extract_info(), fakeidentd_main(), fmtulong(), get_history_event(), gethostname(), hist_error(), history_expand(), history_expand_internal(), history_substring(), if_indextoname(), if_nametoindex(), init_main(), M_StringCopy(), main(), make_device(), pat_subst(), polite_directory_format(), printable_job_status(), rdval_diskstats(), rl_change_case(), rl_copy_text(), rl_history_search_reinit(), rl_insert_text(), rl_tilde_expand(), rl_vi_change_char(), safe_strncpy(), scan_request(), sh_modcase(), sh_realpath(), stats_dev_find_or_new(), strdup(), strmaxcat(), strmaxcpy(), strncpy_IFNAMSIZ(), tilde_expand(), vi_save_insert_buffer(), W_AddFile(), and write_new_utmp().
strrchr()
char* strrchr (char const * s, int c)
Definition at line 113 of file string.c.
 {
     size_t len = strlen(s);
     size_t pos = len;
     while (s[pos] != c && pos-- != 0)
         ;
     if (pos == len)
         return NULL;
     return (char *)s + pos;
 }
References c, NULL, pos, s, and strlen().
strstr()
char* strstr (const char * haystack, const char * needle)
Definition at line 44 of file strstr.c.
 {
   register const unsigned char *haystack, *needle;
   register chartype b, c;
   haystack = (const unsigned char *) phaystack;
   needle = (const unsigned char *) pneedle;
   b = *needle;
   if (b != '\0')
     {
       haystack--;               /* possible ANSI violation */
       do
     {
       c = *++haystack;
       if (c == '\0')
         goto ret0;
     }
       while (c != b);
       c = *++needle;
       if (c == '\0')
     goto foundneedle;
       ++needle;
       goto jin;
       for (;;)
         {
           register chartype a;
       register const unsigned char *rhaystack, *rneedle;
       do
         {
           a = *++haystack;
           if (a == '\0')
         goto ret0;
           if (a == b)
         break;
           a = *++haystack;
           if (a == '\0')
         goto ret0;
 shloop:;    }
           while (a != b);
 jin:      a = *++haystack;
       if (a == '\0')
         goto ret0;
       if (a != c)
         goto shloop;
       rhaystack = haystack-- + 1;
       rneedle = needle;
       a = *rneedle;
       if (*rhaystack == a)
         do
           {
         if (a == '\0')
           goto foundneedle;
         ++rhaystack;
         a = *++needle;
         if (*rhaystack != a)
           break;
         if (a == '\0')
           goto foundneedle;
         ++rhaystack;
         a = *++needle;
           }
         while (*rhaystack == a);
       needle = rneedle;        /* took the register-poor approach */
       if (a == '\0')
         break;
         }
     }
 foundneedle:
   return (char*) haystack;
 ret0:
   return 0;
 }