Fennix Userspace: Userspace/apps/base/busybox/console-tools/setconsole.c File Reference
setconsole.c File Reference
#include "libbb.h"
Functions
int setconsole_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
setconsole_main()
int setconsole_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 43 of file setconsole.c.
 {
     const char *device = CURRENT_TTY;
     int reset;
     /* at most one non-option argument */
     reset = getopt32(argv, "^" "r" "\0" "?1");
     argv += 1 + reset;
     if (*argv) {
         device = *argv;
     } else {
         if (reset)
             device = DEV_CONSOLE;
     }
 //TODO: fails if TIOCCONS redir is already active to some tty.
 //I think SUSE version first does TIOCCONS on /dev/console fd (iow: resets)
 //then TIOCCONS to new tty?
     xioctl(xopen(device, O_WRONLY), TIOCCONS, NULL);
     return EXIT_SUCCESS;
 }
References argv, CURRENT_TTY, DEV_CONSOLE, device, EXIT_SUCCESS, getopt32(), NULL, O_WRONLY, reset(), TIOCCONS, xioctl, and xopen().