Fennix: Userspace/musl/include/net/if.h File Reference
if.h File Reference
#include <features.h>
Data Structures
struct if_nameindex
Macros
#define IF_NAMESIZE 16
Functions
unsigned int if_nametoindex (const char *)
char * if_indextoname (unsigned int, char *)
struct if_nameindex * if_nameindex (void)
void if_freenameindex (struct if_nameindex *)
Data Structure Documentation
if_nameindex
struct if_nameindex
Definition at line 14 of file if.h.
Data Fields
unsigned int if_index
char * if_name
Macro Definition Documentation
IF_NAMESIZE
#define IF_NAMESIZE 16
Definition at line 10 of file if.h.
Function Documentation
if_freenameindex()
void if_freenameindex (struct if_nameindex * idx)
Definition at line 6 of file net-if-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, free, and idx.
if_indextoname()
char* if_indextoname (unsigned int , char *)
Definition at line 11 of file net-if-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by getnameinfo().
if_nameindex()
struct if_nameindex* if_nameindex (void)
Definition at line 16 of file net-if-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __rtnetlink_enumerate(), AF_INET, AF_UNSPEC, ENOBUFS, err(), errno, free, i, ifnamemap::index, ctx::list, malloc, memcpy, memset, ifnamemap::name, ifnamemap::namelen, netlink_msg_to_nameindex(), p, PTHREAD_CANCEL_DISABLE, and pthread_setcancelstate().
if_nametoindex()
unsigned int if_nametoindex (const char * name)
Definition at line 21 of file net-if-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __syscall, AF_UNIX, ifreq::ifr_name, ioctl(), name, r, SIOCGIFINDEX, SOCK_CLOEXEC, SOCK_DGRAM, socket(), and strncpy().
Referenced by __lookup_ipliteral().