Fennix: Userspace/apps/base/busybox/libbb/inode_hash.c File Reference
inode_hash.c File Reference
#include "libbb.h"
Data Structures
struct ino_dev_hash_bucket_struct
Macros
#define HASH_SIZE 311u /* Should be prime */
#define hash_inode(i) ((unsigned)(i) % HASH_SIZE)
Typedefs
typedef struct ino_dev_hash_bucket_struct ino_dev_hashtable_bucket_t
Functions
char *FAST_FUNC is_in_ino_dev_hashtable (const struct stat *statbuf)
void FAST_FUNC add_to_ino_dev_hashtable (const struct stat *statbuf, const char *name)
Variables
static ino_dev_hashtable_bucket_t ** ino_dev_hashtable
Data Structure Documentation
ino_dev_hash_bucket_struct
struct ino_dev_hash_bucket_struct
Definition at line 12 of file inode_hash.c.
Data Fields
dev_t dev
ino_t ino
char isdir
char name[1]
struct ino_dev_hash_bucket_struct * next
Macro Definition Documentation
hash_inode
#define hash_inode (i) ((unsigned)(i) % HASH_SIZE)
Definition at line 29 of file inode_hash.c.
HASH_SIZE
#define HASH_SIZE 311u /* Should be prime */
Definition at line 28 of file inode_hash.c.
Typedef Documentation
ino_dev_hashtable_bucket_t
typedef struct ino_dev_hash_bucket_struct ino_dev_hashtable_bucket_t
Function Documentation
add_to_ino_dev_hashtable()
void FAST_FUNC add_to_ino_dev_hashtable (const struct stat * statbuf, const char * name)
Definition at line 59 of file inode_hash.c.
 {
     int i;
     ino_dev_hashtable_bucket_t *bucket;
     if (!name)
         name = "";
     bucket = xmalloc(sizeof(ino_dev_hashtable_bucket_t) + strlen(name));
     bucket->ino = statbuf->st_ino;
     bucket->dev = statbuf->st_dev;
     bucket->isdir = !!S_ISDIR(statbuf->st_mode);
     strcpy(bucket->name, name);
     if (!ino_dev_hashtable)
         ino_dev_hashtable = xzalloc(HASH_SIZE * sizeof(*ino_dev_hashtable));
     i = hash_inode(statbuf->st_ino);
     bucket->next = ino_dev_hashtable[i];
     ino_dev_hashtable[i] = bucket;
 }
References ino_dev_hash_bucket_struct::dev, hash_inode, HASH_SIZE, i, ino_dev_hash_bucket_struct::ino, ino_dev_hashtable, ino_dev_hash_bucket_struct::isdir, ino_dev_hash_bucket_struct::name, ino_dev_hash_bucket_struct::next, S_ISDIR, stat::st_dev, stat::st_ino, stat::st_mode, strcpy, strlen(), xmalloc, and xzalloc().
Referenced by copy_file(), and du().
is_in_ino_dev_hashtable()
char* FAST_FUNC is_in_ino_dev_hashtable (const struct stat * statbuf)
Definition at line 38 of file inode_hash.c.
 {
     ino_dev_hashtable_bucket_t *bucket;
     if (!ino_dev_hashtable)
         return NULL;
     bucket = ino_dev_hashtable[hash_inode(statbuf->st_ino)];
     while (bucket != NULL) {
         if ((bucket->ino == statbuf->st_ino)
          && (bucket->dev == statbuf->st_dev)
          && (bucket->isdir == !!S_ISDIR(statbuf->st_mode))
         ) {
             return bucket->name;
         }
         bucket = bucket->next;
     }
     return NULL;
 }
References ino_dev_hash_bucket_struct::dev, hash_inode, ino_dev_hash_bucket_struct::ino, ino_dev_hashtable, ino_dev_hash_bucket_struct::isdir, ino_dev_hash_bucket_struct::name, ino_dev_hash_bucket_struct::next, NULL, S_ISDIR, stat::st_dev, stat::st_ino, and stat::st_mode.
Referenced by copy_file(), and du().
Variable Documentation
ino_dev_hashtable
ino_dev_hashtable_bucket_t** ino_dev_hashtable static
Definition at line 32 of file inode_hash.c.
Referenced by add_to_ino_dev_hashtable(), and is_in_ino_dev_hashtable().