Fennix: Userspace/apps/base/busybox/archival/libarchive/open_transformer.c File Reference
open_transformer.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
void FAST_FUNC init_transformer_state (transformer_state_t *xstate)
int FAST_FUNC check_signature16 (transformer_state_t *xstate, unsigned magic16)
ssize_t FAST_FUNC transformer_write (transformer_state_t *xstate, const void *buf, size_t bufsize)
ssize_t FAST_FUNC xtransformer_write (transformer_state_t *xstate, const void *buf, size_t bufsize)
void check_errors_in_children (int signo)
void FAST_FUNC fork_transformer (int fd, const char *transform_prog)
Function Documentation
check_errors_in_children()
void check_errors_in_children (int signo)
Definition at line 67 of file open_transformer.c.
 {
     int status;
     if (!signo) {
         /* block waiting for any child */
         if (wait(&status) < 0)
 //FIXME: check EINTR?
             return; /* probably there are no children */
         goto check_status;
     }
     /* Wait for any child without blocking */
     for (;;) {
         if (wait_any_nohang(&status) < 0)
 //FIXME: check EINTR?
             /* wait failed?! I'm confused... */
             return;
  check_status:
         /*if (WIFEXITED(status) && WEXITSTATUS(status) == 0)*/
         /* On Linux, the above can be checked simply as: */
         if (status == 0)
             /* this child exited with 0 */
             continue;
         /* Cannot happen:
         if (!WIFSIGNALED(status) && !WIFEXITED(status)) ???;
          */
         bb_got_signal = 1;
     }
 }
References bb_got_signal, status, wait(), and wait_any_nohang().
Referenced by tar_main().
check_signature16()
int FAST_FUNC check_signature16 (transformer_state_t * xstate, unsigned magic16)
Definition at line 13 of file open_transformer.c.
 {
     if (!xstate->signature_skipped) {
         uint16_t magic2;
         if (full_read(xstate->src_fd, &magic2, 2) != 2 || magic2 != magic16) {
             bb_simple_error_msg("invalid magic");
             return -1;
         }
         xstate->signature_skipped = 2;
     }
     return 0;
 }
References bb_simple_error_msg(), full_read(), transformer_state_t::signature_skipped, and transformer_state_t::src_fd.
Referenced by IF_DESKTOP().
fork_transformer()
void FAST_FUNC fork_transformer (int fd, const char * transform_prog)
Definition at line 105 of file open_transformer.c.
 {
     struct fd_pair fd_pipe;
     int pid;
     xpiped_pair(fd_pipe);
     pid = BB_MMU ? xfork() : xvfork();
     if (pid == 0) {
         /* Child */
         close(fd_pipe.rd); /* we don't want to read from the parent */
         // FIXME: error check?
 #if BB_MMU
         {
             IF_DESKTOP(long long) int r;
             transformer_state_t xstate;
             init_transformer_state(&xstate);
             xstate.signature_skipped = signature_skipped;
             xstate.src_fd = fd;
             xstate.dst_fd = fd_pipe.wr;
             r = transformer(&xstate);
             if (ENABLE_FEATURE_CLEAN_UP) {
                 close(fd_pipe.wr); /* send EOF */
                 close(fd);
             }
             /* must be _exit! bug was actually seen here */
             _exit(/*error if:*/ r < 0);
         }
 #else
         {
             char *argv[4];
             xmove_fd(fd, 0);
             xmove_fd(fd_pipe.wr, 1);
             argv[0] = (char*)transform_prog;
             argv[1] = (char*)"-cf";
             argv[2] = (char*)"-";
             argv[3] = NULL;
             BB_EXECVP(transform_prog, argv);
             bb_perror_msg_and_die("can't execute '%s'", transform_prog);
         }
 #endif
         /* notreached */
     }
     /* parent process */
     close(fd_pipe.wr); /* don't want to write to the child */
     xmove_fd(fd_pipe.rd, fd);
 }
References _exit(), argv, BB_EXECVP, BB_MMU, bb_perror_msg_and_die(), close(), transformer_state_t::dst_fd, fd, IF_DESKTOP(), init_transformer_state(), NULL, pid, fd_pair::rd, transformer_state_t::signature_skipped, transformer_state_t::src_fd, fd_pair::wr, xfork(), xmove_fd(), xpiped_pair, and xvfork.
init_transformer_state()
void FAST_FUNC init_transformer_state (transformer_state_t * xstate)
Definition at line 8 of file open_transformer.c.
 {
     memset(xstate, 0, sizeof(*xstate));
 }
References memset.
Referenced by bbunpack(), fork_transformer(), and unzip_extract().
transformer_write()
ssize_t FAST_FUNC transformer_write (transformer_state_t * xstate, const void * buf, size_t bufsize)
Definition at line 26 of file open_transformer.c.
 {
     ssize_t nwrote;
     if (xstate->mem_output_size_max != 0) {
         size_t pos = xstate->mem_output_size;
         size_t size;
         size = (xstate->mem_output_size += bufsize);
         if (size > xstate->mem_output_size_max) {
             free(xstate->mem_output_buf);
             xstate->mem_output_buf = NULL;
             bb_perror_msg("buffer %u too small", (unsigned)xstate->mem_output_size_max);
             nwrote = -1;
             goto ret;
         }
         xstate->mem_output_buf = xrealloc(xstate->mem_output_buf, size + 1);
         memcpy(xstate->mem_output_buf + pos, buf, bufsize);
         xstate->mem_output_buf[size] = '\0';
         nwrote = bufsize;
     } else {
         nwrote = full_write(xstate->dst_fd, buf, bufsize);
         if (nwrote != (ssize_t)bufsize) {
             bb_simple_perror_msg("write");
             nwrote = -1;
             goto ret;
         }
     }
  ret:
     return nwrote;
 }
References bb_perror_msg(), bb_simple_perror_msg(), buf, transformer_state_t::dst_fd, free, full_write(), transformer_state_t::mem_output_buf, transformer_state_t::mem_output_size, transformer_state_t::mem_output_size_max, memcpy, NULL, pos, size, and xrealloc.
Referenced by IF_DESKTOP(), and xtransformer_write().
xtransformer_write()
ssize_t FAST_FUNC xtransformer_write (transformer_state_t * xstate, const void * buf, size_t bufsize)
Definition at line 58 of file open_transformer.c.
 {
     ssize_t nwrote = transformer_write(xstate, buf, bufsize);
     if (nwrote != (ssize_t)bufsize) {
         xfunc_die();
     }
     return nwrote;
 }
References buf, transformer_write(), and xfunc_die().
Referenced by IF_DESKTOP().