Fennix: Userspace/apps/base/busybox/scripts/kconfig/symbol.c File Reference
symbol.c File Reference
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <regex.h>
#include <sys/utsname.h>
#include "lkc.h"
Macros
#define LKC_DIRECT_LINK
Functions
void sym_add_default (struct symbol *sym, const char *def)
void sym_init (void)
enum symbol_type sym_get_type (struct symbol *sym)
const char * sym_type_name (enum symbol_type type)
struct property * sym_get_choice_prop (struct symbol *sym)
struct property * sym_get_default_prop (struct symbol *sym)
struct property * sym_get_range_prop (struct symbol *sym)
static int sym_get_range_val (struct symbol *sym, int base)
static void sym_validate_range (struct symbol *sym)
static void sym_calc_visibility (struct symbol *sym)
static struct symbol * sym_calc_choice (struct symbol *sym)
void sym_calc_value (struct symbol *sym)
void sym_clear_all_valid (void)
void sym_set_changed (struct symbol *sym)
void sym_set_all_changed (void)
bool sym_tristate_within_range (struct symbol *sym, tristate val)
bool sym_set_tristate_value (struct symbol *sym, tristate val)
tristate sym_toggle_tristate_value (struct symbol *sym)
bool sym_string_valid (struct symbol *sym, const char *str)
bool sym_string_within_range (struct symbol *sym, const char *str)
bool sym_set_string_value (struct symbol *sym, const char *newval)
const char * sym_get_string_value (struct symbol *sym)
bool sym_is_changable (struct symbol *sym)
struct symbol * sym_lookup (const char *name, int isconst)
struct symbol * sym_find (const char *name)
struct symbol ** sym_re_search (const char *pattern)
struct symbol * sym_check_deps (struct symbol *sym)
static struct symbol * sym_check_expr_deps (struct expr *e)
struct property * prop_alloc (enum prop_type type, struct symbol *sym)
struct symbol * prop_get_symbol (struct property *prop)
const char * prop_get_type_name (enum prop_type type)
Variables
struct symbol symbol_yes
struct symbol symbol_mod
struct symbol symbol_no
struct symbol symbol_empty
int sym_change_count
struct symbol * modules_sym
tristate modules_val
Macro Definition Documentation
LKC_DIRECT_LINK
#define LKC_DIRECT_LINK
Definition at line 12 of file symbol.c.
Function Documentation
prop_alloc()
struct property* prop_alloc (enum prop_type type, struct symbol * sym)
Definition at line 831 of file symbol.c.
 {
     struct property *prop;
     struct property **propp;
     prop = malloc(sizeof(*prop));
     memset(prop, 0, sizeof(*prop));
     prop->type = type;
     prop->sym = sym;
     prop->file = current_file;
     prop->lineno = zconf_lineno();
     /* append property to the prop list of symbol */
     if (sym) {
         for (propp = &sym->prop; *propp; propp = &(*propp)->next)
             ;
         *propp = prop;
     }
     return prop;
 }
References current_file, property::file, property::lineno, malloc, memset, property::next, symbol::prop, property::sym, type, property::type, and zconf_lineno().
Referenced by menu_add_prop(), and sym_add_default().
prop_get_symbol()
struct symbol* prop_get_symbol (struct property * prop)
Definition at line 853 of file symbol.c.
 {
     if (prop->expr && (prop->expr->type == E_SYMBOL ||
                prop->expr->type == E_CHOICE))
         return prop->expr->left.sym;
     return NULL;
 }
References E_CHOICE, E_SYMBOL, property::expr, NULL, symbol::prop, and expr::type.
Referenced by conf_read_simple(), menu_finalize(), sym_calc_choice(), sym_calc_value(), sym_check_prop(), and sym_set_tristate_value().
prop_get_type_name()
const char* prop_get_type_name (enum prop_type type)
Definition at line 861 of file symbol.c.
 {
     switch (type) {
     case P_PROMPT:
         return "prompt";
     case P_COMMENT:
         return "comment";
     case P_MENU:
         return "menu";
     case P_DEFAULT:
         return "default";
     case P_CHOICE:
         return "choice";
     case P_SELECT:
         return "select";
     case P_RANGE:
         return "range";
     case P_UNKNOWN:
         break;
     }
     return "unknown";
 }
References P_CHOICE, P_COMMENT, P_DEFAULT, P_MENU, P_PROMPT, P_RANGE, P_SELECT, P_UNKNOWN, and type.
Referenced by ConfigMainWindow::setHelp().
sym_add_default()
void sym_add_default (struct symbol * sym, const char * def)
Definition at line 37 of file symbol.c.
 {
     struct property *prop = prop_alloc(P_DEFAULT, sym);
     prop->expr = expr_alloc_symbol(sym_lookup(def, 1));
 }
References property::expr, expr_alloc_symbol(), P_DEFAULT, prop_alloc(), property::sym, and sym_lookup().
Referenced by sym_get_type().
sym_calc_choice()
static struct symbol* sym_calc_choice (struct symbol * sym) static
Definition at line 223 of file symbol.c.
 {
     struct symbol *def_sym;
     struct property *prop;
     struct expr *e;
     /* is the user choice visible? */
     def_sym = sym->user.val;
     if (def_sym) {
         sym_calc_visibility(def_sym);
         if (def_sym->visible != no)
             return def_sym;
     }
     /* any of the defaults visible? */
     for_all_defaults(sym, prop) {
         prop->visible.tri = expr_calc_value(prop->visible.expr);
         if (prop->visible.tri == no)
             continue;
         def_sym = prop_get_symbol(prop);
         sym_calc_visibility(def_sym);
         if (def_sym->visible != no)
             return def_sym;
     }
     /* just get the first visible value */
     prop = sym_get_choice_prop(sym);
     for (e = prop->expr; e; e = e->left.expr) {
         def_sym = e->right.sym;
         sym_calc_visibility(def_sym);
         if (def_sym->visible != no)
             return def_sym;
     }
     /* no choice? reset tristate value */
     sym->curr.tri = no;
     return NULL;
 }
References expr_value::expr, property::expr, expr_calc_value(), for_all_defaults, no, NULL, prop_get_symbol(), expr::right, expr_data::sym, sym_calc_visibility(), sym_get_choice_prop(), expr_value::tri, symbol::user, symbol_value::val, symbol::visible, and property::visible.
Referenced by sym_calc_value().
sym_calc_value()
void sym_calc_value (struct symbol * sym)
Definition at line 262 of file symbol.c.
 {
     struct symbol_value newval, oldval;
     struct property *prop;
     struct expr *e;
     if (!sym)
         return;
     if (sym->flags & SYMBOL_VALID)
         return;
     sym->flags |= SYMBOL_VALID;
     oldval = sym->curr;
     switch (sym->type) {
     case S_INT:
     case S_HEX:
     case S_STRING:
         newval = symbol_empty.curr;
         break;
     case S_BOOLEAN:
     case S_TRISTATE:
         newval = symbol_no.curr;
         break;
     default:
         sym->curr.val = sym->name;
         sym->curr.tri = no;
         return;
     }
     if (!sym_is_choice_value(sym))
         sym->flags &= ~SYMBOL_WRITE;
     sym_calc_visibility(sym);
     /* set default if recursively called */
     sym->curr = newval;
     switch (sym_get_type(sym)) {
     case S_BOOLEAN:
     case S_TRISTATE:
         if (sym_is_choice_value(sym) && sym->visible == yes) {
             prop = sym_get_choice_prop(sym);
             newval.tri = (prop_get_symbol(prop)->curr.val == sym) ? yes : no;
         } else if (E_OR(sym->visible, sym->rev_dep.tri) != no) {
             sym->flags |= SYMBOL_WRITE;
             if (sym_has_value(sym))
                 newval.tri = sym->user.tri;
             else if (!sym_is_choice(sym)) {
                 prop = sym_get_default_prop(sym);
                 if (prop)
                     newval.tri = expr_calc_value(prop->expr);
             }
             newval.tri = E_OR(E_AND(newval.tri, sym->visible), sym->rev_dep.tri);
         } else if (!sym_is_choice(sym)) {
             prop = sym_get_default_prop(sym);
             if (prop) {
                 sym->flags |= SYMBOL_WRITE;
                 newval.tri = expr_calc_value(prop->expr);
             }
         }
         if (newval.tri == mod && sym_get_type(sym) == S_BOOLEAN)
             newval.tri = yes;
         break;
     case S_STRING:
     case S_HEX:
     case S_INT:
         if (sym->visible != no) {
             sym->flags |= SYMBOL_WRITE;
             if (sym_has_value(sym)) {
                 newval.val = sym->user.val;
                 break;
             }
         }
         prop = sym_get_default_prop(sym);
         if (prop) {
             struct symbol *ds = prop_get_symbol(prop);
             if (ds) {
                 sym->flags |= SYMBOL_WRITE;
                 sym_calc_value(ds);
                 newval.val = ds->curr.val;
             }
         }
         break;
     default:
         ;
     }
     sym->curr = newval;
     if (sym_is_choice(sym) && newval.tri == yes)
         sym->curr.val = sym_calc_choice(sym);
     sym_validate_range(sym);
     if (memcmp(&oldval, &sym->curr, sizeof(oldval)))
         sym_set_changed(sym);
     if (modules_sym == sym)
         modules_val = modules_sym->curr.tri;
     if (sym_is_choice(sym)) {
         int flags = sym->flags & (SYMBOL_CHANGED | SYMBOL_WRITE);
         prop = sym_get_choice_prop(sym);
         for (e = prop->expr; e; e = e->left.expr) {
             e->right.sym->flags |= flags;
             if (flags & SYMBOL_CHANGED)
                 sym_set_changed(e->right.sym);
         }
     }
 }
References E_AND, E_OR, property::expr, expr_calc_value(), flags, symbol::flags, if(), memcmp(), mod, modules_sym, modules_val, symbol::name, no, symbol::prop, prop_get_symbol(), symbol::rev_dep, expr::right, S_BOOLEAN, S_HEX, S_INT, S_STRING, S_TRISTATE, expr_data::sym, sym_calc_choice(), sym_calc_visibility(), sym_get_choice_prop(), sym_get_default_prop(), sym_get_type(), sym_has_value(), sym_is_choice(), sym_is_choice_value(), sym_set_changed(), sym_validate_range(), SYMBOL_CHANGED, symbol_empty, symbol_no, SYMBOL_VALID, SYMBOL_WRITE, expr_value::tri, symbol_value::tri, symbol::type, symbol::user, symbol_value::val, symbol::visible, and yes.
Referenced by conf_choice(), conf_expand_value(), conf_read(), conf_read_simple(), conf_write(), expr_calc_value(), fill_row(), ConfigItem::init(), main(), menu_is_visible(), sym_clear_all_valid(), sym_get_range_val(), and ConfigItem::testUpdateMenu().
sym_calc_visibility()
static void sym_calc_visibility (struct symbol * sym) static
Definition at line 193 of file symbol.c.
 {
     struct property *prop;
     tristate tri;
     /* any prompt visible? */
     tri = no;
     for_all_prompts(sym, prop) {
         prop->visible.tri = expr_calc_value(prop->visible.expr);
         tri = E_OR(tri, prop->visible.tri);
     }
     if (tri == mod && (sym->type != S_TRISTATE || modules_val == no))
         tri = yes;
     if (sym->visible != tri) {
         sym->visible = tri;
         sym_set_changed(sym);
     }
     if (sym_is_choice_value(sym))
         return;
     tri = no;
     if (sym->rev_dep.expr)
         tri = expr_calc_value(sym->rev_dep.expr);
     if (tri == mod && sym_get_type(sym) == S_BOOLEAN)
         tri = yes;
     if (sym->rev_dep.tri != tri) {
         sym->rev_dep.tri = tri;
         sym_set_changed(sym);
     }
 }
References E_OR, expr_value::expr, expr_calc_value(), for_all_prompts, mod, modules_val, no, symbol::rev_dep, S_BOOLEAN, S_TRISTATE, property::sym, sym_get_type(), sym_is_choice_value(), sym_set_changed(), expr_value::tri, symbol::type, symbol::visible, property::visible, and yes.
Referenced by sym_calc_choice(), and sym_calc_value().
sym_check_deps()
struct symbol* sym_check_deps (struct symbol * sym)
Definition at line 790 of file symbol.c.
 {
     struct symbol *sym2;
     struct property *prop;
     if (sym->flags & SYMBOL_CHECK) {
         printf("Warning! Found recursive dependency: %s", sym->name);
         return sym;
     }
     if (sym->flags & SYMBOL_CHECKED)
         return NULL;
     sym->flags |= (SYMBOL_CHECK | SYMBOL_CHECKED);
     sym2 = sym_check_expr_deps(sym->rev_dep.expr);
     if (sym2)
         goto out;
     for (prop = sym->prop; prop; prop = prop->next) {
         if (prop->type == P_CHOICE || prop->type == P_SELECT)
             continue;
         sym2 = sym_check_expr_deps(prop->visible.expr);
         if (sym2)
             goto out;
         if (prop->type != P_DEFAULT || sym_is_choice(sym))
             continue;
         sym2 = sym_check_expr_deps(prop->expr);
         if (sym2)
             goto out;
     }
 out:
     if (sym2) {
         printf(" %s", sym->name);
         if (sym2 == sym) {
             printf("\n");
             sym2 = NULL;
         }
     }
     sym->flags &= ~SYMBOL_CHECK;
     return sym2;
 }
References expr_value::expr, property::expr, symbol::flags, symbol::name, property::next, NULL, out(), P_CHOICE, P_DEFAULT, P_SELECT, printf, symbol::prop, symbol::rev_dep, property::sym, sym_check_expr_deps(), sym_is_choice(), SYMBOL_CHECK, SYMBOL_CHECKED, property::type, and property::visible.
Referenced by sym_check_expr_deps().
sym_check_expr_deps()
static struct symbol* sym_check_expr_deps (struct expr * e) static
Definition at line 760 of file symbol.c.
 {
     struct symbol *sym;
     if (!e)
         return NULL;
     switch (e->type) {
     case E_OR:
     case E_AND:
         sym = sym_check_expr_deps(e->left.expr);
         if (sym)
             return sym;
         return sym_check_expr_deps(e->right.expr);
     case E_NOT:
         return sym_check_expr_deps(e->left.expr);
     case E_EQUAL:
     case E_UNEQUAL:
         sym = sym_check_deps(e->left.sym);
         if (sym)
             return sym;
         return sym_check_deps(e->right.sym);
     case E_SYMBOL:
         return sym_check_deps(e->left.sym);
     default:
         break;
     }
     printf("Oops! How to check %d?\n", e->type);
     return NULL;
 }
References E_AND, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, NULL, printf, expr::right, expr_data::sym, sym_check_deps(), and expr::type.
Referenced by sym_check_deps().
sym_clear_all_valid()
void sym_clear_all_valid (void)
Definition at line 371 of file symbol.c.
 {
     struct symbol *sym;
     int i;
     for_all_symbols(i, sym)
         sym->flags &= ~SYMBOL_VALID;
     sym_change_count++;
     if (modules_sym)
         sym_calc_value(modules_sym);
 }
References symbol::flags, for_all_symbols, i, modules_sym, sym_calc_value(), sym_change_count, and SYMBOL_VALID.
Referenced by conf_write(), sym_set_string_value(), and sym_set_tristate_value().
sym_find()
struct symbol* sym_find (const char * name)
Definition at line 692 of file symbol.c.
 {
     struct symbol *symbol = NULL;
     const char *ptr;
     int hash = 0;
     if (!name)
         return NULL;
     if (name[0] && !name[1]) {
         switch (name[0]) {
         case 'y': return &symbol_yes;
         case 'm': return &symbol_mod;
         case 'n': return &symbol_no;
         }
     }
     for (ptr = name; *ptr; ptr++)
         hash += *ptr;
     hash &= 0xff;
     for (symbol = symbol_hash[hash]; symbol; symbol = symbol->next) {
         if (!strcmp(symbol->name, name) &&
             !(symbol->flags & SYMBOL_CONST))
                 break;
     }
     return symbol;
 }
References symbol::flags, symbol::name, symbol::next, NULL, strcmp, SYMBOL_CONST, symbol_mod, symbol_no, and symbol_yes.
Referenced by conf_read_simple().
sym_get_choice_prop()
struct property* sym_get_choice_prop (struct symbol * sym)
Definition at line 111 of file symbol.c.
 {
     struct property *prop;
     for_all_choices(sym, prop)
         return prop;
     return NULL;
 }
References for_all_choices, NULL, and property::sym.
Referenced by conf_read(), conf_read_simple(), menu_finalize(), sym_calc_choice(), sym_calc_value(), and sym_set_tristate_value().
sym_get_default_prop()
struct property* sym_get_default_prop (struct symbol * sym)
Definition at line 120 of file symbol.c.
 {
     struct property *prop;
     for_all_defaults(sym, prop) {
         prop->visible.tri = expr_calc_value(prop->visible.expr);
         if (prop->visible.tri != no)
             return prop;
     }
     return NULL;
 }
References expr_value::expr, expr_calc_value(), for_all_defaults, no, NULL, property::sym, expr_value::tri, and property::visible.
Referenced by sym_calc_value().
sym_get_range_prop()
struct property* sym_get_range_prop (struct symbol * sym)
Definition at line 132 of file symbol.c.
 {
     struct property *prop;
     for_all_properties(sym, prop, P_RANGE) {
         prop->visible.tri = expr_calc_value(prop->visible.expr);
         if (prop->visible.tri != no)
             return prop;
     }
     return NULL;
 }
References expr_value::expr, expr_calc_value(), for_all_properties, no, NULL, P_RANGE, property::sym, expr_value::tri, and property::visible.
Referenced by sym_string_within_range(), and sym_validate_range().
sym_get_range_val()
static int sym_get_range_val (struct symbol * sym, int base) static
Definition at line 144 of file symbol.c.
 {
     sym_calc_value(sym);
     switch (sym->type) {
     case S_INT:
         base = 10;
         break;
     case S_HEX:
         base = 16;
         break;
     default:
         break;
     }
     return strtol(sym->curr.val, NULL, base);
 }
References base, NULL, S_HEX, S_INT, strtol(), property::sym, sym_calc_value(), and symbol::type.
Referenced by sym_string_within_range(), and sym_validate_range().
sym_get_string_value()
const char* sym_get_string_value (struct symbol * sym)
Definition at line 618 of file symbol.c.
 {
     tristate val;
     switch (sym->type) {
     case S_BOOLEAN:
     case S_TRISTATE:
         val = sym_get_tristate_value(sym);
         switch (val) {
         case no:
             return "n";
         case mod:
             return "m";
         case yes:
             return "y";
         }
         break;
     default:
         ;
     }
     return (const char *)sym->curr.val;
 }
References mod, no, S_BOOLEAN, S_TRISTATE, property::sym, sym_get_tristate_value(), symbol::type, val, and yes.
Referenced by build_conf(), conf_expand_value(), conf_string(), conf_sym(), conf_write(), expr_calc_value(), fill_row(), get_prompt_str(), get_relations_str(), main(), ConfigLineEdit::show(), and ConfigItem::updateMenu().
sym_get_type()
enum symbol_type sym_get_type (struct symbol * sym)
Definition at line 44 of file symbol.c.
 {
     enum symbol_type type = sym->type;
     if (type == S_TRISTATE) {
         if (sym_is_choice_value(sym) && sym->visible == yes)
             type = S_BOOLEAN;
         else if (modules_val == no)
             type = S_BOOLEAN;
     }
     return type;
 }
References symbol::flags, getenv, p, utsname::release, S_STRING, sym_add_default(), sym_lookup(), SYMBOL_AUTO, symbol::type, and uname().
Referenced by build_conf(), change_sym_value(), ConfigList::changeValue(), conf_askvalue(), conf_string(), fill_row(), ConfigList::setValue(), sym_calc_value(), sym_calc_visibility(), sym_tristate_within_range(), and ConfigItem::updateMenu().
sym_init()
void sym_init (void)
Definition at line 44 of file symbol.c.
 {
     struct symbol *sym;
     struct utsname uts;
     char *p;
     static bool inited = false;
     if (inited)
         return;
     inited = true;
     uname(&uts);
     sym = sym_lookup("ARCH", 0);
     sym->type = S_STRING;
     sym->flags |= SYMBOL_AUTO;
     p = getenv("ARCH");
     if (p)
         sym_add_default(sym, p);
     sym = sym_lookup("KERNELVERSION", 0);
     sym->type = S_STRING;
     sym->flags |= SYMBOL_AUTO;
     p = getenv("KERNELVERSION");
     if (p)
         sym_add_default(sym, p);
     sym = sym_lookup("UNAME_RELEASE", 0);
     sym->type = S_STRING;
     sym->flags |= SYMBOL_AUTO;
     sym_add_default(sym, uts.release);
 }
sym_is_changable()
bool sym_is_changable (struct symbol * sym)
Definition at line 641 of file symbol.c.
 {
     return sym->visible > sym->rev_dep.tri;
 }
References symbol::rev_dep, property::sym, expr_value::tri, and symbol::visible.
Referenced by build_conf(), check_conf(), conf_askvalue(), conf_choice(), and ConfigItem::updateMenu().
sym_lookup()
struct symbol* sym_lookup (const char * name, int isconst)
Definition at line 646 of file symbol.c.
 {
     struct symbol *symbol;
     const char *ptr;
     char *new_name;
     int hash = 0;
     if (name) {
         if (name[0] && !name[1]) {
             switch (name[0]) {
             case 'y': return &symbol_yes;
             case 'm': return &symbol_mod;
             case 'n': return &symbol_no;
             }
         }
         for (ptr = name; *ptr; ptr++)
             hash += *ptr;
         hash &= 0xff;
         for (symbol = symbol_hash[hash]; symbol; symbol = symbol->next) {
             if (!strcmp(symbol->name, name)) {
                 if ((isconst && symbol->flags & SYMBOL_CONST) ||
                     (!isconst && !(symbol->flags & SYMBOL_CONST)))
                     return symbol;
             }
         }
         new_name = strdup(name);
     } else {
         new_name = NULL;
         hash = 256;
     }
     symbol = malloc(sizeof(*symbol));
     memset(symbol, 0, sizeof(*symbol));
     symbol->name = new_name;
     symbol->type = S_UNKNOWN;
     symbol->flags = SYMBOL_NEW;
     if (isconst)
         symbol->flags |= SYMBOL_CONST;
     symbol->next = symbol_hash[hash];
     symbol_hash[hash] = symbol;
     return symbol;
 }
References symbol::flags, malloc, memset, symbol::name, symbol::next, NULL, S_UNKNOWN, strcmp, strdup(), SYMBOL_CONST, symbol_mod, SYMBOL_NEW, symbol_no, symbol_yes, and symbol::type.
Referenced by conf_expand_value(), conf_write(), main(), sym_add_default(), and sym_get_type().
sym_re_search()
struct symbol** sym_re_search (const char * pattern)
Definition at line 721 of file symbol.c.
 {
     struct symbol *sym, **sym_arr = NULL;
     int i, cnt, size;
     regex_t re;
     cnt = size = 0;
     /* Skip if empty */
     if (strlen(pattern) == 0)
         return NULL;
     if (regcomp(&re, pattern, REG_EXTENDED|REG_NOSUB|REG_ICASE))
         return NULL;
     for_all_symbols(i, sym) {
         if (sym->flags & SYMBOL_CONST || !sym->name)
             continue;
         if (regexec(&re, sym->name, 0, NULL, 0))
             continue;
         if (cnt + 1 >= size) {
             void *tmp = sym_arr;
             size += 16;
             sym_arr = realloc(sym_arr, size * sizeof(struct symbol *));
             if (!sym_arr) {
                 free(tmp);
                 return NULL;
             }
         }
         sym_arr[cnt++] = sym;
     }
     if (sym_arr)
         sym_arr[cnt] = NULL;
     regfree(&re);
     return sym_arr;
 }
References cnt, symbol::flags, for_all_symbols, free, i, symbol::name, NULL, pattern, realloc, REG_EXTENDED, REG_ICASE, REG_NOSUB, regcomp(), regexec, regfree(), size, strlen(), and SYMBOL_CONST.
Referenced by search_conf().
sym_set_all_changed()
void sym_set_all_changed (void)
Definition at line 394 of file symbol.c.
 {
     struct symbol *sym;
     int i;
     for_all_symbols(i, sym)
         sym_set_changed(sym);
 }
References for_all_symbols, i, and sym_set_changed().
Referenced by sym_set_tristate_value().
sym_set_changed()
void sym_set_changed (struct symbol * sym)
Definition at line 383 of file symbol.c.
 {
     struct property *prop;
     sym->flags |= SYMBOL_CHANGED;
     for (prop = sym->prop; prop; prop = prop->next) {
         if (prop->menu)
             prop->menu->flags |= MENU_CHANGED;
     }
 }
References symbol::flags, menu::flags, property::menu, MENU_CHANGED, property::next, symbol::prop, property::sym, and SYMBOL_CHANGED.
Referenced by sym_calc_value(), sym_calc_visibility(), sym_set_all_changed(), sym_set_string_value(), and sym_set_tristate_value().
sym_set_string_value()
bool sym_set_string_value (struct symbol * sym, const char * newval)
Definition at line 569 of file symbol.c.
 {
     const char *oldval;
     char *val;
     int size;
     switch (sym->type) {
     case S_BOOLEAN:
     case S_TRISTATE:
         switch (newval[0]) {
         case 'y': case 'Y':
             return sym_set_tristate_value(sym, yes);
         case 'm': case 'M':
             return sym_set_tristate_value(sym, mod);
         case 'n': case 'N':
             return sym_set_tristate_value(sym, no);
         }
         return false;
     default:
         ;
     }
     if (!sym_string_within_range(sym, newval))
         return false;
     if (sym->flags & SYMBOL_NEW) {
         sym->flags &= ~SYMBOL_NEW;
         sym_set_changed(sym);
     }
     oldval = sym->user.val;
     size = strlen(newval) + 1;
     if (sym->type == S_HEX && (newval[0] != '0' || (newval[1] != 'x' && newval[1] != 'X'))) {
         size += 2;
         sym->user.val = val = malloc(size);
         *val++ = '0';
         *val++ = 'x';
     } else if (!oldval || strcmp(oldval, newval))
         sym->user.val = val = malloc(size);
     else
         return true;
     strcpy(val, newval);
     free((void *)oldval);
     sym_clear_all_valid();
     return true;
 }
References symbol::flags, free, malloc, mod, no, S_BOOLEAN, S_HEX, S_TRISTATE, size, strcmp, strcpy, strlen(), property::sym, sym_clear_all_valid(), sym_set_changed(), sym_set_tristate_value(), sym_string_within_range(), SYMBOL_NEW, symbol::type, symbol::user, val, symbol_value::val, and yes.
Referenced by conf_string(), ConfigLineEdit::keyPressEvent(), and renderer_edited().
sym_set_tristate_value()
bool sym_set_tristate_value (struct symbol * sym, tristate val)
Definition at line 422 of file symbol.c.
 {
     tristate oldval = sym_get_tristate_value(sym);
     if (oldval != val && !sym_tristate_within_range(sym, val))
         return false;
     if (sym->flags & SYMBOL_NEW) {
         sym->flags &= ~SYMBOL_NEW;
         sym_set_changed(sym);
     }
     /*
      * setting a choice value also resets the new flag of the choice
      * symbol and all other choice values.
      */
     if (sym_is_choice_value(sym) && val == yes) {
         struct symbol *cs = prop_get_symbol(sym_get_choice_prop(sym));
         struct property *prop;
         struct expr *e;
         cs->user.val = sym;
         cs->flags &= ~SYMBOL_NEW;
         prop = sym_get_choice_prop(cs);
         for (e = prop->expr; e; e = e->left.expr) {
             if (e->right.sym->visible != no)
                 e->right.sym->flags &= ~SYMBOL_NEW;
         }
     }
     sym->user.tri = val;
     if (oldval != val) {
         sym_clear_all_valid();
         if (sym == modules_sym)
             sym_set_all_changed();
     }
     return true;
 }
References property::expr, symbol::flags, modules_sym, no, prop_get_symbol(), expr::right, expr_data::sym, sym_clear_all_valid(), sym_get_choice_prop(), sym_get_tristate_value(), sym_is_choice_value(), sym_set_all_changed(), sym_set_changed(), sym_tristate_within_range(), SYMBOL_NEW, symbol_value::tri, symbol::user, val, symbol_value::val, symbol::visible, and yes.
Referenced by change_sym_value(), conf(), conf_choice(), conf_sym(), ConfigList::setValue(), sym_set_choice_value(), sym_set_string_value(), and sym_toggle_tristate_value().
sym_string_valid()
bool sym_string_valid (struct symbol * sym, const char * str)
Definition at line 484 of file symbol.c.
 {
     signed char ch;
     switch (sym->type) {
     case S_STRING:
         return true;
     case S_INT:
         ch = *str++;
         if (ch == '-')
             ch = *str++;
         if (!isdigit(ch))
             return false;
         if (ch == '0' && *str != 0)
             return false;
         while ((ch = *str++)) {
             if (!isdigit(ch))
                 return false;
         }
         return true;
     case S_HEX:
         if (str[0] == '0' && (str[1] == 'x' || str[1] == 'X'))
             str += 2;
         ch = *str++;
         do {
             if (!isxdigit(ch))
                 return false;
         } while ((ch = *str++));
         return true;
     case S_BOOLEAN:
     case S_TRISTATE:
         switch (str[0]) {
         case 'y': case 'Y':
         case 'm': case 'M':
         case 'n': case 'N':
             return true;
         }
         return false;
     default:
         return false;
     }
 }
References isdigit, isxdigit, S_BOOLEAN, S_HEX, S_INT, S_STRING, S_TRISTATE, str, and symbol::type.
Referenced by conf_read_simple(), menu_range_valid_sym(), and sym_string_within_range().
sym_string_within_range()
bool sym_string_within_range (struct symbol * sym, const char * str)
Definition at line 527 of file symbol.c.
 {
     struct property *prop;
     int val;
     switch (sym->type) {
     case S_STRING:
         return sym_string_valid(sym, str);
     case S_INT:
         if (!sym_string_valid(sym, str))
             return false;
         prop = sym_get_range_prop(sym);
         if (!prop)
             return true;
         val = strtol(str, NULL, 10);
         return val >= sym_get_range_val(prop->expr->left.sym, 10) &&
                val <= sym_get_range_val(prop->expr->right.sym, 10);
     case S_HEX:
         if (!sym_string_valid(sym, str))
             return false;
         prop = sym_get_range_prop(sym);
         if (!prop)
             return true;
         val = strtol(str, NULL, 16);
         return val >= sym_get_range_val(prop->expr->left.sym, 16) &&
                val <= sym_get_range_val(prop->expr->right.sym, 16);
     case S_BOOLEAN:
     case S_TRISTATE:
         switch (str[0]) {
         case 'y': case 'Y':
             return sym_tristate_within_range(sym, yes);
         case 'm': case 'M':
             return sym_tristate_within_range(sym, mod);
         case 'n': case 'N':
             return sym_tristate_within_range(sym, no);
         }
         return false;
     default:
         return false;
     }
 }
References property::expr, mod, no, NULL, expr::right, S_BOOLEAN, S_HEX, S_INT, S_STRING, S_TRISTATE, str, strtol(), expr_data::sym, property::sym, sym_get_range_prop(), sym_get_range_val(), sym_string_valid(), sym_tristate_within_range(), symbol::type, val, and yes.
Referenced by conf_read(), and sym_set_string_value().
sym_toggle_tristate_value()
tristate sym_toggle_tristate_value (struct symbol * sym)
Definition at line 461 of file symbol.c.
 {
     tristate oldval, newval;
     oldval = newval = sym_get_tristate_value(sym);
     do {
         switch (newval) {
         case no:
             newval = mod;
             break;
         case mod:
             newval = yes;
             break;
         case yes:
             newval = no;
             break;
         }
         if (sym_set_tristate_value(sym, newval))
             break;
     } while (oldval != newval);
     return newval;
 }
References mod, no, sym_get_tristate_value(), sym_set_tristate_value(), and yes.
Referenced by ConfigList::changeValue(), conf(), and toggle_sym_value().
sym_tristate_within_range()
bool sym_tristate_within_range (struct symbol * sym, tristate val)
Definition at line 403 of file symbol.c.
 {
     int type = sym_get_type(sym);
     if (sym->visible == no)
         return false;
     if (type != S_BOOLEAN && type != S_TRISTATE)
         return false;
     if (type == S_BOOLEAN && val == mod)
         return false;
     if (sym->visible <= sym->rev_dep.tri)
         return false;
     if (sym_is_choice_value(sym) && sym->visible == yes)
         return val == yes;
     return val >= sym->rev_dep.tri && val <= sym->visible;
 }
References mod, no, symbol::rev_dep, S_BOOLEAN, S_TRISTATE, sym_get_type(), sym_is_choice_value(), expr_value::tri, type, val, symbol::visible, and yes.
Referenced by change_sym_value(), conf_askvalue(), conf_sym(), fill_row(), sym_set_tristate_value(), sym_string_within_range(), and ConfigItem::updateMenu().
sym_type_name()
const char* sym_type_name (enum symbol_type type)
Definition at line 90 of file symbol.c.
 {
     switch (type) {
     case S_BOOLEAN:
         return "boolean";
     case S_TRISTATE:
         return "tristate";
     case S_INT:
         return "integer";
     case S_HEX:
         return "hex";
     case S_STRING:
         return "string";
     case S_UNKNOWN:
         return "unknown";
     case S_OTHER:
         break;
     }
     return "???";
 }
References S_BOOLEAN, S_HEX, S_INT, S_OTHER, S_STRING, S_TRISTATE, S_UNKNOWN, and type.
Referenced by menu_set_type(), and ConfigMainWindow::setHelp().
sym_validate_range()
static void sym_validate_range (struct symbol * sym) static
Definition at line 160 of file symbol.c.
 {
     struct property *prop;
     int base, val, val2;
     char str[64];
     switch (sym->type) {
     case S_INT:
         base = 10;
         break;
     case S_HEX:
         base = 16;
         break;
     default:
         return;
     }
     prop = sym_get_range_prop(sym);
     if (!prop)
         return;
     val = strtol(sym->curr.val, NULL, base);
     val2 = sym_get_range_val(prop->expr->left.sym, base);
     if (val >= val2) {
         val2 = sym_get_range_val(prop->expr->right.sym, base);
         if (val <= val2)
             return;
     }
     if (sym->type == S_INT)
         sprintf(str, "%d", val2);
     else
         sprintf(str, "0x%x", val2);
     sym->curr.val = strdup(str);
 }
References base, property::expr, NULL, expr::right, S_HEX, S_INT, sprintf(), str, strdup(), strtol(), expr_data::sym, property::sym, sym_get_range_prop(), sym_get_range_val(), symbol::type, and val.
Referenced by sym_calc_value().
Variable Documentation
modules_sym
struct symbol* modules_sym
Definition at line 34 of file symbol.c.
Referenced by conf_read_simple(), conf_write(), menu_check_dep(), sym_calc_value(), sym_clear_all_valid(), and sym_set_tristate_value().
modules_val
tristate modules_val
Definition at line 35 of file symbol.c.
Referenced by sym_calc_value(), and sym_calc_visibility().
sym_change_count
int sym_change_count
Definition at line 33 of file symbol.c.
Referenced by ConfigMainWindow::closeEvent(), conf_read(), conf_write(), and sym_clear_all_valid().
symbol_empty
struct symbol symbol_empty
Initial value:
= {
    .name = "",
    .curr = { "", no },
    .flags = SYMBOL_VALID,
}
Definition at line 27 of file symbol.c.
Referenced by sym_calc_value().
symbol_mod
struct symbol symbol_mod
Initial value:
= {
    .name = "m",
    .curr = { "m", mod },
    .flags = SYMBOL_MOD|SYMBOL_VALID,
}
Definition at line 19 of file symbol.c.
Referenced by expr_depends_symbol(), expr_join_and(), expr_join_or(), expr_trans_compare(), expr_transform(), menu_check_dep(), menu_finalize(), sym_find(), and sym_lookup().
symbol_no
struct symbol symbol_no
Initial value:
= {
    .name = "n",
    .curr = { "n", no },
    .flags = SYMBOL_NO|SYMBOL_VALID,
}
Definition at line 23 of file symbol.c.
Referenced by __expr_eliminate_eq(), expr_depends_symbol(), expr_eliminate_dups1(), expr_eliminate_dups2(), expr_eliminate_yn(), expr_extract_eq(), expr_is_no(), expr_join_and(), expr_join_or(), expr_trans_bool(), expr_trans_compare(), expr_transform(), menu_finalize(), sym_calc_value(), sym_find(), and sym_lookup().
symbol_yes
struct symbol symbol_yes
Initial value:
= {
    .name = "y",
    .curr = { "y", yes },
    .flags = SYMBOL_YES|SYMBOL_VALID,
}
Definition at line 1 of file symbol.c.
Referenced by __expr_eliminate_eq(), expr_depends_symbol(), expr_eliminate_dups1(), expr_eliminate_dups2(), expr_eliminate_yn(), expr_extract_eq(), expr_is_yes(), expr_join_and(), expr_join_or(), expr_trans_compare(), expr_transform(), sym_find(), and sym_lookup().