Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/ext.c File Reference
ext.c File Reference
#include "volume_id_internal.h"
#include "bb_e2fs_defs.h"
Macros
#define EXT_SUPERBLOCK_OFFSET 0x400
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_ext (struct volume_id *id)
Macro Definition Documentation
EXT_SUPERBLOCK_OFFSET
#define EXT_SUPERBLOCK_OFFSET 0x400
Definition at line 30 of file ext.c.
off
#define off ((uint64_t)0)
Function Documentation
volume_id_probe_ext()
int FAST_FUNC volume_id_probe_ext (struct volume_id * id)
Definition at line 32 of file ext.c.
 {
 #define off ((uint64_t)0)
     struct ext2_super_block *es;
     dbg("ext: probing at offset 0x%llx", (unsigned long long) off);
     es = volume_id_get_buffer(id, off + EXT_SUPERBLOCK_OFFSET, 0x200);
     if (es == NULL)
         return -1;
     if (es->s_magic != cpu_to_le16(EXT2_SUPER_MAGIC)) {
         dbg("ext: no magic found");
         return -1;
     }
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
 //  volume_id_set_label_raw(id, es->volume_name, 16);
     volume_id_set_label_string(id, (void*)es->s_volume_name, 16);
     volume_id_set_uuid(id, es->s_uuid, UUID_DCE);
     dbg("ext: label '%s' uuid '%s'", id->label, id->uuid);
 #if ENABLE_FEATURE_BLKID_TYPE
     if ((es->s_feature_ro_compat & cpu_to_le32(EXT4_FEATURE_RO_COMPAT_HUGE_FILE | EXT4_FEATURE_RO_COMPAT_DIR_NLINK))
      || (es->s_feature_incompat & cpu_to_le32(EXT4_FEATURE_INCOMPAT_EXTENTS | EXT4_FEATURE_INCOMPAT_64BIT))
     ) {
         id->type = "ext4";
     }
     else if (es->s_feature_compat & cpu_to_le32(EXT3_FEATURE_COMPAT_HAS_JOURNAL))
         id->type = "ext3";
     else
         id->type = "ext2";
 #endif
     return 0;
 }
References cpu_to_le16, cpu_to_le32, dbg, EXT2_SUPER_MAGIC, EXT3_FEATURE_COMPAT_HAS_JOURNAL, EXT4_FEATURE_INCOMPAT_64BIT, EXT4_FEATURE_INCOMPAT_EXTENTS, EXT4_FEATURE_RO_COMPAT_DIR_NLINK, EXT4_FEATURE_RO_COMPAT_HUGE_FILE, EXT_SUPERBLOCK_OFFSET, volume_id::label, NULL, off, ext2_super_block::s_feature_compat, ext2_super_block::s_feature_incompat, ext2_super_block::s_feature_ro_compat, ext2_super_block::s_magic, ext2_super_block::s_uuid, ext2_super_block::s_volume_name, volume_id::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().