Fennix: Userspace/apps/system/init/init.c File Reference
init.c File Reference
#include "printf.h"
Data Structures
struct Elf64_auxv_t
union Elf64_auxv_t.a_un
Macros
#define AT_NULL 0
#define AT_IGNORE 1
#define AT_EXECFD 2
#define AT_PHDR 3
#define AT_PHENT 4
#define AT_PHNUM 5
#define AT_PAGESZ 6
#define AT_BASE 7
#define AT_FLAGS 8
#define AT_ENTRY 9
#define AT_NOTELF 10
#define AT_UID 11
#define AT_EUID 12
#define AT_GID 13
#define AT_EGID 14
#define AT_PLATFORM 15
#define AT_HWCAP 16
#define AT_CLKTCK 17
#define AT_SECURE 23
#define AT_BASE_PLATFORM 24
#define AT_RANDOM 25
#define AT_HWCAP2 26
#define AT_EXECFN 31
#define AT_SYSINFO 32
#define AT_SYSINFO_EHDR 33
#define AT_L1I_CACHESHAPE 34
#define AT_L1D_CACHESHAPE 35
#define AT_L2_CACHESHAPE 36
#define AT_L3_CACHESHAPE 37
#define AT_L1I_CACHESIZE 40
#define AT_L1I_CACHEGEOMETRY 41
#define AT_L1D_CACHESIZE 42
#define AT_L1D_CACHEGEOMETRY 43
#define AT_L2_CACHESIZE 44
#define AT_L2_CACHEGEOMETRY 45
#define AT_L3_CACHESIZE 46
#define AT_L3_CACHEGEOMETRY 47
#define AT_MINSIGSTKSZ 51
Functions
static long syscall2 (int sc, long arg1, long arg2)
void putchar (char c)
int main (int argc, char *argv[], char *envp[])
Data Structure Documentation
Elf64_auxv_t
struct Elf64_auxv_t
Definition at line 54 of file abi.h.
Data Fields
uint64_t a_type
unsigned long a_type
union Elf64_auxv_t a_un
union Elf64_auxv_t a_un
Elf64_auxv_t.a_un
union Elf64_auxv_t.a_un
Definition at line 45 of file init.c.
Data Fields
uint64_t a_val
unsigned long a_val
Macro Definition Documentation
AT_BASE
#define AT_BASE 7
Definition at line 10 of file init.c.
AT_BASE_PLATFORM
#define AT_BASE_PLATFORM 24
Definition at line 22 of file init.c.
AT_CLKTCK
#define AT_CLKTCK 17
Definition at line 20 of file init.c.
AT_EGID
#define AT_EGID 14
Definition at line 17 of file init.c.
AT_ENTRY
#define AT_ENTRY 9
Definition at line 12 of file init.c.
AT_EUID
#define AT_EUID 12
Definition at line 15 of file init.c.
AT_EXECFD
#define AT_EXECFD 2
Definition at line 5 of file init.c.
AT_EXECFN
#define AT_EXECFN 31
Definition at line 25 of file init.c.
AT_FLAGS
#define AT_FLAGS 8
Definition at line 11 of file init.c.
AT_GID
#define AT_GID 13
Definition at line 16 of file init.c.
AT_HWCAP
#define AT_HWCAP 16
Definition at line 19 of file init.c.
AT_HWCAP2
#define AT_HWCAP2 26
Definition at line 24 of file init.c.
AT_IGNORE
#define AT_IGNORE 1
Definition at line 4 of file init.c.
AT_L1D_CACHEGEOMETRY
#define AT_L1D_CACHEGEOMETRY 43
Definition at line 35 of file init.c.
AT_L1D_CACHESHAPE
#define AT_L1D_CACHESHAPE 35
Definition at line 29 of file init.c.
AT_L1D_CACHESIZE
#define AT_L1D_CACHESIZE 42
Definition at line 34 of file init.c.
AT_L1I_CACHEGEOMETRY
#define AT_L1I_CACHEGEOMETRY 41
Definition at line 33 of file init.c.
AT_L1I_CACHESHAPE
#define AT_L1I_CACHESHAPE 34
Definition at line 28 of file init.c.
AT_L1I_CACHESIZE
#define AT_L1I_CACHESIZE 40
Definition at line 32 of file init.c.
AT_L2_CACHEGEOMETRY
#define AT_L2_CACHEGEOMETRY 45
Definition at line 37 of file init.c.
AT_L2_CACHESHAPE
#define AT_L2_CACHESHAPE 36
Definition at line 30 of file init.c.
AT_L2_CACHESIZE
#define AT_L2_CACHESIZE 44
Definition at line 36 of file init.c.
AT_L3_CACHEGEOMETRY
#define AT_L3_CACHEGEOMETRY 47
Definition at line 39 of file init.c.
AT_L3_CACHESHAPE
#define AT_L3_CACHESHAPE 37
Definition at line 31 of file init.c.
AT_L3_CACHESIZE
#define AT_L3_CACHESIZE 46
Definition at line 38 of file init.c.
AT_MINSIGSTKSZ
#define AT_MINSIGSTKSZ 51
Definition at line 40 of file init.c.
AT_NOTELF
#define AT_NOTELF 10
Definition at line 13 of file init.c.
AT_NULL
#define AT_NULL 0
Definition at line 3 of file init.c.
AT_PAGESZ
#define AT_PAGESZ 6
Definition at line 9 of file init.c.
AT_PHDR
#define AT_PHDR 3
Definition at line 6 of file init.c.
AT_PHENT
#define AT_PHENT 4
Definition at line 7 of file init.c.
AT_PHNUM
#define AT_PHNUM 5
Definition at line 8 of file init.c.
AT_PLATFORM
#define AT_PLATFORM 15
Definition at line 18 of file init.c.
AT_RANDOM
#define AT_RANDOM 25
Definition at line 23 of file init.c.
AT_SECURE
#define AT_SECURE 23
Definition at line 21 of file init.c.
AT_SYSINFO
#define AT_SYSINFO 32
Definition at line 26 of file init.c.
AT_SYSINFO_EHDR
#define AT_SYSINFO_EHDR 33
Definition at line 27 of file init.c.
AT_UID
#define AT_UID 11
Definition at line 14 of file init.c.
Function Documentation
main()
int main (int argc, char * argv[], char * envp[])
Definition at line 63 of file init.c.
 {
     printf_("Hello World!\n");
     printf_("I have %d arguments\n", argc);
     for (int i = 0; i < argc; i++)
         printf_("argv[%d] = (%p) %s\n", i, argv[i], argv[i]);
     for (int i = 0; envp[i]; i++)
         printf_("envp[%d] = (%p) %s\n", i, envp[i], envp[i]);
     Elf64_auxv_t *auxv;
     while (*envp++ != NULL)
         ;
     int i = 0;
     for (auxv = (Elf64_auxv_t *)envp; auxv->a_type != AT_NULL; auxv++)
     {
         printf_("%lu :%d\n", (auxv->a_type), i++);
     }
     return 0;
 }
References Elf64_auxv_t::a_type, AT_NULL, NULL, and printf_().
putchar()
void putchar (char c)
Definition at line 61 of file init.c.
 { syscall2(1, c, 0); }
References Display, Video::Display::Print(), and syscall2().
Referenced by putchar_wrapper().
syscall2()
static long syscall2 (int sc, long arg1, long arg2) inline static
Definition at line 51 of file init.c.
 {
     long ret;
     __asm__ __volatile__("syscall"
                          : "=a"(ret)
                          : "a"(sc), "D"(arg1), "S"(arg2)
                          : "rcx", "r11", "memory");
     return ret;
 }
References Execute::ret.
Referenced by putchar().