Fennix Userspace: Userspace/apps/base/busybox/coreutils/tr.c File Reference
tr.c File Reference
#include "libbb.h"
Macros
#define CLO ":]\0"
#define TR_OPT_complement (3 << 0)
#define TR_OPT_delete (1 << 2)
#define TR_OPT_squeeze_reps (1 << 3)
Enumerations
enum { ASCII = 256 , TR_BUFSIZ = (BUFSIZ > ASCII*2) ? BUFSIZ : ASCII*2 }
Functions
static void map (char *pvector, char *string1, unsigned string1_len, char *string2, unsigned string2_len)
static unsigned expand (char *arg, char **buffer_p)
static int complement (char *buffer, int buffer_len)
int tr_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
CLO
#define CLO ":]\0"
TR_OPT_complement
#define TR_OPT_complement (3 << 0)
TR_OPT_delete
#define TR_OPT_delete (1 << 2)
TR_OPT_squeeze_reps
#define TR_OPT_squeeze_reps (1 << 3)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ASCII
TR_BUFSIZ
Definition at line 65 of file tr.c.
      {
     ASCII = 256,
     /* string buffer needs to be at least as big as the whole "alphabet".
      * BUFSIZ == ASCII is ok, but we will realloc in expand
      * even for smallest patterns, let's avoid that by using *2:
      */
     TR_BUFSIZ = (BUFSIZ > ASCII*2) ? BUFSIZ : ASCII*2,
 };
Function Documentation
complement()
static int complement (char * buffer, int buffer_len) static
Definition at line 252 of file tr.c.
 {
     int len;
     char conv[ASCII];
     unsigned char ch;
     len = 0;
     ch = '\0';
     while (1) {
         if (memchr(buffer, ch, buffer_len) == NULL)
             conv[len++] = ch;
         if (++ch == '\0')
             break;
     }
     memcpy(buffer, conv, len);
     return len;
 }
References ASCII, memchr(), memcpy(), and NULL.
Referenced by tr_main().
expand()
static unsigned expand (char * arg, char ** buffer_p) static
Definition at line 102 of file tr.c.
 {
     char *buffer = *buffer_p;
     unsigned pos = 0;
     unsigned size = TR_BUFSIZ;
     unsigned i; /* can't be unsigned char: must be able to hold 256 */
     unsigned char ac;
     while (*arg) {
         if (pos + ASCII > size) {
             size += ASCII;
             *buffer_p = buffer = xrealloc(buffer, size);
         }
         if (*arg == '\\') {
             const char *z;
             arg++;
             z = arg;
             ac = bb_process_escape_sequence(&z);
             arg = (char *)z;
             arg--;
             *arg = ac;
             /*
              * fall through, there may be a range.
              * If not, current char will be treated anyway.
              */
         }
         if (arg[1] == '-') { /* "0-9..." */
             ac = arg[2];
             if (ac == '\0') { /* "0-": copy verbatim */
                 buffer[pos++] = *arg++; /* copy '0' */
                 continue; /* next iter will copy '-' and stop */
             }
             i = (unsigned char) *arg;
             arg += 3; /* skip 0-9 or 0-\ */
             if (ac == '\\') {
                 const char *z;
                 z = arg;
                 ac = bb_process_escape_sequence(&z);
                 arg = (char *)z;
             }
             while (i <= ac) /* ok: i is unsigned _int_ */
                 buffer[pos++] = i++;
             continue;
         }
         if ((ENABLE_FEATURE_TR_CLASSES || ENABLE_FEATURE_TR_EQUIV)
          && *arg == '['
         ) {
             arg++;
             i = (unsigned char) *arg++;
             /* "[xyz...". i=x, arg points to y */
             if (ENABLE_FEATURE_TR_CLASSES && i == ':') { /* [:class:] */
 #define CLO ":]\0"
                 static const char classes[] ALIGN1 =
                     "alpha"CLO "alnum"CLO "digit"CLO
                     "lower"CLO "upper"CLO "space"CLO
                     "blank"CLO "punct"CLO "cntrl"CLO
                     "xdigit"CLO;
                 enum {
                     CLASS_invalid = 0, /* we increment the retval */
                     CLASS_alpha = 1,
                     CLASS_alnum = 2,
                     CLASS_digit = 3,
                     CLASS_lower = 4,
                     CLASS_upper = 5,
                     CLASS_space = 6,
                     CLASS_blank = 7,
                     CLASS_punct = 8,
                     CLASS_cntrl = 9,
                     CLASS_xdigit = 10,
                     //CLASS_graph = 11,
                     //CLASS_print = 12,
                 };
                 smalluint j;
                 char *tmp;
                 /* xdigit needs 8, not 7 */
                 i = 7 + (arg[0] == 'x');
                 tmp = xstrndup(arg, i);
                 j = index_in_strings(classes, tmp) + 1;
                 free(tmp);
                 if (j == CLASS_invalid)
                     goto skip_bracket;
                 arg += i;
                 if (j == CLASS_alnum || j == CLASS_digit || j == CLASS_xdigit) {
                     for (i = '0'; i <= '9'; i++)
                         buffer[pos++] = i;
                 }
                 if (j == CLASS_alpha || j == CLASS_alnum || j == CLASS_upper) {
                     for (i = 'A'; i <= 'Z'; i++)
                         buffer[pos++] = i;
                 }
                 if (j == CLASS_alpha || j == CLASS_alnum || j == CLASS_lower) {
                     for (i = 'a'; i <= 'z'; i++)
                         buffer[pos++] = i;
                 }
                 if (j == CLASS_space || j == CLASS_blank) {
                     buffer[pos++] = '\t';
                     if (j == CLASS_space) {
                         buffer[pos++] = '\n';
                         buffer[pos++] = '\v';
                         buffer[pos++] = '\f';
                         buffer[pos++] = '\r';
                     }
                     buffer[pos++] = ' ';
                 }
                 if (j == CLASS_punct || j == CLASS_cntrl) {
                     for (i = '\0'; i < ASCII; i++) {
                         if ((j == CLASS_punct && isprint_asciionly(i) && !isalnum(i) && !isspace(i))
                          || (j == CLASS_cntrl && iscntrl(i))
                         ) {
                             buffer[pos++] = i;
                         }
                     }
                 }
                 if (j == CLASS_xdigit) {
                     for (i = 'A'; i <= 'F'; i++) {
                         buffer[pos + 6] = i | 0x20;
                         buffer[pos++] = i;
                     }
                     pos += 6;
                 }
                 continue;
             }
             /* "[xyz...", i=x, arg points to y */
             if (ENABLE_FEATURE_TR_EQUIV && i == '=') { /* [=CHAR=] */
                 buffer[pos++] = *arg; /* copy CHAR */
                 if (!arg[0] || arg[1] != '=' || arg[2] != ']')
                     bb_show_usage();
                 arg += 3;  /* skip CHAR=] */
                 continue;
             }
             /* The rest of "[xyz..." cases is treated as normal
              * string, "[" has no special meaning here:
              * tr "[a-z]" "[A-Z]" can be written as tr "a-z" "A-Z",
              * also try tr "[a-z]" "_A-Z+" and you'll see that
              * [] is not special here.
              */
  skip_bracket:
             arg -= 2; /* points to "[" in "[xyz..." */
         }
         buffer[pos++] = *arg++;
     }
     return pos;
 }
References ALIGN1, ASCII, bb_process_escape_sequence(), bb_show_usage(), CLO, free, i, index_in_strings(), isalnum, iscntrl, isprint_asciionly, isspace, j, pos, size, TR_BUFSIZ, xrealloc, and xstrndup().
Referenced by do_assignment_internal(), expand_main(), push_string(), scan_table(), and tr_main().
map()
static void map (char * pvector, char * string1, unsigned string1_len, char * string2, unsigned string2_len) static
Definition at line 74 of file tr.c.
 {
     char last = '0';
     unsigned i, j;
     for (j = 0, i = 0; i < string1_len; i++) {
         if (string2_len <= j)
             pvector[(unsigned char)(string1[i])] = last;
         else
             pvector[(unsigned char)(string1[i])] = last = string2[j++];
     }
 }
References i, j, and last.
Referenced by tr_main().
tr_main()
int tr_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 271 of file tr.c.
 {
     int i;
     smalluint opts;
     ssize_t read_chars;
     size_t in_index, out_index;
     unsigned last = UCHAR_MAX + 1; /* not equal to any char */
     unsigned char coded, c;
     char *str1 = xmalloc(TR_BUFSIZ);
     char *str2 = xmalloc(TR_BUFSIZ);
     int str2_length;
     int str1_length;
     char *vector = xzalloc(ASCII * 3);
     char *invec  = vector + ASCII;
     char *outvec = vector + ASCII * 2;
 #define TR_OPT_complement   (3 << 0)
 #define TR_OPT_delete       (1 << 2)
 #define TR_OPT_squeeze_reps (1 << 3)
     for (i = 0; i < ASCII; i++) {
         vector[i] = i;
         /*invec[i] = outvec[i] = FALSE; - done by xzalloc */
     }
     /* -C/-c difference is that -C complements "characters",
      * and -c complements "values" (binary bytes I guess).
      * In POSIX locale, these are the same.
      */
     /* '+': stop at first non-option */
     opts = getopt32(argv, "^+" "Ccds" "\0" "-1");
     argv += optind;
     str1_length = expand(*argv++, &str1);
     str2_length = 0;
     if (opts & TR_OPT_complement)
         str1_length = complement(str1, str1_length);
     if (*argv) {
         if (argv[0][0] == '\0')
             bb_simple_error_msg_and_die("STRING2 cannot be empty");
         str2_length = expand(*argv, &str2);
         map(vector, str1, str1_length,
                 str2, str2_length);
     }
     for (i = 0; i < str1_length; i++)
         invec[(unsigned char)(str1[i])] = TRUE;
     for (i = 0; i < str2_length; i++)
         outvec[(unsigned char)(str2[i])] = TRUE;
     goto start_from;
     /* In this loop, str1 space is reused as input buffer,
      * str2 - as output one. */
     for (;;) {
         /* If we're out of input, flush output and read more input. */
         if ((ssize_t)in_index == read_chars) {
             if (out_index) {
                 xwrite(STDOUT_FILENO, str2, out_index);
  start_from:
                 out_index = 0;
             }
             read_chars = safe_read(STDIN_FILENO, str1, TR_BUFSIZ);
             if (read_chars <= 0) {
                 if (read_chars < 0)
                     bb_simple_perror_msg_and_die(bb_msg_read_error);
                 break;
             }
             in_index = 0;
         }
         c = str1[in_index++];
         if ((opts & TR_OPT_delete) && invec[c])
             continue;
         coded = vector[c];
         if ((opts & TR_OPT_squeeze_reps) && last == coded
          && (invec[c] || outvec[coded])
         ) {
             continue;
         }
         str2[out_index++] = last = coded;
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(vector);
         free(str2);
         free(str1);
     }
     return EXIT_SUCCESS;
 }
References argv, ASCII, bb_msg_read_error, bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), c, complement(), EXIT_SUCCESS, expand(), free, getopt32(), i, last, map(), optind, safe_read(), STDIN_FILENO, STDOUT_FILENO, TR_BUFSIZ, TR_OPT_complement, TR_OPT_delete, TR_OPT_squeeze_reps, TRUE, UCHAR_MAX, xmalloc, xwrite(), and xzalloc().