Fennix: Userspace/musl/src/stdlib/qsort_nr.c File Reference
qsort_nr.c File Reference
#include <stdlib.h>
Macros
#define _BSD_SOURCE
Typedefs
typedef int(* cmpfun) (const void *, const void *)
Functions
static int wrapper_cmp (const void *v1, const void *v2, void *cmp)
void qsort (void *base, size_t nel, size_t width, cmpfun cmp)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file qsort_nr.c.
Typedef Documentation
cmpfun
typedef int(* cmpfun) (const void *, const void *)
Definition at line 4 of file qsort_nr.c.
Function Documentation
qsort()
void qsort (void * base, size_t nel, size_t width, cmpfun cmp)
Definition at line 11 of file qsort_nr.c.
 {
     __qsort_r(base, nel, width, wrapper_cmp, (void *)cmp);
 }
References __qsort_r(), cmp(), and wrapper_cmp().
wrapper_cmp()
static int wrapper_cmp (const void * v1, const void * v2, void * cmp) static
Definition at line 6 of file qsort_nr.c.
 {
     return ((cmpfun)cmp)(v1, v2);
 }
References cmp(), v1, and v2.
Referenced by qsort().