Fennix: mlibc::fd_file Struct Reference
mlibc::fd_file Struct Reference
#include <file-io.hpp>
Public Member Functions
fd_file (int fd, void(*do_dispose)(abstract_file *)=nullptr, bool force_unbuffered=false)
int fd ()
int close () override
Public Member Functions inherited from mlibc::abstract_file
abstract_file (void(*do_dispose)(abstract_file *)=nullptr)
abstract_file (const abstract_file &)=delete
abstract_file & operator= (const abstract_file &)=delete
virtual ~abstract_file ()
void dispose ()
int read (char *buffer, size_t max_size, size_t *actual_size)
int write (const char *buffer, size_t max_size, size_t *actual_size)
int unget (char c)
int update_bufmode (buffer_mode mode)
void purge ()
int flush ()
int tell (off_t *current_offset)
int seek (off_t offset, int whence)
Static Public Member Functions
static int parse_modestring (const char *mode)
Protected Member Functions
int determine_type (stream_type *type) override
int determine_bufmode (buffer_mode *mode) override
int io_read (char *buffer, size_t max_size, size_t *actual_size) override
int io_write (const char *buffer, size_t max_size, size_t *actual_size) override
int io_seek (off_t offset, int whence, off_t *new_offset) override
Private Attributes
int _fd
bool _force_unbuffered
Additional Inherited Members
Data Fields inherited from mlibc::abstract_file
RecursiveFutexLock _lock
frg::default_list_hook< abstract_file > _list_hook
Data Fields inherited from __mlibc_file_base
char * __buffer_ptr
size_t __buffer_size
size_t __offset
size_t __io_offset
size_t __valid_limit
size_t __dirty_begin
size_t __dirty_end
char * __unget_ptr
int __io_mode
int __status_bits
Detailed Description
Definition at line 79 of file file-io.hpp.
Constructor & Destructor Documentation
fd_file()
mlibc::fd_file::fd_file (int fd, void(*)(abstract_file *) do_dispose = nullptr, bool force_unbuffered = false)
Definition at line 431 of file file-io.cpp.
 : abstract_file{do_dispose}, _fd{fd}, _force_unbuffered{force_unbuffered} { }
Member Function Documentation
close()
int mlibc::fd_file::close () override virtual
Implements mlibc::abstract_file.
Definition at line 438 of file file-io.cpp.
                    {
     if(__dirty_begin != __dirty_end)
         mlibc::infoLogger() << "mlibc warning: File is not flushed before closing"
                 << frg::endlog;
     if(int e = mlibc::sys_close(_fd); e)
         return e;
     return 0;
 }
References __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, _fd, mlibc::infoLogger, and mlibc::sys_close().
determine_bufmode()
int mlibc::fd_file::determine_bufmode (buffer_mode * mode) override protected virtual
Implements mlibc::abstract_file.
Definition at line 461 of file file-io.cpp.
{
     // When isatty() is not implemented, we fall back to the safest default (no buffering).
     if(!mlibc::sys_isatty) {
         MLIBC_MISSING_SYSDEP();
         *mode = buffer_mode::no_buffer;
         return 0;
     }
     if(_force_unbuffered) {
         *mode = buffer_mode::no_buffer;
         return 0;
     }
     if(int e = mlibc::sys_isatty(_fd); !e) {
         *mode = buffer_mode::line_buffer;
         return 0;
     }else if(e == ENOTTY) {
         *mode = buffer_mode::full_buffer;
         return 0;
     }else{
         mlibc::infoLogger() << "mlibc: sys_isatty() failed while determining whether"
                 " stream is interactive" << frg::endlog;
         return -1;
     }
 }
References _fd, _force_unbuffered, ENOTTY, mlibc::full_buffer, mlibc::infoLogger, mlibc::line_buffer, MLIBC_MISSING_SYSDEP, mlibc::no_buffer, and mlibc::sys_isatty().
determine_type()
int mlibc::fd_file::determine_type (stream_type * type) override protected virtual
Implements mlibc::abstract_file.
Definition at line 447 of file file-io.cpp.
{
     off_t offset;
     int e = mlibc::sys_seek(_fd, 0, SEEK_CUR, &offset);
     if(!e) {
         *type = stream_type::file_like;
         return 0;
     }else if(e == ESPIPE) {
         *type = stream_type::pipe_like;
         return 0;
     }else{
         return e;
     }
 }
References _fd, ESPIPE, mlibc::file_like, mlibc::offset, mlibc::pipe_like, SEEK_CUR, and mlibc::sys_seek().
fd()
int mlibc::fd_file::fd ()
Definition at line 434 of file file-io.cpp.
                 {
     return _fd;
 }
References _fd.
Referenced by fileno_unlocked().
io_read()
int mlibc::fd_file::io_read (char * buffer, size_t max_size, size_t * actual_size) override protected virtual
Implements mlibc::abstract_file.
Definition at line 486 of file file-io.cpp.
{
     ssize_t s;
     if(int e = mlibc::sys_read(_fd, buffer, max_size, &s); e)
         return e;
     *actual_size = s;
     return 0;
 }
References _fd, max_size, and mlibc::sys_read().
io_seek()
int mlibc::fd_file::io_seek (off_t offset, int whence, off_t * new_offset) override protected virtual
Implements mlibc::abstract_file.
Definition at line 502 of file file-io.cpp.
{
     if(int e = mlibc::sys_seek(_fd, offset, whence, new_offset); e)
         return e;
     return 0;
 }
References _fd, mlibc::new_offset, mlibc::offset, mlibc::sys_seek(), and mlibc::whence.
io_write()
int mlibc::fd_file::io_write (const char * buffer, size_t max_size, size_t * actual_size) override protected virtual
Implements mlibc::abstract_file.
Definition at line 494 of file file-io.cpp.
{
     ssize_t s;
     if(int e = mlibc::sys_write(_fd, buffer, max_size, &s); e)
         return e;
     *actual_size = s;
     return 0;
 }
References _fd, max_size, and mlibc::sys_write().
parse_modestring()
int mlibc::fd_file::parse_modestring (const char * mode) static
Definition at line 508 of file file-io.cpp.
{
     // Consume the first char; this must be 'r', 'w' or 'a'.
     int flags = 0;
     bool has_plus = strchr(mode, '+');
     if(*mode == 'r') {
         if(has_plus) {
             flags = O_RDWR;
         }else{
             flags = O_RDONLY;
         }
     }else if(*mode == 'w') {
         if(has_plus) {
             flags = O_RDWR;
         }else{
             flags = O_WRONLY;
         }
         flags |= O_CREAT | O_TRUNC;
     }else if(*mode == 'a') {
         if(has_plus) {
             flags = O_APPEND | O_RDWR;
         }else{
             flags = O_APPEND | O_WRONLY;
         }
         flags |= O_CREAT;
     }else{
         mlibc::infoLogger() << "Illegal fopen() mode '" << *mode << "'" << frg::endlog;
     }
     mode += 1;
     // Consume additional flags.
     while(*mode) {
         if(*mode == '+') {
             mode++; // This is already handled above.
         }else if(*mode == 'b') {
             mode++; // mlibc assumes that there is no distinction between text and binary.
         }else if(*mode == 'e') {
             flags |= O_CLOEXEC;
             mode++;
         }else{
             mlibc::infoLogger() << "Illegal fopen() flag '" << mode << "'" << frg::endlog;
             mode++;
         }
     }
     return flags;
 }
References mlibc::flags, mlibc::infoLogger, O_APPEND, O_CLOEXEC, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, and strchr().
Referenced by fdopen(), and fopen().
Field Documentation
_fd
int mlibc::fd_file::_fd private
Definition at line 98 of file file-io.hpp.
Referenced by close(), determine_bufmode(), determine_type(), fd(), io_read(), io_seek(), and io_write().
_force_unbuffered
bool mlibc::fd_file::_force_unbuffered private
Definition at line 99 of file file-io.hpp.
Referenced by determine_bufmode().
The documentation for this struct was generated from the following files:
Userspace/mlibc/options/ansi/include/mlibc/file-io.hpp
Userspace/mlibc/options/ansi/generic/file-io.cpp