Fennix Userspace: Userspace/apps/base/busybox/coreutils/factor.c File Reference
factor.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Macros
#define dbg(...) ((void)0)
#define HALF_MAX UINT_MAX
#define HALF_FMT ""
#define R(a, b, c, d, e, f, g, h, i, j, A, B, C, D, E, F, G, H, I, J)
#define P(a, b, c, d, e, f, g, h, i, j, A, B, C, D, E, F, G, H, I, J)
#define WHEEL_START 5
#define WHEEL_SIZE (5 + 24 * 20)
#define square_count (((uint8_t*)&bb_common_bufsiz1)[0])
#define wheel_tab (((uint8_t*)&bb_common_bufsiz1) + 1)
Typedefs
typedef unsigned long long wide_t
typedef unsigned half_t
Functions
static void unpack_wheel (void)
static NOINLINE void print_w (wide_t n)
static NOINLINE void print_h (half_t n)
static void factorize (wide_t N)
static half_t isqrt_odd (wide_t N)
static void factorize_numstr (const char *numstr)
int factor_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const uint64_t packed_wheel []
Macro Definition Documentation
dbg
#define dbg (...) ((void)0)
Definition at line 27 of file factor.c.
HALF_FMT
#define HALF_FMT ""
Definition at line 36 of file factor.c.
HALF_MAX
#define HALF_MAX UINT_MAX
Definition at line 35 of file factor.c.
P
#define P (a, b, c, d, e, f, g, h, i, j, A, B, C, D, E, F, G, H, I, J)
Value:
    R(  (a/2),(b/2),(c/2),(d/2),(e/2),(f/2),(g/2),(h/2),(i/2),(j/2), \
        (A/2),(B/2),(C/2),(D/2),(E/2),(F/2),(G/2),(H/2),(I/2),(J/2)  )
Definition at line 54 of file factor.c.
R
#define R (a, b, c, d, e, f, g, h, i, j, A, B, C, D, E, F, G, H, I, J)
Value:
    (((uint64_t)(a<<0) | (b<<3) | (c<<6) | (d<<9) | (e<<12) | (f<<15) | (g<<18) | (h<<21) | (i<<24) | (j<<27)) << 1) | \
    (((uint64_t)(A<<0) | (B<<3) | (C<<6) | (D<<9) | (E<<12) | (F<<15) | (G<<18) | (H<<21) | (I<<24) | (J<<27)) << 31)
Definition at line 51 of file factor.c.
square_count
#define square_count (((uint8_t*)&bb_common_bufsiz1)[0])
Definition at line 88 of file factor.c.
WHEEL_SIZE
#define WHEEL_SIZE (5 + 24 * 20)
Definition at line 87 of file factor.c.
WHEEL_START
#define WHEEL_START 5
Definition at line 86 of file factor.c.
wheel_tab
#define wheel_tab (((uint8_t*)&bb_common_bufsiz1) + 1)
Definition at line 89 of file factor.c.
Typedef Documentation
half_t
typedef unsigned half_t
Definition at line 34 of file factor.c.
wide_t
typedef unsigned long long wide_t
Definition at line 30 of file factor.c.
Function Documentation
factor_main()
int factor_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 236 of file factor.c.
 {
     unpack_wheel();
     //getopt32(argv, "");
     //argv += optind;
     argv++;
     if (!*argv) {
         /* Read from stdin, several numbers per line are accepted */
         for (;;) {
             char *numstr, *line;
             line = xmalloc_fgetline(stdin);
             if (!line)
                 return EXIT_SUCCESS;
             numstr = line;
             for (;;) {
                 char *end;
                 numstr = skip_whitespace(numstr);
                 if (!numstr[0])
                     break;
                 end = skip_non_whitespace(numstr);
                 if (*end != '\0')
                     *end++ = '\0';
                 factorize_numstr(numstr);
                 numstr = end;
             }
             free(line);
         }
     }
     do {
         /* Leading spaces are ok (coreutils compat) */
         factorize_numstr(skip_whitespace(*argv));
     } while (*++argv);
     return EXIT_SUCCESS;
 }
References argv, end, EXIT_SUCCESS, factorize_numstr(), free, line, skip_non_whitespace(), skip_whitespace(), stdin, unpack_wheel(), and xmalloc_fgetline().
factorize()
static NOINLINE void factorize (wide_t N) static
Definition at line 162 of file factor.c.
 {
     unsigned w;
     half_t factor;
     half_t max_factor;
     if (N < 4)
         goto end;
     /* The code needs to be optimized for the case where
      * there are large prime factors. For example,
      * this is not hard:
      * 8262075252869367027 = 3 7 17 23 47 101 113 127 131 137 823
      *  (the largest divisor to test for largest factor 823
      *  is only ~sqrt(823) = 28, the entire factorization needs
      *  only ~33 trial divisions)
      * but this is:
      * 18446744073709551601 = 53 348051774975651917
      * the last factor requires testing up to
      * 589959129 - about 100 million iterations.
      * The slowest case (largest prime) for N < 2^64 is
      * factor 18446744073709551557 (0xffffffffffffffc5).
      */
     max_factor = isqrt_odd(N);
     if (!max_factor)
         return; /* square was detected and recursively factored */
     factor = 2;
     w = 0;
     for (;;) {
         half_t fw;
         /* The division is the most costly part of the loop.
          * On 64bit CPUs, takes at best 12 cycles, often ~20.
          */
         while ((N % factor) == 0) { /* not likely */
             N = N / factor;
             print_h(factor);
             max_factor = isqrt_odd(N);
             if (!max_factor)
                 return; /* square was detected */
         }
         if (factor >= max_factor)
             break;
         fw = factor + wheel_tab[w];
         if (fw < factor)
             break; /* overflow */
         factor = fw;
         w++;
         if (w < WHEEL_SIZE)
             continue;
         w = WHEEL_START;
     }
  end:
     if (N > 1)
         print_w(N);
     bb_putchar('\n');
 }
References bb_putchar(), end, isqrt_odd(), N, print_h(), print_w(), w, WHEEL_SIZE, WHEEL_START, and wheel_tab.
Referenced by factorize_numstr(), and isqrt_odd().
factorize_numstr()
static void factorize_numstr (const char * numstr) static
Definition at line 220 of file factor.c.
 {
     wide_t N;
     /* Leading + is ok (coreutils compat) */
     if (*numstr == '+')
         numstr++;
     N = bb_strtoull(numstr, NULL, 10);
     if (errno)
         bb_show_usage();
     printf("%llu:", N);
     square_count = 1;
     factorize(N);
 }
References bb_show_usage(), bb_strtoull(), errno, factorize(), N, NULL, printf(), and square_count.
Referenced by factor_main().
isqrt_odd()
static half_t isqrt_odd (wide_t N) static
Definition at line 138 of file factor.c.
 {
     half_t s = isqrt(N);
     /* s^2 is <= N, (s+1)^2 > N */
     /* If s^2 in fact is EQUAL to N, it's very lucky.
      * Examples:
      * factor 18446743988964486098 = 2 * 3037000493 * 3037000493
      * factor 18446743902517389507 = 3 * 2479700513 * 2479700513
      */
     if ((wide_t)s * s == N) {
         /* factorize sqrt(N), printing each factor twice */
         square_count *= 2;
         factorize(s);
         /* Let caller know we recursed */
         return 0;
     }
     /* Subtract 1 from even s, odd s won't change: */
     /* (doesnt work for zero, but we know that s != 0 here) */
     s = (s - 1) | 1;
     return s;
 }
References factorize(), isqrt(), N, s, and square_count.
Referenced by factorize().
print_h()
static NOINLINE void print_h (half_t n) static
Definition at line 131 of file factor.c.
 {
     print_w(n);
 }
References n, and print_w().
Referenced by factorize().
print_w()
static NOINLINE void print_w (wide_t n) static
Definition at line 124 of file factor.c.
 {
     unsigned rep = square_count;
     do
         printf(" %llu", n);
     while (--rep != 0);
 }
References n, printf(), and square_count.
Referenced by factorize(), and print_h().
unpack_wheel()
static void unpack_wheel (void) static
Definition at line 99 of file factor.c.
 {
     int i;
     uint8_t *p;
     setup_common_bufsiz();
     wheel_tab[0] = 1;
     wheel_tab[1] = 2;
     wheel_tab[2] = 2;
     wheel_tab[3] = 4;
     wheel_tab[4] = 2;
     p = &wheel_tab[5];
     for (i = 0; i < ARRAY_SIZE(packed_wheel); i++) {
         uint64_t v = packed_wheel[i];
         while ((v & 0xe) != 0) {
             *p = v & 0xe;
             //printf("%2u,", *p);
             p++;
             v >>= 3;
         }
         //printf("\n");
     }
 }
References ARRAY_SIZE, i, p, packed_wheel, and wheel_tab.
Referenced by factor_main().
Variable Documentation
packed_wheel
const uint64_t packed_wheel[] static
Initial value:
= {
    P( 4, 2, 4, 6, 2, 6, 4, 2, 4, 6, 6, 2, 6, 4, 2, 6, 4, 6, 8, 4),
    P( 2, 4, 2, 4,14, 4, 6, 2,10, 2, 6, 6, 4, 2, 4, 6, 2,10, 2, 4),
    P( 2,12,10, 2, 4, 2, 4, 6, 2, 6, 4, 6, 6, 6, 2, 6, 4, 2, 6, 4),
    P( 6, 8, 4, 2, 4, 6, 8, 6,10, 2, 4, 6, 2, 6, 6, 4, 2, 4, 6, 2),
    P( 6, 4, 2, 6,10, 2,10, 2, 4, 2, 4, 6, 8, 4, 2, 4,12, 2, 6, 4),
    P( 2, 6, 4, 6,12, 2, 4, 2, 4, 8, 6, 4, 6, 2, 4, 6, 2, 6,10, 2),
    P( 4, 6, 2, 6, 4, 2, 4, 2,10, 2,10, 2, 4, 6, 6, 2, 6, 6, 4, 6),
    P( 6, 2, 6, 4, 2, 6, 4, 6, 8, 4, 2, 6, 4, 8, 6, 4, 6, 2, 4, 6),
    P( 8, 6, 4, 2,10, 2, 6, 4, 2, 4, 2,10, 2,10, 2, 4, 2, 4, 8, 6),
    P( 4, 2, 4, 6, 6, 2, 6, 4, 8, 4, 6, 8, 4, 2, 4, 2, 4, 8, 6, 4),
    P( 6, 6, 6, 2, 6, 6, 4, 2, 4, 6, 2, 6, 4, 2, 4, 2,10, 2,10, 2),
    P( 6, 4, 6, 2, 6, 4, 2, 4, 6, 6, 8, 4, 2, 6,10, 8, 4, 2, 4, 2),
    P( 4, 8,10, 6, 2, 4, 8, 6, 6, 4, 2, 4, 6, 2, 6, 4, 6, 2,10, 2),
    P(10, 2, 4, 2, 4, 6, 2, 6, 4, 2, 4, 6, 6, 2, 6, 6, 6, 4, 6, 8),
    P( 4, 2, 4, 2, 4, 8, 6, 4, 8, 4, 6, 2, 6, 6, 4, 2, 4, 6, 8, 4),
    P( 2, 4, 2,10, 2,10, 2, 4, 2, 4, 6, 2,10, 2, 4, 6, 8, 6, 4, 2),
    P( 6, 4, 6, 8, 4, 6, 2, 4, 8, 6, 4, 6, 2, 4, 6, 2, 6, 6, 4, 6),
    P( 6, 2, 6, 6, 4, 2,10, 2,10, 2, 4, 2, 4, 6, 2, 6, 4, 2,10, 6),
    P( 2, 6, 4, 2, 6, 4, 6, 8, 4, 2, 4, 2,12, 6, 4, 6, 2, 4, 6, 2),
    P(12, 4, 2, 4, 8, 6, 4, 2, 4, 2,10, 2,10, 6, 2, 4, 6, 2, 6, 4),
    P( 2, 4, 6, 6, 2, 6, 4, 2,10, 6, 8, 6, 4, 2, 4, 8, 6, 4, 6, 2),
    P( 4, 6, 2, 6, 6, 6, 4, 6, 2, 6, 4, 2, 4, 2,10,12, 2, 4, 2,10),
    P( 2, 6, 4, 2, 4, 6, 6, 2,10, 2, 6, 4,14, 4, 2, 4, 2, 4, 8, 6),
    P( 4, 6, 2, 4, 6, 2, 6, 6, 4, 2, 4, 6, 2, 6, 4, 2, 4,12, 2,12),
}
Definition at line 57 of file factor.c.
Referenced by unpack_wheel().