Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/p_inter.h File Reference
p_inter.h File Reference
Functions
boolean P_GivePower (player_t *, int)
Function Documentation
P_GivePower()
boolean P_GivePower (player_t * player, int power)
Definition at line 284 of file p_inter.c.
 {
     if (power == pw_invulnerability)
     {
     player->powers[power] = INVULNTICS;
     return true;
     }
     if (power == pw_invisibility)
     {
     player->powers[power] = INVISTICS;
     player->mo->flags |= MF_SHADOW;
     return true;
     }
     if (power == pw_infrared)
     {
     player->powers[power] = INFRATICS;
     return true;
     }
     if (power == pw_ironfeet)
     {
     player->powers[power] = IRONTICS;
     return true;
     }
     if (power == pw_strength)
     {
     P_GiveBody (player, 100);
     player->powers[power] = 1;
     return true;
     }
     if (player->powers[power])
     return false;   // already got it
     player->powers[power] = 1;
     return true;
 }
References mobj_s::flags, INFRATICS, INVISTICS, INVULNTICS, IRONTICS, MF_SHADOW, player_s::mo, P_GiveBody(), player_s::powers, pw_infrared, pw_invisibility, pw_invulnerability, pw_ironfeet, and pw_strength.
Referenced by P_TouchSpecialThing(), and ST_Responder().