Fennix: Driver::MasterDeviceFile Class Reference
Driver::MasterDeviceFile Class Reference
#include <driver.hpp>
Public Types
typedef int(* drvOpen_t) (dev_t, dev_t, int, mode_t)
typedef int(* drvClose_t) (dev_t, dev_t)
typedef size_t(* drvRead_t) (dev_t, dev_t, uint8_t *, size_t, off_t)
typedef size_t(* drvWrite_t) (dev_t, dev_t, uint8_t *, size_t, off_t)
typedef int(* drvIoctl_t) (dev_t, dev_t, unsigned long, void *)
Public Member Functions
int open (int Flags, mode_t Mode) final
int close () final
size_t read (uint8_t *Buffer, size_t Size, off_t Offset) final
size_t write (uint8_t *Buffer, size_t Size, off_t Offset) final
int ioctl (unsigned long Request, void *Argp) final
void ClearBuffers ()
int ReportKeyEvent (maj_t ID, min_t MinorID, uint8_t ScanCode)
int ReportMouseEvent (maj_t ID, min_t MinorID, bool LeftButton, bool RightButton, bool MiddleButton, bool Button4, bool Button5, bool Button6, bool Button7, bool Button8, uintptr_t X, uintptr_t Y, int8_t Z, bool Relative)
int ReportNetworkPacket (maj_t ID, min_t MinorID, void *Buffer, size_t Size)
int NewBlock (maj_t ID, min_t MinorID, drvOpen_t Open, drvClose_t Close, drvRead_t Read, drvWrite_t Write, drvIoctl_t Ioctl)
int NewAudio (maj_t ID, min_t MinorID, drvOpen_t Open, drvClose_t Close, drvRead_t Read, drvWrite_t Write, drvIoctl_t Ioctl)
int NewNet (maj_t ID, min_t MinorID, drvOpen_t Open, drvClose_t Close, drvRead_t Read, drvWrite_t Write, drvIoctl_t Ioctl)
dev_t Register (maj_t ID)
int Unregister (maj_t ID, min_t MinorID)
MasterDeviceFile (const char *MasterName, const char *SlaveName, vfs::Node *Parent, int Type)
~MasterDeviceFile ()
Private Types
typedef dev_t maj_t
typedef dev_t min_t
typedef std::unordered_map< min_t, SlaveDeviceFile * > * Slaves
Private Types inherited from vfs::Node
typedef int(* open_t) (int, mode_t)
typedef int(* close_t) ()
typedef size_t(* read_t) (uint8_t *, size_t, off_t)
typedef size_t(* write_t) (uint8_t *, size_t, off_t)
typedef int(* ioctl_t) (unsigned long, void *)
Private Attributes
char SlaveName [16]
vfs::Node * SlaveParent
int DeviceType
min_t SlaveIDCounter = 0
std::unordered_map< maj_t, Slaves > SlavesMap
std::list< uint8_t > RawKeyQueue
std::list< uint8_t > KeyQueue
bool UpperCase = false
bool CapsLock = false
Private Attributes inherited from vfs::Node
open_t open_ptr = nullptr
close_t close_ptr = nullptr
read_t read_ptr = nullptr
write_t write_ptr = nullptr
ioctl_t ioctl_ptr = nullptr
class Virtual * vFS = nullptr
Node * Parent = nullptr
const char * Name
const char * FullPath
NodeType Type
ino_t IndexNode
const char * Symlink
Node * SymlinkTarget
mode_t Mode
uid_t UserIdentifier
gid_t GroupIdentifier
dev_t DeviceMajor
dev_t DeviceMinor
time_t AccessTime
time_t ModifyTime
time_t ChangeTime
off_t Size
std::vector< Node * > Children
std::vector< RefNode * > References
Additional Inherited Members
Private Member Functions inherited from vfs::Node
RefNode * CreateReference ()
void RemoveReference (RefNode *Reference)
Node (Node *Parent, const char *Name, NodeType Type, bool NoParent=false, Virtual *fs=nullptr, int *Err=nullptr)
virtual ~Node ()
Detailed Description
Definition at line 80 of file driver.hpp.
Member Typedef Documentation
drvClose_t
typedef int(* Driver::MasterDeviceFile::drvClose_t) (dev_t, dev_t)
Definition at line 100 of file driver.hpp.
drvIoctl_t
typedef int(* Driver::MasterDeviceFile::drvIoctl_t) (dev_t, dev_t, unsigned long, void *)
Definition at line 103 of file driver.hpp.
drvOpen_t
typedef int(* Driver::MasterDeviceFile::drvOpen_t) (dev_t, dev_t, int, mode_t)
Definition at line 99 of file driver.hpp.
drvRead_t
typedef size_t(* Driver::MasterDeviceFile::drvRead_t) (dev_t, dev_t, uint8_t *, size_t, off_t)
Definition at line 101 of file driver.hpp.
drvWrite_t
typedef size_t(* Driver::MasterDeviceFile::drvWrite_t) (dev_t, dev_t, uint8_t *, size_t, off_t)
Definition at line 102 of file driver.hpp.
maj_t
typedef dev_t Driver::MasterDeviceFile::maj_t private
Definition at line 83 of file driver.hpp.
min_t
typedef dev_t Driver::MasterDeviceFile::min_t private
Definition at line 84 of file driver.hpp.
Slaves
typedef std::unordered_map<min_t, SlaveDeviceFile *>* Driver::MasterDeviceFile::Slaves private
Definition at line 90 of file driver.hpp.
Constructor & Destructor Documentation
MasterDeviceFile()
Driver::MasterDeviceFile::MasterDeviceFile (const char * MasterName, const char * SlaveName, vfs::Node * Parent, int Type)
Definition at line 284 of file master.cpp.
         : Node(Parent, MasterName, NodeType::FILE)
     {
         strncpy(this->SlaveName, _SlaveName, sizeof(this->Name));
         this->DeviceType = Type;
         this->SlaveParent = Parent;
         switch (Type)
         {
         case ddt_Keyboard:
         case ddt_Mouse:
         case ddt_Joystick:
         case ddt_Gamepad:
         case ddt_Touchpad:
         case ddt_Touchscreen:
             this->Type = NodeType::CHARDEVICE;
             break;
         case ddt_SATA:
         case ddt_ATA:
         case ddt_NVMe:
             this->Type = NodeType::BLOCKDEVICE;
             break;
         default:
             break;
         }
     }
References vfs::BLOCKDEVICE, vfs::CHARDEVICE, ddt_ATA, ddt_Gamepad, ddt_Joystick, ddt_Keyboard, ddt_Mouse, ddt_NVMe, ddt_SATA, ddt_Touchpad, ddt_Touchscreen, DeviceType, vfs::Node::Name, vfs::Node::Parent, SlaveName, SlaveParent, strncpy(), and vfs::Node::Type.
~MasterDeviceFile()
Driver::MasterDeviceFile::~MasterDeviceFile ()
Definition at line 314 of file master.cpp.
     {
         foreach (auto &sm in this->SlavesMap)
         {
             Slaves slave = sm.second;
             foreach (auto &sdf in *slave)
                 delete sdf.second;
             delete slave;
         }
         this->SlavesMap.clear();
     }
References slave, and SlavesMap.
Member Function Documentation
ClearBuffers()
void Driver::MasterDeviceFile::ClearBuffers ()
Definition at line 120 of file master.cpp.
     {
         this->RawKeyQueue.clear();
         this->KeyQueue.clear();
         /* ... */
         foreach (auto &sm in this->SlavesMap)
         {
             Slaves slave = sm.second;
             foreach (auto &sdf in *slave)
                 sdf.second->ClearBuffers();
         }
     }
References slave.
close()
int Driver::MasterDeviceFile::close () final virtual
Reimplemented from vfs::Node.
Definition at line 47 of file master.cpp.
     {
         switch (this->DeviceType)
         {
         default:
             if (this->SlavesMap.empty())
                 return -ENOSYS;
             Slaves slave = this->SlavesMap.begin()->second;
             return slave->begin()->second->close();
         }
     }
References ENOSYS, and slave.
ioctl()
int Driver::MasterDeviceFile::ioctl (unsigned long Request, void * Argp) final virtual
Reimplemented from vfs::Node.
Definition at line 107 of file master.cpp.
     {
         switch (this->DeviceType)
         {
         default:
             if (this->SlavesMap.empty())
                 return -ENOSYS;
             Slaves slave = this->SlavesMap.begin()->second;
             return slave->begin()->second->ioctl(Request, Argp);
         }
     }
References ENOSYS, and slave.
NewAudio()
int Driver::MasterDeviceFile::NewAudio (maj_t ID, min_t MinorID, drvOpen_t Open, drvClose_t Close, drvRead_t Read, drvWrite_t Write, drvIoctl_t Ioctl)
Definition at line 209 of file master.cpp.
     {
         assert(this->SlavesMap.find(ID) != this->SlavesMap.end());
         Slaves slave = this->SlavesMap[ID];
         assert((*slave).find(MinorID) != (*slave).end());
         SlaveDeviceFile *sdf = (*slave)[MinorID];
         sdf->Open = Open;
         sdf->Close = Close;
         sdf->Read = Read;
         sdf->Write = Write;
         sdf->Ioctl = Ioctl;
         return 0;
     }
References assert, Driver::SlaveDeviceFile::Close, ID, Driver::SlaveDeviceFile::Ioctl, Driver::SlaveDeviceFile::Open, Driver::SlaveDeviceFile::Read, slave, SysDbg::Write(), and Driver::SlaveDeviceFile::Write.
Referenced by Driver::RegisterAudioDevice().
NewBlock()
int Driver::MasterDeviceFile::NewBlock (maj_t ID, min_t MinorID, drvOpen_t Open, drvClose_t Close, drvRead_t Read, drvWrite_t Write, drvIoctl_t Ioctl)
Definition at line 194 of file master.cpp.
     {
         assert(this->SlavesMap.find(ID) != this->SlavesMap.end());
         Slaves slave = this->SlavesMap[ID];
         assert((*slave).find(MinorID) != (*slave).end());
         SlaveDeviceFile *sdf = (*slave)[MinorID];
         sdf->Open = Open;
         sdf->Close = Close;
         sdf->Read = Read;
         sdf->Write = Write;
         sdf->Ioctl = Ioctl;
         return 0;
     }
References assert, Driver::SlaveDeviceFile::Close, ID, Driver::SlaveDeviceFile::Ioctl, Driver::SlaveDeviceFile::Open, Driver::SlaveDeviceFile::Read, slave, SysDbg::Write(), and Driver::SlaveDeviceFile::Write.
Referenced by Driver::RegisterBlockDevice().
NewNet()
int Driver::MasterDeviceFile::NewNet (maj_t ID, min_t MinorID, drvOpen_t Open, drvClose_t Close, drvRead_t Read, drvWrite_t Write, drvIoctl_t Ioctl)
Definition at line 224 of file master.cpp.
     {
         assert(this->SlavesMap.find(ID) != this->SlavesMap.end());
         Slaves slave = this->SlavesMap[ID];
         assert((*slave).find(MinorID) != (*slave).end());
         SlaveDeviceFile *sdf = (*slave)[MinorID];
         sdf->Open = Open;
         sdf->Close = Close;
         sdf->Read = Read;
         sdf->Write = Write;
         sdf->Ioctl = Ioctl;
         return 0;
     }
References assert, Driver::SlaveDeviceFile::Close, ID, Driver::SlaveDeviceFile::Ioctl, Driver::SlaveDeviceFile::Open, Driver::SlaveDeviceFile::Read, slave, SysDbg::Write(), and Driver::SlaveDeviceFile::Write.
Referenced by Driver::RegisterNetDevice().
open()
int Driver::MasterDeviceFile::open (int Flags, mode_t Mode) final virtual
Reimplemented from vfs::Node.
Definition at line 35 of file master.cpp.
     {
         switch (this->DeviceType)
         {
         default:
             if (this->SlavesMap.empty())
                 return -ENOSYS;
             Slaves slave = this->SlavesMap.begin()->second;
             return slave->begin()->second->open(Flags, Mode);
         }
     }
References ENOSYS, Flags, and slave.
read()
size_t Driver::MasterDeviceFile::read (uint8_t * Buffer, size_t Size, off_t Offset) final virtual
Reimplemented from vfs::Node.
Definition at line 59 of file master.cpp.
     {
         switch (this->DeviceType)
         {
         case ddt_Keyboard:
         {
             while (KeyQueue.empty())
                 TaskManager->Yield();
             /* Request scancode */
             if (Size == 2 && Buffer[1] == 0x00)
             {
                 if (RawKeyQueue.empty())
                     return 0;
                 Buffer[0] = RawKeyQueue.front();
                 RawKeyQueue.pop_front();
                 return 1;
             }
             Buffer[0] = KeyQueue.front();
             KeyQueue.pop_front();
             return 1;
         }
         default:
             if (this->SlavesMap.empty())
                 return 0;
             Slaves slave = this->SlavesMap.begin()->second;
             return slave->begin()->second->read(Buffer, Size, Offset);
         }
     }
References Buffer, ddt_Keyboard, Size, slave, TaskManager, and Tasking::Task::Yield().
Referenced by vfs::KConDevice::read().
Register()
dev_t Driver::MasterDeviceFile::Register (maj_t ID)
Definition at line 239 of file master.cpp.
     {
         debug("Registering slave device %d", ID);
         Slaves slave;
         if (this->SlavesMap.find(ID) != this->SlavesMap.end())
             slave = this->SlavesMap[ID];
         else
             slave = new std::unordered_map<min_t, SlaveDeviceFile *>();
         char name[24];
         sprintf(name, "%s%ld", this->SlaveName, this->SlaveIDCounter);
         SlaveDeviceFile *sdf = new SlaveDeviceFile(name,
                                                    this->SlaveParent,
                                                    this->DeviceType,
                                                    this->Type);
         sdf->DeviceMajor = ID;
         sdf->DeviceMinor = this->SlaveIDCounter;
         (*slave)[this->SlaveIDCounter] = sdf;
         this->SlavesMap[ID] = slave;
         return this->SlaveIDCounter++;
     }
References debug, vfs::Node::DeviceMajor, vfs::Node::DeviceMinor, ID, slave, and sprintf().
Referenced by Driver::RegisterAudioDevice(), Driver::RegisterBlockDevice(), Driver::RegisterInputDevice(), and Driver::RegisterNetDevice().
ReportKeyEvent()
int Driver::MasterDeviceFile::ReportKeyEvent (maj_t ID, min_t MinorID, uint8_t ScanCode)
Definition at line 134 of file master.cpp.
     {
         debug("New key event: %02x", ScanCode);
         if (this->SlavesMap.find(ID) == this->SlavesMap.end())
             return -EINVAL;
         std::unordered_map<min_t, SlaveDeviceFile *> *slave = this->SlavesMap[ID];
         if ((*slave).find(MinorID) == (*slave).end())
             return -EINVAL;
         /* We are master, keep a copy of the scancode and
             converted key */
         if (RawKeyQueue.size() > 16)
             RawKeyQueue.pop_front();
         RawKeyQueue.push_back(ScanCode);
         if (KeyQueue.size() > 16)
             KeyQueue.pop_front();
         switch (ScanCode & ~KEY_PRESSED)
         {
         case KEY_LEFT_SHIFT:
         case KEY_RIGHT_SHIFT:
         {
             if (ScanCode & KEY_PRESSED)
                 UpperCase = true;
             else
                 UpperCase = false;
             break;
         }
         case KEY_CAPS_LOCK:
         {
             if (ScanCode & KEY_PRESSED)
                 CapsLock = !CapsLock;
             break;
         }
         default:
             break;
         }
         KeyQueue.push_back(GetScanCode(ScanCode, UpperCase || CapsLock));
         SlaveDeviceFile *sdf = (*slave)[MinorID];
         return sdf->ReportKeyEvent(ScanCode);
     }
References debug, EINVAL, Driver::GetScanCode(), ID, KEY_CAPS_LOCK, KEY_LEFT_SHIFT, KEY_PRESSED, KEY_RIGHT_SHIFT, Driver::SlaveDeviceFile::ReportKeyEvent(), and slave.
Referenced by Driver::ReportKeyboardEvent().
ReportMouseEvent()
int Driver::MasterDeviceFile::ReportMouseEvent (maj_t ID, min_t MinorID, bool LeftButton, bool RightButton, bool MiddleButton, bool Button4, bool Button5, bool Button6, bool Button7, bool Button8, uintptr_t X, uintptr_t Y, int8_t Z, bool Relative)
Definition at line 180 of file master.cpp.
     {
         return -ENOSYS;
     }
References ENOSYS.
Referenced by Driver::ReportAbsoluteMouseEvent(), and Driver::ReportRelativeMouseEvent().
ReportNetworkPacket()
int Driver::MasterDeviceFile::ReportNetworkPacket (maj_t ID, min_t MinorID, void * Buffer, size_t Size)
Definition at line 188 of file master.cpp.
     {
         /* TODO: Buffer must be allocated by the kernel */
         return -ENOSYS;
     }
References ENOSYS.
Referenced by Driver::ReportNetworkPacket().
Unregister()
int Driver::MasterDeviceFile::Unregister (maj_t ID, min_t MinorID)
Definition at line 263 of file master.cpp.
     {
         debug("Unregistering slave device %d:%d", ID, MinorID);
         if (this->SlavesMap.find(ID) == this->SlavesMap.end())
             return -EINVAL;
         std::unordered_map<min_t, SlaveDeviceFile *> *slave = this->SlavesMap[ID];
         if ((*slave).find(MinorID) == (*slave).end())
             return -EINVAL;
         SlaveDeviceFile *sdf = (*slave)[MinorID];
         delete sdf;
         slave->erase(MinorID);
         if (slave->empty())
         {
             delete slave;
             this->SlavesMap.erase(ID);
         }
         return 0;
     }
References debug, EINVAL, ID, and slave.
Referenced by Driver::UnregisterAudioDevice(), Driver::UnregisterBlockDevice(), Driver::UnregisterInputDevice(), and Driver::UnregisterNetDevice().
write()
size_t Driver::MasterDeviceFile::write (uint8_t * Buffer, size_t Size, off_t Offset) final virtual
Reimplemented from vfs::Node.
Definition at line 93 of file master.cpp.
     {
         switch (this->DeviceType)
         {
         default:
             if (this->SlavesMap.empty())
                 return 0;
             Slaves slave = this->SlavesMap.begin()->second;
             return slave->begin()->second->write(Buffer, Size, Offset);
         }
     }
References Buffer, Size, and slave.
Field Documentation
CapsLock
bool Driver::MasterDeviceFile::CapsLock = false private
Definition at line 96 of file driver.hpp.
DeviceType
int Driver::MasterDeviceFile::DeviceType private
Definition at line 87 of file driver.hpp.
Referenced by MasterDeviceFile().
KeyQueue
std::list<uint8_t> Driver::MasterDeviceFile::KeyQueue private
Definition at line 94 of file driver.hpp.
RawKeyQueue
std::list<uint8_t> Driver::MasterDeviceFile::RawKeyQueue private
Definition at line 93 of file driver.hpp.
SlaveIDCounter
min_t Driver::MasterDeviceFile::SlaveIDCounter = 0 private
Definition at line 88 of file driver.hpp.
SlaveName
char Driver::MasterDeviceFile::SlaveName[16] private
Definition at line 85 of file driver.hpp.
Referenced by MasterDeviceFile().
SlaveParent
vfs::Node* Driver::MasterDeviceFile::SlaveParent private
Definition at line 86 of file driver.hpp.
Referenced by MasterDeviceFile().
SlavesMap
std::unordered_map<maj_t, Slaves> Driver::MasterDeviceFile::SlavesMap private
Definition at line 91 of file driver.hpp.
Referenced by ~MasterDeviceFile().
UpperCase
bool Driver::MasterDeviceFile::UpperCase = false private
Definition at line 95 of file driver.hpp.
The documentation for this class was generated from the following files:
Kernel/include/driver.hpp
Kernel/core/driver/devfile/master.cpp