Fennix: Userspace/apps/base/bash/trap.c File Reference
trap.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "bashansi.h"
#include <stdio.h>
#include <errno.h>
#include "bashintl.h"
#include <signal.h>
#include "trap.h"
#include "shell.h"
#include "execute_cmd.h"
#include "flags.h"
#include "parser.h"
#include "input.h"
#include "jobs.h"
#include "signames.h"
#include "builtins.h"
#include "builtins/common.h"
#include "builtins/builtext.h"
Macros
#define SIG_INHERITED 0x0 /* Value inherited from parent. */
#define SIG_TRAPPED 0x1 /* Currently trapped. */
#define SIG_HARD_IGNORE 0x2 /* Signal was ignored on shell entry. */
#define SIG_SPECIAL 0x4 /* Treat this signal specially. */
#define SIG_NO_TRAP 0x8 /* Signal cannot be trapped. */
#define SIG_INPROGRESS 0x10 /* Signal handler currently executing. */
#define SIG_CHANGED 0x20 /* Trap value changed in trap handler. */
#define SIG_IGNORED 0x40 /* The signal is currently being ignored. */
#define SPECIAL_TRAP(s) ((s) == EXIT_TRAP || (s) == DEBUG_TRAP || (s) == ERROR_TRAP || (s) == RETURN_TRAP)
#define GETORIGSIG(sig)
#define SETORIGSIG(sig, handler)
#define GET_ORIGINAL_SIGNAL(sig)
#define RECURSIVE_SIG(s) (SPECIAL_TRAP(s) == 0)
Functions
static void free_trap_command (int)
static void change_signal (int, char *)
static int _run_trap_internal (int, char *)
static void free_trap_string (int)
static void reset_signal (int)
static void restore_signal (int)
static void reset_or_restore_signal_handlers (sh_resetsig_func_t *)
static void reinit_trap (int)
static void trap_if_untrapped (int, char *)
void initialize_traps ()
char * signal_name (int sig)
int decode_signal (char *string, int flags)
void run_pending_traps ()
void set_trap_state (int sig)
sighandler trap_handler (int sig)
int next_pending_trap (int start)
int first_pending_trap ()
int any_signals_trapped ()
void clear_pending_traps ()
void check_signals ()
void check_signals_and_traps ()
void set_debug_trap (char *command)
void maybe_set_debug_trap (char *command)
void set_error_trap (char *command)
void maybe_set_error_trap (char *command)
void set_return_trap (char *command)
void maybe_set_return_trap (char *command)
SigHandler * set_sigint_handler ()
SigHandler * trap_to_sighandler (int sig)
void set_signal (int sig, char *string)
void get_original_signal (int sig)
void get_all_original_signals ()
void set_original_signal (int sig, SigHandler *handler)
void restore_default_signal (int sig)
void ignore_signal (int sig)
int run_exit_trap ()
void run_trap_cleanup (int sig)
int run_debug_trap ()
void run_error_trap ()
void run_return_trap ()
void run_interrupt_trap (int will_throw)
void free_trap_strings ()
void reset_signal_handlers ()
void restore_original_signals ()
void restore_traps ()
int maybe_call_trap_handler (int sig)
int signal_is_trapped (int sig)
int signal_is_pending (int sig)
int signal_is_special (int sig)
int signal_is_ignored (int sig)
int signal_is_hard_ignored (int sig)
void set_signal_hard_ignored (int sig)
void set_signal_ignored (int sig)
int signal_in_progress (int sig)
Variables
int errno
static int sigmodes [BASH_NSIG]
volatile int from_return_trap
int waiting_for_child
WORD_LIST * subst_assign_varlist
SigHandler * original_signals [NSIG]
char * trap_list [BASH_NSIG]
int pending_traps [NSIG]
int running_trap
int trap_saved_exit_value
int wait_signal_received
int trapped_signal_received
int suppress_debug_trap_verbose = 0
static int catch_flag
Macro Definition Documentation
GET_ORIGINAL_SIGNAL
#define GET_ORIGINAL_SIGNAL (sig)
Value:
  if (sig && sig < NSIG && original_signals[sig] == IMPOSSIBLE_TRAP_HANDLER) \
    GETORIGSIG(sig)
Definition at line 142 of file trap.c.
GETORIGSIG
#define GETORIGSIG (sig)
Value:
  do { \
    original_signals[sig] = (SigHandler *)set_signal_handler (sig, SIG_DFL); \
    set_signal_handler (sig, original_signals[sig]); \
    if (original_signals[sig] == SIG_IGN) \
      sigmodes[sig] |= SIG_HARD_IGNORE; \
  } while (0)
Definition at line 127 of file trap.c.
RECURSIVE_SIG
#define RECURSIVE_SIG (s) (SPECIAL_TRAP(s) == 0)
Definition at line 1043 of file trap.c.
SETORIGSIG
#define SETORIGSIG (sig, handler)
Value:
  do { \
    original_signals[sig] = handler; \
    if (original_signals[sig] == SIG_IGN) \
      sigmodes[sig] |= SIG_HARD_IGNORE; \
  } while (0)
Definition at line 135 of file trap.c.
SIG_CHANGED
#define SIG_CHANGED 0x20 /* Trap value changed in trap handler. */
Definition at line 67 of file trap.c.
SIG_HARD_IGNORE
#define SIG_HARD_IGNORE 0x2 /* Signal was ignored on shell entry. */
Definition at line 63 of file trap.c.
SIG_IGNORED
#define SIG_IGNORED 0x40 /* The signal is currently being ignored. */
Definition at line 68 of file trap.c.
SIG_INHERITED
#define SIG_INHERITED 0x0 /* Value inherited from parent. */
Definition at line 61 of file trap.c.
SIG_INPROGRESS
#define SIG_INPROGRESS 0x10 /* Signal handler currently executing. */
Definition at line 66 of file trap.c.
SIG_NO_TRAP
#define SIG_NO_TRAP 0x8 /* Signal cannot be trapped. */
Definition at line 65 of file trap.c.
SIG_SPECIAL
#define SIG_SPECIAL 0x4 /* Treat this signal specially. */
Definition at line 64 of file trap.c.
SIG_TRAPPED
#define SIG_TRAPPED 0x1 /* Currently trapped. */
Definition at line 62 of file trap.c.
SPECIAL_TRAP
#define SPECIAL_TRAP (s) ((s) == EXIT_TRAP || (s) == DEBUG_TRAP || (s) == ERROR_TRAP || (s) == RETURN_TRAP)
Definition at line 70 of file trap.c.
Function Documentation
_run_trap_internal()
static int _run_trap_internal (int sig, char * tag) static
Definition at line 1048 of file trap.c.
 {
   char *trap_command, *old_trap;
   int trap_exit_value;
   volatile int save_return_catch_flag, function_code;
   int old_modes, old_running, old_int;
   int flags;
   procenv_t save_return_catch;
   WORD_LIST *save_subst_varlist;
   HASH_TABLE *save_tempenv;
   sh_parser_state_t pstate;
 #if defined (ARRAY_VARS)
   ARRAY *ps;
 #endif
   old_modes = old_running = -1;
   trap_exit_value = function_code = 0;
   trap_saved_exit_value = last_command_exit_value;
   /* Run the trap only if SIG is trapped and not ignored, and we are not
      currently executing in the trap handler. */
   if ((sigmodes[sig] & SIG_TRAPPED) && ((sigmodes[sig] & SIG_IGNORED) == 0) &&
       (trap_list[sig] != (char *)IMPOSSIBLE_TRAP_HANDLER) &&
 #if 1
       /* Uncomment this to allow some special signals to recursively execute
      trap handlers. */
       (RECURSIVE_SIG (sig) || (sigmodes[sig] & SIG_INPROGRESS) == 0))
 #else
       ((sigmodes[sig] & SIG_INPROGRESS) == 0))
 #endif
     {
       old_trap = trap_list[sig];
       old_modes = sigmodes[sig];
       old_running = running_trap;
       sigmodes[sig] |= SIG_INPROGRESS;
       sigmodes[sig] &= ~SIG_CHANGED;        /* just to be sure */
       trap_command =  savestring (old_trap);
       running_trap = sig + 1;
       old_int = interrupt_state;    /* temporarily suppress pending interrupts */
       CLRINTERRUPT;
 #if defined (ARRAY_VARS)
       ps = save_pipestatus_array ();
 #endif
       save_parser_state (&pstate);
       save_subst_varlist = subst_assign_varlist;
       subst_assign_varlist = 0;
       save_tempenv = temporary_env;
       temporary_env = 0;    /* traps should not run with temporary env */
 #if defined (JOB_CONTROL)
       if (sig != DEBUG_TRAP)    /* run_debug_trap does this */
     save_pipeline (1);  /* XXX only provides one save level */
 #endif
       /* If we're in a function, make sure return longjmps come here, too. */
       save_return_catch_flag = return_catch_flag;
       if (return_catch_flag)
     {
       COPY_PROCENV (return_catch, save_return_catch);
       function_code = setjmp_nosigs (return_catch);
     }
       flags = SEVAL_NONINT|SEVAL_NOHIST|SEVAL_NOOPTIMIZE;
       if (sig != DEBUG_TRAP && sig != RETURN_TRAP && sig != ERROR_TRAP)
     flags |= SEVAL_RESETLINE;
       evalnest++;
       if (function_code == 0)
         {
       parse_and_execute (trap_command, tag, flags);
       trap_exit_value = last_command_exit_value;
         }
       else
         trap_exit_value = return_catch_value;
       evalnest--;
 #if defined (JOB_CONTROL)
       if (sig != DEBUG_TRAP)    /* run_debug_trap does this */
     restore_pipeline (1);
 #endif
       subst_assign_varlist = save_subst_varlist;
       restore_parser_state (&pstate);
 #if defined (ARRAY_VARS)
       restore_pipestatus_array (ps);
 #endif
       temporary_env = save_tempenv;
       if ((old_modes & SIG_INPROGRESS) == 0)
     sigmodes[sig] &= ~SIG_INPROGRESS;
       running_trap = old_running;
       interrupt_state = old_int;
       if (sigmodes[sig] & SIG_CHANGED)
     {
 #if 0
       /* Special traps like EXIT, DEBUG, RETURN are handled explicitly in
          the places where they can be changed using unwind-protects.  For
          example, look at execute_cmd.c:execute_function(). */
       if (SPECIAL_TRAP (sig) == 0)
 #endif
         free (old_trap);
       sigmodes[sig] &= ~SIG_CHANGED;
       CHECK_TERMSIG;    /* some pathological conditions lead here */
     }
       if (save_return_catch_flag)
     {
       return_catch_flag = save_return_catch_flag;
       return_catch_value = trap_exit_value;
       COPY_PROCENV (save_return_catch, return_catch);
       if (function_code)
         {
 #if 0
           from_return_trap = sig == RETURN_TRAP;
 #endif
           sh_longjmp (return_catch, 1);
         }
     }
     }
   return trap_exit_value;
 }
References CHECK_TERMSIG, CLRINTERRUPT, COPY_PROCENV, DEBUG_TRAP, ERROR_TRAP, evalnest, flags, free, from_return_trap, IMPOSSIBLE_TRAP_HANDLER, interrupt_state, last_command_exit_value, old_int, parse_and_execute(), procenv_t, RECURSIVE_SIG, restore_parser_state(), restore_pipeline(), return_catch, return_catch_flag, return_catch_value, RETURN_TRAP, running_trap, save_parser_state(), save_pipeline(), savestring(), setjmp_nosigs, SEVAL_NOHIST, SEVAL_NONINT, SEVAL_NOOPTIMIZE, SEVAL_RESETLINE, sh_longjmp, SIG_CHANGED, SIG_IGNORED, SIG_INPROGRESS, SIG_TRAPPED, sigmodes, SPECIAL_TRAP, subst_assign_varlist, temporary_env, trap_list, and trap_saved_exit_value.
Referenced by run_debug_trap(), run_error_trap(), run_interrupt_trap(), and run_return_trap().
any_signals_trapped()
int any_signals_trapped ()
Definition at line 597 of file trap.c.
 {
   register int i;
   for (i = 1; i < NSIG; i++)
     if ((sigmodes[i] & SIG_TRAPPED) && (sigmodes[i] & SIG_IGNORED) == 0)
       return i;
   return -1;
 }
References i, NSIG, SIG_IGNORED, SIG_TRAPPED, and sigmodes.
Referenced by should_optimize_fork().
change_signal()
static void change_signal (int sig, char * value) static
Definition at line 850 of file trap.c.
 {
   if ((sigmodes[sig] & SIG_INPROGRESS) == 0)
     free_trap_command (sig);
   trap_list[sig] = value;
   sigmodes[sig] |= SIG_TRAPPED;
   if (value == (char *)IGNORE_SIG)
     sigmodes[sig] |= SIG_IGNORED;
   else
     sigmodes[sig] &= ~SIG_IGNORED;
   if (sigmodes[sig] & SIG_INPROGRESS)
     sigmodes[sig] |= SIG_CHANGED;
 }
References free_trap_command(), IGNORE_SIG, SIG_CHANGED, SIG_IGNORED, SIG_INPROGRESS, SIG_TRAPPED, sigmodes, trap_list, and value.
Referenced by free_trap_string(), ignore_signal(), restore_default_signal(), restore_signal(), and set_signal().
check_signals()
void check_signals (void)
Definition at line 617 of file trap.c.
 {
   /* Add any other shell timeouts here */
   check_read_timeout ();    /* set by the read builtin */
   QUIT;
 }
References QUIT.
Referenced by check_signals_and_traps(), zread(), and zreadintr().
check_signals_and_traps()
void check_signals_and_traps (void)
Definition at line 626 of file trap.c.
 {
   check_signals ();
   run_pending_traps ();
 }
References check_signals(), and run_pending_traps().
Referenced by zread().
clear_pending_traps()
void clear_pending_traps ()
Definition at line 608 of file trap.c.
 {
   register int i;
   for (i = 1; i < NSIG; i++)
     pending_traps[i] = 0;
 }
References i, NSIG, and pending_traps.
Referenced by execute_in_subshell().
decode_signal()
int decode_signal (char * string, int flags)
Definition at line 231 of file trap.c.
 {
   intmax_t sig;
   char *name;
   if (legal_number (string, &sig))
     return ((sig >= 0 && sig < NSIG) ? (int)sig : NO_SIG);
 #if defined (SIGRTMIN) && defined (SIGRTMAX)
   if (STREQN (string, "SIGRTMIN+", 9) || ((flags & DSIG_NOCASE) && strncasecmp (string, "SIGRTMIN+", 9) == 0))
     {
       if (legal_number (string+9, &sig) && sig >= 0 && sig <= SIGRTMAX - SIGRTMIN)
     return (SIGRTMIN + sig);
       else
     return NO_SIG;
     }
   else if (STREQN (string, "RTMIN+", 6) || ((flags & DSIG_NOCASE) && strncasecmp (string, "RTMIN+", 6) == 0))
     {
       if (legal_number (string+6, &sig) && sig >= 0 && sig <= SIGRTMAX - SIGRTMIN)
     return (SIGRTMIN + sig);
       else
     return NO_SIG;
     }
 #endif /* SIGRTMIN && SIGRTMAX */
   /* A leading `SIG' may be omitted. */
   for (sig = 0; sig < BASH_NSIG; sig++)
     {
       name = signal_names[sig];
       if (name == 0 || name[0] == '\0')
     continue;
       /* Check name without the SIG prefix first case sensitively or
      insensitively depending on whether flags includes DSIG_NOCASE */
       if (STREQN (name, "SIG", 3))
     {
       name += 3;
       if ((flags & DSIG_NOCASE) && strcasecmp (string, name) == 0)
         return ((int)sig);
       else if ((flags & DSIG_NOCASE) == 0 && strcmp (string, name) == 0)
         return ((int)sig);
       /* If we can't use the `SIG' prefix to match, punt on this
          name now. */
       else if ((flags & DSIG_SIGPREFIX) == 0)
         continue;
     }
       /* Check name with SIG prefix case sensitively or insensitively
      depending on whether flags includes DSIG_NOCASE */
       name = signal_names[sig];
       if ((flags & DSIG_NOCASE) && strcasecmp (string, name) == 0)
     return ((int)sig);
       else if ((flags & DSIG_NOCASE) == 0 && strcmp (string, name) == 0)
     return ((int)sig);
     }
   return (NO_SIG);
 }
References BASH_NSIG, DSIG_NOCASE, DSIG_SIGPREFIX, flags, legal_number(), NO_SIG, NSIG, signal_names, strcasecmp, strcmp, STREQN, and strncasecmp.
Referenced by display_signal_list().
first_pending_trap()
int first_pending_trap ()
Definition at line 589 of file trap.c.
 {
   return (next_pending_trap (1));
 }
References next_pending_trap().
free_trap_command()
static void free_trap_command (int sig) static
Definition at line 837 of file trap.c.
 {
   if ((sigmodes[sig] & SIG_TRAPPED) && trap_list[sig] &&
       (trap_list[sig] != (char *)IGNORE_SIG) &&
       (trap_list[sig] != (char *)DEFAULT_SIG) &&
       (trap_list[sig] != (char *)IMPOSSIBLE_TRAP_HANDLER))
     free (trap_list[sig]);
 }
References DEFAULT_SIG, free, IGNORE_SIG, IMPOSSIBLE_TRAP_HANDLER, SIG_TRAPPED, sigmodes, and trap_list.
Referenced by change_signal(), reset_or_restore_signal_handlers(), and restore_default_signal().
free_trap_string()
static void free_trap_string (int sig) static
Definition at line 1307 of file trap.c.
 {
   change_signal (sig, (char *)DEFAULT_SIG);
   sigmodes[sig] &= ~SIG_TRAPPED;        /* XXX - SIG_INPROGRESS? */
 }
References change_signal(), DEFAULT_SIG, SIG_TRAPPED, and sigmodes.
Referenced by free_trap_strings().
free_trap_strings()
void free_trap_strings ()
Definition at line 1284 of file trap.c.
 {
   register int i;
   for (i = 0; i < NSIG; i++)
     {
       if (trap_list[i] != (char *)IGNORE_SIG)
     free_trap_string (i);
     }
   for (i = NSIG; i < BASH_NSIG; i++)
     {
       /* Don't free the trap string if the subshell inherited the trap */
       if ((sigmodes[i] & SIG_TRAPPED) == 0)
     {
       free_trap_string (i);
       trap_list[i] = (char *)NULL;
     }
     }
 }
References BASH_NSIG, free_trap_string(), i, IGNORE_SIG, NSIG, NULL, SIG_TRAPPED, sigmodes, and trap_list.
get_all_original_signals()
void get_all_original_signals ()
Definition at line 877 of file trap.c.
 {
   register int i;
   for (i = 1; i < NSIG; i++)
     GET_ORIGINAL_SIGNAL (i);
 }
References GET_ORIGINAL_SIGNAL, i, and NSIG.
get_original_signal()
void get_original_signal (int sig)
Definition at line 868 of file trap.c.
 {
   /* If we aren't sure the of the original value, then get it. */
   if (sig > 0 && sig < NSIG && original_signals[sig] == (SigHandler *)IMPOSSIBLE_TRAP_HANDLER)
     GETORIGSIG (sig);
 }
References GETORIGSIG, IMPOSSIBLE_TRAP_HANDLER, NSIG, and original_signals.
Referenced by get_original_tty_job_signals(), initialize_shell_signals(), and setup_async_signals().
ignore_signal()
void ignore_signal (int sig)
Definition at line 942 of file trap.c.
 {
   if (SPECIAL_TRAP (sig) && ((sigmodes[sig] & SIG_IGNORED) == 0))
     {
       change_signal (sig, (char *)IGNORE_SIG);
       return;
     }
   GET_ORIGINAL_SIGNAL (sig);
   /* A signal ignored on entry to the shell cannot be trapped or reset.
      No error is reported when the user attempts to do so. */
   if (sigmodes[sig] & SIG_HARD_IGNORE)
     return;
   /* If already trapped and ignored, no change necessary. */
   if (sigmodes[sig] & SIG_IGNORED)
     return;
   /* Only change the signal handler for SIG if it allows it. */
   if ((sigmodes[sig] & SIG_NO_TRAP) == 0)
     set_signal_handler (sig, SIG_IGN);
   /* Change the trap command in either case. */
   change_signal (sig, (char *)IGNORE_SIG);
 }
References change_signal(), GET_ORIGINAL_SIGNAL, IGNORE_SIG, set_signal_handler, SIG_HARD_IGNORE, SIG_IGN, SIG_IGNORED, SIG_NO_TRAP, sigmodes, and SPECIAL_TRAP.
initialize_traps()
void initialize_traps ()
Definition at line 147 of file trap.c.
 {
   register int i;
   initialize_signames();
   trap_list[EXIT_TRAP] = trap_list[DEBUG_TRAP] = trap_list[ERROR_TRAP] = trap_list[RETURN_TRAP] = (char *)NULL;
   sigmodes[EXIT_TRAP] = sigmodes[DEBUG_TRAP] = sigmodes[ERROR_TRAP] = sigmodes[RETURN_TRAP] = SIG_INHERITED;
   original_signals[EXIT_TRAP] = IMPOSSIBLE_TRAP_HANDLER;
   for (i = 1; i < NSIG; i++)
     {
       pending_traps[i] = 0;
       trap_list[i] = (char *)DEFAULT_SIG;
       sigmodes[i] = SIG_INHERITED;  /* XXX - only set, not used */
       original_signals[i] = IMPOSSIBLE_TRAP_HANDLER;
     }
   /* Show which signals are treated specially by the shell. */
 #if defined (SIGCHLD)
   GETORIGSIG (SIGCHLD);
   sigmodes[SIGCHLD] |= (SIG_SPECIAL | SIG_NO_TRAP);
 #endif /* SIGCHLD */
   GETORIGSIG (SIGINT);
   sigmodes[SIGINT] |= SIG_SPECIAL;
 #if defined (__BEOS__)
   /* BeOS sets SIGINT to SIG_IGN! */
   original_signals[SIGINT] = SIG_DFL;
   sigmodes[SIGINT] &= ~SIG_HARD_IGNORE;
 #endif
   GETORIGSIG (SIGQUIT);
   sigmodes[SIGQUIT] |= SIG_SPECIAL;
   if (interactive)
     {
       GETORIGSIG (SIGTERM);
       sigmodes[SIGTERM] |= SIG_SPECIAL;
     }
   get_original_tty_job_signals ();
 }
References DEBUG_TRAP, DEFAULT_SIG, ERROR_TRAP, EXIT_TRAP, get_original_tty_job_signals(), GETORIGSIG, i, IMPOSSIBLE_TRAP_HANDLER, initialize_signames(), interactive, NSIG, NULL, original_signals, pending_traps, RETURN_TRAP, SIG_DFL, SIG_HARD_IGNORE, SIG_INHERITED, SIG_NO_TRAP, SIG_SPECIAL, SIGCHLD, SIGINT, sigmodes, SIGQUIT, SIGTERM, and trap_list.
Referenced by shell_initialize().
maybe_call_trap_handler()
int maybe_call_trap_handler (int sig)
Definition at line 1472 of file trap.c.
 {
   /* Call the trap handler for SIG if the signal is trapped and not ignored. */
   if ((sigmodes[sig] & SIG_TRAPPED) && ((sigmodes[sig] & SIG_IGNORED) == 0))
     {
       switch (sig)
     {
     case SIGINT:
       run_interrupt_trap (0);
       break;
     case EXIT_TRAP:
       run_exit_trap ();
       break;
     case DEBUG_TRAP:
       run_debug_trap ();
       break;
     case ERROR_TRAP:
       run_error_trap ();
       break;
     default:
       trap_handler (sig);
       break;
     }
       return (1);
     }
   else
     return (0);
 }
References DEBUG_TRAP, ERROR_TRAP, EXIT_TRAP, run_debug_trap(), run_error_trap(), run_exit_trap(), run_interrupt_trap(), SIG_IGNORED, SIG_TRAPPED, SIGINT, sigmodes, and trap_handler().
Referenced by set_job_status_and_cleanup(), and wait_for().
maybe_set_debug_trap()
void maybe_set_debug_trap (char * command)
Definition at line 709 of file trap.c.
 {
   trap_if_untrapped (DEBUG_TRAP, command);
 }
References DEBUG_TRAP, and trap_if_untrapped().
Referenced by execute_function().
maybe_set_error_trap()
void maybe_set_error_trap (char * command)
Definition at line 723 of file trap.c.
 {
   trap_if_untrapped (ERROR_TRAP, command);
 }
References ERROR_TRAP, and trap_if_untrapped().
Referenced by execute_function().
maybe_set_return_trap()
void maybe_set_return_trap (char * command)
Definition at line 737 of file trap.c.
 {
   trap_if_untrapped (RETURN_TRAP, command);
 }
References RETURN_TRAP, and trap_if_untrapped().
Referenced by execute_function().
next_pending_trap()
int next_pending_trap (int start)
Definition at line 577 of file trap.c.
 {
   register int i;
   for (i = start; i < NSIG; i++)
     if (pending_traps[i])
       return i;
   return -1;
 }
References i, NSIG, pending_traps, and start.
Referenced by first_pending_trap().
reinit_trap()
static void reinit_trap (int sig) static
Definition at line 1401 of file trap.c.
 {
   sigmodes[sig] |= SIG_TRAPPED;
   if (trap_list[sig] == (char *)IGNORE_SIG)
     sigmodes[sig] |= SIG_IGNORED;
   else
     sigmodes[sig] &= ~SIG_IGNORED;
   if (sigmodes[sig] & SIG_INPROGRESS)
     sigmodes[sig] |= SIG_CHANGED;
 }
References IGNORE_SIG, SIG_CHANGED, SIG_IGNORED, SIG_INPROGRESS, SIG_TRAPPED, sigmodes, and trap_list.
Referenced by restore_traps().
reset_or_restore_signal_handlers()
static void reset_or_restore_signal_handlers (sh_resetsig_func_t * reset) static
Definition at line 1336 of file trap.c.
 {
   register int i;
   /* Take care of the exit trap first */
   if (sigmodes[EXIT_TRAP] & SIG_TRAPPED)
     {
       sigmodes[EXIT_TRAP] &= ~SIG_TRAPPED;  /* XXX - SIG_INPROGRESS? */
       if (reset != reset_signal)
     {
       free_trap_command (EXIT_TRAP);
       trap_list[EXIT_TRAP] = (char *)NULL;
     }
     }
   for (i = 1; i < NSIG; i++)
     {
       if (sigmodes[i] & SIG_TRAPPED)
     {
       if (trap_list[i] == (char *)IGNORE_SIG)
         set_signal_handler (i, SIG_IGN);
       else
         (*reset) (i);
     }
       else if (sigmodes[i] & SIG_SPECIAL)
     (*reset) (i);
       pending_traps[i] = 0; /* XXX */
     }
   /* Command substitution and other child processes don't inherit the
      debug, error, or return traps.  If we're in the debugger, and the
      `functrace' or `errtrace' options have been set, then let command
      substitutions inherit them.  Let command substitution inherit the
      RETURN trap if we're in the debugger and tracing functions. */
   if (function_trace_mode == 0)
     {
       sigmodes[DEBUG_TRAP] &= ~SIG_TRAPPED;
       sigmodes[RETURN_TRAP] &= ~SIG_TRAPPED;
     }
   if (error_trace_mode == 0)
     sigmodes[ERROR_TRAP] &= ~SIG_TRAPPED;
 }
References DEBUG_TRAP, error_trace_mode, ERROR_TRAP, EXIT_TRAP, free_trap_command(), function_trace_mode, i, IGNORE_SIG, NSIG, NULL, pending_traps, reset(), reset_signal(), RETURN_TRAP, set_signal_handler, SIG_IGN, SIG_SPECIAL, SIG_TRAPPED, sigmodes, and trap_list.
Referenced by reset_signal_handlers(), and restore_original_signals().
reset_signal()
static void reset_signal (int sig) static
Definition at line 1317 of file trap.c.
 {
   set_signal_handler (sig, original_signals[sig]);
   sigmodes[sig] &= ~SIG_TRAPPED;        /* XXX - SIG_INPROGRESS? */
 }
References original_signals, set_signal_handler, SIG_TRAPPED, and sigmodes.
Referenced by reset_or_restore_signal_handlers(), and reset_signal_handlers().
reset_signal_handlers()
void reset_signal_handlers ()
Definition at line 1384 of file trap.c.
 {
   reset_or_restore_signal_handlers (reset_signal);
 }
References reset_or_restore_signal_handlers(), and reset_signal().
Referenced by command_substitute(), execute_in_subshell(), and execute_simple_command().
restore_default_signal()
void restore_default_signal (int sig)
Definition at line 899 of file trap.c.
 {
   if (SPECIAL_TRAP (sig))
     {
       if ((sig != DEBUG_TRAP && sig != ERROR_TRAP && sig != RETURN_TRAP) ||
       (sigmodes[sig] & SIG_INPROGRESS) == 0)
     free_trap_command (sig);
       trap_list[sig] = (char *)NULL;
       sigmodes[sig] &= ~SIG_TRAPPED;
       if (sigmodes[sig] & SIG_INPROGRESS)
     sigmodes[sig] |= SIG_CHANGED;
       return;
     }
   GET_ORIGINAL_SIGNAL (sig);
   /* A signal ignored on entry to the shell cannot be trapped or reset, but
      no error is reported when attempting to do so.  Thanks Posix.2. */
   if (sigmodes[sig] & SIG_HARD_IGNORE)
     return;
   /* If we aren't trapping this signal, don't bother doing anything else. */
   /* We special-case SIGCHLD and IMPOSSIBLE_TRAP_HANDLER (see above) as a
      sentinel to determine whether or not disposition is reset to the default
      while the trap handler is executing. */
   if (((sigmodes[sig] & SIG_TRAPPED) == 0) &&
       (sig != SIGCHLD || (sigmodes[sig] & SIG_INPROGRESS) == 0 || trap_list[sig] != (char *)IMPOSSIBLE_TRAP_HANDLER))
     return;
   /* Only change the signal handler for SIG if it allows it. */
   if ((sigmodes[sig] & SIG_NO_TRAP) == 0)
     set_signal_handler (sig, original_signals[sig]);
   /* Change the trap command in either case. */
   change_signal (sig, (char *)DEFAULT_SIG);
   /* Mark the signal as no longer trapped. */
   sigmodes[sig] &= ~SIG_TRAPPED;
 }
References change_signal(), DEBUG_TRAP, DEFAULT_SIG, ERROR_TRAP, free_trap_command(), GET_ORIGINAL_SIGNAL, IMPOSSIBLE_TRAP_HANDLER, NULL, original_signals, RETURN_TRAP, set_signal_handler, SIG_CHANGED, SIG_HARD_IGNORE, SIG_INPROGRESS, SIG_NO_TRAP, SIG_TRAPPED, SIGCHLD, sigmodes, SPECIAL_TRAP, and trap_list.
Referenced by execute_builtin(), execute_function(), and execute_in_subshell().
restore_original_signals()
void restore_original_signals ()
Definition at line 1393 of file trap.c.
 {
   reset_or_restore_signal_handlers (restore_signal);
 }
References reset_or_restore_signal_handlers(), and restore_signal().
Referenced by execute_disk_command(), and execute_null_command().
restore_signal()
static void restore_signal (int sig) static
Definition at line 1327 of file trap.c.
 {
   set_signal_handler (sig, original_signals[sig]);
   change_signal (sig, (char *)DEFAULT_SIG);
   sigmodes[sig] &= ~SIG_TRAPPED;
 }
References change_signal(), DEFAULT_SIG, original_signals, set_signal_handler, SIG_TRAPPED, and sigmodes.
Referenced by restore_original_signals(), and trap_handler().
restore_traps()
void restore_traps ()
Definition at line 1417 of file trap.c.
 {
   char *trapstr;
   int i;
   /* Take care of the exit trap first. If TRAP_LIST[0] is non-null, the trap
      has been set. */
   trapstr = trap_list[EXIT_TRAP];
   if (trapstr)
     reinit_trap (EXIT_TRAP);
   /* Then DEBUG, RETURN, and ERROR. TRAP_LIST[N] == 0 if these signals are
      not trapped. This knows what reset_signal_handlers does for these traps */
   trapstr = trap_list[DEBUG_TRAP];
   if (trapstr && function_trace_mode == 0)
     reinit_trap (DEBUG_TRAP);
   trapstr = trap_list[RETURN_TRAP];
   if (trapstr && function_trace_mode == 0)
     reinit_trap (RETURN_TRAP);
   trapstr = trap_list[ERROR_TRAP];
   if (trapstr && error_trace_mode == 0)
     reinit_trap (ERROR_TRAP);
   /* And finally all the `real' signals. reset_signal_handlers just changes the
      signal handler for these signals, leaving the trap value in place. We
      intuit what to do based on that value. We assume that signals marked as
      SIG_SPECIAL are reinitialized by initialize_signals (), so we don't
      change the signal handler unless the signal is supposed to be ignored. */
   for (i = 1; i < NSIG; i++)
     {
       trapstr = trap_list[i];
       if (sigmodes[i] & SIG_SPECIAL)
     {
       if (trapstr && trapstr != (char *)DEFAULT_SIG)
         reinit_trap (i);
       if (trapstr == (char *)IGNORE_SIG && (sigmodes[i] & SIG_NO_TRAP) == 0)
         set_signal_handler (i, SIG_IGN);
     }
       else if (trapstr == (char *)IGNORE_SIG)
     {
       reinit_trap (i);
       if ((sigmodes[i] & SIG_NO_TRAP) == 0)
         set_signal_handler (i, SIG_IGN);
     }
       else if (trapstr != (char *)DEFAULT_SIG)
         /* set_signal duplicates the string argument before freeing it. */
     set_signal (i, trapstr);
       pending_traps[i] = 0; /* XXX */
     }
 }
References DEBUG_TRAP, DEFAULT_SIG, error_trace_mode, ERROR_TRAP, EXIT_TRAP, function_trace_mode, i, IGNORE_SIG, NSIG, pending_traps, reinit_trap(), RETURN_TRAP, set_signal(), set_signal_handler, SIG_IGN, SIG_NO_TRAP, SIG_SPECIAL, sigmodes, and trap_list.
run_debug_trap()
int run_debug_trap ()
Definition at line 1183 of file trap.c.
 {
   int trap_exit_value, old_verbose;
   pid_t save_pgrp;
 #if defined (PGRP_PIPE)
   int save_pipe[2];
 #endif
   /* XXX - question:  should the DEBUG trap inherit the RETURN trap? */
   trap_exit_value = 0;
   if ((sigmodes[DEBUG_TRAP] & SIG_TRAPPED) && ((sigmodes[DEBUG_TRAP] & SIG_IGNORED) == 0) && ((sigmodes[DEBUG_TRAP] & SIG_INPROGRESS) == 0))
     {
 #if defined (JOB_CONTROL)
       save_pgrp = pipeline_pgrp;
       pipeline_pgrp = 0;
       save_pipeline (1);
 #  if defined (PGRP_PIPE)
       save_pgrp_pipe (save_pipe, 1);
 #  endif
       stop_making_children ();
 #endif
       old_verbose = echo_input_at_read;
       echo_input_at_read = suppress_debug_trap_verbose ? 0 : echo_input_at_read;
       trap_exit_value = _run_trap_internal (DEBUG_TRAP, "debug trap");
       echo_input_at_read = old_verbose;
 #if defined (JOB_CONTROL)
       pipeline_pgrp = save_pgrp;
       restore_pipeline (1);
 #  if defined (PGRP_PIPE)
       close_pgrp_pipe ();
       restore_pgrp_pipe (save_pipe);
 #  endif
       if (pipeline_pgrp > 0 && ((subshell_environment & (SUBSHELL_ASYNC|SUBSHELL_PIPE)) == 0))
     give_terminal_to (pipeline_pgrp, 1);
       notify_and_cleanup ();
 #endif
 #if defined (DEBUGGER)
       /* If we're in the debugger and the DEBUG trap returns 2 while we're in
      a function or sourced script, we force a `return'. */
       if (debugging_mode && trap_exit_value == 2 && return_catch_flag)
     {
       return_catch_value = trap_exit_value;
       sh_longjmp (return_catch, 1);
     }
 #endif
     }
   return trap_exit_value;
 }
References _run_trap_internal(), DEBUG_TRAP, debugging_mode, echo_input_at_read, give_terminal_to(), notify_and_cleanup(), pipeline_pgrp, restore_pipeline(), return_catch, return_catch_flag, return_catch_value, save_pipeline(), sh_longjmp, SIG_IGNORED, SIG_INPROGRESS, SIG_TRAPPED, sigmodes, stop_making_children(), SUBSHELL_ASYNC, subshell_environment, SUBSHELL_PIPE, and suppress_debug_trap_verbose.
Referenced by execute_case_command(), execute_for_command(), execute_function(), execute_simple_command(), and maybe_call_trap_handler().
run_error_trap()
void run_error_trap ()
Definition at line 1239 of file trap.c.
 {
   if ((sigmodes[ERROR_TRAP] & SIG_TRAPPED) && ((sigmodes[ERROR_TRAP] & SIG_IGNORED) == 0) && (sigmodes[ERROR_TRAP] & SIG_INPROGRESS) == 0)
     _run_trap_internal (ERROR_TRAP, "error trap");
 }
References _run_trap_internal(), ERROR_TRAP, SIG_IGNORED, SIG_INPROGRESS, SIG_TRAPPED, and sigmodes.
Referenced by execute_command_internal(), execute_connection(), and maybe_call_trap_handler().
run_exit_trap()
int run_exit_trap ()
Definition at line 974 of file trap.c.
 {
   char *trap_command;
   int code, function_code, retval;
 #if defined (ARRAY_VARS)
   ARRAY *ps;
 #endif
   trap_saved_exit_value = last_command_exit_value;
 #if defined (ARRAY_VARS)
   ps = save_pipestatus_array ();
 #endif
   function_code = 0;
   /* Run the trap only if signal 0 is trapped and not ignored, and we are not
      currently running in the trap handler (call to exit in the list of
      commands given to trap 0). */
   if ((sigmodes[EXIT_TRAP] & SIG_TRAPPED) &&
       (sigmodes[EXIT_TRAP] & (SIG_IGNORED|SIG_INPROGRESS)) == 0)
     {
       trap_command = savestring (trap_list[EXIT_TRAP]);
       sigmodes[EXIT_TRAP] &= ~SIG_TRAPPED;
       sigmodes[EXIT_TRAP] |= SIG_INPROGRESS;
       retval = trap_saved_exit_value;
       running_trap = 1;
       code = setjmp_nosigs (top_level);
       /* If we're in a function, make sure return longjmps come here, too. */
       if (return_catch_flag)
     function_code = setjmp_nosigs (return_catch);
       if (code == 0 && function_code == 0)
     {
       reset_parser ();
       parse_and_execute (trap_command, "exit trap", SEVAL_NONINT|SEVAL_NOHIST|SEVAL_RESETLINE|SEVAL_NOOPTIMIZE);
     }
       else if (code == ERREXIT)
     retval = last_command_exit_value;
       else if (code == EXITPROG || code == EXITBLTIN)
     retval = last_command_exit_value;
       else if (function_code != 0)
         retval = return_catch_value;
       else
     retval = trap_saved_exit_value;
       running_trap = 0;
 #if defined (ARRAY_VARS)
       array_dispose (ps);
 #endif
       return retval;
     }
 #if defined (ARRAY_VARS)
   restore_pipestatus_array (ps);
 #endif
   return (trap_saved_exit_value);
 }
References code, ERREXIT, EXIT_TRAP, EXITBLTIN, EXITPROG, last_command_exit_value, parse_and_execute(), reset_parser(), return_catch, return_catch_flag, return_catch_value, retval, running_trap, savestring(), setjmp_nosigs, SEVAL_NOHIST, SEVAL_NONINT, SEVAL_NOOPTIMIZE, SEVAL_RESETLINE, SIG_IGNORED, SIG_INPROGRESS, SIG_TRAPPED, sigmodes, top_level, trap_list, and trap_saved_exit_value.
Referenced by command_substitute(), execute_in_subshell(), exit_shell(), maybe_call_trap_handler(), subshell_exit(), and termsig_handler().
run_interrupt_trap()
void run_interrupt_trap (int will_throw)
Definition at line 1266 of file trap.c.
 {
   if (will_throw && running_trap > 0)
     run_trap_cleanup (running_trap - 1);
   pending_traps[SIGINT] = 0;    /* run_pending_traps does this */
   catch_flag = 0;
   _run_trap_internal (SIGINT, "interrupt trap");
 }
References _run_trap_internal(), catch_flag, pending_traps, run_trap_cleanup(), running_trap, and SIGINT.
Referenced by maybe_call_trap_handler(), run_pending_traps(), termsig_handler(), and throw_to_top_level().
run_pending_traps()
void run_pending_traps ()
Definition at line 297 of file trap.c.
 {
   register int sig;
   int x;
   volatile int old_exit_value, old_running;
   WORD_LIST *save_subst_varlist;
   HASH_TABLE *save_tempenv;
   sh_parser_state_t pstate;
   volatile int save_return_catch_flag, function_code;
   procenv_t save_return_catch;
   char *trap_command, *old_trap;
 #if defined (ARRAY_VARS)
   ARRAY *ps;
 #endif
   if (catch_flag == 0)      /* simple optimization */
     return;
   if (running_trap > 0)
     {
       internal_debug ("run_pending_traps: recursive invocation while running trap for signal %d", running_trap-1);
 #if defined (SIGWINCH)
       if (running_trap == SIGWINCH+1 && pending_traps[SIGWINCH])
     return;         /* no recursive SIGWINCH trap invocations */
 #endif
       /* could check for running the trap handler for the same signal here
      (running_trap == sig+1) */
       if (evalnest_max > 0 && evalnest > evalnest_max)
     {
       internal_error (_("trap handler: maximum trap handler level exceeded (%d)"), evalnest_max);
       evalnest = 0;
       jump_to_top_level (DISCARD);
     }
     }
   catch_flag = trapped_signal_received = 0;
   /* Preserve $? when running trap. */
   trap_saved_exit_value = old_exit_value = last_command_exit_value;
 #if defined (ARRAY_VARS)
   ps = save_pipestatus_array ();
 #endif
   old_running = running_trap;
   for (sig = 1; sig < NSIG; sig++)
     {
       /* XXX this could be made into a counter by using
      while (pending_traps[sig]--) instead of the if statement. */
       if (pending_traps[sig])
     {
       /* XXX - set last_command_exit_value = trap_saved_exit_value here? */
       running_trap = sig + 1;
       if (sig == SIGINT)
         {
           pending_traps[sig] = 0;   /* XXX */
           /* We don't modify evalnest here, since run_interrupt_trap() calls
          _run_trap_internal, which does. */
           run_interrupt_trap (0);
           CLRINTERRUPT; /* interrupts don't stack */
         }
 #if defined (JOB_CONTROL) && defined (SIGCHLD)
       else if (sig == SIGCHLD &&
            trap_list[SIGCHLD] != (char *)IMPOSSIBLE_TRAP_HANDLER &&
            (sigmodes[SIGCHLD] & SIG_INPROGRESS) == 0)
         {
           sigmodes[SIGCHLD] |= SIG_INPROGRESS;
           /* We modify evalnest here even though run_sigchld_trap can run
          the trap action more than once */
           evalnest++;
           x = pending_traps[sig];
           pending_traps[sig] = 0;
           run_sigchld_trap (x); /* use as counter */
           running_trap = 0;
           evalnest--;
           sigmodes[SIGCHLD] &= ~SIG_INPROGRESS;
           /* continue here rather than reset pending_traps[SIGCHLD] below in
          case there are recursive calls to run_pending_traps and children
          have been reaped while run_sigchld_trap was running. */
           continue;
         }
       else if (sig == SIGCHLD &&
            trap_list[SIGCHLD] == (char *)IMPOSSIBLE_TRAP_HANDLER &&
            (sigmodes[SIGCHLD] & SIG_INPROGRESS) != 0)
         {
           /* This can happen when run_pending_traps is called while
          running a SIGCHLD trap handler. */
           running_trap = 0;
           /* want to leave pending_traps[SIGCHLD] alone here */
           continue;                 /* XXX */
         }
       else if (sig == SIGCHLD && (sigmodes[SIGCHLD] & SIG_INPROGRESS))
         {
           /* whoops -- print warning? */
           running_trap = 0;     /* XXX */
           /* want to leave pending_traps[SIGCHLD] alone here */
           continue;
         }
 #endif
       else if (trap_list[sig] == (char *)DEFAULT_SIG ||
            trap_list[sig] == (char *)IGNORE_SIG ||
            trap_list[sig] == (char *)IMPOSSIBLE_TRAP_HANDLER)
         {
           /* This is possible due to a race condition.  Say a bash
          process has SIGTERM trapped.  A subshell is spawned
          using { list; } & and the parent does something and kills
          the subshell with SIGTERM.  It's possible for the subshell
          to set pending_traps[SIGTERM] to 1 before the code in
          execute_cmd.c eventually calls restore_original_signals
          to reset the SIGTERM signal handler in the subshell.  The
          next time run_pending_traps is called, pending_traps[SIGTERM]
          will be 1, but the trap handler in trap_list[SIGTERM] will
          be invalid (probably DEFAULT_SIG, but it could be IGNORE_SIG).
          Unless we catch this, the subshell will dump core when
          trap_list[SIGTERM] == DEFAULT_SIG, because DEFAULT_SIG is
          usually 0x0. */
           internal_warning (_("run_pending_traps: bad value in trap_list[%d]: %p"),
                 sig, trap_list[sig]);
           if (trap_list[sig] == (char *)DEFAULT_SIG)
         {
           internal_warning (_("run_pending_traps: signal handler is SIG_DFL, resending %d (%s) to myself"), sig, signal_name (sig));
           kill (getpid (), sig);
         }
         }
       else
         {
           old_trap = trap_list[sig];
           trap_command = savestring (old_trap);
           save_parser_state (&pstate);
           save_subst_varlist = subst_assign_varlist;
           subst_assign_varlist = 0;
           save_tempenv = temporary_env;
           temporary_env = 0;    /* traps should not run with temporary env */
 #if defined (JOB_CONTROL)
           save_pipeline (1);    /* XXX only provides one save level */
 #endif
           /* XXX - set pending_traps[sig] = 0 here? */
           pending_traps[sig] = 0;
           evalnest++;
           function_code = 0;
           save_return_catch_flag = return_catch_flag;
           if (return_catch_flag)
         {
           COPY_PROCENV (return_catch, save_return_catch);
           function_code = setjmp_nosigs (return_catch);
         }
           if (function_code == 0)
             /* XXX is x always last_command_exit_value? */
         x = parse_and_execute (trap_command, "trap", SEVAL_NONINT|SEVAL_NOHIST|SEVAL_RESETLINE|SEVAL_NOOPTIMIZE);
           else
         {
           parse_and_execute_cleanup (sig + 1);  /* XXX - could use -1 */
           x = return_catch_value;
         }
           evalnest--;
 #if defined (JOB_CONTROL)
           restore_pipeline (1);
 #endif
           subst_assign_varlist = save_subst_varlist;
           restore_parser_state (&pstate);
           temporary_env = save_tempenv;
           if (save_return_catch_flag)
         {
           return_catch_flag = save_return_catch_flag;
           return_catch_value = x;
           COPY_PROCENV (save_return_catch, return_catch);
           if (function_code)
             {
               running_trap = old_running;       /* XXX */
               /* caller will set last_command_exit_value */
               sh_longjmp (return_catch, 1);
             }
         }
         }
       pending_traps[sig] = 0;   /* XXX - move before evalstring? */
       running_trap = old_running;
     }
     }
 #if defined (ARRAY_VARS)
   restore_pipestatus_array (ps);
 #endif
   last_command_exit_value = old_exit_value;
 }
References _, catch_flag, CLRINTERRUPT, COPY_PROCENV, DEFAULT_SIG, DISCARD, evalnest, evalnest_max, getpid(), IGNORE_SIG, IMPOSSIBLE_TRAP_HANDLER, internal_debug(), internal_error(), internal_warning(), jump_to_top_level(), kill(), last_command_exit_value, NSIG, parse_and_execute(), parse_and_execute_cleanup(), pending_traps, procenv_t, restore_parser_state(), restore_pipeline(), return_catch, return_catch_flag, return_catch_value, run_interrupt_trap(), run_sigchld_trap(), running_trap, save_parser_state(), save_pipeline(), savestring(), setjmp_nosigs, SEVAL_NOHIST, SEVAL_NONINT, SEVAL_NOOPTIMIZE, SEVAL_RESETLINE, sh_longjmp, SIG_INPROGRESS, SIGCHLD, SIGINT, sigmodes, signal_name(), SIGWINCH, subst_assign_varlist, temporary_env, trap_list, trap_saved_exit_value, trapped_signal_received, and x.
Referenced by check_signals_and_traps(), execute_command_internal(), execute_connection(), getc_with_restart(), glob_filename(), parse_command(), and redir_open().
run_return_trap()
void run_return_trap ()
Definition at line 1246 of file trap.c.
 {
   int old_exit_value;
 #if 0
   if ((sigmodes[DEBUG_TRAP] & SIG_TRAPPED) && (sigmodes[DEBUG_TRAP] & SIG_INPROGRESS))
     return;
 #endif
   if ((sigmodes[RETURN_TRAP] & SIG_TRAPPED) && ((sigmodes[RETURN_TRAP] & SIG_IGNORED) == 0) && (sigmodes[RETURN_TRAP] & SIG_INPROGRESS) == 0)
     {
       old_exit_value = last_command_exit_value;
       _run_trap_internal (RETURN_TRAP, "return trap");
       last_command_exit_value = old_exit_value;
     }
 }
References _run_trap_internal(), DEBUG_TRAP, last_command_exit_value, RETURN_TRAP, SIG_IGNORED, SIG_INPROGRESS, SIG_TRAPPED, and sigmodes.
Referenced by execute_function(), and source_file().
run_trap_cleanup()
void run_trap_cleanup (int sig)
Definition at line 1036 of file trap.c.
 {
   /* XXX - should we clean up trap_list[sig] == IMPOSSIBLE_TRAP_HANDLER? */
   sigmodes[sig] &= ~(SIG_INPROGRESS|SIG_CHANGED);
 }
References SIG_CHANGED, SIG_INPROGRESS, and sigmodes.
Referenced by execute_in_subshell(), parse_and_execute_cleanup(), run_interrupt_trap(), and throw_to_top_level().
set_debug_trap()
void set_debug_trap (char * command)
Definition at line 696 of file trap.c.
 {
   set_signal (DEBUG_TRAP, command);
 }
References DEBUG_TRAP, and set_signal().
set_error_trap()
void set_error_trap (char * command)
Definition at line 716 of file trap.c.
 {
   set_signal (ERROR_TRAP, command);
 }
References ERROR_TRAP, and set_signal().
Referenced by execute_builtin().
set_original_signal()
void set_original_signal (int sig, SigHandler * handler)
Definition at line 886 of file trap.c.
 {
   if (sig > 0 && sig < NSIG && original_signals[sig] == (SigHandler *)IMPOSSIBLE_TRAP_HANDLER)
     SETORIGSIG (sig, handler);
 }
References handler(), IMPOSSIBLE_TRAP_HANDLER, NSIG, original_signals, and SETORIGSIG.
Referenced by get_original_tty_job_signals(), and initialize_terminating_signals().
set_return_trap()
void set_return_trap (char * command)
Definition at line 730 of file trap.c.
 {
   set_signal (RETURN_TRAP, command);
 }
References RETURN_TRAP, and set_signal().
set_sigint_handler()
SigHandler* set_sigint_handler ()
Definition at line 756 of file trap.c.
 {
   if (sigmodes[SIGINT] & SIG_HARD_IGNORE)
     return ((SigHandler *)SIG_IGN);
   else if (sigmodes[SIGINT] & SIG_IGNORED)
     return ((SigHandler *)set_signal_handler (SIGINT, SIG_IGN)); /* XXX */
   else if (sigmodes[SIGINT] & SIG_TRAPPED)
     return ((SigHandler *)set_signal_handler (SIGINT, trap_handler));
   /* The signal is not trapped, so set the handler to the shell's special
      interrupt handler. */
   else if (interactive) /* XXX - was interactive_shell */
     return (set_signal_handler (SIGINT, sigint_sighandler));
   else
     return (set_signal_handler (SIGINT, termsig_sighandler));
 }
References interactive, set_signal_handler, SIG_HARD_IGNORE, SIG_IGN, SIG_IGNORED, SIG_TRAPPED, SIGINT, sigint_sighandler(), sigmodes, termsig_sighandler(), and trap_handler().
Referenced by command_substitute(), execute_in_subshell(), execute_subshell_builtin_or_function(), and shell_execve().
set_signal()
void set_signal (int sig, char * string)
Definition at line 791 of file trap.c.
 {
   sigset_t set, oset;
   if (SPECIAL_TRAP (sig))
     {
       change_signal (sig, savestring (string));
       if (sig == EXIT_TRAP && interactive == 0)
     initialize_terminating_signals ();
       return;
     }
   /* A signal ignored on entry to the shell cannot be trapped or reset, but
      no error is reported when attempting to do so.  -- Posix.2 */
   if (sigmodes[sig] & SIG_HARD_IGNORE)
     return;
   /* Make sure we have original_signals[sig] if the signal has not yet
      been trapped. */
   if ((sigmodes[sig] & SIG_TRAPPED) == 0)
     {
       /* If we aren't sure of the original value, check it. */
       if (original_signals[sig] == IMPOSSIBLE_TRAP_HANDLER)
         GETORIGSIG (sig);
       if (original_signals[sig] == SIG_IGN)
     return;
     }
   /* Only change the system signal handler if SIG_NO_TRAP is not set.
      The trap command string is changed in either case.  The shell signal
      handlers for SIGINT and SIGCHLD run the user specified traps in an
      environment in which it is safe to do so. */
   if ((sigmodes[sig] & SIG_NO_TRAP) == 0)
     {
       BLOCK_SIGNAL (sig, set, oset);
       change_signal (sig, savestring (string));
       set_signal_handler (sig, trap_handler);
       UNBLOCK_SIGNAL (oset);
     }
   else
     change_signal (sig, savestring (string));
 }
References BLOCK_SIGNAL, change_signal(), EXIT_TRAP, GETORIGSIG, IMPOSSIBLE_TRAP_HANDLER, initialize_terminating_signals(), interactive, original_signals, savestring(), set_signal_handler, SIG_HARD_IGNORE, SIG_IGN, SIG_NO_TRAP, SIG_TRAPPED, sigmodes, SPECIAL_TRAP, trap_handler(), and UNBLOCK_SIGNAL.
Referenced by restore_traps(), set_debug_trap(), set_error_trap(), set_return_trap(), and trap_if_untrapped().
set_signal_hard_ignored()
void set_signal_hard_ignored (int sig)
Definition at line 1538 of file trap.c.
 {
   sigmodes[sig] |= SIG_HARD_IGNORE;
   original_signals[sig] = SIG_IGN;
 }
References original_signals, SIG_HARD_IGNORE, SIG_IGN, and sigmodes.
Referenced by initialize_terminating_signals().
set_signal_ignored()
void set_signal_ignored (int sig)
Definition at line 1546 of file trap.c.
 {
   original_signals[sig] = SIG_IGN;
 }
References original_signals, and SIG_IGN.
set_trap_state()
void set_trap_state (int sig)
Definition at line 493 of file trap.c.
 {
   catch_flag = 1;
   pending_traps[sig]++;
   trapped_signal_received = sig;
 }
References catch_flag, pending_traps, and trapped_signal_received.
Referenced by sigint_sighandler(), and trap_handler().
signal_in_progress()
int signal_in_progress (int sig)
Definition at line 1553 of file trap.c.
 {
   return (sigmodes[sig] & SIG_INPROGRESS);
 }
References SIG_INPROGRESS, and sigmodes.
Referenced by execute_case_command(), execute_command_internal(), execute_for_command(), execute_function(), execute_simple_command(), and waitchld().
signal_is_hard_ignored()
int signal_is_hard_ignored (int sig)
Definition at line 1531 of file trap.c.
 {
   return (sigmodes[sig] & SIG_HARD_IGNORE);
 }
References SIG_HARD_IGNORE, and sigmodes.
Referenced by default_tty_job_signals().
signal_is_ignored()
int signal_is_ignored (int sig)
Definition at line 1524 of file trap.c.
 {
   return (sigmodes[sig] & SIG_IGNORED);
 }
References SIG_IGNORED, and sigmodes.
Referenced by execute_command_internal(), execute_connection(), and reader_loop().
signal_is_pending()
int signal_is_pending (int sig)
Definition at line 1510 of file trap.c.
 {
   return (pending_traps[sig]);
 }
References pending_traps.
Referenced by glob_vector(), and throw_to_top_level().
signal_is_special()
int signal_is_special (int sig)
Definition at line 1517 of file trap.c.
 {
   return (sigmodes[sig] & SIG_SPECIAL);
 }
References SIG_SPECIAL, and sigmodes.
Referenced by reset_terminating_signals().
signal_is_trapped()
int signal_is_trapped (int sig)
Definition at line 1503 of file trap.c.
 {
   return (sigmodes[sig] & SIG_TRAPPED);
 }
References SIG_TRAPPED, and sigmodes.
Referenced by default_tty_job_signals(), execute_command_internal(), execute_connection(), execute_in_subshell(), exit_shell(), initialize_terminating_signals(), morecore(), notify_of_job_status(), parse_and_execute(), reader_loop(), reset_terminating_signals(), set_job_status_and_cleanup(), should_optimize_fork(), sigint_sighandler(), subshell_exit(), termsig_handler(), throw_to_top_level(), wait_for(), wait_sigint_handler(), and waitchld().
signal_name()
char* signal_name (int sig)
Definition at line 213 of file trap.c.
 {
   char *ret;
   /* on cygwin32, signal_names[sig] could be null */
   ret = (sig >= BASH_NSIG || sig < 0 || signal_names[sig] == NULL)
     ? _("invalid signal number")
     : signal_names[sig];
   return ret;
 }
References _, BASH_NSIG, NULL, and signal_names.
Referenced by display_signal_list(), printable_job_status(), and run_pending_traps().
trap_handler()
sighandler trap_handler (int sig)
Definition at line 502 of file trap.c.
 {
   int oerrno;
   if ((sigmodes[sig] & SIG_TRAPPED) == 0)
     {
       internal_debug ("trap_handler: signal %d: signal not trapped", sig);
       SIGRETURN (0);
     }
   /* This means we're in a subshell, but have not yet reset the handler for
      trapped signals. We're not supposed to execute the trap in this situation;
      we should restore the original signal and resend the signal to ourselves
      to preserve the Posix "signal traps that are not being ignored shall be
      set to the default action" semantics. */
   if ((subshell_environment & SUBSHELL_IGNTRAP) && trap_list[sig] != (char *)IGNORE_SIG)
     {
       sigset_t mask;
       /* Paranoia */
       if (original_signals[sig] == IMPOSSIBLE_TRAP_HANDLER)
     original_signals[sig] = SIG_DFL;
       restore_signal (sig);
       /* Make sure we let the signal we just caught through */
       sigemptyset (&mask);
       sigprocmask (SIG_SETMASK, (sigset_t *)NULL, &mask);
       sigdelset (&mask, sig);
       sigprocmask (SIG_SETMASK, &mask, (sigset_t *)NULL);
       kill (getpid (), sig);
       SIGRETURN (0);
     }
   if ((sig >= NSIG) ||
       (trap_list[sig] == (char *)DEFAULT_SIG) ||
       (trap_list[sig] == (char *)IGNORE_SIG))
     programming_error (_("trap_handler: bad signal %d"), sig);
   else
     {
       oerrno = errno;
 #if defined (MUST_REINSTALL_SIGHANDLERS)
 #  if defined (JOB_CONTROL) && defined (SIGCHLD)
       if (sig != SIGCHLD)
 #  endif /* JOB_CONTROL && SIGCHLD */
       set_signal_handler (sig, trap_handler);
 #endif /* MUST_REINSTALL_SIGHANDLERS */
       set_trap_state (sig);
       if (this_shell_builtin && (this_shell_builtin == wait_builtin))
     {
       wait_signal_received = sig;
       if (waiting_for_child && wait_intr_flag)
         sh_longjmp (wait_intr_buf, 1);
     }
 #if defined (READLINE)
       /* Set the event hook so readline will call it after the signal handlers
      finish executing, so if this interrupted character input we can get
      quick response. */
       if (RL_ISSTATE (RL_STATE_SIGHANDLER))
         bashline_set_event_hook ();
 #endif
       errno = oerrno;
     }
   SIGRETURN (0);
 }
References _, DEFAULT_SIG, errno, getpid(), IGNORE_SIG, IMPOSSIBLE_TRAP_HANDLER, internal_debug(), kill(), NSIG, NULL, original_signals, programming_error(), restore_signal(), RL_ISSTATE, RL_STATE_SIGHANDLER, set_signal_handler, set_trap_state(), sh_longjmp, SIG_DFL, SIG_SETMASK, SIG_TRAPPED, SIGCHLD, sigdelset(), sigemptyset(), sigmodes, sigprocmask(), SIGRETURN, subshell_environment, SUBSHELL_IGNTRAP, this_shell_builtin, trap_list, wait_intr_buf, wait_intr_flag, wait_signal_received, and waiting_for_child.
Referenced by maybe_call_trap_handler(), set_job_status_and_cleanup(), set_sigint_handler(), set_signal(), trap_to_sighandler(), and wait_sigint_handler().
trap_if_untrapped()
static void trap_if_untrapped (int sig, char * command) inline static
Definition at line 687 of file trap.c.
 {
   if ((sigmodes[sig] & SIG_TRAPPED) == 0)
     set_signal (sig, command);
 }
References set_signal(), SIG_TRAPPED, and sigmodes.
Referenced by maybe_set_debug_trap(), maybe_set_error_trap(), and maybe_set_return_trap().
trap_to_sighandler()
SigHandler* trap_to_sighandler (int sig)
Definition at line 778 of file trap.c.
 {
   if (sigmodes[sig] & (SIG_IGNORED|SIG_HARD_IGNORE))
     return (SIG_IGN);
   else if (sigmodes[sig] & SIG_TRAPPED)
     return (trap_handler);
   else
     return (SIG_DFL);
 }
References SIG_DFL, SIG_HARD_IGNORE, SIG_IGN, SIG_IGNORED, SIG_TRAPPED, sigmodes, and trap_handler().
Referenced by set_job_status_and_cleanup(), and wait_sigint_handler().
Variable Documentation
catch_flag
int catch_flag static
Definition at line 294 of file trap.c.
Referenced by run_interrupt_trap(), run_pending_traps(), and set_trap_state().
errno
int errno extern
Referenced by trap_handler().
from_return_trap
volatile int from_return_trap extern
Definition at line 310 of file execute_cmd.c.
Referenced by _run_trap_internal(), and execute_function().
original_signals
SigHandler* original_signals[NSIG]
Definition at line 98 of file trap.c.
Referenced by get_original_signal(), initialize_traps(), reset_signal(), restore_default_signal(), restore_signal(), set_original_signal(), set_signal(), set_signal_hard_ignored(), set_signal_ignored(), and trap_handler().
pending_traps
int pending_traps[NSIG]
Definition at line 108 of file trap.c.
Referenced by clear_pending_traps(), initialize_traps(), next_pending_trap(), reset_or_restore_signal_handlers(), restore_traps(), run_interrupt_trap(), run_pending_traps(), set_trap_state(), and signal_is_pending().
running_trap
int running_trap
Definition at line 114 of file trap.c.
Referenced by _run_trap_internal(), evalstring(), execute_case_command(), execute_command_internal(), execute_for_command(), execute_in_subshell(), execute_simple_command(), get_exitstat(), morecore(), parse_and_execute_cleanup(), run_exit_trap(), run_interrupt_trap(), run_pending_traps(), run_sigchld_trap(), should_optimize_fork(), throw_to_top_level(), wait_for(), and waitchld().
sigmodes
int sigmodes[BASH_NSIG] static
Definition at line 75 of file trap.c.
Referenced by _run_trap_internal(), any_signals_trapped(), change_signal(), free_trap_command(), free_trap_string(), free_trap_strings(), ignore_signal(), initialize_traps(), maybe_call_trap_handler(), reinit_trap(), reset_or_restore_signal_handlers(), reset_signal(), restore_default_signal(), restore_signal(), restore_traps(), run_debug_trap(), run_error_trap(), run_exit_trap(), run_pending_traps(), run_return_trap(), run_trap_cleanup(), set_sigint_handler(), set_signal(), set_signal_hard_ignored(), signal_in_progress(), signal_is_hard_ignored(), signal_is_ignored(), signal_is_special(), signal_is_trapped(), trap_handler(), trap_if_untrapped(), and trap_to_sighandler().
subst_assign_varlist
WORD_LIST* subst_assign_varlist extern
Definition at line 177 of file subst.c.
Referenced by _run_trap_internal(), command_substitute(), expand_word_list_internal(), run_pending_traps(), and separate_out_assignments().
suppress_debug_trap_verbose
int suppress_debug_trap_verbose = 0
Definition at line 125 of file trap.c.
Referenced by run_debug_trap().
trap_list
char* trap_list[BASH_NSIG]
Definition at line 105 of file trap.c.
Referenced by _run_trap_internal(), change_signal(), free_trap_command(), free_trap_strings(), initialize_traps(), reinit_trap(), reset_or_restore_signal_handlers(), restore_default_signal(), restore_traps(), run_exit_trap(), run_pending_traps(), run_sigchld_trap(), trap_handler(), and waitchld().
trap_saved_exit_value
int trap_saved_exit_value
Definition at line 117 of file trap.c.
Referenced by _run_trap_internal(), get_exitstat(), run_exit_trap(), and run_pending_traps().
trapped_signal_received
int trapped_signal_received
Definition at line 122 of file trap.c.
Referenced by run_pending_traps(), and set_trap_state().
wait_signal_received
int wait_signal_received
Definition at line 120 of file trap.c.
Referenced by sigint_sighandler(), trap_handler(), wait_sigint_handler(), and waitchld().
waiting_for_child
int waiting_for_child extern
Definition at line 2724 of file jobs.c.
Referenced by restore_sigint_handler(), trap_handler(), wait_for(), wait_for_background_pids(), wait_sigint_cleanup(), and wait_sigint_handler().