Fennix: Userspace/mlibc/options/ansi/include/stdlib.h File Reference
stdlib.h File Reference
#include <alloca.h>
#include <mlibc-config.h>
#include <bits/null.h>
#include <bits/size_t.h>
#include <bits/wchar_t.h>
Data Structures
struct div_t
struct ldiv_t
struct lldiv_t
Macros
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define RAND_MAX 0x7FFFFFFF
#define MB_CUR_MAX 4
Functions
double atof (const char *string)
int atoi (const char *string)
long atol (const char *string)
long long atoll (const char *string)
double strtod (const char *__restrict string, char **__restrict end)
float strtof (const char *__restrict string, char **__restrict end)
long double strtold (const char *__restrict string, char **__restrict end)
long strtol (const char *__restrict string, char **__restrict end, int base)
long long strtoll (const char *__restrict string, char **__restrict end, int base)
unsigned long strtoul (const char *__restrict string, char **__restrict end, int base)
unsigned long long strtoull (const char *__restrict string, char **__restrict end, int base)
int rand (void)
int rand_r (unsigned *)
void srand (unsigned int)
void * aligned_alloc (size_t alignment, size_t size)
void * calloc (size_t count, size_t size)
The standard function.
void free (void *pointer)
The standard function.
void * malloc (size_t size)
The standard function.
void * realloc (void *pointer, size_t size)
The standard function.
int posix_memalign (void **, size_t, size_t)
__attribute__ ((noreturn)) void abort(void)
int atexit (void(*func)(void))
int at_quick_exit (void(*func)(void))
char * getenv (const char *name)
int system (const char *string)
char * mktemp (char *)
void * bsearch (const void *key, const void *base, size_t count, size_t size, int(*compare)(const void *, const void *))
void qsort (void *base, size_t count, size_t size, int(*compare)(const void *, const void *))
void qsort_r (void *base, size_t nmemb, size_t size, int(*compar)(const void *, const void *, void *), void *arg)
int abs (int number)
long labs (long number)
long long llabs (long long number)
div_t div (int number, int denom)
ldiv_t ldiv (long number, long denom)
lldiv_t lldiv (long long number, long long denom)
int mblen (const char *, size_t)
int mbtowc (wchar_t *__restrict wc, const char *__restrict mb_chr, size_t max_size)
int wctomb (char *mb_chr, wchar_t wc)
size_t mbstowcs (wchar_t *__restrict wc_string, const char *__restrict mb_string, size_t max_size)
size_t wcstombs (char *mb_string, const wchar_t *__restrict wc_string, size_t max_size)
Data Structure Documentation
div_t
struct div_t
Definition at line 16 of file stdlib.h.
Data Fields
int quot
int rem
ldiv_t
struct ldiv_t
Definition at line 20 of file stdlib.h.
Data Fields
long quot
long rem
lldiv_t
struct lldiv_t
Definition at line 24 of file stdlib.h.
Data Fields
long long quot
long long rem
Macro Definition Documentation
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 28 of file stdlib.h.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 29 of file stdlib.h.
MB_CUR_MAX
#define MB_CUR_MAX 4
Definition at line 34 of file stdlib.h.
RAND_MAX
#define RAND_MAX 0x7FFFFFFF
Definition at line 31 of file stdlib.h.
Function Documentation
__attribute__()
__attribute__ ((noreturn))
abs()
int abs (int number)
Definition at line 77 of file ld.c.
 { return i < 0 ? -i : i; }
References i, and num.
Referenced by ltoa().
aligned_alloc()
void* aligned_alloc (size_t alignment, size_t size)
Definition at line 119 of file stdlib-stubs.cpp.
{
     void *ptr;
     // alignment must be a power of two, and size % alignment must be 0
     if (alignment & (alignment - 1) || size & (alignment - 1)) {
         errno = EINVAL;
         return nullptr;
     }
     // posix_memalign requires that the alignment is a multiple of sizeof(void *)
     if (alignment < sizeof(void *))
         alignment = sizeof(void *);
     int ret = posix_memalign(&ptr, alignment, size);
     if (ret) {
         errno = ret;
         return nullptr;
     }
     return ptr;
 }
References EINVAL, errno, posix_memalign(), ret, and size.
Referenced by main().
at_quick_exit()
int at_quick_exit (void(*)(void) func)
Definition at line 189 of file stdlib-stubs.cpp.
{
     (void)func;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, and Driver::void().
atexit()
int atexit (void(*)(void) func)
Definition at line 18 of file lib.c.
 {
     return 1;
 }
References __cxa_atexit().
atof()
double atof (const char * string)
Definition at line 548 of file Convert.cpp.
 {
     // Originally from https://github.com/GaloisInc/minlibc/blob/master/atof.c
     /*
     Copyright (c) 2014 Galois Inc.
     All rights reserved.
     Redistribution and use in source and binary forms, with or without
     modification, are permitted provided that the following conditions
     are met:
       * Redistributions of source code must retain the above copyright
         notice, this list of conditions and the following disclaimer.
       * Redistributions in binary form must reproduce the above copyright
         notice, this list of conditions and the following disclaimer in
         the documentation and/or other materials provided with the
         distribution.
       * Neither the name of Galois, Inc. nor the names of its contributors
         may be used to endorse or promote products derived from this
         software without specific prior written permission.
     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
     IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
     TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
     PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
     OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
     EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
     PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     */
     double a = 0.0;
     int e = 0;
     int c;
     while ((c = *String++) != '\0' && isdigit(c))
     {
         a = a * 10.0 + (c - '0');
     }
     if (c == '.')
     {
         while ((c = *String++) != '\0' && isdigit(c))
         {
             a = a * 10.0 + (c - '0');
             e = e - 1;
         }
     }
     if (c == 'e' || c == 'E')
     {
         int sign = 1;
         int i = 0;
         c = *String++;
         if (c == '+')
             c = *String++;
         else if (c == '-')
         {
             c = *String++;
             sign = -1;
         }
         while (isdigit(c))
         {
             i = i * 10 + (c - '0');
             c = *String++;
         }
         e += i * sign;
     }
     while (e > 0)
     {
         a *= 10.0;
         e--;
     }
     while (e < 0)
     {
         a *= 0.1;
         e++;
     }
     return a;
 }
References i, Length, NULL, strlen(), and strtod().
atoi()
int atoi (const char * string)
Definition at line 535 of file Convert.cpp.
 {
     uint64_t Length = strlen((char *)String);
     int OutBuffer = 0;
     int Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (String[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References i, Length, strlen(), and strtol().
atol()
long atol (const char * string)
Definition at line 46 of file stdlib-stubs.cpp.
{
     return strtol(string, nullptr, 10);
 }
References strtol().
atoll()
long long atoll (const char * string)
Definition at line 49 of file stdlib-stubs.cpp.
{
     return strtoll(string, nullptr, 10);
 }
References strtoll().
bsearch()
void* bsearch (const void * key, const void * base, size_t count, size_t size, int(*)(const void *, const void *) compare)
Definition at line 278 of file stdlib-stubs.cpp.
{
     // Invariant: Element is in the interval [i, j).
     size_t i = 0;
     size_t j = count;
     while(i < j) {
         size_t k = (j - i) / 2;
         auto element = reinterpret_cast<const char *>(base) + (i + k) * size;
         auto res = compare(key, element);
         if(res < 0) {
             j = i + k;
         }else if(res > 0) {
             i = i + k + 1;
         }else{
             return const_cast<char *>(element);
         }
     }
     __ensure(i == j);
     return nullptr;
 }
References __ensure, base, compare(), count, i, j, k, and size.
div()
div_t div (int number, int denom)
Definition at line 342 of file stdlib-stubs.cpp.
{
     div_t r;
     r.quot = number / denom;
     r.rem = number % denom;
     return r;
 }
References r.
Referenced by multiboot_main(), and WI_drawTime().
getenv()
char* getenv (const char * name)
Definition at line 46 of file lib.c.
 {
     char **env = environ;
     if (env == NULL)
         return NULL;
     size_t len = strlen(name);
     while (*env != NULL)
     {
         if ((strncmp(*env, name, len) == 0) && ((*env)[len] == '='))
             return &(*env)[len + 1];
         ++env;
     }
 }
References __ensure, environ, anonymous_namespace{environment.cpp}::find_environ_index(), k, and name.
labs()
long labs (long number)
Definition at line 334 of file stdlib-stubs.cpp.
                     {
     return num < 0 ? -num : num;
 }
References num.
Referenced by main().
ldiv()
ldiv_t ldiv (long number, long denom)
Definition at line 349 of file stdlib-stubs.cpp.
{
     ldiv_t r;
     r.quot = number / denom;
     r.rem = number % denom;
     return r;
 }
References r.
llabs()
long long llabs (long long number)
Definition at line 338 of file stdlib-stubs.cpp.
{
     return num < 0 ? -num : num;
 }
References num.
Referenced by main().
lldiv()
lldiv_t lldiv (long long number, long long denom)
Definition at line 356 of file stdlib-stubs.cpp.
{
     lldiv_t r;
     r.quot = number / denom;
     r.rem = number % denom;
     return r;
 }
References r.
mblen()
int mblen (const char * mbs, size_t mb_limit)
Definition at line 363 of file stdlib-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     wchar_t wc;
     mlibc::code_seq<const char> nseq{mbs, mbs + mb_limit};
     mlibc::code_seq<wchar_t> wseq{&wc, &wc + 1};
     if(!mbs) {
         mblen_state = __MLIBC_MBSTATE_INITIALIZER;
         return cc->has_shift_states;
     }
     if(auto e = cc->decode_wtranscode(nseq, wseq, mblen_state); e != mlibc::charcode_error::null)
         __ensure(!"decode_wtranscode() errors are not handled");
     return nseq.it - mbs;
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), anonymous_namespace{stdlib-stubs.cpp}::mblen_state, and mlibc::null.
mbstowcs()
size_t mbstowcs (wchar_t *__restrict wc_string, const char *__restrict mb_string, size_t max_size)
mbtowc()
int mbtowc (wchar_t *__restrict wc, const char *__restrict mb_chr, size_t max_size)
Definition at line 379 of file stdlib-stubs.cpp.
{
     auto cc = mlibc::current_charcode();
     __ensure(max_size);
     // If wc is NULL, decode into a single local character which we discard
     // to obtain the length.
     wchar_t tmp_wc;
     if (!wc)
         wc = &tmp_wc;
     if (mb) {
         if (*mb) {
             mlibc::code_seq<wchar_t> wseq{wc, wc + 1};
             mlibc::code_seq<const char> nseq{mb, mb + max_size};
             auto e = cc->decode_wtranscode(nseq, wseq, mbtowc_state);
             if (e != mlibc::charcode_error::null)
                 __ensure(!"decode_wtranscode() errors are not handled");
             return nseq.it - mb;
         } else {
             *wc = L'\0';
             return 0; // When mbs is a null byte, return 0
         }
     } else {
         mblen_state = __MLIBC_MBSTATE_INITIALIZER;
         return cc->has_shift_states;
     }
 }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, mlibc::current_charcode(), max_size, anonymous_namespace{stdlib-stubs.cpp}::mblen_state, anonymous_namespace{stdlib-stubs.cpp}::mbtowc_state, and mlibc::null.
Referenced by match_bracket(), parse_atom(), parse_bracket_terms(), pat_next(), str_next(), and verify_decode().
mktemp()
char* mktemp (char *)
Definition at line 273 of file stdlib-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
posix_memalign()
int posix_memalign (void ** out, size_t align, size_t size)
Definition at line 470 of file stdlib-stubs.cpp.
{
     if(align < sizeof(void *))
         return EINVAL;
     if(align & (align - 1)) // Make sure that align is a power of two.
         return EINVAL;
     auto p = getAllocator().allocate(frg::max(align, size));
     if(!p)
         return ENOMEM;
     // Hope that the alignment was respected. This works on the current allocator.
     // TODO: Make the allocator alignment-aware.
     __ensure(!(reinterpret_cast<uintptr_t>(p) & (align - 1)));
     *out = p;
     return 0;
 }
References __ensure, EINVAL, ENOMEM, getAllocator(), p, and size.
Referenced by aligned_alloc(), and main().
qsort()
void qsort (void * base, size_t count, size_t size, int(*)(const void *, const void *) compare)
Definition at line 300 of file stdlib-stubs.cpp.
{
     // TODO: implement a faster sort
     for(size_t i = 0; i < count; i++) {
         void *u = (void *)((uintptr_t)base + i * size);
         for(size_t j = i + 1; j < count; j++) {
             void *v = (void *)((uintptr_t)base + j * size);
             if(compare(u, v) <= 0)
                 continue;
             // swap u and v
             char *u_bytes = (char *)u;
             char *v_bytes = (char *)v;
             for(size_t k = 0; k < size; k++) {
                 char temp = u_bytes[k];
                 u_bytes[k] = v_bytes[k];
                 v_bytes[k] = temp;
             }
         }
     }
 }
References base, compare(), count, i, j, k, and size.
Referenced by glob(), parse_bracket(), and scandir().
qsort_r()
void qsort_r (void * base, size_t nmemb, size_t size, int(*)(const void *, const void *, void *) compar, void * arg)
Definition at line 322 of file stdlib-stubs.cpp.
                 {
     (void) compare;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, compare(), and Driver::void().
rand()
int rand (void)
Definition at line 98 of file stdlib-stubs.cpp.
            {
     // rand() is specified to return a positive number so we discard the MSB.
     return static_cast<int>(__mlibc_rand_engine() & 0x7FFFFFFF);
 }
References __mlibc_rand_engine.
rand_r()
int rand_r (unsigned * seed)
Definition at line 111 of file stdlib-stubs.cpp.
{
     return temper(*seed = *seed * 1103515245 + 12345) / 2;
 }
References temper().
srand()
void srand (unsigned int s)
Definition at line 115 of file stdlib-stubs.cpp.
{
     __mlibc_rand_engine.seed(s);
 }
References __mlibc_rand_engine.
strtod()
double strtod (const char *__restrict string, char **__restrict end)
Definition at line 73 of file stdlib-stubs.cpp.
{
     return mlibc::strtofp<double>(string, end);
 }
Referenced by atof(), and strtod_l().
strtof()
float strtof (const char *__restrict string, char **__restrict end)
Definition at line 76 of file stdlib-stubs.cpp.
{
     return mlibc::strtofp<float>(string, end);
 }
Referenced by strtof_l().
strtol()
long strtol (const char *__restrict string, char **__restrict end, int base)
Definition at line 83 of file stdlib-stubs.cpp.
{
     return mlibc::stringToInteger<long, char>(string, end, base);
 }
References base.
Referenced by atoi(), and atol().
strtold()
long double strtold (const char *__restrict string, char **__restrict end)
Definition at line 79 of file stdlib-stubs.cpp.
{
     return mlibc::strtofp<long double>(string, end);
 }
strtoll()
long long strtoll (const char *__restrict string, char **__restrict end, int base)
Definition at line 86 of file stdlib-stubs.cpp.
{
     return mlibc::stringToInteger<long long, char>(string, end, base);
 }
References base.
Referenced by atoll(), and main().
strtoul()
unsigned long strtoul (const char *__restrict string, char **__restrict end, int base)
Definition at line 89 of file stdlib-stubs.cpp.
{
     return mlibc::stringToInteger<unsigned long, char>(string, end, base);
 }
References base.
strtoull()
unsigned long long strtoull (const char *__restrict string, char **__restrict end, int base)
Definition at line 92 of file stdlib-stubs.cpp.
{
     return mlibc::stringToInteger<unsigned long long, char>(string, end, base);
 }
References base.
Referenced by main().
system()
int system (const char * string)
Definition at line 69 of file lib.c.
 {
     return -1;
 }
References _Exit(), child, EINTR, environ, errno, MLIBC_CHECK_OR_ENOSYS, NULL, pthread_testcancel(), sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SIG_BLOCK, SIG_IGN, SIG_SETMASK, sigaddset(), SIGCHLD, sigemptyset(), SIGINT, SIGQUIT, mlibc::status, mlibc::sys_execve(), mlibc::sys_fork(), mlibc::sys_sigaction(), mlibc::sys_sigprocmask(), and mlibc::sys_waitpid().
wcstombs()
size_t wcstombs (char * mb_string, const wchar_t *__restrict wc_string, size_t max_size)
wctomb()
int wctomb (char * mb_chr, wchar_t wc)
Definition at line 408 of file stdlib-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.