Fennix Userspace: Userspace/apps/base/busybox/scripts/test_setenv_leak.c File Reference
test_setenv_leak.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc , char ** argv)
Definition at line 4 of file test_setenv_leak.c.
 {
     char buf[256];
     int i = argv[1] ? atoi(argv[1]) : 999999;
     while (--i > 0) {
         sprintf(buf, "%d", i);
         setenv("VAR", buf, 1);
     }
     printf("Check size of [heap] mapping:\n");
     freopen("/proc/self/maps", "r", stdin);
     while (fgets(buf, sizeof(buf), stdin))
         fputs(buf, stdout);
     return 0;
 }
References argv, atoi(), buf, fgets, fputs, freopen(), i, printf(), setenv(), sprintf(), stdin, and stdout.