Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/p_lights.c File Reference
p_lights.c File Reference
#include "z_zone.h"
#include "m_random.h"
#include "doomdef.h"
#include "p_local.h"
#include "r_state.h"
Functions
void T_FireFlicker (fireflicker_t *flick)
void P_SpawnFireFlicker (sector_t *sector)
void T_LightFlash (lightflash_t *flash)
void P_SpawnLightFlash (sector_t *sector)
void T_StrobeFlash (strobe_t *flash)
void P_SpawnStrobeFlash (sector_t *sector, int fastOrSlow, int inSync)
void EV_StartLightStrobing (line_t *line)
void EV_TurnTagLightsOff (line_t *line)
void EV_LightTurnOn (line_t *line, int bright)
void T_Glow (glow_t *g)
void P_SpawnGlowingLight (sector_t *sector)
Function Documentation
EV_LightTurnOn()
void EV_LightTurnOn (line_t * line, int bright)
Definition at line 264 of file p_lights.c.
 {
     int     i;
     int     j;
     sector_t*   sector;
     sector_t*   temp;
     line_t* templine;
     sector = sectors;
     for (i=0;i<numsectors;i++, sector++)
     {
     if (sector->tag == line->tag)
     {
         // bright = 0 means to search
         // for highest light level
         // surrounding sector
         if (!bright)
         {
         for (j = 0;j < sector->linecount; j++)
         {
             templine = sector->lines[j];
             temp = getNextSector(templine,sector);
             if (!temp)
             continue;
             if (temp->lightlevel > bright)
             bright = temp->lightlevel;
         }
         }
         sector-> lightlevel = bright;
     }
     }
 }
References getNextSector(), i, j, sector_t::lightlevel, sector_t::linecount, sector_t::lines, numsectors, sectors, sector_t::tag, and line_s::tag.
Referenced by P_CrossSpecialLine(), and P_UseSpecialLine().
EV_StartLightStrobing()
void EV_StartLightStrobing (line_t * line)
Definition at line 208 of file p_lights.c.
 {
     int     secnum;
     sector_t*   sec;
     secnum = -1;
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     if (sec->specialdata)
         continue;
     P_SpawnStrobeFlash (sec,SLOWDARK, 0);
     }
 }
References P_FindSectorFromLineTag(), P_SpawnStrobeFlash(), sectors, SLOWDARK, and sector_t::specialdata.
Referenced by P_CrossSpecialLine().
EV_TurnTagLightsOff()
void EV_TurnTagLightsOff (line_t * line)
Definition at line 229 of file p_lights.c.
 {
     int         i;
     int         j;
     int         min;
     sector_t*       sector;
     sector_t*       tsec;
     line_t*     templine;
     sector = sectors;
     for (j = 0;j < numsectors; j++, sector++)
     {
     if (sector->tag == line->tag)
     {
         min = sector->lightlevel;
         for (i = 0;i < sector->linecount; i++)
         {
         templine = sector->lines[i];
         tsec = getNextSector(templine,sector);
         if (!tsec)
             continue;
         if (tsec->lightlevel < min)
             min = tsec->lightlevel;
         }
         sector->lightlevel = min;
     }
     }
 }
References getNextSector(), i, j, sector_t::lightlevel, sector_t::linecount, sector_t::lines, numsectors, sectors, sector_t::tag, and line_s::tag.
Referenced by P_CrossSpecialLine().
P_SpawnFireFlicker()
void P_SpawnFireFlicker (sector_t * sector)
Definition at line 61 of file p_lights.c.
 {
     fireflicker_t*  flick;
     // Note that we are resetting sector attributes.
     // Nothing special about it during gameplay.
     sector->special = 0;
     flick = Z_Malloc ( sizeof(*flick), PU_LEVSPEC, 0);
     P_AddThinker (&flick->thinker);
     flick->thinker.function.acp1 = (actionf_p1) T_FireFlicker;
     flick->sector = sector;
     flick->maxlight = sector->lightlevel;
     flick->minlight = P_FindMinSurroundingLight(sector,sector->lightlevel)+16;
     flick->count = 4;
 }
References actionf_t::acp1, fireflicker_t::count, thinker_s::function, sector_t::lightlevel, fireflicker_t::maxlight, fireflicker_t::minlight, P_AddThinker(), P_FindMinSurroundingLight(), PU_LEVSPEC, fireflicker_t::sector, sector_t::special, T_FireFlicker(), fireflicker_t::thinker, and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnGlowingLight()
void P_SpawnGlowingLight (sector_t * sector)
Definition at line 334 of file p_lights.c.
 {
     glow_t* g;
     g = Z_Malloc( sizeof(*g), PU_LEVSPEC, 0);
     P_AddThinker(&g->thinker);
     g->sector = sector;
     g->minlight = P_FindMinSurroundingLight(sector,sector->lightlevel);
     g->maxlight = sector->lightlevel;
     g->thinker.function.acp1 = (actionf_p1) T_Glow;
     g->direction = -1;
     sector->special = 0;
 }
References g, sector_t::lightlevel, P_AddThinker(), P_FindMinSurroundingLight(), PU_LEVSPEC, sector_t::special, T_Glow(), and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnLightFlash()
void P_SpawnLightFlash (sector_t * sector)
Definition at line 117 of file p_lights.c.
 {
     lightflash_t*   flash;
     // nothing special about it during gameplay
     sector->special = 0;
     flash = Z_Malloc ( sizeof(*flash), PU_LEVSPEC, 0);
     P_AddThinker (&flash->thinker);
     flash->thinker.function.acp1 = (actionf_p1) T_LightFlash;
     flash->sector = sector;
     flash->maxlight = sector->lightlevel;
     flash->minlight = P_FindMinSurroundingLight(sector,sector->lightlevel);
     flash->maxtime = 64;
     flash->mintime = 7;
     flash->count = (P_Random()&flash->maxtime)+1;
 }
References actionf_t::acp1, lightflash_t::count, thinker_s::function, sector_t::lightlevel, lightflash_t::maxlight, lightflash_t::maxtime, lightflash_t::minlight, lightflash_t::mintime, P_AddThinker(), P_FindMinSurroundingLight(), P_Random(), PU_LEVSPEC, lightflash_t::sector, sector_t::special, T_LightFlash(), lightflash_t::thinker, and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnStrobeFlash()
void P_SpawnStrobeFlash (sector_t * sector, int fastOrSlow, int inSync)
Definition at line 174 of file p_lights.c.
 {
     strobe_t*   flash;
     flash = Z_Malloc ( sizeof(*flash), PU_LEVSPEC, 0);
     P_AddThinker (&flash->thinker);
     flash->sector = sector;
     flash->darktime = fastOrSlow;
     flash->brighttime = STROBEBRIGHT;
     flash->thinker.function.acp1 = (actionf_p1) T_StrobeFlash;
     flash->maxlight = sector->lightlevel;
     flash->minlight = P_FindMinSurroundingLight(sector, sector->lightlevel);
     if (flash->minlight == flash->maxlight)
     flash->minlight = 0;
     // nothing special about it during gameplay
     sector->special = 0;
     if (!inSync)
     flash->count = (P_Random()&7)+1;
     else
     flash->count = 1;
 }
References actionf_t::acp1, strobe_t::brighttime, strobe_t::count, strobe_t::darktime, thinker_s::function, sector_t::lightlevel, strobe_t::maxlight, strobe_t::minlight, P_AddThinker(), P_FindMinSurroundingLight(), P_Random(), PU_LEVSPEC, strobe_t::sector, sector_t::special, STROBEBRIGHT, T_StrobeFlash(), strobe_t::thinker, and Z_Malloc().
Referenced by EV_StartLightStrobing(), and P_SpawnSpecials().
T_FireFlicker()
void T_FireFlicker (fireflicker_t * flick)
Definition at line 39 of file p_lights.c.
 {
     int amount;
     if (--flick->count)
     return;
     amount = (P_Random()&3)*16;
     if (flick->sector->lightlevel - amount < flick->minlight)
     flick->sector->lightlevel = flick->minlight;
     else
     flick->sector->lightlevel = flick->maxlight - amount;
     flick->count = 4;
 }
References fireflicker_t::count, sector_t::lightlevel, fireflicker_t::maxlight, fireflicker_t::minlight, P_Random(), and fireflicker_t::sector.
Referenced by P_SpawnFireFlicker().
T_Glow()
void T_Glow (glow_t * g)
Definition at line 307 of file p_lights.c.
 {
     switch(g->direction)
     {
       case -1:
     // DOWN
     g->sector->lightlevel -= GLOWSPEED;
     if (g->sector->lightlevel <= g->minlight)
     {
         g->sector->lightlevel += GLOWSPEED;
         g->direction = 1;
     }
     break;
       case 1:
     // UP
     g->sector->lightlevel += GLOWSPEED;
     if (g->sector->lightlevel >= g->maxlight)
     {
         g->sector->lightlevel -= GLOWSPEED;
         g->direction = -1;
     }
     break;
     }
 }
References g, and GLOWSPEED.
Referenced by P_ArchiveSpecials(), P_SpawnGlowingLight(), and P_UnArchiveSpecials().
T_LightFlash()
void T_LightFlash (lightflash_t * flash)
Definition at line 91 of file p_lights.c.
 {
     if (--flash->count)
     return;
     if (flash->sector->lightlevel == flash->maxlight)
     {
     flash-> sector->lightlevel = flash->minlight;
     flash->count = (P_Random()&flash->mintime)+1;
     }
     else
     {
     flash-> sector->lightlevel = flash->maxlight;
     flash->count = (P_Random()&flash->maxtime)+1;
     }
 }
References lightflash_t::count, sector_t::lightlevel, lightflash_t::maxlight, lightflash_t::maxtime, lightflash_t::minlight, lightflash_t::mintime, P_Random(), and lightflash_t::sector.
Referenced by P_ArchiveSpecials(), P_SpawnLightFlash(), and P_UnArchiveSpecials().
T_StrobeFlash()
void T_StrobeFlash (strobe_t * flash)
Definition at line 148 of file p_lights.c.
 {
     if (--flash->count)
     return;
     if (flash->sector->lightlevel == flash->minlight)
     {
     flash-> sector->lightlevel = flash->maxlight;
     flash->count = flash->brighttime;
     }
     else
     {
     flash-> sector->lightlevel = flash->minlight;
     flash->count =flash->darktime;
     }
 }
References strobe_t::brighttime, strobe_t::count, strobe_t::darktime, sector_t::lightlevel, strobe_t::maxlight, strobe_t::minlight, and strobe_t::sector.
Referenced by P_ArchiveSpecials(), P_SpawnStrobeFlash(), and P_UnArchiveSpecials().