Fennix: Userspace/apps/base/busybox/libbb/executable.c File Reference
executable.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC file_is_executable (const char *name)
char *FAST_FUNC find_executable (const char *filename, char **PATHp)
int FAST_FUNC executable_exists (const char *filename)
void FAST_FUNC BB_EXECVP_or_die (char **argv)
Function Documentation
BB_EXECVP_or_die()
void FAST_FUNC BB_EXECVP_or_die (char ** argv)
Definition at line 87 of file executable.c.
 {
     BB_EXECVP(argv[0], argv);
     /* SUSv3-mandated exit codes */
     xfunc_error_retval = (errno == ENOENT) ? 127 : 126;
     bb_perror_msg_and_die("can't execute '%s'", argv[0]);
 }
References argv, BB_EXECVP, bb_perror_msg_and_die(), ENOENT, errno, and xfunc_error_retval.
Referenced by bootchartd_main(), chpst_main(), chroot_main(), chrt_main(), cttyhack_main(), doexec(), env_main(), exec_prog_or_SHELL(), ionice_main(), launch_helper(), lpd_main(), nice_main(), nohup_main(), parse(), run_command(), runcon_main(), setarch_main(), setpriv_main(), setsid_main(), taskset_main(), tcpudpsvd_main(), timeout_main(), and vfork_child().
executable_exists()
int FAST_FUNC executable_exists (const char * filename)
Definition at line 69 of file executable.c.
 {
     char *path = getenv("PATH");
     char *ret = find_executable(filename, &path);
     free(ret);
     return ret != NULL;
 }
References filename, find_executable(), free, getenv, and NULL.
file_is_executable()
int FAST_FUNC file_is_executable (const char * name)
Definition at line 15 of file executable.c.
 {
     struct stat s;
     return (!access(name, X_OK) && !stat(name, &s) && S_ISREG(s.st_mode));
 }
References access(), s, S_ISREG, stat(), and X_OK.
Referenced by find_executable(), and which_main().
find_executable()
char* FAST_FUNC find_executable (const char * filename, char ** PATHp)
Definition at line 31 of file executable.c.
 {
     /* About empty components in $PATH:
      * http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html
      * 8.3 Other Environment Variables - PATH
      * A zero-length prefix is a legacy feature that indicates the current
      * working directory. It appears as two adjacent colons ( "::" ), as an
      * initial colon preceding the rest of the list, or as a trailing colon
      * following the rest of the list.
      */
     char *p, *n;
     p = *PATHp;
     while (p) {
         int ex;
         n = strchr(p, ':');
         if (n) *n = '\0';
         p = concat_path_file(
             p[0] ? p : ".", /* handle "::" case */
             filename
         );
         ex = file_is_executable(p);
         if (n) *n++ = ':';
         if (ex) {
             *PATHp = n;
             return p;
         }
         free(p);
         p = n;
     } /* on loop exit p == NULL */
     return p;
 }
References concat_path_file(), file_is_executable(), filename, free, n, p, and strchr().
Referenced by executable_exists(), and which_main().