Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/p_tick.c File Reference
p_tick.c File Reference
#include "z_zone.h"
#include "p_local.h"
#include "doomstat.h"
Functions
void P_InitThinkers (void)
void P_AddThinker (thinker_t *thinker)
void P_RemoveThinker (thinker_t *thinker)
void P_AllocateThinker (thinker_t *thinker)
void P_RunThinkers (void)
void P_Ticker (void)
Variables
int leveltime
thinker_t thinkercap
Function Documentation
P_AddThinker()
void P_AddThinker (thinker_t * thinker)
Definition at line 58 of file p_tick.c.
 {
     thinkercap.prev->next = thinker;
     thinker->next = &thinkercap;
     thinker->prev = thinkercap.prev;
     thinkercap.prev = thinker;
 }
References thinker_s::next, thinker_s::prev, and thinkercap.
Referenced by EV_BuildStairs(), EV_DoCeiling(), EV_DoDonut(), EV_DoDoor(), EV_DoFloor(), EV_DoPlat(), EV_VerticalDoor(), P_SpawnDoorCloseIn30(), P_SpawnDoorRaiseIn5Mins(), P_SpawnFireFlicker(), P_SpawnGlowingLight(), P_SpawnLightFlash(), P_SpawnMobj(), P_SpawnStrobeFlash(), P_UnArchiveSpecials(), and P_UnArchiveThinkers().
P_AllocateThinker()
void P_AllocateThinker (thinker_t * thinker)
Definition at line 85 of file p_tick.c.
 {
 }
P_InitThinkers()
void P_InitThinkers (void)
Definition at line 46 of file p_tick.c.
 {
     thinkercap.prev = thinkercap.next  = &thinkercap;
 }
References thinker_s::next, thinker_s::prev, and thinkercap.
Referenced by P_SetupLevel(), and P_UnArchiveThinkers().
P_RemoveThinker()
void P_RemoveThinker (thinker_t * thinker)
Definition at line 73 of file p_tick.c.
 {
   // FIXME: NOP.
   thinker->function.acv = (actionf_v)(-1);
 }
References actionf_t::acv, and thinker_s::function.
Referenced by P_RemoveActiveCeiling(), P_RemoveActivePlat(), P_RemoveMobj(), T_MoveFloor(), and T_VerticalDoor().
P_RunThinkers()
void P_RunThinkers (void)
Definition at line 94 of file p_tick.c.
 {
     thinker_t*  currentthinker;
     currentthinker = thinkercap.next;
     while (currentthinker != &thinkercap)
     {
     if ( currentthinker->function.acv == (actionf_v)(-1) )
     {
         // time to remove it
         currentthinker->next->prev = currentthinker->prev;
         currentthinker->prev->next = currentthinker->next;
         Z_Free (currentthinker);
     }
     else
     {
         if (currentthinker->function.acp1)
         currentthinker->function.acp1 (currentthinker);
     }
     currentthinker = currentthinker->next;
     }
 }
References actionf_t::acp1, actionf_t::acv, thinker_s::function, thinker_s::next, thinker_s::prev, thinkercap, and Z_Free().
Referenced by P_Ticker().
P_Ticker()
void P_Ticker (void)
Definition at line 123 of file p_tick.c.
 {
     int     i;
     // run the tic
     if (paused)
     return;
     // pause if in menu and at least one tic has been run
     if ( !netgame
      && menuactive
      && !demoplayback
      && players[consoleplayer].viewz != 1)
     {
     return;
     }
     for (i=0 ; i<MAXPLAYERS ; i++)
     if (playeringame[i])
         P_PlayerThink (&players[i]);
     P_RunThinkers ();
     P_UpdateSpecials ();
     P_RespawnSpecials ();
     // for par times
     leveltime++;
 }
References consoleplayer, demoplayback, i, leveltime, MAXPLAYERS, menuactive, netgame, P_PlayerThink(), P_RespawnSpecials(), P_RunThinkers(), P_UpdateSpecials(), paused, playeringame, players, and viewz.
Referenced by G_Ticker().
Variable Documentation
leveltime
int leveltime
Definition at line 27 of file p_tick.c.
Referenced by A_WeaponReady(), G_DoCompleted(), G_DoLoadGame(), P_CalcHeight(), P_CalcSwing(), P_MobjThinker(), P_PlayerInSpecialSector(), P_ReadSaveGameHeader(), P_RemoveMobj(), P_RespawnSpecials(), P_SetupLevel(), P_Ticker(), P_UpdateSpecials(), P_WriteSaveGameHeader(), PIT_ChangeSector(), T_MoveCeiling(), T_MoveFloor(), and T_PlatRaise().
thinkercap
thinker_t thinkercap
Definition at line 40 of file p_tick.c.
Referenced by A_BossDeath(), A_BrainAwake(), A_KeenDie(), A_PainShootSkull(), EV_Teleport(), P_AddThinker(), P_ArchiveSpecials(), P_ArchiveThinkers(), P_InitThinkers(), P_RunThinkers(), P_UnArchiveThinkers(), and R_PrecacheLevel().