Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/r_data.h File Reference
r_data.h File Reference
#include "r_defs.h"
#include "r_state.h"
Functions
byte * R_GetColumn (int tex, int col)
void R_InitData (void)
void R_PrecacheLevel (void)
int R_FlatNumForName (char *name)
int R_TextureNumForName (char *name)
int R_CheckTextureNumForName (char *name)
Function Documentation
R_CheckTextureNumForName()
int R_CheckTextureNumForName (char * name)
Definition at line 744 of file r_data.c.
 {
     texture_t *texture;
     int key;
     // "NoTexture" marker.
     if (name[0] == '-')
     return 0;
     key = W_LumpNameHash(name) % numtextures;
     texture=textures_hashtable[key];
     while (texture != NULL)
     {
     if (!strncasecmp (texture->name, name, 8) )
         return texture->index;
         texture = texture->next;
     }
     return -1;
 }
References texture_s::index, texture_s::name, texture_s::next, NULL, numtextures, strncasecmp, textures_hashtable, and W_LumpNameHash().
Referenced by P_InitPicAnims(), P_InitSwitchList(), and R_TextureNumForName().
R_FlatNumForName()
int R_FlatNumForName (char * name)
Definition at line 720 of file r_data.c.
 {
     int     i;
     char    namet[9];
     i = W_CheckNumForName (name);
     if (i == -1)
     {
     namet[8] = 0;
     memcpy (namet, name,8);
     I_Error ("R_FlatNumForName: %s not found",namet);
     }
     return i - firstflat;
 }
References firstflat, i, I_Error(), memcpy, and W_CheckNumForName().
Referenced by G_DoLoadLevel(), P_InitPicAnims(), and P_LoadSectors().
R_GetColumn()
byte* R_GetColumn (int tex, int col)
Definition at line 383 of file r_data.c.
 {
     int     lump;
     int     ofs;
     col &= texturewidthmask[tex];
     lump = texturecolumnlump[tex][col];
     ofs = texturecolumnofs[tex][col];
     if (lump > 0)
     return (byte *)W_CacheLumpNum(lump,PU_CACHE)+ofs;
     if (!texturecomposite[tex])
     R_GenerateComposite (tex);
     return texturecomposite[tex] + ofs;
 }
References PU_CACHE, R_GenerateComposite(), texturecolumnlump, texturecolumnofs, texturecomposite, texturewidthmask, and W_CacheLumpNum().
Referenced by R_DrawPlanes(), R_RenderMaskedSegRange(), and R_RenderSegLoop().
R_InitData()
void R_InitData (void)
Definition at line 703 of file r_data.c.
 {
     R_InitTextures ();
     printf (".");
     R_InitFlats ();
     printf (".");
     R_InitSpriteLumps ();
     printf (".");
     R_InitColormaps ();
 }
References printf, R_InitColormaps(), R_InitFlats(), R_InitSpriteLumps(), and R_InitTextures().
Referenced by R_Init().
R_PrecacheLevel()
void R_PrecacheLevel (void)
Definition at line 800 of file r_data.c.
 {
     char*       flatpresent;
     char*       texturepresent;
     char*       spritepresent;
     int         i;
     int         j;
     int         k;
     int         lump;
     texture_t*      texture;
     thinker_t*      th;
     spriteframe_t*  sf;
     if (demoplayback)
     return;
     // Precache flats.
     flatpresent = Z_Malloc(numflats, PU_STATIC, NULL);
     memset (flatpresent,0,numflats);
     for (i=0 ; i<numsectors ; i++)
     {
     flatpresent[sectors[i].floorpic] = 1;
     flatpresent[sectors[i].ceilingpic] = 1;
     }
     flatmemory = 0;
     for (i=0 ; i<numflats ; i++)
     {
     if (flatpresent[i])
     {
         lump = firstflat + i;
         flatmemory += lumpinfo[lump].size;
         W_CacheLumpNum(lump, PU_CACHE);
     }
     }
     Z_Free(flatpresent);
     // Precache textures.
     texturepresent = Z_Malloc(numtextures, PU_STATIC, NULL);
     memset (texturepresent,0, numtextures);
     for (i=0 ; i<numsides ; i++)
     {
     texturepresent[sides[i].toptexture] = 1;
     texturepresent[sides[i].midtexture] = 1;
     texturepresent[sides[i].bottomtexture] = 1;
     }
     // Sky texture is always present.
     // Note that F_SKY1 is the name used to
     //  indicate a sky floor/ceiling as a flat,
     //  while the sky texture is stored like
     //  a wall texture, with an episode dependend
     //  name.
     texturepresent[skytexture] = 1;
     texturememory = 0;
     for (i=0 ; i<numtextures ; i++)
     {
     if (!texturepresent[i])
         continue;
     texture = textures[i];
     for (j=0 ; j<texture->patchcount ; j++)
     {
         lump = texture->patches[j].patch;
         texturememory += lumpinfo[lump].size;
         W_CacheLumpNum(lump , PU_CACHE);
     }
     }
     Z_Free(texturepresent);
     // Precache sprites.
     spritepresent = Z_Malloc(numsprites, PU_STATIC, NULL);
     memset (spritepresent,0, numsprites);
     for (th = thinkercap.next ; th != &thinkercap ; th=th->next)
     {
     if (th->function.acp1 == (actionf_p1)P_MobjThinker)
         spritepresent[((mobj_t *)th)->sprite] = 1;
     }
     spritememory = 0;
     for (i=0 ; i<numsprites ; i++)
     {
     if (!spritepresent[i])
         continue;
     for (j=0 ; j<sprites[i].numframes ; j++)
     {
         sf = &sprites[i].spriteframes[j];
         for (k=0 ; k<8 ; k++)
         {
         lump = firstspritelump + sf->lump[k];
         spritememory += lumpinfo[lump].size;
         W_CacheLumpNum(lump , PU_CACHE);
         }
     }
     }
     Z_Free(spritepresent);
 }
References actionf_t::acp1, side_t::bottomtexture, sector_t::ceilingpic, demoplayback, firstflat, firstspritelump, flatmemory, sector_t::floorpic, thinker_s::function, i, j, k, spriteframe_t::lump, lumpinfo, memset, side_t::midtexture, thinker_s::next, NULL, numflats, spritedef_t::numframes, numsectors, numsides, numsprites, numtextures, P_MobjThinker(), texpatch_t::patch, texture_s::patchcount, texture_s::patches, PU_CACHE, PU_STATIC, sectors, sides, lumpinfo_s::size, skytexture, spritedef_t::spriteframes, spritememory, sprites, texturememory, textures, thinkercap, side_t::toptexture, W_CacheLumpNum(), Z_Free(), and Z_Malloc().
Referenced by P_SetupLevel().
R_TextureNumForName()
int R_TextureNumForName (char * name)
Definition at line 775 of file r_data.c.
 {
     int     i;
     i = R_CheckTextureNumForName (name);
     if (i==-1)
     {
     I_Error ("R_TextureNumForName: %s not found",
          name);
     }
     return i;
 }
References i, I_Error(), and R_CheckTextureNumForName().
Referenced by G_DoLoadLevel(), G_InitNew(), P_InitPicAnims(), P_InitSwitchList(), and P_LoadSideDefs().