Fennix Userspace: Userspace/musl/src/process/execvp.c File Reference
execvp.c File Reference
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <limits.h>
Functions
int __execvpe (const char *file, char *const argv[], char *const envp[])
int execvp (const char *file, char *const argv[])
weak_alias (__execvpe, execvpe)
Variables
char ** __environ
Function Documentation
__execvpe()
int __execvpe (const char * file, char *const argv[], char *const envp[])
Definition at line 9 of file execvp.c.
 {
     const char *p, *z, *path = getenv("PATH");
     size_t l, k;
     int seen_eacces = 0;
     errno = ENOENT;
     if (!*file) return -1;
     if (strchr(file, '/'))
         return execve(file, argv, envp);
     if (!path) path = "/usr/local/bin:/bin:/usr/bin";
     k = strnlen(file, NAME_MAX+1);
     if (k > NAME_MAX) {
         errno = ENAMETOOLONG;
         return -1;
     }
     l = strnlen(path, PATH_MAX-1)+1;
     for(p=path; ; p=z) {
         char b[l+k+1];
         z = __strchrnul(p, ':');
         if (z-p >= l) {
             if (!*z++) break;
             continue;
         }
         memcpy(b, p, z-p);
         b[z-p] = '/';
         memcpy(b+(z-p)+(z>p), file, k+1);
         execve(b, argv, envp);
         switch (errno) {
         case EACCES:
             seen_eacces = 1;
         case ENOENT:
         case ENOTDIR:
             break;
         default:
             return -1;
         }
         if (!*z++) break;
     }
     if (seen_eacces) errno = EACCES;
     return -1;
 }
References __strchrnul(), argv, EACCES, ENAMETOOLONG, ENOENT, ENOTDIR, errno, execve(), getenv, k, l, memcpy(), NAME_MAX, p, PATH_MAX, strchr(), and strnlen().
Referenced by execvp().
execvp()
int execvp (const char * file, char *const argv[])
Definition at line 55 of file execvp.c.
 {
     return __execvpe(file, argv, __environ);
 }
References __environ, __execvpe(), argv, ENOSYS, and errno.
Referenced by exec_kernel_doc(), execlp(), execvp_or_die(), reset_main(), and start_stop_daemon_main().
weak_alias()
weak_alias (__execvpe , execvpe)
Variable Documentation
__environ
char** __environ extern
Definition at line 3 of file __environ.c.
Referenced by execvp().