Fennix: Xalloc::XLockClass Class Reference
Xalloc::XLockClass Class Reference
Data Structures
struct SpinLockData
Public Member Functions
int Lock (const char *FunctionName)
int Unlock ()
Private Member Functions
void DeadLock (SpinLockData Lock)
Private Attributes
SpinLockData LockData
bool IsLocked = false
Detailed Description
Definition at line 5 of file Xalloc.cpp.
Data Structure Documentation
Xalloc::XLockClass::SpinLockData
struct Xalloc::XLockClass::SpinLockData
Definition at line 7 of file Xalloc.cpp.
Data Fields
const char * AttemptingToGet
size_t Count
const char * CurrentHolder
uintptr_t LockData
Member Function Documentation
DeadLock()
void Xalloc::XLockClass::DeadLock (SpinLockData Lock) inline private
Definition at line 15 of file Xalloc.cpp.
         {
             Xalloc_warn("Potential deadlock in lock '%s' held by '%s'! %ld locks in queue.", Lock.AttemptingToGet, Lock.CurrentHolder, Lock.Count);
         }
References Lock(), and Xalloc_warn.
Referenced by Lock().
Lock()
int Xalloc::XLockClass::Lock (const char * FunctionName) inline
Definition at line 25 of file Xalloc.cpp.
         {
             LockData.AttemptingToGet = FunctionName;
         Retry:
             unsigned int i = 0;
             while (__atomic_exchange_n(&IsLocked, true, __ATOMIC_ACQUIRE) && ++i < 0x10000000)
                 ;
             if (i >= 0x10000000)
             {
                 DeadLock(LockData);
                 goto Retry;
             }
             LockData.Count++;
             LockData.CurrentHolder = FunctionName;
             __sync_synchronize();
             return 0;
         }
References Xalloc::XLockClass::SpinLockData::AttemptingToGet, Xalloc::XLockClass::SpinLockData::Count, Xalloc::XLockClass::SpinLockData::CurrentHolder, DeadLock(), IsLocked, and LockData.
Referenced by Xalloc::AllocatorV1::Calloc(), DeadLock(), Xalloc::AllocatorV1::Realloc(), and Xalloc::XSmartLock::XSmartLock().
Unlock()
int Xalloc::XLockClass::Unlock () inline
Definition at line 43 of file Xalloc.cpp.
         {
             __sync_synchronize();
             __atomic_store_n(&IsLocked, false, __ATOMIC_RELEASE);
             LockData.Count--;
             IsLocked = false;
             return 0;
         }
References Xalloc::XLockClass::SpinLockData::Count, IsLocked, and LockData.
Referenced by Xalloc::AllocatorV1::Calloc(), Xalloc::AllocatorV1::Malloc(), Xalloc::AllocatorV1::Realloc(), and Xalloc::XSmartLock::~XSmartLock().
Field Documentation
IsLocked
bool Xalloc::XLockClass::IsLocked = false private
Definition at line 22 of file Xalloc.cpp.
Referenced by Lock(), and Unlock().
LockData
SpinLockData Xalloc::XLockClass::LockData private
Definition at line 21 of file Xalloc.cpp.
Referenced by Lock(), and Unlock().
The documentation for this class was generated from the following file:
Kernel/Core/Memory/HeapAllocators/Xalloc.cpp