Fennix: Userspace/apps/base/busybox/networking/libiproute/rtm_map.h File Reference
rtm_map.h File Reference
Functions
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN const char * rtnl_rtntype_n2a (int id) FAST_FUNC
int rtnl_rtntype_a2n (int *id, char *arg) FAST_FUNC
int get_rt_realms (uint32_t *realms, char *arg) FAST_FUNC
Function Documentation
get_rt_realms()
int get_rt_realms (uint32_t * realms, char * arg)
Definition at line 105 of file rtm_map.c.
 {
     uint32_t realm = 0;
     char *p = strchr(arg, '/');
     *realms = 0;
     if (p) {
         *p = 0;
         if (rtnl_rtrealm_a2n(realms, arg)) {
             *p = '/';
             return -1;
         }
         *realms <<= 16;
         *p = '/';
         arg = p+1;
     }
     if (*arg && rtnl_rtrealm_a2n(&realm, arg))
         return -1;
     *realms |= realm;
     return 0;
 }
References p, rtnl_rtrealm_a2n(), and strchr().
Referenced by iproute_modify(), and iprule_modify().
rtnl_rtntype_a2n()
int rtnl_rtntype_a2n (int * id, char * arg)
Definition at line 68 of file rtm_map.c.
 {
     const smalluint key = index_in_substrings(keywords, arg) + 1;
     char *end;
     unsigned long res;
     if (key == ARG_local)
         res = RTN_LOCAL;
     else if (key == ARG_nat)
         res = RTN_NAT;
     else if (key == ARG_broadcast || key == ARG_brd)
         res = RTN_BROADCAST;
     else if (key == ARG_anycast)
         res = RTN_ANYCAST;
     else if (key == ARG_multicast)
         res = RTN_MULTICAST;
     else if (key == ARG_prohibit)
         res = RTN_PROHIBIT;
     else if (key == ARG_unreachable)
         res = RTN_UNREACHABLE;
     else if (key == ARG_blackhole)
         res = RTN_BLACKHOLE;
     else if (key == ARG_xresolve)
         res = RTN_XRESOLVE;
     else if (key == ARG_unicast)
         res = RTN_UNICAST;
     else if (key == ARG_throw)
         res = RTN_THROW;
     else {
         res = strtoul(arg, &end, 0);
         if (end == arg || *end || res > 255)
             return -1;
     }
     *id = res;
     return 0;
 }
References ARG_anycast, ARG_blackhole, ARG_brd, ARG_broadcast, ARG_local, ARG_multicast, ARG_nat, ARG_prohibit, ARG_throw, ARG_unicast, ARG_unreachable, ARG_xresolve, end, index_in_substrings(), and strtoul().
Referenced by iproute_modify(), and iprule_modify().
rtnl_rtntype_n2a()
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN const char* rtnl_rtntype_n2a (int id)
Definition at line 36 of file rtm_map.c.
 {
     switch (id) {
     case RTN_UNSPEC:
         return "none";
     case RTN_UNICAST:
         return str_unicast;
     case RTN_LOCAL:
         return str_local;
     case RTN_BROADCAST:
         return str_broadcast;
     case RTN_ANYCAST:
         return str_anycast;
     case RTN_MULTICAST:
         return str_multicast;
     case RTN_BLACKHOLE:
         return str_blackhole;
     case RTN_UNREACHABLE:
         return str_unreachable;
     case RTN_PROHIBIT:
         return str_prohibit;
     case RTN_THROW:
         return str_throw;
     case RTN_NAT:
         return str_nat;
     case RTN_XRESOLVE:
         return str_xresolve;
     default:
         return itoa(id);
     }
 }
References itoa, str_anycast, str_blackhole, str_broadcast, str_local, str_multicast, str_nat, str_prohibit, str_throw, str_unicast, str_unreachable, and str_xresolve.
Referenced by print_route(), and print_rule().