Fennix: Userspace/musl/src/time/timegm.c File Reference
timegm.c File Reference
#include "time_impl.h"
#include <errno.h>
Macros
#define _GNU_SOURCE
Functions
time_t timegm (struct tm *tm)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file timegm.c.
Function Documentation
timegm()
time_t timegm (struct tm * tm)
Definition at line 5 of file timegm.c.
 {
     struct tm new;
     long long t = __tm_to_secs(tm);
     if (__secs_to_tm(t, &new) < 0) {
         errno = EOVERFLOW;
         return -1;
     }
     *tm = new;
     tm->tm_isdst = 0;
     tm->__tm_gmtoff = 0;
     tm->__tm_zone = __utc;
     return t;
 }
References __secs_to_tm(), tm::__tm_gmtoff, __tm_to_secs(), tm::__tm_zone, __utc, EOVERFLOW, errno, and tm::tm_isdst.
Referenced by __time32gm().