Fennix: Userspace/apps/base/busybox/procps/top.c File Reference
top.c File Reference
#include "libbb.h"
Data Structures
struct top_status_t
struct jiffy_counts_t
struct save_hist
struct globals
struct topmem_status_t
Macros
#define ESC "\033"
#define G_scroll_ofs 0
#define G (*ptr_to_globals)
#define top (G.top)
#define ntop (G.ntop)
#define sort_field (G.sort_field)
#define inverted (G.inverted)
#define smp_cpu_info (G.smp_cpu_info)
#define initial_settings (G.initial_settings)
#define sort_function (G.sort_function)
#define prev_hist (G.prev_hist)
#define prev_hist_count (G.prev_hist_count)
#define cur_jif (G.cur_jif)
#define prev_jif (G.prev_jif)
#define cpu_jif (G.cpu_jif)
#define cpu_prev_jif (G.cpu_prev_jif)
#define num_cpus (G.num_cpus)
#define total_pcpu (G.total_pcpu)
#define line_buf (G.line_buf)
#define INIT_G()
#define OPT_BATCH_MODE (option_mask32 & OPT_b)
#define display_cpus(scr_width, scrbuf, lines_rem) ((void)0)
#define UPSCALE 100
#define CALC_STAT(name, val) unsigned name = (val)
#define SHOW_STAT(name) name
#define FMT "%4u%%"
#define topmem ((topmem_status_t*)top)
Typedefs
typedef struct top_status_t top_status_t
typedef struct jiffy_counts_t jiffy_counts_t
typedef struct save_hist save_hist
typedef int(* cmp_funcp) (top_status_t *P, top_status_t *Q)
typedef unsigned long mem_t
typedef struct topmem_status_t topmem_status_t
Enumerations
enum { SORT_DEPTH = 3 }
enum { LINE_BUF_SIZE = 512 - 64 }
enum {
OPT_d = (1 << 0) , OPT_n = (1 << 1) , OPT_b = (1 << 2) , OPT_H = (1 << 3) ,
OPT_m = (1 << 4) , OPT_EOF = (1 << 5)
}
enum {
MI_MEMTOTAL , MI_MEMFREE , MI_MEMSHARED , MI_SHMEM ,
MI_BUFFERS , MI_CACHED , MI_SWAPTOTAL , MI_SWAPFREE ,
MI_DIRTY , MI_WRITEBACK , MI_ANONPAGES , MI_MAPPED ,
MI_SLAB , MI_MAX
}
enum { NUM_SORT_FIELD = 7 }
enum { TOP_MASK , TOPMEM_MASK , EXIT_MASK = 0 , NO_RESCAN_MASK = (unsigned)-1 }
Functions
static int mem_sort (top_status_t *P, top_status_t *Q)
static void parse_meminfo (unsigned long meminfo[MI_MAX])
static unsigned long display_header (int scr_width, int *lines_rem_p)
static NOINLINE void display_process_list (int lines_rem, int scr_width)
static void clearmems (void)
void display_topmem_process_list (int lines_rem, int scr_width)
int topmem_sort (char *a, char *b)
int top_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
top_status_t
struct top_status_t
Definition at line 122 of file top.c.
Data Fields
char comm[COMM_LEN]
unsigned pid
unsigned ppid
char state[4]
unsigned uid
unsigned long vsz
jiffy_counts_t
struct jiffy_counts_t
Definition at line 137 of file top.c.
Data Fields
unsigned long long busy
unsigned long long idle
unsigned long long iowait
unsigned long long irq
unsigned long long nic
unsigned long long softirq
unsigned long long steal
unsigned long long sys
unsigned long long total
unsigned long long usr
save_hist
struct save_hist
Definition at line 147 of file top.c.
Data Fields
pid_t pid
unsigned long ticks
topmem_status_t
struct topmem_status_t
Definition at line 783 of file top.c.
Data Fields
char comm[COMM_LEN]
mem_t dirty
mem_t dirty_sh
unsigned pid
mem_t rss
mem_t rss_sh
mem_t stack
mem_t vsz
mem_t vszrw
Macro Definition Documentation
CALC_STAT
#define CALC_STAT (name, val) unsigned name = (val)
cpu_jif
#define cpu_jif (G.cpu_jif)
Definition at line 211 of file top.c.
cpu_prev_jif
#define cpu_prev_jif (G.cpu_prev_jif)
Definition at line 212 of file top.c.
cur_jif
#define cur_jif (G.cur_jif)
Definition at line 209 of file top.c.
display_cpus
#define display_cpus (scr_width, scrbuf, lines_rem) ((void)0)
Definition at line 513 of file top.c.
ESC
#define ESC "\033"
Definition at line 120 of file top.c.
FMT
#define FMT "%4u%%"
G
#define G (*ptr_to_globals)
Definition at line 199 of file top.c.
G_scroll_ofs
#define G_scroll_ofs 0
Definition at line 176 of file top.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    BUILD_BUG_ON(LINE_BUF_SIZE <= 80); \
} while (0)
Definition at line 216 of file top.c.
initial_settings
#define initial_settings (G.initial_settings)
Definition at line 205 of file top.c.
inverted
#define inverted (G.inverted)
Definition at line 203 of file top.c.
line_buf
#define line_buf (G.line_buf)
Definition at line 215 of file top.c.
ntop
#define ntop (G.ntop)
Definition at line 201 of file top.c.
num_cpus
#define num_cpus (G.num_cpus)
Definition at line 213 of file top.c.
OPT_BATCH_MODE
#define OPT_BATCH_MODE (option_mask32 & OPT_b)
Definition at line 229 of file top.c.
prev_hist
#define prev_hist (G.prev_hist)
Definition at line 207 of file top.c.
prev_hist_count
#define prev_hist_count (G.prev_hist_count)
Definition at line 208 of file top.c.
prev_jif
#define prev_jif (G.prev_jif)
Definition at line 210 of file top.c.
SHOW_STAT
#define SHOW_STAT (name) name
smp_cpu_info
#define smp_cpu_info (G.smp_cpu_info)
Definition at line 204 of file top.c.
sort_field
#define sort_field (G.sort_field)
Definition at line 202 of file top.c.
sort_function
#define sort_function (G.sort_function)
Definition at line 206 of file top.c.
top
#define top (G.top)
Definition at line 200 of file top.c.
topmem
#define topmem ((topmem_status_t*)top)
Definition at line 798 of file top.c.
total_pcpu
#define total_pcpu (G.total_pcpu)
Definition at line 214 of file top.c.
UPSCALE
#define UPSCALE 100
Typedef Documentation
cmp_funcp
typedef int(* cmp_funcp) (top_status_t *P, top_status_t *Q)
Definition at line 152 of file top.c.
jiffy_counts_t
typedef struct jiffy_counts_t jiffy_counts_t
mem_t
typedef unsigned long mem_t
Definition at line 781 of file top.c.
save_hist
typedef struct save_hist save_hist
top_status_t
typedef struct top_status_t top_status_t
topmem_status_t
typedef struct topmem_status_t topmem_status_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SORT_DEPTH
Definition at line 155 of file top.c.
 { SORT_DEPTH = 3 };
anonymous enum
anonymous enum
Enumerator
LINE_BUF_SIZE
Definition at line 158 of file top.c.
 { LINE_BUF_SIZE = 512 - 64 };
anonymous enum
anonymous enum
Enumerator
OPT_d
OPT_n
OPT_b
OPT_H
OPT_m
OPT_EOF
Definition at line 221 of file top.c.
      {
     OPT_d = (1 << 0),
     OPT_n = (1 << 1),
     OPT_b = (1 << 2),
     OPT_H = (1 << 3),
     OPT_m = (1 << 4),
     OPT_EOF = (1 << 5), /* pseudo: "we saw EOF in stdin" */
 };
anonymous enum
anonymous enum
Enumerator
MI_MEMTOTAL
MI_MEMFREE
MI_MEMSHARED
MI_SHMEM
MI_BUFFERS
MI_CACHED
MI_SWAPTOTAL
MI_SWAPFREE
MI_DIRTY
MI_WRITEBACK
MI_ANONPAGES
MI_MAPPED
MI_SLAB
MI_MAX
Definition at line 516 of file top.c.
      {
     MI_MEMTOTAL,
     MI_MEMFREE,
     MI_MEMSHARED,
     MI_SHMEM,
     MI_BUFFERS,
     MI_CACHED,
     MI_SWAPTOTAL,
     MI_SWAPFREE,
     MI_DIRTY,
     MI_WRITEBACK,
     MI_ANONPAGES,
     MI_MAPPED,
     MI_SLAB,
     MI_MAX
 };
anonymous enum
anonymous enum
Enumerator
NUM_SORT_FIELD
Definition at line 796 of file top.c.
 { NUM_SORT_FIELD = 7 };
anonymous enum
anonymous enum
Enumerator
TOP_MASK
TOPMEM_MASK
EXIT_MASK
NO_RESCAN_MASK
Definition at line 915 of file top.c.
      {
     TOP_MASK = 0
         | PSSCAN_PID
         | PSSCAN_PPID
         | PSSCAN_VSZ
         | PSSCAN_STIME
         | PSSCAN_UTIME
         | PSSCAN_STATE
         | PSSCAN_COMM
         | PSSCAN_CPU
         | PSSCAN_UIDGID,
     TOPMEM_MASK = 0
         | PSSCAN_PID
         | PSSCAN_SMAPS
         | PSSCAN_COMM,
     EXIT_MASK = 0,
     NO_RESCAN_MASK = (unsigned)-1,
 };
Function Documentation
clearmems()
static void clearmems (void) static
Definition at line 756 of file top.c.
 {
     clear_username_cache();
     free(top);
     top = NULL;
 }
References clear_username_cache(), free, NULL, and top.
Referenced by top_main().
display_header()
static unsigned long display_header (int scr_width, int * lines_rem_p) static
Definition at line 567 of file top.c.
 {
     char scrbuf[100]; /* [80] was a bit too low on 8Gb ram box */
     char *buf;
     unsigned long meminfo[MI_MAX];
     parse_meminfo(meminfo);
     /* Output memory info */
     if (scr_width > (int)sizeof(scrbuf))
         scr_width = sizeof(scrbuf);
     snprintf(scrbuf, scr_width,
         "Mem: %luK used, %luK free, %luK shrd, %luK buff, %luK cached",
         meminfo[MI_MEMTOTAL] - meminfo[MI_MEMFREE],
         meminfo[MI_MEMFREE],
         meminfo[MI_MEMSHARED] + meminfo[MI_SHMEM],
         meminfo[MI_BUFFERS],
         meminfo[MI_CACHED]);
     /* Go to top & clear to the end of screen */
     printf(OPT_BATCH_MODE ? "%s\n" : ESC"[H" ESC"[J" "%s\n", scrbuf);
     (*lines_rem_p)--;
     /* Display CPU time split as percentage of total time.
      * This displays either a cumulative line or one line per CPU.
      */
     display_cpus(scr_width, scrbuf, lines_rem_p);
     /* Read load average as a string */
     buf = stpcpy(scrbuf, "Load average: ");
     open_read_close("loadavg", buf, sizeof(scrbuf) - sizeof("Load average: "));
     scrbuf[scr_width - 1] = '\0';
     strchrnul(buf, '\n')[0] = '\0';
     puts(scrbuf);
     (*lines_rem_p)--;
     return meminfo[MI_MEMTOTAL];
 }
References buf, display_cpus, ESC, MI_BUFFERS, MI_CACHED, MI_MAX, MI_MEMFREE, MI_MEMSHARED, MI_MEMTOTAL, MI_SHMEM, open_read_close(), OPT_BATCH_MODE, parse_meminfo(), printf, puts(), snprintf(), stpcpy(), and strchrnul().
Referenced by display_process_list().
display_process_list()
static NOINLINE void display_process_list (int lines_rem, int scr_width) static
Definition at line 605 of file top.c.
 {
     enum {
         BITS_PER_INT = sizeof(int) * 8
     };
     top_status_t *s;
     unsigned long total_memory = display_header(scr_width, &lines_rem); /* or use total_vsz? */
     /* xxx_shift and xxx_scale variables allow us to replace
      * expensive divides with multiply and shift */
     unsigned pmem_shift, pmem_scale, pmem_half;
 #if ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE
     unsigned tmp_unsigned;
     unsigned pcpu_shift, pcpu_scale, pcpu_half;
     unsigned busy_jifs;
 #endif
     /* what info of the processes is shown */
     printf(OPT_BATCH_MODE ? "%.*s" : ESC"[7m" "%.*s" ESC"[m", scr_width,
         "  PID  PPID USER     STAT   VSZ %VSZ"
         IF_FEATURE_TOP_SMP_PROCESS(" CPU")
         IF_FEATURE_TOP_CPU_USAGE_PERCENTAGE(" %CPU")
         " COMMAND");
     lines_rem--;
 #if ENABLE_FEATURE_TOP_DECIMALS
 # define UPSCALE 1000
 # define CALC_STAT(name, val) div_t name = div((val), 10)
 # define SHOW_STAT(name) name.quot, '0'+name.rem
 # define FMT "%3u.%c"
 #else
 # define UPSCALE 100
 # define CALC_STAT(name, val) unsigned name = (val)
 # define SHOW_STAT(name) name
 # define FMT "%4u%%"
 #endif
     /*
      * %VSZ = s->vsz/MemTotal
      */
     pmem_shift = BITS_PER_INT-11;
     pmem_scale = UPSCALE*(1U<<(BITS_PER_INT-11)) / total_memory;
     /* s->vsz is in kb. we want (s->vsz * pmem_scale) to never overflow */
     while (pmem_scale >= 512) {
         pmem_scale /= 4;
         pmem_shift -= 2;
     }
     pmem_half = (1U << pmem_shift) / (ENABLE_FEATURE_TOP_DECIMALS ? 20 : 2);
 #if ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE
     busy_jifs = cur_jif.busy - prev_jif.busy;
     /* This happens if there were lots of short-lived processes
      * between two top updates (e.g. compilation) */
     if (total_pcpu < busy_jifs) total_pcpu = busy_jifs;
     /*
      * CPU% = s->pcpu/sum(s->pcpu) * busy_cpu_ticks/total_cpu_ticks
      * (pcpu is delta of sys+user time between samples)
      */
     /* (cur_jif.xxx - prev_jif.xxx) and s->pcpu are
      * in 0..~64000 range (HZ*update_interval).
      * we assume that unsigned is at least 32-bit.
      */
     pcpu_shift = 6;
     pcpu_scale = UPSCALE*64 * (uint16_t)busy_jifs;
     if (pcpu_scale == 0)
         pcpu_scale = 1;
     while (pcpu_scale < (1U << (BITS_PER_INT-2))) {
         pcpu_scale *= 4;
         pcpu_shift += 2;
     }
     tmp_unsigned = (uint16_t)(cur_jif.total - prev_jif.total) * total_pcpu;
     if (tmp_unsigned != 0)
         pcpu_scale /= tmp_unsigned;
     /* we want (s->pcpu * pcpu_scale) to never overflow */
     while (pcpu_scale >= 1024) {
         pcpu_scale /= 4;
         pcpu_shift -= 2;
     }
     pcpu_half = (1U << pcpu_shift) / (ENABLE_FEATURE_TOP_DECIMALS ? 20 : 2);
     /* printf(" pmem_scale=%u pcpu_scale=%u ", pmem_scale, pcpu_scale); */
 #endif
     /* Ok, all preliminary data is ready, go through the list */
     scr_width += 2; /* account for leading '\n' and trailing NUL */
     if (lines_rem > ntop - G_scroll_ofs)
         lines_rem = ntop - G_scroll_ofs;
     s = top + G_scroll_ofs;
     while (--lines_rem >= 0) {
         int n;
         char *ppu;
         char ppubuf[sizeof(int)*3 * 2 + 12];
         char vsz_str_buf[8];
         unsigned col;
         CALC_STAT(pmem, (s->vsz*pmem_scale + pmem_half) >> pmem_shift);
 #if ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE
         CALC_STAT(pcpu, (s->pcpu*pcpu_scale + pcpu_half) >> pcpu_shift);
 #endif
         smart_ulltoa5(s->vsz, vsz_str_buf, " mgtpezy");
         /* PID PPID USER STAT VSZ %VSZ [%CPU] COMMAND */
         n = sprintf(ppubuf, "%5u %5u %-8.8s", s->pid, s->ppid, get_cached_username(s->uid));
         ppu = ppubuf;
         if (n != 6+6+8) {
             /* Format PID PPID USER part into 6+6+8 chars:
              * shrink PID/PPID if possible, then truncate USER
              */
             char *p, *pp;
             if (*ppu == ' ') {
                 do {
                     ppu++, n--;
                     if (n == 6+6+8)
                         goto shortened;
                 } while (*ppu == ' ');
             }
             pp = p = skip_non_whitespace(ppu) + 1;
             if (*p == ' ') {
                 do
                     p++, n--;
                 while (n != 6+6+8 && *p == ' ');
                 overlapping_strcpy(pp, p); /* shrink PPID */
             }
             ppu[6+6+8] = '\0'; /* truncate USER */
         }
  shortened:
         col = snprintf(line_buf, scr_width,
                 "\n" "%s %s  %.5s" FMT
                 IF_FEATURE_TOP_SMP_PROCESS(" %3d")
                 IF_FEATURE_TOP_CPU_USAGE_PERCENTAGE(FMT)
                 " ",
                 ppu,
                 s->state, vsz_str_buf,
                 SHOW_STAT(pmem)
                 IF_FEATURE_TOP_SMP_PROCESS(, s->last_seen_on_cpu)
                 IF_FEATURE_TOP_CPU_USAGE_PERCENTAGE(, SHOW_STAT(pcpu))
         );
         if ((int)(scr_width - col) > 1)
             read_cmdline(line_buf + col, scr_width - col, s->pid, s->comm);
         fputs_stdout(line_buf);
         /* printf(" %d/%d %lld/%lld", s->pcpu, total_pcpu,
             cur_jif.busy - prev_jif.busy, cur_jif.total - prev_jif.total); */
         s++;
     }
     /* printf(" %d", hist_iterations); */
     bb_putchar(OPT_BATCH_MODE ? '\n' : '\r');
     fflush_all();
 }
References bb_putchar(), CALC_STAT, cur_jif, display_header(), ESC, fflush_all(), FMT, fputs_stdout(), G_scroll_ofs, get_cached_username(), line_buf, n, ntop, OPT_BATCH_MODE, overlapping_strcpy(), p, prev_jif, printf, read_cmdline(), s, SHOW_STAT, skip_non_whitespace(), smart_ulltoa5(), snprintf(), sprintf(), top, total_pcpu, and UPSCALE.
Referenced by top_main().
display_topmem_process_list()
void display_topmem_process_list (int lines_rem, int scr_width)
Referenced by top_main().
mem_sort()
static int mem_sort (top_status_t * P, top_status_t * Q) static
Definition at line 241 of file top.c.
 {
     /* We want to avoid unsigned->signed and truncation errors */
     if (Q->vsz < P->vsz) return -1;
     return Q->vsz != P->vsz; /* 0 if ==, 1 if > */
 }
References P, and top_status_t::vsz.
Referenced by top_main().
parse_meminfo()
static void parse_meminfo (unsigned long meminfo[MI_MAX]) static
Definition at line 533 of file top.c.
 {
     static const char fields[] ALIGN1 =
         "MemTotal\0"
         "MemFree\0"
         "MemShared\0"
         "Shmem\0"
         "Buffers\0"
         "Cached\0"
         "SwapTotal\0"
         "SwapFree\0"
         "Dirty\0"
         "Writeback\0"
         "AnonPages\0"
         "Mapped\0"
         "Slab\0";
     char buf[60]; /* actual lines we expect are ~30 chars or less */
     FILE *f;
     int i;
     memset(meminfo, 0, sizeof(meminfo[0]) * MI_MAX);
     f = xfopen_for_read("meminfo");
     while (fgets(buf, sizeof(buf), f) != NULL) {
         char *c = strchr(buf, ':');
         if (!c)
             continue;
         *c = '\0';
         i = index_in_strings(fields, buf);
         if (i >= 0)
             meminfo[i] = strtoul(c+1, NULL, 10);
     }
     fclose(f);
 }
References ALIGN1, buf, c, f, fclose(), fgets, i, index_in_strings(), memset, MI_MAX, NULL, strchr(), strtoul(), and xfopen_for_read().
Referenced by display_header().
top_main()
int top_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1132 of file top.c.
 {
     duration_t interval;
     int iterations;
     unsigned col;
     char *str_interval, *str_iterations;
     unsigned scan_mask = TOP_MASK;
     INIT_G();
     interval = 5; /* default update interval is 5 seconds */
     iterations = 0; /* infinite */
 #if ENABLE_FEATURE_TOP_SMP_CPU
     /*num_cpus = 0;*/
     /*smp_cpu_info = 0;*/  /* to start with show aggregate */
     cpu_jif = &cur_jif;
     cpu_prev_jif = &prev_jif;
 #endif
     /* all args are options; -n NUM */
     make_all_argv_opts(argv); /* options can be specified w/o dash */
     col = getopt32(argv, "d:n:bHm", &str_interval, &str_iterations);
     /* NB: -m and -H are accepted even if not configured */
 #if ENABLE_FEATURE_TOPMEM
     if (col & OPT_m) /* -m (busybox specific) */
         scan_mask = TOPMEM_MASK;
 #endif
     if (col & OPT_d) {
         /* work around for "-d 1" -> "-d -1" done by make_all_argv_opts() */
         if (str_interval[0] == '-')
             str_interval++;
         interval = parse_duration_str(str_interval);
         /* Need to limit it to not overflow poll timeout */
         if (interval > INT_MAX / 1000)
             interval = INT_MAX / 1000;
     }
     if (col & OPT_n) {
         if (str_iterations[0] == '-')
             str_iterations++;
         iterations = xatou(str_iterations);
     }
 #if ENABLE_FEATURE_SHOW_THREADS
     if (col & OPT_H) {
         scan_mask |= PSSCAN_TASKS;
     }
 #endif
     /* change to /proc */
     xchdir("/proc");
 #if ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE
     sort_function[0] = pcpu_sort;
     sort_function[1] = mem_sort;
     sort_function[2] = time_sort;
 #else
     sort_function[0] = mem_sort;
 #endif
     if (OPT_BATCH_MODE) {
         option_mask32 |= OPT_EOF;
     }
 #if ENABLE_FEATURE_TOP_INTERACTIVE
     else {
         /* Turn on unbuffered input; turn off echoing, ^C ^Z etc */
         set_termios_to_raw(STDIN_FILENO, &initial_settings, TERMIOS_CLEAR_ISIG);
         die_func = reset_term;
     }
     bb_signals(BB_FATAL_SIGS, sig_catcher);
     /* Eat initial input, if any */
     scan_mask = handle_input(scan_mask, 0);
 #endif
     while (scan_mask != EXIT_MASK) {
         IF_FEATURE_TOP_INTERACTIVE(unsigned new_mask;)
         procps_status_t *p = NULL;
         if (OPT_BATCH_MODE) {
             G.lines = INT_MAX;
             col = LINE_BUF_SIZE - 2; /* +2 bytes for '\n', NUL */
         } else {
             G.lines = 24; /* default */
             col = 79;
             /* We output to stdout, we need size of stdout (not stdin)! */
             get_terminal_width_height(STDOUT_FILENO, &col, &G.lines);
             if (G.lines < 5 || col < 10) {
                 sleep_for_duration(interval);
                 continue;
             }
             if (col > LINE_BUF_SIZE - 2)
                 col = LINE_BUF_SIZE - 2;
         }
         /* read process IDs & status for all the processes */
         ntop = 0;
         while ((p = procps_scan(p, scan_mask)) != NULL) {
             int n;
             IF_FEATURE_TOPMEM(if (scan_mask != TOPMEM_MASK)) {
                 n = ntop;
                 top = xrealloc_vector(top, 6, ntop++);
                 top[n].pid = p->pid;
                 top[n].ppid = p->ppid;
                 top[n].vsz = p->vsz;
 #if ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE
                 top[n].ticks = p->stime + p->utime;
 #endif
                 top[n].uid = p->uid;
                 strcpy(top[n].state, p->state);
                 strcpy(top[n].comm, p->comm);
 #if ENABLE_FEATURE_TOP_SMP_PROCESS
                 top[n].last_seen_on_cpu = p->last_seen_on_cpu;
 #endif
             }
 #if ENABLE_FEATURE_TOPMEM
             else { /* TOPMEM */
                 if (!(p->smaps.mapped_ro | p->smaps.mapped_rw))
                     continue; /* kernel threads are ignored */
                 n = ntop;
                 /* No bug here - top and topmem are the same */
                 top = xrealloc_vector(topmem, 6, ntop++);
                 strcpy(topmem[n].comm, p->comm);
                 topmem[n].pid      = p->pid;
                 topmem[n].vsz      = p->smaps.mapped_rw + p->smaps.mapped_ro;
                 topmem[n].vszrw    = p->smaps.mapped_rw;
                 topmem[n].rss_sh   = p->smaps.shared_clean + p->smaps.shared_dirty;
                 topmem[n].rss      = p->smaps.private_clean + p->smaps.private_dirty + topmem[n].rss_sh;
                 topmem[n].dirty    = p->smaps.private_dirty + p->smaps.shared_dirty;
                 topmem[n].dirty_sh = p->smaps.shared_dirty;
                 topmem[n].stack    = p->smaps.stack;
             }
 #endif
         } /* end of "while we read /proc" */
         if (ntop == 0) {
             bb_simple_error_msg("no process info in /proc");
             break;
         }
         IF_FEATURE_TOPMEM(if (scan_mask != TOPMEM_MASK)) {
 #if ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE
             if (!prev_hist_count) {
                 do_stats();
                 usleep(100000);
                 clearmems();
                 continue;
             }
             do_stats();
             /* TODO: we don't need to sort all 10000 processes, we need to find top 24! */
             qsort(top, ntop, sizeof(top_status_t), (void*)mult_lvl_cmp);
 #else
             qsort(top, ntop, sizeof(top_status_t), (void*)(sort_function[0]));
 #endif
         }
 #if ENABLE_FEATURE_TOPMEM
         else { /* TOPMEM */
             qsort(topmem, ntop, sizeof(topmem_status_t), (void*)topmem_sort);
         }
 #endif
  IF_FEATURE_TOP_INTERACTIVE(display:)
         IF_FEATURE_TOPMEM(if (scan_mask != TOPMEM_MASK)) {
             display_process_list(G.lines, col);
         }
 #if ENABLE_FEATURE_TOPMEM
         else { /* TOPMEM */
             display_topmem_process_list(G.lines, col);
         }
 #endif
         if (iterations >= 0 && !--iterations)
             break;
 #if !ENABLE_FEATURE_TOP_INTERACTIVE
         clearmems();
         sleep_for_duration(interval);
 #else
         new_mask = handle_input(scan_mask, interval);
         if (new_mask == NO_RESCAN_MASK)
             goto display;
         scan_mask = new_mask;
         clearmems();
 #endif
     } /* end of "while (not Q)" */
     bb_putchar('\n');
 #if ENABLE_FEATURE_TOP_INTERACTIVE
     reset_term();
 #endif
     if (ENABLE_FEATURE_CLEAN_UP) {
         clearmems();
 #if ENABLE_FEATURE_TOP_CPU_USAGE_PERCENTAGE
         free(prev_hist);
 #endif
     }
     return EXIT_SUCCESS;
 }
References argv, BB_FATAL_SIGS, bb_putchar(), bb_signals(), bb_simple_error_msg(), clearmems(), cpu_jif, cpu_prev_jif, cur_jif, die_func, display(), display_process_list(), display_topmem_process_list(), EXIT_MASK, EXIT_SUCCESS, free, G, get_terminal_width_height(), getopt32(), INIT_G, initial_settings, INT_MAX, LINE_BUF_SIZE, make_all_argv_opts(), mem_sort(), n, NO_RESCAN_MASK, ntop, NULL, OPT_BATCH_MODE, OPT_d, OPT_EOF, OPT_H, OPT_m, OPT_n, option_mask32, p, parse_duration_str(), prev_hist, prev_hist_count, prev_jif, procps_scan(), PSSCAN_TASKS, qsort(), set_termios_to_raw(), sig_catcher(), sleep_for_duration, sort_function, state, STDIN_FILENO, STDOUT_FILENO, strcpy, TERMIOS_CLEAR_ISIG, top, TOP_MASK, topmem, TOPMEM_MASK, topmem_sort(), usleep(), xatou(), xchdir(), and xrealloc_vector.
topmem_sort()
int topmem_sort (char * a, char * b)
Referenced by top_main().