Fennix Userspace: Userspace/apps/base/busybox/coreutils/test.c File Reference
test.c File Reference
#include "libbb.h"
#include <regex.h>
#include <fnmatch.h>
Data Structures
struct operator_t
struct test_statics
Macros
#define TEST_DEBUG 0
#define BASH_TEST2 0
#define is_int_op(a) (((unsigned char)((a) - INTEQ)) <= 5)
#define is_str_op(a) (((unsigned char)((a) - STREZ)) <= 5)
#define is_file_op(a) (((unsigned char)((a) - FILNT)) <= 2)
#define is_file_access(a) (((unsigned char)((a) - FILRD)) <= 2)
#define is_file_type(a) (((unsigned char)((a) - FILREG)) <= 5)
#define is_file_bit(a) (((unsigned char)((a) - FILSUID)) <= 2)
#define nest_msg(...) ((void)0)
#define unnest_msg(...) ((void)0)
#define dbg_msg(...) ((void)0)
#define unnest_msg_and_return(expr, ...) return expr
#define S (*test_ptr_to_statics)
#define args (S.args)
#define last_operator (S.last_operator)
#define group_array (S.group_array)
#define ngroups (S.ngroups)
#define bash_test2 (S.bash_test2)
#define leaving (S.leaving)
#define INIT_S()
#define DEINIT_S()
Typedefs
typedef int number_t
Enumerations
enum token {
EOI , FILRD , FILWR , FILEX ,
FILEXIST , FILREG , FILDIR , FILCDEV ,
FILBDEV , FILFIFO , FILSOCK , FILSYM ,
FILGZ , FILTT , FILSUID , FILSGID ,
FILSTCK , FILNT , FILOT , FILEQ ,
FILUID , FILGID , STREZ , STRNZ ,
STREQ , STRNE , STRLT , STRGT ,
INTEQ , INTNE , INTGE , INTGT ,
INTLE , INTLT , UNOT , BAND ,
BOR , LPAREN , RPAREN , OPERAND
}
enum {
UNOP , BINOP , BUNOP , BBINOP ,
PAREN
}
Functions
static number_t primary (enum token n)
static void syntax (const char *op, const char *msg) NORETURN
static number_t getn (const char *s)
static enum token check_operator (const char *s)
static int binop (void)
static void initialize_group_array (void)
static int is_a_group_member (gid_t gid)
static int test_eaccess (struct stat *st, int mode)
static int filstat (char *nm, enum token mode)
static number_t nexpr (enum token n)
static number_t aexpr (enum token n)
static number_t oexpr (enum token n)
int test_main (int argc, char **argv)
Variables
static const struct operator_t ops_table[] ALIGN2
static const char ops_texts[] ALIGN1
struct test_statics *BB_GLOBAL_CONST test_ptr_to_statics
Data Structure Documentation
operator_t
struct operator_t
Definition at line 305 of file test.c.
Data Fields
unsigned char op_num
unsigned char op_type
test_statics
struct test_statics
Definition at line 424 of file test.c.
Data Fields
char ** args
gid_t * group_array
const struct operator_t* last_operator
jmp_buf leaving
int ngroups
Macro Definition Documentation
args
#define args (S.args)
Definition at line 441 of file test.c.
BASH_TEST2
#define BASH_TEST2 0
Definition at line 156 of file test.c.
bash_test2
#define bash_test2 (S.bash_test2)
Definition at line 445 of file test.c.
dbg_msg
#define dbg_msg (...) ((void)0)
Definition at line 293 of file test.c.
DEINIT_S
#define DEINIT_S ()
Value:
    do { \
    free(group_array); \
    free(test_ptr_to_statics); \
} while (0)
Definition at line 451 of file test.c.
group_array
#define group_array (S.group_array)
Definition at line 443 of file test.c.
INIT_S
#define INIT_S ()
Value:
    do { \
    XZALLOC_CONST_PTR(&test_ptr_to_statics, sizeof(S)); \
} while (0)
Definition at line 448 of file test.c.
is_file_access
#define is_file_access (a) (((unsigned char)((a) - FILRD)) <= 2)
Definition at line 218 of file test.c.
is_file_bit
#define is_file_bit (a) (((unsigned char)((a) - FILSUID)) <= 2)
Definition at line 220 of file test.c.
is_file_op
#define is_file_op (a) (((unsigned char)((a) - FILNT)) <= 2)
Definition at line 217 of file test.c.
is_file_type
#define is_file_type (a) (((unsigned char)((a) - FILREG)) <= 5)
Definition at line 219 of file test.c.
is_int_op
#define is_int_op (a) (((unsigned char)((a) - INTEQ)) <= 5)
Definition at line 215 of file test.c.
is_str_op
#define is_str_op (a) (((unsigned char)((a) - STREZ)) <= 5)
Definition at line 216 of file test.c.
last_operator
#define last_operator (S.last_operator)
Definition at line 442 of file test.c.
leaving
#define leaving (S.leaving)
Definition at line 446 of file test.c.
nest_msg
#define nest_msg (...) ((void)0)
Definition at line 291 of file test.c.
ngroups
#define ngroups (S.ngroups)
Definition at line 444 of file test.c.
S
#define S (*test_ptr_to_statics)
Definition at line 440 of file test.c.
TEST_DEBUG
#define TEST_DEBUG 0
Definition at line 149 of file test.c.
unnest_msg
#define unnest_msg (...) ((void)0)
Definition at line 292 of file test.c.
unnest_msg_and_return
#define unnest_msg_and_return (expr, ...) return expr
Definition at line 294 of file test.c.
Typedef Documentation
number_t
typedef int number_t
Definition at line 419 of file test.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
UNOP
BINOP
BUNOP
BBINOP
PAREN
Definition at line 297 of file test.c.
      {
     UNOP,
     BINOP,
     BUNOP,
     BBINOP,
     PAREN
 };
token
enum token
Enumerator
EOI
FILRD
FILWR
FILEX
FILEXIST
FILREG
FILDIR
FILCDEV
FILBDEV
FILFIFO
FILSOCK
FILSYM
FILGZ
FILTT
FILSUID
FILSGID
FILSTCK
FILNT
FILOT
FILEQ
FILUID
FILGID
STREZ
STRNZ
STREQ
STRNE
STRLT
STRGT
INTEQ
INTNE
INTGE
INTGT
INTLE
INTLT
UNOT
BAND
BOR
LPAREN
RPAREN
OPERAND
Definition at line 159 of file test.c.
            {
     EOI,
     FILRD, /* file access */
     FILWR,
     FILEX,
     FILEXIST,
     FILREG, /* file type */
     FILDIR,
     FILCDEV,
     FILBDEV,
     FILFIFO,
     FILSOCK,
     FILSYM,
     FILGZ,
     FILTT,
     FILSUID, /* file bit */
     FILSGID,
     FILSTCK,
     FILNT, /* file ops */
     FILOT,
     FILEQ,
     FILUID,
     FILGID,
     STREZ, /* str ops */
     STRNZ,
     STREQ,
     STRNE,
     STRLT,
     STRGT,
 #if BASH_TEST2
     REGEX,
 #endif
     INTEQ, /* int ops */
     INTNE,
     INTGE,
     INTGT,
     INTLE,
     INTLT,
     UNOT,
     BAND,
     BOR,
     LPAREN,
     RPAREN,
     OPERAND
 };
Function Documentation
aexpr()
static number_t aexpr (enum token n) static
Definition at line 796 of file test.c.
 {
     number_t res;
     nest_msg(">aexpr(%s)\n", TOKSTR[n]);
     res = nexpr(n);
     dbg_msg("aexpr: nexpr:%lld, next args:%s(%p)\n", res, args[1], &args[1]);
     if (check_operator(*++args) == BAND) {
         dbg_msg("aexpr: arg is AND, next args:%s(%p)\n", args[1], &args[1]);
         res = aexpr(check_operator(*++args)) && res;
         unnest_msg("<aexpr:%lld\n", res);
         return res;
     }
     args--;
     unnest_msg("<aexpr:%lld, args:%s(%p)\n", res, args[0], &args[0]);
     return res;
 }
References BAND, check_operator(), dbg_msg, n, nest_msg, nexpr(), and unnest_msg.
Referenced by oexpr().
binop()
static int binop (void) static
Definition at line 557 of file test.c.
 {
     const char *opnd1, *opnd2;
     const struct operator_t *op;
     number_t val1, val2;
     opnd1 = *args;
     check_operator(*++args);
     op = last_operator;
     opnd2 = *++args;
     if (opnd2 == NULL)
         syntax(args[-1], "argument expected");
     if (is_int_op(op->op_num)) {
         val1 = getn(opnd1);
         val2 = getn(opnd2);
         if (op->op_num == INTEQ)
             return val1 == val2;
         if (op->op_num == INTNE)
             return val1 != val2;
         if (op->op_num == INTGE)
             return val1 >= val2;
         if (op->op_num == INTGT)
             return val1 >  val2;
         if (op->op_num == INTLE)
             return val1 <= val2;
         /*if (op->op_num == INTLT)*/
         return val1 <  val2;
     }
 #if BASH_TEST2
     if (bash_test2) {
         if (op->op_num == STREQ) {
             val1 = fnmatch(opnd2, opnd1, 0);
             return val1 == 0;
         }
         if (op->op_num == STRNE) {
             val1 = fnmatch(opnd2, opnd1, 0);
             return val1 != 0;
         }
         if (op->op_num == REGEX) {
             regex_t re_buffer;
             memset(&re_buffer, 0, sizeof(re_buffer));
             if (regcomp(&re_buffer, opnd2, REG_EXTENDED)) { // REG_NEWLINE?
                 /* Bad regex */
                 longjmp(leaving, 2); /* [[ a =~ * ]]; echo $? - prints 2 (silently, no error msg) */
             }
             val1 = regexec(&re_buffer, opnd1, 0, NULL, 0);
             regfree(&re_buffer);
             return val1 == 0;
         }
     }
 #endif
     if (is_str_op(op->op_num)) {
         val1 = strcmp(opnd1, opnd2);
         if (op->op_num == STREQ)
             return val1 == 0;
         if (op->op_num == STRNE)
             return val1 != 0;
         if (op->op_num == STRLT)
             return val1 < 0;
         /*if (op->op_num == STRGT)*/
         return val1 > 0;
     }
     /* We are sure that these three are by now the only binops we didn't check
      * yet, so we do not check if the class is correct:
      */
 /*  if (is_file_op(op->op_num)) */
     {
         struct stat b1, b2;
         if (stat(opnd1, &b1) || stat(opnd2, &b2))
             return 0; /* false, since at least one stat failed */
         if (op->op_num == FILNT)
             return b1.st_mtime > b2.st_mtime;
         if (op->op_num == FILOT)
             return b1.st_mtime < b2.st_mtime;
         /*if (op->op_num == FILEQ)*/
         return b1.st_dev == b2.st_dev && b1.st_ino == b2.st_ino;
     }
     /*return 1; - NOTREACHED */
 }
References args, bash_test2, check_operator(), FILNT, FILOT, fnmatch(), getn(), INTEQ, INTGE, INTGT, INTLE, INTNE, is_int_op, is_str_op, last_operator, leaving, longjmp(), memset(), NULL, re_buffer, REG_EXTENDED, regcomp(), regexec, regfree(), stat::st_dev, stat::st_ino, stat(), strcmp, STREQ, STRLT, STRNE, and syntax().
Referenced by primary(), and test_main().
check_operator()
static enum token check_operator (const char * s) static
Definition at line 471 of file test.c.
 {
     static const struct operator_t no_op = {
         .op_num = -1,
         .op_type = -1
     };
     int n;
     last_operator = &no_op;
     if (s == NULL)
         return EOI;
     n = index_in_strings(ops_texts, s);
     if (n < 0)
         return OPERAND;
 #if BASH_TEST2
     if (ops_table[n].op_num == REGEX && !bash_test2) {
         /* =~ is only for [[ ]] */
         return OPERAND;
     }
     if (ops_table[n].op_num == BAND || ops_table[n].op_num == BOR) {
         /* [ ]   accepts -a and -o but not && and || */
         /* [[ ]] accepts && and || but not -a and -o */
         if (bash_test2 == (s[0] == '-'))
             return OPERAND;
     }
 #endif
     last_operator = &ops_table[n];
     return ops_table[n].op_num;
 }
References errno, p, s, skip_whitespace(), strtol(), strtoll(), and syntax().
Referenced by aexpr(), binop(), nexpr(), oexpr(), primary(), and test_main().
filstat()
static int filstat (char * nm, enum token mode) static
Definition at line 699 of file test.c.
 {
     struct stat s;
     unsigned i = i; /* gcc 3.x thinks it can be used uninitialized */
     if (mode == FILSYM) {
 #ifdef S_IFLNK
         if (lstat(nm, &s) == 0) {
             i = S_IFLNK;
             goto filetype;
         }
 #endif
         return 0;
     }
     if (stat(nm, &s) != 0)
         return 0;
     if (mode == FILEXIST)
         return 1;
     if (is_file_access(mode)) {
         if (mode == FILRD)
             i = R_OK;
         if (mode == FILWR)
             i = W_OK;
         if (mode == FILEX)
             i = X_OK;
         return test_eaccess(&s, i) == 0;
     }
     if (is_file_type(mode)) {
         if (mode == FILREG)
             i = S_IFREG;
         if (mode == FILDIR)
             i = S_IFDIR;
         if (mode == FILCDEV)
             i = S_IFCHR;
         if (mode == FILBDEV)
             i = S_IFBLK;
         if (mode == FILFIFO) {
 #ifdef S_IFIFO
             i = S_IFIFO;
 #else
             return 0;
 #endif
         }
         if (mode == FILSOCK) {
 #ifdef S_IFSOCK
             i = S_IFSOCK;
 #else
             return 0;
 #endif
         }
  filetype:
         return ((s.st_mode & S_IFMT) == i);
     }
     if (is_file_bit(mode)) {
         if (mode == FILSUID)
             i = S_ISUID;
         if (mode == FILSGID)
             i = S_ISGID;
         if (mode == FILSTCK)
             i = S_ISVTX;
         return ((s.st_mode & i) != 0);
     }
     if (mode == FILGZ)
         return s.st_size > 0L;
     if (mode == FILUID)
         return s.st_uid == geteuid();
     if (mode == FILGID)
         return s.st_gid == getegid();
     return 1; /* NOTREACHED */
 }
References FILBDEV, FILCDEV, FILDIR, FILEX, FILEXIST, FILFIFO, FILGID, FILGZ, FILRD, FILREG, FILSGID, FILSOCK, FILSTCK, FILSUID, FILSYM, FILUID, FILWR, getegid, geteuid, i, is_file_access, is_file_bit, is_file_type, L, lstat, R_OK, s, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO, S_IFLNK, S_IFMT, S_IFREG, S_IFSOCK, S_ISGID, S_ISUID, S_ISVTX, stat(), test_eaccess(), W_OK, and X_OK.
Referenced by primary().
getn()
static number_t getn (const char * s) static
Definition at line 471 of file test.c.
 {
     char *p;
 #if ENABLE_FEATURE_TEST_64
     long long r;
 #else
     long r;
 #endif
     errno = 0;
 #if ENABLE_FEATURE_TEST_64
     r = strtoll(s, &p, 10);
 #else
     r = strtol(s, &p, 10);
 #endif
     if (errno != 0)
         syntax(s, "out of range");
     if (p == s || *(skip_whitespace(p)) != '\0')
         syntax(s, "bad number");
     return r;
 }
Referenced by binop(), and primary().
initialize_group_array()
static void initialize_group_array (void) static
Definition at line 640 of file test.c.
 {
     group_array = bb_getgroups(&ngroups, NULL);
 }
References bb_getgroups(), group_array, ngroups, and NULL.
Referenced by is_a_group_member().
is_a_group_member()
static int is_a_group_member (gid_t gid) static
Definition at line 649 of file test.c.
 {
     int i;
     /* Short-circuit if possible, maybe saving a call to getgroups(). */
     if (gid == getgid() || gid == getegid())
         return 1;
     if (ngroups == 0)
         initialize_group_array();
     /* Search through the list looking for GID. */
     for (i = 0; i < ngroups; i++)
         if (gid == group_array[i])
             return 1;
     return 0;
 }
References getegid, getgid, group_array, i, initialize_group_array(), and ngroups.
Referenced by test_eaccess().
nexpr()
static number_t nexpr (enum token n) static
Definition at line 772 of file test.c.
 {
     number_t res;
     nest_msg(">nexpr(%s)\n", TOKSTR[n]);
     if (n == UNOT) {
         n = check_operator(*++args);
         if (n == EOI) {
             /* special case: [ ! ], [ a -a ! ] are valid */
             /* IOW, "! ARG" may miss ARG */
             args--;
             unnest_msg("<nexpr:1 (!EOI), args:%s(%p)\n", args[0], &args[0]);
             return 1;
         }
         res = !nexpr(n);
         unnest_msg("<nexpr:%lld\n", res);
         return res;
     }
     res = primary(n);
     unnest_msg("<nexpr:%lld\n", res);
     return res;
 }
References check_operator(), EOI, n, nest_msg, primary(), unnest_msg, and UNOT.
Referenced by aexpr().
oexpr()
static number_t oexpr (enum token n) static
Definition at line 815 of file test.c.
 {
     number_t res;
     nest_msg(">oexpr(%s)\n", TOKSTR[n]);
     res = aexpr(n);
     dbg_msg("oexpr: aexpr:%lld, next args:%s(%p)\n", res, args[1], &args[1]);
     if (check_operator(*++args) == BOR) {
         dbg_msg("oexpr: next arg is OR, next args:%s(%p)\n", args[1], &args[1]);
         res = oexpr(check_operator(*++args)) || res;
         unnest_msg("<oexpr:%lld\n", res);
         return res;
     }
     args--;
     unnest_msg("<oexpr:%lld, args:%s(%p)\n", res, args[0], &args[0]);
     return res;
 }
References aexpr(), BOR, check_operator(), dbg_msg, n, nest_msg, and unnest_msg.
Referenced by primary(), and test_main().
primary()
static number_t primary (enum token n) static
Definition at line 834 of file test.c.
 {
 #if TEST_DEBUG
     number_t res = res; /* for compiler */
 #else
     number_t res;
 #endif
     const struct operator_t *args0_op;
     nest_msg(">primary(%s)\n", TOKSTR[n]);
     if (n == EOI) {
         syntax(NULL, "argument expected");
     }
     if (n == LPAREN) {
         res = oexpr(check_operator(*++args));
         if (check_operator(*++args) != RPAREN)
             syntax(NULL, "closing paren expected");
         unnest_msg("<primary:%lld\n", res);
         return res;
     }
     /* coreutils 6.9 checks "is args[1] binop and args[2] exist?" first,
      * do the same */
     args0_op = last_operator;
     /* last_operator = operator at args[1] */
     if (check_operator(args[1]) != EOI) { /* if args[1] != NULL */
         if (args[2]) {
             // coreutils also does this:
             // if (args[3] && args[0] = "-l" && args[2] is BINOP)
             //  return binop(1 /* prepended by -l */);
             if (last_operator->op_type == BINOP)
                 unnest_msg_and_return(binop(), "<primary: binop:%lld\n");
         }
     }
     /* check "is args[0] unop?" second */
     if (args0_op->op_type == UNOP) {
         /* unary expression */
         if (args[1] == NULL)
 //          syntax(args0_op->op_text, "argument expected");
             goto check_emptiness;
         args++;
         if (n == STREZ)
             unnest_msg_and_return(args[0][0] == '\0', "<primary:%lld\n");
         if (n == STRNZ)
             unnest_msg_and_return(args[0][0] != '\0', "<primary:%lld\n");
         if (n == FILTT)
             unnest_msg_and_return(isatty(getn(*args)), "<primary: isatty(%s)%lld\n", *args);
         unnest_msg_and_return(filstat(*args, n), "<primary: filstat(%s):%lld\n", *args);
     }
     /*check_operator(args[1]); - already done */
     if (last_operator->op_type == BINOP) {
         /* args[2] is known to be NULL, isn't it bound to fail? */
         unnest_msg_and_return(binop(), "<primary:%lld\n");
     }
  check_emptiness:
     unnest_msg_and_return(args[0][0] != '\0', "<primary:%lld\n");
 }
References BINOP, binop(), check_operator(), EOI, filstat(), FILTT, getn(), isatty(), last_operator, LPAREN, n, nest_msg, NULL, oexpr(), operator_t::op_type, RPAREN, STREZ, STRNZ, syntax(), unnest_msg, unnest_msg_and_return, and UNOP.
Referenced by _nl_locale_name(), and nexpr().
syntax()
static void syntax (const char * op, const char * msg) static
Definition at line 459 of file test.c.
 {
     if (op && *op) {
         bb_error_msg("%s: %s", op, msg);
     } else {
         bb_error_msg("%s: %s"+4, msg);
     }
     longjmp(leaving, 2);
 }
References bb_error_msg(), leaving, and longjmp().
Referenced by _nl_explode_name(), binop(), check_operator(), memtodest(), primary(), readtoken1(), and synstack_push().
test_eaccess()
static int test_eaccess (struct stat * st, int mode) static
Definition at line 672 of file test.c.
 {
     unsigned int euid = geteuid();
     if (euid == 0) {
         /* Root can read or write any file. */
         if (mode != X_OK)
             return 0;
         /* Root can execute any file that has any one of the execute
          * bits set. */
         if (st->st_mode & (S_IXUSR | S_IXGRP | S_IXOTH))
             return 0;
     }
     if (st->st_uid == euid)  /* owner */
         mode <<= 6;
     else if (is_a_group_member(st->st_gid))
         mode <<= 3;
     if (st->st_mode & mode)
         return 0;
     return -1;
 }
References euid, geteuid, is_a_group_member(), S_IXGRP, S_IXOTH, S_IXUSR, and X_OK.
Referenced by filstat().
test_main()
int test_main (int argc, char ** argv)
Definition at line 894 of file test.c.
 {
     int res;
     const char *arg0;
 #if BASH_TEST2
     bool bt2 = 0;
 #endif
     arg0 = bb_basename(argv[0]);
     if ((ENABLE_TEST1 || ENABLE_TEST2 || ENABLE_ASH_TEST || ENABLE_HUSH_TEST)
      && (arg0[0] == '[')
     ) {
         --argc;
         if (!arg0[1]) { /* "[" ? */
             if (NOT_LONE_CHAR(argv[argc], ']')) {
                 bb_simple_error_msg("missing ]");
                 return 2;
             }
         } else { /* assuming "[[" */
             if (strcmp(argv[argc], "]]") != 0) {
                 bb_simple_error_msg("missing ]]");
                 return 2;
             }
 #if BASH_TEST2
             bt2 = 1;
 #endif
         }
         argv[argc] = NULL;
     }
     /* argc is unused after this point */
     /* We must do DEINIT_S() prior to returning */
     INIT_S();
 #if BASH_TEST2
     bash_test2 = bt2;
 #endif
     res = setjmp(leaving);
     if (res)
         goto ret;
     /* resetting ngroups is probably unnecessary.  it will
      * force a new call to getgroups(), which prevents using
      * group data fetched during a previous call.  but the
      * only way the group data could be stale is if there's
      * been an intervening call to setgroups(), and this
      * isn't likely in the case of a shell.  paranoia
      * prevails...
      */
     /*ngroups = 0; - done by INIT_S() */
     argv++;
     args = argv;
     /* Implement special cases from POSIX.2, section 4.62.4.
      * Testcase: "test '(' = '('"
      * The general parser would misinterpret '(' as group start.
      */
     if (1) {
         int negate = 0;
  again:
         if (!argv[0]) {
             /* "test" */
             res = 1;
             goto ret_special;
         }
         if (!argv[1]) {
             /* "test [!] arg" */
             res = (argv[0][0] == '\0');
             goto ret_special;
         }
         if (argv[2]) {
             if (!argv[3]) {
                 /*
                  * http://pubs.opengroup.org/onlinepubs/009695399/utilities/test.html
                  * """ 3 arguments:
                  * If $2 is a binary primary, perform the binary test of $1 and $3.
                  * """
                  */
                 check_operator(argv[1]);
                 if (last_operator->op_type == BINOP) {
                     /* "test [!] arg1 <binary_op> arg2" */
                     args = argv;
                     res = (binop() == 0);
  ret_special:
                     /* If there was leading "!" op... */
                     res ^= negate;
                     goto ret;
                 }
                 /* """If $1 is '(' and $3 is ')', perform the unary test of $2."""
                  * Looks like this works without additional coding.
                  */
                 goto check_negate;
             }
             /* argv[3] exists (at least 4 args), is it exactly 4 args? */
             if (!argv[4]) {
                 /*
                  * """ 4 arguments:
                  * If $1 is '!', negate the three-argument test of $2, $3, and $4.
                  * If $1 is '(' and $4 is ')', perform the two-argument test of $2 and $3.
                  * """
                  * Example why code below is necessary: test '(' ! -e ')'
                  */
                 if (LONE_CHAR(argv[0], '(')
                  && LONE_CHAR(argv[3], ')')
                 ) {
                     /* "test [!] ( x y )" */
                     argv[3] = NULL;
                     argv++;
                 }
             }
         }
  check_negate:
         if (LONE_CHAR(argv[0], '!')) {
             argv++;
             negate ^= 1;
             goto again;
         }
     }
     res = !oexpr(check_operator(*args));
     if (*args != NULL && *++args != NULL) {
         /* Examples:
          * test 3 -lt 5 6
          * test -t 1 2
          */
         bb_error_msg("%s: unknown operand", *args);
         res = 2;
     }
  ret:
     DEINIT_S();
     return res;
 }
References arg0, argc, argv, bash_test2, bb_basename(), bb_error_msg(), bb_simple_error_msg(), BINOP, binop(), check_operator(), DEINIT_S, INIT_S, last_operator, leaving, LONE_CHAR, NOT_LONE_CHAR, NULL, oexpr(), setjmp, and strcmp.
Variable Documentation
ALIGN1
const char ops_texts [] ALIGN1 static
Definition at line 363 of file test.c.
ALIGN2
const struct operator_t ops_table [] ALIGN2 static
Definition at line 309 of file test.c.
test_ptr_to_statics
struct test_statics* BB_GLOBAL_CONST test_ptr_to_statics extern
Definition at line 14 of file test_ptr_hack.c.