Fennix Kernel: NetworkARP::ARP Class Reference
NetworkARP::ARP Class Reference
#include <arp.hpp>
Public Member Functions
ARP (NetworkEthernet::Ethernet *Ethernet)
~ARP ()
uint48_t Resolve (InternetProtocol IP)
Resolve an IP address to a MAC address.
void Broadcast (InternetProtocol IP)
Broadcast an ARP packet.
Public Member Functions inherited from NetworkEthernet::EthernetEvents
FrameType GetFrameType ()
virtual void OnEthernetPacketSent (EthernetPacket *Packet)
Private Types
enum DAType { DA_ADD = 1 , DA_DEL = 2 , DA_SEARCH = 3 , DA_UPDATE = 4 }
Private Member Functions
DiscoveredAddress * ManageDiscoveredAddresses (DAType Type, InternetProtocol IP, MediaAccessControl MAC)
DiscoveredAddress * Search (InternetProtocol TargetIP)
DiscoveredAddress * Update (InternetProtocol TargetIP, MediaAccessControl TargetMAC)
bool OnEthernetPacketReceived (uint8_t *Data, uint64_t Length)
Private Attributes
NetworkEthernet::Ethernet * Ethernet
std::vector< NetworkARP::DiscoveredAddress * > DiscoveredAddresses
Additional Inherited Members
Protected Member Functions inherited from NetworkEthernet::EthernetEvents
EthernetEvents (FrameType Type)
~EthernetEvents ()
Detailed Description
Definition at line 66 of file arp.hpp.
Member Enumeration Documentation
DAType
enum NetworkARP::ARP::DAType private
Enumerator
DA_ADD
DA_DEL
DA_SEARCH
DA_UPDATE
Definition at line 71 of file arp.hpp.
         {
             DA_ADD = 1,
             DA_DEL = 2,
             DA_SEARCH = 3,
             DA_UPDATE = 4
         };
Constructor & Destructor Documentation
ARP()
NetworkARP::ARP::ARP (NetworkEthernet::Ethernet * Ethernet)
Definition at line 89 of file AddressResolutionProtocol.cpp.
                                               : NetworkEthernet::EthernetEvents(NetworkEthernet::TYPE_ARP)
     {
         debug("ARP interface %#lx created.", this);
         this->Ethernet = Ethernet;
     }
References debug, and Ethernet.
~ARP()
NetworkARP::ARP::~ARP ()
Definition at line 95 of file AddressResolutionProtocol.cpp.
     {
         debug("ARP interface %#lx destroyed.", this);
     }
References debug.
Member Function Documentation
Broadcast()
void NetworkARP::ARP::Broadcast (InternetProtocol IP)
Broadcast an ARP packet.
Parameters
IP The IP address to broadcast.
Definition at line 172 of file AddressResolutionProtocol.cpp.
     {
         netdbg("Sending broadcast");
         uint48_t ResolvedMAC = this->Resolve(IP);
         ARPHeader *Header = new ARPHeader;
         Header->HardwareType = b16(ARPHardwareType::HTYPE_ETHERNET);
         Header->ProtocolType = b16(NetworkEthernet::FrameType::TYPE_IPV4);
         Header->HardwareSize = b8(0x6);
         Header->ProtocolSize = b8(0x4);
         Header->Operation = b16(ARPOperation::REQUEST);
         Header->SenderMAC = b48(Ethernet->GetInterface()->MAC.ToHex());
         Header->SenderIP = b32(Ethernet->GetInterface()->IP.v4.ToHex());
         Header->TargetMAC = b48(ResolvedMAC);
         Header->TargetIP = b32(IP.v4.ToHex());
         Ethernet->Send(MediaAccessControl().FromHex(ResolvedMAC), NetworkEthernet::FrameType::TYPE_ARP, (uint8_t *)Header, sizeof(ARPHeader));
         delete Header, Header = nullptr;
     }
References b16, b32, b48, b8, Ethernet, NetworkEthernet::Ethernet::GetInterface(), NetworkARP::ARPHeader::HardwareSize, NetworkARP::ARPHeader::HardwareType, NetworkARP::HTYPE_ETHERNET, NetworkInterfaceManager::DeviceInterface::IP, NetworkInterfaceManager::DeviceInterface::MAC, netdbg, NetworkARP::ARPHeader::Operation, NetworkARP::ARPHeader::ProtocolSize, NetworkARP::ARPHeader::ProtocolType, NetworkARP::REQUEST, Resolve(), NetworkEthernet::Ethernet::Send(), NetworkARP::ARPHeader::SenderIP, NetworkARP::ARPHeader::SenderMAC, NetworkARP::ARPHeader::TargetIP, NetworkARP::ARPHeader::TargetMAC, MediaAccessControl::ToHex(), InternetProtocol::Version4::ToHex(), NetworkEthernet::TYPE_ARP, NetworkEthernet::TYPE_IPV4, and InternetProtocol::v4.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
ManageDiscoveredAddresses()
DiscoveredAddress * NetworkARP::ARP::ManageDiscoveredAddresses (DAType Type, InternetProtocol IP, MediaAccessControl MAC) private
Definition at line 29 of file AddressResolutionProtocol.cpp.
     {
         switch (Type)
         {
         case DA_ADD:
         {
             DiscoveredAddress *tmp = new DiscoveredAddress;
             tmp->IP = IP;
             tmp->MAC = MAC;
             DiscoveredAddresses.push_back(tmp);
             netdbg("Added %s to discovered addresses", IP.v4.ToStringLittleEndian());
             return tmp;
         }
         case DA_DEL:
         {
             for (size_t i = 0; i < DiscoveredAddresses.size(); i++)
             {
                 if (DiscoveredAddresses[i]->IP.v4 == IP.v4)
                 {
                     DiscoveredAddress *tmp = DiscoveredAddresses[i];
                     netdbg("Removed %s from discovered addresses", IP.v4.ToStringLittleEndian());
                     delete tmp, tmp = nullptr;
                     DiscoveredAddresses.remove(i);
                 }
             }
             return nullptr;
         }
         case DA_SEARCH:
         {
             for (size_t i = 0; i < DiscoveredAddresses.size(); i++)
             {
                 if (DiscoveredAddresses[i]->IP.v4 == IP.v4)
                 {
                     netdbg("Found %s in discovered addresses", IP.v4.ToStringLittleEndian());
                     return DiscoveredAddresses[i];
                 }
             }
             return nullptr;
         }
         case DA_UPDATE:
         {
             for (size_t i = 0; i < DiscoveredAddresses.size(); i++)
             {
                 if (DiscoveredAddresses[i]->IP.v4 == IP.v4)
                 {
                     DiscoveredAddresses[i]->MAC = MAC;
                     netdbg("Updated %s in discovered addresses", IP.v4.ToStringLittleEndian());
                     return DiscoveredAddresses[i];
                 }
             }
             return nullptr;
         }
         default:
         {
             return nullptr;
         }
         }
         return nullptr;
     }
References DA_ADD, DA_DEL, DA_SEARCH, DA_UPDATE, DiscoveredAddresses, NetworkARP::DiscoveredAddress::IP, NetworkARP::DiscoveredAddress::MAC, netdbg, std::vector< T >::push_back(), std::vector< T >::remove(), std::vector< T >::size(), and Type.
Referenced by OnEthernetPacketReceived(), Search(), and Update().
OnEthernetPacketReceived()
bool NetworkARP::ARP::OnEthernetPacketReceived (uint8_t * Data, uint64_t Length) private virtual
Reimplemented from NetworkEthernet::EthernetEvents.
Definition at line 190 of file AddressResolutionProtocol.cpp.
     {
         netdbg("Received packet");
         ARPHeader *Header = (ARPHeader *)Data;
         InternetProtocol SenderIPv4;
         SenderIPv4.v4 = SenderIPv4.v4.FromHex(b32(Header->SenderIP));
         /* We only support Ethernet and IPv4. */
         if (b16(Header->HardwareType) != ARPHardwareType::HTYPE_ETHERNET || b16(Header->ProtocolType) != NetworkEthernet::FrameType::TYPE_IPV4)
         {
             warn("Invalid hardware/protocol type (%d/%d)", b16(Header->HardwareType), b16(Header->ProtocolType));
             return false;
         }
         InternetProtocol TmpIPStruct;
         InternetProtocol().v4.FromHex(b32(Header->SenderIP));
         if (ManageDiscoveredAddresses(DA_SEARCH, TmpIPStruct, MediaAccessControl().FromHex(b48(Header->SenderMAC))) == nullptr)
         {
             netdbg("Discovered new address %s", SenderIPv4.v4.ToStringLittleEndian());
             TmpIPStruct.v4.FromHex(b32(Header->SenderIP));
             ManageDiscoveredAddresses(DA_ADD, TmpIPStruct, MediaAccessControl().FromHex(b48(Header->SenderMAC)));
         }
         else
         {
             netdbg("Updated address %s", SenderIPv4.v4.ToStringLittleEndian());
             TmpIPStruct.v4.FromHex(b32(Header->SenderIP));
             ManageDiscoveredAddresses(DA_UPDATE, TmpIPStruct, MediaAccessControl().FromHex(b48(Header->SenderMAC)));
         }
         switch (b16(Header->Operation))
         {
         case ARPOperation::REQUEST:
             netdbg("Received request from %s", SenderIPv4.v4.ToStringLittleEndian());
             /* We need to byteswap before we send it back. */
             Header->TargetMAC = b48(Header->SenderMAC);
             Header->TargetIP = b32(Header->SenderIP);
             Header->SenderMAC = b48(Ethernet->GetInterface()->MAC.ToHex());
             Header->SenderIP = b32(Ethernet->GetInterface()->IP.v4.ToHex());
             Header->Operation = b16(ARPOperation::REPLY);
             Ethernet->Send(MediaAccessControl().FromHex(Header->TargetMAC), NetworkEthernet::FrameType::TYPE_ARP, (uint8_t *)Header, sizeof(ARPHeader));
             netdbg("Sent request for %s", SenderIPv4.v4.ToStringLittleEndian());
             break;
         case ARPOperation::REPLY:
             fixme("Received reply from %s", SenderIPv4.v4.ToStringLittleEndian());
             break;
         default:
             warn("Invalid operation (%d)", b16(Header->Operation));
             break;
         }
         return false;
     }
References b16, b32, b48, DA_ADD, DA_SEARCH, DA_UPDATE, Data, Ethernet, fixme, InternetProtocol::Version4::FromHex(), NetworkEthernet::Ethernet::GetInterface(), NetworkARP::ARPHeader::HardwareType, NetworkARP::HTYPE_ETHERNET, NetworkInterfaceManager::DeviceInterface::IP, NetworkInterfaceManager::DeviceInterface::MAC, ManageDiscoveredAddresses(), netdbg, NetworkARP::ARPHeader::Operation, NetworkARP::ARPHeader::ProtocolType, NetworkARP::REPLY, NetworkARP::REQUEST, NetworkEthernet::Ethernet::Send(), NetworkARP::ARPHeader::SenderIP, NetworkARP::ARPHeader::SenderMAC, NetworkARP::ARPHeader::TargetIP, NetworkARP::ARPHeader::TargetMAC, MediaAccessControl::ToHex(), InternetProtocol::Version4::ToHex(), InternetProtocol::Version4::ToStringLittleEndian(), NetworkEthernet::TYPE_ARP, NetworkEthernet::TYPE_IPV4, InternetProtocol::v4, and warn.
Resolve()
uint48_t NetworkARP::ARP::Resolve (InternetProtocol IP)
Resolve an IP address to a MAC address.
Parameters
IP The IP address to resolve. (Little-endian)
Returns
uint48_t The MAC address of the IP address.
Definition at line 122 of file AddressResolutionProtocol.cpp.
     {
         netdbg("Resolving %s", IP.v4.ToStringLittleEndian());
         if (IP.v4 == 0xFFFFFFFF)
             return 0xFFFFFFFFFFFF;
         /* If we can't find the MAC, return the default value which is 0xFFFFFFFFFFFF. */
         uint48_t ret = this->Search(IP)->MAC.ToHex();
         netdbg("Resolved %s to %lx", IP.v4.ToStringLittleEndian(), ret);
         if (ret == 0xFFFFFFFFFFFF)
         {
             netdbg("Sending request");
             /* If we can't find the MAC, send a request.
                Because we are going to send this over the network, we need to byteswap first.
                This is actually very confusing for me. */
             ARPHeader *Header = new ARPHeader;
             Header->HardwareType = b16(ARPHardwareType::HTYPE_ETHERNET);
             Header->ProtocolType = b16(NetworkEthernet::FrameType::TYPE_IPV4);
             Header->HardwareSize = b8(6);
             Header->ProtocolSize = b8(4);
             Header->Operation = b16(ARPOperation::REQUEST);
             Header->SenderMAC = b48(Ethernet->GetInterface()->MAC.ToHex());
             Header->SenderIP = b32(Ethernet->GetInterface()->IP.v4.ToHex());
             Header->TargetMAC = b48(0xFFFFFFFFFFFF);
             Header->TargetIP = b32(IP.v4.ToHex());
             netdbg("SIP: %s; TIP: %s", InternetProtocol().v4.FromHex(Header->SenderIP).ToStringLittleEndian(),
                    InternetProtocol().v4.FromHex(Header->TargetIP).ToStringLittleEndian());
             /* Send the request to the broadcast MAC address. */
             Ethernet->Send({.Address = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}}, NetworkEthernet::FrameType::TYPE_ARP, (uint8_t *)Header, sizeof(ARPHeader));
             delete Header, Header = nullptr;
         }
         int RequestTimeout = 20;
         debug("Waiting for response");
         while (ret == 0xFFFFFFFFFFFF)
         {
             ret = this->Search(IP)->MAC.ToHex();
             if (--RequestTimeout == 0)
             {
                 warn("Request timeout.");
                 return 0;
             }
             netdbg("Still waiting...");
             TaskManager->Sleep(1000);
         }
         return ret;
     }
References b16, b32, b48, b8, debug, Ethernet, NetworkEthernet::Ethernet::GetInterface(), NetworkARP::ARPHeader::HardwareSize, NetworkARP::ARPHeader::HardwareType, NetworkARP::HTYPE_ETHERNET, NetworkInterfaceManager::DeviceInterface::IP, NetworkARP::DiscoveredAddress::MAC, NetworkInterfaceManager::DeviceInterface::MAC, netdbg, NetworkARP::ARPHeader::Operation, NetworkARP::ARPHeader::ProtocolSize, NetworkARP::ARPHeader::ProtocolType, NetworkARP::REQUEST, Search(), NetworkEthernet::Ethernet::Send(), NetworkARP::ARPHeader::SenderIP, NetworkARP::ARPHeader::SenderMAC, Tasking::Task::Sleep(), NetworkARP::ARPHeader::TargetIP, NetworkARP::ARPHeader::TargetMAC, TaskManager, MediaAccessControl::ToHex(), InternetProtocol::Version4::ToHex(), NetworkEthernet::TYPE_ARP, NetworkEthernet::TYPE_IPV4, InternetProtocol::v4, and warn.
Referenced by Broadcast(), and NetworkIPv4::IPv4::Send().
Search()
DiscoveredAddress * NetworkARP::ARP::Search (InternetProtocol TargetIP) private
Definition at line 104 of file AddressResolutionProtocol.cpp.
     {
         DiscoveredAddress *ret = ManageDiscoveredAddresses(DA_SEARCH, TargetIP, MediaAccessControl());
         if (ret)
             return ret;
         warn("No address found for %s", TargetIP.v4.ToStringLittleEndian());
         return &InvalidRet;
     }
References DA_SEARCH, NetworkARP::InvalidRet, ManageDiscoveredAddresses(), InternetProtocol::Version4::ToStringLittleEndian(), InternetProtocol::v4, and warn.
Referenced by Resolve().
Update()
DiscoveredAddress * NetworkARP::ARP::Update (InternetProtocol TargetIP, MediaAccessControl TargetMAC) private
Definition at line 113 of file AddressResolutionProtocol.cpp.
     {
         DiscoveredAddress *ret = ManageDiscoveredAddresses(DA_UPDATE, TargetIP, TargetMAC);
         if (ret)
             return ret;
         warn("No address found for %s", TargetIP.v4.ToStringLittleEndian());
         return &InvalidRet;
     }
References DA_UPDATE, NetworkARP::InvalidRet, ManageDiscoveredAddresses(), InternetProtocol::Version4::ToStringLittleEndian(), InternetProtocol::v4, and warn.
Field Documentation
DiscoveredAddresses
std::vector<NetworkARP::DiscoveredAddress *> NetworkARP::ARP::DiscoveredAddresses private
Definition at line 79 of file arp.hpp.
Referenced by ManageDiscoveredAddresses().
Ethernet
NetworkEthernet::Ethernet* NetworkARP::ARP::Ethernet private
Definition at line 69 of file arp.hpp.
Referenced by ARP(), Broadcast(), OnEthernetPacketReceived(), and Resolve().
The documentation for this class was generated from the following files:
Kernel/include/net/arp.hpp
Kernel/Network/AddressResolutionProtocol.cpp