Fennix Userspace: Userspace/musl/src/locale/__lctrans.c File Reference
__lctrans.c File Reference
#include <locale.h>
#include "locale_impl.h"
Functions
static const char * dummy (const char *msg, const struct __locale_map *lm)
weak_alias (dummy, __lctrans_impl)
const char * __lctrans (const char *msg, const struct __locale_map *lm)
const char * __lctrans_cur (const char *msg)
Function Documentation
__lctrans()
const char* __lctrans (const char * msg, const struct __locale_map * lm)
Definition at line 11 of file __lctrans.c.
 {
     return __lctrans_impl(msg, lm);
 }
References __lctrans_impl().
__lctrans_cur()
const char* __lctrans_cur (const char * msg)
Definition at line 16 of file __lctrans.c.
 {
     return __lctrans_impl(msg, CURRENT_LOCALE->cat[LC_MESSAGES]);
 }
References __lctrans_impl(), CURRENT_LOCALE, and LC_MESSAGES.
Referenced by __getopt_msg().
dummy()
static const char* dummy (const char * msg, const struct __locale_map * lm) static
Definition at line 4 of file __lctrans.c.
 {
     return msg;
 }
weak_alias()
weak_alias (dummy , __lctrans_impl)