Fennix: Userspace/musl/src/math/fmaf.c File Reference
fmaf.c File Reference
#include <fenv.h>
#include <math.h>
#include <stdint.h>
Functions
float fmaf (float x, float y, float z)
Function Documentation
fmaf()
float fmaf (float x, float y, float z)
Definition at line 39 of file fmaf.c.
 {
     #pragma STDC FENV_ACCESS ON
     double xy, result;
     union {double f; uint64_t i;} u;
     int e;
     xy = (double)x * y;
     result = xy + z;
     u.f = result;
     e = u.i>>52 & 0x7ff;
     /* Common case: The double precision result is fine. */
     if ((u.i & 0x1fffffff) != 0x10000000 || /* not a halfway case */
         e == 0x7ff ||                   /* NaN */
         (result - xy == z && result - z == xy) || /* exact */
         fegetround() != FE_TONEAREST)       /* not round-to-nearest */
     {
         /*
         underflow may not be raised correctly, example:
         fmaf(0x1p-120f, 0x1p-120f, 0x1p-149f)
         */
 #if defined(FE_INEXACT) && defined(FE_UNDERFLOW)
         if (e < 0x3ff-126 && e >= 0x3ff-149 && fetestexcept(FE_INEXACT)) {
             feclearexcept(FE_INEXACT);
             /* TODO: gcc and clang bug workaround */
             volatile float vz = z;
             result = xy + vz;
             if (fetestexcept(FE_INEXACT))
                 feraiseexcept(FE_UNDERFLOW);
             else
                 feraiseexcept(FE_INEXACT);
         }
 #endif
         z = result;
         return z;
     }
     /*
      * If result is inexact, and exactly halfway between two float values,
      * we need to adjust the low-order bit in the direction of the error.
      */
     double err;
     int neg = u.i >> 63;
     if (neg == (z > xy))
         err = xy - result + z;
     else
         err = z - result + xy;
     if (neg == (err < 0))
         u.i++;
     else
         u.i--;
     z = u.f;
     return z;
 }
References err(), f, FE_INEXACT, FE_TONEAREST, FE_UNDERFLOW, feclearexcept(), fegetround(), feraiseexcept(), fetestexcept(), i, x, and y.