Fennix Userspace: Userspace/musl/src/misc/setrlimit.c File Reference
setrlimit.c File Reference
#include <sys/resource.h>
#include <errno.h>
#include "syscall.h"
#include "libc.h"
Data Structures
struct ctx
Macros
#define MIN(a, b) ((a)<(b) ? (a) : (b))
#define FIX(x) do{ if ((x)>=SYSCALL_RLIM_INFINITY) (x)=RLIM_INFINITY; }while(0)
Functions
int setrlimit (int resource, const struct rlimit *rlim)
Data Structure Documentation
ctx
struct ctx
Definition at line 7 of file setgroups.c.
Data Fields
int amode
size_t count
int eid
int err
int fd
const char * filename
int id
unsigned long lim[2]
const gid_t * list
int nr
int p
int res
int ret
int sid
Macro Definition Documentation
FIX
#define FIX (x) do{ if ((x)>=SYSCALL_RLIM_INFINITY) (x)=RLIM_INFINITY; }while(0)
Definition at line 7 of file setrlimit.c.
MIN
#define MIN (a, b) ((a)<(b) ? (a) : (b))
Definition at line 6 of file setrlimit.c.
Function Documentation
setrlimit()
int setrlimit (int resource, const struct rlimit * rlim)
Definition at line 24 of file setrlimit.c.
 {
     struct rlimit tmp;
     if (SYSCALL_RLIM_INFINITY != RLIM_INFINITY) {
         tmp = *rlim;
         FIX(tmp.rlim_cur);
         FIX(tmp.rlim_max);
         rlim = &tmp;
     }
     int ret = __syscall(SYS_prlimit64, 0, resource, rlim, 0);
 #ifdef SYS_setrlimit
     if (ret != -ENOSYS) return __syscall_ret(ret);
     struct ctx c = {
         .lim[0] = MIN(rlim->rlim_cur, MIN(-1UL, SYSCALL_RLIM_INFINITY)),
         .lim[1] = MIN(rlim->rlim_max, MIN(-1UL, SYSCALL_RLIM_INFINITY)),
         .res = resource, .err = -1
     };
     __synccall(do_setrlimit, &c);
     if (c.err) {
         if (c.err>0) errno = c.err;
         return -1;
     }
     return 0;
 #else
     return __syscall_ret(ret);
 #endif
 }
References __synccall(), __syscall, __syscall_ret(), c, ENOSYS, errno, FIX, MIN, ctx::ret, rlimit::rlim_cur, RLIM_INFINITY, rlimit::rlim_max, and SYSCALL_RLIM_INFINITY.
Referenced by bump_nofile(), inetd_main(), limit(), passwd_main(), run(), shell_builtin_ulimit(), and ulimit().