Fennix Userspace: LibraryGuard Struct Reference
LibraryGuard Struct Reference
Public Member Functions
LibraryGuard ()
LibraryGuard ()
LibraryGuard ()
LibraryGuard ()
LibraryGuard ()
LibraryGuard ()
LibraryGuard ()
LibraryGuard ()
Detailed Description
Definition at line 14 of file entry.cpp.
Constructor & Destructor Documentation
LibraryGuard() [1/8]
LibraryGuard::LibraryGuard ()
Definition at line 20 of file entry.cpp.
{
     __mlibc_initLocale();
     // Parse the exec() stack.
     mlibc::parse_exec_stack(__dlapi_entrystack(), &__mlibc_stack_data);
     mlibc::set_startup_data(__mlibc_stack_data.argc, __mlibc_stack_data.argv,
                             __mlibc_stack_data.envp);
 }
References __dlapi_entrystack(), __mlibc_initLocale(), __mlibc_stack_data, mlibc::exec_stack_data::argc, mlibc::exec_stack_data::argv, mlibc::exec_stack_data::envp, mlibc::parse_exec_stack(), and mlibc::set_startup_data().
LibraryGuard() [2/8]
LibraryGuard::LibraryGuard ()
LibraryGuard() [3/8]
LibraryGuard::LibraryGuard ()
LibraryGuard() [4/8]
LibraryGuard::LibraryGuard ()
LibraryGuard() [5/8]
LibraryGuard::LibraryGuard ()
LibraryGuard() [6/8]
LibraryGuard::LibraryGuard ()
LibraryGuard() [7/8]
LibraryGuard::LibraryGuard ()
LibraryGuard() [8/8]
LibraryGuard::LibraryGuard ()
The documentation for this struct was generated from the following file:
Userspace/mlibc/sysdeps/aero/generic/entry.cpp