Fennix Userspace: Userspace/musl/src/process/execv.c File Reference
execv.c File Reference
#include <unistd.h>
Functions
int execv (const char *path, char *const argv[])
Variables
char ** __environ
Function Documentation
execv()
int execv (const char * path, char *const argv[])
Definition at line 5 of file execv.c.
 {
     return execve(path, argv, __environ);
 }
References __environ, argv, ENOSYS, errno, and execve().
Referenced by exec_conf(), exec_shell(), execl(), main(), popen_ls(), pseudo_exec_argv(), re_exec(), self_fork_exec(), startservice(), switch_root_main(), and test_execve_fork().
Variable Documentation
__environ
char** __environ extern
Definition at line 3 of file __environ.c.
Referenced by execv().