Fennix Userspace: Userspace/libc/include/stdio.h File Reference
stdio.h File Reference
#include <stdarg.h>
#include <stddef.h>
#include <sys/stat.h>
Data Structures
struct _IO_marker
struct _IO_FILE
Macros
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define EOF (-1)
EOF - End of file.
#define stdin stdin
#define stdout stdout
#define stderr stderr
Typedefs
typedef struct _IO_FILE FILE
Functions
FILE * freopen (const char *filename, const char *mode, FILE *stream)
FILE * fopen (const char *filename, const char *mode)
size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
off_t fseek (FILE *stream, long offset, int whence)
long ftell (FILE *stream)
int fclose (FILE *fp)
int fflush (FILE *stream)
int fprintf (FILE *stream, const char *format,...)
int printf (const char *format,...)
void setbuf (FILE *stream, char *buf)
int vfprintf (FILE *stream, const char *format, va_list arg)
int vsscanf (const char *s, const char *format, va_list arg)
int sscanf (const char *s, const char *format,...)
int fputc (int c, FILE *stream)
int putc (int c, FILE *stream)
int fputs (const char *s, FILE *stream)
int puts (const char *s)
int putchar (int c)
int fgetc (FILE *stream)
Variables
FILE * stdin
FILE * stdout
FILE * stderr
Data Structure Documentation
_IO_marker
struct _IO_marker
Definition at line 19 of file stdio.h.
Data Fields
struct _IO_marker * _next
int _pos
struct _IO_FILE * _sbuf
Macro Definition Documentation
EOF
#define EOF (-1)
EOF - End of file.
The value returned by several functions to indicate the end of file.
Definition at line 17 of file stdio.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 9 of file stdio.h.
SEEK_END
#define SEEK_END 2
Definition at line 10 of file stdio.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 8 of file stdio.h.
stderr
#define stderr stderr
Definition at line 58 of file stdio.h.
stdin
#define stdin stdin
Definition at line 56 of file stdio.h.
stdout
#define stdout stdout
Definition at line 57 of file stdio.h.
Typedef Documentation
FILE
typedef struct _IO_FILE FILE
Definition at line 1 of file stdio.h.
Function Documentation
fclose()
int fclose (FILE * fp)
Definition at line 54 of file file.c.
 {
     if (fp == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     return syscall1(sc_close, fp->_fileno);
 }
References _IO_FILE::_fileno, EINVAL, EOF, errno, and NULL.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), _nl_log_untranslated(), add_remove_shell_main(), append_control_file_to_llist(), arp_show(), bb_displayroutes(), bb_dump_addfile(), cleanup(), comm_main(), conf_read_simple(), conf_write(), config_close(), convert(), create_file(), create_list(), dialog_menu(), do_all_in_proc_swaps(), do_disk_statistics(), do_info(), do_pidfile(), do_wordexp(), download_one_url(), dprintf(), encode_n_base64(), endgrent(), endmntent(), endpwent(), endusershell(), evaluate(), expand_main(), extract_info(), fb_drawimage(), fclose_if_not_stdin(), file_action_grep(), file_write_dep(), finalize(), find_export_symbols(), freopen(), G_DoLoadGame(), G_DoSaveGame(), get_block_backed_filesystems(), get_charset_aliases(), get_cpu_count(), get_cpu_statistics(), get_hz(), get_irqcpu_nr(), get_irqs_from_interrupts(), get_irqs_from_stat(), get_smp_uptime(), get_uptime(), getdate(), getgrouplist(), getgrouplist_internal(), handle_dir_common(), head_builtin(), if_readlist_proc(), ifupdown_main(), index_status_file(), is_hpet_irq(), is_ide_cdrom_or_tape(), klogd_setloglevel(), list_devs_in_proc_partititons(), LoadDefaultCollection(), LoadResponseFile(), logdir_close(), M_FileExists(), M_ReadFile(), M_ReadSaveStrings(), M_WriteFile(), main(), more_main(), next_input_file(), open_shell_script(), parse(), parse_conf(), parse_file(), parse_meminfo(), patch_main(), pclose(), popen(), popmaildir_main(), print_builtin(), print_login_issue(), print_numbered_lines(), process_cron_update_file(), process_files(), process_includes(), process_irq_counts(), process_timer_stats(), procps_scan(), query(), read_alias_file(), read_config_file(), read_cstate_counts(), read_iface_state(), read_interfaces(), read_man_page(), readprofile_main(), rev_main(), rotate(), rtc_adjtime_is_utc(), save_input_to_file(), SaveDefaultCollection(), scan_proc_net_or_maps(), scriptreplay_main(), sed_main(), sendmail_main(), setfiles_main(), setgrent(), setpwent(), StatDump(), stdcat(), test_file(), unpack_package(), unset_bash_input(), update_passwd(), W_StdC_CloseFile(), write_helpfiles(), write_status_file(), write_str_to_file(), WriteTimidityConfig(), xprint_and_close_file(), and xtrace_reset().
fflush()
int fflush (FILE * stream)
Definition at line 85 of file file.c.
 {
     if (stream == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     errno = ENOSYS;
     return EOF;
 }
References EINVAL, ENOSYS, EOF, errno, and NULL.
Referenced by _flushlbf(), _rl_clean_up_for_exit(), _rl_erase_entire_line(), _rl_init_file_error(), _rl_internal_pager(), _rl_move_vert(), _rl_ttyflush(), _rl_update_final(), botch(), builtin_usage(), conf_askvalue(), conf_choice(), create_directory(), create_file(), display_matches(), do_redirection_internal(), docfunctions(), download_one_url(), dprintf(), dump_file(), evaluate(), exec_kernel_doc(), execute_builtin_or_function(), execute_subshell_builtin_or_function(), exit_shell(), fclose(), fflush_all(), fflush_stdout_and_exit(), freopen(), ftpcmd(), hello_builtin(), hello_builtin_load(), hello_builtin_unload(), I_Error(), I_InitSquashTable(), I_InitStretchTables(), id_builtin(), inotifyd_main(), line_error(), logdir_close(), main(), necho_builtin(), newline_and_flush(), parse_file(), powertop_main(), print_builtin(), print_pipeline(), print_prompt(), printst(), programming_error(), reader_loop(), readline_internal_setup(), rl_deprep_terminal(), rl_ding(), rl_prep_terminal(), rl_print_last_kbd_macro(), rl_redisplay(), rl_show_char(), rotate(), sh_chkwrite(), subshell_exit(), test_brk(), test_dirent(), test_execve_fork(), test_file(), test_passwd(), test_ptmx(), test_stdio(), test_time(), test_watch_directory(), test_watch_file(), throw_to_top_level(), update_passwd(), uuencode_main(), wait_for(), write_helpfiles(), xbotch(), xtrace_print_assignment(), xtrace_print_word_list(), and xtrace_reset().
fgetc()
int fgetc (FILE * stream)
Definition at line 7 of file get.c.
 {
 }
fopen()
FILE* fopen (const char * filename, const char * mode)
Definition at line 19 of file file.c.
 {
     int fd = syscall2(sc_open, (uint64_t)filename, (uint64_t)mode);
     if (fd < 0)
         return NULL;
     FILE *FilePtr = malloc(sizeof(FILE));
     FilePtr->_fileno = fd;
     return FilePtr;
 }
References _IO_FILE::_fileno, fd, filename, malloc, and NULL.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), _nl_log_untranslated(), conf_write(), create_file(), dialog_menu(), file_write_dep(), find_export_symbols(), fopen_for_read(), fopen_for_write(), fopen_or_warn(), freopen(), G_DoLoadGame(), G_DoSaveGame(), get_charset_aliases(), getdate(), getgrent(), getgrouplist(), getpwent(), getspnam_r(), head_builtin(), LoadDefaultCollection(), LoadResponseFile(), M_FileExists(), M_ReadFile(), M_ReadSaveStrings(), M_WriteFile(), main(), process_includes(), produces_handler(), read_alias_file(), read_man_page(), SaveDefaultCollection(), setmntent(), setusershell(), StatDump(), stdcat(), test_file(), update_passwd(), W_StdC_OpenFile(), write_helpfiles(), WriteTimidityConfig(), and xfopen().
fprintf()
int fprintf (FILE * stream, const char * format, ...)
Definition at line 97 of file file.c.
 {
     if (stream == NULL || format == NULL)
     {
         errno = EINVAL;
         return -1;
     }
     va_list args;
     va_start(args, format);
     const int ret = vfprintf(stream, format, args);
     va_end(args);
     return ret;
 }
References args, EINVAL, errno, format(), NULL, va_end, va_start, and vfprintf().
Referenced by __assert_fail(), _nl_log_untranslated(), _rl_errmsg(), _rl_init_file_error(), _rl_internal_pager(), _rl_macro_dumper_internal(), _rl_ttymsg(), addcchar(), addcstr(), addmntent(), ash_vmsg(), ask_and_unlink(), back_lines(), bad_record_die(), bb_progress_update(), bbunpack(), botch(), builtin_error(), builtin_error_prolog(), builtin_usage(), builtin_warning(), catch(), cmp_main(), conf_warning(), conf_write(), confirm_or_abort(), const_des_init(), dd_output_status(), describe_pid(), dialog_checklist(), dialog_menu(), dialog_textbox(), display_matches(), do_check(), do_config_file(), dolisten(), DonutOverrun(), download_one_url(), dump_lsyntax(), error_prolog(), escape_input(), EV_DoDonut(), EV_VerticalDoor(), exec_kernel_doc(), execute_line(), extract_info(), fatal_error(), fgets_trim_sanitize(), file_write_dep(), finalize(), find_export_symbols(), ftpcmd(), get_line(), get_working_directory(), glob_filename(), handle_eof_input_unit(), herror(), I_CDMusPrintStartup(), I_Error(), ifupdown_main(), init_wsize(), initialize_signames(), internal_debug(), internal_error(), internal_inform(), internal_warning(), ipaddr_modify(), j_inputbox(), kconfig_load(), klogd_setloglevel(), line_error(), M_Episode(), main(), make_here_document(), memory_error_and_abort(), menu_warn(), mkfs_vfat_main(), mv_main(), nc_main(), notify_of_job_status(), pad(), PadRejectArray(), parse_dep_file(), ParseField(), parser_error(), pretty_print_job(), print_builtin(), print_deps(), print_pipeline(), print_position(), print_prompt(), print_route(), printargs(), process_files(), process_line(), produces_handler(), programming_error(), prop_warn(), psignal(), putgrent(), putpwent(), putspent(), reader_loop(), readline_internal_setup(), readwrite(), remove_file(), report_error(), resize_main(), restore(), retrieve_file_data(), rl_deprep_terminal(), rl_ding(), rl_dump_functions(), rl_dump_macros(), rl_dump_variables(), rl_function_dumper(), rl_list_funmap_names(), rl_prep_terminal(), rl_show_char(), rl_variable_dumper(), safe_write_to_pty_decode_iac(), save_input_to_file(), SaveDefaultCollection(), saveg_read8(), saveg_write8(), scan_expression(), scan_request(), script_main(), send_headers(), send_pwd_to_eterm(), shell_getc(), show_shell_usage(), sigpipe(), sigstat(), sort_main(), SpechitOverrun(), stdcat(), stralloc(), strgrow(), sys_error(), table_lookup(), throw_to_top_level(), too_dangerous(), unpack_package(), update_passwd(), usage(), Usage(), valid_argument(), vwarn(), vwarnx(), wait_for(), wcomment(), wprintf_core(), write_buffer_no_status(), write_builtins(), write_documentation(), write_dummy_declarations(), write_endifs(), write_file_footers(), write_file_headers(), write_helpfiles(), write_ifdefs(), write_longdocs(), write_signames(), write_status_file(), WriteTimidityConfig(), xargs_main(), xbotch(), xgetpty(), xmalloc(), xtrace_print_assignment(), xtrace_print_case_command_head(), xtrace_print_for_command_head(), xtrace_print_word_list(), and Z_FileDumpHeap().
fputc()
int fputc (int c, FILE * stream)
Definition at line 7 of file put.c.
 {
     // FIXME
     // if (stream == NULL)
     // {
     //     errno = EBADF;
     //     return EOF;
     // }
     char str[2] = {c, '\0'};
     // return syscall3(sys_KernelCTL, KCTL_PRINT, str, 0);
 }
References c, and str.
fputs()
int fputs (const char * s, FILE * stream)
Definition at line 21 of file put.c.
 {
     for (int i = 0; s[i] != '\0'; i++)
         fputc(s[i], stream);
 }
References fputc(), i, and s.
fread()
size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 30 of file file.c.
 {
     if (ptr == NULL || stream == NULL || size == 0 || nmemb == 0)
     {
         errno = EINVAL;
         return 0;
     }
     syscall3(sc_lseek, stream->_fileno, stream->_offset, SEEK_SET);
     return syscall3(sc_read, (uint64_t)stream->_fileno, (uint64_t)ptr, size * nmemb);
 }
References _IO_FILE::_fileno, _IO_FILE::_offset, EINVAL, errno, NULL, SEEK_SET, and size.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), diffreg(), encode_n_base64(), fb_drawimage(), get(), getgrouplist(), getw(), LoadResponseFile(), M_ReadFile(), M_ReadSaveStrings(), read_block(), read_man_page(), retrieve_file_data(), saveg_read8(), skip(), and W_StdC_Read().
freopen()
FILE* freopen (const char * filename, const char * mode, FILE * stream)
Definition at line 13 of file file.c.
 {
     errno = ENOSYS;
     return NULL;
 }
References ENOSYS, errno, and NULL.
Referenced by command_substitute(), do_piping(), main(), makemime_main(), next(), and xfreopen_write().
fseek()
off_t fseek (FILE * stream, long offset, int whence)
Definition at line 43 of file fseek.c.
 {
     return __fseeko(f, off, whence);
 }
References __fseeko(), f, and off.
Referenced by addmntent(), M_FileLength(), main(), and W_StdC_Read().
ftell()
long ftell (FILE * stream)
Definition at line 80 of file file.c.
 {
     return stream->_offset;
 }
References _IO_FILE::_offset.
Referenced by G_DoSaveGame(), M_FileLength(), saveg_read_pad(), and saveg_write_pad().
fwrite()
size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 42 of file file.c.
 {
     if (ptr == NULL || stream == NULL || size == 0 || nmemb == 0)
     {
         errno = EINVAL;
         return 0;
     }
     syscall3(sc_lseek, stream->_fileno, stream->_offset, SEEK_SET);
     return syscall3(sc_write, (uint64_t)stream->_fileno, (uint64_t)ptr, size * nmemb);
 }
References _IO_FILE::_fileno, _IO_FILE::_offset, EINVAL, errno, NULL, SEEK_SET, and size.
Referenced by __getopt_msg(), _rl_output_some_chars(), _rl_put_indicator(), buffer_pwrite(), conf_write(), encode_n_base64(), evaluate(), expr_print_file_helper(), fnprint(), fputs(), M_WriteFile(), perror(), print_line(), putw(), read_base64(), refresh(), saveg_write8(), svlogd_main(), tee_main(), write2stdout(), and write_zeros().
printf()
int printf (const char * format, ...)
An implementation of the C standard's printf/vprintf
Note
you must implement a putchar_ function for using this function - it invokes putchar_ rather than directly performing any I/O (which insulates it from any dependence on the operating system and external libraries).
Parameters
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each %-specifier in format string
Returns
The number of characters written into s, not counting the terminating null character
Definition at line 1554 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vprintf(format, args);
     va_end(args);
     return ret;
 }
References args, format(), va_end, va_start, and vprintf().
Referenced by __libc_sbrk(), act(), add_links(), add_zone_common(), adddep(), adjtimex_main(), alarm_handler(), alarm_intr(), allocate_new_page(), arp_del(), arp_disp(), arp_show(), ascii_main(), ask(), ask_and_unlink(), basename_builtin(), bb_displayroutes(), bb_make_directory(), blockdev_main(), buffer_print(), builtin_help(), cal_main(), cb_linehandler(), cbq_print_opt(), center(), change_filedir_context(), check_all(), check_blocks(), check_conf(), check_consistency(), check_counts(), check_file(), check_mail(), check_mount(), check_stdin(), check_zone_nr2(), CheckDirectoryHasIWAD(), chrt_main(), cksum_main(), clear_line(), colon(), com_help(), com_pwd(), com_stat(), common_ping_main(), common_traceroute_main(), conf(), conf_askvalue(), conf_choice(), conf_read_simple(), conf_string(), conf_sym(), configure_package(), conv_c(), conv_u(), copy_file(), cut_file(), cutbytes(), cutchars(), cutfields(), D_AddFile(), D_CheckNetGame(), D_Disconnected(), D_DoomLoop(), D_DoomMain(), D_FindIWAD(), D_InitNetGame(), dbg_print_flags(), dbg_print_ptype(), dbg_print_stype(), depmod_main(), devfsd_main(), devmem_main(), df_main(), diff(), dirname_builtin(), display(), display_boolean(), display_files(), display_header(), display_process_list(), display_recoverable(), display_signal_list(), display_single(), display_tree(), display_uuid_cache(), display_verbose(), do_modprobe(), do_msg(), do_sem(), do_shm(), do_stat(), do_stop(), docfunctions(), doCommands(), dumpleases_main(), env_main(), ether_wake_main(), exec_conf(), execute(), expr_calc_value(), expr_compare_type(), expr_copy(), expr_eq(), expr_free(), expr_join_and(), expr_join_or(), expr_main(), expr_transform(), factorize_numstr(), fdformat_main(), fdisk_main(), fgconsole_main(), fileAction(), filter_rename_config(), finish(), flash_eraseall_main(), fork_bomb(), fork_bomb_syscall(), format_address_std(), free(), free_main(), fsck_device(), fsck_minix_main(), fstrim_main(), ftpgetput_main(), G_DoPlayDemo(), generate_output(), get_boot(), get_inode_common(), get_list_blocks(), get_sectorsize(), getconf_all(), getconf_internal(), getconf_print(), getsebool_main(), gotoxy(), grep_file(), GUS_WriteConfig(), HandleSignal(), head_builtin(), head_main(), header_verbose_list(), header_verbose_list_ar(), hello_builtin(), hello_builtin_load(), hello_builtin_unload(), hexedit_main(), hostid_main(), hostname_main(), hush_main(), I_CDMusPrintStartup(), I_GetPaletteIndex(), I_InitGraphics(), I_InitJoystick(), I_InitSquashTable(), I_InitStretchTables(), I_PrintStartupBanner(), I_ResetScaleTables(), I_ZoneBase(), id_main(), id_prall(), id_prgrp(), id_pruser(), ife_print(), ifupdown_main(), InitGameVersion(), inotifyd_main(), ionice_main(), ipcalc_main(), ipneigh_list_or_flush(), kbd_mode_main(), kill_main(), last_main(), less_gets(), liballoc_dump(), list_attributes(), list_disk_geometry(), list_packages(), list_table(), ln_main(), LoadGameSettings(), LoadResponseFile(), logname_builtin(), logread_main(), losetup_main(), lpd_main(), lsattr_dir_proc(), lsmod_main(), lsof_main(), lsscsi_main(), M_ExtractFileBase(), M_GetSaveGameDir(), M_LoadDefaults(), M_SetConfigDir(), main(), makemime_main(), malloc(), matchpathcon_main(), md5_sha1_sum_main(), mem_fread(), mem_fseek(), message__print_file_lineno(), message__print_gettext_msgid_msgstr(), mkfs_ext2_main(), mkswap_main(), mktemp_builtin(), more_main(), mount_main(), mountpoint_main(), move_cursor(), mt_main(), mv_main(), nandwrite_main(), necho_builtin(), netstat_main(), next_good_eraseblock(), nice_main(), noresp(), nproc_main(), number_process(), obscure(), open_list_and_close(), packet4_ok(), parse_dep_file(), passwd_main(), paste_files_separate(), patch_main(), perms(), pidof_main(), powertop_main(), pretty_print_loop(), print(), print_addrinfo(), print_ascii(), print_assignment(), print_base(), print_bytes_scaled(), print_C_style(), print_char(), print_class(), print_closing_wait(), print_cmdline(), print_command(), print_common(), print_delta_ms(), print_devstat_header(), print_double(), print_flag(), print_flags_separated(), print_float(), print_fltseq(), print_func_list(), print_header(), print_hilite(), print_host(), print_inet_line(), print_int(), print_intseq(), print_line(), print_lineno(), print_link_flags(), print_linkinfo(), print_long_double(), print_matchpathcon(), print_msg(), print_neigh(), print_numbered_lines(), print_perms(), print_qdisc(), print_queuelen(), print_route(), print_rule(), print_s_char(), print_s_short(), print_sem(), print_shm(), print_short(), print_sig(), print_signames(), print_smaprec(), print_stats_cpu_struct(), print_stats_dev_struct(), print_status(), print_statusline(), print_tunnel(), print_var_function(), print_var_value(), print_w(), printargv(), PrintDehackedBanners(), printenv_builtin(), printf_cap(), PrintGameVersion(), printlim(), printline(), printmode(), printone(), printsome(), printst(), prio_print_opt(), process_pid_str(), process_wait_result(), procps_get_maps(), progress(), ps_main(), pscan_main(), purge_package(), pwdx_main(), query(), R_GenerateLookup(), R_Init(), R_InitData(), R_InitSpriteLumps(), R_InitTextures(), rdate_main(), rdev_main(), read_block(), read_extended(), read_tables(), ReadLine(), readLines(), readlink_main(), readprofile_main(), realloc(), realpath_builtin(), reboot_linux(), recursive_check(), recursive_query(), recv_pack(), redraw(), redraw_cur_line(), reinitialize(), remove_file(), remove_package(), reset_main(), resize_main(), restore(), restore_term(), rfkill_main(), rl_print_last_kbd_macro(), rmdir_main(), rtcwake_main(), runlevel_main(), scan_and_display_dirs_recur(), scan_and_match(), scan_recursive(), scan_request(), script_main(), seed_from_file_if_exists(), seedrng_main(), self_fork_exec(), send_probe(), send_r_n(), seq_main(), serial_get(), sestatus_main(), set_mode(), setConMode(), SetMissionForPackName(), setup_tables(), shell_builtin_ulimit(), show_clock(), show_entry(), show_min_max(), show_progress(), show_shell_version(), show_timerstats(), showkey_main(), showmode(), shuf_main(), shutdown_linux(), signalHandler(), sigstat(), sort_main(), start_job(), start_stop_daemon_main(), StatDump(), status_print(), strftime_builtin(), strings_main(), strlist_print(), sum_file(), summarize(), sym_check_deps(), sym_check_expr_deps(), sysctl_act_on_setting(), telnet_main(), test_args(), test_brk(), test_dirent(), test_execve_fork(), test_file(), test_passwd(), test_ptmx(), test_signal(), test_stdio(), test_system(), test_time(), test_unaligned(), test_watch_directory(), test_watch_file(), traceroute_init(), tree_main(), tree_print(), ts_main(), ttysize_main(), tunctl_main(), uniq_main(), unix_do_one(), unpack_package(), unzip_main(), update_tree(), uprint(), uptime_main(), usage(), use_config(), uuencode_main(), vlock_main(), volname_main(), W_AddFile(), W_ParseCommandLine(), wait_one(), warn_geometry(), watch_main(), watchdog_main(), wc_main(), who_main(), whoami_builtin(), WI_drawOnLnode(), write_block(), write_irqcpu_stats(), write_stats_core(), writeLines(), xprintf(), xxd_main(), and Z_DumpHeap().
putc()
int putc (int c, FILE * stream)
Definition at line 19 of file put.c.
 { return fputc(c, stream); }
References c, and fputc().
putchar()
int putchar (int c)
Definition at line 33 of file put.c.
 { return fputc(c, stdout); }
References c, fputc(), and stdout.
puts()
int puts (const char * s)
Definition at line 27 of file put.c.
 {
     for (int i = 0; s[i] != '\0'; i++)
         fputc(s[i], stdout);
 }
References fputc(), i, s, and stdout.
Referenced by ACTF(), add_remove_shell_main(), ask(), builtin_pwd(), cal_main(), check_all(), check_deps(), check_mail(), check_mount(), colon(), cpu_report(), cryptpw_main(), cttyhack_main(), cut_file(), date_main(), diff(), dirname_main(), display_boolean(), display_header(), display_verbose(), do_stop(), doCommands(), doit(), dumpleases_main(), encode_n_base64(), expr_main(), fatattr_main(), fdformat_main(), fdisk_main(), fetch(), fileAction(), findfs_main(), fsck_main(), fsck_minix_main(), get(), get_boot(), get_inode_common(), getenforce_main(), getopt_main(), getsebool_main(), grep_file(), header_list(), hostname_main(), httpd_main(), I_InitSquashTable(), I_InitStretchTables(), I_PrintBanner(), ipcrm_main(), ipneigh_list_or_flush(), kill_main(), list_packages(), list_table(), logical_getcwd(), login_main(), logname_main(), losetup_main(), lpd_main(), main(), makemime_main(), mesg_main(), mktemp_main(), modprobe_main(), new_password(), powertop_main(), preadfd(), print_ascii(), print_closing_wait(), print_host(), print_line(), print_login_issue(), print_matchpathcon(), print_numbered_lines(), print_serial_flags(), print_timestamp(), printenv_main(), printlim(), process_wait_result(), procps_get_maps(), ps_main(), pwd_main(), read_extended(), read_tables(), realpath_main(), recv_pack(), run_parts_main(), run_pipe(), runlevel_main(), scan_request(), sed_main(), show_help(), show_timerstats(), showkey_main(), sysctl_act_on_setting(), tar_main(), tree_print(), trim_trailing_spaces_and_print(), tsort_main(), tty_builtin(), tty_main(), tunctl_main(), uevent_main(), umaskcmd(), unzip_main(), usage(), vlock_main(), warn_geometry(), which_main(), who_main(), whoami_main(), write_block(), and writeline().
setbuf()
void setbuf (FILE * stream, char * buf)
Definition at line 112 of file file.c.
 {
 }
Referenced by fsck_main(), main(), mpstat_main(), open_next_file(), and tee_main().
sscanf()
int sscanf (const char * s, const char * format, ...)
Definition at line 125 of file file.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsscanf(s, format, args);
     va_end(args);
     return ret;
 }
References args, format(), s, va_end, va_start, and vsscanf().
Referenced by action_compat(), arp_show(), build_ipv4_addr(), cap_name_to_number(), colon(), conf(), conf_choice(), depmod_main(), do_disk_statistics(), do_mktime(), do_tunnels_list(), fb_drawimage(), fuser_main(), get_cpu_count(), get_cpu_statistics(), get_dev_fields(), get_header_cpio(), get_irqs_from_stat(), get_num_from_file(), get_uptime(), get_wol_pw(), getmntent_r(), list_devs_in_proc_partititons(), ll_addr_a2n(), M_StrToInt(), main(), make_device(), name_to_dev_t(), parse_datestr(), parse_meminfo(), ParseIntParameter(), patch_main(), process_config_line(), procps_scan(), readprofile_main(), recover_mode(), scan_inet_proc_line(), scan_proc_net_or_maps(), ubi_devnum_from_devname(), ubi_tools_main(), and unix_do_one().
vfprintf()
int vfprintf (FILE * stream, const char * format, va_list arg)
Definition at line 116 of file file.c.
 {
     return 0;
 }
Referenced by _rl_init_file_error(), ash_vmsg(), builtin_error(), builtin_warning(), conf_warning(), dprintf(), fatal_error(), fprintf(), I_Error(), internal_debug(), internal_error(), internal_inform(), internal_warning(), menu_warn(), parser_error(), printf(), programming_error(), prop_warn(), report_error(), sys_error(), vdprintf(), vprintf(), vsnprintf(), vwarn(), and vwarnx().
vsscanf()
int vsscanf (const char * s, const char * format, va_list arg)
Definition at line 121 of file file.c.
 {
 }
Referenced by sscanf().
Variable Documentation
stderr
FILE* stderr extern
Definition at line 11 of file file.c.
stdin
FILE* stdin extern
Definition at line 9 of file file.c.
stdout
FILE* stdout extern
Definition at line 10 of file file.c.