Fennix Userspace: Userspace/musl/src/legacy/err.c File Reference
err.c File Reference
#include <err.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
Functions
void vwarn (const char *fmt, va_list ap)
void vwarnx (const char *fmt, va_list ap)
_Noreturn void verr (int status, const char *fmt, va_list ap)
_Noreturn void verrx (int status, const char *fmt, va_list ap)
void warn (const char *fmt,...)
void warnx (const char *fmt,...)
_Noreturn void err (int status, const char *fmt,...)
_Noreturn void errx (int status, const char *fmt,...)
Variables
char * __progname
Function Documentation
err()
_Noreturn void err (int status, const char * fmt, ...)
Definition at line 53 of file err.c.
 {
     va_list ap;
     va_start(ap, fmt);
     verr(status, fmt, ap);
     va_end(ap);
 }
References ap, status, va_end, va_start, and verr().
Referenced by __ptsname_r(), _remove_directory(), arith_apply(), arp_del(), bbunpack(), cdcmd(), cut_out_ull_opt(), do_all_in_proc_swaps(), do_em_all_in_fstab(), do_get_ioctl(), do_ioctl_get_ifname(), do_ioctl_get_iftype(), do_nftw(), do_show(), do_wordexp(), docd(), echo_main(), evaltree(), evaluate(), evaluate_string(), examine_file(), expandstr(), fileAction(), fixredir(), fmaf(), get_header_tar(), get_terminal_width_height(), gethostbyaddr(), gethostbyaddr_r(), gethostbyname2(), gethostbyname2_r(), gethostbyname_r(), getjob(), iconv(), IF_DESKTOP(), if_nameindex(), is_whole_disk(), lio_wait(), match(), moderror(), mountpoint_main(), ntp_init(), parse_atom(), parse_bracket(), parse_datestr(), ParseField(), process_one(), psRsaEncryptPub(), pstm_exptmod(), pstm_mod(), ptsname(), read_num(), redirectsafe(), restore(), rmmod_main(), rtnl_dump_filter(), rtnl_send_check(), rtnl_talk(), savefd(), send_pack(), sendto_ip4(), serial_ctl(), shell_builtin_read(), start(), start_one_job(), strerror_r(), swap_enable_disable(), tre_parse(), typecmd(), volume_id_get_buffer(), waitproc(), wh_helper(), and xmalloc_readlink_or_warn().
errx()
_Noreturn void errx (int status, const char * fmt, ...)
Definition at line 61 of file err.c.
 {
     va_list ap;
     va_start(ap, fmt);
     verrx(status, fmt, ap);
     va_end(ap);
 }
References ap, status, va_end, va_start, and verrx().
verr()
_Noreturn void verr (int status, const char * fmt, va_list ap)
Definition at line 25 of file err.c.
 {
     vwarn(fmt, ap);
     exit(status);
 }
References ap, exit(), status, and vwarn().
Referenced by err().
verrx()
_Noreturn void verrx (int status, const char * fmt, va_list ap)
Definition at line 31 of file err.c.
 {
     vwarnx(fmt, ap);
     exit(status);
 }
References ap, exit(), status, and vwarnx().
Referenced by errx().
vwarn()
void vwarn (const char * fmt, va_list ap)
Definition at line 8 of file err.c.
 {
     fprintf (stderr, "%s: ", __progname);
     if (fmt) {
         vfprintf(stderr, fmt, ap);
         fputs (": ", stderr);
     }
     perror(0);
 }
References __progname, ap, fprintf(), fputs, perror(), stderr, and vfprintf().
Referenced by verr(), and warn().
vwarnx()
void vwarnx (const char * fmt, va_list ap)
Definition at line 18 of file err.c.
 {
     fprintf (stderr, "%s: ", __progname);
     if (fmt) vfprintf(stderr, fmt, ap);
     putc('\n', stderr);
 }
References __progname, ap, fprintf(), putc, stderr, and vfprintf().
Referenced by verrx(), and warnx().
warn()
void warn (const char * fmt, ...)
Definition at line 37 of file err.c.
 {
     va_list ap;
     va_start(ap, fmt);
     vwarn(fmt, ap);
     va_end(ap);
 }
References ap, va_end, va_start, and vwarn().
warnx()
void warnx (const char * fmt, ...)
Definition at line 45 of file err.c.
 {
     va_list ap;
     va_start(ap, fmt);
     vwarnx(fmt, ap);
     va_end(ap);
 }
References ap, va_end, va_start, and vwarnx().
Variable Documentation
__progname
char* __progname extern
Definition at line 6 of file libc.c.
Referenced by __init_libc(), vwarn(), and vwarnx().