Fennix Kernel: Time::HighPrecisionEventTimer Class Reference
Time::HighPrecisionEventTimer Class Reference
#include <time.hpp>
Data Structures
struct HPET
Public Member Functions
bool Sleep (uint64_t Duration, Units Unit)
uint64_t GetCounter ()
uint64_t CalculateTarget (uint64_t Target, Units Unit)
uint64_t GetNanosecondsSinceClassCreation ()
HighPrecisionEventTimer (void *hpet)
~HighPrecisionEventTimer ()
Private Member Functions
uint64_t ConvertUnit (Units Unit)
Private Attributes
uint32_t clk = 0
HPET * hpet = nullptr
uint64_t ClassCreationTime = 0
Detailed Description
Definition at line 50 of file time.hpp.
Data Structure Documentation
Time::HighPrecisionEventTimer::HPET
struct Time::HighPrecisionEventTimer::HPET
Definition at line 53 of file time.hpp.
Data Fields
uintptr_t GeneralCapabilities
uintptr_t GeneralConfiguration
uintptr_t GeneralIntStatus
uintptr_t MainCounterValue
uintptr_t Reserved0
uintptr_t Reserved1
uintptr_t Reserved2
uintptr_t Reserved3[24]
uintptr_t Reserved4
Constructor & Destructor Documentation
HighPrecisionEventTimer()
Time::HighPrecisionEventTimer::HighPrecisionEventTimer (void * hpet)
Definition at line 79 of file HighPrecisionEventTimer.cpp.
     {
 #if defined(a86)
         ACPI::ACPI::HPETHeader *HPET_HDR = (ACPI::ACPI::HPETHeader *)hpet;
         Memory::Virtual().Remap((void *)HPET_HDR->Address.Address,
                                 (void *)HPET_HDR->Address.Address,
                                 Memory::PTFlag::RW | Memory::PTFlag::PCD);
         this->hpet = (HPET *)HPET_HDR->Address.Address;
         trace("%s timer is at address %016p", HPET_HDR->Header.OEMID, (void *)HPET_HDR->Address.Address);
         clk = s_cst(uint32_t, (uint64_t)this->hpet->GeneralCapabilities >> 32);
 #ifdef a64
         mmoutq(&this->hpet->GeneralConfiguration, 0);
         mmoutq(&this->hpet->MainCounterValue, 0);
         mmoutq(&this->hpet->GeneralConfiguration, 1);
 #else
         mmoutl(&this->hpet->GeneralConfiguration, 0);
         mmoutl(&this->hpet->MainCounterValue, 0);
         mmoutl(&this->hpet->GeneralConfiguration, 1);
 #endif
         ClassCreationTime = this->GetCounter();
 #endif
     }
References ACPI::ACPI::GenericAddressStructure::Address, ACPI::ACPI::HPETHeader::Address, ClassCreationTime, clk, GetCounter(), ACPI::ACPI::HPETHeader::Header, hpet, ACPI::ACPI::ACPIHeader::OEMID, and trace.
~HighPrecisionEventTimer()
Time::HighPrecisionEventTimer::~HighPrecisionEventTimer ()
Definition at line 102 of file HighPrecisionEventTimer.cpp.
     {
     }
Member Function Documentation
CalculateTarget()
uint64_t Time::HighPrecisionEventTimer::CalculateTarget (uint64_t Target, Units Unit)
Definition at line 60 of file HighPrecisionEventTimer.cpp.
     {
 #if defined(a64)
         return mminq(&((HPET *)hpet)->MainCounterValue) + (Target * ConvertUnit(Unit)) / clk;
 #elif defined(a32)
         return mminl(&((HPET *)hpet)->MainCounterValue) + (Target * ConvertUnit(Unit)) / clk;
 #endif
     }
References clk, ConvertUnit(), and hpet.
Referenced by Time::time::CalculateTarget().
ConvertUnit()
uint64_t Time::HighPrecisionEventTimer::ConvertUnit (Units Unit) inline private
Definition at line 70 of file time.hpp.
         {
             switch (Unit)
             {
             case Femtoseconds:
                 return 1;
             case Picoseconds:
                 return 1000;
             case Nanoseconds:
                 return 1000000;
             case Microseconds:
                 return 1000000000;
             case Milliseconds:
                 return 1000000000000;
             case Seconds:
                 return 1000000000000000;
             case Minutes:
                 return 1000000000000000000;
             // case Hours:
             //     return 1000000000000000000000;
             // case Days:
             //     return 1000000000000000000000000;
             // case Months:
             //     return 1000000000000000000000000000;
             // case Years:
             //     return 1000000000000000000000000000000;
             default:
                 error("Invalid time unit %d", Unit);
                 return 1;
             }
         }
References error, Time::Femtoseconds, Time::Microseconds, Time::Milliseconds, Time::Minutes, Time::Nanoseconds, Time::Picoseconds, and Time::Seconds.
Referenced by CalculateTarget(), GetNanosecondsSinceClassCreation(), and Sleep().
GetCounter()
uint64_t Time::HighPrecisionEventTimer::GetCounter ()
Definition at line 51 of file HighPrecisionEventTimer.cpp.
     {
 #if defined(a64)
         return mminq(&((HPET *)hpet)->MainCounterValue);
 #elif defined(a32)
         return mminl(&((HPET *)hpet)->MainCounterValue);
 #endif
     }
References hpet.
Referenced by Time::time::GetCounter(), GetNanosecondsSinceClassCreation(), and HighPrecisionEventTimer().
GetNanosecondsSinceClassCreation()
uint64_t Time::HighPrecisionEventTimer::GetNanosecondsSinceClassCreation ()
Definition at line 69 of file HighPrecisionEventTimer.cpp.
     {
 #if defined(a86)
         uint64_t Subtraction = this->GetCounter() - this->ClassCreationTime;
         if (Subtraction <= 0 || this->clk <= 0)
             return 0;
         return Subtraction / (this->clk / ConvertUnit(Units::Nanoseconds));
 #endif
     }
References ClassCreationTime, clk, ConvertUnit(), GetCounter(), and Time::Nanoseconds.
Referenced by Time::time::GetNanosecondsSinceClassCreation().
Sleep()
bool Time::HighPrecisionEventTimer::Sleep (uint64_t Duration, Units Unit)
Definition at line 35 of file HighPrecisionEventTimer.cpp.
     {
 #if defined(a64)
         uint64_t Target = mminq(&((HPET *)hpet)->MainCounterValue) + (Duration * ConvertUnit(Unit)) / clk;
         while (mminq(&((HPET *)hpet)->MainCounterValue) < Target)
             CPU::Pause();
         return true;
 #elif defined(a32)
         uint64_t Target = mminl(&((HPET *)hpet)->MainCounterValue) + (Duration * ConvertUnit(Unit)) / clk;
         while (mminl(&((HPET *)hpet)->MainCounterValue) < Target)
             CPU::Pause();
         return true;
 #endif
 return false;
     }
References clk, ConvertUnit(), hpet, and CPU::Pause().
Referenced by Time::time::Sleep().
Field Documentation
ClassCreationTime
uint64_t Time::HighPrecisionEventTimer::ClassCreationTime = 0 private
Definition at line 68 of file time.hpp.
Referenced by GetNanosecondsSinceClassCreation(), and HighPrecisionEventTimer().
clk
uint32_t Time::HighPrecisionEventTimer::clk = 0 private
Definition at line 66 of file time.hpp.
Referenced by CalculateTarget(), GetNanosecondsSinceClassCreation(), HighPrecisionEventTimer(), and Sleep().
hpet
HPET* Time::HighPrecisionEventTimer::hpet = nullptr private
Definition at line 67 of file time.hpp.
Referenced by CalculateTarget(), GetCounter(), HighPrecisionEventTimer(), and Sleep().
The documentation for this class was generated from the following files:
Kernel/include/time.hpp
Kernel/Core/Time/HighPrecisionEventTimer.cpp