Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/w_file.c File Reference
w_file.c File Reference
#include <stdio.h>
#include "config.h"
#include "doomtype.h"
#include "m_argv.h"
#include "w_file.h"
Functions
wad_file_t * W_OpenFile (char *path)
void W_CloseFile (wad_file_t *wad)
size_t W_Read (wad_file_t *wad, unsigned int offset, void *buffer, size_t buffer_len)
Variables
wad_file_class_t stdc_wad_file
static wad_file_class_t * wad_file_classes []
Function Documentation
W_CloseFile()
void W_CloseFile (wad_file_t * wad)
Definition at line 85 of file w_file.c.
 {
     wad->file_class->CloseFile(wad);
 }
References wad_file_class_t::CloseFile, and _wad_file_s::file_class.
W_OpenFile()
wad_file_t* W_OpenFile (char * path)
Definition at line 53 of file w_file.c.
 {
     wad_file_t *result;
     int i;
     // Use the OS's virtual memory subsystem to map WAD files
     // directly into memory.
     //
     if (!M_CheckParm("-mmap"))
     {
         return stdc_wad_file.OpenFile(path);
     }
     // Try all classes in order until we find one that works
     result = NULL;
     for (i = 0; i < arrlen(wad_file_classes); ++i)
     {
         result = wad_file_classes[i]->OpenFile(path);
         if (result != NULL)
         {
             break;
         }
     }
     return result;
 }
References arrlen, i, M_CheckParm(), NULL, wad_file_class_t::OpenFile, stdc_wad_file, and wad_file_classes.
Referenced by W_AddFile().
W_Read()
size_t W_Read (wad_file_t * wad, unsigned int offset, void * buffer, size_t buffer_len)
Definition at line 90 of file w_file.c.
 {
     return wad->file_class->Read(wad, offset, buffer, buffer_len);
 }
References _wad_file_s::file_class, offset, and wad_file_class_t::Read.
Referenced by W_AddFile(), and W_ReadLump().
Variable Documentation
stdc_wad_file
wad_file_class_t stdc_wad_file extern
Initial value:
=
{
    W_StdC_OpenFile,
    W_StdC_CloseFile,
    W_StdC_Read,
}
Definition at line 89 of file w_file_stdc.c.
Referenced by W_OpenFile(), and W_StdC_OpenFile().
wad_file_classes
wad_file_class_t* wad_file_classes[] static
Initial value:
=
{
    &stdc_wad_file,
}
Definition at line 40 of file w_file.c.
Referenced by W_OpenFile().