Fennix Userspace: Userspace/musl/src/time/__tm_to_secs.c File Reference
__tm_to_secs.c File Reference
#include "time_impl.h"
Functions
long long __tm_to_secs (const struct tm *tm)
Function Documentation
__tm_to_secs()
long long __tm_to_secs (const struct tm * tm)
Definition at line 3 of file __tm_to_secs.c.
 {
     int is_leap;
     long long year = tm->tm_year;
     int month = tm->tm_mon;
     if (month >= 12 || month < 0) {
         int adj = month / 12;
         month %= 12;
         if (month < 0) {
             adj--;
             month += 12;
         }
         year += adj;
     }
     long long t = __year_to_secs(year, &is_leap);
     t += __month_to_secs(month, is_leap);
     t += 86400LL * (tm->tm_mday-1);
     t += 3600LL * tm->tm_hour;
     t += 60LL * tm->tm_min;
     t += tm->tm_sec;
     return t;
 }
References __month_to_secs(), __year_to_secs(), is_leap(), t, tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, and tm::tm_year.
Referenced by __strftime_fmt_1(), mktime(), and timegm().