Fennix Userspace: Userspace/apps/base/bash/lib/readline/search.c File Reference
search.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include "ansi_stdlib.h"
#include "rldefs.h"
#include "rlmbutil.h"
#include "readline.h"
#include "history.h"
#include "histlib.h"
#include "rlprivate.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define abs(x) (((x) >= 0) ? (x) : -(x))
Functions
static void make_history_line_current (HIST_ENTRY *)
static int noninc_search_from_pos (char *, int, int, int, int *)
static int noninc_dosearch (char *, int, int)
static int noninc_search (int, int)
static int rl_history_search_internal (int, int)
static void rl_history_search_reinit (int)
static _rl_search_cxt * _rl_nsearch_init (int, int)
static void _rl_nsearch_abort (_rl_search_cxt *)
static int _rl_nsearch_dispatch (_rl_search_cxt *, int)
int _rl_nsearch_cleanup (_rl_search_cxt *cxt, int r)
static int _rl_nsearch_dosearch (_rl_search_cxt *cxt)
int rl_noninc_forward_search (int count, int key)
int rl_noninc_reverse_search (int count, int key)
int rl_noninc_forward_search_again (int count, int key)
int rl_noninc_reverse_search_again (int count, int key)
int _rl_nsearch_callback (_rl_search_cxt *cxt)
int rl_history_search_forward (int count, int ignore)
int rl_history_search_backward (int count, int ignore)
int rl_history_substr_search_forward (int count, int ignore)
int rl_history_substr_search_backward (int count, int ignore)
Variables
_rl_search_cxt * _rl_nscxt = 0
static char * noninc_search_string = (char *) NULL
static int noninc_history_pos
static char * prev_line_found = (char *) NULL
static int _rl_history_search_len
int _rl_history_search_pos
static int _rl_history_search_flags
static char * history_search_string
static int history_string_size
Macro Definition Documentation
abs
#define abs (x) (((x) >= 0) ? (x) : -(x))
Definition at line 54 of file search.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file search.c.
Function Documentation
_rl_nsearch_abort()
static void _rl_nsearch_abort (_rl_search_cxt * cxt) static
Definition at line 273 of file search.c.
 {
   rl_maybe_unsave_line ();
   rl_point = cxt->save_point;
   rl_mark = cxt->save_mark;
   rl_restore_prompt ();
   rl_clear_message ();
   _rl_fix_point (1);
   RL_UNSETSTATE (RL_STATE_NSEARCH);
 }
References _rl_fix_point(), rl_clear_message(), rl_mark, rl_maybe_unsave_line(), rl_point, rl_restore_prompt(), RL_STATE_NSEARCH, RL_UNSETSTATE, __rl_search_context::save_mark, and __rl_search_context::save_point.
Referenced by _rl_nsearch_callback(), _rl_nsearch_dispatch(), and noninc_search().
_rl_nsearch_callback()
int _rl_nsearch_callback (_rl_search_cxt * cxt)
Definition at line 508 of file search.c.
 {
   int c, r;
   c = _rl_search_getchar (cxt);
   if (c <= 0)
     {
       if (c < 0)
         _rl_nsearch_abort (cxt);
       return 1;
     }
   r = _rl_nsearch_dispatch (cxt, c);
   if (r != 0)
     return 1;
   r = _rl_nsearch_dosearch (cxt);
   return ((r >= 0) ? _rl_nsearch_cleanup (cxt, r) : (r != 1));
 }
References _rl_nsearch_abort(), _rl_nsearch_cleanup(), _rl_nsearch_dispatch(), _rl_nsearch_dosearch(), _rl_search_getchar(), c, and r.
Referenced by rl_callback_read_char().
_rl_nsearch_cleanup()
int _rl_nsearch_cleanup (_rl_search_cxt * cxt, int r)
Definition at line 262 of file search.c.
 {
   _rl_scxt_dispose (cxt, 0);
   _rl_nscxt = 0;
   RL_UNSETSTATE(RL_STATE_NSEARCH);
   return (r != 1);
 }
References _rl_nscxt, _rl_scxt_dispose(), r, RL_STATE_NSEARCH, and RL_UNSETSTATE.
Referenced by _rl_nsearch_callback(), noninc_search(), and rl_callback_sigcleanup().
_rl_nsearch_dispatch()
static int _rl_nsearch_dispatch (_rl_search_cxt * cxt, int c) static
Definition at line 289 of file search.c.
 {
   int n;
   if (c < 0)
     c = CTRL ('C');
   switch (c)
     {
     case CTRL('W'):
       rl_unix_word_rubout (1, c);
       break;
     case CTRL('U'):
       rl_unix_line_discard (1, c);
       break;
     case RETURN:
     case NEWLINE:
       return 0;
     case CTRL('H'):
     case RUBOUT:
       if (rl_point == 0)
     {
       _rl_nsearch_abort (cxt);
       return -1;
     }
       _rl_rubout_char (1, c);
       break;
     case CTRL('C'):
     case CTRL('G'):
       rl_ding ();
       _rl_nsearch_abort (cxt);
       return -1;
     case ESC:
       /* XXX - experimental code to allow users to bracketed-paste into the
      search string. Similar code is in isearch.c:_rl_isearch_dispatch().
      The difference here is that the bracketed paste sometimes doesn't
      paste everything, so checking for the prefix and the suffix in the
      input queue doesn't work well. We just have to check to see if the
      number of chars in the input queue is enough for the bracketed paste
      prefix and hope for the best. */
       if (_rl_enable_bracketed_paste && ((n = _rl_nchars_available ()) >= (BRACK_PASTE_SLEN-1)))
     {
       if (_rl_read_bracketed_paste_prefix (c) == 1)
         rl_bracketed_paste_begin (1, c);
       else
         {
           c = rl_read_key ();   /* get the ESC that got pushed back */
           _rl_insert_char (1, c);
         }
         }
       else
         _rl_insert_char (1, c);
       break;
     default:
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     rl_insert_text (cxt->mb);
       else
 #endif
     _rl_insert_char (1, c);
       break;
     }
   (*rl_redisplay_function) ();
   rl_deactivate_mark ();
   return 1;
 }
References _rl_enable_bracketed_paste, _rl_insert_char(), _rl_nchars_available(), _rl_nsearch_abort(), _rl_read_bracketed_paste_prefix(), _rl_rubout_char(), BRACK_PASTE_SLEN, c, CTRL, ESC, MB_CUR_MAX, n, NEWLINE, RETURN, rl_bracketed_paste_begin(), rl_byte_oriented, rl_deactivate_mark(), rl_ding(), rl_insert_text(), rl_point, rl_read_key(), rl_unix_line_discard(), rl_unix_word_rubout(), and RUBOUT.
Referenced by _rl_nsearch_callback(), and noninc_search().
_rl_nsearch_dosearch()
static int _rl_nsearch_dosearch (_rl_search_cxt * cxt) static
Definition at line 368 of file search.c.
 {
   rl_mark = cxt->save_mark;
   /* If rl_point == 0, we want to re-use the previous search string and
      start from the saved history position.  If there's no previous search
      string, punt. */
   if (rl_point == 0)
     {
       if (noninc_search_string == 0)
     {
       rl_ding ();
       rl_restore_prompt ();
       RL_UNSETSTATE (RL_STATE_NSEARCH);
       return -1;
     }
     }
   else
     {
       /* We want to start the search from the current history position. */
       noninc_history_pos = cxt->save_line;
       FREE (noninc_search_string);
       noninc_search_string = savestring (rl_line_buffer);
       /* If we don't want the subsequent undo list generated by the search
      matching a history line to include the contents of the search string,
      we need to clear rl_line_buffer here.  For now, we just clear the
      undo list generated by reading the search string.  (If the search
      fails, the old undo list will be restored by rl_maybe_unsave_line.) */
       rl_free_undo_list ();
     }
   rl_restore_prompt ();
   return (noninc_dosearch (noninc_search_string, cxt->direction, cxt->sflags&SF_PATTERN));
 }
References __rl_search_context::direction, FREE, noninc_dosearch(), noninc_history_pos, noninc_search_string, rl_ding(), rl_free_undo_list(), rl_line_buffer, rl_mark, rl_point, rl_restore_prompt(), RL_STATE_NSEARCH, RL_UNSETSTATE, __rl_search_context::save_line, __rl_search_context::save_mark, savestring(), SF_PATTERN, and __rl_search_context::sflags.
Referenced by _rl_nsearch_callback(), and noninc_search().
_rl_nsearch_init()
static _rl_search_cxt * _rl_nsearch_init (int dir, int pchar) static
Definition at line 223 of file search.c.
 {
   _rl_search_cxt *cxt;
   char *p;
   cxt = _rl_scxt_alloc (RL_SEARCH_NSEARCH, 0);
   if (dir < 0)
     cxt->sflags |= SF_REVERSE;      /* not strictly needed */
 #if defined (VI_MODE)
   if (VI_COMMAND_MODE() && (pchar == '?' || pchar == '/'))
     cxt->sflags |= SF_PATTERN;
 #endif
   cxt->direction = dir;
   cxt->history_pos = cxt->save_line;
   rl_maybe_save_line ();
   /* Clear the undo list, since reading the search string should create its
      own undo list, and the whole list will end up being freed when we
      finish reading the search string. */
   rl_undo_list = 0;
   /* Use the line buffer to read the search string. */
   rl_line_buffer[0] = 0;
   rl_end = rl_point = 0;
   p = _rl_make_prompt_for_search (pchar ? pchar : ':');
   rl_message ("%s", p);
   xfree (p);
   RL_SETSTATE(RL_STATE_NSEARCH);
   _rl_nscxt = cxt;
   return cxt;
 }
References _rl_make_prompt_for_search(), _rl_nscxt, _rl_scxt_alloc(), __rl_search_context::direction, __rl_search_context::history_pos, p, rl_end, rl_line_buffer, rl_maybe_save_line(), rl_message(), rl_point, RL_SEARCH_NSEARCH, RL_SETSTATE, RL_STATE_NSEARCH, rl_undo_list, __rl_search_context::save_line, SF_PATTERN, SF_REVERSE, __rl_search_context::sflags, VI_COMMAND_MODE, and xfree.
Referenced by noninc_search().
make_history_line_current()
static void make_history_line_current (HIST_ENTRY * entry) static
Definition at line 85 of file search.c.
 {
   UNDO_LIST *xlist;
   xlist = _rl_saved_line_for_history ? (UNDO_LIST *)_rl_saved_line_for_history->data : 0;
   /* At this point, rl_undo_list points to a private search string list. */
   if (rl_undo_list && rl_undo_list != (UNDO_LIST *)entry->data && rl_undo_list != xlist)
     rl_free_undo_list ();
   /* Now we create a new undo list with a single insert for this text.
      WE DON'T CHANGE THE ORIGINAL HISTORY ENTRY UNDO LIST */
   _rl_replace_text (entry->line, 0, rl_end);
   _rl_fix_point (1);
 #if defined (VI_MODE)
   if (rl_editing_mode == vi_mode)
     /* POSIX.2 says that the `U' command doesn't affect the copy of any
        command lines to the edit line.  We're going to implement that by
        making the undo list start after the matching line is copied to the
        current editing buffer. */
     rl_free_undo_list ();
 #endif
   /* This will need to free the saved undo list associated with the original
      (pre-search) line buffer.
      XXX - look at _rl_free_saved_history_line and consider calling it if
      rl_undo_list != xlist (or calling rl_free_undo list directly on
      _rl_saved_line_for_history->data) */
   if (_rl_saved_line_for_history)
     _rl_free_history_entry (_rl_saved_line_for_history);
   _rl_saved_line_for_history = (HIST_ENTRY *)NULL;
 }
References _rl_fix_point(), _rl_free_history_entry(), _rl_replace_text(), _rl_saved_line_for_history, _hist_entry::data, entry::data, if(), NULL, rl_editing_mode, rl_end, rl_free_undo_list(), rl_undo_list, and vi_mode.
Referenced by noninc_dosearch(), and rl_history_search_internal().
noninc_dosearch()
static int noninc_dosearch (char * string, int dir, int flags) static
Definition at line 169 of file search.c.
 {
   int oldpos, pos, ind;
   HIST_ENTRY *entry;
   if (string == 0 || *string == '\0' || noninc_history_pos < 0)
     {
       rl_ding ();
       return 0;
     }
   pos = noninc_search_from_pos (string, noninc_history_pos + dir, dir, flags, &ind);
   if (pos == -1)
     {
       /* Search failed, current history position unchanged. */
       rl_maybe_unsave_line ();
       rl_clear_message ();
       rl_point = 0;
       rl_ding ();
       return 0;
     }
   noninc_history_pos = pos;
   oldpos = where_history ();
   history_set_pos (noninc_history_pos);
   entry = current_history ();       /* will never be NULL after successful search */
 #if defined (VI_MODE)
   if (rl_editing_mode != vi_mode)
 #endif
     history_set_pos (oldpos);
   make_history_line_current (entry);
   if (_rl_enable_active_region && ((flags & SF_PATTERN) == 0) && ind > 0 && ind < rl_end)
     {
       rl_point = ind;
       rl_mark = ind + strlen (string);
       if (rl_mark > rl_end)
     rl_mark = rl_end;   /* can't happen? */
       rl_activate_mark ();
     }
   else
     {
       rl_point = 0;
       rl_mark = rl_end;
     }
   rl_clear_message ();
   return 1;
 }
References _rl_enable_active_region, current_history(), flags, history_set_pos(), make_history_line_current(), noninc_history_pos, noninc_search_from_pos(), pos, rl_activate_mark(), rl_clear_message(), rl_ding(), rl_editing_mode, rl_end, rl_mark, rl_maybe_unsave_line(), rl_point, SF_PATTERN, strlen(), vi_mode, and where_history().
Referenced by _rl_nsearch_dosearch(), rl_noninc_forward_search_again(), and rl_noninc_reverse_search_again().
noninc_search()
static int noninc_search (int dir, int pchar) static
Definition at line 410 of file search.c.
 {
   _rl_search_cxt *cxt;
   int c, r;
   cxt = _rl_nsearch_init (dir, pchar);
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     return (0);
   /* Read the search string. */
   r = 0;
   while (1)
     {
       c = _rl_search_getchar (cxt);
       if (c < 0)
     {
       _rl_nsearch_abort (cxt);
       return 1;
     }
       if (c == 0)
     break;
       r = _rl_nsearch_dispatch (cxt, c);
       if (r < 0)
         return 1;
       else if (r == 0)
     break;
     }
   r = _rl_nsearch_dosearch (cxt);
   return ((r >= 0) ? _rl_nsearch_cleanup (cxt, r) : (r != 1));
 }
References _rl_nsearch_abort(), _rl_nsearch_cleanup(), _rl_nsearch_dispatch(), _rl_nsearch_dosearch(), _rl_nsearch_init(), _rl_search_getchar(), c, r, RL_ISSTATE, and RL_STATE_CALLBACK.
Referenced by rl_noninc_forward_search(), and rl_noninc_reverse_search().
noninc_search_from_pos()
static int noninc_search_from_pos (char * string, int pos, int dir, int flags, int * ncp) static
Definition at line 123 of file search.c.
 {
   int ret, old, sflags;
   char *s;
   if (pos < 0)
     return -1;
   old = where_history ();
   if (history_set_pos (pos) == 0)
     return -1;
   RL_SETSTATE(RL_STATE_SEARCH);
   /* These functions return the match offset in the line; history_offset gives
      the matching line in the history list */
   if (flags & SF_PATTERN)
     {
       s = string;
       sflags = 0;       /* Non-anchored search */
       if (*s == '^')
     {
       sflags |= ANCHORED_SEARCH;
       s++;
     }
       ret = _hs_history_patsearch (s, dir, sflags);
     }
   else if (*string == '^')
     ret = history_search_prefix (string + 1, dir);
   else
     ret = history_search (string, dir);
   RL_UNSETSTATE(RL_STATE_SEARCH);
   if (ncp)
     *ncp = ret;     /* caller will catch -1 to indicate no-op */
   if (ret != -1)
     ret = where_history ();
   history_set_pos (old);
   return (ret);
 }
References _hs_history_patsearch(), ANCHORED_SEARCH, flags, history_search(), history_search_prefix(), history_set_pos(), pos, ret, RL_SETSTATE, RL_STATE_SEARCH, RL_UNSETSTATE, SF_PATTERN, string, and where_history().
Referenced by noninc_dosearch(), and rl_history_search_internal().
rl_history_search_backward()
int rl_history_search_backward (int count, int ignore)
Definition at line 658 of file search.c.
 {
   if (count == 0)
     return (0);
   if (rl_last_func != rl_history_search_forward &&
       rl_last_func != rl_history_search_backward)
     rl_history_search_reinit (ANCHORED_SEARCH);
   if (_rl_history_search_len == 0)
     return (rl_get_previous_history (count, ignore));
   return (rl_history_search_internal (abs (count), (count > 0) ? -1 : 1));
 }
References _rl_history_search_len, abs, ANCHORED_SEARCH, count, rl_get_previous_history(), rl_history_search_backward(), rl_history_search_forward(), rl_history_search_internal(), rl_history_search_reinit(), and rl_last_func.
Referenced by bind_termcap_arrow_keys(), rl_history_search_backward(), and rl_history_search_forward().
rl_history_search_forward()
int rl_history_search_forward (int count, int ignore)
Definition at line 640 of file search.c.
 {
   if (count == 0)
     return (0);
   if (rl_last_func != rl_history_search_forward &&
       rl_last_func != rl_history_search_backward)
     rl_history_search_reinit (ANCHORED_SEARCH);
   if (_rl_history_search_len == 0)
     return (rl_get_next_history (count, ignore));
   return (rl_history_search_internal (abs (count), (count > 0) ? 1 : -1));
 }
References _rl_history_search_len, abs, ANCHORED_SEARCH, count, rl_get_next_history(), rl_history_search_backward(), rl_history_search_forward(), rl_history_search_internal(), rl_history_search_reinit(), and rl_last_func.
Referenced by bind_termcap_arrow_keys(), rl_history_search_backward(), and rl_history_search_forward().
rl_history_search_internal()
static int rl_history_search_internal (int count, int dir) static
Definition at line 529 of file search.c.
 {
   HIST_ENTRY *temp;
   int ret, oldpos, newcol;
   int had_saved_line;
   char *t;
   had_saved_line = _rl_saved_line_for_history != 0;
   rl_maybe_save_line ();
   temp = (HIST_ENTRY *)NULL;
   /* Search COUNT times through the history for a line matching
      history_search_string.  If history_search_string[0] == '^', the
      line must match from the start; otherwise any substring can match.
      When this loop finishes, TEMP, if non-null, is the history line to
      copy into the line buffer. */
   while (count)
     {
       RL_CHECK_SIGNALS ();
       ret = noninc_search_from_pos (history_search_string, _rl_history_search_pos + dir, dir, 0, &newcol);
       if (ret == -1)
     break;
       /* Get the history entry we found. */
       _rl_history_search_pos = ret;
       oldpos = where_history ();
       history_set_pos (_rl_history_search_pos);
       temp = current_history ();    /* will never be NULL after successful search */
       history_set_pos (oldpos);
       /* Don't find multiple instances of the same line. */
       if (prev_line_found && STREQ (prev_line_found, temp->line))
         continue;
       prev_line_found = temp->line;
       count--;
     }
   /* If we didn't find anything at all, return. */
   if (temp == 0)
     {
       /* XXX - check had_saved_line here? */
       rl_maybe_unsave_line ();
       rl_ding ();
       /* If you don't want the saved history line (last match) to show up
          in the line buffer after the search fails, change the #if 0 to
          #if 1 */
 #if 0
       if (rl_point > _rl_history_search_len)
         {
           rl_point = rl_end = _rl_history_search_len;
           rl_line_buffer[rl_end] = '\0';
           rl_mark = 0;
         }
 #else
       rl_point = _rl_history_search_len;    /* rl_maybe_unsave_line changes it */
       rl_mark = rl_end;
 #endif
       return 1;
     }
   /* Copy the line we found into the current line buffer. */
   make_history_line_current (temp);
   /* decide where to put rl_point -- need to change this for pattern search */
   if (_rl_history_search_flags & ANCHORED_SEARCH)
     rl_point = _rl_history_search_len;  /* easy case */
   else
     {
 #if 0
       t = strstr (rl_line_buffer, history_search_string);   /* XXX */
       rl_point = t ? (int)(t - rl_line_buffer) + _rl_history_search_len : rl_end;
 #else
       rl_point = (newcol >= 0) ? newcol : rl_end;
 #endif
     }
   rl_mark = rl_end;
   return 0;
 }
References _rl_history_search_flags, _rl_history_search_len, _rl_history_search_pos, _rl_saved_line_for_history, ANCHORED_SEARCH, count, current_history(), history_search_string, history_set_pos(), int, _hist_entry::line, make_history_line_current(), noninc_search_from_pos(), NULL, prev_line_found, ret, RL_CHECK_SIGNALS, rl_ding(), rl_end, rl_line_buffer, rl_mark, rl_maybe_save_line(), rl_maybe_unsave_line(), rl_point, STREQ, strstr(), t, and where_history().
Referenced by rl_history_search_backward(), rl_history_search_forward(), rl_history_substr_search_backward(), and rl_history_substr_search_forward().
rl_history_search_reinit()
static void rl_history_search_reinit (int flags) static
Definition at line 610 of file search.c.
 {
   int sind;
   _rl_history_search_pos = where_history ();
   _rl_history_search_len = rl_point;
   _rl_history_search_flags = flags;
   prev_line_found = (char *)NULL;
   if (rl_point)
     {
       /* Allocate enough space for anchored and non-anchored searches */
       if (_rl_history_search_len >= history_string_size - 2)
     {
       history_string_size = _rl_history_search_len + 2;
       history_search_string = (char *)xrealloc (history_search_string, history_string_size);
     }
       sind = 0;
       if (flags & ANCHORED_SEARCH)
     history_search_string[sind++] = '^';
       strncpy (history_search_string + sind, rl_line_buffer, rl_point);
       history_search_string[rl_point + sind] = '\0';
     }
   _rl_free_saved_history_line ();   /* XXX rl_undo_list? */
 }
References _rl_free_saved_history_line(), _rl_history_search_flags, _rl_history_search_len, _rl_history_search_pos, ANCHORED_SEARCH, flags, history_search_string, history_string_size, NULL, prev_line_found, rl_line_buffer, rl_point, strncpy(), where_history(), and xrealloc.
Referenced by rl_history_search_backward(), rl_history_search_forward(), rl_history_substr_search_backward(), and rl_history_substr_search_forward().
rl_history_substr_search_backward()
int rl_history_substr_search_backward (int count, int ignore)
Definition at line 695 of file search.c.
 {
   if (count == 0)
     return (0);
   if (rl_last_func != rl_history_substr_search_forward &&
       rl_last_func != rl_history_substr_search_backward)
     rl_history_search_reinit (NON_ANCHORED_SEARCH);
   if (_rl_history_search_len == 0)
     return (rl_get_previous_history (count, ignore));
   return (rl_history_search_internal (abs (count), (count > 0) ? -1 : 1));
 }
References _rl_history_search_len, abs, count, NON_ANCHORED_SEARCH, rl_get_previous_history(), rl_history_search_internal(), rl_history_search_reinit(), rl_history_substr_search_backward(), rl_history_substr_search_forward(), and rl_last_func.
Referenced by rl_history_substr_search_backward(), and rl_history_substr_search_forward().
rl_history_substr_search_forward()
int rl_history_substr_search_forward (int count, int ignore)
Definition at line 677 of file search.c.
 {
   if (count == 0)
     return (0);
   if (rl_last_func != rl_history_substr_search_forward &&
       rl_last_func != rl_history_substr_search_backward)
     rl_history_search_reinit (NON_ANCHORED_SEARCH);
   if (_rl_history_search_len == 0)
     return (rl_get_next_history (count, ignore));
   return (rl_history_search_internal (abs (count), (count > 0) ? 1 : -1));
 }
References _rl_history_search_len, abs, count, NON_ANCHORED_SEARCH, rl_get_next_history(), rl_history_search_internal(), rl_history_search_reinit(), rl_history_substr_search_backward(), rl_history_substr_search_forward(), and rl_last_func.
Referenced by rl_history_substr_search_backward(), and rl_history_substr_search_forward().
rl_noninc_forward_search()
int rl_noninc_forward_search (int count, int key)
Definition at line 449 of file search.c.
 {
   return noninc_search (1, (key == '?') ? '?' : 0);
 }
References noninc_search().
Referenced by rl_vi_search().
rl_noninc_forward_search_again()
int rl_noninc_forward_search_again (int count, int key)
Definition at line 466 of file search.c.
 {
   int r;
   if (!noninc_search_string)
     {
       rl_ding ();
       return (1);
     }
 #if defined (VI_MODE)
   if (VI_COMMAND_MODE() && key == 'N')
     r = noninc_dosearch (noninc_search_string, 1, SF_PATTERN);
   else
 #endif
     r = noninc_dosearch (noninc_search_string, 1, 0);
   return (r != 1);
 }
References noninc_dosearch(), noninc_search_string, r, rl_ding(), SF_PATTERN, and VI_COMMAND_MODE.
Referenced by rl_vi_search_again().
rl_noninc_reverse_search()
int rl_noninc_reverse_search (int count, int key)
Definition at line 457 of file search.c.
 {
   return noninc_search (-1, (key == '/') ? '/' : 0);
 }
References noninc_search().
Referenced by rl_vi_search().
rl_noninc_reverse_search_again()
int rl_noninc_reverse_search_again (int count, int key)
Definition at line 488 of file search.c.
 {
   int r;
   if (!noninc_search_string)
     {
       rl_ding ();
       return (1);
     }
 #if defined (VI_MODE)
   if (VI_COMMAND_MODE() && key == 'n')
     r = noninc_dosearch (noninc_search_string, -1, SF_PATTERN);
   else
 #endif
     r = noninc_dosearch (noninc_search_string, -1, 0);
   return (r != 1);
 }
References noninc_dosearch(), noninc_search_string, r, rl_ding(), SF_PATTERN, and VI_COMMAND_MODE.
Referenced by rl_vi_search_again().
Variable Documentation
_rl_history_search_flags
int _rl_history_search_flags static
Definition at line 65 of file search.c.
Referenced by rl_history_search_internal(), and rl_history_search_reinit().
_rl_history_search_len
int _rl_history_search_len static
Definition at line 63 of file search.c.
Referenced by rl_history_search_backward(), rl_history_search_forward(), rl_history_search_internal(), rl_history_search_reinit(), rl_history_substr_search_backward(), and rl_history_substr_search_forward().
_rl_history_search_pos
int _rl_history_search_pos
Definition at line 64 of file search.c.
Referenced by _rl_start_using_history(), rl_history_search_internal(), and rl_history_search_reinit().
_rl_nscxt
_rl_search_cxt* _rl_nscxt = 0
Definition at line 56 of file search.c.
Referenced by _rl_nsearch_cleanup(), _rl_nsearch_init(), rl_callback_read_char(), and rl_callback_sigcleanup().
history_search_string
char* history_search_string static
Definition at line 67 of file search.c.
Referenced by rl_history_search_internal(), and rl_history_search_reinit().
history_string_size
int history_string_size static
Definition at line 68 of file search.c.
Referenced by rl_history_search_reinit().
noninc_history_pos
int noninc_history_pos static
Definition at line 59 of file search.c.
Referenced by _rl_nsearch_dosearch(), and noninc_dosearch().
noninc_search_string
char* noninc_search_string = (char *) NULL static
Definition at line 58 of file search.c.
Referenced by _rl_nsearch_dosearch(), rl_noninc_forward_search_again(), and rl_noninc_reverse_search_again().
prev_line_found
char* prev_line_found = (char *) NULL static
Definition at line 61 of file search.c.
Referenced by rl_history_search_internal(), and rl_history_search_reinit().