Fennix: Kernel/Architecture/i686/ArithmeticOperations.c File Reference
ArithmeticOperations.c File Reference
Data Structures
union arith64_word
struct arith64_word.u32
struct arith64_word.s32
Macros
#define arith64_u64 unsigned long long int
#define arith64_s64 signed long long int
#define arith64_u32 unsigned int
#define arith64_s32 int
#define arith64_hi(n) (arith64_word){.u64 = n}.u32.hi
#define arith64_lo(n) (arith64_word){.u64 = n}.u32.lo
#define arith64_neg(a, b) (((a) ^ ((((arith64_s64)(b)) >= 0) - 1)) + (((arith64_s64)(b)) < 0))
#define arith64_abs(a) arith64_neg(a, a)
Functions
arith64_s64 __absvdi2 (arith64_s64 a)
arith64_s64 __ashldi3 (arith64_s64 a, int b)
arith64_s64 __ashrdi3 (arith64_s64 a, int b)
int __clzsi2 (arith64_u32 a)
int __clzdi2 (arith64_u64 a)
int __ctzsi2 (arith64_u32 a)
int __ctzdi2 (arith64_u64 a)
arith64_u64 __divmoddi4 (arith64_u64 a, arith64_u64 b, arith64_u64 *c)
arith64_s64 __divdi3 (arith64_s64 a, arith64_s64 b)
int __ffsdi2 (arith64_u64 a)
arith64_u64 __lshrdi3 (arith64_u64 a, int b)
arith64_s64 __moddi3 (arith64_s64 a, arith64_s64 b)
int __popcountsi2 (arith64_u32 a)
int __popcountdi2 (arith64_u64 a)
arith64_u64 __udivdi3 (arith64_u64 a, arith64_u64 b)
arith64_u64 __umoddi3 (arith64_u64 a, arith64_u64 b)
double __adddf3 (double a, double b)
double __muldf3 (double a, double b)
double __floatsidf (int i)
int __ltdf2 (double a, double b)
int __gtdf2 (double a, double b)
int __nedf2 (double a, double b)
int __eqdf2 (double a, double b)
double __floatdidf (long i)
double __divdf3 (double a, double b)
double __subdf3 (double a, double b)
int __gedf2 (double a, double b)
int __fixdfsi (double a)
long __fixdfdi (double a)
int __ledf2 (double a, double b)
Data Structure Documentation
arith64_word
union arith64_word
Definition at line 7 of file ArithmeticOperations.c.
Data Fields
struct arith64_word s32
arith64_s64 s64
struct arith64_word u32
arith64_u64 u64
arith64_word.u32
struct arith64_word.u32
Definition at line 11 of file ArithmeticOperations.c.
Data Fields
arith64_u32 hi
arith64_u32 lo
arith64_word.s32
struct arith64_word.s32
Definition at line 21 of file ArithmeticOperations.c.
Data Fields
arith64_s32 hi
arith64_s32 lo
Macro Definition Documentation
arith64_abs
#define arith64_abs (a) arith64_neg(a, a)
Definition at line 36 of file ArithmeticOperations.c.
arith64_hi
#define arith64_hi (n) (arith64_word){.u64 = n}.u32.hi
Definition at line 33 of file ArithmeticOperations.c.
arith64_lo
#define arith64_lo (n) (arith64_word){.u64 = n}.u32.lo
Definition at line 34 of file ArithmeticOperations.c.
arith64_neg
#define arith64_neg (a, b) (((a) ^ ((((arith64_s64)(b)) >= 0) - 1)) + (((arith64_s64)(b)) < 0))
Definition at line 35 of file ArithmeticOperations.c.
arith64_s32
#define arith64_s32 int
Definition at line 5 of file ArithmeticOperations.c.
arith64_s64
#define arith64_s64 signed long long int
Definition at line 3 of file ArithmeticOperations.c.
arith64_u32
#define arith64_u32 unsigned int
Definition at line 4 of file ArithmeticOperations.c.
arith64_u64
#define arith64_u64 unsigned long long int
Definition at line 2 of file ArithmeticOperations.c.
Function Documentation
__absvdi2()
arith64_s64 __absvdi2 (arith64_s64 a)
Definition at line 38 of file ArithmeticOperations.c.
 {
     return arith64_abs(a);
 }
References arith64_abs.
__adddf3()
double __adddf3 (double a, double b)
Definition at line 272 of file ArithmeticOperations.c.
 { return a + b; }
__ashldi3()
arith64_s64 __ashldi3 (arith64_s64 a, int b)
Definition at line 43 of file ArithmeticOperations.c.
 {
     arith64_word w = {.s64 = a};
     b &= 63;
     if (b >= 32)
     {
         w.u32.hi = w.u32.lo << (b - 32);
         w.u32.lo = 0;
     }
     else if (b)
     {
         w.u32.hi = (w.u32.lo >> (32 - b)) | (w.u32.hi << b);
         w.u32.lo <<= b;
     }
     return w.s64;
 }
References arith64_word::s64, and arith64_word::u32.
__ashrdi3()
arith64_s64 __ashrdi3 (arith64_s64 a, int b)
Definition at line 62 of file ArithmeticOperations.c.
 {
     arith64_word w = {.s64 = a};
     b &= 63;
     if (b >= 32)
     {
         w.s32.lo = w.s32.hi >> (b - 32);
         w.s32.hi >>= 31; // 0xFFFFFFFF or 0
     }
     else if (b)
     {
         w.u32.lo = (w.u32.hi << (32 - b)) | (w.u32.lo >> b);
         w.s32.hi >>= b;
     }
     return w.s64;
 }
References arith64_word::s32, arith64_word::s64, and arith64_word::u32.
__clzdi2()
int __clzdi2 (arith64_u64 a)
Definition at line 99 of file ArithmeticOperations.c.
 {
     int b, n = 0;
     b = !(a & 0xffffffff00000000ULL) << 5;
     n += b;
     a <<= b;
     b = !(a & 0xffff000000000000ULL) << 4;
     n += b;
     a <<= b;
     b = !(a & 0xff00000000000000ULL) << 3;
     n += b;
     a <<= b;
     b = !(a & 0xf000000000000000ULL) << 2;
     n += b;
     a <<= b;
     b = !(a & 0xc000000000000000ULL) << 1;
     n += b;
     a <<= b;
     return n + !(a & 0x8000000000000000ULL);
 }
Referenced by __divmoddi4().
__clzsi2()
int __clzsi2 (arith64_u32 a)
Definition at line 81 of file ArithmeticOperations.c.
 {
     int b, n = 0;
     b = !(a & 0xffff0000) << 4;
     n += b;
     a <<= b;
     b = !(a & 0xff000000) << 3;
     n += b;
     a <<= b;
     b = !(a & 0xf0000000) << 2;
     n += b;
     a <<= b;
     b = !(a & 0xc0000000) << 1;
     n += b;
     a <<= b;
     return n + !(a & 0x80000000);
 }
__ctzdi2()
int __ctzdi2 (arith64_u64 a)
Definition at line 138 of file ArithmeticOperations.c.
 {
     int b, n = 0;
     b = !(a & 0x00000000ffffffffULL) << 5;
     n += b;
     a >>= b;
     b = !(a & 0x000000000000ffffULL) << 4;
     n += b;
     a >>= b;
     b = !(a & 0x00000000000000ffULL) << 3;
     n += b;
     a >>= b;
     b = !(a & 0x000000000000000fULL) << 2;
     n += b;
     a >>= b;
     b = !(a & 0x0000000000000003ULL) << 1;
     n += b;
     a >>= b;
     return n + !(a & 0x0000000000000001ULL);
 }
Referenced by __ffsdi2().
__ctzsi2()
int __ctzsi2 (arith64_u32 a)
Definition at line 120 of file ArithmeticOperations.c.
 {
     int b, n = 0;
     b = !(a & 0x0000ffff) << 4;
     n += b;
     a >>= b;
     b = !(a & 0x000000ff) << 3;
     n += b;
     a >>= b;
     b = !(a & 0x0000000f) << 2;
     n += b;
     a >>= b;
     b = !(a & 0x00000003) << 1;
     n += b;
     a >>= b;
     return n + !(a & 0x00000001);
 }
__divdf3()
double __divdf3 (double a, double b)
Definition at line 280 of file ArithmeticOperations.c.
 { return a / b; }
__divdi3()
arith64_s64 __divdi3 (arith64_s64 a, arith64_s64 b)
Definition at line 204 of file ArithmeticOperations.c.
 {
     arith64_u64 q = __divmoddi4(arith64_abs(a), arith64_abs(b), (void *)0);
     return arith64_neg(q, a ^ b);
 }
References __divmoddi4(), arith64_abs, arith64_neg, and arith64_u64.
__divmoddi4()
arith64_u64 __divmoddi4 (arith64_u64 a, arith64_u64 b, arith64_u64 * c)
Definition at line 159 of file ArithmeticOperations.c.
 {
     if (b > a) //
     {
         if (c)
             *c = a;
         return 0;
     }
     if (!arith64_hi(b))
     {
         if (b == 0)
         {
             volatile char x = 0;
             x = 1 / x;
         }
         if (b == 1)
         {
             if (c)
                 *c = 0;
             return a;
         }
         if (!arith64_hi(a))
         {
             if (c)
                 *c = arith64_lo(a) % arith64_lo(b);
             return arith64_lo(a) / arith64_lo(b);
         }
     }
     char bits = __clzdi2(b) - __clzdi2(a) + 1;
     arith64_u64 rem = a >> bits;
     a <<= 64 - bits;
     arith64_u64 wrap = 0;
     while (bits-- > 0)
     {
         rem = (rem << 1) | (a >> 63);
         a = (a << 1) | (wrap & 1);
         wrap = ((arith64_s64)(b - rem - 1) >> 63);
         rem -= b & wrap;
     }
     if (c)
         *c = rem;
     return (a << 1) | (wrap & 1);
 }
References __clzdi2(), arith64_hi, arith64_lo, arith64_s64, and arith64_u64.
Referenced by __divdi3(), __moddi3(), __udivdi3(), and __umoddi3().
__eqdf2()
int __eqdf2 (double a, double b)
Definition at line 278 of file ArithmeticOperations.c.
 { return a == b; }
__ffsdi2()
int __ffsdi2 (arith64_u64 a)
Definition at line 210 of file ArithmeticOperations.c.
 { return a ? __ctzdi2(a) + 1 : 0; }
References __ctzdi2().
__fixdfdi()
long __fixdfdi (double a)
Definition at line 284 of file ArithmeticOperations.c.
 { return (long)a; }
__fixdfsi()
int __fixdfsi (double a)
Definition at line 283 of file ArithmeticOperations.c.
 { return (int)a; }
__floatdidf()
double __floatdidf (long i)
Definition at line 279 of file ArithmeticOperations.c.
 { return (double)i; }
__floatsidf()
double __floatsidf (int i)
Definition at line 274 of file ArithmeticOperations.c.
 { return (double)i; }
__gedf2()
int __gedf2 (double a, double b)
Definition at line 282 of file ArithmeticOperations.c.
 { return a >= b; }
__gtdf2()
int __gtdf2 (double a, double b)
Definition at line 276 of file ArithmeticOperations.c.
 { return a > b; }
__ledf2()
int __ledf2 (double a, double b)
Definition at line 285 of file ArithmeticOperations.c.
 { return a <= b; }
__lshrdi3()
arith64_u64 __lshrdi3 (arith64_u64 a, int b)
Definition at line 212 of file ArithmeticOperations.c.
 {
     arith64_word w = {.u64 = a};
     b &= 63;
     if (b >= 32)
     {
         w.u32.lo = w.u32.hi >> (b - 32);
         w.u32.hi = 0;
     }
     else if (b)
     {
         w.u32.lo = (w.u32.hi << (32 - b)) | (w.u32.lo >> b);
         w.u32.hi >>= b;
     }
     return w.u64;
 }
References arith64_word::u32, and arith64_word::u64.
__ltdf2()
int __ltdf2 (double a, double b)
Definition at line 275 of file ArithmeticOperations.c.
 { return a < b; }
__moddi3()
arith64_s64 __moddi3 (arith64_s64 a, arith64_s64 b)
Definition at line 231 of file ArithmeticOperations.c.
 {
     arith64_u64 r;
     __divmoddi4(arith64_abs(a), arith64_abs(b), &r);
     return arith64_neg(r, a);
 }
References __divmoddi4(), arith64_abs, arith64_neg, and arith64_u64.
__muldf3()
double __muldf3 (double a, double b)
Definition at line 273 of file ArithmeticOperations.c.
 { return a * b; }
__nedf2()
int __nedf2 (double a, double b)
Definition at line 277 of file ArithmeticOperations.c.
 { return a != b; }
__popcountdi2()
int __popcountdi2 (arith64_u64 a)
Definition at line 249 of file ArithmeticOperations.c.
 {
     a = a - ((a >> 1) & 0x5555555555555555ULL);
     a = ((a >> 2) & 0x3333333333333333ULL) + (a & 0x3333333333333333ULL);
     a = (a + (a >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
     a = (a + (a >> 32));
     a = (a + (a >> 16));
     return (a + (a >> 8)) & 127;
 }
__popcountsi2()
int __popcountsi2 (arith64_u32 a)
Definition at line 238 of file ArithmeticOperations.c.
 {
     a = a - ((a >> 1) & 0x55555555);
     a = ((a >> 2) & 0x33333333) + (a & 0x33333333);
     a = (a + (a >> 4)) & 0x0F0F0F0F;
     a = (a + (a >> 16));
     return (a + (a >> 8)) & 63;
 }
__subdf3()
double __subdf3 (double a, double b)
Definition at line 281 of file ArithmeticOperations.c.
 { return a - b; }
__udivdi3()
arith64_u64 __udivdi3 (arith64_u64 a, arith64_u64 b)
Definition at line 261 of file ArithmeticOperations.c.
 { return __divmoddi4(a, b, (void *)0); }
References __divmoddi4().
__umoddi3()
arith64_u64 __umoddi3 (arith64_u64 a, arith64_u64 b)
Definition at line 263 of file ArithmeticOperations.c.
 {
     arith64_u64 r;
     __divmoddi4(a, b, &r);
     return r;
 }
References __divmoddi4(), and arith64_u64.