Fennix: Kernel/include/filesystem.hpp File Reference
filesystem.hpp File Reference
#include <types.h>
#include <smart_ptr.hpp>
#include <lock.hpp>
#include <errno.h>
#include <vector>
#include <atomic>
#include <string>
Data Structures
struct stat
Structure holding information about a file, as returned by the stat function.
struct stat64
Extended structure for large file support, holding information about a file.
class vfs::Node
class vfs::RefNode
class vfs::Virtual
class vfs::FileDescriptorTable
struct vfs::FileDescriptorTable::Fildes
Namespaces
vfs
Macros
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define S_IXOTH 0001
#define S_IWOTH 0002
#define S_IROTH 0004
#define S_IRWXO 0007
#define S_IXGRP 0010
#define S_IWGRP 0020
#define S_IRGRP 0040
#define S_IRWXG 0070
#define S_IXUSR 0100
#define S_IWUSR 0200
#define S_IRUSR 0400
#define S_IRWXU 0700
#define O_RDONLY 00
#define O_WRONLY 01
#define O_RDWR 02
#define O_CREAT 0100
#define O_EXCL 0200
#define O_TRUNC 01000
#define O_APPEND 02000
#define O_CLOEXEC 02000000
#define S_IFIFO 0010000
#define S_IFCHR 0020000
#define S_IFDIR 0040000
#define S_IFBLK 0060000
#define S_IFREG 0100000
#define S_IFLNK 0120000
#define S_IFSOCK 0140000
#define S_IFMT 0170000
#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)
#define S_ISCHR(mode) (((mode) & S_IFMT) == S_IFCHR)
#define S_ISBLK(mode) (((mode) & S_IFMT) == S_IFBLK)
#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)
#define S_ISFIFO(mode) (((mode) & S_IFMT) == S_IFIFO)
#define S_ISLNK(mode) (((mode) & S_IFMT) == S_IFLNK)
#define S_ISSOCK(mode) (((mode) & S_IFMT) == S_IFSOCK)
Enumerations
enum vfs::NodeType : mode_t {
vfs::NODE_TYPE_NONE = 0x0 , vfs::FILE = S_IFREG , vfs::DIRECTORY = S_IFDIR , vfs::CHARDEVICE = S_IFCHR ,
vfs::BLOCKDEVICE = S_IFBLK , vfs::PIPE = S_IFIFO , vfs::SYMLINK = S_IFLNK , vfs::MOUNTPOINT = S_IFDIR
}
Functions
static int ConvertFileFlags (const char *Mode)
int operator== (const Fildes &other)
int operator!= (const Fildes &other)
int fopen (const char *pathname, const char *mode)
int creat (const char *pathname, mode_t mode)
ssize_t fread (int fd, void *buf, size_t count)
ssize_t fwrite (int fd, const void *buf, size_t count)
int fclose (int fd)
off_t lseek (int fd, off_t offset, int whence)
int stat (const char *pathname, struct stat *statbuf)
int fstat (int fd, struct stat *statbuf)
int lstat (const char *pathname, struct stat *statbuf)
Variables
RefNode * Handle = nullptr
mode_t Mode = 0
int Flags = 0
int Descriptor = -1
Data Structure Documentation
stat
struct stat
Structure holding information about a file, as returned by the stat function.
The 'stat' structure provides information about a file, including its size, ownership, permissions, and other attributes. It is used with the stat function to query file status.
Definition at line 94 of file filesystem.hpp.
Data Fields
unsigned long __pad
unsigned int __pad0
long __pad1[2]
int __pad1[3]
int __pad2
unsigned int __pad2[2]
long __pad2[2]
int __pad3
long __pad3
unsigned int __pad4
long __pad4[2]
int __pad5[14]
struct stat __st_atim32
struct stat __st_atim32
struct stat __st_atim32
struct stat __st_atim32
struct stat __st_atim32
struct stat __st_atim32
struct stat __st_atim32
struct stat __st_atim32
struct stat __st_atim32
int __st_blksize_padding
struct stat __st_ctim32
struct stat __st_ctim32
struct stat __st_ctim32
struct stat __st_ctim32
struct stat __st_ctim32
struct stat __st_ctim32
struct stat __st_ctim32
struct stat __st_ctim32
struct stat __st_ctim32
int __st_dev_padding
short __st_dev_padding
long __st_ino_truncated
struct stat __st_mtim32
struct stat __st_mtim32
struct stat __st_mtim32
struct stat __st_mtim32
struct stat __st_mtim32
struct stat __st_mtim32
struct stat __st_mtim32
struct stat __st_mtim32
struct stat __st_mtim32
long __st_padding1[2]
long __st_padding2[2]
long __st_padding3
long __st_padding4[2]
int __st_rdev_padding
short __st_rdev_padding
long long __st_rdev_padding
unsigned __unused[2]
unsigned long __unused[3]
long long __unused[3]
long __unused[3]
struct timespec st_atim
time_t st_atime
Time of last access.
mode_t st_attr
Additional file attributes.
blksize_t st_blksize
Optimal I/O block size.
blkcnt_t st_blocks
Number of blocks allocated.
struct timespec st_ctim
time_t st_ctime
Time of last status change.
dev_t st_dev
Device ID of the file.
gid_t st_gid
Group ID of the file's owner.
ino_t st_ino
Inode number.
mode_t st_mode
File type and mode.
struct timespec st_mtim
time_t st_mtime
Time of last modification.
nlink_t st_nlink
Number of hard links.
dev_t st_rdev
Device ID for special files.
off_t st_size
Size of the file in bytes.
uid_t st_uid
User ID of the file's owner.
stat64
struct stat64
Extended structure for large file support, holding information about a file.
The 'stat64' structure is similar to 'struct stat' but is extended to support large files on 32-bit systems. It is used with the stat64 function for large file support.
Definition at line 133 of file filesystem.hpp.
Data Fields
time_t st_atime
Time of last access.
mode_t st_attr
Additional file attributes.
blksize_t st_blksize
Optimal I/O block size.
blkcnt64_t st_blocks
Number of blocks allocated.
time_t st_ctime
Time of last status change.
dev_t st_dev
Device ID of the file.
gid_t st_gid
Group ID of the file's owner.
ino64_t st_ino
Inode number.
mode_t st_mode
File type and mode.
time_t st_mtime
Time of last modification.
nlink_t st_nlink
Number of hard links.
dev_t st_rdev
Device ID for special files.
off64_t st_size
Size of the file in bytes.
uid_t st_uid
User ID of the file's owner.
Macro Definition Documentation
O_APPEND
#define O_APPEND 02000
Definition at line 66 of file filesystem.hpp.
O_CLOEXEC
#define O_CLOEXEC 02000000
Definition at line 67 of file filesystem.hpp.
O_CREAT
#define O_CREAT 0100
Definition at line 63 of file filesystem.hpp.
O_EXCL
#define O_EXCL 0200
Definition at line 64 of file filesystem.hpp.
O_RDONLY
#define O_RDONLY 00
Definition at line 60 of file filesystem.hpp.
O_RDWR
#define O_RDWR 02
Definition at line 62 of file filesystem.hpp.
O_TRUNC
#define O_TRUNC 01000
Definition at line 65 of file filesystem.hpp.
O_WRONLY
#define O_WRONLY 01
Definition at line 61 of file filesystem.hpp.
S_IFBLK
#define S_IFBLK 0060000
Definition at line 72 of file filesystem.hpp.
S_IFCHR
#define S_IFCHR 0020000
Definition at line 70 of file filesystem.hpp.
S_IFDIR
#define S_IFDIR 0040000
Definition at line 71 of file filesystem.hpp.
S_IFIFO
#define S_IFIFO 0010000
Definition at line 69 of file filesystem.hpp.
S_IFLNK
#define S_IFLNK 0120000
Definition at line 74 of file filesystem.hpp.
S_IFMT
#define S_IFMT 0170000
Definition at line 77 of file filesystem.hpp.
S_IFREG
#define S_IFREG 0100000
Definition at line 73 of file filesystem.hpp.
S_IFSOCK
#define S_IFSOCK 0140000
Definition at line 75 of file filesystem.hpp.
S_IRGRP
#define S_IRGRP 0040
Group members have read permission.
Definition at line 47 of file filesystem.hpp.
S_IROTH
#define S_IROTH 0004
Other users have read permission.
Definition at line 39 of file filesystem.hpp.
S_IRUSR
#define S_IRUSR 0400
The file owner has read permission.
Definition at line 55 of file filesystem.hpp.
S_IRWXG
#define S_IRWXG 0070
Group members have read, write, and execute permissions.
Definition at line 49 of file filesystem.hpp.
S_IRWXO
#define S_IRWXO 0007
Other users have read, write, and execute permissions.
Definition at line 41 of file filesystem.hpp.
S_IRWXU
#define S_IRWXU 0700
The file owner has read, write, and execute permissions.
Definition at line 58 of file filesystem.hpp.
S_ISBLK
#define S_ISBLK (mode) (((mode) & S_IFMT) == S_IFBLK)
Definition at line 81 of file filesystem.hpp.
S_ISCHR
#define S_ISCHR (mode) (((mode) & S_IFMT) == S_IFCHR)
Definition at line 80 of file filesystem.hpp.
S_ISDIR
#define S_ISDIR (mode) (((mode) & S_IFMT) == S_IFDIR)
Definition at line 79 of file filesystem.hpp.
S_ISFIFO
#define S_ISFIFO (mode) (((mode) & S_IFMT) == S_IFIFO)
Definition at line 83 of file filesystem.hpp.
S_ISLNK
#define S_ISLNK (mode) (((mode) & S_IFMT) == S_IFLNK)
Definition at line 84 of file filesystem.hpp.
S_ISREG
#define S_ISREG (mode) (((mode) & S_IFMT) == S_IFREG)
Definition at line 82 of file filesystem.hpp.
S_ISSOCK
#define S_ISSOCK (mode) (((mode) & S_IFMT) == S_IFSOCK)
Definition at line 85 of file filesystem.hpp.
S_IWGRP
#define S_IWGRP 0020
Group members have write permission.
Definition at line 45 of file filesystem.hpp.
S_IWOTH
#define S_IWOTH 0002
Other users have write permission.
Definition at line 37 of file filesystem.hpp.
S_IWUSR
#define S_IWUSR 0200
The file owner has write permission.
Definition at line 53 of file filesystem.hpp.
S_IXGRP
#define S_IXGRP 0010
Group members have execute permission.
Definition at line 43 of file filesystem.hpp.
S_IXOTH
#define S_IXOTH 0001
Other users have execute permission.
Definition at line 35 of file filesystem.hpp.
S_IXUSR
#define S_IXUSR 0100
The file owner has execute permission.
Definition at line 51 of file filesystem.hpp.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 31 of file filesystem.hpp.
SEEK_END
#define SEEK_END 2
Definition at line 32 of file filesystem.hpp.
SEEK_SET
#define SEEK_SET 0
Definition at line 30 of file filesystem.hpp.
Function Documentation
ConvertFileFlags()
static int ConvertFileFlags (const char * Mode) inline static
Definition at line 165 of file filesystem.hpp.
 {
     int Flags = 0;
     if (strchr(Mode, '+'))
         Flags |= O_RDWR;
     else if (*Mode == 'r')
         Flags |= O_RDONLY;
     else
         Flags |= O_WRONLY;
     if (strchr(Mode, 'x'))
         Flags |= O_EXCL;
     if (strchr(Mode, 'e'))
         Flags |= O_CLOEXEC;
     if (*Mode != 'r')
         Flags |= O_CREAT;
     if (*Mode == 'w')
         Flags |= O_TRUNC;
     if (*Mode == 'a')
         Flags |= O_APPEND;
     return Flags;
 }
References Flags, O_APPEND, O_CLOEXEC, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, and strchr().
Referenced by fopen().
creat()
int creat (const char * pathname, mode_t mode)
Definition at line 44 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int fd = fdt->_creat(pathname, mode);
     return fd;
 }
References vfs::FileDescriptorTable::_creat(), CheckForScheduler(), ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by show_textbox(), and writeLines().
fclose()
int fclose (int fd)
Definition at line 77 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_close(fd);
     return ret;
 }
References vfs::FileDescriptorTable::_close(), CheckForScheduler(), ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), _nl_log_untranslated(), add_remove_shell_main(), append_control_file_to_llist(), arp_show(), bb_displayroutes(), bb_dump_addfile(), cleanup(), cmd_cat(), comm_main(), conf_read_simple(), conf_write(), config_close(), convert(), create_file(), create_list(), dialog_menu(), do_all_in_proc_swaps(), do_disk_statistics(), do_info(), do_pidfile(), do_wordexp(), download_one_url(), dprintf(), Execute::ELFObject::ELFObject(), encode_n_base64(), endgrent(), endmntent(), endpwent(), endusershell(), evaluate(), expand_main(), extract_info(), fb_drawimage(), fclose_if_not_stdin(), file_action_grep(), file_write_dep(), finalize(), find_export_symbols(), freopen(), G_DoLoadGame(), G_DoSaveGame(), get_block_backed_filesystems(), get_charset_aliases(), get_cpu_count(), get_cpu_statistics(), get_hz(), get_irqcpu_nr(), get_irqs_from_interrupts(), get_irqs_from_stat(), get_smp_uptime(), get_uptime(), Execute::GetBinaryType(), getdate(), getgrouplist(), getgrouplist_internal(), handle_dir_common(), head_builtin(), if_readlist_proc(), ifupdown_main(), index_status_file(), is_hpet_irq(), is_ide_cdrom_or_tape(), klogd_setloglevel(), list_devs_in_proc_partititons(), LoadDefaultCollection(), Driver::Manager::LoadDriverFile(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), LoadResponseFile(), logdir_close(), M_FileExists(), M_ReadFile(), M_ReadSaveStrings(), M_WriteFile(), main(), more_main(), next_input_file(), open_shell_script(), parse(), parse_conf(), parse_file(), parse_meminfo(), patch_main(), pclose(), popen(), popmaildir_main(), print_builtin(), print_login_issue(), print_numbered_lines(), process_cron_update_file(), process_files(), process_includes(), process_irq_counts(), process_timer_stats(), procps_scan(), query(), read_alias_file(), read_config_file(), read_cstate_counts(), read_iface_state(), read_interfaces(), read_man_page(), readprofile_main(), rev_main(), rotate(), rpmalloc_initialize_config(), rtc_adjtime_is_utc(), save_input_to_file(), SaveDefaultCollection(), scan_proc_net_or_maps(), scriptreplay_main(), sed_main(), sendmail_main(), setfiles_main(), setgrent(), setpwent(), Execute::Spawn(), StatDump(), stdcat(), test_file(), unpack_package(), unset_bash_input(), update_passwd(), W_StdC_CloseFile(), write_helpfiles(), write_status_file(), write_str_to_file(), WriteTimidityConfig(), xprint_and_close_file(), and xtrace_reset().
fopen()
int fopen (const char * pathname, const char * mode)
Definition at line 33 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int fd = fdt->_open(pathname, ConvertFileFlags(mode), 0666);
     return fd;
 }
References vfs::FileDescriptorTable::_open(), CheckForScheduler(), ConvertFileFlags(), ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), _nl_log_untranslated(), cmd_cat(), conf_write(), create_file(), dialog_menu(), Execute::ELFObject::ELFObject(), file_write_dep(), find_export_symbols(), fopen_for_read(), fopen_for_write(), fopen_or_warn(), freopen(), G_DoLoadGame(), G_DoSaveGame(), get_charset_aliases(), Execute::GetBinaryType(), getdate(), getgrent(), getgrouplist(), getpwent(), getspnam_r(), head_builtin(), LoadDefaultCollection(), Driver::Manager::LoadDriverFile(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), LoadResponseFile(), M_FileExists(), M_ReadFile(), M_ReadSaveStrings(), M_WriteFile(), main(), process_includes(), produces_handler(), read_alias_file(), read_man_page(), rpmalloc_initialize_config(), SaveDefaultCollection(), setmntent(), setusershell(), Execute::Spawn(), StartKernelShell(), StatDump(), stdcat(), test_file(), update_passwd(), W_StdC_OpenFile(), write_helpfiles(), WriteTimidityConfig(), and xfopen().
fread()
ssize_t fread (int fd, void * buf, size_t count)
Definition at line 55 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = fdt->_read(fd, buf, count);
     return ret;
 }
References vfs::FileDescriptorTable::_read(), buf, CheckForScheduler(), count, ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __getgr_a(), __getpw_a(), __nscd_query(), cmd_cat(), diffreg(), Execute::ELFGetDynamicTag_x86_64(), Execute::ELFGetSections_x86_64(), Execute::ELFGetSymbolType_x86_64(), Execute::ELFLookupSymbol(), Execute::ELFObject::ELFObject(), encode_n_base64(), fb_drawimage(), get(), Execute::GetBinaryType(), getgrouplist(), getw(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), Execute::ELFObject::LoadInterpreter(), LoadResponseFile(), M_ReadFile(), M_ReadSaveStrings(), read_block(), read_man_page(), retrieve_file_data(), saveg_read8(), skip(), Execute::Spawn(), StartKernelShell(), and W_StdC_Read().
fstat()
int fstat (int fd, struct stat * statbuf)
Definition at line 110 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_fstat(fd, statbuf);
     return ret;
 }
References vfs::FileDescriptorTable::_fstat(), CheckForScheduler(), ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __fstat_time32(), __fxstat(), _evalfile(), _nl_load_domain(), _rl_read_file(), archivefile(), cmd_cat(), copy_tempfile(), crontab_main(), dd_main(), diff_main(), do_config_file(), fdopendir(), file_insert(), flash_eraseall_main(), flashcp_main(), getspnam_r(), getstat(), handle_retr(), here_document_to_fd(), history_truncate_file(), IF_DESKTOP(), isnetconn(), last_main(), load_crontab(), load_library(), log_locally(), lpqr_main(), main(), more_main(), noclobber_open(), open_shell_script(), openredirect(), patch_main(), print_deps(), read_history_range(), scan_proc_net_or_maps(), sem_open(), send_file_and_exit(), sh_stat(), shred_main(), skip(), Execute::Spawn(), tail_main(), ttyname_r(), update_passwd(), uuencode_main(), write_pidfile(), xfstat(), and xmalloc_read_with_initial_buf().
fwrite()
ssize_t fwrite (int fd, const void * buf, size_t count)
Definition at line 66 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = fdt->_write(fd, buf, count);
     return ret;
 }
References vfs::FileDescriptorTable::_write(), buf, CheckForScheduler(), count, ENOSYS, fd, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __getopt_msg(), _rl_output_some_chars(), _rl_put_indicator(), buffer_pwrite(), conf_write(), encode_n_base64(), evaluate(), expr_print_file_helper(), fnprint(), fputs(), M_WriteFile(), perror(), print_line(), putw(), read_base64(), refresh(), saveg_write8(), svlogd_main(), tee_main(), write2stdout(), and write_zeros().
lseek()
off_t lseek (int fd, off_t offset, int whence)
Definition at line 88 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     off_t ret = fdt->_lseek(fd, offset, whence);
     return ret;
 }
References vfs::FileDescriptorTable::_lseek(), CheckForScheduler(), ENOSYS, fd, Tasking::PCB::FileDescriptors, offset, and thisProcess.
Referenced by back_lines(), bb_BLKGETSIZE_sectors(), cutfile(), dd_main(), dialog_textbox(), diffreg(), Execute::ELFGetDynamicTag_x86_64(), Execute::ELFGetSections_x86_64(), Execute::ELFGetSymbolType_x86_64(), Execute::ELFLookupSymbol(), Execute::ELFObject::ELFObject(), fd_ispipe(), get_header_ar(), get_header_tar(), get_line(), get_volume_size_in_bytes(), Execute::GetBinaryType(), history_do_write(), io_thread_func(), last_main(), Execute::ELFObject::LoadDyn_x86_64(), Execute::ELFObject::LoadExec_x86_64(), mmap_fixed(), open_shell_script(), print_position(), retrieve_file_data(), rewinddir(), scan_file(), seek_by_jump(), seek_sector(), seekdir(), send_file_and_exit(), tail_main(), unzip_skip(), volume_id_get_buffer(), xlseek(), and zsyncfd().
lstat()
int lstat (const char * pathname, struct stat * statbuf)
Definition at line 121 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_lstat(pathname, statbuf);
     return ret;
 }
References vfs::FileDescriptorTable::_lstat(), CheckForScheduler(), ENOSYS, Tasking::PCB::FileDescriptors, and thisProcess.
operator!=()
int __attribute__::operator!= (const Fildes & other)
Definition at line 13 of file filesystem.hpp.
                                                 ://www.gnu.org/licenses/>.
 */
operator==()
int __attribute__::operator== (const Fildes & other)
Definition at line 5 of file filesystem.hpp.
                                                 ://www.gnu.org/licenses/>.
stat()
int stat (const char * pathname, struct stat * statbuf)
Definition at line 99 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int ret = fdt->_stat(pathname, statbuf);
     return ret;
 }
References vfs::FileDescriptorTable::_stat(), CheckForScheduler(), ENOSYS, Tasking::PCB::FileDescriptors, and thisProcess.
Referenced by __stat_time32(), __xstat(), _path_isdir(), _rl_print_color_indicator(), action_permissions(), append_to_match(), bb_make_directory(), bbunpack(), binop(), cdcmd(), colon(), conf(), conf_choice(), conf_get_default_confname(), conf_load(), conf_save(), conf_string(), conf_write(), crond_main(), custom(), deluser_main(), diff_main(), display_single(), do_glob(), do_nftw(), do_rescan(), du(), exec_conf(), fchmodat(), file_action_grep(), file_is_executable(), fileAction(), filstat(), find_command(), find_dot_file(), find_main(), find_mount_point(), ftok(), get_current_dir_name(), getstat(), glob_testdir(), grep_main(), handle_incoming_and_exit(), history_do_write(), init(), install_main(), is_directory(), is_ide_cdrom_or_tape(), ln_builtin(), ln_main(), logdir_open(), logical_getcwd(), mailstat(), main(), mktemp(), mountpoint_main(), mv_main(), my_stat(), name_to_dev_t(), noclobber_open(), open_control(), openredirect(), patch_main(), pid_is_user(), process_event(), procps_scan(), read_config_file(), read_man_page(), realpath_builtin(), recursive_action1(), rotate(), runsv_main(), runsvdir_main(), scan_recursive(), scan_request(), search_conf(), sed_main(), set_loop(), sh_mktmpname(), singlemount(), stat_char(), swap_enable_disable(), switch_root_main(), sysctl_act_recursive(), tail_main(), ttyname_r(), vi_main(), who_main(), xgetpty(), xmkpath(), and xstat().
Variable Documentation
Descriptor
int Descriptor = -1
Definition at line 3 of file filesystem.hpp.
Flags
int Flags = 0
Definition at line 2 of file filesystem.hpp.
Referenced by ConvertFileFlags().
Handle
RefNode* Handle = nullptr
Definition at line 0 of file filesystem.hpp.
Mode
mode_t Mode = 0
Definition at line 1 of file filesystem.hpp.
Referenced by vfs::FileDescriptorTable::AddFileDescriptor().