Fennix: Userspace/apps/base/busybox/networking/udhcp/common.h File Reference
common.h File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <netinet/udp.h>
#include <netinet/ip.h>
Data Structures
struct dhcp_packet
struct ip_udp_dhcp_packet
struct udp_dhcp_packet
struct BUG_bad_sizeof_struct_ip_udp_dhcp_packet
struct dhcp_scan_state
struct dhcp_optflag
struct option_set
Macros
#define DHCP_MAGIC 0x63825363
#define DHCP_OPTIONS_BUFSIZE 308
#define BOOTREQUEST 1
#define BOOTREPLY 2
#define BROADCAST_FLAG 0x8000 /* "I need broadcast replies" */
#define DHCP_PKT_SNAME_LEN 64
#define DHCP_PKT_FILE_LEN 128
#define DHCP_PKT_SNAME_LEN_STR "64"
#define DHCP_PKT_FILE_LEN_STR "128"
#define DHCP_PADDING 0x00
#define DHCP_SUBNET 0x01
#define DHCP_HOST_NAME 0x0c /* 12: either client informs server or server gives name to client */
#define DHCP_REQUESTED_IP 0x32 /* 50: sent by client if specific IP is wanted */
#define DHCP_LEASE_TIME 0x33 /* 51: 32bit big-endian */
#define DHCP_OPTION_OVERLOAD 0x34 /* 52: 1 byte */
#define DHCP_MESSAGE_TYPE 0x35 /* 53: 1 byte */
#define DHCP_SERVER_ID 0x36 /* 54: server's IP */
#define DHCP_PARAM_REQ 0x37 /* 55: list of options client wants */
#define DHCP_MAX_SIZE 0x39 /* 57: 16bit big-endian */
#define DHCP_VENDOR 0x3c /* 60: client's vendor (a string) */
#define DHCP_CLIENT_ID 0x3d /* 61: by default client's MAC addr, but may be arbitrarily long */
#define DHCP_FQDN 0x51 /* 81: client asks to update DNS to map its FQDN to its new IP */
#define DHCP_END 0xff /* 255: */
#define OPT_CODE 0
#define OPT_LEN 1
#define OPT_DATA 2
#define D6_OPT_CODE 0
#define D6_OPT_LEN 2
#define D6_OPT_DATA 4
#define OPTION_FIELD 0
#define FILE_FIELD 1
#define SNAME_FIELD 2
#define DHCPDISCOVER 1 /* client -> server */
#define DHCPOFFER 2 /* client <- server */
#define DHCPREQUEST 3 /* client -> server */
#define DHCPDECLINE 4 /* client -> server */
#define DHCPACK 5 /* client <- server */
#define DHCPNAK 6 /* client <- server */
#define DHCPRELEASE 7 /* client -> server */
#define DHCPINFORM 8 /* client -> server */
#define DHCP_MINTYPE DHCPDISCOVER
#define DHCP_MAXTYPE DHCPINFORM
#define udhcp_find_option(opt_list, code, dhcpv6) udhcp_find_option(opt_list, code)
#define IF_UDHCP_VERBOSE(...)
#define udhcp_dump_packet(...) ((void)0)
#define log1(...) ((void)0)
#define log1s(msg) ((void)0)
#define log2(...) ((void)0)
#define log2s(msg) ((void)0)
#define log3(...) ((void)0)
#define log3s(msg) ((void)0)
#define udhcp_insert_new_option(opt_list, code, length, dhcpv6) udhcp_insert_new_option(opt_list, code, length)
#define udhcp_str2optset(str, arg, optflags, option_strings, dhcpv6) udhcp_str2optset(str, arg, optflags, option_strings)
Enumerations
enum { IP_UDP_DHCP_SIZE = sizeof(struct ip_udp_dhcp_packet) - CONFIG_UDHCPC_SLACK_FOR_BUGGY_SERVERS , UDP_DHCP_SIZE = sizeof(struct udp_dhcp_packet) - CONFIG_UDHCPC_SLACK_FOR_BUGGY_SERVERS , DHCP_SIZE = sizeof(struct dhcp_packet) - CONFIG_UDHCPC_SLACK_FOR_BUGGY_SERVERS }
enum {
OPTION_IP = 0 , OPTION_IP_PAIR , OPTION_STRING , OPTION_STRING_HOST ,
OPTION_U8 , OPTION_U16 , OPTION_U32 , OPTION_S32 ,
OPTION_BIN , OPTION_STATIC_ROUTES , OPTION_6RD , OPTION_TYPE_MASK = 0x0f ,
OPTION_REQ = 0x10 , OPTION_LIST = 0x20
}
Functions
unsigned FAST_FUNC udhcp_option_idx (const char *name, const char *option_strings)
void init_scan_state (struct dhcp_packet *packet, struct dhcp_scan_state *scan_state) FAST_FUNC
uint8_t * udhcp_scan_options (struct dhcp_packet *packet, struct dhcp_scan_state *scan_state) FAST_FUNC
uint8_t * udhcp_get_option (struct dhcp_packet *packet, int code) FAST_FUNC
uint8_t * udhcp_get_option32 (struct dhcp_packet *packet, int code) FAST_FUNC
int udhcp_end_option (uint8_t *optionptr) FAST_FUNC
void udhcp_add_binary_option (struct dhcp_packet *packet, uint8_t *addopt) FAST_FUNC
struct option_set * udhcp_find_option (struct option_set *opt_list, uint8_t code, bool dhcpv6) FAST_FUNC
int FAST_FUNC udhcp_str2nip (const char *str, void *arg)
void *FAST_FUNC udhcp_insert_new_option (struct option_set **opt_list, unsigned code, unsigned length, bool dhcpv6)
int FAST_FUNC udhcp_str2optset (const char *str, void *arg, const struct dhcp_optflag *optflags, const char *option_strings, bool dhcpv6)
int udhcp_recv_kernel_packet (struct dhcp_packet *packet, int fd) FAST_FUNC
int udhcp_send_raw_packet (struct dhcp_packet *dhcp_pkt, uint32_t source_nip, int source_port, uint32_t dest_nip, int dest_port, const uint8_t *dest_arp, int ifindex) FAST_FUNC
int udhcp_send_kernel_packet (struct dhcp_packet *dhcp_pkt, uint32_t source_nip, int source_port, uint32_t dest_nip, int dest_port, const char *ifname) FAST_FUNC
void udhcp_sp_setup (void) FAST_FUNC
void udhcp_sp_fd_set (struct pollfd *pfds, int extra_fd) FAST_FUNC
int udhcp_sp_read (void) FAST_FUNC
int udhcp_read_interface (const char *interface, int *ifindex, uint32_t *nip, uint8_t *mac) FAST_FUNC
int udhcp_listen_socket (int port, const char *inf) FAST_FUNC
int arpping (uint32_t test_nip, const uint8_t *safe_mac, uint32_t from_ip, uint8_t *from_mac, const char *interface, unsigned timeo) FAST_FUNC
int sprint_nip6 (char *dest, const uint8_t *ip) FAST_FUNC
Variables
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN const uint8_t MAC_BCAST_ADDR[6] ALIGN2
const uint8_t dhcp_option_lengths[] ALIGN1
Data Structure Documentation
dhcp_packet
struct dhcp_packet
Definition at line 30 of file common.h.
Data Fields
uint8_t chaddr[16]
uint32_t ciaddr
uint32_t cookie
uint8_t file[128]
uint16_t flags
uint32_t gateway_nip
uint8_t hlen
uint8_t hops
uint8_t htype
uint8_t op
uint8_t options[DHCP_OPTIONS_BUFSIZE+CONFIG_UDHCPC_SLACK_FOR_BUGGY_SERVERS]
uint16_t secs
uint32_t siaddr_nip
uint8_t sname[64]
uint32_t xid
uint32_t yiaddr
ip_udp_dhcp_packet
struct ip_udp_dhcp_packet
Definition at line 69 of file common.h.
Data Fields
struct dhcp_packet data
struct iphdr ip
struct udphdr udp
udp_dhcp_packet
struct udp_dhcp_packet
Definition at line 75 of file common.h.
Data Fields
struct dhcp_packet data
struct udphdr udp
BUG_bad_sizeof_struct_ip_udp_dhcp_packet
struct BUG_bad_sizeof_struct_ip_udp_dhcp_packet
Definition at line 87 of file common.h.
Data Fields
char c[IP_UDP_DHCP_SIZE==576 ? 1 :-1]
dhcp_scan_state
struct dhcp_scan_state
Definition at line 124 of file common.h.
Data Fields
uint8_t * optionptr
int overload
int rem
dhcp_optflag
struct dhcp_optflag
Definition at line 214 of file common.h.
Data Fields
uint8_t code
uint8_t flags
option_set
struct option_set
Definition at line 219 of file common.h.
Data Fields
uint8_t * data
struct option_set * next
Macro Definition Documentation
BOOTREPLY
#define BOOTREPLY 2
Definition at line 27 of file common.h.
BOOTREQUEST
#define BOOTREQUEST 1
Definition at line 26 of file common.h.
BROADCAST_FLAG
#define BROADCAST_FLAG 0x8000 /* "I need broadcast replies" */
Definition at line 38 of file common.h.
D6_OPT_CODE
#define D6_OPT_CODE 0
Definition at line 194 of file common.h.
D6_OPT_DATA
#define D6_OPT_DATA 4
Definition at line 196 of file common.h.
D6_OPT_LEN
#define D6_OPT_LEN 2
Definition at line 195 of file common.h.
DHCP_CLIENT_ID
#define DHCP_CLIENT_ID 0x3d /* 61: by default client's MAC addr, but may be arbitrarily long */
Definition at line 169 of file common.h.
DHCP_END
#define DHCP_END 0xff /* 255: */
Definition at line 187 of file common.h.
DHCP_FQDN
#define DHCP_FQDN 0x51 /* 81: client asks to update DNS to map its FQDN to its new IP */
Definition at line 174 of file common.h.
DHCP_HOST_NAME
#define DHCP_HOST_NAME 0x0c /* 12: either client informs server or server gives name to client */
Definition at line 145 of file common.h.
DHCP_LEASE_TIME
#define DHCP_LEASE_TIME 0x33 /* 51: 32bit big-endian */
Definition at line 159 of file common.h.
DHCP_MAGIC
#define DHCP_MAGIC 0x63825363
Definition at line 24 of file common.h.
DHCP_MAX_SIZE
#define DHCP_MAX_SIZE 0x39 /* 57: 16bit big-endian */
Definition at line 165 of file common.h.
DHCP_MAXTYPE
#define DHCP_MAXTYPE DHCPINFORM
Definition at line 212 of file common.h.
DHCP_MESSAGE_TYPE
#define DHCP_MESSAGE_TYPE 0x35 /* 53: 1 byte */
Definition at line 161 of file common.h.
DHCP_MINTYPE
#define DHCP_MINTYPE DHCPDISCOVER
Definition at line 211 of file common.h.
DHCP_OPTION_OVERLOAD
#define DHCP_OPTION_OVERLOAD 0x34 /* 52: 1 byte */
Definition at line 160 of file common.h.
DHCP_OPTIONS_BUFSIZE
#define DHCP_OPTIONS_BUFSIZE 308
Definition at line 25 of file common.h.
DHCP_PADDING
#define DHCP_PADDING 0x00
Definition at line 135 of file common.h.
DHCP_PARAM_REQ
#define DHCP_PARAM_REQ 0x37 /* 55: list of options client wants */
Definition at line 163 of file common.h.
DHCP_PKT_FILE_LEN
#define DHCP_PKT_FILE_LEN 128
Definition at line 65 of file common.h.
DHCP_PKT_FILE_LEN_STR
#define DHCP_PKT_FILE_LEN_STR "128"
Definition at line 67 of file common.h.
DHCP_PKT_SNAME_LEN
#define DHCP_PKT_SNAME_LEN 64
Definition at line 64 of file common.h.
DHCP_PKT_SNAME_LEN_STR
#define DHCP_PKT_SNAME_LEN_STR "64"
Definition at line 66 of file common.h.
DHCP_REQUESTED_IP
#define DHCP_REQUESTED_IP 0x32 /* 50: sent by client if specific IP is wanted */
Definition at line 158 of file common.h.
DHCP_SERVER_ID
#define DHCP_SERVER_ID 0x36 /* 54: server's IP */
Definition at line 162 of file common.h.
DHCP_SUBNET
#define DHCP_SUBNET 0x01
Definition at line 136 of file common.h.
DHCP_VENDOR
#define DHCP_VENDOR 0x3c /* 60: client's vendor (a string) */
Definition at line 168 of file common.h.
DHCPACK
#define DHCPACK 5 /* client <- server */
Definition at line 207 of file common.h.
DHCPDECLINE
#define DHCPDECLINE 4 /* client -> server */
Definition at line 206 of file common.h.
DHCPDISCOVER
#define DHCPDISCOVER 1 /* client -> server */
Definition at line 203 of file common.h.
DHCPINFORM
#define DHCPINFORM 8 /* client -> server */
Definition at line 210 of file common.h.
DHCPNAK
#define DHCPNAK 6 /* client <- server */
Definition at line 208 of file common.h.
DHCPOFFER
#define DHCPOFFER 2 /* client <- server */
Definition at line 204 of file common.h.
DHCPRELEASE
#define DHCPRELEASE 7 /* client -> server */
Definition at line 209 of file common.h.
DHCPREQUEST
#define DHCPREQUEST 3 /* client -> server */
Definition at line 205 of file common.h.
FILE_FIELD
#define FILE_FIELD 1
Definition at line 199 of file common.h.
IF_UDHCP_VERBOSE
#define IF_UDHCP_VERBOSE (...)
Definition at line 318 of file common.h.
log1
#define log1 (...) ((void)0)
Definition at line 320 of file common.h.
log1s
#define log1s (msg) ((void)0)
Definition at line 321 of file common.h.
log2
#define log2 (...) ((void)0)
Definition at line 322 of file common.h.
log2s
#define log2s (msg) ((void)0)
Definition at line 323 of file common.h.
log3
#define log3 (...) ((void)0)
Definition at line 324 of file common.h.
log3s
#define log3s (msg) ((void)0)
Definition at line 325 of file common.h.
OPT_CODE
#define OPT_CODE 0
Definition at line 190 of file common.h.
OPT_DATA
#define OPT_DATA 2
Definition at line 192 of file common.h.
OPT_LEN
#define OPT_LEN 1
Definition at line 191 of file common.h.
OPTION_FIELD
#define OPTION_FIELD 0
Definition at line 198 of file common.h.
SNAME_FIELD
#define SNAME_FIELD 2
Definition at line 200 of file common.h.
udhcp_dump_packet
#define udhcp_dump_packet (...) ((void)0)
Definition at line 319 of file common.h.
udhcp_find_option
#define udhcp_find_option (opt_list, code, dhcpv6) udhcp_find_option(opt_list, code)
Definition at line 249 of file common.h.
udhcp_insert_new_option
#define udhcp_insert_new_option (opt_list, code, length, dhcpv6) udhcp_insert_new_option(opt_list, code, length)
Definition at line 334 of file common.h.
udhcp_str2optset
#define udhcp_str2optset (str, arg, optflags, option_strings, dhcpv6) udhcp_str2optset(str, arg, optflags, option_strings)
Definition at line 344 of file common.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IP_UDP_DHCP_SIZE
UDP_DHCP_SIZE
DHCP_SIZE
Definition at line 80 of file common.h.
      {
     IP_UDP_DHCP_SIZE = sizeof(struct ip_udp_dhcp_packet) - CONFIG_UDHCPC_SLACK_FOR_BUGGY_SERVERS,
     UDP_DHCP_SIZE    = sizeof(struct udp_dhcp_packet) - CONFIG_UDHCPC_SLACK_FOR_BUGGY_SERVERS,
     DHCP_SIZE        = sizeof(struct dhcp_packet) - CONFIG_UDHCPC_SLACK_FOR_BUGGY_SERVERS,
 };
anonymous enum
anonymous enum
Enumerator
OPTION_IP
OPTION_IP_PAIR
OPTION_STRING
OPTION_STRING_HOST
OPTION_U8
OPTION_U16
OPTION_U32
OPTION_S32
OPTION_BIN
OPTION_STATIC_ROUTES
OPTION_6RD
OPTION_TYPE_MASK
OPTION_REQ
OPTION_LIST
Definition at line 94 of file common.h.
      {
     OPTION_IP = 0,
     OPTION_IP_PAIR,
     OPTION_STRING,
     /* Opts of STRING_HOST type will be sanitized before they are passed
      * to udhcpc script's environment: */
     OPTION_STRING_HOST,
 //  OPTION_BOOLEAN,
     OPTION_U8,
     OPTION_U16,
 //  OPTION_S16,
     OPTION_U32,
     OPTION_S32,
     OPTION_BIN,
     OPTION_STATIC_ROUTES,
     OPTION_6RD,
 #if ENABLE_FEATURE_UDHCP_RFC3397 || ENABLE_FEATURE_UDHCPC6_RFC3646 || ENABLE_FEATURE_UDHCPC6_RFC4704
     OPTION_DNS_STRING,  /* RFC1035 compressed domain name list */
 #endif
 #if ENABLE_FEATURE_UDHCP_RFC3397
     OPTION_SIP_SERVERS,
 #endif
     OPTION_TYPE_MASK = 0x0f,
     /* Client requests this option by default */
     OPTION_REQ  = 0x10,
     /* There can be a list of 1 or more of these */
     OPTION_LIST = 0x20,
 };
Function Documentation
arpping()
int arpping (uint32_t test_nip, const uint8_t * safe_mac, uint32_t from_ip, uint8_t * from_mac, const char * interface, unsigned timeo)
Definition at line 37 of file arpping.c.
 {
     int timeout_ms;
     struct pollfd pfd[1];
 #define s (pfd[0].fd)           /* socket */
     int rv = 1;             /* "no reply received" yet */
     struct sockaddr addr;   /* for interface name */
     struct arpMsg arp;
     const char *msg;
     if (!timeo)
         return 1;
     s = socket(PF_PACKET, SOCK_PACKET, htons(ETH_P_ARP));
     if (s == -1) {
         bb_simple_perror_msg(bb_msg_can_not_create_raw_socket);
         return -1;
     }
     if (setsockopt_broadcast(s) == -1) {
         bb_simple_perror_msg("can't enable bcast on ARP socket");
         goto ret;
     }
     /* send arp request */
     memset(&arp, 0, sizeof(arp));
     memset(arp.h_dest, 0xff, 6);                    /* MAC DA */
     memcpy(arp.h_source, from_mac, 6);              /* MAC SA */
     arp.h_proto = htons(ETH_P_ARP);                 /* protocol type (Ethernet) */
     arp.htype = htons(ARPHRD_ETHER);                /* hardware type */
     arp.ptype = htons(ETH_P_IP);                    /* protocol type (ARP message) */
     arp.hlen = 6;                                   /* hardware address length */
     arp.plen = 4;                                   /* protocol address length */
     arp.operation = htons(ARPOP_REQUEST);           /* ARP op code */
     memcpy(arp.sHaddr, from_mac, 6);                /* source hardware address */
     memcpy(arp.sInaddr, &from_ip, sizeof(from_ip)); /* source IP address */
     /* tHaddr is zero-filled */                     /* target hardware address */
     memcpy(arp.tInaddr, &test_nip, sizeof(test_nip));/* target IP address */
     memset(&addr, 0, sizeof(addr));
     safe_strncpy(addr.sa_data, interface, sizeof(addr.sa_data));
     if (sendto(s, &arp, sizeof(arp), 0, &addr, sizeof(addr)) < 0) {
         // TODO: error message? caller didn't expect us to fail,
         // just returning 1 "no reply received" misleads it.
         goto ret;
     }
     /* wait for arp reply, and check it */
     timeout_ms = (int)timeo;
     do {
         typedef uint32_t aliased_uint32_t FIX_ALIASING;
         int r;
         unsigned prevTime = monotonic_ms();
         pfd[0].events = POLLIN;
         r = safe_poll(pfd, 1, timeout_ms);
         if (r < 0)
             break;
         if (r) {
             r = safe_read(s, &arp, sizeof(arp));
             if (r < 0)
                 break;
             //log3("sHaddr %02x:%02x:%02x:%02x:%02x:%02x",
             //  arp.sHaddr[0], arp.sHaddr[1], arp.sHaddr[2],
             //  arp.sHaddr[3], arp.sHaddr[4], arp.sHaddr[5]);
             if (r >= ARP_MSG_SIZE
              && arp.operation == htons(ARPOP_REPLY)
              /* don't check it: Linux doesn't return proper tHaddr (fixed in 2.6.24?) */
              /* && memcmp(arp.tHaddr, from_mac, 6) == 0 */
              && *(aliased_uint32_t*)arp.sInaddr == test_nip
             ) {
                 /* if ARP source MAC matches safe_mac
                  * (which is client's MAC), then it's not a conflict
                  * (client simply already has this IP and replies to ARPs!)
                  */
                 if (!safe_mac || memcmp(safe_mac, arp.sHaddr, 6) != 0)
                     rv = 0;
                 //else log2("sHaddr == safe_mac");
                 break;
             }
         }
         timeout_ms -= (unsigned)monotonic_ms() - prevTime + 1;
         /* We used to check "timeout_ms > 0", but
          * this is more under/overflow-resistant
          * (people did see overflows here when system time jumps):
          */
     } while ((unsigned)timeout_ms <= timeo);
  ret:
     close(s);
     msg = "no ARP reply received for this address";
     if (rv == 0)
         msg += 3;
     log1s(msg);
     return rv;
 }
References addr, ARP_MSG_SIZE, ARPHRD_ETHER, ARPOP_REPLY, ARPOP_REQUEST, bb_simple_perror_msg(), close(), ETH_P_ARP, ETH_P_IP, FIX_ALIASING, arpMsg::h_dest, arpMsg::h_proto, arpMsg::h_source, arpMsg::hlen, htons(), arpMsg::htype, log1s, memcmp(), memcpy, memset, monotonic_ms(), arpMsg::operation, PF_PACKET, pfd, arpMsg::plen, POLLIN, arpMsg::ptype, s, safe_poll(), safe_read(), safe_strncpy(), sendto(), setsockopt_broadcast(), arpMsg::sHaddr, arpMsg::sInaddr, SOCK_PACKET, socket(), timeout_ms, and arpMsg::tInaddr.
Referenced by nobody_responds_to_arp(), and udhcpc_main().
init_scan_state()
void init_scan_state (struct dhcp_packet * packet, struct dhcp_scan_state * scan_state)
Definition at line 234 of file common.c.
 {
     scan_state->overload = 0;
     scan_state->rem = sizeof(packet->options);
     scan_state->optionptr = packet->options;
 }
References dhcp_scan_state::optionptr, dhcp_packet::options, dhcp_scan_state::overload, and dhcp_scan_state::rem.
Referenced by fill_envp(), and udhcp_get_option().
sprint_nip6()
int sprint_nip6 (char * dest, const uint8_t * ip)
Definition at line 719 of file common.c.
 {
     char hexstrbuf[16 * 2];
     bin2hex(hexstrbuf, (void*)ip, 16);
     return sprintf(dest, /* "%s" */
         "%.4s:%.4s:%.4s:%.4s:%.4s:%.4s:%.4s:%.4s",
         /* pre, */
         hexstrbuf + 0 * 4,
         hexstrbuf + 1 * 4,
         hexstrbuf + 2 * 4,
         hexstrbuf + 3 * 4,
         hexstrbuf + 4 * 4,
         hexstrbuf + 5 * 4,
         hexstrbuf + 6 * 4,
         hexstrbuf + 7 * 4
     );
 }
References bin2hex(), and sprintf().
Referenced by option_to_env(), and xmalloc_optname_optval().
udhcp_add_binary_option()
void udhcp_add_binary_option (struct dhcp_packet * packet, uint8_t * addopt)
Definition at line 361 of file common.c.
 {
     unsigned len;
     uint8_t *optionptr = packet->options;
     unsigned end = udhcp_end_option(optionptr);
     len = OPT_DATA + addopt[OPT_LEN];
     /* end position + (option code/length + addopt length) + end option */
     if (end + len + 1 >= DHCP_OPTIONS_BUFSIZE) {
 //TODO: learn how to use overflow option if we exhaust packet->options[]
         bb_error_msg("option 0x%02x did not fit into the packet",
                 addopt[OPT_CODE]);
         return;
     }
     log_option("adding option", addopt);
     memcpy(optionptr + end, addopt, len);
     optionptr[end + len] = DHCP_END;
 }
References bb_error_msg(), DHCP_END, DHCP_OPTIONS_BUFSIZE, end, len, log_option, memcpy, OPT_CODE, OPT_DATA, OPT_LEN, dhcp_scan_state::optionptr, dhcp_packet::options, and udhcp_end_option().
Referenced by add_client_options(), add_server_options(), and add_serverid_and_clientid_options().
udhcp_end_option()
int udhcp_end_option (uint8_t * optionptr)
Definition at line 346 of file common.c.
 {
     int i = 0;
     while (optionptr[i] != DHCP_END) {
         if (optionptr[i] != DHCP_PADDING)
             i += optionptr[i + OPT_LEN] + OPT_DATA-1;
         i++;
     }
     return i;
 }
References DHCP_END, DHCP_PADDING, i, OPT_DATA, OPT_LEN, and dhcp_scan_state::optionptr.
Referenced by add_client_options(), udhcp_add_binary_option(), udhcp_send_kernel_packet(), and udhcp_send_raw_packet().
udhcp_find_option()
struct option_set* udhcp_find_option (struct option_set * opt_list, uint8_t code, bool dhcpv6)
Definition at line 407 of file common.c.
 {
     IF_NOT_UDHCPC6(bool dhcpv6 = 0;)
     uint8_t cur_code;
     for (;;) {
         if (!opt_list)
             return opt_list; /* NULL */
         if (!dhcpv6) {
             cur_code = opt_list->data[OPT_CODE];
         } else {
 //FIXME: add support for code > 0xff
             if (opt_list->data[D6_OPT_CODE] != 0)
                 return NULL;
             cur_code = opt_list->data[D6_OPT_CODE + 1];
         }
         if (cur_code >= code) {
             if (cur_code == code)
                 return opt_list;
             return NULL;
         }
         opt_list = opt_list->next;
     }
 }
References code, D6_OPT_CODE, option_set::data, option_set::next, NULL, and OPT_CODE.
Referenced by attach_option().
udhcp_get_option()
uint8_t* udhcp_get_option (struct dhcp_packet * packet, int code)
Definition at line 317 of file common.c.
 {
     uint8_t *optptr;
     struct dhcp_scan_state scan_state;
     init_scan_state(packet, &scan_state);
     while ((optptr = udhcp_scan_options(packet, &scan_state)) != NULL) {
         if (optptr[OPT_CODE] == code) {
             log_option("option found", optptr);
             return optptr + OPT_DATA;
         }
     }
     /* log3 because udhcpc uses it a lot - very noisy */
     log3("option 0x%02x not found", code);
     return NULL;
 }
References code, init_scan_state(), log3, log_option, NULL, OPT_CODE, OPT_DATA, optptr, and udhcp_scan_options().
Referenced by get_dhcp_packet_type(), send_ACK(), send_offer(), udhcp_get_option32(), udhcpc_main(), and udhcpd_main().
udhcp_get_option32()
uint8_t* udhcp_get_option32 (struct dhcp_packet * packet, int code)
Definition at line 335 of file common.c.
 {
     uint8_t *r = udhcp_get_option(packet, code);
     if (r) {
         if (r[-OPT_DATA + OPT_LEN] != 4)
             r = NULL;
     }
     return r;
 }
References code, NULL, OPT_DATA, OPT_LEN, and udhcp_get_option().
Referenced by select_lease_time(), udhcpc_main(), and udhcpd_main().
udhcp_insert_new_option()
void* FAST_FUNC udhcp_insert_new_option (struct option_set ** opt_list, unsigned code, unsigned length, bool dhcpv6)
Definition at line 446 of file common.c.
 {
     IF_NOT_UDHCPC6(bool dhcpv6 = 0;)
     struct option_set *new, **curr;
     log2("attaching option %02x to list", code);
     new = xmalloc(sizeof(*new));
     if (!dhcpv6) {
         new->data = xzalloc(length + OPT_DATA);
         new->data[OPT_CODE] = code;
         new->data[OPT_LEN] = length;
     } else {
         new->data = xzalloc(length + D6_OPT_DATA);
         new->data[D6_OPT_CODE] = code >> 8;
         new->data[D6_OPT_CODE + 1] = code & 0xff;
         new->data[D6_OPT_LEN] = length >> 8;
         new->data[D6_OPT_LEN + 1] = length & 0xff;
     }
     curr = opt_list;
 //FIXME: DHCP6 codes > 255!!
     while (*curr && (*curr)->data[OPT_CODE] < code)
         curr = &(*curr)->next;
     new->next = *curr;
     *curr = new;
     return new->data;
 }
References code, D6_OPT_CODE, D6_OPT_DATA, D6_OPT_LEN, option_set::data, log2, option_set::next, OPT_CODE, OPT_DATA, OPT_LEN, xmalloc, and xzalloc().
Referenced by attach_option().
udhcp_listen_socket()
int udhcp_listen_socket (int port, const char * inf)
Definition at line 79 of file socket.c.
 {
     int fd;
     struct sockaddr_in addr;
     char *colon;
     log2("opening listen socket on *:%d %s", port, inf);
     fd = xsocket(PF_INET, SOCK_DGRAM, IPPROTO_UDP);
     setsockopt_reuseaddr(fd);
     if (setsockopt_broadcast(fd) == -1)
         bb_simple_perror_msg_and_die("SO_BROADCAST");
     /* SO_BINDTODEVICE doesn't work on ethernet aliases (ethN:M) */
     colon = strrchr(inf, ':');
     if (colon)
         *colon = '\0';
     if (setsockopt_bindtodevice(fd, inf))
         xfunc_die(); /* warning is already printed */
     if (colon)
         *colon = ':';
     memset(&addr, 0, sizeof(addr));
     addr.sin_family = AF_INET;
     addr.sin_port = htons(port);
     /* addr.sin_addr.s_addr = ip; - all-zeros is INADDR_ANY */
     xbind(fd, (struct sockaddr *)&addr, sizeof(addr));
     return fd;
 }
References addr, AF_INET, bb_simple_perror_msg_and_die(), colon, fd, htons(), IPPROTO_UDP, log2, memset, PF_INET, port, setsockopt_bindtodevice(), setsockopt_broadcast(), setsockopt_reuseaddr(), SOCK_DGRAM, strrchr(), xbind(), xfunc_die(), and xsocket().
Referenced by change_listen_mode(), init_sockets(), and udhcpd_main().
udhcp_option_idx()
unsigned FAST_FUNC udhcp_option_idx (const char * name, const char * option_strings)
Definition at line 209 of file common.c.
 {
     int n = index_in_strings(option_strings, name);
     if (n >= 0)
         return n;
     {
         char *buf, *d;
         const char *s;
         s = option_strings;
         while (*s)
             s += strlen(s) + 1;
         d = buf = xzalloc(s - option_strings);
         s = option_strings;
         while (!(*s == '\0' && s[1] == '\0')) {
             *d++ = (*s == '\0' ? ' ' : *s);
             s++;
         }
         bb_error_msg_and_die("unknown option '%s', known options: %s", name, buf);
     }
 }
References bb_error_msg_and_die(), buf, index_in_strings(), n, s, strlen(), and xzalloc().
Referenced by udhcp_str2optset(), udhcpc6_main(), and udhcpc_main().
udhcp_read_interface()
int udhcp_read_interface (const char * interface, int * ifindex, uint32_t * nip, uint8_t * mac)
Definition at line 28 of file socket.c.
 {
     /* char buffer instead of bona-fide struct avoids aliasing warning */
     char ifr_buf[sizeof(struct ifreq)];
     struct ifreq *const ifr = (void *)ifr_buf;
     int fd;
     struct sockaddr_in *our_ip;
     memset(ifr, 0, sizeof(*ifr));
     fd = xsocket(AF_INET, SOCK_RAW, IPPROTO_RAW);
     ifr->ifr_addr.sa_family = AF_INET;
     strncpy_IFNAMSIZ(ifr->ifr_name, interface);
     if (nip) {
         if (ioctl_or_perror(fd, SIOCGIFADDR, ifr,
             "is interface %s up and configured?", interface)
         ) {
             close(fd);
             return -1;
         }
         our_ip = (struct sockaddr_in *) &ifr->ifr_addr;
         *nip = our_ip->sin_addr.s_addr;
         log1("IP %s", inet_ntoa(our_ip->sin_addr));
     }
     if (ifindex) {
         if (ioctl_or_warn(fd, SIOCGIFINDEX, ifr) != 0) {
             close(fd);
             return -1;
         }
         log2("ifindex %d", ifr->ifr_ifindex);
         *ifindex = ifr->ifr_ifindex;
     }
     if (mac) {
         if (ioctl_or_warn(fd, SIOCGIFHWADDR, ifr) != 0) {
             close(fd);
             return -1;
         }
         memcpy(mac, ifr->ifr_hwaddr.sa_data, 6);
         log2("MAC %02x:%02x:%02x:%02x:%02x:%02x",
             mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
     }
     close(fd);
     return 0;
 }
References AF_INET, close(), fd, ifr, inet_ntoa(), ioctl_or_perror(), ioctl_or_warn, IPPROTO_RAW, log1, log2, memcpy, memset, in_addr::s_addr, sockaddr_in::sin_addr, SIOCGIFADDR, SIOCGIFHWADDR, SIOCGIFINDEX, SOCK_RAW, strncpy_IFNAMSIZ(), and xsocket().
Referenced by dhcprelay_main(), udhcpc_main(), and udhcpd_main().
udhcp_recv_kernel_packet()
int udhcp_recv_kernel_packet (struct dhcp_packet * packet, int fd)
Definition at line 81 of file packet.c.
 {
     int bytes;
     memset(packet, 0, sizeof(*packet));
     bytes = safe_read(fd, packet, sizeof(*packet));
     if (bytes < 0) {
         log1s("packet read error, ignoring");
         return bytes; /* returns -1 */
     }
     if (bytes < offsetof(struct dhcp_packet, options)
      || packet->cookie != htonl(DHCP_MAGIC)
     ) {
         bb_simple_info_msg("packet with bad magic, ignoring");
         return -2;
     }
     log2("received %s", "a packet");
     /* log2 because more informative msg for valid packets is printed later at log1 level */
     udhcp_dump_packet(packet);
     return bytes;
 }
References bb_simple_info_msg, dhcp_packet::cookie, DHCP_MAGIC, fd, htonl(), log1s, log2, memset, offsetof, safe_read(), and udhcp_dump_packet.
Referenced by dhcprelay_main(), udhcpc_main(), and udhcpd_main().
udhcp_scan_options()
uint8_t* udhcp_scan_options (struct dhcp_packet * packet, struct dhcp_scan_state * scan_state)
Definition at line 244 of file common.c.
 {
     int len;
     enum {
         FILE_FIELD101  = FILE_FIELD  * 0x101,
         SNAME_FIELD101 = SNAME_FIELD * 0x101,
     };
     /* option bytes: [code][len][data1][data2]..[dataLEN] */
     while (1) {
         if (scan_state->rem <= 0) {
  complain:
             bb_simple_error_msg("bad packet, malformed option field");
             return NULL;
         }
         /* DHCP_PADDING and DHCP_END have no [len] byte */
         if (scan_state->optionptr[OPT_CODE] == DHCP_PADDING) {
             scan_state->rem--;
             scan_state->optionptr++;
             continue;
         }
         if (scan_state->optionptr[OPT_CODE] == DHCP_END) {
             if ((scan_state->overload & FILE_FIELD101) == FILE_FIELD) {
                 /* can use packet->file, and didn't look at it yet */
                 scan_state->overload |= FILE_FIELD101; /* "we looked at it" */
                 scan_state->optionptr = packet->file;
                 scan_state->rem = sizeof(packet->file);
                 continue;
             }
             if ((scan_state->overload & SNAME_FIELD101) == SNAME_FIELD) {
                 /* can use packet->sname, and didn't look at it yet */
                 scan_state->overload |= SNAME_FIELD101; /* "we looked at it" */
                 scan_state->optionptr = packet->sname;
                 scan_state->rem = sizeof(packet->sname);
                 continue;
             }
             break;
         }
         if (scan_state->rem <= OPT_LEN) /* [len] byte exists? */
             goto complain; /* no, complain and return NULL */
         len = scan_state->optionptr[OPT_LEN];
         /* Skip options with zero length.
          * Users report that DHCP server on a TrendNet router (unknown model)
          * provides a zero-length option 12 (Host Name)
          * (this violates RFC 2132 section 3.14).
          */
         if (len == 0) {
             scan_state->rem -= 2;
             scan_state->optionptr += 2;
             continue;
         }
         len += 2;
         scan_state->rem -= len;
         if (scan_state->rem < 0) /* option is longer than options field? */
             goto complain; /* yes, complain and return NULL */
         if (scan_state->optionptr[OPT_CODE] == DHCP_OPTION_OVERLOAD) {
             /* len is known to be >= 3 now, [data] byte exists */
             scan_state->overload |= scan_state->optionptr[OPT_DATA];
         } else {
             uint8_t *return_ptr = scan_state->optionptr;
             scan_state->optionptr += len;
             return return_ptr;
         }
         scan_state->optionptr += len;
     }
     return NULL;
 }
References bb_simple_error_msg(), DHCP_END, DHCP_OPTION_OVERLOAD, DHCP_PADDING, dhcp_packet::file, FILE_FIELD, len, NULL, OPT_CODE, OPT_DATA, OPT_LEN, dhcp_scan_state::optionptr, dhcp_scan_state::overload, dhcp_scan_state::rem, dhcp_packet::sname, and SNAME_FIELD.
Referenced by fill_envp(), and udhcp_get_option().
udhcp_send_kernel_packet()
int udhcp_send_kernel_packet (struct dhcp_packet * dhcp_pkt, uint32_t source_nip, int source_port, uint32_t dest_nip, int dest_port, const char * ifname)
Definition at line 192 of file packet.c.
 {
     struct sockaddr_in sa;
     unsigned padding;
     int fd;
     int result = -1;
     const char *msg;
     fd = socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP);
     if (fd < 0) {
         msg = "socket(%s)";
         goto ret_msg;
     }
     setsockopt_reuseaddr(fd);
     /* If interface carrier goes down, unless we
      * bind socket to a particular netdev, the packet
      * can go out through another interface, eg. via
      * default route despite being bound to a specific
      * source IP. As such, bind to device hard and fail
      * otherwise. Sending renewal packets on foreign
      * interfaces makes no sense.
      */
     if (ifname) {
         if (setsockopt_bindtodevice(fd, ifname) < 0) {
             msg = "bindtodevice";
             goto ret_close;
         }
     }
     memset(&sa, 0, sizeof(sa));
     sa.sin_family = AF_INET;
     sa.sin_port = htons(source_port);
     sa.sin_addr.s_addr = source_nip;
     if (bind(fd, (struct sockaddr *)&sa, sizeof(sa)) == -1) {
         msg = "bind(%s)";
         goto ret_close;
     }
     memset(&sa, 0, sizeof(sa));
     sa.sin_family = AF_INET;
     sa.sin_port = htons(dest_port);
     sa.sin_addr.s_addr = dest_nip;
     if (connect(fd, (struct sockaddr *)&sa, sizeof(sa)) == -1) {
         msg = "connect";
         goto ret_close;
     }
     udhcp_dump_packet(dhcp_pkt);
     padding = DHCP_OPTIONS_BUFSIZE - 1 - udhcp_end_option(dhcp_pkt->options);
     if (padding > DHCP_SIZE - 300)
         padding = DHCP_SIZE - 300;
     result = safe_write(fd, dhcp_pkt, DHCP_SIZE - padding);
     msg = "write";
  ret_close:
     close(fd);
     if (result < 0) {
  ret_msg:
         bb_perror_msg(msg, "UDP");
     }
     return result;
 }
References AF_INET, bb_perror_msg(), bind(), close(), connect(), DHCP_OPTIONS_BUFSIZE, DHCP_SIZE, fd, htons(), IPPROTO_UDP, memset, dhcp_packet::options, PF_INET, in_addr::s_addr, safe_write(), setsockopt_bindtodevice(), setsockopt_reuseaddr(), sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, SOCK_DGRAM, socket(), udhcp_dump_packet, and udhcp_end_option().
Referenced by bcast_or_ucast(), and send_packet_to_relay().
udhcp_send_raw_packet()
int udhcp_send_raw_packet (struct dhcp_packet * dhcp_pkt, uint32_t source_nip, int source_port, uint32_t dest_nip, int dest_port, const uint8_t * dest_arp, int ifindex)
Definition at line 106 of file packet.c.
 {
     struct sockaddr_ll dest_sll;
     struct ip_udp_dhcp_packet packet;
     unsigned padding;
     int fd;
     int result = -1;
     const char *msg;
     fd = socket(PF_PACKET, SOCK_DGRAM, htons(ETH_P_IP));
     if (fd < 0) {
         msg = "socket(%s)";
         goto ret_msg;
     }
     memset(&dest_sll, 0, sizeof(dest_sll));
     memset(&packet, 0, offsetof(struct ip_udp_dhcp_packet, data));
     packet.data = *dhcp_pkt; /* struct copy */
     dest_sll.sll_family = AF_PACKET;
     dest_sll.sll_protocol = htons(ETH_P_IP);
     dest_sll.sll_ifindex = ifindex;
     /*dest_sll.sll_hatype = ARPHRD_???;*/
     /*dest_sll.sll_pkttype = PACKET_???;*/
     dest_sll.sll_halen = 6;
     memcpy(dest_sll.sll_addr, dest_arp, 6);
 //TODO: is bind() necessary? we sendto() to this destination, should work anyway
     if (bind(fd, (struct sockaddr *)&dest_sll, sizeof(dest_sll)) < 0) {
         msg = "bind(%s)";
         goto ret_close;
     }
     /* We were sending full-sized DHCP packets (zero padded),
      * but some badly configured servers were seen dropping them.
      * Apparently they drop all DHCP packets >576 *ethernet* octets big,
      * whereas they may only drop packets >576 *IP* octets big
      * (which for typical Ethernet II means 590 octets: 6+6+2 + 576).
      *
      * In order to work with those buggy servers,
      * we truncate packets after end option byte.
      *
      * However, RFC 1542 says "The IP Total Length and UDP Length
      * must be large enough to contain the minimal BOOTP header of 300 octets".
      * Thus, we retain enough padding to not go below 300 BOOTP bytes.
      * Some devices have filters which drop DHCP packets shorter than that.
      */
     padding = DHCP_OPTIONS_BUFSIZE - 1 - udhcp_end_option(packet.data.options);
     if (padding > DHCP_SIZE - 300)
         padding = DHCP_SIZE - 300;
     packet.ip.protocol = IPPROTO_UDP;
     packet.ip.saddr = source_nip;
     packet.ip.daddr = dest_nip;
     packet.udp.source = htons(source_port);
     packet.udp.dest = htons(dest_port);
     /* size, excluding IP header: */
     packet.udp.len = htons(UDP_DHCP_SIZE - padding);
     /* for UDP checksumming, ip.len is set to UDP packet len */
     packet.ip.tot_len = packet.udp.len;
     packet.udp.check = inet_cksum(&packet,
             IP_UDP_DHCP_SIZE - padding);
     /* but for sending, it is set to IP packet len */
     packet.ip.tot_len = htons(IP_UDP_DHCP_SIZE - padding);
     packet.ip.ihl = sizeof(packet.ip) >> 2;
     packet.ip.version = IPVERSION;
     packet.ip.ttl = IPDEFTTL;
     packet.ip.check = inet_cksum(&packet.ip, sizeof(packet.ip));
     udhcp_dump_packet(dhcp_pkt);
     result = sendto(fd, &packet, IP_UDP_DHCP_SIZE - padding, /*flags:*/ 0,
             (struct sockaddr *) &dest_sll, sizeof(dest_sll));
     msg = "sendto";
  ret_close:
     close(fd);
     if (result < 0) {
  ret_msg:
         bb_perror_msg(msg, "PACKET");
     }
     return result;
 }
References AF_PACKET, bb_perror_msg(), bind(), iphdr::check, close(), iphdr::daddr, ip_udp_dhcp_packet::data, DHCP_OPTIONS_BUFSIZE, DHCP_SIZE, ETH_P_IP, fd, htons(), iphdr::ihl, inet_cksum(), ip_udp_dhcp_packet::ip, IP_UDP_DHCP_SIZE, IPDEFTTL, IPPROTO_UDP, IPVERSION, memcpy, memset, offsetof, dhcp_packet::options, PF_PACKET, iphdr::protocol, iphdr::saddr, sendto(), sockaddr_ll::sll_addr, sockaddr_ll::sll_family, sockaddr_ll::sll_halen, sockaddr_ll::sll_ifindex, sockaddr_ll::sll_protocol, SOCK_DGRAM, socket(), iphdr::tot_len, iphdr::ttl, udhcp_dump_packet, udhcp_end_option(), ip_udp_dhcp_packet::udp, UDP_DHCP_SIZE, and iphdr::version.
Referenced by raw_bcast_from_client_data_ifindex(), and send_packet_to_client().
udhcp_sp_fd_set()
void udhcp_sp_fd_set (struct pollfd * pfds, int extra_fd)
Definition at line 68 of file signalpipe.c.
 {
     pfds[0].fd = READ_FD;
     pfds[0].events = POLLIN;
     pfds[1].fd = -1;
     if (extra_fd >= 0) {
         close_on_exec_on(extra_fd);
         pfds[1].fd = extra_fd;
         pfds[1].events = POLLIN;
     }
     /* this simplifies "is extra_fd ready?" tests elsewhere: */
     pfds[1].revents = 0;
 }
References close_on_exec_on(), pollfd::events, pollfd::fd, POLLIN, READ_FD, and pollfd::revents.
Referenced by udhcpc6_main(), udhcpc_main(), and udhcpd_main().
udhcp_sp_read()
int udhcp_sp_read (void)
Definition at line 85 of file signalpipe.c.
 {
     unsigned char sig;
     /* Can't block here, fd is in nonblocking mode */
     if (safe_read(READ_FD, &sig, 1) != 1)
         return 0;
     return sig;
 }
References READ_FD, and safe_read().
Referenced by udhcpc6_main(), udhcpc_main(), and udhcpd_main().
udhcp_sp_setup()
void udhcp_sp_setup (void)
Definition at line 37 of file signalpipe.c.
 {
     struct fd_pair signal_pipe;
     /* All callers also want this, so... */
     bb_sanitize_stdio();
     /* was socketpair, but it needs AF_UNIX in kernel */
     xpiped_pair(signal_pipe);
     /* usually we get fds 3 and 4, but if we get higher ones... */
     if (signal_pipe.rd != READ_FD)
         xmove_fd(signal_pipe.rd, READ_FD);
     if (signal_pipe.wr != WRITE_FD)
         xmove_fd(signal_pipe.wr, WRITE_FD);
     close_on_exec_on(READ_FD);
     close_on_exec_on(WRITE_FD);
     ndelay_on(READ_FD);
     ndelay_on(WRITE_FD);
     bb_signals(0
         + (1 << SIGUSR1)
         + (1 << SIGUSR2)
         + (1 << SIGTERM)
         , signal_handler);
 }
References bb_sanitize_stdio(), bb_signals(), close_on_exec_on(), ndelay_on(), fd_pair::rd, READ_FD, signal_handler(), SIGTERM, SIGUSR1, SIGUSR2, fd_pair::wr, WRITE_FD, xmove_fd(), and xpiped_pair.
Referenced by udhcpc6_main(), udhcpc_main(), and udhcpd_main().
udhcp_str2nip()
int FAST_FUNC udhcp_str2nip (const char * str, void * arg)
Definition at line 433 of file common.c.
 {
     len_and_sockaddr *lsa;
     lsa = host_and_af2sockaddr(str, 0, AF_INET);
     if (!lsa)
         return 0;
     /* arg maybe unaligned */
     move_to_unaligned32((uint32_t*)arg, lsa->u.sin.sin_addr.s_addr);
     free(lsa);
     return 1;
 }
References AF_INET, free, host_and_af2sockaddr, lsa, move_to_unaligned32, and str.
Referenced by read_staticlease(), and udhcp_str2optset().
udhcp_str2optset()
int FAST_FUNC udhcp_str2optset (const char * str, void * arg, const struct dhcp_optflag * optflags, const char * option_strings, bool dhcpv6)
Definition at line 558 of file common.c.
 {
     struct option_set **opt_list = arg;
     char *opt;
     char *str;
     const struct dhcp_optflag *optflag;
     struct dhcp_optflag userdef_optflag;
     unsigned optcode;
     int retval;
     /* IP_PAIR needs 8 bytes, STATIC_ROUTES needs 9 max */
     char buffer[9] ALIGNED(4);
     uint16_t *result_u16 = (uint16_t *) buffer;
     uint32_t *result_u32 = (uint32_t *) buffer;
     /* Cheat, the only *const* str possible is "" */
     str = (char *) const_str;
     opt = strtok_r(str, " \t=:", &str);
     if (!opt)
         return 0;
     optcode = bb_strtou(opt, NULL, 0);
     if (!errno && optcode < 255) {
         /* Raw (numeric) option code.
          * Initially assume binary (hex-str), but if "str" or 'str'
          * is seen later, switch to STRING.
          */
         userdef_optflag.flags = OPTION_BIN;
         userdef_optflag.code = optcode;
         optflag = &userdef_optflag;
     } else {
         optflag = &optflags[udhcp_option_idx(opt, option_strings)];
     }
     /* Loop to handle OPTION_LIST case, else execute just once */
     retval = 0;
     do {
         int length;
         char *val;
         if (optflag->flags == OPTION_BIN) {
             val = strtok_r(NULL, "", &str); /* do not split "'q w e'" */
             if (val) trim(val);
         } else
             val = strtok_r(NULL, ", \t", &str);
         if (!val)
             break;
         length = dhcp_option_lengths[optflag->flags & OPTION_TYPE_MASK];
         retval = 0;
         opt = buffer; /* new meaning for variable opt */
         switch (optflag->flags & OPTION_TYPE_MASK) {
         case OPTION_IP:
             retval = udhcp_str2nip(val, buffer);
             break;
         case OPTION_IP_PAIR:
             retval = udhcp_str2nip(val, buffer);
             val = strtok_r(NULL, ", \t/-", &str);
             if (!val)
                 retval = 0;
             if (retval)
                 retval = udhcp_str2nip(val, buffer + 4);
             break;
  case_OPTION_STRING:
         case OPTION_STRING:
         case OPTION_STRING_HOST:
 #if ENABLE_FEATURE_UDHCP_RFC3397
         case OPTION_DNS_STRING:
 #endif
             length = strnlen(val, 254);
             if (length > 0) {
                 opt = val;
                 retval = 1;
             }
             break;
 //      case OPTION_BOOLEAN: {
 //          static const char no_yes[] ALIGN1 = "no\0yes\0";
 //          buffer[0] = retval = index_in_strings(no_yes, val);
 //          retval++; /* 0 - bad; 1: "no" 2: "yes" */
 //          break;
 //      }
         case OPTION_U8:
             buffer[0] = bb_strtou32(val, NULL, 0);
             retval = (errno == 0);
             break;
         /* htonX are macros in older libc's, using temp var
          * in code below for safety */
         /* TODO: use bb_strtoX? */
         case OPTION_U16: {
             uint32_t tmp = bb_strtou32(val, NULL, 0);
             *result_u16 = htons(tmp);
             retval = (errno == 0 /*&& tmp < 0x10000*/);
             break;
         }
 //      case OPTION_S16: {
 //          long tmp = bb_strtoi32(val, NULL, 0);
 //          *result_u16 = htons(tmp);
 //          retval = (errno == 0);
 //          break;
 //      }
         case OPTION_U32: {
             uint32_t tmp = bb_strtou32(val, NULL, 0);
             *result_u32 = htonl(tmp);
             retval = (errno == 0);
             break;
         }
         case OPTION_S32: {
             int32_t tmp = bb_strtoi32(val, NULL, 0);
             *result_u32 = htonl(tmp);
             retval = (errno == 0);
             break;
         }
         case OPTION_STATIC_ROUTES: {
             /* Input: "a.b.c.d/m" */
             /* Output: mask(1 byte),pfx(0-4 bytes),gw(4 bytes) */
             unsigned mask;
             char *slash = strchr(val, '/');
             if (slash) {
                 *slash = '\0';
                 retval = udhcp_str2nip(val, buffer + 1);
                 buffer[0] = mask = bb_strtou(slash + 1, NULL, 10);
                 val = strtok_r(NULL, ", \t/-", &str);
                 if (!val || mask > 32 || errno)
                     retval = 0;
                 if (retval) {
                     length = ((mask + 7) >> 3) + 5;
                     retval = udhcp_str2nip(val, buffer + (length - 4));
                 }
             }
             break;
         }
         case OPTION_BIN:
             /* Raw (numeric) option code. Is it a string? */
             if (val[0] == '"' || val[0] == '\'') {
                 char delim = val[0];
                 char *end = last_char_is(val + 1, delim);
                 if (end) {
                     *end = '\0';
                     val++;
                     userdef_optflag.flags = OPTION_STRING;
                     goto case_OPTION_STRING;
                 }
             }
             /* No: hex-str option, handled in attach_option() */
             opt = val;
             retval = 1;
             break;
         default:
             break;
         }
         if (retval)
             attach_option(opt_list, optflag, opt, length, dhcpv6);
     } while (retval && (optflag->flags & OPTION_LIST));
     return retval;
 }
References ALIGNED(), attach_option, bb_strtoi32(), bb_strtou(), bb_strtou32(), buffer, dhcp_optflag::code, end, errno, dhcp_optflag::flags, htonl(), htons(), last_char_is(), NULL, opt, optflags, OPTION_BIN, OPTION_IP, OPTION_IP_PAIR, OPTION_LIST, OPTION_S32, OPTION_STATIC_ROUTES, OPTION_STRING, OPTION_STRING_HOST, OPTION_TYPE_MASK, OPTION_U16, OPTION_U32, OPTION_U8, retval, str, strchr(), strnlen(), strtok_r(), trim(), udhcp_option_idx(), udhcp_str2nip(), and val.
Variable Documentation
ALIGN1
const uint8_t dhcp_option_lengths [] ALIGN1 extern
Definition at line 8 of file common.c.
ALIGN2
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN const uint8_t MAC_BCAST_ADDR [6] ALIGN2 extern
Definition at line 13 of file common.c.