Fennix Userspace: Userspace/apps/base/bash/examples/loadables/seq.c File Reference
seq.c File Reference
#include <config.h>
#include <sys/types.h>
#include <stdio.h>
#include <errno.h>
#include "bashansi.h"
#include "loadables.h"
#include "bashintl.h"
Macros
#define PRIdMAX "ld"
#define FLOATMAX_CONV ""
#define strtofltmax strtod
#define FLOATMAX_FMT "%g"
#define FLOATMAX_WFMT "%0.f"
#define MAX(a, b) (((a) < (b))? (b) : (a))
Typedefs
typedef double floatmax_t
Functions
static floatmax_t getfloatmax PARAMS ((const char *))
static char *genformat PARAMS ((floatmax_t, floatmax_t, floatmax_t))
static floatmax_t getfloatmax (char *arg) const
static char * long_double_format (char const *fmt)
static int getprec (char *numbuf) const
static char * genformat (floatmax_t first, floatmax_t incr, floatmax_t last)
int print_fltseq (char *fmt, floatmax_t first, floatmax_t last, floatmax_t incr) const
int width_needed (intmax_t num)
int print_intseq (intmax_t ifirst, intmax_t ilast, intmax_t iincr)
int seq_builtin (WORD_LIST *list)
Variables
int errno
static int conversion_error = 0
static int equal_width
static char const * separator
static char const terminator [] = "\n"
static char decimal_point
char * seq_doc []
struct builtin seq_struct
Macro Definition Documentation
FLOATMAX_CONV
#define FLOATMAX_CONV ""
Definition at line 59 of file seq.c.
FLOATMAX_FMT
#define FLOATMAX_FMT "%g"
Definition at line 61 of file seq.c.
FLOATMAX_WFMT
#define FLOATMAX_WFMT "%0.f"
Definition at line 62 of file seq.c.
MAX
#define MAX (a, b) (((a) < (b))? (b) : (a))
Definition at line 67 of file seq.c.
PRIdMAX
#define PRIdMAX "ld"
Definition at line 46 of file seq.c.
strtofltmax
#define strtofltmax strtod
Definition at line 60 of file seq.c.
Typedef Documentation
floatmax_t
typedef double floatmax_t
Definition at line 58 of file seq.c.
Function Documentation
genformat()
static char* genformat (floatmax_t first, floatmax_t incr, floatmax_t last) static
Definition at line 199 of file seq.c.
 {
   static char buf[6 + 2 * INT_STRLEN_BOUND (int)];
   int wfirst, wlast, width;
   int iprec, fprec, lprec, prec;
   if (equal_width == 0)
     return (FLOATMAX_FMT);
   /* OK, we have to figure out the largest number of decimal places. This is
      a little more expensive than using the original strings. */
   snprintf (buf, sizeof (buf), FLOATMAX_FMT, incr);
   iprec = getprec (buf);
   wfirst = snprintf (buf, sizeof (buf), FLOATMAX_FMT, first);
   fprec = getprec (buf);
   prec = MAX (fprec, iprec);
   wlast = snprintf (buf, sizeof (buf), FLOATMAX_FMT, last);
   lprec = getprec (buf);
   /* increase first width by any increased precision in increment */
   wfirst += (prec - fprec);
   /* adjust last width to use precision from first/incr */
   wlast += (prec - lprec);
   if (lprec && prec == 0)
     wlast--;        /* no decimal point */
   if (lprec == 0 && prec)
     wlast++;        /* include decimal point */
   if (fprec == 0 && prec)
     wfirst++;       /* include decimal point */
   width = MAX (wfirst, wlast);
   if (width)
     sprintf (buf, "%%0%d.%d%sf", width, prec, FLOATMAX_CONV);
   else
     sprintf (buf, "%%.%d%sf", prec, FLOATMAX_CONV);
   return buf;
 }
References buf, equal_width, first, FLOATMAX_CONV, FLOATMAX_FMT, getprec(), INT_STRLEN_BOUND, last, MAX, prec, snprintf(), sprintf(), and width.
Referenced by seq_builtin().
getfloatmax()
static floatmax_t getfloatmax (char * arg) const static
Definition at line 84 of file seq.c.
 {
   floatmax_t ret;
   char *ep;
   errno = 0;
   ret = strtofltmax (arg, &ep);
   if (*ep)
     {
       sh_invalidnum ((char *)arg);
       conversion_error = 1;
     }
   else if (errno == ERANGE)
     {
       builtin_error ("warning: %s: %s", arg, strerror(ERANGE));
       conversion_error = 1;
     }
   if (ret == -0.0)
     ret = 0.0;
   return (ret);
 }
References builtin_error(), conversion_error, ERANGE, errno, sh_invalidnum(), strerror(), and strtofltmax.
Referenced by seq_builtin().
getprec()
static int getprec (char * numbuf) const static
Definition at line 184 of file seq.c.
 {
   int p;
   char *dp;
   if (dp = strchr (numbuf, decimal_point))
     dp++;       /* skip over decimal point */
   for (p = 0; dp && *dp && ISDIGIT (*dp); dp++)
     p++;
   return p;
 }
References decimal_point, ISDIGIT, p, and strchr().
Referenced by genformat().
long_double_format()
static char* long_double_format (char const * fmt) static
Definition at line 114 of file seq.c.
 {
   size_t i;
   size_t length_modifier_offset;
   int has_L;
   for (i = 0; ! (fmt[i] == '%' && fmt[i + 1] != '%'); i += (fmt[i] == '%') + 1)
     {
       if (!fmt[i])
     {
       builtin_error ("format %s has no %% directive", fmt);
       return 0;
     }
     }
   i++;
   i += strspn (fmt + i, "-+#0 '");  /* zero or more flags */
   i += strspn (fmt + i, "0123456789");  /* optional minimum field width */
   if (fmt[i] == '.')            /* optional precision */
     {
       i++;
       i += strspn (fmt + i, "0123456789");
     }
   length_modifier_offset = i;       /* optional length modifier */
   /* we could ignore an 'l' length modifier here */
   has_L = (fmt[i] == 'L');
   i += has_L;
   switch (fmt[i])
     {
     case '\0':
       builtin_error ("format %s ends in %%", fmt);
       return 0;
     case 'A':
     case 'a':
     case 'e':
     case 'E':
     case 'f':
     case 'F':
     case 'g':
     case 'G':
       break;
     default:
       builtin_error ("format %s has unknown `%%%c' directive", fmt, fmt[i]);
       return 0;
     }
   for (i++; ; i += (fmt[i] == '%') + 1)
     if (fmt[i] == '%' && fmt[i + 1] != '%')
       {
         builtin_error ("format %s has too many %% directives", fmt);
         return 0;
       }
     else if (fmt[i] == 0)
       {
         size_t format_size = i + 1;
         char *ldfmt = xmalloc (format_size + 1);
         memcpy (ldfmt, fmt, length_modifier_offset);
 #ifdef USE_LONG_DOUBLE
         ldfmt[length_modifier_offset] = 'L';
         strcpy (ldfmt + length_modifier_offset + 1,
                 fmt + length_modifier_offset + has_L);
 #else
         strcpy (ldfmt + length_modifier_offset, fmt + length_modifier_offset);
 #endif
         return ldfmt;
       }
 }
References builtin_error(), i, memcpy(), strcpy(), strspn(), and xmalloc.
Referenced by seq_builtin().
PARAMS() [1/2]
static floatmax_t getfloatmax PARAMS ((const char *)) static
PARAMS() [2/2]
static char* genformat PARAMS ((floatmax_t, floatmax_t, floatmax_t)) static
print_fltseq()
int print_fltseq (char * fmt, floatmax_t first, floatmax_t last, floatmax_t incr) const
Definition at line 245 of file seq.c.
 {
   int n;
   floatmax_t next;
   const char *s;
   n = 0;        /* iteration counter */
   s = "";
   for (next = first; incr >= 0 ? (next <= last) : (next >= last); next = first + n * incr)
     {
       QUIT;
       if (*s && fputs (s, stdout) == EOF)
     return (sh_chkwrite (EXECUTION_FAILURE));
       if (printf (fmt, next) < 0)
     return (sh_chkwrite (EXECUTION_FAILURE));
       s = separator;
       n++;
     }
   if (n > 0 && fputs (terminator, stdout) == EOF)
     return (sh_chkwrite (EXECUTION_FAILURE));
   return (sh_chkwrite (EXECUTION_SUCCESS));
 }
References EOF, EXECUTION_FAILURE, EXECUTION_SUCCESS, first, fputs, last, n, next, printf(), QUIT, s, separator, sh_chkwrite(), stdout, and terminator.
Referenced by seq_builtin().
print_intseq()
int print_intseq (intmax_t ifirst, intmax_t ilast, intmax_t iincr)
Definition at line 288 of file seq.c.
 {
   char intwfmt[6 + INT_STRLEN_BOUND(int) + sizeof (PRIdMAX)];
   const char *s;
   intmax_t i, next;
   /* compute integer format string */
   if (equal_width)  /* -w supplied */
     {
       int wfirst, wlast, width;
       wfirst = width_needed (ifirst);
       wlast = width_needed (ilast);
       width = MAX(wfirst, wlast);
       /* The leading %s is for the separator */
       snprintf (intwfmt, sizeof (intwfmt), "%%s%%0%u" PRIdMAX, width);
     }
   /* We could use braces.c:mkseq here but that allocates lots of memory */
   s = "";
   for (i = ifirst; (ifirst <= ilast) ? (i <= ilast) : (i >= ilast); i = next)
     {
       QUIT;
       /* The leading %s is for the separator */
       if (printf (equal_width ?  intwfmt : "%s%" PRIdMAX, s, i) < 0)
     return (sh_chkwrite (EXECUTION_FAILURE));
       s = separator;
       next = i + iincr;
     }
   if (fputs (terminator, stdout) == EOF)
     return (sh_chkwrite (EXECUTION_FAILURE));
   return (sh_chkwrite (EXECUTION_SUCCESS));
 }
References EOF, equal_width, EXECUTION_FAILURE, EXECUTION_SUCCESS, fputs, i, INT_STRLEN_BOUND, MAX, next, PRIdMAX, printf(), QUIT, s, separator, sh_chkwrite(), snprintf(), stdout, terminator, width, and width_needed().
Referenced by seq_builtin().
seq_builtin()
int seq_builtin (WORD_LIST * list)
Definition at line 326 of file seq.c.
 {
   floatmax_t first, last, incr;
   intmax_t ifirst, ilast, iincr;
   WORD_LIST *l;
   int opt, nargs, intseq, freefmt;
   char *first_str, *incr_str, *last_str;
   char const *fmtstr;       /* The printf(3) format used for output.  */
   equal_width = 0;
   separator = "\n";
   fmtstr = NULL;
   first = 1.0;
   last = 0.0;
   incr = 0.0;       /* set later */
   ifirst = ilast = iincr = 0;
   first_str = incr_str = last_str = 0;
   intseq = freefmt = 0;
   opt = 0;
   reset_internal_getopt ();
   while (opt != -1)
     {
       l = lcurrent ? lcurrent : list;
       if (l && l->word && l->word->word && l->word->word[0] == '-' &&
        (l->word->word[1] == '.' || DIGIT (l->word->word[1])))
     {
       loptend = l;
       break;    /* negative number */
     }
       if ((opt = internal_getopt (list, "f:s:w")) == -1)
         break;
       switch (opt)
     {
     case 'f':
       fmtstr = list_optarg;
       break;
     case 's':
       separator = list_optarg;
       break;
     case 'w':
       equal_width = 1;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   if (list == 0)
     {
       builtin_usage ();
       return (EXECUTION_FAILURE);
     }
   for (nargs = 1, l = list; l->next; l = l->next)
     nargs++;
   if (nargs > 3)
     {
       builtin_usage ();
       return (EXECUTION_FAILURE);
     }
   /* LAST */
   conversion_error = 0;
   last = getfloatmax (last_str = l->word->word);
   if (conversion_error)
     return (EXECUTION_FAILURE);
   /* FIRST LAST */
   if (nargs > 1)
     {
       conversion_error = 0;
       first = getfloatmax (first_str = list->word->word);
       if (conversion_error)
     return (EXECUTION_FAILURE);
     }
   /* FIRST INCR LAST */
   if (nargs > 2)
     {
       conversion_error = 0;
       incr = getfloatmax (incr_str = list->next->word->word);
       if (conversion_error)
     return (EXECUTION_FAILURE);
       if (incr == 0.0)
     {
       builtin_error ("zero %screment", (first < last) ?  "in" : "de");
       return (EXECUTION_FAILURE);
     }
     }
   /* Sanitize arguments */
   if (incr == 0.0)
     incr = (first <= last) ?  1.0 : -1.0;
   if ((incr < 0.0 && first < last) || (incr > 0 && first > last))
     {
       builtin_error ("incorrect %screment", (first < last) ?  "in" : "de");
       return (EXECUTION_FAILURE);
     }
   /* validate format here */
   if (fmtstr)
     {
       fmtstr = long_double_format (fmtstr);
       freefmt = 1;
       if (fmtstr == 0)
     return (EXECUTION_FAILURE);
     }
   if (fmtstr != NULL && equal_width)
     {
       builtin_warning ("-w ignored when the format string is specified");
       equal_width = 0;
     }
   /* Placeholder for later additional conditions */
   if (last_str && all_digits (last_str) &&
       (first_str == 0 || all_digits (first_str)) &&
       (incr_str == 0 || all_digits (incr_str)) &&
       fmtstr == NULL)
     intseq = 1;
   if (intseq)
     {
       ifirst = (intmax_t)first; /* truncation */
       ilast = (intmax_t)last;
       iincr = (intmax_t)incr;
       return (print_intseq (ifirst, ilast, iincr));
     }
   decimal_point = locale_decpoint ();
   if (fmtstr == NULL)
     fmtstr = genformat (first, incr, last);
   print_fltseq (fmtstr, first, last, incr);
   if (freefmt)
     free ((void *)fmtstr);
   return sh_chkwrite (EXECUTION_SUCCESS);
 }
References all_digits(), builtin_error(), builtin_usage(), builtin_warning(), CASE_HELPOPT, conversion_error, decimal_point, DIGIT, equal_width, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, first, fmtstr(), free, genformat(), getfloatmax(), internal_getopt(), l, last, lcurrent, list(), list_optarg, locale_decpoint(), long_double_format(), loptend, node::next, NULL, opt, print_fltseq(), print_intseq(), reset_internal_getopt(), separator, and sh_chkwrite().
width_needed()
int width_needed (intmax_t num)
Definition at line 273 of file seq.c.
 {
   int ret;
   ret = num < 0;        /* sign */
   if (ret)
     num = -num;
   do
     ret++;
   while (num /= 10);
   return ret;
 }
References num.
Referenced by print_intseq().
Variable Documentation
conversion_error
int conversion_error = 0 static
Definition at line 69 of file seq.c.
Referenced by getfloatmax(), and seq_builtin().
decimal_point
char decimal_point static
Definition at line 80 of file seq.c.
Referenced by getprec(), and seq_builtin().
equal_width
int equal_width static
Definition at line 72 of file seq.c.
Referenced by genformat(), print_intseq(), and seq_builtin().
errno
int errno extern
Referenced by getfloatmax(), and seq_main().
separator
char const* separator static
Definition at line 75 of file seq.c.
Referenced by _print_word_list(), command_print_word_list(), print_flags_separated(), print_fltseq(), print_intseq(), print_word_list(), and seq_builtin().
seq_doc
char* seq_doc[]
Initial value:
= {
    "Print numbers from FIRST to LAST, in steps of INCREMENT.",
    "",
    "-f FORMAT    use printf style floating-point FORMAT",
    "-s STRING    use STRING to separate numbers (default: \\n)",
    "-w           equalize width by padding with leading zeroes",
    "",
    "If FIRST or INCREMENT is omitted, it defaults to 1.  However, an",
    "omitted INCREMENT defaults to -1 when LAST is smaller than FIRST.",
    "The sequence of numbers ends when the sum of the current number and",
    "INCREMENT would become greater than LAST.",
    "FIRST, INCREMENT, and LAST are interpreted as floating point values.",
    "",
    "FORMAT must be suitable for printing one argument of type 'double';",
    "it defaults to %.PRECf if FIRST, INCREMENT, and LAST are all fixed point",
    "decimal numbers with maximum precision PREC, and to %g otherwise.",
    (char *)NULL
}
Definition at line 476 of file seq.c.
seq_struct
struct builtin seq_struct
Initial value:
= {
    "seq",
    seq_builtin,
    BUILTIN_ENABLED,
    seq_doc,
    "seq [-f format] [-s separator] [-w] [FIRST [INCR]] LAST",
    0
}
Definition at line 476 of file seq.c.
terminator
char const terminator[] = "\n" static
Definition at line 78 of file seq.c.
Referenced by print_fltseq(), and print_intseq().