Fennix Kernel: Kernel/FileSystem/Mounts/Teletype.cpp File Reference
Teletype.cpp File Reference
#include <filesystem.hpp>
#include <errno.h>
#include "../../kernel.h"
Functions
ReadFSFunction (tty_Write)
void Init_Teletype (Virtual *vfs_ctx)
Variables
FileSystemOperations tty_op
Function Documentation
Init_Teletype()
void Init_Teletype (Virtual * vfs_ctx)
Definition at line 39 of file Teletype.cpp.
 {
     Node *n = vfs_ctx->Create("tty", CHARDEVICE, DevFS);
     n->Operator = &tty_op;
 }
References VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), DevFS, VirtualFileSystem::Node::Operator, and tty_op.
Referenced by Main().
ReadFSFunction()
ReadFSFunction (tty_Write)
Definition at line 25 of file Teletype.cpp.
 {
     for (size_t i = 0; i < Size; i++)
         putchar(((char *)Buffer)[i]);
     Display->SetBuffer(0);
     return Size;
 }
References Display, putchar(), and Size.
Variable Documentation
tty_op
FileSystemOperations tty_op
Initial value:
= {
    .Name = "tty",
    .Write = tty_Write,
}
Definition at line 34 of file Teletype.cpp.
Referenced by Init_Teletype().