Fennix Userspace: Userspace/musl/src/thread/pthread_mutex_unlock.c File Reference
pthread_mutex_unlock.c File Reference
#include "pthread_impl.h"
Functions
int __pthread_mutex_unlock (pthread_mutex_t *m)
weak_alias (__pthread_mutex_unlock, pthread_mutex_unlock)
Function Documentation
__pthread_mutex_unlock()
int __pthread_mutex_unlock (pthread_mutex_t * m)
Definition at line 3 of file pthread_mutex_unlock.c.
 {
     pthread_t self;
     int waiters = m->_m_waiters;
     int cont;
     int type = m->_m_type & 15;
     int priv = (m->_m_type & 128) ^ 128;
     int new = 0;
     int old;
     if (type != PTHREAD_MUTEX_NORMAL) {
         self = __pthread_self();
         old = m->_m_lock;
         int own = old & 0x3fffffff;
         if (own != self->tid)
             return EPERM;
         if ((type&3) == PTHREAD_MUTEX_RECURSIVE && m->_m_count)
             return m->_m_count--, 0;
         if ((type&4) && (old&0x40000000))
             new = 0x7fffffff;
         if (!priv) {
             self->robust_list.pending = &m->_m_next;
             __vm_lock();
         }
         volatile void *prev = m->_m_prev;
         volatile void *next = m->_m_next;
         *(volatile void *volatile *)prev = next;
         if (next != &self->robust_list.head) *(volatile void *volatile *)
             ((char *)next - sizeof(void *)) = prev;
     }
     if (type&8) {
         if (old<0 || a_cas(&m->_m_lock, old, new)!=old) {
             if (new) a_store(&m->_m_waiters, -1);
             __syscall(SYS_futex, &m->_m_lock, FUTEX_UNLOCK_PI|priv);
         }
         cont = 0;
         waiters = 0;
     } else {
         cont = a_swap(&m->_m_lock, new);
     }
     if (type != PTHREAD_MUTEX_NORMAL && !priv) {
         self->robust_list.pending = 0;
         __vm_unlock();
     }
     if (waiters || cont<0)
         __wake(&m->_m_lock, 1, priv);
     return 0;
 }
References __pthread_self, __syscall, __vm_lock(), __vm_unlock(), __wake(), a_cas, a_store, a_swap, EPERM, FUTEX_UNLOCK_PI, PTHREAD_MUTEX_NORMAL, PTHREAD_MUTEX_RECURSIVE, and SYS_futex.
Referenced by __pthread_cond_timedwait(), and mtx_unlock().
weak_alias()
weak_alias (__pthread_mutex_unlock , pthread_mutex_unlock)