Fennix Userspace: Userspace/apps/base/busybox/coreutils/sleep.c File Reference
sleep.c File Reference
#include "libbb.h"
Functions
int sleep_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
sleep_main()
int sleep_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 64 of file sleep.c.
 {
     duration_t duration;
     /* Note: sleep_main may be directly called from ash as a builtin.
      * This brings some complications:
      * + we can't use xfunc here
      * + we can't use bb_show_usage
      * + applet_name can be the name of the shell
      */
     ++argv;
     if (!*argv) {
         /* Without this, bare "sleep" in ash shows _ash_ --help */
         /* (ash can be the "sh" applet as well, so check 2nd char) */
         if (ENABLE_ASH_SLEEP && applet_name[1] != 'l') {
             bb_simple_error_msg("sleep: missing operand");
             return EXIT_FAILURE;
         }
         bb_show_usage();
     }
     /* GNU sleep accepts "inf", "INF", "infinity" and "INFINITY" */
     if (strncasecmp(argv[0], "inf", 3) == 0)
         for (;;)
             sleep(INT_MAX);
 //FIXME: in ash, "sleep 123qwerty" as a builtin aborts the shell
 #if ENABLE_FEATURE_FANCY_SLEEP
     duration = 0;
     do {
         duration += parse_duration_str(*argv);
     } while (*++argv);
     sleep_for_duration(duration);
 #else /* simple */
     duration = xatou(*argv);
     sleep(duration);
 #endif
     return EXIT_SUCCESS;
 }
References applet_name, argv, bb_show_usage(), bb_simple_error_msg(), EXIT_FAILURE, EXIT_SUCCESS, INT_MAX, parse_duration_str(), sleep(), sleep_for_duration, strncasecmp, and xatou().