Fennix: Userspace/apps/base/busybox/archival/libarchive/get_header_tar_lzma.c File Reference
get_header_tar_lzma.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
char FAST_FUNC get_header_tar_lzma (archive_handle_t *archive_handle)
Function Documentation
get_header_tar_lzma()
char FAST_FUNC get_header_tar_lzma (archive_handle_t * archive_handle)
Definition at line 11 of file get_header_tar_lzma.c.
 {
     /* Can't lseek over pipes */
     archive_handle->seek = seek_by_read;
     fork_transformer_with_sig(archive_handle->src_fd, unpack_lzma_stream, "unlzma");
     archive_handle->offset = 0;
     while (get_header_tar(archive_handle) == EXIT_SUCCESS)
         continue;
     /* Can only do one file at a time */
     return EXIT_FAILURE;
 }
References EXIT_FAILURE, EXIT_SUCCESS, fork_transformer_with_sig, get_header_tar(), archive_handle_t::offset, archive_handle_t::seek, seek_by_read(), and archive_handle_t::src_fd.
Referenced by filter_accept_list_reassign().