Fennix Kernel: SymbolResolver::Symbols Class Reference
SymbolResolver::Symbols Class Reference
#include <symbols.hpp>
Data Structures
struct SymbolTable
Public Member Functions
std::vector< SymbolTable > & GetSymTable ()
void * GetImage ()
const char * GetSymbol (uintptr_t Address)
uintptr_t GetSymbol (const char *Name)
void AddSymbol (uintptr_t Address, const char *Name)
void AddSymbolInfoFromGRUB (uint64_t Num, uint64_t EntSize, uint64_t Shndx, uintptr_t Sections)
void AppendSymbols (uintptr_t ImageAddress, uintptr_t BaseAddress=0)
Symbols (uintptr_t ImageAddress)
Symbols ()
~Symbols ()
Data Fields
decltype(SymbolTableExists) & SymTableExists = this->SymbolTableExists
Private Attributes
std::vector< SymbolTable > SymTable
void * Image = nullptr
bool SymbolTableExists = false
Detailed Description
Definition at line 24 of file symbols.hpp.
Data Structure Documentation
SymbolResolver::Symbols::SymbolTable
struct SymbolResolver::Symbols::SymbolTable
Definition at line 27 of file symbols.hpp.
Data Fields
uintptr_t Address
char * FunctionName
Constructor & Destructor Documentation
Symbols() [1/2]
SymbolResolver::Symbols::Symbols (uintptr_t ImageAddress)
Definition at line 322 of file symbols.cpp.
     {
         debug("+ %#lx", this);
         this->Image = (void *)ImageAddress;
         this->AppendSymbols(ImageAddress);
     }
References AppendSymbols(), debug, and Image.
Symbols() [2/2]
SymbolResolver::Symbols::Symbols () inline
Definition at line 47 of file symbols.hpp.
 {}
~Symbols()
SymbolResolver::Symbols::~Symbols ()
Definition at line 329 of file symbols.cpp.
     {
         debug("- %#lx", this);
         debug("Freeing %d symbols",
               this->SymTable.size());
         foreach (auto tbl in this->SymTable)
             delete[] tbl.FunctionName;
     }
References debug, and SymTable.
Member Function Documentation
AddSymbol()
void SymbolResolver::Symbols::AddSymbol (uintptr_t Address, const char * Name)
Definition at line 91 of file symbols.cpp.
     {
         SymbolTable tbl{};
         tbl.Address = Address;
         tbl.FunctionName = new char[strlen(Name) + 1];
         strcpy(tbl.FunctionName, Name);
         this->SymTable.push_back(tbl);
         this->SymbolTableExists = true;
     }
References Address, SymbolResolver::Symbols::SymbolTable::Address, CPU::Name(), strcpy, strlen(), SymbolTableExists, and SymTable.
Referenced by linux_fork(), and sys_fork().
AddSymbolInfoFromGRUB()
void SymbolResolver::Symbols::AddSymbolInfoFromGRUB (uint64_t Num, uint64_t EntSize, uint64_t Shndx, uintptr_t Sections)
Referenced by Main().
AppendSymbols()
void SymbolResolver::Symbols::AppendSymbols (uintptr_t ImageAddress, uintptr_t BaseAddress = 0)
Definition at line 216 of file symbols.cpp.
     {
         /* FIXME: Get only the required headers instead of the whole file */
         if (ImageAddress == 0 ||
             Memory::Virtual().Check((void *)ImageAddress) == false)
         {
             error("Invalid image address %#lx", ImageAddress);
             return;
         }
         debug("Solving symbols for address: %#llx", ImageAddress);
 #if defined(a64) || defined(aa64)
         Elf64_Ehdr *Header = (Elf64_Ehdr *)ImageAddress;
 #elif defined(a32)
         Elf32_Ehdr *Header = (Elf32_Ehdr *)ImageAddress;
 #endif
         if (Header->e_ident[0] != 0x7F &&
             Header->e_ident[1] != 'E' &&
             Header->e_ident[2] != 'L' &&
             Header->e_ident[3] != 'F')
         {
             error("Invalid ELF header");
             return;
         }
         Elf_Shdr *ElfSections = (Elf_Shdr *)(ImageAddress + Header->e_shoff);
         Elf_Sym *ElfSymbols = nullptr;
         char *strtab = nullptr;
         size_t TotalEntries = 0;
         for (uint16_t i = 0; i < Header->e_shnum; i++)
         {
             switch (ElfSections[i].sh_type)
             {
             case SHT_SYMTAB:
                 ElfSymbols = (Elf_Sym *)(ImageAddress + ElfSections[i].sh_offset);
                 TotalEntries = ElfSections[i].sh_size / sizeof(Elf_Sym);
                 debug("Symbol table found, %d entries", TotalEntries);
                 break;
             case SHT_STRTAB:
                 if (Header->e_shstrndx == i)
                 {
                     debug("String table found, %d entries", ElfSections[i].sh_size);
                 }
                 else
                 {
                     strtab = (char *)(ImageAddress + ElfSections[i].sh_offset);
                     debug("String table found, %d entries", ElfSections[i].sh_size);
                 }
                 break;
             default:
                 break;
             }
         }
         if (ElfSymbols != nullptr && strtab != nullptr)
         {
             size_t Index, MinimumIndex;
             for (size_t i = 0; i < TotalEntries - 1; i++)
             {
                 MinimumIndex = i;
                 for (Index = i + 1; Index < TotalEntries; Index++)
                     if (ElfSymbols[Index].st_value < ElfSymbols[MinimumIndex].st_value)
                         MinimumIndex = Index;
                 Elf_Sym tmp = ElfSymbols[MinimumIndex];
                 ElfSymbols[MinimumIndex] = ElfSymbols[i];
                 ElfSymbols[i] = tmp;
             }
             while (ElfSymbols[0].st_value == 0)
             {
                 ElfSymbols++;
                 TotalEntries--;
             }
             trace("Symbol table loaded, %d entries (%ld KiB)",
                   TotalEntries, TO_KiB(TotalEntries * sizeof(SymbolTable)));
             /* TODO: maybe a checker for duplicated addresses? */
             Elf_Sym *sym = nullptr;
             const char *name = nullptr;
             for (size_t i = 0, g = TotalEntries; i < g; i++)
             {
                 sym = &ElfSymbols[i];
                 name = &strtab[ElfSymbols[i].st_name];
                 SymbolTable tbl{};
                 tbl.Address = sym->st_value + BaseAddress;
                 tbl.FunctionName = new char[strlen(name) + 1];
                 strcpy(tbl.FunctionName, name);
                 this->SymTable.push_back(tbl);
                 this->SymbolTableExists = true;
                 // debug("Symbol %d: %#llx %s", i,
                 //    this->SymTable[i].Address,
                 //    this->SymTable[i].FunctionName);
             }
         }
         if (this->SymbolTableExists)
         {
             debug("Symbol table exists, %d entries (%ld KiB)",
                   this->SymTable.size(), TO_KiB(this->SymTable.size() * sizeof(SymbolTable)));
         }
     }
References SymbolResolver::Symbols::SymbolTable::Address, CPU::Check, debug, elf64_hdr::e_ident, elf64_hdr::e_shnum, elf64_hdr::e_shoff, elf64_hdr::e_shstrndx, error, SHT_STRTAB, SHT_SYMTAB, strcpy, strlen(), SymbolTableExists, SymTable, TO_KiB, and trace.
Referenced by Symbols().
GetImage()
void* SymbolResolver::Symbols::GetImage () inline
Definition at line 40 of file symbols.hpp.
 { return this->Image; }
References Image.
GetSymbol() [1/2]
uintptr_t SymbolResolver::Symbols::GetSymbol (const char * Name)
Definition at line 60 of file symbols.cpp.
     {
         SymbolTable Result{};
         if (this->SymbolTableExists == false)
         {
             debug("Symbol table does not exist");
             if (this->SymTable.size() > 0)
             {
                 debug("SymbolTableExists is false but SymTable.size() is %d",
                       this->SymTable.size());
             }
             return Result.Address;
         }
         std::vector<SymbolTable> rSymTable = this->SymTable;
         rSymTable.reverse();
         foreach (auto st in rSymTable)
         {
             if (unlikely(strcmp(st.FunctionName, Name) == 0))
             {
                 Result = st;
                 break;
             }
         }
         // debug("Symbol %#lx: %s", Result.Address, Result.FunctionName);
         return Result.Address;
     }
References debug, CPU::Name(), st, strcmp(), SymbolTableExists, SymTable, and unlikely.
GetSymbol() [2/2]
const NIF char * SymbolResolver::Symbols::GetSymbol (uintptr_t Address)
Definition at line 28 of file symbols.cpp.
     {
         SymbolTable Result{};
         if (this->SymbolTableExists == false)
         {
             debug("Symbol table does not exist");
             if (this->SymTable.size() > 0)
             {
                 debug("SymbolTableExists is false but SymTable.size() is %d",
                       this->SymTable.size());
             }
             return Result.FunctionName;
         }
         std::vector<SymbolTable> rSymTable = this->SymTable;
         rSymTable.reverse();
         foreach (auto st in rSymTable)
         {
             if (unlikely(st.Address <= Address &&
                          st.Address > Result.Address))
             {
                 Result = st;
                 break;
             }
         }
         // debug("Symbol %#lx: %s", Result.Address, Result.FunctionName);
         return Result.FunctionName;
     }
References Address, debug, st, SymbolTableExists, SymTable, and unlikely.
Referenced by __cxxabiv1::__cxa_atexit(), __cxxabiv1::__cxa_finalize(), __cyg_profile_func_enter(), __cyg_profile_func_exit(), __memcpy_chk(), __memmove_chk(), __memset_chk(), __strcat_chk(), __strcpy_chk(), calloc(), CrashHandler::DisplayStackFrameScreen(), free(), CrashHandler::Handle_x86_32(), CrashHandler::Handle_x86_64(), Interrupts::MainInterruptHandler(), malloc(), operator delete(), operator delete[](), operator new(), operator new[](), realloc(), Tasking::Task::Task(), CrashHandler::UserInput(), Memory::VirtualMemoryArea::VirtualMemoryArea(), and Memory::VirtualMemoryArea::~VirtualMemoryArea().
GetSymTable()
std::vector<SymbolTable>& SymbolResolver::Symbols::GetSymTable () inline
Definition at line 39 of file symbols.hpp.
 { return this->SymTable; }
References SymTable.
Referenced by linux_fork(), and sys_fork().
Field Documentation
Image
void* SymbolResolver::Symbols::Image = nullptr private
Definition at line 34 of file symbols.hpp.
Referenced by GetImage(), and Symbols().
SymbolTableExists
bool SymbolResolver::Symbols::SymbolTableExists = false private
Definition at line 35 of file symbols.hpp.
Referenced by AddSymbol(), AppendSymbols(), and GetSymbol().
SymTable
std::vector<SymbolTable> SymbolResolver::Symbols::SymTable private
Definition at line 33 of file symbols.hpp.
Referenced by AddSymbol(), AppendSymbols(), GetSymbol(), GetSymTable(), and ~Symbols().
SymTableExists
decltype(SymbolTableExists) & SymbolResolver::Symbols::SymTableExists = this->SymbolTableExists
Definition at line 38 of file symbols.hpp.
Referenced by CrashHandler::DisplayStackFrameScreen(), linux_fork(), Main(), and sys_fork().
The documentation for this class was generated from the following files:
Kernel/include/symbols.hpp
Kernel/core/symbols.cpp