Fennix Userspace: Userspace/musl/src/string/mempcpy.c File Reference
mempcpy.c File Reference
#include <string.h>
Macros
#define _GNU_SOURCE
Functions
void * mempcpy (void *dest, const void *src, size_t n)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file mempcpy.c.
Function Documentation
mempcpy()
void* mempcpy (void * dest, const void * src, size_t n)
Definition at line 4 of file mempcpy.c.
 {
     return (char *)memcpy(dest, src, n) + n;
 }
References memcpy(), n, and src.
Referenced by _nl_init_domain_conv(), add_d6_client_options(), awk_split(), bb_unsetenv(), concat_option(), dname_dec(), o_addblock(), padvance_magic(), read_alias_file(), readtoken1(), rmescapes(), run_pipe(), send_client_hello_and_alloc_hsd(), send_d6_discover(), send_d6_release(), send_d6_renew(), send_d6_select(), send_pack(), setvar(), single_quote(), stnputs(), and xmalloc_substitute_string().