Fennix Userspace: Userspace/musl/src/internal/locale_impl.h File Reference
locale_impl.h File Reference
#include <locale.h>
#include <stdlib.h>
#include "libc.h"
#include "pthread_impl.h"
Data Structures
struct __locale_map
Macros
#define LOCALE_NAME_MAX 23
#define LOC_MAP_FAILED ((const struct __locale_map *)-1)
#define LCTRANS(msg, lc, loc) __lctrans(msg, (loc)->cat[(lc)])
#define LCTRANS_CUR(msg) __lctrans_cur(msg)
#define C_LOCALE ((locale_t)&__c_locale)
#define UTF8_LOCALE ((locale_t)&__c_dot_utf8_locale)
#define CURRENT_LOCALE (__pthread_self()->locale)
#define CURRENT_UTF8 (!!__pthread_self()->locale->cat[LC_CTYPE])
#define MB_CUR_MAX (CURRENT_UTF8 ? 4 : 1)
Functions
hidden const struct __locale_map * __get_locale (int, const char *)
hidden const char * __mo_lookup (const void *, size_t, const char *)
hidden const char * __lctrans (const char *, const struct __locale_map *)
hidden const char * __lctrans_cur (const char *)
hidden const char * __lctrans_impl (const char *, const struct __locale_map *)
hidden int __loc_is_allocated (locale_t)
hidden char * __gettextdomain (void)
Variables
hidden volatile int __locale_lock [1]
hidden const struct __locale_map __c_dot_utf8
hidden const struct __locale_struct __c_locale
hidden const struct __locale_struct __c_dot_utf8_locale
Data Structure Documentation
__locale_map
struct __locale_map
Definition at line 11 of file locale_impl.h.
Data Fields
const void * map
size_t map_size
char name[LOCALE_NAME_MAX+1]
const struct __locale_map * next
Macro Definition Documentation
C_LOCALE
#define C_LOCALE ((locale_t)&__c_locale)
Definition at line 37 of file locale_impl.h.
CURRENT_LOCALE
#define CURRENT_LOCALE (__pthread_self()->locale)
Definition at line 40 of file locale_impl.h.
CURRENT_UTF8
#define CURRENT_UTF8 (!!__pthread_self()->locale->cat[LC_CTYPE])
Definition at line 42 of file locale_impl.h.
LCTRANS
#define LCTRANS (msg, lc, loc) __lctrans(msg, (loc)->cat[(lc)])
Definition at line 34 of file locale_impl.h.
LCTRANS_CUR
#define LCTRANS_CUR (msg) __lctrans_cur(msg)
Definition at line 35 of file locale_impl.h.
LOC_MAP_FAILED
#define LOC_MAP_FAILED ((const struct __locale_map *)-1)
Definition at line 32 of file locale_impl.h.
LOCALE_NAME_MAX
#define LOCALE_NAME_MAX 23
Definition at line 9 of file locale_impl.h.
MB_CUR_MAX
#define MB_CUR_MAX (CURRENT_UTF8 ? 4 : 1)
Definition at line 45 of file locale_impl.h.
UTF8_LOCALE
#define UTF8_LOCALE ((locale_t)&__c_dot_utf8_locale)
Definition at line 38 of file locale_impl.h.
Function Documentation
__get_locale()
hidden const struct __locale_map* __get_locale (int cat, const char * val)
Definition at line 34 of file locale_map.c.
 {
     static void *volatile loc_head;
     const struct __locale_map *p;
     struct __locale_map *new = 0;
     const char *path = 0, *z;
     char buf[256];
     size_t l, n;
     if (!*val) {
         (val = getenv("LC_ALL")) && *val ||
         (val = getenv(envvars[cat])) && *val ||
         (val = getenv("LANG")) && *val ||
         (val = "C.UTF-8");
     }
     /* Limit name length and forbid leading dot or any slashes. */
     for (n=0; n<LOCALE_NAME_MAX && val[n] && val[n]!='/'; n++);
     if (val[0]=='.' || val[n]) val = "C.UTF-8";
     int builtin = (val[0]=='C' && !val[1])
         || !strcmp(val, "C.UTF-8")
         || !strcmp(val, "POSIX");
     if (builtin) {
         if (cat == LC_CTYPE && val[1]=='.')
             return (void *)&__c_dot_utf8;
         return 0;
     }
     for (p=loc_head; p; p=p->next)
         if (!strcmp(val, p->name)) return p;
     if (!libc.secure) path = getenv("MUSL_LOCPATH");
     /* FIXME: add a default path? */
     if (path) for (; *path; path=z+!!*z) {
         z = __strchrnul(path, ':');
         l = z - path;
         if (l >= sizeof buf - n - 2) continue;
         memcpy(buf, path, l);
         buf[l] = '/';
         memcpy(buf+l+1, val, n);
         buf[l+1+n] = 0;
         size_t map_size;
         const void *map = __map_file(buf, &map_size);
         if (map) {
             new = malloc(sizeof *new);
             if (!new) {
                 __munmap((void *)map, map_size);
                 break;
             }
             new->map = map;
             new->map_size = map_size;
             memcpy(new->name, val, n);
             new->name[n] = 0;
             new->next = loc_head;
             loc_head = new;
             break;
         }
     }
     /* If no locale definition was found, make a locale map
      * object anyway to store the name, which is kept for the
      * sake of being able to do message translations at the
      * application level. */
     if (!new && (new = malloc(sizeof *new))) {
         new->map = __c_dot_utf8.map;
         new->map_size = __c_dot_utf8.map_size;
         memcpy(new->name, val, n);
         new->name[n] = 0;
         new->next = loc_head;
         loc_head = new;
     }
     /* For LC_CTYPE, never return a null pointer unless the
      * requested name was "C" or "POSIX". */
     if (!new && cat == LC_CTYPE) new = (void *)&__c_dot_utf8;
     return new;
 }
References __c_dot_utf8, __map_file(), __munmap(), __strchrnul(), buf, envvars, getenv, l, LC_CTYPE, libc, LOCALE_NAME_MAX, malloc, map, __locale_map::map, __locale_map::map_size, map_size, memcpy(), n, p, strcmp, and val.
Referenced by do_newlocale(), and setlocale().
__gettextdomain()
hidden char* __gettextdomain (void)
Definition at line 9 of file textdomain.c.
 {
     return current_domain ? current_domain : "messages";
 }
References current_domain.
Referenced by dcngettext(), and textdomain().
__lctrans()
hidden const char* __lctrans (const char * msg, const struct __locale_map * lm)
Definition at line 11 of file __lctrans.c.
 {
     return __lctrans_impl(msg, lm);
 }
References __lctrans_impl().
__lctrans_cur()
hidden const char* __lctrans_cur (const char * msg)
Definition at line 16 of file __lctrans.c.
 {
     return __lctrans_impl(msg, CURRENT_LOCALE->cat[LC_MESSAGES]);
 }
References __lctrans_impl(), CURRENT_LOCALE, and LC_MESSAGES.
Referenced by __getopt_msg().
__lctrans_impl()
hidden const char* __lctrans_impl (const char * msg, const struct __locale_map * lm)
Definition at line 15 of file locale_map.c.
 {
     const char *trans = 0;
     if (lm) trans = __mo_lookup(lm->map, lm->map_size, msg);
     return trans ? trans : msg;
 }
References __mo_lookup(), __locale_map::map, __locale_map::map_size, and trans.
Referenced by __lctrans(), and __lctrans_cur().
__loc_is_allocated()
hidden int __loc_is_allocated (locale_t loc)
Definition at line 15 of file newlocale.c.
 {
     return loc && loc != C_LOCALE && loc != UTF8_LOCALE
         && loc != &default_locale && loc != &default_ctype_locale;
 }
References C_LOCALE, default_ctype_locale, default_locale, and UTF8_LOCALE.
Referenced by do_newlocale(), and freelocale().
__mo_lookup()
hidden const char* __mo_lookup (const void * p, size_t size, const char * s)
Definition at line 9 of file __mo_lookup.c.
 {
     const uint32_t *mo = p;
     int sw = *mo - 0x950412de;
     uint32_t b = 0, n = swapc(mo[2], sw);
     uint32_t o = swapc(mo[3], sw);
     uint32_t t = swapc(mo[4], sw);
     if (n>=size/4 || o>=size-4*n || t>=size-4*n || ((o|t)%4))
         return 0;
     o/=4;
     t/=4;
     for (;;) {
         uint32_t ol = swapc(mo[o+2*(b+n/2)], sw);
         uint32_t os = swapc(mo[o+2*(b+n/2)+1], sw);
         if (os >= size || ol >= size-os || ((char *)p)[os+ol])
             return 0;
         int sign = strcmp(s, (char *)p + os);
         if (!sign) {
             uint32_t tl = swapc(mo[t+2*(b+n/2)], sw);
             uint32_t ts = swapc(mo[t+2*(b+n/2)+1], sw);
             if (ts >= size || tl >= size-ts || ((char *)p)[ts+tl])
                 return 0;
             return (char *)p + ts;
         }
         else if (n == 1) return 0;
         else if (sign < 0)
             n /= 2;
         else {
             b += n/2;
             n -= n/2;
         }
     }
     return 0;
 }
References n, p, s, size, strcmp, swapc(), t, and tl.
Referenced by __lctrans_impl(), and dcngettext().
Variable Documentation
__c_dot_utf8
hidden const struct __locale_map __c_dot_utf8 extern
Definition at line 4 of file c_locale.c.
Referenced by __get_locale().
__c_dot_utf8_locale
hidden const struct __locale_struct __c_dot_utf8_locale extern
Definition at line 4 of file c_locale.c.
__c_locale
hidden const struct __locale_struct __c_locale extern
Definition at line 4 of file c_locale.c.
__locale_lock
hidden volatile int __locale_lock[1] extern
Definition at line 31 of file locale_map.c.
Referenced by __newlocale(), and setlocale().