Fennix Kernel: Kernel/include/task.hpp File Reference
task.hpp File Reference
#include <types.h>
#include <filesystem.hpp>
#include <ints.hpp>
#include <symbols.hpp>
#include <vector.hpp>
#include <memory.hpp>
#include <atomic.hpp>
#include <ipc.hpp>
#include <debug.h>
#include <abi.h>
Data Structures
struct Tasking::TaskSecurity
struct Tasking::TaskInfo
struct Tasking::TCB
struct Tasking::PCB
class Tasking::Security
struct Tasking::Security::TokenData
class Tasking::Task
Namespaces
Tasking
Macros
#define PEXIT(Code) TaskManager->GetCurrentProcess()->ExitCode = Code
#define TEXIT(Code) TaskManager->GetCurrentThread()->ExitCode = Code
Typedefs
typedef unsigned long Tasking::IP
typedef __UINTPTR_TYPE__ Tasking::IPOffset
typedef unsigned long Tasking::UPID
typedef unsigned long Tasking::UTID
typedef __UINTPTR_TYPE__ Tasking::Token
Enumerations
enum Tasking::TaskArchitecture {
Tasking::UnknownArchitecture , Tasking::x32 , Tasking::x64 , Tasking::ARM32 ,
Tasking::ARM64
}
enum Tasking::TaskCompatibility { Tasking::UnknownPlatform , Tasking::Native , Tasking::Linux , Tasking::Windows }
enum Tasking::TaskTrustLevel { Tasking::UnknownElevation , Tasking::Kernel , Tasking::System , Tasking::User }
enum Tasking::TaskStatus {
Tasking::UnknownStatus , Tasking::Ready , Tasking::Running , Tasking::Sleeping ,
Tasking::Waiting , Tasking::Stopped , Tasking::Terminated
}
enum Tasking::TaskPriority {
Tasking::UnknownPriority = 0 , Tasking::Idle = 1 , Tasking::Low = 2 , Tasking::Normal = 5 ,
Tasking::High = 8 , Tasking::Critical = 10
}
enum Tasking::TTL {
Tasking::UnknownTrustLevel = 0b0001 , Tasking::Untrusted = 0b0010 , Tasking::Trusted = 0b0100 , Tasking::TrustedByKernel = 0b1000 ,
Tasking::FullTrust = Trusted | TrustedByKernel
}
Token Trust Level.
Functions
void TaskingScheduler_OneShot (int TimeSlice)
Data Structure Documentation
Tasking::TaskSecurity
struct Tasking::TaskSecurity
Definition at line 87 of file task.hpp.
Data Fields
bool IsCritical
bool IsDebugEnabled
bool IsKernelDebugEnabled
TaskTrustLevel TrustLevel
Token UniqueToken
Tasking::TaskInfo
struct Tasking::TaskInfo
Definition at line 96 of file task.hpp.
Data Fields
bool Affinity[256]
TaskArchitecture Architecture
TaskCompatibility Compatibility
uint64_t CurrentKernelTime
uint64_t CurrentUserTime
uint64_t Day
uint64_t Hour
uint64_t KernelTime
uint64_t Minute
uint64_t Month
uint64_t OldKernelTime
uint64_t OldUserTime
TaskPriority Priority
uint64_t Second
uint64_t SleepUntil
uint64_t SpawnTime
uint64_t Usage[256]
uint64_t UserTime
uint64_t Year
Tasking::PCB
struct Tasking::PCB
Definition at line 184 of file task.hpp.
Data Fields
vector< PCB * > Children
Symbols * ELFSymbolTable
int ExitCode
UPID ID
TaskInfo Info
IPC * IPC
Node * memDirectory
char Name[256]
PageTable4 * PageTable
PCB * Parent
Node * ProcessDirectory
TaskSecurity Security
TaskStatus Status
vector< TCB * > Threads
Tasking::Security::TokenData
struct Tasking::Security::TokenData
Definition at line 215 of file task.hpp.
Data Fields
uint64_t OwnerID
bool Process
Token token
int TrustLevel
Macro Definition Documentation
PEXIT
#define PEXIT (Code) TaskManager->GetCurrentProcess()->ExitCode = Code
Definition at line 366 of file task.hpp.
TEXIT
#define TEXIT (Code) TaskManager->GetCurrentThread()->ExitCode = Code
Definition at line 367 of file task.hpp.
Function Documentation
TaskingScheduler_OneShot()
void TaskingScheduler_OneShot (int TimeSlice)
Definition at line 110 of file Scheduler.cpp.
 {
     if (TimeSlice == 0)
         TimeSlice = Tasking::TaskPriority::Normal;
 #if defined(a64)
     ((APIC::Timer *)Interrupts::apicTimer[GetCurrentCPU()->ID])->OneShot(CPU::x86::IRQ16, TimeSlice);
 #elif defined(a32)
 #elif defined(aa64)
 #endif
 }
References GetCurrentCPU(), CPUData::ID, CPU::x86::IRQ16, Tasking::Normal, and APIC::OneShot.
Referenced by Tasking::Task::Schedule(), and Tasking::Task::~Task().