Fennix Userspace: Userspace/musl/src/network/getservbyname_r.c File Reference
getservbyname_r.c File Reference
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <inttypes.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include "lookup.h"
Macros
#define _GNU_SOURCE
#define ALIGN (sizeof(struct { char a; char *b; }) - sizeof(char *))
Functions
int getservbyname_r (const char *name, const char *prots, struct servent *se, char *buf, size_t buflen, struct servent **res)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file getservbyname_r.c.
ALIGN
#define ALIGN (sizeof(struct { char a; char *b; }) - sizeof(char *))
Definition at line 11 of file getservbyname_r.c.
Function Documentation
getservbyname_r()
int getservbyname_r (const char * name, const char * prots, struct servent * se, char * buf, size_t buflen, struct servent ** res)
Definition at line 13 of file getservbyname_r.c.
 {
     struct service servs[MAXSERVS];
     int cnt, proto, align;
     *res = 0;
     /* Don't treat numeric port number strings as service records. */
     char *end = "";
     strtoul(name, &end, 10);
     if (!*end) return ENOENT;
     /* Align buffer */
     align = -(uintptr_t)buf & ALIGN-1;
     if (buflen < 2*sizeof(char *)+align)
         return ERANGE;
     buf += align;
     if (!prots) proto = 0;
     else if (!strcmp(prots, "tcp")) proto = IPPROTO_TCP;
     else if (!strcmp(prots, "udp")) proto = IPPROTO_UDP;
     else return EINVAL;
     cnt = __lookup_serv(servs, name, proto, 0, 0);
     if (cnt<0) switch (cnt) {
     case EAI_MEMORY:
     case EAI_SYSTEM:
         return ENOMEM;
     default:
         return ENOENT;
     }
     se->s_name = (char *)name;
     se->s_aliases = (void *)buf;
     se->s_aliases[0] = se->s_name;
     se->s_aliases[1] = 0;
     se->s_port = htons(servs[0].port);
     se->s_proto = servs[0].proto == IPPROTO_TCP ? "tcp" : "udp";
     *res = se;
     return 0;
 }
References __lookup_serv(), ALIGN, buf, buflen, cnt, EAI_MEMORY, EAI_SYSTEM, EINVAL, end, ENOENT, ENOMEM, ERANGE, htons(), IPPROTO_TCP, IPPROTO_UDP, MAXSERVS, port, service::proto, servent::s_aliases, servent::s_name, servent::s_port, servent::s_proto, strcmp, and strtoul().
Referenced by getservbyname().