Fennix Userspace: Userspace/apps/base/bash/lib/readline/examples/rltest.c File Reference
rltest.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <readline/readline.h>
#include <readline/history.h>
Functions
void exit ()
HIST_ENTRY ** history_list ()
int main ()
Function Documentation
exit()
void exit ()
Referenced by main().
history_list()
HIST_ENTRY** history_list ()
Definition at line 180 of file history.c.
 {
   return (the_history);
 }
References the_history.
Referenced by _rl_isearch_init(), history_do_write(), history_search_internal(), main(), rl_clear_history(), and rl_get_previous_history().
main()
int main (void)
Definition at line 54 of file rltest.c.
 {
   char *temp, *prompt;
   int done;
 #ifdef HAVE_SETLOCALE
   setlocale (LC_ALL, "");
 #endif
   temp = (char *)NULL;
   prompt = "readline$ ";
   done = 0;
   while (!done)
     {
       temp = readline (prompt);
       /* Test for EOF. */
       if (!temp)
     exit (1);
       /* If there is anything on the line, print it and remember it. */
       if (*temp)
     {
       fprintf (stderr, "%s\r\n", temp);
       add_history (temp);
     }
       /* Check for `command' that we handle. */
       if (strcmp (temp, "quit") == 0)
     done = 1;
       if (strcmp (temp, "list") == 0)
     {
       HIST_ENTRY **list;
       register int i;
       list = history_list ();
       if (list)
         {
           for (i = 0; list[i]; i++)
         fprintf (stderr, "%d: %s\r\n", i, list[i]->line);
         }
     }
       free (temp);
     }
   exit (0);
 }
References add_history(), done, exit(), fprintf(), free, history_list(), i, LC_ALL, list(), NULL, prompt, readline(), setlocale, stderr, and strcmp.