Fennix Userspace: Userspace/musl/src/ipc/semget.c File Reference
semget.c File Reference
#include <sys/sem.h>
#include <limits.h>
#include <errno.h>
#include "syscall.h"
#include "ipc.h"
Functions
int semget (key_t key, int n, int fl)
Function Documentation
semget()
int semget (key_t key, int n, int fl)
Definition at line 7 of file semget.c.
 {
     /* The kernel uses the wrong type for the sem_nsems member
      * of struct semid_ds, and thus might not check that the
      * n fits in the correct (per POSIX) userspace type, so
      * we have to check here. */
     if (n > USHRT_MAX) return __syscall_ret(-EINVAL);
 #ifndef SYS_ipc
     return syscall(SYS_semget, key, n, fl);
 #else
     return syscall(SYS_ipc, IPCOP_semget, key, n, fl);
 #endif
 }
References __syscall_ret(), EINVAL, IPCOP_semget, n, syscall(), and USHRT_MAX.
Referenced by ipcrm_main(), and logread_main().