Fennix Userspace: Userspace/mlibc/tests/rtdl/soname/test.c File Reference
test.c File Reference
#include <dlfcn.h>
#include <stdio.h>
#include <assert.h>
#include <string.h>
Macros
#define LIBFOO "libfoo.so"
#define LIBBAR "libbar.so"
Functions
int main ()
Macro Definition Documentation
LIBBAR
#define LIBBAR "libbar.so"
Definition at line 11 of file test.c.
LIBFOO
#define LIBFOO "libfoo.so"
Definition at line 10 of file test.c.
Function Documentation
main()
int main (void)
Definition at line 14 of file test.c.
            {
     void *foo = dlopen(LIBFOO, RTLD_NOW);
     void *bar = dlopen(LIBBAR, RTLD_NOW);
     assert(foo);
     assert(bar);
     // Since these libraries have the same SONAME, they should return the same thing.
     assert(foo == bar);
     char *(*fooSym)(void) = dlsym(foo, "name");
     char *(*barSym)(void) = dlsym(bar, "name");
     assert(fooSym && barSym);
     assert(fooSym() && barSym());
     printf("foo: name() = \"%s\"\n", fooSym());
     printf("bar: name() = \"%s\"\n", barSym());
     assert(!strcmp(fooSym(), barSym()));
     dlclose(foo);
     dlclose(bar);
 }
References assert, bar(), dlclose, dlopen, dlsym, foo(), LIBBAR, LIBFOO, printf(), RTLD_NOW, and strcmp.
Referenced by __dls2(), and _start_c().