Fennix Kernel: Kernel/core/panic/ui.cpp File Reference
ui.cpp File Reference
#include <display.hpp>
#include <bitmap.hpp>
#include <convert.h>
#include <printf.h>
#include <lock.hpp>
#include <rand.hpp>
#include <uart.hpp>
#include <debug.h>
#include <smp.hpp>
#include <cpu.hpp>
#include <io.h>
#include "../../kernel.h"
#include "kbd/keyboard.hpp"
Data Structures
struct StackFrame
struct x86ExceptionName
Functions
void ExPrint (const char *Format,...)
void DiagnosticDataCollection ()
void InitFont ()
nsa const char * ExGetKSymbolByAddress (uintptr_t Address)
nsa const char * ExGetKSymbol (CPU::ExceptionFrame *Frame)
nsa char * TrimWhiteSpace (char *str)
nsa void ExDumpData (void *Address, unsigned long Length)
nsa void DisplayTopOverlay ()
nsa void DisplayBottomOverlay ()
nsa void DisplayMainScreen (CPU::ExceptionFrame *Frame)
nsa void DisplayDetailsScreen (CPU::ExceptionFrame *Frame)
nsa void DisplayStackScreen (CPU::ExceptionFrame *Frame)
nsa void DisplayProcessScreen (CPU::ExceptionFrame *Frame, bool IgnoreReady=true)
void UserInput (char *Input)
void ArrowInput (uint8_t key)
nsa void DisplayCrashScreen (CPU::ExceptionFrame *Frame)
nsa void DisplayStackSmashing ()
nsa void DisplayBufferOverflow ()
nsa void DisplayAssertionFailed (const char *File, int Line, const char *Expression)
Variables
KernelConsole::FontRenderer CrashFontRenderer
void * FbBeforePanic
x86ExceptionName x86Exceptions []
static const char * x86PageFaultDescriptions [9]
int ActiveScreen = 0
char __modSym [20]
CPU::ExceptionFrame * ExFrame
Data Structure Documentation
StackFrame
struct StackFrame
Definition at line 49 of file ui.cpp.
Data Fields
struct StackFrame * bp
uintptr_t ip
x86ExceptionName
struct x86ExceptionName
Definition at line 55 of file ui.cpp.
Data Fields
const char * Cause
const char * Mnemonic
const char * Name
Function Documentation
ArrowInput()
void ArrowInput (uint8_t key)
Definition at line 856 of file ui.cpp.
 {
     switch (key)
     {
     case KEY_D_RIGHT:
         if (ActiveScreen < 3)
             ActiveScreen++;
         else
             return;
         break;
     case KEY_D_LEFT:
         if (ActiveScreen > 0)
             ActiveScreen--;
         else
             return;
         break;
     case KEY_D_DOWN:
     case KEY_D_UP:
     default:
         return;
     }
     Display->ClearBuffer();
     ExPrint("\x1b[2J");
     DisplayTopOverlay();
     switch (ActiveScreen)
     {
     case 0:
         DisplayMainScreen(ExFrame);
         break;
     case 1:
         DisplayDetailsScreen(ExFrame);
         break;
     case 2:
         DisplayStackScreen(ExFrame);
         break;
     case 3:
         DisplayProcessScreen(ExFrame);
         break;
     default:
         break;
     }
     DisplayBottomOverlay();
 }
References ActiveScreen, Video::Display::ClearBuffer(), Display, DisplayBottomOverlay(), DisplayDetailsScreen(), DisplayMainScreen(), DisplayProcessScreen(), DisplayStackScreen(), DisplayTopOverlay(), ExFrame, ExPrint(), KEY_D_DOWN, KEY_D_LEFT, KEY_D_RIGHT, and KEY_D_UP.
Referenced by DisplayCrashScreen(), and CrashPS2KeyboardDriver::OnInterruptReceived().
DiagnosticDataCollection()
void DiagnosticDataCollection ()
Definition at line 105 of file diag.cpp.
 {
     Display->ClearBuffer();
     DisplayTopOverlay();
     ExPrint("\nPlease wait while we collect some diagnostic information...\n");
     ExPrint("This may take a while...\n");
     mode_t mode = S_IRWXU |
                   S_IRWXG |
                   S_IROTH |
                   S_IFDIR;
     FileNode *panicDir = fs->ForceCreate(nullptr, "/var/panic", mode);
     if (!panicDir)
     {
         ExPrint("\x1b[0;30;41mFailed to create /var/panic\x1b[0m\n");
         Display->UpdateBuffer();
         return;
     }
     FileNode *dumpFile;
     Time::Clock clock = Time::ReadClock();
     char filename[64];
     for (int i = 0; i < INT32_MAX; i++)
     {
         sprintf(filename, "dump-%d-%d-%d-%d.dmp",
                 clock.Year, clock.Month, clock.Day, i);
         if (fs->PathExists(filename, panicDir))
             continue;
         mode = S_IRWXU |
                S_IRWXG |
                S_IROTH |
                S_IFREG;
         dumpFile = fs->Create(panicDir, filename, mode);
         break;
     }
     if (!WriteDiagDataToNode(dumpFile))
         return;
     ExPrint("You can find the diagnostic file in /var/panic/%s\n", filename);
     Display->UpdateBuffer();
 }
References Video::Display::ClearBuffer(), vfs::Virtual::Create(), Time::Clock::Day, Display, DisplayTopOverlay(), ExPrint(), vfs::Virtual::ForceCreate(), fs, INT32_MAX, Time::Clock::Month, vfs::Virtual::PathExists(), Time::ReadClock(), S_IFDIR, S_IFREG, S_IROTH, S_IRWXG, S_IRWXU, sprintf(), Video::Display::UpdateBuffer(), WriteDiagDataToNode(), and Time::Clock::Year.
Referenced by UserInput().
DisplayAssertionFailed()
nsa void DisplayAssertionFailed (const char * File, int Line, const char * Expression)
Definition at line 804 of file ui.cpp.
 {
     InitFont();
     ExPrint("\x1b[2J\x1b[H");
     Display->ClearBuffer();
     DisplayTopOverlay();
     ExPrint("\nWe're sorry, but the system has encountered a critical error and needs to restart.\n");
     ExPrint("\nError: Assertion Failed\n");
     ExPrint("In file \"%s\" at line %d, \"%s\" failed\n",
             File, Line, Expression);
     CPUData *core = GetCurrentCPU();
     if (TaskManager && core->CurrentProcess.load() && core->CurrentThread.load())
     {
         ExPrint("Core: %d / pid: %d / tid: %d\n", core->ID,
                 core->CurrentProcess->ID, core->CurrentThread->ID);
     }
     else if (core->IsActive)
         ExPrint("Core: %d\n", core->ID);
     ExPrint("\nWhat to do:\n");
     ExPrint(" This is a kernel bug.\n");
     ExPrint(" Please create a new issue on https://github.com/Fennix-Project/Fennix for further assistance.\n");
     CPU::ExceptionFrame ef;
     // Fill only the necessary fields
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wframe-address"
     /* Jump over HandleAssertionFailed, and ip will be the function where it failed */
     void *fun = __builtin_return_address(1);
     /* Jump over this, HandleAssertionFailed & ip */
     void *stk = __builtin_frame_address(2);
 #pragma GCC diagnostic pop
 #ifdef __x86_64__
     asmv("movq %%cr3, %0" : "=r"(ef.cr3));
     ef.rip = (uint64_t)fun;
     ef.rbp = ef.rsp = (uint64_t)stk;
 #elif defined(__i386__)
     asmv("movl %%cr3, %0" : "=r"(ef.cr3));
     ef.eip = (uint32_t)fun;
     ef.ebp = ef.esp = (uint32_t)stk;
 #endif
     DisplayStackScreen(&ef);
     /* TODO: Add additional info */
 }
References asmv(), Video::Display::ClearBuffer(), CPUData::CurrentProcess, CPUData::CurrentThread, Display, DisplayStackScreen(), DisplayTopOverlay(), Expression, ExPrint(), GetCurrentCPU(), CPUData::ID, InitFont(), CPUData::IsActive, Line, and TaskManager.
Referenced by HandleAssertionFailed().
DisplayBottomOverlay()
nsa void DisplayBottomOverlay ()
Definition at line 292 of file ui.cpp.
 {
     ExPrint("\x1b[%d;%dH> \x1b[1;37m", (Display->GetWidth / CrashFontRenderer.CurrentFont->GetInfo().Width) - 1, 1);
 }
References CrashFontRenderer, KernelConsole::FontRenderer::CurrentFont, Display, ExPrint(), Video::Font::GetInfo(), Video::Display::GetWidth, and Video::FontInfo::Width.
Referenced by ArrowInput(), DisplayCrashScreen(), and UserInput().
DisplayBufferOverflow()
nsa void DisplayBufferOverflow ()
Definition at line 778 of file ui.cpp.
 {
     InitFont();
     ExPrint("\x1b[2J\x1b[H");
     Display->ClearBuffer();
     DisplayTopOverlay();
     ExPrint("\nWe're sorry, but the system has encountered a critical error and needs to restart.\n");
     ExPrint("\nError: Buffer Overflow In Kernel Mode\n");
     CPUData *core = GetCurrentCPU();
     if (TaskManager)
     {
         ExPrint("Core: %d / pid: %d / tid: %d\n", core->ID,
                 core->CurrentProcess->ID, core->CurrentThread->ID);
     }
     else if (core->IsActive)
         ExPrint("Core: %d\n", core->ID);
     ExPrint("\nWhat to do:\n");
     ExPrint(" This is a kernel bug.\n");
     ExPrint(" Please create a new issue on https://github.com/Fennix-Project/Fennix for further assistance.\n");
     /* TODO: Add additional info */
 }
References Video::Display::ClearBuffer(), CPUData::CurrentProcess, CPUData::CurrentThread, Display, DisplayTopOverlay(), ExPrint(), GetCurrentCPU(), CPUData::ID, InitFont(), CPUData::IsActive, and TaskManager.
Referenced by HandleBufferOverflow().
DisplayCrashScreen()
nsa void DisplayCrashScreen (CPU::ExceptionFrame * Frame)
Definition at line 625 of file ui.cpp.
 {
     ExFrame = Frame;
     /* TODO */
     // void *BufferBeforeUpdate = KernelAllocator.RequestPages(TO_PAGES(Display->GetSize));
     // if (BufferBeforeUpdate)
     //  memcpy(BufferBeforeUpdate, Display->GetBuffer, Display->GetSize);
     Display->ClearBuffer();
     ExPrint("\x1b[2J\x1b[H");
     if (Config.InterruptsOnCrash == false)
     {
         DisplayMainScreen(Frame);
         CPU::Stop();
     }
     DisplayTopOverlay();
     DisplayMainScreen(Frame);
     InitializeKeyboards();
     DisplayBottomOverlay();
 #ifdef DEBUG
     static int once = 0;
     static uint8_t com4 = 0xFF;
     if (!once++)
         com4 = inb(0x2E8);
     if (com4 == 0xFF)
         CPU::Halt(true);
     char UserInputBuffer[256]{'\0'};
     int BackSpaceLimit = 0;
     while (true)
     {
         while ((inb(0x2E8 + 5) & 1) == 0)
             CPU::Pause();
         char key = inb(0x2E8);
         // debug("key: %d", key);
         if (key == '\x7f') /* Backspace (DEL) */
         {
             if (BackSpaceLimit <= 0)
                 continue;
             char keyBuf[5] = {'\b', '\x1b', '[', 'K', '\0'};
             ExPrint(keyBuf);
             backspace(UserInputBuffer);
             BackSpaceLimit--;
             continue;
         }
         else if (key == '\x0d') /* Enter (CR) */
         {
             UserInput(UserInputBuffer);
             BackSpaceLimit = 0;
             UserInputBuffer[0] = '\0';
             continue;
         }
         else if (key == '\x1b') /* Escape */
         {
             char tmp[16]{'\0'};
             append(tmp, key);
             while ((inb(0x2E8 + 5) & 1) == 0)
                 CPU::Pause();
             char key = inb(0x2E8);
             append(tmp, key);
             if (key == '[')
             {
                 // 27 91
                 // <  68
                 // > 67
                 //  down 66
                 //  up 65
                 while ((inb(0x2E8 + 5) & 1) == 0)
                     CPU::Pause();
                 key = inb(0x2E8);
                 append(tmp, key);
                 switch (key)
                 {
                 case 'A':
                     key = KEY_D_UP;
                     break;
                 case 'B':
                     key = KEY_D_DOWN;
                     break;
                 case 'C':
                     key = KEY_D_RIGHT;
                     break;
                 case 'D':
                     key = KEY_D_LEFT;
                     break;
                 default:
                 {
                     for (size_t i = 0; i < strlen(tmp); i++)
                     {
                         if ((int)sizeof(UserInputBuffer) <= BackSpaceLimit)
                             continue;
                         append(UserInputBuffer, tmp[i]);
                         BackSpaceLimit++;
                         char keyBuf[2] = {(char)tmp[i], '\0'};
                         ExPrint(keyBuf);
                     }
                     continue;
                 }
                 }
                 ArrowInput(key);
                 continue;
             }
         }
         if ((int)sizeof(UserInputBuffer) <= BackSpaceLimit)
             continue;
         append(UserInputBuffer, key);
         BackSpaceLimit++;
         char keyBuf[2] = {(char)key, '\0'};
         ExPrint(keyBuf);
     }
 #endif
     debug("cpu halted");
     CPU::Halt(true);
 }
References append(), ArrowInput(), backspace(), Video::Display::ClearBuffer(), Config, debug, Display, DisplayBottomOverlay(), DisplayMainScreen(), DisplayTopOverlay(), ExFrame, ExPrint(), CPU::Halt(), InitializeKeyboards(), KernelConfig::InterruptsOnCrash, KEY_D_DOWN, KEY_D_LEFT, KEY_D_RIGHT, KEY_D_UP, CPU::Pause(), CPU::Stop(), strlen(), and UserInput().
Referenced by HandleException().
DisplayDetailsScreen()
nsa void DisplayDetailsScreen (CPU::ExceptionFrame * Frame)
Definition at line 341 of file ui.cpp.
 {
     ExPrint("\nException Frame:\n");
     ExPrint(" General Purpose Registers:\n");
     ExPrint("  RAX: %#lx  RBX: %#lx  RCX: %#lx  RDX: %#lx\n",
             Frame->rax, Frame->rbx, Frame->rcx, Frame->rdx);
     ExPrint("  RSI: %#lx  RDI: %#lx  R8: %#lx  R9: %#lx\n",
             Frame->rsi, Frame->rdi, Frame->r8, Frame->r9);
     ExPrint("  R10: %#lx  R11: %#lx  R12: %#lx  R13: %#lx\n",
             Frame->r10, Frame->r11, Frame->r12, Frame->r13);
     ExPrint("  R14: %#lx  R15: %#lx\n", Frame->r14, Frame->r15);
     ExPrint(" Control Registers:\n");
     ExPrint("  CR0: %#lx  CR2: %#lx  CR3: %#lx  CR4: %#lx\n",
             Frame->cr0, Frame->cr2, Frame->cr3, Frame->cr4);
     ExPrint("  CR8: %#lx\n", Frame->cr8);
     ExPrint(" Segment Registers:\n");
     ExPrint("  CS: %#lx  SS: %#lx  DS: %#lx  ES: %#lx  FS: %#lx  GS: %#lx\n",
             Frame->cs, Frame->ss, Frame->ds, Frame->es, Frame->fs, Frame->gs);
     ExPrint(" Debug Registers:\n");
     ExPrint("  DR0: %#lx  DR1: %#lx  DR2: %#lx  DR3: %#lx\n",
             Frame->dr0, Frame->dr1, Frame->dr2, Frame->dr3);
     ExPrint("  DR6: %#lx  DR7: %#lx\n", Frame->dr6, Frame->dr7);
     ExPrint(" Other:\n");
     ExPrint("  INT: %#lx  ERR: %#lx  RIP: %#lx  RFLAGS: %#lx\n",
             Frame->InterruptNumber, Frame->ErrorCode,
             Frame->rip, Frame->rflags.raw);
     ExPrint("  RSP: %#lx  RBP: %#lx\n",
             Frame->rsp, Frame->rbp);
     ExPrint("Exception Details:\n");
     switch (Frame->InterruptNumber)
     {
     case CPU::x86::PageFault:
     {
         CPU::x64::PageFaultErrorCode pfCode = {.raw = (uint32_t)Frame->ErrorCode};
         ExPrint("PFEC: P:%d W:%d U:%d R:%d I:%d PK:%d SS:%d SGX:%d\n",
                 pfCode.P, pfCode.W, pfCode.U, pfCode.R,
                 pfCode.I, pfCode.PK, pfCode.SS, pfCode.SGX);
         {
             Memory::Virtual vmm((Memory::PageTable *)Frame->cr3);
             if (vmm.GetMapType((void *)Frame->cr2) != Memory::Virtual::FourKiB)
                 ExPrint("Can't display page %#lx\n", Frame->cr2);
             else
             {
                 Memory::PageTableEntry *pte = vmm.GetPTE((void *)Frame->cr2);
                 ExPrint("Page %#lx: P:%d W:%d U:%d G:%d CoW:%d KRsv:%d NX:%d\n",
                         ALIGN_DOWN(Frame->cr2, 0x1000), pte->Present, pte->ReadWrite,
                         pte->UserSupervisor, pte->Global, pte->CopyOnWrite,
                         pte->KernelReserve, pte->ExecuteDisable);
             }
         }
         ExPrint("%s", x86PageFaultDescriptions[Frame->ErrorCode & 0b111]);
         if (Frame->ErrorCode & 0x8)
             ExPrint("%s", x86PageFaultDescriptions[8]);
         break;
     }
     case CPU::x86::StackSegmentFault:
     case CPU::x86::GeneralProtectionFault:
     {
         CPU::x64::SelectorErrorCode sCode = {.raw = Frame->ErrorCode};
         ExPrint("Kernel performed an illegal operation.\n");
         ExPrint("External: %d\n", sCode.External);
         ExPrint("Table: %d\n", sCode.Table);
         ExPrint("Index: %#x\n", sCode.Idx);
         break;
     }
     default:
         ExPrint("No additional information available for this exception.\n");
         break;
     }
     if (!TaskManager)
         return;
     CPUData *core = GetCurrentCPU();
     Tasking::PCB *proc = core->CurrentProcess.load();
     Tasking::TCB *thread = core->CurrentThread.load();
     ExPrint("Exception in %s process %s(%d) thread %s(%d)\n",
             proc->Security.ExecutionMode == Tasking::User ? "user" : "kernel",
             proc->Name, proc->ID,
             thread->Name, thread->ID);
 }
References ALIGN_DOWN, CPUData::CurrentProcess, CPUData::CurrentThread, ExPrint(), Memory::Virtual::FourKiB, CPU::x86::GeneralProtectionFault, GetCurrentCPU(), Memory::Virtual::GetMapType(), Memory::Virtual::GetPTE(), Tasking::TCB::ID, Tasking::PCB::ID, Tasking::TCB::Name, Tasking::PCB::Name, CPU::x86::PageFault, CPU::x64::PageFaultErrorCode::raw, CPU::x64::SelectorErrorCode::raw, Tasking::PCB::Security, CPU::x86::StackSegmentFault, TaskManager, Tasking::User, and x86PageFaultDescriptions.
Referenced by ArrowInput().
DisplayMainScreen()
nsa void DisplayMainScreen (CPU::ExceptionFrame * Frame)
Definition at line 297 of file ui.cpp.
 {
     ExPrint("\nWe're sorry, but the system has encountered a critical error and needs to restart.\n");
     ExPrint("\nError: %s (%s 0x%x)\n",
 #if defined(a86)
             x86Exceptions[Frame->InterruptNumber].Name,
             x86Exceptions[Frame->InterruptNumber].Mnemonic,
 #elif defined(aa64)
 #error "AA64 not implemented"
 #endif
             Frame->InterruptNumber);
 #if defined(a86)
     ExPrint("Cause: %s\n", x86Exceptions[Frame->InterruptNumber].Cause);
 #endif
     ExPrint("Exception occurred in function %s (%#lx)\n",
             ExGetKSymbol(Frame),
 #if defined(a64)
             Frame->rip);
 #elif defined(a32)
             Frame->eip);
 #elif defined(aa64)
             Frame->pc);
 #endif
     CPUData *core = GetCurrentCPU();
     if (TaskManager)
     {
         ExPrint("Core: %d / pid: %d / tid: %d\n", core->ID,
                 core->CurrentProcess->ID, core->CurrentThread->ID);
     }
     else if (core->IsActive)
         ExPrint("Core: %d\n", core->ID);
     ExPrint("\nWhat to do:\n");
     ExPrint("  1. Restart your device and see if the problem persists.\n");
     ExPrint("  2. Remove any newly installed hardware.\n");
     ExPrint("  3. Check for any available updates for your operating system.\n");
     ExPrint("  4. Uninstall any recently installed drivers or software.\n");
     ExPrint("  If none of the above steps resolve the issue, create a new issue on https://github.com/Fennix-Project/Fennix for further assistance.\n");
     ExPrint("\nUse command 'diag' to create a diagnostic report.\n");
 }
References x86ExceptionName::Cause, CPUData::CurrentProcess, CPUData::CurrentThread, error, ExGetKSymbol(), ExPrint(), GetCurrentCPU(), CPUData::ID, CPUData::IsActive, x86ExceptionName::Mnemonic, x86ExceptionName::Name, TaskManager, and x86Exceptions.
Referenced by ArrowInput(), and DisplayCrashScreen().
DisplayProcessScreen()
nsa void DisplayProcessScreen (CPU::ExceptionFrame * Frame, bool IgnoreReady = true)
Definition at line 514 of file ui.cpp.
 {
     const char *StatusColor[] = {
         "31m",   // Unknown
         "1;33m", // Ready
         "32m",   // Running
         "1;33m", // Sleeping
         "1;33m", // Blocked
         "1;33m", // Stopped
         "1;33m", // Waiting
         "35m",   // Core dump
         "1;31m", // Zombie
         "31m",   // Terminated
         "1;33m", // Frozen
     };
     const char *StatusString[] = {
         "UNK", // Unknown
         "RDY", // Ready
         "RUN", // Running
         "SLP", // Sleeping
         "BLK", // Blocked
         "STP", // Stopped
         "WTG", // Waiting
         "CRD", // Core dump
         "ZMB", // Zombie
         "TRM", // Terminated
         "FRZ", // Frozen
     };
     if (!TaskManager)
     {
         ExPrint("Tasking is not initialized\n");
         return;
     }
     size_t textLimit = 32;
     if (Display->GetWidth > 800 && Display->GetHeight > 600)
         textLimit = 128;
     std::vector<Tasking::PCB *> Plist = TaskManager->GetProcessList();
     ExPrint("\nProcess list (%ld):\n", Plist.size());
     bool pRdy = false;
     bool showNote = false;
     /* FIXME: This is slow */
     foreach (auto Process in Plist)
     {
         bool ignore = true;
         if (Process->State == Tasking::Ready && IgnoreReady)
         {
             foreach (auto Thread in Process->Threads)
             {
                 if (Thread->State == Tasking::Ready)
                     continue;
                 ignore = false;
                 break;
             }
             if (ignore)
             {
                 pRdy = true;
                 debug("Ignoring ready process %s(%d)",
                       Process->Name, Process->ID);
                 showNote = true;
                 continue;
             }
         }
         ExPrint("-> %.*s%s(%ld) \x1b[%s%s\x1b[0m [exe: %s]\n",
                 textLimit, Process->Name,
                 strlen(Process->Name) > textLimit ? "..." : "",
                 Process->ID, StatusColor[Process->State.load()],
                 StatusString[Process->State.load()],
                 Process->Executable
                     ? Process->Executable->Name.c_str()
                     : "none");
         bool tRdy = false;
         foreach (auto Thread in Process->Threads)
         {
             if (Thread->State == Tasking::Ready && IgnoreReady)
             {
                 tRdy = true;
                 debug("Ignoring ready thread %s(%d)",
                       Thread->Name, Thread->ID);
                 showNote = true;
                 continue;
             }
             ExPrint("  -> %.*s%s(%ld) \x1b[%s%s\x1b[0m\n",
                     textLimit, Thread->Name,
                     strlen(Thread->Name) > textLimit ? "..." : "",
                     Thread->ID, StatusColor[Thread->State.load()],
                     StatusString[Thread->State.load()]);
         }
         if (tRdy)
             ExPrint("  -> ...\n");
     }
     if (pRdy)
         ExPrint("-> ...\n");
     if (showNote)
         ExPrint("Note: Some processes may not be displayed.\n");
 }
References debug, Display, ExPrint(), Video::Display::GetHeight, Tasking::Task::GetProcessList(), Video::Display::GetWidth, Tasking::Ready, strlen(), and TaskManager.
Referenced by ArrowInput(), and UserInput().
DisplayStackScreen()
nsa void DisplayStackScreen (CPU::ExceptionFrame * Frame)
Definition at line 430 of file ui.cpp.
 {
     Memory::Virtual vmm;
     struct StackFrame *sf;
 #if defined(a64)
     sf = (struct StackFrame *)Frame->rbp;
 #elif defined(a32)
     sf = (struct StackFrame *)Frame->ebp;
 #endif
     ExPrint("\nStack trace (%#lx):\n", sf);
     if (!vmm.Check(sf))
     {
         void *ptr = ((Memory::PageTable *)Frame->cr3)->Get(sf);
         debug("Virtual pointer %#lx -> %#lx", sf, ptr);
         if (vmm.Check(ptr))
             sf = (struct StackFrame *)ptr;
         else
         {
             ExPrint("\x1b[31m< No stack trace available. >\x1b[0m\n");
             return;
         }
     }
     /* FIXME: Get symbol offset more efficiently */
     uintptr_t fIP;
 #if defined(a64)
     fIP = Frame->rip;
 #elif defined(a32)
     fIP = Frame->eip;
 #elif defined(aa64)
     fIP = Frame->pc;
 #endif
     ExPrint("%p", (void *)fIP);
     ExPrint(" in ");
     if ((fIP >= (uintptr_t)&_kernel_start &&
          fIP <= (uintptr_t)&_kernel_end))
     {
         const char *sym = KernelSymbolTable->GetSymbol(fIP);
         ssize_t offset = fIP - KernelSymbolTable->GetSymbol(sym);
         if (offset < 0)
             offset = -offset;
         ExPrint("%s+%#lx \x1b[31m<- Exception\x1b[0m\n",
                 sym, offset);
     }
     else
         ExPrint("??? \x1b[31m<- Exception\x1b[0m\n");
     if (!sf || !sf->ip || !sf->bp)
     {
         ExPrint("\n\x1b[31m< No stack trace available. >\x1b[0m\n");
         return;
     }
     for (int i = 0; i < 16; ++i)
     {
         if (!sf->ip)
             break;
         ExPrint("%p", (void *)sf->ip);
         ExPrint(" in ");
         if ((sf->ip >= (uintptr_t)&_kernel_start &&
              sf->ip <= (uintptr_t)&_kernel_end))
         {
             const char *sym = KernelSymbolTable->GetSymbol(sf->ip);
             ssize_t offset = sf->ip - KernelSymbolTable->GetSymbol(sym);
             if (offset < 0)
                 offset = -offset;
             ExPrint("%s+%#lx\n", sym, offset);
         }
         else
             ExPrint("???\n");
         if (!vmm.Check(sf->bp))
             return;
         sf = sf->bp;
     }
 }
References _kernel_end, _kernel_start, StackFrame::bp, Memory::Virtual::Check(), debug, ExPrint(), SymbolResolver::Symbols::GetSymbol(), StackFrame::ip, and KernelSymbolTable.
Referenced by ArrowInput(), and DisplayAssertionFailed().
DisplayStackSmashing()
nsa void DisplayStackSmashing ()
Definition at line 752 of file ui.cpp.
 {
     InitFont();
     ExPrint("\x1b[2J\x1b[H");
     Display->ClearBuffer();
     DisplayTopOverlay();
     ExPrint("\nWe're sorry, but the system has encountered a critical error and needs to restart.\n");
     ExPrint("\nError: Stack Smashing In Kernel Mode\n");
     CPUData *core = GetCurrentCPU();
     if (TaskManager)
     {
         ExPrint("Core: %d / pid: %d / tid: %d\n", core->ID,
                 core->CurrentProcess->ID, core->CurrentThread->ID);
     }
     else if (core->IsActive)
         ExPrint("Core: %d\n", core->ID);
     ExPrint("\nWhat to do:\n");
     ExPrint(" This is a kernel bug.\n");
     ExPrint(" Please create a new issue on https://github.com/Fennix-Project/Fennix for further assistance.\n");
     /* TODO: Add additional info */
 }
References Video::Display::ClearBuffer(), CPUData::CurrentProcess, CPUData::CurrentThread, Display, DisplayTopOverlay(), ExPrint(), GetCurrentCPU(), CPUData::ID, InitFont(), CPUData::IsActive, and TaskManager.
Referenced by HandleStackSmashing().
DisplayTopOverlay()
nsa void DisplayTopOverlay ()
Definition at line 201 of file ui.cpp.
 {
     ExPrint("\x1b[H%s %s %s %s \x1b[0m| ",
             ActiveScreen == 0 ? "\x1b[1;37m"
                                 "MAIN   "
                               : "\x1b[0m"
                                 "M",
             ActiveScreen == 1 ? "\x1b[1;37m"
                                 "DETAIL "
                               : "\x1b[0m"
                                 "D",
             ActiveScreen == 2 ? "\x1b[1;37m"
                                 "STACK  "
                               : "\x1b[0m"
                                 "S",
             ActiveScreen == 3 ? "\x1b[1;37m"
                                 "PROCESS"
                               : "\x1b[0m"
                                 "P");
     ExPrint("%s %s %s | ", KERNEL_NAME, KERNEL_ARCH, KERNEL_VERSION);
     ExPrint("%ld | ", TO_MiB(KernelAllocator.GetFreeMemory()));
     ExPrint("%s %s", CPU::Hypervisor(), CPU::Vendor());
     ExPrint("\x1b[3;1H");
     /* https://imgflip.com/i/77slbl */
     if ((Random::rand32() % 100) >= 98)
     {
         debug("Easter egg activated!");
         int BaseXOffset = Display->GetWidth - 14;
         int BaseYOffset = 8;
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 0, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 0, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 0, 0x21852E);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 0, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 8, BaseYOffset + 1, 0x21852E);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 2, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 2, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 2, 0xFFFFFF);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 2, 0x000000);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 2, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 2, 0xFFFFFF);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 2, 0x000000);
         Display->SetPixel(BaseXOffset + 8, BaseYOffset + 2, 0x21852E);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 3, 0x21852E);
         Display->SetPixel(BaseXOffset + 0, BaseYOffset + 4, 0x21852E);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 4, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 4, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 4, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 4, 0xA84832);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 4, 0xA84832);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 4, 0xA84832);
         Display->SetPixel(BaseXOffset + 7, BaseYOffset + 4, 0xA84832);
         Display->SetPixel(BaseXOffset + 0, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 5, 0x21852E);
         Display->SetPixel(BaseXOffset + 0, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 1, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 2, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 3, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 4, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 5, BaseYOffset + 6, 0x1216FF);
         Display->SetPixel(BaseXOffset + 6, BaseYOffset + 6, 0x1216FF);
         Display->UpdateBuffer();
     }
 }
References ActiveScreen, debug, Display, ExPrint(), Video::Display::GetWidth, CPU::Hypervisor(), KernelAllocator, Random::rand32(), Video::Display::SetPixel(), TO_MiB, Video::Display::UpdateBuffer(), and CPU::Vendor().
Referenced by ArrowInput(), DiagnosticDataCollection(), DisplayAssertionFailed(), DisplayBufferOverflow(), DisplayCrashScreen(), DisplayStackSmashing(), and UserInput().
ExDumpData()
nsa void ExDumpData (void * Address, unsigned long Length)
Definition at line 169 of file ui.cpp.
 {
     ExPrint("-------------------------------------------------------------------------\n");
     unsigned char *AddressChar = (unsigned char *)Address;
     unsigned char Buffer[17];
     unsigned long Iterate;
     for (Iterate = 0; Iterate < Length; Iterate++)
     {
         if ((Iterate % 16) == 0)
         {
             if (Iterate != 0)
                 ExPrint("  %s\n", Buffer);
             ExPrint("  %04x ", Iterate);
         }
         ExPrint(" %02x", AddressChar[Iterate]);
         if ((AddressChar[Iterate] < 0x20) || (AddressChar[Iterate] > 0x7E))
             Buffer[Iterate % 16] = '.';
         else
             Buffer[Iterate % 16] = AddressChar[Iterate];
         Buffer[(Iterate % 16) + 1] = '\0';
     }
     while ((Iterate % 16) != 0)
     {
         ExPrint("   ");
         Iterate++;
     }
     ExPrint("  %s\n", Buffer);
     ExPrint("-------------------------------------------------------------------------\n\n.");
 }
References Address, Driver::Buffer, ExPrint(), and Length.
Referenced by UserInput().
ExGetKSymbol()
nsa const char* ExGetKSymbol (CPU::ExceptionFrame * Frame)
Definition at line 140 of file ui.cpp.
 {
     if (Frame->rip < (uintptr_t)&_kernel_start &&
         Frame->rip > (uintptr_t)&_kernel_end)
         return "<OUTSIDE KERNEL>";
 #if defined(a64)
     return ExGetKSymbolByAddress(Frame->rip);
 #elif defined(a32)
     return ExGetKSymbolByAddress(Frame->eip);
 #elif defined(aa64)
     return ExGetKSymbolByAddress(Frame->pc);
 #endif
 }
References _kernel_end, _kernel_start, and ExGetKSymbolByAddress().
Referenced by DisplayMainScreen().
ExGetKSymbolByAddress()
nsa const char* ExGetKSymbolByAddress (uintptr_t Address)
Definition at line 112 of file ui.cpp.
 {
     if (Address < (uintptr_t)&_kernel_start &&
         Address > (uintptr_t)&_kernel_end)
         return "<OUTSIDE KERNEL>";
     if (!KernelSymbolTable)
         return "<UNKNOWN>";
     const char *sym = KernelSymbolTable->GetSymbol(Address);
     size_t symLen = strlen(sym);
     if (symLen > 16)
     {
         strncpy(__modSym, sym, 16);
         __modSym[16] = '.';
         __modSym[17] = '.';
         __modSym[18] = '.';
         __modSym[19] = '\0';
         sym = __modSym;
     }
     if (unlikely(symLen > 128))
         warn("Symbol \"%s\" is too long! Memory corrupted?", sym);
     return sym;
 }
References __modSym, _kernel_end, _kernel_start, Address, SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, strlen(), strncpy(), unlikely, and warn.
Referenced by ExGetKSymbol().
ExPrint()
void ExPrint (const char * Format, ...)
Definition at line 90 of file handler.cpp.
 {
     va_list args;
     va_start(args, Format);
     vfctprintf(__printfWrapper, NULL, Format, args);
     va_end(args);
 }
Referenced by ArrowInput(), DisplayAssertionFailed(), DisplayBottomOverlay(), DisplayBufferOverflow(), DisplayCrashScreen(), DisplayDetailsScreen(), DisplayMainScreen(), DisplayProcessScreen(), DisplayStackScreen(), DisplayStackSmashing(), DisplayTopOverlay(), ExDumpData(), HandleExceptionInsideException(), HandleUnrecoverableException(), and UserInput().
InitFont()
void InitFont ()
Definition at line 138 of file handler.cpp.
 {
     /* Hope we won't crash here */
     if (Display == nullptr)
     {
         error("Can't initialize font without display initalized");
         CPU::Stop();
     }
     if (FbBeforePanic == nullptr)
     {
         FbPagesBeforePanic = TO_PAGES(Display->GetSize);
         FbBeforePanic = KernelAllocator.RequestPages(FbPagesBeforePanic);
         debug("Created before panic framebuffer at %#lx", FbBeforePanic);
     }
     memcpy(FbBeforePanic, Display->GetBuffer, Display->GetSize);
     if (CrashFontRenderer.CurrentFont == nullptr)
         CrashFontRenderer.CurrentFont = new Video::Font(&_binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_start,
                                                         &_binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_end,
                                                         Video::FontType::PCScreenFont2);
     if (Terminals[15] == nullptr)
     {
         size_t Cols = Display->GetWidth / CrashFontRenderer.CurrentFont->GetInfo().Width;
         size_t Rows = Display->GetHeight / CrashFontRenderer.CurrentFont->GetInfo().Height;
         Terminals[15] = new VirtualTerminal(Cols, Rows, Display->GetWidth, Display->GetHeight, paint_callback, nullptr);
     }
 }
References _binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_end, _binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_start, CrashFontRenderer, KernelConsole::FontRenderer::CurrentFont, debug, Display, error, FbBeforePanic, FbPagesBeforePanic, Video::Display::GetBuffer, Video::Display::GetHeight, Video::Font::GetInfo(), Video::Display::GetSize, Video::Display::GetWidth, Video::FontInfo::Height, KernelAllocator, memcpy(), KernelConsole::paint_callback(), Video::PCScreenFont2, CPU::Stop(), KernelConsole::Terminals, TO_PAGES, and Video::FontInfo::Width.
Referenced by DisplayAssertionFailed(), DisplayBufferOverflow(), DisplayStackSmashing(), and HandleException().
TrimWhiteSpace()
nsa char* TrimWhiteSpace (char * str)
Definition at line 155 of file ui.cpp.
 {
     char *end;
     while (*str == ' ')
         str++;
     if (*str == 0)
         return str;
     end = str + strlen(str) - 1;
     while (end > str && *end == ' ')
         end--;
     *(end + 1) = 0;
     return str;
 }
References strlen().
Referenced by UserInput().
UserInput()
void UserInput (char * Input)
Definition at line 903 of file ui.cpp.
 {
     debug("User input: %s", Input);
     Display->ClearBuffer();
     ExPrint("\x1b[2J");
     DisplayTopOverlay();
     if (strcmp(Input, "help") == 0)
     {
         ExPrint("Commands:\n");
         ExPrint("\x1b[1;37m  help              - Display this help message.\n");
         ExPrint("\x1b[0m  clear             - Clear the screen.\n");
         ExPrint("\x1b[1;37m  exit              - Shutdown the device.\n");
         ExPrint("\x1b[0m  reboot            - Reboot the device.\n");
         ExPrint("\x1b[1;37m  bitmap            - Display the kernel's bitmap.\n");
         ExPrint("\x1b[0m  mem               - Display memory information.\n");
         ExPrint("\x1b[1;37m  dump [addr] [len] - Dump [len] bytes from [addr].\n");
         ExPrint("\x1b[0m  diag              - Collect diagnostic information.\n");
         ExPrint("\x1b[1;37m  screen            - Display the final output prior to system panic.\n");
     }
     else if (strcmp(Input, "clear") == 0)
     {
         ExPrint("\x1b[2J");
         DisplayTopOverlay();
     }
     else if (strcmp(Input, "exit") == 0)
     {
         Display->ClearBuffer();
         const char msg[] = "Shutting down...";
         size_t msgLen = strlen(msg);
         size_t msgPixels = msgLen * CrashFontRenderer.CurrentFont->GetInfo().Width;
         uint32_t x = uint32_t((Display->GetWidth - msgPixels) / 2);
         uint32_t y = uint32_t((Display->GetHeight - CrashFontRenderer.CurrentFont->GetInfo().Height) / 2);
         x /= CrashFontRenderer.CurrentFont->GetInfo().Width;
         y /= CrashFontRenderer.CurrentFont->GetInfo().Height;
         ExPrint("\x1b[2J");
         ExPrint("\x1b[%d;%dH", y, x);
         ExPrint("\x1b[30;41m%s\x1b[0m\x1b[H", msg);
         PowerManager->Shutdown();
         CPU::Stop();
     }
     else if (strcmp(Input, "reboot") == 0)
     {
         Display->ClearBuffer();
         const char msg[] = "Rebooting...";
         size_t msgLen = strlen(msg);
         size_t msgPixels = msgLen * CrashFontRenderer.CurrentFont->GetInfo().Width;
         uint32_t x = uint32_t((Display->GetWidth - msgPixels) / 2);
         uint32_t y = uint32_t((Display->GetHeight - CrashFontRenderer.CurrentFont->GetInfo().Height) / 2);
         x /= CrashFontRenderer.CurrentFont->GetInfo().Width;
         y /= CrashFontRenderer.CurrentFont->GetInfo().Height;
         ExPrint("\x1b[2J");
         ExPrint("\x1b[%d;%dH", y, x);
         ExPrint("\x1b[30;41m%s\x1b[0m\x1b[H", msg);
         PowerManager->Reboot();
         CPU::Stop();
     }
     else if (strncmp(Input, "bitmap", 6) == 0)
     {
         Bitmap bm = KernelAllocator.GetPageBitmap();
         ExPrint("\n[0%%] %08ld: ", 0);
         for (size_t i = 0; i < bm.Size; i++)
         {
             if (bm.Get(i))
                 ExPrint("\x1b[31m1\x1b[0m");
             else
                 ExPrint("\x1b[32m0\x1b[0m");
             if (i % 128 == 127)
             {
                 short Percentage = s_cst(short, (i * 100) / bm.Size);
                 ExPrint("\n[%03ld%%] %08ld: ", Percentage, i);
             }
         }
         ExPrint("\n--- END OF BITMAP ---\nBitmap size: %ld\n\n.", bm.Size);
         DisplayTopOverlay();
     }
     else if (strcmp(Input, "mem") == 0)
     {
         uint64_t Total = KernelAllocator.GetTotalMemory();
         uint64_t Used = KernelAllocator.GetUsedMemory();
         uint64_t Free = KernelAllocator.GetFreeMemory();
         uint64_t Reserved = KernelAllocator.GetReservedMemory();
         ExPrint("\x1b[1;32mTotal: %ld bytes\n\x1b[1;31mUsed: %ld bytes\n\x1b[1;32mFree: %ld bytes\n\x1b[1;35mReserved: %ld bytes\n", Total, Used, Free, Reserved);
         int Progress = s_cst(int, (Used * 100) / Total);
         int ReservedProgress = s_cst(int, (Reserved * 100) / Total);
         ExPrint("\x1b[1;32m%3d%% \x1b[0m[", Progress);
         for (int i = 0; i < Progress; i++)
             ExPrint("\x1b[1;31m|");
         for (int i = 0; i < 100 - Progress; i++)
             ExPrint("\x1b[1;32m|");
         for (int i = 0; i < ReservedProgress; i++)
             ExPrint("\x1b[1;35m|");
         ExPrint("\x1b[0m]\n");
     }
     else if (strncmp(Input, "dump", 4) == 0)
     {
         char *arg = TrimWhiteSpace(Input + 4);
         char *addr = strtok(arg, " ");
         char *len = strtok(NULL, " ");
         if (addr == NULL || len == NULL)
         {
             ExPrint("\x1b[31mInvalid arguments\n");
             goto End;
         }
         uintptr_t Address = strtoul(addr, NULL, 16);
         size_t Length = strtoul(len, NULL, 10);
         uintptr_t AlignedAddress = ROUND_DOWN(Address, PAGE_SIZE);
         bool IsRangeValid = true;
         {
             Memory::Virtual vmm;
             for (uintptr_t adr = AlignedAddress;
                  adr < Address + Length;
                  adr += PAGE_SIZE)
             {
                 if (!vmm.Check((void *)adr))
                 {
                     ExPrint("\x1b[31mAddress %#lx is not mapped\n", adr);
                     IsRangeValid = false;
                 }
             }
         }
         if (IsRangeValid)
         {
             debug("Dumping %ld bytes from %#lx\n", Length, Address);
             ExDumpData((void *)Address, (unsigned long)Length);
         }
     }
     else if (strcmp(Input, "diag") == 0)
     {
         DiagnosticDataCollection();
     }
     else if (strcmp(Input, "screen") == 0)
     {
         if (unlikely(FbBeforePanic == nullptr))
         {
             ExPrint("No screen data available\n");
             goto End;
         }
         memcpy(Display->GetBuffer, FbBeforePanic, Display->GetSize);
         return;
     }
 #ifdef DEBUG
     else if (strcmp(Input, "pt") == 0)
     {
         /* Helpful for qemu "info tlb" command */
         CPU::PageTable((void *)ExFrame->cr3);
         ExPrint("Here be dragons\n");
     }
     else if (strcmp(Input, "ps") == 0)
     {
         DisplayProcessScreen(ExFrame, false);
     }
 #endif // DEBUG
     else if (strlen(Input) > 0)
         ExPrint("Unknown command: %s", Input);
     else
         ExPrint("Use the 'help' command to display a list of available commands.");
 End:
     DisplayBottomOverlay();
 }
References addr, Address, arg, Memory::Virtual::Check(), Video::Display::ClearBuffer(), CrashFontRenderer, KernelConsole::FontRenderer::CurrentFont, debug, DiagnosticDataCollection(), Display, DisplayBottomOverlay(), DisplayProcessScreen(), DisplayTopOverlay(), ExDumpData(), ExFrame, ExPrint(), FbBeforePanic, Bitmap::Get(), Video::Display::GetBuffer, Video::Display::GetHeight, Video::Font::GetInfo(), Video::Display::GetSize, Video::Display::GetWidth, Video::FontInfo::Height, KernelAllocator, len, Length, memcpy(), NULL, PAGE_SIZE, CPU::PageTable(), PowerManager, Power::Power::Reboot(), Reserved, ROUND_DOWN, Power::Power::Shutdown(), Bitmap::Size, CPU::Stop(), strcmp(), strlen(), strncmp(), strtok(), strtoul(), TrimWhiteSpace(), unlikely, and Video::FontInfo::Width.
Referenced by DisplayCrashScreen(), and CrashPS2KeyboardDriver::OnInterruptReceived().
Variable Documentation
__modSym
char __modSym[20]
Definition at line 111 of file ui.cpp.
Referenced by ExGetKSymbolByAddress().
ActiveScreen
int ActiveScreen = 0
Definition at line 109 of file ui.cpp.
Referenced by ArrowInput(), and DisplayTopOverlay().
CrashFontRenderer
KernelConsole::FontRenderer CrashFontRenderer extern
Definition at line 53 of file handler.cpp.
Referenced by BaseBufferStackError(), DisplayBottomOverlay(), HandleException(), InitFont(), paint_callback(), and UserInput().
ExFrame
CPU::ExceptionFrame* ExFrame
Definition at line 624 of file ui.cpp.
Referenced by ArrowInput(), DisplayCrashScreen(), UserInput(), and WriteDiagDataToNode().
FbBeforePanic
void* FbBeforePanic extern
Definition at line 51 of file handler.cpp.
Referenced by InitFont(), and UserInput().
x86Exceptions
x86ExceptionName x86Exceptions[]
Definition at line 63 of file ui.cpp.
Referenced by DisplayMainScreen().
x86PageFaultDescriptions
const char* x86PageFaultDescriptions[9] static
Initial value:
= {
    "Supervisor tried to read a non-present page entry\n",
    "Supervisor tried to read a page and caused a protection fault\n",
    "Supervisor tried to write to a non-present page entry\n",
    "Supervisor tried to write a page and caused a protection fault\n",
    "User tried to read a non-present page entry\n",
    "User tried to read a page and caused a protection fault\n",
    "User tried to write to a non-present page entry\n",
    "User tried to write a page and caused a protection fault\n",
    "One or more page directory entries contain reserved bits which are set to 1.\n"}
Definition at line 98 of file ui.cpp.
Referenced by DisplayDetailsScreen().