Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/gusconf.c File Reference
gusconf.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "w_wad.h"
#include "z_zone.h"
Data Structures
struct gus_config_t
Macros
#define MAX_INSTRUMENTS 256
Functions
static unsigned int MappingIndex (void)
static int SplitLine (char *line, char **fields, unsigned int max_fields)
static void ParseLine (gus_config_t *config, char *line)
static void ParseDMXConfig (char *dmxconf, gus_config_t *config)
static void FreeDMXConfig (gus_config_t *config)
static char * ReadDMXConfig (void)
static boolean WriteTimidityConfig (char *path, gus_config_t *config)
boolean GUS_WriteConfig (char *path)
Variables
char * gus_patch_path = ""
unsigned int gus_ram_kb = 1024
Data Structure Documentation
gus_config_t
struct gus_config_t
Definition at line 34 of file gusconf.c.
Data Fields
int mapping[MAX_INSTRUMENTS]
char * patch_names[MAX_INSTRUMENTS]
Macro Definition Documentation
MAX_INSTRUMENTS
#define MAX_INSTRUMENTS 256
Definition at line 32 of file gusconf.c.
Function Documentation
FreeDMXConfig()
static void FreeDMXConfig (gus_config_t * config) static
Definition at line 165 of file gusconf.c.
 {
     unsigned int i;
     for (i = 0; i < MAX_INSTRUMENTS; ++i)
     {
         free(config->patch_names[i]);
     }
 }
References free, i, MAX_INSTRUMENTS, and gus_config_t::patch_names.
Referenced by GUS_WriteConfig().
GUS_WriteConfig()
boolean GUS_WriteConfig (char * path)
Definition at line 244 of file gusconf.c.
 {
     boolean result;
     char *dmxconf;
     gus_config_t config;
     if (!strcmp(gus_patch_path, ""))
     {
         printf("You haven't configured gus_patch_path.\n");
         printf("gus_patch_path needs to point to the location of "
                "your GUS patch set.\n"
                "To get a copy of the \"standard\" GUS patches, "
                "download a copy of dgguspat.zip.\n");
         return false;
     }
     dmxconf = ReadDMXConfig();
     ParseDMXConfig(dmxconf, &config);
     result = WriteTimidityConfig(path, &config);
     FreeDMXConfig(&config);
     Z_Free(dmxconf);
     return result;
 }
References FreeDMXConfig(), gus_patch_path, ParseDMXConfig(), printf, ReadDMXConfig(), strcmp, WriteTimidityConfig(), and Z_Free().
MappingIndex()
static unsigned int MappingIndex (void) static
Definition at line 43 of file gusconf.c.
 {
     unsigned int result = gus_ram_kb / 256;
     if (result < 1)
     {
         return 1;
     }
     else if (result > 4)
     {
         return 4;
     }
     else
     {
         return result;
     }
 }
References gus_ram_kb.
Referenced by ParseLine().
ParseDMXConfig()
static void ParseDMXConfig (char * dmxconf, gus_config_t * config) static
Definition at line 129 of file gusconf.c.
 {
     char *p, *newline;
     unsigned int i;
     memset(config, 0, sizeof(gus_config_t));
     for (i = 0; i < MAX_INSTRUMENTS; ++i)
     {
         config->mapping[i] = -1;
     }
     p = dmxconf;
     for (;;)
     {
         newline = strchr(p, '\n');
         if (newline != NULL)
         {
             *newline = '\0';
         }
         ParseLine(config, p);
         if (newline == NULL)
         {
             break;
         }
         else
         {
             p = newline + 1;
         }
     }
 }
References i, gus_config_t::mapping, MAX_INSTRUMENTS, memset, newline(), NULL, p, ParseLine(), and strchr().
Referenced by GUS_WriteConfig().
ParseLine()
static void ParseLine (gus_config_t * config, char * line) static
Definition at line 108 of file gusconf.c.
 {
     char *fields[6];
     unsigned int num_fields;
     unsigned int instr_id, mapped_id;
     num_fields = SplitLine(line, fields, 6);
     if (num_fields < 6)
     {
         return;
     }
     instr_id = atoi(fields[0]);
     mapped_id = atoi(fields[MappingIndex()]);
     free(config->patch_names[instr_id]);
     config->patch_names[instr_id] = strdup(fields[5]);
     config->mapping[instr_id] = mapped_id;
 }
References atoi(), free, line, gus_config_t::mapping, MappingIndex(), gus_config_t::patch_names, SplitLine(), and strdup().
Referenced by ParseDMXConfig().
ReadDMXConfig()
static char* ReadDMXConfig (void) static
Definition at line 175 of file gusconf.c.
 {
     int lumpnum;
     unsigned int len;
     char *data;
     // TODO: This should be chosen based on gamemode == commercial:
     lumpnum = W_CheckNumForName("DMXGUS");
     if (lumpnum < 0)
     {
         lumpnum = W_GetNumForName("DMXGUSC");
     }
     len = W_LumpLength(lumpnum);
     data = Z_Malloc(len + 1, PU_STATIC, NULL);
     W_ReadLump(lumpnum, data);
     return data;
 }
References len, NULL, PU_STATIC, W_CheckNumForName(), W_GetNumForName(), W_LumpLength(), W_ReadLump(), and Z_Malloc().
Referenced by GUS_WriteConfig().
SplitLine()
static int SplitLine (char * line, char ** fields, unsigned int max_fields) static
Definition at line 61 of file gusconf.c.
 {
     unsigned int num_fields;
     char *p;
     fields[0] = line;
     num_fields = 1;
     for (p = line; *p != '\0'; ++p)
     {
         if (*p == ',')
         {
             *p = '\0';
             // Skip spaces following the comma.
             do
             {
                 ++p;
             } while (*p != '\0' && isspace(*p));
             fields[num_fields] = p;
             ++num_fields;
             --p;
             if (num_fields >= max_fields)
             {
                 break;
             }
         }
         else if (*p == '#')
         {
             *p = '\0';
             break;
         }
     }
     // Strip off trailing whitespace from the end of the line.
     p = fields[num_fields - 1] + strlen(fields[num_fields - 1]);
     while (p > fields[num_fields - 1] && isspace(*(p - 1)))
     {
         --p;
         *p = '\0';
     }
     return num_fields;
 }
References isspace, line, p, and strlen().
Referenced by ParseLine().
WriteTimidityConfig()
static boolean WriteTimidityConfig (char * path, gus_config_t * config) static
Definition at line 197 of file gusconf.c.
 {
     FILE *fstream;
     unsigned int i;
     fstream = fopen(path, "w");
     if (fstream == NULL)
     {
         return false;
     }
     fprintf(fstream, "# Autogenerated Timidity config.\n\n");
     fprintf(fstream, "dir %s\n", gus_patch_path);
     fprintf(fstream, "\nbank 0\n\n");
     for (i = 0; i < 128; ++i)
     {
         if (config->mapping[i] >= 0 && config->mapping[i] < MAX_INSTRUMENTS
          && config->patch_names[config->mapping[i]] != NULL)
         {
             fprintf(fstream, "%i %s\n",
                     i, config->patch_names[config->mapping[i]]);
         }
     }
     fprintf(fstream, "\ndrumset 0\n\n");
     for (i = 128 + 25; i < MAX_INSTRUMENTS; ++i)
     {
         if (config->mapping[i] >= 0 && config->mapping[i] < MAX_INSTRUMENTS
          && config->patch_names[config->mapping[i]] != NULL)
         {
             fprintf(fstream, "%i %s\n",
                     i - 128, config->patch_names[config->mapping[i]]);
         }
     }
     fprintf(fstream, "\n");
     fclose(fstream);
     return true;
 }
References fclose(), fopen(), fprintf(), gus_patch_path, i, gus_config_t::mapping, MAX_INSTRUMENTS, NULL, and gus_config_t::patch_names.
Referenced by GUS_WriteConfig().
Variable Documentation
gus_patch_path
char* gus_patch_path = ""
Definition at line 40 of file gusconf.c.
Referenced by GUS_WriteConfig(), and WriteTimidityConfig().
gus_ram_kb
unsigned int gus_ram_kb = 1024
Definition at line 41 of file gusconf.c.
Referenced by MappingIndex().