Fennix Kernel: Kernel/SystemCalls/Syscalls.cpp File Reference
Syscalls.cpp File Reference
#include <syscalls.hpp>
#include <debug.h>
#include "../kernel.h"
Functions
NewLock (SyscallsLock)
uintptr_t SystemCallsHandler (SyscallsFrame *Frame)
Function Documentation
NewLock()
NewLock (SyscallsLock)
SystemCallsHandler()
uintptr_t SystemCallsHandler (SyscallsFrame * Frame)
Definition at line 26 of file Syscalls.cpp.
 {
     CPU::Interrupts(CPU::Enable);
     SmartLock(SyscallsLock); /* TODO: This should be replaced or moved somewhere else. */
     Tasking::TaskInfo *Ptinfo = &TaskManager->GetCurrentProcess()->Info;
     Tasking::TaskInfo *Ttinfo = &TaskManager->GetCurrentThread()->Info;
     uint64_t TempTimeCalc = TimeManager->GetCounter();
     switch (Ttinfo->Compatibility)
     {
     case Tasking::TaskCompatibility::Native:
     {
         uintptr_t ret = HandleNativeSyscalls(Frame);
         Ptinfo->KernelTime += TimeManager->GetCounter() - TempTimeCalc;
         Ttinfo->KernelTime += TimeManager->GetCounter() - TempTimeCalc;
         return ret;
     }
     case Tasking::TaskCompatibility::Linux:
     {
         uintptr_t ret = HandleLinuxSyscalls(Frame);
         Ptinfo->KernelTime += TimeManager->GetCounter() - TempTimeCalc;
         Ttinfo->KernelTime += TimeManager->GetCounter() - TempTimeCalc;
         return ret;
     }
     case Tasking::TaskCompatibility::Windows:
     {
         error("Windows compatibility not implemented yet.");
         break;
     }
     default:
     {
         error("Unknown compatibility mode! Killing thread...");
         TaskManager->KillThread(TaskManager->GetCurrentThread(), -0xCA11);
         break;
     }
     }
     assert(false); /* Should never reach here. */
     return 0;
 }
References assert, Tasking::TaskInfo::Compatibility, CPU::Enable, error, Time::time::GetCounter(), Tasking::Task::GetCurrentProcess(), Tasking::Task::GetCurrentThread(), HandleLinuxSyscalls(), HandleNativeSyscalls(), Tasking::TCB::Info, Tasking::PCB::Info, CPU::Interrupts(), Tasking::TaskInfo::KernelTime, Tasking::Task::KillThread(), Tasking::Linux, Tasking::Native, TaskManager, TimeManager, and Tasking::Windows.