Fennix Userspace: Userspace/musl/src/fenv/powerpc64/fenv.c File Reference
fenv.c File Reference
#include <fenv.h>
#include <features.h>
Macros
#define _GNU_SOURCE
Functions
static double get_fpscr_f (void)
static long get_fpscr (void)
static void set_fpscr_f (double fpscr)
static void set_fpscr (long fpscr)
int feclearexcept (int mask)
int feraiseexcept (int mask)
int fetestexcept (int mask)
int fegetround (void)
hidden int __fesetround (int r)
int fegetenv (fenv_t *envp)
int fesetenv (const fenv_t *envp)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file fenv.c.
Function Documentation
__fesetround()
hidden int __fesetround (int r)
Definition at line 53 of file fenv.c.
 {
     set_fpscr(get_fpscr() & ~3L | r);
     return 0;
 }
References get_fpscr(), and set_fpscr().
feclearexcept()
int feclearexcept (int mask)
Definition at line 27 of file fenv.c.
 {
     mask &= FE_ALL_EXCEPT;
     if (mask & FE_INVALID) mask |= FE_ALL_INVALID;
     set_fpscr(get_fpscr() & ~mask);
     return 0;
 }
References FE_ALL_EXCEPT, FE_INVALID, get_fpscr(), and set_fpscr().
fegetenv()
int fegetenv (fenv_t * envp)
Definition at line 59 of file fenv.c.
 {
     *envp = get_fpscr_f();
     return 0;
 }
References get_fpscr_f().
fegetround()
int fegetround (void)
Definition at line 48 of file fenv.c.
 {
     return get_fpscr() & 3;
 }
References get_fpscr().
feraiseexcept()
int feraiseexcept (int mask)
Definition at line 35 of file fenv.c.
 {
     mask &= FE_ALL_EXCEPT;
     if (mask & FE_INVALID) mask |= FE_INVALID_SOFTWARE;
     set_fpscr(get_fpscr() | mask);
     return 0;
 }
References FE_ALL_EXCEPT, FE_INVALID, get_fpscr(), and set_fpscr().
fesetenv()
int fesetenv (const fenv_t * envp)
Definition at line 65 of file fenv.c.
 {
     set_fpscr_f(envp != FE_DFL_ENV ? *envp : 0);
     return 0;
 }
References FE_DFL_ENV, and set_fpscr_f().
fetestexcept()
int fetestexcept (int mask)
Definition at line 43 of file fenv.c.
 {
     return get_fpscr() & mask & FE_ALL_EXCEPT;
 }
References FE_ALL_EXCEPT, and get_fpscr().
get_fpscr()
static long get_fpscr (void) inline static
Definition at line 12 of file fenv.c.
 {
     return (union {double f; long i;}) {get_fpscr_f()}.i;
 }
References f, get_fpscr_f(), and i.
Referenced by __fesetround(), feclearexcept(), fegetround(), feraiseexcept(), and fetestexcept().
get_fpscr_f()
static double get_fpscr_f (void) inline static
Definition at line 5 of file fenv.c.
 {
     double d;
     __asm__ __volatile__("mffs %0" : "=d"(d));
     return d;
 }
References __asm__().
Referenced by fegetenv(), and get_fpscr().
set_fpscr()
static void set_fpscr (long fpscr) static
Definition at line 22 of file fenv.c.
 {
     set_fpscr_f((union {long i; double f;}) {fpscr}.f);
 }
References f, i, and set_fpscr_f().
Referenced by __fesetround(), feclearexcept(), and feraiseexcept().
set_fpscr_f()
static void set_fpscr_f (double fpscr) inline static
Definition at line 17 of file fenv.c.
 {
     __asm__ __volatile__("mtfsf 255, %0" : : "d"(fpscr));
 }
References __asm__().
Referenced by fesetenv(), and set_fpscr().