Fennix: Userspace/apps/base/busybox/networking/ifconfig.c File Reference
ifconfig.c File Reference
#include "libbb.h"
#include "inet_common.h"
#include <net/if.h>
#include <net/if_arp.h>
#include <netinet/in.h>
Data Structures
struct arg1opt
struct options
Macros
#define QUESTIONABLE_ALIAS_CASE
#define SIOCSIFTXQLEN 0x8943
#define SIOCGIFTXQLEN 0x8942
#define ifr_qlen ifr_ifru.ifru_mtu
#define IFF_DYNAMIC 0x8000 /* dialup device with changing addresses */
#define N_CLR 0x01
#define M_CLR 0x02
#define N_SET 0x04
#define M_SET 0x08
#define N_ARG 0x10
#define M_ARG 0x20
#define M_MASK (M_CLR | M_SET | M_ARG)
#define N_MASK (N_CLR | N_SET | N_ARG)
#define SET_MASK (N_SET | M_SET)
#define CLR_MASK (N_CLR | M_CLR)
#define SET_CLR_MASK (SET_MASK | CLR_MASK)
#define ARG_MASK (M_ARG | N_ARG)
#define A_CAST_TYPE 0x03
#define A_MAP_TYPE 0x0C
#define A_ARG_REQ 0x10 /* Set if an arg is required. */
#define A_NETMASK 0x20 /* Set if netmask (check for multiple sets). */
#define A_SET_AFTER 0x40 /* Set a flag at the end. */
#define A_COLON_CHK 0x80 /* Is this needed? See below. */
#define A_HOSTNAME 0
#define A_BROADCAST 0
#define A_CAST_CHAR_PTR 0x01
#define A_CAST_RESOLVE 0x01
#define A_CAST_HOST_COPY 0x02
#define A_CAST_HOST_COPY_IN_ETHER A_CAST_HOST_COPY
#define A_CAST_HOST_COPY_RESOLVE (A_CAST_HOST_COPY | A_CAST_RESOLVE)
#define A_MAP_ULONG 0x04 /* memstart */
#define A_MAP_USHORT 0x08 /* io_addr */
#define A_MAP_UCHAR 0x0C /* irq */
#define ARG_METRIC (A_ARG_REQ /*| A_CAST_INT*/)
#define ARG_MTU (A_ARG_REQ /*| A_CAST_INT*/)
#define ARG_TXQUEUELEN (A_ARG_REQ /*| A_CAST_INT*/)
#define ARG_MEM_START (A_ARG_REQ | A_MAP_ULONG)
#define ARG_IO_ADDR (A_ARG_REQ | A_MAP_ULONG)
#define ARG_IRQ (A_ARG_REQ | A_MAP_UCHAR)
#define ARG_DSTADDR (A_ARG_REQ | A_CAST_HOST_COPY_RESOLVE)
#define ARG_NETMASK (A_ARG_REQ | A_CAST_HOST_COPY_RESOLVE | A_NETMASK)
#define ARG_BROADCAST (A_ARG_REQ | A_CAST_HOST_COPY_RESOLVE | A_SET_AFTER | A_BROADCAST)
#define ARG_HW (A_ARG_REQ | A_CAST_HOST_COPY_IN_ETHER)
#define ARG_POINTOPOINT (A_ARG_REQ | A_CAST_HOST_COPY_RESOLVE | A_SET_AFTER)
#define ARG_KEEPALIVE (A_ARG_REQ | A_CAST_CHAR_PTR)
#define ARG_OUTFILL (A_ARG_REQ | A_CAST_CHAR_PTR)
#define ARG_HOSTNAME (A_CAST_HOST_COPY_RESOLVE | A_SET_AFTER | A_COLON_CHK | A_HOSTNAME)
#define ARG_ADD_DEL (A_CAST_HOST_COPY_RESOLVE | A_SET_AFTER)
#define ifreq_offsetof(x) offsetof(struct ifreq, x)
Functions
int ifconfig_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const struct arg1opt Arg1Opt[] ALIGN_PTR
Data Structure Documentation
arg1opt
struct arg1opt
Definition at line 226 of file ifconfig.c.
Data Fields
unsigned short ifr_offset
const char * name
unsigned short selector
options
struct options
Definition at line 232 of file ifconfig.c.
Data Fields
const unsigned char arg_flags
const unsigned char flags
const char * name
const unsigned short selector
Macro Definition Documentation
A_ARG_REQ
#define A_ARG_REQ 0x10 /* Set if an arg is required. */
Definition at line 177 of file ifconfig.c.
A_BROADCAST
#define A_BROADCAST 0
Definition at line 186 of file ifconfig.c.
A_CAST_CHAR_PTR
#define A_CAST_CHAR_PTR 0x01
Definition at line 192 of file ifconfig.c.
A_CAST_HOST_COPY
#define A_CAST_HOST_COPY 0x02
Definition at line 194 of file ifconfig.c.
A_CAST_HOST_COPY_IN_ETHER
#define A_CAST_HOST_COPY_IN_ETHER A_CAST_HOST_COPY
Definition at line 195 of file ifconfig.c.
A_CAST_HOST_COPY_RESOLVE
#define A_CAST_HOST_COPY_RESOLVE (A_CAST_HOST_COPY | A_CAST_RESOLVE)
Definition at line 196 of file ifconfig.c.
A_CAST_RESOLVE
#define A_CAST_RESOLVE 0x01
Definition at line 193 of file ifconfig.c.
A_CAST_TYPE
#define A_CAST_TYPE 0x03
Definition at line 168 of file ifconfig.c.
A_COLON_CHK
#define A_COLON_CHK 0x80 /* Is this needed? See below. */
Definition at line 180 of file ifconfig.c.
A_HOSTNAME
#define A_HOSTNAME 0
Definition at line 185 of file ifconfig.c.
A_MAP_TYPE
#define A_MAP_TYPE 0x0C
Definition at line 176 of file ifconfig.c.
A_MAP_UCHAR
#define A_MAP_UCHAR 0x0C /* irq */
Definition at line 203 of file ifconfig.c.
A_MAP_ULONG
#define A_MAP_ULONG 0x04 /* memstart */
Definition at line 201 of file ifconfig.c.
A_MAP_USHORT
#define A_MAP_USHORT 0x08 /* io_addr */
Definition at line 202 of file ifconfig.c.
A_NETMASK
#define A_NETMASK 0x20 /* Set if netmask (check for multiple sets). */
Definition at line 178 of file ifconfig.c.
A_SET_AFTER
#define A_SET_AFTER 0x40 /* Set a flag at the end. */
Definition at line 179 of file ifconfig.c.
ARG_ADD_DEL
#define ARG_ADD_DEL (A_CAST_HOST_COPY_RESOLVE | A_SET_AFTER)
Definition at line 223 of file ifconfig.c.
ARG_BROADCAST
#define ARG_BROADCAST (A_ARG_REQ | A_CAST_HOST_COPY_RESOLVE | A_SET_AFTER | A_BROADCAST)
Definition at line 217 of file ifconfig.c.
ARG_DSTADDR
#define ARG_DSTADDR (A_ARG_REQ | A_CAST_HOST_COPY_RESOLVE)
Definition at line 215 of file ifconfig.c.
ARG_HOSTNAME
#define ARG_HOSTNAME (A_CAST_HOST_COPY_RESOLVE | A_SET_AFTER | A_COLON_CHK | A_HOSTNAME)
Definition at line 222 of file ifconfig.c.
ARG_HW
#define ARG_HW (A_ARG_REQ | A_CAST_HOST_COPY_IN_ETHER)
Definition at line 218 of file ifconfig.c.
ARG_IO_ADDR
#define ARG_IO_ADDR (A_ARG_REQ | A_MAP_ULONG)
Definition at line 213 of file ifconfig.c.
ARG_IRQ
#define ARG_IRQ (A_ARG_REQ | A_MAP_UCHAR)
Definition at line 214 of file ifconfig.c.
ARG_KEEPALIVE
#define ARG_KEEPALIVE (A_ARG_REQ | A_CAST_CHAR_PTR)
Definition at line 220 of file ifconfig.c.
ARG_MASK
#define ARG_MASK (M_ARG | N_ARG)
Definition at line 155 of file ifconfig.c.
ARG_MEM_START
#define ARG_MEM_START (A_ARG_REQ | A_MAP_ULONG)
Definition at line 212 of file ifconfig.c.
ARG_METRIC
#define ARG_METRIC (A_ARG_REQ /*| A_CAST_INT*/)
Definition at line 209 of file ifconfig.c.
ARG_MTU
#define ARG_MTU (A_ARG_REQ /*| A_CAST_INT*/)
Definition at line 210 of file ifconfig.c.
ARG_NETMASK
#define ARG_NETMASK (A_ARG_REQ | A_CAST_HOST_COPY_RESOLVE | A_NETMASK)
Definition at line 216 of file ifconfig.c.
ARG_OUTFILL
#define ARG_OUTFILL (A_ARG_REQ | A_CAST_CHAR_PTR)
Definition at line 221 of file ifconfig.c.
ARG_POINTOPOINT
#define ARG_POINTOPOINT (A_ARG_REQ | A_CAST_HOST_COPY_RESOLVE | A_SET_AFTER)
Definition at line 219 of file ifconfig.c.
ARG_TXQUEUELEN
#define ARG_TXQUEUELEN (A_ARG_REQ /*| A_CAST_INT*/)
Definition at line 211 of file ifconfig.c.
CLR_MASK
#define CLR_MASK (N_CLR | M_CLR)
Definition at line 153 of file ifconfig.c.
IFF_DYNAMIC
#define IFF_DYNAMIC 0x8000 /* dialup device with changing addresses */
Definition at line 127 of file ifconfig.c.
ifr_qlen
#define ifr_qlen ifr_ifru.ifru_mtu
Definition at line 123 of file ifconfig.c.
ifreq_offsetof
#define ifreq_offsetof (x) offsetof(struct ifreq, x)
Definition at line 244 of file ifconfig.c.
M_ARG
#define M_ARG 0x20
Definition at line 148 of file ifconfig.c.
M_CLR
#define M_CLR 0x02
Definition at line 144 of file ifconfig.c.
M_MASK
#define M_MASK (M_CLR | M_SET | M_ARG)
Definition at line 150 of file ifconfig.c.
M_SET
#define M_SET 0x08
Definition at line 146 of file ifconfig.c.
N_ARG
#define N_ARG 0x10
Definition at line 147 of file ifconfig.c.
N_CLR
#define N_CLR 0x01
Definition at line 143 of file ifconfig.c.
N_MASK
#define N_MASK (N_CLR | N_SET | N_ARG)
Definition at line 151 of file ifconfig.c.
N_SET
#define N_SET 0x04
Definition at line 145 of file ifconfig.c.
QUESTIONABLE_ALIAS_CASE
#define QUESTIONABLE_ALIAS_CASE
Definition at line 112 of file ifconfig.c.
SET_CLR_MASK
#define SET_CLR_MASK (SET_MASK | CLR_MASK)
Definition at line 154 of file ifconfig.c.
SET_MASK
#define SET_MASK (N_SET | M_SET)
Definition at line 152 of file ifconfig.c.
SIOCGIFTXQLEN
#define SIOCGIFTXQLEN 0x8942
Definition at line 118 of file ifconfig.c.
SIOCSIFTXQLEN
#define SIOCSIFTXQLEN 0x8943
Definition at line 117 of file ifconfig.c.
Function Documentation
ifconfig_main()
int ifconfig_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 318 of file ifconfig.c.
 {
     struct ifreq ifr;
     struct sockaddr_in sai;
 #if ENABLE_FEATURE_IFCONFIG_HW
     struct sockaddr sa;
 #endif
     const struct arg1opt *a1op;
     const struct options *op;
     int sockfd;         /* socket fd we use to manipulate stuff with */
     int selector;
 #if ENABLE_FEATURE_IFCONFIG_BROADCAST_PLUS
     unsigned int mask;
     unsigned int did_flags;
     unsigned int sai_hostname, sai_netmask;
 #else
     unsigned char mask;
     unsigned char did_flags;
 #endif
     char *p;
     /*char host[128];*/
     const char *host = NULL; /* make gcc happy */
     IF_FEATURE_IFCONFIG_STATUS(char *show_all_param;)
     did_flags = 0;
 #if ENABLE_FEATURE_IFCONFIG_BROADCAST_PLUS
     sai_hostname = 0;
     sai_netmask = 0;
 #endif
     /* skip argv[0] */
     ++argv;
 #if ENABLE_FEATURE_IFCONFIG_STATUS
     show_all_param = NULL;
     if (argv[0] && argv[0][0] == '-' && argv[0][1] == 'a' && !argv[0][2]) {
         ++argv;
         show_all_param = IFNAME_SHOW_DOWNED_TOO;
     }
 #endif
     if (!argv[0] || !argv[1]) { /* one or no args */
 #if ENABLE_FEATURE_IFCONFIG_STATUS
         return display_interfaces(argv[0] ? argv[0] : show_all_param);
 #else
         bb_simple_error_msg_and_die("no support for status display");
 #endif
     }
     /* Create a channel to the NET kernel. */
     sockfd = xsocket(AF_INET, SOCK_DGRAM, 0);
     /* get interface name */
     strncpy_IFNAMSIZ(ifr.ifr_name, *argv);
     /* Process the remaining arguments. */
     while (*++argv != NULL) {
         p = *argv;
         mask = N_MASK;
         if (*p == '-') {    /* If the arg starts with '-'... */
             ++p;        /*    advance past it and */
             mask = M_MASK;  /*    set the appropriate mask. */
         }
         for (op = OptArray; op->name; op++) {   /* Find table entry. */
             if (strcmp(p, op->name) == 0) { /* If name matches... */
                 mask &= op->flags;
                 if (mask)   /* set the mask and go. */
                     goto FOUND_ARG;
                 /* If we get here, there was a valid arg with an */
                 /* invalid '-' prefix. */
                 bb_error_msg_and_die("bad: '%s'", p-1);
             }
         }
         /* We fell through, so treat as possible hostname. */
         a1op = Arg1Opt + ARRAY_SIZE(Arg1Opt) - 1;
         mask = op->arg_flags;
         goto HOSTNAME;
  FOUND_ARG:
         if (mask & ARG_MASK) {
             mask = op->arg_flags;
             if (mask & A_NETMASK & did_flags)
                 bb_show_usage();
             a1op = Arg1Opt + (op - OptArray);
             if (*++argv == NULL) {
                 if (mask & A_ARG_REQ)
                     bb_show_usage();
                 --argv;
                 mask &= A_SET_AFTER;    /* just for broadcast */
             } else {    /* got an arg so process it */
  HOSTNAME:
                 did_flags |= (mask & (A_NETMASK|A_HOSTNAME));
                 if (mask & A_CAST_HOST_COPY) {
 #if ENABLE_FEATURE_IFCONFIG_HW
                     if (mask & A_CAST_RESOLVE) {
 #endif
                         host = *argv;
                         if (strcmp(host, "inet") == 0)
                             continue; /* compat stuff */
                         sai.sin_family = AF_INET;
                         sai.sin_port = 0;
                         if (strcmp(host, "default") == 0) {
                             /* Default is special, meaning 0.0.0.0. */
                             sai.sin_addr.s_addr = INADDR_ANY;
                         }
 #if ENABLE_FEATURE_IFCONFIG_BROADCAST_PLUS
                         else if ((host[0] == '+' && !host[1])
                          && (mask & A_BROADCAST)
                          && (did_flags & (A_NETMASK|A_HOSTNAME)) == (A_NETMASK|A_HOSTNAME)
                         ) {
                             /* + is special, meaning broadcast is derived. */
                             sai.sin_addr.s_addr = (~sai_netmask) | (sai_hostname & sai_netmask);
                         }
 #endif
                         else {
                             len_and_sockaddr *lsa;
 #if ENABLE_FEATURE_IPV6
                             char *prefix;
                             int prefix_len = 0;
                             prefix = strchr(host, '/');
                             if (prefix) {
                                 prefix_len = xatou_range(prefix + 1, 0, 128);
                                 *prefix = '\0';
                             }
  resolve:
 #endif
                             lsa = xhost2sockaddr(host, 0);
 #if ENABLE_FEATURE_IPV6
                             if (lsa->u.sa.sa_family != AF_INET6 && prefix) {
 /* TODO: we do not support "ifconfig eth0 up 1.2.3.4/17".
  * For now, just make it fail instead of silently ignoring "/17" part:
  */
                                 *prefix = '/';
                                 goto resolve;
                             }
                             if (lsa->u.sa.sa_family == AF_INET6) {
                                 int sockfd6;
                                 struct in6_ifreq ifr6;
                                 sockfd6 = xsocket(AF_INET6, SOCK_DGRAM, 0);
                                 xioctl(sockfd6, SIOCGIFINDEX, &ifr);
                                 ifr6.ifr6_ifindex = ifr.ifr_ifindex;
                                 ifr6.ifr6_prefixlen = prefix_len;
                                 memcpy(&ifr6.ifr6_addr,
                                         &lsa->u.sin6.sin6_addr,
                                         sizeof(struct in6_addr));
                                 ioctl_or_perror_and_die(sockfd6, a1op->selector, &ifr6, "SIOC%s", a1op->name);
                                 if (ENABLE_FEATURE_CLEAN_UP)
                                     free(lsa);
                                 continue;
                             }
 #endif
                             sai.sin_addr = lsa->u.sin.sin_addr;
                             if (ENABLE_FEATURE_CLEAN_UP)
                                 free(lsa);
                         }
 #if ENABLE_FEATURE_IFCONFIG_BROADCAST_PLUS
                         if (mask & A_HOSTNAME)
                             sai_hostname = sai.sin_addr.s_addr;
                         if (mask & A_NETMASK)
                             sai_netmask = sai.sin_addr.s_addr;
 #endif
                         p = (char *) &sai;
 #if ENABLE_FEATURE_IFCONFIG_HW
                     } else {    /* A_CAST_HOST_COPY_IN_ETHER */
                         /* This is the "hw" arg case. */
                         smalluint hw_class = index_in_substrings("ether\0"
                                 IF_FEATURE_HWIB("infiniband\0"), *argv) + 1;
                         if (!hw_class || !*++argv)
                             bb_show_usage();
                         host = *argv;
                         if (hw_class == 1 ? in_ether(host, &sa) : in_ib(host, &sa))
                             bb_error_msg_and_die("invalid hw-addr %s", host);
                         p = (char *) &sa;
                     }
 #endif
                     memcpy( ((char *)&ifr) + a1op->ifr_offset,
                         p, sizeof(struct sockaddr));
                 } else {
                     /* FIXME: error check?? */
                     unsigned long i = strtoul(*argv, NULL, 0);
                     p = ((char *)&ifr) + a1op->ifr_offset;
 #if ENABLE_FEATURE_IFCONFIG_MEMSTART_IOADDR_IRQ
                     if (mask & A_MAP_TYPE) {
                         xioctl(sockfd, SIOCGIFMAP, &ifr);
                         if ((mask & A_MAP_UCHAR) == A_MAP_UCHAR)
                             *(unsigned char *) p = i;
                         else if (mask & A_MAP_USHORT)
                             *(unsigned short *) p = i;
                         else
                             *(unsigned long *) p = i;
                     } else
 #endif
                     if (mask & A_CAST_CHAR_PTR)
                         *(caddr_t *) p = (caddr_t) i;
                     else    /* A_CAST_INT */
                         *(int *) p = i;
                 }
                 ioctl_or_perror_and_die(sockfd, a1op->selector, &ifr, "SIOC%s", a1op->name);
 #ifdef QUESTIONABLE_ALIAS_CASE
                 if (mask & A_COLON_CHK) {
                     /*
                      * Don't do the set_flag() if the address is an alias with
                      * a '-' at the end, since it's deleted already! - Roman
                      *
                      * Should really use regex.h here, not sure though how well
                      * it'll go with the cross-platform support etc.
                      */
                     char *ptr;
                     short int found_colon = 0;
                     for (ptr = ifr.ifr_name; *ptr; ptr++)
                         if (*ptr == ':')
                             found_colon++;
                     if (found_colon && ptr[-1] == '-')
                         continue;
                 }
 #endif
             }
             if (!(mask & A_SET_AFTER))
                 continue;
             mask = N_SET;
         } /* if (mask & ARG_MASK) */
         xioctl(sockfd, SIOCGIFFLAGS, &ifr);
         selector = op->selector;
         if (mask & SET_MASK)
             ifr.ifr_flags |= selector;
         else
             ifr.ifr_flags &= ~selector;
         xioctl(sockfd, SIOCSIFFLAGS, &ifr);
     } /* while () */
     if (ENABLE_FEATURE_CLEAN_UP)
         close(sockfd);
     return 0;
 }
References A_ARG_REQ, A_BROADCAST, A_CAST_CHAR_PTR, A_CAST_HOST_COPY, A_CAST_RESOLVE, A_COLON_CHK, A_HOSTNAME, A_MAP_TYPE, A_MAP_UCHAR, A_MAP_USHORT, A_NETMASK, A_SET_AFTER, AF_INET, AF_INET6, ARG_MASK, argv, ARRAY_SIZE, bb_error_msg_and_die(), bb_show_usage(), bb_simple_error_msg_and_die(), close(), display_interfaces(), free, HOSTNAME, i, IFNAME_SHOW_DOWNED_TOO, ifr, arg1opt::ifr_offset, in_ether(), in_ib, INADDR_ANY, index_in_substrings(), ioctl_or_perror_and_die(), lsa, M_MASK, memcpy, N_MASK, N_SET, op::name, arg1opt::name, NULL, p, prefix(), in_addr::s_addr, arg1opt::selector, options::selector, SET_MASK, sockaddr_in::sin_addr, sockaddr_in::sin_family, sockaddr_in::sin_port, SIOCGIFFLAGS, SIOCGIFINDEX, SIOCGIFMAP, SIOCSIFFLAGS, SOCK_DGRAM, sockfd, strchr(), strcmp, strncpy_IFNAMSIZ(), strtoul(), xhost2sockaddr(), xioctl, and xsocket().
Variable Documentation
ALIGN_PTR
const struct options OptArray [] ALIGN_PTR static
Initial value:
= {
    { "SIFMETRIC",  SIOCSIFMETRIC,  ifreq_offsetof(ifr_metric) },
    { "SIFMTU",     SIOCSIFMTU,     ifreq_offsetof(ifr_mtu) },
    { "SIFTXQLEN",  SIOCSIFTXQLEN,  ifreq_offsetof(ifr_qlen) },
    { "SIFDSTADDR", SIOCSIFDSTADDR, ifreq_offsetof(ifr_dstaddr) },
    { "SIFNETMASK", SIOCSIFNETMASK, ifreq_offsetof(ifr_netmask) },
    { "SIFBRDADDR", SIOCSIFBRDADDR, ifreq_offsetof(ifr_broadaddr) },
    { "SIFDSTADDR", SIOCSIFDSTADDR, ifreq_offsetof(ifr_dstaddr) },
    { "SIFADDR",    SIOCSIFADDR,    ifreq_offsetof(ifr_addr) },
}
Definition at line 250 of file ifconfig.c.