Fennix Userspace: Userspace/mlibc/options/ansi/generic/complex/cproj.c File Reference
cproj.c File Reference
#include <complex.h>
#include <math.h>
#include "fdlibm.h"
Functions
double complex cproj (double complex z)
Function Documentation
cproj()
double complex cproj (double complex z)
Definition at line 91 of file cproj.c.
 {
     double_complex w = { .z = z };
     if (isinf(creal(z)) || isinf(cimag(z))) {
 #ifdef __INFINITY
         REAL_PART(w) = __INFINITY;
 #else
         REAL_PART(w) = INFINITY;
 #endif
         IMAG_PART(w) = copysign(0.0, cimag(z));
     }
     return (w.z);
 }
References cimag(), copysign(), creal(), IMAG_PART, INFINITY, isinf, REAL_PART, and double_complex::z.