Fennix Kernel: NetworkNTP::NTP Class Reference
NetworkNTP::NTP Class Reference
#include <ntp.hpp>
Public Member Functions
NTP (NetworkUDP::Socket *Socket)
~NTP ()
int ReadTime ()
Get the time from the NTP server.
Private Member Functions
virtual void OnUDPPacketReceived (NetworkUDP::Socket *Socket, uint8_t *Data, uint64_t Length)
Private Attributes
NetworkUDP::Socket * UDPSocket
bool TimeReceived = false
NTPHeader NTPPacket
Additional Inherited Members
Protected Member Functions inherited from NetworkUDP::UDPEvents
UDPEvents ()
~UDPEvents ()
Detailed Description
Definition at line 127 of file ntp.hpp.
Constructor & Destructor Documentation
NTP()
NetworkNTP::NTP::NTP (NetworkUDP::Socket * Socket)
Definition at line 15 of file NetworkTimeProtocol.cpp.
                                      : NetworkUDP::UDPEvents()
     {
         debug("NTP interface %#lx created.", this);
         this->UDPSocket = Socket;
     }
References debug, and UDPSocket.
~NTP()
NetworkNTP::NTP::~NTP ()
Definition at line 21 of file NetworkTimeProtocol.cpp.
     {
         debug("NTP interface %#lx destroyed.", this);
     }
References debug.
Member Function Documentation
OnUDPPacketReceived()
void NetworkNTP::NTP::OnUDPPacketReceived (NetworkUDP::Socket * Socket, uint8_t * Data, uint64_t Length) private virtual
Reimplemented from NetworkUDP::UDPEvents.
Definition at line 8 of file NetworkTimeProtocol.cpp.
     {
         this->NTPPacket = *(NTPHeader *)Data;
         this->TimeReceived = true;
         netdbg("Received UDP packet for NTP.");
     }
References Data, netdbg, NTPPacket, and TimeReceived.
ReadTime()
int NetworkNTP::NTP::ReadTime ()
Get the time from the NTP server.
Returns
Unix Timestamp
Definition at line 26 of file NetworkTimeProtocol.cpp.
     {
         netdbg("Requesting time");
         this->TimeReceived = false;
         NTPHeader ReqPacket;                      // This may require phyiscal memory allocation but Ethernet already has this job.
         memset(&ReqPacket, 0, sizeof(NTPHeader)); // Zero out the packet
         *((char *)&ReqPacket) = 0x1b;             // byteswap nightmare, this is the code below but in little endian
         // ReqPacket.LeapIndicator = 0;
         // ReqPacket.VersionNumber = 3;
         // ReqPacket.Mode = 3;
         UDPSocket->SocketUDP->Send(UDPSocket, (uint8_t *)&ReqPacket, sizeof(NTPHeader));
         debug("Waiting for response...");
         int RequestTimeout = 20;
         while (!this->TimeReceived)
         {
             if (--RequestTimeout == 0)
             {
                 warn("Request timeout.");
                 return 0;
             }
             netdbg("Still waiting...");
             TaskManager->Sleep(1000);
         }
         int UnixTimestamp = b32(this->NTPPacket.TransmitTimestamp[0]) - 2208988800;
         debug("Unix time: %d", UnixTimestamp);
         return UnixTimestamp;
     }
References b32, debug, memset(), netdbg, NTPPacket, NetworkUDP::UDP::Send(), Tasking::Task::Sleep(), NetworkUDP::Socket::SocketUDP, TaskManager, TimeReceived, NetworkNTP::NTPHeader::TransmitTimestamp, UDPSocket, and warn.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Field Documentation
NTPPacket
NTPHeader NetworkNTP::NTP::NTPPacket private
Definition at line 132 of file ntp.hpp.
Referenced by OnUDPPacketReceived(), and ReadTime().
TimeReceived
bool NetworkNTP::NTP::TimeReceived = false private
Definition at line 131 of file ntp.hpp.
Referenced by OnUDPPacketReceived(), and ReadTime().
UDPSocket
NetworkUDP::Socket* NetworkNTP::NTP::UDPSocket private
Definition at line 130 of file ntp.hpp.
Referenced by NTP(), and ReadTime().
The documentation for this class was generated from the following files:
Kernel/include/net/ntp.hpp
Kernel/Network/NetworkTimeProtocol.cpp