Fennix Userspace: Userspace/apps/base/busybox/coreutils/nice.c File Reference
nice.c File Reference
#include "libbb.h"
Functions
int nice_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
nice_main()
int nice_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 28 of file nice.c.
 {
     int old_priority, adjustment;
     old_priority = getpriority(PRIO_PROCESS, 0);
     if (!*++argv) { /* No args, so (GNU) output current nice value. */
         printf("%d\n", old_priority);
         fflush_stdout_and_exit_SUCCESS();
     }
     adjustment = 10;  /* Set default adjustment. */
     if (argv[0][0] == '-') {
         char *nnn = argv[0] + 1;
         if (nnn[0] == 'n') { /* -n */
             nnn += 1;
             if (!nnn[0]) { /* "-n NNN" */
                 nnn = *++argv;
             }
             /* else: "-nNNN" (w/o space) */
         }
         /* else: "-NNN" (NNN may be negative) - same as "-n NNN" */
         if (!nnn || !argv[1]) {  /* Missing priority or PROG! */
             bb_show_usage();
         }
         adjustment = xatoi_range(nnn, INT_MIN/2, INT_MAX/2);
         argv++;
     }
     {  /* Set our priority. */
         int prio = old_priority + adjustment;
         if (setpriority(PRIO_PROCESS, 0, prio) < 0) {
             bb_perror_msg_and_die("setpriority(%d)", prio);
         }
     }
     BB_EXECVP_or_die(argv);
 }
References argv, BB_EXECVP_or_die(), bb_perror_msg_and_die(), bb_show_usage(), fflush_stdout_and_exit_SUCCESS(), getpriority(), INT_MAX, INT_MIN, printf(), PRIO_PROCESS, and setpriority().