Fennix: Kernel/Core/Driver/DriverAPI.cpp File Reference
DriverAPI.cpp File Reference
#include <driver.hpp>
#include <dumper.hpp>
#include <lock.hpp>
#include "../../kernel.h"
#include "../../Fex.hpp"
#include "api.hpp"
Macros
#define drvdbg(m, ...)
Functions
NewLock (DriverDisplayPrintLock)
void DriverDebugPrint (char *String, __UINT64_TYPE__ DriverUID)
void DriverDisplayPrint (char *String)
void * RequestPage (__UINT64_TYPE__ Size)
void FreePage (void *Page, __UINT64_TYPE__ Size)
void MapMemory (void *VirtualAddress, void *PhysicalAddress, __UINT64_TYPE__ Flags)
void UnmapMemory (void *VirtualAddress)
void * Drivermemcpy (void *Destination, void *Source, __UINT64_TYPE__ Size)
void * Drivermemset (void *Destination, int Value, __UINT64_TYPE__ Size)
void DriverNetSend (__UINT32_TYPE__ DriverID, __UINT8_TYPE__ *Data, __UINT16_TYPE__ Size)
void DriverNetReceive (__UINT32_TYPE__ DriverID, __UINT8_TYPE__ *Data, __UINT16_TYPE__ Size)
void DriverAHCIDiskRead (__UINT32_TYPE__ DriverID, __UINT64_TYPE__ Sector, __UINT8_TYPE__ *Data, __UINT32_TYPE__ SectorCount, __UINT8_TYPE__ Port)
void DriverAHCIDiskWrite (__UINT32_TYPE__ DriverID, __UINT64_TYPE__ Sector, __UINT8_TYPE__ *Data, __UINT32_TYPE__ SectorCount, __UINT8_TYPE__ Port)
char * DriverPCIGetDeviceName (__UINT32_TYPE__ VendorID, __UINT32_TYPE__ DeviceID)
__UINT32_TYPE__ DriverGetWidth ()
__UINT32_TYPE__ DriverGetHeight ()
void DriverSleep (__UINT64_TYPE__ Milliseconds)
int Driversprintf (char *Buffer, const char *Format,...)
Variables
KernelAPI KernelAPITemplate
Macro Definition Documentation
drvdbg
#define drvdbg (m, ...)
Definition at line 33 of file DriverAPI.cpp.
Function Documentation
DriverAHCIDiskRead()
void DriverAHCIDiskRead (__UINT32_TYPE__ DriverID, __UINT64_TYPE__ Sector, __UINT8_TYPE__ * Data, __UINT32_TYPE__ SectorCount, __UINT8_TYPE__ Port)
Definition at line 119 of file DriverAPI.cpp.
 {
     DumpData("DriverDiskRead", Data, SectorCount * 512);
     UNUSED(DriverID);
     UNUSED(Sector);
     UNUSED(Port);
 }
References Data, DumpData(), and UNUSED.
DriverAHCIDiskWrite()
void DriverAHCIDiskWrite (__UINT32_TYPE__ DriverID, __UINT64_TYPE__ Sector, __UINT8_TYPE__ * Data, __UINT32_TYPE__ SectorCount, __UINT8_TYPE__ Port)
Definition at line 131 of file DriverAPI.cpp.
 {
     DumpData("DriverDiskWrite",
              Data, SectorCount * 512);
     UNUSED(DriverID);
     UNUSED(Sector);
     UNUSED(Port);
 }
References Data, DumpData(), and UNUSED.
DriverDebugPrint()
void DriverDebugPrint (char * String, __UINT64_TYPE__ DriverUID)
Definition at line 38 of file DriverAPI.cpp.
 {
     trace("[%ld] %s", DriverUID, String);
 }
References trace.
DriverDisplayPrint()
void DriverDisplayPrint (char * String)
Definition at line 43 of file DriverAPI.cpp.
 {
     SmartLock(DriverDisplayPrintLock);
     for (__UINT64_TYPE__ i = 0; i < strlen(String); i++)
         Display->Print(String[i], 0, true);
 }
References Display, i, and strlen().
DriverGetHeight()
__UINT32_TYPE__ DriverGetHeight ()
Definition at line 159 of file DriverAPI.cpp.
 {
     /* TODO: We won't rely only on display buffers,
         what about graphics drivers and changing resolutions? */
     return Display->GetBuffer(0)->Height;
 }
References Display.
DriverGetWidth()
__UINT32_TYPE__ DriverGetWidth ()
Definition at line 152 of file DriverAPI.cpp.
 {
     /* TODO: We won't rely only on display buffers,
         what about graphics drivers and changing resolutions? */
     return Display->GetBuffer(0)->Width;
 }
References Display.
Drivermemcpy()
void* Drivermemcpy (void * Destination, void * Source, __UINT64_TYPE__ Size)
Definition at line 84 of file DriverAPI.cpp.
 {
     SmartLock(DriverDisplayPrintLock);
     drvdbg("Copying %ld bytes from %#lx-%#lx to %#lx-%#lx...", Size,
            (__UINT64_TYPE__)Source, (__UINT64_TYPE__)Source + Size,
            (__UINT64_TYPE__)Destination, (__UINT64_TYPE__)Destination + Size);
     return memcpy(Destination, Source, size_t(Size));
 }
References drvdbg, memcpy, and Size.
Drivermemset()
void* Drivermemset (void * Destination, int Value, __UINT64_TYPE__ Size)
Definition at line 93 of file DriverAPI.cpp.
 {
     SmartLock(DriverDisplayPrintLock);
     drvdbg("Setting value %#x at %#lx-%#lx (%ld bytes)...", Value,
            (__UINT64_TYPE__)Destination,
            (__UINT64_TYPE__)Destination + Size, Size);
     return memset(Destination, Value, size_t(Size));
 }
References drvdbg, memset, and Size.
DriverNetReceive()
void DriverNetReceive (__UINT32_TYPE__ DriverID, __UINT8_TYPE__ * Data, __UINT16_TYPE__ Size)
Definition at line 111 of file DriverAPI.cpp.
 {
     if (NIManager)
         NIManager->DrvReceive(DriverID, Data, Size);
 }
References Data, NetworkInterfaceManager::NetworkInterface::DrvReceive(), NIManager, and Size.
DriverNetSend()
void DriverNetSend (__UINT32_TYPE__ DriverID, __UINT8_TYPE__ * Data, __UINT16_TYPE__ Size)
Definition at line 102 of file DriverAPI.cpp.
 {
     // This is useless I guess...
     if (NIManager)
         NIManager->DrvSend(DriverID, Data, Size);
 }
References Data, NetworkInterfaceManager::NetworkInterface::DrvSend(), NIManager, and Size.
DriverPCIGetDeviceName()
char* DriverPCIGetDeviceName (__UINT32_TYPE__ VendorID, __UINT32_TYPE__ DeviceID)
Definition at line 144 of file DriverAPI.cpp.
 {
     UNUSED(VendorID);
     UNUSED(DeviceID);
     return (char *)"Unknown";
 }
References UNUSED.
DriverSleep()
void DriverSleep (__UINT64_TYPE__ Milliseconds)
Definition at line 166 of file DriverAPI.cpp.
 {
     SmartLock(DriverDisplayPrintLock);
     drvdbg("Sleeping for %ld milliseconds...", Milliseconds);
     if (TaskManager)
         TaskManager->Sleep(Milliseconds);
     else
         TimeManager->Sleep(size_t(Milliseconds),
                            Time::Units::Milliseconds);
 }
References drvdbg, Time::Milliseconds, Time::time::Sleep(), Tasking::Task::Sleep(), TaskManager, and TimeManager.
Driversprintf()
int Driversprintf (char * Buffer, const char * Format, ...)
Definition at line 177 of file DriverAPI.cpp.
 {
     va_list args;
     va_start(args, Format);
     int ret = vsprintf(Buffer, Format, args);
     va_end(args);
     return ret;
 }
References args, va_end, va_start, and vsprintf().
FreePage()
void FreePage (void * Page, __UINT64_TYPE__ Size)
Definition at line 59 of file DriverAPI.cpp.
 {
     drvdbg("Freeing %ld pages (%#lx-%#lx)",
            Size, (__UINT64_TYPE__)Page,
            (__UINT64_TYPE__)Page + FROM_PAGES(Size));
     KernelAllocator.FreePages(Page, size_t(Size + 1));
 }
References drvdbg, FROM_PAGES, KernelAllocator, and Size.
MapMemory()
void MapMemory (void * VirtualAddress, void * PhysicalAddress, __UINT64_TYPE__ Flags)
Definition at line 67 of file DriverAPI.cpp.
 {
     SmartLock(DriverDisplayPrintLock);
     drvdbg("Mapping %#lx to %#lx with flags %#lx...",
            (__UINT64_TYPE__)VirtualAddress,
            (__UINT64_TYPE__)PhysicalAddress, Flags);
     Memory::Virtual(KernelPageTable).Map(VirtualAddress, PhysicalAddress, Flags);
 }
References drvdbg, Flags, KernelPageTable, and PhysicalAddress.
NewLock()
NewLock (DriverDisplayPrintLock)
RequestPage()
void* RequestPage (__UINT64_TYPE__ Size)
Definition at line 50 of file DriverAPI.cpp.
 {
     void *ret = KernelAllocator.RequestPages(size_t(Size + 1));
     drvdbg("Allocated %ld pages (%#lx-%#lx)",
            Size, (__UINT64_TYPE__)ret,
            (__UINT64_TYPE__)ret + FROM_PAGES(Size));
     return ret;
 }
References drvdbg, FROM_PAGES, KernelAllocator, and Size.
UnmapMemory()
void UnmapMemory (void * VirtualAddress)
Definition at line 76 of file DriverAPI.cpp.
 {
     SmartLock(DriverDisplayPrintLock);
     drvdbg("Unmapping %#lx...",
            (__UINT64_TYPE__)VirtualAddress);
     Memory::Virtual(KernelPageTable).Unmap(VirtualAddress);
 }
References drvdbg, and KernelPageTable.
Variable Documentation
KernelAPITemplate
KernelAPI KernelAPITemplate
Definition at line 186 of file DriverAPI.cpp.
Referenced by Driver::Driver::CallDriverEntryPoint().