Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/f_wipe.h File Reference
f_wipe.h File Reference
Enumerations
enum { wipe_ColorXForm , wipe_Melt , wipe_NUMWIPES }
Functions
int wipe_StartScreen (int x, int y, int width, int height)
int wipe_EndScreen (int x, int y, int width, int height)
int wipe_ScreenWipe (int wipeno, int x, int y, int width, int height, int ticks)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
wipe_ColorXForm
wipe_Melt
wipe_NUMWIPES
Definition at line 27 of file f_wipe.h.
 {
     // simple gradual pixel change for 8-bit only
     wipe_ColorXForm,
     // weird screen melt
     wipe_Melt,
     wipe_NUMWIPES
 };
Function Documentation
wipe_EndScreen()
int wipe_EndScreen (int x, int y, int width, int height)
Definition at line 243 of file f_wipe.c.
 {
     wipe_scr_end = Z_Malloc(SCREENWIDTH * SCREENHEIGHT, PU_STATIC, NULL);
     I_ReadScreen(wipe_scr_end);
     V_DrawBlock(x, y, width, height, wipe_scr_start); // restore start scr.
     return 0;
 }
References anonymous_namespace{search.cpp}::height(), I_ReadScreen(), NULL, PU_STATIC, SCREENHEIGHT, SCREENWIDTH, V_DrawBlock(), wipe_scr_end, wipe_scr_start, x, y, and Z_Malloc().
Referenced by D_Display().
wipe_ScreenWipe()
int wipe_ScreenWipe (int wipeno, int x, int y, int width, int height, int ticks)
Definition at line 256 of file f_wipe.c.
 {
     int rc;
     static int (*wipes[])(int, int, int) =
     {
     wipe_initColorXForm, wipe_doColorXForm, wipe_exitColorXForm,
     wipe_initMelt, wipe_doMelt, wipe_exitMelt
     };
     // initial stuff
     if (!go)
     {
     go = 1;
     // wipe_scr = (byte *) Z_Malloc(width*height, PU_STATIC, 0); // DEBUG
     wipe_scr = I_VideoBuffer;
     (*wipes[wipeno*3])(width, height, ticks);
     }
     // do a piece of wipe-in
     V_MarkRect(0, 0, width, height);
     rc = (*wipes[wipeno*3+1])(width, height, ticks);
     //  V_DrawBlock(x, y, 0, width, height, wipe_scr); // DEBUG
     // final stuff
     if (rc)
     {
     go = 0;
     (*wipes[wipeno*3+2])(width, height, ticks);
     }
     return !go;
 }
References go, anonymous_namespace{search.cpp}::height(), I_VideoBuffer, int, V_MarkRect(), wipe_doColorXForm(), wipe_doMelt(), wipe_exitColorXForm(), wipe_exitMelt(), wipe_initColorXForm(), wipe_initMelt(), and wipe_scr.
Referenced by D_Display().
wipe_StartScreen()
int wipe_StartScreen (int x, int y, int width, int height)
Definition at line 231 of file f_wipe.c.
 {
     wipe_scr_start = Z_Malloc(SCREENWIDTH * SCREENHEIGHT, PU_STATIC, NULL);
     I_ReadScreen(wipe_scr_start);
     return 0;
 }
References I_ReadScreen(), NULL, PU_STATIC, SCREENHEIGHT, SCREENWIDTH, wipe_scr_start, and Z_Malloc().
Referenced by D_Display().