Fennix: Userspace/apps/base/busybox/libbb/wfopen_input.c File Reference
wfopen_input.c File Reference
#include "libbb.h"
Functions
FILE *FAST_FUNC fopen_or_warn_stdin (const char *filename)
FILE *FAST_FUNC xfopen_stdin (const char *filename)
int FAST_FUNC open_or_warn_stdin (const char *filename)
int FAST_FUNC xopen_stdin (const char *filename)
Function Documentation
fopen_or_warn_stdin()
FILE* FAST_FUNC fopen_or_warn_stdin (const char * filename)
Definition at line 16 of file wfopen_input.c.
 {
     FILE *fp = stdin;
     if (filename != bb_msg_standard_input
      && NOT_LONE_DASH(filename)
     ) {
         fp = fopen_or_warn(filename, "r");
     }
     return fp;
 }
References filename, fopen_or_warn(), NOT_LONE_DASH, and stdin.
Referenced by config_open(), cut_main(), do_info(), expand_main(), fold_main(), head_main(), open_next_file(), paste_main(), print_numbered_lines(), rev_main(), strings_main(), tac_main(), wc_main(), and xfopen_stdin().
open_or_warn_stdin()
int FAST_FUNC open_or_warn_stdin (const char * filename)
Definition at line 36 of file wfopen_input.c.
 {
     int fd = STDIN_FILENO;
     if (filename != bb_msg_standard_input
      && NOT_LONE_DASH(filename)
     ) {
         fd = open_or_warn(filename, O_RDONLY);
     }
     return fd;
 }
References fd, filename, NOT_LONE_DASH, O_RDONLY, open_or_warn(), and STDIN_FILENO.
Referenced by bb_cat(), cksum_main(), hash_file(), sum_file(), tail_main(), and xopen_stdin().
xfopen_stdin()
FILE* FAST_FUNC xfopen_stdin (const char * filename)
Definition at line 28 of file wfopen_input.c.
 {
     FILE *fp = fopen_or_warn_stdin(filename);
     if (fp)
         return fp;
     xfunc_die();  /* We already output an error message. */
 }
References filename, fopen_or_warn_stdin(), and xfunc_die().
Referenced by cmp_main(), comm_main(), fbsplash_main(), init(), load_regexes_from_file(), md5_sha1_sum_main(), next_input_file(), patch_main(), sed_main(), shuf_main(), and sort_main().
xopen_stdin()
int FAST_FUNC xopen_stdin (const char * filename)
Definition at line 49 of file wfopen_input.c.
 {
     int fd = open_or_warn_stdin(filename);
     if (fd >= 0)
         return fd;
     xfunc_die();  /* We already output an error message. */
 }
References fd, filename, open_or_warn_stdin(), and xfunc_die().
Referenced by awk_main(), download_one_url(), dpkg_deb_main(), patch_main(), and split_main().