Fennix: std::unordered_map< key_type, value_type > Class Template Reference
std::unordered_map< key_type, value_type > Class Template Reference
#include <unordered_map.hpp>
Public Types
typedef std::pair< key_type, value_type > key_value_pair
typedef std::list< key_value_pair > bucket
typedef std::vector< bucket >::iterator iterator
typedef std::vector< bucket >::const_iterator const_iterator
Public Member Functions
unordered_map ()
unordered_map (size_t num_buckets)
void insert (const key_value_pair &pair)
bool contains (const key_type &key) const
iterator find (const key_type &k)
const_iterator find (const key_type &k) const
iterator end () noexcept
size_t size () const
value_type & operator[] (const key_type &key)
Private Member Functions
size_t hash (const key_type &key) const
Private Attributes
std::vector< bucket > bkts
Static Private Attributes
static const size_t DEFAULT_NUM_BUCKETS = 10
Detailed Description
template<typename key_type, typename value_type>
class std::unordered_map< key_type, value_type >
Definition at line 12 of file unordered_map.hpp.
Member Typedef Documentation
bucket
template<typename key_type , typename value_type > typedef std::list<key_value_pair> std::unordered_map< key_type, value_type >::bucket
Definition at line 16 of file unordered_map.hpp.
const_iterator
template<typename key_type , typename value_type > typedef std::vector<bucket>::const_iterator std::unordered_map< key_type, value_type >::const_iterator
Definition at line 18 of file unordered_map.hpp.
iterator
template<typename key_type , typename value_type > typedef std::vector<bucket>::iterator std::unordered_map< key_type, value_type >::iterator
Definition at line 17 of file unordered_map.hpp.
key_value_pair
template<typename key_type , typename value_type > typedef std::pair<key_type, value_type> std::unordered_map< key_type, value_type >::key_value_pair
Definition at line 15 of file unordered_map.hpp.
Constructor & Destructor Documentation
unordered_map() [1/2]
template<typename key_type , typename value_type > std::unordered_map< key_type, value_type >::unordered_map () inline
Definition at line 31 of file unordered_map.hpp.
 : bkts(DEFAULT_NUM_BUCKETS) {}
unordered_map() [2/2]
template<typename key_type , typename value_type > std::unordered_map< key_type, value_type >::unordered_map (size_t num_buckets) inline
Definition at line 32 of file unordered_map.hpp.
 : bkts(num_buckets) {}
Member Function Documentation
contains()
template<typename key_type , typename value_type > bool std::unordered_map< key_type, value_type >::contains (const key_type & key) const inline
Definition at line 49 of file unordered_map.hpp.
         {
             size_t bucket_index = hash(key);
             const bucket &bkt = this->bkts[bucket_index];
             for (auto it = bkt.begin(); it != bkt.end(); ++it)
             {
                 if (it->first == key)
                 {
                     return true;
                 }
             }
             return false;
         }
References std::list< T >::begin(), std::list< T >::end(), std::unordered_map< key_type, value_type >::hash(), and CrashHandler::key.
end()
template<typename key_type , typename value_type > iterator std::unordered_map< key_type, value_type >::end () inline noexcept
Definition at line 87 of file unordered_map.hpp.
 { return this->bkts.end(); }
References std::vector< T >::end().
find() [1/2]
template<typename key_type , typename value_type > iterator std::unordered_map< key_type, value_type >::find (const key_type & k) inline
Definition at line 63 of file unordered_map.hpp.
         {
             size_t bucket_index = hash(k);
             bucket &bkt = this->bkts[bucket_index];
             for (auto it = bkt.begin(); it != bkt.end(); ++it)
             {
                 if (it->first == k)
                     return it;
             }
             return bkt.end();
         }
References std::list< T >::begin(), std::list< T >::end(), std::unordered_map< key_type, value_type >::hash(), and k.
find() [2/2]
template<typename key_type , typename value_type > const_iterator std::unordered_map< key_type, value_type >::find (const key_type & k) const inline
Definition at line 75 of file unordered_map.hpp.
         {
             size_t bucket_index = hash(k);
             const bucket &bkt = this->bkts[bucket_index];
             for (auto it = bkt.begin(); it != bkt.end(); ++it)
             {
                 if (it->first == k)
                     return it;
             }
             return bkt.end();
         }
References std::list< T >::begin(), std::list< T >::end(), std::unordered_map< key_type, value_type >::hash(), and k.
hash()
template<typename key_type , typename value_type > size_t std::unordered_map< key_type, value_type >::hash (const key_type & key) const inline private
Definition at line 24 of file unordered_map.hpp.
         {
             std::hash<key_type> hash_function;
             return hash_function(key) % this->bkts.size();
         }
References CrashHandler::key, and std::vector< T >::size().
Referenced by std::unordered_map< key_type, value_type >::contains(), std::unordered_map< key_type, value_type >::find(), std::unordered_map< key_type, value_type >::insert(), and std::unordered_map< key_type, value_type >::operator[]().
insert()
template<typename key_type , typename value_type > void std::unordered_map< key_type, value_type >::insert (const key_value_pair & pair) inline
Definition at line 34 of file unordered_map.hpp.
         {
             size_t bucket_index = hash(pair.first);
             bucket &bkt = this->bkts[bucket_index];
             for (auto it = bkt.begin(); it != bkt.end(); ++it)
             {
                 if (it->first == pair.first)
                 {
                     it->second = pair.second;
                     return;
                 }
             }
             bkt.push_back(pair);
         }
References std::list< T >::begin(), std::list< T >::end(), std::pair< T1, T2 >::first, std::unordered_map< key_type, value_type >::hash(), std::list< T >::push_back(), and std::pair< T1, T2 >::second.
operator[]()
template<typename key_type , typename value_type > value_type& std::unordered_map< key_type, value_type >::operator[] (const key_type & key) inline
Definition at line 98 of file unordered_map.hpp.
         {
             size_t bucket_index = hash(key);
             bucket &bkt = this->bkts[bucket_index];
             for (auto it = bkt.begin(); it != bkt.end(); ++it)
             {
                 if (it->first == key)
                     return it->second;
             }
             bkt.emplace_back(key, value_type());
             return bkt.back().second;
         }
References std::list< T >::begin(), std::list< T >::end(), std::unordered_map< key_type, value_type >::hash(), and CrashHandler::key.
size()
template<typename key_type , typename value_type > size_t std::unordered_map< key_type, value_type >::size () const inline
Definition at line 89 of file unordered_map.hpp.
         {
             size_t count = 0;
             foreach (const auto &bkt in this->bkts)
                 count += bkt.size();
             return count;
         }
References mlibc::count.
Field Documentation
bkts
template<typename key_type , typename value_type > std::vector<bucket> std::unordered_map< key_type, value_type >::bkts private
Definition at line 22 of file unordered_map.hpp.
DEFAULT_NUM_BUCKETS
template<typename key_type , typename value_type > const size_t std::unordered_map< key_type, value_type >::DEFAULT_NUM_BUCKETS = 10 static private
Definition at line 21 of file unordered_map.hpp.
The documentation for this class was generated from the following file:
Kernel/include/std/unordered_map.hpp