Fennix: anonymous_namespace{time-stubs.cpp} Namespace Reference
anonymous_namespace{time-stubs.cpp} Namespace Reference
Data Structures
struct tzfile
Functions
void civil_from_days (time_t days_since_epoch, int *year, unsigned int *month, unsigned int *day)
void weekday_from_days (time_t days_since_epoch, unsigned int *weekday)
void yearday_from_date (unsigned int year, unsigned int month, unsigned int day, unsigned int *yday)
int unix_local_from_gmt (time_t unix_gmt, time_t *offset, bool *dst, char **tm_zone)
Variables
unsigned char tt_isdst
unsigned char tt_abbrind
Data Structure Documentation
anonymous_namespace{time-stubs.cpp}::tzfile
struct anonymous_namespace{time-stubs.cpp}::tzfile
Definition at line 362 of file time-stubs.cpp.
Data Fields
uint8_t magic[4]
uint8_t reserved[15]
uint32_t tzh_charcnt
uint32_t tzh_leapcnt
uint32_t tzh_timecnt
uint32_t tzh_ttisgmtcnt
uint32_t tzh_ttisstdcnt
uint32_t tzh_typecnt
uint8_t version
Function Documentation
civil_from_days()
void anonymous_namespace{time-stubs.cpp}::civil_from_days (time_t days_since_epoch, int * year, unsigned int * month, unsigned int * day)
Definition at line 502 of file time-stubs.cpp.
{
     time_t time = days_since_epoch + 719468;
     int era = (time >= 0 ? time : time - 146096) / 146097;
     unsigned int doe = static_cast<unsigned int>(time - era * 146097);
     unsigned int yoe = (doe - doe/1460 + doe/36524 - doe/146096) / 365;
     int y = static_cast<int>(yoe) + era * 400;
     unsigned int doy = doe - (365*yoe + yoe/4 - yoe/100);
     unsigned int mp = (5*doy + 2)/153;
     unsigned int d = doy - (153*mp+2)/5 + 1;
     unsigned int m = mp + (mp < 10 ? 3 : -9);
     *year = y + (m <= 2);
     *month = m;
     *day = d;
 }
References time(), and y.
Referenced by gmtime_r(), and localtime_r().
unix_local_from_gmt()
int anonymous_namespace{time-stubs.cpp}::unix_local_from_gmt (time_t unix_gmt, time_t * offset, bool * dst, char ** tm_zone)
Definition at line 536 of file time-stubs.cpp.
{
     tzfile tzfile_time;
     memcpy(&tzfile_time, reinterpret_cast<char *>(get_localtime_window()->get()), sizeof(tzfile));
     tzfile_time.tzh_ttisgmtcnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_ttisgmtcnt);
     tzfile_time.tzh_ttisstdcnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_ttisstdcnt);
     tzfile_time.tzh_leapcnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_leapcnt);
     tzfile_time.tzh_timecnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_timecnt);
     tzfile_time.tzh_typecnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_typecnt);
     tzfile_time.tzh_charcnt = mlibc::bit_util<uint32_t>::byteswap(tzfile_time.tzh_charcnt);
     if(tzfile_time.magic[0] != 'T' || tzfile_time.magic[1] != 'Z' || tzfile_time.magic[2] != 'i'
             || tzfile_time.magic[3] != 'f') {
         mlibc::infoLogger() << "mlibc: /etc/localtime is not a valid TZinfo file" << frg::endlog;
         return -1;
     }
     if(tzfile_time.version != '\0' && tzfile_time.version != '2' && tzfile_time.version != '3') {
         mlibc::infoLogger() << "mlibc: /etc/localtime has an invalid TZinfo version"
                 << frg::endlog;
         return -1;
     }
     int index = -1;
     for(size_t i = 0; i < tzfile_time.tzh_timecnt; i++) {
         int32_t ttime;
         memcpy(&ttime, reinterpret_cast<char *>(get_localtime_window()->get()) + sizeof(tzfile)
                 + i * sizeof(int32_t), sizeof(int32_t));
         ttime = mlibc::bit_util<uint32_t>::byteswap(ttime);
         // If we are before the first transition, the format dicates that
         // the first ttinfo entry should be used (and not the ttinfo entry pointed
         // to by the first transition time).
         if(i && ttime > unix_gmt) {
             index = i - 1;
             break;
         }
     }
     // The format dictates that if no transition is applicable,
     // the first entry in the file is chosen.
     uint8_t ttinfo_index = 0;
     if(index >= 0) {
         memcpy(&ttinfo_index, reinterpret_cast<char *>(get_localtime_window()->get()) + sizeof(tzfile)
                 + tzfile_time.tzh_timecnt * sizeof(int32_t)
                 + index * sizeof(uint8_t), sizeof(uint8_t));
     }
     // There should be at least one entry in the ttinfo table.
     // TODO: If there is not, we might want to fall back to UTC, no DST (?).
     __ensure(tzfile_time.tzh_typecnt);
     ttinfo time_info;
     memcpy(&time_info, reinterpret_cast<char *>(get_localtime_window()->get()) + sizeof(tzfile)
             + tzfile_time.tzh_timecnt * sizeof(int32_t)
             + tzfile_time.tzh_timecnt * sizeof(uint8_t)
             + ttinfo_index * sizeof(ttinfo), sizeof(ttinfo));
     time_info.tt_gmtoff = mlibc::bit_util<uint32_t>::byteswap(time_info.tt_gmtoff);
     char *abbrevs = reinterpret_cast<char *>(get_localtime_window()->get()) + sizeof(tzfile)
         + tzfile_time.tzh_timecnt * sizeof(int32_t)
         + tzfile_time.tzh_timecnt * sizeof(uint8_t)
         + tzfile_time.tzh_typecnt * sizeof(struct ttinfo);
     *offset = time_info.tt_gmtoff;
     *dst = time_info.tt_isdst;
     *tm_zone = abbrevs + time_info.tt_abbrind;
     return 0;
 }
References __ensure, file_window::get(), get_localtime_window(), i, index(), mlibc::infoLogger, anonymous_namespace{time-stubs.cpp}::tzfile::magic, memcpy, offset, anonymous_namespace{time-stubs.cpp}::tzfile::tzh_charcnt, anonymous_namespace{time-stubs.cpp}::tzfile::tzh_leapcnt, anonymous_namespace{time-stubs.cpp}::tzfile::tzh_timecnt, anonymous_namespace{time-stubs.cpp}::tzfile::tzh_ttisgmtcnt, anonymous_namespace{time-stubs.cpp}::tzfile::tzh_ttisstdcnt, anonymous_namespace{time-stubs.cpp}::tzfile::tzh_typecnt, and anonymous_namespace{time-stubs.cpp}::tzfile::version.
Referenced by localtime_r().
weekday_from_days()
void anonymous_namespace{time-stubs.cpp}::weekday_from_days (time_t days_since_epoch, unsigned int * weekday)
Definition at line 518 of file time-stubs.cpp.
{
     *weekday = static_cast<unsigned int>(days_since_epoch >= -4 ?
             (days_since_epoch+4) % 7 : (days_since_epoch+5) % 7 + 6);
 }
Referenced by gmtime_r(), and localtime_r().
yearday_from_date()
void anonymous_namespace{time-stubs.cpp}::yearday_from_date (unsigned int year, unsigned int month, unsigned int day, unsigned int * yday)
Definition at line 523 of file time-stubs.cpp.
{
     unsigned int n1 = 275 * month / 9;
     unsigned int n2 = (month + 9) / 12;
     unsigned int n3 = (1 + (year - 4 * year / 4 + 2) / 3);
     *yday = n1 - (n2 * n3) + day - 30;
 }
Referenced by gmtime_r(), and localtime_r().
Variable Documentation
tt_abbrind
unsigned char anonymous_namespace{time-stubs.cpp}::tt_abbrind
Definition at line 377 of file time-stubs.cpp.
tt_isdst
unsigned char anonymous_namespace{time-stubs.cpp}::tt_isdst
Definition at line 376 of file time-stubs.cpp.