Fennix: Userspace/apps/base/bash/lib/sh/stringvec.c File Reference
stringvec.c File Reference
#include <config.h>
#include <bashtypes.h>
#include <bashansi.h>
#include <stdio.h>
#include <chartypes.h>
#include "shell.h"
Functions
char ** strvec_create (int n)
char ** strvec_mcreate (int n)
char ** strvec_resize (char **array, int nsize)
char ** strvec_mresize (char **array, int nsize)
int strvec_len (char **array)
void strvec_flush (char **array)
void strvec_dispose (char **array)
int strvec_remove (char **array, char *name)
int strvec_search (char **array, char *name)
char ** strvec_copy (char **array)
int strvec_posixcmp (char **s1, char **s2)
int strvec_strcmp (char **s1, char **s2)
void strvec_sort (char **array, int posix)
char ** strvec_from_word_list (WORD_LIST *list, int alloc, int starting_index, int *ip)
WORD_LIST * strvec_to_word_list (char **array, int alloc, int starting_index)
Function Documentation
strvec_copy()
char** strvec_copy (char ** array)
Definition at line 142 of file stringvec.c.
 {
   register int i;
   int len;
   char **ret;
   len = strvec_len (array);
   ret = (char **)xmalloc ((len + 1) * sizeof (char *));
   for (i = 0; array[i]; i++)
     ret[i] = savestring (array[i]);
   ret[i] = (char *)NULL;
   return (ret);
 }
References i, len, NULL, savestring(), strvec_len(), and xmalloc.
strvec_create()
char** strvec_create (int n)
Definition at line 37 of file stringvec.c.
 {
   return ((char **)xmalloc ((n) * sizeof (char *)));
 }
References n, and xmalloc.
Referenced by all_variables_matching_prefix(), dispose_temporary_env(), get_group_list(), ignore_globbed_names(), make_env_array_from_var_list(), save_dollar_vars(), strlist_create(), tilde_initialize(), and user_command_matches().
strvec_dispose()
void strvec_dispose (char ** array)
Definition at line 93 of file stringvec.c.
 {
   if (array == 0)
     return;
   strvec_flush (array);
   free (array);
 }
References free, and strvec_flush().
Referenced by dispose_temporary_env(), glob_expand_word_list(), and strlist_dispose().
strvec_flush()
void strvec_flush (char ** array)
Definition at line 80 of file stringvec.c.
 {
   register int i;
   if (array == 0)
     return;
   for (i = 0; array[i]; i++)
     free (array[i]);
 }
References free, and i.
Referenced by maybe_make_export_env(), strlist_flush(), and strvec_dispose().
strvec_from_word_list()
char** strvec_from_word_list (WORD_LIST * list, int alloc, int starting_index, int * ip)
Definition at line 220 of file stringvec.c.
 {
   int count;
   char **array;
   count = list_length (list);
   array = (char **)xmalloc ((1 + count + starting_index) * sizeof (char *));
   for (count = 0; count < starting_index; count++)
     array[count] = (char *)NULL;
   for (count = starting_index; list; count++, list = list->next)
     array[count] = alloc ? savestring (list->word->word) : list->word->word;
   array[count] = (char *)NULL;
   if (ip)
     *ip = count;
   return (array);
 }
References count, list(), list_length(), node::next, NULL, savestring(), and xmalloc.
Referenced by execute_disk_command(), make_builtin_argv(), and strlist_from_word_list().
strvec_len()
int strvec_len (char ** array)
Definition at line 69 of file stringvec.c.
 {
   register int i;
   for (i = 0; array[i]; i++);
   return (i);
 }
References i.
Referenced by execute_shell_script(), make_env_array_from_var_list(), shell_execve(), sort_variables(), strvec_copy(), and strvec_sort().
strvec_mcreate()
char** strvec_mcreate (int n)
Definition at line 45 of file stringvec.c.
 {
   return ((char **)malloc ((n) * sizeof (char *)));
 }
References malloc, and n.
strvec_mresize()
char** strvec_mresize (char ** array, int nsize)
Definition at line 60 of file stringvec.c.
 {
   return ((char **)realloc (array, nsize * sizeof (char *)));
 }
References realloc.
strvec_posixcmp()
int strvec_posixcmp (char ** s1, char ** s2)
Definition at line 164 of file stringvec.c.
 {
   int result;
 #if defined (HAVE_STRCOLL)
    result = strcoll (*s1, *s2);
    if (result != 0)
      return result;
 #endif
   if ((result = **s1 - **s2) == 0)
     result = strcmp (*s1, *s2);
   return (result);
 }
References s1, s2, strcmp, and strcoll().
Referenced by strvec_sort().
strvec_remove()
int strvec_remove (char ** array, char * name)
Definition at line 104 of file stringvec.c.
 {
   register int i, j;
   char *x;
   if (array == 0)
     return 0;
   for (i = 0; array[i]; i++)
     if (STREQ (name, array[i]))
       {
     x = array[i];
     for (j = i; array[j]; j++)
       array[j] = array[j + 1];
     free (x);
     return 1;
       }
   return 0;
 }
References free, i, j, STREQ, and x.
Referenced by strlist_remove().
strvec_resize()
char** strvec_resize (char ** array, int nsize)
Definition at line 52 of file stringvec.c.
 {
   return ((char **)xrealloc (array, nsize * sizeof (char *)));
 }
References xrealloc.
Referenced by execute_shell_script(), maybe_make_export_env(), shell_execve(), strlist_resize(), and user_command_matches().
strvec_search()
int strvec_search (char ** array, char * name)
Definition at line 128 of file stringvec.c.
 {
   int i;
   for (i = 0; array[i]; i++)
     if (STREQ (name, array[i]))
       return (i);
   return (-1);
 }
References i, and STREQ.
strvec_sort()
void strvec_sort (char ** array, int posix)
Definition at line 201 of file stringvec.c.
 {
   if (posix)
     qsort (array, strvec_len (array), sizeof (char *), (QSFUNC *)strvec_posixcmp);
   else
     qsort (array, strvec_len (array), sizeof (char *), (QSFUNC *)strvec_strcmp);
 }
References qsort(), strvec_len(), strvec_posixcmp(), and strvec_strcmp().
Referenced by strlist_sort().
strvec_strcmp()
int strvec_strcmp (char ** s1, char ** s2)
Definition at line 184 of file stringvec.c.
 {
 #if defined (HAVE_STRCOLL)
    return (strcoll (*s1, *s2));
 #else /* !HAVE_STRCOLL */
   int result;
   if ((result = **s1 - **s2) == 0)
     result = strcmp (*s1, *s2);
   return (result);
 #endif /* !HAVE_STRCOLL */
 }
References s1, s2, strcmp, and strcoll().
Referenced by strvec_sort().
strvec_to_word_list()
WORD_LIST* strvec_to_word_list (char ** array, int alloc, int starting_index)
Definition at line 247 of file stringvec.c.
 {
   WORD_LIST *list;
   WORD_DESC *w;
   int i, count;
   if (array == 0 || array[0] == 0)
     return (WORD_LIST *)NULL;
   for (count = 0; array[count]; count++)
     ;
   for (i = starting_index, list = (WORD_LIST *)NULL; i < count; i++)
     {
       w = make_bare_word (alloc ? array[i] : "");
       if (alloc == 0)
     {
       free (w->word);
       w->word = array[i];
     }
       list = make_word_list (w, list);
     }
   return (REVERSE_LIST (list, WORD_LIST *));
 }
References count, free, i, list(), make_bare_word(), make_word_list(), NULL, REVERSE_LIST, and w.
Referenced by parameter_brace_expand(), and strlist_to_word_list().