Fennix Kernel: Kernel/include/vm.hpp File Reference
vm.hpp File Reference
#include <types.h>
Functions
bool IsVirtualizedEnvironment ()
Function Documentation
IsVirtualizedEnvironment()
bool IsVirtualizedEnvironment ()
Detects if the system is running in a virtualized environment.
Returns
true if the system is running in a virtualized environment, false otherwise.
Definition at line 178 of file detect.cpp.
 {
     static bool IsVM = false;
     static int vm_check = 0;
     if (vm_check++)
     {
         debug("Virtualized environment: %s",
               IsVM ? "Yes" : "No");
         return IsVM;
     }
     debug("Detecting virtualized environment...");
     if (DetectByHypervisor())
         IsVM = true;
     if (IsVMwareBackdoorAvailable())
         IsVM = true;
     if (DetectByCPUID())
         IsVM = true;
     if (DetectByHPET())
         IsVM = true;
     /* TODO: Add more detection methods */
     debug("Virtualized environment: %s",
           IsVM ? "Yes" : "No");
     return IsVM;
 }
References debug, DetectByCPUID(), DetectByHPET(), DetectByHypervisor(), and IsVMwareBackdoorAvailable().
Referenced by KernelMainThread().