Fennix: Lynx/UEFI/src/Lynx.c File Reference
Lynx.c File Reference
#include <efi.h>
#include <efilib.h>
#include "Memory/memory.hpp"
#include "FileLoader.h"
#include "printf.h"
Functions
void port_byte_out (short unsigned int port, unsigned char value)
unsigned char port_byte_in (short unsigned int port)
int strlen (const char s[])
int init_serial ()
void printf (const char *format,...)
void putchar (char c)
EFI_STATUS EFIAPI efi_main (EFI_HANDLE ImageHandle, EFI_SYSTEM_TABLE *SystemTable)
Function Documentation
efi_main()
EFI_STATUS EFIAPI efi_main (EFI_HANDLE ImageHandle, EFI_SYSTEM_TABLE * SystemTable)
Definition at line 68 of file Lynx.c.
 {
     InitializeLib(ImageHandle, SystemTable);
     SystemTable->BootServices->SetWatchdogTimer(0, 0, 0, NULL);
     Print(L"Lynx Bootloader © EnderIce2 2022\n");
     Print(L"UEFI not implemented\n");
             while (1)
             asm("hlt");
     InitializeMemoryManagement(ImageHandle, SystemTable);
     EFI_FILE *Kernel = LoadFile(NULL, L"kernel.fsys", ImageHandle, SystemTable);
     if (Kernel == NULL)
     {
         Print(L"Kernel not found\n");
         while (1)
             asm("hlt");
     }
     while (1)
         asm("hlt");
     return EFI_SUCCESS;
 }
References InitializeMemoryManagement(), Tasking::Kernel, L, LoadFile(), NULL, and Print.
init_serial()
int init_serial ()
Definition at line 33 of file Lynx.c.
 {
     // TODO: fix crash on virtualbox (or virtualbox is faulty???????????)
     port_byte_out(0x3F8 + 1, 0x00);
     port_byte_out(0x3F8 + 3, 0x80);
     port_byte_out(0x3F8 + 0, 0x03);
     port_byte_out(0x3F8 + 1, 0x00);
     port_byte_out(0x3F8 + 3, 0x03);
     port_byte_out(0x3F8 + 2, 0xC7);
     port_byte_out(0x3F8 + 4, 0x0B);
     port_byte_out(0x3F8 + 4, 0x1E);
     port_byte_out(0x3F8 + 0, 0xAE);
     if (port_byte_in(0x3F8 + 0) != 0xAE)
     {
         return -1; // serial port is faulty
     }
     port_byte_out(0x3F8 + 4, 0x0F);
     return 0;
 }
References port_byte_in(), and port_byte_out().
port_byte_in()
unsigned char port_byte_in (short unsigned int port)
Definition at line 16 of file Lynx.c.
 {
     unsigned char ReturnValue;
     __asm__ volatile("inb %1, %0"
                      : "=a"(ReturnValue)
                      : "Nd"(port));
     return ReturnValue;
 }
References __asm__(), and port.
Referenced by init_serial(), and putchar().
port_byte_out()
void port_byte_out (short unsigned int port, unsigned char value)
Definition at line 9 of file Lynx.c.
 {
     __asm__ volatile("outb %0, %1"
                      :
                      : "a"(value), "Nd"(port));
 }
References __asm__(), port, and value.
Referenced by init_serial(), and putchar().
printf()
void printf (const char * format, ...)
An implementation of the C standard's printf/vprintf
Note
you must implement a putchar_ function for using this function - it invokes putchar_ rather than directly performing any I/O (which insulates it from any dependence on the operating system and external libraries).
Parameters
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each %-specifier in format string
Returns
The number of characters written into s, not counting the terminating null character
Definition at line 53 of file Lynx.c.
 {
     va_list args;
     va_start(args, format);
     printf_(format, args);
     va_end(args);
 }
References args, format(), printf_(), va_end, and va_start.
putchar()
void putchar (char c)
Definition at line 61 of file Lynx.c.
 {
     while ((port_byte_in(0x3F8 + 5) & 0x20) == 0)
         ;
     port_byte_out(0x3F8, c);
 }
References c, port_byte_in(), and port_byte_out().
Referenced by print_esc_string(), print_formatted(), and putchar_wrapper().
strlen()
int strlen (const char s[])
Definition at line 25 of file Lynx.c.
 {
     int i = 0;
     while (s[i] != '\0')
         ++i;
     return i;
 }
References i, and s.
Referenced by __attribute__(), __dls3(), __get_resolv_conf(), __getopt_long_core(), __getopt_msg(), __lookup_serv(), __mkostemps(), NetworkDHCP::__no_sanitize(), SymbolResolver::__no_sanitize(), Tasking::__no_sanitize(), __nscd_query(), __strchrnul(), __strftime_fmt_1(), __strxfrm_l(), _evalfile(), _hs_append_history_line(), _hs_history_patsearch(), _nl_find_domain(), _nl_find_msg(), _nl_init_domain_conv(), _nl_load_domain(), _nl_log_untranslated(), _nl_make_l10nflist(), _remove_directory(), _rl_copy_to_kill_ring(), _rl_custom_readline_prefix(), _rl_isearch_dispatch(), _rl_isearch_fini(), _rl_isearch_init(), _rl_macro_dumper_internal(), _rl_make_prompt_for_search(), _rl_print_color_indicator(), _rl_reset_region_color(), _rl_savestring(), _rl_strindex(), _rl_untranslate_macro_value(), _rl_vi_replace_insert(), acpid_main(), add_cmd(), add_exclude(), add_links(), add_peers(), add_symbols_from(), add_to_ino_dev_hashtable(), VirtualFileSystem::Virtual::AddNewChild(), adjtimex_main(), alrm_catcher(), ansic_quote(), argz_count__(), argz_stringify__(), atof(), atoi(), awk_printf(), awk_split(), awk_sub(), basename(), basename_builtin(), basename_main(), bb_verror_msg(), bbunpack(), buffer_pwrite(), builtin_arrayref_flags(), builtin_eval(), cag_option_get_print_indention(), cal_main(), calcsize(), cat_main(), catopen(), center(), change_to_size(), chat_main(), chcon_main(), check_existence_through_netlink(), cht_CheckCheat(), cmdlookup(), colon(), comm_match(), command_generator(), compare_keys(), compute_lcd_of_matches(), conf_choice(), conf_get_default_confname(), conf_read_simple(), conf_string(), convert_dname(), convert_to_struct(), count_strstr(), cprintf(), create_links_from_list(), csvsplit(), cut_file(), cut_out_ull_opt(), cutbytes(), cutchars(), cwk_path_change_extension(), cwk_path_change_root(), cwk_path_change_segment(), cwk_path_output(), data_extract_all_prefix(), dbg_print_flags(), dcngettext(), de_backslash(), decode_prompt_string(), dequote_escapes(), dialog_checklist(), dialog_inputbox(), die(), DirIsFile(), dirname(), dirname_builtin(), dirspell(), dname_dec(), do_add_or_delete(), do_cmd(), do_glob(), do_nftw(), do_redirection_internal(), do_set(), do_sethostname(), do_tzset(), download_one_url(), DriverDisplayPrint(), dsvsplit(), dupstr(), echo_main(), escape(), escape_input(), escape_text(), EscapeShellString(), eval6(), evaluate(), evaluate_string(), exec_builtin(), exec_kernel_doc(), expand_arith_string(), expand_one_var(), expand_prompt(), expand_string_dollar_quote(), expand_string_if_necessary(), expand_variable(), expand_word_internal(), exponent(), expr_print_file_helper(), extract_colon_unit(), extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), F_Ticker(), fcopy(), fileAction(), fill_package_struct(), filter_rename_config(), find_block_device_in_dir(), find_charmap(), find_codeset(), find_export_symbols(), find_user_command_in_path(), find_user_command_internal(), finish_oldfile(), first_alpha(), fixup_rpath(), floating(), fmt_str(), fnprint(), fnwidth(), fputs(), full_write1_str(), full_write2_str(), G_RecordDemo(), gather_options_str(), get_bash_name(), get_charset_aliases(), get_input_line(), get_local_var_value(), get_mode(), get_modinfo_value(), get_node(), get_tmpdir(), getaddrinfo(), getdomainname(), getenv(), GetGameName(), gethostbyname2_r(), getlogin_r(), getmntent_r(), getnameinfo(), VirtualFileSystem::Virtual::GetPathFromNode(), getprotoent(), getspnam_r(), getsubopt(), glob(), glob_dir_to_array(), glob_filename(), glob_vector(), glue_prefix_and_suffix(), grep_file(), groupnum(), handle_dir_common(), handle_incoming_and_exit(), handle_special(), hash_find(), hash_remove(), history_arg_extract(), history_backupfile(), history_do_write(), history_expand(), history_expand_internal(), history_filename(), history_search_internal(), history_tempfile(), hush_main(), I_Error(), I_PrintBanner(), if(), if_redefined(), ife_print(), index_in_strings_case_insensitive(), index_in_substrings(), indirection_level_string(), inet_ntop(), INET_rresolve(), init_exec(), init_main(), initialize_shell_variables(), initialize_siglist(), InitLimineAfterStack(), insert_match(), ipaddr_modify(), iprule_modify(), is_prefixed_with(), is_section_name(), is_suffixed_with(), is_whole_disk(), isolate_tilde_prefix(), kill_main(), kw_lookup(), list_table(), ll_proto_a2n(), ll_type_n2a(), load_library(), LoadDefaultCollection(), locale_charset(), log_locally(), logger_main(), logmatch(), logread_main(), lpqr_main(), lsmod_main(), M_Drawer(), M_ExtractFileBase(), M_SaveSelect(), M_StrCaseStr(), M_StringConcat(), M_StringCopy(), M_StringDuplicate(), M_StringEndsWith(), M_StringHeight(), M_StringJoin(), M_StringReplace(), M_StringStartsWith(), M_StringWidth(), mailstat(), main(), make_all_argv_opts(), make_default_mailpath(), make_device(), make_hash(), make_here_document(), make_redirection(), make_tempdir(), make_word_flags(), match(), mbschr(), mbsrtowcs(), md5_crypt(), md5String(), mk_env_string(), mkdirpath(), mkdtemp(), mktemp(), modinfo(), mount_it_now(), multiboot_main(), name_from_hosts(), named_function_string(), nbdclient_main(), new_get_kernel_symbols(), new_init_action(), next_file(), nftw(), nl_main(), nmeter_main(), nodeckstrdup(), noninc_dosearch(), normalize(), VirtualFileSystem::Virtual::NormalizePath(), nproc_main(), number(), o_addQstr(), o_addstr(), o_addstr_with_NUL(), obj_elf_hash(), obj_load_order_prio(), obj_string_patch(), obscure_msg(), openhere(), std::string::operator=(), opt_in_list(), P_SaveGameFile(), padvance_magic(), param_expand(), parameter_brace_expand(), parameter_brace_expand_word(), parse(), parse_cmd_args(), parse_common(), parse_compound_assignment(), parse_comsub(), parse_conf(), parse_conf_file(), parse_escapes(), parse_group(), parse_matched_pair(), parse_module(), parse_mount_options(), parse_one_line(), parse_subst_cmd(), ParseConfig(), parser_if(), partname(), pat_subst(), Tasking::PCB::PCB(), perror(), pgrep_main(), phash_search(), pid_is_name(), pointer(), polite_directory_format(), pop3_checkr(), popmaildir_main(), pos_params_assignment(), posix_spawn_file_actions_addchdir_np(), posix_spawn_file_actions_addopen(), prepend_new_eth_table(), prf_hmac_sha256(), print_addrinfo(), print_autowrap(), print_e2flags_long(), print_filename(), print_flags_separated(), print_line(), print_offending_line(), print_title(), printargs(), PrintDehackedBanners(), printstr_base64(), process_config_line(), process_files(), process_packet(), process_stdin(), purge_package(), pushstring(), quote_escapes_internal(), quote_globbing_chars(), quote_string(), quote_string_for_globbing(), quote_string_for_repl(), rdval(), read_alias_file(), read_base64(), read_cmdline(), read_cstate_counts(), read_line_input(), read_lines(), read_token_word(), VirtualFileSystem::USTAR::ReadArchive(), realpath(), redraw_prompt(), regerror(), remove_package(), remove_pattern(), remove_quoted_ifs(), remove_quoted_nulls(), remove_trailing_whitespace(), Tasking::TCB::Rename(), Tasking::PCB::Rename(), std::string::replace(), replace_tempfile(), rev_main(), rl_bind_keyseq_if_unbound_in_map(), rl_complete_internal(), rl_display_match_list(), rl_display_search(), rl_expand_prompt(), rl_filename_completion_function(), rl_function_of_keyseq(), rl_generic_bind(), rl_insert_comment(), rl_insert_text(), rl_invoking_keyseqs_in_map(), rl_macro_bind(), rl_menu_complete(), rl_message(), rl_on_new_line_with_prompt(), rl_parse_and_bind(), rl_quote_filename(), rl_redisplay(), rl_replace_line(), rl_username_completion_function(), rl_vi_yank_pop(), rl_yank_pop(), rmescapes(), rmoldest(), rpm_getstr(), rtc_xopen(), run_pipe(), runsvdir_main(), sanitize_env_if_suid(), savestring(), say(), scan_and_match(), scan_inet_proc_line(), scan_proc_net_or_maps(), scan_request(), scan_troff(), scanright(), searchLines(), send_file_and_exit(), sendmail_main(), seq_main(), service(), set_binding_values(), set_mode(), setenv(), setfattr_main(), setfiles_main(), setinputstring(), setlocale(), setup_heredoc(), setup_ignore_patterns(), setvar(), sh_backslash_quote(), sh_canonpath(), sh_double_quote(), sh_makepath(), sh_mktmpdir(), sh_mktmpfd(), sh_mktmpname(), sh_modcase(), sh_physpath(), sh_single_quote(), sh_stat(), sh_strvis(), sh_un_double_quote(), SHA1_UpdateString(), sha_crypt(), shell_builtin_ulimit(), shell_execve(), shell_getc(), shell_ungets(), show_status_line(), show_textbox(), skip_matched_pair(), skip_to_delim(), smtp_checkp(), sort_main(), split_main(), SplitLine(), sstrdup(), st_expr_expand(), stack_putstr(), start_stop_daemon_main(), StartKernelShell(), str_append(), strcasestr(), strcat(), strcreplace(), strdup(), strduplicate(), strerror_r(), strftime(), strftime_builtin(), strgrow(), std::string::string(), string_checker(), string_extract(), string_extract_double_quoted(), string_extract_single_quoted(), string_list_internal(), string_option_to_env(), string_quote_removal(), string_to_llist(), string_transform(), string_var_assignment(), strings(), strip(), stripwhite(), strlcat(), strlcpy(), strmaxcat(), strmaxcpy(), strncat(), strptime(), strrchr(), strrcmp(), strrstr(), strsep(), strsub(), strtodest(), subCommand(), subevalvar(), sv_emacs_modestr(), sv_isrchterm(), sv_vicmd_modestr(), sv_viins_modestr(), sym_re_search(), sym_set_string_value(), sys_kernelctl(), table_lookup(), targp_parse(), Tasking::TCB::TCB(), tcpudpsvd_main(), tempnam(), textdomain(), tgetent(), tilde_expand(), tilde_find_prefix(), tilde_find_suffix(), tparam1(), trim(), trim_pathname(), CrashHandler::TrimWhiteSpace(), udhcp_option_idx(), udhcpc_main(), uevent_main(), unescape(), unicode_strlen(), unquoted_glob_pattern_p(), unzip_main(), update_line(), update_passwd(), updatepwd(), user_command_matches(), CrashHandler::UserInput(), validate_path(), vgetopt32(), volume_id_probe_romfs(), W_AddFile(), wget_main(), write_helpfiles(), write_longdocs(), write_new_utmp(), xargs_main(), xmalloc_fgets_internal(), xmalloc_follow_symlinks(), xmalloc_optname_optval(), xmalloc_realpath_coreutils(), xmalloc_substitute_string(), xrealloc_getcwd_or_warn(), xwrite_str(), and ZenityErrorBox().