Fennix Userspace: Userspace/musl/src/dirent/scandir.c File Reference
scandir.c File Reference
#include <dirent.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <errno.h>
#include <stddef.h>
Functions
int scandir (const char *path, struct dirent ***res, int(*sel)(const struct dirent *), int(*cmp)(const struct dirent **, const struct dirent **))
Function Documentation
scandir()
int scandir (const char * path, struct dirent *** res, int(*)(const struct dirent *) sel, int(*)(const struct dirent **, const struct dirent **) cmp)
Definition at line 8 of file scandir.c.
 {
     DIR *d = opendir(path);
     struct dirent *de, **names=0, **tmp;
     size_t cnt=0, len=0;
     int old_errno = errno;
     if (!d) return -1;
     while ((errno=0), (de = readdir(d))) {
         if (sel && !sel(de)) continue;
         if (cnt >= len) {
             len = 2*len+1;
             if (len > SIZE_MAX/sizeof *names) break;
             tmp = realloc(names, len * sizeof *names);
             if (!tmp) break;
             names = tmp;
         }
         names[cnt] = malloc(de->d_reclen);
         if (!names[cnt]) break;
         memcpy(names[cnt++], de, de->d_reclen);
     }
     closedir(d);
     if (errno) {
         if (names) while (cnt-->0) free(names[cnt]);
         free(names);
         return -1;
     }
     errno = old_errno;
     if (cmp) qsort(names, cnt, sizeof *names, (int (*)(const void *, const void *))cmp);
     *res = names;
     return cnt;
 }
References closedir(), cmp(), cnt, dirent::d_reclen, errno, free, malloc, memcpy(), names, opendir(), qsort(), readdir(), realloc, and SIZE_MAX.
Referenced by tree_print().