Fennix: SysDbg Namespace Reference
SysDbg Namespace Reference
Functions
NIF void Write (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void WriteLine (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void LockedWrite (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
NIF void LockedWriteLine (DebugLevel Level, const char *File, int Line, const char *Function, const char *Format,...)
Function Documentation
LockedWrite()
NIF void SysDbg::LockedWrite (DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 148 of file debugger.cpp.
     {
         SmartTimeoutLock(DebuggerLock, 1000);
         va_list args;
         va_start(args, Format);
         if (!WritePrefix(Level, File, Line, Function, Format, args))
         {
             va_end(args);
             return;
         }
         vfctprintf(uart_wrapper, nullptr, Format, args);
         va_end(args);
     }
References args, Level, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
LockedWriteLine()
NIF void SysDbg::LockedWriteLine (DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 162 of file debugger.cpp.
     {
         SmartTimeoutLock(DebuggerLock, 1000);
         va_list args;
         va_start(args, Format);
         if (!WritePrefix(Level, File, Line, Function, Format, args))
         {
             va_end(args);
             return;
         }
         vfctprintf(uart_wrapper, nullptr, Format, args);
         va_end(args);
         uart_wrapper('\n', nullptr);
     }
References args, Level, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
Write()
NIF void SysDbg::Write (DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 121 of file debugger.cpp.
     {
         va_list args;
         va_start(args, Format);
         if (!WritePrefix(Level, File, Line, Function, Format, args))
         {
             va_end(args);
             return;
         }
         vfctprintf(uart_wrapper, nullptr, Format, args);
         va_end(args);
     }
References args, Level, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().
Referenced by APIC::APIC::APIC(), Memory::VirtualMemoryArea::CreateCoWRegion(), APIC::APIC::EOI(), APIC::APIC::ICR(), APIC::APIC::IPI(), Driver::MasterDeviceFile::NewAudio(), Driver::MasterDeviceFile::NewBlock(), Driver::MasterDeviceFile::NewNet(), Port::ReadWrite(), Driver::RegisterAudioDevice(), RegisterAudioDevice(), Driver::RegisterBlockDevice(), RegisterBlockDevice(), Driver::RegisterNetDevice(), RegisterNetDevice(), APIC::APIC::SendInitIPI(), APIC::APIC::SendStartupIPI(), and Driver::SlaveDeviceFile::write().
WriteLine()
NIF void SysDbg::WriteLine (DebugLevel Level, const char * File, int Line, const char * Function, const char * Format, ...)
Definition at line 134 of file debugger.cpp.
     {
         va_list args;
         va_start(args, Format);
         if (!WritePrefix(Level, File, Line, Function, Format, args))
         {
             va_end(args);
             return;
         }
         vfctprintf(uart_wrapper, nullptr, Format, args);
         va_end(args);
         uart_wrapper('\n', nullptr);
     }
References args, Level, uart_wrapper(), va_end, va_start, vfctprintf(), and WritePrefix().