Fennix: Userspace/apps/base/busybox/networking/udhcp/common.c File Reference
common.c File Reference
#include "common.h"
Macros
#define log_option(pfx, opt) ((void)0)
#define attach_option(opt_list, optflag, buffer, length, dhcpv6) attach_option(opt_list, optflag, buffer, length)
Functions
unsigned FAST_FUNC udhcp_option_idx (const char *name, const char *option_strings)
void FAST_FUNC init_scan_state (struct dhcp_packet *packet, struct dhcp_scan_state *scan_state)
uint8_t *FAST_FUNC udhcp_scan_options (struct dhcp_packet *packet, struct dhcp_scan_state *scan_state)
uint8_t *FAST_FUNC udhcp_get_option (struct dhcp_packet *packet, int code)
uint8_t *FAST_FUNC udhcp_get_option32 (struct dhcp_packet *packet, int code)
int FAST_FUNC udhcp_end_option (uint8_t *optionptr)
void FAST_FUNC udhcp_add_binary_option (struct dhcp_packet *packet, uint8_t *addopt)
struct option_set *FAST_FUNC udhcp_find_option (struct option_set *opt_list, uint8_t code, bool dhcpv6)
int FAST_FUNC udhcp_str2nip (const char *str, void *arg)
void *FAST_FUNC udhcp_insert_new_option (struct option_set **opt_list, unsigned code, unsigned length, bool dhcpv6)
static NOINLINE void attach_option (struct option_set **opt_list, const struct dhcp_optflag *optflag, char *buffer, int length, bool dhcpv6)
int FAST_FUNC udhcp_str2optset (const char *const_str, void *arg, const struct dhcp_optflag *optflags, const char *option_strings, bool dhcpv6)
int FAST_FUNC sprint_nip6 (char *dest, const uint8_t *ip)
Variables
const uint8_t MAC_BCAST_ADDR[6] ALIGN2
const uint8_t dhcp_option_lengths[] ALIGN1
Macro Definition Documentation
attach_option
#define attach_option (opt_list, optflag, buffer, length, dhcpv6) attach_option(opt_list, optflag, buffer, length)
Definition at line 487 of file common.c.
log_option
#define log_option (pfx, opt) ((void)0)
Definition at line 206 of file common.c.
Function Documentation
attach_option()
static NOINLINE void attach_option (struct option_set ** opt_list, const struct dhcp_optflag * optflag, char * buffer, int length, bool dhcpv6) static
Definition at line 490 of file common.c.
 {
     IF_NOT_UDHCPC6(bool dhcpv6 = 0;)
     struct option_set *existing;
     char *allocated = NULL;
     if ((optflag->flags & OPTION_TYPE_MASK) == OPTION_BIN) {
         const char *end;
         allocated = xstrdup(buffer); /* more than enough */
         end = hex2bin(allocated, buffer, 255);
         if (errno)
             bb_error_msg_and_die("malformed hex string '%s'", buffer);
         length = end - allocated;
         buffer = allocated;
     }
 #if ENABLE_FEATURE_UDHCP_RFC3397
     if ((optflag->flags & OPTION_TYPE_MASK) == OPTION_DNS_STRING) {
         /* reuse buffer and length for RFC1035-formatted string */
         allocated = buffer = (char *)dname_enc(/*NULL, 0,*/ buffer, &length);
     }
 #endif
     existing = udhcp_find_option(*opt_list, optflag->code, dhcpv6);
     if (!existing) {
         /* make a new option */
         uint8_t *p = udhcp_insert_new_option(opt_list, optflag->code, length, dhcpv6);
         if (!dhcpv6)
             memcpy(p + OPT_DATA, buffer, length);
         else
             memcpy(p + D6_OPT_DATA, buffer, length);
         goto ret;
     }
     if (optflag->flags & OPTION_LIST) {
         unsigned old_len;
         /* add it to an existing option */
         log2("attaching option %02x to existing member of list", optflag->code);
         old_len = existing->data[OPT_LEN];
         if (old_len + length < 255) {
             /* actually 255 is ok too, but adding a space can overlow it */
             existing->data = xrealloc(existing->data, OPT_DATA + 1 + old_len + length);
 // So far dhcp_optflags[] has no OPTION_STRING[_HOST] | OPTION_LIST items
 #if 0
             if ((optflag->flags & OPTION_TYPE_MASK) == OPTION_STRING
              || (optflag->flags & OPTION_TYPE_MASK) == OPTION_STRING_HOST
             ) {
                 /* add space separator between STRING options in a list */
                 existing->data[OPT_DATA + old_len] = ' ';
                 old_len++;
             }
 #endif
             memcpy(existing->data + OPT_DATA + old_len, buffer, length);
             existing->data[OPT_LEN] = old_len + length;
         } /* else, ignore the data, we could put this in a second option in the future */
     } /* else, ignore the new data */
  ret:
     free(allocated);
 }
References bb_error_msg_and_die(), dhcp_optflag::code, D6_OPT_DATA, dname_enc(), end, errno, dhcp_optflag::flags, free, hex2bin(), log2, memcpy, NULL, OPT_DATA, OPT_LEN, OPTION_BIN, OPTION_LIST, OPTION_STRING, OPTION_STRING_HOST, OPTION_TYPE_MASK, p, udhcp_find_option(), udhcp_insert_new_option(), xrealloc, and xstrdup().
init_scan_state()
void FAST_FUNC init_scan_state (struct dhcp_packet * packet, struct dhcp_scan_state * scan_state)
Definition at line 234 of file common.c.
 {
     scan_state->overload = 0;
     scan_state->rem = sizeof(packet->options);
     scan_state->optionptr = packet->options;
 }
References dhcp_scan_state::optionptr, dhcp_packet::options, dhcp_scan_state::overload, and dhcp_scan_state::rem.
Referenced by fill_envp(), and udhcp_get_option().
sprint_nip6()
int FAST_FUNC sprint_nip6 (char * dest, const uint8_t * ip)
Definition at line 719 of file common.c.
 {
     char hexstrbuf[16 * 2];
     bin2hex(hexstrbuf, (void*)ip, 16);
     return sprintf(dest, /* "%s" */
         "%.4s:%.4s:%.4s:%.4s:%.4s:%.4s:%.4s:%.4s",
         /* pre, */
         hexstrbuf + 0 * 4,
         hexstrbuf + 1 * 4,
         hexstrbuf + 2 * 4,
         hexstrbuf + 3 * 4,
         hexstrbuf + 4 * 4,
         hexstrbuf + 5 * 4,
         hexstrbuf + 6 * 4,
         hexstrbuf + 7 * 4
     );
 }
References bin2hex(), and sprintf().
Referenced by option_to_env(), and xmalloc_optname_optval().
udhcp_add_binary_option()
void FAST_FUNC udhcp_add_binary_option (struct dhcp_packet * packet, uint8_t * addopt)
Definition at line 361 of file common.c.
 {
     unsigned len;
     uint8_t *optionptr = packet->options;
     unsigned end = udhcp_end_option(optionptr);
     len = OPT_DATA + addopt[OPT_LEN];
     /* end position + (option code/length + addopt length) + end option */
     if (end + len + 1 >= DHCP_OPTIONS_BUFSIZE) {
 //TODO: learn how to use overflow option if we exhaust packet->options[]
         bb_error_msg("option 0x%02x did not fit into the packet",
                 addopt[OPT_CODE]);
         return;
     }
     log_option("adding option", addopt);
     memcpy(optionptr + end, addopt, len);
     optionptr[end + len] = DHCP_END;
 }
References bb_error_msg(), DHCP_END, DHCP_OPTIONS_BUFSIZE, end, len, log_option, memcpy, OPT_CODE, OPT_DATA, OPT_LEN, dhcp_scan_state::optionptr, dhcp_packet::options, and udhcp_end_option().
Referenced by add_client_options(), add_server_options(), and add_serverid_and_clientid_options().
udhcp_end_option()
int FAST_FUNC udhcp_end_option (uint8_t * optionptr)
Definition at line 346 of file common.c.
 {
     int i = 0;
     while (optionptr[i] != DHCP_END) {
         if (optionptr[i] != DHCP_PADDING)
             i += optionptr[i + OPT_LEN] + OPT_DATA-1;
         i++;
     }
     return i;
 }
References DHCP_END, DHCP_PADDING, i, OPT_DATA, OPT_LEN, and dhcp_scan_state::optionptr.
Referenced by add_client_options(), udhcp_add_binary_option(), udhcp_send_kernel_packet(), and udhcp_send_raw_packet().
udhcp_find_option()
struct option_set* FAST_FUNC udhcp_find_option (struct option_set * opt_list, uint8_t code, bool dhcpv6)
Definition at line 407 of file common.c.
 {
     IF_NOT_UDHCPC6(bool dhcpv6 = 0;)
     uint8_t cur_code;
     for (;;) {
         if (!opt_list)
             return opt_list; /* NULL */
         if (!dhcpv6) {
             cur_code = opt_list->data[OPT_CODE];
         } else {
 //FIXME: add support for code > 0xff
             if (opt_list->data[D6_OPT_CODE] != 0)
                 return NULL;
             cur_code = opt_list->data[D6_OPT_CODE + 1];
         }
         if (cur_code >= code) {
             if (cur_code == code)
                 return opt_list;
             return NULL;
         }
         opt_list = opt_list->next;
     }
 }
References code, D6_OPT_CODE, option_set::data, option_set::next, NULL, and OPT_CODE.
Referenced by attach_option().
udhcp_get_option()
uint8_t* FAST_FUNC udhcp_get_option (struct dhcp_packet * packet, int code)
Definition at line 317 of file common.c.
 {
     uint8_t *optptr;
     struct dhcp_scan_state scan_state;
     init_scan_state(packet, &scan_state);
     while ((optptr = udhcp_scan_options(packet, &scan_state)) != NULL) {
         if (optptr[OPT_CODE] == code) {
             log_option("option found", optptr);
             return optptr + OPT_DATA;
         }
     }
     /* log3 because udhcpc uses it a lot - very noisy */
     log3("option 0x%02x not found", code);
     return NULL;
 }
References code, init_scan_state(), log3, log_option, NULL, OPT_CODE, OPT_DATA, optptr, and udhcp_scan_options().
Referenced by get_dhcp_packet_type(), send_ACK(), send_offer(), udhcp_get_option32(), udhcpc_main(), and udhcpd_main().
udhcp_get_option32()
uint8_t* FAST_FUNC udhcp_get_option32 (struct dhcp_packet * packet, int code)
Definition at line 335 of file common.c.
 {
     uint8_t *r = udhcp_get_option(packet, code);
     if (r) {
         if (r[-OPT_DATA + OPT_LEN] != 4)
             r = NULL;
     }
     return r;
 }
References code, NULL, OPT_DATA, OPT_LEN, and udhcp_get_option().
Referenced by select_lease_time(), udhcpc_main(), and udhcpd_main().
udhcp_insert_new_option()
void* FAST_FUNC udhcp_insert_new_option (struct option_set ** opt_list, unsigned code, unsigned length, bool dhcpv6)
Definition at line 446 of file common.c.
 {
     IF_NOT_UDHCPC6(bool dhcpv6 = 0;)
     struct option_set *new, **curr;
     log2("attaching option %02x to list", code);
     new = xmalloc(sizeof(*new));
     if (!dhcpv6) {
         new->data = xzalloc(length + OPT_DATA);
         new->data[OPT_CODE] = code;
         new->data[OPT_LEN] = length;
     } else {
         new->data = xzalloc(length + D6_OPT_DATA);
         new->data[D6_OPT_CODE] = code >> 8;
         new->data[D6_OPT_CODE + 1] = code & 0xff;
         new->data[D6_OPT_LEN] = length >> 8;
         new->data[D6_OPT_LEN + 1] = length & 0xff;
     }
     curr = opt_list;
 //FIXME: DHCP6 codes > 255!!
     while (*curr && (*curr)->data[OPT_CODE] < code)
         curr = &(*curr)->next;
     new->next = *curr;
     *curr = new;
     return new->data;
 }
References code, D6_OPT_CODE, D6_OPT_DATA, D6_OPT_LEN, option_set::data, log2, option_set::next, OPT_CODE, OPT_DATA, OPT_LEN, xmalloc, and xzalloc().
Referenced by attach_option().
udhcp_option_idx()
unsigned FAST_FUNC udhcp_option_idx (const char * name, const char * option_strings)
Definition at line 209 of file common.c.
 {
     int n = index_in_strings(option_strings, name);
     if (n >= 0)
         return n;
     {
         char *buf, *d;
         const char *s;
         s = option_strings;
         while (*s)
             s += strlen(s) + 1;
         d = buf = xzalloc(s - option_strings);
         s = option_strings;
         while (!(*s == '\0' && s[1] == '\0')) {
             *d++ = (*s == '\0' ? ' ' : *s);
             s++;
         }
         bb_error_msg_and_die("unknown option '%s', known options: %s", name, buf);
     }
 }
References bb_error_msg_and_die(), buf, index_in_strings(), n, s, strlen(), and xzalloc().
Referenced by udhcp_str2optset(), udhcpc6_main(), and udhcpc_main().
udhcp_scan_options()
uint8_t* FAST_FUNC udhcp_scan_options (struct dhcp_packet * packet, struct dhcp_scan_state * scan_state)
Definition at line 244 of file common.c.
 {
     int len;
     enum {
         FILE_FIELD101  = FILE_FIELD  * 0x101,
         SNAME_FIELD101 = SNAME_FIELD * 0x101,
     };
     /* option bytes: [code][len][data1][data2]..[dataLEN] */
     while (1) {
         if (scan_state->rem <= 0) {
  complain:
             bb_simple_error_msg("bad packet, malformed option field");
             return NULL;
         }
         /* DHCP_PADDING and DHCP_END have no [len] byte */
         if (scan_state->optionptr[OPT_CODE] == DHCP_PADDING) {
             scan_state->rem--;
             scan_state->optionptr++;
             continue;
         }
         if (scan_state->optionptr[OPT_CODE] == DHCP_END) {
             if ((scan_state->overload & FILE_FIELD101) == FILE_FIELD) {
                 /* can use packet->file, and didn't look at it yet */
                 scan_state->overload |= FILE_FIELD101; /* "we looked at it" */
                 scan_state->optionptr = packet->file;
                 scan_state->rem = sizeof(packet->file);
                 continue;
             }
             if ((scan_state->overload & SNAME_FIELD101) == SNAME_FIELD) {
                 /* can use packet->sname, and didn't look at it yet */
                 scan_state->overload |= SNAME_FIELD101; /* "we looked at it" */
                 scan_state->optionptr = packet->sname;
                 scan_state->rem = sizeof(packet->sname);
                 continue;
             }
             break;
         }
         if (scan_state->rem <= OPT_LEN) /* [len] byte exists? */
             goto complain; /* no, complain and return NULL */
         len = scan_state->optionptr[OPT_LEN];
         /* Skip options with zero length.
          * Users report that DHCP server on a TrendNet router (unknown model)
          * provides a zero-length option 12 (Host Name)
          * (this violates RFC 2132 section 3.14).
          */
         if (len == 0) {
             scan_state->rem -= 2;
             scan_state->optionptr += 2;
             continue;
         }
         len += 2;
         scan_state->rem -= len;
         if (scan_state->rem < 0) /* option is longer than options field? */
             goto complain; /* yes, complain and return NULL */
         if (scan_state->optionptr[OPT_CODE] == DHCP_OPTION_OVERLOAD) {
             /* len is known to be >= 3 now, [data] byte exists */
             scan_state->overload |= scan_state->optionptr[OPT_DATA];
         } else {
             uint8_t *return_ptr = scan_state->optionptr;
             scan_state->optionptr += len;
             return return_ptr;
         }
         scan_state->optionptr += len;
     }
     return NULL;
 }
References bb_simple_error_msg(), DHCP_END, DHCP_OPTION_OVERLOAD, DHCP_PADDING, dhcp_packet::file, FILE_FIELD, len, NULL, OPT_CODE, OPT_DATA, OPT_LEN, dhcp_scan_state::optionptr, dhcp_scan_state::overload, dhcp_scan_state::rem, dhcp_packet::sname, and SNAME_FIELD.
Referenced by fill_envp(), and udhcp_get_option().
udhcp_str2nip()
int FAST_FUNC udhcp_str2nip (const char * str, void * arg)
Definition at line 433 of file common.c.
 {
     len_and_sockaddr *lsa;
     lsa = host_and_af2sockaddr(str, 0, AF_INET);
     if (!lsa)
         return 0;
     /* arg maybe unaligned */
     move_to_unaligned32((uint32_t*)arg, lsa->u.sin.sin_addr.s_addr);
     free(lsa);
     return 1;
 }
References AF_INET, free, host_and_af2sockaddr, lsa, move_to_unaligned32, and str.
Referenced by read_staticlease(), and udhcp_str2optset().
udhcp_str2optset()
int FAST_FUNC udhcp_str2optset (const char * const_str, void * arg, const struct dhcp_optflag * optflags, const char * option_strings, bool dhcpv6)
Definition at line 558 of file common.c.
 {
     struct option_set **opt_list = arg;
     char *opt;
     char *str;
     const struct dhcp_optflag *optflag;
     struct dhcp_optflag userdef_optflag;
     unsigned optcode;
     int retval;
     /* IP_PAIR needs 8 bytes, STATIC_ROUTES needs 9 max */
     char buffer[9] ALIGNED(4);
     uint16_t *result_u16 = (uint16_t *) buffer;
     uint32_t *result_u32 = (uint32_t *) buffer;
     /* Cheat, the only *const* str possible is "" */
     str = (char *) const_str;
     opt = strtok_r(str, " \t=:", &str);
     if (!opt)
         return 0;
     optcode = bb_strtou(opt, NULL, 0);
     if (!errno && optcode < 255) {
         /* Raw (numeric) option code.
          * Initially assume binary (hex-str), but if "str" or 'str'
          * is seen later, switch to STRING.
          */
         userdef_optflag.flags = OPTION_BIN;
         userdef_optflag.code = optcode;
         optflag = &userdef_optflag;
     } else {
         optflag = &optflags[udhcp_option_idx(opt, option_strings)];
     }
     /* Loop to handle OPTION_LIST case, else execute just once */
     retval = 0;
     do {
         int length;
         char *val;
         if (optflag->flags == OPTION_BIN) {
             val = strtok_r(NULL, "", &str); /* do not split "'q w e'" */
             if (val) trim(val);
         } else
             val = strtok_r(NULL, ", \t", &str);
         if (!val)
             break;
         length = dhcp_option_lengths[optflag->flags & OPTION_TYPE_MASK];
         retval = 0;
         opt = buffer; /* new meaning for variable opt */
         switch (optflag->flags & OPTION_TYPE_MASK) {
         case OPTION_IP:
             retval = udhcp_str2nip(val, buffer);
             break;
         case OPTION_IP_PAIR:
             retval = udhcp_str2nip(val, buffer);
             val = strtok_r(NULL, ", \t/-", &str);
             if (!val)
                 retval = 0;
             if (retval)
                 retval = udhcp_str2nip(val, buffer + 4);
             break;
  case_OPTION_STRING:
         case OPTION_STRING:
         case OPTION_STRING_HOST:
 #if ENABLE_FEATURE_UDHCP_RFC3397
         case OPTION_DNS_STRING:
 #endif
             length = strnlen(val, 254);
             if (length > 0) {
                 opt = val;
                 retval = 1;
             }
             break;
 //      case OPTION_BOOLEAN: {
 //          static const char no_yes[] ALIGN1 = "no\0yes\0";
 //          buffer[0] = retval = index_in_strings(no_yes, val);
 //          retval++; /* 0 - bad; 1: "no" 2: "yes" */
 //          break;
 //      }
         case OPTION_U8:
             buffer[0] = bb_strtou32(val, NULL, 0);
             retval = (errno == 0);
             break;
         /* htonX are macros in older libc's, using temp var
          * in code below for safety */
         /* TODO: use bb_strtoX? */
         case OPTION_U16: {
             uint32_t tmp = bb_strtou32(val, NULL, 0);
             *result_u16 = htons(tmp);
             retval = (errno == 0 /*&& tmp < 0x10000*/);
             break;
         }
 //      case OPTION_S16: {
 //          long tmp = bb_strtoi32(val, NULL, 0);
 //          *result_u16 = htons(tmp);
 //          retval = (errno == 0);
 //          break;
 //      }
         case OPTION_U32: {
             uint32_t tmp = bb_strtou32(val, NULL, 0);
             *result_u32 = htonl(tmp);
             retval = (errno == 0);
             break;
         }
         case OPTION_S32: {
             int32_t tmp = bb_strtoi32(val, NULL, 0);
             *result_u32 = htonl(tmp);
             retval = (errno == 0);
             break;
         }
         case OPTION_STATIC_ROUTES: {
             /* Input: "a.b.c.d/m" */
             /* Output: mask(1 byte),pfx(0-4 bytes),gw(4 bytes) */
             unsigned mask;
             char *slash = strchr(val, '/');
             if (slash) {
                 *slash = '\0';
                 retval = udhcp_str2nip(val, buffer + 1);
                 buffer[0] = mask = bb_strtou(slash + 1, NULL, 10);
                 val = strtok_r(NULL, ", \t/-", &str);
                 if (!val || mask > 32 || errno)
                     retval = 0;
                 if (retval) {
                     length = ((mask + 7) >> 3) + 5;
                     retval = udhcp_str2nip(val, buffer + (length - 4));
                 }
             }
             break;
         }
         case OPTION_BIN:
             /* Raw (numeric) option code. Is it a string? */
             if (val[0] == '"' || val[0] == '\'') {
                 char delim = val[0];
                 char *end = last_char_is(val + 1, delim);
                 if (end) {
                     *end = '\0';
                     val++;
                     userdef_optflag.flags = OPTION_STRING;
                     goto case_OPTION_STRING;
                 }
             }
             /* No: hex-str option, handled in attach_option() */
             opt = val;
             retval = 1;
             break;
         default:
             break;
         }
         if (retval)
             attach_option(opt_list, optflag, opt, length, dhcpv6);
     } while (retval && (optflag->flags & OPTION_LIST));
     return retval;
 }
References ALIGNED(), attach_option, bb_strtoi32(), bb_strtou(), bb_strtou32(), buffer, dhcp_optflag::code, end, errno, dhcp_optflag::flags, htonl(), htons(), last_char_is(), NULL, opt, optflags, OPTION_BIN, OPTION_IP, OPTION_IP_PAIR, OPTION_LIST, OPTION_S32, OPTION_STATIC_ROUTES, OPTION_STRING, OPTION_STRING_HOST, OPTION_TYPE_MASK, OPTION_U16, OPTION_U32, OPTION_U8, retval, str, strchr(), strnlen(), strtok_r(), trim(), udhcp_option_idx(), udhcp_str2nip(), and val.
Variable Documentation
ALIGN1
const uint8_t dhcp_option_lengths [] ALIGN1
Initial value:
= {
    [OPTION_IP] =      4,
    [OPTION_IP_PAIR] = 8,
    [OPTION_STRING] =  1,
    [OPTION_STRING_HOST] = 1,
    [OPTION_U8] =      1,
    [OPTION_U16] =     2,
    [OPTION_U32] =     4,
    [OPTION_S32] =     4,
    [OPTION_STATIC_ROUTES] = 5,
    [OPTION_6RD] =    12,
}
Definition at line 157 of file common.c.
ALIGN2
const uint8_t MAC_BCAST_ADDR [6] ALIGN2
Initial value:
= {
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff
}
Definition at line 13 of file common.c.