Fennix: Userspace/musl/src/malloc/mallocng/free.c File Reference
free.c File Reference
#include <stdlib.h>
#include <sys/mman.h>
#include "meta.h"
Data Structures
struct mapinfo
Macros
#define _BSD_SOURCE
Functions
static struct mapinfo nontrivial_free (struct meta *, int)
static struct mapinfo free_group (struct meta *g)
static int okay_to_free (struct meta *g)
void free (void *p)
The standard function.
Data Structure Documentation
mapinfo
struct mapinfo
Definition at line 7 of file free.c.
Data Fields
void * base
size_t len
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file free.c.
Function Documentation
free_group()
static struct mapinfo free_group (struct meta * g) static
Definition at line 1 of file free.c.
 {
     struct mapinfo mi = { 0 };
     int sc = g->sizeclass;
     if (sc < 48) {
         ctx.usage_by_class[sc] -= g->last_idx+1;
     }
     if (g->maplen) {
         step_seq();
         record_seq(sc);
         mi.base = g->mem;
         mi.len = g->maplen*4096UL;
     } else {
         void *p = g->mem;
         struct meta *m = get_meta(p);
         int idx = get_slot_index(p);
         g->mem->meta = 0;
         // not checking size/reserved here; it's intentionally invalid
         mi = nontrivial_free(m, idx);
     }
     free_meta(g);
     return mi;
 }
nontrivial_free()
static struct mapinfo nontrivial_free (struct meta * g, int i) static
Definition at line 38 of file free.c.
 {
     uint32_t self = 1u<<i;
     int sc = g->sizeclass;
     uint32_t mask = g->freed_mask | g->avail_mask;
     if (mask+self == (2u<<g->last_idx)-1 && okay_to_free(g)) {
         // any multi-slot group is necessarily on an active list
         // here, but single-slot groups might or might not be.
         if (g->next) {
             assert(sc < 48);
             int activate_new = (ctx.active[sc]==g);
             dequeue(&ctx.active[sc], g);
             if (activate_new && ctx.active[sc])
                 activate_group(ctx.active[sc]);
         }
         return free_group(g);
     } else if (!mask) {
         assert(sc < 48);
         // might still be active if there were no allocations
         // after last available slot was taken.
         if (ctx.active[sc] != g) {
             queue(&ctx.active[sc], g);
         }
     }
     a_or(&g->freed_mask, self);
     return (struct mapinfo){ 0 };
 }
References cnt, g, get_stride(), is_bouncing(), size_classes, UNIT, and usage().
Referenced by free().
okay_to_free()
static int okay_to_free (struct meta * g) static
Definition at line 38 of file free.c.
 {
     int sc = g->sizeclass;
     if (!g->freeable) return 0;
     // always free individual mmaps not suitable for reuse
     if (sc >= 48 || get_stride(g) < UNIT*size_classes[sc])
         return 1;
     // always free groups allocated inside another group's slot
     // since recreating them should not be expensive and they
     // might be blocking freeing of a much larger group.
     if (!g->maplen) return 1;
     // if there is another non-full group, free this one to
     // consolidate future allocations, reduce fragmentation.
     if (g->next != g) return 1;
     // free any group in a size class that's not bouncing
     if (!is_bouncing(sc)) return 1;
     size_t cnt = g->last_idx+1;
     size_t usage = ctx.usage_by_class[sc];
     // if usage is high enough that a larger count should be
     // used, free the low-count group so a new one will be made.
     if (9*cnt <= usage && cnt < 20)
         return 1;
     // otherwise, keep the last group in a bouncing class.
     return 0;
 }