Fennix Userspace: Userspace/mlibc/options/posix/generic/sys-stat-stubs.cpp File Reference
sys-stat-stubs.cpp File Reference
#include <errno.h>
#include <bits/ensure.h>
#include <sys/stat.h>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
Functions
int chmod (const char *pathname, mode_t mode)
int fchmod (int fd, mode_t mode)
int fchmodat (int dirfd, const char *pathname, mode_t mode, int flags)
int fstatat (int dirfd, const char *path, struct stat *result, int flags)
int futimens (int fd, const struct timespec times[2])
int mkdir (const char *path, mode_t mode)
int mkdirat (int dirfd, const char *path, mode_t mode)
int mkfifo (const char *path, mode_t mode)
int mkfifoat (int dirfd, const char *path, mode_t mode)
int mknod (const char *path, mode_t mode, dev_t dev)
int mknodat (int dirfd, const char *path, mode_t mode, dev_t dev)
mode_t umask (mode_t mode)
int utimensat (int dirfd, const char *pathname, const struct timespec times[2], int flags)
int stat (const char *path, struct stat *result)
int lstat (const char *path, struct stat *result)
int fstat (int fd, struct stat *result)
Function Documentation
chmod()
int chmod (const char * pathname, mode_t mode)
Definition at line 9 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_chmod, -1);
     if(int e = mlibc::sys_chmod(pathname, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_chmod().
fchmod()
int fchmod (int fd, mode_t mode)
Definition at line 18 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchmod, -1);
     if(int e = mlibc::sys_fchmod(fd, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fchmod().
fchmodat()
int fchmodat (int dirfd, const char * pathname, mode_t mode, int flags)
Definition at line 27 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fchmodat, -1);
     if(int e = mlibc::sys_fchmodat(dirfd, pathname, mode, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd(), errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_fchmodat().
fstat()
int fstat (int fd, struct stat * result)
Definition at line 147 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_stat, -1);
     if(int e = mlibc::sys_stat(mlibc::fsfd_target::fd, fd, "", 0, result); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::fd, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_stat().
Referenced by fdopendir(), and getspnam_r().
fstatat()
int fstatat (int dirfd, const char * path, struct stat * result, int flags)
Definition at line 36 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_stat, -1);
     if(int e = mlibc::sys_stat(mlibc::fsfd_target::fd_path, dirfd, path, flags, result); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd(), errno, mlibc::fd_path, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_stat().
futimens()
int futimens (int fd, const struct timespec times[2])
Definition at line 45 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_utimensat, -1);
     if (int e = mlibc::sys_utimensat(fd, nullptr, times, 0); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_utimensat(), and times().
lstat()
int lstat (const char * path, struct stat * result)
Definition at line 137 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_stat, -1);
     if(int e = mlibc::sys_stat(mlibc::fsfd_target::path,
             -1, path, AT_SYMLINK_NOFOLLOW, result); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References AT_SYMLINK_NOFOLLOW, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::path, and mlibc::sys_stat().
Referenced by do_glob().
mkdir()
int mkdir (const char * path, mode_t mode)
Definition at line 56 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mkdir, -1);
     if(int e = mlibc::sys_mkdir(path, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mkdir().
Referenced by M_MakeDirectory(), and prepare().
mkdirat()
int mkdirat (int dirfd, const char * path, mode_t mode)
Definition at line 65 of file sys-stat-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31mmlibc: mkdirat() ignores its mode\e[39m" << frg::endlog;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mkdirat, -1);
     if(int e = mlibc::sys_mkdirat(dirfd, path, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd(), errno, mlibc::infoLogger, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mkdirat().
mkfifo()
int mkfifo (const char * path, mode_t mode)
Definition at line 75 of file sys-stat-stubs.cpp.
{
     return mkfifoat(AT_FDCWD, path, mode);
 }
References AT_FDCWD, and mkfifoat().
mkfifoat()
int mkfifoat (int dirfd, const char * path, mode_t mode)
Definition at line 79 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mkfifoat, -1);
     if (int e = mlibc::sys_mkfifoat(dirfd, path, mode); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd(), errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mkfifoat().
Referenced by mkfifo().
mknod()
int mknod (const char * path, mode_t mode, dev_t dev)
Definition at line 89 of file sys-stat-stubs.cpp.
{
     return mknodat(AT_FDCWD, path, mode, dev);
 }
References AT_FDCWD, and mknodat().
mknodat()
int mknodat (int dirfd, const char * path, mode_t mode, dev_t dev)
Definition at line 93 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mknodat, -1);
     if (int e = mlibc::sys_mknodat(dirfd, path, mode, dev); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd(), errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mknodat().
Referenced by mknod().
stat()
int stat (const char * path, struct stat * result)
Definition at line 128 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_stat, -1);
     if(int e = mlibc::sys_stat(mlibc::fsfd_target::path, -1, path, 0, result); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::path, and mlibc::sys_stat().
Referenced by do_glob().
umask()
mode_t umask (mode_t mode)
Definition at line 103 of file sys-stat-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_umask, -1);
     mode_t old;
     if (int e = mlibc::sys_umask(mode, &old); e) {
         errno = e;
         return -1;
     }
     return old;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_umask().
utimensat()
int utimensat (int dirfd, const char * pathname, const struct timespec times[2], int flags)
Definition at line 113 of file sys-stat-stubs.cpp.
{
     if(pathname == nullptr) {
         errno = EINVAL;
         return -1;
     }
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_utimensat, -1);
     if (int e = mlibc::sys_utimensat(dirfd, pathname, times, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References dirfd(), EINVAL, errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_utimensat(), and times().