Fennix Kernel: Kernel/core/interrupts_manager.cpp File Reference
interrupts_manager.cpp File Reference
#include <ints.hpp>
#include <syscalls.hpp>
#include <acpi.hpp>
#include <smp.hpp>
#include <vector>
#include <io.h>
#include "../kernel.h"
Data Structures
struct Interrupts::Event
Namespaces
Interrupts
Macros
#define SORT_DIVIDER 1
#define SORT_START 10000
Functions
void HandleException (CPU::ExceptionFrame *Frame)
nsa void ExceptionHandler (void *Frame)
void Interrupts::Initialize (int Core)
void Interrupts::Enable (int Core)
void Interrupts::InitializeTimer (int Core)
nsa void Interrupts::RemoveAll ()
void Interrupts::AddHandler (void(*Callback)(CPU::TrapFrame *), int InterruptNumber, void *ctx, bool Critical)
void Interrupts::RemoveHandler (void(*Callback)(CPU::TrapFrame *), int InterruptNumber)
void Interrupts::RemoveHandler (void(*Callback)(CPU::TrapFrame *))
void Interrupts::RemoveHandler (int InterruptNumber)
nsa void Interrupts::ReturnFromInterrupt ()
nsa void Interrupts::MainInterruptHandler (void *Data)
nsa void Interrupts::SchedulerInterruptHandler (void *Data)
Variables
std::list< Event > Interrupts::RegisteredEvents
std::atomic_uint Interrupts::SortEvents = SORT_START / SORT_DIVIDER
constexpr uint32_t Interrupts::SORT_ITR = (SORT_START * 100) / SORT_DIVIDER
Macro Definition Documentation
SORT_DIVIDER
#define SORT_DIVIDER 1
Definition at line 102 of file interrupts_manager.cpp.
SORT_START
#define SORT_START 10000
Definition at line 105 of file interrupts_manager.cpp.
Function Documentation
ExceptionHandler()
nsa void ExceptionHandler (void * Frame)
Definition at line 41 of file interrupts_manager.cpp.
 {
     HandleException((CPU::ExceptionFrame *)Frame);
 }
References HandleException().
HandleException()
void HandleException (CPU::ExceptionFrame * Frame)
Definition at line 281 of file handler.cpp.
 {
     /* We don't need to restore the page table
         because the ExceptionHandlerStub will
         do it for us if we return. */
     CPU::PageTable(KernelPageTable);
     InitFont();
     /* First check the exception */
     if (unlikely(Frame->InterruptNumber == CPU::x86::DoubleFault))
     {
         ExceptionLock.store(true, std::memory_order_release);
         HandleUnrecoverableException(Frame);
     }
     if (Frame->cs == GDT_USER_CODE && Frame->ss == GDT_USER_DATA)
     {
         if (UserModeExceptionHandler(Frame))
             goto ExceptionExit;
         CPUData *core = GetCurrentCPU();
         if (likely(core->CurrentThread->Security.IsCritical == false))
             TaskManager->Yield();
         error("Critical thread \"%s\"(%d) died",
               core->CurrentThread->Name,
               core->CurrentThread->ID);
     }
     debug("-----------------------------------------------------------------------------------");
     error("Exception: %#x", Frame->InterruptNumber);
     debug("%ld MiB / %ld MiB (%ld MiB Reserved)",
           TO_MiB(KernelAllocator.GetUsedMemory()),
           TO_MiB(KernelAllocator.GetTotalMemory()),
           TO_MiB(KernelAllocator.GetReservedMemory()));
     if (ExceptionLock.load(std::memory_order_acquire))
         HandleExceptionInsideException(Frame);
     ExceptionLock.store(true, std::memory_order_release);
     {
         const char msg[] = "Entering in panic mode...";
         size_t msgLen = strlen(msg);
         size_t msgPixels = msgLen * CrashFontRenderer.CurrentFont->GetInfo().Width;
         uint32_t x = uint32_t((Display->GetWidth - msgPixels) / 2);
         uint32_t y = uint32_t((Display->GetHeight - CrashFontRenderer.CurrentFont->GetInfo().Height) / 2);
         x /= CrashFontRenderer.CurrentFont->GetInfo().Width;
         y /= CrashFontRenderer.CurrentFont->GetInfo().Height;
         printf("\x1b[2J\x1b[%d;%dH", y, x);
         printf("\x1b[30;41m%s\x1b[0m\x1b[H", msg);
     }
     if (DriverManager)
         DriverManager->Panic();
     if (TaskManager)
         TaskManager->Panic();
     Interrupts::RemoveAll();
     HaltAllCores();
     ForceUnlock = true;
     DisplayCrashScreen(Frame);
     CPU::Stop();
 ExceptionExit:
     ExceptionLock.store(false, std::memory_order_release);
 }
References CrashFontRenderer, KernelConsole::FontRenderer::CurrentFont, CPUData::CurrentThread, debug, Display, DisplayCrashScreen(), CPU::x86::DoubleFault, DriverManager, error, ExceptionLock, ForceUnlock, GDT_USER_CODE, GDT_USER_DATA, GetCurrentCPU(), Video::Display::GetHeight, Video::Font::GetInfo(), Video::Display::GetWidth, HaltAllCores(), HandleExceptionInsideException(), HandleUnrecoverableException(), Video::FontInfo::Height, InitFont(), KernelAllocator, KernelPageTable, likely, memory_order_acquire, memory_order_release, CPU::PageTable(), Driver::Manager::Panic(), Tasking::Task::Panic(), printf, Interrupts::RemoveAll(), CPU::Stop(), strlen(), TaskManager, TO_MiB, unlikely, UserModeExceptionHandler(), Video::FontInfo::Width, and Tasking::Task::Yield().
Referenced by ExceptionHandler().