Fennix: Userspace/libc/src/Runtime.c File Reference
Runtime.c File Reference
#include <sys/syscalls.h>
#include <sys/types.h>
Functions
void __libc_init_array (void)
void __libc_fini_array (void)
void __libc_init_std (void)
void __libc_fini_std (void)
PUBLIC void __libc_init (void)
PUBLIC void _exit (int Code)
Function Documentation
__libc_fini_array()
void __libc_fini_array (void)
Definition at line 18 of file InitArray.c.
 {
     for (fct *func = __fini_array_start; func != __fini_array_end; func++)
         (*func)();
 }
References __fini_array_end, and __fini_array_start.
Referenced by _exit().
__libc_fini_std()
void __libc_fini_std (void)
Definition at line 11 of file std_init.c.
 {
 }
Referenced by _exit().
__libc_init()
PUBLIC void __libc_init (void)
Definition at line 10 of file Runtime.c.
 {
     __libc_init_array();
     __libc_init_std();
 }
References __libc_init_array(), and __libc_init_std().
__libc_init_array()
void __libc_init_array (void)
Definition at line 12 of file InitArray.c.
 {
     for (fct *func = __init_array_start; func != __init_array_end; func++)
         (*func)();
 }
References __init_array_end, and __init_array_start.
Referenced by __libc_init().
__libc_init_std()
void __libc_init_std (void)
Definition at line 5 of file std_init.c.
 {
     /* FIXME: Temporal workaround */
     // int IsCritical = syscall1(_KernelCTL, 6 /* KCTL_IS_CRITICAL */);
 }
Referenced by __libc_init().
_exit()
PUBLIC void _exit (int Code)
Definition at line 16 of file Runtime.c.
 {
     __libc_fini_std();
     __libc_fini_array();
     syscall1(_Exit, (long)Code);
     while (1)
         ;
 }
References __libc_fini_array(), __libc_fini_std(), _Exit, and syscall1().