Fennix Userspace: Userspace/libc/include/ctype.h File Reference
ctype.h File Reference
Functions
int tolower (int c)
int toupper (int c)
int isspace (int c)
Function Documentation
isspace()
int isspace (int c)
Definition at line 24 of file ctype.c.
 {
     return c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\f' || c == '\v';
 }
References c.
Referenced by do_scanf(), mlibc::get_nameserver(), GetGameName(), mlibc::char_detail< char >::isSpace(), isspace_l(), LoadResponseFile(), mlibc::lookup_addr_hosts(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), mlibc::lookup_serv_file_port(), SplitLine(), anonymous_namespace{time.cpp}::strptime_internal(), and strtoxmax().
tolower()
int tolower (int c)
Definition at line 3 of file ctype.c.
 {
     if (c >= 'A' && c <= 'Z')
     {
         c -= 'A';
         c += 'a';
     }
     return c;
 }
References c.
toupper()
int toupper (int c)
Definition at line 14 of file ctype.c.
 {
     if (c >= 'a' && c <= 'z')
     {
         c -= 'a';
         c += 'A';
     }
     return c;
 }
References c.