Fennix Lynx Bootloader: Memory64::PageDirectoryEntry Union Reference
Memory64::PageDirectoryEntry Union Reference
#include <memory.hpp>
Public Member Functions
void SetAddress (uintptr_t _Address)
Set PageTableEntryPtr address.
uintptr_t GetAddress ()
Get PageTableEntryPtr address.
Data Fields
struct {
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
uint64_t CacheDisable: 1
uint64_t Accessed: 1
uint64_t Available0: 1
uint64_t PageSize: 1
uint64_t Available1: 4
uint64_t Address: 40
uint64_t Available2: 11
uint64_t ExecuteDisable: 1
};
struct {
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
uint64_t CacheDisable: 1
uint64_t Accessed: 1
uint64_t Dirty: 1
uint64_t PageSize: 1
uint64_t Global: 1
uint64_t Available0: 3
uint64_t PageAttributeTable: 1
uint64_t Reserved0: 8
uint64_t Address: 31
uint64_t Available1: 7
uint64_t ProtectionKey: 4
uint64_t ExecuteDisable: 1
} TwoMB
uint64_t raw
Detailed Description
Definition at line 281 of file memory.hpp.
Member Function Documentation
GetAddress()
uintptr_t Memory64::PageDirectoryEntry::GetAddress () inline
Get PageTableEntryPtr address.
Definition at line 330 of file memory.hpp.
         {
             return (this->raw & 0x000FFFFFFFFFF000) >> 12;
         }
Referenced by Memory64::Virtual::Check(), Memory64::Virtual::GetPhysical(), Memory64::Virtual::Map(), and Memory64::Virtual::Unmap().
SetAddress()
void Memory64::PageDirectoryEntry::SetAddress (uintptr_t _Address) inline
Set PageTableEntryPtr address.
Definition at line 322 of file memory.hpp.
         {
             _Address &= 0x000000FFFFFFFFFF;
             this->raw &= 0xFFF0000000000FFF;
             this->raw |= (_Address << 12);
         }
Referenced by Memory64::Virtual::Map().
Field Documentation
struct { ... }
raw
uint64_t Memory64::PageDirectoryEntry::raw
Definition at line 319 of file memory.hpp.
Referenced by Memory64::Virtual::Map().
struct { ... } Memory64::PageDirectoryEntry::TwoMB
The documentation for this union was generated from the following file:
Lynx/FennixLoader/include/memory.hpp