Fennix Userspace: mlibc::abstract_file Struct Reference
mlibc::abstract_file Struct Reference abstract
#include <file-io.hpp>
Public Member Functions
abstract_file (void(*do_dispose)(abstract_file *)=nullptr)
abstract_file (const abstract_file &)=delete
abstract_file & operator= (const abstract_file &)=delete
virtual ~abstract_file ()
void dispose ()
virtual int close ()=0
int read (char *buffer, size_t max_size, size_t *actual_size)
int write (const char *buffer, size_t max_size, size_t *actual_size)
int unget (char c)
int update_bufmode (buffer_mode mode)
void purge ()
int flush ()
int tell (off_t *current_offset)
int seek (off_t offset, int whence)
Data Fields
RecursiveFutexLock _lock
frg::default_list_hook< abstract_file > _list_hook
Data Fields inherited from __mlibc_file_base
char * __buffer_ptr
size_t __buffer_size
size_t __offset
size_t __io_offset
size_t __valid_limit
size_t __dirty_begin
size_t __dirty_end
char * __unget_ptr
int __io_mode
int __status_bits
Protected Member Functions
virtual int determine_type (stream_type *type)=0
virtual int determine_bufmode (buffer_mode *mode)=0
virtual int io_read (char *buffer, size_t max_size, size_t *actual_size)=0
virtual int io_write (const char *buffer, size_t max_size, size_t *actual_size)=0
virtual int io_seek (off_t offset, int whence, off_t *new_offset)=0
Private Member Functions
int _init_type ()
int _init_bufmode ()
int _write_back ()
int _save_pos ()
int _reset ()
void _ensure_allocation ()
Private Attributes
stream_type _type
buffer_mode _bufmode
void(* _do_dispose)(abstract_file *)
Detailed Description
Definition at line 25 of file file-io.hpp.
Constructor & Destructor Documentation
abstract_file() [1/2]
mlibc::abstract_file::abstract_file (void(*)(abstract_file *) do_dispose = nullptr)
Definition at line 58 of file file-io.cpp.
 : _type{stream_type::unknown}, _bufmode{buffer_mode::unknown}, _do_dispose{do_dispose} {
     // TODO: For __fwriting to work correctly, set the __io_mode to 1 if the write is write-only.
     __buffer_ptr = nullptr;
     __unget_ptr = nullptr;
     __buffer_size = 4096;
     __offset = 0;
     __io_offset = 0;
     __valid_limit = 0;
     __dirty_begin = 0;
     __dirty_end = 0;
     __io_mode = 0;
     __status_bits = 0;
     global_file_list().push_back(this);
 }
References __mlibc_file_base::__buffer_ptr, __mlibc_file_base::__buffer_size, __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, __mlibc_file_base::__io_mode, __mlibc_file_base::__io_offset, __mlibc_file_base::__offset, __mlibc_file_base::__status_bits, __mlibc_file_base::__unget_ptr, __mlibc_file_base::__valid_limit, mlibc::anonymous_namespace{file-io.cpp}::global_file_list(), and mlibc::unknown.
abstract_file() [2/2]
mlibc::abstract_file::abstract_file (const abstract_file &) delete
~abstract_file()
mlibc::abstract_file::~abstract_file () virtual
Definition at line 75 of file file-io.cpp.
{
     if(__dirty_begin != __dirty_end)
         mlibc::infoLogger() << "mlibc warning: File is not flushed before destruction"
                 << frg::endlog;
     if(__buffer_ptr)
         getAllocator().free(__buffer_ptr - ungetBufferSize);
     auto it = global_file_list().iterator_to(this);
     global_file_list().erase(it);
 }
References __mlibc_file_base::__buffer_ptr, __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, getAllocator(), mlibc::anonymous_namespace{file-io.cpp}::global_file_list(), mlibc::infoLogger, and mlibc::anonymous_namespace{file-io.cpp}::ungetBufferSize.
Member Function Documentation
_ensure_allocation()
void mlibc::abstract_file::_ensure_allocation () private
Definition at line 418 of file file-io.cpp.
{
     if(__buffer_ptr)
         return;
     auto ptr = getAllocator().allocate(__buffer_size + ungetBufferSize);
     __buffer_ptr = reinterpret_cast<char *>(ptr) + ungetBufferSize;
     __unget_ptr = __buffer_ptr;
 }
References __mlibc_file_base::__buffer_ptr, __mlibc_file_base::__buffer_size, __mlibc_file_base::__unget_ptr, getAllocator(), and mlibc::anonymous_namespace{file-io.cpp}::ungetBufferSize.
Referenced by read(), unget(), and write().
_init_bufmode()
int mlibc::abstract_file::_init_bufmode () private
Definition at line 336 of file file-io.cpp.
{
     if(_bufmode != buffer_mode::unknown)
         return 0;
     if(determine_bufmode(&_bufmode))
         return -1;
     __ensure(_bufmode != buffer_mode::unknown);
     return 0;
 }
References __ensure, _bufmode, determine_bufmode(), and mlibc::unknown.
Referenced by read(), and write().
_init_type()
int mlibc::abstract_file::_init_type () private
Definition at line 326 of file file-io.cpp.
{
     if(_type != stream_type::unknown)
         return 0;
     if(int e = determine_type(&_type); e)
         return e;
     __ensure(_type != stream_type::unknown);
     return 0;
 }
References __ensure, _type, determine_type(), and mlibc::unknown.
Referenced by _reset(), _save_pos(), and _write_back().
_reset()
int mlibc::abstract_file::_reset () private
Definition at line 400 of file file-io.cpp.
{
     if(int e = _init_type(); e)
         return e;
     // For pipe-like files, we must not forget already read data.
     // TODO: Report this error to the user.
     if(_type == stream_type::pipe_like)
         __ensure(__offset == __valid_limit);
     __ensure(__dirty_begin == __dirty_end);
     __offset = 0;
     __io_offset = 0;
     __valid_limit = 0;
     return 0;
 }
References __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, __ensure, __mlibc_file_base::__io_offset, __mlibc_file_base::__offset, __mlibc_file_base::__valid_limit, _init_type(), _type, and mlibc::pipe_like.
Referenced by read(), and write().
_save_pos()
int mlibc::abstract_file::_save_pos () private
Definition at line 383 of file file-io.cpp.
{
     if (int e = _init_type(); e)
         return e;
     if (_type == stream_type::file_like) {
         off_t new_offset;
         auto seek_offset = (off_t(__offset) - off_t(__io_offset));
         if (int e = io_seek(seek_offset, SEEK_CUR, &new_offset); e) {
             __status_bits |= __MLIBC_ERROR_BIT;
             mlibc::infoLogger() << "hit io_seek() error " << e << frg::endlog;
             return e;
         }
         return 0;
     }
     return 0; // nothing to do for the rest
 }
References __mlibc_file_base::__io_offset, __MLIBC_ERROR_BIT, __mlibc_file_base::__offset, __mlibc_file_base::__status_bits, _init_type(), _type, mlibc::file_like, mlibc::infoLogger, io_seek(), mlibc::new_offset, and SEEK_CUR.
Referenced by flush().
_write_back()
int mlibc::abstract_file::_write_back () private
Definition at line 346 of file file-io.cpp.
{
     if(int e = _init_type(); e)
         return e;
     if(__dirty_begin == __dirty_end)
         return 0;
     // For non-pipe streams, first do a seek to reset the
     // I/O position to zero, then do a write().
     if(_type == stream_type::file_like) {
         if(__io_offset != __dirty_begin) {
             __ensure(__dirty_begin - __io_offset > 0);
             off_t new_offset;
             if(int e = io_seek(off_t(__dirty_begin) - off_t(__io_offset), SEEK_CUR, &new_offset); e)
                 return e;
             __io_offset = __dirty_begin;
         }
     }else{
         __ensure(_type == stream_type::pipe_like);
         __ensure(__io_offset == __dirty_begin);
     }
     // Now, we are in the correct position to write-back everything.
     while(__io_offset < __dirty_end) {
         size_t io_size;
         if(int e = io_write(__buffer_ptr + __io_offset, __dirty_end - __io_offset, &io_size); e) {
             __status_bits |= __MLIBC_ERROR_BIT;
             return e;
         }
         __ensure(io_size > 0 && "io_write() is expected to always write at least one byte");
         __io_offset += io_size;
         __dirty_begin += io_size;
     }
     return 0;
 }
References __mlibc_file_base::__buffer_ptr, __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, __ensure, __mlibc_file_base::__io_offset, __MLIBC_ERROR_BIT, __mlibc_file_base::__status_bits, _init_type(), _type, mlibc::file_like, io_seek(), io_write(), mlibc::new_offset, mlibc::pipe_like, and SEEK_CUR.
Referenced by flush(), read(), seek(), and write().
close()
virtual int mlibc::abstract_file::close () pure virtual
Implemented in mlibc::mem_file, and mlibc::fd_file.
determine_bufmode()
virtual int mlibc::abstract_file::determine_bufmode (buffer_mode * mode) protected pure virtual
Implemented in mlibc::mem_file, and mlibc::fd_file.
Referenced by _init_bufmode().
determine_type()
virtual int mlibc::abstract_file::determine_type (stream_type * type) protected pure virtual
Implemented in mlibc::mem_file, and mlibc::fd_file.
Referenced by _init_type().
dispose()
void mlibc::abstract_file::dispose ()
Definition at line 87 of file file-io.cpp.
{
     if(!_do_dispose)
         return;
     _do_dispose(this);
 }
References _do_dispose.
flush()
int mlibc::abstract_file::flush ()
Definition at line 279 of file file-io.cpp.
{
     if (__dirty_end != __dirty_begin) {
         if (int e = _write_back(); e)
             return e;
     }
     if (int e = _save_pos(); e)
         return e;
     purge();
     return 0;
 }
References __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, _save_pos(), _write_back(), and purge().
io_read()
virtual int mlibc::abstract_file::io_read (char * buffer, size_t max_size, size_t * actual_size) protected pure virtual
Implemented in mlibc::mem_file, and mlibc::fd_file.
Referenced by read().
io_seek()
virtual int mlibc::abstract_file::io_seek (off_t offset, int whence, off_t * new_offset) protected pure virtual
Implemented in mlibc::mem_file, and mlibc::fd_file.
Referenced by _save_pos(), _write_back(), seek(), and tell().
io_write()
virtual int mlibc::abstract_file::io_write (const char * buffer, size_t max_size, size_t * actual_size) protected pure virtual
Implemented in mlibc::mem_file, and mlibc::fd_file.
Referenced by _write_back(), and write().
operator=()
abstract_file& mlibc::abstract_file::operator= (const abstract_file &) delete
purge()
void mlibc::abstract_file::purge ()
Definition at line 271 of file file-io.cpp.
{
     __offset = 0;
     __io_offset = 0;
     __valid_limit = 0;
     __dirty_end = __dirty_begin;
     __unget_ptr = __buffer_ptr;
 }
References __mlibc_file_base::__buffer_ptr, __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, __mlibc_file_base::__io_offset, __mlibc_file_base::__offset, __mlibc_file_base::__unget_ptr, and __mlibc_file_base::__valid_limit.
Referenced by flush(), and seek().
read()
int mlibc::abstract_file::read (char * buffer, size_t max_size, size_t * actual_size)
Definition at line 97 of file file-io.cpp.
{
     __ensure(max_size);
     if(_init_bufmode())
         return -1;
     size_t unget_length = 0;
     if (__unget_ptr != __buffer_ptr) {
         unget_length = frg::min(max_size, (size_t)(__buffer_ptr - __unget_ptr));
         memcpy(buffer, __unget_ptr, unget_length);
         __unget_ptr += unget_length;
         buffer += unget_length;
         max_size -= unget_length;
         if (max_size == 0) {
             *actual_size = unget_length;
             return 0;
         }
     }
     if(globallyDisableBuffering || _bufmode == buffer_mode::no_buffer) {
         size_t io_size;
         if(int e = io_read(buffer, max_size, &io_size); e) {
             __status_bits |= __MLIBC_ERROR_BIT;
             return e;
         }
         if(!io_size)
             __status_bits |= __MLIBC_EOF_BIT;
         *actual_size = io_size + unget_length;
         return 0;
     }
     // Ensure correct buffer type for pipe-like streams.
     // TODO: In order to support pipe-like streams we need to write-back the buffer.
     if(__io_mode && __valid_limit)
         mlibc::panicLogger() << "mlibc: Cannot read-write to same pipe-like stream"
                 << frg::endlog;
     __io_mode = 0;
     // Clear the buffer, then buffer new data.
     if(__offset == __valid_limit) {
         // TODO: We only have to write-back/reset if __valid_limit reaches the buffer end.
         if(int e = _write_back(); e)
             return e;
         if(int e = _reset(); e)
             return e;
         // Perform a read-ahead.
         _ensure_allocation();
         size_t io_size;
         if(int e = io_read(__buffer_ptr, __buffer_size, &io_size); e) {
             __status_bits |= __MLIBC_ERROR_BIT;
             return e;
         }
         if(!io_size) {
             __status_bits |= __MLIBC_EOF_BIT;
             *actual_size = 0;
             return 0;
         }
         __io_offset = io_size;
         __valid_limit = io_size;
     }
     // Return data from the buffer.
     __ensure(__offset < __valid_limit);
     auto chunk = frg::min(size_t(__valid_limit - __offset), max_size);
     memcpy(buffer, __buffer_ptr + __offset, chunk);
     __offset += chunk;
     *actual_size = chunk + unget_length;
     return 0;
 }
References __mlibc_file_base::__buffer_ptr, __mlibc_file_base::__buffer_size, __ensure, __mlibc_file_base::__io_mode, __mlibc_file_base::__io_offset, __MLIBC_EOF_BIT, __MLIBC_ERROR_BIT, __mlibc_file_base::__offset, __mlibc_file_base::__status_bits, __mlibc_file_base::__unget_ptr, __mlibc_file_base::__valid_limit, _bufmode, _ensure_allocation(), _init_bufmode(), _reset(), _write_back(), mlibc::anonymous_namespace{file-io.cpp}::globallyDisableBuffering, io_read(), max_size, memcpy(), mlibc::no_buffer, and mlibc::panicLogger.
seek()
int mlibc::abstract_file::seek (off_t offset, int whence)
Definition at line 300 of file file-io.cpp.
{
     if(int e = _write_back(); e)
         return e;
     off_t new_offset;
     if(whence == SEEK_CUR) {
         auto seek_offset = offset + (off_t(__offset) - off_t(__io_offset));
         if(int e = io_seek(seek_offset, whence, &new_offset); e) {
             __status_bits |= __MLIBC_ERROR_BIT;
             return e;
         }
     }else{
         __ensure(whence == SEEK_SET || whence == SEEK_END);
         if(int e = io_seek(offset, whence, &new_offset); e) {
             __status_bits |= __MLIBC_ERROR_BIT;
             return e;
         }
     }
     // We just forget the current buffer.
     // TODO: If the seek is "small", we can just modify our internal offset.
     purge();
     return 0;
 }
References __ensure, __mlibc_file_base::__io_offset, __MLIBC_ERROR_BIT, __mlibc_file_base::__offset, __mlibc_file_base::__status_bits, _write_back(), io_seek(), mlibc::new_offset, mlibc::offset, purge(), SEEK_CUR, SEEK_END, SEEK_SET, and mlibc::whence.
tell()
int mlibc::abstract_file::tell (off_t * current_offset)
Definition at line 291 of file file-io.cpp.
{
     off_t seek_offset;
     if(int e = io_seek(0, SEEK_CUR, &seek_offset); e)
         return e;
     *current_offset = seek_offset + (off_t(__offset) - off_t(__io_offset));
     return 0;
 }
References __mlibc_file_base::__io_offset, __mlibc_file_base::__offset, io_seek(), and SEEK_CUR.
unget()
int mlibc::abstract_file::unget (char c)
Definition at line 246 of file file-io.cpp.
{
     if (!__unget_ptr) {
         // This can happen if the file is unbuffered, but we still need
         // a space to store ungetc'd data.
         __ensure(!__buffer_ptr);
         _ensure_allocation();
         __ensure(__unget_ptr);
     }
     if ((size_t)(__buffer_ptr - __unget_ptr) + 1 > ungetBufferSize)
         return EOF;
     else {
         *(--__unget_ptr) = c;
         return c;
     }
 }
References __mlibc_file_base::__buffer_ptr, __ensure, __mlibc_file_base::__unget_ptr, _ensure_allocation(), c, EOF, and mlibc::anonymous_namespace{file-io.cpp}::ungetBufferSize.
update_bufmode()
int mlibc::abstract_file::update_bufmode (buffer_mode mode)
Definition at line 263 of file file-io.cpp.
{
     // setvbuf() has undefined behavior if I/O has been performed.
     __ensure(__dirty_begin == __dirty_end
             && "update_bufmode() must only be called before performing I/O");
     _bufmode = mode;
     return 0;
 }
References __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, __ensure, and _bufmode.
write()
int mlibc::abstract_file::write (const char * buffer, size_t max_size, size_t * actual_size)
Definition at line 173 of file file-io.cpp.
{
     __ensure(max_size);
     if(_init_bufmode())
         return -1;
     if(globallyDisableBuffering || _bufmode == buffer_mode::no_buffer) {
         // As we do not buffer, nothing can be dirty.
         __ensure(__dirty_begin == __dirty_end);
         size_t io_size;
         if(int e = io_write(buffer, max_size, &io_size); e) {
             __status_bits |= __MLIBC_ERROR_BIT;
             return e;
         }
         __ensure(io_size > 0 && "io_write() is expected to always write at least one byte");
         *actual_size = io_size;
         return 0;
     }
     // Flush the buffer if necessary.
     if(__offset == __buffer_size) {
         if(int e = _write_back(); e)
             return e;
         if(int e = _reset(); e)
             return e;
     }
     // Ensure correct buffer type for pipe-like streams.
     // TODO: We could full support pipe-like files
     // by ungetc()ing all data before a write happens,
     // however, for now we just report an error.
     if(!__io_mode && __valid_limit) // TODO: Only check this for pipe-like streams.
         mlibc::panicLogger() << "mlibc: Cannot read-write to same pipe-like stream"
                 << frg::endlog;
     __io_mode = 1;
     __ensure(__offset < __buffer_size);
     auto chunk = frg::min(__buffer_size - __offset, max_size);
     // Line-buffered streams perform I/O on full lines.
     bool flush_line = false;
     if(_bufmode == buffer_mode::line_buffer) {
         auto nl = reinterpret_cast<char *>(memchr(buffer, '\n', chunk));
         if(nl) {
             chunk = nl + 1 - buffer;
             flush_line = true;
         }
     }
     __ensure(chunk);
     // Buffer data (without necessarily performing I/O).
     _ensure_allocation();
     memcpy(__buffer_ptr + __offset, buffer, chunk);
     if(__dirty_begin != __dirty_end) {
         __dirty_begin = frg::min(__dirty_begin, __offset);
         __dirty_end = frg::max(__dirty_end, __offset + chunk);
     }else{
         __dirty_begin = __offset;
         __dirty_end = __offset + chunk;
     }
     __valid_limit = frg::max(__offset + chunk, __valid_limit);
     __offset += chunk;
     // Flush line-buffered streams.
     if(flush_line) {
         if(_write_back())
             return -1;
     }
     *actual_size = chunk;
     return 0;
 }
References __mlibc_file_base::__buffer_ptr, __mlibc_file_base::__buffer_size, __mlibc_file_base::__dirty_begin, __mlibc_file_base::__dirty_end, __ensure, __mlibc_file_base::__io_mode, __MLIBC_ERROR_BIT, __mlibc_file_base::__offset, __mlibc_file_base::__status_bits, __mlibc_file_base::__valid_limit, _bufmode, _ensure_allocation(), _init_bufmode(), _reset(), _write_back(), mlibc::anonymous_namespace{file-io.cpp}::globallyDisableBuffering, io_write(), mlibc::line_buffer, max_size, memchr(), memcpy(), mlibc::no_buffer, and mlibc::panicLogger.
Field Documentation
_bufmode
buffer_mode mlibc::abstract_file::_bufmode private
Definition at line 69 of file file-io.hpp.
Referenced by _init_bufmode(), read(), update_bufmode(), and write().
_do_dispose
void(* mlibc::abstract_file::_do_dispose) (abstract_file *) private
Definition at line 70 of file file-io.hpp.
Referenced by dispose().
_list_hook
frg::default_list_hook<abstract_file> mlibc::abstract_file::_list_hook
Definition at line 76 of file file-io.hpp.
_lock
RecursiveFutexLock mlibc::abstract_file::_lock
Definition at line 74 of file file-io.hpp.
_type
stream_type mlibc::abstract_file::_type private
Definition at line 68 of file file-io.hpp.
Referenced by _init_type(), _reset(), _save_pos(), and _write_back().
The documentation for this struct was generated from the following files:
Userspace/mlibc/options/ansi/include/mlibc/file-io.hpp
Userspace/mlibc/options/ansi/generic/file-io.cpp