Fennix: Userspace/apps/base/busybox/coreutils/comm.c File Reference
comm.c File Reference
#include "libbb.h"
Macros
#define COMM_OPT_1 (1 << 0)
#define COMM_OPT_2 (1 << 1)
#define COMM_OPT_3 (1 << 2)
Functions
static void writeline (char *line, int class)
int comm_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
COMM_OPT_1
#define COMM_OPT_1 (1 << 0)
Definition at line 30 of file comm.c.
COMM_OPT_2
#define COMM_OPT_2 (1 << 1)
Definition at line 31 of file comm.c.
COMM_OPT_3
#define COMM_OPT_3 (1 << 2)
Definition at line 32 of file comm.c.
Function Documentation
comm_main()
int comm_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 58 of file comm.c.
 {
     char *thisline[2];
     FILE *stream[2];
     int i;
     int order;
     getopt32(argv, "^" "123" "\0" "=2");
     argv += optind;
     for (i = 0; i < 2; ++i) {
         stream[i] = xfopen_stdin(argv[i]);
     }
     order = 0;
     thisline[1] = thisline[0] = NULL;
     while (1) {
         if (order <= 0) {
             free(thisline[0]);
             thisline[0] = xmalloc_fgetline(stream[0]);
         }
         if (order >= 0) {
             free(thisline[1]);
             thisline[1] = xmalloc_fgetline(stream[1]);
         }
         i = !thisline[0] + (!thisline[1] << 1);
         if (i)
             break;
         order = strcmp(thisline[0], thisline[1]);
         if (order >= 0)
             writeline(thisline[1], order ? 1 : 2);
         else
             writeline(thisline[0], 0);
     }
     /* EOF at least on one of the streams */
     i &= 1;
     if (thisline[i]) {
         /* stream[i] is not at EOF yet */
         /* we did not print thisline[i] yet */
         char *p = thisline[i];
         writeline(p, i);
         while (1) {
             free(p);
             p = xmalloc_fgetline(stream[i]);
             if (!p)
                 break;
             writeline(p, i);
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         fclose(stream[0]);
         fclose(stream[1]);
     }
     return EXIT_SUCCESS;
 }
References argv, EXIT_SUCCESS, fclose(), free, getopt32(), i, NULL, optind, order(), p, strcmp, writeline(), xfopen_stdin(), and xmalloc_fgetline().
writeline()
static void writeline (char * line, int class) static
Definition at line 35 of file comm.c.
 {
     int flags = option_mask32;
     if (class == 0) {
         if (flags & COMM_OPT_1)
             return;
     } else if (class == 1) {
         if (flags & COMM_OPT_2)
             return;
         if (!(flags & COMM_OPT_1))
             putchar('\t');
     } else /*if (class == 2)*/ {
         if (flags & COMM_OPT_3)
             return;
         if (!(flags & COMM_OPT_1))
             putchar('\t');
         if (!(flags & COMM_OPT_2))
             putchar('\t');
     }
     puts(line);
 }
References COMM_OPT_1, COMM_OPT_2, COMM_OPT_3, flags, option_mask32, putchar, and puts().
Referenced by comm_main().