Fennix: Userspace/musl/src/math/acosf.c File Reference
acosf.c File Reference
#include "libm.h"
Functions
static float R (float z)
float acosf (float x)
Variables
static const float pio2_hi = 1.5707962513e+00
static const float pio2_lo = 7.5497894159e-08
static const float pS0 = 1.6666586697e-01
static const float pS1 = -4.2743422091e-02
static const float pS2 = -8.6563630030e-03
static const float qS1 = -7.0662963390e-01
Function Documentation
acosf()
float acosf (float x)
Definition at line 34 of file acosf.c.
 {
     float z,w,s,c,df;
     uint32_t hx,ix;
     GET_FLOAT_WORD(hx, x);
     ix = hx & 0x7fffffff;
     /* |x| >= 1 or nan */
     if (ix >= 0x3f800000) {
         if (ix == 0x3f800000) {
             if (hx >> 31)
                 return 2*pio2_hi + 0x1p-120f;
             return 0;
         }
         return 0/(x-x);
     }
     /* |x| < 0.5 */
     if (ix < 0x3f000000) {
         if (ix <= 0x32800000) /* |x| < 2**-26 */
             return pio2_hi + 0x1p-120f;
         return pio2_hi - (x - (pio2_lo-x*R(x*x)));
     }
     /* x < -0.5 */
     if (hx >> 31) {
         z = (1+x)*0.5f;
         s = sqrtf(z);
         w = R(z)*s-pio2_lo;
         return 2*(pio2_hi - (s+w));
     }
     /* x > 0.5 */
     z = (1-x)*0.5f;
     s = sqrtf(z);
     GET_FLOAT_WORD(hx,s);
     SET_FLOAT_WORD(df,hx&0xfffff000);
     c = (z-df*df)/(s+df);
     w = R(z)*s+c;
     return 2*(df+w);
 }
References c, GET_FLOAT_WORD, pio2_hi, pio2_lo, R(), SET_FLOAT_WORD, sqrtf(), and x.
R()
static float R (float z) static
Definition at line 26 of file acosf.c.
 {
     float_t p, q;
     p = z*(pS0+z*(pS1+z*pS2));
     q = 1.0f+z*qS1;
     return p/q;
 }
References p, pS0, pS1, pS2, and qS1.
Referenced by acosf().
Variable Documentation
pio2_hi
const float pio2_hi = 1.5707962513e+00 static
Definition at line 19 of file acosf.c.
Referenced by acosf().
pio2_lo
const float pio2_lo = 7.5497894159e-08 static
Definition at line 20 of file acosf.c.
Referenced by acosf().
pS0
const float pS0 = 1.6666586697e-01 static
Definition at line 21 of file acosf.c.
Referenced by R().
pS1
const float pS1 = -4.2743422091e-02 static
Definition at line 22 of file acosf.c.
Referenced by R().
pS2
const float pS2 = -8.6563630030e-03 static
Definition at line 23 of file acosf.c.
Referenced by R().
qS1
const float qS1 = -7.0662963390e-01 static
Definition at line 24 of file acosf.c.
Referenced by R().