Fennix Userspace: Userspace/apps/base/bash/error.c File Reference
error.c File Reference
#include "config.h"
#include "bashtypes.h"
#include <fcntl.h>
#include <varargs.h>
#include <stdio.h>
#include <errno.h>
#include "bashansi.h"
#include "bashintl.h"
#include "shell.h"
#include "execute_cmd.h"
#include "flags.h"
#include "input.h"
Macros
#define MAINTAINER "bash-maintainers@gnu.org"
Functions
int executing_line_number PARAMS ((void))
static void error_prolog PARAMS ((int))
static void error_prolog (int print_lineno)
char * get_name_for_error ()
void file_error (char *filename) const
void programming_error (char *format, va_alist) const
void report_error (char *format, va_alist) const
void fatal_error (char *format, va_alist) const
void internal_error (char *format, va_alist) const
void internal_warning (char *format, va_alist) const
void internal_inform (char *format, va_alist) const
void internal_debug (char *format, va_alist) const
void sys_error (char *format, va_alist) const
void parser_error (int lineno, const char *format, va_alist)
void command_error (char *func, int code, int e, int flags) const
char * command_errstr (int code)
void err_unboundvar (char *s) const
void err_readonly (char *s) const
Variables
int errno
const char *const the_current_maintainer = MAINTAINER
int gnu_error_format = 0
static const char *const cmd_error_table []
Macro Definition Documentation
MAINTAINER
#define MAINTAINER "bash-maintainers@gnu.org"
Definition at line 71 of file error.c.
Function Documentation
command_error()
void command_error (char * func, int code, int e, int flags) const
Definition at line 496 of file error.c.
 {
   if (code > CMDERR_LAST)
     code = CMDERR_DEFAULT;
   programming_error ("%s: %s: %d", func, _(cmd_error_table[code]), e);
 }
References _, cmd_error_table, CMDERR_DEFAULT, CMDERR_LAST, code, and programming_error().
Referenced by clean_simple_command(), dispose_command(), execute_command_internal(), execute_connection(), make_command_string_internal(), parse_and_execute(), parse_string(), and reader_loop().
command_errstr()
char* command_errstr (int code)
Definition at line 507 of file error.c.
 {
   if (code > CMDERR_LAST)
     code = CMDERR_DEFAULT;
   return (_(cmd_error_table[code]));
 }
References _, cmd_error_table, CMDERR_DEFAULT, CMDERR_LAST, and code.
err_readonly()
void err_readonly (char * s) const
Definition at line 533 of file error.c.
 {
   report_error (_("%s: readonly variable"), s);
 }
References _, report_error(), and s.
Referenced by asort_builtin(), assign_in_env(), bind_variable_internal(), csv_builtin(), cut_internal(), dsv_builtin(), execute_for_command(), and realpath_builtin().
err_unboundvar()
void err_unboundvar (char * s) const
Definition at line 526 of file error.c.
 {
   report_error (_("%s: unbound variable"), s);
 }
References _, report_error(), and s.
Referenced by expr_streval(), param_expand(), and parameter_brace_expand().
error_prolog()
static void error_prolog (int print_lineno) static
Definition at line 79 of file error.c.
 {
   char *ename;
   int line;
   ename = get_name_for_error ();
   line = (print_lineno && interactive_shell == 0) ? executing_line_number () : -1;
   if (line > 0)
     fprintf (stderr, "%s:%s%d: ", ename, gnu_error_format ? "" : _(" line "), line);
   else
     fprintf (stderr, "%s: ", ename);
 }
References _, executing_line_number(), fprintf(), get_name_for_error(), gnu_error_format, interactive_shell, line, print_lineno(), and stderr.
Referenced by fatal_error(), internal_debug(), internal_error(), internal_inform(), internal_warning(), report_error(), and sys_error().
fatal_error()
void fatal_error (char * format, va_alist) const
Definition at line 213 of file error.c.
 {
   va_list args;
   error_prolog (0);
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   va_end (args);
   sh_exit (2);
 }
References args, error_prolog(), format(), fprintf(), sh_exit(), SH_VA_START, stderr, va_end, and vfprintf().
file_error()
void file_error (char * filename) const
Definition at line 132 of file error.c.
 {
   report_error ("%s: %s", filename, strerror (errno));
 }
References errno, filename, report_error(), and strerror().
get_name_for_error()
char* get_name_for_error ()
Definition at line 96 of file error.c.
 {
   char *name;
 #if defined (ARRAY_VARS)
   SHELL_VAR *bash_source_v;
   ARRAY *bash_source_a;
 #endif
   name = (char *)NULL;
   if (interactive_shell == 0)
     {
 #if defined (ARRAY_VARS)
       bash_source_v = find_variable ("BASH_SOURCE");
       if (bash_source_v && array_p (bash_source_v) &&
       (bash_source_a = array_cell (bash_source_v)))
     name = array_reference (bash_source_a, 0);
       if (name == 0 || *name == '\0')   /* XXX - was just name == 0 */
 #endif
     name = dollar_vars[0];
     }
   if (name == 0 && shell_name && *shell_name)
     name = base_pathname (shell_name);
   if (name == 0)
 #if defined (PROGRAM)
     name = PROGRAM;
 #else
     name = "bash";
 #endif
   return (name);
 }
References array_cell, array_p, base_pathname(), dollar_vars, find_variable(), interactive_shell, NULL, PROGRAM, and shell_name.
Referenced by builtin_error_prolog(), error_prolog(), get_working_directory(), notify_of_job_status(), parser_error(), and sh_exit().
internal_debug()
void internal_debug (char * format, va_alist) const
Definition at line 301 of file error.c.
 {
 #ifdef DEBUG
   va_list args;
   error_prolog (1);
   fprintf (stderr, _("DEBUG warning: "));
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   va_end (args);
 #else
   return;
 #endif
 }
References _, args, error_prolog(), format(), fprintf(), SH_VA_START, stderr, va_end, and vfprintf().
Referenced by add_process(), bgp_add(), delete_old_job(), dequote_string(), maybe_give_terminal_to(), run_pending_traps(), trap_handler(), and wait_for().
internal_error()
void internal_error (char * format, va_alist) const
Definition at line 235 of file error.c.
 {
   va_list args;
   error_prolog (1);
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   va_end (args);
 }
References args, error_prolog(), format(), fprintf(), SH_VA_START, stderr, va_end, and vfprintf().
Referenced by _evalfile(), all_local_variables(), async_redirect_stdin(), bind_variable_value(), check_identifier(), check_unbind_variable(), evalerror(), execute_builtin(), execute_disk_command(), execute_function(), execute_intern_function(), initialize_job_control(), make_here_document(), make_local_variable(), netopen(), open_shell_script(), pop_scope(), pop_var_context(), redirection_error(), run_pending_traps(), sh_noassign(), shell_execve(), sigprocmask(), start_job(), sv_shcompat(), sv_xtracefd(), verify_substring_values(), wait_for_single_pid(), and xtrace_set().
internal_inform()
void internal_inform (char * format, va_alist) const
Definition at line 278 of file error.c.
 {
   va_list args;
   error_prolog (1);
   /* TRANSLATORS: this is a prefix for informational messages. */
   fprintf (stderr, _("INFORM: "));
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   va_end (args);
 }
References _, args, error_prolog(), format(), fprintf(), SH_VA_START, stderr, va_end, and vfprintf().
internal_warning()
void internal_warning (char * format, va_alist) const
Definition at line 256 of file error.c.
 {
   va_list args;
   error_prolog (1);
   fprintf (stderr, _("warning: "));
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   va_end (args);
 }
References _, args, error_prolog(), format(), fprintf(), SH_VA_START, stderr, va_end, and vfprintf().
Referenced by add_process(), adjust_shell_level(), bgp_delete(), bgp_search(), bind_int_variable(), bind_variable(), bind_variable_internal(), bind_variable_value(), delete_job(), find_variable_nameref(), find_variable_nameref_for_assignment(), find_variable_nameref_for_create(), main(), make_here_document(), param_expand(), parse_and_execute(), parse_comsub(), read_comsub(), redir_special_open(), run_pending_traps(), set_locale_var(), shell_getc(), start_debugger(), unwind_frame_discard_internal(), unwind_frame_run_internal(), wait_for_job(), waitchld(), xmalloc(), xrealloc(), and xtrace_set().
PARAMS() [1/2]
static void error_prolog PARAMS ((int)) static
PARAMS() [2/2]
int executing_line_number PARAMS ((void))
parser_error()
void parser_error (int lineno, const char * format, va_alist)
Definition at line 358 of file error.c.
 {
   va_list args;
   char *ename, *iname;
   ename = get_name_for_error ();
   iname = yy_input_name ();
   if (interactive)
     fprintf (stderr, "%s: ", ename);
   else if (interactive_shell)
     fprintf (stderr, "%s: %s:%s%d: ", ename, iname, gnu_error_format ? "" : _(" line "), lineno);
   else if (STREQ (ename, iname))
     fprintf (stderr, "%s:%s%d: ", ename, gnu_error_format ? "" : _(" line "), lineno);
   else
     fprintf (stderr, "%s: %s:%s%d: ", ename, iname, gnu_error_format ? "" : _(" line "), lineno);
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   va_end (args);
   if (exit_immediately_on_error)
     exit_shell (last_command_exit_value = 2);
 }
References _, args, exit_immediately_on_error, exit_shell(), format(), fprintf(), get_name_for_error(), gnu_error_format, interactive, interactive_shell, last_command_exit_value, lineno, SH_VA_START, stderr, STREQ, va_end, vfprintf(), and yy_input_name().
Referenced by make_arith_for_command(), parse_compound_assignment(), parse_matched_pair(), print_offending_line(), report_syntax_error(), and xparse_dolparen().
programming_error()
void programming_error (char * format, va_alist) const
Definition at line 142 of file error.c.
 {
   va_list args;
   char *h;
 #if defined (JOB_CONTROL)
   give_terminal_to (shell_pgrp, 0);
 #endif /* JOB_CONTROL */
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   va_end (args);
 #if defined (HISTORY)
   if (remember_on_history)
     {
       h = last_history_line ();
       fprintf (stderr, _("last command: %s\n"), h ? h : "(null)");
     }
 #endif
 #if 0
   fprintf (stderr, "Report this to %s\n", the_current_maintainer);
 #endif
   fprintf (stderr, _("Aborting..."));
   fflush (stderr);
   abort ();
 }
References _, abort(), args, fflush(), format(), fprintf(), give_terminal_to(), h, remember_on_history, SH_VA_START, shell_pgrp, stderr, the_current_maintainer, va_end, and vfprintf().
Referenced by command_error().
report_error()
void report_error (char * format, va_alist) const
Definition at line 186 of file error.c.
 {
   va_list args;
   error_prolog (1);
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, "\n");
   va_end (args);
   if (exit_immediately_on_error)
     {
       if (last_command_exit_value == 0)
     last_command_exit_value = EXECUTION_FAILURE;
       exit_shell (last_command_exit_value);
     }
 }
References args, error_prolog(), EXECUTION_FAILURE, exit_immediately_on_error, exit_shell(), format(), fprintf(), last_command_exit_value, SH_VA_START, stderr, va_end, and vfprintf().
Referenced by do_assignment_internal(), err_readonly(), err_unboundvar(), expand_word_internal(), extract_delimited_string(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), file_error(), glob_expand_word_list(), initialize_shell_variables(), main(), param_expand(), parameter_brace_expand(), parameter_brace_expand_error(), parameter_brace_expand_indir(), parameter_brace_expand_rhs(), parameter_brace_expand_word(), parse_long_options(), parse_shell_options(), and singlemount().
sys_error()
void sys_error (char * format, va_alist) const
Definition at line 327 of file error.c.
 {
   int e;
   va_list args;
   e = errno;
   error_prolog (0);
   SH_VA_START (args, format);
   vfprintf (stderr, format, args);
   fprintf (stderr, ": %s\n", strerror (e));
   va_end (args);
 }
References args, errno, error_prolog(), format(), fprintf(), SH_VA_START, stderr, strerror(), va_end, and vfprintf().
Referenced by add_undo_redirect(), command_substitute(), disable_priv_mode(), do_redirection_internal(), dup_error(), execute_pipeline(), get_tty_state(), getc_with_restart(), give_terminal_to(), initialize_job_control(), make_child(), set_tty_state(), shell_execve(), start_pipeline(), wait_for_background_pids(), and wait_for_single_pid().
Variable Documentation
cmd_error_table
const char* const cmd_error_table[] static
Initial value:
= {
    N_("unknown command error"),
    N_("bad command type"),
    N_("bad connector"),
    N_("bad jump"),
    0
}
Definition at line 487 of file error.c.
Referenced by command_error(), and command_errstr().
errno
int errno extern
Referenced by file_error(), and sys_error().
gnu_error_format
int gnu_error_format = 0
Definition at line 76 of file error.c.
Referenced by error_prolog(), main(), and parser_error().
the_current_maintainer
const char* const the_current_maintainer = MAINTAINER
Definition at line 74 of file error.c.
Referenced by programming_error().