Fennix: Userspace/apps/base/busybox/networking/httpd_indexcgi.c File Reference
httpd_indexcgi.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <dirent.h>
#include <time.h>
Data Structures
struct dir_list_t
Macros
#define _GNU_SOURCE 1 /* for strchrnul */
#define STYLE_STR
Typedefs
typedef struct dir_list_t dir_list_t
Enumerations
enum { BUFFER_SIZE = sizeof(buffer) , HEADROOM = 64 }
Functions
static int compare_dl (dir_list_t *a, dir_list_t *b)
static void guarantee (int size)
static void fmt_str (const char *src)
static void fmt_url (const char *name)
static void fmt_html (const char *name)
static void fmt_ull (unsigned long long n)
static void fmt_02u (unsigned n)
static void fmt_04u (unsigned n)
int main (int argc, char **argv)
Variables
static char buffer [2 *1024 > sizeof(STYLE_STR) ? 2 *1024 :sizeof(STYLE_STR)]
static char * dst = buffer
Data Structure Documentation
dir_list_t
struct dir_list_t
Definition at line 92 of file httpd_indexcgi.c.
Data Fields
mode_t dl_mode
time_t dl_mtime
char * dl_name
off_t dl_size
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE 1 /* for strchrnul */
Definition at line 38 of file httpd_indexcgi.c.
STYLE_STR
#define STYLE_STR
Definition at line 54 of file httpd_indexcgi.c.
Typedef Documentation
dir_list_t
typedef struct dir_list_t dir_list_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BUFFER_SIZE
HEADROOM
Definition at line 118 of file httpd_indexcgi.c.
      {
     BUFFER_SIZE = sizeof(buffer),
     HEADROOM = 64,
 };
Function Documentation
compare_dl()
static int compare_dl (dir_list_t * a, dir_list_t * b) static
Definition at line 99 of file httpd_indexcgi.c.
 {
     /* ".." is 'less than' any other dir entry */
     if (strcmp(a->dl_name, "..") == 0) {
         return -1;
     }
     if (strcmp(b->dl_name, "..") == 0) {
         return 1;
     }
     if (S_ISDIR(a->dl_mode) != S_ISDIR(b->dl_mode)) {
         /* 1 if b is a dir (and thus a is 'after' b, a > b),
          * else -1 (a < b) */
         return (S_ISDIR(b->dl_mode) != 0) ? 1 : -1;
     }
     return strcmp(a->dl_name, b->dl_name);
 }
References dir_list_t::dl_mode, dir_list_t::dl_name, S_ISDIR, and strcmp.
Referenced by main().
fmt_02u()
static void fmt_02u (unsigned n) static
Definition at line 198 of file httpd_indexcgi.c.
 {
     /* n %= 100; - not needed, callers don't pass big n */
     dst[0] = (n / 10) + '0';
     dst[1] = (n % 10) + '0';
     dst += 2;
 }
References dst, and n.
Referenced by fmt_04u(), and main().
fmt_04u()
static void fmt_04u (unsigned n) static
Definition at line 207 of file httpd_indexcgi.c.
 {
     /* n %= 10000; - not needed, callers don't pass big n */
     fmt_02u(n / 100);
     fmt_02u(n % 100);
 }
References fmt_02u(), and n.
Referenced by main().
fmt_html()
static void fmt_html (const char * name) static
Definition at line 164 of file httpd_indexcgi.c.
 {
     while (*name) {
         char c = *name++;
         if (c == '<')
             fmt_str("&lt;");
         else if (c == '>')
             fmt_str("&gt;");
         else if (c == '&') {
             fmt_str("&amp;");
         } else {
             guarantee(1);
             *dst++ = c;
             continue;
         }
     }
 }
References c, dst, fmt_str(), and guarantee().
Referenced by main().
fmt_str()
static void fmt_str (const char * src) static
Definition at line 136 of file httpd_indexcgi.c.
 {
     unsigned len = strlen(src);
     guarantee(len);
     memcpy(dst, src, len);
     dst += len;
 }
References dst, guarantee(), len, memcpy, src, and strlen().
Referenced by display_speed(), display_window_size(), fmt_html(), fmt_ull(), main(), and parse_datestr().
fmt_ull()
static void fmt_ull (unsigned long long n) static
Definition at line 183 of file httpd_indexcgi.c.
 {
     char buf[sizeof(n)*3 + 2];
     char *p;
     p = buf + sizeof(buf) - 1;
     *p = '\0';
     do {
         *--p = (n % 10) + '0';
         n /= 10;
     } while (n);
     fmt_str(/*dst,*/ p);
 }
References buf, fmt_str(), n, and p.
Referenced by main().
fmt_url()
static void fmt_url (const char * name) static
Definition at line 145 of file httpd_indexcgi.c.
 {
     while (*name) {
         unsigned c = *name++;
         guarantee(3);
         *dst = c;
         if ((c - '0') > 9 /* not a digit */
          && ((c|0x20) - 'a') > ('z' - 'a') /* not A-Z or a-z */
          && !strchr("._-+@", c)
         ) {
             *dst++ = '%';
             *dst++ = "0123456789ABCDEF"[c >> 4];
             *dst = "0123456789ABCDEF"[c & 0xf];
         }
         dst++;
     }
 }
References c, dst, guarantee(), and strchr().
Referenced by main().
guarantee()
static void guarantee (int size) static
Definition at line 125 of file httpd_indexcgi.c.
 {
     if (buffer + (BUFFER_SIZE-HEADROOM) - dst >= size)
         return;
     write(STDOUT_FILENO, buffer, dst - buffer);
     dst = buffer;
 }
References buffer, BUFFER_SIZE, dst, HEADROOM, size, STDOUT_FILENO, and write().
Referenced by fmt_html(), fmt_str(), fmt_url(), and main().
main()
int main (int argc , char ** argv)
Definition at line 214 of file httpd_indexcgi.c.
 {
     dir_list_t *dir_list;
     dir_list_t *cdir;
     unsigned dir_list_count;
     unsigned count_dirs;
     unsigned count_files;
     unsigned long long size_total;
     DIR *dirp;
     char *location;
     location = getenv("REQUEST_URI");
     if (!location)
         return 1;
     /* drop URL arguments if any */
     strchrnul(location, '?')[0] = '\0';
     if (location[0] != '/'
      || strstr(location, "//")
      || strstr(location, "/../")
      || strcmp(strrchr(location, '/'), "/..") == 0
     ) {
         return 1;
     }
     if (chdir("..")
      || (location[1] && chdir(location + 1))
     ) {
         return 1;
     }
     dirp = opendir(".");
     if (!dirp)
         return 1;
     dir_list = NULL;
     dir_list_count = 0;
     while (1) {
         struct dirent *dp;
         struct stat sb;
         dp = readdir(dirp);
         if (!dp)
             break;
         if (dp->d_name[0] == '.' && !dp->d_name[1])
             continue;
         if (stat(dp->d_name, &sb) != 0)
             continue;
         dir_list = realloc(dir_list, (dir_list_count + 1) * sizeof(dir_list[0]));
         dir_list[dir_list_count].dl_name = strdup(dp->d_name);
         dir_list[dir_list_count].dl_mode = sb.st_mode;
         dir_list[dir_list_count].dl_size = sb.st_size;
         dir_list[dir_list_count].dl_mtime = sb.st_mtime;
         dir_list_count++;
     }
     closedir(dirp);
     qsort(dir_list, dir_list_count, sizeof(dir_list[0]), (void*)compare_dl);
     fmt_str(
         "" /* Additional headers (currently none) */
         "\r\n" /* Mandatory empty line after headers */
         "<html><head><title>Index of ");
     /* Guard against directories with &, > etc */
     fmt_html(location);
     fmt_str(
         "</title>\n"
         STYLE_STR
         "</head>" "\n"
         "<body>" "\n"
         "<h1>Index of ");
     fmt_html(location);
     fmt_str(
         "</h1>" "\n"
         "<table>" "\n"
         "<col class=nm><col class=sz><col class=dt>" "\n"
         "<tr class=hdr><th class=cnt>Name<th class=sz>Size<th class=dt>Last modified" "\n");
     count_dirs = 0;
     count_files = 0;
     size_total = 0;
     cdir = dir_list;
     while (dir_list_count--) {
         struct tm *ptm;
         if (S_ISDIR(cdir->dl_mode)) {
             count_dirs++;
         } else if (S_ISREG(cdir->dl_mode)) {
             count_files++;
             size_total += cdir->dl_size;
         } else
             goto next;
         fmt_str("<tr><td class=nm><a href='");
         fmt_url(cdir->dl_name); /* %20 etc */
         if (S_ISDIR(cdir->dl_mode))
             *dst++ = '/';
         fmt_str("'>");
         fmt_html(cdir->dl_name); /* &lt; etc */
         if (S_ISDIR(cdir->dl_mode))
             *dst++ = '/';
         fmt_str("</a><td class=sz>");
         if (S_ISREG(cdir->dl_mode))
             fmt_ull(cdir->dl_size);
         fmt_str("<td class=dt>");
         ptm = gmtime(&cdir->dl_mtime);
         fmt_04u(1900 + ptm->tm_year); *dst++ = '-';
         fmt_02u(ptm->tm_mon + 1); *dst++ = '-';
         fmt_02u(ptm->tm_mday); *dst++ = ' ';
         fmt_02u(ptm->tm_hour); *dst++ = ':';
         fmt_02u(ptm->tm_min); *dst++ = ':';
         fmt_02u(ptm->tm_sec);
         *dst++ = '\n';
  next:
         cdir++;
     }
     fmt_str("<tr class=foot><th class=cnt>Files: ");
     fmt_ull(count_files);
     /* count_dirs - 1: we don't want to count ".." */
     fmt_str(", directories: ");
     fmt_ull(count_dirs - 1);
     fmt_str("<th class=sz>");
     fmt_ull(size_total);
     fmt_str("<th class=dt>\n");
     /* "</table></body></html>" - why bother? */
     guarantee(BUFFER_SIZE * 2); /* flush */
     return 0;
 }
References BUFFER_SIZE, chdir(), closedir(), compare_dl(), count_dirs(), dirent::d_name, dir_list_t::dl_mode, dir_list_t::dl_mtime, dir_list_t::dl_name, dir_list_t::dl_size, dst, fmt_02u(), fmt_04u(), fmt_html(), fmt_str(), fmt_ull(), fmt_url(), getenv, gmtime(), guarantee(), next, NULL, opendir(), qsort(), readdir(), realloc, S_ISDIR, S_ISREG, stat::st_mode, stat::st_mtime, stat::st_size, stat(), strchrnul(), strcmp, strdup(), strrchr(), strstr(), STYLE_STR, tm::tm_hour, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, and tm::tm_year.
Variable Documentation
buffer
char buffer[2 *1024 > sizeof(STYLE_STR) ? 2 *1024 :sizeof(STYLE_STR)] static
Definition at line 116 of file httpd_indexcgi.c.
Referenced by guarantee().
dst
char* dst = buffer static
Definition at line 117 of file httpd_indexcgi.c.
Referenced by fmt_02u(), fmt_html(), fmt_str(), fmt_url(), guarantee(), and main().