Fennix Userspace: Userspace/musl/include/ctype.h File Reference
ctype.h File Reference
#include <features.h>
Macros
#define isalpha(a) (0 ? isalpha(a) : (((unsigned)(a)|32)-'a') < 26)
#define isdigit(a) (0 ? isdigit(a) : ((unsigned)(a)-'0') < 10)
#define islower(a) (0 ? islower(a) : ((unsigned)(a)-'a') < 26)
#define isupper(a) (0 ? isupper(a) : ((unsigned)(a)-'A') < 26)
#define isprint(a) (0 ? isprint(a) : ((unsigned)(a)-0x20) < 0x5f)
#define isgraph(a) (0 ? isgraph(a) : ((unsigned)(a)-0x21) < 0x5e)
#define isspace(a) __isspace(a)
Functions
int isalnum (int)
int isalpha (int)
int isblank (int)
int iscntrl (int)
int isdigit (int)
int isgraph (int)
int islower (int)
int isprint (int)
int ispunct (int)
int isspace (int)
int isupper (int)
int isxdigit (int)
int tolower (int)
int toupper (int)
static __inline int __isspace (int _c)
Macro Definition Documentation
isalpha
#define isalpha (a) (0 ? isalpha(a) : (((unsigned)(a)|32)-'a') < 26)
Definition at line 31 of file ctype.h.
isdigit
#define isdigit (a) (0 ? isdigit(a) : ((unsigned)(a)-'0') < 10)
Definition at line 32 of file ctype.h.
isgraph
#define isgraph (a) (0 ? isgraph(a) : ((unsigned)(a)-0x21) < 0x5e)
Definition at line 36 of file ctype.h.
islower
#define islower (a) (0 ? islower(a) : ((unsigned)(a)-'a') < 26)
Definition at line 33 of file ctype.h.
isprint
#define isprint (a) (0 ? isprint(a) : ((unsigned)(a)-0x20) < 0x5f)
Definition at line 35 of file ctype.h.
isspace
#define isspace (a) __isspace(a)
Definition at line 37 of file ctype.h.
isupper
#define isupper (a) (0 ? isupper(a) : ((unsigned)(a)-'A') < 26)
Definition at line 34 of file ctype.h.
Function Documentation
__isspace()
static __inline int __isspace (int _c) static
Definition at line 26 of file ctype.h.
 {
     return _c == ' ' || (unsigned)_c-'\t' < 5;
 }
isalnum()
int isalnum (int nc)
Definition at line 36 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_alnum(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_alnum(), isalpha, isdigit, and mlibc::null.
Referenced by __isalnum_l(), _nl_normalize_codeset(), add_links(), is_valid_hostname(), isalnum_l(), ispunct(), scan_request(), and scan_troff().
isalpha()
int isalpha (int nc)
Definition at line 12 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_alpha(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_alpha(), and mlibc::null.
Referenced by __isalpha_l().
isblank()
int isblank (int nc)
Definition at line 60 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_blank(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_blank(), and mlibc::null.
Referenced by __isblank_l().
iscntrl()
int iscntrl (int nc)
Definition at line 100 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::generic_is_control(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::generic_is_control(), and mlibc::null.
Referenced by __iscntrl_l(), and iscntrl_l().
isdigit()
int isdigit (int nc)
Definition at line 20 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_digit(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_digit(), and mlibc::null.
Referenced by __isdigit_l().
isgraph()
int isgraph (int nc)
Definition at line 52 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_graph(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_graph(), and mlibc::null.
Referenced by __isgraph_l().
islower()
int islower (int nc)
Definition at line 84 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_lower(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_lower(), and mlibc::null.
Referenced by __islower_l().
isprint()
int isprint (int nc)
Definition at line 76 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_print(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_print(), and mlibc::null.
Referenced by __isprint_l().
ispunct()
int ispunct (int nc)
Definition at line 44 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_punct(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_punct(), isalnum(), isgraph, and mlibc::null.
Referenced by __ispunct_l(), ispunct_l(), and scan_troff_mandoc().
isspace()
int isspace (int c)
Definition at line 26 of file ctype.c.
 {
     return c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\f' || c == '\v';
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_space(), and mlibc::null.
Referenced by __isspace_l().
isupper()
int isupper (int nc)
Definition at line 92 of file ctype-stubs.cpp.
                     {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_upper(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_upper(), and mlibc::null.
Referenced by __isupper_l().
isxdigit()
int isxdigit (int nc)
Definition at line 28 of file ctype-stubs.cpp.
                      {
     auto cc = mlibc::current_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_xdigit(cp);
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), mlibc::charset::is_xdigit(), isdigit, and mlibc::null.
Referenced by __isxdigit_l().
tolower()
int tolower (int c)
Definition at line 5 of file ctype.c.
 {
     if (c >= 'A' && c <= 'Z')
     {
         c -= 'A';
         c += 'a';
     }
     return c;
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), isupper, mlibc::null, and mlibc::charset::to_lower().
Referenced by __tolower_l().
toupper()
int toupper (int c)
Definition at line 16 of file ctype.c.
 {
     if (c >= 'a' && c <= 'z')
     {
         c -= 'a';
         c += 'A';
     }
     return c;
 }
References c, cp, mlibc::current_charcode(), mlibc::current_charset(), islower, mlibc::null, and mlibc::charset::to_upper().
Referenced by __toupper_l().