Fennix Userspace: Userspace/musl/src/mman/mprotect.c File Reference
mprotect.c File Reference
#include <sys/mman.h>
#include "libc.h"
#include "syscall.h"
Functions
int __mprotect (void *addr, size_t len, int prot)
weak_alias (__mprotect, mprotect)
Function Documentation
__mprotect()
int __mprotect (void * addr, size_t len, int prot)
Definition at line 5 of file mprotect.c.
 {
     size_t start, end;
     start = (size_t)addr & -PAGE_SIZE;
     end = (size_t)((char *)addr + len + PAGE_SIZE-1) & -PAGE_SIZE;
     return syscall(SYS_mprotect, start, end-start, prot);
 }
References addr, PAGE_SIZE, start(), and syscall().
Referenced by __pthread_create().
weak_alias()
weak_alias (__mprotect , mprotect)