Fennix: Userspace/apps/base/bash/examples/loadables/setpgid.c File Reference
setpgid.c File Reference
#include <config.h>
#include <errno.h>
#include <string.h>
#include "bashtypes.h"
#include "posixtime.h"
#include <stdio.h>
#include "builtins.h"
#include "shell.h"
#include "common.h"
#include "bashgetopt.h"
Macros
#define setpgid(pid, pgrp) setpgrp (pid, pgrp)
Functions
int setpgid_builtin (WORD_LIST *list)
Variables
const char * setpgid_doc []
struct builtin setpgid_struct
Macro Definition Documentation
setpgid
#define setpgid (pid, pgrp) setpgrp (pid, pgrp)
Definition at line 41 of file setpgid.c.
Function Documentation
setpgid_builtin()
int setpgid_builtin (WORD_LIST * list)
Definition at line 45 of file setpgid.c.
 {
   register WORD_LIST *wl;
   intmax_t pid_arg, pgid_arg;
   pid_t pid, pgid;
   char *pidstr, *pgidstr;
   wl = list;
   pid = pgid = 0;
   if (wl == 0 || wl->next == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   pidstr = wl->word ? wl->word->word : 0;
   pgidstr = wl->next->word ? wl->next->word->word : 0;
   if (pidstr == 0 || pgidstr == 0)
     {
       builtin_usage ();
       return (EX_USAGE);
     }
   if (legal_number (pidstr, &pid_arg) == 0)
     {
       builtin_error ("%s: pid argument must be numeric", pidstr);
       return (EXECUTION_FAILURE);
     }
   if (pid_arg < 0)
     {
       builtin_error("%s: negative pid  values not allowed", pidstr);
       return (EXECUTION_FAILURE);
     }
   pid = pid_arg;
   if (legal_number (pgidstr, &pgid_arg) == 0)
     {
       builtin_error ("%s: pgrp argument must be numeric", pgidstr);
       return (EXECUTION_FAILURE);
     }
   if (pgid_arg < 0)
     {
       builtin_error ("%s: negative pgrp values not allowed", pgidstr);
       return (EXECUTION_FAILURE);
     }
   pgid = pgid_arg;
   errno = 0;
   if (setpgid(pid, pgid) < 0)
     {
       builtin_error("setpgid failed: %s", strerror (errno));
       return (EXECUTION_FAILURE);
     }
   return (EXECUTION_SUCCESS);
 }
References builtin_error(), builtin_usage(), errno, EX_USAGE, EXECUTION_FAILURE, EXECUTION_SUCCESS, legal_number(), list(), word_list::next, pid, setpgid, strerror(), word_desc::word, and word_list::word.
Variable Documentation
setpgid_doc
const char* setpgid_doc[]
Initial value:
= {
    "invoke the setpgid(2) system call",
    "",
    "Arguments:",
    "   pid : numeric process identifier, >= 0",
    "   pgrpid: numeric process group identifier, >=0",
    "See the setpgid(2) manual page.",
    (const char *)NULL
}
Definition at line 104 of file setpgid.c.
setpgid_struct
struct builtin setpgid_struct
Initial value:
= {
    "setpgid",
    setpgid_builtin,
    BUILTIN_ENABLED,
    (char **)setpgid_doc,
    "setpgid pid pgrpid",
    0
}
Definition at line 104 of file setpgid.c.