Fennix Userspace: Userspace/musl/src/network/getifaddrs.c File Reference
getifaddrs.c File Reference
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <ifaddrs.h>
#include <syscall.h>
#include <net/if.h>
#include <netinet/in.h>
#include "netlink.h"
Data Structures
struct sockaddr_ll_hack
union sockany
struct ifaddrs_storage
struct ifaddrs_ctx
Macros
#define _GNU_SOURCE
#define IFADDRS_HASH_SIZE 64
Functions
void freeifaddrs (struct ifaddrs *ifp)
static void copy_addr (struct sockaddr **r, int af, union sockany *sa, void *addr, size_t addrlen, int ifindex)
static void gen_netmask (struct sockaddr **r, int af, union sockany *sa, int prefixlen)
static void copy_lladdr (struct sockaddr **r, union sockany *sa, void *addr, size_t addrlen, int ifindex, unsigned short hatype)
static int netlink_msg_to_ifaddr (void *pctx, struct nlmsghdr *h)
int getifaddrs (struct ifaddrs **ifap)
Data Structure Documentation
sockaddr_ll_hack
struct sockaddr_ll_hack
Definition at line 18 of file getifaddrs.c.
Data Fields
unsigned char sll_addr[24]
unsigned short sll_family
unsigned char sll_halen
unsigned short sll_hatype
int sll_ifindex
unsigned char sll_pkttype
unsigned short sll_protocol
sockany
union sockany
Definition at line 26 of file getifaddrs.c.
Data Fields
struct sockaddr_ll_hack ll
struct sockaddr sa
struct sockaddr_in v4
struct sockaddr_in6 v6
ifaddrs_storage
struct ifaddrs_storage
Definition at line 33 of file getifaddrs.c.
Data Fields
struct ifaddrs_storage * hash_next
struct ifaddrs ifa
union sockany addr netmask ifu
unsigned int index
char name[IFNAMSIZ+1]
ifaddrs_ctx
struct ifaddrs_ctx
Definition at line 41 of file getifaddrs.c.
Data Fields
struct ifaddrs * first
struct ifaddrs_storage * hash[IFADDRS_HASH_SIZE]
struct ifaddrs * last
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file getifaddrs.c.
IFADDRS_HASH_SIZE
#define IFADDRS_HASH_SIZE 64
Definition at line 12 of file getifaddrs.c.
Function Documentation
copy_addr()
static void copy_addr (struct sockaddr ** r, int af, union sockany * sa, void * addr, size_t addrlen, int ifindex) static
Definition at line 57 of file getifaddrs.c.
 {
     uint8_t *dst;
     int len;
     switch (af) {
     case AF_INET:
         dst = (uint8_t*) &sa->v4.sin_addr;
         len = 4;
         break;
     case AF_INET6:
         dst = (uint8_t*) &sa->v6.sin6_addr;
         len = 16;
         if (IN6_IS_ADDR_LINKLOCAL(addr) || IN6_IS_ADDR_MC_LINKLOCAL(addr))
             sa->v6.sin6_scope_id = ifindex;
         break;
     default:
         return;
     }
     if (addrlen < len) return;
     sa->sa.sa_family = af;
     memcpy(dst, addr, len);
     *r = &sa->sa;
 }
References addr, AF_INET, AF_INET6, IN6_IS_ADDR_LINKLOCAL, IN6_IS_ADDR_MC_LINKLOCAL, memcpy(), r, sockany::sa, sockaddr::sa_family, sockaddr_in6::sin6_addr, sockaddr_in6::sin6_scope_id, sockaddr_in::sin_addr, sockany::v4, and sockany::v6.
Referenced by gen_netmask(), and netlink_msg_to_ifaddr().
copy_lladdr()
static void copy_lladdr (struct sockaddr ** r, union sockany * sa, void * addr, size_t addrlen, int ifindex, unsigned short hatype) static
Definition at line 94 of file getifaddrs.c.
 {
     if (addrlen > sizeof(sa->ll.sll_addr)) return;
     sa->ll.sll_family = AF_PACKET;
     sa->ll.sll_ifindex = ifindex;
     sa->ll.sll_hatype = hatype;
     sa->ll.sll_halen = addrlen;
     memcpy(sa->ll.sll_addr, addr, addrlen);
     *r = &sa->sa;
 }
References addr, AF_PACKET, sockany::ll, memcpy(), r, sockany::sa, sockaddr_ll_hack::sll_addr, sockaddr_ll_hack::sll_family, sockaddr_ll_hack::sll_halen, sockaddr_ll_hack::sll_hatype, and sockaddr_ll_hack::sll_ifindex.
Referenced by netlink_msg_to_ifaddr().
freeifaddrs()
void freeifaddrs (struct ifaddrs * ifp)
Definition at line 47 of file getifaddrs.c.
 {
     struct ifaddrs *n;
     while (ifp) {
         n = ifp->ifa_next;
         free(ifp);
         ifp = n;
     }
 }
References free, ifaddrs::ifa_next, and n.
Referenced by getifaddrs().
gen_netmask()
static void gen_netmask (struct sockaddr ** r, int af, union sockany * sa, int prefixlen) static
Definition at line 82 of file getifaddrs.c.
 {
     uint8_t addr[16] = {0};
     int i;
     if (prefixlen > 8*sizeof(addr)) prefixlen = 8*sizeof(addr);
     i = prefixlen / 8;
     memset(addr, 0xff, i);
     if (i < sizeof(addr)) addr[i++] = 0xff << (8 - (prefixlen % 8));
     copy_addr(r, af, sa, addr, sizeof(addr), 0);
 }
References addr, copy_addr(), i, memset(), and r.
Referenced by netlink_msg_to_ifaddr().
getifaddrs()
int getifaddrs (struct ifaddrs ** ifap)
Definition at line 207 of file getifaddrs.c.
 {
     struct ifaddrs_ctx _ctx, *ctx = &_ctx;
     int r;
     memset(ctx, 0, sizeof *ctx);
     r = __rtnetlink_enumerate(AF_UNSPEC, AF_UNSPEC, netlink_msg_to_ifaddr, ctx);
     if (r == 0) *ifap = ctx->first;
     else freeifaddrs(ctx->first);
     return r;
 }
References __rtnetlink_enumerate(), AF_UNSPEC, freeifaddrs(), memset(), netlink_msg_to_ifaddr(), and r.
netlink_msg_to_ifaddr()
static int netlink_msg_to_ifaddr (void * pctx, struct nlmsghdr * h) static
Definition at line 105 of file getifaddrs.c.
 {
     struct ifaddrs_ctx *ctx = pctx;
     struct ifaddrs_storage *ifs, *ifs0;
     struct ifinfomsg *ifi = NLMSG_DATA(h);
     struct ifaddrmsg *ifa = NLMSG_DATA(h);
     struct rtattr *rta;
     int stats_len = 0;
     if (h->nlmsg_type == RTM_NEWLINK) {
         for (rta = NLMSG_RTA(h, sizeof(*ifi)); NLMSG_RTAOK(rta, h); rta = RTA_NEXT(rta)) {
             if (rta->rta_type != IFLA_STATS) continue;
             stats_len = RTA_DATALEN(rta);
             break;
         }
     } else {
         for (ifs0 = ctx->hash[ifa->ifa_index % IFADDRS_HASH_SIZE]; ifs0; ifs0 = ifs0->hash_next)
             if (ifs0->index == ifa->ifa_index)
                 break;
         if (!ifs0) return 0;
     }
     ifs = calloc(1, sizeof(struct ifaddrs_storage) + stats_len);
     if (ifs == 0) return -1;
     if (h->nlmsg_type == RTM_NEWLINK) {
         ifs->index = ifi->ifi_index;
         ifs->ifa.ifa_flags = ifi->ifi_flags;
         for (rta = NLMSG_RTA(h, sizeof(*ifi)); NLMSG_RTAOK(rta, h); rta = RTA_NEXT(rta)) {
             switch (rta->rta_type) {
             case IFLA_IFNAME:
                 if (RTA_DATALEN(rta) < sizeof(ifs->name)) {
                     memcpy(ifs->name, RTA_DATA(rta), RTA_DATALEN(rta));
                     ifs->ifa.ifa_name = ifs->name;
                 }
                 break;
             case IFLA_ADDRESS:
                 copy_lladdr(&ifs->ifa.ifa_addr, &ifs->addr, RTA_DATA(rta), RTA_DATALEN(rta), ifi->ifi_index, ifi->ifi_type);
                 break;
             case IFLA_BROADCAST:
                 copy_lladdr(&ifs->ifa.ifa_broadaddr, &ifs->ifu, RTA_DATA(rta), RTA_DATALEN(rta), ifi->ifi_index, ifi->ifi_type);
                 break;
             case IFLA_STATS:
                 ifs->ifa.ifa_data = (void*)(ifs+1);
                 memcpy(ifs->ifa.ifa_data, RTA_DATA(rta), RTA_DATALEN(rta));
                 break;
             }
         }
         if (ifs->ifa.ifa_name) {
             unsigned int bucket = ifs->index % IFADDRS_HASH_SIZE;
             ifs->hash_next = ctx->hash[bucket];
             ctx->hash[bucket] = ifs;
         }
     } else {
         ifs->ifa.ifa_name = ifs0->ifa.ifa_name;
         ifs->ifa.ifa_flags = ifs0->ifa.ifa_flags;
         for (rta = NLMSG_RTA(h, sizeof(*ifa)); NLMSG_RTAOK(rta, h); rta = RTA_NEXT(rta)) {
             switch (rta->rta_type) {
             case IFA_ADDRESS:
                 /* If ifa_addr is already set we, received an IFA_LOCAL before
                  * so treat this as destination address */
                 if (ifs->ifa.ifa_addr)
                     copy_addr(&ifs->ifa.ifa_dstaddr, ifa->ifa_family, &ifs->ifu, RTA_DATA(rta), RTA_DATALEN(rta), ifa->ifa_index);
                 else
                     copy_addr(&ifs->ifa.ifa_addr, ifa->ifa_family, &ifs->addr, RTA_DATA(rta), RTA_DATALEN(rta), ifa->ifa_index);
                 break;
             case IFA_BROADCAST:
                 copy_addr(&ifs->ifa.ifa_broadaddr, ifa->ifa_family, &ifs->ifu, RTA_DATA(rta), RTA_DATALEN(rta), ifa->ifa_index);
                 break;
             case IFA_LOCAL:
                 /* If ifa_addr is set and we get IFA_LOCAL, assume we have
                  * a point-to-point network. Move address to correct field. */
                 if (ifs->ifa.ifa_addr) {
                     ifs->ifu = ifs->addr;
                     ifs->ifa.ifa_dstaddr = &ifs->ifu.sa;
                     memset(&ifs->addr, 0, sizeof(ifs->addr));
                 }
                 copy_addr(&ifs->ifa.ifa_addr, ifa->ifa_family, &ifs->addr, RTA_DATA(rta), RTA_DATALEN(rta), ifa->ifa_index);
                 break;
             case IFA_LABEL:
                 if (RTA_DATALEN(rta) < sizeof(ifs->name)) {
                     memcpy(ifs->name, RTA_DATA(rta), RTA_DATALEN(rta));
                     ifs->ifa.ifa_name = ifs->name;
                 }
                 break;
             }
         }
         if (ifs->ifa.ifa_addr)
             gen_netmask(&ifs->ifa.ifa_netmask, ifa->ifa_family, &ifs->netmask, ifa->ifa_prefixlen);
     }
     if (ifs->ifa.ifa_name) {
         if (!ctx->first) ctx->first = &ifs->ifa;
         if (ctx->last) ctx->last->ifa_next = &ifs->ifa;
         ctx->last = &ifs->ifa;
     } else {
         free(ifs);
     }
     return 0;
 }
References calloc, copy_addr(), copy_lladdr(), free, gen_netmask(), ifaddrs_storage::hash_next, ifaddrs_storage::ifa, ifaddrs::ifa_addr, IFA_ADDRESS, ifaddrs::ifa_broadaddr, IFA_BROADCAST, ifaddrs::ifa_data, ifaddrs::ifa_dstaddr, ifaddrmsg::ifa_family, ifaddrs::ifa_flags, ifaddrmsg::ifa_index, IFA_LABEL, IFA_LOCAL, ifaddrs::ifa_name, ifaddrs::ifa_netmask, ifaddrmsg::ifa_prefixlen, IFADDRS_HASH_SIZE, ifinfomsg::ifi_flags, ifinfomsg::ifi_index, ifinfomsg::ifi_type, IFLA_ADDRESS, IFLA_BROADCAST, IFLA_IFNAME, IFLA_STATS, ifaddrs_storage::ifu, ifaddrs_storage::index, memcpy(), memset(), ifaddrs_storage::name, NLMSG_DATA, NLMSG_RTA, NLMSG_RTAOK, nlmsghdr::nlmsg_type, RTA_DATA, RTA_DATALEN, RTA_NEXT, rtattr::rta_type, RTM_NEWLINK, and sockany::sa.
Referenced by getifaddrs().