Fennix Kernel: Kernel/syscalls/native/exit.cpp File Reference
exit.cpp File Reference
#include <syscalls.hpp>
#include <memory.hpp>
#include <lock.hpp>
#include <exec.hpp>
#include <errno.h>
#include <debug.h>
#include "../../syscalls.h"
#include "../../kernel.h"
#include "../../ipc.h"
Macros
#define SysFrm SyscallsFrame
Functions
__noreturn void sys_exit (SysFrm *, int status)
Macro Definition Documentation
SysFrm
#define SysFrm SyscallsFrame
Definition at line 38 of file exit.cpp.
Function Documentation
sys_exit()
__noreturn void sys_exit (SysFrm * , int status)
Definition at line 47 of file exit.cpp.
 {
     TCB *t = thisThread;
     trace("Userspace thread %s(%d) exited with code %d (%#x)",
           t->Name,
           t->ID, status,
           status < 0 ? -status : status);
     t->ExitCode = status;
     t->KeepTime = TimeManager->CalculateTarget(10, Time::Seconds);
     t->State = Terminated;
     while (true)
         t->GetContext()->Yield();
     __builtin_unreachable();
 }
References Time::time::CalculateTarget(), Tasking::TCB::ExitCode, Tasking::TCB::GetContext(), Tasking::TCB::ID, Tasking::TCB::KeepTime, Tasking::TCB::Name, Time::Seconds, Tasking::TCB::State, Tasking::Terminated, thisThread, TimeManager, trace, and Tasking::Task::Yield().
Referenced by linux_exit().