Fennix Userspace: Userspace/musl/src/signal/psignal.c File Reference
psignal.c File Reference
#include "stdio_impl.h"
#include <string.h>
#include <signal.h>
#include <errno.h>
Functions
void psignal (int sig, const char *msg)
Function Documentation
psignal()
void psignal (int sig, const char * msg)
Definition at line 6 of file psignal.c.
 {
     FILE *f = stderr;
     char *s = strsignal(sig);
     FLOCK(f);
     /* Save stderr's orientation and encoding rule, since psignal is not
      * permitted to change them. Save errno and restore it if there is no
      * error since fprintf might change it even on success but psignal is
      * not permitted to do so. */
     void *old_locale = f->locale;
     int old_mode = f->mode;
     int old_errno = errno;
     if (fprintf(f, "%s%s%s\n", msg?msg:"", msg?": ":"", s)>=0)
         errno = old_errno;
     f->mode = old_mode;
     f->locale = old_locale;
     FUNLOCK(f);
 }
References errno, f, FLOCK, fprintf(), FUNLOCK, _IO_FILE::locale, _IO_FILE::mode, s, stderr, and strsignal().
Referenced by psiginfo().