Fennix: CrashHandler Namespace Reference
CrashHandler Namespace Reference
Data Structures
class CrashKeyboardDriver
struct StackFrame
Functions
void TraceFrames (CHArchTrapFrame *Frame, int Count, SymbolResolver::Symbols *SymHandle, bool Kernel)
void ArrowInput (uint8_t key)
void UserInput (char *Input)
void HookKeyboard ()
void DisplayMainScreen (CRData data)
void DisplayDetailsScreen (CRData data)
void DisplayStackFrameScreen (CRData data)
void DisplayTasksScreen (CRData data)
void DisplayConsoleScreen (CRData data)
SafeFunction void printfWrapper (char c, void *unused)
SafeFunction void EHPrint (const char *Format,...)
SafeFunction void EHDumpData (void *Address, unsigned long Length)
SafeFunction char * TrimWhiteSpace (char *str)
SafeFunction void DisplayTopOverlay ()
SafeFunction void DisplayBottomOverlay ()
SafeFunction void StopAllCores ()
SafeFunction void Handle (void *Data)
if (scanCode==KEY_D_TAB||scanCode==KEY_D_LCTRL||scanCode==KEY_D_LALT||scanCode==KEY_U_LCTRL||scanCode==KEY_U_LALT) return
switch (scanCode)
if (key !=KEY_INVALID)
Variables
int SBIdx = 255
uintptr_t PageFaultAddress = 0
void * EHIntFrames [INT_FRAMES_MAX]
static bool ExceptionOccurred = false
CRData crashdata = {}
int BackSpaceLimit = 0
static char UserInputBuffer [1024]
uint8_t scanCode = inb(0x60)
int key = GetLetterFromScanCode(scanCode)
Data Structure Documentation
CrashHandler::StackFrame
struct CrashHandler::StackFrame
Definition at line 20 of file SFrame.cpp.
Data Fields
struct StackFrame * rbp
uintptr_t rip
Function Documentation
ArrowInput()
SafeFunction void CrashHandler::ArrowInput (uint8_t key)
Definition at line 235 of file CrashHandler.cpp.
     {
         switch (key)
         {
         case KEY_D_UP:
             if (SBIdx < 255)
                 SBIdx++;
             else
                 return;
             break;
         case KEY_D_LEFT:
             if (SBIdx < 255)
                 SBIdx++;
             else
                 return;
             break;
         case KEY_D_RIGHT:
             if (SBIdx > 251)
                 SBIdx--;
             else
                 return;
             break;
         case KEY_D_DOWN:
             if (SBIdx > 251)
                 SBIdx--;
             else
                 return;
             break;
         default:
             break;
         }
         Display->ClearBuffer(SBIdx);
         DisplayTopOverlay();
         EHPrint("\eFAFAFA");
         switch (SBIdx)
         {
         case 255:
         {
             DisplayMainScreen(crashdata);
             break;
         }
         case 254:
         {
             DisplayDetailsScreen(crashdata);
             break;
         }
         case 253:
         {
             DisplayStackFrameScreen(crashdata);
             break;
         }
         case 252:
         {
             DisplayTasksScreen(crashdata);
             break;
         }
         case 251:
         {
             DisplayConsoleScreen(crashdata);
             break;
         }
         default:
         {
             break;
         }
         }
         DisplayBottomOverlay();
         Display->SetBuffer(SBIdx);
     }
References crashdata, Display, DisplayBottomOverlay(), DisplayConsoleScreen(), DisplayDetailsScreen(), DisplayMainScreen(), DisplayStackFrameScreen(), DisplayTasksScreen(), DisplayTopOverlay(), EHPrint(), key, KEY_D_DOWN, KEY_D_LEFT, KEY_D_RIGHT, KEY_D_UP, and SBIdx.
Referenced by switch().
DisplayBottomOverlay()
SafeFunction void CrashHandler::DisplayBottomOverlay ()
Definition at line 221 of file CrashHandler.cpp.
     {
         Video::ScreenBuffer *sb = Display->GetBuffer(SBIdx);
         Video::Font *f = Display->GetCurrentFont();
         Video::FontInfo fi = f->GetInfo();
         for (uint32_t i = 0; i < sb->Width; i++)
             for (uint32_t j = sb->Height - fi.Height - 8; j < sb->Height; j++)
                 Display->SetPixel(i, j, 0x282828, SBIdx);
         Display->SetBufferCursor(SBIdx, 8, sb->Height - fi.Height - 4);
         EHPrint("\eAAAAAA> \eFAFAFA");
     }
References Display, EHPrint(), Video::Font::GetInfo(), Video::FontInfo::Height, Video::ScreenBuffer::Height, i, j, SBIdx, and Video::ScreenBuffer::Width.
Referenced by ArrowInput(), Handle(), and UserInput().
DisplayConsoleScreen()
SafeFunction void CrashHandler::DisplayConsoleScreen (CRData data)
Definition at line 20 of file Console.cpp.
     {
         EHPrint("TODO");
         UNUSED(data);
     }
References EHPrint(), and UNUSED.
Referenced by ArrowInput(), and UserInput().
DisplayDetailsScreen()
SafeFunction void CrashHandler::DisplayDetailsScreen (CRData data)
Definition at line 20 of file Details.cpp.
     {
         if (data.Process)
             EHPrint("\e7981FCCurrent Process: %s(%ld)\n",
                     data.Process->Name,
                     data.Process->ID);
         if (data.Thread)
             EHPrint("\e7981FCCurrent Thread: %s(%ld)\n",
                     data.Thread->Name,
                     data.Thread->ID);
         EHPrint("\e7981FCTechnical Informations on CPU %lld:\n", data.ID);
         uintptr_t ds;
 #if defined(a64)
         CPUData *cpu = (CPUData *)data.CPUData;
         if (cpu)
         {
             EHPrint("\eE46CEBCPU Data Address: %#lx\n", cpu);
             EHPrint("Syscalls Stack: %#lx, TempStack: %#lx\n", cpu->SystemCallStack, cpu->TempStack);
             EHPrint("Core Stack: %#lx, Core ID: %ld, Error Code: %ld\n", cpu->Stack, cpu->ID, cpu->ErrorCode);
             EHPrint("Is Active: %s\n", cpu->IsActive ? "true" : "false");
             EHPrint("Current Process: %#lx, Current Thread: %#lx\n", cpu->CurrentProcess, cpu->CurrentThread);
             EHPrint("Arch Specific Data: %#lx\n", cpu->Data);
             EHPrint("Checksum: 0x%X\n", cpu->Checksum);
         }
         asmv("mov %%ds, %0"
              : "=r"(ds));
 #elif defined(a32)
         asmv("mov %%ds, %0"
              : "=r"(ds));
 #elif defined(aa64)
 #endif
 #if defined(a64)
         EHPrint("\e7981FCFS=%#llx  GS=%#llx  SS=%#llx  CS=%#llx  DS=%#llx\n",
                 CPU::x64::rdmsr(CPU::x64::MSR_FS_BASE), CPU::x64::rdmsr(CPU::x64::MSR_GS_BASE),
                 data.Frame->ss, data.Frame->cs, ds);
         EHPrint("R8=%#llx  R9=%#llx  R10=%#llx  R11=%#llx\n", data.Frame->r8, data.Frame->r9, data.Frame->r10, data.Frame->r11);
         EHPrint("R12=%#llx  R13=%#llx  R14=%#llx  R15=%#llx\n", data.Frame->r12, data.Frame->r13, data.Frame->r14, data.Frame->r15);
         EHPrint("RAX=%#llx  RBX=%#llx  RCX=%#llx  RDX=%#llx\n", data.Frame->rax, data.Frame->rbx, data.Frame->rcx, data.Frame->rdx);
         EHPrint("RSI=%#llx  RDI=%#llx  RBP=%#llx  RSP=%#llx\n", data.Frame->rsi, data.Frame->rdi, data.Frame->rbp, data.Frame->rsp);
         EHPrint("RIP=%#llx  RFL=%#llx  INT=%#llx  ERR=%#llx  EFER=%#llx\n", data.Frame->rip, data.Frame->rflags.raw, data.Frame->InterruptNumber, data.Frame->ErrorCode, data.efer.raw);
 #elif defined(a32)
         EHPrint("\e7981FCFS=%#llx  GS=%#llx  SS=%#llx  CS=%#llx  DS=%#llx\n",
                 CPU::x32::rdmsr(CPU::x32::MSR_FS_BASE), CPU::x32::rdmsr(CPU::x32::MSR_GS_BASE),
                 data.Frame->ss, data.Frame->cs, ds);
         EHPrint("EAX=%#llx  EBX=%#llx  ECX=%#llx  EDX=%#llx\n", data.Frame->eax, data.Frame->ebx, data.Frame->ecx, data.Frame->edx);
         EHPrint("ESI=%#llx  EDI=%#llx  EBP=%#llx  ESP=%#llx\n", data.Frame->esi, data.Frame->edi, data.Frame->ebp, data.Frame->esp);
         EHPrint("EIP=%#llx  EFL=%#llx  INT=%#llx  ERR=%#llx  EFER=%#llx\n", data.Frame->eip, data.Frame->eflags.raw, data.Frame->InterruptNumber, data.Frame->ErrorCode, data.efer.raw);
 #elif defined(aa64)
 #endif
         EHPrint("CR0=%#llx  CR2=%#llx  CR3=%#llx  CR4=%#llx  CR8=%#llx\n", data.cr0.raw, data.cr2.raw, data.cr3.raw, data.cr4.raw, data.cr8.raw);
         EHPrint("DR0=%#llx  DR1=%#llx  DR2=%#llx  DR3=%#llx  DR6=%#llx  DR7=%#llx\n", data.dr0, data.dr1, data.dr2, data.dr3, data.dr6, data.dr7.raw);
         EHPrint("\eFC797BCR0: PE:%s     MP:%s     EM:%s     TS:%s\n     ET:%s     NE:%s     WP:%s     AM:%s\n     NW:%s     CD:%s     PG:%s\n     R0:%#x R1:%#x R2:%#x\n",
                 data.cr0.PE ? "True " : "False", data.cr0.MP ? "True " : "False", data.cr0.EM ? "True " : "False", data.cr0.TS ? "True " : "False",
                 data.cr0.ET ? "True " : "False", data.cr0.NE ? "True " : "False", data.cr0.WP ? "True " : "False", data.cr0.AM ? "True " : "False",
                 data.cr0.NW ? "True " : "False", data.cr0.CD ? "True " : "False", data.cr0.PG ? "True " : "False",
                 data.cr0.Reserved0, data.cr0.Reserved1, data.cr0.Reserved2);
         EHPrint("\eFCBD79CR2: PFLA: %#llx\n",
                 data.cr2.PFLA);
         EHPrint("\e79FC84CR3: PWT:%s     PCD:%s    PDBR:%#llx\n",
                 data.cr3.PWT ? "True " : "False", data.cr3.PCD ? "True " : "False", data.cr3.PDBR);
         EHPrint("\eBD79FCCR4: VME:%s     PVI:%s     TSD:%s      DE:%s\n     PSE:%s     PAE:%s     MCE:%s     PGE:%s\n     PCE:%s    UMIP:%s  OSFXSR:%s OSXMMEXCPT:%s\n    LA57:%s    VMXE:%s    SMXE:%s   PCIDE:%s\n OSXSAVE:%s    SMEP:%s    SMAP:%s     PKE:%s\n     R0:%#x R1:%#x R2:%#x\n",
                 data.cr4.VME ? "True " : "False", data.cr4.PVI ? "True " : "False", data.cr4.TSD ? "True " : "False", data.cr4.DE ? "True " : "False",
                 data.cr4.PSE ? "True " : "False", data.cr4.PAE ? "True " : "False", data.cr4.MCE ? "True " : "False", data.cr4.PGE ? "True " : "False",
                 data.cr4.PCE ? "True " : "False", data.cr4.UMIP ? "True " : "False", data.cr4.OSFXSR ? "True " : "False", data.cr4.OSXMMEXCPT ? "True " : "False",
                 data.cr4.LA57 ? "True " : "False", data.cr4.VMXE ? "True " : "False", data.cr4.SMXE ? "True " : "False", data.cr4.PCIDE ? "True " : "False",
                 data.cr4.OSXSAVE ? "True " : "False", data.cr4.SMEP ? "True " : "False", data.cr4.SMAP ? "True " : "False", data.cr4.PKE ? "True " : "False",
 #if defined(a64)
                 data.cr4.Reserved0, data.cr4.Reserved1, data.cr4.Reserved2);
 #elif defined(a32)
                 data.cr4.Reserved0, data.cr4.Reserved1, 0);
 #elif defined(aa64)
 #endif
         EHPrint("\e79FCF5CR8: TPL:%d\n", data.cr8.TPL);
 #if defined(a64)
         EHPrint("\eFCFC02RFL: CF:%s     PF:%s     AF:%s     ZF:%s\n     SF:%s     TF:%s     IF:%s     DF:%s\n     OF:%s   IOPL:%s     NT:%s     RF:%s\n     VM:%s     AC:%s    VIF:%s    VIP:%s\n     ID:%s     AlwaysOne:%d\n     R0:%#x R1:%#x R2:%#x R3:%#x\n",
                 data.Frame->rflags.CF ? "True " : "False", data.Frame->rflags.PF ? "True " : "False", data.Frame->rflags.AF ? "True " : "False", data.Frame->rflags.ZF ? "True " : "False",
                 data.Frame->rflags.SF ? "True " : "False", data.Frame->rflags.TF ? "True " : "False", data.Frame->rflags.IF ? "True " : "False", data.Frame->rflags.DF ? "True " : "False",
                 data.Frame->rflags.OF ? "True " : "False", data.Frame->rflags.IOPL ? "True " : "False", data.Frame->rflags.NT ? "True " : "False", data.Frame->rflags.RF ? "True " : "False",
                 data.Frame->rflags.VM ? "True " : "False", data.Frame->rflags.AC ? "True " : "False", data.Frame->rflags.VIF ? "True " : "False", data.Frame->rflags.VIP ? "True " : "False",
                 data.Frame->rflags.ID ? "True " : "False", data.Frame->rflags.AlwaysOne,
                 data.Frame->rflags.Reserved0, data.Frame->rflags.Reserved1, data.Frame->rflags.Reserved2, data.Frame->rflags.Reserved3);
 #elif defined(a32)
         EHPrint("\eFCFC02EFL: CF:%s     PF:%s     AF:%s     ZF:%s\n     SF:%s     TF:%s     IF:%s     DF:%s\n     OF:%s   IOPL:%s     NT:%s     RF:%s\n     VM:%s     AC:%s    VIF:%s    VIP:%s\n     ID:%s     AlwaysOne:%d\n     R0:%#x R1:%#x R2:%#x\n",
                 data.Frame->eflags.CF ? "True " : "False", data.Frame->eflags.PF ? "True " : "False", data.Frame->eflags.AF ? "True " : "False", data.Frame->eflags.ZF ? "True " : "False",
                 data.Frame->eflags.SF ? "True " : "False", data.Frame->eflags.TF ? "True " : "False", data.Frame->eflags.IF ? "True " : "False", data.Frame->eflags.DF ? "True " : "False",
                 data.Frame->eflags.OF ? "True " : "False", data.Frame->eflags.IOPL ? "True " : "False", data.Frame->eflags.NT ? "True " : "False", data.Frame->eflags.RF ? "True " : "False",
                 data.Frame->eflags.VM ? "True " : "False", data.Frame->eflags.AC ? "True " : "False", data.Frame->eflags.VIF ? "True " : "False", data.Frame->eflags.VIP ? "True " : "False",
                 data.Frame->eflags.ID ? "True " : "False", data.Frame->eflags.AlwaysOne,
                 data.Frame->eflags.Reserved0, data.Frame->eflags.Reserved1, data.Frame->eflags.Reserved2);
 #elif defined(aa64)
 #endif
         EHPrint("\eA0F0F0DR7: LDR0:%s     GDR0:%s     LDR1:%s     GDR1:%s\n     LDR2:%s     GDR2:%s     LDR3:%s     GDR3:%s\n     CDR0:%s     SDR0:%s     CDR1:%s     SDR1:%s\n     CDR2:%s     SDR2:%s     CDR3:%s     SDR3:%s\n     R:%#x\n",
                 data.dr7.LocalDR0 ? "True " : "False", data.dr7.GlobalDR0 ? "True " : "False", data.dr7.LocalDR1 ? "True " : "False", data.dr7.GlobalDR1 ? "True " : "False",
                 data.dr7.LocalDR2 ? "True " : "False", data.dr7.GlobalDR2 ? "True " : "False", data.dr7.LocalDR3 ? "True " : "False", data.dr7.GlobalDR3 ? "True " : "False",
                 data.dr7.ConditionsDR0 ? "True " : "False", data.dr7.SizeDR0 ? "True " : "False", data.dr7.ConditionsDR1 ? "True " : "False", data.dr7.SizeDR1 ? "True " : "False",
                 data.dr7.ConditionsDR2 ? "True " : "False", data.dr7.SizeDR2 ? "True " : "False", data.dr7.ConditionsDR3 ? "True " : "False", data.dr7.SizeDR3 ? "True " : "False",
                 data.dr7.Reserved);
         EHPrint("\e009FF0EFER: SCE:%s      LME:%s      LMA:%s      NXE:%s\n     SVME:%s    LMSLE:%s    FFXSR:%s      TCE:%s\n     R0:%#x R1:%#x R2:%#x\n",
                 data.efer.SCE ? "True " : "False", data.efer.LME ? "True " : "False", data.efer.LMA ? "True " : "False", data.efer.NXE ? "True " : "False",
                 data.efer.SVME ? "True " : "False", data.efer.LMSLE ? "True " : "False", data.efer.FFXSR ? "True " : "False", data.efer.TCE ? "True " : "False",
                 data.efer.Reserved0, data.efer.Reserved1, data.efer.Reserved2);
         switch (data.Frame->InterruptNumber)
         {
         case CPU::x86::DivideByZero:
         {
             DivideByZeroExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::Debug:
         {
             DebugExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::NonMaskableInterrupt:
         {
             NonMaskableInterruptExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::Breakpoint:
         {
             BreakpointExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::Overflow:
         {
             OverflowExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::BoundRange:
         {
             BoundRangeExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::InvalidOpcode:
         {
             InvalidOpcodeExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::DeviceNotAvailable:
         {
             DeviceNotAvailableExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::DoubleFault:
         {
             DoubleFaultExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::CoprocessorSegmentOverrun:
         {
             CoprocessorSegmentOverrunExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::InvalidTSS:
         {
             InvalidTSSExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::SegmentNotPresent:
         {
             SegmentNotPresentExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::StackSegmentFault:
         {
             StackFaultExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::GeneralProtectionFault:
         {
             GeneralProtectionExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::PageFault:
         {
             PageFaultExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::x87FloatingPoint:
         {
             x87FloatingPointExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::AlignmentCheck:
         {
             AlignmentCheckExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::MachineCheck:
         {
             MachineCheckExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::SIMDFloatingPoint:
         {
             SIMDFloatingPointExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::Virtualization:
         {
             VirtualizationExceptionHandler(data.Frame);
             break;
         }
         case CPU::x86::Security:
         {
             SecurityExceptionHandler(data.Frame);
             break;
         }
         default:
         {
             UnknownExceptionHandler(data.Frame);
             break;
         }
         }
     }
References CPU::x86::AlignmentCheck, AlignmentCheckExceptionHandler(), asmv, CPU::x86::BoundRange, BoundRangeExceptionHandler(), CPU::x86::Breakpoint, BreakpointExceptionHandler(), CPUData::Checksum, CPU::x86::CoprocessorSegmentOverrun, CoprocessorSegmentOverrunExceptionHandler(), CPUData::CurrentProcess, CPUData::CurrentThread, CPUData::Data, CPU::x86::Debug, DebugExceptionHandler(), CPU::x86::DeviceNotAvailable, DeviceNotAvailableExceptionHandler(), CPU::x86::DivideByZero, DivideByZeroExceptionHandler(), CPU::x86::DoubleFault, DoubleFaultExceptionHandler(), EHPrint(), CPUData::ErrorCode, GeneralProtectionExceptionHandler(), CPU::x86::GeneralProtectionFault, CPUData::ID, if(), CPU::x86::InvalidOpcode, InvalidOpcodeExceptionHandler(), CPU::x86::InvalidTSS, InvalidTSSExceptionHandler(), CPUData::IsActive, CPU::x86::MachineCheck, MachineCheckExceptionHandler(), CPU::x32::MSR_FS_BASE, CPU::x64::MSR_FS_BASE, CPU::x32::MSR_GS_BASE, CPU::x64::MSR_GS_BASE, CPU::x86::NonMaskableInterrupt, NonMaskableInterruptExceptionHandler(), CPU::x86::Overflow, OverflowExceptionHandler(), CPU::x86::PageFault, PageFaultExceptionHandler(), CPU::x86::Security, SecurityExceptionHandler(), CPU::x86::SegmentNotPresent, SegmentNotPresentExceptionHandler(), CPU::x86::SIMDFloatingPoint, SIMDFloatingPointExceptionHandler(), CPUData::Stack, StackFaultExceptionHandler(), CPU::x86::StackSegmentFault, CPUData::SystemCallStack, CPUData::TempStack, UnknownExceptionHandler(), CPU::x86::Virtualization, VirtualizationExceptionHandler(), CPU::x86::x87FloatingPoint, and x87FloatingPointExceptionHandler().
Referenced by ArrowInput(), and UserInput().
DisplayMainScreen()
SafeFunction void CrashHandler::DisplayMainScreen (CRData data)
Definition at line 30 of file Main.cpp.
     {
         CHArchTrapFrame *Frame = data.Frame;
         /*
  _______ ___ ___ _______ _______ _______ _______      ______ ______ _______ _______ _______ _______ _____
 |     __|   |   |     __|_     _|    ___|   |   |    |      |   __ \   _   |     __|   |   |    ___|     \
 |__     |\     /|__     | |   | |    ___|       |    |   ---|      <       |__     |       |    ___|  --  |
 |_______| |___| |_______| |___| |_______|__|_|__|    |______|___|__|___|___|_______|___|___|_______|_____/
         */
         EHPrint("\eFF5500 _______ ___ ___ _______ _______ _______ _______      ______ ______ _______ _______ _______ _______ _____  \n");
         EHPrint("|     __|   |   |     __|_     _|    ___|   |   |    |      |   __ \\   _   |     __|   |   |    ___|     \\ \n");
         EHPrint("|__     |\\     /|__     | |   | |    ___|       |    |   ---|      <       |__     |       |    ___|  --  |\n");
         EHPrint("|_______| |___| |_______| |___| |_______|__|_|__|    |______|___|__|___|___|_______|___|___|_______|_____/ \n\eFAFAFA");
         switch (Frame->InterruptNumber)
         {
         case CPU::x86::DivideByZero:
         {
             EHPrint("Exception: Divide By Zero\n");
             EHPrint("The processor attempted to divide a number by zero.\n");
             break;
         }
         case CPU::x86::Debug:
         {
             EHPrint("Exception: Debug\n");
             EHPrint("A debug exception has occurred.\n");
             break;
         }
         case CPU::x86::NonMaskableInterrupt:
         {
             EHPrint("Exception: Non-Maskable Interrupt\n");
             EHPrint("A non-maskable interrupt was received.\n");
             break;
         }
         case CPU::x86::Breakpoint:
         {
             EHPrint("Exception: Breakpoint\n");
             EHPrint("The processor encountered a breakpoint.\n");
             break;
         }
         case CPU::x86::Overflow:
         {
             EHPrint("Exception: Overflow\n");
             EHPrint("The processor attempted to add a number to a number that was too large.\n");
             break;
         }
         case CPU::x86::BoundRange:
         {
             EHPrint("Exception: Bound Range\n");
             EHPrint("The processor attempted to access an array element that is out of bounds.\n");
             break;
         }
         case CPU::x86::InvalidOpcode:
         {
             EHPrint("Exception: Invalid Opcode\n");
             EHPrint("The processor attempted to execute an invalid opcode.\n");
             break;
         }
         case CPU::x86::DeviceNotAvailable:
         {
             EHPrint("Exception: Device Not Available\n");
             EHPrint("The processor attempted to use a device that is not available.\n");
             break;
         }
         case CPU::x86::DoubleFault:
         {
             EHPrint("Exception: Double Fault\n");
             EHPrint("The processor encountered a double fault.\n");
             break;
         }
         case CPU::x86::CoprocessorSegmentOverrun:
         {
             EHPrint("Exception: Coprocessor Segment Overrun\n");
             EHPrint("The processor attempted to access a segment that is not available.\n");
             break;
         }
         case CPU::x86::InvalidTSS:
         {
             EHPrint("Exception: Invalid TSS\n");
             EHPrint("The processor attempted to access a task state segment that is not available or valid.\n");
             CPU::x64::SelectorErrorCode SelCode = {.raw = Frame->ErrorCode};
             EHPrint("External? %s\n", SelCode.External ? "Yes" : "No");
             EHPrint("GDT  IDT  LDT  IDT\n");
             switch (SelCode.Table)
             {
             case 0b00:
             {
                 EHPrint(" ^                \n");
                 EHPrint(" |                \n");
                 EHPrint(" %ld\n", SelCode.Idx);
                 break;
             }
             case 0b01:
             {
                 EHPrint("      ^           \n");
                 EHPrint("      |           \n");
                 EHPrint("      %ld\n", SelCode.Idx);
                 break;
             }
             case 0b10:
             {
                 EHPrint("           ^      \n");
                 EHPrint("           |      \n");
                 EHPrint("           %ld\n", SelCode.Idx);
                 break;
             }
             case 0b11:
             {
                 EHPrint("                ^ \n");
                 EHPrint("                | \n");
                 EHPrint("                %ld\n", SelCode.Idx);
                 break;
             }
             }
             break;
         }
         case CPU::x86::SegmentNotPresent:
         {
             EHPrint("Exception: Segment Not Present\n");
             EHPrint("The processor attempted to access a segment that is not present.\n");
             CPU::x64::SelectorErrorCode SelCode = {.raw = Frame->ErrorCode};
             EHPrint("External? %s\n", SelCode.External ? "Yes" : "No");
             EHPrint("GDT  IDT  LDT  IDT\n");
             switch (SelCode.Table)
             {
             case 0b00:
             {
                 EHPrint(" ^                \n");
                 EHPrint(" |                \n");
                 EHPrint(" %ld\n", SelCode.Idx);
                 break;
             }
             case 0b01:
             {
                 EHPrint("      ^           \n");
                 EHPrint("      |           \n");
                 EHPrint("      %ld\n", SelCode.Idx);
                 break;
             }
             case 0b10:
             {
                 EHPrint("           ^      \n");
                 EHPrint("           |      \n");
                 EHPrint("           %ld\n", SelCode.Idx);
                 break;
             }
             case 0b11:
             {
                 EHPrint("                ^ \n");
                 EHPrint("                | \n");
                 EHPrint("                %ld\n", SelCode.Idx);
                 break;
             }
             }
             break;
         }
         case CPU::x86::StackSegmentFault:
         {
             EHPrint("Exception: Stack Segment Fault\n");
             CPU::x64::SelectorErrorCode SelCode = {.raw = Frame->ErrorCode};
             EHPrint("External? %s\n", SelCode.External ? "Yes" : "No");
             EHPrint("GDT  IDT  LDT  IDT\n");
             switch (SelCode.Table)
             {
             case 0b00:
             {
                 EHPrint(" ^                \n");
                 EHPrint(" |                \n");
                 EHPrint(" %ld\n", SelCode.Idx);
                 break;
             }
             case 0b01:
             {
                 EHPrint("      ^           \n");
                 EHPrint("      |           \n");
                 EHPrint("      %ld\n", SelCode.Idx);
                 break;
             }
             case 0b10:
             {
                 EHPrint("           ^      \n");
                 EHPrint("           |      \n");
                 EHPrint("           %ld\n", SelCode.Idx);
                 break;
             }
             case 0b11:
             {
                 EHPrint("                ^ \n");
                 EHPrint("                | \n");
                 EHPrint("                %ld\n", SelCode.Idx);
                 break;
             }
             }
             break;
         }
         case CPU::x86::GeneralProtectionFault:
         {
             EHPrint("Exception: General Protection Fault\n");
             EHPrint("Kernel performed an illegal operation.\n");
             CPU::x64::SelectorErrorCode SelCode = {.raw = Frame->ErrorCode};
             EHPrint("External? %s\n", SelCode.External ? "Yes" : "No");
             EHPrint("GDT  IDT  LDT  IDT\n");
             switch (SelCode.Table)
             {
             case 0b00:
             {
                 EHPrint(" ^                \n");
                 EHPrint(" |                \n");
                 EHPrint(" %ld\n", SelCode.Idx);
                 break;
             }
             case 0b01:
             {
                 EHPrint("      ^           \n");
                 EHPrint("      |           \n");
                 EHPrint("      %ld\n", SelCode.Idx);
                 break;
             }
             case 0b10:
             {
                 EHPrint("           ^      \n");
                 EHPrint("           |      \n");
                 EHPrint("           %ld\n", SelCode.Idx);
                 break;
             }
             case 0b11:
             {
                 EHPrint("                ^ \n");
                 EHPrint("                | \n");
                 EHPrint("                %ld\n", SelCode.Idx);
                 break;
             }
             }
             break;
         }
         case CPU::x86::PageFault:
         {
             EHPrint("Exception: Page Fault\n");
             EHPrint("The processor attempted to access a page that is not present.\n");
             CPU::x64::PageFaultErrorCode params = {.raw = (uint32_t)Frame->ErrorCode};
 #if defined(a64)
             EHPrint("At \e8888FF%#lx \eFAFAFAby \e8888FF%#lx\eFAFAFA\n", PageFaultAddress, Frame->rip);
 #elif defined(a32)
             EHPrint("At \e8888FF%#lx \eFAFAFAby \e8888FF%#lx\eFAFAFA\n", PageFaultAddress, Frame->eip);
 #elif defined(aa64)
 #endif
             EHPrint("Page: %s\eFAFAFA\n", params.P ? "\e058C19Present" : "\eE85230Not Present");
             EHPrint("Write Operation: \e8888FF%s\eFAFAFA\n", params.W ? "Read-Only" : "Read-Write");
             EHPrint("Processor Mode: \e8888FF%s\eFAFAFA\n", params.U ? "User-Mode" : "Kernel-Mode");
             EHPrint("CPU Reserved Bits: %s\eFAFAFA\n", params.R ? "\eE85230Reserved" : "\e058C19Unreserved");
             EHPrint("Caused By An Instruction Fetch: %s\eFAFAFA\n", params.I ? "\eE85230Yes" : "\e058C19No");
             EHPrint("Caused By A Protection-Key Violation: %s\eFAFAFA\n", params.PK ? "\eE85230Yes" : "\e058C19No");
             EHPrint("Caused By A Shadow Stack Access: %s\eFAFAFA\n", params.SS ? "\eE85230Yes" : "\e058C19No");
             EHPrint("Caused By An SGX Violation: %s\eFAFAFA\n", params.SGX ? "\eE85230Yes" : "\e058C19No");
             EHPrint("More Info: \e8888FF");
             if (Frame->ErrorCode & 0x00000008)
                 EHPrint("One or more page directory entries contain reserved bits which are set to 1.\n");
             else
                 EHPrint(PagefaultDescriptions[Frame->ErrorCode & 0b111]);
             EHPrint("\eFAFAFA");
             break;
         }
         case CPU::x86::x87FloatingPoint:
         {
             EHPrint("Exception: x87 Floating Point\n");
             EHPrint("The x87 FPU generated an error.\n");
             break;
         }
         case CPU::x86::AlignmentCheck:
         {
             EHPrint("Exception: Alignment Check\n");
             EHPrint("The CPU detected an unaligned memory access.\n");
             break;
         }
         case CPU::x86::MachineCheck:
         {
             EHPrint("Exception: Machine Check\n");
             EHPrint("The CPU detected a hardware error.\n");
             break;
         }
         case CPU::x86::SIMDFloatingPoint:
         {
             EHPrint("Exception: SIMD Floating Point\n");
             EHPrint("The CPU detected an error in the SIMD unit.\n");
             break;
         }
         case CPU::x86::Virtualization:
         {
             EHPrint("Exception: Virtualization\n");
             EHPrint("The CPU detected a virtualization error.\n");
             break;
         }
         case CPU::x86::Security:
         {
             EHPrint("Exception: Security\n");
             EHPrint("The CPU detected a security violation.\n");
             break;
         }
         default:
         {
             EHPrint("Exception: Unknown\n");
             EHPrint("The CPU generated an unknown exception.\n");
             break;
         }
         }
 #if defined(a64)
         EHPrint("The exception happened at \e8888FF%#lx\eFAFAFA\n", Frame->rip);
 #elif defined(a32)
         EHPrint("The exception happened at \e8888FF%#lx\eFAFAFA\n", Frame->eip);
 #elif defined(aa64)
 #endif
     }
References CPU::x86::AlignmentCheck, CPU::x86::BoundRange, CPU::x86::Breakpoint, CPU::x86::CoprocessorSegmentOverrun, CPU::x86::Debug, CPU::x86::DeviceNotAvailable, CPU::x86::DivideByZero, CPU::x86::DoubleFault, EHPrint(), CPU::x86::GeneralProtectionFault, CPU::x86::InvalidOpcode, CPU::x86::InvalidTSS, CPU::x86::MachineCheck, CPU::x86::NonMaskableInterrupt, CPU::x86::Overflow, CPU::x86::PageFault, PageFaultAddress, PagefaultDescriptions, params, CPU::x64::SelectorErrorCode::raw, CPU::x86::Security, CPU::x86::SegmentNotPresent, CPU::x86::SIMDFloatingPoint, CPU::x86::StackSegmentFault, CPU::x86::Virtualization, and CPU::x86::x87FloatingPoint.
Referenced by ArrowInput(), Handle(), and UserInput().
DisplayStackFrameScreen()
SafeFunction void CrashHandler::DisplayStackFrameScreen (CRData data)
Definition at line 21 of file StackFrame.cpp.
     {
         EHPrint("\eFAFAFATracing 10 frames...");
         TraceFrames(data.Frame, 10, KernelSymbolTable, true);
         if (data.Process)
         {
             EHPrint("\n\eFAFAFATracing 10 process frames...");
             SymbolResolver::Symbols *sh = data.Process->ELFSymbolTable;
             if (!sh)
                 EHPrint("\n\eFF0000< No symbol table available. >\n");
             else
                 TraceFrames(data.Frame, 10, sh, false);
         }
         EHPrint("\n\eFAFAFATracing interrupt frames...");
         for (short i = 0; i < 8; i++)
         {
             if (EHIntFrames[i])
             {
                 if (!Memory::Virtual().Check(EHIntFrames[i]))
                     continue;
                 EHPrint("\n\e2565CC%p", EHIntFrames[i]);
                 EHPrint("\e7925CC-");
 #if defined(a64)
                 if ((uintptr_t)EHIntFrames[i] >= 0xFFFFFFFF80000000 && (uintptr_t)EHIntFrames[i] <= (uintptr_t)&_kernel_end)
 #elif defined(a32)
                 if ((uintptr_t)EHIntFrames[i] >= 0xC0000000 && (uintptr_t)EHIntFrames[i] <= (uintptr_t)&_kernel_end)
 #elif defined(aa64)
 #endif
                     EHPrint("\e25CCC9%s", KernelSymbolTable->GetSymbolFromAddress((uintptr_t)EHIntFrames[i]));
                 else
                     EHPrint("\eFF4CA9Outside Kernel");
             }
         }
         if (data.Process && data.Thread)
         {
             EHPrint("\n\n\eFAFAFATracing thread instruction pointer history...");
             SymbolResolver::Symbols *sh = data.Process->ELFSymbolTable;
             if (!sh)
                 EHPrint("\n\eFFA500Warning: No symbol table available.");
             int SameItr = 0;
             uintptr_t LastRIP = 0;
             for (size_t i = 0; i < sizeof(data.Thread->IPHistory) / sizeof(data.Thread->IPHistory[0]); i++)
             {
                 if (data.Thread->IPHistory[i] == LastRIP)
                 {
                     SameItr++;
                     if (SameItr > 2)
                         continue;
                 }
                 else
                     SameItr = 0;
                 LastRIP = data.Thread->IPHistory[i];
                 if (!sh)
                     EHPrint("\n\eCCCCCC%d: \e2565CC%p", i, data.Thread->IPHistory[i]);
                 else
                     EHPrint("\n\eCCCCCC%d: \e2565CC%p\e7925CC-\e25CCC9%s", i, data.Thread->IPHistory[i], sh->GetSymbolFromAddress(data.Thread->IPHistory[i]));
             }
             EHPrint("\n\e7925CCNote: \e2565CCSame instruction pointers are not shown more than 3 times.\n");
         }
     }
References Check(), EHIntFrames, EHPrint(), SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelSymbolTable, and TraceFrames().
Referenced by ArrowInput(), and UserInput().
DisplayTasksScreen()
SafeFunction void CrashHandler::DisplayTasksScreen (CRData data)
Definition at line 20 of file Tasks.cpp.
     {
         const char *StatusColor[7] = {
             "FF0000", // Unknown
             "AAFF00", // Ready
             "00AA00", // Running
             "FFAA00", // Sleeping
             "FFAA00", // Waiting
             "FF0088", // Stopped
             "FF0000", // Terminated
         };
         const char *StatusString[7] = {
             "Unknown",    // Unknown
             "Ready",      // Ready
             "Running",    // Running
             "Sleeping",   // Sleeping
             "Waiting",    // Waiting
             "Stopped",    // Stopped
             "Terminated", // Terminated
         };
         std::vector<Tasking::PCB *> Plist = TaskManager->GetProcessList();
         if (TaskManager)
         {
             if (data.Thread)
 #if defined(a64)
                 EHPrint("\eFAFAFACrash occurred in thread \eAA0F0F%s\eFAFAFA(%ld) at \e00AAAA%#lx\n", data.Thread->Name, data.Thread->ID, data.Frame->rip);
 #elif defined(a32)
                 EHPrint("\eFAFAFACrash occurred in thread \eAA0F0F%s\eFAFAFA(%ld) at \e00AAAA%#lx\n", data.Thread->Name, data.Thread->ID, data.Frame->eip);
 #elif defined(aa64)
 #endif
             EHPrint("\eFAFAFAProcess list (%ld):\n", Plist.size());
             foreach (auto Process in Plist)
             {
                 EHPrint("\e%s-> \eFAFAFA%s\eCCCCCC(%ld) \e00AAAA%s\eFAFAFA PT:\e00AAAA%#lx\n",
                         StatusColor[Process->Status], Process->Name, Process->ID, StatusString[Process->Status],
                         Process->PageTable);
                 foreach (auto Thread in Process->Threads)
                     EHPrint("\e%s  -> \eFAFAFA%s\eCCCCCC(%ld) \e00AAAA%s\eFAFAFA Stack:\e00AAAA%#lx\n",
                             StatusColor[Thread->Status], Thread->Name, Thread->ID, StatusString[Thread->Status],
                             Thread->Stack);
             }
         }
         else
             EHPrint("\eFAFAFATaskManager is not initialized!\n");
     }
References EHPrint(), Tasking::Task::GetProcessList(), Process::ID, Thread::ID, Process::Name, Thread::Name, std::vector< T >::size(), and TaskManager.
Referenced by ArrowInput(), and UserInput().
DisplayTopOverlay()
SafeFunction void CrashHandler::DisplayTopOverlay ()
Definition at line 103 of file CrashHandler.cpp.
     {
         Video::ScreenBuffer *sb = Display->GetBuffer(SBIdx);
         Video::Font *f = Display->GetCurrentFont();
         Video::FontInfo fi = f->GetInfo();
         for (uint32_t i = 0; i < sb->Width; i++)
             for (uint32_t j = 0; j < fi.Height + 8; j++)
                 Display->SetPixel(i, j, 0x282828, SBIdx);
         Display->SetBufferCursor(SBIdx, 8, (fi.Height + 8) / 6);
         switch (SBIdx)
         {
         case 255:
         {
             EHPrint("\eAAAAAAMAIN \e606060DETAILS \e606060FRAMES \e606060TASKS \e606060CONSOLE");
             break;
         }
         case 254:
         {
             EHPrint("\e606060MAIN \eAAAAAADETAILS \e606060FRAMES \e606060TASKS \e606060CONSOLE");
             break;
         }
         case 253:
         {
             EHPrint("\e606060MAIN \e606060DETAILS \eAAAAAAFRAMES \e606060TASKS \e606060CONSOLE");
             break;
         }
         case 252:
         {
             EHPrint("\e606060MAIN \e606060DETAILS \e606060FRAMES \eAAAAAATASKS \e606060CONSOLE");
             break;
         }
         case 251:
         {
             EHPrint("\e606060MAIN \e606060DETAILS \e606060FRAMES \e606060TASKS \eAAAAAACONSOLE");
             break;
         }
         default:
         {
             EHPrint("\e606060MAIN \e606060DETAILS \e606060FRAMES \e606060TASKS \e606060CONSOLE");
             break;
         }
         }
         EHPrint("  \e00AAFF%ldMB / %ldMB (%ldMB Reserved)",
                 TO_MB(KernelAllocator.GetUsedMemory()),
                 TO_MB(KernelAllocator.GetTotalMemory()),
                 TO_MB(KernelAllocator.GetReservedMemory()));
         EHPrint("  \eAA0F0F%s", CPU::Hypervisor());
         EHPrint(" \eAAF00F%s", CPU::Vendor());
         EHPrint(" \eAA00FF%s", CPU::Name());
         Display->SetBufferCursor(SBIdx, 0, fi.Height + 10);
         /* https://imgflip.com/i/77slbl */
         if ((Random::rand32() % 100) >= 98)
         {
             debug("Easter egg activated!");
             int BaseXOffset = sb->Width - 14;
             int BaseYOffset = 8;
             Display->SetPixel(BaseXOffset + 3, BaseYOffset + 0, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 4, BaseYOffset + 0, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 6, BaseYOffset + 0, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 7, BaseYOffset + 0, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 2, BaseYOffset + 1, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 3, BaseYOffset + 1, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 4, BaseYOffset + 1, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 5, BaseYOffset + 1, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 6, BaseYOffset + 1, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 7, BaseYOffset + 1, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 8, BaseYOffset + 1, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 1, BaseYOffset + 2, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 2, BaseYOffset + 2, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 3, BaseYOffset + 2, 0xFFFFFF, SBIdx);
             Display->SetPixel(BaseXOffset + 4, BaseYOffset + 2, 0x000000, SBIdx);
             Display->SetPixel(BaseXOffset + 5, BaseYOffset + 2, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 6, BaseYOffset + 2, 0xFFFFFF, SBIdx);
             Display->SetPixel(BaseXOffset + 7, BaseYOffset + 2, 0x000000, SBIdx);
             Display->SetPixel(BaseXOffset + 8, BaseYOffset + 2, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 1, BaseYOffset + 3, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 2, BaseYOffset + 3, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 3, BaseYOffset + 3, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 4, BaseYOffset + 3, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 5, BaseYOffset + 3, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 6, BaseYOffset + 3, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 7, BaseYOffset + 3, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 0, BaseYOffset + 4, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 1, BaseYOffset + 4, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 2, BaseYOffset + 4, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 3, BaseYOffset + 4, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 4, BaseYOffset + 4, 0xA84832, SBIdx);
             Display->SetPixel(BaseXOffset + 5, BaseYOffset + 4, 0xA84832, SBIdx);
             Display->SetPixel(BaseXOffset + 6, BaseYOffset + 4, 0xA84832, SBIdx);
             Display->SetPixel(BaseXOffset + 7, BaseYOffset + 4, 0xA84832, SBIdx);
             Display->SetPixel(BaseXOffset + 0, BaseYOffset + 5, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 1, BaseYOffset + 5, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 2, BaseYOffset + 5, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 3, BaseYOffset + 5, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 4, BaseYOffset + 5, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 5, BaseYOffset + 5, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 6, BaseYOffset + 5, 0x21852E, SBIdx);
             Display->SetPixel(BaseXOffset + 0, BaseYOffset + 6, 0x1216FF, SBIdx);
             Display->SetPixel(BaseXOffset + 1, BaseYOffset + 6, 0x1216FF, SBIdx);
             Display->SetPixel(BaseXOffset + 2, BaseYOffset + 6, 0x1216FF, SBIdx);
             Display->SetPixel(BaseXOffset + 3, BaseYOffset + 6, 0x1216FF, SBIdx);
             Display->SetPixel(BaseXOffset + 4, BaseYOffset + 6, 0x1216FF, SBIdx);
             Display->SetPixel(BaseXOffset + 5, BaseYOffset + 6, 0x1216FF, SBIdx);
             Display->SetPixel(BaseXOffset + 6, BaseYOffset + 6, 0x1216FF, SBIdx);
             Display->SetBuffer(SBIdx);
         }
     }
References debug, Display, EHPrint(), Video::Font::GetInfo(), Video::FontInfo::Height, CPU::Hypervisor(), i, j, KernelAllocator, CPU::Name(), Random::rand32(), SBIdx, CPU::Vendor(), and Video::ScreenBuffer::Width.
Referenced by ArrowInput(), Handle(), and UserInput().
EHDumpData()
SafeFunction void CrashHandler::EHDumpData (void * Address, unsigned long Length)
Definition at line 51 of file CrashHandler.cpp.
     {
         EHPrint("-------------------------------------------------------------------------\n");
         Display->SetBuffer(SBIdx);
         unsigned char *AddressChar = (unsigned char *)Address;
         unsigned char Buffer[17];
         unsigned long Iterate;
         for (Iterate = 0; Iterate < Length; Iterate++)
         {
             if ((Iterate % 16) == 0)
             {
                 if (Iterate != 0)
                     EHPrint("  \e8A78FF%s\eAABBCC\n", Buffer);
                 EHPrint("  \e9E9E9E%04x\eAABBCC ", Iterate);
                 Display->SetBuffer(SBIdx);
             }
             EHPrint(" \e4287f5%02x\eAABBCC", AddressChar[Iterate]);
             if ((AddressChar[Iterate] < 0x20) || (AddressChar[Iterate] > 0x7e))
                 Buffer[Iterate % 16] = '.';
             else
                 Buffer[Iterate % 16] = AddressChar[Iterate];
             Buffer[(Iterate % 16) + 1] = '\0';
         }
         while ((Iterate % 16) != 0)
         {
             EHPrint("   ");
             Display->SetBuffer(SBIdx);
             Iterate++;
         }
         EHPrint("  \e8A78FF%s\eAABBCC\n", Buffer);
         EHPrint("-------------------------------------------------------------------------\n\n.");
         Display->SetBuffer(SBIdx);
     }
References Address, Display, EHPrint(), Length, and SBIdx.
Referenced by UserInput().
EHPrint()
void CrashHandler::EHPrint (const char * Format, ...)
Definition at line 43 of file CrashHandler.cpp.
     {
         va_list args;
         va_start(args, Format);
         vfctprintf(printfWrapper, NULL, Format, args);
         va_end(args);
     }
References args, NULL, printfWrapper(), va_end(), va_start(), and vfctprintf().
Referenced by ArrowInput(), DebugExceptionHandler(), DisplayBottomOverlay(), DisplayConsoleScreen(), DisplayDetailsScreen(), DisplayMainScreen(), DisplayStackFrameScreen(), DisplayTasksScreen(), DisplayTopOverlay(), EHDumpData(), GeneralProtectionExceptionHandler(), Handle(), InvalidOpcodeExceptionHandler(), PageFaultExceptionHandler(), StackFaultExceptionHandler(), TraceFrames(), and UserInput().
Handle()
void CrashHandler::Handle (void * Data)
Definition at line 788 of file CrashHandler.cpp.
     {
         // TODO: SUPPORT SMP
         CPU::Interrupts(CPU::Disable);
         SBIdx = 255;
         CHArchTrapFrame *Frame = (CHArchTrapFrame *)Data;
 #if defined(a64)
         error("An exception occurred!");
         error("Exception: %#llx", Frame->InterruptNumber);
         for (size_t i = 0; i < INT_FRAMES_MAX; i++)
             EHIntFrames[i] = Interrupts::InterruptFrames[i];
         PageFaultAddress = CPU::x64::readcr2().PFLA;
         if (Frame->cs != GDT_USER_CODE && Frame->cs != GDT_USER_DATA)
         {
             if (PageFaultAddress)
                 debug("Exception in kernel mode (ip: %#lx cr2: %#lx (%s))",
                       Frame->rip, PageFaultAddress, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress(Frame->rip) : "No symbol");
             else
                 debug("Exception in kernel mode (ip: %#lx (%s))",
                       Frame->rip, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress(Frame->rip) : "No symbol");
             if (TaskManager)
                 TaskManager->Panic();
             ForceUnlock = true;
             Display->CreateBuffer(0, 0, SBIdx);
             StopAllCores();
         }
         else
         {
             if (PageFaultAddress)
                 debug("Exception in user mode (ip: %#lx cr2: %#lx (%s))",
                       Frame->rip, PageFaultAddress, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress(Frame->rip) : "No symbol");
             else
                 debug("Exception in user mode (ip: %#lx (%s))",
                       Frame->rip, KernelSymbolTable ? KernelSymbolTable->GetSymbolFromAddress(Frame->rip) : "No symbol");
             CPUData *data = GetCurrentCPU();
             if (!data)
             {
                 ForceUnlock = true;
                 Display->CreateBuffer(0, 0, SBIdx);
                 StopAllCores();
                 EHPrint("\eFF0000Cannot get CPU data! This results in a kernel crash!");
                 error("Cannot get CPU data! This results in a kernel crash!");
                 error("This should never happen!");
             }
             else
             {
                 debug("CPU %ld data is valid", data->ID);
                 if (data->CurrentThread->Security.IsCritical)
                 {
                     debug("Critical thread \"%s\"(%d) died", data->CurrentThread->Name, data->CurrentThread->ID);
                     if (TaskManager)
                         TaskManager->Panic();
                     ForceUnlock = true;
                     Display->CreateBuffer(0, 0, SBIdx);
                     StopAllCores();
                 }
                 else
                 {
                     debug("Current thread is valid %#lx", data->CurrentThread);
                     UserModeExceptionHandler(Frame);
                     return;
                 }
             }
         }
         if (ExceptionOccurred)
         {
             SBIdx = 255;
             Display->ClearBuffer(SBIdx);
             Display->SetBufferCursor(SBIdx, 0, 0);
             CPU::x64::CR0 cr0 = CPU::x64::readcr0();
             CPU::x64::CR2 cr2 = CPU::x64::CR2{.PFLA = PageFaultAddress};
             CPU::x64::CR3 cr3 = CPU::x64::readcr3();
             CPU::x64::CR4 cr4 = CPU::x64::readcr4();
             CPU::x64::CR8 cr8 = CPU::x64::readcr8();
             CPU::x64::EFER efer;
             efer.raw = CPU::x64::rdmsr(CPU::x64::MSR_EFER);
             uintptr_t ds;
             asmv("mov %%ds, %0"
                  : "=r"(ds));
             EHPrint("\eFF2525FS=%#llx  GS=%#llx  SS=%#llx  CS=%#llx  DS=%#llx\n",
                     CPU::x64::rdmsr(CPU::x64::MSR_FS_BASE), CPU::x64::rdmsr(CPU::x64::MSR_GS_BASE),
                     Frame->ss, Frame->cs, ds);
             EHPrint("R8=%#llx  R9=%#llx  R10=%#llx  R11=%#llx\n", Frame->r8, Frame->r9, Frame->r10, Frame->r11);
             EHPrint("R12=%#llx  R13=%#llx  R14=%#llx  R15=%#llx\n", Frame->r12, Frame->r13, Frame->r14, Frame->r15);
             EHPrint("RAX=%#llx  RBX=%#llx  RCX=%#llx  RDX=%#llx\n", Frame->rax, Frame->rbx, Frame->rcx, Frame->rdx);
             EHPrint("RSI=%#llx  RDI=%#llx  RBP=%#llx  RSP=%#llx\n", Frame->rsi, Frame->rdi, Frame->rbp, Frame->rsp);
             EHPrint("RIP=%#llx  RFL=%#llx  INT=%#llx  ERR=%#llx  EFER=%#llx\n", Frame->rip, Frame->rflags.raw, Frame->InterruptNumber, Frame->ErrorCode, efer.raw);
             EHPrint("CR0=%#llx  CR2=%#llx  CR3=%#llx  CR4=%#llx  CR8=%#llx\n", cr0.raw, cr2.raw, cr3.raw, cr4.raw, cr8.raw);
             EHPrint("CR0: PE:%s     MP:%s     EM:%s     TS:%s\n     ET:%s     NE:%s     WP:%s     AM:%s\n     NW:%s     CD:%s     PG:%s\n     R0:%#x R1:%#x R2:%#x\n",
                     cr0.PE ? "True " : "False", cr0.MP ? "True " : "False", cr0.EM ? "True " : "False", cr0.TS ? "True " : "False",
                     cr0.ET ? "True " : "False", cr0.NE ? "True " : "False", cr0.WP ? "True " : "False", cr0.AM ? "True " : "False",
                     cr0.NW ? "True " : "False", cr0.CD ? "True " : "False", cr0.PG ? "True " : "False",
                     cr0.Reserved0, cr0.Reserved1, cr0.Reserved2);
             EHPrint("CR2: PFLA: %#llx\n",
                     cr2.PFLA);
             EHPrint("CR3: PWT:%s     PCD:%s    PDBR:%#llx\n",
                     cr3.PWT ? "True " : "False", cr3.PCD ? "True " : "False", cr3.PDBR);
             EHPrint("CR4: VME:%s     PVI:%s     TSD:%s      DE:%s\n     PSE:%s     PAE:%s     MCE:%s     PGE:%s\n     PCE:%s    UMIP:%s  OSFXSR:%s OSXMMEXCPT:%s\n    LA57:%s    VMXE:%s    SMXE:%s   PCIDE:%s\n OSXSAVE:%s    SMEP:%s    SMAP:%s     PKE:%s\n     R0:%#x R1:%#x R2:%#x\n",
                     cr4.VME ? "True " : "False", cr4.PVI ? "True " : "False", cr4.TSD ? "True " : "False", cr4.DE ? "True " : "False",
                     cr4.PSE ? "True " : "False", cr4.PAE ? "True " : "False", cr4.MCE ? "True " : "False", cr4.PGE ? "True " : "False",
                     cr4.PCE ? "True " : "False", cr4.UMIP ? "True " : "False", cr4.OSFXSR ? "True " : "False", cr4.OSXMMEXCPT ? "True " : "False",
                     cr4.LA57 ? "True " : "False", cr4.VMXE ? "True " : "False", cr4.SMXE ? "True " : "False", cr4.PCIDE ? "True " : "False",
                     cr4.OSXSAVE ? "True " : "False", cr4.SMEP ? "True " : "False", cr4.SMAP ? "True " : "False", cr4.PKE ? "True " : "False",
                     cr4.Reserved0, cr4.Reserved1, cr4.Reserved2);
             EHPrint("CR8: TPL:%d\n", cr8.TPL);
             EHPrint("RFL: CF:%s     PF:%s     AF:%s     ZF:%s\n     SF:%s     TF:%s     IF:%s     DF:%s\n     OF:%s   IOPL:%s     NT:%s     RF:%s\n     VM:%s     AC:%s    VIF:%s    VIP:%s\n     ID:%s     AlwaysOne:%d\n     R0:%#x R1:%#x R2:%#x R3:%#x\n",
                     Frame->rflags.CF ? "True " : "False", Frame->rflags.PF ? "True " : "False", Frame->rflags.AF ? "True " : "False", Frame->rflags.ZF ? "True " : "False",
                     Frame->rflags.SF ? "True " : "False", Frame->rflags.TF ? "True " : "False", Frame->rflags.IF ? "True " : "False", Frame->rflags.DF ? "True " : "False",
                     Frame->rflags.OF ? "True " : "False", Frame->rflags.IOPL ? "True " : "False", Frame->rflags.NT ? "True " : "False", Frame->rflags.RF ? "True " : "False",
                     Frame->rflags.VM ? "True " : "False", Frame->rflags.AC ? "True " : "False", Frame->rflags.VIF ? "True " : "False", Frame->rflags.VIP ? "True " : "False",
                     Frame->rflags.ID ? "True " : "False", Frame->rflags.AlwaysOne,
                     Frame->rflags.Reserved0, Frame->rflags.Reserved1, Frame->rflags.Reserved2, Frame->rflags.Reserved3);
             EHPrint("EFER: SCE:%s      LME:%s      LMA:%s      NXE:%s\n     SVME:%s    LMSLE:%s    FFXSR:%s      TCE:%s\n     R0:%#x R1:%#x R2:%#x\n",
                     efer.SCE ? "True " : "False", efer.LME ? "True " : "False", efer.LMA ? "True " : "False", efer.NXE ? "True " : "False",
                     efer.SVME ? "True " : "False", efer.LMSLE ? "True " : "False", efer.FFXSR ? "True " : "False", efer.TCE ? "True " : "False",
                     efer.Reserved0, efer.Reserved1, efer.Reserved2);
             EHPrint("\nException occurred while handling exception! HALTED!");
             Display->SetBuffer(SBIdx);
             Interrupts::RemoveAll();
             CPU::Stop();
         }
         ExceptionOccurred = true;
         if (DriverManager)
             DriverManager->UnloadAllDrivers();
         debug("Reading control registers...");
         crashdata.Frame = Frame;
         crashdata.cr0 = CPU::x64::readcr0();
         crashdata.cr2 = CPU::x64::CR2{.PFLA = PageFaultAddress};
         crashdata.cr3 = CPU::x64::readcr3();
         crashdata.cr4 = CPU::x64::readcr4();
         crashdata.cr8 = CPU::x64::readcr8();
         crashdata.efer.raw = CPU::x64::rdmsr(CPU::x64::MSR_EFER);
         uintptr_t ds;
         asmv("mov %%ds, %0"
              : "=r"(ds));
         // Get debug registers
         asmv("movq %%dr0, %0"
              : "=r"(crashdata.dr0));
         asmv("movq %%dr1, %0"
              : "=r"(crashdata.dr1));
         asmv("movq %%dr2, %0"
              : "=r"(crashdata.dr2));
         asmv("movq %%dr3, %0"
              : "=r"(crashdata.dr3));
         asmv("movq %%dr6, %0"
              : "=r"(crashdata.dr6));
         asmv("movq %%dr7, %0"
              : "=r"(crashdata.dr7));
         CPUData *cpudata = GetCurrentCPU();
         if (cpudata == nullptr)
         {
             EHPrint("\eFFA500Invalid CPU data!\n");
             for (long i = 0; i < MAX_CPU; i++)
             {
                 cpudata = GetCPU(i);
                 if (cpudata != nullptr)
                     break;
                 if (i == MAX_CPU - 1)
                 {
                     EHPrint("\eFF0000No CPU data found!\n");
                     cpudata = nullptr;
                 }
             }
             debug("CPU ptr %#lx", cpudata);
         }
         if (cpudata != nullptr)
         {
             crashdata.ID = cpudata->ID;
             crashdata.CPUData = cpudata;
             error("Technical Informations on CPU %lld:", cpudata->ID);
         }
         if (TaskManager && cpudata != nullptr)
         {
             crashdata.Process = cpudata->CurrentProcess.Load();
             crashdata.Thread = cpudata->CurrentThread.Load();
             error("Current Process: %s(%ld)",
                   cpudata->CurrentProcess->Name,
                   cpudata->CurrentProcess->ID);
             error("Current Thread: %s(%ld)",
                   cpudata->CurrentThread->Name,
                   cpudata->CurrentThread->ID);
         }
         {
             error("FS=%#llx  GS=%#llx  SS=%#llx  CS=%#llx  DS=%#llx",
                   CPU::x64::rdmsr(CPU::x64::MSR_FS_BASE), CPU::x64::rdmsr(CPU::x64::MSR_GS_BASE),
                   Frame->ss, Frame->cs, ds);
             error("R8=%#llx  R9=%#llx  R10=%#llx  R11=%#llx", Frame->r8, Frame->r9, Frame->r10, Frame->r11);
             error("R12=%#llx  R13=%#llx  R14=%#llx  R15=%#llx", Frame->r12, Frame->r13, Frame->r14, Frame->r15);
             error("RAX=%#llx  RBX=%#llx  RCX=%#llx  RDX=%#llx", Frame->rax, Frame->rbx, Frame->rcx, Frame->rdx);
             error("RSI=%#llx  RDI=%#llx  RBP=%#llx  RSP=%#llx", Frame->rsi, Frame->rdi, Frame->rbp, Frame->rsp);
             error("RIP=%#llx  RFL=%#llx  INT=%#llx  ERR=%#llx  EFER=%#llx", Frame->rip, Frame->rflags.raw, Frame->InterruptNumber, Frame->ErrorCode, crashdata.efer.raw);
             error("CR0=%#llx  CR2=%#llx  CR3=%#llx  CR4=%#llx  CR8=%#llx", crashdata.cr0.raw, crashdata.cr2.raw, crashdata.cr3.raw, crashdata.cr4.raw, crashdata.cr8.raw);
             error("DR0=%#llx  DR1=%#llx  DR2=%#llx  DR3=%#llx  DR6=%#llx  DR7=%#llx", crashdata.dr0, crashdata.dr1, crashdata.dr2, crashdata.dr3, crashdata.dr6, crashdata.dr7.raw);
             error("CR0: PE:%s     MP:%s     EM:%s     TS:%s     ET:%s     NE:%s     WP:%s     AM:%s     NW:%s     CD:%s     PG:%s     R0:%#x R1:%#x R2:%#x",
                   crashdata.cr0.PE ? "True " : "False", crashdata.cr0.MP ? "True " : "False", crashdata.cr0.EM ? "True " : "False", crashdata.cr0.TS ? "True " : "False",
                   crashdata.cr0.ET ? "True " : "False", crashdata.cr0.NE ? "True " : "False", crashdata.cr0.WP ? "True " : "False", crashdata.cr0.AM ? "True " : "False",
                   crashdata.cr0.NW ? "True " : "False", crashdata.cr0.CD ? "True " : "False", crashdata.cr0.PG ? "True " : "False",
                   crashdata.cr0.Reserved0, crashdata.cr0.Reserved1, crashdata.cr0.Reserved2);
             error("CR2: PFLA: %#llx",
                   crashdata.cr2.PFLA);
             error("CR3: PWT:%s     PCD:%s    PDBR:%#llx",
                   crashdata.cr3.PWT ? "True " : "False", crashdata.cr3.PCD ? "True " : "False", crashdata.cr3.PDBR);
             error("CR4: VME:%s     PVI:%s     TSD:%s      DE:%s     PSE:%s     PAE:%s     MCE:%s     PGE:%s     PCE:%s    UMIP:%s  OSFXSR:%s OSXMMEXCPT:%s    LA57:%s    VMXE:%s    SMXE:%s   PCIDE:%s OSXSAVE:%s    SMEP:%s    SMAP:%s     PKE:%s     R0:%#x R1:%#x R2:%#x",
                   crashdata.cr4.VME ? "True " : "False", crashdata.cr4.PVI ? "True " : "False", crashdata.cr4.TSD ? "True " : "False", crashdata.cr4.DE ? "True " : "False",
                   crashdata.cr4.PSE ? "True " : "False", crashdata.cr4.PAE ? "True " : "False", crashdata.cr4.MCE ? "True " : "False", crashdata.cr4.PGE ? "True " : "False",
                   crashdata.cr4.PCE ? "True " : "False", crashdata.cr4.UMIP ? "True " : "False", crashdata.cr4.OSFXSR ? "True " : "False", crashdata.cr4.OSXMMEXCPT ? "True " : "False",
                   crashdata.cr4.LA57 ? "True " : "False", crashdata.cr4.VMXE ? "True " : "False", crashdata.cr4.SMXE ? "True " : "False", crashdata.cr4.PCIDE ? "True " : "False",
                   crashdata.cr4.OSXSAVE ? "True " : "False", crashdata.cr4.SMEP ? "True " : "False", crashdata.cr4.SMAP ? "True " : "False", crashdata.cr4.PKE ? "True " : "False",
                   crashdata.cr4.Reserved0, crashdata.cr4.Reserved1, crashdata.cr4.Reserved2);
             error("CR8: TPL:%d", crashdata.cr8.TPL);
             error("RFL: CF:%s     PF:%s     AF:%s     ZF:%s     SF:%s     TF:%s     IF:%s     DF:%s     OF:%s   IOPL:%s     NT:%s     RF:%s     VM:%s     AC:%s    VIF:%s    VIP:%s     ID:%s     AlwaysOne:%d     R0:%#x R1:%#x R2:%#x R3:%#x",
                   Frame->rflags.CF ? "True " : "False", Frame->rflags.PF ? "True " : "False", Frame->rflags.AF ? "True " : "False", Frame->rflags.ZF ? "True " : "False",
                   Frame->rflags.SF ? "True " : "False", Frame->rflags.TF ? "True " : "False", Frame->rflags.IF ? "True " : "False", Frame->rflags.DF ? "True " : "False",
                   Frame->rflags.OF ? "True " : "False", Frame->rflags.IOPL ? "True " : "False", Frame->rflags.NT ? "True " : "False", Frame->rflags.RF ? "True " : "False",
                   Frame->rflags.VM ? "True " : "False", Frame->rflags.AC ? "True " : "False", Frame->rflags.VIF ? "True " : "False", Frame->rflags.VIP ? "True " : "False",
                   Frame->rflags.ID ? "True " : "False", Frame->rflags.AlwaysOne,
                   Frame->rflags.Reserved0, Frame->rflags.Reserved1, Frame->rflags.Reserved2, Frame->rflags.Reserved3);
             error("DR7: LDR0:%s     GDR0:%s     LDR1:%s     GDR1:%s     LDR2:%s     GDR2:%s     LDR3:%s     GDR3:%s     CDR0:%s     SDR0:%s     CDR1:%s     SDR1:%s     CDR2:%s     SDR2:%s     CDR3:%s     SDR3:%s     R:%#x",
                   crashdata.dr7.LocalDR0 ? "True " : "False", crashdata.dr7.GlobalDR0 ? "True " : "False", crashdata.dr7.LocalDR1 ? "True " : "False", crashdata.dr7.GlobalDR1 ? "True " : "False",
                   crashdata.dr7.LocalDR2 ? "True " : "False", crashdata.dr7.GlobalDR2 ? "True " : "False", crashdata.dr7.LocalDR3 ? "True " : "False", crashdata.dr7.GlobalDR3 ? "True " : "False",
                   crashdata.dr7.ConditionsDR0 ? "True " : "False", crashdata.dr7.SizeDR0 ? "True " : "False", crashdata.dr7.ConditionsDR1 ? "True " : "False", crashdata.dr7.SizeDR1 ? "True " : "False",
                   crashdata.dr7.ConditionsDR2 ? "True " : "False", crashdata.dr7.SizeDR2 ? "True " : "False", crashdata.dr7.ConditionsDR3 ? "True " : "False", crashdata.dr7.SizeDR3 ? "True " : "False",
                   crashdata.dr7.Reserved);
             error("EFER: SCE:%s      LME:%s      LMA:%s      NXE:%s     SVME:%s    LMSLE:%s    FFXSR:%s      TCE:%s     R0:%#x R1:%#x R2:%#x",
                   crashdata.efer.SCE ? "True " : "False", crashdata.efer.LME ? "True " : "False", crashdata.efer.LMA ? "True " : "False", crashdata.efer.NXE ? "True " : "False",
                   crashdata.efer.SVME ? "True " : "False", crashdata.efer.LMSLE ? "True " : "False", crashdata.efer.FFXSR ? "True " : "False", crashdata.efer.TCE ? "True " : "False",
                   crashdata.efer.Reserved0, crashdata.efer.Reserved1, crashdata.efer.Reserved2);
         }
         goto CrashEnd;
 #elif defined(a32)
 #elif defined(aa64)
 #endif
     CrashEnd:
         if (Config.InterruptsOnCrash)
         {
             // 255 // Main
             Display->CreateBuffer(0, 0, 254); // Details
             Display->CreateBuffer(0, 0, 253); // Frames
             Display->CreateBuffer(0, 0, 252); // Tasks
             Display->CreateBuffer(0, 0, 251); // Console
             Display->CreateBuffer(0, 0, 250); // Empty
             DisplayTopOverlay();
             DisplayMainScreen(crashdata);
             DisplayBottomOverlay();
             Display->SetBuffer(255);
             debug("Interrupts are enabled, waiting for user input");
             CPU::Interrupts(CPU::Enable);
             HookKeyboard();
         }
         else
         {
             /*
             TODO: Stuff that should be done when IOC is disabled.
             */
             Display->SetBuffer(255);
         }
         CPU::Halt(true);
     }
References asmv, Config, crashdata, CPUData::CurrentProcess, CPUData::CurrentThread, Data, debug, CPU::Disable, Display, DisplayBottomOverlay(), DisplayMainScreen(), DisplayTopOverlay(), DriverManager, EHIntFrames, EHPrint(), CPU::Enable, error, ExceptionOccurred, ForceUnlock, GDT_USER_CODE, GDT_USER_DATA, GetCPU(), GetCurrentCPU(), SymbolResolver::Symbols::GetSymbolFromAddress(), CPU::Halt(), HookKeyboard(), i, CPUData::ID, Tasking::TCB::ID, Tasking::PCB::ID, INT_FRAMES_MAX, Interrupts::InterruptFrames, CPU::Interrupts(), KernelConfig::InterruptsOnCrash, Tasking::TaskSecurity::IsCritical, KernelSymbolTable, Atomic< T >::Load(), MAX_CPU, CPU::x64::MSR_EFER, CPU::x64::MSR_FS_BASE, CPU::x64::MSR_GS_BASE, Tasking::TCB::Name, Tasking::PCB::Name, PageFaultAddress, Tasking::Task::Panic(), CPU::x64::EFER::raw, CPU::x64::CR0::raw, CPU::x64::CR2::raw, CPU::x64::CR3::raw, CPU::x64::CR4::raw, CPU::x64::CR8::raw, Interrupts::RemoveAll(), SBIdx, Tasking::TCB::Security, CPU::Stop(), StopAllCores(), TaskManager, Driver::Driver::UnloadAllDrivers(), and UserModeExceptionHandler().
Referenced by ExceptionHandler().
HookKeyboard()
SafeFunction void CrashHandler::HookKeyboard ()
Definition at line 159 of file KBDrv.cpp.
     {
         CrashKeyboardDriver kbd; // We don't want to allocate memory.
         asmv("KeyboardHookLoop: nop; jmp KeyboardHookLoop;");
         // CPU::Halt(true); // This is an infinite loop.
     }
References asmv.
Referenced by Handle().
if() [1/2]
CrashHandler::if (key ! = KEY_INVALID)
Definition at line 132 of file KBDrv.cpp.
         {
             if (key == KEY_D_BACKSPACE)
             {
                 if (BackSpaceLimit > 0)
                 {
                     Display->Print('\b', SBIdx);
                     backspace(UserInputBuffer);
                     BackSpaceLimit--;
                 }
             }
             else if (key == '\n')
             {
                 UserInput(UserInputBuffer);
                 BackSpaceLimit = 0;
                 UserInputBuffer[0] = '\0';
             }
             else
             {
                 append(UserInputBuffer, key);
                 Display->Print(key, SBIdx);
                 BackSpaceLimit++;
             }
             Display->SetBuffer(SBIdx); // Update as we type.
         }
References append(), backspace(), BackSpaceLimit, Display, key, KEY_D_BACKSPACE, SBIdx, UserInput(), and UserInputBuffer.
if() [2/2]
CrashHandler::if (scanCode = =KEY_D_TAB||scanCode==KEY_D_LCTRL||scanCode==KEY_D_LALT||scanCode==KEY_U_LCTRL||scanCode==KEY_U_LALT)
Referenced by DisplayDetailsScreen(), and TraceFrames().
printfWrapper()
SafeFunction void CrashHandler::printfWrapper (char c, void * unused)
Definition at line 37 of file CrashHandler.cpp.
     {
         Display->Print(c, SBIdx, true);
         UNUSED(unused);
     }
References c, Display, SBIdx, and UNUSED.
Referenced by EHPrint().
StopAllCores()
SafeFunction void CrashHandler::StopAllCores ()
Definition at line 754 of file CrashHandler.cpp.
     {
 #if defined(a64) || defined(a32)
         /* FIXME: Can't send IPIs to other cores
          * because it causes another exception on
          * the other cores.
          *
          * Also it makes every core to stay at 100% usage for some reason.
          */
         // if (SMP::CPUCores > 1)
         // {
         //     for (int i = 1; i < SMP::CPUCores; i++)
         //     {
         //         APIC::InterruptCommandRegisterLow icr;
         //         icr.Vector = CPU::x86::IRQ29;
         //         icr.Level = APIC::APICLevel::Assert;
         //         ((APIC::APIC *)Interrupts::apic[i])->IPI(i, icr);
         //         __sync;
         //     }
         // }
         // APIC::InterruptCommandRegisterLow icr;
         // icr.Vector = CPU::x86::IRQ29;
         // icr.Level = APIC::APICLevel::Assert;
         // icr.DestinationShorthand = APIC::APICDestinationShorthand::AllExcludingSelf;
         // ((APIC::APIC *)Interrupts::apic[0])->IPI(0, icr);
         // CPU::Interrupts(CPU::Enable);
         __sync;
         CPU::Interrupts(CPU::Disable);
         // }
 #elif defined(aa64)
 #endif
     }
References __sync, CPU::Disable, and CPU::Interrupts().
Referenced by Handle().
switch()
CrashHandler::switch (scanCode)
Definition at line 122 of file KBDrv.cpp.
         {
         case KEY_D_UP:
         case KEY_D_LEFT:
         case KEY_D_RIGHT:
         case KEY_D_DOWN:
             ArrowInput(scanCode);
         }
References ArrowInput(), KEY_D_DOWN, KEY_D_LEFT, KEY_D_RIGHT, KEY_D_UP, and scanCode.
Referenced by ProcessMB2(), and tre_match_empty().
TraceFrames()
SafeFunction void CrashHandler::TraceFrames (CHArchTrapFrame * Frame, int Count, SymbolResolver::Symbols * SymHandle, bool Kernel)
Definition at line 26 of file SFrame.cpp.
     {
         if (!Memory::Virtual().Check(Frame))
         {
             EHPrint("Invalid frame pointer: %p\n", Frame);
             return;
         }
 #if defined(a64)
         struct StackFrame *frames = (struct StackFrame *)Frame->rbp; // (struct StackFrame *)__builtin_frame_address(0);
         if (!Memory::Virtual().Check((void *)Frame->rbp))
 #elif defined(a32)
         struct StackFrame *frames = (struct StackFrame *)Frame->ebp; // (struct StackFrame *)__builtin_frame_address(0);
         if (!Memory::Virtual().Check((void *)Frame->ebp))
 #elif defined(aa64)
 #endif
         {
             #if defined(a64)
             EHPrint("Invalid rbp pointer: %p\n", Frame->rbp);
             #elif defined(a32)
             EHPrint("Invalid ebp pointer: %p\n", Frame->ebp);
             #elif defined(aa64)
 #endif
             return;
         }
         if (!Memory::Virtual().Check(SymHandle))
         {
             EHPrint("Invalid symbol handle: %p\n", SymHandle);
             return;
         }
         debug("\nStack tracing... %p %d %p %d", Frame, Count, frames, Kernel);
         EHPrint("\e7981FC\nStack Trace:\n");
         if (!frames || !frames->rip || !frames->rbp)
         {
 #if defined(a64)
             EHPrint("\e2565CC%p", (void *)Frame->rip);
 #elif defined(a32)
             EHPrint("\e2565CC%p", (void *)Frame->eip);
 #elif defined(aa64)
 #endif
             EHPrint("\e7925CC-");
 #if defined(a64)
             EHPrint("\eAA25CC%s", SymHandle->GetSymbolFromAddress(Frame->rip));
 #elif defined(a32)
             EHPrint("\eAA25CC%s", SymHandle->GetSymbolFromAddress(Frame->eip));
 #elif defined(aa64)
 #endif
             EHPrint("\e7981FC <- Exception");
             EHPrint("\eFF0000\n< No stack trace available. >\n");
         }
         else
         {
 #if defined(a64)
             EHPrint("\e2565CC%p", (void *)Frame->rip);
             EHPrint("\e7925CC-");
             if ((Frame->rip >= 0xFFFFFFFF80000000 && Frame->rip <= (uintptr_t)&_kernel_end) || !Kernel)
                 EHPrint("\eAA25CC%s", SymHandle->GetSymbolFromAddress(Frame->rip));
             else
                 EHPrint("Outside Kernel");
 #elif defined(a32)
             EHPrint("\e2565CC%p", (void *)Frame->eip);
             EHPrint("\e7925CC-");
             if ((Frame->eip >= 0xC0000000 && Frame->eip <= (uintptr_t)&_kernel_end) || !Kernel)
                 EHPrint("\eAA25CC%s", SymHandle->GetSymbolFromAddress(Frame->eip));
             else
                 EHPrint("Outside Kernel");
 #elif defined(aa64)
 #endif
             EHPrint("\e7981FC <- Exception");
             for (int frame = 0; frame < Count; ++frame)
             {
                 if (!frames->rip)
                     break;
                 EHPrint("\n\e2565CC%p", (void *)frames->rip);
                 EHPrint("\e7925CC-");
 #if defined(a64)
                 if ((frames->rip >= 0xFFFFFFFF80000000 && frames->rip <= (uintptr_t)&_kernel_end) || !Kernel)
 #elif defined(a32)
                 if ((frames->rip >= 0xC0000000 && frames->rip <= (uintptr_t)&_kernel_end) || !Kernel)
 #elif defined(aa64)
 #endif
                     EHPrint("\e25CCC9%s", SymHandle->GetSymbolFromAddress(frames->rip));
                 else
                     EHPrint("\eFF4CA9Outside Kernel");
                 if (!Memory::Virtual().Check(frames->rbp))
                     return;
                 frames = frames->rbp;
             }
         }
         EHPrint("\n");
     }
References Check(), debug, EHPrint(), SymbolResolver::Symbols::GetSymbolFromAddress(), if(), Tasking::Kernel, CrashHandler::StackFrame::rbp, and CrashHandler::StackFrame::rip.
Referenced by DisplayStackFrameScreen().
TrimWhiteSpace()
SafeFunction char* CrashHandler::TrimWhiteSpace (char * str)
Definition at line 87 of file CrashHandler.cpp.
     {
         char *end;
         while (*str == ' ')
             str++;
         if (*str == 0)
             return str;
         end = str + strlen(str) - 1;
         while (end > str && *end == ' ')
             end--;
         *(end + 1) = 0;
         return str;
     }
References strlen().
Referenced by UserInput().
UserInput()
SafeFunction void CrashHandler::UserInput (char * Input)
Definition at line 306 of file CrashHandler.cpp.
     {
         SmartCriticalSection(UserInputLock);
         Display->ClearBuffer(SBIdx);
         DisplayTopOverlay();
         EHPrint("\eFAFAFA");
         if (strcmp(Input, "help") == 0)
         {
             EHPrint("Available commands are:\n");
             EHPrint("exit - Shutdown the OS.\n");
             EHPrint("reboot - Reboot the OS.\n");
             EHPrint("help - Display this help message.\n");
             EHPrint("showbuf,sb <INDEX> - Display the contents of a screen buffer.\n");
             EHPrint("       - A sleep timer will be enabled. This will cause the OS to sleep for an unknown amount of time.\n");
             EHPrint("       - \eFF4400WARNING: This can crash the system if a wrong buffer is selected.\eFAFAFA\n");
             EHPrint("ifr <COUNT> - Show interrupt frames.\n");
             EHPrint("tlb <ADDRESS> - Print the page table entries\n");
             EHPrint("bitmap - Print the memory bitmap\n");
             EHPrint("mem - Print the memory allocation\n");
             EHPrint("cr<INDEX> - Print the CPU control register\n");
             EHPrint("tss <CORE> - Print the CPU task state segment\n");
             EHPrint("dump <ADDRESS HEX> <LENGTH DEC> - Dump memory\n");
             EHPrint("       - \eFF4400WARNING: This can crash the system if you try to read from an unmapped page.\eFAFAFA\n");
             EHPrint("uartmemdmp <INDEX> <SKIP INACCESSIBLE (bool 0,1)> - Dump the memory of a UART.\n");
             EHPrint("main - Show the main screen.\n");
             EHPrint("details - Show the details screen.\n");
             EHPrint("frames - Show the stack frame screen.\n");
             EHPrint("tasks - Show the tasks screen.\n");
             EHPrint("console - Show the console screen.\n");
             EHPrint("Also, you can use the arrow keys to navigate between the screens.\n");
             EHPrint("=========================================================================\n");
             EHPrint("Kernel Compiled at: %s %s with C++ Standard: %d\n", __DATE__, __TIME__, CPP_LANGUAGE_STANDARD);
             EHPrint("C++ Language Version (__cplusplus): %ld\n", __cplusplus);
         }
         else if (strcmp(Input, "exit") == 0)
         {
             PowerManager->Shutdown();
             EHPrint("\eFFFFFFNow it's safe to turn off your computer.");
             Display->SetBuffer(SBIdx);
             CPU::Stop();
         }
         else if (strcmp(Input, "reboot") == 0)
         {
             PowerManager->Reboot();
             EHPrint("\eFFFFFFNow it's safe to reboot your computer.");
             Display->SetBuffer(SBIdx);
             CPU::Stop();
         }
         else if (strncmp(Input, "showbuf", 7) == 0 || strncmp(Input, "sb", 2) == 0)
         {
             char *arg = TrimWhiteSpace(Input + 7);
             int tmpidx = SBIdx;
             SBIdx = atoi(arg);
             Display->SetBuffer(SBIdx);
             for (int i = 0; i < 5000000; i++)
                 inb(0x80);
             SBIdx = tmpidx;
             Display->SetBuffer(SBIdx);
         }
         else if (strncmp(Input, "ifr", 3) == 0)
         {
             char *arg = TrimWhiteSpace(Input + 3);
             int CountI = atoi(arg);
             int TotalCount = sizeof(EHIntFrames) / sizeof(EHIntFrames[0]);
             debug("Printing %ld interrupt frames.", CountI);
             if (CountI > TotalCount)
             {
                 EHPrint("\eFF4400Count too big! Maximum allowed is %ld\eFAFAFA\n", TotalCount);
                 Display->SetBuffer(SBIdx);
             }
             else
             {
                 for (int i = 0; i < CountI; i++)
                 {
                     if (EHIntFrames[i])
                     {
                         if (!Memory::Virtual().Check(EHIntFrames[i]))
                             continue;
                         EHPrint("\n\e2565CC%p", EHIntFrames[i]);
                         EHPrint("\e7925CC-");
 #if defined(a64)
                         if ((uintptr_t)EHIntFrames[i] >= 0xFFFFFFFF80000000 && (uintptr_t)EHIntFrames[i] <= (uintptr_t)&_kernel_end)
 #elif defined(a32)
                         if ((uintptr_t)EHIntFrames[i] >= 0xC0000000 && (uintptr_t)EHIntFrames[i] <= (uintptr_t)&_kernel_end)
 #elif defined(aa64)
 #endif
                             EHPrint("\e25CCC9%s", KernelSymbolTable->GetSymbolFromAddress((uintptr_t)EHIntFrames[i]));
                         else
                             EHPrint("\eFF4CA9Outside Kernel");
                         for (int i = 0; i < 20000; i++)
                             inb(0x80);
                         Display->SetBuffer(SBIdx);
                     }
                 }
             }
         }
         else if (strncmp(Input, "tlb", 3) == 0)
         {
             char *arg = TrimWhiteSpace(Input + 3);
             uintptr_t Address = NULL;
             Address = strtol(arg, NULL, 16);
             debug("Converted %s to %#lx", arg, Address);
             Memory::PageTable4 *BasePageTable = (Memory::PageTable4 *)Address;
             if (Memory::Virtual().Check(BasePageTable))
             {
                 for (int PMLIndex = 0; PMLIndex < 512; PMLIndex++)
                 {
                     Memory::PageMapLevel4 PML4 = BasePageTable->Entries[PMLIndex];
                     EHPrint("\e888888# \eAABBCC%03d-%03d-%03d-%03d\e4500F5: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:\e888888%#lx\n",
                             PMLIndex, 0, 0, 0,
                             PML4.Present ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                             PML4.ReadWrite ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                             PML4.UserSupervisor ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                             PML4.WriteThrough ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                             PML4.CacheDisable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                             PML4.Accessed ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                             PML4.ExecuteDisable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                             PML4.GetAddress() << 12);
                     Display->SetBuffer(SBIdx);
                     if (PML4.Present)
                     {
                         Memory::PageDirectoryPointerTableEntryPtr *PDPTE = (Memory::PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4.GetAddress() << 12);
                         if (PDPTE)
{
                             for (int PDPTEIndex = 0; PDPTEIndex < 512; PDPTEIndex++)
{
                                 EHPrint("\e888888# \eAABBCC%03d-%03d-%03d-%03d\e4500F5: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:\e888888%#lx\n",
                                         PMLIndex, PDPTEIndex, 0, 0,
                                         PDPTE->Entries[PDPTEIndex].Present ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                         PDPTE->Entries[PDPTEIndex].ReadWrite ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                         PDPTE->Entries[PDPTEIndex].UserSupervisor ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                         PDPTE->Entries[PDPTEIndex].WriteThrough ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                         PDPTE->Entries[PDPTEIndex].CacheDisable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                         PDPTE->Entries[PDPTEIndex].Accessed ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                         PDPTE->Entries[PDPTEIndex].ExecuteDisable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                         PDPTE->Entries[PDPTEIndex].GetAddress() << 12);
                                 Display->SetBuffer(SBIdx);
                                 if ((PDPTE->Entries[PDPTEIndex].Present))
{
                                     Memory::PageDirectoryEntryPtr *PDE = (Memory::PageDirectoryEntryPtr *)((uintptr_t)PDPTE->Entries[PDPTEIndex].GetAddress() << 12);
                                     if (PDE)
{
                                         for (int PDEIndex = 0; PDEIndex < 512; PDEIndex++)
{
                                             EHPrint("\e888888# \eAABBCC%03d-%03d-%03d-%03d\e4500F5: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:\e888888%#lx\n",
                                                     PMLIndex, PDPTEIndex, PDEIndex, 0,
                                                     PDE->Entries[PDEIndex].Present ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                     PDE->Entries[PDEIndex].ReadWrite ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                     PDE->Entries[PDEIndex].UserSupervisor ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                     PDE->Entries[PDEIndex].WriteThrough ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                     PDE->Entries[PDEIndex].CacheDisable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                     PDE->Entries[PDEIndex].Accessed ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                     PDE->Entries[PDEIndex].ExecuteDisable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                     PDE->Entries[PDEIndex].GetAddress() << 12);
                                             Display->SetBuffer(SBIdx);
                                             if ((PDE->Entries[PDEIndex].Present))
{
                                                 Memory::PageTableEntryPtr *PTE = (Memory::PageTableEntryPtr *)((uintptr_t)PDE->Entries[PDEIndex].GetAddress() << 12);
                                                 if (PTE)
{
                                                     for (int PTEIndex = 0; PTEIndex < 512; PTEIndex++)
{
                                                         EHPrint("\e888888# \eAABBCC%03d-%03d-%03d-%03d\e4500F5: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s D:%s PAT:%s G:%s PK:%d NX:%s Address:\e888888%#lx\n",
                                                                 PMLIndex, PDPTEIndex, PDEIndex, PTEIndex,
                                                                 PTE->Entries[PTEIndex].Present ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].ReadWrite ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].UserSupervisor ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].WriteThrough ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].CacheDisable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].Accessed ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].Dirty ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].PageAttributeTable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].Global ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].ProtectionKey,
                                                                 PTE->Entries[PTEIndex].ExecuteDisable ? "\e00FF001\e4500F5" : "\eFF00000\e4500F5",
                                                                 PTE->Entries[PTEIndex].GetAddress() << 12);
                                                         Display->SetBuffer(SBIdx);
                                                     }
                                                 }
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
         }
         else if (strncmp(Input, "bitmap", 6) == 0)
         {
             Bitmap bm = KernelAllocator.GetPageBitmap();
             EHPrint("\n\eFAFAFA[0%%] %08ld: ", 0);
             for (size_t i = 0; i < bm.Size; i++)
             {
                 if (bm.Get(i))
                     EHPrint("\eFF00001");
                 else
                     EHPrint("\e00FF000");
                 if (i % 128 == 127)
                 {
                     short Percentage = (i * 100) / bm.Size;
                     EHPrint("\n\eFAFAFA[%03ld%%] %08ld: ", Percentage, i);
                     Display->SetBuffer(SBIdx);
                 }
             }
             EHPrint("\n\e22AA44--- END OF BITMAP ---\nBitmap size: %ld\n\n.", bm.Size);
             Display->SetBuffer(SBIdx);
         }
         else if (strcmp(Input, "mem") == 0)
         {
             uint64_t Total = KernelAllocator.GetTotalMemory();
             uint64_t Used = KernelAllocator.GetUsedMemory();
             uint64_t Free = KernelAllocator.GetFreeMemory();
             uint64_t Reserved = KernelAllocator.GetReservedMemory();
             EHPrint("\e22AA44Total: %ld bytes\n\eFF0000Used: %ld bytes\n\e00FF00Free: %ld bytes\n\eFF00FFReserved: %ld bytes\n", Total, Used, Free, Reserved);
             int Progress = (Used * 100) / Total;
             int ReservedProgress = (Reserved * 100) / Total;
             EHPrint("\e22AA44%3d%% \eCCCCCC[", Progress);
             for (int i = 0; i < Progress; i++)
                 EHPrint("\eFF0000|");
             for (int i = 0; i < 100 - Progress; i++)
                 EHPrint("\e00FF00|");
             for (int i = 0; i < ReservedProgress; i++)
                 EHPrint("\eFF00FF|");
             EHPrint("\eCCCCCC]\n");
             Display->SetBuffer(SBIdx);
         }
         else if (strncmp(Input, "cr", 2) == 0)
         {
             char *cr = TrimWhiteSpace(Input + 2);
             switch (cr[0])
             {
             case '0':
             {
 #if defined(a64)
                 EHPrint("\e44AA000: %#lx\n", CPU::x64::readcr0());
 #elif defined(a32)
                 EHPrint("\e44AA000: %#lx\n", CPU::x32::readcr0());
 #endif
                 break;
             }
             case '2':
             {
 #if defined(a64)
                 EHPrint("\e44AA002: %#lx\n", PageFaultAddress);
 #elif defined(a32)
                 EHPrint("\e44AA002: %#lx\n", CPU::x32::readcr2());
 #endif
                 break;
             }
             case '3':
             {
 #if defined(a64)
                 EHPrint("\e44AA003: %#lx\n", CPU::x64::readcr3());
 #elif defined(a32)
                 EHPrint("\e44AA003: %#lx\n", CPU::x32::readcr3());
 #endif
                 break;
             }
             case '4':
             {
 #if defined(a64)
                 EHPrint("\e44AA004: %#lx\n", CPU::x64::readcr4());
 #elif defined(a32)
                 EHPrint("\e44AA004: %#lx\n", CPU::x32::readcr4());
 #endif
                 break;
             }
             case '8':
             {
 #if defined(a64)
                 EHPrint("\e44AA008: %#lx\n", CPU::x64::readcr8());
 #elif defined(a32)
                 EHPrint("\e44AA008: %#lx\n", CPU::x32::readcr8());
 #endif
                 break;
             }
             default:
                 EHPrint("\eFF0000Invalid CR\n");
                 break;
             }
         }
         else if (strncmp(Input, "tss", 3) == 0)
         {
             char *arg = TrimWhiteSpace(Input + 3);
             int TSSIndex = atoi(arg);
             if (TSSIndex > SMP::CPUCores)
             {
                 EHPrint("\eFF0000Invalid TSS index\n");
             }
             else
             {
                 GlobalDescriptorTable::TaskStateSegment tss = GlobalDescriptorTable::tss[TSSIndex];
                 EHPrint("\eFAFAFAStack Pointer 0: \eAABB22%#lx\n", tss.StackPointer[0]);
                 EHPrint("\eFAFAFAStack Pointer 1: \eAABB22%#lx\n", tss.StackPointer[1]);
                 EHPrint("\eFAFAFAStack Pointer 2: \eAABB22%#lx\n", tss.StackPointer[2]);
                 EHPrint("\eFAFAFAInterrupt Stack Table: \eAABB22%#lx\n", tss.InterruptStackTable[0]);
                 EHPrint("\eFAFAFAInterrupt Stack Table: \eAABB22%#lx\n", tss.InterruptStackTable[1]);
                 EHPrint("\eFAFAFAInterrupt Stack Table: \eAABB22%#lx\n", tss.InterruptStackTable[2]);
                 EHPrint("\eFAFAFAInterrupt Stack Table: \eAABB22%#lx\n", tss.InterruptStackTable[3]);
                 EHPrint("\eFAFAFAInterrupt Stack Table: \eAABB22%#lx\n", tss.InterruptStackTable[4]);
                 EHPrint("\eFAFAFAInterrupt Stack Table: \eAABB22%#lx\n", tss.InterruptStackTable[5]);
                 EHPrint("\eFAFAFAInterrupt Stack Table: \eAABB22%#lx\n", tss.InterruptStackTable[6]);
                 EHPrint("\eFAFAFAI/O Map Base Address Offset: \eAABB22%#lx\n", tss.IOMapBaseAddressOffset);
                 EHPrint("\eFAFAFAReserved 0: \eAABB22%#lx\n", tss.Reserved0);
                 EHPrint("\eFAFAFAReserved 1: \eAABB22%#lx\n", tss.Reserved1);
                 EHPrint("\eFAFAFAReserved 2: \eAABB22%#lx\n", tss.Reserved2);
             }
         }
         else if (strncmp(Input, "dump", 4) == 0)
         {
             char *arg = TrimWhiteSpace(Input + 4);
             char *addr = strtok(arg, " ");
             char *len = strtok(NULL, " ");
             if (addr == NULL || len == NULL)
             {
                 EHPrint("\eFF0000Invalid arguments\n");
             }
             else
             {
                 uint64_t Address = strtoul(addr, NULL, 16);
                 uint64_t Length = strtoul(len, NULL, 10);
                 debug("Dumping %ld bytes from %#lx\n", Length, Address);
                 EHDumpData((void *)Address, Length);
             }
         }
         else if (strncmp(Input, "uartmemdmp", 10) == 0)
         {
             char *arg = TrimWhiteSpace(Input + 10);
             char *cPort = strtok(arg, " ");
             char *cBoolSkip = strtok(NULL, " ");
             UniversalAsynchronousReceiverTransmitter::SerialPorts port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM1;
             switch (cPort[0])
             {
             case '1':
                 port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM1;
                 break;
             case '2':
                 port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM2;
                 break;
             case '3':
                 port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM3;
                 break;
             case '4':
                 port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM4;
                 break;
             case '5':
                 port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM5;
                 break;
             case '6':
                 port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM6;
                 break;
             case '7':
                 port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM7;
                 break;
             case '8':
                 port = UniversalAsynchronousReceiverTransmitter::SerialPorts::COM8;
                 break;
             default:
                 EHPrint("\eFF0000Invalid port! Defaulting to 1.\n");
                 break;
             }
             EHPrint("\eF8F8F8Dumping memory to UART port %c (%#lx) and %s inaccessible pages.\n", cPort[0], port, cBoolSkip[0] == '1' ? "skipping" : "zeroing");
             Display->SetBuffer(SBIdx);
             uint64_t Length = KernelAllocator.GetTotalMemory();
             uint64_t ProgressLength = Length;
             UniversalAsynchronousReceiverTransmitter::UART uart(port);
             Memory::Virtual vma;
             uint8_t *Address = reinterpret_cast<uint8_t *>(0x0);
             int Progress = 0;
             for (size_t i = 0; i < Length; i++)
             {
                 if (vma.Check(Address))
                     uart.Write(*Address);
                 else if (cBoolSkip[0] == '0')
                     uart.Write((uint8_t)0);
                 else
                     ProgressLength--;
                 Address++;
                 if (unlikely(i % 0x1000 == 0))
                 {
                     int NewProgress = (i * 100) / ProgressLength;
                     if (unlikely(NewProgress != Progress))
                     {
                         Progress = NewProgress;
                         EHPrint("\n%d%%\n", Progress);
                         Display->SetBuffer(SBIdx);
                     }
                     Display->Print('.', SBIdx);
                     if (unlikely(i % 0x500 == 0))
                         Display->SetBuffer(SBIdx);
                 }
             }
             EHPrint("\nDone.\n");
         }
         else if (strcmp(Input, "main") == 0)
         {
             SBIdx = 255;
             DisplayTopOverlay();
             DisplayMainScreen(crashdata);
             Display->SetBuffer(SBIdx);
         }
         else if (strcmp(Input, "details") == 0)
         {
             SBIdx = 254;
             DisplayTopOverlay();
             DisplayDetailsScreen(crashdata);
             Display->SetBuffer(SBIdx);
         }
         else if (strcmp(Input, "frames") == 0)
         {
             SBIdx = 253;
             DisplayTopOverlay();
             DisplayStackFrameScreen(crashdata);
             Display->SetBuffer(SBIdx);
         }
         else if (strcmp(Input, "tasks") == 0)
         {
             SBIdx = 252;
             DisplayTopOverlay();
             DisplayTasksScreen(crashdata);
             Display->SetBuffer(SBIdx);
         }
         else if (strcmp(Input, "console") == 0)
         {
             SBIdx = 251;
             DisplayTopOverlay();
             DisplayConsoleScreen(crashdata);
             Display->SetBuffer(SBIdx);
         }
         else if (strlen(Input) > 0)
             EHPrint("Unknown command: %s", Input);
         DisplayBottomOverlay();
         Display->SetBuffer(SBIdx);
     }
References Address, mlibc::arg, atoi(), Check(), UniversalAsynchronousReceiverTransmitter::COM1, UniversalAsynchronousReceiverTransmitter::COM2, UniversalAsynchronousReceiverTransmitter::COM3, UniversalAsynchronousReceiverTransmitter::COM4, UniversalAsynchronousReceiverTransmitter::COM5, UniversalAsynchronousReceiverTransmitter::COM6, UniversalAsynchronousReceiverTransmitter::COM7, UniversalAsynchronousReceiverTransmitter::COM8, SMP::CPUCores, crashdata, debug, Display, DisplayBottomOverlay(), DisplayConsoleScreen(), DisplayDetailsScreen(), DisplayMainScreen(), DisplayStackFrameScreen(), DisplayTasksScreen(), DisplayTopOverlay(), EHDumpData(), EHIntFrames, EHPrint(), Bitmap::Get(), SymbolResolver::Symbols::GetSymbolFromAddress(), i, KernelAllocator, KernelSymbolTable, Length, NULL, PageFaultAddress, PowerManager, Power::Power::Reboot(), Reserved, SBIdx, Power::Power::Shutdown(), Bitmap::Size, CPU::Stop(), strcmp(), strlen(), strncmp(), strtok(), strtol(), strtoul(), TaskStateSegment, TrimWhiteSpace(), GlobalDescriptorTable::tss, unlikely, and UniversalAsynchronousReceiverTransmitter::UART::Write().
Referenced by if().
Variable Documentation
BackSpaceLimit
int CrashHandler::BackSpaceLimit = 0
Definition at line 102 of file KBDrv.cpp.
Referenced by if().
crashdata
CRData CrashHandler::crashdata = {}
Definition at line 101 of file CrashHandler.cpp.
Referenced by ArrowInput(), Handle(), and UserInput().
EHIntFrames
void * CrashHandler::EHIntFrames
Definition at line 33 of file CrashHandler.cpp.
Referenced by DisplayStackFrameScreen(), Handle(), and UserInput().
ExceptionOccurred
bool CrashHandler::ExceptionOccurred = false static
Definition at line 34 of file CrashHandler.cpp.
Referenced by Handle().
key
int CrashHandler::key = GetLetterFromScanCode(scanCode)
Definition at line 131 of file KBDrv.cpp.
Referenced by addKeyToQueue(), AM_Responder(), ArrowInput(), bsearch(), check_key(), cht_CheckCheat(), std::unordered_map< key_type, value_type >::contains(), convertToDoomKey(), free_key(), G_BuildTiccmd(), GenerateTextureHashTable(), GetTypedChar(), std::unordered_map< key_type, value_type >::hash(), I_GetEvent(), if(), IsNullKey(), lfind(), lsearch(), M_EndGameResponse(), M_QuickLoadResponse(), M_QuickSaveResponse(), M_QuitResponse(), M_Responder(), M_VerifyNightmare(), main(), mus2mid(), std::hash< Key >::operator()(), std::unordered_map< key_type, value_type >::operator[](), pthread_getspecific(), pthread_key_create(), pthread_key_delete(), pthread_setspecific(), R_CheckTextureNumForName(), tfind(), TranslateKey(), tsearch(), UpdateShiftStatus(), worker2(), WritePressKey(), and WriteReleaseKey().
PageFaultAddress
uintptr_t CrashHandler::PageFaultAddress = 0
Definition at line 32 of file CrashHandler.cpp.
Referenced by DisplayMainScreen(), Handle(), PageFaultExceptionHandler(), UserInput(), and UserModeExceptionHandler().
SBIdx
int CrashHandler::SBIdx = 255
Definition at line 35 of file CrashHandler.cpp.
Referenced by ArrowInput(), DisplayBottomOverlay(), DisplayTopOverlay(), EHDumpData(), Handle(), if(), printfWrapper(), and UserInput().
scanCode
uint8_t CrashHandler::scanCode = inb(0x60)
Definition at line 114 of file KBDrv.cpp.
Referenced by switch().
UserInputBuffer
char CrashHandler::UserInputBuffer[1024] static
Definition at line 103 of file KBDrv.cpp.
Referenced by if().