Fennix Userspace: Userspace/apps/base/busybox/libbb/ask_confirmation.c File Reference
ask_confirmation.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC bb_ask_y_confirmation_FILE (FILE *fp)
int FAST_FUNC bb_ask_y_confirmation (void)
Function Documentation
bb_ask_y_confirmation()
int FAST_FUNC bb_ask_y_confirmation (void)
Definition at line 29 of file ask_confirmation.c.
 {
     return bb_ask_y_confirmation_FILE(stdin);
 }
References bb_ask_y_confirmation_FILE(), and stdin.
Referenced by ask_and_unlink(), confirm_or_abort(), mv_main(), and remove_file().
bb_ask_y_confirmation_FILE()
int FAST_FUNC bb_ask_y_confirmation_FILE (FILE * fp)
Definition at line 14 of file ask_confirmation.c.
 {
     char first = 0;
     int c;
     fflush_all();
     while (((c = fgetc(fp)) != EOF) && (c != '\n')) {
         if (first == 0 && !isblank(c)) {
             first = c|0x20;
         }
     }
     return first == 'y';
 }
References c, EOF, fflush_all(), fgetc, first, and isblank.
Referenced by bb_ask_y_confirmation().