Fennix Userspace: Userspace/mlibc/options/posix/include/sched.h File Reference
sched.h File Reference
#include <abi-bits/pid_t.h>
#include <bits/size_t.h>
Data Structures
struct sched_param
struct __mlibc_cpu_set
Macros
#define CLONE_VM 0x00000100
#define CLONE_FS 0x00000200
#define CLONE_FILES 0x00000400
#define CLONE_SIGHAND 0x00000800
#define CLONE_PTRACE 0x00002000
#define CLONE_VFORK 0x00004000
#define CLONE_PARENT 0x00008000
#define CLONE_THREAD 0x00010000
#define CLONE_NEWNS 0x00020000
#define CLONE_SYSVSEM 0x00040000
#define CLONE_SETTLS 0x00080000
#define CLONE_PARENT_SETTID 0x00100000
#define CLONE_CHILD_CLEARTID 0x00200000
#define CLONE_DETACHED 0x00400000
#define CLONE_UNTRACED 0x00800000
#define CLONE_CHILD_SETTID 0x01000000
#define CLONE_NEWCGROUP 0x02000000
#define CLONE_NEWUTS 0x04000000
#define CLONE_NEWIPC 0x08000000
#define CLONE_NEWUSER 0x10000000
#define CLONE_NEWPID 0x20000000
#define CLONE_NEWNET 0x40000000
#define CLONE_IO 0x80000000
#define CPU_SETSIZE 128
#define CPU_ISSET __mlibc_cpu_isset
#define CPU_COUNT __mlibc_cpu_count
#define SCHED_OTHER 0
#define SCHED_FIFO 1
#define SCHED_RR 2
#define SCHED_BATCH 3
#define SCHED_IDLE 5
#define SCHED_DEADLINE 6
#define SCHED_RESET_ON_FORK 0x40000000
Typedefs
typedef struct __mlibc_cpu_set cpu_set_t
Functions
int sched_yield ()
int sched_getaffinity (pid_t pid, size_t cpusetsize, cpu_set_t *mask)
int sched_get_priority_max (int policy)
int sched_get_priority_min (int policy)
int unshare (int flags)
int __mlibc_cpu_isset (int cpu, cpu_set_t *set)
int __mlibc_cpu_count (cpu_set_t *set)
int clone (int(*)(void *), void *, int, void *,...)
Data Structure Documentation
sched_param
struct sched_param
Definition at line 4 of file struct_sched_param.h.
Data Fields
int __reserved1
struct sched_param __reserved2[2]
int __reserved3
int sched_priority
__mlibc_cpu_set
struct __mlibc_cpu_set
Definition at line 58 of file sched.h.
Data Fields
unsigned long __bits[128/sizeof(long)]
Macro Definition Documentation
CLONE_CHILD_CLEARTID
#define CLONE_CHILD_CLEARTID 0x00200000
Definition at line 24 of file sched.h.
CLONE_CHILD_SETTID
#define CLONE_CHILD_SETTID 0x01000000
Definition at line 27 of file sched.h.
CLONE_DETACHED
#define CLONE_DETACHED 0x00400000
Definition at line 25 of file sched.h.
CLONE_FILES
#define CLONE_FILES 0x00000400
Definition at line 14 of file sched.h.
CLONE_FS
#define CLONE_FS 0x00000200
Definition at line 13 of file sched.h.
CLONE_IO
#define CLONE_IO 0x80000000
Definition at line 34 of file sched.h.
CLONE_NEWCGROUP
#define CLONE_NEWCGROUP 0x02000000
Definition at line 28 of file sched.h.
CLONE_NEWIPC
#define CLONE_NEWIPC 0x08000000
Definition at line 30 of file sched.h.
CLONE_NEWNET
#define CLONE_NEWNET 0x40000000
Definition at line 33 of file sched.h.
CLONE_NEWNS
#define CLONE_NEWNS 0x00020000
Definition at line 20 of file sched.h.
CLONE_NEWPID
#define CLONE_NEWPID 0x20000000
Definition at line 32 of file sched.h.
CLONE_NEWUSER
#define CLONE_NEWUSER 0x10000000
Definition at line 31 of file sched.h.
CLONE_NEWUTS
#define CLONE_NEWUTS 0x04000000
Definition at line 29 of file sched.h.
CLONE_PARENT
#define CLONE_PARENT 0x00008000
Definition at line 18 of file sched.h.
CLONE_PARENT_SETTID
#define CLONE_PARENT_SETTID 0x00100000
Definition at line 23 of file sched.h.
CLONE_PTRACE
#define CLONE_PTRACE 0x00002000
Definition at line 16 of file sched.h.
CLONE_SETTLS
#define CLONE_SETTLS 0x00080000
Definition at line 22 of file sched.h.
CLONE_SIGHAND
#define CLONE_SIGHAND 0x00000800
Definition at line 15 of file sched.h.
CLONE_SYSVSEM
#define CLONE_SYSVSEM 0x00040000
Definition at line 21 of file sched.h.
CLONE_THREAD
#define CLONE_THREAD 0x00010000
Definition at line 19 of file sched.h.
CLONE_UNTRACED
#define CLONE_UNTRACED 0x00800000
Definition at line 26 of file sched.h.
CLONE_VFORK
#define CLONE_VFORK 0x00004000
Definition at line 17 of file sched.h.
CLONE_VM
#define CLONE_VM 0x00000100
Definition at line 12 of file sched.h.
CPU_COUNT
#define CPU_COUNT __mlibc_cpu_count
Definition at line 38 of file sched.h.
CPU_ISSET
#define CPU_ISSET __mlibc_cpu_isset
Definition at line 37 of file sched.h.
CPU_SETSIZE
#define CPU_SETSIZE 128
Definition at line 36 of file sched.h.
SCHED_BATCH
#define SCHED_BATCH 3
Definition at line 47 of file sched.h.
SCHED_DEADLINE
#define SCHED_DEADLINE 6
Definition at line 49 of file sched.h.
SCHED_FIFO
#define SCHED_FIFO 1
Definition at line 45 of file sched.h.
SCHED_IDLE
#define SCHED_IDLE 5
Definition at line 48 of file sched.h.
SCHED_OTHER
#define SCHED_OTHER 0
Definition at line 44 of file sched.h.
SCHED_RESET_ON_FORK
#define SCHED_RESET_ON_FORK 0x40000000
Definition at line 50 of file sched.h.
SCHED_RR
#define SCHED_RR 2
Definition at line 46 of file sched.h.
Typedef Documentation
cpu_set_t
typedef struct __mlibc_cpu_set cpu_set_t
Definition at line 56 of file sched.h.
Function Documentation
__mlibc_cpu_count()
int __mlibc_cpu_count (cpu_set_t * set)
Definition at line 38 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
__mlibc_cpu_isset()
int __mlibc_cpu_isset (int cpu, cpu_set_t * set)
Definition at line 33 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
clone()
int clone (int(*)(void *) func, void * stack, int flags, void * arg, ...)
Definition at line 48 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __clone(), __ensure, __syscall_ret(), flags, mlibc::stack, va_arg, va_end(), and va_start().
sched_get_priority_max()
int sched_get_priority_max (int policy)
Definition at line 23 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
sched_get_priority_min()
int sched_get_priority_min (int policy)
Definition at line 28 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
sched_getaffinity()
int sched_getaffinity (pid_t pid, size_t cpusetsize, cpu_set_t * mask)
Definition at line 18 of file sched-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31mmlibc: sched_getaffinity() always fails\e[39m" << frg::endlog;
     return -1;
 }
References __syscall_ret(), do_getaffinity(), mlibc::infoLogger, and size.
sched_yield()
int sched_yield ()
Definition at line 8 of file sched-stubs.cpp.
                       {
     if(mlibc::sys_yield) {
         mlibc::sys_yield();
     }else{
         // Missing sched_yield() is not an error.
         MLIBC_MISSING_SYSDEP();
     }
     return 0;
 }
unshare()
int unshare (int flags)
Definition at line 43 of file sched-stubs.cpp.
                  {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, flags, and syscall().