Fennix: Userspace/apps/base/busybox/coreutils/expand.c File Reference
expand.c File Reference
#include "libbb.h"
#include "unicode.h"
Enumerations
enum { OPT_INITIAL = 1 << 0 , OPT_TABS = 1 << 1 , OPT_ALL = 1 << 2 }
Functions
int expand_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_INITIAL
OPT_TABS
OPT_ALL
Definition at line 60 of file expand.c.
      {
     OPT_INITIAL     = 1 << 0,
     OPT_TABS        = 1 << 1,
     OPT_ALL         = 1 << 2,
 };
Function Documentation
expand_main()
int expand_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 188 of file expand.c.
 {
     /* Default 8 spaces for 1 tab */
     const char *opt_t = "8";
     FILE *file;
     unsigned tab_size;
     unsigned opt;
     int exit_status = EXIT_SUCCESS;
     init_unicode();
     if (ENABLE_EXPAND && (!ENABLE_UNEXPAND || applet_name[0] == 'e')) {
         opt = getopt32long(argv, "it:",
                 "initial\0"          No_argument       "i"
                 "tabs\0"             Required_argument "t"
                 , &opt_t
         );
     } else {
         opt = getopt32long(argv, "^"
                 "ft:a"
                 "\0"
                 "ta" /* -t NUM sets -a */,
                 "first-only\0"       No_argument       "f"
                 "tabs\0"             Required_argument "t"
                 "all\0"              No_argument       "a"
                 , &opt_t
         );
         /* -t implies -a, but an explicit -f overrides */
         if (opt & OPT_INITIAL) opt &= ~OPT_ALL;
     }
     tab_size = xatou_range(opt_t, 1, UINT_MAX);
     argv += optind;
     if (!*argv) {
         *--argv = (char*)bb_msg_standard_input;
     }
     do {
         file = fopen_or_warn_stdin(*argv);
         if (!file) {
             exit_status = EXIT_FAILURE;
             continue;
         }
         if (ENABLE_EXPAND && (!ENABLE_UNEXPAND || applet_name[0] == 'e'))
             IF_EXPAND(expand(file, tab_size, opt));
         else
             IF_UNEXPAND(unexpand(file, tab_size, opt));
         /* Check and close the file */
         if (fclose_if_not_stdin(file)) {
             bb_simple_perror_msg(*argv);
             exit_status = EXIT_FAILURE;
         }
         /* If stdin also clear EOF */
         if (file == stdin)
             clearerr(file);
     } while (*++argv);
     /* Now close stdin also */
     /* (if we didn't read from it, it's a no-op) */
     if (fclose(stdin))
         bb_simple_perror_msg_and_die(bb_msg_standard_input);
     fflush_stdout_and_exit(exit_status);
 }
References applet_name, argv, bb_simple_perror_msg(), bb_simple_perror_msg_and_die(), clearerr(), EXIT_FAILURE, exit_status, EXIT_SUCCESS, expand(), fclose(), fclose_if_not_stdin(), fflush_stdout_and_exit(), fopen_or_warn_stdin(), getopt32long, init_unicode, No_argument, opt, OPT_ALL, OPT_INITIAL, optind, Required_argument, stdin, and UINT_MAX.