Fennix: Userspace/apps/base/bash/hashlib.c File Reference
hashlib.c File Reference
#include <config.h>
#include "bashansi.h"
#include <stdio.h>
#include "shell.h"
#include "hashlib.h"
Macros
#define HASH_REHASH_MULTIPLIER 4
#define HASH_REHASH_FACTOR 2
#define HASH_SHOULDGROW(table) ((table)->nentries >= (table)->nbuckets * HASH_REHASH_FACTOR)
#define HASH_SHOULDSHRINK(table)
#define HASH_BUCKET(s, t, h) (((h) = hash_string (s)) & ((t)->nbuckets - 1))
#define FNV_OFFSET 2166136261
#define FNV_PRIME 16777619
Functions
static BUCKET_CONTENTS *copy_bucket_array PARAMS ((BUCKET_CONTENTS *, sh_string_func_t *))
static void hash_rehash PARAMS ((HASH_TABLE *, int))
static void hash_grow PARAMS ((HASH_TABLE *))
HASH_TABLE * hash_create (int buckets)
int hash_size (HASH_TABLE *table)
static BUCKET_CONTENTS * copy_bucket_array (BUCKET_CONTENTS *ba, sh_string_func_t *cpdata)
static void hash_rehash (HASH_TABLE *table, int nsize)
static void hash_grow (HASH_TABLE *table)
static void hash_shrink (HASH_TABLE *table)
HASH_TABLE * hash_copy (HASH_TABLE *table, sh_string_func_t *cpdata)
unsigned int hash_string (char *s) const
int hash_bucket (char *string, HASH_TABLE *table) const
BUCKET_CONTENTS * hash_search (char *string, HASH_TABLE *table, int flags) const
BUCKET_CONTENTS * hash_remove (char *string, HASH_TABLE *table, int flags) const
BUCKET_CONTENTS * hash_insert (char *string, HASH_TABLE *table, int flags)
void hash_flush (HASH_TABLE *table, sh_free_func_t *free_data)
void hash_dispose (HASH_TABLE *table)
void hash_walk (HASH_TABLE *table, hash_wfunc *func)
Macro Definition Documentation
FNV_OFFSET
#define FNV_OFFSET 2166136261
Definition at line 204 of file hashlib.c.
FNV_PRIME
#define FNV_PRIME 16777619
Definition at line 205 of file hashlib.c.
HASH_BUCKET
#define HASH_BUCKET (s, t, h) (((h) = hash_string (s)) & ((t)->nbuckets - 1))
Definition at line 51 of file hashlib.c.
HASH_REHASH_FACTOR
#define HASH_REHASH_FACTOR 2
Definition at line 39 of file hashlib.c.
HASH_REHASH_MULTIPLIER
#define HASH_REHASH_MULTIPLIER 4
Definition at line 38 of file hashlib.c.
HASH_SHOULDGROW
#define HASH_SHOULDGROW (table) ((table)->nentries >= (table)->nbuckets * HASH_REHASH_FACTOR)
Definition at line 41 of file hashlib.c.
HASH_SHOULDSHRINK
#define HASH_SHOULDSHRINK (table)
Value:
  (((table)->nbuckets > DEFAULT_HASH_BUCKETS) && \
   ((table)->nentries < (table)->nbuckets / HASH_REHASH_MULTIPLIER))
Definition at line 45 of file hashlib.c.
Function Documentation
copy_bucket_array()
static BUCKET_CONTENTS* copy_bucket_array (BUCKET_CONTENTS * ba, sh_string_func_t * cpdata) static
Definition at line 91 of file hashlib.c.
 {
   BUCKET_CONTENTS *new_bucket, *n, *e;
   if (ba == 0)
     return ((BUCKET_CONTENTS *)0);
   for (n = (BUCKET_CONTENTS *)0, e = ba; e; e = e->next)
     {
       if (n == 0)
         {
           new_bucket = (BUCKET_CONTENTS *)xmalloc (sizeof (BUCKET_CONTENTS));
           n = new_bucket;
         }
       else
         {
           n->next = (BUCKET_CONTENTS *)xmalloc (sizeof (BUCKET_CONTENTS));
           n = n->next;
         }
       n->key = savestring (e->key);
       n->data = e->data ? (cpdata ? (*cpdata) (e->data) : savestring (e->data))
             : NULL;
       n->khash = e->khash;
       n->times_found = e->times_found;
       n->next = (BUCKET_CONTENTS *)NULL;
     }
   return new_bucket;
 }
References bucket_contents::data, bucket_contents::key, bucket_contents::khash, n, bucket_contents::next, NULL, savestring(), bucket_contents::times_found, and xmalloc.
Referenced by hash_copy().
hash_bucket()
int hash_bucket (char * string, HASH_TABLE * table) const
Definition at line 236 of file hashlib.c.
 {
   unsigned int h;
   return (HASH_BUCKET (string, table, h));
 }
References HASH_BUCKET, and table.
hash_copy()
HASH_TABLE* hash_copy (HASH_TABLE * table, sh_string_func_t * cpdata)
Definition at line 179 of file hashlib.c.
 {
   HASH_TABLE *new_table;
   int i;
   if (table == 0)
     return ((HASH_TABLE *)NULL);
   new_table = hash_create (table->nbuckets);
   for (i = 0; i < table->nbuckets; i++)
     new_table->bucket_array[i] = copy_bucket_array (table->bucket_array[i], cpdata);
   new_table->nentries = table->nentries;
   return new_table;
 }
References hash_table::bucket_array, copy_bucket_array(), hash_create(), i, hash_table::nentries, NULL, and table.
hash_create()
HASH_TABLE* hash_create (int buckets)
Definition at line 62 of file hashlib.c.
 {
   HASH_TABLE *new_table;
   register int i;
   new_table = (HASH_TABLE *)xmalloc (sizeof (HASH_TABLE));
   if (buckets == 0)
     buckets = DEFAULT_HASH_BUCKETS;
   new_table->bucket_array =
     (BUCKET_CONTENTS **)xmalloc (buckets * sizeof (BUCKET_CONTENTS *));
   new_table->nbuckets = buckets;
   new_table->nentries = 0;
   for (i = 0; i < buckets; i++)
     new_table->bucket_array[i] = (BUCKET_CONTENTS *)NULL;
   return (new_table);
 }
References hash_table::bucket_array, DEFAULT_HASH_BUCKETS, i, hash_table::nbuckets, hash_table::nentries, NULL, and xmalloc.
Referenced by assign_in_env(), bind_invalid_envvar(), create_variable_tables(), hash_copy(), hash_insert(), make_local_variable(), phash_create(), push_posix_tempvar_internal(), and push_temp_var().
hash_dispose()
void hash_dispose (HASH_TABLE * table)
Definition at line 409 of file hashlib.c.
 {
   free (table->bucket_array);
   free (table);
 }
References free, and table.
Referenced by dispose_temporary_env(), dispose_var_context(), flush_temporary_env(), kill_all_local_variables(), and pop_scope().
hash_flush()
void hash_flush (HASH_TABLE * table, sh_free_func_t * free_data)
Definition at line 375 of file hashlib.c.
 {
   int i;
   register BUCKET_CONTENTS *bucket, *item;
   if (table == 0 || HASH_ENTRIES (table) == 0)
     return;
   for (i = 0; i < table->nbuckets; i++)
     {
       bucket = table->bucket_array[i];
       while (bucket)
     {
       item = bucket;
       bucket = bucket->next;
       if (free_data)
         (*free_data) (item->data);
       else
         free (item->data);
       free (item->key);
       free (item);
     }
       table->bucket_array[i] = (BUCKET_CONTENTS *)NULL;
     }
   table->nentries = 0;
 }
References bucket_contents::data, free, HASH_ENTRIES, i, bucket_contents::key, bucket_contents::next, NULL, and table.
Referenced by delete_all_variables(), dispose_temporary_env(), flush_temporary_env(), phash_flush(), pop_scope(), and pop_var_context().
hash_grow()
static void hash_grow (HASH_TABLE * table) static
Definition at line 158 of file hashlib.c.
 {
   int nsize;
   nsize = table->nbuckets * HASH_REHASH_MULTIPLIER;
   if (nsize > 0)        /* overflow */
     hash_rehash (table, nsize);
 }
References hash_rehash(), HASH_REHASH_MULTIPLIER, and table.
Referenced by hash_insert(), and hash_search().
hash_insert()
BUCKET_CONTENTS* hash_insert (char * string, HASH_TABLE * table, int flags)
Definition at line 334 of file hashlib.c.
 {
   BUCKET_CONTENTS *item;
   int bucket;
   unsigned int hv;
   if (table == 0)
     table = hash_create (0);
   item = (flags & HASH_NOSRCH) ? (BUCKET_CONTENTS *)NULL
                    : hash_search (string, table, 0);
   if (item == 0)
     {
       if (HASH_SHOULDGROW (table))
     hash_grow (table);
       bucket = HASH_BUCKET (string, table, hv);
       item = (BUCKET_CONTENTS *)xmalloc (sizeof (BUCKET_CONTENTS));
       item->next = table->bucket_array[bucket];
       table->bucket_array[bucket] = item;
       item->data = NULL;
       item->key = string;
       item->khash = hv;
       item->times_found = 0;
       table->nentries++;
     }
   return (item);
 }
References bucket_contents::data, flags, HASH_BUCKET, hash_create(), hash_grow(), HASH_NOSRCH, hash_search(), HASH_SHOULDGROW, bucket_contents::key, bucket_contents::khash, bucket_contents::next, NULL, string, table, bucket_contents::times_found, and xmalloc.
Referenced by bind_function(), make_new_variable(), makunbound(), and phash_insert().
hash_rehash()
static void hash_rehash (HASH_TABLE * table, int nsize) static
Definition at line 125 of file hashlib.c.
 {
   int osize, i, j;
   BUCKET_CONTENTS **old_bucket_array, *item, *next;
   if (table == NULL || nsize == table->nbuckets)
     return;
   osize = table->nbuckets;
   old_bucket_array = table->bucket_array;
   table->nbuckets = nsize;
   table->bucket_array = (BUCKET_CONTENTS **)xmalloc (table->nbuckets * sizeof (BUCKET_CONTENTS *));
   for (i = 0; i < table->nbuckets; i++)
     table->bucket_array[i] = (BUCKET_CONTENTS *)NULL;
   for (j = 0; j < osize; j++)
     {
       for (item = old_bucket_array[j]; item; item = next)
     {
       next = item->next;
       i = item->khash & (table->nbuckets - 1);
       item->next = table->bucket_array[i];
       table->bucket_array[i] = item;
     }
     }
   free (old_bucket_array);
 }
References free, i, j, bucket_contents::khash, bucket_contents::next, NULL, table, and xmalloc.
Referenced by hash_grow(), and hash_shrink().
hash_remove()
BUCKET_CONTENTS* hash_remove (char * string, HASH_TABLE * table, int flags) const
Definition at line 300 of file hashlib.c.
 {
   int bucket;
   BUCKET_CONTENTS *prev, *temp;
   unsigned int hv;
   if (table == 0 || HASH_ENTRIES (table) == 0)
     return (BUCKET_CONTENTS *)NULL;
   bucket = HASH_BUCKET (string, table, hv);
   prev = (BUCKET_CONTENTS *)NULL;
   for (temp = table->bucket_array[bucket]; temp; temp = temp->next)
     {
       if (hv == temp->khash && STREQ (temp->key, string))
     {
       if (prev)
         prev->next = temp->next;
       else
         table->bucket_array[bucket] = temp->next;
       table->nentries--;
       return (temp);
     }
       prev = temp;
     }
   return ((BUCKET_CONTENTS *) NULL);
 }
References HASH_BUCKET, HASH_ENTRIES, bucket_contents::key, bucket_contents::khash, bucket_contents::next, NULL, STREQ, and table.
Referenced by delete_var(), makunbound(), phash_remove(), and unbind_func().
hash_search()
BUCKET_CONTENTS* hash_search (char * string, HASH_TABLE * table, int flags) const
Definition at line 248 of file hashlib.c.
 {
   BUCKET_CONTENTS *list;
   int bucket;
   unsigned int hv;
   if (table == 0 || ((flags & HASH_CREATE) == 0 && HASH_ENTRIES (table) == 0))
     return (BUCKET_CONTENTS *)NULL;
   bucket = HASH_BUCKET (string, table, hv);
   for (list = table->bucket_array ? table->bucket_array[bucket] : 0; list; list = list->next)
     {
       /* This is the comparison function */
       if (hv == list->khash && STREQ (list->key, string))
     {
       list->times_found++;
       return (list);
     }
     }
   if (flags & HASH_CREATE)
     {
       if (HASH_SHOULDGROW (table))
     {
       hash_grow (table);
       bucket = HASH_BUCKET (string, table, hv);
     }
       list = (BUCKET_CONTENTS *)xmalloc (sizeof (BUCKET_CONTENTS));
       list->next = table->bucket_array[bucket];
       table->bucket_array[bucket] = list;
       list->data = NULL;
       list->key = (char *)string;   /* XXX fix later */
       list->khash = hv;
       list->times_found = 0;
       table->nentries++;
       return (list);
     }
   return (BUCKET_CONTENTS *)NULL;
 }
References bucket_contents::data, flags, HASH_BUCKET, HASH_CREATE, HASH_ENTRIES, hash_grow(), HASH_SHOULDGROW, bucket_contents::key, bucket_contents::khash, bucket_contents::next, NULL, STREQ, table, bucket_contents::times_found, and xmalloc.
Referenced by hash_insert(), hash_lookup(), and phash_search().
hash_shrink()
static void hash_shrink (HASH_TABLE * table) static
Definition at line 169 of file hashlib.c.
 {
   int nsize;
   nsize = table->nbuckets / HASH_REHASH_MULTIPLIER;
   hash_rehash (table, nsize);
 }
References hash_rehash(), HASH_REHASH_MULTIPLIER, and table.
hash_size()
int hash_size (HASH_TABLE * table)
Definition at line 84 of file hashlib.c.
 {
   return (HASH_ENTRIES(table));
 }
References HASH_ENTRIES, and table.
Referenced by _nl_load_domain().
hash_string()
unsigned int hash_string (char * s) const
Definition at line 215 of file hashlib.c.
 {
   register unsigned int i;
   for (i = FNV_OFFSET; *s; s++)
     {
       /* FNV-1a has the XOR first, traditional FNV-1 has the multiply first */
       /* was i *= FNV_PRIME */
       i += (i<<1) + (i<<4) + (i<<7) + (i<<8) + (i<<24);
       i ^= *s;
     }
   return i;
 }
References FNV_OFFSET, and i.
Referenced by _nl_find_msg(), and _nl_load_domain().
hash_walk()
void hash_walk (HASH_TABLE * table, hash_wfunc * func)
Definition at line 417 of file hashlib.c.
 {
   register int i;
   BUCKET_CONTENTS *item;
   if (table == 0 || HASH_ENTRIES (table) == 0)
     return;
   for (i = 0; i < table->nbuckets; i++)
     {
       for (item = hash_items (i, table); item; item = item->next)
     if ((*func) (item) < 0)
       return;
     }
 }
References HASH_ENTRIES, hash_items, i, bucket_contents::next, and table.
PARAMS() [1/3]
static BUCKET_CONTENTS* copy_bucket_array PARAMS ((BUCKET_CONTENTS *, sh_string_func_t *)) static
PARAMS() [2/3]
static void hash_grow PARAMS ((HASH_TABLE *)) static
PARAMS() [3/3]
static void hash_rehash PARAMS ((HASH_TABLE *, int)) static