Fennix Userspace: Userspace/apps/base/busybox/miscutils/beep.c File Reference
beep.c File Reference
#include "libbb.h"
#include <linux/kd.h>
Macros
#define CLOCK_TICK_RATE 1193180
#define FREQ (4000)
#define LENGTH (30)
#define DELAY (0)
#define REPETITIONS (1)
Functions
int beep_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
CLOCK_TICK_RATE
#define CLOCK_TICK_RATE 1193180
Definition at line 48 of file beep.c.
DELAY
#define DELAY (0)
Definition at line 62 of file beep.c.
FREQ
#define FREQ (4000)
Definition at line 53 of file beep.c.
LENGTH
#define LENGTH (30)
Definition at line 58 of file beep.c.
REPETITIONS
#define REPETITIONS (1)
Definition at line 63 of file beep.c.
Function Documentation
beep_main()
int beep_main (int argc, char ** argv)
Definition at line 66 of file beep.c.
 {
     int speaker = get_console_fd_or_die();
     unsigned tickrate_div_freq = tickrate_div_freq; /* for compiler */
     unsigned length = length;
     unsigned delay = delay;
     unsigned rep = rep;
     int c;
     c = 'n';
     while (c != -1) {
         if (c == 'n') {
             tickrate_div_freq = CLOCK_TICK_RATE / FREQ;
             length = LENGTH;
             delay = DELAY;
             rep = REPETITIONS;
         }
         c = getopt(argc, argv, "f:l:d:r:n");
 /* TODO: -s, -c:
  * pipe stdin to stdout, but also beep after each line (-s) or char (-c)
  */
         switch (c) {
         case 'f':
 /* TODO: what "-f 0" should do? */
             tickrate_div_freq = (unsigned)CLOCK_TICK_RATE / xatou(optarg);
             continue;
         case 'l':
             length = xatou(optarg);
             continue;
         case 'd':
 /* TODO:
  * -d N, -D N
  * specify a delay of N milliseconds between repetitions.
  * -d specifies that this delay should only occur between beeps,
  * that is, it should not occur after the last repetition.
  * -D indicates that the delay should occur after every repetition
  */
             delay = xatou(optarg);
             continue;
         case 'r':
             rep = xatou(optarg);
             continue;
         case 'n':
         case -1:
             break;
         default:
             bb_show_usage();
         }
         while (rep) {
 //bb_error_msg("rep[%d] freq=%d, length=%d, delay=%d", rep, freq, length, delay);
             xioctl(speaker, KIOCSOUND, (void*)(uintptr_t)tickrate_div_freq);
             msleep(length);
             ioctl(speaker, KIOCSOUND, (void*)0);
             if (--rep)
                 msleep(delay);
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         close(speaker);
     return EXIT_SUCCESS;
 }
References argc, argv, bb_show_usage(), c, CLOCK_TICK_RATE, close(), DELAY, EXIT_SUCCESS, FREQ, get_console_fd_or_die(), getopt(), ioctl(), LENGTH, msleep(), optarg, REPETITIONS, xatou(), and xioctl.