Fennix Userspace: Userspace/musl/src/ctype/iswcntrl.c File Reference
iswcntrl.c File Reference
#include <wctype.h>
Functions
int iswcntrl (wint_t wc)
int __iswcntrl_l (wint_t c, locale_t l)
weak_alias (__iswcntrl_l, iswcntrl_l)
Function Documentation
__iswcntrl_l()
int __iswcntrl_l (wint_t c, locale_t l)
Definition at line 11 of file iswcntrl.c.
 {
     return iswcntrl(c);
 }
References iswcntrl().
iswcntrl()
int iswcntrl (wint_t wc)
Definition at line 3 of file iswcntrl.c.
 {
     return (unsigned)wc < 32
         || (unsigned)(wc-0x7f) < 33
         || (unsigned)(wc-0x2028) < 2
         || (unsigned)(wc-0xfff9) < 3;
 }
Referenced by __iswcntrl_l(), and iswctype().
weak_alias()
weak_alias (__iswcntrl_l , iswcntrl_l)