Fennix: Userspace/apps/base/bash/include/stat-time.h File Reference
stat-time.h File Reference
#include <sys/stat.h>
Data Structures
struct timespec
Functions
static long int get_stat_atime_ns (struct stat const *st)
static long int get_stat_ctime_ns (struct stat const *st)
static long int get_stat_mtime_ns (struct stat const *st)
static long int get_stat_birthtime_ns (struct stat const *st)
static struct timespec get_stat_atime (struct stat const *st)
static struct timespec get_stat_ctime (struct stat const *st)
static struct timespec get_stat_mtime (struct stat const *st)
static int timespec_cmp (struct timespec a, struct timespec b)
static struct timespec get_stat_birthtime (struct stat const *st)
Data Structure Documentation
timespec
struct timespec
Definition at line 34 of file stat-time.h.
Data Fields
long int tv_nsec
time_t tv_sec
Function Documentation
get_stat_atime()
static struct timespec get_stat_atime (struct stat const * st) inline static
Definition at line 104 of file stat-time.h.
 {
 #ifdef STAT_TIMESPEC
   return STAT_TIMESPEC (st, st_atim);
 #else
   struct timespec t;
   t.tv_sec = st->st_atime;
   t.tv_nsec = get_stat_atime_ns (st);
   return t;
 #endif
 }
References Driver::void().
Referenced by unary_test().
get_stat_atime_ns()
static long int get_stat_atime_ns (struct stat const * st) inline static
Definition at line 65 of file stat-time.h.
 {
 # if defined STAT_TIMESPEC
   return STAT_TIMESPEC (st, st_atim).tv_nsec;
 # elif defined STAT_TIMESPEC_NS
   return STAT_TIMESPEC_NS (st, st_atim);
 # else
   return 0;
 # endif
 }
get_stat_birthtime()
static struct timespec get_stat_birthtime (struct stat const * st) inline static
Definition at line 160 of file stat-time.h.
 {
   struct timespec t;
 #if (defined HAVE_STRUCT_STAT_ST_BIRTHTIMESPEC_TV_NSEC \
      || defined HAVE_STRUCT_STAT_ST_BIRTHTIM_TV_NSEC)
   t = STAT_TIMESPEC (st, st_birthtim);
 #elif defined HAVE_STRUCT_STAT_ST_BIRTHTIMENSEC
   t.tv_sec = st->st_birthtime;
   t.tv_nsec = st->st_birthtimensec;
 #elif (defined _WIN32 || defined __WIN32__) && ! defined __CYGWIN__
   /* Native Windows platforms (but not Cygwin) put the "file creation
      time" in st_ctime (!).  See
      <http://msdn2.microsoft.com/de-de/library/14h5k7ff(VS.80).aspx>.  */
   t.tv_sec = st->st_ctime;
   t.tv_nsec = 0;
 #else
   /* Birth time is not supported.  */
   t.tv_sec = -1;
   t.tv_nsec = -1;
   /* Avoid a "parameter unused" warning.  */
   (void) st;
 #endif
 #if (defined HAVE_STRUCT_STAT_ST_BIRTHTIMESPEC_TV_NSEC \
      || defined HAVE_STRUCT_STAT_ST_BIRTHTIM_TV_NSEC \
      || defined HAVE_STRUCT_STAT_ST_BIRTHTIMENSEC)
   /* FreeBSD and NetBSD sometimes signal the absence of knowledge by
      using zero.  Attempt to work around this problem.  Alas, this can
      report failure even for valid time stamps.  Also, NetBSD
      sometimes returns junk in the birth time fields; work around this
      bug if it is detected.  */
   if (! (t.tv_sec && 0 <= t.tv_nsec && t.tv_nsec < 1000000000))
     {
       t.tv_sec = -1;
       t.tv_nsec = -1;
     }
 #endif
   return t;
 }
References timespec::tv_nsec, and timespec::tv_sec.
get_stat_birthtime_ns()
static long int get_stat_birthtime_ns (struct stat const * st) inline static
Definition at line 104 of file stat-time.h.
 {
 # if defined HAVE_STRUCT_STAT_ST_BIRTHTIMESPEC_TV_NSEC
   return STAT_TIMESPEC (st, st_birthtim).tv_nsec;
 # elif defined HAVE_STRUCT_STAT_ST_BIRTHTIMENSEC
   return STAT_TIMESPEC_NS (st, st_birthtim);
 # else
   /* Avoid a "parameter unused" warning.  */
   (void) st;
   return 0;
 # endif
 }
get_stat_ctime()
static struct timespec get_stat_ctime (struct stat const * st) inline static
Definition at line 104 of file stat-time.h.
 {
 #ifdef STAT_TIMESPEC
   return STAT_TIMESPEC (st, st_ctim);
 #else
   struct timespec t;
   t.tv_sec = st->st_ctime;
   t.tv_nsec = get_stat_ctime_ns (st);
   return t;
 #endif
 }
get_stat_ctime_ns()
static long int get_stat_ctime_ns (struct stat const * st) inline static
Definition at line 78 of file stat-time.h.
 {
 # if defined STAT_TIMESPEC
   return STAT_TIMESPEC (st, st_ctim).tv_nsec;
 # elif defined STAT_TIMESPEC_NS
   return STAT_TIMESPEC_NS (st, st_ctim);
 # else
   return 0;
 # endif
 }
get_stat_mtime()
static struct timespec get_stat_mtime (struct stat const * st) inline static
Definition at line 104 of file stat-time.h.
 {
 #ifdef STAT_TIMESPEC
   return STAT_TIMESPEC (st, st_mtim);
 #else
   struct timespec t;
   t.tv_sec = st->st_mtime;
   t.tv_nsec = get_stat_mtime_ns (st);
   return t;
 #endif
 }
Referenced by stat_mtime(), and unary_test().
get_stat_mtime_ns()
static long int get_stat_mtime_ns (struct stat const * st) inline static
Definition at line 91 of file stat-time.h.
 {
 # if defined STAT_TIMESPEC
   return STAT_TIMESPEC (st, st_mtim).tv_nsec;
 # elif defined STAT_TIMESPEC_NS
   return STAT_TIMESPEC_NS (st, st_mtim);
 # else
   return 0;
 # endif
 }
timespec_cmp()
static int timespec_cmp (struct timespec a, struct timespec b) inline static
Definition at line 160 of file stat-time.h.
 {
   return (a.tv_sec < b.tv_sec
         ? -1
         : (a.tv_sec > b.tv_sec
          ? 1
          : (int) (a.tv_nsec - b.tv_nsec)));
 }
Referenced by filecomp(), and unary_test().