Fennix: Userspace/musl/include/semaphore.h File Reference
semaphore.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <fcntl.h>
Data Structures
struct sem_t
Macros
#define __NEED_time_t
#define __NEED_struct_timespec
#define SEM_FAILED ((sem_t *)0)
Functions
int sem_close (sem_t *)
int sem_destroy (sem_t *)
int sem_getvalue (sem_t *__restrict, int *__restrict)
int sem_init (sem_t *, int, unsigned)
sem_t * sem_open (const char *, int,...)
int sem_post (sem_t *)
int sem_timedwait (sem_t *__restrict, const struct timespec *__restrict)
int sem_trywait (sem_t *)
int sem_unlink (const char *)
int sem_wait (sem_t *)
Data Structure Documentation
sem_t
struct sem_t
Definition at line 17 of file semaphore.h.
Data Fields
volatile int __val[4 *sizeof(long)/sizeof(int)]
Macro Definition Documentation
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 10 of file semaphore.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 9 of file semaphore.h.
SEM_FAILED
#define SEM_FAILED ((sem_t *)0)
Definition at line 15 of file semaphore.h.
Function Documentation
sem_close()
int sem_close (sem_t * sem)
Definition at line 168 of file sem_open.c.
 {
     int i;
     LOCK(lock);
     for (i=0; i<SEM_NSEMS_MAX && semtab[i].sem != sem; i++);
     if (--semtab[i].refcnt) {
         UNLOCK(lock);
         return 0;
     }
     semtab[i].sem = 0;
     semtab[i].ino = 0;
     UNLOCK(lock);
     munmap(sem, sizeof *sem);
     return 0;
 }
References i, LOCK, lock, munmap(), semtab, and UNLOCK.
sem_destroy()
int sem_destroy (sem_t * sem)
Definition at line 3 of file sem_destroy.c.
 {
     return 0;
 }
Referenced by __membarrier(), __synccall(), and mq_notify().
sem_getvalue()
int sem_getvalue (sem_t * __restrict, int * __restrict)
sem_init()
int sem_init (sem_t * sem, int pshared, unsigned value)
Definition at line 5 of file sem_init.c.
 {
     if (value > SEM_VALUE_MAX) {
         errno = EINVAL;
         return -1;
     }
     sem->__val[0] = value;
     sem->__val[1] = 0;
     sem->__val[2] = pshared ? 0 : 128;
     return 0;
 }
References sem_t::__val, EINVAL, errno, and value.
Referenced by __membarrier(), __synccall(), mq_notify(), sem_open(), and submit().
sem_open()
sem_t* sem_open (const char * name, int flags, ...)
Definition at line 32 of file sem_open.c.
 {
     va_list ap;
     mode_t mode;
     unsigned value;
     int fd, i, e, slot, first=1, cnt, cs;
     sem_t newsem;
     void *map;
     char tmp[64];
     struct timespec ts;
     struct stat st;
     char buf[NAME_MAX+10];
     if (!(name = __shm_mapname(name, buf)))
         return SEM_FAILED;
     LOCK(lock);
     /* Allocate table if we don't have one yet */
     if (!semtab && !(semtab = calloc(sizeof *semtab, SEM_NSEMS_MAX))) {
         UNLOCK(lock);
         return SEM_FAILED;
     }
     /* Reserve a slot in case this semaphore is not mapped yet;
      * this is necessary because there is no way to handle
      * failures after creation of the file. */
     slot = -1;
     for (cnt=i=0; i<SEM_NSEMS_MAX; i++) {
         cnt += semtab[i].refcnt;
         if (!semtab[i].sem && slot < 0) slot = i;
     }
     /* Avoid possibility of overflow later */
     if (cnt == INT_MAX || slot < 0) {
         errno = EMFILE;
         UNLOCK(lock);
         return SEM_FAILED;
     }
     /* Dummy pointer to make a reservation */
     semtab[slot].sem = (sem_t *)-1;
     UNLOCK(lock);
     flags &= (O_CREAT|O_EXCL);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     /* Early failure check for exclusive open; otherwise the case
      * where the semaphore already exists is expensive. */
     if (flags == (O_CREAT|O_EXCL) && access(name, F_OK) == 0) {
         errno = EEXIST;
         goto fail;
     }
     for (;;) {
         /* If exclusive mode is not requested, try opening an
          * existing file first and fall back to creation. */
         if (flags != (O_CREAT|O_EXCL)) {
             fd = open(name, FLAGS);
             if (fd >= 0) {
                 if (fstat(fd, &st) < 0 ||
                     (map = mmap(0, sizeof(sem_t), PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0)) == MAP_FAILED) {
                     close(fd);
                     goto fail;
                 }
                 close(fd);
                 break;
             }
             if (errno != ENOENT)
                 goto fail;
         }
         if (!(flags & O_CREAT))
             goto fail;
         if (first) {
             first = 0;
             va_start(ap, flags);
             mode = va_arg(ap, mode_t) & 0666;
             value = va_arg(ap, unsigned);
             va_end(ap);
             if (value > SEM_VALUE_MAX) {
                 errno = EINVAL;
                 goto fail;
             }
             sem_init(&newsem, 1, value);
         }
         /* Create a temp file with the new semaphore contents
          * and attempt to atomically link it as the new name */
         clock_gettime(CLOCK_REALTIME, &ts);
         snprintf(tmp, sizeof(tmp), "/dev/shm/tmp-%d", (int)ts.tv_nsec);
         fd = open(tmp, O_CREAT|O_EXCL|FLAGS, mode);
         if (fd < 0) {
             if (errno == EEXIST) continue;
             goto fail;
         }
         if (write(fd, &newsem, sizeof newsem) != sizeof newsem || fstat(fd, &st) < 0 ||
             (map = mmap(0, sizeof(sem_t), PROT_READ|PROT_WRITE, MAP_SHARED, fd, 0)) == MAP_FAILED) {
             close(fd);
             unlink(tmp);
             goto fail;
         }
         close(fd);
         e = link(tmp, name) ? errno : 0;
         unlink(tmp);
         if (!e) break;
         munmap(map, sizeof(sem_t));
         /* Failure is only fatal when doing an exclusive open;
          * otherwise, next iteration will try to open the
          * existing file. */
         if (e != EEXIST || flags == (O_CREAT|O_EXCL))
             goto fail;
     }
     /* See if the newly mapped semaphore is already mapped. If
      * so, unmap the new mapping and use the existing one. Otherwise,
      * add it to the table of mapped semaphores. */
     LOCK(lock);
     for (i=0; i<SEM_NSEMS_MAX && semtab[i].ino != st.st_ino; i++);
     if (i<SEM_NSEMS_MAX) {
         munmap(map, sizeof(sem_t));
         semtab[slot].sem = 0;
         slot = i;
         map = semtab[i].sem;
     }
     semtab[slot].refcnt++;
     semtab[slot].sem = map;
     semtab[slot].ino = st.st_ino;
     UNLOCK(lock);
     pthread_setcancelstate(cs, 0);
     return map;
 fail:
     pthread_setcancelstate(cs, 0);
     LOCK(lock);
     semtab[slot].sem = 0;
     UNLOCK(lock);
     return SEM_FAILED;
 }
References __shm_mapname(), access(), buf, calloc, close(), cnt, EEXIST, EINVAL, EMFILE, ENOENT, errno, F_OK, fd, FLAGS, fstat(), i, INT_MAX, link(), LOCK, lock, map, MAP_FAILED, MAP_SHARED, mmap(), mode_t, munmap(), O_CREAT, O_EXCL, open(), PROT_READ, PROT_WRITE, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), SEM_FAILED, sem_init(), semtab, slot, snprintf(), timespec::tv_nsec, unlink(), UNLOCK, va_arg, va_end, va_start, value, and write().
sem_post()
int sem_post (sem_t * sem)
Definition at line 5 of file sem_post.c.
 {
     int val, new, waiters, priv = sem->__val[2];
     do {
         val = sem->__val[0];
         waiters = sem->__val[1];
         if ((val & SEM_VALUE_MAX) == SEM_VALUE_MAX) {
             errno = EOVERFLOW;
             return -1;
         }
         new = val + 1;
         if (waiters <= 1)
             new &= ~0x80000000;
     } while (a_cas(sem->__val, val, new) != val);
     if (val<0) __wake(sem->__val, waiters>1 ? 1 : -1, priv);
     return 0;
 }
References sem_t::__val, __wake(), a_cas, EOVERFLOW, and errno.
Referenced by __synccall(), bcast_barrier(), handler(), io_thread_func(), and start().
sem_timedwait()
int sem_timedwait (sem_t * __restrict, const struct timespec * __restrict)
Referenced by __sem_timedwait_time32(), and sem_wait().
sem_trywait()
int sem_trywait (sem_t * sem)
Definition at line 5 of file sem_trywait.c.
 {
     int val;
     while ((val=sem->__val[0]) & SEM_VALUE_MAX) {
         if (a_cas(sem->__val, val, val-1)==val) return 0;
     }
     errno = EAGAIN;
     return -1;
 }
References sem_t::__val, a_cas, EAGAIN, and errno.
Referenced by sem_timedwait().
sem_unlink()
int sem_unlink (const char * name)
Definition at line 4 of file sem_unlink.c.
 {
     return shm_unlink(name);
 }
References shm_unlink().
sem_wait()
int sem_wait (sem_t * sem)
Definition at line 3 of file sem_wait.c.
 {
     return sem_timedwait(sem, 0);
 }
References sem_timedwait().
Referenced by __membarrier(), __synccall(), handler(), mq_notify(), and submit().