Fennix: Userspace/apps/base/bash/lib/termcap/termcap.c File Reference
termcap.c File Reference
#include "ltcap.h"
Data Structures
struct buffer
Macros
#define NULL (char *) 0
#define O_RDONLY 0
#define BUFSIZE 2048
#define TERMCAP_FILE "/etc/termcap"
#define valid_filename_p(fn) (*(fn) == '/')
Functions
char * getenv ()
char * malloc ()
char * realloc ()
static void memory_out ()
static char * xmalloc (unsigned size)
static char * xrealloc (char *ptr, unsigned size)
static char * tgetst1 ()
static char * find_capability (char *bp, char *cap)
__private_extern__ int tgetnum (char *cap)
__private_extern__ int tgetflag (char *cap)
__private_extern__ char * tgetstr (char *cap, char **area)
static char * tgetst1 (char *ptr, char **area)
__private_extern__ int tputs (char *str, int nlines, int(*)() outfun)
static int scan_file ()
static char * gobble_line ()
static int compare_contin ()
static int name_match ()
__private_extern__ int tgetent (char *bp, char *name)
static int scan_file (char *str, int fd, struct buffer *bufp)
static int name_match (char *line, char *name)
static int compare_contin (char *str1, char *str2)
static char * gobble_line (int fd, struct buffer *bufp, char *append_end)
Variables
static char * term_entry
static char esctab []
short ospeed
int tputs_baud_rate
__private_extern__ char PC = '\0'
static int speeds []
Data Structure Documentation
buffer
struct buffer
Definition at line 384 of file termcap.c.
Data Fields
int ateof
char * beg
int full
char * ptr
int size
Macro Definition Documentation
BUFSIZE
#define BUFSIZE 2048
Definition at line 102 of file termcap.c.
NULL
#define NULL (char *) 0
Definition at line 82 of file termcap.c.
O_RDONLY
#define O_RDONLY 0
Definition at line 86 of file termcap.c.
TERMCAP_FILE
#define TERMCAP_FILE "/etc/termcap"
Definition at line 109 of file termcap.c.
valid_filename_p
#define valid_filename_p (fn) (*(fn) == '/')
Definition at line 436 of file termcap.c.
Function Documentation
compare_contin() [1/2]
static int compare_contin () static
Referenced by name_match().
compare_contin() [2/2]
static int compare_contin (char * str1, char * str2) static
Definition at line 677 of file termcap.c.
 {
   register int c1, c2;
   while (1)
     {
       c1 = *str1++;
       c2 = *str2++;
       while (c1 == '\\' && *str1 == '\n')
     {
       str1++;
       while ((c1 = *str1++) == ' ' || c1 == '\t');
     }
       if (c2 == '\0')
     {
       /* End of type being looked up.  */
       if (c1 == '|' || c1 == ':')
         /* If end of name in data base, we win.  */
         return 0;
       else
         return 1;
         }
       else if (c1 != c2)
     return 1;
     }
 }
find_capability()
static char* find_capability (char * bp, char * cap) static
Definition at line 157 of file termcap.c.
 {
   for (; *bp; bp++)
     if (bp[0] == ':'
     && bp[1] == cap[0]
     && bp[2] == cap[1])
       return &bp[4];
   return NULL;
 }
References bp, and NULL.
Referenced by tgetent(), tgetflag(), tgetnum(), and tgetstr().
getenv()
char* getenv ()
Referenced by tgetent().
gobble_line() [1/2]
static char* gobble_line () static
Referenced by scan_file().
gobble_line() [2/2]
static char* gobble_line (int fd, struct buffer * bufp, char * append_end) static
Definition at line 718 of file termcap.c.
 {
   register char *end;
   register int nread;
   register char *buf = bufp->beg;
   register char *tem;
   if (!append_end)
     append_end = bufp->ptr;
   while (1)
     {
       end = append_end;
       while (*end && *end != '\n') end++;
       if (*end)
         break;
       if (bufp->ateof)
     return buf + bufp->full;
       if (bufp->ptr == buf)
     {
       if (bufp->full == bufp->size)
         {
           bufp->size *= 2;
           /* Add 1 to size to ensure room for terminating null.  */
           tem = (char *) xrealloc (buf, bufp->size + 1);
           bufp->ptr = (bufp->ptr - buf) + tem;
           append_end = (append_end - buf) + tem;
           bufp->beg = buf = tem;
         }
     }
       else
     {
       append_end -= bufp->ptr - buf;
       bcopy (bufp->ptr, buf, bufp->full -= bufp->ptr - buf);
       bufp->ptr = buf;
     }
       if (!(nread = read (fd, buf + bufp->full, bufp->size - bufp->full)))
     bufp->ateof = 1;
       bufp->full += nread;
       buf[bufp->full] = '\0';
     }
   return end + 1;
 }
References buffer::ateof, bcopy, buffer::beg, buf, end, fd, buffer::full, buffer::ptr, read(), buffer::size, and xrealloc().
malloc()
char* malloc ()
Referenced by xmalloc().
memory_out()
static void memory_out () static
Definition at line 114 of file termcap.c.
 {
   write (2, "virtual memory exhausted\n", 25);
   exit (1);
 }
References exit(), and write().
Referenced by xmalloc(), and xrealloc().
name_match() [1/2]
static int name_match () static
Referenced by scan_file().
name_match() [2/2]
static int name_match (char * line, char * name) static
Definition at line 661 of file termcap.c.
 {
   register char *tem;
   if (!compare_contin (line, name))
     return 1;
   /* This line starts an entry.  Is it the right one?  */
   for (tem = line; *tem && *tem != '\n' && *tem != ':'; tem++)
     if (*tem == '|' && !compare_contin (tem + 1, name))
       return 1;
   return 0;
 }
References compare_contin().
realloc()
char* realloc ()
Referenced by xrealloc().
scan_file() [1/2]
static int scan_file () static
Referenced by tgetent().
scan_file() [2/2]
static int scan_file (char * str, int fd, struct buffer * bufp) static
Definition at line 621 of file termcap.c.
 {
   register char *end;
   bufp->ptr = bufp->beg;
   bufp->full = 0;
   bufp->ateof = 0;
   *bufp->ptr = '\0';
   lseek (fd, 0L, 0);
   while (!bufp->ateof)
     {
       /* Read a line into the buffer.  */
       end = NULL;
       do
     {
       /* if it is continued, append another line to it,
          until a non-continued line ends.  */
       end = gobble_line (fd, bufp, end);
     }
       while (!bufp->ateof && end[-2] == '\\');
       if (*bufp->ptr != '#'
       && name_match (bufp->ptr, str))
     return 1;
       /* Discard the line just processed.  */
       bufp->ptr = end;
     }
   return 0;
 }
References buffer::ateof, buffer::beg, end, fd, buffer::full, gobble_line(), L, lseek(), name_match(), NULL, buffer::ptr, and str.
tgetent()
__private_extern__ int tgetent (char * bp, char * name)
Definition at line 454 of file termcap.c.
 {
   register char *termcap_name;
   register int fd;
   struct buffer buf;
   register char *bp1;
   char *bp2;
   char *term;
   int malloc_size = 0;
   register int c;
   char *tcenv;          /* TERMCAP value, if it contains :tc=.  */
   char *indirect = NULL;    /* Terminal type in :tc= in TERMCAP value.  */
   int filep;
 #ifdef INTERNAL_TERMINAL
   /* For the internal terminal we don't want to read any termcap file,
      so fake it.  */
   if (!strcmp (name, "internal"))
     {
       term = INTERNAL_TERMINAL;
       if (!bp)
     {
       malloc_size = 1 + strlen (term);
       bp = (char *) xmalloc (malloc_size);
     }
       strcpy (bp, term);
       goto ret;
     }
 #endif /* INTERNAL_TERMINAL */
   /* For compatibility with programs like `less' that want to
      put data in the termcap buffer themselves as a fallback.  */
   if (bp)
     term_entry = bp;
   termcap_name = getenv ("TERMCAP");
   if (termcap_name && *termcap_name == '\0')
     termcap_name = NULL;
 #if 0
 #if defined (MSDOS) && !defined (TEST)
   if (termcap_name && (*termcap_name == '\\'
                || *termcap_name == '/'
                || termcap_name[1] == ':'))
     dostounix_filename(termcap_name);
 #endif
 #endif
   filep = termcap_name && valid_filename_p (termcap_name);
   /* If termcap_name is non-null and starts with / (in the un*x case, that is),
      it is a file name to use instead of /etc/termcap.
      If it is non-null and does not start with /,
      it is the entry itself, but only if
      the name the caller requested matches the TERM variable.  */
   if (termcap_name && !filep && !strcmp (name, getenv ("TERM")))
     {
       indirect = tgetst1 (find_capability (termcap_name, "tc"), (char **) 0);
       if (!indirect)
     {
       if (!bp)
         bp = termcap_name;
       else
         strcpy (bp, termcap_name);
       goto ret;
     }
       else
     {           /* It has tc=.  Need to read /etc/termcap.  */
       tcenv = termcap_name;
       termcap_name = NULL;
     }
     }
   if (!termcap_name || !filep)
     termcap_name = TERMCAP_FILE;
   /* Here we know we must search a file and termcap_name has its name.  */
 #ifdef MSDOS
   fd = open (termcap_name, O_RDONLY|O_TEXT, 0);
 #else
   fd = open (termcap_name, O_RDONLY, 0);
 #endif
   if (fd < 0)
     return -1;
   buf.size = BUFSIZE;
   /* Add 1 to size to ensure room for terminating null.  */
   buf.beg = (char *) xmalloc (buf.size + 1);
   term = indirect ? indirect : name;
   if (!bp)
     {
       malloc_size = indirect ? strlen (tcenv) + 1 : buf.size;
       bp = (char *) xmalloc (malloc_size);
     }
   bp1 = bp;
   if (indirect)
     /* Copy the data from the environment variable.  */
     {
       strcpy (bp, tcenv);
       bp1 += strlen (tcenv);
     }
   while (term)
     {
       /* Scan the file, reading it via buf, till find start of main entry.  */
       if (scan_file (term, fd, &buf) == 0)
     {
       close (fd);
       free (buf.beg);
       if (malloc_size)
         free (bp);
       return 0;
     }
       /* Free old `term' if appropriate.  */
       if (term != name)
     free (term);
       /* If BP is malloc'd by us, make sure it is big enough.  */
       if (malloc_size)
     {
       malloc_size = bp1 - bp + buf.size;
       termcap_name = (char *) xrealloc (bp, malloc_size);
       bp1 += termcap_name - bp;
       bp = termcap_name;
     }
       bp2 = bp1;
       /* Copy the line of the entry from buf into bp.  */
       termcap_name = buf.ptr;
       while ((*bp1++ = c = *termcap_name++) && c != '\n')
     /* Drop out any \ newline sequence.  */
     if (c == '\\' && *termcap_name == '\n')
       {
         bp1--;
         termcap_name++;
       }
       *bp1 = '\0';
       /* Does this entry refer to another terminal type's entry?
      If something is found, copy it into heap and null-terminate it.  */
       term = tgetst1 (find_capability (bp2, "tc"), (char **) 0);
     }
   close (fd);
   free (buf.beg);
   if (malloc_size)
     bp = (char *) xrealloc (bp, bp1 - bp + 1);
  ret:
   term_entry = bp;
   return 1;
 }
References bp, buf, BUFSIZE, c, close(), fd, find_capability(), free, getenv(), NULL, O_RDONLY, O_TEXT, open(), scan_file(), strcmp, strcpy, strlen, term, term_entry, TERMCAP_FILE, tgetst1(), valid_filename_p, xmalloc(), and xrealloc().
tgetflag()
__private_extern__ int tgetflag (char * cap)
Definition at line 181 of file termcap.c.
 {
   register char *ptr = find_capability (term_entry, cap);
   return ptr && ptr[-1] == ':';
 }
References find_capability(), and term_entry.
tgetnum()
__private_extern__ int tgetnum (char * cap)
Definition at line 170 of file termcap.c.
 {
   register char *ptr = find_capability (term_entry, cap);
   if (!ptr || ptr[-1] != '#')
     return -1;
   return atoi (ptr);
 }
References atoi(), find_capability(), and term_entry.
tgetst1() [1/2]
static char* tgetst1 () static
Referenced by tgetent(), and tgetstr().
tgetst1() [2/2]
static char* tgetst1 (char * ptr, char ** area) static
Definition at line 223 of file termcap.c.
 {
   register char *p, *r;
   register int c;
   register int size;
   char *ret;
   register int c1;
   if (!ptr)
     return NULL;
   /* `ret' gets address of where to store the string.  */
   if (!area)
     {
       /* Compute size of block needed (may overestimate).  */
       p = ptr;
       while ((c = *p++) && c != ':' && c != '\n')
     ;
       ret = (char *) xmalloc (p - ptr + 1);
     }
   else
     ret = *area;
   /* Copy the string value, stopping at null or colon.
      Also process ^ and \ abbreviations.  */
   p = ptr;
   r = ret;
   while ((c = *p++) && c != ':' && c != '\n')
     {
       if (c == '^')
     {
       c = *p++;
       if (c == '?')
         c = 0177;
       else
         c &= 037;
     }
       else if (c == '\\')
     {
       c = *p++;
       if (c >= '0' && c <= '7')
         {
           c -= '0';
           size = 0;
           while (++size < 3 && (c1 = *p) >= '0' && c1 <= '7')
         {
           c *= 8;
           c += c1 - '0';
           p++;
         }
         }
       else if (c >= 0100 && c < 0200)
         {
           c1 = esctab[(c & ~040) - 0100];
           if (c1 != ' ')
         c = c1;
         }
     }
       *r++ = c;
     }
   *r = '\0';
   /* Update *AREA.  */
   if (area)
     *area = r + 1;
   return ret;
 }
References c, esctab, NULL, p, size, and xmalloc().
tgetstr()
__private_extern__ char* tgetstr (char * cap, char ** area)
Definition at line 195 of file termcap.c.
 {
   register char *ptr = find_capability (term_entry, cap);
   if (!ptr || (ptr[-1] != '=' && ptr[-1] != '~'))
     return NULL;
   return tgetst1 (ptr, area);
 }
References find_capability(), NULL, term_entry, and tgetst1().
tputs()
__private_extern__ int tputs (char * str, int nlines, int (*) () outfun)
Definition at line 316 of file termcap.c.
 {
   register int padcount = 0;
   register int speed;
 #ifdef emacs
   extern baud_rate;
   speed = baud_rate;
   /* For quite high speeds, convert to the smaller
      units to avoid overflow.  */
   if (speed > 10000)
     speed = - speed / 100;
 #else
   if (ospeed == 0)
     speed = tputs_baud_rate;
   else if (ospeed > 0 && ospeed < (sizeof speeds / sizeof speeds[0]))
     speed = speeds[ospeed];
   else
     speed = 0;
 #endif
   if (!str)
     return -1;
   while (*str >= '0' && *str <= '9')
     {
       padcount += *str++ - '0';
       padcount *= 10;
     }
   if (*str == '.')
     {
       str++;
       padcount += *str++ - '0';
     }
   if (*str == '*')
     {
       str++;
       padcount *= nlines;
     }
   while (*str)
     (*outfun) (*str++);
   /* PADCOUNT is now in units of tenths of msec.
      SPEED is measured in characters per 10 seconds
      or in characters per .1 seconds (if negative).
      We use the smaller units for larger speeds to avoid overflow.  */
   padcount *= speed;
   padcount += 500;
   padcount /= 1000;
   if (speed < 0)
     padcount = -padcount;
   else
     {
       padcount += 50;
       padcount /= 100;
     }
   while (padcount-- > 0)
     (*outfun) (PC);
   return 0;
 }
References ospeed, PC, speeds, str, and tputs_baud_rate.
xmalloc()
static char* xmalloc (unsigned size) static
Definition at line 121 of file termcap.c.
 {
   register char *tem = malloc (size);
   if (!tem)
     memory_out ();
   return tem;
 }
References malloc(), memory_out(), and size.
Referenced by tgetent(), and tgetst1().
xrealloc()
static char* xrealloc (char * ptr, unsigned size) static
Definition at line 132 of file termcap.c.
 {
   register char *tem = realloc (ptr, size);
   if (!tem)
     memory_out ();
   return tem;
 }
References memory_out(), realloc(), and size.
Referenced by gobble_line(), and tgetent().
Variable Documentation
esctab
char esctab[] static
Initial value:
= " \007\010  \033\014 \
      \012 \
  \015 \011 \013 \
        "
Definition at line 209 of file termcap.c.
Referenced by tgetst1().
ospeed
short ospeed
Definition at line 295 of file termcap.c.
Referenced by display_speed(), and tputs().
PC
__private_extern__ char PC = '\0'
Definition at line 298 of file termcap.c.
Referenced by tputs().
speeds
int speeds[] static
Initial value:
=
  {
    0, 50, 75, 110, 135, 150, -2, -3, -6, -12,
    -18, -24, -48, -96, -192, -288, -384, -576, -1152
  }
Definition at line 303 of file termcap.c.
Referenced by tputs(), tty_baud_to_value(), and tty_value_to_baud().
term_entry
char* term_entry static
Definition at line 148 of file termcap.c.
Referenced by tgetent(), tgetflag(), tgetnum(), and tgetstr().
tputs_baud_rate
int tputs_baud_rate
Definition at line 297 of file termcap.c.
Referenced by tputs().