Fennix: Userspace/apps/base/busybox/archival/libarchive/filter_accept_list_reassign.c File Reference
filter_accept_list_reassign.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
char FAST_FUNC filter_accept_list_reassign (archive_handle_t *archive_handle)
Function Documentation
filter_accept_list_reassign()
char FAST_FUNC filter_accept_list_reassign (archive_handle_t * archive_handle)
Definition at line 17 of file filter_accept_list_reassign.c.
 {
     /* Check the file entry is in the accept list */
     if (find_list_entry(archive_handle->accept, archive_handle->file_header->name)) {
         const char *name_ptr;
         /* Find extension */
         name_ptr = strrchr(archive_handle->file_header->name, '.');
         if (!name_ptr)
             return EXIT_FAILURE;
         name_ptr++;
         /* Modify the subarchive handler based on the extension */
         if (strcmp(name_ptr, "tar") == 0) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar;
             return EXIT_SUCCESS;
         }
         if (ENABLE_FEATURE_SEAMLESS_GZ
          && strcmp(name_ptr, "gz") == 0
         ) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar_gz;
             return EXIT_SUCCESS;
         }
         if (ENABLE_FEATURE_SEAMLESS_BZ2
          && strcmp(name_ptr, "bz2") == 0
         ) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar_bz2;
             return EXIT_SUCCESS;
         }
         if (ENABLE_FEATURE_SEAMLESS_LZMA
          && strcmp(name_ptr, "lzma") == 0
         ) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar_lzma;
             return EXIT_SUCCESS;
         }
         if (ENABLE_FEATURE_SEAMLESS_XZ
          && strcmp(name_ptr, "xz") == 0
         ) {
             archive_handle->dpkg__action_data_subarchive = get_header_tar_xz;
             return EXIT_SUCCESS;
         }
     }
     return EXIT_FAILURE;
 }
References archive_handle_t::accept, EXIT_FAILURE, EXIT_SUCCESS, archive_handle_t::file_header, find_list_entry(), get_header_tar(), get_header_tar_bz2(), get_header_tar_gz(), get_header_tar_lzma(), get_header_tar_xz(), file_header_t::name, strcmp, and strrchr().
Referenced by dpkg_deb_main(), and init_archive_deb_ar().