Fennix Kernel: Kernel/include_std/errno.h File Reference
errno.h File Reference
#include <types.h>
Macros
#define EPERM 1
#define ENOENT 2
#define ESRCH 3
#define EINTR 4
#define EIO 5
#define ENXIO 6
#define E2BIG 7
#define ENOEXEC 8
#define EBADF 9
#define ECHILD 10
#define EAGAIN 11
#define ENOMEM 12
#define EACCES 13
#define EFAULT 14
#define ENOTBLK 15
#define EBUSY 16
#define EEXIST 17
#define EXDEV 18
#define ENODEV 19
#define ENOTDIR 20
#define EISDIR 21
#define EINVAL 22
#define ENFILE 23
#define EMFILE 24
#define ENOTTY 25
#define ETXTBSY 26
#define EFBIG 27
#define ENOSPC 28
#define ESPIPE 29
#define EROFS 30
#define EMLINK 31
#define EPIPE 32
#define EDOM 33
#define ERANGE 34
#define EDEADLK 35
#define ENAMETOOLONG 36
#define ENOLCK 37
#define ENOSYS 38
#define ENOTEMPTY 39
#define ELOOP 40
#define ENOMSG 42
#define EIDRM 43
#define ECHRNG 44
#define EL2NSYNC 45
#define EL3HLT 46
#define EL3RST 47
#define ELNRNG 48
#define EUNATCH 49
#define ENOCSI 50
#define EL2HLT 51
#define EBADE 52
#define EBADR 53
#define EXFULL 54
#define ENOANO 55
#define EBADRQC 56
#define EBADSLT 57
#define EBFONT 59
#define ENOSTR 60
#define ENODATA 61
#define ETIME 62
#define ENOSR 63
#define ENONET 64
#define ENOPKG 65
#define EREMOTE 66
#define ENOLINK 67
#define EADV 68
#define ESRMNT 69
#define ECOMM 70
#define EPROTO 71
#define EMULTIHOP 72
#define EDOTDOT 73
#define EBADMSG 74
#define EOVERFLOW 75
#define ENOTUNIQ 76
#define EBADFD 77
#define EREMCHG 78
#define ELIBACC 79
#define ELIBBAD 80
#define ELIBSCN 81
#define ELIBMAX 82
#define ELIBEXEC 83
#define EILSEQ 84
#define ERESTART 85
#define ESTRPIPE 86
#define EUSERS 87
#define ENOTSOCK 88
#define EDESTADDRREQ 89
#define EMSGSIZE 90
#define EPROTOTYPE 91
#define ENOPROTOOPT 92
#define EPROTONOSUPPORT 93
#define ESOCKTNOSUPPORT 94
#define EOPNOTSUPP 95
#define EPFNOSUPPORT 96
#define EAFNOSUPPORT 97
#define EADDRINUSE 98
#define EADDRNOTAVAIL 99
#define ENETDOWN 100
#define ENETUNREACH 101
#define ENETRESET 102
#define ECONNABORTED 103
#define ECONNRESET 104
#define ENOBUFS 105
#define EISCONN 106
#define ENOTCONN 107
#define ESHUTDOWN 108
#define ETOOMANYREFS 109
#define ETIMEDOUT 110
#define ECONNREFUSED 111
#define EHOSTDOWN 112
#define EHOSTUNREACH 113
#define EALREADY 114
#define EINPROGRESS 115
#define ESTALE 116
#define EUCLEAN 117
#define ENOTNAM 118
#define ENAVAIL 119
#define EISNAM 120
#define EREMOTEIO 121
#define EDQUOT 122
#define ENOMEDIUM 123
#define EMEDIUMTYPE 124
#define ECANCELED 125
#define ENOKEY 126
#define EKEYEXPIRED 127
#define EKEYREVOKED 128
#define EKEYREJECTED 129
#define EOWNERDEAD 130
#define ENOTRECOVERABLE 131
#define errno (*__errno_location())
Functions
EXTERNC int * __errno_location (void) __attribute__((const))
const char * strerror (int errnum)
Macro Definition Documentation
E2BIG
#define E2BIG 7
Argument list too long
Definition at line 40 of file errno.h.
EACCES
#define EACCES 13
Permission denied
Definition at line 58 of file errno.h.
EADDRINUSE
#define EADDRINUSE 98
Address already in use
Definition at line 307 of file errno.h.
EADDRNOTAVAIL
#define EADDRNOTAVAIL 99
Cannot assign requested address
Definition at line 310 of file errno.h.
EADV
#define EADV 68
Advertise error
Definition at line 217 of file errno.h.
EAFNOSUPPORT
#define EAFNOSUPPORT 97
Address family not supported by protocol
Definition at line 304 of file errno.h.
EAGAIN
#define EAGAIN 11
Try again
Definition at line 52 of file errno.h.
EALREADY
#define EALREADY 114
Operation already in progress
Definition at line 355 of file errno.h.
EBADE
#define EBADE 52
Invalid exchange
Definition at line 172 of file errno.h.
EBADF
#define EBADF 9
Bad file number
Definition at line 46 of file errno.h.
EBADFD
#define EBADFD 77
File descriptor in bad state
Definition at line 244 of file errno.h.
EBADMSG
#define EBADMSG 74
Not a data message
Definition at line 235 of file errno.h.
EBADR
#define EBADR 53
Invalid request descriptor
Definition at line 175 of file errno.h.
EBADRQC
#define EBADRQC 56
Invalid request code
Definition at line 184 of file errno.h.
EBADSLT
#define EBADSLT 57
Invalid slot
Definition at line 187 of file errno.h.
EBFONT
#define EBFONT 59
Bad font file format
Definition at line 190 of file errno.h.
EBUSY
#define EBUSY 16
Device or resource busy
Definition at line 67 of file errno.h.
ECANCELED
#define ECANCELED 125
Operation Canceled
Definition at line 388 of file errno.h.
ECHILD
#define ECHILD 10
No child processes
Definition at line 49 of file errno.h.
ECHRNG
#define ECHRNG 44
Channel number out of range
Definition at line 148 of file errno.h.
ECOMM
#define ECOMM 70
Communication error on send
Definition at line 223 of file errno.h.
ECONNABORTED
#define ECONNABORTED 103
Software caused connection abort
Definition at line 322 of file errno.h.
ECONNREFUSED
#define ECONNREFUSED 111
Connection refused
Definition at line 346 of file errno.h.
ECONNRESET
#define ECONNRESET 104
Connection reset by peer
Definition at line 325 of file errno.h.
EDEADLK
#define EDEADLK 35
Resource deadlock would occur
Definition at line 124 of file errno.h.
EDESTADDRREQ
#define EDESTADDRREQ 89
Destination address required
Definition at line 280 of file errno.h.
EDOM
#define EDOM 33
Math argument out of domain of func
Definition at line 118 of file errno.h.
EDOTDOT
#define EDOTDOT 73
RFS specific error
Definition at line 232 of file errno.h.
EDQUOT
#define EDQUOT 122
Quota exceeded
Definition at line 379 of file errno.h.
EEXIST
#define EEXIST 17
File exists
Definition at line 70 of file errno.h.
EFAULT
#define EFAULT 14
Bad address
Definition at line 61 of file errno.h.
EFBIG
#define EFBIG 27
File too large
Definition at line 100 of file errno.h.
EHOSTDOWN
#define EHOSTDOWN 112
Host is down
Definition at line 349 of file errno.h.
EHOSTUNREACH
#define EHOSTUNREACH 113
No route to host
Definition at line 352 of file errno.h.
EIDRM
#define EIDRM 43
Identifier removed
Definition at line 145 of file errno.h.
EILSEQ
#define EILSEQ 84
Illegal byte sequence
Definition at line 265 of file errno.h.
EINPROGRESS
#define EINPROGRESS 115
Operation now in progress
Definition at line 358 of file errno.h.
EINTR
#define EINTR 4
Interrupted system call
Definition at line 31 of file errno.h.
EINVAL
#define EINVAL 22
Invalid argument
Definition at line 85 of file errno.h.
EIO
#define EIO 5
I/O error
Definition at line 34 of file errno.h.
EISCONN
#define EISCONN 106
Transport endpoint is already connected
Definition at line 331 of file errno.h.
EISDIR
#define EISDIR 21
Is a directory
Definition at line 82 of file errno.h.
EISNAM
#define EISNAM 120
Is a named type file
Definition at line 373 of file errno.h.
EKEYEXPIRED
#define EKEYEXPIRED 127
Key has expired
Definition at line 394 of file errno.h.
EKEYREJECTED
#define EKEYREJECTED 129
Key was rejected by service
Definition at line 400 of file errno.h.
EKEYREVOKED
#define EKEYREVOKED 128
Key has been revoked
Definition at line 397 of file errno.h.
EL2HLT
#define EL2HLT 51
Level 2 halted
Definition at line 169 of file errno.h.
EL2NSYNC
#define EL2NSYNC 45
Level 2 not synchronized
Definition at line 151 of file errno.h.
EL3HLT
#define EL3HLT 46
Level 3 halted
Definition at line 154 of file errno.h.
EL3RST
#define EL3RST 47
Level 3 reset
Definition at line 157 of file errno.h.
ELIBACC
#define ELIBACC 79
Can not access a needed shared library
Definition at line 250 of file errno.h.
ELIBBAD
#define ELIBBAD 80
Accessing a corrupted shared library
Definition at line 253 of file errno.h.
ELIBEXEC
#define ELIBEXEC 83
Cannot exec a shared library directly
Definition at line 262 of file errno.h.
ELIBMAX
#define ELIBMAX 82
Attempting to link in too many shared libraries
Definition at line 259 of file errno.h.
ELIBSCN
#define ELIBSCN 81
.lib section in a.out corrupted
Definition at line 256 of file errno.h.
ELNRNG
#define ELNRNG 48
Link number out of range
Definition at line 160 of file errno.h.
ELOOP
#define ELOOP 40
Too many symbolic links encountered
Definition at line 139 of file errno.h.
EMEDIUMTYPE
#define EMEDIUMTYPE 124
Wrong medium type
Definition at line 385 of file errno.h.
EMFILE
#define EMFILE 24
Too many open files
Definition at line 91 of file errno.h.
EMLINK
#define EMLINK 31
Too many links
Definition at line 112 of file errno.h.
EMSGSIZE
#define EMSGSIZE 90
Message too long
Definition at line 283 of file errno.h.
EMULTIHOP
#define EMULTIHOP 72
Multihop attempted
Definition at line 229 of file errno.h.
ENAMETOOLONG
#define ENAMETOOLONG 36
File name too long
Definition at line 127 of file errno.h.
ENAVAIL
#define ENAVAIL 119
No XENIX semaphores available
Definition at line 370 of file errno.h.
ENETDOWN
#define ENETDOWN 100
Network is down
Definition at line 313 of file errno.h.
ENETRESET
#define ENETRESET 102
Network dropped connection because of reset
Definition at line 319 of file errno.h.
ENETUNREACH
#define ENETUNREACH 101
Network is unreachable
Definition at line 316 of file errno.h.
ENFILE
#define ENFILE 23
File table overflow
Definition at line 88 of file errno.h.
ENOANO
#define ENOANO 55
No anode
Definition at line 181 of file errno.h.
ENOBUFS
#define ENOBUFS 105
No buffer space available
Definition at line 328 of file errno.h.
ENOCSI
#define ENOCSI 50
No CSI structure available
Definition at line 166 of file errno.h.
ENODATA
#define ENODATA 61
No data available
Definition at line 196 of file errno.h.
ENODEV
#define ENODEV 19
No such device
Definition at line 76 of file errno.h.
ENOENT
#define ENOENT 2
No such file or directory
Definition at line 25 of file errno.h.
ENOEXEC
#define ENOEXEC 8
Exec format error
Definition at line 43 of file errno.h.
ENOKEY
#define ENOKEY 126
Required key not available
Definition at line 391 of file errno.h.
ENOLCK
#define ENOLCK 37
No record locks available
Definition at line 130 of file errno.h.
ENOLINK
#define ENOLINK 67
Link has been severed
Definition at line 214 of file errno.h.
ENOMEDIUM
#define ENOMEDIUM 123
No medium found
Definition at line 382 of file errno.h.
ENOMEM
#define ENOMEM 12
Out of memory
Definition at line 55 of file errno.h.
ENOMSG
#define ENOMSG 42
No message of desired type
Definition at line 142 of file errno.h.
ENONET
#define ENONET 64
Machine is not on the network
Definition at line 205 of file errno.h.
ENOPKG
#define ENOPKG 65
Package not installed
Definition at line 208 of file errno.h.
ENOPROTOOPT
#define ENOPROTOOPT 92
Protocol not available
Definition at line 289 of file errno.h.
ENOSPC
#define ENOSPC 28
No space left on device
Definition at line 103 of file errno.h.
ENOSR
#define ENOSR 63
Out of streams resources
Definition at line 202 of file errno.h.
ENOSTR
#define ENOSTR 60
Device not a stream
Definition at line 193 of file errno.h.
ENOSYS
#define ENOSYS 38
Function not implemented
Definition at line 133 of file errno.h.
ENOTBLK
#define ENOTBLK 15
Block device required
Definition at line 64 of file errno.h.
ENOTCONN
#define ENOTCONN 107
Transport endpoint is not connected
Definition at line 334 of file errno.h.
ENOTDIR
#define ENOTDIR 20
Not a directory
Definition at line 79 of file errno.h.
ENOTEMPTY
#define ENOTEMPTY 39
Directory not empty
Definition at line 136 of file errno.h.
ENOTNAM
#define ENOTNAM 118
Not a XENIX named type file
Definition at line 367 of file errno.h.
ENOTRECOVERABLE
#define ENOTRECOVERABLE 131
State not recoverable
Definition at line 406 of file errno.h.
ENOTSOCK
#define ENOTSOCK 88
Socket operation on non-socket
Definition at line 277 of file errno.h.
ENOTTY
#define ENOTTY 25
Not a typewriter
Definition at line 94 of file errno.h.
ENOTUNIQ
#define ENOTUNIQ 76
Name not unique on network
Definition at line 241 of file errno.h.
ENXIO
#define ENXIO 6
No such device or address
Definition at line 37 of file errno.h.
EOPNOTSUPP
#define EOPNOTSUPP 95
Operation not supported on transport endpoint
Definition at line 298 of file errno.h.
EOVERFLOW
#define EOVERFLOW 75
Value too large for defined data type
Definition at line 238 of file errno.h.
EOWNERDEAD
#define EOWNERDEAD 130
Owner died
Definition at line 403 of file errno.h.
EPERM
#define EPERM 1
Operation not permitted
Definition at line 22 of file errno.h.
EPFNOSUPPORT
#define EPFNOSUPPORT 96
Protocol family not supported
Definition at line 301 of file errno.h.
EPIPE
#define EPIPE 32
Broken pipe
Definition at line 115 of file errno.h.
EPROTO
#define EPROTO 71
Protocol error
Definition at line 226 of file errno.h.
EPROTONOSUPPORT
#define EPROTONOSUPPORT 93
Protocol not supported
Definition at line 292 of file errno.h.
EPROTOTYPE
#define EPROTOTYPE 91
Protocol wrong type for socket
Definition at line 286 of file errno.h.
ERANGE
#define ERANGE 34
Math result not representable
Definition at line 121 of file errno.h.
EREMCHG
#define EREMCHG 78
Remote address changed
Definition at line 247 of file errno.h.
EREMOTE
#define EREMOTE 66
Object is remote
Definition at line 211 of file errno.h.
EREMOTEIO
#define EREMOTEIO 121
Remote I/O error
Definition at line 376 of file errno.h.
ERESTART
#define ERESTART 85
Interrupted system call should be restarted
Definition at line 268 of file errno.h.
EROFS
#define EROFS 30
Read-only file system
Definition at line 109 of file errno.h.
errno
#define errno (*__errno_location())
Definition at line 410 of file errno.h.
ESHUTDOWN
#define ESHUTDOWN 108
Cannot send after transport endpoint shutdown
Definition at line 337 of file errno.h.
ESOCKTNOSUPPORT
#define ESOCKTNOSUPPORT 94
Socket type not supported
Definition at line 295 of file errno.h.
ESPIPE
#define ESPIPE 29
Illegal seek
Definition at line 106 of file errno.h.
ESRCH
#define ESRCH 3
No such process
Definition at line 28 of file errno.h.
ESRMNT
#define ESRMNT 69
Srmount error
Definition at line 220 of file errno.h.
ESTALE
#define ESTALE 116
Stale NFS file handle
Definition at line 361 of file errno.h.
ESTRPIPE
#define ESTRPIPE 86
Streams pipe error
Definition at line 271 of file errno.h.
ETIME
#define ETIME 62
Timer expired
Definition at line 199 of file errno.h.
ETIMEDOUT
#define ETIMEDOUT 110
Connection timed out
Definition at line 343 of file errno.h.
ETOOMANYREFS
#define ETOOMANYREFS 109
Too many references: cannot splice
Definition at line 340 of file errno.h.
ETXTBSY
#define ETXTBSY 26
Text file busy
Definition at line 97 of file errno.h.
EUCLEAN
#define EUCLEAN 117
Structure needs cleaning
Definition at line 364 of file errno.h.
EUNATCH
#define EUNATCH 49
Protocol driver not attached
Definition at line 163 of file errno.h.
EUSERS
#define EUSERS 87
Too many users
Definition at line 274 of file errno.h.
EXDEV
#define EXDEV 18
Cross-device link
Definition at line 73 of file errno.h.
EXFULL
#define EXFULL 54
Exchange full
Definition at line 178 of file errno.h.
Function Documentation
__errno_location()
EXTERNC int* __errno_location (void) const
strerror()
const char* strerror (int errnum)
Definition at line 35 of file errno.cpp.
 {
     if (errnum < 0)
         errnum = -errnum;
     switch (errnum)
     {
     case 0:
         return "Success";
     case EPERM:
         return "Operation not permitted";
     case ENOENT:
         return "No such file or directory";
     case ESRCH:
         return "No such process";
     case EINTR:
         return "Interrupted system call";
     case EIO:
         return "Input/output error";
     case ENXIO:
         return "No such device or address";
     case E2BIG:
         return "Argument list too long";
     case ENOEXEC:
         return "Exec format error";
     case EBADF:
         return "Bad file descriptor";
     case ECHILD:
         return "No child processes";
     case EAGAIN:
         return "Resource temporarily unavailable";
     case ENOMEM:
         return "Cannot allocate memory";
     case EACCES:
         return "Permission denied";
     case EFAULT:
         return "Bad address";
     case ENOTBLK:
         return "Block device required";
     case EBUSY:
         return "Device or resource busy";
     case EEXIST:
         return "File exists";
     case EXDEV:
         return "Invalid cross-device link";
     case ENODEV:
         return "No such device";
     case ENOTDIR:
         return "Not a directory";
     case EISDIR:
         return "Is a directory";
     case EINVAL:
         return "Invalid argument";
     case ENFILE:
         return "Too many open files in system";
     case EMFILE:
         return "Too many open files";
     case ENOTTY:
         return "Inappropriate ioctl for device";
     case ETXTBSY:
         return "Text file busy";
     case EFBIG:
         return "File too large";
     case ENOSPC:
         return "No space left on device";
     case ESPIPE:
         return "Illegal seek";
     case EROFS:
         return "Read-only file system";
     case EMLINK:
         return "Too many links";
     case EPIPE:
         return "Broken pipe";
     case EDOM:
         return "Numerical argument out of domain";
     case ERANGE:
         return "Numerical result out of range";
     case EDEADLK:
         return "Resource deadlock avoided";
     case ENAMETOOLONG:
         return "File name too long";
     case ENOLCK:
         return "No locks available";
     case ENOSYS:
         return "Function not implemented";
     case ENOTEMPTY:
         return "Directory not empty";
     case ELOOP:
         return "Too many levels of symbolic links";
     case ENOMSG:
         return "No message of desired type";
     case EIDRM:
         return "Identifier removed";
     case ECHRNG:
         return "Channel number out of range";
     case EL2NSYNC:
         return "Level 2 not synchronized";
     case EL3HLT:
         return "Level 3 halted";
     case EL3RST:
         return "Level 3 reset";
     case ELNRNG:
         return "Link number out of range";
     case EUNATCH:
         return "Protocol driver not attached";
     case ENOCSI:
         return "No CSI structure available";
     case EL2HLT:
         return "Level 2 halted";
     case EBADE:
         return "Invalid exchange";
     case EBADR:
         return "Invalid request descriptor";
     case EXFULL:
         return "Exchange full";
     case ENOANO:
         return "No anode";
     case EBADRQC:
         return "Invalid request code";
     case EBADSLT:
         return "Invalid slot";
     case EBFONT:
         return "Bad font file format";
     case ENOSTR:
         return "Device not a stream";
     case ENODATA:
         return "No data available";
     case ETIME:
         return "Timer expired";
     case ENOSR:
         return "Out of streams resources";
     case ENONET:
         return "Machine is not on the network";
     case ENOPKG:
         return "Package not installed";
     case EREMOTE:
         return "Object is remote";
     case ENOLINK:
         return "Link has been severed";
     case EADV:
         return "Advertise error";
     case ESRMNT:
         return "Srmount error";
     case ECOMM:
         return "Communication error on send";
     case EPROTO:
         return "Protocol error";
     case EMULTIHOP:
         return "Multihop attempted";
     case EDOTDOT:
         return "RFS specific error";
     case EBADMSG:
         return "Bad message";
     case EOVERFLOW:
         return "Value too large for defined data type";
     case ENOTUNIQ:
         return "Name not unique on network";
     case EBADFD:
         return "File descriptor in bad state";
     case EREMCHG:
         return "Remote address changed";
     case ELIBACC:
         return "Can not access a needed shared library";
     case ELIBBAD:
         return "Accessing a corrupted shared library";
     case ELIBSCN:
         return ".lib section in a.out corrupted";
     case ELIBMAX:
         return "Attempting to link in too many shared libraries";
     case ELIBEXEC:
         return "Cannot exec a shared library directly";
     case EILSEQ:
         return "Illegal byte sequence";
     case ERESTART:
         return "Interrupted system call should be restarted";
     case ESTRPIPE:
         return "Streams pipe error";
     case EUSERS:
         return "Too many users";
     case ENOTSOCK:
         return "Socket operation on non-socket";
     case EDESTADDRREQ:
         return "Destination address required";
     case EMSGSIZE:
         return "Message too long";
     case EPROTOTYPE:
         return "Protocol wrong type for socket";
     case ENOPROTOOPT:
         return "Protocol not available";
     case EPROTONOSUPPORT:
         return "Protocol not supported";
     case ESOCKTNOSUPPORT:
         return "Socket type not supported";
     case EOPNOTSUPP:
         return "Operation not supported";
     case EPFNOSUPPORT:
         return "Protocol family not supported";
     case EAFNOSUPPORT:
         return "Address family not supported by protocol";
     case EADDRINUSE:
         return "Address already in use";
     case EADDRNOTAVAIL:
         return "Cannot assign requested address";
     case ENETDOWN:
         return "Network is down";
     case ENETUNREACH:
         return "Network is unreachable";
     case ENETRESET:
         return "Network dropped connection on reset";
     case ECONNABORTED:
         return "Software caused connection abort";
     case ECONNRESET:
         return "Connection reset by peer";
     case ENOBUFS:
         return "No buffer space available";
     case EISCONN:
         return "Transport endpoint is already connected";
     case ENOTCONN:
         return "Transport endpoint is not connected";
     case ESHUTDOWN:
         return "Cannot send after transport endpoint shutdown";
     case ETOOMANYREFS:
         return "Too many references: cannot splice";
     case ETIMEDOUT:
         return "Connection timed out";
     case ECONNREFUSED:
         return "Connection refused";
     case EHOSTDOWN:
         return "Host is down";
     case EHOSTUNREACH:
         return "No route to host";
     case EALREADY:
         return "Operation already in progress";
     case EINPROGRESS:
         return "Operation now in progress";
     case ESTALE:
         return "Stale file handle";
     case EUCLEAN:
         return "Structure needs cleaning";
     case ENOTNAM:
         return "Not a XENIX named type file";
     case ENAVAIL:
         return "No XENIX semaphores available";
     case EISNAM:
         return "Is a named type file";
     case EREMOTEIO:
         return "Remote I/O error";
     case EDQUOT:
         return "Quota exceeded";
     case ENOMEDIUM:
         return "No medium found";
     case EMEDIUMTYPE:
         return "Wrong medium type";
     case ECANCELED:
         return "Operation Canceled";
     case ENOKEY:
         return "Required key not available";
     case EKEYEXPIRED:
         return "Key has expired";
     case EKEYREVOKED:
         return "Key has been revoked";
     case EKEYREJECTED:
         return "Key was rejected by service";
     case EOWNERDEAD:
         return "Owner died";
     case ENOTRECOVERABLE:
         return "State not recoverable";
     default:
         return "Unknown error";
     }
 }
References E2BIG, EACCES, EADDRINUSE, EADDRNOTAVAIL, EADV, EAFNOSUPPORT, EAGAIN, EALREADY, EBADE, EBADF, EBADFD, EBADMSG, EBADR, EBADRQC, EBADSLT, EBFONT, EBUSY, ECANCELED, ECHILD, ECHRNG, ECOMM, ECONNABORTED, ECONNREFUSED, ECONNRESET, EDEADLK, EDESTADDRREQ, EDOM, EDOTDOT, EDQUOT, EEXIST, EFAULT, EFBIG, EHOSTDOWN, EHOSTUNREACH, EIDRM, EILSEQ, EINPROGRESS, EINTR, EINVAL, EIO, EISCONN, EISDIR, EISNAM, EKEYEXPIRED, EKEYREJECTED, EKEYREVOKED, EL2HLT, EL2NSYNC, EL3HLT, EL3RST, ELIBACC, ELIBBAD, ELIBEXEC, ELIBMAX, ELIBSCN, ELNRNG, ELOOP, EMEDIUMTYPE, EMFILE, EMLINK, EMSGSIZE, EMULTIHOP, ENAMETOOLONG, ENAVAIL, ENETDOWN, ENETRESET, ENETUNREACH, ENFILE, ENOANO, ENOBUFS, ENOCSI, ENODATA, ENODEV, ENOENT, ENOEXEC, ENOKEY, ENOLCK, ENOLINK, ENOMEDIUM, ENOMEM, ENOMSG, ENONET, ENOPKG, ENOPROTOOPT, ENOSPC, ENOSR, ENOSTR, ENOSYS, ENOTBLK, ENOTCONN, ENOTDIR, ENOTEMPTY, ENOTNAM, ENOTRECOVERABLE, ENOTSOCK, ENOTTY, ENOTUNIQ, ENXIO, EOPNOTSUPP, EOVERFLOW, EOWNERDEAD, EPERM, EPFNOSUPPORT, EPIPE, EPROTO, EPROTONOSUPPORT, EPROTOTYPE, ERANGE, EREMCHG, EREMOTE, EREMOTEIO, ERESTART, EROFS, ESHUTDOWN, ESOCKTNOSUPPORT, ESPIPE, ESRCH, ESRMNT, ESTALE, ESTRPIPE, ETIME, ETIMEDOUT, ETOOMANYREFS, ETXTBSY, EUCLEAN, EUNATCH, EUSERS, EXDEV, and EXFULL.
Referenced by cmd_modinfo(), Execute::GetBinaryType(), Driver::Manager::LoadAllDrivers(), Driver::Manager::Manager(), StartKernelShell(), Driver::Manager::UnloadAllDrivers(), and WriteDiagDataToNode().