Fennix: Userspace/apps/base/bash/lib/sh/strtod.c File Reference
strtod.c File Reference
#include <errno.h>
#include <chartypes.h>
#include <math.h>
#include <bashansi.h>
Macros
#define DBL_MAX 1.7976931348623159e+308
#define DBL_MIN 2.2250738585072010e-308
#define NULL 0
#define HUGE_VAL HUGE
Functions
int locale_decpoint PARAMS ((void))
double strtod (char *nptr, char **endptr) const
Variables
int errno
Macro Definition Documentation
DBL_MAX
#define DBL_MAX 1.7976931348623159e+308
Definition at line 38 of file strtod.c.
DBL_MIN
#define DBL_MIN 2.2250738585072010e-308
Definition at line 39 of file strtod.c.
HUGE_VAL
#define HUGE_VAL HUGE
Definition at line 49 of file strtod.c.
NULL
#define NULL 0
Definition at line 45 of file strtod.c.
Function Documentation
PARAMS()
int locale_decpoint PARAMS ((void))
strtod()
double strtod (char * nptr, char ** endptr) const
Definition at line 59 of file strtod.c.
 {
   register const char *s;
   short sign;
   /* The number so far.  */
   double num;
   int radixchar;
   int got_dot;          /* Found a decimal point.  */
   int got_digit;        /* Seen any digits.  */
   /* The exponent of the number.  */
   long int exponent;
   if (nptr == NULL)
     {
       errno = EINVAL;
       goto noconv;
     }
   s = nptr;
   /* Eat whitespace.  */
   while (ISSPACE ((unsigned char)*s))
     ++s;
   /* Get the sign.  */
   sign = *s == '-' ? -1 : 1;
   if (*s == '-' || *s == '+')
     ++s;
   radixchar = locale_decpoint ();
   num = 0.0;
   got_dot = 0;
   got_digit = 0;
   exponent = 0;
   for (;; ++s)
     {
       if (DIGIT (*s))
     {
       got_digit = 1;
       /* Make sure that multiplication by 10 will not overflow.  */
       if (num > DBL_MAX * 0.1)
         /* The value of the digit doesn't matter, since we have already
            gotten as many digits as can be represented in a `double'.
            This doesn't necessarily mean the result will overflow.
            The exponent may reduce it to within range.
            We just need to record that there was another
            digit so that we can multiply by 10 later.  */
         ++exponent;
       else
         num = (num * 10.0) + (*s - '0');
       /* Keep track of the number of digits after the decimal point.
          If we just divided by 10 here, we would lose precision.  */
       if (got_dot)
         --exponent;
     }
       else if (!got_dot && *s == radixchar)
     /* Record that we have found the decimal point.  */
     got_dot = 1;
       else
     /* Any other character terminates the number.  */
     break;
     }
   if (!got_digit)
     goto noconv;
   if (TOLOWER ((unsigned char)*s) == 'e')
     {
       /* Get the exponent specified after the `e' or `E'.  */
       int save = errno;
       char *end;
       long int exp;
       errno = 0;
       ++s;
       exp = strtol (s, &end, 10);
       if (errno == ERANGE)
     {
       /* The exponent overflowed a `long int'.  It is probably a safe
          assumption that an exponent that cannot be represented by
          a `long int' exceeds the limits of a `double'.  */
       if (endptr != NULL)
         *endptr = end;
       if (exp < 0)
         goto underflow;
       else
         goto overflow;
     }
       else if (end == s)
     /* There was no exponent.  Reset END to point to
        the 'e' or 'E', so *ENDPTR will be set there.  */
     end = (char *) s - 1;
       errno = save;
       s = end;
       exponent += exp;
     }
   if (endptr != NULL)
     *endptr = (char *) s;
   if (num == 0.0)
     return 0.0;
   /* Multiply NUM by 10 to the EXPONENT power,
      checking for overflow and underflow.  */
   if (exponent < 0)
     {
       if (num < DBL_MIN * pow (10.0, (double) -exponent))
     goto underflow;
     }
   else if (exponent > 0)
     {
       if (num > DBL_MAX * pow (10.0, (double) -exponent))
     goto overflow;
     }
   num *= pow (10.0, (double) exponent);
   return num * sign;
 overflow:
   /* Return an overflow error.  */
   errno = ERANGE;
   return HUGE_VAL * sign;
 underflow:
   /* Return an underflow error.  */
   if (endptr != NULL)
     *endptr = (char *) nptr;
   errno = ERANGE;
   return 0.0;
 noconv:
   /* There was no number.  */
   if (endptr != NULL)
     *endptr = (char *) nptr;
   return 0.0;
 }
References DBL_MAX, DBL_MIN, DIGIT, EINVAL, end, ERANGE, errno, exp, exponent(), HUGE_VAL, ISSPACE, locale_decpoint(), NULL, num, pow, s, strtol(), and TOLOWER.
Variable Documentation
errno
int errno extern
Referenced by strtod().