Fennix Userspace: Userspace/musl/src/ctype/iswalnum.c File Reference
iswalnum.c File Reference
#include <wctype.h>
Functions
int iswalnum (wint_t wc)
int __iswalnum_l (wint_t c, locale_t l)
weak_alias (__iswalnum_l, iswalnum_l)
Function Documentation
__iswalnum_l()
int __iswalnum_l (wint_t c, locale_t l)
Definition at line 8 of file iswalnum.c.
 {
     return iswalnum(c);
 }
References iswalnum().
iswalnum()
int iswalnum (wint_t wc)
Definition at line 3 of file iswalnum.c.
 {
     return iswdigit(wc) || iswalpha(wc);
 }
References iswalpha(), and iswdigit.
Referenced by __iswalnum_l(), and iswctype().
weak_alias()
weak_alias (__iswalnum_l , iswalnum_l)