Fennix: vfs Namespace Reference
vfs Namespace Reference
Data Structures
class EXT2
class Initrd
class USTAR
struct vfsInode
class Virtual
class FileDescriptorTable
Functions
__no_sanitize ("alignment") ssize_t USTAR
int __vfs_Lookup (struct Inode *_Parent, const char *Name, struct Inode **Result)
int __vfs_Create (struct Inode *Parent, const char *Name, mode_t Mode, struct Inode **Result)
fixme ("maybe wrong implementation of readdir")
foreach (const auto &Root in Node->Children)
if (ent) ent -> d_off=INT32_MAX
if (totalSize+sizeof(struct kdirent) >=Size) return totalSize
ssize_t __vfs_ReadLink (struct Inode *Node, char *Buffer, size_t Size)
Variables
struct kdirent * Buffer
struct kdirent size_t Size
struct kdirent size_t off_t Offset
struct kdirent size_t off_t off_t Entries
size_t totalSize = 0
off_t entriesSkipped = 0
struct kdirent * ent = nullptr
vfsInode * Node = (vfsInode *)_Node
off_t entries = 0
ent d_ino = 0
ent d_off = 0
ent d_reclen = 0
ent d_type = DT_UNKNOWN
ent d_name [0] = '\0'
Data Structure Documentation
vfs::vfsInode
struct vfs::vfsInode
Definition at line 87 of file filesystem.hpp.
Data Fields
vector< Inode * > Children
string FriendlyName
string Name
Inode Node
Function Documentation
__no_sanitize()
vfs::__no_sanitize ("alignment")
Definition at line 212 of file ustar.cpp.
     {
         /* FIXME: FIX ALIGNMENT FOR DIRENT! */
         auto Node = (USTARInode *)_Node;
         off_t realOffset = Offset;
         size_t totalSize = 0;
         uint16_t reclen = 0;
         struct kdirent *ent = nullptr;
         if (Offset == 0)
         {
             reclen = (uint16_t)(offsetof(struct kdirent, d_name) + strlen(".") + 1);
             if (totalSize + reclen >= Size)
                 return -EINVAL;
             ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
             ent->d_ino = Node->Node.Index;
             ent->d_off = Offset++;
             ent->d_reclen = reclen;
             ent->d_type = DT_DIR;
             strcpy(ent->d_name, ".");
             totalSize += reclen;
         }
         if (Offset <= 1)
         {
             reclen = (uint16_t)(offsetof(struct kdirent, d_name) + strlen("..") + 1);
             if (totalSize + reclen >= Size)
             {
                 if (realOffset == 1)
                     return -EINVAL;
                 return totalSize;
             }
             ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
             if (Node->Parent)
                 ent->d_ino = Node->Parent->Node.Index;
             else
             {
                 warn("Parent is null for %s", Node->Name.c_str());
                 ent->d_ino = Node->Node.Index;
             }
             ent->d_off = Offset++;
             ent->d_reclen = reclen;
             ent->d_type = DT_DIR;
             strcpy(ent->d_name, "..");
             totalSize += reclen;
         }
         // off_t entriesSkipped = 0;
         // auto fileItr = Files.begin();
         // while (fileItr != Files.end())
         // {
         //  if (fileItr->second->Deleted)
         //      continue;
         //  reclen = (uint16_t)(offsetof(struct kdirent, d_name) + strlen(fileItr->second->Name.c_str()) + 1);
         //  if (Offset > entriesSkipped)
         //  {
         //      entriesSkipped++;
         //      continue;
         //  }
         //  if (totalSize + reclen >= Size)
         //      break;
         //  ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
         //  ent->d_ino = fileItr->first;
         //  ent->d_off = Offset++;
         //  ent->d_reclen = reclen;
         //  ent->d_type = IFTODT(StringToInt(fileItr->second->Header->mode));
         //  strncpy(ent->d_name,
         //          fileItr->second->Name.c_str(),
         //          strlen(fileItr->second->Name.c_str()));
         //  totalSize += reclen;
         //  fileItr++;
         // }
         if (!S_ISDIR(Node->Node.Mode))
             return -ENOTDIR;
         if ((Offset >= 2 ? (Offset - 2) : Offset) > (off_t)Node->Children.size())
             return -EINVAL;
         off_t entries = 0;
         for (const auto &var : Node->Children)
         {
             if (var->Node.Offset < Offset)
                 continue;
             if (entries >= Entries)
                 break;
             if (var->Deleted)
                 continue;
             reclen = (uint16_t)(offsetof(struct kdirent, d_name) + strlen(var->Name.c_str()) + 1);
             if (totalSize + reclen >= Size)
                 break;
             ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
             ent->d_ino = var->Node.Index;
             ent->d_off = var->Node.Offset;
             ent->d_reclen = reclen;
             switch (var->Header->typeflag[0])
             {
             case AREGTYPE:
             case REGTYPE:
                 ent->d_type = DT_REG;
                 break;
             case LNKTYPE:
                 fixme("Hard link not implemented for %s", var->Header->name);
                 ent->d_type = DT_LNK;
                 break;
             case SYMTYPE:
                 ent->d_type = DT_LNK;
                 break;
             case CHRTYPE:
                 ent->d_type = DT_CHR;
                 break;
             case BLKTYPE:
                 ent->d_type = DT_BLK;
                 break;
             case DIRTYPE:
                 ent->d_type = DT_DIR;
                 break;
             case FIFOTYPE:
                 ent->d_type = DT_FIFO;
                 break;
             case CONTTYPE:
             default:
                 ent->d_type = 0;
                 break;
             }
             strncpy(ent->d_name, var->Name.c_str(), strlen(var->Name.c_str()));
             totalSize += reclen;
             entries++;
         }
         if (totalSize + sizeof(struct kdirent) >= Size)
             return totalSize;
         ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
         ent->d_ino = 0;
         ent->d_off = 0;
         ent->d_reclen = 0;
         ent->d_type = DT_UNKNOWN;
         ent->d_name[0] = '\0';
         return totalSize;
     }
References AREGTYPE, BLKTYPE, Buffer, vfs::vfsInode::Children, CHRTYPE, CONTTYPE, kdirent::d_ino, d_name, kdirent::d_name, kdirent::d_off, kdirent::d_reclen, kdirent::d_type, DIRTYPE, DT_BLK, DT_CHR, DT_DIR, DT_FIFO, DT_LNK, DT_REG, DT_UNKNOWN, EINVAL, ENOTDIR, ent, Entries, entries, FIFOTYPE, fixme(), Inode::Index, LNKTYPE, Inode::Mode, vfs::vfsInode::Name, vfs::vfsInode::Node, Node, off_t, Offset, offsetof, Driver::realOffset, Driver::reclen, REGTYPE, S_ISDIR, Size, strcpy, strlen, strncpy(), SYMTYPE, totalSize, and warn.
__vfs_Create()
int vfs::__vfs_Create (struct Inode * Parent, const char * Name, mode_t Mode, struct Inode ** Result)
Definition at line 64 of file virtual.cpp.
     {
         assert(Parent != nullptr);
         assert(!"Not implemented");
     }
References assert.
Referenced by vfs::Virtual::Virtual().
__vfs_Lookup()
int vfs::__vfs_Lookup (struct Inode * _Parent, const char * Name, struct Inode ** Result)
Definition at line 35 of file virtual.cpp.
     {
         vfsInode *Parent = (vfsInode *)_Parent;
         if (!S_ISDIR(Parent->Node.Mode))
             return -ENOTDIR;
         assert(Parent->Node.Flags & I_FLAG_MOUNTPOINT);
         if (Parent->Children.empty())
             return -ENOENT;
         off_t offset = 0;
         for (const auto &Root : Parent->Children)
         {
             char rootName[128]{};
             snprintf(rootName, sizeof(rootName), "\x06root-%ld\x06", offset);
             if (strcmp(rootName, Name) == 0)
             {
                 *Result = Root;
                 return 0;
             }
             offset++;
         }
         return -ENOENT;
     }
References assert, vfs::vfsInode::Children, ENOENT, ENOTDIR, Inode::Flags, I_FLAG_MOUNTPOINT, Inode::Mode, Name, vfs::vfsInode::Node, off_t, S_ISDIR, snprintf(), and strcmp.
Referenced by vfs::Virtual::Virtual().
__vfs_ReadLink()
ssize_t vfs::__vfs_ReadLink (struct Inode * Node, char * Buffer, size_t Size)
Definition at line 131 of file virtual.cpp.
     {
         switch (Node->GetMinor())
         {
         case 1:
         {
             /* FIXME: https://github.com/torvalds/linux/blob/c942a0cd3603e34dd2d7237e064d9318cb7f9654/fs/proc/self.c#L11
                     https://lxr.linux.no/#linux+v3.2.9/fs/proc/base.c#L2482 */
             int ret = snprintf(Buffer, Size, "/proc/%d", thisProcess->ID);
             debug("ReadLink: %s (%d bytes)", Buffer, ret);
             return ret;
         }
         default:
             return -ENOENT;
         }
     }
References Buffer, debug, ENOENT, Node, ret, Size, snprintf(), and thisProcess.
Referenced by vfs::Virtual::Virtual().
fixme()
vfs::fixme ("maybe wrong implementation of readdir")
Referenced by __no_sanitize(), vfs::FileDescriptorTable::AddFileDescriptor(), vfs::Virtual::ForceCreate(), Driver::Manager::LoadDriverFile(), vfs::USTAR::ReadArchive(), vfs::Virtual::RemoveCacheNode(), vfs::USTAR::Stat(), and Driver::Manager::UnregisterDevice().
foreach()
vfs::foreach (const auto &Root in Node-> Children)
Definition at line 89 of file virtual.cpp.
         {
             if (entries >= Entries)
                 break;
             uint16_t reclen = (uint16_t)(offsetof(struct kdirent, d_name) + strlen("root") + 1);
             if (Offset > entriesSkipped)
             {
                 entriesSkipped++;
                 continue;
             }
             if (totalSize + reclen >= Size)
                 break;
             ent = (struct kdirent *)((uintptr_t)Buffer + totalSize);
             ent->d_ino = Root->Index;
             ent->d_off = Root->Offset;
             ent->d_reclen = reclen;
             ent->d_type = IFTODT(Root->Mode);
             strncpy(ent->d_name, "root", strlen("root"));
             totalSize += reclen;
             entries++;
         }
References Buffer, kdirent::d_ino, d_name, kdirent::d_name, kdirent::d_off, kdirent::d_reclen, kdirent::d_type, ent, Entries, entries, entriesSkipped, IFTODT, Offset, offsetof, Driver::reclen, Size, strlen, strncpy(), and totalSize.
if() [1/2]
vfs::if (ent) -> d_off=INT32_MAX
Referenced by Driver::__fs_Close(), Driver::__fs_Ioctl(), Driver::__fs_Open(), Driver::__fs_Read(), and Driver::__fs_Write().
if() [2/2]
vfs::if (totalSize+sizeof(struct kdirent) >= Size)
Variable Documentation
Buffer
struct kdirent* vfs::Buffer
Definition at line 72 of file virtual.cpp.
Referenced by Driver::__fs_Read(), Driver::__fs_Write(), __no_sanitize(), __vfs_ReadLink(), cmd_dump(), Driver::for(), foreach(), Driver::if(), vfs::USTAR::Read(), and vfs::USTAR::ReadLink().
d_ino
ent vfs::d_ino = 0
Definition at line 123 of file virtual.cpp.
d_name
ent vfs::d_name[0] = '\0'
Definition at line 127 of file virtual.cpp.
Referenced by __no_sanitize(), Driver::for(), foreach(), and Driver::if().
d_off
ent vfs::d_off = 0
Definition at line 124 of file virtual.cpp.
d_reclen
ent vfs::d_reclen = 0
Definition at line 125 of file virtual.cpp.
d_type
ent vfs::d_type = DT_UNKNOWN
Definition at line 126 of file virtual.cpp.
ent
vfs::ent = nullptr
Definition at line 86 of file virtual.cpp.
Referenced by __no_sanitize(), Driver::for(), foreach(), and Driver::if().
Entries
struct kdirent size_t off_t off_t vfs::Entries
Initial value:
{
        if (_Node->GetMinor() != 0)
        {
            debug("_Node->GetMinor() != 0");
            return -ENOENT;
        }
        assert(_Node->Flags & I_FLAG_MOUNTPOINT)
Definition at line 72 of file virtual.cpp.
Referenced by __no_sanitize(), Driver::for(), and foreach().
entries
off_t vfs::entries = 0
Definition at line 88 of file virtual.cpp.
Referenced by __no_sanitize(), Driver::for(), and foreach().
entriesSkipped
off_t vfs::entriesSkipped = 0
Definition at line 85 of file virtual.cpp.
Referenced by foreach().
Node
vfsInode* vfs::Node = (vfsInode *)_Node
Definition at line 87 of file virtual.cpp.
Referenced by Driver::__fs_Close(), Driver::__fs_Ioctl(), Driver::__fs_Open(), Driver::__fs_Read(), Driver::__fs_Write(), __no_sanitize(), __vfs_ReadLink(), vfs::Virtual::Create(), vfs::Virtual::CreateCacheNode(), vfs::Virtual::CreateLink(), Driver::for(), vfs::Virtual::GetByNode(), vfs::Virtual::GetByPath(), Driver::if(), vfs::Virtual::Mount(), vfs::Virtual::PathExists(), vfs::USTAR::Read(), vfs::USTAR::ReadLink(), vfs::Virtual::Remove(), vfs::Virtual::RemoveCacheNode(), and vfs::USTAR::Stat().
Offset
struct kdirent size_t off_t vfs::Offset
Definition at line 72 of file virtual.cpp.
Referenced by Driver::__fs_Read(), Driver::__fs_Write(), __no_sanitize(), Driver::for(), foreach(), Driver::if(), and vfs::USTAR::Read().
Size
struct kdirent size_t vfs::Size
Definition at line 72 of file virtual.cpp.
Referenced by Driver::__fs_Read(), Driver::__fs_Write(), __no_sanitize(), __vfs_ReadLink(), Driver::for(), foreach(), Driver::if(), vfs::USTAR::Read(), vfs::USTAR::ReadArchive(), and vfs::USTAR::ReadLink().
totalSize
return vfs::totalSize = 0
Definition at line 84 of file virtual.cpp.
Referenced by __no_sanitize(), Driver::for(), foreach(), and Driver::if().