Fennix: Userspace/musl/src/stdio/flockfile.c File Reference
flockfile.c File Reference
#include "stdio_impl.h"
#include "pthread_impl.h"
Functions
void flockfile (FILE *f)
Function Documentation
flockfile()
void flockfile (FILE * f)
Definition at line 4 of file flockfile.c.
 {
     if (!ftrylockfile(f)) return;
     __lockfile(f);
     __register_locked_file(f, __pthread_self());
 }
References __lockfile(), __pthread_self, __register_locked_file(), f, and ftrylockfile().
Referenced by main(), and worker().