Fennix: Userspace/musl/src/time/timer_create.c File Reference
timer_create.c File Reference
#include <time.h>
#include <setjmp.h>
#include <limits.h>
#include "pthread_impl.h"
#include "atomic.h"
Data Structures
struct ksigevent
struct start_args
Functions
static void dummy_0 ()
weak_alias (dummy_0, __pthread_tsd_run_dtors)
static void cleanup_fromsig (void *p)
static void * start (void *arg)
int timer_create (clockid_t clk, struct sigevent *restrict evp, timer_t *restrict res)
Data Structure Documentation
ksigevent
struct ksigevent
Definition at line 7 of file timer_create.c.
Data Fields
int sigev_notify
int sigev_signo
int sigev_tid
union sigval sigev_value
Function Documentation
cleanup_fromsig()
static void cleanup_fromsig (void * p) static
Definition at line 24 of file timer_create.c.
 {
     pthread_t self = __pthread_self();
     __pthread_tsd_run_dtors();
     self->cancel = 0;
     self->cancelbuf = 0;
     self->canceldisable = 0;
     self->cancelasync = 0;
     __reset_tls();
     longjmp(p, 1);
 }
References __pthread_self, __pthread_tsd_run_dtors(), __reset_tls(), longjmp(), and p.
Referenced by start().
dummy_0()
static void dummy_0 (void) static
Definition at line 19 of file timer_create.c.
 {
 }
start()
static void* start (void * arg) static
Definition at line 36 of file timer_create.c.
 {
     pthread_t self = __pthread_self();
     struct start_args *args = arg;
     jmp_buf jb;
     void (*notify)(union sigval) = args->sev->sigev_notify_function;
     union sigval val = args->sev->sigev_value;
     pthread_barrier_wait(&args->b);
     if (self->cancel)
         return 0;
     for (;;) {
         siginfo_t si;
         while (sigwaitinfo(SIGTIMER_SET, &si) < 0);
         if (si.si_code == SI_TIMER && !setjmp(jb)) {
             pthread_cleanup_push(cleanup_fromsig, jb);
             notify(val);
             pthread_cleanup_pop(1);
         }
         if (self->timer_id < 0) break;
     }
     __syscall(SYS_timer_delete, self->timer_id & INT_MAX);
     return 0;
 }
References __pthread_self, __syscall, cleanup_fromsig(), INT_MAX, pthread_barrier_wait(), pthread_cleanup_pop, pthread_cleanup_push, setjmp, args::sev, sigevent::sigev_notify_function, sigevent::sigev_value, SIGTIMER_SET, sigwaitinfo(), val, and Module::void().
timer_create()
int timer_create (clockid_t clk, struct sigevent *restrict evp, timer_t *restrict res)
Definition at line 62 of file timer_create.c.
 {
     volatile static int init = 0;
     pthread_t td;
     pthread_attr_t attr;
     int r;
     struct start_args args;
     struct ksigevent ksev, *ksevp=0;
     int timerid;
     sigset_t set;
     switch (evp ? evp->sigev_notify : SIGEV_SIGNAL) {
     case SIGEV_NONE:
     case SIGEV_SIGNAL:
     case SIGEV_THREAD_ID:
         if (evp) {
             ksev.sigev_value = evp->sigev_value;
             ksev.sigev_signo = evp->sigev_signo;
             ksev.sigev_notify = evp->sigev_notify;
             if (evp->sigev_notify == SIGEV_THREAD_ID)
                 ksev.sigev_tid = evp->sigev_notify_thread_id;
             else
                 ksev.sigev_tid = 0;
             ksevp = &ksev;
         }
         if (syscall(SYS_timer_create, clk, ksevp, &timerid) < 0)
             return -1;
         *res = (void *)(intptr_t)timerid;
         break;
     case SIGEV_THREAD:
         if (!init) {
             struct sigaction sa = { .sa_handler = SIG_DFL };
             __libc_sigaction(SIGTIMER, &sa, 0);
             a_store(&init, 1);
         }
         if (evp->sigev_notify_attributes)
             attr = *evp->sigev_notify_attributes;
         else
             pthread_attr_init(&attr);
         pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
         pthread_barrier_init(&args.b, 0, 2);
         args.sev = evp;
         __block_app_sigs(&set);
         __syscall(SYS_rt_sigprocmask, SIG_BLOCK, SIGTIMER_SET, 0, _NSIG/8);
         r = pthread_create(&td, &attr, start, &args);
         __restore_sigs(&set);
         if (r) {
             errno = r;
             return -1;
         }
         ksev.sigev_value.sival_ptr = 0;
         ksev.sigev_signo = SIGTIMER;
         ksev.sigev_notify = SIGEV_THREAD_ID;
         ksev.sigev_tid = td->tid;
         if (syscall(SYS_timer_create, clk, &ksev, &timerid) < 0) {
             timerid = -1;
             td->cancel = 1;
         }
         td->timer_id = timerid;
         pthread_barrier_wait(&args.b);
         if (timerid < 0) return -1;
         *res = (void *)(INTPTR_MIN | (uintptr_t)td>>1);
         break;
     default:
         errno = EINVAL;
         return -1;
     }
     return 0;
 }
weak_alias()
weak_alias (dummy_0 , __pthread_tsd_run_dtors)