Fennix Userspace: Userspace/apps/base/busybox/include/xatonum.h File Reference
xatonum.h File Reference
Macros
#define DECLARE_STR_CONV(type, T, UT)
#define DEFINE_EQUIV_STR_CONV(narrow, N, W, UN, UW)
Functions
uint32_t BUG_xatou32_unimplemented (void)
static ALWAYS_INLINE uint32_t xatou32 (const char *numstr)
unsigned long long bb_strtoull (const char *arg, char **endp, int base) FAST_FUNC
long long bb_strtoll (const char *arg, char **endp, int base) FAST_FUNC
static ALWAYS_INLINE unsigned long bb_strtoul (const char *arg, char **endp, int base)
static ALWAYS_INLINE long bb_strtol (const char *arg, char **endp, int base)
static ALWAYS_INLINE unsigned bb_strtou (const char *arg, char **endp, int base)
static ALWAYS_INLINE int bb_strtoi (const char *arg, char **endp, int base)
uint32_t BUG_bb_strtou32_unimplemented (void)
static ALWAYS_INLINE uint32_t bb_strtou32 (const char *arg, char **endp, int base)
static ALWAYS_INLINE int32_t bb_strtoi32 (const char *arg, char **endp, int base)
double bb_strtod (const char *arg, char **endp) FAST_FUNC
Macro Definition Documentation
DECLARE_STR_CONV
#define DECLARE_STR_CONV (type, T, UT)
Value:
\
unsigned type xstrto##UT##_range_sfx(const char *str, int b, unsigned type l, unsigned type u, const struct suffix_mult *sfx) FAST_FUNC; \
unsigned type xstrto##UT##_range(const char *str, int b, unsigned type l, unsigned type u) FAST_FUNC; \
unsigned type xstrto##UT##_sfx(const char *str, int b, const struct suffix_mult *sfx) FAST_FUNC; \
unsigned type xstrto##UT(const char *str, int b) FAST_FUNC; \
unsigned type xato##UT##_range_sfx(const char *str, unsigned type l, unsigned type u, const struct suffix_mult *sfx) FAST_FUNC; \
unsigned type xato##UT##_range(const char *str, unsigned type l, unsigned type u) FAST_FUNC; \
unsigned type xato##UT##_sfx(const char *str, const struct suffix_mult *sfx) FAST_FUNC; \
unsigned type xato##UT(const char *str) FAST_FUNC; \
type xstrto##T##_range_sfx(const char *str, int b, type l, type u, const struct suffix_mult *sfx) FAST_FUNC; \
type xstrto##T##_range(const char *str, int b, type l, type u) FAST_FUNC; \
type xstrto##T(const char *str, int b) FAST_FUNC; \
type xato##T##_range_sfx(const char *str, type l, type u, const struct suffix_mult *sfx) FAST_FUNC; \
type xato##T##_range(const char *str, type l, type u) FAST_FUNC; \
type xato##T##_sfx(const char *str, const struct suffix_mult *sfx) FAST_FUNC; \
type xato##T(const char *str) FAST_FUNC; \
Definition at line 13 of file xatonum.h.
DEFINE_EQUIV_STR_CONV
#define DEFINE_EQUIV_STR_CONV (narrow, N, W, UN, UW)
Definition at line 37 of file xatonum.h.
Function Documentation
bb_strtod()
double bb_strtod (const char * arg, char ** endp)
bb_strtoi()
static ALWAYS_INLINE int bb_strtoi (const char * arg, char ** endp, int base) static
Definition at line 147 of file xatonum.h.
 { return bb_strtoll(arg, endp, base); }
References base, and bb_strtoll().
Referenced by bb_strtoi32(), get_width_prec(), and kill_main().
bb_strtoi32()
static ALWAYS_INLINE int32_t bb_strtoi32 (const char * arg, char ** endp, int base) static
Definition at line 172 of file xatonum.h.
 {
     if (sizeof(int32_t) == sizeof(int))
         return bb_strtoi(arg, endp, base);
     if (sizeof(int32_t) == sizeof(long))
         return bb_strtol(arg, endp, base);
     return BUG_bb_strtou32_unimplemented();
 }
References base, bb_strtoi(), bb_strtol(), and BUG_bb_strtou32_unimplemented().
Referenced by udhcp_str2optset().
bb_strtol()
static ALWAYS_INLINE long bb_strtol (const char * arg, char ** endp, int base) static
Definition at line 135 of file xatonum.h.
 { return bb_strtoll(arg, endp, base); }
References base, and bb_strtoll().
Referenced by bb_strtoi32(), convert_to_struct(), get_numeric(), and parse_datestr().
bb_strtoll()
long long bb_strtoll (const char * arg, char ** endp, int base)
Definition at line 72 of file bb_strtonum.c.
 {
     unsigned long long v;
     char *endptr;
     char first;
     if (!endp) endp = &endptr;
     *endp = (char*) arg;
     /* Check for the weird "feature":
      * a "-" string is apparently a valid "number" for strto[u]l[l]!
      * It returns zero and errno is 0! :( */
     first = (arg[0] != '-' ? arg[0] : arg[1]);
     if (!isalnum(first)) return ret_ERANGE();
     errno = 0;
     v = strtoll(arg, endp, base);
     return handle_errors(v, endp);
 }
References base, errno, first, handle_errors(), isalnum, ret_ERANGE(), and strtoll().
Referenced by bb_strtoi(), bb_strtol(), conv_strtoll(), conv_strtoull(), and parse_datestr().
bb_strtou()
static ALWAYS_INLINE unsigned bb_strtou (const char * arg, char ** endp, int base) static
Definition at line 144 of file xatonum.h.
 { return bb_strtoull(arg, endp, base); }
References base, and bb_strtoull().
Referenced by bb_lookup_port(), bb_strtou32(), bcode(), builtin_shift(), convert_to_struct(), decode_one_format(), determine_optimal_seed_len(), do_procinit(), dump_procs(), fixredir(), get_drv_info(), get_prefix_1(), get_signum(), get_uidgid(), handle_incoming_and_exit(), handle_port(), hush_main(), kill_main(), ll_proto_a2n(), lpd_main(), lsscsi_main(), name_to_dev_t(), number_process(), openServer(), parse_one_line(), parse_params(), process_pax_hdr(), process_timer_stats(), procps_scan(), pwdx_main(), read_num(), redirect_opt_num(), renice_main(), reread_config_file(), rtnl_a2n(), rtnl_tab_initialize(), scan_recursive(), sha_crypt(), shell_builtin_read(), shell_builtin_ulimit(), split_escape_and_log(), start_stop_daemon_main(), str2sockaddr(), tcpudpsvd_main(), udhcp_str2optset(), udhcpc6_main(), and udhcpc_main().
bb_strtou32()
static ALWAYS_INLINE uint32_t bb_strtou32 (const char * arg, char ** endp, int base) static
Definition at line 163 of file xatonum.h.
 {
     if (sizeof(uint32_t) == sizeof(unsigned))
         return bb_strtou(arg, endp, base);
     if (sizeof(uint32_t) == sizeof(unsigned long))
         return bb_strtoul(arg, endp, base);
     return BUG_bb_strtou32_unimplemented();
 }
References base, bb_strtou(), bb_strtoul(), and BUG_bb_strtou32_unimplemented().
Referenced by read_u32(), and udhcp_str2optset().
bb_strtoul()
static ALWAYS_INLINE unsigned long bb_strtoul (const char * arg, char ** endp, int base) static
Definition at line 132 of file xatonum.h.
 { return bb_strtoull(arg, endp, base); }
References base, and bb_strtoull().
Referenced by bb_strtou32(), get_ug_id(), name_to_dev_t(), remove_ids(), and shell_builtin_ulimit().
bb_strtoull()
unsigned long long bb_strtoull (const char * arg, char ** endp, int base)
Definition at line 54 of file bb_strtonum.c.
 {
     unsigned long long v;
     char *endptr;
     if (!endp) endp = &endptr;
     *endp = (char*) arg;
     /* strtoul("  -4200000000") returns 94967296, errno 0 (!) */
     /* I don't think that this is right. Preventing this... */
     if (!isalnum(arg[0])) return ret_ERANGE();
     /* not 100% correct for lib func, but convenient for the caller */
     errno = 0;
     v = strtoull(arg, endp, base);
     return handle_errors(v, endp);
 }
References base, errno, handle_errors(), isalnum, ret_ERANGE(), and strtoull().
Referenced by bb_strtou(), bb_strtoul(), conv_strtoull(), cut_out_ull_opt(), devmem_main(), factorize_numstr(), hexedit_main(), hush_main(), process_irq_counts(), read_cstate_counts(), and shell_builtin_ulimit().
BUG_bb_strtou32_unimplemented()
uint32_t BUG_bb_strtou32_unimplemented (void)
Referenced by bb_strtoi32(), and bb_strtou32().
BUG_xatou32_unimplemented()
uint32_t BUG_xatou32_unimplemented (void)
Referenced by xatou32().
xatou32()
static ALWAYS_INLINE uint32_t xatou32 (const char * numstr) static
Definition at line 105 of file xatonum.h.
 {
     if (UINT_MAX == 0xffffffff)
         return xatou(numstr);
     if (ULONG_MAX == 0xffffffff)
         return xatoul(numstr);
     return BUG_xatou32_unimplemented();
 }
References BUG_xatou32_unimplemented(), UINT_MAX, ULONG_MAX, and xatou().
Referenced by decode_arg(), and fbset_main().