Fennix: Userspace/apps/base/busybox/applets/usage.c File Reference
usage.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include "autoconf.h"
#include "usage.h"
#include "applets.h"
Data Structures
struct usage_data
Macros
#define BB_MMU 1
#define USE_FOR_NOMMU(...)
#define USE_FOR_MMU(...) __VA_ARGS__
#define MAKE_USAGE(aname, usage) { aname, usage },
Functions
static int compare_func (const void *a, const void *b)
int main (void)
Variables
static struct usage_data usage_array []
Data Structure Documentation
usage_data
struct usage_data
Definition at line 26 of file usage.c.
Data Fields
const char * aname
const char * usage
Macro Definition Documentation
BB_MMU
#define BB_MMU 1
Definition at line 19 of file usage.c.
MAKE_USAGE
#define MAKE_USAGE (aname, usage) { aname, usage },
Definition at line 25 of file usage.c.
USE_FOR_MMU
#define USE_FOR_MMU (...) __VA_ARGS__
Definition at line 21 of file usage.c.
USE_FOR_NOMMU
#define USE_FOR_NOMMU (...)
Definition at line 20 of file usage.c.
Function Documentation
compare_func()
static int compare_func (const void * a, const void * b) static
Definition at line 33 of file usage.c.
 {
     const struct usage_data *ua = a;
     const struct usage_data *ub = b;
     return strcmp(ua->aname, ub->aname);
 }
References usage_data::aname, and strcmp.
Referenced by main().
main()
int main (void)
Definition at line 40 of file usage.c.
 {
     int i;
     int num_messages = sizeof(usage_array) / sizeof(usage_array[0]);
     if (num_messages == 0)
         return 0;
     qsort(usage_array,
         num_messages, sizeof(usage_array[0]),
         compare_func);
     for (i = 0; i < num_messages; i++)
         write(STDOUT_FILENO, usage_array[i].usage, strlen(usage_array[i].usage) + 1);
     return 0;
 }
References compare_func(), i, qsort(), STDOUT_FILENO, strlen, usage(), usage_array, and write().
Variable Documentation
usage_array
struct usage_data usage_array[] static
Initial value:
= {
}
Referenced by main().