Fennix: Userspace/apps/base/busybox/coreutils/rm.c File Reference
rm.c File Reference
#include "libbb.h"
Functions
int rm_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
rm_main()
int rm_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 43 of file rm.c.
 {
     int status = 0;
     int flags = 0;
     unsigned opt;
     opt = getopt32(argv, "^" "fiRrv" "\0" "f-i:i-f");
     argv += optind;
     if (opt & 1)
         flags |= FILEUTILS_FORCE;
     if (opt & 2)
         flags |= FILEUTILS_INTERACTIVE;
     if (opt & (8|4))
         flags |= FILEUTILS_RECUR;
     if ((opt & 16) && FILEUTILS_VERBOSE)
         flags |= FILEUTILS_VERBOSE;
     if (*argv != NULL) {
         do {
             const char *base = bb_get_last_path_component_strip(*argv);
             if (DOT_OR_DOTDOT(base)) {
                 bb_simple_error_msg("can't remove '.' or '..'");
             } else if (remove_file(*argv, flags) >= 0) {
                 continue;
             }
             status = 1;
         } while (*++argv);
     } else if (!(flags & FILEUTILS_FORCE)) {
         bb_show_usage();
     }
     return status;
 }
References argv, base, bb_get_last_path_component_strip(), bb_show_usage(), bb_simple_error_msg(), DOT_OR_DOTDOT, FILEUTILS_FORCE, FILEUTILS_INTERACTIVE, FILEUTILS_RECUR, FILEUTILS_VERBOSE, flags, getopt32(), NULL, opt, optind, remove_file(), and status.