Fennix: Userspace/musl/include/malloc.h File Reference
malloc.h File Reference
#include <bits/alltypes.h>
Macros
#define __NEED_size_t
Functions
void * malloc (size_t)
The standard function.
void * calloc (size_t, size_t)
The standard function.
void * realloc (void *, size_t)
The standard function.
void free (void *)
The standard function.
void * valloc (size_t)
void * memalign (size_t, size_t)
size_t malloc_usable_size (void *)
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 8 of file malloc.h.
Function Documentation
malloc_usable_size()
size_t malloc_usable_size (void * mem)
Definition at line 1346 of file malloc.c.
 {
   register union mhead *p;
   register char *ap;
   if ((ap = (char *)mem) == 0)
     return 0;
   /* Find the true start of the memory block to discover which bin */
   p = (union mhead *) ap - 1;
   if (p->mh_alloc == ISMEMALIGN)
     {
       ap -= p->mh_nbytes;
       p = (union mhead *) ap - 1;
     }
   /* return 0 if ISFREE */
   if (p->mh_alloc == ISFREE)
     return 0;
References __ensure, CHUNK_SIZE, g, get_meta(), get_nominal_size(), get_slot_index(), get_stride(), IB, idx, MEM_TO_CHUNK, OVERHEAD, p, and start().
memalign()
void* memalign (size_t alignment, size_t size)
Definition at line 1525 of file malloc.c.
 {
References __ensure, aligned_alloc(), and len.
Referenced by valloc().
valloc()
void* valloc (size_t size)
Definition at line 1534 of file malloc.c.
 {
References internal_valloc(), memalign(), NULL, PAGE_SIZE, and size.