Fennix: Userspace/libs/include/sysfile.h File Reference
sysfile.h File Reference
#include <stddef.h>
Data Structures
struct File
Enumerations
enum FileFlags {
FILE_READ = 1 , FILE_WRITE = 2 , FILE_APPEND = 4 , FILE_CREATE = 8 ,
FILE_TRUNCATE = 16 , FILE_EXCLUSIVE = 32 , FILE_DIRECTORY = 64 , FILE_SYMLINK = 128 ,
FILE_NONBLOCK = 256 , FILE_CLOEXEC = 512
}
Functions
File * FileOpen (const char *Path, uint64_t Flags)
void FileClose (File *File)
uint64_t FileRead (File *File, uint8_t *Buffer, uint64_t Size)
uint64_t FileWrite (File *File, uint8_t *Buffer, uint64_t Size)
uint64_t FileSeek (File *File, uint64_t Offset, uint64_t Whence)
uint64_t FileStatus (File *File)
Data Structure Documentation
File
struct File
Definition at line 6 of file sysfile.h.
Data Fields
void * KernelPrivate
Enumeration Type Documentation
FileFlags
enum FileFlags
Enumerator
FILE_READ
FILE_WRITE
FILE_APPEND
FILE_CREATE
FILE_TRUNCATE
FILE_EXCLUSIVE
FILE_DIRECTORY
FILE_SYMLINK
FILE_NONBLOCK
FILE_CLOEXEC
Definition at line 11 of file sysfile.h.
 {
     FILE_READ = 1,
     FILE_WRITE = 2,
     FILE_APPEND = 4,
     FILE_CREATE = 8,
     FILE_TRUNCATE = 16,
     FILE_EXCLUSIVE = 32,
     FILE_DIRECTORY = 64,
     FILE_SYMLINK = 128,
     FILE_NONBLOCK = 256,
     FILE_CLOEXEC = 512,
 };
Function Documentation
FileClose()
void FileClose (File * File)
Definition at line 21 of file File.c.
 {
     syscall1(_FileClose, (uint64_t)File->KernelPrivate);
     KrnlFreePages((uintptr_t)File, sizeof(File) / __FILE_GetPageSize() + 1);
 }
References __FILE_GetPageSize(), _FileClose, File::KernelPrivate, KrnlFreePages(), and syscall1().
Referenced by main().
FileOpen()
File* FileOpen (const char * Path, uint64_t Flags)
Definition at line 14 of file File.c.
 {
     File *FilePtr = (File *)KrnlRequestPages(sizeof(File) / __FILE_GetPageSize() + 1);
     FilePtr->KernelPrivate = (void *)syscall2(_FileOpen, (uint64_t)Path, Flags);
     return FilePtr;
 }
References __FILE_GetPageSize(), _FileOpen, Flags, File::KernelPrivate, KrnlRequestPages(), and syscall2().
Referenced by main().
FileRead()
uint64_t FileRead (File * File, uint8_t * Buffer, uint64_t Size)
Definition at line 27 of file File.c.
 {
     return syscall3(_FileRead, (uint64_t)File->KernelPrivate, (uint64_t)Buffer, Size);
 }
References _FileRead, File::KernelPrivate, and syscall3().
Referenced by main().
FileSeek()
uint64_t FileSeek (File * File, uint64_t Offset, uint64_t Whence)
Definition at line 37 of file File.c.
 {
     return syscall3(_FileSeek, (uint64_t)File->KernelPrivate, Offset, Whence);
 }
References _FileSeek, File::KernelPrivate, and syscall3().
FileStatus()
uint64_t FileStatus (File * File)
Definition at line 42 of file File.c.
 {
     return syscall1(_FileStatus, (uint64_t)File->KernelPrivate);
 }
References _FileStatus, File::KernelPrivate, and syscall1().
FileWrite()
uint64_t FileWrite (File * File, uint8_t * Buffer, uint64_t Size)
Definition at line 32 of file File.c.
 {
     return syscall3(_FileWrite, (uint64_t)File->KernelPrivate, (uint64_t)Buffer, Size);
 }
References _FileWrite, File::KernelPrivate, and syscall3().