Fennix Userspace: Userspace/apps/base/bash/lib/sh/strerror.c File Reference
strerror.c File Reference
#include <config.h>
#include <bashtypes.h>
#include <stdio.h>
#include <errno.h>
#include <shell.h>
Functions
char * strerror (int e)
Variables
int errno
static char * errbase = "Unknown system error "
Function Documentation
strerror()
char* strerror (int e)
Definition at line 52 of file strerror.c.
 {
   static char emsg[40];
 #if defined (HAVE_SYS_ERRLIST)
   extern int sys_nerr;
   extern char *sys_errlist[];
   if (e > 0 && e < sys_nerr)
     return (sys_errlist[e]);
   else
 #endif /* HAVE_SYS_ERRLIST */
     {
       char *z;
       z = itos (e);
       strcpy (emsg, errbase);
       strcat (emsg, z);
       free (z);
       return (&emsg[0]);
     }
 }
References errbase, free, itos(), strcat(), strcpy(), and sys_nerr.
Variable Documentation
errbase
char* errbase = "Unknown system error " static
Definition at line 49 of file strerror.c.
Referenced by strerror().
errno
int errno extern