Fennix Userspace: Userspace/mlibc/options/ansi/generic/signal-stubs.cpp File Reference
signal-stubs.cpp File Reference
#include <bits/ensure.h>
#include <errno.h>
#include <signal.h>
#include <mlibc/debug.hpp>
#include <mlibc/ansi-sysdeps.hpp>
Functions
__sighandler signal (int sn, __sighandler handler)
int raise (int sig)
int sigprocmask (int how, const sigset_t *__restrict set, sigset_t *__restrict retrieve)
Function Documentation
raise()
int raise (int sig)
Definition at line 23 of file signal-stubs.cpp.
                    {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getpid && mlibc::sys_kill, -1);
     pid_t pid = mlibc::sys_getpid();
     if (int e = mlibc::sys_kill(pid, sig)) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_getpid(), and mlibc::sys_kill().
signal()
__sighandler signal (int sn, __sighandler handler)
Definition at line 9 of file signal-stubs.cpp.
{
     struct sigaction sa;
     sa.sa_handler = handler;
     sa.sa_flags = 0;
     sa.sa_mask = 0;
     struct sigaction old;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigaction, SIG_ERR);
     if(int e = mlibc::sys_sigaction(sn, &sa, &old)){
         errno = e;
         return SIG_ERR;
     }
     return old.sa_handler;
 }
References errno, handler(), MLIBC_CHECK_OR_ENOSYS, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SIG_ERR, and mlibc::sys_sigaction().
sigprocmask()
int sigprocmask (int how, const sigset_t *__restrict set, sigset_t *__restrict retrieve)
Definition at line 36 of file signal-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_sigprocmask, -1);
     if(int e = mlibc::sys_sigprocmask(how, set, retrieve); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_sigprocmask().