Fennix Userspace: Userspace/mlibc/tests/posix/abort.c File Reference
abort.c File Reference
#include <signal.h>
#include <assert.h>
#include <stdlib.h>
Functions
void handler (int sig, siginfo_t *info, void *ctx)
int main ()
Function Documentation
handler()
void handler (int sig, siginfo_t * info, void * ctx)
Definition at line 5 of file abort.c.
{
     (void)sig;
     (void)info;
     (void)ctx;
 }
Referenced by __cxa_atexit(), __mlibc_do_finalize(), do_scanf(), main(), signal(), vfscanf(), and vsscanf().
main()
int main (void)
Definition at line 11 of file abort.c.
            {
     struct sigaction sa;
     sa.sa_sigaction = handler;
     sa.sa_flags = SA_SIGINFO;
     sigemptyset(&sa.sa_mask);
     int ret = sigaction(SIGABRT, &sa, NULL);
     assert(!ret);
     abort();
 }
References abort(), assert, handler(), NULL, ret, sigaction::sa_flags, sigaction::sa_mask, sigaction::sa_sigaction, SA_SIGINFO, SIGABRT, sigaction(), and sigemptyset().