Fennix: Drivers/library/stdcpp.cpp File Reference
stdcpp.cpp File Reference
#include <base.h>
#include <driver.h>
Functions
void * __new_alloc_page (std::size_t Size)
void __delete_alloc_page (void *Pointer)
void * operator new (std::size_t Size)
Overload new operator to allocate memory from the heap.
void * operator new[] (std::size_t Size)
void operator delete (void *Pointer)
Overload delete operator to free memory from the heap.
void operator delete[] (void *Pointer)
void operator delete (void *Pointer, std::size_t)
void operator delete[] (void *Pointer, std::size_t)
Variables
__driverAPI * API
Function Documentation
__delete_alloc_page()
void __delete_alloc_page (void * Pointer)
Definition at line 40 of file stdcpp.cpp.
 {
     API->FreePages(API->MajorID, Pointer, 1);
 }
References API, __driverAPI::FreePages, and __driverAPI::MajorID.
Referenced by operator delete(), and operator delete[]().
__new_alloc_page()
void* __new_alloc_page (std::size_t Size)
TODO: memory allocator we can't really call kernel's malloc because the kernel keep track of memory usage for each driver
maybe implement the allocator in vma?
Definition at line 31 of file stdcpp.cpp.
 {
     /* Do not allow allocations larger than 4 KiB */
     if (Size > PAGE_SIZE)
         asmv("ud2");
     return API->RequestPages(API->MajorID, 1);
 }
References API, asmv(), __driverAPI::MajorID, PAGE_SIZE, __driverAPI::RequestPages, and Size.
Referenced by operator new(), and operator new[]().
operator delete() [1/2]
void operator delete (void * Pointer)
Overload delete operator to free memory from the heap.
Parameters
Address Pointer to the memory to free
Definition at line 55 of file stdcpp.cpp.
 {
     __delete_alloc_page(Pointer);
 }
References __delete_alloc_page(), Buffer, Data, i, and Length.
operator delete() [2/2]
void operator delete (void * Pointer, std::size_t)
Definition at line 65 of file stdcpp.cpp.
 {
     __delete_alloc_page(Pointer);
 }
References __delete_alloc_page().
operator delete[]() [1/2]
void operator delete[] (void * Pointer)
Definition at line 60 of file stdcpp.cpp.
 {
     __delete_alloc_page(Pointer);
 }
References __delete_alloc_page().
operator delete[]() [2/2]
void operator delete[] (void * Pointer, std::size_t)
Definition at line 70 of file stdcpp.cpp.
 {
     __delete_alloc_page(Pointer);
 }
References __delete_alloc_page().
operator new()
void* operator new (std::size_t Size)
Overload new operator to allocate memory from the heap.
Parameters
Size Unused
Returns
void* Pointer to the allocated memory
Definition at line 45 of file stdcpp.cpp.
 {
     return __new_alloc_page(Size);
 }
References __new_alloc_page(), dst, i, Length, Size, and src.
operator new[]()
void* operator new[] (std::size_t Size)
Definition at line 50 of file stdcpp.cpp.
 {
     return __new_alloc_page(Size);
 }
References __new_alloc_page(), and Size.
Variable Documentation
API
__driverAPI* API extern
Definition at line 23 of file base.c.
Referenced by __delete_alloc_page(), and __new_alloc_page().