Fennix Kernel: Kernel/Architecture/amd64/Bootstrap/Multiboot/2/Multiboot64bitMap.cpp File Reference
Multiboot64bitMap.cpp File Reference
#include <types.h>
Data Structures
struct PageTable4
class PageMapIndexer
Functions
union __attribute__ ((packed)) PageTableEntry
struct PageTable4 __attribute__ ((aligned(0x1000)))
__attribute__ ((section(".bootstrap.data"))) static PageTable4 *BPTable
__always_inline SafeFunction NIF void * RequestPage ()
__attribute__ ((section(".bootstrap.text"))) SafeFunction NIF void MB2_64_Map(void *VirtualAddress
if (!PML4.Present)
if (!PDPTE.Present)
if (!PDE.Present)
PTE SetAddress ((uintptr_t) PhysicalAddress >> 12)
asmv ("invlpg (%0)" ::"r"(VirtualAddress) :"memory")
Variables
PageMapLevel4 Entries [512] = PML4
char BootPageTable []
uintptr_t _kernel_start
uintptr_t _kernel_end
class PageMapIndexer __attribute__
void * PhysicalAddress
void uint64_t Flags
uint64_t DirectoryFlags = Flags & 0x3F
PageMapLevel4 PML4 = BPTable->Entries[Index.PMLIndex]
PageDirectoryPointerTableEntryPtr * PDPTEPtr = nullptr
PML4 raw = DirectoryFlags
PageDirectoryPointerTableEntry PDPTE = PDPTEPtr->Entries[Index.PDPTEIndex]
PageDirectoryEntryPtr * PDEPtr = nullptr
PageDirectoryEntry PDE = PDEPtr->Entries[Index.PDEIndex]
PageTableEntryPtr * PTEPtr = nullptr
PageTableEntry PTE = PTEPtr->Entries[Index.PTEIndex]
PTE Present = true
Data Structure Documentation
PageTable4
struct PageTable4
Definition at line 153 of file Multiboot64bitMap.cpp.
Data Fields
PageMapLevel4 Entries[512]
Function Documentation
__attribute__() [1/4]
struct PageTable4 __attribute__ ((aligned(0x1000)))
__attribute__() [2/4]
union __attribute__ ((packed))
Definition at line 1 of file Multiboot64bitMap.cpp.
 {
     struct
     {
         bool Present : 1;            // 0
         bool ReadWrite : 1;          // 1
         bool UserSupervisor : 1;     // 2
         bool WriteThrough : 1;       // 3
         bool CacheDisable : 1;       // 4
         bool Accessed : 1;           // 5
         bool Dirty : 1;              // 6
         bool PageAttributeTable : 1; // 7
         bool Global : 1;             // 8
         uint8_t Available0 : 3;      // 9-11
         uint64_t Address : 40;       // 12-51
         uint32_t Available1 : 7;     // 52-58
         uint8_t ProtectionKey : 4;   // 59-62
         bool ExecuteDisable : 1;     // 63
     };
     uint64_t raw;
     __always_inline inline SafeFunction NIF void SetAddress(uintptr_t _Address)
     {
         _Address &= 0x000000FFFFFFFFFF;
         this->raw &= 0xFFF0000000000FFF;
         this->raw |= (_Address << 12);
     }
     __always_inline inline SafeFunction NIF uintptr_t GetAddress() { return (this->raw & 0x000FFFFFFFFFF000) >> 12; }
 };
References __always_inline, Address, NIF, Present, raw, SafeFunction, and SetAddress().
__attribute__() [3/4]
__attribute__ ((section(".bootstrap.data")))
__attribute__() [4/4]
__attribute__ ((section(".bootstrap.text")))
Definition at line 283 of file Multiboot64bitMap.cpp.
 {
     BPTable = (PageTable4 *)BootPageTable;
     uintptr_t KernelStart = (uintptr_t)&_kernel_start;
     uintptr_t KernelEnd = (uintptr_t)&_kernel_end;
     uintptr_t PhysicalStart = KernelStart - 0xFFFFFFFF80000000;
     for (uintptr_t i = KernelStart; i < KernelEnd; i += 0x1000)
     {
         MB2_64_Map((void *)i, (void *)PhysicalStart, 0x3);
         PhysicalStart += 0x1000;
     }
     asmv("mov %%cr3, %%rax\n"
          "mov %%rax, %%cr3\n"
          :
          :
          : "rax");
 }
References _kernel_end, _kernel_start, asmv(), and BootPageTable.
asmv()
asmv ("invlpg (%0)" ::"r"(VirtualAddress) :"memory")
Referenced by __aligned(), __attribute__(), __chk_fail(), __convert_chk_fail(), __cyg_profile_func_enter(), __cyg_profile_func_exit(), __stack_chk_fail(), SMAP::_clac(), FXSR::_fxrstor64(), FXSR::_fxsave64(), SMAP::_stac(), CPU::MemBar::Barrier(), CPU::CheckSIMD(), CPU::Counter(), x32::cpuid(), x64::cpuid(), CrashHandler::DisplayDetailsScreen(), Entry(), CPU::MemBar::Fence(), x32::fxrstor(), x64::fxrstor(), x32::fxsave(), x64::fxsave(), CPU::x86::AMD::CPUID0x00000000::Get(), CPU::x86::AMD::CPUID0x00000001::Get(), CPU::x86::AMD::CPUID0x00000005::Get(), CPU::x86::AMD::CPUID0x00000006::Get(), CPU::x86::AMD::CPUID0x00000007::Get(), CPU::x86::AMD::CPUID0x0000000B_ECX_0::Get(), CPU::x86::AMD::CPUID0x0000000B_ECX_1::Get(), CPU::x86::AMD::CPUID0x0000000D_ECX_0::Get(), CPU::x86::AMD::CPUID0x0000000D_ECX_1::Get(), CPU::x86::AMD::CPUID0x0000000D_ECX_2::Get(), CPU::x86::AMD::CPUID0x0000000D_ECX_11::Get(), CPU::x86::AMD::CPUID0x0000000D_ECX_12::Get(), CPU::x86::AMD::CPUID0x0000000D_ECX_3E::Get(), CPU::x86::AMD::CPUID0x80000000::Get(), CPU::x86::AMD::CPUID0x80000001::Get(), CPU::x86::AMD::CPUID0x80000002::Get(), CPU::x86::AMD::CPUID0x80000003::Get(), CPU::x86::AMD::CPUID0x80000004::Get(), CPU::x86::AMD::CPUID0x80000005::Get(), CPU::x86::AMD::CPUID0x80000006::Get(), CPU::x86::AMD::CPUID0x80000007::Get(), CPU::x86::AMD::CPUID0x80000008::Get(), CPU::x86::AMD::CPUID0x8000000A::Get(), CPU::x86::AMD::CPUID0x80000019::Get(), CPU::x86::AMD::CPUID0x8000001A::Get(), CPU::x86::AMD::CPUID0x8000001B::Get(), CPU::x86::AMD::CPUID0x8000001C::Get(), CPU::x86::AMD::CPUID0x8000001D::Get(), CPU::x86::AMD::CPUID0x8000001E::Get(), CPU::x86::AMD::CPUID0x8000001F::Get(), CPU::x86::AMD::CPUID0x80000020::Get(), CPU::x86::AMD::CPUID0x80000021::Get(), CPU::x86::AMD::CPUID0x80000022::Get(), CPU::x86::AMD::CPUID0x80000023::Get(), CPU::x86::AMD::CPUID0x80000026::Get(), CPU::x86::Intel::CPUID0x00000000::Get(), CPU::x86::Intel::CPUID0x00000001::Get(), CPU::x86::Intel::CPUID0x00000002::Get(), CPU::x86::Intel::CPUID0x00000003::Get(), CPU::x86::Intel::CPUID0x00000004_1::Get(), CPU::x86::Intel::CPUID0x00000005::Get(), CPU::x86::Intel::CPUID0x00000006::Get(), CPU::x86::Intel::CPUID0x00000007_0::Get(), CPU::x86::Intel::CPUID0x00000007_1::Get(), CPU::x86::Intel::CPUID0x0000000A::Get(), CPU::x86::Intel::CPUID0x00000015::Get(), CPU::x86::Intel::CPUID0x00000016::Get(), CPU::x86::Intel::CPUID0x80000000::Get(), CPU::x86::Intel::CPUID0x80000001::Get(), CPU::x86::Intel::CPUID0x80000002::Get(), CPU::x86::Intel::CPUID0x80000003::Get(), CPU::x86::Intel::CPUID0x80000004::Get(), CPU::x86::Intel::CPUID0x80000006::Get(), CPU::x86::Intel::CPUID0x80000008::Get(), CPU::x86::Intel::CPUID0x8000000A::Get(), Halt(), CrashHandler::Handle(), CPU::Hypervisor(), GlobalDescriptorTable::Init(), InitLimine(), InitLimineAfterStack(), CPU::Interrupts(), x32::invlpg(), x64::invlpg(), x32::lgdt(), x64::lgdt(), x32::lidt(), x64::lidt(), CPU::MemBar::LoadFence(), x32::ltr(), x64::ltr(), memcpy_sse(), memcpy_sse2(), memcpy_sse3(), memcpy_sse4_1(), memcpy_sse4_2(), memcpy_ssse3(), memset_sse4_2(), CPU::Name(), CPU::PageTable(), CPU::Pause(), Random::rand16(), Random::rand32(), Random::rand64(), Tasking::Task::Schedule(), GlobalDescriptorTable::SetKernelStack(), StartCPU(), CPU::MemBar::StoreFence(), sys_fork(), UserModeExceptionHandler(), and CPU::Vendor().
if() [1/3]
if (!PDE. Present)
Definition at line 251 of file Multiboot64bitMap.cpp.
     {
         PTEPtr = (PageTableEntryPtr *)RequestPage();
         if (PTEPtr == nullptr)
             return;
         {
             void *ptr = PTEPtr;
             uint8_t value = 0;
             size_t num = 0x1000;
             uint8_t *p = (uint8_t *)ptr;
             for (size_t i = 0; i < num; i++)
                 p[i] = value;
         }
         PDE.Present = true;
         PDE.SetAddress((uintptr_t)PTEPtr >> 12);
     }
References PDE, PTEPtr, and RequestPage().
if() [2/3]
if (!PDPTE. Present)
Definition at line 228 of file Multiboot64bitMap.cpp.
     {
         PDEPtr = (PageDirectoryEntryPtr *)RequestPage();
         if (PDEPtr == nullptr)
             return;
         {
             void *ptr = PDEPtr;
             uint8_t value = 0;
             size_t num = 0x1000;
             uint8_t *p = (uint8_t *)ptr;
             for (size_t i = 0; i < num; i++)
                 p[i] = value;
         }
         PDPTE.Present = true;
         PDPTE.SetAddress((uintptr_t)PDEPtr >> 12);
     }
References PDEPtr, PDPTE, and RequestPage().
if() [3/3]
if (!PML4. Present)
Definition at line 205 of file Multiboot64bitMap.cpp.
     {
         PDPTEPtr = (PageDirectoryPointerTableEntryPtr *)RequestPage();
         if (PDPTEPtr == nullptr)
             return;
         {
             void *ptr = PDPTEPtr;
             uint8_t value = 0;
             size_t num = 0x1000;
             uint8_t *p = (uint8_t *)ptr;
             for (size_t i = 0; i < num; i++)
                 p[i] = value;
         }
         PML4.Present = true;
         PML4.SetAddress((uintptr_t)PDPTEPtr >> 12);
     }
References PDPTEPtr, PML4, and RequestPage().
Referenced by AudioCodec97::CallbackHandler(), CrashHandler::DisplayDetailsScreen(), and Interrupts::MainInterruptHandler().
RequestPage()
__always_inline SafeFunction NIF void* RequestPage () inline
Definition at line 164 of file Multiboot64bitMap.cpp.
 {
     void *Page = (void *)(BootPageTable + BPT_Allocated);
     BPT_Allocated += 0x1000;
     if (BPT_Allocated >= 0x10000) /* The length of BootPageTable */
     {
         while (true)
             ;
     }
     return Page;
 }
References BootPageTable.
Referenced by if().
SetAddress()
PTE SetAddress ((uintptr_t) PhysicalAddress >> 12)
Referenced by __attribute__().
Variable Documentation
__attribute__
class PageMapIndexer __attribute__
_kernel_end
uintptr_t _kernel_end
Definition at line 159 of file Multiboot64bitMap.cpp.
Referenced by __attribute__(), CrashHandler::DisplayStackFrameScreen(), MapKernel(), multiboot_main(), CrashHandler::TraceFrames(), and CrashHandler::UserInput().
_kernel_start
uintptr_t _kernel_start extern
Referenced by __attribute__(), MapKernel(), and multiboot_main().
BootPageTable
char BootPageTable[]
Definition at line 158 of file Multiboot64bitMap.cpp.
Referenced by __attribute__(), and RequestPage().
DirectoryFlags
uint64_t DirectoryFlags = Flags & 0x3F
Definition at line 201 of file Multiboot64bitMap.cpp.
Entries
PTEPtr Entries = PML4
Definition at line 0 of file Multiboot64bitMap.cpp.
Referenced by Disk::Manager::FetchDisks(), GlobalDescriptorTable::Init(), PageFaultExceptionHandler(), and PCI::PCI::PCI().
Flags
void uint64_t Flags
Initial value:
{
    PageMapIndexer Index = PageMapIndexer((uintptr_t)VirtualAddress)
Definition at line 197 of file Multiboot64bitMap.cpp.
Referenced by AudioCodec97::CallbackHandler(), InterProcessCommunication::IPC::HandleSyscall(), CPU::Interrupts(), MapMemory(), APIC::APIC::RawRedirectIRQ(), sys_file_open(), sys_ipc(), sys_memory_map(), and Xalloc_MAP_MEMORY().
PDE
PageDirectoryEntry PDE = PDEPtr->Entries[Index.PDEIndex]
Definition at line 249 of file Multiboot64bitMap.cpp.
Referenced by if(), PageFaultExceptionHandler(), CrashHandler::UserInput(), and UserModeExceptionHandler().
PDEPtr
else PDEPtr = nullptr
Definition at line 227 of file Multiboot64bitMap.cpp.
Referenced by if().
PDPTE
PageDirectoryPointerTableEntry PDPTE = PDPTEPtr->Entries[Index.PDPTEIndex]
Definition at line 226 of file Multiboot64bitMap.cpp.
Referenced by if(), PageFaultExceptionHandler(), CrashHandler::UserInput(), and UserModeExceptionHandler().
PDPTEPtr
else PDPTEPtr = nullptr
Definition at line 204 of file Multiboot64bitMap.cpp.
Referenced by if().
PhysicalAddress
void* PhysicalAddress
Definition at line 197 of file Multiboot64bitMap.cpp.
Referenced by MapMemory(), sys_memory_map(), and Xalloc_MAP_MEMORY().
PML4
PageMapLevel4 PML4 = BPTable->Entries[Index.PMLIndex]
Definition at line 203 of file Multiboot64bitMap.cpp.
Referenced by if(), PageFaultExceptionHandler(), CrashHandler::UserInput(), and UserModeExceptionHandler().
Present
PTE Present = true
Definition at line 273 of file Multiboot64bitMap.cpp.
Referenced by __attribute__(), PageFaultExceptionHandler(), InterruptDescriptorTable::SetEntry(), and UserModeExceptionHandler().
PTE
PageTableEntry PTE = PTEPtr->Entries[Index.PTEIndex]
Definition at line 272 of file Multiboot64bitMap.cpp.
Referenced by PageFaultExceptionHandler(), CrashHandler::UserInput(), and UserModeExceptionHandler().
PTEPtr
else PTEPtr = nullptr
Definition at line 250 of file Multiboot64bitMap.cpp.
Referenced by if().
raw
unsigned long raw = DirectoryFlags
Definition at line 223 of file Multiboot64bitMap.cpp.
Referenced by __attribute__(), and PageFaultExceptionHandler().