Fennix: Userspace/apps/base/busybox/libbb/bb_strtonum.c File Reference
bb_strtonum.c File Reference
#include "libbb.h"
Functions
static unsigned long long ret_ERANGE (void)
static unsigned long long handle_errors (unsigned long long v, char **endp)
unsigned long long FAST_FUNC bb_strtoull (const char *arg, char **endp, int base)
long long FAST_FUNC bb_strtoll (const char *arg, char **endp, int base)
Function Documentation
bb_strtoll()
long long FAST_FUNC bb_strtoll (const char * arg, char ** endp, int base)
Definition at line 72 of file bb_strtonum.c.
 {
     unsigned long long v;
     char *endptr;
     char first;
     if (!endp) endp = &endptr;
     *endp = (char*) arg;
     /* Check for the weird "feature":
      * a "-" string is apparently a valid "number" for strto[u]l[l]!
      * It returns zero and errno is 0! :( */
     first = (arg[0] != '-' ? arg[0] : arg[1]);
     if (!isalnum(first)) return ret_ERANGE();
     errno = 0;
     v = strtoll(arg, endp, base);
     return handle_errors(v, endp);
 }
References base, errno, first, handle_errors(), isalnum, ret_ERANGE(), and strtoll().
Referenced by bb_strtoi(), bb_strtol(), conv_strtoll(), conv_strtoull(), and parse_datestr().
bb_strtoull()
unsigned long long FAST_FUNC bb_strtoull (const char * arg, char ** endp, int base)
Definition at line 54 of file bb_strtonum.c.
 {
     unsigned long long v;
     char *endptr;
     if (!endp) endp = &endptr;
     *endp = (char*) arg;
     /* strtoul("  -4200000000") returns 94967296, errno 0 (!) */
     /* I don't think that this is right. Preventing this... */
     if (!isalnum(arg[0])) return ret_ERANGE();
     /* not 100% correct for lib func, but convenient for the caller */
     errno = 0;
     v = strtoull(arg, endp, base);
     return handle_errors(v, endp);
 }
References base, errno, handle_errors(), isalnum, ret_ERANGE(), and strtoull().
Referenced by bb_strtou(), bb_strtoul(), conv_strtoull(), cut_out_ull_opt(), devmem_main(), factorize_numstr(), hexedit_main(), hush_main(), process_irq_counts(), read_cstate_counts(), and shell_builtin_ulimit().
handle_errors()
static unsigned long long handle_errors (unsigned long long v, char ** endp) static
Definition at line 38 of file bb_strtonum.c.
 {
     char next_ch = **endp;
     /* errno is already set to ERANGE by strtoXXX if value overflowed */
     if (next_ch) {
         /* "1234abcg" or out-of-range? */
         if (isalnum(next_ch) || errno)
             return ret_ERANGE();
         /* good number, just suspicious terminator */
         errno = EINVAL;
     }
     return v;
 }
References EINVAL, errno, isalnum, and ret_ERANGE().
Referenced by bb_strtoll(), and bb_strtoull().
ret_ERANGE()
static unsigned long long ret_ERANGE (void) static
Definition at line 32 of file bb_strtonum.c.
 {
     errno = ERANGE; /* this ain't as small as it looks (on glibc) */
     return ULLONG_MAX;
 }
References ERANGE, errno, and ULLONG_MAX.
Referenced by bb_strtoll(), bb_strtoull(), and handle_errors().