Fennix: Userspace/apps/base/bash/dispose_cmd.c File Reference
dispose_cmd.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "bashansi.h"
#include "shell.h"
Functions
void dispose_command (COMMAND *command)
void dispose_function_def_contents (FUNCTION_DEF *c)
void dispose_function_def (FUNCTION_DEF *c)
void dispose_word (WORD_DESC *w)
void dispose_word_desc (WORD_DESC *w)
void dispose_words (WORD_LIST *list)
void dispose_redirects (REDIRECT *list)
Variables
sh_obj_cache_t wdcache
sh_obj_cache_t wlcache
Function Documentation
dispose_command()
void dispose_command (COMMAND * command)
Definition at line 36 of file dispose_cmd.c.
 {
   if (command == 0)
     return;
   if (command->redirects)
     dispose_redirects (command->redirects);
   switch (command->type)
     {
     case cm_for:
 #if defined (SELECT_COMMAND)
     case cm_select:
 #endif
       {
     register FOR_COM *c;
 #if defined (SELECT_COMMAND)
     if (command->type == cm_select)
       c = (FOR_COM *)command->value.Select;
     else
 #endif
     c = command->value.For;
     dispose_word (c->name);
     dispose_words (c->map_list);
     dispose_command (c->action);
     free (c);
     break;
       }
 #if defined (ARITH_FOR_COMMAND)
     case cm_arith_for:
       {
     register ARITH_FOR_COM *c;
     c = command->value.ArithFor;
     dispose_words (c->init);
     dispose_words (c->test);
     dispose_words (c->step);
     dispose_command (c->action);
     free (c);
     break;
       }
 #endif /* ARITH_FOR_COMMAND */
     case cm_group:
       {
     dispose_command (command->value.Group->command);
     free (command->value.Group);
     break;
       }
     case cm_subshell:
       {
     dispose_command (command->value.Subshell->command);
     free (command->value.Subshell);
     break;
       }
     case cm_coproc:
       {
     free (command->value.Coproc->name);
     dispose_command (command->value.Coproc->command);
     free (command->value.Coproc);
     break;
       }
     case cm_case:
       {
     register CASE_COM *c;
     PATTERN_LIST *t, *p;
     c = command->value.Case;
     dispose_word (c->word);
     for (p = c->clauses; p; )
       {
         dispose_words (p->patterns);
         dispose_command (p->action);
         t = p;
         p = p->next;
         free (t);
       }
     free (c);
     break;
       }
     case cm_until:
     case cm_while:
       {
     register WHILE_COM *c;
     c = command->value.While;
     dispose_command (c->test);
     dispose_command (c->action);
     free (c);
     break;
       }
     case cm_if:
       {
     register IF_COM *c;
     c = command->value.If;
     dispose_command (c->test);
     dispose_command (c->true_case);
     dispose_command (c->false_case);
     free (c);
     break;
       }
     case cm_simple:
       {
     register SIMPLE_COM *c;
     c = command->value.Simple;
     dispose_words (c->words);
     dispose_redirects (c->redirects);
     free (c);
     break;
       }
     case cm_connection:
       {
     register CONNECTION *c;
     c = command->value.Connection;
     dispose_command (c->first);
     dispose_command (c->second);
     free (c);
     break;
       }
 #if defined (DPAREN_ARITHMETIC)
     case cm_arith:
       {
     register ARITH_COM *c;
     c = command->value.Arith;
     dispose_words (c->exp);
     free (c);
     break;
       }
 #endif /* DPAREN_ARITHMETIC */
 #if defined (COND_COMMAND)
     case cm_cond:
       {
     register COND_COM *c;
     c = command->value.Cond;
     dispose_cond_node (c);
     break;
       }
 #endif /* COND_COMMAND */
     case cm_function_def:
       {
     register FUNCTION_DEF *c;
     c = command->value.Function_def;
     dispose_function_def (c);
     break;
       }
     default:
       command_error ("dispose_command", CMDERR_BADTYPE, command->type, 0);
       break;
     }
   free (command);
 }
References c, cm_arith, cm_arith_for, cm_case, cm_cond, cm_connection, cm_coproc, cm_for, cm_function_def, cm_group, cm_if, cm_select, cm_simple, cm_subshell, cm_until, cm_while, CMDERR_BADTYPE, command_error(), dispose_function_def(), dispose_redirects(), dispose_word(), dispose_words(), free, p, command::redirects, t, command::type, and command::value.
Referenced by bind_function(), command_substitute(), delete_job(), dispose_function_def_contents(), dispose_variable_value(), execute_function(), named_function_string(), parse_and_execute(), parse_comsub(), parse_string(), parse_string_to_command(), pretty_print_loop(), print_function_def(), reader_loop(), and shell_execve().
dispose_function_def()
void dispose_function_def (FUNCTION_DEF * c)
Definition at line 237 of file dispose_cmd.c.
 {
   dispose_function_def_contents (c);
   free (c);
 }
References c, dispose_function_def_contents(), and free.
Referenced by dispose_command().
dispose_function_def_contents()
void dispose_function_def_contents (FUNCTION_DEF * c)
Definition at line 228 of file dispose_cmd.c.
 {
   dispose_word (c->name);
   dispose_command (c->command);
   FREE (c->source_file);
 }
References c, dispose_command(), dispose_word(), and FREE.
Referenced by dispose_function_def().
dispose_redirects()
void dispose_redirects (REDIRECT * list)
Definition at line 303 of file dispose_cmd.c.
 {
   register REDIRECT *t;
   while (list)
     {
       t = list;
       list = list->next;
       if (t->rflags & REDIR_VARASSIGN)
     dispose_word (t->redirector.filename);
       switch (t->instruction)
     {
     case r_reading_until:
     case r_deblank_reading_until:
       free (t->here_doc_eof);
     /*FALLTHROUGH*/
     case r_reading_string:
     case r_output_direction:
     case r_input_direction:
     case r_inputa_direction:
     case r_appending_to:
     case r_err_and_out:
     case r_append_err_and_out:
     case r_input_output:
     case r_output_force:
     case r_duplicating_input_word:
     case r_duplicating_output_word:
     case r_move_input_word:
     case r_move_output_word:
       dispose_word (t->redirectee.filename);
       /* FALLTHROUGH */
     default:
       break;
     }
       free (t);
     }
 }
References dispose_word(), free, list(), node::next, r_append_err_and_out, r_appending_to, r_deblank_reading_until, r_duplicating_input_word, r_duplicating_output_word, r_err_and_out, r_input_direction, r_input_output, r_inputa_direction, r_move_input_word, r_move_output_word, r_output_direction, r_output_force, r_reading_string, r_reading_until, REDIR_VARASSIGN, and t.
Referenced by cleanup_redirects(), dispose_command(), dispose_exec_redirects(), dispose_partial_redirects(), do_redirection_internal(), do_redirections(), execute_builtin_or_function(), execute_command_internal(), execute_in_subshell(), print_deferred_heredocs(), and print_redirection_list().
dispose_word()
void dispose_word (WORD_DESC * w)
Definition at line 246 of file dispose_cmd.c.
 {
   FREE (w->word);
   ocache_free (wdcache, WORD_DESC, w);
 }
References FREE, ocache_free, w, and wdcache.
Referenced by dispose_command(), dispose_function_def_contents(), dispose_redirects(), dispose_words(), expand_word_internal(), make_redirection(), parameter_brace_expand_rhs(), pos_params_modcase(), and pos_params_pat_subst().
dispose_word_desc()
void dispose_word_desc (WORD_DESC * w)
Definition at line 255 of file dispose_cmd.c.
 {
   w->word = 0;
   ocache_free (wdcache, WORD_DESC, w);
 }
References ocache_free, w, and wdcache.
Referenced by expand_word_internal(), param_expand(), parameter_brace_expand(), and parameter_brace_find_indir().
dispose_words()
void dispose_words (WORD_LIST * list)
Definition at line 264 of file dispose_cmd.c.
 {
   WORD_LIST *t;
   while (list)
     {
       t = list;
       list = list->next;
       dispose_word (t->word);
 #if 0
       free (t);
 #else
       ocache_free (wlcache, WORD_LIST, t);
 #endif
     }
 }
References dispose_word(), free, list(), node::next, ocache_free, t, and wlcache.
Referenced by bind_args(), clear_dollar_vars(), decode_prompt_string(), dispose_command(), dispose_saved_dollar_vars(), execute_case_command(), execute_for_command(), execute_simple_command(), expand_arith_string(), expand_string_for_patsub(), expand_string_if_necessary(), expand_string_leave_quoted(), expand_string_to_string_internal(), expand_word(), expand_word_internal(), expand_word_list_internal(), getpattern(), glob_expand_word_list(), invalidate_cached_quoted_dollar_at(), list_remove_pattern(), list_transform(), make_arith_for_command(), param_expand(), parameter_brace_expand(), parameter_brace_expand_error(), parameter_brace_expand_length(), parameter_brace_expand_rhs(), parameter_list_remove_pattern(), parameter_list_transform(), parse_compound_assignment(), parse_string_to_word_list(), pos_params(), pos_params_modcase(), pos_params_pat_subst(), print_builtin(), redirection_expand(), remember_args(), save_bash_argv(), separate_out_assignments(), shell_expand_word_list(), shift_args(), and string_rest_of_args().
Variable Documentation
wdcache
sh_obj_cache_t wdcache extern
Definition at line 52 of file make_cmd.c.
Referenced by alloc_word_desc(), cmd_init(), dispose_word(), and dispose_word_desc().
wlcache
sh_obj_cache_t wlcache
Definition at line 32 of file dispose_cmd.c.
Referenced by dispose_words().