Fennix: Userspace/apps/base/bash/lib/readline/rltty.c File Reference
rltty.c File Reference
#include <sys/types.h>
#include <signal.h>
#include <errno.h>
#include <stdio.h>
#include "rldefs.h"
#include "rltty.h"
#include "readline.h"
#include "rlprivate.h"
Data Structures
struct bsdtty
Macros
#define READLINE_LIBRARY
#define TPX_PREPPED 0x01
#define TPX_BRACKPASTE 0x02
#define TPX_METAKEY 0x04
#define SGTTY_SET 0x01
#define LFLAG_SET 0x02
#define TCHARS_SET 0x04
#define LTCHARS_SET 0x08
#define TIOTYPE struct bsdtty
#define ANYP (EVENP | ODDP)
#define SET_SPECIAL(sc, func) set_special_char(kmap, &ttybuff, sc, func)
#define RESET_SPECIAL(c)
Functions
static void set_winsize (int)
static void save_tty_chars (TIOTYPE *)
static int _get_tty_settings (int, TIOTYPE *)
static int get_tty_settings (int, TIOTYPE *)
static int _set_tty_settings (int, TIOTYPE *)
static int set_tty_settings (int, TIOTYPE *)
static void prepare_terminal_settings (int, TIOTYPE, TIOTYPE *)
static void set_special_char (Keymap, TIOTYPE *, int, rl_command_func_t *)
void rl_prep_terminal (int meta_flag)
void rl_deprep_terminal (void)
int rl_tty_set_echoing (int u)
int rl_restart_output (int count, int key)
int rl_stop_output (int count, int key)
static void _rl_bind_tty_special_chars (Keymap kmap, TIOTYPE ttybuff)
void rltty_set_default_bindings (Keymap kmap)
void rl_tty_set_default_bindings (Keymap kmap)
void rl_tty_unset_default_bindings (Keymap kmap)
int _rl_disable_tty_signals (void)
int _rl_restore_tty_signals (void)
Variables
int errno
rl_vintfunc_t * rl_prep_term_function = rl_prep_terminal
rl_voidfunc_t * rl_deprep_term_function = rl_deprep_terminal
static int terminal_prepped
static _RL_TTY_CHARS _rl_tty_chars
static _RL_TTY_CHARS _rl_last_tty_chars
static TIOTYPE otio
Data Structure Documentation
bsdtty
struct bsdtty
Definition at line 106 of file rltty.c.
Data Fields
int flags
int lflag
struct sgttyb sgttyb
Macro Definition Documentation
ANYP
#define ANYP (EVENP | ODDP)
LFLAG_SET
#define LFLAG_SET 0x02
Definition at line 102 of file rltty.c.
LTCHARS_SET
#define LTCHARS_SET 0x08
Definition at line 104 of file rltty.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 23 of file rltty.c.
RESET_SPECIAL
#define RESET_SPECIAL (c)
Value:
  if (c != -1 && kmap[(unsigned char)c].type == ISFUNC) \
    kmap[(unsigned char)c].function = rl_insert;
Definition at line 831 of file rltty.c.
SET_SPECIAL
#define SET_SPECIAL (sc, func) set_special_char(kmap, &ttybuff, sc, func)
Definition at line 815 of file rltty.c.
SGTTY_SET
#define SGTTY_SET 0x01
Definition at line 101 of file rltty.c.
TCHARS_SET
#define TCHARS_SET 0x04
Definition at line 103 of file rltty.c.
TIOTYPE
#define TIOTYPE struct bsdtty
Definition at line 118 of file rltty.c.
TPX_BRACKPASTE
#define TPX_BRACKPASTE 0x02
Definition at line 67 of file rltty.c.
TPX_METAKEY
#define TPX_METAKEY 0x04
Definition at line 68 of file rltty.c.
TPX_PREPPED
#define TPX_PREPPED 0x01
Definition at line 66 of file rltty.c.
Function Documentation
_get_tty_settings()
static int _get_tty_settings (int , TIOTYPE *) static
_rl_bind_tty_special_chars()
static void _rl_bind_tty_special_chars (Keymap kmap, TIOTYPE ttybuff) static
Definition at line 836 of file rltty.c.
 {
   if (ttybuff.flags & SGTTY_SET)
     {
       SET_SPECIAL (ttybuff.sgttyb.sg_erase, rl_rubout);
       SET_SPECIAL (ttybuff.sgttyb.sg_kill, rl_unix_line_discard);
     }
 #  if defined (TIOCGLTC)
   if (ttybuff.flags & LTCHARS_SET)
     {
       SET_SPECIAL (ttybuff.ltchars.t_werasc, rl_unix_word_rubout);
       SET_SPECIAL (ttybuff.ltchars.t_lnextc, rl_quoted_insert);
     }
 #  endif /* TIOCGLTC */
 }
References LTCHARS_SET, rl_quoted_insert(), rl_rubout(), rl_unix_line_discard(), rl_unix_word_rubout(), SET_SPECIAL, and SGTTY_SET.
Referenced by rl_prep_terminal(), and rltty_set_default_bindings().
_rl_disable_tty_signals()
int _rl_disable_tty_signals (void)
Definition at line 942 of file rltty.c.
 {
   return 0;
 }
Referenced by rl_quoted_insert().
_rl_restore_tty_signals()
int _rl_restore_tty_signals (void)
Definition at line 948 of file rltty.c.
 {
   return 0;
 }
Referenced by _rl_insert_next().
_set_tty_settings()
static int _set_tty_settings (int , TIOTYPE *) static
get_tty_settings()
static int get_tty_settings (int tty, TIOTYPE * tiop) static
Definition at line 170 of file rltty.c.
 {
   set_winsize (tty);
   tiop->flags = tiop->lflag = 0;
   errno = 0;
   if (ioctl (tty, TIOCGETP, &(tiop->sgttyb)) < 0)
     return -1;
   tiop->flags |= SGTTY_SET;
 #if defined (TIOCLGET)
   if (ioctl (tty, TIOCLGET, &(tiop->lflag)) == 0)
     tiop->flags |= LFLAG_SET;
 #endif
 #if defined (TIOCGETC)
   if (ioctl (tty, TIOCGETC, &(tiop->tchars)) == 0)
     tiop->flags |= TCHARS_SET;
 #endif
 #if defined (TIOCGLTC)
   if (ioctl (tty, TIOCGLTC, &(tiop->ltchars)) == 0)
     tiop->flags |= LTCHARS_SET;
 #endif
   return 0;
 }
References errno, ioctl(), LFLAG_SET, LTCHARS_SET, set_winsize(), SGTTY_SET, TCHARS_SET, TIOCGETC, TIOCGETP, and TIOCGLTC.
Referenced by rl_prep_terminal(), and rltty_set_default_bindings().
prepare_terminal_settings()
static void prepare_terminal_settings (int meta_flag, TIOTYPE oldtio, TIOTYPE * tiop) static
Definition at line 237 of file rltty.c.
 {
   _rl_echoing_p = (oldtio.sgttyb.sg_flags & ECHO);
   _rl_echoctl = (oldtio.sgttyb.sg_flags & ECHOCTL);
   /* Copy the original settings to the structure we're going to use for
      our settings. */
   tiop->sgttyb = oldtio.sgttyb;
   tiop->lflag = oldtio.lflag;
 #if defined (TIOCGETC)
   tiop->tchars = oldtio.tchars;
 #endif
 #if defined (TIOCGLTC)
   tiop->ltchars = oldtio.ltchars;
 #endif
   tiop->flags = oldtio.flags;
   /* First, the basic settings to put us into character-at-a-time, no-echo
      input mode. */
   tiop->sgttyb.sg_flags &= ~(ECHO | CRMOD);
   tiop->sgttyb.sg_flags |= CBREAK;
   /* If this terminal doesn't care how the 8th bit is used, then we can
      use it for the meta-key.  If only one of even or odd parity is
      specified, then the terminal is using parity, and we cannot. */
 #if !defined (ANYP)
 #  define ANYP (EVENP | ODDP)
 #endif
   if (((oldtio.sgttyb.sg_flags & ANYP) == ANYP) ||
       ((oldtio.sgttyb.sg_flags & ANYP) == 0))
     {
       tiop->sgttyb.sg_flags |= ANYP;
       /* Hack on local mode flags if we can. */
 #if defined (TIOCLGET)
 #  if defined (LPASS8)
       tiop->lflag |= LPASS8;
 #  endif /* LPASS8 */
 #endif /* TIOCLGET */
     }
 #if defined (TIOCGETC)
 #  if defined (USE_XON_XOFF)
   /* Get rid of terminal output start and stop characters. */
   tiop->tchars.t_stopc = -1; /* C-s */
   tiop->tchars.t_startc = -1; /* C-q */
   /* If there is an XON character, bind it to restart the output. */
   if (oldtio.tchars.t_startc != -1)
     rl_bind_key (oldtio.tchars.t_startc, rl_restart_output);
 #  endif /* USE_XON_XOFF */
   /* If there is an EOF char, bind _rl_eof_char to it. */
   if (oldtio.tchars.t_eofc != -1)
     _rl_eof_char = oldtio.tchars.t_eofc;
 #  if defined (NO_KILL_INTR)
   /* Get rid of terminal-generated SIGQUIT and SIGINT. */
   tiop->tchars.t_quitc = -1; /* C-\ */
   tiop->tchars.t_intrc = -1; /* C-c */
 #  endif /* NO_KILL_INTR */
 #endif /* TIOCGETC */
 #if defined (TIOCGLTC)
   /* Make the interrupt keys go away.  Just enough to make people happy. */
   tiop->ltchars.t_dsuspc = -1;  /* C-y */
   tiop->ltchars.t_lnextc = -1;  /* C-v */
 #endif /* TIOCGLTC */
 }
References _rl_echoctl, _rl_echoing_p, _rl_eof_char, ANYP, ECHO, ECHOCTL, rl_bind_key(), and rl_restart_output().
Referenced by rl_prep_terminal().
rl_deprep_terminal()
void rl_deprep_terminal (void)
Definition at line 680 of file rltty.c.
 {
   int tty;
   if (terminal_prepped == 0)
     return;
   /* Try to keep this function from being interrupted. */
   _rl_block_sigint ();
   tty = rl_instream ? fileno (rl_instream) : fileno (stdin);
   if (terminal_prepped & TPX_BRACKPASTE)
     {
       fprintf (rl_outstream, BRACK_PASTE_FINI);
       /* Since the last character in BRACK_PASTE_FINI is \r */
       _rl_last_c_pos = 0;
       if (rl_eof_found && (RL_ISSTATE (RL_STATE_TIMEOUT) == 0))
     fprintf (rl_outstream, "\n");
       else if (_rl_echoing_p == 0)
     fprintf (rl_outstream, "\n");
     }
   if (_rl_enable_keypad)
     _rl_control_keypad (0);
   fflush (rl_outstream);
   if (set_tty_settings (tty, &otio) < 0)
     {
       _rl_release_sigint ();
       return;
     }
   terminal_prepped = 0;
   RL_UNSETSTATE(RL_STATE_TERMPREPPED);
   _rl_release_sigint ();
 }
References _rl_block_sigint(), _rl_control_keypad(), _rl_echoing_p, _rl_enable_keypad, _rl_last_c_pos, _rl_release_sigint(), BRACK_PASTE_FINI, fflush(), fileno(), fprintf(), otio, rl_eof_found, rl_instream, RL_ISSTATE, rl_outstream, RL_STATE_TERMPREPPED, RL_STATE_TIMEOUT, RL_UNSETSTATE, set_tty_settings(), stdin, terminal_prepped, and TPX_BRACKPASTE.
rl_prep_terminal()
void rl_prep_terminal (int meta_flag)
Definition at line 597 of file rltty.c.
 {
   int tty, nprep;
   TIOTYPE tio;
   if (terminal_prepped)
     return;
   /* Try to keep this function from being INTerrupted. */
   _rl_block_sigint ();
   tty = rl_instream ? fileno (rl_instream) : fileno (stdin);
   if (get_tty_settings (tty, &tio) < 0)
     {
 #if defined (ENOTSUP)
       /* MacOS X and Linux, at least, lie about the value of errno if
      tcgetattr fails. */
       if (errno == ENOTTY || errno == EINVAL || errno == ENOTSUP)
 #else
       if (errno == ENOTTY || errno == EINVAL)
 #endif
     _rl_echoing_p = 1;      /* XXX */
       _rl_release_sigint ();
       return;
     }
   otio = tio;
   if (_rl_bind_stty_chars)
     {
 #if defined (VI_MODE)
       /* If editing in vi mode, make sure we restore the bindings in the
      insertion keymap no matter what keymap we ended up in. */
       if (rl_editing_mode == vi_mode)
     rl_tty_unset_default_bindings (vi_insertion_keymap);
       else
 #endif
     rl_tty_unset_default_bindings (_rl_keymap);
     }
   save_tty_chars (&otio);
   RL_SETSTATE(RL_STATE_TTYCSAVED);
   if (_rl_bind_stty_chars)
     {
 #if defined (VI_MODE)
       /* If editing in vi mode, make sure we set the bindings in the
      insertion keymap no matter what keymap we ended up in. */
       if (rl_editing_mode == vi_mode)
     _rl_bind_tty_special_chars (vi_insertion_keymap, tio);
       else
 #endif
     _rl_bind_tty_special_chars (_rl_keymap, tio);
     }
   prepare_terminal_settings (meta_flag, otio, &tio);
   if (set_tty_settings (tty, &tio) < 0)
     {
       _rl_release_sigint ();
       return;
     }
   if (_rl_enable_keypad)
     _rl_control_keypad (1);
   nprep = TPX_PREPPED;
   if (_rl_enable_bracketed_paste)
     {
       fprintf (rl_outstream, BRACK_PASTE_INIT);
       nprep |= TPX_BRACKPASTE;
     }
   fflush (rl_outstream);
   terminal_prepped = nprep;
   RL_SETSTATE(RL_STATE_TERMPREPPED);
   _rl_release_sigint ();
 }
References _rl_bind_stty_chars, _rl_bind_tty_special_chars(), _rl_block_sigint(), _rl_control_keypad(), _rl_echoing_p, _rl_enable_bracketed_paste, _rl_enable_keypad, _rl_keymap, _rl_release_sigint(), BRACK_PASTE_INIT, EINVAL, ENOTSUP, ENOTTY, errno, fflush(), fileno(), fprintf(), get_tty_settings(), otio, prepare_terminal_settings(), rl_editing_mode, rl_instream, rl_outstream, RL_SETSTATE, RL_STATE_TERMPREPPED, RL_STATE_TTYCSAVED, rl_tty_unset_default_bindings(), save_tty_chars(), set_tty_settings(), stdin, terminal_prepped, tio, TIOTYPE, TPX_BRACKPASTE, TPX_PREPPED, vi_insertion_keymap, and vi_mode.
rl_restart_output()
int rl_restart_output (int count, int key)
Definition at line 740 of file rltty.c.
 {
 #if defined (__MINGW32__)
   return 0;
 #else /* !__MING32__ */
   int fildes = fileno (rl_outstream);
 #if defined (TIOCSTART)
 #if defined (apollo)
   ioctl (&fildes, TIOCSTART, 0);
 #else
   ioctl (fildes, TIOCSTART, 0);
 #endif /* apollo */
 #else /* !TIOCSTART */
 #  if defined (TERMIOS_TTY_DRIVER)
 #    if defined (__ksr1__)
   if (ksrflow)
     {
       ksrflow = 0;
       tcflow (fildes, TCOON);
     }
 #    else /* !ksr1 */
   tcflow (fildes, TCOON);       /* Simulate a ^Q. */
 #    endif /* !ksr1 */
 #  else /* !TERMIOS_TTY_DRIVER */
 #    if defined (TCXONC)
   ioctl (fildes, TCXONC, TCOON);
 #    endif /* TCXONC */
 #  endif /* !TERMIOS_TTY_DRIVER */
 #endif /* !TIOCSTART */
   return 0;
 #endif /* !__MINGW32__ */
 }
References fileno(), ioctl(), rl_outstream, tcflow(), TCOON, TCXONC, and TIOCSTART.
Referenced by _rl_clean_up_for_exit(), and prepare_terminal_settings().
rl_stop_output()
int rl_stop_output (int count, int key)
Definition at line 777 of file rltty.c.
 {
 #if defined (__MINGW32__)
   return 0;
 #else
   int fildes = fileno (rl_instream);
 #if defined (TIOCSTOP)
 # if defined (apollo)
   ioctl (&fildes, TIOCSTOP, 0);
 # else
   ioctl (fildes, TIOCSTOP, 0);
 # endif /* apollo */
 #else /* !TIOCSTOP */
 # if defined (TERMIOS_TTY_DRIVER)
 #  if defined (__ksr1__)
   ksrflow = 1;
 #  endif /* ksr1 */
   tcflow (fildes, TCOOFF);
 # else
 #   if defined (TCXONC)
   ioctl (fildes, TCXONC, TCOON);
 #   endif /* TCXONC */
 # endif /* !TERMIOS_TTY_DRIVER */
 #endif /* !TIOCSTOP */
   return 0;
 #endif /* !__MINGW32__ */
 }
References fileno(), ioctl(), rl_instream, tcflow(), TCOOFF, TCOON, TCXONC, and TIOCSTOP.
rl_tty_set_default_bindings()
void rl_tty_set_default_bindings (Keymap kmap)
Definition at line 910 of file rltty.c.
 {
   rltty_set_default_bindings (kmap);
 }
References rltty_set_default_bindings().
Referenced by readline_default_bindings(), and reset_default_bindings().
rl_tty_set_echoing()
int rl_tty_set_echoing (int u)
Definition at line 724 of file rltty.c.
 {
   int o;
   o = _rl_echoing_p;
   _rl_echoing_p = u;
   return o;
 }
References _rl_echoing_p.
rl_tty_unset_default_bindings()
void rl_tty_unset_default_bindings (Keymap kmap)
Definition at line 920 of file rltty.c.
 {
   /* Don't bother before we've saved the tty special chars at least once. */
   if (RL_ISSTATE(RL_STATE_TTYCSAVED) == 0)
     return;
   RESET_SPECIAL (_rl_tty_chars.t_erase);
   RESET_SPECIAL (_rl_tty_chars.t_kill);
 #  if defined (VLNEXT) && defined (TERMIOS_TTY_DRIVER)
   RESET_SPECIAL (_rl_tty_chars.t_lnext);
 #  endif /* VLNEXT && TERMIOS_TTY_DRIVER */
 #  if defined (VWERASE) && defined (TERMIOS_TTY_DRIVER)
   RESET_SPECIAL (_rl_tty_chars.t_werase);
 #  endif /* VWERASE && TERMIOS_TTY_DRIVER */
 }
References RESET_SPECIAL, RL_ISSTATE, RL_STATE_TTYCSAVED, _rl_tty_chars::t_erase, _rl_tty_chars::t_kill, _rl_tty_chars::t_lnext, and _rl_tty_chars::t_werase.
Referenced by reset_default_bindings(), and rl_prep_terminal().
rltty_set_default_bindings()
void rltty_set_default_bindings (Keymap kmap)
Definition at line 894 of file rltty.c.
 {
 #if !defined (NO_TTY_DRIVER)
   TIOTYPE ttybuff;
   int tty;
   tty = fileno (rl_instream);
   if (get_tty_settings (tty, &ttybuff) == 0)
     _rl_bind_tty_special_chars (kmap, ttybuff);
 #endif
 }
References _rl_bind_tty_special_chars(), fileno(), get_tty_settings(), rl_instream, and TIOTYPE.
Referenced by rl_tty_set_default_bindings().
save_tty_chars()
static void save_tty_chars (TIOTYPE * tiop) static
Definition at line 133 of file rltty.c.
 {
   _rl_last_tty_chars = _rl_tty_chars;
   if (tiop->flags & SGTTY_SET)
     {
       _rl_tty_chars.t_erase = tiop->sgttyb.sg_erase;
       _rl_tty_chars.t_kill = tiop->sgttyb.sg_kill;
     }
   if (tiop->flags & TCHARS_SET)
     {
       _rl_intr_char = _rl_tty_chars.t_intr = tiop->tchars.t_intrc;
       _rl_quit_char = _rl_tty_chars.t_quit = tiop->tchars.t_quitc;
       _rl_tty_chars.t_start = tiop->tchars.t_startc;
       _rl_tty_chars.t_stop = tiop->tchars.t_stopc;
       _rl_tty_chars.t_eof = tiop->tchars.t_eofc;
       _rl_tty_chars.t_eol = '\n';
       _rl_tty_chars.t_eol2 = tiop->tchars.t_brkc;
     }
   if (tiop->flags & LTCHARS_SET)
     {
       _rl_susp_char = _rl_tty_chars.t_susp = tiop->ltchars.t_suspc;
       _rl_tty_chars.t_dsusp = tiop->ltchars.t_dsuspc;
       _rl_tty_chars.t_reprint = tiop->ltchars.t_rprntc;
       _rl_tty_chars.t_flush = tiop->ltchars.t_flushc;
       _rl_tty_chars.t_werase = tiop->ltchars.t_werasc;
       _rl_tty_chars.t_lnext = tiop->ltchars.t_lnextc;
     }
   _rl_tty_chars.t_status = -1;
 }
References _rl_intr_char, _rl_last_tty_chars, _rl_quit_char, _rl_susp_char, _rl_tty_chars, LTCHARS_SET, SGTTY_SET, _rl_tty_chars::t_dsusp, _rl_tty_chars::t_eof, _rl_tty_chars::t_eol, _rl_tty_chars::t_eol2, _rl_tty_chars::t_erase, _rl_tty_chars::t_flush, _rl_tty_chars::t_intr, _rl_tty_chars::t_kill, _rl_tty_chars::t_lnext, _rl_tty_chars::t_quit, _rl_tty_chars::t_reprint, _rl_tty_chars::t_start, _rl_tty_chars::t_status, _rl_tty_chars::t_stop, _rl_tty_chars::t_susp, _rl_tty_chars::t_werase, and TCHARS_SET.
Referenced by rl_prep_terminal().
set_special_char()
static void set_special_char (Keymap kmap, TIOTYPE * tiop, int sc, rl_command_func_t * func) static
Definition at line 825 of file rltty.c.
 {
   if (sc != -1 && kmap[(unsigned char)sc].type == ISFUNC)
     kmap[(unsigned char)sc].function = func;
 }
References ISFUNC, and type.
set_tty_settings()
static int set_tty_settings (int tty, TIOTYPE * tiop) static
Definition at line 200 of file rltty.c.
 {
   if (tiop->flags & SGTTY_SET)
     {
       ioctl (tty, TIOCSETN, &(tiop->sgttyb));
       tiop->flags &= ~SGTTY_SET;
     }
   _rl_echoing_p = 1;
 #if defined (TIOCLSET)
   if (tiop->flags & LFLAG_SET)
     {
       ioctl (tty, TIOCLSET, &(tiop->lflag));
       tiop->flags &= ~LFLAG_SET;
     }
 #endif
 #if defined (TIOCSETC)
   if (tiop->flags & TCHARS_SET)
     {
       ioctl (tty, TIOCSETC, &(tiop->tchars));
       tiop->flags &= ~TCHARS_SET;
     }
 #endif
 #if defined (TIOCSLTC)
   if (tiop->flags & LTCHARS_SET)
     {
       ioctl (tty, TIOCSLTC, &(tiop->ltchars));
       tiop->flags &= ~LTCHARS_SET;
     }
 #endif
   return 0;
 }
References _rl_echoing_p, ioctl(), LFLAG_SET, LTCHARS_SET, SGTTY_SET, TCHARS_SET, TIOCSETC, TIOCSETN, and TIOCSLTC.
Referenced by rl_deprep_terminal(), and rl_prep_terminal().
set_winsize()
static void set_winsize (int tty) static
Definition at line 83 of file rltty.c.
 {
 #if defined (TIOCGWINSZ)
   struct winsize w;
   if (ioctl (tty, TIOCGWINSZ, &w) == 0)
       (void) ioctl (tty, TIOCSWINSZ, &w);
 #endif /* TIOCGWINSZ */
 }
References ioctl(), TIOCGWINSZ, TIOCSWINSZ, and w.
Referenced by get_tty_settings().
Variable Documentation
_rl_last_tty_chars
_RL_TTY_CHARS _rl_last_tty_chars static
Definition at line 72 of file rltty.c.
Referenced by save_tty_chars().
_rl_tty_chars
_RL_TTY_CHARS _rl_tty_chars static
Definition at line 72 of file rltty.c.
Referenced by save_tty_chars().
errno
int errno extern
Referenced by get_tty_settings(), and rl_prep_terminal().
otio
TIOTYPE otio static
Definition at line 120 of file rltty.c.
Referenced by rl_deprep_terminal(), and rl_prep_terminal().
rl_deprep_term_function
rl_voidfunc_t* rl_deprep_term_function = rl_deprep_terminal
Definition at line 53 of file rltty.c.
Referenced by exit_shell(), readline(), rl_callback_handler_remove(), rl_callback_read_char(), and rl_cleanup_after_signal().
rl_prep_term_function
rl_vintfunc_t* rl_prep_term_function = rl_prep_terminal
Definition at line 52 of file rltty.c.
Referenced by _rl_callback_newline(), readline(), and rl_reset_after_signal().
terminal_prepped
int terminal_prepped static
Definition at line 70 of file rltty.c.
Referenced by rl_deprep_terminal(), and rl_prep_terminal().