Fennix: Userspace/apps/base/busybox/archival/libarchive/unxz/xz_lzma2.h File Reference
xz_lzma2.h File Reference
Macros
#define RC_SHIFT_BITS 8
#define RC_TOP_BITS 24
#define RC_TOP_VALUE (1 << RC_TOP_BITS)
#define RC_BIT_MODEL_TOTAL_BITS 11
#define RC_BIT_MODEL_TOTAL (1 << RC_BIT_MODEL_TOTAL_BITS)
#define RC_MOVE_BITS 5
#define POS_STATES_MAX (1 << 4)
#define STATES 12
#define LIT_STATES 7
#define LITERAL_CODER_SIZE 0x300
#define LITERAL_CODERS_MAX (1 << 4)
#define MATCH_LEN_MIN 2
#define LEN_LOW_BITS 3
#define LEN_LOW_SYMBOLS (1 << LEN_LOW_BITS)
#define LEN_MID_BITS 3
#define LEN_MID_SYMBOLS (1 << LEN_MID_BITS)
#define LEN_HIGH_BITS 8
#define LEN_HIGH_SYMBOLS (1 << LEN_HIGH_BITS)
#define LEN_SYMBOLS (LEN_LOW_SYMBOLS + LEN_MID_SYMBOLS + LEN_HIGH_SYMBOLS)
#define MATCH_LEN_MAX (MATCH_LEN_MIN + LEN_SYMBOLS - 1)
#define DIST_STATES 4
#define DIST_SLOT_BITS 6
#define DIST_SLOTS (1 << DIST_SLOT_BITS)
#define DIST_MODEL_START 4
#define DIST_MODEL_END 14
#define FULL_DISTANCES_BITS (DIST_MODEL_END / 2)
#define FULL_DISTANCES (1 << FULL_DISTANCES_BITS)
#define ALIGN_BITS 4
#define ALIGN_SIZE (1 << ALIGN_BITS)
#define ALIGN_MASK (ALIGN_SIZE - 1)
#define PROBS_TOTAL (1846 + LITERAL_CODERS_MAX * LITERAL_CODER_SIZE)
#define REPS 4
Enumerations
enum lzma_state {
STATE_LIT_LIT , STATE_MATCH_LIT_LIT , STATE_REP_LIT_LIT , STATE_SHORTREP_LIT_LIT ,
STATE_MATCH_LIT , STATE_REP_LIT , STATE_SHORTREP_LIT , STATE_LIT_MATCH ,
STATE_LIT_LONGREP , STATE_LIT_SHORTREP , STATE_NONLIT_MATCH , STATE_NONLIT_REP
}
Functions
static void XZ_FUNC lzma_state_literal (enum lzma_state *state)
static void XZ_FUNC lzma_state_match (enum lzma_state *state)
static void XZ_FUNC lzma_state_long_rep (enum lzma_state *state)
static void XZ_FUNC lzma_state_short_rep (enum lzma_state *state)
static bool XZ_FUNC lzma_state_is_literal (enum lzma_state state)
static uint32_t XZ_FUNC lzma_get_dist_state (uint32_t len)
Macro Definition Documentation
ALIGN_BITS
#define ALIGN_BITS 4
Definition at line 190 of file xz_lzma2.h.
ALIGN_MASK
#define ALIGN_MASK (ALIGN_SIZE - 1)
Definition at line 192 of file xz_lzma2.h.
ALIGN_SIZE
#define ALIGN_SIZE (1 << ALIGN_BITS)
Definition at line 191 of file xz_lzma2.h.
DIST_MODEL_END
#define DIST_MODEL_END 14
Definition at line 180 of file xz_lzma2.h.
DIST_MODEL_START
#define DIST_MODEL_START 4
Definition at line 168 of file xz_lzma2.h.
DIST_SLOT_BITS
#define DIST_SLOT_BITS 6
Definition at line 158 of file xz_lzma2.h.
DIST_SLOTS
#define DIST_SLOTS (1 << DIST_SLOT_BITS)
Definition at line 159 of file xz_lzma2.h.
DIST_STATES
#define DIST_STATES 4
Definition at line 141 of file xz_lzma2.h.
FULL_DISTANCES
#define FULL_DISTANCES (1 << FULL_DISTANCES_BITS)
Definition at line 184 of file xz_lzma2.h.
FULL_DISTANCES_BITS
#define FULL_DISTANCES_BITS (DIST_MODEL_END / 2)
Definition at line 183 of file xz_lzma2.h.
LEN_HIGH_BITS
#define LEN_HIGH_BITS 8
Definition at line 125 of file xz_lzma2.h.
LEN_HIGH_SYMBOLS
#define LEN_HIGH_SYMBOLS (1 << LEN_HIGH_BITS)
Definition at line 126 of file xz_lzma2.h.
LEN_LOW_BITS
#define LEN_LOW_BITS 3
Definition at line 121 of file xz_lzma2.h.
LEN_LOW_SYMBOLS
#define LEN_LOW_SYMBOLS (1 << LEN_LOW_BITS)
Definition at line 122 of file xz_lzma2.h.
LEN_MID_BITS
#define LEN_MID_BITS 3
Definition at line 123 of file xz_lzma2.h.
LEN_MID_SYMBOLS
#define LEN_MID_SYMBOLS (1 << LEN_MID_BITS)
Definition at line 124 of file xz_lzma2.h.
LEN_SYMBOLS
#define LEN_SYMBOLS (LEN_LOW_SYMBOLS + LEN_MID_SYMBOLS + LEN_HIGH_SYMBOLS)
Definition at line 127 of file xz_lzma2.h.
LIT_STATES
#define LIT_STATES 7
Definition at line 61 of file xz_lzma2.h.
LITERAL_CODER_SIZE
#define LITERAL_CODER_SIZE 0x300
Definition at line 106 of file xz_lzma2.h.
LITERAL_CODERS_MAX
#define LITERAL_CODERS_MAX (1 << 4)
Definition at line 109 of file xz_lzma2.h.
MATCH_LEN_MAX
#define MATCH_LEN_MAX (MATCH_LEN_MIN + LEN_SYMBOLS - 1)
Definition at line 133 of file xz_lzma2.h.
MATCH_LEN_MIN
#define MATCH_LEN_MIN 2
Definition at line 112 of file xz_lzma2.h.
POS_STATES_MAX
#define POS_STATES_MAX (1 << 4)
Definition at line 27 of file xz_lzma2.h.
PROBS_TOTAL
#define PROBS_TOTAL (1846 + LITERAL_CODERS_MAX * LITERAL_CODER_SIZE)
Definition at line 195 of file xz_lzma2.h.
RC_BIT_MODEL_TOTAL
#define RC_BIT_MODEL_TOTAL (1 << RC_BIT_MODEL_TOTAL_BITS)
Definition at line 19 of file xz_lzma2.h.
RC_BIT_MODEL_TOTAL_BITS
#define RC_BIT_MODEL_TOTAL_BITS 11
Definition at line 18 of file xz_lzma2.h.
RC_MOVE_BITS
#define RC_MOVE_BITS 5
Definition at line 20 of file xz_lzma2.h.
RC_SHIFT_BITS
#define RC_SHIFT_BITS 8
Definition at line 15 of file xz_lzma2.h.
RC_TOP_BITS
#define RC_TOP_BITS 24
Definition at line 16 of file xz_lzma2.h.
RC_TOP_VALUE
#define RC_TOP_VALUE (1 << RC_TOP_BITS)
Definition at line 17 of file xz_lzma2.h.
REPS
#define REPS 4
Definition at line 202 of file xz_lzma2.h.
STATES
#define STATES 12
Definition at line 58 of file xz_lzma2.h.
Enumeration Type Documentation
lzma_state
enum lzma_state
Enumerator
STATE_LIT_LIT
STATE_MATCH_LIT_LIT
STATE_REP_LIT_LIT
STATE_SHORTREP_LIT_LIT
STATE_MATCH_LIT
STATE_REP_LIT
STATE_SHORTREP_LIT
STATE_LIT_MATCH
STATE_LIT_LONGREP
STATE_LIT_SHORTREP
STATE_NONLIT_MATCH
STATE_NONLIT_REP
Definition at line 42 of file xz_lzma2.h.
                 {
     STATE_LIT_LIT,
     STATE_MATCH_LIT_LIT,
     STATE_REP_LIT_LIT,
     STATE_SHORTREP_LIT_LIT,
     STATE_MATCH_LIT,
     STATE_REP_LIT,
     STATE_SHORTREP_LIT,
     STATE_LIT_MATCH,
     STATE_LIT_LONGREP,
     STATE_LIT_SHORTREP,
     STATE_NONLIT_MATCH,
     STATE_NONLIT_REP
 };
Function Documentation
lzma_get_dist_state()
static uint32_t XZ_FUNC lzma_get_dist_state (uint32_t len) inline static
Definition at line 147 of file xz_lzma2.h.
 {
     return len < DIST_STATES + MATCH_LEN_MIN
             ? len - MATCH_LEN_MIN : DIST_STATES - 1;
 }
References DIST_STATES, len, and MATCH_LEN_MIN.
Referenced by lzma_match().
lzma_state_is_literal()
static bool XZ_FUNC lzma_state_is_literal (enum lzma_state state) inline static
Definition at line 93 of file xz_lzma2.h.
 {
     return state < LIT_STATES;
 }
References LIT_STATES, and state.
Referenced by lzma_literal().
lzma_state_literal()
static void XZ_FUNC lzma_state_literal (enum lzma_state * state) inline static
Definition at line 64 of file xz_lzma2.h.
 {
     if (*state <= STATE_SHORTREP_LIT_LIT)
         *state = STATE_LIT_LIT;
     else if (*state <= STATE_LIT_SHORTREP)
         *state -= 3;
     else
         *state -= 6;
 }
References state, STATE_LIT_LIT, STATE_LIT_SHORTREP, and STATE_SHORTREP_LIT_LIT.
Referenced by lzma_literal().
lzma_state_long_rep()
static void XZ_FUNC lzma_state_long_rep (enum lzma_state * state) inline static
Definition at line 81 of file xz_lzma2.h.
 {
     *state = *state < LIT_STATES ? STATE_LIT_LONGREP : STATE_NONLIT_REP;
 }
References LIT_STATES, state, STATE_LIT_LONGREP, and STATE_NONLIT_REP.
Referenced by lzma_rep_match().
lzma_state_match()
static void XZ_FUNC lzma_state_match (enum lzma_state * state) inline static
Definition at line 75 of file xz_lzma2.h.
 {
     *state = *state < LIT_STATES ? STATE_LIT_MATCH : STATE_NONLIT_MATCH;
 }
References LIT_STATES, state, STATE_LIT_MATCH, and STATE_NONLIT_MATCH.
Referenced by lzma_match().
lzma_state_short_rep()
static void XZ_FUNC lzma_state_short_rep (enum lzma_state * state) inline static
Definition at line 87 of file xz_lzma2.h.
 {
     *state = *state < LIT_STATES ? STATE_LIT_SHORTREP : STATE_NONLIT_REP;
 }
References LIT_STATES, state, STATE_LIT_SHORTREP, and STATE_NONLIT_REP.
Referenced by lzma_rep_match().