Fennix Kernel: Kernel/syscalls/linux.cpp File Reference
linux.cpp File Reference
#include <syscall/linux/syscalls_amd64.hpp>
#include <syscall/linux/syscalls_i386.hpp>
#include <syscall/linux/signals.hpp>
#include <syscall/linux/defs.hpp>
#include <syscalls.hpp>
#include <signal.hpp>
#include <utsname.h>
#include <rand.hpp>
#include <limits.h>
#include <exec.hpp>
#include <debug.h>
#include <cpu.hpp>
#include <time.h>
#include <memory.hpp>
#include <ini.h>
#include "../kernel.h"
#include "../syscalls.h"
Data Structures
struct SyscallData
Macros
#define INI_IMPLEMENTATION
#define WCONTINUED 1
#define WNOHANG 2
#define WUNTRACED 4
#define WEXITED 8
#define WNOWAIT 16
#define WSTOPPED 32
Functions
void linux_fork_return (void *tableAddr)
static ssize_t linux_read (SysFrm *, int fd, void *buf, size_t count)
static ssize_t linux_write (SysFrm *, int fd, const void *buf, size_t count)
static int linux_open (SysFrm *sf, const char *pathname, int flags, mode_t mode)
static int linux_close (SysFrm *, int fd)
static int linux_stat (SysFrm *, const char *pathname, struct stat *statbuf)
static int linux_fstat (SysFrm *, int fd, struct stat *statbuf)
static int linux_lstat (SysFrm *, const char *pathname, struct stat *statbuf)
static off_t linux_lseek (SysFrm *, int fd, off_t offset, int whence)
static void * linux_mmap (SysFrm *, void *addr, size_t length, int prot, int flags, int fildes, off_t offset)
static int linux_mprotect (SysFrm *, void *addr, size_t len, int prot)
static int linux_munmap (SysFrm *, void *addr, size_t length)
static void * linux_brk (SysFrm *, void *addr)
static int linux_ioctl (SysFrm *, int fd, unsigned long request, void *argp)
static ssize_t linux_readv (SysFrm *sf, int fildes, const struct iovec *iov, int iovcnt)
static ssize_t linux_writev (SysFrm *sf, int fildes, const struct iovec *iov, int iovcnt)
static int linux_pipe (SysFrm *, int pipefd[2])
static int linux_dup (SysFrm *, int oldfd)
static int linux_dup2 (SysFrm *, int oldfd, int newfd)
static int linux_pause (SysFrm *)
static int linux_nanosleep (SysFrm *, const struct timespec *req, struct timespec *rem)
static pid_t linux_getpid (SysFrm *)
static int linux_shutdown (SysFrm *, int sockfd, int how)
static pid_t linux_fork (SysFrm *sf)
static int linux_execve (SysFrm *sf, const char *pathname, char *const argv[], char *const envp[])
static __noreturn void linux_exit (SysFrm *, int status)
static pid_t linux_wait4 (SysFrm *, pid_t pid, int *wstatus, int options, struct rusage *rusage)
static int linux_kill (SysFrm *, pid_t pid, int sig)
static int linux_uname (SysFrm *, struct utsname *buf)
static int linux_fcntl (SysFrm *, int fd, int cmd, void *arg)
static int linux_creat (SysFrm *, const char *pathname, mode_t mode)
static int linux_mkdir (SysFrm *, const char *pathname, mode_t mode)
static ssize_t linux_readlink (SysFrm *, const char *pathname, char *buf, size_t bufsiz)
static uid_t linux_getuid (SysFrm *)
static pid_t linux_getppid (SysFrm *)
static int linux_arch_prctl (SysFrm *, int code, unsigned long addr)
static int linux_reboot (SysFrm *, int magic, int magic2, int cmd, void *arg)
static int linux_sigaction (SysFrm *, int signum, const struct sigaction *act, struct sigaction *oldact)
static int linux_sigprocmask (SysFrm *, int how, const sigset_t *set, sigset_t *oldset, size_t sigsetsize)
static void linux_sigreturn (SysFrm *sf)
static pid_t linux_gettid (SysFrm *)
static pid_t linux_set_tid_address (SysFrm *, int *tidptr)
static ssize_t linux_getdents64 (SysFrm *, int fd, struct linux_dirent64 *dirp, size_t count)
static int linux_clock_gettime (SysFrm *, clockid_t clockid, struct timespec *tp)
static __noreturn void linux_exit_group (SysFrm *sf, int status)
static int linux_tgkill (SysFrm *sf, pid_t tgid, pid_t tid, int sig)
static long linux_newfstatat (SysFrm *, int dfd, const char *filename, struct stat *statbuf, int flag)
static int linux_pipe2 (SysFrm *sf, int pipefd[2], int flags)
static int linux_prlimit64 (SysFrm *, pid_t pid, int resource, const struct rlimit *new_limit, struct rlimit *old_limit)
static ssize_t linux_getrandom (SysFrm *, void *buf, size_t buflen, unsigned int flags)
uintptr_t HandleLinuxSyscalls (SyscallsFrame *Frame)
Variables
static SyscallData LinuxSyscallsTableAMD64 []
static SyscallData LinuxSyscallsTableI386 []
Data Structure Documentation
SyscallData
struct SyscallData
Definition at line 42 of file linux.cpp.
Data Fields
void * Handler
const char * Name
int RequiredID
Macro Definition Documentation
INI_IMPLEMENTATION
#define INI_IMPLEMENTATION
Definition at line 34 of file linux.cpp.
WCONTINUED
#define WCONTINUED 1
WEXITED
#define WEXITED 8
WNOHANG
#define WNOHANG 2
WNOWAIT
#define WNOWAIT 16
WSTOPPED
#define WSTOPPED 32
WUNTRACED
#define WUNTRACED 4
Function Documentation
HandleLinuxSyscalls()
uintptr_t HandleLinuxSyscalls (SyscallsFrame * Frame)
Definition at line 2806 of file linux.cpp.
 {
 #if defined(a64)
     if (Frame->rax > sizeof(LinuxSyscallsTableAMD64) / sizeof(SyscallData))
     {
         fixme("Syscall %d not implemented",
               Frame->rax);
         return -ENOSYS;
     }
     SyscallData Syscall = LinuxSyscallsTableAMD64[Frame->rax];
     long (*call)(SysFrm *, long, ...) = r_cst(long (*)(SysFrm *, long, ...),
                                               Syscall.Handler);
     if (unlikely(!call))
     {
         fixme("Syscall %s(%d) not implemented.",
               Syscall.Name, Frame->rax);
         return -ENOSYS;
     }
     debug("> [%d:\"%s\"]( %#lx  %#lx  %#lx  %#lx  %#lx  %#lx )",
           Frame->rax, Syscall.Name,
           Frame->rdi, Frame->rsi, Frame->rdx,
           Frame->r10, Frame->r8, Frame->r9);
     long sc_ret = call(Frame,
                        Frame->rdi, Frame->rsi, Frame->rdx,
                        Frame->r10, Frame->r8, Frame->r9);
     debug("< [%d:\"%s\"] = %d", Frame->rax, Syscall.Name, sc_ret);
     return sc_ret;
 #elif defined(a32)
     if (Frame->eax > sizeof(LinuxSyscallsTableI386) / sizeof(SyscallData))
     {
         fixme("Syscall %d not implemented",
               Frame->eax);
         return -ENOSYS;
     }
     SyscallData Syscall = LinuxSyscallsTableI386[Frame->eax];
     long (*call)(SysFrm *, long, ...) = r_cst(long (*)(SysFrm *, long, ...),
                                               Syscall.Handler);
     if (unlikely(!call))
     {
         fixme("Syscall %s(%d) not implemented.",
               Syscall.Name, Frame->eax);
         return -ENOSYS;
     }
     debug("> [%d:\"%s\"]( %#lx  %#lx  %#lx  %#lx  %#lx  %#lx )",
           Frame->eax, Syscall.Name,
           Frame->ebx, Frame->ecx, Frame->edx,
           Frame->esi, Frame->edi, Frame->ebp);
     int sc_ret = call(Frame,
                       Frame->ebx, Frame->ecx, Frame->edx,
                       Frame->esi, Frame->edi, Frame->ebp);
     debug("< [%d:\"%s\"] = %d", Frame->eax, Syscall.Name, sc_ret);
     return sc_ret;
 #elif defined(aa64)
     return -ENOSYS;
 #endif
 #if defined(a64)
     UNUSED(LinuxSyscallsTableI386);
 #elif defined(a32)
     UNUSED(LinuxSyscallsTableAMD64);
 #endif
 }
References debug, ENOSYS, fixme, SyscallData::Handler, LinuxSyscallsTableAMD64, LinuxSyscallsTableI386, SyscallData::Name, SysFrm, unlikely, and UNUSED.
Referenced by SystemCallsHandler().
linux_arch_prctl()
static int linux_arch_prctl (SysFrm * , int code, unsigned long addr) static
Definition at line 1354 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check((void *)addr))
     {
         debug("Invalid address %#lx", addr);
         return -EFAULT;
     }
     if (!vmm.Check((void *)addr, Memory::US))
     {
         debug("Address %#lx is not user accessible", addr);
         return -EPERM;
     }
     switch (code)
     {
     case ARCH_SET_GS:
     {
 #if defined(a64)
         CPU::x64::wrmsr(CPU::x64::MSRID::MSR_GS_BASE, addr);
 #elif defined(a32)
         CPU::x32::wrmsr(CPU::x32::MSRID::MSR_GS_BASE, addr);
 #endif
         return 0;
     }
     case ARCH_SET_FS:
     {
 #if defined(a64)
         CPU::x64::wrmsr(CPU::x64::MSRID::MSR_FS_BASE, addr);
 #elif defined(a32)
         CPU::x32::wrmsr(CPU::x32::MSRID::MSR_FS_BASE, addr);
 #endif
         return 0;
     }
     case ARCH_GET_FS:
     {
 #if defined(a64)
         *r_cst(uint64_t *, addr) =
             CPU::x64::rdmsr(CPU::x64::MSRID::MSR_FS_BASE);
 #elif defined(a32)
         *r_cst(uint64_t *, addr) =
             CPU::x32::rdmsr(CPU::x32::MSRID::MSR_FS_BASE);
 #endif
         return 0;
     }
     case ARCH_GET_GS:
     {
 #if defined(a64)
         *r_cst(uint64_t *, addr) =
             CPU::x64::rdmsr(CPU::x64::MSRID::MSR_GS_BASE);
 #elif defined(a32)
         *r_cst(uint64_t *, addr) =
             CPU::x32::rdmsr(CPU::x32::MSRID::MSR_GS_BASE);
 #endif
         return 0;
     }
     case ARCH_GET_CPUID:
     case ARCH_SET_CPUID:
     case ARCH_GET_XCOMP_SUPP:
     case ARCH_GET_XCOMP_PERM:
     case ARCH_REQ_XCOMP_PERM:
     case ARCH_GET_XCOMP_GUEST_PERM:
     case ARCH_REQ_XCOMP_GUEST_PERM:
     case ARCH_XCOMP_TILECFG:
     case ARCH_XCOMP_TILEDATA:
     case ARCH_MAP_VDSO_X32:
     case ARCH_MAP_VDSO_32:
     case ARCH_MAP_VDSO_64:
     case ARCH_GET_UNTAG_MASK:
     case ARCH_ENABLE_TAGGED_ADDR:
     case ARCH_GET_MAX_TAG_BITS:
     case ARCH_FORCE_TAGGED_SVA:
     {
         fixme("Code %#lx not implemented", code);
         return -ENOSYS;
     }
     default:
     {
         debug("Invalid code %#lx", code);
         return -EINVAL;
     }
     }
 }
References addr, ARCH_ENABLE_TAGGED_ADDR, ARCH_FORCE_TAGGED_SVA, ARCH_GET_CPUID, ARCH_GET_FS, ARCH_GET_GS, ARCH_GET_MAX_TAG_BITS, ARCH_GET_UNTAG_MASK, ARCH_GET_XCOMP_GUEST_PERM, ARCH_GET_XCOMP_PERM, ARCH_GET_XCOMP_SUPP, ARCH_MAP_VDSO_32, ARCH_MAP_VDSO_64, ARCH_MAP_VDSO_X32, ARCH_REQ_XCOMP_GUEST_PERM, ARCH_REQ_XCOMP_PERM, ARCH_SET_CPUID, ARCH_SET_FS, ARCH_SET_GS, ARCH_XCOMP_TILECFG, ARCH_XCOMP_TILEDATA, Memory::Virtual::Check(), debug, EFAULT, EINVAL, ENOSYS, EPERM, fixme, CPU::x32::MSR_FS_BASE, CPU::x32::MSR_GS_BASE, Tasking::PCB::PageTable, thisProcess, and Memory::US.
linux_brk()
static void* linux_brk (SysFrm * , void * addr) static
Definition at line 409 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     void *ret = pcb->ProgramBreak->brk(addr);
     debug("brk(%#lx) = %#lx", addr, ret);
     return ret;
 }
References addr, Memory::ProgramBreak::brk(), debug, Tasking::PCB::ProgramBreak, and thisProcess.
linux_clock_gettime()
static int linux_clock_gettime (SysFrm * , clockid_t clockid, struct timespec * tp) static
Definition at line 1668 of file linux.cpp.
 {
     static_assert(sizeof(struct timespec) < PAGE_SIZE);
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check(tp, Memory::US))
     {
         debug("Invalid address %#lx", tp);
         return -EFAULT;
     }
     timespec *pTp = pcb->PageTable->Get(tp);
     /* FIXME: This is not correct? */
     switch (clockid)
     {
     case CLOCK_REALTIME:
     {
         uint64_t time = TimeManager->GetCounter();
         pTp->tv_sec = time / Time::ConvertUnit(Time::Seconds);
         pTp->tv_nsec = time / Time::ConvertUnit(Time::Nanoseconds);
         debug("time=%ld sec=%ld nsec=%ld",
               time, pTp->tv_sec, pTp->tv_nsec);
         break;
     }
     case CLOCK_MONOTONIC:
     {
         uint64_t time = TimeManager->GetCounter();
         pTp->tv_sec = time / Time::ConvertUnit(Time::Seconds);
         pTp->tv_nsec = time / Time::ConvertUnit(Time::Nanoseconds);
         debug("time=%ld sec=%ld nsec=%ld",
               time, pTp->tv_sec, pTp->tv_nsec);
         break;
     }
     case CLOCK_PROCESS_CPUTIME_ID:
     case CLOCK_THREAD_CPUTIME_ID:
     case CLOCK_MONOTONIC_RAW:
     case CLOCK_REALTIME_COARSE:
     case CLOCK_MONOTONIC_COARSE:
     case CLOCK_BOOTTIME:
     case CLOCK_REALTIME_ALARM:
     case CLOCK_BOOTTIME_ALARM:
     case CLOCK_SGI_CYCLE:
     case CLOCK_TAI:
     {
         fixme("clockid %d is stub", clockid);
         return -ENOSYS;
     }
     default:
     {
         warn("Invalid clockid %#lx", clockid);
         return -EINVAL;
     }
     }
     return 0;
 }
References Memory::Virtual::Check(), CLOCK_BOOTTIME, CLOCK_BOOTTIME_ALARM, CLOCK_MONOTONIC, CLOCK_MONOTONIC_COARSE, CLOCK_MONOTONIC_RAW, CLOCK_PROCESS_CPUTIME_ID, CLOCK_REALTIME, CLOCK_REALTIME_ALARM, CLOCK_REALTIME_COARSE, CLOCK_SGI_CYCLE, CLOCK_TAI, CLOCK_THREAD_CPUTIME_ID, Time::ConvertUnit(), debug, EFAULT, EINVAL, ENOSYS, fixme, Memory::PageTable::Get(), Time::time::GetCounter(), Time::Nanoseconds, PAGE_SIZE, Tasking::PCB::PageTable, Time::Seconds, thisProcess, TimeManager, timespec::tv_nsec, timespec::tv_sec, Memory::US, and warn.
linux_close()
static int linux_close (SysFrm * , int fd) static
Definition at line 121 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return fdt->_close(fd);
 }
References vfs::FileDescriptorTable::_close(), Tasking::PCB::FileDescriptors, and thisProcess.
linux_creat()
static int linux_creat (SysFrm * , const char * pathname, mode_t mode) static
Definition at line 1271 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return fdt->_creat(pathname, mode);
 }
References vfs::FileDescriptorTable::_creat(), Tasking::PCB::FileDescriptors, and thisProcess.
linux_dup()
static int linux_dup (SysFrm * , int oldfd) static
Definition at line 523 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return fdt->_dup(oldfd);
 }
References vfs::FileDescriptorTable::_dup(), Tasking::PCB::FileDescriptors, and thisProcess.
linux_dup2()
static int linux_dup2 (SysFrm * , int oldfd, int newfd) static
Definition at line 531 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return fdt->_dup2(oldfd, newfd);
 }
References vfs::FileDescriptorTable::_dup2(), Tasking::PCB::FileDescriptors, and thisProcess.
linux_execve()
static int linux_execve (SysFrm * sf, const char * pathname, char *const argv[], char *const envp[]) static
Definition at line 710 of file linux.cpp.
 {
     /* FIXME: exec doesn't follow the UNIX standard
         The pid, open files, etc. should be preserved */
     PCB *pcb = thisProcess;
     Memory::Virtual vmm = Memory::Virtual(pcb->PageTable);
     if (pathname == nullptr ||
         !vmm.Check((void *)pathname, Memory::US) ||
         !vmm.Check((void *)argv, Memory::US) ||
         !vmm.Check((void *)envp, Memory::US))
         return -ENOENT;
     const char *safe_path;
     char **safe_argv;
     char **safe_envp;
     safe_path = (const char *)pcb->vma->RequestPages(1);
     safe_argv = (char **)pcb->vma->RequestPages(TO_PAGES(MAX_ARG));
     safe_envp = (char **)pcb->vma->RequestPages(TO_PAGES(MAX_ARG));
     {
         Memory::SwapPT swap(pcb->PageTable);
         size_t len = strlen(pathname);
         memset((void *)safe_path, 0, PAGE_SIZE);
         memcpy((void *)safe_path, pathname, len);
         const char *arg;
         char *n_arg;
         for (int i = 0; argv[i] != nullptr; i++)
         {
             arg = argv[i];
             size_t len = strlen(arg);
             n_arg = (char *)pcb->vma->RequestPages(TO_PAGES(len));
             memcpy((void *)n_arg, arg, len);
             n_arg[len] = '\0';
             safe_argv[i] = n_arg;
             if (likely(i < MAX_ARG - 1))
                 safe_argv[i + 1] = nullptr;
         }
         for (int i = 0; envp[i] != nullptr; i++)
         {
             arg = envp[i];
             size_t len = strlen(arg);
             n_arg = (char *)pcb->vma->RequestPages(TO_PAGES(len));
             memcpy((void *)n_arg, arg, len);
             n_arg[len] = '\0';
             safe_envp[i] = n_arg;
             if (likely(i < MAX_ARG - 1))
                 safe_envp[i + 1] = nullptr;
         }
     }
     function("%s %#lx %#lx", safe_path, safe_argv, safe_envp);
 #ifdef DEBUG
     for (int i = 0; safe_argv[i] != nullptr; i++)
         debug("safe_argv[%d]: %s", i, safe_argv[i]);
     for (int i = 0; safe_envp[i] != nullptr; i++)
         debug("safe_envp[%d]: %s", i, safe_envp[i]);
 #endif
     vfs::RefNode *File = fs->Open(safe_path,
                                   pcb->CurrentWorkingDirectory);
     if (!File)
     {
         error("File not found");
         return -ENOENT;
     }
     char shebang_magic[2];
     File->read((uint8_t *)shebang_magic, 2);
     if (shebang_magic[0] == '#' && shebang_magic[1] == '!')
     {
         char *orig_path = (char *)pcb->vma->RequestPages(TO_PAGES(strlen(pathname) + 1));
         memcpy(orig_path, pathname, strlen(pathname) + 1);
         char *shebang = (char *)safe_path;
         size_t shebang_len = 0;
         constexpr int shebang_len_max = 255;
         File->seek(2, SEEK_SET);
         off_t shebang_off = 2;
         while (true)
         {
             char c;
             if (File->node->read((uint8_t *)&c, 1, shebang_off) == 0)
                 break;
             if (c == '\n' || shebang_len == shebang_len_max)
                 break;
             shebang[shebang_len++] = c;
             shebang_off++;
         }
         shebang[shebang_len] = '\0';
         debug("Shebang: %s", shebang);
         char **c_safe_argv = (char **)pcb->vma->RequestPages(TO_PAGES(MAX_ARG));
         int i = 0;
         for (; safe_argv[i] != nullptr; i++)
         {
             size_t arg_len = strlen(safe_argv[i]);
             char *c_arg = (char *)pcb->vma->RequestPages(TO_PAGES(arg_len));
             memcpy((void *)c_arg, safe_argv[i], arg_len);
             c_arg[arg_len] = '\0';
             c_safe_argv[i] = c_arg;
             debug("c_safe_argv[%d]: %s", i, c_safe_argv[i]);
         }
         c_safe_argv[i] = nullptr;
         char *token = strtok(shebang, " ");
         i = 0;
         while (token != nullptr)
         {
             size_t len = strlen(token);
             char *t_arg = (char *)pcb->vma->RequestPages(TO_PAGES(len));
             memcpy((void *)t_arg, token, len);
             t_arg[len] = '\0';
             safe_argv[i++] = t_arg;
             token = strtok(nullptr, " ");
         }
         safe_argv[i++] = orig_path;
         for (int j = 1; c_safe_argv[j] != nullptr; j++)
         {
             safe_argv[i++] = c_safe_argv[j];
             debug("clone: safe_argv[%d]: %s",
                   i, safe_argv[i - 1]);
         }
         safe_argv[i] = nullptr;
         delete File;
         return linux_execve(sf, safe_argv[0],
                             (char *const *)safe_argv,
                             (char *const *)safe_envp);
     }
     int ret = Execute::Spawn((char *)safe_path,
                              (const char **)safe_argv,
                              (const char **)safe_envp,
                              pcb, true,
                              pcb->Info.Compatibility);
     if (ret < 0)
     {
         error("Failed to spawn");
         delete File;
         return ret;
     }
     delete File;
     Tasking::Task *ctx = pcb->GetContext();
     // ctx->Sleep(1000);
     // pcb->SetState(Tasking::Zombie);
     // pcb->SetExitCode(0); /* FIXME: get process exit code */
     while (true)
         ctx->Yield();
     __builtin_unreachable();
 }
References Memory::Virtual::Check(), Tasking::TaskInfo::Compatibility, ctx, Tasking::PCB::CurrentWorkingDirectory, debug, ENOENT, error, fs, Tasking::PCB::GetContext(), Tasking::PCB::Info, len, likely, MAX_ARG, memcpy(), memset(), vfs::RefNode::node, vfs::Virtual::Open(), PAGE_SIZE, Tasking::PCB::PageTable, vfs::RefNode::read(), Memory::VirtualMemoryArea::RequestPages(), vfs::RefNode::seek(), SEEK_SET, Execute::Spawn(), strlen(), strtok(), swap(), thisProcess, TO_PAGES, Memory::US, and Tasking::PCB::vma.
linux_exit()
static __noreturn void linux_exit (SysFrm * , int status) static
Definition at line 881 of file linux.cpp.
 {
     TCB *t = thisThread;
     trace("Userspace thread %s(%d) exited with code %d (%#x)",
           t->Name,
           t->ID, status,
           status < 0 ? -status : status);
     t->SetState(Tasking::Zombie);
     t->SetExitCode(status);
     while (true)
         t->GetContext()->Yield();
     __builtin_unreachable();
 }
References Tasking::TCB::GetContext(), Tasking::TCB::ID, Tasking::TCB::Name, Tasking::TCB::SetExitCode(), Tasking::TCB::SetState(), thisThread, trace, Tasking::Task::Yield(), and Tasking::Zombie.
Referenced by linux_exit_group().
linux_exit_group()
static __noreturn void linux_exit_group (SysFrm * sf, int status) static
Definition at line 1728 of file linux.cpp.
 {
     fixme("status=%d", status);
     linux_exit(sf, status);
 }
References fixme, and linux_exit().
linux_fcntl()
static int linux_fcntl (SysFrm * , int fd, int cmd, void * arg) static
Definition at line 1233 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::Virtual vmm(pcb->PageTable);
     switch (cmd)
     {
     case F_DUPFD:
         return fdt->_dup2(fd, s_cst(int, (uintptr_t)arg));
     case F_GETFD:
         return fdt->GetFlags(fd);
     case F_SETFD:
         return fdt->SetFlags(fd, s_cst(int, (uintptr_t)arg));
     case F_GETFL:
     case F_SETFL:
     case F_SETOWN:
     case F_GETOWN:
     case F_SETSIG:
     case F_GETSIG:
     case F_GETLK:
     case F_SETLK:
     case F_SETLKW:
     case F_SETOWN_EX:
     case F_GETOWN_EX:
     {
         fixme("cmd %d not implemented", cmd);
         return -ENOSYS;
     }
     default:
     {
         debug("Invalid cmd %#x", cmd);
         return -EINVAL;
     }
     }
 }
References vfs::FileDescriptorTable::_dup2(), debug, EINVAL, ENOSYS, F_DUPFD, F_GETFD, F_GETFL, F_GETLK, F_GETOWN, F_GETOWN_EX, F_GETSIG, F_SETFD, F_SETFL, F_SETLK, F_SETLKW, F_SETOWN, F_SETOWN_EX, F_SETSIG, Tasking::PCB::FileDescriptors, fixme, vfs::FileDescriptorTable::GetFlags(), Tasking::PCB::PageTable, vfs::FileDescriptorTable::SetFlags(), and thisProcess.
linux_fork()
static pid_t linux_fork (SysFrm * sf) static
Definition at line 624 of file linux.cpp.
 {
     TCB *Thread = thisThread;
     PCB *Parent = Thread->Parent;
     PCB *NewProcess =
         TaskManager->CreateProcess(Parent,
                                    Parent->Name,
                                    Parent->Security.ExecutionMode,
                                    nullptr, true);
     if (unlikely(!NewProcess))
     {
         error("Failed to create process for fork");
         return -EAGAIN;
     }
     NewProcess->PageTable = Parent->PageTable->Fork();
     NewProcess->vma->SetTable(NewProcess->PageTable);
     NewProcess->vma->Fork(Parent->vma);
     NewProcess->ProgramBreak->SetTable(NewProcess->PageTable);
     NewProcess->FileDescriptors->Fork(Parent->FileDescriptors);
     if (Parent->ELFSymbolTable &&
         Parent->ELFSymbolTable->SymTableExists)
     {
         NewProcess->ELFSymbolTable = new SymbolResolver::Symbols(0);
         foreach (auto sym in Parent->ELFSymbolTable->GetSymTable())
         {
             NewProcess->ELFSymbolTable->AddSymbol(sym.Address,
                                                   sym.FunctionName);
         }
     }
     TCB *NewThread =
         TaskManager->CreateThread(NewProcess,
                                   0,
                                   nullptr,
                                   nullptr,
                                   std::vector<AuxiliaryVector>(),
                                   Thread->Info.Architecture,
                                   Thread->Info.Compatibility,
                                   true);
     if (!NewThread)
     {
         error("Failed to create thread for fork");
         delete NewProcess;
         return -EAGAIN;
     }
     NewThread->Rename(Thread->Name);
     TaskManager->UpdateFrame();
     NewThread->FPU = Thread->FPU;
     NewThread->Stack->Fork(Thread->Stack);
     NewThread->Info.Architecture = Thread->Info.Architecture;
     NewThread->Info.Compatibility = Thread->Info.Compatibility;
     NewThread->Security.IsCritical = Thread->Security.IsCritical;
     NewThread->Registers = Thread->Registers;
 #if defined(a64)
     NewThread->Registers.rip = (uintptr_t)linux_fork_return;
     /* For sysretq */
     NewThread->Registers.rdi = (uintptr_t)NewProcess->PageTable;
     NewThread->Registers.rcx = sf->ReturnAddress;
     NewThread->Registers.r8 = sf->StackPointer;
 #else
 #warning "sys_fork not implemented for other platforms"
 #endif
 #ifdef a86
     NewThread->GSBase = NewThread->ShadowGSBase;
     NewThread->ShadowGSBase = Thread->ShadowGSBase;
     NewThread->FSBase = Thread->FSBase;
 #endif
     debug("ret addr: %#lx, stack: %#lx ip: %#lx", sf->ReturnAddress,
           sf->StackPointer, (uintptr_t)linux_fork_return);
     debug("Forked thread \"%s\"(%d) to \"%s\"(%d)",
           Thread->Name, Thread->ID,
           NewThread->Name, NewThread->ID);
     NewThread->SetState(Tasking::Ready);
     // Parent->GetContext()->Yield();
     return (int)NewProcess->ID;
 }
References SymbolResolver::Symbols::AddSymbol(), Tasking::TaskInfo::Architecture, Tasking::TaskInfo::Compatibility, Tasking::Task::CreateProcess(), Tasking::Task::CreateThread(), debug, EAGAIN, Tasking::PCB::ELFSymbolTable, error, Tasking::PCB::FileDescriptors, Memory::PageTable::Fork(), vfs::FileDescriptorTable::Fork(), Memory::StackGuard::Fork(), Memory::VirtualMemoryArea::Fork(), SymbolResolver::Symbols::GetSymTable(), Tasking::TCB::ID, Tasking::PCB::ID, Tasking::TCB::Info, linux_fork_return(), Tasking::TCB::Name, Tasking::PCB::Name, Tasking::PCB::PageTable, Tasking::TCB::Parent, Tasking::PCB::ProgramBreak, Tasking::Ready, Tasking::TCB::Rename(), Tasking::TCB::Security, Tasking::PCB::Security, Tasking::TCB::SetState(), Memory::ProgramBreak::SetTable(), Memory::VirtualMemoryArea::SetTable(), Tasking::TCB::Stack, SymbolResolver::Symbols::SymTableExists, TaskManager, thisThread, unlikely, Tasking::Task::UpdateFrame(), and Tasking::PCB::vma.
linux_fork_return()
void linux_fork_return (void * tableAddr)
Definition at line 48 of file linux.cpp.
 {
 #if defined(a64)
     asmv("movq %0, %%cr3" ::"r"(tableAddr)); /* Load process page table */
     asmv("movq $0, %rax\n");                 /* Return 0 */
     asmv("movq %r8, %rsp\n");                /* Restore stack pointer */
     asmv("movq %r8, %rbp\n");                /* Restore base pointer */
     asmv("swapgs\n");                        /* Swap GS back to the user GS */
     asmv("sti\n");                           /* Enable interrupts */
     asmv("sysretq\n");                       /* Return to rcx address in user mode */
 #elif defined(a32)
 #warning "linux_fork_return not implemented for i386"
 #endif
     __builtin_unreachable();
 }
References asmv().
Referenced by linux_fork().
linux_fstat()
static int linux_fstat (SysFrm * , int fd, struct stat * statbuf) static
Definition at line 146 of file linux.cpp.
 {
 #undef fstat
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check((void *)statbuf, Memory::US))
     {
         debug("Invalid address %#lx", statbuf);
         return -EFAULT;
     }
     auto pStatbuf = pcb->PageTable->Get(statbuf);
     return fdt->_fstat(fd, pStatbuf);
 }
References vfs::FileDescriptorTable::_fstat(), Memory::Virtual::Check(), debug, EFAULT, Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), Tasking::PCB::PageTable, thisProcess, and Memory::US.
linux_getdents64()
static ssize_t linux_getdents64 (SysFrm * , int fd, struct linux_dirent64 * dirp, size_t count) static
Definition at line 1634 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     if (count < sizeof(struct linux_dirent64))
     {
         debug("Invalid count %d", count);
         return -EINVAL;
     }
     vfs::FileDescriptorTable::Fildes &
         fildes = fdt->GetDescriptor(fd);
     if (!fildes.Handle)
     {
         debug("Invalid fd %d", fd);
         return -EBADF;
     }
     if (fildes.Handle->node->Type != vfs::NodeType::DIRECTORY)
     {
         debug("Invalid node type %d",
               fildes.Handle->node->Type);
         return -ENOTDIR;
     }
     auto pDirp = pcb->PageTable->Get(dirp);
     UNUSED(pDirp);
     stub;
     return -ENOSYS;
 }
References debug, vfs::DIRECTORY, EBADF, EINVAL, ENOSYS, ENOTDIR, Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), vfs::FileDescriptorTable::GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, vfs::RefNode::node, Tasking::PCB::PageTable, stub, thisProcess, and UNUSED.
linux_getpid()
static pid_t linux_getpid (SysFrm *) static
Definition at line 611 of file linux.cpp.
 {
     return thisProcess->ID;
 }
References thisProcess.
linux_getppid()
static pid_t linux_getppid (SysFrm *) static
Definition at line 1348 of file linux.cpp.
 {
     return thisProcess->Parent->ID;
 }
References thisProcess.
linux_getrandom()
static ssize_t linux_getrandom (SysFrm * , void * buf, size_t buflen, unsigned int flags) static
Definition at line 1866 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check(buf, Memory::US))
     {
         debug("Invalid address %#lx", buf);
         return -EFAULT;
     }
     if (flags & GRND_NONBLOCK)
         fixme("GRND_NONBLOCK not implemented");
     if (flags & ~(GRND_NONBLOCK |
                   GRND_RANDOM |
                   GRND_INSECURE))
     {
         warn("Invalid flags %#x", flags);
         return -EINVAL;
     }
     if (flags & GRND_RANDOM)
     {
         uint16_t random;
         for (size_t i = 0; i < buflen; i++)
         {
             random = Random::rand16();
             {
                 Memory::SwapPT swap(pcb->PageTable);
                 ((uint8_t *)buf)[i] = uint8_t(random & 0xFF);
             }
         }
         return buflen;
     }
     return 0;
 }
References Memory::Virtual::Check(), debug, EFAULT, EINVAL, fixme, GRND_INSECURE, GRND_NONBLOCK, GRND_RANDOM, Tasking::PCB::PageTable, Random::rand16(), swap(), thisProcess, Memory::US, and warn.
linux_gettid()
static pid_t linux_gettid (SysFrm *) static
Definition at line 1616 of file linux.cpp.
 {
     return thisThread->ID;
 }
References thisThread.
linux_getuid()
static uid_t linux_getuid (SysFrm *) static
Definition at line 1342 of file linux.cpp.
 {
     return thisProcess->Security.Real.UserID;
 }
References thisProcess.
linux_ioctl()
static int linux_ioctl (SysFrm * , int fd, unsigned long request, void * argp) static
Definition at line 418 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check((void *)argp, Memory::US))
     {
         debug("Invalid address %#lx", argp);
         return -EFAULT;
     }
     auto pArgp = pcb->PageTable->Get(argp);
     return fdt->_ioctl(fd, request, pArgp);
 }
References vfs::FileDescriptorTable::_ioctl(), Memory::Virtual::Check(), debug, EFAULT, Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), Tasking::PCB::PageTable, thisProcess, and Memory::US.
linux_kill()
static int linux_kill (SysFrm * , pid_t pid, int sig) static
Definition at line 1123 of file linux.cpp.
 {
     PCB *target = thisProcess->GetContext()->GetProcessByID(pid);
     if (!target)
         return -ESRCH;
     /* TODO: Check permissions */
     if (sig == 0)
         return 0;
     if (pid == 0)
     {
         fixme("Sending signal %d to all processes", sig);
         return -ENOSYS;
     }
     if (pid == -1)
     {
         fixme("Sending signal %d to all processes except init", sig);
         return -ENOSYS;
     }
     if (pid < -1)
     {
         fixme("Sending signal %d to process group %d", sig, pid);
         return -ENOSYS;
     }
     return target->Signals->SendSignal(sig);
 }
References ENOSYS, ESRCH, fixme, Tasking::Signal::SendSignal(), Tasking::PCB::Signals, and thisProcess.
linux_lseek()
static off_t linux_lseek (SysFrm * , int fd, off_t offset, int whence) static
Definition at line 191 of file linux.cpp.
 {
     static_assert(SEEK_SET == sc_SEEK_SET);
     static_assert(SEEK_CUR == sc_SEEK_CUR);
     static_assert(SEEK_END == sc_SEEK_END);
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return fdt->_lseek(fd, offset, whence);
 }
References vfs::FileDescriptorTable::_lseek(), Tasking::PCB::FileDescriptors, sc_SEEK_CUR, sc_SEEK_END, sc_SEEK_SET, SEEK_CUR, SEEK_END, SEEK_SET, and thisProcess.
linux_lstat()
static int linux_lstat (SysFrm * , const char * pathname, struct stat * statbuf) static
Definition at line 164 of file linux.cpp.
 {
 #undef lstat
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check((void *)pathname, Memory::US))
     {
         debug("Invalid address %#lx", pathname);
         return -EFAULT;
     }
     if (!vmm.Check((void *)statbuf, Memory::US))
     {
         debug("Invalid address %#lx", statbuf);
         return -EFAULT;
     }
     auto pPathname = pcb->PageTable->Get(pathname);
     auto pStatbuf = pcb->PageTable->Get(statbuf);
     return fdt->_lstat(pPathname, pStatbuf);
 }
References vfs::FileDescriptorTable::_lstat(), Memory::Virtual::Check(), debug, EFAULT, Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), Tasking::PCB::PageTable, thisProcess, and Memory::US.
linux_mkdir()
static int linux_mkdir (SysFrm * , const char * pathname, mode_t mode) static
Definition at line 1279 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     fixme("semi-stub");
     const char *pPathname = pcb->PageTable->Get(pathname);
     vfs::Node *n = fs->Create(pPathname, vfs::DIRECTORY, pcb->CurrentWorkingDirectory);
     if (!n)
         return -EEXIST;
     return 0;
 }
References vfs::Virtual::Create(), Tasking::PCB::CurrentWorkingDirectory, vfs::DIRECTORY, EEXIST, fixme, fs, Memory::PageTable::Get(), Tasking::PCB::PageTable, and thisProcess.
linux_mmap()
static void* linux_mmap (SysFrm * , void * addr, size_t length, int prot, int flags, int fildes, off_t offset) static
Definition at line 203 of file linux.cpp.
 {
     static_assert(PROT_NONE == sc_PROT_NONE);
     static_assert(PROT_READ == sc_PROT_READ);
     static_assert(PROT_WRITE == sc_PROT_WRITE);
     static_assert(PROT_EXEC == sc_PROT_EXEC);
     int new_flags = 0;
     if (flags & MAP_SHARED)
     {
         new_flags |= sc_MAP_SHARED;
         flags &= ~MAP_SHARED;
     }
     if (flags & MAP_PRIVATE)
     {
         new_flags |= sc_MAP_PRIVATE;
         flags &= ~MAP_PRIVATE;
     }
     if (flags & MAP_FIXED)
     {
         new_flags |= sc_MAP_FIXED;
         flags &= ~MAP_FIXED;
     }
     if (flags & MAP_ANONYMOUS)
     {
         new_flags |= sc_MAP_ANONYMOUS;
         flags &= ~MAP_ANONYMOUS;
     }
     if (flags)
         fixme("unhandled flags: %#x", flags);
     flags = new_flags;
     if (length == 0)
         return (void *)-EINVAL;
     if (fildes != -1)
         return (void *)-ENOSYS;
     bool p_None = prot & sc_PROT_NONE;
     bool p_Read = prot & sc_PROT_READ;
     bool p_Write = prot & sc_PROT_WRITE;
     bool p_Exec = prot & sc_PROT_EXEC;
     bool m_Shared = flags & sc_MAP_SHARED;
     bool m_Private = flags & sc_MAP_PRIVATE;
     bool m_Fixed = flags & sc_MAP_FIXED;
     bool m_Anon = flags & sc_MAP_ANONYMOUS;
     UNUSED(p_None);
     UNUSED(m_Anon);
     debug("N:%d R:%d W:%d E:%d",
           p_None, p_Read, p_Write,
           p_Exec);
     debug("S:%d P:%d F:%d A:%d",
           m_Shared, m_Private,
           m_Fixed, m_Anon);
     int UnknownFlags = flags & ~(sc_MAP_SHARED |
                                  sc_MAP_PRIVATE |
                                  sc_MAP_FIXED |
                                  sc_MAP_ANONYMOUS);
     if (UnknownFlags)
     {
         debug("Unknown flags: %x", UnknownFlags);
         return (void *)-EINVAL;
     }
     if (length > PAGE_SIZE_2M)
         fixme("large page 2 MiB (requested %d)",
               TO_MiB(length));
     else if (length > PAGE_SIZE_1G)
         fixme("huge page 1 GiB (requested %d)",
               TO_GiB(length));
     if (offset % PAGE_SIZE)
         return (void *)-EINVAL;
     if (uintptr_t(addr) % PAGE_SIZE && m_Fixed)
         return (void *)-EINVAL;
     if ((m_Shared && m_Private) ||
         (!m_Shared && !m_Private))
         return (void *)-EINVAL;
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     intptr_t ret = (intptr_t)vma->CreateCoWRegion(addr, length,
                                                   p_Read, p_Write, p_Exec,
                                                   m_Fixed, m_Shared);
     return (void *)ret;
 }
References addr, Memory::VirtualMemoryArea::CreateCoWRegion(), debug, EINVAL, ENOSYS, fixme, MAP_ANONYMOUS, MAP_FIXED, MAP_PRIVATE, MAP_SHARED, PAGE_SIZE, PAGE_SIZE_1G, PAGE_SIZE_2M, PROT_EXEC, PROT_NONE, PROT_READ, PROT_WRITE, sc_MAP_ANONYMOUS, sc_MAP_FIXED, sc_MAP_PRIVATE, sc_MAP_SHARED, sc_PROT_EXEC, sc_PROT_NONE, sc_PROT_READ, sc_PROT_WRITE, thisProcess, TO_GiB, TO_MiB, UNUSED, and Tasking::PCB::vma.
linux_mprotect()
static int linux_mprotect (SysFrm * , void * addr, size_t len, int prot) static
Definition at line 302 of file linux.cpp.
 {
     if (len == 0)
         return -EINVAL;
     if (uintptr_t(addr) % PAGE_SIZE)
         return -EINVAL;
     // bool p_None = prot & sc_PROT_NONE;
     bool p_Read = prot & sc_PROT_READ;
     bool p_Write = prot & sc_PROT_WRITE;
     // bool p_Exec = prot & sc_PROT_EXEC;
     PCB *pcb = thisProcess;
     Memory::Virtual vmm = Memory::Virtual(pcb->PageTable);
     for (uintptr_t i = uintptr_t(addr);
          i < uintptr_t(addr) + len;
          i += PAGE_SIZE)
     {
         if (likely(!vmm.Check((void *)i, Memory::G)))
         {
             Memory::PageTableEntry *pte = vmm.GetPTE(addr);
             if (pte == nullptr)
             {
                 debug("Page %#lx is not mapped inside %#lx",
                       (void *)i, pcb->PageTable);
                 fixme("Page %#lx is not mapped", (void *)i);
                 continue;
                 return -ENOMEM;
             }
             if (!pte->Present ||
                 (!pte->UserSupervisor && p_Read) ||
                 (!pte->ReadWrite && p_Write))
             {
                 debug("Page %p is not mapped with the correct permissions",
                       (void *)i);
                 return -EACCES;
             }
             // pte->Present = !p_None;
             pte->UserSupervisor = p_Read;
             pte->ReadWrite = p_Write;
             // pte->ExecuteDisable = p_Exec;
             debug("Changed permissions of page %#lx to %s %s %s %s",
                   (void *)i,
                   (prot & sc_PROT_NONE) ? "None" : "",
                   p_Read ? "Read" : "",
                   p_Write ? "Write" : "",
                   (prot & sc_PROT_EXEC) ? "Exec" : "");
 #if defined(a64)
             CPU::x64::invlpg(addr);
 #elif defined(a32)
             CPU::x32::invlpg(addr);
 #elif defined(aa64)
             asmv("dsb sy");
             asmv("tlbi vae1is, %0"
                  :
                  : "r"(addr)
                  : "memory");
             asmv("dsb sy");
             asmv("isb");
 #endif
         }
         else
         {
             warn("%p is a global page", (void *)i);
             return -ENOMEM;
         }
     }
     return 0;
 }
References addr, asmv(), Memory::Virtual::Check(), debug, EACCES, EINVAL, ENOMEM, fixme, Memory::G, Memory::Virtual::GetPTE(), x32::invlpg(), len, likely, PAGE_SIZE, Tasking::PCB::PageTable, sc_PROT_EXEC, sc_PROT_NONE, sc_PROT_READ, sc_PROT_WRITE, thisProcess, and warn.
linux_munmap()
static int linux_munmap (SysFrm * , void * addr, size_t length) static
Definition at line 380 of file linux.cpp.
 {
     if (uintptr_t(addr) % PAGE_SIZE)
         return -EINVAL;
     if (length == 0)
         return -EINVAL;
     PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     Memory::Virtual vmm = Memory::Virtual(pcb->PageTable);
     for (uintptr_t i = uintptr_t(addr);
          i < uintptr_t(addr) + length;
          i += PAGE_SIZE)
     {
         if (likely(!vmm.Check((void *)i, Memory::G)))
             vmm.Remap((void *)i, (void *)i, Memory::P | Memory::RW);
         else
             warn("%p is a global page", (void *)i);
     }
     /* TODO: Check if the page is allocated
                 and not only mapped */
     vma->FreePages((void *)addr, TO_PAGES(length) + 1);
     return 0;
 }
References addr, Memory::Virtual::Check(), EINVAL, Memory::VirtualMemoryArea::FreePages(), Memory::G, likely, Memory::P, PAGE_SIZE, Tasking::PCB::PageTable, Memory::Virtual::Remap(), Memory::RW, thisProcess, TO_PAGES, Tasking::PCB::vma, and warn.
linux_nanosleep()
static int linux_nanosleep (SysFrm * , const struct timespec * req, struct timespec * rem) static
Definition at line 546 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check((void *)req, Memory::US))
     {
         debug("Invalid address %#lx", req);
         return -EFAULT;
     }
     if (rem && !vmm.Check((void *)rem, Memory::US))
     {
         debug("Invalid address %#lx", rem);
         return -EFAULT;
     }
     auto pReq = pcb->PageTable->Get(req);
     auto pRem = rem ? pcb->PageTable->Get(rem) : 0;
     if (pReq->tv_nsec < 0 || pReq->tv_nsec > 999999999)
     {
         debug("Invalid tv_nsec %ld", pReq->tv_nsec);
         return -EINVAL;
     }
     if (pReq->tv_sec < 0)
     {
         debug("Invalid tv_sec %ld", pReq->tv_sec);
         return -EINVAL;
     }
     debug("tv_nsec=%ld tv_sec=%ld",
           pReq->tv_nsec, pReq->tv_sec);
     uint64_t nanoTime = pReq->tv_nsec;
     uint64_t secTime = pReq->tv_sec * 1000000000; /* Nano */
     uint64_t time = TimeManager->GetCounter();
     uint64_t sleepTime = TimeManager->CalculateTarget(nanoTime + secTime, Time::Nanoseconds);
     debug("time=%ld secTime=%ld nanoTime=%ld sleepTime=%ld",
           time, secTime, nanoTime, sleepTime);
     while (time < sleepTime)
     {
         pcb->GetContext()->Yield();
         /* TODO: sleep should be interrupted by
             the signal and return errno EINTR */
         time = TimeManager->GetCounter();
     }
     debug("time=     %ld", time);
     debug("sleepTime=%ld", sleepTime);
     if (rem)
     {
         pRem->tv_sec = 0;
         pRem->tv_nsec = 0;
     }
     return 0;
 }
References Time::time::CalculateTarget(), Memory::Virtual::Check(), debug, EFAULT, EINVAL, Memory::PageTable::Get(), Tasking::PCB::GetContext(), Time::time::GetCounter(), Time::Nanoseconds, Tasking::PCB::PageTable, thisProcess, TimeManager, Memory::US, and Tasking::Task::Yield().
linux_newfstatat()
static long linux_newfstatat (SysFrm * , int dfd, const char * filename, struct stat * statbuf, int flag) static
Definition at line 1746 of file linux.cpp.
 {
     /* FIXME: This function is not working at all? */
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::Virtual vmm(pcb->PageTable);
     if (flag)
         fixme("flag %#x is stub", flag);
     if (!filename)
     {
         debug("Invalid filename %#lx", filename);
         return -EFAULT;
     }
     if (!statbuf)
     {
         debug("Invalid statbuf %#lx", statbuf);
         return -EFAULT;
     }
     if (dfd == AT_FDCWD)
     {
         fixme("dfd AT_FDCWD is stub");
         return -ENOSYS;
     }
     vfs::FileDescriptorTable::Fildes &
         fildes = fdt->GetDescriptor(dfd);
     if (!fildes.Handle)
     {
         debug("Invalid fd %d", dfd);
         return -EBADF;
     }
     const char *pFilename = pcb->PageTable->Get(filename);
     struct stat *pStatbuf = pcb->PageTable->Get(statbuf);
     debug("%s %#lx %#lx", pFilename, filename, statbuf);
     return fdt->_stat(pFilename, pStatbuf);
 }
References vfs::FileDescriptorTable::_stat(), AT_FDCWD, debug, EBADF, EFAULT, ENOSYS, Tasking::PCB::FileDescriptors, fixme, Memory::PageTable::Get(), vfs::FileDescriptorTable::GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, Tasking::PCB::PageTable, and thisProcess.
linux_open()
static int linux_open (SysFrm * sf, const char * pathname, int flags, mode_t mode) static
Definition at line 93 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     const char *pPathname = pcb->PageTable->Get(pathname);
     function("%s, %d, %d", pPathname, flags, mode);
     if (flags & 0200000 /* O_DIRECTORY */)
     {
         vfs::Node *node = fs->GetNodeFromPath(pPathname);
         if (!node)
         {
             debug("Couldn't find %s", pPathname);
             return -ENOENT;
         }
         if (node->Type != vfs::NodeType::DIRECTORY)
         {
             debug("%s is not a directory", pPathname);
             return -ENOTDIR;
         }
     }
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     return fdt->_open(pPathname, flags, mode);
 }
References vfs::FileDescriptorTable::_open(), debug, vfs::DIRECTORY, ENOENT, ENOTDIR, Tasking::PCB::FileDescriptors, fs, Memory::PageTable::Get(), vfs::Virtual::GetNodeFromPath(), Tasking::PCB::PageTable, thisProcess, and vfs::Node::Type.
linux_pause()
static int linux_pause (SysFrm *) static
Definition at line 539 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     return pcb->Signals->WaitAnySignal();
 }
References Tasking::PCB::Signals, thisProcess, and Tasking::Signal::WaitAnySignal().
linux_pipe()
static int linux_pipe (SysFrm * , int pipefd[2]) static
Definition at line 513 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     int *pPipefd = pcb->PageTable->Get(pipefd);
     debug("pipefd=%#lx", pPipefd);
     fixme("pipefd=[%d, %d]", pPipefd[0], pPipefd[1]);
     return -ENOSYS;
 }
References debug, ENOSYS, fixme, Memory::PageTable::Get(), Tasking::PCB::PageTable, and thisProcess.
Referenced by linux_pipe2().
linux_pipe2()
static int linux_pipe2 (SysFrm * sf, int pipefd[2], int flags) static
Definition at line 1792 of file linux.cpp.
 {
     if (flags == 0)
         return linux_pipe(sf, pipefd);
     PCB *pcb = thisProcess;
     int *pPipefd = pcb->PageTable->Get(pipefd);
     debug("pipefd=%#lx", pPipefd);
     fixme("pipefd=[%d, %d] flags=%#x", pPipefd[0], pPipefd[1], flags);
     return -ENOSYS;
 }
References debug, ENOSYS, fixme, Memory::PageTable::Get(), linux_pipe(), Tasking::PCB::PageTable, and thisProcess.
linux_prlimit64()
static int linux_prlimit64 (SysFrm * , pid_t pid, int resource, const struct rlimit * new_limit, struct rlimit * old_limit) static
Definition at line 1805 of file linux.cpp.
 {
     static_assert(sizeof(struct rlimit) < PAGE_SIZE);
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (old_limit && !vmm.Check(old_limit, Memory::US))
     {
         debug("Invalid address %#lx", old_limit);
         return -EFAULT;
     }
     if (new_limit && !vmm.Check((void *)new_limit, Memory::US))
     {
         debug("Invalid address %#lx", new_limit);
         return -EFAULT;
     }
     auto pOldLimit = pcb->PageTable->Get(old_limit);
     auto pNewLimit = pcb->PageTable->Get(new_limit);
     UNUSED(pOldLimit);
     UNUSED(pNewLimit);
     switch (resource)
     {
     case RLIMIT_CPU:
     case RLIMIT_FSIZE:
     case RLIMIT_DATA:
     case RLIMIT_STACK:
     case RLIMIT_CORE:
     case RLIMIT_RSS:
     case RLIMIT_NPROC:
     case RLIMIT_NOFILE:
     case RLIMIT_MEMLOCK:
     case RLIMIT_AS:
     case RLIMIT_LOCKS:
     case RLIMIT_SIGPENDING:
     case RLIMIT_MSGQUEUE:
     case RLIMIT_NICE:
     case RLIMIT_RTPRIO:
     case RLIMIT_RTTIME:
     case RLIMIT_NLIMITS:
     {
         fixme("resource %d is stub", resource);
         return -ENOSYS;
     }
     default:
     {
         debug("Invalid resource %d", resource);
         return -EINVAL;
     }
     }
     return 0;
 }
References Memory::Virtual::Check(), debug, EFAULT, EINVAL, ENOSYS, fixme, Memory::PageTable::Get(), PAGE_SIZE, Tasking::PCB::PageTable, RLIMIT_AS, RLIMIT_CORE, RLIMIT_CPU, RLIMIT_DATA, RLIMIT_FSIZE, RLIMIT_LOCKS, RLIMIT_MEMLOCK, RLIMIT_MSGQUEUE, RLIMIT_NICE, RLIMIT_NLIMITS, RLIMIT_NOFILE, RLIMIT_NPROC, RLIMIT_RSS, RLIMIT_RTPRIO, RLIMIT_RTTIME, RLIMIT_SIGPENDING, RLIMIT_STACK, thisProcess, UNUSED, and Memory::US.
linux_read()
static ssize_t linux_read (SysFrm * , int fd, void * buf, size_t count) static
Definition at line 65 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     void *pBuf = pcb->PageTable->Get(buf);
     function("%d, %p, %d", fd, buf, count);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = fdt->_read(fd, pBuf, count);
     if (ret >= 0)
         fdt->_lseek(fd, ret, SEEK_CUR);
     return ret;
 }
References vfs::FileDescriptorTable::_lseek(), vfs::FileDescriptorTable::_read(), Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), Tasking::PCB::PageTable, SEEK_CUR, and thisProcess.
Referenced by linux_readv().
linux_readlink()
static ssize_t linux_readlink (SysFrm * , const char * pathname, char * buf, size_t bufsiz) static
Definition at line 1292 of file linux.cpp.
 {
     if (!pathname || !buf)
         return -EINVAL;
     if (bufsiz > PAGE_SIZE)
     {
         warn("bufsiz is too large: %ld", bufsiz);
         return -EINVAL;
     }
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check((void *)buf, Memory::US))
     {
         warn("Invalid address %#lx", buf);
         return -EFAULT;
     }
     const char *pPath = pcb->PageTable->Get(pathname);
     char *pBuf = pcb->PageTable->Get(buf);
     function("%s %#lx %ld", pPath, buf, bufsiz);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     int fd = fdt->_open(pPath, O_RDONLY, 0);
     if (fd < 0)
         return -ENOENT;
     vfs::FileDescriptorTable::Fildes fildes = fdt->GetDescriptor(fd);
     vfs::Node *node = fildes.Handle->node;
     fdt->_close(fd);
     if (node->Type != vfs::NodeType::SYMLINK)
         return -EINVAL;
     if (!node->Symlink)
     {
         warn("Symlink null for \"%s\"?", pPath);
         return -EINVAL;
     }
     size_t len = strlen(node->Symlink);
     if (len > bufsiz)
         len = bufsiz;
     strncpy(pBuf, node->Symlink, len);
     return len;
 }
References vfs::FileDescriptorTable::_close(), vfs::FileDescriptorTable::_open(), Memory::Virtual::Check(), EFAULT, EINVAL, ENOENT, Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), vfs::FileDescriptorTable::GetDescriptor(), vfs::FileDescriptorTable::Fildes::Handle, len, vfs::RefNode::node, O_RDONLY, PAGE_SIZE, Tasking::PCB::PageTable, strlen(), strncpy(), vfs::SYMLINK, vfs::Node::Symlink, thisProcess, vfs::Node::Type, Memory::US, and warn.
linux_readv()
static ssize_t linux_readv (SysFrm * sf, int fildes, const struct iovec * iov, int iovcnt) static
Definition at line 435 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     const struct iovec *pIov = pcb->PageTable->Get(iov);
     ssize_t Total = 0;
     for (int i = 0; i < iovcnt; i++)
     {
         debug("%d: iov[%d]: %p %d", fildes, i, pIov[i].iov_base, pIov[i].iov_len);
         if (!pIov[i].iov_base)
         {
             debug("invalid iov_base");
             return -EFAULT;
         }
         if (pIov[i].iov_len == 0)
         {
             debug("invalid iov_len");
             continue;
         }
         ssize_t n = linux_read(sf, fildes, pIov[i].iov_base, pIov[i].iov_len);
         if (n < 0)
             return n;
         debug("n: %d", n);
         Total += n;
         if (n < (ssize_t)pIov[i].iov_len)
         {
             debug("break");
             break;
         }
     }
     debug("readv: %d", Total);
     return Total;
 }
References debug, EFAULT, Memory::PageTable::Get(), iovec::iov_base, iovec::iov_len, linux_read(), Tasking::PCB::PageTable, and thisProcess.
linux_reboot()
static int linux_reboot (SysFrm * , int magic, int magic2, int cmd, void * arg) static
Definition at line 1442 of file linux.cpp.
 {
     if (magic != LINUX_REBOOT_MAGIC1 ||
         (magic2 != LINUX_REBOOT_MAGIC2 &&
          magic2 != LINUX_REBOOT_MAGIC2A &&
          magic2 != LINUX_REBOOT_MAGIC2B &&
          magic2 != LINUX_REBOOT_MAGIC2C))
     {
         warn("Invalid magic %#x %#x", magic, magic2);
         return -EINVAL;
     }
     PCB *pcb = thisProcess;
     debug("cmd=%#x arg=%#lx", cmd, arg);
     switch ((unsigned int)cmd)
     {
     case LINUX_REBOOT_CMD_RESTART:
     {
         KPrint("Restarting system.");
         Tasking::Task *ctx = pcb->GetContext();
         ctx->CreateThread(ctx->GetKernelProcess(),
                           Tasking::IP(KST_Reboot))
             ->Rename("Restart");
         return 0;
     }
     case LINUX_REBOOT_CMD_HALT:
     {
         KPrint("System halted.");
         pcb->GetContext()->Panic();
         CPU::Stop();
     }
     case LINUX_REBOOT_CMD_POWER_OFF:
     {
         KPrint("Power down.");
         Tasking::Task *ctx = pcb->GetContext();
         ctx->CreateThread(ctx->GetKernelProcess(),
                           Tasking::IP(KST_Shutdown))
             ->Rename("Shutdown");
         return 0;
     }
     case LINUX_REBOOT_CMD_RESTART2:
     {
         Memory::Virtual vmm(pcb->PageTable);
         if (!vmm.Check(arg, Memory::US))
         {
             debug("Invalid address %#lx", arg);
             return -EFAULT;
         }
         void *pArg = pcb->PageTable->Get(arg);
         KPrint("Restarting system with command '%s'",
                (const char *)pArg);
         Tasking::Task *ctx = pcb->GetContext();
         ctx->CreateThread(ctx->GetKernelProcess(),
                           Tasking::IP(KST_Reboot))
             ->Rename("Restart");
         break;
     }
     case LINUX_REBOOT_CMD_CAD_ON:
     case LINUX_REBOOT_CMD_CAD_OFF:
     case LINUX_REBOOT_CMD_SW_SUSPEND:
     case LINUX_REBOOT_CMD_KEXEC:
     {
         fixme("cmd %#x not implemented", cmd);
         return -ENOSYS;
     }
     default:
     {
         debug("Invalid cmd %#x", cmd);
         return -EINVAL;
     }
     }
     return 0;
 }
References Memory::Virtual::Check(), ctx, debug, EFAULT, EINVAL, ENOSYS, fixme, Memory::PageTable::Get(), Tasking::PCB::GetContext(), KPrint(), KST_Reboot(), KST_Shutdown(), LINUX_REBOOT_CMD_CAD_OFF, LINUX_REBOOT_CMD_CAD_ON, LINUX_REBOOT_CMD_HALT, LINUX_REBOOT_CMD_KEXEC, LINUX_REBOOT_CMD_POWER_OFF, LINUX_REBOOT_CMD_RESTART, LINUX_REBOOT_CMD_RESTART2, LINUX_REBOOT_CMD_SW_SUSPEND, LINUX_REBOOT_MAGIC1, LINUX_REBOOT_MAGIC2, LINUX_REBOOT_MAGIC2A, LINUX_REBOOT_MAGIC2B, LINUX_REBOOT_MAGIC2C, Tasking::PCB::PageTable, Tasking::Task::Panic(), thisProcess, Memory::US, and warn.
linux_set_tid_address()
static pid_t linux_set_tid_address (SysFrm * , int * tidptr) static
Definition at line 1622 of file linux.cpp.
 {
     if (tidptr == nullptr)
         return -EINVAL;
     Tasking::TCB *tcb = thisThread;
     tcb->Linux.clear_child_tid = tidptr;
     return tcb->ID;
 }
References EINVAL, Tasking::TCB::ID, Tasking::TCB::Linux, and thisThread.
linux_shutdown()
static int linux_shutdown (SysFrm * , int sockfd, int how) static
Definition at line 617 of file linux.cpp.
 {
     stub;
     return -ENOSYS;
 }
References ENOSYS, and stub.
linux_sigaction()
static int linux_sigaction (SysFrm * , int signum, const struct sigaction * act, struct sigaction * oldact) static
Definition at line 1523 of file linux.cpp.
 {
     if (signum == linux_SIGKILL || signum == linux_SIGSTOP)
     {
         debug("Invalid signal %d", signum);
         return -EINVAL;
     }
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (oldact && !vmm.Check(oldact, Memory::US))
     {
         debug("Invalid address %#lx", oldact);
         return -EFAULT;
     }
     if (act && !vmm.Check((void *)act, Memory::US))
     {
         debug("Invalid address %#lx", act);
         return -EFAULT;
     }
     debug("signum=%d act=%#lx oldact=%#lx", signum, act, oldact);
     auto pOldact = pcb->PageTable->Get(oldact);
     auto pAct = pcb->PageTable->Get(act);
     int ret = 0;
     if (pOldact)
         ret = pcb->Signals->GetAction(signum, pOldact);
     if (unlikely(ret < 0))
         return ret;
     if (pAct)
         ret = pcb->Signals->SetAction(signum, *pAct);
     return ret;
 }
References Memory::Virtual::Check(), debug, EFAULT, EINVAL, Memory::PageTable::Get(), Tasking::Signal::GetAction(), linux_SIGKILL, linux_SIGSTOP, Tasking::PCB::PageTable, Tasking::Signal::SetAction(), Tasking::PCB::Signals, thisProcess, unlikely, and Memory::US.
linux_sigprocmask()
static int linux_sigprocmask (SysFrm * , int how, const sigset_t * set, sigset_t * oldset, size_t sigsetsize) static
Definition at line 1567 of file linux.cpp.
 {
     static_assert(sizeof(sigset_t) < PAGE_SIZE);
     if (sigsetsize != sizeof(sigset_t))
     {
         warn("Unsupported sigsetsize %d!", sigsetsize);
         return -EINVAL;
     }
     PCB *pcb = thisProcess;
     const sigset_t *pSet = (const sigset_t *)pcb->PageTable->Get((void *)set);
     sigset_t *pOldset = (sigset_t *)pcb->PageTable->Get(oldset);
     debug("how=%#x set=%#lx oldset=%#lx",
           how, pSet ? *pSet : 0, pOldset ? *pOldset : 0);
     if (pOldset)
         *pOldset = pcb->Signals->GetMask();
     if (!pSet)
         return 0;
     switch (how)
     {
     case SIG_BLOCK:
         pcb->Signals->Block(*pSet);
         break;
     case SIG_UNBLOCK:
         pcb->Signals->Unblock(*pSet);
         break;
     case SIG_SETMASK:
         pcb->Signals->SetMask(*pSet);
         break;
     default:
         warn("Invalid how %#x", how);
         return -EINVAL;
     }
     return 0;
 }
References Tasking::Signal::Block(), debug, EINVAL, Memory::PageTable::Get(), Tasking::Signal::GetMask(), PAGE_SIZE, Tasking::PCB::PageTable, Tasking::Signal::SetMask(), SIG_BLOCK, SIG_SETMASK, SIG_UNBLOCK, Tasking::PCB::Signals, thisProcess, Tasking::Signal::Unblock(), and warn.
linux_sigreturn()
static void linux_sigreturn (SysFrm * sf) static
Definition at line 1610 of file linux.cpp.
 {
     thisProcess->Signals->RestoreHandleSignal(sf);
 }
References thisProcess.
linux_stat()
static int linux_stat (SysFrm * , const char * pathname, struct stat * statbuf) static
Definition at line 129 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check((void *)pathname, Memory::US))
     {
         debug("Invalid address %#lx", pathname);
         return -EFAULT;
     }
     auto pPathname = pcb->PageTable->Get(pathname);
     return fdt->_stat(pPathname, statbuf);
 }
References vfs::FileDescriptorTable::_stat(), Memory::Virtual::Check(), debug, EFAULT, Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), Tasking::PCB::PageTable, thisProcess, and Memory::US.
linux_tgkill()
static int linux_tgkill (SysFrm * sf, pid_t tgid, pid_t tid, int sig) static
Definition at line 1735 of file linux.cpp.
 {
     Tasking::TCB *target = thisProcess->GetContext()->GetThreadByID(tid);
     if (!target)
         return -ESRCH;
     fixme("semi-stub: %d %d %d", tgid, tid, sig);
     return target->Parent->Signals->SendSignal(sig);
 }
References ESRCH, fixme, Tasking::TCB::Parent, Tasking::Signal::SendSignal(), Tasking::PCB::Signals, and thisProcess.
linux_uname()
static int linux_uname (SysFrm * , struct utsname * buf) static
Definition at line 1156 of file linux.cpp.
 {
     assert(sizeof(struct utsname) < PAGE_SIZE);
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check(buf, Memory::US))
     {
         debug("Invalid address %#lx", buf);
         return -EFAULT;
     }
     auto pBuf = pcb->PageTable->Get(buf);
     struct utsname uname =
     {
         /* TODO: This shouldn't be hardcoded */
         .sysname = KERNEL_NAME,
         .nodename = "fennix",
         .release = KERNEL_VERSION,
         .version = KERNEL_VERSION,
 #if defined(a64)
         .machine = "x86_64",
 #elif defined(a32)
         .machine = "i386",
 #elif defined(aa64)
         .machine = "arm64",
 #elif defined(aa32)
         .machine = "arm",
 #endif
     };
     vfs::RefNode *rn = fs->Open("/etc/cross/linux");
     if (rn)
     {
         Memory::SmartHeap sh(rn->Size);
         rn->read(sh, rn->Size);
         delete rn;
         ini_t *ini = ini_load(sh, NULL);
         int section = ini_find_section(ini, "uname", NULL);
         int sysIdx = ini_find_property(ini, section, "sysname", NULL);
         int nodIdx = ini_find_property(ini, section, "nodename", NULL);
         int relIdx = ini_find_property(ini, section, "release", NULL);
         int verIdx = ini_find_property(ini, section, "version", NULL);
         int macIdx = ini_find_property(ini, section, "machine", NULL);
         const char *uSys = ini_property_value(ini, section, sysIdx);
         const char *uNod = ini_property_value(ini, section, nodIdx);
         const char *uRel = ini_property_value(ini, section, relIdx);
         const char *uVer = ini_property_value(ini, section, verIdx);
         const char *uMac = ini_property_value(ini, section, macIdx);
         debug("sysname=%s", uSys);
         debug("nodename=%s", uNod);
         debug("release=%s", uRel);
         debug("version=%s", uVer);
         debug("machine=%s", uMac);
         if (uSys && strcmp(uSys, "auto") != 0)
             strncpy(uname.sysname, uSys, sizeof(uname.sysname));
         if (uNod && strcmp(uNod, "auto") != 0)
             strncpy(uname.nodename, uNod, sizeof(uname.nodename));
         if (uRel && strcmp(uRel, "auto") != 0)
             strncpy(uname.release, uRel, sizeof(uname.release));
         if (uVer && strcmp(uVer, "auto") != 0)
             strncpy(uname.version, uVer, sizeof(uname.version));
         if (uMac && strcmp(uMac, "auto") != 0)
             strncpy(uname.machine, uMac, sizeof(uname.machine));
         ini_destroy(ini);
     }
     else
         warn("Couldn't open /etc/cross/linux");
     memcpy(pBuf, &uname, sizeof(struct utsname));
     return 0;
 }
References assert, Memory::Virtual::Check(), debug, EFAULT, fs, Memory::PageTable::Get(), ini_destroy(), ini_find_property(), ini_find_section(), ini_load(), ini_property_value(), utsname::machine, memcpy(), utsname::nodename, NULL, vfs::Virtual::Open(), PAGE_SIZE, Tasking::PCB::PageTable, vfs::RefNode::read(), utsname::release, vfs::RefNode::Size, strcmp(), strncpy(), utsname::sysname, thisProcess, Memory::US, utsname::version, and warn.
linux_wait4()
static pid_t linux_wait4 (SysFrm * , pid_t pid, int * wstatus, int options, struct rusage * rusage) static
Definition at line 898 of file linux.cpp.
 {
     static_assert(sizeof(struct rusage) < PAGE_SIZE);
     /* FIXME: this function is very poorly implemented, the way
         it handles the zombie & coredump processes is very
         inefficient and should be rewritten */
     PCB *pcb = thisProcess;
     Memory::Virtual vmm(pcb->PageTable);
     if (!vmm.Check(rusage, Memory::US) && rusage != nullptr)
     {
         debug("Invalid address %#lx", rusage);
         return -EFAULT;
     }
     if (pid == -1)
     {
         if (pcb->Children.empty())
         {
             debug("No children");
             return -ECHILD;
         }
         std::vector<PCB *> wChilds;
         for (auto child : pcb->Children)
         {
             if (child->State == Tasking::Zombie)
             {
                 if (wstatus != nullptr)
                 {
                     int *pWstatus = pcb->PageTable->Get(wstatus);
                     *pWstatus = 0;
                     bool ProcessExited = true;
                     int ExitStatus = child->ExitCode.load();
                     debug("Process returned %d", ExitStatus);
                     if (ProcessExited)
                         *pWstatus |= ExitStatus << 8;
                 }
                 if (rusage != nullptr)
                 {
                     size_t kTime = child->Info.KernelTime;
                     size_t uTime = child->Info.UserTime;
                     size_t _maxrss = child->GetSize();
                     struct rusage *pRusage = pcb->PageTable->Get(rusage);
                     pRusage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
                     pRusage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
                     pRusage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
                     pRusage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
                     pRusage->ru_maxrss = _maxrss;
                 }
                 child->SetState(Tasking::Terminated);
                 return child->ID;
             }
             if (child->State == Tasking::CoreDump)
             {
                 if (wstatus != nullptr)
                 {
                     int *pWstatus = pcb->PageTable->Get(wstatus);
                     *pWstatus = 0;
                     bool ProcessExited = true;
                     int ExitStatus = child->ExitCode.load();
                     bool ProcessSignaled = true;
                     bool CoreDumped = true;
                     int TermSignal = child->Signals->GetLastSignal();
                     debug("Process returned %d", ExitStatus);
                     if (ProcessExited)
                         *pWstatus |= ExitStatus << 8;
                     if (ProcessSignaled)
                         *pWstatus |= TermSignal;
                     if (CoreDumped)
                         *pWstatus |= 0x80;
                 }
                 if (rusage != nullptr)
                 {
                     size_t kTime = child->Info.KernelTime;
                     size_t uTime = child->Info.UserTime;
                     size_t _maxrss = child->GetSize();
                     struct rusage *pRusage = pcb->PageTable->Get(rusage);
                     pRusage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
                     pRusage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
                     pRusage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
                     pRusage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
                     pRusage->ru_maxrss = _maxrss;
                 }
                 child->SetState(Tasking::Terminated);
                 return child->ID;
             }
             if (child->State != Tasking::Terminated)
                 wChilds.push_back(child);
         }
         if (wChilds.empty())
         {
             debug("No children");
             return -ECHILD;
         }
         fixme("Waiting for %d children", wChilds.size());
         pid = wChilds.front()->ID;
     }
     if (pid == 0)
     {
         fixme("Waiting for any child process whose process group ID is equal to that of the calling process");
         return -ENOSYS;
     }
     if (pid < -1)
     {
         fixme("Waiting for any child process whose process group ID is equal to the absolute value of pid");
         return -ENOSYS;
     }
     /* Wait for a child process, or any process? */
     PCB *tPcb = pcb->GetContext()->GetProcessByID(pid);
     if (!tPcb)
     {
         warn("Invalid PID %d", pid);
         return -ECHILD;
     }
     if (options)
     {
 #define WCONTINUED 1
 #define WNOHANG 2
 #define WUNTRACED 4
 #define WEXITED 8
 #define WNOWAIT 16
 #define WSTOPPED 32
         fixme("options=%#x", options);
     }
 #ifdef DEBUG
     foreach (auto child in pcb->Children)
         debug("Child: %s(%d)", child->Name, child->ID);
 #endif
     debug("Waiting for %d(%#lx) state %d", pid, tPcb, tPcb->State);
     while (tPcb->State != Tasking::Zombie &&
            tPcb->State != Tasking::CoreDump &&
            tPcb->State != Tasking::Terminated)
         pcb->GetContext()->Yield();
     debug("Waited for %d(%#lx) state %d", pid, tPcb, tPcb->State);
     if (wstatus != nullptr)
     {
         int *pWstatus = pcb->PageTable->Get(wstatus);
         *pWstatus = 0;
         bool ProcessExited = true;
         int ExitStatus = tPcb->ExitCode.load();
         bool ProcessSignaled = false;
         bool CoreDumped = false;
         bool ProcessStopped = false;
         bool ProcessContinued = false;
         int TermSignal = 0;
         debug("Process returned %d", ExitStatus);
         if (ProcessExited)
             *pWstatus |= ExitStatus << 8;
         if (ProcessSignaled)
             *pWstatus |= TermSignal;
         if (CoreDumped)
             *pWstatus |= 0x80;
         /* FIXME: Untested */
         if (ProcessStopped)
             *pWstatus |= 0x7F;
         if (ProcessContinued)
             *pWstatus = 0xFFFF;
         debug("wstatus=%#x", *pWstatus);
     }
     if (rusage != nullptr)
     {
         size_t kTime = tPcb->Info.KernelTime;
         size_t uTime = tPcb->Info.UserTime;
         size_t _maxrss = tPcb->GetSize();
         struct rusage *pRusage = pcb->PageTable->Get(rusage);
         pRusage->ru_utime.tv_sec = uTime / 1000000000000000; /* Seconds */
         pRusage->ru_utime.tv_usec = uTime / 1000000000;      /* Microseconds */
         pRusage->ru_stime.tv_sec = kTime / 1000000000000000; /* Seconds */
         pRusage->ru_stime.tv_usec = kTime / 1000000000;      /* Microseconds */
         pRusage->ru_maxrss = _maxrss;
         /* TODO: The rest of the fields */
     }
     return pid;
 }
References Memory::Virtual::Check(), Tasking::PCB::Children, Tasking::CoreDump, debug, ECHILD, EFAULT, ENOSYS, fixme, Memory::PageTable::Get(), Tasking::PCB::GetContext(), Tasking::Task::GetProcessByID(), PAGE_SIZE, Tasking::PCB::PageTable, rusage::ru_maxrss, rusage::ru_stime, rusage::ru_utime, Tasking::Terminated, thisProcess, timeval::tv_sec, timeval::tv_usec, Memory::US, warn, and Tasking::Zombie.
linux_write()
static ssize_t linux_write (SysFrm * , int fd, const void * buf, size_t count) static
Definition at line 79 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     const void *pBuf = pcb->PageTable->Get((void *)buf);
     function("%d, %p, %d", fd, buf, count);
     vfs::FileDescriptorTable *fdt = pcb->FileDescriptors;
     ssize_t ret = fdt->_write(fd, pBuf, count);
     if (ret)
         fdt->_lseek(fd, ret, SEEK_CUR);
     return ret;
 }
References vfs::FileDescriptorTable::_lseek(), vfs::FileDescriptorTable::_write(), Tasking::PCB::FileDescriptors, Memory::PageTable::Get(), Tasking::PCB::PageTable, SEEK_CUR, and thisProcess.
Referenced by linux_writev().
linux_writev()
static ssize_t linux_writev (SysFrm * sf, int fildes, const struct iovec * iov, int iovcnt) static
Definition at line 474 of file linux.cpp.
 {
     PCB *pcb = thisProcess;
     const struct iovec *pIov = pcb->PageTable->Get(iov);
     ssize_t Total = 0;
     for (int i = 0; i < iovcnt; i++)
     {
         debug("%d: iov[%d]: %p %d", fildes, i, pIov[i].iov_base, pIov[i].iov_len);
         if (!pIov[i].iov_base)
         {
             debug("invalid iov_base");
             return -EFAULT;
         }
         if (pIov[i].iov_len == 0)
         {
             debug("invalid iov_len");
             continue;
         }
         ssize_t n = linux_write(sf, fildes, pIov[i].iov_base, pIov[i].iov_len);
         if (n < 0)
             return n;
         debug("n: %d", n);
         Total += n;
         if (n < (ssize_t)pIov[i].iov_len)
         {
             debug("break");
             break;
         }
     }
     debug("writev: %d", Total);
     return Total;
 }
References debug, EFAULT, Memory::PageTable::Get(), iovec::iov_base, iovec::iov_len, linux_write(), Tasking::PCB::PageTable, and thisProcess.
Variable Documentation
LinuxSyscallsTableAMD64
SyscallData LinuxSyscallsTableAMD64[] static
Definition at line 1906 of file linux.cpp.
Referenced by HandleLinuxSyscalls().
LinuxSyscallsTableI386
SyscallData LinuxSyscallsTableI386[] static
Definition at line 2356 of file linux.cpp.
Referenced by HandleLinuxSyscalls().