Fennix: Userspace/apps/base/busybox/networking/ping.c File Reference
ping.c File Reference
#include <net/if.h>
#include <netinet/ip_icmp.h>
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define SOL_RAW IPPROTO_RAW
#define create_icmp_socket(lsa) create_icmp_socket()
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
#define common_ping_main(af, argv) common_ping_main(argv)
Enumerations
enum {
DEFDATALEN = 56 , MAXIPLEN = 60 , MAXICMPLEN = 76 , MAX_DUP_CHK = (8 * 128) ,
MAXWAIT = 10 , PINGINTERVAL = 1 , pingsock = 0
}
Functions
static void create_icmp_socket (void)
static void noresp (int ign UNUSED_PARAM)
static void ping4 (len_and_sockaddr *lsa)
static int common_ping_main (sa_family_t af, char **argv)
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
common_ping_main
#define common_ping_main (af, argv) common_ping_main(argv)
Definition at line 338 of file ping.c.
create_icmp_socket
#define create_icmp_socket (lsa) create_icmp_socket()
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 244 of file ping.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 245 of file ping.c.
SOL_RAW
#define SOL_RAW IPPROTO_RAW
Definition at line 154 of file ping.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DEFDATALEN
MAXIPLEN
MAXICMPLEN
MAX_DUP_CHK
MAXWAIT
PINGINTERVAL
pingsock
Definition at line 201 of file ping.c.
      {
     DEFDATALEN = 56,
     MAXIPLEN = 60,
     MAXICMPLEN = 76,
     MAX_DUP_CHK = (8 * 128),
     MAXWAIT = 10,
     PINGINTERVAL = 1, /* 1 second */
     pingsock = 0,
 };
Function Documentation
common_ping_main()
static int common_ping_main (sa_family_t af, char ** argv) static
Definition at line 340 of file ping.c.
 {
     len_and_sockaddr *lsa;
     INIT_G();
 #if ENABLE_PING6
     while ((++argv)[0] && argv[0][0] == '-') {
         if (argv[0][1] == '4') {
             af = AF_INET;
             continue;
         }
         if (argv[0][1] == '6') {
             af = AF_INET6;
             continue;
         }
         bb_show_usage();
     }
 #else
     argv++;
 #endif
     G.hostname = *argv;
     if (!G.hostname)
         bb_show_usage();
 #if ENABLE_PING6
     lsa = xhost_and_af2sockaddr(G.hostname, 0, af);
 #else
     lsa = xhost_and_af2sockaddr(G.hostname, 0, AF_INET);
 #endif
     /* Set timer _after_ DNS resolution */
     signal(SIGALRM, noresp);
     alarm(5); /* give the host 5000ms to respond */
     create_icmp_socket(lsa);
     G.myid = (uint16_t) getpid();
     /* we can use native-endian ident, but other Unix ping/traceroute
      * utils use *big-endian pid*, and e.g. traceroute on our machine may be
      * *not* from busybox, idents may collide. Follow the convention:
      */
     G.myid = htons(G.myid);
 #if ENABLE_PING6
     if (lsa->u.sa.sa_family == AF_INET6)
         ping6(lsa);
     else
 #endif
         ping4(lsa);
     if (ENABLE_FEATURE_CLEAN_UP)
         close(pingsock);
     printf("%s is alive!\n", G.hostname);
     return EXIT_SUCCESS;
 }
References AF_INET, AF_INET6, alarm(), argv, bb_show_usage(), close(), create_icmp_socket, EXIT_SUCCESS, G, getpid(), htons(), INIT_G, lsa, noresp(), ping4(), pingsock, printf, SIGALRM, signal, and xhost_and_af2sockaddr.
create_icmp_socket()
static void create_icmp_socket (void) static
Definition at line 215 of file ping.c.
 {
     int sock;
 #if ENABLE_PING6
     if (lsa->u.sa.sa_family == AF_INET6)
         sock = socket(AF_INET6, SOCK_RAW, IPPROTO_ICMPV6);
     else
 #endif
         sock = socket(AF_INET, SOCK_RAW, 1); /* 1 == ICMP */
     if (sock < 0) {
         if (errno == EPERM)
             bb_simple_error_msg_and_die(bb_msg_perm_denied_are_you_root);
         bb_simple_perror_msg_and_die(bb_msg_can_not_create_raw_socket);
     }
     xmove_fd(sock, pingsock);
 }
References AF_INET, AF_INET6, bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), EPERM, errno, IPPROTO_ICMPV6, lsa, pingsock, sock, SOCK_RAW, socket(), and xmove_fd().
noresp()
static void noresp (int ign UNUSED_PARAM) static
Definition at line 247 of file ping.c.
 {
     printf("No response from %s\n", G.hostname);
     exit(EXIT_FAILURE);
 }
References exit(), EXIT_FAILURE, G, and printf.
Referenced by common_ping_main().
ping4()
static void ping4 (len_and_sockaddr * lsa) static
Definition at line 253 of file ping.c.
 {
     struct icmp *pkt;
     int c;
     pkt = (struct icmp *) G.packet;
     /*memset(pkt, 0, sizeof(G.packet)); already is */
     pkt->icmp_type = ICMP_ECHO;
     pkt->icmp_id = G.myid;
     pkt->icmp_cksum = inet_cksum(pkt, sizeof(G.packet));
     xsendto(pingsock, G.packet, DEFDATALEN + ICMP_MINLEN, &lsa->u.sa, lsa->len);
     /* listen for replies */
     while (1) {
 #if 0
         struct sockaddr_in from;
         socklen_t fromlen = sizeof(from);
         c = recvfrom(pingsock, G.packet, sizeof(G.packet), 0,
                 (struct sockaddr *) &from, &fromlen);
 #else
         c = recv(pingsock, G.packet, sizeof(G.packet), 0);
 #endif
         if (c < 0) {
             if (errno != EINTR)
                 bb_simple_perror_msg("recvfrom");
             continue;
         }
         if (c >= 76) {          /* ip + icmp */
             struct iphdr *iphdr = (struct iphdr *) G.packet;
             pkt = (struct icmp *) (G.packet + (iphdr->ihl << 2));   /* skip ip hdr */
             if (pkt->icmp_id != G.myid)
                 continue; /* not our ping */
             if (pkt->icmp_type == ICMP_ECHOREPLY)
                 break;
         }
     }
 }
References bb_simple_perror_msg(), c, DEFDATALEN, EINTR, errno, G, icmp::icmp_cksum, ICMP_ECHO, ICMP_ECHOREPLY, ICMP_MINLEN, icmp::icmp_type, iphdr::ihl, inet_cksum(), lsa, pingsock, recv(), recvfrom(), and xsendto().
Referenced by common_ping_main().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING