Fennix: Userspace/apps/base/bash/lib/readline/undo.c File Reference
undo.c File Reference
#include <sys/types.h>
#include "ansi_stdlib.h"
#include <stdio.h>
#include "rldefs.h"
#include "readline.h"
#include "history.h"
#include "rlprivate.h"
#include "xmalloc.h"
#include "histlib.h"
Macros
#define READLINE_LIBRARY
#define TRANS(i) ((i) == -1 ? rl_point : ((i) == -2 ? rl_end : (i)))
Functions
static UNDO_LIST * alloc_undo_entry (enum undo_code what, int start, int end, char *text)
void rl_add_undo (enum undo_code what, int start, int end, char *text)
void _rl_free_undo_list (UNDO_LIST *ul)
void rl_free_undo_list (void)
UNDO_LIST * _rl_copy_undo_entry (UNDO_LIST *entry)
UNDO_LIST * _rl_copy_undo_list (UNDO_LIST *head)
int rl_do_undo (void)
int _rl_fix_last_undo_of_type (int type, int start, int end)
int rl_begin_undo_group (void)
int rl_end_undo_group (void)
int rl_modifying (int start, int end)
int rl_revert_line (int count, int key)
int rl_undo_command (int count, int key)
Variables
int _rl_doing_an_undo = 0
int _rl_undo_group_level = 0
UNDO_LIST * rl_undo_list = (UNDO_LIST *)NULL
Macro Definition Documentation
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file undo.c.
TRANS
#define TRANS (i) ((i) == -1 ? rl_point : ((i) == -2 ? rl_end : (i)))
Function Documentation
_rl_copy_undo_entry()
UNDO_LIST* _rl_copy_undo_entry (UNDO_LIST * entry)
Definition at line 128 of file undo.c.
 {
   UNDO_LIST *new;
   new = alloc_undo_entry (entry->what, entry->start, entry->end, (char *)NULL);
   new->text = entry->text ? savestring (entry->text) : 0;
   return new;
 }
References alloc_undo_entry(), NULL, and savestring().
Referenced by _rl_copy_undo_list().
_rl_copy_undo_list()
UNDO_LIST* _rl_copy_undo_list (UNDO_LIST * head)
Definition at line 138 of file undo.c.
 {
   UNDO_LIST *list, *new, *roving, *c;
   if (head == 0)
     return head;
   list = head;
   new = 0;
   while (list)
     {
       c = _rl_copy_undo_entry (list);
       if (new == 0)
     roving = new = c;
       else
     {
       roving->next = c;
       roving = roving->next;
     }
       list = list->next;
     }
   roving->next = 0;
   return new;
 }
References _rl_copy_undo_entry(), c, head, list(), undo_list::next, and node::next.
_rl_fix_last_undo_of_type()
int _rl_fix_last_undo_of_type (int type, int start, int end)
Definition at line 274 of file undo.c.
 {
   UNDO_LIST *rl;
   for (rl = rl_undo_list; rl; rl = rl->next)
     {
       if (rl->what == type)
     {
       rl->start = start;
       rl->end = end;
       return 0;
     }
     }
   return 1;
 }
References undo_list::end, end, undo_list::next, rl_undo_list, undo_list::start, start, type, and undo_list::what.
_rl_free_undo_list()
void _rl_free_undo_list (UNDO_LIST * ul)
Definition at line 99 of file undo.c.
 {
   UNDO_LIST *release;
   while (ul)
     {
       release = ul;
       ul = ul->next;
       if (release->what == UNDO_DELETE)
     xfree (release->text);
       xfree (release);
     }
 }
References release(), UNDO_DELETE, and xfree.
Referenced by _rl_free_saved_history_line(), rl_clear_history(), and rl_free_undo_list().
alloc_undo_entry()
static UNDO_LIST* alloc_undo_entry (enum undo_code what, int start, int end, char * text) static
Definition at line 71 of file undo.c.
 {
   UNDO_LIST *temp;
   temp = (UNDO_LIST *)xmalloc (sizeof (UNDO_LIST));
   temp->what = what;
   temp->start = start;
   temp->end = end;
   temp->text = text;
   temp->next = (UNDO_LIST *)NULL;
   return temp;
 }
References undo_list::end, end, undo_list::next, NULL, undo_list::start, start, undo_list::text, text, undo_list::what, and xmalloc.
Referenced by _rl_copy_undo_entry(), and rl_add_undo().
rl_add_undo()
void rl_add_undo (enum undo_code what, int start, int end, char * text)
Definition at line 88 of file undo.c.
 {
   UNDO_LIST *temp;
   temp = alloc_undo_entry (what, start, end, text);
   temp->next = rl_undo_list;
   rl_undo_list = temp;
 }
References alloc_undo_entry(), end, undo_list::next, rl_undo_list, start, and text.
Referenced by rl_begin_undo_group(), rl_delete_text(), rl_end_undo_group(), rl_insert_text(), and rl_modifying().
rl_begin_undo_group()
int rl_begin_undo_group (void)
Definition at line 292 of file undo.c.
 {
   rl_add_undo (UNDO_BEGIN, 0, 0, 0);
   _rl_undo_group_level++;
   return 0;
 }
References _rl_undo_group_level, rl_add_undo(), and UNDO_BEGIN.
Referenced by _rl_overwrite_char(), _rl_overwrite_rubout(), _rl_replace_text(), _rl_vi_change_char(), _rl_vi_replace_insert(), _rl_vi_stuff_insert(), insert_all_matches(), rl_kill_full_line(), rl_modifying(), rl_transpose_chars(), rl_transpose_words(), rl_vi_change_case(), rl_vi_overstrike(), rl_vi_start_inserting(), rl_yank_nth_arg_internal(), vi_change_dispatch(), and vi_yank_dispatch().
rl_do_undo()
int rl_do_undo (void)
Definition at line 167 of file undo.c.
 {
   UNDO_LIST *release, *search;
   int waiting_for_begin, start, end;
   HIST_ENTRY *cur, *temp;
 #define TRANS(i) ((i) == -1 ? rl_point : ((i) == -2 ? rl_end : (i)))
   start = end = waiting_for_begin = 0;
   do
     {
       if (rl_undo_list == 0)
     return (0);
       _rl_doing_an_undo = 1;
       RL_SETSTATE(RL_STATE_UNDOING);
       /* To better support vi-mode, a start or end value of -1 means
      rl_point, and a value of -2 means rl_end. */
       if (rl_undo_list->what == UNDO_DELETE || rl_undo_list->what == UNDO_INSERT)
     {
       start = TRANS (rl_undo_list->start);
       end = TRANS (rl_undo_list->end);
     }
       switch (rl_undo_list->what)
     {
     /* Undoing deletes means inserting some text. */
     case UNDO_DELETE:
       rl_point = start;
       _rl_fix_point (1);
       rl_insert_text (rl_undo_list->text);
       xfree (rl_undo_list->text);
       break;
     /* Undoing inserts means deleting some text. */
     case UNDO_INSERT:
       rl_delete_text (start, end);
       rl_point = start;
       _rl_fix_point (1);
       break;
     /* Undoing an END means undoing everything 'til we get to a BEGIN. */
     case UNDO_END:
       waiting_for_begin++;
       break;
     /* Undoing a BEGIN means that we are done with this group. */
     case UNDO_BEGIN:
       if (waiting_for_begin)
         waiting_for_begin--;
       else
         rl_ding ();
       break;
     }
       _rl_doing_an_undo = 0;
       RL_UNSETSTATE(RL_STATE_UNDOING);
       release = rl_undo_list;
       rl_undo_list = rl_undo_list->next;
       release->next = 0;    /* XXX */
       /* If we are editing a history entry, make sure the change is replicated
      in the history entry's line */
       cur = current_history ();
       if (cur && cur->data && (UNDO_LIST *)cur->data == release)
     {
       temp = replace_history_entry (where_history (), rl_line_buffer, (histdata_t)rl_undo_list);
       xfree (temp->line);
       FREE (temp->timestamp);
       xfree (temp);
     }
       /* Make sure there aren't any history entries with that undo list */
       _hs_replace_history_data (-1, (histdata_t *)release, (histdata_t *)rl_undo_list);
       /* And make sure this list isn't anywhere in the saved line for history */
       if (_rl_saved_line_for_history && _rl_saved_line_for_history->data)
     {
       /* Brute force; no finesse here */
       search = (UNDO_LIST *)_rl_saved_line_for_history->data;
       if (search == release)
         _rl_saved_line_for_history->data = rl_undo_list;
       else
         {
           while (search->next)
         {
           if (search->next == release)
             {
               search->next = rl_undo_list;
               break;
             }
           search = search->next;
         }
         }
     }
       xfree (release);
     }
   while (waiting_for_begin);
   return (1);
 }
References _hs_replace_history_data(), _rl_doing_an_undo, _rl_fix_point(), _rl_saved_line_for_history, cur, current_history(), _hist_entry::data, undo_list::end, end, FREE, if(), _hist_entry::line, undo_list::next, release(), replace_history_entry(), rl_delete_text(), rl_ding(), rl_insert_text(), rl_line_buffer, rl_point, RL_SETSTATE, RL_STATE_UNDOING, rl_undo_list, RL_UNSETSTATE, search(), undo_list::start, start, undo_list::text, _hist_entry::timestamp, TRANS, UNDO_BEGIN, UNDO_DELETE, UNDO_END, UNDO_INSERT, undo_list::what, where_history(), and xfree.
Referenced by _rl_revert_previous_lines(), rl_revert_line(), rl_undo_command(), rl_vi_overstrike_delete(), rl_yank_last_arg(), and vi_yank_dispatch().
rl_end_undo_group()
int rl_end_undo_group (void)
Definition at line 301 of file undo.c.
 {
   rl_add_undo (UNDO_END, 0, 0, 0);
   _rl_undo_group_level--;
   return 0;
 }
References _rl_undo_group_level, rl_add_undo(), and UNDO_END.
Referenced by _rl_overwrite_char(), _rl_overwrite_rubout(), _rl_replace_text(), _rl_vi_change_char(), _rl_vi_done_inserting(), _rl_vi_replace_insert(), _rl_vi_stuff_insert(), insert_all_matches(), rl_kill_full_line(), rl_modifying(), rl_transpose_chars(), rl_transpose_words(), rl_vi_change_case(), rl_vi_overstrike_delete(), rl_yank_nth_arg_internal(), vi_change_dispatch(), and vi_yank_dispatch().
rl_free_undo_list()
void rl_free_undo_list (void)
Definition at line 117 of file undo.c.
 {
   UNDO_LIST *release, *orig_list;
   orig_list = rl_undo_list;
   _rl_free_undo_list (rl_undo_list);
   rl_undo_list = (UNDO_LIST *)NULL;
   _hs_replace_history_data (-1, (histdata_t *)orig_list, (histdata_t *)NULL);
 }
References _hs_replace_history_data(), _rl_free_undo_list(), NULL, release(), and rl_undo_list.
Referenced by _rl_nsearch_dosearch(), free_undo_list(), make_history_line_current(), readline_internal_teardown(), rl_free_line_state(), rl_replace_line(), and rl_vi_movement_mode().
rl_modifying()
int rl_modifying (int start, int end)
Definition at line 310 of file undo.c.
 {
   if (start > end)
     {
       SWAP (start, end);
     }
   if (start != end)
     {
       char *temp = rl_copy_text (start, end);
       rl_begin_undo_group ();
       rl_add_undo (UNDO_DELETE, start, end, temp);
       rl_add_undo (UNDO_INSERT, start, end, (char *)NULL);
       rl_end_undo_group ();
     }
   return 0;
 }
References end, NULL, rl_add_undo(), rl_begin_undo_group(), rl_copy_text(), rl_end_undo_group(), start, SWAP, UNDO_DELETE, and UNDO_INSERT.
Referenced by invert_case_line(), and rl_change_case().
rl_revert_line()
int rl_revert_line (int count, int key)
Definition at line 330 of file undo.c.
 {
   if (rl_undo_list == 0)
     rl_ding ();
   else
     {
       while (rl_undo_list)
     rl_do_undo ();
 #if defined (VI_MODE)
       if (rl_editing_mode == vi_mode)
     rl_point = rl_mark = 0;     /* rl_end should be set correctly */
 #endif
     }
   return 0;
 }
References rl_ding(), rl_do_undo(), rl_editing_mode, rl_mark, rl_point, rl_undo_list, and vi_mode.
Referenced by readline_internal_teardown().
rl_undo_command()
int rl_undo_command (int count, int key)
Definition at line 349 of file undo.c.
 {
   if (count < 0)
     return 0;   /* Nothing to do. */
   while (count)
     {
       if (rl_do_undo ())
     count--;
       else
     {
       rl_ding ();
       break;
     }
     }
   return 0;
 }
References count, rl_ding(), and rl_do_undo().
Referenced by rl_vi_undo().
Variable Documentation
_rl_doing_an_undo
int _rl_doing_an_undo = 0
Definition at line 56 of file undo.c.
Referenced by rl_delete_text(), rl_do_undo(), and rl_insert_text().
_rl_undo_group_level
int _rl_undo_group_level = 0
Definition at line 59 of file undo.c.
Referenced by _rl_vi_done_inserting(), rl_begin_undo_group(), and rl_end_undo_group().
rl_undo_list
UNDO_LIST* rl_undo_list = (UNDO_LIST *)NULL
Definition at line 62 of file undo.c.
Referenced by _rl_fix_last_undo_of_type(), _rl_free_saved_history_line(), _rl_nsearch_init(), _rl_revert_previous_lines(), _rl_vi_done_inserting(), _rl_vi_save_replace(), make_history_line_current(), readline_internal_teardown(), rl_add_undo(), rl_clear_history(), rl_do_undo(), rl_free_undo_list(), rl_insert_text(), rl_maybe_replace_line(), rl_maybe_save_line(), rl_maybe_unsave_line(), rl_redisplay(), rl_replace_from_history(), rl_restore_state(), rl_revert_line(), and rl_save_state().