Fennix Userspace: Userspace/mlibc/options/linux/include/bits/linux/linux_unistd.h File Reference
linux_unistd.h File Reference
Functions
int dup3 (int fd, int newfd, int flags)
int vhangup (void)
int getdtablesize (void)
Function Documentation
dup3()
int dup3 (int fd, int newfd, int flags)
Definition at line 6 of file linux-unistd.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
getdtablesize()
int getdtablesize (void)
Definition at line 146 of file oslib.c.
 {
 #  if defined (_POSIX_VERSION) && defined (HAVE_SYSCONF) && defined (_SC_OPEN_MAX)
   return (sysconf(_SC_OPEN_MAX));   /* Posix systems use sysconf */
 #  else /* ! (_POSIX_VERSION && HAVE_SYSCONF && _SC_OPEN_MAX) */
 #    if defined (ULIMIT_MAXFDS)
   return (ulimit (4, 0L));  /* System V.3 systems use ulimit(4, 0L) */
 #    else /* !ULIMIT_MAXFDS */
 #      if defined (NOFILE)  /* Other systems use NOFILE */
   return (NOFILE);
 #      else /* !NOFILE */
   return (20);          /* XXX - traditional value is 20 */
 #      endif /* !NOFILE */
 #    endif /* !ULIMIT_MAXFDS */
 #  endif /* ! (_POSIX_VERSION && _SC_OPEN_MAX) */
 }
References _SC_OPEN_MAX, getrlimit(), INT_MAX, L, NOFILE, rlimit::rlim_cur, RLIMIT_NOFILE, sysconf(), and ulimit().
Referenced by dup2(), getmaxfd(), main(), and move_to_high_fd().
vhangup()
int vhangup (void)
Definition at line 11 of file linux-unistd.cpp.
                   {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, and syscall().