Fennix Userspace: Userspace/musl/include/sys/sysinfo.h File Reference
sysinfo.h File Reference
Data Structures
struct sysinfo
Macros
#define SI_LOAD_SHIFT 16
Functions
int sysinfo (struct sysinfo *)
int get_nprocs_conf (void)
int get_nprocs (void)
long get_phys_pages (void)
long get_avphys_pages (void)
Data Structure Documentation
sysinfo
struct sysinfo
Definition at line 10 of file sysinfo.h.
Data Fields
char __reserved[256]
unsigned long bufferram
unsigned long freehigh
unsigned long freeram
unsigned long freeswap
unsigned long loads[3]
unsigned mem_unit
unsigned short pad
unsigned short procs
unsigned long sharedram
unsigned long totalhigh
unsigned long totalram
unsigned long totalswap
unsigned long uptime
Macro Definition Documentation
SI_LOAD_SHIFT
#define SI_LOAD_SHIFT 16
Definition at line 8 of file sysinfo.h.
Function Documentation
get_avphys_pages()
long get_avphys_pages (void)
Definition at line 19 of file legacy.c.
 {
     return sysconf(_SC_AVPHYS_PAGES);
 }
References _SC_AVPHYS_PAGES, and sysconf().
get_nprocs()
int get_nprocs (void)
Definition at line 9 of file legacy.c.
 {
     return sysconf(_SC_NPROCESSORS_ONLN);
 }
References _SC_NPROCESSORS_ONLN, and sysconf().
get_nprocs_conf()
int get_nprocs_conf (void)
Definition at line 4 of file legacy.c.
 {
     return sysconf(_SC_NPROCESSORS_CONF);
 }
References _SC_NPROCESSORS_CONF, and sysconf().
get_phys_pages()
long get_phys_pages (void)
Definition at line 14 of file legacy.c.
 {
     return sysconf(_SC_PHYS_PAGES);
 }
References _SC_PHYS_PAGES, and sysconf().
sysinfo()
int sysinfo (struct sysinfo *)
Referenced by free_main(), getloadavg(), and uptime_main().