Fennix Userspace: mlibc::polymorphic_charcode Struct Reference
mlibc::polymorphic_charcode Struct Reference abstract
#include <charcode.hpp>
Public Member Functions
virtual ~polymorphic_charcode ()
charcode_error promote (char nc, codepoint &wc)
charcode_error promote_wtranscode (char nc, wchar_t &wc)
polymorphic_charcode (bool preserves_7bit_units_, bool has_shift_states_)
virtual charcode_error decode (code_seq< const char > &nseq, code_seq< codepoint > &wseq, __mlibc_mbstate &st)=0
virtual charcode_error decode_wtranscode (code_seq< const char > &nseq, code_seq< wchar_t > &wseq, __mlibc_mbstate &st)=0
virtual charcode_error decode_wtranscode_length (code_seq< const char > &nseq, size_t *n, __mlibc_mbstate &st)=0
virtual charcode_error encode_wtranscode (code_seq< char > &nseq, code_seq< const wchar_t > &wseq, __mlibc_mbstate &st)=0
virtual charcode_error encode_wtranscode_length (code_seq< const wchar_t > &wseq, size_t *n, __mlibc_mbstate &st)=0
Data Fields
const bool preserves_7bit_units
const bool has_shift_states
Detailed Description
Definition at line 44 of file charcode.hpp.
Constructor & Destructor Documentation
~polymorphic_charcode()
mlibc::polymorphic_charcode::~polymorphic_charcode () virtual default
polymorphic_charcode()
mlibc::polymorphic_charcode::polymorphic_charcode (bool preserves_7bit_units_, bool has_shift_states_) inline
Definition at line 87 of file charcode.hpp.
     : preserves_7bit_units{preserves_7bit_units_}, has_shift_states{has_shift_states_} { }
Member Function Documentation
decode()
virtual charcode_error mlibc::polymorphic_charcode::decode (code_seq< const char > & nseq, code_seq< codepoint > & wseq, __mlibc_mbstate & st) pure virtual
Implemented in mlibc::polymorphic_charcode_adapter< G >.
Referenced by promote().
decode_wtranscode()
virtual charcode_error mlibc::polymorphic_charcode::decode_wtranscode (code_seq< const char > & nseq, code_seq< wchar_t > & wseq, __mlibc_mbstate & st) pure virtual
Implemented in mlibc::polymorphic_charcode_adapter< G >.
Referenced by promote_wtranscode().
decode_wtranscode_length()
virtual charcode_error mlibc::polymorphic_charcode::decode_wtranscode_length (code_seq< const char > & nseq, size_t * n, __mlibc_mbstate & st) pure virtual
Implemented in mlibc::polymorphic_charcode_adapter< G >.
encode_wtranscode()
virtual charcode_error mlibc::polymorphic_charcode::encode_wtranscode (code_seq< char > & nseq, code_seq< const wchar_t > & wseq, __mlibc_mbstate & st) pure virtual
Implemented in mlibc::polymorphic_charcode_adapter< G >.
encode_wtranscode_length()
virtual charcode_error mlibc::polymorphic_charcode::encode_wtranscode_length (code_seq< const wchar_t > & wseq, size_t * n, __mlibc_mbstate & st) pure virtual
Implemented in mlibc::polymorphic_charcode_adapter< G >.
promote()
charcode_error mlibc::polymorphic_charcode::promote (char nc, codepoint & wc) inline
Definition at line 48 of file charcode.hpp.
{
         auto uc = static_cast<unsigned char>(nc);
         if(uc <= 0x7F && preserves_7bit_units) {
             wc = uc;
             return charcode_error::null;
         }
         code_seq<const char> nseq{&nc, &nc + 1};
         code_seq<codepoint> wseq{&wc, &wc + 1};
         __mlibc_mbstate st = __MLIBC_MBSTATE_INITIALIZER;
         if(auto e = decode(nseq, wseq, st); e != charcode_error::null)
             return e;
         // This should have read/written exactly one code unit/code point.
         __ensure(nseq.it == nseq.end);
         __ensure(wseq.it == wseq.end);
         return charcode_error::null;
     }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, decode(), mlibc::null, and preserves_7bit_units.
promote_wtranscode()
charcode_error mlibc::polymorphic_charcode::promote_wtranscode (char nc, wchar_t & wc) inline
Definition at line 68 of file charcode.hpp.
{
         auto uc = static_cast<unsigned char>(nc);
         if(uc <= 0x7F && preserves_7bit_units) { // TODO: Use "wtranscode_preserves_7bit_units".
             wc = uc;
             return charcode_error::null;
         }
         code_seq<const char> nseq{&nc, &nc + 1};
         code_seq<wchar_t> wseq{&wc, &wc + 1};
         __mlibc_mbstate st = __MLIBC_MBSTATE_INITIALIZER;
         if(auto e = decode_wtranscode(nseq, wseq, st); e != charcode_error::null)
             return e;
         // This should have read/written exactly one code unit/code point.
         __ensure(nseq.it == nseq.end);
         __ensure(wseq.it == wseq.end);
         return charcode_error::null;
     }
References __ensure, __MLIBC_MBSTATE_INITIALIZER, decode_wtranscode(), mlibc::null, and preserves_7bit_units.
Field Documentation
has_shift_states
const bool mlibc::polymorphic_charcode::has_shift_states
Definition at line 109 of file charcode.hpp.
preserves_7bit_units
const bool mlibc::polymorphic_charcode::preserves_7bit_units
Definition at line 106 of file charcode.hpp.
Referenced by promote(), and promote_wtranscode().
The documentation for this struct was generated from the following files:
Userspace/mlibc/options/internal/include/mlibc/charcode.hpp
Userspace/mlibc/options/internal/generic/charcode.cpp