Fennix: Userspace/apps/base/busybox/util-linux/volume_id/udf.c File Reference
udf.c File Reference
#include "volume_id_internal.h"
Data Structures
struct volume_descriptor
struct volume_descriptor::descriptor_tag
struct volume_structure_descriptor
union volume_descriptor.type
struct anchor_descriptor.type.anchor
struct primary_descriptor.type.primary
struct dstring.type.primary.ident
Macros
#define UDF_VSD_OFFSET 0x8000
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_udf (struct volume_id *id)
Variables
struct volume_descriptor PACKED
Data Structure Documentation
volume_descriptor
struct volume_descriptor
Definition at line 29 of file udf.c.
Data Fields
struct descriptor_tag tag
union volume_descriptor type
volume_descriptor::descriptor_tag
struct volume_descriptor::descriptor_tag
Definition at line 30 of file udf.c.
Data Fields
uint8_t checksum
uint16_t crc
uint16_t crc_len
uint16_t id
uint32_t location
uint8_t reserved
uint16_t serial
uint16_t version
volume_structure_descriptor
struct volume_structure_descriptor
Definition at line 56 of file udf.c.
Data Fields
uint8_t id[5]
uint8_t type
uint8_t version
volume_descriptor.type
union volume_descriptor.type
Definition at line 40 of file udf.c.
Data Fields
type anchor
type primary
volume_descriptor::anchor_descriptor.type.anchor
struct volume_descriptor::anchor_descriptor.type.anchor
Definition at line 41 of file udf.c.
Data Fields
uint32_t length
uint32_t location
volume_descriptor::primary_descriptor.type.primary
struct volume_descriptor::primary_descriptor.type.primary
Definition at line 45 of file udf.c.
Data Fields
uint32_t desc_num
primary ident
uint32_t seq_num
volume_descriptor::primary_descriptor::dstring.type.primary.ident
struct volume_descriptor::primary_descriptor::dstring.type.primary.ident
Definition at line 48 of file udf.c.
Data Fields
uint8_t c[31]
uint8_t clen
Macro Definition Documentation
off
#define off ((uint64_t)0)
UDF_VSD_OFFSET
#define UDF_VSD_OFFSET 0x8000
Definition at line 62 of file udf.c.
Function Documentation
volume_id_probe_udf()
int FAST_FUNC volume_id_probe_udf (struct volume_id * id)
Definition at line 64 of file udf.c.
 {
 #define off ((uint64_t)0)
     struct volume_descriptor *vd;
     struct volume_structure_descriptor *vsd;
     unsigned bs;
     unsigned b;
     unsigned type;
     unsigned count;
     unsigned loc;
     unsigned clen;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     vsd = volume_id_get_buffer(id, off + UDF_VSD_OFFSET, 0x200);
     if (vsd == NULL)
         return -1;
     if (memcmp(vsd->id, "NSR02", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "NSR03", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "BEA01", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "BOOT2", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "CD001", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "CDW02", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "TEA03", 5) == 0)
         goto blocksize;
     return -1;
 blocksize:
     /* search the next VSD to get the logical block size of the volume */
     for (bs = 0x800; bs < 0x8000; bs += 0x800) {
         vsd = volume_id_get_buffer(id, off + UDF_VSD_OFFSET + bs, 0x800);
         if (vsd == NULL)
             return -1;
         dbg("test for blocksize: 0x%x", bs);
         if (vsd->id[0] != '\0')
             goto nsr;
     }
     return -1;
 nsr:
     /* search the list of VSDs for a NSR descriptor */
     for (b = 0; b < 64; b++) {
         vsd = volume_id_get_buffer(id, off + UDF_VSD_OFFSET + (b * bs), 0x800);
         if (vsd == NULL)
             return -1;
         dbg("vsd: %c%c%c%c%c",
             vsd->id[0], vsd->id[1], vsd->id[2], vsd->id[3], vsd->id[4]);
         if (vsd->id[0] == '\0')
             return -1;
         if (memcmp(vsd->id, "NSR02", 5) == 0)
             goto anchor;
         if (memcmp(vsd->id, "NSR03", 5) == 0)
             goto anchor;
     }
     return -1;
 anchor:
     /* read anchor volume descriptor */
     vd = volume_id_get_buffer(id, off + (256 * bs), 0x200);
     if (vd == NULL)
         return -1;
     type = le16_to_cpu(vd->tag.id);
     if (type != 2) /* TAG_ID_AVDP */
         goto found;
     /* get descriptor list address and block count */
     count = le32_to_cpu(vd->type.anchor.length) / bs;
     loc = le32_to_cpu(vd->type.anchor.location);
     dbg("0x%x descriptors starting at logical secor 0x%x", count, loc);
     /* pick the primary descriptor from the list */
     for (b = 0; b < count; b++) {
         vd = volume_id_get_buffer(id, off + ((loc + b) * bs), 0x200);
         if (vd == NULL)
             return -1;
         type = le16_to_cpu(vd->tag.id);
         dbg("descriptor type %i", type);
         /* check validity */
         if (type == 0)
             goto found;
         if (le32_to_cpu(vd->tag.location) != loc + b)
             goto found;
         if (type == 1) /* TAG_ID_PVD */
             goto pvd;
     }
     goto found;
  pvd:
 //  volume_id_set_label_raw(id, &(vd->type.primary.ident.clen), 32);
     clen = vd->type.primary.ident.clen;
     dbg("label string charsize=%i bit", clen);
     if (clen == 8)
         volume_id_set_label_string(id, vd->type.primary.ident.c, 31);
     else if (clen == 16)
         volume_id_set_label_unicode16(id, vd->type.primary.ident.c, BE, 31);
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "udf";)
     return 0;
 }
References BE, count, dbg, found, volume_descriptor::descriptor_tag::id, volume_structure_descriptor::id, le16_to_cpu, le32_to_cpu, volume_descriptor::descriptor_tag::location, memcmp(), NULL, off, volume_descriptor::tag, type, volume_descriptor::type, UDF_VSD_OFFSET, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_label_unicode16().
Variable Documentation
PACKED
struct volume_structure_descriptor PACKED