Fennix Kernel: KernelConsole Namespace Reference
KernelConsole Namespace Reference
Data Structures
struct ANSIArgument
struct ANSIParser
struct TerminalAttribute
struct TerminalCell
struct TerminalCursor
class FontRenderer
class VirtualTerminal
Typedefs
typedef void(* PaintCallback) (TerminalCell *Cell, long X, long Y)
typedef void(* CursorCallback) (TerminalCursor *Cursor)
Enumerations
enum TerminalColor {
BLACK , RED , GREEN , YELLOW ,
BLUE , MAGENTA , CYAN , GREY
}
Functions
__no_sanitize ("undefined") char FontRenderer
void paint_callback (TerminalCell *cell, long x, long y)
void cursor_callback (TerminalCursor *cur)
bool SetTheme (std::string Theme)
void EarlyInit ()
void LateInit ()
Variables
int TermColors []
int TermBrightColors []
FontRenderer Renderer
VirtualTerminal * Terminals [16] = {nullptr}
std::atomic< VirtualTerminal * > CurrentTerminal = nullptr
Data Structure Documentation
KernelConsole::ANSIArgument
struct KernelConsole::ANSIArgument
Definition at line 38 of file kcon.hpp.
Data Fields
bool Empty
int Value
KernelConsole::TerminalAttribute
struct KernelConsole::TerminalAttribute
Definition at line 58 of file kcon.hpp.
Data Fields
TerminalColor Background
bool Bright
TerminalColor Foreground
KernelConsole::TerminalCell
struct KernelConsole::TerminalCell
Definition at line 65 of file kcon.hpp.
Data Fields
TerminalAttribute attr
char c
KernelConsole::TerminalCursor
struct KernelConsole::TerminalCursor
Definition at line 71 of file kcon.hpp.
Data Fields
long X
long Y
Typedef Documentation
CursorCallback
typedef void(* KernelConsole::CursorCallback) (TerminalCursor *Cursor)
Definition at line 78 of file kcon.hpp.
PaintCallback
typedef void(* KernelConsole::PaintCallback) (TerminalCell *Cell, long X, long Y)
Definition at line 77 of file kcon.hpp.
Enumeration Type Documentation
TerminalColor
enum KernelConsole::TerminalColor
Enumerator
BLACK
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
GREY
Definition at line 26 of file kcon.hpp.
     {
         BLACK,
         RED,
         GREEN,
         YELLOW,
         BLUE,
         MAGENTA,
         CYAN,
         GREY
     };
Function Documentation
__no_sanitize()
KernelConsole::__no_sanitize ("undefined")
Definition at line 51 of file console.cpp.
     {
         uint64_t x = CellX * CurrentFont->GetInfo().Width;
         uint64_t y = CellY * CurrentFont->GetInfo().Height;
         switch (CurrentFont->GetInfo().Type)
         {
         case Video::FontType::PCScreenFont1:
         {
             uint32_t *PixelPtr = (uint32_t *)Display->GetBuffer;
             char *FontPtr = (char *)CurrentFont->GetInfo().PSF1Font->GlyphBuffer + (Char * CurrentFont->GetInfo().PSF1Font->Header->charsize);
             for (uint64_t Y = 0; Y < 16; Y++)
             {
                 for (uint64_t X = 0; X < 8; X++)
                 {
                     if ((*FontPtr & (0b10000000 >> X)) > 0)
                         *(unsigned int *)(PixelPtr + (x + X) + ((y + Y) * Display->GetWidth)) = Foreground;
                     else
                         *(unsigned int *)(PixelPtr + (x + X) + ((y + Y) * Display->GetWidth)) = Background;
                 }
                 FontPtr++;
             }
             break;
         }
         case Video::FontType::PCScreenFont2:
         {
             Video::FontInfo fInfo = CurrentFont->GetInfo();
             int BytesPerLine = (fInfo.PSF2Font->Header->width + 7) / 8;
             char *FontAddress = (char *)fInfo.StartAddress;
             uint32_t FontHeaderSize = fInfo.PSF2Font->Header->headersize;
             uint32_t FontCharSize = fInfo.PSF2Font->Header->charsize;
             uint32_t FontLength = fInfo.PSF2Font->Header->length;
             char *FontPtr = FontAddress + FontHeaderSize + (Char > 0 && (uint32_t)Char < FontLength ? Char : 0) * FontCharSize;
             uint32_t FontHdrWidth = fInfo.PSF2Font->Header->width;
             uint32_t FontHdrHeight = fInfo.PSF2Font->Header->height;
             for (uint32_t Y = 0; Y < FontHdrHeight; Y++)
             {
                 for (uint32_t X = 0; X < FontHdrWidth; X++)
                 {
                     void *FramebufferAddress = (void *)((uintptr_t)Display->GetBuffer +
                                                         ((y + Y) * Display->GetWidth + (x + X)) *
                                                             (Display->GetFramebufferStruct().BitsPerPixel / 8));
                     if ((*FontPtr & (0b10000000 >> (X % 8))) > 0)
                         *(uint32_t *)FramebufferAddress = Foreground;
                     else
                         *(uint32_t *)FramebufferAddress = Background;
                 }
                 FontPtr += BytesPerLine;
             }
             break;
         }
         default:
             warn("Unsupported font type");
             break;
         }
         return Char;
     }
References BootInfo::FramebufferInfo::BitsPerPixel, Video::PSF2_HEADER::charsize, Display, Video::Display::GetBuffer, Video::Display::GetFramebufferStruct(), Video::Display::GetWidth, Video::_PSF2_FONT::Header, Video::PSF2_HEADER::headersize, Video::PSF2_HEADER::height, Video::PSF2_HEADER::length, Video::PCScreenFont1, Video::PCScreenFont2, Video::FontInfo::PSF2Font, Video::FontInfo::StartAddress, warn, and Video::PSF2_HEADER::width.
cursor_callback()
void KernelConsole::cursor_callback (TerminalCursor * cur)
Definition at line 123 of file console.cpp.
     {
         Renderer.Cursor = {cur->X, cur->Y};
     }
References KernelConsole::FontRenderer::Cursor, Renderer, KernelConsole::TerminalCursor::X, and KernelConsole::TerminalCursor::Y.
Referenced by EarlyInit().
EarlyInit()
void KernelConsole::EarlyInit ()
Definition at line 261 of file console.cpp.
     {
         Renderer.CurrentFont = new Video::Font(&_binary_files_tamsyn_font_1_11_Tamsyn7x14r_psf_start,
                                                &_binary_files_tamsyn_font_1_11_Tamsyn7x14r_psf_end,
                                                Video::FontType::PCScreenFont2);
         size_t Rows = Display->GetWidth / Renderer.CurrentFont->GetInfo().Width;
         size_t Cols = Display->GetHeight / Renderer.CurrentFont->GetInfo().Height;
         debug("Terminal size: %ux%u", Rows, Cols);
         Terminals[0] = new VirtualTerminal(Rows, Cols, Display->GetWidth, Display->GetHeight, paint_callback, cursor_callback);
         Terminals[0]->Clear(0, 0, Rows, Cols - 1);
         CurrentTerminal.store(Terminals[0], std::memory_order_release);
     }
References _binary_files_tamsyn_font_1_11_Tamsyn7x14r_psf_end, _binary_files_tamsyn_font_1_11_Tamsyn7x14r_psf_start, KernelConsole::VirtualTerminal::Clear(), KernelConsole::FontRenderer::CurrentFont, CurrentTerminal, cursor_callback(), debug, Display, Video::Display::GetHeight, Video::Font::GetInfo(), Video::Display::GetWidth, Video::FontInfo::Height, memory_order_release, paint_callback(), Video::PCScreenFont2, Renderer, Terminals, and Video::FontInfo::Width.
Referenced by Main().
LateInit()
void KernelConsole::LateInit ()
Definition at line 275 of file console.cpp.
     {
         FileNode *rn = fs->GetByPath("/etc/term", thisProcess->Info.RootNode);
         if (rn == nullptr)
             return;
         kstat st{};
         rn->Stat(&st);
         char *sh = new char[st.Size];
         rn->Read(sh, st.Size, 0);
         ini_t *ini = ini_load(sh, NULL);
         int general = ini_find_section(ini, "general", NULL);
         int cursor = ini_find_section(ini, "cursor", NULL);
         assert(general != INI_NOT_FOUND && cursor != INI_NOT_FOUND);
         int themeIndex = ini_find_property(ini, general, "theme", NULL);
         assert(themeIndex != INI_NOT_FOUND);
         int cursorColor = ini_find_property(ini, cursor, "color", NULL);
         int cursorBlink = ini_find_property(ini, cursor, "blink", NULL);
         assert(cursorColor != INI_NOT_FOUND && cursorBlink != INI_NOT_FOUND);
         const char *colorThemeStr = ini_property_value(ini, general, themeIndex);
         const char *cursorColorStr = ini_property_value(ini, cursor, cursorColor);
         const char *cursorBlinkStr = ini_property_value(ini, cursor, cursorBlink);
         debug("colorThemeStr=%s", colorThemeStr);
         debug("cursorColorStr=%s", cursorColorStr);
         debug("cursorBlinkStr=%s", cursorBlinkStr);
         auto getColorComponent = [](const char *str, int &index) -> int
         {
             int value = 0;
             while (str[index] >= '0' && str[index] <= '9')
             {
                 value = value * 10 + (str[index] - '0');
                 ++index;
             }
             return value;
         };
         auto parseColor = [getColorComponent](const char *colorStr) -> unsigned int
         {
             int index = 0;
             int r = getColorComponent(colorStr, index);
             if (colorStr[index] == ',')
                 ++index;
             int g = getColorComponent(colorStr, index);
             if (colorStr[index] == ',')
                 ++index;
             int b = getColorComponent(colorStr, index);
             return (r << 16) | (g << 8) | b;
         };
         if (colorThemeStr != 0)
             SetTheme(colorThemeStr);
         if (cursorBlinkStr != 0 && strncmp(cursorBlinkStr, "true", 4) == 0)
         {
             uint32_t blinkColor = 0xFFFFFF;
             if (cursorColorStr != 0)
                 blinkColor = parseColor(cursorColorStr);
             fixme("cursor blink with colors %X", blinkColor);
         }
         ini_destroy(ini);
         delete[] sh;
 #ifdef DEBUG
         // __test_themes();
 #endif
     }
References assert, debug, fixme, fs, vfs::Virtual::GetByPath(), ini_destroy(), ini_find_property(), ini_find_section(), ini_load(), INI_NOT_FOUND, ini_property_value(), NULL, FileNode::Read(), SetTheme(), st, FileNode::Stat(), strncmp(), and thisProcess.
Referenced by KernelMainThread().
paint_callback()
void KernelConsole::paint_callback (TerminalCell * cell, long x, long y)
Definition at line 115 of file console.cpp.
     {
         if (cell->attr.Bright)
             Renderer.Paint(x, y, cell->c, TermBrightColors[cell->attr.Foreground], TermColors[cell->attr.Background]);
         else
             Renderer.Paint(x, y, cell->c, TermColors[cell->attr.Foreground], TermColors[cell->attr.Background]);
     }
References KernelConsole::TerminalCell::attr, KernelConsole::TerminalAttribute::Background, KernelConsole::TerminalAttribute::Bright, KernelConsole::TerminalCell::c, KernelConsole::TerminalAttribute::Foreground, KernelConsole::FontRenderer::Paint(), Renderer, TermBrightColors, and TermColors.
Referenced by BaseBufferStackError(), EarlyInit(), and InitFont().
SetTheme()
bool KernelConsole::SetTheme (std::string Theme)
Definition at line 131 of file console.cpp.
     {
         FileNode *rn = fs->GetByPath("/etc/term", thisProcess->Info.RootNode);
         if (rn == nullptr)
             return false;
         kstat st{};
         rn->Stat(&st);
         char *sh = new char[st.Size];
         rn->Read(sh, st.Size, 0);
         ini_t *ini = ini_load(sh, NULL);
         int themeSection, c0, c1, c2, c3, c4, c5, c6, c7, colorsIdx;
         const char *colors[8];
         debug("Loading terminal theme: \"%s\"", Theme.c_str());
         themeSection = ini_find_section(ini, Theme.c_str(), NULL);
         if (themeSection == INI_NOT_FOUND)
         {
             ini_destroy(ini);
             delete[] sh;
             return false;
         }
         auto getColorComponent = [](const char *str, int &index) -> int
         {
             int value = 0;
             while (str[index] >= '0' && str[index] <= '9')
             {
                 value = value * 10 + (str[index] - '0');
                 ++index;
             }
             return value;
         };
         auto parseColor = [getColorComponent](const char *colorStr) -> unsigned int
         {
             int index = 0;
             int r = getColorComponent(colorStr, index);
             if (colorStr[index] == ',')
                 ++index;
             int g = getColorComponent(colorStr, index);
             if (colorStr[index] == ',')
                 ++index;
             int b = getColorComponent(colorStr, index);
             return (r << 16) | (g << 8) | b;
         };
         c0 = ini_find_property(ini, themeSection, "color0", NULL);
         c1 = ini_find_property(ini, themeSection, "color1", NULL);
         c2 = ini_find_property(ini, themeSection, "color2", NULL);
         c3 = ini_find_property(ini, themeSection, "color3", NULL);
         c4 = ini_find_property(ini, themeSection, "color4", NULL);
         c5 = ini_find_property(ini, themeSection, "color5", NULL);
         c6 = ini_find_property(ini, themeSection, "color6", NULL);
         c7 = ini_find_property(ini, themeSection, "color7", NULL);
         colors[0] = ini_property_value(ini, themeSection, c0);
         colors[1] = ini_property_value(ini, themeSection, c1);
         colors[2] = ini_property_value(ini, themeSection, c2);
         colors[3] = ini_property_value(ini, themeSection, c3);
         colors[4] = ini_property_value(ini, themeSection, c4);
         colors[5] = ini_property_value(ini, themeSection, c5);
         colors[6] = ini_property_value(ini, themeSection, c6);
         colors[7] = ini_property_value(ini, themeSection, c7);
         colorsIdx = 0;
         for (auto color : colors)
         {
             colorsIdx++;
             if (color == 0)
                 continue;
             char *delimiterPos = strchr(color, ':');
             if (delimiterPos == NULL)
                 continue;
             char colorStr[20], colorBrightStr[20];
             strncpy(colorStr, color, delimiterPos - color);
             colorStr[delimiterPos - color] = '\0';
             strcpy(colorBrightStr, delimiterPos + 1);
             TermColors[colorsIdx - 1] = parseColor(colorStr);
             TermBrightColors[colorsIdx - 1] = parseColor(colorBrightStr);
         }
         ini_destroy(ini);
         delete[] sh;
         return true;
     }
References debug, fs, vfs::Virtual::GetByPath(), ini_destroy(), ini_find_property(), ini_find_section(), ini_load(), INI_NOT_FOUND, ini_property_value(), NULL, FileNode::Read(), st, FileNode::Stat(), strchr(), strcpy, strncpy(), TermBrightColors, TermColors, and thisProcess.
Referenced by cmd_theme(), and LateInit().
Variable Documentation
CurrentTerminal
std::atomic< VirtualTerminal * > KernelConsole::CurrentTerminal = nullptr
Definition at line 129 of file console.cpp.
Referenced by Driver::__fs_Close(), Driver::__fs_Ioctl(), Driver::__fs_Open(), Driver::__fs_Read(), Driver::__fs_Write(), EarlyInit(), putchar(), and Execute::Spawn().
Renderer
FontRenderer KernelConsole::Renderer
Definition at line 113 of file console.cpp.
Referenced by cursor_callback(), EarlyInit(), and paint_callback().
TermBrightColors
int KernelConsole::TermBrightColors
Initial value:
= {
        [TerminalColor::BLACK] = 0x858585,
        [TerminalColor::RED] = 0xFF5555,
        [TerminalColor::GREEN] = 0x55FF55,
        [TerminalColor::YELLOW] = 0xFFFF55,
        [TerminalColor::BLUE] = 0x5555FF,
        [TerminalColor::MAGENTA] = 0xFF55FF,
        [TerminalColor::CYAN] = 0x55FFFF,
        [TerminalColor::GREY] = 0xFFFFFF,
    }
Definition at line 40 of file console.cpp.
Referenced by paint_callback(), and SetTheme().
TermColors
int KernelConsole::TermColors
Initial value:
= {
        [TerminalColor::BLACK] = 0x000000,
        [TerminalColor::RED] = 0xAA0000,
        [TerminalColor::GREEN] = 0x00AA00,
        [TerminalColor::YELLOW] = 0xAA5500,
        [TerminalColor::BLUE] = 0x0000AA,
        [TerminalColor::MAGENTA] = 0xAA00AA,
        [TerminalColor::CYAN] = 0x00AAAA,
        [TerminalColor::GREY] = 0xAAAAAA,
    }
Definition at line 29 of file console.cpp.
Referenced by paint_callback(), and SetTheme().
Terminals
VirtualTerminal * KernelConsole::Terminals = {nullptr}
0 - Default 1...11 - User ... 15 - Panic
Definition at line 128 of file console.cpp.
Referenced by __printfWrapper(), BaseBufferStackError(), EarlyInit(), and InitFont().