Fennix Userspace: Userspace/apps/base/bash/lib/sh/zmapfd.c File Reference
zmapfd.c File Reference
#include <config.h>
#include <sys/types.h>
#include <errno.h>
#include "bashansi.h"
#include "command.h"
#include "general.h"
Macros
#define ZBUFSIZ 4096
Functions
ssize_t zread PARAMS ((int, char *, size_t))
int zmapfd (int fd, char **ostr, char *fn)
Variables
int errno
Macro Definition Documentation
ZBUFSIZ
#define ZBUFSIZ 4096
Definition at line 40 of file zmapfd.c.
Function Documentation
PARAMS()
ssize_t zread PARAMS ((int, char *, size_t))
zmapfd()
int zmapfd (int fd, char ** ostr, char * fn)
Definition at line 48 of file zmapfd.c.
 {
   ssize_t nr;
   int rval;
   char lbuf[ZBUFSIZ];
   char *result;
   size_t rsize, rind;
   rval = 0;
   result = (char *)xmalloc (rsize = ZBUFSIZ);
   rind = 0;
   while (1)
     {
       nr = zread (fd, lbuf, sizeof (lbuf));
       if (nr == 0)
     {
       rval = rind;
       break;
     }
       else if (nr < 0)
     {
       free (result);
       if (ostr)
         *ostr = (char *)NULL;
       return -1;
     }
       RESIZE_MALLOCED_BUFFER (result, rind, nr, rsize, ZBUFSIZ);
       memcpy (result+rind, lbuf, nr);
       rind += nr;
     }
   RESIZE_MALLOCED_BUFFER (result, rind, 1, rsize, 128);
   result[rind] = '\0';
   if (ostr)
     *ostr = result;
   else
     free (result);
   return rval;
 }
References free, lbuf, memcpy(), NULL, RESIZE_MALLOCED_BUFFER, xmalloc, ZBUFSIZ, and zread().
Referenced by _evalfile().
Variable Documentation
errno
int errno extern