Fennix Userspace: Userspace/musl/include/search.h File Reference
search.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct entry
Macros
#define __NEED_size_t
Typedefs
typedef struct entry ENTRY
Enumerations
enum ACTION { FIND , ENTER }
enum VISIT {
preorder , postorder , endorder , leaf ,
preorder , postorder , endorder , leaf
}
Functions
int hcreate (size_t)
void hdestroy (void)
ENTRY * hsearch (ENTRY, ACTION)
void insque (void *, void *)
void remque (void *)
void * lsearch (const void *, void *, size_t *, size_t, int(*)(const void *, const void *))
void * lfind (const void *, const void *, size_t *, size_t, int(*)(const void *, const void *))
void * tdelete (const void *__restrict, void **__restrict, int(*)(const void *, const void *))
void * tfind (const void *, void *const *, int(*)(const void *, const void *))
void * tsearch (const void *, void **, int(*)(const void *, const void *))
void twalk (const void *, void(*)(const void *, VISIT, int))
Data Structure Documentation
entry
struct entry
Definition at line 16 of file search.h.
Data Fields
void * data
char * key
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file search.h.
Typedef Documentation
ENTRY
typedef struct entry ENTRY
Enumeration Type Documentation
ACTION
enum ACTION
Enumerator
FIND
ENTER
Definition at line 13 of file search.h.
 { FIND, ENTER } ACTION;
VISIT
enum VISIT
Enumerator
preorder
postorder
endorder
leaf
preorder
postorder
endorder
leaf
Definition at line 14 of file search.h.
 { preorder, postorder, endorder, leaf } VISIT;
Function Documentation
hcreate()
int hcreate (size_t nel)
Definition at line 72 of file hsearch.c.
 {
     return __hcreate_r(nel, &htab);
 }
References __hcreate_r(), and htab.
hdestroy()
void hdestroy (void)
Definition at line 77 of file hsearch.c.
 {
     __hdestroy_r(&htab);
 }
References __hdestroy_r(), and htab.
hsearch()
ENTRY* hsearch (ENTRY item, ACTION action)
Definition at line 95 of file hsearch.c.
 {
     ENTRY *e;
     __hsearch_r(item, action, &e, &htab);
     return e;
 }
References __hsearch_r(), and htab.
insque()
void insque (void * element, void * pred)
Definition at line 8 of file insque.c.
 {
     struct node *e = element;
     struct node *p = pred;
     if (!p) {
         e->next = e->prev = 0;
         return;
     }
     e->next = p->next;
     e->prev = p;
     p->next = e;
     if (e->next)
         e->next->prev = e;
 }
References node::next, p, and node::prev.
lfind()
void* lfind (const void * key, const void * base, size_t * nelp, size_t width, int(*)(const void *, const void *) compar)
Definition at line 142 of file search.cpp.
{
     (void)key;
     (void)base;
     (void)nelp;
     (void)width;
     (void)compar;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, base, i, node::key, n, p, and width.
lsearch()
void* lsearch (const void * key, void * base, size_t * nelp, size_t width, int(*)(const void *, const void *) compar)
Definition at line 131 of file search.cpp.
{
     (void)key;
     (void)base;
     (void)nelp;
     (void)width;
     (void)compar;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, base, i, node::key, memcpy(), n, p, and width.
remque()
void remque (void * element)
Definition at line 24 of file insque.c.
 {
     struct node *e = element;
     if (e->next)
         e->next->prev = e->prev;
     if (e->prev)
         e->prev->next = e->next;
 }
References node::next, and node::prev.
tdelete()
void* tdelete (const void * __restrict, void ** __restrict, int(*)(const void *, const void *) compar)
Definition at line 113 of file search.cpp.
{
     (void)compar;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
tfind()
void* tfind (const void * key, void *const * rootp, int(*)(const void *, const void *) compar)
Definition at line 97 of file search.cpp.
{
     if(!rootp)
         return 0;
     struct node *n = (struct node *)*rootp;
     for(;;) {
         if(!n)
             break;
         int c = compar(key, n->key);
         if(!c)
             break;
         n = (struct node *)n->a[c > 0];
     }
     return n;
 }
References c, cmp(), node::key, and n.
Referenced by check_key(), and main().
tsearch()
void* tsearch (const void * key, void ** rootp, int(*)(const void *, const void *) compar)
Definition at line 65 of file search.cpp.
{
     if (!rootp)
         return NULL;
     struct node *n = static_cast<struct node *>(*rootp);
     frg::stack<struct node **, MemoryAllocator> nodes(getAllocator());
     nodes.push(reinterpret_cast<struct node **>(rootp));
     int c = 0;
     for (;;) {
         if (!n)
             break;
         c = compar(key, n->key);
         if (!c)
             return n;
         nodes.push(reinterpret_cast<struct node **>(&n->a[c > 0]));
         n = static_cast<struct node *>(n->a[c > 0]);
     }
     struct node *insert = static_cast<struct node*>(malloc(sizeof(struct node)));
     if (!insert)
         return NULL;
     insert->key = key;
     insert->a[0] = insert->a[1] = NULL;
     insert->h = 1;
     (*nodes.top()) = insert;
     nodes.pop();
     while(nodes.size() && balance_tree(nodes.top())) nodes.pop();
     return insert;
 }
References __tsearch_balance(), node::a, anonymous_namespace{search.cpp}::balance_tree(), c, cmp(), getAllocator(), node::h, i, node::key, malloc, MAXH, n, nodes, NULL, and r.
Referenced by main(), and while().
twalk()
void twalk (const void * root, void(*)(const void *, VISIT, int) action)
Definition at line 119 of file search.cpp.
{
     (void)action;
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, and walk().