Fennix Userspace: Userspace/apps/base/busybox/libbb/concat_path_file.c File Reference
concat_path_file.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC concat_path_file (const char *path, const char *filename)
Function Documentation
concat_path_file()
char* FAST_FUNC concat_path_file (const char * path, const char * filename)
Definition at line 18 of file concat_path_file.c.
 {
     char *lc;
     if (!path)
         path = "";
     lc = last_char_is(path, '/');
     while (*filename == '/')
         filename++;
     return xasprintf("%s%s%s", path, (lc==NULL ? "/" : ""), filename);
 }
References filename, last_char_is(), NULL, and xasprintf().
Referenced by action_modload(), ash_main(), bb_simplify_path(), build_alias(), concat_subpath_file(), copy_file(), cp_main(), depmod_main(), diff_main(), dir_operation(), download_one_url(), fileAction(), find_executable(), get_header_tar(), hush_main(), install_main(), ln_main(), lsattr_dir_proc(), mktemp_main(), mv_main(), nohup_main(), parse_inittab(), read_interfaces(), restore(), scan_one_dir(), slattach_main(), vi_main(), wall_main(), and xmalloc_realpath_coreutils().