Fennix: Userspace/mlibc/options/posix/generic/sys-resource-stubs.cpp File Reference
sys-resource-stubs.cpp File Reference
#include <errno.h>
#include <sys/resource.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
Functions
int getpriority (int which, id_t who)
int setpriority (int which, id_t who, int prio)
int getrusage (int scope, struct rusage *usage)
int getrlimit (int resource, struct rlimit *limit)
int setrlimit (int resource, const struct rlimit *limit)
Function Documentation
getpriority()
int getpriority (int which, id_t who)
Definition at line 9 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getpriority, -1);
     int value = 0;
     if(int e = mlibc::sys_getpriority(which, who, &value); e) {
         errno = e;
     }
     return value;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_getpriority(), and value.
Referenced by main().
getrlimit()
int getrlimit (int resource, struct rlimit * limit)
Definition at line 36 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getrlimit, -1);
     if(int e = mlibc::sys_getrlimit(resource, limit); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getrlimit().
Referenced by main(), and sysconf().
getrusage()
int getrusage (int scope, struct rusage * usage)
Definition at line 27 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getrusage, -1);
     if(int e = mlibc::sys_getrusage(scope, usage); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getrusage().
setpriority()
int setpriority (int which, id_t who, int prio)
Definition at line 18 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setpriority, -1);
     if(int e = mlibc::sys_setpriority(which, who, prio); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setpriority().
Referenced by main().
setrlimit()
int setrlimit (int resource, const struct rlimit * limit)
Definition at line 45 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setrlimit, -1);
     if(int e = mlibc::sys_setrlimit(resource, limit); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setrlimit().
Referenced by main().