Fennix: Kernel/storage/fs/ustar.cpp File Reference
ustar.cpp File Reference
#include <filesystem/ustar.hpp>
#include <memory.hpp>
#include <functional>
#include <debug.h>
#include "../../kernel.h"
Namespaces
vfs
Macros
#define TMAGIC "ustar"
#define TMAGLEN 6
#define TVERSION "00"
#define TVERSLEN 2
Functions
vfs::__no_sanitize ("alignment") ssize_t USTAR
O2 int __ustar_Lookup (struct Inode *Parent, const char *Name, struct Inode **Result)
O2 int __ustar_Create (struct Inode *Parent, const char *Name, mode_t Mode, struct Inode **Result)
O2 ssize_t __ustar_Read (struct Inode *Node, void *Buffer, size_t Size, off_t Offset)
O2 ssize_t __ustar_Readdir (struct Inode *Node, struct kdirent *Buffer, size_t Size, off_t Offset, off_t Entries)
O2 int __ustar_SymLink (Inode *Parent, const char *Name, const char *Target, Inode **Result)
O2 ssize_t __ustar_ReadLink (Inode *Node, char *Buffer, size_t Size)
O2 int __ustar_Stat (struct Inode *Node, kstat *Stat)
int __ustar_DestroyInode (FileSystemInfo *Info, Inode *Node)
int __ustar_Destroy (FileSystemInfo *fsi)
bool TestAndInitializeUSTAR (uintptr_t Address, size_t Size)
Macro Definition Documentation
TMAGIC
#define TMAGIC "ustar"
Definition at line 26 of file ustar.cpp.
TMAGLEN
#define TMAGLEN 6
Definition at line 27 of file ustar.cpp.
TVERSION
#define TVERSION "00"
Definition at line 28 of file ustar.cpp.
TVERSLEN
#define TVERSLEN 2
Definition at line 29 of file ustar.cpp.
Function Documentation
__ustar_Create()
O2 int __ustar_Create (struct Inode * Parent, const char * Name, mode_t Mode, struct Inode ** Result)
Definition at line 790 of file ustar.cpp.
 {
     return ((vfs::USTAR *)Parent->PrivateData)->Create(Parent, Name, Mode, Result);
 }
References Inode::Mode, Name, and Inode::PrivateData.
Referenced by TestAndInitializeUSTAR().
__ustar_Destroy()
int __ustar_Destroy (FileSystemInfo * fsi)
Definition at line 826 of file ustar.cpp.
 {
     assert(fsi->PrivateData);
     delete (vfs::USTAR *)fsi->PrivateData;
     delete fsi;
     return 0;
 }
References assert, and FileSystemInfo::PrivateData.
Referenced by TestAndInitializeUSTAR().
__ustar_DestroyInode()
int __ustar_DestroyInode (FileSystemInfo * Info, Inode * Node)
Definition at line 820 of file ustar.cpp.
 {
     ((vfs::USTAR::USTARInode *)Node)->Deleted = true;
     return 0;
 }
References Driver::Node.
Referenced by TestAndInitializeUSTAR().
__ustar_Lookup()
O2 int __ustar_Lookup (struct Inode * Parent, const char * Name, struct Inode ** Result)
Definition at line 785 of file ustar.cpp.
 {
     return ((vfs::USTAR *)Parent->PrivateData)->Lookup(Parent, Name, Result);
 }
References Name, and Inode::PrivateData.
Referenced by TestAndInitializeUSTAR().
__ustar_Read()
O2 ssize_t __ustar_Read (struct Inode * Node, void * Buffer, size_t Size, off_t Offset)
Definition at line 795 of file ustar.cpp.
 {
     return ((vfs::USTAR *)Node->PrivateData)->Read(Node, Buffer, Size, Offset);
 }
References Buffer, Driver::Node, Driver::Offset, and Driver::Size.
Referenced by TestAndInitializeUSTAR().
__ustar_Readdir()
O2 ssize_t __ustar_Readdir (struct Inode * Node, struct kdirent * Buffer, size_t Size, off_t Offset, off_t Entries)
Definition at line 800 of file ustar.cpp.
 {
     return ((vfs::USTAR *)Node->PrivateData)->ReadDir(Node, Buffer, Size, Offset, Entries);
 }
References Buffer, Entries, Driver::Node, Driver::Offset, and Driver::Size.
Referenced by TestAndInitializeUSTAR().
__ustar_ReadLink()
O2 ssize_t __ustar_ReadLink (Inode * Node, char * Buffer, size_t Size)
Definition at line 810 of file ustar.cpp.
 {
     return ((vfs::USTAR *)Node->PrivateData)->ReadLink(Node, Buffer, Size);
 }
References Buffer, Driver::Node, and Driver::Size.
Referenced by TestAndInitializeUSTAR().
__ustar_Stat()
O2 int __ustar_Stat (struct Inode * Node, kstat * Stat)
Definition at line 815 of file ustar.cpp.
 {
     return ((vfs::USTAR *)Node->PrivateData)->Stat(Node, Stat);
 }
References Driver::Node, and Stat.
Referenced by TestAndInitializeUSTAR().
__ustar_SymLink()
O2 int __ustar_SymLink (Inode * Parent, const char * Name, const char * Target, Inode ** Result)
Definition at line 805 of file ustar.cpp.
 {
     return ((vfs::USTAR *)Parent->PrivateData)->SymLink(Parent, Name, Target, Result);
 }
References Name, and Inode::PrivateData.
Referenced by TestAndInitializeUSTAR().
TestAndInitializeUSTAR()
bool TestAndInitializeUSTAR (uintptr_t Address, size_t Size)
Definition at line 834 of file ustar.cpp.
 {
     vfs::USTAR *ustar = new vfs::USTAR();
     if (!ustar->TestArchive(Address))
     {
         delete ustar;
         return false;
     }
     ustar->DeviceID = fs->EarlyReserveDevice();
     ustar->ReadArchive(Address, Size);
     Inode *initrd = nullptr;
     ustar->Lookup(nullptr, "/", &initrd);
     assert(initrd != nullptr);
     FileSystemInfo *fsi = new FileSystemInfo;
     fsi->Name = "ustar";
     fsi->RootName = "/";
     fsi->Flags = I_FLAG_ROOT | I_FLAG_MOUNTPOINT | I_FLAG_CACHE_KEEP;
     fsi->SuperOps.DeleteInode = __ustar_DestroyInode;
     fsi->SuperOps.Destroy = __ustar_Destroy;
     fsi->Ops.Lookup = __ustar_Lookup;
     fsi->Ops.Create = __ustar_Create;
     fsi->Ops.Read = __ustar_Read;
     fsi->Ops.ReadDir = __ustar_Readdir;
     fsi->Ops.SymLink = __ustar_SymLink;
     fsi->Ops.ReadLink = __ustar_ReadLink;
     fsi->Ops.Stat = __ustar_Stat;
     fsi->PrivateData = ustar;
     fs->LateRegisterFileSystem(ustar->DeviceID, fsi, initrd);
     fs->AddRoot(initrd);
     return true;
 }
References __ustar_Create(), __ustar_Destroy(), __ustar_DestroyInode(), __ustar_Lookup(), __ustar_Read(), __ustar_Readdir(), __ustar_ReadLink(), __ustar_Stat(), __ustar_SymLink(), Address, vfs::Virtual::AddRoot(), assert, InodeOperations::Create, SuperBlockOperations::DeleteInode, SuperBlockOperations::Destroy, vfs::USTAR::DeviceID, vfs::Virtual::EarlyReserveDevice(), FileSystemInfo::Flags, fs, I_FLAG_CACHE_KEEP, I_FLAG_MOUNTPOINT, I_FLAG_ROOT, vfs::Virtual::LateRegisterFileSystem(), vfs::USTAR::Lookup(), InodeOperations::Lookup, FileSystemInfo::Name, FileSystemInfo::Ops, FileSystemInfo::PrivateData, InodeOperations::Read, vfs::USTAR::ReadArchive(), InodeOperations::ReadDir, InodeOperations::ReadLink, FileSystemInfo::RootName, Driver::Size, InodeOperations::Stat, FileSystemInfo::SuperOps, InodeOperations::SymLink, and vfs::USTAR::TestArchive().
Referenced by SearchForInitrd().