Fennix: Userspace/apps/base/busybox/coreutils/id.c File Reference
id.c File Reference
#include "libbb.h"
Enumerations
enum {
PRINT_REAL = (1 << 0) , NAME_NOT_NUMBER = (1 << 1) , JUST_USER = (1 << 2) , JUST_GROUP = (1 << 3) ,
JUST_ALL_GROUPS = (1 << 4)
}
Functions
static int print_common (unsigned id, const char *name, const char *prefix)
static int print_group (gid_t id, const char *prefix)
static int print_user (uid_t id, const char *prefix)
static int get_groups (const char *username, gid_t rgid, gid_t *groups, int *n)
int id_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PRINT_REAL
NAME_NOT_NUMBER
JUST_USER
JUST_GROUP
JUST_ALL_GROUPS
Definition at line 71 of file id.c.
      {
     PRINT_REAL      = (1 << 0),
     NAME_NOT_NUMBER = (1 << 1),
     JUST_USER       = (1 << 2),
     JUST_GROUP      = (1 << 3),
     JUST_ALL_GROUPS = (1 << 4),
 #if ENABLE_SELINUX
     JUST_CONTEXT    = (1 << 5),
 #endif
 };
Function Documentation
get_groups()
static int get_groups (const char * username, gid_t rgid, gid_t * groups, int * n) static
Definition at line 120 of file id.c.
 {
     int m;
     if (username) {
         /* If the user is a member of more than
          * *n groups, then -1 is returned. Otherwise >= 0.
          * (and no defined way of detecting errors?!) */
         m = getgrouplist(username, rgid, groups, n);
         /* I guess *n < 0 might indicate error. Anyway,
          * malloc'ing -1 bytes won't be good, so: */
         if (*n < 0)
             return 0;
         return m;
     }
     *n = getgroups(*n, groups);
     if (*n >= 0)
         return *n;
     /* Error */
     if (errno == EINVAL) /* *n is too small? */
         *n = getgroups(0, groups); /* get needed *n */
     /* if *n >= 0, return -1 (got new *n), else return 0 (error): */
     return -(*n >= 0);
 }
References EINVAL, errno, getgrouplist, getgroups(), groups, n, and rgid.
Referenced by id_main().
id_main()
int id_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 147 of file id.c.
 {
     uid_t ruid;
     gid_t rgid;
     uid_t euid;
     gid_t egid;
     unsigned opt;
     int i;
     int status = EXIT_SUCCESS;
     const char *prefix;
     const char *username;
 #if ENABLE_SELINUX
     security_context_t scontext = NULL;
 #endif
     if (ENABLE_GROUPS && (!ENABLE_ID || applet_name[0] == 'g')) {
         /* TODO: coreutils groups prepend "USER : " prefix,
          * and accept many usernames. Example:
          * # groups root root
          * root : root
          * root : root
          */
         opt = option_mask32 = getopt32(argv, "") | JUST_ALL_GROUPS | NAME_NOT_NUMBER;
     } else {
         /* Don't allow -n -r -nr -ug -rug -nug -rnug -uZ -gZ -GZ*/
         /* Don't allow more than one username */
         opt = getopt32(argv, "^"
             "rnugG" IF_SELINUX("Z")
             "\0"
             "?1:u--g:g--u:G--u:u--G:g--G:G--g:r?ugG:n?ugG"
             IF_SELINUX(":u--Z:Z--u:g--Z:Z--g:G--Z:Z--G")
         );
     }
     username = argv[optind];
     if (username) {
         struct passwd *p = xgetpwnam(username);
         euid = ruid = p->pw_uid;
         egid = rgid = p->pw_gid;
     } else {
         egid = getegid();
         rgid = getgid();
         euid = geteuid();
         ruid = getuid();
     }
     /* JUST_ALL_GROUPS ignores -r PRINT_REAL flag even if man page for */
     /* id says: print the real ID instead of the effective ID, with -ugG */
     /* in fact in this case egid is always printed if egid != rgid */
     if (!opt || (opt & JUST_ALL_GROUPS)) {
         gid_t *groups;
         int n;
         if (!opt) {
             /* Default Mode */
             status |= print_user(ruid, "uid=");
             status |= print_group(rgid, " gid=");
             if (euid != ruid)
                 status |= print_user(euid, " euid=");
             if (egid != rgid)
                 status |= print_group(egid, " egid=");
         } else {
             /* JUST_ALL_GROUPS */
             status |= print_group(rgid, NULL);
             if (egid != rgid)
                 status |= print_group(egid, " ");
         }
         /* We are supplying largish buffer, trying
          * to not run get_groups() twice. That might be slow
          * ("user database in remote SQL server" case) */
         groups = xmalloc(64 * sizeof(groups[0]));
         n = 64;
         if (get_groups(username, rgid, groups, &n) < 0) {
             /* Need bigger buffer after all */
             groups = xrealloc(groups, n * sizeof(groups[0]));
             get_groups(username, rgid, groups, &n);
         }
         if (n > 0) {
             /* Print the list */
             prefix = " groups=";
             for (i = 0; i < n; i++) {
                 if (opt && (groups[i] == rgid || groups[i] == egid))
                     continue;
                 status |= print_group(groups[i], opt ? " " : prefix);
                 prefix = ",";
             }
         } else if (n < 0) { /* error in get_groups() */
             if (ENABLE_DESKTOP)
                 bb_simple_error_msg_and_die("can't get groups");
             return EXIT_FAILURE;
         }
         if (ENABLE_FEATURE_CLEAN_UP)
             free(groups);
 #if ENABLE_SELINUX
         if (is_selinux_enabled()) {
             if (getcon(&scontext) == 0)
                 printf(" context=%s", scontext);
         }
 #endif
     } else if (opt & PRINT_REAL) {
         euid = ruid;
         egid = rgid;
     }
     if (opt & JUST_USER)
         status |= print_user(euid, NULL);
     else if (opt & JUST_GROUP)
         status |= print_group(egid, NULL);
 #if ENABLE_SELINUX
     else if (opt & JUST_CONTEXT) {
         selinux_or_die();
         if (username || getcon(&scontext)) {
             bb_error_msg_and_die("can't get process context%s",
                 username ? " for a different user" : "");
         }
         fputs_stdout(scontext);
     }
     /* freecon(NULL) seems to be harmless */
     if (ENABLE_FEATURE_CLEAN_UP)
         freecon(scontext);
 #endif
     bb_putchar('\n');
     fflush_stdout_and_exit(status);
 }
References applet_name, argv, bb_error_msg_and_die(), bb_putchar(), bb_simple_error_msg_and_die(), egid, euid, EXIT_FAILURE, EXIT_SUCCESS, fflush_stdout_and_exit(), fputs_stdout(), free, get_groups(), getegid, geteuid, getgid, getopt32(), getuid, groups, i, JUST_ALL_GROUPS, JUST_GROUP, JUST_USER, n, NAME_NOT_NUMBER, NULL, opt, optind, option_mask32, p, prefix(), print_group(), PRINT_REAL, print_user(), printf, rgid, ruid, selinux_or_die(), status, xgetpwnam(), xmalloc, and xrealloc.
print_common()
static int print_common (unsigned id, const char * name, const char * prefix) static
Definition at line 82 of file id.c.
 {
     if (prefix) {
         printf("%s", prefix);
     }
     if (!(option_mask32 & NAME_NOT_NUMBER) || !name) {
         printf("%u", id);
     }
     if (!option_mask32 || (option_mask32 & NAME_NOT_NUMBER)) {
         if (name) {
             printf(option_mask32 ? "%s" : "(%s)", name);
         } else {
             /* Don't set error status flag in default mode */
             if (option_mask32) {
                 if (ENABLE_DESKTOP)
                     bb_error_msg("unknown ID %u", id);
                 return EXIT_FAILURE;
             }
         }
     }
     return EXIT_SUCCESS;
 }
References bb_error_msg(), EXIT_FAILURE, EXIT_SUCCESS, NAME_NOT_NUMBER, option_mask32, prefix(), and printf.
Referenced by print_group(), and print_user().
print_group()
static int print_group (gid_t id, const char * prefix) static
Definition at line 105 of file id.c.
 {
     return print_common(id, gid2group(id), prefix);
 }
References gid2group(), prefix(), and print_common().
Referenced by id_main().
print_user()
static int print_user (uid_t id, const char * prefix) static
Definition at line 110 of file id.c.
 {
     return print_common(id, uid2uname(id), prefix);
 }
References prefix(), print_common(), and uid2uname().
Referenced by id_main().