Fennix: Userspace/apps/base/busybox/include/grp_.h File Reference
grp_.h File Reference
Macros
#define endgrent bb_internal_endgrent
#define getgrgid bb_internal_getgrgid
#define getgrnam bb_internal_getgrnam
#define getgrouplist bb_internal_getgrouplist
#define initgroups bb_internal_initgroups
Functions
struct group *FAST_FUNC getgrgid (gid_t __gid)
struct group *FAST_FUNC getgrnam (const char *__name)
int FAST_FUNC getgrouplist (const char *__user, gid_t __group, gid_t *__groups, int *__ngroups)
int FAST_FUNC initgroups (const char *__user, gid_t __group)
Macro Definition Documentation
endgrent
void FAST_FUNC endgrent bb_internal_endgrent
Definition at line 33 of file grp_.h.
getgrgid
#define getgrgid bb_internal_getgrgid
Definition at line 34 of file grp_.h.
getgrnam
#define getgrnam bb_internal_getgrnam
Definition at line 35 of file grp_.h.
getgrouplist
#define getgrouplist bb_internal_getgrouplist
Definition at line 36 of file grp_.h.
initgroups
#define initgroups bb_internal_initgroups
Definition at line 37 of file grp_.h.
Function Documentation
getgrgid()
struct group* FAST_FUNC getgrgid (gid_t __gid)
Definition at line 480 of file pwd_grp.c.
 {
     return getXXnam(utoa(id), (1 << 2) + 2);
 }
References getXXnam(), and utoa().
getgrnam()
struct group* FAST_FUNC getgrnam (const char * __name)
Definition at line 472 of file pwd_grp.c.
 {
     return getXXnam(name, (1 << 2) + 0);
 }
References getXXnam().
getgrouplist()
int FAST_FUNC getgrouplist (const char * __user, gid_t __group, gid_t * __groups, int * __ngroups)
Definition at line 559 of file pwd_grp.c.
 {
     int ngroups_old = *ngroups;
     gid_t *group_list = getgrouplist_internal(ngroups, user, gid);
     if (*ngroups <= ngroups_old) {
         ngroups_old = *ngroups;
         memcpy(groups, group_list, ngroups_old * sizeof(groups[0]));
     } else {
         ngroups_old = -1;
     }
     free(group_list);
     return ngroups_old;
 }
References __getgrent_a(), __nscd_query(), bswap_32, buf, calloc, cleanup(), EIO, ENOENT, ENOTDIR, errno, f, fclose(), ferror, fopen(), fread(), free, getgrouplist_internal(), GETINITGR, gr, group::gr_gid, group::gr_mem, groups, i, INITGR_LEN, INITGRFOUND, INITGRNGRPS, mem, memcpy, n, ngroups, size, strcmp, and swap().
initgroups()
int FAST_FUNC initgroups (const char * __user, gid_t __group)
Definition at line 549 of file pwd_grp.c.
 {
     int ngroups;
     gid_t *group_list = getgrouplist_internal(&ngroups, user, gid);
     ngroups = setgroups(ngroups, group_list);
     free(group_list);
     return ngroups;
 }
References count, free, getgrouplist, getgrouplist_internal(), groups, ngroups, and setgroups().