Fennix Kernel: Interrupts Namespace Reference
Interrupts Namespace Reference
Data Structures
struct Event
class Handler
Functions
void Initialize (int Core)
void Enable (int Core)
void InitializeTimer (int Core)
nsa void RemoveAll ()
void AddHandler (void(*Callback)(CPU::TrapFrame *), int InterruptNumber, void *ctx, bool Critical)
void RemoveHandler (void(*Callback)(CPU::TrapFrame *), int InterruptNumber)
void RemoveHandler (void(*Callback)(CPU::TrapFrame *))
void RemoveHandler (int InterruptNumber)
nsa void MainInterruptHandler (void *Data)
Variables
std::list< Event > RegisteredEvents
std::atomic_uint SortEvents = SORT_START / SORT_DIVIDER
constexpr uint32_t SORT_ITR = (SORT_START * 100) / SORT_DIVIDER
Function Documentation
AddHandler()
void Interrupts::AddHandler (void(*)(CPU::TrapFrame *) Callback, int InterruptNumber, void * ctx, bool Critical)
Definition at line 205 of file interrupts_manager.cpp.
     {
         /* Just log a warning if the interrupt is already registered. */
         foreach (auto ev in RegisteredEvents)
         {
             if (ev.IRQ == InterruptNumber &&
                 ev.Callback == Callback)
             {
                 warn("IRQ%d is already registered.",
                      InterruptNumber);
             }
         }
         Event newEvent =
             {InterruptNumber, /* IRQ */
              nullptr,         /* Data */
              false,           /* IsHandler */
              Callback,        /* Callback */
              ctx,             /* Context */
              0,               /* Priority */
              Critical};       /* Critical */
         RegisteredEvents.push_back(newEvent);
         debug("Registered interrupt handler for IRQ%d to %#lx",
               InterruptNumber, Callback);
     }
References Tasking::Critical, ctx, debug, RegisteredEvents, and warn.
Referenced by Driver::RegisterInterruptHandler().
Enable()
void Interrupts::Enable (int Core)
Definition at line 159 of file interrupts_manager.cpp.
     {
 #if defined(a86)
         if (((ACPI::MADT *)PowerManager->GetMADT())->LAPICAddress != nullptr)
         {
             // TODO: This function is called by SMP too. Do not initialize timers that doesn't support multiple cores.
             apic[Core] = new APIC::APIC(Core);
             if (Core == Config.IOAPICInterruptCore) // Redirect IRQs to the specified core.
                 ((APIC::APIC *)apic[Core])->RedirectIRQs(uint8_t(Core));
         }
         else
         {
             error("LAPIC not found");
             // TODO: PIC
         }
 #elif defined(aa64)
         warn("aarch64 is not supported yet");
 #endif
         CPU::Interrupts(CPU::Enable);
     }
References Config, CPU::Enable, error, Power::Power::GetMADT(), CPU::Interrupts(), KernelConfig::IOAPICInterruptCore, PowerManager, and warn.
Referenced by Main(), and StartCPU().
Initialize()
void Interrupts::Initialize (int Core)
Definition at line 115 of file interrupts_manager.cpp.
     {
 #if defined(a64)
         GlobalDescriptorTable::Init(Core);
         InterruptDescriptorTable::Init(Core);
         CPUData *CoreData = GetCPU(Core);
         CoreData->Checksum = CPU_DATA_CHECKSUM;
         CPU::x64::wrmsr(CPU::x64::MSR_GS_BASE, (uint64_t)CoreData);
         CPU::x64::wrmsr(CPU::x64::MSR_SHADOW_GS_BASE, (uint64_t)CoreData);
         CoreData->ID = Core;
         CoreData->IsActive = true;
         CoreData->Stack = (uintptr_t)KernelAllocator.RequestPages(TO_PAGES(STACK_SIZE + 1)) + STACK_SIZE;
         if (CoreData->Checksum != CPU_DATA_CHECKSUM)
         {
             KPrint("CPU %d checksum mismatch! %x != %x",
                    Core, CoreData->Checksum, CPU_DATA_CHECKSUM);
             CPU::Stop();
         }
         debug("Stack for core %d is %#lx (Address: %#lx)",
               Core, CoreData->Stack, CoreData->Stack - STACK_SIZE);
         InitializeSystemCalls();
 #elif defined(a32)
         GlobalDescriptorTable::Init(Core);
         InterruptDescriptorTable::Init(Core);
         CPUData *CoreData = GetCPU(Core);
         CoreData->Checksum = CPU_DATA_CHECKSUM;
         CPU::x32::wrmsr(CPU::x32::MSR_GS_BASE, (uint64_t)CoreData);
         CPU::x32::wrmsr(CPU::x32::MSR_SHADOW_GS_BASE, (uint64_t)CoreData);
         CoreData->ID = Core;
         CoreData->IsActive = true;
         CoreData->Stack = (uintptr_t)KernelAllocator.RequestPages(TO_PAGES(STACK_SIZE + 1)) + STACK_SIZE;
         if (CoreData->Checksum != CPU_DATA_CHECKSUM)
         {
             KPrint("CPU %d checksum mismatch! %x != %x",
                    Core, CoreData->Checksum, CPU_DATA_CHECKSUM);
             CPU::Stop();
         }
         debug("Stack for core %d is %#lx (Address: %#lx)",
               Core, CoreData->Stack, CoreData->Stack - STACK_SIZE);
 #elif defined(aa64)
         warn("aarch64 is not supported yet");
 #endif
     }
References CPUData::Checksum, CPU_DATA_CHECKSUM, debug, GetCPU(), CPUData::ID, GlobalDescriptorTable::Init(), InterruptDescriptorTable::Init(), InitializeSystemCalls(), CPUData::IsActive, KernelAllocator, KPrint(), CPU::x32::MSR_GS_BASE, CPU::x64::MSR_GS_BASE, CPU::x32::MSR_SHADOW_GS_BASE, CPU::x64::MSR_SHADOW_GS_BASE, CPUData::Stack, STACK_SIZE, CPU::Stop(), TO_PAGES, and warn.
Referenced by Main(), and StartCPU().
InitializeTimer()
void Interrupts::InitializeTimer (int Core)
Definition at line 180 of file interrupts_manager.cpp.
     {
         // TODO: This function is called by SMP too. Do not initialize timers that doesn't support multiple cores.
 #if defined(a86)
         if (apic[Core] != nullptr)
             apicTimer[Core] = new APIC::Timer((APIC::APIC *)apic[Core]);
         else
         {
             fixme("apic not found");
         }
 #elif defined(aa64)
         warn("aarch64 is not supported yet");
 #endif
     }
References fixme, and warn.
Referenced by Main(), and StartCPU().
MainInterruptHandler()
nsa void Interrupts::MainInterruptHandler (void * Data)
Definition at line 283 of file interrupts_manager.cpp.
     {
 #if defined(a64)
         CPU::x64::TrapFrame *Frame = (CPU::x64::TrapFrame *)Data;
 #elif defined(a32)
         CPU::x32::TrapFrame *Frame = (CPU::x32::TrapFrame *)Data;
 #elif defined(aa64)
         CPU::aarch64::TrapFrame *Frame = (CPU::aarch64::TrapFrame *)Data;
 #endif
         // debug("IRQ%ld", Frame->InterruptNumber - 32);
         CPUData *CoreData = GetCurrentCPU();
         int Core = 0;
         if (likely(CoreData != nullptr))
             Core = CoreData->ID;
         /* If this is false, we have a big problem. */
         if (unlikely(Frame->InterruptNumber >= CPU::x86::IRQ223 ||
                      Frame->InterruptNumber <= CPU::x86::ISR0))
         {
             error("Interrupt number %d is out of range.",
                   Frame->InterruptNumber);
             assert(!"Interrupt number is out of range.");
         }
         /* Halt core interrupt */
         if (unlikely(Frame->InterruptNumber == CPU::x86::IRQ31))
             CPU::Stop();
         bool InterruptHandled = false;
         foreach (auto &ev in RegisteredEvents)
         {
 #if defined(a86)
             int iEvNum = ev.IRQ + CPU::x86::IRQ0;
 #elif defined(aa64)
             int iEvNum = ev.IRQ;
 #endif
             if (iEvNum == s_cst(int, Frame->InterruptNumber))
             {
                 if (ev.IsHandler)
                 {
                     Handler *hnd = (Handler *)ev.Data;
                     hnd->OnInterruptReceived(Frame);
                 }
                 else
                 {
                     if (ev.Context != nullptr)
                         ev.Callback((CPU::TrapFrame *)ev.Context);
                     else
                         ev.Callback(Frame);
                 }
                 ev.Priority++;
                 InterruptHandled = true;
             }
         }
         if (unlikely(!InterruptHandled))
         {
             error("IRQ%d is unhandled on CPU %d.",
                   Frame->InterruptNumber - 32, Core);
         }
         /* TODO: This should be done when the os is idle */
         if (SortEvents++ > SORT_ITR)
         {
             debug("Sorting events");
             SortEvents = 0;
             RegisteredEvents.sort([](const Event &a, const Event &b)
                                   { return a.Priority < b.Priority; });
 #ifdef DEBUG
             foreach (auto ev in RegisteredEvents)
             {
                 void *func = ev.IsHandler
                                  ? ev.Data
                                  : (void *)ev.Callback;
                 const char *symbol = ev.IsHandler
                                          ? "class"
                                          : KernelSymbolTable->GetSymbol((uintptr_t)func);
                 debug("Event IRQ%d [%#lx %s] has priority %ld",
                       ev.IRQ, func, symbol, ev.Priority);
             }
 #endif
         }
         if (likely(apic[Core]))
         {
             APIC::APIC *this_apic = (APIC::APIC *)apic[Core];
             this_apic->EOI();
             // TODO: Handle PIC too
             return;
         }
         else
             fixme("APIC not found for core %d", Core);
         // TODO: PIC
         assert(!"Interrupt EOI not handled.");
         CPU::Stop();
     }
References assert, Data, debug, APIC::APIC::EOI(), error, fixme, GetCurrentCPU(), SymbolResolver::Symbols::GetSymbol(), CPUData::ID, CPU::x64::TrapFrame::InterruptNumber, CPU::x86::IRQ0, CPU::x86::IRQ223, CPU::x86::IRQ31, CPU::x86::ISR0, KernelSymbolTable, likely, Interrupts::Handler::OnInterruptReceived(), Interrupts::Event::Priority, RegisteredEvents, SORT_ITR, SortEvents, CPU::Stop(), and unlikely.
RemoveAll()
void Interrupts::RemoveAll ()
Definition at line 195 of file interrupts_manager.cpp.
     {
         forItr(itr, RegisteredEvents)
         {
             if (itr->Critical)
                 continue;
             RegisteredEvents.erase(itr);
         }
     }
References RegisteredEvents.
Referenced by HandleException().
RemoveHandler() [1/3]
void Interrupts::RemoveHandler (int InterruptNumber)
Definition at line 266 of file interrupts_manager.cpp.
     {
         forItr(itr, RegisteredEvents)
         {
             if (itr->IRQ == InterruptNumber)
             {
                 debug("Removing handle %d %#lx", itr->IRQ,
                       itr->IsHandler
                           ? itr->Data
                           : (void *)itr->Callback);
                 RegisteredEvents.erase(itr);
             }
         }
         warn("IRQ%d not found.", InterruptNumber);
     }
References debug, RegisteredEvents, and warn.
RemoveHandler() [2/3]
void Interrupts::RemoveHandler (void(*)(CPU::TrapFrame *) Callback)
Definition at line 249 of file interrupts_manager.cpp.
     {
         forItr(itr, RegisteredEvents)
         {
             if (itr->Callback == Callback)
             {
                 debug("Removing handle %d %#lx", itr->IRQ,
                       itr->IsHandler
                           ? itr->Data
                           : (void *)itr->Callback);
                 RegisteredEvents.erase(itr);
             }
         }
         warn("Handle not found.");
     }
References debug, RegisteredEvents, and warn.
RemoveHandler() [3/3]
void Interrupts::RemoveHandler (void(*)(CPU::TrapFrame *) Callback, int InterruptNumber)
Definition at line 233 of file interrupts_manager.cpp.
     {
         forItr(itr, RegisteredEvents)
         {
             if (itr->IRQ == InterruptNumber &&
                 itr->Callback == Callback)
             {
                 RegisteredEvents.erase(itr);
                 debug("Unregistered interrupt handler for IRQ%d to %#lx",
                       InterruptNumber, Callback);
                 return;
             }
         }
         warn("Event %d not found.", InterruptNumber);
     }
References debug, RegisteredEvents, and warn.
Referenced by Driver::OverrideInterruptHandler(), Driver::Manager::UnloadAllDrivers(), Driver::UnregisterAllInterruptHandlers(), and Driver::UnregisterInterruptHandler().
Variable Documentation
RegisteredEvents
std::list<Event> Interrupts::RegisteredEvents
Definition at line 97 of file interrupts_manager.cpp.
Referenced by AddHandler(), Interrupts::Handler::Handler(), MainInterruptHandler(), RemoveAll(), RemoveHandler(), and Interrupts::Handler::~Handler().
SORT_ITR
constexpr uint32_t Interrupts::SORT_ITR = (SORT_START * 100) / SORT_DIVIDER constexpr
Definition at line 107 of file interrupts_manager.cpp.
Referenced by MainInterruptHandler().
SortEvents
std::atomic_uint Interrupts::SortEvents = SORT_START / SORT_DIVIDER
Definition at line 106 of file interrupts_manager.cpp.
Referenced by MainInterruptHandler().