Fennix: Userspace/apps/base/bash/lib/readline/complete.c File Reference
complete.c File Reference
#include <sys/types.h>
#include <fcntl.h>
#include <signal.h>
#include "ansi_stdlib.h"
#include <stdio.h>
#include <errno.h>
#include "posixdir.h"
#include "posixstat.h"
#include "rldefs.h"
#include "rlmbutil.h"
#include "readline.h"
#include "xmalloc.h"
#include "rlprivate.h"
#include "colors.h"
Macros
#define READLINE_LIBRARY
#define LSTAT stat
#define HIDDEN_FILE(fname) ((fname)[0] == '.')
#define X_OK 1
#define ELLIPSIS_LEN 3
Typedefs
typedef int QSFUNC()
Functions
static int stat_char (char *)
static int colored_stat_start (const char *)
static void colored_stat_end (void)
static int colored_prefix_start (void)
static void colored_prefix_end (void)
static int path_isdir (const char *)
static char * rl_quote_filename (char *, int, char *)
static void _rl_complete_sigcleanup (int, void *)
static void set_completion_defaults (int)
static int get_y_or_n (int)
static int _rl_internal_pager (int)
static char * printable_part (char *)
static int fnwidth (const char *)
static int fnprint (const char *, int, const char *)
static int print_filename (char *, char *, int)
static char ** gen_completion_matches (char *, int, int, rl_compentry_func_t *, int, int)
static char ** remove_duplicate_matches (char **)
static void insert_match (char *, int, int, char *)
static int append_to_match (char *, int, int, int)
static void insert_all_matches (char **, int, char *)
static int complete_fncmp (const char *, int, const char *, int)
static void display_matches (char **)
static int compute_lcd_of_matches (char **, int, const char *)
static int postprocess_matches (char ***, int)
static int compare_match (char *, const char *)
static int complete_get_screenwidth (void)
static char * make_quoted_replacement (char *, int, char *)
int rl_complete (int ignore, int invoking_key)
int rl_possible_completions (int ignore, int invoking_key)
int rl_insert_completions (int ignore, int invoking_key)
int rl_completion_mode (rl_command_func_t *cfunc)
void _rl_reset_completion_state (void)
char _rl_find_completion_word (int *fp, int *dp)
void rl_display_match_list (char **matches, int len, int max)
void _rl_free_match_list (char **matches)
int rl_complete_internal (int what_to_do)
char ** rl_completion_matches (const char *text, rl_compentry_func_t *entry_function)
char * rl_username_completion_function (const char *text, int state)
char * rl_filename_completion_function (const char *text, int state)
int rl_old_menu_complete (int count, int invoking_key)
int rl_menu_complete (int count, int ignore)
int rl_backward_menu_complete (int count, int key)
Variables
int errno
rl_compdisp_func_t * rl_completion_display_matches_hook = (rl_compdisp_func_t *)NULL
int _rl_complete_show_all = 0
int _rl_complete_show_unmodified = 0
int _rl_complete_mark_directories = 1
int _rl_complete_mark_symlink_dirs = 0
int _rl_print_completions_horizontally
int _rl_completion_case_fold = 0
int _rl_completion_case_map = 0
int _rl_match_hidden_files = 1
int _rl_completion_prefix_display_length = 0
int _rl_completion_columns = -1
int _rl_colored_stats = 0
int _rl_colored_completion_prefix = 0
int _rl_skip_completed_text = 0
int _rl_menu_complete_prefix_first = 0
int rl_visible_stats = 0
rl_icppfunc_t * rl_directory_completion_hook = (rl_icppfunc_t *)NULL
rl_icppfunc_t * rl_directory_rewrite_hook = (rl_icppfunc_t *)NULL
rl_icppfunc_t * rl_filename_stat_hook = (rl_icppfunc_t *)NULL
rl_dequote_func_t * rl_filename_rewrite_hook = (rl_dequote_func_t *)NULL
int rl_complete_with_tilde_expansion = 0
rl_compentry_func_t * rl_completion_entry_function = (rl_compentry_func_t *)NULL
rl_compentry_func_t * rl_menu_completion_entry_function = (rl_compentry_func_t *)NULL
rl_completion_func_t * rl_attempted_completion_function = (rl_completion_func_t *)NULL
int rl_attempted_completion_over = 0
int rl_completion_type = 0
int rl_completion_query_items = 100
int _rl_page_completions = 1
const char * rl_basic_word_break_characters = " \t\n\"\\'`@$><=;|&{("
const char * rl_basic_quote_characters = "\"'"
const char * rl_completer_word_break_characters = 0
rl_cpvfunc_t * rl_completion_word_break_hook = (rl_cpvfunc_t *)NULL
const char * rl_completer_quote_characters = (const char *)NULL
const char * rl_filename_quote_characters = (const char *)NULL
const char * rl_special_prefixes = (const char *)NULL
int rl_ignore_completion_duplicates = 1
int rl_filename_completion_desired = 0
int rl_filename_quoting_desired = 1
rl_compignore_func_t * rl_ignore_some_completions_function = (rl_compignore_func_t *)NULL
rl_quote_func_t * rl_filename_quoting_function = rl_quote_filename
rl_dequote_func_t * rl_filename_dequoting_function = (rl_dequote_func_t *)NULL
rl_linebuf_func_t * rl_char_is_quoted_p = (rl_linebuf_func_t *)NULL
int rl_completion_suppress_append = 0
int rl_completion_append_character = ' '
int rl_completion_suppress_quote = 0
int rl_completion_quote_character
int rl_completion_found_quote
int rl_completion_mark_symlink_dirs
int rl_inhibit_completion
int rl_completion_invoking_key
int rl_sort_completion_matches = 1
static int completion_changed_buffer
static int last_completion_failed = 0
static int completion_y_or_n
static int _rl_complete_display_matches_interrupt = 0
Macro Definition Documentation
ELLIPSIS_LEN
#define ELLIPSIS_LEN 3
Definition at line 802 of file complete.c.
HIDDEN_FILE
#define HIDDEN_FILE (fname) ((fname)[0] == '.')
Definition at line 93 of file complete.c.
LSTAT
#define LSTAT stat
Definition at line 89 of file complete.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file complete.c.
X_OK
#define X_OK 1
Definition at line 112 of file complete.c.
Typedef Documentation
QSFUNC
typedef int QSFUNC()
Definition at line 83 of file complete.c.
Function Documentation
_rl_complete_sigcleanup()
static void _rl_complete_sigcleanup (int sig, void * ptr) static
Definition at line 502 of file complete.c.
 {
   if (sig == SIGINT)    /* XXX - for now */
     {
       _rl_free_match_list ((char **)ptr);
       _rl_complete_display_matches_interrupt = 1;
     }
 }
References _rl_complete_display_matches_interrupt, _rl_free_match_list(), and SIGINT.
Referenced by rl_complete_internal().
_rl_find_completion_word()
char _rl_find_completion_word (int * fp, int * dp)
Definition at line 1079 of file complete.c.
 {
   int scan, end, found_quote, delimiter, pass_next, isbrk;
   char quote_char;
   const char *brkchars;
   end = rl_point;
   found_quote = delimiter = 0;
   quote_char = '\0';
   brkchars = 0;
   if (rl_completion_word_break_hook)
     brkchars = (*rl_completion_word_break_hook) ();
   if (brkchars == 0)
     brkchars = rl_completer_word_break_characters;
   if (rl_completer_quote_characters)
     {
       /* We have a list of characters which can be used in pairs to
      quote substrings for the completer.  Try to find the start
      of an unclosed quoted substring. */
       /* FOUND_QUOTE is set so we know what kind of quotes we found. */
       for (scan = pass_next = 0; scan < end; scan = MB_NEXTCHAR (rl_line_buffer, scan, 1, MB_FIND_ANY))
     {
       if (pass_next)
         {
           pass_next = 0;
           continue;
         }
       /* Shell-like semantics for single quotes -- don't allow backslash
          to quote anything in single quotes, especially not the closing
          quote.  If you don't like this, take out the check on the value
          of quote_char. */
       if (quote_char != '\'' && rl_line_buffer[scan] == '\\')
         {
           pass_next = 1;
           found_quote |= RL_QF_BACKSLASH;
           continue;
         }
       if (quote_char != '\0')
         {
           /* Ignore everything until the matching close quote char. */
           if (rl_line_buffer[scan] == quote_char)
         {
           /* Found matching close.  Abandon this substring. */
           quote_char = '\0';
           rl_point = end;
         }
         }
       else if (strchr (rl_completer_quote_characters, rl_line_buffer[scan]))
         {
           /* Found start of a quoted substring. */
           quote_char = rl_line_buffer[scan];
           rl_point = scan + 1;
           /* Shell-like quoting conventions. */
           if (quote_char == '\'')
         found_quote |= RL_QF_SINGLE_QUOTE;
           else if (quote_char == '"')
         found_quote |= RL_QF_DOUBLE_QUOTE;
           else
         found_quote |= RL_QF_OTHER_QUOTE;
         }
     }
     }
   if (rl_point == end && quote_char == '\0')
     {
       /* We didn't find an unclosed quoted substring upon which to do
          completion, so use the word break characters to find the
          substring on which to complete. */
       while (rl_point = MB_PREVCHAR (rl_line_buffer, rl_point, MB_FIND_ANY))
     {
       scan = rl_line_buffer[rl_point];
       if (strchr (brkchars, scan) == 0)
         continue;
       /* Call the application-specific function to tell us whether
          this word break character is quoted and should be skipped. */
       if (rl_char_is_quoted_p && found_quote &&
           (*rl_char_is_quoted_p) (rl_line_buffer, rl_point))
         continue;
       /* Convoluted code, but it avoids an n^2 algorithm with calls
          to char_is_quoted. */
       break;
     }
     }
   /* If we are at an unquoted word break, then advance past it. */
   scan = rl_line_buffer[rl_point];
   /* If there is an application-specific function to say whether or not
      a character is quoted and we found a quote character, let that
      function decide whether or not a character is a word break, even
      if it is found in rl_completer_word_break_characters.  Don't bother
      if we're at the end of the line, though. */
   if (scan)
     {
       if (rl_char_is_quoted_p)
     isbrk = (found_quote == 0 ||
         (*rl_char_is_quoted_p) (rl_line_buffer, rl_point) == 0) &&
         strchr (brkchars, scan) != 0;
       else
     isbrk = strchr (brkchars, scan) != 0;
       if (isbrk)
     {
       /* If the character that caused the word break was a quoting
          character, then remember it as the delimiter. */
       if (rl_basic_quote_characters &&
           strchr (rl_basic_quote_characters, scan) &&
           (end - rl_point) > 1)
         delimiter = scan;
       /* If the character isn't needed to determine something special
          about what kind of completion to perform, then advance past it. */
       if (rl_special_prefixes == 0 || strchr (rl_special_prefixes, scan) == 0)
         rl_point++;
     }
     }
   if (fp)
     *fp = found_quote;
   if (dp)
     *dp = delimiter;
   return (quote_char);
 }
References end, MB_FIND_ANY, MB_NEXTCHAR, MB_PREVCHAR, rl_basic_quote_characters, rl_char_is_quoted_p, rl_completer_quote_characters, rl_completer_word_break_characters, rl_completion_word_break_hook, rl_line_buffer, rl_point, RL_QF_BACKSLASH, RL_QF_DOUBLE_QUOTE, RL_QF_OTHER_QUOTE, RL_QF_SINGLE_QUOTE, rl_special_prefixes, and strchr().
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
_rl_free_match_list()
void _rl_free_match_list (char ** matches)
Definition at line 1958 of file complete.c.
 {
   register int i;
   if (matches == 0)
     return;
   for (i = 0; matches[i]; i++)
     xfree (matches[i]);
   xfree (matches);
 }
References i, and xfree.
Referenced by _rl_complete_sigcleanup(), gen_completion_matches(), rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
_rl_internal_pager()
static int _rl_internal_pager (int lines) static
Definition at line 565 of file complete.c.
 {
   int i;
   fprintf (rl_outstream, "--More--");
   fflush (rl_outstream);
   i = get_y_or_n (1);
   _rl_erase_entire_line ();
   if (i == 0)
     return -1;
   else if (i == 2)
     return (lines - 1);
   else
     return 0;
 }
References _rl_erase_entire_line(), fflush(), fprintf(), get_y_or_n(), i, lines, and rl_outstream.
Referenced by rl_display_match_list().
_rl_reset_completion_state()
void _rl_reset_completion_state (void)
Definition at line 495 of file complete.c.
 {
   rl_completion_found_quote = 0;
   rl_completion_quote_character = 0;
 }
References rl_completion_found_quote, and rl_completion_quote_character.
Referenced by _rl_handle_signal(), and rl_complete_internal().
append_to_match()
static int append_to_match (char * text, int delimiter, int quote_char, int nontrivial_match) static
Definition at line 1855 of file complete.c.
 {
   char temp_string[4], *filename, *fn;
   int temp_string_index, s;
   struct stat finfo;
   temp_string_index = 0;
   if (quote_char && rl_point && rl_completion_suppress_quote == 0 &&
       rl_line_buffer[rl_point - 1] != quote_char)
     temp_string[temp_string_index++] = quote_char;
   if (delimiter)
     temp_string[temp_string_index++] = delimiter;
   else if (rl_completion_suppress_append == 0 && rl_completion_append_character)
     temp_string[temp_string_index++] = rl_completion_append_character;
   temp_string[temp_string_index++] = '\0';
   if (rl_filename_completion_desired)
     {
       filename = tilde_expand (text);
       if (rl_filename_stat_hook)
         {
           fn = savestring (filename);
       (*rl_filename_stat_hook) (&fn);
       xfree (filename);
       filename = fn;
         }
       s = (nontrivial_match && rl_completion_mark_symlink_dirs == 0)
         ? LSTAT (filename, &finfo)
         : stat (filename, &finfo);
       if (s == 0 && S_ISDIR (finfo.st_mode))
     {
       if (_rl_complete_mark_directories /* && rl_completion_suppress_append == 0 */)
         {
           /* This is clumsy.  Avoid putting in a double slash if point
          is at the end of the line and the previous character is a
          slash. */
           if (rl_point && rl_line_buffer[rl_point] == '\0' && rl_line_buffer[rl_point - 1] == '/')
         ;
           else if (rl_line_buffer[rl_point] != '/')
         rl_insert_text ("/");
         }
     }
 #ifdef S_ISLNK
       /* Don't add anything if the filename is a symlink and resolves to a
      directory. */
       else if (s == 0 && S_ISLNK (finfo.st_mode) && path_isdir (filename))
     ;
 #endif
       else
     {
       if (rl_point == rl_end && temp_string_index)
         rl_insert_text (temp_string);
     }
       xfree (filename);
     }
   else
     {
       if (rl_point == rl_end && temp_string_index)
     rl_insert_text (temp_string);
     }
   return (temp_string_index);
 }
References _rl_complete_mark_directories, filename, LSTAT, path_isdir(), rl_completion_append_character, rl_completion_mark_symlink_dirs, rl_completion_suppress_append, rl_completion_suppress_quote, rl_end, rl_filename_completion_desired, rl_filename_stat_hook, rl_insert_text(), rl_line_buffer, rl_point, s, S_ISDIR, S_ISLNK, savestring(), stat::st_mode, stat(), text, tilde_expand(), and xfree.
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
colored_prefix_end()
static void colored_prefix_end (void) static
Definition at line 704 of file complete.c.
 {
   colored_stat_end ();      /* for now */
 }
References colored_stat_end().
Referenced by fnprint().
colored_prefix_start()
static int colored_prefix_start (void) static
Definition at line 697 of file complete.c.
 {
   _rl_set_normal_color ();
   return (_rl_print_prefix_color ());
 }
References _rl_print_prefix_color(), and _rl_set_normal_color().
Referenced by fnprint().
colored_stat_end()
static void colored_stat_end (void) static
Definition at line 690 of file complete.c.
 {
   _rl_prep_non_filename_text ();
   _rl_put_indicator (&_rl_color_indicator[C_CLR_TO_EOL]);
 }
References _rl_color_indicator, _rl_prep_non_filename_text(), _rl_put_indicator(), and C_CLR_TO_EOL.
Referenced by colored_prefix_end(), and fnprint().
colored_stat_start()
static int colored_stat_start (const char * filename) static
Definition at line 683 of file complete.c.
 {
   _rl_set_normal_color ();
   return (_rl_print_color_indicator (filename));
 }
References _rl_print_color_indicator(), _rl_set_normal_color(), and filename.
Referenced by fnprint().
compare_match()
static int compare_match (char * text, const char * match) static
Definition at line 1974 of file complete.c.
 {
   char *temp;
   int r;
   if (rl_filename_completion_desired && rl_filename_quoting_desired &&
       rl_completion_found_quote && rl_filename_dequoting_function)
     {
       temp = (*rl_filename_dequoting_function) (text, rl_completion_quote_character);
       r = strcmp (temp, match);
       xfree (temp);
       return r;
     }
   return (strcmp (text, match));
 }
References rl_completion_found_quote, rl_completion_quote_character, rl_filename_completion_desired, rl_filename_dequoting_function, rl_filename_quoting_desired, strcmp, text, and xfree.
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
complete_fncmp()
static int complete_fncmp (const char * convfn, int convlen, const char * filename, int filename_len) static
Definition at line 2328 of file complete.c.
 {
   register char *s1, *s2;
   int d, len;
 #if defined (HANDLE_MULTIBYTE)
   size_t v1, v2;
   mbstate_t ps1, ps2;
   WCHAR_T wc1, wc2;
 #endif
 #if defined (HANDLE_MULTIBYTE)
   memset (&ps1, 0, sizeof (mbstate_t));
   memset (&ps2, 0, sizeof (mbstate_t));
 #endif
   if (filename_len == 0)
     return 1;
   if (convlen < filename_len)
     return 0;
   len = filename_len;
   s1 = (char *)convfn;
   s2 = (char *)filename;
   /* Otherwise, if these match up to the length of filename, then
      it is a match. */
   if (_rl_completion_case_fold && _rl_completion_case_map)
     {
       /* Case-insensitive comparison treating _ and - as equivalent */
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       do
         {
           v1 = MBRTOWC (&wc1, s1, convlen, &ps1);
           v2 = MBRTOWC (&wc2, s2, filename_len, &ps2);
           if (v1 == 0 && v2 == 0)
         return 1;
           else if (MB_INVALIDCH (v1) || MB_INVALIDCH (v2))
         {
           if (*s1 != *s2)       /* do byte comparison */
             return 0;
           else if ((*s1 == '-' || *s1 == '_') && (*s2 == '-' || *s2 == '_'))
             return 0;
           s1++; s2++; len--;
           continue;
         }
           wc1 = towlower (wc1);
           wc2 = towlower (wc2);
           s1 += v1;
           s2 += v1;
           len -= v1;
           if ((wc1 == L'-' || wc1 == L'_') && (wc2 == L'-' || wc2 == L'_'))
             continue;
           if (wc1 != wc2)
         return 0;
         }
       while (len != 0);
     }
       else
 #endif
     {
     do
       {
         d = _rl_to_lower (*s1) - _rl_to_lower (*s2);
         /* *s1 == [-_] && *s2 == [-_] */
         if ((*s1 == '-' || *s1 == '_') && (*s2 == '-' || *s2 == '_'))
           d = 0;
         if (d != 0)
           return 0;
         s1++; s2++; /* already checked convlen >= filename_len */
       }
     while (--len != 0);
     }
       return 1;
     }
   else if (_rl_completion_case_fold)
     {
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       do
         {
           v1 = MBRTOWC (&wc1, s1, convlen, &ps1);
           v2 = MBRTOWC (&wc2, s2, filename_len, &ps2);
           if (v1 == 0 && v2 == 0)
         return 1;
           else if (MB_INVALIDCH (v1) || MB_INVALIDCH (v2))
         {
           if (*s1 != *s2)       /* do byte comparison */
             return 0;
           s1++; s2++; len--;
           continue;
         }
           wc1 = towlower (wc1);
           wc2 = towlower (wc2);
           if (wc1 != wc2)
         return 0;
           s1 += v1;
           s2 += v1;
           len -= v1;
         }
       while (len != 0);
       return 1;
     }
       else
 #endif
       if ((_rl_to_lower (convfn[0]) == _rl_to_lower (filename[0])) &&
       (convlen >= filename_len) &&
       (_rl_strnicmp (filename, convfn, filename_len) == 0))
     return 1;
     }
   else
     {
       if ((convfn[0] == filename[0]) &&
       (convlen >= filename_len) &&
       (strncmp (filename, convfn, filename_len) == 0))
     return 1;
     }
   return 0;
 }
References _rl_completion_case_fold, _rl_completion_case_map, _rl_strnicmp(), _rl_to_lower(), filename, L, len, MB_CUR_MAX, MB_INVALIDCH, MBRTOWC, memset, ps2, rl_byte_oriented, s1, s2, strncmp(), towlower(), v1, v2, and WCHAR_T.
Referenced by rl_filename_completion_function().
complete_get_screenwidth()
static int complete_get_screenwidth (void) static
Definition at line 1510 of file complete.c.
 {
   int cols;
   char *envcols;
   cols = _rl_completion_columns;
   if (cols >= 0 && cols <= _rl_screenwidth)
     return cols;
   envcols = getenv ("COLUMNS");
   if (envcols && *envcols)
     cols = atoi (envcols);
   if (cols >= 0 && cols <= _rl_screenwidth)
     return cols;
   return _rl_screenwidth;
 }
References _rl_completion_columns, _rl_screenwidth, atoi(), cols, and getenv.
Referenced by rl_display_match_list().
compute_lcd_of_matches()
static int compute_lcd_of_matches (char ** match_list, int matches, const char * text) static
Definition at line 1316 of file complete.c.
 {
   register int i, c1, c2, si;
   int low;      /* Count of max-matched characters. */
   int lx;
   char *dtext;      /* dequoted TEXT, if needed */
 #if defined (HANDLE_MULTIBYTE)
   int v;
   size_t v1, v2;
   mbstate_t ps1, ps2;
   WCHAR_T wc1, wc2;
 #endif
   /* If only one match, just use that.  Otherwise, compare each
      member of the list with the next, finding out where they
      stop matching. */
   if (matches == 1)
     {
       match_list[0] = match_list[1];
       match_list[1] = (char *)NULL;
       return 1;
     }
   for (i = 1, low = 100000; i < matches; i++)
     {
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       memset (&ps1, 0, sizeof (mbstate_t));
       memset (&ps2, 0, sizeof (mbstate_t));
     }
 #endif
       for (si = 0; (c1 = match_list[i][si]) && (c2 = match_list[i + 1][si]); si++)
     {
         if (_rl_completion_case_fold)
           {
             c1 = _rl_to_lower (c1);
             c2 = _rl_to_lower (c2);
           }
 #if defined (HANDLE_MULTIBYTE)
         if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
           {
         v1 = MBRTOWC (&wc1, match_list[i]+si, strlen (match_list[i]+si), &ps1);
         v2 = MBRTOWC (&wc2, match_list[i+1]+si, strlen (match_list[i+1]+si), &ps2);
         if (MB_INVALIDCH (v1) || MB_INVALIDCH (v2))
           {
             if (c1 != c2)   /* do byte comparison */
               break;
             continue;
           }
         if (_rl_completion_case_fold)
           {
             wc1 = towlower (wc1);
             wc2 = towlower (wc2);
           }
         if (wc1 != wc2)
           break;
         else if (v1 > 1)
           si += v1 - 1;
           }
         else
 #endif
         if (c1 != c2)
           break;
     }
       if (low > si)
     low = si;
     }
   /* If there were multiple matches, but none matched up to even the
      first character, and the user typed something, use that as the
      value of matches[0]. */
   if (low == 0 && text && *text)
     {
       match_list[0] = (char *)xmalloc (strlen (text) + 1);
       strcpy (match_list[0], text);
     }
   else
     {
       match_list[0] = (char *)xmalloc (low + 1);
       /* XXX - this might need changes in the presence of multibyte chars */
       /* If we are ignoring case, try to preserve the case of the string
      the user typed in the face of multiple matches differing in case. */
       if (_rl_completion_case_fold)
     {
       /* We're making an assumption here:
         IF we're completing filenames AND
            the application has defined a filename dequoting function AND
            we found a quote character AND
            the application has requested filename quoting
         THEN
            we assume that TEXT was dequoted before checking against
            the file system and needs to be dequoted here before we
            check against the list of matches
         FI */
       dtext = (char *)NULL;
       if (rl_filename_completion_desired &&
           rl_filename_dequoting_function &&
           rl_completion_found_quote &&
           rl_filename_quoting_desired)
         {
           dtext = (*rl_filename_dequoting_function) ((char *)text, rl_completion_quote_character);
           text = dtext;
         }
       /* sort the list to get consistent answers. */
       if (rl_sort_completion_matches)
         qsort (match_list+1, matches, sizeof(char *), (QSFUNC *)_rl_qsort_string_compare);
       si = strlen (text);
       lx = (si <= low) ? si : low;  /* check shorter of text and matches */
       /* Try to preserve the case of what the user typed in the presence of
          multiple matches: check each match for something that matches
          what the user typed taking case into account; use it up to common
          length of matches if one is found.  If not, just use first match. */
       for (i = 1; i <= matches; i++)
         if (strncmp (match_list[i], text, lx) == 0)
           {
         strncpy (match_list[0], match_list[i], low);
         break;
           }
       /* no casematch, use first entry */
       if (i > matches)
         strncpy (match_list[0], match_list[1], low);
       FREE (dtext);
     }
       else
         strncpy (match_list[0], match_list[1], low);
       match_list[0][low] = '\0';
     }
   return matches;
 }
References _rl_completion_case_fold, _rl_qsort_string_compare(), _rl_to_lower(), FREE, i, MB_CUR_MAX, MB_INVALIDCH, MBRTOWC, memset, NULL, ps2, qsort(), rl_byte_oriented, rl_completion_found_quote, rl_completion_quote_character, rl_filename_completion_desired, rl_filename_dequoting_function, rl_filename_quoting_desired, rl_sort_completion_matches, strcpy, strlen(), strncmp(), strncpy(), text, towlower(), v1, v2, WCHAR_T, and xmalloc.
Referenced by postprocess_matches(), and rl_completion_matches().
display_matches()
static void display_matches (char ** matches) static
Definition at line 1688 of file complete.c.
 {
   int len, max, i;
   char *temp;
   /* Move to the last visible line of a possibly-multiple-line command. */
   _rl_move_vert (_rl_vis_botlin);
   /* Handle simple case first.  What if there is only one answer? */
   if (matches[1] == 0)
     {
       temp = printable_part (matches[0]);
       rl_crlf ();
       print_filename (temp, matches[0], 0);
       rl_crlf ();
       rl_forced_update_display ();
       rl_display_fixed = 1;
       return;
     }
   /* There is more than one answer.  Find out how many there are,
      and find the maximum printed length of a single entry. */
   for (max = 0, i = 1; matches[i]; i++)
     {
       temp = printable_part (matches[i]);
       len = fnwidth (temp);
       if (len > max)
     max = len;
     }
   len = i - 1;
   /* If the caller has defined a display hook, then call that now. */
   if (rl_completion_display_matches_hook)
     {
       (*rl_completion_display_matches_hook) (matches, len, max);
       return;
     }
   /* If there are many items, then ask the user if she really wants to
      see them all. */
   if (rl_completion_query_items > 0 && len >= rl_completion_query_items)
     {
       rl_crlf ();
       fprintf (rl_outstream, "Display all %d possibilities? (y or n)", len);
       fflush (rl_outstream);
       if ((completion_y_or_n = get_y_or_n (0)) == 0)
     {
       rl_crlf ();
       rl_forced_update_display ();
       rl_display_fixed = 1;
       return;
     }
     }
   rl_display_match_list (matches, len, max);
   rl_forced_update_display ();
   rl_display_fixed = 1;
 }
References _rl_move_vert(), _rl_vis_botlin, completion_y_or_n, fflush(), fnwidth(), fprintf(), get_y_or_n(), i, len, max, print_filename(), printable_part(), rl_completion_display_matches_hook, rl_completion_query_items, rl_crlf(), rl_display_fixed, rl_display_match_list(), rl_forced_update_display(), and rl_outstream.
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
fnprint()
static int fnprint (const char * to_print, int prefix_bytes, const char * real_pathname) static
Definition at line 805 of file complete.c.
 {
   int printed_len, w;
   const char *s;
   int common_prefix_len, print_len;
 #if defined (HANDLE_MULTIBYTE)
   mbstate_t ps;
   const char *end;
   size_t tlen;
   int width;
   WCHAR_T wc;
   print_len = strlen (to_print);
   end = to_print + print_len + 1;
   memset (&ps, 0, sizeof (mbstate_t));
 #else
   print_len = strlen (to_print);
 #endif
   printed_len = common_prefix_len = 0;
   /* Don't print only the ellipsis if the common prefix is one of the
      possible completions.  Only cut off prefix_bytes if we're going to be
      printing the ellipsis, which takes precedence over coloring the
      completion prefix (see print_filename() below). */
   if (_rl_completion_prefix_display_length > 0 && prefix_bytes >= print_len)
     prefix_bytes = 0;
 #if defined (COLOR_SUPPORT)
   if (_rl_colored_stats && (prefix_bytes == 0 || _rl_colored_completion_prefix <= 0))
     colored_stat_start (real_pathname);
 #endif
   if (prefix_bytes && _rl_completion_prefix_display_length > 0 &&
       prefix_bytes > _rl_completion_prefix_display_length)
     {
       char ellipsis;
       ellipsis = (to_print[prefix_bytes] == '.') ? '_' : '.';
       for (w = 0; w < ELLIPSIS_LEN; w++)
     putc (ellipsis, rl_outstream);
       printed_len = ELLIPSIS_LEN;
     }
 #if defined (COLOR_SUPPORT)
   else if (prefix_bytes && _rl_colored_completion_prefix > 0)
     {
       common_prefix_len = prefix_bytes;
       prefix_bytes = 0;
       /* XXX - print color indicator start here */
       colored_prefix_start ();
     }
 #endif
   s = to_print + prefix_bytes;
   while (*s)
     {
       if (CTRL_CHAR (*s))
         {
           putc ('^', rl_outstream);
           putc (UNCTRL (*s), rl_outstream);
           printed_len += 2;
           s++;
 #if defined (HANDLE_MULTIBYTE)
       memset (&ps, 0, sizeof (mbstate_t));
 #endif
         }
       else if (*s == RUBOUT)
     {
       putc ('^', rl_outstream);
       putc ('?', rl_outstream);
       printed_len += 2;
       s++;
 #if defined (HANDLE_MULTIBYTE)
       memset (&ps, 0, sizeof (mbstate_t));
 #endif
     }
       else
     {
 #if defined (HANDLE_MULTIBYTE)
       tlen = MBRTOWC (&wc, s, end - s, &ps);
       if (MB_INVALIDCH (tlen))
         {
           tlen = 1;
           width = 1;
           memset (&ps, 0, sizeof (mbstate_t));
         }
       else if (MB_NULLWCH (tlen))
         break;
       else
         {
           w = WCWIDTH (wc);
           width = (w >= 0) ? w : 1;
         }
       fwrite (s, 1, tlen, rl_outstream);
       s += tlen;
       printed_len += width;
 #else
       putc (*s, rl_outstream);
       s++;
       printed_len++;
 #endif
     }
       if (common_prefix_len > 0 && (s - to_print) >= common_prefix_len)
     {
 #if defined (COLOR_SUPPORT)
       /* printed bytes = s - to_print */
       /* printed bytes should never be > but check for paranoia's sake */
       colored_prefix_end ();
       if (_rl_colored_stats)
         colored_stat_start (real_pathname);     /* XXX - experiment */
 #endif
       common_prefix_len = 0;
     }
     }
 #if defined (COLOR_SUPPORT)
   /* XXX - unconditional for now */
   if (_rl_colored_stats)
     colored_stat_end ();
 #endif
   return printed_len;
 }
References _rl_colored_completion_prefix, _rl_colored_stats, _rl_completion_prefix_display_length, colored_prefix_end(), colored_prefix_start(), colored_stat_end(), colored_stat_start(), CTRL_CHAR, ELLIPSIS_LEN, end, fwrite(), MB_INVALIDCH, MB_NULLWCH, MBRTOWC, memset, putc, rl_outstream, RUBOUT, s, strlen(), UNCTRL, w, WCHAR_T, and width.
Referenced by print_filename().
fnwidth()
static int fnwidth (const char * string) static
Definition at line 753 of file complete.c.
 {
   int width, pos;
 #if defined (HANDLE_MULTIBYTE)
   mbstate_t ps;
   int left, w;
   size_t clen;
   WCHAR_T wc;
   left = strlen (string) + 1;
   memset (&ps, 0, sizeof (mbstate_t));
 #endif
   width = pos = 0;
   while (string[pos])
     {
       if (CTRL_CHAR (string[pos]) || string[pos] == RUBOUT)
     {
       width += 2;
       pos++;
     }
       else
     {
 #if defined (HANDLE_MULTIBYTE)
       clen = MBRTOWC (&wc, string + pos, left - pos, &ps);
       if (MB_INVALIDCH (clen))
         {
           width++;
           pos++;
           memset (&ps, 0, sizeof (mbstate_t));
         }
       else if (MB_NULLWCH (clen))
         break;
       else
         {
           pos += clen;
           w = WCWIDTH (wc);
           width += (w >= 0) ? w : 1;
         }
 #else
       width++;
       pos++;
 #endif
     }
     }
   return width;
 }
References CTRL_CHAR, MB_INVALIDCH, MB_NULLWCH, MBRTOWC, memset, pos, RUBOUT, strlen(), w, WCHAR_T, and width.
Referenced by display_matches(), and rl_display_match_list().
gen_completion_matches()
static char ** gen_completion_matches (char * text, int start, int end, rl_compentry_func_t * our_func, int found_quote, int quote_char) static
Definition at line 1212 of file complete.c.
 {
   char **matches;
   rl_completion_found_quote = found_quote;
   rl_completion_quote_character = quote_char;
   /* If the user wants to TRY to complete, but then wants to give
      up and use the default completion function, they set the
      variable rl_attempted_completion_function. */
   if (rl_attempted_completion_function)
     {
       matches = (*rl_attempted_completion_function) (text, start, end);
       if (RL_SIG_RECEIVED())
     {
       _rl_free_match_list (matches);
       matches = 0;
       RL_CHECK_SIGNALS ();
     }
       if (matches || rl_attempted_completion_over)
     {
       rl_attempted_completion_over = 0;
       return (matches);
     }
     }
   /* XXX -- filename dequoting moved into rl_filename_completion_function */
   /* rl_completion_matches will check for signals as well to avoid a long
      delay while reading a directory. */
   matches = rl_completion_matches (text, our_func);
   if (RL_SIG_RECEIVED())
     {
       _rl_free_match_list (matches);
       matches = 0;
       RL_CHECK_SIGNALS ();
     }
   return matches;
 }
References _rl_free_match_list(), end, rl_attempted_completion_function, rl_attempted_completion_over, RL_CHECK_SIGNALS, rl_completion_found_quote, rl_completion_matches(), rl_completion_quote_character, RL_SIG_RECEIVED, start, and text.
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
get_y_or_n()
static int get_y_or_n (int for_pager) static
Definition at line 532 of file complete.c.
 {
   int c;
   /* For now, disable pager in callback mode, until we later convert to state
      driven functions.  Have to wait until next major version to add new
      state definition, since it will change value of RL_STATE_DONE. */
 #if defined (READLINE_CALLBACKS)
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     return 1;
 #endif
   for (;;)
     {
       RL_SETSTATE(RL_STATE_MOREINPUT);
       c = rl_read_key ();
       RL_UNSETSTATE(RL_STATE_MOREINPUT);
       if (c == 'y' || c == 'Y' || c == ' ')
     return (1);
       if (c == 'n' || c == 'N' || c == RUBOUT)
     return (0);
       if (c == ABORT_CHAR || c < 0)
     _rl_abort_internal ();
       if (for_pager && (c == NEWLINE || c == RETURN))
     return (2);
       if (for_pager && (c == 'q' || c == 'Q'))
     return (0);
       rl_ding ();
     }
 }
References _rl_abort_internal(), ABORT_CHAR, c, NEWLINE, RETURN, rl_ding(), RL_ISSTATE, rl_read_key(), RL_SETSTATE, RL_STATE_CALLBACK, RL_STATE_MOREINPUT, RL_UNSETSTATE, and RUBOUT.
Referenced by _rl_internal_pager(), and display_matches().
insert_all_matches()
static void insert_all_matches (char ** matches, int point, char * qc) static
Definition at line 1922 of file complete.c.
 {
   int i;
   char *rp;
   rl_begin_undo_group ();
   /* remove any opening quote character; make_quoted_replacement will add
      it back. */
   if (qc && *qc && point && rl_line_buffer[point - 1] == *qc)
     point--;
   rl_delete_text (point, rl_point);
   rl_point = point;
   if (matches[1])
     {
       for (i = 1; matches[i]; i++)
     {
       rp = make_quoted_replacement (matches[i], SINGLE_MATCH, qc);
       rl_insert_text (rp);
       rl_insert_text (" ");
       if (rp != matches[i])
         xfree (rp);
     }
     }
   else
     {
       rp = make_quoted_replacement (matches[0], SINGLE_MATCH, qc);
       rl_insert_text (rp);
       rl_insert_text (" ");
       if (rp != matches[0])
     xfree (rp);
     }
   rl_end_undo_group ();
 }
References i, make_quoted_replacement(), rl_begin_undo_group(), rl_delete_text(), rl_end_undo_group(), rl_insert_text(), rl_line_buffer, rl_point, SINGLE_MATCH, and xfree.
Referenced by rl_complete_internal().
insert_match()
static void insert_match (char * match, int start, int mtype, char * qc) static
Definition at line 1798 of file complete.c.
 {
   char *replacement, *r;
   char oqc;
   int end, rlen;
   oqc = qc ? *qc : '\0';
   replacement = make_quoted_replacement (match, mtype, qc);
   /* Now insert the match. */
   if (replacement)
     {
       rlen = strlen (replacement);
       /* Don't double an opening quote character. */
       if (qc && *qc && start && rl_line_buffer[start - 1] == *qc &&
         replacement[0] == *qc)
     start--;
       /* If make_quoted_replacement changed the quoting character, remove
      the opening quote and insert the (fully-quoted) replacement. */
       else if (qc && (*qc != oqc) && start && rl_line_buffer[start - 1] == oqc &&
         replacement[0] != oqc)
     start--;
       end = rl_point - 1;
       /* Don't double a closing quote character */
       if (qc && *qc && end && rl_line_buffer[rl_point] == *qc && replacement[rlen - 1] == *qc)
         end++;
       if (_rl_skip_completed_text)
     {
       r = replacement;
       while (start < rl_end && *r && rl_line_buffer[start] == *r)
         {
           start++;
           r++;
         }
       if (start <= end || *r)
         _rl_replace_text (r, start, end);
       rl_point = start + strlen (r);
     }
       else
     _rl_replace_text (replacement, start, end);
       if (replacement != match)
         xfree (replacement);
     }
 }
References _rl_replace_text(), _rl_skip_completed_text, end, make_quoted_replacement(), rl_end, rl_line_buffer, rl_point, start, strlen(), and xfree.
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
make_quoted_replacement()
static char * make_quoted_replacement (char * match, int mtype, char * qc) static
Definition at line 1756 of file complete.c.
 {
   int should_quote, do_replace;
   char *replacement;
   /* If we are doing completion on quoted substrings, and any matches
      contain any of the completer_word_break_characters, then auto-
      matically prepend the substring with a quote character (just pick
      the first one from the list of such) if it does not already begin
      with a quote string.  FIXME: Need to remove any such automatically
      inserted quote character when it no longer is necessary, such as
      if we change the string we are completing on and the new set of
      matches don't require a quoted substring. */
   replacement = match;
   should_quote = match && rl_completer_quote_characters &&
             rl_filename_completion_desired &&
             rl_filename_quoting_desired;
   if (should_quote)
     should_quote = should_quote && (!qc || !*qc ||
              (rl_completer_quote_characters && strchr (rl_completer_quote_characters, *qc)));
   if (should_quote)
     {
       /* If there is a single match, see if we need to quote it.
          This also checks whether the common prefix of several
      matches needs to be quoted. */
       should_quote = rl_filename_quote_characters
             ? (_rl_strpbrk (match, rl_filename_quote_characters) != 0)
             : 0;
       do_replace = should_quote ? mtype : NO_MATCH;
       /* Quote the replacement, since we found an embedded
      word break character in a potential match. */
       if (do_replace != NO_MATCH && rl_filename_quoting_function)
     replacement = (*rl_filename_quoting_function) (match, do_replace, qc);
     }
   return (replacement);
 }
References _rl_strpbrk(), match(), NO_MATCH, rl_completer_quote_characters, rl_filename_completion_desired, rl_filename_quote_characters, rl_filename_quoting_desired, rl_filename_quoting_function, and strchr().
Referenced by insert_all_matches(), and insert_match().
path_isdir()
static int path_isdir (const char * filename) static
Definition at line 582 of file complete.c.
 {
   struct stat finfo;
   return (stat (filename, &finfo) == 0 && S_ISDIR (finfo.st_mode));
 }
References filename, S_ISDIR, and stat::st_mode.
Referenced by append_to_match(), and print_filename().
postprocess_matches()
static int postprocess_matches (char *** matchesp, int matching_filenames) static
Definition at line 1456 of file complete.c.
 {
   char *t, **matches, **temp_matches;
   int nmatch, i;
   matches = *matchesp;
   if (matches == 0)
     return 0;
   /* It seems to me that in all the cases we handle we would like
      to ignore duplicate possibilities.  Scan for the text to
      insert being identical to the other completions. */
   if (rl_ignore_completion_duplicates)
     {
       temp_matches = remove_duplicate_matches (matches);
       xfree (matches);
       matches = temp_matches;
     }
   /* If we are matching filenames, then here is our chance to
      do clever processing by re-examining the list.  Call the
      ignore function with the array as a parameter.  It can
      munge the array, deleting matches as it desires. */
   if (rl_ignore_some_completions_function && matching_filenames)
     {
       for (nmatch = 1; matches[nmatch]; nmatch++)
     ;
       (void)(*rl_ignore_some_completions_function) (matches);
       if (matches == 0 || matches[0] == 0)
     {
       FREE (matches);
       *matchesp = (char **)0;
       return 0;
         }
       else
     {
       /* If we removed some matches, recompute the common prefix. */
       for (i = 1; matches[i]; i++)
         ;
       if (i > 1 && i < nmatch)
         {
           t = matches[0];
           compute_lcd_of_matches (matches, i - 1, t);
           FREE (t);
         }
     }
     }
   *matchesp = matches;
   return (1);
 }
References compute_lcd_of_matches(), FREE, i, remove_duplicate_matches(), rl_ignore_completion_duplicates, rl_ignore_some_completions_function, t, Module::void(), and xfree.
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
print_filename()
static int print_filename (char * to_print, char * full_pathname, int prefix_bytes) static
Definition at line 934 of file complete.c.
 {
   int printed_len, extension_char, slen, tlen;
   char *s, c, *new_full_pathname, *dn;
   extension_char = 0;
 #if defined (COLOR_SUPPORT)
   /* Defer printing if we want to prefix with a color indicator */
   if (_rl_colored_stats == 0 || rl_filename_completion_desired == 0)
 #endif
     printed_len = fnprint (to_print, prefix_bytes, to_print);
   if (rl_filename_completion_desired && (
 #if defined (VISIBLE_STATS)
      rl_visible_stats ||
 #endif
 #if defined (COLOR_SUPPORT)
      _rl_colored_stats ||
 #endif
      _rl_complete_mark_directories))
     {
       /* If to_print != full_pathname, to_print is the basename of the
      path passed.  In this case, we try to expand the directory
      name before checking for the stat character. */
       if (to_print != full_pathname)
     {
       /* Terminate the directory name. */
       c = to_print[-1];
       to_print[-1] = '\0';
       /* If setting the last slash in full_pathname to a NUL results in
          full_pathname being the empty string, we are trying to complete
          files in the root directory.  If we pass a null string to the
          bash directory completion hook, for example, it will expand it
          to the current directory.  We just want the `/'. */
       if (full_pathname == 0 || *full_pathname == 0)
         dn = "/";
       else if (full_pathname[0] != '/')
         dn = full_pathname;
       else if (full_pathname[1] == 0)
         dn = "//";      /* restore trailing slash to `//' */
       else if (full_pathname[1] == '/' && full_pathname[2] == 0)
         dn = "/";       /* don't turn /// into // */
       else
         dn = full_pathname;
       s = tilde_expand (dn);
       if (rl_directory_completion_hook)
         (*rl_directory_completion_hook) (&s);
       slen = strlen (s);
       tlen = strlen (to_print);
       new_full_pathname = (char *)xmalloc (slen + tlen + 2);
       strcpy (new_full_pathname, s);
       if (s[slen - 1] == '/')
         slen--;
       else
         new_full_pathname[slen] = '/';
       strcpy (new_full_pathname + slen + 1, to_print);
 #if defined (VISIBLE_STATS)
       if (rl_visible_stats)
         extension_char = stat_char (new_full_pathname);
       else
 #endif
       if (_rl_complete_mark_directories)
         {
           dn = 0;
           if (rl_directory_completion_hook == 0 && rl_filename_stat_hook)
         {
           dn = savestring (new_full_pathname);
           (*rl_filename_stat_hook) (&dn);
           xfree (new_full_pathname);
           new_full_pathname = dn;
         }
           if (path_isdir (new_full_pathname))
         extension_char = '/';
         }
       /* Move colored-stats code inside fnprint() */
 #if defined (COLOR_SUPPORT)
       if (_rl_colored_stats)
         printed_len = fnprint (to_print, prefix_bytes, new_full_pathname);
 #endif
       xfree (new_full_pathname);
       to_print[-1] = c;
     }
       else
     {
       s = tilde_expand (full_pathname);
 #if defined (VISIBLE_STATS)
       if (rl_visible_stats)
         extension_char = stat_char (s);
       else
 #endif
         if (_rl_complete_mark_directories && path_isdir (s))
           extension_char = '/';
       /* Move colored-stats code inside fnprint() */
 #if defined (COLOR_SUPPORT)
       if (_rl_colored_stats)
         printed_len = fnprint (to_print, prefix_bytes, s);
 #endif
     }
       xfree (s);
       if (extension_char)
     {
       putc (extension_char, rl_outstream);
       printed_len++;
     }
     }
   return printed_len;
 }
References _rl_colored_stats, _rl_complete_mark_directories, c, COLOR_SUPPORT, fnprint(), full_pathname(), path_isdir(), putc, rl_directory_completion_hook, rl_filename_completion_desired, rl_filename_stat_hook, rl_outstream, rl_visible_stats, s, savestring(), stat_char(), strcpy, strlen(), tilde_expand(), VISIBLE_STATS, xfree, and xmalloc.
Referenced by display_matches(), and rl_display_match_list().
printable_part()
static char * printable_part (char * pathname) static
Definition at line 719 of file complete.c.
 {
   char *temp, *x;
   if (rl_filename_completion_desired == 0)  /* don't need to do anything */
     return (pathname);
   temp = strrchr (pathname, '/');
 #if defined (__MSDOS__) || defined (_WIN32)
   if (temp == 0 && ISALPHA ((unsigned char)pathname[0]) && pathname[1] == ':')
     temp = pathname + 1;
 #endif
   if (temp == 0 || *temp == '\0')
     return (pathname);
   else if (temp[1] == 0 && temp == pathname)
     return (pathname);
   /* If the basename is NULL, we might have a pathname like '/usr/src/'.
      Look for a previous slash and, if one is found, return the portion
      following that slash.  If there's no previous slash, just return the
      pathname we were passed. */
   else if (temp[1] == '\0')
     {
       for (x = temp - 1; x > pathname; x--)
         if (*x == '/')
           break;
       return ((*x == '/') ? x + 1 : pathname);
     }
   else
     return ++temp;
 }
References ISALPHA, rl_filename_completion_desired, strrchr(), and x.
Referenced by display_matches(), and rl_display_match_list().
remove_duplicate_matches()
static char ** remove_duplicate_matches (char ** matches) static
Definition at line 1256 of file complete.c.
 {
   char *lowest_common;
   int i, j, newlen;
   char dead_slot;
   char **temp_array;
   /* Sort the items. */
   for (i = 0; matches[i]; i++)
     ;
   /* Sort the array without matches[0], since we need it to
      stay in place no matter what. */
   if (i && rl_sort_completion_matches)
     qsort (matches+1, i-1, sizeof (char *), (QSFUNC *)_rl_qsort_string_compare);
   /* Remember the lowest common denominator for it may be unique. */
   lowest_common = savestring (matches[0]);
   for (i = newlen = 0; matches[i + 1]; i++)
     {
       if (strcmp (matches[i], matches[i + 1]) == 0)
     {
       xfree (matches[i]);
       matches[i] = (char *)&dead_slot;
     }
       else
     newlen++;
     }
   /* We have marked all the dead slots with (char *)&dead_slot.
      Copy all the non-dead entries into a new array. */
   temp_array = (char **)xmalloc ((3 + newlen) * sizeof (char *));
   for (i = j = 1; matches[i]; i++)
     {
       if (matches[i] != (char *)&dead_slot)
     temp_array[j++] = matches[i];
     }
   temp_array[j] = (char *)NULL;
   if (matches[0] != (char *)&dead_slot)
     xfree (matches[0]);
   /* Place the lowest common denominator back in [0]. */
   temp_array[0] = lowest_common;
   /* If there is one string left, and it is identical to the
      lowest common denominator, then the LCD is the string to
      insert. */
   if (j == 2 && strcmp (temp_array[0], temp_array[1]) == 0)
     {
       xfree (temp_array[1]);
       temp_array[1] = (char *)NULL;
     }
   return (temp_array);
 }
References _rl_qsort_string_compare(), i, j, NULL, qsort(), rl_sort_completion_matches, savestring(), strcmp, xfree, and xmalloc.
Referenced by postprocess_matches().
rl_backward_menu_complete()
int rl_backward_menu_complete (int count, int key)
Definition at line 2987 of file complete.c.
 {
   /* Positive arguments to backward-menu-complete translate into negative
      arguments for menu-complete, and vice versa. */
   return (rl_menu_complete (-count, key));
 }
References count, and rl_menu_complete().
Referenced by rl_menu_complete().
rl_complete()
int rl_complete (int ignore, int invoking_key)
Definition at line 434 of file complete.c.
 {
   rl_completion_invoking_key = invoking_key;
   if (rl_inhibit_completion)
     return (_rl_insert_char (ignore, invoking_key));
 #if 0
   else if (rl_last_func == rl_complete && completion_changed_buffer == 0 && last_completion_failed == 0)
 #else
   else if (rl_last_func == rl_complete && completion_changed_buffer == 0)
 #endif
     return (rl_complete_internal ('?'));
   else if (_rl_complete_show_all)
     return (rl_complete_internal ('!'));
   else if (_rl_complete_show_unmodified)
     return (rl_complete_internal ('@'));
   else
     return (rl_complete_internal (TAB));
 }
References _rl_complete_show_all, _rl_complete_show_unmodified, _rl_insert_char(), completion_changed_buffer, ignore(), last_completion_failed, rl_complete_internal(), rl_completion_invoking_key, rl_inhibit_completion, rl_last_func, and TAB.
Referenced by rl_vi_complete().
rl_complete_internal()
int rl_complete_internal (int what_to_do)
Definition at line 2000 of file complete.c.
 {
   char **matches;
   rl_compentry_func_t *our_func;
   int start, end, delimiter, found_quote, i, nontrivial_lcd;
   char *text, *saved_line_buffer;
   char quote_char;
   int tlen, mlen, saved_last_completion_failed;
   RL_SETSTATE(RL_STATE_COMPLETING);
   saved_last_completion_failed = last_completion_failed;
   set_completion_defaults (what_to_do);
   saved_line_buffer = rl_line_buffer ? savestring (rl_line_buffer) : (char *)NULL;
   our_func = rl_completion_entry_function
         ? rl_completion_entry_function
         : rl_filename_completion_function;
   /* We now look backwards for the start of a filename/variable word. */
   end = rl_point;
   found_quote = delimiter = 0;
   quote_char = '\0';
   if (rl_point)
     /* This (possibly) changes rl_point.  If it returns a non-zero char,
        we know we have an open quote. */
     quote_char = _rl_find_completion_word (&found_quote, &delimiter);
   start = rl_point;
   rl_point = end;
   text = rl_copy_text (start, end);
   matches = gen_completion_matches (text, start, end, our_func, found_quote, quote_char);
   /* nontrivial_lcd is set if the common prefix adds something to the word
      being completed. */
   nontrivial_lcd = matches && compare_match (text, matches[0]) != 0;
   if (what_to_do == '!' || what_to_do == '@')
     tlen = strlen (text);
   xfree (text);
   if (matches == 0)
     {
       rl_ding ();
       FREE (saved_line_buffer);
       completion_changed_buffer = 0;
       last_completion_failed = 1;
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       _rl_reset_completion_state ();
       return (0);
     }
   /* If we are matching filenames, the attempted completion function will
      have set rl_filename_completion_desired to a non-zero value.  The basic
      rl_filename_completion_function does this. */
   i = rl_filename_completion_desired;
   if (postprocess_matches (&matches, i) == 0)
     {
       rl_ding ();
       FREE (saved_line_buffer);
       completion_changed_buffer = 0;
       last_completion_failed = 1;
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       _rl_reset_completion_state ();
       return (0);
     }
   if (matches && matches[0] && *matches[0])
     last_completion_failed = 0;
   switch (what_to_do)
     {
     case TAB:
     case '!':
     case '@':
       /* Insert the first match with proper quoting. */
       if (what_to_do == TAB)
         {
           if (*matches[0])
         insert_match (matches[0], start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
         }
       else if (*matches[0] && matches[1] == 0)
     /* should we perform the check only if there are multiple matches? */
     insert_match (matches[0], start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
       else if (*matches[0]) /* what_to_do != TAB && multiple matches */
     {
       mlen = *matches[0] ? strlen (matches[0]) : 0;
       if (mlen >= tlen)
         insert_match (matches[0], start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
     }
       /* If there are more matches, ring the bell to indicate.
      If we are in vi mode, Posix.2 says to not ring the bell.
      If the `show-all-if-ambiguous' variable is set, display
      all the matches immediately.  Otherwise, if this was the
      only match, and we are hacking files, check the file to
      see if it was a directory.  If so, and the `mark-directories'
      variable is set, add a '/' to the name.  If not, and we
      are at the end of the line, then add a space.  */
       if (matches[1])
     {
       if (what_to_do == '!')
         {
           display_matches (matches);
           break;
         }
       else if (what_to_do == '@')
         {
           if (nontrivial_lcd == 0)
         display_matches (matches);
           break;
         }
       else if (rl_editing_mode != vi_mode)
         rl_ding (); /* There are other matches remaining. */
     }
       else
     append_to_match (matches[0], delimiter, quote_char, nontrivial_lcd);
       break;
     case '*':
       insert_all_matches (matches, start, &quote_char);
       break;
     case '?':
       /* Let's try to insert a single match here if the last completion failed
      but this attempt returned a single match. */
       if (saved_last_completion_failed && matches[0] && *matches[0] && matches[1] == 0)
     {
       insert_match (matches[0], start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
       append_to_match (matches[0], delimiter, quote_char, nontrivial_lcd);
       break;
     }
       if (rl_completion_display_matches_hook == 0)
     {
       _rl_sigcleanup = _rl_complete_sigcleanup;
       _rl_sigcleanarg = matches;
       _rl_complete_display_matches_interrupt = 0;
     }
       display_matches (matches);
       if (_rl_complete_display_matches_interrupt)
         {
           matches = 0;      /* already freed by rl_complete_sigcleanup */
           _rl_complete_display_matches_interrupt = 0;
       if (rl_signal_event_hook)
         (*rl_signal_event_hook) ();     /* XXX */
         }
       _rl_sigcleanup = 0;
       _rl_sigcleanarg = 0;
       break;
     default:
       _rl_ttymsg ("bad value %d for what_to_do in rl_complete", what_to_do);
       rl_ding ();
       FREE (saved_line_buffer);
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       _rl_free_match_list (matches);
       _rl_reset_completion_state ();
       return 1;
     }
   _rl_free_match_list (matches);
   /* Check to see if the line has changed through all of this manipulation. */
   if (saved_line_buffer)
     {
       completion_changed_buffer = strcmp (rl_line_buffer, saved_line_buffer) != 0;
       xfree (saved_line_buffer);
     }
   RL_UNSETSTATE(RL_STATE_COMPLETING);
   _rl_reset_completion_state ();
   RL_CHECK_SIGNALS ();
   return 0;
 }
References _rl_complete_display_matches_interrupt, _rl_complete_sigcleanup(), _rl_find_completion_word(), _rl_free_match_list(), _rl_reset_completion_state(), _rl_sigcleanarg, _rl_sigcleanup, _rl_ttymsg(), append_to_match(), compare_match(), completion_changed_buffer, display_matches(), end, FREE, gen_completion_matches(), i, insert_all_matches(), insert_match(), last_completion_failed, MULT_MATCH, NULL, postprocess_matches(), RL_CHECK_SIGNALS, rl_completion_display_matches_hook, rl_completion_entry_function, rl_copy_text(), rl_ding(), rl_editing_mode, rl_filename_completion_desired, rl_filename_completion_function(), rl_line_buffer, rl_point, RL_SETSTATE, rl_signal_event_hook, RL_STATE_COMPLETING, RL_UNSETSTATE, savestring(), set_completion_defaults(), SINGLE_MATCH, start, strcmp, strlen(), TAB, text, vi_mode, and xfree.
Referenced by rl_complete(), rl_insert_completions(), rl_possible_completions(), and rl_vi_complete().
rl_completion_matches()
char** rl_completion_matches (const char * text, rl_compentry_func_t * entry_function)
Definition at line 2198 of file complete.c.
 {
   register int i;
   /* Number of slots in match_list. */
   int match_list_size;
   /* The list of matches. */
   char **match_list;
   /* Number of matches actually found. */
   int matches;
   /* Temporary string binder. */
   char *string;
   matches = 0;
   match_list_size = 10;
   match_list = (char **)xmalloc ((match_list_size + 1) * sizeof (char *));
   match_list[1] = (char *)NULL;
   while (string = (*entry_function) (text, matches))
     {
       if (RL_SIG_RECEIVED ())
     {
       /* Start at 1 because we don't set matches[0] in this function.
          Only free the list members if we're building match list from
          rl_filename_completion_function, since we know that doesn't
          free the strings it returns. */
       if (entry_function == rl_filename_completion_function)
         {
           for (i = 1; match_list[i]; i++)
         xfree (match_list[i]);
         }
       xfree (match_list);
       match_list = 0;
       match_list_size = 0;
       matches = 0;
       RL_CHECK_SIGNALS ();
     }
       if (matches + 1 >= match_list_size)
     match_list = (char **)xrealloc
       (match_list, ((match_list_size += 10) + 1) * sizeof (char *));
       if (match_list == 0)
     return (match_list);
       match_list[++matches] = string;
       match_list[matches + 1] = (char *)NULL;
     }
   /* If there were any matches, then look through them finding out the
      lowest common denominator.  That then becomes match_list[0]. */
   if (matches)
     compute_lcd_of_matches (match_list, matches, text);
   else              /* There were no matches. */
     {
       xfree (match_list);
       match_list = (char **)NULL;
     }
   return (match_list);
 }
References compute_lcd_of_matches(), i, NULL, RL_CHECK_SIGNALS, rl_filename_completion_function(), RL_SIG_RECEIVED, string, text, xfree, xmalloc, and xrealloc.
Referenced by completion_matches(), fileman_completion(), and gen_completion_matches().
rl_completion_mode()
int rl_completion_mode (rl_command_func_t * cfunc)
Definition at line 475 of file complete.c.
 {
   if (rl_last_func == cfunc && !completion_changed_buffer)
     return '?';
   else if (_rl_complete_show_all)
     return '!';
   else if (_rl_complete_show_unmodified)
     return '@';
   else
     return TAB;
 }
References _rl_complete_show_all, _rl_complete_show_unmodified, completion_changed_buffer, rl_last_func, and TAB.
rl_display_match_list()
void rl_display_match_list (char ** matches, int len, int max)
Definition at line 1531 of file complete.c.
 {
   int count, limit, printed_len, lines, cols;
   int i, j, k, l, common_length, sind;
   char *temp, *t;
   /* Find the length of the prefix common to all items: length as displayed
      characters (common_length) and as a byte index into the matches (sind) */
   common_length = sind = 0;
   if (_rl_completion_prefix_display_length > 0)
     {
       t = printable_part (matches[0]);
       /* check again in case of /usr/src/ */
       temp = rl_filename_completion_desired ? strrchr (t, '/') : 0;
       common_length = temp ? fnwidth (temp) : fnwidth (t);
       sind = temp ? strlen (temp) : strlen (t);
       if (common_length > max || sind > max)
     common_length = sind = 0;
       if (common_length > _rl_completion_prefix_display_length && common_length > ELLIPSIS_LEN)
     max -= common_length - ELLIPSIS_LEN;
       else if (_rl_colored_completion_prefix <= 0)
     common_length = sind = 0;
     }
 #if defined (COLOR_SUPPORT)
   else if (_rl_colored_completion_prefix > 0)
     {
       t = printable_part (matches[0]);
       temp = rl_filename_completion_desired ? strrchr (t, '/') : 0;
       common_length = temp ? fnwidth (temp) : fnwidth (t);
       sind = temp ? RL_STRLEN (temp+1) : RL_STRLEN (t);     /* want portion after final slash */
       if (common_length > max || sind > max)
     common_length = sind = 0;
     }
 #endif
   /* How many items of MAX length can we fit in the screen window? */
   cols = complete_get_screenwidth ();
   max += 2;
   limit = cols / max;
   if (limit != 1 && (limit * max == cols))
     limit--;
   /* If cols == 0, limit will end up -1 */
   if (cols < _rl_screenwidth && limit < 0)
     limit = 1;
   /* Avoid a possible floating exception.  If max > cols,
      limit will be 0 and a divide-by-zero fault will result. */
   if (limit == 0)
     limit = 1;
   /* How many iterations of the printing loop? */
   count = (len + (limit - 1)) / limit;
   /* Watch out for special case.  If LEN is less than LIMIT, then
      just do the inner printing loop.
        0 < len <= limit  implies  count = 1. */
   /* Sort the items if they are not already sorted. */
   if (rl_ignore_completion_duplicates == 0 && rl_sort_completion_matches)
     qsort (matches + 1, len, sizeof (char *), (QSFUNC *)_rl_qsort_string_compare);
   rl_crlf ();
   lines = 0;
   if (_rl_print_completions_horizontally == 0)
     {
       /* Print the sorted items, up-and-down alphabetically, like ls. */
       for (i = 1; i <= count; i++)
     {
       for (j = 0, l = i; j < limit; j++)
         {
           if (l > len || matches[l] == 0)
         break;
           else
         {
           temp = printable_part (matches[l]);
           printed_len = print_filename (temp, matches[l], sind);
           if (j + 1 < limit)
             {
               if (max <= printed_len)
             putc (' ', rl_outstream);
               else
             for (k = 0; k < max - printed_len; k++)
               putc (' ', rl_outstream);
             }
         }
           l += count;
         }
       rl_crlf ();
 #if defined (SIGWINCH)
       if (RL_SIG_RECEIVED () && RL_SIGWINCH_RECEIVED() == 0)
 #else
       if (RL_SIG_RECEIVED ())
 #endif
         return;
       lines++;
       if (_rl_page_completions && lines >= (_rl_screenheight - 1) && i < count)
         {
           lines = _rl_internal_pager (lines);
           if (lines < 0)
         return;
         }
     }
     }
   else
     {
       /* Print the sorted items, across alphabetically, like ls -x. */
       for (i = 1; matches[i]; i++)
     {
       temp = printable_part (matches[i]);
       printed_len = print_filename (temp, matches[i], sind);
       /* Have we reached the end of this line? */
 #if defined (SIGWINCH)
       if (RL_SIG_RECEIVED () && RL_SIGWINCH_RECEIVED() == 0)
 #else
       if (RL_SIG_RECEIVED ())
 #endif
         return;
       if (matches[i+1])
         {
           if (limit == 1 || (i && (limit > 1) && (i % limit) == 0))
         {
           rl_crlf ();
           lines++;
           if (_rl_page_completions && lines >= _rl_screenheight - 1)
             {
               lines = _rl_internal_pager (lines);
               if (lines < 0)
             return;
             }
         }
           else if (max <= printed_len)
         putc (' ', rl_outstream);
           else
         for (k = 0; k < max - printed_len; k++)
           putc (' ', rl_outstream);
         }
     }
       rl_crlf ();
     }
 }
References _rl_colored_completion_prefix, _rl_completion_prefix_display_length, _rl_internal_pager(), _rl_page_completions, _rl_print_completions_horizontally, _rl_qsort_string_compare(), _rl_screenheight, _rl_screenwidth, cols, complete_get_screenwidth(), count, ELLIPSIS_LEN, fnwidth(), i, j, k, l, len, limit(), lines, max, print_filename(), printable_part(), putc, qsort(), rl_crlf(), rl_filename_completion_desired, rl_ignore_completion_duplicates, rl_outstream, RL_SIG_RECEIVED, RL_SIGWINCH_RECEIVED, rl_sort_completion_matches, RL_STRLEN, strlen(), strrchr(), and t.
Referenced by display_matches().
rl_filename_completion_function()
char* rl_filename_completion_function (const char * text, int state)
Definition at line 2456 of file complete.c.
 {
   static DIR *directory = (DIR *)NULL;
   static char *filename = (char *)NULL;
   static char *dirname = (char *)NULL;
   static char *users_dirname = (char *)NULL;
   static int filename_len;
   char *temp, *dentry, *convfn;
   int dirlen, dentlen, convlen;
   int tilde_dirname;
   struct dirent *entry;
   /* If we don't have any state, then do some initialization. */
   if (state == 0)
     {
       /* If we were interrupted before closing the directory or reading
      all of its contents, close it. */
       if (directory)
     {
       closedir (directory);
       directory = (DIR *)NULL;
     }
       FREE (dirname);
       FREE (filename);
       FREE (users_dirname);
       filename = savestring (text);
       if (*text == 0)
     text = ".";
       dirname = savestring (text);
       temp = strrchr (dirname, '/');
 #if defined (__MSDOS__) || defined (_WIN32)
       /* special hack for //X/... */
       if (dirname[0] == '/' && dirname[1] == '/' && ISALPHA ((unsigned char)dirname[2]) && dirname[3] == '/')
         temp = strrchr (dirname + 3, '/');
 #endif
       if (temp)
     {
       strcpy (filename, ++temp);
       *temp = '\0';
     }
 #if defined (__MSDOS__) || (defined (_WIN32) && !defined (__CYGWIN__))
       /* searches from current directory on the drive */
       else if (ISALPHA ((unsigned char)dirname[0]) && dirname[1] == ':')
         {
           strcpy (filename, dirname + 2);
           dirname[2] = '\0';
         }
 #endif
       else
     {
       dirname[0] = '.';
       dirname[1] = '\0';
     }
       /* We aren't done yet.  We also support the "~user" syntax. */
       /* Save the version of the directory that the user typed, dequoting
      it if necessary. */
       if (rl_completion_found_quote && rl_filename_dequoting_function)
     users_dirname = (*rl_filename_dequoting_function) (dirname, rl_completion_quote_character);
       else
     users_dirname = savestring (dirname);
       tilde_dirname = 0;
       if (*dirname == '~')
     {
       temp = tilde_expand (dirname);
       xfree (dirname);
       dirname = temp;
       tilde_dirname = 1;
     }
       /* We have saved the possibly-dequoted version of the directory name
      the user typed.  Now transform the directory name we're going to
      pass to opendir(2).  The directory rewrite hook modifies only the
      directory name; the directory completion hook modifies both the
      directory name passed to opendir(2) and the version the user
      typed.  Both the directory completion and rewrite hooks should perform
      any necessary dequoting.  The hook functions return 1 if they modify
      the directory name argument.  If either hook returns 0, it should
      not modify the directory name pointer passed as an argument. */
       if (rl_directory_rewrite_hook)
     (*rl_directory_rewrite_hook) (&dirname);
       else if (rl_directory_completion_hook && (*rl_directory_completion_hook) (&dirname))
     {
       xfree (users_dirname);
       users_dirname = savestring (dirname);
     }
       else if (tilde_dirname == 0 && rl_completion_found_quote && rl_filename_dequoting_function)
     {
       /* delete single and double quotes */
       xfree (dirname);
       dirname = savestring (users_dirname);
     }
       directory = opendir (dirname);
       /* Now dequote a non-null filename.  FILENAME will not be NULL, but may
      be empty. */
       if (*filename && rl_completion_found_quote && rl_filename_dequoting_function)
     {
       /* delete single and double quotes */
       temp = (*rl_filename_dequoting_function) (filename, rl_completion_quote_character);
       xfree (filename);
       filename = temp;
     }
       filename_len = strlen (filename);
       rl_filename_completion_desired = 1;
     }
   /* At this point we should entertain the possibility of hacking wildcarded
      filenames, like /usr/man/man<WILD>/te<TAB>.  If the directory name
      contains globbing characters, then build an array of directories, and
      then map over that list while completing. */
   /* *** UNIMPLEMENTED *** */
   /* Now that we have some state, we can read the directory. */
   entry = (struct dirent *)NULL;
   while (directory && (entry = readdir (directory)))
     {
       convfn = dentry = entry->d_name;
       convlen = dentlen = D_NAMLEN (entry);
       if (rl_filename_rewrite_hook)
     {
       convfn = (*rl_filename_rewrite_hook) (dentry, dentlen);
       convlen = (convfn == dentry) ? dentlen : strlen (convfn);
     }
       /* Special case for no filename.  If the user has disabled the
          `match-hidden-files' variable, skip filenames beginning with `.'.
      All other entries except "." and ".." match. */
       if (filename_len == 0)
     {
       if (_rl_match_hidden_files == 0 && HIDDEN_FILE (convfn))
         continue;
       if (convfn[0] != '.' ||
            (convfn[1] && (convfn[1] != '.' || convfn[2])))
         break;
     }
       else
     {
       if (complete_fncmp (convfn, convlen, filename, filename_len))
         break;
     }
     }
   if (entry == 0)
     {
       if (directory)
     {
       closedir (directory);
       directory = (DIR *)NULL;
     }
       if (dirname)
     {
       xfree (dirname);
       dirname = (char *)NULL;
     }
       if (filename)
     {
       xfree (filename);
       filename = (char *)NULL;
     }
       if (users_dirname)
     {
       xfree (users_dirname);
       users_dirname = (char *)NULL;
     }
       return (char *)NULL;
     }
   else
     {
       /* dirname && (strcmp (dirname, ".") != 0) */
       if (dirname && (dirname[0] != '.' || dirname[1]))
     {
       if (rl_complete_with_tilde_expansion && *users_dirname == '~')
         {
           dirlen = strlen (dirname);
           temp = (char *)xmalloc (2 + dirlen + D_NAMLEN (entry));
           strcpy (temp, dirname);
           /* Canonicalization cuts off any final slash present.  We
          may need to add it back. */
           if (dirname[dirlen - 1] != '/')
             {
               temp[dirlen++] = '/';
               temp[dirlen] = '\0';
             }
         }
       else
         {
           dirlen = strlen (users_dirname);
           temp = (char *)xmalloc (2 + dirlen + D_NAMLEN (entry));
           strcpy (temp, users_dirname);
           /* Make sure that temp has a trailing slash here. */
           if (users_dirname[dirlen - 1] != '/')
         temp[dirlen++] = '/';
         }
       strcpy (temp + dirlen, convfn);
     }
       else
     temp = savestring (convfn);
       if (convfn != dentry)
     xfree (convfn);
       return (temp);
     }
 }
References _rl_match_hidden_files, closedir(), complete_fncmp(), D_NAMLEN, directory, dirname, filename, FREE, HIDDEN_FILE, ISALPHA, NULL, opendir(), readdir(), rl_complete_with_tilde_expansion, rl_completion_found_quote, rl_completion_quote_character, rl_directory_completion_hook, rl_directory_rewrite_hook, rl_filename_completion_desired, rl_filename_dequoting_function, rl_filename_rewrite_hook, savestring(), state, strcpy, strlen(), strrchr(), text, tilde_expand(), xfree, and xmalloc.
Referenced by filename_completion_function(), rl_complete_internal(), rl_completion_matches(), rl_menu_complete(), and rl_old_menu_complete().
rl_insert_completions()
int rl_insert_completions (int ignore, int invoking_key)
Definition at line 463 of file complete.c.
 {
   rl_completion_invoking_key = invoking_key;
   return (rl_complete_internal ('*'));
 }
References rl_complete_internal(), and rl_completion_invoking_key.
rl_menu_complete()
int rl_menu_complete (int count, int ignore)
Definition at line 2815 of file complete.c.
 {
   rl_compentry_func_t *our_func;
   int matching_filenames, found_quote;
   static char *orig_text;
   static char **matches = (char **)0;
   static int match_list_index = 0;
   static int match_list_size = 0;
   static int nontrivial_lcd = 0;
   static int full_completion = 0;   /* set to 1 if menu completion should reinitialize on next call */
   static int orig_start, orig_end;
   static char quote_char;
   static int delimiter, cstate;
   /* The first time through, we generate the list of matches and set things
      up to insert them. */
   if ((rl_last_func != rl_menu_complete && rl_last_func != rl_backward_menu_complete) || full_completion)
     {
       /* Clean up from previous call, if any. */
       FREE (orig_text);
       if (matches)
     _rl_free_match_list (matches);
       match_list_index = match_list_size = 0;
       matches = (char **)NULL;
       full_completion = 0;
       RL_SETSTATE(RL_STATE_COMPLETING);
       /* Only the completion entry function can change these. */
       set_completion_defaults ('%');
       our_func = rl_menu_completion_entry_function;
       if (our_func == 0)
     our_func = rl_completion_entry_function
             ? rl_completion_entry_function
             : rl_filename_completion_function;
       /* We now look backwards for the start of a filename/variable word. */
       orig_end = rl_point;
       found_quote = delimiter = 0;
       quote_char = '\0';
       if (rl_point)
     /* This (possibly) changes rl_point.  If it returns a non-zero char,
        we know we have an open quote. */
     quote_char = _rl_find_completion_word (&found_quote, &delimiter);
       orig_start = rl_point;
       rl_point = orig_end;
       orig_text = rl_copy_text (orig_start, orig_end);
       matches = gen_completion_matches (orig_text, orig_start, orig_end,
                     our_func, found_quote, quote_char);
       nontrivial_lcd = matches && compare_match (orig_text, matches[0]) != 0;
       /* If we are matching filenames, the attempted completion function will
      have set rl_filename_completion_desired to a non-zero value.  The basic
      rl_filename_completion_function does this. */
       matching_filenames = rl_filename_completion_desired;
       if (matches == 0 || postprocess_matches (&matches, matching_filenames) == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       FREE (orig_text);
       orig_text = (char *)0;
       completion_changed_buffer = 0;
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       return (0);
     }
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       for (match_list_size = 0; matches[match_list_size]; match_list_size++)
         ;
       if (match_list_size == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       match_list_index = 0;
       completion_changed_buffer = 0;
       return (0);
         }
       /* matches[0] is lcd if match_list_size > 1, but the circular buffer
      code below should take care of it. */
       if (*matches[0])
     {
       insert_match (matches[0], orig_start, matches[1] ? MULT_MATCH : SINGLE_MATCH, &quote_char);
       orig_end = orig_start + strlen (matches[0]);
       completion_changed_buffer = STREQ (orig_text, matches[0]) == 0;
     }
       if (match_list_size > 1 && _rl_complete_show_all)
     {
       display_matches (matches);
       /* If there are so many matches that the user has to be asked
          whether or not he wants to see the matches, menu completion
          is unwieldy. */
       if (rl_completion_query_items > 0 && match_list_size >= rl_completion_query_items)
         {
           rl_ding ();
           FREE (matches);
           matches = (char **)0;
           full_completion = 1;
           return (0);
         }
       else if (_rl_menu_complete_prefix_first)
         {
           rl_ding ();
           return (0);
         }
     }
       else if (match_list_size <= 1)
     {
       append_to_match (matches[0], delimiter, quote_char, nontrivial_lcd);
       full_completion = 1;
       return (0);
     }
       else if (_rl_menu_complete_prefix_first && match_list_size > 1)
     {
       rl_ding ();
       return (0);
     }
     }
   /* Now we have the list of matches.  Replace the text between
      rl_line_buffer[orig_start] and rl_line_buffer[rl_point] with
      matches[match_list_index], and add any necessary closing char. */
   if (matches == 0 || match_list_size == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       completion_changed_buffer = 0;
       return (0);
     }
   match_list_index += count;
   if (match_list_index < 0)
     {
       while (match_list_index < 0)
     match_list_index += match_list_size;
     }
   else
     match_list_index %= match_list_size;
   if (match_list_index == 0 && match_list_size > 1)
     {
       rl_ding ();
       insert_match (matches[0], orig_start, MULT_MATCH, &quote_char);
     }
   else
     {
       insert_match (matches[match_list_index], orig_start, SINGLE_MATCH, &quote_char);
       append_to_match (matches[match_list_index], delimiter, quote_char,
                compare_match (orig_text, matches[match_list_index]));
     }
   completion_changed_buffer = 1;
   return (0);
 }
References _rl_complete_show_all, _rl_find_completion_word(), _rl_free_match_list(), _rl_menu_complete_prefix_first, append_to_match(), compare_match(), completion_changed_buffer, count, display_matches(), FREE, gen_completion_matches(), insert_match(), MULT_MATCH, NULL, postprocess_matches(), rl_backward_menu_complete(), rl_completion_entry_function, rl_completion_query_items, rl_copy_text(), rl_ding(), rl_filename_completion_desired, rl_filename_completion_function(), rl_last_func, rl_menu_completion_entry_function, rl_point, RL_SETSTATE, RL_STATE_COMPLETING, RL_UNSETSTATE, set_completion_defaults(), SINGLE_MATCH, STREQ, and strlen().
Referenced by rl_backward_menu_complete().
rl_old_menu_complete()
int rl_old_menu_complete (int count, int invoking_key)
Definition at line 2684 of file complete.c.
 {
   rl_compentry_func_t *our_func;
   int matching_filenames, found_quote;
   static char *orig_text;
   static char **matches = (char **)0;
   static int match_list_index = 0;
   static int match_list_size = 0;
   static int orig_start, orig_end;
   static char quote_char;
   static int delimiter;
   /* The first time through, we generate the list of matches and set things
      up to insert them. */
   if (rl_last_func != rl_old_menu_complete)
     {
       /* Clean up from previous call, if any. */
       FREE (orig_text);
       if (matches)
     _rl_free_match_list (matches);
       match_list_index = match_list_size = 0;
       matches = (char **)NULL;
       rl_completion_invoking_key = invoking_key;
       RL_SETSTATE(RL_STATE_COMPLETING);
       /* Only the completion entry function can change these. */
       set_completion_defaults ('%');
       our_func = rl_menu_completion_entry_function;
       if (our_func == 0)
     our_func = rl_completion_entry_function
             ? rl_completion_entry_function
             : rl_filename_completion_function;
       /* We now look backwards for the start of a filename/variable word. */
       orig_end = rl_point;
       found_quote = delimiter = 0;
       quote_char = '\0';
       if (rl_point)
     /* This (possibly) changes rl_point.  If it returns a non-zero char,
        we know we have an open quote. */
     quote_char = _rl_find_completion_word (&found_quote, &delimiter);
       orig_start = rl_point;
       rl_point = orig_end;
       orig_text = rl_copy_text (orig_start, orig_end);
       matches = gen_completion_matches (orig_text, orig_start, orig_end,
                     our_func, found_quote, quote_char);
       /* If we are matching filenames, the attempted completion function will
      have set rl_filename_completion_desired to a non-zero value.  The basic
      rl_filename_completion_function does this. */
       matching_filenames = rl_filename_completion_desired;
       if (matches == 0 || postprocess_matches (&matches, matching_filenames) == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       FREE (orig_text);
       orig_text = (char *)0;
       completion_changed_buffer = 0;
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       return (0);
     }
       RL_UNSETSTATE(RL_STATE_COMPLETING);
       for (match_list_size = 0; matches[match_list_size]; match_list_size++)
         ;
       /* matches[0] is lcd if match_list_size > 1, but the circular buffer
      code below should take care of it. */
       if (match_list_size > 1 && _rl_complete_show_all)
     display_matches (matches);
     }
   /* Now we have the list of matches.  Replace the text between
      rl_line_buffer[orig_start] and rl_line_buffer[rl_point] with
      matches[match_list_index], and add any necessary closing char. */
   if (matches == 0 || match_list_size == 0)
     {
       rl_ding ();
       FREE (matches);
       matches = (char **)0;
       completion_changed_buffer = 0;
       return (0);
     }
   match_list_index += count;
   if (match_list_index < 0)
     {
       while (match_list_index < 0)
     match_list_index += match_list_size;
     }
   else
     match_list_index %= match_list_size;
   if (match_list_index == 0 && match_list_size > 1)
     {
       rl_ding ();
       insert_match (orig_text, orig_start, MULT_MATCH, &quote_char);
     }
   else
     {
       insert_match (matches[match_list_index], orig_start, SINGLE_MATCH, &quote_char);
       append_to_match (matches[match_list_index], delimiter, quote_char,
                compare_match (orig_text, matches[match_list_index]));
     }
   completion_changed_buffer = 1;
   return (0);
 }
References _rl_complete_show_all, _rl_find_completion_word(), _rl_free_match_list(), append_to_match(), compare_match(), completion_changed_buffer, count, display_matches(), FREE, gen_completion_matches(), insert_match(), MULT_MATCH, NULL, postprocess_matches(), rl_completion_entry_function, rl_completion_invoking_key, rl_copy_text(), rl_ding(), rl_filename_completion_desired, rl_filename_completion_function(), rl_last_func, rl_menu_completion_entry_function, rl_point, RL_SETSTATE, RL_STATE_COMPLETING, RL_UNSETSTATE, set_completion_defaults(), and SINGLE_MATCH.
rl_possible_completions()
int rl_possible_completions (int ignore, int invoking_key)
Definition at line 456 of file complete.c.
 {
   rl_completion_invoking_key = invoking_key;
   return (rl_complete_internal ('?'));
 }
References rl_complete_internal(), and rl_completion_invoking_key.
Referenced by rl_delete_or_show_completions().
rl_quote_filename()
static char * rl_quote_filename (char * s, int rtype, char * qcp) static
Definition at line 1051 of file complete.c.
 {
   char *r;
   r = (char *)xmalloc (strlen (s) + 2);
   *r = *rl_completer_quote_characters;
   strcpy (r + 1, s);
   if (qcp)
     *qcp = *rl_completer_quote_characters;
   return r;
 }
References rl_completer_quote_characters, s, strcpy, strlen(), and xmalloc.
rl_username_completion_function()
char* rl_username_completion_function (const char * text, int state)
Definition at line 2266 of file complete.c.
 {
 #if defined (__WIN32__) || defined (__OPENNT)
   return (char *)NULL;
 #else /* !__WIN32__ && !__OPENNT) */
   static char *username = (char *)NULL;
   static struct passwd *entry;
   static int namelen, first_char, first_char_loc;
   char *value;
   if (state == 0)
     {
       FREE (username);
       first_char = *text;
       first_char_loc = first_char == '~';
       username = savestring (&text[first_char_loc]);
       namelen = strlen (username);
 #if defined (HAVE_GETPWENT)
       setpwent ();
 #endif
     }
 #if defined (HAVE_GETPWENT)
   while (entry = getpwent ())
     {
       /* Null usernames should result in all users as possible completions. */
       if (namelen == 0 || (STREQN (username, entry->pw_name, namelen)))
     break;
     }
 #endif
   if (entry == 0)
     {
 #if defined (HAVE_GETPWENT)
       endpwent ();
 #endif
       return ((char *)NULL);
     }
   else
     {
       value = (char *)xmalloc (2 + strlen (entry->pw_name));
       *value = *text;
       strcpy (value + first_char_loc, entry->pw_name);
       if (first_char == '~')
     rl_filename_completion_desired = 1;
       return (value);
     }
 #endif /* !__WIN32__ && !__OPENNT */
 }
References endpwent(), FREE, getpwent, namelen, NULL, rl_filename_completion_desired, savestring(), setpwent, state, strcpy, STREQN, strlen(), text, value, and xmalloc.
Referenced by username_completion_function().
set_completion_defaults()
static void set_completion_defaults (int what_to_do) static
Definition at line 514 of file complete.c.
 {
   /* Only the completion entry function can change these. */
   rl_filename_completion_desired = 0;
   rl_filename_quoting_desired = 1;
   rl_completion_type = what_to_do;
   rl_completion_suppress_append = rl_completion_suppress_quote = 0;
   rl_completion_append_character = ' ';
   /* The completion entry function may optionally change this. */
   rl_completion_mark_symlink_dirs = _rl_complete_mark_symlink_dirs;
   /* Reset private state. */
   _rl_complete_display_matches_interrupt = 0;
 }
References _rl_complete_display_matches_interrupt, _rl_complete_mark_symlink_dirs, rl_completion_append_character, rl_completion_mark_symlink_dirs, rl_completion_suppress_append, rl_completion_suppress_quote, rl_completion_type, rl_filename_completion_desired, and rl_filename_quoting_desired.
Referenced by rl_complete_internal(), rl_menu_complete(), and rl_old_menu_complete().
stat_char()
static int stat_char (char * filename) static
Definition at line 599 of file complete.c.
 {
   struct stat finfo;
   int character, r;
   char *f;
   const char *fn;
   /* Short-circuit a //server on cygwin, since that will always behave as
      a directory. */
 #if __CYGWIN__
   if (filename[0] == '/' && filename[1] == '/' && strchr (filename+2, '/') == 0)
     return '/';
 #endif
   f = 0;
   if (rl_filename_stat_hook)
     {
       f = savestring (filename);
       (*rl_filename_stat_hook) (&f);
       fn = f;
     }
   else
     fn = filename;
 #if defined (HAVE_LSTAT) && defined (S_ISLNK)
   r = lstat (fn, &finfo);
 #else
   r = stat (fn, &finfo);
 #endif
   if (r == -1)
     {
       xfree (f);
       return (0);
     }
   character = 0;
   if (S_ISDIR (finfo.st_mode))
     character = '/';
 #if defined (S_ISCHR)
   else if (S_ISCHR (finfo.st_mode))
     character = '%';
 #endif /* S_ISCHR */
 #if defined (S_ISBLK)
   else if (S_ISBLK (finfo.st_mode))
     character = '#';
 #endif /* S_ISBLK */
 #if defined (S_ISLNK)
   else if (S_ISLNK (finfo.st_mode))
     character = '@';
 #endif /* S_ISLNK */
 #if defined (S_ISSOCK)
   else if (S_ISSOCK (finfo.st_mode))
     character = '=';
 #endif /* S_ISSOCK */
 #if defined (S_ISFIFO)
   else if (S_ISFIFO (finfo.st_mode))
     character = '|';
 #endif
   else if (S_ISREG (finfo.st_mode))
     {
 #if defined (_WIN32) && !defined (__CYGWIN__)
       char *ext;
       /* Windows doesn't do access and X_OK; check file extension instead */
       ext = strrchr (fn, '.');
       if (ext && (_rl_stricmp (ext, ".exe") == 0 ||
           _rl_stricmp (ext, ".cmd") == 0 ||
           _rl_stricmp (ext, ".bat") == 0 ||
           _rl_stricmp (ext, ".com") == 0))
     character = '*';
 #else
       if (access (filename, X_OK) == 0)
     character = '*';
 #endif
     }
   xfree (f);
   return (character);
 }
References _rl_stricmp(), access(), f, filename, lstat, rl_filename_stat_hook, S_ISBLK, S_ISCHR, S_ISDIR, S_ISFIFO, S_ISLNK, S_ISREG, S_ISSOCK, savestring(), stat::st_mode, stat(), strchr(), strrchr(), X_OK, and xfree.
Referenced by print_filename().
Variable Documentation
_rl_colored_completion_prefix
int _rl_colored_completion_prefix = 0
Definition at line 216 of file complete.c.
Referenced by fnprint(), readline_initialize_everything(), and rl_display_match_list().
_rl_colored_stats
int _rl_colored_stats = 0
Definition at line 212 of file complete.c.
Referenced by _rl_parse_colors(), fnprint(), print_filename(), and readline_initialize_everything().
_rl_complete_display_matches_interrupt
int _rl_complete_display_matches_interrupt = 0 static
Definition at line 422 of file complete.c.
Referenced by _rl_complete_sigcleanup(), rl_complete_internal(), and set_completion_defaults().
_rl_complete_mark_directories
int _rl_complete_mark_directories = 1
Definition at line 172 of file complete.c.
Referenced by append_to_match(), and print_filename().
_rl_complete_mark_symlink_dirs
int _rl_complete_mark_symlink_dirs = 0
Definition at line 178 of file complete.c.
Referenced by set_completion_defaults().
_rl_complete_show_all
int _rl_complete_show_all = 0
Definition at line 165 of file complete.c.
Referenced by rl_complete(), rl_completion_mode(), rl_menu_complete(), and rl_old_menu_complete().
_rl_complete_show_unmodified
int _rl_complete_show_unmodified = 0
Definition at line 169 of file complete.c.
Referenced by rl_complete(), and rl_completion_mode().
_rl_completion_case_fold
int _rl_completion_case_fold = 0
Definition at line 188 of file complete.c.
Referenced by complete_fncmp(), and compute_lcd_of_matches().
_rl_completion_case_map
int _rl_completion_case_map = 0
Definition at line 193 of file complete.c.
Referenced by complete_fncmp().
_rl_completion_columns
int _rl_completion_columns = -1
Definition at line 207 of file complete.c.
Referenced by _rl_get_string_variable_value(), complete_get_screenwidth(), and sv_compwidth().
_rl_completion_prefix_display_length
int _rl_completion_prefix_display_length = 0
Definition at line 203 of file complete.c.
Referenced by _rl_get_string_variable_value(), fnprint(), rl_display_match_list(), and sv_dispprefix().
_rl_match_hidden_files
int _rl_match_hidden_files = 1
Definition at line 197 of file complete.c.
Referenced by rl_filename_completion_function().
_rl_menu_complete_prefix_first
int _rl_menu_complete_prefix_first = 0
Definition at line 227 of file complete.c.
Referenced by rl_menu_complete().
_rl_page_completions
int _rl_page_completions = 1
Definition at line 294 of file complete.c.
Referenced by rl_display_match_list().
_rl_print_completions_horizontally
int _rl_print_completions_horizontally
Definition at line 182 of file complete.c.
Referenced by rl_display_match_list().
_rl_skip_completed_text
int _rl_skip_completed_text = 0
Definition at line 223 of file complete.c.
Referenced by insert_match().
completion_changed_buffer
int completion_changed_buffer static
Definition at line 416 of file complete.c.
Referenced by rl_complete(), rl_complete_internal(), rl_completion_mode(), rl_menu_complete(), and rl_old_menu_complete().
completion_y_or_n
int completion_y_or_n static
Definition at line 420 of file complete.c.
Referenced by display_matches().
errno
int errno extern
last_completion_failed
int last_completion_failed = 0 static
Definition at line 417 of file complete.c.
Referenced by rl_complete(), and rl_complete_internal().
rl_attempted_completion_function
rl_completion_func_t* rl_attempted_completion_function = (rl_completion_func_t *)NULL
Definition at line 277 of file complete.c.
Referenced by gen_completion_matches(), initialize_readline(), rl_restore_state(), and rl_save_state().
rl_attempted_completion_over
int rl_attempted_completion_over = 0
Definition at line 281 of file complete.c.
Referenced by gen_completion_matches().
rl_basic_quote_characters
const char* rl_basic_quote_characters = "\"'"
Definition at line 302 of file complete.c.
Referenced by _rl_find_completion_word(), and find_matching_open().
rl_basic_word_break_characters
const char* rl_basic_word_break_characters = " \t\n\"\\'`@$><=;|&{("
Definition at line 299 of file complete.c.
Referenced by readline_initialize_everything().
rl_char_is_quoted_p
rl_linebuf_func_t* rl_char_is_quoted_p = (rl_linebuf_func_t *)NULL
Definition at line 369 of file complete.c.
Referenced by _rl_find_completion_word().
rl_complete_with_tilde_expansion
int rl_complete_with_tilde_expansion = 0
Definition at line 259 of file complete.c.
Referenced by rl_filename_completion_function().
rl_completer_quote_characters
const char* rl_completer_quote_characters = (const char *)NULL
Definition at line 318 of file complete.c.
Referenced by _rl_find_completion_word(), make_quoted_replacement(), and rl_quote_filename().
rl_completer_word_break_characters
const char* rl_completer_word_break_characters = 0
Definition at line 307 of file complete.c.
Referenced by _rl_find_completion_word(), readline_initialize_everything(), rl_restore_state(), and rl_save_state().
rl_completion_append_character
int rl_completion_append_character = ' '
Definition at line 378 of file complete.c.
Referenced by append_to_match(), and set_completion_defaults().
rl_completion_display_matches_hook
rl_compdisp_func_t* rl_completion_display_matches_hook = (rl_compdisp_func_t *)NULL
Definition at line 108 of file complete.c.
Referenced by display_matches(), and rl_complete_internal().
rl_completion_entry_function
rl_compentry_func_t* rl_completion_entry_function = (rl_compentry_func_t *)NULL
Definition at line 264 of file complete.c.
Referenced by rl_complete_internal(), rl_menu_complete(), rl_old_menu_complete(), rl_restore_state(), and rl_save_state().
rl_completion_found_quote
int rl_completion_found_quote
Definition at line 391 of file complete.c.
Referenced by _rl_reset_completion_state(), compare_match(), compute_lcd_of_matches(), gen_completion_matches(), and rl_filename_completion_function().
rl_completion_invoking_key
int rl_completion_invoking_key
Definition at line 408 of file complete.c.
Referenced by rl_complete(), rl_insert_completions(), rl_old_menu_complete(), and rl_possible_completions().
rl_completion_mark_symlink_dirs
int rl_completion_mark_symlink_dirs
Definition at line 402 of file complete.c.
Referenced by append_to_match(), and set_completion_defaults().
rl_completion_query_items
int rl_completion_query_items = 100
Definition at line 292 of file complete.c.
Referenced by _rl_get_string_variable_value(), display_matches(), rl_menu_complete(), and sv_compquery().
rl_completion_quote_character
int rl_completion_quote_character
Definition at line 387 of file complete.c.
Referenced by _rl_reset_completion_state(), compare_match(), compute_lcd_of_matches(), gen_completion_matches(), and rl_filename_completion_function().
rl_completion_suppress_append
int rl_completion_suppress_append = 0
Definition at line 374 of file complete.c.
Referenced by append_to_match(), and set_completion_defaults().
rl_completion_suppress_quote
int rl_completion_suppress_quote = 0
Definition at line 383 of file complete.c.
Referenced by append_to_match(), and set_completion_defaults().
rl_completion_type
int rl_completion_type = 0
Definition at line 286 of file complete.c.
Referenced by set_completion_defaults().
rl_completion_word_break_hook
rl_cpvfunc_t* rl_completion_word_break_hook = (rl_cpvfunc_t *)NULL
Definition at line 312 of file complete.c.
Referenced by _rl_find_completion_word().
rl_directory_completion_hook
rl_icppfunc_t* rl_directory_completion_hook = (rl_icppfunc_t *)NULL
Definition at line 241 of file complete.c.
Referenced by print_filename(), and rl_filename_completion_function().
rl_directory_rewrite_hook
rl_icppfunc_t* rl_directory_rewrite_hook = (rl_icppfunc_t *)NULL
Definition at line 243 of file complete.c.
Referenced by rl_filename_completion_function().
rl_filename_completion_desired
int rl_filename_completion_desired = 0
Definition at line 334 of file complete.c.
Referenced by append_to_match(), compare_match(), compute_lcd_of_matches(), make_quoted_replacement(), print_filename(), printable_part(), rl_complete_internal(), rl_display_match_list(), rl_filename_completion_function(), rl_menu_complete(), rl_old_menu_complete(), rl_username_completion_function(), and set_completion_defaults().
rl_filename_dequoting_function
rl_dequote_func_t* rl_filename_dequoting_function = (rl_dequote_func_t *)NULL
Definition at line 364 of file complete.c.
Referenced by compare_match(), compute_lcd_of_matches(), and rl_filename_completion_function().
rl_filename_quote_characters
const char* rl_filename_quote_characters = (const char *)NULL
Definition at line 321 of file complete.c.
Referenced by make_quoted_replacement().
rl_filename_quoting_desired
int rl_filename_quoting_desired = 1
Definition at line 341 of file complete.c.
Referenced by compare_match(), compute_lcd_of_matches(), make_quoted_replacement(), and set_completion_defaults().
rl_filename_quoting_function
rl_quote_func_t* rl_filename_quoting_function = rl_quote_filename
Definition at line 358 of file complete.c.
Referenced by make_quoted_replacement().
rl_filename_rewrite_hook
rl_dequote_func_t* rl_filename_rewrite_hook = (rl_dequote_func_t *)NULL
Definition at line 256 of file complete.c.
Referenced by rl_filename_completion_function().
rl_filename_stat_hook
rl_icppfunc_t* rl_filename_stat_hook = (rl_icppfunc_t *)NULL
Definition at line 245 of file complete.c.
Referenced by _rl_print_color_indicator(), append_to_match(), print_filename(), and stat_char().
rl_ignore_completion_duplicates
int rl_ignore_completion_duplicates = 1
Definition at line 329 of file complete.c.
Referenced by postprocess_matches(), and rl_display_match_list().
rl_ignore_some_completions_function
rl_compignore_func_t* rl_ignore_some_completions_function = (rl_compignore_func_t *)NULL
Definition at line 352 of file complete.c.
Referenced by postprocess_matches(), rl_restore_state(), and rl_save_state().
rl_inhibit_completion
int rl_inhibit_completion
Definition at line 405 of file complete.c.
Referenced by rl_complete().
rl_menu_completion_entry_function
rl_compentry_func_t* rl_menu_completion_entry_function = (rl_compentry_func_t *)NULL
Definition at line 268 of file complete.c.
Referenced by rl_menu_complete(), rl_old_menu_complete(), rl_restore_state(), and rl_save_state().
rl_sort_completion_matches
int rl_sort_completion_matches = 1
Definition at line 411 of file complete.c.
Referenced by compute_lcd_of_matches(), remove_duplicate_matches(), and rl_display_match_list().
rl_special_prefixes
const char* rl_special_prefixes = (const char *)NULL
Definition at line 326 of file complete.c.
Referenced by _rl_find_completion_word().
rl_visible_stats
int rl_visible_stats = 0
Definition at line 235 of file complete.c.
Referenced by print_filename().