Fennix: Userspace/apps/base/busybox/mailutils/makemime.c File Reference
makemime.c File Reference
#include "libbb.h"
#include "mail.h"
Macros
#define dbg_error_msg(...) ((void)0)
#define boundary opt_output
Functions
int makemime_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
boundary
#define boundary opt_output
dbg_error_msg
#define dbg_error_msg (...) ((void)0)
Definition at line 25 of file makemime.c.
Function Documentation
makemime_main()
int makemime_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 174 of file makemime.c.
 {
     unsigned opts;
     llist_t *opt_headers = NULL, *l;
     const char *opt_output;
     const char *content_type = "application/octet-stream";
 #define boundary opt_output
     enum {
         OPT_c = 1 << 0,         // create (non-multipart) section
         OPT_e = 1 << 1,         // Content-Transfer-Encoding. Ignored. Assumed base64
         OPT_o = 1 << 2,         // output to
         OPT_C = 1 << 3,         // charset
         OPT_N = 1 << 4,         // COMPAT
         OPT_a = 1 << 5,         // additional headers
         //OPT_m = 1 << 6,         // create mutipart section
         //OPT_j = 1 << 7,         // join section to multipart section
     };
     INIT_G();
     // parse options
     opts = getopt32(argv,
         "c:e:o:C:N:a:*", // "m:j:",
         &content_type, NULL, &opt_output, &G.opt_charset, NULL, &opt_headers //, NULL, NULL
     );
     //argc -= optind;
     argv += optind;
     // respect -o output
     if (opts & OPT_o)
         freopen(opt_output, "w", stdout);
     // no files given on command line? -> use stdin
     if (!*argv)
         *--argv = (char *)"-";
     // put additional headers
     for (l = opt_headers; l; l = l->link)
         puts(l->data);
     // make a random string -- it will delimit message parts
     srand(monotonic_us());
     boundary = xasprintf("%u-%u-%u",
             (unsigned)rand(), (unsigned)rand(), (unsigned)rand());
     // put multipart header
     printf(
         "Mime-Version: 1.0\n"
         "Content-Type: multipart/mixed; boundary=\"%s\"\n"
         , boundary
     );
     // put attachments
     while (*argv) {
         printf(
             "\n--%s\n"
             "Content-Type: %s; charset=%s\n"
             "Content-Disposition: inline; filename=\"%s\"\n"
             "Content-Transfer-Encoding: base64\n"
             , boundary
             , content_type
             , G.opt_charset
             , bb_get_last_path_component_strip(*argv)
         );
         printfile_base64(*argv++);
     }
     // put multipart footer
     printf("\n--%s--\n" "\n", boundary);
     return EXIT_SUCCESS;
 #undef boundary
 }
References argv, bb_get_last_path_component_strip(), boundary, EXIT_SUCCESS, freopen(), G(), getopt32(), INIT_G, l, monotonic_us(), NULL, OPT_a, OPT_C, OPT_c, OPT_e, OPT_N, OPT_o, optind, printf, printfile_base64(), puts(), rand(), srand(), stdout, and xasprintf().