Fennix Userspace: anonymous_namespace{pwd-stubs.cpp} Namespace Reference
anonymous_namespace{pwd-stubs.cpp} Namespace Reference
Functions
bool open_global_file ()
void close_global_file ()
bool extract_entry (frg::string_view line, passwd *entry)
void copy_to_buffer (passwd *pwd, char *buffer, size_t size)
void clear_entry (passwd *entry)
Variables
FILE * global_file
Function Documentation
clear_entry()
void anonymous_namespace{pwd-stubs.cpp}::clear_entry (passwd * entry)
Definition at line 107 of file pwd-stubs.cpp.
{
         free(entry->pw_name);
         free(entry->pw_dir);
         free(entry->pw_passwd);
         free(entry->pw_shell);
         entry->pw_name = nullptr;
         entry->pw_dir = nullptr;
         entry->pw_passwd = nullptr;
         entry->pw_shell = nullptr;
     }
References free.
Referenced by getpwent(), getpwnam(), and getpwuid().
close_global_file()
void anonymous_namespace{pwd-stubs.cpp}::close_global_file ()
Definition at line 25 of file pwd-stubs.cpp.
{
         if(global_file) {
             fclose(global_file);
             global_file = nullptr;
         }
     }
References fclose(), and global_file.
Referenced by endpwent().
copy_to_buffer()
void anonymous_namespace{pwd-stubs.cpp}::copy_to_buffer (passwd * pwd, char * buffer, size_t size)
Definition at line 88 of file pwd-stubs.cpp.
{
         char *pw_dir = stpcpy(buffer, pwd->pw_name) + 1;
         free(pwd->pw_name);
         pwd->pw_name = buffer;
         char *pw_shell = stpcpy(pw_dir, pwd->pw_dir) + 1;
         free(pwd->pw_dir);
         pwd->pw_dir = pw_dir;
         char *pw_passwd = stpcpy(pw_shell, pwd->pw_shell) + 1;
         free(pwd->pw_shell);
         pwd->pw_shell = pw_shell;
         char *end = stpcpy(pw_passwd, pwd->pw_passwd);
         __ensure(end <= buffer + size);
         free(pwd->pw_passwd);
         pwd->pw_passwd = pw_passwd;
     }
References __ensure, buffer, free, passwd::pw_dir, passwd::pw_name, passwd::pw_passwd, passwd::pw_shell, size, and stpcpy().
Referenced by getpwnam_r(), and getpwuid_r().
extract_entry()
bool anonymous_namespace{pwd-stubs.cpp}::extract_entry (frg::string_view line, passwd * entry)
Definition at line 32 of file pwd-stubs.cpp.
{
         frg::string_view segments[8];
         // Parse the line into 7 or 8 segments.
         size_t s = 0;
         int n;
         for(n = 0; n < 7; n++) {
             size_t d = line.find_first(':', s);
             if(d == size_t(-1))
                 break;
             segments[n] = line.sub_string(s, d - s);
             s = d + 1;
         }
         if(line.find_first(':', s) != size_t(-1))
             return false;
         segments[n] = line.sub_string(s, line.size() - s);
         n++;
         if(n < 7)
             return false;
         // TODO: Handle strndup() failure.
         auto name = strndup(segments[0].data(), segments[0].size());
         __ensure(name);
         auto passwd = strndup(segments[1].data(), segments[1].size());
         __ensure(passwd);
         auto uid = segments[2].to_number<int>();
         if(!uid)
             return false;
         auto gid = segments[3].to_number<int>();
         if(!gid)
             return false;
         auto real_name = strndup(segments[4].data(), segments[4].size());
         __ensure(real_name);
         auto dir = strndup(segments[5].data(), segments[5].size());
         __ensure(dir);
         auto shell = strndup(segments[6].data(), segments[6].size());
         __ensure(shell);
         // Chop the newline off the end of shell
         __ensure(strlen(shell) > 0);
         shell[strlen(shell) - 1] = '\0';
         entry->pw_name = name;
         entry->pw_passwd = passwd;
         entry->pw_uid = *uid;
         entry->pw_gid = *gid;
         entry->pw_dir = dir;
         entry->pw_shell = shell;
         entry->pw_gecos = real_name;
         return true;
     }
References __ensure, line, n, name, size, strlen(), and strndup().
Referenced by getpwent(), getpwnam(), getpwnam_r(), getpwuid(), and getpwuid_r().
open_global_file()
bool anonymous_namespace{pwd-stubs.cpp}::open_global_file ()
Definition at line 13 of file pwd-stubs.cpp.
{
         if(!global_file) {
             global_file = fopen("/etc/passwd", "r");
             if(!global_file) {
                 errno = EIO;
                 return false;
             }
         }
         return true;
     }
References EIO, errno, fopen(), and global_file.
Referenced by getpwent(), and setpwent().
Variable Documentation
global_file
FILE* anonymous_namespace{pwd-stubs.cpp}::global_file
Definition at line 11 of file pwd-stubs.cpp.
Referenced by close_global_file(), getpwent(), open_global_file(), and setpwent().