Fennix Userspace: Userspace/apps/base/bash/lib/readline/parens.c File Reference
parens.c File Reference
#include "rlconf.h"
#include <stdio.h>
#include <sys/types.h>
#include "posixselect.h"
#include <strings.h>
#include "readline.h"
#include "rlprivate.h"
Macros
#define READLINE_LIBRARY
Functions
char * strchr ()
char * strrchr ()
static int find_matching_open (char *, int, int)
void _rl_enable_paren_matching (int on_or_off)
int rl_set_paren_blink_timeout (int u)
int rl_insert_close (int count, int invoking_key)
Variables
int rl_blink_matching_paren = 0
static int _paren_blink_usec = 500000
Macro Definition Documentation
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file parens.c.
Function Documentation
_rl_enable_paren_matching()
void _rl_enable_paren_matching (int on_or_off)
Definition at line 67 of file parens.c.
 {
   if (on_or_off)
     {
       /* ([{ */
       rl_bind_key_in_map (')', rl_insert_close, emacs_standard_keymap);
       rl_bind_key_in_map (']', rl_insert_close, emacs_standard_keymap);
       rl_bind_key_in_map ('}', rl_insert_close, emacs_standard_keymap);
 #if defined (VI_MODE)
       /* ([{ */
       rl_bind_key_in_map (')', rl_insert_close, vi_insertion_keymap);
       rl_bind_key_in_map (']', rl_insert_close, vi_insertion_keymap);
       rl_bind_key_in_map ('}', rl_insert_close, vi_insertion_keymap);
 #endif
     }
   else
     {
       /* ([{ */
       rl_bind_key_in_map (')', rl_insert, emacs_standard_keymap);
       rl_bind_key_in_map (']', rl_insert, emacs_standard_keymap);
       rl_bind_key_in_map ('}', rl_insert, emacs_standard_keymap);
 #if defined (VI_MODE)
       /* ([{ */
       rl_bind_key_in_map (')', rl_insert, vi_insertion_keymap);
       rl_bind_key_in_map (']', rl_insert, vi_insertion_keymap);
       rl_bind_key_in_map ('}', rl_insert, vi_insertion_keymap);
 #endif
     }
 }
References emacs_standard_keymap, rl_bind_key_in_map(), rl_insert(), rl_insert_close(), and vi_insertion_keymap.
Referenced by hack_special_boolean_var().
find_matching_open()
static int find_matching_open (char * string, int from, int closer) static
Definition at line 152 of file parens.c.
 {
   register int i;
   int opener, level, delimiter;
   switch (closer)
     {
     case ']': opener = '['; break;
     case '}': opener = '{'; break;
     case ')': opener = '('; break;
     default:
       return (-1);
     }
   level = 1;            /* The closer passed in counts as 1. */
   delimiter = 0;        /* Delimited state unknown. */
   for (i = from; i > -1; i--)
     {
       if (delimiter && (string[i] == delimiter))
     delimiter = 0;
       else if (rl_basic_quote_characters && strchr (rl_basic_quote_characters, string[i]))
     delimiter = string[i];
       else if (!delimiter && (string[i] == closer))
     level++;
       else if (!delimiter && (string[i] == opener))
     level--;
       if (!level)
     break;
     }
   return (i);
 }
References i, rl_basic_quote_characters, and strchr().
Referenced by rl_insert_close().
rl_insert_close()
int rl_insert_close (int count, int invoking_key)
Definition at line 111 of file parens.c.
 {
   if (rl_explicit_arg || !rl_blink_matching_paren)
     _rl_insert_char (count, invoking_key);
   else
     {
 #if defined (HAVE_SELECT)
       int orig_point, match_point, ready;
       struct timeval timer;
       fd_set readfds;
       _rl_insert_char (1, invoking_key);
       (*rl_redisplay_function) ();
       match_point =
     find_matching_open (rl_line_buffer, rl_point - 2, invoking_key);
       /* Emacs might message or ring the bell here, but I don't. */
       if (match_point < 0)
     return 1;
       FD_ZERO (&readfds);
       FD_SET (fileno (rl_instream), &readfds);
       USEC_TO_TIMEVAL (_paren_blink_usec, timer);
       orig_point = rl_point;
       rl_point = match_point;
       (*rl_redisplay_function) ();
 #  if defined (RL_TIMEOUT_USE_SELECT)
       ready = _rl_timeout_select (1, &readfds, (fd_set *)NULL, (fd_set *)NULL, &timer, NULL);
 #  else
       ready = select (1, &readfds, (fd_set *)NULL, (fd_set *)NULL, &timer);
 #  endif
       rl_point = orig_point;
 #else /* !HAVE_SELECT */
       _rl_insert_char (count, invoking_key);
 #endif /* !HAVE_SELECT */
     }
   return 0;
 }
References _paren_blink_usec, _rl_insert_char(), _rl_timeout_select(), count, FD_SET, FD_ZERO, fileno(), find_matching_open(), NULL, rl_blink_matching_paren, rl_explicit_arg, rl_instream, rl_line_buffer, rl_point, select(), and USEC_TO_TIMEVAL.
Referenced by _rl_enable_paren_matching().
rl_set_paren_blink_timeout()
int rl_set_paren_blink_timeout (int u)
Definition at line 100 of file parens.c.
 {
   int o;
   o = _paren_blink_usec;
   if (u > 0)
     _paren_blink_usec = u;
   return (o);
 }
References _paren_blink_usec.
strchr()
char* strchr ()
Referenced by find_matching_open().
strrchr()
char * strrchr ()
Variable Documentation
_paren_blink_usec
int _paren_blink_usec = 500000 static
Definition at line 62 of file parens.c.
Referenced by rl_insert_close(), and rl_set_paren_blink_timeout().
rl_blink_matching_paren
int rl_blink_matching_paren = 0
Definition at line 60 of file parens.c.
Referenced by hack_special_boolean_var(), and rl_insert_close().