Fennix: Userspace/apps/base/busybox/coreutils/uuencode.c File Reference
uuencode.c File Reference
#include "libbb.h"
Enumerations
enum { SRC_BUF_SIZE = 15*3 , DST_BUF_SIZE = 4 * ((SRC_BUF_SIZE + 2) / 3) }
Functions
int uuencode_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SRC_BUF_SIZE
DST_BUF_SIZE
Definition at line 35 of file uuencode.c.
      {
     SRC_BUF_SIZE = 15*3,  /* This *MUST* be a multiple of 3 */
     DST_BUF_SIZE = 4 * ((SRC_BUF_SIZE + 2) / 3),
 };
Function Documentation
uuencode_main()
int uuencode_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 41 of file uuencode.c.
 {
     struct stat stat_buf;
     int src_fd = STDIN_FILENO;
     const char *tbl;
     mode_t mode;
     char src_buf[SRC_BUF_SIZE];
     char dst_buf[DST_BUF_SIZE + 1];
     tbl = bb_uuenc_tbl_std;
     mode = 0666 & ~umask(0666);
     if (getopt32(argv, "^" "m" "\0" "-1:?2"/*must have 1 or 2 args*/)) {
         tbl = bb_uuenc_tbl_base64;
     }
     argv += optind;
     if (argv[1]) {
         src_fd = xopen(argv[0], O_RDONLY);
         fstat(src_fd, &stat_buf);
         mode = stat_buf.st_mode & (S_IRWXU | S_IRWXG | S_IRWXO);
         argv++;
     }
     printf("begin%s %o %s", tbl == bb_uuenc_tbl_std ? "" : "-base64", mode, *argv);
     while (1) {
         size_t size = full_read(src_fd, src_buf, SRC_BUF_SIZE);
         if (!size)
             break;
         if ((ssize_t)size < 0)
             bb_simple_perror_msg_and_die(bb_msg_read_error);
         /* Encode the buffer we just read in */
         bb_uuencode(dst_buf, src_buf, size, tbl);
         bb_putchar('\n');
         if (tbl == bb_uuenc_tbl_std) {
             bb_putchar(tbl[size]);
         }
         fflush(stdout);
         xwrite(STDOUT_FILENO, dst_buf, 4 * ((size + 2) / 3));
     }
     printf(tbl == bb_uuenc_tbl_std ? "\n`\nend\n" : "\n====\n");
     fflush_stdout_and_exit_SUCCESS();
 }
References argv, bb_msg_read_error, bb_putchar(), bb_simple_perror_msg_and_die(), bb_uuencode(), DST_BUF_SIZE, fflush(), fflush_stdout_and_exit_SUCCESS(), fstat(), full_read(), getopt32(), O_RDONLY, optind, printf, S_IRWXG, S_IRWXO, S_IRWXU, size, src_buf, SRC_BUF_SIZE, stat::st_mode, STDIN_FILENO, stdout, STDOUT_FILENO, umask(), xopen(), and xwrite().