Fennix Userspace: Userspace/musl/src/stdio/vswscanf.c File Reference
vswscanf.c File Reference
#include "stdio_impl.h"
#include <wchar.h>
Functions
static size_t wstring_read (FILE *f, unsigned char *buf, size_t len)
int vswscanf (const wchar_t *restrict s, const wchar_t *restrict fmt, va_list ap)
weak_alias (vswscanf, __isoc99_vswscanf)
Function Documentation
vswscanf()
int vswscanf (const wchar_t *restrict s, const wchar_t *restrict fmt, va_list ap)
Definition at line 27 of file vswscanf.c.
 {
     unsigned char buf[256];
     FILE f = {
         .buf = buf, .buf_size = sizeof buf,
         .cookie = (void *)s,
         .read = wstring_read, .lock = -1
     };
     return vfwscanf(&f, fmt, ap);
 }
References ap, buf, _IO_FILE::buf, f, lock, read(), s, vfwscanf(), and wstring_read().
weak_alias()
weak_alias (vswscanf , __isoc99_vswscanf)
wstring_read()
static size_t wstring_read (FILE * f, unsigned char * buf, size_t len) static
Definition at line 4 of file vswscanf.c.
 {
     const wchar_t *src = f->cookie;
     size_t k;
     if (!src) return 0;
     k = wcsrtombs((void *)f->buf, &src, f->buf_size, 0);
     if (k==(size_t)-1) {
         f->rpos = f->rend = 0;
         return 0;
     }
     f->rpos = f->buf;
     f->rend = f->buf + k;
     f->cookie = (void *)src;
     if (!len || !k) return 0;
     *buf = *f->rpos++;
     return 1;
 }
References buf, _IO_FILE::buf, _IO_FILE::buf_size, _IO_FILE::cookie, f, k, _IO_FILE::rend, _IO_FILE::rpos, src, and wcsrtombs().
Referenced by vswscanf().