Fennix Userspace: Userspace/apps/base/busybox/coreutils/tail.c File Reference
tail.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
#define header_fmt_str "\n==> %s <==\n"
#define FOLLOW (opt & 0x1)
#define COUNT_BYTES (opt & 0x2)
#define FOLLOW_RETRY 0
Functions
static void tail_xprint_header (const char *fmt, const char *filename)
static ssize_t tail_read (int fd, char *buf, size_t count)
static unsigned eat_num (const char *p)
int tail_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
COUNT_BYTES
#define COUNT_BYTES (opt & 0x2)
FOLLOW
#define FOLLOW (opt & 0x1)
FOLLOW_RETRY
#define FOLLOW_RETRY 0
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 78 of file tail.c.
header_fmt_str
#define header_fmt_str "\n==> %s <==\n"
Definition at line 100 of file tail.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 79 of file tail.c.
Function Documentation
eat_num()
static unsigned eat_num (const char * p) static
Definition at line 102 of file tail.c.
 {
     if (*p == '-')
         p++;
     else if (*p == '+') {
         p++;
         G.from_top = 1;
     }
     return xatou_sfx(p, bkm_suffixes);
 }
References bkm_suffixes, G, and p.
Referenced by tail_main().
tail_main()
int tail_main (int argc, char ** argv)
Definition at line 114 of file tail.c.
 {
     unsigned count = 10;
     unsigned sleep_period = 1;
     const char *str_c, *str_n;
     char *tailbuf;
     size_t tailbufsize;
     unsigned header_threshold = 1;
     unsigned nfiles;
     int i, opt;
     int *fds;
     const char *fmt;
     int prev_fd;
     INIT_G();
 #if ENABLE_INCLUDE_SUSv2 || ENABLE_FEATURE_FANCY_TAIL
     /* Allow legacy syntax of an initial numeric option without -n. */
     if (argv[1] && (argv[1][0] == '+' || argv[1][0] == '-')
      && isdigit(argv[1][1])
     ) {
         count = eat_num(argv[1]);
         argv++;
         argc--;
     }
 #endif
     /* -s NUM, -F imlies -f */
     opt = getopt32(argv, IF_FEATURE_FANCY_TAIL("^")
             "fc:n:"IF_FEATURE_FANCY_TAIL("qs:+vF")
             IF_FEATURE_FANCY_TAIL("\0" "Ff"),
             &str_c, &str_n IF_FEATURE_FANCY_TAIL(,&sleep_period)
     );
 #define FOLLOW (opt & 0x1)
 #define COUNT_BYTES (opt & 0x2)
     //if (opt & 0x1) // -f
     if (opt & 0x2) count = eat_num(str_c); // -c
     if (opt & 0x4) count = eat_num(str_n); // -n
 #if ENABLE_FEATURE_FANCY_TAIL
     /* q: make it impossible for nfiles to be > header_threshold */
     if (opt & 0x8) header_threshold = UINT_MAX; // -q
     //if (opt & 0x10) // -s
     if (opt & 0x20) header_threshold = 0; // -v
 # define FOLLOW_RETRY (opt & 0x40)
 #else
 # define FOLLOW_RETRY 0
 #endif
     argc -= optind;
     argv += optind;
     /* open all the files */
     fds = xmalloc(sizeof(fds[0]) * (argc + 1));
     if (!argv[0]) {
         struct stat statbuf;
         if (fstat(STDIN_FILENO, &statbuf) == 0
          && S_ISFIFO(statbuf.st_mode)
         ) {
             opt &= ~1; /* clear FOLLOW */
         }
         argv[0] = (char *) bb_msg_standard_input;
     }
     nfiles = i = 0;
     do {
         int fd = open_or_warn_stdin(argv[i]);
         if (fd < 0 && !FOLLOW_RETRY) {
             G.exitcode = EXIT_FAILURE;
             continue;
         }
         fds[nfiles] = fd;
         argv[nfiles++] = argv[i];
     } while (++i < argc);
     if (!nfiles)
         bb_simple_error_msg_and_die("no files");
     /* prepare the buffer */
     tailbufsize = BUFSIZ;
     if (!G.from_top && COUNT_BYTES) {
         if (tailbufsize < count + BUFSIZ) {
             tailbufsize = count + BUFSIZ;
         }
     }
     /* tail -c1024m REGULAR_FILE doesn't really need 1G mem block.
      * (In fact, it doesn't need ANY memory). So delay allocation.
      */
     tailbuf = NULL;
     /* tail the files */
     fmt = header_fmt_str + 1; /* skip leading newline in the header on the first output */
     i = 0;
     do {
         char *buf;
         int taillen;
         int newlines_seen;
         unsigned seen;
         int nread;
         int fd = fds[i];
         if (ENABLE_FEATURE_FANCY_TAIL && fd < 0)
             continue; /* may happen with -F */
         if (nfiles > header_threshold) {
             tail_xprint_header(fmt, argv[i]);
             fmt = header_fmt_str;
         }
         if (!G.from_top) {
             off_t current = lseek(fd, 0, SEEK_END);
             if (current > 0) {
                 unsigned off;
                 if (COUNT_BYTES) {
                 /* Optimizing count-bytes case if the file is seekable.
                  * Beware of backing up too far.
                  * Also we exclude files with size 0 (because of /proc/xxx) */
                     if (count == 0)
                         continue; /* showing zero bytes is easy :) */
                     current -= count;
                     if (current < 0)
                         current = 0;
                     xlseek(fd, current, SEEK_SET);
                     bb_copyfd_size(fd, STDOUT_FILENO, count);
                     continue;
                 }
 #if 1 /* This is technically incorrect for *LONG* strings, but very useful */
                 /* Optimizing count-lines case if the file is seekable.
                  * We assume the lines are <64k.
                  * (Users complain that tail takes too long
                  * on multi-gigabyte files) */
                 off = (count | 0xf); /* for small counts, be more paranoid */
                 if (off > (INT_MAX / (64*1024)))
                     off = (INT_MAX / (64*1024));
                 current -= off * (64*1024);
                 if (current < 0)
                     current = 0;
                 xlseek(fd, current, SEEK_SET);
 #endif
             }
         }
         if (!tailbuf)
             tailbuf = xmalloc(tailbufsize);
         buf = tailbuf;
         taillen = 0;
         /* "We saw 1st line/byte".
          * Used only by +N code ("start from Nth", 1-based): */
         seen = 1;
         newlines_seen = 0;
         while ((nread = tail_read(fd, buf, tailbufsize - taillen)) > 0) {
             if (G.from_top) {
                 int nwrite = nread;
                 if (seen < count) {
                     /* We need to skip a few more bytes/lines */
                     if (COUNT_BYTES) {
                         nwrite -= (count - seen);
                         seen += nread;
                     } else {
                         char *s = buf;
                         do {
                             --nwrite;
                             if (*s++ == '\n' && ++seen == count) {
                                 break;
                             }
                         } while (nwrite);
                     }
                 }
                 if (nwrite > 0)
                     xwrite(STDOUT_FILENO, buf + nread - nwrite, nwrite);
             } else if (count) {
                 if (COUNT_BYTES) {
                     taillen += nread;
                     if (taillen > (int)count) {
                         memmove(tailbuf, tailbuf + taillen - count, count);
                         taillen = count;
                     }
                 } else {
                     int k = nread;
                     int newlines_in_buf = 0;
                     do { /* count '\n' in last read */
                         k--;
                         if (buf[k] == '\n') {
                             newlines_in_buf++;
                         }
                     } while (k);
                     if (newlines_seen + newlines_in_buf < (int)count) {
                         newlines_seen += newlines_in_buf;
                         taillen += nread;
                     } else {
                         int extra = (buf[nread-1] != '\n');
                         char *s;
                         k = newlines_seen + newlines_in_buf + extra - count;
                         s = tailbuf;
                         while (k) {
                             if (*s == '\n') {
                                 k--;
                             }
                             s++;
                         }
                         taillen += nread - (s - tailbuf);
                         memmove(tailbuf, s, taillen);
                         newlines_seen = count - extra;
                     }
                     if (tailbufsize < (size_t)taillen + BUFSIZ) {
                         tailbufsize = taillen + BUFSIZ;
                         tailbuf = xrealloc(tailbuf, tailbufsize);
                     }
                 }
                 buf = tailbuf + taillen;
             }
         } /* while (tail_read() > 0) */
         if (!G.from_top) {
             xwrite(STDOUT_FILENO, tailbuf, taillen);
         }
     } while (++i < nfiles);
     prev_fd = fds[i-1];
     tailbuf = xrealloc(tailbuf, BUFSIZ);
     fmt = NULL;
     if (FOLLOW) while (1) {
         sleep(sleep_period);
         i = 0;
         do {
             int nread;
             const char *filename = argv[i];
             int fd = fds[i];
             int new_fd = -1;
             struct stat sbuf;
             if (FOLLOW_RETRY) {
                 struct stat fsbuf;
                 if (fd < 0
                  || fstat(fd, &fsbuf) < 0
                  || stat(filename, &sbuf) < 0
                  || fsbuf.st_dev != sbuf.st_dev
                  || fsbuf.st_ino != sbuf.st_ino
                 ) {
                     /* Looks like file has been created/renamed/deleted */
                     new_fd = open(filename, O_RDONLY);
                     if (new_fd >= 0) {
                         bb_error_msg("%s has %s; following end of new file",
                             filename, (fd < 0) ? "appeared" : "been replaced"
                         );
                         if (fd < 0) {
                             /* No previously open fd for this file,
                              * start using new_fd immediately. */
                             fds[i] = fd = new_fd;
                             new_fd = -1;
                         }
                     } else if (fd >= 0) {
                         bb_perror_msg("%s has been renamed or deleted", filename);
                     }
                 }
             }
             if (ENABLE_FEATURE_FANCY_TAIL && fd < 0)
                 continue;
             if (nfiles > header_threshold) {
                 fmt = header_fmt_str;
             }
             for (;;) {
                 /* tail -f keeps following files even if they are truncated */
                 /* /proc files report zero st_size, don't lseek them */
                 if (fstat(fd, &sbuf) == 0
                  /* && S_ISREG(sbuf.st_mode) TODO? */
                  && sbuf.st_size > 0
                 ) {
                     off_t current = lseek(fd, 0, SEEK_CUR);
                     if (sbuf.st_size < current) {
                         //bb_perror_msg("%s: file truncated", filename); - says coreutils 8.32
                         xlseek(fd, 0, SEEK_SET);
                     }
                 }
                 nread = tail_read(fd, tailbuf, BUFSIZ);
                 if (nread <= 0) {
                     if (new_fd < 0)
                         break;
                     /* Switch to "tail -F"ing the new file */
                     xmove_fd(new_fd, fd);
                     new_fd = -1;
                     continue;
                 }
                 if (fmt && (fd != prev_fd)) {
                     tail_xprint_header(fmt, filename);
                     fmt = NULL;
                     prev_fd = fd;
                 }
                 xwrite(STDOUT_FILENO, tailbuf, nread);
             }
         } while (++i < nfiles);
     } /* while (1) */
     if (ENABLE_FEATURE_CLEAN_UP) {
         free(fds);
         free(tailbuf);
     }
     return G.exitcode;
 }
References argc, argv, bb_copyfd_size(), bb_error_msg(), bb_perror_msg(), bb_simple_error_msg_and_die(), buf, BUFSIZ, count, COUNT_BYTES, current, eat_num(), EXIT_FAILURE, fd, filename, FOLLOW, FOLLOW_RETRY, free, fstat(), G, getopt32(), header_fmt_str, i, INIT_G, INT_MAX, isdigit, k, lseek(), memmove(), NULL, O_RDONLY, off, off_t, open(), open_or_warn_stdin(), opt, optind, s, S_ISFIFO, SEEK_CUR, SEEK_END, SEEK_SET, sleep(), stat::st_dev, stat::st_ino, stat::st_mode, stat::st_size, stat(), STDIN_FILENO, STDOUT_FILENO, tail_read(), tail_xprint_header(), UINT_MAX, xlseek(), xmalloc, xmove_fd(), xrealloc, and xwrite().
tail_read()
static ssize_t tail_read (int fd, char * buf, size_t count) static
Definition at line 87 of file tail.c.
 {
     ssize_t r;
     r = full_read(fd, buf, count);
     if (r < 0) {
         bb_simple_perror_msg(bb_msg_read_error);
         G.exitcode = EXIT_FAILURE;
     }
     return r;
 }
References bb_msg_read_error, bb_simple_perror_msg(), buf, count, EXIT_FAILURE, fd, full_read(), and G.
Referenced by tail_main().
tail_xprint_header()
static void tail_xprint_header (const char * fmt, const char * filename) static
Definition at line 81 of file tail.c.
 {
     if (fdprintf(STDOUT_FILENO, fmt, filename) < 0)
         bb_perror_nomsg_and_die();
 }
References bb_perror_nomsg_and_die(), fdprintf, filename, and STDOUT_FILENO.
Referenced by tail_main().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING