Fennix: Userspace/musl/src/env/__libc_start_main.c File Reference
__libc_start_main.c File Reference
#include <elf.h>
#include <poll.h>
#include <fcntl.h>
#include <signal.h>
#include <unistd.h>
#include "syscall.h"
#include "atomic.h"
#include "libc.h"
Macros
#define AUX_CNT 38
Typedefs
typedef int lsm2_fn(int(*) (int, char **, char **), int, char **)
Functions
static void dummy (void)
weak_alias (dummy, _init)
static void dummy1 (void *p)
weak_alias (dummy1, __init_ssp)
void __init_libc (char **envp, char *pn)
static void libc_start_init (void)
weak_alias (libc_start_init, __libc_start_init)
int __libc_start_main (int(*main)(int, char **, char **), int argc, char **argv, void(*init_dummy)(), void(*fini_dummy)(), void(*ldso_dummy)())
static int libc_start_main_stage2 (int(*main)(int, char **, char **), int argc, char **argv)
Variables
weak hidden void(*const __init_array_start)(void)
weak hidden void(*const)(*const) __init_array_end (void)
static lsm2_fn libc_start_main_stage2
Macro Definition Documentation
AUX_CNT
#define AUX_CNT 38
Definition at line 18 of file __libc_start_main.c.
Typedef Documentation
lsm2_fn
typedef int lsm2_fn(int(*)(int, char **, char **), int, char **)
Definition at line 69 of file __libc_start_main.c.
Function Documentation
__init_libc()
void __init_libc (char ** envp, char * pn)
Definition at line 23 of file __libc_start_main.c.
 {
     size_t i, *auxv, aux[AUX_CNT] = { 0 };
     __environ = envp;
     for (i=0; envp[i]; i++);
     libc.auxv = auxv = (void *)(envp+i+1);
     for (i=0; auxv[i]; i+=2) if (auxv[i]<AUX_CNT) aux[auxv[i]] = auxv[i+1];
     __hwcap = aux[AT_HWCAP];
     if (aux[AT_SYSINFO]) __sysinfo = aux[AT_SYSINFO];
     libc.page_size = aux[AT_PAGESZ];
     if (!pn) pn = (void*)aux[AT_EXECFN];
     if (!pn) pn = "";
     __progname = __progname_full = pn;
     for (i=0; pn[i]; i++) if (pn[i]=='/') __progname = pn+i+1;
     __init_tls(aux);
     __init_ssp((void *)aux[AT_RANDOM]);
     if (aux[AT_UID]==aux[AT_EUID] && aux[AT_GID]==aux[AT_EGID]
         && !aux[AT_SECURE]) return;
     struct pollfd pfd[3] = { {.fd=0}, {.fd=1}, {.fd=2} };
     int r =
 #ifdef SYS_poll
     __syscall(SYS_poll, pfd, 3, 0);
 #else
     __syscall(SYS_ppoll, pfd, 3, &(struct timespec){0}, 0, _NSIG/8);
 #endif
     if (r<0) a_crash();
     for (i=0; i<3; i++) if (pfd[i].revents&POLLNVAL)
         if (__sys_open("/dev/null", O_RDWR)<0)
             a_crash();
     libc.secure = 1;
 }
References __environ, __hwcap, __init_ssp(), __init_tls(), __progname, __progname_full, __sys_open, __syscall, __sysinfo, _NSIG, a_crash, AT_EGID, AT_EUID, AT_EXECFN, AT_GID, AT_HWCAP, AT_PAGESZ, AT_RANDOM, AT_SECURE, AT_SYSINFO, AT_UID, AUX_CNT, i, libc, O_RDWR, pfd, POLLNVAL, pollfd::revents, and SYS_ppoll.
Referenced by __libc_start_main().
__libc_start_main()
int __libc_start_main (int(*)(int, char **, char **) main, int argc, char ** argv, void(*)() init_dummy, void(*)() fini_dummy, void(*)() ldso_dummy)
Definition at line 72 of file __libc_start_main.c.
 {
     char **envp = argv+argc+1;
     /* External linkage, and explicit noinline attribute if available,
      * are used to prevent the stack frame used during init from
      * persisting for the entire process lifetime. */
     __init_libc(envp, argv[0]);
     /* Barrier against hoisting application code or anything using ssp
      * or thread pointer prior to its initialization above. */
     lsm2_fn *stage2 = libc_start_main_stage2;
     __asm__ ( "" : "+r"(stage2) : : "memory" );
     return stage2(main, argc, argv);
 }
References __asm__(), __init_libc(), argc, argv, libc_start_main_stage2, and main().
dummy()
static void dummy (void) static
Definition at line 10 of file __libc_start_main.c.
 {}
dummy1()
static void dummy1 (void * p) static
Definition at line 15 of file __libc_start_main.c.
 {}
libc_start_init()
static void libc_start_init (void) static
Definition at line 59 of file __libc_start_main.c.
 {
     _init();
     uintptr_t a = (uintptr_t)&__init_array_start;
     for (; a<(uintptr_t)&__init_array_end; a+=sizeof(void(*)()))
         (*(void (**)(void))a)();
 }
References __init_array_end, __init_array_start, _init(), and Driver::void().
libc_start_main_stage2()
static int libc_start_main_stage2 (int(*)(int, char **, char **) main, int argc, char ** argv) static
Definition at line 89 of file __libc_start_main.c.
 {
     char **envp = argv+argc+1;
     __libc_start_init();
     /* Pass control to the application */
     exit(main(argc, argv, envp));
     return 0;
 }
References __libc_start_init(), argc, argv, exit(), and main().
weak_alias() [1/3]
weak_alias (dummy , _init)
weak_alias() [2/3]
weak_alias (dummy1 , __init_ssp)
weak_alias() [3/3]
weak_alias (libc_start_init , __libc_start_init)
Variable Documentation
__init_array_end
weak hidden void(*const)(*const) __init_array_end(void) (void)
Definition at line 13 of file __libc_start_main.c.
Referenced by libc_start_init().
__init_array_start
weak hidden void(*const __init_array_start) (void) (void) extern
Definition at line 162 of file dynlink.c.
Referenced by libc_start_init().
libc_start_main_stage2
lsm2_fn libc_start_main_stage2 static
Definition at line 70 of file __libc_start_main.c.
Referenced by __libc_start_main().