Fennix: Userspace/apps/base/busybox/util-linux/volume_id/ocfs2.c File Reference
ocfs2.c File Reference
#include "volume_id_internal.h"
Data Structures
struct ocfs2_super_block
Macros
#define OCFS2_VOL_UUID_LEN 16
#define OCFS2_MAX_VOL_LABEL_LEN 64
#define OCFS2_SUPERBLOCK_OFFSET 0x2000
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_ocfs2 (struct volume_id *id)
Variables
struct ocfs2_super_block PACKED
Data Structure Documentation
ocfs2_super_block
struct ocfs2_super_block
Definition at line 39 of file ocfs2.c.
Data Fields
uint64_t i_atime
uint32_t i_atime_nsec
uint64_t i_blkno
uint32_t i_clusters
uint64_t i_ctime
uint32_t i_ctime_nsec
uint64_t i_dtime
uint32_t i_flags
uint32_t i_fs_generation
uint32_t i_generation
uint32_t i_gid
uint64_t i_last_eb_blk
uint16_t i_links_count
uint16_t i_mode
uint64_t i_mtime
uint32_t i_mtime_nsec
uint64_t i_pad1
uint32_t i_reserved0
uint64_t i_reserved1[9]
uint8_t i_signature[8]
uint64_t i_size
uint16_t i_suballoc_bit
int16_t i_suballoc_slot
uint32_t i_uid
uint32_t s_blocksize_bits
uint32_t s_checkinterval
uint32_t s_clustersize_bits
uint32_t s_creator_os
uint16_t s_errors
uint32_t s_feature_compat
uint32_t s_feature_incompat
uint32_t s_feature_ro_compat
uint64_t s_first_cluster_group
uint8_t s_label[OCFS2_MAX_VOL_LABEL_LEN]
uint64_t s_lastcheck
uint16_t s_major_rev_level
int16_t s_max_mnt_count
uint16_t s_max_slots
uint16_t s_minor_rev_level
uint16_t s_mnt_count
uint16_t s_reserved1
uint32_t s_reserved2
uint64_t s_root_blkno
uint16_t s_state
uint64_t s_system_dir_blkno
uint8_t s_uuid[OCFS2_VOL_UUID_LEN]
Macro Definition Documentation
OCFS2_MAX_VOL_LABEL_LEN
#define OCFS2_MAX_VOL_LABEL_LEN 64
Definition at line 31 of file ocfs2.c.
OCFS2_SUPERBLOCK_OFFSET
#define OCFS2_SUPERBLOCK_OFFSET 0x2000
Definition at line 32 of file ocfs2.c.
OCFS2_VOL_UUID_LEN
#define OCFS2_VOL_UUID_LEN 16
Definition at line 30 of file ocfs2.c.
off
#define off ((uint64_t)0)
Function Documentation
volume_id_probe_ocfs2()
int FAST_FUNC volume_id_probe_ocfs2 (struct volume_id * id)
Definition at line 89 of file ocfs2.c.
 {
 #define off ((uint64_t)0)
     struct ocfs2_super_block *os;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     os = volume_id_get_buffer(id, off + OCFS2_SUPERBLOCK_OFFSET, 0x200);
     if (os == NULL)
         return -1;
     if (memcmp(os->i_signature, "OCFSV2", 6) != 0) {
         return -1;
     }
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
 //  volume_id_set_label_raw(id, os->s_label, OCFS2_MAX_VOL_LABEL_LEN < VOLUME_ID_LABEL_SIZE ?
 //                  OCFS2_MAX_VOL_LABEL_LEN : VOLUME_ID_LABEL_SIZE);
     volume_id_set_label_string(id, os->s_label, OCFS2_MAX_VOL_LABEL_LEN < VOLUME_ID_LABEL_SIZE ?
                     OCFS2_MAX_VOL_LABEL_LEN : VOLUME_ID_LABEL_SIZE);
     volume_id_set_uuid(id, os->s_uuid, UUID_DCE);
     IF_FEATURE_BLKID_TYPE(id->type = "ocfs2";)
     return 0;
 }
References dbg, ocfs2_super_block::i_signature, memcmp(), NULL, OCFS2_MAX_VOL_LABEL_LEN, OCFS2_SUPERBLOCK_OFFSET, off, ocfs2_super_block::s_label, ocfs2_super_block::s_uuid, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_string(), and volume_id_set_uuid().
Variable Documentation
PACKED
struct ocfs2_super_block PACKED