Fennix Userspace: Userspace/musl/src/exit/exit.c File Reference
exit.c File Reference
#include <stdlib.h>
#include <stdint.h>
#include "libc.h"
Functions
static void dummy ()
weak_alias (dummy, __funcs_on_exit)
weak_alias (dummy, __stdio_exit)
weak_alias (dummy, _fini)
static void libc_exit_fini (void)
weak_alias (libc_exit_fini, __libc_exit_fini)
_Noreturn void exit (int code)
Variables
weak hidden void(*const __fini_array_start)(void)
weak hidden void(*const)(*const) __fini_array_end (void)
Function Documentation
dummy()
static void dummy (void) static
Definition at line 5 of file exit.c.
 {
 }
exit()
_Noreturn void exit (int code)
Definition at line 27 of file exit.c.
 {
     __funcs_on_exit();
     __libc_exit_fini();
     __stdio_exit();
     _Exit(code);
 }
References __funcs_on_exit(), __libc_exit_fini(), __stdio_exit(), _exit(), _Exit(), code, and status.
libc_exit_fini()
static void libc_exit_fini (void) static
Definition at line 17 of file exit.c.
 {
     uintptr_t a = (uintptr_t)&__fini_array_end;
     for (; a>(uintptr_t)&__fini_array_start; a-=sizeof(void(*)()))
         (*(void (**)())(a-sizeof(void(*)())))();
     _fini();
 }
References __fini_array_end, __fini_array_start, and _fini().
weak_alias() [1/4]
weak_alias (dummy , __funcs_on_exit)
weak_alias() [2/4]
weak_alias (dummy , __stdio_exit)
weak_alias() [3/4]
weak_alias (dummy , _fini)
weak_alias() [4/4]
weak_alias (libc_exit_fini , __libc_exit_fini)
Variable Documentation
__fini_array_end
weak hidden void(*const)(*const) __fini_array_end(void) (void)
Definition at line 15 of file exit.c.
Referenced by libc_exit_fini().
__fini_array_start
weak hidden void(*const __fini_array_start) (void) (void) extern
Definition at line 162 of file dynlink.c.
Referenced by libc_exit_fini().