Fennix: Kernel/library/convert.cpp File Reference
convert.cpp File Reference
#include <convert.h>
#include <memory.hpp>
#include <limits.h>
#include <debug.h>
#include <cpu.hpp>
#include "../kernel.h"
Functions
EXTERNC int memcmp (const void *vl, const void *vr, size_t n)
EXTERNC void backspace (char s[])
EXTERNC void append (char s[], char n)
EXTERNC int strncmp (const char *s1, const char *s2, size_t n)
EXTERNC long unsigned strlen (const char s[])
EXTERNC char * strcat_unsafe (char *destination, const char *source)
EXTERNC char * strcpy_unsafe (char *destination, const char *source)
EXTERNC char * strncpy (char *destination, const char *source, unsigned long num)
EXTERNC int strcmp (const char *l, const char *r)
EXTERNC int strncasecmp (const char *string1, const char *string2, size_t count)
EXTERNC char * strstr (const char *haystack, const char *needle)
EXTERNC char * strchr (const char *String, int Char)
EXTERNC char * strdup (const char *String)
EXTERNC int isalpha (int c)
EXTERNC int isupper (int c)
EXTERNC long int strtol (const char *str, char **endptr, int base)
EXTERNC unsigned long int strtoul (const char *str, char **endptr, int base)
EXTERNC int isdigit (int c)
EXTERNC int isspace (int c)
EXTERNC int isempty (char *str)
EXTERNC unsigned int isdelim (char c, const char *delim)
EXTERNC long abs (long i)
EXTERNC void swap (char *x, char *y)
EXTERNC char * reverse (char *Buffer, int i, int j)
EXTERNC float sqrtf (float x)
EXTERNC double clamp (double x, double low, double high)
EXTERNC float lerp (float a, float b, float t)
EXTERNC float smoothstep (float a, float b, float t)
EXTERNC float cubicInterpolate (float a, float b, float t)
EXTERNC char * strtok (char *src, const char *delim)
int strcasecmp (const char *s1, const char *s2)
size_t wcslen (const wchar_t *s)
size_t wcsrtombs (char *dst, const wchar_t **src, size_t len, mbstate_t *ps)
EXTERNC int atoi (const char *String)
EXTERNC double atof (const char *String)
EXTERNC char * itoa (int Value, char *Buffer, int Base)
EXTERNC char * ltoa (long Value, char *Buffer, int Base)
EXTERNC char * ultoa (unsigned long Value, char *Buffer, int Base)
EXTERNC int log2 (unsigned int n)
EXTERNC void __chk_fail (void) __noreturn
__noreturn static __always_inline void __convert_chk_fail (void)
EXTERNC __no_stack_protector void * __memcpy_chk (void *dest, const void *src, size_t len, size_t slen)
EXTERNC __no_stack_protector void * __memset_chk (void *dest, int val, size_t len, size_t slen)
EXTERNC __no_stack_protector void * __memmove_chk (void *dest, const void *src, size_t len, size_t slen)
EXTERNC __no_stack_protector char * __strcat_chk (char *dest, const char *src, size_t slen)
EXTERNC __no_stack_protector char * __strcpy_chk (char *dest, const char *src, size_t slen)
EXTERNC __no_stack_protector void * memcpy (void *dest, const void *src, size_t len)
EXTERNC __no_stack_protector void * memset (void *dest, int val, size_t len)
Function Documentation
__chk_fail()
EXTERNC void __chk_fail (void)
Definition at line 93 of file stack_check.cpp.
 {
     TaskingPanic();
     for (short i = 0; i < 10; i++)
         error("Buffer overflow detected!");
     KPrint("\eFF0000Buffer overflow detected!");
 #if defined(a86)
     while (1)
         asmv("cli; hlt");
 #elif defined(aa64)
     asmv("wfe");
 #endif
 }
References asmv(), error, i, KPrint(), and TaskingPanic().
Referenced by __memcpy_chk(), __memmove_chk(), __memset_chk(), __strcat_chk(), and __strcpy_chk().
__convert_chk_fail()
__noreturn static __always_inline void __convert_chk_fail (void) inline static
Definition at line 782 of file convert.cpp.
 {
 #if defined(a86)
     asmv("int3");
 #else
 #warning "Not implemented!"
 #endif
     __builtin_unreachable();
 }
References asmv().
Referenced by __memcpy_chk(), __memmove_chk(), __memset_chk(), __strcat_chk(), and __strcpy_chk().
__memcpy_chk()
EXTERNC __no_stack_protector void* __memcpy_chk (void * dest, const void * src, size_t len, size_t slen)
Definition at line 794 of file convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx src:%#lx len:%llu slen:%llu )",
           dest, src, len, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(src == NULL))
     {
         error("src is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len == 0))
     {
         error("len is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len > slen))
         __chk_fail();
     void *ret = nullptr;
     if (Config.SIMD)
     {
         uint64_t simd = CPU::CheckSIMD();
         if (simd & CPU::x86SIMDType::SIMD_SSE42)
             ret = memcpy_sse4_2(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE41)
             ret = memcpy_sse4_1(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSSE3)
             ret = memcpy_ssse3(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE3)
             ret = memcpy_sse3(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE2)
             ret = memcpy_sse2(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE)
             ret = memcpy_sse(dest, src, len);
         else
             ret = memcpy_unsafe(dest, src, len);
     }
     else
     {
         static int once = 0;
         if (!once++)
             fixme("SIMD memcpy disabled");
         ret = memcpy_unsafe(dest, src, len);
     }
     return ret;
 }
References __chk_fail(), __convert_chk_fail(), CPU::CheckSIMD(), Config, debug, error, fixme, SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, len, memcpy_sse(), memcpy_sse2(), memcpy_sse3(), memcpy_sse4_1(), memcpy_sse4_2(), memcpy_ssse3(), memcpy_unsafe(), NULL, KernelConfig::SIMD, CPU::SIMD_SSE, CPU::SIMD_SSE2, CPU::SIMD_SSE3, CPU::SIMD_SSE41, CPU::SIMD_SSE42, CPU::SIMD_SSSE3, src, and unlikely.
Referenced by memcpy().
__memmove_chk()
EXTERNC __no_stack_protector void* __memmove_chk (void * dest, const void * src, size_t len, size_t slen)
Definition at line 932 of file convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx src:%#lx len:%llu slen:%llu )",
           dest, src, len, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(src == NULL))
     {
         error("src is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len == 0))
     {
         error("len is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len > slen))
         __chk_fail();
     void *ret = nullptr;
     if (Config.SIMD)
     {
         uint64_t simd = CPU::CheckSIMD();
         if (simd & CPU::x86SIMDType::SIMD_SSE42)
             ret = memmove_sse4_2(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE41)
             ret = memmove_sse4_1(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSSE3)
             ret = memmove_ssse3(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE3)
             ret = memmove_sse3(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE2)
             ret = memmove_sse2(dest, src, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE)
             ret = memmove_sse(dest, src, len);
         else
             ret = memmove_unsafe(dest, src, len);
     }
     else
     {
         static int once = 0;
         if (!once++)
             fixme("SIMD memmove disabled");
         ret = memmove_unsafe(dest, src, len);
     }
     return ret;
 }
References __chk_fail(), __convert_chk_fail(), CPU::CheckSIMD(), Config, debug, error, fixme, SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, len, memmove_sse(), memmove_sse2(), memmove_sse3(), memmove_sse4_1(), memmove_sse4_2(), memmove_ssse3(), memmove_unsafe(), NULL, KernelConfig::SIMD, CPU::SIMD_SSE, CPU::SIMD_SSE2, CPU::SIMD_SSE3, CPU::SIMD_SSE41, CPU::SIMD_SSE42, CPU::SIMD_SSSE3, src, and unlikely.
__memset_chk()
EXTERNC __no_stack_protector void* __memset_chk (void * dest, int val, size_t len, size_t slen)
Definition at line 868 of file convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx val:%#x len:%llu slen:%llu )", dest, val, len, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len == 0))
     {
         error("len is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(len > slen))
         __chk_fail();
     void *ret = nullptr;
     if (Config.SIMD)
     {
         uint64_t simd = CPU::CheckSIMD();
         if (simd & CPU::x86SIMDType::SIMD_SSE42)
             ret = memset_sse4_2(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE41)
             ret = memset_sse4_1(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSSE3)
             ret = memset_ssse3(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE3)
             ret = memset_sse3(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE2)
             ret = memset_sse2(dest, val, len);
         else if (simd & CPU::x86SIMDType::SIMD_SSE)
             ret = memset_sse(dest, val, len);
         else
             ret = memset_unsafe(dest, val, len);
     }
     else
     {
         static int once = 0;
         if (!once++)
             fixme("SIMD memset disabled");
         ret = memset_unsafe(dest, val, len);
     }
     return ret;
 }
References __chk_fail(), __convert_chk_fail(), CPU::CheckSIMD(), Config, debug, error, fixme, SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, len, memset_sse(), memset_sse2(), memset_sse3(), memset_sse4_1(), memset_sse4_2(), memset_ssse3(), memset_unsafe(), NULL, KernelConfig::SIMD, CPU::SIMD_SSE, CPU::SIMD_SSE2, CPU::SIMD_SSE3, CPU::SIMD_SSE41, CPU::SIMD_SSE42, CPU::SIMD_SSSE3, unlikely, and val.
Referenced by memset().
__strcat_chk()
EXTERNC __no_stack_protector char* __strcat_chk (char * dest, const char * src, size_t slen)
Definition at line 1006 of file convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx src:%#lx slen:%llu )",
           dest, src, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(src == NULL))
     {
         error("src is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     size_t dest_len = strlen(dest);
     if (unlikely(dest_len + strlen(src) + 1 > slen))
         __chk_fail();
     return strcat_unsafe(dest, src);
 }
References __chk_fail(), __convert_chk_fail(), debug, error, SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, NULL, src, strcat_unsafe(), strlen(), and unlikely.
__strcpy_chk()
EXTERNC __no_stack_protector char* __strcpy_chk (char * dest, const char * src, size_t slen)
Definition at line 1045 of file convert.cpp.
 {
 #ifdef DBG_CHK
     debug("( dest:%#lx src:%#lx slen:%llu )",
           dest, src, slen);
 #endif
     if (unlikely(dest == NULL))
     {
         error("dest is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(src == NULL))
     {
         error("src is NULL (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     if (unlikely(slen == 0))
     {
         error("slen is 0 (for %#lx %s)",
               __builtin_return_address(0),
               KernelSymbolTable ? KernelSymbolTable->GetSymbol((uintptr_t)__builtin_return_address(0))
                                 : "Unknown");
         __convert_chk_fail();
     }
     size_t len = strlen(src);
     if (unlikely(len >= slen))
         __chk_fail();
     return strcpy_unsafe(dest, src);
 }
References __chk_fail(), __convert_chk_fail(), debug, error, SymbolResolver::Symbols::GetSymbol(), KernelSymbolTable, len, NULL, src, strcpy_unsafe(), strlen(), and unlikely.
abs()
EXTERNC long abs (long i)
Definition at line 366 of file convert.cpp.
 { return i < 0 ? -i : i; }
References i.
Referenced by itoa(), and ltoa().
append()
EXTERNC void append (char s[], char n)
Definition at line 44 of file convert.cpp.
 {
     int len = s_cst(int, strlen(s));
     s[len] = n;
     s[len + 1] = '\0';
 }
References len, n, s, and strlen().
Referenced by _rl_copy_to_kill_ring(), awk_printf(), display_single(), escape_text(), expr_print_help(), gather_options_str(), new_init_action(), CrashHandler::CrashKeyboardDriver::OnInterruptReceived(), and tee_builtin().
atof()
EXTERNC double atof (const char * String)
Definition at line 580 of file convert.cpp.
 {
     // Originally from https://github.com/GaloisInc/minlibc/blob/master/atof.c
     /*
     Copyright (c) 2014 Galois Inc.
     All rights reserved.
     Redistribution and use in source and binary forms, with or without
     modification, are permitted provided that the following conditions
     are met:
       * Redistributions of source code must retain the above copyright
         notice, this list of conditions and the following disclaimer.
       * Redistributions in binary form must reproduce the above copyright
         notice, this list of conditions and the following disclaimer in
         the documentation and/or other materials provided with the
         distribution.
       * Neither the name of Galois, Inc. nor the names of its contributors
         may be used to endorse or promote products derived from this
         software without specific prior written permission.
     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
     IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
     TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
     PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
     OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
     EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
     PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     */
     double a = 0.0;
     int e = 0;
     int c;
     while ((c = *String++) != '\0' && isdigit(c))
     {
         a = a * 10.0 + (c - '0');
     }
     if (c == '.')
     {
         while ((c = *String++) != '\0' && isdigit(c))
         {
             a = a * 10.0 + (c - '0');
             e = e - 1;
         }
     }
     if (c == 'e' || c == 'E')
     {
         int sign = 1;
         int i = 0;
         c = *String++;
         if (c == '+')
             c = *String++;
         else if (c == '-')
         {
             c = *String++;
             sign = -1;
         }
         while (isdigit(c))
         {
             i = i * 10 + (c - '0');
             c = *String++;
         }
         e += i * sign;
     }
     while (e > 0)
     {
         a *= 10.0;
         e--;
     }
     while (e < 0)
     {
         a *= 0.1;
         e++;
     }
     return a;
 }
atoi()
EXTERNC int atoi (const char * String)
Definition at line 567 of file convert.cpp.
 {
     uint64_t Length = strlen((char *)String);
     int OutBuffer = 0;
     int Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (String[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
backspace()
EXTERNC void backspace (char s[])
Definition at line 38 of file convert.cpp.
 {
     int len = s_cst(int, strlen(s));
     s[len - 1] = '\0';
 }
References len, s, and strlen().
Referenced by CrashHandler::CrashKeyboardDriver::OnInterruptReceived().
clamp()
EXTERNC double clamp (double x, double low, double high)
Definition at line 404 of file convert.cpp.
 {
     if (x < low)
         return low;
     else if (x > high)
         return high;
     else
         return x;
 }
References x.
Referenced by smoothstep().
cubicInterpolate()
EXTERNC float cubicInterpolate (float a, float b, float t)
Definition at line 428 of file convert.cpp.
 {
     float t2 = t * t;
     float t3 = t2 * t;
     return a + (-2 * t3 + 3 * t2) * b;
 }
References t, t2, and t3.
isalpha()
EXTERNC int isalpha (int c)
Definition at line 192 of file convert.cpp.
 {
     return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
 }
Referenced by strtol(), and strtoul().
isdelim()
EXTERNC unsigned int isdelim (char c, const char * delim)
Definition at line 355 of file convert.cpp.
 {
     while (*delim != '\0')
     {
         if (c == *delim)
             return 1;
         delim++;
     }
     return 0;
 }
References c.
Referenced by strtok().
isdigit()
EXTERNC int isdigit (int c)
Definition at line 332 of file convert.cpp.
 {
     return c >= '0' && c <= '9';
 }
Referenced by atof(), strtol(), and strtoul().
isempty()
EXTERNC int isempty (char * str)
Definition at line 342 of file convert.cpp.
 {
     if (strlen(str) == 0)
         return 1;
     while (*str != '\0')
     {
         if (!isspace(*str))
             return 0;
         str++;
     }
     return 1;
 }
References isspace(), str, and strlen().
Referenced by vfs::Virtual::Create(), vfs::Virtual::Delete(), vfs::Virtual::PathExists(), and vfs::USTAR::ReadArchive().
isspace()
EXTERNC int isspace (int c)
Definition at line 337 of file convert.cpp.
 {
     return c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\f' || c == '\v';
 }
Referenced by isempty(), strtol(), and strtoul().
isupper()
EXTERNC int isupper (int c)
Definition at line 197 of file convert.cpp.
 {
     return (c >= 'A' && c <= 'Z');
 }
Referenced by strtol(), and strtoul().
itoa()
EXTERNC char* itoa (int Value, char * Buffer, int Base)
Definition at line 662 of file convert.cpp.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     int n = s_cst(int, abs(Value));
     int i = 0;
     while (n)
     {
         int r = s_cst(int, n % Base);
         if (r >= 10)
             Buffer[i++] = s_cst(char, 65 + (r - 10));
         else
             Buffer[i++] = s_cst(char, 48 + r);
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     if (Value < 0 && Base == 10)
         Buffer[i++] = '-';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References abs(), Buffer, i, n, and reverse().
lerp()
EXTERNC float lerp (float a, float b, float t)
Definition at line 414 of file convert.cpp.
 {
     return (1 - t) * a + t * b;
 }
References t.
Referenced by smoothstep().
log2()
EXTERNC int log2 (unsigned int n)
Definition at line 743 of file convert.cpp.
 {
     if (n == 0)
     {
         error("log2(0) is undefined.");
         return -1;
     }
     int log = 0;
     if ((n & 0xFFFF0000) != 0)
     {
         n >>= 16;
         log = 16;
     }
     if (n >= 256)
     {
         n >>= 8;
         log += 8;
     }
     if (n >= 16)
     {
         n >>= 4;
         log += 4;
     }
     if (n >= 4)
     {
         n >>= 2;
         log += 2;
     }
     return log + (n >> 1);
 }
References error, log, and n.
ltoa()
EXTERNC char* ltoa (long Value, char * Buffer, int Base)
Definition at line 690 of file convert.cpp.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     long n = abs(Value);
     int i = 0;
     while (n)
     {
         int r = s_cst(int, n % Base);
         if (r >= 10)
             Buffer[i++] = s_cst(char, 65 + (r - 10));
         else
             Buffer[i++] = s_cst(char, 48 + r);
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     if (Value < 0 && Base == 10)
         Buffer[i++] = '-';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
memcmp()
EXTERNC int memcmp (const void * vl, const void * vr, size_t n)
Definition at line 30 of file convert.cpp.
 {
     const unsigned char *l = (unsigned char *)vl, *r = (unsigned char *)vr;
     for (; n && *l == *r; n--, l++, r++)
         ;
     return n ? *l - *r : 0;
 }
memcpy()
EXTERNC __no_stack_protector void* memcpy (void * dest, const void * src, size_t len)
Definition at line 1087 of file convert.cpp.
 {
     void *ret = __memcpy_chk(dest, src, len, __builtin_object_size(dest, 0));
     return ret;
 }
References __memcpy_chk(), len, and src.
memset()
EXTERNC __no_stack_protector void* memset (void * dest, int val, size_t len)
Definition at line 1094 of file convert.cpp.
 {
     void *ret = __memset_chk(dest, val, len, __builtin_object_size(dest, 0));
     return ret;
 }
References __memset_chk(), len, and val.
reverse()
EXTERNC char* reverse (char * Buffer, int i, int j)
Definition at line 375 of file convert.cpp.
 {
     while (i < j)
         swap(&Buffer[i++], &Buffer[j--]);
     return Buffer;
 }
Referenced by itoa(), ltoa(), and ultoa().
smoothstep()
EXTERNC float smoothstep (float a, float b, float t)
Definition at line 419 of file convert.cpp.
 {
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wfloat-conversion"
     t = clamp(s_cst(double, t), 0.0, 1.0);
 #pragma GCC diagnostic pop
     return lerp(a, b, t * t * (3 - 2 * t));
 }
References clamp(), lerp(), and t.
sqrtf()
EXTERNC float sqrtf (float x)
Definition at line 382 of file convert.cpp.
 {
     if (x < 0.0f)
         return NAN;
     if (x < 1e-7f)
         return 0.0f;
     float guess = x / 2.0f;
     for (short i = 0; i < 10; i++)
     {
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wfloat-equal"
         if (guess == 0.0f)
             return 0.0f;
 #pragma GCC diagnostic pop
         guess = (guess + x / guess) / 2.0f;
     }
     return guess;
 }
strcasecmp()
int strcasecmp (const char * s1, const char * s2)
Definition at line 475 of file convert.cpp.
 {
     const unsigned char *p1 = (const unsigned char *)s1;
     const unsigned char *p2 = (const unsigned char *)s2;
     int result;
     if (p1 == p2)
         return 0;
     while ((result = std::tolower(*p1) - std::tolower(*p2++)) == 0)
         if (*p1++ == '\0')
             break;
     return result;
 }
strcat_unsafe()
EXTERNC char* strcat_unsafe (char * destination, const char * source)
Definition at line 85 of file convert.cpp.
 {
     if ((destination == NULL) || (source == NULL))
         return NULL;
     char *start = destination;
     while (*start != '\0')
         start++;
     while (*source != '\0')
         *start++ = *source++;
     *start = '\0';
     return destination;
 }
References NULL, source, and start.
Referenced by __strcat_chk().
strchr()
EXTERNC char* strchr (const char * String, int Char)
Definition at line 173 of file convert.cpp.
 {
     assert(String != NULL);
     while (*String != (char)Char)
     {
         if (!*String++)
             return 0;
     }
     return (char *)String;
 }
strcmp()
EXTERNC int strcmp (const char * l, const char * r)
Definition at line 135 of file convert.cpp.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
strcpy_unsafe()
EXTERNC char* strcpy_unsafe (char * destination, const char * source)
Definition at line 101 of file convert.cpp.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source != '\0')
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
References NULL, and source.
Referenced by __strcpy_chk().
strdup()
EXTERNC char* strdup (const char * String)
Definition at line 185 of file convert.cpp.
 {
     char *OutBuffer = (char *)kmalloc(strlen((char *)String) + 1);
     strncpy(OutBuffer, String, strlen(String) + 1);
     return OutBuffer;
 }
strlen()
EXTERNC long unsigned strlen (const char s[])
Definition at line 64 of file convert.cpp.
 {
     if (Config.SIMD)
     {
         uint64_t simd = CPU::CheckSIMD();
         if (simd & CPU::x86SIMDType::SIMD_SSE42)
             return strlen_sse4_2(s);
         else if (simd & CPU::x86SIMDType::SIMD_SSE41)
             return strlen_sse4_1(s);
         else if (simd & CPU::x86SIMDType::SIMD_SSSE3)
             return strlen_ssse3(s);
         else if (simd & CPU::x86SIMDType::SIMD_SSE3)
             return strlen_sse3(s);
         else if (simd & CPU::x86SIMDType::SIMD_SSE2)
             return strlen_sse2(s);
         else if (simd & CPU::x86SIMDType::SIMD_SSE)
             return strlen_sse(s);
     }
     return __strlen(s);
 }
Referenced by __strcat_chk(), __strcpy_chk(), append(), atoi(), backspace(), isempty(), and strdup().
strncasecmp()
EXTERNC int strncasecmp (const char * string1, const char * string2, size_t count)
Definition at line 143 of file convert.cpp.
 {
     int result = 0;
     while (count--)
     {
         if ((result = std::tolower(*string1) - std::tolower(*string2)) != 0 || !*string1)
             break;
         string1++;
         string2++;
     }
     return result;
 }
strncmp()
EXTERNC int strncmp (const char * s1, const char * s2, size_t n)
Definition at line 51 of file convert.cpp.
 {
     for (size_t i = 0; i < n; i++)
     {
         char c1 = s1[i], c2 = s2[i];
         if (c1 != c2)
             return c1 - c2;
         if (!c1)
             return 0;
     }
     return 0;
 }
References i, n, s1, and s2.
strncpy()
EXTERNC char* strncpy (char * destination, const char * source, unsigned long num)
Definition at line 118 of file convert.cpp.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source && num--)
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
Referenced by strdup().
strstr()
EXTERNC char* strstr (const char * haystack, const char * needle)
Definition at line 156 of file convert.cpp.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }
strtok()
EXTERNC char* strtok (char * src, const char * delim)
Definition at line 435 of file convert.cpp.
 {
     static char *src1;
     if (!src)
         src = src1;
     if (!src)
         return NULL;
     while (1)
     {
         if (isdelim(*src, (char *)delim))
         {
             src++;
             continue;
         }
         if (*src == '\0')
             return NULL;
         break;
     }
     char *ret = src;
     while (1)
     {
         if (*src == '\0')
         {
             src1 = src;
             return ret;
         }
         if (isdelim(*src, (char *)delim))
         {
             *src = '\0';
             src1 = src + 1;
             return ret;
         }
         src++;
     }
     return NULL;
 }
References isdelim(), NULL, and src.
Referenced by ExecuteCommand(), linux_execve(), parseflags(), sys_execve(), targp_parse(), and CrashHandler::UserInput().
strtol()
EXTERNC long int strtol (const char * str, char ** endptr, int base)
Definition at line 202 of file convert.cpp.
 {
     const char *s;
     long acc, cutoff;
     int c;
     int neg, any, cutlim;
     s = str;
     do
     {
         c = *s++;
     } while (isspace(c));
     if (c == '-')
     {
         neg = 1;
         c = *s++;
     }
     else
     {
         neg = 0;
         if (c == '+')
             c = *s++;
     }
     if ((base == 0 || base == 16) && c == '0' && (*s == 'x' || *s == 'X'))
     {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     cutoff = neg ? LONG_MIN : LONG_MAX;
     cutlim = s_cst(int, cutoff % base);
     cutoff /= base;
     for (acc = 0, any = 0;; c = *s++)
     {
         if (isdigit(c))
             c -= '0';
         else if (isalpha(c))
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         else
             break;
         if (c >= base)
             break;
         if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
             any = -1;
         else
         {
             any = 1;
             acc *= base;
             acc += c;
         }
     }
     if (any < 0)
     {
         acc = neg ? LONG_MIN : LONG_MAX;
     }
     else if (neg)
         acc = -acc;
     if (endptr != 0)
         *endptr = (char *)(any ? s - 1 : str);
     return (acc);
 }
References base, c, isalpha(), isdigit(), isspace(), isupper(), LONG_MAX, LONG_MIN, s, and str.
Referenced by add_cmd(), check_operator(), get_address(), getservbyport_r(), history_get_time(), main(), odoffset(), parse_subst_cmd(), ParseField(), patch_main(), rpmalloc_initialize_config(), strtod(), strtoimax(), sv_xtracefd(), sym_get_range_val(), sym_string_within_range(), sym_validate_range(), and CrashHandler::UserInput().
strtoul()
EXTERNC unsigned long int strtoul (const char * str, char ** endptr, int base)
Definition at line 267 of file convert.cpp.
 {
     const char *s;
     unsigned long acc, cutoff;
     int c;
     int neg, any, cutlim;
     s = str;
     do
     {
         c = *s++;
     } while (isspace(c));
     if (c == '-')
     {
         neg = 1;
         c = *s++;
     }
     else
     {
         neg = 0;
         if (c == '+')
             c = *s++;
     }
     if ((base == 0 || base == 16) && c == '0' && (*s == 'x' || *s == 'X'))
     {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     cutoff = neg ? LONG_MIN : LONG_MAX;
     cutlim = s_cst(int, cutoff % base);
     cutoff /= base;
     for (acc = 0, any = 0;; c = *s++)
     {
         if (isdigit(c))
             c -= '0';
         else if (isalpha(c))
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         else
             break;
         if (c >= base)
             break;
         if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
             any = -1;
         else
         {
             any = 1;
             acc *= base;
             acc += c;
         }
     }
     if (any < 0)
     {
         acc = neg ? LONG_MIN : LONG_MAX;
     }
     else if (neg)
         acc = -acc;
     if (endptr != 0)
         *endptr = (char *)(any ? s - 1 : str);
     return (acc);
 }
References base, c, isalpha(), isdigit(), isspace(), isupper(), LONG_MAX, LONG_MIN, s, and str.
Referenced by __get_resolv_conf(), __inet_aton(), __lookup_serv(), __strftime_l(), bb_parse_mode(), dcngettext(), ether_aton_r(), evalprim(), get_irqs_from_interrupts(), get_mode(), get_qdisc_handle(), get_tc_classid(), get_u16(), get_u32(), get_unsigned(), getservbyname_r(), ifconfig_main(), init_cpu(), klogd_main(), new_process_module_arguments(), parse_meminfo(), process_irq_counts(), read_key(), reverse_services(), rtnl_rtntype_a2n(), sha256crypt(), sha512crypt(), strptime(), strtoumax(), and CrashHandler::UserInput().
swap()
EXTERNC void swap (char * x, char * y)
Definition at line 368 of file convert.cpp.
 {
     char t = *x;
     *x = *y;
     *y = t;
 }
Referenced by reverse().
ultoa()
EXTERNC char* ultoa (unsigned long Value, char * Buffer, int Base)
Definition at line 718 of file convert.cpp.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     unsigned long n = Value;
     int i = 0;
     while (n)
     {
         int r = s_cst(int, n % Base);
         if (r >= 10)
             Buffer[i++] = s_cst(char, 65 + (r - 10));
         else
             Buffer[i++] = s_cst(char, 48 + r);
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References Buffer, i, n, and reverse().
wcslen()
size_t wcslen (const wchar_t * s)
Definition at line 488 of file convert.cpp.
 {
     size_t len = 0;
     while (s[len] != L'\0')
     {
         if (s[++len] == L'\0')
             return len;
         if (s[++len] == L'\0')
             return len;
         if (s[++len] == L'\0')
             return len;
         ++len;
     }
     return len;
 }
wcsrtombs()
size_t wcsrtombs (char * dst, const wchar_t ** src, size_t len, mbstate_t * ps)
Definition at line 506 of file convert.cpp.
 {
     UNUSED(ps);
     size_t count = 0;
     while (len > 0)
     {
         wchar_t wc = **src;
         if (wc == L'\0')
             break;
         if (wc < 0x80)
         {
             if (dst)
                 *dst++ = (char)wc;
             count++;
             len--;
         }
         else if (wc < 0x800)
         {
             if (dst)
             {
                 *dst++ = (char)(0xC0 | (wc >> 6));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 2;
             len -= 2;
         }
         else if (wc < 0x10000)
         {
             if (dst)
             {
                 *dst++ = (char)(0xE0 | (wc >> 12));
                 *dst++ = (char)(0x80 | ((wc >> 6) & 0x3F));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 3;
             len -= 3;
         }
         else
         {
             if (dst)
             {
                 *dst++ = (char)(0xF0 | (wc >> 18));
                 *dst++ = (char)(0x80 | ((wc >> 12) & 0x3F));
                 *dst++ = (char)(0x80 | ((wc >> 6) & 0x3F));
                 *dst++ = (char)(0x80 | (wc & 0x3F));
             }
             count += 4;
             len -= 4;
         }
         (*src)++;
     }
     if (dst)
         *dst = '\0';
     return count;
 }
References count, dst, L, len, src, and UNUSED.
Referenced by fputws(), remove_pattern(), wcstombs(), and wstring_read().