Fennix: Userspace/mlibc/options/posix/include/sched.h File Reference
sched.h File Reference
#include <abi-bits/pid_t.h>
#include <bits/size_t.h>
#include <mlibc-config.h>
Data Structures
struct sched_param
Macros
#define SCHED_OTHER 0
#define SCHED_FIFO 1
#define SCHED_RR 2
#define SCHED_BATCH 3
#define SCHED_IDLE 5
#define SCHED_DEADLINE 6
#define SCHED_RESET_ON_FORK 0x40000000
Functions
int sched_yield (void)
int sched_get_priority_max (int policy)
int sched_get_priority_min (int policy)
int sched_setscheduler (pid_t pid, int policy, const struct sched_param *param)
int sched_getparam (pid_t pid, struct sched_param *param)
Data Structure Documentation
sched_param
struct sched_param
Definition at line 4 of file struct_sched_param.h.
Data Fields
int sched_priority
Macro Definition Documentation
SCHED_BATCH
#define SCHED_BATCH 3
Definition at line 25 of file sched.h.
SCHED_DEADLINE
#define SCHED_DEADLINE 6
Definition at line 27 of file sched.h.
SCHED_FIFO
#define SCHED_FIFO 1
Definition at line 23 of file sched.h.
SCHED_IDLE
#define SCHED_IDLE 5
Definition at line 26 of file sched.h.
SCHED_OTHER
#define SCHED_OTHER 0
Definition at line 22 of file sched.h.
SCHED_RESET_ON_FORK
#define SCHED_RESET_ON_FORK 0x40000000
Definition at line 28 of file sched.h.
SCHED_RR
#define SCHED_RR 2
Definition at line 24 of file sched.h.
Function Documentation
sched_get_priority_max()
int sched_get_priority_max (int policy)
Definition at line 20 of file sched-stubs.cpp.
{
     int res = 0;
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_get_max_priority, -1);
     if(int e = sysdep(policy, &res); e) {
         errno = e;
         return -1;
     }
     return res;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_get_max_priority().
sched_get_priority_min()
int sched_get_priority_min (int policy)
Definition at line 31 of file sched-stubs.cpp.
{
     int res = 0;
     auto sysdep = MLIBC_CHECK_OR_ENOSYS(mlibc::sys_get_min_priority, -1);
     if(int e = sysdep(policy, &res); e) {
         errno = e;
         return -1;
     }
     return res;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_get_min_priority().
sched_getparam()
int sched_getparam (pid_t pid, struct sched_param * param)
Definition at line 47 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sched_setscheduler()
int sched_setscheduler (pid_t pid, int policy, const struct sched_param * param)
Definition at line 42 of file sched-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
sched_yield()
int sched_yield (void)
Definition at line 10 of file sched-stubs.cpp.
                       {
     if(mlibc::sys_yield) {
         mlibc::sys_yield();
     }else{
         // Missing sched_yield() is not an error.
         MLIBC_MISSING_SYSDEP();
     }
     return 0;
 }
References MLIBC_MISSING_SYSDEP, and mlibc::sys_yield().