Fennix Userspace: Userspace/mlibc/tests/posix/wcwidth.c File Reference
wcwidth.c File Reference
#include <assert.h>
#include <locale.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <wchar.h>
Functions
void assertWidthIs (int expected_width, wchar_t c)
int main ()
Variables
static int tests_run
static int test_failures
Function Documentation
assertWidthIs()
void assertWidthIs (int expected_width, wchar_t c)
Definition at line 25 of file wcwidth.c.
{
     tests_run++;
     int actual_width = wcwidth(c);
     if (actual_width != expected_width) {
         fprintf(stderr, "ERROR: wcwidth(U+%04x, '%lc') returned %d, expected %d\n", c, c, actual_width, expected_width);
         test_failures++;
     }
 }
References c, fprintf(), stderr, test_failures, tests_run, and wcwidth().
Referenced by main().
main()
int main (void)
Definition at line 34 of file wcwidth.c.
            {
     setlocale(LC_CTYPE, "C.UTF-8");
     assertWidthIs(1, 'a');
     assertWidthIs(1, L'ö');
     // Some wide:
     assertWidthIs(2, L'Ａ');
     assertWidthIs(2, L'Ｂ');
     assertWidthIs(2, L'Ｃ');
     assertWidthIs(2, L'中');
     assertWidthIs(2, L'文');
     assertWidthIs(2, 0x679C);
     assertWidthIs(2, 0x679D);
     assertWidthIs(2, 0x2070E);
     assertWidthIs(2, 0x20731);
 #ifndef USE_HOST_LIBC
     assertWidthIs(1, 0x11A3);
 #endif
     assertWidthIs(2, 0x1F428); // Koala emoji.
     assertWidthIs(2, 0x231a);  // Watch emoji.
     if (test_failures > 0) printf("%d tests FAILED, ", test_failures);
     printf("%d tests OK\n", tests_run - test_failures);
     return (test_failures == 0) ? 0 : 1;
 }
References assertWidthIs(), L, LC_CTYPE, printf(), setlocale, test_failures, and tests_run.
Variable Documentation
test_failures
int test_failures static
Definition at line 23 of file wcwidth.c.
Referenced by assertWidthIs(), and main().
tests_run
int tests_run static
Definition at line 22 of file wcwidth.c.
Referenced by assertWidthIs(), and main().