Fennix Userspace: Userspace/musl/arch/x32/syscall_arch.h File Reference
syscall_arch.h File Reference
Macros
#define __SYSCALL_LL_E(x) (x)
#define __SYSCALL_LL_O(x) (x)
#define __scc(X) sizeof(1?(X):0ULL) < 8 ? (unsigned long) (X) : (long long) (X)
#define SYS_clock_gettime64 SYS_clock_gettime
#define SYS_clock_settime64 SYS_clock_settime
#define SYS_clock_adjtime64 SYS_clock_adjtime
#define SYS_clock_nanosleep_time64 SYS_clock_nanosleep
#define SYS_timer_gettime64 SYS_timer_gettime
#define SYS_timer_settime64 SYS_timer_settime
#define SYS_timerfd_gettime64 SYS_timerfd_gettime
#define SYS_timerfd_settime64 SYS_timerfd_settime
#define SYS_utimensat_time64 SYS_utimensat
#define SYS_pselect6_time64 SYS_pselect6
#define SYS_ppoll_time64 SYS_ppoll
#define SYS_recvmmsg_time64 SYS_recvmmsg
#define SYS_mq_timedsend_time64 SYS_mq_timedsend
#define SYS_mq_timedreceive_time64 SYS_mq_timedreceive
#define SYS_semtimedop_time64 SYS_semtimedop
#define SYS_rt_sigtimedwait_time64 SYS_rt_sigtimedwait
#define SYS_futex_time64 SYS_futex
#define SYS_sched_rr_get_interval_time64 SYS_sched_rr_get_interval
#define SYS_getrusage_time64 SYS_getrusage
#define SYS_wait4_time64 SYS_wait4
#define IPC_64 0
Typedefs
typedef long long syscall_arg_t
Functions
static __inline long __syscall0 (long long n)
static __inline long __syscall1 (long long n, long long a1)
static __inline long __syscall2 (long long n, long long a1, long long a2)
static __inline long __syscall3 (long long n, long long a1, long long a2, long long a3)
static __inline long __syscall4 (long long n, long long a1, long long a2, long long a3, long long a4_)
static __inline long __syscall5 (long long n, long long a1, long long a2, long long a3, long long a4_, long long a5_)
static __inline long __syscall6 (long long n, long long a1, long long a2, long long a3, long long a4_, long long a5_, long long a6_)
Macro Definition Documentation
__scc
#define __scc (X) sizeof(1?(X):0ULL) < 8 ? (unsigned long) (X) : (long long) (X)
Definition at line 4 of file syscall_arch.h.
__SYSCALL_LL_E
#define __SYSCALL_LL_E (x) (x)
Definition at line 1 of file syscall_arch.h.
__SYSCALL_LL_O
#define __SYSCALL_LL_O (x) (x)
Definition at line 2 of file syscall_arch.h.
IPC_64
#define IPC_64 0
Definition at line 93 of file syscall_arch.h.
SYS_clock_adjtime64
#define SYS_clock_adjtime64 SYS_clock_adjtime
Definition at line 74 of file syscall_arch.h.
SYS_clock_gettime64
#define SYS_clock_gettime64 SYS_clock_gettime
Definition at line 72 of file syscall_arch.h.
SYS_clock_nanosleep_time64
#define SYS_clock_nanosleep_time64 SYS_clock_nanosleep
Definition at line 75 of file syscall_arch.h.
SYS_clock_settime64
#define SYS_clock_settime64 SYS_clock_settime
Definition at line 73 of file syscall_arch.h.
SYS_futex_time64
#define SYS_futex_time64 SYS_futex
Definition at line 88 of file syscall_arch.h.
SYS_getrusage_time64
#define SYS_getrusage_time64 SYS_getrusage
Definition at line 90 of file syscall_arch.h.
SYS_mq_timedreceive_time64
#define SYS_mq_timedreceive_time64 SYS_mq_timedreceive
Definition at line 85 of file syscall_arch.h.
SYS_mq_timedsend_time64
#define SYS_mq_timedsend_time64 SYS_mq_timedsend
Definition at line 84 of file syscall_arch.h.
SYS_ppoll_time64
#define SYS_ppoll_time64 SYS_ppoll
Definition at line 82 of file syscall_arch.h.
SYS_pselect6_time64
#define SYS_pselect6_time64 SYS_pselect6
Definition at line 81 of file syscall_arch.h.
SYS_recvmmsg_time64
#define SYS_recvmmsg_time64 SYS_recvmmsg
Definition at line 83 of file syscall_arch.h.
SYS_rt_sigtimedwait_time64
#define SYS_rt_sigtimedwait_time64 SYS_rt_sigtimedwait
Definition at line 87 of file syscall_arch.h.
SYS_sched_rr_get_interval_time64
#define SYS_sched_rr_get_interval_time64 SYS_sched_rr_get_interval
Definition at line 89 of file syscall_arch.h.
SYS_semtimedop_time64
#define SYS_semtimedop_time64 SYS_semtimedop
Definition at line 86 of file syscall_arch.h.
SYS_timer_gettime64
#define SYS_timer_gettime64 SYS_timer_gettime
Definition at line 76 of file syscall_arch.h.
SYS_timer_settime64
#define SYS_timer_settime64 SYS_timer_settime
Definition at line 77 of file syscall_arch.h.
SYS_timerfd_gettime64
#define SYS_timerfd_gettime64 SYS_timerfd_gettime
Definition at line 78 of file syscall_arch.h.
SYS_timerfd_settime64
#define SYS_timerfd_settime64 SYS_timerfd_settime
Definition at line 79 of file syscall_arch.h.
SYS_utimensat_time64
#define SYS_utimensat_time64 SYS_utimensat
Definition at line 80 of file syscall_arch.h.
SYS_wait4_time64
#define SYS_wait4_time64 SYS_wait4
Definition at line 91 of file syscall_arch.h.
Typedef Documentation
syscall_arg_t
typedef long long syscall_arg_t
Definition at line 5 of file syscall_arch.h.
Function Documentation
__syscall0()
static __inline long __syscall0 (long long n) static
Definition at line 7 of file syscall_arch.h.
 {
     unsigned long ret;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), and n.
__syscall1()
static __inline long __syscall1 (long long n, long long a1) static
Definition at line 14 of file syscall_arch.h.
 {
     unsigned long ret;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, and n.
__syscall2()
static __inline long __syscall2 (long long n, long long a1, long long a2) static
Definition at line 21 of file syscall_arch.h.
 {
     unsigned long ret;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2)
                     : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, and n.
__syscall3()
static __inline long __syscall3 (long long n, long long a1, long long a2, long long a3) static
Definition at line 29 of file syscall_arch.h.
 {
     unsigned long ret;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
                           "d"(a3) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, a3, and n.
__syscall4()
static __inline long __syscall4 (long long n, long long a1, long long a2, long long a3, long long a4_) static
Definition at line 37 of file syscall_arch.h.
 {
     unsigned long ret;
     register long long a4 __asm__("r10") = a4_;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
                       "d"(a3), "r"(a4): "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, a3, a4, and n.
__syscall5()
static __inline long __syscall5 (long long n, long long a1, long long a2, long long a3, long long a4_, long long a5_) static
Definition at line 47 of file syscall_arch.h.
 {
     unsigned long ret;
     register long long a4 __asm__("r10") = a4_;
     register long long a5 __asm__("r8") = a5_;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
                       "d"(a3), "r"(a4), "r"(a5) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, a3, a4, a5, and n.
__syscall6()
static __inline long __syscall6 (long long n, long long a1, long long a2, long long a3, long long a4_, long long a5_, long long a6_) static
Definition at line 58 of file syscall_arch.h.
 {
     unsigned long ret;
     register long long a4 __asm__("r10") = a4_;
     register long long a5 __asm__("r8") = a5_;
     register long long a6 __asm__("r9") = a6_;
     __asm__ __volatile__ ("syscall" : "=a"(ret) : "a"(n), "D"(a1), "S"(a2),
                       "d"(a3), "r"(a4), "r"(a5), "r"(a6) : "rcx", "r11", "memory");
     return ret;
 }
References __asm__(), a1, a2, a3, a4, a5, a6, and n.