Fennix: Userspace/mlibc/options/ansi/generic/complex/cabs.c File Reference
cabs.c File Reference
#include <complex.h>
#include <math.h>
Functions
double cabs (double complex z)
Function Documentation
cabs()
double cabs (double complex z)
Definition at line 49 of file cabs.c.
 {
     return hypot( creal(z), cimag(z) );
 }
References cimag(), creal(), and hypot().
Referenced by clog(), cpow(), and csqrt().