Fennix Userspace: Userspace/mlibc/sysdeps/lyre/include/sys/mount.h File Reference
mount.h File Reference
Macros
#define MS_RDONLY 1
#define MS_NOSUID 2
#define MS_NODEV 4
#define MS_NOEXEC 8
#define MS_SYNCHRONOUS 16
#define MS_REMOUNT 32
#define MS_MANDLOCK 64
#define MS_DIRSYNC 128
#define MS_NOSYMFOLLOW 256
#define MS_NOATIME 1024
#define MS_NODIRATIME 2048
#define MS_BIND 4096
#define MS_MOVE 8192
#define MS_REC 16384
#define MS_SILENT 32768
#define MS_POSIXACL (1 << 16)
#define MS_UNBINDABLE (1 << 17)
#define MS_PRIVATE (1 << 18)
#define MS_SLAVE (1 << 19)
#define MS_SHARED (1 << 20)
#define MS_RELATIME (1 << 21)
#define MS_KERNMOUNT (1 << 22)
#define MS_I_VERSION (1 << 23)
#define MS_STRICTATIME (1 << 24)
#define MS_LAZYTIME (1 << 25)
#define MS_NOREMOTELOCK (1 << 27)
#define MS_NOSEC (1 << 28)
#define MS_BORN (1 << 29)
#define MS_ACTIVE (1 << 30)
#define MS_NOUSER (1 << 31)
#define MNT_FORCE 1
Functions
int mount (const char *source, const char *target, const char *fstype, unsigned long flags, const void *data)
int umount (const char *target)
int umount2 (const char *target, int flags)
Macro Definition Documentation
MNT_FORCE
#define MNT_FORCE 1
Definition at line 39 of file mount.h.
MS_ACTIVE
#define MS_ACTIVE (1 << 30)
Definition at line 36 of file mount.h.
MS_BIND
#define MS_BIND 4096
Definition at line 19 of file mount.h.
MS_BORN
#define MS_BORN (1 << 29)
Definition at line 35 of file mount.h.
MS_DIRSYNC
#define MS_DIRSYNC 128
Definition at line 15 of file mount.h.
MS_I_VERSION
#define MS_I_VERSION (1 << 23)
Definition at line 30 of file mount.h.
MS_KERNMOUNT
#define MS_KERNMOUNT (1 << 22)
Definition at line 29 of file mount.h.
MS_LAZYTIME
#define MS_LAZYTIME (1 << 25)
Definition at line 32 of file mount.h.
MS_MANDLOCK
#define MS_MANDLOCK 64
Definition at line 14 of file mount.h.
MS_MOVE
#define MS_MOVE 8192
Definition at line 20 of file mount.h.
MS_NOATIME
#define MS_NOATIME 1024
Definition at line 17 of file mount.h.
MS_NODEV
#define MS_NODEV 4
Definition at line 10 of file mount.h.
MS_NODIRATIME
#define MS_NODIRATIME 2048
Definition at line 18 of file mount.h.
MS_NOEXEC
#define MS_NOEXEC 8
Definition at line 11 of file mount.h.
MS_NOREMOTELOCK
#define MS_NOREMOTELOCK (1 << 27)
Definition at line 33 of file mount.h.
MS_NOSEC
#define MS_NOSEC (1 << 28)
Definition at line 34 of file mount.h.
MS_NOSUID
#define MS_NOSUID 2
Definition at line 9 of file mount.h.
MS_NOSYMFOLLOW
#define MS_NOSYMFOLLOW 256
Definition at line 16 of file mount.h.
MS_NOUSER
#define MS_NOUSER (1 << 31)
Definition at line 37 of file mount.h.
MS_POSIXACL
#define MS_POSIXACL (1 << 16)
Definition at line 23 of file mount.h.
MS_PRIVATE
#define MS_PRIVATE (1 << 18)
Definition at line 25 of file mount.h.
MS_RDONLY
#define MS_RDONLY 1
Definition at line 8 of file mount.h.
MS_REC
#define MS_REC 16384
Definition at line 21 of file mount.h.
MS_RELATIME
#define MS_RELATIME (1 << 21)
Definition at line 28 of file mount.h.
MS_REMOUNT
#define MS_REMOUNT 32
Definition at line 13 of file mount.h.
MS_SHARED
#define MS_SHARED (1 << 20)
Definition at line 27 of file mount.h.
MS_SILENT
#define MS_SILENT 32768
Definition at line 22 of file mount.h.
MS_SLAVE
#define MS_SLAVE (1 << 19)
Definition at line 26 of file mount.h.
MS_STRICTATIME
#define MS_STRICTATIME (1 << 24)
Definition at line 31 of file mount.h.
MS_SYNCHRONOUS
#define MS_SYNCHRONOUS 16
Definition at line 12 of file mount.h.
MS_UNBINDABLE
#define MS_UNBINDABLE (1 << 17)
Definition at line 24 of file mount.h.
Function Documentation
mount()
int mount (const char * source, const char * target, const char * fstype, unsigned long flags, const void * data)
Definition at line 8 of file sys-mount.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mount, -1);
     if(int e = mlibc::sys_mount(source, target, fstype, flags, data); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mount().
umount()
int umount (const char * target)
Definition at line 18 of file sys-mount.cpp.
{
     return umount2(target, 0);
 }
References umount2().
umount2()
int umount2 (const char * target, int flags)
Definition at line 22 of file sys-mount.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_umount2, -1);
     if(int e = mlibc::sys_umount2(target, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_umount2().
Referenced by umount().