Fennix: Userspace/musl/src/legacy/getpass.c File Reference
getpass.c File Reference
#include <stdio.h>
#include <termios.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
Macros
#define _GNU_SOURCE
Functions
char * getpass (const char *prompt)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file getpass.c.
Function Documentation
getpass()
char* getpass (const char * prompt)
Definition at line 8 of file getpass.c.
 {
     int fd;
     struct termios s, t;
     ssize_t l;
     static char password[128];
     if ((fd = open("/dev/tty", O_RDWR|O_NOCTTY|O_CLOEXEC)) < 0) return 0;
     tcgetattr(fd, &t);
     s = t;
     t.c_lflag &= ~(ECHO|ISIG);
     t.c_lflag |= ICANON;
     t.c_iflag &= ~(INLCR|IGNCR);
     t.c_iflag |= ICRNL;
     tcsetattr(fd, TCSAFLUSH, &t);
     tcdrain(fd);
     dprintf(fd, "%s", prompt);
     l = read(fd, password, sizeof password);
     if (l >= 0) {
         if (l > 0 && password[l-1] == '\n' || l==sizeof password) l--;
         password[l] = 0;
     }
     tcsetattr(fd, TCSAFLUSH, &s);
     dprintf(fd, "\n");
     close(fd);
     return l<0 ? 0 : password;
 }
References close(), dprintf(), ECHO, fd, ICANON, ICRNL, IGNCR, INLCR, ISIG, l, O_CLOEXEC, O_NOCTTY, O_RDWR, open(), password, prompt, read(), s, t, tcdrain(), tcgetattr(), TCSAFLUSH, and tcsetattr().