Fennix Userspace: Userspace/apps/base/busybox/libbb/print_flags.c File Reference
print_flags.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC print_flags_separated (const int *masks, const char *labels, int flags, const char *separator)
int FAST_FUNC print_flags (const masks_labels_t *ml, int flags)
Function Documentation
print_flags()
int FAST_FUNC print_flags (const masks_labels_t * ml, int flags)
Definition at line 29 of file print_flags.c.
 {
     return print_flags_separated(ml->masks, ml->labels, flags, NULL);
 }
References flags, ml, NULL, and print_flags_separated().
print_flags_separated()
int FAST_FUNC print_flags_separated (const int * masks, const char * labels, int flags, const char * separator)
Definition at line 12 of file print_flags.c.
 {
     const char *need_separator = NULL;
     while (*labels) {
         if (flags & *masks) {
             printf("%s%s",
                 need_separator ? need_separator : "",
                 labels);
             need_separator = separator;
             flags &= ~ *masks;
         }
         masks++;
         labels += strlen(labels) + 1;
     }
     return flags;
 }
References flags, NULL, printf(), separator, and strlen().
Referenced by arp_disp(), print_flags(), and print_link_flags().