Fennix Userspace: Userspace/apps/base/busybox/libbb/read.c File Reference
read.c File Reference
#include "libbb.h"
Functions
ssize_t FAST_FUNC safe_read (int fd, void *buf, size_t count)
ssize_t FAST_FUNC full_read (int fd, void *buf, size_t len)
ssize_t FAST_FUNC read_close (int fd, void *buf, size_t size)
ssize_t FAST_FUNC open_read_close (const char *filename, void *buf, size_t size)
Function Documentation
full_read()
ssize_t FAST_FUNC full_read (int fd, void * buf, size_t len)
Definition at line 36 of file read.c.
 {
     ssize_t cc;
     ssize_t total;
     total = 0;
     while (len) {
         cc = safe_read(fd, buf, len);
         if (cc < 0) {
             if (total) {
                 /* we already have some! */
                 /* user can do another read to know the error code */
                 return total;
             }
             return cc; /* read() returns -1 on failure. */
         }
         if (cc == 0)
             break;
         buf = ((char *)buf) + cc;
         total += cc;
         len -= cc;
     }
     return total;
 }
References buf, fd, safe_read(), and total.
Referenced by acpid_main(), archivefile(), bad_zone(), check_signature16(), dd_read(), dumpleases_main(), edir(), file_insert(), get_boot(), get_header_cpio(), get_header_tar(), get_response_or_say_and_die(), IF_DESKTOP(), inotifyd_main(), last_main(), lzo_compress(), nandwrite_main(), read_block(), read_close(), read_leases(), read_pte(), read_superblock(), rfkill_main(), tail_read(), top_up(), ubi_tools_main(), uuencode_main(), volume_id_get_buffer(), xmalloc_read_with_initial_buf(), and xread().
open_read_close()
ssize_t FAST_FUNC open_read_close (const char * filename, void * buf, size_t size)
Definition at line 74 of file read.c.
 {
     int fd = open(filename, O_RDONLY);
     if (fd < 0)
         return fd;
     return read_close(fd, buf, size);
 }
References buf, fd, filename, O_RDONLY, open(), read_close(), and size.
Referenced by cttyhack_main(), determine_optimal_seed_len(), display_header(), do_logging(), generate_uuid(), get_line(), get_num_from_file(), logdir_open(), make_device(), may_wakeup(), name_to_dev_t(), nmeter_main(), pid_is_exec(), pid_is_name(), read_cmdline(), read_new_seed(), seed_from_file_if_exists(), tls_get_random(), and ubi_get_volid_by_name().
read_close()
ssize_t FAST_FUNC read_close (int fd, void * buf, size_t size)
Definition at line 64 of file read.c.
 {
     /*int e;*/
     size = full_read(fd, buf, size);
     /*e = errno;*/
     close(fd);
     /*errno = e;*/
     return size;
 }
References buf, close(), fd, full_read(), and size.
Referenced by open_read_close().
safe_read()
ssize_t FAST_FUNC safe_read (int fd, void * buf, size_t count)
Definition at line 11 of file read.c.
 {
     ssize_t n;
     for (;;) {
         n = read(fd, buf, count);
         if (n >= 0 || errno != EINTR)
             break;
         /* Some callers set errno=0, are upset when they see EINTR.
          * Returning EINTR is wrong since we retry read(),
          * the "error" was transient.
          */
         errno = 0;
         /* repeat the read() */
     }
     return n;
 }
References buf, count, EINTR, errno, fd, n, and read().
Referenced by arpping(), askremotedate(), auto_baud(), awk_getline(), bb_full_fd_action(), chat_main(), cksum_main(), d6_recv_kernel_packet(), d6_recv_raw_packet(), dd_read(), do_rd(), dump_procs(), fdformat_main(), file_read(), fill_bitbuffer(), filter_rename_config(), full_read(), get_line(), get_response_or_say_and_die(), getty_main(), hash_file(), IF_DESKTOP(), lpd_main(), microcom_main(), nc_main(), ndelay_read(), nonblock_immune_read(), pipe_progress_main(), powertop_main(), rc_read(), read_key(), read_lines(), readLines(), refill_HFILE_and_getc(), rtcwake_main(), run(), script_main(), send_file_and_exit(), split_main(), sum_file(), tee_main(), telnet_main(), telnetd_main(), tls_run_copy_loop(), tls_xread_record(), tr_main(), udhcp_recv_kernel_packet(), udhcp_sp_read(), uevent_main(), and xsendfile().