Fennix Userspace: Userspace/apps/base/bash/examples/loadables/template.c File Reference
template.c File Reference
#include <config.h>
#include "bashansi.h"
#include <stdio.h>
#include <errno.h>
#include "loadables.h"
Functions
char * strerror ()
int template_builtin (WORD_LIST *list)
int template_builtin_load (char *name)
void template_builtin_unload (char *name)
Variables
int errno
char * template_doc []
struct builtin template_struct
Function Documentation
strerror()
char* strerror ()
template_builtin()
int template_builtin (WORD_LIST * list)
Definition at line 23 of file template.c.
 {
   int opt, rval;
   rval = EXECUTION_SUCCESS;
   reset_internal_getopt ();
   while ((opt = internal_getopt (list, "")) != -1)
     {
       switch (opt)
     {
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
   list = loptend;
   return (rval);
 }
References builtin_usage(), CASE_HELPOPT, EX_USAGE, EXECUTION_SUCCESS, internal_getopt(), list(), loptend, opt, and reset_internal_getopt().
template_builtin_load()
int template_builtin_load (char * name)
Definition at line 48 of file template.c.
 {
   return (1);
 }
template_builtin_unload()
void template_builtin_unload (char * name)
Definition at line 56 of file template.c.
 {
 }
Variable Documentation
errno
int errno extern
template_doc
char* template_doc[]
Initial value:
= {
    "Short description.",
    ""
    "Longer description of builtin and usage.",
    (char *)NULL
}
Definition at line 61 of file template.c.
template_struct
struct builtin template_struct
Initial value:
= {
    "template",
    template_builtin,
    BUILTIN_ENABLED,
    template_doc,
    "template",
    0
}
Definition at line 61 of file template.c.