Fennix: Userspace/libc/include/unistd.h File Reference
unistd.h File Reference
#include <sys/types.h>
Functions
int execl (const char *pathname, const char *arg,...)
int execlp (const char *file, const char *arg,...)
int execle (const char *pathname, const char *arg,...)
int execv (const char *pathname, char *const argv[])
int execvp (const char *file, char *const argv[])
int execvpe (const char *file, char *const argv[], char *const envp[])
int execve (const char *pathname, char *const argv[], char *const envp[])
pid_t fork (void)
unsigned int sleep (unsigned int seconds)
int usleep (useconds_t usec)
Variables
char ** environ
Function Documentation
execl()
int execl (const char * pathname, const char * arg, ...)
Definition at line 6 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ENOSYS, and errno.
Referenced by bootchartd_main(), custom(), data_extract_to_command(), do_wordexp(), processorstart(), script_main(), start_one_job(), and start_shell_in_child().
execle()
int execle (const char * pathname, const char * arg, ...)
Definition at line 18 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ENOSYS, and errno.
Referenced by doit().
execlp()
int execlp (const char * file, const char * arg, ...)
Definition at line 12 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ENOSYS, and errno.
Referenced by halt_main(), and runsv().
execv()
int execv (const char * pathname, char *const argv[])
Definition at line 24 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ENOSYS, and errno.
Referenced by exec_conf(), exec_shell(), execl(), main(), popen_ls(), pseudo_exec_argv(), re_exec(), startservice(), and switch_root_main().
execve()
int execve (const char * pathname, char *const argv[], char *const envp[])
Definition at line 42 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ENOSYS, and errno.
Referenced by __execvpe(), child(), execle(), execv(), fexecve(), re_execute_shell(), shell_execve(), and tryexec().
execvp()
int execvp (const char * file, char *const argv[])
Definition at line 30 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ENOSYS, and errno.
Referenced by exec_kernel_doc(), execlp(), execvp_or_die(), reset_main(), and start_stop_daemon_main().
execvpe()
int execvpe (const char * file, char *const argv[], char *const envp[])
Definition at line 36 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ENOSYS, and errno.
fork()
pid_t fork (void)
Definition at line 48 of file exe.c.
 {
     return syscall0(sc_fork);
 }
References sc_fork, and syscall0().
sleep()
unsigned int sleep (unsigned int seconds)
Definition at line 6 of file sleep.c.
 {
     // return syscall1(sys_Sleep, seconds * 1000000);
 }
Referenced by crond_main(), exec_conf(), fsleep(), halt_main(), iostat_main(), main(), make_child(), nc_main(), pause1cannot(), pause2cannot(), pause_after_failed_login(), pause_nomem(), powertop_main(), process_line(), readwrite(), runsvdir_main(), sendmail_main(), slattach_main(), sleep1(), sleep10(), sleep_main(), sleep_much(), startservice(), tail_main(), udhcpc6_main(), and udhcpc_main().
usleep()
int usleep (useconds_t usec)
Definition at line 11 of file sleep.c.
 {
     // return syscall1(sys_Sleep, usec);
 }
Variable Documentation
environ
char** environ extern
Definition at line 42 of file lib.c.
Referenced by getenv().