Fennix: Userspace/apps/base/busybox/util-linux/volume_id/xfs.c File Reference
xfs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct xfs_super_block
Macros
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_xfs (struct volume_id *id)
Variables
struct xfs_super_block PACKED
Data Structure Documentation
xfs_super_block
struct xfs_super_block
Definition at line 29 of file xfs.c.
Data Fields
uint32_t blocksize
uint64_t dblocks
uint32_t dummy1[2]
uint32_t dummy2[15]
uint32_t dummy3[2]
uint64_t fdblocks
uint8_t fname[12]
uint64_t icount
uint64_t ifree
uint8_t magic[4]
uint64_t rblocks
uint8_t uuid[16]
Macro Definition Documentation
off
#define off ((uint64_t)0)
Function Documentation
volume_id_probe_xfs()
int FAST_FUNC volume_id_probe_xfs (struct volume_id * id)
Definition at line 44 of file xfs.c.
 {
 #define off ((uint64_t)0)
     struct xfs_super_block *xs;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     xs = volume_id_get_buffer(id, off, 0x200);
     if (xs == NULL)
         return -1;
     if (memcmp(xs->magic, "XFSB", 4) != 0)
         return -1;
 //  volume_id_set_label_raw(id, xs->fname, 12);
     volume_id_set_label_string(id, xs->fname, 12);
     volume_id_set_uuid(id, xs->uuid, UUID_DCE);
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "xfs";)
     return 0;
 }
References dbg, xfs_super_block::fname, xfs_super_block::magic, memcmp(), NULL, off, xfs_super_block::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
Variable Documentation
PACKED
struct xfs_super_block PACKED