Fennix: Userspace/musl/src/stdio/fputws.c File Reference
fputws.c File Reference
#include "stdio_impl.h"
#include "locale_impl.h"
#include <wchar.h>
Functions
int fputws (const wchar_t *restrict ws, FILE *restrict f)
weak_alias (fputws, fputws_unlocked)
Function Documentation
fputws()
int fputws (const wchar_t *restrict ws, FILE *restrict f)
Definition at line 5 of file fputws.c.
 {
     unsigned char buf[BUFSIZ];
     size_t l=0;
     locale_t *ploc = &CURRENT_LOCALE, loc = *ploc;
     FLOCK(f);
     fwide(f, 1);
     *ploc = f->locale;
     while (ws && (l = wcsrtombs((void *)buf, (void*)&ws, sizeof buf, 0))+1 > 1)
         if (__fwritex(buf, l, f) < l) {
             FUNLOCK(f);
             *ploc = loc;
             return -1;
         }
     FUNLOCK(f);
     *ploc = loc;
     return l; /* 0 or -1 */
 }
References __fwritex(), buf, BUFSIZ, CURRENT_LOCALE, f, FLOCK, FUNLOCK, fwide(), l, and wcsrtombs().
weak_alias()
weak_alias (fputws , fputws_unlocked)