Fennix Userspace: Userspace/apps/base/bash/lib/sh/makepath.c File Reference
makepath.c File Reference
#include <config.h>
#include <bashansi.h>
#include "shell.h"
#include <tilde/tilde.h>
Macros
#define NULL 0
#define MP_DOTILDE 0x01
#define MP_DOCWD 0x02
#define MP_RMDOT 0x04
#define MP_IGNDOT 0x08
#define MAKEDOT()
Functions
char *get_working_directory PARAMS ((char *))
char * sh_makepath (char *path, char *dir, int flags) const
Variables
static char * nullpath = ""
Macro Definition Documentation
MAKEDOT
#define MAKEDOT ()
Value:
  do { \
    xpath = (char *)xmalloc (2); \
    xpath[0] = '.'; \
    xpath[1] = '\0'; \
    pathlen = 1; \
  } while (0)
Definition at line 61 of file makepath.c.
MP_DOCWD
#define MP_DOCWD 0x02
Definition at line 43 of file makepath.c.
MP_DOTILDE
#define MP_DOTILDE 0x01
Definition at line 42 of file makepath.c.
MP_IGNDOT
#define MP_IGNDOT 0x08
Definition at line 45 of file makepath.c.
MP_RMDOT
#define MP_RMDOT 0x04
Definition at line 44 of file makepath.c.
NULL
#define NULL 0
Definition at line 36 of file makepath.c.
Function Documentation
PARAMS()
char* get_working_directory PARAMS ((char *))
sh_makepath()
char* sh_makepath (char * path, char * dir, int flags) const
Definition at line 70 of file makepath.c.
 {
   int dirlen, pathlen;
   char *ret, *xpath, *xdir, *r, *s;
   if (path == 0 || *path == '\0')
     {
       if (flags & MP_DOCWD)
     {
       xpath = get_working_directory ("sh_makepath");
       if (xpath == 0)
         {
           ret = get_string_value ("PWD");
           if (ret)
         xpath = savestring (ret);
         }
       if (xpath == 0)
         MAKEDOT();
       else
         pathlen = strlen (xpath);
     }
       else
     MAKEDOT();
     }
   else if ((flags & MP_IGNDOT) && path[0] == '.' && (path[1] == '\0' ||
                              (path[1] == '/' && path[2] == '\0')))
     {
       xpath = nullpath;
       pathlen = 0;
     }
   else
     {
       xpath = ((flags & MP_DOTILDE) && *path == '~') ? bash_tilde_expand (path, 0) : (char *)path;
       pathlen = strlen (xpath);
     }
   xdir = (char *)dir;
   dirlen = strlen (xdir);
   if ((flags & MP_RMDOT) && dir[0] == '.' && dir[1] == '/')
     {
       xdir += 2;
       dirlen -= 2;
     }
   r = ret = (char *)xmalloc (2 + dirlen + pathlen);
   s = xpath;
   while (*s)
     *r++ = *s++;
   if (s > xpath && s[-1] != '/')
     *r++ = '/';
   s = xdir;
   while (*r++ = *s++)
     ;
   if (xpath != path && xpath != nullpath)
     free (xpath);
   return (ret);
 }
References bash_tilde_expand(), dir, flags, free, get_string_value(), get_working_directory(), MAKEDOT, MP_DOCWD, MP_DOTILDE, MP_IGNDOT, MP_RMDOT, nullpath, s, savestring(), strlen(), and xmalloc.
Referenced by _path_checkino(), find_in_path_element(), full_pathname(), glob_vector(), make_absolute(), and sh_realpath().
Variable Documentation
nullpath
char* nullpath = "" static
Definition at line 50 of file makepath.c.
Referenced by sh_makepath().