Fennix Userspace: Userspace/apps/base/busybox/scripts/kconfig/lxdialog/util.c File Reference
util.c File Reference
#include "dialog.h"
#include "colors.h"
Functions
void attr_clear (WINDOW *win, int height, int width, chtype attr)
void dialog_clear (void)
void init_dialog (void)
void color_setup (void)
void end_dialog (void)
void print_title (WINDOW *dialog, const char *title, int width)
void print_autowrap (WINDOW *win, const char *prompt, int width, int y, int x)
void print_button (WINDOW *win, const char *label, int y, int x, int selected)
void draw_box (WINDOW *win, int y, int x, int height, int width, chtype box, chtype border)
void draw_shadow (WINDOW *win, int y, int x, int height, int width)
int first_alpha (const char *string, const char *exempt)
Variables
bool use_colors = 1
const char * backtitle = NULL
chtype attributes []
int color_table [][3]
Function Documentation
attr_clear()
void attr_clear (WINDOW * win, int height, int width, chtype attr)
Definition at line 107 of file util.c.
 {
     int i, j;
     wattrset(win, attr);
     for (i = 0; i < height; i++) {
         wmove(win, i, 0);
         for (j = 0; j < width; j++)
             waddch(win, ' ');
     }
     touchwin(win);
 }
References height(), i, j, and width.
Referenced by dialog_clear(), dialog_textbox(), and main().
color_setup()
void color_setup (void)
Definition at line 155 of file util.c.
 {
     int i;
     if (has_colors()) { /* Terminal supports color? */
         start_color();
         /* Initialize color pairs */
         for (i = 0; i < ATTRIBUTE_COUNT; i++)
             init_pair(i + 1, color_table[i][0], color_table[i][1]);
         /* Setup color attributes */
         for (i = 0; i < ATTRIBUTE_COUNT; i++)
             attributes[i] = C_ATTR(color_table[i][2], i + 1);
     }
 }
References ATTRIBUTE_COUNT, attributes, C_ATTR, color_table, and i.
Referenced by init_dialog().
dialog_clear()
void dialog_clear (void)
Definition at line 120 of file util.c.
 {
     attr_clear(stdscr, LINES, COLS, screen_attr);
     /* Display background title if it exists ... - SLH */
     if (backtitle != NULL) {
         int i;
         wattrset(stdscr, screen_attr);
         mvwaddstr(stdscr, 0, 1, (char *)backtitle);
         wmove(stdscr, 1, 1);
         for (i = 1; i < COLS - 1; i++)
             waddch(stdscr, ACS_HLINE);
     }
     wnoutrefresh(stdscr);
 }
References ACS_HLINE, attr_clear(), backtitle, i, NULL, and screen_attr.
Referenced by init_dialog().
draw_box()
void draw_box (WINDOW * win, int y, int x, int height, int width, chtype box, chtype border)
Definition at line 290 of file util.c.
 {
     int i, j;
     wattrset(win, 0);
     for (i = 0; i < height; i++) {
         wmove(win, y + i, x);
         for (j = 0; j < width; j++)
             if (!i && !j)
                 waddch(win, border | ACS_ULCORNER);
             else if (i == height - 1 && !j)
                 waddch(win, border | ACS_LLCORNER);
             else if (!i && j == width - 1)
                 waddch(win, box | ACS_URCORNER);
             else if (i == height - 1 && j == width - 1)
                 waddch(win, box | ACS_LRCORNER);
             else if (!i)
                 waddch(win, border | ACS_HLINE);
             else if (i == height - 1)
                 waddch(win, box | ACS_HLINE);
             else if (!j)
                 waddch(win, border | ACS_VLINE);
             else if (j == width - 1)
                 waddch(win, box | ACS_VLINE);
             else
                 waddch(win, box | ' ');
     }
 }
References ACS_HLINE, ACS_LLCORNER, ACS_LRCORNER, ACS_ULCORNER, ACS_URCORNER, ACS_VLINE, height(), i, j, width, x, and y.
Referenced by dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), dialog_textbox(), and dialog_yesno().
draw_shadow()
void draw_shadow (WINDOW * win, int y, int x, int height, int width)
Definition at line 324 of file util.c.
 {
     int i;
     if (has_colors()) { /* Whether terminal supports color? */
         wattrset(win, shadow_attr);
         wmove(win, y + height, x + 2);
         for (i = 0; i < width; i++)
             waddch(win, winch(win) & A_CHARTEXT);
         for (i = y + 1; i < y + height + 1; i++) {
             wmove(win, i, x + width);
             waddch(win, winch(win) & A_CHARTEXT);
             waddch(win, winch(win) & A_CHARTEXT);
         }
         wnoutrefresh(win);
     }
 }
References height(), i, shadow_attr, width, x, and y.
Referenced by dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), dialog_textbox(), and dialog_yesno().
end_dialog()
void end_dialog (void)
Definition at line 175 of file util.c.
 {
     endwin();
 }
Referenced by main().
first_alpha()
int first_alpha (const char * string, const char * exempt)
Definition at line 345 of file util.c.
 {
     int i, in_paren = 0, c;
     for (i = 0; i < strlen(string); i++) {
         c = tolower(string[i]);
         if (strchr("<[(", c))
             ++in_paren;
         if (strchr(">])", c) && in_paren > 0)
             --in_paren;
         if ((!in_paren) && isalpha(c) && strchr(exempt, c) == 0)
             return i;
     }
     return 0;
 }
References c, i, isalpha, strchr(), strlen(), and tolower.
Referenced by dialog_menu(), and do_print_item().
init_dialog()
void init_dialog (void)
Definition at line 139 of file util.c.
 {
     initscr();      /* Init curses */
     keypad(stdscr, TRUE);
     cbreak();
     noecho();
     if (use_colors)     /* Set up colors */
         color_setup();
     dialog_clear();
 }
References color_setup(), dialog_clear(), TRUE, and use_colors.
Referenced by main().
print_autowrap()
void print_autowrap (WINDOW * win, const char * prompt, int width, int y, int x)
Definition at line 200 of file util.c.
 {
     int newl, cur_x, cur_y;
     int i, prompt_len, room, wlen;
     char tempstr[MAX_LEN + 1], *word, *sp, *sp2;
     strcpy(tempstr, prompt);
     prompt_len = strlen(tempstr);
     /*
      * Remove newlines
      */
     for (i = 0; i < prompt_len; i++) {
         if (tempstr[i] == '\n')
             tempstr[i] = ' ';
     }
     if (prompt_len <= width - x * 2) {  /* If prompt is short */
         wmove(win, y, (width - prompt_len) / 2);
         waddstr(win, tempstr);
     } else {
         cur_x = x;
         cur_y = y;
         newl = 1;
         word = tempstr;
         while (word && *word) {
             sp = strchr(word, ' ');
             if (sp)
                 *sp++ = 0;
             /* Wrap to next line if either the word does not fit,
                or it is the first word of a new sentence, and it is
                short, and the next word does not fit. */
             room = width - cur_x;
             wlen = strlen(word);
             if (wlen > room ||
                 (newl && wlen < 4 && sp
                  && wlen + 1 + strlen(sp) > room
                  && (!(sp2 = strchr(sp, ' '))
                  || wlen + 1 + (sp2 - sp) > room))) {
                 cur_y++;
                 cur_x = x;
             }
             wmove(win, cur_y, cur_x);
             waddstr(win, word);
             getyx(win, cur_y, cur_x);
             cur_x++;
             if (sp && *sp == ' ') {
                 cur_x++;    /* double space */
                 while (*++sp == ' ') ;
                 newl = 1;
             } else
                 newl = 0;
             word = sp;
         }
     }
 }
References i, MAX_LEN, prompt, sp, strchr(), strcpy(), strlen(), width, x, and y.
Referenced by dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), and dialog_yesno().
print_button()
void print_button (WINDOW * win, const char * label, int y, int x, int selected)
Definition at line 262 of file util.c.
 {
     int i, temp;
     wmove(win, y, x);
     wattrset(win, selected ? button_active_attr : button_inactive_attr);
     waddstr(win, "<");
     temp = strspn(label, " ");
     label += temp;
     wattrset(win, selected ? button_label_active_attr
          : button_label_inactive_attr);
     for (i = 0; i < temp; i++)
         waddch(win, ' ');
     wattrset(win, selected ? button_key_active_attr
          : button_key_inactive_attr);
     waddch(win, label[0]);
     wattrset(win, selected ? button_label_active_attr
          : button_label_inactive_attr);
     waddstr(win, (char *)label + 1);
     wattrset(win, selected ? button_active_attr : button_inactive_attr);
     waddstr(win, ">");
     wmove(win, y, x + temp + 1);
 }
References button_active_attr, button_inactive_attr, button_key_active_attr, button_key_inactive_attr, button_label_active_attr, button_label_inactive_attr, i, label, strspn(), x, and y.
Referenced by dialog_msgbox(), dialog_textbox(), and print_buttons().
print_title()
void print_title (WINDOW * dialog, const char * title, int width)
Definition at line 183 of file util.c.
 {
     if (title) {
         int tlen = MIN(width - 2, strlen(title));
         wattrset(dialog, title_attr);
         mvwaddch(dialog, 0, (width - tlen) / 2 - 1, ' ');
         mvwaddnstr(dialog, 0, (width - tlen)/2, title, tlen);
         waddch(dialog, ' ');
     }
 }
References MIN, strlen(), title, title_attr, and width.
Referenced by dialog_checklist(), dialog_inputbox(), dialog_menu(), dialog_msgbox(), dialog_textbox(), and dialog_yesno().
Variable Documentation
attributes
chtype attributes[]
Definition at line 32 of file util.c.
Referenced by checkjobs(), color_setup(), and mk_env_string().
backtitle
const char* backtitle = NULL
Definition at line 27 of file util.c.
Referenced by dialog_clear(), and main().
color_table
int color_table[][3]
Definition at line 69 of file util.c.
Referenced by color_setup().
use_colors
bool use_colors = 1
Definition at line 25 of file util.c.
Referenced by init_dialog().