Fennix Userspace: Userspace/apps/base/bash/lib/intl/os2compat.c File Reference
os2compat.c File Reference
#include <stdlib.h>
#include <string.h>
#include <sys/param.h>
Macros
#define OS2_AWARE
Functions
unsigned long DosScanEnv (const unsigned char *pszName, unsigned char **ppszValue)
char * _nl_getenv (const char *name)
static __attribute__ ((constructor))
Variables
char libintl_nl_default_dirname [MAXPATHLEN+1]
char * _nlos2_libdir = NULL
char * _nlos2_localealiaspath = NULL
char * _nlos2_localedir = NULL
Macro Definition Documentation
OS2_AWARE
#define OS2_AWARE
Definition at line 21 of file os2compat.c.
Function Documentation
__attribute__()
static __attribute__ ((constructor)) static
Definition at line 50 of file os2compat.c.
 {
   char *root = getenv ("UNIXROOT");
   char *gnulocaledir = getenv ("GNULOCALEDIR");
   _nlos2_libdir = gnulocaledir;
   if (!_nlos2_libdir)
     {
       if (root)
         {
           size_t sl = strlen (root);
           _nlos2_libdir = (char *) malloc (sl + strlen (LIBDIR) + 1);
           memcpy (_nlos2_libdir, root, sl);
           memcpy (_nlos2_libdir + sl, LIBDIR, strlen (LIBDIR) + 1);
         }
       else
         _nlos2_libdir = LIBDIR;
     }
   _nlos2_localealiaspath = gnulocaledir;
   if (!_nlos2_localealiaspath)
     {
       if (root)
         {
           size_t sl = strlen (root);
           _nlos2_localealiaspath = (char *) malloc (sl + strlen (LOCALE_ALIAS_PATH) + 1);
           memcpy (_nlos2_localealiaspath, root, sl);
           memcpy (_nlos2_localealiaspath + sl, LOCALE_ALIAS_PATH, strlen (LOCALE_ALIAS_PATH) + 1);
         }
      else
         _nlos2_localealiaspath = LOCALE_ALIAS_PATH;
     }
   _nlos2_localedir = gnulocaledir;
   if (!_nlos2_localedir)
     {
       if (root)
         {
           size_t sl = strlen (root);
           _nlos2_localedir = (char *) malloc (sl + strlen (LOCALEDIR) + 1);
           memcpy (_nlos2_localedir, root, sl);
           memcpy (_nlos2_localedir + sl, LOCALEDIR, strlen (LOCALEDIR) + 1);
         }
       else
         _nlos2_localedir = LOCALEDIR;
     }
   if (strlen (_nlos2_localedir) <= MAXPATHLEN)
     strcpy (libintl_nl_default_dirname, _nlos2_localedir);
 }
References _nlos2_libdir, _nlos2_localealiaspath, _nlos2_localedir, getenv, LIBDIR, libintl_nl_default_dirname, LOCALE_ALIAS_PATH, LOCALEDIR, malloc, MAXPATHLEN, memcpy(), strcpy(), and strlen().
_nl_getenv()
char* _nl_getenv (const char * name)
Definition at line 34 of file os2compat.c.
 {
   unsigned char *value;
   if (DosScanEnv (name, &value))
     return NULL;
   else
     return value;
 }
References DosScanEnv(), NULL, and value.
DosScanEnv()
unsigned long DosScanEnv (const unsigned char * pszName, unsigned char ** ppszValue)
Referenced by _nl_getenv().
Variable Documentation
_nlos2_libdir
char* _nlos2_libdir = NULL
Definition at line 46 of file os2compat.c.
Referenced by __attribute__().
_nlos2_localealiaspath
char* _nlos2_localealiaspath = NULL
Definition at line 47 of file os2compat.c.
Referenced by __attribute__().
_nlos2_localedir
char* _nlos2_localedir = NULL
Definition at line 48 of file os2compat.c.
Referenced by __attribute__().
libintl_nl_default_dirname
char libintl_nl_default_dirname[MAXPATHLEN+1]
Definition at line 44 of file os2compat.c.
Referenced by __attribute__().