Fennix Userspace: Userspace/apps/base/busybox/miscutils/flash_eraseall.c File Reference
flash_eraseall.c File Reference
#include "libbb.h"
#include <mtd/mtd-user.h>
#include <linux/jffs2.h>
Macros
#define OPTION_J (1 << 0)
#define OPTION_N (1 << 1)
#define OPTION_Q (1 << 2)
#define IS_NAND (1 << 3)
#define cpu_to_je16(v) ((jint16_t){(v)})
#define cpu_to_je32(v) ((jint32_t){(v)})
Functions
static void show_progress (mtd_info_t *meminfo, erase_info_t *erase)
int flash_eraseall_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
cpu_to_je16
#define cpu_to_je16 (v) ((jint16_t){(v)})
Definition at line 62 of file flash_eraseall.c.
cpu_to_je32
#define cpu_to_je32 (v) ((jint32_t){(v)})
Definition at line 63 of file flash_eraseall.c.
IS_NAND
#define IS_NAND (1 << 3)
Definition at line 40 of file flash_eraseall.c.
OPTION_J
#define OPTION_J (1 << 0)
Definition at line 37 of file flash_eraseall.c.
OPTION_N
#define OPTION_N (1 << 1)
Definition at line 38 of file flash_eraseall.c.
OPTION_Q
#define OPTION_Q (1 << 2)
Definition at line 39 of file flash_eraseall.c.
Function Documentation
flash_eraseall_main()
int flash_eraseall_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 76 of file flash_eraseall.c.
 {
     struct jffs2_unknown_node cleanmarker;
     mtd_info_t meminfo;
     int fd, clmpos, clmlen;
     erase_info_t erase;
     struct stat st;
     unsigned int flags;
     char *mtd_name;
     flags = getopt32(argv, "^" "jNq" "\0" "=1");
     mtd_name = argv[optind];
     fd = xopen(mtd_name, O_RDWR);
     fstat(fd, &st);
     if (!S_ISCHR(st.st_mode))
         bb_error_msg_and_die("%s: not a char device", mtd_name);
     xioctl(fd, MEMGETINFO, &meminfo);
     erase.length = meminfo.erasesize;
     if (meminfo.type == MTD_NANDFLASH)
         flags |= IS_NAND;
     clmpos = 0;
     clmlen = 8;
     if (flags & OPTION_J) {
         uint32_t *crc32_table;
         crc32_table = crc32_new_table_le();
         cleanmarker.magic = cpu_to_je16(JFFS2_MAGIC_BITMASK);
         cleanmarker.nodetype = cpu_to_je16(JFFS2_NODETYPE_CLEANMARKER);
         if (!(flags & IS_NAND))
             cleanmarker.totlen = cpu_to_je32(sizeof(struct jffs2_unknown_node));
         else {
             struct nand_oobinfo oobinfo;
             xioctl(fd, MEMGETOOBSEL, &oobinfo);
             /* Check for autoplacement */
             if (oobinfo.useecc == MTD_NANDECC_AUTOPLACE) {
                 /* Get the position of the free bytes */
                 clmpos = oobinfo.oobfree[0][0];
                 clmlen = oobinfo.oobfree[0][1];
                 if (clmlen > 8)
                     clmlen = 8;
                 if (clmlen == 0)
                     bb_simple_error_msg_and_die("autoplacement selected and no empty space in oob");
             } else {
                 /* Legacy mode */
                 switch (meminfo.oobsize) {
                 case 8:
                     clmpos = 6;
                     clmlen = 2;
                     break;
                 case 16:
                     clmpos = 8;
                     /*clmlen = 8;*/
                     break;
                 case 64:
                     clmpos = 16;
                     /*clmlen = 8;*/
                     break;
                 }
             }
             cleanmarker.totlen = cpu_to_je32(8);
         }
         cleanmarker.hdr_crc = cpu_to_je32(
             crc32_block_endian0(0, &cleanmarker, sizeof(struct jffs2_unknown_node) - 4, crc32_table)
         );
     }
     /* Don't want to destroy progress indicator by bb_error_msg's */
     applet_name = xasprintf("\n%s: %s", applet_name, mtd_name);
     for (erase.start = 0; erase.start < meminfo.size;
          erase.start += meminfo.erasesize) {
         if (!(flags & OPTION_N)) {
             int ret;
             loff_t offset = erase.start;
             ret = ioctl(fd, MEMGETBADBLOCK, &offset);
             if (ret > 0) {
                 if (!(flags & OPTION_Q))
                     printf("\nSkipping bad block at 0x%08x\n", erase.start);
                 continue;
             }
             if (ret < 0) {
                 /* Black block table is not available on certain flash
                  * types e.g. NOR
                  */
                 if (errno == EOPNOTSUPP) {
                     flags |= OPTION_N;
                     if (flags & IS_NAND)
                         bb_simple_error_msg_and_die("bad block check not available");
                 } else {
                     bb_simple_perror_msg_and_die("MEMGETBADBLOCK error");
                 }
             }
         }
         if (!(flags & OPTION_Q))
             show_progress(&meminfo, &erase);
         xioctl(fd, MEMERASE, &erase);
         /* format for JFFS2 ? */
         if (!(flags & OPTION_J))
             continue;
         /* write cleanmarker */
         if (flags & IS_NAND) {
             struct mtd_oob_buf oob;
             oob.ptr = (unsigned char *) &cleanmarker;
             oob.start = erase.start + clmpos;
             oob.length = clmlen;
             xioctl(fd, MEMWRITEOOB, &oob);
         } else {
             xlseek(fd, erase.start, SEEK_SET);
             /* if (lseek(fd, erase.start, SEEK_SET) < 0) {
                 bb_perror_msg("MTD %s failure", "seek");
                 continue;
             } */
             xwrite(fd, &cleanmarker, sizeof(cleanmarker));
             /* if (write(fd, &cleanmarker, sizeof(cleanmarker)) != sizeof(cleanmarker)) {
                 bb_perror_msg("MTD %s failure", "write");
                 continue;
             } */
         }
         if (!(flags & OPTION_Q))
             printf(" Cleanmarker written at %x.", erase.start);
     }
     if (!(flags & OPTION_Q)) {
         show_progress(&meminfo, &erase);
         bb_putchar('\n');
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         close(fd);
     return EXIT_SUCCESS;
 }
References applet_name, argv, bb_error_msg_and_die(), bb_putchar(), bb_simple_error_msg_and_die(), bb_simple_perror_msg_and_die(), close(), cpu_to_je16, cpu_to_je32, crc32_block_endian0(), crc32_new_table_le(), EOPNOTSUPP, errno, EXIT_SUCCESS, fd, flags, fstat(), getopt32(), ioctl(), IS_NAND, O_RDWR, offset, optind, OPTION_J, OPTION_N, OPTION_Q, printf(), S_ISCHR, SEEK_SET, show_progress(), xasprintf(), xioctl, xlseek(), xopen(), and xwrite().
show_progress()
static void show_progress (mtd_info_t * meminfo, erase_info_t * erase) static
Definition at line 65 of file flash_eraseall.c.
 {
     printf("\rErasing %u Kibyte @ %x - %2u%% complete.",
         (unsigned)meminfo->erasesize / 1024,
         erase->start,
         (unsigned) ((unsigned long long) erase->start * 100 / meminfo->size)
     );
     fflush_all();
 }
References fflush_all(), and printf().
Referenced by flash_eraseall_main().