Fennix: Userspace/musl/arch/i386/syscall_arch.h File Reference
syscall_arch.h File Reference
Macros
#define __SYSCALL_LL_E(x)
#define __SYSCALL_LL_O(x) __SYSCALL_LL_E((x))
#define SYSCALL_INSNS "call *%%gs:16"
#define SYSCALL_INSNS_12 "xchg %%ebx,%%edx ; " SYSCALL_INSNS " ; xchg %%ebx,%%edx"
#define SYSCALL_INSNS_34 "xchg %%ebx,%%edi ; " SYSCALL_INSNS " ; xchg %%ebx,%%edi"
#define VDSO_USEFUL
#define VDSO_CGT32_SYM "__vdso_clock_gettime"
#define VDSO_CGT32_VER "LINUX_2.6"
#define VDSO_CGT_SYM "__vdso_clock_gettime64"
#define VDSO_CGT_VER "LINUX_2.6"
Functions
static long __syscall0 (long n)
static long __syscall1 (long n, long a1)
static long __syscall2 (long n, long a1, long a2)
static long __syscall3 (long n, long a1, long a2, long a3)
static long __syscall4 (long n, long a1, long a2, long a3, long a4)
static long __syscall5 (long n, long a1, long a2, long a3, long a4, long a5)
static long __syscall6 (long n, long a1, long a2, long a3, long a4, long a5, long a6)
Macro Definition Documentation
__SYSCALL_LL_E
#define __SYSCALL_LL_E (x)
Value:
((union { long long ll; long l[2]; }){ .ll = x }).l[0], \
((union { long long ll; long l[2]; }){ .ll = x }).l[1]
Definition at line 1 of file syscall_arch.h.
__SYSCALL_LL_O
#define __SYSCALL_LL_O (x) __SYSCALL_LL_E((x))
Definition at line 4 of file syscall_arch.h.
SYSCALL_INSNS
#define SYSCALL_INSNS "call *%%gs:16"
Definition at line 9 of file syscall_arch.h.
SYSCALL_INSNS_12
#define SYSCALL_INSNS_12 "xchg %%ebx,%%edx ; " SYSCALL_INSNS " ; xchg %%ebx,%%edx"
Definition at line 12 of file syscall_arch.h.
SYSCALL_INSNS_34
#define SYSCALL_INSNS_34 "xchg %%ebx,%%edi ; " SYSCALL_INSNS " ; xchg %%ebx,%%edi"
Definition at line 13 of file syscall_arch.h.
VDSO_CGT32_SYM
#define VDSO_CGT32_SYM "__vdso_clock_gettime"
Definition at line 86 of file syscall_arch.h.
VDSO_CGT32_VER
#define VDSO_CGT32_VER "LINUX_2.6"
Definition at line 87 of file syscall_arch.h.
VDSO_CGT_SYM
#define VDSO_CGT_SYM "__vdso_clock_gettime64"
Definition at line 88 of file syscall_arch.h.
VDSO_CGT_VER
#define VDSO_CGT_VER "LINUX_2.6"
Definition at line 89 of file syscall_arch.h.
VDSO_USEFUL
#define VDSO_USEFUL
Definition at line 85 of file syscall_arch.h.
Function Documentation
__syscall0()
static long __syscall0 (long n) inline static
Definition at line 15 of file syscall_arch.h.
 {
     unsigned long __ret;
     __asm__ __volatile__ (SYSCALL_INSNS : "=a"(__ret) : "a"(n) : "memory");
     return __ret;
 }
References __asm__(), n, and SYSCALL_INSNS.
__syscall1()
static long __syscall1 (long n, long a1) inline static
Definition at line 22 of file syscall_arch.h.
 {
     unsigned long __ret;
     __asm__ __volatile__ (SYSCALL_INSNS_12 : "=a"(__ret) : "a"(n), "d"(a1) : "memory");
     return __ret;
 }
References __asm__(), a1, n, and SYSCALL_INSNS_12.
__syscall2()
static long __syscall2 (long n, long a1, long a2) inline static
Definition at line 29 of file syscall_arch.h.
 {
     unsigned long __ret;
     __asm__ __volatile__ (SYSCALL_INSNS_12 : "=a"(__ret) : "a"(n), "d"(a1), "c"(a2) : "memory");
     return __ret;
 }
References __asm__(), a1, a2, n, and SYSCALL_INSNS_12.
__syscall3()
static long __syscall3 (long n, long a1, long a2, long a3) inline static
Definition at line 36 of file syscall_arch.h.
 {
     unsigned long __ret;
 #if !defined(__PIC__) || !defined(BROKEN_EBX_ASM)
     __asm__ __volatile__ (SYSCALL_INSNS : "=a"(__ret) : "a"(n), "b"(a1), "c"(a2), "d"(a3) : "memory");
 #else
     __asm__ __volatile__ (SYSCALL_INSNS_34 : "=a"(__ret) : "a"(n), "D"(a1), "c"(a2), "d"(a3) : "memory");
 #endif
     return __ret;
 }
References __asm__(), a1, a2, a3, n, SYSCALL_INSNS, and SYSCALL_INSNS_34.
__syscall4()
static long __syscall4 (long n, long a1, long a2, long a3, long a4) inline static
Definition at line 47 of file syscall_arch.h.
 {
     unsigned long __ret;
 #if !defined(__PIC__) || !defined(BROKEN_EBX_ASM)
     __asm__ __volatile__ (SYSCALL_INSNS : "=a"(__ret) : "a"(n), "b"(a1), "c"(a2), "d"(a3), "S"(a4) : "memory");
 #else
     __asm__ __volatile__ (SYSCALL_INSNS_34 : "=a"(__ret) : "a"(n), "D"(a1), "c"(a2), "d"(a3), "S"(a4) : "memory");
 #endif
     return __ret;
 }
References __asm__(), a1, a2, a3, a4, n, SYSCALL_INSNS, and SYSCALL_INSNS_34.
__syscall5()
static long __syscall5 (long n, long a1, long a2, long a3, long a4, long a5) inline static
Definition at line 58 of file syscall_arch.h.
 {
     unsigned long __ret;
 #if !defined(__PIC__) || !defined(BROKEN_EBX_ASM)
     __asm__ __volatile__ (SYSCALL_INSNS
         : "=a"(__ret) : "a"(n), "b"(a1), "c"(a2), "d"(a3), "S"(a4), "D"(a5) : "memory");
 #else
     __asm__ __volatile__ ("pushl %2 ; push %%ebx ; mov 4(%%esp),%%ebx ; " SYSCALL_INSNS " ; pop %%ebx ; add $4,%%esp"
         : "=a"(__ret) : "a"(n), "g"(a1), "c"(a2), "d"(a3), "S"(a4), "D"(a5) : "memory");
 #endif
     return __ret;
 }
References __asm__(), a1, a2, a3, a4, a5, n, and SYSCALL_INSNS.
__syscall6()
static long __syscall6 (long n, long a1, long a2, long a3, long a4, long a5, long a6) inline static
Definition at line 71 of file syscall_arch.h.
 {
     unsigned long __ret;
 #if !defined(__PIC__) || !defined(BROKEN_EBX_ASM)
     __asm__ __volatile__ ("pushl %7 ; push %%ebp ; mov 4(%%esp),%%ebp ; " SYSCALL_INSNS " ; pop %%ebp ; add $4,%%esp"
         : "=a"(__ret) : "a"(n), "b"(a1), "c"(a2), "d"(a3), "S"(a4), "D"(a5), "g"(a6) : "memory");
 #else
     unsigned long a1a6[2] = { a1, a6 };
     __asm__ __volatile__ ("pushl %1 ; push %%ebx ; push %%ebp ; mov 8(%%esp),%%ebx ; mov 4(%%ebx),%%ebp ; mov (%%ebx),%%ebx ; " SYSCALL_INSNS " ; pop %%ebp ; pop %%ebx ; add $4,%%esp"
         : "=a"(__ret) : "g"(&a1a6), "a"(n), "c"(a2), "d"(a3), "S"(a4), "D"(a5) : "memory");
 #endif
     return __ret;
 }
References __asm__(), a1, a2, a3, a4, a5, a6, n, and SYSCALL_INSNS.