Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/doomgeneric_fennix.c File Reference
doomgeneric_fennix.c File Reference
#include "doomkeys.h"
#include "doomgeneric.h"
#include <stdio.h>
#include <fennix/syscall.h>
Macros
#define KEYQUEUE_SIZE 16
Functions
static unsigned char convertToDoomKey (unsigned char key)
static void addKeyToQueue (int pressed, unsigned char keyCode)
void DG_Init ()
void DG_DrawFrame ()
void DG_SleepMs (uint32_t ms)
uint32_t DG_GetTicksMs ()
int DG_GetKey (int *pressed, unsigned char *doomKey)
void DG_SetWindowTitle (const char *title)
int main (int argc, char **argv)
Variables
static unsigned short s_KeyQueue [KEYQUEUE_SIZE]
static unsigned int s_KeyQueueWriteIndex = 0
static unsigned int s_KeyQueueReadIndex = 0
Macro Definition Documentation
KEYQUEUE_SIZE
#define KEYQUEUE_SIZE 16
Definition at line 8 of file doomgeneric_fennix.c.
Function Documentation
addKeyToQueue()
static void addKeyToQueue (int pressed, unsigned char keyCode) static
Definition at line 53 of file doomgeneric_fennix.c.
 {
     unsigned char key = convertToDoomKey(keyCode);
     unsigned short keyData = (pressed << 8) | key;
     s_KeyQueue[s_KeyQueueWriteIndex] = keyData;
     s_KeyQueueWriteIndex++;
     s_KeyQueueWriteIndex %= KEYQUEUE_SIZE;
 }
References convertToDoomKey(), KEYQUEUE_SIZE, s_KeyQueue, and s_KeyQueueWriteIndex.
convertToDoomKey()
static unsigned char convertToDoomKey (unsigned char key) static
Definition at line 14 of file doomgeneric_fennix.c.
 {
     // switch (key)
     // {
     // case VK_RETURN:
     //  key = KEY_ENTER;
     //  break;
     // case VK_ESCAPE:
     //  key = KEY_ESCAPE;
     //  break;
     // case VK_LEFT:
     //  key = KEY_LEFTARROW;
     //  break;
     // case VK_RIGHT:
     //  key = KEY_RIGHTARROW;
     //  break;
     // case VK_UP:
     //  key = KEY_UPARROW;
     //  break;
     // case VK_DOWN:
     //  key = KEY_DOWNARROW;
     //  break;
     // case VK_CONTROL:
     //  key = KEY_FIRE;
     //  break;
     // case VK_SPACE:
     //  key = KEY_USE;
     //  break;
     // case VK_SHIFT:
     //  key = KEY_RSHIFT;
     //  break;
     // default:
     //  key = tolower(key);
     //  break;
     // }
     return key;
 }
Referenced by addKeyToQueue().
DG_DrawFrame()
void DG_DrawFrame ()
Definition at line 69 of file doomgeneric_fennix.c.
 {
     // syscall1(sys_Print, 'H');
         // StretchDIBits(s_Hdc, 0, 0, DOOMGENERIC_RESX, DOOMGENERIC_RESY, 0, 0, DOOMGENERIC_RESX, DOOMGENERIC_RESY, DG_ScreenBuffer);
 }
Referenced by I_FinishUpdate().
DG_GetKey()
int DG_GetKey (int * pressed, unsigned char * doomKey)
Definition at line 86 of file doomgeneric_fennix.c.
 {
     if (s_KeyQueueReadIndex == s_KeyQueueWriteIndex)
     {
         //key queue is empty
         return 0;
     }
     else
     {
         unsigned short keyData = s_KeyQueue[s_KeyQueueReadIndex];
         s_KeyQueueReadIndex++;
         s_KeyQueueReadIndex %= KEYQUEUE_SIZE;
         *pressed = keyData >> 8;
         *doomKey = keyData & 0xFF;
         return 1;
     }
 }
References KEYQUEUE_SIZE, s_KeyQueue, s_KeyQueueReadIndex, and s_KeyQueueWriteIndex.
Referenced by I_GetEvent().
DG_GetTicksMs()
uint32_t DG_GetTicksMs ()
Definition at line 80 of file doomgeneric_fennix.c.
 {
     static uint32_t stub;
     return ++stub; // TODO
 }
Referenced by I_GetTicks().
DG_Init()
void DG_Init ()
Definition at line 64 of file doomgeneric_fennix.c.
 {
     memset(s_KeyQueue, 0, KEYQUEUE_SIZE * sizeof(unsigned short));
 }
References KEYQUEUE_SIZE, memset(), and s_KeyQueue.
Referenced by doomgeneric_Create().
DG_SetWindowTitle()
void DG_SetWindowTitle (const char * title)
Definition at line 107 of file doomgeneric_fennix.c.
 {
     // for (int i = 0; i < 14; i++)
     //  syscall1(sys_Print, "Window Title: "[i]);
     // for (int i = 0; title[i] != '\0'; i++)
     // {
     //  syscall1(sys_Print, title[i]);
     // }
     // syscall1(sys_Print, '\n');
 }
Referenced by I_SetWindowTitle().
DG_SleepMs()
void DG_SleepMs (uint32_t ms)
Definition at line 75 of file doomgeneric_fennix.c.
 {
     // syscall1(sys_Sleep, ms);
 }
Referenced by I_Sleep().
main()
int main (int argc , char ** argv)
Definition at line 119 of file doomgeneric_fennix.c.
 {
     doomgeneric_Create(argc, argv);
     for (int i = 0; ; i++)
     {
         doomgeneric_Tick();
     }
     return 0;
 }
References argc, argv, doomgeneric_Create(), doomgeneric_Tick(), and i.
Variable Documentation
s_KeyQueue
unsigned short s_KeyQueue[KEYQUEUE_SIZE] static
Definition at line 10 of file doomgeneric_fennix.c.
Referenced by addKeyToQueue(), DG_GetKey(), and DG_Init().
s_KeyQueueReadIndex
unsigned int s_KeyQueueReadIndex = 0 static
Definition at line 12 of file doomgeneric_fennix.c.
Referenced by DG_GetKey().
s_KeyQueueWriteIndex
unsigned int s_KeyQueueWriteIndex = 0 static
Definition at line 11 of file doomgeneric_fennix.c.
Referenced by addKeyToQueue(), and DG_GetKey().