Fennix Userspace: Userspace/musl/src/unistd/close.c File Reference
close.c File Reference
#include <unistd.h>
#include <errno.h>
#include "aio_impl.h"
#include "syscall.h"
Functions
static int dummy (int fd)
weak_alias (dummy, __aio_close)
int close (int fd)
Function Documentation
close()
int close (int fd)
Definition at line 13 of file close.c.
 {
     fd = __aio_close(fd);
     int r = __syscall_cp(SYS_close, fd);
     if (r == -EINTR) r = 0;
     return __syscall_ret(r);
 }
References __aio_close(), __syscall_cp, __syscall_ret(), EINTR, and fd.
Referenced by __dls3(), __lookup_name(), __nscd_query(), __res_msend_rc(), _evalfile(), _nl_load_domain(), _rl_read_file(), _vsyslog(), accept_builtin(), acpid_main(), archivefile(), arpping(), askremotedate(), async_redirect_stdin(), awk_main(), bb_cat(), bb_daemonize_or_rexec(), bb_init_module(), beep_main(), blkdiscard_main(), blockdev_main(), brctl_main(), cat_file(), cat_main(), change_attributes(), change_listen_mode(), chat_main(), check_dev_tty(), check_mount(), child(), chpst_main(), cksum_main(), clean_up_and_exit(), cleanup(), close_fd_bitmap(), close_pipes(), closedir(), closelog(), closescript(), command_substitute(), common_ping_main(), ConfigMainWindow::ConfigMainWindow(), conspy_main(), copy_file(), copy_inode(), create_cdev_if_doesnt_exist(), crontab_main(), cttyhack_main(), cutfile(), d6_read_interface(), d6_send_kernel_packet_from_client_data_ifindex(), d6_send_raw_packet_from_client_data_ifindex(), daemon(), data_extract_all(), data_extract_to_command(), deb_extract_control_file_to_buffer(), del_loop(), delete_tempfile(), devmem_main(), dialog_textbox(), diffreg(), do_add_ioctl(), do_changename(), do_chflags(), do_config_file(), do_del_ioctl(), do_get_ioctl(), do_io_until_eof_and_exit(), do_ioctl_get_ifindex(), do_ioctl_get_ifname(), do_ioctl_get_iftype(), do_logging(), do_nftw(), do_piping(), do_redirection_internal(), do_syslogd(), do_wordexp(), dolisten(), download_one_url(), dpkg_deb_main(), dprintf(), dump_file(), dump_procs(), dumpkmap_main(), dup2(), edir(), eject_main(), ether_wake_main(), evalbackcmd(), evalpipe(), exec_conf(), execute_pipeline(), expbackq(), extract_info(), fail_hunk(), fatattr_main(), fb_open(), fbset_main(), fdformat_main(), fdisk_main(), file_insert(), file_write(), filter_rename_config(), flash_eraseall_main(), fmtmsg(), fork_transformer(), forkchild(), forkpty(), free_volume_id(), freeramdisk_main(), from_sys_clock(), fstrim_main(), ftpd_main(), get_address(), get_boot(), get_console_fd_or_die(), get_free_loop(), get_terminal_width_height(), getaddrinfo(), getpass(), getspnam_r(), getty_main(), handle_dir_common(), handle_retr(), hash_file(), here_document_to_fd(), hfclose(), history_do_write(), history_truncate_file(), if_fetch(), if_readconf(), ifconfig_main(), INET_setroute(), inetd_main(), iproute_flush_cache(), is_whole_disk(), isrv_close_fd(), kbd_mode_main(), klogd_close(), last_main(), launch_helper(), list_attributes(), load_firmware(), load_library(), loadkmap_main(), log_locally(), logdir_close(), login_tty(), lpd_main(), lpqr_main(), make_new_session(), maybe_close(), microcom_main(), mini_httpd_nommu(), mkfs_ext2_main(), mkfs_vfat_main(), mkswap_main(), mktemp_builtin(), motd(), move_to_high_fd(), nandwrite_main(), nbdclient_main(), nc_main(), noclobber_open(), nohup_main(), nsenter_main(), ntpd_main(), open_shell_script(), open_stdio_to_tty(), open_tty(), openhere(), openpty(), openredirect(), openvt_main(), optimize_cat_file(), parse(), parse_comsub(), parse_matched_pair(), partprobe_main(), patch_main(), popen_ls(), popfile(), popredir(), port_pasv_cleanup(), posix_close(), posix_spawn(), prepare_socket_fd(), print_deps(), print_queuelen(), processorstart(), pscan_main(), pthread_getname_np(), pthread_setname_np(), pump_data_and_QUIT(), query_loop(), read_close(), read_history_range(), read_leases(), read_new_seed(), read_rtc(), read_to_buf(), readahead_main(), readfile_z(), readLines(), readprofile_main(), readwrite(), recv_and_process_peer_pkt(), redirect(), refill_HFILE_and_getc(), restart_job_control(), restore_redirects(), restore_state_and_exit(), restore_stdin(), rtcwake_main(), run_pipe(), runsv_main(), rx_main(), savefd(), scan_proc_net_or_maps(), screen_read_close(), script_main(), scriptreplay_main(), seed_from_file_if_exists(), sem_open(), send_query_to_peer(), serial_ctl(), set_address(), set_loop(), set_mtu(), set_qlen(), setup_heredoc(), setup_redirects(), sh_closepipe(), sh_mktmpfp(), show_textbox(), shutdown_watchdog(), singlemount(), skip_matched_pair(), start(), start_shell_in_child(), start_tcp(), startservice(), step_time(), sulogin_main(), sum_file(), sysctl_act_on_setting(), tar_main(), tcpudpsvd_main(), tee_builtin(), telnetd_main(), test_ptmx(), test_watch_directory(), test_watch_file(), tgetent(), touch(), tsort_main(), ubi_tools_main(), udhcp_read_interface(), udhcp_send_kernel_packet(), udhcp_send_raw_packet(), udhcpd_main(), uevent_main(), uniq_main(), unshare_main(), unzip_main(), update_status(), urandom_close(), volname_main(), wait_for_seqfile(), wall_main(), watch_main(), write_leases(), write_pidfile(), writeLines(), xclose(), xconnect(), xdup_CLOEXEC_and_close(), xmalloc_open_read_close(), xmove_fd(), xopen_xwrite_close(), xsendto(), and xtrace_reset().
dummy()
static int dummy (int fd) static
Definition at line 6 of file close.c.
 {
     return fd;
 }
References fd.
weak_alias()
weak_alias (dummy , __aio_close)