Fennix: Userspace/musl/src/malloc/mallocng/meta.h File Reference
meta.h File Reference
#include <stdint.h>
#include <errno.h>
#include <limits.h>
#include "glue.h"
Data Structures
struct group
struct meta
struct meta_area
struct malloc_context
Macros
#define MMAP_THRESHOLD 131052
#define UNIT 16
#define IB 4
#define PGSZ PAGESIZE
Functions
__attribute__ ((__visibility__("hidden"))) extern const uint16_t size_classes[]
static void queue (struct meta **phead, struct meta *m)
static void dequeue (struct meta **phead, struct meta *m)
static struct meta * dequeue_head (struct meta **phead)
static void free_meta (struct meta *m)
static uint32_t activate_group (struct meta *m)
static int get_slot_index (const unsigned char *p)
static struct meta * get_meta (const unsigned char *p)
static size_t get_nominal_size (const unsigned char *p, const unsigned char *end)
static size_t get_stride (const struct meta *g)
static void set_size (unsigned char *p, unsigned char *end, size_t n)
static void * enframe (struct meta *g, int idx, size_t n, int ctr)
static int size_to_class (size_t n)
static int size_overflows (size_t n)
static void step_seq (void)
static void record_seq (int sc)
static void account_bounce (int sc)
static void decay_bounces (int sc)
static int is_bouncing (int sc)
Data Structure Documentation
group
struct group
Definition at line 19 of file grp.h.
Data Fields
unsigned char active_idx:5
gid_t gr_gid
char ** gr_mem
char * gr_name
char * gr_passwd
struct meta * meta
char pad[UNIT - sizeof(struct meta *) - 1]
unsigned char storage[]
meta
struct meta
Definition at line 24 of file meta.h.
Data Fields
volatile int avail_mask
uintptr_t freeable:1
volatile int freed_mask
uintptr_t last_idx:5
uintptr_t maplen:8*sizeof(uintptr_t)-12
struct group * mem
struct meta * next
struct meta * prev
uintptr_t sizeclass:6
meta_area
struct meta_area
Definition at line 34 of file meta.h.
Data Fields
uint64_t check
struct meta_area * next
int nslots
struct meta slots[]
malloc_context
struct malloc_context
Definition at line 41 of file meta.h.
Data Fields
struct meta * active[48]
struct meta * avail_meta
size_t avail_meta_area_count
unsigned char * avail_meta_areas
size_t avail_meta_count
uint8_t bounces[32]
uintptr_t brk
struct meta * free_meta_head
int init_done
size_t meta_alloc_shift
struct meta_area * meta_area_head
struct meta_area * meta_area_tail
unsigned mmap_counter
uint64_t secret
uint8_t seq
uint8_t unmap_seq[32]
size_t usage_by_class[48]
Macro Definition Documentation
IB
#define IB 4
Definition at line 15 of file meta.h.
MMAP_THRESHOLD
#define MMAP_THRESHOLD 131052
Definition at line 12 of file meta.h.
PGSZ
#define PGSZ PAGESIZE
Definition at line 64 of file meta.h.
UNIT
#define UNIT 16
Definition at line 14 of file meta.h.
Function Documentation
__attribute__()
__attribute__ ((__visibility__("hidden"))) const
account_bounce()
static void account_bounce (int sc) inline static
Definition at line 264 of file meta.h.
 {
     if (sc-7U < 32) {
         int seq = ctx.unmap_seq[sc-7];
         if (seq && ctx.seq-seq < 10) {
             if (ctx.bounces[sc-7]+1 < 100)
                 ctx.bounces[sc-7]++;
             else
                 ctx.bounces[sc-7] = 150;
         }
     }
 }
References seq.
Referenced by alloc_group().
activate_group()
static uint32_t activate_group (struct meta * m) inline static
Definition at line 115 of file meta.h.
 {
     assert(!m->avail_mask);
     uint32_t mask, act = (2u<<m->mem->active_idx)-1;
     do mask = m->freed_mask;
     while (a_cas(&m->freed_mask, mask, mask&~act)!=mask);
     return m->avail_mask = mask & act;
 }
References a_cas, act(), group::active_idx, assert, meta::avail_mask, meta::freed_mask, and meta::mem.
Referenced by try_avail().
decay_bounces()
static void decay_bounces (int sc) inline static
Definition at line 277 of file meta.h.
 {
     if (sc-7U < 32 && ctx.bounces[sc-7])
         ctx.bounces[sc-7]--;
 }
Referenced by try_avail().
dequeue()
static void dequeue (struct meta ** phead, struct meta * m) inline static
Definition at line 90 of file meta.h.
 {
     if (m->next != m) {
         m->prev->next = m->next;
         m->next->prev = m->prev;
         if (*phead == m) *phead = m->next;
     } else {
         *phead = 0;
     }
     m->prev = m->next = 0;
 }
References meta::next, and meta::prev.
Referenced by dequeue_head(), and try_avail().
dequeue_head()
static struct meta* dequeue_head (struct meta ** phead) inline static
Definition at line 102 of file meta.h.
 {
     struct meta *m = *phead;
     if (m) dequeue(phead, m);
     return m;
 }
References dequeue().
Referenced by alloc_meta().
enframe()
static void* enframe (struct meta * g, int idx, size_t n, int ctr) inline static
Definition at line 196 of file meta.h.
 {
     size_t stride = get_stride(g);
     size_t slack = (stride-IB-n)/UNIT;
     unsigned char *p = g->mem->storage + stride*idx;
     unsigned char *end = p+stride-IB;
     // cycle offset within slot to increase interval to address
     // reuse, facilitate trapping double-free.
     int off = (p[-3] ? *(uint16_t *)(p-2) + 1 : ctr) & 255;
     assert(!p[-4]);
     if (off > slack) {
         size_t m = slack;
         m |= m>>1; m |= m>>2; m |= m>>4;
         off &= m;
         if (off > slack) off -= slack+1;
         assert(off <= slack);
     }
     if (off) {
         // store offset in unused header at offset zero
         // if enframing at non-zero offset.
         *(uint16_t *)(p-2) = off;
         p[-3] = 7<<5;
         p += UNIT*off;
         // for nonzero offset there is no permanent check
         // byte, so make one.
         p[-4] = 0;
     }
     *(uint16_t *)(p-2) = (size_t)(p-g->mem->storage)/UNIT;
     p[-3] = idx;
     set_size(p, end, n);
     return p;
 }
References assert, end, g, get_stride(), IB, idx, n, off, p, set_size(), and UNIT.
Referenced by alloc_group(), and malloc().
free_meta()
static void free_meta (struct meta * m) inline static
Definition at line 109 of file meta.h.
 {
     *m = (struct meta){0};
     queue(&ctx.free_meta_head, m);
 }
References queue().
Referenced by alloc_group().
get_meta()
static struct meta* get_meta (const unsigned char * p) inline static
Definition at line 129 of file meta.h.
 {
     assert(!((uintptr_t)p & 15));
     int offset = *(const uint16_t *)(p - 2);
     int index = get_slot_index(p);
     if (p[-4]) {
         assert(!offset);
         offset = *(uint32_t *)(p - 8);
         assert(offset > 0xffff);
     }
     const struct group *base = (const void *)(p - UNIT*offset - UNIT);
     const struct meta *meta = base->meta;
     assert(meta->mem == base);
     assert(index <= meta->last_idx);
     assert(!(meta->avail_mask & (1u<<index)));
     assert(!(meta->freed_mask & (1u<<index)));
     const struct meta_area *area = (void *)((uintptr_t)meta & -4096);
     assert(area->check == ctx.secret);
     if (meta->sizeclass < 48) {
         assert(offset >= size_classes[meta->sizeclass]*index);
         assert(offset < size_classes[meta->sizeclass]*(index+1));
     } else {
         assert(meta->sizeclass == 63);
     }
     if (meta->maplen) {
         assert(offset <= meta->maplen*4096UL/UNIT - 1);
     }
     return (struct meta *)meta;
 }
References assert, meta::avail_mask, base, meta_area::check, meta::freed_mask, get_slot_index(), index(), meta::last_idx, meta::maplen, meta::mem, offset, p, size_classes, meta::sizeclass, and UNIT.
Referenced by aligned_alloc(), free(), is_allzero(), malloc_usable_size(), and realloc().
get_nominal_size()
static size_t get_nominal_size (const unsigned char * p, const unsigned char * end) inline static
Definition at line 159 of file meta.h.
 {
     size_t reserved = p[-3] >> 5;
     if (reserved >= 5) {
         assert(reserved == 5);
         reserved = *(const uint32_t *)(end-4);
         assert(reserved >= 5);
         assert(!end[-5]);
     }
     assert(reserved <= end-p);
     assert(!*(end-reserved));
     // also check the slot's overflow byte
     assert(!*end);
     return end-reserved-p;
 }
References assert, end, and p.
Referenced by free(), malloc_usable_size(), and realloc().
get_slot_index()
static int get_slot_index (const unsigned char * p) inline static
Definition at line 124 of file meta.h.
 {
     return p[-3] & 31;
 }
References p.
Referenced by aligned_alloc(), free(), get_meta(), malloc_usable_size(), and realloc().
get_stride()
static size_t get_stride (const struct meta * g) inline static
Definition at line 175 of file meta.h.
 {
     if (!g->last_idx && g->maplen) {
         return g->maplen*4096UL - UNIT;
     } else {
         return UNIT*size_classes[g->sizeclass];
     }
 }
References g, size_classes, and UNIT.
Referenced by aligned_alloc(), enframe(), free(), is_allzero(), malloc_usable_size(), nontrivial_free(), and realloc().
is_bouncing()
static int is_bouncing (int sc) inline static
Definition at line 283 of file meta.h.
 {
     return (sc-7U < 32 && ctx.bounces[sc-7] >= 100);
 }
Referenced by alloc_group(), and nontrivial_free().
queue()
static void queue (struct meta ** phead, struct meta * m) inline static
Definition at line 75 of file meta.h.
 {
     assert(!m->next);
     assert(!m->prev);
     if (*phead) {
         struct meta *head = *phead;
         m->next = head;
         m->prev = head->prev;
         m->next->prev = m->prev->next = m;
     } else {
         m->prev = m->next = m;
         *phead = m;
     }
 }
References assert, and head.
Referenced by alloc_slot(), do_init_fini(), donate(), free_meta(), lpd_main(), lpqr_main(), queue_ctors(), and tcflush().
record_seq()
static void record_seq (int sc) inline static
Definition at line 259 of file meta.h.
 {
     if (sc-7U < 32) ctx.unmap_seq[sc-7] = ctx.seq;
 }
set_size()
static void set_size (unsigned char * p, unsigned char * end, size_t n) inline static
Definition at line 184 of file meta.h.
 {
     int reserved = end-p-n;
     if (reserved) end[-reserved] = 0;
     if (reserved >= 5) {
         *(uint32_t *)(end-4) = reserved;
         end[-5] = 0;
         reserved = 5;
     }
     p[-3] = (p[-3]&31) + (reserved<<5);
 }
References end, n, and p.
Referenced by aligned_alloc(), enframe(), and realloc().
size_overflows()
static int size_overflows (size_t n) inline static
Definition at line 240 of file meta.h.
 {
     if (n >= SIZE_MAX/2 - 4096) {
         errno = ENOMEM;
         return 1;
     }
     return 0;
 }
References ENOMEM, errno, n, and SIZE_MAX.
Referenced by malloc(), and realloc().
size_to_class()
static int size_to_class (size_t n) inline static
Definition at line 229 of file meta.h.
 {
     n = (n+IB-1)>>4;
     if (n<10) return n;
     n++;
     int i = (28-a_clz_32(n))*4 + 8;
     if (n>size_classes[i+1]) i+=2;
     if (n>size_classes[i]) i++;
     return i;
 }
References a_clz_32, i, IB, n, and size_classes.
Referenced by alloc_group(), malloc(), and realloc().
step_seq()
static void step_seq (void) inline static
Definition at line 249 of file meta.h.
 {
     if (ctx.seq==255) {
         for (int i=0; i<32; i++) ctx.unmap_seq[i] = 0;
         ctx.seq = 1;
     } else {
         ctx.seq++;
     }
 }
References i.
Referenced by alloc_group(), and malloc().