Fennix Userspace: Userspace/musl/arch/arm/syscall_arch.h File Reference
syscall_arch.h File Reference
Macros
#define __SYSCALL_LL_E(x)
#define __SYSCALL_LL_O(x) 0, __SYSCALL_LL_E((x))
#define __ASM____R7__ __asm__("r7")
#define __asm_syscall(...)
#define R7_OPERAND "r"(r7)
#define SYSCALL_FADVISE_6_ARG
#define SYSCALL_IPC_BROKEN_MODE
#define VDSO_USEFUL
#define VDSO_CGT32_SYM "__vdso_clock_gettime"
#define VDSO_CGT32_VER "LINUX_2.6"
#define VDSO_CGT_SYM "__vdso_clock_gettime64"
#define VDSO_CGT_VER "LINUX_2.6"
#define VDSO_CGT_WORKAROUND 1
Functions
static long __syscall0 (long n)
static long __syscall1 (long n, long a)
static long __syscall2 (long n, long a, long b)
static long __syscall3 (long n, long a, long b, long c)
static long __syscall4 (long n, long a, long b, long c, long d)
static long __syscall5 (long n, long a, long b, long c, long d, long e)
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f)
Macro Definition Documentation
__ASM____R7__
#define __ASM____R7__ __asm__("r7")
Definition at line 19 of file syscall_arch.h.
__asm_syscall
#define __asm_syscall (...)
Value:
    do { \
    __asm__ __volatile__ ( "svc 0" \
    : "=r"(r0) : __VA_ARGS__ : "memory"); \
    return r0; \
    } while (0)
Definition at line 20 of file syscall_arch.h.
__SYSCALL_LL_E
#define __SYSCALL_LL_E (x)
Value:
((union { long long ll; long l[2]; }){ .ll = x }).l[0], \
((union { long long ll; long l[2]; }){ .ll = x }).l[1]
Definition at line 1 of file syscall_arch.h.
__SYSCALL_LL_O
#define __SYSCALL_LL_O (x) 0, __SYSCALL_LL_E((x))
Definition at line 4 of file syscall_arch.h.
R7_OPERAND
#define R7_OPERAND "r"(r7)
Definition at line 34 of file syscall_arch.h.
SYSCALL_FADVISE_6_ARG
#define SYSCALL_FADVISE_6_ARG
Definition at line 101 of file syscall_arch.h.
SYSCALL_IPC_BROKEN_MODE
#define SYSCALL_IPC_BROKEN_MODE
Definition at line 103 of file syscall_arch.h.
VDSO_CGT32_SYM
#define VDSO_CGT32_SYM "__vdso_clock_gettime"
Definition at line 106 of file syscall_arch.h.
VDSO_CGT32_VER
#define VDSO_CGT32_VER "LINUX_2.6"
Definition at line 107 of file syscall_arch.h.
VDSO_CGT_SYM
#define VDSO_CGT_SYM "__vdso_clock_gettime64"
Definition at line 108 of file syscall_arch.h.
VDSO_CGT_VER
#define VDSO_CGT_VER "LINUX_2.6"
Definition at line 109 of file syscall_arch.h.
VDSO_CGT_WORKAROUND
#define VDSO_CGT_WORKAROUND 1
Definition at line 110 of file syscall_arch.h.
VDSO_USEFUL
#define VDSO_USEFUL
Definition at line 105 of file syscall_arch.h.
Function Documentation
__syscall0()
static long __syscall0 (long n) inline static
Definition at line 37 of file syscall_arch.h.
 {
     register long r7 __ASM____R7__ = n;
     register long r0 __asm__("r0");
     __asm_syscall(R7_OPERAND);
 }
References __asm__(), __ASM____R7__, __asm_syscall, n, r0, and R7_OPERAND.
__syscall1()
static long __syscall1 (long n, long a) inline static
Definition at line 44 of file syscall_arch.h.
 {
     register long r7 __ASM____R7__ = n;
     register long r0 __asm__("r0") = a;
     __asm_syscall(R7_OPERAND, "0"(r0));
 }
References __asm__(), __ASM____R7__, __asm_syscall, n, r0, and R7_OPERAND.
__syscall2()
static long __syscall2 (long n, long a, long b) inline static
Definition at line 51 of file syscall_arch.h.
 {
     register long r7 __ASM____R7__ = n;
     register long r0 __asm__("r0") = a;
     register long r1 __asm__("r1") = b;
     __asm_syscall(R7_OPERAND, "0"(r0), "r"(r1));
 }
References __asm__(), __ASM____R7__, __asm_syscall, n, r0, r1, and R7_OPERAND.
__syscall3()
static long __syscall3 (long n, long a, long b, long c) inline static
Definition at line 59 of file syscall_arch.h.
 {
     register long r7 __ASM____R7__ = n;
     register long r0 __asm__("r0") = a;
     register long r1 __asm__("r1") = b;
     register long r2 __asm__("r2") = c;
     __asm_syscall(R7_OPERAND, "0"(r0), "r"(r1), "r"(r2));
 }
References __asm__(), __ASM____R7__, __asm_syscall, c, n, r0, r1, r2, and R7_OPERAND.
__syscall4()
static long __syscall4 (long n, long a, long b, long c, long d) inline static
Definition at line 68 of file syscall_arch.h.
 {
     register long r7 __ASM____R7__ = n;
     register long r0 __asm__("r0") = a;
     register long r1 __asm__("r1") = b;
     register long r2 __asm__("r2") = c;
     register long r3 __asm__("r3") = d;
     __asm_syscall(R7_OPERAND, "0"(r0), "r"(r1), "r"(r2), "r"(r3));
 }
References __asm__(), __ASM____R7__, __asm_syscall, c, n, r0, r1, r2, r3, and R7_OPERAND.
__syscall5()
static long __syscall5 (long n, long a, long b, long c, long d, long e) inline static
Definition at line 78 of file syscall_arch.h.
 {
     register long r7 __ASM____R7__ = n;
     register long r0 __asm__("r0") = a;
     register long r1 __asm__("r1") = b;
     register long r2 __asm__("r2") = c;
     register long r3 __asm__("r3") = d;
     register long r4 __asm__("r4") = e;
     __asm_syscall(R7_OPERAND, "0"(r0), "r"(r1), "r"(r2), "r"(r3), "r"(r4));
 }
References __asm__(), __ASM____R7__, __asm_syscall, c, n, r0, r1, r2, r3, r4, and R7_OPERAND.
__syscall6()
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f) inline static
Definition at line 89 of file syscall_arch.h.
 {
     register long r7 __ASM____R7__ = n;
     register long r0 __asm__("r0") = a;
     register long r1 __asm__("r1") = b;
     register long r2 __asm__("r2") = c;
     register long r3 __asm__("r3") = d;
     register long r4 __asm__("r4") = e;
     register long r5 __asm__("r5") = f;
     __asm_syscall(R7_OPERAND, "0"(r0), "r"(r1), "r"(r2), "r"(r3), "r"(r4), "r"(r5));
 }
References __asm__(), __ASM____R7__, __asm_syscall, c, f, n, r0, r1, r2, r3, r4, r5, and R7_OPERAND.