Fennix Userspace: Userspace/apps/base/busybox/coreutils/chown.c File Reference
chown.c File Reference
#include "libbb.h"
Data Structures
struct param_t
Macros
#define OPT_STR "Rh" IF_DESKTOP("vcfLHP")
#define BIT_RECURSE 1
#define OPT_RECURSE (opt & 1)
#define OPT_NODEREF (opt & 2)
#define OPT_VERBOSE (IF_DESKTOP(opt & 0x04) IF_NOT_DESKTOP(0))
#define OPT_CHANGED (IF_DESKTOP(opt & 0x08) IF_NOT_DESKTOP(0))
#define OPT_QUIET (IF_DESKTOP(opt & 0x10) IF_NOT_DESKTOP(0))
#define BIT_TRAVERSE 0x20
#define OPT_TRAVERSE (IF_DESKTOP(opt & BIT_TRAVERSE) IF_NOT_DESKTOP(0))
#define BIT_TRAVERSE_TOP (0x20|0x40)
#define OPT_TRAVERSE_TOP (IF_DESKTOP(opt & BIT_TRAVERSE_TOP) IF_NOT_DESKTOP(0))
#define param (*(struct param_t*)state->userData)
#define opt option_mask32
Typedefs
typedef int(* chown_fptr) (const char *, uid_t, gid_t)
Functions
static int FAST_FUNC fileAction (struct recursive_state *state UNUSED_PARAM, const char *fileName, struct stat *statbuf)
int chown_main (int argc UNUSED_PARAM, char **argv)
Data Structure Documentation
param_t
struct param_t
Definition at line 99 of file chown.c.
Data Fields
chown_fptr chown_func
struct bb_uidgid_t ugid
Macro Definition Documentation
BIT_RECURSE
#define BIT_RECURSE 1
Definition at line 63 of file chown.c.
BIT_TRAVERSE
#define BIT_TRAVERSE 0x20
Definition at line 77 of file chown.c.
BIT_TRAVERSE_TOP
#define BIT_TRAVERSE_TOP (0x20|0x40)
Definition at line 80 of file chown.c.
opt
#define opt option_mask32
OPT_CHANGED
#define OPT_CHANGED (IF_DESKTOP(opt & 0x08) IF_NOT_DESKTOP(0))
Definition at line 67 of file chown.c.
OPT_NODEREF
#define OPT_NODEREF (opt & 2)
Definition at line 65 of file chown.c.
OPT_QUIET
#define OPT_QUIET (IF_DESKTOP(opt & 0x10) IF_NOT_DESKTOP(0))
Definition at line 68 of file chown.c.
OPT_RECURSE
#define OPT_RECURSE (opt & 1)
Definition at line 64 of file chown.c.
OPT_STR
#define OPT_STR "Rh" IF_DESKTOP("vcfLHP")
Definition at line 62 of file chown.c.
OPT_TRAVERSE
#define OPT_TRAVERSE (IF_DESKTOP(opt & BIT_TRAVERSE) IF_NOT_DESKTOP(0))
Definition at line 78 of file chown.c.
OPT_TRAVERSE_TOP
#define OPT_TRAVERSE_TOP (IF_DESKTOP(opt & BIT_TRAVERSE_TOP) IF_NOT_DESKTOP(0))
Definition at line 81 of file chown.c.
OPT_VERBOSE
#define OPT_VERBOSE (IF_DESKTOP(opt & 0x04) IF_NOT_DESKTOP(0))
Definition at line 66 of file chown.c.
param
#define param (*(struct param_t*)state->userData)
Typedef Documentation
chown_fptr
typedef int(* chown_fptr) (const char *, uid_t, gid_t)
Definition at line 97 of file chown.c.
Function Documentation
chown_main()
int chown_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 128 of file chown.c.
 {
     int retval = EXIT_SUCCESS;
     int opt, flags;
     struct param_t param;
 #if ENABLE_FEATURE_CHOWN_LONG_OPTIONS
     opt = getopt32long(argv, "^" OPT_STR "\0" "-2", chown_longopts);
 #else
     opt = getopt32(argv, "^" OPT_STR "\0" "-2");
 #endif
     argv += optind;
     /* This matches coreutils behavior (almost - see below) */
     param.chown_func = chown;
     if (OPT_NODEREF
     /* || (OPT_RECURSE && !OPT_TRAVERSE_TOP): */
     IF_DESKTOP( || (opt & (BIT_RECURSE|BIT_TRAVERSE_TOP)) == BIT_RECURSE)
     ) {
         param.chown_func = lchown;
     }
     flags = ACTION_DEPTHFIRST; /* match coreutils order */
     if (OPT_RECURSE)
         flags |= ACTION_RECURSE;
     if (OPT_TRAVERSE_TOP)
         flags |= ACTION_FOLLOWLINKS_L0; /* -H/-L: follow links on depth 0 */
     if (OPT_TRAVERSE)
         flags |= ACTION_FOLLOWLINKS; /* follow links if -L */
     parse_chown_usergroup_or_die(&param.ugid, argv[0]);
     /* Ok, ready to do the deed now */
     while (*++argv) {
         if (!recursive_action(*argv,
                 flags,          /* flags */
                 fileAction,     /* file action */
                 fileAction,     /* dir action */
                 &param)         /* user data */
         ) {
             retval = EXIT_FAILURE;
         }
     }
     return retval;
 }
Referenced by adduser_main(), and chgrp_main().
fileAction()
static int FAST_FUNC fileAction (struct recursive_state *state UNUSED_PARAM, const char * fileName, struct stat * statbuf) static
Definition at line 104 of file chown.c.
 {
 #define param  (*(struct param_t*)state->userData)
 #define opt option_mask32
     uid_t u = (param.ugid.uid == (uid_t)-1L) ? statbuf->st_uid : param.ugid.uid;
     gid_t g = (param.ugid.gid == (gid_t)-1L) ? statbuf->st_gid : param.ugid.gid;
     if (param.chown_func(fileName, u, g) == 0) {
         if (OPT_VERBOSE
          || (OPT_CHANGED && (statbuf->st_uid != u || statbuf->st_gid != g))
         ) {
             printf("changed ownership of '%s' to %u:%u\n",
                     fileName, (unsigned)u, (unsigned)g);
         }
         return TRUE;
     }
     if (!OPT_QUIET)
         bb_simple_perror_msg(fileName);
     return FALSE;
 #undef opt
 #undef param
 }
References bb_simple_perror_msg(), FALSE, fileName, g, OPT_CHANGED, OPT_QUIET, OPT_VERBOSE, param, printf(), stat::st_gid, stat::st_uid, and TRUE.