Fennix: Userspace/musl/src/string/strchr.c File Reference
strchr.c File Reference
#include <string.h>
Functions
char * strchr (const char *s, int c)
Function Documentation
strchr()
char* strchr (const char * s, int c)
Definition at line 3 of file strchr.c.
 {
     char *r = __strchrnul(s, c);
     return *(unsigned char *)r == (unsigned char)c ? r : 0;
 }
References __strchrnul(), c, and r.
Referenced by __execvpe(), __fdopen(), __fmodeflags(), __get_resolv_conf(), __getgrent_a(), __getpwent_a(), __lookup_ipliteral(), __lookup_serv(), __parsespent(), _nl_explode_name(), _nl_init_domain_conv(), _rl_find_completion_word(), _rl_isearch_dispatch(), a64l(), add_links(), argz_next__(), builtin_arrayref_flags(), cag_option_find_by_letter(), catopen(), ConvertFileFlags(), dcngettext(), decode_prompt_string(), dequote_escapes(), dequote_string(), do_glob(), do_tzset(), dsvsplit(), EscapeShellString(), execute_intern_function(), execvpe(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), fix_assignment_words(), fixup_rpath(), fmemopen(), fmtmsg(), fopen(), fopencookie(), mlibc::get_nameserver(), getmntent_r(), getopt(), getopt_long(), getprec(), getspnam_r(), getsubopt(), index(), internal_getopt(), load_library(), locale_charset(), mlibc::lookup_addr_hosts(), mlibc::lookup_name_hosts(), mlibc::lookup_serv_file_name(), mlibc::lookup_serv_file_port(), main(), make_here_document(), make_path(), make_quoted_replacement(), mbschr(), name_from_hosts(), parse_matched_pair(), mlibc::fd_file::parse_modestring(), ParseDMXConfig(), plural_lookup(), popen(), read_alias_file(), read_token_word(), realpath(), remove_quoted_nulls(), reverse_hosts(), reverse_services(), rl_alphabetic(), scan_request(), sh_getopt(), show_shell_usage(), sleep_builtin(), stat_char(), strcreplace(), strftime(), strsep(), strstr(), strtoxmax(), targp_parse(), tilde_expand(), validate_path(), vi_change_dispatch(), vi_delete_dispatch(), and vi_yank_dispatch().