Fennix: Userspace/musl/src/signal/block.c File Reference
block.c File Reference
#include "pthread_impl.h"
#include "syscall.h"
#include <signal.h>
Functions
void __block_all_sigs (void *set)
void __block_app_sigs (void *set)
void __restore_sigs (void *set)
Variables
static const unsigned long all_mask []
static const unsigned long app_mask []
Function Documentation
__block_all_sigs()
void __block_all_sigs (void * set)
Definition at line 31 of file block.c.
 {
     __syscall(SYS_rt_sigprocmask, SIG_BLOCK, &all_mask, set, _NSIG/8);
 }
References __syscall, _NSIG, all_mask, and SIG_BLOCK.
Referenced by __pthread_exit(), __sigaction(), __synccall(), _Fork(), abort(), do_setgroups(), do_setxid(), do_wordexp(), faccessat(), and pthread_kill().
__block_app_sigs()
void __block_app_sigs (void * set)
Definition at line 36 of file block.c.
 {
     __syscall(SYS_rt_sigprocmask, SIG_BLOCK, &app_mask, set, _NSIG/8);
 }
References __syscall, _NSIG, app_mask, and SIG_BLOCK.
Referenced by __membarrier(), __pthread_create(), __pthread_exit(), __pthread_key_delete(), __synccall(), fork(), install_new_tls(), pthread_getschedparam(), pthread_setschedparam(), pthread_setschedprio(), raise(), and sigqueue().
__restore_sigs()
void __restore_sigs (void * set)
Definition at line 41 of file block.c.
 {
     __syscall(SYS_rt_sigprocmask, SIG_SETMASK, set, 0, _NSIG/8);
 }
References __syscall, _NSIG, and SIG_SETMASK.
Referenced by __membarrier(), __pthread_create(), __pthread_exit(), __pthread_key_delete(), __sigaction(), __synccall(), _Fork(), do_wordexp(), faccessat(), fork(), install_new_tls(), pthread_getschedparam(), pthread_kill(), pthread_setschedparam(), pthread_setschedprio(), raise(), and sigqueue().
Variable Documentation
all_mask
const unsigned long all_mask[] static
Initial value:
= {
    -1UL
}
Definition at line 5 of file block.c.
Referenced by __block_all_sigs().
app_mask
const unsigned long app_mask[] static
Initial value:
= {
    0xfffffffc7fffffff, -1UL
}
Definition at line 15 of file block.c.
Referenced by __block_app_sigs().