Fennix Kernel: CrashKeyboardDriver Class Reference
CrashKeyboardDriver Class Reference
#include <keyboard.hpp>
Public Member Functions
CrashKeyboardDriver ()
~CrashKeyboardDriver ()
Private Member Functions
void PS2Wait (bool Read)
void OnInterruptReceived (CPU::TrapFrame *Frame)
Private Attributes
int BackSpaceLimit = 0
char UserInputBuffer [256]
int TimeoutCallNumber = 0
Additional Inherited Members
Protected Member Functions inherited from Interrupts::Handler
void SetInterruptNumber (int InterruptNumber)
Set a new interrupt number.
int GetInterruptNumber ()
Handler (int InterruptNumber, bool Critical=false)
Create a new interrupt handler.
Handler (PCI::PCIDevice Device, bool Critical=false)
Handler ()
~Handler ()
Detailed Description
Definition at line 206 of file keyboard.hpp.
Constructor & Destructor Documentation
CrashKeyboardDriver()
CrashKeyboardDriver::CrashKeyboardDriver ()
Definition at line 141 of file keyboard.cpp.
                                          : Interrupts::Handler(1) /* IRQ1 */
 {
 #define WaitRead PS2Wait(true)
 #define WaitWrite PS2Wait(false)
 #define SetMessageLocation                        \
     Display->SetBufferCursor(8,                   \
                              Display->GetHeight - \
                                  Display->GetCurrentFont()->GetInfo().Height - 24)
     CPU::Interrupts(CPU::Disable);
     /* Dots will be printed at the bottom of the screen as a progress bar. */
     Display->SetBufferCursor(8,
                              Display->GetHeight -
                                  Display->GetCurrentFont()->GetInfo().Height - 8);
 #if defined(a86)
     /* Disable port 1 & 2 */
     {
         /* Disable Port 1 */
         WaitWrite;
         outb(0x64, 0xAD);
         /* Disable Port 2 */
         WaitWrite;
         outb(0x64, 0xA7);
     }
     Display->Print('.');
     /* Flush */
     {
         int Timeout = 100000;
         while ((inb(0x64) & 1) && Timeout-- > 0)
             inb(0x60);
         if (Timeout <= 0)
         {
             SetMessageLocation;
             ExPrint(ERROR_COLOR
                     "PS/2 controller timeout (flush;0)\n" DEFAULT_COLOR);
             CPU::Stop();
         }
     }
     Display->Print('.');
     /* Test controller */
     {
         /* Save config */
         WaitWrite;
         outb(0x64, 0x20);
         WaitRead;
         uint8_t cfg = inb(0x60);
         /* Test PS/2 controller */
         WaitWrite;
         outb(0x64, 0xAA);
         WaitRead;
         uint8_t test = inb(0x60);
         if (test != 0x55)
         {
             if (test == 0xFA)
             {
                 trace("PS/2 controller sent ACK to test request.");
                 WaitRead;
                 test = inb(0x60);
             }
             if (test != 0x55)
             {
                 SetMessageLocation;
                 ExPrint(ERROR_COLOR
                         "PS/2 controller self test failed (%#x)\n" DEFAULT_COLOR,
                         test);
                 CPU::Stop();
             }
         }
         /* Restore config */
         WaitWrite;
         outb(0x64, 0x60);
         WaitWrite;
         outb(0x60, cfg);
     }
     Display->Print('.');
     /* Disable scanning; Enable port 1; Set default settings */
     {
         /* Disable scanning */
         outb(0x60, 0xF5);
         /* Enable Port 1 */
         WaitWrite;
         outb(0x64, 0xAE);
         /* Set default settings */
         outb(0x60, 0xF6);
     }
     Display->Print('.');
     /* Test port 1 */
     {
         WaitWrite;
         outb(0x64, 0xAB);
         WaitRead;
         uint8_t test = inb(0x60);
         if (test != 0x00)
         {
             if (test == 0xFA)
             {
                 trace("PS/2 keyboard sent ACK to test request.");
                 WaitRead;
                 test = inb(0x60);
             }
             if (test != 0x00)
             {
                 SetMessageLocation;
                 ExPrint(ERROR_COLOR
                         "PS/2 keyboard self test failed (%#x)\n" DEFAULT_COLOR,
                         test);
                 CPU::Stop();
             }
         }
     }
     Display->Print('.');
     /* Configure the controller */
     {
         /* Read Controller Configuration */
         WaitWrite;
         outb(0x64, 0x20);
         WaitRead;
         uint8_t cfg = inb(0x60);
         /* Enable Port 1 & Port 1 translation */
         cfg |= 0b01000001;
         /* Write Controller Configuration */
         WaitWrite;
         outb(0x64, 0x60);
         WaitWrite;
         outb(0x60, cfg);
     }
     Display->Print('.');
     /* Enable port 1; Set scan code; Enable scanning */
     {
         /* Enable Port 1 */
         outb(0x64, 0xAE);
         /* Set scan code set 1 */
         WaitWrite;
         outb(0x60, 0xF0);
         WaitWrite;
         outb(0x60, 0x02);
         /* Check if we have scan code set 1 */
         WaitWrite;
         outb(0x60, 0xF0);
         WaitWrite;
         outb(0x60, 0x00);
         /* Read scan code set */
         WaitRead;
         uint8_t scs = inb(0x60);
         if (scs == 0xFA || scs == 0xFE)
         {
             if (scs == 0xFA)
                 trace("PS/2 keyboard sent ACK to scan code set request.");
             if (scs == 0xFE)
                 trace("PS/2 keyboard sent RESEND to scan code set request.");
             WaitRead;
             scs = inb(0x60);
         }
         if (scs != 0x41)
         {
             SetMessageLocation;
             ExPrint(WARN_COLOR
                     "PS/2 keyboard scan code set 1 not supported (%#x)\n" DEFAULT_COLOR,
                     scs);
         }
         /* Enable scanning */
         outb(0x60, 0xF4);
     }
     Display->Print('.');
 #endif // defined(a86)
     CPU::Interrupts(CPU::Enable);
 }
References DEFAULT_COLOR, CPU::Disable, Display, CPU::Enable, ERROR_COLOR, ExPrint(), Video::Display::GetCurrentFont(), Video::Display::GetHeight, Video::Font::GetInfo(), Video::FontInfo::Height, CPU::Interrupts(), Video::Display::Print(), Video::Display::SetBufferCursor(), SetMessageLocation, CPU::Stop(), trace, WaitRead, WaitWrite, and WARN_COLOR.
~CrashKeyboardDriver()
CrashKeyboardDriver::~CrashKeyboardDriver () inline
Definition at line 218 of file keyboard.hpp.
 {}
Member Function Documentation
OnInterruptReceived()
nsa void CrashKeyboardDriver::OnInterruptReceived (CPU::TrapFrame * Frame) private virtual
Reimplemented from Interrupts::Handler.
Definition at line 337 of file keyboard.cpp.
 {
 #if defined(a86)
     UNUSED(Frame);
     uint8_t scanCode = inb(0x60);
     if (scanCode == KEY_D_TAB ||
         scanCode == KEY_D_LCTRL ||
         scanCode == KEY_D_LALT ||
         scanCode == KEY_U_LCTRL ||
         scanCode == KEY_U_LALT)
         return;
     switch (scanCode)
     {
     case KEY_D_UP:
     case KEY_D_LEFT:
     case KEY_D_RIGHT:
     case KEY_D_DOWN:
         ArrowInput(scanCode);
         break;
     default:
         break;
     }
     int key = GetLetterFromScanCode(scanCode);
     if (key != KEY_INVALID)
     {
         if (key == KEY_D_BACKSPACE)
         {
             if (BackSpaceLimit > 0)
             {
                 Display->Print('\b');
                 backspace(UserInputBuffer);
                 BackSpaceLimit--;
             }
         }
         else if (key == '\n')
         {
             UserInput(UserInputBuffer);
             BackSpaceLimit = 0;
             UserInputBuffer[0] = '\0';
         }
         else
         {
             append(UserInputBuffer, s_cst(char, key));
             Display->Print((char)key);
             BackSpaceLimit++;
         }
         Display->UpdateBuffer(); /* Update as we type. */
     }
 #endif // a64 || a32
 }
References append(), ArrowInput(), backspace(), BackSpaceLimit, Display, GetLetterFromScanCode(), KEY_D_BACKSPACE, KEY_D_DOWN, KEY_D_LALT, KEY_D_LCTRL, KEY_D_LEFT, KEY_D_RIGHT, KEY_D_TAB, KEY_D_UP, KEY_INVALID, KEY_U_LALT, KEY_U_LCTRL, Video::Display::Print(), UNUSED, Video::Display::UpdateBuffer(), UserInput(), and UserInputBuffer.
PS2Wait()
nsa void CrashKeyboardDriver::PS2Wait (bool Read) private
Definition at line 102 of file keyboard.cpp.
 {
     TimeoutCallNumber++;
 #if defined(a86)
     int Timeout = 100000;
     uint8_t Status = 0;
     while (Timeout--)
     {
         Status = inb(0x64);
         if (Read)
         {
             if ((Status & 1) == 1)
                 return;
         }
         else
         {
             if ((Status & 2) == 0)
                 return;
         }
     }
     ExPrint(WARN_COLOR "PS/2 controller timeout (%s;%d)\n" DEFAULT_COLOR,
             Read ? "read" : "write", TimeoutCallNumber - 1);
 #endif // a86
 }
References DEFAULT_COLOR, ExPrint(), TimeoutCallNumber, and WARN_COLOR.
Field Documentation
BackSpaceLimit
int CrashKeyboardDriver::BackSpaceLimit = 0 private
Definition at line 212 of file keyboard.hpp.
Referenced by OnInterruptReceived().
TimeoutCallNumber
int CrashKeyboardDriver::TimeoutCallNumber = 0 private
Definition at line 214 of file keyboard.hpp.
Referenced by PS2Wait().
UserInputBuffer
char CrashKeyboardDriver::UserInputBuffer[256] private
Definition at line 213 of file keyboard.hpp.
Referenced by OnInterruptReceived().
The documentation for this class was generated from the following files:
Kernel/core/panic/keyboard.hpp
Kernel/core/panic/keyboard.cpp