Fennix Userspace: Userspace/apps/base/bash/lib/glob/strmatch.c File Reference
strmatch.c File Reference
#include <config.h>
#include "stdc.h"
#include "strmatch.h"
Functions
int xstrmatch PARAMS ((char *, char *, int))
int strmatch (char *pattern, char *string, int flags)
Function Documentation
PARAMS()
int xstrmatch PARAMS ((char *, char *, int))
strmatch()
int strmatch (char * pattern, char * string, int flags)
Definition at line 33 of file strmatch.c.
 {
   if (string == 0 || pattern == 0)
     return FNM_NOMATCH;
   return (xstrmatch (pattern, string, flags));
 }
References flags, FNM_NOMATCH, pattern, and xstrmatch().
Referenced by exec_name_should_ignore(), execute_case_command(), find_index_in_alist(), find_string_in_alist(), glob_name_is_acceptable(), glob_vector(), match_upattern(), patcomp(), remove_upattern(), and sh_modcase().