Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/sha1.c File Reference
sha1.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "i_swap.h"
#include "sha1.h"
Macros
#define K1 0x5A827999L
#define K2 0x6ED9EBA1L
#define K3 0x8F1BBCDCL
#define K4 0xCA62C1D6L
#define F1(x, y, z) (z ^ (x & (y ^ z)))
#define F2(x, y, z) (x ^ y ^ z)
#define F3(x, y, z) ((x & y) | (z & (x | y)))
#define F4(x, y, z) (x ^ y ^ z)
#define rol(x, n) (((x) << (n)) | ((x) >> (32-(n))))
#define M(i)
#define R(a, b, c, d, e, f, k, m)
#define X(a)
Functions
void SHA1_Init (sha1_context_t *hd)
static void Transform (sha1_context_t *hd, byte *data)
void SHA1_Update (sha1_context_t *hd, byte *inbuf, size_t inlen)
void SHA1_Final (sha1_digest_t digest, sha1_context_t *hd)
void SHA1_UpdateInt32 (sha1_context_t *context, unsigned int val)
void SHA1_UpdateString (sha1_context_t *context, char *str)
Macro Definition Documentation
F1
#define F1 (x, y, z) (z ^ (x & (y ^ z)))
F2
#define F2 (x, y, z) (x ^ y ^ z)
F3
#define F3 (x, y, z) ((x & y) | (z & (x | y)))
F4
#define F4 (x, y, z) (x ^ y ^ z)
K1
#define K1 0x5A827999L
K2
#define K2 0x6ED9EBA1L
K3
#define K3 0x8F1BBCDCL
K4
#define K4 0xCA62C1D6L
M
#define M (i)
Value:
            ( tm =   x[i&0x0f] ^ x[(i-14)&0x0f] \
            ^ x[(i-8)&0x0f] ^ x[(i-3)&0x0f] \
           , (x[i&0x0f] = rol(tm,1)) )
R
#define R (a, b, c, d, e, f, k, m)
Value:
                      do { e += rol( a, 5 )     \
                      + f( b, c, d )  \
                      + k         \
                      + m;        \
                 b = rol( b, 30 );    \
                   } while(0)
rol
#define rol (x, n) (((x) << (n)) | ((x) >> (32-(n))))
X
#define X (a)
Value:
              do { *p++ = hd->h##a >> 24; *p++ = hd->h##a >> 16;     \
              *p++ = hd->h##a >> 8; *p++ = hd->h##a; } while(0)
Function Documentation
SHA1_Final()
void SHA1_Final (sha1_digest_t digest, sha1_context_t * hd)
Definition at line 238 of file sha1.c.
 {
     uint32_t t, msb, lsb;
     byte *p;
     SHA1_Update(hd, NULL, 0); /* flush */;
     t = hd->nblocks;
     /* multiply by 64 to make a byte count */
     lsb = t << 6;
     msb = t >> 26;
     /* add the count */
     t = lsb;
     if ((lsb += hd->count) < t)
     msb++;
     /* multiply by 8 to make a bit count */
     t = lsb;
     lsb <<= 3;
     msb <<= 3;
     msb |= t >> 29;
     if (hd->count < 56)
     {
         /* enough room */
     hd->buf[hd->count++] = 0x80; /* pad */
     while (hd->count < 56)
         hd->buf[hd->count++] = 0;  /* pad */
     }
     else
     {
         /* need one extra block */
     hd->buf[hd->count++] = 0x80; /* pad character */
     while (hd->count < 64)
         hd->buf[hd->count++] = 0;
     SHA1_Update(hd, NULL, 0);  /* flush */;
     memset(hd->buf, 0, 56 ); /* fill next block with zeroes */
     }
     /* append the 64 bit count */
     hd->buf[56] = msb >> 24;
     hd->buf[57] = msb >> 16;
     hd->buf[58] = msb >>  8;
     hd->buf[59] = msb      ;
     hd->buf[60] = lsb >> 24;
     hd->buf[61] = lsb >> 16;
     hd->buf[62] = lsb >>  8;
     hd->buf[63] = lsb      ;
     Transform(hd, hd->buf);
     p = hd->buf;
 #ifdef SYS_BIG_ENDIAN
 #define X(a) do { *(uint32_t*)p = hd->h##a ; p += 4; } while(0)
 #else /* little endian */
 #define X(a) do { *p++ = hd->h##a >> 24; *p++ = hd->h##a >> 16;  \
               *p++ = hd->h##a >> 8; *p++ = hd->h##a; } while(0)
 #endif
     X(0);
     X(1);
     X(2);
     X(3);
     X(4);
 #undef X
     memcpy(digest, hd->buf, sizeof(sha1_digest_t));
 }
References sha1_context_s::buf, sha1_context_s::count, memcpy(), memset(), sha1_context_s::nblocks, NULL, p, SHA1_Update(), t, Transform(), and X.
Referenced by W_Checksum().
SHA1_Init()
void SHA1_Init (sha1_context_t * hd)
Definition at line 40 of file sha1.c.
 {
     hd->h0 = 0x67452301;
     hd->h1 = 0xefcdab89;
     hd->h2 = 0x98badcfe;
     hd->h3 = 0x10325476;
     hd->h4 = 0xc3d2e1f0;
     hd->nblocks = 0;
     hd->count = 0;
 }
References sha1_context_s::count, sha1_context_s::h0, sha1_context_s::h1, sha1_context_s::h2, sha1_context_s::h3, sha1_context_s::h4, and sha1_context_s::nblocks.
Referenced by W_Checksum().
SHA1_Update()
void SHA1_Update (sha1_context_t * hd, byte * inbuf, size_t inlen)
Definition at line 198 of file sha1.c.
 {
     if (hd->count == 64)
     {
         /* flush the buffer */
     Transform(hd, hd->buf);
     hd->count = 0;
     hd->nblocks++;
     }
     if (!inbuf)
     return;
     if (hd->count)
     {
     for (; inlen && hd->count < 64; inlen--)
         hd->buf[hd->count++] = *inbuf++;
     SHA1_Update(hd, NULL, 0);
     if (!inlen)
         return;
     }
     while (inlen >= 64)
     {
     Transform(hd, inbuf);
     hd->count = 0;
     hd->nblocks++;
     inlen -= 64;
     inbuf += 64;
     }
     for (; inlen && hd->count < 64; inlen--)
     hd->buf[hd->count++] = *inbuf++;
 }
References sha1_context_s::buf, sha1_context_s::count, sha1_context_s::nblocks, NULL, and Transform().
Referenced by SHA1_Final(), SHA1_UpdateInt32(), and SHA1_UpdateString().
SHA1_UpdateInt32()
void SHA1_UpdateInt32 (sha1_context_t * context, unsigned int val)
Definition at line 303 of file sha1.c.
 {
     byte buf[4];
     buf[0] = (val >> 24) & 0xff;
     buf[1] = (val >> 16) & 0xff;
     buf[2] = (val >> 8) & 0xff;
     buf[3] = val & 0xff;
     SHA1_Update(context, buf, 4);
 }
References buf, context, SHA1_Update(), and val.
Referenced by ChecksumAddLump().
SHA1_UpdateString()
void SHA1_UpdateString (sha1_context_t * context, char * str)
Definition at line 315 of file sha1.c.
 {
     SHA1_Update(context, (byte *) str, strlen(str) + 1);
 }
References context, SHA1_Update(), str, and strlen().
Referenced by ChecksumAddLump().
Transform()
static void Transform (sha1_context_t * hd, byte * data) static
Definition at line 55 of file sha1.c.
 {
     uint32_t a,b,c,d,e,tm;
     uint32_t x[16];
     /* get values from the chaining vars */
     a = hd->h0;
     b = hd->h1;
     c = hd->h2;
     d = hd->h3;
     e = hd->h4;
 #ifdef SYS_BIG_ENDIAN
     memcpy(x, data, 64);
 #else
     {
         int i;
         byte *p2;
         for(i=0, p2=(byte*)x; i < 16; i++, p2 += 4 )
         {
             p2[3] = *data++;
             p2[2] = *data++;
             p2[1] = *data++;
             p2[0] = *data++;
         }
     }
 #endif
 #define K1  0x5A827999L
 #define K2  0x6ED9EBA1L
 #define K3  0x8F1BBCDCL
 #define K4  0xCA62C1D6L
 #define F1(x,y,z)   ( z ^ ( x & ( y ^ z ) ) )
 #define F2(x,y,z)   ( x ^ y ^ z )
 #define F3(x,y,z)   ( ( x & y ) | ( z & ( x | y ) ) )
 #define F4(x,y,z)   ( x ^ y ^ z )
 #define rol(x,n) ( ((x) << (n)) | ((x) >> (32-(n))) )
 #define M(i) ( tm =   x[i&0x0f] ^ x[(i-14)&0x0f] \
             ^ x[(i-8)&0x0f] ^ x[(i-3)&0x0f] \
            , (x[i&0x0f] = rol(tm,1)) )
 #define R(a,b,c,d,e,f,k,m)  do { e += rol( a, 5 )     \
                       + f( b, c, d )  \
                       + k         \
                       + m;        \
                  b = rol( b, 30 );    \
                    } while(0)
     R( a, b, c, d, e, F1, K1, x[ 0] );
     R( e, a, b, c, d, F1, K1, x[ 1] );
     R( d, e, a, b, c, F1, K1, x[ 2] );
     R( c, d, e, a, b, F1, K1, x[ 3] );
     R( b, c, d, e, a, F1, K1, x[ 4] );
     R( a, b, c, d, e, F1, K1, x[ 5] );
     R( e, a, b, c, d, F1, K1, x[ 6] );
     R( d, e, a, b, c, F1, K1, x[ 7] );
     R( c, d, e, a, b, F1, K1, x[ 8] );
     R( b, c, d, e, a, F1, K1, x[ 9] );
     R( a, b, c, d, e, F1, K1, x[10] );
     R( e, a, b, c, d, F1, K1, x[11] );
     R( d, e, a, b, c, F1, K1, x[12] );
     R( c, d, e, a, b, F1, K1, x[13] );
     R( b, c, d, e, a, F1, K1, x[14] );
     R( a, b, c, d, e, F1, K1, x[15] );
     R( e, a, b, c, d, F1, K1, M(16) );
     R( d, e, a, b, c, F1, K1, M(17) );
     R( c, d, e, a, b, F1, K1, M(18) );
     R( b, c, d, e, a, F1, K1, M(19) );
     R( a, b, c, d, e, F2, K2, M(20) );
     R( e, a, b, c, d, F2, K2, M(21) );
     R( d, e, a, b, c, F2, K2, M(22) );
     R( c, d, e, a, b, F2, K2, M(23) );
     R( b, c, d, e, a, F2, K2, M(24) );
     R( a, b, c, d, e, F2, K2, M(25) );
     R( e, a, b, c, d, F2, K2, M(26) );
     R( d, e, a, b, c, F2, K2, M(27) );
     R( c, d, e, a, b, F2, K2, M(28) );
     R( b, c, d, e, a, F2, K2, M(29) );
     R( a, b, c, d, e, F2, K2, M(30) );
     R( e, a, b, c, d, F2, K2, M(31) );
     R( d, e, a, b, c, F2, K2, M(32) );
     R( c, d, e, a, b, F2, K2, M(33) );
     R( b, c, d, e, a, F2, K2, M(34) );
     R( a, b, c, d, e, F2, K2, M(35) );
     R( e, a, b, c, d, F2, K2, M(36) );
     R( d, e, a, b, c, F2, K2, M(37) );
     R( c, d, e, a, b, F2, K2, M(38) );
     R( b, c, d, e, a, F2, K2, M(39) );
     R( a, b, c, d, e, F3, K3, M(40) );
     R( e, a, b, c, d, F3, K3, M(41) );
     R( d, e, a, b, c, F3, K3, M(42) );
     R( c, d, e, a, b, F3, K3, M(43) );
     R( b, c, d, e, a, F3, K3, M(44) );
     R( a, b, c, d, e, F3, K3, M(45) );
     R( e, a, b, c, d, F3, K3, M(46) );
     R( d, e, a, b, c, F3, K3, M(47) );
     R( c, d, e, a, b, F3, K3, M(48) );
     R( b, c, d, e, a, F3, K3, M(49) );
     R( a, b, c, d, e, F3, K3, M(50) );
     R( e, a, b, c, d, F3, K3, M(51) );
     R( d, e, a, b, c, F3, K3, M(52) );
     R( c, d, e, a, b, F3, K3, M(53) );
     R( b, c, d, e, a, F3, K3, M(54) );
     R( a, b, c, d, e, F3, K3, M(55) );
     R( e, a, b, c, d, F3, K3, M(56) );
     R( d, e, a, b, c, F3, K3, M(57) );
     R( c, d, e, a, b, F3, K3, M(58) );
     R( b, c, d, e, a, F3, K3, M(59) );
     R( a, b, c, d, e, F4, K4, M(60) );
     R( e, a, b, c, d, F4, K4, M(61) );
     R( d, e, a, b, c, F4, K4, M(62) );
     R( c, d, e, a, b, F4, K4, M(63) );
     R( b, c, d, e, a, F4, K4, M(64) );
     R( a, b, c, d, e, F4, K4, M(65) );
     R( e, a, b, c, d, F4, K4, M(66) );
     R( d, e, a, b, c, F4, K4, M(67) );
     R( c, d, e, a, b, F4, K4, M(68) );
     R( b, c, d, e, a, F4, K4, M(69) );
     R( a, b, c, d, e, F4, K4, M(70) );
     R( e, a, b, c, d, F4, K4, M(71) );
     R( d, e, a, b, c, F4, K4, M(72) );
     R( c, d, e, a, b, F4, K4, M(73) );
     R( b, c, d, e, a, F4, K4, M(74) );
     R( a, b, c, d, e, F4, K4, M(75) );
     R( e, a, b, c, d, F4, K4, M(76) );
     R( d, e, a, b, c, F4, K4, M(77) );
     R( c, d, e, a, b, F4, K4, M(78) );
     R( b, c, d, e, a, F4, K4, M(79) );
     /* update chainig vars */
     hd->h0 += a;
     hd->h1 += b;
     hd->h2 += c;
     hd->h3 += d;
     hd->h4 += e;
 }
References b, c, F1, F2, F3, F4, sha1_context_s::h0, sha1_context_s::h1, sha1_context_s::h2, sha1_context_s::h3, sha1_context_s::h4, i, K1, K2, K3, K4, M, memcpy(), R, and x.
Referenced by SHA1_Final(), and SHA1_Update().