Fennix: Kernel/core/panic/keyboard.cpp File Reference
keyboard.cpp File Reference
#include "keyboard.hpp"
#include <display.hpp>
#include <convert.h>
#include <printf.h>
#include <debug.h>
#include <smp.hpp>
#include <cpu.hpp>
#include <io.h>
#include "../../kernel.h"
Macros
#define ERROR_COLOR "\eFF0000"
#define WARN_COLOR "\eFFAA00"
#define DEFAULT_COLOR "\e00FF00"
#define WaitRead PS2Wait(true)
#define WaitWrite PS2Wait(false)
#define SetMessageLocation
Functions
void ExPrint (const char *Format,...)
void ArrowInput (uint8_t key)
void UserInput (char *Input)
static nsa int GetLetterFromScanCode (uint8_t ScanCode)
Variables
const char sc_ascii_low []
const char sc_ascii_high []
static int LowerCase = true
Macro Definition Documentation
DEFAULT_COLOR
#define DEFAULT_COLOR "\e00FF00"
Definition at line 38 of file keyboard.cpp.
ERROR_COLOR
#define ERROR_COLOR "\eFF0000"
Definition at line 36 of file keyboard.cpp.
SetMessageLocation
#define SetMessageLocation
Value:
    Display->SetBufferCursor(8,                   \
                             Display->GetHeight - \
                                 Display->GetCurrentFont()->GetInfo().Height - 24)
WaitRead
#define WaitRead PS2Wait(true)
WaitWrite
#define WaitWrite PS2Wait(false)
WARN_COLOR
#define WARN_COLOR "\eFFAA00"
Definition at line 37 of file keyboard.cpp.
Function Documentation
ArrowInput()
void ArrowInput (uint8_t key)
Definition at line 711 of file ui.cpp.
 {
     switch (key)
     {
     case KEY_D_RIGHT:
         if (ActiveScreen < 3)
             ActiveScreen++;
         else
             return;
         break;
     case KEY_D_LEFT:
         if (ActiveScreen > 0)
             ActiveScreen--;
         else
             return;
         break;
     case KEY_D_DOWN:
     case KEY_D_UP:
     default:
         return;
     }
     Display->ClearBuffer();
     DisplayTopOverlay();
     switch (ActiveScreen)
     {
     case 0:
         DisplayMainScreen(ExFrame);
         break;
     case 1:
         DisplayDetailsScreen(ExFrame);
         break;
     case 2:
         DisplayStackScreen(ExFrame);
         break;
     case 3:
         DisplayProcessScreen(ExFrame);
         break;
     default:
         break;
     }
     DisplayBottomOverlay();
     Display->UpdateBuffer();
 }
References ActiveScreen, Video::Display::ClearBuffer(), Display, DisplayBottomOverlay(), DisplayDetailsScreen(), DisplayMainScreen(), DisplayProcessScreen(), DisplayStackScreen(), DisplayTopOverlay(), ExFrame, KEY_D_DOWN, KEY_D_LEFT, KEY_D_RIGHT, KEY_D_UP, and Video::Display::UpdateBuffer().
Referenced by CrashKeyboardDriver::OnInterruptReceived().
ExPrint()
void ExPrint (const char * Format, ...)
Definition at line 54 of file handler.cpp.
 {
     va_list args;
     va_start(args, Format);
     vfctprintf(__printfWrapper, NULL, Format, args);
     va_end(args);
 }
Referenced by CrashKeyboardDriver::CrashKeyboardDriver(), and CrashKeyboardDriver::PS2Wait().
GetLetterFromScanCode()
static nsa int GetLetterFromScanCode (uint8_t ScanCode) inline static
Definition at line 58 of file keyboard.cpp.
 {
     if (ScanCode & 0x80)
     {
         switch (ScanCode)
         {
         case KEY_U_LSHIFT:
             LowerCase = true;
             return KEY_INVALID;
         case KEY_U_RSHIFT:
             LowerCase = true;
             return KEY_INVALID;
         default:
             return KEY_INVALID;
         }
     }
     else
     {
         switch (ScanCode)
         {
         case KEY_D_RETURN:
             return '\n';
         case KEY_D_LSHIFT:
             LowerCase = false;
             return KEY_INVALID;
         case KEY_D_RSHIFT:
             LowerCase = false;
             return KEY_INVALID;
         case KEY_D_BACKSPACE:
             return ScanCode;
         default:
         {
             if (ScanCode > 0x39)
                 break;
             if (LowerCase)
                 return sc_ascii_low[ScanCode];
             else
                 return sc_ascii_high[ScanCode];
         }
         }
     }
     return KEY_INVALID;
 }
References KEY_D_BACKSPACE, KEY_D_LSHIFT, KEY_D_RETURN, KEY_D_RSHIFT, KEY_INVALID, KEY_U_LSHIFT, KEY_U_RSHIFT, LowerCase, sc_ascii_high, and sc_ascii_low.
Referenced by CrashKeyboardDriver::OnInterruptReceived().
UserInput()
void UserInput (char * Input)
Definition at line 758 of file ui.cpp.
 {
     debug("User input: %s", Input);
     Display->ClearBuffer();
     DisplayTopOverlay();
     if (strcmp(Input, "help") == 0)
     {
         ExPrint("Commands:\n");
         ExPrint("\eAAAAAA  help              - Display this help message.\n");
         ExPrint("\eCACACA  clear             - Clear the screen.\n");
         ExPrint("\eAAAAAA  exit              - Shutdown the device.\n");
         ExPrint("\eCACACA  reboot            - Reboot the device.\n");
         ExPrint("\eAAAAAA  bitmap            - Display the kernel's bitmap.\n");
         ExPrint("\eCACACA  mem               - Display memory information.\n");
         ExPrint("\eAAAAAA  dump [addr] [len] - Dump [len] bytes from [addr].\n");
         ExPrint("\eCACACA  diag              - Collect diagnostic information.\n");
     }
     else if (strcmp(Input, "clear") == 0)
     {
         Display->ClearBuffer();
         DisplayTopOverlay();
     }
     else if (strcmp(Input, "exit") == 0)
     {
         Display->ClearBuffer();
         const char msg[] = "Shutting down...";
         size_t msgLen = strlen(msg);
         size_t msgPixels = msgLen * CrashFont->GetInfo().Width;
         uint32_t x = uint32_t((Display->GetWidth - msgPixels) / 2);
         uint32_t y = uint32_t((Display->GetHeight - CrashFont->GetInfo().Height) / 2);
         Display->SetBufferCursor(x, y);
         Display->PrintString("\eAAAAAA");
         Display->PrintString(msg, CrashFont);
         Display->UpdateBuffer();
         PowerManager->Shutdown();
         CPU::Stop();
     }
     else if (strcmp(Input, "reboot") == 0)
     {
         Display->ClearBuffer();
         const char msg[] = "Rebooting...";
         size_t msgLen = strlen(msg);
         size_t msgPixels = msgLen * CrashFont->GetInfo().Width;
         uint32_t x = uint32_t((Display->GetWidth - msgPixels) / 2);
         uint32_t y = uint32_t((Display->GetHeight - CrashFont->GetInfo().Height) / 2);
         Display->SetBufferCursor(x, y);
         Display->PrintString("\eAAAAAA");
         Display->PrintString(msg, CrashFont);
         Display->UpdateBuffer();
         PowerManager->Reboot();
         CPU::Stop();
     }
     else if (strncmp(Input, "bitmap", 6) == 0)
     {
         Bitmap bm = KernelAllocator.GetPageBitmap();
         Video::Font *oldFont = CrashFont;
         CrashFont = Display->GetDefaultFont();
         ExPrint("\n\eAAAAAA[0%%] %08ld: ", 0);
         for (size_t i = 0; i < bm.Size; i++)
         {
             if (bm.Get(i))
                 Display->PrintString("\eFF0000");
             else
                 Display->PrintString("\e00FF00");
             Display->Print('0');
             if (i % 128 == 127)
             {
                 short Percentage = s_cst(short, (i * 100) / bm.Size);
                 ExPrint("\n\eAAAAAA[%03ld%%] %08ld: ", Percentage, i);
                 Display->UpdateBuffer();
             }
         }
         ExPrint("\n\eAAAAAA--- END OF BITMAP ---\nBitmap size: %ld\n\n.", bm.Size);
         DisplayTopOverlay();
         Display->UpdateBuffer();
         CrashFont = oldFont;
     }
     else if (strcmp(Input, "mem") == 0)
     {
         uint64_t Total = KernelAllocator.GetTotalMemory();
         uint64_t Used = KernelAllocator.GetUsedMemory();
         uint64_t Free = KernelAllocator.GetFreeMemory();
         uint64_t Reserved = KernelAllocator.GetReservedMemory();
         ExPrint("\e22AA44Total: %ld bytes\n\eFF0000Used: %ld bytes\n\e00FF00Free: %ld bytes\n\eFF00FFReserved: %ld bytes\n", Total, Used, Free, Reserved);
         int Progress = s_cst(int, (Used * 100) / Total);
         int ReservedProgress = s_cst(int, (Reserved * 100) / Total);
         ExPrint("\e22AA44%3d%% \eCCCCCC[", Progress);
         for (int i = 0; i < Progress; i++)
             ExPrint("\eFF0000|");
         for (int i = 0; i < 100 - Progress; i++)
             ExPrint("\e00FF00|");
         for (int i = 0; i < ReservedProgress; i++)
             ExPrint("\eFF00FF|");
         ExPrint("\eCCCCCC]\eAAAAAA\n");
     }
     else if (strncmp(Input, "dump", 4) == 0)
     {
         char *arg = TrimWhiteSpace(Input + 4);
         char *addr = strtok(arg, " ");
         char *len = strtok(NULL, " ");
         if (addr == NULL || len == NULL)
         {
             ExPrint("\eFF0000Invalid arguments\n");
             goto End;
         }
         uintptr_t Address = strtoul(addr, NULL, 16);
         size_t Length = strtoul(len, NULL, 10);
         uintptr_t AlignedAddress = ROUND_DOWN(Address, PAGE_SIZE);
         bool IsRangeValid = true;
         {
             Memory::Virtual vmm;
             for (uintptr_t adr = AlignedAddress;
                  adr < Address + Length;
                  adr += PAGE_SIZE)
             {
                 if (!vmm.Check((void *)adr))
                 {
                     ExPrint("\eFFA500Address %#lx is not mapped\n", adr);
                     IsRangeValid = false;
                 }
             }
         }
         if (IsRangeValid)
         {
             debug("Dumping %ld bytes from %#lx\n", Length, Address);
             Video::Font *oldFont = CrashFont;
             CrashFont = Display->GetDefaultFont();
             ExDumpData((void *)Address, (unsigned long)Length);
             CrashFont = oldFont;
         }
     }
     else if (strcmp(Input, "diag") == 0)
     {
         DiagnosticDataCollection();
     }
 #ifdef DEBUG
     else if (strcmp(Input, "pt") == 0)
     {
         /* Helpful for qemu "info tlb" command */
         CPU::PageTable((void *)ExFrame->cr3);
         ExPrint("Here be dragons\n");
     }
 #endif // DEBUG
     else if (strlen(Input) > 0)
         ExPrint("Unknown command: %s", Input);
     else
         ExPrint("Use the 'help' command to display a list of available commands.");
 End:
     DisplayBottomOverlay();
     Display->UpdateBuffer();
 }
References addr, Address, Memory::Virtual::Check(), Video::Display::ClearBuffer(), CrashFont, debug, DiagnosticDataCollection(), Display, DisplayBottomOverlay(), DisplayTopOverlay(), ExDumpData(), ExFrame, ExPrint(), Bitmap::Get(), Video::Display::GetDefaultFont(), Video::Display::GetHeight, Video::Font::GetInfo(), Video::Display::GetWidth, Video::FontInfo::Height, i, KernelAllocator, len, Length, NULL, PAGE_SIZE, CPU::PageTable(), PowerManager, Video::Display::Print(), Video::Display::PrintString(), Power::Power::Reboot(), Reserved, ROUND_DOWN, Video::Display::SetBufferCursor(), Power::Power::Shutdown(), Bitmap::Size, CPU::Stop(), strcmp, strlen, strncmp(), strtok(), strtoul(), TrimWhiteSpace(), Video::Display::UpdateBuffer(), Video::FontInfo::Width, x, and y.
Referenced by CrashKeyboardDriver::OnInterruptReceived().
Variable Documentation
LowerCase
int LowerCase = true static
Definition at line 56 of file keyboard.cpp.
Referenced by GetLetterFromScanCode().
sc_ascii_high
const char sc_ascii_high[]
Initial value:
= {'?', '?', '!', '@', '#', '$', '%', '^',
                              '&', '*', '(', ')', '_', '+', '?', '?', 'Q', 'W', 'E', 'R', 'T', 'Y',
                              'U', 'I', 'O', 'P', '{', '}', '?', '?', 'A', 'S', 'D', 'F', 'G',
                              'H', 'J', 'K', 'L', ';', '\"', '~', '?', '|', 'Z', 'X', 'C', 'V',
                              'B', 'N', 'M', '<', '>', '?', '?', '?', '?', ' '}
Definition at line 50 of file keyboard.cpp.
Referenced by GetLetterFromScanCode().
sc_ascii_low
const char sc_ascii_low[]
Initial value:
= {'?', '?', '1', '2', '3', '4', '5', '6',
                             '7', '8', '9', '0', '-', '=', '?', '?', 'q', 'w', 'e', 'r', 't', 'y',
                             'u', 'i', 'o', 'p', '[', ']', '?', '?', 'a', 's', 'd', 'f', 'g',
                             'h', 'j', 'k', 'l', ';', '\'', '`', '?', '\\', 'z', 'x', 'c', 'v',
                             'b', 'n', 'm', ',', '.', '/', '?', '?', '?', ' '}
Definition at line 44 of file keyboard.cpp.
Referenced by GetLetterFromScanCode().