Fennix: Vector< T > Class Template Reference
Vector< T > Class Template Reference
#include <vector.hpp>
Public Types
typedef T * iterator
Public Member Functions
NIF Vector ()
NIF Vector (size_t Size)
NIF Vector (size_t Size, const T &Initial)
NIF Vector (const Vector< T > &Vector)
NIF ~Vector ()
NIF void remove (size_t Position)
NIF void remove (const T &Value)
NIF T & null_elem ()
NIF bool null_elem (size_t Index)
NIF T & next (size_t Position)
NIF T & prev (size_t Position)
NIF T & next (const T &Value)
NIF T & prev (const T &Value)
NIF size_t capacity () const
NIF size_t size () const
NIF bool empty () const
NIF iterator begin ()
NIF iterator end ()
NIF T & front ()
NIF T & back ()
NIF void push_back (const T &Value)
NIF void pop_back ()
NIF void reverse ()
NIF void reserve (size_t Capacity)
NIF void resize (size_t Size)
NIF void clear ()
NIF T * data ()
NIF T & operator[] (size_t Index)
NIF Vector< T > & operator= (const Vector< T > &Vector)
Private Attributes
size_t VectorSize = 0
size_t VectorCapacity = 0
T * VectorBuffer = nullptr
Detailed Description
template<class T>
class Vector< T >
Definition at line 9 of file vector.hpp.
Member Typedef Documentation
iterator
template<class T > typedef T* Vector< T >::iterator
Definition at line 17 of file vector.hpp.
Constructor & Destructor Documentation
Vector() [1/4]
template<class T > NIF Vector< T >::Vector () inline
Definition at line 19 of file vector.hpp.
     {
 #ifdef DEBUG_MEM_ALLOCATION
         debug("VECTOR INIT: Vector( )");
 #endif
         VectorCapacity = 0;
         VectorSize = 0;
         VectorBuffer = 0;
     }
References debug, Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
Vector() [2/4]
template<class T > NIF Vector< T >::Vector (size_t Size) inline
Definition at line 29 of file vector.hpp.
     {
         VectorCapacity = Size;
         VectorSize = Size;
 #ifdef DEBUG_MEM_ALLOCATION
         debug("VECTOR INIT: Vector( %lld )", Size);
 #endif
         VectorBuffer = new T[Size];
     }
References debug, Size, Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
Vector() [3/4]
template<class T > NIF Vector< T >::Vector (size_t Size, const T & Initial) inline
Definition at line 39 of file vector.hpp.
     {
         VectorSize = Size;
         VectorCapacity = Size;
 #ifdef DEBUG_MEM_ALLOCATION
         debug("VECTOR INIT: Vector( %lld %llx )", Size, Initial);
 #endif
         assert(Size > 0);
         VectorBuffer = new T[Size];
         for (size_t i = 0; i < Size; i++)
             VectorBuffer[i] = Initial;
     }
References assert, debug, Size, Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
Vector() [4/4]
template<class T > NIF Vector< T >::Vector (const Vector< T > & Vector) inline
Definition at line 52 of file vector.hpp.
     {
         VectorSize = Vector.VectorSize;
         VectorCapacity = Vector.VectorCapacity;
 #ifdef DEBUG_MEM_ALLOCATION
         debug("VECTOR INIT: Vector( <vector> )->Size: %lld", VectorSize);
 #endif
         assert(VectorSize > 0);
         VectorBuffer = new T[VectorSize];
         for (size_t i = 0; i < VectorSize; i++)
             VectorBuffer[i] = Vector.VectorBuffer[i];
     }
References assert, debug, Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
~Vector()
template<class T > NIF Vector< T >::~Vector () inline
Definition at line 65 of file vector.hpp.
     {
 #ifdef DEBUG_MEM_ALLOCATION
         debug("VECTOR INIT: ~Vector( ~%lx )", VectorBuffer);
 #endif
         VectorSize = 0;
         VectorCapacity = 0;
         if (VectorBuffer != nullptr)
         {
             delete[] VectorBuffer, VectorBuffer = nullptr;
         }
     }
References debug, Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
Member Function Documentation
back()
template<class T > NIF T& Vector< T >::back () inline
Definition at line 175 of file vector.hpp.
 { return VectorBuffer[VectorSize - 1]; }
References Vector< T >::VectorBuffer, and Vector< T >::VectorSize.
begin()
template<class T > NIF iterator Vector< T >::begin () inline
Definition at line 169 of file vector.hpp.
 { return VectorBuffer; }
References Vector< T >::VectorBuffer.
capacity()
template<class T > NIF size_t Vector< T >::capacity () const inline
Definition at line 163 of file vector.hpp.
 { return VectorCapacity; }
References Vector< T >::VectorCapacity.
clear()
template<class T > NIF void Vector< T >::clear () inline
Definition at line 226 of file vector.hpp.
     {
         VectorCapacity = 0;
         VectorSize = 0;
         if (VectorBuffer != nullptr)
         {
             delete[] VectorBuffer, VectorBuffer = nullptr;
         }
     }
References Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
data()
template<class T > NIF T* Vector< T >::data () inline
Definition at line 236 of file vector.hpp.
 { return VectorBuffer; }
References Vector< T >::VectorBuffer.
empty()
template<class T > NIF bool Vector< T >::empty () const
end()
template<class T > NIF iterator Vector< T >::end () inline
Definition at line 171 of file vector.hpp.
 { return VectorBuffer + size(); }
References Vector< T >::size(), and Vector< T >::VectorBuffer.
front()
template<class T > NIF T& Vector< T >::front () inline
Definition at line 173 of file vector.hpp.
 { return VectorBuffer[0]; }
References Vector< T >::VectorBuffer.
next() [1/2]
template<class T > NIF T& Vector< T >::next (const T & Value) inline
Definition at line 131 of file vector.hpp.
     {
         for (size_t i = 0; i < VectorSize; i++)
         {
             if (VectorBuffer[i] == Value)
             {
                 if (i + 1 < VectorSize && reinterpret_cast<uintptr_t>(&VectorBuffer[i + 1]))
                     return VectorBuffer[i + 1];
                 else
                     break;
             }
         }
         warn("next( %#lx ) is null (requested by %#lx)", Value, __builtin_return_address(0));
         return this->null_elem();
     }
References Vector< T >::null_elem(), Vector< T >::VectorBuffer, Vector< T >::VectorSize, and warn.
next() [2/2]
template<class T > NIF T& Vector< T >::next (size_t Position) inline
Definition at line 115 of file vector.hpp.
     {
         if (Position + 1 < VectorSize && reinterpret_cast<uintptr_t>(&VectorBuffer[Position + 1]))
             return VectorBuffer[Position + 1];
         warn("next( %lld ) is null (requested by %#lx)", Position, __builtin_return_address(0));
         return this->null_elem();
     }
References Vector< T >::null_elem(), Vector< T >::VectorBuffer, Vector< T >::VectorSize, and warn.
null_elem() [1/2]
template<class T > NIF T& Vector< T >::null_elem () inline
Definition at line 102 of file vector.hpp.
     {
         static T null_elem;
         return null_elem;
     }
Referenced by Vector< T >::next(), Vector< T >::operator[](), and Vector< T >::prev().
null_elem() [2/2]
template<class T > NIF bool Vector< T >::null_elem (size_t Index) inline
Definition at line 108 of file vector.hpp.
     {
         if (!reinterpret_cast<uintptr_t>(&VectorBuffer[Index]))
             return false;
         return true;
     }
References Vector< T >::VectorBuffer.
operator=()
template<class T > NIF Vector<T>& Vector< T >::operator= (const Vector< T > & Vector) inline
Definition at line 248 of file vector.hpp.
     {
         delete[] VectorBuffer;
         VectorSize = Vector.VectorSize;
         VectorCapacity = Vector.VectorCapacity;
 #ifdef DEBUG_MEM_ALLOCATION
         debug("VECTOR ALLOCATION: operator=( <vector> )->Size:%lld", VectorSize);
 #endif
         VectorBuffer = new T[VectorSize];
         for (size_t i = 0; i < VectorSize; i++)
             VectorBuffer[i] = Vector.VectorBuffer[i];
         return *this;
     }
References debug, Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
operator[]()
template<class T > NIF T& Vector< T >::operator[] (size_t Index) inline
Definition at line 238 of file vector.hpp.
     {
         if (!reinterpret_cast<uintptr_t>(&VectorBuffer[Index]))
         {
             warn("operator[]( %lld ) is null (requested by %#lx)", Index, __builtin_return_address(0));
             return this->null_elem();
         }
         return VectorBuffer[Index];
     }
References Vector< T >::null_elem(), Vector< T >::VectorBuffer, and warn.
pop_back()
template<class T > NIF void Vector< T >::pop_back () inline
Definition at line 184 of file vector.hpp.
 { VectorSize--; }
References Vector< T >::VectorSize.
prev() [1/2]
template<class T > NIF T& Vector< T >::prev (const T & Value) inline
Definition at line 147 of file vector.hpp.
     {
         for (size_t i = 0; i < VectorSize; i++)
         {
             if (VectorBuffer[i] == Value)
             {
                 if (i > 0 && reinterpret_cast<uintptr_t>(&VectorBuffer[i - 1]))
                     return VectorBuffer[i - 1];
                 else
                     break;
             }
         }
         warn("prev( %#lx ) is null (requested by %#lx)", Value, __builtin_return_address(0));
         return this->null_elem();
     }
References Vector< T >::null_elem(), Vector< T >::VectorBuffer, Vector< T >::VectorSize, and warn.
prev() [2/2]
template<class T > NIF T& Vector< T >::prev (size_t Position) inline
Definition at line 123 of file vector.hpp.
     {
         if (Position > 0 && reinterpret_cast<uintptr_t>(&VectorBuffer[Position - 1]))
             return VectorBuffer[Position - 1];
         warn("prev( %lld ) is null (requested by %#lx)", Position, __builtin_return_address(0));
         return this->null_elem();
     }
References Vector< T >::null_elem(), Vector< T >::VectorBuffer, and warn.
push_back()
template<class T > NIF void Vector< T >::push_back (const T & Value) inline
Definition at line 177 of file vector.hpp.
     {
         if (VectorSize >= VectorCapacity)
             reserve(VectorCapacity + 5);
         VectorBuffer[VectorSize++] = Value;
     }
References Vector< T >::reserve(), Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
Referenced by Tasking::Task::CreateThread(), Execute::ELFLoadExec(), NetworkEthernet::EthernetEvents::EthernetEvents(), PCI::PCI::FindPCIDevice(), and NetworkARP::ARP::ManageDiscoveredAddresses().
remove() [1/2]
template<class T > NIF void Vector< T >::remove (const T & Value) inline
Definition at line 90 of file vector.hpp.
     {
         for (size_t i = 0; i < VectorSize; i++)
         {
             if (VectorBuffer[i] == Value)
             {
                 remove(i);
                 return;
             }
         }
     }
References Vector< T >::remove(), Vector< T >::VectorBuffer, and Vector< T >::VectorSize.
remove() [2/2]
template<class T > NIF void Vector< T >::remove (size_t Position) inline
Definition at line 78 of file vector.hpp.
     {
         if (Position >= VectorSize)
             return;
         memset(&*(VectorBuffer + Position), 0, sizeof(T));
         for (size_t i = 0; i < VectorSize - 1; i++)
         {
             *(VectorBuffer + Position + i) = *(VectorBuffer + Position + i + 1);
         }
         VectorSize--;
     }
References memset, Vector< T >::VectorBuffer, and Vector< T >::VectorSize.
Referenced by NetworkARP::ARP::ManageDiscoveredAddresses(), and Vector< T >::remove().
reserve()
template<class T > NIF void Vector< T >::reserve (size_t Capacity) inline
Definition at line 198 of file vector.hpp.
     {
         if (VectorBuffer == 0)
         {
             VectorSize = 0;
             VectorCapacity = 0;
         }
 #ifdef DEBUG_MEM_ALLOCATION
         debug("VECTOR ALLOCATION: reverse( %lld )", Capacity);
 #endif
         T *NewBuffer = new T[Capacity];
         size_t _Size = Capacity < VectorSize ? Capacity : VectorSize;
         for (size_t i = 0; i < _Size; i++)
             NewBuffer[i] = VectorBuffer[i];
         VectorCapacity = Capacity;
 #ifdef DEBUG_MEM_ALLOCATION
         debug("VECTOR ALLOCATION: reverse( <Capacity> )->Buffer:~%lld", VectorBuffer);
 #endif
         delete[] VectorBuffer;
         VectorBuffer = NewBuffer;
     }
References debug, Vector< T >::VectorBuffer, Vector< T >::VectorCapacity, and Vector< T >::VectorSize.
Referenced by Vector< T >::push_back(), and Vector< T >::resize().
resize()
template<class T > NIF void Vector< T >::resize (size_t Size) inline
Definition at line 220 of file vector.hpp.
     {
         reserve(Size);
         VectorSize = Size;
     }
References Vector< T >::reserve(), Size, and Vector< T >::VectorSize.
reverse()
template<class T > NIF void Vector< T >::reverse () inline
Definition at line 186 of file vector.hpp.
     {
         if (VectorSize <= 1)
             return;
         for (size_t i = 0, j = VectorSize - 1; i < j; i++, j--)
         {
             T c = *(VectorBuffer + i);
             *(VectorBuffer + i) = *(VectorBuffer + j);
             *(VectorBuffer + j) = c;
         }
     }
References Vector< T >::VectorBuffer, and Vector< T >::VectorSize.
size()
template<class T > NIF size_t Vector< T >::size () const inline
Definition at line 165 of file vector.hpp.
 { return VectorSize; }
References Vector< T >::VectorSize.
Referenced by Tasking::Task::CreateThread(), CrashHandler::DisplayTasksScreen(), Driver::Driver::DriverLoadBindPCI(), Vector< T >::end(), and NetworkARP::ARP::ManageDiscoveredAddresses().
Field Documentation
VectorBuffer
template<class T > T* Vector< T >::VectorBuffer = nullptr private
Definition at line 14 of file vector.hpp.
Referenced by Vector< T >::back(), Vector< T >::begin(), Vector< T >::clear(), Vector< T >::data(), Vector< T >::end(), Vector< T >::front(), Vector< T >::next(), Vector< T >::null_elem(), Vector< T >::operator=(), Vector< T >::operator[](), Vector< T >::prev(), Vector< T >::push_back(), Vector< T >::remove(), Vector< T >::reserve(), Vector< T >::reverse(), Vector< T >::Vector(), and Vector< T >::~Vector().
VectorCapacity
template<class T > size_t Vector< T >::VectorCapacity = 0 private
Definition at line 13 of file vector.hpp.
Referenced by Vector< T >::capacity(), Vector< T >::clear(), Vector< T >::operator=(), Vector< T >::push_back(), Vector< T >::reserve(), Vector< T >::Vector(), and Vector< T >::~Vector().
VectorSize
template<class T > size_t Vector< T >::VectorSize = 0 private
Definition at line 12 of file vector.hpp.
Referenced by Vector< T >::back(), Vector< T >::clear(), Vector< T >::next(), Vector< T >::operator=(), Vector< T >::pop_back(), Vector< T >::prev(), Vector< T >::push_back(), Vector< T >::remove(), Vector< T >::reserve(), Vector< T >::resize(), Vector< T >::reverse(), Vector< T >::size(), Vector< T >::Vector(), and Vector< T >::~Vector().
The documentation for this class was generated from the following file:
Kernel/include/vector.hpp