Fennix: Userspace/musl/src/crypt/crypt_des.h File Reference
crypt_des.h File Reference
#include <stdint.h>
Data Structures
struct expanded_key
Functions
hidden void __des_setkey (const unsigned char *, struct expanded_key *)
hidden void __do_des (uint32_t, uint32_t, uint32_t *, uint32_t *, uint32_t, uint32_t, const struct expanded_key *)
Data Structure Documentation
expanded_key
struct expanded_key
Definition at line 6 of file crypt_des.h.
Data Fields
uint32_t l[16]
uint32_t r[16]
Function Documentation
__des_setkey()
hidden void __des_setkey (const unsigned char * key, struct expanded_key * ekey)
Definition at line 693 of file crypt_des.c.
 {
     uint32_t k0, k1, rawkey0, rawkey1;
     unsigned int shifts, round, i, ibit;
     rawkey0 =
         (uint32_t)key[3] |
         ((uint32_t)key[2] << 8) |
         ((uint32_t)key[1] << 16) |
         ((uint32_t)key[0] << 24);
     rawkey1 =
         (uint32_t)key[7] |
         ((uint32_t)key[6] << 8) |
         ((uint32_t)key[5] << 16) |
         ((uint32_t)key[4] << 24);
     /*
      * Do key permutation and split into two 28-bit subkeys.
      */
     k0 = k1 = 0;
     for (i = 0, ibit = 28; i < 4; i++, ibit -= 4) {
         unsigned int j = i << 1;
         k0 |= key_perm_maskl[i][(rawkey0 >> ibit) & 0xf] |
               key_perm_maskl[i + 4][(rawkey1 >> ibit) & 0xf];
         k1 |= key_perm_maskr[j][(rawkey0 >> ibit) & 0xf];
         ibit -= 4;
         k1 |= key_perm_maskr[j + 1][(rawkey0 >> ibit) & 0xf] |
               key_perm_maskr[i + 8][(rawkey1 >> ibit) & 0xf];
     }
     /*
      * Rotate subkeys and do compression permutation.
      */
     shifts = 0;
     for (round = 0; round < 16; round++) {
         uint32_t t0, t1;
         uint32_t kl, kr;
         shifts += key_shifts[round];
         t0 = (k0 << shifts) | (k0 >> (28 - shifts));
         t1 = (k1 << shifts) | (k1 >> (28 - shifts));
         kl = kr = 0;
         ibit = 25;
         for (i = 0; i < 4; i++) {
             kl |= comp_maskl0[i][(t0 >> ibit) & 7];
             kr |= comp_maskr0[i][(t1 >> ibit) & 7];
             ibit -= 4;
             kl |= comp_maskl1[i][(t0 >> ibit) & 0xf];
             kr |= comp_maskr1[i][(t1 >> ibit) & 0xf];
             ibit -= 3;
         }
         ekey->l[round] = kl;
         ekey->r[round] = kr;
     }
 }
References comp_maskl0, comp_maskl1, comp_maskr0, comp_maskr1, i, j, key_perm_maskl, key_perm_maskr, key_shifts, expanded_key::l, expanded_key::r, round, t0, and t1.
Referenced by _crypt_extended_r_uut(), and setkey().
__do_des()
hidden void __do_des (uint32_t l_in, uint32_t r_in, uint32_t * l_out, uint32_t * r_out, uint32_t count, uint32_t saltbits, const struct expanded_key * ekey)
Definition at line 754 of file crypt_des.c.
 {
     uint32_t l, r;
     /*
      * Do initial permutation (IP).
      */
     l = r = 0;
     if (l_in | r_in) {
         unsigned int i, ibit;
         for (i = 0, ibit = 28; i < 8; i++, ibit -= 4) {
             l |= ip_maskl[i][(l_in >> ibit) & 0xf] |
                  ip_maskl[i + 8][(r_in >> ibit) & 0xf];
             r |= ip_maskr[i][(l_in >> ibit) & 0xf] |
                  ip_maskr[i + 8][(r_in >> ibit) & 0xf];
         }
     }
     while (count--) {
         /*
          * Do each round.
          */
         unsigned int round = 16;
         const uint32_t *kl = ekey->l;
         const uint32_t *kr = ekey->r;
         uint32_t f;
         while (round--) {
             uint32_t r48l, r48r;
             /*
              * Expand R to 48 bits (simulate the E-box).
              */
             r48l    = ((r & 0x00000001) << 23)
                 | ((r & 0xf8000000) >> 9)
                 | ((r & 0x1f800000) >> 11)
                 | ((r & 0x01f80000) >> 13)
                 | ((r & 0x001f8000) >> 15);
             r48r    = ((r & 0x0001f800) << 7)
                 | ((r & 0x00001f80) << 5)
                 | ((r & 0x000001f8) << 3)
                 | ((r & 0x0000001f) << 1)
                 | ((r & 0x80000000) >> 31);
             /*
              * Do salting for crypt() and friends, and
              * XOR with the permuted key.
              */
             f = (r48l ^ r48r) & saltbits;
             r48l ^= f ^ *kl++;
             r48r ^= f ^ *kr++;
             /*
              * Do S-box lookups (which shrink it back to 32 bits)
              * and do the P-box permutation at the same time.
              */
             f = psbox[0][r48l >> 18]
               | psbox[1][(r48l >> 12) & 0x3f]
               | psbox[2][(r48l >> 6) & 0x3f]
               | psbox[3][r48l & 0x3f]
               | psbox[4][r48r >> 18]
               | psbox[5][(r48r >> 12) & 0x3f]
               | psbox[6][(r48r >> 6) & 0x3f]
               | psbox[7][r48r & 0x3f];
             /*
              * Now that we've permuted things, complete f().
              */
             f ^= l;
             l = r;
             r = f;
         }
         r = l;
         l = f;
     }
     /*
      * Do final permutation (inverse of IP).
      */
     {
         unsigned int i, ibit;
         uint32_t lo, ro;
         lo = ro = 0;
         for (i = 0, ibit = 28; i < 4; i++, ibit -= 4) {
             ro |= fp_maskr[i][(l >> ibit) & 0xf] |
                   fp_maskr[i + 4][(r >> ibit) & 0xf];
             ibit -= 4;
             lo |= fp_maskl[i][(l >> ibit) & 0xf] |
                   fp_maskl[i + 4][(r >> ibit) & 0xf];
         }
         *l_out = lo;
         *r_out = ro;
     }
 }
References count, f, fp_maskl, fp_maskr, i, ip_maskl, ip_maskr, expanded_key::l, psbox, r, expanded_key::r, and round.
Referenced by _crypt_extended_r_uut(), des_cipher(), and encrypt().