Fennix Kernel: Kernel/include/interface/errno.h File Reference
errno.h File Reference
#include <types.h>
Macros
#define errno (*__errno_location())
Enumerations
enum KernelErrors {
EOK = 0 , E2BIG = 1 , EACCES = 2 , EADDRINUSE = 3 ,
EADDRNOTAVAIL = 4 , EAFNOSUPPORT = 5 , EAGAIN = 6 , EALREADY = 7 ,
EBADF = 8 , EBADMSG = 9 , EBUSY = 10 , ECANCELED = 11 ,
ECHILD = 12 , ECONNABORTED = 13 , ECONNREFUSED = 14 , ECONNRESET = 15 ,
EDEADLK = 16 , EDESTADDRREQ = 17 , EDOM = 18 , EDQUOT = 19 ,
EEXIST = 20 , EFAULT = 21 , EFBIG = 22 , EHOSTUNREACH = 23 ,
EIDRM = 24 , EILSEQ = 25 , EINPROGRESS = 26 , EINTR = 27 ,
EINVAL = 28 , EIO = 29 , EISCONN = 30 , EISDIR = 31 ,
ELOOP = 32 , EMFILE = 33 , EMLINK = 34 , EMSGSIZE = 35 ,
EMULTIHOP = 36 , ENAMETOOLONG = 37 , ENETDOWN = 38 , ENETRESET = 39 ,
ENETUNREACH = 40 , ENFILE = 41 , ENOBUFS = 42 , ENODATA = 43 ,
ENODEV = 44 , ENOENT = 45 , ENOEXEC = 46 , ENOLCK = 47 ,
ENOLINK = 48 , ENOMEM = 49 , ENOMSG = 50 , ENOPROTOOPT = 51 ,
ENOSPC = 52 , ENOSR = 53 , ENOSTR = 54 , ENOSYS = 55 ,
ENOTCONN = 56 , ENOTDIR = 57 , ENOTEMPTY = 58 , ENOTRECOVERABLE = 59 ,
ENOTSOCK = 60 , ENOTSUP = 61 , ENOTTY = 62 , ENXIO = 63 ,
EOPNOTSUPP = 64 , EOVERFLOW = 65 , EOWNERDEAD = 66 , EPERM = 67 ,
EPIPE = 68 , EPROTO = 69 , EPROTONOSUPPORT = 70 , EPROTOTYPE = 71 ,
ERANGE = 72 , EROFS = 73 , ESPIPE = 74 , ESRCH = 75 ,
ESTALE = 76 , ETIME = 77 , ETIMEDOUT = 78 , ETXTBSY = 79 ,
EWOULDBLOCK = 80 , EXDEV = 81 , __ERRNO_MAX
}
Functions
EXTERNC int * __errno_location (void) __attribute__((const))
char * strerror (int errnum)
Macro Definition Documentation
errno
#define errno (*__errno_location())
Definition at line 593 of file errno.h.
Enumeration Type Documentation
KernelErrors
enum KernelErrors
The documentation for these error codes are from: https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html
Full list: https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/errno.h.html
Enumerator
EOK
No Error
E2BIG
Argument list too long. The sum of the number of bytes used by the new process image's argument list and environment list is greater than the system-imposed limit of {ARG_MAX} bytes. or: Lack of space in an output buffer. or: Argument is greater than the system-imposed maximum.
EACCES
Permission denied. An attempt was made to access a file in a way forbidden by its file access permissions.
EADDRINUSE
Address in use. The specified address is in use.
EADDRNOTAVAIL
Address not available. The specified address is not available from the local system.
EAFNOSUPPORT
Address family not supported. The implementation does not support the specified address family, or the specified address is not a valid address for the address family of the specified socket.
EAGAIN
Resource temporarily unavailable. This is a temporary condition and later calls to the same routine may complete normally.
EALREADY
Connection already in progress. A connection request is already in progress for the specified socket.
EBADF
Bad file descriptor. A file descriptor argument is out of range, refers to no open file, or a read (write) request is made to a file that is only open for writing (reading).
EBADMSG
Bad message. During a read(), getmsg(), getpmsg(), or ioctl() I_RECVFD request to a STREAMS device, a message arrived at the head of the STREAM that is inappropriate for the function receiving the message. read() Message waiting to be read on a STREAM is not a data message. getmsg() or getpmsg() A file descriptor was received instead of a control message. ioctl() Control or data information was received instead of a file descriptor when I_RECVFD was specified.
EBUSY
Resource busy. An attempt was made to make use of a system resource that is not currently available, as it is being used by another process in a manner that would have conflicted with the request being made by this process.
ECANCELED
Operation canceled. The associated asynchronous operation was canceled before completion.
ECHILD
No child process. A wait(), waitid(), or waitpid() function was executed by a process that had no existing or unwaited-for child process.
ECONNABORTED
Connection aborted. The connection has been aborted.
ECONNREFUSED
Connection refused. An attempt to connect to a socket was refused because there was no process listening or because the queue of connection requests was full and the underlying protocol does not support retransmissions.
ECONNRESET
Connection reset. The connection was forcibly closed by the peer.
EDEADLK
Resource deadlock would occur. An attempt was made to lock a system resource that would have resulted in a deadlock situation.
EDESTADDRREQ
Destination address required. No bind address was established.
EDOM
Domain error. An input argument is outside the defined domain of the mathematical function (defined in the ISO C standard).
EDQUOT
Reserved.
EEXIST
File exists. An existing file was mentioned in an inappropriate context; for example, as a new link name in the link() function.
EFAULT
Bad address. The system detected an invalid address in attempting to use an argument of a call. The reliable detection of this error cannot be guaranteed, and when not detected may result in the generation of a signal, indicating an address violation, which is sent to the process.
EFBIG
File too large. The size of a file would exceed the maximum file size of an implementation or offset maximum established in the corresponding file description.
EHOSTUNREACH
Host is unreachable. The destination host cannot be reached (probably because the host is down or a remote router cannot reach it).
EIDRM
Identifier removed. Returned during XSI interprocess communication if an identifier has been removed from the system.
EILSEQ
Illegal byte sequence. A wide-character code has been detected that does not correspond to a valid character, or a byte sequence does not form a valid wide-character code (defined in the ISO C standard).
EINPROGRESS
Operation in progress. This code is used to indicate that an asynchronous operation has not yet completed. or: O_NONBLOCK is set for the socket file descriptor and the connection cannot be immediately established.
EINTR
Interrupted function call. An asynchronous signal was caught by the process during the execution of an interruptible function. If the signal handler performs a normal return, the interrupted function call may return this condition (see the Base Definitions volume of POSIX.1-2017, <signal.h>).
EINVAL
Invalid argument. Some invalid argument was supplied; for example, specifying an undefined signal in a signal() function or a kill() function.
EIO
Input/output error. Some physical input or output error has occurred. This error may be reported on a subsequent operation on the same file descriptor. Any other error-causing operation on the same file descriptor may cause the [EIO] error indication to be lost.
EISCONN
Socket is connected. The specified socket is already connected.
EISDIR
Is a directory. An attempt was made to open a directory with write mode specified.
ELOOP
Symbolic link loop. A loop exists in symbolic links encountered during pathname resolution. This error may also be returned if more than {SYMLOOP_MAX} symbolic links are encountered during pathname resolution.
EMFILE
File descriptor value too large or too many open streams. An attempt was made to open a file descriptor with a value greater than or equal to {OPEN_MAX}, or an attempt was made to open more than the maximum number of streams allowed in the process.
EMLINK
Too many links. An attempt was made to have the link count of a single file exceed {LINK_MAX}.
EMSGSIZE
Message too large. A message sent on a transport provider was larger than an internal message buffer or some other network limit. or: Inappropriate message buffer length.
EMULTIHOP
Reserved.
ENAMETOOLONG
Filename too long. The length of a pathname exceeds {PATH_MAX} and the implementation considers this to be an error, or a pathname component is longer than {NAME_MAX}. This error may also occur when pathname substitution, as a result of encountering a symbolic link during pathname resolution, results in a pathname string the size of which exceeds {PATH_MAX}.
ENETDOWN
Network is down. The local network interface used to reach the destination is down.
ENETRESET
The connection was aborted by the network.
ENETUNREACH
Network unreachable. No route to the network is present.
ENFILE
Too many files open in system. Too many files are currently open in the system. The system has reached its predefined limit for simultaneously open files and temporarily cannot accept requests to open another one.
ENOBUFS
No buffer space available. Insufficient buffer resources were available in the system to perform the socket operation.
ENODATA
No message available. No message is available on the STREAM head read queue.
ENODEV
No such device. An attempt was made to apply an inappropriate function to a device; for example, trying to read a write-only device such as a printer.
ENOENT
No such file or directory. A component of a specified pathname does not exist, or the pathname is an empty string.
ENOEXEC
Executable file format error. A request is made to execute a file that, although it has appropriate privileges, is not in the format required by the implementation for executable files.
ENOLCK
No locks available. A system-imposed limit on the number of simultaneous file and record locks has been reached and no more are currently available.
ENOLINK
Reserved.
ENOMEM
Not enough space. The new process image requires more memory than is allowed by the hardware or system-imposed memory management constraints.
ENOMSG
No message of the desired type. The message queue does not contain a message of the required type during XSI interprocess communication.
ENOPROTOOPT
Protocol not available. The protocol option specified to setsockopt() is not supported by the implementation.
ENOSPC
No space left on a device. During the write() function on a regular file or when extending a directory, there is no free space left on the device.
ENOSR
No STREAM resources. Insufficient STREAMS memory resources are available to perform a STREAMS-related function. This is a temporary condition; it may be recovered from if other processes release resources.
ENOSTR
Not a STREAM. A STREAM function was attempted on a file descriptor that was not associated with a STREAMS device.
ENOSYS
Functionality not supported. An attempt was made to use optional functionality that is not supported in this implementation.
ENOTCONN
Socket not connected. The socket is not connected.
ENOTDIR
Not a directory. A component of the specified pathname exists, but it is not a directory, when a directory was expected; or an attempt was made to create a non-directory file, and the specified pathname contains at least one non- <slash> character and ends with one or more trailing <slash> characters.
ENOTEMPTY
Directory not empty. A directory other than an empty directory was supplied when an empty directory was expected.
ENOTRECOVERABLE
State not recoverable. The state protected by a robust mutex is not recoverable.
ENOTSOCK
Not a socket. The file descriptor does not refer to a socket.
ENOTSUP
Not supported. The implementation does not support the requested feature or value.
ENOTTY
Inappropriate I/O control operation. A control function has been attempted for a file or special file for which the operation is inappropriate.
ENXIO
No such device or address. Input or output on a special file refers to a device that does not exist, or makes a request beyond the capabilities of the device. It may also occur when, for example, a tape drive is not on-line.
EOPNOTSUPP
Operation not supported on socket. The type of socket (address family or protocol) does not support the requested operation.
EOVERFLOW
Value too large to be stored in data type. An operation was attempted which would generate a value that is outside the range of values that can be represented in the relevant data type or that are allowed for a given data item.
EOWNERDEAD
Previous owner died. The owner of a robust mutex terminated while holding the mutex lock.
EPERM
Operation not permitted. An attempt was made to perform an operation limited to processes with appropriate privileges or to the owner of a file or other resource.
EPIPE
Broken pipe. A write was attempted on a socket, pipe, or FIFO for which there is no process to read the data.
EPROTO
Protocol error. Some protocol error occurred. This error is device-specific, but is generally not related to a hardware failure.
EPROTONOSUPPORT
Protocol not supported. The protocol is not supported by the address family, or the protocol is not supported by the implementation.
EPROTOTYPE
Protocol wrong type for socket. The socket type is not supported by the protocol.
ERANGE
Result too large or too small. The result of the function is too large (overflow) or too small (underflow) to be represented in the available space.
EROFS
Read-only file system. An attempt was made to modify a file or directory on a file system that is read-only.
ESPIPE
Invalid seek. An attempt was made to access the file offset associated with a pipe or FIFO.
ESRCH
No such process. No process can be found corresponding to that specified by the given process ID.
ESTALE
Reserved.
ETIME
STREAM ioctl() timeout. The timer set for a STREAMS ioctl() call has expired. The cause of this error is device-specific and could indicate either a hardware or software failure, or a timeout value that is too short for the specific operation. The status of the ioctl() operation is unspecified.
ETIMEDOUT
Connection timed out. The connection to a remote machine has timed out. If the connection timed out during execution of the function that reported this error (as opposed to timing out prior to the function being called), it is unspecified whether the function has completed some or all of the documented behavior associated with a successful completion of the function. or: Operation timed out. The time limit associated with the operation was exceeded before the operation completed.
ETXTBSY
Text file busy. An attempt was made to execute a pure-procedure program that is currently open for writing, or an attempt has been made to open for writing a pure-procedure program that is being executed.
EWOULDBLOCK
Operation would block. An operation on a socket marked as non-blocking has encountered a situation such as no data available that otherwise would have caused the function to suspend execution.
EXDEV
Improper link. A link to a file on another file system was attempted.
__ERRNO_MAX
Definition at line 28 of file errno.h.
 {
     EOK = 0,
     E2BIG = 1,
     EACCES = 2,
     EADDRINUSE = 3,
     EADDRNOTAVAIL = 4,
     EAFNOSUPPORT = 5,
     EAGAIN = 6,
     EALREADY = 7,
     EBADF = 8,
     EBADMSG = 9,
     EBUSY = 10,
     ECANCELED = 11,
     ECHILD = 12,
     ECONNABORTED = 13,
     ECONNREFUSED = 14,
     ECONNRESET = 15,
     EDEADLK = 16,
     EDESTADDRREQ = 17,
     EDOM = 18,
     EDQUOT = 19,
     EEXIST = 20,
     EFAULT = 21,
     EFBIG = 22,
     EHOSTUNREACH = 23,
     EIDRM = 24,
     EILSEQ = 25,
     EINPROGRESS = 26,
     EINTR = 27,
     EINVAL = 28,
     EIO = 29,
     EISCONN = 30,
     EISDIR = 31,
     ELOOP = 32,
     EMFILE = 33,
     EMLINK = 34,
     EMSGSIZE = 35,
     EMULTIHOP = 36,
     ENAMETOOLONG = 37,
     ENETDOWN = 38,
     ENETRESET = 39,
     ENETUNREACH = 40,
     ENFILE = 41,
     ENOBUFS = 42,
     ENODATA = 43,
     ENODEV = 44,
     ENOENT = 45,
     ENOEXEC = 46,
     ENOLCK = 47,
     ENOLINK = 48,
     ENOMEM = 49,
     ENOMSG = 50,
     ENOPROTOOPT = 51,
     ENOSPC = 52,
     ENOSR = 53,
     ENOSTR = 54,
     ENOSYS = 55,
     ENOTCONN = 56,
     ENOTDIR = 57,
     ENOTEMPTY = 58,
     ENOTRECOVERABLE = 59,
     ENOTSOCK = 60,
     ENOTSUP = 61,
     ENOTTY = 62,
     ENXIO = 63,
     EOPNOTSUPP = 64,
     EOVERFLOW = 65,
     EOWNERDEAD = 66,
     EPERM = 67,
     EPIPE = 68,
     EPROTO = 69,
     EPROTONOSUPPORT = 70,
     EPROTOTYPE = 71,
     ERANGE = 72,
     EROFS = 73,
     ESPIPE = 74,
     ESRCH = 75,
     ESTALE = 76,
     ETIME = 77,
     ETIMEDOUT = 78,
     ETXTBSY = 79,
     EWOULDBLOCK = 80,
     EXDEV = 81,
     __ERRNO_MAX
 } KernelErrors;
Function Documentation
__errno_location()
EXTERNC int* __errno_location (void) const
strerror()
char* strerror (int errnum)
Definition at line 35 of file errno.cpp.
 {
     if (errnum < 0)
         errnum = -errnum;
     switch (errnum)
     {
     case EOK:
         return (char *)"No error";
     case E2BIG:
         return (char *)"Argument list too long";
     case EACCES:
         return (char *)"Permission denied";
     case EADDRINUSE:
         return (char *)"Address in use";
     case EADDRNOTAVAIL:
         return (char *)"Address not available";
     case EAFNOSUPPORT:
         return (char *)"Address family not supported";
     case EAGAIN:
         return (char *)"Resource unavailable, try again";
     case EALREADY:
         return (char *)"Connection already in progress";
     case EBADF:
         return (char *)"Bad file descriptor";
     case EBADMSG:
         return (char *)"Bad message";
     case EBUSY:
         return (char *)"Device or resource busy";
     case ECANCELED:
         return (char *)"Operation canceled";
     case ECHILD:
         return (char *)"No child processes";
     case ECONNABORTED:
         return (char *)"Connection aborted";
     case ECONNREFUSED:
         return (char *)"Connection refused";
     case ECONNRESET:
         return (char *)"Connection reset";
     case EDEADLK:
         return (char *)"Resource deadlock would occur";
     case EDESTADDRREQ:
         return (char *)"Destination address required";
     case EDOM:
         return (char *)"Mathematics argument out of domain of function";
     case EDQUOT:
         return (char *)"Reserved";
     case EEXIST:
         return (char *)"File exists";
     case EFAULT:
         return (char *)"Bad address";
     case EFBIG:
         return (char *)"File too large";
     case EHOSTUNREACH:
         return (char *)"Host is unreachable";
     case EIDRM:
         return (char *)"Identifier removed";
     case EILSEQ:
         return (char *)"Illegal byte sequence";
     case EINPROGRESS:
         return (char *)"Operation in progress";
     case EINTR:
         return (char *)"Interrupted function";
     case EINVAL:
         return (char *)"Invalid argument";
     case EIO:
         return (char *)"I/O error";
     case EISCONN:
         return (char *)"Socket is connected";
     case EISDIR:
         return (char *)"Is a directory";
     case ELOOP:
         return (char *)"Too many levels of symbolic links";
     case EMFILE:
         return (char *)"File descriptor value too large";
     case EMLINK:
         return (char *)"Too many links";
     case EMSGSIZE:
         return (char *)"Message too large";
     case EMULTIHOP:
         return (char *)"Reserved";
     case ENAMETOOLONG:
         return (char *)"Filename too long";
     case ENETDOWN:
         return (char *)"Network is down";
     case ENETRESET:
         return (char *)"Connection aborted by network";
     case ENETUNREACH:
         return (char *)"Network unreachable";
     case ENFILE:
         return (char *)"Too many files open in system";
     case ENOBUFS:
         return (char *)"No buffer space available";
     case ENODATA:
         return (char *)"No message available on the STREAM head read queue";
     case ENODEV:
         return (char *)"No such device";
     case ENOENT:
         return (char *)"No such file or directory";
     case ENOEXEC:
         return (char *)"Executable file format error";
     case ENOLCK:
         return (char *)"No locks available";
     case ENOLINK:
         return (char *)"Reserved";
     case ENOMEM:
         return (char *)"Not enough space";
     case ENOMSG:
         return (char *)"No message of the desired type";
     case ENOPROTOOPT:
         return (char *)"Protocol not available";
     case ENOSPC:
         return (char *)"No space left on device";
     case ENOSR:
         return (char *)"No STREAM resources";
     case ENOSTR:
         return (char *)"Not a STREAM";
     case ENOSYS:
         return (char *)"Functionality not supported";
     case ENOTCONN:
         return (char *)"The socket is not connected";
     case ENOTDIR:
         return (char *)"Not a directory or a symbolic link to a directory";
     case ENOTEMPTY:
         return (char *)"Directory not empty";
     case ENOTRECOVERABLE:
         return (char *)"State not recoverable";
     case ENOTSOCK:
         return (char *)"Not a socket";
     case ENOTSUP:
         return (char *)"Not supported";
     case ENOTTY:
         return (char *)"Inappropriate I/O control operation";
     case ENXIO:
         return (char *)"No such device or address";
     case EOPNOTSUPP:
         return (char *)"Operation not supported on socket";
     case EOVERFLOW:
         return (char *)"Value too large to be stored in data type";
     case EOWNERDEAD:
         return (char *)"Previous owner died";
     case EPERM:
         return (char *)"Operation not permitted";
     case EPIPE:
         return (char *)"Broken pipe";
     case EPROTO:
         return (char *)"Protocol error";
     case EPROTONOSUPPORT:
         return (char *)"Protocol not supported";
     case EPROTOTYPE:
         return (char *)"Protocol wrong type for socket";
     case ERANGE:
         return (char *)"Result too large";
     case EROFS:
         return (char *)"Read-only file system";
     case ESPIPE:
         return (char *)"Invalid seek";
     case ESRCH:
         return (char *)"No such process";
     case ESTALE:
         return (char *)"Reserved";
     case ETIME:
         return (char *)"Stream ioctl() timeout";
     case ETIMEDOUT:
         return (char *)"Connection timed out";
     case ETXTBSY:
         return (char *)"Text file busy";
     case EWOULDBLOCK:
         return (char *)"Operation would block";
     case EXDEV:
         return (char *)"Cross-device link";
     default:
         return (char *)"Unknown error";
     }
 }
References E2BIG, EACCES, EADDRINUSE, EADDRNOTAVAIL, EAFNOSUPPORT, EAGAIN, EALREADY, EBADF, EBADMSG, EBUSY, ECANCELED, ECHILD, ECONNABORTED, ECONNREFUSED, ECONNRESET, EDEADLK, EDESTADDRREQ, EDOM, EDQUOT, EEXIST, EFAULT, EFBIG, EHOSTUNREACH, EIDRM, EILSEQ, EINPROGRESS, EINTR, EINVAL, EIO, EISCONN, EISDIR, ELOOP, EMFILE, EMLINK, EMSGSIZE, EMULTIHOP, ENAMETOOLONG, ENETDOWN, ENETRESET, ENETUNREACH, ENFILE, ENOBUFS, ENODATA, ENODEV, ENOENT, ENOEXEC, ENOLCK, ENOLINK, ENOMEM, ENOMSG, ENOPROTOOPT, ENOSPC, ENOSR, ENOSTR, ENOSYS, ENOTCONN, ENOTDIR, ENOTEMPTY, ENOTRECOVERABLE, ENOTSOCK, ENOTSUP, ENOTTY, ENXIO, EOK, EOPNOTSUPP, EOVERFLOW, EOWNERDEAD, EPERM, EPIPE, EPROTO, EPROTONOSUPPORT, EPROTOTYPE, ERANGE, EROFS, ESPIPE, ESRCH, ESTALE, ETIME, ETIMEDOUT, ETXTBSY, EWOULDBLOCK, and EXDEV.
Referenced by cmd_modinfo(), KernelMainThread(), KShellThread(), linux_mmap(), Driver::Manager::LoadAllDrivers(), Driver::Manager::PreloadDrivers(), Driver::Manager::UnloadAllDrivers(), and WriteDiagDataToNode().