Fennix: mlibc::charset Struct Reference
mlibc::charset Struct Reference
#include <charset.hpp>
Public Member Functions
bool is_ascii_superset ()
bool is_alpha (codepoint c)
bool is_digit (codepoint c)
bool is_xdigit (codepoint c)
bool is_alnum (codepoint c)
bool is_punct (codepoint c)
bool is_graph (codepoint c)
bool is_blank (codepoint c)
bool is_space (codepoint c)
bool is_print (codepoint c)
bool is_lower (codepoint c)
bool is_upper (codepoint c)
codepoint to_lower (codepoint c)
codepoint to_upper (codepoint c)
Detailed Description
Definition at line 11 of file charset.hpp.
Member Function Documentation
is_alnum()
bool mlibc::charset::is_alnum (codepoint c)
Definition at line 40 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_alnum() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by isalnum(), and iswalnum().
is_alpha()
bool mlibc::charset::is_alpha (codepoint c)
Definition at line 13 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_alpha() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by isalpha(), and iswalpha().
is_ascii_superset()
bool mlibc::charset::is_ascii_superset ()
Definition at line 8 of file charset.cpp.
{
     // TODO: For locales that change the meaning of ASCII chars, this needs to be changed.
     return true;
 }
Referenced by is_alnum(), is_alpha(), is_blank(), is_digit(), is_graph(), is_lower(), is_print(), is_punct(), is_space(), is_upper(), is_xdigit(), to_lower(), and to_upper().
is_blank()
bool mlibc::charset::is_blank (codepoint c)
Definition at line 73 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return c == ' ' || c == '\t';
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_blank() is not implemented"
                 " for the full Unicode charset " << c << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by isblank(), and iswblank().
is_digit()
bool mlibc::charset::is_digit (codepoint c)
Definition at line 22 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return c >= '0' && c <= '9';
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_digit() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by isdigit(), and iswdigit().
is_graph()
bool mlibc::charset::is_graph (codepoint c)
Definition at line 64 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return c >= 0x21 && c <= 0x7E;
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_graph() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by isgraph(), and iswgraph().
is_lower()
bool mlibc::charset::is_lower (codepoint c)
Definition at line 100 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return (c >= 'a' && c <= 'z');
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_print() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by islower(), and iswlower().
is_print()
bool mlibc::charset::is_print (codepoint c)
Definition at line 91 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return c >= 0x20 && c <= 0x7E;
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_print() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by isprint(), and iswprint().
is_punct()
bool mlibc::charset::is_punct (codepoint c)
Definition at line 49 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return c == '!' || c == '"' || c == '#' || c == '$' || c == '%' || c == '&'
                 || c == '\'' || c == '(' || c == ')' || c == '*' || c == '+' || c == ','
                 || c == '-' || c == '.' || c == '/'
                 || c == ':' || c == ';' || c == '<' || c == '=' || c == '>' || c == '?'
                 || c == '@'
                 || c == '[' || c == '\\' || c == ']' || c == '^' || c == '_' || c == '`'
                 || c == '{' || c == '|' || c == '}' || c == '~';
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_punct() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by ispunct(), and iswpunct().
is_space()
bool mlibc::charset::is_space (codepoint c)
Definition at line 82 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return c == ' ' || c == '\t' || c == '\n' || c == '\v' || c == '\f' || c == '\r';
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_space() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by isspace(), and iswspace().
is_upper()
bool mlibc::charset::is_upper (codepoint c)
Definition at line 109 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return (c >= 'A' && c <= 'Z');
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_print() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by isupper(), and iswupper().
is_xdigit()
bool mlibc::charset::is_xdigit (codepoint c)
Definition at line 31 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F');
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::is_xdigit() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return false;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by iswxdigit(), and isxdigit().
to_lower()
codepoint mlibc::charset::to_lower (codepoint c)
Definition at line 118 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         if(c >= 'A' && c <= 'Z')
             return c - 'A' + 'a';
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::to_lower() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return c;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by tolower(), and towlower().
to_upper()
codepoint mlibc::charset::to_upper (codepoint c)
Definition at line 128 of file charset.cpp.
{
     if(c <= 0x7F && is_ascii_superset())
         if(c >= 'a' && c <= 'z')
             return c - 'a' + 'A';
     if(c > 0x7F)
         mlibc::infoLogger() << "mlibc: charset::to_upper() is not implemented"
                 " for the full Unicode charset" << frg::endlog;
     return c;
 }
References c, mlibc::infoLogger, and is_ascii_superset().
Referenced by toupper(), and towupper().
The documentation for this struct was generated from the following files:
Userspace/mlibc/options/internal/include/mlibc/charset.hpp
Userspace/mlibc/options/internal/generic/charset.cpp