Fennix: Kernel/Architecture/amd64/SystemCalls.cpp File Reference
SystemCalls.cpp File Reference
#include <syscalls.hpp>
#include <cpu.hpp>
#include "cpu/gdt.hpp"
Functions
uint64_t SystemCallsHandler (SyscallsFrame *regs)
void SystemCallHandlerStub ()
__naked __used __no_stack_protector __aligned (16) void SystemCallHandlerStub()
void InitializeSystemCalls ()
Initialize syscalls for the current CPU. (Function is available on x32, x64 & aarch64)
Function Documentation
__aligned()
__naked __used __no_stack_protector __aligned (16)
Definition at line 32 of file SystemCalls.cpp.
 {
     asmv("swapgs\n");            /* Swap GS to get the CPUData */
     asmv("mov %rsp, %gs:0x8\n"); /* We save the current rsp to CPUData->TempStack */
     asmv("mov %gs:0x0, %rsp\n"); /* Get CPUData->SystemCallStack and set it as rsp */
     asmv("push $0x1b\n");        /* Push user data segment for SyscallsFrame */
     asmv("push %gs:0x8\n");      /* Push CPUData->TempStack (old rsp) for SyscallsFrame */
     asmv("push %r11\n");         /* Push the flags for SyscallsFrame */
     asmv("push $0x23\n");        /* Push user code segment for SyscallsFrame */
     asmv("push %rcx\n");         /* Push the return address for SyscallsFrame + sysretq (https://www.felixcloutier.com/x86/sysret) */
     asmv("push %rax\n" /* Push registers */
          "push %rbx\n"
          "push %rcx\n"
          "push %rdx\n"
          "push %rsi\n"
          "push %rdi\n"
          "push %rbp\n"
          "push %r8\n"
          "push %r9\n"
          "push %r10\n"
          "push %r11\n"
          "push %r12\n"
          "push %r13\n"
          "push %r14\n"
          "push %r15\n");
     asmv("mov %rsp, %rdi\n"); /* Set the first argument to the SyscallsFrame pointer */
     asmv("mov $0, %rbp\n");
     asmv("call SystemCallsHandler\n");
     asmv("pop %r15\n" /* Pop registers except rax */
          "pop %r14\n"
          "pop %r13\n"
          "pop %r12\n"
          "pop %r11\n"
          "pop %r10\n"
          "pop %r9\n"
          "pop %r8\n"
          "pop %rbp\n"
          "pop %rdi\n"
          "pop %rsi\n"
          "pop %rdx\n"
          "pop %rcx\n"
          "pop %rbx\n");
     asmv("mov %gs:0x8, %rsp\n"); // Restore rsp from CPUData->TempStack
 #ifdef DEBUG
     asmv("movq $0, %gs:0x8\n"); // Easier to debug stacks // FIXME: Can't use xor
 #endif
     asmv("swapgs\n");  // Swap GS back to the user GS
     asmv("sti\n");     // Enable interrupts
     asmv("sysretq\n"); // Return to rcx address in user mode
 }
References asmv().
InitializeSystemCalls()
void InitializeSystemCalls ()
Initialize syscalls for the current CPU. (Function is available on x32, x64 & aarch64)
Definition at line 88 of file SystemCalls.cpp.
 {
     wrmsr(MSR_EFER, rdmsr(MSR_EFER) | 1);
     wrmsr(MSR_STAR, ((uint64_t)(GDT_KERNEL_CODE) << 32) | ((uint64_t)(GDT_KERNEL_DATA | 3) << 48));
     wrmsr(MSR_LSTAR, (uint64_t)SystemCallHandlerStub);
     wrmsr(MSR_SYSCALL_MASK, (uint64_t)(1 << 9));
 }
References GDT_KERNEL_CODE, GDT_KERNEL_DATA, CPU::x64::MSR_EFER, CPU::x64::MSR_LSTAR, CPU::x64::MSR_STAR, CPU::x64::MSR_SYSCALL_MASK, and SystemCallHandlerStub().
SystemCallHandlerStub()
void SystemCallHandlerStub ()
Definition at line 22 of file SystemCalls.cpp.
 {
 }
Referenced by InitializeSystemCalls().
SystemCallsHandler()
uint64_t SystemCallsHandler (SyscallsFrame * regs)
Definition at line 26 of file Syscalls.cpp.
 {
     CPU::Interrupts(CPU::Enable);
     SmartLock(SyscallsLock); /* TODO: This should be replaced or moved somewhere else. */
     Tasking::TaskInfo *Ptinfo = &TaskManager->GetCurrentProcess()->Info;
     Tasking::TaskInfo *Ttinfo = &TaskManager->GetCurrentThread()->Info;
     uint64_t TempTimeCalc = TimeManager->GetCounter();
     switch (Ttinfo->Compatibility)
     {
     case Tasking::TaskCompatibility::Native:
     {
         uintptr_t ret = HandleNativeSyscalls(Frame);
         Ptinfo->KernelTime += TimeManager->GetCounter() - TempTimeCalc;
         Ttinfo->KernelTime += TimeManager->GetCounter() - TempTimeCalc;
         return ret;
     }
     case Tasking::TaskCompatibility::Linux:
     {
         uintptr_t ret = HandleLinuxSyscalls(Frame);
         Ptinfo->KernelTime += TimeManager->GetCounter() - TempTimeCalc;
         Ttinfo->KernelTime += TimeManager->GetCounter() - TempTimeCalc;
         return ret;
     }
     case Tasking::TaskCompatibility::Windows:
     {
         error("Windows compatibility not implemented yet.");
         break;
     }
     default:
     {
         error("Unknown compatibility mode! Killing thread...");
         TaskManager->KillThread(TaskManager->GetCurrentThread(), -0xCA11);
         break;
     }
     }
     assert(false); /* Should never reach here. */
     return 0;
 }