Fennix Userspace: Userspace/musl/src/linux/eventfd.c File Reference
eventfd.c File Reference
#include <sys/eventfd.h>
#include <unistd.h>
#include <errno.h>
#include "syscall.h"
Functions
int eventfd (unsigned int count, int flags)
int eventfd_read (int fd, eventfd_t *value)
int eventfd_write (int fd, eventfd_t value)
Function Documentation
eventfd()
int eventfd (unsigned int count, int flags)
Definition at line 6 of file eventfd.c.
 {
     int r = __syscall(SYS_eventfd2, count, flags);
 #ifdef SYS_eventfd
     if (r==-ENOSYS && !flags) r = __syscall(SYS_eventfd, count);
 #endif
     return __syscall_ret(r);
 }
References __syscall, __syscall_ret(), count, and ENOSYS.
eventfd_read()
int eventfd_read (int fd, eventfd_t * value)
Definition at line 15 of file eventfd.c.
 {
     return (sizeof(*value) == read(fd, value, sizeof(*value))) ? 0 : -1;
 }
References read(), and value.
eventfd_write()
int eventfd_write (int fd, eventfd_t value)
Definition at line 20 of file eventfd.c.
 {
     return (sizeof(value) == write(fd, &value, sizeof(value))) ? 0 : -1;
 }
References value, and write().