Fennix Userspace: Userspace/apps/base/bash/builtins/bashgetopt.c File Reference
bashgetopt.c File Reference
#include <config.h>
#include "../bashansi.h"
#include <chartypes.h>
#include <errno.h>
#include "../shell.h"
#include "common.h"
#include "bashgetopt.h"
Macros
#define ISOPT(s) (((*(s) == '-') || (plus && *(s) == '+')) && (s)[1])
#define NOTOPT(s) (((*(s) != '-') && (!plus || *(s) != '+')) || (s)[1] == '\0')
Functions
int internal_getopt (WORD_LIST *list, char *opts)
void reset_internal_getopt ()
Variables
static int sp
char * list_optarg
int list_optflags
int list_optopt
int list_opttype
static WORD_LIST * lhead = (WORD_LIST *)NULL
WORD_LIST * lcurrent = (WORD_LIST *)NULL
WORD_LIST * loptend
Macro Definition Documentation
ISOPT
#define ISOPT (s) (((*(s) == '-') || (plus && *(s) == '+')) && (s)[1])
Definition at line 36 of file bashgetopt.c.
NOTOPT
#define NOTOPT (s) (((*(s) != '-') && (!plus || *(s) != '+')) || (s)[1] == '\0')
Definition at line 37 of file bashgetopt.c.
Function Documentation
internal_getopt()
int internal_getopt (WORD_LIST * list, char * opts)
Definition at line 51 of file bashgetopt.c.
 {
     register int c;
     register char *cp;
     int plus;   /* nonzero means to handle +option */
     static char errstr[3] = { '-', '\0', '\0' };
     plus = *opts == '+';
     if (plus)
         opts++;
     if (list == 0) {
         list_optarg = (char *)NULL;
         list_optflags = 0;
         loptend = (WORD_LIST *)NULL;    /* No non-option arguments */
         return -1;
     }
     if (list != lhead || lhead == 0) {
         /* Hmmm.... called with a different word list.  Reset. */
         sp = 1;
         lcurrent = lhead = list;
         loptend = (WORD_LIST *)NULL;
     }
     if (sp == 1) {
         if (lcurrent == 0 || NOTOPT(lcurrent->word->word)) {
                 lhead = (WORD_LIST *)NULL;
                 loptend = lcurrent;
             return(-1);
         } else if (ISHELP (lcurrent->word->word)) {
             lhead = (WORD_LIST *)NULL;
             loptend = lcurrent;
             return (GETOPT_HELP);
         } else if (lcurrent->word->word[0] == '-' &&
                lcurrent->word->word[1] == '-' &&
                lcurrent->word->word[2] == 0) {
             lhead = (WORD_LIST *)NULL;
             loptend = lcurrent->next;
             return(-1);
         }
         errstr[0] = list_opttype = lcurrent->word->word[0];
     }
     list_optopt = c = lcurrent->word->word[sp];
     if (c == ':' || (cp = strchr(opts, c)) == NULL) {
         errstr[1] = c;
         sh_invalidopt (errstr);
         if (lcurrent->word->word[++sp] == '\0') {
             lcurrent = lcurrent->next;
             sp = 1;
         }
         list_optarg = NULL;
         list_optflags = 0;
         if (lcurrent)
             loptend = lcurrent->next;
         return('?');
     }
     if (*++cp == ':' || *cp == ';') {
         /* `:': Option requires an argument. */
         /* `;': option argument may be missing */
         /* We allow -l2 as equivalent to -l 2 */
         if (lcurrent->word->word[sp+1]) {
             list_optarg = lcurrent->word->word + sp + 1;
             list_optflags = 0;
             lcurrent = lcurrent->next;
         /* If the specifier is `;', don't set optarg if the next
            argument looks like another option. */
 #if 0
         } else if (lcurrent->next && (*cp == ':' || lcurrent->next->word->word[0] != '-')) {
 #else
         } else if (lcurrent->next && (*cp == ':' || NOTOPT(lcurrent->next->word->word))) {
 #endif
             lcurrent = lcurrent->next;
             list_optarg = lcurrent->word->word;
             list_optflags = lcurrent->word->flags;
             lcurrent = lcurrent->next;
         } else if (*cp == ';') {
             list_optarg = (char *)NULL;
             list_optflags = 0;
             lcurrent = lcurrent->next;
         } else {    /* lcurrent->next == NULL */
             errstr[1] = c;
             sh_needarg (errstr);
             sp = 1;
             list_optarg = (char *)NULL;
             list_optflags = 0;
             return('?');
         }
         sp = 1;
     } else if (*cp == '#') {
         /* option requires a numeric argument */
         if (lcurrent->word->word[sp+1]) {
             if (DIGIT(lcurrent->word->word[sp+1])) {
                 list_optarg = lcurrent->word->word + sp + 1;
                 list_optflags = 0;
                 lcurrent = lcurrent->next;
             } else {
                 list_optarg = (char *)NULL;
                 list_optflags = 0;
             }
         } else {
             if (lcurrent->next && legal_number(lcurrent->next->word->word, (intmax_t *)0)) {
                 lcurrent = lcurrent->next;
                 list_optarg = lcurrent->word->word;
                 list_optflags = lcurrent->word->flags;
                 lcurrent = lcurrent->next;
             } else {
                 errstr[1] = c;
                 sh_neednumarg (errstr);
                 sp = 1;
                 list_optarg = (char *)NULL;
                 list_optflags = 0;
                 return ('?');
             }
         }
     } else {
         /* No argument, just return the option. */
         if (lcurrent->word->word[++sp] == '\0') {
             sp = 1;
             lcurrent = lcurrent->next;
         }
         list_optarg = (char *)NULL;
         list_optflags = 0;
     }
     return(c);
 }
References c, DIGIT, word_desc::flags, GETOPT_HELP, ISHELP, lcurrent, legal_number(), lhead, list(), list_optarg, list_optflags, list_optopt, list_opttype, loptend, word_list::next, NOTOPT, NULL, sh_invalidopt(), sh_needarg(), sh_neednumarg(), sp, strchr(), word_desc::word, and word_list::word.
Referenced by accept_builtin(), asort_builtin(), csv_builtin(), cut_internal(), dsv_builtin(), fdflags_builtin(), getconf_builtin(), head_builtin(), id_builtin(), ln_builtin(), mkdir_builtin(), mkfifo_builtin(), mktemp_builtin(), no_options(), pathchk_builtin(), print_builtin(), printenv_builtin(), push_builtin(), realpath_builtin(), rm_builtin(), seq_builtin(), stat_builtin(), tee_builtin(), template_builtin(), tty_builtin(), uname_builtin(), and whoami_builtin().
reset_internal_getopt()
void reset_internal_getopt ()
Definition at line 190 of file bashgetopt.c.
 {
     lhead = lcurrent = loptend = (WORD_LIST *)NULL;
     sp = 1;
 }
References lcurrent, lhead, loptend, NULL, and sp.
Referenced by accept_builtin(), asort_builtin(), csv_builtin(), cut_internal(), dsv_builtin(), fdflags_builtin(), getconf_builtin(), head_builtin(), id_builtin(), ln_builtin(), mkdir_builtin(), mkfifo_builtin(), mktemp_builtin(), no_options(), pathchk_builtin(), print_builtin(), printenv_builtin(), push_builtin(), realpath_builtin(), rm_builtin(), seq_builtin(), stat_builtin(), tee_builtin(), template_builtin(), tty_builtin(), uname_builtin(), and whoami_builtin().
Variable Documentation
lcurrent
WORD_LIST* lcurrent = (WORD_LIST *)NULL
Definition at line 47 of file bashgetopt.c.
Referenced by internal_getopt(), print_builtin(), reset_internal_getopt(), and seq_builtin().
lhead
WORD_LIST* lhead = (WORD_LIST *)NULL static
Definition at line 46 of file bashgetopt.c.
Referenced by internal_getopt(), and reset_internal_getopt().
list_optarg
char* list_optarg
Definition at line 41 of file bashgetopt.c.
Referenced by accept_builtin(), csv_builtin(), cut_internal(), dsv_builtin(), fdflags_builtin(), head_builtin(), internal_getopt(), mkdir_builtin(), mkfifo_builtin(), mktemp_builtin(), print_builtin(), realpath_builtin(), seq_builtin(), and stat_builtin().
list_optflags
int list_optflags
Definition at line 42 of file bashgetopt.c.
Referenced by internal_getopt().
list_optopt
int list_optopt
Definition at line 43 of file bashgetopt.c.
Referenced by internal_getopt().
list_opttype
int list_opttype
Definition at line 44 of file bashgetopt.c.
Referenced by internal_getopt().
loptend
WORD_LIST* loptend
Definition at line 48 of file bashgetopt.c.
Referenced by accept_builtin(), asort_builtin(), basename_builtin(), csv_builtin(), cut_internal(), dirname_builtin(), dsv_builtin(), fdflags_builtin(), getconf_builtin(), head_builtin(), id_builtin(), internal_getopt(), ln_builtin(), mkdir_builtin(), mkfifo_builtin(), mktemp_builtin(), pathchk_builtin(), print_builtin(), printenv_builtin(), push_builtin(), realpath_builtin(), reset_internal_getopt(), rm_builtin(), seq_builtin(), stat_builtin(), strftime_builtin(), tee_builtin(), template_builtin(), tty_builtin(), uname_builtin(), and whoami_builtin().
sp
int sp static
Definition at line 39 of file bashgetopt.c.
Referenced by __dls2(), __dls2b(), __dls3(), __parsespent(), _dlstart_c(), addfname(), alloc_procps_scan(), awk_sub(), chrt_main(), evalcommand(), evalfor(), expandarg(), fallbackQSort3(), fgetspent(), free_procps_scan(), freestrings(), getspnam(), getspnam_r(), getstat(), growstackblock(), has_super(), I_Scale2x(), I_Scale3x(), I_Scale4x(), I_Scale5x(), ifsbreakup(), internal_getopt(), loadstat(), mainQSort3(), match_pattern(), match_upattern(), parse_gnutimefmt(), parse_url(), pgetc(), popstackmark(), popstring(), print_autowrap(), procps_scan(), pushstring(), putspent(), refresh(), reread_config_file(), reset_internal_getopt(), rl_restore_state(), rl_save_state(), scan_request(), send_probe(), stalloc(), statlink(), and statval().