Fennix Userspace: Userspace/musl/src/prng/lrand48.c File Reference
lrand48.c File Reference
#include <stdlib.h>
#include <inttypes.h>
#include "rand48.h"
Functions
long nrand48 (unsigned short s[3])
long lrand48 (void)
Function Documentation
lrand48()
long lrand48 (void)
Definition at line 10 of file lrand48.c.
 {
     return nrand48(__seed48);
 }
References __seed48, and nrand48().
nrand48()
long nrand48 (unsigned short s[3])
Definition at line 5 of file lrand48.c.
 {
     return __rand48_step(s, __seed48+3) >> 17;
 }
References __rand48_step(), and __seed48.
Referenced by lrand48().