Fennix: Userspace/mlibc/sysdeps/aero/generic/entry.cpp File Reference
entry.cpp File Reference
#include <bits/ensure.h>
#include <mlibc/elf/startup.h>
#include <stdint.h>
#include <stdlib.h>
Data Structures
struct LibraryGuard
Functions
void __mlibc_initLocale ()
uintptr_t * __dlapi_entrystack ()
void __mlibc_entry (int(*main_fn)(int argc, char *argv[], char *env[]))
Variables
char ** environ
static mlibc::exec_stack_data __mlibc_stack_data
static LibraryGuard guard
Function Documentation
__dlapi_entrystack()
uintptr_t* __dlapi_entrystack ()
Definition at line 398 of file main.cpp.
{
     return entryStack;
 }
Referenced by LibraryGuard::LibraryGuard().
__mlibc_entry()
void __mlibc_entry (int(*)(int argc, char *argv[], char *env[]) main_fn)
Definition at line 29 of file entry.cpp.
{
     // TODO: call __dlapi_enter, otherwise static builds will break (see Linux sysdeps)
     auto result =
         main_fn(__mlibc_stack_data.argc, __mlibc_stack_data.argv, environ);
     exit(result);
 }
References __mlibc_stack_data, mlibc::exec_stack_data::argc, mlibc::exec_stack_data::argv, environ, and exit().
__mlibc_initLocale()
void __mlibc_initLocale ()
Definition at line 74 of file locale-stubs.cpp.
{
     mlibc::collate_facet = &mlibc::c_locale;
     mlibc::ctype_facet = &mlibc::c_locale;
     mlibc::monetary_facet = &mlibc::c_locale;
     mlibc::numeric_facet = &mlibc::c_locale;
     mlibc::time_facet = &mlibc::c_locale;
     mlibc::messages_facet = &mlibc::c_locale;
 }
Referenced by LibraryGuard::LibraryGuard().
Variable Documentation
__mlibc_stack_data
mlibc::exec_stack_data __mlibc_stack_data static
Definition at line 12 of file entry.cpp.
Referenced by __mlibc_entry(), and LibraryGuard::LibraryGuard().
environ
char** environ extern
Definition at line 42 of file lib.c.
Referenced by __mlibc_entry().
guard
LibraryGuard guard static
Definition at line 18 of file entry.cpp.