Fennix Userspace: Userspace/musl/src/internal/complex_impl.h File Reference
complex_impl.h File Reference
#include <complex.h>
#include "libm.h"
Macros
#define __CMPLX(x, y, t) ((union { _Complex t __z; t __xy[2]; }){.__xy = {(x),(y)}}.__z)
#define CMPLX(x, y) __CMPLX(x, y, double)
#define CMPLXF(x, y) __CMPLX(x, y, float)
#define CMPLXL(x, y) __CMPLX(x, y, long double)
Functions
hidden double complex __ldexp_cexp (double complex, int)
hidden float complex __ldexp_cexpf (float complex, int)
Macro Definition Documentation
__CMPLX
#define __CMPLX (x, y, t) ((union { _Complex t __z; t __xy[2]; }){.__xy = {(x),(y)}}.__z)
Definition at line 12 of file complex_impl.h.
CMPLX
#define CMPLX (x, y) __CMPLX(x, y, double)
Definition at line 15 of file complex_impl.h.
CMPLXF
#define CMPLXF (x, y) __CMPLX(x, y, float)
Definition at line 16 of file complex_impl.h.
CMPLXL
#define CMPLXL (x, y) __CMPLX(x, y, long double)
Definition at line 17 of file complex_impl.h.
Function Documentation
__ldexp_cexp()
hidden double complex __ldexp_cexp (double complex, int expt)
Definition at line 67 of file __cexp.c.
 {
     double x, y, exp_x, scale1, scale2;
     int ex_expt, half_expt;
     x = creal(z);
     y = cimag(z);
     exp_x = __frexp_exp(x, &ex_expt);
     expt += ex_expt;
     /*
      * Arrange so that scale1 * scale2 == 2**expt.  We use this to
      * compensate for scalbn being horrendously slow.
      */
     half_expt = expt / 2;
     INSERT_WORDS(scale1, (0x3ff + half_expt) << 20, 0);
     half_expt = expt - half_expt;
     INSERT_WORDS(scale2, (0x3ff + half_expt) << 20, 0);
     return CMPLX(cos(y) * exp_x * scale1 * scale2, sin(y) * exp_x * scale1 * scale2);
 }
References __frexp_exp(), cimag, CMPLX, cos, creal, INSERT_WORDS, sin, x, and y.
Referenced by ccosh(), cexp(), and csinh().
__ldexp_cexpf()
hidden float complex __ldexp_cexpf (float complex, int expt)
Definition at line 51 of file __cexpf.c.
 {
     float x, y, exp_x, scale1, scale2;
     int ex_expt, half_expt;
     x = crealf(z);
     y = cimagf(z);
     exp_x = __frexp_expf(x, &ex_expt);
     expt += ex_expt;
     half_expt = expt / 2;
     SET_FLOAT_WORD(scale1, (0x7f + half_expt) << 23);
     half_expt = expt - half_expt;
     SET_FLOAT_WORD(scale2, (0x7f + half_expt) << 23);
     return CMPLXF(cosf(y) * exp_x * scale1 * scale2,
       sinf(y) * exp_x * scale1 * scale2);
 }
References __frexp_expf(), cimagf, CMPLXF, cosf(), crealf, SET_FLOAT_WORD, sinf(), x, and y.
Referenced by ccoshf(), cexpf(), and csinhf().