Fennix Userspace: Userspace/mlibc/options/lsb/generic/tls.cpp File Reference
tls.cpp File Reference
#include <internal-config.h>
#include <mlibc/thread.hpp>
#include <mlibc/rtdl-abi.hpp>
Functions
void * __tls_get_addr (struct __abi_tls_entry *entry)
Function Documentation
__tls_get_addr()
void* __tls_get_addr (struct __abi_tls_entry * entry)
Definition at line 15 of file tls.cpp.
{
         return __dlapi_get_tls(entry);
     }
References __dlapi_get_tls().
Referenced by dl_iterate_phdr(), do_dlsym(), and static_dl_iterate_phdr().