Fennix: Userspace/apps/base/bash/lib/readline/examples/excallback.c File Reference
excallback.c File Reference
#include <sys/types.h>
#include <stdlib.h>
#include <stdio.h>
#include <termios.h>
#include <locale.h>
#include <readline/readline.h>
Macros
#define STDIN_FILENO 0
Functions
void process_line (char *line)
int change_prompt (void)
char * get_prompt (void)
int main ()
Variables
int prompt = 1
char prompt_buf [40]
char line_buf [256]
tcflag_t old_lflag
cc_t old_vtime
struct termios term
Macro Definition Documentation
STDIN_FILENO
#define STDIN_FILENO 0
Definition at line 62 of file excallback.c.
Function Documentation
change_prompt()
int change_prompt (void)
Definition at line 173 of file excallback.c.
 {
   /* toggle the prompt variable */
   prompt = !prompt;
   /* save away the current contents of the line */
   strcpy(line_buf, rl_line_buffer);
   /* install a new handler which will change the prompt and erase the current line */
   rl_callback_handler_install(get_prompt(), process_line);
   /* insert the old text on the new line */
   rl_insert_text(line_buf);
   /* redraw the current line - this is an undocumented function. It invokes the
    * redraw-current-line command.
    */
   rl_refresh_line(0, 0);
 }
References get_prompt(), line_buf, process_line(), prompt, rl_callback_handler_install(), rl_insert_text(), rl_line_buffer, rl_refresh_line(), and strcpy.
Referenced by main().
get_prompt()
char * get_prompt (void)
Definition at line 194 of file excallback.c.
 {
   /* The prompts can even be different lengths! */
   sprintf(prompt_buf, "%s",
     prompt ? "Hit ctrl-t to toggle prompt> " : "Pretty cool huh?> ");
   return prompt_buf;
 }
References prompt, prompt_buf, and sprintf().
Referenced by change_prompt(), and main().
main()
int main (void)
Definition at line 105 of file excallback.c.
 {
     fd_set fds;
     setlocale (LC_ALL, "");
     /* Adjust the terminal slightly before the handler is installed. Disable
      * canonical mode processing and set the input character time flag to be
      * non-blocking.
      */
     if( tcgetattr(STDIN_FILENO, &term) < 0 ) {
         perror("tcgetattr");
         exit(1);
     }
     old_lflag = term.c_lflag;
     old_vtime = term.c_cc[VTIME];
     term.c_lflag &= ~ICANON;
     term.c_cc[VTIME] = 1;
     /* COMMENT LINE BELOW - see above */
     if( tcsetattr(STDIN_FILENO, TCSANOW, &term) < 0 ) {
         perror("tcsetattr");
         exit(1);
     }
     rl_add_defun("change-prompt", change_prompt, CTRL('t'));
     rl_callback_handler_install(get_prompt(), process_line);
     while(1) {
       FD_ZERO(&fds);
       FD_SET(fileno(stdin), &fds);
       if( select(FD_SETSIZE, &fds, NULL, NULL, NULL) < 0) {
         perror("select");
         exit(1);
       }
       if( FD_ISSET(fileno(stdin), &fds) ) {
         rl_callback_read_char();
       }
     }
 }
References termios::c_cc, termios::c_lflag, change_prompt(), CTRL, exit(), FD_ISSET, FD_SET, FD_SETSIZE, FD_ZERO, fileno(), get_prompt(), ICANON, LC_ALL, NULL, old_lflag, old_vtime, perror(), process_line(), rl_add_defun(), rl_callback_handler_install(), rl_callback_read_char(), select(), setlocale, stdin, STDIN_FILENO, tcgetattr(), TCSANOW, tcsetattr(), term, and VTIME.
process_line()
void process_line (char * line)
Definition at line 148 of file excallback.c.
 {
   if( line == NULL ) {
     fprintf(stderr, "\n", line);
     /* reset the old terminal setting before exiting */
     term.c_lflag     = old_lflag;
     term.c_cc[VTIME] = old_vtime;
     if( tcsetattr(STDIN_FILENO, TCSANOW, &term) < 0 ) {
         perror("tcsetattr");
         exit(1);
     }
     exit(0);
   }
   if( strcmp(line, "sleep") == 0 ) {
     sleep(3);
   } else {
     fprintf(stderr, "|%s|\n", line);
   }
   free (line);
 }
References termios::c_cc, termios::c_lflag, exit(), fprintf(), free, NULL, old_lflag, old_vtime, perror(), sleep(), stderr, STDIN_FILENO, strcmp, TCSANOW, tcsetattr(), term, and VTIME.
Referenced by change_prompt(), and main().
Variable Documentation
line_buf
char line_buf[256]
Definition at line 99 of file excallback.c.
Referenced by change_prompt().
old_lflag
tcflag_t old_lflag
Definition at line 100 of file excallback.c.
Referenced by main(), and process_line().
old_vtime
cc_t old_vtime
Definition at line 101 of file excallback.c.
Referenced by main(), and process_line().
prompt
int prompt = 1
Definition at line 98 of file excallback.c.
Referenced by change_prompt(), and get_prompt().
prompt_buf
char prompt_buf[40]
Definition at line 99 of file excallback.c.
Referenced by get_prompt().
term
struct termios term
Definition at line 101 of file excallback.c.
Referenced by _rl_init_terminal_io(), do_rd(), is_TERM_dumb(), legal_pathopt(), main(), padvance_magic(), process_line(), setup_environment(), tgetent(), and vlock_main().