Fennix: Userspace/mlibc/options/ansi/generic/fenv-stubs.cpp File Reference
fenv-stubs.cpp File Reference
#include <bits/ensure.h>
#include <fenv.h>
Functions
int feclearexcept (int)
int fegetenv (fenv_t *)
int fegetexceptflag (fexcept_t *, int)
int fegetround (void)
int feholdexcept (fenv_t *)
int feraiseexcept (int)
int fesetenv (const fenv_t *)
int fesetexceptflag (const fexcept_t *, int)
int fesetround (int)
int fetestexcept (int)
int feupdateenv (const fenv_t *)
Function Documentation
feclearexcept()
int feclearexcept (int)
Definition at line 5 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by feholdexcept(), fesetexceptflag(), fmaf(), nearbyint(), nearbyintf(), and nearbyintl().
fegetenv()
int fegetenv (fenv_t *)
Definition at line 10 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by feholdexcept().
fegetexceptflag()
int fegetexceptflag (fexcept_t * , int)
Definition at line 15 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fegetround()
int fegetround (void)
Definition at line 20 of file fenv-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by __flt_rounds(), and fmaf().
feholdexcept()
int feholdexcept (fenv_t *)
Definition at line 25 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
feraiseexcept()
int feraiseexcept (int)
Definition at line 30 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by fesetexceptflag(), feupdateenv(), and fmaf().
fesetenv()
int fesetenv (const fenv_t *)
Definition at line 35 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by feupdateenv().
fesetexceptflag()
int fesetexceptflag (const fexcept_t * , int)
Definition at line 40 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
fesetround()
int fesetround (int)
Definition at line 45 of file fenv-stubs.cpp.
                     {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by fmaf().
fetestexcept()
int fetestexcept (int)
Definition at line 50 of file fenv-stubs.cpp.
                       {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
Referenced by fegetexceptflag(), feupdateenv(), fmaf(), nearbyint(), nearbyintf(), and nearbyintl().
feupdateenv()
int feupdateenv (const fenv_t *)
Definition at line 55 of file fenv-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.