Fennix: Userspace/apps/base/bash/shell.c File Reference
shell.c File Reference
#include "config.h"
#include "bashtypes.h"
#include "posixstat.h"
#include "posixtime.h"
#include "bashansi.h"
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include "filecntl.h"
#include "bashintl.h"
#include "shell.h"
#include "parser.h"
#include "flags.h"
#include "trap.h"
#include "mailcheck.h"
#include "builtins.h"
#include "builtins/common.h"
#include "input.h"
#include "execute_cmd.h"
#include "findcmd.h"
#include <tilde/tilde.h>
#include <glob/strmatch.h>
Macros
#define INSTALL_DEBUG_MODE
#define NEED_SH_SETLINEBUF_DECL /* used in externs.h */
#define Int 1
#define Charp 2
#define PROGRAM "bash"
Functions
int initialize_job_control PARAMS ((int))
int get_tty_state PARAMS ((void))
struct passwd * getpwuid ()
static int parse_long_options PARAMS ((char **, int, int))
static int bind_args PARAMS ((char **, int, int, int))
static void add_shopt_to_alist PARAMS ((char *, int))
static void execute_env_file PARAMS ((char *))
static void show_shell_usage PARAMS ((FILE *, int))
int main (int argc, char **argv, char **env)
static int parse_long_options (char **argv, int arg_start, int arg_end)
static int parse_shell_options (char **argv, int arg_start, int arg_end)
void exit_shell (int s)
void sh_exit (int s)
void subshell_exit (int s)
void set_exit_status (int s)
static void execute_env_file (char *env_file)
static void run_startup_files ()
static int uidget ()
void disable_priv_mode ()
static int bind_args (char **argv, int arg_start, int arg_end, int start_index)
void unbind_args ()
static void start_debugger ()
static int open_shell_script (char *script_name)
static void set_bash_input ()
void unset_bash_input (int check_zero)
static void set_shell_name (char *argv0)
static void set_option_defaults ()
static void reset_option_defaults ()
static void init_interactive ()
static void init_noninteractive ()
static void init_interactive_script ()
void get_current_user_info ()
static void shell_initialize ()
static void shell_reinitialize ()
static void show_shell_usage (FILE *fp, int extra)
static void add_shopt_to_alist (char *opt, int on_or_off)
static void run_shopt_alist ()
Variables
int running_in_background
int errno
int gnu_error_format
int shell_initialized = 0
int bash_argv_initialized = 0
COMMAND * global_command = (COMMAND *)NULL
struct user_info current_user
char * current_host_name = (char *)NULL
int login_shell = 0
int interactive = 0
int interactive_shell = 0
int hup_on_exit = 0
int check_jobs_at_exit = 0
int autocd = 0
int startup_state = 0
int reading_shell_script = 0
int debugging_login_shell = 0
char ** shell_environment
int executing = 0
int current_command_number = 1
int indirection_level = 0
char * shell_name = (char *)NULL
time_t shell_start_time
struct timeval shellstart
int running_under_emacs
int have_devfd = 0
static char * bashrc_file = DEFAULT_BASHRC
static int act_like_sh
static int su_shell
static int sourced_env
static int running_setuid
static int debugging
static int no_rc
static int no_profile
static int do_version
static int make_login_shell
static int want_initial_help
int debugging_mode = 0
int no_line_editing = 1
int wordexp_only = 0
int protected_mode = 0
int pretty_print_mode = 0
int posixly_correct = 0
struct {
const char * name
int type
int * int_value
char ** char_value
} long_args []
procenv_t subshell_top_level
int subshell_argc
char ** subshell_argv
char ** subshell_envp
char * exec_argv0
int read_from_stdin
int want_pending_command
char * command_execution_string
char * shell_script_filename
int malloc_trace_at_exit = 0
static int shell_reinitialized = 0
static FILE * default_input
static STRING_INT_ALIST * shopt_alist
static int shopt_ind = 0
static int shopt_len = 0
Macro Definition Documentation
Charp
#define Charp 2
Definition at line 242 of file shell.c.
INSTALL_DEBUG_MODE
#define INSTALL_DEBUG_MODE
Definition at line 26 of file shell.c.
Int
#define Int 1
Definition at line 241 of file shell.c.
NEED_SH_SETLINEBUF_DECL
#define NEED_SH_SETLINEBUF_DECL /* used in externs.h */
Definition at line 51 of file shell.c.
PROGRAM
#define PROGRAM "bash"
Definition at line 1789 of file shell.c.
Function Documentation
add_shopt_to_alist()
static void add_shopt_to_alist (char * opt, int on_or_off) static
Definition at line 2111 of file shell.c.
 {
   if (shopt_ind >= shopt_len)
     {
       shopt_len += 8;
       shopt_alist = (STRING_INT_ALIST *)xrealloc (shopt_alist, shopt_len * sizeof (shopt_alist[0]));
     }
   shopt_alist[shopt_ind].word = opt;
   shopt_alist[shopt_ind].token = on_or_off;
   shopt_ind++;
 }
References shopt_alist, shopt_ind, shopt_len, STRING_INT_ALIST::token, STRING_INT_ALIST::word, and xrealloc.
Referenced by parse_shell_options().
bind_args()
static int bind_args (char ** argv, int arg_start, int arg_end, int start_index) static
Definition at line 1478 of file shell.c.
 {
   register int i;
   WORD_LIST *args, *tl;
   for (i = arg_start, args = tl = (WORD_LIST *)NULL; i < arg_end; i++)
     {
       if (args == 0)
     args = tl = make_word_list (make_word (argv[i]), args);
       else
     {
       tl->next = make_word_list (make_word (argv[i]), (WORD_LIST *)NULL);
       tl = tl->next;
     }
     }
   if (args)
     {
       if (start_index == 0) /* bind to $0...$n for sh -c command */
     {
       /* Posix.2 4.56.3 says that the first argument after sh -c command
          becomes $0, and the rest of the arguments become $1...$n */
       shell_name = savestring (args->word->word);
       FREE (dollar_vars[0]);
       dollar_vars[0] = savestring (args->word->word);
       remember_args (args->next, 1);
       if (debugging_mode)
         {
           push_args (args->next);   /* BASH_ARGV and BASH_ARGC */
           bash_argv_initialized = 1;
         }
     }
       else          /* bind to $1...$n for shell script */
         {
       remember_args (args, 1);
       /* We do this unconditionally so something like -O extdebug doesn't
          do it first.  We're setting the definitive positional params
          here. */
       if (debugging_mode)
         {
           push_args (args);     /* BASH_ARGV and BASH_ARGC */
           bash_argv_initialized = 1;
         }
         }
       dispose_words (args);
     }
   return (i);
 }
References args, argv, bash_argv_initialized, debugging_mode, dispose_words(), dollar_vars, FREE, i, make_word(), make_word_list(), word_list::next, NULL, push_args(), remember_args(), savestring(), and shell_name.
Referenced by main().
disable_priv_mode()
void disable_priv_mode ()
Definition at line 1339 of file shell.c.
 {
   int e;
 #if HAVE_SETRESUID
   if (setresuid (current_user.uid, current_user.uid, current_user.uid) < 0)
 #else
   if (setuid (current_user.uid) < 0)
 #endif
     {
       e = errno;
       sys_error (_("cannot set uid to %d: effective uid %d"), current_user.uid, current_user.euid);
 #if defined (EXIT_ON_SETUID_FAILURE)
       if (e == EAGAIN)
     exit (e);
 #endif
     }
 #if HAVE_SETRESGID
   if (setresgid (current_user.gid, current_user.gid, current_user.gid) < 0)
 #else
   if (setgid (current_user.gid) < 0)
 #endif
     sys_error (_("cannot set gid to %d: effective gid %d"), current_user.gid, current_user.egid);
   current_user.euid = current_user.uid;
   current_user.egid = current_user.gid;
 }
References _, current_user, EAGAIN, user_info::egid, errno, user_info::euid, exit(), user_info::gid, setgid(), setresgid(), setresuid(), setuid(), sys_error(), and user_info::uid.
Referenced by change_flag(), and main().
execute_env_file()
static void execute_env_file (char * env_file) static
Definition at line 1109 of file shell.c.
 {
   char *fn;
   if (env_file && *env_file)
     {
       fn = expand_string_unsplit_to_string (env_file, Q_DOUBLE_QUOTES);
       if (fn && *fn)
     maybe_execute_file (fn, 1);
       FREE (fn);
     }
 }
References expand_string_unsplit_to_string(), FREE, maybe_execute_file(), and Q_DOUBLE_QUOTES.
Referenced by run_startup_files().
exit_shell()
void exit_shell (int s)
Definition at line 988 of file shell.c.
 {
   fflush (stdout);      /* XXX */
   fflush (stderr);
   /* Clean up the terminal if we are in a state where it's been modified. */
 #if defined (READLINE)
   if (RL_ISSTATE (RL_STATE_TERMPREPPED) && rl_deprep_term_function)
     (*rl_deprep_term_function) ();
 #endif
   if (read_tty_modified ())
     read_tty_cleanup ();
   /* Do trap[0] if defined.  Allow it to override the exit status
      passed to us. */
   if (signal_is_trapped (0))
     s = run_exit_trap ();
 #if defined (PROCESS_SUBSTITUTION)
   unlink_all_fifos ();
 #endif /* PROCESS_SUBSTITUTION */
 #if defined (HISTORY)
   if (remember_on_history)
     maybe_save_shell_history ();
 #endif /* HISTORY */
 #if defined (COPROCESS_SUPPORT)
   coproc_flush ();
 #endif
 #if defined (JOB_CONTROL)
   /* If the user has run `shopt -s huponexit', hangup all jobs when we exit
      an interactive login shell.  ksh does this unconditionally. */
   if (interactive_shell && login_shell && hup_on_exit)
     hangup_all_jobs ();
   /* If this shell is interactive, or job control is active, terminate all
      stopped jobs and restore the original terminal process group.  Don't do
      this if we're in a subshell and calling exit_shell after, for example,
      a failed word expansion.  We want to do this even if the shell is not
      interactive because we set the terminal's process group when job control
      is enabled regardless of the interactive status. */
   if (subshell_environment == 0)
     end_job_control ();
 #endif /* JOB_CONTROL */
   /* Always return the exit status of the last command to our parent. */
   sh_exit (s);
 }
References end_job_control(), fflush(), hangup_all_jobs(), hup_on_exit, interactive_shell, login_shell, remember_on_history, rl_deprep_term_function, RL_ISSTATE, RL_STATE_TERMPREPPED, run_exit_trap(), sh_exit(), signal_is_trapped(), stderr, stdout, and subshell_environment.
Referenced by main(), parser_error(), push_builtin(), push_heredoc(), and report_error().
get_current_user_info()
void get_current_user_info ()
Definition at line 1892 of file shell.c.
 {
   struct passwd *entry;
   /* Don't fetch this more than once. */
   if (current_user.user_name == 0)
     {
 #if defined (__TANDEM)
       entry = getpwnam (getlogin ());
 #else
       entry = getpwuid (current_user.uid);
 #endif
       if (entry)
     {
       current_user.user_name = savestring (entry->pw_name);
       current_user.shell = (entry->pw_shell && entry->pw_shell[0])
                 ? savestring (entry->pw_shell)
                 : savestring ("/bin/sh");
       current_user.home_dir = savestring (entry->pw_dir);
     }
       else
     {
       current_user.user_name = _("I have no name!");
       current_user.user_name = savestring (current_user.user_name);
       current_user.shell = savestring ("/bin/sh");
       current_user.home_dir = savestring ("/");
     }
 #if defined (HAVE_GETPWENT)
       endpwent ();
 #endif
     }
 }
References _, current_user, endpwent(), getlogin(), getpwnam(), getpwuid(), user_info::home_dir, savestring(), user_info::shell, user_info::uid, and user_info::user_name.
Referenced by decode_prompt_string(), get_bash_name(), initialize_shell_variables(), make_default_mailpath(), set_shell_var(), sh_get_home_dir(), shell_initialize(), and whoami_builtin().
getpwuid()
struct passwd* getpwuid ()
init_interactive()
static void init_interactive () static
Definition at line 1845 of file shell.c.
 {
   expand_aliases = expaliases_flag = 1;
   interactive_shell = startup_state = interactive = 1;
 #if defined (HISTORY)
   if (enable_history_list == -1)
     enable_history_list = 1;                /* set default  */
   remember_on_history = enable_history_list;
 #  if defined (BANG_HISTORY)
   histexp_flag = history_expansion;         /* XXX */
 #  endif
 #endif
 }
References enable_history_list, expaliases_flag, expand_aliases, history_expansion, interactive, interactive_shell, remember_on_history, and startup_state.
Referenced by main().
init_interactive_script()
static void init_interactive_script () static
Definition at line 1878 of file shell.c.
 {
 #if defined (HISTORY)
   if (enable_history_list == -1)
     enable_history_list = 1;
 #endif
   init_noninteractive ();
   expand_aliases = expaliases_flag = interactive_shell = startup_state = 1;
 #if defined (HISTORY)
   remember_on_history = enable_history_list;    /* XXX */
 #endif
 }
References enable_history_list, expaliases_flag, expand_aliases, init_noninteractive(), interactive_shell, remember_on_history, and startup_state.
Referenced by open_shell_script().
init_noninteractive()
static void init_noninteractive () static
Definition at line 1860 of file shell.c.
 {
 #if defined (HISTORY)
   if (enable_history_list == -1)            /* set default */
     enable_history_list = 0;
   bash_history_reinit (0);
 #endif /* HISTORY */
   interactive_shell = startup_state = interactive = 0;
   expand_aliases = expaliases_flag = posixly_correct;   /* XXX - was 0 not posixly_correct */
   no_line_editing = 1;
 #if defined (JOB_CONTROL)
   /* Even if the shell is not interactive, enable job control if the -i or
      -m option is supplied at startup. */
   set_job_control (forced_interactive||jobs_m_flag);
 #endif /* JOB_CONTROL */
 }
References enable_history_list, expaliases_flag, expand_aliases, forced_interactive, interactive, interactive_shell, jobs_m_flag, no_line_editing, posixly_correct, set_job_control(), and startup_state.
Referenced by init_interactive_script(), and main().
main()
int main (int argc, char ** argv, char ** env)
Definition at line 370 of file shell.c.
 {
   register int i;
   int code, old_errexit_flag;
 #if defined (RESTRICTED_SHELL)
   int saverst;
 #endif
   volatile int locally_skip_execution;
   volatile int arg_index, top_level_arg_index;
 #ifdef __OPENNT
   char **env;
   env = environ;
 #endif /* __OPENNT */
   USE_VAR(argc);
   USE_VAR(argv);
   USE_VAR(env);
   USE_VAR(code);
   USE_VAR(old_errexit_flag);
 #if defined (RESTRICTED_SHELL)
   USE_VAR(saverst);
 #endif
   /* Catch early SIGINTs. */
   code = setjmp_nosigs (top_level);
   if (code)
     exit (2);
   xtrace_init ();
 #if defined (USING_BASH_MALLOC) && defined (DEBUG) && !defined (DISABLE_MALLOC_WRAPPERS)
   malloc_set_register (1);  /* XXX - change to 1 for malloc debugging */
 #endif
   check_dev_tty ();
 #ifdef __CYGWIN__
   _cygwin32_check_tmp ();
 #endif /* __CYGWIN__ */
   /* Wait forever if we are debugging a login shell. */
   while (debugging_login_shell) sleep (3);
   set_default_locale ();
   running_setuid = uidget ();
   if (getenv ("POSIXLY_CORRECT") || getenv ("POSIX_PEDANTIC"))
     posixly_correct = 1;
 #if defined (USE_GNU_MALLOC_LIBRARY)
   mcheck (programming_error, (void (*) ())0);
 #endif /* USE_GNU_MALLOC_LIBRARY */
   if (setjmp_sigs (subshell_top_level))
     {
       argc = subshell_argc;
       argv = subshell_argv;
       env = subshell_envp;
       sourced_env = 0;
     }
   shell_reinitialized = 0;
   /* Initialize `local' variables for all `invocations' of main (). */
   arg_index = 1;
   if (arg_index > argc)
     arg_index = argc;
   command_execution_string = shell_script_filename = (char *)NULL;
   want_pending_command = locally_skip_execution = read_from_stdin = 0;
   default_input = stdin;
 #if defined (BUFFERED_INPUT)
   default_buffered_input = -1;
 #endif
   /* Fix for the `infinite process creation' bug when running shell scripts
      from startup files on System V. */
   login_shell = make_login_shell = 0;
   /* If this shell has already been run, then reinitialize it to a
      vanilla state. */
   if (shell_initialized || shell_name)
     {
       /* Make sure that we do not infinitely recurse as a login shell. */
       if (*shell_name == '-')
     shell_name++;
       shell_reinitialize ();
       if (setjmp_nosigs (top_level))
     exit (2);
     }
   shell_environment = env;
   set_shell_name (argv[0]);
   gettimeofday (&shellstart, 0);
   shell_start_time = shellstart.tv_sec;
   /* Parse argument flags from the input line. */
   /* Find full word arguments first. */
   arg_index = parse_long_options (argv, arg_index, argc);
   if (want_initial_help)
     {
       show_shell_usage (stdout, 1);
       exit (EXECUTION_SUCCESS);
     }
   if (do_version)
     {
       show_shell_version (1);
       exit (EXECUTION_SUCCESS);
     }
   echo_input_at_read = verbose_flag;    /* --verbose given */
   /* All done with full word options; do standard shell option parsing.*/
   this_command_name = shell_name;   /* for error reporting */
   arg_index = parse_shell_options (argv, arg_index, argc);
   /* If user supplied the "--login" (or -l) flag, then set and invert
      LOGIN_SHELL. */
   if (make_login_shell)
     {
       login_shell++;
       login_shell = -login_shell;
     }
   set_login_shell ("login_shell", login_shell != 0);
 #if defined (TRANSLATABLE_STRINGS)
   if (dump_po_strings)
     dump_translatable_strings = 1;
   if (dump_translatable_strings)
     read_but_dont_execute = 1;
 #endif
   if (running_setuid && privileged_mode == 0)
     disable_priv_mode ();
   /* Need to get the argument to a -c option processed in the
      above loop.  The next arg is a command to execute, and the
      following args are $0...$n respectively. */
   if (want_pending_command)
     {
       command_execution_string = argv[arg_index];
       if (command_execution_string == 0)
     {
       report_error (_("%s: option requires an argument"), "-c");
       exit (EX_BADUSAGE);
     }
       arg_index++;
     }
   this_command_name = (char *)NULL;
   /* First, let the outside world know about our interactive status.
      A shell is interactive if the `-i' flag was given, or if all of
      the following conditions are met:
     no -c command
     no arguments remaining or the -s flag given
     standard input is a terminal
     standard error is a terminal
      Refer to Posix.2, the description of the `sh' utility. */
   if (forced_interactive ||     /* -i flag */
       (!command_execution_string && /* No -c command and ... */
        wordexp_only == 0 &&     /* No --wordexp and ... */
        ((arg_index == argc) ||      /*   no remaining args or... */
     read_from_stdin) &&     /*   -s flag with args, and */
        isatty (fileno (stdin)) &&   /* Input is a terminal and */
        isatty (fileno (stderr))))   /* error output is a terminal. */
     init_interactive ();
   else
     init_noninteractive ();
   /*
    * Some systems have the bad habit of starting login shells with lots of open
    * file descriptors.  For instance, most systems that have picked up the
    * pre-4.0 Sun YP code leave a file descriptor open each time you call one
    * of the getpw* functions, and it's set to be open across execs.  That
    * means one for login, one for xterm, one for shelltool, etc.  There are
    * also systems that open persistent FDs to other agents or files as part
    * of process startup; these need to be set to be close-on-exec.
    */
   if (login_shell && interactive_shell)
     {
       for (i = 3; i < 20; i++)
     SET_CLOSE_ON_EXEC (i);
     }
   /* If we're in a strict Posix.2 mode, turn on interactive comments,
      alias expansion in non-interactive shells, and other Posix.2 things. */
   if (posixly_correct)
     {
       bind_variable ("POSIXLY_CORRECT", "y", 0);
       sv_strict_posix ("POSIXLY_CORRECT");
     }
   /* Now we run the shopt_alist and process the options. */
   if (shopt_alist)
     run_shopt_alist ();
   /* From here on in, the shell must be a normal functioning shell.
      Variables from the environment are expected to be set, etc. */
   shell_initialize ();
   set_default_lang ();
   set_default_locale_vars ();
   /*
    * M-x term -> TERM=eterm-color INSIDE_EMACS='251,term:0.96' (eterm)
    * M-x shell -> TERM='dumb' INSIDE_EMACS='25.1,comint' (no line editing)
    *
    * Older versions of Emacs may set EMACS to 't' or to something like
    * '22.1 (term:0.96)' instead of (or in addition to) setting INSIDE_EMACS.
    * They may set TERM to 'eterm' instead of 'eterm-color'.  They may have
    * a now-obsolete command that sets neither EMACS nor INSIDE_EMACS:
    * M-x terminal -> TERM='emacs-em7955' (line editing)
    */
   if (interactive_shell)
     {
       char *term, *emacs, *inside_emacs;
       int emacs_term, in_emacs;
       term = get_string_value ("TERM");
       emacs = get_string_value ("EMACS");
       inside_emacs = get_string_value ("INSIDE_EMACS");
       if (inside_emacs)
     {
       emacs_term = strstr (inside_emacs, ",term:") != 0;
       in_emacs = 1;
     }
       else if (emacs)
     {
       /* Infer whether we are in an older Emacs. */
       emacs_term = strstr (emacs, " (term:") != 0;
       in_emacs = emacs_term || STREQ (emacs, "t");
     }
       else
     in_emacs = emacs_term = 0;
       /* Not sure any emacs terminal emulator sets TERM=emacs any more */
       no_line_editing |= STREQ (term, "emacs");
       no_line_editing |= in_emacs && STREQ (term, "dumb");
       /* running_under_emacs == 2 for `eterm' */
       running_under_emacs = in_emacs || STREQN (term, "emacs", 5);
       running_under_emacs += emacs_term && STREQN (term, "eterm", 5);
       if (running_under_emacs)
     gnu_error_format = 1;
     }
   top_level_arg_index = arg_index;
   old_errexit_flag = exit_immediately_on_error;
   /* Give this shell a place to longjmp to before executing the
      startup files.  This allows users to press C-c to abort the
      lengthy startup. */
   code = setjmp_sigs (top_level);
   if (code)
     {
       if (code == EXITPROG || code == ERREXIT || code == EXITBLTIN)
     exit_shell (last_command_exit_value);
       else
     {
 #if defined (JOB_CONTROL)
       /* Reset job control, since run_startup_files turned it off. */
       set_job_control (interactive_shell);
 #endif
       /* Reset value of `set -e', since it's turned off before running
          the startup files. */
       exit_immediately_on_error += old_errexit_flag;
       locally_skip_execution++;
     }
     }
   arg_index = top_level_arg_index;
   /* Execute the start-up scripts. */
   if (interactive_shell == 0)
     {
       unbind_variable ("PS1");
       unbind_variable ("PS2");
       interactive = 0;
 #if 0
       /* This has already been done by init_noninteractive */
       expand_aliases = posixly_correct;
 #endif
     }
   else
     {
       change_flag ('i', FLAG_ON);
       interactive = 1;
     }
 #if defined (RESTRICTED_SHELL)
   /* Set restricted_shell based on whether the basename of $0 indicates that
      the shell should be restricted or if the `-r' option was supplied at
      startup. */
   restricted_shell = shell_is_restricted (shell_name);
   /* If the `-r' option is supplied at invocation, make sure that the shell
      is not in restricted mode when running the startup files. */
   saverst = restricted;
   restricted = 0;
 #endif
   /* Set positional parameters before running startup files. top_level_arg_index
      holds the index of the current argument before setting the positional
      parameters, so any changes performed in the startup files won't affect
      later option processing. */
   if (wordexp_only)
     ;           /* nothing yet */
   else if (command_execution_string)
     arg_index = bind_args (argv, arg_index, argc, 0);   /* $0 ... $n */
   else if (arg_index != argc && read_from_stdin == 0)
     {
       shell_script_filename = argv[arg_index++];
       arg_index = bind_args (argv, arg_index, argc, 1); /* $1 ... $n */
     }
   else
     arg_index = bind_args (argv, arg_index, argc, 1);   /* $1 ... $n */
   /* The startup files are run with `set -e' temporarily disabled. */
   if (locally_skip_execution == 0 && running_setuid == 0)
     {
       char *t;
       old_errexit_flag = exit_immediately_on_error;
       exit_immediately_on_error = 0;
       /* Temporarily set $0 while running startup files, then restore it so
      we get better error messages when trying to open script files. */
       if (shell_script_filename)
     {
       t = dollar_vars[0];
       dollar_vars[0] = exec_argv0 ? savestring (exec_argv0) : savestring (shell_script_filename);
     }
       run_startup_files ();
       if (shell_script_filename)
     {
       free (dollar_vars[0]);
       dollar_vars[0] = t;
     }
       exit_immediately_on_error += old_errexit_flag;
     }
   /* If we are invoked as `sh', turn on Posix mode. */
   if (act_like_sh)
     {
       bind_variable ("POSIXLY_CORRECT", "y", 0);
       sv_strict_posix ("POSIXLY_CORRECT");
     }
 #if defined (RESTRICTED_SHELL)
   /* Turn on the restrictions after executing the startup files.  This
      means that `bash -r' or `set -r' invoked from a startup file will
      turn on the restrictions after the startup files are executed. */
   restricted = saverst || restricted;
   if (shell_reinitialized == 0)
     maybe_make_restricted (shell_name);
 #endif /* RESTRICTED_SHELL */
 #if defined (WORDEXP_OPTION)
   if (wordexp_only)
     {
       startup_state = 3;
       last_command_exit_value = run_wordexp (argv[top_level_arg_index]);
       exit_shell (last_command_exit_value);
     }
 #endif
   cmd_init ();      /* initialize the command object caches */
   uwp_init ();
   if (command_execution_string)
     {
       startup_state = 2;
       if (debugging_mode)
     start_debugger ();
 #if defined (ONESHOT)
       executing = 1;
       run_one_command (command_execution_string);
       exit_shell (last_command_exit_value);
 #else /* ONESHOT */
       with_input_from_string (command_execution_string, "-c");
       goto read_and_execute;
 #endif /* !ONESHOT */
     }
   /* Get possible input filename and set up default_buffered_input or
      default_input as appropriate. */
   if (shell_script_filename)
     open_shell_script (shell_script_filename);
   else if (interactive == 0)
     {
       /* In this mode, bash is reading a script from stdin, which is a
      pipe or redirected file. */
 #if defined (BUFFERED_INPUT)
       default_buffered_input = fileno (stdin);  /* == 0 */
 #else
       setbuf (default_input, (char *)NULL);
 #endif /* !BUFFERED_INPUT */
       read_from_stdin = 1;
     }
   else if (top_level_arg_index == argc)     /* arg index before startup files */
     /* "If there are no operands and the -c option is not specified, the -s
        option shall be assumed." */
     read_from_stdin = 1;
   set_bash_input ();
   if (debugging_mode && locally_skip_execution == 0 && running_setuid == 0 && (reading_shell_script || interactive_shell == 0))
     start_debugger ();
   /* Do the things that should be done only for interactive shells. */
   if (interactive_shell)
     {
       /* Set up for checking for presence of mail. */
       reset_mail_timer ();
       init_mail_dates ();
 #if defined (HISTORY)
       /* Initialize the interactive history stuff. */
       bash_initialize_history ();
       /* Don't load the history from the history file if we've already
      saved some lines in this session (e.g., by putting `history -s xx'
      into one of the startup files). */
       if (shell_initialized == 0 && history_lines_this_session == 0)
     load_history ();
 #endif /* HISTORY */
       /* Initialize terminal state for interactive shells after the
      .bash_profile and .bashrc are interpreted. */
       get_tty_state ();
     }
 #if !defined (ONESHOT)
  read_and_execute:
 #endif /* !ONESHOT */
   shell_initialized = 1;
   if (pretty_print_mode && interactive_shell)
     {
       internal_warning (_("pretty-printing mode ignored in interactive shells"));
       pretty_print_mode = 0;
     }
   if (pretty_print_mode)
     exit_shell (pretty_print_loop ());
   /* Read commands until exit condition. */
   reader_loop ();
   exit_shell (last_command_exit_value);
 }
References _, act_like_sh, argc, argv, bind_args(), bind_variable(), change_flag(), check_dev_tty(), cmd_init(), command_execution_string, debugging_login_shell, debugging_mode, default_input, disable_priv_mode(), do_version, dollar_vars, dump_po_strings, dump_translatable_strings, echo_input_at_read, env, environ, ERREXIT, EX_BADUSAGE, exec_argv0, executing, EXECUTION_SUCCESS, exit(), exit_immediately_on_error, exit_shell(), EXITBLTIN, EXITPROG, expand_aliases, fileno(), FLAG_ON, forced_interactive, free, get_string_value(), get_tty_state(), getenv, gettimeofday(), gnu_error_format, history_lines_this_session, i, init_interactive(), init_mail_dates(), init_noninteractive(), interactive, interactive_shell, internal_warning(), isatty(), last_command_exit_value, login_shell, make_login_shell, malloc_set_register(), no_line_editing, NULL, open_shell_script(), parse_long_options(), parse_shell_options(), posixly_correct, pretty_print_loop(), pretty_print_mode, privileged_mode, programming_error(), read_but_dont_execute, read_from_stdin, reader_loop(), reading_shell_script, report_error(), reset_mail_timer(), run_shopt_alist(), run_startup_files(), running_setuid, running_under_emacs, savestring(), set_bash_input(), SET_CLOSE_ON_EXEC, set_default_lang(), set_default_locale(), set_default_locale_vars(), set_job_control(), set_shell_name(), setbuf(), setjmp_nosigs, setjmp_sigs, shell_environment, shell_initialize(), shell_initialized, shell_name, shell_reinitialize(), shell_reinitialized, shell_script_filename, shell_start_time, shellstart, shopt_alist, show_shell_usage(), show_shell_version(), sleep(), sourced_env, start_debugger(), startup_state, stderr, stdin, stdout, STREQ, STREQN, strstr(), subshell_argc, subshell_argv, subshell_envp, subshell_top_level, sv_strict_posix(), t, term, this_command_name, top_level, timeval::tv_sec, uidget(), unbind_variable(), USE_VAR, uwp_init(), verbose_flag, want_initial_help, want_pending_command, with_input_from_string(), wordexp_only, and xtrace_init().
open_shell_script()
static int open_shell_script (char * script_name) static
Definition at line 1564 of file shell.c.
 {
   int fd, e, fd_is_tty;
   char *filename, *path_filename, *t;
   char sample[80];
   int sample_len;
   struct stat sb;
 #if defined (ARRAY_VARS)
   SHELL_VAR *funcname_v, *bash_source_v, *bash_lineno_v;
   ARRAY *funcname_a, *bash_source_a, *bash_lineno_a;
 #endif
   filename = savestring (script_name);
   fd = open (filename, O_RDONLY);
   if ((fd < 0) && (errno == ENOENT) && (absolute_program (filename) == 0))
     {
       e = errno;
       /* If it's not in the current directory, try looking through PATH
      for it. */
       path_filename = find_path_file (script_name);
       if (path_filename)
     {
       free (filename);
       filename = path_filename;
       fd = open (filename, O_RDONLY);
     }
       else
     errno = e;
     }
   if (fd < 0)
     {
       e = errno;
       file_error (filename);
 #if defined (JOB_CONTROL)
       end_job_control ();   /* just in case we were run as bash -i script */
 #endif
       sh_exit ((e == ENOENT) ? EX_NOTFOUND : EX_NOINPUT);
     }
   free (dollar_vars[0]);
   dollar_vars[0] = exec_argv0 ? savestring (exec_argv0) : savestring (script_name);
   if (exec_argv0)
     {
       free (exec_argv0);
       exec_argv0 = (char *)NULL;
     }
   if (file_isdir (filename))
     {
 #if defined (EISDIR)
       errno = EISDIR;
 #else
       errno = EINVAL;
 #endif
       file_error (filename);
 #if defined (JOB_CONTROL)
       end_job_control ();   /* just in case we were run as bash -i script */
 #endif
       sh_exit (EX_NOINPUT);
     }
 #if defined (ARRAY_VARS)
   GET_ARRAY_FROM_VAR ("FUNCNAME", funcname_v, funcname_a);
   GET_ARRAY_FROM_VAR ("BASH_SOURCE", bash_source_v, bash_source_a);
   GET_ARRAY_FROM_VAR ("BASH_LINENO", bash_lineno_v, bash_lineno_a);
   array_push (bash_source_a, filename);
   if (bash_lineno_a)
     {
       t = itos (executing_line_number ());
       array_push (bash_lineno_a, t);
       free (t);
     }
   array_push (funcname_a, "main");
 #endif
 #ifdef HAVE_DEV_FD
   fd_is_tty = isatty (fd);
 #else
   fd_is_tty = 0;
 #endif
   /* Only do this with non-tty file descriptors we can seek on. */
   if (fd_is_tty == 0 && (lseek (fd, 0L, 1) != -1))
     {
       /* Check to see if the `file' in `bash file' is a binary file
      according to the same tests done by execute_simple_command (),
      and report an error and exit if it is. */
       sample_len = read (fd, sample, sizeof (sample));
       if (sample_len < 0)
     {
       e = errno;
       if ((fstat (fd, &sb) == 0) && S_ISDIR (sb.st_mode))
         {
 #if defined (EISDIR)
           errno = EISDIR;
           file_error (filename);
 #else
           internal_error (_("%s: Is a directory"), filename);
 #endif
         }
       else
         {
           errno = e;
           file_error (filename);
         }
 #if defined (JOB_CONTROL)
       end_job_control ();   /* just in case we were run as bash -i script */
 #endif
       exit (EX_NOEXEC);
     }
       else if (sample_len > 0 && (check_binary_file (sample, sample_len)))
     {
       internal_error (_("%s: cannot execute binary file"), filename);
 #if defined (JOB_CONTROL)
       end_job_control ();   /* just in case we were run as bash -i script */
 #endif
       exit (EX_BINARY_FILE);
     }
       /* Now rewind the file back to the beginning. */
       lseek (fd, 0L, 0);
     }
   /* Open the script.  But try to move the file descriptor to a randomly
      large one, in the hopes that any descriptors used by the script will
      not match with ours. */
   fd = move_to_high_fd (fd, 1, -1);
 #if defined (BUFFERED_INPUT)
   default_buffered_input = fd;
   SET_CLOSE_ON_EXEC (default_buffered_input);
 #else /* !BUFFERED_INPUT */
   default_input = fdopen (fd, "r");
   if (default_input == 0)
     {
       file_error (filename);
       exit (EX_NOTFOUND);
     }
   SET_CLOSE_ON_EXEC (fd);
   if (fileno (default_input) != fd)
     SET_CLOSE_ON_EXEC (fileno (default_input));
 #endif /* !BUFFERED_INPUT */
   /* Just about the only way for this code to be executed is if something
      like `bash -i /dev/stdin' is executed. */
   if (interactive_shell && fd_is_tty)
     {
       dup2 (fd, 0);
       close (fd);
       fd = 0;
 #if defined (BUFFERED_INPUT)
       default_buffered_input = 0;
 #else
       fclose (default_input);
       default_input = stdin;
 #endif
     }
   else if (forced_interactive && fd_is_tty == 0)
     /* But if a script is called with something like `bash -i scriptname',
        we need to do a non-interactive setup here, since we didn't do it
        before. */
     init_interactive_script ();
   free (filename);
   reading_shell_script = 1;
   return (fd);
 }
References _, absolute_program(), array_push, check_binary_file(), close(), default_input, dollar_vars, dup2(), EINVAL, EISDIR, end_job_control(), ENOENT, errno, EX_BINARY_FILE, EX_NOEXEC, EX_NOINPUT, EX_NOTFOUND, exec_argv0, executing_line_number(), exit(), fclose(), fdopen(), file_error(), file_isdir(), fileno(), find_path_file(), forced_interactive, free, fstat(), GET_ARRAY_FROM_VAR, init_interactive_script(), interactive_shell, internal_error(), isatty(), itos(), L, lseek(), move_to_high_fd(), NULL, O_RDONLY, open(), read(), reading_shell_script, S_ISDIR, savestring(), SET_CLOSE_ON_EXEC, sh_exit(), stat::st_mode, stdin, and t.
Referenced by main().
PARAMS() [1/7]
static void execute_env_file PARAMS ((char *)) static
PARAMS() [2/7]
static int parse_long_options PARAMS ((char **, int, int)) static
PARAMS() [3/7]
static int bind_args PARAMS ((char **, int, int, int)) static
PARAMS() [4/7]
static void add_shopt_to_alist PARAMS ((char *, int)) static
PARAMS() [5/7]
static void show_shell_usage PARAMS ((FILE *, int)) static
PARAMS() [6/7]
int initialize_job_control PARAMS ((int))
PARAMS() [7/7]
int get_tty_state PARAMS ((void))
parse_long_options()
static int parse_long_options (char ** argv, int arg_start, int arg_end) static
Definition at line 838 of file shell.c.
 {
   int arg_index, longarg, i;
   char *arg_string;
   arg_index = arg_start;
   while ((arg_index != arg_end) && (arg_string = argv[arg_index]) &&
      (*arg_string == '-'))
     {
       longarg = 0;
       /* Make --login equivalent to -login. */
       if (arg_string[1] == '-' && arg_string[2])
     {
       longarg = 1;
       arg_string++;
     }
       for (i = 0; long_args[i].name; i++)
     {
       if (STREQ (arg_string + 1, long_args[i].name))
         {
           if (long_args[i].type == Int)
         *long_args[i].int_value = 1;
           else if (argv[++arg_index] == 0)
         {
           report_error (_("%s: option requires an argument"), long_args[i].name);
           exit (EX_BADUSAGE);
         }
           else
         *long_args[i].char_value = argv[arg_index];
           break;
         }
     }
       if (long_args[i].name == 0)
     {
       if (longarg)
         {
           report_error (_("%s: invalid option"), argv[arg_index]);
           show_shell_usage (stderr, 0);
           exit (EX_BADUSAGE);
         }
       break;        /* No such argument.  Maybe flag arg. */
     }
       arg_index++;
     }
   return (arg_index);
 }
References _, argv, EX_BADUSAGE, exit(), i, Int, long_args, name, report_error(), show_shell_usage(), stderr, STREQ, and type.
Referenced by main().
parse_shell_options()
static int parse_shell_options (char ** argv, int arg_start, int arg_end) static
Definition at line 893 of file shell.c.
 {
   int arg_index;
   int arg_character, on_or_off, next_arg, i;
   char *o_option, *arg_string;
   arg_index = arg_start;
   while (arg_index != arg_end && (arg_string = argv[arg_index]) &&
      (*arg_string == '-' || *arg_string == '+'))
     {
       /* There are flag arguments, so parse them. */
       next_arg = arg_index + 1;
       /* A single `-' signals the end of options.  From the 4.3 BSD sh.
      An option `--' means the same thing; this is the standard
      getopt(3) meaning. */
       if (arg_string[0] == '-' &&
        (arg_string[1] == '\0' ||
          (arg_string[1] == '-' && arg_string[2] == '\0')))
     return (next_arg);
       i = 1;
       on_or_off = arg_string[0];
       while (arg_character = arg_string[i++])
     {
       switch (arg_character)
         {
         case 'c':
           want_pending_command = 1;
           break;
         case 'l':
           make_login_shell = 1;
           break;
         case 's':
           read_from_stdin = 1;
           break;
         case 'o':
           o_option = argv[next_arg];
           if (o_option == 0)
         {
           set_option_defaults ();
           list_minus_o_opts (-1, (on_or_off == '-') ? 0 : 1);
           reset_option_defaults ();
           break;
         }
           if (set_minus_o_option (on_or_off, o_option) != EXECUTION_SUCCESS)
         exit (EX_BADUSAGE);
           next_arg++;
           break;
         case 'O':
           /* Since some of these can be overridden by the normal
          interactive/non-interactive shell initialization or
          initializing posix mode, we save the options and process
          them after initialization. */
           o_option = argv[next_arg];
           if (o_option == 0)
         {
           shopt_listopt (o_option, (on_or_off == '-') ? 0 : 1);
           break;
         }
           add_shopt_to_alist (o_option, on_or_off);
           next_arg++;
           break;
         case 'D':
 #if defined (TRANSLATABLE_STRINGS)
           dump_translatable_strings = 1;
 #endif
           break;
         default:
           if (change_flag (arg_character, on_or_off) == FLAG_ERROR)
         {
           report_error (_("%c%c: invalid option"), on_or_off, arg_character);
           show_shell_usage (stderr, 0);
           exit (EX_BADUSAGE);
         }
         }
     }
       /* Can't do just a simple increment anymore -- what about
      "bash -abouo emacs ignoreeof -hP"? */
       arg_index = next_arg;
     }
   return (arg_index);
 }
References _, add_shopt_to_alist(), argv, change_flag(), dump_translatable_strings, EX_BADUSAGE, EXECUTION_SUCCESS, exit(), FLAG_ERROR, i, make_login_shell, read_from_stdin, report_error(), reset_option_defaults(), set_option_defaults(), show_shell_usage(), stderr, and want_pending_command.
Referenced by main().
reset_option_defaults()
static void reset_option_defaults () static
Definition at line 1837 of file shell.c.
 {
 #if defined (HISTORY)
   enable_history_list = -1;
 #endif
 }
References enable_history_list.
Referenced by parse_shell_options().
run_shopt_alist()
static void run_shopt_alist () static
Definition at line 2126 of file shell.c.
 {
   register int i;
   for (i = 0; i < shopt_ind; i++)
     if (shopt_setopt (shopt_alist[i].word, (shopt_alist[i].token == '-')) != EXECUTION_SUCCESS)
       exit (EX_BADUSAGE);
   free (shopt_alist);
   shopt_alist = 0;
   shopt_ind = shopt_len = 0;
 }
References EX_BADUSAGE, EXECUTION_SUCCESS, exit(), free, i, shopt_alist, shopt_ind, shopt_len, and token.
Referenced by main().
run_startup_files()
static void run_startup_files () static
Definition at line 1124 of file shell.c.
 {
 #if defined (JOB_CONTROL)
   int old_job_control;
 #endif
   int sourced_login, run_by_ssh;
 #if 1   /* TAG:bash-5.3 andrew.gregory.8@gmail.com 2/21/2022 */
   /* get the rshd/sshd case out of the way first. */
   if (interactive_shell == 0 && no_rc == 0 && login_shell == 0 &&
       act_like_sh == 0 && command_execution_string)
     {
 #ifdef SSH_SOURCE_BASHRC
       run_by_ssh = (find_variable ("SSH_CLIENT") != (SHELL_VAR *)0) ||
            (find_variable ("SSH2_CLIENT") != (SHELL_VAR *)0);
 #else
       run_by_ssh = 0;
 #endif
 #endif
       /* If we were run by sshd or we think we were run by rshd, execute
      ~/.bashrc if we are a top-level shell. */
 #if 1   /* TAG:bash-5.3 */
       if ((run_by_ssh || isnetconn (fileno (stdin))) && shell_level < 2)
 #else
       if (isnetconn (fileno (stdin) && shell_level < 2)
 #endif
     {
 #ifdef SYS_BASHRC
 #  if defined (__OPENNT)
       maybe_execute_file (_prefixInstallPath(SYS_BASHRC, NULL, 0), 1);
 #  else
       maybe_execute_file (SYS_BASHRC, 1);
 #  endif
 #endif
       maybe_execute_file (bashrc_file, 1);
       return;
     }
     }
 #if defined (JOB_CONTROL)
   /* Startup files should be run without job control enabled. */
   old_job_control = interactive_shell ? set_job_control (0) : 0;
 #endif
   sourced_login = 0;
   /* A shell begun with the --login (or -l) flag that is not in posix mode
      runs the login shell startup files, no matter whether or not it is
      interactive.  If NON_INTERACTIVE_LOGIN_SHELLS is defined, run the
      startup files if argv[0][0] == '-' as well. */
 #if defined (NON_INTERACTIVE_LOGIN_SHELLS)
   if (login_shell && posixly_correct == 0)
 #else
   if (login_shell < 0 && posixly_correct == 0)
 #endif
     {
       /* We don't execute .bashrc for login shells. */
       no_rc++;
       /* Execute /etc/profile and one of the personal login shell
      initialization files. */
       if (no_profile == 0)
     {
       maybe_execute_file (SYS_PROFILE, 1);
       if (act_like_sh)  /* sh */
         maybe_execute_file ("~/.profile", 1);
       else if ((maybe_execute_file ("~/.bash_profile", 1) == 0) &&
            (maybe_execute_file ("~/.bash_login", 1) == 0))  /* bash */
         maybe_execute_file ("~/.profile", 1);
     }
       sourced_login = 1;
     }
   /* A non-interactive shell not named `sh' and not in posix mode reads and
      executes commands from $BASH_ENV.  If `su' starts a shell with `-c cmd'
      and `-su' as the name of the shell, we want to read the startup files.
      No other non-interactive shells read any startup files. */
   if (interactive_shell == 0 && !(su_shell && login_shell))
     {
       if (posixly_correct == 0 && act_like_sh == 0 && privileged_mode == 0 &&
         sourced_env++ == 0)
     execute_env_file (get_string_value ("BASH_ENV"));
       return;
     }
   /* Interactive shell or `-su' shell. */
   if (posixly_correct == 0)       /* bash, sh */
     {
       if (login_shell && sourced_login++ == 0)
     {
       /* We don't execute .bashrc for login shells. */
       no_rc++;
       /* Execute /etc/profile and one of the personal login shell
          initialization files. */
       if (no_profile == 0)
         {
           maybe_execute_file (SYS_PROFILE, 1);
           if (act_like_sh)  /* sh */
         maybe_execute_file ("~/.profile", 1);
           else if ((maybe_execute_file ("~/.bash_profile", 1) == 0) &&
                (maybe_execute_file ("~/.bash_login", 1) == 0))  /* bash */
         maybe_execute_file ("~/.profile", 1);
         }
     }
       /* bash */
       if (act_like_sh == 0 && no_rc == 0)
     {
 #ifdef SYS_BASHRC
 #  if defined (__OPENNT)
       maybe_execute_file (_prefixInstallPath(SYS_BASHRC, NULL, 0), 1);
 #  else
       maybe_execute_file (SYS_BASHRC, 1);
 #  endif
 #endif
       maybe_execute_file (bashrc_file, 1);
     }
       /* sh */
       else if (act_like_sh && privileged_mode == 0 && sourced_env++ == 0)
     execute_env_file (get_string_value ("ENV"));
     }
   else      /* bash --posix, sh --posix */
     {
       /* bash and sh */
       if (interactive_shell && privileged_mode == 0 && sourced_env++ == 0)
     execute_env_file (get_string_value ("ENV"));
     }
 #if defined (JOB_CONTROL)
   set_job_control (old_job_control);
 #endif
 }
References act_like_sh, bashrc_file, command_execution_string, execute_env_file(), fileno(), find_variable(), get_string_value(), interactive_shell, isnetconn(), login_shell, maybe_execute_file(), no_profile, no_rc, NULL, posixly_correct, privileged_mode, set_job_control(), shell_level, sourced_env, stdin, and su_shell.
Referenced by main().
set_bash_input()
static void set_bash_input () static
Definition at line 1740 of file shell.c.
 {
   /* Make sure the fd from which we are reading input is not in
      no-delay mode. */
 #if defined (BUFFERED_INPUT)
   if (interactive == 0)
     sh_unset_nodelay_mode (default_buffered_input);
   else
 #endif /* !BUFFERED_INPUT */
     sh_unset_nodelay_mode (fileno (stdin));
   /* with_input_from_stdin really means `with_input_from_readline' */
   if (interactive && no_line_editing == 0)
     with_input_from_stdin ();
 #if defined (BUFFERED_INPUT)
   else if (interactive == 0)
     with_input_from_buffered_stream (default_buffered_input, dollar_vars[0]);
 #endif /* BUFFERED_INPUT */
   else
     with_input_from_stream (default_input, dollar_vars[0]);
 }
References default_input, dollar_vars, fileno(), interactive, no_line_editing, sh_unset_nodelay_mode(), stdin, with_input_from_stdin(), and with_input_from_stream().
Referenced by main().
set_exit_status()
void set_exit_status (int s)
Definition at line 1075 of file shell.c.
 {
   set_pipestatus_from_exit (last_command_exit_value = s);
 }
References last_command_exit_value, and set_pipestatus_from_exit().
Referenced by do_assignment_internal(), expand_word_internal(), expr_streval(), make_arith_command(), make_arith_for_command(), make_child(), make_cond_command(), make_select_command(), param_expand(), parameter_brace_expand(), parameter_brace_expand_error(), parameter_brace_expand_word(), parse_compound_assignment(), parse_comsub(), parse_string_to_word_list(), reader_loop(), sigint_sighandler(), sv_locale(), and wait_sigint_handler().
set_option_defaults()
static void set_option_defaults () static
Definition at line 1829 of file shell.c.
 {
 #if defined (HISTORY)
   enable_history_list = 0;
 #endif
 }
References enable_history_list.
Referenced by parse_shell_options().
set_shell_name()
static void set_shell_name (char * argv0) static
Definition at line 1793 of file shell.c.
 {
   /* Here's a hack.  If the name of this shell is "sh", then don't do
      any startup files; just try to be more like /bin/sh. */
   shell_name = argv0 ? base_pathname (argv0) : PROGRAM;
   if (argv0 && *argv0 == '-')
     {
       if (*shell_name == '-')
     shell_name++;
       login_shell = 1;
     }
   if (shell_name[0] == 's' && shell_name[1] == 'h' && shell_name[2] == '\0')
     act_like_sh++;
   if (shell_name[0] == 's' && shell_name[1] == 'u' && shell_name[2] == '\0')
     su_shell++;
   shell_name = argv0 ? argv0 : PROGRAM;
   FREE (dollar_vars[0]);
   dollar_vars[0] = savestring (shell_name);
   /* A program may start an interactive shell with
       "execl ("/bin/bash", "-", NULL)".
      If so, default the name of this shell to our name. */
   if (!shell_name || !*shell_name || (shell_name[0] == '-' && !shell_name[1]))
     shell_name = PROGRAM;
 }
References act_like_sh, base_pathname(), dollar_vars, FREE, login_shell, PROGRAM, savestring(), shell_name, and su_shell.
Referenced by main().
sh_exit()
void sh_exit (int s)
Definition at line 1043 of file shell.c.
 {
 #if defined (MALLOC_DEBUG) && defined (USING_BASH_MALLOC)
   if (malloc_trace_at_exit && (subshell_environment & (SUBSHELL_COMSUB|SUBSHELL_PROCSUB)) == 0)
     trace_malloc_stats (get_name_for_error (), (char *)NULL);
   /* mlocation_write_table (); */
 #endif
   exit (s);
 }
References exit(), get_name_for_error(), malloc_trace_at_exit, NULL, SUBSHELL_COMSUB, subshell_environment, and SUBSHELL_PROCSUB.
Referenced by execute_command_internal(), execute_simple_command(), exit_shell(), fatal_error(), open_shell_script(), and subshell_exit().
shell_initialize()
static void shell_initialize () static
Definition at line 1928 of file shell.c.
 {
   char hostname[256];
   int should_be_restricted;
   /* Line buffer output for stderr and stdout. */
   if (shell_initialized == 0)
     {
       sh_setlinebuf (stderr);
       sh_setlinebuf (stdout);
     }
   /* Sort the array of shell builtins so that the binary search in
      find_shell_builtin () works correctly. */
   initialize_shell_builtins ();
   /* Initialize the trap signal handlers before installing our own
      signal handlers.  traps.c:restore_original_signals () is responsible
      for restoring the original default signal handlers.  That function
      is called when we make a new child. */
   initialize_traps ();
   initialize_signals (0);
   /* It's highly unlikely that this will change. */
   if (current_host_name == 0)
     {
       /* Initialize current_host_name. */
       if (gethostname (hostname, 255) < 0)
     current_host_name = "??host??";
       else
     current_host_name = savestring (hostname);
     }
   /* Initialize the stuff in current_user that comes from the password
      file.  We don't need to do this right away if the shell is not
      interactive. */
   if (interactive_shell)
     get_current_user_info ();
   /* Initialize our interface to the tilde expander. */
   tilde_initialize ();
 #if defined (RESTRICTED_SHELL)
   should_be_restricted = shell_is_restricted (shell_name);
 #endif
   /* Initialize internal and environment variables.  Don't import shell
      functions from the environment if we are running in privileged or
      restricted mode or if the shell is running setuid. */
 #if defined (RESTRICTED_SHELL)
   initialize_shell_variables (shell_environment, privileged_mode||restricted||should_be_restricted||running_setuid);
 #else
   initialize_shell_variables (shell_environment, privileged_mode||running_setuid);
 #endif
   /* Initialize the data structures for storing and running jobs. */
   initialize_job_control (jobs_m_flag);
   /* Initialize input streams to null. */
   initialize_bash_input ();
   initialize_flags ();
   /* Initialize the shell options.  Don't import the shell options
      from the environment variables $SHELLOPTS or $BASHOPTS if we are
      running in privileged or restricted mode or if the shell is running
      setuid. */
 #if defined (RESTRICTED_SHELL)
   initialize_shell_options (privileged_mode||restricted||should_be_restricted||running_setuid);
   initialize_bashopts (privileged_mode||restricted||should_be_restricted||running_setuid);
 #else
   initialize_shell_options (privileged_mode||running_setuid);
   initialize_bashopts (privileged_mode||running_setuid);
 #endif
 }
References current_host_name, get_current_user_info(), gethostname(), initialize_bash_input(), initialize_flags(), initialize_job_control(), initialize_shell_builtins(), initialize_shell_variables(), initialize_signals(), initialize_traps(), interactive_shell, jobs_m_flag, privileged_mode, running_setuid, savestring(), sh_setlinebuf(), shell_environment, shell_initialized, shell_name, stderr, stdout, and tilde_initialize().
Referenced by main().
shell_reinitialize()
static void shell_reinitialize () static
Definition at line 2008 of file shell.c.
 {
   /* The default shell prompts. */
   primary_prompt = PPROMPT;
   secondary_prompt = SPROMPT;
   /* Things that get 1. */
   current_command_number = 1;
   /* We have decided that the ~/.bashrc file should not be executed
      for the invocation of each shell script.  If the variable $ENV
      (or $BASH_ENV) is set, its value is used as the name of a file
      to source. */
   no_rc = no_profile = 1;
   /* Things that get 0. */
   login_shell = make_login_shell = interactive = executing = 0;
   debugging = do_version = line_number = last_command_exit_value = 0;
   forced_interactive = interactive_shell = 0;
   subshell_environment = running_in_background = 0;
   expand_aliases = expaliases_flag = 0;
   bash_argv_initialized = 0;
   /* XXX - should we set jobs_m_flag to 0 here? */
 #if defined (HISTORY)
   bash_history_reinit (enable_history_list = 0);
 #endif /* HISTORY */
 #if defined (RESTRICTED_SHELL)
   restricted = 0;
 #endif /* RESTRICTED_SHELL */
   /* Ensure that the default startup file is used.  (Except that we don't
      execute this file for reinitialized shells). */
   bashrc_file = DEFAULT_BASHRC;
   /* Delete all variables and functions.  They will be reinitialized when
      the environment is parsed. */
   delete_all_contexts (shell_variables);
   delete_all_variables (shell_functions);
   reinit_special_variables ();
 #if defined (READLINE)
   bashline_reinitialize ();
 #endif
   shell_reinitialized = 1;
 }
References bash_argv_initialized, bashrc_file, current_command_number, debugging, DEFAULT_BASHRC, delete_all_contexts(), delete_all_variables(), do_version, enable_history_list, executing, expaliases_flag, expand_aliases, forced_interactive, interactive, interactive_shell, last_command_exit_value, line_number, login_shell, make_login_shell, no_profile, no_rc, PPROMPT, primary_prompt, reinit_special_variables(), running_in_background, secondary_prompt, shell_functions, shell_reinitialized, shell_variables, SPROMPT, and subshell_environment.
Referenced by main().
show_shell_usage()
static void show_shell_usage (FILE * fp, int extra) static
Definition at line 2060 of file shell.c.
 {
   int i;
   char *set_opts, *s, *t;
   if (extra)
     fprintf (fp, _("GNU bash, version %s-(%s)\n"), shell_version_string (), MACHTYPE);
   fprintf (fp, _("Usage:\t%s [GNU long option] [option] ...\n\t%s [GNU long option] [option] script-file ...\n"),
          shell_name, shell_name);
   fputs (_("GNU long options:\n"), fp);
   for (i = 0; long_args[i].name; i++)
     fprintf (fp, "\t--%s\n", long_args[i].name);
   fputs (_("Shell options:\n"), fp);
   fputs (_("\t-ilrsD or -c command or -O shopt_option\t\t(invocation only)\n"), fp);
   for (i = 0, set_opts = 0; shell_builtins[i].name; i++)
     if (STREQ (shell_builtins[i].name, "set"))
       {
     set_opts = savestring (shell_builtins[i].short_doc);
     break;
       }
   if (set_opts)
     {
       s = strchr (set_opts, '[');
       if (s == 0)
     s = set_opts;
       while (*++s == '-')
     ;
       t = strchr (s, ']');
       if (t)
     *t = '\0';
       fprintf (fp, _("\t-%s or -o option\n"), s);
       free (set_opts);
     }
   if (extra)
     {
       fprintf (fp, _("Type `%s -c \"help set\"' for more information about shell options.\n"), shell_name);
       fprintf (fp, _("Type `%s -c help' for more information about shell builtin commands.\n"), shell_name);
       fprintf (fp, _("Use the `bashbug' command to report bugs.\n"));
       fprintf (fp, "\n");
       fprintf (fp, _("bash home page: <http://www.gnu.org/software/bash>\n"));
       fprintf (fp, _("General help using GNU software: <http://www.gnu.org/gethelp/>\n"));
     }
 }
References _, fprintf(), fputs(), free, i, long_args, MACHTYPE, builtin::name, name, savestring(), shell_builtins, shell_name, shell_version_string(), strchr(), STREQ, and t.
Referenced by main(), parse_long_options(), and parse_shell_options().
start_debugger()
static void start_debugger () static
Definition at line 1539 of file shell.c.
 {
 #if defined (DEBUGGER) && defined (DEBUGGER_START_FILE)
   int old_errexit;
   int r;
   old_errexit = exit_immediately_on_error;
   exit_immediately_on_error = 0;
   r = force_execute_file (DEBUGGER_START_FILE, 1);
   if (r < 0)
     {
       internal_warning (_("cannot start debugger; debugging mode disabled"));
       debugging_mode = 0;
     }
   error_trace_mode = function_trace_mode = debugging_mode;
   set_shellopts ();
   set_bashopts ();
   exit_immediately_on_error += old_errexit;
 #endif
 }
References _, debugging_mode, error_trace_mode, exit_immediately_on_error, force_execute_file(), function_trace_mode, internal_warning(), and r.
Referenced by main().
subshell_exit()
void subshell_exit (int s)
Definition at line 1059 of file shell.c.
 {
   fflush (stdout);
   fflush (stderr);
   /* Do trap[0] if defined.  Allow it to override the exit status
      passed to us. */
   last_command_exit_value = s;
   if (signal_is_trapped (0))
     s = run_exit_trap ();
   sh_exit (s);
 }
References fflush(), last_command_exit_value, run_exit_trap(), sh_exit(), signal_is_trapped(), stderr, and stdout.
Referenced by execute_command_internal(), and execute_subshell_builtin_or_function().
uidget()
static int uidget () static
Definition at line 1316 of file shell.c.
 {
   uid_t u;
   u = getuid ();
   if (current_user.uid != u)
     {
       FREE (current_user.user_name);
       FREE (current_user.shell);
       FREE (current_user.home_dir);
       current_user.user_name = current_user.shell = current_user.home_dir = (char *)NULL;
     }
   current_user.uid = u;
   current_user.gid = getgid ();
   current_user.euid = geteuid ();
   current_user.egid = getegid ();
   /* See whether or not we are running setuid or setgid. */
   return (current_user.uid != current_user.euid) ||
        (current_user.gid != current_user.egid);
 }
References current_user, user_info::egid, user_info::euid, FREE, getegid, geteuid, getgid, getuid, user_info::gid, user_info::home_dir, NULL, user_info::shell, user_info::uid, and user_info::user_name.
Referenced by main().
unbind_args()
void unbind_args ()
Definition at line 1532 of file shell.c.
 {
   remember_args ((WORD_LIST *)NULL, 1);
   pop_args ();              /* Reset BASH_ARGV and BASH_ARGC */
 }
References NULL, pop_args(), and remember_args().
Referenced by shell_execve().
unset_bash_input()
void unset_bash_input (int check_zero)
Definition at line 1767 of file shell.c.
 {
 #if defined (BUFFERED_INPUT)
   if ((check_zero && default_buffered_input >= 0) ||
       (check_zero == 0 && default_buffered_input > 0))
     {
       close_buffered_fd (default_buffered_input);
       default_buffered_input = bash_input.location.buffered_fd = -1;
       bash_input.type = st_none;        /* XXX */
     }
 #else /* !BUFFERED_INPUT */
   if (default_input)
     {
       fclose (default_input);
       default_input = (FILE *)NULL;
     }
 #endif /* !BUFFERED_INPUT */
 }
References bash_input, default_input, fclose(), BASH_INPUT::location, NULL, st_none, and BASH_INPUT::type.
Referenced by initialize_subshell(), and make_child().
Variable Documentation
act_like_sh
int act_like_sh static
Definition at line 200 of file shell.c.
Referenced by main(), run_startup_files(), and set_shell_name().
autocd
int autocd = 0
Definition at line 152 of file shell.c.
Referenced by execute_simple_command().
bash_argv_initialized
int bash_argv_initialized = 0
Definition at line 113 of file shell.c.
Referenced by bind_args(), init_bash_argv(), and shell_reinitialize().
bashrc_file
char* bashrc_file = DEFAULT_BASHRC static
Definition at line 197 of file shell.c.
Referenced by run_startup_files(), and shell_reinitialize().
check_jobs_at_exit
int check_jobs_at_exit = 0
Definition at line 149 of file shell.c.
command_execution_string
char* command_execution_string
Definition at line 301 of file shell.c.
Referenced by initialize_shell_variables(), main(), and run_startup_files().
current_command_number
int current_command_number = 1
Definition at line 174 of file shell.c.
Referenced by decode_prompt_string(), reader_loop(), and shell_reinitialize().
current_host_name
char* current_host_name = (char *)NULL
Definition at line 125 of file shell.c.
Referenced by decode_prompt_string(), set_machine_vars(), and shell_initialize().
current_user
struct user_info current_user
Initial value:
=
{
  (uid_t)-1, (uid_t)-1, (gid_t)-1, (gid_t)-1,
  (char *)NULL, (char *)NULL, (char *)NULL
}
Definition at line 115 of file shell.c.
Referenced by decode_prompt_string(), disable_priv_mode(), file_status(), genseed(), get_bash_name(), get_current_user_info(), group_member(), initialize_group_array(), initialize_shell_variables(), inituser(), make_default_mailpath(), set_shell_var(), sh_eaccess(), sh_get_home_dir(), sh_stataccess(), uidget(), uidset(), unary_test(), and whoami_builtin().
debugging
int debugging static
Definition at line 212 of file shell.c.
Referenced by shell_reinitialize().
debugging_login_shell
int debugging_login_shell = 0
Definition at line 165 of file shell.c.
Referenced by main().
debugging_mode
int debugging_mode = 0
Definition at line 219 of file shell.c.
Referenced by bind_args(), execute_case_command(), execute_for_command(), execute_function(), execute_simple_command(), main(), run_debug_trap(), and start_debugger().
default_input
FILE* default_input static
Definition at line 308 of file shell.c.
Referenced by main(), open_shell_script(), set_bash_input(), and unset_bash_input().
do_version
int do_version static
Definition at line 215 of file shell.c.
Referenced by main(), and shell_reinitialize().
errno
int errno extern
Referenced by disable_priv_mode(), and open_shell_script().
exec_argv0
char* exec_argv0
Definition at line 289 of file shell.c.
Referenced by main(), and open_shell_script().
executing
int executing = 0
Definition at line 171 of file shell.c.
Referenced by executing_line_number(), main(), reader_loop(), and shell_reinitialize().
global_command
COMMAND* global_command = (COMMAND *)NULL
Definition at line 115 of file shell.c.
Referenced by parse_and_execute(), parse_comsub(), parse_string(), pretty_print_loop(), read_command(), reader_loop(), and yyparse().
gnu_error_format
int gnu_error_format extern
Definition at line 76 of file error.c.
Referenced by error_prolog(), main(), and parser_error().
have_devfd
int have_devfd = 0
Definition at line 193 of file shell.c.
hup_on_exit
int hup_on_exit = 0
Definition at line 146 of file shell.c.
Referenced by exit_shell().
indirection_level
int indirection_level = 0
Definition at line 177 of file shell.c.
Referenced by indirection_level_string(), parse_and_execute(), parse_prologue(), and reader_loop().
interactive
int interactive = 0
Definition at line 139 of file shell.c.
Referenced by _evalfile(), command_substitute(), execute_command_internal(), execute_disk_command(), execute_in_subshell(), execute_null_command(), execute_simple_command(), execute_subshell_builtin_or_function(), get_tty_state(), handle_eof_input_unit(), init_interactive(), init_noninteractive(), initialize_job_control(), initialize_job_signals(), initialize_shell_signals(), initialize_traps(), main(), notify_and_cleanup(), parse_and_execute(), parse_command(), parse_prologue(), parser_error(), print_pipeline(), prompt_again(), read_a_line(), read_command(), read_token(), reader_loop(), report_syntax_error(), set_bash_input(), set_sigint_handler(), set_signal(), set_tty_state(), shell_reinitialize(), stop_pipeline(), termsig_handler(), termsig_sighandler(), throw_to_top_level(), wait_for(), waitchld(), yylex(), and yyparse().
interactive_shell
int interactive_shell = 0
Definition at line 142 of file shell.c.
Referenced by builtin_error_prolog(), change_flag(), do_assignment_statements(), do_redirection_internal(), error_prolog(), execute_for_command(), execute_in_subshell(), execute_intern_function(), execute_simple_command(), executing_line_number(), exit_shell(), expr_streval(), get_name_for_error(), get_new_window_size(), get_original_tty_job_signals(), init_interactive(), init_interactive_script(), init_noninteractive(), initialize_shell_variables(), initialize_subshell(), initialize_terminating_signals(), main(), make_child(), mark_dead_jobs_as_notified(), notify_and_cleanup(), notify_of_job_status(), open_redir_file(), open_shell_script(), param_expand(), parameter_brace_expand(), parameter_brace_expand_rhs(), parameter_brace_transform(), parse_and_execute(), parse_compound_assignment(), parse_comsub(), parse_prologue(), parse_string_to_word_list(), parser_error(), posix_initialize(), reader_loop(), redirection_error(), run_startup_files(), set_job_control(), set_job_status_and_cleanup(), set_pwd(), shell_getc(), shell_initialize(), shell_reinitialize(), source_file(), stop_pipeline(), sv_strict_posix(), termsig_handler(), termsig_sighandler(), throw_to_top_level(), and wait_for().
login_shell
int login_shell = 0
Definition at line 134 of file shell.c.
Referenced by execute_in_subshell(), execute_subshell_builtin_or_function(), exit_shell(), get_bash_name(), handle_eof_input_unit(), initialize_job_signals(), initialize_shell_variables(), main(), run_startup_files(), set_pwd(), set_shell_name(), and shell_reinitialize().
const { ... } long_args[]
Referenced by parse_long_options(), and show_shell_usage().
make_login_shell
int make_login_shell static
Definition at line 216 of file shell.c.
Referenced by main(), parse_shell_options(), and shell_reinitialize().
malloc_trace_at_exit
int malloc_trace_at_exit = 0
Definition at line 304 of file shell.c.
Referenced by sh_exit().
no_line_editing
int no_line_editing = 1
Definition at line 223 of file shell.c.
Referenced by decode_prompt_string(), get_new_window_size(), init_noninteractive(), initialize_shell_variables(), main(), parse_command(), prompt_again(), read_a_line(), set_bash_input(), shell_getc(), and termsig_sighandler().
no_profile
int no_profile static
Definition at line 214 of file shell.c.
Referenced by run_startup_files(), and shell_reinitialize().
no_rc
int no_rc static
Definition at line 213 of file shell.c.
Referenced by run_startup_files(), and shell_reinitialize().
posixly_correct
int posixly_correct = 0
Definition at line 237 of file shell.c.
Referenced by command_substitute(), decode_prompt_string(), display_signal_list(), do_assignment_statements(), do_redirection_internal(), execute_builtin(), execute_command_internal(), execute_for_command(), execute_intern_function(), execute_simple_command(), expand_word_internal(), extract_dollar_brace_string(), extract_heredoc_dolbrace_string(), find_in_path_element(), fix_assignment_words(), importable_function_name(), init_noninteractive(), initialize_shell_variables(), main(), merge_temporary_env(), notify_of_job_status(), open_redir_file(), param_expand(), parameter_brace_expand(), parameter_brace_expand_rhs(), parse_and_execute(), parse_compound_assignment(), parse_comsub(), parse_matched_pair(), parse_string_to_word_list(), pretty_print_loop(), print_function_def(), print_var_value(), printable_job_status(), push_posix_tempvar_internal(), read_token_word(), redirection_error(), redirection_expand(), run_startup_files(), search_for_command(), set_pwd(), source_file(), start_job(), sv_locale(), sv_strict_posix(), time_command_acceptable(), wait_for_single_pid(), and waitchld().
pretty_print_mode
int pretty_print_mode = 0
Definition at line 232 of file shell.c.
Referenced by main().
protected_mode
int protected_mode = 0
Definition at line 230 of file shell.c.
read_from_stdin
int read_from_stdin
Definition at line 297 of file shell.c.
Referenced by main(), and parse_shell_options().
reading_shell_script
int reading_shell_script = 0
Definition at line 162 of file shell.c.
Referenced by main(), and open_shell_script().
running_in_background
int running_in_background extern
Definition at line 225 of file jobs.c.
Referenced by initialize_job_control(), make_child(), maybe_give_terminal_to(), set_job_control(), shell_reinitialize(), stop_pipeline(), and wait_for().
running_setuid
int running_setuid static
Definition at line 209 of file shell.c.
Referenced by main(), and shell_initialize().
running_under_emacs
int running_under_emacs
Definition at line 187 of file shell.c.
Referenced by main(), and parse_command().
shell_environment
char** shell_environment
Definition at line 168 of file shell.c.
Referenced by main(), and shell_initialize().
shell_initialized
int shell_initialized = 0
Definition at line 112 of file shell.c.
Referenced by change_flag(), main(), make_function_def(), shell_initialize(), and throw_to_top_level().
shell_name
char* shell_name = (char *)NULL
Definition at line 180 of file shell.c.
Referenced by assign_bash_argv0(), bind_args(), change_flag(), decode_prompt_string(), get_bash_name(), get_name_for_error(), main(), set_shell_name(), shell_execve(), shell_initialize(), and show_shell_usage().
shell_reinitialized
int shell_reinitialized = 0 static
Definition at line 306 of file shell.c.
Referenced by main(), and shell_reinitialize().
shell_script_filename
char* shell_script_filename
Definition at line 302 of file shell.c.
Referenced by main().
shell_start_time
time_t shell_start_time
Definition at line 183 of file shell.c.
Referenced by assign_seconds(), get_seconds(), init_mail_file(), and main().
shellstart
struct timeval shellstart
Definition at line 183 of file shell.c.
Referenced by assign_seconds(), and main().
shopt_alist
STRING_INT_ALIST* shopt_alist static
Definition at line 310 of file shell.c.
Referenced by add_shopt_to_alist(), main(), and run_shopt_alist().
shopt_ind
int shopt_ind = 0 static
Definition at line 311 of file shell.c.
Referenced by add_shopt_to_alist(), and run_shopt_alist().
shopt_len
int shopt_len = 0 static
Definition at line 311 of file shell.c.
Referenced by add_shopt_to_alist(), and run_shopt_alist().
sourced_env
int sourced_env static
Definition at line 206 of file shell.c.
Referenced by main(), and run_startup_files().
startup_state
int startup_state = 0
Definition at line 161 of file shell.c.
Referenced by command_substitute(), init_interactive(), init_interactive_script(), init_noninteractive(), main(), notify_of_job_status(), parse_and_execute(), and should_suppress_fork().
su_shell
int su_shell static
Definition at line 203 of file shell.c.
Referenced by run_startup_files(), and set_shell_name().
subshell_argc
int subshell_argc
Definition at line 285 of file shell.c.
Referenced by main(), and shell_execve().
subshell_argv
char** subshell_argv
Definition at line 286 of file shell.c.
Referenced by main(), and shell_execve().
subshell_envp
char** subshell_envp
Definition at line 287 of file shell.c.
Referenced by main(), and shell_execve().
subshell_top_level
procenv_t subshell_top_level
Definition at line 284 of file shell.c.
Referenced by main(), and shell_execve().
want_initial_help
int want_initial_help static
Definition at line 217 of file shell.c.
Referenced by main().
want_pending_command
int want_pending_command
Definition at line 298 of file shell.c.
Referenced by main(), parse_shell_options(), and which_set_flags().
wordexp_only
int wordexp_only = 0
Definition at line 229 of file shell.c.
Referenced by command_substitute(), and main().