Fennix Userspace: Userspace/musl/src/unistd/read.c File Reference
read.c File Reference
#include <unistd.h>
#include "syscall.h"
Functions
ssize_t read (int fd, void *buf, size_t count)
Function Documentation
read()
ssize_t read (int fd, void * buf, size_t count)
Definition at line 4 of file read.c.
 {
     return syscall_cp(SYS_read, fd, buf, count);
 }
References buf, count, and syscall_cp.
Referenced by eventfd_read(), forkpty(), getpass(), io_thread_func(), map_library(), mmap_fixed(), posix_spawn(), pthread_getname_np(), ptmx_test(), read_loop(), test_ptmx(), test_stdio(), test_watch_directory(), test_watch_file(), and vswscanf().