Fennix: Userspace/apps/base/busybox/libbb/xfuncs.c File Reference
xfuncs.c File Reference
#include "libbb.h"
Macros
#define IMAXBEL 0
#define IUCLC 0
#define IXANY 0
Functions
int FAST_FUNC ndelay_on (int fd)
int FAST_FUNC ndelay_off (int fd)
void FAST_FUNC close_on_exec_on (int fd)
char *FAST_FUNC strncpy_IFNAMSIZ (char *dst, const char *src)
char *FAST_FUNC utoa_to_buf (unsigned n, char *buf, unsigned buflen)
char *FAST_FUNC itoa_to_buf (int n, char *buf, unsigned buflen)
char *FAST_FUNC utoa (unsigned n)
char *FAST_FUNC itoa (int n)
char *FAST_FUNC bin2hex (char *p, const char *cp, int count)
char *FAST_FUNC hex2bin (char *dst, const char *str, int count)
int FAST_FUNC bb_putchar_stderr (char ch)
ssize_t FAST_FUNC full_write1_str (const char *str)
ssize_t FAST_FUNC full_write2_str (const char *str)
static int wh_helper (int value, int def_val, const char *env_name, int *err)
int FAST_FUNC get_terminal_width_height (int fd, unsigned *width, unsigned *height)
int FAST_FUNC get_terminal_width (int fd)
int FAST_FUNC is_TERM_dumb (void)
int FAST_FUNC tcsetattr_stdin_TCSANOW (const struct termios *tp)
int FAST_FUNC get_termios_and_make_raw (int fd, struct termios *newterm, struct termios *oldterm, int flags)
int FAST_FUNC set_termios_to_raw (int fd, struct termios *oldterm, int flags)
pid_t FAST_FUNC safe_waitpid (pid_t pid, int *wstat, int options)
pid_t FAST_FUNC wait_any_nohang (int *wstat)
int FAST_FUNC wait4pid (pid_t pid)
void FAST_FUNC exit_SUCCESS (void)
void FAST_FUNC _exit_SUCCESS (void)
Variables
static char local_buf [sizeof(int) *3]
Macro Definition Documentation
IMAXBEL
#define IMAXBEL 0
IUCLC
#define IUCLC 0
IXANY
#define IXANY 0
Function Documentation
_exit_SUCCESS()
void FAST_FUNC _exit_SUCCESS (void)
Definition at line 432 of file xfuncs.c.
 {
     _exit(EXIT_SUCCESS);
 }
References _exit(), and EXIT_SUCCESS.
Referenced by alarm_handler(), bb_daemonize_or_rexec(), openhere(), pause_and_low_level_reboot(), pseudo_exec(), pseudo_exec_argv(), runsv_main(), shutdown_on_signal(), and start_stop_daemon_main().
bb_putchar_stderr()
int FAST_FUNC bb_putchar_stderr (char ch)
Definition at line 220 of file xfuncs.c.
 {
     return write(STDERR_FILENO, &ch, 1);
 }
References STDERR_FILENO, and write().
Referenced by gotsig(), ParseField(), pipe_progress_main(), and xargs_main().
bin2hex()
char* FAST_FUNC bin2hex (char * p, const char * cp, int count)
Definition at line 132 of file xfuncs.c.
 {
     while (count) {
         unsigned char c = *cp++;
         /* put lowercase hex digits */
         *p++ = 0x20 | bb_hexdigits_upcase[c >> 4];
         *p++ = 0x20 | bb_hexdigits_upcase[c & 0xf];
         count--;
     }
     return p;
 }
References c, count, and p.
Referenced by dolisten(), fill_envp(), filter_rename_config(), fmt_time_bernstein_25(), hash_bin_to_hex(), mkswap_main(), popmaildir_main(), and sprint_nip6().
close_on_exec_on()
void FAST_FUNC close_on_exec_on (int fd)
Definition at line 44 of file xfuncs.c.
 {
     fcntl(fd, F_SETFD, FD_CLOEXEC);
 }
References F_SETFD, fcntl(), fd, and FD_CLOEXEC.
Referenced by devfsd_main(), dup_CLOEXEC(), ftpd_main(), getXXent(), hfopen(), hush_main(), logdir_open(), make_new_session(), message(), nc_main(), open_control(), rotate(), runsv_main(), runsvdir_main(), savefd(), setinputfile(), svlogd_main(), tcpudpsvd_main(), telnetd_main(), time_main(), udhcp_sp_fd_set(), udhcp_sp_setup(), wait_for_seqfile(), xargs_main(), and xdup_CLOEXEC_and_close().
exit_SUCCESS()
void FAST_FUNC exit_SUCCESS (void)
Definition at line 427 of file xfuncs.c.
 {
     exit(EXIT_SUCCESS);
 }
References exit(), and EXIT_SUCCESS.
Referenced by check_mount(), clean_up_and_exit(), devfsd_main(), finish(), get_logname(), grep_file(), less_exit(), and nc_main().
full_write1_str()
ssize_t FAST_FUNC full_write1_str (const char * str)
Definition at line 225 of file xfuncs.c.
 {
     return full_write(STDOUT_FILENO, str, strlen(str));
 }
References full_write(), STDOUT_FILENO, str, and strlen().
Referenced by bbconfig_main(), clear_main(), con_escape(), finalize_tty_attrs(), get_logname(), getty_main(), hush_main(), telnet_main(), and to_echo().
full_write2_str()
ssize_t FAST_FUNC full_write2_str (const char * str)
Definition at line 230 of file xfuncs.c.
 {
     return full_write(STDERR_FILENO, str, strlen(str));
 }
References full_write(), STDERR_FILENO, str, and strlen().
Referenced by bb_show_usage(), and main().
get_terminal_width()
int FAST_FUNC get_terminal_width (int fd)
Definition at line 299 of file xfuncs.c.
 {
     unsigned width;
     get_terminal_width_height(fd, &width, NULL);
     return width;
 }
References fd, get_terminal_width_height(), NULL, and width.
Referenced by bb_progress_update(), ls_main(), ps_main(), pstree_main(), run_pipe(), stty_main(), and watch_main().
get_terminal_width_height()
int FAST_FUNC get_terminal_width_height (int fd, unsigned * width, unsigned * height)
Definition at line 265 of file xfuncs.c.
 {
     struct winsize win;
     int err;
     int close_me = -1;
     if (fd == -1) {
         if (isatty(STDOUT_FILENO))
             fd = STDOUT_FILENO;
         else
         if (isatty(STDERR_FILENO))
             fd = STDERR_FILENO;
         else
         if (isatty(STDIN_FILENO))
             fd = STDIN_FILENO;
         else
             close_me = fd = open("/dev/tty", O_RDONLY);
     }
     win.ws_row = 0;
     win.ws_col = 0;
     /* I've seen ioctl returning 0, but row/col is (still?) 0.
      * We treat that as an error too.  */
     err = ioctl(fd, TIOCGWINSZ, &win) != 0 || win.ws_row == 0;
     if (height)
         *height = wh_helper(win.ws_row, 24, "LINES", &err);
     if (width)
         *width = wh_helper(win.ws_col, 80, "COLUMNS", &err);
     if (close_me >= 0)
         close(close_me);
     return err;
 }
References close(), err(), fd, height(), ioctl(), isatty(), O_RDONLY, open(), STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, TIOCGWINSZ, wh_helper(), and width.
Referenced by conspy_main(), display_window_size(), get_terminal_width(), get_wh(), hexedit_main(), less_main(), show_timerstats(), telnet_main(), and top_main().
get_termios_and_make_raw()
int FAST_FUNC get_termios_and_make_raw (int fd, struct termios * newterm, struct termios * oldterm, int flags)
Definition at line 317 of file xfuncs.c.
 {
 //TODO: slattach, shell read might be adapted to use this too: grep for "tcsetattr", "[VTIME] = 0"
     int r;
     memset(oldterm, 0, sizeof(*oldterm)); /* paranoia */
     r = tcgetattr(fd, oldterm);
     *newterm = *oldterm;
     /* Turn off buffered input (ICANON)
      * Turn off echoing (ECHO)
      * and separate echoing of newline (ECHONL, normally off anyway)
      */
     newterm->c_lflag &= ~(ICANON | ECHO | ECHONL);
     if (flags & TERMIOS_CLEAR_ISIG) {
         /* dont recognize INT/QUIT/SUSP chars */
         newterm->c_lflag &= ~ISIG;
     }
     /* reads will block only if < 1 char is available */
     newterm->c_cc[VMIN] = 1;
     /* no timeout (reads block forever) */
     newterm->c_cc[VTIME] = 0;
 /* IXON, IXOFF, and IXANY:
  * IXOFF=1: sw flow control is enabled on input queue:
  * tty transmits a STOP char when input queue is close to full
  * and transmits a START char when input queue is nearly empty.
  * IXON=1: sw flow control is enabled on output queue:
  * tty will stop sending if STOP char is received,
  * and resume sending if START is received, or if any char
  * is received and IXANY=1.
  */
     if (flags & TERMIOS_RAW_CRNL_INPUT) {
         /* IXON=0: XON/XOFF chars are treated as normal chars (why we do this?) */
         /* dont convert CR to NL on input */
         newterm->c_iflag &= ~(IXON | ICRNL);
     }
     if (flags & TERMIOS_RAW_CRNL_OUTPUT) {
         /* dont convert NL to CR+NL on output */
         newterm->c_oflag &= ~(ONLCR);
         /* Maybe clear more c_oflag bits? Usually, only OPOST and ONLCR are set.
          * OPOST  Enable output processing (reqd for OLCUC and *NL* bits to work)
          * OLCUC  Map lowercase characters to uppercase on output.
          * OCRNL  Map CR to NL on output.
          * ONOCR  Don't output CR at column 0.
          * ONLRET Don't output CR.
          */
     }
     if (flags & TERMIOS_RAW_INPUT) {
 #ifndef IMAXBEL
 # define IMAXBEL 0
 #endif
 #ifndef IUCLC
 # define IUCLC 0
 #endif
 #ifndef IXANY
 # define IXANY 0
 #endif
         /* IXOFF=0: disable sending XON/XOFF if input buf is full
          * IXON=0: input XON/XOFF chars are not special
          * BRKINT=0: dont send SIGINT on break
          * IMAXBEL=0: dont echo BEL on input line too long
          * INLCR,ICRNL,IUCLC: dont convert anything on input
          */
         newterm->c_iflag &= ~(IXOFF|IXON|IXANY|BRKINT|INLCR|ICRNL|IUCLC|IMAXBEL);
     }
     return r;
 }
References BRKINT, termios::c_cc, termios::c_iflag, termios::c_lflag, termios::c_oflag, ECHO, ECHONL, fd, flags, ICANON, ICRNL, IMAXBEL, INLCR, ISIG, IUCLC, IXANY, IXOFF, IXON, memset, ONLCR, tcgetattr(), TERMIOS_CLEAR_ISIG, TERMIOS_RAW_CRNL_INPUT, TERMIOS_RAW_CRNL_OUTPUT, TERMIOS_RAW_INPUT, VMIN, and VTIME.
Referenced by less_main(), set_termios_to_raw(), and xget1().
hex2bin()
char* FAST_FUNC hex2bin (char * dst, const char * str, int count)
Definition at line 145 of file xfuncs.c.
 {
     errno = EINVAL;
     while (*str && count) {
         uint8_t val;
         uint8_t c = *str++;
         if (isdigit(c))
             val = c - '0';
         else if ((c|0x20) >= 'a' && (c|0x20) <= 'f')
             val = (c|0x20) - ('a' - 10);
         else
             return NULL;
         val <<= 4;
         c = *str;
         if (isdigit(c))
             val |= c - '0';
         else if ((c|0x20) >= 'a' && (c|0x20) <= 'f')
             val |= (c|0x20) - ('a' - 10);
         else if (c == ':' || c == '\0')
             val >>= 4;
         else
             return NULL;
         *dst++ = val;
         if (c != '\0')
             str++;
         if (*str == ':')
             str++;
         count--;
     }
     errno = (*str ? ERANGE : 0);
     return dst;
 }
References c, count, dst, EINVAL, ERANGE, errno, isdigit, NULL, str, and val.
Referenced by attach_option(), and ntp_init().
is_TERM_dumb()
int FAST_FUNC is_TERM_dumb (void)
Definition at line 306 of file xfuncs.c.
 {
     char *term = getenv("TERM");
     return term && strcmp(term, "dumb") == 0;
 }
References getenv, strcmp, and term.
Referenced by ls_main().
itoa()
char* FAST_FUNC itoa (int n)
Definition at line 124 of file xfuncs.c.
 {
     *(itoa_to_buf(n, local_buf, sizeof(local_buf) - 1)) = '\0';
     return local_buf;
 }
References itoa_to_buf(), local_buf, and n.
itoa_to_buf()
char* FAST_FUNC itoa_to_buf (int n, char * buf, unsigned buflen)
Definition at line 94 of file xfuncs.c.
 {
     if (!buflen)
         return buf;
     if (n < 0) {
         n = -n;
         *buf++ = '-';
         buflen--;
     }
     return utoa_to_buf((unsigned)n, buf, buflen);
 }
References buf, buflen, n, and utoa_to_buf().
Referenced by itoa().
ndelay_off()
int FAST_FUNC ndelay_off (int fd)
Definition at line 35 of file xfuncs.c.
 {
     int flags = fcntl(fd, F_GETFL);
     if (!(flags & O_NONBLOCK))
         return flags;
     fcntl(fd, F_SETFL, flags & ~O_NONBLOCK);
     return flags;
 }
References F_GETFL, F_SETFL, fcntl(), fd, flags, and O_NONBLOCK.
Referenced by alarm_handler(), getty_main(), handle_retr(), restore_tty(), retrieve_file_data(), setup_heredoc(), and stty_main().
ndelay_on()
int FAST_FUNC ndelay_on (int fd)
Definition at line 26 of file xfuncs.c.
 {
     int flags = fcntl(fd, F_GETFL);
     if (flags & O_NONBLOCK)
         return flags;
     fcntl(fd, F_SETFL, flags | O_NONBLOCK);
     return flags;
 }
References F_GETFL, F_SETFL, fcntl(), fd, flags, and O_NONBLOCK.
Referenced by alarm_handler(), less_main(), make_new_session(), new_peer(), pscan_main(), read_lines(), retrieve_file_data(), runsv_main(), runsvdir_main(), script_main(), setup_heredoc(), and udhcp_sp_setup().
safe_waitpid()
pid_t FAST_FUNC safe_waitpid (pid_t pid, int * wstat, int options)
Definition at line 393 of file xfuncs.c.
 {
     pid_t r;
     do
         r = waitpid(pid, wstat, options);
     while ((r == -1) && (errno == EINTR));
     return r;
 }
References EINTR, errno, pid, waitpid(), and wstat.
Referenced by custom(), doit(), openvt_main(), processorstop(), signal_handler(), spawn(), wait4pid(), wait_any_nohang(), wait_for_exitstatus(), and xargs_exec().
set_termios_to_raw()
int FAST_FUNC set_termios_to_raw (int fd, struct termios * oldterm, int flags)
Definition at line 385 of file xfuncs.c.
 {
     struct termios newterm;
     get_termios_and_make_raw(fd, &newterm, oldterm, flags);
     return tcsetattr(fd, TCSANOW, &newterm);
 }
References fd, flags, get_termios_and_make_raw(), TCSANOW, and tcsetattr().
Referenced by conspy_main(), fsck_minix_main(), hexedit_main(), more_main(), powertop_main(), rawmode(), and top_main().
strncpy_IFNAMSIZ()
char* FAST_FUNC strncpy_IFNAMSIZ (char * dst, const char * src)
Definition at line 49 of file xfuncs.c.
 {
 #ifndef IFNAMSIZ
     enum { IFNAMSIZ = 16 };
 #endif
     return strncpy(dst, src, IFNAMSIZ);
 }
References dst, IFNAMSIZ, src, and strncpy().
Referenced by add_interface(), arp_del(), arp_getdevhw(), arp_set(), brctl_main(), change_active(), d6_read_interface(), detect_link_wlan(), do_add_ioctl(), do_changename(), do_chflags(), do_del_ioctl(), do_get_ioctl(), do_ioctl_get_ifindex(), do_ioctl_get_iftype(), enslave(), ether_wake_main(), get_address(), if_fetch(), ifconfig_main(), nameif_main(), parse_address(), parse_args(), print_queuelen(), release(), set_ifreq_to_ifname(), set_ifrname_and_do_ioctl(), set_mtu(), set_qlen(), tunctl_main(), udhcp_read_interface(), and vconfig_main().
tcsetattr_stdin_TCSANOW()
int FAST_FUNC tcsetattr_stdin_TCSANOW (const struct termios * tp)
Definition at line 312 of file xfuncs.c.
 {
     return tcsetattr(STDIN_FILENO, TCSANOW, tp);
 }
References STDIN_FILENO, TCSANOW, tcsetattr(), and tp.
Referenced by alarm_handler(), cookmode(), die(), fsck_minix_main(), make_new_session(), restore_term(), set_sane_term(), set_tty_attrs(), start_shell_in_child(), and vlock_main().
utoa()
char* FAST_FUNC utoa (unsigned n)
Definition at line 116 of file xfuncs.c.
 {
     *(utoa_to_buf(n, local_buf, sizeof(local_buf) - 1)) = '\0';
     return local_buf;
 }
References local_buf, n, and utoa_to_buf().
Referenced by addgroup_wrapper(), chpst_main(), expand_one_var(), get_drv_info(), get_local_var_value(), getgrgid(), getpwuid(), gid2group_utoa(), header_verbose_list(), init(), multiconvert(), open_mdev_log(), pidof_main(), policy_name(), process_action(), ps_main(), runsvdir_main(), startservice(), tcpudpsvd_main(), uid2uname_utoa(), and wait_for_seqfile().
utoa_to_buf()
char* FAST_FUNC utoa_to_buf (unsigned n, char * buf, unsigned buflen)
Definition at line 62 of file xfuncs.c.
 {
     unsigned i, out, res;
     if (buflen) {
         out = 0;
         BUILD_BUG_ON(sizeof(n) != 4 && sizeof(n) != 8);
         if (sizeof(n) == 4)
         // 2^32-1 = 4294967295
             i = 1000000000;
 #if UINT_MAX > 0xffffffff /* prevents warning about "const too large" */
         else
         if (sizeof(n) == 8)
         // 2^64-1 = 18446744073709551615
             i = 10000000000000000000;
 #endif
         for (; i; i /= 10) {
             res = n / i;
             n = n % i;
             if (res || out || i == 1) {
                 if (--buflen == 0)
                     break;
                 out++;
                 *buf++ = '0' + res;
             }
         }
     }
     return buf;
 }
References buf, buflen, BUILD_BUG_ON, i, n, and out().
Referenced by itoa_to_buf(), startservice(), utoa(), and write_pidfile().
wait4pid()
int FAST_FUNC wait4pid (pid_t pid)
Definition at line 409 of file xfuncs.c.
 {
     int status;
     if (pid <= 0) {
         /*errno = ECHILD; -- wrong. */
         /* we expect errno to be already set from failed [v]fork/exec */
         return -1;
     }
     if (safe_waitpid(pid, &status, 0) == -1)
         return -1;
     if (WIFEXITED(status))
         return WEXITSTATUS(status);
     if (WIFSIGNALED(status))
         return WTERMSIG(status) + 0x180;
     return 0;
 }
References pid, safe_waitpid(), status, WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by edit_file(), parse(), and spawn_and_wait().
wait_any_nohang()
pid_t FAST_FUNC wait_any_nohang (int * wstat)
Definition at line 403 of file xfuncs.c.
 {
     return safe_waitpid(-1, wstat, WNOHANG);
 }
References safe_waitpid(), WNOHANG, and wstat.
Referenced by check_errors_in_children(), handle_sigchld(), reap_child(), runsv_main(), runsvdir_main(), sig_child_handler(), stop_handler(), and xargs_exec().
wh_helper()
static int wh_helper (int value, int def_val, const char * env_name, int * err) static
Definition at line 235 of file xfuncs.c.
 {
     /* Envvars override even if "value" from ioctl is valid (>0).
      * Rationale: it's impossible to guess what user wants.
      * For example: "man CMD | ...": should "man" format output
      * to stdout's width? stdin's width? /dev/tty's width? 80 chars?
      * We _cant_ know it. If "..." saves text for e.g. email,
      * then it's probably 80 chars.
      * If "..." is, say, "grep -v DISCARD | $PAGER", then user
      * would prefer his tty's width to be used!
      *
      * Since we don't know, at least allow user to do this:
      * "COLUMNS=80 man CMD | ..."
      */
     char *s = getenv(env_name);
     if (s) {
         value = atoi(s);
         /* If LINES/COLUMNS are set, pretend that there is
          * no error getting w/h, this prevents some ugly
          * cursor tricks by our callers */
         *err = 0;
     }
     if (value <= 1 || value >= 30000)
         value = def_val;
     return value;
 }
References atoi(), err(), getenv, s, and value.
Referenced by get_terminal_width_height().
Variable Documentation
local_buf
char local_buf[sizeof(int) *3] static
Definition at line 113 of file xfuncs.c.
Referenced by itoa(), and utoa().