Fennix: Userspace/musl/include/stdlib.h File Reference
stdlib.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct div_t
struct ldiv_t
struct lldiv_t
Macros
#define NULL ((void*)0)
#define __NEED_size_t
#define __NEED_wchar_t
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define MB_CUR_MAX (__ctype_get_mb_cur_max())
#define RAND_MAX (0x7fffffff)
Functions
int atoi (const char *)
long atol (const char *)
long long atoll (const char *)
double atof (const char *)
float strtof (const char *__restrict, char **__restrict)
double strtod (const char *__restrict, char **__restrict)
long double strtold (const char *__restrict, char **__restrict)
long strtol (const char *__restrict, char **__restrict, int)
unsigned long strtoul (const char *__restrict, char **__restrict, int)
long long strtoll (const char *__restrict, char **__restrict, int)
unsigned long long strtoull (const char *__restrict, char **__restrict, int)
int rand (void)
void srand (unsigned)
void * malloc (size_t)
The standard function.
void * calloc (size_t, size_t)
The standard function.
void * realloc (void *, size_t)
The standard function.
void free (void *)
The standard function.
void * aligned_alloc (size_t, size_t)
_Noreturn void abort (void)
int atexit (void(*)(void))
_Noreturn void exit (int)
_Noreturn void _Exit (int)
int at_quick_exit (void(*)(void))
_Noreturn void quick_exit (int)
char * getenv (const char *)
int system (const char *)
void * bsearch (const void *, const void *, size_t, size_t, int(*)(const void *, const void *))
void qsort (void *, size_t, size_t, int(*)(const void *, const void *))
int abs (int)
long labs (long)
long long llabs (long long)
div_t div (int, int)
ldiv_t ldiv (long, long)
lldiv_t lldiv (long long, long long)
int mblen (const char *, size_t)
int mbtowc (wchar_t *__restrict, const char *__restrict, size_t)
int wctomb (char *, wchar_t)
size_t mbstowcs (wchar_t *__restrict, const char *__restrict, size_t)
size_t wcstombs (char *__restrict, const wchar_t *__restrict, size_t)
size_t __ctype_get_mb_cur_max (void)
Data Structure Documentation
div_t
struct div_t
Definition at line 64 of file stdlib.h.
Data Fields
int quot
int rem
ldiv_t
struct ldiv_t
Definition at line 65 of file stdlib.h.
Data Fields
long quot
long rem
lldiv_t
struct lldiv_t
Definition at line 66 of file stdlib.h.
Data Fields
long long quot
long long rem
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 18 of file stdlib.h.
__NEED_wchar_t
#define __NEED_wchar_t
Definition at line 19 of file stdlib.h.
EXIT_FAILURE
#define EXIT_FAILURE 1
Definition at line 78 of file stdlib.h.
EXIT_SUCCESS
#define EXIT_SUCCESS 0
Definition at line 79 of file stdlib.h.
MB_CUR_MAX
#define MB_CUR_MAX (__ctype_get_mb_cur_max())
Definition at line 82 of file stdlib.h.
NULL
#define NULL ((void*)0)
Definition at line 15 of file stdlib.h.
RAND_MAX
#define RAND_MAX (0x7fffffff)
Definition at line 84 of file stdlib.h.
Function Documentation
__ctype_get_mb_cur_max()
size_t __ctype_get_mb_cur_max (void)
Definition at line 4 of file __ctype_get_mb_cur_max.c.
 {
     return MB_CUR_MAX;
 }
References MB_CUR_MAX.
_Exit()
_Noreturn void _Exit (int ec)
Definition at line 4 of file _Exit.c.
 {
     __syscall(SYS_exit_group, ec);
     for (;;) __syscall(SYS_exit, ec);
 }
References __syscall.
Referenced by _exit(), abort(), exit(), and quick_exit().
abort()
_Noreturn void abort (void)
Definition at line 22 of file stdlib.cpp.
 {
     error("abort() called");
     CPU::Stop();
     __builtin_unreachable();
 }
References __abort_lock, __block_all_sigs(), __pthread_self, __syscall, _Exit(), _NSIG, a_crash, LOCK, SIG_DFL, SIG_UNBLOCK, SIGABRT, SIGKILL, and syscall1().
abs()
int abs (int i)
Definition at line 19 of file fcts.c.
 { return i < 0 ? -i : i; }
References i.
Referenced by ltoa().
aligned_alloc()
void* aligned_alloc (size_t align, size_t len)
Definition at line 5 of file aligned_alloc.c.
 {
     if ((align & -align) != align) {
         errno = EINVAL;
         return 0;
     }
     if (len > SIZE_MAX - align || align >= (1ULL<<31)*UNIT) {
         errno = ENOMEM;
         return 0;
     }
     if (DISABLE_ALIGNED_ALLOC) {
         errno = ENOMEM;
         return 0;
     }
     if (align <= UNIT) align = UNIT;
     unsigned char *p = malloc(len + align - UNIT);
     if (!p)
         return 0;
     struct meta *g = get_meta(p);
     int idx = get_slot_index(p);
     size_t stride = get_stride(g);
     unsigned char *start = g->mem->storage + stride*idx;
     unsigned char *end = g->mem->storage + stride*(idx+1) - IB;
     size_t adj = -(uintptr_t)p & (align-1);
     if (!adj) {
         set_size(p, end, len);
         return p;
     }
     p += adj;
     uint32_t offset = (size_t)(p-g->mem->storage)/UNIT;
     if (offset <= 0xffff) {
         *(uint16_t *)(p-2) = offset;
         p[-4] = 0;
     } else {
         // use a 32-bit offset if 16-bit doesn't fit. for this,
         // 16-bit field must be zero, [-4] byte nonzero.
         *(uint16_t *)(p-2) = 0;
         *(uint32_t *)(p-8) = offset;
         p[-4] = 1;
     }
     p[-3] = idx;
     set_size(p, end, len);
     // store offset to aligned enframing. this facilitates cycling
     // offset and also iteration of heap for debugging/measurement.
     // for extreme overalignment it won't fit but these are classless
     // allocations anyway.
     *(uint16_t *)(start - 2) = (size_t)(p-start)/UNIT;
     start[-3] = 7<<5;
     return p;
 }
References __aligned_alloc_replaced, __bin_chunk(), __malloc_replaced, C_INUSE, chunk::csize, DISABLE_ALIGNED_ALLOC, EINVAL, ENOMEM, errno, get_meta(), get_slot_index(), get_stride(), IB, idx, IS_MMAPPED, len, malloc, meta::mem, mem, MEM_TO_CHUNK, n, NEXT_CHUNK, p, chunk::psize, set_size(), SIZE_ALIGN, SIZE_MAX, start(), group::storage, and UNIT.
Referenced by memalign(), and posix_memalign().
at_quick_exit()
int at_quick_exit (void(*)(void) func)
Definition at line 25 of file at_quick_exit.c.
 {
     int r = 0;
     LOCK(lock);
     if (count == 32) r = -1;
     else funcs[count++] = func;
     UNLOCK(lock);
     return r;
 }
References count, func(), funcs, LOCK, lock, and UNLOCK.
atexit()
int atexit (void(*)(void) function)
Definition at line 16 of file lib.c.
 {
     return 1;
 }
References __cxa_atexit(), call(), and func().
atof()
double atof (const char * String)
Definition at line 602 of file convert.cpp.
 {
     // Originally from https://github.com/GaloisInc/minlibc/blob/master/atof.c
     /*
     Copyright (c) 2014 Galois Inc.
     All rights reserved.
     Redistribution and use in source and binary forms, with or without
     modification, are permitted provided that the following conditions
     are met:
       * Redistributions of source code must retain the above copyright
         notice, this list of conditions and the following disclaimer.
       * Redistributions in binary form must reproduce the above copyright
         notice, this list of conditions and the following disclaimer in
         the documentation and/or other materials provided with the
         distribution.
       * Neither the name of Galois, Inc. nor the names of its contributors
         may be used to endorse or promote products derived from this
         software without specific prior written permission.
     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
     IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
     TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
     PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
     OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
     EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
     PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
     PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
     LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
     NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
     */
     double a = 0.0;
     int e = 0;
     int c;
     while ((c = *String++) != '\0' && isdigit(c))
     {
         a = a * 10.0 + (c - '0');
     }
     if (c == '.')
     {
         while ((c = *String++) != '\0' && isdigit(c))
         {
             a = a * 10.0 + (c - '0');
             e = e - 1;
         }
     }
     if (c == 'e' || c == 'E')
     {
         int sign = 1;
         int i = 0;
         c = *String++;
         if (c == '+')
             c = *String++;
         else if (c == '-')
         {
             c = *String++;
             sign = -1;
         }
         while (isdigit(c))
         {
             i = i * 10 + (c - '0');
             c = *String++;
         }
         e += i * sign;
     }
     while (e > 0)
     {
         a *= 10.0;
         e--;
     }
     while (e < 0)
     {
         a *= 0.1;
         e++;
     }
     return a;
 }
References i, Length, strlen, and strtod().
atoi()
int atoi (const char * String)
Definition at line 589 of file convert.cpp.
 {
     uint64_t Length = strlen((char *)String);
     int OutBuffer = 0;
     int Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (String[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References i, isdigit, isspace, Length, n, and strlen.
atol()
long atol (const char * s)
Definition at line 4 of file atol.c.
 {
     long n=0;
     int neg=0;
     while (isspace(*s)) s++;
     switch (*s) {
     case '-': neg=1;
     case '+': s++;
     }
     /* Compute n as a negative number to avoid overflow on LONG_MIN */
     while (isdigit(*s))
         n = 10*n - (*s++ - '0');
     return neg ? n : -n;
 }
References isdigit, isspace, and n.
atoll()
long long atoll (const char * s)
Definition at line 4 of file atoll.c.
 {
     long long n=0;
     int neg=0;
     while (isspace(*s)) s++;
     switch (*s) {
     case '-': neg=1;
     case '+': s++;
     }
     /* Compute n as a negative number to avoid overflow on LLONG_MIN */
     while (isdigit(*s))
         n = 10*n - (*s++ - '0');
     return neg ? n : -n;
 }
References isdigit, isspace, and n.
bsearch()
void* bsearch (const void * key, const void * base, size_t nel, size_t width, int(*)(const void *, const void *) cmp)
Definition at line 3 of file bsearch.c.
 {
     void *try;
     int sign;
     while (nel > 0) {
         try = (char *)base + width*(nel/2);
         sign = cmp(key, try);
         if (sign < 0) {
             nel /= 2;
         } else if (sign > 0) {
             base = (char *)try + width;
             nel -= nel/2+1;
         } else {
             return try;
         }
     }
     return NULL;
 }
References cmp(), and NULL.
Referenced by catgets().
div()
div_t div (int num, int den)
Definition at line 3 of file div.c.
 {
     return (div_t){ num/den, num%den };
 }
Referenced by WI_drawTime().
exit()
_Noreturn void exit (int status)
Definition at line 21 of file lib.c.
 {
     _exit(status);
 }
References __funcs_on_exit(), __libc_exit_fini(), __stdio_exit(), and _Exit().
getenv()
char* getenv (const char * name)
Definition at line 44 of file lib.c.
 {
     char **env = environ;
     if (env == NULL)
         return NULL;
     size_t len = strlen(name);
     while (*env != NULL)
     {
         if ((strncmp(*env, name, len) == 0) && ((*env)[len] == '='))
             return &(*env)[len + 1];
         ++env;
     }
 }
References __environ, __strchrnul(), and strncmp().
labs()
long labs (long a)
Definition at line 3 of file labs.c.
 {
     return a>0 ? a : -a;
 }
ldiv()
ldiv_t ldiv (long num, long den)
Definition at line 3 of file ldiv.c.
 {
     return (ldiv_t){ num/den, num%den };
 }
llabs()
long long llabs (long long a)
Definition at line 3 of file llabs.c.
 {
     return a>0 ? a : -a;
 }
lldiv()
lldiv_t lldiv (long long num, long long den)
Definition at line 3 of file lldiv.c.
 {
     return (lldiv_t){ num/den, num%den };
 }
mblen()
int mblen (const char * s, size_t n)
Definition at line 3 of file mblen.c.
 {
     return mbtowc(0, s, n);
 }
References mbtowc(), and n.
Referenced by __getopt_long_core().
mbstowcs()
size_t mbstowcs (wchar_t * __restrict, const char * __restrict, size_t)
Referenced by __wcsftime_l(), and is_valid_hostname().
mbtowc()
int mbtowc (wchar_t * __restrict, const char * __restrict, size_t)
Referenced by __fgetwc_unlocked_internal(), getopt(), match_bracket(), mblen(), parse_atom(), parse_bracket_terms(), pat_next(), str_next(), sw_write(), and wprintf_core().
qsort()
void qsort (void * , size_t , size_t , int(*)(const void *, const void *))
Referenced by __lookup_name(), glob(), parse_bracket(), and scandir().
quick_exit()
_Noreturn void quick_exit (int code)
Definition at line 7 of file quick_exit.c.
 {
     __funcs_on_quick_exit();
     _Exit(code);
 }
References __funcs_on_quick_exit(), and _Exit().
rand()
int rand (void)
Definition at line 11 of file rand.c.
 {
     seed = 6364136223846793005ULL*seed + 1;
     return seed>>33;
 }
References seed.
srand()
void srand (unsigned s)
Definition at line 6 of file rand.c.
 {
     seed = s-1;
 }
References seed.
strtod()
double strtod (const char * __restrict, char ** __restrict)
Referenced by atof(), and strtod_l().
strtof()
float strtof (const char * __restrict, char ** __restrict)
Referenced by strtof_l().
strtol()
long strtol (const char * __restrict, char ** __restrict, int base)
Definition at line 203 of file convert.cpp.
 {
     const char *s;
     long acc, cutoff;
     int c;
     int neg, any, cutlim;
     s = str;
     do
     {
         c = *s++;
     } while (isspace(c));
     if (c == '-')
     {
         neg = 1;
         c = *s++;
     }
     else
     {
         neg = 0;
         if (c == '+')
             c = *s++;
     }
     if ((base == 0 || base == 16) && c == '0' && (*s == 'x' || *s == 'X'))
     {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     cutoff = neg ? LONG_MIN : LONG_MAX;
     cutlim = s_cst(int, cutoff % base);
     cutoff /= base;
     for (acc = 0, any = 0;; c = *s++)
     {
         if (isdigit(c))
             c -= '0';
         else if (isalpha(c))
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         else
             break;
         if (c >= base)
             break;
         if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
             any = -1;
         else
         {
             any = 1;
             acc *= base;
             acc += c;
         }
     }
     if (any < 0)
     {
         acc = neg ? LONG_MIN : LONG_MAX;
     }
     else if (neg)
         acc = -acc;
     if (endptr != 0)
         *endptr = (char *)(any ? s - 1 : str);
     return (acc);
 }
strtold()
long double strtold (const char * __restrict, char ** __restrict)
Referenced by strtold_l().
strtoll()
long long strtoll (const char * __restrict, char ** __restrict, int)
strtoul()
unsigned long strtoul (const char * __restrict, char ** __restrict, int base)
Definition at line 268 of file convert.cpp.
 {
     const char *s;
     unsigned long acc, cutoff;
     int c;
     int neg, any, cutlim;
     s = str;
     do
     {
         c = *s++;
     } while (isspace(c));
     if (c == '-')
     {
         neg = 1;
         c = *s++;
     }
     else
     {
         neg = 0;
         if (c == '+')
             c = *s++;
     }
     if ((base == 0 || base == 16) && c == '0' && (*s == 'x' || *s == 'X'))
     {
         c = s[1];
         s += 2;
         base = 16;
     }
     if (base == 0)
         base = c == '0' ? 8 : 10;
     cutoff = neg ? LONG_MIN : LONG_MAX;
     cutlim = s_cst(int, cutoff % base);
     cutoff /= base;
     for (acc = 0, any = 0;; c = *s++)
     {
         if (isdigit(c))
             c -= '0';
         else if (isalpha(c))
             c -= isupper(c) ? 'A' - 10 : 'a' - 10;
         else
             break;
         if (c >= base)
             break;
         if (any < 0 || acc > cutoff || (acc == cutoff && c > cutlim))
             any = -1;
         else
         {
             any = 1;
             acc *= base;
             acc += c;
         }
     }
     if (any < 0)
     {
         acc = neg ? LONG_MIN : LONG_MAX;
     }
     else if (neg)
         acc = -acc;
     if (endptr != 0)
         *endptr = (char *)(any ? s - 1 : str);
     return (acc);
 }
strtoull()
unsigned long long strtoull (const char * __restrict, char ** __restrict, int)
Referenced by __lookup_ipliteral().
system()
int system (const char * command)
Definition at line 67 of file lib.c.
 {
     return -1;
 }
References __environ, EINTR, errno, NULL, posix_spawn(), POSIX_SPAWN_SETSIGDEF, POSIX_SPAWN_SETSIGMASK, posix_spawnattr_destroy(), posix_spawnattr_init(), posix_spawnattr_setflags(), posix_spawnattr_setsigdefault(), posix_spawnattr_setsigmask(), pthread_testcancel(), ret, SIG_BLOCK, SIG_IGN, SIG_SETMASK, sigaddset(), SIGCHLD, sigemptyset(), SIGINT, sigprocmask(), SIGQUIT, and waitpid().
wcstombs()
size_t wcstombs (char * __restrict, const wchar_t * __restrict, size_t)
wctomb()
int wctomb (char * s, wchar_t wc)
Definition at line 4 of file wctomb.c.
 {
     if (!s) return 0;
     return wcrtomb(s, wc, 0);
 }
References wcrtomb().
Referenced by __fputwc_unlocked(), printf_core(), and vfwscanf().