Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/f2fs.c File Reference
f2fs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct f2fs_super_block
Macros
#define F2FS_MAGIC 0xF2F52010
#define F2FS_UUID_SIZE 16
#define F2FS_LABEL_SIZE 512
#define F2FS_LABEL_BYTES 1024
#define F2FS_SB1_OFFSET 0x400
Functions
int FAST_FUNC volume_id_probe_f2fs (struct volume_id *id)
Variables
struct f2fs_super_block PACKED
Data Structure Documentation
f2fs_super_block
struct f2fs_super_block
Definition at line 31 of file f2fs.c.
Data Fields
uint64_t block_count
uint32_t checksum_offset
uint32_t cp_blkaddr
uint32_t log_blocks_per_seg
uint32_t log_blocksize
uint32_t log_sectors_per_block
uint32_t log_sectorsize
uint32_t magic
uint32_t main_blkaddr
uint16_t major_ver
uint32_t meta_ino
uint16_t minor_ver
uint32_t nat_blkaddr
uint32_t node_ino
uint32_t root_ino
uint32_t secs_per_zone
uint32_t section_count
uint32_t segment0_blkaddr
uint32_t segment_count
uint32_t segment_count_ckpt
uint32_t segment_count_main
uint32_t segment_count_nat
uint32_t segment_count_sit
uint32_t segment_count_ssa
uint32_t segs_per_sec
uint32_t sit_blkaddr
uint32_t ssa_blkaddr
uint8_t uuid[F2FS_UUID_SIZE]
uint16_t volume_name[F2FS_LABEL_SIZE]
Macro Definition Documentation
F2FS_LABEL_BYTES
#define F2FS_LABEL_BYTES 1024
Definition at line 25 of file f2fs.c.
F2FS_LABEL_SIZE
#define F2FS_LABEL_SIZE 512
Definition at line 24 of file f2fs.c.
F2FS_MAGIC
#define F2FS_MAGIC 0xF2F52010
Definition at line 22 of file f2fs.c.
F2FS_SB1_OFFSET
#define F2FS_SB1_OFFSET 0x400
Definition at line 26 of file f2fs.c.
F2FS_UUID_SIZE
#define F2FS_UUID_SIZE 16
Definition at line 23 of file f2fs.c.
Function Documentation
volume_id_probe_f2fs()
int FAST_FUNC volume_id_probe_f2fs (struct volume_id * id)
Definition at line 66 of file f2fs.c.
 {
     struct f2fs_super_block *sb;
     // Go for primary super block (ignore second sb)
     dbg("f2fs: probing at offset 0x%x", F2FS_SB1_OFFSET);
     sb = volume_id_get_buffer(id, F2FS_SB1_OFFSET, sizeof(*sb));
     if (!sb)
         return -1;
     if (sb->magic != cpu_to_le32(F2FS_MAGIC))
         return -1;
     IF_FEATURE_BLKID_TYPE(id->type = "f2fs");
     // For version 1.0 we don't know sb structure and can't set label/uuid
     if (sb->major_ver == cpu_to_le16(1) && sb->minor_ver == cpu_to_le16(0))
         return 0;
     volume_id_set_label_unicode16(id, (uint8_t *)sb->volume_name,
                       LE, MIN(F2FS_LABEL_BYTES, VOLUME_ID_LABEL_SIZE));
     volume_id_set_uuid(id, sb->uuid, UUID_DCE);
     return 0;
 }
References cpu_to_le16, cpu_to_le32, dbg, F2FS_LABEL_BYTES, F2FS_MAGIC, F2FS_SB1_OFFSET, LE, f2fs_super_block::magic, f2fs_super_block::major_ver, MIN, f2fs_super_block::minor_ver, f2fs_super_block::uuid, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_unicode16(), volume_id_set_uuid(), and f2fs_super_block::volume_name.
Variable Documentation
PACKED
struct f2fs_super_block PACKED