Fennix Userspace: Userspace/mlibc/options/ansi/include/string.h File Reference
string.h File Reference
#include <mlibc-config.h>
#include <bits/null.h>
#include <bits/size_t.h>
Functions
void * memcpy (void *__restrict dest, const void *__restrict src, size_t size)
void * memmove (void *dest, const void *src, size_t size)
char * strcpy (char *__restrict dest, const char *src)
char * strncpy (char *__restrict dest, const char *src, size_t max_size)
char * strcat (char *__restrict dest, const char *__restrict src)
char * strncat (char *__restrict dest, const char *__restrict src, size_t max_size)
int memcmp (const void *a, const void *b, size_t size)
int strcmp (const char *a, const char *b)
int strcoll (const char *a, const char *b)
int strncmp (const char *a, const char *b, size_t max_size)
size_t strxfrm (char *__restrict dest, const char *__restrict src, size_t max_size)
void * memchr (const void *s, int c, size_t size)
char * strchr (const char *s, int c)
size_t strcspn (const char *s, const char *chrs)
char * strpbrk (const char *s, const char *chrs)
char * strrchr (const char *s, int c)
size_t strspn (const char *s, const char *chrs)
char * strstr (const char *pattern, const char *s)
char * strtok (char *__restrict s, const char *__restrict delimiter)
char * strchrnul (const char *, int)
void * memset (void *dest, int c, size_t size)
char * strerror (int errnum)
size_t strlen (const char *s)
int strerror_r (int, char *, size_t)
void * mempcpy (void *, const void *, size_t)
int strverscmp (const char *l0, const char *r0)
int ffsl (long i)
int ffsll (long long i)
void * memmem (const void *, size_t, const void *, size_t)
Function Documentation
ffsl()
int ffsl (long i)
Definition at line 59 of file strings-stubs.cpp.
                  {
 #ifdef __mlibc_ffsl
     return __mlibc_ffsl(i);
 #else
     return ffs_generic<long>(i);
 #endif
 }
References i.
Referenced by main().
ffsll()
int ffsll (long long i)
Definition at line 67 of file strings-stubs.cpp.
{
 #ifdef __mlibc_ffsll
     return __mlibc_ffsll(i);
 #else
     return ffs_generic<long long>(i);
 #endif
 }
References i.
Referenced by main().
memchr()
void* memchr (const void * s, int c, size_t size)
Definition at line 111 of file string-stubs.cpp.
{
     auto s_bytes = static_cast<const unsigned char *>(s);
     for(size_t i = 0; i < size; i++)
         if(s_bytes[i] == static_cast<unsigned char>(c))
             return const_cast<unsigned char *>(s_bytes + i);
     return nullptr;
 }
References c, i, and size.
Referenced by main(), we_askshell(), and mlibc::abstract_file::write().
memcmp()
int memcmp (const void * a, const void * b, size_t size)
Definition at line 54 of file string-stubs.cpp.
{
     for(size_t i = 0; i < size; i++) {
         auto a_byte = static_cast<const unsigned char *>(a)[i];
         auto b_byte = static_cast<const unsigned char *>(b)[i];
         if(a_byte < b_byte)
             return -1;
         if(a_byte > b_byte)
             return 1;
     }
     return 0;
 }
References b, i, and size.
Referenced by main(), and test_affinity().
memcpy()
void* memcpy (void *__restrict dest, const void *__restrict src, size_t size)
Definition at line 105 of file essential.cpp.
{
     return forward_copy(dest, src, n);
 }
References anonymous_namespace{essential.cpp}::forward_copy(), and n.
memmem()
void* memmem (const void * hs, size_t haystackLen, const void * nd, size_t needleLen)
Definition at line 514 of file string-stubs.cpp.
{
     const char *haystack = static_cast<const char *>(hs);
     const char *needle = static_cast<const char *>(nd);
     for (size_t i = 0; i < haystackLen; i++) {
         bool found = true;
         for (size_t j = 0; j < needleLen; j++) {
             if (i + j >= haystackLen || haystack[i + j] != needle[j]) {
                 found = false;
                 break;
             }
         }
         if(found)
             return const_cast<char *>(&haystack[i]);
     }
     return nullptr;
 }
References i, and j.
Referenced by main().
memmove()
void* memmove (void * dest, const void * src, size_t size)
Definition at line 290 of file memop.c.
 {
 #ifdef __GNUC__
     typedef __attribute__((__may_alias__)) size_t WT;
 #define WS (sizeof(WT))
 #endif
     char *d = dest;
     const char *s = src;
     if (d == s)
         return d;
     if ((uintptr_t)s - (uintptr_t)d - n <= -2 * n)
         return memcpy(d, s, n);
     if (d < s)
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)d % WS)
             {
                 if (!n--)
                     return dest;
                 *d++ = *s++;
             }
             for (; n >= WS; n -= WS, d += WS, s += WS)
                 *(WT *)d = *(WT *)s;
         }
 #endif
         for (; n; n--)
             *d++ = *s++;
     }
     else
     {
 #ifdef __GNUC__
         if ((uintptr_t)s % WS == (uintptr_t)d % WS)
         {
             while ((uintptr_t)(d + n) % WS)
             {
                 if (!n--)
                     return dest;
                 d[n] = s[n];
             }
             while (n >= WS)
                 n -= WS, *(WT *)(d + n) = *(WT *)(s + n);
         }
 #endif
         while (n)
             n--, d[n] = s[n];
     }
     return dest;
 }
References anonymous_namespace{essential.cpp}::forward_copy(), i, and size.
mempcpy()
void* mempcpy (void * dest, const void * src, size_t len)
Definition at line 472 of file string-stubs.cpp.
{
     return (char *)memcpy(dest, src, len) + len;
 }
References memcpy().
Referenced by writev().
memset()
void* memset (void * dest, int c, size_t size)
Definition at line 99 of file fcts.c.
 {
     uint8_t *p = s;
     while (n--)
         *p++ = c;
 }
References __attribute__(), c, mlibc::count, i, k, n, and p.
Referenced by __FD_ZERO(), __mlibc_cpu_zero(), ObjectRepository::_fetchFromFile(), accessDtv(), allocateTcb(), AM_clearFB(), BuildNewTic(), calloc(), DG_Init(), do_scanf(), G_BuildTiccmd(), G_DoLoadLevel(), G_PlayerFinishLevel(), G_PlayerReborn(), GenerateTextureHashTable(), GetSectorAtNullAddress(), I_Error(), I_InitGraphics(), I_Stretch5x(), initTlsObjects(), ld_load(), LoadResponseFile(), M_ExtractFileBase(), main(), P_LoadBlockMap(), P_LoadLineDefs(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_ReadSaveGameHeader(), P_SpawnMobj(), P_SpawnSpecials(), P_UpdateSpecials(), P_WriteSaveGameHeader(), PadRejectArray(), ParseDMXConfig(), pthread_barrier_destroy(), pthread_condattr_destroy(), pthread_mutexattr_destroy(), R_CheckPlane(), R_ClearPlanes(), R_FindPlane(), R_GenerateLookup(), R_InitSpriteDefs(), R_PrecacheLevel(), regcomp(), SHA1_Final(), socket_setup(), stpncpy(), mlibc::sys_getrusage(), mlibc::sys_pselect(), tre_mem_alloc_impl(), tre_mem_new_impl(), tre_tnfa_run_backtrack(), tre_tnfa_run_parallel(), verify_decode(), W_GenerateHashTable(), and WritePCXfile().
strcat()
char* strcat (char *__restrict dest, const char *__restrict src)
Definition at line 37 of file string-stubs.cpp.
{
     strcpy(dest + strlen(dest), src);
     return dest;
 }
References strcpy(), and strlen().
strchr()
char* strchr (const char * s, int c)
Definition at line 103 of file string.c.
 {
     size_t len = strlen(s);
     for (size_t i = 0; i < len; i++)
         if (s[i] == c)
             return (char *)s + i;
     return NULL;
 }
References c, and i.
Referenced by strcspn(), strpbrk(), strspn(), and strtok_r().
strchrnul()
char* strchrnul (const char * s, int c)
Definition at line 220 of file string-stubs.cpp.
{
     size_t i = 0;
     while(s[i]) {
         if(s[i] == c)
             return const_cast<char *>(s + i);
         i++;
     }
     return const_cast<char *>(s + i);
 }
References c, and i.
Referenced by expand_tilde(), mlibc::lookup_name_dns(), and anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname().
strcmp()
int strcmp (const char * a, const char * b)
Definition at line 106 of file fcts.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
References b, i, and r.
Referenced by callback(), check_root_group(), CheckDirectoryHasIWAD(), cmpstringp(), ELFLookupSymbol(), ends_with(), getgrnam(), getgrnam_r(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), getpwnam(), getpwnam_r(), GUS_WriteConfig(), iconv_open(), InitGameVersion(), M_GetSaveGameDir(), M_SaveSelect(), M_SetConfigDir(), M_StringEndsWith(), main(), P_ReadSaveGameHeader(), mlibc::query_locale_description(), SearchCollection(), sort(), StatDump(), strcoll(), test1(), test3(), test4(), test5(), and test7().
strcoll()
int strcoll (const char * a, const char * b)
Definition at line 81 of file string-stubs.cpp.
{
     // TODO: strcoll should take "LC_COLLATE" into account.
     return strcmp(a, b);
 }
References b, and strcmp().
Referenced by alphasort().
strcpy()
char* strcpy (char *__restrict dest, const char * src)
Definition at line 14 of file string-stubs.cpp.
{
     char *dest_bytes = (char *)dest;
     char *src_bytes = (char *)src;
     while(*src_bytes)
         *(dest_bytes++) = *(src_bytes++);
     *dest_bytes = 0;
     return dest;
 }
Referenced by ctermid(), posix_spawn_file_actions_addopen(), realpath(), and strcat().
strcspn()
size_t strcspn (const char * s, const char * chrs)
Definition at line 129 of file string-stubs.cpp.
{
     size_t n = 0;
     while(true) {
         if(!s[n] || strchr(chrs, s[n]))
             return n;
         n++;
     }
 }
References n, and strchr().
strerror()
char* strerror (int errnum)
Definition at line 340 of file string-stubs.cpp.
                       {
     const char *s;
     switch(e) {
     case EAGAIN: s = "Operation would block (EAGAIN)"; break;
     case EACCES: s = "Access denied (EACCESS)"; break;
     case EBADF:  s = "Bad file descriptor (EBADF)"; break;
     case EEXIST: s = "File exists already (EEXIST)"; break;
     case EFAULT: s = "Access violation (EFAULT)"; break;
     case EINTR:  s = "Operation interrupted (EINTR)"; break;
     case EINVAL: s = "Invalid argument (EINVAL)"; break;
     case EIO:    s = "I/O error (EIO)"; break;
     case EISDIR: s = "Resource is directory (EISDIR)"; break;
     case ENOENT: s = "No such file or directory (ENOENT)"; break;
     case ENOMEM: s = "Out of memory (ENOMEM)"; break;
     case ENOTDIR: s = "Expected directory instead of file (ENOTDIR)"; break;
     case ENOSYS: s = "Operation not implemented (ENOSYS)"; break;
     case EPERM:  s = "Operation not permitted (EPERM)"; break;
     case EPIPE:  s = "Broken pipe (EPIPE)"; break;
     case ESPIPE: s = "Seek not possible (ESPIPE)"; break;
     case ENXIO: s = "No such device or address (ENXIO)"; break;
     case ENOEXEC: s = "Exec format error (ENOEXEC)"; break;
     case ENOSPC: s = "No space left on device (ENOSPC)"; break;
     case ENOTSOCK: s = "Socket operation on non-socket (ENOTSOCK)"; break;
     case ENOTCONN: s = "Transport endpoint is not connected (ENOTCONN)"; break;
     case EDOM: s = "Numerical argument out of domain (EDOM)"; break;
     case EILSEQ: s = "Invalid or incomplete multibyte or wide character (EILSEQ)"; break;
     case ERANGE: s = "Numerical result out of range (ERANGE)"; break;
     case E2BIG: s = "Argument list too long (E2BIG)"; break;
     case EADDRINUSE: s = "Address already in use (EADDRINUSE)"; break;
     case EADDRNOTAVAIL: s = "Cannot assign requested address (EADDRNOTAVAIL)"; break;
     case EAFNOSUPPORT: s = "Address family not supported by protocol (EAFNOSUPPORT)"; break;
     case EALREADY: s = "Operation already in progress (EALREADY)"; break;
     case EBADMSG: s = "Bad message (EBADMSG)"; break;
     case EBUSY: s = "Device or resource busy (EBUSY)"; break;
     case ECANCELED: s = "Operation canceled (ECANCELED)"; break;
     case ECHILD: s = "No child processes (ECHILD)"; break;
     case ECONNABORTED: s = "Software caused connection abort (ECONNABORTED)"; break;
     case ECONNREFUSED: s = "Connection refused (ECONNREFUSED)"; break;
     case ECONNRESET: s = "Connection reset by peer (ECONNRESET)"; break;
     case EDEADLK: s = "Resource deadlock avoided (EDEADLK)"; break;
     case EDESTADDRREQ: s = "Destination address required (EDESTADDRREQ)"; break;
     case EDQUOT: s = "Disk quota exceeded (EDQUOT)"; break;
     case EFBIG: s = "File too large (EFBIG)"; break;
     case EHOSTUNREACH: s = "No route to host (EHOSTUNREACH)"; break;
     case EIDRM: s = "Identifier removed (EIDRM)"; break;
     case EINPROGRESS: s = "Operation now in progress (EINPROGRESS)"; break;
     case EISCONN: s = "Transport endpoint is already connected (EISCONN)"; break;
     case ELOOP: s = "Too many levels of symbolic links (ELOOP)"; break;
     case EMFILE: s = "Too many open files (EMFILE)"; break;
     case EMLINK: s = "Too many links (EMLINK)"; break;
     case EMSGSIZE: s = "Message too long (EMSGSIZE)"; break;
     case EMULTIHOP: s = "Multihop attempted (EMULTIHOP)"; break;
     case ENAMETOOLONG: s = "File name too long (ENAMETOOLONG)"; break;
     case ENETDOWN: s = "Network is down (ENETDOWN)"; break;
     case ENETRESET: s = "Network dropped connection on reset (ENETRESET)"; break;
     case ENETUNREACH: s = "Network is unreachable (ENETUNREACH)"; break;
     case ENFILE: s = "Too many open files in system (ENFILE)"; break;
     case ENOBUFS: s = "No buffer space available (ENOBUFS)"; break;
     case ENODEV: s = "No such device (ENODEV)"; break;
     case ENOLCK: s = "No locks available (ENOLCK)"; break;
     case ENOLINK: s = "Link has been severed (ENOLINK)"; break;
     case ENOMSG: s = "No message of desired type (ENOMSG)"; break;
     case ENOPROTOOPT: s = "Protocol not available (ENOPROTOOPT)"; break;
     case ENOTEMPTY: s = "Directory not empty (ENOTEMPTY)"; break;
     case ENOTRECOVERABLE: s = "Sate not recoverable (ENOTRECOVERABLE)"; break;
     case ENOTSUP: s = "Operation not supported (ENOTSUP)"; break;
     case ENOTTY: s = "Inappropriate ioctl for device (ENOTTY)"; break;
     case EOVERFLOW: s = "Value too large for defined datatype (EOVERFLOW)"; break;
 #if EOPNOTSUPP != ENOTSUP
     /* these are aliases on the mlibc abi */
     case EOPNOTSUPP: s = "Operation not supported (EOPNOTSUP)"; break;
 #endif
     case EOWNERDEAD: s = "Owner died (EOWNERDEAD)"; break;
     case EPROTO: s = "Protocol error (EPROTO)"; break;
     case EPROTONOSUPPORT: s = "Protocol not supported (EPROTONOSUPPORT)"; break;
     case EPROTOTYPE: s = "Protocol wrong type for socket (EPROTOTYPE)"; break;
     case EROFS: s = "Read-only file system (EROFS)"; break;
     case ESRCH: s = "No such process (ESRCH)"; break;
     case ESTALE: s = "Stale file handle (ESTALE)"; break;
     case ETIMEDOUT: s = "Connection timed out (ETIMEDOUT)"; break;
     case ETXTBSY: s = "Text file busy (ETXTBSY)"; break;
     case EXDEV: s = "Invalid cross-device link (EXDEV)"; break;
     case ENODATA: s = "No data available (ENODATA)"; break;
     case ETIME: s = "Timer expired (ETIME)"; break;
     case ENOKEY: s = "Required key not available (ENOKEY)"; break;
     case ESHUTDOWN: s = "Cannot send after transport endpoint shutdown (ESHUTDOWN)"; break;
     case EHOSTDOWN: s = "Host is down (EHOSTDOWN)"; break;
     case EBADFD: s = "File descriptor in bad state (EBADFD)"; break;
     case ENOMEDIUM: s = "No medium found (ENOMEDIUM)"; break;
     case ENOTBLK: s = "Block device required (ENOTBLK)"; break;
     case ENONET: s = "Machine is not on the network (ENONET)"; break;
     case EPFNOSUPPORT: s = "Protocol family not supported (EPFNOSUPPORT)"; break;
     case ESOCKTNOSUPPORT: s = "Socket type not supported (ESOCKTNOSUPPORT)"; break;
     case ESTRPIPE: s = "Streams pipe error (ESTRPIPE)"; break;
     case EREMOTEIO: s = "Remote I/O error (EREMOTEIO)"; break;
     case ERFKILL: s = "Operation not possible due to RF-kill (ERFKILL)"; break;
     case EBADR: s = "Invalid request descriptor (EBADR)"; break;
     case EUNATCH: s = "Protocol driver not attached (EUNATCH)"; break;
     case EMEDIUMTYPE: s = "Wrong medium type (EMEDIUMTYPE)"; break;
     case EREMOTE: s = "Object is remote (EREMOTE)"; break;
     case EKEYREJECTED: s = "Key was rejected by service (EKEYREJECTED)"; break;
     case EUCLEAN: s = "Structure needs cleaning (EUCLEAN)"; break;
     case EBADSLT: s = "Invalid slot (EBADSLT)"; break;
     case ENOANO: s = "No anode (ENOANO)"; break;
     case ENOCSI: s = "No CSI structure available (ENOCSI)"; break;
     case ENOSTR: s = "Device not a stream (ENOSTR)"; break;
     case ETOOMANYREFS: s = "Too many references: cannot splice (ETOOMANYREFS)"; break;
     case ENOPKG: s = "Package not installed (ENOPKG)"; break;
     case EKEYREVOKED: s = "Key has been revoked (EKEYREVOKED)"; break;
     case EXFULL: s = "Exchange full (EXFULL)"; break;
     case ELNRNG: s = "Link number out of range (ELNRNG)"; break;
     case ENOTUNIQ: s = "Name not unique on network (ENOTUNIQ)"; break;
     case ERESTART: s = "Interrupted system call should be restarted (ERESTART)"; break;
     case EUSERS: s = "Too many users (EUSERS)"; break;
     default:
         s = "Unknown error code (?)";
     }
     return const_cast<char *>(s);
 }
References E2BIG, EACCES, EADDRINUSE, EADDRNOTAVAIL, EAFNOSUPPORT, EAGAIN, EALREADY, EBADF, EBADFD, EBADMSG, EBADR, EBADSLT, EBUSY, ECANCELED, ECHILD, ECONNABORTED, ECONNREFUSED, ECONNRESET, EDEADLK, EDESTADDRREQ, EDOM, EDQUOT, EEXIST, EFAULT, EFBIG, EHOSTDOWN, EHOSTUNREACH, EIDRM, EILSEQ, EINPROGRESS, EINTR, EINVAL, EIO, EISCONN, EISDIR, EKEYREJECTED, EKEYREVOKED, ELNRNG, ELOOP, EMEDIUMTYPE, EMFILE, EMLINK, EMSGSIZE, EMULTIHOP, ENAMETOOLONG, ENETDOWN, ENETRESET, ENETUNREACH, ENFILE, ENOANO, ENOBUFS, ENOCSI, ENODATA, ENODEV, ENOENT, ENOEXEC, ENOKEY, ENOLCK, ENOLINK, ENOMEDIUM, ENOMEM, ENOMSG, ENONET, ENOPKG, ENOPROTOOPT, ENOSPC, ENOSTR, ENOSYS, ENOTBLK, ENOTCONN, ENOTDIR, ENOTEMPTY, ENOTRECOVERABLE, ENOTSOCK, ENOTSUP, ENOTTY, ENOTUNIQ, ENXIO, EOPNOTSUPP, EOVERFLOW, EOWNERDEAD, EPERM, EPFNOSUPPORT, EPIPE, EPROTO, EPROTONOSUPPORT, EPROTOTYPE, ERANGE, EREMOTE, EREMOTEIO, ERESTART, ERFKILL, EROFS, ESHUTDOWN, ESOCKTNOSUPPORT, ESPIPE, ESRCH, ESTALE, ESTRPIPE, ETIME, ETIMEDOUT, ETOOMANYREFS, ETXTBSY, EUCLEAN, EUNATCH, EUSERS, EXDEV, and EXFULL.
Referenced by __assert_fail_perror(), error(), error_at_line(), main(), PrintfAgent< F >::operator()(), perror(), run_cmd(), run_test(), socket_setup(), and strerror_r().
strerror_r()
int strerror_r (int e, char * buffer, size_t bufsz)
Definition at line 463 of file string-stubs.cpp.
{
     auto s = strerror(e);
     strncpy(buffer, s, bufsz);
     // Note that strerror_r does not set errno on error!
     if(strlen(s) >= bufsz)
         return ERANGE;
     return 0;
 }
References ERANGE, strerror(), strlen(), and strncpy().
strlen()
size_t strlen (const char * s)
Definition at line 5 of file string.c.
 {
     long unsigned i = 0;
     if (str)
         while (str[i] != '\0')
             ++i;
     return i;
 }
References i.
Referenced by strchr(), strdup(), and strrchr().
strncat()
char* strncat (char *__restrict dest, const char *__restrict src, size_t max_size)
Definition at line 41 of file string-stubs.cpp.
{
     auto dest_bytes = static_cast<char *>(dest);
     auto src_bytes = static_cast<const char *>(src);
     dest_bytes += strlen(dest);
     size_t i = 0;
     while(*src_bytes && i < max_size) {
         *(dest_bytes++) = *(src_bytes++);
         i++;
     }
     *dest_bytes = 0;
     return dest;
 }
References i, max_size, and strlen().
strncmp()
int strncmp (const char * a, const char * b, size_t max_size)
Definition at line 21 of file string.c.
 {
     for (size_t i = 0; i < n; i++)
     {
         char c1 = s1[i], c2 = s2[i];
         if (c1 != c2)
             return c1 - c2;
         if (!c1)
             return 0;
     }
     return 0;
 }
References b, i, and max_size.
strncpy()
char* strncpy (char *__restrict dest, const char * src, size_t max_size)
Definition at line 22 of file string-stubs.cpp.
{
     auto dest_bytes = static_cast<char *>(dest);
     auto src_bytes = static_cast<const char *>(src);
     size_t i = 0;
     while(*src_bytes && i < max_size) {
         *(dest_bytes++) = *(src_bytes++);
         i++;
     }
     while(i < max_size) {
         *(dest_bytes++) = 0;
         i++;
     }
     return dest;
 }
References i, and max_size.
Referenced by strerror_r(), and strxfrm().
strpbrk()
char* strpbrk (const char * s, const char * chrs)
Definition at line 137 of file string-stubs.cpp.
{
     size_t n = 0;
     while(s[n]) {
         if(strchr(chrs, s[n]))
             return const_cast<char *>(s + n);
         n++;
     }
     return nullptr;
 }
References n, and strchr().
strrchr()
char* strrchr (const char * s, int c)
Definition at line 113 of file string.c.
 {
     size_t len = strlen(s);
     size_t pos = len;
     while (s[pos] != c && pos-- != 0)
         ;
     if (pos == len)
         return NULL;
     return (char *)s + pos;
 }
References c, i, and strlen().
strspn()
size_t strspn (const char * s, const char * chrs)
Definition at line 155 of file string-stubs.cpp.
{
     size_t n = 0;
     while(true) {
         if(!s[n] || !strchr(chrs, s[n]))
             return n;
         n++;
     }
 }
References n, and strchr().
strstr()
char* strstr (const char * pattern, const char * s)
Definition at line 64 of file string.c.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }
References i, and j.
strtok()
char* strtok (char *__restrict s, const char *__restrict delimiter)
Definition at line 214 of file string-stubs.cpp.
{
         static char *saved;
         return strtok_r(s, delimiter, &saved);
 }
References strtok_r().
strverscmp()
int strverscmp (const char * l0, const char * r0)
Definition at line 478 of file string-stubs.cpp.
{
     const unsigned char *l = (const unsigned char *)l0;
     const unsigned char *r = (const unsigned char *)r0;
     size_t i, dp, j;
     int z = 1;
     /* Find maximal matching prefix and track its maximal digit
      * suffix and whether those digits are all zeros. */
     for(dp = i = 0; l[i] == r[i]; i++) {
         int c = l[i];
         if(!c)
             return 0;
         if(!isdigit(c))
             dp = i + 1, z = 1;
         else if(c != '0')
             z = 0;
     }
     if(l[dp] != '0' && r[dp] != '0') {
         /* If we're not looking at a digit sequence that began
          * with a zero, longest digit string is greater. */
         for(j = i; isdigit(l[j]); j++) {
             if(!isdigit(r[j]))
                 return 1;
         }
         if(isdigit(r[j]))
             return -1;
     } else if(z && dp < i && (isdigit(l[i]) || isdigit(r[i]))) {
         /* Otherwise, if common prefix of digit sequence is
          * all zeros, digits order less than non-digits. */
         return (unsigned char)(l[i] - '0') - (unsigned char)(r[i] - '0');
     }
     return l[i] - r[i];
 }
References c, i, isdigit(), j, and r.
Referenced by main(), and versionsort().
strxfrm()
size_t strxfrm (char *__restrict dest, const char *__restrict src, size_t max_size)
Definition at line 104 of file string-stubs.cpp.
{
     size_t l = strlen(src);
     // NOTE: This might not work for non ANSI charsets.
     strncpy(dest, src, n);
     return l;
 }
References n, strlen(), and strncpy().