Fennix: Drivers/storage/ahci/ahci.hpp File Reference
ahci.hpp File Reference
#include <types.h>
Functions
EXTERNC int cxx_Panic ()
EXTERNC int cxx_Probe ()
EXTERNC int cxx_Initialize ()
EXTERNC int cxx_Finalize ()
Function Documentation
cxx_Finalize()
EXTERNC int cxx_Finalize ()
Definition at line 848 of file ac97.cpp.
 {
     PCIArray *ctx = Devices;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count++ > sizeof(Drivers) / sizeof(AC97Device *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type != 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is not I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         delete Drivers[Count++];
         ctx->Device->Header->Command |= PCI_COMMAND_INTX_DISABLE;
         ctx = (PCIArray *)ctx->Next;
     }
     for (size_t i = 0; i < sizeof(AudioID) / sizeof(dev_t); i++)
     {
         if (AudioID[i] != (dev_t)-1)
             UnregisterDevice(AudioID[i]);
     }
     return 0;
 }
References AudioID, dev_t, Devices, Drivers, i, if(), KernelLog(), NetID, PCI_COMMAND_INTX_DISABLE, PortCount, and v0::UnregisterDevice().
Referenced by DriverFinal().
cxx_Initialize()
EXTERNC int cxx_Initialize ()
We loop through all the devices and initialize them
Definition at line 797 of file ac97.cpp.
 {
     PCIArray *ctx = Devices;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count > sizeof(Drivers) / sizeof(AC97Device *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type != 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is not I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         InitializePCI(ctx->Device);
         Drivers[Count] = new AC97Device((PCIHeader0 *)ctx->Device->Header);
         /* FIXME: bad code */
         switch (Count)
         {
         case 0:
             RegisterInterruptHandler(iLine(ctx->Device), (void *)OIR(0));
             break;
         case 1:
             RegisterInterruptHandler(iLine(ctx->Device), (void *)OIR(1));
             break;
         case 2:
             RegisterInterruptHandler(iLine(ctx->Device), (void *)OIR(2));
             break;
         case 3:
             RegisterInterruptHandler(iLine(ctx->Device), (void *)OIR(3));
             break;
         default:
             break;
         }
         dev_t ret = RegisterDevice(AUDIO_TYPE_PCM, &AudioOps);
         AudioID[Count] = ret;
         Count++;
         ctx = (PCIArray *)ctx->Next;
     }
     return 0;
 }
References AUDIO_TYPE_PCM, AudioID, AudioOps, BLOCK_TYPE_HDD, BlockOps, CheckPortType(), dev_t, Devices, Drivers, EBADF, EINVAL, ENODEV, v0::GetBAR(), i, E1000Device::ID, RTL8139Device::ID, if(), v0::iLine(), v0::InitializePCI(), KernelLog(), KernelPrint(), NetID, NetOps, NETWORK_TYPE_ETHERNET, None, OIR, PortCount, HBAMemory::Ports, HBAMemory::PortsImplemented, PortTypeName, v0::RegisterDevice(), RegisterInterruptHandler(), ret, SATA, and SATAPI.
Referenced by DriverEntry().
cxx_Panic()
EXTERNC int cxx_Panic ()
Definition at line 739 of file ac97.cpp.
 {
     PCIArray *ctx = Devices;
     short Count = 0;
     while (ctx != nullptr)
     {
         if (Drivers[Count] != nullptr)
             Drivers[Count]->Panic();
         Count++;
         ctx = (PCIArray *)ctx->Next;
     }
     return 0;
 }
References Devices, Drivers, i, AC97Device::Panic(), HDADevice::Panic(), E1000Device::Panic(), RTL8139Device::Panic(), and PortCount.
Referenced by DriverPanic().
cxx_Probe()
EXTERNC int cxx_Probe ()
Definition at line 754 of file ac97.cpp.
 {
     uint16_t VendorIDs[] = {0x8086, PCI_END};
     uint16_t DeviceIDs[] = {0x2415, PCI_END};
     Devices = GetPCIDevices(VendorIDs, DeviceIDs);
     if (Devices == nullptr)
     {
         KernelLog("No AC'97 device found.");
         return -ENODEV;
     }
     PCIArray *ctx = Devices;
     bool Found = false;
     size_t Count = 0;
     while (ctx != nullptr)
     {
         if (Count++ > sizeof(Drivers) / sizeof(AC97Device *))
             break;
         PCIHeader0 *PCIBaseAddress = (PCIHeader0 *)ctx->Device->Header;
         uint32_t PCIBAR0 = PCIBaseAddress->BAR0;
         uint8_t Type = PCIBAR0 & 1;
         if (Type != 1)
         {
             KernelLog("Device %x:%x.%d BAR0 is not I/O.",
                       PCIBaseAddress->Header.VendorID,
                       PCIBaseAddress->Header.DeviceID,
                       PCIBaseAddress->Header.ProgIF);
             continue;
         }
         Found = true;
         ctx = (PCIArray *)ctx->Next;
     }
     if (!Found)
     {
         KernelLog("No valid AC'97 device found.");
         return -EINVAL;
     }
     return 0;
 }
References Devices, Drivers, EINVAL, ENODEV, v0::GetPCIDevices(), if(), KernelLog(), and PCI_END.
Referenced by DriverProbe().