Fennix: Userspace/apps/base/busybox/miscutils/adjtimex.c File Reference
adjtimex.c File Reference
#include "libbb.h"
#include <sys/timex.h>
Functions
int adjtimex_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const uint16_t statlist_bit[] ALIGN2
static const char statlist_name[] ALIGN1
Function Documentation
adjtimex_main()
int adjtimex_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 84 of file adjtimex.c.
 {
     enum {
         OPT_quiet = 0x1
     };
     unsigned opt;
     char *opt_o, *opt_f, *opt_p, *opt_t;
     struct timex txc;
     int ret;
     const char *descript;
     memset(&txc, 0, sizeof(txc));
     opt = getopt32(argv, "^" "qo:f:p:t:"
             "\0" "=0"/*no valid non-option args*/,
             &opt_o, &opt_f, &opt_p, &opt_t
     );
     //if (opt & 0x1) // -q
     if (opt & 0x2) { // -o
         txc.offset = xatol(opt_o);
         txc.modes |= ADJ_OFFSET_SINGLESHOT;
     }
     if (opt & 0x4) { // -f
         txc.freq = xatol(opt_f);
         txc.modes |= ADJ_FREQUENCY;
     }
     if (opt & 0x8) { // -p
         txc.constant = xatol(opt_p);
         txc.modes |= ADJ_TIMECONST;
     }
     if (opt & 0x10) { // -t
         txc.tick = xatol(opt_t);
         txc.modes |= ADJ_TICK;
     }
     /* It's NOFORK applet because the code is very simple:
      * just some printf. No opens, no allocs.
      * If you need to make it more complex, feel free to downgrade to NOEXEC
      */
     ret = adjtimex(&txc);
     if (ret < 0)
         bb_perror_nomsg_and_die();
     if (!(opt & OPT_quiet)) {
         const char *sep;
         const char *name;
         int i;
         printf(
             "    mode:         %d\n"
             "-o  offset:       %ld us\n"
             "-f  freq.adjust:  %ld (65536 = 1ppm)\n"
             "    maxerror:     %ld\n"
             "    esterror:     %ld\n"
             "    status:       %d (",
             txc.modes, txc.offset, txc.freq, txc.maxerror,
             txc.esterror, txc.status
         );
         /* representative output of next code fragment:
          * "PLL | PPSTIME"
          */
         name = statlist_name;
         sep = "";
         for (i = 0; statlist_bit[i]; i++) {
             if (txc.status & statlist_bit[i]) {
                 printf("%s%s", sep, name);
                 sep = " | ";
             }
             name += strlen(name) + 1;
         }
         descript = "error";
         if (ret <= 5)
             descript = nth_string(ret_code_descript, ret);
         printf(")\n"
             "-p  timeconstant: %ld\n"
             "    precision:    %ld us\n"
             "    tolerance:    %ld\n"
             "-t  tick:         %ld us\n"
             "    time.tv_sec:  %ld\n"
             "    time.tv_usec: %ld\n"
             "    return value: %d (%s)\n",
             txc.constant,
             txc.precision, txc.tolerance, txc.tick,
             (long)txc.time.tv_sec, (long)txc.time.tv_usec,
             ret, descript
         );
     }
     return 0;
 }
References ADJ_FREQUENCY, ADJ_OFFSET_SINGLESHOT, ADJ_TICK, ADJ_TIMECONST, adjtimex(), argv, bb_perror_nomsg_and_die(), timex::constant, timex::esterror, timex::freq, getopt32(), i, timex::maxerror, memset, timex::modes, nth_string(), timex::offset, opt, timex::precision, printf, timex::status, strlen(), timex::tick, timex::time, timex::tolerance, timeval::tv_sec, timeval::tv_usec, and xatol().
Variable Documentation
ALIGN1
const char ret_code_descript [] ALIGN1 static
Initial value:
=
    "PLL"       "\0"
    "PPSFREQ"   "\0"
    "PPSTIME"   "\0"
    "FFL"       "\0"
    "INS"       "\0"
    "DEL"       "\0"
    "UNSYNC"    "\0"
    "FREQHOLD"  "\0"
    "PPSSIGNAL" "\0"
    "PPSJITTER" "\0"
    "PPSWANDER" "\0"
    "PPSERROR"  "\0"
    "CLOCKERR"
Definition at line 58 of file adjtimex.c.
ALIGN2
const uint16_t statlist_bit [] ALIGN2 static
Initial value:
= {
    STA_PLL,
    STA_PPSFREQ,
    STA_PPSTIME,
    STA_FLL,
    STA_INS,
    STA_DEL,
    STA_UNSYNC,
    STA_FREQHOLD,
    STA_PPSSIGNAL,
    STA_PPSJITTER,
    STA_PPSWANDER,
    STA_PPSERROR,
    STA_CLOCKERR,
    0
}
Definition at line 42 of file adjtimex.c.