Fennix Userspace: Userspace/apps/base/busybox/miscutils/ttysize.c File Reference
ttysize.c File Reference
#include "libbb.h"
Functions
int ttysize_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
ttysize_main()
int ttysize_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 33 of file ttysize.c.
 {
     unsigned w, h;
     struct winsize wsz;
     w = 80;
     h = 24;
     if (ioctl(0, TIOCGWINSZ, &wsz) == 0
      || ioctl(1, TIOCGWINSZ, &wsz) == 0
      || ioctl(2, TIOCGWINSZ, &wsz) == 0
     ) {
         w = wsz.ws_col;
         h = wsz.ws_row;
     }
     if (!argv[1]) {
         printf("%u %u", w, h);
     } else {
         const char *fmt, *arg;
         fmt = "%u %u" + 3; /* "%u" */
         while ((arg = *++argv) != NULL) {
             char c = arg[0];
             if (c == 'w')
                 printf(fmt, w);
             if (c == 'h')
                 printf(fmt, h);
             fmt = "%u %u" + 2; /* " %u" */
         }
     }
     bb_putchar('\n');
     return 0;
 }
References argv, bb_putchar(), c, h, ioctl(), NULL, printf(), TIOCGWINSZ, and w.