Fennix Userspace: Userspace/mlibc/options/ansi/generic/complex/cacosh.c File Reference
cacosh.c File Reference
#include <complex.h>
Functions
double complex cacosh (double complex z)
Function Documentation
cacosh()
double complex cacosh (double complex z)
Definition at line 83 of file cacosh.c.
 {
     double complex w;
 #if 0 /* does not give the principal value */
     w = I * cacos(z);
 #else
     w = clog(z + csqrt(z + 1) * csqrt(z - 1));
 #endif
     return w;
 }
References cacos(), clog(), complex, csqrt(), and I.