Fennix Userspace: loop_interface_t Struct Reference
loop_interface_t Struct Reference
#include <d_loop.h>
Data Fields
void(* ProcessEvents)()
void(* BuildTiccmd)(ticcmd_t *cmd, int maketic)
void(* RunTic)(ticcmd_t *cmds, boolean *ingame)
void(* RunMenu)()
Detailed Description
Definition at line 31 of file d_loop.h.
Field Documentation
BuildTiccmd
void(* loop_interface_t::BuildTiccmd) (ticcmd_t *cmd, int maketic)
Definition at line 40 of file d_loop.h.
Referenced by BuildNewTic().
ProcessEvents
void(* loop_interface_t::ProcessEvents) ()
Definition at line 35 of file d_loop.h.
Referenced by BuildNewTic().
RunMenu
void(* loop_interface_t::RunMenu) ()
Definition at line 48 of file d_loop.h.
Referenced by BuildNewTic().
RunTic
void(* loop_interface_t::RunTic) (ticcmd_t *cmds, boolean *ingame)
Definition at line 44 of file d_loop.h.
Referenced by TryRunTics().
The documentation for this struct was generated from the following file:
Userspace/apps/user/games/doomgeneric/doomgeneric/d_loop.h