Fennix: Userspace/apps/base/busybox/coreutils/who.c File Reference
who.c File Reference
#include "libbb.h"
Macros
#define CNT_APPLET (ENABLE_USERS + ENABLE_W + ENABLE_WHO)
Functions
static void idle_string (char *str6, time_t t)
int who_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
CNT_APPLET
#define CNT_APPLET (ENABLE_USERS + ENABLE_W + ENABLE_WHO)
Function Documentation
idle_string()
static void idle_string (char * str6, time_t t) static
Definition at line 89 of file who.c.
 {
     t = time(NULL) - t;
     /*if (t < 60) {
         str6[0] = '.';
         str6[1] = '\0';
         return;
     }*/
     if (t >= 0 && t < (24 * 60 * 60)) {
         sprintf(str6, "%02d:%02d",
                 (int) (t / (60 * 60)),
                 (int) ((t % (60 * 60)) / 60));
         return;
     }
     strcpy(str6, "old");
 }
References NULL, sprintf(), strcpy, t, and time().
Referenced by who_main().
who_main()
int who_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 108 of file who.c.
 {
 #define CNT_APPLET (ENABLE_USERS + ENABLE_W + ENABLE_WHO)
     int do_users = (ENABLE_USERS && (CNT_APPLET == 1 || applet_name[0] == 'u'));
     int do_w     = (ENABLE_W     && (CNT_APPLET == 1 || applet_name[1] == '\0'));
     int do_who   = (ENABLE_WHO   && (CNT_APPLET == 1 || applet_name[1] == 'h'));
     struct utmpx *ut;
     unsigned opt;
     const char *fmt = "%s";
     opt = getopt32(argv, do_who ? "^" "aH" "\0" "=0": "^" "" "\0" "=0");
     if ((opt & 2) || do_w) /* -H or we are w */
         puts("USER\t\tTTY\t\tIDLE\tTIME\t\t HOST");
     setutxent();
     while ((ut = getutxent()) != NULL) {
         if (ut->ut_user[0]
          && ((opt & 1) || ut->ut_type == USER_PROCESS)
         ) {
             if (!do_users) {
                 char str6[6];
                 char name[sizeof("/dev/") + sizeof(ut->ut_line) + 1];
                 struct stat st;
                 time_t seconds;
                 str6[0] = '?';
                 str6[1] = '\0';
                 strcpy(name, "/dev/");
                 safe_strncpy(ut->ut_line[0] == '/' ? name : name + sizeof("/dev/")-1,
                     ut->ut_line,
                     sizeof(ut->ut_line)+1
                 );
                 if (stat(name, &st) == 0)
                     idle_string(str6, st.st_atime);
                 /* manpages say ut_tv.tv_sec *is* time_t,
                  * but some systems have it wrong */
                 seconds = ut->ut_tv.tv_sec;
                 /* How wide time field can be?
                  * "Nov 10 19:33:20": 15 chars
                  * "2010-11-10 19:33": 16 chars
                  */
                 printf("%-15.*s %-15.*s %-7s %-16.16s %.*s\n",
                         (int)sizeof(ut->ut_user), ut->ut_user,
                         (int)sizeof(ut->ut_line), ut->ut_line,
                         str6,
 // TODO: with LANG=en_US.UTF-8, who from coreutils 8.25 shows
 // TIME col as "2017-04-06 18:47" (the default format is "Apr  6 18:47").
 // The former format looks saner to me. Switch to it unconditionally?
                         ctime(&seconds) + 4,
                         (int)sizeof(ut->ut_host), ut->ut_host
                 );
             } else {
                 printf(fmt, ut->ut_user);
                 fmt = " %s";
             }
         }
     }
     if (do_users)
         bb_putchar('\n');
     if (ENABLE_FEATURE_CLEAN_UP)
         endutxent();
     return EXIT_SUCCESS;
 }
References applet_name, argv, bb_putchar(), CNT_APPLET, ctime(), endutxent(), EXIT_SUCCESS, getopt32(), getutxent(), idle_string(), NULL, opt, printf, puts(), safe_strncpy(), setutxent(), stat(), strcpy, timeval::tv_sec, USER_PROCESS, utmpx::ut_host, utmpx::ut_line, utmpx::ut_tv, utmpx::ut_type, and utmpx::ut_user.