Fennix Lynx Bootloader: Kernel/Architecture/amd64/cpu/SymmetricMultiprocessing.cpp File Reference
SymmetricMultiprocessing.cpp File Reference
#include <smp.hpp>
#include <interrupts.hpp>
#include <memory.hpp>
#include <cpu.hpp>
#include "../../../kernel.h"
Namespaces
SMP
Macros
#define TRAMPOLINE_START 0x2000
Enumerations
enum SMPTrampolineAddress {
PAGE_TABLE = 0x500, START_ADDR = 0x520, STACK = 0x570, GDT = 0x580,
IDT = 0x590
}
Functions
static __attribute__ ((aligned(PAGE_SIZE))) CPUData CPUs[MAX_CPU]
CPUData * GetCPU (uint64_t id)
CPUData * GetCurrentCPU ()
void StartCPU ()
void SMP::Initialize (void *madt)
Variables
uint64_t _trampoline_start
uint64_t _trampoline_end
enum SMPTrampolineAddress __attribute__
volatile bool CPUEnabled = false
Macro Definition Documentation
TRAMPOLINE_START
#define TRAMPOLINE_START 0x2000
Definition at line 17 of file SymmetricMultiprocessing.cpp.
Enumeration Type Documentation
SMPTrampolineAddress
enum SMPTrampolineAddress
Enumerator
PAGE_TABLE
START_ADDR
STACK
GDT
IDT
Definition at line 19 of file SymmetricMultiprocessing.cpp.
 {
     PAGE_TABLE = 0x500,
     START_ADDR = 0x520,
     STACK = 0x570,
     GDT = 0x580,
     IDT = 0x590,
 };
Function Documentation
__attribute__()
static __attribute__ ((aligned(PAGE_SIZE))) static
GetCPU()
CPUData* GetCPU (uint64_t id)
Definition at line 33 of file SymmetricMultiprocessing.cpp.
 { return &CPUs[id]; }
GetCurrentCPU()
CPUData* GetCurrentCPU ()
Definition at line 35 of file SymmetricMultiprocessing.cpp.
 {
     uint64_t ret = 0;
 #if defined(__amd64__)
     ret = ((APIC::APIC *)Interrupts::apic)->Read(APIC::APIC::APIC_ID) >> 24;
 #elif defined(__i386__)
 #elif defined(__aarch64__)
 #endif
     if (!CPUs[ret].IsActive)
     {
         error("CPU %d is not active!", ret);
         return &CPUs[0];
     }
     if (CPUs[ret].Checksum != CPU_DATA_CHECKSUM)
     {
         error("CPU %d data is corrupted!", ret);
         return &CPUs[0];
     }
     return &CPUs[ret];
 }
References Interrupts::apic, APIC::APIC::APIC_ID, Checksum, CPU_DATA_CHECKSUM, error, and IsActive.
StartCPU()
void StartCPU ()
Definition at line 58 of file SymmetricMultiprocessing.cpp.
 {
     CPU::Interrupts(CPU::Disable);
     uint64_t CPU_ID;
     // Enable CPU features
     {
         CPU::x64::CR0 cr0 = CPU::x64::readcr0();
         CPU::x64::CR4 cr4 = CPU::x64::readcr4();
         uint32_t rax, rbx, rcx, rdx;
         CPU::x64::cpuid(0x1, &rax, &rbx, &rcx, &rdx);
         if (rdx & CPU::x64::CPUID_FEAT_RDX_SSE)
         {
             cr0.EM = 0;
             cr0.MP = 1;
             cr4.OSFXSR = 1;
             cr4.OSXMMEXCPT = 1;
         }
         // Enable cpu cache but... how to use it?
         cr0.NW = 0;
         cr0.CD = 0;
         CPU::x64::cpuid(0x1, &rax, &rbx, &rcx, &rdx);
         if (rdx & CPU::x64::CPUID_FEAT_RDX_UMIP)
         {
             fixme("Not going to enable UMIP.");
             // cr4.UMIP = 1;
         }
         if (rdx & CPU::x64::CPUID_FEAT_RDX_SMEP)
             cr4.SMEP = 1;
         if (rdx & CPU::x64::CPUID_FEAT_RDX_SMAP)
             cr4.SMAP = 1;
         CPU::x64::writecr0(cr0);
         CPU::x64::writecr4(cr4);
         CPU::x64::wrmsr(CPU::x64::MSR_CR_PAT, 0x6 | (0x0 << 8) | (0x1 << 16));
     }
     // Enable APIC
     {
         CPU::x64::wrmsr(CPU::x64::MSR_APIC_BASE, (CPU::x64::rdmsr(CPU::x64::MSR_APIC_BASE) | 0x800) & ~(1 << 10));
         ((APIC::APIC *)Interrupts::apic)->Write(APIC::APIC::APIC_SVR, ((APIC::APIC *)Interrupts::apic)->Read(APIC::APIC::APIC_SVR) | 0x1FF);
     }
     // Set CPU_ID variable using APIC
     CPU_ID = ((APIC::APIC *)Interrupts::apic)->Read(APIC::APIC::APIC_ID) >> 24;
     // Initialize GDT and IDT
     Interrupts::Initialize(CPU_ID);
     CPU::Interrupts(CPU::Enable);
     KPrint("CPU %d is online", CPU_ID);
     CPUEnabled = true;
     CPU::Stop();
 }
References Interrupts::apic, APIC::APIC::APIC_ID, APIC::APIC::APIC_SVR, CPUEnabled, CPU::x64::cpuid(), CPU::x64::CPUID_FEAT_RDX_SMAP, CPU::x64::CPUID_FEAT_RDX_SMEP, CPU::x64::CPUID_FEAT_RDX_SSE, CPU::x64::CPUID_FEAT_RDX_UMIP, CPU::Disable, CPU::Enable, fixme, Interrupts::Initialize(), CPU::Interrupts(), KPrint(), CPU::x64::MSR_APIC_BASE, CPU::x64::MSR_CR_PAT, CPU::x64::rdmsr(), CPU::x64::readcr0(), CPU::x64::readcr4(), CPU::Stop(), CPU::x64::writecr0(), CPU::x64::writecr4(), and CPU::x64::wrmsr().
Variable Documentation
__attribute__
enum SMPTrampolineAddress __attribute__
_trampoline_end
uint64_t _trampoline_end
Definition at line 15 of file SymmetricMultiprocessing.cpp.
_trampoline_start
uint64_t _trampoline_start
Definition at line 15 of file SymmetricMultiprocessing.cpp.
CPUEnabled
volatile bool CPUEnabled = false
Definition at line 28 of file SymmetricMultiprocessing.cpp.