Fennix Kernel: Kernel/kshell/commands/ls.cpp File Reference
ls.cpp File Reference
#include "../cmds.hpp"
#include <filesystem.hpp>
#include "../../kernel.h"
Functions
const char * ColorNodeType (Node *node)
size_t MaxNameLength (Node *nodes)
void PrintLS (Node *node)
void cmd_ls (const char *args)
Function Documentation
cmd_ls()
void cmd_ls (const char * args)
Definition at line 71 of file ls.cpp.
 {
     if (args[0] == '\0')
     {
         Node *rootNode = thisProcess->CurrentWorkingDirectory;
         if (rootNode == nullptr)
             rootNode = fs->GetRootNode()->Children[0];
         PrintLS(rootNode);
     }
     else
     {
         Node *thisNode = fs->GetNodeFromPath(args, thisProcess->CurrentWorkingDirectory);
         if (thisNode == nullptr)
         {
             printf("ls: %s: No such file or directory\n", args);
             return;
         }
         if (thisNode->Type != NodeType::DIRECTORY)
         {
             printf("%s%s\n", ColorNodeType(thisNode), thisNode->Name);
             return;
         }
         PrintLS(thisNode);
     }
 }
References vfs::Node::Children, ColorNodeType(), vfs::DIRECTORY, fs, vfs::Virtual::GetNodeFromPath(), vfs::Virtual::GetRootNode(), vfs::Node::Name, printf, PrintLS(), thisProcess, and vfs::Node::Type.
ColorNodeType()
const char* ColorNodeType (Node * node)
Definition at line 26 of file ls.cpp.
 {
     switch (node->Type)
     {
     case NodeType::DIRECTORY:
         return "\e3871F5";
     case NodeType::BLOCKDEVICE:
         return "\eE8CD1E";
     case NodeType::CHARDEVICE:
         return "\e86E01F";
     case NodeType::PIPE:
         return "\eE0991F";
     case NodeType::SYMLINK:
         return "\e1FB9E0";
     case NodeType::FILE:
         return "\eCCCCCC";
     default:
         return "\eF72020";
     }
 }
References vfs::BLOCKDEVICE, vfs::CHARDEVICE, vfs::DIRECTORY, vfs::PIPE, vfs::SYMLINK, and vfs::Node::Type.
Referenced by cmd_ls(), and PrintLS().
MaxNameLength()
size_t MaxNameLength (Node * nodes)
Definition at line 47 of file ls.cpp.
 {
     size_t maxLength = 0;
     foreach (auto &node in nodes->Children)
         maxLength = std::max(maxLength, strlen(node->Name));
     return maxLength;
 }
References strlen().
Referenced by PrintLS().
PrintLS()
void PrintLS (Node * node)
Definition at line 55 of file ls.cpp.
 {
     size_t maxNameLength = MaxNameLength(node);
     int count = 0;
     bool first = true;
     foreach (auto &var in node->Children)
     {
         if (count % 5 == 0 && !first)
             printf("\n");
         printf(" %s%-*s ", ColorNodeType(var), (int)maxNameLength, var->Name);
         count++;
         first = false;
     }
     printf("\eCCCCCC\n");
 }
References ColorNodeType(), MaxNameLength(), and printf.
Referenced by cmd_ls().