Fennix: Userspace/musl/src/internal/procfdname.c File Reference
procfdname.c File Reference
#include "syscall.h"
Functions
void __procfdname (char *buf, unsigned fd)
Function Documentation
__procfdname()
void __procfdname (char * buf, unsigned fd)
Definition at line 3 of file procfdname.c.
 {
     unsigned i, j;
     for (i=0; (buf[i] = "/proc/self/fd/"[i]); i++);
     if (!fd) {
         buf[i] = '0';
         buf[i+1] = 0;
         return;
     }
     for (j=fd; j; j/=10, i++);
     buf[i] = 0;
     for (; fd; fd/=10) buf[--i] = '0' + fd%10;
 }
References buf, fd, i, and j.
Referenced by fchdir(), fchmod(), fchmodat(), fchown(), fexecve(), and ttyname_r().