Fennix Userspace: Userspace/musl/src/math/tanf.c File Reference
tanf.c File Reference
#include "libm.h"
Functions
float tanf (float x)
Variables
static const double t1pio2 = 1*M_PI_2
static const double t2pio2 = 2*M_PI_2
static const double t3pio2 = 3*M_PI_2
static const double t4pio2 = 4*M_PI_2
Function Documentation
tanf()
float tanf (float x)
Definition at line 26 of file tanf.c.
 {
     double y;
     uint32_t ix;
     unsigned n, sign;
     GET_FLOAT_WORD(ix, x);
     sign = ix >> 31;
     ix &= 0x7fffffff;
     if (ix <= 0x3f490fda) {  /* |x| ~<= pi/4 */
         if (ix < 0x39800000) {  /* |x| < 2**-12 */
             /* raise inexact if x!=0 and underflow if subnormal */
             FORCE_EVAL(ix < 0x00800000 ? x/0x1p120f : x+0x1p120f);
             return x;
         }
         return __tandf(x, 0);
     }
     if (ix <= 0x407b53d1) {  /* |x| ~<= 5*pi/4 */
         if (ix <= 0x4016cbe3)  /* |x| ~<= 3pi/4 */
             return __tandf((sign ? x+t1pio2 : x-t1pio2), 1);
         else
             return __tandf((sign ? x+t2pio2 : x-t2pio2), 0);
     }
     if (ix <= 0x40e231d5) {  /* |x| ~<= 9*pi/4 */
         if (ix <= 0x40afeddf)  /* |x| ~<= 7*pi/4 */
             return __tandf((sign ? x+t3pio2 : x-t3pio2), 1);
         else
             return __tandf((sign ? x+t4pio2 : x-t4pio2), 0);
     }
     /* tan(Inf or NaN) is NaN */
     if (ix >= 0x7f800000)
         return x - x;
     /* argument reduction */
     n = __rem_pio2f(x, &y);
     return __tandf(y, n&1);
 }
References __rem_pio2f(), __tandf(), FORCE_EVAL, GET_FLOAT_WORD, n, t1pio2, t2pio2, t3pio2, t4pio2, x, and y.
Referenced by ctanhf().
Variable Documentation
t1pio2
const double t1pio2 = 1*M_PI_2 static
Definition at line 21 of file tanf.c.
Referenced by tanf().
t2pio2
const double t2pio2 = 2*M_PI_2 static
Definition at line 22 of file tanf.c.
Referenced by tanf().
t3pio2
const double t3pio2 = 3*M_PI_2 static
Definition at line 23 of file tanf.c.
Referenced by tanf().
t4pio2
const double t4pio2 = 4*M_PI_2 static
Definition at line 24 of file tanf.c.
Referenced by tanf().