Fennix: Userspace/musl/src/fenv/fesetround.c File Reference
fesetround.c File Reference
#include <fenv.h>
#include <features.h>
Functions
hidden int __fesetround (int)
int fesetround (int r)
Function Documentation
__fesetround()
hidden int __fesetround (int r)
Definition at line 25 of file fenv.c.
 {
     return 0;
 }
References get_fpc(), get_fpscr(), r, set_fpc(), and set_fpscr().
Referenced by fesetround().
fesetround()
int fesetround (int r)
Definition at line 8 of file fesetround.c.
 {
     if (r != FE_TONEAREST
 #ifdef FE_DOWNWARD
         && r != FE_DOWNWARD
 #endif
 #ifdef FE_UPWARD
         && r != FE_UPWARD
 #endif
 #ifdef FE_TOWARDZERO
         && r != FE_TOWARDZERO
 #endif
     )
         return -1;
     return __fesetround(r);
 }
References __fesetround(), FE_DOWNWARD, FE_TONEAREST, FE_TOWARDZERO, FE_UPWARD, and r.