Fennix: Userspace/mlibc/tests/glibc/error_print_progname.c File Reference
error_print_progname.c File Reference
#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <errno.h>
#include <error.h>
Functions
void test_progname (void)
int main ()
Variables
bool ran = false
Function Documentation
main()
int main (void)
Definition at line 14 of file error_print_progname.c.
            {
     assert(error_print_progname == NULL);
     error_print_progname = &test_progname;
     error(0, EINVAL, "test error #1");
     assert(ran == true);
 }
References assert, EINVAL, error, error_print_progname, NULL, ran, and test_progname().
test_progname()
void test_progname (void)
Definition at line 9 of file error_print_progname.c.
{
     ran = true;
     fprintf(stderr, "progname test");
 }
References fprintf(), ran, and stderr.
Referenced by main().
Variable Documentation
ran
bool ran = false
Definition at line 7 of file error_print_progname.c.
Referenced by main(), and test_progname().