Fennix Kernel: Kernel/Modules/BuiltinModuleLoader.cpp File Reference
BuiltinModuleLoader.cpp File Reference
#include "drv.hpp"
#include "AHCI/ahci.hpp"
#include "VMware/mouse.hpp"
#include "PersonalSystem2/mouse.hpp"
#include "PersonalSystem2/keyboard.hpp"
#include "ATA/ata.hpp"
#include "AudioCodec97/ac97.hpp"
#include "Realtek/rtl8139.hpp"
#include "AdvancedMicroDevices/pcnet.hpp"
#include "Intel/gigabit.hpp"
#include <pci.hpp>
#include <vector>
#include "../Core/Driver/api.hpp"
#include "../kernel.h"
#include "../DAPI.hpp"
#include "../Fex.hpp"
Functions
std::vector< PCI::PCIDeviceHeader * > FindPCI (uint16_t VendorID[16], uint16_t DeviceID[16])
bool StartAHCI ()
bool StartVMwareMouse ()
bool StartPS2Mouse ()
bool StartPS2Keyboard ()
bool StartATA ()
bool StartAC97 ()
bool StartRTL8139 ()
bool StartPCNET ()
bool StartGigabit ()
Variables
FexExtended AHCIExtendedHeader
FexExtended VMwareVirtualMouseExtendedHeader
FexExtended PS2MouseExtendedHeader
FexExtended PS2KeyboardExtendedHeader
FexExtended ATAExtendedHeader
FexExtended AC97ExtendedHeader
FexExtended RTL8139ExtendedHeader
FexExtended AMDPCNETExtendedHeader
FexExtended IntelGigabitExtendedHeader
Function Documentation
FindPCI()
std::vector<PCI::PCIDeviceHeader *> FindPCI (uint16_t VendorID[16], uint16_t DeviceID[16])
Definition at line 177 of file BuiltinModuleLoader.cpp.
 {
     for (uint16_t Vidx = 0; Vidx < 16; Vidx++)
     {
         for (uint16_t Didx = 0; Didx < 16; Didx++)
         {
             if (VendorID[Vidx] == 0 || DeviceID[Didx] == 0)
                 break;
             std::vector<PCI::PCIDeviceHeader *> devices = PCIManager->FindPCIDevice(VendorID[Vidx], DeviceID[Didx]);
             if (devices.size() == 0)
                 continue;
             return devices;
         }
     }
     warn("No PCI device found");
     return std::vector<PCI::PCIDeviceHeader *>();
 }
References PCI::PCI::FindPCIDevice(), PCIManager, and warn.
StartAC97()
bool StartAC97 ()
Definition at line 258 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = AudioCodec97::DriverEntry,
         .ExtendedHeader = &AC97ExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References AC97ExtendedHeader, AudioCodec97::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartAHCI()
bool StartAHCI ()
Definition at line 198 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = AdvancedHostControllerInterface::DriverEntry,
         .ExtendedHeader = &AHCIExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References AHCIExtendedHeader, AdvancedHostControllerInterface::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartATA()
bool StartATA ()
Definition at line 246 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = AdvancedTechnologyAttachment::DriverEntry,
         .ExtendedHeader = &ATAExtendedHeader};
     if (DriverManager->DriverLoadBindInterrupt((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References ATAExtendedHeader, AdvancedTechnologyAttachment::DriverEntry(), Driver::Driver::DriverLoadBindInterrupt(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartGigabit()
bool StartGigabit ()
Definition at line 294 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = Gigabit::DriverEntry,
         .ExtendedHeader = &IntelGigabitExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References Gigabit::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, IntelGigabitExtendedHeader, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartPCNET()
bool StartPCNET ()
Definition at line 282 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = PCNET::DriverEntry,
         .ExtendedHeader = &AMDPCNETExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References AMDPCNETExtendedHeader, PCNET::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, and OK.
Referenced by Driver::Driver::LoadDrivers().
StartPS2Keyboard()
bool StartPS2Keyboard ()
Definition at line 234 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = PS2Keyboard::DriverEntry,
         .ExtendedHeader = &PS2KeyboardExtendedHeader};
     if (DriverManager->DriverLoadBindInterrupt((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References PS2Keyboard::DriverEntry(), Driver::Driver::DriverLoadBindInterrupt(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, OK, and PS2KeyboardExtendedHeader.
Referenced by Driver::Driver::LoadDrivers().
StartPS2Mouse()
bool StartPS2Mouse ()
Definition at line 222 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = PS2Mouse::DriverEntry,
         .ExtendedHeader = &PS2MouseExtendedHeader};
     if (DriverManager->DriverLoadBindInterrupt((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References PS2Mouse::DriverEntry(), Driver::Driver::DriverLoadBindInterrupt(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, OK, and PS2MouseExtendedHeader.
Referenced by Driver::Driver::LoadDrivers().
StartRTL8139()
bool StartRTL8139 ()
Definition at line 270 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = RTL8139::DriverEntry,
         .ExtendedHeader = &RTL8139ExtendedHeader};
     if (DriverManager->DriverLoadBindPCI((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References RTL8139::DriverEntry(), Driver::Driver::DriverLoadBindPCI(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, OK, and RTL8139ExtendedHeader.
Referenced by Driver::Driver::LoadDrivers().
StartVMwareMouse()
bool StartVMwareMouse ()
Definition at line 210 of file BuiltinModuleLoader.cpp.
 {
     Driver::BuiltInDriverInfo BIDI = {
         .EntryPoint = VMwareMouse::DriverEntry,
         .ExtendedHeader = &VMwareVirtualMouseExtendedHeader};
     if (DriverManager->DriverLoadBindInterrupt((uintptr_t)&BIDI, 0, true) == Driver::DriverCode::OK)
         return true;
     return false;
 }
References VMwareMouse::DriverEntry(), Driver::Driver::DriverLoadBindInterrupt(), DriverManager, Driver::BuiltInDriverInfo::EntryPoint, OK, and VMwareVirtualMouseExtendedHeader.
Referenced by Driver::Driver::LoadDrivers().
Variable Documentation
AC97ExtendedHeader
FexExtended AC97ExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "Audio Codec '97 Driver",
        .Type = FexDriverType_Audio,
        .TypeFlags = FexDriverInputTypes_None,
        .OverrideOnConflict = false,
        .Callback = AudioCodec97::CallbackHandler,
        .InterruptCallback = AudioCodec97::InterruptCallback,
        .Bind = {
            .Type = BIND_PCI,
            .PCI = {
                .VendorID = {0x8086},
                .DeviceID = {0x2415},
                .Class = 0x4,
                .SubClass = 0x3,
                .ProgIF = 0x0,
            }}}}
Definition at line 109 of file BuiltinModuleLoader.cpp.
Referenced by StartAC97().
AHCIExtendedHeader
FexExtended AHCIExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "Advanced Host Controller Interface",
        .Type = FexDriverType_Storage,
        .Callback = AdvancedHostControllerInterface::CallbackHandler,
        .InterruptCallback = AdvancedHostControllerInterface::InterruptCallback,
        .Bind = {
            .Type = BIND_PCI,
            .PCI = {
                .VendorID = {0x8086, 0x15AD},
                .DeviceID = {0x2922, 0x2829, 0x07E0},
                .Class = 0x1,
                .SubClass = 0x6,
                .ProgIF = 0x1,
            }}}}
Definition at line 41 of file BuiltinModuleLoader.cpp.
Referenced by StartAHCI().
AMDPCNETExtendedHeader
FexExtended AMDPCNETExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "Advanced Micro Devices PCNET",
        .Type = FexDriverType_Network,
        .Callback = PCNET::CallbackHandler,
        .InterruptCallback = PCNET::InterruptCallback,
        .Bind = {
            .Type = BIND_PCI,
            .PCI = {
                .VendorID = {0x1022},
                .DeviceID = {0x2000},
                .Class = 0x2,
                .SubClass = 0x0,
                .ProgIF = 0x0,
            }}}}
Definition at line 143 of file BuiltinModuleLoader.cpp.
Referenced by StartPCNET().
ATAExtendedHeader
FexExtended ATAExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "Advanced Technology Attachment",
        .Type = FexDriverType_Storage,
        .Callback = AdvancedTechnologyAttachment::CallbackHandler,
        .InterruptCallback = AdvancedTechnologyAttachment::InterruptCallback,
        .Bind = {
            .Type = BIND_INTERRUPT,
            .Interrupt = {
                .Vector = {14, 15},
            }}}}
Definition at line 97 of file BuiltinModuleLoader.cpp.
Referenced by StartATA().
IntelGigabitExtendedHeader
FexExtended IntelGigabitExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "Intel Gigabit Ethernet Controller",
        .Type = FexDriverType_Network,
        .Callback = Gigabit::CallbackHandler,
        .InterruptCallback = Gigabit::InterruptCallback,
        .Bind = {
            .Type = BIND_PCI,
            .PCI = {
                .VendorID = {0x8086},
                .DeviceID = {0x100E, 0x100F, 0x10D3, 0x10EA, 0x153A},
                .Class = 0x2,
                .SubClass = 0x0,
                .ProgIF = 0x0,
            }}}}
Definition at line 159 of file BuiltinModuleLoader.cpp.
Referenced by StartGigabit().
PS2KeyboardExtendedHeader
FexExtended PS2KeyboardExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "PS/2 Keyboard",
        .Type = FexDriverType_Input,
        .TypeFlags = FexDriverInputTypes_Keyboard,
        .Callback = PS2Keyboard::CallbackHandler,
        .InterruptCallback = PS2Keyboard::InterruptCallback,
        .Bind = {
            .Type = BIND_INTERRUPT,
            .Interrupt = {
                .Vector = {1},
            }}}}
Definition at line 84 of file BuiltinModuleLoader.cpp.
Referenced by StartPS2Keyboard().
PS2MouseExtendedHeader
FexExtended PS2MouseExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "PS/2 Mouse",
        .Type = FexDriverType_Input,
        .TypeFlags = FexDriverInputTypes_Mouse,
        .Callback = PS2Mouse::CallbackHandler,
        .InterruptCallback = PS2Mouse::InterruptCallback,
        .Bind = {
            .Type = BIND_INTERRUPT,
            .Interrupt = {
                .Vector = {12},
            }}}}
Definition at line 71 of file BuiltinModuleLoader.cpp.
Referenced by StartPS2Mouse().
RTL8139ExtendedHeader
FexExtended RTL8139ExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "Realtek RTL8139",
        .Type = FexDriverType_Network,
        .Callback = RTL8139::CallbackHandler,
        .InterruptCallback = RTL8139::InterruptCallback,
        .Bind = {
            .Type = BIND_PCI,
            .PCI = {
                .VendorID = {0x10EC},
                .DeviceID = {0x8139},
                .Class = 0x2,
                .SubClass = 0x0,
                .ProgIF = 0x0,
            }}}}
Definition at line 127 of file BuiltinModuleLoader.cpp.
Referenced by StartRTL8139().
VMwareVirtualMouseExtendedHeader
FexExtended VMwareVirtualMouseExtendedHeader
Initial value:
= {
    .Driver = {
        .Name = "VMware Virtual Mouse",
        .Type = FexDriverType_Input,
        .TypeFlags = FexDriverInputTypes_Mouse,
        .OverrideOnConflict = true,
        .Callback = VMwareMouse::CallbackHandler,
        .InterruptCallback = VMwareMouse::InterruptCallback,
        .Bind = {
            .Type = BIND_INTERRUPT,
            .Interrupt = {
                .Vector = {12},
            }}}}
Definition at line 57 of file BuiltinModuleLoader.cpp.
Referenced by StartVMwareMouse().