Fennix Userspace: Userspace/mlibc/sysdeps/managarm/generic/entry.cpp File Reference
entry.cpp File Reference
#include <pthread.h>
#include <stdlib.h>
#include <sys/auxv.h>
#include <frg/eternal.hpp>
#include <bits/ensure.h>
#include <mlibc/allocator.hpp>
#include <mlibc/debug.hpp>
#include <mlibc/posix-pipe.hpp>
#include <mlibc/all-sysdeps.hpp>
#include <mlibc/elf/startup.h>
#include <protocols/posix/data.hpp>
#include <protocols/posix/supercalls.hpp>
Data Structures
struct LibraryGuard
Namespaces
anonymous_namespace{entry.cpp}
Functions
void __mlibc_initLocale ()
uintptr_t * __dlapi_entrystack ()
void anonymous_namespace{entry.cpp}::actuallyCacheInfos ()
MemoryAllocator & getSysdepsAllocator ()
HelHandle getPosixLane ()
HelHandle * cacheFileTable ()
HelHandle getHandleForFd (int fd)
void clearCachedInfos ()
void __mlibc_entry (int(*main_fn)(int argc, char *argv[], char *env[]))
Variables
thread_local Queue globalQueue
thread_local HelHandle __mlibc_posix_lane
thread_local void * __mlibc_clk_tracker_page
thread_local unsigned anonymous_namespace{entry.cpp}::__mlibc_gsf_nesting
thread_local void * anonymous_namespace{entry.cpp}::__mlibc_cached_thread_page
thread_local HelHandle * anonymous_namespace{entry.cpp}::cachedFileTable
thread_local pthread_once_t anonymous_namespace{entry.cpp}::has_cached_infos = PTHREAD_ONCE_INIT
static LibraryGuard guard
char ** environ
static mlibc::exec_stack_data __mlibc_stack_data
Function Documentation
__dlapi_entrystack()
uintptr_t* __dlapi_entrystack ()
Definition at line 398 of file main.cpp.
{
     return entryStack;
 }
__mlibc_entry()
void __mlibc_entry (int(*)(int argc, char *argv[], char *env[]) main_fn)
Definition at line 127 of file entry.cpp.
{
     // TODO: call __dlapi_enter, otherwise static builds will break (see Linux sysdeps)
     auto result = main_fn(__mlibc_stack_data.argc, __mlibc_stack_data.argv, environ);
     exit(result);
 }
References __mlibc_stack_data, mlibc::exec_stack_data::argc, mlibc::exec_stack_data::argv, environ, and exit().
__mlibc_initLocale()
void __mlibc_initLocale ()
Definition at line 74 of file locale-stubs.cpp.
{
     mlibc::collate_facet = &mlibc::c_locale;
     mlibc::ctype_facet = &mlibc::c_locale;
     mlibc::monetary_facet = &mlibc::c_locale;
     mlibc::numeric_facet = &mlibc::c_locale;
     mlibc::time_facet = &mlibc::c_locale;
     mlibc::messages_facet = &mlibc::c_locale;
 }
References mlibc::c_locale, mlibc::collate_facet, mlibc::ctype_facet, mlibc::messages_facet, mlibc::monetary_facet, mlibc::numeric_facet, and mlibc::time_facet.
cacheFileTable()
HelHandle* cacheFileTable ()
Definition at line 92 of file entry.cpp.
{
     // TODO: Make sure that this is signal-safe (it is called e.g. by sys_clock_get()).
     pthread_once(&has_cached_infos, &actuallyCacheInfos);
     return cachedFileTable;
 }
References anonymous_namespace{entry.cpp}::actuallyCacheInfos(), anonymous_namespace{entry.cpp}::cachedFileTable, anonymous_namespace{entry.cpp}::has_cached_infos, and pthread_once().
Referenced by getHandleForFd(), and getPosixLane().
clearCachedInfos()
void clearCachedInfos ()
Definition at line 105 of file entry.cpp.
{
     has_cached_infos = PTHREAD_ONCE_INIT;
 }
References anonymous_namespace{entry.cpp}::has_cached_infos, and PTHREAD_ONCE_INIT.
getHandleForFd()
HelHandle getHandleForFd (int fd)
Definition at line 98 of file entry.cpp.
{
     if (fd >= 512)
         return 0;
     return cacheFileTable()[fd];
 }
References cacheFileTable(), and fd.
Referenced by __mlibc_getPassthrough(), mlibc::ioctl_drm(), mlibc::sys_fallocate(), and mlibc::sys_flock().
getPosixLane()
HelHandle getPosixLane ()
Definition at line 87 of file entry.cpp.
{
     cacheFileTable();
     return __mlibc_posix_lane;
 }
References __mlibc_posix_lane, and cacheFileTable().
Referenced by mlibc::sys_chroot(), mlibc::sys_getrusage(), mlibc::sys_inotify_add_watch(), mlibc::sys_memfd_create(), mlibc::sys_mkfifoat(), mlibc::sys_mount(), mlibc::sys_signalfd_create(), mlibc::sys_timerfd_create(), mlibc::sys_timerfd_settime(), and mlibc::sys_vm_remap().
getSysdepsAllocator()
MemoryAllocator& getSysdepsAllocator ()
Definition at line 78 of file entry.cpp.
{
     // use frg::eternal to prevent a call to __cxa_atexit().
     // this is necessary because __cxa_atexit() call this function.
     static frg::eternal<VirtualAllocator> virtualAllocator;
     static frg::eternal<MemoryPool> heap{virtualAllocator.get()};
     static frg::eternal<MemoryAllocator> singleton{&heap.get()};
     return singleton.get();
 }
Referenced by mlibc::ioctl_drm(), Queue::Queue(), mlibc::sys_chroot(), mlibc::sys_fallocate(), mlibc::sys_flock(), mlibc::sys_getrusage(), mlibc::sys_inotify_add_watch(), mlibc::sys_memfd_create(), mlibc::sys_mkfifoat(), mlibc::sys_mount(), mlibc::sys_signalfd_create(), mlibc::sys_timerfd_create(), mlibc::sys_timerfd_settime(), and mlibc::sys_vm_remap().
Variable Documentation
__mlibc_clk_tracker_page
thread_local void* __mlibc_clk_tracker_page
Definition at line 27 of file entry.cpp.
Referenced by anonymous_namespace{entry.cpp}::actuallyCacheInfos().
__mlibc_posix_lane
thread_local HelHandle __mlibc_posix_lane
Definition at line 26 of file entry.cpp.
Referenced by anonymous_namespace{entry.cpp}::actuallyCacheInfos(), and getPosixLane().
__mlibc_stack_data
mlibc::exec_stack_data __mlibc_stack_data static
Definition at line 116 of file entry.cpp.
Referenced by __mlibc_entry().
environ
char** environ extern
Definition at line 42 of file lib.c.
globalQueue
thread_local Queue globalQueue
Definition at line 23 of file entry.cpp.
guard
LibraryGuard guard static
Definition at line 113 of file entry.cpp.