Fennix: Userspace/apps/base/busybox/miscutils/fbsplash.c File Reference
fbsplash.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <linux/fb.h>
Data Structures
struct globals
Macros
#define DEBUG 0
#define ESC "\033"
#define G (*ptr_to_globals)
#define INIT_G()
#define nbar_width ns[0]
#define nbar_height ns[1]
#define nbar_posx ns[2]
#define nbar_posy ns[3]
#define nbar_colr ns[4]
#define nbar_colg ns[5]
#define nbar_colb ns[6]
#define img_posx ns[7]
#define img_posy ns[8]
#define DEBUG_MESSAGE(...) ((void)0)
#define concat_buf bb_common_bufsiz1
Functions
static void fb_setpal (int fd)
static void fb_open (const char *strfb_device)
static unsigned fb_pixel_value (unsigned r, unsigned g, unsigned b)
static void fb_write_pixel (unsigned char *addr, unsigned pixel)
static void fb_drawrectangle (void)
static void fb_drawfullrectangle (int nx1pos, int ny1pos, int nx2pos, int ny2pos, unsigned char nred, unsigned char ngreen, unsigned char nblue)
static void fb_drawprogressbar (unsigned percent)
static void fb_drawimage (void)
static void init (const char *cfg_filename)
int fbsplash_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
concat_buf
#define concat_buf bb_common_bufsiz1
DEBUG
#define DEBUG 0
Definition at line 65 of file fbsplash.c.
DEBUG_MESSAGE
#define DEBUG_MESSAGE (...) ((void)0)
Definition at line 107 of file fbsplash.c.
ESC
#define ESC "\033"
Definition at line 67 of file fbsplash.c.
G
#define G (*ptr_to_globals)
Definition at line 85 of file fbsplash.c.
img_posx
#define img_posx ns[7]
Definition at line 97 of file fbsplash.c.
img_posy
#define img_posy ns[8]
Definition at line 98 of file fbsplash.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 86 of file fbsplash.c.
nbar_colb
#define nbar_colb ns[6]
Definition at line 96 of file fbsplash.c.
nbar_colg
#define nbar_colg ns[5]
Definition at line 95 of file fbsplash.c.
nbar_colr
#define nbar_colr ns[4]
Definition at line 94 of file fbsplash.c.
nbar_height
#define nbar_height ns[1]
Definition at line 91 of file fbsplash.c.
nbar_posx
#define nbar_posx ns[2]
Definition at line 92 of file fbsplash.c.
nbar_posy
#define nbar_posy ns[3]
Definition at line 93 of file fbsplash.c.
nbar_width
#define nbar_width ns[0]
Definition at line 90 of file fbsplash.c.
Function Documentation
fb_drawfullrectangle()
static void fb_drawfullrectangle (int nx1pos, int ny1pos, int nx2pos, int ny2pos, unsigned char nred, unsigned char ngreen, unsigned char nblue) static
Draw filled rectangle on framebuffer
Parameters
nx1pos,ny1pos upper left position
nx2pos,ny2pos down right position
nred,ngreen,nblue rgb color
Definition at line 291 of file fbsplash.c.
 {
     int cnt1, cnt2, nypos;
     unsigned thispix;
     unsigned char *ptr;
     thispix = fb_pixel_value(nred, ngreen, nblue);
     cnt1 = ny2pos - ny1pos;
     nypos = ny1pos;
     do {
         ptr = G.addr + nypos * G.scr_fix.line_length + nx1pos * G.bytes_per_pixel;
         cnt2 = nx2pos - nx1pos;
         do {
             fb_write_pixel(ptr, thispix);
             ptr += G.bytes_per_pixel;
         } while (--cnt2 >= 0);
         nypos++;
     } while (--cnt1 >= 0);
 }
References fb_pixel_value(), fb_write_pixel(), and G.
Referenced by fb_drawprogressbar().
fb_drawimage()
static void fb_drawimage (void) static
Draw image from PPM file
Definition at line 375 of file fbsplash.c.
 {
     FILE *theme_file;
     char *read_ptr;
     unsigned char *pixline;
     unsigned i, j, width, height, line_size;
     if (LONE_DASH(G.image_filename)) {
         theme_file = stdin;
     } else {
         int fd = open_zipped(G.image_filename, /*fail_if_not_compressed:*/ 0);
         if (fd < 0)
             bb_simple_perror_msg_and_die(G.image_filename);
         theme_file = xfdopen_for_read(fd);
     }
     /* Parse ppm header:
      * - Magic: two characters "P6".
      * - Whitespace (blanks, TABs, CRs, LFs).
      * - A width, formatted as ASCII characters in decimal.
      * - Whitespace.
      * - A height, ASCII decimal.
      * - Whitespace.
      * - The maximum color value, ASCII decimal, in 0..65535
      * - Newline or other single whitespace character.
      *   (we support newline only)
      * - A raster of Width * Height pixels in triplets of rgb
      *   in pure binary by 1 or 2 bytes. (we support only 1 byte)
      */
 #define concat_buf bb_common_bufsiz1
     setup_common_bufsiz();
     read_ptr = concat_buf;
     while (1) {
         int w, h, max_color_val;
         int rem = concat_buf + COMMON_BUFSIZE - read_ptr;
         if (rem < 2
          || fgets(read_ptr, rem, theme_file) == NULL
         ) {
             bb_error_msg_and_die("bad PPM file '%s'", G.image_filename);
         }
         read_ptr = strchrnul(read_ptr, '#');
         *read_ptr = '\0'; /* ignore #comments */
         if (sscanf(concat_buf, "P6 %u %u %u", &w, &h, &max_color_val) == 3
          && max_color_val <= 255
         ) {
             width = w; /* w is on stack, width may be in register */
             height = h;
             break;
         }
     }
     line_size = width*3;
     pixline = xmalloc(line_size);
     if ((width + G.img_posx) > G.scr_var.xres)
         width = G.scr_var.xres - G.img_posx;
     if ((height + G.img_posy) > G.scr_var.yres)
         height = G.scr_var.yres - G.img_posy;
     for (j = 0; j < height; j++) {
         unsigned char *pixel;
         unsigned char *src;
         if (fread(pixline, 1, line_size, theme_file) != line_size)
             bb_error_msg_and_die("bad PPM file '%s'", G.image_filename);
         pixel = pixline;
         src = G.addr + (G.img_posy + j) * G.scr_fix.line_length + G.img_posx * G.bytes_per_pixel;
         for (i = 0; i < width; i++) {
             unsigned thispix = fb_pixel_value(pixel[0], pixel[1], pixel[2]);
             fb_write_pixel(src, thispix);
             src += G.bytes_per_pixel;
             pixel += 3;
         }
     }
     free(pixline);
     fclose(theme_file);
 }
References bb_error_msg_and_die(), bb_simple_perror_msg_and_die(), concat_buf, fb_pixel_value(), fb_write_pixel(), fclose(), fd, fgets, for(), fread(), free, G, h, height(), i, j, line_size, LONE_DASH, NULL, open_zipped, src, sscanf(), stdin, strchrnul(), w, width, xfdopen_for_read(), and xmalloc.
Referenced by fbsplash_main().
fb_drawprogressbar()
static void fb_drawprogressbar (unsigned percent) static
Draw a progress bar on framebuffer
Parameters
percent percentage of loading
Definition at line 319 of file fbsplash.c.
 {
     int left_x, top_y, pos_x;
     unsigned width, height;
     // outer box
     left_x = G.nbar_posx;
     top_y = G.nbar_posy;
     width = G.nbar_width - 1;
     height = G.nbar_height - 1;
     if ((int)(height | width) < 0)
         return;
     // NB: "width" of 1 actually makes rect with width of 2!
     fb_drawrectangle();
     // inner "empty" rectangle
     left_x++;
     top_y++;
     width -= 2;
     height -= 2;
     if ((int)(height | width) < 0)
         return;
     pos_x = left_x;
     if (percent > 0) {
         int i, y;
         // actual progress bar
         pos_x += (unsigned)(width * percent) / 100;
         y = top_y;
         i = height;
         if (height == 0)
             height++; // divide by 0 is bad
         while (i >= 0) {
             // draw one-line thick "rectangle"
             // top line will have gray lvl 200, bottom one 100
             unsigned gray_level = 100 + (unsigned)i*100 / height;
             fb_drawfullrectangle(
                     left_x, y, pos_x, y,
                     gray_level, gray_level, gray_level);
             y++;
             i--;
         }
     }
     fb_drawfullrectangle(
             pos_x, top_y,
             left_x + width, top_y + height,
             G.nbar_colr, G.nbar_colg, G.nbar_colb);
 }
References fb_drawfullrectangle(), fb_drawrectangle(), G, height(), i, percent, width, and y.
Referenced by fbsplash_main().
fb_drawrectangle()
static void fb_drawrectangle (void) static
Draw hollow rectangle on framebuffer
Definition at line 250 of file fbsplash.c.
 {
     int cnt;
     unsigned thispix;
     unsigned char *ptr1, *ptr2;
     unsigned char nred = G.nbar_colr/2;
     unsigned char ngreen =  G.nbar_colg/2;
     unsigned char nblue = G.nbar_colb/2;
     thispix = fb_pixel_value(nred, ngreen, nblue);
     // horizontal lines
     ptr1 = G.addr + G.nbar_posy * G.scr_fix.line_length + G.nbar_posx * G.bytes_per_pixel;
     ptr2 = G.addr + (G.nbar_posy + G.nbar_height - 1) * G.scr_fix.line_length + G.nbar_posx * G.bytes_per_pixel;
     cnt = G.nbar_width - 1;
     do {
         fb_write_pixel(ptr1, thispix);
         fb_write_pixel(ptr2, thispix);
         ptr1 += G.bytes_per_pixel;
         ptr2 += G.bytes_per_pixel;
     } while (--cnt >= 0);
     // vertical lines
     ptr1 = G.addr + G.nbar_posy * G.scr_fix.line_length + G.nbar_posx * G.bytes_per_pixel;
     ptr2 = G.addr + G.nbar_posy * G.scr_fix.line_length + (G.nbar_posx + G.nbar_width - 1) * G.bytes_per_pixel;
     cnt = G.nbar_height - 1;
     do {
         fb_write_pixel(ptr1, thispix);
         fb_write_pixel(ptr2, thispix);
         ptr1 += G.scr_fix.line_length;
         ptr2 += G.scr_fix.line_length;
     } while (--cnt >= 0);
 }
References cnt, fb_pixel_value(), fb_write_pixel(), and G.
Referenced by fb_drawprogressbar().
fb_open()
static void fb_open (const char * strfb_device) static
Open and initialize the framebuffer device
Parameters
*strfb_device pointer to framebuffer device
Definition at line 152 of file fbsplash.c.
 {
     int fbfd = xopen(strfb_device, O_RDWR);
     // framebuffer properties
     xioctl(fbfd, FBIOGET_VSCREENINFO, &G.scr_var);
     xioctl(fbfd, FBIOGET_FSCREENINFO, &G.scr_fix);
     switch (G.scr_var.bits_per_pixel) {
     case 8:
         fb_setpal(fbfd);
         break;
     case 16:
     case 24:
     case 32:
         break;
     default:
         bb_error_msg_and_die("unsupported %u bpp", (int)G.scr_var.bits_per_pixel);
         break;
     }
     G.red_shift   = 8 - G.scr_var.red.length;
     G.green_shift = 8 - G.scr_var.green.length;
     G.blue_shift  = 8 - G.scr_var.blue.length;
     G.bytes_per_pixel = (G.scr_var.bits_per_pixel + 7) >> 3;
     // map the device in memory
     G.addr = mmap(NULL,
             (G.scr_var.yres_virtual ?: G.scr_var.yres) * G.scr_fix.line_length,
             PROT_WRITE, MAP_SHARED, fbfd, 0);
     if (G.addr == MAP_FAILED)
         bb_simple_perror_msg_and_die("mmap");
     // point to the start of the visible screen
     G.addr += G.scr_var.yoffset * G.scr_fix.line_length + G.scr_var.xoffset * G.bytes_per_pixel;
     close(fbfd);
 }
References bb_error_msg_and_die(), bb_simple_perror_msg_and_die(), close(), fb_setpal(), FBIOGET_VSCREENINFO, G, MAP_FAILED, MAP_SHARED, mmap(), NULL, O_RDWR, PROT_WRITE, xioctl, and xopen().
Referenced by fbsplash_main().
fb_pixel_value()
static unsigned fb_pixel_value (unsigned r, unsigned g, unsigned b) static
Return pixel value of the passed RGB color. This is performance critical fn.
Definition at line 197 of file fbsplash.c.
 {
     /* We assume that the r,g,b values are <= 255 */
     if (G.bytes_per_pixel == 1) {
         r = r        & 0xe0; // 3-bit red
         g = (g >> 3) & 0x1c; // 3-bit green
         b =  b >> 6;         // 2-bit blue
         return r + g + b;
     }
     if (G.bytes_per_pixel == 2) {
         // ARM PL110 on Integrator/CP has RGBA5551 bit arrangement.
         // We want to support bit locations like that.
         //
         // First shift out unused bits
         r = r >> G.red_shift;
         g = g >> G.green_shift;
         b = b >> G.blue_shift;
         // Then shift the remaining bits to their offset
         return (r << G.scr_var.red.offset) +
             (g << G.scr_var.green.offset) +
             (b << G.scr_var.blue.offset);
     }
     // RGB 888
     return b + (g << 8) + (r << 16);
 }
References g, and G.
Referenced by fb_drawfullrectangle(), fb_drawimage(), and fb_drawrectangle().
fb_setpal()
static void fb_setpal (int fd) static
Configure palette for RGB:332
Definition at line 113 of file fbsplash.c.
 {
     struct fb_cmap cmap;
     /* fb colors are 16 bit */
     unsigned short red[256], green[256], blue[256];
     unsigned i;
     /* RGB:332 */
     for (i = 0; i < 256; i++) {
         /* Color is encoded in pixel value as rrrgggbb.
          * 3-bit color is mapped to 16-bit one as:
          * 000 -> 00000000 00000000
          * 001 -> 00100100 10010010
          * ...
          * 011 -> 01101101 10110110
          * 100 -> 10010010 01001001
          * ...
          * 111 -> 11111111 11111111
          */
         red[i]   = (( i >> 5       ) * 0x9249) >> 2; // rrr * 00 10010010 01001001 >> 2
         green[i] = (((i >> 2) & 0x7) * 0x9249) >> 2; // ggg * 00 10010010 01001001 >> 2
         /* 2-bit color is easier: */
         blue[i]  =  ( i       & 0x3) * 0x5555; // bb * 01010101 01010101
     }
     cmap.start = 0;
     cmap.len   = 256;
     cmap.red   = red;
     cmap.green = green;
     cmap.blue  = blue;
     cmap.transp = 0;
     xioctl(fd, FBIOPUTCMAP, &cmap);
 }
References fd, i, and xioctl.
Referenced by fb_open().
fb_write_pixel()
static void fb_write_pixel (unsigned char * addr, unsigned pixel) static
Draw pixel on framebuffer
Definition at line 227 of file fbsplash.c.
 {
     switch (G.bytes_per_pixel) {
     case 1:
         *addr = pixel;
         break;
     case 2:
         *(uint16_t *)addr = pixel;
         break;
     case 4:
         *(uint32_t *)addr = pixel;
         break;
     default: // 24 bits per pixel
         addr[0] = pixel;
         addr[1] = pixel >> 8;
         addr[2] = pixel >> 16;
     }
 }
References addr, and G.
Referenced by fb_drawfullrectangle(), fb_drawimage(), and fb_drawrectangle().
fbsplash_main()
int fbsplash_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 492 of file fbsplash.c.
 {
     const char *fb_device, *cfg_filename, *fifo_filename;
     FILE *fp = fp; // for compiler
     char *num_buf;
     unsigned num;
     bool bCursorOff;
     INIT_G();
     // parse command line options
     fb_device = "/dev/fb0";
     cfg_filename = NULL;
     fifo_filename = NULL;
     bCursorOff = 1 & getopt32(argv, "cs:d:i:f:",
             &G.image_filename, &fb_device, &cfg_filename, &fifo_filename);
     // parse configuration file
     if (cfg_filename)
         init(cfg_filename);
     // We must have -s IMG
     if (!G.image_filename)
         bb_show_usage();
     fb_open(fb_device);
     if (fifo_filename && bCursorOff) {
         // hide cursor (BEFORE any fb ops)
         full_write(STDOUT_FILENO, ESC"[?25l", 6);
     }
     fb_drawimage();
     if (!fifo_filename)
         return EXIT_SUCCESS;
     fp = xfopen_stdin(fifo_filename);
     if (fp != stdin) {
         // For named pipes, we want to support this:
         //  mkfifo cmd_pipe
         //  fbsplash -f cmd_pipe .... &
         //  ...
         //  echo 33 >cmd_pipe
         //  ...
         //  echo 66 >cmd_pipe
         // This means that we don't want fbsplash to get EOF
         // when last writer closes input end.
         // The simplest way is to open fifo for writing too
         // and become an additional writer :)
         open(fifo_filename, O_WRONLY); // errors are ignored
     }
     fb_drawprogressbar(0);
     // Block on read, waiting for some input.
     // Use of <stdio.h> style I/O allows to correctly
     // handle a case when we have many buffered lines
     // already in the pipe
     while ((num_buf = xmalloc_fgetline(fp)) != NULL) {
         if (is_prefixed_with(num_buf, "exit")) {
             DEBUG_MESSAGE("exit");
             break;
         }
         num = atoi(num_buf);
         if (isdigit(num_buf[0]) && (num <= 100)) {
 #if DEBUG
             DEBUG_MESSAGE(itoa(num));
 #endif
             fb_drawprogressbar(num);
         }
         free(num_buf);
     }
     if (bCursorOff) // restore cursor
         full_write(STDOUT_FILENO, ESC"[?25h", 6);
     return EXIT_SUCCESS;
 }
References argv, atoi(), bb_show_usage(), DEBUG_MESSAGE, ESC, EXIT_SUCCESS, fb_drawimage(), fb_drawprogressbar(), fb_open(), free, full_write(), G, getopt32(), init(), INIT_G, is_prefixed_with(), isdigit, itoa, NULL, num, O_WRONLY, open(), stdin, STDOUT_FILENO, xfopen_stdin(), and xmalloc_fgetline().
init()
static void init (const char * cfg_filename) static
Parse configuration file
Parameters
*cfg_filename name of the configuration file
Definition at line 458 of file fbsplash.c.
 {
     static const char param_names[] ALIGN1 =
         "BAR_WIDTH\0" "BAR_HEIGHT\0"
         "BAR_LEFT\0" "BAR_TOP\0"
         "BAR_R\0" "BAR_G\0" "BAR_B\0"
         "IMG_LEFT\0" "IMG_TOP\0"
 #if DEBUG
         "DEBUG\0"
 #endif
         ;
     char *token[2];
     parser_t *parser = config_open2(cfg_filename, xfopen_stdin);
     while (config_read(parser, token, 2, 2, "#=",
                 (PARSE_NORMAL | PARSE_MIN_DIE) & ~(PARSE_TRIM | PARSE_COLLAPSE))) {
         unsigned val = xatoi_positive(token[1]);
         int i = index_in_strings(param_names, token[0]);
         if (i < 0)
             bb_error_msg_and_die("syntax error: %s", token[0]);
         if (i >= 0 && i < 9)
             G.ns[i] = val;
 #if DEBUG
         if (i == 9) {
             G.bdebug_messages = val;
             if (G.bdebug_messages)
                 G.logfile_fd = xfopen_for_write("/tmp/fbsplash.log");
         }
 #endif
     }
     config_close(parser);
 }
References ALIGN1, bb_error_msg_and_die(), config_close(), config_open2(), config_read, G, i, index_in_strings(), PARSE_COLLAPSE, PARSE_MIN_DIE, PARSE_NORMAL, PARSE_TRIM, parser, val, xatoi_positive(), xfopen_for_write(), and xfopen_stdin().
Referenced by fbsplash_main().