Fennix: FutexLockImpl< Recursive > Struct Template Reference
FutexLockImpl< Recursive > Struct Template Reference
#include <lock.hpp>
Public Member Functions
FutexLockImpl ()
FutexLockImpl (const FutexLockImpl &)=delete
FutexLockImpl & operator= (const FutexLockImpl &)=delete
void lock ()
bool try_lock ()
void unlock ()
Static Public Attributes
static constexpr uint32_t waitersBit = (1 << 31)
static constexpr uint32_t ownerMask = (static_cast<uint32_t>(1) << 30) - 1
Private Attributes
uint32_t _state
uint32_t _recursion
Detailed Description
template<bool Recursive>
struct FutexLockImpl< Recursive >
Definition at line 12 of file lock.hpp.
Constructor & Destructor Documentation
FutexLockImpl() [1/2]
template<bool Recursive> FutexLockImpl< Recursive >::FutexLockImpl () inline
Definition at line 13 of file lock.hpp.
 : _state{0}, _recursion{0} { }
FutexLockImpl() [2/2]
template<bool Recursive> FutexLockImpl< Recursive >::FutexLockImpl (const FutexLockImpl< Recursive > &) delete
Member Function Documentation
lock()
template<bool Recursive> void FutexLockImpl< Recursive >::lock () inline
Definition at line 22 of file lock.hpp.
                 {
         unsigned int this_tid = mlibc::this_tid();
         unsigned int expected = 0;
         while(true) {
             if(!expected) {
                 // Try to take the mutex here.
                 if(__atomic_compare_exchange_n(&_state,
                         &expected, this_tid, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)) {
                     if constexpr (Recursive) {
                         __ensure(!_recursion);
                         _recursion = 1;
                     }
                     return;
                 }
             }else{
                 // If this (recursive) mutex is already owned by us, increment the recursion level.
                 if((expected & ownerMask) == this_tid) {
                     if constexpr (Recursive)
                         ++_recursion;
                     else
                         mlibc::panicLogger() << "mlibc: FutexLock deadlock detected!" << frg::endlog;
                     return;
                 }
                 // Wait on the futex if the waiters flag is set.
                 if(expected & waitersBit) {
                     int e = mlibc::sys_futex_wait((int *)&_state, expected, nullptr);
                     // If the wait returns EAGAIN, that means that the waitersBit was just unset by
                     // some other thread. In this case, we should loop back around.
                     if (e && e != EAGAIN)
                         mlibc::panicLogger() << "sys_futex_wait() failed with error code " << e << frg::endlog;
                     // Opportunistically try to take the lock after we wake up.
                     expected = 0;
                 }else{
                     // Otherwise we have to set the waiters flag first.
                     unsigned int desired = expected | waitersBit;
                     if(__atomic_compare_exchange_n((int *)&_state,
                             reinterpret_cast<int*>(&expected), desired, false, __ATOMIC_RELAXED, __ATOMIC_RELAXED))
                         expected = desired;
                 }
             }
         }
     }
References __ensure, FutexLockImpl< Recursive >::_recursion, FutexLockImpl< Recursive >::_state, EAGAIN, FutexLockImpl< Recursive >::ownerMask, mlibc::panicLogger, mlibc::sys_futex_wait(), mlibc::this_tid(), and FutexLockImpl< Recursive >::waitersBit.
Referenced by pthread_exit().
operator=()
template<bool Recursive> FutexLockImpl& FutexLockImpl< Recursive >::operator= (const FutexLockImpl< Recursive > &) delete
try_lock()
template<bool Recursive> bool FutexLockImpl< Recursive >::try_lock () inline
Definition at line 69 of file lock.hpp.
                     {
         unsigned int this_tid = mlibc::this_tid();
         unsigned int expected = __atomic_load_n(&_state, __ATOMIC_RELAXED);
         if(!expected) {
             // Try to take the mutex here.
             if(__atomic_compare_exchange_n(&_state,
                             &expected, this_tid, false, __ATOMIC_ACQUIRE, __ATOMIC_ACQUIRE)) {
                 if constexpr (Recursive)
                     _recursion = 1;
                 return true;
             }
         } else {
             // If this (recursive) mutex is already owned by us, increment the recursion level.
             if((expected & ownerMask) == this_tid) {
                 if constexpr (Recursive) {
                     __ensure(!_recursion);
                     ++_recursion;
                     return true;
                 } else {
                     return false;
                 }
             }
         }
         return false;
     }
References __ensure, FutexLockImpl< Recursive >::_recursion, FutexLockImpl< Recursive >::_state, FutexLockImpl< Recursive >::ownerMask, and mlibc::this_tid().
unlock()
template<bool Recursive> void FutexLockImpl< Recursive >::unlock () inline
Definition at line 97 of file lock.hpp.
                   {
         // Decrement the recursion level and unlock if we hit zero.
         if constexpr (Recursive) {
             __ensure(_recursion);
             if(--_recursion)
                 return;
         }
         // Reset the mutex to the unlocked state.
         auto state = __atomic_exchange_n(&_state, 0, __ATOMIC_RELEASE);
         __ensure((state & ownerMask) == mlibc::this_tid());
         if(state & waitersBit) {
             // Wake the futex if there were waiters. Since the mutex might not exist at this location
             // anymore, we must conservatively ignore EACCES and EINVAL which may occur as a result.
             int e = mlibc::sys_futex_wake((int *)&_state);
             __ensure(e >= 0 || e == EACCES || e == EINVAL);
         }
     }
References __ensure, FutexLockImpl< Recursive >::_recursion, FutexLockImpl< Recursive >::_state, EACCES, EINVAL, FutexLockImpl< Recursive >::ownerMask, state, mlibc::sys_futex_wake(), mlibc::this_tid(), and FutexLockImpl< Recursive >::waitersBit.
Referenced by pthread_exit().
Field Documentation
_recursion
template<bool Recursive> uint32_t FutexLockImpl< Recursive >::_recursion private
Definition at line 118 of file lock.hpp.
Referenced by FutexLockImpl< Recursive >::lock(), FutexLockImpl< Recursive >::try_lock(), and FutexLockImpl< Recursive >::unlock().
_state
template<bool Recursive> uint32_t FutexLockImpl< Recursive >::_state private
Definition at line 117 of file lock.hpp.
Referenced by FutexLockImpl< Recursive >::lock(), FutexLockImpl< Recursive >::try_lock(), and FutexLockImpl< Recursive >::unlock().
ownerMask
template<bool Recursive> constexpr uint32_t FutexLockImpl< Recursive >::ownerMask = (static_cast<uint32_t>(1) << 30) - 1 static constexpr
Definition at line 20 of file lock.hpp.
Referenced by FutexLockImpl< Recursive >::lock(), FutexLockImpl< Recursive >::try_lock(), and FutexLockImpl< Recursive >::unlock().
waitersBit
template<bool Recursive> constexpr uint32_t FutexLockImpl< Recursive >::waitersBit = (1 << 31) static constexpr
Definition at line 19 of file lock.hpp.
Referenced by FutexLockImpl< Recursive >::lock(), and FutexLockImpl< Recursive >::unlock().
The documentation for this struct was generated from the following file:
Userspace/mlibc/options/internal/include/mlibc/lock.hpp