Fennix Userspace: Userspace/musl/src/malloc/calloc.c File Reference
calloc.c File Reference
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include "dynlink.h"
Functions
static size_t mal0_clear (char *p, size_t n)
static int allzerop (void *p)
weak_alias (allzerop, __malloc_allzerop)
void * calloc (size_t m, size_t n)
The standard function.
Function Documentation
allzerop()
static int allzerop (void * p) static
Definition at line 27 of file calloc.c.
 {
     return 0;
 }
mal0_clear()
static size_t mal0_clear (char * p, size_t n) static
Definition at line 7 of file calloc.c.
 {
     const size_t pagesz = 4096; /* arbitrary */
     if (n < pagesz) return n;
 #ifdef __GNUC__
     typedef uint64_t __attribute__((__may_alias__)) T;
 #else
     typedef unsigned char T;
 #endif
     char *pp = p + n;
     size_t i = (uintptr_t)pp & (pagesz - 1);
     for (;;) {
         pp = memset(pp - i, 0, i);
         if (pp - p < pagesz) return pp - p;
         for (i = pagesz; i; i -= 2*sizeof(T), pp -= 2*sizeof(T))
                 if (((T *)pp)[-1] | ((T *)pp)[-2])
                 break;
     }
 }
References __attribute__(), i, memset(), n, p, and T.
Referenced by calloc().
weak_alias()
weak_alias (allzerop , __malloc_allzerop)