Fennix Userspace: Userspace/apps/base/busybox/networking/nc.c File Reference
nc.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Macros
#define iobuf bb_common_bufsiz1
Functions
static void timeout (int signum UNUSED_PARAM)
int nc_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
iobuf
#define iobuf bb_common_bufsiz1
Function Documentation
nc_main()
int nc_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 119 of file nc.c.
 {
     /* sfd sits _here_ only because of "repeat" option (-l -l). */
     int sfd = sfd; /* for gcc */
     int cfd = 0;
     unsigned lport = 0;
     IF_NOT_NC_SERVER(const) unsigned do_listen = 0;
     IF_NOT_NC_EXTRA (const) unsigned wsecs = 0;
     IF_NOT_NC_EXTRA (const) unsigned delay = 0;
     IF_NOT_NC_EXTRA (const int execparam = 0;)
     IF_NC_EXTRA     (char **execparam = NULL;)
     struct pollfd pfds[2];
     int opt; /* must be signed (getopt returns -1) */
     if (ENABLE_NC_SERVER || ENABLE_NC_EXTRA) {
         /* getopt32 is _almost_ usable:
         ** it cannot handle "... -e PROG -prog-opt" */
         while ((opt = getopt(argc, argv,
             "" IF_NC_SERVER("lp:") IF_NC_EXTRA("w:i:f:e:") )) > 0
         ) {
             if (ENABLE_NC_SERVER && opt == 'l')
                 IF_NC_SERVER(do_listen++);
             else if (ENABLE_NC_SERVER && opt == 'p')
                 IF_NC_SERVER(lport = bb_lookup_port(optarg, "tcp", 0));
             else if (ENABLE_NC_EXTRA && opt == 'w')
                 IF_NC_EXTRA( wsecs = xatou(optarg));
             else if (ENABLE_NC_EXTRA && opt == 'i')
                 IF_NC_EXTRA( delay = xatou(optarg));
             else if (ENABLE_NC_EXTRA && opt == 'f')
                 IF_NC_EXTRA( cfd = xopen(optarg, O_RDWR));
             else if (ENABLE_NC_EXTRA && opt == 'e' && optind <= argc) {
                 /* We cannot just 'break'. We should let getopt finish.
                 ** Or else we won't be able to find where
                 ** 'host' and 'port' params are
                 ** (think "nc -w 60 host port -e PROG"). */
                 IF_NC_EXTRA(
                     char **p;
                     // +2: one for progname (optarg) and one for NULL
                     execparam = xzalloc(sizeof(char*) * (argc - optind + 2));
                     p = execparam;
                     *p++ = optarg;
                     while (optind < argc) {
                         *p++ = argv[optind++];
                     }
                 )
                 /* optind points to argv[argc] (NULL) now.
                 ** FIXME: we assume that getopt will not count options
                 ** possibly present on "-e PROG ARGS" and will not
                 ** include them into final value of optind
                 ** which is to be used ...  */
             } else bb_show_usage();
         }
         argv += optind; /* ... here! */
         argc -= optind;
         // -l and -f don't mix
         if (do_listen && cfd) bb_show_usage();
         // File mode needs need zero arguments, listen mode needs zero or one,
         // client mode needs one or two
         if (cfd) {
             if (argc) bb_show_usage();
         } else if (do_listen) {
             if (argc > 1) bb_show_usage();
         } else {
             if (!argc || argc > 2) bb_show_usage();
         }
     } else {
         if (argc != 3) bb_show_usage();
         argc--;
         argv++;
     }
     if (wsecs) {
         signal(SIGALRM, timeout);
         alarm(wsecs);
     }
     if (!cfd) {
         if (do_listen) {
             sfd = create_and_bind_stream_or_die(argv[0], lport);
             xlisten(sfd, do_listen); /* can be > 1 */
 #if 0  /* nc-1.10 does not do this (without -v) */
             /* If we didn't specify a port number,
              * query and print it after listen() */
             if (!lport) {
                 len_and_sockaddr lsa;
                 lsa.len = LSA_SIZEOF_SA;
                 getsockname(sfd, &lsa.u.sa, &lsa.len);
                 lport = get_nport(&lsa.u.sa);
                 fdprintf(2, "%d\n", ntohs(lport));
             }
 #endif
             close_on_exec_on(sfd);
  accept_again:
             cfd = accept(sfd, NULL, 0);
             if (cfd < 0)
                 bb_simple_perror_msg_and_die("accept");
             if (!execparam)
                 close(sfd);
         } else {
             cfd = create_and_connect_stream_or_die(argv[0],
                 bb_lookup_port(argv[1], "tcp", 0));
         }
     }
     if (wsecs) {
         alarm(0);
         /* Non-ignored signals revert to SIG_DFL on exec anyway */
         /*signal(SIGALRM, SIG_DFL);*/
     }
     /* -e given? */
     if (execparam) {
         pid_t pid;
         /* With more than one -l, repeatedly act as server */
         if (do_listen > 1 && (pid = xvfork()) != 0) {
             /* parent */
             /* prevent zombies */
             signal(SIGCHLD, SIG_IGN);
             close(cfd);
             goto accept_again;
         }
         /* child, or main thread if only one -l */
         xmove_fd(cfd, 0);
         xdup2(0, 1);
         /*xdup2(0, 2); - original nc 1.10 does this, we don't */
         IF_NC_EXTRA(BB_EXECVP(execparam[0], execparam);)
         IF_NC_EXTRA(bb_perror_msg_and_die("can't execute '%s'", execparam[0]);)
     }
     /* loop copying stdin to cfd, and cfd to stdout */
     pfds[0].fd = STDIN_FILENO;
     pfds[0].events = POLLIN;
     pfds[1].fd = cfd;
     pfds[1].events = POLLIN;
 #define iobuf bb_common_bufsiz1
     setup_common_bufsiz();
     for (;;) {
         int fdidx;
         int ofd;
         int nread;
         if (safe_poll(pfds, 2, -1) < 0)
             bb_simple_perror_msg_and_die("poll");
         fdidx = 0;
         while (1) {
             if (pfds[fdidx].revents) {
                 nread = safe_read(pfds[fdidx].fd, iobuf, COMMON_BUFSIZE);
                 if (fdidx != 0) {
                     if (nread < 1)
                         exit_SUCCESS();
                     ofd = STDOUT_FILENO;
                 } else {
                     if (nread < 1) {
                         /* Close outgoing half-connection so they get EOF,
                          * but leave incoming alone so we can see response */
                         shutdown(cfd, SHUT_WR);
                         pfds[0].fd = -1;
                     }
                     ofd = cfd;
                 }
                 xwrite(ofd, iobuf, nread);
                 if (delay > 0)
                     sleep(delay);
             }
             if (fdidx == 1)
                 break;
             fdidx++;
         }
     }
 }
References accept(), alarm(), argc, argv, BB_EXECVP, bb_lookup_port(), bb_perror_msg_and_die(), bb_show_usage(), bb_simple_perror_msg_and_die(), close(), close_on_exec_on(), create_and_bind_stream_or_die(), create_and_connect_stream_or_die(), exit_SUCCESS(), fd, fdprintf, get_nport(), getopt(), getsockname(), iobuf, lsa, LSA_SIZEOF_SA, ntohs(), NULL, O_RDWR, ofd, opt, optarg, optind, p, pid, POLLIN, safe_poll(), safe_read(), SHUT_WR, shutdown(), SIG_IGN, SIGALRM, SIGCHLD, signal, sleep(), STDIN_FILENO, STDOUT_FILENO, timeout(), xatou(), xdup2(), xlisten(), xmove_fd(), xopen(), xvfork, xwrite(), and xzalloc().
timeout()
static void timeout (int signum UNUSED_PARAM) static
Definition at line 113 of file nc.c.
 {
     bb_simple_error_msg_and_die("timed out");
 }
References bb_simple_error_msg_and_die().
Referenced by __res_msend_rc(), _rl_input_available(), ask_and_check_password_extended(), bb_ask_noecho(), chat_main(), input_avail(), isrv_run(), microcom_main(), nbdclient_main(), nc_main(), ntpd_main(), poll(), preadfd(), pscan_main(), read_byte(), read_key(), receive(), recvmmsg(), rl_gather_tyi(), safe_poll(), safe_read_key(), shell_builtin_read(), sigtimedwait(), sulogin_main(), timeout_main(), timeout_wait(), udhcpc6_main(), udhcpc_main(), and wait_for_seqfile().