Fennix: Userspace/apps/base/busybox/klibc-utils/nuke.c File Reference
nuke.c File Reference
#include "libbb.h"
Functions
int nuke_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
nuke_main()
int nuke_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 26 of file nuke.c.
 {
 // klibc-utils do not check opts, will try to delete "-dir" args
     //opt = getopt32(argv, "");
     //argv += optind;
     while (*++argv) {
 #if 0
 // klibc-utils do not check this, will happily operate on ".."
         const char *base = bb_get_last_path_component_strip(*argv);
         if (DOT_OR_DOTDOT(base)) {
             bb_error_msg("can't remove '.' or '..'");
             continue;
         }
 #endif
         remove_file(*argv, FILEUTILS_FORCE | FILEUTILS_RECUR);
     }
 // klibc-utils do not indicate errors
     return EXIT_SUCCESS;
 }
References argv, base, bb_error_msg(), bb_get_last_path_component_strip(), DOT_OR_DOTDOT, EXIT_SUCCESS, FILEUTILS_FORCE, FILEUTILS_RECUR, and remove_file().