Fennix Userspace: Userspace/apps/base/bash/mailcheck.c File Reference
mailcheck.c File Reference
#include "config.h"
#include <stdio.h>
#include "bashtypes.h"
#include "posixstat.h"
#include "posixtime.h"
#include "bashansi.h"
#include "bashintl.h"
#include "shell.h"
#include "execute_cmd.h"
#include "mailcheck.h"
#include <tilde/tilde.h>
Data Structures
struct _fileinfo
Macros
#define MBOX_INITIALIZED 0x01
#define RESET_MAIL_FILE(i)
#define UPDATE_MAIL_FILE(i, finfo)
#define atime mailfiles[i]->access_time
#define mtime mailfiles[i]->mod_time
Typedefs
typedef struct _fileinfo FILEINFO
Functions
int mailstat PARAMS ((const char *, struct stat *))
static int find_mail_file PARAMS ((char *))
static void init_mail_file PARAMS ((int))
static int add_mail_file PARAMS ((char *, char *))
static void dispose_mail_file PARAMS ((FILEINFO *))
int time_to_check_mail ()
void reset_mail_timer ()
static int find_mail_file (char *file)
static void init_mail_file (int i)
static void update_mail_file (int i)
static int add_mail_file (char *file, char *msg)
void reset_mail_files ()
static FILEINFO * alloc_mail_file (char *filename, char *msg)
static void dispose_mail_file (FILEINFO *mf)
void free_mail_files ()
void init_mail_dates ()
static int file_mod_date_changed (int i)
static int file_access_date_changed (int i)
static int file_has_grown (int i)
static char * parse_mailpath_spec (char *str)
char * make_default_mailpath ()
void remember_mail_dates ()
void check_mail ()
Variables
time_t shell_start_time
static FILEINFO ** mailfiles = (FILEINFO **)NULL
static int mailfiles_count
static time_t last_time_mail_checked = 0
int mail_warning
Data Structure Documentation
_fileinfo
struct _fileinfo
Definition at line 48 of file mailcheck.c.
Data Fields
time_t access_time
off_t file_size
int flags
time_t mod_time
char * msg
char * name
Macro Definition Documentation
atime
#define atime mailfiles[i]->access_time
MBOX_INITIALIZED
#define MBOX_INITIALIZED 0x01
Definition at line 42 of file mailcheck.c.
mtime
#define mtime mailfiles[i]->mod_time
RESET_MAIL_FILE
#define RESET_MAIL_FILE (i)
Value:
  do \
    { \
      mailfiles[i]->access_time = mailfiles[i]->mod_time = 0; \
      mailfiles[i]->file_size = 0; \
      mailfiles[i]->flags = 0; \
    } \
  while (0)
Definition at line 127 of file mailcheck.c.
UPDATE_MAIL_FILE
#define UPDATE_MAIL_FILE (i, finfo)
Value:
  do \
    { \
      mailfiles[i]->access_time = finfo.st_atime; \
      mailfiles[i]->mod_time = finfo.st_mtime; \
      mailfiles[i]->file_size = finfo.st_size; \
      mailfiles[i]->flags |= MBOX_INITIALIZED; \
    } \
  while (0)
Definition at line 136 of file mailcheck.c.
Typedef Documentation
FILEINFO
typedef struct _fileinfo FILEINFO
Function Documentation
add_mail_file()
static int add_mail_file (char * file, char * msg) static
Definition at line 172 of file mailcheck.c.
 {
   struct stat finfo;
   char *filename;
   int i;
   filename = full_pathname (file);
   i = find_mail_file (filename);
   if (i >= 0)
     {
       if (mailstat (filename, &finfo) == 0)
     UPDATE_MAIL_FILE (i, finfo);
       free (filename);
       return i;
     }
   i = mailfiles_count++;
   mailfiles = (FILEINFO **)xrealloc
         (mailfiles, mailfiles_count * sizeof (FILEINFO *));
   mailfiles[i] = alloc_mail_file (filename, msg);
   init_mail_file (i);
   return i;
 }
References alloc_mail_file(), filename, find_mail_file(), free, full_pathname(), i, init_mail_file(), mailfiles, mailfiles_count, mailstat(), UPDATE_MAIL_FILE, and xrealloc.
Referenced by remember_mail_dates().
alloc_mail_file()
static FILEINFO* alloc_mail_file (char * filename, char * msg) static
Definition at line 211 of file mailcheck.c.
 {
   FILEINFO *mf;
   mf = (FILEINFO *)xmalloc (sizeof (FILEINFO));
   mf->name = filename;
   mf->msg = msg ? savestring (msg) : (char *)NULL;
   mf->flags = 0;
   return mf;
 }
References filename, _fileinfo::flags, _fileinfo::msg, _fileinfo::name, NULL, savestring(), and xmalloc.
Referenced by add_mail_file().
check_mail()
void check_mail ()
Definition at line 417 of file mailcheck.c.
 {
   char *current_mail_file, *message;
   int i, use_user_notification;
   char *dollar_underscore, *temp;
   dollar_underscore = get_string_value ("_");
   if (dollar_underscore)
     dollar_underscore = savestring (dollar_underscore);
   for (i = 0; i < mailfiles_count; i++)
     {
       current_mail_file = mailfiles[i]->name;
       if (*current_mail_file == '\0')
     continue;
       if (file_mod_date_changed (i))
     {
       int file_is_bigger;
       use_user_notification = mailfiles[i]->msg != (char *)NULL;
       message = mailfiles[i]->msg ? mailfiles[i]->msg : _("You have mail in $_");
       bind_variable ("_", current_mail_file, 0);
 #define atime mailfiles[i]->access_time
 #define mtime mailfiles[i]->mod_time
       /* Have to compute this before the call to update_mail_file, which
          resets all the information. */
       file_is_bigger = file_has_grown (i);
       update_mail_file (i);
       /* If the user has just run a program which manipulates the
          mail file, then don't bother explaining that the mail
          file has been manipulated.  Since some systems don't change
          the access time to be equal to the modification time when
          the mail in the file is manipulated, check the size also.  If
          the file has not grown, continue. */
       if ((atime >= mtime) && !file_is_bigger)
         continue;
       /* If the mod time is later than the access time and the file
          has grown, note the fact that this is *new* mail. */
       if (use_user_notification == 0 && (atime < mtime) && file_is_bigger)
         message = _("You have new mail in $_");
 #undef atime
 #undef mtime
       if (temp = expand_string_to_string (message, Q_DOUBLE_QUOTES))
         {
           puts (temp);
           free (temp);
         }
       else
         putchar ('\n');
     }
       if (mail_warning && file_access_date_changed (i))
     {
       update_mail_file (i);
       printf (_("The mail in %s has been read\n"), current_mail_file);
     }
     }
   if (dollar_underscore)
     {
       bind_variable ("_", dollar_underscore, 0);
       free (dollar_underscore);
     }
   else
     unbind_variable ("_");
 }
References _, atime, bind_variable(), expand_string_to_string(), file_access_date_changed(), file_has_grown(), file_mod_date_changed(), free, get_string_value(), i, mail_warning, mailfiles, mailfiles_count, message(), _fileinfo::msg, mtime, _fileinfo::name, NULL, printf(), putchar, puts(), Q_DOUBLE_QUOTES, savestring(), unbind_variable(), and update_mail_file().
Referenced by yylex().
dispose_mail_file()
static void dispose_mail_file (FILEINFO * mf) static
Definition at line 225 of file mailcheck.c.
 {
   free (mf->name);
   FREE (mf->msg);
   free (mf);
 }
References FREE, free, _fileinfo::msg, and _fileinfo::name.
Referenced by free_mail_files().
file_access_date_changed()
static int file_access_date_changed (int i) static
Definition at line 284 of file mailcheck.c.
 {
   time_t atime;
   struct stat finfo;
   char *file;
   file = mailfiles[i]->name;
   atime = mailfiles[i]->access_time;
   if (mailstat (file, &finfo) != 0)
     return (0);
   if (finfo.st_size > 0)
     return (atime < finfo.st_atime);
   return (0);
 }
References _fileinfo::access_time, atime, i, mailfiles, mailstat(), _fileinfo::name, and stat::st_size.
Referenced by check_mail().
file_has_grown()
static int file_has_grown (int i) static
Definition at line 305 of file mailcheck.c.
 {
   off_t size;
   struct stat finfo;
   char *file;
   file = mailfiles[i]->name;
   size = mailfiles[i]->file_size;
   return ((mailstat (file, &finfo) == 0) && (finfo.st_size > size));
 }
References _fileinfo::file_size, i, mailfiles, mailstat(), _fileinfo::name, off_t, size, and stat::st_size.
Referenced by check_mail().
file_mod_date_changed()
static int file_mod_date_changed (int i) static
Definition at line 260 of file mailcheck.c.
 {
   time_t mtime;
   struct stat finfo;
   char *file;
   file = mailfiles[i]->name;
   mtime = mailfiles[i]->mod_time;
   if (mailstat (file, &finfo) != 0)
     return (0);
   if (finfo.st_size > 0)
     return (mtime < finfo.st_mtime);
   if (finfo.st_size == 0 && mailfiles[i]->file_size > 0)
     UPDATE_MAIL_FILE (i, finfo);
   return (0);
 }
References _fileinfo::file_size, i, mailfiles, mailstat(), _fileinfo::mod_time, mtime, _fileinfo::name, stat::st_size, and UPDATE_MAIL_FILE.
Referenced by check_mail().
find_mail_file()
static int find_mail_file (char * file) static
Definition at line 115 of file mailcheck.c.
 {
   register int i;
   for (i = 0; i < mailfiles_count; i++)
     if (STREQ (mailfiles[i]->name, file))
       return i;
   return -1;
 }
References i, mailfiles, mailfiles_count, and STREQ.
Referenced by add_mail_file().
free_mail_files()
void free_mail_files ()
Definition at line 235 of file mailcheck.c.
 {
   register int i;
   for (i = 0; i < mailfiles_count; i++)
     dispose_mail_file (mailfiles[i]);
   if (mailfiles)
     free (mailfiles);
   mailfiles_count = 0;
   mailfiles = (FILEINFO **)NULL;
 }
References dispose_mail_file(), free, i, mailfiles, mailfiles_count, and NULL.
Referenced by sv_mail().
init_mail_dates()
void init_mail_dates ()
Definition at line 250 of file mailcheck.c.
 {
   if (mailfiles == 0)
     remember_mail_dates ();
 }
References mailfiles, and remember_mail_dates().
Referenced by main().
init_mail_file()
static void init_mail_file (int i) static
Definition at line 147 of file mailcheck.c.
 {
   mailfiles[i]->access_time = mailfiles[i]->mod_time = last_time_mail_checked ? last_time_mail_checked : shell_start_time;
   mailfiles[i]->file_size = 0;
   mailfiles[i]->flags = 0;
 }
References _fileinfo::access_time, _fileinfo::file_size, _fileinfo::flags, i, last_time_mail_checked, mailfiles, _fileinfo::mod_time, and shell_start_time.
Referenced by add_mail_file().
make_default_mailpath()
char* make_default_mailpath ()
Definition at line 347 of file mailcheck.c.
 {
 #if defined (DEFAULT_MAIL_DIRECTORY)
   char *mp;
   get_current_user_info ();
   mp = (char *)xmalloc (2 + sizeof (DEFAULT_MAIL_DIRECTORY) + strlen (current_user.user_name));
   strcpy (mp, DEFAULT_MAIL_DIRECTORY);
   mp[sizeof(DEFAULT_MAIL_DIRECTORY) - 1] = '/';
   strcpy (mp + sizeof (DEFAULT_MAIL_DIRECTORY), current_user.user_name);
   return (mp);
 #else
   return ((char *)NULL);
 #endif
 }
References current_user, get_current_user_info(), NULL, strcpy(), strlen(), user_info::user_name, and xmalloc.
Referenced by remember_mail_dates().
PARAMS() [1/5]
static int find_mail_file PARAMS ((char *)) static
PARAMS() [2/5]
static int add_mail_file PARAMS ((char *, char *)) static
PARAMS() [3/5]
int mailstat PARAMS ((const char *, struct stat *))
PARAMS() [4/5]
static void dispose_mail_file PARAMS ((FILEINFO *)) static
PARAMS() [5/5]
static void init_mail_file PARAMS ((int)) static
parse_mailpath_spec()
static char* parse_mailpath_spec (char * str) static
Definition at line 322 of file mailcheck.c.
 {
   char *s;
   int pass_next;
   for (s = str, pass_next = 0; s && *s; s++)
     {
       if (pass_next)
     {
       pass_next = 0;
       continue;
     }
       if (*s == '\\')
     {
       pass_next++;
       continue;
     }
       if (*s == '?' || *s == '%')
     return s;
     }
   return ((char *)NULL);
 }
References NULL, s, and str.
Referenced by remember_mail_dates().
remember_mail_dates()
void remember_mail_dates ()
Definition at line 368 of file mailcheck.c.
 {
   char *mailpaths;
   char *mailfile, *mp;
   int i = 0;
   mailpaths = get_string_value ("MAILPATH");
   /* If no $MAILPATH, but $MAIL, use that as a single filename to check. */
   if (mailpaths == 0 && (mailpaths = get_string_value ("MAIL")))
     {
       add_mail_file (mailpaths, (char *)NULL);
       return;
     }
   if (mailpaths == 0)
     {
       mailpaths = make_default_mailpath ();
       if (mailpaths)
     {
       add_mail_file (mailpaths, (char *)NULL);
       free (mailpaths);
     }
       return;
     }
   while (mailfile = extract_colon_unit (mailpaths, &i))
     {
       mp = parse_mailpath_spec (mailfile);
       if (mp && *mp)
     *mp++ = '\0';
       add_mail_file (mailfile, mp);
       free (mailfile);
     }
 }
References add_mail_file(), extract_colon_unit(), free, get_string_value(), i, make_default_mailpath(), NULL, and parse_mailpath_spec().
Referenced by init_mail_dates(), and sv_mail().
reset_mail_files()
void reset_mail_files ()
Definition at line 202 of file mailcheck.c.
 {
   register int i;
   for (i = 0; i < mailfiles_count; i++)
     RESET_MAIL_FILE (i);
 }
References i, mailfiles_count, and RESET_MAIL_FILE.
reset_mail_timer()
void reset_mail_timer ()
Definition at line 107 of file mailcheck.c.
 {
   last_time_mail_checked = NOW;
 }
References last_time_mail_checked, and NOW.
Referenced by main(), sv_mail(), and yylex().
time_to_check_mail()
int time_to_check_mail ()
Definition at line 85 of file mailcheck.c.
 {
   char *temp;
   time_t now;
   intmax_t seconds;
   temp = get_string_value ("MAILCHECK");
   /* Negative number, or non-numbers (such as empty string) cause no
      checking to take place. */
   if (temp == 0 || legal_number (temp, &seconds) == 0 || seconds < 0)
     return (0);
   now = NOW;
   /* Time to check if MAILCHECK is explicitly set to zero, or if enough
      time has passed since the last check. */
   return (seconds == 0 || ((now - last_time_mail_checked) >= seconds));
 }
References get_string_value(), last_time_mail_checked, legal_number(), and NOW.
Referenced by yylex().
update_mail_file()
static void update_mail_file (int i) static
Definition at line 156 of file mailcheck.c.
 {
   char *file;
   struct stat finfo;
   file = mailfiles[i]->name;
   if (mailstat (file, &finfo) == 0)
     UPDATE_MAIL_FILE (i, finfo);
   else
     RESET_MAIL_FILE (i);
 }
References i, mailfiles, mailstat(), _fileinfo::name, RESET_MAIL_FILE, and UPDATE_MAIL_FILE.
Referenced by check_mail().
Variable Documentation
last_time_mail_checked
time_t last_time_mail_checked = 0 static
Definition at line 64 of file mailcheck.c.
Referenced by init_mail_file(), reset_mail_timer(), and time_to_check_mail().
mail_warning
int mail_warning
Definition at line 67 of file mailcheck.c.
Referenced by check_mail().
mailfiles
FILEINFO** mailfiles = (FILEINFO **)NULL static
Definition at line 58 of file mailcheck.c.
Referenced by add_mail_file(), check_mail(), file_access_date_changed(), file_has_grown(), file_mod_date_changed(), find_mail_file(), free_mail_files(), init_mail_dates(), init_mail_file(), and update_mail_file().
mailfiles_count
int mailfiles_count static
Definition at line 61 of file mailcheck.c.
Referenced by add_mail_file(), check_mail(), find_mail_file(), free_mail_files(), and reset_mail_files().
shell_start_time
time_t shell_start_time extern
Definition at line 183 of file shell.c.
Referenced by init_mail_file().