Fennix: Xalloc::Block Class Reference
Xalloc::Block Class Reference
Public Member Functions
bool Check ()
Block (Xsize_t Size)
~Block ()
void * operator new (Xsize_t Size)
Overload new operator to allocate memory from the heap.
void operator delete (void *Address)
Overload delete operator to free memory from the heap.
Data Fields
void * Address = nullptr
int Checksum = Xalloc_BlockChecksum
Xsize_t Size = 0
Block * Next = nullptr
Block * Last = nullptr
bool IsFree = true
Detailed Description
Definition at line 53 of file XallocV1.cpp.
Constructor & Destructor Documentation
Block()
Xalloc::Block::Block (Xsize_t Size) inline
Definition at line 71 of file XallocV1.cpp.
         {
             this->Address = Xalloc_REQUEST_PAGES(XStoP(Size + 1));
             this->Size = Size;
             Xmemset(this->Address, 0, Size);
         }
References Size, Xalloc_REQUEST_PAGES(), Xmemset(), and XStoP.
~Block()
Xalloc::Block::~Block () inline
Definition at line 78 of file XallocV1.cpp.
         {
             Xalloc_FREE_PAGES(this->Address, XStoP(this->Size + 1));
         }
References Xalloc_FREE_PAGES(), and XStoP.
Member Function Documentation
Check()
bool Xalloc::Block::Check () inline
Definition at line 64 of file XallocV1.cpp.
         {
             if (this->Checksum != Xalloc_BlockChecksum)
                 return false;
             return true;
         }
References Xalloc_BlockChecksum.
Referenced by Xalloc::V1::free(), and Xalloc::V1::malloc().
operator delete()
void Xalloc::Block::operator delete (void * Address) inline
Overload delete operator to free memory from the heap.
Parameters
Address Pointer to the memory to free
Definition at line 99 of file XallocV1.cpp.
         {
             Xalloc_FREE_PAGES(Address, XStoP(sizeof(Block)));
         }
References Address, Xalloc_FREE_PAGES(), and XStoP.
operator new()
void* Xalloc::Block::operator new (Xsize_t Size) inline
Overload new operator to allocate memory from the heap.
Parameters
Size Unused
Returns
void* Pointer to the allocated memory
Definition at line 88 of file XallocV1.cpp.
         {
             void *ptr = Xalloc_REQUEST_PAGES(XStoP(sizeof(Block)));
             return ptr;
             (void)(Size);
         }
References Size, Driver::void(), Xalloc_REQUEST_PAGES(), and XStoP.
Field Documentation
Address
void* Xalloc::Block::Address = nullptr
Definition at line 56 of file XallocV1.cpp.
Referenced by Xalloc::V1::free(), Xalloc::V1::malloc(), and operator delete().
Checksum
int Xalloc::Block::Checksum = Xalloc_BlockChecksum
Definition at line 58 of file XallocV1.cpp.
Referenced by Xalloc::V1::free(), and Xalloc::V1::malloc().
IsFree
bool Xalloc::Block::IsFree = true
Definition at line 62 of file XallocV1.cpp.
Referenced by Xalloc::V1::free(), and Xalloc::V1::malloc().
Last
Block* Xalloc::Block::Last = nullptr
Definition at line 61 of file XallocV1.cpp.
Next
Block* Xalloc::Block::Next = nullptr
Definition at line 60 of file XallocV1.cpp.
Referenced by Xalloc::V1::free(), and Xalloc::V1::malloc().
Size
Xsize_t Xalloc::Block::Size = 0
Definition at line 59 of file XallocV1.cpp.
Referenced by Block(), Xalloc::V1::malloc(), and operator new().
The documentation for this class was generated from the following file:
Kernel/Core/Memory/HeapAllocators/Xalloc/XallocV1.cpp