Fennix: Userspace/apps/base/busybox/shell/math.c File Reference
math.c File Reference
#include "libbb.h"
#include "math.h"
Data Structures
struct var_or_num_t
struct remembered_name
Macros
#define tok_decl(prec, id) (((id)<<5) | (prec))
#define PREC(op) ((op) & 0x1F)
#define TOK_LPAREN tok_decl(0,0)
#define TOK_COMMA tok_decl(1,0)
#define TOK_ASSIGN tok_decl(2,0)
#define TOK_AND_ASSIGN tok_decl(2,1)
#define TOK_OR_ASSIGN tok_decl(2,2)
#define TOK_XOR_ASSIGN tok_decl(2,3)
#define TOK_PLUS_ASSIGN tok_decl(2,4)
#define TOK_MINUS_ASSIGN tok_decl(2,5)
#define TOK_LSHIFT_ASSIGN tok_decl(2,6)
#define TOK_RSHIFT_ASSIGN tok_decl(2,7)
#define TOK_MUL_ASSIGN tok_decl(3,0)
#define TOK_DIV_ASSIGN tok_decl(3,1)
#define TOK_REM_ASSIGN tok_decl(3,2)
#define fix_assignment_prec(prec) do { if (prec == 3) prec = 2; } while (0)
#define TOK_CONDITIONAL tok_decl(4,0)
#define TOK_CONDITIONAL_SEP tok_decl(4,1)
#define TOK_OR tok_decl(5,0)
#define TOK_AND tok_decl(6,0)
#define TOK_BOR tok_decl(7,0)
#define TOK_BXOR tok_decl(8,0)
#define TOK_BAND tok_decl(9,0)
#define TOK_EQ tok_decl(10,0)
#define TOK_NE tok_decl(10,1)
#define TOK_LT tok_decl(11,0)
#define TOK_GT tok_decl(11,1)
#define TOK_GE tok_decl(11,2)
#define TOK_LE tok_decl(11,3)
#define TOK_LSHIFT tok_decl(12,0)
#define TOK_RSHIFT tok_decl(12,1)
#define TOK_ADD tok_decl(13,0)
#define TOK_SUB tok_decl(13,1)
#define TOK_MUL tok_decl(14,0)
#define TOK_DIV tok_decl(14,1)
#define TOK_REM tok_decl(14,2)
#define TOK_EXPONENT tok_decl(15,1)
#define UNARYPREC 16
#define TOK_BNOT tok_decl(UNARYPREC,0)
#define TOK_NOT tok_decl(UNARYPREC,1)
#define TOK_UMINUS tok_decl(UNARYPREC+1,0)
#define TOK_UPLUS tok_decl(UNARYPREC+1,1)
#define PREC_PRE (UNARYPREC+2)
#define TOK_PRE_INC tok_decl(PREC_PRE, 0)
#define TOK_PRE_DEC tok_decl(PREC_PRE, 1)
#define PREC_POST (UNARYPREC+3)
#define TOK_POST_INC tok_decl(PREC_POST, 0)
#define TOK_POST_DEC tok_decl(PREC_POST, 1)
#define SPEC_PREC (UNARYPREC+4)
#define TOK_NUM tok_decl(SPEC_PREC, 0)
#define TOK_RPAREN tok_decl(SPEC_PREC, 1)
#define NUMPTR (*numstackptr)
#define ptr_to_rparen (&op_tokens[sizeof(op_tokens)-7])
#define strto_arith_t(nptr, endptr) strtoul(nptr, endptr, 0)
Typedefs
typedef unsigned char operator
typedef struct remembered_name remembered_name
Functions
static int is_assign_op (operator op)
static int is_right_associative (operator prec)
static arith_t evaluate_string (arith_state_t *math_state, const char *expr)
static const char * arith_lookup_val (arith_state_t *math_state, var_or_num_t *t)
static NOINLINE const char * arith_apply (arith_state_t *math_state, operator op, var_or_num_t *numstack, var_or_num_t **numstackptr)
arith_t FAST_FUNC arith (arith_state_t *math_state, const char *expr)
Variables
static const char op_tokens[] ALIGN1
Data Structure Documentation
var_or_num_t
struct var_or_num_t
Definition at line 230 of file math.c.
Data Fields
arith_t second_val
char second_val_present
arith_t val
char * var
remembered_name
struct remembered_name
Definition at line 244 of file math.c.
Data Fields
struct remembered_name * next
const char * var
Macro Definition Documentation
fix_assignment_prec
#define fix_assignment_prec (prec) do { if (prec == 3) prec = 2; } while (0)
Definition at line 151 of file math.c.
NUMPTR
#define NUMPTR (*numstackptr)
PREC
#define PREC (op) ((op) & 0x1F)
Definition at line 128 of file math.c.
PREC_POST
#define PREC_POST (UNARYPREC+3)
Definition at line 201 of file math.c.
PREC_PRE
#define PREC_PRE (UNARYPREC+2)
Definition at line 196 of file math.c.
ptr_to_rparen
#define ptr_to_rparen (&op_tokens[sizeof(op_tokens)-7])
Definition at line 509 of file math.c.
SPEC_PREC
#define SPEC_PREC (UNARYPREC+4)
Definition at line 206 of file math.c.
strto_arith_t
#define strto_arith_t (nptr, endptr) strtoul(nptr, endptr, 0)
Definition at line 576 of file math.c.
TOK_ADD
#define TOK_ADD tok_decl(13,0)
Definition at line 178 of file math.c.
TOK_AND
#define TOK_AND tok_decl(6,0)
Definition at line 159 of file math.c.
TOK_AND_ASSIGN
#define TOK_AND_ASSIGN tok_decl(2,1)
Definition at line 139 of file math.c.
TOK_ASSIGN
#define TOK_ASSIGN tok_decl(2,0)
Definition at line 138 of file math.c.
TOK_BAND
#define TOK_BAND tok_decl(9,0)
Definition at line 165 of file math.c.
TOK_BNOT
#define TOK_BNOT tok_decl(UNARYPREC,0)
Definition at line 190 of file math.c.
TOK_BOR
#define TOK_BOR tok_decl(7,0)
Definition at line 161 of file math.c.
TOK_BXOR
#define TOK_BXOR tok_decl(8,0)
Definition at line 163 of file math.c.
TOK_COMMA
#define TOK_COMMA tok_decl(1,0)
Definition at line 132 of file math.c.
TOK_CONDITIONAL
#define TOK_CONDITIONAL tok_decl(4,0)
Definition at line 154 of file math.c.
TOK_CONDITIONAL_SEP
#define TOK_CONDITIONAL_SEP tok_decl(4,1)
Definition at line 155 of file math.c.
tok_decl
#define tok_decl (prec, id) (((id)<<5) | (prec))
Definition at line 127 of file math.c.
TOK_DIV
#define TOK_DIV tok_decl(14,1)
Definition at line 182 of file math.c.
TOK_DIV_ASSIGN
#define TOK_DIV_ASSIGN tok_decl(3,1)
Definition at line 148 of file math.c.
TOK_EQ
#define TOK_EQ tok_decl(10,0)
Definition at line 167 of file math.c.
TOK_EXPONENT
#define TOK_EXPONENT tok_decl(15,1)
Definition at line 186 of file math.c.
TOK_GE
#define TOK_GE tok_decl(11,2)
Definition at line 172 of file math.c.
TOK_GT
#define TOK_GT tok_decl(11,1)
Definition at line 171 of file math.c.
TOK_LE
#define TOK_LE tok_decl(11,3)
Definition at line 173 of file math.c.
TOK_LPAREN
#define TOK_LPAREN tok_decl(0,0)
Definition at line 130 of file math.c.
TOK_LSHIFT
#define TOK_LSHIFT tok_decl(12,0)
Definition at line 175 of file math.c.
TOK_LSHIFT_ASSIGN
#define TOK_LSHIFT_ASSIGN tok_decl(2,6)
Definition at line 144 of file math.c.
TOK_LT
#define TOK_LT tok_decl(11,0)
Definition at line 170 of file math.c.
TOK_MINUS_ASSIGN
#define TOK_MINUS_ASSIGN tok_decl(2,5)
Definition at line 143 of file math.c.
TOK_MUL
#define TOK_MUL tok_decl(14,0)
Definition at line 181 of file math.c.
TOK_MUL_ASSIGN
#define TOK_MUL_ASSIGN tok_decl(3,0)
Definition at line 147 of file math.c.
TOK_NE
#define TOK_NE tok_decl(10,1)
Definition at line 168 of file math.c.
TOK_NOT
#define TOK_NOT tok_decl(UNARYPREC,1)
Definition at line 191 of file math.c.
TOK_NUM
#define TOK_NUM tok_decl(SPEC_PREC, 0)
Definition at line 208 of file math.c.
TOK_OR
#define TOK_OR tok_decl(5,0)
Definition at line 157 of file math.c.
TOK_OR_ASSIGN
#define TOK_OR_ASSIGN tok_decl(2,2)
Definition at line 140 of file math.c.
TOK_PLUS_ASSIGN
#define TOK_PLUS_ASSIGN tok_decl(2,4)
Definition at line 142 of file math.c.
TOK_POST_DEC
#define TOK_POST_DEC tok_decl(PREC_POST, 1)
Definition at line 204 of file math.c.
TOK_POST_INC
#define TOK_POST_INC tok_decl(PREC_POST, 0)
Definition at line 203 of file math.c.
TOK_PRE_DEC
#define TOK_PRE_DEC tok_decl(PREC_PRE, 1)
Definition at line 199 of file math.c.
TOK_PRE_INC
#define TOK_PRE_INC tok_decl(PREC_PRE, 0)
Definition at line 198 of file math.c.
TOK_REM
#define TOK_REM tok_decl(14,2)
Definition at line 183 of file math.c.
TOK_REM_ASSIGN
#define TOK_REM_ASSIGN tok_decl(3,2)
Definition at line 149 of file math.c.
TOK_RPAREN
#define TOK_RPAREN tok_decl(SPEC_PREC, 1)
Definition at line 209 of file math.c.
TOK_RSHIFT
#define TOK_RSHIFT tok_decl(12,1)
Definition at line 176 of file math.c.
TOK_RSHIFT_ASSIGN
#define TOK_RSHIFT_ASSIGN tok_decl(2,7)
Definition at line 145 of file math.c.
TOK_SUB
#define TOK_SUB tok_decl(13,1)
Definition at line 179 of file math.c.
TOK_UMINUS
#define TOK_UMINUS tok_decl(UNARYPREC+1,0)
Definition at line 193 of file math.c.
TOK_UPLUS
#define TOK_UPLUS tok_decl(UNARYPREC+1,1)
Definition at line 194 of file math.c.
TOK_XOR_ASSIGN
#define TOK_XOR_ASSIGN tok_decl(2,3)
Definition at line 141 of file math.c.
UNARYPREC
#define UNARYPREC 16
Definition at line 189 of file math.c.
Typedef Documentation
operator
typedef unsigned char operator
Definition at line 119 of file math.c.
remembered_name
typedef struct remembered_name remembered_name
Function Documentation
arith()
arith_t FAST_FUNC arith (arith_state_t * math_state, const char * expr)
Definition at line 819 of file math.c.
 {
     math_state->errmsg = NULL;
     math_state->list_of_recursed_names = NULL;
     return evaluate_string(math_state, expr);
 }
References arith_state_t::errmsg, evaluate_string(), arith_state_t::list_of_recursed_names, and NULL.
arith_apply()
static NOINLINE const char* arith_apply (arith_state_t * math_state, operator op, var_or_num_t * numstack, var_or_num_t ** numstackptr) static
Definition at line 296 of file math.c.
 {
 #define NUMPTR (*numstackptr)
     var_or_num_t *top_of_stack;
     arith_t rez;
     const char *err;
     /* There is no operator that can work without arguments */
     if (NUMPTR == numstack)
         goto err;
     top_of_stack = NUMPTR - 1;
     /* Resolve name to value, if needed */
     err = arith_lookup_val(math_state, top_of_stack);
     if (err)
         return err;
     rez = top_of_stack->val;
     if (op == TOK_UMINUS)
         rez = -rez;
     else if (op == TOK_NOT)
         rez = !rez;
     else if (op == TOK_BNOT)
         rez = ~rez;
     else if (op == TOK_POST_INC || op == TOK_PRE_INC)
         rez++;
     else if (op == TOK_POST_DEC || op == TOK_PRE_DEC)
         rez--;
     else if (op != TOK_UPLUS) {
         /* Binary operators */
         arith_t right_side_val;
         char bad_second_val;
         /* Binary operators need two arguments */
         if (top_of_stack == numstack)
             goto err;
         /* ...and they pop one */
         NUMPTR = top_of_stack; /* this decrements NUMPTR */
         bad_second_val = top_of_stack->second_val_present;
         if (op == TOK_CONDITIONAL) { /* ? operation */
             /* Make next if (...) protect against
              * $((expr1 ? expr2)) - that is, missing ": expr" */
             bad_second_val = !bad_second_val;
         }
         if (bad_second_val) {
             /* Protect against $((expr <not_?_op> expr1 : expr2)) */
             return "malformed ?: operator";
         }
         top_of_stack--; /* now points to left side */
         if (op != TOK_ASSIGN) {
             /* Resolve left side value (unless the op is '=') */
             err = arith_lookup_val(math_state, top_of_stack);
             if (err)
                 return err;
         }
         right_side_val = rez;
         rez = top_of_stack->val;
         if (op == TOK_CONDITIONAL) /* ? operation */
             rez = (rez ? right_side_val : top_of_stack[1].second_val);
         else if (op == TOK_CONDITIONAL_SEP) { /* : operation */
             if (top_of_stack == numstack) {
                 /* Protect against $((expr : expr)) */
                 return "malformed ?: operator";
             }
             top_of_stack->second_val_present = op;
             top_of_stack->second_val = right_side_val;
         }
         else if (op == TOK_BOR || op == TOK_OR_ASSIGN)
             rez |= right_side_val;
         else if (op == TOK_OR)
             rez = right_side_val || rez;
         else if (op == TOK_BAND || op == TOK_AND_ASSIGN)
             rez &= right_side_val;
         else if (op == TOK_BXOR || op == TOK_XOR_ASSIGN)
             rez ^= right_side_val;
         else if (op == TOK_AND)
             rez = rez && right_side_val;
         else if (op == TOK_EQ)
             rez = (rez == right_side_val);
         else if (op == TOK_NE)
             rez = (rez != right_side_val);
         else if (op == TOK_GE)
             rez = (rez >= right_side_val);
         else if (op == TOK_RSHIFT || op == TOK_RSHIFT_ASSIGN)
             rez >>= right_side_val;
         else if (op == TOK_LSHIFT || op == TOK_LSHIFT_ASSIGN)
             rez <<= right_side_val;
         else if (op == TOK_GT)
             rez = (rez > right_side_val);
         else if (op == TOK_LT)
             rez = (rez < right_side_val);
         else if (op == TOK_LE)
             rez = (rez <= right_side_val);
         else if (op == TOK_MUL || op == TOK_MUL_ASSIGN)
             rez *= right_side_val;
         else if (op == TOK_ADD || op == TOK_PLUS_ASSIGN)
             rez += right_side_val;
         else if (op == TOK_SUB || op == TOK_MINUS_ASSIGN)
             rez -= right_side_val;
         else if (op == TOK_ASSIGN || op == TOK_COMMA)
             rez = right_side_val;
         else if (op == TOK_EXPONENT) {
             arith_t c;
             if (right_side_val < 0)
                 return "exponent less than 0";
             c = 1;
             while (--right_side_val >= 0)
                 c *= rez;
             rez = c;
         }
         else if (right_side_val == 0)
             return "divide by zero";
         else if (op == TOK_DIV || op == TOK_DIV_ASSIGN
               || op == TOK_REM || op == TOK_REM_ASSIGN) {
             /*
              * bash 4.2.45 x86 64bit: SEGV on 'echo $((2**63 / -1))'
              *
              * MAX_NEGATIVE_INT / -1 = MAX_POSITIVE_INT+1
              * and thus is not representable.
              * Some CPUs segfault trying such op.
              * Others overflow MAX_POSITIVE_INT+1 to
              * MAX_NEGATIVE_INT (0x7fff+1 = 0x8000).
              * Make sure to at least not SEGV here:
              */
             if (right_side_val == -1
              && rez << 1 == 0 /* MAX_NEGATIVE_INT or 0 */
             ) {
                 right_side_val = 1;
             }
             if (op == TOK_DIV || op == TOK_DIV_ASSIGN)
                 rez /= right_side_val;
             else {
                 rez %= right_side_val;
             }
         }
     }
     if (is_assign_op(op)) {
         char buf[sizeof(arith_t)*3 + 2];
         if (top_of_stack->var == NULL) {
             /* Hmm, 1=2 ? */
             goto err;
         }
         /* Save to shell variable */
         sprintf(buf, ARITH_FMT, rez);
         math_state->setvar(top_of_stack->var, buf);
         /* After saving, make previous value for v++ or v-- */
         if (op == TOK_POST_INC)
             rez--;
         if (op == TOK_POST_DEC)
             rez++;
     }
     top_of_stack->val = rez;
     /* Erase var name, it is just a number now */
     top_of_stack->var = NULL;
     return NULL;
  err:
     return "arithmetic syntax error";
 #undef NUMPTR
 }
References ARITH_FMT, arith_lookup_val(), buf, c, err(), is_assign_op(), NULL, NUMPTR, var_or_num_t::second_val, var_or_num_t::second_val_present, arith_state_t::setvar, sprintf(), TOK_ADD, TOK_AND, TOK_AND_ASSIGN, TOK_ASSIGN, TOK_BAND, TOK_BNOT, TOK_BOR, TOK_BXOR, TOK_COMMA, TOK_CONDITIONAL, TOK_CONDITIONAL_SEP, TOK_DIV, TOK_DIV_ASSIGN, TOK_EQ, TOK_EXPONENT, TOK_GE, TOK_GT, TOK_LE, TOK_LSHIFT, TOK_LSHIFT_ASSIGN, TOK_LT, TOK_MINUS_ASSIGN, TOK_MUL, TOK_MUL_ASSIGN, TOK_NE, TOK_NOT, TOK_OR, TOK_OR_ASSIGN, TOK_PLUS_ASSIGN, TOK_POST_DEC, TOK_POST_INC, TOK_PRE_DEC, TOK_PRE_INC, TOK_REM, TOK_REM_ASSIGN, TOK_RSHIFT, TOK_RSHIFT_ASSIGN, TOK_SUB, TOK_UMINUS, TOK_UPLUS, TOK_XOR_ASSIGN, var_or_num_t::val, and var_or_num_t::var.
Referenced by evaluate_string().
arith_lookup_val()
static const char* arith_lookup_val (arith_state_t * math_state, var_or_num_t * t) static
Definition at line 254 of file math.c.
 {
     if (t->var) {
         const char *p = math_state->lookupvar(t->var);
         if (p) {
             remembered_name *cur;
             remembered_name cur_save;
             /* did we already see this name?
              * testcase: a=b; b=a; echo $((a))
              */
             for (cur = math_state->list_of_recursed_names; cur; cur = cur->next) {
                 if (strcmp(cur->var, t->var) == 0) {
                     /* Yes */
                     return "expression recursion loop detected";
                 }
             }
             /* push current var name */
             cur = math_state->list_of_recursed_names;
             cur_save.var = t->var;
             cur_save.next = cur;
             math_state->list_of_recursed_names = &cur_save;
             /* recursively evaluate p as expression */
             t->val = evaluate_string(math_state, p);
             /* pop current var name */
             math_state->list_of_recursed_names = cur;
             return math_state->errmsg;
         }
         /* treat undefined var as 0 */
         t->val = 0;
     }
     return 0;
 }
References cur, arith_state_t::errmsg, evaluate_string(), arith_state_t::list_of_recursed_names, arith_state_t::lookupvar, remembered_name::next, p, strcmp, t, and remembered_name::var.
Referenced by arith_apply(), and evaluate_string().
evaluate_string()
static arith_t evaluate_string (arith_state_t * math_state, const char * expr) static
Definition at line 581 of file math.c.
 {
     operator lasttok;
     const char *errmsg;
     const char *start_expr = expr = skip_whitespace(expr);
     unsigned expr_len = strlen(expr) + 2;
     /* Stack of integers */
     /* The proof that there can be no more than strlen(startbuf)/2+1
      * integers in any given correct or incorrect expression
      * is left as an exercise to the reader. */
     var_or_num_t *const numstack = alloca((expr_len / 2) * sizeof(numstack[0]));
     var_or_num_t *numstackptr = numstack;
     /* Stack of operator tokens */
     operator *const stack = alloca(expr_len * sizeof(stack[0]));
     operator *stackptr = stack;
     /* Start with a left paren */
     *stackptr++ = lasttok = TOK_LPAREN;
     errmsg = NULL;
     while (1) {
         const char *p;
         operator op;
         operator prec;
         expr = skip_whitespace(expr);
         if (*expr == '\0') {
             if (expr == start_expr) {
                 /* Null expression */
                 numstack->val = 0;
                 goto ret;
             }
             /* This is only reached after all tokens have been extracted from the
              * input stream. If there are still tokens on the operator stack, they
              * are to be applied in order. At the end, there should be a final
              * result on the integer stack */
             if (expr != ptr_to_rparen + 1) {
                 /* If we haven't done so already,
                  * append a closing right paren
                  * and let the loop process it */
                 expr = ptr_to_rparen;
 //bb_error_msg("expr=')'");
                 continue;
             }
             /* At this point, we're done with the expression */
             if (numstackptr != numstack + 1) {
                 /* ...but if there isn't, it's bad */
                 goto err;
             }
             goto ret;
         }
         p = endofname(expr);
         if (p != expr) {
             /* Name */
             size_t var_name_size = (p - expr) + 1;  /* +1 for NUL */
             numstackptr->var = alloca(var_name_size);
             safe_strncpy(numstackptr->var, expr, var_name_size);
 //bb_error_msg("var:'%s'", numstackptr->var);
             expr = p;
  num:
             numstackptr->second_val_present = 0;
             numstackptr++;
             lasttok = TOK_NUM;
             continue;
         }
         if (isdigit(*expr)) {
             /* Number */
             numstackptr->var = NULL;
             errno = 0;
             numstackptr->val = strto_arith_t(expr, (char**) &expr);
 //bb_error_msg("val:%lld", numstackptr->val);
             if (errno)
                 numstackptr->val = 0; /* bash compat */
             goto num;
         }
         /* Should be an operator */
         /* Special case: XYZ--, XYZ++, --XYZ, ++XYZ are recognized
          * only if XYZ is a variable name, not a number or EXPR. IOW:
          * "a+++v" is a++ + v.
          * "(a)+++7" is ( a ) + + + 7.
          * "7+++v" is 7 + ++v, not 7++ + v.
          * "--7" is - - 7, not --7.
          * "++++a" is + + ++a, not ++ ++a.
          */
         if ((expr[0] == '+' || expr[0] == '-')
          && (expr[1] == expr[0])
         ) {
             if (numstackptr == numstack || !numstackptr[-1].var) { /* not a VAR++ */
                 char next = skip_whitespace(expr + 2)[0];
                 if (!(isalpha(next) || next == '_')) { /* not a ++VAR */
                     //bb_error_msg("special %c%c", expr[0], expr[0]);
                     op = (expr[0] == '+' ? TOK_ADD : TOK_SUB);
                     expr++;
                     goto tok_found1;
                 }
             }
         }
         p = op_tokens;
         while (1) {
             /* Compare expr to current op_tokens[] element */
             const char *e = expr;
             while (1) {
                 if (*p == '\0') {
                     /* Match: operator is found */
                     expr = e;
                     goto tok_found;
                 }
                 if (*p != *e)
                     break;
                 p++;
                 e++;
             }
             /* No match, go to next element of op_tokens[] */
             while (*p)
                 p++;
             p += 2; /* skip NUL and TOK_foo bytes */
             if (*p == '\0') {
                 /* No next element, operator not found */
                 //math_state->syntax_error_at = expr;
                 goto err;
             }
         }
  tok_found:
         op = p[1]; /* fetch TOK_foo value */
  tok_found1:
         /* NB: expr now points past the operator */
         /* post grammar: a++ reduce to num */
         if (lasttok == TOK_POST_INC || lasttok == TOK_POST_DEC)
             lasttok = TOK_NUM;
         /* Plus and minus are binary (not unary) _only_ if the last
          * token was a number, or a right paren (which pretends to be
          * a number, since it evaluates to one). Think about it.
          * It makes sense. */
         if (lasttok != TOK_NUM) {
             switch (op) {
             case TOK_ADD:
                 op = TOK_UPLUS;
                 break;
             case TOK_SUB:
                 op = TOK_UMINUS;
                 break;
             case TOK_POST_INC:
                 op = TOK_PRE_INC;
                 break;
             case TOK_POST_DEC:
                 op = TOK_PRE_DEC;
                 break;
             }
         }
         /* We don't want an unary operator to cause recursive descent on the
          * stack, because there can be many in a row and it could cause an
          * operator to be evaluated before its argument is pushed onto the
          * integer stack.
          * But for binary operators, "apply" everything on the operator
          * stack until we find an operator with a lesser priority than the
          * one we have just extracted. If op is right-associative,
          * then stop "applying" on the equal priority too.
          * Left paren is given the lowest priority so it will never be
          * "applied" in this way.
          */
         prec = PREC(op);
 //bb_error_msg("prec:%02x", prec);
         if ((prec > 0 && prec < UNARYPREC) || prec == SPEC_PREC) {
             /* not left paren or unary */
             if (lasttok != TOK_NUM) {
                 /* binary op must be preceded by a num */
                 goto err;
             }
             /* The algorithm employed here is simple: while we don't
              * hit an open paren nor the bottom of the stack, pop
              * tokens and apply them */
             while (stackptr != stack) {
                 operator prev_op = *--stackptr;
                 if (op == TOK_RPAREN) {
 //bb_error_msg("op == TOK_RPAREN");
                     if (prev_op == TOK_LPAREN) {
 //bb_error_msg("prev_op == TOK_LPAREN");
 //bb_error_msg("  %p %p numstackptr[-1].var:'%s'", numstack, numstackptr-1, numstackptr[-1].var);
                         if (numstackptr[-1].var) {
                             /* Expression is (var), lookup now */
                             errmsg = arith_lookup_val(math_state, &numstackptr[-1]);
                             if (errmsg)
                                 goto err_with_custom_msg;
                             /* Erase var name: (var) is just a number, for example, (var) = 1 is not valid */
                             numstackptr[-1].var = NULL;
                         }
                         /* Any operator directly after a
                          * close paren should consider itself binary */
                         lasttok = TOK_NUM;
                         goto next;
                     }
 //bb_error_msg("prev_op != TOK_LPAREN");
                 } else {
                     operator prev_prec = PREC(prev_op);
 //bb_error_msg("op != TOK_RPAREN");
                     fix_assignment_prec(prec);
                     fix_assignment_prec(prev_prec);
                     if (prev_prec < prec
                      || (prev_prec == prec && is_right_associative(prec))
                     ) {
                         stackptr++;
                         break;
                     }
                 }
 //bb_error_msg("arith_apply(prev_op:%02x)", prev_op);
                 errmsg = arith_apply(math_state, prev_op, numstack, &numstackptr);
                 if (errmsg)
                     goto err_with_custom_msg;
             }
             if (op == TOK_RPAREN)
                 goto err;
         }
         /* Push this operator to the stack and remember it */
 //bb_error_msg("push op:%02x", op);
         *stackptr++ = lasttok = op;
  next: ;
     } /* while (1) */
  err:
     errmsg = "arithmetic syntax error";
  err_with_custom_msg:
     numstack->val = -1;
  ret:
     math_state->errmsg = errmsg;
     return numstack->val;
 }
References alloca, arith_apply(), arith_lookup_val(), endofname(), err(), errmsg(), arith_state_t::errmsg, errno, expr(), fix_assignment_prec, is_right_associative(), isalpha, isdigit, lasttok, next, NULL, num, p, prec, PREC, ptr_to_rparen, safe_strncpy(), var_or_num_t::second_val_present, skip_whitespace(), SPEC_PREC, stack, strlen(), strto_arith_t, TOK_ADD, TOK_LPAREN, TOK_NUM, TOK_POST_DEC, TOK_POST_INC, TOK_PRE_DEC, TOK_PRE_INC, TOK_RPAREN, TOK_SUB, TOK_UMINUS, TOK_UPLUS, UNARYPREC, var_or_num_t::val, and var_or_num_t::var.
Referenced by arith(), and arith_lookup_val().
is_assign_op()
static int is_assign_op (operator op) static
Definition at line 212 of file math.c.
 {
     operator prec = PREC(op);
     fix_assignment_prec(prec);
     return prec == PREC(TOK_ASSIGN)
     || prec == PREC_PRE
     || prec == PREC_POST;
 }
References fix_assignment_prec, prec, PREC, PREC_POST, PREC_PRE, and TOK_ASSIGN.
Referenced by arith_apply().
is_right_associative()
static int is_right_associative (operator prec) static
Definition at line 222 of file math.c.
 {
     return prec == PREC(TOK_ASSIGN)
     || prec == PREC(TOK_EXPONENT)
     || prec == PREC(TOK_CONDITIONAL);
 }
References prec, PREC, TOK_ASSIGN, TOK_CONDITIONAL, and TOK_EXPONENT.
Referenced by evaluate_string().
Variable Documentation
ALIGN1
const char op_tokens [] ALIGN1 static
Definition at line 466 of file math.c.