Fennix Userspace: Userspace/apps/base/busybox/coreutils/link.c File Reference
link.c File Reference
#include "libbb.h"
Functions
int link_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
link_main()
int link_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 28 of file link.c.
 {
     getopt32(argv, "^" "" "\0" "=2");
     argv += optind;
     if (link(argv[0], argv[1]) != 0) {
         /* shared message */
         bb_perror_msg_and_die("can't create %slink '%s' to '%s'",
             "hard", argv[1], argv[0]
         );
     }
     return EXIT_SUCCESS;
 }
References argv, bb_perror_msg_and_die(), EXIT_SUCCESS, getopt32(), link(), and optind.