Fennix Userspace: Userspace/musl/crt/crt1.c File Reference
crt1.c File Reference
#include <features.h>
#include "libc.h"
#include "crt_arch.h"
Macros
#define START "_start"
Functions
int main ()
weak void _init ()
weak void _fini ()
int __libc_start_main (int(*)(), int, char **, void(*)(), void(*)(), void(*)())
void _start_c (long *p)
Macro Definition Documentation
START
#define START "_start"
Definition at line 4 of file crt1.c.
Function Documentation
__libc_start_main()
int __libc_start_main (int(*)() , int , char ** , void(*)() , void(*)() , void(*)())
Referenced by _start_c().
_fini()
weak void _fini ()
Referenced by _start_c(), and libc_exit_fini().
_init()
weak void _init ()
Referenced by _start_c(), and libc_start_init().
_start_c()
void _start_c (long * p)
Definition at line 14 of file crt1.c.
 {
     int argc = p[0];
     char **argv = (void *)(p+1);
     __libc_start_main(main, argc, argv, _init, _fini, 0);
 }
References __libc_start_main(), _fini(), _init(), main(), and p.
main()
int main ()
Definition at line 132 of file fsh.c.
 {
     char command[MAX_COMMAND_LENGTH];
     for (int i = 0; i < NSIG; ++i)
         signal(i, HandleSignal);
     char hostname[256];
     gethostname(hostname, sizeof(hostname));
     while (1)
     {
         printf("\033[1;32m");
         printf("┌──(%s@%s)-[%s]\n", getenv("USER"), hostname, getenv("PWD"));
         printf("└$ ");
         printf("\033[0m");
         DisableInputBuffering();
         ReadLine(command, sizeof(command));
         EnableInputBuffering();
         putchar('\n');
         if (strcmp(command, "exit") == 0)
             break;
         ExecuteCommand(command);
     }
     return 0;
 }
Referenced by _start_c().