Fennix Userspace: Userspace/apps/base/busybox/editors/vi.c File Reference
vi.c File Reference
#include "libbb.h"
Data Structures
struct globals
Macros
#define ENABLE_FEATURE_VI_CRASHME 0
#define IF_FEATURE_VI_CRASHME(...)
#define Isprint(c) ((unsigned char)(c) >= ' ' && (unsigned char)(c) < 0x7f)
#define isbackspace(c) ((c) == term_orig.c_cc[VERASE] || (c) == 8 || (c) == 127)
#define ESC "\033"
#define ESC_BOLD_TEXT ESC"[7m"
#define ESC_NORM_TEXT ESC"[m"
#define ESC_BELL "\007"
#define ESC_CLEAR2EOL ESC"[K"
#define ESC_CLEAR2EOS ESC"[J"
#define ESC_SET_CURSOR_POS ESC"[%u;%uH"
#define ESC_SET_CURSOR_TOPLEFT ESC"[H"
#define autoindent (0)
#define expandtab (0)
#define err_method (0)
#define ignorecase (0)
#define SET_READONLY_FILE(flags) ((void)0)
#define SET_READONLY_MODE(flags) ((void)0)
#define UNSET_READONLY_FILE(flags) ((void)0)
#define STATUS_BUFFER_LEN 200
#define G (*ptr_to_globals)
#define text (G.text)
#define text_size (G.text_size)
#define end (G.end)
#define dot (G.dot)
#define reg (G.reg)
#define vi_setops (G.vi_setops)
#define editing (G.editing)
#define cmd_mode (G.cmd_mode)
#define modified_count (G.modified_count)
#define last_modified_count (G.last_modified_count)
#define cmdline_filecnt (G.cmdline_filecnt)
#define cmdcnt (G.cmdcnt)
#define rstart (G.rstart)
#define rows (G.rows)
#define columns (G.columns)
#define crow (G.crow)
#define ccol (G.ccol)
#define offset (G.offset)
#define status_buffer (G.status_buffer)
#define have_status_msg (G.have_status_msg)
#define last_status_cksum (G.last_status_cksum)
#define current_filename (G.current_filename)
#define alt_filename (G.alt_filename)
#define screen (G.screen)
#define screensize (G.screensize)
#define screenbegin (G.screenbegin)
#define tabstop (G.tabstop)
#define last_search_char (G.last_search_char)
#define last_search_cmd (G.last_search_cmd)
#define readonly_mode 0
#define adding2q (G.adding2q)
#define lmc_len (G.lmc_len)
#define ioq (G.ioq)
#define ioq_start (G.ioq_start)
#define dotcnt (G.dotcnt)
#define last_search_pattern (G.last_search_pattern)
#define char_insert__indentcol (G.char_insert__indentcol)
#define newindent (G.newindent)
#define cmd_error (G.cmd_error)
#define edit_file__cur_line (G.edit_file__cur_line)
#define refresh__old_offset (G.refresh__old_offset)
#define format_edit_status__tot (G.format_edit_status__tot)
#define YDreg (G.YDreg)
#define regtype (G.regtype)
#define mark (G.mark)
#define restart (G.restart)
#define term_orig (G.term_orig)
#define cindex (G.cindex)
#define keep_index (G.keep_index)
#define initial_cmds (G.initial_cmds)
#define readbuffer (G.readbuffer)
#define scr_out_buf (G.scr_out_buf)
#define last_modifying_cmd (G.last_modifying_cmd)
#define get_input_line__buf (G.get_input_line__buf)
#define INIT_G()
#define old_offset refresh__old_offset
#define get_one_char() readit()
#define buf get_input_line__buf
#define tot format_edit_status__tot
#define text_hole_delete(a, b, c) text_hole_delete(a,b)
#define flush_undo_data() ((void)0)
#define undo_queue_commit() ((void)0)
#define end_cmd_q() ((void)0)
#define yank_delete(a, b, c, d, e) yank_delete(a,b,c,d)
#define char_insert(a, b, c) char_insert(a,b)
#define init_filename(f) ((void)(0))
#define strchr_backslash(s, c) strchr(s, c)
#define VI_OPTSTR
Enumerations
enum { MAX_TABSTOP = 32 , MAX_INPUT_LEN = 128 , MAX_SCR_COLS = CONFIG_FEATURE_VI_MAX_LEN , MAX_SCR_ROWS = CONFIG_FEATURE_VI_MAX_LEN }
enum {
YANKONLY = FALSE , YANKDEL = TRUE , FORWARD = 1 , BACK = -1 ,
LIMITED = 0 , FULL = 1 , PARTIAL = 0 , WHOLE = 1 ,
MULTI = 2 , S_BEFORE_WS = 1 , S_TO_WS = 2 , S_OVER_WS = 3 ,
S_END_PUNCT = 4 , S_END_ALNUM = 5 , C_END = -1
}
enum {
OPTBIT_H , OPTBIT_h , OPT_C = IF_FEATURE_VI_CRASHME((1 << OPTBIT_C)) + 0 , OPT_c = IF_FEATURE_VI_COLON((1 << OPTBIT_c)) + 0 ,
OPT_H = 1 << OPTBIT_H , OPT_h = 1 << OPTBIT_h , OPT_R = IF_FEATURE_VI_READONLY((1 << OPTBIT_R)) + 0
}
Functions
static void show_status_line (void)
static void status_line_bold (const char *,...)
static void show_help (void)
static void write1 (const char *out)
static ALWAYS_INLINE int query_screen_dimensions (void)
static int mysleep (int hund)
static void rawmode (void)
static void cookmode (void)
static void place_cursor (int row, int col)
static void clear_to_eol (void)
static void go_bottom_and_clear_to_eol (void)
static void standout_start (void)
static void standout_end (void)
static char * begin_line (char *p)
static char * end_line (char *p)
static char * dollar_line (char *p)
static char * prev_line (char *p)
static char * next_line (char *p)
static char * end_screen (void)
static int count_lines (char *start, char *stop)
static char * find_line (int li)
static int next_tabstop (int col)
static int prev_tabstop (int col)
static int next_column (char c, int co)
static int get_column (char *p)
static void screen_erase (void)
static void new_screen (int ro, int co)
static void sync_cursor (char *d, int *row, int *col)
static char * format_line (char *src)
static void refresh (int full_screen)
static void redraw (int full_screen)
static void flash (int h)
static void indicate_error (void)
static int readit (void)
static int get_motion_char (void)
static char * get_input_line (const char *prompt)
static void Hit_Return (void)
static int format_edit_status (void)
static int bufsum (char *buf, int count)
static void status_line (const char *format,...)
static void status_line_bold_errno (const char *fn)
static void print_literal (char *buf, const char *s)
static void not_implemented (const char *s)
static uintptr_t text_hole_make (char *p, int size)
static char * text_hole_delete (char *p, char *q, int undo)
static void dot_left (void)
static void dot_right (void)
static void dot_begin (void)
static void dot_end (void)
static char * move_to_col (char *p, int l)
static void dot_next (void)
static void dot_prev (void)
static void dot_skip_over_ws (void)
static void dot_to_char (int cmd)
static void dot_scroll (int cnt, int dir)
static char * bound_dot (char *p)
static char * yank_delete (char *start, char *stop, int buftype, int yf, int undo)
static int file_insert (const char *fn, char *p, int initial)
static char * find_pair (char *p, const char c)
static uintptr_t stupid_insert (char *p, char c)
static size_t indent_len (char *p)
static char * char_insert (char *p, char c, int undo)
static void update_filename (char *fn)
static int init_text_buffer (char *fn)
static int file_write (char *fn, char *first, char *last)
static void colon (char *buf)
static int st_test (char *p, int type, int dir, char *tested)
static char * skip_thing (char *p, int linecnt, int dir, int type)
static void do_cmd (int c)
static int at_eof (const char *s)
static int find_range (char **start, char **stop, int cmd)
static void edit_file (char *fn)
int vi_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
adding2q
#define adding2q (G.adding2q)
Definition at line 506 of file vi.c.
alt_filename
#define alt_filename (G.alt_filename)
Definition at line 491 of file vi.c.
autoindent
#define autoindent (0)
Definition at line 322 of file vi.c.
buf
#define buf get_input_line__buf
ccol
#define ccol (G.ccol)
Definition at line 485 of file vi.c.
char_insert
#define char_insert (a, b, c) char_insert(a,b)
Definition at line 2115 of file vi.c.
char_insert__indentcol
#define char_insert__indentcol (G.char_insert__indentcol)
Definition at line 512 of file vi.c.
cindex
#define cindex (G.cindex)
Definition at line 526 of file vi.c.
cmd_error
#define cmd_error (G.cmd_error)
Definition at line 514 of file vi.c.
cmd_mode
#define cmd_mode (G.cmd_mode)
Definition at line 476 of file vi.c.
cmdcnt
#define cmdcnt (G.cmdcnt)
Definition at line 480 of file vi.c.
cmdline_filecnt
#define cmdline_filecnt (G.cmdline_filecnt)
Definition at line 479 of file vi.c.
columns
#define columns (G.columns)
Definition at line 483 of file vi.c.
crow
#define crow (G.crow)
Definition at line 484 of file vi.c.
current_filename
#define current_filename (G.current_filename)
Definition at line 490 of file vi.c.
dot
#define dot (G.dot)
Definition at line 471 of file vi.c.
dotcnt
#define dotcnt (G.dotcnt)
Definition at line 510 of file vi.c.
edit_file__cur_line
#define edit_file__cur_line (G.edit_file__cur_line)
Definition at line 516 of file vi.c.
editing
#define editing (G.editing)
Definition at line 475 of file vi.c.
ENABLE_FEATURE_VI_CRASHME
#define ENABLE_FEATURE_VI_CRASHME 0
Definition at line 203 of file vi.c.
end
#define end (G.end)
Definition at line 470 of file vi.c.
end_cmd_q
#define end_cmd_q () ((void)0)
Definition at line 1950 of file vi.c.
err_method
#define err_method (0)
Definition at line 324 of file vi.c.
ESC
#define ESC "\033"
Definition at line 242 of file vi.c.
ESC_BELL
#define ESC_BELL "\007"
Definition at line 247 of file vi.c.
ESC_BOLD_TEXT
#define ESC_BOLD_TEXT ESC"[7m"
Definition at line 244 of file vi.c.
ESC_CLEAR2EOL
#define ESC_CLEAR2EOL ESC"[K"
Definition at line 249 of file vi.c.
ESC_CLEAR2EOS
#define ESC_CLEAR2EOS ESC"[J"
Definition at line 254 of file vi.c.
ESC_NORM_TEXT
#define ESC_NORM_TEXT ESC"[m"
Definition at line 245 of file vi.c.
ESC_SET_CURSOR_POS
#define ESC_SET_CURSOR_POS ESC"[%u;%uH"
Definition at line 256 of file vi.c.
ESC_SET_CURSOR_TOPLEFT
#define ESC_SET_CURSOR_TOPLEFT ESC"[H"
Definition at line 257 of file vi.c.
expandtab
#define expandtab (0)
Definition at line 323 of file vi.c.
flush_undo_data
#define flush_undo_data () ((void)0)
Definition at line 1804 of file vi.c.
format_edit_status__tot
#define format_edit_status__tot (G.format_edit_status__tot)
Definition at line 518 of file vi.c.
G
#define G (*ptr_to_globals)
Definition at line 467 of file vi.c.
get_input_line__buf
#define get_input_line__buf (G.get_input_line__buf)
Definition at line 532 of file vi.c.
get_one_char
#define get_one_char () readit()
Definition at line 1179 of file vi.c.
have_status_msg
#define have_status_msg (G.have_status_msg)
Definition at line 488 of file vi.c.
IF_FEATURE_VI_CRASHME
#define IF_FEATURE_VI_CRASHME (...)
Definition at line 204 of file vi.c.
ignorecase
#define ignorecase (0)
Definition at line 325 of file vi.c.
init_filename
#define init_filename (f) ((void)(0))
Definition at line 2283 of file vi.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    last_modified_count--; \
    /* "" but has space for 2 chars: */ \
    IF_FEATURE_VI_SEARCH(last_search_pattern = xzalloc(2);) \
    tabstop = 8; \
    IF_FEATURE_VI_SETOPTS(newindent--;) \
} while (0)
Definition at line 544 of file vi.c.
initial_cmds
#define initial_cmds (G.initial_cmds)
Definition at line 528 of file vi.c.
ioq
#define ioq (G.ioq)
Definition at line 508 of file vi.c.
ioq_start
#define ioq_start (G.ioq_start)
Definition at line 509 of file vi.c.
isbackspace
#define isbackspace (c) ((c) == term_orig.c_cc[VERASE] || (c) == 8 || (c) == 127)
Definition at line 227 of file vi.c.
Isprint
#define Isprint (c) ((unsigned char)(c) >= ' ' && (unsigned char)(c) < 0x7f)
Definition at line 222 of file vi.c.
keep_index
#define keep_index (G.keep_index)
Definition at line 527 of file vi.c.
last_modified_count
#define last_modified_count (G.last_modified_count)
Definition at line 478 of file vi.c.
last_modifying_cmd
#define last_modifying_cmd (G.last_modifying_cmd)
Definition at line 531 of file vi.c.
last_search_char
#define last_search_char (G.last_search_char)
Definition at line 496 of file vi.c.
last_search_cmd
#define last_search_cmd (G.last_search_cmd)
Definition at line 497 of file vi.c.
last_search_pattern
#define last_search_pattern (G.last_search_pattern)
Definition at line 511 of file vi.c.
last_status_cksum
#define last_status_cksum (G.last_status_cksum)
Definition at line 489 of file vi.c.
lmc_len
#define lmc_len (G.lmc_len)
Definition at line 507 of file vi.c.
mark
#define mark (G.mark)
Definition at line 523 of file vi.c.
modified_count
#define modified_count (G.modified_count)
Definition at line 477 of file vi.c.
newindent
#define newindent (G.newindent)
Definition at line 513 of file vi.c.
offset
#define offset (G.offset)
Definition at line 486 of file vi.c.
old_offset
#define old_offset refresh__old_offset
readbuffer
#define readbuffer (G.readbuffer)
Definition at line 529 of file vi.c.
readonly_mode
#define readonly_mode 0
Definition at line 504 of file vi.c.
refresh__old_offset
#define refresh__old_offset (G.refresh__old_offset)
Definition at line 517 of file vi.c.
reg
#define reg (G.reg)
Definition at line 472 of file vi.c.
regtype
#define regtype (G.regtype)
Definition at line 522 of file vi.c.
restart
#define restart (G.restart)
Definition at line 524 of file vi.c.
rows
#define rows (G.rows)
Definition at line 482 of file vi.c.
rstart
#define rstart (G.rstart)
Definition at line 481 of file vi.c.
scr_out_buf
#define scr_out_buf (G.scr_out_buf)
Definition at line 530 of file vi.c.
screen
#define screen (G.screen)
Definition at line 492 of file vi.c.
screenbegin
#define screenbegin (G.screenbegin)
Definition at line 494 of file vi.c.
screensize
#define screensize (G.screensize)
Definition at line 493 of file vi.c.
SET_READONLY_FILE
#define SET_READONLY_FILE (flags) ((void)0)
Definition at line 334 of file vi.c.
SET_READONLY_MODE
#define SET_READONLY_MODE (flags) ((void)0)
Definition at line 335 of file vi.c.
status_buffer
#define status_buffer (G.status_buffer)
Definition at line 487 of file vi.c.
STATUS_BUFFER_LEN
#define STATUS_BUFFER_LEN 200
Definition at line 420 of file vi.c.
strchr_backslash
#define strchr_backslash (s, c) strchr(s, c)
Definition at line 2786 of file vi.c.
tabstop
#define tabstop (G.tabstop)
Definition at line 495 of file vi.c.
term_orig
#define term_orig (G.term_orig)
Definition at line 525 of file vi.c.
text
#define text (G.text)
Definition at line 468 of file vi.c.
text_hole_delete
#define text_hole_delete (a, b, c) text_hole_delete(a,b)
Definition at line 1530 of file vi.c.
text_size
#define text_size (G.text_size)
Definition at line 469 of file vi.c.
tot
#define tot format_edit_status__tot
undo_queue_commit
#define undo_queue_commit () ((void)0)
Definition at line 1805 of file vi.c.
UNSET_READONLY_FILE
#define UNSET_READONLY_FILE (flags) ((void)0)
Definition at line 336 of file vi.c.
VI_OPTSTR
#define VI_OPTSTR
Value:
    IF_FEATURE_VI_CRASHME("C") \
    IF_FEATURE_VI_COLON("c:*") \
    "Hh" \
    IF_FEATURE_VI_READONLY("R")
Definition at line 4935 of file vi.c.
vi_setops
#define vi_setops (G.vi_setops)
Definition at line 474 of file vi.c.
yank_delete
#define yank_delete (a, b, c, d, e) yank_delete(a,b,c,d)
Definition at line 1956 of file vi.c.
YDreg
#define YDreg (G.YDreg)
Definition at line 520 of file vi.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPTBIT_H
OPTBIT_h
OPT_C
OPT_c
OPT_H
OPT_h
OPT_R
Definition at line 4941 of file vi.c.
      {
     IF_FEATURE_VI_CRASHME(OPTBIT_C,)
     IF_FEATURE_VI_COLON(OPTBIT_c,)
     OPTBIT_H,
     OPTBIT_h,
     IF_FEATURE_VI_READONLY(OPTBIT_R,)
     OPT_C = IF_FEATURE_VI_CRASHME(  (1 << OPTBIT_C)) + 0,
     OPT_c = IF_FEATURE_VI_COLON(    (1 << OPTBIT_c)) + 0,
     OPT_H = 1 << OPTBIT_H,
     OPT_h = 1 << OPTBIT_h,
     OPT_R = IF_FEATURE_VI_READONLY( (1 << OPTBIT_R)) + 0,
 };
anonymous enum
anonymous enum
Enumerator
MAX_TABSTOP
MAX_INPUT_LEN
MAX_SCR_COLS
MAX_SCR_ROWS
Definition at line 229 of file vi.c.
      {
     MAX_TABSTOP = 32, // sanity limit
     // User input len. Need not be extra big.
     // Lines in file being edited *can* be bigger than this.
     MAX_INPUT_LEN = 128,
     // Sanity limits. We have only one buffer of this size.
     MAX_SCR_COLS = CONFIG_FEATURE_VI_MAX_LEN,
     MAX_SCR_ROWS = CONFIG_FEATURE_VI_MAX_LEN,
 };
anonymous enum
anonymous enum
Enumerator
YANKONLY
YANKDEL
FORWARD
BACK
LIMITED
FULL
PARTIAL
WHOLE
MULTI
S_BEFORE_WS
S_TO_WS
S_OVER_WS
S_END_PUNCT
S_END_ALNUM
C_END
Definition at line 268 of file vi.c.
      {
     YANKONLY = FALSE,
     YANKDEL = TRUE,
     FORWARD = 1,    // code depends on "1"  for array index
     BACK = -1,  // code depends on "-1" for array index
     LIMITED = 0,    // char_search() only current line
     FULL = 1,   // char_search() to the end/beginning of entire text
     PARTIAL = 0,    // buffer contains partial line
     WHOLE = 1,  // buffer contains whole lines
     MULTI = 2,  // buffer may include newlines
     S_BEFORE_WS = 1,    // used in skip_thing() for moving "dot"
     S_TO_WS = 2,        // used in skip_thing() for moving "dot"
     S_OVER_WS = 3,      // used in skip_thing() for moving "dot"
     S_END_PUNCT = 4,    // used in skip_thing() for moving "dot"
     S_END_ALNUM = 5,    // used in skip_thing() for moving "dot"
     C_END = -1, // cursor is at end of line due to '$' command
 };
Function Documentation
at_eof()
static int at_eof (const char * s) static
Definition at line 3552 of file vi.c.
 {
     // does 's' point to end of file, even with no terminating newline?
     return ((s == end - 2 && s[1] == '\n') || s == end - 1);
 }
References end, and s.
Referenced by find_range().
begin_line()
static char* begin_line (char * p) static
Definition at line 691 of file vi.c.
 {
     if (p > text) {
         p = memrchr(text, '\n', p - text);
         if (!p)
             return text;
         return p + 1;
     }
     return p;
 }
References memrchr(), p, and text.
Referenced by char_insert(), colon(), do_cmd(), dollar_line(), dot_begin(), dot_scroll(), edit_file(), find_range(), get_column(), move_to_col(), prev_line(), and sync_cursor().
bound_dot()
static char* bound_dot (char * p) static
Definition at line 1920 of file vi.c.
 {
     if (p >= end && end > text) {
         p = end - 1;
         indicate_error();
     }
     if (p < text) {
         p = text;
         indicate_error();
     }
     return p;
 }
References end, indicate_error(), p, and text.
Referenced by colon(), and do_cmd().
bufsum()
static int bufsum (char * buf, int count) static
Definition at line 1315 of file vi.c.
 {
     int sum = 0;
     char *e = buf + count;
     while (buf < e)
         sum += (unsigned char) *buf++;
     return sum;
 }
References buf, and count.
Referenced by show_status_line().
char_insert()
static char* char_insert (char * p, char c, int undo) static
Definition at line 2117 of file vi.c.
 {
 #if ENABLE_FEATURE_VI_SETOPTS
 # define indentcol char_insert__indentcol
     size_t len;
     int col, ntab, nspc;
 #endif
     char *bol = begin_line(p);
     if (c == 22) {      // Is this an ctrl-V?
         p += stupid_insert(p, '^'); // use ^ to indicate literal next
         refresh(FALSE); // show the ^
         c = get_one_char();
         *p = c;
 #if ENABLE_FEATURE_VI_UNDO
         undo_push_insert(p, 1, undo);
 #else
         modified_count++;
 #endif
         p++;
     } else if (c == 27) {   // Is this an ESC?
         cmd_mode = 0;
         undo_queue_commit();
         cmdcnt = 0;
         end_cmd_q();    // stop adding to q
         last_status_cksum = 0;  // force status update
         if ((dot > text) && (p[-1] != '\n')) {
             p--;
         }
 #if ENABLE_FEATURE_VI_SETOPTS
         if (autoindent) {
             len = indent_len(bol);
             col = get_column(bol + len);
             if (len && col == indentcol && bol[len] == '\n') {
                 // remove autoindent from otherwise empty line
                 text_hole_delete(bol, bol + len - 1, undo);
                 p = bol;
             }
         }
 #endif
     } else if (c == 4) {    // ctrl-D reduces indentation
         char *r = bol + indent_len(bol);
         int prev = prev_tabstop(get_column(r));
         while (r > bol && get_column(r) > prev) {
             if (p > bol)
                 p--;
             r--;
             r = text_hole_delete(r, r, ALLOW_UNDO_QUEUED);
         }
 #if ENABLE_FEATURE_VI_SETOPTS
         if (autoindent && indentcol && r == end_line(p)) {
             // record changed size of autoindent
             indentcol = get_column(p);
             return p;
         }
 #endif
 #if ENABLE_FEATURE_VI_SETOPTS
     } else if (c == '\t' && expandtab) {    // expand tab
         col = get_column(p);
         col = next_tabstop(col) - col + 1;
         while (col--) {
 # if ENABLE_FEATURE_VI_UNDO
             undo_push_insert(p, 1, undo);
 # else
             modified_count++;
 # endif
             p += 1 + stupid_insert(p, ' ');
         }
 #endif
     } else if (isbackspace(c)) {
         if (cmd_mode == 2) {
             // special treatment for backspace in Replace mode
             if (p > rstart) {
                 p--;
 #if ENABLE_FEATURE_VI_UNDO
                 undo_pop();
 #endif
             }
         } else if (p > text) {
             p--;
             p = text_hole_delete(p, p, ALLOW_UNDO_QUEUED);  // shrink buffer 1 char
         }
     } else {
         // insert a char into text[]
         if (c == 13)
             c = '\n';   // translate \r to \n
 #if ENABLE_FEATURE_VI_UNDO
 # if ENABLE_FEATURE_VI_UNDO_QUEUE
         if (c == '\n')
             undo_queue_commit();
 # endif
         undo_push_insert(p, 1, undo);
 #else
         modified_count++;
 #endif
         p += 1 + stupid_insert(p, c);   // insert the char
 #if ENABLE_FEATURE_VI_SETOPTS
         if (showmatch && strchr(")]}", c) != NULL) {
             showmatching(p - 1);
         }
         if (autoindent && c == '\n') {  // auto indent the new line
             if (newindent < 0) {
                 // use indent of previous line
                 bol = prev_line(p);
                 len = indent_len(bol);
                 col = get_column(bol + len);
                 if (len && col == indentcol) {
                     // previous line was empty except for autoindent
                     // move the indent to the current line
                     memmove(bol + 1, bol, len);
                     *bol = '\n';
                     return p;
                 }
             } else {
                 // for 'O'/'cc' commands add indent before newly inserted NL
                 if (p != end - 1)   // but not for 'cc' at EOF
                     p--;
                 col = newindent;
             }
             if (col) {
                 // only record indent if in insert/replace mode or for
                 // the 'o'/'O'/'cc' commands, which are switched to
                 // insert mode early.
                 indentcol = cmd_mode != 0 ? col : 0;
                 if (expandtab) {
                     ntab = 0;
                     nspc = col;
                 } else {
                     ntab = col / tabstop;
                     nspc = col % tabstop;
                 }
                 p += text_hole_make(p, ntab + nspc);
 # if ENABLE_FEATURE_VI_UNDO
                 undo_push_insert(p, ntab + nspc, undo);
 # endif
                 memset(p, '\t', ntab);
                 p += ntab;
                 memset(p, ' ', nspc);
                 return p + nspc;
             }
         }
 #endif
     }
 #if ENABLE_FEATURE_VI_SETOPTS
     indentcol = 0;
 # undef indentcol
 #endif
     return p;
 }
References autoindent, begin_line(), c, cmd_mode, cmdcnt, dot, end, end_cmd_q, end_line(), expandtab, FALSE, get_column(), get_one_char, indent_len(), isbackspace, last_status_cksum, memmove(), memset(), modified_count, newindent, next_tabstop(), NULL, p, prev_line(), prev_tabstop(), refresh(), rstart, strchr(), stupid_insert(), tabstop, text, text_hole_delete, text_hole_make(), undo(), and undo_queue_commit.
clear_to_eol()
static void clear_to_eol (void) static
Definition at line 667 of file vi.c.
 {
     write1(ESC_CLEAR2EOL);
 }
References ESC_CLEAR2EOL, and write1().
Referenced by go_bottom_and_clear_to_eol().
colon()
static void colon (char * buf) static
Definition at line 2790 of file vi.c.
 {
 #if !ENABLE_FEATURE_VI_COLON
     // Simple ":cmd" handler with minimal set of commands
     char *p = buf;
     int cnt;
     if (*p == ':')
         p++;
     cnt = strlen(p);
     if (cnt == 0)
         return;
     if (strncmp(p, "quit", cnt) == 0
      || strcmp(p, "q!") == 0
     ) {
         if (modified_count && p[1] != '!') {
             status_line_bold("No write since last change (:%s! overrides)", p);
         } else {
             editing = 0;
         }
         return;
     }
     if (strncmp(p, "write", cnt) == 0
      || strcmp(p, "wq") == 0
      || strcmp(p, "wn") == 0
      || (p[0] == 'x' && !p[1])
     ) {
         if (modified_count != 0 || p[0] != 'x') {
             cnt = file_write(current_filename, text, end - 1);
         }
         if (cnt < 0) {
             if (cnt == -1)
                 status_line_bold("Write error: "STRERROR_FMT STRERROR_ERRNO);
         } else {
             modified_count = 0;
             last_modified_count = -1;
             status_line("'%s' %uL, %uC",
                 current_filename,
                 count_lines(text, end - 1), cnt
             );
             if (p[0] == 'x'
              || p[1] == 'q' || p[1] == 'n'
             ) {
                 editing = 0;
             }
         }
         return;
     }
     if (strncmp(p, "file", cnt) == 0) {
         last_status_cksum = 0;  // force status update
         return;
     }
     if (sscanf(p, "%d", &cnt) > 0) {
         dot = find_line(cnt);
         dot_skip_over_ws();
         return;
     }
     not_implemented(p);
 #else
 // check how many addresses we got
 # define GOT_ADDRESS (got & 1)
 # define GOT_RANGE ((got & 3) == 3)
     char c, *buf1, *q, *r;
     char *fn, cmd[MAX_INPUT_LEN], *cmdend, *args, *exp = NULL;
     int i, l, li, b, e;
     unsigned int got;
     int useforce;
     // :3154    // if (-e line 3154) goto it  else stay put
     // :4,33w! foo  // write a portion of buffer to file "foo"
     // :w       // write all of buffer to current file
     // :q       // quit
     // :q!      // quit- dont care about modified file
     // :'a,'z!sort -u   // filter block through sort
     // :'f      // goto mark "f"
     // :'fl     // list literal the mark "f" line
     // :.r bar  // read file "bar" into buffer before dot
     // :/123/,/abc/d    // delete lines from "123" line to "abc" line
     // :/xyz/   // goto the "xyz" line
     // :s/find/replace/ // substitute pattern "find" with "replace"
     // :!<cmd>  // run <cmd> then return
     //
     while (*buf == ':')
         buf++;          // move past leading colons
     while (isblank(*buf))
         buf++;          // move past leading blanks
     if (!buf[0] || buf[0] == '"')
         goto ret;       // ignore empty lines or those starting with '"'
     li = i = 0;
     b = e = -1;
     got = 0;
     li = count_lines(text, end - 1);
     fn = current_filename;
     // look for optional address(es)  :.  :1  :1,9   :'q,'a   :%
     buf = get_address(buf, &b, &e, &got);
     if (buf == NULL) {
         goto ret;
     }
     // get the COMMAND into cmd[]
     strcpy(cmd, buf);
     buf1 = cmd;
     while (!isspace(*buf1) && *buf1 != '\0') {
         buf1++;
     }
     cmdend = buf1;
     // get any ARGuments
     while (isblank(*buf1))
         buf1++;
     args = buf1;
     *cmdend = '\0';
     useforce = FALSE;
     if (cmdend > cmd && cmdend[-1] == '!') {
         useforce = TRUE;
         cmdend[-1] = '\0';   // get rid of !
     }
     // assume the command will want a range, certain commands
     // (read, substitute) need to adjust these assumptions
     if (!GOT_ADDRESS) {
         q = text;           // no addr, use 1,$ for the range
         r = end - 1;
     } else {
         // at least one addr was given, get its details
         if (e < 0 || e > li) {
             status_line_bold("Invalid range");
             goto ret;
         }
         q = r = find_line(e);
         if (!GOT_RANGE) {
             // if there is only one addr, then it's the line
             // number of the single line the user wants.
             // Reset the end pointer to the end of that line.
             r = end_line(q);
             li = 1;
         } else {
             // we were given two addrs.  change the
             // start pointer to the addr given by user.
             if (b < 0 || b > li || b > e) {
                 status_line_bold("Invalid range");
                 goto ret;
             }
             q = find_line(b);   // what line is #b
             r = end_line(r);
             li = e - b + 1;
         }
     }
     // ------------ now look for the command ------------
     i = strlen(cmd);
     if (i == 0) {       // :123CR goto line #123
         if (e >= 0) {
             dot = find_line(e); // what line is #e
             dot_skip_over_ws();
         }
     }
 # if ENABLE_FEATURE_ALLOW_EXEC
     else if (cmd[0] == '!') {   // run a cmd
         int retcode;
         // :!ls   run the <cmd>
         exp = expand_args(buf + 1);
         if (exp == NULL)
             goto ret;
         go_bottom_and_clear_to_eol();
         cookmode();
         retcode = system(exp);  // run the cmd
         if (retcode)
             printf("\nshell returned %i\n\n", retcode);
         rawmode();
         Hit_Return();           // let user see results
     }
 # endif
     else if (cmd[0] == '=' && !cmd[1]) {    // where is the address
         if (!GOT_ADDRESS) { // no addr given- use defaults
             e = count_lines(text, dot);
         }
         status_line("%d", e);
     } else if (strncmp(cmd, "delete", i) == 0) {    // delete lines
         if (!GOT_ADDRESS) { // no addr given- use defaults
             q = begin_line(dot);    // assume .,. for the range
             r = end_line(dot);
         }
         dot = yank_delete(q, r, WHOLE, YANKDEL, ALLOW_UNDO);    // save, then delete lines
         dot_skip_over_ws();
     } else if (strncmp(cmd, "edit", i) == 0) {  // Edit a file
         int size;
         // don't edit, if the current file has been modified
         if (modified_count && !useforce) {
             status_line_bold("No write since last change (:%s! overrides)", cmd);
             goto ret;
         }
         if (args[0]) {
             // the user supplied a file name
             fn = exp = expand_args(args);
             if (exp == NULL)
                 goto ret;
         } else if (current_filename == NULL) {
             // no user file name, no current name- punt
             status_line_bold("No current filename");
             goto ret;
         }
         size = init_text_buffer(fn);
 # if ENABLE_FEATURE_VI_YANKMARK
         if (Ureg >= 0 && Ureg < 28) {
             free(reg[Ureg]);    //   free orig line reg- for 'U'
             reg[Ureg] = NULL;
         }
         /*if (YDreg < 28) - always true*/ {
             free(reg[YDreg]);   //   free default yank/delete register
             reg[YDreg] = NULL;
         }
 # endif
         // how many lines in text[]?
         li = count_lines(text, end - 1);
         status_line("'%s'%s"
             IF_FEATURE_VI_READONLY("%s")
             " %uL, %uC",
             fn,
             (size < 0 ? " [New file]" : ""),
             IF_FEATURE_VI_READONLY(
                 ((readonly_mode) ? " [Readonly]" : ""),
             )
             li, (int)(end - text)
         );
     } else if (strncmp(cmd, "file", i) == 0) {  // what File is this
         if (e >= 0) {
             status_line_bold("No address allowed on this command");
             goto ret;
         }
         if (args[0]) {
             // user wants a new filename
             exp = expand_args(args);
             if (exp == NULL)
                 goto ret;
             update_filename(exp);
         } else {
             // user wants file status info
             last_status_cksum = 0;  // force status update
         }
     } else if (strncmp(cmd, "features", i) == 0) {  // what features are available
         // print out values of all features
         go_bottom_and_clear_to_eol();
         cookmode();
         show_help();
         rawmode();
         Hit_Return();
     } else if (strncmp(cmd, "list", i) == 0) {  // literal print line
         if (!GOT_ADDRESS) { // no addr given- use defaults
             q = begin_line(dot);    // assume .,. for the range
             r = end_line(dot);
         }
         go_bottom_and_clear_to_eol();
         puts("\r");
         for (; q <= r; q++) {
             int c_is_no_print;
             c = *q;
             c_is_no_print = (c & 0x80) && !Isprint(c);
             if (c_is_no_print) {
                 c = '.';
                 standout_start();
             }
             if (c == '\n') {
                 write1("$\r");
             } else if (c < ' ' || c == 127) {
                 bb_putchar('^');
                 if (c == 127)
                     c = '?';
                 else
                     c += '@';
             }
             bb_putchar(c);
             if (c_is_no_print)
                 standout_end();
         }
         Hit_Return();
     } else if (strncmp(cmd, "quit", i) == 0 // quit
             || strncmp(cmd, "next", i) == 0 // edit next file
             || strncmp(cmd, "prev", i) == 0 // edit previous file
     ) {
         int n;
         if (useforce) {
             if (*cmd == 'q') {
                 // force end of argv list
                 optind = cmdline_filecnt;
             }
             editing = 0;
             goto ret;
         }
         // don't exit if the file been modified
         if (modified_count) {
             status_line_bold("No write since last change (:%s! overrides)", cmd);
             goto ret;
         }
         // are there other file to edit
         n = cmdline_filecnt - optind - 1;
         if (*cmd == 'q' && n > 0) {
             status_line_bold("%u more file(s) to edit", n);
             goto ret;
         }
         if (*cmd == 'n' && n <= 0) {
             status_line_bold("No more files to edit");
             goto ret;
         }
         if (*cmd == 'p') {
             // are there previous files to edit
             if (optind < 1) {
                 status_line_bold("No previous files to edit");
                 goto ret;
             }
             optind -= 2;
         }
         editing = 0;
     } else if (strncmp(cmd, "read", i) == 0) {  // read file into text[]
         int size, num;
         if (args[0]) {
             // the user supplied a file name
             fn = exp = expand_args(args);
             if (exp == NULL)
                 goto ret;
             init_filename(fn);
         } else if (current_filename == NULL) {
             // no user file name, no current name- punt
             status_line_bold("No current filename");
             goto ret;
         }
         if (e == 0) {   // user said ":0r foo"
             q = text;
         } else {    // read after given line or current line if none given
             q = next_line(GOT_ADDRESS ? find_line(e) : dot);
             // read after last line
             if (q == end-1)
                 ++q;
         }
         num = count_lines(text, q);
         if (q == end)
             num++;
         { // dance around potentially-reallocated text[]
             uintptr_t ofs = q - text;
             size = file_insert(fn, q, 0);
             q = text + ofs;
         }
         if (size < 0)
             goto ret;   // nothing was inserted
         // how many lines in text[]?
         li = count_lines(q, q + size - 1);
         status_line("'%s'"
             IF_FEATURE_VI_READONLY("%s")
             " %uL, %uC",
             fn,
             IF_FEATURE_VI_READONLY((readonly_mode ? " [Readonly]" : ""),)
             li, size
         );
         dot = find_line(num);
     } else if (strncmp(cmd, "rewind", i) == 0) {    // rewind cmd line args
         if (modified_count && !useforce) {
             status_line_bold("No write since last change (:%s! overrides)", cmd);
         } else {
             // reset the filenames to edit
             optind = -1; // start from 0th file
             editing = 0;
         }
 # if ENABLE_FEATURE_VI_SET
     } else if (strncmp(cmd, "set", i) == 0) {   // set or clear features
 #  if ENABLE_FEATURE_VI_SETOPTS
         char *argp, *argn, oldch;
 #  endif
         // only blank is regarded as args delimiter. What about tab '\t'?
         if (!args[0] || strcmp(args, "all") == 0) {
             // print out values of all options
 #  if ENABLE_FEATURE_VI_SETOPTS
             status_line_bold(
                 "%sautoindent "
                 "%sexpandtab "
                 "%sflash "
                 "%signorecase "
                 "%sshowmatch "
                 "tabstop=%u",
                 autoindent ? "" : "no",
                 expandtab ? "" : "no",
                 err_method ? "" : "no",
                 ignorecase ? "" : "no",
                 showmatch ? "" : "no",
                 tabstop
             );
 #  endif
             goto ret;
         }
 #  if ENABLE_FEATURE_VI_SETOPTS
         argp = args;
         while (*argp) {
             i = 0;
             if (argp[0] == 'n' && argp[1] == 'o') // "noXXX"
                 i = 2;
             argn = skip_non_whitespace(argp);
             oldch = *argn;
             *argn = '\0';
             setops(argp, i);
             *argn = oldch;
             argp = skip_whitespace(argn);
         }
 #  endif /* FEATURE_VI_SETOPTS */
 # endif /* FEATURE_VI_SET */
 # if ENABLE_FEATURE_VI_SEARCH
     } else if (cmd[0] == 's') { // substitute a pattern with a replacement pattern
         char *F, *R, *flags;
         size_t len_F, len_R;
         int gflag = 0;      // global replace flag
         int subs = 0;   // number of substitutions
 #  if ENABLE_FEATURE_VI_VERBOSE_STATUS
         int last_line = 0, lines = 0;
 #  endif
 #  if ENABLE_FEATURE_VI_REGEX_SEARCH
         regex_t preg;
         int cflags;
         char *Rorig;
 #   if ENABLE_FEATURE_VI_UNDO
         int undo = 0;
 #   endif
 #  endif
         // F points to the "find" pattern
         // R points to the "replace" pattern
         // replace the cmd line delimiters "/" with NULs
         c = buf[1]; // what is the delimiter
         F = buf + 2;    // start of "find"
         R = strchr_backslash(F, c); // middle delimiter
         if (!R)
             goto colon_s_fail;
         len_F = R - F;
         *R++ = '\0';    // terminate "find"
         flags = strchr_backslash(R, c);
         if (flags) {
             *flags++ = '\0';    // terminate "replace"
             gflag = *flags;
         }
         if (len_F) {    // save "find" as last search pattern
             free(last_search_pattern);
             last_search_pattern = xstrdup(F - 1);
             last_search_pattern[0] = '/';
         } else if (last_search_pattern[1] == '\0') {
             status_line_bold("No previous search");
             goto ret;
         } else {
             F = last_search_pattern + 1;
             len_F = strlen(F);
         }
         if (!GOT_ADDRESS) { // no addr given
             q = begin_line(dot);      // start with cur line
             r = end_line(dot);
             b = e = count_lines(text, q); // cur line number
         } else if (!GOT_RANGE) {    // one addr given
             b = e;
         }
 #  if ENABLE_FEATURE_VI_REGEX_SEARCH
         Rorig = R;
         cflags = 0;
         if (ignorecase)
             cflags = REG_ICASE;
         memset(&preg, 0, sizeof(preg));
         if (regcomp(&preg, F, cflags) != 0) {
             status_line(":s bad search pattern");
             goto regex_search_end;
         }
 #  else
         len_R = strlen(R);
 #  endif
         for (i = b; i <= e; i++) {  // so, :20,23 s \0 find \0 replace \0
             char *ls = q;       // orig line start
             char *found;
  vc4:
 #  if ENABLE_FEATURE_VI_REGEX_SEARCH
             found = regex_search(q, &preg, Rorig, &len_F, &len_R, &R);
 #  else
             found = char_search(q, F, (FORWARD << 1) | LIMITED);    // search cur line only for "find"
 #  endif
             if (found) {
                 uintptr_t bias;
                 // we found the "find" pattern - delete it
                 // For undo support, the first item should not be chained
                 // This needs to be handled differently depending on
                 // whether or not regex support is enabled.
 #  if ENABLE_FEATURE_VI_REGEX_SEARCH
 #   define TEST_LEN_F len_F // len_F may be zero
 #   define TEST_UNDO1 undo++
 #   define TEST_UNDO2 undo++
 #  else
 #   define TEST_LEN_F 1     // len_F is never zero
 #   define TEST_UNDO1 subs
 #   define TEST_UNDO2 1
 #  endif
                 if (TEST_LEN_F) // match can be empty, no delete needed
                     text_hole_delete(found, found + len_F - 1,
                                 TEST_UNDO1 ? ALLOW_UNDO_CHAIN : ALLOW_UNDO);
                 if (len_R != 0) {   // insert the "replace" pattern, if required
                     bias = string_insert(found, R,
                                 TEST_UNDO2 ? ALLOW_UNDO_CHAIN : ALLOW_UNDO);
                     found += bias;
                     ls += bias;
                     //q += bias; - recalculated anyway
                 }
 #  if ENABLE_FEATURE_VI_REGEX_SEARCH
                 free(R);
 #  endif
                 if (TEST_LEN_F || len_R != 0) {
                     dot = ls;
                     subs++;
 #  if ENABLE_FEATURE_VI_VERBOSE_STATUS
                     if (last_line != i) {
                         last_line = i;
                         ++lines;
                     }
 #  endif
                 }
                 // check for "global"  :s/foo/bar/g
                 if (gflag == 'g') {
                     if ((found + len_R) < end_line(ls)) {
                         q = found + len_R;
                         goto vc4;   // don't let q move past cur line
                     }
                 }
             }
             q = next_line(ls);
         }
         if (subs == 0) {
             status_line_bold("No match");
         } else {
             dot_skip_over_ws();
 #  if ENABLE_FEATURE_VI_VERBOSE_STATUS
             if (subs > 1)
                 status_line("%d substitutions on %d lines", subs, lines);
 #  endif
         }
 #  if ENABLE_FEATURE_VI_REGEX_SEARCH
  regex_search_end:
         regfree(&preg);
 #  endif
 # endif /* FEATURE_VI_SEARCH */
     } else if (strncmp(cmd, "version", i) == 0) {  // show software version
         status_line(BB_VER);
     } else if (strncmp(cmd, "write", i) == 0  // write text to file
             || strcmp(cmd, "wq") == 0
             || strcmp(cmd, "wn") == 0
             || (cmd[0] == 'x' && !cmd[1])
     ) {
         int size;
         //int forced = FALSE;
         // is there a file name to write to?
         if (args[0]) {
             struct stat statbuf;
             exp = expand_args(args);
             if (exp == NULL)
                 goto ret;
             if (!useforce && (fn == NULL || strcmp(fn, exp) != 0) &&
                     stat(exp, &statbuf) == 0) {
                 status_line_bold("File exists (:w! overrides)");
                 goto ret;
             }
             fn = exp;
             init_filename(fn);
         }
 # if ENABLE_FEATURE_VI_READONLY
         else if (readonly_mode && !useforce && fn) {
             status_line_bold("'%s' is read only", fn);
             goto ret;
         }
 # endif
         //if (useforce) {
             // if "fn" is not write-able, chmod u+w
             // sprintf(syscmd, "chmod u+w %s", fn);
             // system(syscmd);
             // forced = TRUE;
         //}
         if (modified_count != 0 || cmd[0] != 'x') {
             size = r - q + 1;
             l = file_write(fn, q, r);
         } else {
             size = 0;
             l = 0;
         }
         //if (useforce && forced) {
             // chmod u-w
             // sprintf(syscmd, "chmod u-w %s", fn);
             // system(syscmd);
             // forced = FALSE;
         //}
         if (l < 0) {
             if (l == -1)
                 status_line_bold_errno(fn);
         } else {
             // how many lines written
             li = count_lines(q, q + l - 1);
             status_line("'%s' %uL, %uC", fn, li, l);
             if (l == size) {
                 if (q == text && q + l == end) {
                     modified_count = 0;
                     last_modified_count = -1;
                 }
                 if (cmd[1] == 'n') {
                     editing = 0;
                 } else if (cmd[0] == 'x' || cmd[1] == 'q') {
                     // are there other files to edit?
                     int n = cmdline_filecnt - optind - 1;
                     if (n > 0) {
                         if (useforce) {
                             // force end of argv list
                             optind = cmdline_filecnt;
                         } else {
                             status_line_bold("%u more file(s) to edit", n);
                             goto ret;
                         }
                     }
                     editing = 0;
                 }
             }
         }
 # if ENABLE_FEATURE_VI_YANKMARK
     } else if (strncmp(cmd, "yank", i) == 0) {  // yank lines
         if (!GOT_ADDRESS) { // no addr given- use defaults
             q = begin_line(dot);    // assume .,. for the range
             r = end_line(dot);
         }
         text_yank(q, r, YDreg, WHOLE);
         li = count_lines(q, r);
         status_line("Yank %d lines (%d chars) into [%c]",
                 li, strlen(reg[YDreg]), what_reg());
 # endif
     } else {
         // cmd unknown
         not_implemented(cmd);
     }
  ret:
 # if ENABLE_FEATURE_VI_COLON_EXPAND
     free(exp);
 # endif
     dot = bound_dot(dot);   // make sure "dot" is valid
     return;
 # if ENABLE_FEATURE_VI_SEARCH
  colon_s_fail:
     status_line(":s expression missing delimiters");
 # endif
 #endif /* FEATURE_VI_COLON */
 }
References args, autoindent, bb_putchar(), begin_line(), bound_dot(), buf, c, cmd, cmdline_filecnt, cnt, cookmode(), count_lines(), current_filename, dot, dot_skip_over_ws(), editing, end, end_line(), err_method, exp, expandtab, F, FALSE, file_insert(), file_write(), find_line(), flags, FORWARD, found, free, get_address(), go_bottom_and_clear_to_eol(), Hit_Return(), i, ignorecase, init_filename, init_text_buffer(), isblank, Isprint, isspace, l, last_modified_count, last_search_pattern, last_status_cksum, LIMITED, lines, MAX_INPUT_LEN, memset(), modified_count, n, next_line(), not_implemented(), NULL, num, optind, p, printf(), puts(), R, rawmode(), readonly_mode, reg, REG_ICASE, regcomp(), regfree(), show_help(), size, skip_non_whitespace(), skip_whitespace(), sscanf(), standout_end(), standout_start(), stat(), status_line(), status_line_bold(), status_line_bold_errno(), strchr_backslash, strcmp, strcpy(), STRERROR_ERRNO, STRERROR_FMT, strlen(), strncmp(), subs, system(), tabstop, text, text_hole_delete, TRUE, undo(), update_filename(), WHOLE, write1(), xstrdup(), yank_delete, YANKDEL, and YDreg.
Referenced by do_cmd().
cookmode()
static void cookmode (void) static
Definition at line 635 of file vi.c.
 {
     fflush_all();
     tcsetattr_stdin_TCSANOW(&term_orig);
 }
References fflush_all(), tcsetattr_stdin_TCSANOW(), and term_orig.
Referenced by colon(), edit_file(), and readit().
count_lines()
static int count_lines (char * start, char * stop) static
Definition at line 753 of file vi.c.
 {
     char *q;
     int cnt;
     if (stop < start) { // start and stop are backwards- reverse them
         q = start;
         start = stop;
         stop = q;
     }
     cnt = 0;
     stop = end_line(stop);
     while (start <= stop && start <= end - 1) {
         start = end_line(start);
         if (*start == '\n')
             cnt++;
         start++;
     }
     return cnt;
 }
References cnt, end, end_line(), start, and stop.
Referenced by colon(), do_cmd(), format_edit_status(), and sync_cursor().
do_cmd()
static void do_cmd (int c) static
Definition at line 3683 of file vi.c.
 {
     char *p, *q, *save_dot;
     char buf[12];
     int dir;
     int cnt, i, j;
     int c1;
 #if ENABLE_FEATURE_VI_YANKMARK
     char *orig_dot = dot;
 #endif
 #if ENABLE_FEATURE_VI_UNDO
     int allow_undo = ALLOW_UNDO;
     int undo_del = UNDO_DEL;
 #endif
 //  c1 = c; // quiet the compiler
 //  cnt = yf = 0; // quiet the compiler
 //  p = q = save_dot = buf; // quiet the compiler
     memset(buf, '\0', sizeof(buf));
     keep_index = FALSE;
     cmd_error = FALSE;
     show_status_line();
     // if this is a cursor key, skip these checks
     switch (c) {
         case KEYCODE_UP:
         case KEYCODE_DOWN:
         case KEYCODE_LEFT:
         case KEYCODE_RIGHT:
         case KEYCODE_HOME:
         case KEYCODE_END:
         case KEYCODE_PAGEUP:
         case KEYCODE_PAGEDOWN:
         case KEYCODE_DELETE:
             goto key_cmd_mode;
     }
     if (cmd_mode == 2) {
         //  flip-flop Insert/Replace mode
         if (c == KEYCODE_INSERT)
             goto dc_i;
         // we are 'R'eplacing the current *dot with new char
         if (*dot == '\n') {
             // don't Replace past E-o-l
             cmd_mode = 1;   // convert to insert
             undo_queue_commit();
         } else {
             if (1 <= c || Isprint(c)) {
                 if (c != 27 && !isbackspace(c))
                     dot = yank_delete(dot, dot, PARTIAL, YANKDEL, ALLOW_UNDO);
                 dot = char_insert(dot, c, ALLOW_UNDO_CHAIN);
             }
             goto dc1;
         }
     }
     if (cmd_mode == 1) {
         // hitting "Insert" twice means "R" replace mode
         if (c == KEYCODE_INSERT) goto dc5;
         // insert the char c at "dot"
         if (1 <= c || Isprint(c)) {
             dot = char_insert(dot, c, ALLOW_UNDO_QUEUED);
         }
         goto dc1;
     }
  key_cmd_mode:
     switch (c) {
         //case 0x01:    // soh
         //case 0x09:    // ht
         //case 0x0b:    // vt
         //case 0x0e:    // so
         //case 0x0f:    // si
         //case 0x10:    // dle
         //case 0x11:    // dc1
         //case 0x13:    // dc3
 #if ENABLE_FEATURE_VI_CRASHME
     case 0x14:          // dc4  ctrl-T
         crashme = (crashme == 0) ? 1 : 0;
         break;
 #endif
         //case 0x16:    // syn
         //case 0x17:    // etb
         //case 0x18:    // can
         //case 0x1c:    // fs
         //case 0x1d:    // gs
         //case 0x1e:    // rs
         //case 0x1f:    // us
         //case '!': // !-
         //case '#': // #-
         //case '&': // &-
         //case '(': // (-
         //case ')': // )-
         //case '*': // *-
         //case '=': // =-
         //case '@': // @-
         //case 'K': // K-
         //case 'Q': // Q-
         //case 'S': // S-
         //case 'V': // V-
         //case '[': // [-
         //case '\\':    // \-
         //case ']': // ]-
         //case '_': // _-
         //case '`': // `-
         //case 'v': // v-
     default:            // unrecognized command
         buf[0] = c;
         buf[1] = '\0';
         not_implemented(buf);
         end_cmd_q();    // stop adding to q
     case 0x00:          // nul- ignore
         break;
     case 2:         // ctrl-B  scroll up   full screen
     case KEYCODE_PAGEUP:    // Cursor Key Page Up
         dot_scroll(rows - 2, -1);
         break;
     case 4:         // ctrl-D  scroll down half screen
         dot_scroll((rows - 2) / 2, 1);
         break;
     case 5:         // ctrl-E  scroll down one line
         dot_scroll(1, 1);
         break;
     case 6:         // ctrl-F  scroll down full screen
     case KEYCODE_PAGEDOWN:  // Cursor Key Page Down
         dot_scroll(rows - 2, 1);
         break;
     case 7:         // ctrl-G  show current status
         last_status_cksum = 0;  // force status update
         break;
     case 'h':           // h- move left
     case KEYCODE_LEFT:  // cursor key Left
     case 8:     // ctrl-H- move left    (This may be ERASE char)
     case 0x7f:  // DEL- move left   (This may be ERASE char)
         do {
             dot_left();
         } while (--cmdcnt > 0);
         break;
     case 10:            // Newline ^J
     case 'j':           // j- goto next line, same col
     case KEYCODE_DOWN:  // cursor key Down
     case 13:            // Carriage Return ^M
     case '+':           // +- goto next line
         q = dot;
         do {
             p = next_line(q);
             if (p == end_line(q)) {
                 indicate_error();
                 goto dc1;
             }
             q = p;
         } while (--cmdcnt > 0);
         dot = q;
         if (c == 13 || c == '+') {
             dot_skip_over_ws();
         } else {
             // try to stay in saved column
             dot = cindex == C_END ? end_line(dot) : move_to_col(dot, cindex);
             keep_index = TRUE;
         }
         break;
     case 12:            // ctrl-L  force redraw whole screen
     case 18:            // ctrl-R  force redraw
         redraw(TRUE);   // this will redraw the entire display
         break;
     case 21:            // ctrl-U  scroll up half screen
         dot_scroll((rows - 2) / 2, -1);
         break;
     case 25:            // ctrl-Y  scroll up one line
         dot_scroll(1, -1);
         break;
     case 27:            // esc
         if (cmd_mode == 0)
             indicate_error();
         cmd_mode = 0;   // stop inserting
         undo_queue_commit();
         end_cmd_q();
         last_status_cksum = 0;  // force status update
         break;
     case ' ':           // move right
     case 'l':           // move right
     case KEYCODE_RIGHT: // Cursor Key Right
         do {
             dot_right();
         } while (--cmdcnt > 0);
         break;
 #if ENABLE_FEATURE_VI_YANKMARK
     case '"':           // "- name a register to use for Delete/Yank
         c1 = (get_one_char() | 0x20) - 'a'; // | 0x20 is tolower()
         if ((unsigned)c1 <= 25) { // a-z?
             YDreg = c1;
         } else {
             indicate_error();
         }
         break;
     case '\'':          // '- goto a specific mark
         c1 = (get_one_char() | 0x20);
         if ((unsigned)(c1 - 'a') <= 25) { // a-z?
             c1 = (c1 - 'a');
             // get the b-o-l
             q = mark[c1];
             if (text <= q && q < end) {
                 dot = q;
                 dot_begin();    // go to B-o-l
                 dot_skip_over_ws();
             } else {
                 indicate_error();
             }
         } else if (c1 == '\'') {    // goto previous context
             dot = swap_context(dot);    // swap current and previous context
             dot_begin();    // go to B-o-l
             dot_skip_over_ws();
 #if ENABLE_FEATURE_VI_YANKMARK
             orig_dot = dot; // this doesn't update stored contexts
 #endif
         } else {
             indicate_error();
         }
         break;
     case 'm':           // m- Mark a line
         // this is really stupid.  If there are any inserts or deletes
         // between text[0] and dot then this mark will not point to the
         // correct location! It could be off by many lines!
         // Well..., at least its quick and dirty.
         c1 = (get_one_char() | 0x20) - 'a';
         if ((unsigned)c1 <= 25) { // a-z?
             // remember the line
             mark[c1] = dot;
         } else {
             indicate_error();
         }
         break;
     case 'P':           // P- Put register before
     case 'p':           // p- put register after
         p = reg[YDreg];
         if (p == NULL) {
             status_line_bold("Nothing in register %c", what_reg());
             break;
         }
         cnt = 0;
         i = cmdcnt ?: 1;
         // are we putting whole lines or strings
         if (regtype[YDreg] == WHOLE) {
             if (c == 'P') {
                 dot_begin();    // putting lines- Put above
             }
             else /* if ( c == 'p') */ {
                 // are we putting after very last line?
                 if (end_line(dot) == (end - 1)) {
                     dot = end;  // force dot to end of text[]
                 } else {
                     dot_next(); // next line, then put before
                 }
             }
         } else {
             if (c == 'p')
                 dot_right();    // move to right, can move to NL
             // how far to move cursor if register doesn't have a NL
             if (strchr(p, '\n') == NULL)
                 cnt = i * strlen(p) - 1;
         }
         do {
             // dot is adjusted if text[] is reallocated so we don't have to
             string_insert(dot, p, allow_undo);  // insert the string
 # if ENABLE_FEATURE_VI_UNDO
             allow_undo = ALLOW_UNDO_CHAIN;
 # endif
         } while (--cmdcnt > 0);
         dot += cnt;
         dot_skip_over_ws();
 # if ENABLE_FEATURE_VI_YANKMARK && ENABLE_FEATURE_VI_VERBOSE_STATUS
         yank_status("Put", p, i);
 # endif
         end_cmd_q();    // stop adding to q
         break;
     case 'U':           // U- Undo; replace current line with original version
         if (reg[Ureg] != NULL) {
             p = begin_line(dot);
             q = end_line(dot);
             p = text_hole_delete(p, q, ALLOW_UNDO); // delete cur line
             p += string_insert(p, reg[Ureg], ALLOW_UNDO_CHAIN); // insert orig line
             dot = p;
             dot_skip_over_ws();
 # if ENABLE_FEATURE_VI_YANKMARK && ENABLE_FEATURE_VI_VERBOSE_STATUS
             yank_status("Undo", reg[Ureg], 1);
 # endif
         }
         break;
 #endif /* FEATURE_VI_YANKMARK */
 #if ENABLE_FEATURE_VI_UNDO
     case 'u':   // u- undo last operation
         undo_pop();
         break;
 #endif
     case '$':           // $- goto end of line
     case KEYCODE_END:       // Cursor Key End
         for (;;) {
             dot = end_line(dot);
             if (--cmdcnt <= 0)
                 break;
             dot_next();
         }
         cindex = C_END;
         keep_index = TRUE;
         break;
     case '%':           // %- find matching char of pair () [] {}
         for (q = dot; q < end && *q != '\n'; q++) {
             if (strchr("()[]{}", *q) != NULL) {
                 // we found half of a pair
                 p = find_pair(q, *q);
                 if (p == NULL) {
                     indicate_error();
                 } else {
                     dot = p;
                 }
                 break;
             }
         }
         if (*q == '\n')
             indicate_error();
         break;
     case 'f':           // f- forward to a user specified char
     case 'F':           // F- backward to a user specified char
     case 't':           // t- move to char prior to next x
     case 'T':           // T- move to char after previous x
         last_search_char = get_one_char();  // get the search char
         last_search_cmd = c;
         // fall through
     case ';':           // ;- look at rest of line for last search char
     case ',':           // ,- repeat latest search in opposite direction
         dot_to_char(c != ',' ? last_search_cmd : last_search_cmd ^ 0x20);
         break;
 #if ENABLE_FEATURE_VI_DOT_CMD
     case '.':           // .- repeat the last modifying command
         // Stuff the last_modifying_cmd back into stdin
         // and let it be re-executed.
         if (lmc_len != 0) {
             if (cmdcnt) // update saved count if current count is non-zero
                 dotcnt = cmdcnt;
             last_modifying_cmd[lmc_len] = '\0';
             ioq = ioq_start = xasprintf("%u%s", dotcnt, last_modifying_cmd);
         }
         break;
 #endif
 #if ENABLE_FEATURE_VI_SEARCH
     case 'N':           // N- backward search for last pattern
         dir = last_search_pattern[0] == '/' ? BACK : FORWARD;
         goto dc4;       // now search for pattern
         break;
     case '?':           // ?- backward search for a pattern
     case '/':           // /- forward search for a pattern
         buf[0] = c;
         buf[1] = '\0';
         q = get_input_line(buf);    // get input line- use "status line"
         if (!q[0])  // user changed mind and erased the "/"-  do nothing
             break;
         if (!q[1]) {    // if no pat re-use old pat
             if (last_search_pattern[0])
                 last_search_pattern[0] = c;
         } else {    // strlen(q) > 1: new pat- save it and find
             free(last_search_pattern);
             last_search_pattern = xstrdup(q);
         }
         // fall through
     case 'n':           // n- repeat search for last pattern
         // search rest of text[] starting at next char
         // if search fails "dot" is unchanged
         dir = last_search_pattern[0] == '/' ? FORWARD : BACK;
  dc4:
         if (last_search_pattern[1] == '\0') {
             status_line_bold("No previous search");
             break;
         }
         do {
             q = char_search(dot + dir, last_search_pattern + 1,
                         (dir << 1) | FULL);
             if (q != NULL) {
                 dot = q;    // good search, update "dot"
             } else {
                 // no pattern found between "dot" and top/bottom of file
                 // continue from other end of file
                 const char *msg;
                 q = char_search(dir == FORWARD ? text : end - 1,
                         last_search_pattern + 1, (dir << 1) | FULL);
                 if (q != NULL) {    // found something
                     dot = q;    // found new pattern- goto it
                     msg = "search hit %s, continuing at %s";
                 } else {    // pattern is nowhere in file
                     cmdcnt = 0; // force exit from loop
                     msg = "Pattern not found";
                 }
                 if (dir == FORWARD)
                     status_line_bold(msg, "BOTTOM", "TOP");
                 else
                     status_line_bold(msg, "TOP", "BOTTOM");
             }
         } while (--cmdcnt > 0);
         break;
     case '{':           // {- move backward paragraph
     case '}':           // }- move forward paragraph
         dir = c == '}' ? FORWARD : BACK;
         do {
             int skip = TRUE; // initially skip consecutive empty lines
             while (dir == FORWARD ? dot < end - 1 : dot > text) {
                 if (*dot == '\n' && dot[dir] == '\n') {
                     if (!skip) {
                         if (dir == FORWARD)
                             ++dot;  // move to next blank line
                         goto dc2;
                     }
                 }
                 else {
                     skip = FALSE;
                 }
                 dot += dir;
             }
             goto dc6; // end of file
  dc2:       continue;
         } while (--cmdcnt > 0);
         break;
 #endif /* FEATURE_VI_SEARCH */
     case '0':           // 0- goto beginning of line
     case '1':           // 1-
     case '2':           // 2-
     case '3':           // 3-
     case '4':           // 4-
     case '5':           // 5-
     case '6':           // 6-
     case '7':           // 7-
     case '8':           // 8-
     case '9':           // 9-
         if (c == '0' && cmdcnt < 1) {
             dot_begin();    // this was a standalone zero
         } else {
             cmdcnt = cmdcnt * 10 + (c - '0');   // this 0 is part of a number
         }
         break;
     case ':':           // :- the colon mode commands
         p = get_input_line(":");    // get input line- use "status line"
         colon(p);       // execute the command
         break;
     case '<':           // <- Left  shift something
     case '>':           // >- Right shift something
         cnt = count_lines(text, dot);   // remember what line we are on
         if (find_range(&p, &q, c) == -1)
             goto dc6;
         i = count_lines(p, q);  // # of lines we are shifting
         for (p = begin_line(p); i > 0; i--, p = next_line(p)) {
             if (c == '<') {
                 // shift left- remove tab or tabstop spaces
                 if (*p == '\t') {
                     // shrink buffer 1 char
                     text_hole_delete(p, p, allow_undo);
                 } else if (*p == ' ') {
                     // we should be calculating columns, not just SPACE
                     for (j = 0; *p == ' ' && j < tabstop; j++) {
                         text_hole_delete(p, p, allow_undo);
 #if ENABLE_FEATURE_VI_UNDO
                         allow_undo = ALLOW_UNDO_CHAIN;
 #endif
                     }
                 }
             } else if (/* c == '>' && */ p != end_line(p)) {
                 // shift right -- add tab or tabstop spaces on non-empty lines
                 char_insert(p, '\t', allow_undo);
             }
 #if ENABLE_FEATURE_VI_UNDO
             allow_undo = ALLOW_UNDO_CHAIN;
 #endif
         }
         dot = find_line(cnt);   // what line were we on
         dot_skip_over_ws();
         end_cmd_q();    // stop adding to q
         break;
     case 'A':           // A- append at e-o-l
         dot_end();      // go to e-o-l
         //**** fall through to ... 'a'
     case 'a':           // a- append after current char
         if (*dot != '\n')
             dot++;
         goto dc_i;
         break;
     case 'B':           // B- back a blank-delimited Word
     case 'E':           // E- end of a blank-delimited word
     case 'W':           // W- forward a blank-delimited word
         dir = FORWARD;
         if (c == 'B')
             dir = BACK;
         do {
             if (c == 'W' || isspace(dot[dir])) {
                 dot = skip_thing(dot, 1, dir, S_TO_WS);
                 dot = skip_thing(dot, 2, dir, S_OVER_WS);
             }
             if (c != 'W')
                 dot = skip_thing(dot, 1, dir, S_BEFORE_WS);
         } while (--cmdcnt > 0);
         break;
     case 'C':           // C- Change to e-o-l
     case 'D':           // D- delete to e-o-l
         save_dot = dot;
         dot = dollar_line(dot); // move to before NL
         // copy text into a register and delete
         dot = yank_delete(save_dot, dot, PARTIAL, YANKDEL, ALLOW_UNDO); // delete to e-o-l
         if (c == 'C')
             goto dc_i;  // start inserting
 #if ENABLE_FEATURE_VI_DOT_CMD
         if (c == 'D')
             end_cmd_q();    // stop adding to q
 #endif
         break;
     case 'g': // 'gg' goto a line number (vim) (default: very first line)
         c1 = get_one_char();
         if (c1 != 'g') {
             buf[0] = 'g';
             // c1 < 0 if the key was special. Try "g<up-arrow>"
             // TODO: if Unicode?
             buf[1] = (c1 >= 0 ? c1 : '*');
             buf[2] = '\0';
             not_implemented(buf);
             cmd_error = TRUE;
             break;
         }
         if (cmdcnt == 0)
             cmdcnt = 1;
         // fall through
     case 'G':       // G- goto to a line number (default= E-O-F)
         dot = end - 1;              // assume E-O-F
         if (cmdcnt > 0) {
             dot = find_line(cmdcnt);    // what line is #cmdcnt
         }
         dot_begin();
         dot_skip_over_ws();
         break;
     case 'H':           // H- goto top line on screen
         dot = screenbegin;
         if (cmdcnt > (rows - 1)) {
             cmdcnt = (rows - 1);
         }
         while (--cmdcnt > 0) {
             dot_next();
         }
         dot_begin();
         dot_skip_over_ws();
         break;
     case 'I':           // I- insert before first non-blank
         dot_begin();    // 0
         dot_skip_over_ws();
         //**** fall through to ... 'i'
     case 'i':           // i- insert before current char
     case KEYCODE_INSERT:    // Cursor Key Insert
  dc_i:
 #if ENABLE_FEATURE_VI_SETOPTS
         newindent = -1;
 #endif
         cmd_mode = 1;   // start inserting
         undo_queue_commit();    // commit queue when cmd_mode changes
         break;
     case 'J':           // J- join current and next lines together
         do {
             dot_end();      // move to NL
             if (dot < end - 1) {    // make sure not last char in text[]
 #if ENABLE_FEATURE_VI_UNDO
                 undo_push(dot, 1, UNDO_DEL);
                 *dot++ = ' ';   // replace NL with space
                 undo_push((dot - 1), 1, UNDO_INS_CHAIN);
 #else
                 *dot++ = ' ';
                 modified_count++;
 #endif
                 while (isblank(*dot)) { // delete leading WS
                     text_hole_delete(dot, dot, ALLOW_UNDO_CHAIN);
                 }
             }
         } while (--cmdcnt > 0);
         end_cmd_q();    // stop adding to q
         break;
     case 'L':           // L- goto bottom line on screen
         dot = end_screen();
         if (cmdcnt > (rows - 1)) {
             cmdcnt = (rows - 1);
         }
         while (--cmdcnt > 0) {
             dot_prev();
         }
         dot_begin();
         dot_skip_over_ws();
         break;
     case 'M':           // M- goto middle line on screen
         dot = screenbegin;
         for (cnt = 0; cnt < (rows-1) / 2; cnt++)
             dot = next_line(dot);
         dot_skip_over_ws();
         break;
     case 'O':           // O- open an empty line above
         dot_begin();
 #if ENABLE_FEATURE_VI_SETOPTS
         // special case: use indent of current line
         newindent = get_column(dot + indent_len(dot));
 #endif
         goto dc3;
     case 'o':           // o- open an empty line below
         dot_end();
  dc3:
 #if ENABLE_FEATURE_VI_SETOPTS
         cmd_mode = 1;   // switch to insert mode early
 #endif
         dot = char_insert(dot, '\n', ALLOW_UNDO);
         if (c == 'O' && !autoindent) {
             // done in char_insert() for 'O'+autoindent
             dot_prev();
         }
         goto dc_i;
         break;
     case 'R':           // R- continuous Replace char
  dc5:
         cmd_mode = 2;
         undo_queue_commit();
         rstart = dot;
         break;
     case KEYCODE_DELETE:
         if (dot < end - 1)
             dot = yank_delete(dot, dot, PARTIAL, YANKDEL, ALLOW_UNDO);
         break;
     case 'X':           // X- delete char before dot
     case 'x':           // x- delete the current char
     case 's':           // s- substitute the current char
         dir = 0;
         if (c == 'X')
             dir = -1;
         do {
             if (dot[dir] != '\n') {
                 if (c == 'X')
                     dot--;  // delete prev char
                 dot = yank_delete(dot, dot, PARTIAL, YANKDEL, allow_undo);  // delete char
 #if ENABLE_FEATURE_VI_UNDO
                 allow_undo = ALLOW_UNDO_CHAIN;
 #endif
             }
         } while (--cmdcnt > 0);
         end_cmd_q();    // stop adding to q
         if (c == 's')
             goto dc_i;  // start inserting
         break;
     case 'Z':           // Z- if modified, {write}; exit
         c1 = get_one_char();
         // ZQ means to exit without saving
         if (c1 == 'Q') {
             editing = 0;
             optind = cmdline_filecnt;
             break;
         }
         // ZZ means to save file (if necessary), then exit
         if (c1 != 'Z') {
             indicate_error();
             break;
         }
         if (modified_count) {
             if (ENABLE_FEATURE_VI_READONLY && readonly_mode && current_filename) {
                 status_line_bold("'%s' is read only", current_filename);
                 break;
             }
             cnt = file_write(current_filename, text, end - 1);
             if (cnt < 0) {
                 if (cnt == -1)
                     status_line_bold("Write error: "STRERROR_FMT STRERROR_ERRNO);
             } else if (cnt == (end - 1 - text + 1)) {
                 editing = 0;
             }
         } else {
             editing = 0;
         }
         // are there other files to edit?
         j = cmdline_filecnt - optind - 1;
         if (editing == 0 && j > 0) {
             editing = 1;
             modified_count = 0;
             last_modified_count = -1;
             status_line_bold("%u more file(s) to edit", j);
         }
         break;
     case '^':           // ^- move to first non-blank on line
         dot_begin();
         dot_skip_over_ws();
         break;
     case 'b':           // b- back a word
     case 'e':           // e- end of word
         dir = FORWARD;
         if (c == 'b')
             dir = BACK;
         do {
             if ((dot + dir) < text || (dot + dir) > end - 1)
                 break;
             dot += dir;
             if (isspace(*dot)) {
                 dot = skip_thing(dot, (c == 'e') ? 2 : 1, dir, S_OVER_WS);
             }
             if (isalnum(*dot) || *dot == '_') {
                 dot = skip_thing(dot, 1, dir, S_END_ALNUM);
             } else if (ispunct(*dot)) {
                 dot = skip_thing(dot, 1, dir, S_END_PUNCT);
             }
         } while (--cmdcnt > 0);
         break;
     case 'c':           // c- change something
     case 'd':           // d- delete something
 #if ENABLE_FEATURE_VI_YANKMARK
     case 'y':           // y- yank   something
     case 'Y':           // Y- Yank a line
 #endif
     {
         int yf = YANKDEL;   // assume either "c" or "d"
         int buftype;
 #if ENABLE_FEATURE_VI_YANKMARK
 # if ENABLE_FEATURE_VI_VERBOSE_STATUS
         char *savereg = reg[YDreg];
 # endif
         if (c == 'y' || c == 'Y')
             yf = YANKONLY;
 #endif
         // determine range, and whether it spans lines
         buftype = find_range(&p, &q, c);
         if (buftype == -1)  // invalid range
             goto dc6;
         if (buftype == WHOLE) {
             save_dot = p;   // final cursor position is start of range
             p = begin_line(p);
 #if ENABLE_FEATURE_VI_SETOPTS
             if (c == 'c')   // special case: use indent of current line
                 newindent = get_column(p + indent_len(p));
 #endif
             q = end_line(q);
         }
         dot = yank_delete(p, q, buftype, yf, ALLOW_UNDO);   // delete word
         if (buftype == WHOLE) {
             if (c == 'c') {
 #if ENABLE_FEATURE_VI_SETOPTS
                 cmd_mode = 1;   // switch to insert mode early
 #endif
                 dot = char_insert(dot, '\n', ALLOW_UNDO_CHAIN);
                 // on the last line of file don't move to prev line,
                 // handled in char_insert() if autoindent is enabled
                 if (dot != (end-1) && !autoindent) {
                     dot_prev();
                 }
             } else if (c == 'd') {
                 dot_begin();
                 dot_skip_over_ws();
             } else {
                 dot = save_dot;
             }
         }
         // if CHANGING, not deleting, start inserting after the delete
         if (c == 'c') {
             goto dc_i;  // start inserting
         }
 #if ENABLE_FEATURE_VI_YANKMARK && ENABLE_FEATURE_VI_VERBOSE_STATUS
         // only update status if a yank has actually happened
         if (reg[YDreg] != savereg)
             yank_status(c == 'd' ? "Delete" : "Yank", reg[YDreg], 1);
 #endif
  dc6:
         end_cmd_q();    // stop adding to q
         break;
     }
     case 'k':           // k- goto prev line, same col
     case KEYCODE_UP:        // cursor key Up
     case '-':           // -- goto prev line
         q = dot;
         do {
             p = prev_line(q);
             if (p == begin_line(q)) {
                 indicate_error();
                 goto dc1;
             }
             q = p;
         } while (--cmdcnt > 0);
         dot = q;
         if (c == '-') {
             dot_skip_over_ws();
         } else {
             // try to stay in saved column
             dot = cindex == C_END ? end_line(dot) : move_to_col(dot, cindex);
             keep_index = TRUE;
         }
         break;
     case 'r':           // r- replace the current char with user input
         c1 = get_one_char();    // get the replacement char
         if (c1 != 27) {
             if (end_line(dot) - dot < (cmdcnt ?: 1)) {
                 indicate_error();
                 goto dc6;
             }
             do {
                 dot = text_hole_delete(dot, dot, allow_undo);
 #if ENABLE_FEATURE_VI_UNDO
                 allow_undo = ALLOW_UNDO_CHAIN;
 #endif
                 dot = char_insert(dot, c1, allow_undo);
             } while (--cmdcnt > 0);
             dot_left();
         }
         end_cmd_q();    // stop adding to q
         break;
     case 'w':           // w- forward a word
         do {
             if (isalnum(*dot) || *dot == '_') { // we are on ALNUM
                 dot = skip_thing(dot, 1, FORWARD, S_END_ALNUM);
             } else if (ispunct(*dot)) { // we are on PUNCT
                 dot = skip_thing(dot, 1, FORWARD, S_END_PUNCT);
             }
             if (dot < end - 1)
                 dot++;      // move over word
             if (isspace(*dot)) {
                 dot = skip_thing(dot, 2, FORWARD, S_OVER_WS);
             }
         } while (--cmdcnt > 0);
         break;
     case 'z':           // z-
         c1 = get_one_char();    // get the replacement char
         cnt = 0;
         if (c1 == '.')
             cnt = (rows - 2) / 2;   // put dot at center
         if (c1 == '-')
             cnt = rows - 2; // put dot at bottom
         screenbegin = begin_line(dot);  // start dot at top
         dot_scroll(cnt, -1);
         break;
     case '|':           // |- move to column "cmdcnt"
         dot = move_to_col(dot, cmdcnt - 1); // try to move to column
         break;
     case '~':           // ~- flip the case of letters   a-z -> A-Z
         do {
 #if ENABLE_FEATURE_VI_UNDO
             if (isalpha(*dot)) {
                 undo_push(dot, 1, undo_del);
                 *dot = islower(*dot) ? toupper(*dot) : tolower(*dot);
                 undo_push(dot, 1, UNDO_INS_CHAIN);
                 undo_del = UNDO_DEL_CHAIN;
             }
 #else
             if (islower(*dot)) {
                 *dot = toupper(*dot);
                 modified_count++;
             } else if (isupper(*dot)) {
                 *dot = tolower(*dot);
                 modified_count++;
             }
 #endif
             dot_right();
         } while (--cmdcnt > 0);
         end_cmd_q();    // stop adding to q
         break;
         //----- The Cursor and Function Keys -----------------------------
     case KEYCODE_HOME:  // Cursor Key Home
         dot_begin();
         break;
         // The Fn keys could point to do_macro which could translate them
 #if 0
     case KEYCODE_FUN1:  // Function Key F1
     case KEYCODE_FUN2:  // Function Key F2
     case KEYCODE_FUN3:  // Function Key F3
     case KEYCODE_FUN4:  // Function Key F4
     case KEYCODE_FUN5:  // Function Key F5
     case KEYCODE_FUN6:  // Function Key F6
     case KEYCODE_FUN7:  // Function Key F7
     case KEYCODE_FUN8:  // Function Key F8
     case KEYCODE_FUN9:  // Function Key F9
     case KEYCODE_FUN10: // Function Key F10
     case KEYCODE_FUN11: // Function Key F11
     case KEYCODE_FUN12: // Function Key F12
         break;
 #endif
     }
  dc1:
     // if text[] just became empty, add back an empty line
     if (end == text) {
         char_insert(text, '\n', NO_UNDO);   // start empty buf with dummy line
         dot = text;
     }
     // it is OK for dot to exactly equal to end, otherwise check dot validity
     if (dot != end) {
         dot = bound_dot(dot);   // make sure "dot" is valid
     }
 #if ENABLE_FEATURE_VI_YANKMARK
     if (dot != orig_dot)
         check_context(c);   // update the current context
 #endif
     if (!isdigit(c))
         cmdcnt = 0;     // cmd was not a number, reset cmdcnt
     cnt = dot - begin_line(dot);
     // Try to stay off of the Newline
     if (*dot == '\n' && cnt > 0 && cmd_mode == 0)
         dot--;
 }
References autoindent, BACK, begin_line(), bound_dot(), buf, c, C_END, char_insert, cindex, cmd_error, cmd_mode, cmdcnt, cmdline_filecnt, cnt, colon(), count_lines(), current_filename, dir, dollar_line(), dot, dot_begin(), dot_end(), dot_left(), dot_next(), dot_prev(), dot_right(), dot_scroll(), dot_skip_over_ws(), dot_to_char(), dotcnt, editing, end, end_cmd_q, end_line(), end_screen(), FALSE, file_write(), find_line(), find_pair(), find_range(), FORWARD, free, FULL, get_column(), get_input_line(), get_one_char, i, indent_len(), indicate_error(), ioq, ioq_start, isalnum, isalpha, isbackspace, isblank, isdigit, islower, Isprint, ispunct, isspace, isupper, j, keep_index, KEYCODE_DELETE, KEYCODE_DOWN, KEYCODE_END, KEYCODE_HOME, KEYCODE_INSERT, KEYCODE_LEFT, KEYCODE_PAGEDOWN, KEYCODE_PAGEUP, KEYCODE_RIGHT, KEYCODE_UP, last_modified_count, last_modifying_cmd, last_search_char, last_search_cmd, last_search_pattern, last_status_cksum, lmc_len, mark, memset(), modified_count, move_to_col(), newindent, next_line(), not_implemented(), NULL, optind, p, PARTIAL, prev_line(), readonly_mode, redraw(), reg, regtype, rows, rstart, S_BEFORE_WS, S_END_ALNUM, S_END_PUNCT, S_OVER_WS, S_TO_WS, screenbegin, show_status_line(), skip, skip_thing(), status_line_bold(), strchr(), STRERROR_ERRNO, STRERROR_FMT, strlen(), tabstop, text, text_hole_delete, tolower, toupper, TRUE, undo_queue_commit, WHOLE, xasprintf(), xstrdup(), yank_delete, YANKDEL, YANKONLY, and YDreg.
Referenced by edit_file(), and find_range().
dollar_line()
static char* dollar_line (char * p) static
Definition at line 712 of file vi.c.
 {
     p = end_line(p);
     // Try to stay off of the Newline
     if (*p == '\n' && (p - begin_line(p)) > 0)
         p--;
     return p;
 }
References begin_line(), end_line(), and p.
Referenced by do_cmd().
dot_begin()
static void dot_begin (void) static
Definition at line 1823 of file vi.c.
 {
     undo_queue_commit();
     dot = begin_line(dot);  // return pointer to first char cur line
 }
References begin_line(), dot, and undo_queue_commit.
Referenced by do_cmd().
dot_end()
static void dot_end (void) static
Definition at line 1829 of file vi.c.
 {
     undo_queue_commit();
     dot = end_line(dot);    // return pointer to last char cur line
 }
References dot, end_line(), and undo_queue_commit.
Referenced by do_cmd().
dot_left()
static void dot_left (void) static
Definition at line 1809 of file vi.c.
 {
     undo_queue_commit();
     if (dot > text && dot[-1] != '\n')
         dot--;
 }
References dot, text, and undo_queue_commit.
Referenced by do_cmd(), and dot_to_char().
dot_next()
static void dot_next (void) static
Definition at line 1849 of file vi.c.
 {
     undo_queue_commit();
     dot = next_line(dot);
 }
References dot, next_line(), and undo_queue_commit.
Referenced by do_cmd().
dot_prev()
static void dot_prev (void) static
Definition at line 1855 of file vi.c.
 {
     undo_queue_commit();
     dot = prev_line(dot);
 }
References dot, prev_line(), and undo_queue_commit.
Referenced by do_cmd().
dot_right()
static void dot_right (void) static
Definition at line 1816 of file vi.c.
 {
     undo_queue_commit();
     if (dot < end - 1 && *dot != '\n')
         dot++;
 }
References dot, end, and undo_queue_commit.
Referenced by do_cmd(), and dot_to_char().
dot_scroll()
static void dot_scroll (int cnt, int dir) static
Definition at line 1895 of file vi.c.
 {
     char *q;
     undo_queue_commit();
     for (; cnt > 0; cnt--) {
         if (dir < 0) {
             // scroll Backwards
             // ctrl-Y scroll up one line
             screenbegin = prev_line(screenbegin);
         } else {
             // scroll Forwards
             // ctrl-E scroll down one line
             screenbegin = next_line(screenbegin);
         }
     }
     // make sure "dot" stays on the screen so we dont scroll off
     if (dot < screenbegin)
         dot = screenbegin;
     q = end_screen();   // find new bottom line
     if (dot > q)
         dot = begin_line(q);    // is dot is below bottom line?
     dot_skip_over_ws();
 }
References begin_line(), cnt, dir, dot, dot_skip_over_ws(), end_screen(), next_line(), prev_line(), screenbegin, and undo_queue_commit.
Referenced by do_cmd().
dot_skip_over_ws()
static void dot_skip_over_ws (void) static
Definition at line 1861 of file vi.c.
 {
     // skip WS
     while (isspace(*dot) && *dot != '\n' && dot < end - 1)
         dot++;
 }
References dot, end, and isspace.
Referenced by colon(), do_cmd(), and dot_scroll().
dot_to_char()
static void dot_to_char (int cmd) static
Definition at line 1868 of file vi.c.
 {
     char *q = dot;
     int dir = islower(cmd) ? FORWARD : BACK;
     if (last_search_char == 0)
         return;
     do {
         do {
             q += dir;
             if ((dir == FORWARD ? q > end - 1 : q < text) || *q == '\n') {
                 indicate_error();
                 return;
             }
         } while (*q != last_search_char);
     } while (--cmdcnt > 0);
     dot = q;
     // place cursor before/after char as required
     if (cmd == 't')
         dot_left();
     else if (cmd == 'T')
         dot_right();
 }
References BACK, cmd, cmdcnt, dir, dot, dot_left(), dot_right(), end, FORWARD, indicate_error(), islower, last_search_char, and text.
Referenced by do_cmd().
edit_file()
static void edit_file (char * fn) static
Definition at line 4801 of file vi.c.
 {
 #if ENABLE_FEATURE_VI_YANKMARK
 #define cur_line edit_file__cur_line
 #endif
     int c;
 #if ENABLE_FEATURE_VI_USE_SIGNALS
     int sig;
 #endif
     editing = 1;    // 0 = exit, 1 = one file, 2 = multiple files
     rawmode();
     rows = 24;
     columns = 80;
     IF_FEATURE_VI_ASK_TERMINAL(G.get_rowcol_error =) query_screen_dimensions();
 #if ENABLE_FEATURE_VI_ASK_TERMINAL
     if (G.get_rowcol_error /* TODO? && no input on stdin */) {
         uint64_t k;
         write1(ESC"[999;999H" ESC"[6n");
         fflush_all();
         k = safe_read_key(STDIN_FILENO, readbuffer, /*timeout_ms:*/ 100);
         if ((int32_t)k == KEYCODE_CURSOR_POS) {
             uint32_t rc = (k >> 32);
             columns = (rc & 0x7fff);
             if (columns > MAX_SCR_COLS)
                 columns = MAX_SCR_COLS;
             rows = ((rc >> 16) & 0x7fff);
             if (rows > MAX_SCR_ROWS)
                 rows = MAX_SCR_ROWS;
         }
     }
 #endif
     new_screen(rows, columns);  // get memory for virtual screen
     init_text_buffer(fn);
 #if ENABLE_FEATURE_VI_YANKMARK
     YDreg = 26;         // default Yank/Delete reg
 //  Ureg = 27; - const      // hold orig line for "U" cmd
     mark[26] = mark[27] = text; // init "previous context"
 #endif
 #if ENABLE_FEATURE_VI_CRASHME
     last_input_char = '\0';
 #endif
     crow = 0;
     ccol = 0;
 #if ENABLE_FEATURE_VI_USE_SIGNALS
     signal(SIGWINCH, winch_handler);
     signal(SIGTSTP, tstp_handler);
     sig = sigsetjmp(restart, 1);
     if (sig != 0) {
         screenbegin = dot = text;
     }
     // int_handler() can jump to "restart",
     // must install handler *after* initializing "restart"
     signal(SIGINT, int_handler);
 #endif
     cmd_mode = 0;       // 0=command  1=insert  2='R'eplace
     cmdcnt = 0;
     offset = 0;         // no horizontal offset
     c = '\0';
 #if ENABLE_FEATURE_VI_DOT_CMD
     free(ioq_start);
     ioq_start = NULL;
     adding2q = 0;
 #endif
 #if ENABLE_FEATURE_VI_COLON
     while (initial_cmds)
         run_cmds((char *)llist_pop(&initial_cmds));
 #endif
     redraw(FALSE);          // dont force every col re-draw
     //------This is the main Vi cmd handling loop -----------------------
     while (editing > 0) {
 #if ENABLE_FEATURE_VI_CRASHME
         if (crashme > 0) {
             if ((end - text) > 1) {
                 crash_dummy();  // generate a random command
             } else {
                 crashme = 0;
                 string_insert(text, "\n\n#####  Ran out of text to work on.  #####\n\n", NO_UNDO);
                 dot = text;
                 refresh(FALSE);
             }
         }
 #endif
         c = get_one_char(); // get a cmd from user
 #if ENABLE_FEATURE_VI_CRASHME
         last_input_char = c;
 #endif
 #if ENABLE_FEATURE_VI_YANKMARK
         // save a copy of the current line- for the 'U" command
         if (begin_line(dot) != cur_line) {
             cur_line = begin_line(dot);
             text_yank(begin_line(dot), end_line(dot), Ureg, PARTIAL);
         }
 #endif
 #if ENABLE_FEATURE_VI_DOT_CMD
         // If c is a command that changes text[],
         // (re)start remembering the input for the "." command.
         if (!adding2q
          && ioq_start == NULL
          && cmd_mode == 0 // command mode
          && c > '\0' // exclude NUL and non-ASCII chars
          && c < 0x7f // (Unicode and such)
          && strchr(modifying_cmds, c)
         ) {
             start_new_cmd_q(c);
         }
 #endif
         do_cmd(c);      // execute the user command
         // poll to see if there is input already waiting. if we are
         // not able to display output fast enough to keep up, skip
         // the display update until we catch up with input.
         if (!readbuffer[0] && mysleep(0) == 0) {
             // no input pending - so update output
             refresh(FALSE);
             show_status_line();
         }
 #if ENABLE_FEATURE_VI_CRASHME
         if (crashme > 0)
             crash_test();   // test editor variables
 #endif
     }
     //-------------------------------------------------------------------
     go_bottom_and_clear_to_eol();
     cookmode();
 #undef cur_line
 }
References adding2q, begin_line(), c, ccol, cmd_mode, cmdcnt, columns, cookmode(), crow, do_cmd(), dot, editing, end, end_line(), ESC, FALSE, fflush_all(), free, G, get_one_char, go_bottom_and_clear_to_eol(), init_text_buffer(), initial_cmds, ioq_start, k, KEYCODE_CURSOR_POS, llist_pop(), mark, MAX_SCR_COLS, MAX_SCR_ROWS, mysleep(), new_screen(), NULL, offset, PARTIAL, query_screen_dimensions(), rawmode(), rc, readbuffer, redraw(), refresh(), restart, rows, safe_read_key(), screenbegin, show_status_line(), SIGINT, signal, SIGTSTP, SIGWINCH, STDIN_FILENO, strchr(), text, winch_handler(), write1(), and YDreg.
Referenced by vi_main().
end_line()
static char* end_line (char * p) static
Definition at line 702 of file vi.c.
 {
     if (p < end - 1) {
         p = memchr(p, '\n', end - p - 1);
         if (!p)
             return end - 1;
     }
     return p;
 }
References end, memchr(), and p.
Referenced by char_insert(), colon(), count_lines(), do_cmd(), dollar_line(), dot_end(), edit_file(), end_screen(), next_line(), and sync_cursor().
end_screen()
static char* end_screen (void) static
Definition at line 739 of file vi.c.
 {
     char *q;
     int cnt;
     // find new bottom line
     q = screenbegin;
     for (cnt = 0; cnt < rows - 2; cnt++)
         q = next_line(q);
     q = end_line(q);
     return q;
 }
References cnt, end_line(), next_line(), rows, and screenbegin.
Referenced by do_cmd(), dot_scroll(), and sync_cursor().
file_insert()
static int file_insert (const char * fn, char * p, int initial) static
Definition at line 1982 of file vi.c.
 {
     int cnt = -1;
     int fd, size;
     struct stat statbuf;
     if (p < text)
         p = text;
     if (p > end)
         p = end;
     fd = open(fn, O_RDONLY);
     if (fd < 0) {
         if (!initial)
             status_line_bold_errno(fn);
         return cnt;
     }
     // Validate file
     if (fstat(fd, &statbuf) < 0) {
         status_line_bold_errno(fn);
         goto fi;
     }
     if (!S_ISREG(statbuf.st_mode)) {
         status_line_bold("'%s' is not a regular file", fn);
         goto fi;
     }
     size = (statbuf.st_size < INT_MAX ? (int)statbuf.st_size : INT_MAX);
     p += text_hole_make(p, size);
     cnt = full_read(fd, p, size);
     if (cnt < 0) {
         status_line_bold_errno(fn);
         p = text_hole_delete(p, p + size - 1, NO_UNDO); // un-do buffer insert
     } else if (cnt < size) {
         // There was a partial read, shrink unused space
         p = text_hole_delete(p + cnt, p + size - 1, NO_UNDO);
         status_line_bold("can't read '%s'", fn);
     }
 # if ENABLE_FEATURE_VI_UNDO
     else {
         undo_push_insert(p, size, ALLOW_UNDO);
     }
 # endif
  fi:
     close(fd);
 #if ENABLE_FEATURE_VI_READONLY
     if (initial
      && ((access(fn, W_OK) < 0) ||
         // root will always have access()
         // so we check fileperms too
         !(statbuf.st_mode & (S_IWUSR | S_IWGRP | S_IWOTH))
         )
     ) {
         SET_READONLY_FILE(readonly_mode);
     }
 #endif
     return cnt;
 }
References access(), close(), cnt, end, fd, fstat(), full_read(), INT_MAX, O_RDONLY, open(), p, readonly_mode, S_ISREG, S_IWGRP, S_IWOTH, S_IWUSR, SET_READONLY_FILE, size, stat::st_mode, stat::st_size, status_line_bold(), status_line_bold_errno(), text, text_hole_delete, text_hole_make(), and W_OK.
Referenced by colon(), and init_text_buffer().
file_write()
static int file_write (char * fn, char * first, char * last) static
Definition at line 2357 of file vi.c.
 {
     int fd, cnt, charcnt;
     if (fn == 0) {
         status_line_bold("No current filename");
         return -2;
     }
     // By popular request we do not open file with O_TRUNC,
     // but instead ftruncate() it _after_ successful write.
     // Might reduce amount of data lost on power fail etc.
     fd = open(fn, (O_WRONLY | O_CREAT), 0666);
     if (fd < 0)
         return -1;
     cnt = last - first + 1;
     charcnt = full_write(fd, first, cnt);
     ftruncate(fd, charcnt);
     if (charcnt == cnt) {
         // good write
         //modified_count = FALSE;
     } else {
         charcnt = 0;
     }
     close(fd);
     return charcnt;
 }
References close(), cnt, fd, first, ftruncate(), full_write(), last, O_CREAT, O_WRONLY, open(), and status_line_bold().
Referenced by colon(), and do_cmd().
find_line()
static char* find_line (int li) static
Definition at line 774 of file vi.c.
 {
     char *q;
     for (q = text; li > 1; li--) {
         q = next_line(q);
     }
     return q;
 }
References next_line(), and text.
Referenced by colon(), and do_cmd().
find_pair()
static char* find_pair (char * p, const char c) static
Definition at line 2044 of file vi.c.
 {
     const char *braces = "()[]{}";
     char match;
     int dir, level;
     dir = strchr(braces, c) - braces;
     dir ^= 1;
     match = braces[dir];
     dir = ((dir & 1) << 1) - 1; // 1 for ([{, -1 for )\}
     // look for match, count levels of pairs  (( ))
     level = 1;
     for (;;) {
         p += dir;
         if (p < text || p >= end)
             return NULL;
         if (*p == c)
             level++;    // increase pair levels
         if (*p == match) {
             level--;    // reduce pair level
             if (level == 0)
                 return p; // found matching pair
         }
     }
 }
References c, dir, end, match(), NULL, p, and strchr().
Referenced by do_cmd().
find_range()
static int find_range (char ** start, char ** stop, int cmd) static
Definition at line 3558 of file vi.c.
 {
     char *p, *q, *t;
     int buftype = -1;
     int c;
     p = q = dot;
 #if ENABLE_FEATURE_VI_YANKMARK
     if (cmd == 'Y') {
         c = 'y';
     } else
 #endif
     {
         c = get_motion_char();
     }
 #if ENABLE_FEATURE_VI_YANKMARK
     if ((cmd == 'Y' || cmd == c) && strchr("cdy><", c)) {
 #else
     if (cmd == c && strchr("cd><", c)) {
 #endif
         // these cmds operate on whole lines
         buftype = WHOLE;
         if (--cmdcnt > 0) {
             do_cmd('j');
             if (cmd_error)
                 buftype = -1;
         }
     } else if (strchr("^%$0bBeEfFtThnN/?|{}\b\177", c)) {
         // Most operate on char positions within a line.  Of those that
         // don't '%' needs no special treatment, search commands are
         // marked as MULTI and  "{}" are handled below.
         buftype = strchr("nN/?", c) ? MULTI : PARTIAL;
         do_cmd(c);      // execute movement cmd
         if (p == dot)   // no movement is an error
             buftype = -1;
     } else if (strchr("wW", c)) {
         buftype = MULTI;
         do_cmd(c);      // execute movement cmd
         // step back one char, but not if we're at end of file,
         // or if we are at EOF and search was for 'w' and we're at
         // the start of a 'W' word.
         if (dot > p && (!at_eof(dot) || (c == 'w' && ispunct(*dot))))
             dot--;
         t = dot;
         // don't include trailing WS as part of word
         while (dot > p && isspace(*dot)) {
             if (*dot-- == '\n')
                 t = dot;
         }
         // for non-change operations WS after NL is not part of word
         if (cmd != 'c' && dot != t && *dot != '\n')
             dot = t;
     } else if (strchr("GHL+-gjk'\r\n", c)) {
         // these operate on whole lines
         buftype = WHOLE;
         do_cmd(c);      // execute movement cmd
         if (cmd_error)
             buftype = -1;
     } else if (c == ' ' || c == 'l') {
         // forward motion by character
         int tmpcnt = (cmdcnt ?: 1);
         buftype = PARTIAL;
         do_cmd(c);      // execute movement cmd
         // exclude last char unless range isn't what we expected
         // this indicates we've hit EOL
         if (tmpcnt == dot - p)
             dot--;
     }
     if (buftype == -1) {
         if (c != 27)
             indicate_error();
         return buftype;
     }
     q = dot;
     if (q < p) {
         t = q;
         q = p;
         p = t;
     }
     // movements which don't include end of range
     if (q > p) {
         if (strchr("^0bBFThnN/?|\b\177", c)) {
             q--;
         } else if (strchr("{}", c)) {
             buftype = (p == begin_line(p) && (*q == '\n' || at_eof(q))) ?
                             WHOLE : MULTI;
             if (!at_eof(q)) {
                 q--;
                 if (q > p && p != begin_line(p))
                     q--;
             }
         }
     }
     *start = p;
     *stop = q;
     return buftype;
 }
References at_eof(), begin_line(), c, cmd, cmd_error, cmdcnt, do_cmd(), dot, get_motion_char(), indicate_error(), ispunct, isspace, MULTI, p, PARTIAL, start, stop, strchr(), t, and WHOLE.
Referenced by do_cmd().
flash()
static void flash (int h) static
Definition at line 1098 of file vi.c.
 {
     standout_start();
     redraw(TRUE);
     mysleep(h);
     standout_end();
     redraw(TRUE);
 }
References h, mysleep(), redraw(), standout_end(), standout_start(), and TRUE.
Referenced by dialog_inputbox(), indicate_error(), P_SpawnLightFlash(), P_SpawnStrobeFlash(), P_UnArchiveSpecials(), T_LightFlash(), and T_StrobeFlash().
format_edit_status()
static int format_edit_status (void) static
Definition at line 1255 of file vi.c.
 {
     static const char cmd_mode_indicator[] ALIGN1 = "-IR-";
 #define tot format_edit_status__tot
     int cur, percent, ret, trunc_at;
     // modified_count is now a counter rather than a flag.  this
     // helps reduce the amount of line counting we need to do.
     // (this will cause a mis-reporting of modified status
     // once every MAXINT editing operations.)
     // it would be nice to do a similar optimization here -- if
     // we haven't done a motion that could have changed which line
     // we're on, then we shouldn't have to do this count_lines()
     cur = count_lines(text, dot);
     // count_lines() is expensive.
     // Call it only if something was changed since last time
     // we were here:
     if (modified_count != last_modified_count) {
         tot = cur + count_lines(dot, end - 1) - 1;
         last_modified_count = modified_count;
     }
     //    current line         percent
     //   -------------    ~~ ----------
     //    total lines            100
     if (tot > 0) {
         percent = (100 * cur) / tot;
     } else {
         cur = tot = 0;
         percent = 100;
     }
     trunc_at = columns < STATUS_BUFFER_LEN-1 ?
         columns : STATUS_BUFFER_LEN-1;
     ret = snprintf(status_buffer, trunc_at+1,
 #if ENABLE_FEATURE_VI_READONLY
         "%c %s%s%s %d/%d %d%%",
 #else
         "%c %s%s %d/%d %d%%",
 #endif
         cmd_mode_indicator[cmd_mode & 3],
         (current_filename != NULL ? current_filename : "No file"),
 #if ENABLE_FEATURE_VI_READONLY
         (readonly_mode ? " [Readonly]" : ""),
 #endif
         (modified_count ? " [Modified]" : ""),
         cur, tot, percent);
     if (ret >= 0 && ret < trunc_at)
         return ret;  // it all fit
     return trunc_at;  // had to truncate
 #undef tot
 }
References ALIGN1, cmd_mode, columns, count_lines(), cur, current_filename, dot, end, last_modified_count, modified_count, NULL, percent, readonly_mode, snprintf(), status_buffer, STATUS_BUFFER_LEN, text, and tot.
Referenced by show_status_line().
format_line()
static char* format_line (char * src) static
Definition at line 931 of file vi.c.
 {
     unsigned char c;
     int co;
     int ofs = offset;
     char *dest = scr_out_buf; // [MAX_SCR_COLS + MAX_TABSTOP * 2]
     c = '~'; // char in col 0 in non-existent lines is '~'
     co = 0;
     while (co < columns + tabstop) {
         // have we gone past the end?
         if (src < end) {
             c = *src++;
             if (c == '\n')
                 break;
             if ((c & 0x80) && !Isprint(c)) {
                 c = '.';
             }
             if (c < ' ' || c == 0x7f) {
                 if (c == '\t') {
                     c = ' ';
                     //      co %    8     !=     7
                     while ((co % tabstop) != (tabstop - 1)) {
                         dest[co++] = c;
                     }
                 } else {
                     dest[co++] = '^';
                     if (c == 0x7f)
                         c = '?';
                     else
                         c += '@'; // Ctrl-X -> 'X'
                 }
             }
         }
         dest[co++] = c;
         // discard scrolled-off-to-the-left portion,
         // in tabstop-sized pieces
         if (ofs >= tabstop && co >= tabstop) {
             memmove(dest, dest + tabstop, co);
             co -= tabstop;
             ofs -= tabstop;
         }
         if (src >= end)
             break;
     }
     // check "short line, gigantic offset" case
     if (co < ofs)
         ofs = co;
     // discard last scrolled off part
     co -= ofs;
     dest += ofs;
     // fill the rest with spaces
     if (co < columns)
         memset(&dest[co], ' ', columns - co);
     return dest;
 }
References c, columns, end, Isprint, memmove(), memset(), offset, scr_out_buf, src, and tabstop.
Referenced by refresh().
get_column()
static int get_column (char * p) static
Definition at line 803 of file vi.c.
 {
     const char *r;
     int co = 0;
     for (r = begin_line(p); r < p; r++)
         co = next_column(*r, co);
     return co;
 }
References begin_line(), next_column(), and p.
Referenced by char_insert(), and do_cmd().
get_input_line()
static char* get_input_line (const char * prompt) static
Definition at line 1204 of file vi.c.
 {
     // char [MAX_INPUT_LEN]
 #define buf get_input_line__buf
     int c;
     int i;
     strcpy(buf, prompt);
     last_status_cksum = 0;  // force status update
     go_bottom_and_clear_to_eol();
     write1(buf);      // write out the :, /, or ? prompt
     i = strlen(buf);
     while (i < MAX_INPUT_LEN - 1) {
         c = get_one_char();
         if (c == '\n' || c == '\r' || c == 27)
             break;      // this is end of input
         if (isbackspace(c)) {
             // user wants to erase prev char
             buf[--i] = '\0';
             go_bottom_and_clear_to_eol();
             if (i <= 0) // user backs up before b-o-l, exit
                 break;
             write1(buf);
         } else if (c > 0 && c < 256) { // exclude Unicode
             // (TODO: need to handle Unicode)
             buf[i] = c;
             buf[++i] = '\0';
             bb_putchar(c);
         }
     }
     refresh(FALSE);
     return buf;
 #undef buf
 }
References bb_putchar(), buf, c, FALSE, get_one_char, go_bottom_and_clear_to_eol(), i, isbackspace, last_status_cksum, MAX_INPUT_LEN, prompt, refresh(), strcpy(), strlen(), and write1().
Referenced by do_cmd().
get_motion_char()
static int get_motion_char (void) static
Definition at line 1183 of file vi.c.
 {
     int c, cnt;
     c = get_one_char();
     if (isdigit(c)) {
         if (c != '0') {
             // get any non-zero motion count
             for (cnt = 0; isdigit(c); c = get_one_char())
                 cnt = cnt * 10 + (c - '0');
             cmdcnt = (cmdcnt ?: 1) * cnt;
         } else {
             // ensure standalone '0' works
             cmdcnt = 0;
         }
     }
     return c;
 }
References c, cmdcnt, cnt, get_one_char, and isdigit.
Referenced by find_range().
go_bottom_and_clear_to_eol()
static void go_bottom_and_clear_to_eol (void) static
Definition at line 672 of file vi.c.
 {
     place_cursor(rows - 1, 0);
     clear_to_eol();
 }
References clear_to_eol(), place_cursor(), and rows.
Referenced by colon(), edit_file(), get_input_line(), readit(), and show_status_line().
Hit_Return()
static void Hit_Return (void) static
Definition at line 1241 of file vi.c.
 {
     int c;
     standout_start();
     write1("[Hit return to continue]");
     standout_end();
     while ((c = get_one_char()) != '\n' && c != '\r')
         continue;
     redraw(TRUE);       // force redraw all
 }
References c, get_one_char, redraw(), standout_end(), standout_start(), TRUE, and write1().
Referenced by colon(), and show_status_line().
indent_len()
static size_t indent_len (char * p) static
Definition at line 2105 of file vi.c.
 {
     char *r = p;
     while (r < (end - 1) && isblank(*r))
         r++;
     return r - p;
 }
References end, isblank, and p.
Referenced by char_insert(), and do_cmd().
indicate_error()
static void indicate_error (void) static
Definition at line 1107 of file vi.c.
 {
 #if ENABLE_FEATURE_VI_CRASHME
     if (crashme > 0)
         return;
 #endif
     cmd_error = TRUE;
     if (!err_method) {
         write1(ESC_BELL);
     } else {
         flash(10);
     }
 }
References cmd_error, err_method, ESC_BELL, flash(), TRUE, and write1().
Referenced by bound_dot(), do_cmd(), dot_to_char(), and find_range().
init_text_buffer()
static int init_text_buffer (char * fn) static
Definition at line 2307 of file vi.c.
 {
     int rc;
     // allocate/reallocate text buffer
     free(text);
     text_size = 10240;
     screenbegin = dot = end = text = xzalloc(text_size);
     update_filename(fn);
     rc = file_insert(fn, text, 1);
     if (rc < 0) {
         // file doesnt exist. Start empty buf with dummy line
         char_insert(text, '\n', NO_UNDO);
     }
     flush_undo_data();
     modified_count = 0;
     last_modified_count = -1;
 #if ENABLE_FEATURE_VI_YANKMARK
     // init the marks
     memset(mark, 0, sizeof(mark));
 #endif
     return rc;
 }
References char_insert, dot, end, file_insert(), flush_undo_data, free, last_modified_count, mark, memset(), modified_count, rc, screenbegin, text, text_size, update_filename(), and xzalloc().
Referenced by colon(), edit_file(), and vi_main().
move_to_col()
static char* move_to_col (char * p, int l) static
Definition at line 1835 of file vi.c.
 {
     int co;
     p = begin_line(p);
     co = 0;
     do {
         if (*p == '\n') //vda || *p == '\0')
             break;
         co = next_column(*p, co);
     } while (co <= l && p++ < end);
     return p;
 }
References begin_line(), end, l, next_column(), and p.
Referenced by do_cmd().
mysleep()
static int mysleep (int hund) static
Definition at line 616 of file vi.c.
 {
     struct pollfd pfd[1];
     if (hund != 0)
         fflush_all();
     pfd[0].fd = STDIN_FILENO;
     pfd[0].events = POLLIN;
     return safe_poll(pfd, 1, hund*10) > 0;
 }
References fflush_all(), pfd, POLLIN, safe_poll(), and STDIN_FILENO.
Referenced by edit_file(), and flash().
new_screen()
static void new_screen (int ro, int co) static
Definition at line 819 of file vi.c.
 {
     char *s;
     free(screen);
     screensize = ro * co + 8;
     s = screen = xmalloc(screensize);
     // initialize the new screen. assume this will be a empty file.
     screen_erase();
     // non-existent text[] lines start with a tilde (~).
     //screen[(1 * co) + 0] = '~';
     //screen[(2 * co) + 0] = '~';
     //..
     //screen[((ro-2) * co) + 0] = '~';
     ro -= 2;
     while (--ro >= 0) {
         s += co;
         *s = '~';
     }
 }
References free, s, screen, screen_erase(), screensize, and xmalloc.
Referenced by edit_file(), and refresh().
next_column()
static int next_column (char c, int co) static
Definition at line 794 of file vi.c.
 {
     if (c == '\t')
         co = next_tabstop(co);
     else if ((unsigned char)c < ' ' || c == 0x7f)
         co++; // display as ^X, use 2 columns
     return co + 1;
 }
References c, and next_tabstop().
Referenced by get_column(), move_to_col(), and sync_cursor().
next_line()
static char* next_line (char * p) static
Definition at line 730 of file vi.c.
 {
     p = end_line(p);
     if (p < end - 1 && *p == '\n')
         p++;            // step to next line
     return p;
 }
References end, end_line(), and p.
Referenced by add_remove_shell_main(), colon(), cut_file(), do_cmd(), dot_next(), dot_scroll(), end_screen(), find_line(), paste_files_separate(), process_files(), and sync_cursor().
next_tabstop()
static int next_tabstop (int col) static
Definition at line 784 of file vi.c.
 {
     return col + ((tabstop - 1) - (col % tabstop));
 }
References tabstop.
Referenced by char_insert(), and next_column().
not_implemented()
static void not_implemented (const char * s) static
Definition at line 1408 of file vi.c.
 {
     char buf[MAX_INPUT_LEN];
     print_literal(buf, s);
     status_line_bold("'%s' is not implemented", buf);
 }
References buf, MAX_INPUT_LEN, print_literal(), s, and status_line_bold().
Referenced by colon(), and do_cmd().
place_cursor()
static void place_cursor (int row, int col) static
Definition at line 653 of file vi.c.
 {
     char cm1[sizeof(ESC_SET_CURSOR_POS) + sizeof(int)*3 * 2];
     if (row < 0) row = 0;
     if (row >= rows) row = rows - 1;
     if (col < 0) col = 0;
     if (col >= columns) col = columns - 1;
     sprintf(cm1, ESC_SET_CURSOR_POS, row + 1, col + 1);
     write1(cm1);
 }
References columns, ESC_SET_CURSOR_POS, rows, sprintf(), and write1().
Referenced by go_bottom_and_clear_to_eol(), refresh(), and show_status_line().
prev_line()
static char* prev_line (char * p) static
Definition at line 721 of file vi.c.
 {
     p = begin_line(p);  // goto beginning of cur line
     if (p > text && p[-1] == '\n')
         p--;            // step to prev line
     p = begin_line(p);  // goto beginning of prev line
     return p;
 }
References begin_line(), p, and text.
Referenced by char_insert(), do_cmd(), dot_prev(), dot_scroll(), sort_main(), and sync_cursor().
prev_tabstop()
static int prev_tabstop (int col) static
Definition at line 789 of file vi.c.
 {
     return col - ((col % tabstop) ?: tabstop);
 }
References tabstop.
Referenced by char_insert().
print_literal()
static void print_literal (char * buf, const char * s) static
Definition at line 1383 of file vi.c.
 {
     char *d;
     unsigned char c;
     if (!s[0])
         s = "(NULL)";
     d = buf;
     for (; *s; s++) {
         c = *s;
         if ((c & 0x80) && !Isprint(c))
             c = '?';
         if (c < ' ' || c == 0x7f) {
             *d++ = '^';
             c |= '@'; // 0x40
             if (c == 0x7f)
                 c = '?';
         }
         *d++ = c;
         *d = '\0';
         if (d - buf > MAX_INPUT_LEN - 10) // paranoia
             break;
     }
 }
References buf, c, Isprint, MAX_INPUT_LEN, and s.
Referenced by not_implemented().
query_screen_dimensions()
static ALWAYS_INLINE int query_screen_dimensions (void) static
Definition at line 609 of file vi.c.
 {
     return 0;
 }
Referenced by edit_file(), and refresh().
rawmode()
static void rawmode (void) static
Definition at line 629 of file vi.c.
 {
     // no TERMIOS_CLEAR_ISIG: leave ISIG on - allow signals
     set_termios_to_raw(STDIN_FILENO, &term_orig, TERMIOS_RAW_CRNL);
 }
References set_termios_to_raw(), STDIN_FILENO, term_orig, and TERMIOS_RAW_CRNL.
Referenced by colon(), and edit_file().
readit()
static int readit (void) static
Definition at line 1122 of file vi.c.
 {
     int c;
     fflush_all();
     // Wait for input. TIMEOUT = -1 makes read_key wait even
     // on nonblocking stdin.
     // Note: read_key sets errno to 0 on success.
  again:
     c = safe_read_key(STDIN_FILENO, readbuffer, /*timeout:*/ -1);
     if (c == -1) { // EOF/error
         if (errno == EAGAIN) // paranoia
             goto again;
         go_bottom_and_clear_to_eol();
         cookmode(); // terminal to "cooked"
         bb_simple_error_msg_and_die("can't read user input");
     }
     return c;
 }
References bb_simple_error_msg_and_die(), c, cookmode(), EAGAIN, errno, fflush_all(), go_bottom_and_clear_to_eol(), readbuffer, safe_read_key(), and STDIN_FILENO.
redraw()
static void redraw (int full_screen) static
Definition at line 1087 of file vi.c.
 {
     // cursor to top,left; clear to the end of screen
     write1(ESC_SET_CURSOR_TOPLEFT ESC_CLEAR2EOS);
     screen_erase();     // erase the internal screen buffer
     last_status_cksum = 0;  // force status update
     refresh(full_screen);   // this will redraw the entire display
     show_status_line();
 }
References ESC_CLEAR2EOS, ESC_SET_CURSOR_TOPLEFT, last_status_cksum, refresh(), screen_erase(), show_status_line(), and write1().
Referenced by do_cmd(), edit_file(), flash(), and Hit_Return().
refresh()
static void refresh (int full_screen) static
Definition at line 993 of file vi.c.
 {
 #define old_offset refresh__old_offset
     int li, changed;
     char *tp, *sp;      // pointer into text[] and screen[]
     if (ENABLE_FEATURE_VI_WIN_RESIZE IF_FEATURE_VI_ASK_TERMINAL(&& !G.get_rowcol_error) ) {
         unsigned c = columns, r = rows;
         query_screen_dimensions();
 #if ENABLE_FEATURE_VI_USE_SIGNALS
         full_screen |= (c - columns) | (r - rows);
 #else
         if (c != columns || r != rows) {
             full_screen = TRUE;
             // update screen memory since SIGWINCH won't have done it
             new_screen(rows, columns);
         }
 #endif
     }
     sync_cursor(dot, &crow, &ccol); // where cursor will be (on "dot")
     tp = screenbegin;   // index into text[] of top line
     // compare text[] to screen[] and mark screen[] lines that need updating
     for (li = 0; li < rows - 1; li++) {
         int cs, ce;             // column start & end
         char *out_buf;
         // format current text line
         out_buf = format_line(tp /*, li*/);
         // skip to the end of the current text[] line
         if (tp < end) {
             char *t = memchr(tp, '\n', end - tp);
             if (!t) t = end - 1;
             tp = t + 1;
         }
         // see if there are any changes between virtual screen and out_buf
         changed = FALSE;    // assume no change
         cs = 0;
         ce = columns - 1;
         sp = &screen[li * columns]; // start of screen line
         if (full_screen) {
             // force re-draw of every single column from 0 - columns-1
             goto re0;
         }
         // compare newly formatted buffer with virtual screen
         // look forward for first difference between buf and screen
         for (; cs <= ce; cs++) {
             if (out_buf[cs] != sp[cs]) {
                 changed = TRUE; // mark for redraw
                 break;
             }
         }
         // look backward for last difference between out_buf and screen
         for (; ce >= cs; ce--) {
             if (out_buf[ce] != sp[ce]) {
                 changed = TRUE; // mark for redraw
                 break;
             }
         }
         // now, cs is index of first diff, and ce is index of last diff
         // if horz offset has changed, force a redraw
         if (offset != old_offset) {
  re0:
             changed = TRUE;
         }
         // make a sanity check of columns indexes
         if (cs < 0) cs = 0;
         if (ce > columns - 1) ce = columns - 1;
         if (cs > ce) { cs = 0; ce = columns - 1; }
         // is there a change between virtual screen and out_buf
         if (changed) {
             // copy changed part of buffer to virtual screen
             memcpy(sp+cs, out_buf+cs, ce-cs+1);
             place_cursor(li, cs);
             // write line out to terminal
             fwrite(&sp[cs], ce - cs + 1, 1, stdout);
         }
     }
     place_cursor(crow, ccol);
     if (!keep_index)
         cindex = ccol + offset;
     old_offset = offset;
 #undef old_offset
 }
References c, ccol, changed, cindex, columns, crow, dot, end, FALSE, format_line(), fwrite(), G, keep_index, memchr(), memcpy(), new_screen(), offset, old_offset, place_cursor(), query_screen_dimensions(), rows, screen, screenbegin, sp, stdout, sync_cursor(), t, tp, and TRUE.
Referenced by char_insert(), edit_file(), get_input_line(), main(), redraw(), ST_Drawer(), ST_drawWidgets(), STlib_updateBinIcon(), STlib_updateMultIcon(), STlib_updateNum(), and STlib_updatePercent().
screen_erase()
static void screen_erase (void) static
Definition at line 814 of file vi.c.
 {
     memset(screen, ' ', screensize);    // clear new screen
 }
References memset(), screen, and screensize.
Referenced by new_screen(), and redraw().
show_help()
static void show_help (void) static
Definition at line 560 of file vi.c.
 {
     puts("These features are available:"
 #if ENABLE_FEATURE_VI_SEARCH
     "\n\tPattern searches with / and ?"
 #endif
 #if ENABLE_FEATURE_VI_DOT_CMD
     "\n\tLast command repeat with ."
 #endif
 #if ENABLE_FEATURE_VI_YANKMARK
     "\n\tLine marking with 'x"
     "\n\tNamed buffers with \"x"
 #endif
 #if ENABLE_FEATURE_VI_READONLY
     //not implemented: "\n\tReadonly if vi is called as \"view\""
     //redundant: usage text says this too: "\n\tReadonly with -R command line arg"
 #endif
 #if ENABLE_FEATURE_VI_SET
     "\n\tSome colon mode commands with :"
 #endif
 #if ENABLE_FEATURE_VI_SETOPTS
     "\n\tSettable options with \":set\""
 #endif
 #if ENABLE_FEATURE_VI_USE_SIGNALS
     "\n\tSignal catching- ^C"
     "\n\tJob suspend and resume with ^Z"
 #endif
 #if ENABLE_FEATURE_VI_WIN_RESIZE
     "\n\tAdapt to window re-sizes"
 #endif
     );
 }
References puts().
Referenced by colon(), and vi_main().
show_status_line()
static void show_status_line (void) static
Definition at line 1324 of file vi.c.
 {
     int cnt = 0, cksum = 0;
     // either we already have an error or status message, or we
     // create one.
     if (!have_status_msg) {
         cnt = format_edit_status();
         cksum = bufsum(status_buffer, cnt);
     }
     if (have_status_msg || ((cnt > 0 && last_status_cksum != cksum))) {
         last_status_cksum = cksum;      // remember if we have seen this line
         go_bottom_and_clear_to_eol();
         write1(status_buffer);
         if (have_status_msg) {
             if (((int)strlen(status_buffer) - (have_status_msg - 1)) >
                     (columns - 1) ) {
                 have_status_msg = 0;
                 Hit_Return();
             }
             have_status_msg = 0;
         }
         place_cursor(crow, ccol);  // put cursor back in correct place
     }
     fflush_all();
 }
References bufsum(), ccol, cnt, columns, crow, fflush_all(), format_edit_status(), go_bottom_and_clear_to_eol(), have_status_msg, Hit_Return(), last_status_cksum, place_cursor(), status_buffer, strlen(), and write1().
Referenced by do_cmd(), edit_file(), and redraw().
skip_thing()
static char* skip_thing (char * p, int linecnt, int dir, int type) static
Definition at line 3491 of file vi.c.
 {
     char c;
     while (st_test(p, type, dir, &c)) {
         // make sure we limit search to correct number of lines
         if (c == '\n' && --linecnt < 1)
             break;
         if (dir >= 0 && p >= end - 1)
             break;
         if (dir < 0 && p <= text)
             break;
         p += dir;       // move to next char
     }
     return p;
 }
References c, dir, end, p, st_test(), text, and type.
Referenced by do_cmd().
st_test()
static int st_test (char * p, int type, int dir, char * tested) static
Definition at line 3457 of file vi.c.
 {
     char c, c0, ci;
     int test, inc;
     inc = dir;
     c = c0 = p[0];
     ci = p[inc];
     test = 0;
     if (type == S_BEFORE_WS) {
         c = ci;
         test = (!isspace(c) || c == '\n');
     }
     if (type == S_TO_WS) {
         c = c0;
         test = (!isspace(c) || c == '\n');
     }
     if (type == S_OVER_WS) {
         c = c0;
         test = isspace(c);
     }
     if (type == S_END_PUNCT) {
         c = ci;
         test = ispunct(c);
     }
     if (type == S_END_ALNUM) {
         c = ci;
         test = (isalnum(c) || c == '_');
     }
     *tested = c;
     return test;
 }
References c, dir, isalnum, ispunct, isspace, p, S_BEFORE_WS, S_END_ALNUM, S_END_PUNCT, S_OVER_WS, S_TO_WS, test, and type.
Referenced by skip_thing().
standout_end()
static void standout_end (void) static
Definition at line 685 of file vi.c.
 {
     write1(ESC_NORM_TEXT);
 }
References ESC_NORM_TEXT, and write1().
Referenced by colon(), flash(), and Hit_Return().
standout_start()
static void standout_start (void) static
Definition at line 679 of file vi.c.
 {
     write1(ESC_BOLD_TEXT);
 }
References ESC_BOLD_TEXT, and write1().
Referenced by colon(), flash(), and Hit_Return().
status_line()
static void status_line (const char * format, ...) static
Definition at line 1352 of file vi.c.
 {
     va_list args;
     va_start(args, format);
     vsnprintf(status_buffer, STATUS_BUFFER_LEN, format, args);
     va_end(args);
     have_status_msg = 1;
 }
References args, format(), have_status_msg, status_buffer, STATUS_BUFFER_LEN, va_end, va_start, and vsnprintf().
Referenced by colon(), and index_status_file().
status_line_bold()
static void status_line_bold (const char * format, ...) static
Definition at line 1362 of file vi.c.
 {
     va_list args;
     va_start(args, format);
     strcpy(status_buffer, ESC_BOLD_TEXT);
     vsnprintf(status_buffer + (sizeof(ESC_BOLD_TEXT)-1),
         STATUS_BUFFER_LEN - sizeof(ESC_BOLD_TEXT) - sizeof(ESC_NORM_TEXT),
         format, args
     );
     strcat(status_buffer, ESC_NORM_TEXT);
     va_end(args);
     have_status_msg = 1 + (sizeof(ESC_BOLD_TEXT)-1) + (sizeof(ESC_NORM_TEXT)-1);
 }
References args, ESC_BOLD_TEXT, ESC_NORM_TEXT, format(), have_status_msg, status_buffer, STATUS_BUFFER_LEN, strcat(), strcpy(), va_end, va_start, and vsnprintf().
Referenced by colon(), do_cmd(), file_insert(), file_write(), not_implemented(), status_line_bold_errno(), and vi_main().
status_line_bold_errno()
static void status_line_bold_errno (const char * fn) static
Definition at line 1377 of file vi.c.
 {
     status_line_bold("'%s' "STRERROR_FMT, fn STRERROR_ERRNO);
 }
References status_line_bold(), STRERROR_ERRNO, and STRERROR_FMT.
Referenced by colon(), and file_insert().
stupid_insert()
static uintptr_t stupid_insert (char * p, char c) static
Definition at line 2095 of file vi.c.
 {
     uintptr_t bias;
     bias = text_hole_make(p, 1);
     p += bias;
     *p = c;
     return bias;
 }
References c, p, and text_hole_make().
Referenced by char_insert().
sync_cursor()
static void sync_cursor (char * d, int * row, int * col) static
Definition at line 841 of file vi.c.
 {
     char *beg_cur;  // begin and end of "d" line
     char *tp;
     int cnt, ro, co;
     beg_cur = begin_line(d);    // first char of cur line
     if (beg_cur < screenbegin) {
         // "d" is before top line on screen
         // how many lines do we have to move
         cnt = count_lines(beg_cur, screenbegin);
  sc1:
         screenbegin = beg_cur;
         if (cnt > (rows - 1) / 2) {
             // we moved too many lines. put "dot" in middle of screen
             for (cnt = 0; cnt < (rows - 1) / 2; cnt++) {
                 screenbegin = prev_line(screenbegin);
             }
         }
     } else {
         char *end_scr;  // begin and end of screen
         end_scr = end_screen(); // last char of screen
         if (beg_cur > end_scr) {
             // "d" is after bottom line on screen
             // how many lines do we have to move
             cnt = count_lines(end_scr, beg_cur);
             if (cnt > (rows - 1) / 2)
                 goto sc1;   // too many lines
             for (ro = 0; ro < cnt - 1; ro++) {
                 // move screen begin the same amount
                 screenbegin = next_line(screenbegin);
                 // now, move the end of screen
                 end_scr = next_line(end_scr);
                 end_scr = end_line(end_scr);
             }
         }
     }
     // "d" is on screen- find out which row
     tp = screenbegin;
     for (ro = 0; ro < rows - 1; ro++) { // drive "ro" to correct row
         if (tp == beg_cur)
             break;
         tp = next_line(tp);
     }
     // find out what col "d" is on
     co = 0;
     do { // drive "co" to correct column
         if (*tp == '\n') //vda || *tp == '\0')
             break;
         co = next_column(*tp, co) - 1;
         // inserting text before a tab, don't include its position
         if (cmd_mode && tp == d - 1 && *d == '\t') {
             co++;
             break;
         }
     } while (tp++ < d && ++co);
     // "co" is the column where "dot" is.
     // The screen has "columns" columns.
     // The currently displayed columns are  0+offset -- columns+ofset
     // |-------------------------------------------------------------|
     //               ^ ^                                ^
     //        offset | |------- columns ----------------|
     //
     // If "co" is already in this range then we do not have to adjust offset
     //      but, we do have to subtract the "offset" bias from "co".
     // If "co" is outside this range then we have to change "offset".
     // If the first char of a line is a tab the cursor will try to stay
     //  in column 7, but we have to set offset to 0.
     if (co < 0 + offset) {
         offset = co;
     }
     if (co >= columns + offset) {
         offset = co - columns + 1;
     }
     // if the first char of the line is a tab, and "dot" is sitting on it
     //  force offset to 0.
     if (d == beg_cur && *d == '\t') {
         offset = 0;
     }
     co -= offset;
     *row = ro;
     *col = co;
 }
References begin_line(), cmd_mode, cnt, columns, count_lines(), end_line(), end_screen(), next_column(), next_line(), offset, prev_line(), rows, screenbegin, and tp.
Referenced by refresh().
text_hole_delete()
static char* text_hole_delete (char * p, char * q, int undo) static
Definition at line 1532 of file vi.c.
 {
     char *src, *dest;
     int cnt, hole_size;
     // move forwards, from beginning
     // assume p <= q
     src = q + 1;
     dest = p;
     if (q < p) {        // they are backward- swap them
         src = p + 1;
         dest = q;
     }
     hole_size = q - p + 1;
     cnt = end - src;
 #if ENABLE_FEATURE_VI_UNDO
     switch (undo) {
         case NO_UNDO:
             break;
         case ALLOW_UNDO:
             undo_push(p, hole_size, UNDO_DEL);
             break;
         case ALLOW_UNDO_CHAIN:
             undo_push(p, hole_size, UNDO_DEL_CHAIN);
             break;
 # if ENABLE_FEATURE_VI_UNDO_QUEUE
         case ALLOW_UNDO_QUEUED:
             undo_push(p, hole_size, UNDO_DEL_QUEUED);
             break;
 # endif
     }
     modified_count--;
 #endif
     if (src < text || src > end)
         goto thd0;
     if (dest < text || dest >= end)
         goto thd0;
     modified_count++;
     if (src >= end)
         goto thd_atend; // just delete the end of the buffer
     memmove(dest, src, cnt);
  thd_atend:
     end = end - hole_size;  // adjust the new END
     if (dest >= end)
         dest = end - 1; // make sure dest in below end-1
     if (end <= text)
         dest = end = text;  // keep pointers valid
  thd0:
     return dest;
 }
References cnt, end, memmove(), modified_count, p, src, text, and undo().
text_hole_make()
static uintptr_t text_hole_make (char * p, int size) static
Definition at line 1496 of file vi.c.
 {
     uintptr_t bias = 0;
     if (size <= 0)
         return bias;
     end += size;        // adjust the new END
     if (end >= (text + text_size)) {
         char *new_text;
         text_size += end - (text + text_size) + 10240;
         new_text = xrealloc(text, text_size);
         bias = (new_text - text);
         screenbegin += bias;
         dot         += bias;
         end         += bias;
         p           += bias;
 #if ENABLE_FEATURE_VI_YANKMARK
         {
             int i;
             for (i = 0; i < ARRAY_SIZE(mark); i++)
                 if (mark[i])
                     mark[i] += bias;
         }
 #endif
         text = new_text;
     }
     memmove(p + size, p, end - size - p);
     memset(p, ' ', size);   // clear new hole
     return bias;
 }
References ARRAY_SIZE, dot, end, i, mark, memmove(), memset(), p, screenbegin, size, text, text_size, and xrealloc.
Referenced by char_insert(), file_insert(), and stupid_insert().
update_filename()
static void update_filename (char * fn) static
Definition at line 2286 of file vi.c.
 {
 #if ENABLE_FEATURE_VI_COLON_EXPAND
     if (fn == NULL)
         return;
     if (current_filename == NULL || strcmp(fn, current_filename) != 0) {
         free(alt_filename);
         alt_filename = current_filename;
         current_filename = xstrdup(fn);
     }
 #else
     if (fn != current_filename) {
         free(current_filename);
         current_filename = xstrdup(fn);
     }
 #endif
 }
References alt_filename, current_filename, free, NULL, strcmp, and xstrdup().
Referenced by colon(), and init_text_buffer().
vi_main()
int vi_main (int argc, char ** argv)
Definition at line 4955 of file vi.c.
 {
     int opts;
     INIT_G();
 #if ENABLE_FEATURE_VI_UNDO
     //undo_stack_tail = NULL; - already is
 # if ENABLE_FEATURE_VI_UNDO_QUEUE
     undo_queue_state = UNDO_EMPTY;
     //undo_q = 0; - already is
 # endif
 #endif
 #if ENABLE_FEATURE_VI_CRASHME
     srand((long) getpid());
 #endif
 #ifdef NO_SUCH_APPLET_YET
     // if we aren't "vi", we are "view"
     if (ENABLE_FEATURE_VI_READONLY && applet_name[2]) {
         SET_READONLY_MODE(readonly_mode);
     }
 #endif
     // 0: all of our options are disabled by default in vim
     //vi_setops = 0;
     opts = getopt32(argv, VI_OPTSTR IF_FEATURE_VI_COLON(, &initial_cmds));
 #if ENABLE_FEATURE_VI_CRASHME
     if (opts & OPT_C)
         crashme = 1;
 #endif
     if (opts & OPT_R)
         SET_READONLY_MODE(readonly_mode);
     if (opts & OPT_H)
         show_help();
     if (opts & (OPT_H | OPT_h)) {
         bb_show_usage();
         return 1;
     }
     argv += optind;
     cmdline_filecnt = argc - optind;
     //  1-  process EXINIT variable from environment
     //  2-  if EXINIT is unset process $HOME/.exrc file
     //  3-  process command line args
 #if ENABLE_FEATURE_VI_COLON
     {
         const char *exinit = getenv("EXINIT");
         char *cmds = NULL;
         if (exinit) {
             cmds = xstrdup(exinit);
         } else {
             const char *home = getenv("HOME");
             if (home && *home) {
                 char *exrc = concat_path_file(home, ".exrc");
                 struct stat st;
                 // .exrc must belong to and only be writable by user
                 if (stat(exrc, &st) == 0) {
                     if ((st.st_mode & (S_IWGRP|S_IWOTH)) == 0
                      && st.st_uid == getuid()
                     ) {
                         cmds = xmalloc_open_read_close(exrc, NULL);
                     } else {
                         status_line_bold(".exrc: permission denied");
                     }
                 }
                 free(exrc);
             }
         }
         if (cmds) {
             init_text_buffer(NULL);
             run_cmds(cmds);
             free(cmds);
         }
     }
 #endif
     // "Save cursor, use alternate screen buffer, clear screen"
     write1(ESC"[?1049h");
     // This is the main file handling loop
     optind = 0;
     while (1) {
         edit_file(argv[optind]); // might be NULL on 1st iteration
         // NB: optind can be changed by ":next" and ":rewind" commands
         optind++;
         if (optind >= cmdline_filecnt)
             break;
     }
     // "Use normal screen buffer, restore cursor"
     write1(ESC"[?1049l");
     return 0;
 }
References applet_name, argc, argv, bb_show_usage(), cmdline_filecnt, concat_path_file(), edit_file(), ESC, free, getenv, getopt32(), getpid(), getuid, INIT_G, init_text_buffer(), initial_cmds, NULL, OPT_C, OPT_H, OPT_h, OPT_R, optind, readonly_mode, S_IWGRP, S_IWOTH, SET_READONLY_MODE, show_help(), srand(), stat(), status_line_bold(), VI_OPTSTR, write1(), xmalloc_open_read_close(), and xstrdup().
write1()
static void write1 (const char * out) static
Definition at line 593 of file vi.c.
 {
     fputs_stdout(out);
 }
References fputs_stdout(), and out().
Referenced by clear_to_eol(), colon(), edit_file(), get_input_line(), Hit_Return(), indicate_error(), place_cursor(), redraw(), show_status_line(), standout_end(), standout_start(), and vi_main().
yank_delete()
static char* yank_delete (char * start, char * stop, int buftype, int yf, int undo) static
Definition at line 1958 of file vi.c.
 {
     char *p;
     // make sure start <= stop
     if (start > stop) {
         // they are backwards, reverse them
         p = start;
         start = stop;
         stop = p;
     }
     if (buftype == PARTIAL && *start == '\n')
         return start;
     p = start;
 #if ENABLE_FEATURE_VI_YANKMARK
     text_yank(start, stop, YDreg, buftype);
 #endif
     if (yf == YANKDEL) {
         p = text_hole_delete(start, stop, undo);
     }                   // delete lines
     return p;
 }
References p, PARTIAL, start, stop, text_hole_delete, undo(), YANKDEL, and YDreg.