Fennix Userspace: Userspace/apps/base/bash/lib/readline/misc.c File Reference
misc.c File Reference
#include "ansi_stdlib.h"
#include <stdio.h>
#include "rldefs.h"
#include "rlmbutil.h"
#include "readline.h"
#include "history.h"
#include "rlprivate.h"
#include "histlib.h"
#include "rlshell.h"
#include "xmalloc.h"
Macros
#define READLINE_LIBRARY
#define HISTORY_FULL() (history_is_stifled () && history_length >= history_max_entries)
Functions
static int rl_digit_loop (void)
static void _rl_history_set_point (void)
int _rl_arg_overflow (void)
void _rl_arg_init (void)
int _rl_arg_getchar (void)
int _rl_arg_dispatch (_rl_arg_cxt cxt, int c)
void _rl_reset_argument (void)
int rl_digit_argument (int ignore, int key)
int rl_universal_argument (int count, int key)
int _rl_arg_callback (_rl_arg_cxt cxt)
int rl_discard_argument (void)
void _rl_start_using_history (void)
void _rl_free_history_entry (HIST_ENTRY *entry)
int rl_maybe_replace_line (void)
int rl_maybe_unsave_line (void)
int rl_maybe_save_line (void)
int _rl_free_saved_history_line (void)
void rl_replace_from_history (HIST_ENTRY *entry, int flags)
void _rl_revert_previous_lines (void)
void _rl_revert_all_lines (void)
void rl_clear_history (void)
int rl_beginning_of_history (int count, int key)
int rl_end_of_history (int count, int key)
int rl_get_next_history (int count, int key)
int rl_get_previous_history (int count, int key)
int rl_fetch_history (int count, int c)
static int set_saved_history ()
int rl_operate_and_get_next (int count, int c)
int rl_vi_editing_mode (int count, int key)
int rl_emacs_editing_mode (int count, int key)
void _rl_set_insert_mode (int im, int force)
int rl_overwrite_mode (int count, int key)
Variables
int _rl_history_preserve_point = 0
_rl_arg_cxt _rl_argcxt
int _rl_history_saved_point = -1
HIST_ENTRY * _rl_saved_line_for_history = (HIST_ENTRY *)NULL
static rl_hook_func_t * _rl_saved_internal_startup_hook = 0
static int saved_history_logical_offset = -1
Macro Definition Documentation
HISTORY_FULL
#define HISTORY_FULL () (history_is_stifled () && history_length >= history_max_entries)
Definition at line 693 of file misc.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file misc.c.
Function Documentation
_rl_arg_callback()
int _rl_arg_callback (_rl_arg_cxt cxt)
Definition at line 255 of file misc.c.
 {
   int c, r;
   c = _rl_arg_getchar ();
   if (c < 0)
     return (1);     /* EOF */
   if (_rl_argcxt & NUM_READONE)
     {
       _rl_argcxt &= ~NUM_READONE;
       rl_restore_prompt ();
       rl_clear_message ();
       RL_UNSETSTATE(RL_STATE_NUMERICARG);
       rl_execute_next (c);
       return 0;
     }
   r = _rl_arg_dispatch (cxt, c);
   if (r > 0)
     rl_message ("(arg: %d) ", rl_arg_sign * rl_numeric_arg);
   return (r != 1);
 }
References _rl_arg_dispatch(), _rl_arg_getchar(), _rl_argcxt, c, NUM_READONE, rl_arg_sign, rl_clear_message(), rl_execute_next(), rl_message(), rl_numeric_arg, rl_restore_prompt(), RL_STATE_NUMERICARG, and RL_UNSETSTATE.
Referenced by rl_callback_read_char().
_rl_arg_dispatch()
int _rl_arg_dispatch (_rl_arg_cxt cxt, int c)
Definition at line 117 of file misc.c.
 {
   int key, r;
   key = c;
   /* If we see a key bound to `universal-argument' after seeing digits,
       it ends the argument but is otherwise ignored. */
   if (c >= 0 && _rl_keymap[c].type == ISFUNC && _rl_keymap[c].function == rl_universal_argument)
     {
       if ((cxt & NUM_SAWDIGITS) == 0)
     {
       rl_numeric_arg *= 4;
       return 1;
     }
       else if (RL_ISSTATE (RL_STATE_CALLBACK))
         {
           _rl_argcxt |= NUM_READONE;
           return 0; /* XXX */
         }
       else
     {
       key = _rl_bracketed_read_key ();
       rl_restore_prompt ();
       rl_clear_message ();
       RL_UNSETSTATE(RL_STATE_NUMERICARG);
       if (key < 0)
         return -1;
       return (_rl_dispatch (key, _rl_keymap));
     }
     }
   c = UNMETA (c);
   if (_rl_digit_p (c))
     {
       r = _rl_digit_value (c);
       rl_numeric_arg = rl_explicit_arg ? (rl_numeric_arg * 10) +  r : r;
       rl_explicit_arg = 1;
       _rl_argcxt |= NUM_SAWDIGITS;
     }
   else if (c == '-' && rl_explicit_arg == 0)
     {
       rl_numeric_arg = 1;
       _rl_argcxt |= NUM_SAWMINUS;
       rl_arg_sign = -1;
     }
   else
     {
       /* Make M-- command equivalent to M--1 command. */
       if ((_rl_argcxt & NUM_SAWMINUS) && rl_numeric_arg == 1 && rl_explicit_arg == 0)
     rl_explicit_arg = 1;
       rl_restore_prompt ();
       rl_clear_message ();
       RL_UNSETSTATE(RL_STATE_NUMERICARG);
       r = _rl_dispatch (key, _rl_keymap);
       if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       /* At worst, this will cause an extra redisplay.  Otherwise,
          we have to wait until the next character comes in. */
       if (rl_done == 0)
         (*rl_redisplay_function) ();
       r = 0;
     }
       return r;
     }
   return 1;
 }
References _rl_argcxt, _rl_bracketed_read_key(), _rl_digit_p(), _rl_digit_value(), _rl_dispatch(), _rl_keymap, c, ISFUNC, NUM_READONE, NUM_SAWDIGITS, NUM_SAWMINUS, rl_arg_sign, rl_clear_message(), rl_done, rl_explicit_arg, RL_ISSTATE, rl_numeric_arg, rl_restore_prompt(), RL_STATE_CALLBACK, RL_STATE_NUMERICARG, rl_universal_argument(), RL_UNSETSTATE, type, and UNMETA.
Referenced by _rl_arg_callback(), rl_digit_argument(), and rl_digit_loop().
_rl_arg_getchar()
int _rl_arg_getchar (void)
Definition at line 101 of file misc.c.
 {
   int c;
   rl_message ("(arg: %d) ", rl_arg_sign * rl_numeric_arg);
   RL_SETSTATE(RL_STATE_MOREINPUT);
   c = rl_read_key ();
   RL_UNSETSTATE(RL_STATE_MOREINPUT);
   return c;
 }
References c, rl_arg_sign, rl_message(), rl_numeric_arg, rl_read_key(), RL_SETSTATE, RL_STATE_MOREINPUT, and RL_UNSETSTATE.
Referenced by _rl_arg_callback(), rl_digit_loop(), and rl_digit_loop1().
_rl_arg_init()
void _rl_arg_init (void)
Definition at line 93 of file misc.c.
 {
   rl_save_prompt ();
   _rl_argcxt = 0;
   RL_SETSTATE(RL_STATE_NUMERICARG);
 }
References _rl_argcxt, rl_save_prompt(), RL_SETSTATE, and RL_STATE_NUMERICARG.
Referenced by rl_digit_argument(), and rl_universal_argument().
_rl_arg_overflow()
int _rl_arg_overflow (void)
Definition at line 77 of file misc.c.
 {
   if (rl_numeric_arg > 1000000)
     {
       _rl_argcxt = 0;
       rl_explicit_arg = rl_numeric_arg = 0;
       rl_ding ();
       rl_restore_prompt ();
       rl_clear_message ();
       RL_UNSETSTATE(RL_STATE_NUMERICARG);
       return 1;
     }
   return 0;
 }
References _rl_argcxt, rl_clear_message(), rl_ding(), rl_explicit_arg, rl_numeric_arg, rl_restore_prompt(), RL_STATE_NUMERICARG, and RL_UNSETSTATE.
Referenced by rl_digit_loop(), and rl_digit_loop1().
_rl_free_history_entry()
void _rl_free_history_entry (HIST_ENTRY * entry)
Definition at line 317 of file misc.c.
 {
   if (entry == 0)
     return;
   FREE (entry->line);
   FREE (entry->timestamp);
   xfree (entry);
 }
References FREE, and xfree.
Referenced by _rl_free_saved_history_line(), make_history_line_current(), readline_internal_teardown(), rl_clear_history(), and rl_maybe_unsave_line().
_rl_free_saved_history_line()
int _rl_free_saved_history_line (void)
Definition at line 383 of file misc.c.
 {
   UNDO_LIST *orig;
   if (_rl_saved_line_for_history)
     {
       if (rl_undo_list && rl_undo_list == (UNDO_LIST *)_rl_saved_line_for_history->data)
     rl_undo_list = 0;
       /* Have to free this separately because _rl_free_history entry can't:
      it doesn't know whether or not this has application data. Only the
      callers that know this is _rl_saved_line_for_history can know that
      it's an undo list. */
       if (_rl_saved_line_for_history->data)
     _rl_free_undo_list ((UNDO_LIST *)_rl_saved_line_for_history->data);
       _rl_free_history_entry (_rl_saved_line_for_history);
       _rl_saved_line_for_history = (HIST_ENTRY *)NULL;
     }
   return 0;
 }
References _rl_free_history_entry(), _rl_free_undo_list(), _rl_saved_line_for_history, _hist_entry::data, NULL, and rl_undo_list.
Referenced by _rl_start_using_history(), rl_get_previous_history(), rl_history_search_reinit(), and rl_vi_search().
_rl_history_set_point()
static void _rl_history_set_point (void) static
Definition at line 404 of file misc.c.
 {
   rl_point = (_rl_history_preserve_point && _rl_history_saved_point != -1)
         ? _rl_history_saved_point
         : rl_end;
   if (rl_point > rl_end)
     rl_point = rl_end;
 #if defined (VI_MODE)
   if (rl_editing_mode == vi_mode && _rl_keymap != vi_insertion_keymap)
     rl_point = 0;
 #endif /* VI_MODE */
   if (rl_editing_mode == emacs_mode)
     rl_mark = (rl_point == rl_end ? 0 : rl_end);
 }
References _rl_history_preserve_point, _rl_history_saved_point, _rl_keymap, emacs_mode, rl_editing_mode, rl_end, rl_mark, rl_point, vi_insertion_keymap, and vi_mode.
Referenced by rl_get_next_history(), and rl_get_previous_history().
_rl_reset_argument()
void _rl_reset_argument (void)
Definition at line 217 of file misc.c.
 {
   rl_numeric_arg = rl_arg_sign = 1;
   rl_explicit_arg = 0;
   _rl_argcxt = 0;
 }
References _rl_argcxt, rl_arg_sign, rl_explicit_arg, and rl_numeric_arg.
Referenced by _rl_abort_internal(), readline_internal_char(), rl_discard_argument(), rl_free_line_state(), and rl_insert().
_rl_revert_all_lines()
void _rl_revert_all_lines (void)
Definition at line 493 of file misc.c.
 {
   int pos;
   pos = where_history ();
   using_history ();
   _rl_revert_previous_lines ();
   history_set_pos (pos);
 }
References _rl_revert_previous_lines(), history_set_pos(), pos, using_history(), and where_history().
Referenced by readline_internal_teardown().
_rl_revert_previous_lines()
void _rl_revert_previous_lines (void)
Definition at line 446 of file misc.c.
 {
   int hpos;
   HIST_ENTRY *entry;
   UNDO_LIST *ul, *saved_undo_list;
   char *lbuf;
   lbuf = savestring (rl_line_buffer);
   saved_undo_list = rl_undo_list;
   hpos = where_history ();
   entry = (hpos == history_length) ? previous_history () : current_history ();
   while (entry)
     {
       if (ul = (UNDO_LIST *)entry->data)
     {
       if (ul == saved_undo_list)
         saved_undo_list = 0;
       /* Set up rl_line_buffer and other variables from history entry */
       rl_replace_from_history (entry, 0);   /* entry->line is now current */
       entry->data = 0;          /* entry->data is now current undo list */
       /* Undo all changes to this history entry */
       while (rl_undo_list)
         rl_do_undo ();
       /* And copy the reverted line back to the history entry, preserving
          the timestamp. */
       FREE (entry->line);
       entry->line = savestring (rl_line_buffer);
     }
       entry = previous_history ();
     }
   /* Restore history state */
   rl_undo_list = saved_undo_list;   /* may have been set to null */
   history_set_pos (hpos);
   /* reset the line buffer */
   rl_replace_line (lbuf, 0);
   _rl_set_the_line ();
   /* and clean up */
   xfree (lbuf);
 }
References _rl_set_the_line(), current_history(), entry::data, FREE, history_length, history_set_pos(), lbuf, previous_history(), rl_do_undo(), rl_line_buffer, rl_replace_from_history(), rl_replace_line(), rl_undo_list, savestring(), where_history(), and xfree.
Referenced by _rl_revert_all_lines().
_rl_set_insert_mode()
void _rl_set_insert_mode (int im, int force)
Definition at line 759 of file misc.c.
 {
 #ifdef CURSOR_MODE
   _rl_set_cursor (im, force);
 #endif
   rl_insert_mode = im;
 }
References _rl_set_cursor(), force, and rl_insert_mode.
Referenced by readline_internal_teardown(), rl_emacs_editing_mode(), rl_initialize(), rl_overwrite_mode(), and rl_vi_editing_mode().
_rl_start_using_history()
void _rl_start_using_history (void)
Definition at line 306 of file misc.c.
 {
   using_history ();
   if (_rl_saved_line_for_history)
     _rl_free_saved_history_line ();
   _rl_saved_line_for_history = (HIST_ENTRY *)NULL;
   _rl_history_search_pos = -99;     /* some random invalid history position */
 }
References _rl_free_saved_history_line(), _rl_history_search_pos, _rl_saved_line_for_history, NULL, and using_history().
Referenced by rl_initialize().
rl_beginning_of_history()
int rl_beginning_of_history (int count, int key)
Definition at line 542 of file misc.c.
 {
   return (rl_get_previous_history (1 + where_history (), key));
 }
References rl_get_previous_history(), and where_history().
Referenced by rl_fetch_history().
rl_clear_history()
void rl_clear_history (void)
Definition at line 508 of file misc.c.
 {
   HIST_ENTRY **hlist, *hent;
   register int i;
   UNDO_LIST *ul, *saved_undo_list;
   saved_undo_list = rl_undo_list;
   hlist = history_list ();      /* direct pointer, not copy */
   for (i = 0; i < history_length; i++)
     {
       hent = hlist[i];
       if (ul = (UNDO_LIST *)hent->data)
     {
       if (ul == saved_undo_list)
         saved_undo_list = 0;
       _rl_free_undo_list (ul);
       hent->data = 0;
     }
       _rl_free_history_entry (hent);
     }
   history_offset = history_length = 0;
   rl_undo_list = saved_undo_list;   /* should be NULL */
 }
References _rl_free_history_entry(), _rl_free_undo_list(), _hist_entry::data, history_length, history_list(), history_offset, i, and rl_undo_list.
rl_digit_argument()
int rl_digit_argument (int ignore, int key)
Definition at line 226 of file misc.c.
 {
   _rl_arg_init ();
   if (RL_ISSTATE (RL_STATE_CALLBACK))
     {
       _rl_arg_dispatch (_rl_argcxt, key);
       rl_message ("(arg: %d) ", rl_arg_sign * rl_numeric_arg);
       return 0;
     }
   else
     {
       rl_execute_next (key);
       return (rl_digit_loop ());
     }
 }
References _rl_arg_dispatch(), _rl_arg_init(), _rl_argcxt, rl_arg_sign, rl_digit_loop(), rl_execute_next(), RL_ISSTATE, rl_message(), rl_numeric_arg, and RL_STATE_CALLBACK.
Referenced by _rl_dispatch_subseq(), rl_trim_arg_from_keyseq(), and rl_vi_arg_digit().
rl_digit_loop()
static int rl_digit_loop (void) static
Definition at line 190 of file misc.c.
 {
   int c, r;
   while (1)
     {
       if (_rl_arg_overflow ())
     return 1;
       c = _rl_arg_getchar ();
       if (c < 0)
     {
       _rl_abort_internal ();
       return -1;
     }
       r = _rl_arg_dispatch (_rl_argcxt, c);
       if (r <= 0 || (RL_ISSTATE (RL_STATE_NUMERICARG) == 0))
         break;
     }
   return r;
 }
References _rl_abort_internal(), _rl_arg_dispatch(), _rl_arg_getchar(), _rl_arg_overflow(), _rl_argcxt, c, RL_ISSTATE, and RL_STATE_NUMERICARG.
Referenced by rl_digit_argument(), and rl_universal_argument().
rl_discard_argument()
int rl_discard_argument (void)
Definition at line 281 of file misc.c.
 {
   rl_ding ();
   rl_clear_message ();
   _rl_reset_argument ();
   return 0;
 }
References _rl_reset_argument(), rl_clear_message(), and rl_ding().
rl_emacs_editing_mode()
int rl_emacs_editing_mode (int count, int key)
Definition at line 745 of file misc.c.
 {
   rl_editing_mode = emacs_mode;
   _rl_set_insert_mode (RL_IM_INSERT, 1); /* emacs mode default is insert mode */
   _rl_keymap = emacs_standard_keymap;
   if (_rl_show_mode_in_prompt)
     _rl_reset_prompt ();
   return 0;
 }
References _rl_keymap, _rl_reset_prompt(), _rl_set_insert_mode(), _rl_show_mode_in_prompt, emacs_mode, emacs_standard_keymap, rl_editing_mode, and RL_IM_INSERT.
rl_end_of_history()
int rl_end_of_history (int count, int key)
Definition at line 549 of file misc.c.
 {
   rl_maybe_replace_line ();
   using_history ();
   rl_maybe_unsave_line ();
   return 0;
 }
References rl_maybe_replace_line(), rl_maybe_unsave_line(), and using_history().
rl_fetch_history()
int rl_fetch_history (int count, int c)
Definition at line 653 of file misc.c.
 {
   int wanted, nhist;
   /* Giving an argument of n means we want the nth command in the history
      file.  The command number is interpreted the same way that the bash
      `history' command does it -- that is, giving an argument count of 450
      to this command would get the command listed as number 450 in the
      output of `history'. */
   if (rl_explicit_arg)
     {
       nhist = history_base + where_history ();
       /* Negative arguments count back from the end of the history list. */
       wanted = (count >= 0) ? nhist - count : -count;
       if (wanted <= 0 || wanted >= nhist)
     {
       /* In vi mode, we don't change the line with an out-of-range
          argument, as for the `G' command. */
       if (rl_editing_mode == vi_mode)
         rl_ding ();
       else
         rl_beginning_of_history (0, 0);
     }
       else
         rl_get_previous_history (wanted, c);
     }
   else
     rl_beginning_of_history (count, 0);
   return (0);
 }
References c, count, history_base, rl_beginning_of_history(), rl_ding(), rl_editing_mode, rl_explicit_arg, rl_get_previous_history(), vi_mode, and where_history().
Referenced by rl_vi_fetch_history().
rl_get_next_history()
int rl_get_next_history (int count, int key)
Definition at line 559 of file misc.c.
 {
   HIST_ENTRY *temp;
   if (count < 0)
     return (rl_get_previous_history (-count, key));
   if (count == 0)
     return 0;
   rl_maybe_replace_line ();
   /* either not saved by rl_newline or at end of line, so set appropriately. */
   if (_rl_history_saved_point == -1 && (rl_point || rl_end))
     _rl_history_saved_point = (rl_point == rl_end) ? -1 : rl_point;
   temp = (HIST_ENTRY *)NULL;
   while (count)
     {
       temp = next_history ();
       if (!temp)
     break;
       --count;
     }
   if (temp == 0)
     rl_maybe_unsave_line ();
   else
     {
       rl_replace_from_history (temp, 0);
       _rl_history_set_point ();
     }
   return 0;
 }
References _rl_history_saved_point, _rl_history_set_point(), count, next_history(), NULL, rl_end, rl_get_previous_history(), rl_maybe_replace_line(), rl_maybe_unsave_line(), rl_point, and rl_replace_from_history().
Referenced by _rl_isearch_fini(), bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_arrow_keys(), rl_get_previous_history(), rl_history_search_forward(), and rl_history_substr_search_forward().
rl_get_previous_history()
int rl_get_previous_history (int count, int key)
Definition at line 597 of file misc.c.
 {
   HIST_ENTRY *old_temp, *temp;
   int had_saved_line;
   if (count < 0)
     return (rl_get_next_history (-count, key));
   if (count == 0 || history_list () == 0)
     return 0;
   /* either not saved by rl_newline or at end of line, so set appropriately. */
   if (_rl_history_saved_point == -1 && (rl_point || rl_end))
     _rl_history_saved_point = (rl_point == rl_end) ? -1 : rl_point;
   /* If we don't have a line saved, then save this one. */
   had_saved_line = _rl_saved_line_for_history != 0;
   rl_maybe_save_line ();
   /* If the current line has changed, save the changes. */
   rl_maybe_replace_line ();
   temp = old_temp = (HIST_ENTRY *)NULL;
   while (count)
     {
       temp = previous_history ();
       if (temp == 0)
     break;
       old_temp = temp;
       --count;
     }
   /* If there was a large argument, and we moved back to the start of the
      history, that is not an error.  So use the last value found. */
   if (!temp && old_temp)
     temp = old_temp;
   if (temp == 0)
     {
       if (had_saved_line == 0)
     _rl_free_saved_history_line ();
       rl_ding ();
     }
   else
     {
       rl_replace_from_history (temp, 0);
       _rl_history_set_point ();
     }
   return 0;
 }
References _rl_free_saved_history_line(), _rl_history_saved_point, _rl_history_set_point(), _rl_saved_line_for_history, count, history_list(), NULL, previous_history(), rl_ding(), rl_end, rl_get_next_history(), rl_maybe_replace_line(), rl_maybe_save_line(), rl_point, and rl_replace_from_history().
Referenced by _rl_isearch_fini(), bind_arrow_keys_internal(), bind_termcap_arrow_keys(), rl_arrow_keys(), rl_beginning_of_history(), rl_fetch_history(), rl_get_next_history(), rl_history_search_backward(), rl_history_substr_search_backward(), and set_saved_history().
rl_maybe_replace_line()
int rl_maybe_replace_line (void)
Definition at line 330 of file misc.c.
 {
   HIST_ENTRY *temp;
   temp = current_history ();
   /* If the current line has changed, save the changes. */
   if (temp && ((UNDO_LIST *)(temp->data) != rl_undo_list))
     {
       temp = replace_history_entry (where_history (), rl_line_buffer, (histdata_t)rl_undo_list);
       xfree (temp->line);
       FREE (temp->timestamp);
       xfree (temp);
     }
   return 0;
 }
References current_history(), _hist_entry::data, FREE, _hist_entry::line, replace_history_entry(), rl_line_buffer, rl_undo_list, _hist_entry::timestamp, where_history(), and xfree.
Referenced by _rl_isearch_init(), maybe_replace_line(), rl_end_of_history(), rl_get_next_history(), and rl_get_previous_history().
rl_maybe_save_line()
int rl_maybe_save_line (void)
Definition at line 369 of file misc.c.
 {
   if (_rl_saved_line_for_history == 0)
     {
       _rl_saved_line_for_history = (HIST_ENTRY *)xmalloc (sizeof (HIST_ENTRY));
       _rl_saved_line_for_history->line = savestring (rl_line_buffer);
       _rl_saved_line_for_history->timestamp = (char *)NULL;
       _rl_saved_line_for_history->data = (char *)rl_undo_list;
     }
   return 0;
 }
References _rl_saved_line_for_history, _hist_entry::data, _hist_entry::line, NULL, rl_line_buffer, rl_undo_list, savestring(), _hist_entry::timestamp, and xmalloc.
Referenced by _rl_nsearch_init(), maybe_save_line(), rl_get_previous_history(), and rl_history_search_internal().
rl_maybe_unsave_line()
int rl_maybe_unsave_line (void)
Definition at line 348 of file misc.c.
 {
   if (_rl_saved_line_for_history)
     {
       /* Can't call with `1' because rl_undo_list might point to an undo
      list from a history entry, as in rl_replace_from_history() below. */
       rl_replace_line (_rl_saved_line_for_history->line, 0);
       rl_undo_list = (UNDO_LIST *)_rl_saved_line_for_history->data;
       /* Doesn't free `data'. */
       _rl_free_history_entry (_rl_saved_line_for_history);
       _rl_saved_line_for_history = (HIST_ENTRY *)NULL;
       rl_point = rl_end;    /* rl_replace_line sets rl_end */
     }
   else
     rl_ding ();
   return 0;
 }
References _rl_free_history_entry(), _rl_saved_line_for_history, _hist_entry::data, _hist_entry::line, NULL, rl_ding(), rl_end, rl_point, rl_replace_line(), and rl_undo_list.
Referenced by _rl_nsearch_abort(), maybe_unsave_line(), noninc_dosearch(), rl_end_of_history(), rl_get_next_history(), and rl_history_search_internal().
rl_operate_and_get_next()
int rl_operate_and_get_next (int count, int c)
Definition at line 713 of file misc.c.
 {
   /* Accept the current line. */
   rl_newline (1, c);
   saved_history_logical_offset = rl_explicit_arg ? count : where_history () + history_base + 1;
   _rl_saved_internal_startup_hook = _rl_internal_startup_hook;
   _rl_internal_startup_hook = set_saved_history;
   return 0;
 }
References _rl_internal_startup_hook, _rl_saved_internal_startup_hook, c, count, history_base, rl_explicit_arg, rl_newline(), saved_history_logical_offset, set_saved_history(), and where_history().
rl_overwrite_mode()
int rl_overwrite_mode (int count, int key)
Definition at line 771 of file misc.c.
 {
   if (rl_explicit_arg == 0)
     _rl_set_insert_mode (rl_insert_mode ^ 1, 0);
   else if (count > 0)
     _rl_set_insert_mode (RL_IM_OVERWRITE, 0);
   else
     _rl_set_insert_mode (RL_IM_INSERT, 0);
   return 0;
 }
References _rl_set_insert_mode(), count, rl_explicit_arg, RL_IM_INSERT, RL_IM_OVERWRITE, and rl_insert_mode.
Referenced by bind_arrow_keys_internal(), and bind_termcap_arrow_keys().
rl_replace_from_history()
void rl_replace_from_history (HIST_ENTRY * entry, int flags)
Definition at line 422 of file misc.c.
 {
   /* Can't call with `1' because rl_undo_list might point to an undo list
      from a history entry, just like we're setting up here. */
   rl_replace_line (entry->line, 0);
   rl_undo_list = (UNDO_LIST *)entry->data;
   rl_point = rl_end;
   rl_mark = 0;
 #if defined (VI_MODE)
   if (rl_editing_mode == vi_mode)
     {
       rl_point = 0;
       rl_mark = rl_end;
     }
 #endif
 }
References entry::data, rl_editing_mode, rl_end, rl_mark, rl_point, rl_replace_line(), rl_undo_list, VI_MODE, and vi_mode.
Referenced by _rl_revert_previous_lines(), rl_get_next_history(), and rl_get_previous_history().
rl_universal_argument()
int rl_universal_argument (int count, int key)
Definition at line 246 of file misc.c.
 {
   _rl_arg_init ();
   rl_numeric_arg *= 4;
   return (RL_ISSTATE (RL_STATE_CALLBACK) ? 0 : rl_digit_loop ());
 }
References _rl_arg_init(), rl_digit_loop(), RL_ISSTATE, rl_numeric_arg, and RL_STATE_CALLBACK.
Referenced by _rl_arg_dispatch(), _rl_vi_arg_dispatch(), and rl_trim_arg_from_keyseq().
rl_vi_editing_mode()
int rl_vi_editing_mode (int count, int key)
Definition at line 733 of file misc.c.
 {
 #if defined (VI_MODE)
   _rl_set_insert_mode (RL_IM_INSERT, 1);    /* vi mode ignores insert mode */
   rl_editing_mode = vi_mode;
   rl_vi_insert_mode (1, key);
 #endif /* VI_MODE */
   return 0;
 }
References _rl_set_insert_mode(), rl_editing_mode, RL_IM_INSERT, rl_vi_insert_mode(), and vi_mode.
set_saved_history()
static int set_saved_history () static
Definition at line 696 of file misc.c.
 {
   int absolute_offset, count;
   if (saved_history_logical_offset >= 0)
     {
       absolute_offset = saved_history_logical_offset - history_base;
       count = where_history () - absolute_offset;
       rl_get_previous_history (count, 0);
     }
   saved_history_logical_offset = -1;
   _rl_internal_startup_hook = _rl_saved_internal_startup_hook;
   return (0);
 }
References _rl_internal_startup_hook, _rl_saved_internal_startup_hook, count, history_base, rl_get_previous_history(), saved_history_logical_offset, and where_history().
Referenced by rl_operate_and_get_next().
Variable Documentation
_rl_argcxt
_rl_arg_cxt _rl_argcxt
Definition at line 64 of file misc.c.
Referenced by _rl_arg_callback(), _rl_arg_dispatch(), _rl_arg_init(), _rl_arg_overflow(), _rl_reset_argument(), rl_callback_read_char(), rl_callback_sigcleanup(), rl_digit_argument(), and rl_digit_loop().
_rl_history_preserve_point
int _rl_history_preserve_point = 0
Definition at line 62 of file misc.c.
Referenced by _rl_history_set_point(), and rl_newline().
_rl_history_saved_point
int _rl_history_saved_point = -1
Definition at line 68 of file misc.c.
Referenced by _rl_history_set_point(), rl_get_next_history(), rl_get_previous_history(), and rl_newline().
_rl_saved_internal_startup_hook
rl_hook_func_t* _rl_saved_internal_startup_hook = 0 static
Definition at line 690 of file misc.c.
Referenced by rl_operate_and_get_next(), and set_saved_history().
_rl_saved_line_for_history
HIST_ENTRY* _rl_saved_line_for_history = (HIST_ENTRY *)NULL
Definition at line 302 of file misc.c.
Referenced by _rl_free_saved_history_line(), _rl_isearch_init(), _rl_start_using_history(), make_history_line_current(), rl_do_undo(), rl_get_previous_history(), rl_history_search_internal(), rl_maybe_save_line(), and rl_maybe_unsave_line().
saved_history_logical_offset
int saved_history_logical_offset = -1 static
Definition at line 691 of file misc.c.
Referenced by rl_operate_and_get_next(), and set_saved_history().