Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/g_game.h File Reference
g_game.h File Reference
#include "doomdef.h"
#include "d_event.h"
#include "d_ticcmd.h"
Functions
void G_DeathMatchSpawnPlayer (int playernum)
void G_InitNew (skill_t skill, int episode, int map)
void G_DeferedInitNew (skill_t skill, int episode, int map)
void G_DeferedPlayDemo (char *demo)
void G_LoadGame (char *name)
void G_DoLoadGame (void)
void G_SaveGame (int slot, char *description)
void G_RecordDemo (char *name)
void G_BeginRecording (void)
void G_PlayDemo (char *name)
void G_TimeDemo (char *name)
boolean G_CheckDemoStatus (void)
void G_ExitLevel (void)
void G_SecretExitLevel (void)
void G_WorldDone (void)
void G_BuildTiccmd (ticcmd_t *cmd, int maketic)
void G_Ticker (void)
boolean G_Responder (event_t *ev)
void G_ScreenShot (void)
void G_DrawMouseSpeedBox (void)
int G_VanillaVersionCode (void)
Variables
int vanilla_savegame_limit
int vanilla_demo_limit
Function Documentation
G_BeginRecording()
void G_BeginRecording (void)
Definition at line 2058 of file g_game.c.
 {
     int             i;
     // @category demo
     //
     // Record a high resolution "Doom 1.91" demo.
     //
     longtics = M_CheckParm("-longtics") != 0;
     // If not recording a longtics demo, record in low res
     lowres_turn = !longtics;
     demo_p = demobuffer;
     // Save the right version code for this demo
     if (longtics)
     {
         *demo_p++ = DOOM_191_VERSION;
     }
     else
     {
         *demo_p++ = G_VanillaVersionCode();
     }
     *demo_p++ = gameskill;
     *demo_p++ = gameepisode;
     *demo_p++ = gamemap;
     *demo_p++ = deathmatch;
     *demo_p++ = respawnparm;
     *demo_p++ = fastparm;
     *demo_p++ = nomonsters;
     *demo_p++ = consoleplayer;
     for (i=0 ; i<MAXPLAYERS ; i++)
     *demo_p++ = playeringame[i];
 }
References consoleplayer, deathmatch, demo_p, demobuffer, DOOM_191_VERSION, fastparm, G_VanillaVersionCode(), gameepisode, gamemap, gameskill, i, longtics, lowres_turn, M_CheckParm(), MAXPLAYERS, nomonsters, playeringame, and respawnparm.
Referenced by D_DoomLoop().
G_BuildTiccmd()
void G_BuildTiccmd (ticcmd_t * cmd, int maketic)
Definition at line 322 of file g_game.c.
 {
     int     i;
     boolean strafe;
     boolean bstrafe;
     int     speed;
     int     tspeed;
     int     forward;
     int     side;
     memset(cmd, 0, sizeof(ticcmd_t));
     cmd->consistancy =
     consistancy[consoleplayer][maketic%BACKUPTICS];
     strafe = gamekeydown[key_strafe] || mousebuttons[mousebstrafe]
     || joybuttons[joybstrafe];
     // fraggle: support the old "joyb_speed = 31" hack which
     // allowed an autorun effect
     speed = key_speed >= NUMKEYS
          || joybspeed >= MAX_JOY_BUTTONS
          || gamekeydown[key_speed]
          || joybuttons[joybspeed];
     forward = side = 0;
     // use two stage accelerative turning
     // on the keyboard and joystick
     if (joyxmove < 0
     || joyxmove > 0
     || gamekeydown[key_right]
     || gamekeydown[key_left])
     turnheld += ticdup;
     else
     turnheld = 0;
     if (turnheld < SLOWTURNTICS)
     tspeed = 2;             // slow turn
     else
     tspeed = speed;
     // let movement keys cancel each other out
     if (strafe)
     {
     if (gamekeydown[key_right])
     {
         // fprintf(stderr, "strafe right\n");
         side += sidemove[speed];
     }
     if (gamekeydown[key_left])
     {
         //  fprintf(stderr, "strafe left\n");
         side -= sidemove[speed];
     }
     if (joyxmove > 0)
         side += sidemove[speed];
     if (joyxmove < 0)
         side -= sidemove[speed];
     }
     else
     {
     if (gamekeydown[key_right])
         cmd->angleturn -= angleturn[tspeed];
     if (gamekeydown[key_left])
         cmd->angleturn += angleturn[tspeed];
     if (joyxmove > 0)
         cmd->angleturn -= angleturn[tspeed];
     if (joyxmove < 0)
         cmd->angleturn += angleturn[tspeed];
     }
     if (gamekeydown[key_up])
     {
     // fprintf(stderr, "up\n");
     forward += forwardmove[speed];
     }
     if (gamekeydown[key_down])
     {
     // fprintf(stderr, "down\n");
     forward -= forwardmove[speed];
     }
     if (joyymove < 0)
         forward += forwardmove[speed];
     if (joyymove > 0)
         forward -= forwardmove[speed];
     if (gamekeydown[key_strafeleft]
      || joybuttons[joybstrafeleft]
      || mousebuttons[mousebstrafeleft]
      || joystrafemove < 0)
     {
         side -= sidemove[speed];
     }
     if (gamekeydown[key_straferight]
      || joybuttons[joybstraferight]
      || mousebuttons[mousebstraferight]
      || joystrafemove > 0)
     {
         side += sidemove[speed];
     }
     // buttons
     cmd->chatchar = HU_dequeueChatChar();
     if (gamekeydown[key_fire] || mousebuttons[mousebfire]
     || joybuttons[joybfire])
     cmd->buttons |= BT_ATTACK;
     if (gamekeydown[key_use]
      || joybuttons[joybuse]
      || mousebuttons[mousebuse])
     {
     cmd->buttons |= BT_USE;
     // clear double clicks if hit use button
     dclicks = 0;
     }
     // If the previous or next weapon button is pressed, the
     // next_weapon variable is set to change weapons when
     // we generate a ticcmd.  Choose a new weapon.
     if (gamestate == GS_LEVEL && next_weapon != 0)
     {
         i = G_NextWeapon(next_weapon);
         cmd->buttons |= BT_CHANGE;
         cmd->buttons |= i << BT_WEAPONSHIFT;
     }
     else
     {
         // Check weapon keys.
         for (i=0; i<arrlen(weapon_keys); ++i)
         {
             int key = *weapon_keys[i];
             if (gamekeydown[key])
             {
                 cmd->buttons |= BT_CHANGE;
                 cmd->buttons |= i<<BT_WEAPONSHIFT;
                 break;
             }
         }
     }
     next_weapon = 0;
     // mouse
     if (mousebuttons[mousebforward])
     {
     forward += forwardmove[speed];
     }
     if (mousebuttons[mousebbackward])
     {
         forward -= forwardmove[speed];
     }
     if (dclick_use)
     {
         // forward double click
         if (mousebuttons[mousebforward] != dclickstate && dclicktime > 1 )
         {
             dclickstate = mousebuttons[mousebforward];
             if (dclickstate)
                 dclicks++;
             if (dclicks == 2)
             {
                 cmd->buttons |= BT_USE;
                 dclicks = 0;
             }
             else
                 dclicktime = 0;
         }
         else
         {
             dclicktime += ticdup;
             if (dclicktime > 20)
             {
                 dclicks = 0;
                 dclickstate = 0;
             }
         }
         // strafe double click
         bstrafe =
             mousebuttons[mousebstrafe]
             || joybuttons[joybstrafe];
         if (bstrafe != dclickstate2 && dclicktime2 > 1 )
         {
             dclickstate2 = bstrafe;
             if (dclickstate2)
                 dclicks2++;
             if (dclicks2 == 2)
             {
                 cmd->buttons |= BT_USE;
                 dclicks2 = 0;
             }
             else
                 dclicktime2 = 0;
         }
         else
         {
             dclicktime2 += ticdup;
             if (dclicktime2 > 20)
             {
                 dclicks2 = 0;
                 dclickstate2 = 0;
             }
         }
     }
     forward += mousey;
     if (strafe)
     side += mousex*2;
     else
     cmd->angleturn -= mousex*0x8;
     if (mousex == 0)
     {
         // No movement in the previous frame
         testcontrols_mousespeed = 0;
     }
     mousex = mousey = 0;
     if (forward > MAXPLMOVE)
     forward = MAXPLMOVE;
     else if (forward < -MAXPLMOVE)
     forward = -MAXPLMOVE;
     if (side > MAXPLMOVE)
     side = MAXPLMOVE;
     else if (side < -MAXPLMOVE)
     side = -MAXPLMOVE;
     cmd->forwardmove += forward;
     cmd->sidemove += side;
     // special buttons
     if (sendpause)
     {
     sendpause = false;
     cmd->buttons = BT_SPECIAL | BTS_PAUSE;
     }
     if (sendsave)
     {
     sendsave = false;
     cmd->buttons = BT_SPECIAL | BTS_SAVEGAME | (savegameslot<<BTS_SAVESHIFT);
     }
     // low-res turning
     if (lowres_turn)
     {
         static signed short carry = 0;
         signed short desired_angleturn;
         desired_angleturn = cmd->angleturn + carry;
         // round angleturn to the nearest 256 unit boundary
         // for recording demos with single byte values for turn
         cmd->angleturn = (desired_angleturn + 128) & 0xff00;
         // Carry forward the error from the reduced resolution to the
         // next tic, so that successive small movements can accumulate.
         carry = desired_angleturn - cmd->angleturn;
     }
 }
References ticcmd_t::angleturn, angleturn, arrlen, BACKUPTICS, BT_ATTACK, BT_CHANGE, BT_SPECIAL, BT_USE, BT_WEAPONSHIFT, BTS_PAUSE, BTS_SAVEGAME, BTS_SAVESHIFT, ticcmd_t::buttons, ticcmd_t::chatchar, ticcmd_t::consistancy, consistancy, consoleplayer, dclick_use, dclicks, dclicks2, dclickstate, dclickstate2, dclicktime, dclicktime2, ticcmd_t::forwardmove, forwardmove, G_NextWeapon(), gamekeydown, gamestate, GS_LEVEL, HU_dequeueChatChar(), i, joybfire, joybspeed, joybstrafe, joybstrafeleft, joybstraferight, joybuse, joybuttons, joystrafemove, joyxmove, joyymove, key_down, key_fire, key_left, key_right, key_speed, key_strafe, key_strafeleft, key_straferight, key_up, key_use, lowres_turn, maketic, MAX_JOY_BUTTONS, MAXPLMOVE, memset(), mousebbackward, mousebfire, mousebforward, mousebstrafe, mousebstrafeleft, mousebstraferight, mousebuse, mousebuttons, mousex, mousey, next_weapon, NUMKEYS, savegameslot, sendpause, sendsave, ticcmd_t::sidemove, sidemove, SLOWTURNTICS, testcontrols_mousespeed, ticdup, turnheld, and weapon_keys.
G_CheckDemoStatus()
boolean G_CheckDemoStatus (void)
Definition at line 2248 of file g_game.c.
 {
     int             endtime;
     if (timingdemo)
     {
         float fps;
         int realtics;
     endtime = I_GetTime ();
         realtics = endtime - starttime;
         fps = ((float) gametic * TICRATE) / realtics;
         // Prevent recursive calls
         timingdemo = false;
         demoplayback = false;
     I_Error ("timed %i gametics in %i realtics (%f fps)",
                  gametic, realtics, fps);
     }
     if (demoplayback)
     {
         W_ReleaseLumpName(defdemoname);
     demoplayback = false;
     netdemo = false;
     netgame = false;
     deathmatch = false;
     playeringame[1] = playeringame[2] = playeringame[3] = 0;
     respawnparm = false;
     fastparm = false;
     nomonsters = false;
     consoleplayer = 0;
         if (singledemo)
             I_Quit ();
         else
             D_AdvanceDemo ();
     return true;
     }
     if (demorecording)
     {
     *demo_p++ = DEMOMARKER;
     M_WriteFile (demoname, demobuffer, demo_p - demobuffer);
     Z_Free (demobuffer);
     demorecording = false;
     I_Error ("Demo %s recorded",demoname);
     }
     return false;
 }
References consoleplayer, D_AdvanceDemo(), deathmatch, defdemoname, demo_p, demobuffer, DEMOMARKER, demoname, demoplayback, demorecording, fastparm, gametic, I_Error(), I_GetTime(), I_Quit(), M_WriteFile(), netdemo, netgame, nomonsters, playeringame, respawnparm, singledemo, starttime, TICRATE, timingdemo, W_ReleaseLumpName(), and Z_Free().
Referenced by D_DoomMain(), G_ReadDemoTiccmd(), G_WriteDemoTiccmd(), and PlayerQuitGame().
G_DeathMatchSpawnPlayer()
void G_DeathMatchSpawnPlayer (int playernum)
Definition at line 1223 of file g_game.c.
 {
     int             i,j;
     int             selections;
     selections = deathmatch_p - deathmatchstarts;
     if (selections < 4)
     I_Error ("Only %i deathmatch spots, 4 required", selections);
     for (j=0 ; j<20 ; j++)
     {
     i = P_Random() % selections;
     if (G_CheckSpot (playernum, &deathmatchstarts[i]) )
     {
         deathmatchstarts[i].type = playernum+1;
         P_SpawnPlayer (&deathmatchstarts[i]);
         return;
     }
     }
     // no good spot, so the player will probably get stuck
     P_SpawnPlayer (&playerstarts[playernum]);
 }
References deathmatch_p, deathmatchstarts, G_CheckSpot(), i, I_Error(), j, P_Random(), P_SpawnPlayer(), and playerstarts.
Referenced by G_DoReborn(), G_Responder(), and P_SetupLevel().
G_DeferedInitNew()
void G_DeferedInitNew (skill_t skill, int episode, int map)
Definition at line 1698 of file g_game.c.
 {
     d_skill = skill;
     d_episode = episode;
     d_map = map;
     gameaction = ga_newgame;
 }
References d_episode, d_map, d_skill, ga_newgame, and gameaction.
Referenced by M_ChooseSkill(), M_VerifyNightmare(), and ST_Responder().
G_DeferedPlayDemo()
void G_DeferedPlayDemo (char * demo)
Definition at line 2107 of file g_game.c.
 {
     defdemoname = name;
     gameaction = ga_playdemo;
 }
References defdemoname, ga_playdemo, gameaction, and name.
Referenced by D_DoAdvanceDemo(), and D_DoomMain().
G_DoLoadGame()
void G_DoLoadGame (void)
Definition at line 1548 of file g_game.c.
 {
     int savedleveltime;
     gameaction = ga_nothing;
     save_stream = fopen(savename, "rb");
     if (save_stream == NULL)
     {
         return;
     }
     savegame_error = false;
     if (!P_ReadSaveGameHeader())
     {
         fclose(save_stream);
         return;
     }
     savedleveltime = leveltime;
     // load a base level
     G_InitNew (gameskill, gameepisode, gamemap);
     leveltime = savedleveltime;
     // dearchive all the modifications
     P_UnArchivePlayers ();
     P_UnArchiveWorld ();
     P_UnArchiveThinkers ();
     P_UnArchiveSpecials ();
     if (!P_ReadSaveGameEOF())
     I_Error ("Bad savegame");
     fclose(save_stream);
     if (setsizeneeded)
         R_ExecuteSetViewSize ();
     // draw the pattern into the back screen
     R_FillBackScreen ();
 }
References fclose(), fopen(), G_InitNew(), ga_nothing, gameaction, gameepisode, gamemap, gameskill, I_Error(), leveltime, NULL, P_ReadSaveGameEOF(), P_ReadSaveGameHeader(), P_UnArchivePlayers(), P_UnArchiveSpecials(), P_UnArchiveThinkers(), P_UnArchiveWorld(), R_ExecuteSetViewSize(), R_FillBackScreen(), save_stream, savegame_error, savename, and setsizeneeded.
Referenced by G_Ticker().
G_DrawMouseSpeedBox()
void G_DrawMouseSpeedBox (void)
G_ExitLevel()
void G_ExitLevel (void)
Definition at line 1328 of file g_game.c.
 {
     secretexit = false;
     gameaction = ga_completed;
 }
References ga_completed, gameaction, and secretexit.
Referenced by A_BossDeath(), A_BrainDie(), P_CrossSpecialLine(), P_PlayerInSpecialSector(), P_UpdateSpecials(), and P_UseSpecialLine().
G_InitNew()
void G_InitNew (skill_t skill, int episode, int map)
Definition at line 1727 of file g_game.c.
 {
     char *skytexturename;
     int             i;
     if (paused)
     {
     paused = false;
     S_ResumeSound ();
     }
     /*
     // Note: This commented-out block of code was added at some point
     // between the DOS version(s) and the Doom source release. It isn't
     // found in disassemblies of the DOS version and causes IDCLEV and
     // the -warp command line parameter to behave differently.
     // This is left here for posterity.
     // This was quite messy with SPECIAL and commented parts.
     // Supposedly hacks to make the latest edition work.
     // It might not work properly.
     if (episode < 1)
       episode = 1;
     if ( gamemode == retail )
     {
       if (episode > 4)
     episode = 4;
     }
     else if ( gamemode == shareware )
     {
       if (episode > 1)
        episode = 1; // only start episode 1 on shareware
     }
     else
     {
       if (episode > 3)
     episode = 3;
     }
     */
     if (skill > sk_nightmare)
     skill = sk_nightmare;
     if (gameversion >= exe_ultimate)
     {
         if (episode == 0)
         {
             episode = 4;
         }
     }
     else
     {
         if (episode < 1)
         {
             episode = 1;
         }
         if (episode > 3)
         {
             episode = 3;
         }
     }
     if (episode > 1 && gamemode == shareware)
     {
         episode = 1;
     }
     if (map < 1)
     map = 1;
     if ( (map > 9)
      && ( gamemode != commercial) )
       map = 9;
     M_ClearRandom ();
     if (skill == sk_nightmare || respawnparm )
     respawnmonsters = true;
     else
     respawnmonsters = false;
     if (fastparm || (skill == sk_nightmare && gameskill != sk_nightmare) )
     {
     for (i=S_SARG_RUN1 ; i<=S_SARG_PAIN2 ; i++)
         states[i].tics >>= 1;
     mobjinfo[MT_BRUISERSHOT].speed = 20*FRACUNIT;
     mobjinfo[MT_HEADSHOT].speed = 20*FRACUNIT;
     mobjinfo[MT_TROOPSHOT].speed = 20*FRACUNIT;
     }
     else if (skill != sk_nightmare && gameskill == sk_nightmare)
     {
     for (i=S_SARG_RUN1 ; i<=S_SARG_PAIN2 ; i++)
         states[i].tics <<= 1;
     mobjinfo[MT_BRUISERSHOT].speed = 15*FRACUNIT;
     mobjinfo[MT_HEADSHOT].speed = 10*FRACUNIT;
     mobjinfo[MT_TROOPSHOT].speed = 10*FRACUNIT;
     }
     // force players to be initialized upon first level load
     for (i=0 ; i<MAXPLAYERS ; i++)
     players[i].playerstate = PST_REBORN;
     usergame = true;                // will be set false if a demo
     paused = false;
     demoplayback = false;
     automapactive = false;
     viewactive = true;
     gameepisode = episode;
     gamemap = map;
     gameskill = skill;
     viewactive = true;
     // Set the sky to use.
     //
     // Note: This IS broken, but it is how Vanilla Doom behaves.
     // See http://doomwiki.org/wiki/Sky_never_changes_in_Doom_II.
     //
     // Because we set the sky here at the start of a game, not at the
     // start of a level, the sky texture never changes unless we
     // restore from a saved game.  This was fixed before the Doom
     // source release, but this IS the way Vanilla DOS Doom behaves.
     if (gamemode == commercial)
     {
         if (gamemap < 12)
             skytexturename = "SKY1";
         else if (gamemap < 21)
             skytexturename = "SKY2";
         else
             skytexturename = "SKY3";
     }
     else
     {
         switch (gameepisode)
         {
           default:
           case 1:
             skytexturename = "SKY1";
             break;
           case 2:
             skytexturename = "SKY2";
             break;
           case 3:
             skytexturename = "SKY3";
             break;
           case 4:        // Special Edition sky
             skytexturename = "SKY4";
             break;
         }
     }
     skytexturename = DEH_String(skytexturename);
     skytexture = R_TextureNumForName(skytexturename);
     G_DoLoadLevel ();
 }
References automapactive, commercial, DEH_String, demoplayback, exe_ultimate, fastparm, FRACUNIT, G_DoLoadLevel(), gameepisode, gamemap, gamemode, gameskill, gameversion, i, M_ClearRandom(), MAXPLAYERS, mobjinfo, MT_BRUISERSHOT, MT_HEADSHOT, MT_TROOPSHOT, paused, players, PST_REBORN, R_TextureNumForName(), respawnmonsters, respawnparm, S_ResumeSound(), S_SARG_PAIN2, S_SARG_RUN1, shareware, sk_nightmare, skytexture, mobjinfo_t::speed, states, usergame, and viewactive.
Referenced by D_DoomMain(), G_DoLoadGame(), G_DoNewGame(), and G_DoPlayDemo().
G_LoadGame()
void G_LoadGame (char * name)
Definition at line 1539 of file g_game.c.
 {
     M_StringCopy(savename, name, sizeof(savename));
     gameaction = ga_loadgame;
 }
References ga_loadgame, gameaction, M_StringCopy(), name, and savename.
Referenced by D_DoomMain(), and M_LoadSelect().
G_PlayDemo()
void G_PlayDemo (char * name)
G_RecordDemo()
void G_RecordDemo (char * name)
Definition at line 2010 of file g_game.c.
 {
     size_t demoname_size;
     int i;
     int maxsize;
     usergame = false;
     demoname_size = strlen(name) + 5;
     demoname = Z_Malloc(demoname_size, PU_STATIC, NULL);
     M_snprintf(demoname, demoname_size, "%s.lmp", name);
     maxsize = 0x20000;
     // @arg <size>
     // @category demo
     // @vanilla
     //
     // Specify the demo buffer size (KiB)
     //
     i = M_CheckParmWithArgs("-maxdemo", 1);
     if (i)
     maxsize = atoi(myargv[i+1])*1024;
     demobuffer = Z_Malloc (maxsize,PU_STATIC,NULL);
     demoend = demobuffer + maxsize;
     demorecording = true;
 }
References atoi(), demobuffer, demoend, demoname, demorecording, i, M_CheckParmWithArgs(), M_snprintf(), myargv, name, NULL, PU_STATIC, strlen(), usergame, and Z_Malloc().
Referenced by D_DoomMain().
G_Responder()
boolean G_Responder (event_t * ev)
Definition at line 733 of file g_game.c.
 {
     // allow spy mode changes even during the demo
     if (gamestate == GS_LEVEL && ev->type == ev_keydown
      && ev->data1 == key_spy && (singledemo || !deathmatch) )
     {
     // spy mode
     do
     {
         displayplayer++;
         if (displayplayer == MAXPLAYERS)
         displayplayer = 0;
     } while (!playeringame[displayplayer] && displayplayer != consoleplayer);
     return true;
     }
     // any other key pops up menu if in demos
     if (gameaction == ga_nothing && !singledemo &&
     (demoplayback || gamestate == GS_DEMOSCREEN)
     )
     {
     if (ev->type == ev_keydown ||
         (ev->type == ev_mouse && ev->data1) ||
         (ev->type == ev_joystick && ev->data1) )
     {
         M_StartControlPanel ();
         return true;
     }
     return false;
     }
     if (gamestate == GS_LEVEL)
     {
 #if 0
     if (devparm && ev->type == ev_keydown && ev->data1 == ';')
     {
         G_DeathMatchSpawnPlayer (0);
         return true;
     }
 #endif
     if (HU_Responder (ev))
         return true;    // chat ate the event
     if (ST_Responder (ev))
         return true;    // status window ate it
     if (AM_Responder (ev))
         return true;    // automap ate it
     }
     if (gamestate == GS_FINALE)
     {
     if (F_Responder (ev))
         return true;    // finale ate the event
     }
     if (testcontrols && ev->type == ev_mouse)
     {
         // If we are invoked by setup to test the controls, save the
         // mouse speed so that we can display it on-screen.
         // Perform a low pass filter on this so that the thermometer
         // appears to move smoothly.
         testcontrols_mousespeed = abs(ev->data2);
     }
     // If the next/previous weapon keys are pressed, set the next_weapon
     // variable to change weapons when the next ticcmd is generated.
     if (ev->type == ev_keydown && ev->data1 == key_prevweapon)
     {
         next_weapon = -1;
     }
     else if (ev->type == ev_keydown && ev->data1 == key_nextweapon)
     {
         next_weapon = 1;
     }
     switch (ev->type)
     {
       case ev_keydown:
     if (ev->data1 == key_pause)
     {
         sendpause = true;
     }
         else if (ev->data1 <NUMKEYS)
         {
         gamekeydown[ev->data1] = true;
         }
     return true;    // eat key down events
       case ev_keyup:
     if (ev->data1 <NUMKEYS)
         gamekeydown[ev->data1] = false;
     return false;   // always let key up events filter down
       case ev_mouse:
         SetMouseButtons(ev->data1);
     mousex = ev->data2*(mouseSensitivity+5)/10;
     mousey = ev->data3*(mouseSensitivity+5)/10;
     return true;    // eat events
       case ev_joystick:
         SetJoyButtons(ev->data1);
     joyxmove = ev->data2;
     joyymove = ev->data3;
         joystrafemove = ev->data4;
     return true;    // eat events
       default:
     break;
     }
     return false;
 }
References abs(), AM_Responder(), consoleplayer, event_t::data1, event_t::data2, event_t::data3, event_t::data4, deathmatch, demoplayback, devparm, displayplayer, ev_joystick, ev_keydown, ev_keyup, ev_mouse, F_Responder(), G_DeathMatchSpawnPlayer(), ga_nothing, gameaction, gamekeydown, gamestate, GS_DEMOSCREEN, GS_FINALE, GS_LEVEL, HU_Responder(), joystrafemove, joyxmove, joyymove, key_nextweapon, key_pause, key_prevweapon, key_spy, M_StartControlPanel(), MAXPLAYERS, mouseSensitivity, mousex, mousey, next_weapon, NUMKEYS, playeringame, sendpause, SetJoyButtons(), SetMouseButtons(), singledemo, ST_Responder(), testcontrols, testcontrols_mousespeed, and event_t::type.
Referenced by D_ProcessEvents().
G_SaveGame()
void G_SaveGame (int slot, char * description)
Definition at line 1601 of file g_game.c.
 {
     savegameslot = slot;
     M_StringCopy(savedescription, description, sizeof(savedescription));
     sendsave = true;
 }
References M_StringCopy(), savedescription, savegameslot, and sendsave.
Referenced by M_DoSave().
G_ScreenShot()
void G_ScreenShot (void)
Definition at line 1296 of file g_game.c.
 {
     gameaction = ga_screenshot;
 }
References ga_screenshot, and gameaction.
Referenced by M_Responder().
G_SecretExitLevel()
void G_SecretExitLevel (void)
Definition at line 1335 of file g_game.c.
 {
     // IF NO WOLF3D LEVELS, NO SECRET EXIT!
     if ( (gamemode == commercial)
       && (W_CheckNumForName("map31")<0))
     secretexit = false;
     else
     secretexit = true;
     gameaction = ga_completed;
 }
References commercial, ga_completed, gameaction, gamemode, secretexit, and W_CheckNumForName().
Referenced by P_CrossSpecialLine(), and P_UseSpecialLine().
G_Ticker()
void G_Ticker (void)
Definition at line 854 of file g_game.c.
 {
     int     i;
     int     buf;
     ticcmd_t*   cmd;
     // do player reborns if needed
     for (i=0 ; i<MAXPLAYERS ; i++)
     if (playeringame[i] && players[i].playerstate == PST_REBORN)
         G_DoReborn (i);
     // do things to change the game state
     while (gameaction != ga_nothing)
     {
     switch (gameaction)
     {
       case ga_loadlevel:
         G_DoLoadLevel ();
         break;
       case ga_newgame:
         G_DoNewGame ();
         break;
       case ga_loadgame:
         G_DoLoadGame ();
         break;
       case ga_savegame:
         G_DoSaveGame ();
         break;
       case ga_playdemo:
         G_DoPlayDemo ();
         break;
       case ga_completed:
         G_DoCompleted ();
         break;
       case ga_victory:
         F_StartFinale ();
         break;
       case ga_worlddone:
         G_DoWorldDone ();
         break;
       case ga_screenshot:
         V_ScreenShot("DOOM%02i.%s");
             players[consoleplayer].message = DEH_String("screen shot");
         gameaction = ga_nothing;
         break;
       case ga_nothing:
         break;
     }
     }
     // get commands, check consistancy,
     // and build new consistancy check
     buf = (gametic/ticdup)%BACKUPTICS;
     for (i=0 ; i<MAXPLAYERS ; i++)
     {
     if (playeringame[i])
     {
         cmd = &players[i].cmd;
         memcpy(cmd, &netcmds[i], sizeof(ticcmd_t));
         if (demoplayback)
         G_ReadDemoTiccmd (cmd);
         if (demorecording)
         G_WriteDemoTiccmd (cmd);
         // check for turbo cheats
             // check ~ 4 seconds whether to display the turbo message.
             // store if the turbo threshold was exceeded in any tics
             // over the past 4 seconds.  offset the checking period
             // for each player so messages are not displayed at the
             // same time.
             if (cmd->forwardmove > TURBOTHRESHOLD)
             {
                 turbodetected[i] = true;
             }
             if ((gametic & 31) == 0
              && ((gametic >> 5) % MAXPLAYERS) == i
              && turbodetected[i])
             {
                 static char turbomessage[80];
                 extern char *player_names[4];
                 M_snprintf(turbomessage, sizeof(turbomessage),
                            "%s is turbo!", player_names[i]);
                 players[consoleplayer].message = turbomessage;
                 turbodetected[i] = false;
             }
         if (netgame && !netdemo && !(gametic%ticdup) )
         {
         if (gametic > BACKUPTICS
             && consistancy[i][buf] != cmd->consistancy)
         {
             I_Error ("consistency failure (%i should be %i)",
                  cmd->consistancy, consistancy[i][buf]);
         }
         if (players[i].mo)
             consistancy[i][buf] = players[i].mo->x;
         else
             consistancy[i][buf] = rndindex;
         }
     }
     }
     // check for special buttons
     for (i=0 ; i<MAXPLAYERS ; i++)
     {
     if (playeringame[i])
     {
         if (players[i].cmd.buttons & BT_SPECIAL)
         {
         switch (players[i].cmd.buttons & BT_SPECIALMASK)
         {
           case BTS_PAUSE:
             paused ^= 1;
             if (paused)
             S_PauseSound ();
             else
             S_ResumeSound ();
             break;
           case BTS_SAVEGAME:
             if (!savedescription[0])
                     {
                         M_StringCopy(savedescription, "NET GAME",
                                      sizeof(savedescription));
                     }
             savegameslot =
             (players[i].cmd.buttons & BTS_SAVEMASK)>>BTS_SAVESHIFT;
             gameaction = ga_savegame;
             break;
         }
         }
     }
     }
     // Have we just finished displaying an intermission screen?
     if (oldgamestate == GS_INTERMISSION && gamestate != GS_INTERMISSION)
     {
         WI_End();
     }
     oldgamestate = gamestate;
     // do main actions
     switch (gamestate)
     {
       case GS_LEVEL:
     P_Ticker ();
     ST_Ticker ();
     AM_Ticker ();
     HU_Ticker ();
     break;
       case GS_INTERMISSION:
     WI_Ticker ();
     break;
       case GS_FINALE:
     F_Ticker ();
     break;
       case GS_DEMOSCREEN:
     D_PageTicker ();
     break;
     }
 }
References AM_Ticker(), BACKUPTICS, BT_SPECIAL, BT_SPECIALMASK, BTS_PAUSE, BTS_SAVEGAME, BTS_SAVEMASK, BTS_SAVESHIFT, buf, ticcmd_t::buttons, player_s::cmd, ticcmd_t::consistancy, consistancy, consoleplayer, D_PageTicker(), DEH_String, demoplayback, demorecording, F_StartFinale(), F_Ticker(), ticcmd_t::forwardmove, G_DoCompleted(), G_DoLoadGame(), G_DoLoadLevel(), G_DoNewGame(), G_DoPlayDemo(), G_DoReborn(), G_DoSaveGame(), G_DoWorldDone(), G_ReadDemoTiccmd(), G_WriteDemoTiccmd(), ga_completed, ga_loadgame, ga_loadlevel, ga_newgame, ga_nothing, ga_playdemo, ga_savegame, ga_screenshot, ga_victory, ga_worlddone, gameaction, gamestate, gametic, GS_DEMOSCREEN, GS_FINALE, GS_INTERMISSION, GS_LEVEL, HU_Ticker(), i, I_Error(), M_snprintf(), M_StringCopy(), MAXPLAYERS, memcpy(), player_s::message, player_s::mo, netcmds, netdemo, netgame, oldgamestate, P_Ticker(), paused, player_names, playeringame, players, PST_REBORN, rndindex, S_PauseSound(), S_ResumeSound(), savedescription, savegameslot, ST_Ticker(), ticdup, turbodetected, TURBOTHRESHOLD, V_ScreenShot(), WI_End(), WI_Ticker(), and mobj_s::x.
Referenced by RunTic().
G_TimeDemo()
void G_TimeDemo (char * name)
Definition at line 2220 of file g_game.c.
 {
     // @vanilla
     //
     // Disable rendering the screen entirely.
     //
     nodrawers = M_CheckParm ("-nodraw");
     timingdemo = true;
     singletics = true;
     defdemoname = name;
     gameaction = ga_playdemo;
 }
References defdemoname, ga_playdemo, gameaction, M_CheckParm(), name, nodrawers, singletics, and timingdemo.
Referenced by D_DoomMain().
G_VanillaVersionCode()
int G_VanillaVersionCode (void)
Definition at line 2040 of file g_game.c.
 {
     switch (gameversion)
     {
         case exe_doom_1_2:
             I_Error("Doom 1.2 does not have a version code!");
         case exe_doom_1_666:
             return 106;
         case exe_doom_1_7:
             return 107;
         case exe_doom_1_8:
             return 108;
         case exe_doom_1_9:
         default:  // All other versions are variants on v1.9:
             return 109;
     }
 }
References exe_doom_1_2, exe_doom_1_666, exe_doom_1_7, exe_doom_1_8, exe_doom_1_9, gameversion, and I_Error().
Referenced by G_BeginRecording(), G_DoPlayDemo(), GetGameName(), P_ReadSaveGameHeader(), and P_WriteSaveGameHeader().
G_WorldDone()
void G_WorldDone (void)
Definition at line 1494 of file g_game.c.
 {
     gameaction = ga_worlddone;
     if (secretexit)
     players[consoleplayer].didsecret = true;
     if ( gamemode == commercial )
     {
     switch (gamemap)
     {
       case 15:
       case 31:
         if (!secretexit)
         break;
       case 6:
       case 11:
       case 20:
       case 30:
         F_StartFinale ();
         break;
     }
     }
 }
References commercial, consoleplayer, player_s::didsecret, F_StartFinale(), ga_worlddone, gameaction, gamemap, gamemode, players, and secretexit.
Referenced by WI_updateNoState().
Variable Documentation
vanilla_demo_limit
int vanilla_demo_limit extern
Definition at line 231 of file g_game.c.
Referenced by D_BindVariables(), and G_WriteDemoTiccmd().
vanilla_savegame_limit
int vanilla_savegame_limit extern
Definition at line 230 of file g_game.c.
Referenced by D_BindVariables(), and G_DoSaveGame().