Fennix: Userspace/apps/base/busybox/libbb/obscure.c File Reference
obscure.c File Reference
#include "libbb.h"
Macros
#define CATEGORIES 4
#define LOWERCASE 1
#define UPPERCASE 2
#define NUMBERS 4
#define SPECIAL 8
#define LAST_CAT 8
Functions
static int string_checker_helper (const char *p1, const char *p2) __attribute__((__pure__))
static int string_checker (const char *p1, const char *p2)
static const char * obscure_msg (const char *old_p, const char *new_p, const struct passwd *pw)
int FAST_FUNC obscure (const char *old, const char *newval, const struct passwd *pw)
Macro Definition Documentation
CATEGORIES
#define CATEGORIES 4
Definition at line 85 of file obscure.c.
LAST_CAT
#define LAST_CAT 8
Definition at line 92 of file obscure.c.
LOWERCASE
#define LOWERCASE 1
Definition at line 87 of file obscure.c.
NUMBERS
#define NUMBERS 4
Definition at line 89 of file obscure.c.
SPECIAL
#define SPECIAL 8
Definition at line 90 of file obscure.c.
UPPERCASE
#define UPPERCASE 2
Definition at line 88 of file obscure.c.
Function Documentation
obscure()
int FAST_FUNC obscure (const char * old, const char * newval, const struct passwd * pw)
Definition at line 174 of file obscure.c.
 {
     const char *msg;
     msg = obscure_msg(old, newval, pw);
     if (msg) {
         printf("Bad password: %s\n", msg);
         return 1;
     }
     return 0;
 }
References obscure_msg(), old, printf, and pw.
Referenced by new_password().
obscure_msg()
static const char* obscure_msg (const char * old_p, const char * new_p, const struct passwd * pw) static
Definition at line 94 of file obscure.c.
 {
     unsigned length;
     unsigned size;
     unsigned mixed;
     unsigned c;
     unsigned i;
     const char *p;
     char *hostname;
     /* size */
     if (!new_p || (length = strlen(new_p)) < CONFIG_PASSWORD_MINLEN)
         return "too short";
     /* no username as-is, as sub-string, reversed, capitalized, doubled */
     if (string_checker(new_p, pw->pw_name)) {
         return "similar to username";
     }
 #ifndef __BIONIC__
     /* no gecos as-is, as sub-string, reversed, capitalized, doubled */
     if (pw->pw_gecos[0] && string_checker(new_p, pw->pw_gecos)) {
         return "similar to gecos";
     }
 #endif
     /* hostname as-is, as sub-string, reversed, capitalized, doubled */
     hostname = safe_gethostname();
     i = string_checker(new_p, hostname);
     free(hostname);
     if (i)
         return "similar to hostname";
     /* Should / Must contain a mix of: */
     mixed = 0;
     for (i = 0; i < length; i++) {
         if (islower(new_p[i])) {        /* a-z */
             mixed |= LOWERCASE;
         } else if (isupper(new_p[i])) { /* A-Z */
             mixed |= UPPERCASE;
         } else if (isdigit(new_p[i])) { /* 0-9 */
             mixed |= NUMBERS;
         } else  {                       /* special characters */
             mixed |= SPECIAL;
         }
         /* Count i'th char */
         c = 0;
         p = new_p;
         while (1) {
             p = strchr(p, new_p[i]);
             if (p == NULL) {
                 break;
             }
             c++;
             p++;
             if (!*p) {
                 break;
             }
         }
         /* More than 50% similar characters ? */
         if (c*2 >= length) {
             return "too many similar characters";
         }
     }
     size = CONFIG_PASSWORD_MINLEN + 2*CATEGORIES;
     for (i = 1; i <= LAST_CAT; i <<= 1)
         if (mixed & i)
             size -= 2;
     if (length < size)
         return "too weak";
     if (old_p && old_p[0]) {
         /* check vs. old password */
         if (string_checker(new_p, old_p)) {
             return "similar to old password";
         }
     }
     return NULL;
 }
References c, CATEGORIES, free, i, isdigit, islower, isupper, LAST_CAT, LOWERCASE, NULL, NUMBERS, p, pw, passwd::pw_gecos, passwd::pw_name, safe_gethostname(), size, SPECIAL, strchr(), string_checker(), strlen(), and UPPERCASE.
Referenced by obscure().
string_checker()
static int string_checker (const char * p1, const char * p2) static
Definition at line 60 of file obscure.c.
 {
     int size, i;
     /* check string */
     int ret = string_checker_helper(p1, p2);
     /* make our own copy */
     char *p = xstrdup(p1);
     /* reverse string */
     i = size = strlen(p1);
     while (--i >= 0) {
         *p++ = p1[i];
     }
     p -= size; /* restore pointer */
     /* check reversed string */
     ret |= string_checker_helper(p, p2);
     /* clean up */
     nuke_str(p);
     free(p);
     return ret;
 }
References free, i, nuke_str(), p, size, string_checker_helper(), strlen(), and xstrdup().
Referenced by obscure_msg().
string_checker_helper()
static int string_checker_helper (const char * p1, const char * p2) static
Definition at line 46 of file obscure.c.
 {
     /* as sub-string */
     if (strcasestr(p2, p1) != NULL
     /* invert in case haystack is shorter than needle */
      || strcasestr(p1, p2) != NULL
     /* as-is or capitalized */
     /* || strcasecmp(p1, p2) == 0 - 1st strcasestr should catch this too */
     ) {
         return 1;
     }
     return 0;
 }
References NULL, and strcasestr().
Referenced by string_checker().