Fennix: Userspace/apps/base/bash/builtins/mkbuiltins.c File Reference
mkbuiltins.c File Reference
#include <config.h>
#include "../bashtypes.h"
#include "posixstat.h"
#include "filecntl.h"
#include "../bashansi.h"
#include <stdio.h>
#include <errno.h>
#include "stdc.h"
Data Structures
struct ARRAY
struct BUILTIN_DESC
struct DEF_FILE
struct HANDLER_ENTRY
Macros
#define DOCFILE "builtins.texi"
#define savestring(x) strcpy (xmalloc (1 + strlen (x)), (x))
#define whitespace(c) (((c) == ' ') || ((c) == '\t'))
#define BUILTIN_FLAG_SPECIAL 0x01
#define BUILTIN_FLAG_ASSIGNMENT 0x02
#define BUILTIN_FLAG_LOCALVAR 0x04
#define BUILTIN_FLAG_POSIX_BUILTIN 0x08
#define BUILTIN_FLAG_ARRAYREF_ARG 0x10
#define BASE_INDENT 4
#define document_name(b) ((b)->docname ? (b)->docname : (b)->name)
#define free_safely(x) if (x) free (x)
#define STRING_ARRAY 0x01
#define TEXINFO 0x02
#define PLAINTEXT 0x04
#define HELPFILE 0x08
Typedefs
typedef int Function()
typedef int mk_handler_func_t PARAMS((char *, DEF_FILE *, char *))
Functions
static char * xmalloc ()
static char * xrealloc ()
char * strcpy ()
static int is_special_builtin ()
static int is_assignment_builtin ()
static int is_localvar_builtin ()
static int is_posix_builtin ()
static int is_arrayvar_builtin ()
static int rename ()
void extract_info ()
void file_error ()
void line_error ()
void write_file_headers ()
void write_file_footers ()
void write_ifdefs ()
void write_endifs ()
void write_documentation ()
void write_longdocs ()
void write_builtins ()
int write_helpfiles ()
void free_defs ()
void add_documentation ()
void must_be_building ()
void remove_trailing_whitespace ()
int main (int argc, char **argv)
ARRAY * array_create (int width)
ARRAY * copy_string_array (ARRAY *array)
void array_add (char *element, ARRAY *array)
void array_free (ARRAY *array)
HANDLER_ENTRY * find_directive (char *directive)
void extract_info (char *filename, FILE *structfile, FILE *externfile)
static void free_builtin (BUILTIN_DESC *builtin)
void free_defs (DEF_FILE *defs)
char * strip_whitespace (char *string)
void remove_trailing_whitespace (char *string)
char * get_arg (char *for_whom, DEF_FILE *defs, char *string)
void must_be_building (char *directive, DEF_FILE *defs)
BUILTIN_DESC * current_builtin (char *directive, DEF_FILE *defs)
void add_documentation (DEF_FILE *defs, char *line)
int builtin_handler (char *self, DEF_FILE *defs, char *arg)
int function_handler (char *self, DEF_FILE *defs, char *arg)
int docname_handler (char *self, DEF_FILE *defs, char *arg)
int short_doc_handler (char *self, DEF_FILE *defs, char *arg)
int comment_handler (char *self, DEF_FILE *defs, char *arg)
int depends_on_handler (char *self, DEF_FILE *defs, char *arg)
int produces_handler (char *self, DEF_FILE *defs, char *arg)
int end_handler (char *self, DEF_FILE *defs, char *arg)
void line_error (DEF_FILE *defs, char *format, char *arg1, char *arg2)
void file_error (char *filename)
static void memory_error_and_abort ()
static char * xmalloc (int bytes)
static char * xrealloc (char *pointer, int bytes)
BUILTIN_DESC * copy_builtin (BUILTIN_DESC *builtin)
void save_builtin (BUILTIN_DESC *builtin)
void write_file_headers (FILE *structfile, FILE *externfile)
void write_file_footers (FILE *structfile, FILE *externfile)
void write_builtins (DEF_FILE *defs, FILE *structfile, FILE *externfile)
void write_longdocs (FILE *stream, ARRAY *builtins)
void write_dummy_declarations (FILE *stream, ARRAY *builtins)
void write_ifdefs (FILE *stream, char **defines)
void write_endifs (FILE *stream, char **defines)
void write_documentation (FILE *stream, char **documentation, int indentation, int flags)
int write_helpfiles (ARRAY *builtins)
static int _find_in_table (char *name, name_table)
static int is_special_builtin (char *name)
static int is_assignment_builtin (char *name)
static int is_localvar_builtin (char *name)
static int is_posix_builtin (char *name)
static int is_arrayvar_builtin (char *name)
static int rename (char *from, char *to)
Variables
int errno
FILE * documentation_file = (FILE *)NULL
int only_documentation = 0
int inhibit_production = 0
int inhibit_functions = 0
int separate_helpfiles = 0
int single_longdoc_strings = 1
char * helpfile_directory
char * error_directory = (char *)NULL
char * struct_filename = (char *)NULL
char * extern_filename = (char *)NULL
char * include_filename = (char *)NULL
ARRAY * saved_builtins = (ARRAY *)NULL
char * special_builtins []
char * assignment_builtins []
char * localvar_builtins []
char * posix_builtins []
char * arrayvar_builtins []
HANDLER_ENTRY handlers []
static int building_builtin = 0
int output_cpp_line_info = 0
char * structfile_header []
char * structfile_footer []
Data Structure Documentation
ARRAY
struct ARRAY
Definition at line 123 of file mkbuiltins.c.
Data Fields
char ** array
int growth_rate
int sindex
int size
int width
BUILTIN_DESC
struct BUILTIN_DESC
Definition at line 132 of file mkbuiltins.c.
Data Fields
ARRAY * dependencies
char * docname
int flags
char * function
ARRAY * longdoc
char * name
char * shortdoc
DEF_FILE
struct DEF_FILE
Definition at line 143 of file mkbuiltins.c.
Data Fields
ARRAY * builtins
char * filename
int line_number
ARRAY * lines
FILE * output
char * production
HANDLER_ENTRY
struct HANDLER_ENTRY
Definition at line 468 of file mkbuiltins.c.
Data Fields
char * directive
mk_handler_func_t * function
Macro Definition Documentation
BASE_INDENT
#define BASE_INDENT 4
Definition at line 78 of file mkbuiltins.c.
BUILTIN_FLAG_ARRAYREF_ARG
#define BUILTIN_FLAG_ARRAYREF_ARG 0x10
Definition at line 76 of file mkbuiltins.c.
BUILTIN_FLAG_ASSIGNMENT
#define BUILTIN_FLAG_ASSIGNMENT 0x02
Definition at line 73 of file mkbuiltins.c.
BUILTIN_FLAG_LOCALVAR
#define BUILTIN_FLAG_LOCALVAR 0x04
Definition at line 74 of file mkbuiltins.c.
BUILTIN_FLAG_POSIX_BUILTIN
#define BUILTIN_FLAG_POSIX_BUILTIN 0x08
Definition at line 75 of file mkbuiltins.c.
BUILTIN_FLAG_SPECIAL
#define BUILTIN_FLAG_SPECIAL 0x01
Definition at line 72 of file mkbuiltins.c.
DOCFILE
#define DOCFILE "builtins.texi"
Definition at line 56 of file mkbuiltins.c.
document_name
#define document_name (b) ((b)->docname ? (b)->docname : (b)->name)
Definition at line 225 of file mkbuiltins.c.
free_safely
#define free_safely (x) if (x) free (x)
Definition at line 666 of file mkbuiltins.c.
HELPFILE
#define HELPFILE 0x08
Definition at line 1131 of file mkbuiltins.c.
PLAINTEXT
#define PLAINTEXT 0x04
Definition at line 1130 of file mkbuiltins.c.
savestring
#define savestring (x) strcpy (xmalloc (1 + strlen (x)), (x))
Definition at line 68 of file mkbuiltins.c.
STRING_ARRAY
#define STRING_ARRAY 0x01
Definition at line 1128 of file mkbuiltins.c.
TEXINFO
#define TEXINFO 0x02
Definition at line 1129 of file mkbuiltins.c.
whitespace
#define whitespace (c) (((c) == ' ') || ((c) == '\t'))
Definition at line 69 of file mkbuiltins.c.
Typedef Documentation
Function
typedef int Function()
Definition at line 464 of file mkbuiltins.c.
PARAMS
typedef int mk_handler_func_t PARAMS((char *, DEF_FILE *, char *))
Definition at line 465 of file mkbuiltins.c.
Function Documentation
_find_in_table()
static int _find_in_table (char * name, name_table) static
Definition at line 1635 of file mkbuiltins.c.
 {
   register int i;
   for (i = 0; name_table[i]; i++)
     if (strcmp (name, name_table[i]) == 0)
       return 1;
   return 0;
 }
References i, and strcmp.
Referenced by is_arrayvar_builtin(), is_assignment_builtin(), is_localvar_builtin(), is_posix_builtin(), and is_special_builtin().
add_documentation() [1/2]
void add_documentation ()
Referenced by extract_info().
add_documentation() [2/2]
void add_documentation (DEF_FILE * defs, char * line)
Definition at line 795 of file mkbuiltins.c.
 {
   register BUILTIN_DESC *builtin;
   builtin = current_builtin ("(implied LONGDOC)", defs);
   remove_trailing_whitespace (line);
   if (!*line && !builtin->longdoc)
     return;
   if (!builtin->longdoc)
     builtin->longdoc = array_create (sizeof (char *));
   array_add (line, builtin->longdoc);
 }
References array_add(), array_create(), builtin, current_builtin(), and remove_trailing_whitespace().
array_add()
void array_add (char * element, ARRAY * array)
Definition at line 434 of file mkbuiltins.c.
 {
   if (array->sindex + 2 > array->size)
     array->array = (char **)xrealloc
       (array->array, (array->size += array->growth_rate) * array->width);
   array->array[array->sindex++] = element;
   array->array[array->sindex] = (char *)NULL;
 }
References NULL, and xrealloc().
Referenced by add_documentation(), builtin_handler(), depends_on_handler(), extract_info(), and save_builtin().
array_create()
ARRAY* array_create (int width)
Definition at line 387 of file mkbuiltins.c.
 {
   ARRAY *array;
   array = (ARRAY *)xmalloc (sizeof (ARRAY));
   array->size = 0;
   array->sindex = 0;
   array->width = width;
   /* Default to increasing size in units of 20. */
   array->growth_rate = 20;
   array->array = (char **)NULL;
   return (array);
 }
References NULL, width, and xmalloc().
Referenced by add_documentation(), builtin_handler(), copy_string_array(), depends_on_handler(), extract_info(), and save_builtin().
array_free()
void array_free (ARRAY * array)
Definition at line 448 of file mkbuiltins.c.
 {
   if (array->array)
     free (array->array);
   free (array);
 }
References free.
Referenced by free_builtin(), and free_defs().
builtin_handler()
int builtin_handler (char * self, DEF_FILE * defs, char * arg)
Definition at line 816 of file mkbuiltins.c.
 {
   BUILTIN_DESC *new;
   char *name;
   /* If we are already building a builtin, we cannot start a new one. */
   if (building_builtin)
     {
       line_error (defs, "%s found before $END", self);
       return (-1);
     }
   output_cpp_line_info++;
   /* Get the name of this builtin, and stick it in the array. */
   name = get_arg (self, defs, arg);
   /* If this is the first builtin, create the array to hold them. */
   if (!defs->builtins)
     defs->builtins = array_create (sizeof (BUILTIN_DESC *));
   new = (BUILTIN_DESC *)xmalloc (sizeof (BUILTIN_DESC));
   new->name = name;
   new->function = (char *)NULL;
   new->shortdoc = (char *)NULL;
   new->docname = (char *)NULL;
   new->longdoc = (ARRAY *)NULL;
   new->dependencies = (ARRAY *)NULL;
   new->flags = 0;
   if (is_special_builtin (name))
     new->flags |= BUILTIN_FLAG_SPECIAL;
   if (is_assignment_builtin (name))
     new->flags |= BUILTIN_FLAG_ASSIGNMENT;
   if (is_localvar_builtin (name))
     new->flags |= BUILTIN_FLAG_LOCALVAR;
   if (is_posix_builtin (name))
     new->flags |= BUILTIN_FLAG_POSIX_BUILTIN;
   if (is_arrayvar_builtin (name))
     new->flags |= BUILTIN_FLAG_ARRAYREF_ARG;
   array_add ((char *)new, defs->builtins);
   building_builtin = 1;
   return (0);
 }
References array_add(), array_create(), building_builtin, BUILTIN_FLAG_ARRAYREF_ARG, BUILTIN_FLAG_ASSIGNMENT, BUILTIN_FLAG_LOCALVAR, BUILTIN_FLAG_POSIX_BUILTIN, BUILTIN_FLAG_SPECIAL, DEF_FILE::builtins, get_arg(), if(), is_arrayvar_builtin(), is_assignment_builtin(), is_localvar_builtin(), is_posix_builtin(), is_special_builtin(), line_error(), NULL, output_cpp_line_info, and xmalloc().
comment_handler()
int comment_handler (char * self, DEF_FILE * defs, char * arg)
Definition at line 933 of file mkbuiltins.c.
 {
   return (0);
 }
copy_builtin()
BUILTIN_DESC* copy_builtin (BUILTIN_DESC * builtin)
Definition at line 1090 of file mkbuiltins.c.
 {
   BUILTIN_DESC *new;
   new = (BUILTIN_DESC *)xmalloc (sizeof (BUILTIN_DESC));
   new->name = savestring (builtin->name);
   new->shortdoc = savestring (builtin->shortdoc);
   new->longdoc = copy_string_array (builtin->longdoc);
   new->dependencies = copy_string_array (builtin->dependencies);
   new->function =
     builtin->function ? savestring (builtin->function) : (char *)NULL;
   new->docname =
     builtin->docname  ? savestring (builtin->docname)  : (char *)NULL;
   return (new);
 }
References copy_string_array(), builtin::function, builtin::name, NULL, savestring, and xmalloc().
Referenced by save_builtin().
copy_string_array()
ARRAY* copy_string_array (ARRAY * array)
Definition at line 407 of file mkbuiltins.c.
 {
   register int i;
   ARRAY *copy;
   if (!array)
     return (ARRAY *)NULL;
   copy = array_create (sizeof (char *));
   copy->size = array->size;
   copy->sindex = array->sindex;
   copy->width = array->width;
   copy->array = (char **)xmalloc ((1 + array->sindex) * sizeof (char *));
   for (i = 0; i < array->sindex; i++)
     copy->array[i] = savestring (array->array[i]);
   copy->array[i] = (char *)NULL;
   return (copy);
 }
References ARRAY::array, array_create(), i, NULL, savestring, ARRAY::sindex, ARRAY::size, ARRAY::width, and xmalloc().
Referenced by copy_builtin().
current_builtin()
BUILTIN_DESC* current_builtin (char * directive, DEF_FILE * defs)
Definition at line 781 of file mkbuiltins.c.
 {
   must_be_building (directive, defs);
   if (defs->builtins)
     return ((BUILTIN_DESC *)defs->builtins->array[defs->builtins->sindex - 1]);
   else
     return ((BUILTIN_DESC *)NULL);
 }
References ARRAY::array, DEF_FILE::builtins, must_be_building(), NULL, and ARRAY::sindex.
Referenced by add_documentation(), depends_on_handler(), docname_handler(), function_handler(), and short_doc_handler().
depends_on_handler()
int depends_on_handler (char * self, DEF_FILE * defs, char * arg)
Definition at line 943 of file mkbuiltins.c.
 {
   register BUILTIN_DESC *builtin;
   char *dependent;
   builtin = current_builtin (self, defs);
   dependent = get_arg (self, defs, arg);
   if (!builtin->dependencies)
     builtin->dependencies = array_create (sizeof (char *));
   array_add (dependent, builtin->dependencies);
   return (0);
 }
References array_add(), array_create(), builtin, current_builtin(), and get_arg().
docname_handler()
int docname_handler (char * self, DEF_FILE * defs, char * arg)
Definition at line 893 of file mkbuiltins.c.
 {
   register BUILTIN_DESC *builtin;
   builtin = current_builtin (self, defs);
   if (builtin->docname)
     line_error (defs, "%s already had a docname (%s)",
         builtin->name, builtin->docname);
   else
     builtin->docname = get_arg (self, defs, arg);
   return (0);
 }
References builtin, current_builtin(), get_arg(), line_error(), and builtin::name.
end_handler()
int end_handler (char * self, DEF_FILE * defs, char * arg)
Definition at line 998 of file mkbuiltins.c.
 {
   must_be_building (self, defs);
   building_builtin = 0;
   return (0);
 }
References building_builtin, and must_be_building().
extract_info() [1/2]
void extract_info ()
Referenced by main().
extract_info() [2/2]
void extract_info (char * filename, FILE * structfile, FILE * externfile)
Definition at line 527 of file mkbuiltins.c.
 {
   register int i;
   DEF_FILE *defs;
   struct stat finfo;
   size_t file_size;
   char *buffer, *line;
   int fd, nr;
   if (stat (filename, &finfo) == -1)
     file_error (filename);
   fd = open (filename, O_RDONLY, 0666);
   if (fd == -1)
     file_error (filename);
   file_size = (size_t)finfo.st_size;
   buffer = xmalloc (1 + file_size);
   if ((nr = read (fd, buffer, file_size)) < 0)
     file_error (filename);
   /* This is needed on WIN32, and does not hurt on Unix. */
   if (nr < file_size)
     file_size = nr;
   close (fd);
   if (nr == 0)
     {
       fprintf (stderr, "mkbuiltins: %s: skipping zero-length file\n", filename);
       free (buffer);
       return;
     }
   /* Create and fill in the initial structure describing this file. */
   defs = (DEF_FILE *)xmalloc (sizeof (DEF_FILE));
   defs->filename = filename;
   defs->lines = array_create (sizeof (char *));
   defs->line_number = 0;
   defs->production = (char *)NULL;
   defs->output = (FILE *)NULL;
   defs->builtins = (ARRAY *)NULL;
   /* Build the array of lines. */
   i = 0;
   while (i < file_size)
     {
       array_add (&buffer[i], defs->lines);
       while (i < file_size && buffer[i] != '\n')
     i++;
       buffer[i++] = '\0';
     }
   /* Begin processing the input file.  We don't write any output
      until we have a file to write output to. */
   output_cpp_line_info = 1;
   /* Process each line in the array. */
   for (i = 0; line = defs->lines->array[i]; i++)
     {
       defs->line_number = i;
       if (*line == '$')
     {
       register int j;
       char *directive;
       HANDLER_ENTRY *handler;
       /* Isolate the directive. */
       for (j = 0; line[j] && !whitespace (line[j]); j++);
       directive = xmalloc (j);
       strncpy (directive, line + 1, j - 1);
       directive[j -1] = '\0';
       /* Get the function handler and call it. */
       handler = find_directive (directive);
       if (!handler)
         {
           line_error (defs, "Unknown directive `%s'", directive);
           free (directive);
           continue;
         }
       else
         {
           /* Advance to the first non-whitespace character. */
           while (whitespace (line[j]))
         j++;
           /* Call the directive handler with the FILE, and ARGS. */
           (*(handler->function)) (directive, defs, line + j);
         }
       free (directive);
     }
       else
     {
       if (building_builtin)
         add_documentation (defs, line);
       else if (defs->output)
         {
           if (output_cpp_line_info)
         {
           /* If we're handed an absolute pathname, don't prepend
              the directory name. */
           if (defs->filename[0] == '/')
             fprintf (defs->output, "#line %d \"%s\"\n",
                  defs->line_number + 1, defs->filename);
           else
             fprintf (defs->output, "#line %d \"%s%s\"\n",
                  defs->line_number + 1,
                  error_directory ? error_directory : "./",
                  defs->filename);
           output_cpp_line_info = 0;
         }
           fprintf (defs->output, "%s\n", line);
         }
     }
     }
   /* Close the production file. */
   if (defs->output)
     fclose (defs->output);
   /* The file has been processed.  Write the accumulated builtins to
      the builtins.c file, and write the extern definitions to the
      builtext.h file. */
   write_builtins (defs, structfile, externfile);
   free (buffer);
   free_defs (defs);
 }
References add_documentation(), ARRAY::array, array_add(), array_create(), buffer, building_builtin, DEF_FILE::builtins, close(), error_directory, fclose(), fd, file_error(), file_size, DEF_FILE::filename, filename, find_directive(), fprintf(), free, free_defs(), handler(), i, j, line, line_error(), DEF_FILE::line_number, DEF_FILE::lines, NULL, O_RDONLY, open(), DEF_FILE::output, output_cpp_line_info, DEF_FILE::production, read(), stat::st_size, stderr, strncpy(), whitespace, write_builtins(), and xmalloc().
file_error() [1/2]
void file_error ()
Referenced by _evalfile(), cutfile(), extract_info(), main(), open_redir_file(), open_shell_script(), produces_handler(), and shell_execve().
file_error() [2/2]
void file_error (char * filename)
Definition at line 1030 of file mkbuiltins.c.
 {
   perror (filename);
   exit (2);
 }
References exit(), filename, and perror().
find_directive()
HANDLER_ENTRY* find_directive (char * directive)
Definition at line 497 of file mkbuiltins.c.
 {
   register int i;
   for (i = 0; handlers[i].directive; i++)
     if (strcmp (handlers[i].directive, directive) == 0)
       return (&handlers[i]);
   return ((HANDLER_ENTRY *)NULL);
 }
References HANDLER_ENTRY::directive, handlers, i, NULL, and strcmp.
Referenced by extract_info().
free_builtin()
static void free_builtin (BUILTIN_DESC * builtin) static
Definition at line 669 of file mkbuiltins.c.
 {
   register int i;
   free_safely (builtin->name);
   free_safely (builtin->function);
   free_safely (builtin->shortdoc);
   free_safely (builtin->docname);
   if (builtin->longdoc)
     array_free (builtin->longdoc);
   if (builtin->dependencies)
     {
       for (i = 0; builtin->dependencies->array[i]; i++)
     free (builtin->dependencies->array[i]);
       array_free (builtin->dependencies);
     }
 }
References array_free(), free, free_safely, builtin::function, i, and builtin::name.
Referenced by free_defs().
free_defs() [1/2]
void free_defs ()
Referenced by extract_info().
free_defs() [2/2]
void free_defs (DEF_FILE * defs)
Definition at line 692 of file mkbuiltins.c.
 {
   register int i;
   register BUILTIN_DESC *builtin;
   if (defs->production)
     free (defs->production);
   if (defs->lines)
     array_free (defs->lines);
   if (defs->builtins)
     {
       for (i = 0; builtin = (BUILTIN_DESC *)defs->builtins->array[i]; i++)
     {
       free_builtin (builtin);
       free (builtin);
     }
       array_free (defs->builtins);
     }
   free (defs);
 }
References ARRAY::array, array_free(), builtin, DEF_FILE::builtins, free, free_builtin(), i, DEF_FILE::lines, and DEF_FILE::production.
function_handler()
int function_handler (char * self, DEF_FILE * defs, char * arg)
Definition at line 868 of file mkbuiltins.c.
 {
   register BUILTIN_DESC *builtin;
   builtin = current_builtin (self, defs);
   if (builtin == 0)
     {
       line_error (defs, "syntax error: no current builtin for $FUNCTION directive");
       exit (1);
     }
   if (builtin->function)
     line_error (defs, "%s already has a function (%s)",
         builtin->name, builtin->function);
   else
     builtin->function = get_arg (self, defs, arg);
   return (0);
 }
References builtin, current_builtin(), exit(), builtin::function, get_arg(), line_error(), and builtin::name.
get_arg()
char* get_arg (char * for_whom, DEF_FILE * defs, char * string)
Definition at line 755 of file mkbuiltins.c.
 {
   char *new;
   new = strip_whitespace (string);
   if (!*new)
     line_error (defs, "%s requires an argument", for_whom);
   return (savestring (new));
 }
References line_error(), savestring, and strip_whitespace().
Referenced by builtin_handler(), depends_on_handler(), docname_handler(), function_handler(), produces_handler(), and short_doc_handler().
is_arrayvar_builtin() [1/2]
static int is_arrayvar_builtin () static
Referenced by builtin_handler().
is_arrayvar_builtin() [2/2]
static int is_arrayvar_builtin (char * name) static
Definition at line 1675 of file mkbuiltins.c.
 {
   return (_find_in_table (name, arrayvar_builtins));
 }
References _find_in_table(), and arrayvar_builtins.
is_assignment_builtin() [1/2]
static int is_assignment_builtin () static
Referenced by builtin_handler().
is_assignment_builtin() [2/2]
static int is_assignment_builtin (char * name) static
Definition at line 1654 of file mkbuiltins.c.
 {
   return (_find_in_table (name, assignment_builtins));
 }
References _find_in_table(), and assignment_builtins.
is_localvar_builtin() [1/2]
static int is_localvar_builtin () static
Referenced by builtin_handler().
is_localvar_builtin() [2/2]
static int is_localvar_builtin (char * name) static
Definition at line 1661 of file mkbuiltins.c.
 {
   return (_find_in_table (name, localvar_builtins));
 }
References _find_in_table(), and localvar_builtins.
is_posix_builtin() [1/2]
static int is_posix_builtin () static
Referenced by builtin_handler().
is_posix_builtin() [2/2]
static int is_posix_builtin (char * name) static
Definition at line 1668 of file mkbuiltins.c.
 {
   return (_find_in_table (name, posix_builtins));
 }
References _find_in_table(), and posix_builtins.
is_special_builtin() [1/2]
static int is_special_builtin () static
Referenced by builtin_handler(), and do_assignment_statements().
is_special_builtin() [2/2]
static int is_special_builtin (char * name) static
Definition at line 1647 of file mkbuiltins.c.
 {
   return (_find_in_table (name, special_builtins));
 }
References _find_in_table(), and special_builtins.
line_error() [1/2]
void line_error ()
Referenced by builtin_handler(), docname_handler(), extract_info(), function_handler(), get_arg(), must_be_building(), produces_handler(), and short_doc_handler().
line_error() [2/2]
void line_error (DEF_FILE * defs, char * format, char * arg1, char * arg2)
Definition at line 1016 of file mkbuiltins.c.
 {
   if (defs->filename[0] != '/')
     fprintf (stderr, "%s", error_directory ? error_directory : "./");
   fprintf (stderr, "%s:%d:", defs->filename, defs->line_number + 1);
   fprintf (stderr, format, arg1, arg2);
   fprintf (stderr, "\n");
   fflush (stderr);
 }
References error_directory, fflush(), DEF_FILE::filename, format(), fprintf(), DEF_FILE::line_number, and stderr.
main()
int main (int argc , char ** argv)
Definition at line 232 of file mkbuiltins.c.
 {
   int arg_index = 1;
   FILE *structfile, *externfile;
   char *documentation_filename, *temp_struct_filename;
   structfile = externfile = (FILE *)NULL;
   documentation_filename = DOCFILE;
   temp_struct_filename = (char *)NULL;
   while (arg_index < argc && argv[arg_index][0] == '-')
     {
       char *arg = argv[arg_index++];
       if (strcmp (arg, "-externfile") == 0)
     extern_filename = argv[arg_index++];
       else if (strcmp (arg, "-includefile") == 0)
     include_filename = argv[arg_index++];
       else if (strcmp (arg, "-structfile") == 0)
     struct_filename = argv[arg_index++];
       else if (strcmp (arg, "-noproduction") == 0)
     inhibit_production = 1;
       else if (strcmp (arg, "-nofunctions") == 0)
     inhibit_functions = 1;
       else if (strcmp (arg, "-document") == 0)
     documentation_file = fopen (documentation_filename, "w");
       else if (strcmp (arg, "-D") == 0)
     {
       int len;
       if (error_directory)
         free (error_directory);
       error_directory = xmalloc (2 + strlen (argv[arg_index]));
       strcpy (error_directory, argv[arg_index]);
       len = strlen (error_directory);
       if (len && error_directory[len - 1] != '/')
         strcat (error_directory, "/");
       arg_index++;
     }
       else if (strcmp (arg, "-documentonly") == 0)
     {
       only_documentation = 1;
       documentation_file = fopen (documentation_filename, "w");
     }
       else if (strcmp (arg, "-H") == 0)
         {
       separate_helpfiles = 1;
       helpfile_directory = argv[arg_index++];
         }
       else if (strcmp (arg, "-S") == 0)
     single_longdoc_strings = 0;
       else
     {
       fprintf (stderr, "%s: Unknown flag %s.\n", argv[0], arg);
       exit (2);
     }
     }
   if (include_filename == 0)
     include_filename = extern_filename;
   /* If there are no files to process, just quit now. */
   if (arg_index == argc)
     exit (0);
   if (!only_documentation)
     {
       /* Open the files. */
       if (struct_filename)
     {
       temp_struct_filename = xmalloc (15);
       sprintf (temp_struct_filename, "mk-%ld", (long) getpid ());
       structfile = fopen (temp_struct_filename, "w");
       if (!structfile)
         file_error (temp_struct_filename);
     }
       if (extern_filename)
     {
       externfile = fopen (extern_filename, "w");
       if (!externfile)
         file_error (extern_filename);
     }
       /* Write out the headers. */
       write_file_headers (structfile, externfile);
     }
   if (documentation_file)
     {
       fprintf (documentation_file, "@c Table of builtins created with %s.\n",
            argv[0]);
       fprintf (documentation_file, "@ftable @asis\n");
     }
   /* Process the .def files. */
   while (arg_index < argc)
     {
       register char *arg;
       arg = argv[arg_index++];
       extract_info (arg, structfile, externfile);
     }
   /* Close the files. */
   if (!only_documentation)
     {
       /* Write the footers. */
       write_file_footers (structfile, externfile);
       if (structfile)
     {
       write_longdocs (structfile, saved_builtins);
       fclose (structfile);
       rename (temp_struct_filename, struct_filename);
     }
       if (externfile)
     fclose (externfile);
     }
 #if 0
   /* This is now done by a different program */
   if (separate_helpfiles)
     {
       write_helpfiles (saved_builtins);
     }
 #endif
   if (documentation_file)
     {
       fprintf (documentation_file, "@end ftable\n");
       fclose (documentation_file);
     }
   exit (0);
 }
References argc, argv, DOCFILE, documentation_file, error_directory, exit(), extern_filename, extract_info(), fclose(), file_error(), fopen(), fprintf(), free, getpid(), helpfile_directory, include_filename, inhibit_functions, inhibit_production, len, NULL, only_documentation, rename(), saved_builtins, separate_helpfiles, single_longdoc_strings, sprintf(), stderr, strcat, strcmp, strcpy(), strlen(), struct_filename, write_file_footers(), write_file_headers(), write_helpfiles(), write_longdocs(), and xmalloc().
memory_error_and_abort()
static void memory_error_and_abort () static
Definition at line 1075 of file mkbuiltins.c.
 {
   fprintf (stderr, "mkbuiltins: out of virtual memory\n");
   abort ();
 }
References abort(), fprintf(), and stderr.
Referenced by xmalloc(), and xrealloc().
must_be_building() [1/2]
void must_be_building ()
Referenced by current_builtin(), and end_handler().
must_be_building() [2/2]
void must_be_building (char * directive, DEF_FILE * defs)
Definition at line 771 of file mkbuiltins.c.
 {
   if (!building_builtin)
     line_error (defs, "%s must be inside of a $BUILTIN block", directive);
 }
References building_builtin, and line_error().
produces_handler()
int produces_handler (char * self, DEF_FILE * defs, char * arg)
Definition at line 964 of file mkbuiltins.c.
 {
   /* If just hacking documentation, don't change any of the production
      files. */
   if (only_documentation)
     return (0);
   output_cpp_line_info++;
   if (defs->production)
     line_error (defs, "%s already has a %s definition", defs->filename, self);
   else
     {
       defs->production = get_arg (self, defs, arg);
       if (inhibit_production)
     return (0);
       defs->output = fopen (defs->production, "w");
       if (!defs->output)
     file_error (defs->production);
       fprintf (defs->output, "/* %s, created from %s. */\n",
            defs->production, defs->filename);
     }
   return (0);
 }
References file_error(), DEF_FILE::filename, fopen(), fprintf(), get_arg(), inhibit_production, line_error(), only_documentation, DEF_FILE::output, output_cpp_line_info, and DEF_FILE::production.
remove_trailing_whitespace() [1/2]
void remove_trailing_whitespace ()
Referenced by add_documentation(), and strip_whitespace().
remove_trailing_whitespace() [2/2]
void remove_trailing_whitespace (char * string)
Definition at line 737 of file mkbuiltins.c.
 {
   register int i;
   i = strlen (string) - 1;
   while (i > 0 && whitespace (string[i]))
     i--;
   string[++i] = '\0';
 }
References i, strlen(), and whitespace.
rename() [1/2]
static int rename () static
Referenced by conf_write(), file_write_dep(), finish_oldfile(), G_DoSaveGame(), history_rename(), ln_main(), log_locally(), logdir_open(), main(), mv_main(), processorstop(), remove_package(), rename_or_warn(), replace_tempfile(), rotate(), update_passwd(), write_status_file(), and xrename().
rename() [2/2]
static int rename (char * from, char * to) static
Definition at line 1683 of file mkbuiltins.c.
 {
   unlink (to);
   if (link (from, to) < 0)
     return (-1);
   unlink (from);
   return (0);
 }
References link(), and unlink().
save_builtin()
void save_builtin (BUILTIN_DESC * builtin)
Definition at line 1112 of file mkbuiltins.c.
 {
   BUILTIN_DESC *newbuiltin;
   newbuiltin = copy_builtin (builtin);
   /* If this is the first builtin to be saved, create the array
      to hold it. */
   if (!saved_builtins)
       saved_builtins = array_create (sizeof (BUILTIN_DESC *));
   array_add ((char *)newbuiltin, saved_builtins);
 }
References array_add(), array_create(), copy_builtin(), and saved_builtins.
Referenced by write_builtins().
short_doc_handler()
int short_doc_handler (char * self, DEF_FILE * defs, char * arg)
Definition at line 913 of file mkbuiltins.c.
 {
   register BUILTIN_DESC *builtin;
   builtin = current_builtin (self, defs);
   if (builtin->shortdoc)
     line_error (defs, "%s already has short documentation (%s)",
         builtin->name, builtin->shortdoc);
   else
     builtin->shortdoc = get_arg (self, defs, arg);
   return (0);
 }
References builtin, current_builtin(), get_arg(), line_error(), and builtin::name.
strcpy()
char* strcpy ()
Referenced by main().
strip_whitespace()
char* strip_whitespace (char * string)
Definition at line 725 of file mkbuiltins.c.
 {
   while (whitespace (*string))
       string++;
   remove_trailing_whitespace (string);
   return (string);
 }
References remove_trailing_whitespace(), and whitespace.
Referenced by get_arg().
write_builtins() [1/2]
void write_builtins ()
Referenced by extract_info().
write_builtins() [2/2]
void write_builtins (DEF_FILE * defs, FILE * structfile, FILE * externfile)
Definition at line 1233 of file mkbuiltins.c.
 {
   register int i;
   /* Write out the information. */
   if (defs->builtins)
     {
       register BUILTIN_DESC *builtin;
       for (i = 0; i < defs->builtins->sindex; i++)
     {
       builtin = (BUILTIN_DESC *)defs->builtins->array[i];
       /* Write out any #ifdefs that may be there. */
       if (!only_documentation)
         {
           if (builtin->dependencies)
         {
           write_ifdefs (externfile, builtin->dependencies->array);
           write_ifdefs (structfile, builtin->dependencies->array);
         }
           /* Write the extern definition. */
           if (externfile)
         {
           if (builtin->function)
             fprintf (externfile, "extern int %s PARAMS((WORD_LIST *));\n",
                  builtin->function);
           fprintf (externfile, "extern char * const %s_doc[];\n",
                document_name (builtin));
         }
           /* Write the structure definition. */
           if (structfile)
         {
           fprintf (structfile, "  { \"%s\", ", builtin->name);
           if (builtin->function && inhibit_functions == 0)
             fprintf (structfile, "%s, ", builtin->function);
           else
             fprintf (structfile, "(sh_builtin_func_t *)0x0, ");
           fprintf (structfile, "%s%s%s%s%s%s, %s_doc,\n",
             "BUILTIN_ENABLED | STATIC_BUILTIN",
             (builtin->flags & BUILTIN_FLAG_SPECIAL) ? " | SPECIAL_BUILTIN" : "",
             (builtin->flags & BUILTIN_FLAG_ASSIGNMENT) ? " | ASSIGNMENT_BUILTIN" : "",
             (builtin->flags & BUILTIN_FLAG_LOCALVAR) ? " | LOCALVAR_BUILTIN" : "",
             (builtin->flags & BUILTIN_FLAG_POSIX_BUILTIN) ? " | POSIX_BUILTIN" : "",
             (builtin->flags & BUILTIN_FLAG_ARRAYREF_ARG) ? " | ARRAYREF_BUILTIN" : "",
             document_name (builtin));
           /* Don't translate short document summaries that are identical
              to command names */
           if (builtin->shortdoc && strcmp (builtin->name, builtin->shortdoc) == 0)
             {
               if (inhibit_functions)
             fprintf (structfile, "     \"%s\", \"%s\" },\n",
               builtin->shortdoc ? builtin->shortdoc : builtin->name,
               document_name (builtin));
               else
             fprintf (structfile, "     \"%s\", (char *)NULL },\n",
               builtin->shortdoc ? builtin->shortdoc : builtin->name);
             }
           else
             {
               if (inhibit_functions)
             fprintf (structfile, "     N_(\"%s\"), \"%s\" },\n",
               builtin->shortdoc ? builtin->shortdoc : builtin->name,
               document_name (builtin));
               else
             fprintf (structfile, "     N_(\"%s\"), (char *)NULL },\n",
               builtin->shortdoc ? builtin->shortdoc : builtin->name);
             }
         }
           if (structfile || separate_helpfiles)
         /* Save away this builtin for later writing of the
            long documentation strings. */
         save_builtin (builtin);
           /* Write out the matching #endif, if necessary. */
           if (builtin->dependencies)
         {
           if (externfile)
             write_endifs (externfile, builtin->dependencies->array);
           if (structfile)
             write_endifs (structfile, builtin->dependencies->array);
         }
         }
       if (documentation_file)
         {
           fprintf (documentation_file, "@item %s\n", builtin->name);
           write_documentation
         (documentation_file, builtin->longdoc->array, 0, TEXINFO);
         }
     }
     }
 }
References ARRAY::array, builtin, BUILTIN_FLAG_ARRAYREF_ARG, BUILTIN_FLAG_ASSIGNMENT, BUILTIN_FLAG_LOCALVAR, BUILTIN_FLAG_POSIX_BUILTIN, BUILTIN_FLAG_SPECIAL, DEF_FILE::builtins, document_name, documentation_file, builtin::flags, fprintf(), builtin::function, i, if(), inhibit_functions, builtin::name, only_documentation, save_builtin(), separate_helpfiles, ARRAY::sindex, strcmp, TEXINFO, write_documentation(), write_endifs(), and write_ifdefs().
write_documentation() [1/2]
void write_documentation ()
Referenced by write_builtins(), write_helpfiles(), and write_longdocs().
write_documentation() [2/2]
void write_documentation (FILE * stream, char ** documentation, int indentation, int flags)
Definition at line 1462 of file mkbuiltins.c.
 {
   register int i, j;
   register char *line;
   int string_array, texinfo, base_indent, filename_p;
   if (stream == 0)
     return;
   string_array = flags & STRING_ARRAY;
   filename_p = flags & HELPFILE;
   if (string_array)
     {
       fprintf (stream, " {\n#if defined (HELP_BUILTIN)\n"); /* } */
       if (single_longdoc_strings)
     {
       if (filename_p == 0)
         {
           if (documentation && documentation[0] && documentation[0][0])
         fprintf (stream,  "N_(\"");
           else
         fprintf (stream, "N_(\" ");     /* the empty string translates specially. */
         }
       else
         fprintf (stream, "\"");
     }
     }
   base_indent = (string_array && single_longdoc_strings && filename_p == 0) ? BASE_INDENT : 0;
   for (i = 0, texinfo = (flags & TEXINFO); documentation && (line = documentation[i]); i++)
     {
       /* Allow #ifdef's to be written out verbatim, but don't put them into
      separate help files. */
       if (*line == '#')
     {
       if (string_array && filename_p == 0 && single_longdoc_strings == 0)
         fprintf (stream, "%s\n", line);
       continue;
     }
       /* prefix with N_( for gettext */
       if (string_array && single_longdoc_strings == 0)
     {
       if (filename_p == 0)
         {
           if (line[0])
         fprintf (stream, "  N_(\"");
           else
         fprintf (stream, "  N_(\" ");       /* the empty string translates specially. */
         }
       else
         fprintf (stream, "  \"");
     }
       if (indentation)
     for (j = 0; j < indentation; j++)
       fprintf (stream, " ");
       /* Don't indent the first line, because of how the help builtin works. */
       if (i == 0)
     indentation += base_indent;
       if (string_array)
     {
       for (j = 0; line[j]; j++)
         {
           switch (line[j])
         {
         case '\\':
         case '"':
           fprintf (stream, "\\%c", line[j]);
           break;
         default:
           fprintf (stream, "%c", line[j]);
         }
         }
       /* closing right paren for gettext */
       if (single_longdoc_strings == 0)
         {
           if (filename_p == 0)
         fprintf (stream, "\"),\n");
           else
         fprintf (stream, "\",\n");
         }
       else if (documentation[i+1])
         /* don't add extra newline after last line */
         fprintf (stream, "\\n\\\n");
     }
       else if (texinfo)
     {
       for (j = 0; line[j]; j++)
         {
           switch (line[j])
         {
         case '@':
         case '{':
         case '}':
           fprintf (stream, "@%c", line[j]);
           break;
         default:
           fprintf (stream, "%c", line[j]);
         }
         }
       fprintf (stream, "\n");
     }
       else
     fprintf (stream, "%s\n", line);
     }
   /* closing right paren for gettext */
   if (string_array && single_longdoc_strings)
     {
       if (filename_p == 0)
     fprintf (stream, "\"),\n");
       else
     fprintf (stream, "\",\n");
     }
   if (string_array)
     fprintf (stream, "#endif /* HELP_BUILTIN */\n  (char *)NULL\n};\n");
 }
References BASE_INDENT, flags, fprintf(), HELPFILE, i, indentation, j, line, single_longdoc_strings, STRING_ARRAY, and TEXINFO.
write_dummy_declarations()
void write_dummy_declarations (FILE * stream, ARRAY * builtins)
Definition at line 1378 of file mkbuiltins.c.
 {
   register int i;
   BUILTIN_DESC *builtin;
   for (i = 0; structfile_header[i]; i++)
     fprintf (stream, "%s\n", structfile_header[i]);
   for (i = 0; i < builtins->sindex; i++)
     {
       builtin = (BUILTIN_DESC *)builtins->array[i];
       /* How to guarantee that no builtin is written more than once? */
       fprintf (stream, "int %s () { return (0); }\n", builtin->function);
     }
 }
References ARRAY::array, builtin, fprintf(), builtin::function, i, ARRAY::sindex, and structfile_header.
write_endifs() [1/2]
void write_endifs ()
Referenced by write_builtins(), and write_longdocs().
write_endifs() [2/2]
void write_endifs (FILE * stream, char ** defines)
Definition at line 1435 of file mkbuiltins.c.
 {
   register int i;
   if (!stream)
     return;
   fprintf (stream, "#endif /* ");
   for (i = 0; defines[i]; i++)
     {
       fprintf (stream, "%s", defines[i]);
       if (defines[i + 1])
     fprintf (stream, " && ");
     }
   fprintf (stream, " */\n");
 }
References fprintf(), and i.
write_file_footers() [1/2]
void write_file_footers ()
Referenced by main().
write_file_footers() [2/2]
void write_file_footers (FILE * structfile, FILE * externfile)
Definition at line 1217 of file mkbuiltins.c.
 {
   register int i;
   /* Write out the footers. */
   if (structfile)
     {
       for (i = 0; structfile_footer[i]; i++)
     fprintf (structfile, "%s\n", structfile_footer[i]);
     }
 }
References fprintf(), i, and structfile_footer.
write_file_headers() [1/2]
void write_file_headers ()
Referenced by main().
write_file_headers() [2/2]
void write_file_headers (FILE * structfile, FILE * externfile)
Definition at line 1190 of file mkbuiltins.c.
 {
   register int i;
   if (structfile)
     {
       for (i = 0; structfile_header[i]; i++)
     fprintf (structfile, "%s\n", structfile_header[i]);
       fprintf (structfile, "#include \"%s\"\n",
            include_filename ? include_filename : "builtext.h");
       fprintf (structfile, "#include \"bashintl.h\"\n");
       fprintf (structfile, "\nstruct builtin static_shell_builtins[] = {\n");
     }
   if (externfile)
     fprintf (externfile,
          "/* %s - The list of builtins found in libbuiltins.a. */\n",
          include_filename ? include_filename : "builtext.h");
 }
References fprintf(), i, include_filename, and structfile_header.
write_helpfiles() [1/2]
int write_helpfiles ()
Referenced by main().
write_helpfiles() [2/2]
int write_helpfiles (ARRAY * builtins)
Definition at line 1593 of file mkbuiltins.c.
 {
   char *helpfile, *bname;
   FILE *helpfp;
   int i, hdlen;
   BUILTIN_DESC *builtin;
   i = mkdir ("helpfiles", 0777);
   if (i < 0 && errno != EEXIST)
     {
       fprintf (stderr, "write_helpfiles: helpfiles: cannot create directory\n");
       return -1;
     }
   hdlen = strlen ("helpfiles/");
   for (i = 0; i < builtins->sindex; i++)
     {
       builtin = (BUILTIN_DESC *)builtins->array[i];
       bname = document_name (builtin);
       helpfile = (char *)xmalloc (hdlen + strlen (bname) + 1);
       sprintf (helpfile, "helpfiles/%s", bname);
       helpfp = fopen (helpfile, "w");
       if (helpfp == 0)
     {
       fprintf (stderr, "write_helpfiles: cannot open %s\n", helpfile);
       free (helpfile);
       continue;
     }
       write_documentation (helpfp, builtin->longdoc->array, 4, PLAINTEXT);
       fflush (helpfp);
       fclose (helpfp);
       free (helpfile);
     }
   return 0;
 }
References ARRAY::array, builtin, document_name, EEXIST, errno, fclose(), fflush(), fopen(), fprintf(), free, i, mkdir(), PLAINTEXT, ARRAY::sindex, sprintf(), stderr, strlen(), write_documentation(), and xmalloc().
write_ifdefs() [1/2]
void write_ifdefs ()
Referenced by write_builtins(), and write_longdocs().
write_ifdefs() [2/2]
void write_ifdefs (FILE * stream, char ** defines)
Definition at line 1404 of file mkbuiltins.c.
 {
   register int i;
   if (!stream)
     return;
   fprintf (stream, "#if ");
   for (i = 0; defines[i]; i++)
     {
       char *def = defines[i];
       if (*def == '!')
     fprintf (stream, "!defined (%s)", def + 1);
       else
     fprintf (stream, "defined (%s)", def);
       if (defines[i + 1])
     fprintf (stream, " && ");
     }
   fprintf (stream, "\n");
 }
References fprintf(), and i.
write_longdocs() [1/2]
void write_longdocs ()
Referenced by main().
write_longdocs() [2/2]
void write_longdocs (FILE * stream, ARRAY * builtins)
Definition at line 1339 of file mkbuiltins.c.
 {
   register int i;
   register BUILTIN_DESC *builtin;
   char *dname;
   char *sarray[2];
   for (i = 0; i < builtins->sindex; i++)
     {
       builtin = (BUILTIN_DESC *)builtins->array[i];
       if (builtin->dependencies)
     write_ifdefs (stream, builtin->dependencies->array);
       /* Write the long documentation strings. */
       dname = document_name (builtin);
       fprintf (stream, "char * const %s_doc[] =", dname);
       if (separate_helpfiles)
     {
       int l = strlen (helpfile_directory) + strlen (dname) + 1;
       sarray[0] = (char *)xmalloc (l + 1);
       sprintf (sarray[0], "%s/%s", helpfile_directory, dname);
       sarray[1] = (char *)NULL;
       write_documentation (stream, sarray, 0, STRING_ARRAY|HELPFILE);
       free (sarray[0]);
     }
       else
     write_documentation (stream, builtin->longdoc->array, 0, STRING_ARRAY);
       if (builtin->dependencies)
     write_endifs (stream, builtin->dependencies->array);
     }
 }
References ARRAY::array, builtin, document_name, fprintf(), free, HELPFILE, helpfile_directory, i, if(), l, NULL, separate_helpfiles, ARRAY::sindex, sprintf(), STRING_ARRAY, strlen(), write_documentation(), write_endifs(), write_ifdefs(), and xmalloc().
xmalloc() [1/2]
static char* xmalloc () static
Referenced by array_create(), builtin_handler(), copy_builtin(), copy_string_array(), extract_info(), main(), write_helpfiles(), and write_longdocs().
xmalloc() [2/2]
static char* xmalloc (int bytes) static
Definition at line 1046 of file mkbuiltins.c.
 {
   char *temp = (char *)malloc (bytes);
   if (!temp)
     memory_error_and_abort ();
   return (temp);
 }
References malloc, and memory_error_and_abort().
xrealloc() [1/2]
static char * xrealloc ()
Referenced by array_add().
xrealloc() [2/2]
static char* xrealloc (char * pointer, int bytes) static
Definition at line 1057 of file mkbuiltins.c.
 {
   char *temp;
   if (!pointer)
     temp = (char *)malloc (bytes);
   else
     temp = (char *)realloc (pointer, bytes);
   if (!temp)
     memory_error_and_abort ();
   return (temp);
 }
References malloc, memory_error_and_abort(), and realloc.
Variable Documentation
arrayvar_builtins
char* arrayvar_builtins[]
Initial value:
=
{
  "declare", "let", "local", "printf", "read", "test", "[",
  "typeset", "unset", "wait",
  (char *)NULL
}
Definition at line 186 of file mkbuiltins.c.
Referenced by is_arrayvar_builtin().
assignment_builtins
char* assignment_builtins[]
Initial value:
=
{
  "alias", "declare", "export", "local", "readonly", "typeset",
  (char *)NULL
}
Definition at line 164 of file mkbuiltins.c.
Referenced by is_assignment_builtin().
building_builtin
int building_builtin = 0 static
Definition at line 511 of file mkbuiltins.c.
Referenced by builtin_handler(), end_handler(), extract_info(), and must_be_building().
documentation_file
FILE* documentation_file = (FILE *)NULL
Definition at line 82 of file mkbuiltins.c.
Referenced by main(), and write_builtins().
errno
int errno extern
Referenced by write_helpfiles().
error_directory
char* error_directory = (char *)NULL
Definition at line 108 of file mkbuiltins.c.
Referenced by extract_info(), line_error(), and main().
extern_filename
char* extern_filename = (char *)NULL
Definition at line 114 of file mkbuiltins.c.
Referenced by main().
handlers
HANDLER_ENTRY handlers[]
Initial value:
= {
  { "BUILTIN", builtin_handler },
  { "DOCNAME", docname_handler },
  { "FUNCTION", function_handler },
  { "SHORT_DOC", short_doc_handler },
  { "$", comment_handler },
  { "COMMENT", comment_handler },
  { "DEPENDS_ON", depends_on_handler },
  { "PRODUCES", produces_handler },
  { "END", end_handler },
  { (char *)NULL, (mk_handler_func_t *)NULL }
}
Definition at line 482 of file mkbuiltins.c.
Referenced by find_directive().
helpfile_directory
char* helpfile_directory
Definition at line 104 of file mkbuiltins.c.
Referenced by main(), and write_longdocs().
include_filename
char* include_filename = (char *)NULL
Definition at line 118 of file mkbuiltins.c.
Referenced by main(), and write_file_headers().
inhibit_functions
int inhibit_functions = 0
Definition at line 92 of file mkbuiltins.c.
Referenced by main(), and write_builtins().
inhibit_production
int inhibit_production = 0
Definition at line 88 of file mkbuiltins.c.
Referenced by main(), and produces_handler().
localvar_builtins
char* localvar_builtins[]
Initial value:
=
{
  "declare", "local", "typeset", (char *)NULL
}
Definition at line 170 of file mkbuiltins.c.
Referenced by is_localvar_builtin().
only_documentation
int only_documentation = 0
Definition at line 85 of file mkbuiltins.c.
Referenced by main(), produces_handler(), and write_builtins().
output_cpp_line_info
int output_cpp_line_info = 0
Definition at line 515 of file mkbuiltins.c.
Referenced by builtin_handler(), extract_info(), and produces_handler().
posix_builtins
char* posix_builtins[]
Initial value:
=
{
  "alias", "bg", "cd", "command", "false", "fc", "fg", "getopts", "jobs",
  "kill", "newgrp", "pwd", "read", "true", "umask", "unalias", "wait",
  (char *)NULL
}
Definition at line 176 of file mkbuiltins.c.
Referenced by is_posix_builtin().
saved_builtins
ARRAY* saved_builtins = (ARRAY *)NULL
Definition at line 153 of file mkbuiltins.c.
Referenced by main(), and save_builtin().
separate_helpfiles
int separate_helpfiles = 0
Definition at line 96 of file mkbuiltins.c.
Referenced by main(), write_builtins(), and write_longdocs().
single_longdoc_strings
int single_longdoc_strings = 1
Definition at line 100 of file mkbuiltins.c.
Referenced by main(), and write_documentation().
special_builtins
char* special_builtins[]
Initial value:
=
{
  ":", ".", "source", "break", "continue", "eval", "exec", "exit",
  "export", "readonly", "return", "set", "shift", "times", "trap", "unset",
  (char *)NULL
}
Definition at line 156 of file mkbuiltins.c.
Referenced by is_special_builtin().
struct_filename
char* struct_filename = (char *)NULL
Definition at line 111 of file mkbuiltins.c.
Referenced by main().
structfile_footer
char* structfile_footer[]
Initial value:
= {
  "  { (char *)0x0, (sh_builtin_func_t *)0x0, 0, (char **)0x0, (char *)0x0, (char *)0x0 }",
  "};",
  "",
  "struct builtin *shell_builtins = static_shell_builtins;",
  "struct builtin *current_builtin;",
  "",
  "int num_shell_builtins =",
  "\tsizeof (static_shell_builtins) / sizeof (struct builtin) - 1;",
  (char *)NULL
}
Definition at line 1175 of file mkbuiltins.c.
Referenced by write_file_footers().
structfile_header
char* structfile_header[]
Definition at line 1133 of file mkbuiltins.c.
Referenced by write_dummy_declarations(), and write_file_headers().