Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/iso9660.c File Reference
iso9660.c File Reference
#include "volume_id_internal.h"
Data Structures
struct iso_volume_descriptor
struct high_sierra_volume_descriptor
Macros
#define ISO_SUPERBLOCK_OFFSET 0x8000
#define ISO_SECTOR_SIZE 0x800
#define ISO_VD_OFFSET (ISO_SUPERBLOCK_OFFSET + ISO_SECTOR_SIZE)
#define ISO_VD_PRIMARY 0x1
#define ISO_VD_SUPPLEMENTARY 0x2
#define ISO_VD_END 0xff
#define ISO_VD_MAX 16
#define off ((uint64_t)0)
Functions
int FAST_FUNC volume_id_probe_iso9660 (struct volume_id *id)
Variables
struct iso_volume_descriptor PACKED
Data Structure Documentation
iso_volume_descriptor
struct iso_volume_descriptor
Definition at line 37 of file iso9660.c.
Data Fields
uint8_t escape_sequences[8]
uint8_t flags
uint8_t space_size[8]
uint8_t system_id[32]
uint8_t unused[8]
uint8_t vd_id[5]
uint8_t vd_type
uint8_t vd_version
uint8_t volume_id[32]
high_sierra_volume_descriptor
struct high_sierra_volume_descriptor
Definition at line 49 of file iso9660.c.
Data Fields
uint8_t foo[8]
uint8_t id[4]
uint8_t type
uint8_t version
Macro Definition Documentation
ISO_SECTOR_SIZE
#define ISO_SECTOR_SIZE 0x800
Definition at line 30 of file iso9660.c.
ISO_SUPERBLOCK_OFFSET
#define ISO_SUPERBLOCK_OFFSET 0x8000
Definition at line 29 of file iso9660.c.
ISO_VD_END
#define ISO_VD_END 0xff
Definition at line 34 of file iso9660.c.
ISO_VD_MAX
#define ISO_VD_MAX 16
Definition at line 35 of file iso9660.c.
ISO_VD_OFFSET
#define ISO_VD_OFFSET (ISO_SUPERBLOCK_OFFSET + ISO_SECTOR_SIZE)
Definition at line 31 of file iso9660.c.
ISO_VD_PRIMARY
#define ISO_VD_PRIMARY 0x1
Definition at line 32 of file iso9660.c.
ISO_VD_SUPPLEMENTARY
#define ISO_VD_SUPPLEMENTARY 0x2
Definition at line 33 of file iso9660.c.
off
#define off ((uint64_t)0)
Function Documentation
volume_id_probe_iso9660()
int FAST_FUNC volume_id_probe_iso9660 (struct volume_id * id)
Definition at line 56 of file iso9660.c.
 {
 #define off ((uint64_t)0)
     uint8_t *buf;
     struct iso_volume_descriptor *is;
     struct high_sierra_volume_descriptor *hs;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     buf = volume_id_get_buffer(id, off + ISO_SUPERBLOCK_OFFSET, 0x200);
     if (buf == NULL)
         return -1;
     is = (struct iso_volume_descriptor *) buf;
     if (memcmp(is->vd_id, "CD001", 5) == 0) {
         int vd_offset;
         int i;
         dbg("read label from PVD");
 //      volume_id_set_label_raw(id, is->volume_id, 32);
         volume_id_set_label_string(id, is->volume_id, 32);
         dbg("looking for SVDs");
         vd_offset = ISO_VD_OFFSET;
         for (i = 0; i < ISO_VD_MAX; i++) {
             uint8_t svd_label[64];
             is = volume_id_get_buffer(id, off + vd_offset, 0x200);
             if (is == NULL || is->vd_type == ISO_VD_END)
                 break;
             if (is->vd_type != ISO_VD_SUPPLEMENTARY)
                 continue;
             dbg("found SVD at offset 0x%llx", (unsigned long long) (off + vd_offset));
             if (memcmp(is->escape_sequences, "%/@", 3) == 0
              || memcmp(is->escape_sequences, "%/C", 3) == 0
              || memcmp(is->escape_sequences, "%/E", 3) == 0
             ) {
                 dbg("Joliet extension found");
                 volume_id_set_unicode16((char *)svd_label, sizeof(svd_label), is->volume_id, BE, 32);
                 if (memcmp(id->label, svd_label, 16) == 0) {
                     dbg("SVD label is identical, use the possibly longer PVD one");
                     break;
                 }
 //              volume_id_set_label_raw(id, is->volume_id, 32);
                 volume_id_set_label_string(id, svd_label, 32);
 //              strcpy(id->type_version, "Joliet Extension");
                 goto found;
             }
             vd_offset += ISO_SECTOR_SIZE;
         }
         goto found;
     }
     hs = (struct high_sierra_volume_descriptor *) buf;
     if (memcmp(hs->id, "CDROM", 5) == 0) {
 //      strcpy(id->type_version, "High Sierra");
         goto found;
     }
     return -1;
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "iso9660";)
     return 0;
 }
References BE, buf, dbg, iso_volume_descriptor::escape_sequences, found, i, high_sierra_volume_descriptor::id, ISO_SECTOR_SIZE, ISO_SUPERBLOCK_OFFSET, ISO_VD_END, ISO_VD_MAX, ISO_VD_OFFSET, ISO_VD_SUPPLEMENTARY, volume_id::label, memcmp(), NULL, off, iso_volume_descriptor::vd_id, iso_volume_descriptor::vd_type, iso_volume_descriptor::volume_id, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_unicode16().
Variable Documentation
PACKED
struct high_sierra_volume_descriptor PACKED