Fennix Userspace: Userspace/musl/include/sys/mount.h File Reference
mount.h File Reference
#include <sys/ioctl.h>
Macros
#define BLKROSET _IO(0x12, 93)
#define BLKROGET _IO(0x12, 94)
#define BLKRRPART _IO(0x12, 95)
#define BLKGETSIZE _IO(0x12, 96)
#define BLKFLSBUF _IO(0x12, 97)
#define BLKRASET _IO(0x12, 98)
#define BLKRAGET _IO(0x12, 99)
#define BLKFRASET _IO(0x12,100)
#define BLKFRAGET _IO(0x12,101)
#define BLKSECTSET _IO(0x12,102)
#define BLKSECTGET _IO(0x12,103)
#define BLKSSZGET _IO(0x12,104)
#define BLKBSZGET _IOR(0x12,112,size_t)
#define BLKBSZSET _IOW(0x12,113,size_t)
#define BLKGETSIZE64 _IOR(0x12,114,size_t)
#define MS_RDONLY 1
#define MS_NOSUID 2
#define MS_NODEV 4
#define MS_NOEXEC 8
#define MS_SYNCHRONOUS 16
#define MS_REMOUNT 32
#define MS_MANDLOCK 64
#define MS_DIRSYNC 128
#define MS_NOSYMFOLLOW 256
#define MS_NOATIME 1024
#define MS_NODIRATIME 2048
#define MS_BIND 4096
#define MS_MOVE 8192
#define MS_REC 16384
#define MS_SILENT 32768
#define MS_POSIXACL (1<<16)
#define MS_UNBINDABLE (1<<17)
#define MS_PRIVATE (1<<18)
#define MS_SLAVE (1<<19)
#define MS_SHARED (1<<20)
#define MS_RELATIME (1<<21)
#define MS_KERNMOUNT (1<<22)
#define MS_I_VERSION (1<<23)
#define MS_STRICTATIME (1<<24)
#define MS_LAZYTIME (1<<25)
#define MS_NOREMOTELOCK (1<<27)
#define MS_NOSEC (1<<28)
#define MS_BORN (1<<29)
#define MS_ACTIVE (1<<30)
#define MS_NOUSER (1U<<31)
#define MS_RMT_MASK (MS_RDONLY|MS_SYNCHRONOUS|MS_MANDLOCK|MS_I_VERSION|MS_LAZYTIME)
#define MS_MGC_VAL 0xc0ed0000
#define MS_MGC_MSK 0xffff0000
#define MNT_FORCE 1
#define MNT_DETACH 2
#define MNT_EXPIRE 4
#define UMOUNT_NOFOLLOW 8
Functions
int mount (const char *, const char *, const char *, unsigned long, const void *)
int umount (const char *)
int umount2 (const char *, int)
Macro Definition Documentation
BLKBSZGET
#define BLKBSZGET _IOR(0x12,112,size_t)
Definition at line 22 of file mount.h.
BLKBSZSET
#define BLKBSZSET _IOW(0x12,113,size_t)
Definition at line 23 of file mount.h.
BLKFLSBUF
#define BLKFLSBUF _IO(0x12, 97)
Definition at line 14 of file mount.h.
BLKFRAGET
#define BLKFRAGET _IO(0x12,101)
Definition at line 18 of file mount.h.
BLKFRASET
#define BLKFRASET _IO(0x12,100)
Definition at line 17 of file mount.h.
BLKGETSIZE
#define BLKGETSIZE _IO(0x12, 96)
Definition at line 13 of file mount.h.
BLKGETSIZE64
#define BLKGETSIZE64 _IOR(0x12,114,size_t)
Definition at line 24 of file mount.h.
BLKRAGET
#define BLKRAGET _IO(0x12, 99)
Definition at line 16 of file mount.h.
BLKRASET
#define BLKRASET _IO(0x12, 98)
Definition at line 15 of file mount.h.
BLKROGET
#define BLKROGET _IO(0x12, 94)
Definition at line 11 of file mount.h.
BLKROSET
#define BLKROSET _IO(0x12, 93)
Definition at line 10 of file mount.h.
BLKRRPART
#define BLKRRPART _IO(0x12, 95)
Definition at line 12 of file mount.h.
BLKSECTGET
#define BLKSECTGET _IO(0x12,103)
Definition at line 20 of file mount.h.
BLKSECTSET
#define BLKSECTSET _IO(0x12,102)
Definition at line 19 of file mount.h.
BLKSSZGET
#define BLKSSZGET _IO(0x12,104)
Definition at line 21 of file mount.h.
MNT_DETACH
#define MNT_DETACH 2
Definition at line 63 of file mount.h.
MNT_EXPIRE
#define MNT_EXPIRE 4
Definition at line 64 of file mount.h.
MNT_FORCE
#define MNT_FORCE 1
Definition at line 62 of file mount.h.
MS_ACTIVE
#define MS_ACTIVE (1<<30)
Definition at line 54 of file mount.h.
MS_BIND
#define MS_BIND 4096
Definition at line 37 of file mount.h.
MS_BORN
#define MS_BORN (1<<29)
Definition at line 53 of file mount.h.
MS_DIRSYNC
#define MS_DIRSYNC 128
Definition at line 33 of file mount.h.
MS_I_VERSION
#define MS_I_VERSION (1<<23)
Definition at line 48 of file mount.h.
MS_KERNMOUNT
#define MS_KERNMOUNT (1<<22)
Definition at line 47 of file mount.h.
MS_LAZYTIME
#define MS_LAZYTIME (1<<25)
Definition at line 50 of file mount.h.
MS_MANDLOCK
#define MS_MANDLOCK 64
Definition at line 32 of file mount.h.
MS_MGC_MSK
#define MS_MGC_MSK 0xffff0000
Definition at line 60 of file mount.h.
MS_MGC_VAL
#define MS_MGC_VAL 0xc0ed0000
Definition at line 59 of file mount.h.
MS_MOVE
#define MS_MOVE 8192
Definition at line 38 of file mount.h.
MS_NOATIME
#define MS_NOATIME 1024
Definition at line 35 of file mount.h.
MS_NODEV
#define MS_NODEV 4
Definition at line 28 of file mount.h.
MS_NODIRATIME
#define MS_NODIRATIME 2048
Definition at line 36 of file mount.h.
MS_NOEXEC
#define MS_NOEXEC 8
Definition at line 29 of file mount.h.
MS_NOREMOTELOCK
#define MS_NOREMOTELOCK (1<<27)
Definition at line 51 of file mount.h.
MS_NOSEC
#define MS_NOSEC (1<<28)
Definition at line 52 of file mount.h.
MS_NOSUID
#define MS_NOSUID 2
Definition at line 27 of file mount.h.
MS_NOSYMFOLLOW
#define MS_NOSYMFOLLOW 256
Definition at line 34 of file mount.h.
MS_NOUSER
#define MS_NOUSER (1U<<31)
Definition at line 55 of file mount.h.
MS_POSIXACL
#define MS_POSIXACL (1<<16)
Definition at line 41 of file mount.h.
MS_PRIVATE
#define MS_PRIVATE (1<<18)
Definition at line 43 of file mount.h.
MS_RDONLY
#define MS_RDONLY 1
Definition at line 26 of file mount.h.
MS_REC
#define MS_REC 16384
Definition at line 39 of file mount.h.
MS_RELATIME
#define MS_RELATIME (1<<21)
Definition at line 46 of file mount.h.
MS_REMOUNT
#define MS_REMOUNT 32
Definition at line 31 of file mount.h.
MS_RMT_MASK
#define MS_RMT_MASK (MS_RDONLY|MS_SYNCHRONOUS|MS_MANDLOCK|MS_I_VERSION|MS_LAZYTIME)
Definition at line 57 of file mount.h.
MS_SHARED
#define MS_SHARED (1<<20)
Definition at line 45 of file mount.h.
MS_SILENT
#define MS_SILENT 32768
Definition at line 40 of file mount.h.
MS_SLAVE
#define MS_SLAVE (1<<19)
Definition at line 44 of file mount.h.
MS_STRICTATIME
#define MS_STRICTATIME (1<<24)
Definition at line 49 of file mount.h.
MS_SYNCHRONOUS
#define MS_SYNCHRONOUS 16
Definition at line 30 of file mount.h.
MS_UNBINDABLE
#define MS_UNBINDABLE (1<<17)
Definition at line 42 of file mount.h.
UMOUNT_NOFOLLOW
#define UMOUNT_NOFOLLOW 8
Definition at line 65 of file mount.h.
Function Documentation
mount()
int mount (const char * special, const char * dir, const char * fstype, unsigned long flags, const void * data)
Definition at line 4 of file mount.c.
 {
     return syscall(SYS_mount, special, dir, fstype, flags, data);
 }
References syscall().
umount()
int umount (const char * special)
Definition at line 9 of file mount.c.
 {
     return syscall(SYS_umount2, special, 0);
 }
References syscall().
umount2()
int umount2 (const char * special, int flags)
Definition at line 14 of file mount.c.
 {
     return syscall(SYS_umount2, special, flags);
 }
References syscall().