Fennix Userspace: Userspace/libc/src/print/printf.h File Reference
printf.h File Reference
#include <types.h>
Macros
#define ATTR_PRINTF((one_based_format_index) , (first_arg))
Small stand-alone implementation of the printf family of functions ((v)printf, (v)s(n)printf etc., geared towards use on embedded systems with a very limited resources.
#define ATTR_VPRINTF(one_based_format_index)
#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES 0
#define PRINTF_VISIBILITY __attribute__((visibility("default")))
Functions
PRINTF_VISIBILITY int putchar (int c)
PRINTF_VISIBILITY int fctprintf (void(*out)(char c, void *extra_arg), void *extra_arg, const char *format,...) ATTR_PRINTF(3
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vfctprintf (void(*out)(char c, void *extra_arg), void *extra_arg, const char *format, va_list arg) ATTR_VPRINTF(3)
PRINTF_VISIBILITY int printf (const char *format,...) ATTR_PRINTF(1
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vprintf (const char *format, va_list arg) ATTR_VPRINTF(1)
PRINTF_VISIBILITY int sprintf (char *s, const char *format,...) ATTR_PRINTF(2
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vsprintf (char *s, const char *format, va_list arg) ATTR_VPRINTF(2)
PRINTF_VISIBILITY int snprintf (char *s, size_t count, const char *format,...) ATTR_PRINTF(3
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vsnprintf (char *s, size_t count, const char *format, va_list arg) ATTR_VPRINTF(3)
Macro Definition Documentation
ATTR_PRINTF
#define ATTR_PRINTF () , (first_arg))
Small stand-alone implementation of the printf family of functions ((v)printf, (v)s(n)printf etc., geared towards use on embedded systems with a very limited resources.
Author
(c) Eyal Rozenberg eyalr.nosp@m.oz1@.nosp@m.gmx.c.nosp@m.om 2021-2022, Haifa, Palestine/Israel
(c) Marco Paland (info@.nosp@m.pala.nosp@m.nd.co.nosp@m.m) 2014-2019, PALANDesign Hannover, Germany
Note
Others have made smaller contributions to this file: see the contributors page at https://github.com/eyalroz/printf/graphs/contributors or ask one of the authors.
the implementations are thread-safe; re-entrant; use no functions from the standard library; and do not dynamically allocate any memory.
@license The MIT License (MIT)
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 97 of file printf.h.
ATTR_VPRINTF
#define ATTR_VPRINTF (one_based_format_index)
PRINTF_ALIAS_STANDARD_FUNCTION_NAMES
#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES 0
PRINTF_VISIBILITY
#define PRINTF_VISIBILITY __attribute__((visibility("default")))
Function Documentation
fctprintf()
PRINTF_VISIBILITY int fctprintf (void(*)(char c, void *extra_arg) out, void * extra_arg, const char * format, ...)
printf/vprintf with user-specified output function
An alternative to printf_, in which the output function is specified dynamically (rather than putchar_ being used)
Parameters
out An output function which takes one character and a type-erased additional parameters
extra_arg The type-erased argument to pass to the output function out with each call
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters for which the output f unction was invoked, not counting the terminating null character
printf()
PRINTF_VISIBILITY int printf (const char * format, ...)
An implementation of the C standard's printf/vprintf
Note
you must implement a putchar_ function for using this function - it invokes putchar_ rather than directly performing any I/O (which insulates it from any dependence on the operating system and external libraries).
Parameters
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each %-specifier in format string
Returns
The number of characters written into s, not counting the terminating null character
Definition at line 70 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vprintf(format, args);
     va_end(args);
     return ret;
 }
References args, format, ret, va_end(), va_start(), and vprintf().
Referenced by allocate_new_page(), callback(), check_root_group(), CheckDirectoryHasIWAD(), D_AddFile(), D_CheckNetGame(), D_Disconnected(), D_DoomLoop(), D_DoomMain(), D_FindIWAD(), D_InitNetGame(), free(), G_DoPlayDemo(), GUS_WriteConfig(), I_CDMusPrintStartup(), I_GetPaletteIndex(), I_InitGraphics(), I_InitJoystick(), I_InitSquashTable(), I_InitStretchTables(), I_PrintStartupBanner(), I_ResetScaleTables(), I_ZoneBase(), InitGameVersion(), liballoc_dump(), LoadGameSettings(), LoadResponseFile(), M_ExtractFileBase(), M_GetSaveGameDir(), M_LoadDefaults(), M_SetConfigDir(), main(), malloc(), mem_fread(), mem_fseek(), PrintDehackedBanners(), PrintGameVersion(), R_GenerateLookup(), R_Init(), R_InitData(), R_InitSpriteLumps(), R_InitTextures(), realloc(), run_cmd(), SetMissionForPackName(), StatDump(), test_getattrnp(), W_AddFile(), W_ParseCommandLine(), WI_drawOnLnode(), and Z_DumpHeap().
putchar()
PRINTF_VISIBILITY int putchar (int c)
Definition at line 33 of file put.c.
 { return fputc(c, stdout); }
snprintf()
PRINTF_VISIBILITY int snprintf (char * s, size_t count, const char * format, ...)
An implementation of the C standard's snprintf/vsnprintf
Parameters
s An array in which to store the formatted string. It must be large enough to fit either the entire formatted output, or at least n characters. Alternatively, it can be NULL, in which case nothing will be printed, and only the number of characters which could have been printed is tallied and returned.
n The maximum number of characters to write to the array, including a terminating null character
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters that COULD have been written into s, not counting the terminating null character. A value equal or larger than n indicates truncation. Only when the returned value is non-negative and less than n, the null-terminated string has been fully and successfully printed.
sprintf()
PRINTF_VISIBILITY int sprintf (char * s, const char * format, ...)
An implementation of the C standard's sprintf/vsprintf
Note
For security considerations (the potential for exceeding the buffer bounds), please consider using the size-constrained variant, snprintf / vsnprintf , instead.
Parameters
s An array in which to store the formatted string. It must be large enough to fit the formatted output!
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters written into s, not counting the terminating null character
vfctprintf()
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vfctprintf (void(*)(char c, void *extra_arg) out, void * extra_arg, const char * format, va_list arg)
Definition at line 1548 of file printf.c.
 {
     output_gadget_t gadget = function_gadget(out, extra_arg);
     return vsnprintf_impl(&gadget, format, arg);
 }
References mlibc::arg, format, function_gadget(), and vsnprintf_impl().
Referenced by fctprintf().
vprintf()
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vprintf (const char * format, va_list arg)
Definition at line 1531 of file printf.c.
 {
     output_gadget_t gadget = extern_putchar_gadget();
     return vsnprintf_impl(&gadget, format, arg);
 }
References mlibc::arg, extern_putchar_gadget(), format, and vsnprintf_impl().
Referenced by printf().
vsnprintf()
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vsnprintf (char * s, size_t count, const char * format, va_list arg)
Definition at line 1537 of file printf.c.
 {
     output_gadget_t gadget = buffer_gadget(s, n);
     return vsnprintf_impl(&gadget, format, arg);
 }
References mlibc::arg, buffer_gadget(), format, n, and vsnprintf_impl().
Referenced by _vsyslog(), M_vsnprintf(), snprintf(), and vsprintf().
vsprintf()
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vsprintf (char * s, const char * format, va_list arg)
Definition at line 1543 of file printf.c.
 {
     return vsnprintf(s, PRINTF_MAX_POSSIBLE_BUFFER_SIZE, format, arg);
 }
References mlibc::arg, format, PRINTF_MAX_POSSIBLE_BUFFER_SIZE, and vsnprintf().
Referenced by sprintf().