Fennix: Scope Struct Reference
Scope Struct Reference
#include <linker.hpp>
Public Types
using ResolveFlags = uint32_t
Public Member Functions
Scope (bool isGlobal=false)
void appendObject (SharedObject *object)
frg::optional< ObjectSymbol > resolveSymbol (frg::string_view string, uint64_t skipRts, ResolveFlags flags)
Static Public Member Functions
static frg::optional< ObjectSymbol > resolveGlobalOrLocal (Scope &globalScope, Scope *localScope, frg::string_view string, uint64_t skipRts, ResolveFlags flags)
static frg::optional< ObjectSymbol > resolveGlobalOrLocalNext (Scope &globalScope, Scope *localScope, frg::string_view string, SharedObject *origin)
Data Fields
bool isGlobal
frg::vector< SharedObject *, MemoryAllocator > _objects
Static Public Attributes
static constexpr ResolveFlags resolveCopy = 1
static constexpr ResolveFlags skipGlobalAfterRts = 1 << 1
Private Member Functions
frg::optional< ObjectSymbol > _resolveNext (frg::string_view string, SharedObject *target)
Detailed Description
Definition at line 244 of file linker.hpp.
Member Typedef Documentation
ResolveFlags
using Scope::ResolveFlags = uint32_t
Definition at line 245 of file linker.hpp.
Constructor & Destructor Documentation
Scope()
Scope::Scope (bool isGlobal = false)
Definition at line 1119 of file linker.cpp.
 : isGlobal{isGlobal}, _objects(getAllocator()) { }
Member Function Documentation
_resolveNext()
frg::optional< ObjectSymbol > Scope::_resolveNext (frg::string_view string, SharedObject * target) private
Definition at line 1093 of file linker.cpp.
{
     // Skip objects until we find the target, and only look for symbols after that.
     size_t i;
     for (i = 0; i < _objects.size(); i++) {
         if (_objects[i] == target)
             break;
     }
     if (i == _objects.size()) {
         mlibc::infoLogger() << "rtdl: object passed to Scope::resolveAfter was not found" << frg::endlog;
         return frg::optional<ObjectSymbol>();
     }
     for (i = i + 1; i < _objects.size(); i++) {
         if(_objects[i]->isMainObject)
             continue;
         frg::optional<ObjectSymbol> p = resolveInObject(_objects[i], string);
         if(p)
             return p;
     }
     return frg::optional<ObjectSymbol>();
 }
References _objects, i, mlibc::infoLogger, p, and resolveInObject().
Referenced by resolveGlobalOrLocalNext().
appendObject()
void Scope::appendObject (SharedObject * object)
Definition at line 1122 of file linker.cpp.
{
     // Don't insert duplicates.
     for (auto obj : _objects) {
         if (obj == object)
             return;
     }
     _objects.push(object);
 }
References _objects.
Referenced by Loader::linkObjects().
resolveGlobalOrLocal()
frg::optional< ObjectSymbol > Scope::resolveGlobalOrLocal (Scope & globalScope, Scope * localScope, frg::string_view string, uint64_t skipRts, ResolveFlags flags) static
Definition at line 1132 of file linker.cpp.
{
     auto sym = globalScope.resolveSymbol(string, skipRts, flags | skipGlobalAfterRts);
     if(!sym && localScope)
         sym = localScope->resolveSymbol(string, skipRts, flags | skipGlobalAfterRts);
     return sym;
 }
References mlibc::flags, globalScope, resolveSymbol(), and skipGlobalAfterRts.
Referenced by Loader::_processLazyRelocations(), Loader::_processRela(), lazyRelocate(), and processCopyRela().
resolveGlobalOrLocalNext()
frg::optional< ObjectSymbol > Scope::resolveGlobalOrLocalNext (Scope & globalScope, Scope * localScope, frg::string_view string, SharedObject * origin) static
Definition at line 1140 of file linker.cpp.
{
     auto sym = globalScope._resolveNext(string, origin);
     if(!sym && localScope) {
         sym = localScope->_resolveNext(string, origin);
     }
     return sym;
 }
References _resolveNext(), and globalScope.
resolveSymbol()
frg::optional< ObjectSymbol > Scope::resolveSymbol (frg::string_view string, uint64_t skipRts, ResolveFlags flags)
Definition at line 1150 of file linker.cpp.
{
     for (auto object : _objects) {
         if((flags & resolveCopy) && object->isMainObject)
             continue;
         if((flags & skipGlobalAfterRts) && object->globalRts > skipRts) {
             // globalRts should be monotone increasing for objects in the global scope,
             // so as an optimization we can break early here.
             // TODO: If we implement DT_SYMBOLIC, this assumption fails.
             if(isGlobal)
                 break;
             else
                 continue;
         }
         frg::optional<ObjectSymbol> p = resolveInObject(object, string);
         if(p)
             return p;
     }
     return frg::optional<ObjectSymbol>();
 }
References _objects, mlibc::flags, isGlobal, p, resolveCopy, resolveInObject(), and skipGlobalAfterRts.
Referenced by resolveGlobalOrLocal().
Field Documentation
_objects
frg::vector<SharedObject *, MemoryAllocator> Scope::_objects
Definition at line 265 of file linker.hpp.
Referenced by _resolveNext(), appendObject(), and resolveSymbol().
isGlobal
bool Scope::isGlobal
Definition at line 260 of file linker.hpp.
Referenced by Loader::linkObjects(), and resolveSymbol().
resolveCopy
constexpr ResolveFlags Scope::resolveCopy = 1 inline static constexpr
Definition at line 246 of file linker.hpp.
Referenced by processCopyRela(), and resolveSymbol().
skipGlobalAfterRts
constexpr ResolveFlags Scope::skipGlobalAfterRts = 1 << 1 inline static constexpr
Definition at line 247 of file linker.hpp.
Referenced by resolveGlobalOrLocal(), and resolveSymbol().
The documentation for this struct was generated from the following files:
Userspace/mlibc/options/rtdl/generic/linker.hpp
Userspace/mlibc/options/rtdl/generic/linker.cpp