Fennix: Userspace/mlibc/options/ansi/generic/complex/ccos.c File Reference
ccos.c File Reference
#include <complex.h>
#include <math.h>
#include "cephes_subr.h"
Functions
double complex ccos (double complex z)
Function Documentation
ccos()
double complex ccos (double complex z)
Definition at line 73 of file ccos.c.
 {
     double complex w;
     double ch, sh;
     __mlibc_cchsh(cimag(z), &ch, &sh);
     w = cos(creal(z)) * ch - (sin(creal(z)) * sh) * I;
     return w;
 }
References __mlibc_cchsh(), cimag(), complex, cos(), creal(), I(), and sin().