Fennix: Userspace/mlibc/options/posix/include/sys/resource.h File Reference
resource.h File Reference
#include <abi-bits/resource.h>
#include <bits/posix/id_t.h>
#include <abi-bits/suseconds_t.h>
#include <bits/ansi/time_t.h>
#include <bits/posix/timeval.h>
Data Structures
struct rlimit
Macros
#define PRIO_PROCESS 1
#define PRIO_PGRP 2
#define PRIO_USER 3
#define RLIM_INFINITY ((rlim_t)-1)
#define RLIM_SAVED_MAX ((rlim_t)-1)
#define RLIM_SAVED_CUR ((rlim_t)-1)
#define RLIM_NLIMITS RLIMIT_NLIMITS
Typedefs
typedef unsigned long rlim_t
Functions
int getpriority (int, id_t)
int setpriority (int, id_t, int)
int getrusage (int, struct rusage *)
int getrlimit (int, struct rlimit *)
int setrlimit (int, const struct rlimit *)
Data Structure Documentation
rlimit
struct rlimit
Definition at line 26 of file resource.h.
Data Fields
rlim_t rlim_cur
rlim_t rlim_max
Macro Definition Documentation
PRIO_PGRP
#define PRIO_PGRP 2
Definition at line 11 of file resource.h.
PRIO_PROCESS
#define PRIO_PROCESS 1
Definition at line 10 of file resource.h.
PRIO_USER
#define PRIO_USER 3
Definition at line 12 of file resource.h.
RLIM_INFINITY
#define RLIM_INFINITY ((rlim_t)-1)
Definition at line 14 of file resource.h.
RLIM_NLIMITS
#define RLIM_NLIMITS RLIMIT_NLIMITS
Definition at line 18 of file resource.h.
RLIM_SAVED_CUR
#define RLIM_SAVED_CUR ((rlim_t)-1)
Definition at line 16 of file resource.h.
RLIM_SAVED_MAX
#define RLIM_SAVED_MAX ((rlim_t)-1)
Definition at line 15 of file resource.h.
Typedef Documentation
rlim_t
typedef unsigned long rlim_t
Definition at line 24 of file resource.h.
Function Documentation
getpriority()
int getpriority (int which, id_t who)
Definition at line 9 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getpriority, -1);
     int value = 0;
     if(int e = mlibc::sys_getpriority(which, who, &value); e) {
         errno = e;
     }
     return value;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_getpriority(), and value.
Referenced by main().
getrlimit()
int getrlimit (int resource, struct rlimit * limit)
Definition at line 36 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getrlimit, -1);
     if(int e = mlibc::sys_getrlimit(resource, limit); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getrlimit().
Referenced by main(), and sysconf().
getrusage()
int getrusage (int scope, struct rusage * usage)
Definition at line 27 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getrusage, -1);
     if(int e = mlibc::sys_getrusage(scope, usage); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_getrusage().
setpriority()
int setpriority (int which, id_t who, int prio)
Definition at line 18 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setpriority, -1);
     if(int e = mlibc::sys_setpriority(which, who, prio); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setpriority().
Referenced by main().
setrlimit()
int setrlimit (int resource, const struct rlimit * limit)
Definition at line 45 of file sys-resource-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setrlimit, -1);
     if(int e = mlibc::sys_setrlimit(resource, limit); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_setrlimit().
Referenced by main().