Fennix Userspace: Userspace/apps/base/busybox/miscutils/mt.c File Reference
mt.c File Reference
#include "libbb.h"
#include <sys/mtio.h>
Functions
int mt_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const short opcode_value[] ALIGN2
static const char opcode_name[] ALIGN1
Function Documentation
mt_main()
int mt_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 107 of file mt.c.
 {
     const char *file = "/dev/tape";
     struct mtop op;
     struct mtpos position;
     int fd, mode, idx;
     if (!argv[1]) {
         bb_show_usage();
     }
     if (strcmp(argv[1], "-f") == 0) {
         if (!argv[2] || !argv[3])
             bb_show_usage();
         file = argv[2];
         argv += 2;
     }
     idx = index_in_strings(opcode_name, argv[1]);
     if (idx < 0)
         bb_error_msg_and_die("unrecognized opcode %s", argv[1]);
     op.mt_op = opcode_value[idx];
     if (argv[2])
         op.mt_count = xatoi_positive(argv[2]);
     else
         op.mt_count = 1;  /* One, not zero, right? */
     switch (opcode_value[idx]) {
         case MTWEOF:
         case MTERASE:
         case MTWSM:
         case MTSETDRVBUFFER:
             mode = O_WRONLY;
             break;
         default:
             mode = O_RDONLY;
             break;
     }
     fd = xopen(file, mode);
     switch (opcode_value[idx]) {
         case MTTELL:
             ioctl_or_perror_and_die(fd, MTIOCPOS, &position, "%s", file);
             printf("At block %d\n", (int) position.mt_blkno);
             break;
         default:
             ioctl_or_perror_and_die(fd, MTIOCTOP, &op, "%s", file);
             break;
     }
     return EXIT_SUCCESS;
 }
References argv, bb_error_msg_and_die(), bb_show_usage(), EXIT_SUCCESS, fd, idx, index_in_strings(), ioctl_or_perror_and_die(), mtpos::mt_blkno, MTERASE, MTIOCPOS, MTIOCTOP, MTSETDRVBUFFER, MTTELL, MTWEOF, MTWSM, O_RDONLY, O_WRONLY, printf(), strcmp, xatoi_positive(), and xopen().
Variable Documentation
ALIGN1
const char opcode_name [] ALIGN1 static
Definition at line 70 of file mt.c.
ALIGN2
const short opcode_value [] ALIGN2 static
Definition at line 33 of file mt.c.