Fennix Lynx Bootloader: Lynx/FennixLoader/ega.c File Reference
ega.c File Reference
#include <types.h>
Enumerations
enum vga_color {
VGA_COLOR_BLACK = 0 , VGA_COLOR_BLUE = 1 , VGA_COLOR_GREEN = 2 , VGA_COLOR_CYAN = 3 ,
VGA_COLOR_RED = 4 , VGA_COLOR_MAGENTA = 5 , VGA_COLOR_BROWN = 6 , VGA_COLOR_LIGHT_GREY = 7 ,
VGA_COLOR_DARK_GREY = 8 , VGA_COLOR_LIGHT_BLUE = 9 , VGA_COLOR_LIGHT_GREEN = 10 , VGA_COLOR_LIGHT_CYAN = 11 ,
VGA_COLOR_LIGHT_RED = 12 , VGA_COLOR_LIGHT_MAGENTA = 13 , VGA_COLOR_LIGHT_BROWN = 14 , VGA_COLOR_WHITE = 15 ,
VGA_COLOR_BLACK = 0 , VGA_COLOR_BLUE = 1 , VGA_COLOR_GREEN = 2 , VGA_COLOR_CYAN = 3 ,
VGA_COLOR_RED = 4 , VGA_COLOR_MAGENTA = 5 , VGA_COLOR_BROWN = 6 , VGA_COLOR_LIGHT_GREY = 7 ,
VGA_COLOR_DARK_GREY = 8 , VGA_COLOR_LIGHT_BLUE = 9 , VGA_COLOR_LIGHT_GREEN = 10 , VGA_COLOR_LIGHT_CYAN = 11 ,
VGA_COLOR_LIGHT_RED = 12 , VGA_COLOR_LIGHT_MAGENTA = 13 , VGA_COLOR_LIGHT_BROWN = 14 , VGA_COLOR_WHITE = 15
}
Functions
void outb (uint16_t port, uint8_t val)
static uint8_t vga_entry_color (enum vga_color fg, enum vga_color bg)
static uint16_t vga_entry (unsigned char uc, uint8_t color)
size_t ega_strlen (const char *str)
void terminal_initialize (void)
void terminal_setcolor (uint8_t color)
void terminal_putentryat (char c, uint8_t color, size_t x, size_t y)
void terminal_putchar (char c)
Variables
static const size_t VGA_WIDTH = 80
static const size_t VGA_HEIGHT = 25
int terminal_initialized
size_t terminal_row
size_t terminal_column
uint8_t terminal_color
uint16_t * terminal_buffer
Enumeration Type Documentation
vga_color
enum vga_color
Enumerator
VGA_COLOR_BLACK
VGA_COLOR_BLUE
VGA_COLOR_GREEN
VGA_COLOR_CYAN
VGA_COLOR_RED
VGA_COLOR_MAGENTA
VGA_COLOR_BROWN
VGA_COLOR_LIGHT_GREY
VGA_COLOR_DARK_GREY
VGA_COLOR_LIGHT_BLUE
VGA_COLOR_LIGHT_GREEN
VGA_COLOR_LIGHT_CYAN
VGA_COLOR_LIGHT_RED
VGA_COLOR_LIGHT_MAGENTA
VGA_COLOR_LIGHT_BROWN
VGA_COLOR_WHITE
VGA_COLOR_BLACK
VGA_COLOR_BLUE
VGA_COLOR_GREEN
VGA_COLOR_CYAN
VGA_COLOR_RED
VGA_COLOR_MAGENTA
VGA_COLOR_BROWN
VGA_COLOR_LIGHT_GREY
VGA_COLOR_DARK_GREY
VGA_COLOR_LIGHT_BLUE
VGA_COLOR_LIGHT_GREEN
VGA_COLOR_LIGHT_CYAN
VGA_COLOR_LIGHT_RED
VGA_COLOR_LIGHT_MAGENTA
VGA_COLOR_LIGHT_BROWN
VGA_COLOR_WHITE
Definition at line 4 of file ega.c.
 {
     VGA_COLOR_BLACK = 0,
     VGA_COLOR_BLUE = 1,
     VGA_COLOR_GREEN = 2,
     VGA_COLOR_CYAN = 3,
     VGA_COLOR_RED = 4,
     VGA_COLOR_MAGENTA = 5,
     VGA_COLOR_BROWN = 6,
     VGA_COLOR_LIGHT_GREY = 7,
     VGA_COLOR_DARK_GREY = 8,
     VGA_COLOR_LIGHT_BLUE = 9,
     VGA_COLOR_LIGHT_GREEN = 10,
     VGA_COLOR_LIGHT_CYAN = 11,
     VGA_COLOR_LIGHT_RED = 12,
     VGA_COLOR_LIGHT_MAGENTA = 13,
     VGA_COLOR_LIGHT_BROWN = 14,
     VGA_COLOR_WHITE = 15,
 };
Function Documentation
ega_strlen()
size_t ega_strlen (const char * str)
Definition at line 41 of file ega.c.
 {
     size_t len = 0;
     while (str[len])
         len++;
     return len;
 }
References len.
outb()
void outb (uint16_t port, uint8_t val)
Definition at line 24 of file ega.c.
 {
     asm volatile("outb %0, %1"
                  :
                  : "a"(val), "Nd"(port));
 }
Referenced by terminal_putchar().
terminal_initialize()
void terminal_initialize (void)
Definition at line 58 of file ega.c.
 {
     terminal_initialized = 1;
     terminal_row = 0;
     terminal_column = 0;
     terminal_color = vga_entry_color(VGA_COLOR_LIGHT_GREY, VGA_COLOR_BLACK);
     terminal_buffer = (uint16_t *)0xB8000;
     for (size_t y = 0; y < VGA_HEIGHT; y++)
     {
         for (size_t x = 0; x < VGA_WIDTH; x++)
         {
             const size_t index = y * VGA_WIDTH + x;
             terminal_buffer[index] = vga_entry(' ', terminal_color);
         }
     }
 }
References terminal_buffer, terminal_color, terminal_column, terminal_initialized, terminal_row, VGA_COLOR_BLACK, VGA_COLOR_LIGHT_GREY, vga_entry(), vga_entry_color(), VGA_HEIGHT, and VGA_WIDTH.
Referenced by loader_main().
terminal_putchar()
void terminal_putchar (char c)
Definition at line 88 of file ega.c.
 {
     if (!terminal_initialized)
         return;
     switch (c)
     {
     case '\n':
     case '\r':
         terminal_column = 0;
         if (++terminal_row >= VGA_HEIGHT)
         {
             // terminal_row = 0;
             // scroll the screen
             for (size_t y = 0; y < VGA_HEIGHT - 1; y++)
             {
                 for (size_t x = 0; x < VGA_WIDTH; x++)
                 {
                     const size_t index = y * VGA_WIDTH + x;
                     terminal_buffer[index] = terminal_buffer[index + VGA_WIDTH];
                 }
             }
             for (size_t x = 0; x < VGA_WIDTH; x++)
             {
                 const size_t index = (VGA_HEIGHT - 1) * VGA_WIDTH + x;
                 terminal_buffer[index] = vga_entry(' ', terminal_color);
             }
             terminal_row = VGA_HEIGHT - 1;
         }
         // Update the cursor
         uint16_t cursorLocation = terminal_row * 80 + terminal_column;
         outb(0x3D4, 14);                  // Tell the VGA board we are setting the high cursor byte.
         outb(0x3D5, cursorLocation >> 8); // Send the high cursor byte.
         outb(0x3D4, 15);                  // Tell the VGA board we are setting the low cursor byte.
         outb(0x3D5, cursorLocation);      // Send the low cursor byte.
         return;
     case '\t':
         terminal_column += 4;
         if (terminal_column >= VGA_WIDTH)
         {
             terminal_column = 0;
             if (++terminal_row == VGA_HEIGHT)
                 terminal_row = 0;
         }
         return;
     }
     terminal_putentryat(c, terminal_color, terminal_column, terminal_row);
     if (++terminal_column >= VGA_WIDTH)
     {
         terminal_column = 0;
         if (++terminal_row >= VGA_HEIGHT)
         {
             // terminal_row = 0;
             // scroll the screen
             for (size_t y = 0; y < VGA_HEIGHT - 1; y++)
             {
                 for (size_t x = 0; x < VGA_WIDTH; x++)
                 {
                     const size_t index = y * VGA_WIDTH + x;
                     terminal_buffer[index] = terminal_buffer[index + VGA_WIDTH];
                 }
             }
             for (size_t x = 0; x < VGA_WIDTH; x++)
             {
                 const size_t index = (VGA_HEIGHT - 1) * VGA_WIDTH + x;
                 terminal_buffer[index] = vga_entry(' ', terminal_color);
             }
             terminal_row = VGA_HEIGHT - 1;
         }
     }
     // Update the cursor
     uint16_t cursorLocation = terminal_row * 80 + terminal_column;
     outb(0x3D4, 14);                  // Tell the VGA board we are setting the high cursor byte.
     outb(0x3D5, cursorLocation >> 8); // Send the high cursor byte.
     outb(0x3D4, 15);                  // Tell the VGA board we are setting the low cursor byte.
     outb(0x3D5, cursorLocation);      // Send the low cursor byte.
 }
References outb(), terminal_buffer, terminal_color, terminal_column, terminal_initialized, terminal_putentryat(), terminal_row, vga_entry(), VGA_HEIGHT, and VGA_WIDTH.
Referenced by putchar().
terminal_putentryat()
void terminal_putentryat (char c, uint8_t color, size_t x, size_t y)
Definition at line 80 of file ega.c.
 {
     if (!terminal_initialized)
         return;
     const size_t index = y * VGA_WIDTH + x;
     terminal_buffer[index] = vga_entry(c, color);
 }
References terminal_buffer, terminal_initialized, vga_entry(), and VGA_WIDTH.
Referenced by terminal_putchar().
terminal_setcolor()
void terminal_setcolor (uint8_t color)
Definition at line 75 of file ega.c.
 {
     terminal_color = color;
 }
References terminal_color.
Referenced by WritePrefix().
vga_entry()
static uint16_t vga_entry (unsigned char uc, uint8_t color) inline static
Definition at line 36 of file ega.c.
 {
     return (uint16_t)uc | (uint16_t)color << 8;
 }
Referenced by terminal_initialize(), terminal_putchar(), and terminal_putentryat().
vga_entry_color()
static uint8_t vga_entry_color (enum vga_color fg, enum vga_color bg) inline static
Definition at line 31 of file ega.c.
 {
     return fg | bg << 4;
 }
Referenced by terminal_initialize().
Variable Documentation
terminal_buffer
uint16_t* terminal_buffer
Definition at line 56 of file ega.c.
Referenced by terminal_initialize(), terminal_putchar(), and terminal_putentryat().
terminal_color
uint8_t terminal_color
Definition at line 55 of file ega.c.
Referenced by terminal_initialize(), terminal_putchar(), and terminal_setcolor().
terminal_column
size_t terminal_column
Definition at line 54 of file ega.c.
Referenced by terminal_initialize(), and terminal_putchar().
terminal_initialized
int terminal_initialized
Definition at line 52 of file ega.c.
Referenced by terminal_initialize(), terminal_putchar(), and terminal_putentryat().
terminal_row
size_t terminal_row
Definition at line 53 of file ega.c.
Referenced by terminal_initialize(), and terminal_putchar().
VGA_HEIGHT
const size_t VGA_HEIGHT = 25 static
Definition at line 50 of file ega.c.
Referenced by terminal_initialize(), and terminal_putchar().
VGA_WIDTH
const size_t VGA_WIDTH = 80 static
Definition at line 49 of file ega.c.
Referenced by terminal_initialize(), terminal_putchar(), and terminal_putentryat().