Fennix Userspace: Userspace/apps/base/busybox/coreutils/chmod.c File Reference
chmod.c File Reference
#include "libbb.h"
Macros
#define OPT_RECURSE (option_mask32 & 1)
#define OPT_VERBOSE (IF_DESKTOP(option_mask32 & 2) IF_NOT_DESKTOP(0))
#define OPT_CHANGED (IF_DESKTOP(option_mask32 & 4) IF_NOT_DESKTOP(0))
#define OPT_QUIET (IF_DESKTOP(option_mask32 & 8) IF_NOT_DESKTOP(0))
#define OPT_STR "R" IF_DESKTOP("vcf")
Functions
static int FAST_FUNC fileAction (struct recursive_state *state, const char *fileName, struct stat *statbuf)
int chmod_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
OPT_CHANGED
#define OPT_CHANGED (IF_DESKTOP(option_mask32 & 4) IF_NOT_DESKTOP(0))
Definition at line 56 of file chmod.c.
OPT_QUIET
#define OPT_QUIET (IF_DESKTOP(option_mask32 & 8) IF_NOT_DESKTOP(0))
Definition at line 57 of file chmod.c.
OPT_RECURSE
#define OPT_RECURSE (option_mask32 & 1)
Definition at line 54 of file chmod.c.
OPT_STR
#define OPT_STR "R" IF_DESKTOP("vcf")
Definition at line 58 of file chmod.c.
OPT_VERBOSE
#define OPT_VERBOSE (IF_DESKTOP(option_mask32 & 2) IF_NOT_DESKTOP(0))
Definition at line 55 of file chmod.c.
Function Documentation
chmod_main()
int chmod_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 107 of file chmod.c.
 {
     int retval = EXIT_SUCCESS;
     char *arg, **argp;
     char *smode;
     /* Convert first encountered -r into ar, -w into aw etc
      * so that getopt would not eat it */
     argp = argv;
     while ((arg = *++argp)) {
         /* Mode spec must be the first arg (sans -R etc) */
         /* (protect against mishandling e.g. "chmod 644 -r") */
         if (arg[0] != '-') {
             arg = NULL;
             break;
         }
         /* An option. Not a -- or valid option? */
         if (arg[1] && !strchr("-"OPT_STR, arg[1])) {
             arg[0] = 'a';
             break;
         }
     }
     /* Parse options */
     getopt32(argv, "^" OPT_STR "\0" "-2");
     argv += optind;
     /* Restore option-like mode if needed */
     if (arg) arg[0] = '-';
     /* Ok, ready to do the deed now */
     smode = *argv++;
     do {
         if (!recursive_action(*argv,
             OPT_RECURSE,    // recurse
             fileAction,     // file action
             fileAction,     // dir action
             smode)          // user data
         ) {
             retval = EXIT_FAILURE;
         }
     } while (*++argv);
     return retval;
 }
References argv, EXIT_FAILURE, EXIT_SUCCESS, fileAction(), getopt32(), NULL, OPT_RECURSE, OPT_STR, optind, recursive_action(), retval, and strchr().
fileAction()
static int FAST_FUNC fileAction (struct recursive_state * state, const char * fileName, struct stat * statbuf) static
Definition at line 69 of file chmod.c.
 {
     mode_t newmode;
     /* match coreutils behavior */
     if (state->depth == 0) {
         /* statbuf holds lstat result, but we need stat (follow link) */
         if (stat(fileName, statbuf))
             goto err;
     } else { /* depth > 0: skip links */
         if (S_ISLNK(statbuf->st_mode))
             return TRUE;
     }
     newmode = bb_parse_mode((char *)state->userData, statbuf->st_mode);
     if (newmode == (mode_t)-1)
         bb_error_msg_and_die("invalid mode '%s'", (char *)state->userData);
     if (chmod(fileName, newmode) == 0) {
         if (OPT_VERBOSE
          || (OPT_CHANGED
              && (statbuf->st_mode & 07777) != (newmode & 07777))
         ) {
             char modestr[12];
             printf("mode of '%s' changed to %04o (%s)\n", fileName,
                 newmode & 07777, bb_mode_string(modestr, newmode)+1);
         }
         return TRUE;
     }
  err:
     if (!OPT_QUIET)
         bb_simple_perror_msg(fileName);
     return FALSE;
 }
References bb_error_msg_and_die(), bb_mode_string(), bb_parse_mode(), bb_simple_perror_msg(), chmod(), err(), FALSE, fileName, mode_t, OPT_CHANGED, OPT_QUIET, OPT_VERBOSE, printf(), S_ISLNK, stat::st_mode, stat(), state, and TRUE.
Referenced by chmod_main(), and recursive_action().