Fennix: Userspace/musl/src/include/sys/membarrier.h File Reference
membarrier.h File Reference
#include "../../../include/sys/membarrier.h"
#include <features.h>
Functions
hidden int __membarrier (int, int)
Function Documentation
__membarrier()
hidden int __membarrier (int cmd, int flags)
Definition at line 22 of file membarrier.c.
 {
     int r = __syscall(SYS_membarrier, cmd, flags);
     /* Emulate the private expedited command, which is needed by the
      * dynamic linker for installation of dynamic TLS, for older
      * kernels that lack the syscall. Unlike the syscall, this only
      * synchronizes with threads of the process, not other processes
      * sharing the VM, but such sharing is not a supported usage
      * anyway. */
     if (r && cmd == MEMBARRIER_CMD_PRIVATE_EXPEDITED && !flags) {
         pthread_t self=__pthread_self(), td;
         sigset_t set;
         __block_app_sigs(&set);
         __tl_lock();
         sem_init(&barrier_sem, 0, 0);
         struct sigaction sa = {
             .sa_flags = SA_RESTART | SA_ONSTACK,
             .sa_handler = bcast_barrier
         };
         memset(&sa.sa_mask, -1, sizeof sa.sa_mask);
         if (!__libc_sigaction(SIGSYNCCALL, &sa, 0)) {
             for (td=self->next; td!=self; td=td->next)
                 __syscall(SYS_tkill, td->tid, SIGSYNCCALL);
             for (td=self->next; td!=self; td=td->next)
                 sem_wait(&barrier_sem);
             r = 0;
             sa.sa_handler = SIG_IGN;
             __libc_sigaction(SIGSYNCCALL, &sa, 0);
         }
         sem_destroy(&barrier_sem);
         __tl_unlock();
         __restore_sigs(&set);
     }
     return __syscall_ret(r);
 }
References __block_app_sigs(), __libc_sigaction(), __pthread_self, __restore_sigs(), __syscall, __syscall_ret(), __tl_lock(), __tl_unlock(), barrier_sem, bcast_barrier(), flags, MEMBARRIER_CMD_PRIVATE_EXPEDITED, memset, r, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, SA_ONSTACK, SA_RESTART, sem_destroy(), sem_init(), sem_wait(), SIG_IGN, and SIGSYNCCALL.
Referenced by install_new_tls().