Fennix: anonymous_namespace{grp-stubs.cpp} Namespace Reference
anonymous_namespace{grp-stubs.cpp} Namespace Reference
Functions
bool open_global_file ()
void close_global_file ()
template<typename F >
void walk_segments (frg::string_view line, char delimiter, F fn)
bool extract_entry (frg::string_view line, group *entry)
void clear_entry (group *entry)
template<typename C >
int walk_file (struct group *entry, C cond)
int copy_to_buffer (struct group *grp, char *buffer, size_t size)
Variables
FILE * global_file
Function Documentation
clear_entry()
void anonymous_namespace{grp-stubs.cpp}::clear_entry (group * entry)
Definition at line 103 of file grp-stubs.cpp.
{
         free(entry->gr_name);
         if(entry->gr_mem) {
             for(size_t i = 0; entry->gr_mem[i]; i++)
                 free(entry->gr_mem[i]);
             free(entry->gr_mem);
         }
         entry->gr_name = nullptr;
         entry->gr_mem = nullptr;
     }
References free(), group::gr_mem, group::gr_name, and i.
Referenced by getgrent().
close_global_file()
void anonymous_namespace{grp-stubs.cpp}::close_global_file ()
Definition at line 27 of file grp-stubs.cpp.
{
         if(global_file) {
             fclose(global_file);
             global_file = nullptr;
         }
     }
References fclose(), and global_file.
Referenced by endgrent().
copy_to_buffer()
int anonymous_namespace{grp-stubs.cpp}::copy_to_buffer (struct group * grp, char * buffer, size_t size)
Definition at line 140 of file grp-stubs.cpp.
{
         // Adjust to correct alignment so that we can put gr_mem first in buffer
         uintptr_t mask = sizeof(char *) - 1;
         size_t offset = (reinterpret_cast<uintptr_t>(buffer) % sizeof(char *) + mask) & ~mask;
         if (size < offset)
             return ERANGE;
         buffer += offset;
         size -= offset;
         // Calculate the amount of space we need
         size_t nmemb, required_size = 0;
         for (nmemb = 0; grp->gr_mem[nmemb] != nullptr; nmemb++) {
             // One for the string's null terminator and one for the pointer in gr_mem
             required_size += strlen(grp->gr_mem[nmemb]) + 1 + sizeof(char *);
         }
         // One for null terminator of gr_name, plus sizeof(char *) for nullptr terminator of gr_mem
         required_size += strlen(grp->gr_name) + 1 + sizeof(char *);
         if (size < required_size)
             return ERANGE;
         // Put the gr_mem array first in the buffer as we are guaranteed
         // that the pointer is aligned correctly
         char *string_data = buffer + (nmemb + 1) * sizeof(char *);
         for (size_t i = 0; i < nmemb; i++) {
             reinterpret_cast<char **>(buffer)[i] = string_data;
             string_data = stpcpy(string_data, grp->gr_mem[i]) + 1;
             free(grp->gr_mem[i]);
         }
         reinterpret_cast<char **>(buffer)[nmemb] = nullptr;
         free(grp->gr_mem);
         grp->gr_mem = reinterpret_cast<char **>(buffer);
         char *gr_name = stpcpy(string_data, grp->gr_name) + 1;
         free(grp->gr_name);
         grp->gr_name = string_data;
         __ensure(gr_name <= buffer + size);
         return 0;
     }
References __ensure, ERANGE, free(), group::gr_mem, group::gr_name, i, offset, size, stpcpy(), and strlen().
Referenced by getgrgid_r(), and getgrnam_r().
extract_entry()
bool anonymous_namespace{grp-stubs.cpp}::extract_entry (frg::string_view line, group * entry)
Definition at line 58 of file grp-stubs.cpp.
{
         frg::string_view segments[5];
         // Parse the line into 3 or 4 segments (depending if the group has members or not)
         int n = 0;
         walk_segments(line, ':', [&] (frg::string_view s) {
             __ensure(n < 4);
             segments[n++] = s;
         });
         if(n < 3) // n can be 3 when there are no members in the group
             return false;
         // TODO: Handle strndup() and malloc() failure.
         auto name = strndup(segments[0].data(), segments[0].size());
         __ensure(name);
         auto passwd = strndup(segments[1].data(), segments[1].size());
         auto gid = segments[2].to_number<int>();
         if(!gid)
             return false;
         size_t n_members = 0;
         walk_segments(segments[3], ',', [&] (frg::string_view) {
             n_members++;
         });
         auto members = reinterpret_cast<char **>(malloc(sizeof(char *) * (n_members + 1)));
         __ensure(members);
         size_t k = 0;
         walk_segments(segments[3], ',', [&] (frg::string_view m) {
             members[k] = strndup(m.data(), m.size());
             __ensure(members[k]);
             k++;
         });
         members[k] = nullptr;
         entry->gr_name = name;
         entry->gr_passwd = passwd;
         entry->gr_gid = *gid;
         entry->gr_mem = members;
         return true;
     }
References __ensure, group::gr_gid, group::gr_mem, group::gr_name, group::gr_passwd, k, malloc(), n, name, size, strndup(), and walk_segments().
Referenced by getgrent(), and walk_file().
open_global_file()
bool anonymous_namespace{grp-stubs.cpp}::open_global_file ()
Definition at line 15 of file grp-stubs.cpp.
{
         if(!global_file) {
             global_file = fopen("/etc/group", "r");
             if(!global_file) {
                 errno = EIO;
                 return false;
             }
         }
         return true;
     }
References EIO, errno, fopen(), and global_file.
Referenced by getgrent(), and setgrent().
walk_file()
template<typename C > int anonymous_namespace{grp-stubs.cpp}::walk_file (struct group * entry, C cond)
Definition at line 115 of file grp-stubs.cpp.
{
         auto file = fopen("/etc/group", "r");
         if(!file) {
             return EIO;
         }
         char line[512];
         while(fgets(line, 512, file)) {
             if(!extract_entry(line, entry))
                 continue;
             if(cond(entry)) {
                 fclose(file);
                 return 0;
             }
         }
         int err = ESRCH;
         if(ferror(file)) {
             err = EIO;
         }
         fclose(file);
         return err;
     }
References cond, EIO, ESRCH, extract_entry(), fclose(), ferror(), fgets(), and fopen().
Referenced by getgrgid(), getgrgid_r(), getgrnam(), and getgrnam_r().
walk_segments()
template<typename F > void anonymous_namespace{grp-stubs.cpp}::walk_segments (frg::string_view line, char delimiter, F fn)
Definition at line 35 of file grp-stubs.cpp.
{
         size_t s = 0;
         while(true) {
             size_t d = line.find_first(delimiter, s);
             if(d == size_t(-1))
                 break;
             auto chunk = line.sub_string(s, d - s);
             fn(chunk);
             s = d + 1;
         }
         if(line[s]) {
             auto chunk = line.sub_string(s, line.size() - s);
             if (chunk.size() > 0) {
                 // Remove trailing newline
                 if (chunk[chunk.size() - 1] == '\n')
                     chunk = chunk.sub_string(0, chunk.size() - 1);
                 fn(chunk);
             }
         }
     }
Referenced by extract_entry().
Variable Documentation
global_file
FILE* anonymous_namespace{grp-stubs.cpp}::global_file
Definition at line 13 of file grp-stubs.cpp.
Referenced by close_global_file(), getgrent(), open_global_file(), and setgrent().