Fennix: Userspace/apps/base/busybox/libbb/bb_do_delay.c File Reference
bb_do_delay.c File Reference
#include "libbb.h"
Macros
#define LOGIN_FAIL_DELAY 3
Functions
void FAST_FUNC pause_after_failed_login (void)
void FAST_FUNC sleep1 (void)
void FAST_FUNC msleep (unsigned ms)
Macro Definition Documentation
LOGIN_FAIL_DELAY
#define LOGIN_FAIL_DELAY 3
Definition at line 14 of file bb_do_delay.c.
Function Documentation
msleep()
void FAST_FUNC msleep (unsigned ms)
Definition at line 37 of file bb_do_delay.c.
 {
 #if 0
     /* 1. usleep(n) is not guaranteed by standards to accept n >= 1000000
      * 2. multiplication in usleep(ms * 1000) can overflow if ms > 4294967
      *    (sleep of ~71.5 minutes)
      * Let's play safe and loop:
      */
     while (ms > 500) {
         usleep(500000);
         ms -= 500;
     }
     usleep(ms * 1000);
 #else
 //usleep is often implemented as a call to nanosleep.
 //Simply do the same to implement msleep.
 //it's marginally larger, but wakes your CPU less often:
 //function    old     new   delta
 //msleep       45      52      +7
     struct timespec ts;
     ts.tv_sec = ms / 1000;
     ts.tv_nsec = (ms % 1000) * 1000000;
     /*
      * If a signal has non-default handler, nanosleep returns early.
      * Our version of msleep doesn't return early
      * if interrupted by such signals:
      */
     while (nanosleep(&ts, &ts) != 0)
         continue;
 #endif
 }
References nanosleep(), timespec::tv_nsec, timespec::tv_sec, and usleep().
Referenced by beep_main(), chat_main(), common_traceroute_main(), open_new_state_file(), and watchdog_main().
pause_after_failed_login()
void FAST_FUNC pause_after_failed_login (void)
Definition at line 16 of file bb_do_delay.c.
 {
 #if 0 /* over-engineered madness */
     time_t end, diff;
     end = time(NULL) + LOGIN_FAIL_DELAY;
     diff = LOGIN_FAIL_DELAY;
     do {
         sleep(diff);
         diff = end - time(NULL);
     } while (diff > 0);
 #else
     sleep(LOGIN_FAIL_DELAY);
 #endif
 }
References diff(), end, LOGIN_FAIL_DELAY, NULL, sleep(), and time().
Referenced by login_main(), new_password(), su_main(), sulogin_main(), and vlock_main().
sleep1()
void FAST_FUNC sleep1 (void)
Definition at line 32 of file bb_do_delay.c.
 {
     sleep(1);
 }
References sleep().
Referenced by auto_baud(), chat_main(), ifplugd_main(), inetd_main(), init_main(), load_firmware(), logread_main(), nbdclient_main(), pause_and_low_level_reboot(), restore_state_and_exit(), run_shutdown_and_kill_processes(), runsv_main(), stop_handler(), telnet_main(), timeout_wait(), and wait_one().