Fennix Userspace: Userspace/apps/base/bash/lib/readline/macro.c File Reference
macro.c File Reference
#include <sys/types.h>
#include "ansi_stdlib.h"
#include <stdio.h>
#include "rldefs.h"
#include "readline.h"
#include "history.h"
#include "rlprivate.h"
#include "xmalloc.h"
Data Structures
struct saved_macro
Macros
#define READLINE_LIBRARY
#define MAX_MACRO_LEVEL 16
Functions
void _rl_with_macro_input (char *string)
int _rl_next_macro_key (void)
int _rl_peek_macro_key (void)
int _rl_prev_macro_key (void)
void _rl_push_executing_macro (void)
void _rl_pop_executing_macro (void)
void _rl_add_macro_char (int c)
void _rl_kill_kbd_macro (void)
int rl_start_kbd_macro (int ignore1, int ignore2)
int rl_end_kbd_macro (int count, int ignore)
int rl_call_last_kbd_macro (int count, int ignore)
int rl_print_last_kbd_macro (int count, int ignore)
void rl_push_macro_input (char *macro)
Variables
char * rl_executing_macro = (char *)NULL
static int executing_macro_index
static char * current_macro = (char *)NULL
static int current_macro_size
static int current_macro_index
static struct saved_macro * macro_list = (struct saved_macro *)NULL
static int macro_level = 0
Data Structure Documentation
saved_macro
struct saved_macro
Definition at line 79 of file macro.c.
Data Fields
struct saved_macro * next
int sindex
char * string
Macro Definition Documentation
MAX_MACRO_LEVEL
#define MAX_MACRO_LEVEL 16
Definition at line 52 of file macro.c.
READLINE_LIBRARY
#define READLINE_LIBRARY
Definition at line 22 of file macro.c.
Function Documentation
_rl_add_macro_char()
void _rl_add_macro_char (int c)
Definition at line 208 of file macro.c.
 {
   if (current_macro_index + 1 >= current_macro_size)
     {
       if (current_macro == 0)
     current_macro = (char *)xmalloc (current_macro_size = 25);
       else
     current_macro = (char *)xrealloc (current_macro, current_macro_size += 25);
     }
   current_macro[current_macro_index++] = c;
   current_macro[current_macro_index] = '\0';
 }
References c, current_macro, current_macro_index, current_macro_size, xmalloc, and xrealloc.
Referenced by _rl_bracketed_text(), _rl_dispatch_subseq(), and _rl_insert_next().
_rl_kill_kbd_macro()
void _rl_kill_kbd_macro (void)
Definition at line 223 of file macro.c.
 {
   if (current_macro)
     {
       xfree (current_macro);
       current_macro = (char *) NULL;
     }
   current_macro_size = current_macro_index = 0;
   FREE (rl_executing_macro);
   rl_executing_macro = (char *) NULL;
   executing_macro_index = 0;
   RL_UNSETSTATE(RL_STATE_MACRODEF);
 }
References current_macro, current_macro_index, current_macro_size, executing_macro_index, FREE, NULL, rl_executing_macro, RL_STATE_MACRODEF, RL_UNSETSTATE, and xfree.
Referenced by _rl_abort_internal(), and rl_free_line_state().
_rl_next_macro_key()
int _rl_next_macro_key (void)
Definition at line 114 of file macro.c.
 {
   int c;
   if (rl_executing_macro == 0)
     return (0);
   if (rl_executing_macro[executing_macro_index] == 0)
     {
       _rl_pop_executing_macro ();
       return (_rl_next_macro_key ());
     }
 #if defined (READLINE_CALLBACKS)
   c = rl_executing_macro[executing_macro_index++];
   if (RL_ISSTATE (RL_STATE_CALLBACK) && RL_ISSTATE (RL_STATE_READCMD|RL_STATE_MOREINPUT) && rl_executing_macro[executing_macro_index] == 0)
       _rl_pop_executing_macro ();
   return c;
 #else
   /* XXX - consider doing the same as the callback code, just not testing
      whether we're running in callback mode */
   return (rl_executing_macro[executing_macro_index++]);
 #endif
 }
References _rl_pop_executing_macro(), c, executing_macro_index, rl_executing_macro, RL_ISSTATE, RL_STATE_CALLBACK, RL_STATE_MOREINPUT, and RL_STATE_READCMD.
Referenced by rl_read_key().
_rl_peek_macro_key()
int _rl_peek_macro_key (void)
Definition at line 140 of file macro.c.
 {
   if (rl_executing_macro == 0)
     return (0);
   if (rl_executing_macro[executing_macro_index] == 0 && (macro_list == 0 || macro_list->string == 0))
     return (0);
   if (rl_executing_macro[executing_macro_index] == 0 && macro_list && macro_list->string)
     return (macro_list->string[0]);
   return (rl_executing_macro[executing_macro_index]);
 }
References executing_macro_index, macro_list, rl_executing_macro, and saved_macro::string.
Referenced by _rl_dispatch_subseq().
_rl_pop_executing_macro()
void _rl_pop_executing_macro (void)
Definition at line 183 of file macro.c.
 {
   struct saved_macro *macro;
   FREE (rl_executing_macro);
   rl_executing_macro = (char *)NULL;
   executing_macro_index = 0;
   if (macro_list)
     {
       macro = macro_list;
       rl_executing_macro = macro_list->string;
       executing_macro_index = macro_list->sindex;
       macro_list = macro_list->next;
       xfree (macro);
     }
   macro_level--;
   if (rl_executing_macro == 0)
     RL_UNSETSTATE(RL_STATE_MACROINPUT);
 }
References executing_macro_index, FREE, macro_level, macro_list, saved_macro::next, NULL, rl_executing_macro, RL_STATE_MACROINPUT, RL_UNSETSTATE, saved_macro::sindex, saved_macro::string, and xfree.
Referenced by _rl_abort_internal(), and _rl_next_macro_key().
_rl_prev_macro_key()
int _rl_prev_macro_key (void)
Definition at line 152 of file macro.c.
 {
   if (rl_executing_macro == 0)
     return (0);
   if (executing_macro_index == 0)
     return (0);
   executing_macro_index--;
   return (rl_executing_macro[executing_macro_index]);
 }
References executing_macro_index, and rl_executing_macro.
Referenced by _rl_dispatch_subseq(), and _rl_subseq_result().
_rl_push_executing_macro()
void _rl_push_executing_macro (void)
Definition at line 166 of file macro.c.
 {
   struct saved_macro *saver;
   saver = (struct saved_macro *)xmalloc (sizeof (struct saved_macro));
   saver->next = macro_list;
   saver->sindex = executing_macro_index;
   saver->string = rl_executing_macro;
   macro_list = saver;
   macro_level++;
 }
References executing_macro_index, macro_level, macro_list, saved_macro::next, rl_executing_macro, saved_macro::sindex, saved_macro::string, and xmalloc.
Referenced by _rl_with_macro_input().
_rl_with_macro_input()
void _rl_with_macro_input (char * string)
Definition at line 93 of file macro.c.
 {
   if (macro_level > MAX_MACRO_LEVEL)
     {
       _rl_errmsg ("maximum macro execution nesting level exceeded");
       _rl_abort_internal ();
       return;
     }
 #if 0
   if (rl_executing_macro)       /* XXX - later */
 #endif
     _rl_push_executing_macro ();
   rl_executing_macro = string;
   executing_macro_index = 0;
   RL_SETSTATE(RL_STATE_MACROINPUT);
 }
References _rl_abort_internal(), _rl_errmsg(), _rl_push_executing_macro(), executing_macro_index, macro_level, MAX_MACRO_LEVEL, rl_executing_macro, RL_SETSTATE, RL_STATE_MACROINPUT, and string.
Referenced by _rl_dispatch_subseq(), rl_call_last_kbd_macro(), rl_push_macro_input(), and rl_start_kbd_macro().
rl_call_last_kbd_macro()
int rl_call_last_kbd_macro (int count, int ignore)
Definition at line 291 of file macro.c.
 {
   if (current_macro == 0)
     _rl_abort_internal ();
   if (RL_ISSTATE (RL_STATE_MACRODEF))
     {
       rl_ding ();       /* no recursive macros */
       current_macro[--current_macro_index] = '\0';  /* erase this char */
       return 0;
     }
   while (count--)
     _rl_with_macro_input (savestring (current_macro));
   return 0;
 }
References _rl_abort_internal(), _rl_with_macro_input(), count, current_macro, current_macro_index, rl_ding(), RL_ISSTATE, RL_STATE_MACRODEF, and savestring().
Referenced by rl_end_kbd_macro().
rl_end_kbd_macro()
int rl_end_kbd_macro (int count, int ignore)
Definition at line 270 of file macro.c.
 {
   if (RL_ISSTATE (RL_STATE_MACRODEF) == 0)
     {
       _rl_abort_internal ();
       return 1;
     }
   current_macro_index -= rl_key_sequence_length;
   if (current_macro_index < 0)
     current_macro_index = 0;
   current_macro[current_macro_index] = '\0';
   RL_UNSETSTATE(RL_STATE_MACRODEF);
   return (rl_call_last_kbd_macro (--count, 0));
 }
References _rl_abort_internal(), count, current_macro, current_macro_index, rl_call_last_kbd_macro(), RL_ISSTATE, rl_key_sequence_length, RL_STATE_MACRODEF, and RL_UNSETSTATE.
rl_print_last_kbd_macro()
int rl_print_last_kbd_macro (int count, int ignore)
Definition at line 309 of file macro.c.
 {
   char *m;
   if (current_macro == 0)
     {
       rl_ding ();
       return 0;
     }
   m = _rl_untranslate_macro_value (current_macro, 1);
   rl_crlf ();
   printf ("%s", m);
   fflush (stdout);
   rl_crlf ();
   FREE (m);
   rl_forced_update_display ();
   rl_display_fixed = 1;
   return 0;
 }
References _rl_untranslate_macro_value(), current_macro, fflush(), FREE, printf(), rl_crlf(), rl_ding(), rl_display_fixed, rl_forced_update_display(), and stdout.
rl_push_macro_input()
void rl_push_macro_input (char * macro)
Definition at line 331 of file macro.c.
 {
   _rl_with_macro_input (macro);
 }
References _rl_with_macro_input().
rl_start_kbd_macro()
int rl_start_kbd_macro (int ignore1, int ignore2)
Definition at line 246 of file macro.c.
 {
   if (RL_ISSTATE (RL_STATE_MACRODEF))
     {
       _rl_abort_internal ();
       return 1;
     }
   if (rl_explicit_arg)
     {
       if (current_macro)
     _rl_with_macro_input (savestring (current_macro));
     }
   else
     current_macro_index = 0;
   RL_SETSTATE(RL_STATE_MACRODEF);
   return 0;
 }
References _rl_abort_internal(), _rl_with_macro_input(), current_macro, current_macro_index, rl_explicit_arg, RL_ISSTATE, RL_SETSTATE, RL_STATE_MACRODEF, and savestring().
Variable Documentation
current_macro
char* current_macro = (char *)NULL static
Definition at line 69 of file macro.c.
Referenced by _rl_add_macro_char(), _rl_kill_kbd_macro(), rl_call_last_kbd_macro(), rl_end_kbd_macro(), rl_print_last_kbd_macro(), and rl_start_kbd_macro().
current_macro_index
int current_macro_index static
Definition at line 75 of file macro.c.
Referenced by _rl_add_macro_char(), _rl_kill_kbd_macro(), rl_call_last_kbd_macro(), rl_end_kbd_macro(), and rl_start_kbd_macro().
current_macro_size
int current_macro_size static
Definition at line 72 of file macro.c.
Referenced by _rl_add_macro_char(), and _rl_kill_kbd_macro().
executing_macro_index
int executing_macro_index static
Definition at line 65 of file macro.c.
Referenced by _rl_kill_kbd_macro(), _rl_next_macro_key(), _rl_peek_macro_key(), _rl_pop_executing_macro(), _rl_prev_macro_key(), _rl_push_executing_macro(), and _rl_with_macro_input().
macro_level
int macro_level = 0 static
Definition at line 88 of file macro.c.
Referenced by _rl_pop_executing_macro(), _rl_push_executing_macro(), and _rl_with_macro_input().
macro_list
struct saved_macro* macro_list = (struct saved_macro *)NULL static
Definition at line 86 of file macro.c.
Referenced by _rl_peek_macro_key(), _rl_pop_executing_macro(), and _rl_push_executing_macro().
rl_executing_macro
char* rl_executing_macro = (char *)NULL
Definition at line 62 of file macro.c.
Referenced by _rl_abort_internal(), _rl_kill_kbd_macro(), _rl_next_macro_key(), _rl_peek_macro_key(), _rl_pop_executing_macro(), _rl_prev_macro_key(), _rl_push_executing_macro(), _rl_with_macro_input(), rl_restore_state(), and rl_save_state().