Fennix: Userspace/musl/src/misc/ptsname.c File Reference
ptsname.c File Reference
#include <stdlib.h>
#include <errno.h>
Functions
char * ptsname (int fd)
Function Documentation
ptsname()
char* ptsname (int fd)
Definition at line 4 of file ptsname.c.
 {
     static char buf[9 + sizeof(int)*3 + 1];
     int err = __ptsname_r(fd, buf, sizeof buf);
     if (err) {
         errno = err;
         return 0;
     }
     return buf;
 }
References __ptsname_r(), buf, err(), errno, and fd.
Referenced by xgetpty().