Fennix Userspace: Userspace/apps/base/busybox/loginutils/vlock.c File Reference
vlock.c File Reference
#include "libbb.h"
Functions
int vlock_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
vlock_main()
int vlock_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 58 of file vlock.c.
 {
 #ifdef __linux__
     struct vt_mode vtm;
     struct vt_mode ovtm;
 #endif
     struct termios term;
     struct termios oterm;
     struct passwd *pw;
     pw = xgetpwuid(getuid());
     getopt32(argv, "^" "a" "\0" "=0"/* no args!*/);
     /* Ignore some signals so that we don't get killed by them */
     bb_signals(0
         + (1 << SIGTSTP)
         + (1 << SIGTTIN)
         + (1 << SIGTTOU)
         + (1 << SIGHUP )
         + (1 << SIGCHLD) /* paranoia :) */
         + (1 << SIGQUIT)
         + (1 << SIGINT )
         , SIG_IGN);
 #ifdef __linux__
     /* We will use SIGUSRx for console switch control: */
     /* 1: set handlers */
     signal_SA_RESTART_empty_mask(SIGUSR1, release_vt);
     signal_SA_RESTART_empty_mask(SIGUSR2, acquire_vt);
     /* 2: unmask them */
     sig_unblock(SIGUSR1);
     sig_unblock(SIGUSR2);
 #endif
     /* Revert stdin/out to our controlling tty
      * (or die if we have none) */
     xmove_fd(xopen(CURRENT_TTY, O_RDWR), STDIN_FILENO);
     xdup2(STDIN_FILENO, STDOUT_FILENO);
 #ifdef __linux__
     xioctl(STDIN_FILENO, VT_GETMODE, &vtm);
     ovtm = vtm;
     /* "console switches are controlled by us, not kernel!" */
     vtm.mode = VT_PROCESS;
     vtm.relsig = SIGUSR1;
     vtm.acqsig = SIGUSR2;
     ioctl(STDIN_FILENO, VT_SETMODE, &vtm);
 #endif
 //TODO: use set_termios_to_raw()
     tcgetattr(STDIN_FILENO, &oterm);
     term = oterm;
     term.c_iflag |= IGNBRK; /* ignore serial break (why? VTs don't have breaks, right?) */
     term.c_iflag &= ~BRKINT; /* redundant? "dont translate break to SIGINT" */
     term.c_lflag &= ~(ISIG | ECHO | ECHOCTL); /* ignore ^C ^Z, echo off */
     tcsetattr_stdin_TCSANOW(&term);
     while (1) {
         printf("Virtual console%s locked by %s.\n",
                 /* "s" if -a, else "": */ "s" + !option_mask32,
                 pw->pw_name
         );
         if (ask_and_check_password(pw) > 0) {
             break;
         }
         pause_after_failed_login();
         puts("Incorrect password");
     }
 #ifdef __linux__
     ioctl(STDIN_FILENO, VT_SETMODE, &ovtm);
 #endif
     tcsetattr_stdin_TCSANOW(&oterm);
     fflush_stdout_and_exit_SUCCESS();
 }
References argv, ask_and_check_password(), bb_signals(), BRKINT, termios::c_iflag, termios::c_lflag, CURRENT_TTY, ECHO, ECHOCTL, fflush_stdout_and_exit_SUCCESS(), getopt32(), getuid, IGNBRK, ioctl(), ISIG, O_RDWR, option_mask32, pause_after_failed_login(), printf(), puts(), pw, passwd::pw_name, SIG_IGN, sig_unblock(), SIGCHLD, SIGHUP, SIGINT, signal_SA_RESTART_empty_mask(), SIGQUIT, SIGTSTP, SIGTTIN, SIGTTOU, SIGUSR1, SIGUSR2, STDIN_FILENO, STDOUT_FILENO, tcgetattr(), tcsetattr_stdin_TCSANOW(), term, xdup2(), xgetpwuid(), xioctl, xmove_fd(), and xopen().