Fennix Userspace: Userspace/apps/base/busybox/libbb/find_root_device.c File Reference
find_root_device.c File Reference
#include "libbb.h"
Data Structures
struct arena
Enumerations
enum { DEVNAME_MAX = 256 }
Functions
static char * find_block_device_in_dir (struct arena *ap)
char *FAST_FUNC find_block_device (const char *path)
Data Structure Documentation
arena
struct arena
Definition at line 16 of file find_root_device.c.
Data Fields
dev_t dev
char devpath[DEVNAME_MAX]
struct stat st
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DEVNAME_MAX
Definition at line 15 of file find_root_device.c.
 { DEVNAME_MAX = 256 };
Function Documentation
find_block_device()
char* FAST_FUNC find_block_device (const char * path)
Definition at line 65 of file find_root_device.c.
 {
     struct arena a;
     if (stat(path, &a.st) != 0)
         return NULL;
     a.dev = S_ISBLK(a.st.st_mode) ? a.st.st_rdev : a.st.st_dev;
     strcpy(a.devpath, "/dev");
     return find_block_device_in_dir(&a);
 }
Referenced by df_main(), mountpoint_main(), and rdev_main().
find_block_device_in_dir()
static char* find_block_device_in_dir (struct arena * ap) static
Definition at line 24 of file find_root_device.c.
 {
     DIR *dir;
     struct dirent *entry;
     char *retpath = NULL;
     int len, rem;
     len = strlen(ap->devpath);
     rem = DEVNAME_MAX-2 - len;
     if (rem <= 0)
         return NULL;
     dir = opendir(ap->devpath);
     if (!dir)
         return NULL;
     ap->devpath[len++] = '/';
     while ((entry = readdir(dir)) != NULL) {
         safe_strncpy(ap->devpath + len, entry->d_name, rem);
         /* lstat: do not follow links */
         if (lstat(ap->devpath, &ap->st) != 0)
             continue;
         if (S_ISBLK(ap->st.st_mode) && ap->st.st_rdev == ap->dev) {
             retpath = xstrdup(ap->devpath);
             break;
         }
         if (S_ISDIR(ap->st.st_mode)) {
             /* Do not recurse for '.' and '..' */
             if (DOT_OR_DOTDOT(entry->d_name))
                 continue;
             retpath = find_block_device_in_dir(ap);
             if (retpath)
                 break;
         }
     }
     closedir(dir);
     return retpath;
 }
References ap, closedir(), DEVNAME_MAX, dir, DOT_OR_DOTDOT, lstat, NULL, opendir(), readdir(), S_ISBLK, S_ISDIR, safe_strncpy(), strlen(), and xstrdup().