Fennix Userspace: Userspace/musl/src/signal/sigpause.c File Reference
sigpause.c File Reference
#include <signal.h>
Functions
int sigpause (int sig)
Function Documentation
sigpause()
int sigpause (int sig)
Definition at line 3 of file sigpause.c.
 {
     sigset_t mask;
     sigprocmask(0, 0, &mask);
     sigdelset(&mask, sig);
     return sigsuspend(&mask);
 }
References sigdelset(), sigprocmask(), and sigsuspend().