Fennix Userspace: Userspace/libc/include/spawn.h File Reference
spawn.h File Reference
#include <stddef.h>
#include <bits/types/struct_sched_param.h>
#include <bits/types/sigset_t.h>
#include <sys/types.h>
Data Structures
struct __spawn_action
struct posix_spawnattr_t
struct posix_spawn_file_actions_t
Functions
int posix_spawn (pid_t *pid, const char *path, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *attrp, char *const argv[], char *const envp[])
int posix_spawnp (pid_t *pid, const char *file, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *attrp, char *const argv[], char *const envp[])
Data Structure Documentation
__spawn_action
struct __spawn_action
Definition at line 9 of file spawn.h.
Data Fields
int __stub
posix_spawnattr_t
struct posix_spawnattr_t
Definition at line 14 of file spawn.h.
Data Fields
sigset_t __def
short int __flags
int __flags
void * __fn
sigset_t __mask
int __pad[16]
char __pad[64-sizeof(void *)]
pid_t __pgrp
int __pol
int __policy
int __prio
sigset_t __sd
struct sched_param __sp
sigset_t __ss
posix_spawn_file_actions_t
struct posix_spawn_file_actions_t
Definition at line 25 of file spawn.h.
Data Fields
struct __spawn_action * __actions
void * __actions
int __allocated
int __pad[16]
int __pad0[2]
int __used
Function Documentation
posix_spawn()
int posix_spawn (pid_t * pid, const char * path, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t * attrp, char *const argv[], char *const envp[])
Definition at line 3 of file spawn.c.
 {
 }
Referenced by popen(), posix_spawnp(), and system().
posix_spawnp()
int posix_spawnp (pid_t * pid, const char * file, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t * attrp, char *const argv[], char *const envp[])
Definition at line 11 of file spawn.c.
 {
 }