Fennix Userspace: Userspace/musl/src/signal/raise.c File Reference
raise.c File Reference
#include <signal.h>
#include <stdint.h>
#include "syscall.h"
#include "pthread_impl.h"
Functions
int raise (int sig)
Function Documentation
raise()
int raise (int sig)
Definition at line 6 of file raise.c.
 {
     sigset_t set;
     __block_app_sigs(&set);
     int ret = syscall(SYS_tkill, __pthread_self()->tid, sig);
     __restore_sigs(&set);
     return ret;
 }
References __block_app_sigs(), __pthread_self, __restore_sigs(), and syscall().