Fennix: Userspace/apps/base/busybox/coreutils/chroot.c File Reference
chroot.c File Reference
#include "libbb.h"
Functions
int chroot_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
chroot_main()
int chroot_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 38 of file chroot.c.
 {
     ++argv;
     if (!*argv)
         bb_show_usage();
     xchroot(*argv);
     ++argv;
     if (!*argv) { /* no 2nd param (PROG), use shell */
         argv -= 2;
         argv[0] = (char *) get_shell_name();
         argv[1] = (char *) "-i"; /* GNU coreutils 8.4 compat */
         /*argv[2] = NULL; - already is */
     }
     BB_EXECVP_or_die(argv);
 }
References argv, BB_EXECVP_or_die(), bb_show_usage(), get_shell_name(), and xchroot().