Fennix: Userspace/libc/src/std/string/string.c File Reference
string.c File Reference
#include <string.h>
#include "../../mem/liballoc_1_1.h"
Functions
size_t strlen (const char *str)
int strcmp (const char *l, const char *r)
int strncmp (const char *s1, const char *s2, size_t n)
int strcasecmp (const char *s1, const char *s2)
int strncasecmp (const char *string1, const char *string2, size_t count)
char * strstr (const char *haystack, const char *needle)
char * strncpy (char *destination, const char *source, unsigned long num)
char * strdup (const char *s)
char * strchr (char const *s, int c)
char * strrchr (char const *s, int c)
Function Documentation
strcasecmp()
int strcasecmp (const char * s1, const char * s2)
Definition at line 34 of file string.c.
 {
     const unsigned char *p1 = (const unsigned char *)s1;
     const unsigned char *p2 = (const unsigned char *)s2;
     int result;
     if (p1 == p2)
         return 0;
     while ((result = tolower(*p1) - tolower(*p2++)) == 0)
         if (*p1++ == '\0')
             break;
     return result;
 }
References mlibc::result, s1, s2, and tolower.
strchr()
char* strchr (char const * s, int c)
Definition at line 103 of file string.c.
 {
     size_t len = strlen(s);
     for (size_t i = 0; i < len; i++)
         if (s[i] == c)
             return (char *)s + i;
     return NULL;
 }
References c, i, len, NULL, and strlen().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 14 of file string.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
References r.
Referenced by main().
strdup()
char* strdup (const char * s)
Definition at line 96 of file string.c.
 {
     char *buf = (char *)__malloc(strlen((char *)s) + 1);
     strncpy(buf, s, strlen(s) + 1);
     return buf;
 }
References __malloc, buf, strlen(), and strncpy().
strlen()
size_t strlen (const char * str)
Definition at line 5 of file string.c.
 {
     long unsigned i = 0;
     if (str)
         while (str[i] != '\0')
             ++i;
     return i;
 }
Referenced by strchr(), strdup(), and strrchr().
strncasecmp()
int strncasecmp (const char * string1, const char * string2, size_t count)
Definition at line 47 of file string.c.
 {
     if (count)
     {
         const unsigned char *s1 = (const unsigned char *)string1;
         const unsigned char *s2 = (const unsigned char *)string2;
         int result;
         do
         {
             if ((result = tolower(*s1) - tolower(*s2++)) != 0 || !*s1++)
                 break;
         } while (--count);
         return result;
     }
     return 0;
 }
strncmp()
int strncmp (const char * s1, const char * s2, size_t n)
Definition at line 21 of file string.c.
 {
     for (size_t i = 0; i < n; i++)
     {
         char c1 = s1[i], c2 = s2[i];
         if (c1 != c2)
             return c1 - c2;
         if (!c1)
             return 0;
     }
     return 0;
 }
References i, n, s1, and s2.
strncpy()
char* strncpy (char * destination, const char * source, unsigned long num)
Definition at line 81 of file string.c.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source && num--)
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
References NULL.
Referenced by VirtualFileSystem::Virtual::CreateRoot(), Driver::Driver::Driver(), InitLimineAfterStack(), mlibc::ioctl_drm(), M_StringCopy(), multiboot_main(), ParseConfig(), realpath(), Tasking::TCB::Rename(), strdup(), sys_fork(), mlibc::sys_if_indextoname(), mlibc::sys_if_nametoindex(), and W_AddFile().
strrchr()
char* strrchr (char const * s, int c)
Definition at line 113 of file string.c.
 {
     size_t len = strlen(s);
     size_t pos = len;
     while (s[pos] != c && pos-- != 0)
         ;
     if (pos == len)
         return NULL;
     return (char *)s + pos;
 }
strstr()
char* strstr (const char * haystack, const char * needle)
Definition at line 64 of file string.c.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }
References b, and NULL.