Fennix: Userspace/apps/base/busybox/libbb/llist.c File Reference
llist.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC llist_add_to (llist_t **old_head, void *data)
void FAST_FUNC llist_add_to_end (llist_t **list_head, void *data)
void *FAST_FUNC llist_pop (llist_t **head)
void FAST_FUNC llist_unlink (llist_t **head, llist_t *elm)
void FAST_FUNC llist_free (llist_t *elm, void(*freeit)(void *data))
llist_t *FAST_FUNC llist_rev (llist_t *list)
llist_t *FAST_FUNC llist_find_str (llist_t *list, const char *str)
Function Documentation
llist_add_to()
void FAST_FUNC llist_add_to (llist_t ** old_head, void * data)
Definition at line 15 of file llist.c.
 {
     llist_t *new_head = xmalloc(sizeof(llist_t));
     new_head->data = data;
     new_head->link = *old_head;
     *old_head = new_head;
 }
References llist_t::data, llist_t::link, and xmalloc.
Referenced by add_peers(), append_control_file_to_llist(), concat_option(), config_file_action(), dpkg_deb_main(), dpkg_main(), get_header_tar(), grep_main(), init_archive_deb_control(), init_archive_deb_data(), iostat_main(), last_main(), load_modules_dep(), load_pattern_list(), load_regexes_from_file(), ntp_init(), parse_module(), putenvp(), read_iface_state(), syslogd_main(), tac_main(), unpack_package(), and unzip_main().
llist_add_to_end()
void FAST_FUNC llist_add_to_end (llist_t ** list_head, void * data)
Definition at line 25 of file llist.c.
 {
     while (*list_head)
         list_head = &(*list_head)->link;
     *list_head = xzalloc(sizeof(llist_t));
     (*list_head)->data = data;
     /*(*list_head)->link = NULL;*/
 }
References llist_t::link, and xzalloc().
Referenced by add_probe(), append(), ar_main(), bbunit_registertest(), chat_main(), create_or_remember_link(), get_block_backed_filesystems(), ifupdown_main(), read_interfaces(), sendmail_main(), string_to_llist(), tar_main(), and vgetopt32().
llist_find_str()
llist_t* FAST_FUNC llist_find_str (llist_t * list, const char * str)
Definition at line 89 of file llist.c.
 {
     while (list) {
         if (strcmp(list->data, str) == 0)
             break;
         list = list->link;
     }
     return list;
 }
References list(), str, and strcmp.
Referenced by do_disk_statistics(), iostat_main(), pidof_main(), and read_interfaces().
llist_free()
void FAST_FUNC llist_free (llist_t * elm, void(*)(void *data) freeit)
Definition at line 64 of file llist.c.
 {
     while (elm) {
         void *data = llist_pop(&elm);
         if (freeit)
             freeit(data);
     }
 }
References llist_pop().
Referenced by d4_run_script(), grep_main(), ifupdown_main(), iostat_main(), last_main(), and pidof_main().
llist_pop()
void* FAST_FUNC llist_pop (llist_t ** head)
Definition at line 35 of file llist.c.
 {
     void *data = NULL;
     llist_t *temp = *head;
     if (temp) {
         data = temp->data;
         *head = temp->link;
         free(temp);
     }
     return data;
 }
References llist_t::data, free, head, llist_t::link, and NULL.
Referenced by awk_main(), depmod_main(), diff_main(), do_modprobe(), edit_file(), env_main(), flush_append(), getopt_main(), ifupdown_main(), llist_free(), modprobe_main(), mount_main(), ntp_init(), run_parts_main(), sed_main(), sendmail_main(), setfiles_main(), sort_main(), syslogd_main(), tac_main(), udhcpc6_main(), udhcpc_main(), unit_main(), unpack_package(), and wget_main().
llist_rev()
llist_t* FAST_FUNC llist_rev (llist_t * list)
Definition at line 75 of file llist.c.
 {
     llist_t *rev = NULL;
     while (list) {
         llist_t *next = list->link;
         list->link = rev;
         rev = list;
         list = next;
     }
     return rev;
 }
References list(), next, and NULL.
Referenced by do_modprobe(), and unpack_package().
llist_unlink()
void FAST_FUNC llist_unlink (llist_t ** head, llist_t * elm)
Definition at line 49 of file llist.c.
 {
     if (!elm)
         return;
     while (*head) {
         if (*head == elm) {
             *head = (*head)->link;
             break;
         }
         head = &(*head)->link;
     }
 }
References head.
Referenced by chat_main(), ifupdown_main(), and last_main().