Fennix: Userspace/musl/src/string/memcmp.c File Reference
memcmp.c File Reference
#include <string.h>
Functions
int memcmp (const void *vl, const void *vr, size_t n)
Function Documentation
memcmp()
int memcmp (const void * vl, const void * vr, size_t n)
Definition at line 3 of file memcmp.c.
 {
     const unsigned char *l=vl, *r=vr;
     for (; n && *l == *r; n--, l++, r++);
     return n ? *l-*r : 0;
 }
References l, and n.
Referenced by __crypt_blowfish(), __crypt_md5(), __crypt_sha256(), __crypt_sha512(), __dls3(), __mkostemps(), __res_msend_rc(), _rl_move_cursor_relative(), argstr(), arpping(), bcmp(), chat_main(), check_magic(), clear_leases(), common_traceroute_main(), conf_read_simple(), do_newlocale(), do_syslogd(), do_tzset(), dolisten(), ACPI::DSDT::DSDT(), Entry(), Disk::Manager::FetchDisks(), find_key_in_der_cert(), find_lease_by_mac(), findString(), flashcp_main(), get(), get_header_tar(), get_static_nip_by_mac(), getnameinfo(), handle_port(), inet_addr_match(), inet_ntop(), is_defined_config(), match(), mkdtemp(), mktemp(), nameif_main(), nbdclient_main(), netlink_msg_to_nameindex(), parse_args(), parse_config_file(), policyof(), print_addrinfo(), pthread_setattr_default_np(), vfs::USTAR::ReadArchive(), recv_pack(), reread_config_file(), reverse_hosts(), strrcmp(), stty_main(), sym_calc_value(), vfs::USTAR::TestArchive(), tls_handshake(), twoway_memmem(), twoway_strstr(), udhcpc_main(), update_line(), volume_id_probe_bcache(), volume_id_probe_btrfs(), volume_id_probe_exfat(), volume_id_probe_hpfs(), volume_id_probe_intel_software_raid(), volume_id_probe_iso9660(), volume_id_probe_jfs(), volume_id_probe_lfs(), volume_id_probe_linux_swap(), volume_id_probe_lsi_mega_raid(), volume_id_probe_luks(), volume_id_probe_lvm2(), volume_id_probe_mac_partition_map(), volume_id_probe_ntfs(), volume_id_probe_nvidia_raid(), volume_id_probe_ocfs2(), volume_id_probe_promise_fasttrack_raid(), volume_id_probe_reiserfs(), volume_id_probe_romfs(), volume_id_probe_udf(), volume_id_probe_vfat(), volume_id_probe_xfs(), write_block(), and xmalloc_fgets_internal().