Fennix: Kernel/syscalls/native/munmap.cpp File Reference
munmap.cpp File Reference
#include <syscalls.hpp>
#include <memory.hpp>
#include <lock.hpp>
#include <exec.hpp>
#include <errno.h>
#include <debug.h>
#include "../../syscalls.h"
#include "../../kernel.h"
#include "../../ipc.h"
Macros
#define SysFrm SyscallsFrame
Functions
int sys_munmap (SysFrm *, void *addr, size_t len)
Macro Definition Documentation
SysFrm
#define SysFrm SyscallsFrame
Definition at line 38 of file munmap.cpp.
Function Documentation
sys_munmap()
int sys_munmap (SysFrm * , void * addr, size_t len)
Definition at line 47 of file munmap.cpp.
 {
     if (uintptr_t(addr) % PAGE_SIZE)
         return -EINVAL;
     if (len == 0)
         return -EINVAL;
     Tasking::PCB *pcb = thisProcess;
     Memory::VirtualMemoryArea *vma = pcb->vma;
     Memory::Virtual vmm = Memory::Virtual(pcb->PageTable);
     for (uintptr_t i = uintptr_t(addr);
          i < uintptr_t(addr) + len;
          i += PAGE_SIZE)
     {
         if (likely(!vmm.Check((void *)i, Memory::G)))
             vmm.Remap((void *)i, (void *)i, Memory::P | Memory::RW);
         else
             warn("%p is a global page", (void *)i);
     }
     /* TODO: Check if the page is allocated
                 and not only mapped */
     vma->FreePages((void *)addr, TO_PAGES(len) + 1);
     return 0;
 }
References addr, Memory::Virtual::Check(), EINVAL, Memory::VirtualMemoryArea::FreePages(), Memory::G, i, len, likely, Memory::P, PAGE_SIZE, Tasking::PCB::PageTable, Memory::Virtual::Remap(), Memory::RW, thisProcess, TO_PAGES, Tasking::PCB::vma, and warn.
Referenced by linux_munmap().