Fennix: Userspace/musl/src/network/socket.c File Reference
socket.c File Reference
#include <sys/socket.h>
#include <fcntl.h>
#include <errno.h>
#include "syscall.h"
Functions
int socket (int domain, int type, int protocol)
Function Documentation
socket()
int socket (int domain, int type, int protocol)
Definition at line 6 of file socket.c.
 {
     int s = __socketcall(socket, domain, type, protocol, 0, 0, 0);
     if ((s==-EINVAL || s==-EPROTONOSUPPORT)
         && (type&(SOCK_CLOEXEC|SOCK_NONBLOCK))) {
         s = __socketcall(socket, domain,
             type & ~(SOCK_CLOEXEC|SOCK_NONBLOCK),
             protocol, 0, 0, 0);
         if (s < 0) return __syscall_ret(s);
         if (type & SOCK_CLOEXEC)
             __syscall(SYS_fcntl, s, F_SETFD, FD_CLOEXEC);
         if (type & SOCK_NONBLOCK)
             __syscall(SYS_fcntl, s, F_SETFL, O_NONBLOCK);
     }
     return __syscall_ret(s);
 }
References __socketcall, __syscall, __syscall_ret(), EINVAL, EPROTONOSUPPORT, F_SETFD, F_SETFL, FD_CLOEXEC, O_NONBLOCK, SOCK_CLOEXEC, SOCK_NONBLOCK, socket(), and type.
Referenced by __lookup_name(), __nscd_query(), __openlog(), __res_msend_rc(), __rtnetlink_enumerate(), NetworkUDP::UDP::Connect(), getaddrinfo(), if_indextoname(), if_nametoindex(), mq_notify(), socket(), and start_tcp().