Fennix Userspace: Userspace/musl/src/math/atan2f.c File Reference
atan2f.c File Reference
#include "libm.h"
Functions
float atan2f (float y, float x)
Variables
static const float pi = 3.1415927410e+00
static const float pi_lo = -8.7422776573e-08
Function Documentation
atan2f()
float atan2f (float y, float x)
Definition at line 22 of file atan2f.c.
 {
     float z;
     uint32_t m,ix,iy;
     if (isnan(x) || isnan(y))
         return x+y;
     GET_FLOAT_WORD(ix, x);
     GET_FLOAT_WORD(iy, y);
     if (ix == 0x3f800000)  /* x=1.0 */
         return atanf(y);
     m = ((iy>>31)&1) | ((ix>>30)&2);  /* 2*sign(x)+sign(y) */
     ix &= 0x7fffffff;
     iy &= 0x7fffffff;
     /* when y = 0 */
     if (iy == 0) {
         switch (m) {
         case 0:
         case 1: return y;   /* atan(+-0,+anything)=+-0 */
         case 2: return  pi; /* atan(+0,-anything) = pi */
         case 3: return -pi; /* atan(-0,-anything) =-pi */
         }
     }
     /* when x = 0 */
     if (ix == 0)
         return m&1 ? -pi/2 : pi/2;
     /* when x is INF */
     if (ix == 0x7f800000) {
         if (iy == 0x7f800000) {
             switch (m) {
             case 0: return  pi/4; /* atan(+INF,+INF) */
             case 1: return -pi/4; /* atan(-INF,+INF) */
             case 2: return 3*pi/4;  /*atan(+INF,-INF)*/
             case 3: return -3*pi/4; /*atan(-INF,-INF)*/
             }
         } else {
             switch (m) {
             case 0: return  0.0f;    /* atan(+...,+INF) */
             case 1: return -0.0f;    /* atan(-...,+INF) */
             case 2: return  pi; /* atan(+...,-INF) */
             case 3: return -pi; /* atan(-...,-INF) */
             }
         }
     }
     /* |y/x| > 0x1p26 */
     if (ix+(26<<23) < iy || iy == 0x7f800000)
         return m&1 ? -pi/2 : pi/2;
     /* z = atan(|y/x|) with correct underflow */
     if ((m&2) && iy+(26<<23) < ix)  /*|y/x| < 0x1p-26, x < 0 */
         z = 0.0;
     else
         z = atanf(fabsf(y/x));
     switch (m) {
     case 0: return z;              /* atan(+,+) */
     case 1: return -z;             /* atan(-,+) */
     case 2: return pi - (z-pi_lo); /* atan(+,-) */
     default: /* case 3 */
         return (z-pi_lo) - pi; /* atan(-,-) */
     }
 }
References atanf(), fabsf(), GET_FLOAT_WORD, isnan, pi, pi_lo, x, and y.
Referenced by cargf(), and catanf().
Variable Documentation
pi
const float pi = 3.1415927410e+00 static
Definition at line 19 of file atan2f.c.
Referenced by atan2f().
pi_lo
const float pi_lo = -8.7422776573e-08 static
Definition at line 20 of file atan2f.c.
Referenced by atan2f().