Fennix: Userspace/apps/base/busybox/procps/free.c File Reference
free.c File Reference
#include "libbb.h"
Data Structures
struct globals
Macros
#define G_unit (1 << 10)
Functions
static const char * scale (struct globals *g, unsigned long d)
static NOINLINE unsigned int parse_meminfo (struct globals *g)
int free_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int free_main (int argc UNUSED_PARAM, char **argv IF_NOT_DESKTOP(UNUSED_PARAM))
Macro Definition Documentation
G_unit
#define G_unit (1 << 10)
Definition at line 65 of file free.c.
Function Documentation
free_main() [1/2]
int free_main (int argc UNUSED_PARAM, char **argv IF_NOT_DESKTOPUNUSED_PARAM)
Definition at line 108 of file free.c.
 {
     struct globals G;
     struct sysinfo info;
     unsigned long long cached, cached_plus_free, available;
     int seen_available;
 #if ENABLE_DESKTOP
     G.unit = 1 << 10;
     if (argv[1] && argv[1][0] == '-') {
         switch (argv[1][1]) {
         case 'b':
             G.unit = 1;
             break;
         case 'k': /* 2^10 */
             /* G.unit = 1 << 10; - already is */
             break;
         case 'm': /* 2^20 */
             G.unit = 1 << 20;
             break;
         case 'g': /* 2^30 */
             G.unit = 1 << 30;
             break;
 //      case 't':
 // -- WRONG, -t is not "terabytes" in procps-ng, it's --total
 //          G.unit = 1 << 40;
 //          break;
         case 'h':
             G.unit = 0; /* human readable */
             break;
         default:
             bb_show_usage();
         }
     }
 #endif
     printf("       %12s%12s%12s%12s%12s%12s\n"
     "Mem:   ",
         "total",
         "used",
         "free",
         "shared", "buff/cache", "available" /* swap and total don't have these columns */
     );
     sysinfo(&info);
     /* Extract cached and memavailable from /proc/meminfo and convert to mem_units */
     seen_available = parse_meminfo(&G);
     G.mem_unit = (info.mem_unit ? info.mem_unit : 1); /* kernels < 2.4.x return mem_unit==0, so cope */
     available = ((unsigned long long) G.available_kb * 1024) / G.mem_unit;
     cached = ((unsigned long long) G.cached_kb * 1024) / G.mem_unit;
     cached += info.bufferram;
     cached += ((unsigned long long) G.reclaimable_kb * 1024) / G.mem_unit;
     cached_plus_free = cached + info.freeram;
     printf("%12s%12s%12s",
         scale(&G, info.totalram),                //total
         scale(&G, info.totalram - cached_plus_free), //used
         scale(&G, info.freeram)                  //free
     );
     /* using two printf's: only 4 auto strings are supported, we need 6 */
     printf("%12s%12s%12s\n",
         scale(&G, info.sharedram),               //shared
         scale(&G, cached),                       //buff/cache
         scale(&G, available)                     //available
     );
     /* On kernels < 3.14, MemAvailable is not provided.
      * Show alternate, more meaningful busy/free numbers by counting
      * buffer cache as free memory. */
     if (!seen_available) {
         printf("-/+ buffers/cache: ");
         printf("%12s%12s%12s\n" + 4,
             scale(&G, info.totalram - cached_plus_free), //used
             scale(&G, cached_plus_free)                  //free
         );
     }
 #if BB_MMU
     printf("Swap:  ");
     printf("%12s%12s%12s\n",
         scale(&G, info.totalswap),                 //total
         scale(&G, info.totalswap - info.freeswap), //used
         scale(&G, info.freeswap)                   //free
     );
 #endif
     return EXIT_SUCCESS;
 }
References argv, bb_show_usage(), EXIT_SUCCESS, G(), info, parse_meminfo(), printf, scale(), and sysinfo().
free_main() [2/2]
int free_main (int argc, char ** argv)
parse_meminfo()
static NOINLINE unsigned int parse_meminfo (struct globals * g) static
Definition at line 81 of file free.c.
 {
     char buf[60]; /* actual lines we expect are ~30 chars or less */
     FILE *fp;
     int seen_cached_and_available_and_reclaimable;
     fp = xfopen_for_read("/proc/meminfo");
     g->cached_kb = g->available_kb = g->reclaimable_kb = 0;
     seen_cached_and_available_and_reclaimable = 3;
     while (fgets(buf, sizeof(buf), fp)) {
         if (sscanf(buf, "Cached: %lu %*s\n", &g->cached_kb) == 1)
             if (--seen_cached_and_available_and_reclaimable == 0)
                 break;
         if (sscanf(buf, "MemAvailable: %lu %*s\n", &g->available_kb) == 1)
             if (--seen_cached_and_available_and_reclaimable == 0)
                 break;
         if (sscanf(buf, "SReclaimable: %lu %*s\n", &g->reclaimable_kb) == 1)
             if (--seen_cached_and_available_and_reclaimable == 0)
                 break;
     }
     /* Have to close because of NOFORK */
     fclose(fp);
     return seen_cached_and_available_and_reclaimable == 0;
 }
References buf, fclose(), fgets, g, sscanf(), and xfopen_for_read().
Referenced by free_main().
scale()
static const char* scale (struct globals * g, unsigned long d) static
Definition at line 71 of file free.c.
 {
     /* Display (size * block_size) with one decimal digit.
      * If display_unit == 0, show value no bigger than 1024 with suffix (K,M,G...),
      * else divide by display_unit and do not use suffix.
      * Returns "auto pointer" */
     return make_human_readable_str(d, g->mem_unit, G_unit);
 }
References g, G_unit, and make_human_readable_str().
Referenced by free_main().