Fennix: InodeOperations Struct Reference
InodeOperations Struct Reference
#include <fs.h>
Data Fields
int(* Lookup)(struct Inode *Parent, const char *Name, struct Inode **Result)
int(* Create)(struct Inode *Parent, const char *Name, mode_t Mode, struct Inode **Result)
int(* Remove)(struct Inode *Parent, const char *Name)
int(* Rename)(struct Inode *Parent, const char *OldName, const char *NewName)
ssize_t(* Read)(struct Inode *Node, void *Buffer, size_t Size, off_t Offset)
ssize_t(* Write)(struct Inode *Node, const void *Buffer, size_t Size, off_t Offset)
int(* Truncate)(struct Inode *Node, off_t Size)
int(* Open)(struct Inode *Node, int Flags, mode_t Mode)
int(* Close)(struct Inode *Node)
int(* Ioctl)(struct Inode *Node, unsigned long Request, void *Argp)
ssize_t(* ReadDir)(struct Inode *Node, struct kdirent *Buffer, size_t Size, off_t Offset, off_t Entries)
int(* MkDir)(struct Inode *Parent, const char *Name, mode_t Mode, struct Inode **Result)
int(* RmDir)(struct Inode *Parent, const char *Name)
int(* SymLink)(struct Inode *Parent, const char *Name, const char *Target, struct Inode **Result)
ssize_t(* ReadLink)(struct Inode *Node, char *Buffer, size_t Size)
off_t(* Seek)(struct Inode *Node, off_t Offset)
int(* Stat)(struct Inode *Node, struct kstat *Stat)
Detailed Description
Definition at line 314 of file fs.h.
Field Documentation
Close
int(* InodeOperations::Close)(struct Inode *Node)
Definition at line 324 of file fs.h.
Referenced by Driver::Manager::InitializeDaemonFS().
Create
int(* InodeOperations::Create)(struct Inode *Parent, const char *Name, mode_t Mode, struct Inode **Result)
Definition at line 317 of file fs.h.
Referenced by Driver::Manager::InitializeDaemonFS(), TestAndInitializeUSTAR(), and vfs::Virtual::Virtual().
Ioctl
int(* InodeOperations::Ioctl)(struct Inode *Node, unsigned long Request, void *Argp)
Definition at line 325 of file fs.h.
Referenced by Driver::Manager::InitializeDaemonFS().
Lookup
int(* InodeOperations::Lookup)(struct Inode *Parent, const char *Name, struct Inode **Result)
Definition at line 316 of file fs.h.
Referenced by Driver::Manager::InitializeDaemonFS(), TestAndInitializeUSTAR(), and vfs::Virtual::Virtual().
MkDir
int(* InodeOperations::MkDir)(struct Inode *Parent, const char *Name, mode_t Mode, struct Inode **Result)
Definition at line 327 of file fs.h.
Open
int(* InodeOperations::Open)(struct Inode *Node, int Flags, mode_t Mode)
Definition at line 323 of file fs.h.
Referenced by Driver::Manager::InitializeDaemonFS().
Read
ssize_t(* InodeOperations::Read)(struct Inode *Node, void *Buffer, size_t Size, off_t Offset)
Definition at line 320 of file fs.h.
Referenced by Driver::Manager::InitializeDaemonFS(), and TestAndInitializeUSTAR().
ReadDir
ssize_t(* InodeOperations::ReadDir)(struct Inode *Node, struct kdirent *Buffer, size_t Size, off_t Offset, off_t Entries)
Definition at line 326 of file fs.h.
Referenced by Driver::Manager::InitializeDaemonFS(), TestAndInitializeUSTAR(), and vfs::Virtual::Virtual().
ReadLink
ssize_t(* InodeOperations::ReadLink)(struct Inode *Node, char *Buffer, size_t Size)
Definition at line 330 of file fs.h.
Referenced by TestAndInitializeUSTAR(), and vfs::Virtual::Virtual().
Remove
int(* InodeOperations::Remove)(struct Inode *Parent, const char *Name)
Definition at line 318 of file fs.h.
Rename
int(* InodeOperations::Rename)(struct Inode *Parent, const char *OldName, const char *NewName)
Definition at line 319 of file fs.h.
RmDir
int(* InodeOperations::RmDir)(struct Inode *Parent, const char *Name)
Definition at line 328 of file fs.h.
Seek
off_t(* InodeOperations::Seek)(struct Inode *Node, off_t Offset)
Definition at line 331 of file fs.h.
Stat
int(* InodeOperations::Stat)(struct Inode *Node, struct kstat *Stat)
Definition at line 332 of file fs.h.
Referenced by TestAndInitializeUSTAR().
SymLink
int(* InodeOperations::SymLink)(struct Inode *Parent, const char *Name, const char *Target, struct Inode **Result)
Definition at line 329 of file fs.h.
Referenced by TestAndInitializeUSTAR().
Truncate
int(* InodeOperations::Truncate)(struct Inode *Node, off_t Size)
Definition at line 322 of file fs.h.
Write
ssize_t(* InodeOperations::Write)(struct Inode *Node, const void *Buffer, size_t Size, off_t Offset)
Definition at line 321 of file fs.h.
Referenced by Driver::Manager::InitializeDaemonFS().
The documentation for this struct was generated from the following file:
Kernel/include/interface/fs.h