Fennix Userspace: Userspace/musl/src/math/logf.c File Reference
logf.c File Reference
#include <math.h>
#include <stdint.h>
#include "libm.h"
#include "logf_data.h"
Macros
#define T __logf_data.tab
#define A __logf_data.poly
#define Ln2 __logf_data.ln2
#define N (1 << LOGF_TABLE_BITS)
#define OFF 0x3f330000
Functions
float logf (float x)
Macro Definition Documentation
A
#define A __logf_data.poly
Definition at line 22 of file logf.c.
Ln2
#define Ln2 __logf_data.ln2
Definition at line 23 of file logf.c.
N
#define N (1 << LOGF_TABLE_BITS)
Definition at line 24 of file logf.c.
OFF
#define OFF 0x3f330000
Definition at line 25 of file logf.c.
T
#define T __logf_data.tab
Definition at line 21 of file logf.c.
Function Documentation
logf()
float logf (float x)
Definition at line 27 of file logf.c.
 {
     double_t z, r, r2, y, y0, invc, logc;
     uint32_t ix, iz, tmp;
     int k, i;
     ix = asuint(x);
     /* Fix sign of zero with downward rounding when x==1.  */
     if (WANT_ROUNDING && predict_false(ix == 0x3f800000))
         return 0;
     if (predict_false(ix - 0x00800000 >= 0x7f800000 - 0x00800000)) {
         /* x < 0x1p-126 or inf or nan.  */
         if (ix * 2 == 0)
             return __math_divzerof(1);
         if (ix == 0x7f800000) /* log(inf) == inf.  */
             return x;
         if ((ix & 0x80000000) || ix * 2 >= 0xff000000)
             return __math_invalidf(x);
         /* x is subnormal, normalize it.  */
         ix = asuint(x * 0x1p23f);
         ix -= 23 << 23;
     }
     /* x = 2^k z; where z is in range [OFF,2*OFF] and exact.
        The range is split into N subintervals.
        The ith subinterval contains z and c is near its center.  */
     tmp = ix - OFF;
     i = (tmp >> (23 - LOGF_TABLE_BITS)) % N;
     k = (int32_t)tmp >> 23; /* arithmetic shift */
     iz = ix - (tmp & 0xff800000);
     invc = T[i].invc;
     logc = T[i].logc;
     z = (double_t)asfloat(iz);
     /* log(x) = log1p(z/c-1) + log(c) + k*Ln2 */
     r = z * invc - 1;
     y0 = logc + (double_t)k * Ln2;
     /* Pipelined polynomial evaluation to approximate log1p(r).  */
     r2 = r * r;
     y = A[1] * r + A[2];
     y = A[0] * r2 + y;
     y = y * r2 + (y0 + r);
     return eval_as_float(y);
 }
References __math_divzerof(), __math_invalidf(), A, asfloat, asuint, eval_as_float(), i, k, Ln2, LOGF_TABLE_BITS, N, OFF, predict_false, r2, T, WANT_ROUNDING, x, y, and y0().
Referenced by __lgammaf_r(), acoshf(), asinhf(), catanf(), clogf(), jnf(), y0f(), and y1f().