Fennix: Userspace/musl/src/ctype/wctrans.c File Reference
wctrans.c File Reference
#include <wctype.h>
#include <string.h>
Functions
wctrans_t wctrans (const char *class)
wint_t towctrans (wint_t wc, wctrans_t trans)
wctrans_t __wctrans_l (const char *s, locale_t l)
wint_t __towctrans_l (wint_t c, wctrans_t t, locale_t l)
weak_alias (__wctrans_l, wctrans_l)
weak_alias (__towctrans_l, towctrans_l)
Function Documentation
__towctrans_l()
wint_t __towctrans_l (wint_t c, wctrans_t t, locale_t l)
Definition at line 23 of file wctrans.c.
 {
     return towctrans(c, t);
 }
References c, t, and towctrans().
__wctrans_l()
wctrans_t __wctrans_l (const char * s, locale_t l)
Definition at line 18 of file wctrans.c.
 {
     return wctrans(s);
 }
References wctrans().
towctrans()
wint_t towctrans (wint_t wc, wctrans_t trans)
Definition at line 11 of file wctrans.c.
 {
     if (trans == (wctrans_t)1) return towupper(wc);
     if (trans == (wctrans_t)2) return towlower(wc);
     return wc;
 }
References towlower(), towupper(), and trans.
Referenced by __towctrans_l(), and towctrans_l().
wctrans()
wctrans_t wctrans (const char * class)
Definition at line 4 of file wctrans.c.
 {
     if (!strcmp(class, "toupper")) return (wctrans_t)1;
     if (!strcmp(class, "tolower")) return (wctrans_t)2;
     return 0;
 }
References strcmp.
Referenced by __wctrans_l().
weak_alias() [1/2]
weak_alias (__towctrans_l , towctrans_l)
weak_alias() [2/2]
weak_alias (__wctrans_l , wctrans_l)