Fennix Userspace: Userspace/apps/base/busybox/libbb/pw_encrypt_des.c File Reference
pw_encrypt_des.c File Reference
Data Structures
struct const_des_ctx
struct des_ctx
Macros
#define USE_PRECOMPUTED_u_sbox 1
#define USE_REPETITIVE_SPEEDUP 0
#define USE_ip_mask 0
#define USE_de_keys 0
#define C (*cctx)
#define init_perm (C.init_perm)
#define final_perm (C.final_perm)
#define m_sbox (C.m_sbox)
#define D (*ctx)
#define const_ctx (D.const_ctx)
#define saltbits (D.saltbits)
#define old_salt (D.old_salt)
#define old_rawkey0 (D.old_rawkey0)
#define old_rawkey1 (D.old_rawkey1)
#define un_pbox (D.un_pbox)
#define inv_comp_perm (D.inv_comp_perm)
#define inv_key_perm (D.inv_key_perm)
#define en_keysl (D.en_keysl)
#define en_keysr (D.en_keysr)
#define de_keysl (D.de_keysl)
#define de_keysr (D.de_keysr)
#define ip_maskl (D.ip_maskl)
#define ip_maskr (D.ip_maskr)
#define fp_maskl (D.fp_maskl)
#define fp_maskr (D.fp_maskr)
#define key_perm_maskl (D.key_perm_maskl)
#define key_perm_maskr (D.key_perm_maskr)
#define comp_maskl (D.comp_maskl)
#define comp_maskr (D.comp_maskr)
#define psbox (D.psbox)
#define DES_OUT_BUFSIZE 21
Functions
static int ascii_to_bin (char ch)
static struct const_des_ctx * const_des_init (void)
static struct des_ctx * des_init (struct des_ctx *ctx, const struct const_des_ctx *cctx)
static void setup_salt (struct des_ctx *ctx, uint32_t salt)
static void des_setkey (struct des_ctx *ctx, const char *key)
static void do_des (struct des_ctx *ctx, uint32_t *l_out, uint32_t *r_out, int count)
static void to64_msb_first (char *s, unsigned v)
static char *NOINLINE des_crypt (struct des_ctx *ctx, char output[DES_OUT_BUFSIZE], const unsigned char *key, const unsigned char *salt_str)
Variables
static const uint8_t IP[64] ALIGN1
static const uint8_t u_sbox [8][32]
static const uint32_t bits32[32] ALIGN4
Data Structure Documentation
const_des_ctx
struct const_des_ctx
Definition at line 225 of file pw_encrypt_des.c.
Data Fields
uint8_t final_perm[64]
uint8_t m_sbox[4][4096]
des_ctx
struct des_ctx
Definition at line 306 of file pw_encrypt_des.c.
Data Fields
uint32_t comp_maskl[8][128]
uint32_t comp_maskr[8][128]
const struct const_des_ctx * const_ctx
uint32_t en_keysl[16]
uint32_t en_keysr[16]
uint32_t fp_maskl[8][256]
uint32_t fp_maskr[8][256]
uint8_t inv_comp_perm[56]
uint8_t inv_key_perm[64]
uint32_t key_perm_maskl[8][128]
uint32_t key_perm_maskr[8][128]
uint32_t psbox[4][256]
uint32_t saltbits
uint8_t un_pbox[32]
Macro Definition Documentation
C
#define C (*cctx)
Definition at line 232 of file pw_encrypt_des.c.
comp_maskl
#define comp_maskl (D.comp_maskl)
Definition at line 347 of file pw_encrypt_des.c.
comp_maskr
#define comp_maskr (D.comp_maskr)
Definition at line 348 of file pw_encrypt_des.c.
const_ctx
#define const_ctx (D.const_ctx)
Definition at line 329 of file pw_encrypt_des.c.
D
#define D (*ctx)
Definition at line 328 of file pw_encrypt_des.c.
de_keysl
#define de_keysl (D.de_keysl)
Definition at line 339 of file pw_encrypt_des.c.
de_keysr
#define de_keysr (D.de_keysr)
Definition at line 340 of file pw_encrypt_des.c.
DES_OUT_BUFSIZE
#define DES_OUT_BUFSIZE 21
Definition at line 695 of file pw_encrypt_des.c.
en_keysl
#define en_keysl (D.en_keysl)
Definition at line 337 of file pw_encrypt_des.c.
en_keysr
#define en_keysr (D.en_keysr)
Definition at line 338 of file pw_encrypt_des.c.
final_perm
#define final_perm (C.final_perm)
Definition at line 234 of file pw_encrypt_des.c.
fp_maskl
#define fp_maskl (D.fp_maskl)
Definition at line 343 of file pw_encrypt_des.c.
fp_maskr
#define fp_maskr (D.fp_maskr)
Definition at line 344 of file pw_encrypt_des.c.
init_perm
#define init_perm (C.init_perm)
Definition at line 233 of file pw_encrypt_des.c.
inv_comp_perm
#define inv_comp_perm (D.inv_comp_perm)
Definition at line 335 of file pw_encrypt_des.c.
inv_key_perm
#define inv_key_perm (D.inv_key_perm)
Definition at line 336 of file pw_encrypt_des.c.
ip_maskl
#define ip_maskl (D.ip_maskl)
Definition at line 341 of file pw_encrypt_des.c.
ip_maskr
#define ip_maskr (D.ip_maskr)
Definition at line 342 of file pw_encrypt_des.c.
key_perm_maskl
#define key_perm_maskl (D.key_perm_maskl)
Definition at line 345 of file pw_encrypt_des.c.
key_perm_maskr
#define key_perm_maskr (D.key_perm_maskr)
Definition at line 346 of file pw_encrypt_des.c.
m_sbox
#define m_sbox (C.m_sbox)
Definition at line 235 of file pw_encrypt_des.c.
old_rawkey0
#define old_rawkey0 (D.old_rawkey0)
Definition at line 332 of file pw_encrypt_des.c.
old_rawkey1
#define old_rawkey1 (D.old_rawkey1)
Definition at line 333 of file pw_encrypt_des.c.
old_salt
#define old_salt (D.old_salt)
Definition at line 331 of file pw_encrypt_des.c.
psbox
#define psbox (D.psbox)
Definition at line 349 of file pw_encrypt_des.c.
saltbits
#define saltbits (D.saltbits)
Definition at line 330 of file pw_encrypt_des.c.
un_pbox
#define un_pbox (D.un_pbox)
Definition at line 334 of file pw_encrypt_des.c.
USE_de_keys
#define USE_de_keys 0
Definition at line 64 of file pw_encrypt_des.c.
USE_ip_mask
#define USE_ip_mask 0
Definition at line 63 of file pw_encrypt_des.c.
USE_PRECOMPUTED_u_sbox
#define USE_PRECOMPUTED_u_sbox 1
Definition at line 61 of file pw_encrypt_des.c.
USE_REPETITIVE_SPEEDUP
#define USE_REPETITIVE_SPEEDUP 0
Definition at line 62 of file pw_encrypt_des.c.
Function Documentation
ascii_to_bin()
static int ascii_to_bin (char ch) static
Definition at line 204 of file pw_encrypt_des.c.
 {
     if (ch > 'z')
         return 0;
     if (ch >= 'a')
         return (ch - 'a' + 38);
     if (ch > 'Z')
         return 0;
     if (ch >= 'A')
         return (ch - 'A' + 12);
     if (ch > '9')
         return 0;
     if (ch >= '.')
         return (ch - '.');
     return 0;
 }
Referenced by des_crypt().
const_des_init()
static struct const_des_ctx* const_des_init (void) static
Definition at line 238 of file pw_encrypt_des.c.
 {
     unsigned i, j, b;
     struct const_des_ctx *cctx;
 #if !USE_PRECOMPUTED_u_sbox
     uint8_t u_sbox[8][64];
     cctx = xmalloc(sizeof(*cctx));
     /* Invert the S-boxes, reordering the input bits. */
     for (i = 0; i < 8; i++) {
         for (j = 0; j < 64; j++) {
             b = (j & 0x20) | ((j & 1) << 4) | ((j >> 1) & 0xf);
             u_sbox[i][j] = sbox[i][b];
         }
     }
     for (i = 0; i < 8; i++) {
         fprintf(stderr, "\t{\t");
         for (j = 0; j < 64; j+=2)
             fprintf(stderr, " 0x%02x,", u_sbox[i][j] + u_sbox[i][j+1]*16);
         fprintf(stderr, "\n\t},\n");
     }
     /*
      * Convert the inverted S-boxes into 4 arrays of 8 bits.
      * Each will handle 12 bits of the S-box input.
      */
     for (b = 0; b < 4; b++)
         for (i = 0; i < 64; i++)
             for (j = 0; j < 64; j++)
                 m_sbox[b][(i << 6) | j] =
                     (uint8_t)((u_sbox[(b << 1)][i] << 4) |
                         u_sbox[(b << 1) + 1][j]);
 #else
     cctx = xmalloc(sizeof(*cctx));
     /*
      * Convert the inverted S-boxes into 4 arrays of 8 bits.
      * Each will handle 12 bits of the S-box input.
      */
     for (b = 0; b < 4; b++)
      for (i = 0; i < 64; i++)
       for (j = 0; j < 64; j++) {
         uint8_t lo, hi;
         hi = u_sbox[(b << 1)][i / 2];
         if (!(i & 1))
             hi <<= 4;
         lo = u_sbox[(b << 1) + 1][j / 2];
         if (j & 1)
             lo >>= 4;
         m_sbox[b][(i << 6) | j] = (hi & 0xf0) | (lo & 0x0f);
     }
 #endif
     /*
      * Set up the initial & final permutations into a useful form.
      */
     for (i = 0; i < 64; i++) {
         final_perm[i] = IP[i] - 1;
 #if USE_ip_mask
         init_perm[final_perm[i]] = (uint8_t)i;
 #endif
     }
     return cctx;
 }
References final_perm, fprintf(), i, init_perm, IP, j, m_sbox, sbox, stderr, u_sbox, and xmalloc.
des_crypt()
static char* NOINLINE des_crypt (struct des_ctx * ctx, char output[DES_OUT_BUFSIZE], const unsigned char * key, const unsigned char * salt_str) static
Definition at line 714 of file pw_encrypt_des.c.
 {
     uint32_t salt, r0, r1, keybuf[2];
     uint8_t *q;
     /* Bad salt? Mimic crypt() API - return NULL */
     if (!salt_str[0] || !salt_str[1])
         return NULL;
     /*
      * Copy the key, shifting each character up by one bit
      * and padding with zeros.
      */
     q = (uint8_t *)keybuf;
     while (q - (uint8_t *)keybuf != 8) {
         *q = *key << 1;
         if (*q)
             key++;
         q++;
     }
     des_setkey(ctx, (char *)keybuf);
     /*
      * salt_str - 2 chars of salt (converted to 12 bits)
      * key - up to 8 characters
      */
     output[0] = salt_str[0];
     output[1] = salt_str[1];
     salt = (ascii_to_bin(salt_str[1]) << 6)
          |  ascii_to_bin(salt_str[0]);
     setup_salt(ctx, salt); /* set ctx->saltbits for do_des() */
     /* Do it. */
     do_des(ctx, /*0, 0,*/ &r0, &r1, 25 /* count */);
     /* Now encode the result. */
 #if 0
 {
     uint32_t l = (r0 >> 8);
     q = (uint8_t *)output + 2;
     *q++ = ascii64[(l >> 18) & 0x3f]; /* bits 31..26 of r0 */
     *q++ = ascii64[(l >> 12) & 0x3f]; /* bits 25..20 of r0 */
     *q++ = ascii64[(l >> 6) & 0x3f]; /* bits 19..14 of r0 */
     *q++ = ascii64[l & 0x3f]; /* bits 13..8 of r0 */
     l = ((r0 << 16) | (r1 >> 16));
     *q++ = ascii64[(l >> 18) & 0x3f]; /* bits 7..2 of r0 */
     *q++ = ascii64[(l >> 12) & 0x3f]; /* bits 1..2 of r0 and 31..28 of r1 */
     *q++ = ascii64[(l >> 6) & 0x3f]; /* bits 27..22 of r1 */
     *q++ = ascii64[l & 0x3f]; /* bits 21..16 of r1 */
     l = r1 << 2;
     *q++ = ascii64[(l >> 12) & 0x3f]; /* bits 15..10 of r1 */
     *q++ = ascii64[(l >> 6) & 0x3f]; /* bits 9..4 of r1 */
     *q++ = ascii64[l & 0x3f]; /* bits 3..0 of r1 + 00 */
     *q = 0;
 }
 #else
     /* Each call takes low-order 24 bits and stores 4 chars */
     /* bits 31..8 of r0 */
     to64_msb_first(output + 2, (r0 >> 8));
     /* bits 7..0 of r0 and 31..16 of r1 */
     to64_msb_first(output + 6, (r0 << 16) | (r1 >> 16));
     /* bits 15..0 of r1 and two zero bits (plus extra zero byte) */
     to64_msb_first(output + 10, (r1 << 8));
     /* extra zero byte is encoded as '.', fixing it */
     output[13] = '\0';
 #endif
     return output;
 }
References ascii64, ascii_to_bin(), des_setkey(), do_des(), keybuf, l, NULL, output, r0, r1, setup_salt(), and to64_msb_first().
des_init()
static struct des_ctx* des_init (struct des_ctx * ctx, const struct const_des_ctx * cctx) static
Definition at line 352 of file pw_encrypt_des.c.
 {
     int i, j, b, k, inbit, obit;
     uint32_t p;
     const uint32_t *bits28, *bits24;
     if (!ctx)
         ctx = xmalloc(sizeof(*ctx));
     const_ctx = cctx;
 #if USE_REPETITIVE_SPEEDUP
     old_rawkey0 = old_rawkey1 = 0;
     old_salt = 0;
 #endif
     //saltbits = 0; /* not needed: we call setup_salt() before do_des() */
     bits28 = bits32 + 4;
     bits24 = bits28 + 4;
     /* Initialise the inverted key permutation. */
     for (i = 0; i < 64; i++) {
         inv_key_perm[i] = 255;
     }
     /*
      * Invert the key permutation and initialise the inverted key
      * compression permutation.
      */
     for (i = 0; i < 56; i++) {
         inv_key_perm[key_perm[i] - 1] = (uint8_t)i;
         inv_comp_perm[i] = 255;
     }
     /* Invert the key compression permutation. */
     for (i = 0; i < 48; i++) {
         inv_comp_perm[comp_perm[i] - 1] = (uint8_t)i;
     }
     /*
      * Set up the OR-mask arrays for the initial and final permutations,
      * and for the key initial and compression permutations.
      */
     for (k = 0; k < 8; k++) {
         uint32_t il, ir;
         uint32_t fl, fr;
         for (i = 0; i < 256; i++) {
 #if USE_ip_mask
             il = 0;
             ir = 0;
 #endif
             fl = 0;
             fr = 0;
             for (j = 0; j < 8; j++) {
                 inbit = 8 * k + j;
                 if (i & bits8[j]) {
 #if USE_ip_mask
                     obit = init_perm[inbit];
                     if (obit < 32)
                         il |= bits32[obit];
                     else
                         ir |= bits32[obit - 32];
 #endif
                     obit = final_perm[inbit];
                     if (obit < 32)
                         fl |= bits32[obit];
                     else
                         fr |= bits32[obit - 32];
                 }
             }
 #if USE_ip_mask
             ip_maskl[k][i] = il;
             ip_maskr[k][i] = ir;
 #endif
             fp_maskl[k][i] = fl;
             fp_maskr[k][i] = fr;
         }
         for (i = 0; i < 128; i++) {
             il = 0;
             ir = 0;
             for (j = 0; j < 7; j++) {
                 inbit = 8 * k + j;
                 if (i & bits8[j + 1]) {
                     obit = inv_key_perm[inbit];
                     if (obit == 255)
                         continue;
                     if (obit < 28)
                         il |= bits28[obit];
                     else
                         ir |= bits28[obit - 28];
                 }
             }
             key_perm_maskl[k][i] = il;
             key_perm_maskr[k][i] = ir;
             il = 0;
             ir = 0;
             for (j = 0; j < 7; j++) {
                 inbit = 7 * k + j;
                 if (i & bits8[j + 1]) {
                     obit = inv_comp_perm[inbit];
                     if (obit == 255)
                         continue;
                     if (obit < 24)
                         il |= bits24[obit];
                     else
                         ir |= bits24[obit - 24];
                 }
             }
             comp_maskl[k][i] = il;
             comp_maskr[k][i] = ir;
         }
     }
     /*
      * Invert the P-box permutation, and convert into OR-masks for
      * handling the output of the S-box arrays setup above.
      */
     for (i = 0; i < 32; i++)
         un_pbox[pbox[i] - 1] = (uint8_t)i;
     for (b = 0; b < 4; b++) {
         for (i = 0; i < 256; i++) {
             p = 0;
             for (j = 0; j < 8; j++) {
                 if (i & bits8[j])
                     p |= bits32[un_pbox[8 * b + j]];
             }
             psbox[b][i] = p;
         }
     }
     return ctx;
 }
References comp_maskl, comp_maskr, const_ctx, ctx, final_perm, fp_maskl, fp_maskr, i, init_perm, inv_comp_perm, inv_key_perm, ip_maskl, ip_maskr, j, k, key_perm_maskl, key_perm_maskr, old_rawkey0, old_rawkey1, old_salt, p, psbox, un_pbox, and xmalloc.
des_setkey()
static void des_setkey (struct des_ctx * ctx, const char * key) static
Definition at line 508 of file pw_encrypt_des.c.
 {
     uint32_t k0, k1, rawkey0, rawkey1;
     int shifts, round;
     rawkey0 = ntohl(*(const uint32_t *) key);
     rawkey1 = ntohl(*(const uint32_t *) (key + 4));
 #if USE_REPETITIVE_SPEEDUP
     if ((rawkey0 | rawkey1)
      && rawkey0 == old_rawkey0
      && rawkey1 == old_rawkey1
     ) {
         /*
          * Already setup for this key.
          * This optimisation fails on a zero key (which is weak and
          * has bad parity anyway) in order to simplify the starting
          * conditions.
          */
         return;
     }
     old_rawkey0 = rawkey0;
     old_rawkey1 = rawkey1;
 #endif
     /*
      * Do key permutation and split into two 28-bit subkeys.
      */
     k0 = key_perm_maskl[0][rawkey0 >> 25]
        | key_perm_maskl[1][(rawkey0 >> 17) & 0x7f]
        | key_perm_maskl[2][(rawkey0 >> 9) & 0x7f]
        | key_perm_maskl[3][(rawkey0 >> 1) & 0x7f]
        | key_perm_maskl[4][rawkey1 >> 25]
        | key_perm_maskl[5][(rawkey1 >> 17) & 0x7f]
        | key_perm_maskl[6][(rawkey1 >> 9) & 0x7f]
        | key_perm_maskl[7][(rawkey1 >> 1) & 0x7f];
     k1 = key_perm_maskr[0][rawkey0 >> 25]
        | key_perm_maskr[1][(rawkey0 >> 17) & 0x7f]
        | key_perm_maskr[2][(rawkey0 >> 9) & 0x7f]
        | key_perm_maskr[3][(rawkey0 >> 1) & 0x7f]
        | key_perm_maskr[4][rawkey1 >> 25]
        | key_perm_maskr[5][(rawkey1 >> 17) & 0x7f]
        | key_perm_maskr[6][(rawkey1 >> 9) & 0x7f]
        | key_perm_maskr[7][(rawkey1 >> 1) & 0x7f];
     /*
      * Rotate subkeys and do compression permutation.
      */
     shifts = 0;
     for (round = 0; round < 16; round++) {
         uint32_t t0, t1;
         shifts += key_shifts[round];
         t0 = (k0 << shifts) | (k0 >> (28 - shifts));
         t1 = (k1 << shifts) | (k1 >> (28 - shifts));
 #if USE_de_keys
         de_keysl[15 - round] =
 #endif
         en_keysl[round] = comp_maskl[0][(t0 >> 21) & 0x7f]
                 | comp_maskl[1][(t0 >> 14) & 0x7f]
                 | comp_maskl[2][(t0 >> 7) & 0x7f]
                 | comp_maskl[3][t0 & 0x7f]
                 | comp_maskl[4][(t1 >> 21) & 0x7f]
                 | comp_maskl[5][(t1 >> 14) & 0x7f]
                 | comp_maskl[6][(t1 >> 7) & 0x7f]
                 | comp_maskl[7][t1 & 0x7f];
 #if USE_de_keys
         de_keysr[15 - round] =
 #endif
         en_keysr[round] = comp_maskr[0][(t0 >> 21) & 0x7f]
                 | comp_maskr[1][(t0 >> 14) & 0x7f]
                 | comp_maskr[2][(t0 >> 7) & 0x7f]
                 | comp_maskr[3][t0 & 0x7f]
                 | comp_maskr[4][(t1 >> 21) & 0x7f]
                 | comp_maskr[5][(t1 >> 14) & 0x7f]
                 | comp_maskr[6][(t1 >> 7) & 0x7f]
                 | comp_maskr[7][t1 & 0x7f];
     }
 }
References comp_maskl, comp_maskr, de_keysl, de_keysr, en_keysl, en_keysr, key_perm_maskl, key_perm_maskr, key_shifts, ntohl(), old_rawkey0, old_rawkey1, round, t0, and t1.
Referenced by des_crypt().
do_des()
static void do_des (struct des_ctx * ctx, uint32_t * l_out, uint32_t * r_out, int count) static
Definition at line 592 of file pw_encrypt_des.c.
 {
     const struct const_des_ctx *cctx = const_ctx;
     /*
      * l_in, r_in, l_out, and r_out are in pseudo-"big-endian" format.
      */
     uint32_t l, r, *kl, *kr;
     uint32_t f = f; /* silence gcc */
     uint32_t r48l, r48r;
     int round;
     /* Do initial permutation (IP). */
 #if USE_ip_mask
     uint32_t l_in = 0;
     uint32_t r_in = 0;
     l = ip_maskl[0][l_in >> 24]
       | ip_maskl[1][(l_in >> 16) & 0xff]
       | ip_maskl[2][(l_in >> 8) & 0xff]
       | ip_maskl[3][l_in & 0xff]
       | ip_maskl[4][r_in >> 24]
       | ip_maskl[5][(r_in >> 16) & 0xff]
       | ip_maskl[6][(r_in >> 8) & 0xff]
       | ip_maskl[7][r_in & 0xff];
     r = ip_maskr[0][l_in >> 24]
       | ip_maskr[1][(l_in >> 16) & 0xff]
       | ip_maskr[2][(l_in >> 8) & 0xff]
       | ip_maskr[3][l_in & 0xff]
       | ip_maskr[4][r_in >> 24]
       | ip_maskr[5][(r_in >> 16) & 0xff]
       | ip_maskr[6][(r_in >> 8) & 0xff]
       | ip_maskr[7][r_in & 0xff];
 #elif 0 /* -65 bytes (using the fact that l_in == r_in == 0) */
     l = r = 0;
     for (round = 0; round < 8; round++) {
         l |= ip_maskl[round][0];
         r |= ip_maskr[round][0];
     }
     bb_error_msg("l:%x r:%x", l, r); /* reports 0, 0 always! */
 #else /* using the fact that ip_maskX[] is constant (written to by des_init) */
     l = r = 0;
 #endif
     do {
         /* Do each round. */
         kl = en_keysl;
         kr = en_keysr;
         round = 16;
         do {
             /* Expand R to 48 bits (simulate the E-box). */
             r48l    = ((r & 0x00000001) << 23)
                 | ((r & 0xf8000000) >> 9)
                 | ((r & 0x1f800000) >> 11)
                 | ((r & 0x01f80000) >> 13)
                 | ((r & 0x001f8000) >> 15);
             r48r    = ((r & 0x0001f800) << 7)
                 | ((r & 0x00001f80) << 5)
                 | ((r & 0x000001f8) << 3)
                 | ((r & 0x0000001f) << 1)
                 | ((r & 0x80000000) >> 31);
             /*
              * Do salting for crypt() and friends, and
              * XOR with the permuted key.
              */
             f = (r48l ^ r48r) & saltbits;
             r48l ^= f ^ *kl++;
             r48r ^= f ^ *kr++;
             /*
              * Do sbox lookups (which shrink it back to 32 bits)
              * and do the pbox permutation at the same time.
              */
             f = psbox[0][m_sbox[0][r48l >> 12]]
               | psbox[1][m_sbox[1][r48l & 0xfff]]
               | psbox[2][m_sbox[2][r48r >> 12]]
               | psbox[3][m_sbox[3][r48r & 0xfff]];
             /* Now that we've permuted things, complete f(). */
             f ^= l;
             l = r;
             r = f;
         } while (--round);
         r = l;
         l = f;
     } while (--count);
     /* Do final permutation (inverse of IP). */
     *l_out  = fp_maskl[0][l >> 24]
         | fp_maskl[1][(l >> 16) & 0xff]
         | fp_maskl[2][(l >> 8) & 0xff]
         | fp_maskl[3][l & 0xff]
         | fp_maskl[4][r >> 24]
         | fp_maskl[5][(r >> 16) & 0xff]
         | fp_maskl[6][(r >> 8) & 0xff]
         | fp_maskl[7][r & 0xff];
     *r_out  = fp_maskr[0][l >> 24]
         | fp_maskr[1][(l >> 16) & 0xff]
         | fp_maskr[2][(l >> 8) & 0xff]
         | fp_maskr[3][l & 0xff]
         | fp_maskr[4][r >> 24]
         | fp_maskr[5][(r >> 16) & 0xff]
         | fp_maskr[6][(r >> 8) & 0xff]
         | fp_maskr[7][r & 0xff];
 }
References bb_error_msg(), const_ctx, count, en_keysl, en_keysr, f, fp_maskl, fp_maskr, ip_maskl, ip_maskr, l, m_sbox, psbox, round, and saltbits.
Referenced by des_crypt().
setup_salt()
static void setup_salt (struct des_ctx * ctx, uint32_t salt) static
Definition at line 486 of file pw_encrypt_des.c.
 {
     uint32_t invbits;
 #if USE_REPETITIVE_SPEEDUP
     if (salt == old_salt)
         return;
     old_salt = salt;
 #endif
     invbits = 0;
     salt |= (1 << 24);
     do {
         invbits = (invbits << 1) + (salt & 1);
         salt >>= 1;
     } while (salt != 1);
     saltbits = invbits;
 }
References old_salt, and saltbits.
Referenced by des_crypt().
to64_msb_first()
static void to64_msb_first (char * s, unsigned v) static
Definition at line 698 of file pw_encrypt_des.c.
 {
 #if 0
     *s++ = ascii64[(v >> 18) & 0x3f]; /* bits 23..18 */
     *s++ = ascii64[(v >> 12) & 0x3f]; /* bits 17..12 */
     *s++ = ascii64[(v >> 6) & 0x3f]; /* bits 11..6 */
     *s   = ascii64[v & 0x3f]; /* bits 5..0 */
 #endif
     *s++ = i64c(v >> 18); /* bits 23..18 */
     *s++ = i64c(v >> 12); /* bits 17..12 */
     *s++ = i64c(v >> 6); /* bits 11..6 */
     *s   = i64c(v); /* bits 5..0 */
 }
References ascii64, i64c(), and s.
Referenced by des_crypt().
Variable Documentation
ALIGN1
const uint8_t bits8 [8] ALIGN1 static
Initial value:
= {
    58, 50, 42, 34, 26, 18, 10,  2, 60, 52, 44, 36, 28, 20, 12,  4,
    62, 54, 46, 38, 30, 22, 14,  6, 64, 56, 48, 40, 32, 24, 16,  8,
    57, 49, 41, 33, 25, 17,  9,  1, 59, 51, 43, 35, 27, 19, 11,  3,
    61, 53, 45, 37, 29, 21, 13,  5, 63, 55, 47, 39, 31, 23, 15,  7
}
Definition at line 68 of file pw_encrypt_des.c.
ALIGN4
const uint32_t bits32 [32] ALIGN4 static
Initial value:
= {
    0x80000000, 0x40000000, 0x20000000, 0x10000000,
    0x08000000, 0x04000000, 0x02000000, 0x01000000,
    0x00800000, 0x00400000, 0x00200000, 0x00100000,
    0x00080000, 0x00040000, 0x00020000, 0x00010000,
    0x00008000, 0x00004000, 0x00002000, 0x00001000,
    0x00000800, 0x00000400, 0x00000200, 0x00000100,
    0x00000080, 0x00000040, 0x00000020, 0x00000010,
    0x00000008, 0x00000004, 0x00000002, 0x00000001
}
Definition at line 189 of file pw_encrypt_des.c.
u_sbox
const uint8_t u_sbox[8][32] static
Definition at line 140 of file pw_encrypt_des.c.
Referenced by const_des_init().