Fennix: Userspace/mlibc/options/posix/include/bits/posix/posix_stdlib.h File Reference
posix_stdlib.h File Reference
#include <bits/posix/locale_t.h>
Functions
long random (void)
double drand48 (void)
void srand48 (long int)
char * initstate (unsigned int, char *, size_t)
char * setstate (char *)
void srandom (unsigned int)
int putenv (char *)
int setenv (const char *, const char *, int)
int unsetenv (const char *)
int mkstemp (char *)
int mkostemp (char *, int flags)
char * mkdtemp (char *path)
char * realpath (const char *__restrict, char *__restrict)
int posix_openpt (int flags)
int grantpt (int fd)
int unlockpt (int fd)
char * ptsname (int fd)
int ptsname_r (int fd, char *buf, size_t len)
double strtod_l (const char *__restrict__ nptr, char **__restrict__ endptr, locale_t loc)
long double strtold_l (const char *__restrict__ nptr, char **__restrict__ endptr, locale_t loc)
float strtof_l (const char *__restrict string, char **__restrict end, locale_t loc)
int getloadavg (double *, int)
char * secure_getenv (const char *)
char * canonicalize_file_name (const char *)
void * reallocarray (void *, size_t, size_t)
int clearenv (void)
Function Documentation
canonicalize_file_name()
char* canonicalize_file_name (const char *)
Definition at line 493 of file posix_stdlib.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
clearenv()
int clearenv (void)
Definition at line 8 of file clearenv.c.
 {
     char **e = __environ;
     __environ = 0;
     if (e) while (*e) __env_rm_add(*e++, 0);
     return 0;
 }
References __env_rm_add(), and __environ.
drand48()
double drand48 (void)
Definition at line 79 of file posix_stdlib.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, __seed48, and erand48().
getloadavg()
int getloadavg (double * a, int n)
Definition at line 472 of file posix_stdlib.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure, i, sysinfo::loads, n, SI_LOAD_SHIFT, and sysinfo().
grantpt()
int grantpt (int fd)
Definition at line 448 of file posix_stdlib.cpp.
                  {
     return 0;
 }
initstate()
char* initstate (unsigned int seed, char * state, size_t size)
Definition at line 108 of file posix_stdlib.cpp.
{
     void *old;
     if(size < 8)
         return 0;
     old = savestate();
     if(size < 32)
         n = 0;
     else if(size < 64)
         n = 7;
     else if(size < 128)
         n = 15;
     else if(size < 256)
         n = 31;
     else
         n = 63;
     x = (uint32_t *)state + 1;
     srandom(seed);
     savestate();
     return (char *)old;
 }
References n, savestate(), seed, size, srandom(), state, and x.
mkdtemp()
char* mkdtemp (char * path)
Definition at line 180 of file posix_stdlib.cpp.
{
     mlibc::infoLogger() << "mlibc mkdtemp(" << pattern << ") called" << frg::endlog;
     auto n = strlen(pattern);
     __ensure(n >= 6);
     if(n < 6) {
         errno = EINVAL;
         return NULL;
     }
     for(size_t i = 0; i < 6; i++) {
         if(pattern[n - 6 + i] == 'X')
             continue;
         errno = EINVAL;
         return NULL;
     }
     // TODO: Do an exponential search.
     for(size_t i = 0; i < 999999; i++) {
         __ensure(sprintf(pattern + (n - 6), "%06zu", i) == 6);
         if(int e = mlibc::sys_mkdir(pattern, S_IRWXU); !e) {
             return pattern;
         }else if(e != EEXIST) {
             errno = e;
             return NULL;
         }
     }
     errno = EEXIST;
     return NULL;
 }
References __ensure, __randname(), EEXIST, EINVAL, errno, i, mlibc::infoLogger, memcmp(), memcpy, mkdir(), n, NULL, pattern, S_IRWXU, sprintf(), strlen(), and mlibc::sys_mkdir().
Referenced by sh_mktmpdir().
mkostemp()
int mkostemp (char * pattern, int flags)
Definition at line 142 of file posix_stdlib.cpp.
{
     flags &= ~O_WRONLY;
     auto n = strlen(pattern);
     __ensure(n >= 6);
     if(n < 6) {
         errno = EINVAL;
         return -1;
     }
     for(size_t i = 0; i < 6; i++) {
         if(pattern[n - 6 + i] == 'X')
             continue;
         errno = EINVAL;
         return -1;
     }
     // TODO: Do an exponential search.
     for(size_t i = 0; i < 999999; i++) {
         __ensure(sprintf(pattern + (n - 6), "%06zu", i) == 6);
 //      mlibc::infoLogger() << "mlibc: mkstemp candidate is "
 //              << (const char *)pattern << frg::endlog;
         int fd;
         if(int e = mlibc::sys_open(pattern, O_RDWR | O_CREAT | O_EXCL | flags, S_IRUSR | S_IWUSR, &fd); !e) {
             return fd;
         }else if(e != EEXIST) {
             errno = e;
             return -1;
         }
     }
     errno = EEXIST;
     return -1;
 }
References __ensure, __mkostemps(), EEXIST, EINVAL, errno, flags, i, n, O_CREAT, O_EXCL, O_RDWR, O_WRONLY, pattern, S_IRUSR, S_IWUSR, sprintf(), strlen(), and mlibc::sys_open().
Referenced by mkstemp().
mkstemp()
int mkstemp (char * path)
Definition at line 176 of file posix_stdlib.cpp.
{
     return mkostemp(path, 0);
 }
References __mkostemps(), and mkostemp().
Referenced by sh_mktmpfd().
posix_openpt()
int posix_openpt (int flags)
Definition at line 433 of file posix_stdlib.cpp.
{
     int fd;
     if(int e = mlibc::sys_open("/dev/ptmx", flags, 0, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References EAGAIN, ENOSPC, errno, flags, open(), r, and mlibc::sys_open().
ptsname()
char* ptsname (int fd)
Definition at line 424 of file posix_stdlib.cpp.
                       {
     int index;
     static char buffer[128];
     if(ioctl(fd, TIOCGPTN, &index))
         return NULL;
     snprintf(buffer, 128, "/dev/pts/%d", index);
     return buffer;
 }
References __ptsname_r(), buf, buffer, err(), errno, index, int, ioctl(), NULL, snprintf(), and TIOCGPTN.
ptsname_r()
int ptsname_r (int fd, char * buf, size_t len)
Definition at line 413 of file posix_stdlib.cpp.
{
     int index;
     if(ioctl(fd, TIOCGPTN, &index))
         return -1;
     if((size_t)snprintf(buffer, length, "/dev/pts/%d", index) >= length) {
         errno = ERANGE;
         return -1;
     }
     return 0;
 }
References ERANGE, errno, index, ioctl(), mlibc::length, snprintf(), and TIOCGPTN.
Referenced by openpty().
putenv()
int putenv (char * s)
Definition at line 41 of file putenv.c.
 {
     size_t l = __strchrnul(s, '=') - s;
     if (!l || !s[l]) return unsetenv(s);
     return __putenv(s, l, 0);
 }
References __putenv(), __strchrnul(), and unsetenv().
random()
long random (void)
Definition at line 62 of file posix_stdlib.cpp.
                   {
     long k;
     if(n == 0) {
         k = x[0] = lcg31(x[0]);
         return k;
     }
     x[i] += x[j];
     k = x[i] >> 1;
     if(++i == n)
         i = 0;
     if(++j == n)
         j = 0;
     return k;
 }
References i, j, k, lcg31(), LOCK, lock, n, UNLOCK, and x.
reallocarray()
void* reallocarray (void * ptr, size_t m, size_t n)
Definition at line 484 of file posix_stdlib.cpp.
{
     if(n && m > -1 / n) {
         errno = ENOMEM;
         return 0;
     }
     return realloc(ptr, m * n);
 }
References ENOMEM, errno, n, and realloc.
Referenced by main().
realpath()
char* realpath (const char * __restrict, char * __restrict)
Definition at line 210 of file posix_stdlib.cpp.
{
     if(debugPathResolution)
         mlibc::infoLogger() << "mlibc realpath(): Called on '" << path << "'" << frg::endlog;
     frg::string_view path_view{path};
     // In case of the root, the string only contains the null-terminator.
     frg::small_vector<char, PATH_MAX, MemoryAllocator> resolv{getAllocator()};
     size_t ps;
     // If the path is relative, we have to preprend the working directory.
     if(path[0] == '/') {
         resolv.push_back(0);
         ps = 1;
     }else{
         MLIBC_CHECK_OR_ENOSYS(mlibc::sys_getcwd, nullptr);
         // Try to getcwd() until the buffer is large enough.
         resolv.resize(128);
         while(true) {
             int e = mlibc::sys_getcwd(resolv.data(), resolv.size());
             if(e == ERANGE) {
                 resolv.resize(2 * resolv.size());
             }else if(!e) {
                 break;
             }else{
                 errno = e;
                 return nullptr;
             }
         }
         frg::string_view cwd_view{resolv.data()};
         if(cwd_view == "/") {
             // Restore our invariant that we only store the null-terminator for the root.
             resolv.resize(1);
             resolv[0] = 0;
         }else{
             resolv.resize(cwd_view.size() + 1);
         }
         ps = 0;
     }
     // Contains unresolved links as a relative path compared to resolv.
     frg::small_vector<char, PATH_MAX, MemoryAllocator> lnk{getAllocator()};
     size_t ls = 0;
     auto process_segment = [&] (frg::string_view s_view) -> int {
         if(debugPathResolution)
             mlibc::infoLogger() << "mlibc realpath(): resolv is '" << resolv.data() << "'"
                     << ", segment is " << s_view.data()
                     << ", size: " << s_view.size() << frg::endlog;
         if(!s_view.size() || s_view == ".") {
             // Keep resolv invariant.
             return 0;
         }else if(s_view == "..") {
             // Remove a single segment from resolv.
             if(resolv.size() > 1) {
                 auto slash = strrchr(resolv.data(), '/');
                 __ensure(slash); // We never remove the leading sla.
                 resolv.resize((slash - resolv.data()) + 1);
                 *slash = 0; // Replace the slash by a null-terminator.
             }
             return 0;
         }
         // Append the segment to resolv.
         auto rsz = resolv.size();
         resolv[rsz - 1] = '/'; // Replace null-terminator by a slash.
         resolv.resize(rsz + s_view.size() + 1);
         memcpy(resolv.data() + rsz, s_view.data(), s_view.size());
         resolv[rsz + s_view.size()] = 0;
         // stat() the path to (1) see if it exists and (2) see if it is a link.
         if(!mlibc::sys_stat) {
             MLIBC_MISSING_SYSDEP();
             return ENOSYS;
         }
         if(debugPathResolution)
             mlibc::infoLogger() << "mlibc realpath(): stat()ing '"
                     << resolv.data() << "'" << frg::endlog;
         struct stat st;
         if(int e = mlibc::sys_stat(mlibc::fsfd_target::path,
                 -1, resolv.data(), AT_SYMLINK_NOFOLLOW, &st); e)
             return e;
         if(S_ISLNK(st.st_mode)) {
             if(debugPathResolution) {
                 mlibc::infoLogger() << "mlibc realpath(): Encountered symlink '"
                     << resolv.data() << "'" << frg::endlog;
             }
             if(!mlibc::sys_readlink) {
                 MLIBC_MISSING_SYSDEP();
                 return ENOSYS;
             }
             ssize_t sz = 0;
             char path[512];
             if (int e = mlibc::sys_readlink(resolv.data(), path, 512, &sz); e)
                 return e;
             if(debugPathResolution) {
                 mlibc::infoLogger() << "mlibc realpath(): Symlink resolves to '"
                     << frg::string_view{path, static_cast<size_t>(sz)} << "'" << frg::endlog;
             }
             if (path[0] == '/') {
                 // Absolute path, replace resolv
                 resolv.resize(sz);
                 strncpy(resolv.data(), path, sz - 1);
                 resolv.data()[sz - 1] = 0;
                 if(debugPathResolution) {
                     mlibc::infoLogger() << "mlibc realpath(): Symlink is absolute, resolv: '"
                         << resolv.data() << "'" << frg::endlog;
                 }
             } else {
                 // Relative path, revert changes to resolv, prepend to lnk
                 resolv.resize(rsz);
                 resolv[rsz - 1] = 0;
                 auto lsz = lnk.size();
                 lnk.resize((lsz - ls) + sz);
                 memmove(lnk.data() + sz, lnk.data() + ls, lsz - ls);
                 memcpy(lnk.data(), path, sz);
                 ls = 0;
                 if(debugPathResolution) {
                     mlibc::infoLogger() << "mlibc realpath(): Symlink is relative, resolv: '"
                         << resolv.data() << "' lnk: '"
                         << frg::string_view{lnk.data(), lnk.size()} << "'" << frg::endlog;
                 }
             }
         }
         return 0;
     };
     // Each iteration of this outer loop consumes segment of the input path.
     // This design avoids copying the input path into lnk;
     // the latter could often involve additional allocations.
     while(ps < path_view.size()) {
         frg::string_view ps_view;
         if(auto slash = strchr(path + ps, '/'); slash) {
             ps_view = frg::string_view{path + ps, static_cast<size_t>(slash - (path + ps))};
         }else{
             ps_view = frg::string_view{path + ps, strlen(path) - ps};
         }
         ps += ps_view.size() + 1;
         // Handle one segment from the input path.
         if(int e = process_segment(ps_view); e) {
             errno = e;
             return nullptr;
         }
         // This inner loop consumes segments of lnk.
         while(ls < lnk.size()) {
             frg::string_view ls_view;
             if(auto slash = strchr(lnk.data() + ls, '/'); slash) {
                 ls_view = frg::string_view{lnk.data() + ls, static_cast<size_t>(slash - (lnk.data() + ls))};
             }else{
                 ls_view = frg::string_view{lnk.data() + ls, strlen(lnk.data()) - ls};
             }
             ls += ls_view.size() + 1;
             // Handle one segment from the link
             if(int e = process_segment(ls_view); e) {
                 errno = e;
                 return nullptr;
             }
         }
         // All of lnk was consumed, reset it
         lnk.resize(0);
         ls = 0;
     }
     if(resolv.size() == 1) {
         resolv.resize(0);
         resolv.push_back('/');
         resolv.push_back(0);
     }
     if(debugPathResolution)
         mlibc::infoLogger() << "mlibc realpath(): Returns '" << resolv.data() << "'" << frg::endlog;
     if(resolv.size() > PATH_MAX) {
         errno = ENAMETOOLONG;
         return nullptr;
     }
     if(!out)
         out = reinterpret_cast<char *>(getAllocator().allocate(resolv.size()));
     strcpy(out, resolv.data());
     return out;
 }
References __ensure, AT_SYMLINK_NOFOLLOW, anonymous_namespace{posix_stdlib.cpp}::debugPathResolution, ENAMETOOLONG, ENOSYS, ERANGE, errno, getAllocator(), mlibc::infoLogger, memcpy, memmove, MLIBC_CHECK_OR_ENOSYS, MLIBC_MISSING_SYSDEP, out(), mlibc::path, PATH_MAX, S_ISLNK, strchr(), strcpy, strlen(), strncpy(), strrchr(), mlibc::sys_getcwd(), mlibc::sys_readlink(), and mlibc::sys_stat().
secure_getenv()
char* secure_getenv (const char * name)
Definition at line 477 of file posix_stdlib.cpp.
{
     if (mlibc::rtdlConfig().secureRequired)
         return NULL;
     else
         return getenv(name);
 }
References getenv, libc, name, NULL, and mlibc::rtdlConfig().
setenv()
int setenv (const char * var, const char * value, int overwrite)
Definition at line 24 of file setenv.c.
 {
     char *s;
     size_t l1, l2;
     if (!var || !(l1 = __strchrnul(var, '=') - var) || var[l1]) {
         errno = EINVAL;
         return -1;
     }
     if (!overwrite && getenv(var)) return 0;
     l2 = strlen(value);
     s = malloc(l1+l2+2);
     if (!s) return -1;
     memcpy(s, var, l1);
     s[l1] = '=';
     memcpy(s+l1+1, value, l2+1);
     return __putenv(s, l1, s);
 }
References __putenv(), __strchrnul(), EINVAL, errno, getenv, malloc, memcpy, strlen(), and value.
Referenced by sh_set_lines_and_columns(), and test7().
setstate()
char* setstate (char * state)
Definition at line 130 of file posix_stdlib.cpp.
{
     void *old;
     old = savestate();
     loadstate((uint32_t *)state);
     return (char *)old;
 }
References loadstate(), LOCK, lock, savestate(), state, and UNLOCK.
srand48()
void srand48 (long int)
Definition at line 84 of file posix_stdlib.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
srandom()
void srandom (unsigned int seed)
Definition at line 90 of file posix_stdlib.cpp.
{
     int k;
     uint64_t s = seed;
     if(n == 0) {
         x[0] = s;
         return;
     }
     i = n == 31 || n == 7 ? 3 : 1;
     j = 0;
     for(k = 0; k < n; k++) {
         s = lcg64(s);
         x[k] = s >> 32;
     }
     // Make sure x contains at least one odd number
     x[0] |= 1;
 }
References i, j, k, lcg64(), n, seed, and x.
Referenced by initstate(), and sh_seedrand().
strtod_l()
double strtod_l (const char *__restrict__ nptr, char **__restrict__ endptr, locale_t loc)
Definition at line 452 of file posix_stdlib.cpp.
{
     mlibc::infoLogger() << "mlibc: strtod_l ignores locale!" << frg::endlog;
     return strtod(nptr, endptr);
 }
References endptr, mlibc::infoLogger, and strtod().
strtof_l()
float strtof_l (const char *__restrict string, char **__restrict end, locale_t loc)
strtold_l()
long double strtold_l (const char *__restrict__ nptr, char **__restrict__ endptr, locale_t loc)
unlockpt()
int unlockpt (int fd)
Definition at line 443 of file posix_stdlib.cpp.
                      {
     int unlock = 0;
     return ioctl(fd, TIOCSPTLCK, &unlock);
 }
References ioctl(), TIOCSPTLCK, and unlock().
unsetenv()
int unsetenv (const char * name)
Definition at line 9 of file unsetenv.c.
 {
     size_t l = __strchrnul(name, '=') - name;
     if (!l || name[l]) {
         errno = EINVAL;
         return -1;
     }
     if (__environ) {
         char **e = __environ, **eo = e;
         for (; *e; e++)
             if (!strncmp(name, *e, l) && l[*e] == '=')
                 __env_rm_add(*e, 0);
             else if (eo != e)
                 *eo++ = *e;
             else
                 eo++;
         if (eo != e) *eo = 0;
     }
     return 0;
 }
References __env_rm_add(), __environ, __strchrnul(), EINVAL, errno, name, and strncmp().
Referenced by putenv().