Fennix: Userspace/apps/base/bash/make_cmd.c File Reference
make_cmd.c File Reference
#include "config.h"
#include <stdio.h>
#include "bashtypes.h"
#include "filecntl.h"
#include "bashansi.h"
#include "bashintl.h"
#include "shell.h"
#include "execute_cmd.h"
#include "parser.h"
#include "flags.h"
#include "input.h"
#include "shmbutil.h"
Macros
#define WDCACHESIZE 128
#define WLCACHESIZE 128
Functions
static COMMAND *make_for_or_select PARAMS ((enum command_type, WORD_DESC *, WORD_LIST *, COMMAND *, int))
static COMMAND *make_until_or_while PARAMS ((enum command_type, COMMAND *, COMMAND *))
void cmd_init ()
WORD_DESC * alloc_word_desc ()
WORD_DESC * make_bare_word (char *string) const
WORD_DESC * make_word_flags (WORD_DESC *w, const char *string)
WORD_DESC * make_word (char *string) const
WORD_DESC * make_word_from_token (int token)
WORD_LIST * make_word_list (WORD_DESC *word, WORD_LIST *wlink)
COMMAND * make_command (enum command_type type, SIMPLE_COM *pointer)
COMMAND * command_connect (COMMAND *com1, COMMAND *com2, int connector)
static COMMAND * make_for_or_select (enum command_type type, WORD_DESC *name, WORD_LIST *map_list, COMMAND *action, int lineno)
COMMAND * make_for_command (WORD_DESC *name, WORD_LIST *map_list, COMMAND *action, int lineno)
COMMAND * make_select_command (WORD_DESC *name, WORD_LIST *map_list, COMMAND *action, int lineno)
COMMAND * make_arith_for_command (WORD_LIST *exprs, COMMAND *action, int lineno)
COMMAND * make_group_command (COMMAND *command)
COMMAND * make_case_command (WORD_DESC *word, PATTERN_LIST *clauses, int lineno)
PATTERN_LIST * make_pattern_list (WORD_LIST *patterns, COMMAND *action)
COMMAND * make_if_command (COMMAND *test, COMMAND *true_case, COMMAND *false_case)
static COMMAND * make_until_or_while (enum command_type which, COMMAND *test, COMMAND *action)
COMMAND * make_while_command (COMMAND *test, COMMAND *action)
COMMAND * make_until_command (COMMAND *test, COMMAND *action)
COMMAND * make_arith_command (WORD_LIST *exp)
COMMAND * make_cond_command (COND_COM *cond_node)
COMMAND * make_bare_simple_command ()
COMMAND * make_simple_command (ELEMENT element, COMMAND *command)
void make_here_document (REDIRECT *temp, int lineno)
REDIRECT * make_redirection (REDIRECTEE source, enum r_instruction instruction, REDIRECTEE dest_and_filename, int flags)
COMMAND * make_function_def (WORD_DESC *name, COMMAND *command, int lineno, int lstart)
COMMAND * make_subshell_command (COMMAND *command)
COMMAND * make_coproc_command (char *name, COMMAND *command)
COMMAND * clean_simple_command (COMMAND *command)
COMMAND * connect_async_list (COMMAND *command, COMMAND *command2, int connector)
Variables
int here_doc_first_line = 0
sh_obj_cache_t wdcache = {0, 0, 0}
sh_obj_cache_t wlcache = {0, 0, 0}
Macro Definition Documentation
WDCACHESIZE
#define WDCACHESIZE 128
Definition at line 55 of file make_cmd.c.
WLCACHESIZE
#define WLCACHESIZE 128
Definition at line 56 of file make_cmd.c.
Function Documentation
alloc_word_desc()
WORD_DESC* alloc_word_desc ()
Definition at line 72 of file make_cmd.c.
 {
   WORD_DESC *temp;
   ocache_alloc (wdcache, WORD_DESC, temp);
   temp->flags = 0;
   temp->word = 0;
   return temp;
 }
References word_desc::flags, ocache_alloc, wdcache, and word_desc::word.
Referenced by command_substitute(), expand_word_internal(), list_remove_pattern(), list_string(), list_transform(), make_bare_word(), param_expand(), parameter_brace_expand(), parameter_brace_expand_indir(), parameter_brace_expand_rhs(), parameter_brace_expand_word(), pos_params_modcase(), pos_params_pat_subst(), read_token_word(), and word_list_split().
clean_simple_command()
COMMAND* clean_simple_command (COMMAND * command)
Definition at line 846 of file make_cmd.c.
 {
   if (command->type != cm_simple)
     command_error ("clean_simple_command", CMDERR_BADTYPE, command->type, 0);
   else
     {
       command->value.Simple->words =
     REVERSE_LIST (command->value.Simple->words, WORD_LIST *);
       command->value.Simple->redirects =
     REVERSE_LIST (command->value.Simple->redirects, REDIRECT *);
     }
   parser_state &= ~PST_REDIRLIST;
   return (command);
 }
References cm_simple, CMDERR_BADTYPE, command_error(), parser_state, PST_REDIRLIST, command::redirects, REVERSE_LIST, command::type, and command::value.
Referenced by yyparse().
cmd_init()
void cmd_init ()
Definition at line 65 of file make_cmd.c.
 {
   ocache_create (wdcache, WORD_DESC, WDCACHESIZE);
   ocache_create (wlcache, WORD_LIST, WLCACHESIZE);
 }
References ocache_create, wdcache, WDCACHESIZE, wlcache, and WLCACHESIZE.
Referenced by main().
command_connect()
COMMAND* command_connect (COMMAND * com1, COMMAND * com2, int connector)
Definition at line 186 of file make_cmd.c.
 {
   CONNECTION *temp;
   temp = (CONNECTION *)xmalloc (sizeof (CONNECTION));
   temp->connector = connector;
   temp->first = com1;
   temp->second = com2;
   return (make_command (cm_connection, (SIMPLE_COM *)temp));
 }
References cm_connection, com2, connection::connector, connection::first, make_command(), connection::second, and xmalloc.
Referenced by connect_async_list(), and yyparse().
connect_async_list()
COMMAND* connect_async_list (COMMAND * command, COMMAND * command2, int connector)
Definition at line 873 of file make_cmd.c.
 {
   COMMAND *t, *t1, *t2;
   t1 = command;
   t = command->value.Connection->second;
   if (!t || (command->flags & CMD_WANT_SUBSHELL) ||
       command->value.Connection->connector != ';')
     {
       t = command_connect (command, command2, connector);
       return t;
     }
   /* This is just defensive programming.  The Yacc precedence rules
      will generally hand this function a command where t points directly
      to the command we want (e.g. given a ; b ; c ; d &, t1 will point
      to the `a ; b ; c' list and t will be the `d').  We only want to do
      this if the list is not being executed as a unit in the background
      with `( ... )', so we have to check for CMD_WANT_SUBSHELL.  That's
      the only way to tell. */
   while (((t->flags & CMD_WANT_SUBSHELL) == 0) && t->type == cm_connection &&
      t->value.Connection->connector == ';')
     {
       t1 = t;
       t = t->value.Connection->second;
     }
   /* Now we have t pointing to the last command in the list, and
      t1->value.Connection->second == t. */
   t2 = command_connect (t, command2, connector);
   t1->value.Connection->second = t2;
   return command;
 }
References cm_connection, CMD_WANT_SUBSHELL, command_connect(), command::flags, t, t1, t2, and command::value.
Referenced by yyparse().
make_arith_command()
COMMAND* make_arith_command (WORD_LIST * exp)
Definition at line 427 of file make_cmd.c.
 {
 #if defined (DPAREN_ARITHMETIC)
   COMMAND *command;
   ARITH_COM *temp;
   command = (COMMAND *)xmalloc (sizeof (COMMAND));
   command->value.Arith = temp = (ARITH_COM *)xmalloc (sizeof (ARITH_COM));
   temp->flags = 0;
   temp->line = line_number;
   temp->exp = exp;
   command->type = cm_arith;
   command->redirects = (REDIRECT *)NULL;
   command->flags = 0;
   return (command);
 #else
   set_exit_status (2);
   return ((COMMAND *)NULL);
 #endif
 }
References cm_arith, exp, command::flags, line_number, NULL, command::redirects, set_exit_status(), command::type, command::value, and xmalloc.
Referenced by yyparse().
make_arith_for_command()
COMMAND* make_arith_for_command (WORD_LIST * exprs, COMMAND * action, int lineno)
Definition at line 265 of file make_cmd.c.
 {
 #if defined (ARITH_FOR_COMMAND)
   ARITH_FOR_COM *temp;
   WORD_LIST *init, *test, *step;
   char *s, *t, *start;
   int nsemi, i;
   init = test = step = (WORD_LIST *)NULL;
   /* Parse the string into the three component sub-expressions. */
   start = t = s = exprs->word->word;
   for (nsemi = 0; ;)
     {
       /* skip whitespace at the start of each sub-expression. */
       while (whitespace (*s))
     s++;
       start = s;
       /* skip to the semicolon or EOS */
       i = skip_to_delim (start, 0, ";", SD_NOJMP|SD_NOPROCSUB);
       s = start + i;
       t = (i > 0) ? substring (start, 0, i) : (char *)NULL;
       nsemi++;
       switch (nsemi)
     {
     case 1:
       init = make_arith_for_expr (t);
       break;
     case 2:
       test = make_arith_for_expr (t);
       break;
     case 3:
       step = make_arith_for_expr (t);
       break;
     }
       FREE (t);
       if (*s == '\0')
     break;
       s++;  /* skip over semicolon */
     }
   if (nsemi != 3)
     {
       if (nsemi < 3)
     parser_error (lineno, _("syntax error: arithmetic expression required"));
       else
     parser_error (lineno, _("syntax error: `;' unexpected"));
       parser_error (lineno, _("syntax error: `((%s))'"), exprs->word->word);
       free (init);
       free (test);
       free (step);
       set_exit_status (2);
       return ((COMMAND *)NULL);
     }
   temp = (ARITH_FOR_COM *)xmalloc (sizeof (ARITH_FOR_COM));
   temp->flags = 0;
   temp->line = lineno;
   temp->init = init ? init : make_arith_for_expr ("1");
   temp->test = test ? test : make_arith_for_expr ("1");
   temp->step = step ? step : make_arith_for_expr ("1");
   temp->action = action;
   dispose_words (exprs);
   return (make_command (cm_arith_for, (SIMPLE_COM *)temp));
 #else
   dispose_words (exprs);
   set_exit_status (2);
   return ((COMMAND *)NULL);
 #endif /* ARITH_FOR_COMMAND */
 }
References _, cm_arith_for, dispose_words(), FREE, free, i, init, lineno, make_command(), NULL, parser_error(), s, SD_NOJMP, SD_NOPROCSUB, set_exit_status(), skip_to_delim(), start, substring(), t, test, whitespace, word_desc::word, word_list::word, and xmalloc.
Referenced by yyparse().
make_bare_simple_command()
COMMAND* make_bare_simple_command ()
Definition at line 496 of file make_cmd.c.
 {
   COMMAND *command;
   SIMPLE_COM *temp;
   command = (COMMAND *)xmalloc (sizeof (COMMAND));
   command->value.Simple = temp = (SIMPLE_COM *)xmalloc (sizeof (SIMPLE_COM));
   temp->flags = 0;
   temp->line = line_number;
   temp->words = (WORD_LIST *)NULL;
   temp->redirects = (REDIRECT *)NULL;
   command->type = cm_simple;
   command->redirects = (REDIRECT *)NULL;
   command->flags = 0;
   return (command);
 }
References cm_simple, command::flags, simple_com::flags, simple_com::line, line_number, NULL, command::redirects, simple_com::redirects, command::type, command::value, simple_com::words, and xmalloc.
Referenced by make_simple_command().
make_bare_word()
WORD_DESC* make_bare_word (char * string) const
Definition at line 83 of file make_cmd.c.
 {
   WORD_DESC *temp;
   temp = alloc_word_desc ();
   if (*string)
     temp->word = savestring (string);
   else
     {
       temp->word = (char *)xmalloc (1);
       temp->word[0] = '\0';
     }
   return (temp);
 }
References alloc_word_desc(), savestring(), word_desc::word, and xmalloc.
Referenced by copy_word(), do_redirection_internal(), expand_prompt_string(), glob_expand_word_list(), list_rest_of_args(), make_word(), munge_list(), and strvec_to_word_list().
make_case_command()
COMMAND* make_case_command (WORD_DESC * word, PATTERN_LIST * clauses, int lineno)
Definition at line 354 of file make_cmd.c.
 {
   CASE_COM *temp;
   temp = (CASE_COM *)xmalloc (sizeof (CASE_COM));
   temp->flags = 0;
   temp->line = lineno;
   temp->word = word;
   temp->clauses = REVERSE_LIST (clauses, PATTERN_LIST *);
   return (make_command (cm_case, (SIMPLE_COM *)temp));
 }
References case_com::clauses, cm_case, case_com::flags, case_com::line, lineno, make_command(), REVERSE_LIST, case_com::word, and xmalloc.
Referenced by yyparse().
make_command()
COMMAND* make_command (enum command_type type, SIMPLE_COM * pointer)
Definition at line 171 of file make_cmd.c.
 {
   COMMAND *temp;
   temp = (COMMAND *)xmalloc (sizeof (COMMAND));
   temp->type = type;
   temp->value.Simple = pointer;
   temp->value.Simple->flags = temp->flags = 0;
   temp->redirects = (REDIRECT *)NULL;
   return (temp);
 }
References NULL, type, and xmalloc.
Referenced by command_connect(), make_arith_for_command(), make_case_command(), make_coproc_command(), make_for_or_select(), make_function_def(), make_group_command(), make_if_command(), make_subshell_command(), and make_until_or_while().
make_cond_command()
COMMAND* make_cond_command (COND_COM * cond_node)
Definition at line 474 of file make_cmd.c.
 {
 #if defined (COND_COMMAND)
   COMMAND *command;
   command = (COMMAND *)xmalloc (sizeof (COMMAND));
   command->value.Cond = cond_node;
   command->type = cm_cond;
   command->redirects = (REDIRECT *)NULL;
   command->flags = 0;
   command->line = cond_node ? cond_node->line : 0;
   return (command);
 #else
   set_exit_status (2);
   return ((COMMAND *)NULL);
 #endif
 }
References cm_cond, command::flags, command::line, cond_com::line, NULL, command::redirects, set_exit_status(), command::type, command::value, and xmalloc.
make_coproc_command()
COMMAND* make_coproc_command (char * name, COMMAND * command)
Definition at line 829 of file make_cmd.c.
 {
   COPROC_COM *temp;
   temp = (COPROC_COM *)xmalloc (sizeof (COPROC_COM));
   temp->name = savestring (name);
   temp->command = command;
   temp->flags = CMD_WANT_SUBSHELL|CMD_COPROC_SUBSHELL;
   return (make_command (cm_coproc, (SIMPLE_COM *)temp));
 }
References cm_coproc, CMD_COPROC_SUBSHELL, CMD_WANT_SUBSHELL, coproc_com::command, coproc_com::flags, make_command(), coproc_com::name, savestring(), and xmalloc.
Referenced by yyparse().
make_for_command()
COMMAND* make_for_command (WORD_DESC * name, WORD_LIST * map_list, COMMAND * action, int lineno)
Definition at line 219 of file make_cmd.c.
 {
   return (make_for_or_select (cm_for, name, map_list, action, lineno));
 }
References cm_for, lineno, and make_for_or_select().
Referenced by yyparse().
make_for_or_select()
static COMMAND* make_for_or_select (enum command_type type, WORD_DESC * name, WORD_LIST * map_list, COMMAND * action, int lineno) static
Definition at line 200 of file make_cmd.c.
 {
   FOR_COM *temp;
   temp = (FOR_COM *)xmalloc (sizeof (FOR_COM));
   temp->flags = 0;
   temp->name = name;
   temp->line = lineno;
   temp->map_list = map_list;
   temp->action = action;
   return (make_command (type, (SIMPLE_COM *)temp));
 }
References for_com::action, for_com::flags, for_com::line, lineno, make_command(), for_com::map_list, for_com::name, type, and xmalloc.
Referenced by make_for_command(), and make_select_command().
make_function_def()
COMMAND* make_function_def (WORD_DESC * name, COMMAND * command, int lineno, int lstart)
Definition at line 775 of file make_cmd.c.
 {
   FUNCTION_DEF *temp;
 #if defined (ARRAY_VARS)
   SHELL_VAR *bash_source_v;
   ARRAY *bash_source_a;
 #endif
   temp = (FUNCTION_DEF *)xmalloc (sizeof (FUNCTION_DEF));
   temp->command = command;
   temp->name = name;
   temp->line = lineno;
   temp->flags = 0;
   command->line = lstart;
   /* Information used primarily for debugging. */
   temp->source_file = 0;
 #if defined (ARRAY_VARS)
   GET_ARRAY_FROM_VAR ("BASH_SOURCE", bash_source_v, bash_source_a);
   if (bash_source_a && array_num_elements (bash_source_a) > 0)
     temp->source_file = array_reference (bash_source_a, 0);
 #endif
   /* Assume that shell functions without a source file before the shell is
      initialized come from the environment.  Otherwise default to "main"
      (usually functions being defined interactively) */
   if (temp->source_file == 0)
     temp->source_file = shell_initialized ? "main" : "environment";
 #if defined (DEBUGGER)
   bind_function_def (name->word, temp, 0);
 #endif
   temp->source_file = temp->source_file ? savestring (temp->source_file) : 0;
   return (make_command (cm_function_def, (SIMPLE_COM *)temp));
 }
References array_num_elements, cm_function_def, function_def::command, function_def::flags, GET_ARRAY_FROM_VAR, command::line, function_def::line, lineno, make_command(), function_def::name, savestring(), shell_initialized, function_def::source_file, word_desc::word, and xmalloc.
Referenced by yyparse().
make_group_command()
COMMAND* make_group_command (COMMAND * command)
Definition at line 343 of file make_cmd.c.
 {
   GROUP_COM *temp;
   temp = (GROUP_COM *)xmalloc (sizeof (GROUP_COM));
   temp->command = command;
   return (make_command (cm_group, (SIMPLE_COM *)temp));
 }
References cm_group, group_com::command, make_command(), and xmalloc.
Referenced by yyparse().
make_here_document()
void make_here_document (REDIRECT * temp, int lineno)
Definition at line 558 of file make_cmd.c.
 {
   int kill_leading, redir_len;
   char *redir_word, *document, *full_line;
   int document_index, document_size, delim_unquoted;
   if (temp->instruction != r_deblank_reading_until &&
       temp->instruction != r_reading_until)
     {
       internal_error (_("make_here_document: bad instruction type %d"), temp->instruction);
       return;
     }
   kill_leading = temp->instruction == r_deblank_reading_until;
   full_line = document = (char *)NULL;
   document_index = document_size = 0;
   delim_unquoted = (temp->redirectee.filename->flags & W_QUOTED) == 0;
   /* Quote removal is the only expansion performed on the delimiter
      for here documents, making it an extremely special case. */
   /* "If any part of word is quoted, the delimiter shall be formed by
      performing quote removal on word." */
   if (delim_unquoted == 0)
     redir_word = string_quote_removal (temp->redirectee.filename->word, 0);
   else
     redir_word = savestring (temp->redirectee.filename->word);
   /* redirection_expand will return NULL if the expansion results in
      multiple words or no words.  Check for that here, and just abort
      this here document if it does. */
   if (redir_word)
     redir_len = strlen (redir_word);
   else
     {
       temp->here_doc_eof = (char *)xmalloc (1);
       temp->here_doc_eof[0] = '\0';
       goto document_done;
     }
   free (temp->redirectee.filename->word);
   temp->here_doc_eof = redir_word;
   /* Read lines from wherever lines are coming from.
      For each line read, if kill_leading, then kill the
      leading tab characters.
      If the line matches redir_word exactly, then we have
      manufactured the document.  Otherwise, add the line to the
      list of lines in the document. */
   /* If the here-document delimiter was quoted, the lines should
      be read verbatim from the input.  If it was not quoted, we
      need to perform backslash-quoted newline removal. */
   while (full_line = read_secondary_line (delim_unquoted))
     {
       register char *line;
       int len;
       here_doc_first_line = 0;
       line = full_line;
       line_number++;
       /* If set -v is in effect, echo the line read.  read_secondary_line/
      read_a_line leaves the newline at the end, so don't print another. */
       if (echo_input_at_read)
     fprintf (stderr, "%s", line);
       if (kill_leading && *line)
     {
       /* Hack:  To be compatible with some Bourne shells, we
          check the word before stripping the whitespace.  This
          is a hack, though. */
       if (STREQN (line, redir_word, redir_len) && line[redir_len] == '\n')
         break;
       while (*line == '\t')
         line++;
     }
       if (*line == 0)
     continue;
       if (STREQN (line, redir_word, redir_len) && line[redir_len] == '\n')
     break;
       /* Backwards compatibility here */
       if (STREQN (line, redir_word, redir_len) && (parser_state & PST_EOFTOKEN) && shell_eof_token && strchr (line+redir_len, shell_eof_token))
     {
       shell_ungets (line + redir_len);
       full_line = 0;
       break;
     }
       len = strlen (line);
       if (len + document_index >= document_size)
     {
       document_size = document_size ? 2 * (document_size + len) : len + 2;
       document = (char *)xrealloc (document, document_size);
     }
       /* len is guaranteed to be > 0 because of the check for line
      being an empty string before the call to strlen. */
       FASTCOPY (line, document + document_index, len);
       document_index += len;
     }
   if (full_line == 0)
     internal_warning (_("here-document at line %d delimited by end-of-file (wanted `%s')"), lineno, redir_word);
 document_done:
   if (document)
     document[document_index] = '\0';
   else
     {
       document = (char *)xmalloc (1);
       document[0] = '\0';
     }
   temp->redirectee.filename->word = document;
   here_doc_first_line = 0;
 }
References _, echo_input_at_read, FASTCOPY, REDIRECTEE::filename, word_desc::flags, fprintf(), free, redirect::here_doc_eof, here_doc_first_line, redirect::instruction, internal_error(), internal_warning(), len, line, line_number, lineno, NULL, parser_state, PST_EOFTOKEN, r_deblank_reading_until, r_reading_until, read_secondary_line(), redirect::redirectee, savestring(), shell_eof_token, shell_ungets(), stderr, strchr(), STREQN, string_quote_removal(), strlen, W_QUOTED, word_desc::word, xmalloc, and xrealloc.
Referenced by gather_here_documents().
make_if_command()
COMMAND* make_if_command (COMMAND * test, COMMAND * true_case, COMMAND * false_case)
Definition at line 385 of file make_cmd.c.
 {
   IF_COM *temp;
   temp = (IF_COM *)xmalloc (sizeof (IF_COM));
   temp->flags = 0;
   temp->test = test;
   temp->true_case = true_case;
   temp->false_case = false_case;
   return (make_command (cm_if, (SIMPLE_COM *)temp));
 }
References cm_if, if_com::false_case, if_com::flags, make_command(), if_com::test, test, if_com::true_case, and xmalloc.
Referenced by yyparse().
make_pattern_list()
PATTERN_LIST* make_pattern_list (WORD_LIST * patterns, COMMAND * action)
Definition at line 370 of file make_cmd.c.
 {
   PATTERN_LIST *temp;
   temp = (PATTERN_LIST *)xmalloc (sizeof (PATTERN_LIST));
   temp->patterns = REVERSE_LIST (patterns, WORD_LIST *);
   temp->action = action;
   temp->next = NULL;
   temp->flags = 0;
   return (temp);
 }
References pattern_list::action, pattern_list::flags, pattern_list::next, NULL, pattern_list::patterns, REVERSE_LIST, and xmalloc.
Referenced by yyparse().
make_redirection()
REDIRECT* make_redirection (REDIRECTEE source, enum r_instruction instruction, REDIRECTEE dest_and_filename, int flags)
Definition at line 686 of file make_cmd.c.
 {
   REDIRECT *temp;
   WORD_DESC *w;
   int wlen;
   intmax_t lfd;
   temp = (REDIRECT *)xmalloc (sizeof (REDIRECT));
   /* First do the common cases. */
   temp->redirector = source;
   temp->redirectee = dest_and_filename;
   temp->here_doc_eof = 0;
   temp->instruction = instruction;
   temp->flags = 0;
   temp->rflags = flags;
   temp->next = (REDIRECT *)NULL;
   switch (instruction)
     {
     case r_output_direction:        /* >foo */
     case r_output_force:        /* >| foo */
     case r_err_and_out:         /* &>filename */
       temp->flags = O_TRUNC | O_WRONLY | O_CREAT;
       break;
     case r_appending_to:        /* >>foo */
     case r_append_err_and_out:      /* &>> filename */
       temp->flags = O_APPEND | O_WRONLY | O_CREAT;
       break;
     case r_input_direction:     /* <foo */
     case r_inputa_direction:        /* foo & makes this. */
       temp->flags = O_RDONLY;
       break;
     case r_input_output:        /* <>foo */
       temp->flags = O_RDWR | O_CREAT;
       break;
     case r_deblank_reading_until:   /* <<-foo */
     case r_reading_until:       /* << foo */
     case r_reading_string:      /* <<< foo */
     case r_close_this:          /* <&- */
     case r_duplicating_input:       /* 1<&2 */
     case r_duplicating_output:      /* 1>&2 */
       break;
     /* the parser doesn't pass these. */
     case r_move_input:          /* 1<&2- */
     case r_move_output:         /* 1>&2- */
     case r_move_input_word:     /* 1<&$foo- */
     case r_move_output_word:        /* 1>&$foo- */
       break;
     /* The way the lexer works we have to do this here. */
     case r_duplicating_input_word:  /* 1<&$foo */
     case r_duplicating_output_word: /* 1>&$foo */
       w = dest_and_filename.filename;
       wlen = strlen (w->word) - 1;
       if (w->word[wlen] == '-')     /* Yuck */
         {
           w->word[wlen] = '\0';
       if (all_digits (w->word) && legal_number (w->word, &lfd) && lfd == (int)lfd)
         {
           dispose_word (w);
           temp->instruction = (instruction == r_duplicating_input_word) ? r_move_input : r_move_output;
           temp->redirectee.dest = lfd;
         }
       else
         temp->instruction = (instruction == r_duplicating_input_word) ? r_move_input_word : r_move_output_word;
         }
       break;
     default:
       programming_error (_("make_redirection: redirection instruction `%d' out of range"), instruction);
       abort ();
       break;
     }
   return (temp);
 }
References _, abort(), all_digits(), REDIRECTEE::dest, dispose_word(), REDIRECTEE::filename, redirect::flags, flags, redirect::here_doc_eof, redirect::instruction, legal_number(), redirect::next, NULL, O_APPEND, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, programming_error(), r_append_err_and_out, r_appending_to, r_close_this, r_deblank_reading_until, r_duplicating_input, r_duplicating_input_word, r_duplicating_output, r_duplicating_output_word, r_err_and_out, r_input_direction, r_input_output, r_inputa_direction, r_move_input, r_move_input_word, r_move_output, r_move_output_word, r_output_direction, r_output_force, r_reading_string, r_reading_until, redirect::redirectee, redirect::redirector, redirect::rflags, source, strlen, w, and xmalloc.
Referenced by add_undo_close_redirect(), add_undo_redirect(), do_redirection_internal(), and yyparse().
make_select_command()
COMMAND* make_select_command (WORD_DESC * name, WORD_LIST * map_list, COMMAND * action, int lineno)
Definition at line 229 of file make_cmd.c.
 {
 #if defined (SELECT_COMMAND)
   return (make_for_or_select (cm_select, name, map_list, action, lineno));
 #else
   set_exit_status (2);
   return ((COMMAND *)NULL);
 #endif
 }
References cm_select, lineno, make_for_or_select(), NULL, and set_exit_status().
Referenced by yyparse().
make_simple_command()
COMMAND* make_simple_command (ELEMENT element, COMMAND * command)
Definition at line 519 of file make_cmd.c.
 {
   /* If we are starting from scratch, then make the initial command
      structure.  Also note that we have to fill in all the slots, since
      malloc doesn't return zeroed space. */
   if (command == 0)
     {
       command = make_bare_simple_command ();
       parser_state |= PST_REDIRLIST;
     }
   if (element.word)
     {
       command->value.Simple->words = make_word_list (element.word, command->value.Simple->words);
       parser_state &= ~PST_REDIRLIST;
     }
   else if (element.redirect)
     {
       REDIRECT *r = element.redirect;
       /* Due to the way <> is implemented, there may be more than a single
      redirection in element.redirect.  We just follow the chain as far
      as it goes, and hook onto the end. */
       while (r->next)
     r = r->next;
       r->next = command->value.Simple->redirects;
       command->value.Simple->redirects = element.redirect;
     }
   return (command);
 }
References make_bare_simple_command(), make_word_list(), redirect::next, parser_state, PST_REDIRLIST, element::redirect, command::redirects, command::value, and element::word.
Referenced by yyparse().
make_subshell_command()
COMMAND* make_subshell_command (COMMAND * command)
Definition at line 816 of file make_cmd.c.
 {
   SUBSHELL_COM *temp;
   temp = (SUBSHELL_COM *)xmalloc (sizeof (SUBSHELL_COM));
   temp->command = command;
   temp->flags = CMD_WANT_SUBSHELL;
   temp->line = line_number;
   return (make_command (cm_subshell, (SIMPLE_COM *)temp));
 }
References cm_subshell, CMD_WANT_SUBSHELL, subshell_com::command, subshell_com::flags, subshell_com::line, line_number, make_command(), and xmalloc.
Referenced by yyparse().
make_until_command()
COMMAND* make_until_command (COMMAND * test, COMMAND * action)
Definition at line 420 of file make_cmd.c.
 {
   return (make_until_or_while (cm_until, test, action));
 }
References cm_until, make_until_or_while(), and test.
Referenced by yyparse().
make_until_or_while()
static COMMAND* make_until_or_while (enum command_type which, COMMAND * test, COMMAND * action) static
Definition at line 399 of file make_cmd.c.
 {
   WHILE_COM *temp;
   temp = (WHILE_COM *)xmalloc (sizeof (WHILE_COM));
   temp->flags = 0;
   temp->test = test;
   temp->action = action;
   return (make_command (which, (SIMPLE_COM *)temp));
 }
References while_com::action, while_com::flags, make_command(), while_com::test, test, and xmalloc.
Referenced by make_until_command(), and make_while_command().
make_while_command()
COMMAND* make_while_command (COMMAND * test, COMMAND * action)
Definition at line 413 of file make_cmd.c.
 {
   return (make_until_or_while (cm_while, test, action));
 }
References cm_while, make_until_or_while(), and test.
Referenced by yyparse().
make_word()
WORD_DESC* make_word (char * string) const
Definition at line 135 of file make_cmd.c.
 {
   WORD_DESC *temp;
   temp = make_bare_word (string);
   return (make_word_flags (temp, string));
 }
References make_bare_word(), and make_word_flags().
Referenced by bind_args(), execute_disk_command(), execute_simple_command(), make_word_from_token(), pos_params(), and print_builtin().
make_word_flags()
WORD_DESC* make_word_flags (WORD_DESC * w, const char * string)
Definition at line 102 of file make_cmd.c.
 {
   register int i;
   size_t slen;
   DECLARE_MBSTATE;
   i = 0;
   slen = strlen (string);
   while (i < slen)
     {
       switch (string[i])
     {
     case '$':
       w->flags |= W_HASDOLLAR;
       break;
     case '\\':
       break;    /* continue the loop */
     case '\'':
     case '`':
     case '"':
       w->flags |= W_QUOTED;
       break;
     }
       ADVANCE_CHAR (string, slen, i);
     }
   return (w);
 }
References ADVANCE_CHAR, DECLARE_MBSTATE, i, strlen, w, W_HASDOLLAR, and W_QUOTED.
Referenced by make_word().
make_word_from_token()
WORD_DESC* make_word_from_token (int token)
Definition at line 145 of file make_cmd.c.
 {
   char tokenizer[2];
   tokenizer[0] = token;
   tokenizer[1] = '\0';
   return (make_word (tokenizer));
 }
References make_word().
make_word_list()
WORD_LIST* make_word_list (WORD_DESC * word, WORD_LIST * wlink)
Definition at line 157 of file make_cmd.c.
 {
   WORD_LIST *temp;
   ocache_alloc (wlcache, WORD_LIST, temp);
   temp->word = word;
   temp->next = wlink;
   return (temp);
 }
References word_list::next, ocache_alloc, wlcache, and word_list::word.
Referenced by bind_args(), copy_word_list(), execute_disk_command(), execute_simple_command(), expand_prompt_string(), expand_word_internal(), glob_expand_word_list(), list_remove_pattern(), list_rest_of_args(), list_string(), list_transform(), make_simple_command(), munge_list(), parse_compound_assignment(), parse_string_to_word_list(), pos_params(), print_builtin(), redirection_expand(), strvec_to_word_list(), word_list_split(), and yyparse().
PARAMS() [1/2]
static COMMAND* make_until_or_while PARAMS ((enum command_type, COMMAND *, COMMAND *)) static
PARAMS() [2/2]
static COMMAND* make_for_or_select PARAMS ((enum command_type, WORD_DESC *, WORD_LIST *, COMMAND *, int)) static
Variable Documentation
here_doc_first_line
int here_doc_first_line = 0
Definition at line 49 of file make_cmd.c.
Referenced by gather_here_documents(), make_here_document(), reset_parser(), restore_parser_state(), and save_parser_state().
wdcache
sh_obj_cache_t wdcache = {0, 0, 0}
Definition at line 52 of file make_cmd.c.
Referenced by alloc_word_desc(), cmd_init(), dispose_word(), and dispose_word_desc().
wlcache
sh_obj_cache_t wlcache = {0, 0, 0}
Definition at line 53 of file make_cmd.c.
Referenced by cmd_init(), and make_word_list().