Fennix: Userspace/mlibc/tests/posix/alarm.c File Reference
alarm.c File Reference
#include <signal.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
Functions
static void sigalrm_handler (int signal)
int main ()
Variables
static volatile int alarms_fired = 0
Function Documentation
main()
int main (void)
Definition at line 15 of file alarm.c.
            {
     signal(SIGALRM, sigalrm_handler);
     alarms_fired = 0;
     unsigned int ret = alarm(10);
     assert(!ret);
     sleep(1);
     ret = alarm(1);
     assert(ret == 9);
     sleep(2);
     if(alarms_fired != 1) {
         fprintf(stderr, "alarm handler fired %u times instead of 1\n", alarms_fired);
         exit(1);
     }
 }
References alarm(), alarms_fired, assert, exit(), fprintf(), ret, SIGALRM, sigalrm_handler(), signal(), sleep(), and stderr.
sigalrm_handler()
static void sigalrm_handler (int signal) static
Definition at line 10 of file alarm.c.
{
     if(signal == SIGALRM)
         alarms_fired++;
 }
References alarms_fired, SIGALRM, and signal().
Referenced by main().
Variable Documentation
alarms_fired
volatile int alarms_fired = 0 static
Definition at line 8 of file alarm.c.
Referenced by main(), and sigalrm_handler().