Fennix: Userspace/mlibc/options/glibc/generic/glibc-assert.cpp File Reference
glibc-assert.cpp File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <bits/ensure.h>
Functions
void __assert_fail_perror (int errno, const char *file, unsigned int line, const char *function)
Function Documentation
__assert_fail_perror()
void __assert_fail_perror (int errno, const char * file, unsigned int line, const char * function)
Definition at line 8 of file glibc-assert.cpp.
{
     char *errormsg = strerror(errno);
     fprintf(stderr, "In function %s, file %s:%d: Errno '%s' failed!\n",
             function, file, line, errormsg);
     abort();
 }
References abort(), errno, fprintf(), stderr, and strerror().