Fennix: Kernel/library/c/stdio.cpp File Reference
stdio.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <debug.h>
Macros
#define va_copy(dest, src) __builtin_va_copy(dest, src)
Functions
EXTERNC int asprintf (char **strp, const char *fmt,...)
EXTERNC int vasprintf (char **strp, const char *fmt, va_list ap)
int fprintf (FILE *stream, const char *format,...)
int fputs (const char *s, FILE *stream)
Variables
FILE __local_stdin = {.st = 0}
FILE __local_stdout = {.st = 1}
FILE __local_stderr = {.st = 2}
FILE * stdin = &__local_stdin
FILE * stdout = &__local_stdout
FILE * stderr = &__local_stderr
Macro Definition Documentation
va_copy
#define va_copy (dest, src) __builtin_va_copy(dest, src)
Definition at line 39 of file stdio.cpp.
Function Documentation
asprintf()
EXTERNC int asprintf (char ** strp, const char * fmt, ...)
Definition at line 30 of file stdio.cpp.
 {
     va_list ap;
     va_start(ap, fmt);
     int ret = vasprintf(strp, fmt, ap);
     va_end(ap);
     return ret;
 }
References ret, va_end, va_start, and vasprintf().
fprintf()
int fprintf (FILE * stream, const char * format, ...)
Definition at line 65 of file stdio.cpp.
 {
     switch (stream->st)
     {
     case 0:
     {
         error("fprintf() called with stdin");
         return -1;
     }
     case 1:
     {
         va_list ap;
         va_start(ap, format);
         int ret = vprintf(format, ap);
         va_end(ap);
         return ret;
     }
     case 2:
     {
         va_list ap;
         va_start(ap, format);
         int ret = vprintf(format, ap);
         va_end(ap);
         return ret;
     }
     default:
         return -1;
     }
 }
References error, ret, FILE::st, va_end, va_start, and vprintf().
fputs()
int fputs (const char * s, FILE * stream)
Definition at line 95 of file stdio.cpp.
 {
     for (const char *c = s; *c; c++)
         uart_wrapper(*c, NULL);
     return 0;
 }
vasprintf()
EXTERNC int vasprintf (char ** strp, const char * fmt, va_list ap)
Definition at line 41 of file stdio.cpp.
 {
     va_list ap2;
     va_copy(ap2, ap);
     int len = vsnprintf(NULL, 0, fmt, ap2);
     va_end(ap2);
     if (len < 0)
     {
         return -1;
     }
     *strp = (char *)malloc(len + 1);
     if (!*strp)
     {
         return -1;
     }
     int ret = vsnprintf(*strp, len + 1, fmt, ap);
     if (ret < 0)
     {
         free(*strp);
         *strp = NULL;
     }
     return ret;
 }
References free, len, malloc, NULL, ret, va_copy, va_end, and vsnprintf().
Referenced by asprintf().
Variable Documentation
__local_stderr
FILE __local_stderr = {.st = 2}
Definition at line 24 of file stdio.cpp.
__local_stdin
FILE __local_stdin = {.st = 0}
Definition at line 22 of file stdio.cpp.
__local_stdout
FILE __local_stdout = {.st = 1}
Definition at line 23 of file stdio.cpp.
stderr
FILE* stderr = &__local_stderr
Definition at line 28 of file stdio.cpp.
stdin
FILE* stdin = &__local_stdin
Definition at line 26 of file stdio.cpp.
stdout
FILE* stdout = &__local_stdout
Definition at line 27 of file stdio.cpp.