Fennix Userspace: Userspace/musl/src/ctype/iswspace.c File Reference
iswspace.c File Reference
#include <wchar.h>
#include <wctype.h>
Functions
int iswspace (wint_t wc)
int __iswspace_l (wint_t c, locale_t l)
weak_alias (__iswspace_l, iswspace_l)
Function Documentation
__iswspace_l()
int __iswspace_l (wint_t c, locale_t l)
Definition at line 19 of file iswspace.c.
 {
     return iswspace(c);
 }
References c, and iswspace().
iswspace()
int iswspace (wint_t wc)
Definition at line 8 of file iswspace.c.
 {
     static const wchar_t spaces[] = {
         ' ', '\t', '\n', '\r', 11, 12,  0x0085,
         0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005,
         0x2006, 0x2008, 0x2009, 0x200a,
         0x2028, 0x2029, 0x205f, 0x3000, 0
     };
     return wc && wcschr(spaces, wc);
 }
References wcschr().
Referenced by __iswspace_l().
weak_alias()
weak_alias (__iswspace_l , iswspace_l)