Fennix: Userspace/musl/src/signal/kill.c File Reference
kill.c File Reference
#include <signal.h>
#include "syscall.h"
Functions
int kill (pid_t pid, int sig)
Function Documentation
kill()
int kill (pid_t pid, int sig)
Definition at line 4 of file kill.c.
 {
     return syscall(SYS_kill, pid, sig);
 }
References pid, and syscall().
Referenced by _rl_handle_signal(), act(), bootchartd_main(), check_and_run_traps(), command_substitute(), con_escape(), ctrl(), do_rescan(), do_stop(), do_wordexp(), halt_main(), hush_main(), ifplugd_main(), init_main(), initialize_job_control(), kill_all_if_got_signal(), kill_main(), kill_pid(), kill_shell(), killpg(), last_main(), run_pending_traps(), run_shutdown_and_kill_processes(), runsvdir_main(), scan_recursive(), sigcont_sighandler(), signal_mdevs(), sigstop_sighandler(), stopservice(), timeout_main(), timeout_wait(), trap_handler(), wait_for(), wait_one(), wait_sigint_handler(), waitfor(), and winch_handler().