Fennix Kernel: Driver::Manager Class Reference
Driver::Manager Class Reference
#include <driver.hpp>
Data Structures
struct DeviceInode
Public Member Functions
std::unordered_map< dev_t, DriverObject > & GetDrivers ()
void Daemon ()
void PreloadDrivers ()
void LoadAllDrivers ()
void UnloadAllDrivers ()
void Panic ()
dev_t CreateIncrementalDevice (dev_t DriverID, const std::string &Prefix, mode_t Mode, InodeOperations *Ops)
dev_t RegisterDevice (dev_t DriverID, DeviceType Type, const InodeOperations *Operations)
int ReportInputEvent (dev_t DriverID, InputReport *Report)
int UnregisterDevice (dev_t DriverID, dev_t Device)
Manager ()
~Manager ()
Data Fields
RingBuffer< KeyboardReport > GlobalKeyboardInputReports
RingBuffer< MouseReport > GlobalMouseInputReports
Private Member Functions
NewLock (ModuleInitLock)
int LoadDriverFile (DriverObject &Drv, FileNode *File)
void InitializeDaemonFS ()
dev_t RegisterInputDevice (std::unordered_map< dev_t, DriverHandlers > *, dev_t, size_t, const InodeOperations *)
dev_t RegisterBlockDevice (std::unordered_map< dev_t, DriverHandlers > *, dev_t, size_t, const InodeOperations *)
Private Attributes
std::unordered_map< dev_t, DriverObject > Drivers
dev_t DriverIDCounter = 2
FileNode * devNode = nullptr
FileNode * devInputNode = nullptr
Detailed Description
Definition at line 82 of file driver.hpp.
Data Structure Documentation
Driver::Manager::DeviceInode
struct Driver::Manager::DeviceInode
Definition at line 108 of file driver.hpp.
Data Fields
vector< DeviceInode * > Children
string Name
struct Inode Node
FileNode * Parent
Inode * ParentInode
Constructor & Destructor Documentation
Manager()
Driver::Manager::Manager ()
Definition at line 517 of file driver.cpp.
 { this->InitializeDaemonFS(); }
~Manager()
Driver::Manager::~Manager ()
Definition at line 519 of file driver.cpp.
     {
         debug("Unloading drivers");
         UnloadAllDrivers();
     }
References debug.
Member Function Documentation
CreateIncrementalDevice()
dev_t Driver::Manager::CreateIncrementalDevice (dev_t DriverID, const std::string & Prefix, mode_t Mode, InodeOperations * Ops)
Prefixes:
dsk (any disk device)
dsk0p0 (disk 0, partition 0)
blk (block device)
eth (Ethernet device)
wlan (Wireless LAN device)
lo (Loopback device)
kb (Keyboard device)
ms (Mouse device)
js (Joystick device)
tp (Touchpad device)
tc (Touchscreen device)
cam (Camera device)
spk (Speaker device)
mic (Microphone device)
snd (Sound device)
tty (Serial device)
lp (Parallel device)
gpu (Graphics device)
fb (Framebuffer device)
usb (USB device)
usb0dsk0p0 (USB 0, disk 0, partition 0; for USB storage)
Daemon()
void Driver::Manager::Daemon ()
Definition at line 595 of file daemon.cpp.
     {
         while (true)
         {
             TaskManager->Sleep(1000);
         }
     }
References Tasking::Task::Sleep(), and TaskManager.
Referenced by Driver::ManagerDaemonWrapper().
GetDrivers()
std::unordered_map<dev_t, DriverObject>& Driver::Manager::GetDrivers () inline
Definition at line 118 of file driver.hpp.
 { return Drivers; }
References Drivers.
Referenced by Driver::__fs_Close(), Driver::__fs_Ioctl(), Driver::__fs_Open(), Driver::__fs_Read(), Driver::__fs_Write(), v0::AllocateMemory(), cmd_lsmod(), cmd_modinfo(), v0::FreeMemory(), v0::GetPCIDevices(), v0::OverrideInterruptHandler(), RegisterDevice(), v0::RegisterInterruptHandler(), ReportInputEvent(), v0::UnregisterAllInterruptHandlers(), UnregisterDevice(), and v0::UnregisterInterruptHandler().
InitializeDaemonFS()
void Driver::Manager::InitializeDaemonFS () private
Definition at line 754 of file daemon.cpp.
     {
         ptmx = new TTY::PTMXDevice;
         dev_t MinorID = 0;
         DeviceInode *_dev = new DeviceInode;
         _dev->Name = "dev";
         /* d rwx r-- r-- */
         mode_t mode = S_IRWXU |
                       S_IRGRP |
                       S_IROTH |
                       S_IFDIR;
         Inode *dev = (Inode *)_dev;
         dev->Mode = mode;
         dev->Flags = I_FLAG_MOUNTPOINT | I_FLAG_CACHE_KEEP;
         FileSystemInfo *fsi = new FileSystemInfo;
         fsi->Name = "Device Virtual File System";
         fsi->RootName = "dev";
         fsi->Flags = I_FLAG_ROOT | I_FLAG_MOUNTPOINT | I_FLAG_CACHE_KEEP;
         fsi->SuperOps = {};
         fsi->Ops.Lookup = __fs_Lookup;
         fsi->Ops.Create = __fs_Create;
         fsi->Ops.Read = __fs_Read;
         fsi->Ops.Write = __fs_Write;
         fsi->Ops.Open = __fs_Open;
         fsi->Ops.Close = __fs_Close;
         fsi->Ops.Ioctl = __fs_Ioctl;
         fsi->Ops.ReadDir = __fs_Readdir;
         dev->Device = fs->RegisterFileSystem(fsi, dev);
         dev->SetDevice(0, MinorID++);
         MinorID++; /* 1 = /proc/self */
         devNode = fs->Mount(fs->GetRoot(0), dev, "/dev");
         _dev->Parent = devNode->Parent;
         _dev->ParentInode = devNode->Parent->Node;
         /* d rwx r-- r-- */
         mode = S_IRWXU |
                S_IRGRP |
                S_IROTH |
                S_IFDIR;
         DeviceInode *input = new DeviceInode;
         input->Parent = devNode;
         input->ParentInode = devNode->Node;
         input->Name = "input";
         input->Node.Device = dev->Device;
         input->Node.Mode = mode;
         input->Node.Flags = I_FLAG_CACHE_KEEP;
         input->Node.Offset = _dev->Children.size();
         _dev->Children.push_back(input);
         devInputNode = fs->GetByPath("input", devNode);
         auto createDevice = [](DeviceInode *p1, FileNode *p2, const std::string &name, dev_t maj, dev_t min, mode_t mode)
         {
             DeviceInode *device = new DeviceInode;
             device->Parent = p2;
             device->ParentInode = p2->Node;
             device->Name = name;
             device->Node.Device = p2->Node->Device;
             device->Node.Mode = mode;
             device->Node.SetDevice(maj, min);
             device->Node.Flags = I_FLAG_CACHE_KEEP;
             device->Node.Offset = p1->Children.size();
             p1->Children.push_back(device);
         };
         /* c rw- rw- rw- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP | S_IWGRP |
                S_IROTH | S_IWOTH |
                S_IFCHR;
         createDevice(_dev, devNode, "null", 0, MinorID++, mode);
         /* c rw- rw- rw- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP | S_IWGRP |
                S_IROTH | S_IWOTH |
                S_IFCHR;
         createDevice(_dev, devNode, "zero", 0, MinorID++, mode);
         /* c rw- rw- rw- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP | S_IWGRP |
                S_IROTH | S_IWOTH |
                S_IFCHR;
         createDevice(_dev, devNode, "random", 0, MinorID++, mode);
         /* c rw- r-- --- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP |
                S_IFCHR;
         createDevice(_dev, devNode, "mem", 0, MinorID++, mode);
         /* c rw- r-- --- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP |
                S_IFCHR;
         createDevice(_dev, devNode, "kcon", 0, MinorID++, mode);
         /* c rw- rw- rw- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP | S_IWGRP |
                S_IRUSR | S_IWUSR |
                S_IFCHR;
         createDevice(_dev, devNode, "tty", 0, MinorID++, mode);
         /* c rw- rw- rw- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP | S_IWGRP |
                S_IRUSR | S_IWUSR |
                S_IFCHR;
         createDevice(_dev, devNode, "ptmx", 0, MinorID++, mode);
         /* ------------------------------------------------------ */
         MinorID = 0;
         /* c rw- r-- --- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP |
                S_IFCHR;
         createDevice(input, devInputNode, "keyboard", 1, MinorID++, mode);
         /* c rw- r-- --- */
         mode = S_IRUSR | S_IWUSR |
                S_IRGRP |
                S_IFCHR;
         createDevice(input, devInputNode, "mouse", 1, MinorID++, mode);
     }
References Driver::__fs_Close(), Driver::__fs_Create(), Driver::__fs_Ioctl(), Driver::__fs_Lookup(), Driver::__fs_Open(), Driver::__fs_Read(), Driver::__fs_Write(), Driver::Manager::DeviceInode::Children, InodeOperations::Close, InodeOperations::Create, Inode::Device, Inode::Flags, FileSystemInfo::Flags, fs, vfs::Virtual::GetByPath(), vfs::Virtual::GetRoot(), I_FLAG_CACHE_KEEP, I_FLAG_MOUNTPOINT, I_FLAG_ROOT, InodeOperations::Ioctl, InodeOperations::Lookup, Inode::Mode, vfs::Virtual::Mount(), Driver::Manager::DeviceInode::Name, FileSystemInfo::Name, Driver::Manager::DeviceInode::Node, Inode::Offset, InodeOperations::Open, FileSystemInfo::Ops, Driver::Manager::DeviceInode::Parent, FileNode::Parent, Driver::Manager::DeviceInode::ParentInode, Driver::ptmx, InodeOperations::Read, InodeOperations::ReadDir, vfs::Virtual::RegisterFileSystem(), FileSystemInfo::RootName, S_IFCHR, S_IFDIR, S_IRGRP, S_IROTH, S_IRUSR, S_IRWXU, S_IWGRP, S_IWOTH, S_IWUSR, FileSystemInfo::SuperOps, and InodeOperations::Write.
LoadAllDrivers()
void Driver::Manager::LoadAllDrivers ()
Definition at line 88 of file driver.cpp.
     {
         if (Drivers.empty())
         {
             KPrint("\x1b[1;31;41mNo drivers to load");
             return;
         }
         foreach (auto &var in Drivers)
         {
             DriverObject &Drv = var.second;
             debug("Calling driver %s at %#lx", Drv.Path.c_str(), Drv.EntryPoint);
             int (*DrvInit)(dev_t) = (int (*)(dev_t))Drv.EntryPoint;
             Drv.ErrorCode = DrvInit(Drv.ID);
             if (Drv.ErrorCode < 0)
             {
                 KPrint("FATAL: _start() failed for %s: %s",
                        Drv.Name, strerror(Drv.ErrorCode));
                 error("Failed to load driver %s: %s",
                       Drv.Path.c_str(), strerror(Drv.ErrorCode));
                 Drv.vma->FreeAllPages();
                 continue;
             }
             KPrint("Loading driver %s", Drv.Name);
             debug("Calling Probe()=%#lx on driver %s",
                   Drv.Probe, Drv.Path.c_str());
             Drv.ErrorCode = Drv.Probe();
             if (Drv.ErrorCode < 0)
             {
                 KPrint("Probe() failed for %s: %s",
                        Drv.Name, strerror(Drv.ErrorCode));
                 error("Failed to probe driver %s: %s",
                       Drv.Path.c_str(), strerror(Drv.ErrorCode));
                 Drv.vma->FreeAllPages();
                 continue;
             }
             debug("Calling driver Entry()=%#lx function on driver %s",
                   Drv.Entry, Drv.Path.c_str());
             Drv.ErrorCode = Drv.Entry();
             if (Drv.ErrorCode < 0)
             {
                 KPrint("Entry() failed for %s: %s",
                        Drv.Name, strerror(Drv.ErrorCode));
                 error("Failed to initialize driver %s: %s",
                       Drv.Path.c_str(), strerror(Drv.ErrorCode));
                 Drv.vma->FreeAllPages();
                 continue;
             }
             debug("Loaded driver %s", Drv.Path.c_str());
             Drv.Initialized = true;
         }
     }
References debug, Driver::DriverObject::Entry, Driver::DriverObject::EntryPoint, error, Driver::DriverObject::ErrorCode, Memory::VirtualMemoryArea::FreeAllPages(), Driver::DriverObject::ID, Driver::DriverObject::Initialized, KPrint(), Driver::DriverObject::Name, Driver::DriverObject::Path, Driver::DriverObject::Probe, strerror(), and Driver::DriverObject::vma.
Referenced by KernelMainThread().
LoadDriverFile()
int Driver::Manager::LoadDriverFile (DriverObject & Drv, FileNode * File) private
Definition at line 200 of file driver.cpp.
     {
         trace("Loading driver %s in memory", File->Name.c_str());
         Elf_Ehdr ELFHeader{};
         File->Read(&ELFHeader, sizeof(Elf_Ehdr), 0);
         AssertReturnError(ELFHeader.e_ident[EI_CLASS] == ELFCLASS64, -ENOEXEC);
         AssertReturnError(ELFHeader.e_ident[EI_DATA] == ELFDATA2LSB, -ENOEXEC);
         AssertReturnError(ELFHeader.e_ident[EI_OSABI] == ELFOSABI_SYSV, -ENOEXEC);
         AssertReturnError(ELFHeader.e_ident[EI_ABIVERSION] == 0, -ENOEXEC);
         AssertReturnError(ELFHeader.e_type == ET_DYN, -ENOEXEC);
         AssertReturnError(ELFHeader.e_machine == EM_X86_64, -ENOEXEC);
         AssertReturnError(ELFHeader.e_version == EV_CURRENT, -ENOEXEC);
         AssertReturnError(ELFHeader.e_entry != 0x0, -ENOEXEC);
         AssertReturnError(ELFHeader.e_shstrndx != SHN_UNDEF, -ENOEXEC);
         Drv.EntryPoint = ELFHeader.e_entry;
         size_t segSize = 0;
         Elf_Phdr phdr{};
         for (Elf_Half i = 0; i < ELFHeader.e_phnum; i++)
         {
             File->Read(&phdr, sizeof(Elf_Phdr), ELFHeader.e_phoff + (i * sizeof(Elf_Phdr)));
             if (phdr.p_type == PT_LOAD || phdr.p_type == PT_DYNAMIC)
             {
                 if (segSize < phdr.p_vaddr + phdr.p_memsz)
                     segSize = phdr.p_vaddr + phdr.p_memsz;
                 continue;
             }
             if (phdr.p_type == PT_INTERP)
             {
                 char interp[17];
                 File->Read(interp, sizeof(interp), phdr.p_offset);
                 if (strncmp(interp, "/boot/fennix.elf", sizeof(interp)) != 0)
                 {
                     error("Interpreter is not /boot/fennix.elf");
                     return -ENOEXEC;
                 }
             }
         }
         debug("segSize: %ld", segSize);
         Drv.BaseAddress = (uintptr_t)Drv.vma->RequestPages(TO_PAGES(segSize) + 1);
         Drv.EntryPoint += Drv.BaseAddress;
         debug("Driver %s has entry point %#lx and base %#lx",
               File->Name.c_str(), Drv.EntryPoint, Drv.BaseAddress);
         Elf64_Shdr sht_strtab{};
         Elf64_Shdr sht_symtab{};
         Elf_Shdr shstrtab{};
         Elf_Shdr shdr{};
         __DriverInfo driverInfo{};
         File->Read(&shstrtab, sizeof(Elf_Shdr), ELFHeader.e_shoff + (ELFHeader.e_shstrndx * ELFHeader.e_shentsize));
         for (Elf_Half i = 0; i < ELFHeader.e_shnum; i++)
         {
             if (i == ELFHeader.e_shstrndx)
                 continue;
             File->Read(&shdr, ELFHeader.e_shentsize, ELFHeader.e_shoff + (i * ELFHeader.e_shentsize));
             switch (shdr.sh_type)
             {
             case SHT_PROGBITS:
                 break;
             case SHT_SYMTAB:
                 sht_symtab = shdr;
                 continue;
             case SHT_STRTAB:
                 sht_strtab = shdr;
                 continue;
             case SHT_NULL:
             default:
                 continue;
             }
             char symName[16];
             File->Read(symName, sizeof(symName), shstrtab.sh_offset + shdr.sh_name);
             if (strcmp(symName, ".driver.info") != 0)
                 continue;
             File->Read(&driverInfo, sizeof(__DriverInfo), shdr.sh_offset);
             /* Perform relocations */
             driverInfo.Name = (const char *)(Drv.BaseAddress + (uintptr_t)driverInfo.Name);
             driverInfo.Description = (const char *)(Drv.BaseAddress + (uintptr_t)driverInfo.Description);
             driverInfo.Author = (const char *)(Drv.BaseAddress + (uintptr_t)driverInfo.Author);
             driverInfo.License = (const char *)(Drv.BaseAddress + (uintptr_t)driverInfo.License);
         }
         for (size_t h = 0; h < (sht_symtab.sh_size / sizeof(Elf64_Sym)); h++)
         {
             Elf64_Sym symEntry{};
             uintptr_t symOffset = sht_symtab.sh_offset + (h * sizeof(Elf64_Sym));
             File->Read(&symEntry, sizeof(Elf64_Sym), symOffset);
             if (symEntry.st_name == 0)
                 continue;
             char symName[16];
             File->Read(symName, sizeof(symName), sht_strtab.sh_offset + symEntry.st_name);
             switch (symEntry.st_shndx)
             {
             case SHN_UNDEF:
             case SHN_ABS:
             case SHN_LOPROC /* , SHN_LORESERVE and SHN_BEFORE */:
             case SHN_AFTER:
             case SHN_HIPROC:
             case SHN_COMMON:
             case SHN_HIRESERVE:
                 break;
             default:
             {
                 debug("shndx: %d", symEntry.st_shndx);
                 if (strcmp(symName, "DriverEntry") == 0)
                     Drv.Entry = (int (*)())(Drv.BaseAddress + symEntry.st_value);
                 else if (strcmp(symName, "DriverFinal") == 0)
                     Drv.Final = (int (*)())(Drv.BaseAddress + symEntry.st_value);
                 else if (strcmp(symName, "DriverPanic") == 0)
                     Drv.Panic = (int (*)())(Drv.BaseAddress + symEntry.st_value);
                 else if (strcmp(symName, "DriverProbe") == 0)
                     Drv.Probe = (int (*)())(Drv.BaseAddress + symEntry.st_value);
                 debug("Found %s at %#lx", symName, symEntry.st_value);
                 break;
             }
             }
         }
         for (Elf_Half i = 0; i < ELFHeader.e_phnum; i++)
         {
             File->Read(&phdr, sizeof(Elf_Phdr), ELFHeader.e_phoff + (i * sizeof(Elf_Phdr)));
             switch (phdr.p_type)
             {
             case PT_LOAD:
             case PT_DYNAMIC:
             {
                 if (phdr.p_memsz == 0)
                     continue;
                 uintptr_t dest = Drv.BaseAddress + phdr.p_vaddr;
                 debug("Copying PHDR %#lx to %#lx-%#lx (%ld file bytes, %ld mem bytes)",
                       phdr.p_type, dest, dest + phdr.p_memsz,
                       phdr.p_filesz, phdr.p_memsz);
                 if (phdr.p_filesz > 0)
                     File->Read(dest, phdr.p_filesz, phdr.p_offset);
                 if (phdr.p_memsz - phdr.p_filesz > 0)
                 {
                     void *zero = (void *)(dest + phdr.p_filesz);
                     memset(zero, 0, phdr.p_memsz - phdr.p_filesz);
                 }
                 if (phdr.p_type != PT_DYNAMIC)
                     break;
                 Elf64_Dyn *dyn = (Elf64_Dyn *)(Drv.BaseAddress + phdr.p_vaddr);
                 Elf64_Dyn *relaSize = nullptr;
                 Elf64_Dyn *pltrelSize = nullptr;
                 while (dyn->d_tag != DT_NULL)
                 {
                     switch (dyn->d_tag)
                     {
                     case DT_PLTRELSZ:
                     {
                         pltrelSize = dyn;
                         break;
                     }
                     case DT_PLTGOT:
                     {
                         Elf_Addr *got = (Elf_Addr *)(Drv.BaseAddress + dyn->d_un.d_ptr);
                         got[1] = 0;
                         got[2] = 0;
                         break;
                     }
                     case DT_RELASZ:
                     {
                         relaSize = dyn;
                         break;
                     }
                     case DT_PLTREL:
                     {
                         AssertReturnError(dyn->d_un.d_val == DT_RELA, -ENOEXEC);
                         break;
                     }
                     default:
                         break;
                     }
                     dyn++;
                 }
                 dyn = (Elf64_Dyn *)(Drv.BaseAddress + phdr.p_vaddr);
                 while (dyn->d_tag != DT_NULL)
                 {
                     switch (dyn->d_tag)
                     {
                     case DT_RELA: /* .rela.dyn */
                     {
                         AssertReturnError(relaSize != nullptr, -ENOEXEC);
                         Elf64_Rela *rela = (Elf64_Rela *)(Drv.BaseAddress + dyn->d_un.d_ptr);
                         for (size_t i = 0; i < (relaSize->d_un.d_val / sizeof(Elf64_Rela)); i++)
{
                             Elf64_Rela *r = &rela[i];
                             uintptr_t *reloc = (uintptr_t *)(Drv.BaseAddress + r->r_offset);
                             uintptr_t relocTarget = 0;
                             switch (ELF64_R_TYPE(r->r_info))
{
                             case R_X86_64_GLOB_DAT:
                             case R_X86_64_JUMP_SLOT:
{
                                 relocTarget = Drv.BaseAddress;
                                 break;
                             }
                             case R_X86_64_RELATIVE:
                             case R_X86_64_64:
{
                                 relocTarget = Drv.BaseAddress + r->r_addend;
                                 break;
                             }
                             default:
{
                                 fixme("Unhandled relocation type: %#lx",
                                       ELF64_R_TYPE(r->r_info));
                                 break;
                             }
                             }
                             *reloc = relocTarget;
                             debug("Relocated %#lx to %#lx",
                                   r->r_offset, *reloc);
                         }
                         break;
                     }
                     case DT_JMPREL: /* .rela.plt */
                     {
                         AssertReturnError(pltrelSize != nullptr, -ENOEXEC);
                         std::vector<Elf64_Dyn> symtab = Execute::ELFGetDynamicTag_x86_64(File, DT_SYMTAB);
                         Elf64_Sym *symbols = (Elf64_Sym *)((uintptr_t)Drv.BaseAddress + symtab[0].d_un.d_ptr);
                         std::vector<Elf64_Dyn> StrTab = Execute::ELFGetDynamicTag_x86_64(File, DT_STRTAB);
                         char *DynStr = (char *)((uintptr_t)Drv.BaseAddress + StrTab[0].d_un.d_ptr);
                         Elf64_Rela *rela = (Elf64_Rela *)(Drv.BaseAddress + dyn->d_un.d_ptr);
                         for (size_t i = 0; i < (pltrelSize->d_un.d_val / sizeof(Elf64_Rela)); i++)
{
                             Elf64_Rela *r = &rela[i];
                             uintptr_t *reloc = (uintptr_t *)(Drv.BaseAddress + r->r_offset);
                             switch (ELF64_R_TYPE(r->r_info))
{
                             case R_X86_64_JUMP_SLOT:
{
                                 Elf64_Xword symIndex = ELF64_R_SYM(r->r_info);
                                 Elf64_Sym *sym = symbols + symIndex;
                                 const char *symName = DynStr + sym->st_name;
                                 debug("Resolving symbol %s", symName);
                                 *reloc = (uintptr_t)GetSymbolByName(symName, driverInfo.Version.APIVersion);
                                 break;
                             }
                             default:
{
                                 fixme("Unhandled relocation type: %#lx",
                                       ELF64_R_TYPE(r->r_info));
                                 break;
                             }
                             }
                         }
                         break;
                     }
                     case DT_PLTGOT:
                     case DT_PLTRELSZ:
                     case DT_RELASZ:
                     case DT_PLTREL:
                         break;
                     default:
                     {
                         fixme("Unhandled dynamic tag: %#lx", dyn->d_tag);
                         break;
                     }
                     }
                     dyn++;
                 }
                 break;
             }
             case PT_PHDR:
             case PT_INTERP:
                 break;
             default:
             {
                 fixme("Unhandled program header type: %#lx", phdr.p_type);
                 break;
             }
             }
         }
         AssertReturnError(driverInfo.Name != nullptr, -EFAULT);
         strncpy(Drv.Name, driverInfo.Name, sizeof(Drv.Name));
         strncpy(Drv.Description, driverInfo.Description, sizeof(Drv.Description));
         strncpy(Drv.Author, driverInfo.Author, sizeof(Drv.Author));
         Drv.Version.Major = driverInfo.Version.Major;
         Drv.Version.Minor = driverInfo.Version.Minor;
         Drv.Version.Patch = driverInfo.Version.Patch;
         strncpy(Drv.License, driverInfo.License, sizeof(Drv.License));
         return 0;
     }
References AssertReturnError, Driver::DriverObject::Author, Driver::DriverObject::BaseAddress, Elf64_Dyn::d_tag, Elf64_Dyn::d_un, debug, Driver::DriverObject::Description, DT_JMPREL, DT_NULL, DT_PLTGOT, DT_PLTREL, DT_PLTRELSZ, DT_RELA, DT_RELASZ, DT_STRTAB, DT_SYMTAB, EFAULT, EI_ABIVERSION, EI_CLASS, EI_DATA, EI_OSABI, ELF64_R_SYM, ELF64_R_TYPE, ELFCLASS64, ELFDATA2LSB, Execute::ELFGetDynamicTag_x86_64(), ELFOSABI_SYSV, EM_X86_64, ENOEXEC, Driver::DriverObject::Entry, Driver::DriverObject::EntryPoint, error, ET_DYN, EV_CURRENT, Driver::DriverObject::Final, vfs::fixme(), GetSymbolByName(), Driver::DriverObject::License, memset(), Driver::DriverObject::Name, FileNode::Name, Driver::DriverObject::Panic, Driver::DriverObject::Probe, PT_DYNAMIC, PT_INTERP, PT_LOAD, PT_PHDR, Elf64_Rela::r_addend, Elf64_Rela::r_info, Elf64_Rela::r_offset, R_X86_64_64, R_X86_64_GLOB_DAT, R_X86_64_JUMP_SLOT, R_X86_64_RELATIVE, FileNode::Read(), Memory::VirtualMemoryArea::RequestPages(), SHN_ABS, SHN_AFTER, SHN_COMMON, SHN_HIPROC, SHN_HIRESERVE, SHN_LOPROC, SHN_UNDEF, SHT_NULL, SHT_PROGBITS, SHT_STRTAB, SHT_SYMTAB, elf64_sym::st_name, strcmp(), strncmp(), strncpy(), TO_PAGES, trace, Driver::DriverObject::Version, and Driver::DriverObject::vma.
NewLock()
Driver::Manager::NewLock (ModuleInitLock) private
Panic()
void Driver::Manager::Panic ()
Definition at line 177 of file driver.cpp.
     {
         Memory::Virtual vmm;
         if (Drivers.size() == 0)
             return;
         foreach (auto Driver in Drivers)
         {
             if (!Driver.second.Initialized)
                 continue;
             trace("Panic on driver %s", Driver.second.Name);
             debug("%#lx", Driver.second.Panic);
             /* Crash while probing? */
             if (Driver.second.Panic && vmm.Check((void *)Driver.second.Panic))
                 Driver.second.Panic();
             else
                 error("No panic function for driver %s",
                       Driver.second.Name);
         }
     }
References debug, error, and trace.
Referenced by BaseBufferStackError(), and HandleException().
PreloadDrivers()
void Driver::Manager::PreloadDrivers ()
Definition at line 37 of file driver.cpp.
     {
         debug("Initializing driver manager");
         const char *DriverDirectory = Config.DriverDirectory;
         FileNode *drvDirNode = fs->GetByPath(DriverDirectory, nullptr);
         if (!drvDirNode)
         {
             error("Failed to open driver directory %s", DriverDirectory);
             KPrint("Failed to open driver directory %s", DriverDirectory);
             return;
         }
         foreach (const auto &drvNode in drvDirNode->Children)
         {
             debug("Checking driver %s", drvNode->Path.c_str());
             if (!drvNode->IsRegularFile())
                 continue;
             if (Execute::GetBinaryType(drvNode->Path) != Execute::BinTypeELF)
             {
                 error("Driver %s is not an ELF binary", drvNode->Path.c_str());
                 continue;
             }
             DriverObject drvObj = {.BaseAddress = 0,
                                    .EntryPoint = 0,
                                    .vma = new Memory::VirtualMemoryArea(thisProcess->PageTable),
                                    .Path = drvNode->Path,
                                    .InterruptHandlers = new std::unordered_map<uint8_t, void *>(),
                                    .DeviceOperations = new std::unordered_map<dev_t, DriverHandlers>(),
                                    .ID = DriverIDCounter};
             int err = this->LoadDriverFile(drvObj, drvNode);
             debug("err = %d (%s)", err, strerror(err));
             if (err != 0)
             {
                 error("Failed to load driver %s: %s",
                       drvNode->Path.c_str(), strerror(err));
                 delete drvObj.vma;
                 delete drvObj.InterruptHandlers;
                 delete drvObj.DeviceOperations;
                 continue;
             }
             debug("gdb: \"0x%lX\" %s", drvObj.BaseAddress, drvObj.Name);
             Drivers.insert({DriverIDCounter++, drvObj});
         }
     }
References Driver::DriverObject::BaseAddress, Execute::BinTypeELF, Config, debug, Driver::DriverObject::DeviceOperations, KernelConfig::DriverDirectory, error, fs, Execute::GetBinaryType(), vfs::Virtual::GetByPath(), Driver::DriverObject::InterruptHandlers, KPrint(), Driver::DriverObject::Name, strerror(), thisProcess, and Driver::DriverObject::vma.
Referenced by KernelMainThread().
RegisterBlockDevice()
dev_t Driver::Manager::RegisterBlockDevice (std::unordered_map< dev_t, DriverHandlers > * dop, dev_t DriverID, size_t i, const InodeOperations * Operations) private
Definition at line 635 of file daemon.cpp.
     {
         std::string prefix = "event";
         for (size_t j = 0; j < 128; j++)
         {
             std::string deviceName = prefix + std::to_string(j);
             FileNode *node = fs->GetByPath(deviceName.c_str(), devInputNode);
             if (node)
                 continue;
             /* c rwx r-- r-- */
             mode_t mode = S_IRWXU |
                           S_IRGRP |
                           S_IROTH |
                           S_IFBLK;
             node = fs->ForceCreate(devInputNode, deviceName.c_str(), mode);
             node->Node->SetDevice(DriverID, i);
             DriverHandlers dh{};
             dh.Ops = Operations;
             dh.Node = node->Node;
             dh.InputReports = new RingBuffer<InputReport>(16);
             dop->insert({i, std::move(dh)});
             return i;
         }
         ReturnLogError(-1, "No available slots for device %d", DriverID);
         return -1; /* -Werror=return-type */
     }
References vfs::Virtual::ForceCreate(), fs, vfs::Virtual::GetByPath(), FileNode::Node, Driver::DriverHandlers::Ops, ReturnLogError, S_IFBLK, S_IRGRP, S_IROTH, and S_IRWXU.
RegisterDevice()
dev_t Driver::Manager::RegisterDevice (dev_t DriverID, DeviceType Type, const InodeOperations * Operations)
Definition at line 667 of file daemon.cpp.
     {
         std::unordered_map<dev_t, Driver::DriverObject> &drivers =
             DriverManager->GetDrivers();
         const auto it = drivers.find(DriverID);
         if (it == drivers.end())
             ReturnLogError(-EINVAL, "Driver %d not found", DriverID);
         const Driver::DriverObject *drv = &it->second;
         auto dop = drv->DeviceOperations;
         for (size_t i = 0; i < 128; i++)
         {
             const auto dOps = dop->find(i);
             const auto dOpsEnd = dop->end();
             if (dOps != dOpsEnd)
                 continue;
             DeviceType devType = (DeviceType)(Type & DEVICE_TYPE_MASK);
             switch (devType)
             {
             case DEVICE_TYPE_INPUT:
                 return RegisterInputDevice(dop, DriverID, i, Operations);
             case DEVICE_TYPE_BLOCK:
                 return RegisterBlockDevice(dop, DriverID, i, Operations);
             default:
                 ReturnLogError(-1, "Invalid device type %d", Type);
             }
         }
         ReturnLogError(-1, "No available slots for device %d", DriverID);
     }
References DEVICE_TYPE_BLOCK, DEVICE_TYPE_INPUT, DEVICE_TYPE_MASK, Driver::DriverObject::DeviceOperations, DriverManager, EINVAL, GetDrivers(), it, and ReturnLogError.
Referenced by v0::RegisterDevice().
RegisterInputDevice()
dev_t Driver::Manager::RegisterInputDevice (std::unordered_map< dev_t, DriverHandlers > * dop, dev_t DriverID, size_t i, const InodeOperations * Operations) private
Definition at line 603 of file daemon.cpp.
     {
         std::string prefix = "event";
         for (size_t j = 0; j < 128; j++)
         {
             std::string deviceName = prefix + std::to_string(j);
             FileNode *node = fs->GetByPath(deviceName.c_str(), devInputNode);
             if (node)
                 continue;
             /* c rwx r-- r-- */
             mode_t mode = S_IRWXU |
                           S_IRGRP |
                           S_IROTH |
                           S_IFCHR;
             node = fs->ForceCreate(devInputNode, deviceName.c_str(), mode);
             node->Node->SetDevice(DriverID, i);
             DriverHandlers dh{};
             dh.Ops = Operations;
             dh.Node = node->Node;
             dh.InputReports = new RingBuffer<InputReport>(16);
             dop->insert({i, std::move(dh)});
             return i;
         }
         ReturnLogError(-1, "No available slots for device %d", DriverID);
         return -1; /* -Werror=return-type */
     }
References vfs::Virtual::ForceCreate(), fs, vfs::Virtual::GetByPath(), FileNode::Node, Driver::DriverHandlers::Ops, ReturnLogError, S_IFCHR, S_IRGRP, S_IROTH, and S_IRWXU.
ReportInputEvent()
int Driver::Manager::ReportInputEvent (dev_t DriverID, InputReport * Report)
Definition at line 718 of file daemon.cpp.
     {
         std::unordered_map<dev_t, Driver::DriverObject> &drivers =
             DriverManager->GetDrivers();
         const auto it = drivers.find(DriverID);
         if (it == drivers.end())
             ReturnLogError(-EINVAL, "Driver %d not found", DriverID);
         const Driver::DriverObject *drv = &it->second;
         auto dop = drv->DeviceOperations;
         auto dOps = dop->find(Report->Device);
         if (dOps == dop->end())
             ReturnLogError(-EINVAL, "Device %d not found", Report->Device);
         dOps->second.InputReports->Write(Report, 1);
         switch (Report->Type)
         {
         case INPUT_TYPE_KEYBOARD:
         {
             KeyboardReport *kReport = &Report->Keyboard;
             GlobalKeyboardInputReports.Write(kReport, 1);
             break;
         }
         case INPUT_TYPE_MOUSE:
         {
             MouseReport *mReport = &Report->Mouse;
             GlobalMouseInputReports.Write(mReport, 1);
             break;
         }
         default:
             assert(!"Invalid input type");
         }
         return 0;
     }
References assert, InputReport::Device, Driver::DriverObject::DeviceOperations, DriverManager, EINVAL, GetDrivers(), INPUT_TYPE_KEYBOARD, INPUT_TYPE_MOUSE, it, ReturnLogError, and InputReport::Type.
Referenced by v0::ReportInputEvent().
UnloadAllDrivers()
void Driver::Manager::UnloadAllDrivers ()
Definition at line 149 of file driver.cpp.
     {
         foreach (auto &var in Drivers)
         {
             DriverObject *Drv = &var.second;
             if (!Drv->Initialized)
                 continue;
             debug("Unloading driver %s", Drv->Name);
             int err = Drv->Final();
             if (err < 0)
             {
                 warn("Failed to unload driver %s: %s",
                      Drv->Name, strerror(err));
             }
             if (!Drv->InterruptHandlers->empty())
             {
                 foreach (auto &rInt in * Drv->InterruptHandlers)
                 {
                     Interrupts::RemoveHandler((void (*)(CPU::TrapFrame *))rInt.second);
                 }
                 Drv->InterruptHandlers->clear();
             }
         }
         Drivers.clear();
     }
References debug, Driver::DriverObject::Final, Driver::DriverObject::Initialized, Driver::DriverObject::InterruptHandlers, Driver::DriverObject::Name, Interrupts::RemoveHandler(), strerror(), and warn.
UnregisterDevice()
int Driver::Manager::UnregisterDevice (dev_t DriverID, dev_t Device)
Definition at line 699 of file daemon.cpp.
     {
         std::unordered_map<dev_t, Driver::DriverObject> &drivers =
             DriverManager->GetDrivers();
         const auto it = drivers.find(DriverID);
         if (it == drivers.end())
             ReturnLogError(-EINVAL, "Driver %d not found", DriverID);
         const Driver::DriverObject *drv = &it->second;
         auto dop = drv->DeviceOperations;
         const auto dOps = dop->find(Device);
         if (dOps == dop->end())
             ReturnLogError(-EINVAL, "Device %d not found", Device);
         dop->erase(dOps);
         fixme("remove eventX from /dev/input");
         fixme("delete InputReports");
         return 0;
     }
References Driver::DriverObject::DeviceOperations, DriverManager, EINVAL, vfs::fixme(), GetDrivers(), it, and ReturnLogError.
Referenced by v0::UnregisterDevice().
Field Documentation
devInputNode
FileNode* Driver::Manager::devInputNode = nullptr private
Definition at line 94 of file driver.hpp.
devNode
FileNode* Driver::Manager::devNode = nullptr private
Definition at line 93 of file driver.hpp.
DriverIDCounter
dev_t Driver::Manager::DriverIDCounter = 2 private
0 - generic null/zero/random/etc devices 1 - input/... devices
Definition at line 92 of file driver.hpp.
Drivers
std::unordered_map<dev_t, DriverObject> Driver::Manager::Drivers private
Definition at line 86 of file driver.hpp.
Referenced by GetDrivers().
GlobalKeyboardInputReports
RingBuffer<KeyboardReport> Driver::Manager::GlobalKeyboardInputReports
Definition at line 105 of file driver.hpp.
Referenced by Driver::__fs_Read(), and KernelConsole::VirtualTerminal::Read().
GlobalMouseInputReports
RingBuffer<MouseReport> Driver::Manager::GlobalMouseInputReports
Definition at line 106 of file driver.hpp.
Referenced by Driver::__fs_Read().
The documentation for this class was generated from the following files:
Kernel/include/driver.hpp
Kernel/core/driver/daemon.cpp
Kernel/core/driver/driver.cpp