Fennix Userspace: Userspace/musl/src/stdio/__fclose_ca.c File Reference
__fclose_ca.c File Reference
#include "stdio_impl.h"
Functions
int __fclose_ca (FILE *f)
Function Documentation
__fclose_ca()
int __fclose_ca (FILE * f)
Definition at line 3 of file __fclose_ca.c.
 {
     return f->close(f);
 }
References _IO_FILE::close, and f.
Referenced by __get_resolv_conf(), __lookup_serv(), name_from_hosts(), reverse_hosts(), and reverse_services().