Fennix Kernel: NetworkEthernet::Ethernet Class Reference
NetworkEthernet::Ethernet Class Reference
#include <eth.hpp>
Public Member Functions
NetworkInterfaceManager::DeviceInterface * GetInterface ()
Get driver interface.
Ethernet (NetworkInterfaceManager::DeviceInterface *Interface)
~Ethernet ()
void Send (MediaAccessControl MAC, FrameType Type, uint8_t *Data, size_t Length)
Send an Ethernet packet.
Public Member Functions inherited from NetworkInterfaceManager::Events
virtual void OnInterfaceAdded (DeviceInterface *Interface)
virtual void OnInterfaceRemoved (DeviceInterface *Interface)
virtual void OnInterfaceChanged (DeviceInterface *Interface)
virtual void OnInterfaceSent (DeviceInterface *Interface, uint8_t *Data, size_t Length)
Private Member Functions
void Receive (uint8_t *Data, size_t Length)
void OnInterfaceReceived (NetworkInterfaceManager::DeviceInterface *Interface, uint8_t *Data, size_t Length)
Private Attributes
NetworkInterfaceManager::DeviceInterface * Interface
Additional Inherited Members
Protected Member Functions inherited from NetworkInterfaceManager::Events
Events (DeviceInterface *Interface)
~Events ()
Detailed Description
Definition at line 73 of file eth.hpp.
Constructor & Destructor Documentation
Ethernet()
NetworkEthernet::Ethernet::Ethernet (NetworkInterfaceManager::DeviceInterface * Interface)
Definition at line 36 of file eth.cpp.
                                                                         : NetworkInterfaceManager::Events(Interface)
     {
         debug("Ethernet interface %#lx created.", this);
         this->Interface = Interface;
     }
References debug, and Interface.
~Ethernet()
NetworkEthernet::Ethernet::~Ethernet ()
Definition at line 42 of file eth.cpp.
     {
         debug("Ethernet interface %#lx destroyed.", this);
     }
References debug.
Member Function Documentation
GetInterface()
NetworkInterfaceManager::DeviceInterface* NetworkEthernet::Ethernet::GetInterface () inline
Get driver interface.
Returns
Driver interface
Definition at line 84 of file eth.hpp.
         {
             netdbg("Interface: %#lx (MAC: %s; IPv4: %s; IPv6: %s)", this->Interface,
                    this->Interface->MAC.ToString(),
                    this->Interface->IP.v4.ToStringLittleEndian(),
                    this->Interface->IP.v6.ToStringLittleEndian());
             return this->Interface;
         }
References Interface, NetworkInterfaceManager::DeviceInterface::MAC, netdbg, and MediaAccessControl::ToString().
Referenced by NetworkARP::ARP::Broadcast(), NetworkARP::ARP::OnEthernetPacketReceived(), NetworkARP::ARP::Resolve(), and NetworkIPv4::IPv4::Send().
OnInterfaceReceived()
void NetworkEthernet::Ethernet::OnInterfaceReceived (NetworkInterfaceManager::DeviceInterface * Interface, uint8_t * Data, size_t Length) private virtual
Reimplemented from NetworkInterfaceManager::Events.
Definition at line 129 of file eth.cpp.
     {
         if (Interface == this->Interface)
             this->Receive(Data, Length);
     }
References Interface, Length, and Receive().
Receive()
void NetworkEthernet::Ethernet::Receive (uint8_t * Data, size_t Length) private
Definition at line 65 of file eth.cpp.
     {
         EthernetPacket *Packet = (EthernetPacket *)Data;
         size_t PacketLength = Length - sizeof(EthernetHeader);
         /* TODO: I have to do checks here to be sure that PacketLength is right */
         UNUSED(PacketLength);
         MediaAccessControl SourceMAC;
         SourceMAC.FromHex(b48(Packet->Header.SourceMAC));
         MediaAccessControl DestinationMAC;
         DestinationMAC.FromHex(b48(Packet->Header.DestinationMAC));
         netdbg("Received frame type %#x from %s to %s", b16(Packet->Header.Type), SourceMAC.ToString(), DestinationMAC.ToString());
         /*                 Byte-swapped               little-endian                   */
         if (b48(Packet->Header.DestinationMAC) == 0xFFFFFFFFFFFF ||
             /*                 Byte-swapped           Driver interface has little-endian order */
             b48(Packet->Header.DestinationMAC) == this->Interface->MAC.ToHex())
         /* This is true only if the packet is for us (Interface MAC or broadcast) */
         {
             netdbg("Received data from %s [Type %#x]", SourceMAC.ToString(), b16(Packet->Header.Type));
             bool Reply = false;
             switch (b16(Packet->Header.Type))
             {
             case TYPE_IPV4:
                 foreach (auto e in RegisteredEvents)
                     if (e.Type == TYPE_IPV4)
                         Reply = e.Ptr->OnEthernetPacketReceived((uint8_t *)Packet->Data, Length);
                 break;
             case TYPE_ARP:
                 foreach (auto e in RegisteredEvents)
                     if (e.Type == TYPE_ARP)
                         Reply = e.Ptr->OnEthernetPacketReceived((uint8_t *)Packet->Data, Length);
                 break;
             case TYPE_RARP:
                 foreach (auto e in RegisteredEvents)
                     if (e.Type == TYPE_RARP)
                         Reply = e.Ptr->OnEthernetPacketReceived((uint8_t *)Packet->Data, Length);
                 break;
             case TYPE_IPV6:
                 foreach (auto e in RegisteredEvents)
                     if (e.Type == TYPE_IPV6)
                         Reply = e.Ptr->OnEthernetPacketReceived((uint8_t *)Packet->Data, Length);
                 break;
             default:
                 warn("Unknown packet type %#lx", Packet->Header.Type);
                 break;
             }
             if (Reply)
             {
                 /* FIXME: I should reply, right? I have to do more research here... */
                 // Packet->Header.DestinationMAC = Packet->Header.SourceMAC;
                 // Packet->Header.SourceMAC = b48(this->Interface->MAC.ToHex());
                 fixme("Replying to %s [%s]=>[%s]", SourceMAC.ToString(),
                       this->Interface->MAC.ToString(), DestinationMAC.ToString());
             }
         }
         else
         {
             netdbg("Packet not for us [%s]=>[%s]", this->Interface->MAC.ToString(), DestinationMAC.ToString());
         }
     }
References b16, b48, Data, NetworkEthernet::EthernetPacket::Data, NetworkEthernet::EthernetHeader::DestinationMAC, fixme, MediaAccessControl::FromHex(), NetworkEthernet::EthernetPacket::Header, Interface, Length, NetworkInterfaceManager::DeviceInterface::MAC, netdbg, NetworkEthernet::RegisteredEvents, NetworkEthernet::EthernetHeader::SourceMAC, MediaAccessControl::ToString(), NetworkEthernet::EthernetHeader::Type, NetworkEthernet::TYPE_ARP, NetworkEthernet::TYPE_IPV4, NetworkEthernet::TYPE_IPV6, NetworkEthernet::TYPE_RARP, UNUSED, and warn.
Referenced by OnInterfaceReceived().
Send()
void NetworkEthernet::Ethernet::Send (MediaAccessControl MAC, FrameType Type, uint8_t * Data, size_t Length)
Send an Ethernet packet.
Parameters
MAC The MAC address of the destination. (Big-endian)
Type The type of the packet.
Data The data to send.
Length The length of the data.
Definition at line 47 of file eth.cpp.
     {
         netdbg("Sending frame type %#x to %s", Type, MAC.ToString());
         size_t PacketLength = sizeof(EthernetHeader) + Length;
         EthernetPacket *Packet = (EthernetPacket *)kmalloc(PacketLength);
         Packet->Header.DestinationMAC = b48(MAC.ToHex());
         Packet->Header.SourceMAC = b48(this->Interface->MAC.ToHex());
         Packet->Header.Type = b16(Type);
         memcpy(Packet->Data, Data, Length);
         /* Network Interface Manager takes care of physical allocation.
            So basically, we allocate here and then it allocates again but 1:1 mapped. */
         // NIManager->Send(Interface, (uint8_t *)Packet, PacketLength);
         assert(!"Function not implemented");
         kfree(Packet);
     }
References assert, b16, b48, Data, NetworkEthernet::EthernetPacket::Data, NetworkEthernet::EthernetHeader::DestinationMAC, NetworkEthernet::EthernetPacket::Header, Interface, kfree, kmalloc, Length, NetworkInterfaceManager::DeviceInterface::MAC, memcpy(), netdbg, NetworkEthernet::EthernetHeader::SourceMAC, MediaAccessControl::ToHex(), MediaAccessControl::ToString(), and NetworkEthernet::EthernetHeader::Type.
Referenced by NetworkARP::ARP::Broadcast(), NetworkARP::ARP::OnEthernetPacketReceived(), NetworkARP::ARP::Resolve(), and NetworkIPv4::IPv4::Send().
Field Documentation
Interface
NetworkInterfaceManager::DeviceInterface* NetworkEthernet::Ethernet::Interface private
Definition at line 76 of file eth.hpp.
Referenced by Ethernet(), GetInterface(), OnInterfaceReceived(), Receive(), and Send().
The documentation for this class was generated from the following files:
Kernel/include/net/eth.hpp
Kernel/network/eth.cpp