Fennix Userspace: Userspace/mlibc/tests/posix/pthread_thread_local.c File Reference
pthread_thread_local.c File Reference
#include <stdio.h>
#include <pthread.h>
#include <assert.h>
Functions
void * check_counter (void *arg)
int main ()
Variables
_Thread_local unsigned int counter = 9999
_Thread_local unsigned int uninitialized
Function Documentation
check_counter()
void* check_counter (void * arg)
Definition at line 8 of file pthread_thread_local.c.
 {
     (void)arg;
     fprintf(stderr, "counter for worker thread: %d, at %p\n", counter, &counter);
     fflush(stderr);
     assert(counter == 9999);
     fprintf(stderr, "uninitialized data for worker thread: %d, at %p\n", uninitialized, &uninitialized);
     fflush(stderr);
     assert(uninitialized == 0);
     ++counter;
     ++uninitialized;
     fprintf(stderr, "counter for worker thread: %d\n", counter);
     fflush(stderr);
     assert(counter == 10000);
     assert(uninitialized == 1);
     return NULL;
 }
References assert, counter, fflush(), fprintf(), NULL, stderr, and uninitialized.
Referenced by main().
main()
int main (void)
Definition at line 28 of file pthread_thread_local.c.
 {
     fprintf(stderr, "counter for main thread: %d, at %p\n", counter, &counter);
     fflush(stderr);
     assert(counter == 9999);
     fprintf(stderr, "uninitialized data for main thread: %d, at %p\n", uninitialized, &uninitialized);
     fflush(stderr);
     assert(uninitialized == 0);
     ++counter;
     ++uninitialized;
     fprintf(stderr, "counter for main: %d\n", counter);
     fflush(stderr);
     assert(counter == 10000);
     assert(uninitialized == 1);
     pthread_t thd;
     pthread_create(&thd, NULL, check_counter, NULL);
     pthread_join(thd, NULL);
     fprintf(stderr, "counter for main: %d\n", counter);
     fflush(stderr);
     assert(counter == 10000);
     assert(uninitialized == 1);
 }
References assert, check_counter(), counter, fflush(), fprintf(), NULL, pthread_create(), pthread_join(), stderr, and uninitialized.
Variable Documentation
counter
_Thread_local unsigned int counter = 9999
Definition at line 5 of file pthread_thread_local.c.
Referenced by check_counter(), and main().
uninitialized
_Thread_local unsigned int uninitialized
Definition at line 6 of file pthread_thread_local.c.
Referenced by check_counter(), and main().