Fennix: Kernel/Core/Crash/chfcts.hpp File Reference
chfcts.hpp File Reference
#include <types.h>
#include <interrupts.hpp>
#include <task.hpp>
#include <cpu.hpp>
Data Structures
class CrashHandler::CrashKeyboardDriver
Namespaces
CrashHandler
Enumerations
enum Keys {
KEY_INVALID = 0x0 , KEY_D_ESCAPE = 0x1 , KEY_D_1 = 0x2 , KEY_D_2 = 0x3 ,
KEY_D_3 = 0x4 , KEY_D_4 = 0x5 , KEY_D_5 = 0x6 , KEY_D_6 = 0x7 ,
KEY_D_7 = 0x8 , KEY_D_8 = 0x9 , KEY_D_9 = 0xa , KEY_D_0 = 0xb ,
KEY_D_MINUS = 0xc , KEY_D_EQUALS = 0xd , KEY_D_BACKSPACE = 0xe , KEY_D_TAB = 0xf ,
KEY_D_Q = 0x10 , KEY_D_W = 0x11 , KEY_D_E = 0x12 , KEY_D_R = 0x13 ,
KEY_D_T = 0x14 , KEY_D_Y = 0x15 , KEY_D_U = 0x16 , KEY_D_I = 0x17 ,
KEY_D_O = 0x18 , KEY_D_P = 0x19 , KEY_D_LBRACKET = 0x1a , KEY_D_RBRACKET = 0x1b ,
KEY_D_RETURN = 0x1c , KEY_D_LCTRL = 0x1d , KEY_D_A = 0x1e , KEY_D_S = 0x1f ,
KEY_D_D = 0x20 , KEY_D_F = 0x21 , KEY_D_G = 0x22 , KEY_D_H = 0x23 ,
KEY_D_J = 0x24 , KEY_D_K = 0x25 , KEY_D_L = 0x26 , KEY_D_SEMICOLON = 0x27 ,
KEY_D_APOSTROPHE = 0x28 , KEY_D_GRAVE = 0x29 , KEY_D_LSHIFT = 0x2a , KEY_D_BACKSLASH = 0x2b ,
KEY_D_Z = 0x2c , KEY_D_X = 0x2d , KEY_D_C = 0x2e , KEY_D_V = 0x2f ,
KEY_D_B = 0x30 , KEY_D_N = 0x31 , KEY_D_M = 0x32 , KEY_D_COMMA = 0x33 ,
KEY_D_PERIOD = 0x34 , KEY_D_SLASH = 0x35 , KEY_D_RSHIFT = 0x36 , KEY_D_PRTSC = 0x37 ,
KEY_D_LALT = 0x38 , KEY_D_SPACE = 0x39 , KEY_D_CAPSLOCK = 0x3a , KEY_D_NUMLOCK = 0x45 ,
KEY_D_SCROLLLOCK = 0x46 , KEY_D_KP_MULTIPLY = 0x37 , KEY_D_KP_7 = 0x47 , KEY_D_KP_8 = 0x48 ,
KEY_D_KP_9 = 0x49 , KEY_D_KP_MINUS = 0x4a , KEY_D_KP_4 = 0x4b , KEY_D_KP_5 = 0x4c ,
KEY_D_KP_6 = 0x4d , KEY_D_KP_PLUS = 0x4e , KEY_D_KP_1 = 0x4f , KEY_D_KP_2 = 0x50 ,
KEY_D_KP_3 = 0x51 , KEY_D_KP_0 = 0x52 , KEY_D_KP_PERIOD = 0x53 , KEY_D_F1 = 0x3b ,
KEY_D_F2 = 0x3c , KEY_D_F3 = 0x3d , KEY_D_F4 = 0x3e , KEY_D_F5 = 0x3f ,
KEY_D_F6 = 0x40 , KEY_D_F7 = 0x41 , KEY_D_F8 = 0x42 , KEY_D_F9 = 0x43 ,
KEY_D_F10 = 0x44 , KEY_D_F11 = 0x57 , KEY_D_F12 = 0x58 , KEY_D_UP = 0x48 ,
KEY_D_LEFT = 0x4b , KEY_D_RIGHT = 0x4d , KEY_D_DOWN = 0x50 , KEY_U_ESCAPE = 0x81 ,
KEY_U_1 = 0x82 , KEY_U_2 = 0x83 , KEY_U_3 = 0x84 , KEY_U_4 = 0x85 ,
KEY_U_5 = 0x86 , KEY_U_6 = 0x87 , KEY_U_7 = 0x88 , KEY_U_8 = 0x89 ,
KEY_U_9 = 0x8a , KEY_U_0 = 0x8b , KEY_U_MINUS = 0x8c , KEY_U_EQUALS = 0x8d ,
KEY_U_BACKSPACE = 0x8e , KEY_U_TAB = 0x8f , KEY_U_Q = 0x90 , KEY_U_W = 0x91 ,
KEY_U_E = 0x92 , KEY_U_R = 0x93 , KEY_U_T = 0x94 , KEY_U_Y = 0x95 ,
KEY_U_U = 0x96 , KEY_U_I = 0x97 , KEY_U_O = 0x98 , KEY_U_P = 0x99 ,
KEY_U_LBRACKET = 0x9a , KEY_U_RBRACKET = 0x9b , KEY_U_RETURN = 0x9c , KEY_U_LCTRL = 0x9d ,
KEY_U_A = 0x9e , KEY_U_S = 0x9f , KEY_U_D = 0xa0 , KEY_U_F = 0xa1 ,
KEY_U_G = 0xa2 , KEY_U_H = 0xa3 , KEY_U_J = 0xa4 , KEY_U_K = 0xa5 ,
KEY_U_L = 0xa6 , KEY_U_SEMICOLON = 0xa7 , KEY_U_APOSTROPHE = 0xa8 , KEY_U_GRAVE = 0xa9 ,
KEY_U_LSHIFT = 0xaa , KEY_U_BACKSLASH = 0xab , KEY_U_Z = 0xac , KEY_U_X = 0xad ,
KEY_U_C = 0xae , KEY_U_V = 0xaf , KEY_U_B = 0xb0 , KEY_U_N = 0xb1 ,
KEY_U_M = 0xb2 , KEY_U_COMMA = 0xb3 , KEY_U_PERIOD = 0xb4 , KEY_U_SLASH = 0xb5 ,
KEY_U_RSHIFT = 0xb6 , KEY_U_KP_MULTIPLY = 0xb7 , KEY_U_LALT = 0xb8 , KEY_U_SPACE = 0xb9 ,
KEY_U_CAPSLOCK = 0xba , KEY_U_F1 = 0xbb , KEY_U_F2 = 0xbc , KEY_U_F3 = 0xbd ,
KEY_U_F4 = 0xbe , KEY_U_F5 = 0xbf , KEY_U_F6 = 0xc0 , KEY_U_F7 = 0xc1 ,
KEY_U_F8 = 0xc2 , KEY_U_F9 = 0xc3 , KEY_U_F10 = 0xc4 , KEY_U_NUMLOCK = 0xc5 ,
KEY_U_SCROLLLOCK = 0xc6 , KEY_U_KP_7 = 0xc7 , KEY_U_KP_8 = 0xc8 , KEY_U_KP_9 = 0xc9 ,
KEY_U_KP_MINUS = 0xca , KEY_U_KP_4 = 0xcb , KEY_U_KP_5 = 0xcc , KEY_U_KP_6 = 0xcd ,
KEY_U_KP_PLUS = 0xce , KEY_U_KP_1 = 0xcf , KEY_U_KP_2 = 0xd0 , KEY_U_KP_3 = 0xd1 ,
KEY_U_KP_0 = 0xd2 , KEY_U_KP_PERIOD = 0xd3 , KEY_U_F11 = 0xd7 , KEY_U_F12 = 0xd8
}
Functions
void CrashHandler::TraceFrames (CHArchTrapFrame *Frame, int Count, SymbolResolver::Symbols *SymHandle, bool Kernel)
void CrashHandler::ArrowInput (uint8_t key)
void CrashHandler::UserInput (char *Input)
void CrashHandler::HookKeyboard ()
void CrashHandler::DisplayMainScreen (CRData data)
void CrashHandler::DisplayDetailsScreen (CRData data)
void CrashHandler::DisplayStackFrameScreen (CRData data)
void CrashHandler::DisplayTasksScreen (CRData data)
void CrashHandler::DisplayConsoleScreen (CRData data)
void DivideByZeroExceptionHandler (CHArchTrapFrame *Frame)
void DebugExceptionHandler (CHArchTrapFrame *Frame)
void NonMaskableInterruptExceptionHandler (CHArchTrapFrame *Frame)
void BreakpointExceptionHandler (CHArchTrapFrame *Frame)
void OverflowExceptionHandler (CHArchTrapFrame *Frame)
void BoundRangeExceptionHandler (CHArchTrapFrame *Frame)
void InvalidOpcodeExceptionHandler (CHArchTrapFrame *Frame)
void DeviceNotAvailableExceptionHandler (CHArchTrapFrame *Frame)
void DoubleFaultExceptionHandler (CHArchTrapFrame *Frame)
void CoprocessorSegmentOverrunExceptionHandler (CHArchTrapFrame *Frame)
void InvalidTSSExceptionHandler (CHArchTrapFrame *Frame)
void SegmentNotPresentExceptionHandler (CHArchTrapFrame *Frame)
void StackFaultExceptionHandler (CHArchTrapFrame *Frame)
void GeneralProtectionExceptionHandler (CHArchTrapFrame *Frame)
void PageFaultExceptionHandler (CHArchTrapFrame *Frame)
void x87FloatingPointExceptionHandler (CHArchTrapFrame *Frame)
void AlignmentCheckExceptionHandler (CHArchTrapFrame *Frame)
void MachineCheckExceptionHandler (CHArchTrapFrame *Frame)
void SIMDFloatingPointExceptionHandler (CHArchTrapFrame *Frame)
void VirtualizationExceptionHandler (CHArchTrapFrame *Frame)
void SecurityExceptionHandler (CHArchTrapFrame *Frame)
void UnknownExceptionHandler (CHArchTrapFrame *Frame)
void UserModeExceptionHandler (CHArchTrapFrame *Frame)
Variables
int CrashHandler::SBIdx = 255
Enumeration Type Documentation
Keys
enum Keys
Enumerator
KEY_INVALID
KEY_D_ESCAPE
KEY_D_1
KEY_D_2
KEY_D_3
KEY_D_4
KEY_D_5
KEY_D_6
KEY_D_7
KEY_D_8
KEY_D_9
KEY_D_0
KEY_D_MINUS
KEY_D_EQUALS
KEY_D_BACKSPACE
KEY_D_TAB
KEY_D_Q
KEY_D_W
KEY_D_E
KEY_D_R
KEY_D_T
KEY_D_Y
KEY_D_U
KEY_D_I
KEY_D_O
KEY_D_P
KEY_D_LBRACKET
KEY_D_RBRACKET
KEY_D_RETURN
KEY_D_LCTRL
KEY_D_A
KEY_D_S
KEY_D_D
KEY_D_F
KEY_D_G
KEY_D_H
KEY_D_J
KEY_D_K
KEY_D_L
KEY_D_SEMICOLON
KEY_D_APOSTROPHE
KEY_D_GRAVE
KEY_D_LSHIFT
KEY_D_BACKSLASH
KEY_D_Z
KEY_D_X
KEY_D_C
KEY_D_V
KEY_D_B
KEY_D_N
KEY_D_M
KEY_D_COMMA
KEY_D_PERIOD
KEY_D_SLASH
KEY_D_RSHIFT
KEY_D_PRTSC
KEY_D_LALT
KEY_D_SPACE
KEY_D_CAPSLOCK
KEY_D_NUMLOCK
KEY_D_SCROLLLOCK
KEY_D_KP_MULTIPLY
KEY_D_KP_7
KEY_D_KP_8
KEY_D_KP_9
KEY_D_KP_MINUS
KEY_D_KP_4
KEY_D_KP_5
KEY_D_KP_6
KEY_D_KP_PLUS
KEY_D_KP_1
KEY_D_KP_2
KEY_D_KP_3
KEY_D_KP_0
KEY_D_KP_PERIOD
KEY_D_F1
KEY_D_F2
KEY_D_F3
KEY_D_F4
KEY_D_F5
KEY_D_F6
KEY_D_F7
KEY_D_F8
KEY_D_F9
KEY_D_F10
KEY_D_F11
KEY_D_F12
KEY_D_UP
KEY_D_LEFT
KEY_D_RIGHT
KEY_D_DOWN
KEY_U_ESCAPE
KEY_U_1
KEY_U_2
KEY_U_3
KEY_U_4
KEY_U_5
KEY_U_6
KEY_U_7
KEY_U_8
KEY_U_9
KEY_U_0
KEY_U_MINUS
KEY_U_EQUALS
KEY_U_BACKSPACE
KEY_U_TAB
KEY_U_Q
KEY_U_W
KEY_U_E
KEY_U_R
KEY_U_T
KEY_U_Y
KEY_U_U
KEY_U_I
KEY_U_O
KEY_U_P
KEY_U_LBRACKET
KEY_U_RBRACKET
KEY_U_RETURN
KEY_U_LCTRL
KEY_U_A
KEY_U_S
KEY_U_D
KEY_U_F
KEY_U_G
KEY_U_H
KEY_U_J
KEY_U_K
KEY_U_L
KEY_U_SEMICOLON
KEY_U_APOSTROPHE
KEY_U_GRAVE
KEY_U_LSHIFT
KEY_U_BACKSLASH
KEY_U_Z
KEY_U_X
KEY_U_C
KEY_U_V
KEY_U_B
KEY_U_N
KEY_U_M
KEY_U_COMMA
KEY_U_PERIOD
KEY_U_SLASH
KEY_U_RSHIFT
KEY_U_KP_MULTIPLY
KEY_U_LALT
KEY_U_SPACE
KEY_U_CAPSLOCK
KEY_U_F1
KEY_U_F2
KEY_U_F3
KEY_U_F4
KEY_U_F5
KEY_U_F6
KEY_U_F7
KEY_U_F8
KEY_U_F9
KEY_U_F10
KEY_U_NUMLOCK
KEY_U_SCROLLLOCK
KEY_U_KP_7
KEY_U_KP_8
KEY_U_KP_9
KEY_U_KP_MINUS
KEY_U_KP_4
KEY_U_KP_5
KEY_U_KP_6
KEY_U_KP_PLUS
KEY_U_KP_1
KEY_U_KP_2
KEY_U_KP_3
KEY_U_KP_0
KEY_U_KP_PERIOD
KEY_U_F11
KEY_U_F12
Definition at line 56 of file chfcts.hpp.
 {
     KEY_INVALID = 0x0,
     KEY_D_ESCAPE = 0x1,
     KEY_D_1 = 0x2,
     KEY_D_2 = 0x3,
     KEY_D_3 = 0x4,
     KEY_D_4 = 0x5,
     KEY_D_5 = 0x6,
     KEY_D_6 = 0x7,
     KEY_D_7 = 0x8,
     KEY_D_8 = 0x9,
     KEY_D_9 = 0xa,
     KEY_D_0 = 0xb,
     KEY_D_MINUS = 0xc,
     KEY_D_EQUALS = 0xd,
     KEY_D_BACKSPACE = 0xe,
     KEY_D_TAB = 0xf,
     KEY_D_Q = 0x10,
     KEY_D_W = 0x11,
     KEY_D_E = 0x12,
     KEY_D_R = 0x13,
     KEY_D_T = 0x14,
     KEY_D_Y = 0x15,
     KEY_D_U = 0x16,
     KEY_D_I = 0x17,
     KEY_D_O = 0x18,
     KEY_D_P = 0x19,
     KEY_D_LBRACKET = 0x1a,
     KEY_D_RBRACKET = 0x1b,
     KEY_D_RETURN = 0x1c,
     KEY_D_LCTRL = 0x1d,
     KEY_D_A = 0x1e,
     KEY_D_S = 0x1f,
     KEY_D_D = 0x20,
     KEY_D_F = 0x21,
     KEY_D_G = 0x22,
     KEY_D_H = 0x23,
     KEY_D_J = 0x24,
     KEY_D_K = 0x25,
     KEY_D_L = 0x26,
     KEY_D_SEMICOLON = 0x27,
     KEY_D_APOSTROPHE = 0x28,
     KEY_D_GRAVE = 0x29,
     KEY_D_LSHIFT = 0x2a,
     KEY_D_BACKSLASH = 0x2b,
     KEY_D_Z = 0x2c,
     KEY_D_X = 0x2d,
     KEY_D_C = 0x2e,
     KEY_D_V = 0x2f,
     KEY_D_B = 0x30,
     KEY_D_N = 0x31,
     KEY_D_M = 0x32,
     KEY_D_COMMA = 0x33,
     KEY_D_PERIOD = 0x34,
     KEY_D_SLASH = 0x35,
     KEY_D_RSHIFT = 0x36,
     KEY_D_PRTSC = 0x37,
     KEY_D_LALT = 0x38,
     KEY_D_SPACE = 0x39,
     KEY_D_CAPSLOCK = 0x3a,
     KEY_D_NUMLOCK = 0x45,
     KEY_D_SCROLLLOCK = 0x46,
     KEY_D_KP_MULTIPLY = 0x37,
     KEY_D_KP_7 = 0x47,
     KEY_D_KP_8 = 0x48,
     KEY_D_KP_9 = 0x49,
     KEY_D_KP_MINUS = 0x4a,
     KEY_D_KP_4 = 0x4b,
     KEY_D_KP_5 = 0x4c,
     KEY_D_KP_6 = 0x4d,
     KEY_D_KP_PLUS = 0x4e,
     KEY_D_KP_1 = 0x4f,
     KEY_D_KP_2 = 0x50,
     KEY_D_KP_3 = 0x51,
     KEY_D_KP_0 = 0x52,
     KEY_D_KP_PERIOD = 0x53,
     KEY_D_F1 = 0x3b,
     KEY_D_F2 = 0x3c,
     KEY_D_F3 = 0x3d,
     KEY_D_F4 = 0x3e,
     KEY_D_F5 = 0x3f,
     KEY_D_F6 = 0x40,
     KEY_D_F7 = 0x41,
     KEY_D_F8 = 0x42,
     KEY_D_F9 = 0x43,
     KEY_D_F10 = 0x44,
     KEY_D_F11 = 0x57,
     KEY_D_F12 = 0x58,
     KEY_D_UP = 0x48,
     KEY_D_LEFT = 0x4b,
     KEY_D_RIGHT = 0x4d,
     KEY_D_DOWN = 0x50,
     KEY_U_ESCAPE = 0x81,
     KEY_U_1 = 0x82,
     KEY_U_2 = 0x83,
     KEY_U_3 = 0x84,
     KEY_U_4 = 0x85,
     KEY_U_5 = 0x86,
     KEY_U_6 = 0x87,
     KEY_U_7 = 0x88,
     KEY_U_8 = 0x89,
     KEY_U_9 = 0x8a,
     KEY_U_0 = 0x8b,
     KEY_U_MINUS = 0x8c,
     KEY_U_EQUALS = 0x8d,
     KEY_U_BACKSPACE = 0x8e,
     KEY_U_TAB = 0x8f,
     KEY_U_Q = 0x90,
     KEY_U_W = 0x91,
     KEY_U_E = 0x92,
     KEY_U_R = 0x93,
     KEY_U_T = 0x94,
     KEY_U_Y = 0x95,
     KEY_U_U = 0x96,
     KEY_U_I = 0x97,
     KEY_U_O = 0x98,
     KEY_U_P = 0x99,
     KEY_U_LBRACKET = 0x9a,
     KEY_U_RBRACKET = 0x9b,
     KEY_U_RETURN = 0x9c,
     KEY_U_LCTRL = 0x9d,
     KEY_U_A = 0x9e,
     KEY_U_S = 0x9f,
     KEY_U_D = 0xa0,
     KEY_U_F = 0xa1,
     KEY_U_G = 0xa2,
     KEY_U_H = 0xa3,
     KEY_U_J = 0xa4,
     KEY_U_K = 0xa5,
     KEY_U_L = 0xa6,
     KEY_U_SEMICOLON = 0xa7,
     KEY_U_APOSTROPHE = 0xa8,
     KEY_U_GRAVE = 0xa9,
     KEY_U_LSHIFT = 0xaa,
     KEY_U_BACKSLASH = 0xab,
     KEY_U_Z = 0xac,
     KEY_U_X = 0xad,
     KEY_U_C = 0xae,
     KEY_U_V = 0xaf,
     KEY_U_B = 0xb0,
     KEY_U_N = 0xb1,
     KEY_U_M = 0xb2,
     KEY_U_COMMA = 0xb3,
     KEY_U_PERIOD = 0xb4,
     KEY_U_SLASH = 0xb5,
     KEY_U_RSHIFT = 0xb6,
     KEY_U_KP_MULTIPLY = 0xb7,
     KEY_U_LALT = 0xb8,
     KEY_U_SPACE = 0xb9,
     KEY_U_CAPSLOCK = 0xba,
     KEY_U_F1 = 0xbb,
     KEY_U_F2 = 0xbc,
     KEY_U_F3 = 0xbd,
     KEY_U_F4 = 0xbe,
     KEY_U_F5 = 0xbf,
     KEY_U_F6 = 0xc0,
     KEY_U_F7 = 0xc1,
     KEY_U_F8 = 0xc2,
     KEY_U_F9 = 0xc3,
     KEY_U_F10 = 0xc4,
     KEY_U_NUMLOCK = 0xc5,
     KEY_U_SCROLLLOCK = 0xc6,
     KEY_U_KP_7 = 0xc7,
     KEY_U_KP_8 = 0xc8,
     KEY_U_KP_9 = 0xc9,
     KEY_U_KP_MINUS = 0xca,
     KEY_U_KP_4 = 0xcb,
     KEY_U_KP_5 = 0xcc,
     KEY_U_KP_6 = 0xcd,
     KEY_U_KP_PLUS = 0xce,
     KEY_U_KP_1 = 0xcf,
     KEY_U_KP_2 = 0xd0,
     KEY_U_KP_3 = 0xd1,
     KEY_U_KP_0 = 0xd2,
     KEY_U_KP_PERIOD = 0xd3,
     KEY_U_F11 = 0xd7,
     KEY_U_F12 = 0xd8,
 };
Function Documentation
AlignmentCheckExceptionHandler()
void AlignmentCheckExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 276 of file CrashDetails.cpp.
 {
     fixme("Alignment check exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
BoundRangeExceptionHandler()
void BoundRangeExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 54 of file CrashDetails.cpp.
 {
     fixme("Bound range exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
BreakpointExceptionHandler()
void BreakpointExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 44 of file CrashDetails.cpp.
 {
     fixme("Breakpoint exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
CoprocessorSegmentOverrunExceptionHandler()
void CoprocessorSegmentOverrunExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 75 of file CrashDetails.cpp.
 {
     fixme("Coprocessor segment overrun exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
DebugExceptionHandler()
void DebugExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 33 of file CrashDetails.cpp.
 {
     CrashHandler::EHPrint("\eDD2920System crashed!\n");
     CrashHandler::EHPrint("Kernel triggered debug exception.\n");
     UNUSED(Frame);
 }
References CrashHandler::EHPrint(), and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
DeviceNotAvailableExceptionHandler()
void DeviceNotAvailableExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 65 of file CrashDetails.cpp.
 {
     fixme("Device not available exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
DivideByZeroExceptionHandler()
void DivideByZeroExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 28 of file CrashDetails.cpp.
 {
     fixme("Divide by zero exception\n");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
DoubleFaultExceptionHandler()
void DoubleFaultExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 70 of file CrashDetails.cpp.
 {
     fixme("Double fault exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
GeneralProtectionExceptionHandler()
void GeneralProtectionExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 106 of file CrashDetails.cpp.
 {
     // staticbuffer(descbuf);
     // staticbuffer(desc_ext);
     // staticbuffer(desc_table);
     // staticbuffer(desc_idx);
     // staticbuffer(desc_tmp);
     CPU::x64::SelectorErrorCode SelCode = {.raw = Frame->ErrorCode};
     // switch (SelCode.Table)
     // {
     // case CPU::x64::0b00:
     //     memcpy(desc_tmp, "GDT", 3);
     //     break;
     // case CPU::x64::0b01:
     //     memcpy(desc_tmp, "IDT", 3);
     //     break;
     // case CPU::x64::0b10:
     //     memcpy(desc_tmp, "LDT", 3);
     //     break;
     // case CPU::x64::0b11:
     //     memcpy(desc_tmp, "IDT", 3);
     //     break;
     // default:
     //     memcpy(desc_tmp, "Unknown", 7);
     //     break;
     // }
     CrashHandler::EHPrint("\eDD2920System crashed!\n");
     CrashHandler::EHPrint("Kernel performed an illegal operation.\n");
     CrashHandler::EHPrint("More info about the exception:\n");
     CrashHandler::EHPrint("External: %d\n", SelCode.External);
     CrashHandler::EHPrint("Table: %d\n", SelCode.Table);
     CrashHandler::EHPrint("Index: %#x\n", SelCode.Idx);
 }
References CrashHandler::EHPrint(), and CPU::x64::SelectorErrorCode::raw.
Referenced by CrashHandler::DisplayDetailsScreen().
InvalidOpcodeExceptionHandler()
void InvalidOpcodeExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 59 of file CrashDetails.cpp.
 {
     CrashHandler::EHPrint("\eDD2920System crashed!\n");
     CrashHandler::EHPrint("Kernel tried to execute an invalid opcode.\n");
     UNUSED(Frame);
 }
References CrashHandler::EHPrint(), and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
InvalidTSSExceptionHandler()
void InvalidTSSExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 80 of file CrashDetails.cpp.
 {
     fixme("Invalid TSS exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
MachineCheckExceptionHandler()
void MachineCheckExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 281 of file CrashDetails.cpp.
 {
     fixme("Machine check exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
NonMaskableInterruptExceptionHandler()
void NonMaskableInterruptExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 39 of file CrashDetails.cpp.
 {
     fixme("NMI exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
OverflowExceptionHandler()
void OverflowExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 49 of file CrashDetails.cpp.
 {
     fixme("Overflow exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
PageFaultExceptionHandler()
void PageFaultExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 139 of file CrashDetails.cpp.
 {
     CPU::x64::PageFaultErrorCode params = {.raw = (uint32_t)Frame->ErrorCode};
     CrashHandler::EHPrint("\eDD2920System crashed!\n\eFFFFFF");
 #if defined(__amd64__)
     CrashHandler::EHPrint("An exception occurred at %#lx by %#lx\n", CPU::x64::readcr2().PFLA, Frame->rip);
 #elif defined(__i386__)
     CrashHandler::EHPrint("An exception occurred at %#lx by %#lx\n", CPU::x64::readcr2().PFLA, Frame->eip);
 #elif defined(__aarch64__)
 #endif
     CrashHandler::EHPrint("Page: %s\n", params.P ? "Present" : "Not Present");
     CrashHandler::EHPrint("Write Operation: %s\n", params.W ? "Read-Only" : "Read-Write");
     CrashHandler::EHPrint("Processor Mode: %s\n", params.U ? "User-Mode" : "Kernel-Mode");
     CrashHandler::EHPrint("CPU Reserved Bits: %s\n", params.R ? "Reserved" : "Unreserved");
     CrashHandler::EHPrint("Caused By An Instruction Fetch: %s\n", params.I ? "Yes" : "No");
     CrashHandler::EHPrint("Caused By A Protection-Key Violation: %s\n", params.PK ? "Yes" : "No");
     CrashHandler::EHPrint("Caused By A Shadow Stack Access: %s\n", params.SS ? "Yes" : "No");
     CrashHandler::EHPrint("Caused By An SGX Violation: %s\n", params.SGX ? "Yes" : "No");
     if (Frame->ErrorCode & 0x00000008)
         CrashHandler::EHPrint("One or more page directory entries contain reserved bits which are set to 1.\n");
     else
         CrashHandler::EHPrint(PageFaultDescriptions[Frame->ErrorCode & 0b111]);
 #ifdef DEBUG
     uintptr_t CheckPageFaultAddress = 0;
     CheckPageFaultAddress = CPU::x64::readcr2().PFLA;
     if (CheckPageFaultAddress == 0)
 #ifdef __amd64__
         CheckPageFaultAddress = Frame->rip;
 #elif defined(__i386__)
         CheckPageFaultAddress = Frame->eip;
 #elif defined(__aarch64__)
         CheckPageFaultAddress = 0;
 #endif
     Memory::Virtual vma = Memory::Virtual(((Memory::PageTable4 *)CPU::x64::readcr3().raw));
     bool PageAvailable = vma.Check((void *)CheckPageFaultAddress);
     debug("Page available (Check(...)): %s. %s",
           PageAvailable ? "Yes" : "No",
           (params.P && !PageAvailable) ? "CR2 == Present; Check() != Present??????" : "CR2 confirms Check() result.");
     if (PageAvailable)
     {
         bool Present = vma.Check((void *)CheckPageFaultAddress);
         bool ReadWrite = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::RW);
         bool User = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::US);
         bool WriteThrough = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::PWT);
         bool CacheDisabled = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::PCD);
         bool Accessed = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::A);
         bool Dirty = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::D);
         bool Global = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::G);
         /* ... */
         debug("Page available: %s", Present ? "Yes" : "No");
         debug("Page read/write: %s", ReadWrite ? "Yes" : "No");
         debug("Page user/kernel: %s", User ? "User" : "Kernel");
         debug("Page write-through: %s", WriteThrough ? "Yes" : "No");
         debug("Page cache disabled: %s", CacheDisabled ? "Yes" : "No");
         debug("Page accessed: %s", Accessed ? "Yes" : "No");
         debug("Page dirty: %s", Dirty ? "Yes" : "No");
         debug("Page global: %s", Global ? "Yes" : "No");
         if (Present)
         {
             uintptr_t CheckPageFaultLinearAddress = (uintptr_t)CheckPageFaultAddress;
             CheckPageFaultLinearAddress &= 0xFFFFFFFFFFFFF000;
             debug("%#lx -> %#lx", CheckPageFaultAddress, CheckPageFaultLinearAddress);
             Memory::Virtual::PageMapIndexer Index = Memory::Virtual::PageMapIndexer((uintptr_t)CheckPageFaultLinearAddress);
             debug("Index for %#lx is PML:%d PDPTE:%d PDE:%d PTE:%d",
                   CheckPageFaultLinearAddress,
                   Index.PMLIndex,
                   Index.PDPTEIndex,
                   Index.PDEIndex,
                   Index.PTEIndex);
             Memory::PageMapLevel4 PML4 = ((Memory::PageTable4 *)CPU::x64::readcr3().raw)->Entries[Index.PMLIndex];
             Memory::PageDirectoryPointerTableEntryPtr *PDPTE = (Memory::PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4.GetAddress() << 12);
             Memory::PageDirectoryEntryPtr *PDE = (Memory::PageDirectoryEntryPtr *)((uintptr_t)PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
             Memory::PageTableEntryPtr *PTE = (Memory::PageTableEntryPtr *)((uintptr_t)PDE->Entries[Index.PDEIndex].GetAddress() << 12);
             debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                   Index.PMLIndex, 0, 0, 0,
                   PML4.Present ? "1" : "0",
                   PML4.ReadWrite ? "1" : "0",
                   PML4.UserSupervisor ? "1" : "0",
                   PML4.WriteThrough ? "1" : "0",
                   PML4.CacheDisable ? "1" : "0",
                   PML4.Accessed ? "1" : "0",
                   PML4.ExecuteDisable ? "1" : "0",
                   PML4.GetAddress() << 12);
             debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                   Index.PMLIndex, Index.PDPTEIndex, 0, 0,
                   PDPTE->Entries[Index.PDPTEIndex].Present ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].ReadWrite ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].UserSupervisor ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].WriteThrough ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].CacheDisable ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].Accessed ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].ExecuteDisable ? "1" : "0",
                   PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
             debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                   Index.PMLIndex, Index.PDPTEIndex, Index.PDEIndex, 0,
                   PDE->Entries[Index.PDEIndex].Present ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].ReadWrite ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].UserSupervisor ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].WriteThrough ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].CacheDisable ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].Accessed ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].ExecuteDisable ? "1" : "0",
                   PDE->Entries[Index.PDEIndex].GetAddress() << 12);
             debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s D:%s PAT:%s G:%s PK:%d NX:%s Address:%#lx",
                   Index.PMLIndex, Index.PDPTEIndex, Index.PDEIndex, Index.PTEIndex,
                   PTE->Entries[Index.PTEIndex].Present ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].ReadWrite ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].UserSupervisor ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].WriteThrough ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].CacheDisable ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].Accessed ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].Dirty ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].PageAttributeTable ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].Global ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].ProtectionKey,
                   PTE->Entries[Index.PTEIndex].ExecuteDisable ? "1" : "0",
                   PTE->Entries[Index.PTEIndex].GetAddress() << 12);
         }
     }
 #endif
 }
References A, D, debug, CrashHandler::EHPrint(), Entries, G(), PageFaultDescriptions, Present, raw, CPU::x64::CR3::raw, CPU::x64::PageFaultErrorCode::raw, CPU::x64::readcr2(), CPU::x64::readcr3(), RW, and Tasking::User.
Referenced by CrashHandler::DisplayDetailsScreen().
SecurityExceptionHandler()
void SecurityExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 296 of file CrashDetails.cpp.
 {
     fixme("Security exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
SegmentNotPresentExceptionHandler()
void SegmentNotPresentExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 85 of file CrashDetails.cpp.
 {
     fixme("Segment not present exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
SIMDFloatingPointExceptionHandler()
void SIMDFloatingPointExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 286 of file CrashDetails.cpp.
 {
     fixme("SIMD floating point exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
StackFaultExceptionHandler()
void StackFaultExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 90 of file CrashDetails.cpp.
 {
     CPU::x64::SelectorErrorCode SelCode = {.raw = Frame->ErrorCode};
     CrashHandler::EHPrint("\eDD2920System crashed!\n");
     CrashHandler::EHPrint("More info about the exception:\n");
 #if defined(__amd64__)
     CrashHandler::EHPrint("Stack segment fault at address %#lx\n", Frame->rip);
 #elif defined(__i386__)
     CrashHandler::EHPrint("Stack segment fault at address %#lx\n", Frame->eip);
 #elif defined(__aarch64__)
 #endif
     CrashHandler::EHPrint("External: %d\n", SelCode.External);
     CrashHandler::EHPrint("Table: %d\n", SelCode.Table);
     CrashHandler::EHPrint("Index: %#x\n", SelCode.Idx);
     CrashHandler::EHPrint("Error code: %#lx\n", Frame->ErrorCode);
 }
References CrashHandler::EHPrint(), and CPU::x64::SelectorErrorCode::raw.
Referenced by CrashHandler::DisplayDetailsScreen().
UnknownExceptionHandler()
void UnknownExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 301 of file CrashDetails.cpp.
 {
     fixme("Unknown exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
UserModeExceptionHandler()
void UserModeExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 28 of file UserHandler.cpp.
 {
     CriticalSection cs;
     debug("Interrupts? %s.", cs.IsInterruptsEnabled() ? "Yes" : "No");
     fixme("Handling user mode exception");
     TaskManager->GetCurrentThread()->Status = Tasking::TaskStatus::Stopped;
     CPUData *CurCPU = GetCurrentCPU();
     {
         CPU::x64::CR0 cr0 = CPU::x64::readcr0();
         CPU::x64::CR2 cr2 = CPU::x64::readcr2();
         CPU::x64::CR3 cr3 = CPU::x64::readcr3();
         CPU::x64::CR4 cr4 = CPU::x64::readcr4();
         CPU::x64::CR8 cr8 = CPU::x64::readcr8();
         CPU::x64::EFER efer;
         efer.raw = CPU::x64::rdmsr(CPU::x64::MSR_EFER);
         error("Technical Informations on CPU %lld:", CurCPU->ID);
         uintptr_t ds;
 #if defined(__amd64__)
         asmv("mov %%ds, %0"
              : "=r"(ds));
 #elif defined(__i386__)
         asmv("mov %%ds, %0"
              : "=r"(ds));
 #elif defined(__aarch64__)
 #endif
         error("FS=%#llx GS=%#llx SS=%#llx CS=%#llx DS=%#llx",
               CPU::x64::rdmsr(CPU::x64::MSR_FS_BASE), CPU::x64::rdmsr(CPU::x64::MSR_GS_BASE),
               Frame->ss, Frame->cs, ds);
 #if defined(__amd64__)
         error("R8=%#llx R9=%#llx R10=%#llx R11=%#llx", Frame->r8, Frame->r9, Frame->r10, Frame->r11);
         error("R12=%#llx R13=%#llx R14=%#llx R15=%#llx", Frame->r12, Frame->r13, Frame->r14, Frame->r15);
         error("RAX=%#llx RBX=%#llx RCX=%#llx RDX=%#llx", Frame->rax, Frame->rbx, Frame->rcx, Frame->rdx);
         error("RSI=%#llx RDI=%#llx RBP=%#llx RSP=%#llx", Frame->rsi, Frame->rdi, Frame->rbp, Frame->rsp);
         error("RIP=%#llx RFL=%#llx INT=%#llx ERR=%#llx EFER=%#llx", Frame->rip, Frame->rflags.raw, Frame->InterruptNumber, Frame->ErrorCode, efer.raw);
 #elif defined(__i386__)
         error("EAX=%#llx EBX=%#llx ECX=%#llx EDX=%#llx", Frame->eax, Frame->ebx, Frame->ecx, Frame->edx);
         error("ESI=%#llx EDI=%#llx EBP=%#llx ESP=%#llx", Frame->esi, Frame->edi, Frame->ebp, Frame->esp);
         error("EIP=%#llx EFL=%#llx INT=%#llx ERR=%#llx EFER=%#llx", Frame->eip, Frame->eflags.raw, Frame->InterruptNumber, Frame->ErrorCode, efer.raw);
 #elif defined(__aarch64__)
 #endif
         error("CR0=%#llx CR2=%#llx CR3=%#llx CR4=%#llx CR8=%#llx", cr0.raw, cr2.raw, cr3.raw, cr4.raw, cr8.raw);
         error("CR0: PE:%s MP:%s EM:%s TS:%s ET:%s NE:%s WP:%s AM:%s NW:%s CD:%s PG:%s R0:%#x R1:%#x R2:%#x",
               cr0.PE ? "True " : "False", cr0.MP ? "True " : "False", cr0.EM ? "True " : "False", cr0.TS ? "True " : "False",
               cr0.ET ? "True " : "False", cr0.NE ? "True " : "False", cr0.WP ? "True " : "False", cr0.AM ? "True " : "False",
               cr0.NW ? "True " : "False", cr0.CD ? "True " : "False", cr0.PG ? "True " : "False",
               cr0.Reserved0, cr0.Reserved1, cr0.Reserved2);
         error("CR2: PFLA: %#llx",
               cr2.PFLA);
         error("CR3: PWT:%s PCD:%s PDBR:%#llx",
               cr3.PWT ? "True " : "False", cr3.PCD ? "True " : "False", cr3.PDBR);
         error("CR4: VME:%s PVI:%s TSD:%s DE:%s PSE:%s PAE:%s MCE:%s PGE:%s PCE:%s UMIP:%s OSFXSR:%s OSXMMEXCPT:%s    LA57:%s    VMXE:%s    SMXE:%s   PCIDE:%s OSXSAVE:%s    SMEP:%s    SMAP:%s PKE:%s R0:%#x R1:%#x R2:%#x",
               cr4.VME ? "True " : "False", cr4.PVI ? "True " : "False", cr4.TSD ? "True " : "False", cr4.DE ? "True " : "False",
               cr4.PSE ? "True " : "False", cr4.PAE ? "True " : "False", cr4.MCE ? "True " : "False", cr4.PGE ? "True " : "False",
               cr4.PCE ? "True " : "False", cr4.UMIP ? "True " : "False", cr4.OSFXSR ? "True " : "False", cr4.OSXMMEXCPT ? "True " : "False",
               cr4.LA57 ? "True " : "False", cr4.VMXE ? "True " : "False", cr4.SMXE ? "True " : "False", cr4.PCIDE ? "True " : "False",
               cr4.OSXSAVE ? "True " : "False", cr4.SMEP ? "True " : "False", cr4.SMAP ? "True " : "False", cr4.PKE ? "True " : "False",
               cr4.Reserved0, cr4.Reserved1, cr4.Reserved2);
         error("CR8: TPL:%d", cr8.TPL);
 #if defined(__amd64__)
         error("RFL: CF:%s PF:%s AF:%s ZF:%s SF:%s TF:%s IF:%s DF:%s OF:%s IOPL:%s NT:%s RF:%s VM:%s AC:%s VIF:%s VIP:%s ID:%s AlwaysOne:%d R0:%#x R1:%#x R2:%#x R3:%#x",
               Frame->rflags.CF ? "True " : "False", Frame->rflags.PF ? "True " : "False", Frame->rflags.AF ? "True " : "False", Frame->rflags.ZF ? "True " : "False",
               Frame->rflags.SF ? "True " : "False", Frame->rflags.TF ? "True " : "False", Frame->rflags.IF ? "True " : "False", Frame->rflags.DF ? "True " : "False",
               Frame->rflags.OF ? "True " : "False", Frame->rflags.IOPL ? "True " : "False", Frame->rflags.NT ? "True " : "False", Frame->rflags.RF ? "True " : "False",
               Frame->rflags.VM ? "True " : "False", Frame->rflags.AC ? "True " : "False", Frame->rflags.VIF ? "True " : "False", Frame->rflags.VIP ? "True " : "False",
               Frame->rflags.ID ? "True " : "False", Frame->rflags.AlwaysOne,
               Frame->rflags.Reserved0, Frame->rflags.Reserved1, Frame->rflags.Reserved2, Frame->rflags.Reserved3);
 #elif defined(__i386__)
         error("EFL: CF:%s PF:%s AF:%s ZF:%s SF:%s TF:%s IF:%s DF:%s OF:%s IOPL:%s NT:%s RF:%s VM:%s AC:%s VIF:%s VIP:%s ID:%s AlwaysOne:%d R0:%#x R1:%#x R2:%#x",
               Frame->eflags.CF ? "True " : "False", Frame->eflags.PF ? "True " : "False", Frame->eflags.AF ? "True " : "False", Frame->eflags.ZF ? "True " : "False",
               Frame->eflags.SF ? "True " : "False", Frame->eflags.TF ? "True " : "False", Frame->eflags.IF ? "True " : "False", Frame->eflags.DF ? "True " : "False",
               Frame->eflags.OF ? "True " : "False", Frame->eflags.IOPL ? "True " : "False", Frame->eflags.NT ? "True " : "False", Frame->eflags.RF ? "True " : "False",
               Frame->eflags.VM ? "True " : "False", Frame->eflags.AC ? "True " : "False", Frame->eflags.VIF ? "True " : "False", Frame->eflags.VIP ? "True " : "False",
               Frame->eflags.ID ? "True " : "False", Frame->eflags.AlwaysOne,
               Frame->eflags.Reserved0, Frame->eflags.Reserved1, Frame->eflags.Reserved2);
 #elif defined(__aarch64__)
 #endif
         error("EFER: SCE:%s LME:%s LMA:%s NXE:%s SVME:%s LMSLE:%s FFXSR:%s TCE:%s R0:%#x R1:%#x R2:%#x",
               efer.SCE ? "True " : "False", efer.LME ? "True " : "False", efer.LMA ? "True " : "False", efer.NXE ? "True " : "False",
               efer.SVME ? "True " : "False", efer.LMSLE ? "True " : "False", efer.FFXSR ? "True " : "False", efer.TCE ? "True " : "False",
               efer.Reserved0, efer.Reserved1, efer.Reserved2);
     }
     switch (Frame->InterruptNumber)
     {
     case CPU::x64::DivideByZero:
     {
         break;
     }
     case CPU::x64::Debug:
     {
         break;
     }
     case CPU::x64::NonMaskableInterrupt:
     {
         break;
     }
     case CPU::x64::Breakpoint:
     {
         break;
     }
     case CPU::x64::Overflow:
     {
         break;
     }
     case CPU::x64::BoundRange:
     {
         break;
     }
     case CPU::x64::InvalidOpcode:
     {
         break;
     }
     case CPU::x64::DeviceNotAvailable:
     {
         break;
     }
     case CPU::x64::DoubleFault:
     {
         break;
     }
     case CPU::x64::CoprocessorSegmentOverrun:
     {
         break;
     }
     case CPU::x64::InvalidTSS:
     {
         break;
     }
     case CPU::x64::SegmentNotPresent:
     {
         break;
     }
     case CPU::x64::StackSegmentFault:
     {
         break;
     }
     case CPU::x64::GeneralProtectionFault:
     {
         break;
     }
     case CPU::x64::PageFault:
     {
         uintptr_t CheckPageFaultAddress = 0;
         CPU::x64::PageFaultErrorCode params = {.raw = (uint32_t)Frame->ErrorCode};
 #if defined(__amd64__)
         CheckPageFaultAddress = CPU::x64::readcr2().PFLA;
         if (CheckPageFaultAddress == 0)
             CheckPageFaultAddress = Frame->rip;
         error("An exception occurred at %#lx by %#lx", CPU::x64::readcr2().PFLA, Frame->rip);
 #elif defined(__i386__)
         error("An exception occurred at %#lx by %#lx", CPU::x64::readcr2().PFLA, Frame->eip);
 #elif defined(__aarch64__)
 #endif
         error("Page: %s", params.P ? "Present" : "Not Present");
         error("Write Operation: %s", params.W ? "Read-Only" : "Read-Write");
         error("Processor Mode: %s", params.U ? "User-Mode" : "Kernel-Mode");
         error("CPU Reserved Bits: %s", params.R ? "Reserved" : "Unreserved");
         error("Caused By An Instruction Fetch: %s", params.I ? "Yes" : "No");
         error("Caused By A Protection-Key Violation: %s", params.PK ? "Yes" : "No");
         error("Caused By A Shadow Stack Access: %s", params.SS ? "Yes" : "No");
         error("Caused By An SGX Violation: %s", params.SGX ? "Yes" : "No");
         if (Frame->ErrorCode & 0x00000008)
             error("One or more page directory entries contain reserved bits which are set to 1.");
         else
             error(PageFaultDescriptions[Frame->ErrorCode & 0b111]);
 #ifdef DEBUG
         if (CurCPU)
         {
             Memory::Virtual vma = Memory::Virtual(CurCPU->CurrentProcess->PageTable);
             bool PageAvailable = vma.Check((void *)CheckPageFaultAddress);
             debug("Page available (Check(...)): %s. %s",
                   PageAvailable ? "Yes" : "No",
                   (params.P && !PageAvailable) ? "CR2 == Present; Check() != Present??????" : "CR2 confirms Check() result.");
             if (PageAvailable)
             {
                 bool Present = vma.Check((void *)CheckPageFaultAddress);
                 bool ReadWrite = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::RW);
                 bool User = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::US);
                 bool WriteThrough = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::PWT);
                 bool CacheDisabled = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::PCD);
                 bool Accessed = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::A);
                 bool Dirty = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::D);
                 bool Global = vma.Check((void *)CheckPageFaultAddress, Memory::PTFlag::G);
                 /* ... */
                 debug("Page available: %s", Present ? "Yes" : "No");
                 debug("Page read/write: %s", ReadWrite ? "Yes" : "No");
                 debug("Page user/kernel: %s", User ? "User" : "Kernel");
                 debug("Page write-through: %s", WriteThrough ? "Yes" : "No");
                 debug("Page cache disabled: %s", CacheDisabled ? "Yes" : "No");
                 debug("Page accessed: %s", Accessed ? "Yes" : "No");
                 debug("Page dirty: %s", Dirty ? "Yes" : "No");
                 debug("Page global: %s", Global ? "Yes" : "No");
                 if (Present)
                 {
                     uintptr_t CheckPageFaultLinearAddress = (uintptr_t)CheckPageFaultAddress;
                     CheckPageFaultLinearAddress &= 0xFFFFFFFFFFFFF000;
                     debug("%#lx -> %#lx", CheckPageFaultAddress, CheckPageFaultLinearAddress);
                     Memory::Virtual::PageMapIndexer Index = Memory::Virtual::PageMapIndexer((uintptr_t)CheckPageFaultLinearAddress);
                     debug("Index for %#lx is PML:%d PDPTE:%d PDE:%d PTE:%d",
                           CheckPageFaultLinearAddress,
                           Index.PMLIndex,
                           Index.PDPTEIndex,
                           Index.PDEIndex,
                           Index.PTEIndex);
                     Memory::PageMapLevel4 PML4 = CurCPU->CurrentProcess->PageTable->Entries[Index.PMLIndex];
                     Memory::PageDirectoryPointerTableEntryPtr *PDPTE = (Memory::PageDirectoryPointerTableEntryPtr *)((uintptr_t)PML4.GetAddress() << 12);
                     Memory::PageDirectoryEntryPtr *PDE = (Memory::PageDirectoryEntryPtr *)((uintptr_t)PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
                     Memory::PageTableEntryPtr *PTE = (Memory::PageTableEntryPtr *)((uintptr_t)PDE->Entries[Index.PDEIndex].GetAddress() << 12);
                     debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                           Index.PMLIndex, 0, 0, 0,
                           PML4.Present ? "1" : "0",
                           PML4.ReadWrite ? "1" : "0",
                           PML4.UserSupervisor ? "1" : "0",
                           PML4.WriteThrough ? "1" : "0",
                           PML4.CacheDisable ? "1" : "0",
                           PML4.Accessed ? "1" : "0",
                           PML4.ExecuteDisable ? "1" : "0",
                           PML4.GetAddress() << 12);
                     debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                           Index.PMLIndex, Index.PDPTEIndex, 0, 0,
                           PDPTE->Entries[Index.PDPTEIndex].Present ? "1" : "0",
                           PDPTE->Entries[Index.PDPTEIndex].ReadWrite ? "1" : "0",
                           PDPTE->Entries[Index.PDPTEIndex].UserSupervisor ? "1" : "0",
                           PDPTE->Entries[Index.PDPTEIndex].WriteThrough ? "1" : "0",
                           PDPTE->Entries[Index.PDPTEIndex].CacheDisable ? "1" : "0",
                           PDPTE->Entries[Index.PDPTEIndex].Accessed ? "1" : "0",
                           PDPTE->Entries[Index.PDPTEIndex].ExecuteDisable ? "1" : "0",
                           PDPTE->Entries[Index.PDPTEIndex].GetAddress() << 12);
                     debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s NX:%s Address:%#lx",
                           Index.PMLIndex, Index.PDPTEIndex, Index.PDEIndex, 0,
                           PDE->Entries[Index.PDEIndex].Present ? "1" : "0",
                           PDE->Entries[Index.PDEIndex].ReadWrite ? "1" : "0",
                           PDE->Entries[Index.PDEIndex].UserSupervisor ? "1" : "0",
                           PDE->Entries[Index.PDEIndex].WriteThrough ? "1" : "0",
                           PDE->Entries[Index.PDEIndex].CacheDisable ? "1" : "0",
                           PDE->Entries[Index.PDEIndex].Accessed ? "1" : "0",
                           PDE->Entries[Index.PDEIndex].ExecuteDisable ? "1" : "0",
                           PDE->Entries[Index.PDEIndex].GetAddress() << 12);
                     debug("# %03d-%03d-%03d-%03d: P:%s RW:%s US:%s PWT:%s PCB:%s A:%s D:%s PAT:%s G:%s PK:%d NX:%s Address:%#lx",
                           Index.PMLIndex, Index.PDPTEIndex, Index.PDEIndex, Index.PTEIndex,
                           PTE->Entries[Index.PTEIndex].Present ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].ReadWrite ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].UserSupervisor ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].WriteThrough ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].CacheDisable ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].Accessed ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].Dirty ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].PageAttributeTable ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].Global ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].ProtectionKey,
                           PTE->Entries[Index.PTEIndex].ExecuteDisable ? "1" : "0",
                           PTE->Entries[Index.PTEIndex].GetAddress() << 12);
                 }
             }
         }
 #endif
         if (CurCPU)
             if (CurCPU->CurrentThread->Stack->Expand(CPU::x64::readcr2().raw))
             {
                 debug("Stack expanded");
                 TaskManager->GetCurrentThread()->Status = Tasking::TaskStatus::Ready;
                 return;
             }
         break;
     }
     case CPU::x64::x87FloatingPoint:
     {
         break;
     }
     case CPU::x64::AlignmentCheck:
     {
         break;
     }
     case CPU::x64::MachineCheck:
     {
         break;
     }
     case CPU::x64::SIMDFloatingPoint:
     {
         break;
     }
     case CPU::x64::Virtualization:
     {
         break;
     }
     case CPU::x64::Security:
     {
         break;
     }
     default:
     {
         break;
     }
     }
     TaskManager->GetCurrentThread()->Status = Tasking::TaskStatus::Terminated;
     __sync_synchronize();
     error("End of report.");
     CPU::Interrupts(CPU::Enable);
     debug("Interrupts enabled back.");
     return;
 }
References A, CPU::x64::AlignmentCheck, asmv, CPU::x64::BoundRange, CPU::x64::Breakpoint, CPU::x64::CoprocessorSegmentOverrun, CPUData::CurrentProcess, CPUData::CurrentThread, D, CPU::x64::Debug, debug, CPU::x64::DeviceNotAvailable, CPU::x64::DivideByZero, CPU::x64::DoubleFault, CPU::Enable, error, fixme, G(), CPU::x64::GeneralProtectionFault, GetCurrentCPU(), Tasking::Task::GetCurrentThread(), CPUData::ID, CPU::Interrupts(), CPU::x64::InvalidOpcode, CPU::x64::InvalidTSS, CPU::x64::MachineCheck, CPU::x64::MSR_EFER, CPU::x64::MSR_FS_BASE, CPU::x64::MSR_GS_BASE, CPU::x64::NonMaskableInterrupt, CPU::x64::Overflow, CPU::x64::PageFault, PageFaultDescriptions, Tasking::PCB::PageTable, Present, CPU::x64::CR0::raw, CPU::x64::CR2::raw, CPU::x64::CR3::raw, CPU::x64::CR4::raw, CPU::x64::CR8::raw, CPU::x64::EFER::raw, CPU::x64::PageFaultErrorCode::raw, CPU::x64::rdmsr(), CPU::x64::readcr0(), CPU::x64::readcr2(), CPU::x64::readcr3(), CPU::x64::readcr4(), CPU::x64::readcr8(), Tasking::Ready, RW, CPU::x64::Security, CPU::x64::SegmentNotPresent, CPU::x64::SIMDFloatingPoint, Tasking::TCB::Stack, CPU::x64::StackSegmentFault, Tasking::TCB::Status, Tasking::Stopped, TaskManager, Tasking::Terminated, Tasking::User, CPU::x64::Virtualization, and CPU::x64::x87FloatingPoint.
Referenced by CrashHandler::Handle().
VirtualizationExceptionHandler()
void VirtualizationExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 291 of file CrashDetails.cpp.
 {
     fixme("Virtualization exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().
x87FloatingPointExceptionHandler()
void x87FloatingPointExceptionHandler (CHArchTrapFrame * Frame)
Definition at line 271 of file CrashDetails.cpp.
 {
     fixme("x87 floating point exception");
     UNUSED(Frame);
 }
References fixme, and UNUSED.
Referenced by CrashHandler::DisplayDetailsScreen().