Fennix: Userspace/apps/base/bash/lib/intl/plural.c File Reference
plural.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include "plural-exp.h"
Data Structures
union YYSTYPE
union yyalloc
Macros
#define YYBISON 1
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 1
#define YYLSP_NEEDED 0
#define yyparse __gettextparse
#define yylex __gettextlex
#define yyerror __gettexterror
#define yylval __gettextlval
#define yychar __gettextchar
#define yydebug __gettextdebug
#define yynerrs __gettextnerrs
#define YYTOKENTYPE
#define EQUOP2 258
#define CMPOP2 259
#define ADDOP2 260
#define MULOP2 261
#define NUMBER 262
#define __gettextparse PLURAL_PARSE
#define YYLEX_PARAM &((struct parse_args *) arg)->cp
#define YYPARSE_PARAM arg
#define YYDEBUG 0
#define YYERROR_VERBOSE 0
#define yystype YYSTYPE /* obsolescent; will be withdrawn */
#define YYSTYPE_IS_DECLARED 1
#define YYSTYPE_IS_TRIVIAL 1
#define YYFREE free
#define YYMALLOC malloc
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY(To, From, Count)
#define YYSTACK_RELOCATE(Stack)
#define YYFINAL 9
#define YYLAST 54
#define YYNTOKENS 16
#define YYNNTS 3
#define YYNRULES 13
#define YYNSTATES 27
#define YYUNDEFTOK 2
#define YYMAXUTOK 262
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -10
#define YYTABLE_NINF -1
#define YYSIZE_T unsigned int
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYFAIL goto yyerrlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYRHSLOC(Rhs, K) ((Rhs)[K])
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YYLEX yylex (&yylval, YYLEX_PARAM)
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK (yyvsp--, yyssp--)
Typedefs
typedef union YYSTYPE YYSTYPE
typedef short int yysigned_char
Enumerations
enum yytokentype {
EQUOP2 = 258 , CMPOP2 = 259 , ADDOP2 = 260 , MULOP2 = 261 ,
NUMBER = 262 , YYEMPTY = -2 , YYEOF = 0 , YYerror = 256 ,
YYUNDEF = 257 , IF = 258 , THEN = 259 , ELSE = 260 ,
ELIF = 261 , FI = 262 , CASE = 263 , ESAC = 264 ,
FOR = 265 , SELECT = 266 , WHILE = 267 , UNTIL = 268 ,
DO = 269 , DONE = 270 , FUNCTION = 271 , COPROC = 272 ,
COND_START = 273 , COND_END = 274 , COND_ERROR = 275 , IN = 276 ,
BANG = 277 , TIME = 278 , TIMEOPT = 279 , TIMEIGN = 280 ,
WORD = 281 , ASSIGNMENT_WORD = 282 , REDIR_WORD = 283 , NUMBER = 284 ,
ARITH_CMD = 285 , ARITH_FOR_EXPRS = 286 , COND_CMD = 287 , AND_AND = 288 ,
OR_OR = 289 , GREATER_GREATER = 290 , LESS_LESS = 291 , LESS_AND = 292 ,
LESS_LESS_LESS = 293 , GREATER_AND = 294 , SEMI_SEMI = 295 , SEMI_AND = 296 ,
SEMI_SEMI_AND = 297 , LESS_LESS_MINUS = 298 , AND_GREATER = 299 , AND_GREATER_GREATER = 300 ,
LESS_GREATER = 301 , GREATER_BAR = 302 , BAR_AND = 303 , DOLPAREN = 304 ,
yacc_EOF = 305 , YYEMPTY = -2 , YYEOF = 0 , YYerror = 256 ,
YYUNDEF = 257 , IF = 258 , THEN = 259 , ELSE = 260 ,
ELIF = 261 , FI = 262 , CASE = 263 , ESAC = 264 ,
FOR = 265 , SELECT = 266 , WHILE = 267 , UNTIL = 268 ,
DO = 269 , DONE = 270 , FUNCTION = 271 , COPROC = 272 ,
COND_START = 273 , COND_END = 274 , COND_ERROR = 275 , IN = 276 ,
BANG = 277 , TIME = 278 , TIMEOPT = 279 , TIMEIGN = 280 ,
WORD = 281 , ASSIGNMENT_WORD = 282 , REDIR_WORD = 283 , NUMBER = 284 ,
ARITH_CMD = 285 , ARITH_FOR_EXPRS = 286 , COND_CMD = 287 , AND_AND = 288 ,
OR_OR = 289 , GREATER_GREATER = 290 , LESS_LESS = 291 , LESS_AND = 292 ,
LESS_LESS_LESS = 293 , GREATER_AND = 294 , SEMI_SEMI = 295 , SEMI_AND = 296 ,
SEMI_SEMI_AND = 297 , LESS_LESS_MINUS = 298 , AND_GREATER = 299 , AND_GREATER_GREATER = 300 ,
LESS_GREATER = 301 , GREATER_BAR = 302 , BAR_AND = 303 , DOLPAREN = 304 ,
yacc_EOF = 305
}
Functions
static struct expression *new_exp PARAMS ((int nargs, enum operator op, struct expression *const *args))
static struct expression *new_exp_0 PARAMS ((enum operator op))
static struct expression *new_exp_1 PARAMS ((enum operator op, struct expression *right))
static struct expression *new_exp_2 PARAMS ((enum operator op, struct expression *left, struct expression *right))
static struct expression *new_exp_3 PARAMS ((enum operator op, struct expression *bexp, struct expression *tbranch, struct expression *fbranch))
static int yylex PARAMS ((YYSTYPE *lval, const char **pexp))
static void yyerror PARAMS ((const char *str))
static struct expression * new_exp (int nargs, enum operator op, struct expression *const *args)
static struct expression * new_exp_0 (enum operator op)
static struct expression * new_exp_1 (enum operator op, struct expression *right)
static struct expression * new_exp_2 (enum operator op, struct expression *left, struct expression *right)
static struct expression * new_exp_3 (enum operator op, struct expression *bexp, struct expression *tbranch, struct expression *fbranch)
static void yydestruct (char *yymsg, int yytype, YYSTYPE *yyvaluep) const
int yyparse (void *YYPARSE_PARAM)
switch (exp->nargs)
free (exp)
static int yylex (YYSTYPE *lval, const char **pexp)
static void yyerror (char *str) const
Variables
static const unsigned char yytranslate []
static const unsigned char yyr1 []
static const unsigned char yyr2 []
static const unsigned char yydefact []
static const yysigned_char yydefgoto []
static const yysigned_char yypact []
static const yysigned_char yypgoto []
static const unsigned char yytable []
static const yysigned_char yycheck []
static const unsigned char yystos []
void internal_function struct expression * exp
Data Structure Documentation
YYSTYPE
union YYSTYPE
Definition at line 146 of file plural.c.
Data Fields
COMMAND * command
ELEMENT element
struct expression * exp
unsigned long int num
int number
enum operator op
PATTERN_LIST * pattern
REDIRECT * redirect
WORD_DESC * word
WORD_LIST * word_list
yyalloc
union yyalloc
Definition at line 304 of file plural.c.
Data Fields
short int yyss
yy_state_t yyss_alloc
YYSTYPE yyvs
YYSTYPE yyvs_alloc
Macro Definition Documentation
__gettextparse
#define __gettextparse PLURAL_PARSE
Definition at line 124 of file plural.c.
ADDOP2
#define ADDOP2 260
Definition at line 74 of file plural.c.
CMPOP2
#define CMPOP2 259
Definition at line 73 of file plural.c.
EQUOP2
#define EQUOP2 258
Definition at line 72 of file plural.c.
MULOP2
#define MULOP2 261
Definition at line 75 of file plural.c.
NUMBER
#define NUMBER 262
Definition at line 76 of file plural.c.
YY_LOCATION_PRINT
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
Definition at line 635 of file plural.c.
YY_REDUCE_PRINT
#define YY_REDUCE_PRINT (Rule)
Definition at line 737 of file plural.c.
YY_STACK_PRINT
#define YY_STACK_PRINT (Bottom, Top)
Definition at line 736 of file plural.c.
YY_SYMBOL_PRINT
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Definition at line 735 of file plural.c.
YYABORT
#define YYABORT goto yyabortlab
Definition at line 564 of file plural.c.
YYACCEPT
#define YYACCEPT goto yyacceptlab
Definition at line 563 of file plural.c.
YYBACKUP
#define YYBACKUP (Token, Value)
Value:
do                                \
  if (yychar == YYEMPTY && yylen == 1)              \
    {                               \
      yychar = (Token);                     \
      yylval = (Value);                     \
      yytoken = YYTRANSLATE (yychar);               \
      YYPOPSTACK;                       \
      goto yybackup;                        \
    }                               \
  else                              \
    {                               \
      yyerror ("syntax error: cannot back up");\
      YYERROR;                          \
    }                               \
while (0)
Definition at line 576 of file plural.c.
YYBISON
#define YYBISON 1
Definition at line 38 of file plural.c.
yychar
#define yychar __gettextchar
Definition at line 54 of file plural.c.
yyclearin
#define yyclearin (yychar = YYEMPTY)
Definition at line 559 of file plural.c.
YYCOPY
#define YYCOPY (To, From, Count)
Value:
      do                    \
    {                   \
      register YYSIZE_T yyi;        \
      for (yyi = 0; yyi < (Count); yyi++)   \
        (To)[yyi] = (From)[yyi];        \
    }                   \
      while (0)
Definition at line 326 of file plural.c.
yydebug
#define yydebug __gettextdebug
Definition at line 55 of file plural.c.
YYDEBUG
#define YYDEBUG 0
Definition at line 133 of file plural.c.
YYDPRINTF
#define YYDPRINTF (Args)
Definition at line 734 of file plural.c.
YYEMPTY
#define YYEMPTY (-2)
Definition at line 560 of file plural.c.
YYEOF
#define YYEOF 0
Definition at line 561 of file plural.c.
YYERRCODE
#define YYERRCODE 256
Definition at line 595 of file plural.c.
yyerrok
#define yyerrok (yyerrstatus = 0)
Definition at line 558 of file plural.c.
yyerror
#define yyerror __gettexterror
Definition at line 52 of file plural.c.
YYERROR
#define YYERROR goto yyerrorlab
Definition at line 565 of file plural.c.
YYERROR_VERBOSE
#define YYERROR_VERBOSE 0
Definition at line 141 of file plural.c.
YYFAIL
#define YYFAIL goto yyerrlab
Definition at line 572 of file plural.c.
YYFINAL
#define YYFINAL 9
Definition at line 362 of file plural.c.
YYFREE
#define YYFREE free
Definition at line 267 of file plural.c.
YYINITDEPTH
#define YYINITDEPTH 200
Definition at line 743 of file plural.c.
YYLAST
#define YYLAST 54
Definition at line 364 of file plural.c.
yylex
#define yylex __gettextlex
Definition at line 51 of file plural.c.
YYLEX
#define YYLEX yylex (&yylval, YYLEX_PARAM)
Definition at line 643 of file plural.c.
YYLEX_PARAM
#define YYLEX_PARAM &((struct parse_args *) arg)->cp
Definition at line 127 of file plural.c.
YYLLOC_DEFAULT
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
    do                                    \
      if (N)                                \
    {                               \
      (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;    \
      (Current).first_column = YYRHSLOC (Rhs, 1).first_column;  \
      (Current).last_line    = YYRHSLOC (Rhs, N).last_line;     \
      (Current).last_column  = YYRHSLOC (Rhs, N).last_column;   \
    }                               \
      else                              \
    {                               \
      (Current).first_line   = (Current).last_line   =      \
        YYRHSLOC (Rhs, 0).last_line;                \
      (Current).first_column = (Current).last_column =      \
        YYRHSLOC (Rhs, 0).last_column;              \
    }                               \
    while (0)
Definition at line 604 of file plural.c.
YYLSP_NEEDED
#define YYLSP_NEEDED 0
Definition at line 47 of file plural.c.
yylval
YYSTYPE yylval __gettextlval
Definition at line 53 of file plural.c.
Referenced by yyparse().
YYMALLOC
#define YYMALLOC malloc
Definition at line 270 of file plural.c.
YYMAXDEPTH
#define YYMAXDEPTH 10000
Definition at line 754 of file plural.c.
YYMAXUTOK
#define YYMAXUTOK 262
Definition at line 377 of file plural.c.
yynerrs
#define yynerrs __gettextnerrs
Definition at line 56 of file plural.c.
YYNNTS
#define YYNNTS 3
Definition at line 369 of file plural.c.
YYNRULES
#define YYNRULES 13
Definition at line 371 of file plural.c.
YYNSTATES
#define YYNSTATES 27
Definition at line 373 of file plural.c.
YYNTOKENS
#define YYNTOKENS 16
Definition at line 367 of file plural.c.
YYPACT_NINF
#define YYPACT_NINF -10
Definition at line 494 of file plural.c.
yyparse
int yyparse (void) __gettextparse
Definition at line 50 of file plural.c.
Referenced by parse_command().
YYPARSE_PARAM
#define YYPARSE_PARAM arg
Definition at line 128 of file plural.c.
YYPOPSTACK
#define YYPOPSTACK (yyvsp--, yyssp--)
YYPURE
#define YYPURE 1
Definition at line 44 of file plural.c.
YYRECOVERING
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 574 of file plural.c.
YYRHSLOC
#define YYRHSLOC (Rhs, K) ((Rhs)[K])
Definition at line 602 of file plural.c.
YYSIZE_T
#define YYSIZE_T unsigned int
Definition at line 555 of file plural.c.
YYSKELETON_NAME
#define YYSKELETON_NAME "yacc.c"
Definition at line 41 of file plural.c.
YYSTACK_ALLOC
#define YYSTACK_ALLOC YYMALLOC
Definition at line 293 of file plural.c.
YYSTACK_BYTES
#define YYSTACK_BYTES (N)
Value:
     ((N) * (sizeof (short int) + sizeof (YYSTYPE))         \
      + YYSTACK_GAP_MAXIMUM)
Definition at line 315 of file plural.c.
YYSTACK_FREE
#define YYSTACK_FREE YYFREE
Definition at line 294 of file plural.c.
YYSTACK_GAP_MAXIMUM
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 311 of file plural.c.
YYSTACK_RELOCATE
#define YYSTACK_RELOCATE (Stack)
Value:
    do                                  \
      {                                 \
    YYSIZE_T yynewbytes;                        \
    YYCOPY (&yyptr->Stack, Stack, yysize);              \
    Stack = &yyptr->Stack;                      \
    yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
    yyptr += yynewbytes / sizeof (*yyptr);              \
      }                                 \
    while (0)
Definition at line 342 of file plural.c.
yystype
#define yystype YYSTYPE /* obsolescent; will be withdrawn */
Definition at line 153 of file plural.c.
YYSTYPE_IS_DECLARED
#define YYSTYPE_IS_DECLARED 1
Definition at line 154 of file plural.c.
YYSTYPE_IS_TRIVIAL
#define YYSTYPE_IS_TRIVIAL 1
Definition at line 155 of file plural.c.
YYTABLE_NINF
#define YYTABLE_NINF -1
Definition at line 512 of file plural.c.
YYTERROR
#define YYTERROR 1
Definition at line 594 of file plural.c.
YYTOKENTYPE
#define YYTOKENTYPE
Definition at line 61 of file plural.c.
YYTRANSLATE
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 379 of file plural.c.
YYUNDEFTOK
#define YYUNDEFTOK 2
Definition at line 376 of file plural.c.
Typedef Documentation
yysigned_char
typedef short int yysigned_char
Definition at line 358 of file plural.c.
YYSTYPE
typedef union YYSTYPE YYSTYPE
Enumeration Type Documentation
yytokentype
enum yytokentype
Enumerator
EQUOP2
CMPOP2
ADDOP2
MULOP2
NUMBER
YYEMPTY
YYEOF
YYerror
YYUNDEF
IF
THEN
ELSE
ELIF
FI
CASE
ESAC
FOR
SELECT
WHILE
UNTIL
DO
DONE
FUNCTION
COPROC
COND_START
COND_END
COND_ERROR
IN
BANG
TIME
TIMEOPT
TIMEIGN
WORD
ASSIGNMENT_WORD
REDIR_WORD
NUMBER
ARITH_CMD
ARITH_FOR_EXPRS
COND_CMD
AND_AND
OR_OR
GREATER_GREATER
LESS_LESS
LESS_AND
LESS_LESS_LESS
GREATER_AND
SEMI_SEMI
SEMI_AND
SEMI_SEMI_AND
LESS_LESS_MINUS
AND_GREATER
AND_GREATER_GREATER
LESS_GREATER
GREATER_BAR
BAR_AND
DOLPAREN
yacc_EOF
YYEMPTY
YYEOF
YYerror
YYUNDEF
IF
THEN
ELSE
ELIF
FI
CASE
ESAC
FOR
SELECT
WHILE
UNTIL
DO
DONE
FUNCTION
COPROC
COND_START
COND_END
COND_ERROR
IN
BANG
TIME
TIMEOPT
TIMEIGN
WORD
ASSIGNMENT_WORD
REDIR_WORD
NUMBER
ARITH_CMD
ARITH_FOR_EXPRS
COND_CMD
AND_AND
OR_OR
GREATER_GREATER
LESS_LESS
LESS_AND
LESS_LESS_LESS
GREATER_AND
SEMI_SEMI
SEMI_AND
SEMI_SEMI_AND
LESS_LESS_MINUS
AND_GREATER
AND_GREATER_GREATER
LESS_GREATER
GREATER_BAR
BAR_AND
DOLPAREN
yacc_EOF
Definition at line 64 of file plural.c.
                     {
      EQUOP2 = 258,
      CMPOP2 = 259,
      ADDOP2 = 260,
      MULOP2 = 261,
      NUMBER = 262
    };
Function Documentation
free()
free (exp)
new_exp()
static struct expression* new_exp (int nargs, enum operator op, struct expression * const * args) static
Definition at line 182 of file plural.c.
 {
   int i;
   struct expression *newp;
   /* If any of the argument could not be malloc'ed, just return NULL.  */
   for (i = nargs - 1; i >= 0; i--)
     if (args[i] == NULL)
       goto fail;
   /* Allocate a new expression.  */
   newp = (struct expression *) malloc (sizeof (*newp));
   if (newp != NULL)
     {
       newp->nargs = nargs;
       newp->operation = op;
       for (i = nargs - 1; i >= 0; i--)
     newp->val.args[i] = args[i];
       return newp;
     }
  fail:
   for (i = nargs - 1; i >= 0; i--)
     FREE_EXPRESSION (args[i]);
   return NULL;
 }
References FREE_EXPRESSION, i, malloc, expression::nargs, NULL, expression::operation, and expression::val.
Referenced by new_exp_0(), new_exp_1(), new_exp_2(), and new_exp_3().
new_exp_0()
static struct expression* new_exp_0 (enum operator op) inline static
Definition at line 214 of file plural.c.
 {
   return new_exp (0, op, NULL);
 }
References new_exp(), and NULL.
Referenced by yyparse().
new_exp_1()
static struct expression* new_exp_1 (enum operator op, struct expression * right) inline static
Definition at line 221 of file plural.c.
 {
   struct expression *args[1];
   args[0] = right;
   return new_exp (1, op, args);
 }
References new_exp().
Referenced by yyparse().
new_exp_2()
static struct expression* new_exp_2 (enum operator op, struct expression * left, struct expression * right) static
Definition at line 232 of file plural.c.
 {
   struct expression *args[2];
   args[0] = left;
   args[1] = right;
   return new_exp (2, op, args);
 }
References new_exp().
Referenced by yyparse().
new_exp_3()
static struct expression* new_exp_3 (enum operator op, struct expression * bexp, struct expression * tbranch, struct expression * fbranch) inline static
Definition at line 245 of file plural.c.
 {
   struct expression *args[3];
   args[0] = bexp;
   args[1] = tbranch;
   args[2] = fbranch;
   return new_exp (3, op, args);
 }
References new_exp().
Referenced by yyparse().
PARAMS() [1/7]
static void yyerror PARAMS ((const char *str)) static
PARAMS() [2/7]
static struct expression* new_exp_0 PARAMS ((enum operator op)) inline static
PARAMS() [3/7]
static struct expression* new_exp_3 PARAMS ((enum operator op, struct expression *bexp, struct expression *tbranch, struct expression *fbranch)) inline static
PARAMS() [4/7]
static struct expression* new_exp_2 PARAMS ((enum operator op, struct expression *left, struct expression *right)) static
PARAMS() [5/7]
static struct expression* new_exp_1 PARAMS ((enum operator op, struct expression *right)) inline static
PARAMS() [6/7]
static struct expression* new_exp PARAMS ((int nargs, enum operator op, struct expression *const *args)) static
PARAMS() [7/7]
static int yylex PARAMS ((YYSTYPE *lval, const char **pexp)) static
switch()
switch (exp-> nargs)
Definition at line 1510 of file plural.c.
     {
     case 3:
       FREE_EXPRESSION (exp->val.args[2]);
       /* FALLTHROUGH */
     case 2:
       FREE_EXPRESSION (exp->val.args[1]);
       /* FALLTHROUGH */
     case 1:
       FREE_EXPRESSION (exp->val.args[0]);
       /* FALLTHROUGH */
     default:
       break;
     }
References exp, FREE_EXPRESSION, and expression::val.
yydestruct()
static void yydestruct (char * yymsg, int yytype, YYSTYPE * yyvaluep) const static
Definition at line 861 of file plural.c.
 {
   /* Pacify ``unused variable'' warnings.  */
   (void) yyvaluep;
   if (!yymsg)
     yymsg = "Deleting";
   YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);
   switch (yytype)
     {
       default:
         break;
     }
 }
References Driver::void(), and YY_SYMBOL_PRINT.
Referenced by yyparse().
yyerror()
static void yyerror (char * str) const static
Definition at line 1675 of file plural.c.
 {
   /* Do nothing.  We don't print error messages here.  */
 }
yylex()
static int yylex (YYSTYPE * lval, const char ** pexp) static
Definition at line 1530 of file plural.c.
 {
   const char *exp = *pexp;
   int result;
   while (1)
     {
       if (exp[0] == '\0')
     {
       *pexp = exp;
       return YYEOF;
     }
       if (exp[0] != ' ' && exp[0] != '\t')
     break;
       ++exp;
     }
   result = *exp++;
   switch (result)
     {
     case '0': case '1': case '2': case '3': case '4':
     case '5': case '6': case '7': case '8': case '9':
       {
     unsigned long int n = result - '0';
     while (exp[0] >= '0' && exp[0] <= '9')
       {
         n *= 10;
         n += exp[0] - '0';
         ++exp;
       }
     lval->num = n;
     result = NUMBER;
       }
       break;
     case '=':
       if (exp[0] == '=')
     {
       ++exp;
       lval->op = equal;
       result = EQUOP2;
     }
       else
     result = YYERRCODE;
       break;
     case '!':
       if (exp[0] == '=')
     {
       ++exp;
       lval->op = not_equal;
       result = EQUOP2;
     }
       break;
     case '&':
     case '|':
       if (exp[0] == result)
     ++exp;
       else
     result = YYERRCODE;
       break;
     case '<':
       if (exp[0] == '=')
     {
       ++exp;
       lval->op = less_or_equal;
     }
       else
     lval->op = less_than;
       result = CMPOP2;
       break;
     case '>':
       if (exp[0] == '=')
     {
       ++exp;
       lval->op = greater_or_equal;
     }
       else
     lval->op = greater_than;
       result = CMPOP2;
       break;
     case '*':
       lval->op = mult;
       result = MULOP2;
       break;
     case '/':
       lval->op = divide;
       result = MULOP2;
       break;
     case '%':
       lval->op = module;
       result = MULOP2;
       break;
     case '+':
       lval->op = plus;
       result = ADDOP2;
       break;
     case '-':
       lval->op = minus;
       result = ADDOP2;
       break;
     case 'n':
     case '?':
     case ':':
     case '(':
     case ')':
       /* Nothing, just return the character.  */
       break;
     case ';':
     case '\n':
     case '\0':
       /* Be safe and let the user call this function again.  */
       --exp;
       result = YYEOF;
       break;
     default:
       result = YYERRCODE;
 #if YYDEBUG != 0
       --exp;
 #endif
       break;
     }
   *pexp = exp;
   return result;
 }
References ADDOP2, CMPOP2, divide(), EQUOP2, exp, MULOP2, mult, n, YYSTYPE::num, NUMBER, YYSTYPE::op, YYEOF, and YYERRCODE.
yyparse()
int yyparse (void * YYPARSE_PARAM)
Definition at line 912 of file plural.c.
 {
   /* The look-ahead symbol.  */
 int yychar;
 /* The semantic value of the look-ahead symbol.  */
 YYSTYPE yylval;
 /* Number of syntax errors so far.  */
 int yynerrs;
   register int yystate;
   register int yyn;
   int yyresult;
   /* Number of tokens to shift before error messages enabled.  */
   int yyerrstatus;
   /* Look-ahead token as an internal (translated) token number.  */
   int yytoken = 0;
   /* Three stacks and their tools:
      `yyss': related to states,
      `yyvs': related to semantic values,
      `yyls': related to locations.
      Refer to the stacks thru separate pointers, to allow yyoverflow
      to reallocate them elsewhere.  */
   /* The state stack.  */
   short int yyssa[YYINITDEPTH];
   short int *yyss = yyssa;
   register short int *yyssp;
   /* The semantic value stack.  */
   YYSTYPE yyvsa[YYINITDEPTH];
   YYSTYPE *yyvs = yyvsa;
   register YYSTYPE *yyvsp;
 #define YYPOPSTACK   (yyvsp--, yyssp--)
   YYSIZE_T yystacksize = YYINITDEPTH;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
   /* When reducing, the number of symbols on the RHS of the reduced
      rule.  */
   int yylen;
   YYDPRINTF ((stderr, "Starting parse\n"));
   yystate = 0;
   yyerrstatus = 0;
   yynerrs = 0;
   yychar = YYEMPTY;     /* Cause a token to be read.  */
   /* Initialize stack pointers.
      Waste one element of value and location stack
      so that they stay on the same level as the state stack.
      The wasted elements are never initialized.  */
   yyssp = yyss;
   yyvsp = yyvs;
   yyvsp[0] = yylval;
   goto yysetstate;
 /*------------------------------------------------------------.
 | yynewstate -- Push a new state, which is found in yystate.  |
 `------------------------------------------------------------*/
  yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed. so pushing a state here evens the stacks.
      */
   yyssp++;
  yysetstate:
   *yyssp = yystate;
   if (yyss + yystacksize - 1 <= yyssp)
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYSIZE_T yysize = yyssp - yyss + 1;
 #ifdef yyoverflow
       {
     /* Give user a chance to reallocate the stack. Use copies of
        these so that the &'s don't force the real ones into
        memory.  */
     YYSTYPE *yyvs1 = yyvs;
     short int *yyss1 = yyss;
     /* Each stack pointer address is followed by the size of the
        data in use in that stack, in bytes.  This used to be a
        conditional around just the two extra args, but that might
        be undefined if yyoverflow is a macro.  */
     yyoverflow ("parser stack overflow",
             &yyss1, yysize * sizeof (*yyssp),
             &yyvs1, yysize * sizeof (*yyvsp),
             &yystacksize);
     yyss = yyss1;
     yyvs = yyvs1;
       }
 #else /* no yyoverflow */
 # ifndef YYSTACK_RELOCATE
       goto yyoverflowlab;
 # else
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
     goto yyoverflowlab;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
     yystacksize = YYMAXDEPTH;
       {
     short int *yyss1 = yyss;
     union yyalloc *yyptr =
       (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
     if (! yyptr)
       goto yyoverflowlab;
     YYSTACK_RELOCATE (yyss);
     YYSTACK_RELOCATE (yyvs);
 #  undef YYSTACK_RELOCATE
     if (yyss1 != yyssa)
       YYSTACK_FREE (yyss1);
       }
 # endif
 #endif /* no yyoverflow */
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YYDPRINTF ((stderr, "Stack size increased to %lu\n",
           (unsigned long int) yystacksize));
       if (yyss + yystacksize - 1 <= yyssp)
     YYABORT;
     }
   YYDPRINTF ((stderr, "Entering state %d\n", yystate));
   goto yybackup;
 /*-----------.
 | yybackup.  |
 `-----------*/
 yybackup:
 /* Do appropriate processing given the current state.  */
 /* Read a look-ahead token if we need one and don't already have one.  */
 /* yyresume: */
   /* First try to decide what to do without reference to look-ahead token.  */
   yyn = yypact[yystate];
   if (yyn == YYPACT_NINF)
     goto yydefault;
   /* Not known => get a look-ahead token if don't already have one.  */
   /* YYCHAR is either YYEMPTY or YYEOF or a valid look-ahead symbol.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF ((stderr, "Reading a token: "));
       yychar = YYLEX;
     }
   if (yychar <= YYEOF)
     {
       yychar = yytoken = YYEOF;
       YYDPRINTF ((stderr, "Now at end of input.\n"));
     }
   else
     {
       yytoken = YYTRANSLATE (yychar);
       YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yyn == 0 || yyn == YYTABLE_NINF)
     goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   if (yyn == YYFINAL)
     YYACCEPT;
   /* Shift the look-ahead token.  */
   YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
   /* Discard the token being shifted unless it is eof.  */
   if (yychar != YYEOF)
     yychar = YYEMPTY;
   *++yyvsp = yylval;
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   yystate = yyn;
   goto yynewstate;
 /*-----------------------------------------------------------.
 | yydefault -- do the default action for the current state.  |
 `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
 /*-----------------------------.
 | yyreduce -- Do a reduction.  |
 `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      `$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   YY_REDUCE_PRINT (yyn);
   switch (yyn)
     {
         case 2:
 #line 177 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         if ((yyvsp[0].exp) == NULL)
           YYABORT;
         ((struct parse_args *) arg)->res = (yyvsp[0].exp);
       }
     break;
   case 3:
 #line 185 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_3 (qmop, (yyvsp[-4].exp), (yyvsp[-2].exp), (yyvsp[0].exp));
       }
     break;
   case 4:
 #line 189 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_2 (lor, (yyvsp[-2].exp), (yyvsp[0].exp));
       }
     break;
   case 5:
 #line 193 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_2 (land, (yyvsp[-2].exp), (yyvsp[0].exp));
       }
     break;
   case 6:
 #line 197 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_2 ((yyvsp[-1].op), (yyvsp[-2].exp), (yyvsp[0].exp));
       }
     break;
   case 7:
 #line 201 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_2 ((yyvsp[-1].op), (yyvsp[-2].exp), (yyvsp[0].exp));
       }
     break;
   case 8:
 #line 205 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_2 ((yyvsp[-1].op), (yyvsp[-2].exp), (yyvsp[0].exp));
       }
     break;
   case 9:
 #line 209 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_2 ((yyvsp[-1].op), (yyvsp[-2].exp), (yyvsp[0].exp));
       }
     break;
   case 10:
 #line 213 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_1 (lnot, (yyvsp[0].exp));
       }
     break;
   case 11:
 #line 217 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = new_exp_0 (var);
       }
     break;
   case 12:
 #line 221 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         if (((yyval.exp) = new_exp_0 (num)) != NULL)
           (yyval.exp)->val.num = (yyvsp[0].num);
       }
     break;
   case 13:
 #line 226 "/usr/src/local/bash/bash-20080814/lib/intl/plural.y"
     {
         (yyval.exp) = (yyvsp[-1].exp);
       }
     break;
     }
 /* Line 1037 of yacc.c.  */
 #line 1270 "/usr/src/local/bash/bash-20080814/lib/intl/plural.c"
 ␌
   yyvsp -= yylen;
   yyssp -= yylen;
   YY_STACK_PRINT (yyss, yyssp);
   *++yyvsp = yyval;
   /* Now `shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   yyn = yyr1[yyn];
   yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
   if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
     yystate = yytable[yystate];
   else
     yystate = yydefgoto[yyn - YYNTOKENS];
   goto yynewstate;
 /*------------------------------------.
 | yyerrlab -- here on detecting error |
 `------------------------------------*/
 yyerrlab:
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
 #if YYERROR_VERBOSE
       yyn = yypact[yystate];
       if (YYPACT_NINF < yyn && yyn < YYLAST)
     {
       YYSIZE_T yysize = 0;
       int yytype = YYTRANSLATE (yychar);
       const char* yyprefix;
       char *yymsg;
       int yyx;
       /* Start YYX at -YYN if negative to avoid negative indexes in
          YYCHECK.  */
       int yyxbegin = yyn < 0 ? -yyn : 0;
       /* Stay within bounds of both yycheck and yytname.  */
       int yychecklim = YYLAST - yyn;
       int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
       int yycount = 0;
       yyprefix = ", expecting ";
       for (yyx = yyxbegin; yyx < yyxend; ++yyx)
         if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR)
           {
         yysize += yystrlen (yyprefix) + yystrlen (yytname [yyx]);
         yycount += 1;
         if (yycount == 5)
           {
             yysize = 0;
             break;
           }
           }
       yysize += (sizeof ("syntax error, unexpected ")
              + yystrlen (yytname[yytype]));
       yymsg = (char *) YYSTACK_ALLOC (yysize);
       if (yymsg != 0)
         {
           char *yyp = yystpcpy (yymsg, "syntax error, unexpected ");
           yyp = yystpcpy (yyp, yytname[yytype]);
           if (yycount < 5)
         {
           yyprefix = ", expecting ";
           for (yyx = yyxbegin; yyx < yyxend; ++yyx)
             if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR)
               {
             yyp = yystpcpy (yyp, yyprefix);
             yyp = yystpcpy (yyp, yytname[yyx]);
             yyprefix = " or ";
               }
         }
           yyerror (yymsg);
           YYSTACK_FREE (yymsg);
         }
       else
         yyerror ("syntax error; also virtual memory exhausted");
     }
       else
 #endif /* YYERROR_VERBOSE */
     yyerror ("syntax error");
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse look-ahead token after an
      error, discard it.  */
       if (yychar <= YYEOF)
         {
           /* If at end of input, pop the error token,
          then the rest of the stack, then return failure.  */
       if (yychar == YYEOF)
          for (;;)
            {
          YYPOPSTACK;
          if (yyssp == yyss)
            YYABORT;
          yydestruct ("Error: popping",
                              yystos[*yyssp], yyvsp);
            }
         }
       else
     {
       yydestruct ("Error: discarding", yytoken, &yylval);
       yychar = YYEMPTY;
     }
     }
   /* Else will try to reuse look-ahead token after shifting the error
      token.  */
   goto yyerrlab1;
 /*---------------------------------------------------.
 | yyerrorlab -- error raised explicitly by YYERROR.  |
 `---------------------------------------------------*/
 yyerrorlab:
 #ifdef __GNUC__
   /* Pacify GCC when the user code never invokes YYERROR and the label
      yyerrorlab therefore never appears in user code.  */
   if (0)
      goto yyerrorlab;
 #endif
 yyvsp -= yylen;
   yyssp -= yylen;
   yystate = *yyssp;
   goto yyerrlab1;
 /*-------------------------------------------------------------.
 | yyerrlab1 -- common code for both syntax error and YYERROR.  |
 `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;  /* Each real token shifted decrements this.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (yyn != YYPACT_NINF)
     {
       yyn += YYTERROR;
       if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
         {
           yyn = yytable[yyn];
           if (0 < yyn)
         break;
         }
     }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
     YYABORT;
       yydestruct ("Error: popping", yystos[yystate], yyvsp);
       YYPOPSTACK;
       yystate = *yyssp;
       YY_STACK_PRINT (yyss, yyssp);
     }
   if (yyn == YYFINAL)
     YYACCEPT;
   *++yyvsp = yylval;
   /* Shift the error token. */
   YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
 /*-------------------------------------.
 | yyacceptlab -- YYACCEPT comes here.  |
 `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturn;
 /*-----------------------------------.
 | yyabortlab -- YYABORT comes here.  |
 `-----------------------------------*/
 yyabortlab:
   yydestruct ("Error: discarding lookahead",
               yytoken, &yylval);
   yychar = YYEMPTY;
   yyresult = 1;
   goto yyreturn;
 #ifndef yyoverflow
 /*----------------------------------------------.
 | yyoverflowlab -- parser overflow comes here.  |
 `----------------------------------------------*/
 yyoverflowlab:
   yyerror ("parser stack overflow");
   yyresult = 2;
   /* Fall through.  */
 #endif
 yyreturn:
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE (yyss);
 #endif
   return yyresult;
 }
References YYSTYPE::exp, exp, new_exp_0(), new_exp_1(), new_exp_2(), new_exp_3(), NULL, YYSTYPE::num, stderr, val, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yychar, yycheck, yydefact, yydefgoto, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror, YYFINAL, YYINITDEPTH, YYLAST, YYLEX, yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, yypact, YYPACT_NINF, yypgoto, YYPOPSTACK, yyr1, yyr2, YYSIZE_T, yyalloc::yyss, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yystos, yytable, YYTABLE_NINF, YYTERROR, YYTRANSLATE, and yyalloc::yyvs.
Variable Documentation
exp
void internal_function struct expression* exp
Definition at line 1504 of file plural.c.
Referenced by switch(), yylex(), and yyparse().
yycheck
const yysigned_char yycheck[] static
Initial value:
=
{
       1,    10,    11,     4,    13,    14,     8,     9,     0,    10,
      11,    12,    13,    14,    15,    16,     3,     4,     5,     6,
       7,     8,     9,     9,    25,     7,     8,     9,    15,     3,
       4,     5,     6,     7,     8,     9,    -1,    -1,    12,     3,
       4,     5,     6,     7,     8,     9,     5,     6,     7,     8,
       9,     6,     7,     8,     9
}
Definition at line 523 of file plural.c.
Referenced by yyparse().
yydefact
const unsigned char yydefact[] static
Initial value:
=
{
       0,     0,    12,    11,     0,     0,     2,    10,     0,     1,
       0,     0,     0,     0,     0,     0,     0,    13,     0,     4,
       5,     6,     7,     8,     9,     0,     3
}
Definition at line 479 of file plural.c.
Referenced by yyparse().
yydefgoto
const yysigned_char yydefgoto[] static
Initial value:
=
{
      -1,     5,     6
}
Definition at line 487 of file plural.c.
Referenced by yyparse().
yypact
const yysigned_char yypact[] static
Initial value:
=
{
      -9,    -9,   -10,   -10,    -9,     8,    36,   -10,    13,   -10,
      -9,    -9,    -9,    -9,    -9,    -9,    -9,   -10,    26,    41,
      45,    18,    -2,    14,   -10,    -9,    36
}
Definition at line 495 of file plural.c.
Referenced by yyparse().
yypgoto
const yysigned_char yypgoto[] static
Initial value:
=
{
     -10,   -10,    -1
}
Definition at line 503 of file plural.c.
Referenced by yyparse().
yyr1
const unsigned char yyr1[] static
Initial value:
=
{
       0,    16,    17,    18,    18,    18,    18,    18,    18,    18,
      18,    18,    18,    18
}
Definition at line 463 of file plural.c.
Referenced by yyparse().
yyr2
const unsigned char yyr2[] static
Initial value:
=
{
       0,     2,     1,     5,     3,     3,     3,     3,     3,     3,
       2,     1,     1,     3
}
Definition at line 470 of file plural.c.
Referenced by yyparse().
yystos
const unsigned char yystos[] static
Initial value:
=
{
       0,    10,    11,    13,    14,    17,    18,    18,    18,     0,
       3,     4,     5,     6,     7,     8,     9,    15,    18,    18,
      18,    18,    18,    18,    18,    12,    18
}
Definition at line 535 of file plural.c.
Referenced by yyparse().
yytable
const unsigned char yytable[] static
Initial value:
=
{
       7,     1,     2,     8,     3,     4,    15,    16,     9,    18,
      19,    20,    21,    22,    23,    24,    10,    11,    12,    13,
      14,    15,    16,    16,    26,    14,    15,    16,    17,    10,
      11,    12,    13,    14,    15,    16,     0,     0,    25,    10,
      11,    12,    13,    14,    15,    16,    12,    13,    14,    15,
      16,    13,    14,    15,    16
}
Definition at line 513 of file plural.c.
Referenced by yyparse().
yytranslate
const unsigned char yytranslate[] static
Initial value:
=
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    10,     2,     2,     2,     2,     5,     2,
      14,    15,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,    12,     2,
       2,     2,     2,     3,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      13,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     4,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     6,     7,
       8,     9,    11
}
Definition at line 383 of file plural.c.