Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/p_maputl.c File Reference
p_maputl.c File Reference
#include <stdlib.h>
#include "m_bbox.h"
#include "doomdef.h"
#include "doomstat.h"
#include "p_local.h"
#include "r_state.h"
Data Structures
struct intercepts_overrun_t
Functions
fixed_t P_AproxDistance (fixed_t dx, fixed_t dy)
int P_PointOnLineSide (fixed_t x, fixed_t y, line_t *line)
int P_BoxOnLineSide (fixed_t *tmbox, line_t *ld)
int P_PointOnDivlineSide (fixed_t x, fixed_t y, divline_t *line)
void P_MakeDivline (line_t *li, divline_t *dl)
fixed_t P_InterceptVector (divline_t *v2, divline_t *v1)
void P_LineOpening (line_t *linedef)
void P_UnsetThingPosition (mobj_t *thing)
void P_SetThingPosition (mobj_t *thing)
boolean P_BlockLinesIterator (int x, int y, boolean(*func)(line_t *))
boolean P_BlockThingsIterator (int x, int y, boolean(*func)(mobj_t *))
static void InterceptsOverrun (int num_intercepts, intercept_t *intercept)
boolean PIT_AddLineIntercepts (line_t *ld)
boolean PIT_AddThingIntercepts (mobj_t *thing)
boolean P_TraverseIntercepts (traverser_t func, fixed_t maxfrac)
static void InterceptsMemoryOverrun (int location, int value)
boolean P_PathTraverse (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2, int flags, boolean(*trav)(intercept_t *))
Variables
fixed_t opentop
fixed_t openbottom
fixed_t openrange
fixed_t lowfloor
intercept_t intercepts [MAXINTERCEPTS]
intercept_t * intercept_p
divline_t trace
boolean earlyout
int ptflags
fixed_t bulletslope
static intercepts_overrun_t intercepts_overrun []
Data Structure Documentation
intercepts_overrun_t
struct intercepts_overrun_t
Definition at line 738 of file p_maputl.c.
Data Fields
void * addr
boolean int16_array
int len
Function Documentation
InterceptsMemoryOverrun()
static void InterceptsMemoryOverrun (int location, int value) static
Definition at line 782 of file p_maputl.c.
 {
     int i, offset;
     int index;
     void *addr;
     i = 0;
     offset = 0;
     // Search down the array until we find the right entry
     while (intercepts_overrun[i].len != 0)
     {
         if (offset + intercepts_overrun[i].len > location)
         {
             addr = intercepts_overrun[i].addr;
             // Write the value to the memory location.
             // 16-bit and 32-bit values are written differently.
             if (addr != NULL)
             {
                 if (intercepts_overrun[i].int16_array)
                 {
                     index = (location - offset) / 2;
                     ((short *) addr)[index] = value & 0xffff;
                     ((short *) addr)[index + 1] = (value >> 16) & 0xffff;
                 }
                 else
                 {
                     index = (location - offset) / 4;
                     ((int *) addr)[index] = value;
                 }
             }
             break;
         }
         offset += intercepts_overrun[i].len;
         ++i;
     }
 }
References intercepts_overrun_t::addr, addr, i, index, intercepts_overrun, intercepts_overrun_t::len, NULL, offset, and value.
Referenced by InterceptsOverrun().
InterceptsOverrun()
static void InterceptsOverrun (int num_intercepts, intercept_t * intercept) static
Definition at line 827 of file p_maputl.c.
 {
     int location;
     if (num_intercepts <= MAXINTERCEPTS_ORIGINAL)
     {
         // No overrun
         return;
     }
     location = (num_intercepts - MAXINTERCEPTS_ORIGINAL - 1) * 12;
     // Overwrite memory that is overwritten in Vanilla Doom, using
     // the values from the intercept structure.
     //
     // Note: the ->d.{thing,line} member should really have its
     // address translated into the correct address value for
     // Vanilla Doom.
     InterceptsMemoryOverrun(location, intercept->frac);
     InterceptsMemoryOverrun(location + 4, intercept->isaline);
     InterceptsMemoryOverrun(location + 8, (int) intercept->d.thing);
 }
References intercept_t::d, intercept_t::frac, InterceptsMemoryOverrun(), intercept_t::isaline, and MAXINTERCEPTS_ORIGINAL.
Referenced by PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
P_AproxDistance()
fixed_t P_AproxDistance (fixed_t dx, fixed_t dy)
Definition at line 44 of file p_maputl.c.
 {
     dx = abs(dx);
     dy = abs(dy);
     if (dx < dy)
     return dx+dy-(dx>>1);
     return dx+dy-(dy>>1);
 }
References abs.
Referenced by A_SkullAttack(), A_Tracer(), P_CheckMeleeRange(), P_CheckMissileRange(), P_HitSlideLine(), P_LookForPlayers(), P_SpawnMissile(), and P_ZMovement().
P_BlockLinesIterator()
boolean P_BlockLinesIterator (int x, int y, boolean(*)(line_t *) func)
Definition at line 467 of file p_maputl.c.
 {
     int         offset;
     short*      list;
     line_t*     ld;
     if (x<0
     || y<0
     || x>=bmapwidth
     || y>=bmapheight)
     {
     return true;
     }
     offset = y*bmapwidth+x;
     offset = *(blockmap+offset);
     for ( list = blockmaplump+offset ; *list != -1 ; list++)
     {
     ld = &lines[*list];
     if (ld->validcount == validcount)
         continue;   // line has already been checked
     ld->validcount = validcount;
     if ( !func(ld) )
         return false;
     }
     return true;    // everything was checked
 }
References blockmap, blockmaplump, bmapheight, bmapwidth, lines, offset, line_s::validcount, validcount, x, and y.
Referenced by P_CheckPosition(), and P_PathTraverse().
P_BlockThingsIterator()
boolean P_BlockThingsIterator (int x, int y, boolean(*)(mobj_t *) func)
Definition at line 508 of file p_maputl.c.
 {
     mobj_t*     mobj;
     if ( x<0
      || y<0
      || x>=bmapwidth
      || y>=bmapheight)
     {
     return true;
     }
     for (mobj = blocklinks[y*bmapwidth+x] ;
      mobj ;
      mobj = mobj->bnext)
     {
     if (!func( mobj ) )
         return false;
     }
     return true;
 }
References blocklinks, bmapheight, bmapwidth, mobj_s::bnext, x, and y.
Referenced by A_VileChase(), P_ChangeSector(), P_CheckPosition(), P_PathTraverse(), P_RadiusAttack(), and P_TeleportMove().
P_BoxOnLineSide()
int P_BoxOnLineSide (fixed_t * tmbox, line_t * ld)
Definition at line 105 of file p_maputl.c.
 {
     int     p1 = 0;
     int     p2 = 0;
     switch (ld->slopetype)
     {
       case ST_HORIZONTAL:
     p1 = tmbox[BOXTOP] > ld->v1->y;
     p2 = tmbox[BOXBOTTOM] > ld->v1->y;
     if (ld->dx < 0)
     {
         p1 ^= 1;
         p2 ^= 1;
     }
     break;
       case ST_VERTICAL:
     p1 = tmbox[BOXRIGHT] < ld->v1->x;
     p2 = tmbox[BOXLEFT] < ld->v1->x;
     if (ld->dy < 0)
     {
         p1 ^= 1;
         p2 ^= 1;
     }
     break;
       case ST_POSITIVE:
     p1 = P_PointOnLineSide (tmbox[BOXLEFT], tmbox[BOXTOP], ld);
     p2 = P_PointOnLineSide (tmbox[BOXRIGHT], tmbox[BOXBOTTOM], ld);
     break;
       case ST_NEGATIVE:
     p1 = P_PointOnLineSide (tmbox[BOXRIGHT], tmbox[BOXTOP], ld);
     p2 = P_PointOnLineSide (tmbox[BOXLEFT], tmbox[BOXBOTTOM], ld);
     break;
     }
     if (p1 == p2)
     return p1;
     return -1;
 }
References BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, line_s::dx, line_s::dy, P_PointOnLineSide(), line_s::slopetype, ST_HORIZONTAL, ST_NEGATIVE, ST_POSITIVE, ST_VERTICAL, line_s::v1, vertex_t::x, and vertex_t::y.
Referenced by PIT_CheckLine().
P_InterceptVector()
fixed_t P_InterceptVector (divline_t * v2, divline_t * v1)
Definition at line 226 of file p_maputl.c.
 {
 #if 1
     fixed_t frac;
     fixed_t num;
     fixed_t den;
     den = FixedMul (v1->dy>>8,v2->dx) - FixedMul(v1->dx>>8,v2->dy);
     if (den == 0)
     return 0;
     //  I_Error ("P_InterceptVector: parallel");
     num =
     FixedMul ( (v1->x - v2->x)>>8 ,v1->dy )
     +FixedMul ( (v2->y - v1->y)>>8, v1->dx );
     frac = FixedDiv (num , den);
     return frac;
 #else   // UNUSED, float debug.
     float   frac;
     float   num;
     float   den;
     float   v1x;
     float   v1y;
     float   v1dx;
     float   v1dy;
     float   v2x;
     float   v2y;
     float   v2dx;
     float   v2dy;
     v1x = (float)v1->x/FRACUNIT;
     v1y = (float)v1->y/FRACUNIT;
     v1dx = (float)v1->dx/FRACUNIT;
     v1dy = (float)v1->dy/FRACUNIT;
     v2x = (float)v2->x/FRACUNIT;
     v2y = (float)v2->y/FRACUNIT;
     v2dx = (float)v2->dx/FRACUNIT;
     v2dy = (float)v2->dy/FRACUNIT;
     den = v1dy*v2dx - v1dx*v2dy;
     if (den == 0)
     return 0;   // parallel
     num = (v1x - v2x)*v1dy + (v2y - v1y)*v1dx;
     frac = num / den;
     return frac*FRACUNIT;
 #endif
 }
References FixedDiv(), FixedMul(), FRACUNIT, num, v1, and v2.
Referenced by PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
P_LineOpening()
void P_LineOpening (line_t * linedef)
Definition at line 295 of file p_maputl.c.
 {
     sector_t*   front;
     sector_t*   back;
     if (linedef->sidenum[1] == -1)
     {
     // single sided line
     openrange = 0;
     return;
     }
     front = linedef->frontsector;
     back = linedef->backsector;
     if (front->ceilingheight < back->ceilingheight)
     opentop = front->ceilingheight;
     else
     opentop = back->ceilingheight;
     if (front->floorheight > back->floorheight)
     {
     openbottom = front->floorheight;
     lowfloor = back->floorheight;
     }
     else
     {
     openbottom = back->floorheight;
     lowfloor = front->floorheight;
     }
     openrange = opentop - openbottom;
 }
References line_s::backsector, sector_t::ceilingheight, sector_t::floorheight, line_s::frontsector, linedef, lowfloor, openbottom, openrange, opentop, and line_s::sidenum.
Referenced by P_RecursiveSound(), PIT_CheckLine(), PTR_AimTraverse(), PTR_ShootTraverse(), PTR_SlideTraverse(), and PTR_UseTraverse().
P_MakeDivline()
void P_MakeDivline (line_t * li, divline_t * dl)
Definition at line 206 of file p_maputl.c.
 {
     dl->x = li->v1->x;
     dl->y = li->v1->y;
     dl->dx = li->dx;
     dl->dy = li->dy;
 }
References divline_t::dx, line_s::dx, divline_t::dy, line_s::dy, line_s::v1, divline_t::x, vertex_t::x, divline_t::y, and vertex_t::y.
Referenced by PIT_AddLineIntercepts().
P_PathTraverse()
boolean P_PathTraverse (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2, int flags, boolean(*)(intercept_t *) trav)
Definition at line 861 of file p_maputl.c.
 {
     fixed_t xt1;
     fixed_t yt1;
     fixed_t xt2;
     fixed_t yt2;
     fixed_t xstep;
     fixed_t ystep;
     fixed_t partial;
     fixed_t xintercept;
     fixed_t yintercept;
     int     mapx;
     int     mapy;
     int     mapxstep;
     int     mapystep;
     int     count;
     earlyout = flags & PT_EARLYOUT;
     validcount++;
     intercept_p = intercepts;
     if ( ((x1-bmaporgx)&(MAPBLOCKSIZE-1)) == 0)
     x1 += FRACUNIT; // don't side exactly on a line
     if ( ((y1-bmaporgy)&(MAPBLOCKSIZE-1)) == 0)
     y1 += FRACUNIT; // don't side exactly on a line
     trace.x = x1;
     trace.y = y1;
     trace.dx = x2 - x1;
     trace.dy = y2 - y1;
     x1 -= bmaporgx;
     y1 -= bmaporgy;
     xt1 = x1>>MAPBLOCKSHIFT;
     yt1 = y1>>MAPBLOCKSHIFT;
     x2 -= bmaporgx;
     y2 -= bmaporgy;
     xt2 = x2>>MAPBLOCKSHIFT;
     yt2 = y2>>MAPBLOCKSHIFT;
     if (xt2 > xt1)
     {
     mapxstep = 1;
     partial = FRACUNIT - ((x1>>MAPBTOFRAC)&(FRACUNIT-1));
     ystep = FixedDiv (y2-y1,abs(x2-x1));
     }
     else if (xt2 < xt1)
     {
     mapxstep = -1;
     partial = (x1>>MAPBTOFRAC)&(FRACUNIT-1);
     ystep = FixedDiv (y2-y1,abs(x2-x1));
     }
     else
     {
     mapxstep = 0;
     partial = FRACUNIT;
     ystep = 256*FRACUNIT;
     }
     yintercept = (y1>>MAPBTOFRAC) + FixedMul (partial, ystep);
     if (yt2 > yt1)
     {
     mapystep = 1;
     partial = FRACUNIT - ((y1>>MAPBTOFRAC)&(FRACUNIT-1));
     xstep = FixedDiv (x2-x1,abs(y2-y1));
     }
     else if (yt2 < yt1)
     {
     mapystep = -1;
     partial = (y1>>MAPBTOFRAC)&(FRACUNIT-1);
     xstep = FixedDiv (x2-x1,abs(y2-y1));
     }
     else
     {
     mapystep = 0;
     partial = FRACUNIT;
     xstep = 256*FRACUNIT;
     }
     xintercept = (x1>>MAPBTOFRAC) + FixedMul (partial, xstep);
     // Step through map blocks.
     // Count is present to prevent a round off error
     // from skipping the break.
     mapx = xt1;
     mapy = yt1;
     for (count = 0 ; count < 64 ; count++)
     {
     if (flags & PT_ADDLINES)
     {
         if (!P_BlockLinesIterator (mapx, mapy,PIT_AddLineIntercepts))
         return false;   // early out
     }
     if (flags & PT_ADDTHINGS)
     {
         if (!P_BlockThingsIterator (mapx, mapy,PIT_AddThingIntercepts))
         return false;   // early out
     }
     if (mapx == xt2
         && mapy == yt2)
     {
         break;
     }
     if ( (yintercept >> FRACBITS) == mapy)
     {
         yintercept += ystep;
         mapx += mapxstep;
     }
     else if ( (xintercept >> FRACBITS) == mapx)
     {
         xintercept += xstep;
         mapy += mapystep;
     }
     }
     // go through the sorted list
     return P_TraverseIntercepts ( trav, FRACUNIT );
 }
References abs, bmaporgx, bmaporgy, count, divline_t::dx, divline_t::dy, earlyout, FixedDiv(), FixedMul(), flags, FRACBITS, FRACUNIT, intercept_p, intercepts, MAPBLOCKSHIFT, MAPBLOCKSIZE, MAPBTOFRAC, P_BlockLinesIterator(), P_BlockThingsIterator(), P_TraverseIntercepts(), PIT_AddLineIntercepts(), PIT_AddThingIntercepts(), PT_ADDLINES, PT_ADDTHINGS, PT_EARLYOUT, trace, validcount, divline_t::x, divline_t::y, and y1().
Referenced by P_AimLineAttack(), P_LineAttack(), P_SlideMove(), and P_UseLines().
P_PointOnDivlineSide()
int P_PointOnDivlineSide (fixed_t x, fixed_t y, divline_t * line)
Definition at line 156 of file p_maputl.c.
 {
     fixed_t dx;
     fixed_t dy;
     fixed_t left;
     fixed_t right;
     if (!line->dx)
     {
     if (x <= line->x)
         return line->dy > 0;
     return line->dy < 0;
     }
     if (!line->dy)
     {
     if (y <= line->y)
         return line->dx < 0;
     return line->dx > 0;
     }
     dx = (x - line->x);
     dy = (y - line->y);
     // try to quickly decide by looking at sign bits
     if ( (line->dy ^ line->dx ^ dx ^ dy)&0x80000000 )
     {
     if ( (line->dy ^ dx) & 0x80000000 )
         return 1;       // (left is negative)
     return 0;
     }
     left = FixedMul ( line->dy>>8, dx>>8 );
     right = FixedMul ( dy>>8 , line->dx>>8 );
     if (right < left)
     return 0;       // front side
     return 1;           // back side
 }
References FixedMul(), line, x, and y.
Referenced by PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
P_PointOnLineSide()
int P_PointOnLineSide (fixed_t x, fixed_t y, line_t * line)
Definition at line 61 of file p_maputl.c.
 {
     fixed_t dx;
     fixed_t dy;
     fixed_t left;
     fixed_t right;
     if (!line->dx)
     {
     if (x <= line->v1->x)
         return line->dy > 0;
     return line->dy < 0;
     }
     if (!line->dy)
     {
     if (y <= line->v1->y)
         return line->dx < 0;
     return line->dx > 0;
     }
     dx = (x - line->v1->x);
     dy = (y - line->v1->y);
     left = FixedMul ( line->dy>>FRACBITS , dx );
     right = FixedMul ( dy , line->dx>>FRACBITS );
     if (right < left)
     return 0;       // front side
     return 1;           // back side
 }
References FixedMul(), FRACBITS, line, v1, x, and y.
Referenced by P_BoxOnLineSide(), P_HitSlideLine(), P_TryMove(), PIT_AddLineIntercepts(), PTR_SlideTraverse(), and PTR_UseTraverse().
P_SetThingPosition()
void P_SetThingPosition (mobj_t * thing)
Definition at line 391 of file p_maputl.c.
 {
     subsector_t*    ss;
     sector_t*       sec;
     int         blockx;
     int         blocky;
     mobj_t**        link;
     // link into subsector
     ss = R_PointInSubsector (thing->x,thing->y);
     thing->subsector = ss;
     if ( ! (thing->flags & MF_NOSECTOR) )
     {
     // invisible things don't go into the sector links
     sec = ss->sector;
     thing->sprev = NULL;
     thing->snext = sec->thinglist;
     if (sec->thinglist)
         sec->thinglist->sprev = thing;
     sec->thinglist = thing;
     }
     // link into blockmap
     if ( ! (thing->flags & MF_NOBLOCKMAP) )
     {
     // inert things don't need to be in blockmap
     blockx = (thing->x - bmaporgx)>>MAPBLOCKSHIFT;
     blocky = (thing->y - bmaporgy)>>MAPBLOCKSHIFT;
     if (blockx>=0
         && blockx < bmapwidth
         && blocky>=0
         && blocky < bmapheight)
     {
         link = &blocklinks[blocky*bmapwidth+blockx];
         thing->bprev = NULL;
         thing->bnext = *link;
         if (*link)
         (*link)->bprev = thing;
         *link = thing;
     }
     else
     {
         // thing is off the map
         thing->bnext = thing->bprev = NULL;
     }
     }
 }
References blocklinks, bmapheight, bmaporgx, bmaporgy, bmapwidth, mobj_s::bnext, mobj_s::bprev, mobj_s::flags, link(), MAPBLOCKSHIFT, MF_NOBLOCKMAP, MF_NOSECTOR, NULL, R_PointInSubsector(), subsector_s::sector, mobj_s::snext, mobj_s::sprev, mobj_s::subsector, sector_t::thinglist, mobj_s::x, and mobj_s::y.
Referenced by A_Fire(), P_SpawnMobj(), P_TeleportMove(), P_TryMove(), and P_UnArchiveThinkers().
P_TraverseIntercepts()
boolean P_TraverseIntercepts (traverser_t func, fixed_t maxfrac)
Definition at line 682 of file p_maputl.c.
 {
     int         count;
     fixed_t     dist;
     intercept_t*    scan;
     intercept_t*    in;
     count = intercept_p - intercepts;
     in = 0;         // shut up compiler warning
     while (count--)
     {
     dist = __INT_MAX__;
     for (scan = intercepts ; scan<intercept_p ; scan++)
     {
         if (scan->frac < dist)
         {
         dist = scan->frac;
         in = scan;
         }
     }
     if (dist > maxfrac)
         return true;    // checked everything in range
 #if 0  // UNUSED
     {
     // don't check these yet, there may be others inserted
     in = scan = intercepts;
     for ( scan = intercepts ; scan<intercept_p ; scan++)
         if (scan->frac > maxfrac)
         *in++ = *scan;
     intercept_p = in;
     return false;
     }
 #endif
         if ( !func (in) )
         return false;   // don't bother going farther
     in->frac = __INT_MAX__;
     }
     return true;        // everything was traversed
 }
References count, intercept_t::frac, intercept_p, intercepts, and scan.
Referenced by P_PathTraverse().
P_UnsetThingPosition()
void P_UnsetThingPosition (mobj_t * thing)
Definition at line 342 of file p_maputl.c.
 {
     int     blockx;
     int     blocky;
     if ( ! (thing->flags & MF_NOSECTOR) )
     {
     // inert things don't need to be in blockmap?
     // unlink from subsector
     if (thing->snext)
         thing->snext->sprev = thing->sprev;
     if (thing->sprev)
         thing->sprev->snext = thing->snext;
     else
         thing->subsector->sector->thinglist = thing->snext;
     }
     if ( ! (thing->flags & MF_NOBLOCKMAP) )
     {
     // inert things don't need to be in blockmap
     // unlink from block map
     if (thing->bnext)
         thing->bnext->bprev = thing->bprev;
     if (thing->bprev)
         thing->bprev->bnext = thing->bnext;
     else
     {
         blockx = (thing->x - bmaporgx)>>MAPBLOCKSHIFT;
         blocky = (thing->y - bmaporgy)>>MAPBLOCKSHIFT;
         if (blockx>=0 && blockx < bmapwidth
         && blocky>=0 && blocky <bmapheight)
         {
         blocklinks[blocky*bmapwidth+blockx] = thing->bnext;
         }
     }
     }
 }
References blocklinks, bmapheight, bmaporgx, bmaporgy, bmapwidth, mobj_s::bnext, mobj_s::bprev, mobj_s::flags, MAPBLOCKSHIFT, MF_NOBLOCKMAP, MF_NOSECTOR, subsector_s::sector, mobj_s::snext, mobj_s::sprev, mobj_s::subsector, sector_t::thinglist, mobj_s::x, and mobj_s::y.
Referenced by A_Fire(), P_RemoveMobj(), P_TeleportMove(), and P_TryMove().
PIT_AddLineIntercepts()
boolean PIT_AddLineIntercepts (line_t * ld)
Definition at line 559 of file p_maputl.c.
 {
     int         s1;
     int         s2;
     fixed_t     frac;
     divline_t       dl;
     // avoid precision problems with two routines
     if ( trace.dx > FRACUNIT*16
      || trace.dy > FRACUNIT*16
      || trace.dx < -FRACUNIT*16
      || trace.dy < -FRACUNIT*16)
     {
     s1 = P_PointOnDivlineSide (ld->v1->x, ld->v1->y, &trace);
     s2 = P_PointOnDivlineSide (ld->v2->x, ld->v2->y, &trace);
     }
     else
     {
     s1 = P_PointOnLineSide (trace.x, trace.y, ld);
     s2 = P_PointOnLineSide (trace.x+trace.dx, trace.y+trace.dy, ld);
     }
     if (s1 == s2)
     return true;    // line isn't crossed
     // hit the line
     P_MakeDivline (ld, &dl);
     frac = P_InterceptVector (&trace, &dl);
     if (frac < 0)
     return true;    // behind source
     // try to early out the check
     if (earlyout
     && frac < FRACUNIT
     && !ld->backsector)
     {
     return false;   // stop checking
     }
     intercept_p->frac = frac;
     intercept_p->isaline = true;
     intercept_p->d.line = ld;
     InterceptsOverrun(intercept_p - intercepts, intercept_p);
     intercept_p++;
     return true;    // continue
 }
References line_s::backsector, intercept_t::d, divline_t::dx, divline_t::dy, earlyout, intercept_t::frac, FRACUNIT, intercept_p, intercepts, InterceptsOverrun(), intercept_t::isaline, P_InterceptVector(), P_MakeDivline(), P_PointOnDivlineSide(), P_PointOnLineSide(), s1, s2, trace, line_s::v1, line_s::v2, divline_t::x, vertex_t::x, divline_t::y, and vertex_t::y.
Referenced by P_PathTraverse().
PIT_AddThingIntercepts()
boolean PIT_AddThingIntercepts (mobj_t * thing)
Definition at line 614 of file p_maputl.c.
 {
     fixed_t     x1;
     fixed_t     y1;
     fixed_t     x2;
     fixed_t     y2;
     int         s1;
     int         s2;
     boolean     tracepositive;
     divline_t       dl;
     fixed_t     frac;
     tracepositive = (trace.dx ^ trace.dy)>0;
     // check a corner to corner crossection for hit
     if (tracepositive)
     {
     x1 = thing->x - thing->radius;
     y1 = thing->y + thing->radius;
     x2 = thing->x + thing->radius;
     y2 = thing->y - thing->radius;
     }
     else
     {
     x1 = thing->x - thing->radius;
     y1 = thing->y - thing->radius;
     x2 = thing->x + thing->radius;
     y2 = thing->y + thing->radius;
     }
     s1 = P_PointOnDivlineSide (x1, y1, &trace);
     s2 = P_PointOnDivlineSide (x2, y2, &trace);
     if (s1 == s2)
     return true;        // line isn't crossed
     dl.x = x1;
     dl.y = y1;
     dl.dx = x2-x1;
     dl.dy = y2-y1;
     frac = P_InterceptVector (&trace, &dl);
     if (frac < 0)
     return true;        // behind source
     intercept_p->frac = frac;
     intercept_p->isaline = false;
     intercept_p->d.thing = thing;
     InterceptsOverrun(intercept_p - intercepts, intercept_p);
     intercept_p++;
     return true;        // keep going
 }
References intercept_t::d, divline_t::dx, divline_t::dy, intercept_t::frac, intercept_p, intercepts, InterceptsOverrun(), intercept_t::isaline, P_InterceptVector(), P_PointOnDivlineSide(), mobj_s::radius, s1, s2, trace, divline_t::x, mobj_s::x, divline_t::y, mobj_s::y, and y1().
Referenced by P_PathTraverse().
Variable Documentation
bulletslope
fixed_t bulletslope extern
Definition at line 607 of file p_pspr.c.
Referenced by A_FireShotgun2(), P_BulletSlope(), and P_GunShot().
earlyout
boolean earlyout
Definition at line 543 of file p_maputl.c.
Referenced by P_PathTraverse(), and PIT_AddLineIntercepts().
intercept_p
intercept_t* intercept_p
Definition at line 540 of file p_maputl.c.
Referenced by P_PathTraverse(), P_TraverseIntercepts(), PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
intercepts
intercept_t intercepts[MAXINTERCEPTS]
Definition at line 539 of file p_maputl.c.
Referenced by P_PathTraverse(), P_TraverseIntercepts(), PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
intercepts_overrun
intercepts_overrun_t intercepts_overrun[] static
Initial value:
=
{
    {4,   NULL,                          false},
    {4,   NULL,          false},
    {4,   NULL,       false},
    {4,   &lowfloor,                     false},
    {4,   &openbottom,                   false},
    {4,   &opentop,                      false},
    {4,   &openrange,                    false},
    {4,   NULL,                          false},
    {120, NULL,       false},
    {8,   NULL,                          false},
    {4,   &bulletslope,                  false},
    {4,   NULL,            false},
    {4,   NULL,            false},
    {4,   NULL,                          false},
    {40,  &playerstarts,                 true},
    {4,   NULL,        false},
    {4,   &bmapwidth,                    false},
    {4,   NULL,          false},
    {4,   &bmaporgx,                     false},
    {4,   &bmaporgy,                     false},
    {4,   NULL,      false},
    {4,   &bmapheight,                   false},
    {0,   NULL,                          false},
}
Definition at line 753 of file p_maputl.c.
Referenced by InterceptsMemoryOverrun().
lowfloor
fixed_t lowfloor
Definition at line 292 of file p_maputl.c.
Referenced by P_LineOpening(), and PIT_CheckLine().
openbottom
fixed_t openbottom
Definition at line 290 of file p_maputl.c.
Referenced by P_CrossSubsector(), P_LineOpening(), PIT_CheckLine(), PTR_AimTraverse(), PTR_ShootTraverse(), and PTR_SlideTraverse().
openrange
fixed_t openrange
Definition at line 291 of file p_maputl.c.
Referenced by P_LineOpening(), P_RecursiveSound(), and PTR_UseTraverse().
opentop
fixed_t opentop
Definition at line 289 of file p_maputl.c.
Referenced by P_CrossSubsector(), P_LineOpening(), PIT_CheckLine(), PTR_AimTraverse(), PTR_ShootTraverse(), and PTR_SlideTraverse().
ptflags
int ptflags
Definition at line 544 of file p_maputl.c.
trace
divline_t trace
Definition at line 542 of file p_maputl.c.
Referenced by P_PathTraverse(), PIT_AddLineIntercepts(), PIT_AddThingIntercepts(), and PTR_ShootTraverse().