Fennix: Userspace/apps/base/busybox/mailutils/reformime.c File Reference
reformime.c File Reference
#include "libbb.h"
#include "mail.h"
Macros
#define dbg_error_msg(...) ((void)0)
Enumerations
enum { OPT_x = 1 << 0 , OPT_X = 1 << 1 }
Functions
static const char * find_token (const char *const string_array[], const char *key, const char *defvalue)
static const char * xfind_token (const char *const string_array[], const char *key)
static int parse (const char *boundary, char **argv)
int reformime_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
dbg_error_msg
#define dbg_error_msg (...) ((void)0)
Definition at line 33 of file reformime.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_x
OPT_X
Definition at line 57 of file reformime.c.
      {
     OPT_x = 1 << 0,
     OPT_X = 1 << 1,
 #if ENABLE_FEATURE_REFORMIME_COMPAT
     OPT_d = 1 << 2,
     OPT_e = 1 << 3,
     OPT_i = 1 << 4,
     OPT_s = 1 << 5,
     OPT_r = 1 << 6,
     OPT_c = 1 << 7,
     OPT_m = 1 << 8,
     OPT_h = 1 << 9,
     OPT_o = 1 << 10,
     OPT_O = 1 << 11,
 #endif
 };
Function Documentation
find_token()
static const char* find_token (const char *const string_array[], const char * key, const char * defvalue) static
Definition at line 36 of file reformime.c.
 {
     const char *r = NULL;
     int i;
     for (i = 0; string_array[i] != NULL; i++) {
         if (strcasecmp(string_array[i], key) == 0) {
             r = (char *)string_array[i+1];
             break;
         }
     }
     return (r) ? r : defvalue;
 }
References i, NULL, and strcasecmp.
Referenced by parse(), and xfind_token().
parse()
static int parse (const char * boundary, char ** argv) static
Definition at line 74 of file reformime.c.
 {
     int boundary_len = strlen(boundary);
     char uniq[sizeof("%%llu.%u") + sizeof(int)*3];
     dbg_error_msg("BOUNDARY[%s]", boundary);
     // prepare unique string pattern
     sprintf(uniq, "%%llu.%u", (unsigned)getpid());
     dbg_error_msg("UNIQ[%s]", uniq);
     while (1) {
         char *header;
         const char *tokens[32]; /* 32 is enough */
         const char *type;
         /* Read the header (everything up to two \n) */
         {
             unsigned header_idx = 0;
             int last_ch = 0;
             header = NULL;
             while (1) {
                 int ch = fgetc(stdin);
                 if (ch == '\r') /* Support both line endings */
                     continue;
                 if (ch == EOF)
                     break;
                 if (ch == '\n' && last_ch == ch)
                     break;
                 if (!(header_idx & 0xff))
                     header = xrealloc(header, header_idx + 0x101);
                 header[header_idx++] = last_ch = ch;
             }
             if (!header) {
                 dbg_error_msg("EOF");
                 break;
             }
             header[header_idx] = '\0';
             dbg_error_msg("H:'%s'", p);
         }
         /* Split to tokens */
         {
             char *s, *p;
             char *tokstate;
             unsigned ntokens;
             const char *delims = ";=\" \t\n";
             /* Skip to last Content-Type: */
             s = p = header;
             while ((p = strchr(p, '\n')) != NULL) {
                 p++;
                 if (strncasecmp(p, "Content-Type:", sizeof("Content-Type:")-1) == 0)
                     s = p;
             }
             dbg_error_msg("L:'%s'", p);
             ntokens = 0;
             s = strtok_r(s, delims, &tokstate);
             while (s) {
                 tokens[ntokens] = s;
                 if (ntokens < ARRAY_SIZE(tokens) - 1)
                     ntokens++;
                 dbg_error_msg("L[%d]='%s'", ntokens, s);
                 s = strtok_r(NULL, delims, &tokstate);
             }
             tokens[ntokens] = NULL;
             dbg_error_msg("EMPTYLINE, ntokens:%d", ntokens);
             if (ntokens == 0)
                 break;
         }
         /* Is it multipart? */
         type = find_token(tokens, "Content-Type:", "text/plain");
         dbg_error_msg("TYPE:'%s'", type);
         if (0 == strncasecmp(type, "multipart/", 10)) {
             /* Yes, recurse */
             if (strcasecmp(type + 10, "mixed") != 0)
                 bb_error_msg_and_die("no support of content type '%s'", type);
             parse(xfind_token(tokens, "boundary"), argv);
         } else {
             /* No, process one non-multipart section */
             char *end;
             pid_t pid = pid;
             FILE *fp;
             const char *charset = find_token(tokens, "charset", CONFIG_FEATURE_MIME_CHARSET);
             const char *encoding = find_token(tokens, "Content-Transfer-Encoding:", "7bit");
             /* Compose target filename */
             char *filename = (char *)find_token(tokens, "filename", NULL);
             if (!filename)
                 filename = xasprintf(uniq, monotonic_us());
             else
                 filename = bb_get_last_path_component_strip(xstrdup(filename));
             if (option_mask32 & OPT_X) {
                 int fd[2];
                 /* start external helper */
                 xpipe(fd);
                 pid = vfork();
                 if (0 == pid) {
                     /* child reads from fd[0] */
                     close(fd[1]);
                     xmove_fd(fd[0], STDIN_FILENO);
                     xsetenv("CONTENT_TYPE", type);
                     xsetenv("CHARSET", charset);
                     xsetenv("ENCODING", encoding);
                     xsetenv("FILENAME", filename);
                     BB_EXECVP_or_die(argv);
                 }
                 /* parent will write to fd[1] */
                 close(fd[0]);
                 fp = xfdopen_for_write(fd[1]);
                 signal(SIGPIPE, SIG_IGN);
             } else {
                 /* write to file */
                 char *fname = xasprintf("%s%s", *argv, filename);
                 fp = xfopen_for_write(fname);
                 free(fname);
             }
             free(filename);
             /* write to fp */
             end = NULL;
             if (0 == strcasecmp(encoding, "base64")) {
                 read_base64(stdin, fp, '-');
             } else
             if (0 != strcasecmp(encoding, "7bit")
              && 0 != strcasecmp(encoding, "8bit")
             ) {
                 /* quoted-printable, binary, user-defined are unsupported so far */
                 bb_error_msg_and_die("encoding '%s' not supported", encoding);
             } else {
                 /* plain 7bit or 8bit */
                 while ((end = xmalloc_fgets(stdin)) != NULL) {
                     if ('-' == end[0]
                      && '-' == end[1]
                      && strncmp(end + 2, boundary, boundary_len) == 0
                     ) {
                         break;
                     }
                     fputs(end, fp);
                 }
             }
             fclose(fp);
             /* Wait for child */
             if (option_mask32 & OPT_X) {
                 int rc;
                 signal(SIGPIPE, SIG_DFL);
                 rc = (wait4pid(pid) & 0xff);
                 if (rc != 0)
                     return rc + 20;
             }
             /* Multipart ended? */
             if (end && '-' == end[2 + boundary_len] && '-' == end[2 + boundary_len + 1]) {
                 dbg_error_msg("FINISHED MPART:'%s'", end);
                 break;
             }
             dbg_error_msg("FINISHED:'%s'", end);
             free(end);
         } /* end of "handle one non-multipart block" */
         free(header);
     } /* while (1) */
     dbg_error_msg("ENDPARSE[%s]", boundary);
     return EXIT_SUCCESS;
 }
References argv, ARRAY_SIZE, bb_error_msg_and_die(), BB_EXECVP_or_die(), bb_get_last_path_component_strip(), boundary, close(), dbg_error_msg, end, EOF, EXIT_SUCCESS, fclose(), fd, fgetc, filename, find_token(), fname, fputs, free, getpid(), monotonic_us(), NULL, OPT_X, option_mask32, p, pid, rc, read_base64(), s, SIG_DFL, SIG_IGN, signal, SIGPIPE, sprintf(), stdin, STDIN_FILENO, strcasecmp, strchr(), strlen(), strncasecmp, strncmp(), strtok_r(), type, vfork(), wait4pid(), xasprintf(), xfdopen_for_write(), xfind_token(), xfopen_for_write(), xmalloc_fgets(), xmove_fd(), xpipe(), xrealloc, xsetenv(), and xstrdup().
Referenced by reformime_main().
reformime_main()
int reformime_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 276 of file reformime.c.
 {
     unsigned opts;
     const char *opt_prefix = "";
     INIT_G();
     // parse options
     // N.B. only -x and -X are supported so far
     opts = getopt32(argv, "^"
         "x:X" IF_FEATURE_REFORMIME_COMPAT("deis:r:c:m:*h:o:O:")
         "\0" "x--X:X--x",
         &opt_prefix
         IF_FEATURE_REFORMIME_COMPAT(, NULL, NULL, &G.opt_charset, NULL, NULL, NULL, NULL)
     );
     argv += optind;
     return parse("", (opts & OPT_X) ? argv : (char **)&opt_prefix);
 }
References argv, G(), getopt32(), INIT_G, NULL, OPT_X, optind, and parse().
xfind_token()
static const char* xfind_token (const char *const string_array[], const char * key) static
Definition at line 49 of file reformime.c.
 {
     const char *r = find_token(string_array, key, NULL);
     if (r)
         return r;
     bb_error_msg_and_die("not found: '%s'", key);
 }
References bb_error_msg_and_die(), find_token(), and NULL.
Referenced by parse().