Fennix Kernel: Kernel/Architecture/i386/Bootstrap/Multiboot/Multiboot.cpp File Reference
Multiboot.cpp File Reference
#include <types.h>
#include <memory.hpp>
#include "../../../../kernel.h"
Macros
#define MULTIBOOT_HEADER_MAGIC 0x1BADB002
#define MULTIBOOT_BOOTLOADER_MAGIC 0x2BADB002
#define MULTIBOOT2_HEADER_MAGIC 0xe85250d6
#define MULTIBOOT2_BOOTLOADER_MAGIC 0x36d76289
Functions
void multiboot_parse (BootInfo &mb2binfo, uintptr_t Magic, uintptr_t Info)
void multiboot2_parse (BootInfo &mb2binfo, uintptr_t Magic, uintptr_t Info)
EXTERNC void multiboot_main (uintptr_t Magic, uintptr_t Info)
Macro Definition Documentation
MULTIBOOT2_BOOTLOADER_MAGIC
#define MULTIBOOT2_BOOTLOADER_MAGIC 0x36d76289
Definition at line 27 of file Multiboot.cpp.
MULTIBOOT2_HEADER_MAGIC
#define MULTIBOOT2_HEADER_MAGIC 0xe85250d6
Definition at line 26 of file Multiboot.cpp.
MULTIBOOT_BOOTLOADER_MAGIC
#define MULTIBOOT_BOOTLOADER_MAGIC 0x2BADB002
Definition at line 25 of file Multiboot.cpp.
MULTIBOOT_HEADER_MAGIC
#define MULTIBOOT_HEADER_MAGIC 0x1BADB002
Definition at line 24 of file Multiboot.cpp.
Function Documentation
multiboot2_parse()
void multiboot2_parse (BootInfo & mb2binfo, uintptr_t Magic, uintptr_t Info)
Definition at line 25 of file Multiboot2Parse.cpp.
 {
     auto InfoAddress = Info;
     for (auto Tag = (struct multiboot_tag *)((uint8_t *)InfoAddress + 8);
          ;
          Tag = (struct multiboot_tag *)((multiboot_uint8_t *)Tag + ((Tag->size + 7) & ~7)))
     {
         if (Tag->type == MULTIBOOT_TAG_TYPE_END)
         {
             debug("End of multiboot2 tags");
             break;
         }
         switch (Tag->type)
         {
         case MULTIBOOT_TAG_TYPE_CMDLINE:
         {
             strncpy(mb2binfo.Kernel.CommandLine,
                     ((multiboot_tag_string *)Tag)->string,
                     strlen(((multiboot_tag_string *)Tag)->string));
             debug("Kernel command line: %s", mb2binfo.Kernel.CommandLine);
             break;
         }
         case MULTIBOOT_TAG_TYPE_BOOT_LOADER_NAME:
         {
             strncpy(mb2binfo.Bootloader.Name,
                     ((multiboot_tag_string *)Tag)->string,
                     strlen(((multiboot_tag_string *)Tag)->string));
             debug("Bootloader name: %s", mb2binfo.Bootloader.Name);
             break;
         }
         case MULTIBOOT_TAG_TYPE_MODULE:
         {
             multiboot_tag_module *module = (multiboot_tag_module *)Tag;
             static int module_count = 0;
             mb2binfo.Modules[module_count].Address = (void *)(uint64_t)module->mod_start;
             mb2binfo.Modules[module_count].Size = module->mod_end - module->mod_start;
             strncpy(mb2binfo.Modules[module_count].Path, "(null)", 6);
             strncpy(mb2binfo.Modules[module_count].CommandLine, module->cmdline,
                     strlen(module->cmdline));
             debug("Module: %s", mb2binfo.Modules[module_count].Path);
             module_count++;
             break;
         }
         case MULTIBOOT_TAG_TYPE_BASIC_MEMINFO:
         {
             multiboot_tag_basic_meminfo *meminfo = (multiboot_tag_basic_meminfo *)Tag;
             fixme("basic_meminfo->[mem_lower: %#x, mem_upper: %#x]",
                   meminfo->mem_lower, meminfo->mem_upper);
             break;
         }
         case MULTIBOOT_TAG_TYPE_BOOTDEV:
         {
             multiboot_tag_bootdev *bootdev = (multiboot_tag_bootdev *)Tag;
             fixme("bootdev->[biosdev: %#x, slice: %#x, part: %#x]",
                   bootdev->biosdev, bootdev->slice, bootdev->part);
             break;
         }
         case MULTIBOOT_TAG_TYPE_MMAP:
         {
             multiboot_tag_mmap *mmap = (multiboot_tag_mmap *)Tag;
             size_t EntryCount = mmap->size / sizeof(multiboot_mmap_entry);
             mb2binfo.Memory.Entries = EntryCount;
             for (uint32_t i = 0; i < EntryCount; i++)
             {
                 if (i > MAX_MEMORY_ENTRIES)
                 {
                     warn("Too many memory entries, skipping the rest...");
                     break;
                 }
                 multiboot_mmap_entry entry = mmap->entries[i];
                 mb2binfo.Memory.Size += entry.len;
                 switch (entry.type)
                 {
                 case MULTIBOOT_MEMORY_AVAILABLE:
                     mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                     mb2binfo.Memory.Entry[i].Length = entry.len;
                     mb2binfo.Memory.Entry[i].Type = Usable;
                     break;
                 case MULTIBOOT_MEMORY_RESERVED:
                     mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                     mb2binfo.Memory.Entry[i].Length = entry.len;
                     mb2binfo.Memory.Entry[i].Type = Reserved;
                     break;
                 case MULTIBOOT_MEMORY_ACPI_RECLAIMABLE:
                     mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                     mb2binfo.Memory.Entry[i].Length = entry.len;
                     mb2binfo.Memory.Entry[i].Type = ACPIReclaimable;
                     break;
                 case MULTIBOOT_MEMORY_NVS:
                     mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                     mb2binfo.Memory.Entry[i].Length = entry.len;
                     mb2binfo.Memory.Entry[i].Type = ACPINVS;
                     break;
                 case MULTIBOOT_MEMORY_BADRAM:
                     mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                     mb2binfo.Memory.Entry[i].Length = entry.len;
                     mb2binfo.Memory.Entry[i].Type = BadMemory;
                     break;
                 default:
                     mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                     mb2binfo.Memory.Entry[i].Length = entry.len;
                     mb2binfo.Memory.Entry[i].Type = Unknown;
                     break;
                 }
                 debug("Memory entry: [BaseAddress: %#x, Length: %#x, Type: %d]",
                       mb2binfo.Memory.Entry[i].BaseAddress,
                       mb2binfo.Memory.Entry[i].Length,
                       mb2binfo.Memory.Entry[i].Type);
             }
             break;
         }
         case MULTIBOOT_TAG_TYPE_VBE:
         {
             multiboot_tag_vbe *vbe = (multiboot_tag_vbe *)Tag;
             fixme("vbe->[vbe_mode: %#x, vbe_interface_seg: %#x, vbe_interface_off: %#x, vbe_interface_len: %#x]",
                   vbe->vbe_mode, vbe->vbe_interface_seg, vbe->vbe_interface_off, vbe->vbe_interface_len);
             break;
         }
         case MULTIBOOT_TAG_TYPE_FRAMEBUFFER:
         {
             multiboot_tag_framebuffer *fb = (multiboot_tag_framebuffer *)Tag;
             static int fb_count = 0;
             mb2binfo.Framebuffer[fb_count].BaseAddress = (void *)fb->common.framebuffer_addr;
             mb2binfo.Framebuffer[fb_count].Width = fb->common.framebuffer_width;
             mb2binfo.Framebuffer[fb_count].Height = fb->common.framebuffer_height;
             mb2binfo.Framebuffer[fb_count].Pitch = fb->common.framebuffer_pitch;
             mb2binfo.Framebuffer[fb_count].BitsPerPixel = fb->common.framebuffer_bpp;
             switch (fb->common.framebuffer_type)
             {
             case MULTIBOOT_FRAMEBUFFER_TYPE_INDEXED:
             {
                 mb2binfo.Framebuffer[fb_count].Type = Indexed;
                 break;
             }
             case MULTIBOOT_FRAMEBUFFER_TYPE_RGB:
             {
                 mb2binfo.Framebuffer[fb_count].Type = RGB;
                 mb2binfo.Framebuffer[fb_count].RedMaskSize = fb->framebuffer_red_mask_size;
                 mb2binfo.Framebuffer[fb_count].RedMaskShift = fb->framebuffer_red_field_position;
                 mb2binfo.Framebuffer[fb_count].GreenMaskSize = fb->framebuffer_green_mask_size;
                 mb2binfo.Framebuffer[fb_count].GreenMaskShift = fb->framebuffer_green_field_position;
                 mb2binfo.Framebuffer[fb_count].BlueMaskSize = fb->framebuffer_blue_mask_size;
                 mb2binfo.Framebuffer[fb_count].BlueMaskShift = fb->framebuffer_blue_field_position;
                 break;
             }
             case MULTIBOOT_FRAMEBUFFER_TYPE_EGA_TEXT:
             {
                 mb2binfo.Framebuffer[fb_count].Type = EGA;
                 break;
             }
             default:
             {
                 mb2binfo.Framebuffer[fb_count].Type = Unknown_Framebuffer_Type;
                 break;
             }
             }
             debug("Framebuffer %d: %dx%d %d bpp", fb_count, fb->common.framebuffer_width, fb->common.framebuffer_height, fb->common.framebuffer_bpp);
             debug("More info:\nAddress: %p\nPitch: %d\nMemoryModel: %d\nRedMaskSize: %d\nRedMaskShift: %d\nGreenMaskSize: %d\nGreenMaskShift: %d\nBlueMaskSize: %d\nBlueMaskShift: %d",
                   fb->common.framebuffer_addr, fb->common.framebuffer_pitch, fb->common.framebuffer_type,
                   fb->framebuffer_red_mask_size, fb->framebuffer_red_field_position, fb->framebuffer_green_mask_size,
                   fb->framebuffer_green_field_position, fb->framebuffer_blue_mask_size, fb->framebuffer_blue_field_position);
             fb_count++;
             break;
         }
         case MULTIBOOT_TAG_TYPE_ELF_SECTIONS:
         {
             multiboot_tag_elf_sections *elf = (multiboot_tag_elf_sections *)Tag;
             mb2binfo.Kernel.Symbols.Num = elf->num;
             mb2binfo.Kernel.Symbols.EntSize = elf->entsize;
             mb2binfo.Kernel.Symbols.Shndx = elf->shndx;
             mb2binfo.Kernel.Symbols.Sections = r_cst(uintptr_t, elf->sections);
             break;
         }
         case MULTIBOOT_TAG_TYPE_APM:
         {
             multiboot_tag_apm *apm = (multiboot_tag_apm *)Tag;
             fixme("apm->[version: %d, cseg: %d, offset: %d, cseg_16: %d, dseg: %d, flags: %d, cseg_len: %d, cseg_16_len: %d, dseg_len: %d]",
                   apm->version, apm->cseg, apm->offset, apm->cseg_16, apm->dseg, apm->flags, apm->cseg_len, apm->cseg_16_len, apm->dseg_len);
             break;
         }
         case MULTIBOOT_TAG_TYPE_EFI32:
         {
             multiboot_tag_efi32 *efi32 = (multiboot_tag_efi32 *)Tag;
             fixme("efi32->[pointer: %p, size: %d]", efi32->pointer, efi32->size);
             break;
         }
         case MULTIBOOT_TAG_TYPE_EFI64:
         {
             multiboot_tag_efi64 *efi64 = (multiboot_tag_efi64 *)Tag;
             fixme("efi64->[pointer: %p, size: %d]", efi64->pointer, efi64->size);
             break;
         }
         case MULTIBOOT_TAG_TYPE_SMBIOS:
         {
             multiboot_tag_smbios *smbios = (multiboot_tag_smbios *)Tag;
             fixme("smbios->[major: %d, minor: %d]", smbios->major, smbios->minor);
             break;
         }
         case MULTIBOOT_TAG_TYPE_ACPI_OLD:
         {
             mb2binfo.RSDP = (BootInfo::RSDPInfo *)((multiboot_tag_old_acpi *)Tag)->rsdp;
             debug("OLD ACPI RSDP: %p", mb2binfo.RSDP);
             break;
         }
         case MULTIBOOT_TAG_TYPE_ACPI_NEW:
         {
             mb2binfo.RSDP = (BootInfo::RSDPInfo *)((multiboot_tag_new_acpi *)Tag)->rsdp;
             debug("NEW ACPI RSDP: %p", mb2binfo.RSDP);
             break;
         }
         case MULTIBOOT_TAG_TYPE_NETWORK:
         {
             multiboot_tag_network *net = (multiboot_tag_network *)Tag;
             fixme("network->[dhcpack: %p]", net->dhcpack);
             break;
         }
         case MULTIBOOT_TAG_TYPE_EFI_MMAP:
         {
             multiboot_tag_efi_mmap *efi_mmap = (multiboot_tag_efi_mmap *)Tag;
             fixme("efi_mmap->[descr_size: %d, descr_vers: %d, efi_mmap: %p]",
                   efi_mmap->descr_size, efi_mmap->descr_vers, efi_mmap->efi_mmap);
             break;
         }
         case MULTIBOOT_TAG_TYPE_EFI_BS:
         {
             fixme("efi_bs->[%p] (unknown structure)", Tag);
             break;
         }
         case MULTIBOOT_TAG_TYPE_EFI32_IH:
         {
             multiboot_tag_efi32_ih *efi32_ih = (multiboot_tag_efi32_ih *)Tag;
             fixme("efi32_ih->[pointer: %p]", efi32_ih->pointer);
             break;
         }
         case MULTIBOOT_TAG_TYPE_EFI64_IH:
         {
             multiboot_tag_efi64_ih *efi64_ih = (multiboot_tag_efi64_ih *)Tag;
             fixme("efi64_ih->[pointer: %p]", efi64_ih->pointer);
             break;
         }
         case MULTIBOOT_TAG_TYPE_LOAD_BASE_ADDR:
         {
             multiboot_tag_load_base_addr *load_base_addr = (multiboot_tag_load_base_addr *)Tag;
             mb2binfo.Kernel.PhysicalBase = (void *)(uint64_t)load_base_addr->load_base_addr;
             mb2binfo.Kernel.VirtualBase = (void *)(uint64_t)(load_base_addr->load_base_addr + 0xFFFFFFFF80000000);
             mb2binfo.Kernel.Size = ((uint64_t)&_kernel_end - (uint64_t)&_kernel_start) + ((uint64_t)&_bootstrap_end - (uint64_t)&_bootstrap_start);
             debug("Kernel base: %p (physical) %p (virtual)", mb2binfo.Kernel.PhysicalBase, mb2binfo.Kernel.VirtualBase);
             break;
         }
         default:
         {
             error("Unknown multiboot2 tag type: %d", Tag->type);
             break;
         }
         }
     }
     Entry(&mb2binfo);
 }
References _kernel_end, _kernel_start, ACPINVS, ACPIReclaimable, multiboot_mmap_entry::addr, BootInfo::ModuleInfo::Address, BadMemory, BootInfo::FramebufferInfo::BaseAddress, BootInfo::MemoryInfo::MemoryEntryInfo::BaseAddress, multiboot_tag_bootdev::biosdev, BootInfo::FramebufferInfo::BitsPerPixel, BootInfo::FramebufferInfo::BlueMaskShift, BootInfo::FramebufferInfo::BlueMaskSize, BootInfo::Bootloader, multiboot_tag_module::cmdline, BootInfo::ModuleInfo::CommandLine, BootInfo::KernelInfo::CommandLine, multiboot_tag_framebuffer::common, multiboot_tag_apm::cseg, multiboot_tag_apm::cseg_16, multiboot_tag_apm::cseg_16_len, multiboot_tag_apm::cseg_len, debug, multiboot_tag_efi_mmap::descr_size, multiboot_tag_efi_mmap::descr_vers, multiboot_tag_network::dhcpack, multiboot_tag_apm::dseg, multiboot_tag_apm::dseg_len, multiboot_tag_efi_mmap::efi_mmap, EGA, BootInfo::MemoryInfo::Entries, multiboot_tag_mmap::entries, Entry(), BootInfo::MemoryInfo::Entry, BootInfo::KernelInfo::KernelSymbolInfo::EntSize, multiboot_tag_elf_sections::entsize, error, fixme, multiboot_tag_apm::flags, BootInfo::Framebuffer, multiboot_tag_framebuffer_common::framebuffer_addr, multiboot_tag_framebuffer_common::framebuffer_bpp, multiboot_tag_framebuffer_common::framebuffer_height, multiboot_tag_framebuffer_common::framebuffer_pitch, multiboot_tag_framebuffer_common::framebuffer_type, multiboot_tag_framebuffer_common::framebuffer_width, BootInfo::FramebufferInfo::GreenMaskShift, BootInfo::FramebufferInfo::GreenMaskSize, BootInfo::FramebufferInfo::Height, Indexed, Info, BootInfo::Kernel, multiboot_mmap_entry::len, BootInfo::MemoryInfo::MemoryEntryInfo::Length, multiboot_tag_load_base_addr::load_base_addr, Magic, multiboot_tag_smbios::major, MAX_MEMORY_ENTRIES, multiboot_tag_basic_meminfo::mem_lower, multiboot_tag_basic_meminfo::mem_upper, BootInfo::Memory, multiboot_tag_smbios::minor, multiboot_tag_module::mod_end, multiboot_tag_module::mod_start, BootInfo::Modules, MULTIBOOT2_BOOTLOADER_MAGIC, MULTIBOOT_FRAMEBUFFER_TYPE_EGA_TEXT, MULTIBOOT_FRAMEBUFFER_TYPE_INDEXED, MULTIBOOT_FRAMEBUFFER_TYPE_RGB, MULTIBOOT_MEMORY_ACPI_RECLAIMABLE, MULTIBOOT_MEMORY_AVAILABLE, MULTIBOOT_MEMORY_BADRAM, MULTIBOOT_MEMORY_NVS, MULTIBOOT_MEMORY_RESERVED, MULTIBOOT_TAG_TYPE_ACPI_NEW, MULTIBOOT_TAG_TYPE_ACPI_OLD, MULTIBOOT_TAG_TYPE_APM, MULTIBOOT_TAG_TYPE_BASIC_MEMINFO, MULTIBOOT_TAG_TYPE_BOOT_LOADER_NAME, MULTIBOOT_TAG_TYPE_BOOTDEV, MULTIBOOT_TAG_TYPE_CMDLINE, MULTIBOOT_TAG_TYPE_EFI32, MULTIBOOT_TAG_TYPE_EFI32_IH, MULTIBOOT_TAG_TYPE_EFI64, MULTIBOOT_TAG_TYPE_EFI64_IH, MULTIBOOT_TAG_TYPE_EFI_BS, MULTIBOOT_TAG_TYPE_EFI_MMAP, MULTIBOOT_TAG_TYPE_ELF_SECTIONS, MULTIBOOT_TAG_TYPE_END, MULTIBOOT_TAG_TYPE_FRAMEBUFFER, MULTIBOOT_TAG_TYPE_LOAD_BASE_ADDR, MULTIBOOT_TAG_TYPE_MMAP, MULTIBOOT_TAG_TYPE_MODULE, MULTIBOOT_TAG_TYPE_NETWORK, MULTIBOOT_TAG_TYPE_SMBIOS, MULTIBOOT_TAG_TYPE_VBE, BootInfo::BootloaderInfo::Name, NULL, BootInfo::KernelInfo::KernelSymbolInfo::Num, multiboot_tag_elf_sections::num, multiboot_tag_apm::offset, multiboot_tag_bootdev::part, BootInfo::ModuleInfo::Path, BootInfo::KernelInfo::PhysicalBase, BootInfo::FramebufferInfo::Pitch, multiboot_tag_efi32::pointer, multiboot_tag_efi64::pointer, multiboot_tag_efi32_ih::pointer, multiboot_tag_efi64_ih::pointer, BootInfo::FramebufferInfo::RedMaskShift, BootInfo::FramebufferInfo::RedMaskSize, Reserved, RGB, BootInfo::KernelInfo::KernelSymbolInfo::Sections, multiboot_tag_elf_sections::sections, BootInfo::KernelInfo::KernelSymbolInfo::Shndx, multiboot_tag_elf_sections::shndx, BootInfo::MemoryInfo::Size, BootInfo::ModuleInfo::Size, BootInfo::KernelInfo::Size, multiboot_tag_mmap::size, multiboot_tag_efi32::size, multiboot_tag_efi64::size, multiboot_tag_bootdev::slice, strlen(), strncpy(), BootInfo::KernelInfo::Symbols, BootInfo::MemoryInfo::MemoryEntryInfo::Type, BootInfo::FramebufferInfo::Type, multiboot_mmap_entry::type, Unknown, Unknown_Framebuffer_Type, Usable, multiboot_tag_vbe::vbe_interface_len, multiboot_tag_vbe::vbe_interface_off, multiboot_tag_vbe::vbe_interface_seg, multiboot_tag_vbe::vbe_mode, multiboot_tag_apm::version, BootInfo::KernelInfo::VirtualBase, warn, and BootInfo::FramebufferInfo::Width.
multiboot_main()
EXTERNC void multiboot_main (uintptr_t Magic, uintptr_t Info)
Definition at line 32 of file Multiboot.cpp.
 {
     BootInfo mb2binfo{};
     if (Info == NULL || Magic == NULL)
     {
         if (Magic == NULL)
             error("Multiboot magic is NULL");
         if (Info == NULL)
             error("Multiboot info is NULL");
         CPU::Stop();
     }
     else if (Magic == MULTIBOOT_BOOTLOADER_MAGIC)
         multiboot_parse(mb2binfo, Magic, Info);
     else if (Magic == MULTIBOOT2_BOOTLOADER_MAGIC)
         multiboot2_parse(mb2binfo, Magic, Info);
     else
     {
         error("Unknown multiboot magic %#x", Magic);
         CPU::Stop();
     }
 }
References error, Info, Magic, MULTIBOOT2_BOOTLOADER_MAGIC, multiboot2_parse(), MULTIBOOT_BOOTLOADER_MAGIC, multiboot_parse(), and NULL.
multiboot_parse()
void multiboot_parse (BootInfo & mb2binfo, uintptr_t Magic, uintptr_t Info)
Definition at line 25 of file Multiboot1Parse.cpp.
 {
     multiboot_info *InfoAddress = r_cst(multiboot_info *, Info);
     if (InfoAddress->flags & MULTIBOOT_INFO_MEMORY)
     {
         fixme("mem_lower: %#x, mem_upper: %#x",
               InfoAddress->mem_lower, InfoAddress->mem_upper);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_BOOTDEV)
     {
         fixme("boot_device: %#x",
               InfoAddress->boot_device);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_CMDLINE)
     {
         strncpy(mb2binfo.Kernel.CommandLine,
                 r_cst(const char *, InfoAddress->cmdline),
                 strlen(r_cst(const char *, InfoAddress->cmdline)));
         debug("Kernel command line: %s", mb2binfo.Kernel.CommandLine);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_MODS)
     {
         multiboot_mod_list *module = r_cst(multiboot_mod_list *, InfoAddress->mods_addr);
         for (size_t i = 0; i < InfoAddress->mods_count; i++)
         {
             if (i > MAX_MODULES)
             {
                 warn("Too many modules, skipping the rest...");
                 break;
             }
             mb2binfo.Modules[i].Address = (void *)(uint64_t)module[i].mod_start;
             mb2binfo.Modules[i].Size = module[i].mod_end - module[i].mod_start;
             strncpy(mb2binfo.Modules[i].Path, "(null)", 6);
             strncpy(mb2binfo.Modules[i].CommandLine, r_cst(const char *, module[i].cmdline),
                     strlen(r_cst(const char *, module[i].cmdline)));
             debug("Module: %s", mb2binfo.Modules[i].Path);
         }
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_AOUT_SYMS)
     {
         fixme("aout_sym: [tabsize: %#x, strsize: %#x, addr: %#x, reserved: %#x]",
               InfoAddress->u.aout_sym.tabsize, InfoAddress->u.aout_sym.strsize,
               InfoAddress->u.aout_sym.addr, InfoAddress->u.aout_sym.reserved);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_ELF_SHDR)
     {
         mb2binfo.Kernel.Symbols.Num = InfoAddress->u.elf_sec.num;
         mb2binfo.Kernel.Symbols.EntSize = InfoAddress->u.elf_sec.size;
         mb2binfo.Kernel.Symbols.Shndx = InfoAddress->u.elf_sec.shndx;
         mb2binfo.Kernel.Symbols.Sections = s_cst(uintptr_t, InfoAddress->u.elf_sec.addr);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_MEM_MAP)
     {
         mb2binfo.Memory.Entries = InfoAddress->mmap_length / sizeof(multiboot_mmap_entry);
         for (uint32_t i = 0; i < mb2binfo.Memory.Entries; i++)
         {
             if (i > MAX_MEMORY_ENTRIES)
             {
                 warn("Too many memory entries, skipping the rest...");
                 break;
             }
             multiboot_mmap_entry entry = r_cst(multiboot_mmap_entry *, InfoAddress->mmap_addr)[i];
             mb2binfo.Memory.Size += entry.len;
             switch (entry.type)
             {
             case MULTIBOOT_MEMORY_AVAILABLE:
                 mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                 mb2binfo.Memory.Entry[i].Length = entry.len;
                 mb2binfo.Memory.Entry[i].Type = Usable;
                 break;
             case MULTIBOOT_MEMORY_RESERVED:
                 mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                 mb2binfo.Memory.Entry[i].Length = entry.len;
                 mb2binfo.Memory.Entry[i].Type = Reserved;
                 break;
             case MULTIBOOT_MEMORY_ACPI_RECLAIMABLE:
                 mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                 mb2binfo.Memory.Entry[i].Length = entry.len;
                 mb2binfo.Memory.Entry[i].Type = ACPIReclaimable;
                 break;
             case MULTIBOOT_MEMORY_NVS:
                 mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                 mb2binfo.Memory.Entry[i].Length = entry.len;
                 mb2binfo.Memory.Entry[i].Type = ACPINVS;
                 break;
             case MULTIBOOT_MEMORY_BADRAM:
                 mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                 mb2binfo.Memory.Entry[i].Length = entry.len;
                 mb2binfo.Memory.Entry[i].Type = BadMemory;
                 break;
             default:
                 mb2binfo.Memory.Entry[i].BaseAddress = (void *)entry.addr;
                 mb2binfo.Memory.Entry[i].Length = entry.len;
                 mb2binfo.Memory.Entry[i].Type = Unknown;
                 break;
             }
             debug("Memory entry: [BaseAddress: %#x, Length: %#x, Type: %d]",
                   mb2binfo.Memory.Entry[i].BaseAddress,
                   mb2binfo.Memory.Entry[i].Length,
                   mb2binfo.Memory.Entry[i].Type);
         }
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_DRIVE_INFO)
     {
         fixme("drives_length: %d, drives_addr: %#x",
               InfoAddress->drives_length, InfoAddress->drives_addr);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_CONFIG_TABLE)
     {
         fixme("config_table: %#x",
               InfoAddress->config_table);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_BOOT_LOADER_NAME)
     {
         strncpy(mb2binfo.Bootloader.Name,
                 r_cst(const char *, InfoAddress->boot_loader_name),
                 strlen(r_cst(const char *, InfoAddress->boot_loader_name)));
         debug("Bootloader name: %s", mb2binfo.Bootloader.Name);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_APM_TABLE)
     {
         fixme("apm_table: %#x",
               InfoAddress->apm_table);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_VBE_INFO)
     {
         fixme("vbe_control_info: %#x, vbe_mode_info: %#x, vbe_mode: %#x, vbe_interface_seg: %#x, vbe_interface_off: %#x, vbe_interface_len: %#x",
               InfoAddress->vbe_control_info, InfoAddress->vbe_mode_info,
               InfoAddress->vbe_mode, InfoAddress->vbe_interface_seg,
               InfoAddress->vbe_interface_off, InfoAddress->vbe_interface_len);
     }
     if (InfoAddress->flags & MULTIBOOT_INFO_FRAMEBUFFER_INFO)
     {
         static int fb_count = 0;
         mb2binfo.Framebuffer[fb_count].BaseAddress = (void *)InfoAddress->framebuffer_addr;
         mb2binfo.Framebuffer[fb_count].Width = InfoAddress->framebuffer_width;
         mb2binfo.Framebuffer[fb_count].Height = InfoAddress->framebuffer_height;
         mb2binfo.Framebuffer[fb_count].Pitch = InfoAddress->framebuffer_pitch;
         mb2binfo.Framebuffer[fb_count].BitsPerPixel = InfoAddress->framebuffer_bpp;
         switch (InfoAddress->framebuffer_type)
         {
         case MULTIBOOT_FRAMEBUFFER_TYPE_INDEXED:
         {
             mb2binfo.Framebuffer[fb_count].Type = Indexed;
             break;
         }
         case MULTIBOOT_FRAMEBUFFER_TYPE_RGB:
         {
             mb2binfo.Framebuffer[fb_count].Type = RGB;
             mb2binfo.Framebuffer[fb_count].RedMaskSize = InfoAddress->framebuffer_red_mask_size;
             mb2binfo.Framebuffer[fb_count].RedMaskShift = InfoAddress->framebuffer_red_field_position;
             mb2binfo.Framebuffer[fb_count].GreenMaskSize = InfoAddress->framebuffer_green_mask_size;
             mb2binfo.Framebuffer[fb_count].GreenMaskShift = InfoAddress->framebuffer_green_field_position;
             mb2binfo.Framebuffer[fb_count].BlueMaskSize = InfoAddress->framebuffer_blue_mask_size;
             mb2binfo.Framebuffer[fb_count].BlueMaskShift = InfoAddress->framebuffer_blue_field_position;
             break;
         }
         case MULTIBOOT_FRAMEBUFFER_TYPE_EGA_TEXT:
         {
             mb2binfo.Framebuffer[fb_count].Type = EGA;
             break;
         }
         default:
         {
             mb2binfo.Framebuffer[fb_count].Type = Unknown_Framebuffer_Type;
             break;
         }
         }
         debug("Framebuffer %d: %dx%d %d bpp",
               fb_count, InfoAddress->framebuffer_width,
               InfoAddress->framebuffer_height,
               InfoAddress->framebuffer_bpp);
         debug("More info:\nAddress: %p\nPitch: %d\nMemoryModel: %d\nRedMaskSize: %d\nRedMaskShift: %d\nGreenMaskSize: %d\nGreenMaskShift: %d\nBlueMaskSize: %d\nBlueMaskShift: %d",
               InfoAddress->framebuffer_addr, InfoAddress->framebuffer_pitch, InfoAddress->framebuffer_type,
               InfoAddress->framebuffer_red_mask_size, InfoAddress->framebuffer_red_field_position, InfoAddress->framebuffer_green_mask_size,
               InfoAddress->framebuffer_green_field_position, InfoAddress->framebuffer_blue_mask_size, InfoAddress->framebuffer_blue_field_position);
     }
     mb2binfo.Kernel.PhysicalBase = (void *)&_bootstrap_start;
     mb2binfo.Kernel.VirtualBase = (void *)(uint64_t)((uint64_t)&_bootstrap_start + 0xFFFFFFFF80000000);
     mb2binfo.Kernel.Size = ((uint64_t)&_kernel_end - (uint64_t)&_kernel_start) + ((uint64_t)&_bootstrap_end - (uint64_t)&_bootstrap_start);
     debug("Kernel base: %p (physical) %p (virtual)", mb2binfo.Kernel.PhysicalBase, mb2binfo.Kernel.VirtualBase);
     Entry(&mb2binfo);
 }
References _kernel_end, _kernel_start, ACPINVS, ACPIReclaimable, multiboot_mmap_entry::addr, BootInfo::ModuleInfo::Address, multiboot_info::apm_table, BadMemory, BootInfo::FramebufferInfo::BaseAddress, BootInfo::MemoryInfo::MemoryEntryInfo::BaseAddress, BootInfo::FramebufferInfo::BitsPerPixel, BootInfo::FramebufferInfo::BlueMaskShift, BootInfo::FramebufferInfo::BlueMaskSize, multiboot_info::boot_device, multiboot_info::boot_loader_name, BootInfo::Bootloader, multiboot_info::cmdline, BootInfo::ModuleInfo::CommandLine, BootInfo::KernelInfo::CommandLine, multiboot_info::config_table, debug, multiboot_info::drives_addr, multiboot_info::drives_length, EGA, BootInfo::MemoryInfo::Entries, Entry(), BootInfo::MemoryInfo::Entry, BootInfo::KernelInfo::KernelSymbolInfo::EntSize, fixme, multiboot_info::flags, BootInfo::Framebuffer, multiboot_info::framebuffer_addr, multiboot_info::framebuffer_bpp, multiboot_info::framebuffer_height, multiboot_info::framebuffer_pitch, multiboot_info::framebuffer_type, multiboot_info::framebuffer_width, BootInfo::FramebufferInfo::GreenMaskShift, BootInfo::FramebufferInfo::GreenMaskSize, BootInfo::FramebufferInfo::Height, Indexed, Info, BootInfo::Kernel, multiboot_mmap_entry::len, BootInfo::MemoryInfo::MemoryEntryInfo::Length, MAX_MEMORY_ENTRIES, MAX_MODULES, multiboot_info::mem_lower, multiboot_info::mem_upper, BootInfo::Memory, multiboot_info::mmap_addr, multiboot_info::mmap_length, multiboot_mod_list::mod_end, multiboot_mod_list::mod_start, multiboot_info::mods_addr, multiboot_info::mods_count, BootInfo::Modules, MULTIBOOT_FRAMEBUFFER_TYPE_EGA_TEXT, MULTIBOOT_FRAMEBUFFER_TYPE_INDEXED, MULTIBOOT_FRAMEBUFFER_TYPE_RGB, MULTIBOOT_INFO_AOUT_SYMS, MULTIBOOT_INFO_APM_TABLE, MULTIBOOT_INFO_BOOT_LOADER_NAME, MULTIBOOT_INFO_BOOTDEV, MULTIBOOT_INFO_CMDLINE, MULTIBOOT_INFO_CONFIG_TABLE, MULTIBOOT_INFO_DRIVE_INFO, MULTIBOOT_INFO_ELF_SHDR, MULTIBOOT_INFO_FRAMEBUFFER_INFO, MULTIBOOT_INFO_MEM_MAP, MULTIBOOT_INFO_MEMORY, MULTIBOOT_INFO_MODS, MULTIBOOT_INFO_VBE_INFO, MULTIBOOT_MEMORY_ACPI_RECLAIMABLE, MULTIBOOT_MEMORY_AVAILABLE, MULTIBOOT_MEMORY_BADRAM, MULTIBOOT_MEMORY_NVS, MULTIBOOT_MEMORY_RESERVED, BootInfo::BootloaderInfo::Name, BootInfo::KernelInfo::KernelSymbolInfo::Num, BootInfo::ModuleInfo::Path, BootInfo::KernelInfo::PhysicalBase, BootInfo::FramebufferInfo::Pitch, BootInfo::FramebufferInfo::RedMaskShift, BootInfo::FramebufferInfo::RedMaskSize, Reserved, RGB, BootInfo::KernelInfo::KernelSymbolInfo::Sections, BootInfo::KernelInfo::KernelSymbolInfo::Shndx, BootInfo::MemoryInfo::Size, BootInfo::ModuleInfo::Size, BootInfo::KernelInfo::Size, strlen(), strncpy(), BootInfo::KernelInfo::Symbols, BootInfo::MemoryInfo::MemoryEntryInfo::Type, BootInfo::FramebufferInfo::Type, multiboot_mmap_entry::type, multiboot_info::u, Unknown, Unknown_Framebuffer_Type, Usable, multiboot_info::vbe_control_info, multiboot_info::vbe_interface_len, multiboot_info::vbe_interface_off, multiboot_info::vbe_interface_seg, multiboot_info::vbe_mode, multiboot_info::vbe_mode_info, BootInfo::KernelInfo::VirtualBase, warn, and BootInfo::FramebufferInfo::Width.