Fennix: Kernel/core/memory/heap_allocators/rpmalloc/rpmalloc.c File Reference
rpmalloc.c File Reference
#include "rpmalloc.h"
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <sys/mman.h>
#include <sched.h>
#include <assert.h>
#include <stdatomic.h>
Data Structures
struct span_t
struct span_cache_t
struct span_large_cache_t
struct heap_size_class_t
struct heap_t
struct size_class_t
struct global_cache_t
Macros
#define HEAP_ARRAY_SIZE 47
Size of heap hashmap.
#define ENABLE_THREAD_CACHE 1
Enable per-thread cache.
#define ENABLE_GLOBAL_CACHE 1
Enable global cache shared between all threads, requires thread cache.
#define ENABLE_VALIDATE_ARGS 1
Enable validation of args to public entry points.
#define ENABLE_STATISTICS 0
Enable statistics collection.
#define ENABLE_ASSERTS 1
Enable asserts.
#define ENABLE_OVERRIDE 0
Override standard library malloc/free and new/delete entry points.
#define ENABLE_PRELOAD 0
Support preloading.
#define DISABLE_UNMAP 0
Disable unmapping memory pages (also enables unlimited cache)
#define ENABLE_UNLIMITED_CACHE 0
Enable unlimited global cache (no unmapping until finalization)
#define ENABLE_ADAPTIVE_THREAD_CACHE 0
Enable adaptive thread cache size based on use heuristics.
#define DEFAULT_SPAN_MAP_COUNT 64
Default number of spans to map in call to map more virtual memory (default values yield 4MiB here)
#define GLOBAL_CACHE_MULTIPLIER 8
Multiplier for global cache.
#define FORCEINLINE inline __attribute__((__always_inline__))
#define PROT_MAX(f) 0
#define MAP_UNINITIALIZED 0
#define RPMALLOC_TOSTRING_M(x) #x
#define RPMALLOC_TOSTRING(x) RPMALLOC_TOSTRING_M(x)
#define rpmalloc_assert(truth, message)
#define EXPECTED(x) __builtin_expect((x), 1)
#define UNEXPECTED(x) __builtin_expect((x), 0)
#define _rpmalloc_stat_inc(counter)
#define _rpmalloc_stat_dec(counter)
#define _rpmalloc_stat_add(counter, value)
#define _rpmalloc_stat_add64(counter, value)
#define _rpmalloc_stat_add_peak(counter, value, peak)
#define _rpmalloc_stat_sub(counter, value)
#define _rpmalloc_stat_inc_alloc(heap, class_idx)
#define _rpmalloc_stat_inc_free(heap, class_idx)
#define SMALL_GRANULARITY 16
Granularity of a small allocation block (must be power of two)
#define SMALL_GRANULARITY_SHIFT 4
Small granularity shift count.
#define SMALL_CLASS_COUNT 65
Number of small block size classes.
#define SMALL_SIZE_LIMIT (SMALL_GRANULARITY * (SMALL_CLASS_COUNT - 1))
Maximum size of a small block.
#define MEDIUM_GRANULARITY 512
Granularity of a medium allocation block.
#define MEDIUM_GRANULARITY_SHIFT 9
Medium granularity shift count.
#define MEDIUM_CLASS_COUNT 61
Number of medium block size classes.
#define SIZE_CLASS_COUNT (SMALL_CLASS_COUNT + MEDIUM_CLASS_COUNT)
Total number of small + medium size classes.
#define LARGE_CLASS_COUNT 63
Number of large block size classes.
#define MEDIUM_SIZE_LIMIT (SMALL_SIZE_LIMIT + (MEDIUM_GRANULARITY * MEDIUM_CLASS_COUNT))
Maximum size of a medium block.
#define LARGE_SIZE_LIMIT ((LARGE_CLASS_COUNT * _memory_span_size) - SPAN_HEADER_SIZE)
Maximum size of a large block.
#define SPAN_HEADER_SIZE 128
Size of a span header (must be a multiple of SMALL_GRANULARITY and a power of two)
#define MAX_THREAD_SPAN_CACHE 400
Number of spans in thread cache.
#define THREAD_SPAN_CACHE_TRANSFER 64
Number of spans to transfer between thread and global cache.
#define MAX_THREAD_SPAN_LARGE_CACHE 100
Number of spans in thread cache for large spans (must be greater than LARGE_CLASS_COUNT / 2)
#define THREAD_SPAN_LARGE_CACHE_TRANSFER 6
Number of spans to transfer between thread and global cache for large spans.
#define MAX_ALLOC_SIZE (((size_t)-1) - _memory_span_size)
Maximum allocation size to avoid integer overflow.
#define pointer_offset(ptr, ofs) (void *)((char *)(ptr) + (ptrdiff_t)(ofs))
#define pointer_diff(first, second) (ptrdiff_t)((const char *)(first) - (const char *)(second))
#define INVALID_POINTER ((void *)((uintptr_t)-1))
#define SIZE_CLASS_LARGE SIZE_CLASS_COUNT
#define SIZE_CLASS_HUGE ((uint32_t)-1)
#define SPAN_FLAG_MASTER 1U
Flag indicating span is the first (master) span of a split superspan.
#define SPAN_FLAG_SUBSPAN 2U
Flag indicating span is a secondary (sub) span of a split superspan.
#define SPAN_FLAG_ALIGNED_BLOCKS 4U
Flag indicating span has blocks with increased alignment.
#define SPAN_FLAG_UNMAPPED_MASTER 8U
Flag indicating an unmapped master span.
#define _memory_default_span_size (64 * 1024)
Default span size (64KiB)
#define _memory_default_span_size_shift 16
#define _memory_default_span_mask (~((uintptr_t)(_memory_span_size - 1)))
#define TLS_MODEL __attribute__((tls_model("initial-exec")))
Current thread heap.
#define _memory_thread_heap (*__memory_thread_heap())
Typedefs
typedef volatile _Atomic(int32_t)
typedef struct heap_t heap_t
A memory heap, per thread.
typedef struct span_t span_t
Span of memory pages.
typedef struct span_list_t span_list_t
Span list.
typedef struct span_active_t span_active_t
Span active data.
typedef struct size_class_t size_class_t
Size class definition.
typedef struct global_cache_t global_cache_t
Global cache.
typedef struct span_cache_t span_cache_t
typedef struct span_large_cache_t span_large_cache_t
typedef struct heap_size_class_t heap_size_class_t
Functions
long __rpmalloc_sysconf (int name)
void * __rpmalloc_mmap (void *addr, size_t length, int prot, int flags, int fd, off_t offset)
int __rpmalloc_munmap (void *addr, size_t length)
int __rpmalloc_posix_madvise (void *addr, size_t length, int advice)
static FORCEINLINE void atomic_store32 (atomic32_t *dst, int32_t val)
static FORCEINLINE int32_t atomic_incr32 (atomic32_t *val)
static FORCEINLINE int32_t atomic_decr32 (atomic32_t *val)
static FORCEINLINE int32_t atomic_add32 (atomic32_t *val, int32_t add)
static FORCEINLINE int atomic_cas32_acquire (atomic32_t *dst, int32_t val, int32_t ref)
static FORCEINLINE void atomic_store32_release (atomic32_t *dst, int32_t val)
static FORCEINLINE int64_t atomic_load64 (atomic64_t *val)
static FORCEINLINE int64_t atomic_add64 (atomic64_t *val, int64_t add)
static FORCEINLINE void * atomic_load_ptr (atomicptr_t *src)
static FORCEINLINE void atomic_store_ptr (atomicptr_t *dst, void *val)
static FORCEINLINE void atomic_store_ptr_release (atomicptr_t *dst, void *val)
static FORCEINLINE void * atomic_exchange_ptr_acquire (atomicptr_t *dst, void *val)
static FORCEINLINE int atomic_cas_ptr (atomicptr_t *dst, void *val, void *ref)
_Static_assert ((SMALL_GRANULARITY &(SMALL_GRANULARITY - 1))==0, "Small granularity must be power of two")
_Static_assert ((SPAN_HEADER_SIZE &(SPAN_HEADER_SIZE - 1))==0, "Span header size must be power of two")
_Static_assert (sizeof(span_t)<=SPAN_HEADER_SIZE, "span size mismatch")
_Static_assert (sizeof(size_class_t)==8, "Size class size mismatch")
heap_t ** __memory_thread_heap (void)
static heap_t * get_thread_heap_raw (void)
static heap_t * get_thread_heap (void)
Get the current thread heap.
uintptr_t __get_tid (void)
static uintptr_t get_thread_id (void)
Fast thread ID.
static void set_thread_heap (heap_t *heap)
Set the current thread heap.
void rpmalloc_set_main_thread (void)
Set main thread ID.
static void _rpmalloc_spin (void)
static void _rpmalloc_set_name (void *address, size_t size)
static void * _rpmalloc_mmap (size_t size, size_t *offset)
Map more virtual memory.
static void _rpmalloc_unmap (void *address, size_t size, size_t offset, size_t release)
Unmap virtual memory.
static void * _rpmalloc_mmap_os (size_t size, size_t *offset)
Default implementation to map new pages to virtual memory.
static void _rpmalloc_unmap_os (void *address, size_t size, size_t offset, size_t release)
Default implementation to unmap pages from virtual memory.
static void _rpmalloc_span_mark_as_subspan_unless_master (span_t *master, span_t *subspan, size_t span_count)
Declare the span to be a subspan and store distance from master span and span count.
static span_t * _rpmalloc_global_get_reserved_spans (size_t span_count)
Use global reserved spans to fulfill a memory map request (reserve size must be checked by caller)
static void _rpmalloc_global_set_reserved_spans (span_t *master, span_t *reserve, size_t reserve_span_count)
Store the given spans as global reserve (must only be called from within new heap allocation, not thread safe)
static void _rpmalloc_span_double_link_list_add (span_t **head, span_t *span)
Add a span to double linked list at the head.
static void _rpmalloc_span_double_link_list_pop_head (span_t **head, span_t *span)
Pop head span from double linked list.
static void _rpmalloc_span_double_link_list_remove (span_t **head, span_t *span)
Remove a span from double linked list.
static void _rpmalloc_heap_cache_insert (heap_t *heap, span_t *span)
Insert a single span into thread heap cache, releasing to global cache if overflow.
static void _rpmalloc_heap_finalize (heap_t *heap)
static void _rpmalloc_heap_set_reserved_spans (heap_t *heap, span_t *master, span_t *reserve, size_t reserve_span_count)
Store the given spans as reserve in the given heap.
static span_t * _rpmalloc_span_map_from_reserve (heap_t *heap, size_t span_count)
Use reserved spans to fulfill a memory map request (reserve size must be checked by caller)
static size_t _rpmalloc_span_align_count (size_t span_count)
Get the aligned number of spans to map in based on wanted count, configured mapping granularity and the page size.
static void _rpmalloc_span_initialize (span_t *span, size_t total_span_count, size_t span_count, size_t align_offset)
Setup a newly mapped span.
static void _rpmalloc_span_unmap (span_t *span)
Unmap memory pages for the given number of spans (or mark as unused if no partial unmappings)
static span_t * _rpmalloc_span_map_aligned_count (heap_t *heap, size_t span_count)
Map an aligned set of spans, taking configured mapping granularity and the page size into account.
static span_t * _rpmalloc_span_map (heap_t *heap, size_t span_count)
Map in memory pages for the given number of spans (or use previously reserved pages)
static void _rpmalloc_span_release_to_cache (heap_t *heap, span_t *span)
Move the span (used for small or medium allocations) to the heap thread cache.
static uint32_t free_list_partial_init (void **list, void **first_block, void *page_start, void *block_start, uint32_t block_count, uint32_t block_size)
static void * _rpmalloc_span_initialize_new (heap_t *heap, heap_size_class_t *heap_size_class, span_t *span, uint32_t class_idx)
Initialize an unused span (from cache or mapped) to be new active span, putting the initial free list in heap class free list.
static void _rpmalloc_span_extract_free_list_deferred (span_t *span)
static int _rpmalloc_span_is_fully_utilized (span_t *span)
static int _rpmalloc_span_finalize (heap_t *heap, size_t iclass, span_t *span, span_t **list_head)
static void _rpmalloc_global_cache_finalize (global_cache_t *cache)
Finalize a global cache.
static void _rpmalloc_global_cache_insert_spans (span_t **span, size_t span_count, size_t count)
static size_t _rpmalloc_global_cache_extract_spans (span_t **span, size_t span_count, size_t count)
static void _rpmalloc_deallocate_huge (span_t *span)
Deallocate the given huge span.
static void _rpmalloc_heap_cache_adopt_deferred (heap_t *heap, span_t **single_span)
Adopt the deferred span cache list, optionally extracting the first single span for immediate re-use.
static void _rpmalloc_heap_unmap (heap_t *heap)
static void _rpmalloc_heap_global_finalize (heap_t *heap)
static span_t * _rpmalloc_heap_thread_cache_extract (heap_t *heap, size_t span_count)
Extract the given number of spans from the different cache levels.
static span_t * _rpmalloc_heap_thread_cache_deferred_extract (heap_t *heap, size_t span_count)
static span_t * _rpmalloc_heap_reserved_extract (heap_t *heap, size_t span_count)
static span_t * _rpmalloc_heap_global_cache_extract (heap_t *heap, size_t span_count)
Extract a span from the global cache.
static void _rpmalloc_inc_span_statistics (heap_t *heap, size_t span_count, uint32_t class_idx)
static span_t * _rpmalloc_heap_extract_new_span (heap_t *heap, heap_size_class_t *heap_size_class, size_t span_count, uint32_t class_idx)
Get a span from one of the cache levels (thread cache, reserved, global cache) or fallback to mapping more memory.
static void _rpmalloc_heap_initialize (heap_t *heap)
static void _rpmalloc_heap_orphan (heap_t *heap, int first_class)
static heap_t * _rpmalloc_heap_allocate_new (void)
Allocate a new heap from newly mapped memory pages.
static heap_t * _rpmalloc_heap_extract_orphan (heap_t **heap_list)
static heap_t * _rpmalloc_heap_allocate (int first_class)
Allocate a new heap, potentially reusing a previously orphaned heap.
static void _rpmalloc_heap_release (void *heapptr, int first_class, int release_cache)
static void _rpmalloc_heap_release_raw (void *heapptr, int release_cache)
static void _rpmalloc_heap_release_raw_fc (void *heapptr)
static void * free_list_pop (void **list)
Pop first block from a free list.
static void * _rpmalloc_allocate_from_heap_fallback (heap_t *heap, heap_size_class_t *heap_size_class, uint32_t class_idx)
Allocate a small/medium sized memory block from the given heap.
static void * _rpmalloc_allocate_small (heap_t *heap, size_t size)
Allocate a small sized memory block from the given heap.
static void * _rpmalloc_allocate_medium (heap_t *heap, size_t size)
Allocate a medium sized memory block from the given heap.
static void * _rpmalloc_allocate_large (heap_t *heap, size_t size)
Allocate a large sized memory block from the given heap.
static void * _rpmalloc_allocate_huge (heap_t *heap, size_t size)
Allocate a huge block by mapping memory pages directly.
static void * _rpmalloc_allocate (heap_t *heap, size_t size)
Allocate a block of the given size.
static void * _rpmalloc_aligned_allocate (heap_t *heap, size_t alignment, size_t size)
static void _rpmalloc_deallocate_direct_small_or_medium (span_t *span, void *block)
Deallocate the given small/medium memory block in the current thread local heap.
static void _rpmalloc_deallocate_defer_free_span (heap_t *heap, span_t *span)
static void _rpmalloc_deallocate_defer_small_or_medium (span_t *span, void *block)
Put the block in the deferred free list of the owning span.
static void _rpmalloc_deallocate_small_or_medium (span_t *span, void *p)
static void _rpmalloc_deallocate_large (span_t *span)
Deallocate the given large memory block to the current heap.
static void _rpmalloc_deallocate (void *p)
Deallocate the given block.
static size_t _rpmalloc_usable_size (void *p)
Get the usable size of the given block.
static void * _rpmalloc_reallocate (heap_t *heap, void *p, size_t size, size_t oldsize, unsigned int flags)
Reallocate the given block to the given size.
static void * _rpmalloc_aligned_reallocate (heap_t *heap, void *ptr, size_t alignment, size_t size, size_t oldsize, unsigned int flags)
static void _rpmalloc_adjust_size_class (size_t iclass)
Adjust and optimize the size class properties for the given class.
int rpmalloc_initialize (void)
Initialize the allocator and setup global data.
int rpmalloc_initialize_config (const rpmalloc_config_t *config)
Initialize allocator with given configuration.
void rpmalloc_finalize (void)
Finalize the allocator.
void rpmalloc_thread_initialize (void)
Initialize thread, assign heap.
void rpmalloc_thread_finalize (int release_caches)
Finalize thread, orphan heap.
int rpmalloc_is_thread_initialized (void)
Query if allocator is initialized for calling thread.
const rpmalloc_config_t * rpmalloc_config (void)
Get allocator configuration.
RPMALLOC_ALLOCATOR void * rpmalloc (size_t size)
Allocate a memory block of at least the given size.
void rpfree (void *ptr)
Free the given memory block.
RPMALLOC_ALLOCATOR void * rpcalloc (size_t num, size_t size)
RPMALLOC_ALLOCATOR void * rprealloc (void *ptr, size_t size)
Reallocate the given block to at least the given size.
RPMALLOC_ALLOCATOR void * rpaligned_realloc (void *ptr, size_t alignment, size_t size, size_t oldsize, unsigned int flags)
Reallocate the given block to at least the given size and alignment,.
RPMALLOC_ALLOCATOR void * rpaligned_alloc (size_t alignment, size_t size)
Allocate a memory block of at least the given size and alignment.
RPMALLOC_ALLOCATOR void * rpaligned_calloc (size_t alignment, size_t num, size_t size)
RPMALLOC_ALLOCATOR void * rpmemalign (size_t alignment, size_t size)
Allocate a memory block of at least the given size and alignment.
int rpposix_memalign (void **memptr, size_t alignment, size_t size)
Allocate a memory block of at least the given size and alignment.
size_t rpmalloc_usable_size (void *ptr)
Query the usable size of the given memory block (from given pointer to the end of block)
void rpmalloc_thread_collect (void)
Perform deferred deallocations pending for the calling thread heap.
void rpmalloc_thread_statistics (rpmalloc_thread_statistics_t *stats)
Get per-thread statistics.
void rpmalloc_global_statistics (rpmalloc_global_statistics_t *stats)
Get global statistics.
void rpmalloc_dump_statistics (void *file)
Dump all statistics in human readable format to file (should be a FILE*)
Variables
static int _rpmalloc_initialized
Initialized flag.
static uintptr_t _rpmalloc_main_thread_id
Main thread ID.
static rpmalloc_config_t _memory_config
Configuration.
static size_t _memory_page_size
Memory page size.
static size_t _memory_page_size_shift
Shift to divide by page size.
static size_t _memory_map_granularity
Granularity at which memory pages are mapped by OS.
static size_t _memory_span_size
Size of a span of memory pages.
static size_t _memory_span_size_shift
Shift to divide by span size.
static uintptr_t _memory_span_mask
Mask to get to start of a memory span.
static size_t _memory_span_map_count
Number of spans to map in each map call.
static size_t _memory_heap_reserve_count
Number of spans to keep reserved in each heap.
static size_class_t _memory_size_class [SIZE_CLASS_COUNT]
Global size classes.
static size_t _memory_medium_size_limit
Run-time size limit of medium blocks.
static atomic32_t _memory_heap_id
Heap ID counter.
static int _memory_huge_pages
Huge page support.
static global_cache_t _memory_span_cache [LARGE_CLASS_COUNT]
Global span cache.
static span_t * _memory_global_reserve
Global reserved spans.
static size_t _memory_global_reserve_count
Global reserved count.
static span_t * _memory_global_reserve_master
Global reserved master.
static heap_t * _memory_heaps [HEAP_ARRAY_SIZE]
All heaps.
static atomic32_t _memory_global_lock
Used to restrict access to mapping memory for huge pages.
static heap_t * _memory_orphan_heaps
Orphaned heaps.
Data Structure Documentation
span_t
struct span_t
Definition at line 430 of file rpmalloc.c.
Data Fields
uint32_t align_offset Alignment offset.
uint32_t block_count Total block count of size class.
uint32_t block_size Size of a block.
uint32_t flags Flags and counters.
void * free_list Free list.
atomicptr_t free_list_deferred Deferred free list.
uint32_t free_list_limit Index of last block initialized in free list.
heap_t * heap Owning heap.
uint32_t list_size Size of deferred free list, or list of spans when part of a cache list.
span_t * next Next span.
uint32_t offset_from_master Offset from master span for subspans.
span_t * prev Previous span.
atomic32_t remaining_spans Remaining span counter, for master spans.
uint32_t size_class Size class.
uint32_t span_count Number of spans.
uint32_t total_spans Total span counter for master spans.
uint32_t used_count Number of used blocks remaining when in partial state.
span_cache_t
struct span_cache_t
Definition at line 469 of file rpmalloc.c.
Data Fields
size_t count
span_t * span[MAX_THREAD_SPAN_CACHE]
span_large_cache_t
struct span_large_cache_t
Definition at line 476 of file rpmalloc.c.
Data Fields
size_t count
span_t * span[MAX_THREAD_SPAN_LARGE_CACHE]
heap_size_class_t
struct heap_size_class_t
Definition at line 483 of file rpmalloc.c.
Data Fields
span_t * cache Early level cache of fully free spans.
void * free_list Free list of active span.
span_t * partial_span Double linked list of partially used spans with free blocks.
heap_t
struct heap_t
Definition at line 496 of file rpmalloc.c.
Data Fields
atomic32_t child_count Child count.
int finalize Finalization state flag.
size_t full_span_count Number of full spans.
int32_t id Heap ID.
heap_t * master_heap Master heap owning the memory pages.
heap_t * next_heap Next heap in id list.
heap_t * next_orphan Next heap in orphan list.
uintptr_t owner_thread Owning thread ID.
char pad[56408]
heap_size_class_t size_class[SIZE_CLASS_COUNT] Free lists for each size class.
span_cache_t span_cache Arrays of fully freed spans, single span.
atomicptr_t span_free_deferred List of deferred free spans (single linked list)
span_large_cache_t span_large_cache[LARGE_CLASS_COUNT - 1] Arrays of fully freed spans, large spans with > 1 span count.
span_t * span_reserve Mapped but unused spans.
span_t * span_reserve_master Master span for mapped but unused spans.
uint32_t spans_reserved Number of mapped but unused spans.
size_class_t
struct size_class_t
Definition at line 557 of file rpmalloc.c.
Data Fields
uint16_t block_count Number of blocks in each chunk.
uint32_t block_size Size of blocks in this class.
uint16_t class_idx Class index this class is merged with.
global_cache_t
struct global_cache_t
Definition at line 568 of file rpmalloc.c.
Data Fields
uint32_t count Cache count.
atomic32_t lock Cache lock.
span_t * overflow Unlimited cache overflow.
span_t * span[GLOBAL_CACHE_MULTIPLIER *MAX_THREAD_SPAN_CACHE] Cached spans.
Macro Definition Documentation
_memory_default_span_mask
#define _memory_default_span_mask (~((uintptr_t)(_memory_span_size - 1)))
Definition at line 595 of file rpmalloc.c.
_memory_default_span_size
#define _memory_default_span_size (64 * 1024)
Default span size (64KiB)
Global data
Definition at line 593 of file rpmalloc.c.
_memory_default_span_size_shift
#define _memory_default_span_size_shift 16
Definition at line 594 of file rpmalloc.c.
_memory_thread_heap
#define _memory_thread_heap (*__memory_thread_heap())
Definition at line 706 of file rpmalloc.c.
_rpmalloc_stat_add
#define _rpmalloc_stat_add (counter, value)
Value:
    do                                     \
    {                                      \
    } while (0)
Definition at line 257 of file rpmalloc.c.
_rpmalloc_stat_add64
#define _rpmalloc_stat_add64 (counter, value)
Value:
    do                                       \
    {                                        \
    } while (0)
Definition at line 261 of file rpmalloc.c.
_rpmalloc_stat_add_peak
#define _rpmalloc_stat_add_peak (counter, value, peak)
Value:
    do                                                \
    {                                                 \
    } while (0)
Definition at line 265 of file rpmalloc.c.
_rpmalloc_stat_dec
#define _rpmalloc_stat_dec (counter)
Value:
    do                              \
    {                               \
    } while (0)
Definition at line 253 of file rpmalloc.c.
_rpmalloc_stat_inc
#define _rpmalloc_stat_inc (counter)
Value:
    do                              \
    {                               \
    } while (0)
Statistics related functions (evaluate to nothing when statistics not enabled)
Definition at line 249 of file rpmalloc.c.
_rpmalloc_stat_inc_alloc
#define _rpmalloc_stat_inc_alloc (heap, class_idx)
Value:
    do                                            \
    {                                             \
    } while (0)
Definition at line 273 of file rpmalloc.c.
_rpmalloc_stat_inc_free
#define _rpmalloc_stat_inc_free (heap, class_idx)
Value:
    do                                           \
    {                                            \
    } while (0)
Definition at line 277 of file rpmalloc.c.
_rpmalloc_stat_sub
#define _rpmalloc_stat_sub (counter, value)
Value:
    do                                     \
    {                                      \
    } while (0)
Definition at line 269 of file rpmalloc.c.
DEFAULT_SPAN_MAP_COUNT
#define DEFAULT_SPAN_MAP_COUNT 64
Default number of spans to map in call to map more virtual memory (default values yield 4MiB here)
Definition at line 77 of file rpmalloc.c.
DISABLE_UNMAP
#define DISABLE_UNMAP 0
Disable unmapping memory pages (also enables unlimited cache)
Definition at line 65 of file rpmalloc.c.
ENABLE_ADAPTIVE_THREAD_CACHE
#define ENABLE_ADAPTIVE_THREAD_CACHE 0
Enable adaptive thread cache size based on use heuristics.
Definition at line 73 of file rpmalloc.c.
ENABLE_ASSERTS
#define ENABLE_ASSERTS 1
Enable asserts.
Definition at line 53 of file rpmalloc.c.
ENABLE_GLOBAL_CACHE
#define ENABLE_GLOBAL_CACHE 1
Enable global cache shared between all threads, requires thread cache.
Definition at line 41 of file rpmalloc.c.
ENABLE_OVERRIDE
#define ENABLE_OVERRIDE 0
Override standard library malloc/free and new/delete entry points.
Definition at line 57 of file rpmalloc.c.
ENABLE_PRELOAD
#define ENABLE_PRELOAD 0
Support preloading.
Definition at line 61 of file rpmalloc.c.
ENABLE_STATISTICS
#define ENABLE_STATISTICS 0
Enable statistics collection.
Definition at line 49 of file rpmalloc.c.
ENABLE_THREAD_CACHE
#define ENABLE_THREAD_CACHE 1
Enable per-thread cache.
Definition at line 37 of file rpmalloc.c.
ENABLE_UNLIMITED_CACHE
#define ENABLE_UNLIMITED_CACHE 0
Enable unlimited global cache (no unmapping until finalization)
Definition at line 69 of file rpmalloc.c.
ENABLE_VALIDATE_ARGS
#define ENABLE_VALIDATE_ARGS 1
Enable validation of args to public entry points.
Definition at line 45 of file rpmalloc.c.
EXPECTED
#define EXPECTED (x) __builtin_expect((x), 1)
Definition at line 212 of file rpmalloc.c.
FORCEINLINE
#define FORCEINLINE inline __attribute__((__always_inline__))
Definition at line 104 of file rpmalloc.c.
GLOBAL_CACHE_MULTIPLIER
#define GLOBAL_CACHE_MULTIPLIER 8
Multiplier for global cache.
Definition at line 81 of file rpmalloc.c.
HEAP_ARRAY_SIZE
#define HEAP_ARRAY_SIZE 47
Size of heap hashmap.
Build time configurable limits
Definition at line 33 of file rpmalloc.c.
INVALID_POINTER
#define INVALID_POINTER ((void *)((uintptr_t)-1))
Definition at line 332 of file rpmalloc.c.
LARGE_CLASS_COUNT
#define LARGE_CLASS_COUNT 63
Number of large block size classes.
Definition at line 304 of file rpmalloc.c.
LARGE_SIZE_LIMIT
#define LARGE_SIZE_LIMIT ((LARGE_CLASS_COUNT * _memory_span_size) - SPAN_HEADER_SIZE)
Maximum size of a large block.
Definition at line 308 of file rpmalloc.c.
MAP_UNINITIALIZED
#define MAP_UNINITIALIZED 0
Definition at line 125 of file rpmalloc.c.
MAX_ALLOC_SIZE
#define MAX_ALLOC_SIZE (((size_t)-1) - _memory_span_size)
Maximum allocation size to avoid integer overflow.
Definition at line 326 of file rpmalloc.c.
MAX_THREAD_SPAN_CACHE
#define MAX_THREAD_SPAN_CACHE 400
Number of spans in thread cache.
Definition at line 312 of file rpmalloc.c.
MAX_THREAD_SPAN_LARGE_CACHE
#define MAX_THREAD_SPAN_LARGE_CACHE 100
Number of spans in thread cache for large spans (must be greater than LARGE_CLASS_COUNT / 2)
Definition at line 316 of file rpmalloc.c.
MEDIUM_CLASS_COUNT
#define MEDIUM_CLASS_COUNT 61
Number of medium block size classes.
Definition at line 300 of file rpmalloc.c.
MEDIUM_GRANULARITY
#define MEDIUM_GRANULARITY 512
Granularity of a medium allocation block.
Definition at line 296 of file rpmalloc.c.
MEDIUM_GRANULARITY_SHIFT
#define MEDIUM_GRANULARITY_SHIFT 9
Medium granularity shift count.
Definition at line 298 of file rpmalloc.c.
MEDIUM_SIZE_LIMIT
#define MEDIUM_SIZE_LIMIT (SMALL_SIZE_LIMIT + (MEDIUM_GRANULARITY * MEDIUM_CLASS_COUNT))
Maximum size of a medium block.
Definition at line 306 of file rpmalloc.c.
pointer_diff
#define pointer_diff (first, second) (ptrdiff_t)((const char *)(first) - (const char *)(second))
Definition at line 330 of file rpmalloc.c.
pointer_offset
#define pointer_offset (ptr, ofs) (void *)((char *)(ptr) + (ptrdiff_t)(ofs))
Definition at line 329 of file rpmalloc.c.
PROT_MAX
#define PROT_MAX (f) 0
Definition at line 122 of file rpmalloc.c.
rpmalloc_assert
#define rpmalloc_assert (truth, message)
Value:
    do                                                                                                       \
    {                                                                                                        \
        if (!(truth))                                                                                        \
        {                                                                                                    \
            if (_memory_config.error_callback)                                                               \
            {                                                                                                \
                _memory_config.error_callback(                                                               \
                    message " (" RPMALLOC_TOSTRING(truth) ") at " __FILE__ ":" RPMALLOC_TOSTRING(__LINE__)); \
            }                                                                                                \
            else                                                                                             \
            {                                                                                                \
                assert((truth) && message);                                                                  \
            }                                                                                                \
        }                                                                                                    \
    } while (0)
Definition at line 143 of file rpmalloc.c.
RPMALLOC_TOSTRING
#define RPMALLOC_TOSTRING (x) RPMALLOC_TOSTRING_M(x)
Definition at line 142 of file rpmalloc.c.
RPMALLOC_TOSTRING_M
#define RPMALLOC_TOSTRING_M (x) #x
Definition at line 141 of file rpmalloc.c.
SIZE_CLASS_COUNT
#define SIZE_CLASS_COUNT (SMALL_CLASS_COUNT + MEDIUM_CLASS_COUNT)
Total number of small + medium size classes.
Definition at line 302 of file rpmalloc.c.
SIZE_CLASS_HUGE
#define SIZE_CLASS_HUGE ((uint32_t)-1)
Definition at line 335 of file rpmalloc.c.
SIZE_CLASS_LARGE
#define SIZE_CLASS_LARGE SIZE_CLASS_COUNT
Definition at line 334 of file rpmalloc.c.
SMALL_CLASS_COUNT
#define SMALL_CLASS_COUNT 65
Number of small block size classes.
Definition at line 292 of file rpmalloc.c.
SMALL_GRANULARITY
#define SMALL_GRANULARITY 16
Granularity of a small allocation block (must be power of two)
Preconfigured limits and sizes
Definition at line 288 of file rpmalloc.c.
SMALL_GRANULARITY_SHIFT
#define SMALL_GRANULARITY_SHIFT 4
Small granularity shift count.
Definition at line 290 of file rpmalloc.c.
SMALL_SIZE_LIMIT
#define SMALL_SIZE_LIMIT (SMALL_GRANULARITY * (SMALL_CLASS_COUNT - 1))
Maximum size of a small block.
Definition at line 294 of file rpmalloc.c.
SPAN_FLAG_ALIGNED_BLOCKS
#define SPAN_FLAG_ALIGNED_BLOCKS 4U
Flag indicating span has blocks with increased alignment.
Definition at line 361 of file rpmalloc.c.
SPAN_FLAG_MASTER
#define SPAN_FLAG_MASTER 1U
Flag indicating span is the first (master) span of a split superspan.
Definition at line 357 of file rpmalloc.c.
SPAN_FLAG_SUBSPAN
#define SPAN_FLAG_SUBSPAN 2U
Flag indicating span is a secondary (sub) span of a split superspan.
Definition at line 359 of file rpmalloc.c.
SPAN_FLAG_UNMAPPED_MASTER
#define SPAN_FLAG_UNMAPPED_MASTER 8U
Flag indicating an unmapped master span.
Definition at line 363 of file rpmalloc.c.
SPAN_HEADER_SIZE
#define SPAN_HEADER_SIZE 128
Size of a span header (must be a multiple of SMALL_GRANULARITY and a power of two)
Definition at line 310 of file rpmalloc.c.
THREAD_SPAN_CACHE_TRANSFER
#define THREAD_SPAN_CACHE_TRANSFER 64
Number of spans to transfer between thread and global cache.
Definition at line 314 of file rpmalloc.c.
THREAD_SPAN_LARGE_CACHE_TRANSFER
#define THREAD_SPAN_LARGE_CACHE_TRANSFER 6
Number of spans to transfer between thread and global cache for large spans.
Definition at line 318 of file rpmalloc.c.
TLS_MODEL
#define TLS_MODEL __attribute__((tls_model("initial-exec")))
Current thread heap.
Thread local heap and ID
Definition at line 696 of file rpmalloc.c.
UNEXPECTED
#define UNEXPECTED (x) __builtin_expect((x), 0)
Definition at line 213 of file rpmalloc.c.
Typedef Documentation
_Atomic
typedef volatile _Atomic(int32_t)
Definition at line 171 of file rpmalloc.c.
                                                           { return atomic_load_explicit(src, memory_order_relaxed); }
global_cache_t
typedef struct global_cache_t global_cache_t
Global cache.
Definition at line 321 of file rpmalloc.c.
heap_size_class_t
typedef struct heap_size_class_t heap_size_class_t
Definition at line 467 of file rpmalloc.c.
heap_t
typedef struct heap_t heap_t
A memory heap, per thread.
Data types
Definition at line 321 of file rpmalloc.c.
size_class_t
typedef struct size_class_t size_class_t
Size class definition.
Definition at line 321 of file rpmalloc.c.
span_active_t
typedef struct span_active_t span_active_t
Span active data.
Definition at line 321 of file rpmalloc.c.
span_cache_t
typedef struct span_cache_t span_cache_t
Definition at line 467 of file rpmalloc.c.
span_large_cache_t
typedef struct span_large_cache_t span_large_cache_t
Definition at line 467 of file rpmalloc.c.
span_list_t
typedef struct span_list_t span_list_t
Span list.
Definition at line 321 of file rpmalloc.c.
span_t
typedef struct span_t span_t
Span of memory pages.
Definition at line 321 of file rpmalloc.c.
Function Documentation
__get_tid()
uintptr_t __get_tid (void)
Definition at line 51 of file rpmalloc_compat.cpp.
 {
     if (unlikely(!TaskManager || !thisThread))
         return (uintptr_t)-1;
     return thisThread->ID;
 }
References TaskManager, thisThread, and unlikely.
Referenced by get_thread_id().
__memory_thread_heap()
heap_t** __memory_thread_heap (void)
Definition at line 33 of file rpmalloc_compat.cpp.
 {
     if (unlikely(!TaskManager || !thisThread))
     {
         if (unlikely(!__rpmalloc_tls_heap))
         {
             __rpmalloc_tls_heap = (heap_t *)KernelAllocator.RequestPages(TO_PAGES(sizeof(heap_t)));
             debug("rpmalloc TLS heap: %#lx", __rpmalloc_tls_heap);
             memset(__rpmalloc_tls_heap, 0, sizeof(heap_t));
             assert(__rpmalloc_tls_heap);
         }
         return &__rpmalloc_tls_heap;
     }
     return &__rpmalloc_tls_heap;
     heap_t *heap = (heap_t *)thisThread->TLS.pBase;
     return (heap_t **)heap;
 }
References __rpmalloc_tls_heap, assert, debug, heap, KernelAllocator, memset, return(), TaskManager, thisThread, TO_PAGES, and unlikely.
__rpmalloc_mmap()
void* __rpmalloc_mmap (void * addr, size_t length, int prot, int flags, int fd, off_t offset)
Definition at line 69 of file rpmalloc_compat.cpp.
 {
     assert(addr == 0 && fd == -1 && offset == 0);
     void *ptr = KernelAllocator.RequestPages(TO_PAGES(length));
     debug("Requested %d pages, got %p", TO_PAGES(length), ptr);
     if (ptr == nullptr)
         return MAP_FAILED;
     return ptr;
 }
References addr, assert, debug, fd, KernelAllocator, MAP_FAILED, offset, and TO_PAGES.
Referenced by _rpmalloc_mmap_os().
__rpmalloc_munmap()
int __rpmalloc_munmap (void * addr, size_t length)
Definition at line 80 of file rpmalloc_compat.cpp.
 {
     KernelAllocator.FreePages(addr, TO_PAGES(length));
     debug("Freed %d pages at %p", TO_PAGES(length), addr);
     return 0;
 }
References addr, debug, KernelAllocator, and TO_PAGES.
Referenced by _rpmalloc_unmap_os().
__rpmalloc_posix_madvise()
int __rpmalloc_posix_madvise (void * addr, size_t length, int advice)
Definition at line 87 of file rpmalloc_compat.cpp.
 {
     function("%#lx %d %d", addr, length, advice);
     return 0;
 }
References addr.
Referenced by _rpmalloc_unmap_os().
__rpmalloc_sysconf()
long __rpmalloc_sysconf (int name)
Definition at line 58 of file rpmalloc_compat.cpp.
 {
     switch (name)
     {
     case _SC_PAGESIZE:
         return PAGE_SIZE;
     default:
         return -1;
     }
 }
References _SC_PAGESIZE, and PAGE_SIZE.
Referenced by rpmalloc_initialize_config().
_rpmalloc_adjust_size_class()
static void _rpmalloc_adjust_size_class (size_t iclass) static
Adjust and optimize the size class properties for the given class.
Definition at line 2788 of file rpmalloc.c.
 {
     size_t block_size = _memory_size_class[iclass].block_size;
     size_t block_count = (_memory_span_size - SPAN_HEADER_SIZE) / block_size;
     _memory_size_class[iclass].block_count = (uint16_t)block_count;
     _memory_size_class[iclass].class_idx = (uint16_t)iclass;
     // Check if previous size classes can be merged
     if (iclass >= SMALL_CLASS_COUNT)
     {
         size_t prevclass = iclass;
         while (prevclass > 0)
         {
             --prevclass;
             // A class can be merged if number of pages and number of blocks are equal
             if (_memory_size_class[prevclass].block_count == _memory_size_class[iclass].block_count)
                 memcpy_unsafe(_memory_size_class + prevclass, _memory_size_class + iclass, sizeof(_memory_size_class[iclass]));
             else
                 break;
         }
     }
 }
References _memory_size_class, _memory_span_size, size_class_t::block_count, size_class_t::block_size, size_class_t::class_idx, memcpy_unsafe(), SMALL_CLASS_COUNT, and SPAN_HEADER_SIZE.
Referenced by rpmalloc_initialize_config().
_rpmalloc_aligned_allocate()
static void* _rpmalloc_aligned_allocate (heap_t * heap, size_t alignment, size_t size) static
Definition at line 2302 of file rpmalloc.c.
 {
     if (alignment <= SMALL_GRANULARITY)
         return _rpmalloc_allocate(heap, size);
 #if ENABLE_VALIDATE_ARGS
     assert((size + alignment) > size);
     assert((alignment & (alignment - 1)) == 0);
 #endif
     if ((alignment <= SPAN_HEADER_SIZE) && (size < _memory_medium_size_limit))
     {
         // If alignment is less or equal to span header size (which is power of two),
         // and size aligned to span header size multiples is less than size + alignment,
         // then use natural alignment of blocks to provide alignment
         size_t multiple_size = size ? (size + (SPAN_HEADER_SIZE - 1)) & ~(uintptr_t)(SPAN_HEADER_SIZE - 1) : SPAN_HEADER_SIZE;
         rpmalloc_assert(!(multiple_size % SPAN_HEADER_SIZE), "Failed alignment calculation");
         if (multiple_size <= (size + alignment))
             return _rpmalloc_allocate(heap, multiple_size);
     }
     void *ptr = 0;
     size_t align_mask = alignment - 1;
     if (alignment <= _memory_page_size)
     {
         ptr = _rpmalloc_allocate(heap, size + alignment);
         if ((uintptr_t)ptr & align_mask)
         {
             ptr = (void *)(((uintptr_t)ptr & ~(uintptr_t)align_mask) + alignment);
             // Mark as having aligned blocks
             span_t *span = (span_t *)((uintptr_t)ptr & _memory_span_mask);
             span->flags |= SPAN_FLAG_ALIGNED_BLOCKS;
         }
         return ptr;
     }
     // Fallback to mapping new pages for this request. Since pointers passed
     // to rpfree must be able to reach the start of the span by bitmasking of
     // the address with the span size, the returned aligned pointer from this
     // function must be with a span size of the start of the mapped area.
     // In worst case this requires us to loop and map pages until we get a
     // suitable memory address. It also means we can never align to span size
     // or greater, since the span header will push alignment more than one
     // span size away from span start (thus causing pointer mask to give us
     // an invalid span start on free)
     if (alignment & align_mask)
     {
         errno = EINVAL;
         return 0;
     }
     if (alignment >= _memory_span_size)
     {
         errno = EINVAL;
         return 0;
     }
     size_t extra_pages = alignment / _memory_page_size;
     // Since each span has a header, we will at least need one extra memory page
     size_t num_pages = 1 + (size / _memory_page_size);
     if (size & (_memory_page_size - 1))
         ++num_pages;
     if (extra_pages > num_pages)
         num_pages = 1 + extra_pages;
     size_t original_pages = num_pages;
     size_t limit_pages = (_memory_span_size / _memory_page_size) * 2;
     if (limit_pages < (original_pages * 2))
         limit_pages = original_pages * 2;
     size_t mapped_size, align_offset;
     span_t *span;
 retry:
     align_offset = 0;
     mapped_size = num_pages * _memory_page_size;
     span = (span_t *)_rpmalloc_mmap(mapped_size, &align_offset);
     if (!span)
     {
         errno = ENOMEM;
         return 0;
     }
     ptr = pointer_offset(span, SPAN_HEADER_SIZE);
     if ((uintptr_t)ptr & align_mask)
         ptr = (void *)(((uintptr_t)ptr & ~(uintptr_t)align_mask) + alignment);
     if (((size_t)pointer_diff(ptr, span) >= _memory_span_size) ||
         (pointer_offset(ptr, size) > pointer_offset(span, mapped_size)) ||
         (((uintptr_t)ptr & _memory_span_mask) != (uintptr_t)span))
     {
         _rpmalloc_unmap(span, mapped_size, align_offset, mapped_size);
         ++num_pages;
         if (num_pages > limit_pages)
         {
             errno = EINVAL;
             return 0;
         }
         goto retry;
     }
     // Store page count in span_count
     span->size_class = SIZE_CLASS_HUGE;
     span->span_count = (uint32_t)num_pages;
     span->align_offset = (uint32_t)align_offset;
     span->heap = heap;
     _rpmalloc_stat_add_peak(&_huge_pages_current, num_pages, _huge_pages_peak);
 #if RPMALLOC_FIRST_CLASS_HEAPS
     _rpmalloc_span_double_link_list_add(&heap->large_huge_span, span);
 #endif
     ++heap->full_span_count;
     _rpmalloc_stat_add64(&_allocation_counter, 1);
     return ptr;
 }
References _memory_medium_size_limit, _memory_page_size, _memory_span_mask, _memory_span_size, _rpmalloc_allocate(), _rpmalloc_mmap(), _rpmalloc_span_double_link_list_add(), _rpmalloc_stat_add64, _rpmalloc_stat_add_peak, _rpmalloc_unmap(), span_t::align_offset, assert, EINVAL, ENOMEM, errno, span_t::flags, span_t::heap, heap, pointer_diff, pointer_offset, rpmalloc_assert, size, span_t::size_class, SIZE_CLASS_HUGE, SMALL_GRANULARITY, span_t::span_count, SPAN_FLAG_ALIGNED_BLOCKS, and SPAN_HEADER_SIZE.
Referenced by _rpmalloc_aligned_reallocate(), and rpaligned_alloc().
_rpmalloc_aligned_reallocate()
static void* _rpmalloc_aligned_reallocate (heap_t * heap, void * ptr, size_t alignment, size_t size, size_t oldsize, unsigned int flags) static
Definition at line 2729 of file rpmalloc.c.
 {
     if (alignment <= SMALL_GRANULARITY)
         return _rpmalloc_reallocate(heap, ptr, size, oldsize, flags);
     int no_alloc = !!(flags & RPMALLOC_GROW_OR_FAIL);
     size_t usablesize = (ptr ? _rpmalloc_usable_size(ptr) : 0);
     if ((usablesize >= size) && !((uintptr_t)ptr & (alignment - 1)))
     {
         if (no_alloc || (size >= (usablesize / 2)))
             return ptr;
     }
     // Aligned alloc marks span as having aligned blocks
     void *block = (!no_alloc ? _rpmalloc_aligned_allocate(heap, alignment, size) : 0);
     if (EXPECTED(block != 0))
     {
         if (!(flags & RPMALLOC_NO_PRESERVE) && ptr)
         {
             if (!oldsize)
                 oldsize = usablesize;
             memcpy_unsafe(block, ptr, oldsize < size ? oldsize : size);
         }
         _rpmalloc_deallocate(ptr);
     }
     return block;
 }
References _rpmalloc_aligned_allocate(), _rpmalloc_deallocate(), _rpmalloc_reallocate(), _rpmalloc_usable_size(), EXPECTED, flags, heap, memcpy_unsafe(), RPMALLOC_GROW_OR_FAIL, RPMALLOC_NO_PRESERVE, size, and SMALL_GRANULARITY.
Referenced by rpaligned_realloc().
_rpmalloc_allocate()
static void* _rpmalloc_allocate (heap_t * heap, size_t size) static
Allocate a block of the given size.
Definition at line 2289 of file rpmalloc.c.
 {
     _rpmalloc_stat_add64(&_allocation_counter, 1);
     if (EXPECTED(size <= SMALL_SIZE_LIMIT))
         return _rpmalloc_allocate_small(heap, size);
     else if (size <= _memory_medium_size_limit)
         return _rpmalloc_allocate_medium(heap, size);
     else if (size <= LARGE_SIZE_LIMIT)
         return _rpmalloc_allocate_large(heap, size);
     return _rpmalloc_allocate_huge(heap, size);
 }
References _memory_medium_size_limit, _rpmalloc_allocate_huge(), _rpmalloc_allocate_large(), _rpmalloc_allocate_medium(), _rpmalloc_allocate_small(), _rpmalloc_stat_add64, EXPECTED, heap, LARGE_SIZE_LIMIT, size, and SMALL_SIZE_LIMIT.
Referenced by _rpmalloc_aligned_allocate(), _rpmalloc_reallocate(), rpcalloc(), and rpmalloc().
_rpmalloc_allocate_from_heap_fallback()
static void* _rpmalloc_allocate_from_heap_fallback (heap_t * heap, heap_size_class_t * heap_size_class, uint32_t class_idx) static
Allocate a small/medium sized memory block from the given heap.
Definition at line 2143 of file rpmalloc.c.
 {
     span_t *span = heap_size_class->partial_span;
     if (EXPECTED(span != 0))
     {
         rpmalloc_assert(span->block_count == _memory_size_class[span->size_class].block_count, "Span block count corrupted");
         rpmalloc_assert(!_rpmalloc_span_is_fully_utilized(span), "Internal failure");
         void *block;
         if (span->free_list)
         {
             // Span local free list is not empty, swap to size class free list
             block = free_list_pop(&span->free_list);
             heap_size_class->free_list = span->free_list;
             span->free_list = 0;
         }
         else
         {
             // If the span did not fully initialize free list, link up another page worth of blocks
             void *block_start = pointer_offset(span, SPAN_HEADER_SIZE + ((size_t)span->free_list_limit * span->block_size));
             span->free_list_limit += free_list_partial_init(&heap_size_class->free_list, &block,
                                                             (void *)((uintptr_t)block_start & ~(_memory_page_size - 1)), block_start,
                                                             span->block_count - span->free_list_limit, span->block_size);
         }
         rpmalloc_assert(span->free_list_limit <= span->block_count, "Span block count corrupted");
         span->used_count = span->free_list_limit;
         // Swap in deferred free list if present
         if (atomic_load_ptr(&span->free_list_deferred))
             _rpmalloc_span_extract_free_list_deferred(span);
         // If span is still not fully utilized keep it in partial list and early return block
         if (!_rpmalloc_span_is_fully_utilized(span))
             return block;
         // The span is fully utilized, unlink from partial list and add to fully utilized list
         _rpmalloc_span_double_link_list_pop_head(&heap_size_class->partial_span, span);
 #if RPMALLOC_FIRST_CLASS_HEAPS
         _rpmalloc_span_double_link_list_add(&heap->full_span[class_idx], span);
 #endif
         ++heap->full_span_count;
         return block;
     }
     // Find a span in one of the cache levels
     span = _rpmalloc_heap_extract_new_span(heap, heap_size_class, 1, class_idx);
     if (EXPECTED(span != 0))
     {
         // Mark span as owned by this heap and set base data, return first block
         return _rpmalloc_span_initialize_new(heap, heap_size_class, span, class_idx);
     }
     return 0;
 }
References _memory_page_size, _memory_size_class, _rpmalloc_heap_extract_new_span(), _rpmalloc_span_double_link_list_add(), _rpmalloc_span_double_link_list_pop_head(), _rpmalloc_span_extract_free_list_deferred(), _rpmalloc_span_initialize_new(), _rpmalloc_span_is_fully_utilized(), atomic_load_ptr(), span_t::block_count, size_class_t::block_count, span_t::block_size, EXPECTED, span_t::free_list, heap_size_class_t::free_list, span_t::free_list_deferred, span_t::free_list_limit, free_list_partial_init(), free_list_pop(), heap, heap_size_class_t::partial_span, pointer_offset, rpmalloc_assert, span_t::size_class, SPAN_HEADER_SIZE, and span_t::used_count.
Referenced by _rpmalloc_allocate_medium(), and _rpmalloc_allocate_small().
_rpmalloc_allocate_huge()
static void* _rpmalloc_allocate_huge (heap_t * heap, size_t size) static
Allocate a huge block by mapping memory pages directly.
Definition at line 2259 of file rpmalloc.c.
 {
     rpmalloc_assert(heap, "No thread heap");
     _rpmalloc_heap_cache_adopt_deferred(heap, 0);
     size += SPAN_HEADER_SIZE;
     size_t num_pages = size >> _memory_page_size_shift;
     if (size & (_memory_page_size - 1))
         ++num_pages;
     size_t align_offset = 0;
     span_t *span = (span_t *)_rpmalloc_mmap(num_pages * _memory_page_size, &align_offset);
     if (!span)
         return span;
     // Store page count in span_count
     span->size_class = SIZE_CLASS_HUGE;
     span->span_count = (uint32_t)num_pages;
     span->align_offset = (uint32_t)align_offset;
     span->heap = heap;
     _rpmalloc_stat_add_peak(&_huge_pages_current, num_pages, _huge_pages_peak);
 #if RPMALLOC_FIRST_CLASS_HEAPS
     _rpmalloc_span_double_link_list_add(&heap->large_huge_span, span);
 #endif
     ++heap->full_span_count;
     return pointer_offset(span, SPAN_HEADER_SIZE);
 }
References _memory_page_size, _memory_page_size_shift, _rpmalloc_heap_cache_adopt_deferred(), _rpmalloc_mmap(), _rpmalloc_span_double_link_list_add(), _rpmalloc_stat_add_peak, span_t::align_offset, span_t::heap, heap, pointer_offset, rpmalloc_assert, size, span_t::size_class, SIZE_CLASS_HUGE, span_t::span_count, and SPAN_HEADER_SIZE.
Referenced by _rpmalloc_allocate().
_rpmalloc_allocate_large()
static void* _rpmalloc_allocate_large (heap_t * heap, size_t size) static
Allocate a large sized memory block from the given heap.
Definition at line 2228 of file rpmalloc.c.
 {
     rpmalloc_assert(heap, "No thread heap");
     // Calculate number of needed max sized spans (including header)
     // Since this function is never called if size > LARGE_SIZE_LIMIT
     // the span_count is guaranteed to be <= LARGE_CLASS_COUNT
     size += SPAN_HEADER_SIZE;
     size_t span_count = size >> _memory_span_size_shift;
     if (size & (_memory_span_size - 1))
         ++span_count;
     // Find a span in one of the cache levels
     span_t *span = _rpmalloc_heap_extract_new_span(heap, 0, span_count, SIZE_CLASS_LARGE);
     if (!span)
         return span;
     // Mark span as owned by this heap and set base data
     rpmalloc_assert(span->span_count >= span_count, "Internal failure");
     span->size_class = SIZE_CLASS_LARGE;
     span->heap = heap;
 #if RPMALLOC_FIRST_CLASS_HEAPS
     _rpmalloc_span_double_link_list_add(&heap->large_huge_span, span);
 #endif
     ++heap->full_span_count;
     return pointer_offset(span, SPAN_HEADER_SIZE);
 }
References _memory_span_size, _memory_span_size_shift, _rpmalloc_heap_extract_new_span(), _rpmalloc_span_double_link_list_add(), span_t::heap, heap, pointer_offset, rpmalloc_assert, size, span_t::size_class, SIZE_CLASS_LARGE, span_t::span_count, and SPAN_HEADER_SIZE.
Referenced by _rpmalloc_allocate().
_rpmalloc_allocate_medium()
static void* _rpmalloc_allocate_medium (heap_t * heap, size_t size) static
Allocate a medium sized memory block from the given heap.
Definition at line 2213 of file rpmalloc.c.
 {
     rpmalloc_assert(heap, "No thread heap");
     // Calculate the size class index and do a dependent lookup of the final class index (in case of merged classes)
     const uint32_t base_idx = (uint32_t)(SMALL_CLASS_COUNT + ((size - (SMALL_SIZE_LIMIT + 1)) >> MEDIUM_GRANULARITY_SHIFT));
     const uint32_t class_idx = _memory_size_class[base_idx].class_idx;
     heap_size_class_t *heap_size_class = heap->size_class + class_idx;
     _rpmalloc_stat_inc_alloc(heap, class_idx);
     if (EXPECTED(heap_size_class->free_list != 0))
         return free_list_pop(&heap_size_class->free_list);
     return _rpmalloc_allocate_from_heap_fallback(heap, heap_size_class, class_idx);
 }
References _memory_size_class, _rpmalloc_allocate_from_heap_fallback(), _rpmalloc_stat_inc_alloc, size_class_t::class_idx, EXPECTED, heap_size_class_t::free_list, free_list_pop(), heap, MEDIUM_GRANULARITY_SHIFT, rpmalloc_assert, size, SMALL_CLASS_COUNT, and SMALL_SIZE_LIMIT.
Referenced by _rpmalloc_allocate().
_rpmalloc_allocate_small()
static void* _rpmalloc_allocate_small (heap_t * heap, size_t size) static
Allocate a small sized memory block from the given heap.
Definition at line 2199 of file rpmalloc.c.
 {
     rpmalloc_assert(heap, "No thread heap");
     // Small sizes have unique size classes
     const uint32_t class_idx = (uint32_t)((size + (SMALL_GRANULARITY - 1)) >> SMALL_GRANULARITY_SHIFT);
     heap_size_class_t *heap_size_class = heap->size_class + class_idx;
     _rpmalloc_stat_inc_alloc(heap, class_idx);
     if (EXPECTED(heap_size_class->free_list != 0))
         return free_list_pop(&heap_size_class->free_list);
     return _rpmalloc_allocate_from_heap_fallback(heap, heap_size_class, class_idx);
 }
References _rpmalloc_allocate_from_heap_fallback(), _rpmalloc_stat_inc_alloc, EXPECTED, heap_size_class_t::free_list, free_list_pop(), heap, rpmalloc_assert, size, SMALL_GRANULARITY, and SMALL_GRANULARITY_SHIFT.
Referenced by _rpmalloc_allocate().
_rpmalloc_deallocate()
static void _rpmalloc_deallocate (void * p) static
Deallocate the given block.
Definition at line 2615 of file rpmalloc.c.
 {
     _rpmalloc_stat_add64(&_deallocation_counter, 1);
     // Grab the span (always at start of span, using span alignment)
     span_t *span = (span_t *)((uintptr_t)p & _memory_span_mask);
     if (UNEXPECTED(!span))
         return;
     if (EXPECTED(span->size_class < SIZE_CLASS_COUNT))
         _rpmalloc_deallocate_small_or_medium(span, p);
     else if (span->size_class == SIZE_CLASS_LARGE)
         _rpmalloc_deallocate_large(span);
     else
         _rpmalloc_deallocate_huge(span);
 }
References _memory_span_mask, _rpmalloc_deallocate_huge(), _rpmalloc_deallocate_large(), _rpmalloc_deallocate_small_or_medium(), _rpmalloc_stat_add64, EXPECTED, p, span_t::size_class, SIZE_CLASS_COUNT, SIZE_CLASS_LARGE, and UNEXPECTED.
Referenced by _rpmalloc_aligned_reallocate(), _rpmalloc_reallocate(), and rpfree().
_rpmalloc_deallocate_defer_free_span()
static void _rpmalloc_deallocate_defer_free_span (heap_t * heap, span_t * span) static
Definition at line 2467 of file rpmalloc.c.
 {
     if (span->size_class != SIZE_CLASS_HUGE)
         _rpmalloc_stat_inc(&heap->span_use[span->span_count - 1].spans_deferred);
     // This list does not need ABA protection, no mutable side state
     do
     {
         span->free_list = (void *)atomic_load_ptr(&heap->span_free_deferred);
     } while (!atomic_cas_ptr(&heap->span_free_deferred, span, span->free_list));
 }
References _rpmalloc_stat_inc, atomic_cas_ptr(), atomic_load_ptr(), span_t::free_list, heap, span_t::size_class, SIZE_CLASS_HUGE, and span_t::span_count.
Referenced by _rpmalloc_deallocate_defer_small_or_medium(), _rpmalloc_deallocate_huge(), and _rpmalloc_deallocate_large().
_rpmalloc_deallocate_defer_small_or_medium()
static void _rpmalloc_deallocate_defer_small_or_medium (span_t * span, void * block) static
Put the block in the deferred free list of the owning span.
Definition at line 2480 of file rpmalloc.c.
 {
     // The memory ordering here is a bit tricky, to avoid having to ABA protect
     // the deferred free list to avoid desynchronization of list and list size
     // we need to have acquire semantics on successful CAS of the pointer to
     // guarantee the list_size variable validity + release semantics on pointer store
     void *free_list;
     do
     {
         free_list = atomic_exchange_ptr_acquire(&span->free_list_deferred, INVALID_POINTER);
     } while (free_list == INVALID_POINTER);
     *((void **)block) = free_list;
     uint32_t free_count = ++span->list_size;
     int all_deferred_free = (free_count == span->block_count);
     atomic_store_ptr_release(&span->free_list_deferred, block);
     if (all_deferred_free)
     {
         // Span was completely freed by this block. Due to the INVALID_POINTER spin lock
         // no other thread can reach this state simultaneously on this span.
         // Safe to move to owner heap deferred cache
         _rpmalloc_deallocate_defer_free_span(span->heap, span);
     }
 }
References _rpmalloc_deallocate_defer_free_span(), atomic_exchange_ptr_acquire(), atomic_store_ptr_release(), span_t::block_count, span_t::free_list_deferred, span_t::heap, INVALID_POINTER, and span_t::list_size.
Referenced by _rpmalloc_deallocate_small_or_medium().
_rpmalloc_deallocate_direct_small_or_medium()
static void _rpmalloc_deallocate_direct_small_or_medium (span_t * span, void * block) static
Deallocate the given small/medium memory block in the current thread local heap.
Deallocation entry points
Definition at line 2430 of file rpmalloc.c.
 {
     heap_t *heap = span->heap;
     rpmalloc_assert(heap->owner_thread == get_thread_id() || !heap->owner_thread || heap->finalize, "Internal failure");
     // Add block to free list
     if (UNEXPECTED(_rpmalloc_span_is_fully_utilized(span)))
     {
         span->used_count = span->block_count;
 #if RPMALLOC_FIRST_CLASS_HEAPS
         _rpmalloc_span_double_link_list_remove(&heap->full_span[span->size_class], span);
 #endif
         _rpmalloc_span_double_link_list_add(&heap->size_class[span->size_class].partial_span, span);
         --heap->full_span_count;
     }
     *((void **)block) = span->free_list;
     --span->used_count;
     span->free_list = block;
     if (UNEXPECTED(span->used_count == span->list_size))
     {
         // If there are no used blocks it is guaranteed that no other external thread is accessing the span
         if (span->used_count)
         {
             // Make sure we have synchronized the deferred list and list size by using acquire semantics
             // and guarantee that no external thread is accessing span concurrently
             void *free_list;
             do
             {
                 free_list = atomic_exchange_ptr_acquire(&span->free_list_deferred, INVALID_POINTER);
             } while (free_list == INVALID_POINTER);
             atomic_store_ptr_release(&span->free_list_deferred, free_list);
         }
         _rpmalloc_span_double_link_list_remove(&heap->size_class[span->size_class].partial_span, span);
         _rpmalloc_span_release_to_cache(heap, span);
     }
 }
References _rpmalloc_span_double_link_list_add(), _rpmalloc_span_double_link_list_remove(), _rpmalloc_span_is_fully_utilized(), _rpmalloc_span_release_to_cache(), atomic_exchange_ptr_acquire(), atomic_store_ptr_release(), span_t::block_count, span_t::free_list, span_t::free_list_deferred, get_thread_id(), span_t::heap, heap, INVALID_POINTER, span_t::list_size, rpmalloc_assert, span_t::size_class, UNEXPECTED, and span_t::used_count.
Referenced by _rpmalloc_deallocate_small_or_medium().
_rpmalloc_deallocate_huge()
static void _rpmalloc_deallocate_huge (span_t * span) static
Deallocate the given huge span.
Heap control
Definition at line 2588 of file rpmalloc.c.
 {
     rpmalloc_assert(span->heap, "No span heap");
 #if RPMALLOC_FIRST_CLASS_HEAPS
     int defer = (span->heap->owner_thread && (span->heap->owner_thread != get_thread_id()) && !span->heap->finalize);
 #else
     int defer = ((span->heap->owner_thread != get_thread_id()) && !span->heap->finalize);
 #endif
     if (defer)
     {
         _rpmalloc_deallocate_defer_free_span(span->heap, span);
         return;
     }
     rpmalloc_assert(span->heap->full_span_count, "Heap span counter corrupted");
     --span->heap->full_span_count;
 #if RPMALLOC_FIRST_CLASS_HEAPS
     _rpmalloc_span_double_link_list_remove(&span->heap->large_huge_span, span);
 #endif
     // Oversized allocation, page count is stored in span_count
     size_t num_pages = span->span_count;
     _rpmalloc_unmap(span, num_pages * _memory_page_size, span->align_offset, num_pages * _memory_page_size);
     _rpmalloc_stat_sub(&_huge_pages_current, num_pages);
 }
References _memory_page_size, _rpmalloc_deallocate_defer_free_span(), _rpmalloc_span_double_link_list_remove(), _rpmalloc_stat_sub, _rpmalloc_unmap(), span_t::align_offset, heap_t::finalize, heap_t::full_span_count, get_thread_id(), span_t::heap, heap_t::owner_thread, rpmalloc_assert, and span_t::span_count.
Referenced by _rpmalloc_deallocate(), and _rpmalloc_heap_cache_adopt_deferred().
_rpmalloc_deallocate_large()
static void _rpmalloc_deallocate_large (span_t * span) static
Deallocate the given large memory block to the current heap.
Definition at line 2529 of file rpmalloc.c.
 {
     rpmalloc_assert(span->size_class == SIZE_CLASS_LARGE, "Bad span size class");
     rpmalloc_assert(!(span->flags & SPAN_FLAG_MASTER) || !(span->flags & SPAN_FLAG_SUBSPAN), "Span flag corrupted");
     rpmalloc_assert((span->flags & SPAN_FLAG_MASTER) || (span->flags & SPAN_FLAG_SUBSPAN), "Span flag corrupted");
     // We must always defer (unless finalizing) if from another heap since we cannot touch the list or counters of another heap
 #if RPMALLOC_FIRST_CLASS_HEAPS
     int defer = (span->heap->owner_thread && (span->heap->owner_thread != get_thread_id()) && !span->heap->finalize);
 #else
     int defer = ((span->heap->owner_thread != get_thread_id()) && !span->heap->finalize);
 #endif
     if (defer)
     {
         _rpmalloc_deallocate_defer_free_span(span->heap, span);
         return;
     }
     rpmalloc_assert(span->heap->full_span_count, "Heap span counter corrupted");
     --span->heap->full_span_count;
 #if RPMALLOC_FIRST_CLASS_HEAPS
     _rpmalloc_span_double_link_list_remove(&span->heap->large_huge_span, span);
 #endif
 #if ENABLE_ADAPTIVE_THREAD_CACHE || ENABLE_STATISTICS
     // Decrease counter
     size_t idx = span->span_count - 1;
     atomic_decr32(&span->heap->span_use[idx].current);
 #endif
     heap_t *heap = span->heap;
     rpmalloc_assert(heap, "No thread heap");
 #if ENABLE_THREAD_CACHE
     const int set_as_reserved = ((span->span_count > 1) && (heap->span_cache.count == 0) && !heap->finalize && !heap->spans_reserved);
 #else
     const int set_as_reserved = ((span->span_count > 1) && !heap->finalize && !heap->spans_reserved);
 #endif
     if (set_as_reserved)
     {
         heap->span_reserve = span;
         heap->spans_reserved = span->span_count;
         if (span->flags & SPAN_FLAG_MASTER)
         {
             heap->span_reserve_master = span;
         }
         else
         { // SPAN_FLAG_SUBSPAN
             span_t *master = (span_t *)pointer_offset(span, -(intptr_t)((size_t)span->offset_from_master * _memory_span_size));
             heap->span_reserve_master = master;
             rpmalloc_assert(master->flags & SPAN_FLAG_MASTER, "Span flag corrupted");
             rpmalloc_assert(atomic_load32(&master->remaining_spans) >= (int32_t)span->span_count, "Master span count corrupted");
         }
         _rpmalloc_stat_inc(&heap->span_use[idx].spans_to_reserved);
     }
     else
     {
         // Insert into cache list
         _rpmalloc_heap_cache_insert(heap, span);
     }
 }
References _memory_span_size, _rpmalloc_deallocate_defer_free_span(), _rpmalloc_heap_cache_insert(), _rpmalloc_span_double_link_list_remove(), _rpmalloc_stat_inc, atomic_decr32(), heap_t::finalize, span_t::flags, heap_t::full_span_count, get_thread_id(), span_t::heap, heap, idx, master, span_t::offset_from_master, heap_t::owner_thread, pointer_offset, rpmalloc_assert, span_t::size_class, SIZE_CLASS_LARGE, span_t::span_count, SPAN_FLAG_MASTER, and SPAN_FLAG_SUBSPAN.
Referenced by _rpmalloc_deallocate().
_rpmalloc_deallocate_small_or_medium()
static void _rpmalloc_deallocate_small_or_medium (span_t * span, void * p) static
Definition at line 2505 of file rpmalloc.c.
 {
     _rpmalloc_stat_inc_free(span->heap, span->size_class);
     if (span->flags & SPAN_FLAG_ALIGNED_BLOCKS)
     {
         // Realign pointer to block start
         void *blocks_start = pointer_offset(span, SPAN_HEADER_SIZE);
         uint32_t block_offset = (uint32_t)pointer_diff(p, blocks_start);
         p = pointer_offset(p, -(int32_t)(block_offset % span->block_size));
     }
     // Check if block belongs to this heap or if deallocation should be deferred
 #if RPMALLOC_FIRST_CLASS_HEAPS
     int defer = (span->heap->owner_thread && (span->heap->owner_thread != get_thread_id()) && !span->heap->finalize);
 #else
     int defer = ((span->heap->owner_thread != get_thread_id()) && !span->heap->finalize);
 #endif
     if (!defer)
         _rpmalloc_deallocate_direct_small_or_medium(span, p);
     else
         _rpmalloc_deallocate_defer_small_or_medium(span, p);
 }
References _rpmalloc_deallocate_defer_small_or_medium(), _rpmalloc_deallocate_direct_small_or_medium(), _rpmalloc_stat_inc_free, span_t::block_size, heap_t::finalize, span_t::flags, get_thread_id(), span_t::heap, heap_t::owner_thread, p, pointer_diff, pointer_offset, span_t::size_class, SPAN_FLAG_ALIGNED_BLOCKS, and SPAN_HEADER_SIZE.
Referenced by _rpmalloc_deallocate().
_rpmalloc_global_cache_extract_spans()
static size_t _rpmalloc_global_cache_extract_spans (span_t ** span, size_t span_count, size_t count) static
Definition at line 1456 of file rpmalloc.c.
 {
     global_cache_t *cache = &_memory_span_cache[span_count - 1];
     size_t extract_count = 0;
     while (!atomic_cas32_acquire(&cache->lock, 1, 0))
         _rpmalloc_spin();
 #if ENABLE_STATISTICS
     cache->extract_count += count;
 #endif
     size_t want = count - extract_count;
     if (want > cache->count)
         want = cache->count;
     memcpy_unsafe(span + extract_count, cache->span + (cache->count - want), sizeof(span_t *) * want);
     cache->count -= (uint32_t)want;
     extract_count += want;
     while ((extract_count < count) && cache->overflow)
     {
         span_t *current_span = cache->overflow;
         span[extract_count++] = current_span;
         cache->overflow = current_span->next;
     }
 #if ENABLE_ASSERTS
     for (size_t ispan = 0; ispan < extract_count; ++ispan)
     {
         assert(span[ispan]->span_count == span_count);
     }
 #endif
     atomic_store32_release(&cache->lock, 0);
     return extract_count;
 }
References _memory_span_cache, _rpmalloc_spin(), assert, atomic_cas32_acquire(), atomic_store32_release(), global_cache_t::count, count, global_cache_t::lock, memcpy_unsafe(), span_t::next, global_cache_t::overflow, and global_cache_t::span.
Referenced by _rpmalloc_heap_global_cache_extract().
_rpmalloc_global_cache_finalize()
static void _rpmalloc_global_cache_finalize (global_cache_t * cache) static
Finalize a global cache.
Global cache
Definition at line 1347 of file rpmalloc.c.
 {
     while (!atomic_cas32_acquire(&cache->lock, 1, 0))
         _rpmalloc_spin();
     for (size_t ispan = 0; ispan < cache->count; ++ispan)
         _rpmalloc_span_unmap(cache->span[ispan]);
     cache->count = 0;
     while (cache->overflow)
     {
         span_t *span = cache->overflow;
         cache->overflow = span->next;
         _rpmalloc_span_unmap(span);
     }
     atomic_store32_release(&cache->lock, 0);
 }
References _rpmalloc_span_unmap(), _rpmalloc_spin(), atomic_cas32_acquire(), atomic_store32_release(), global_cache_t::count, global_cache_t::lock, span_t::next, global_cache_t::overflow, and global_cache_t::span.
Referenced by rpmalloc_finalize().
_rpmalloc_global_cache_insert_spans()
static void _rpmalloc_global_cache_insert_spans (span_t ** span, size_t span_count, size_t count) static
Definition at line 1367 of file rpmalloc.c.
 {
     const size_t cache_limit = (span_count == 1) ? GLOBAL_CACHE_MULTIPLIER * MAX_THREAD_SPAN_CACHE : GLOBAL_CACHE_MULTIPLIER * (MAX_THREAD_SPAN_LARGE_CACHE - (span_count >> 1));
     global_cache_t *cache = &_memory_span_cache[span_count - 1];
     size_t insert_count = count;
     while (!atomic_cas32_acquire(&cache->lock, 1, 0))
         _rpmalloc_spin();
 #if ENABLE_STATISTICS
     cache->insert_count += count;
 #endif
     if ((cache->count + insert_count) > cache_limit)
         insert_count = cache_limit - cache->count;
     memcpy_unsafe(cache->span + cache->count, span, sizeof(span_t *) * insert_count);
     cache->count += (uint32_t)insert_count;
 #if ENABLE_UNLIMITED_CACHE
     while (insert_count < count)
     {
 #else
     // Enable unlimited cache if huge pages, or we will leak since it is unlikely that an entire huge page
     // will be unmapped, and we're unable to partially decommit a huge page
     while ((_memory_page_size > _memory_span_size) && (insert_count < count))
     {
 #endif
         span_t *current_span = span[insert_count++];
         current_span->next = cache->overflow;
         cache->overflow = current_span;
     }
     atomic_store32_release(&cache->lock, 0);
     span_t *keep = 0;
     for (size_t ispan = insert_count; ispan < count; ++ispan)
     {
         span_t *current_span = span[ispan];
         // Keep master spans that has remaining subspans to avoid dangling them
         if ((current_span->flags & SPAN_FLAG_MASTER) &&
             (atomic_load32(&current_span->remaining_spans) > (int32_t)current_span->span_count))
         {
             current_span->next = keep;
             keep = current_span;
         }
         else
         {
             _rpmalloc_span_unmap(current_span);
         }
     }
     if (keep)
     {
         while (!atomic_cas32_acquire(&cache->lock, 1, 0))
             _rpmalloc_spin();
         size_t islot = 0;
         while (keep)
         {
             for (; islot < cache->count; ++islot)
             {
                 span_t *current_span = cache->span[islot];
                 if (!(current_span->flags & SPAN_FLAG_MASTER) || ((current_span->flags & SPAN_FLAG_MASTER) &&
                                                                   (atomic_load32(&current_span->remaining_spans) <= (int32_t)current_span->span_count)))
                 {
                     _rpmalloc_span_unmap(current_span);
                     cache->span[islot] = keep;
                     break;
                 }
             }
             if (islot == cache->count)
                 break;
             keep = keep->next;
         }
         if (keep)
         {
             span_t *tail = keep;
             while (tail->next)
                 tail = tail->next;
             tail->next = cache->overflow;
             cache->overflow = keep;
         }
         atomic_store32_release(&cache->lock, 0);
     }
 }
References _memory_page_size, _memory_span_cache, _memory_span_size, _rpmalloc_span_unmap(), _rpmalloc_spin(), atomic_cas32_acquire(), atomic_store32_release(), global_cache_t::count, count, span_t::flags, GLOBAL_CACHE_MULTIPLIER, keep, global_cache_t::lock, MAX_THREAD_SPAN_CACHE, MAX_THREAD_SPAN_LARGE_CACHE, memcpy_unsafe(), span_t::next, global_cache_t::overflow, span_t::remaining_spans, global_cache_t::span, span_t::span_count, SPAN_FLAG_MASTER, and tail.
Referenced by _rpmalloc_heap_cache_insert(), and _rpmalloc_heap_release().
_rpmalloc_global_get_reserved_spans()
static span_t* _rpmalloc_global_get_reserved_spans (size_t span_count) static
Use global reserved spans to fulfill a memory map request (reserve size must be checked by caller)
Definition at line 914 of file rpmalloc.c.
 {
     span_t *span = _memory_global_reserve;
     _rpmalloc_span_mark_as_subspan_unless_master(_memory_global_reserve_master, span, span_count);
     _memory_global_reserve_count -= span_count;
     if (_memory_global_reserve_count)
         _memory_global_reserve = (span_t *)pointer_offset(span, span_count << _memory_span_size_shift);
     else
         _memory_global_reserve = 0;
     return span;
 }
References _memory_global_reserve, _memory_global_reserve_count, _memory_global_reserve_master, _memory_span_size_shift, _rpmalloc_span_mark_as_subspan_unless_master(), and pointer_offset.
Referenced by _rpmalloc_heap_allocate_new(), and _rpmalloc_span_map().
_rpmalloc_global_set_reserved_spans()
static void _rpmalloc_global_set_reserved_spans (span_t * master, span_t * reserve, size_t reserve_span_count) static
Store the given spans as global reserve (must only be called from within new heap allocation, not thread safe)
Definition at line 928 of file rpmalloc.c.
 {
     _memory_global_reserve_master = master;
     _memory_global_reserve_count = reserve_span_count;
     _memory_global_reserve = reserve;
 }
References _memory_global_reserve, _memory_global_reserve_count, _memory_global_reserve_master, and master.
Referenced by _rpmalloc_heap_allocate_new(), and _rpmalloc_span_map_aligned_count().
_rpmalloc_heap_allocate()
static heap_t* _rpmalloc_heap_allocate (int first_class) static
Allocate a new heap, potentially reusing a previously orphaned heap.
Definition at line 1978 of file rpmalloc.c.
 {
     heap_t *heap = 0;
     while (!atomic_cas32_acquire(&_memory_global_lock, 1, 0))
         _rpmalloc_spin();
     if (first_class == 0)
         heap = _rpmalloc_heap_extract_orphan(&_memory_orphan_heaps);
 #if RPMALLOC_FIRST_CLASS_HEAPS
     if (!heap)
         heap = _rpmalloc_heap_extract_orphan(&_memory_first_class_orphan_heaps);
 #endif
     if (!heap)
         heap = _rpmalloc_heap_allocate_new();
     atomic_store32_release(&_memory_global_lock, 0);
     _rpmalloc_heap_cache_adopt_deferred(heap, 0);
     return heap;
 }
References _memory_global_lock, _memory_orphan_heaps, _rpmalloc_heap_allocate_new(), _rpmalloc_heap_cache_adopt_deferred(), _rpmalloc_heap_extract_orphan(), _rpmalloc_spin(), atomic_cas32_acquire(), atomic_store32_release(), and heap.
Referenced by rpmalloc_thread_initialize().
_rpmalloc_heap_allocate_new()
static heap_t* _rpmalloc_heap_allocate_new (void) static
Allocate a new heap from newly mapped memory pages.
Definition at line 1887 of file rpmalloc.c.
 {
     // Map in pages for a 16 heaps. If page size is greater than required size for this, map a page and
     // use first part for heaps and remaining part for spans for allocations. Adds a lot of complexity,
     // but saves a lot of memory on systems where page size > 64 spans (4MiB)
     size_t heap_size = sizeof(heap_t);
     size_t aligned_heap_size = 16 * ((heap_size + 15) / 16);
     size_t request_heap_count = 16;
     size_t heap_span_count = ((aligned_heap_size * request_heap_count) + sizeof(span_t) + _memory_span_size - 1) / _memory_span_size;
     size_t block_size = _memory_span_size * heap_span_count;
     size_t span_count = heap_span_count;
     span_t *span = 0;
     // If there are global reserved spans, use these first
     if (_memory_global_reserve_count >= heap_span_count)
     {
         span = _rpmalloc_global_get_reserved_spans(heap_span_count);
     }
     if (!span)
     {
         if (_memory_page_size > block_size)
         {
             span_count = _memory_page_size / _memory_span_size;
             block_size = _memory_page_size;
             // If using huge pages, make sure to grab enough heaps to avoid reallocating a huge page just to serve new heaps
             size_t possible_heap_count = (block_size - sizeof(span_t)) / aligned_heap_size;
             if (possible_heap_count >= (request_heap_count * 16))
                 request_heap_count *= 16;
             else if (possible_heap_count < request_heap_count)
                 request_heap_count = possible_heap_count;
             heap_span_count = ((aligned_heap_size * request_heap_count) + sizeof(span_t) + _memory_span_size - 1) / _memory_span_size;
         }
         size_t align_offset = 0;
         span = (span_t *)_rpmalloc_mmap(block_size, &align_offset);
         if (!span)
             return 0;
         // Master span will contain the heaps
         _rpmalloc_stat_inc(&_master_spans);
         _rpmalloc_span_initialize(span, span_count, heap_span_count, align_offset);
     }
     size_t remain_size = _memory_span_size - sizeof(span_t);
     heap_t *heap = (heap_t *)pointer_offset(span, sizeof(span_t));
     _rpmalloc_heap_initialize(heap);
     // Put extra heaps as orphans
     size_t num_heaps = remain_size / aligned_heap_size;
     if (num_heaps < request_heap_count)
         num_heaps = request_heap_count;
     atomic_store32(&heap->child_count, (int32_t)num_heaps - 1);
     heap_t *extra_heap = (heap_t *)pointer_offset(heap, aligned_heap_size);
     while (num_heaps > 1)
     {
         _rpmalloc_heap_initialize(extra_heap);
         extra_heap->master_heap = heap;
         _rpmalloc_heap_orphan(extra_heap, 1);
         extra_heap = (heap_t *)pointer_offset(extra_heap, aligned_heap_size);
         --num_heaps;
     }
     if (span_count > heap_span_count)
     {
         // Cap reserved spans
         size_t remain_count = span_count - heap_span_count;
         size_t reserve_count = (remain_count > _memory_heap_reserve_count ? _memory_heap_reserve_count : remain_count);
         span_t *remain_span = (span_t *)pointer_offset(span, heap_span_count * _memory_span_size);
         _rpmalloc_heap_set_reserved_spans(heap, span, remain_span, reserve_count);
         if (remain_count > reserve_count)
         {
             // Set to global reserved spans
             remain_span = (span_t *)pointer_offset(remain_span, reserve_count * _memory_span_size);
             reserve_count = remain_count - reserve_count;
             _rpmalloc_global_set_reserved_spans(span, remain_span, reserve_count);
         }
     }
     return heap;
 }
References _memory_global_reserve_count, _memory_heap_reserve_count, _memory_page_size, _memory_span_size, _rpmalloc_global_get_reserved_spans(), _rpmalloc_global_set_reserved_spans(), _rpmalloc_heap_initialize(), _rpmalloc_heap_orphan(), _rpmalloc_heap_set_reserved_spans(), _rpmalloc_mmap(), _rpmalloc_span_initialize(), _rpmalloc_stat_inc, atomic_store32(), heap, heap_t::master_heap, and pointer_offset.
Referenced by _rpmalloc_heap_allocate().
_rpmalloc_heap_cache_adopt_deferred()
static void _rpmalloc_heap_cache_adopt_deferred (heap_t * heap, span_t ** single_span) static
Adopt the deferred span cache list, optionally extracting the first single span for immediate re-use.
Definition at line 1515 of file rpmalloc.c.
 {
     span_t *span = (span_t *)((void *)atomic_exchange_ptr_acquire(&heap->span_free_deferred, 0));
     while (span)
     {
         span_t *next_span = (span_t *)span->free_list;
         rpmalloc_assert(span->heap == heap, "Span heap pointer corrupted");
         if (EXPECTED(span->size_class < SIZE_CLASS_COUNT))
         {
             rpmalloc_assert(heap->full_span_count, "Heap span counter corrupted");
             --heap->full_span_count;
             _rpmalloc_stat_dec(&heap->span_use[0].spans_deferred);
 #if RPMALLOC_FIRST_CLASS_HEAPS
             _rpmalloc_span_double_link_list_remove(&heap->full_span[span->size_class], span);
 #endif
             _rpmalloc_stat_dec(&heap->span_use[0].current);
             _rpmalloc_stat_dec(&heap->size_class_use[span->size_class].spans_current);
             if (single_span && !*single_span)
                 *single_span = span;
             else
                 _rpmalloc_heap_cache_insert(heap, span);
         }
         else
         {
             if (span->size_class == SIZE_CLASS_HUGE)
             {
                 _rpmalloc_deallocate_huge(span);
             }
             else
             {
                 rpmalloc_assert(span->size_class == SIZE_CLASS_LARGE, "Span size class invalid");
                 rpmalloc_assert(heap->full_span_count, "Heap span counter corrupted");
                 --heap->full_span_count;
 #if RPMALLOC_FIRST_CLASS_HEAPS
                 _rpmalloc_span_double_link_list_remove(&heap->large_huge_span, span);
 #endif
                 uint32_t idx = span->span_count - 1;
                 _rpmalloc_stat_dec(&heap->span_use[idx].spans_deferred);
                 _rpmalloc_stat_dec(&heap->span_use[idx].current);
                 if (!idx && single_span && !*single_span)
                     *single_span = span;
                 else
                     _rpmalloc_heap_cache_insert(heap, span);
             }
         }
         span = next_span;
     }
 }
References _rpmalloc_deallocate_huge(), _rpmalloc_heap_cache_insert(), _rpmalloc_span_double_link_list_remove(), _rpmalloc_stat_dec, atomic_exchange_ptr_acquire(), EXPECTED, span_t::free_list, span_t::heap, heap, idx, rpmalloc_assert, span_t::size_class, SIZE_CLASS_COUNT, SIZE_CLASS_HUGE, SIZE_CLASS_LARGE, and span_t::span_count.
Referenced by _rpmalloc_allocate_huge(), _rpmalloc_heap_allocate(), _rpmalloc_heap_finalize(), _rpmalloc_heap_release(), and _rpmalloc_heap_thread_cache_deferred_extract().
_rpmalloc_heap_cache_insert()
static void _rpmalloc_heap_cache_insert (heap_t * heap, span_t * span) static
Insert a single span into thread heap cache, releasing to global cache if overflow.
Span control
Definition at line 1642 of file rpmalloc.c.
 {
     if (UNEXPECTED(heap->finalize != 0))
     {
         _rpmalloc_span_unmap(span);
         _rpmalloc_heap_global_finalize(heap);
         return;
     }
 #if ENABLE_THREAD_CACHE
     size_t span_count = span->span_count;
     _rpmalloc_stat_inc(&heap->span_use[span_count - 1].spans_to_cache);
     if (span_count == 1)
     {
         span_cache_t *span_cache = &heap->span_cache;
         span_cache->span[span_cache->count++] = span;
         if (span_cache->count == MAX_THREAD_SPAN_CACHE)
         {
             const size_t remain_count = MAX_THREAD_SPAN_CACHE - THREAD_SPAN_CACHE_TRANSFER;
 #if ENABLE_GLOBAL_CACHE
             _rpmalloc_stat_add64(&heap->thread_to_global, THREAD_SPAN_CACHE_TRANSFER * _memory_span_size);
             _rpmalloc_stat_add(&heap->span_use[span_count - 1].spans_to_global, THREAD_SPAN_CACHE_TRANSFER);
             _rpmalloc_global_cache_insert_spans(span_cache->span + remain_count, span_count, THREAD_SPAN_CACHE_TRANSFER);
 #else
             for (size_t ispan = 0; ispan < THREAD_SPAN_CACHE_TRANSFER; ++ispan)
                 _rpmalloc_span_unmap(span_cache->span[remain_count + ispan]);
 #endif
             span_cache->count = remain_count;
         }
     }
     else
     {
         size_t cache_idx = span_count - 2;
         span_large_cache_t *span_cache = heap->span_large_cache + cache_idx;
         span_cache->span[span_cache->count++] = span;
         const size_t cache_limit = (MAX_THREAD_SPAN_LARGE_CACHE - (span_count >> 1));
         if (span_cache->count == cache_limit)
         {
             const size_t transfer_limit = 2 + (cache_limit >> 2);
             const size_t transfer_count = (THREAD_SPAN_LARGE_CACHE_TRANSFER <= transfer_limit ? THREAD_SPAN_LARGE_CACHE_TRANSFER : transfer_limit);
             const size_t remain_count = cache_limit - transfer_count;
 #if ENABLE_GLOBAL_CACHE
             _rpmalloc_stat_add64(&heap->thread_to_global, transfer_count * span_count * _memory_span_size);
             _rpmalloc_stat_add(&heap->span_use[span_count - 1].spans_to_global, transfer_count);
             _rpmalloc_global_cache_insert_spans(span_cache->span + remain_count, span_count, transfer_count);
 #else
             for (size_t ispan = 0; ispan < transfer_count; ++ispan)
                 _rpmalloc_span_unmap(span_cache->span[remain_count + ispan]);
 #endif
             span_cache->count = remain_count;
         }
     }
 #else
     (void)sizeof(heap);
     _rpmalloc_span_unmap(span);
 #endif
 }
References _memory_span_size, _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_global_finalize(), _rpmalloc_span_unmap(), _rpmalloc_stat_add, _rpmalloc_stat_add64, _rpmalloc_stat_inc, span_cache_t::count, span_large_cache_t::count, heap, MAX_THREAD_SPAN_CACHE, MAX_THREAD_SPAN_LARGE_CACHE, span_cache_t::span, span_large_cache_t::span, span_t::span_count, THREAD_SPAN_CACHE_TRANSFER, THREAD_SPAN_LARGE_CACHE_TRANSFER, and UNEXPECTED.
Referenced by _rpmalloc_deallocate_large(), _rpmalloc_heap_cache_adopt_deferred(), _rpmalloc_span_map_aligned_count(), and _rpmalloc_span_release_to_cache().
_rpmalloc_heap_extract_new_span()
static span_t* _rpmalloc_heap_extract_new_span (heap_t * heap, heap_size_class_t * heap_size_class, size_t span_count, uint32_t class_idx) static
Get a span from one of the cache levels (thread cache, reserved, global cache) or fallback to mapping more memory.
Definition at line 1801 of file rpmalloc.c.
 {
     span_t *span;
 #if ENABLE_THREAD_CACHE
     if (heap_size_class && heap_size_class->cache)
     {
         span = heap_size_class->cache;
         heap_size_class->cache = (heap->span_cache.count ? heap->span_cache.span[--heap->span_cache.count] : 0);
         _rpmalloc_inc_span_statistics(heap, span_count, class_idx);
         return span;
     }
 #endif
     (void)sizeof(class_idx);
     // Allow 50% overhead to increase cache hits
     size_t base_span_count = span_count;
     size_t limit_span_count = (span_count > 2) ? (span_count + (span_count >> 1)) : span_count;
     if (limit_span_count > LARGE_CLASS_COUNT)
         limit_span_count = LARGE_CLASS_COUNT;
     do
     {
         span = _rpmalloc_heap_thread_cache_extract(heap, span_count);
         if (EXPECTED(span != 0))
         {
             _rpmalloc_stat_inc(&heap->size_class_use[class_idx].spans_from_cache);
             _rpmalloc_inc_span_statistics(heap, span_count, class_idx);
             return span;
         }
         span = _rpmalloc_heap_thread_cache_deferred_extract(heap, span_count);
         if (EXPECTED(span != 0))
         {
             _rpmalloc_stat_inc(&heap->size_class_use[class_idx].spans_from_cache);
             _rpmalloc_inc_span_statistics(heap, span_count, class_idx);
             return span;
         }
         span = _rpmalloc_heap_reserved_extract(heap, span_count);
         if (EXPECTED(span != 0))
         {
             _rpmalloc_stat_inc(&heap->size_class_use[class_idx].spans_from_reserved);
             _rpmalloc_inc_span_statistics(heap, span_count, class_idx);
             return span;
         }
         span = _rpmalloc_heap_global_cache_extract(heap, span_count);
         if (EXPECTED(span != 0))
         {
             _rpmalloc_stat_inc(&heap->size_class_use[class_idx].spans_from_cache);
             _rpmalloc_inc_span_statistics(heap, span_count, class_idx);
             return span;
         }
         ++span_count;
     } while (span_count <= limit_span_count);
     // Final fallback, map in more virtual memory
     span = _rpmalloc_span_map(heap, base_span_count);
     _rpmalloc_inc_span_statistics(heap, base_span_count, class_idx);
     _rpmalloc_stat_inc(&heap->size_class_use[class_idx].spans_map_calls);
     return span;
 }
References _rpmalloc_heap_global_cache_extract(), _rpmalloc_heap_reserved_extract(), _rpmalloc_heap_thread_cache_deferred_extract(), _rpmalloc_heap_thread_cache_extract(), _rpmalloc_inc_span_statistics(), _rpmalloc_span_map(), _rpmalloc_stat_inc, heap_size_class_t::cache, EXPECTED, heap, and LARGE_CLASS_COUNT.
Referenced by _rpmalloc_allocate_from_heap_fallback(), and _rpmalloc_allocate_large().
_rpmalloc_heap_extract_orphan()
static heap_t* _rpmalloc_heap_extract_orphan (heap_t ** heap_list) static
Definition at line 1969 of file rpmalloc.c.
 {
     heap_t *heap = *heap_list;
     *heap_list = (heap ? heap->next_orphan : 0);
     return heap;
 }
References heap.
Referenced by _rpmalloc_heap_allocate().
_rpmalloc_heap_finalize()
static void _rpmalloc_heap_finalize (heap_t * heap) static
Definition at line 2069 of file rpmalloc.c.
 {
     if (heap->spans_reserved)
     {
         span_t *span = _rpmalloc_span_map(heap, heap->spans_reserved);
         _rpmalloc_span_unmap(span);
         heap->spans_reserved = 0;
     }
     _rpmalloc_heap_cache_adopt_deferred(heap, 0);
     for (size_t iclass = 0; iclass < SIZE_CLASS_COUNT; ++iclass)
     {
         if (heap->size_class[iclass].cache)
             _rpmalloc_span_unmap(heap->size_class[iclass].cache);
         heap->size_class[iclass].cache = 0;
         span_t *span = heap->size_class[iclass].partial_span;
         while (span)
         {
             span_t *next = span->next;
             _rpmalloc_span_finalize(heap, iclass, span, &heap->size_class[iclass].partial_span);
             span = next;
         }
         // If class still has a free list it must be a full span
         if (heap->size_class[iclass].free_list)
         {
             span_t *class_span = (span_t *)((uintptr_t)heap->size_class[iclass].free_list & _memory_span_mask);
             span_t **list = 0;
 #if RPMALLOC_FIRST_CLASS_HEAPS
             list = &heap->full_span[iclass];
 #endif
             --heap->full_span_count;
             if (!_rpmalloc_span_finalize(heap, iclass, class_span, list))
             {
                 if (list)
                     _rpmalloc_span_double_link_list_remove(list, class_span);
                 _rpmalloc_span_double_link_list_add(&heap->size_class[iclass].partial_span, class_span);
             }
         }
     }
 #if ENABLE_THREAD_CACHE
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
     {
         span_cache_t *span_cache;
         if (!iclass)
             span_cache = &heap->span_cache;
         else
             span_cache = (span_cache_t *)(heap->span_large_cache + (iclass - 1));
         for (size_t ispan = 0; ispan < span_cache->count; ++ispan)
             _rpmalloc_span_unmap(span_cache->span[ispan]);
         span_cache->count = 0;
     }
 #endif
     rpmalloc_assert(!atomic_load_ptr(&heap->span_free_deferred), "Heaps still active during finalization");
 }
References _memory_span_mask, _rpmalloc_heap_cache_adopt_deferred(), _rpmalloc_span_double_link_list_add(), _rpmalloc_span_double_link_list_remove(), _rpmalloc_span_finalize(), _rpmalloc_span_map(), _rpmalloc_span_unmap(), atomic_load_ptr(), span_cache_t::count, heap, LARGE_CLASS_COUNT, list(), span_t::next, next, rpmalloc_assert, SIZE_CLASS_COUNT, and span_cache_t::span.
Referenced by _rpmalloc_heap_global_finalize().
_rpmalloc_heap_global_cache_extract()
static span_t* _rpmalloc_heap_global_cache_extract (heap_t * heap, size_t span_count) static
Extract a span from the global cache.
Definition at line 1745 of file rpmalloc.c.
 {
 #if ENABLE_GLOBAL_CACHE
 #if ENABLE_THREAD_CACHE
     span_cache_t *span_cache;
     size_t wanted_count;
     if (span_count == 1)
     {
         span_cache = &heap->span_cache;
         wanted_count = THREAD_SPAN_CACHE_TRANSFER;
     }
     else
     {
         span_cache = (span_cache_t *)(heap->span_large_cache + (span_count - 2));
         wanted_count = THREAD_SPAN_LARGE_CACHE_TRANSFER;
     }
     span_cache->count = _rpmalloc_global_cache_extract_spans(span_cache->span, span_count, wanted_count);
     if (span_cache->count)
     {
         _rpmalloc_stat_add64(&heap->global_to_thread, span_count * span_cache->count * _memory_span_size);
         _rpmalloc_stat_add(&heap->span_use[span_count - 1].spans_from_global, span_cache->count);
         return span_cache->span[--span_cache->count];
     }
 #else
     span_t *span = 0;
     size_t count = _rpmalloc_global_cache_extract_spans(&span, span_count, 1);
     if (count)
     {
         _rpmalloc_stat_add64(&heap->global_to_thread, span_count * count * _memory_span_size);
         _rpmalloc_stat_add(&heap->span_use[span_count - 1].spans_from_global, count);
         return span;
     }
 #endif
 #endif
     (void)sizeof(heap);
     (void)sizeof(span_count);
     return 0;
 }
References _memory_span_size, _rpmalloc_global_cache_extract_spans(), _rpmalloc_stat_add, _rpmalloc_stat_add64, span_cache_t::count, count, heap, span_cache_t::span, THREAD_SPAN_CACHE_TRANSFER, and THREAD_SPAN_LARGE_CACHE_TRANSFER.
Referenced by _rpmalloc_heap_extract_new_span().
_rpmalloc_heap_global_finalize()
static void _rpmalloc_heap_global_finalize (heap_t * heap) static
Definition at line 1585 of file rpmalloc.c.
 {
     if (heap->finalize++ > 1)
     {
         --heap->finalize;
         return;
     }
     _rpmalloc_heap_finalize(heap);
 #if ENABLE_THREAD_CACHE
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
     {
         span_cache_t *span_cache;
         if (!iclass)
             span_cache = &heap->span_cache;
         else
             span_cache = (span_cache_t *)(heap->span_large_cache + (iclass - 1));
         for (size_t ispan = 0; ispan < span_cache->count; ++ispan)
             _rpmalloc_span_unmap(span_cache->span[ispan]);
         span_cache->count = 0;
     }
 #endif
     if (heap->full_span_count)
     {
         --heap->finalize;
         return;
     }
     for (size_t iclass = 0; iclass < SIZE_CLASS_COUNT; ++iclass)
     {
         if (heap->size_class[iclass].free_list || heap->size_class[iclass].partial_span)
         {
             --heap->finalize;
             return;
         }
     }
     // Heap is now completely free, unmap and remove from heap list
     size_t list_idx = (size_t)heap->id % HEAP_ARRAY_SIZE;
     heap_t *list_heap = _memory_heaps[list_idx];
     if (list_heap == heap)
     {
         _memory_heaps[list_idx] = heap->next_heap;
     }
     else
     {
         while (list_heap->next_heap != heap)
             list_heap = list_heap->next_heap;
         list_heap->next_heap = heap->next_heap;
     }
     _rpmalloc_heap_unmap(heap);
 }
References _memory_heaps, _rpmalloc_heap_finalize(), _rpmalloc_heap_unmap(), _rpmalloc_span_unmap(), span_cache_t::count, heap, HEAP_ARRAY_SIZE, if(), LARGE_CLASS_COUNT, SIZE_CLASS_COUNT, and span_cache_t::span.
Referenced by _rpmalloc_heap_cache_insert(), and rpmalloc_finalize().
_rpmalloc_heap_initialize()
static void _rpmalloc_heap_initialize (heap_t * heap) static
Definition at line 1859 of file rpmalloc.c.
 {
     memset_unsafe(heap, 0, sizeof(heap_t));
     // Get a new heap ID
     heap->id = 1 + atomic_incr32(&_memory_heap_id);
     // Link in heap in heap ID map
     size_t list_idx = (size_t)heap->id % HEAP_ARRAY_SIZE;
     heap->next_heap = _memory_heaps[list_idx];
     _memory_heaps[list_idx] = heap;
 }
References _memory_heap_id, _memory_heaps, atomic_incr32(), heap, HEAP_ARRAY_SIZE, and memset_unsafe().
Referenced by _rpmalloc_heap_allocate_new().
_rpmalloc_heap_orphan()
static void _rpmalloc_heap_orphan (heap_t * heap, int first_class) static
Definition at line 1872 of file rpmalloc.c.
 {
     heap->owner_thread = (uintptr_t)-1;
 #if RPMALLOC_FIRST_CLASS_HEAPS
     heap_t **heap_list = (first_class ? &_memory_first_class_orphan_heaps : &_memory_orphan_heaps);
 #else
     (void)sizeof(first_class);
     heap_t **heap_list = &_memory_orphan_heaps;
 #endif
     heap->next_orphan = *heap_list;
     *heap_list = heap;
 }
References _memory_orphan_heaps, and heap.
Referenced by _rpmalloc_heap_allocate_new(), and _rpmalloc_heap_release().
_rpmalloc_heap_release()
static void _rpmalloc_heap_release (void * heapptr, int first_class, int release_cache) static
Definition at line 1997 of file rpmalloc.c.
 {
     heap_t *heap = (heap_t *)heapptr;
     if (!heap)
         return;
     // Release thread cache spans back to global cache
     _rpmalloc_heap_cache_adopt_deferred(heap, 0);
     if (release_cache || heap->finalize)
     {
 #if ENABLE_THREAD_CACHE
         for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
         {
             span_cache_t *span_cache;
             if (!iclass)
                 span_cache = &heap->span_cache;
             else
                 span_cache = (span_cache_t *)(heap->span_large_cache + (iclass - 1));
             if (!span_cache->count)
                 continue;
 #if ENABLE_GLOBAL_CACHE
             if (heap->finalize)
             {
                 for (size_t ispan = 0; ispan < span_cache->count; ++ispan)
                     _rpmalloc_span_unmap(span_cache->span[ispan]);
             }
             else
             {
                 _rpmalloc_stat_add64(&heap->thread_to_global, span_cache->count * (iclass + 1) * _memory_span_size);
                 _rpmalloc_stat_add(&heap->span_use[iclass].spans_to_global, span_cache->count);
                 _rpmalloc_global_cache_insert_spans(span_cache->span, iclass + 1, span_cache->count);
             }
 #else
             for (size_t ispan = 0; ispan < span_cache->count; ++ispan)
                 _rpmalloc_span_unmap(span_cache->span[ispan]);
 #endif
             span_cache->count = 0;
         }
 #endif
     }
     if (get_thread_heap_raw() == heap)
         set_thread_heap(0);
 #if ENABLE_STATISTICS
     atomic_decr32(&_memory_active_heaps);
     rpmalloc_assert(atomic_load32(&_memory_active_heaps) >= 0, "Still active heaps during finalization");
 #endif
     // If we are forcibly terminating with _exit the state of the
     // lock atomic is unknown and it's best to just go ahead and exit
     if (get_thread_id() != _rpmalloc_main_thread_id)
     {
         while (!atomic_cas32_acquire(&_memory_global_lock, 1, 0))
             _rpmalloc_spin();
     }
     _rpmalloc_heap_orphan(heap, first_class);
     atomic_store32_release(&_memory_global_lock, 0);
 }
References _memory_global_lock, _memory_span_size, _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_cache_adopt_deferred(), _rpmalloc_heap_orphan(), _rpmalloc_main_thread_id, _rpmalloc_span_unmap(), _rpmalloc_spin(), _rpmalloc_stat_add, _rpmalloc_stat_add64, atomic_cas32_acquire(), atomic_decr32(), atomic_store32_release(), span_cache_t::count, get_thread_heap_raw(), get_thread_id(), heap, LARGE_CLASS_COUNT, rpmalloc_assert, set_thread_heap(), and span_cache_t::span.
Referenced by _rpmalloc_heap_release_raw().
_rpmalloc_heap_release_raw()
static void _rpmalloc_heap_release_raw (void * heapptr, int release_cache) static
Definition at line 2057 of file rpmalloc.c.
 {
     _rpmalloc_heap_release(heapptr, 0, release_cache);
 }
References _rpmalloc_heap_release().
Referenced by _rpmalloc_heap_release_raw_fc(), and rpmalloc_thread_finalize().
_rpmalloc_heap_release_raw_fc()
static void _rpmalloc_heap_release_raw_fc (void * heapptr) static
Definition at line 2063 of file rpmalloc.c.
 {
     _rpmalloc_heap_release_raw(heapptr, 1);
 }
References _rpmalloc_heap_release_raw().
Referenced by rpmalloc_initialize_config().
_rpmalloc_heap_reserved_extract()
static span_t* _rpmalloc_heap_reserved_extract (heap_t * heap, size_t span_count) static
Definition at line 1736 of file rpmalloc.c.
 {
     if (heap->spans_reserved >= span_count)
         return _rpmalloc_span_map(heap, span_count);
     return 0;
 }
References _rpmalloc_span_map(), and heap.
Referenced by _rpmalloc_heap_extract_new_span().
_rpmalloc_heap_set_reserved_spans()
static void _rpmalloc_heap_set_reserved_spans (heap_t * heap, span_t * master, span_t * reserve, size_t reserve_span_count) static
Store the given spans as reserve in the given heap.
Definition at line 1506 of file rpmalloc.c.
 {
     heap->span_reserve_master = master;
     heap->span_reserve = reserve;
     heap->spans_reserved = (uint32_t)reserve_span_count;
 }
References heap, and master.
Referenced by _rpmalloc_heap_allocate_new(), _rpmalloc_span_map(), and _rpmalloc_span_map_aligned_count().
_rpmalloc_heap_thread_cache_deferred_extract()
static span_t* _rpmalloc_heap_thread_cache_deferred_extract (heap_t * heap, size_t span_count) static
Definition at line 1720 of file rpmalloc.c.
 {
     span_t *span = 0;
     if (span_count == 1)
     {
         _rpmalloc_heap_cache_adopt_deferred(heap, &span);
     }
     else
     {
         _rpmalloc_heap_cache_adopt_deferred(heap, 0);
         span = _rpmalloc_heap_thread_cache_extract(heap, span_count);
     }
     return span;
 }
References _rpmalloc_heap_cache_adopt_deferred(), _rpmalloc_heap_thread_cache_extract(), and heap.
Referenced by _rpmalloc_heap_extract_new_span().
_rpmalloc_heap_thread_cache_extract()
static span_t* _rpmalloc_heap_thread_cache_extract (heap_t * heap, size_t span_count) static
Extract the given number of spans from the different cache levels.
Definition at line 1701 of file rpmalloc.c.
 {
     span_t *span = 0;
 #if ENABLE_THREAD_CACHE
     span_cache_t *span_cache;
     if (span_count == 1)
         span_cache = &heap->span_cache;
     else
         span_cache = (span_cache_t *)(heap->span_large_cache + (span_count - 2));
     if (span_cache->count)
     {
         _rpmalloc_stat_inc(&heap->span_use[span_count - 1].spans_from_cache);
         return span_cache->span[--span_cache->count];
     }
 #endif
     return span;
 }
References _rpmalloc_stat_inc, span_cache_t::count, heap, and span_cache_t::span.
Referenced by _rpmalloc_heap_extract_new_span(), and _rpmalloc_heap_thread_cache_deferred_extract().
_rpmalloc_heap_unmap()
static void _rpmalloc_heap_unmap (heap_t * heap) static
Definition at line 1565 of file rpmalloc.c.
 {
     if (!heap->master_heap)
     {
         if ((heap->finalize > 1) && !atomic_load32(&heap->child_count))
         {
             span_t *span = (span_t *)((uintptr_t)heap & _memory_span_mask);
             _rpmalloc_span_unmap(span);
         }
     }
     else
     {
         if (atomic_decr32(&heap->master_heap->child_count) == 0)
         {
             _rpmalloc_heap_unmap(heap->master_heap);
         }
     }
 }
References _memory_span_mask, _rpmalloc_span_unmap(), atomic_decr32(), and heap.
Referenced by _rpmalloc_heap_global_finalize().
_rpmalloc_inc_span_statistics()
static void _rpmalloc_inc_span_statistics (heap_t * heap, size_t span_count, uint32_t class_idx) static
Definition at line 1785 of file rpmalloc.c.
 {
     (void)sizeof(heap);
     (void)sizeof(span_count);
     (void)sizeof(class_idx);
 #if ENABLE_ADAPTIVE_THREAD_CACHE || ENABLE_STATISTICS
     uint32_t idx = (uint32_t)span_count - 1;
     uint32_t current_count = (uint32_t)atomic_incr32(&heap->span_use[idx].current);
     if (current_count > (uint32_t)atomic_load32(&heap->span_use[idx].high))
         atomic_store32(&heap->span_use[idx].high, (int32_t)current_count);
     _rpmalloc_stat_add_peak(&heap->size_class_use[class_idx].spans_current, 1, heap->size_class_use[class_idx].spans_peak);
 #endif
 }
References _rpmalloc_stat_add_peak, atomic_incr32(), atomic_store32(), heap, and idx.
Referenced by _rpmalloc_heap_extract_new_span().
_rpmalloc_mmap()
static void* _rpmalloc_mmap (size_t size, size_t * offset) static
Map more virtual memory.
Definition at line 801 of file rpmalloc.c.
 {
     rpmalloc_assert(!(size % _memory_page_size), "Invalid mmap size");
     rpmalloc_assert(size >= _memory_page_size, "Invalid mmap size");
     void *address = _memory_config.memory_map(size, offset);
     if (EXPECTED(address != 0))
     {
         _rpmalloc_stat_add_peak(&_mapped_pages, (size >> _memory_page_size_shift), _mapped_pages_peak);
         _rpmalloc_stat_add(&_mapped_total, (size >> _memory_page_size_shift));
     }
     return address;
 }
References _memory_config, _memory_page_size, _memory_page_size_shift, _rpmalloc_stat_add, _rpmalloc_stat_add_peak, EXPECTED, rpmalloc_config_t::memory_map, offset, rpmalloc_assert, and size.
Referenced by _rpmalloc_aligned_allocate(), _rpmalloc_allocate_huge(), _rpmalloc_heap_allocate_new(), and _rpmalloc_span_map_aligned_count().
_rpmalloc_mmap_os()
static void* _rpmalloc_mmap_os (size_t size, size_t * offset) static
Default implementation to map new pages to virtual memory.
Definition at line 835 of file rpmalloc.c.
 {
     // Either size is a heap (a single page) or a (multiple) span - we only need to align spans, and only if larger than map granularity
     size_t padding = ((size >= _memory_span_size) && (_memory_span_size > _memory_map_granularity)) ? _memory_span_size : 0;
     rpmalloc_assert(size >= _memory_page_size, "Invalid mmap size");
     int flags = MAP_PRIVATE | MAP_ANONYMOUS | MAP_UNINITIALIZED;
     void *ptr = __rpmalloc_mmap(0, size + padding, PROT_READ | PROT_WRITE, flags, -1, 0);
     if ((ptr == MAP_FAILED) || !ptr)
     {
         if (_memory_config.map_fail_callback)
         {
             if (_memory_config.map_fail_callback(size + padding))
                 return _rpmalloc_mmap_os(size, offset);
         }
         else if (errno != ENOMEM)
         {
             rpmalloc_assert((ptr != MAP_FAILED) && ptr, "Failed to map virtual memory block");
         }
         return 0;
     }
     _rpmalloc_stat_add(&_mapped_pages_os, (int32_t)((size + padding) >> _memory_page_size_shift));
     if (padding)
     {
         size_t final_padding = padding - ((uintptr_t)ptr & ~_memory_span_mask);
         rpmalloc_assert(final_padding <= _memory_span_size, "Internal failure in padding");
         rpmalloc_assert(final_padding <= padding, "Internal failure in padding");
         rpmalloc_assert(!(final_padding % 8), "Internal failure in padding");
         ptr = pointer_offset(ptr, final_padding);
         *offset = final_padding >> 3;
     }
     rpmalloc_assert((size < _memory_span_size) || !((uintptr_t)ptr & ~_memory_span_mask), "Internal failure in padding");
     return ptr;
 }
References __rpmalloc_mmap(), _memory_config, _memory_map_granularity, _memory_page_size, _memory_page_size_shift, _memory_span_mask, _memory_span_size, _rpmalloc_stat_add, ENOMEM, errno, flags, MAP_ANONYMOUS, rpmalloc_config_t::map_fail_callback, MAP_FAILED, MAP_PRIVATE, MAP_UNINITIALIZED, offset, pointer_offset, PROT_READ, PROT_WRITE, rpmalloc_assert, and size.
Referenced by rpmalloc_initialize_config().
_rpmalloc_reallocate()
static void* _rpmalloc_reallocate (heap_t * heap, void * p, size_t size, size_t oldsize, unsigned int flags) static
Reallocate the given block to the given size.
Definition at line 2641 of file rpmalloc.c.
 {
     if (p)
     {
         // Grab the span using guaranteed span alignment
         span_t *span = (span_t *)((uintptr_t)p & _memory_span_mask);
         if (EXPECTED(span->size_class < SIZE_CLASS_COUNT))
         {
             // Small/medium sized block
             rpmalloc_assert(span->span_count == 1, "Span counter corrupted");
             void *blocks_start = pointer_offset(span, SPAN_HEADER_SIZE);
             uint32_t block_offset = (uint32_t)pointer_diff(p, blocks_start);
             uint32_t block_idx = block_offset / span->block_size;
             void *block = pointer_offset(blocks_start, (size_t)block_idx * span->block_size);
             if (!oldsize)
                 oldsize = (size_t)((ptrdiff_t)span->block_size - pointer_diff(p, block));
             if ((size_t)span->block_size >= size)
             {
                 // Still fits in block, never mind trying to save memory, but preserve data if alignment changed
                 if ((p != block) && !(flags & RPMALLOC_NO_PRESERVE))
                     memmove_unsafe(block, p, oldsize);
                 return block;
             }
         }
         else if (span->size_class == SIZE_CLASS_LARGE)
         {
             // Large block
             size_t total_size = size + SPAN_HEADER_SIZE;
             size_t num_spans = total_size >> _memory_span_size_shift;
             if (total_size & (_memory_span_mask - 1))
                 ++num_spans;
             size_t current_spans = span->span_count;
             void *block = pointer_offset(span, SPAN_HEADER_SIZE);
             if (!oldsize)
                 oldsize = (current_spans * _memory_span_size) - (size_t)pointer_diff(p, block) - SPAN_HEADER_SIZE;
             if ((current_spans >= num_spans) && (total_size >= (oldsize / 2)))
             {
                 // Still fits in block, never mind trying to save memory, but preserve data if alignment changed
                 if ((p != block) && !(flags & RPMALLOC_NO_PRESERVE))
                     memmove_unsafe(block, p, oldsize);
                 return block;
             }
         }
         else
         {
             // Oversized block
             size_t total_size = size + SPAN_HEADER_SIZE;
             size_t num_pages = total_size >> _memory_page_size_shift;
             if (total_size & (_memory_page_size - 1))
                 ++num_pages;
             // Page count is stored in span_count
             size_t current_pages = span->span_count;
             void *block = pointer_offset(span, SPAN_HEADER_SIZE);
             if (!oldsize)
                 oldsize = (current_pages * _memory_page_size) - (size_t)pointer_diff(p, block) - SPAN_HEADER_SIZE;
             if ((current_pages >= num_pages) && (num_pages >= (current_pages / 2)))
             {
                 // Still fits in block, never mind trying to save memory, but preserve data if alignment changed
                 if ((p != block) && !(flags & RPMALLOC_NO_PRESERVE))
                     memmove_unsafe(block, p, oldsize);
                 return block;
             }
         }
     }
     else
     {
         oldsize = 0;
     }
     if (!!(flags & RPMALLOC_GROW_OR_FAIL))
         return 0;
     // Size is greater than block size, need to allocate a new block and deallocate the old
     // Avoid hysteresis by overallocating if increase is small (below 37%)
     size_t lower_bound = oldsize + (oldsize >> 2) + (oldsize >> 3);
     size_t new_size = (size > lower_bound) ? size : ((size > oldsize) ? lower_bound : size);
     void *block = _rpmalloc_allocate(heap, new_size);
     if (p && block)
     {
         if (!(flags & RPMALLOC_NO_PRESERVE))
             memcpy_unsafe(block, p, oldsize < new_size ? oldsize : new_size);
         _rpmalloc_deallocate(p);
     }
     return block;
 }
References _memory_page_size, _memory_page_size_shift, _memory_span_mask, _memory_span_size, _memory_span_size_shift, _rpmalloc_allocate(), _rpmalloc_deallocate(), span_t::block_size, EXPECTED, flags, heap, memcpy_unsafe(), memmove_unsafe(), p, pointer_diff, pointer_offset, rpmalloc_assert, RPMALLOC_GROW_OR_FAIL, RPMALLOC_NO_PRESERVE, size, span_t::size_class, SIZE_CLASS_COUNT, SIZE_CLASS_LARGE, span_t::span_count, and SPAN_HEADER_SIZE.
Referenced by _rpmalloc_aligned_reallocate(), and rprealloc().
_rpmalloc_set_name()
static void _rpmalloc_set_name (void * address, size_t size) static
Low level memory map/unmap
Definition at line 781 of file rpmalloc.c.
 {
 #if defined(__linux__) || defined(__ANDROID__)
     const char *name = _memory_huge_pages ? _memory_config.huge_page_name : _memory_config.page_name;
     if (address == MAP_FAILED || !name)
         return;
     // If the kernel does not support CONFIG_ANON_VMA_NAME or if the call fails
     // (e.g. invalid name) it is a no-op basically.
     (void)prctl(PR_SET_VMA, PR_SET_VMA_ANON_NAME, (uintptr_t)address, size, (uintptr_t)name);
 #else
     (void)sizeof(size);
     (void)sizeof(address);
 #endif
 }
References _memory_config, _memory_huge_pages, rpmalloc_config_t::huge_page_name, MAP_FAILED, rpmalloc_config_t::page_name, prctl(), and size.
_rpmalloc_span_align_count()
static size_t _rpmalloc_span_align_count (size_t span_count) static
Get the aligned number of spans to map in based on wanted count, configured mapping granularity and the page size.
Definition at line 1026 of file rpmalloc.c.
 {
     size_t request_count = (span_count > _memory_span_map_count) ? span_count : _memory_span_map_count;
     if ((_memory_page_size > _memory_span_size) && ((request_count * _memory_span_size) % _memory_page_size))
         request_count += _memory_span_map_count - (request_count % _memory_span_map_count);
     return request_count;
 }
References _memory_page_size, _memory_span_map_count, and _memory_span_size.
Referenced by _rpmalloc_span_map_aligned_count().
_rpmalloc_span_double_link_list_add()
static void _rpmalloc_span_double_link_list_add (span_t ** head, span_t * span) static
Add a span to double linked list at the head.
Span linked list management
Definition at line 943 of file rpmalloc.c.
 {
     if (*head)
         (*head)->prev = span;
     span->next = *head;
     *head = span;
 }
References head, and span_t::next.
Referenced by _rpmalloc_aligned_allocate(), _rpmalloc_allocate_from_heap_fallback(), _rpmalloc_allocate_huge(), _rpmalloc_allocate_large(), _rpmalloc_deallocate_direct_small_or_medium(), _rpmalloc_heap_finalize(), and _rpmalloc_span_initialize_new().
_rpmalloc_span_double_link_list_pop_head()
static void _rpmalloc_span_double_link_list_pop_head (span_t ** head, span_t * span) static
Pop head span from double linked list.
Definition at line 953 of file rpmalloc.c.
 {
     rpmalloc_assert(*head == span, "Linked list corrupted");
     span = *head;
     *head = span->next;
 }
References head, span_t::next, and rpmalloc_assert.
Referenced by _rpmalloc_allocate_from_heap_fallback().
_rpmalloc_span_double_link_list_remove()
static void _rpmalloc_span_double_link_list_remove (span_t ** head, span_t * span) static
Remove a span from double linked list.
Definition at line 962 of file rpmalloc.c.
 {
     rpmalloc_assert(*head, "Linked list corrupted");
     if (*head == span)
     {
         *head = span->next;
     }
     else
     {
         span_t *next_span = span->next;
         span_t *prev_span = span->prev;
         prev_span->next = next_span;
         if (EXPECTED(next_span != 0))
             next_span->prev = prev_span;
     }
 }
References EXPECTED, head, span_t::next, span_t::prev, and rpmalloc_assert.
Referenced by _rpmalloc_deallocate_direct_small_or_medium(), _rpmalloc_deallocate_huge(), _rpmalloc_deallocate_large(), _rpmalloc_heap_cache_adopt_deferred(), _rpmalloc_heap_finalize(), and _rpmalloc_span_finalize().
_rpmalloc_span_extract_free_list_deferred()
static void _rpmalloc_span_extract_free_list_deferred (span_t * span) static
Definition at line 1269 of file rpmalloc.c.
 {
     // We need acquire semantics on the CAS operation since we are interested in the list size
     // Refer to _rpmalloc_deallocate_defer_small_or_medium for further comments on this dependency
     do
     {
         span->free_list = atomic_exchange_ptr_acquire(&span->free_list_deferred, INVALID_POINTER);
     } while (span->free_list == INVALID_POINTER);
     span->used_count -= span->list_size;
     span->list_size = 0;
     atomic_store_ptr_release(&span->free_list_deferred, 0);
 }
References atomic_exchange_ptr_acquire(), atomic_store_ptr_release(), span_t::free_list, span_t::free_list_deferred, INVALID_POINTER, span_t::list_size, and span_t::used_count.
Referenced by _rpmalloc_allocate_from_heap_fallback().
_rpmalloc_span_finalize()
static int _rpmalloc_span_finalize (heap_t * heap, size_t iclass, span_t * span, span_t ** list_head) static
Definition at line 1290 of file rpmalloc.c.
 {
     void *free_list = heap->size_class[iclass].free_list;
     span_t *class_span = (span_t *)((uintptr_t)free_list & _memory_span_mask);
     if (span == class_span)
     {
         // Adopt the heap class free list back into the span free list
         void *block = span->free_list;
         void *last_block = 0;
         while (block)
         {
             last_block = block;
             block = *((void **)block);
         }
         uint32_t free_count = 0;
         block = free_list;
         while (block)
         {
             ++free_count;
             block = *((void **)block);
         }
         if (last_block)
         {
             *((void **)last_block) = free_list;
         }
         else
         {
             span->free_list = free_list;
         }
         heap->size_class[iclass].free_list = 0;
         span->used_count -= free_count;
     }
     // If this assert triggers you have memory leaks
     rpmalloc_assert(span->list_size == span->used_count, "Memory leak detected");
     if (span->list_size == span->used_count)
     {
         _rpmalloc_stat_dec(&heap->span_use[0].current);
         _rpmalloc_stat_dec(&heap->size_class_use[iclass].spans_current);
         // This function only used for spans in double linked lists
         if (list_head)
             _rpmalloc_span_double_link_list_remove(list_head, span);
         _rpmalloc_span_unmap(span);
         return 1;
     }
     return 0;
 }
References _memory_span_mask, _rpmalloc_span_double_link_list_remove(), _rpmalloc_span_unmap(), _rpmalloc_stat_dec, span_t::free_list, heap, span_t::list_size, rpmalloc_assert, and span_t::used_count.
Referenced by _rpmalloc_heap_finalize().
_rpmalloc_span_initialize()
static void _rpmalloc_span_initialize (span_t * span, size_t total_span_count, size_t span_count, size_t align_offset) static
Setup a newly mapped span.
Definition at line 1036 of file rpmalloc.c.
 {
     span->total_spans = (uint32_t)total_span_count;
     span->span_count = (uint32_t)span_count;
     span->align_offset = (uint32_t)align_offset;
     span->flags = SPAN_FLAG_MASTER;
     atomic_store32(&span->remaining_spans, (int32_t)total_span_count);
 }
References span_t::align_offset, atomic_store32(), span_t::flags, span_t::remaining_spans, span_t::span_count, SPAN_FLAG_MASTER, and span_t::total_spans.
Referenced by _rpmalloc_heap_allocate_new(), and _rpmalloc_span_map_aligned_count().
_rpmalloc_span_initialize_new()
static void* _rpmalloc_span_initialize_new (heap_t * heap, heap_size_class_t * heap_size_class, span_t * span, uint32_t class_idx) static
Initialize an unused span (from cache or mapped) to be new active span, putting the initial free list in heap class free list.
Definition at line 1234 of file rpmalloc.c.
 {
     rpmalloc_assert(span->span_count == 1, "Internal failure");
     size_class_t *size_class = _memory_size_class + class_idx;
     span->size_class = class_idx;
     span->heap = heap;
     span->flags &= ~SPAN_FLAG_ALIGNED_BLOCKS;
     span->block_size = size_class->block_size;
     span->block_count = size_class->block_count;
     span->free_list = 0;
     span->list_size = 0;
     atomic_store_ptr_release(&span->free_list_deferred, 0);
     // Setup free list. Only initialize one system page worth of free blocks in list
     void *block;
     span->free_list_limit = free_list_partial_init(&heap_size_class->free_list, &block,
                                                    span, pointer_offset(span, SPAN_HEADER_SIZE), size_class->block_count, size_class->block_size);
     // Link span as partial if there remains blocks to be initialized as free list, or full if fully initialized
     if (span->free_list_limit < span->block_count)
     {
         _rpmalloc_span_double_link_list_add(&heap_size_class->partial_span, span);
         span->used_count = span->free_list_limit;
     }
     else
     {
 #if RPMALLOC_FIRST_CLASS_HEAPS
         _rpmalloc_span_double_link_list_add(&heap->full_span[class_idx], span);
 #endif
         ++heap->full_span_count;
         span->used_count = span->block_count;
     }
     return block;
 }
References _memory_size_class, _rpmalloc_span_double_link_list_add(), atomic_store_ptr_release(), span_t::block_count, size_class_t::block_count, span_t::block_size, size_class_t::block_size, span_t::flags, span_t::free_list, heap_size_class_t::free_list, span_t::free_list_deferred, span_t::free_list_limit, free_list_partial_init(), span_t::heap, heap, span_t::list_size, heap_size_class_t::partial_span, pointer_offset, rpmalloc_assert, span_t::size_class, span_t::span_count, SPAN_FLAG_ALIGNED_BLOCKS, SPAN_HEADER_SIZE, and span_t::used_count.
Referenced by _rpmalloc_allocate_from_heap_fallback().
_rpmalloc_span_is_fully_utilized()
static int _rpmalloc_span_is_fully_utilized (span_t * span) static
Definition at line 1283 of file rpmalloc.c.
 {
     rpmalloc_assert(span->free_list_limit <= span->block_count, "Span free list corrupted");
     return !span->free_list && (span->free_list_limit >= span->block_count);
 }
References span_t::block_count, span_t::free_list, span_t::free_list_limit, and rpmalloc_assert.
Referenced by _rpmalloc_allocate_from_heap_fallback(), and _rpmalloc_deallocate_direct_small_or_medium().
_rpmalloc_span_map()
static span_t* _rpmalloc_span_map (heap_t * heap, size_t span_count) static
Map in memory pages for the given number of spans (or use previously reserved pages)
Definition at line 1093 of file rpmalloc.c.
 {
     if (span_count <= heap->spans_reserved)
         return _rpmalloc_span_map_from_reserve(heap, span_count);
     span_t *span = 0;
     int use_global_reserve = (_memory_page_size > _memory_span_size) || (_memory_span_map_count > _memory_heap_reserve_count);
     if (use_global_reserve)
     {
         // If huge pages, make sure only one thread maps more memory to avoid bloat
         while (!atomic_cas32_acquire(&_memory_global_lock, 1, 0))
             _rpmalloc_spin();
         if (_memory_global_reserve_count >= span_count)
         {
             size_t reserve_count = (!heap->spans_reserved ? _memory_heap_reserve_count : span_count);
             if (_memory_global_reserve_count < reserve_count)
                 reserve_count = _memory_global_reserve_count;
             span = _rpmalloc_global_get_reserved_spans(reserve_count);
             if (span)
             {
                 if (reserve_count > span_count)
                 {
                     span_t *reserved_span = (span_t *)pointer_offset(span, span_count << _memory_span_size_shift);
                     _rpmalloc_heap_set_reserved_spans(heap, _memory_global_reserve_master, reserved_span, reserve_count - span_count);
                 }
                 // Already marked as subspan in _rpmalloc_global_get_reserved_spans
                 span->span_count = (uint32_t)span_count;
             }
         }
     }
     if (!span)
         span = _rpmalloc_span_map_aligned_count(heap, span_count);
     if (use_global_reserve)
         atomic_store32_release(&_memory_global_lock, 0);
     return span;
 }
References _memory_global_lock, _memory_global_reserve_count, _memory_global_reserve_master, _memory_heap_reserve_count, _memory_page_size, _memory_span_map_count, _memory_span_size, _memory_span_size_shift, _rpmalloc_global_get_reserved_spans(), _rpmalloc_heap_set_reserved_spans(), _rpmalloc_span_map_aligned_count(), _rpmalloc_span_map_from_reserve(), _rpmalloc_spin(), atomic_cas32_acquire(), atomic_store32_release(), heap, pointer_offset, and span_t::span_count.
Referenced by _rpmalloc_heap_extract_new_span(), _rpmalloc_heap_finalize(), and _rpmalloc_heap_reserved_extract().
_rpmalloc_span_map_aligned_count()
static span_t* _rpmalloc_span_map_aligned_count (heap_t * heap, size_t span_count) static
Map an aligned set of spans, taking configured mapping granularity and the page size into account.
Definition at line 1050 of file rpmalloc.c.
 {
     // If we already have some, but not enough, reserved spans, release those to heap cache and map a new
     // full set of spans. Otherwise we would waste memory if page size > span size (huge pages)
     size_t aligned_span_count = _rpmalloc_span_align_count(span_count);
     size_t align_offset = 0;
     span_t *span = (span_t *)_rpmalloc_mmap(aligned_span_count * _memory_span_size, &align_offset);
     if (!span)
         return 0;
     _rpmalloc_span_initialize(span, aligned_span_count, span_count, align_offset);
     _rpmalloc_stat_inc(&_master_spans);
     if (span_count <= LARGE_CLASS_COUNT)
         _rpmalloc_stat_inc(&heap->span_use[span_count - 1].spans_map_calls);
     if (aligned_span_count > span_count)
     {
         span_t *reserved_spans = (span_t *)pointer_offset(span, span_count * _memory_span_size);
         size_t reserved_count = aligned_span_count - span_count;
         if (heap->spans_reserved)
         {
             _rpmalloc_span_mark_as_subspan_unless_master(heap->span_reserve_master, heap->span_reserve, heap->spans_reserved);
             _rpmalloc_heap_cache_insert(heap, heap->span_reserve);
         }
         if (reserved_count > _memory_heap_reserve_count)
         {
             // If huge pages or eager spam map count, the global reserve spin lock is held by caller, _rpmalloc_span_map
             rpmalloc_assert(atomic_load32(&_memory_global_lock) == 1, "Global spin lock not held as expected");
             size_t remain_count = reserved_count - _memory_heap_reserve_count;
             reserved_count = _memory_heap_reserve_count;
             span_t *remain_span = (span_t *)pointer_offset(reserved_spans, reserved_count * _memory_span_size);
             if (_memory_global_reserve)
             {
                 _rpmalloc_span_mark_as_subspan_unless_master(_memory_global_reserve_master, _memory_global_reserve, _memory_global_reserve_count);
                 _rpmalloc_span_unmap(_memory_global_reserve);
             }
             _rpmalloc_global_set_reserved_spans(span, remain_span, remain_count);
         }
         _rpmalloc_heap_set_reserved_spans(heap, span, reserved_spans, reserved_count);
     }
     return span;
 }
References _memory_global_lock, _memory_global_reserve, _memory_global_reserve_count, _memory_global_reserve_master, _memory_heap_reserve_count, _memory_span_size, _rpmalloc_global_set_reserved_spans(), _rpmalloc_heap_cache_insert(), _rpmalloc_heap_set_reserved_spans(), _rpmalloc_mmap(), _rpmalloc_span_align_count(), _rpmalloc_span_initialize(), _rpmalloc_span_mark_as_subspan_unless_master(), _rpmalloc_span_unmap(), _rpmalloc_stat_inc, heap, LARGE_CLASS_COUNT, pointer_offset, and rpmalloc_assert.
Referenced by _rpmalloc_span_map().
_rpmalloc_span_map_from_reserve()
static span_t* _rpmalloc_span_map_from_reserve (heap_t * heap, size_t span_count) static
Use reserved spans to fulfill a memory map request (reserve size must be checked by caller)
Definition at line 1010 of file rpmalloc.c.
 {
     // Update the heap span reserve
     span_t *span = heap->span_reserve;
     heap->span_reserve = (span_t *)pointer_offset(span, span_count * _memory_span_size);
     heap->spans_reserved -= (uint32_t)span_count;
     _rpmalloc_span_mark_as_subspan_unless_master(heap->span_reserve_master, span, span_count);
     if (span_count <= LARGE_CLASS_COUNT)
         _rpmalloc_stat_inc(&heap->span_use[span_count - 1].spans_from_reserved);
     return span;
 }
References _memory_span_size, _rpmalloc_span_mark_as_subspan_unless_master(), _rpmalloc_stat_inc, heap, LARGE_CLASS_COUNT, and pointer_offset.
Referenced by _rpmalloc_span_map().
_rpmalloc_span_mark_as_subspan_unless_master()
static void _rpmalloc_span_mark_as_subspan_unless_master (span_t * master, span_t * subspan, size_t span_count) static
Declare the span to be a subspan and store distance from master span and span count.
Definition at line 996 of file rpmalloc.c.
 {
     rpmalloc_assert((subspan != master) || (subspan->flags & SPAN_FLAG_MASTER), "Span master pointer and/or flag mismatch");
     if (subspan != master)
     {
         subspan->flags = SPAN_FLAG_SUBSPAN;
         subspan->offset_from_master = (uint32_t)((uintptr_t)pointer_diff(subspan, master) >> _memory_span_size_shift);
         subspan->align_offset = 0;
     }
     subspan->span_count = (uint32_t)span_count;
 }
References _memory_span_size_shift, span_t::align_offset, span_t::flags, master, span_t::offset_from_master, pointer_diff, rpmalloc_assert, span_t::span_count, SPAN_FLAG_MASTER, and SPAN_FLAG_SUBSPAN.
Referenced by _rpmalloc_global_get_reserved_spans(), _rpmalloc_span_map_aligned_count(), and _rpmalloc_span_map_from_reserve().
_rpmalloc_span_release_to_cache()
static void _rpmalloc_span_release_to_cache (heap_t * heap, span_t * span) static
Move the span (used for small or medium allocations) to the heap thread cache.
Definition at line 1172 of file rpmalloc.c.
 {
     rpmalloc_assert(heap == span->heap, "Span heap pointer corrupted");
     rpmalloc_assert(span->size_class < SIZE_CLASS_COUNT, "Invalid span size class");
     rpmalloc_assert(span->span_count == 1, "Invalid span count");
 #if ENABLE_ADAPTIVE_THREAD_CACHE || ENABLE_STATISTICS
     atomic_decr32(&heap->span_use[0].current);
 #endif
     _rpmalloc_stat_dec(&heap->size_class_use[span->size_class].spans_current);
     if (!heap->finalize)
     {
         _rpmalloc_stat_inc(&heap->span_use[0].spans_to_cache);
         _rpmalloc_stat_inc(&heap->size_class_use[span->size_class].spans_to_cache);
         if (heap->size_class[span->size_class].cache)
             _rpmalloc_heap_cache_insert(heap, heap->size_class[span->size_class].cache);
         heap->size_class[span->size_class].cache = span;
     }
     else
     {
         _rpmalloc_span_unmap(span);
     }
 }
References _rpmalloc_heap_cache_insert(), _rpmalloc_span_unmap(), _rpmalloc_stat_dec, _rpmalloc_stat_inc, atomic_decr32(), span_t::heap, heap, rpmalloc_assert, span_t::size_class, SIZE_CLASS_COUNT, and span_t::span_count.
Referenced by _rpmalloc_deallocate_direct_small_or_medium().
_rpmalloc_span_unmap()
static void _rpmalloc_span_unmap (span_t * span) static
Unmap memory pages for the given number of spans (or mark as unused if no partial unmappings)
Definition at line 1131 of file rpmalloc.c.
 {
     rpmalloc_assert((span->flags & SPAN_FLAG_MASTER) || (span->flags & SPAN_FLAG_SUBSPAN), "Span flag corrupted");
     rpmalloc_assert(!(span->flags & SPAN_FLAG_MASTER) || !(span->flags & SPAN_FLAG_SUBSPAN), "Span flag corrupted");
     int is_master = !!(span->flags & SPAN_FLAG_MASTER);
     span_t *master = is_master ? span : ((span_t *)pointer_offset(span, -(intptr_t)((uintptr_t)span->offset_from_master * _memory_span_size)));
     rpmalloc_assert(is_master || (span->flags & SPAN_FLAG_SUBSPAN), "Span flag corrupted");
     rpmalloc_assert(master->flags & SPAN_FLAG_MASTER, "Span flag corrupted");
     size_t span_count = span->span_count;
     if (!is_master)
     {
         // Directly unmap subspans (unless huge pages, in which case we defer and unmap entire page range with master)
         rpmalloc_assert(span->align_offset == 0, "Span align offset corrupted");
         if (_memory_span_size >= _memory_page_size)
             _rpmalloc_unmap(span, span_count * _memory_span_size, 0, 0);
     }
     else
     {
         // Special double flag to denote an unmapped master
         // It must be kept in memory since span header must be used
         span->flags |= SPAN_FLAG_MASTER | SPAN_FLAG_SUBSPAN | SPAN_FLAG_UNMAPPED_MASTER;
         _rpmalloc_stat_add(&_unmapped_master_spans, 1);
     }
     if (atomic_add32(&master->remaining_spans, -(int32_t)span_count) <= 0)
     {
         // Everything unmapped, unmap the master span with release flag to unmap the entire range of the super span
         rpmalloc_assert(!!(master->flags & SPAN_FLAG_MASTER) && !!(master->flags & SPAN_FLAG_SUBSPAN), "Span flag corrupted");
         size_t unmap_count = master->span_count;
         if (_memory_span_size < _memory_page_size)
             unmap_count = master->total_spans;
         _rpmalloc_stat_sub(&_master_spans, 1);
         _rpmalloc_stat_sub(&_unmapped_master_spans, 1);
         _rpmalloc_unmap(master, unmap_count * _memory_span_size, master->align_offset, (size_t)master->total_spans * _memory_span_size);
     }
 }
References _memory_page_size, _memory_span_size, _rpmalloc_stat_add, _rpmalloc_stat_sub, _rpmalloc_unmap(), span_t::align_offset, atomic_add32(), span_t::flags, master, span_t::offset_from_master, pointer_offset, rpmalloc_assert, span_t::span_count, SPAN_FLAG_MASTER, SPAN_FLAG_SUBSPAN, and SPAN_FLAG_UNMAPPED_MASTER.
Referenced by _rpmalloc_global_cache_finalize(), _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_cache_insert(), _rpmalloc_heap_finalize(), _rpmalloc_heap_global_finalize(), _rpmalloc_heap_release(), _rpmalloc_heap_unmap(), _rpmalloc_span_finalize(), _rpmalloc_span_map_aligned_count(), and _rpmalloc_span_release_to_cache().
_rpmalloc_spin()
static void _rpmalloc_spin (void) static
Definition at line 755 of file rpmalloc.c.
 {
 #if defined(_MSC_VER)
     _mm_pause();
 #elif defined(__x86_64__) || defined(__i386__)
     __asm__ volatile("pause" ::: "memory");
 #elif defined(__aarch64__) || (defined(__arm__) && __ARM_ARCH >= 7)
     __asm__ volatile("yield" ::: "memory");
 #elif defined(__powerpc__) || defined(__powerpc64__)
     // No idea if ever been compiled in such archs but ... as precaution
     __asm__ volatile("or 27,27,27");
 #elif defined(__sparc__)
     __asm__ volatile("rd %ccr, %g0 \n\trd %ccr, %g0 \n\trd %ccr, %g0");
 #else
     struct timespec ts = {0};
     nanosleep(&ts, 0);
 #endif
 }
References __asm__(), and nanosleep().
Referenced by _rpmalloc_global_cache_extract_spans(), _rpmalloc_global_cache_finalize(), _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_allocate(), _rpmalloc_heap_release(), and _rpmalloc_span_map().
_rpmalloc_unmap()
static void _rpmalloc_unmap (void * address, size_t size, size_t offset, size_t release) static
Unmap virtual memory.
Definition at line 820 of file rpmalloc.c.
 {
     rpmalloc_assert(!release || (release >= size), "Invalid unmap size");
     rpmalloc_assert(!release || (release >= _memory_page_size), "Invalid unmap size");
     if (release)
     {
         rpmalloc_assert(!(release % _memory_page_size), "Invalid unmap size");
         _rpmalloc_stat_sub(&_mapped_pages, (release >> _memory_page_size_shift));
         _rpmalloc_stat_add(&_unmapped_total, (release >> _memory_page_size_shift));
     }
     _memory_config.memory_unmap(address, size, offset, release);
 }
References _memory_config, _memory_page_size, _memory_page_size_shift, _rpmalloc_stat_add, _rpmalloc_stat_sub, rpmalloc_config_t::memory_unmap, offset, release(), rpmalloc_assert, and size.
Referenced by _rpmalloc_aligned_allocate(), _rpmalloc_deallocate_huge(), and _rpmalloc_span_unmap().
_rpmalloc_unmap_os()
static void _rpmalloc_unmap_os (void * address, size_t size, size_t offset, size_t release) static
Default implementation to unmap pages from virtual memory.
Definition at line 874 of file rpmalloc.c.
 {
     rpmalloc_assert(release || (offset == 0), "Invalid unmap size");
     rpmalloc_assert(!release || (release >= _memory_page_size), "Invalid unmap size");
     rpmalloc_assert(size >= _memory_page_size, "Invalid unmap size");
     if (release && offset)
     {
         offset <<= 3;
         address = pointer_offset(address, -(int32_t)offset);
         if ((release >= _memory_span_size) && (_memory_span_size > _memory_map_granularity))
         {
             // Padding is always one span size
             release += _memory_span_size;
         }
     }
 #if !DISABLE_UNMAP
     if (release)
     {
         if (__rpmalloc_munmap(address, release))
         {
             rpmalloc_assert(0, "Failed to unmap virtual memory block");
         }
     }
     else
     {
         if (__rpmalloc_posix_madvise(address, size, POSIX_MADV_DONTNEED))
         {
             rpmalloc_assert(0, "Failed to madvise virtual memory block as free");
         }
     }
 #endif
     if (release)
         _rpmalloc_stat_sub(&_mapped_pages_os, release >> _memory_page_size_shift);
 }
References __rpmalloc_munmap(), __rpmalloc_posix_madvise(), _memory_map_granularity, _memory_page_size, _memory_page_size_shift, _memory_span_size, _rpmalloc_stat_sub, offset, pointer_offset, POSIX_MADV_DONTNEED, release(), rpmalloc_assert, and size.
Referenced by rpmalloc_initialize_config().
_rpmalloc_usable_size()
static size_t _rpmalloc_usable_size (void * p) static
Get the usable size of the given block.
Reallocation entry points
Initialization, finalization and utility
Definition at line 2765 of file rpmalloc.c.
 {
     // Grab the span using guaranteed span alignment
     span_t *span = (span_t *)((uintptr_t)p & _memory_span_mask);
     if (span->size_class < SIZE_CLASS_COUNT)
     {
         // Small/medium block
         void *blocks_start = pointer_offset(span, SPAN_HEADER_SIZE);
         return span->block_size - ((size_t)pointer_diff(p, blocks_start) % span->block_size);
     }
     if (span->size_class == SIZE_CLASS_LARGE)
     {
         // Large block
         size_t current_spans = span->span_count;
         return (current_spans * _memory_span_size) - (size_t)pointer_diff(p, span);
     }
     // Oversized block, page count is stored in span_count
     size_t current_pages = span->span_count;
     return (current_pages * _memory_page_size) - (size_t)pointer_diff(p, span);
 }
References _memory_page_size, _memory_span_mask, _memory_span_size, span_t::block_size, p, pointer_diff, pointer_offset, span_t::size_class, SIZE_CLASS_COUNT, SIZE_CLASS_LARGE, span_t::span_count, and SPAN_HEADER_SIZE.
Referenced by _rpmalloc_aligned_reallocate(), and rpmalloc_usable_size().
_Static_assert() [1/4]
_Static_assert ((SMALL_GRANULARITY &(SMALL_GRANULARITY - 1)) = =0, "Small granularity must be power of two")
_Static_assert() [2/4]
_Static_assert ((SPAN_HEADER_SIZE &(SPAN_HEADER_SIZE - 1)) = =0, "Span header size must be power of two")
_Static_assert() [3/4]
_Static_assert (sizeof(size_class_t) = =8, "Size class size mismatch")
_Static_assert() [4/4]
_Static_assert (sizeof(span_t)<= SPAN_HEADER_SIZE, "span size mismatch")
atomic_add32()
static FORCEINLINE int32_t atomic_add32 (atomic32_t * val, int32_t add) static
Definition at line 182 of file rpmalloc.c.
 { return atomic_fetch_add_explicit(val, add, memory_order_relaxed) + add; }
References add(), atomic_fetch_add_explicit, memory_order_relaxed, and val.
Referenced by _rpmalloc_span_unmap(), and rpmalloc_finalize().
atomic_add64()
static FORCEINLINE int64_t atomic_add64 (atomic64_t * val, int64_t add) static
Definition at line 186 of file rpmalloc.c.
 { return atomic_fetch_add_explicit(val, add, memory_order_relaxed) + add; }
References add(), atomic_fetch_add_explicit, memory_order_relaxed, and val.
atomic_cas32_acquire()
static FORCEINLINE int atomic_cas32_acquire (atomic32_t * dst, int32_t val, int32_t ref) static
Definition at line 183 of file rpmalloc.c.
 { return atomic_compare_exchange_weak_explicit(dst, &ref, val, memory_order_acquire, memory_order_relaxed); }
References atomic_compare_exchange_weak_explicit, dst, memory_order_acquire, memory_order_relaxed, and val.
Referenced by _rpmalloc_global_cache_extract_spans(), _rpmalloc_global_cache_finalize(), _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_allocate(), _rpmalloc_heap_release(), and _rpmalloc_span_map().
atomic_cas_ptr()
static FORCEINLINE int atomic_cas_ptr (atomicptr_t * dst, void * val, void * ref) static
Definition at line 191 of file rpmalloc.c.
 { return atomic_compare_exchange_weak_explicit(dst, &ref, val, memory_order_relaxed, memory_order_relaxed); }
References atomic_compare_exchange_weak_explicit, dst, memory_order_relaxed, and val.
Referenced by _rpmalloc_deallocate_defer_free_span().
atomic_decr32()
static FORCEINLINE int32_t atomic_decr32 (atomic32_t * val) static
Definition at line 181 of file rpmalloc.c.
 { return atomic_fetch_add_explicit(val, -1, memory_order_relaxed) - 1; }
References atomic_fetch_add_explicit, memory_order_relaxed, and val.
Referenced by _rpmalloc_deallocate_large(), _rpmalloc_heap_release(), _rpmalloc_heap_unmap(), and _rpmalloc_span_release_to_cache().
atomic_exchange_ptr_acquire()
static FORCEINLINE void* atomic_exchange_ptr_acquire (atomicptr_t * dst, void * val) static
Definition at line 190 of file rpmalloc.c.
 { return atomic_exchange_explicit(dst, val, memory_order_acquire); }
References atomic_exchange_explicit, dst, memory_order_acquire, and val.
Referenced by _rpmalloc_deallocate_defer_small_or_medium(), _rpmalloc_deallocate_direct_small_or_medium(), _rpmalloc_heap_cache_adopt_deferred(), and _rpmalloc_span_extract_free_list_deferred().
atomic_incr32()
static FORCEINLINE int32_t atomic_incr32 (atomic32_t * val) static
Definition at line 180 of file rpmalloc.c.
 { return atomic_fetch_add_explicit(val, 1, memory_order_relaxed) + 1; }
References atomic_fetch_add_explicit, memory_order_relaxed, and val.
Referenced by _rpmalloc_heap_initialize(), and _rpmalloc_inc_span_statistics().
atomic_load64()
static FORCEINLINE int64_t atomic_load64 (atomic64_t * val) static
Definition at line 185 of file rpmalloc.c.
 { return atomic_load_explicit(val, memory_order_relaxed); }
References atomic_load_explicit, memory_order_relaxed, and val.
Referenced by rpmalloc_dump_statistics(), and rpmalloc_thread_statistics().
atomic_load_ptr()
static FORCEINLINE void* atomic_load_ptr (atomicptr_t * src) static
Definition at line 187 of file rpmalloc.c.
 { return atomic_load_explicit(src, memory_order_relaxed); }
References atomic_load_explicit, memory_order_relaxed, and src.
Referenced by _rpmalloc_allocate_from_heap_fallback(), _rpmalloc_deallocate_defer_free_span(), _rpmalloc_heap_finalize(), and rpmalloc_thread_statistics().
atomic_store32()
static FORCEINLINE void atomic_store32 (atomic32_t * dst, int32_t val) static
Definition at line 179 of file rpmalloc.c.
 { atomic_store_explicit(dst, val, memory_order_relaxed); }
References atomic_store_explicit, dst, memory_order_relaxed, and val.
Referenced by _rpmalloc_heap_allocate_new(), _rpmalloc_inc_span_statistics(), _rpmalloc_span_initialize(), and rpmalloc_initialize_config().
atomic_store32_release()
static FORCEINLINE void atomic_store32_release (atomic32_t * dst, int32_t val) static
Definition at line 184 of file rpmalloc.c.
 { atomic_store_explicit(dst, val, memory_order_release); }
References atomic_store_explicit, dst, memory_order_release, and val.
Referenced by _rpmalloc_global_cache_extract_spans(), _rpmalloc_global_cache_finalize(), _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_allocate(), _rpmalloc_heap_release(), _rpmalloc_span_map(), rpmalloc_finalize(), and rpmalloc_initialize_config().
atomic_store_ptr()
static FORCEINLINE void atomic_store_ptr (atomicptr_t * dst, void * val) static
Definition at line 188 of file rpmalloc.c.
 { atomic_store_explicit(dst, val, memory_order_relaxed); }
References atomic_store_explicit, dst, memory_order_relaxed, and val.
atomic_store_ptr_release()
static FORCEINLINE void atomic_store_ptr_release (atomicptr_t * dst, void * val) static
Definition at line 189 of file rpmalloc.c.
 { atomic_store_explicit(dst, val, memory_order_release); }
References atomic_store_explicit, dst, memory_order_release, and val.
Referenced by _rpmalloc_deallocate_defer_small_or_medium(), _rpmalloc_deallocate_direct_small_or_medium(), _rpmalloc_span_extract_free_list_deferred(), and _rpmalloc_span_initialize_new().
free_list_partial_init()
static uint32_t free_list_partial_init (void ** list, void ** first_block, void * page_start, void * block_start, uint32_t block_count, uint32_t block_size) static
Initialize a (partial) free list up to next system memory page, while reserving the first block as allocated, returning number of blocks in list
Definition at line 1198 of file rpmalloc.c.
 {
     rpmalloc_assert(block_count, "Internal failure");
     *first_block = block_start;
     if (block_count > 1)
     {
         void *free_block = pointer_offset(block_start, block_size);
         void *block_end = pointer_offset(block_start, (size_t)block_size * block_count);
         // If block size is less than half a memory page, bound init to next memory page boundary
         if (block_size < (_memory_page_size >> 1))
         {
             void *page_end = pointer_offset(page_start, _memory_page_size);
             if (page_end < block_end)
                 block_end = page_end;
         }
         *list = free_block;
         block_count = 2;
         void *next_block = pointer_offset(free_block, block_size);
         while (next_block < block_end)
         {
             *((void **)free_block) = next_block;
             free_block = next_block;
             ++block_count;
             next_block = pointer_offset(next_block, block_size);
         }
         *((void **)free_block) = 0;
     }
     else
     {
         *list = 0;
     }
     return block_count;
 }
References _memory_page_size, list(), pointer_offset, and rpmalloc_assert.
Referenced by _rpmalloc_allocate_from_heap_fallback(), and _rpmalloc_span_initialize_new().
free_list_pop()
static void* free_list_pop (void ** list) static
Pop first block from a free list.
Allocation entry points
Definition at line 2134 of file rpmalloc.c.
 {
     void *block = *list;
     *list = *((void **)block);
     return block;
 }
References list().
Referenced by _rpmalloc_allocate_from_heap_fallback(), _rpmalloc_allocate_medium(), and _rpmalloc_allocate_small().
get_thread_heap()
static heap_t* get_thread_heap (void) inline static
Get the current thread heap.
Definition at line 717 of file rpmalloc.c.
 {
     heap_t *heap = get_thread_heap_raw();
 #if ENABLE_PRELOAD
     if (EXPECTED(heap != 0))
         return heap;
     rpmalloc_initialize();
     return get_thread_heap_raw();
 #else
     return heap;
 #endif
 }
References EXPECTED, get_thread_heap_raw(), heap, and rpmalloc_initialize().
Referenced by rpaligned_alloc(), rpaligned_realloc(), rpcalloc(), rpmalloc(), and rprealloc().
get_thread_heap_raw()
static heap_t* get_thread_heap_raw (void) inline static
Definition at line 710 of file rpmalloc.c.
 {
     return _memory_thread_heap;
 }
References _memory_thread_heap.
Referenced by _rpmalloc_heap_release(), get_thread_heap(), rpmalloc_is_thread_initialized(), rpmalloc_thread_finalize(), rpmalloc_thread_initialize(), and rpmalloc_thread_statistics().
get_thread_id()
static uintptr_t get_thread_id (void) inline static
Fast thread ID.
Definition at line 734 of file rpmalloc.c.
 { return __get_tid(); }
References __get_tid().
Referenced by _rpmalloc_deallocate_direct_small_or_medium(), _rpmalloc_deallocate_huge(), _rpmalloc_deallocate_large(), _rpmalloc_deallocate_small_or_medium(), _rpmalloc_heap_release(), rpmalloc_set_main_thread(), and set_thread_heap().
rpaligned_alloc()
RPMALLOC_ALLOCATOR void* rpaligned_alloc (size_t alignment, size_t size)
Allocate a memory block of at least the given size and alignment.
Definition at line 3140 of file rpmalloc.c.
 {
     heap_t *heap = get_thread_heap();
     return _rpmalloc_aligned_allocate(heap, alignment, size);
 }
References _rpmalloc_aligned_allocate(), get_thread_heap(), heap, and size.
Referenced by rpaligned_calloc(), rpmemalign(), and rpposix_memalign().
rpaligned_calloc()
RPMALLOC_ALLOCATOR void* rpaligned_calloc (size_t alignment, size_t num, size_t size) inline
Definition at line 3147 of file rpmalloc.c.
 {
     size_t total;
 #if ENABLE_VALIDATE_ARGS
     int err = __builtin_umull_overflow(num, size, &total);
     assert(!err && (total < MAX_ALLOC_SIZE));
 #else
     total = num * size;
 #endif
     void *block = rpaligned_alloc(alignment, total);
     if (block)
         memset_unsafe(block, 0, total);
     return block;
 }
References assert, err(), MAX_ALLOC_SIZE, memset_unsafe(), rpaligned_alloc(), size, and total.
rpaligned_realloc()
RPMALLOC_ALLOCATOR void* rpaligned_realloc (void * ptr, size_t alignment, size_t size, size_t oldsize, unsigned int flags)
Reallocate the given block to at least the given size and alignment,.
Definition at line 3129 of file rpmalloc.c.
 {
 #if ENABLE_VALIDATE_ARGS
     assert((size + alignment) >= size && (alignment <= _memory_page_size));
 #endif
     heap_t *heap = get_thread_heap();
     return _rpmalloc_aligned_reallocate(heap, ptr, alignment, size, oldsize, flags);
 }
References _memory_page_size, _rpmalloc_aligned_reallocate(), assert, flags, get_thread_heap(), heap, and size.
rpcalloc()
RPMALLOC_ALLOCATOR void* rpcalloc (size_t num, size_t size) inline
Definition at line 3102 of file rpmalloc.c.
 {
     size_t total;
 #if ENABLE_VALIDATE_ARGS
     int err = __builtin_umull_overflow(num, size, &total);
     assert(!err && (total < MAX_ALLOC_SIZE));
 #else
     total = num * size;
 #endif
     heap_t *heap = get_thread_heap();
     void *block = _rpmalloc_allocate(heap, total);
     if (block)
         memset_unsafe(block, 0, total);
     return block;
 }
References _rpmalloc_allocate(), assert, err(), get_thread_heap(), heap, MAX_ALLOC_SIZE, memset_unsafe(), size, and total.
Referenced by calloc().
rpfree()
void rpfree (void * ptr) inline
Free the given memory block.
Definition at line 3096 of file rpmalloc.c.
 {
     _rpmalloc_deallocate(ptr);
 }
References _rpmalloc_deallocate().
Referenced by free().
rpmalloc()
RPMALLOC_ALLOCATOR void* rpmalloc (size_t size) inline
Allocate a memory block of at least the given size.
Definition at line 3086 of file rpmalloc.c.
 {
 #if ENABLE_VALIDATE_ARGS
     assert(size < MAX_ALLOC_SIZE);
 #endif
     heap_t *heap = get_thread_heap();
     return _rpmalloc_allocate(heap, size);
 }
References _rpmalloc_allocate(), assert, get_thread_heap(), heap, MAX_ALLOC_SIZE, and size.
Referenced by malloc().
rpmalloc_config()
const rpmalloc_config_t* rpmalloc_config (void)
Get allocator configuration.
Definition at line 3078 of file rpmalloc.c.
 {
     return &_memory_config;
 }
References _memory_config.
rpmalloc_dump_statistics()
void rpmalloc_dump_statistics (void * file)
Dump all statistics in human readable format to file (should be a FILE*)
Definition at line 3335 of file rpmalloc.c.
 {
 #if ENABLE_STATISTICS
     for (size_t list_idx = 0; list_idx < HEAP_ARRAY_SIZE; ++list_idx)
     {
         heap_t *heap = _memory_heaps[list_idx];
         while (heap)
         {
             int need_dump = 0;
             for (size_t iclass = 0; !need_dump && (iclass < SIZE_CLASS_COUNT); ++iclass)
             {
                 if (!atomic_load32(&heap->size_class_use[iclass].alloc_total))
                 {
                     rpmalloc_assert(!atomic_load32(&heap->size_class_use[iclass].free_total), "Heap statistics counter mismatch");
                     rpmalloc_assert(!atomic_load32(&heap->size_class_use[iclass].spans_map_calls), "Heap statistics counter mismatch");
                     continue;
                 }
                 need_dump = 1;
             }
             for (size_t iclass = 0; !need_dump && (iclass < LARGE_CLASS_COUNT); ++iclass)
             {
                 if (!atomic_load32(&heap->span_use[iclass].high) && !atomic_load32(&heap->span_use[iclass].spans_map_calls))
                     continue;
                 need_dump = 1;
             }
             if (need_dump)
                 _memory_heap_dump_statistics(heap, file);
             heap = heap->next_heap;
         }
     }
     fprintf(file, "Global stats:\n");
     size_t huge_current = (size_t)atomic_load32(&_huge_pages_current) * _memory_page_size;
     size_t huge_peak = (size_t)_huge_pages_peak * _memory_page_size;
     fprintf(file, "HugeCurrentMiB HugePeakMiB\n");
     fprintf(file, "%14zu %11zu\n", huge_current / (size_t)(1024 * 1024), huge_peak / (size_t)(1024 * 1024));
     fprintf(file, "GlobalCacheMiB\n");
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
     {
         global_cache_t *cache = _memory_span_cache + iclass;
         size_t global_cache = (size_t)cache->count * iclass * _memory_span_size;
         size_t global_overflow_cache = 0;
         span_t *span = cache->overflow;
         while (span)
         {
             global_overflow_cache += iclass * _memory_span_size;
             span = span->next;
         }
         if (global_cache || global_overflow_cache || cache->insert_count || cache->extract_count)
             fprintf(file, "%4zu: %8zuMiB (%8zuMiB overflow) %14zu insert %14zu extract\n", iclass + 1, global_cache / (size_t)(1024 * 1024), global_overflow_cache / (size_t)(1024 * 1024), cache->insert_count, cache->extract_count);
     }
     size_t mapped = (size_t)atomic_load32(&_mapped_pages) * _memory_page_size;
     size_t mapped_os = (size_t)atomic_load32(&_mapped_pages_os) * _memory_page_size;
     size_t mapped_peak = (size_t)_mapped_pages_peak * _memory_page_size;
     size_t mapped_total = (size_t)atomic_load32(&_mapped_total) * _memory_page_size;
     size_t unmapped_total = (size_t)atomic_load32(&_unmapped_total) * _memory_page_size;
     fprintf(file, "MappedMiB MappedOSMiB MappedPeakMiB MappedTotalMiB UnmappedTotalMiB\n");
     fprintf(file, "%9zu %11zu %13zu %14zu %16zu\n",
             mapped / (size_t)(1024 * 1024),
             mapped_os / (size_t)(1024 * 1024),
             mapped_peak / (size_t)(1024 * 1024),
             mapped_total / (size_t)(1024 * 1024),
             unmapped_total / (size_t)(1024 * 1024));
     fprintf(file, "\n");
 #if 0
     int64_t allocated = atomic_load64(&_allocation_counter);
     int64_t deallocated = atomic_load64(&_deallocation_counter);
     fprintf(file, "Allocation count: %lli\n", allocated);
     fprintf(file, "Deallocation count: %lli\n", deallocated);
     fprintf(file, "Current allocations: %lli\n", (allocated - deallocated));
     fprintf(file, "Master spans: %d\n", atomic_load32(&_master_spans));
     fprintf(file, "Dangling master spans: %d\n", atomic_load32(&_unmapped_master_spans));
 #endif
 #endif
     (void)sizeof(file);
 }
References _memory_heaps, _memory_page_size, _memory_span_cache, _memory_span_size, atomic_load64(), global_cache_t::count, fprintf(), heap, HEAP_ARRAY_SIZE, LARGE_CLASS_COUNT, span_t::next, global_cache_t::overflow, rpmalloc_assert, SIZE_CLASS_COUNT, and while().
rpmalloc_finalize()
void rpmalloc_finalize (void)
Finalize the allocator.
Finalize allocator.
Definition at line 2993 of file rpmalloc.c.
 {
     rpmalloc_thread_finalize(1);
     // rpmalloc_dump_statistics(stdout);
     if (_memory_global_reserve)
     {
         atomic_add32(&_memory_global_reserve_master->remaining_spans, -(int32_t)_memory_global_reserve_count);
         _memory_global_reserve_master = 0;
         _memory_global_reserve_count = 0;
         _memory_global_reserve = 0;
     }
     atomic_store32_release(&_memory_global_lock, 0);
     // Free all thread caches and fully free spans
     for (size_t list_idx = 0; list_idx < HEAP_ARRAY_SIZE; ++list_idx)
     {
         heap_t *heap = _memory_heaps[list_idx];
         while (heap)
         {
             heap_t *next_heap = heap->next_heap;
             heap->finalize = 1;
             _rpmalloc_heap_global_finalize(heap);
             heap = next_heap;
         }
     }
 #if ENABLE_GLOBAL_CACHE
     // Free global caches
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
         _rpmalloc_global_cache_finalize(&_memory_span_cache[iclass]);
 #endif
 #if (defined(__APPLE__) || defined(__HAIKU__)) && ENABLE_PRELOAD
     pthread_key_delete(_memory_thread_heap);
 #endif
 #if defined(_WIN32) && (!defined(BUILD_DYNAMIC_LINK) || !BUILD_DYNAMIC_LINK)
     FlsFree(fls_key);
     fls_key = 0;
 #endif
 #if ENABLE_STATISTICS
     // If you hit these asserts you probably have memory leaks (perhaps global scope data doing dynamic allocations) or double frees in your code
     rpmalloc_assert(atomic_load32(&_mapped_pages) == 0, "Memory leak detected");
     rpmalloc_assert(atomic_load32(&_mapped_pages_os) == 0, "Memory leak detected");
 #endif
     _rpmalloc_initialized = 0;
 }
References _memory_global_lock, _memory_global_reserve, _memory_global_reserve_count, _memory_global_reserve_master, _memory_heaps, _memory_span_cache, _memory_thread_heap, _rpmalloc_global_cache_finalize(), _rpmalloc_heap_global_finalize(), _rpmalloc_initialized, atomic_add32(), atomic_store32_release(), heap, HEAP_ARRAY_SIZE, LARGE_CLASS_COUNT, pthread_key_delete(), span_t::remaining_spans, rpmalloc_assert, and rpmalloc_thread_finalize().
rpmalloc_global_statistics()
void rpmalloc_global_statistics (rpmalloc_global_statistics_t * stats)
Get global statistics.
Definition at line 3262 of file rpmalloc.c.
 {
     memset_unsafe(stats, 0, sizeof(rpmalloc_global_statistics_t));
 #if ENABLE_STATISTICS
     stats->mapped = (size_t)atomic_load32(&_mapped_pages) * _memory_page_size;
     stats->mapped_peak = (size_t)_mapped_pages_peak * _memory_page_size;
     stats->mapped_total = (size_t)atomic_load32(&_mapped_total) * _memory_page_size;
     stats->unmapped_total = (size_t)atomic_load32(&_unmapped_total) * _memory_page_size;
     stats->huge_alloc = (size_t)atomic_load32(&_huge_pages_current) * _memory_page_size;
     stats->huge_alloc_peak = (size_t)_huge_pages_peak * _memory_page_size;
 #endif
 #if ENABLE_GLOBAL_CACHE
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
         stats->cached += _memory_span_cache[iclass].count * (iclass + 1) * _memory_span_size;
 #endif
 }
References _memory_page_size, _memory_span_cache, _memory_span_size, rpmalloc_global_statistics_t::cached, global_cache_t::count, rpmalloc_global_statistics_t::huge_alloc, rpmalloc_global_statistics_t::huge_alloc_peak, LARGE_CLASS_COUNT, rpmalloc_global_statistics_t::mapped, rpmalloc_global_statistics_t::mapped_peak, rpmalloc_global_statistics_t::mapped_total, memset_unsafe(), and rpmalloc_global_statistics_t::unmapped_total.
rpmalloc_initialize()
int rpmalloc_initialize (void) inline
Initialize the allocator and setup global data.
Initialize allocator with default configuration.
Definition at line 2814 of file rpmalloc.c.
 {
     if (_rpmalloc_initialized)
     {
         rpmalloc_thread_initialize();
         return 0;
     }
     return rpmalloc_initialize_config(0);
 }
References _rpmalloc_initialized, rpmalloc_initialize_config(), and rpmalloc_thread_initialize().
Referenced by get_thread_heap(), and InitializeMemoryManagement().
rpmalloc_initialize_config()
int rpmalloc_initialize_config (const rpmalloc_config_t * config)
Initialize allocator with given configuration.
Definition at line 2824 of file rpmalloc.c.
 {
     if (_rpmalloc_initialized)
     {
         rpmalloc_thread_initialize();
         return 0;
     }
     _rpmalloc_initialized = 1;
     if (config)
         memcpy_unsafe(&_memory_config, config, sizeof(rpmalloc_config_t));
     else
         memset_unsafe(&_memory_config, 0, sizeof(rpmalloc_config_t));
     if (!_memory_config.memory_map || !_memory_config.memory_unmap)
     {
         _memory_config.memory_map = _rpmalloc_mmap_os;
         _memory_config.memory_unmap = _rpmalloc_unmap_os;
     }
     _memory_map_granularity = (size_t)__rpmalloc_sysconf(_SC_PAGESIZE);
 #if RPMALLOC_CONFIGURABLE
     _memory_page_size = _memory_config.page_size;
 #else
     _memory_page_size = 0;
 #endif
     _memory_huge_pages = 0;
     if (!_memory_page_size)
     {
         _memory_page_size = _memory_map_granularity;
         if (_memory_config.enable_huge_pages)
         {
 #if defined(__linux__)
             size_t huge_page_size = 0;
             FILE *meminfo = fopen("/proc/meminfo", "r");
             if (meminfo)
             {
                 char line[128];
                 while (!huge_page_size && fgets(line, sizeof(line) - 1, meminfo))
                 {
                     line[sizeof(line) - 1] = 0;
                     if (strstr(line, "Hugepagesize:"))
                         huge_page_size = (size_t)strtol(line + 13, 0, 10) * 1024;
                 }
                 fclose(meminfo);
             }
             if (huge_page_size)
             {
                 _memory_huge_pages = 1;
                 _memory_page_size = huge_page_size;
                 _memory_map_granularity = huge_page_size;
             }
 #endif
         }
     }
     else
     {
         if (_memory_config.enable_huge_pages)
             _memory_huge_pages = 1;
     }
     size_t min_span_size = 256;
     size_t max_page_size;
 #if UINTPTR_MAX > 0xFFFFFFFF
     max_page_size = 4096ULL * 1024ULL * 1024ULL;
 #else
     max_page_size = 4 * 1024 * 1024;
 #endif
     if (_memory_page_size < min_span_size)
         _memory_page_size = min_span_size;
     if (_memory_page_size > max_page_size)
         _memory_page_size = max_page_size;
     _memory_page_size_shift = 0;
     size_t page_size_bit = _memory_page_size;
     while (page_size_bit != 1)
     {
         ++_memory_page_size_shift;
         page_size_bit >>= 1;
     }
     _memory_page_size = ((size_t)1 << _memory_page_size_shift);
 #if RPMALLOC_CONFIGURABLE
     if (!_memory_config.span_size)
     {
         _memory_span_size = _memory_default_span_size;
         _memory_span_size_shift = _memory_default_span_size_shift;
         _memory_span_mask = _memory_default_span_mask;
     }
     else
     {
         size_t span_size = _memory_config.span_size;
         if (span_size > (256 * 1024))
             span_size = (256 * 1024);
         _memory_span_size = 4096;
         _memory_span_size_shift = 12;
         while (_memory_span_size < span_size)
         {
             _memory_span_size <<= 1;
             ++_memory_span_size_shift;
         }
         _memory_span_mask = ~(uintptr_t)(_memory_span_size - 1);
     }
 #endif
     _memory_span_map_count = (_memory_config.span_map_count ? _memory_config.span_map_count : DEFAULT_SPAN_MAP_COUNT);
     if ((_memory_span_size * _memory_span_map_count) < _memory_page_size)
         _memory_span_map_count = (_memory_page_size / _memory_span_size);
     if ((_memory_page_size >= _memory_span_size) && ((_memory_span_map_count * _memory_span_size) % _memory_page_size))
         _memory_span_map_count = (_memory_page_size / _memory_span_size);
     _memory_heap_reserve_count = (_memory_span_map_count > DEFAULT_SPAN_MAP_COUNT) ? DEFAULT_SPAN_MAP_COUNT : _memory_span_map_count;
     _memory_config.page_size = _memory_page_size;
     _memory_config.span_size = _memory_span_size;
     _memory_config.span_map_count = _memory_span_map_count;
     _memory_config.enable_huge_pages = _memory_huge_pages;
 #if ((defined(__APPLE__) || defined(__HAIKU__)) && ENABLE_PRELOAD) || defined(__TINYC__)
     if (pthread_key_create(&_memory_thread_heap, _rpmalloc_heap_release_raw_fc))
         return -1;
 #endif
     // Setup all small and medium size classes
     size_t iclass = 0;
     _memory_size_class[iclass].block_size = SMALL_GRANULARITY;
     _rpmalloc_adjust_size_class(iclass);
     for (iclass = 1; iclass < SMALL_CLASS_COUNT; ++iclass)
     {
         size_t size = iclass * SMALL_GRANULARITY;
         _memory_size_class[iclass].block_size = (uint32_t)size;
         _rpmalloc_adjust_size_class(iclass);
     }
     // At least two blocks per span, then fall back to large allocations
     _memory_medium_size_limit = (_memory_span_size - SPAN_HEADER_SIZE) >> 1;
     if (_memory_medium_size_limit > MEDIUM_SIZE_LIMIT)
         _memory_medium_size_limit = MEDIUM_SIZE_LIMIT;
     for (iclass = 0; iclass < MEDIUM_CLASS_COUNT; ++iclass)
     {
         size_t size = SMALL_SIZE_LIMIT + ((iclass + 1) * MEDIUM_GRANULARITY);
         if (size > _memory_medium_size_limit)
             break;
         _memory_size_class[SMALL_CLASS_COUNT + iclass].block_size = (uint32_t)size;
         _rpmalloc_adjust_size_class(SMALL_CLASS_COUNT + iclass);
     }
     _memory_orphan_heaps = 0;
 #if RPMALLOC_FIRST_CLASS_HEAPS
     _memory_first_class_orphan_heaps = 0;
 #endif
 #if ENABLE_STATISTICS
     atomic_store32(&_memory_active_heaps, 0);
     atomic_store32(&_mapped_pages, 0);
     _mapped_pages_peak = 0;
     atomic_store32(&_master_spans, 0);
     atomic_store32(&_mapped_total, 0);
     atomic_store32(&_unmapped_total, 0);
     atomic_store32(&_mapped_pages_os, 0);
     atomic_store32(&_huge_pages_current, 0);
     _huge_pages_peak = 0;
 #endif
     memset_unsafe(_memory_heaps, 0, sizeof(_memory_heaps));
     atomic_store32_release(&_memory_global_lock, 0);
     // Initialize this thread
     rpmalloc_thread_initialize();
     return 0;
 }
References __rpmalloc_sysconf(), _memory_config, _memory_default_span_mask, _memory_default_span_size, _memory_default_span_size_shift, _memory_global_lock, _memory_heap_reserve_count, _memory_heaps, _memory_huge_pages, _memory_map_granularity, _memory_medium_size_limit, _memory_orphan_heaps, _memory_page_size, _memory_page_size_shift, _memory_size_class, _memory_span_map_count, _memory_span_mask, _memory_span_size, _memory_span_size_shift, _memory_thread_heap, _rpmalloc_adjust_size_class(), _rpmalloc_heap_release_raw_fc(), _rpmalloc_initialized, _rpmalloc_mmap_os(), _rpmalloc_unmap_os(), _SC_PAGESIZE, atomic_store32(), atomic_store32_release(), size_class_t::block_size, DEFAULT_SPAN_MAP_COUNT, rpmalloc_config_t::enable_huge_pages, fclose(), fgets, fopen(), line, MEDIUM_CLASS_COUNT, MEDIUM_GRANULARITY, MEDIUM_SIZE_LIMIT, memcpy_unsafe(), rpmalloc_config_t::memory_map, rpmalloc_config_t::memory_unmap, memset_unsafe(), rpmalloc_config_t::page_size, pthread_key_create(), rpmalloc_thread_initialize(), size, SMALL_CLASS_COUNT, SMALL_GRANULARITY, SMALL_SIZE_LIMIT, SPAN_HEADER_SIZE, rpmalloc_config_t::span_map_count, rpmalloc_config_t::span_size, strstr(), and strtol().
Referenced by InitializeMemoryManagement(), and rpmalloc_initialize().
rpmalloc_is_thread_initialized()
int rpmalloc_is_thread_initialized (void)
Query if allocator is initialized for calling thread.
Definition at line 3072 of file rpmalloc.c.
 {
     return (get_thread_heap_raw() != 0) ? 1 : 0;
 }
References get_thread_heap_raw().
rpmalloc_set_main_thread()
void rpmalloc_set_main_thread (void)
Set main thread ID.
Definition at line 749 of file rpmalloc.c.
 {
     _rpmalloc_main_thread_id = get_thread_id();
 }
References _rpmalloc_main_thread_id, and get_thread_id().
rpmalloc_thread_collect()
void rpmalloc_thread_collect (void) inline
Perform deferred deallocations pending for the calling thread heap.
Definition at line 3185 of file rpmalloc.c.
 {
 }
rpmalloc_thread_finalize()
void rpmalloc_thread_finalize (int release_caches)
Finalize thread, orphan heap.
Finalize allocator for calling thread.
Definition at line 3061 of file rpmalloc.c.
 {
     heap_t *heap = get_thread_heap_raw();
     if (heap)
         _rpmalloc_heap_release_raw(heap, release_caches);
     set_thread_heap(0);
 #if defined(_WIN32) && (!defined(BUILD_DYNAMIC_LINK) || !BUILD_DYNAMIC_LINK)
     FlsSetValue(fls_key, 0);
 #endif
 }
References _rpmalloc_heap_release_raw(), get_thread_heap_raw(), heap, and set_thread_heap().
Referenced by rpmalloc_finalize().
rpmalloc_thread_initialize()
void rpmalloc_thread_initialize (void) inline
Initialize thread, assign heap.
Initialize allocator for calling thread.
Definition at line 3044 of file rpmalloc.c.
 {
     if (!get_thread_heap_raw())
     {
         heap_t *heap = _rpmalloc_heap_allocate(0);
         if (heap)
         {
             _rpmalloc_stat_inc(&_memory_active_heaps);
             set_thread_heap(heap);
 #if defined(_WIN32) && (!defined(BUILD_DYNAMIC_LINK) || !BUILD_DYNAMIC_LINK)
             FlsSetValue(fls_key, heap);
 #endif
         }
     }
 }
References _rpmalloc_heap_allocate(), _rpmalloc_stat_inc, get_thread_heap_raw(), heap, and set_thread_heap().
Referenced by rpmalloc_initialize(), and rpmalloc_initialize_config().
rpmalloc_thread_statistics()
void rpmalloc_thread_statistics (rpmalloc_thread_statistics_t * stats)
Get per-thread statistics.
Definition at line 3189 of file rpmalloc.c.
 {
     memset_unsafe(stats, 0, sizeof(rpmalloc_thread_statistics_t));
     heap_t *heap = get_thread_heap_raw();
     if (!heap)
         return;
     for (size_t iclass = 0; iclass < SIZE_CLASS_COUNT; ++iclass)
     {
         size_class_t *size_class = _memory_size_class + iclass;
         span_t *span = heap->size_class[iclass].partial_span;
         while (span)
         {
             size_t free_count = span->list_size;
             size_t block_count = size_class->block_count;
             if (span->free_list_limit < block_count)
                 block_count = span->free_list_limit;
             free_count += (block_count - span->used_count);
             stats->sizecache = free_count * size_class->block_size;
             span = span->next;
         }
     }
 #if ENABLE_THREAD_CACHE
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
     {
         span_cache_t *span_cache;
         if (!iclass)
             span_cache = &heap->span_cache;
         else
             span_cache = (span_cache_t *)(heap->span_large_cache + (iclass - 1));
         stats->spancache = span_cache->count * (iclass + 1) * _memory_span_size;
     }
 #endif
     span_t *deferred = (span_t *)atomic_load_ptr(&heap->span_free_deferred);
     while (deferred)
     {
         if (deferred->size_class != SIZE_CLASS_HUGE)
             stats->spancache = (size_t)deferred->span_count * _memory_span_size;
         deferred = (span_t *)deferred->free_list;
     }
 #if ENABLE_STATISTICS
     stats->thread_to_global = (size_t)atomic_load64(&heap->thread_to_global);
     stats->global_to_thread = (size_t)atomic_load64(&heap->global_to_thread);
     for (size_t iclass = 0; iclass < LARGE_CLASS_COUNT; ++iclass)
     {
         stats->span_use[iclass].current = (size_t)atomic_load32(&heap->span_use[iclass].current);
         stats->span_use[iclass].peak = (size_t)atomic_load32(&heap->span_use[iclass].high);
         stats->span_use[iclass].to_global = (size_t)atomic_load32(&heap->span_use[iclass].spans_to_global);
         stats->span_use[iclass].from_global = (size_t)atomic_load32(&heap->span_use[iclass].spans_from_global);
         stats->span_use[iclass].to_cache = (size_t)atomic_load32(&heap->span_use[iclass].spans_to_cache);
         stats->span_use[iclass].from_cache = (size_t)atomic_load32(&heap->span_use[iclass].spans_from_cache);
         stats->span_use[iclass].to_reserved = (size_t)atomic_load32(&heap->span_use[iclass].spans_to_reserved);
         stats->span_use[iclass].from_reserved = (size_t)atomic_load32(&heap->span_use[iclass].spans_from_reserved);
         stats->span_use[iclass].map_calls = (size_t)atomic_load32(&heap->span_use[iclass].spans_map_calls);
     }
     for (size_t iclass = 0; iclass < SIZE_CLASS_COUNT; ++iclass)
     {
         stats->size_use[iclass].alloc_current = (size_t)atomic_load32(&heap->size_class_use[iclass].alloc_current);
         stats->size_use[iclass].alloc_peak = (size_t)heap->size_class_use[iclass].alloc_peak;
         stats->size_use[iclass].alloc_total = (size_t)atomic_load32(&heap->size_class_use[iclass].alloc_total);
         stats->size_use[iclass].free_total = (size_t)atomic_load32(&heap->size_class_use[iclass].free_total);
         stats->size_use[iclass].spans_to_cache = (size_t)atomic_load32(&heap->size_class_use[iclass].spans_to_cache);
         stats->size_use[iclass].spans_from_cache = (size_t)atomic_load32(&heap->size_class_use[iclass].spans_from_cache);
         stats->size_use[iclass].spans_from_reserved = (size_t)atomic_load32(&heap->size_class_use[iclass].spans_from_reserved);
         stats->size_use[iclass].map_calls = (size_t)atomic_load32(&heap->size_class_use[iclass].spans_map_calls);
     }
 #endif
 }
References _memory_size_class, _memory_span_size, atomic_load64(), atomic_load_ptr(), size_class_t::block_count, size_class_t::block_size, span_cache_t::count, span_t::free_list, span_t::free_list_limit, get_thread_heap_raw(), rpmalloc_thread_statistics_t::global_to_thread, heap, LARGE_CLASS_COUNT, span_t::list_size, memset_unsafe(), span_t::next, span_t::size_class, SIZE_CLASS_COUNT, SIZE_CLASS_HUGE, rpmalloc_thread_statistics_t::size_use, rpmalloc_thread_statistics_t::sizecache, span_t::span_count, rpmalloc_thread_statistics_t::span_use, rpmalloc_thread_statistics_t::spancache, rpmalloc_thread_statistics_t::thread_to_global, and span_t::used_count.
rpmalloc_usable_size()
size_t rpmalloc_usable_size (void * ptr) inline
Query the usable size of the given memory block (from given pointer to the end of block)
Definition at line 3179 of file rpmalloc.c.
 {
     return (ptr ? _rpmalloc_usable_size(ptr) : 0);
 }
References _rpmalloc_usable_size().
rpmemalign()
RPMALLOC_ALLOCATOR void* rpmemalign (size_t alignment, size_t size) inline
Allocate a memory block of at least the given size and alignment.
Definition at line 3163 of file rpmalloc.c.
 {
     return rpaligned_alloc(alignment, size);
 }
References rpaligned_alloc(), and size.
rpposix_memalign()
int rpposix_memalign (void ** memptr, size_t alignment, size_t size) inline
Allocate a memory block of at least the given size and alignment.
Definition at line 3169 of file rpmalloc.c.
 {
     if (memptr)
         *memptr = rpaligned_alloc(alignment, size);
     else
         return EINVAL;
     return *memptr ? 0 : ENOMEM;
 }
References EINVAL, ENOMEM, rpaligned_alloc(), and size.
rprealloc()
RPMALLOC_ALLOCATOR void* rprealloc (void * ptr, size_t size) inline
Reallocate the given block to at least the given size.
Definition at line 3119 of file rpmalloc.c.
 {
 #if ENABLE_VALIDATE_ARGS
     assert(size < MAX_ALLOC_SIZE);
 #endif
     heap_t *heap = get_thread_heap();
     return _rpmalloc_reallocate(heap, ptr, size, 0, 0);
 }
References _rpmalloc_reallocate(), assert, get_thread_heap(), heap, MAX_ALLOC_SIZE, and size.
Referenced by realloc().
set_thread_heap()
static void set_thread_heap (heap_t * heap) static
Set the current thread heap.
Definition at line 738 of file rpmalloc.c.
 {
     _memory_thread_heap = heap;
     if (heap)
         heap->owner_thread = get_thread_id();
 }
References _memory_thread_heap, get_thread_id(), and heap.
Referenced by _rpmalloc_heap_release(), rpmalloc_thread_finalize(), and rpmalloc_thread_initialize().
Variable Documentation
_memory_config
rpmalloc_config_t _memory_config static
Configuration.
Definition at line 602 of file rpmalloc.c.
Referenced by _rpmalloc_mmap(), _rpmalloc_mmap_os(), _rpmalloc_set_name(), _rpmalloc_unmap(), rpmalloc_config(), and rpmalloc_initialize_config().
_memory_global_lock
atomic32_t _memory_global_lock static
Used to restrict access to mapping memory for huge pages.
Definition at line 647 of file rpmalloc.c.
Referenced by _rpmalloc_heap_allocate(), _rpmalloc_heap_release(), _rpmalloc_span_map(), _rpmalloc_span_map_aligned_count(), rpmalloc_finalize(), and rpmalloc_initialize_config().
_memory_global_reserve
span_t* _memory_global_reserve static
Global reserved spans.
Definition at line 639 of file rpmalloc.c.
Referenced by _rpmalloc_global_get_reserved_spans(), _rpmalloc_global_set_reserved_spans(), _rpmalloc_span_map_aligned_count(), and rpmalloc_finalize().
_memory_global_reserve_count
size_t _memory_global_reserve_count static
Global reserved count.
Definition at line 641 of file rpmalloc.c.
Referenced by _rpmalloc_global_get_reserved_spans(), _rpmalloc_global_set_reserved_spans(), _rpmalloc_heap_allocate_new(), _rpmalloc_span_map(), _rpmalloc_span_map_aligned_count(), and rpmalloc_finalize().
_memory_global_reserve_master
span_t* _memory_global_reserve_master static
Global reserved master.
Definition at line 643 of file rpmalloc.c.
Referenced by _rpmalloc_global_get_reserved_spans(), _rpmalloc_global_set_reserved_spans(), _rpmalloc_span_map(), _rpmalloc_span_map_aligned_count(), and rpmalloc_finalize().
_memory_heap_id
atomic32_t _memory_heap_id static
Heap ID counter.
Definition at line 631 of file rpmalloc.c.
Referenced by _rpmalloc_heap_initialize().
_memory_heap_reserve_count
size_t _memory_heap_reserve_count static
Number of spans to keep reserved in each heap.
Definition at line 625 of file rpmalloc.c.
Referenced by _rpmalloc_heap_allocate_new(), _rpmalloc_span_map(), _rpmalloc_span_map_aligned_count(), and rpmalloc_initialize_config().
_memory_heaps
heap_t* _memory_heaps[HEAP_ARRAY_SIZE] static
All heaps.
Definition at line 645 of file rpmalloc.c.
Referenced by _rpmalloc_heap_global_finalize(), _rpmalloc_heap_initialize(), rpmalloc_dump_statistics(), rpmalloc_finalize(), and rpmalloc_initialize_config().
_memory_huge_pages
int _memory_huge_pages static
Huge page support.
Definition at line 633 of file rpmalloc.c.
Referenced by _rpmalloc_set_name(), and rpmalloc_initialize_config().
_memory_map_granularity
size_t _memory_map_granularity static
Granularity at which memory pages are mapped by OS.
Definition at line 608 of file rpmalloc.c.
Referenced by _rpmalloc_mmap_os(), _rpmalloc_unmap_os(), and rpmalloc_initialize_config().
_memory_medium_size_limit
size_t _memory_medium_size_limit static
Run-time size limit of medium blocks.
Definition at line 629 of file rpmalloc.c.
Referenced by _rpmalloc_aligned_allocate(), _rpmalloc_allocate(), and rpmalloc_initialize_config().
_memory_orphan_heaps
heap_t* _memory_orphan_heaps static
Orphaned heaps.
Definition at line 649 of file rpmalloc.c.
Referenced by _rpmalloc_heap_allocate(), _rpmalloc_heap_orphan(), and rpmalloc_initialize_config().
_memory_page_size
size_t _memory_page_size static
Memory page size.
Definition at line 604 of file rpmalloc.c.
Referenced by _rpmalloc_aligned_allocate(), _rpmalloc_allocate_from_heap_fallback(), _rpmalloc_allocate_huge(), _rpmalloc_deallocate_huge(), _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_allocate_new(), _rpmalloc_mmap(), _rpmalloc_mmap_os(), _rpmalloc_reallocate(), _rpmalloc_span_align_count(), _rpmalloc_span_map(), _rpmalloc_span_unmap(), _rpmalloc_unmap(), _rpmalloc_unmap_os(), _rpmalloc_usable_size(), free_list_partial_init(), rpaligned_realloc(), rpmalloc_dump_statistics(), rpmalloc_global_statistics(), and rpmalloc_initialize_config().
_memory_page_size_shift
size_t _memory_page_size_shift static
Shift to divide by page size.
Definition at line 606 of file rpmalloc.c.
Referenced by _rpmalloc_allocate_huge(), _rpmalloc_mmap(), _rpmalloc_mmap_os(), _rpmalloc_reallocate(), _rpmalloc_unmap(), _rpmalloc_unmap_os(), and rpmalloc_initialize_config().
_memory_size_class
size_class_t _memory_size_class[SIZE_CLASS_COUNT] static
Global size classes.
Definition at line 627 of file rpmalloc.c.
Referenced by _rpmalloc_adjust_size_class(), _rpmalloc_allocate_from_heap_fallback(), _rpmalloc_allocate_medium(), _rpmalloc_span_initialize_new(), rpmalloc_initialize_config(), and rpmalloc_thread_statistics().
_memory_span_cache
global_cache_t _memory_span_cache[LARGE_CLASS_COUNT] static
Global span cache.
Definition at line 636 of file rpmalloc.c.
Referenced by _rpmalloc_global_cache_extract_spans(), _rpmalloc_global_cache_insert_spans(), rpmalloc_dump_statistics(), rpmalloc_finalize(), and rpmalloc_global_statistics().
_memory_span_map_count
size_t _memory_span_map_count static
Number of spans to map in each map call.
Definition at line 623 of file rpmalloc.c.
Referenced by _rpmalloc_span_align_count(), _rpmalloc_span_map(), and rpmalloc_initialize_config().
_memory_span_mask
uintptr_t _memory_span_mask static
Mask to get to start of a memory span.
Definition at line 615 of file rpmalloc.c.
Referenced by _rpmalloc_aligned_allocate(), _rpmalloc_deallocate(), _rpmalloc_heap_finalize(), _rpmalloc_heap_unmap(), _rpmalloc_mmap_os(), _rpmalloc_reallocate(), _rpmalloc_span_finalize(), _rpmalloc_usable_size(), and rpmalloc_initialize_config().
_memory_span_size
size_t _memory_span_size static
Size of a span of memory pages.
Definition at line 611 of file rpmalloc.c.
Referenced by _rpmalloc_adjust_size_class(), _rpmalloc_aligned_allocate(), _rpmalloc_allocate_large(), _rpmalloc_deallocate_large(), _rpmalloc_global_cache_insert_spans(), _rpmalloc_heap_allocate_new(), _rpmalloc_heap_cache_insert(), _rpmalloc_heap_global_cache_extract(), _rpmalloc_heap_release(), _rpmalloc_mmap_os(), _rpmalloc_reallocate(), _rpmalloc_span_align_count(), _rpmalloc_span_map(), _rpmalloc_span_map_aligned_count(), _rpmalloc_span_map_from_reserve(), _rpmalloc_span_unmap(), _rpmalloc_unmap_os(), _rpmalloc_usable_size(), rpmalloc_dump_statistics(), rpmalloc_global_statistics(), rpmalloc_initialize_config(), and rpmalloc_thread_statistics().
_memory_span_size_shift
size_t _memory_span_size_shift static
Shift to divide by span size.
Definition at line 613 of file rpmalloc.c.
Referenced by _rpmalloc_allocate_large(), _rpmalloc_global_get_reserved_spans(), _rpmalloc_reallocate(), _rpmalloc_span_map(), _rpmalloc_span_mark_as_subspan_unless_master(), and rpmalloc_initialize_config().
_rpmalloc_initialized
int _rpmalloc_initialized static
Initialized flag.
Definition at line 598 of file rpmalloc.c.
Referenced by rpmalloc_finalize(), rpmalloc_initialize(), and rpmalloc_initialize_config().
_rpmalloc_main_thread_id
uintptr_t _rpmalloc_main_thread_id static
Main thread ID.
Definition at line 600 of file rpmalloc.c.
Referenced by _rpmalloc_heap_release(), and rpmalloc_set_main_thread().