Fennix: Drivers/input/aip/main.c File Reference
main.c File Reference
#include "aip.h"
#include <errno.h>
#include <base.h>
Functions
bool IsKeyboard (uint8_t ID)
bool IsMouse (uint8_t ID)
const char * GetPS2DeviceName (uint8_t ID, uint8_t SubID)
int DriverEntry ()
int DriverFinal ()
int DriverPanic ()
void __intStub ()
int DriverProbe ()
DriverInfo ("aip", "Advanced Integrated Peripheral Driver", "EnderIce2", "0.1", "GPLv3")
Variables
uint8_t Device1ID [2] = {0x00, 0x00}
uint8_t Device2ID [2] = {0x00, 0x00}
bool DualChannel = false
Function Documentation
__intStub()
void __intStub ()
Definition at line 189 of file main.c.
 {}
Referenced by DriverProbe().
DriverEntry()
int DriverEntry ()
A device may fail, but if the other one works, we can still use it.
Definition at line 96 of file main.c.
 {
     PS2WriteCommand(PS2_CMD_DISABLE_PORT_1);
     PS2WriteCommand(PS2_CMD_DISABLE_PORT_2);
     PS2ClearOutputBuffer();
     PS2WriteCommand(PS2_CMD_READ_CONFIG);
     PS2_CONFIGURATION cfg = {.Raw = PS2ReadData()};
     DualChannel = cfg.Port2Clock;
     if (DualChannel)
         Log("Dual channel PS/2 controller detected");
     cfg.Port1Interrupt = 1;
     cfg.Port2Interrupt = 1;
     cfg.Port1Translation = 1;
     PS2WriteCommand(PS2_CMD_WRITE_CONFIG);
     PS2WriteData(cfg.Raw);
     PS2WriteCommand(PS2_CMD_TEST_CONTROLLER);
     uint8_t test = PS2ReadData();
     if (test != PS2_TEST_PASSED)
     {
         Log("PS/2 controller self test failed (%#x)", test);
         return -EFAULT;
     }
     PS2WriteCommand(PS2_CMD_WRITE_CONFIG);
     PS2WriteData(cfg.Raw);
     // bool port2avail = false;
     // if (DualChannel)
     // {
     //  PS2WriteCommand(PS2_CMD_ENABLE_PORT_1);
     //  PS2WriteCommand(PS2_CMD_READ_CONFIG);
     //  cfg.Raw = PS2ReadData();
     //  port2avail = cfg.Port2Clock;
     //  PS2WriteCommand(PS2_CMD_DISABLE_PORT_1);
     // }
     PS2WriteCommand(PS2_CMD_TEST_PORT_1);
     test = PS2ReadData();
     if (test != 0x00)
     {
         Log("PS/2 Port 1 self test failed (%#x)", test);
         return -EFAULT;
     }
     if (DualChannel)
     {
         PS2WriteCommand(PS2_CMD_TEST_PORT_2);
         test = PS2ReadData();
         if (test != 0x00)
         {
             Log("PS/2 Port 2 self test failed (%#x)", test);
             return -EFAULT;
         }
     }
     PS2WriteCommand(PS2_CMD_ENABLE_PORT_1);
     if (DualChannel)
         PS2WriteCommand(PS2_CMD_ENABLE_PORT_2);
     int errK = InitializeKeyboard();
     int errM = 0;
     if (DualChannel)
         errM = InitializeMouse();
     if (errK != 0 && errM != 0)
         return -ENODEV;
     return 0;
 }
References DualChannel, EFAULT, ENODEV, InitializeKeyboard(), InitializeMouse(), Log(), PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, PS2_CMD_ENABLE_PORT_1, PS2_CMD_ENABLE_PORT_2, PS2_CMD_READ_CONFIG, PS2_CMD_TEST_CONTROLLER, PS2_CMD_TEST_PORT_1, PS2_CMD_TEST_PORT_2, PS2_CMD_WRITE_CONFIG, PS2_TEST_PASSED, PS2ClearOutputBuffer(), PS2ReadData(), PS2WriteCommand(), PS2WriteData(), PS2_CONFIGURATION::Raw, and test.
DriverFinal()
int DriverFinal ()
Definition at line 173 of file main.c.
 {
     FinalizeKeyboard();
     FinalizeMouse();
     PS2WriteCommand(PS2_CMD_DISABLE_PORT_1);
     PS2WriteCommand(PS2_CMD_DISABLE_PORT_2);
     return 0;
 }
References FinalizeKeyboard(), FinalizeMouse(), PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, and PS2WriteCommand().
DriverInfo()
DriverInfo ("aip" , "Advanced Integrated Peripheral Driver" , "EnderIce2" , "0.1" , "GPLv3")
DriverPanic()
int DriverPanic ()
Definition at line 182 of file main.c.
 {
     PS2WriteCommand(PS2_CMD_DISABLE_PORT_1);
     PS2WriteCommand(PS2_CMD_DISABLE_PORT_2);
     return 0;
 }
References PS2_CMD_DISABLE_PORT_1, PS2_CMD_DISABLE_PORT_2, and PS2WriteCommand().
DriverProbe()
int DriverProbe ()
Definition at line 190 of file main.c.
 {
     RegisterInterruptHandler(1, __intStub);
     RegisterInterruptHandler(12, __intStub);
     int kbd = DetectPS2Keyboard();
     int mouse = DetectPS2Mouse();
     UnregisterAllInterruptHandlers(__intStub);
     if (kbd != 0 && mouse != 0)
         return -ENODEV;
     if (kbd == 0)
     {
         if (!IsKeyboard(Device1ID[0]))
         {
             Log("PS/2 Port 1 is not a keyboard");
             // return -EINVAL;
         }
     }
     if (mouse == 0)
     {
         if (!IsMouse(Device2ID[0]))
         {
             Log("PS/2 Port 2 is not a mouse");
             // return -EINVAL;
         }
     }
     KPrint("PS/2 Port 1: %s (0x%X 0x%X)",
            GetPS2DeviceName(Device1ID[0], Device1ID[1]),
            Device1ID[0], Device1ID[1]);
     KPrint("PS/2 Port 2: %s (0x%X 0x%X)",
            GetPS2DeviceName(Device2ID[0], Device2ID[1]),
            Device2ID[0], Device2ID[1]);
     return 0;
 }
References __intStub(), DetectPS2Keyboard(), DetectPS2Mouse(), Device1ID, Device2ID, ENODEV, GetPS2DeviceName(), IsKeyboard(), IsMouse(), KPrint(), Log(), Driver::RegisterInterruptHandler(), and Driver::UnregisterAllInterruptHandlers().
GetPS2DeviceName()
const char* GetPS2DeviceName (uint8_t ID, uint8_t SubID)
Definition at line 36 of file main.c.
 {
     switch (ID)
     {
     case 0x00:
         return "Standard PS/2 Mouse";
     case 0x03:
         return "Mouse with scroll wheel";
     case 0x04:
         return "Mouse 5 buttons";
     case 0xAB:
     {
         switch (SubID)
         {
         case 0x83: /* Normal */
         case 0x41: /* Translated */
         case 0xC1: /* Normal + Translated */
             return "Standard PS/2 Keyboard";
         case 0x84:
         case 0x54:
             return "IBM Thinkpad/Spacesaver Keyboard";
         case 0x85:
             return "NCD N-97/122-Key Host Connect(ed) Keyboard";
         case 0x86:
             return "122-Key Keyboard";
         case 0x90:
             return "Japanese \"G\" Keyboard";
         case 0x91:
             return "Japanese \"P\" Keyboard";
         case 0x92:
             return "Japanese \"A\" Keyboard";
         default:
             return "Unknown PS/2 Keyboard";
         }
     }
     case 0xAC:
     {
         switch (SubID)
         {
         case 0xA1:
             return "NCD Sun Keyboard";
         default:
             return "Unknown NCD Sun Keyboard";
         }
     }
     case 0x5D:
     case 0x2B:
         return "Trust Keyboard";
     case 0x47:
     case 0x60:
         return "NMB SGI Keyboard";
     default:
         return "Unknown PS/2 Device";
     }
 }
References ID.
Referenced by DriverProbe().
IsKeyboard()
bool IsKeyboard (uint8_t ID)
Definition at line 23 of file main.c.
 {
     /* Common keyboard IDs */
     return ID == 0xAB || ID == 0xAC || ID == 0x5D ||
            ID == 0x2B || ID == 0x47 || ID == 0x60;
 }
References ID.
Referenced by DriverProbe().
IsMouse()
bool IsMouse (uint8_t ID)
Definition at line 30 of file main.c.
 {
     /* Common mouse IDs */
     return ID == 0x00 || ID == 0x03 || ID == 0x04;
 }
References ID.
Referenced by DriverProbe().
Variable Documentation
Device1ID
uint8_t Device1ID[2] = {0x00, 0x00}
Definition at line 92 of file main.c.
Referenced by DetectPS2Keyboard(), and DriverProbe().
Device2ID
uint8_t Device2ID[2] = {0x00, 0x00}
Definition at line 93 of file main.c.
Referenced by DetectPS2Mouse(), DriverProbe(), and InitializeMouse().
DualChannel
bool DualChannel = false
Definition at line 94 of file main.c.
Referenced by DriverEntry().