Fennix: Userspace/apps/base/busybox/libbb/mode_string.c File Reference
mode_string.c File Reference
#include <assert.h>
#include "libbb.h"
Functions
char *FAST_FUNC bb_mode_string (char buf[11], mode_t mode)
Variables
static const mode_t mode_flags[] ALIGN4
static const char type_chars[16] ALIGN1 = "?pc?d?b?-?l?s???"
Function Documentation
bb_mode_string()
char* FAST_FUNC bb_mode_string (char buf[11], mode_t mode)
Definition at line 44 of file mode_string.c.
 {
     char *p = buf;
     int i, j, k;
     *p = type_chars[ (mode >> 12) & 0xf ];
     i = 0;
     do {
         j = k = 0;
         do {
             *++p = '-';
             if (mode & mode_flags[i+j]) {
                 *p = mode_chars[j];
                 k = j;
             }
         } while (++j < 3);
         if (mode & mode_flags[i+j]) {
             *p = mode_chars[3 + (k & 2) + ((i&8) >> 3)];
         }
         i += 4;
     } while (i < 12);
     buf[10] = '\0';
     return buf;
 }
References buf, i, j, k, and p.
Referenced by display_single(), do_stat(), fileAction(), header_verbose_list(), and header_verbose_list_ar().
Variable Documentation
ALIGN1
const char mode_chars [7] ALIGN1 = "?pc?d?b?-?l?s???" static
Definition at line 40 of file mode_string.c.
ALIGN4
const mode_t mode_flags [] ALIGN4 static
Initial value:
= {
    S_IRUSR, S_IWUSR, S_IXUSR, S_ISUID,
    S_IRGRP, S_IWGRP, S_IXGRP, S_ISGID,
    S_IROTH, S_IWOTH, S_IXOTH, S_ISVTX
}
Definition at line 32 of file mode_string.c.