Fennix: Drivers/include/aip.h File Reference
aip.h File Reference
#include <types.h>
#include <aip/kbd.h>
#include <aip/mouse.h>
Data Structures
union PS2_STATUSES
union PS2_CONFIGURATION
union PS2_OUTPUT_PORT
struct PS2_STATUSES.__unnamed1249__
struct PS2_CONFIGURATION.__unnamed1251__
struct PS2_OUTPUT_PORT.__unnamed1253__
Macros
#define PIC1_CMD 0x20
#define PIC1_DATA (PIC1_CMD + 1)
#define PIC2_CMD 0xA0
#define PIC2_DATA (PIC2_CMD + 1)
#define _PIC_EOI 0x20
#define PS2_DATA 0x60
#define PS2_STATUS 0x64
#define PS2_CMD PS2_STATUS
#define PS2_ACK 0xFA
#define PS2_TEST_PASSED 0x55
#define PS2_TEST_FAILED 0xFC
#define PS2_CMD_READ_CONFIG 0x20
#define PS2_CMD_READ_CONFIG_N(n) (PS2_CMD_READ_CONFIG + n)
#define PS2_CMD_WRITE_CONFIG 0x60
#define PS2_CMD_WRITE_CONFIG_N(n) (PS2_CMD_WRITE_CONFIG + n)
#define PS2_CMD_DISABLE_PORT_2 0xA7
#define PS2_CMD_ENABLE_PORT_2 0xA8
#define PS2_CMD_TEST_PORT_2 0xA9
#define PS2_CMD_TEST_CONTROLLER 0xAA
#define PS2_CMD_TEST_PORT_1 0xAB
#define PS2_CMD_DIAGNOSTIC_DUMP 0xAC
#define PS2_CMD_DISABLE_PORT_1 0xAD
#define PS2_CMD_ENABLE_PORT_1 0xAE
#define PS2_CMD_READ_INPUT_PORT 0xC0
#define PS2_CMD_COPY_INPUT_0_3_TO_4_7_STATUS 0xC1
#define PS2_CMD_COPY_INPUT_4_7_TO_4_7_STATUS 0xC2
#define PS2_CMD_READ_OUTPUT_PORT 0xD0
#define PS2_CMD_WRITE_NEXT_BYTE_TO_OUTPUT_PORT 0xD1
#define PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_1_OUTPUT 0xD2
#define PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_OUTPUT 0xD3
#define PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT 0xD4
#define PS2_CMD_PULSE_OUTPUT_LINE(n) (0xF0 + n)
#define WaitOutput PS2Wait(true)
#define WaitInput PS2Wait(false)
Functions
void PIC_EOI (uint8_t IRQ)
void IRQ_MASK (uint8_t IRQ)
void IRQ_UNMASK (uint8_t IRQ)
void PS2Wait (const bool Output)
void PS2WriteCommand (uint8_t Command)
void PS2WriteData (uint8_t Data)
uint8_t PS2ReadData ()
uint8_t PS2ReadStatus ()
uint8_t PS2ReadAfterACK ()
void PS2ClearOutputBuffer ()
int PS2ACKTimeout ()
Data Structure Documentation
PS2_STATUSES
union PS2_STATUSES
Definition at line 60 of file aip.h.
Data Fields
struct PS2_STATUSES __unnamed__
uint8_t Raw
PS2_CONFIGURATION
union PS2_CONFIGURATION
Definition at line 76 of file aip.h.
Data Fields
struct PS2_CONFIGURATION __unnamed__
uint8_t Raw
PS2_OUTPUT_PORT
union PS2_OUTPUT_PORT
Definition at line 92 of file aip.h.
Data Fields
struct PS2_OUTPUT_PORT __unnamed__
uint8_t Raw
PS2_STATUSES.__unnamed1249__
struct PS2_STATUSES.__unnamed1249__
Definition at line 62 of file aip.h.
Data Fields
uint8_t CommandData: 1
uint8_t InputBufferFull: 1
uint8_t OutputBufferFull: 1
uint8_t ParityError: 1
uint8_t SystemFlag: 1
uint8_t TimeoutError: 1
uint8_t Unknown1: 1
uint8_t Unknown2: 1
PS2_CONFIGURATION.__unnamed1251__
struct PS2_CONFIGURATION.__unnamed1251__
Definition at line 78 of file aip.h.
Data Fields
uint8_t Port1Clock: 1
uint8_t Port1Interrupt: 1
uint8_t Port1Translation: 1
uint8_t Port2Clock: 1
uint8_t Port2Interrupt: 1
uint8_t SystemFlag: 1
uint8_t Zero0: 1
uint8_t Zero1: 1
PS2_OUTPUT_PORT.__unnamed1253__
struct PS2_OUTPUT_PORT.__unnamed1253__
Definition at line 94 of file aip.h.
Data Fields
uint8_t A20Gate: 1
uint8_t Port1InputBufferFull: 1
uint8_t Port1OutputBufferFull: 1
uint8_t Port2Clock: 1
uint8_t Port2Data: 1
uint8_t Port2InputBufferFull: 1
uint8_t Port2OutputBufferFull: 1
uint8_t SystemReset: 1
Macro Definition Documentation
_PIC_EOI
#define _PIC_EOI 0x20
Definition at line 29 of file aip.h.
PIC1_CMD
#define PIC1_CMD 0x20
Definition at line 25 of file aip.h.
PIC1_DATA
#define PIC1_DATA (PIC1_CMD + 1)
Definition at line 26 of file aip.h.
PIC2_CMD
#define PIC2_CMD 0xA0
Definition at line 27 of file aip.h.
PIC2_DATA
#define PIC2_DATA (PIC2_CMD + 1)
Definition at line 28 of file aip.h.
PS2_ACK
#define PS2_ACK 0xFA
Definition at line 34 of file aip.h.
PS2_CMD
#define PS2_CMD PS2_STATUS
Definition at line 33 of file aip.h.
PS2_CMD_COPY_INPUT_0_3_TO_4_7_STATUS
#define PS2_CMD_COPY_INPUT_0_3_TO_4_7_STATUS 0xC1
Definition at line 51 of file aip.h.
PS2_CMD_COPY_INPUT_4_7_TO_4_7_STATUS
#define PS2_CMD_COPY_INPUT_4_7_TO_4_7_STATUS 0xC2
Definition at line 52 of file aip.h.
PS2_CMD_DIAGNOSTIC_DUMP
#define PS2_CMD_DIAGNOSTIC_DUMP 0xAC
Definition at line 47 of file aip.h.
PS2_CMD_DISABLE_PORT_1
#define PS2_CMD_DISABLE_PORT_1 0xAD
Definition at line 48 of file aip.h.
PS2_CMD_DISABLE_PORT_2
#define PS2_CMD_DISABLE_PORT_2 0xA7
Definition at line 42 of file aip.h.
PS2_CMD_ENABLE_PORT_1
#define PS2_CMD_ENABLE_PORT_1 0xAE
Definition at line 49 of file aip.h.
PS2_CMD_ENABLE_PORT_2
#define PS2_CMD_ENABLE_PORT_2 0xA8
Definition at line 43 of file aip.h.
PS2_CMD_PULSE_OUTPUT_LINE
#define PS2_CMD_PULSE_OUTPUT_LINE (n) (0xF0 + n)
Definition at line 58 of file aip.h.
PS2_CMD_READ_CONFIG
#define PS2_CMD_READ_CONFIG 0x20
Definition at line 38 of file aip.h.
PS2_CMD_READ_CONFIG_N
#define PS2_CMD_READ_CONFIG_N (n) (PS2_CMD_READ_CONFIG + n)
Definition at line 39 of file aip.h.
PS2_CMD_READ_INPUT_PORT
#define PS2_CMD_READ_INPUT_PORT 0xC0
Definition at line 50 of file aip.h.
PS2_CMD_READ_OUTPUT_PORT
#define PS2_CMD_READ_OUTPUT_PORT 0xD0
Definition at line 53 of file aip.h.
PS2_CMD_TEST_CONTROLLER
#define PS2_CMD_TEST_CONTROLLER 0xAA
Definition at line 45 of file aip.h.
PS2_CMD_TEST_PORT_1
#define PS2_CMD_TEST_PORT_1 0xAB
Definition at line 46 of file aip.h.
PS2_CMD_TEST_PORT_2
#define PS2_CMD_TEST_PORT_2 0xA9
Definition at line 44 of file aip.h.
PS2_CMD_WRITE_CONFIG
#define PS2_CMD_WRITE_CONFIG 0x60
Definition at line 40 of file aip.h.
PS2_CMD_WRITE_CONFIG_N
#define PS2_CMD_WRITE_CONFIG_N (n) (PS2_CMD_WRITE_CONFIG + n)
Definition at line 41 of file aip.h.
PS2_CMD_WRITE_NEXT_BYTE_TO_OUTPUT_PORT
#define PS2_CMD_WRITE_NEXT_BYTE_TO_OUTPUT_PORT 0xD1
Definition at line 54 of file aip.h.
PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_1_OUTPUT
#define PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_1_OUTPUT 0xD2
Definition at line 55 of file aip.h.
PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT
#define PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_INPUT 0xD4
Definition at line 57 of file aip.h.
PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_OUTPUT
#define PS2_CMD_WRITE_NEXT_BYTE_TO_PS2_PORT_2_OUTPUT 0xD3
Definition at line 56 of file aip.h.
PS2_DATA
#define PS2_DATA 0x60
Definition at line 31 of file aip.h.
PS2_STATUS
#define PS2_STATUS 0x64
Definition at line 32 of file aip.h.
PS2_TEST_FAILED
#define PS2_TEST_FAILED 0xFC
Definition at line 36 of file aip.h.
PS2_TEST_PASSED
#define PS2_TEST_PASSED 0x55
Definition at line 35 of file aip.h.
WaitInput
#define WaitInput PS2Wait(false)
Definition at line 121 of file aip.h.
WaitOutput
#define WaitOutput PS2Wait(true)
Definition at line 120 of file aip.h.
Function Documentation
IRQ_MASK()
void IRQ_MASK (uint8_t IRQ)
Definition at line 32 of file aip.c.
 {
     uint16_t port;
     uint8_t value;
     if (IRQ < 8)
         port = PIC1_DATA;
     else
     {
         port = PIC2_DATA;
         IRQ -= 8;
     }
     value = inb(port) | (1 << IRQ);
     outb(port, value);
 }
References inb(), outb(), PIC1_DATA, PIC2_DATA, port, and value.
IRQ_UNMASK()
void IRQ_UNMASK (uint8_t IRQ)
Definition at line 49 of file aip.c.
 {
     uint16_t port;
     uint8_t value;
     if (IRQ < 8)
         port = PIC1_DATA;
     else
     {
         port = PIC2_DATA;
         IRQ -= 8;
     }
     value = inb(port) & ~(1 << IRQ);
     outb(port, value);
 }
References inb(), outb(), PIC1_DATA, PIC2_DATA, port, and value.
PIC_EOI()
void PIC_EOI (uint8_t IRQ)
Definition at line 25 of file aip.c.
 {
     if (IRQ >= 8)
         outb(PIC2_CMD, _PIC_EOI);
     outb(PIC1_CMD, _PIC_EOI);
 }
References _PIC_EOI, outb(), PIC1_CMD, and PIC2_CMD.
PS2ACKTimeout()
int PS2ACKTimeout ()
Definition at line 136 of file aip.c.
 {
     int timeout = 0x500;
     while (timeout > 0)
     {
         if (PS2ReadData() == PS2_ACK)
             return 0;
         timeout--;
     }
     return -ETIMEDOUT;
 }
References ETIMEDOUT, PS2_ACK, PS2ReadData(), and timeout().
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), and InitializeKeyboard().
PS2ClearOutputBuffer()
void PS2ClearOutputBuffer ()
Definition at line 123 of file aip.c.
 {
     PS2_STATUSES Status;
     int timeout = 0x500;
     while (timeout--)
     {
         Status.Raw = inb(PS2_STATUS);
         if (Status.OutputBufferFull == 0)
             return;
         inb(PS2_DATA);
     }
 }
References inb(), PS2_DATA, PS2_STATUS, PS2_STATUSES::Raw, and timeout().
Referenced by DriverEntry(), and InitializeKeyboard().
PS2ReadAfterACK()
uint8_t PS2ReadAfterACK ()
Definition at line 112 of file aip.c.
 {
     uint8_t ret = PS2ReadData();
     while (ret == PS2_ACK)
     {
         WaitOutput;
         ret = inb(PS2_DATA);
     }
     return ret;
 }
References inb(), PS2_ACK, PS2_DATA, PS2ReadData(), and WaitOutput.
Referenced by InitializeKeyboard().
PS2ReadData()
uint8_t PS2ReadData ()
Definition at line 100 of file aip.c.
 {
     WaitOutput;
     return inb(PS2_DATA);
 }
References inb(), PS2_DATA, and WaitOutput.
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), DriverEntry(), InitializeMouse(), MouseSampleRate(), PS2ACKTimeout(), PS2MouseInterruptHandler(), and PS2ReadAfterACK().
PS2ReadStatus()
uint8_t PS2ReadStatus ()
Definition at line 106 of file aip.c.
 {
     WaitOutput;
     return inb(PS2_STATUS);
 }
References inb(), PS2_STATUS, and WaitOutput.
PS2Wait()
void PS2Wait (const bool Output)
Definition at line 66 of file aip.c.
 {
     int Timeout = 100000;
     PS2_STATUSES Status = {.Raw = inb(PS2_STATUS)};
     while (Timeout--)
     {
         if (!Output) /* FIXME: Reverse? */
         {
             if (Status.OutputBufferFull == 0)
                 return;
         }
         else
         {
             if (Status.InputBufferFull == 0)
                 return;
         }
         Status.Raw = inb(PS2_STATUS);
     }
     Log("PS/2 controller timeout! (Status: %#x, %d)", Status, Output);
 }
References inb(), Log(), PS2_STATUS, and PS2_STATUSES::Raw.
PS2WriteCommand()
void PS2WriteCommand (uint8_t Command)
Definition at line 88 of file aip.c.
 {
     WaitInput;
     outb(PS2_CMD, Command);
 }
References outb(), PS2_CMD, and WaitInput.
Referenced by DetectPS2Mouse(), DriverEntry(), DriverFinal(), DriverPanic(), FinalizeMouse(), InitializeMouse(), and MouseSampleRate().
PS2WriteData()
void PS2WriteData (uint8_t Data)
Definition at line 94 of file aip.c.
 {
     WaitInput;
     outb(PS2_DATA, Data);
 }
References Data, outb(), PS2_DATA, and WaitInput.
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), DriverEntry(), DriverFinal(), DriverPanic(), FinalizeMouse(), InitializeKeyboard(), InitializeMouse(), and MouseSampleRate().