Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/d_loop.c File Reference
d_loop.c File Reference
#include <stdlib.h>
#include <string.h>
#include "doomfeatures.h"
#include "d_event.h"
#include "d_loop.h"
#include "d_ticcmd.h"
#include "i_system.h"
#include "i_timer.h"
#include "i_video.h"
#include "m_argv.h"
#include "m_fixed.h"
#include "net_client.h"
#include "net_gui.h"
#include "net_io.h"
#include "net_query.h"
#include "net_server.h"
#include "net_sdl.h"
#include "net_loop.h"
Data Structures
struct ticcmd_set_t
Functions
static int GetAdjustedTime (void)
static boolean BuildNewTic (void)
void NetUpdate (void)
static void D_Disconnected (void)
void D_ReceiveTic (ticcmd_t *ticcmds, boolean *players_mask)
void D_StartGameLoop (void)
void D_StartNetGame (net_gamesettings_t *settings, netgame_startup_callback_t callback)
boolean D_InitNetGame (net_connect_data_t *connect_data)
void D_QuitNetGame (void)
static int GetLowTic (void)
static void OldNetSync (void)
static boolean PlayersInGame (void)
static void TicdupSquash (ticcmd_set_t *set)
static void SinglePlayerClear (ticcmd_set_t *set)
void TryRunTics (void)
void D_RegisterLoopCallbacks (loop_interface_t *i)
Variables
static ticcmd_set_t ticdata [BACKUPTICS]
static int maketic
static int recvtic
int gametic
boolean singletics = false
static int localplayer
static int skiptics = 0
int ticdup
fixed_t offsetms
static boolean new_sync = true
static loop_interface_t * loop_interface = NULL
static boolean local_playeringame [NET_MAXPLAYERS]
static int player_class
int lasttime
static int frameon
static int frameskip [4]
static int oldnettics
Data Structure Documentation
ticcmd_set_t
struct ticcmd_set_t
Definition at line 45 of file d_loop.c.
Data Fields
ticcmd_t cmds[NET_MAXPLAYERS]
boolean ingame[NET_MAXPLAYERS]
Function Documentation
BuildNewTic()
static boolean BuildNewTic (void) static
Definition at line 136 of file d_loop.c.
 {
     int gameticdiv;
     ticcmd_t cmd;
     gameticdiv = gametic/ticdup;
     I_StartTic ();
     loop_interface->ProcessEvents();
     // Always run the menu
     loop_interface->RunMenu();
     if (drone)
     {
         // In drone mode, do not generate any ticcmds.
         return false;
     }
     if (new_sync)
     {
        // If playing single player, do not allow tics to buffer
        // up very far
        if (!net_client_connected && maketic - gameticdiv > 2)
            return false;
        // Never go more than ~200ms ahead
        if (maketic - gameticdiv > 8)
            return false;
     }
     else
     {
        if (maketic - gameticdiv >= 5)
            return false;
     }
     //printf ("mk:%i ",maketic);
     memset(&cmd, 0, sizeof(ticcmd_t));
     loop_interface->BuildTiccmd(&cmd, maketic);
 #ifdef FEATURE_MULTIPLAYER
     if (net_client_connected)
     {
         NET_CL_SendTiccmd(&cmd, maketic);
     }
 #endif
     ticdata[maketic % BACKUPTICS].cmds[localplayer] = cmd;
     ticdata[maketic % BACKUPTICS].ingame[localplayer] = true;
     ++maketic;
     return true;
 }
References BACKUPTICS, loop_interface_t::BuildTiccmd, ticcmd_set_t::cmds, drone, gametic, I_StartTic(), ticcmd_set_t::ingame, localplayer, loop_interface, maketic, memset(), NET_CL_SendTiccmd(), net_client_connected, new_sync, loop_interface_t::ProcessEvents, loop_interface_t::RunMenu, ticdata, and ticdup.
Referenced by NetUpdate(), and TryRunTics().
D_Disconnected()
static void D_Disconnected (void) static
Definition at line 252 of file d_loop.c.
 {
     // In drone mode, the game cannot continue once disconnected.
     if (drone)
     {
         I_Error("Disconnected from server in drone mode.");
     }
     // disconnected from server
     printf("Disconnected from server.\n");
 }
References drone, I_Error(), and printf().
Referenced by D_ReceiveTic().
D_InitNetGame()
boolean D_InitNetGame (net_connect_data_t * connect_data)
Definition at line 452 of file d_loop.c.
 {
     boolean result = false;
 #ifdef FEATURE_MULTIPLAYER
     net_addr_t *addr = NULL;
     int i;
 #endif
     // Call D_QuitNetGame on exit:
     I_AtExit(D_QuitNetGame, true);
     player_class = connect_data->player_class;
 #ifdef FEATURE_MULTIPLAYER
     // @category net
     //
     // Start a multiplayer server, listening for connections.
     //
     if (M_CheckParm("-server") > 0
      || M_CheckParm("-privateserver") > 0)
     {
         NET_SV_Init();
         NET_SV_AddModule(&net_loop_server_module);
         NET_SV_AddModule(&net_sdl_module);
         NET_SV_RegisterWithMaster();
         net_loop_client_module.InitClient();
         addr = net_loop_client_module.ResolveAddress(NULL);
     }
     else
     {
         // @category net
         //
         // Automatically search the local LAN for a multiplayer
         // server and join it.
         //
         i = M_CheckParm("-autojoin");
         if (i > 0)
         {
             addr = NET_FindLANServer();
             if (addr == NULL)
             {
                 I_Error("No server found on local LAN");
             }
         }
         // @arg <address>
         // @category net
         //
         // Connect to a multiplayer server running on the given
         // address.
         //
         i = M_CheckParmWithArgs("-connect", 1);
         if (i > 0)
         {
             net_sdl_module.InitClient();
             addr = net_sdl_module.ResolveAddress(myargv[i+1]);
             if (addr == NULL)
             {
                 I_Error("Unable to resolve '%s'\n", myargv[i+1]);
             }
         }
     }
     if (addr != NULL)
     {
         if (M_CheckParm("-drone") > 0)
         {
             connect_data->drone = true;
         }
         if (!NET_CL_Connect(addr, connect_data))
         {
             I_Error("D_InitNetGame: Failed to connect to %s\n",
                     NET_AddrToString(addr));
         }
         printf("D_InitNetGame: Connected to %s\n", NET_AddrToString(addr));
         // Wait for launch message received from server.
         NET_WaitForLaunch();
         result = true;
     }
 #endif
     return result;
 }
References addr, D_QuitNetGame(), net_connect_data_t::drone, i, I_AtExit(), I_Error(), _net_module_s::InitClient, M_CheckParm(), M_CheckParmWithArgs(), myargv, NET_AddrToString(), NET_CL_Connect(), NET_FindLANServer(), net_loop_client_module, net_loop_server_module, net_sdl_module, NET_SV_AddModule(), NET_SV_Init(), NET_SV_RegisterWithMaster(), NET_WaitForLaunch(), NULL, player_class, net_connect_data_t::player_class, printf(), and _net_module_s::ResolveAddress.
Referenced by D_ConnectNetGame().
D_QuitNetGame()
void D_QuitNetGame (void)
Definition at line 560 of file d_loop.c.
 {
 #ifdef FEATURE_MULTIPLAYER
     NET_SV_Shutdown();
     NET_CL_Disconnect();
 #endif
 }
References NET_CL_Disconnect(), and NET_SV_Shutdown().
Referenced by D_InitNetGame().
D_ReceiveTic()
void D_ReceiveTic (ticcmd_t * ticcmds, boolean * players_mask)
Definition at line 271 of file d_loop.c.
 {
     int i;
     // Disconnected from server?
     if (ticcmds == NULL && players_mask == NULL)
     {
         D_Disconnected();
         return;
     }
     for (i = 0; i < NET_MAXPLAYERS; ++i)
     {
         if (!drone && i == localplayer)
         {
             // This is us.  Don't overwrite it.
         }
         else
         {
             ticdata[recvtic % BACKUPTICS].cmds[i] = ticcmds[i];
             ticdata[recvtic % BACKUPTICS].ingame[i] = players_mask[i];
         }
     }
     ++recvtic;
 }
References BACKUPTICS, ticcmd_set_t::cmds, D_Disconnected(), drone, i, ticcmd_set_t::ingame, localplayer, NET_MAXPLAYERS, NULL, recvtic, and ticdata.
D_RegisterLoopCallbacks()
void D_RegisterLoopCallbacks (loop_interface_t * i)
Definition at line 823 of file d_loop.c.
 {
     loop_interface = i;
 }
References i, and loop_interface.
Referenced by D_CheckNetGame().
D_StartGameLoop()
void D_StartGameLoop (void)
Definition at line 305 of file d_loop.c.
 {
     lasttime = GetAdjustedTime() / ticdup;
 }
References GetAdjustedTime(), lasttime, and ticdup.
Referenced by D_DoomLoop().
D_StartNetGame()
void D_StartNetGame (net_gamesettings_t * settings, netgame_startup_callback_t callback)
Definition at line 340 of file d_loop.c.
 {
 #if ORIGCODE
     int i;
     offsetms = 0;
     recvtic = 0;
     settings->consoleplayer = 0;
     settings->num_players = 1;
     settings->player_classes[0] = player_class;
     // @category net
     //
     // Use new network client sync code rather than the classic
     // sync code. This is currently disabled by default because it
     // has some bugs.
     //
     if (M_CheckParm("-newsync") > 0)
         settings->new_sync = 1;
     else
         settings->new_sync = 0;
     // TODO: New sync code is not enabled by default because it's
     // currently broken.
     //if (M_CheckParm("-oldsync") > 0)
     //    settings->new_sync = 0;
     //else
     //    settings->new_sync = 1;
     // @category net
     // @arg <n>
     //
     // Send n extra tics in every packet as insurance against dropped
     // packets.
     //
     i = M_CheckParmWithArgs("-extratics", 1);
     if (i > 0)
         settings->extratics = atoi(myargv[i+1]);
     else
         settings->extratics = 1;
     // @category net
     // @arg <n>
     //
     // Reduce the resolution of the game by a factor of n, reducing
     // the amount of network bandwidth needed.
     //
     i = M_CheckParmWithArgs("-dup", 1);
     if (i > 0)
         settings->ticdup = atoi(myargv[i+1]);
     else
         settings->ticdup = 1;
     if (net_client_connected)
     {
         // Send our game settings and block until game start is received
         // from the server.
         NET_CL_StartGame(settings);
         BlockUntilStart(settings, callback);
         // Read the game settings that were received.
         NET_CL_GetSettings(settings);
     }
     if (drone)
     {
         settings->consoleplayer = 0;
     }
     // Set the local player and playeringame[] values.
     localplayer = settings->consoleplayer;
     for (i = 0; i < NET_MAXPLAYERS; ++i)
     {
         local_playeringame[i] = i < settings->num_players;
     }
     // Copy settings to global variables.
     ticdup = settings->ticdup;
     new_sync = settings->new_sync;
     // TODO: Message disabled until we fix new_sync.
     //if (!new_sync)
     //{
     //    printf("Syncing netgames like Vanilla Doom.\n");
     //}
 #else
     settings->consoleplayer = 0;
     settings->num_players = 1;
     settings->player_classes[0] = player_class;
     settings->new_sync = 0;
     settings->extratics = 1;
     settings->ticdup = 1;
     ticdup = settings->ticdup;
     new_sync = settings->new_sync;
 #endif
 }
References atoi(), callback, net_gamesettings_t::consoleplayer, drone, net_gamesettings_t::extratics, i, local_playeringame, localplayer, M_CheckParm(), M_CheckParmWithArgs(), myargv, NET_CL_GetSettings(), NET_CL_StartGame(), net_client_connected, NET_MAXPLAYERS, new_sync, net_gamesettings_t::new_sync, net_gamesettings_t::num_players, offsetms, player_class, net_gamesettings_t::player_classes, recvtic, ticdup, and net_gamesettings_t::ticdup.
Referenced by D_CheckNetGame().
GetAdjustedTime()
static int GetAdjustedTime (void) static
Definition at line 119 of file d_loop.c.
 {
     int time_ms;
     time_ms = I_GetTimeMS();
     if (new_sync)
     {
     // Use the adjustments from net_client.c only if we are
     // using the new sync mode.
         time_ms += (offsetms / FRACUNIT);
     }
     return (time_ms * TICRATE) / 1000;
 }
References FRACUNIT, I_GetTimeMS(), new_sync, offsetms, and TICRATE.
Referenced by D_StartGameLoop(), and NetUpdate().
GetLowTic()
static int GetLowTic (void) static
Definition at line 568 of file d_loop.c.
 {
     int lowtic;
     lowtic = maketic;
 #ifdef FEATURE_MULTIPLAYER
     if (net_client_connected)
     {
         if (drone || recvtic < lowtic)
         {
             lowtic = recvtic;
         }
     }
 #endif
     return lowtic;
 }
References drone, maketic, net_client_connected, and recvtic.
Referenced by TryRunTics().
NetUpdate()
void NetUpdate (void)
Definition at line 203 of file d_loop.c.
 {
     int nowtime;
     int newtics;
     int i;
     // If we are running with singletics (timing a demo), this
     // is all done separately.
     if (singletics)
         return;
 #ifdef FEATURE_MULTIPLAYER
     // Run network subsystems
     NET_CL_Run();
     NET_SV_Run();
 #endif
     // check time
     nowtime = GetAdjustedTime() / ticdup;
     newtics = nowtime - lasttime;
     lasttime = nowtime;
     if (skiptics <= newtics)
     {
         newtics -= skiptics;
         skiptics = 0;
     }
     else
     {
         skiptics -= newtics;
         newtics = 0;
     }
     // build new ticcmds for console player
     for (i=0 ; i<newtics ; i++)
     {
         if (!BuildNewTic())
         {
             break;
         }
     }
 }
References BuildNewTic(), GetAdjustedTime(), i, lasttime, NET_CL_Run(), NET_SV_Run(), singletics, skiptics, and ticdup.
Referenced by D_Display(), R_RenderPlayerView(), and TryRunTics().
OldNetSync()
static void OldNetSync (void) static
Definition at line 591 of file d_loop.c.
 {
     unsigned int i;
     int keyplayer = -1;
     frameon++;
     // ideally maketic should be 1 - 3 tics above lowtic
     // if we are consistantly slower, speed up time
     for (i=0 ; i<NET_MAXPLAYERS ; i++)
     {
         if (local_playeringame[i])
         {
             keyplayer = i;
             break;
         }
     }
     if (keyplayer < 0)
     {
         // If there are no players, we can never advance anyway
         return;
     }
     if (localplayer == keyplayer)
     {
         // the key player does not adapt
     }
     else
     {
         if (maketic <= recvtic)
         {
             lasttime--;
             // printf ("-");
         }
         frameskip[frameon & 3] = oldnettics > recvtic;
         oldnettics = maketic;
         if (frameskip[0] && frameskip[1] && frameskip[2] && frameskip[3])
         {
             skiptics = 1;
             // printf ("+");
         }
     }
 }
References frameon, frameskip, i, lasttime, local_playeringame, localplayer, maketic, NET_MAXPLAYERS, oldnettics, recvtic, and skiptics.
Referenced by TryRunTics().
PlayersInGame()
static boolean PlayersInGame (void) static
Definition at line 642 of file d_loop.c.
 {
     boolean result = false;
     unsigned int i;
     // If we are connected to a server, check if there are any players
     // in the game.
     if (net_client_connected)
     {
         for (i = 0; i < NET_MAXPLAYERS; ++i)
         {
             result = result || local_playeringame[i];
         }
     }
     // Whether single or multi-player, unless we are running as a drone,
     // we are in the game.
     if (!drone)
     {
         result = true;
     }
     return result;
 }
References drone, i, local_playeringame, net_client_connected, and NET_MAXPLAYERS.
Referenced by TryRunTics().
SinglePlayerClear()
static void SinglePlayerClear (ticcmd_set_t * set) static
Definition at line 689 of file d_loop.c.
 {
     unsigned int i;
     for (i = 0; i < NET_MAXPLAYERS; ++i)
     {
         if (i != localplayer)
         {
             set->ingame[i] = false;
         }
     }
 }
References i, ticcmd_set_t::ingame, localplayer, and NET_MAXPLAYERS.
Referenced by TryRunTics().
TicdupSquash()
static void TicdupSquash (ticcmd_set_t * set) static
Definition at line 672 of file d_loop.c.
 {
     ticcmd_t *cmd;
     unsigned int i;
     for (i = 0; i < NET_MAXPLAYERS ; ++i)
     {
         cmd = &set->cmds[i];
         cmd->chatchar = 0;
         if (cmd->buttons & BT_SPECIAL)
             cmd->buttons = 0;
     }
 }
References BT_SPECIAL, ticcmd_t::buttons, ticcmd_t::chatchar, ticcmd_set_t::cmds, i, and NET_MAXPLAYERS.
Referenced by TryRunTics().
TryRunTics()
void TryRunTics (void)
Definition at line 706 of file d_loop.c.
 {
     int i;
     int lowtic;
     int entertic;
     static int oldentertics;
     int realtics;
     int availabletics;
     int counts;
     // get real tics
     entertic = I_GetTime() / ticdup;
     realtics = entertic - oldentertics;
     oldentertics = entertic;
     // in singletics mode, run a single tic every time this function
     // is called.
     if (singletics)
     {
         BuildNewTic();
     }
     else
     {
         NetUpdate ();
     }
     lowtic = GetLowTic();
     availabletics = lowtic - gametic/ticdup;
     // decide how many tics to run
     if (new_sync)
     {
     counts = availabletics;
     }
     else
     {
         // decide how many tics to run
         if (realtics < availabletics-1)
             counts = realtics+1;
         else if (realtics < availabletics)
             counts = realtics;
         else
             counts = availabletics;
         if (counts < 1)
             counts = 1;
         if (net_client_connected)
         {
             OldNetSync();
         }
     }
     if (counts < 1)
     counts = 1;
     // wait for new tics if needed
     while (!PlayersInGame() || lowtic < gametic/ticdup + counts)
     {
     NetUpdate ();
         lowtic = GetLowTic();
     if (lowtic < gametic/ticdup)
         I_Error ("TryRunTics: lowtic < gametic");
         // Don't stay in this loop forever.  The menu is still running,
         // so return to update the screen
     if (I_GetTime() / ticdup - entertic > 0)
     {
         return;
     }
         I_Sleep(1);
     }
     // run the count * ticdup dics
     while (counts--)
     {
         ticcmd_set_t *set;
         if (!PlayersInGame())
         {
             return;
         }
         set = &ticdata[(gametic / ticdup) % BACKUPTICS];
         if (!net_client_connected)
         {
             SinglePlayerClear(set);
         }
     for (i=0 ; i<ticdup ; i++)
     {
             if (gametic/ticdup > lowtic)
                 I_Error ("gametic>lowtic");
             memcpy(local_playeringame, set->ingame, sizeof(local_playeringame));
             loop_interface->RunTic(set->cmds, set->ingame);
         gametic++;
         // modify command for duplicated tics
             TicdupSquash(set);
     }
     NetUpdate ();   // check for new console commands
     }
 }
References BACKUPTICS, BuildNewTic(), ticcmd_set_t::cmds, gametic, GetLowTic(), i, I_Error(), I_GetTime(), I_Sleep(), ticcmd_set_t::ingame, local_playeringame, loop_interface, memcpy(), net_client_connected, NetUpdate(), new_sync, OldNetSync(), PlayersInGame(), loop_interface_t::RunTic, SinglePlayerClear(), singletics, ticdata, ticdup, and TicdupSquash().
Referenced by D_DoomLoop(), and doomgeneric_Tick().
Variable Documentation
frameon
int frameon static
Definition at line 587 of file d_loop.c.
Referenced by OldNetSync().
frameskip
int frameskip[4] static
Definition at line 588 of file d_loop.c.
Referenced by OldNetSync().
gametic
int gametic
Definition at line 72 of file d_loop.c.
Referenced by A_Tracer(), BuildNewTic(), D_Display(), G_CheckDemoStatus(), G_DoLoadLevel(), G_Ticker(), M_QuitResponse(), M_SelectEndMessage(), and TryRunTics().
lasttime
int lasttime
Definition at line 201 of file d_loop.c.
Referenced by D_StartGameLoop(), NetUpdate(), and OldNetSync().
local_playeringame
boolean local_playeringame[NET_MAXPLAYERS] static
Definition at line 108 of file d_loop.c.
Referenced by D_StartNetGame(), OldNetSync(), PlayersInGame(), and TryRunTics().
localplayer
int localplayer static
Definition at line 81 of file d_loop.c.
Referenced by BuildNewTic(), D_ReceiveTic(), D_StartNetGame(), OldNetSync(), and SinglePlayerClear().
loop_interface
loop_interface_t* loop_interface = NULL static
Definition at line 102 of file d_loop.c.
Referenced by BuildNewTic(), D_RegisterLoopCallbacks(), and TryRunTics().
maketic
int maketic static
Definition at line 64 of file d_loop.c.
Referenced by BuildNewTic(), G_BuildTiccmd(), GetLowTic(), and OldNetSync().
new_sync
boolean new_sync = true static
Definition at line 98 of file d_loop.c.
Referenced by BuildNewTic(), D_StartNetGame(), GetAdjustedTime(), and TryRunTics().
offsetms
fixed_t offsetms
Definition at line 94 of file d_loop.c.
Referenced by D_StartNetGame(), and GetAdjustedTime().
oldnettics
int oldnettics static
Definition at line 589 of file d_loop.c.
Referenced by OldNetSync().
player_class
int player_class static
Definition at line 114 of file d_loop.c.
Referenced by D_InitNetGame(), and D_StartNetGame().
recvtic
int recvtic static
Definition at line 68 of file d_loop.c.
Referenced by D_ReceiveTic(), D_StartNetGame(), GetLowTic(), and OldNetSync().
singletics
boolean singletics = false
Definition at line 77 of file d_loop.c.
Referenced by G_TimeDemo(), NetUpdate(), and TryRunTics().
skiptics
int skiptics = 0 static
Definition at line 85 of file d_loop.c.
Referenced by NetUpdate(), and OldNetSync().
ticdata
ticcmd_set_t ticdata[BACKUPTICS] static
Definition at line 60 of file d_loop.c.
Referenced by BuildNewTic(), D_ReceiveTic(), and TryRunTics().
ticdup
int ticdup
Definition at line 90 of file d_loop.c.
Referenced by BuildNewTic(), D_StartGameLoop(), D_StartNetGame(), G_BuildTiccmd(), G_Ticker(), NetUpdate(), and TryRunTics().