Fennix: Userspace/musl/src/include/crypt.h File Reference
crypt.h File Reference
#include "../../include/crypt.h"
#include <features.h>
Functions
hidden char * __crypt_r (const char *, const char *, struct crypt_data *)
hidden char * __crypt_des (const char *, const char *, char *)
hidden char * __crypt_md5 (const char *, const char *, char *)
hidden char * __crypt_blowfish (const char *, const char *, char *)
hidden char * __crypt_sha256 (const char *, const char *, char *)
hidden char * __crypt_sha512 (const char *, const char *, char *)
Function Documentation
__crypt_blowfish()
hidden char* __crypt_blowfish (const char * key, const char * setting, char * output)
Definition at line 748 of file crypt_blowfish.c.
 {
     const char *test_key = "8b \xd0\xc1\xd2\xcf\xcc\xd8";
     const char *test_setting = "$2a$00$abcdefghijklmnopqrstuu";
     static const char test_hashes[2][34] = {
         "i1D709vfamulimlGcq0qq3UvuUasvEa\0\x55", /* 'a', 'b', 'y' */
         "VUrPmXD6q/nVSSp7pNDhCR9071IfIRe\0\x55", /* 'x' */
     };
     const char *test_hash = test_hashes[0];
     char *retval;
     const char *p;
     int ok;
     struct {
         char s[7 + 22 + 1];
         char o[7 + 22 + 31 + 1 + 1 + 1];
     } buf;
 /* Hash the supplied password */
     retval = BF_crypt(key, setting, output, 16);
 /*
  * Do a quick self-test.  It is important that we make both calls to BF_crypt()
  * from the same scope such that they likely use the same stack locations,
  * which makes the second call overwrite the first call's sensitive data on the
  * stack and makes it more likely that any alignment related issues would be
  * detected by the self-test.
  */
     memcpy(buf.s, test_setting, sizeof(buf.s));
     if (retval) {
         unsigned int flags = flags_by_subtype[setting[2] - 'a'];
         test_hash = test_hashes[flags & 1];
         buf.s[2] = setting[2];
     }
     memset(buf.o, 0x55, sizeof(buf.o));
     buf.o[sizeof(buf.o) - 1] = 0;
     p = BF_crypt(test_key, buf.s, buf.o, 1);
     ok = (p == buf.o &&
         !memcmp(p, buf.s, 7 + 22) &&
         !memcmp(p + (7 + 22),
         test_hash,
         31 + 1 + 1 + 1));
     {
         const char *k = "\xff\xa3" "34" "\xff\xff\xff\xa3" "345";
         BF_key ae, ai, ye, yi;
         BF_set_key(k, ae, ai, 2); /* $2a$ */
         BF_set_key(k, ye, yi, 4); /* $2y$ */
         ai[0] ^= 0x10000; /* undo the safety (for comparison) */
         ok = ok && ai[0] == 0xdb9c59bc && ye[17] == 0x33343500 &&
             !memcmp(ae, ye, sizeof(ae)) &&
             !memcmp(ai, yi, sizeof(ai));
     }
     if (ok && retval)
         return retval;
     return "*";
 }
References BF_crypt(), BF_set_key(), buf, flags, flags_by_subtype, k, memcmp(), memcpy, memset, ok, output, p, retval, and s.
Referenced by __crypt_r().
__crypt_des()
hidden char* __crypt_des (const char * key, const char * setting, char * output)
Definition at line 984 of file crypt_des.c.
 {
     const char *test_key = "\x80\xff\x80\x01 "
         "\x7f\x81\x80\x80\x0d\x0a\xff\x7f \x81 test";
     const char *test_setting = "_0.../9Zz";
     const char *test_hash = "_0.../9ZzX7iSJNd21sU";
     char test_buf[21];
     char *retval;
     const char *p;
     if (*setting != _PASSWORD_EFMT1) {
         test_setting = "\x80x";
         test_hash = "\x80x22/wK52ZKGA";
     }
     /*
      * Hash the supplied password.
      */
     retval = _crypt_extended_r_uut(key, setting, output);
     /*
      * Perform a quick self-test.  It is important that we make both calls
      * to _crypt_extended_r_uut() from the same scope such that they likely
      * use the same stack locations, which makes the second call overwrite
      * the first call's sensitive data on the stack and makes it more
      * likely that any alignment related issues would be detected.
      */
     p = _crypt_extended_r_uut(test_key, test_setting, test_buf);
     if (p && !strcmp(p, test_hash) && retval)
         return retval;
     return (setting[0]=='*') ? "x" : "*";
 }
References _crypt_extended_r_uut(), _PASSWORD_EFMT1, output, p, retval, and strcmp.
Referenced by __crypt_r().
__crypt_md5()
hidden char* __crypt_md5 (const char * key, const char * setting, char * output)
Definition at line 271 of file crypt_md5.c.
 {
     static const char testkey[] = "Xy01@#\x01\x02\x80\x7f\xff\r\n\x81\t !";
     static const char testsetting[] = "$1$abcd0123$";
     static const char testhash[] = "$1$abcd0123$9Qcg8DyviekV3tDGMZynJ1";
     char testbuf[64];
     char *p, *q;
     p = md5crypt(key, setting, output);
     /* self test and stack cleanup */
     q = md5crypt(testkey, testsetting, testbuf);
     if (!p || q != testbuf || memcmp(testbuf, testhash, sizeof testhash))
         return "*";
     return p;
 }
References md5crypt(), memcmp(), output, and p.
Referenced by __crypt_r().
__crypt_r()
hidden char* __crypt_r (const char * key, const char * salt, struct crypt_data * data)
Definition at line 3 of file crypt_r.c.
 {
     /* Per the crypt_r API, the caller has provided a pointer to
      * struct crypt_data; however, this implementation does not
      * use the structure to store any internal state, and treats
      * it purely as a char buffer for storing the result. */
     char *output = (char *)data;
     if (salt[0] == '$' && salt[1] && salt[2]) {
         if (salt[1] == '1' && salt[2] == '$')
             return __crypt_md5(key, salt, output);
         if (salt[1] == '2' && salt[3] == '$')
             return __crypt_blowfish(key, salt, output);
         if (salt[1] == '5' && salt[2] == '$')
             return __crypt_sha256(key, salt, output);
         if (salt[1] == '6' && salt[2] == '$')
             return __crypt_sha512(key, salt, output);
     }
     return __crypt_des(key, salt, output);
 }
References __crypt_blowfish(), __crypt_des(), __crypt_md5(), __crypt_sha256(), __crypt_sha512(), and output.
Referenced by crypt().
__crypt_sha256()
hidden char* __crypt_sha256 (const char * key, const char * setting, char * output)
Definition at line 308 of file crypt_sha256.c.
 {
     static const char testkey[] = "Xy01@#\x01\x02\x80\x7f\xff\r\n\x81\t !";
     static const char testsetting[] = "$5$rounds=1234$abc0123456789$";
     static const char testhash[] = "$5$rounds=1234$abc0123456789$3VfDjPt05VHFn47C/ojFZ6KRPYrOjj1lLbH.dkF3bZ6";
     char testbuf[128];
     char *p, *q;
     p = sha256crypt(key, setting, output);
     /* self test and stack cleanup */
     q = sha256crypt(testkey, testsetting, testbuf);
     if (!p || q != testbuf || memcmp(testbuf, testhash, sizeof testhash))
         return "*";
     return p;
 }
References memcmp(), output, p, and sha256crypt().
Referenced by __crypt_r().
__crypt_sha512()
hidden char* __crypt_sha512 (const char * key, const char * setting, char * output)
Definition at line 357 of file crypt_sha512.c.
 {
     static const char testkey[] = "Xy01@#\x01\x02\x80\x7f\xff\r\n\x81\t !";
     static const char testsetting[] = "$6$rounds=1234$abc0123456789$";
     static const char testhash[] = "$6$rounds=1234$abc0123456789$BCpt8zLrc/RcyuXmCDOE1ALqMXB2MH6n1g891HhFj8.w7LxGv.FTkqq6Vxc/km3Y0jE0j24jY5PIv/oOu6reg1";
     char testbuf[128];
     char *p, *q;
     p = sha512crypt(key, setting, output);
     /* self test and stack cleanup */
     q = sha512crypt(testkey, testsetting, testbuf);
     if (!p || q != testbuf || memcmp(testbuf, testhash, sizeof testhash))
         return "*";
     return p;
 }
References memcmp(), output, p, and sha512crypt().
Referenced by __crypt_r().