Fennix: Userspace/apps/base/busybox/networking/tls_aes.c File Reference
tls_aes.c File Reference
#include "tls.h"
Macros
#define ASTATE(col, row) astate[(col)*4 + (row)]
Functions
static uint32_t Subword (uint32_t x)
static int KeyExpansion (uint32_t *RoundKey, const void *key, unsigned key_len)
static void AddRoundKey (unsigned astate[16], const uint32_t *RoundKeys)
static void SubBytes (unsigned astate[16])
static void ShiftRows (unsigned astate[16])
static void MixColumns (unsigned astate[16])
static void InvSubBytes (unsigned astate[16])
static void InvShiftRows (unsigned astate[16])
static ALWAYS_INLINE unsigned Multiply (unsigned x)
static void InvMixColumns (unsigned astate[16])
static void aes_encrypt_1 (struct tls_aes *aes, unsigned astate[16])
void FAST_FUNC aes_setkey (struct tls_aes *aes, const void *key, unsigned key_len)
void FAST_FUNC aes_encrypt_one_block (struct tls_aes *aes, const void *data, void *dst)
void FAST_FUNC aes_cbc_encrypt (struct tls_aes *aes, void *iv, const void *data, size_t len, void *dst)
static void aes_decrypt_1 (struct tls_aes *aes, unsigned astate[16])
void FAST_FUNC aes_cbc_decrypt (struct tls_aes *aes, void *iv, const void *data, size_t len, void *dst)
Variables
static const uint8_t sbox []
static const uint8_t rsbox []
Macro Definition Documentation
ASTATE
#define ASTATE (col, row) astate[(col)*4 + (row)]
Definition at line 206 of file tls_aes.c.
Function Documentation
AddRoundKey()
static void AddRoundKey (unsigned astate[16], const uint32_t * RoundKeys) static
Definition at line 179 of file tls_aes.c.
 {
     int i;
     for (i = 0; i < 16; i += 4) {
         uint32_t n = *RoundKeys++;
         astate[i + 0] ^= (n >> 24);
         astate[i + 1] ^= (n >> 16) & 255;
         astate[i + 2] ^= (n >> 8) & 255;
         astate[i + 3] ^= n & 255;
     }
 }
References i, and n.
Referenced by aes_decrypt_1(), and aes_encrypt_1().
aes_cbc_decrypt()
void FAST_FUNC aes_cbc_decrypt (struct tls_aes * aes, void * iv, const void * data, size_t len, void * dst)
Definition at line 431 of file tls_aes.c.
 {
     uint8_t iv2[16];
     uint8_t iv3[16];
     uint8_t *ivbuf;
     uint8_t *ivnext;
     const uint8_t *ct = data;
     uint8_t *pt = dst;
     ivbuf = memcpy(iv2, iv, 16);
     while (len) {
         ivnext = (ivbuf==iv2) ? iv3 : iv2;
         {
             /* almost aes_decrypt_one_block(rounds, RoundKey, ct, pt)
              * but xor'ing of ivbuf is combined with astate[] -> plaintext[]
              */
             int i;
             unsigned astate[16];
             for (i = 0; i < 16; i++)
                 ivnext[i] = astate[i] = ct[i];
             aes_decrypt_1(aes, astate);
             for (i = 0; i < 16; i++)
                 pt[i] = astate[i] ^ ivbuf[i];
         }
         ivbuf = ivnext;
         ct += 16;
         pt += 16;
         len -= 16;
     }
 }
References aes_decrypt_1(), dst, i, len, and memcpy.
Referenced by tls_xread_record().
aes_cbc_encrypt()
void FAST_FUNC aes_cbc_encrypt (struct tls_aes * aes, void * iv, const void * data, size_t len, void * dst)
Definition at line 366 of file tls_aes.c.
 {
     uint8_t iv2[16];
     const uint8_t *pt = data;
     uint8_t *ct = dst;
     memcpy(iv2, iv, 16);
     while (len > 0) {
         {
             /* almost aes_encrypt_one_block(rounds, RoundKey, pt, ct);
              * but xor'ing of IV with plaintext[] is combined
              * with plaintext[] -> astate[]
              */
             int i;
             unsigned astate[16];
             for (i = 0; i < 16; i++)
                 astate[i] = pt[i] ^ iv2[i];
             aes_encrypt_1(aes, astate);
             for (i = 0; i < 16; i++)
                 iv2[i] = ct[i] = astate[i];
         }
         ct += 16;
         pt += 16;
         len -= 16;
     }
 }
References aes_encrypt_1(), dst, i, len, and memcpy.
Referenced by xwrite_encrypted_and_hmac_signed().
aes_decrypt_1()
static void aes_decrypt_1 (struct tls_aes * aes, unsigned astate[16]) static
Definition at line 394 of file tls_aes.c.
 {
     unsigned rounds = aes->rounds;
     const uint32_t *RoundKey = aes->key;
     RoundKey += rounds * 4;
     AddRoundKey(astate, RoundKey);
     for (;;) {
         InvShiftRows(astate);
         InvSubBytes(astate);
         RoundKey -= 4;
         AddRoundKey(astate, RoundKey);
         if (--rounds == 0)
             break;
         InvMixColumns(astate);
     }
 }
References AddRoundKey(), InvMixColumns(), InvShiftRows(), InvSubBytes(), tls_aes::key, and tls_aes::rounds.
Referenced by aes_cbc_decrypt().
aes_encrypt_1()
static void aes_encrypt_1 (struct tls_aes * aes, unsigned astate[16]) static
Definition at line 329 of file tls_aes.c.
 {
     unsigned rounds = aes->rounds;
     const uint32_t *RoundKey = aes->key;
     for (;;) {
         AddRoundKey(astate, RoundKey);
         RoundKey += 4;
         SubBytes(astate);
         ShiftRows(astate);
         if (--rounds == 0)
             break;
         MixColumns(astate);
     }
     AddRoundKey(astate, RoundKey);
 }
References AddRoundKey(), tls_aes::key, MixColumns(), tls_aes::rounds, ShiftRows(), and SubBytes().
Referenced by aes_cbc_encrypt(), and aes_encrypt_one_block().
aes_encrypt_one_block()
void FAST_FUNC aes_encrypt_one_block (struct tls_aes * aes, const void * data, void * dst)
Definition at line 351 of file tls_aes.c.
 {
     unsigned astate[16];
     unsigned i;
     const uint8_t *pt = data;
     uint8_t *ct = dst;
     for (i = 0; i < 16; i++)
         astate[i] = pt[i];
     aes_encrypt_1(aes, astate);
     for (i = 0; i < 16; i++)
         ct[i] = astate[i];
 }
References aes_encrypt_1(), dst, and i.
Referenced by send_client_key_exchange(), tls_aesgcm_decrypt(), and xwrite_encrypted_aesgcm().
aes_setkey()
void FAST_FUNC aes_setkey (struct tls_aes * aes, const void * key, unsigned key_len)
Definition at line 346 of file tls_aes.c.
 {
     aes->rounds = KeyExpansion(aes->key, key, key_len);
 }
References tls_aes::key, KeyExpansion(), and tls_aes::rounds.
Referenced by send_client_key_exchange().
InvMixColumns()
static void InvMixColumns (unsigned astate[16]) static
Definition at line 302 of file tls_aes.c.
 {
     int i;
     for (i = 0; i < 16; i += 4) {
         unsigned a, b, c, d;
         unsigned x, y, z, t;
         a = astate[i + 0];
         b = astate[i + 1];
         c = astate[i + 2];
         d = astate[i + 3];
         x = (a << 1) ^ (a << 2) ^ (a << 3) ^ b ^ (b << 1) ^ (b << 3)
         /***/ ^ c ^ (c << 2) ^ (c << 3) ^ d ^ (d << 3);
         astate[i + 0] = Multiply(x);
         y = a ^ (a << 3) ^ (b << 1) ^ (b << 2) ^ (b << 3)
         /***/ ^ c ^ (c << 1) ^ (c << 3) ^ d ^ (d << 2) ^ (d << 3);
         astate[i + 1] = Multiply(y);
         z = a ^ (a << 2) ^ (a << 3) ^ b ^ (b << 3)
         /***/ ^ (c << 1) ^ (c << 2) ^ (c << 3) ^ d ^ (d << 1) ^ (d << 3);
         astate[i + 2] = Multiply(z);
         t = a ^ (a << 1) ^ (a << 3) ^ b ^ (b << 2) ^ (b << 3)
         /***/ ^ c ^ (c << 3) ^ (d << 1) ^ (d << 2) ^ (d << 3);
         astate[i + 3] = Multiply(t);
     }
 }
References c, i, Multiply(), t, x, and y.
Referenced by aes_decrypt_1().
InvShiftRows()
static void InvShiftRows (unsigned astate[16]) static
Definition at line 268 of file tls_aes.c.
 {
     unsigned v;
     // Rotate first row 1 columns to right
     v = ASTATE(3,1);
     ASTATE(3,1) = ASTATE(2,1);
     ASTATE(2,1) = ASTATE(1,1);
     ASTATE(1,1) = ASTATE(0,1);
     ASTATE(0,1) = v;
     // Rotate second row 2 columns to right
     v = ASTATE(0,2); ASTATE(0,2) = ASTATE(2,2); ASTATE(2,2) = v;
     v = ASTATE(1,2); ASTATE(1,2) = ASTATE(3,2); ASTATE(3,2) = v;
     // Rotate third row 3 columns to right
     v = ASTATE(0,3);
     ASTATE(0,3) = ASTATE(1,3);
     ASTATE(1,3) = ASTATE(2,3);
     ASTATE(2,3) = ASTATE(3,3);
     ASTATE(3,3) = v;
 }
References ASTATE.
Referenced by aes_decrypt_1().
InvSubBytes()
static void InvSubBytes (unsigned astate[16]) static
Definition at line 260 of file tls_aes.c.
 {
     int i;
     for (i = 0; i < 16; i++)
         astate[i] = rsbox[astate[i]];
 }
References i, and rsbox.
Referenced by aes_decrypt_1().
KeyExpansion()
static int KeyExpansion (uint32_t * RoundKey, const void * key, unsigned key_len) static
Definition at line 128 of file tls_aes.c.
 {
     // The round constant word array, Rcon[i], contains the values given by
     // x to th e power (i-1) being powers of x (x is denoted as {02}) in the field GF(2^8).
     // Note that i starts at 2, not 0.
     static const uint8_t Rcon[] ALIGN1 = {
         0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x1b, 0x36
     //..... 0x6c, 0xd8, 0xab, 0x4d, 0x9a, 0x2f, 0x5e, 0xbc, 0x63, 0xc6,...
     // but aes256 only uses values up to 0x36
     };
     int rounds, words_key, words_RoundKey;
     int i, j, k;
     // key_len 16: aes128, rounds 10, words_key 4, words_RoundKey 44
     // key_len 24: aes192, rounds 12, words_key 6, words_RoundKey 52
     // key_len 32: aes256, rounds 14, words_key 8, words_RoundKey 60
     words_key = key_len / 4;
     rounds = 6 + (key_len / 4);
     words_RoundKey = 28 + key_len;
     // The first round key is the key itself.
     for (i = 0; i < words_key; i++)
         RoundKey[i] = get_unaligned_be32((uint32_t*)key + i);
     // i == words_key now
     // All other round keys are found from the previous round keys.
     j = k = 0;
     for (; i < words_RoundKey; i++) {
         uint32_t tempa;
         tempa = RoundKey[i - 1];
         if (j == 0) {
             // RotWord(): rotates the 4 bytes in a word to the left once.
             tempa = (tempa << 8) | (tempa >> 24);
             tempa = Subword(tempa);
             tempa ^= (uint32_t)Rcon[k] << 24;
         } else if (words_key > 6 && j == 4) {
             tempa = Subword(tempa);
         }
         RoundKey[i] = RoundKey[i - words_key] ^ tempa;
         j++;
         if (j == words_key) {
             j = 0;
             k++;
         }
     }
     return rounds;
 }
References ALIGN1, get_unaligned_be32, i, j, k, and Subword().
Referenced by aes_setkey().
MixColumns()
static void MixColumns (unsigned astate[16]) static
Definition at line 235 of file tls_aes.c.
 {
     int i;
     for (i = 0; i < 16; i += 4) {
         unsigned a, b, c, d;
         unsigned x, y, z, t;
         a = astate[i + 0];
         b = astate[i + 1];
         c = astate[i + 2];
         d = astate[i + 3];
         x = (a << 1) ^ b ^ (b << 1) ^ c ^ d;
         y = a ^ (b << 1) ^ c ^ (c << 1) ^ d;
         z = a ^ b ^ (c << 1) ^ d ^ (d << 1);
         t = a ^ (a << 1) ^ b ^ c ^ (d << 1);
         astate[i + 0] = x ^ ((-(int)(x >> 8)) & 0x11b);
         astate[i + 1] = y ^ ((-(int)(y >> 8)) & 0x11b);
         astate[i + 2] = z ^ ((-(int)(z >> 8)) & 0x11b);
         astate[i + 3] = t ^ ((-(int)(t >> 8)) & 0x11b);
     }
 }
References c, i, t, x, and y.
Referenced by aes_encrypt_1().
Multiply()
static ALWAYS_INLINE unsigned Multiply (unsigned x) static
Definition at line 291 of file tls_aes.c.
 {
     unsigned y;
     y = x >> 8;
     return (x ^ y ^ (y << 1) ^ (y << 3) ^ (y << 4)) & 255;
 }
References x, and y.
Referenced by InvMixColumns().
ShiftRows()
static void ShiftRows (unsigned astate[16]) static
Definition at line 211 of file tls_aes.c.
 {
     unsigned v;
     // Rotate first row 1 columns to left
     v = ASTATE(0,1);
     ASTATE(0,1) = ASTATE(1,1);
     ASTATE(1,1) = ASTATE(2,1);
     ASTATE(2,1) = ASTATE(3,1);
     ASTATE(3,1) = v;
     // Rotate second row 2 columns to left
     v = ASTATE(0,2); ASTATE(0,2) = ASTATE(2,2); ASTATE(2,2) = v;
     v = ASTATE(1,2); ASTATE(1,2) = ASTATE(3,2); ASTATE(3,2) = v;
     // Rotate third row 3 columns to left
     v = ASTATE(3,3);
     ASTATE(3,3) = ASTATE(2,3);
     ASTATE(2,3) = ASTATE(1,3);
     ASTATE(1,3) = ASTATE(0,3);
     ASTATE(0,3) = v;
 }
References ASTATE.
Referenced by aes_encrypt_1().
SubBytes()
static void SubBytes (unsigned astate[16]) static
Definition at line 194 of file tls_aes.c.
 {
     int i;
     for (i = 0; i < 16; i++)
         astate[i] = sbox[astate[i]];
 }
References i, and sbox.
Referenced by aes_encrypt_1().
Subword()
static uint32_t Subword (uint32_t x) static
Definition at line 118 of file tls_aes.c.
 {
     return (sbox[(x >> 24)      ] << 24)
     |      (sbox[(x >> 16) & 255] << 16)
     |      (sbox[(x >> 8 ) & 255] << 8 )
     |      (sbox[(x      ) & 255]      );
 }
References sbox, and x.
Referenced by KeyExpansion().
Variable Documentation
rsbox
const uint8_t rsbox[] static
Definition at line 81 of file tls_aes.c.
Referenced by InvSubBytes().
sbox
const uint8_t sbox[] static
Definition at line 46 of file tls_aes.c.
Referenced by const_des_init(), SubBytes(), and Subword().