Fennix: Userspace/apps/base/busybox/modutils/lsmod.c File Reference
lsmod.c File Reference
#include "libbb.h"
#include "unicode.h"
Functions
static ALWAYS_INLINE void check_tainted (void)
int lsmod_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int lsmod_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Function Documentation
check_tainted()
static ALWAYS_INLINE void check_tainted (void) static
Definition at line 68 of file lsmod.c.
 {
     putchar('\n');
 }
References putchar.
Referenced by lsmod_main().
lsmod_main() [1/2]
int lsmod_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 75 of file lsmod.c.
 {
 #if ENABLE_FEATURE_LSMOD_PRETTY_2_6_OUTPUT
     char *token[4];
     parser_t *parser = config_open("/proc/modules");
     init_unicode();
     printf("%-24sSize  Used by", "Module");
     check_tainted();
     if (ENABLE_FEATURE_2_4_MODULES
      && get_linux_version_code() < KERNEL_VERSION(2,6,0)
     ) {
         while (config_read(parser, token, 4, 3, "# \t", PARSE_NORMAL)) {
             if (token[3] != NULL && token[3][0] == '[') {
                 token[3]++;
                 token[3][strlen(token[3])-1] = '\0';
             } else
                 token[3] = (char *) "";
 # if ENABLE_UNICODE_SUPPORT
             {
                 uni_stat_t uni_stat;
                 char *uni_name = unicode_conv_to_printable(&uni_stat, token[0]);
                 unsigned pad_len = (uni_stat.unicode_width > 19) ? 0 : 19 - uni_stat.unicode_width;
                 printf("%s%*s %8s %2s %s\n", uni_name, pad_len, "", token[1], token[2], token[3]);
                 free(uni_name);
             }
 # else
             printf("%-19s %8s %2s %s\n", token[0], token[1], token[2], token[3]);
 # endif
         }
     } else {
         while (config_read(parser, token, 4, 4, "# \t", PARSE_NORMAL & ~PARSE_GREEDY)) {
             // N.B. token[3] is either '-' (module is not used by others)
             // or comma-separated list ended by comma
             // so trimming the trailing char is just what we need!
             if (token[3][0])
                 token[3][strlen(token[3]) - 1] = '\0';
 # if ENABLE_UNICODE_SUPPORT
             {
                 uni_stat_t uni_stat;
                 char *uni_name = unicode_conv_to_printable(&uni_stat, token[0]);
                 unsigned pad_len = (uni_stat.unicode_width > 19) ? 0 : 19 - uni_stat.unicode_width;
                 printf("%s%*s %8s %2s %s\n", uni_name, pad_len, "", token[1], token[2], token[3]);
                 free(uni_name);
             }
 # else
             printf("%-19s %8s %2s %s\n", token[0], token[1], token[2], token[3]);
 # endif
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         config_close(parser);
 #else
     check_tainted();
     xprint_and_close_file(xfopen_for_read("/proc/modules"));
 #endif
     return EXIT_SUCCESS;
 }
References check_tainted(), config_close(), config_open(), config_read, EXIT_SUCCESS, free, get_linux_version_code(), init_unicode, KERNEL_VERSION, NULL, PARSE_GREEDY, PARSE_NORMAL, parser, printf, strlen(), unicode_conv_to_printable(), uni_stat_t::unicode_width, xfopen_for_read(), and xprint_and_close_file().
lsmod_main() [2/2]
int lsmod_main (int argc, char ** argv)