Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/hu_stuff.h File Reference
hu_stuff.h File Reference
#include "d_event.h"
Macros
#define HU_FONTSTART '!'
#define HU_FONTEND '_'
#define HU_FONTSIZE (HU_FONTEND - HU_FONTSTART + 1)
#define HU_BROADCAST 5
#define HU_MSGX 0
#define HU_MSGY 0
#define HU_MSGWIDTH 64
#define HU_MSGHEIGHT 1
#define HU_MSGTIMEOUT (4*TICRATE)
Functions
void HU_Init (void)
void HU_Start (void)
boolean HU_Responder (event_t *ev)
void HU_Ticker (void)
void HU_Drawer (void)
char HU_dequeueChatChar (void)
void HU_Erase (void)
Variables
char * chat_macros [10]
Macro Definition Documentation
HU_BROADCAST
#define HU_BROADCAST 5
Definition at line 33 of file hu_stuff.h.
HU_FONTEND
#define HU_FONTEND '_'
Definition at line 28 of file hu_stuff.h.
HU_FONTSIZE
#define HU_FONTSIZE (HU_FONTEND - HU_FONTSTART + 1)
Definition at line 31 of file hu_stuff.h.
HU_FONTSTART
#define HU_FONTSTART '!'
Definition at line 27 of file hu_stuff.h.
HU_MSGHEIGHT
#define HU_MSGHEIGHT 1
Definition at line 38 of file hu_stuff.h.
HU_MSGTIMEOUT
#define HU_MSGTIMEOUT (4*TICRATE)
Definition at line 40 of file hu_stuff.h.
HU_MSGWIDTH
#define HU_MSGWIDTH 64
Definition at line 37 of file hu_stuff.h.
HU_MSGX
#define HU_MSGX 0
Definition at line 35 of file hu_stuff.h.
HU_MSGY
#define HU_MSGY 0
Definition at line 36 of file hu_stuff.h.
Function Documentation
HU_dequeueChatChar()
char HU_dequeueChatChar (void)
Definition at line 495 of file hu_stuff.c.
 {
     char c;
     if (head != tail)
     {
     c = chatchars[tail];
     tail = (tail + 1) & (QUEUESIZE-1);
     }
     else
     {
     c = 0;
     }
     return c;
 }
References c, chatchars, head, QUEUESIZE, and tail.
Referenced by G_BuildTiccmd().
HU_Drawer()
void HU_Drawer (void)
Definition at line 383 of file hu_stuff.c.
 {
     HUlib_drawSText(&w_message);
     HUlib_drawIText(&w_chat);
     if (automapactive)
     HUlib_drawTextLine(&w_title, false);
 }
References automapactive, HUlib_drawIText(), HUlib_drawSText(), HUlib_drawTextLine(), w_chat, w_message, and w_title.
Referenced by D_Display().
HU_Erase()
void HU_Erase (void)
Definition at line 393 of file hu_stuff.c.
 {
     HUlib_eraseSText(&w_message);
     HUlib_eraseIText(&w_chat);
     HUlib_eraseTextLine(&w_title);
 }
References HUlib_eraseIText(), HUlib_eraseSText(), HUlib_eraseTextLine(), w_chat, w_message, and w_title.
Referenced by D_Display().
HU_Init()
void HU_Init (void)
Definition at line 286 of file hu_stuff.c.
 {
     int     i;
     int     j;
     char    buffer[9];
     // load the heads-up font
     j = HU_FONTSTART;
     for (i=0;i<HU_FONTSIZE;i++)
     {
     DEH_snprintf(buffer, 9, "STCFN%.3d", j++);
     hu_font[i] = (patch_t *) W_CacheLumpName(buffer, PU_STATIC);
     }
 }
References DEH_snprintf, hu_font, HU_FONTSIZE, HU_FONTSTART, i, j, PU_STATIC, and W_CacheLumpName().
Referenced by D_DoomMain().
HU_Responder()
boolean HU_Responder (event_t * ev)
Definition at line 512 of file hu_stuff.c.
 {
     static char     lastmessage[HU_MAXLINELENGTH+1];
     char*       macromessage;
     boolean     eatkey = false;
     static boolean  altdown = false;
     unsigned char   c;
     int         i;
     int         numplayers;
     static int      num_nobrainers = 0;
     numplayers = 0;
     for (i=0 ; i<MAXPLAYERS ; i++)
     numplayers += playeringame[i];
     if (ev->data1 == KEY_RSHIFT)
     {
     return false;
     }
     else if (ev->data1 == KEY_RALT || ev->data1 == KEY_LALT)
     {
     altdown = ev->type == ev_keydown;
     return false;
     }
     if (ev->type != ev_keydown)
     return false;
     if (!chat_on)
     {
     if (ev->data1 == key_message_refresh)
     {
         message_on = true;
         message_counter = HU_MSGTIMEOUT;
         eatkey = true;
     }
     else if (netgame && ev->data2 == key_multi_msg)
     {
         eatkey = chat_on = true;
         HUlib_resetIText(&w_chat);
         HU_queueChatChar(HU_BROADCAST);
     }
     else if (netgame && numplayers > 2)
     {
         for (i=0; i<MAXPLAYERS ; i++)
         {
         if (ev->data2 == key_multi_msgplayer[i])
         {
             if (playeringame[i] && i!=consoleplayer)
             {
             eatkey = chat_on = true;
             HUlib_resetIText(&w_chat);
             HU_queueChatChar(i+1);
             break;
             }
             else if (i == consoleplayer)
             {
             num_nobrainers++;
             if (num_nobrainers < 3)
                 plr->message = DEH_String(HUSTR_TALKTOSELF1);
             else if (num_nobrainers < 6)
                 plr->message = DEH_String(HUSTR_TALKTOSELF2);
             else if (num_nobrainers < 9)
                 plr->message = DEH_String(HUSTR_TALKTOSELF3);
             else if (num_nobrainers < 32)
                 plr->message = DEH_String(HUSTR_TALKTOSELF4);
             else
                 plr->message = DEH_String(HUSTR_TALKTOSELF5);
             }
         }
         }
     }
     }
     else
     {
     // send a macro
     if (altdown)
     {
         c = ev->data1 - '0';
         if (c > 9)
         return false;
         // fprintf(stderr, "got here\n");
         macromessage = chat_macros[c];
         // kill last message with a '\n'
         HU_queueChatChar(KEY_ENTER); // DEBUG!!!
         // send the macro message
         while (*macromessage)
         HU_queueChatChar(*macromessage++);
         HU_queueChatChar(KEY_ENTER);
             // leave chat mode and notify that it was sent
             chat_on = false;
             M_StringCopy(lastmessage, chat_macros[c], sizeof(lastmessage));
             plr->message = lastmessage;
             eatkey = true;
     }
     else
     {
             c = ev->data2;
         eatkey = HUlib_keyInIText(&w_chat, c);
         if (eatkey)
         {
         // static unsigned char buf[20]; // DEBUG
         HU_queueChatChar(c);
         // M_snprintf(buf, sizeof(buf), "KEY: %d => %d", ev->data1, c);
         //        plr->message = buf;
         }
         if (c == KEY_ENTER)
         {
         chat_on = false;
                 if (w_chat.l.len)
                 {
                     M_StringCopy(lastmessage, w_chat.l.l, sizeof(lastmessage));
                     plr->message = lastmessage;
                 }
         }
         else if (c == KEY_ESCAPE)
         chat_on = false;
     }
     }
     return eatkey;
 }
References c, chat_macros, chat_on, consoleplayer, event_t::data1, event_t::data2, DEH_String, ev_keydown, HU_BROADCAST, HU_MAXLINELENGTH, HU_MSGTIMEOUT, HU_queueChatChar(), HUlib_keyInIText(), HUlib_resetIText(), HUSTR_TALKTOSELF1, HUSTR_TALKTOSELF2, HUSTR_TALKTOSELF3, HUSTR_TALKTOSELF4, HUSTR_TALKTOSELF5, i, KEY_ENTER, KEY_ESCAPE, KEY_LALT, key_message_refresh, key_multi_msg, key_multi_msgplayer, KEY_RALT, KEY_RSHIFT, hu_textline_t::l, hu_itext_t::l, hu_textline_t::len, M_StringCopy(), MAXPLAYERS, player_s::message, message_counter, message_on, netgame, playeringame, plr, event_t::type, and w_chat.
Referenced by G_Responder().
HU_Start()
void HU_Start (void)
Definition at line 308 of file hu_stuff.c.
 {
     int     i;
     char*   s;
     if (headsupactive)
     HU_Stop();
     plr = &players[consoleplayer];
     message_on = false;
     message_dontfuckwithme = false;
     message_nottobefuckedwith = false;
     chat_on = false;
     // create the message widget
     HUlib_initSText(&w_message,
             HU_MSGX, HU_MSGY, HU_MSGHEIGHT,
             hu_font,
             HU_FONTSTART, &message_on);
     // create the map title widget
     HUlib_initTextLine(&w_title,
                HU_TITLEX, HU_TITLEY,
                hu_font,
                HU_FONTSTART);
     switch ( logical_gamemission )
     {
       case doom:
     s = HU_TITLE;
     break;
       case doom2:
      s = HU_TITLE2;
      break;
       case pack_plut:
     s = HU_TITLEP;
     break;
       case pack_tnt:
     s = HU_TITLET;
     break;
       default:
          s = "Unknown level";
          break;
     }
     // Chex.exe always uses the episode 1 level title
     // eg. E2M1 gives the title for E1M1
     if (gameversion == exe_chex)
     {
         s = HU_TITLE_CHEX;
     }
     // dehacked substitution to get modified level name
     s = DEH_String(s);
     while (*s)
     HUlib_addCharToTextLine(&w_title, *(s++));
     // create the chat widget
     HUlib_initIText(&w_chat,
             HU_INPUTX, HU_INPUTY,
             hu_font,
             HU_FONTSTART, &chat_on);
     // create the inputbuffer widgets
     for (i=0 ; i<MAXPLAYERS ; i++)
     HUlib_initIText(&w_inputbuffer[i], 0, 0, 0, 0, &always_off);
     headsupactive = true;
 }
References always_off, chat_on, consoleplayer, DEH_String, doom, doom2, exe_chex, gameversion, headsupactive, hu_font, HU_FONTSTART, HU_INPUTX, HU_INPUTY, HU_MSGHEIGHT, HU_MSGX, HU_MSGY, HU_Stop(), HU_TITLE, HU_TITLE2, HU_TITLE_CHEX, HU_TITLEP, HU_TITLET, HU_TITLEX, HU_TITLEY, HUlib_addCharToTextLine(), HUlib_initIText(), HUlib_initSText(), HUlib_initTextLine(), i, logical_gamemission, MAXPLAYERS, message_dontfuckwithme, message_nottobefuckedwith, message_on, pack_plut, pack_tnt, players, plr, w_chat, w_inputbuffer, w_message, and w_title.
Referenced by P_SpawnPlayer().
HU_Ticker()
void HU_Ticker (void)
Definition at line 402 of file hu_stuff.c.
 {
     int i, rc;
     char c;
     // tick down message counter if message is up
     if (message_counter && !--message_counter)
     {
     message_on = false;
     message_nottobefuckedwith = false;
     }
     if (showMessages || message_dontfuckwithme)
     {
     // display message if necessary
     if ((plr->message && !message_nottobefuckedwith)
         || (plr->message && message_dontfuckwithme))
     {
         HUlib_addMessageToSText(&w_message, 0, plr->message);
         plr->message = 0;
         message_on = true;
         message_counter = HU_MSGTIMEOUT;
         message_nottobefuckedwith = message_dontfuckwithme;
         message_dontfuckwithme = 0;
     }
     } // else message_on = false;
     // check for incoming chat characters
     if (netgame)
     {
     for (i=0 ; i<MAXPLAYERS; i++)
     {
         if (!playeringame[i])
         continue;
         if (i != consoleplayer
         && (c = players[i].cmd.chatchar))
         {
         if (c <= HU_BROADCAST)
             chat_dest[i] = c;
         else
         {
             rc = HUlib_keyInIText(&w_inputbuffer[i], c);
             if (rc && c == KEY_ENTER)
             {
             if (w_inputbuffer[i].l.len
                 && (chat_dest[i] == consoleplayer+1
                 || chat_dest[i] == HU_BROADCAST))
             {
                 HUlib_addMessageToSText(&w_message,
                             DEH_String(player_names[i]),
                             w_inputbuffer[i].l.l);
                 message_nottobefuckedwith = true;
                 message_on = true;
                 message_counter = HU_MSGTIMEOUT;
                 if ( gamemode == commercial )
                   S_StartSound(0, sfx_radio);
                 else
                   S_StartSound(0, sfx_tink);
             }
             HUlib_resetIText(&w_inputbuffer[i]);
             }
         }
         players[i].cmd.chatchar = 0;
         }
     }
     }
 }
References c, chat_dest, ticcmd_t::chatchar, player_s::cmd, commercial, consoleplayer, DEH_String, gamemode, HU_BROADCAST, HU_MSGTIMEOUT, HUlib_addMessageToSText(), HUlib_keyInIText(), HUlib_resetIText(), i, KEY_ENTER, hu_itext_t::l, MAXPLAYERS, player_s::message, message_counter, message_dontfuckwithme, message_nottobefuckedwith, message_on, netgame, player_names, playeringame, players, plr, S_StartSound(), sfx_radio, sfx_tink, showMessages, w_inputbuffer, and w_message.
Referenced by G_Ticker().
Variable Documentation
chat_macros
char* chat_macros[10] extern
Definition at line 64 of file hu_stuff.c.
Referenced by D_BindVariables(), and HU_Responder().