Fennix Userspace: Userspace/mlibc/options/glibc/generic/error.cpp File Reference
error.cpp File Reference
#include <stdio.h>
#include <stdarg.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <error.h>
Functions
void error (int status, int errnum, const char *format,...)
void error_at_line (int status, int errnum, const char *filename, unsigned int linenum, const char *format,...)
Variables
unsigned int error_message_count = 0
int error_one_per_line = 0
void(* error_print_progname)(void) = NULL
Function Documentation
error()
void error (int status, int errnum, const char * format, ...)
Definition at line 12 of file error.cpp.
{
     va_list args;
     va_start(args, format);
     error_message_count++;
     fflush(stdout);
     if(error_print_progname) {
         error_print_progname();
     } else {
         fprintf(stderr, "%s: ", program_invocation_name);
     }
     vfprintf(stderr, format, args);
     va_end(args);
     if(errnum) {
         fprintf(stderr, ": %s\n", strerror(errnum));
     }
     if(status) {
         exit(status);
     }
 }
References args, error_message_count, error_print_progname, exit(), fflush(), format, fprintf(), program_invocation_name, mlibc::status, stderr, stdout, strerror(), va_end(), va_start(), and vfprintf().
error_at_line()
void error_at_line (int status, int errnum, const char * filename, unsigned int linenum, const char * format, ...)
Definition at line 36 of file error.cpp.
{
     va_list args;
     va_start(args, format);
     static bool first_call = true;
     static unsigned int last_line = 0;
     if(!(last_line == linenum && error_one_per_line && !first_call)) {
         first_call = false;
         last_line = linenum;
         error_message_count++;
         fflush(stdout);
         if(error_print_progname) {
             error_print_progname();
         } else {
             fprintf(stderr, "%s:", program_invocation_name);
         }
         fprintf(stderr, "%s:%u: ", filename, linenum);
         vfprintf(stderr, format, args);
         if(errnum) {
             fprintf(stderr, ": %s\n", strerror(errnum));
         }
     }
     va_end(args);
     if(status) {
         exit(status);
     }
 }
References args, error_message_count, error_one_per_line, error_print_progname, exit(), fflush(), format, fprintf(), program_invocation_name, mlibc::status, stderr, stdout, strerror(), va_end(), va_start(), and vfprintf().
Referenced by main().
Variable Documentation
error_message_count
unsigned int error_message_count = 0
Definition at line 8 of file error.cpp.
Referenced by error(), error_at_line(), and main().
error_one_per_line
int error_one_per_line = 0
Definition at line 9 of file error.cpp.
Referenced by error_at_line(), and main().
error_print_progname
void(* error_print_progname) (void) (void) = NULL
Definition at line 10 of file error.cpp.
Referenced by error(), error_at_line(), and main().