Fennix: Userspace/musl/src/exit/at_quick_exit.c File Reference
at_quick_exit.c File Reference
#include <stdlib.h>
#include "libc.h"
#include "lock.h"
#include "fork_impl.h"
Macros
#define COUNT 32
Functions
void __funcs_on_quick_exit ()
int at_quick_exit (void(*func)(void))
Variables
static void(* funcs [COUNT])(void)
static int count
static volatile int lock [1]
volatile int *const __at_quick_exit_lockptr = lock
Macro Definition Documentation
COUNT
#define COUNT 32
Definition at line 6 of file at_quick_exit.c.
Function Documentation
__funcs_on_quick_exit()
void __funcs_on_quick_exit (void)
Definition at line 13 of file at_quick_exit.c.
 {
     void (*func)(void);
     LOCK(lock);
     while (count > 0) {
         func = funcs[--count];
         UNLOCK(lock);
         func();
         LOCK(lock);
     }
 }
References count, func(), funcs, LOCK, lock, and UNLOCK.
Referenced by quick_exit().
at_quick_exit()
int at_quick_exit (void(*)(void) func)
Definition at line 25 of file at_quick_exit.c.
 {
     int r = 0;
     LOCK(lock);
     if (count == 32) r = -1;
     else funcs[count++] = func;
     UNLOCK(lock);
     return r;
 }
References count, func(), funcs, LOCK, lock, and UNLOCK.
Variable Documentation
__at_quick_exit_lockptr
volatile int* const __at_quick_exit_lockptr = lock
Definition at line 11 of file at_quick_exit.c.
count
int count static
Definition at line 9 of file at_quick_exit.c.
Referenced by __funcs_on_quick_exit(), and at_quick_exit().
funcs
void(* funcs[COUNT])(void) (void) static
Definition at line 8 of file at_quick_exit.c.
Referenced by __funcs_on_quick_exit(), and at_quick_exit().
lock
volatile int lock[1] static
Definition at line 10 of file at_quick_exit.c.
Referenced by __funcs_on_quick_exit(), and at_quick_exit().