Fennix Userspace: Userspace/musl/src/passwd/fgetspent.c File Reference
fgetspent.c File Reference
#include "pwf.h"
#include <pthread.h>
Functions
struct spwd * fgetspent (FILE *f)
Function Documentation
fgetspent()
struct spwd* fgetspent (FILE * f)
Definition at line 4 of file fgetspent.c.
 {
     static char *line;
     static struct spwd sp;
     size_t size = 0;
     struct spwd *res = 0;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     if (getline(&line, &size, f) >= 0 && __parsespent(line, &sp) >= 0) res = &sp;
     pthread_setcancelstate(cs, 0);
     return res;
 }
References __parsespent(), f, getline(), line, PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), size, and sp.