Fennix Userspace: Userspace/musl/arch/sh/syscall_arch.h File Reference
syscall_arch.h File Reference
Macros
#define __SYSCALL_LL_E(x)
#define __SYSCALL_LL_O(x) __SYSCALL_LL_E((x))
#define __SYSCALL_LL_PRW(x) 0, __SYSCALL_LL_E((x))
#define __asm_syscall(trapno, ...)
#define SYSCALL_IPC_BROKEN_MODE
#define SIOCGSTAMP_OLD (2U<<30 | 's'<<8 | 100 | 8<<16)
#define SIOCGSTAMPNS_OLD (2U<<30 | 's'<<8 | 101 | 8<<16)
Functions
static long __syscall0 (long n)
static long __syscall1 (long n, long a)
static long __syscall2 (long n, long a, long b)
static long __syscall3 (long n, long a, long b, long c)
static long __syscall4 (long n, long a, long b, long c, long d)
static long __syscall5 (long n, long a, long b, long c, long d, long e)
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f)
Macro Definition Documentation
__asm_syscall
#define __asm_syscall (trapno, ...)
Value:
    do {   \
    __asm__ __volatile__ (                \
        "trapa #31\n"            \
        "or r0, r0\n"                     \
        "or r0, r0\n"                     \
        "or r0, r0\n"                     \
        "or r0, r0\n"                     \
        "or r0, r0\n"                     \
    : "=r"(r0) : __VA_ARGS__ : "memory"); \
    return r0;                            \
    } while (0)
Definition at line 10 of file syscall_arch.h.
__SYSCALL_LL_E
#define __SYSCALL_LL_E (x)
Value:
((union { long long ll; long l[2]; }){ .ll = x }).l[0], \
((union { long long ll; long l[2]; }){ .ll = x }).l[1]
Definition at line 1 of file syscall_arch.h.
__SYSCALL_LL_O
#define __SYSCALL_LL_O (x) __SYSCALL_LL_E((x))
Definition at line 4 of file syscall_arch.h.
__SYSCALL_LL_PRW
#define __SYSCALL_LL_PRW (x) 0, __SYSCALL_LL_E((x))
Definition at line 5 of file syscall_arch.h.
SIOCGSTAMP_OLD
#define SIOCGSTAMP_OLD (2U<<30 | 's'<<8 | 100 | 8<<16)
Definition at line 92 of file syscall_arch.h.
SIOCGSTAMPNS_OLD
#define SIOCGSTAMPNS_OLD (2U<<30 | 's'<<8 | 101 | 8<<16)
Definition at line 93 of file syscall_arch.h.
SYSCALL_IPC_BROKEN_MODE
#define SYSCALL_IPC_BROKEN_MODE
Definition at line 90 of file syscall_arch.h.
Function Documentation
__syscall0()
static long __syscall0 (long n) inline static
Definition at line 22 of file syscall_arch.h.
 {
     register long r3 __asm__("r3") = n;
     register long r0 __asm__("r0");
     __asm_syscall(16, "r"(r3));
 }
References __asm__(), __asm_syscall, n, r0, and r3.
__syscall1()
static long __syscall1 (long n, long a) inline static
Definition at line 29 of file syscall_arch.h.
 {
     register long r3 __asm__("r3") = n;
     register long r4 __asm__("r4") = a;
     register long r0 __asm__("r0");
     __asm_syscall(17, "r"(r3), "r"(r4));
 }
References __asm__(), __asm_syscall, n, r0, r3, and r4.
__syscall2()
static long __syscall2 (long n, long a, long b) inline static
Definition at line 37 of file syscall_arch.h.
 {
     register long r3 __asm__("r3") = n;
     register long r4 __asm__("r4") = a;
     register long r5 __asm__("r5") = b;
     register long r0 __asm__("r0");
     __asm_syscall(18, "r"(r3), "r"(r4), "r"(r5));
 }
References __asm__(), __asm_syscall, n, r0, r3, r4, and r5.
__syscall3()
static long __syscall3 (long n, long a, long b, long c) inline static
Definition at line 46 of file syscall_arch.h.
 {
     register long r3 __asm__("r3") = n;
     register long r4 __asm__("r4") = a;
     register long r5 __asm__("r5") = b;
     register long r6 __asm__("r6") = c;
     register long r0 __asm__("r0");
     __asm_syscall(19, "r"(r3), "r"(r4), "r"(r5), "r"(r6));
 }
References __asm__(), __asm_syscall, c, n, r0, r3, r4, r5, and r6.
__syscall4()
static long __syscall4 (long n, long a, long b, long c, long d) inline static
Definition at line 56 of file syscall_arch.h.
 {
     register long r3 __asm__("r3") = n;
     register long r4 __asm__("r4") = a;
     register long r5 __asm__("r5") = b;
     register long r6 __asm__("r6") = c;
     register long r7 __asm__("r7") = d;
     register long r0 __asm__("r0");
     __asm_syscall(20, "r"(r3), "r"(r4), "r"(r5), "r"(r6), "r"(r7));
 }
References __asm__(), __asm_syscall, c, n, r0, r3, r4, r5, and r6.
__syscall5()
static long __syscall5 (long n, long a, long b, long c, long d, long e) inline static
Definition at line 67 of file syscall_arch.h.
 {
     register long r3 __asm__("r3") = n;
     register long r4 __asm__("r4") = a;
     register long r5 __asm__("r5") = b;
     register long r6 __asm__("r6") = c;
     register long r7 __asm__("r7") = d;
     register long r0 __asm__("r0") = e;
     __asm_syscall(21, "r"(r3), "r"(r4), "r"(r5), "r"(r6), "r"(r7), "0"(r0));
 }
References __asm__(), __asm_syscall, c, n, r0, r3, r4, r5, and r6.
__syscall6()
static long __syscall6 (long n, long a, long b, long c, long d, long e, long f) inline static
Definition at line 78 of file syscall_arch.h.
 {
     register long r3 __asm__("r3") = n;
     register long r4 __asm__("r4") = a;
     register long r5 __asm__("r5") = b;
     register long r6 __asm__("r6") = c;
     register long r7 __asm__("r7") = d;
     register long r0 __asm__("r0") = e;
     register long r1 __asm__("r1") = f;
     __asm_syscall(22, "r"(r3), "r"(r4), "r"(r5), "r"(r6), "r"(r7), "0"(r0), "r"(r1));
 }
References __asm__(), __asm_syscall, c, f, n, r0, r1, r3, r4, r5, and r6.