Fennix Userspace: Userspace/musl/compat/time32/stat_time32.c File Reference
stat_time32.c File Reference
#include "time32.h"
#include <time.h>
#include <string.h>
#include <sys/stat.h>
#include <stddef.h>
Functions
int __stat_time32 (const char *restrict path, struct stat32 *restrict st32)
Function Documentation
__stat_time32()
int __stat_time32 (const char *restrict path, struct stat32 *restrict st32)
Definition at line 9 of file stat_time32.c.
 {
     struct stat st;
     int r = stat(path, &st);
     if (!r) memcpy(st32, &st, offsetof(struct stat, st_atim));
     return r;
 }
References memcpy(), offsetof, stat::st_atim, and stat().
Referenced by __xstat().