Fennix: Userspace/mlibc/tests/posix/search.c File Reference
search.c File Reference
#include <search.h>
#include <assert.h>
#include <stddef.h>
#include <stdlib.h>
Functions
static int compare (const void *pa, const void *pb)
static void check_key (int key, void *root)
static void free_key (void *key)
int main ()
Function Documentation
check_key()
static void check_key (int key, void * root) static
Definition at line 14 of file search.c.
{
     int keyp = key;
     void *ret = tfind((void*) &keyp, &root, compare);
     assert(ret);
     assert(**((int **) ret) == key);
 }
References assert, compare(), ret, and tfind().
Referenced by main().
compare()
static int compare (const void * pa, const void * pb) static
Definition at line 6 of file search.c.
{
     if (*(int*)pa < *(int*) pb)
         return -1;
     if (*(int*)pa > *(int*) pb)
         return 1;
     return 0;
 }
Referenced by check_key(), and main().
free_key()
static void free_key (void * key) static
Definition at line 21 of file search.c.
{
     free(key);
 }
References free.
Referenced by main().
main()
int main (void)
Definition at line 25 of file search.c.
            {
     void *root = NULL;
     for (int i = 0; i < 12; i++) {
         int *ptr = malloc(sizeof(int));
         assert(ptr);
         *ptr = i;
         void *ret = tsearch((void*) ptr, &root, compare);
         assert(ret);
         assert(**((int **) ret) == i);
     }
     // Test a couple of keys
     check_key(1, root);
     check_key(5, root);
     check_key(10, root);
     // Verify NULL on non-existent key
     int key = -1;
     void *ret = tfind((void*) &key, &root, compare);
     assert(ret == NULL);
     // tdelete is not implemented yet (#351)
     (void)free_key;
     // tdestroy(root, free_key);
     return 0;
 }
References assert, check_key(), compare(), free_key(), i, malloc, NULL, ret, tfind(), tsearch(), and Driver::void().