Fennix Userspace: Userspace/musl/src/network/recv.c File Reference
recv.c File Reference
#include <sys/socket.h>
Functions
ssize_t recv (int fd, void *buf, size_t len, int flags)
Function Documentation
recv()
ssize_t recv (int fd, void * buf, size_t len, int flags)
Definition at line 3 of file recv.c.
 {
     return recvfrom(fd, buf, len, flags, 0, 0);
 }
References buf, fd, flags, and recvfrom().
Referenced by __netlink_enumerate(), check_existence_through_netlink(), inetd_main(), ping4(), recv_and_process_peer_pkt(), rtnl_send_check(), and start().