Fennix Kernel: Kernel/core/panic/handler.cpp File Reference
handler.cpp File Reference
#include <display.hpp>
#include <bitmap.hpp>
#include <convert.h>
#include <printf.h>
#include <lock.hpp>
#include <rand.hpp>
#include <uart.hpp>
#include <kcon.hpp>
#include <debug.h>
#include <smp.hpp>
#include <cpu.hpp>
#include <io.h>
#include "../../kernel.h"
Functions
void DisplayCrashScreen (CPU::ExceptionFrame *)
bool UserModeExceptionHandler (CPU::ExceptionFrame *)
void DisplayStackSmashing ()
void DisplayBufferOverflow ()
void DisplayAssertionFailed (const char *, int, const char *)
void paint_callback (TerminalCell *cell, long x, long y)
nsa void __printfWrapper (char c, void *)
nsa void ExPrint (const char *Format,...)
nsa void HaltAllCores ()
nsa void InitFont ()
nsa __noreturn void HandleUnrecoverableException (CPU::ExceptionFrame *Frame)
nsa __noreturn void HandleExceptionInsideException (CPU::ExceptionFrame *Frame)
nsa void HandleException (CPU::ExceptionFrame *Frame)
nsa void BaseBufferStackError (bool Stack)
nsa __noreturn void HandleStackSmashing ()
nsa __noreturn void HandleBufferOverflow ()
EXTERNC nsa __noreturn void HandleAssertionFailed (const char *File, int Line, const char *Expression)
Variables
const char * x86ExceptionMnemonics []
void * FbBeforePanic = nullptr
size_t FbPagesBeforePanic = 0
FontRenderer CrashFontRenderer
int ExTermColors []
int ExTermBrightColors []
std::atomic< bool > UnrecoverableLock = false
std::atomic< bool > ExceptionLock = false
Function Documentation
__printfWrapper()
nsa void __printfWrapper (char c, void *)
Definition at line 85 of file handler.cpp.
 {
     KernelConsole::Terminals[15]->Process(c);
 }
References KernelConsole::VirtualTerminal::Process(), and KernelConsole::Terminals.
Referenced by ExPrint().
BaseBufferStackError()
nsa void BaseBufferStackError (bool Stack)
Definition at line 348 of file handler.cpp.
 {
     /* We don't need to restore the page table
         because the ExceptionHandlerStub will
         do it for us if we return. */
     CPU::PageTable(KernelPageTable);
     if (CrashFontRenderer.CurrentFont == nullptr)
         CrashFontRenderer.CurrentFont = new Video::Font(&_binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_start,
                                                         &_binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_end,
                                                         Video::FontType::PCScreenFont2);
     if (Terminals[15] == nullptr)
     {
         size_t Cols = Display->GetWidth / CrashFontRenderer.CurrentFont->GetInfo().Width;
         size_t Rows = Display->GetHeight / CrashFontRenderer.CurrentFont->GetInfo().Height;
         Terminals[15] = new VirtualTerminal(Cols, Rows, Display->GetWidth, Display->GetHeight, paint_callback, nullptr);
     }
     ExceptionLock.store(true, std::memory_order_release);
     if (DriverManager)
         DriverManager->Panic();
     if (TaskManager)
         TaskManager->Panic();
     HaltAllCores();
     ForceUnlock = true;
     debug("-----------------------------------------------------------------------------------");
     error("%s", Stack ? "Stack smashing detected" : "Buffer overflow detected");
     debug("%ld MiB / %ld MiB (%ld MiB Reserved)",
           TO_MiB(KernelAllocator.GetUsedMemory()),
           TO_MiB(KernelAllocator.GetTotalMemory()),
           TO_MiB(KernelAllocator.GetReservedMemory()));
 }
References _binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_end, _binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_start, CrashFontRenderer, KernelConsole::FontRenderer::CurrentFont, debug, Display, DriverManager, error, ExceptionLock, ForceUnlock, Video::Display::GetHeight, Video::Font::GetInfo(), Video::Display::GetWidth, HaltAllCores(), Video::FontInfo::Height, KernelAllocator, KernelPageTable, memory_order_release, CPU::PageTable(), KernelConsole::paint_callback(), Driver::Manager::Panic(), Tasking::Task::Panic(), Video::PCScreenFont2, Stack, TaskManager, KernelConsole::Terminals, TO_MiB, and Video::FontInfo::Width.
Referenced by HandleBufferOverflow(), and HandleStackSmashing().
DisplayAssertionFailed()
void DisplayAssertionFailed (const char * File, int Line, const char * Expression)
Definition at line 804 of file ui.cpp.
 {
     InitFont();
     ExPrint("\x1b[2J\x1b[H");
     Display->ClearBuffer();
     DisplayTopOverlay();
     ExPrint("\nWe're sorry, but the system has encountered a critical error and needs to restart.\n");
     ExPrint("\nError: Assertion Failed\n");
     ExPrint("In file \"%s\" at line %d, \"%s\" failed\n",
             File, Line, Expression);
     CPUData *core = GetCurrentCPU();
     if (TaskManager && core->CurrentProcess.load() && core->CurrentThread.load())
     {
         ExPrint("Core: %d / pid: %d / tid: %d\n", core->ID,
                 core->CurrentProcess->ID, core->CurrentThread->ID);
     }
     else if (core->IsActive)
         ExPrint("Core: %d\n", core->ID);
     ExPrint("\nWhat to do:\n");
     ExPrint(" This is a kernel bug.\n");
     ExPrint(" Please create a new issue on https://github.com/Fennix-Project/Fennix for further assistance.\n");
     CPU::ExceptionFrame ef;
     // Fill only the necessary fields
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wframe-address"
     /* Jump over HandleAssertionFailed, and ip will be the function where it failed */
     void *fun = __builtin_return_address(1);
     /* Jump over this, HandleAssertionFailed & ip */
     void *stk = __builtin_frame_address(2);
 #pragma GCC diagnostic pop
 #ifdef __x86_64__
     asmv("movq %%cr3, %0" : "=r"(ef.cr3));
     ef.rip = (uint64_t)fun;
     ef.rbp = ef.rsp = (uint64_t)stk;
 #elif defined(__i386__)
     asmv("movl %%cr3, %0" : "=r"(ef.cr3));
     ef.eip = (uint32_t)fun;
     ef.ebp = ef.esp = (uint32_t)stk;
 #endif
     DisplayStackScreen(&ef);
     /* TODO: Add additional info */
 }
References asmv(), Video::Display::ClearBuffer(), CPUData::CurrentProcess, CPUData::CurrentThread, Display, DisplayStackScreen(), DisplayTopOverlay(), Expression, ExPrint(), GetCurrentCPU(), CPUData::ID, InitFont(), CPUData::IsActive, Line, and TaskManager.
Referenced by HandleAssertionFailed().
DisplayBufferOverflow()
void DisplayBufferOverflow ()
Definition at line 778 of file ui.cpp.
 {
     InitFont();
     ExPrint("\x1b[2J\x1b[H");
     Display->ClearBuffer();
     DisplayTopOverlay();
     ExPrint("\nWe're sorry, but the system has encountered a critical error and needs to restart.\n");
     ExPrint("\nError: Buffer Overflow In Kernel Mode\n");
     CPUData *core = GetCurrentCPU();
     if (TaskManager)
     {
         ExPrint("Core: %d / pid: %d / tid: %d\n", core->ID,
                 core->CurrentProcess->ID, core->CurrentThread->ID);
     }
     else if (core->IsActive)
         ExPrint("Core: %d\n", core->ID);
     ExPrint("\nWhat to do:\n");
     ExPrint(" This is a kernel bug.\n");
     ExPrint(" Please create a new issue on https://github.com/Fennix-Project/Fennix for further assistance.\n");
     /* TODO: Add additional info */
 }
References Video::Display::ClearBuffer(), CPUData::CurrentProcess, CPUData::CurrentThread, Display, DisplayTopOverlay(), ExPrint(), GetCurrentCPU(), CPUData::ID, InitFont(), CPUData::IsActive, and TaskManager.
Referenced by HandleBufferOverflow().
DisplayCrashScreen()
void DisplayCrashScreen (CPU::ExceptionFrame * Frame)
Definition at line 625 of file ui.cpp.
 {
     ExFrame = Frame;
     /* TODO */
     // void *BufferBeforeUpdate = KernelAllocator.RequestPages(TO_PAGES(Display->GetSize));
     // if (BufferBeforeUpdate)
     //  memcpy(BufferBeforeUpdate, Display->GetBuffer, Display->GetSize);
     Display->ClearBuffer();
     ExPrint("\x1b[2J\x1b[H");
     if (Config.InterruptsOnCrash == false)
     {
         DisplayMainScreen(Frame);
         CPU::Stop();
     }
     DisplayTopOverlay();
     DisplayMainScreen(Frame);
     InitializeKeyboards();
     DisplayBottomOverlay();
 #ifdef DEBUG
     static int once = 0;
     static uint8_t com4 = 0xFF;
     if (!once++)
         com4 = inb(0x2E8);
     if (com4 == 0xFF)
         CPU::Halt(true);
     char UserInputBuffer[256]{'\0'};
     int BackSpaceLimit = 0;
     while (true)
     {
         while ((inb(0x2E8 + 5) & 1) == 0)
             CPU::Pause();
         char key = inb(0x2E8);
         // debug("key: %d", key);
         if (key == '\x7f') /* Backspace (DEL) */
         {
             if (BackSpaceLimit <= 0)
                 continue;
             char keyBuf[5] = {'\b', '\x1b', '[', 'K', '\0'};
             ExPrint(keyBuf);
             backspace(UserInputBuffer);
             BackSpaceLimit--;
             continue;
         }
         else if (key == '\x0d') /* Enter (CR) */
         {
             UserInput(UserInputBuffer);
             BackSpaceLimit = 0;
             UserInputBuffer[0] = '\0';
             continue;
         }
         else if (key == '\x1b') /* Escape */
         {
             char tmp[16]{'\0'};
             append(tmp, key);
             while ((inb(0x2E8 + 5) & 1) == 0)
                 CPU::Pause();
             char key = inb(0x2E8);
             append(tmp, key);
             if (key == '[')
             {
                 // 27 91
                 // <  68
                 // > 67
                 //  down 66
                 //  up 65
                 while ((inb(0x2E8 + 5) & 1) == 0)
                     CPU::Pause();
                 key = inb(0x2E8);
                 append(tmp, key);
                 switch (key)
                 {
                 case 'A':
                     key = KEY_D_UP;
                     break;
                 case 'B':
                     key = KEY_D_DOWN;
                     break;
                 case 'C':
                     key = KEY_D_RIGHT;
                     break;
                 case 'D':
                     key = KEY_D_LEFT;
                     break;
                 default:
                 {
                     for (size_t i = 0; i < strlen(tmp); i++)
                     {
                         if ((int)sizeof(UserInputBuffer) <= BackSpaceLimit)
                             continue;
                         append(UserInputBuffer, tmp[i]);
                         BackSpaceLimit++;
                         char keyBuf[2] = {(char)tmp[i], '\0'};
                         ExPrint(keyBuf);
                     }
                     continue;
                 }
                 }
                 ArrowInput(key);
                 continue;
             }
         }
         if ((int)sizeof(UserInputBuffer) <= BackSpaceLimit)
             continue;
         append(UserInputBuffer, key);
         BackSpaceLimit++;
         char keyBuf[2] = {(char)key, '\0'};
         ExPrint(keyBuf);
     }
 #endif
     debug("cpu halted");
     CPU::Halt(true);
 }
References append(), ArrowInput(), backspace(), Video::Display::ClearBuffer(), Config, debug, Display, DisplayBottomOverlay(), DisplayMainScreen(), DisplayTopOverlay(), ExFrame, ExPrint(), CPU::Halt(), InitializeKeyboards(), KernelConfig::InterruptsOnCrash, KEY_D_DOWN, KEY_D_LEFT, KEY_D_RIGHT, KEY_D_UP, CPU::Pause(), CPU::Stop(), strlen(), and UserInput().
Referenced by HandleException().
DisplayStackSmashing()
void DisplayStackSmashing ()
Definition at line 752 of file ui.cpp.
 {
     InitFont();
     ExPrint("\x1b[2J\x1b[H");
     Display->ClearBuffer();
     DisplayTopOverlay();
     ExPrint("\nWe're sorry, but the system has encountered a critical error and needs to restart.\n");
     ExPrint("\nError: Stack Smashing In Kernel Mode\n");
     CPUData *core = GetCurrentCPU();
     if (TaskManager)
     {
         ExPrint("Core: %d / pid: %d / tid: %d\n", core->ID,
                 core->CurrentProcess->ID, core->CurrentThread->ID);
     }
     else if (core->IsActive)
         ExPrint("Core: %d\n", core->ID);
     ExPrint("\nWhat to do:\n");
     ExPrint(" This is a kernel bug.\n");
     ExPrint(" Please create a new issue on https://github.com/Fennix-Project/Fennix for further assistance.\n");
     /* TODO: Add additional info */
 }
References Video::Display::ClearBuffer(), CPUData::CurrentProcess, CPUData::CurrentThread, Display, DisplayTopOverlay(), ExPrint(), GetCurrentCPU(), CPUData::ID, InitFont(), CPUData::IsActive, and TaskManager.
Referenced by HandleStackSmashing().
ExPrint()
nsa void ExPrint (const char * Format, ...)
Definition at line 90 of file handler.cpp.
 {
     va_list args;
     va_start(args, Format);
     vfctprintf(__printfWrapper, NULL, Format, args);
     va_end(args);
 }
References __printfWrapper(), NULL, va_end, va_start, and vfctprintf().
Referenced by ArrowInput(), CrashEHCIKeyboardDriver::CrashEHCIKeyboardDriver(), CrashPS2KeyboardDriver::CrashPS2KeyboardDriver(), CrashUHCIKeyboardDriver::CrashUHCIKeyboardDriver(), CrashXHCIKeyboardDriver::CrashXHCIKeyboardDriver(), DiagnosticDataCollection(), DisplayAssertionFailed(), DisplayBottomOverlay(), DisplayBufferOverflow(), DisplayCrashScreen(), DisplayDetailsScreen(), DisplayMainScreen(), DisplayProcessScreen(), DisplayStackScreen(), DisplayStackSmashing(), DisplayTopOverlay(), ExDumpData(), HandleExceptionInsideException(), HandleUnrecoverableException(), CrashXHCIKeyboardDriver::Initialize(), CrashPS2KeyboardDriver::OnInterruptReceived(), CrashPS2KeyboardDriver::PS2Wait(), CrashXHCIKeyboardDriver::TakeOwnership(), UserInput(), and WriteDiagDataToNode().
HaltAllCores()
nsa void HaltAllCores ()
Definition at line 98 of file handler.cpp.
 {
     if (SMP::CPUCores <= 1)
         return;
 #if defined(a86)
     if (Interrupts::apic[0] == nullptr)
         return;
     APIC::InterruptCommandRegister icr{};
     bool x2APIC = ((APIC::APIC *)Interrupts::apic[0])->x2APIC;
     if (likely(x2APIC))
     {
         icr.x2.VEC = s_cst(uint8_t, CPU::x86::IRQ31);
         icr.x2.MT = APIC::Fixed;
         icr.x2.L = APIC::Assert;
         for (int i = 1; i < SMP::CPUCores; i++)
         {
             icr.x2.DES = uint8_t(i);
             ((APIC::APIC *)Interrupts::apic[i])->ICR(icr);
         }
     }
     else
     {
         icr.VEC = s_cst(uint8_t, CPU::x86::IRQ31);
         icr.MT = APIC::Fixed;
         icr.L = APIC::Assert;
         for (int i = 1; i < SMP::CPUCores; i++)
         {
             icr.DES = uint8_t(i);
             ((APIC::APIC *)Interrupts::apic[i])->ICR(icr);
         }
     }
 #elif defined(aa64)
 #endif
 }
References APIC::Assert, SMP::CPUCores, APIC::Fixed, CPU::x86::IRQ31, and likely.
Referenced by BaseBufferStackError(), and HandleException().
HandleAssertionFailed()
EXTERNC nsa __noreturn void HandleAssertionFailed (const char * File, int Line, const char * Expression)
Definition at line 398 of file handler.cpp.
 {
     DisplayAssertionFailed(File, Line, Expression);
     CPU::Stop();
 }
References DisplayAssertionFailed(), Expression, Line, and CPU::Stop().
HandleBufferOverflow()
nsa __noreturn void HandleBufferOverflow ()
Definition at line 391 of file handler.cpp.
 {
     BaseBufferStackError(false);
     DisplayBufferOverflow();
     CPU::Stop();
 }
References BaseBufferStackError(), DisplayBufferOverflow(), and CPU::Stop().
Referenced by __chk_fail().
HandleException()
nsa void HandleException (CPU::ExceptionFrame * Frame)
Definition at line 281 of file handler.cpp.
 {
     /* We don't need to restore the page table
         because the ExceptionHandlerStub will
         do it for us if we return. */
     CPU::PageTable(KernelPageTable);
     InitFont();
     /* First check the exception */
     if (unlikely(Frame->InterruptNumber == CPU::x86::DoubleFault))
     {
         ExceptionLock.store(true, std::memory_order_release);
         HandleUnrecoverableException(Frame);
     }
     if (Frame->cs == GDT_USER_CODE && Frame->ss == GDT_USER_DATA)
     {
         if (UserModeExceptionHandler(Frame))
             goto ExceptionExit;
         CPUData *core = GetCurrentCPU();
         if (likely(core->CurrentThread->Security.IsCritical == false))
             TaskManager->Yield();
         error("Critical thread \"%s\"(%d) died",
               core->CurrentThread->Name,
               core->CurrentThread->ID);
     }
     debug("-----------------------------------------------------------------------------------");
     error("Exception: %#x", Frame->InterruptNumber);
     debug("%ld MiB / %ld MiB (%ld MiB Reserved)",
           TO_MiB(KernelAllocator.GetUsedMemory()),
           TO_MiB(KernelAllocator.GetTotalMemory()),
           TO_MiB(KernelAllocator.GetReservedMemory()));
     if (ExceptionLock.load(std::memory_order_acquire))
         HandleExceptionInsideException(Frame);
     ExceptionLock.store(true, std::memory_order_release);
     {
         const char msg[] = "Entering in panic mode...";
         size_t msgLen = strlen(msg);
         size_t msgPixels = msgLen * CrashFontRenderer.CurrentFont->GetInfo().Width;
         uint32_t x = uint32_t((Display->GetWidth - msgPixels) / 2);
         uint32_t y = uint32_t((Display->GetHeight - CrashFontRenderer.CurrentFont->GetInfo().Height) / 2);
         x /= CrashFontRenderer.CurrentFont->GetInfo().Width;
         y /= CrashFontRenderer.CurrentFont->GetInfo().Height;
         printf("\x1b[2J\x1b[%d;%dH", y, x);
         printf("\x1b[30;41m%s\x1b[0m\x1b[H", msg);
     }
     if (DriverManager)
         DriverManager->Panic();
     if (TaskManager)
         TaskManager->Panic();
     Interrupts::RemoveAll();
     HaltAllCores();
     ForceUnlock = true;
     DisplayCrashScreen(Frame);
     CPU::Stop();
 ExceptionExit:
     ExceptionLock.store(false, std::memory_order_release);
 }
References CrashFontRenderer, KernelConsole::FontRenderer::CurrentFont, CPUData::CurrentThread, debug, Display, DisplayCrashScreen(), CPU::x86::DoubleFault, DriverManager, error, ExceptionLock, ForceUnlock, GDT_USER_CODE, GDT_USER_DATA, GetCurrentCPU(), Video::Display::GetHeight, Video::Font::GetInfo(), Video::Display::GetWidth, HaltAllCores(), HandleExceptionInsideException(), HandleUnrecoverableException(), Video::FontInfo::Height, InitFont(), KernelAllocator, KernelPageTable, likely, memory_order_acquire, memory_order_release, CPU::PageTable(), Driver::Manager::Panic(), Tasking::Task::Panic(), printf, Interrupts::RemoveAll(), CPU::Stop(), strlen(), TaskManager, TO_MiB, unlikely, UserModeExceptionHandler(), Video::FontInfo::Width, and Tasking::Task::Yield().
Referenced by ExceptionHandler().
HandleExceptionInsideException()
nsa __noreturn void HandleExceptionInsideException (CPU::ExceptionFrame * Frame)
Definition at line 231 of file handler.cpp.
 {
     ExPrint("\x1b[0m-----------------------------------------------\n");
     ExPrint("Exception inside exception: %#lx at %#lx\n",
             Frame->InterruptNumber,
 #if defined(a64)
             Frame->rip);
 #elif defined(a32)
             Frame->eip);
 #elif defined(aa64)
             Frame->pc);
 #endif
 #if defined(a86)
     ExPrint("CR0=%#lx CR2=%#lx CR3=%#lx CR4=%#lx CR8=%#lx\n",
             Frame->cr0, Frame->cr2, Frame->cr3, Frame->cr4, Frame->cr8);
     ExPrint("DR0=%#lx DR1=%#lx DR2=%#lx DR3=%#lx DR6=%#lx DR7=%#lx\n",
             Frame->dr0, Frame->dr1, Frame->dr2, Frame->dr3, Frame->dr6, Frame->dr7);
     ExPrint("GS=%#lx FS=%#lx ES=%#lx DS=%#lx SS=%#lx CS=%#lx\n",
             Frame->gs, Frame->fs, Frame->es, Frame->ds, Frame->ss, Frame->cs);
 #endif
 #if defined(a64)
     ExPrint("R8=%#lx R9=%#lx R10=%#lx R11=%#lx R12=%#lx R13=%#lx R14=%#lx R15=%#lx\n",
             Frame->r8, Frame->r9, Frame->r10, Frame->r11, Frame->r12, Frame->r13,
             Frame->r14, Frame->r15);
 #endif
 #if defined(a86)
     ExPrint("AX=%#lx BX=%#lx CX=%#lx DX=%#lx SI=%#lx DI=%#lx BP=%#lx SP=%#lx\n",
 #ifdef a64
             Frame->rax, Frame->rbx, Frame->rcx, Frame->rdx, Frame->rsi, Frame->rdi,
             Frame->rbp, Frame->rsp);
 #else
             Frame->eax, Frame->ebx, Frame->ecx, Frame->edx, Frame->esi, Frame->edi,
             Frame->ebp, Frame->esp);
 #endif /* a64 */
     ExPrint("IP=%#lx FL=%#lx INT=%#lx ERR=%#lx\n",
 #ifdef a64
             Frame->rip, Frame->rflags.raw,
 #else
             Frame->eip, Frame->eflags.raw,
 #endif /* a64 */
             Frame->InterruptNumber, Frame->ErrorCode);
 #endif /* a86 */
     Display->UpdateBuffer();
     CPU::Stop();
 }
References Display, ExPrint(), CPU::Stop(), and Video::Display::UpdateBuffer().
Referenced by HandleException().
HandleStackSmashing()
nsa __noreturn void HandleStackSmashing ()
Definition at line 384 of file handler.cpp.
 {
     BaseBufferStackError(true);
     DisplayStackSmashing();
     CPU::Stop();
 }
References BaseBufferStackError(), DisplayStackSmashing(), and CPU::Stop().
Referenced by __stack_chk_fail().
HandleUnrecoverableException()
nsa __noreturn void HandleUnrecoverableException (CPU::ExceptionFrame * Frame)
Definition at line 170 of file handler.cpp.
 {
     static int setOnce = 0;
     if (!setOnce++) /* FIXME: SMP */
     {
         for (uint32_t x = 0; x < Display->GetWidth; x++)
             for (uint32_t y = 0; y < Display->GetHeight; y++)
                 Display->SetPixel(x, y, 0xFF250500);
         ExPrint("\x1b[H");
     }
     CPUData *core = GetCurrentCPU();
     while (UnrecoverableLock.exchange(true, std::memory_order_acquire))
         CPU::Pause();
     ExPrint("\x1b[0m-----------------------------------------------\n");
     ExPrint("\x1b[30;41mUnrecoverable exception %#lx on CPU %d\n",
             Frame->InterruptNumber, core->ID);
 #if defined(a86)
     ExPrint("CR0=%#lx CR2=%#lx CR3=%#lx CR4=%#lx CR8=%#lx\n",
             Frame->cr0, Frame->cr2, Frame->cr3, Frame->cr4, Frame->cr8);
     ExPrint("DR0=%#lx DR1=%#lx DR2=%#lx DR3=%#lx DR6=%#lx DR7=%#lx\n",
             Frame->dr0, Frame->dr1, Frame->dr2, Frame->dr3, Frame->dr6, Frame->dr7);
     ExPrint("GS=%#lx FS=%#lx ES=%#lx DS=%#lx SS=%#lx CS=%#lx\n",
             Frame->gs, Frame->fs, Frame->es, Frame->ds, Frame->ss, Frame->cs);
 #endif
 #if defined(a64)
     ExPrint("R8=%#lx R9=%#lx R10=%#lx R11=%#lx R12=%#lx R13=%#lx R14=%#lx R15=%#lx\n",
             Frame->r8, Frame->r9, Frame->r10, Frame->r11, Frame->r12, Frame->r13,
             Frame->r14, Frame->r15);
 #endif
 #if defined(a86)
     ExPrint("AX=%#lx BX=%#lx CX=%#lx DX=%#lx SI=%#lx DI=%#lx BP=%#lx SP=%#lx\n",
 #ifdef a64
             Frame->rax, Frame->rbx, Frame->rcx, Frame->rdx, Frame->rsi, Frame->rdi,
             Frame->rbp, Frame->rsp);
 #else
             Frame->eax, Frame->ebx, Frame->ecx, Frame->edx, Frame->esi, Frame->edi,
             Frame->ebp, Frame->esp);
 #endif /* a64 */
     ExPrint("IP=%#lx FL=%#lx INT=%#lx ERR=%#lx\n",
 #ifdef a64
             Frame->rip, Frame->rflags.raw,
 #else
             Frame->eip, Frame->eflags.raw,
 #endif /* a64 */
             Frame->InterruptNumber, Frame->ErrorCode);
 #endif /* a86 */
     Display->UpdateBuffer();
     error("Unrecoverable Exception: %#lx", Frame->InterruptNumber);
     UnrecoverableLock.store(false, std::memory_order_release);
     CPU::Stop();
 }
References Display, error, ExPrint(), GetCurrentCPU(), Video::Display::GetHeight, Video::Display::GetWidth, CPUData::ID, memory_order_acquire, memory_order_release, CPU::Pause(), Video::Display::SetPixel(), CPU::Stop(), UnrecoverableLock, and Video::Display::UpdateBuffer().
Referenced by HandleException().
InitFont()
nsa void InitFont ()
Definition at line 138 of file handler.cpp.
 {
     /* Hope we won't crash here */
     if (Display == nullptr)
     {
         error("Can't initialize font without display initalized");
         CPU::Stop();
     }
     if (FbBeforePanic == nullptr)
     {
         FbPagesBeforePanic = TO_PAGES(Display->GetSize);
         FbBeforePanic = KernelAllocator.RequestPages(FbPagesBeforePanic);
         debug("Created before panic framebuffer at %#lx", FbBeforePanic);
     }
     memcpy(FbBeforePanic, Display->GetBuffer, Display->GetSize);
     if (CrashFontRenderer.CurrentFont == nullptr)
         CrashFontRenderer.CurrentFont = new Video::Font(&_binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_start,
                                                         &_binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_end,
                                                         Video::FontType::PCScreenFont2);
     if (Terminals[15] == nullptr)
     {
         size_t Cols = Display->GetWidth / CrashFontRenderer.CurrentFont->GetInfo().Width;
         size_t Rows = Display->GetHeight / CrashFontRenderer.CurrentFont->GetInfo().Height;
         Terminals[15] = new VirtualTerminal(Cols, Rows, Display->GetWidth, Display->GetHeight, paint_callback, nullptr);
     }
 }
References _binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_end, _binary_files_tamsyn_font_1_11_Tamsyn8x16b_psf_start, CrashFontRenderer, KernelConsole::FontRenderer::CurrentFont, debug, Display, error, FbBeforePanic, FbPagesBeforePanic, Video::Display::GetBuffer, Video::Display::GetHeight, Video::Font::GetInfo(), Video::Display::GetSize, Video::Display::GetWidth, Video::FontInfo::Height, KernelAllocator, memcpy(), KernelConsole::paint_callback(), Video::PCScreenFont2, CPU::Stop(), KernelConsole::Terminals, TO_PAGES, and Video::FontInfo::Width.
Referenced by DisplayAssertionFailed(), DisplayBufferOverflow(), DisplayStackSmashing(), and HandleException().
paint_callback()
void paint_callback (TerminalCell * cell, long x, long y)
Definition at line 77 of file handler.cpp.
 {
     if (cell->attr.Bright)
         CrashFontRenderer.Paint(x, y, cell->c, ExTermBrightColors[cell->attr.Foreground], ExTermColors[cell->attr.Background]);
     else
         CrashFontRenderer.Paint(x, y, cell->c, ExTermColors[cell->attr.Foreground], ExTermColors[cell->attr.Background]);
 }
References KernelConsole::TerminalCell::attr, KernelConsole::TerminalAttribute::Background, KernelConsole::TerminalAttribute::Bright, KernelConsole::TerminalCell::c, CrashFontRenderer, ExTermBrightColors, ExTermColors, KernelConsole::TerminalAttribute::Foreground, and KernelConsole::FontRenderer::Paint().
UserModeExceptionHandler()
bool UserModeExceptionHandler (CPU::ExceptionFrame * Frame)
Definition at line 75 of file user.cpp.
 {
     CPUData *core = GetCurrentCPU();
     Tasking::PCB *proc = core->CurrentProcess;
     Tasking::TCB *thread = core->CurrentThread;
     debug("Current process %s(%d) and thread %s(%d)",
           proc->Name, proc->ID, thread->Name, thread->ID);
     thread->SetState(Tasking::Waiting);
 #ifdef DEBUG
     dbgPrint(Frame);
 #endif
     int sigRet = -1;
     switch (Frame->InterruptNumber)
     {
     case CPU::x86::PageFault:
     {
         bool Handled = proc->vma->HandleCoW(Frame->cr2);
         if (!Handled)
             Handled = thread->Stack->Expand(Frame->cr2);
         if (likely(Handled))
         {
             debug("Page fault handled");
             Frame->cr2 = 0;
             thread->SetState(Tasking::Ready);
             return true;
         }
         sigRet = proc->Signals.SendSignal(SIGSEGV,
                                           {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::Debug:
     case CPU::x86::Breakpoint:
     {
         sigRet = proc->Signals.SendSignal(SIGTRAP,
                                           {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::DivideByZero:
     case CPU::x86::Overflow:
     case CPU::x86::BoundRange:
     case CPU::x86::x87FloatingPoint:
     case CPU::x86::SIMDFloatingPoint:
     {
         sigRet = proc->Signals.SendSignal(SIGFPE,
                                           {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::InvalidOpcode:
     case CPU::x86::GeneralProtectionFault:
     {
         sigRet = proc->Signals.SendSignal(SIGILL,
                                           {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::DeviceNotAvailable:
     {
         sigRet = proc->Signals.SendSignal(SIGBUS,
                                           {Tasking::KILL_CRASH});
         break;
     }
     case CPU::x86::NonMaskableInterrupt:
     case CPU::x86::DoubleFault:
     case CPU::x86::CoprocessorSegmentOverrun:
     case CPU::x86::InvalidTSS:
     case CPU::x86::SegmentNotPresent:
     case CPU::x86::StackSegmentFault:
     case CPU::x86::AlignmentCheck:
     case CPU::x86::MachineCheck:
     case CPU::x86::Virtualization:
     case CPU::x86::Security:
     default:
     {
         error("Unhandled exception %d on CPU %d",
               Frame->InterruptNumber, core->ID);
         break;
     }
     }
     if (sigRet == 0)
     {
         trace("User mode exception handler handled");
         thread->SetState(Tasking::Ready);
         return true;
     }
     error("User mode exception handler failed");
     return false;
 }
References CPU::x86::AlignmentCheck, CPU::x86::BoundRange, CPU::x86::Breakpoint, CPU::x86::CoprocessorSegmentOverrun, CPUData::CurrentProcess, CPUData::CurrentThread, CPU::x86::Debug, debug, CPU::x86::DeviceNotAvailable, CPU::x86::DivideByZero, CPU::x86::DoubleFault, error, Memory::StackGuard::Expand(), CPU::x86::GeneralProtectionFault, GetCurrentCPU(), Memory::VirtualMemoryArea::HandleCoW(), CPUData::ID, Tasking::TCB::ID, Tasking::PCB::ID, CPU::x86::InvalidOpcode, CPU::x86::InvalidTSS, Tasking::KILL_CRASH, likely, CPU::x86::MachineCheck, Tasking::TCB::Name, Tasking::PCB::Name, CPU::x86::NonMaskableInterrupt, CPU::x86::Overflow, CPU::x86::PageFault, Tasking::Ready, CPU::x86::Security, CPU::x86::SegmentNotPresent, Tasking::Signal::SendSignal(), Tasking::TCB::SetState(), SIGBUS, SIGFPE, SIGILL, Tasking::PCB::Signals, SIGSEGV, SIGTRAP, CPU::x86::SIMDFloatingPoint, Tasking::TCB::Stack, CPU::x86::StackSegmentFault, trace, CPU::x86::Virtualization, Tasking::PCB::vma, Tasking::Waiting, and CPU::x86::x87FloatingPoint.
Referenced by HandleException().
Variable Documentation
CrashFontRenderer
FontRenderer CrashFontRenderer
Definition at line 53 of file handler.cpp.
Referenced by BaseBufferStackError(), CrashPS2KeyboardDriver::CrashPS2KeyboardDriver(), DisplayBottomOverlay(), HandleException(), InitFont(), paint_callback(), and UserInput().
ExceptionLock
std::atomic<bool> ExceptionLock = false
Definition at line 280 of file handler.cpp.
Referenced by BaseBufferStackError(), HandleException(), and ACPI::DSDT::OnInterruptReceived().
ExTermBrightColors
int ExTermBrightColors[]
Initial value:
= {
    [TerminalColor::BLACK] = 0x858585,
    [TerminalColor::RED] = 0xFF5555,
    [TerminalColor::GREEN] = 0x55FF55,
    [TerminalColor::YELLOW] = 0xFFFF55,
    [TerminalColor::BLUE] = 0x5555FF,
    [TerminalColor::MAGENTA] = 0xFF55FF,
    [TerminalColor::CYAN] = 0x55FFFF,
    [TerminalColor::GREY] = 0xFFFFFF,
}
Definition at line 66 of file handler.cpp.
Referenced by paint_callback().
ExTermColors
int ExTermColors[]
Initial value:
= {
    [TerminalColor::BLACK] = 0x000000,
    [TerminalColor::RED] = 0xAA0000,
    [TerminalColor::GREEN] = 0x00AA00,
    [TerminalColor::YELLOW] = 0xAA5500,
    [TerminalColor::BLUE] = 0x0000AA,
    [TerminalColor::MAGENTA] = 0xAA00AA,
    [TerminalColor::CYAN] = 0x00AAAA,
    [TerminalColor::GREY] = 0xAAAAAA,
}
Definition at line 55 of file handler.cpp.
Referenced by paint_callback().
FbBeforePanic
void* FbBeforePanic = nullptr
Definition at line 51 of file handler.cpp.
Referenced by InitFont(), and UserInput().
FbPagesBeforePanic
size_t FbPagesBeforePanic = 0
Definition at line 52 of file handler.cpp.
Referenced by InitFont().
UnrecoverableLock
std::atomic<bool> UnrecoverableLock = false
Definition at line 169 of file handler.cpp.
Referenced by HandleUnrecoverableException().
x86ExceptionMnemonics
const char* x86ExceptionMnemonics[] extern