Fennix: Userspace/apps/base/busybox/libbb/pidfile.c File Reference
pidfile.c File Reference
#include "libbb.h"
Macros
#define WANT_PIDFILE 1
Functions
void FAST_FUNC write_pidfile (const char *path)
void FAST_FUNC write_pidfile_std_path_and_ext (const char *name)
void FAST_FUNC remove_pidfile_std_path_and_ext (const char *name)
Variables
smallint wrote_pidfile
Macro Definition Documentation
WANT_PIDFILE
#define WANT_PIDFILE 1
Definition at line 11 of file pidfile.c.
Function Documentation
remove_pidfile_std_path_and_ext()
void FAST_FUNC remove_pidfile_std_path_and_ext (const char * name)
Definition at line 50 of file pidfile.c.
 {
     char buf[sizeof(CONFIG_PID_FILE_PATH) + 64];
     if (!wrote_pidfile)
         return;
     snprintf(buf, sizeof(buf), CONFIG_PID_FILE_PATH"/%s.pid", name);
     unlink(buf);
 }
References buf, snprintf(), unlink(), and wrote_pidfile.
Referenced by clean_up_and_exit(), do_syslogd(), klogd_main(), ntpd_main(), and shutdown_on_signal().
write_pidfile()
void FAST_FUNC write_pidfile (const char * path)
Definition at line 16 of file pidfile.c.
 {
     int pid_fd;
     char *end;
     char buf[sizeof(int)*3 + 2];
     struct stat sb;
     if (!path)
         return;
     /* we will overwrite stale pidfile */
     pid_fd = open(path, O_WRONLY|O_CREAT|O_TRUNC, 0666);
     if (pid_fd < 0)
         return;
     /* path can be "/dev/null"! Test for such cases */
     wrote_pidfile = (fstat(pid_fd, &sb) == 0) && S_ISREG(sb.st_mode);
     if (wrote_pidfile) {
         /* few bytes larger, but doesn't use stdio */
         end = utoa_to_buf(getpid(), buf, sizeof(buf));
         *end = '\n';
         full_write(pid_fd, buf, end - buf + 1);
     }
     close(pid_fd);
 }
References buf, close(), end, fstat(), full_write(), getpid(), O_CREAT, O_TRUNC, O_WRONLY, open(), S_ISREG, stat::st_mode, utoa_to_buf(), and wrote_pidfile.
Referenced by acpid_main(), ifplugd_main(), start_stop_daemon_main(), udhcpc6_main(), udhcpc_main(), udhcpd_main(), and write_pidfile_std_path_and_ext().
write_pidfile_std_path_and_ext()
void FAST_FUNC write_pidfile_std_path_and_ext (const char * name)
Definition at line 42 of file pidfile.c.
 {
     char buf[sizeof(CONFIG_PID_FILE_PATH) + 64];
     snprintf(buf, sizeof(buf), CONFIG_PID_FILE_PATH"/%s.pid", name);
     write_pidfile(buf);
 }
References buf, snprintf(), and write_pidfile().
Referenced by crond_main(), do_syslogd(), inetd_main(), klogd_main(), ntp_init(), and watchdog_main().
Variable Documentation
wrote_pidfile
smallint wrote_pidfile
Definition at line 14 of file pidfile.c.
Referenced by remove_pidfile_std_path_and_ext(), and write_pidfile().