Fennix Userspace: Userspace/apps/base/busybox/miscutils/time.c File Reference
time.c File Reference
#include "libbb.h"
Data Structures
struct resource_t
Macros
#define UL unsigned long
#define TICKS_PER_SEC 100
#define O_CLOEXEC 0
Functions
static pid_t wait3 (int *status, int options, struct rusage *rusage)
static void resuse_end (pid_t pid, resource_t *resp)
static void printargv (char *const *argv)
static unsigned long ptok (const unsigned pagesize, const unsigned long pages)
static void summarize (const char *fmt, char **command, resource_t *resp)
static void run_command (char *const *cmd, resource_t *resp)
int time_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char default_format[] ALIGN1 = "real\t%E\nuser\t%u\nsys\t%T"
Data Structure Documentation
resource_t
struct resource_t
Definition at line 44 of file time.c.
Data Fields
unsigned elapsed_ms
struct rusage ru
int waitstatus
Macro Definition Documentation
O_CLOEXEC
#define O_CLOEXEC 0
TICKS_PER_SEC
#define TICKS_PER_SEC 100
Definition at line 185 of file time.c.
UL
#define UL unsigned long
Definition at line 53 of file time.c.
Function Documentation
printargv()
static void printargv (char *const * argv) static
Definition at line 105 of file time.c.
 {
     const char *fmt = " %s" + 1;
     do {
         printf(fmt, *argv);
         fmt = " %s";
     } while (*++argv);
 }
References argv, and printf().
Referenced by summarize().
ptok()
static unsigned long ptok (const unsigned pagesize, const unsigned long pages) static
Definition at line 125 of file time.c.
 {
     unsigned long tmp;
     /* Conversion.  */
     if (pages > (LONG_MAX / pagesize)) { /* Could overflow.  */
         tmp = pages / 1024;     /* Smaller first, */
         return tmp * pagesize;  /* then larger.  */
     }
     /* Could underflow.  */
     tmp = pages * pagesize; /* Larger first, */
     return tmp / 1024;      /* then smaller.  */
 }
References LONG_MAX.
Referenced by summarize().
resuse_end()
static void resuse_end (pid_t pid, resource_t * resp) static
Definition at line 90 of file time.c.
 {
     pid_t caught;
     /* Ignore signals, but don't ignore the children.  When wait3
      * returns the child process, set the time the command finished. */
     while ((caught = wait3(&resp->waitstatus, 0, &resp->ru)) != pid) {
         if (caught == -1 && errno != EINTR) {
             bb_simple_perror_msg("wait");
             return;
         }
     }
     resp->elapsed_ms = monotonic_ms() - resp->elapsed_ms;
 }
References bb_simple_perror_msg(), EINTR, resource_t::elapsed_ms, errno, monotonic_ms(), pid, resource_t::ru, wait3(), and resource_t::waitstatus.
Referenced by run_command().
run_command()
static void run_command (char *const * cmd, resource_t * resp) static
Definition at line 402 of file time.c.
 {
     pid_t pid;
     void (*interrupt_signal)(int);
     void (*quit_signal)(int);
     resp->elapsed_ms = monotonic_ms();
     pid = xvfork();
     if (pid == 0) {
         /* Child */
         BB_EXECVP_or_die((char**)cmd);
     }
     /* Have signals kill the child but not self (if possible).  */
 //TODO: just block all sigs? and re-enable them in the very end in main?
     interrupt_signal = signal(SIGINT, SIG_IGN);
     quit_signal = signal(SIGQUIT, SIG_IGN);
     resuse_end(pid, resp);
     /* Re-enable signals.  */
     signal(SIGINT, interrupt_signal);
     signal(SIGQUIT, quit_signal);
 }
References BB_EXECVP_or_die(), cmd, resource_t::elapsed_ms, monotonic_ms(), pid, resuse_end(), SIG_IGN, SIGINT, signal, SIGQUIT, and xvfork.
Referenced by time_main().
summarize()
static void summarize (const char * fmt, char ** command, resource_t * resp) static
Definition at line 188 of file time.c.
 {
     unsigned vv_ms;     /* Elapsed virtual (CPU) milliseconds */
     unsigned cpu_ticks; /* Same, in "CPU ticks" */
     unsigned pagesize = bb_getpagesize();
     /* Impossible: we do not use WUNTRACED flag in wait()...
     if (WIFSTOPPED(resp->waitstatus))
         printf("Command stopped by signal %u\n",
                 WSTOPSIG(resp->waitstatus));
     else */
     if (WIFSIGNALED(resp->waitstatus))
         printf("Command terminated by signal %u\n",
                 WTERMSIG(resp->waitstatus));
     else if (WIFEXITED(resp->waitstatus) && WEXITSTATUS(resp->waitstatus))
         printf("Command exited with non-zero status %u\n",
                 WEXITSTATUS(resp->waitstatus));
     vv_ms = (resp->ru.ru_utime.tv_sec + resp->ru.ru_stime.tv_sec) * 1000
           + (resp->ru.ru_utime.tv_usec + resp->ru.ru_stime.tv_usec) / 1000;
 #if (1000 / TICKS_PER_SEC) * TICKS_PER_SEC == 1000
     /* 1000 is exactly divisible by TICKS_PER_SEC (typical) */
     cpu_ticks = vv_ms / (1000 / TICKS_PER_SEC);
 #else
     cpu_ticks = vv_ms * (unsigned long long)TICKS_PER_SEC / 1000;
 #endif
     if (!cpu_ticks) cpu_ticks = 1; /* we divide by it, must be nonzero */
     while (*fmt) {
         /* Handle leading literal part */
         int n = strcspn(fmt, "%\\");
         if (n) {
             printf("%.*s", n, fmt);
             fmt += n;
             continue;
         }
         switch (*fmt) {
 #ifdef NOT_NEEDED
         /* Handle literal char */
         /* Usually we optimize for size, but there is a limit
          * for everything. With this we do a lot of 1-byte writes */
         default:
             bb_putchar(*fmt);
             break;
 #endif
         case '%':
             switch (*++fmt) {
 #ifdef NOT_NEEDED_YET
         /* Our format strings do not have these */
         /* and we do not take format str from user */
             default:
                 bb_putchar('%');
                 /*FALLTHROUGH*/
             case '%':
                 if (!*fmt) goto ret;
                 bb_putchar(*fmt);
                 break;
 #endif
             case 'C':   /* The command that got timed.  */
                 printargv(command);
                 break;
             case 'D':   /* Average unshared data size.  */
                 printf("%lu",
                     (ptok(pagesize, (UL) resp->ru.ru_idrss) +
                      ptok(pagesize, (UL) resp->ru.ru_isrss)) / cpu_ticks);
                 break;
             case 'E': { /* Elapsed real (wall clock) time.  */
                 unsigned seconds = resp->elapsed_ms / 1000;
                 if (seconds >= 3600)    /* One hour -> h:m:s.  */
                     printf("%uh %um %02us",
                             seconds / 3600,
                             (seconds % 3600) / 60,
                             seconds % 60);
                 else
                     printf("%um %u.%02us",  /* -> m:s.  */
                             seconds / 60,
                             seconds % 60,
                             (unsigned)(resp->elapsed_ms / 10) % 100);
                 break;
             }
             case 'F':   /* Major page faults.  */
                 printf("%lu", resp->ru.ru_majflt);
                 break;
             case 'I':   /* Inputs.  */
                 printf("%lu", resp->ru.ru_inblock);
                 break;
             case 'K':   /* Average mem usage == data+stack+text.  */
                 printf("%lu",
                     (ptok(pagesize, (UL) resp->ru.ru_idrss) +
                      ptok(pagesize, (UL) resp->ru.ru_isrss) +
                      ptok(pagesize, (UL) resp->ru.ru_ixrss)) / cpu_ticks);
                 break;
             case 'M':   /* Maximum resident set size.  */
                 printf("%lu", ptok(pagesize, (UL) resp->ru.ru_maxrss));
                 break;
             case 'O':   /* Outputs.  */
                 printf("%lu", resp->ru.ru_oublock);
                 break;
             case 'P':   /* Percent of CPU this job got.  */
                 /* % cpu is (total cpu time)/(elapsed time).  */
                 if (resp->elapsed_ms > 0)
                     printf("%u%%", (unsigned)(vv_ms * 100 / resp->elapsed_ms));
                 else
                     printf("?%%");
                 break;
             case 'R':   /* Minor page faults (reclaims).  */
                 printf("%lu", resp->ru.ru_minflt);
                 break;
             case 'S':   /* System time.  */
                 printf("%u.%02u",
                         (unsigned)resp->ru.ru_stime.tv_sec,
                         (unsigned)(resp->ru.ru_stime.tv_usec / 10000));
                 break;
             case 'T':   /* System time.  */
                 if (resp->ru.ru_stime.tv_sec >= 3600) /* One hour -> h:m:s.  */
                     printf("%uh %um %02us",
                             (unsigned)(resp->ru.ru_stime.tv_sec / 3600),
                             (unsigned)(resp->ru.ru_stime.tv_sec % 3600) / 60,
                             (unsigned)(resp->ru.ru_stime.tv_sec % 60));
                 else
                     printf("%um %u.%02us",  /* -> m:s.  */
                             (unsigned)(resp->ru.ru_stime.tv_sec / 60),
                             (unsigned)(resp->ru.ru_stime.tv_sec % 60),
                             (unsigned)(resp->ru.ru_stime.tv_usec / 10000));
                 break;
             case 'U':   /* User time.  */
                 printf("%u.%02u",
                         (unsigned)resp->ru.ru_utime.tv_sec,
                         (unsigned)(resp->ru.ru_utime.tv_usec / 10000));
                 break;
             case 'u':   /* User time.  */
                 if (resp->ru.ru_utime.tv_sec >= 3600) /* One hour -> h:m:s.  */
                     printf("%uh %um %02us",
                             (unsigned)(resp->ru.ru_utime.tv_sec / 3600),
                             (unsigned)(resp->ru.ru_utime.tv_sec % 3600) / 60,
                             (unsigned)(resp->ru.ru_utime.tv_sec % 60));
                 else
                     printf("%um %u.%02us",  /* -> m:s.  */
                             (unsigned)(resp->ru.ru_utime.tv_sec / 60),
                             (unsigned)(resp->ru.ru_utime.tv_sec % 60),
                             (unsigned)(resp->ru.ru_utime.tv_usec / 10000));
                 break;
             case 'W':   /* Times swapped out.  */
                 printf("%lu", resp->ru.ru_nswap);
                 break;
             case 'X':   /* Average shared text size.  */
                 printf("%lu", ptok(pagesize, (UL) resp->ru.ru_ixrss) / cpu_ticks);
                 break;
             case 'Z':   /* Page size.  */
                 printf("%u", pagesize);
                 break;
             case 'c':   /* Involuntary context switches.  */
                 printf("%lu", resp->ru.ru_nivcsw);
                 break;
             case 'e':   /* Elapsed real time in seconds.  */
                 printf("%u.%02u",
                         (unsigned)resp->elapsed_ms / 1000,
                         (unsigned)(resp->elapsed_ms / 10) % 100);
                 break;
             case 'k':   /* Signals delivered.  */
                 printf("%lu", resp->ru.ru_nsignals);
                 break;
             case 'p':   /* Average stack segment.  */
                 printf("%lu", ptok(pagesize, (UL) resp->ru.ru_isrss) / cpu_ticks);
                 break;
             case 'r':   /* Incoming socket messages received.  */
                 printf("%lu", resp->ru.ru_msgrcv);
                 break;
             case 's':   /* Outgoing socket messages sent.  */
                 printf("%lu", resp->ru.ru_msgsnd);
                 break;
             case 't':   /* Average resident set size.  */
                 printf("%lu", ptok(pagesize, (UL) resp->ru.ru_idrss) / cpu_ticks);
                 break;
             case 'w':   /* Voluntary context switches.  */
                 printf("%lu", resp->ru.ru_nvcsw);
                 break;
             case 'x':   /* Exit status.  */
                 printf("%u", WEXITSTATUS(resp->waitstatus));
                 break;
             }
             break;
 #ifdef NOT_NEEDED_YET
         case '\\':      /* Format escape.  */
             switch (*++fmt) {
             default:
                 bb_putchar('\\');
                 /*FALLTHROUGH*/
             case '\\':
                 if (!*fmt) goto ret;
                 bb_putchar(*fmt);
                 break;
             case 't':
                 bb_putchar('\t');
                 break;
             case 'n':
                 bb_putchar('\n');
                 break;
             }
             break;
 #endif
         }
         ++fmt;
     }
  /* ret: */
     bb_putchar('\n');
 }
References bb_getpagesize, bb_putchar(), resource_t::elapsed_ms, n, printargv(), printf(), ptok(), resource_t::ru, rusage::ru_idrss, rusage::ru_inblock, rusage::ru_isrss, rusage::ru_ixrss, rusage::ru_majflt, rusage::ru_maxrss, rusage::ru_minflt, rusage::ru_msgrcv, rusage::ru_msgsnd, rusage::ru_nivcsw, rusage::ru_nsignals, rusage::ru_nswap, rusage::ru_nvcsw, rusage::ru_oublock, rusage::ru_stime, rusage::ru_utime, strcspn(), TICKS_PER_SEC, timeval::tv_sec, timeval::tv_usec, UL, resource_t::waitstatus, WEXITSTATUS, WIFEXITED, WIFSIGNALED, and WTERMSIG.
Referenced by time_main().
time_main()
int time_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 428 of file time.c.
 {
     resource_t res;
     /* $TIME has lowest prio (-v,-p,-f FMT overrride it) */
     const char *output_format = getenv("TIME") ? : default_format;
     char *output_filename;
     int output_fd;
     int opt;
     int ex;
     enum {
         OPT_v = (1 << 0),
         OPT_p = (1 << 1),
         OPT_a = (1 << 2),
         OPT_o = (1 << 3),
         OPT_f = (1 << 4),
     };
     /* "+": stop on first non-option */
     opt = getopt32(argv, "^+" "vpao:f:" "\0" "-1"/*at least one arg*/,
                 &output_filename, &output_format
     );
     argv += optind;
     if (opt & OPT_v)
         output_format = long_format;
     if (opt & OPT_p)
         output_format = posix_format;
     output_fd = STDERR_FILENO;
     if (opt & OPT_o) {
 #ifndef O_CLOEXEC
 # define O_CLOEXEC 0
 #endif
         output_fd = xopen(output_filename,
             (opt & OPT_a) /* append? */
             ? (O_CREAT | O_WRONLY | O_CLOEXEC | O_APPEND)
             : (O_CREAT | O_WRONLY | O_CLOEXEC | O_TRUNC)
         );
         if (!O_CLOEXEC)
             close_on_exec_on(output_fd);
     }
     run_command(argv, &res);
     /* Cheat. printf's are shorter :) */
     xdup2(output_fd, STDOUT_FILENO);
     summarize(output_format, argv, &res);
     ex = WEXITSTATUS(res.waitstatus);
     /* Impossible: we do not use WUNTRACED flag in wait()...
     if (WIFSTOPPED(res.waitstatus))
         ex = WSTOPSIG(res.waitstatus);
     */
     if (WIFSIGNALED(res.waitstatus))
         ex = WTERMSIG(res.waitstatus);
     fflush_stdout_and_exit(ex);
 }
References argv, close_on_exec_on(), fflush_stdout_and_exit(), getenv, getopt32(), O_APPEND, O_CLOEXEC, O_CREAT, O_TRUNC, O_WRONLY, opt, OPT_a, OPT_f, OPT_o, OPT_p, OPT_v, optind, run_command(), STDERR_FILENO, STDOUT_FILENO, summarize(), resource_t::waitstatus, WEXITSTATUS, WIFSIGNALED, WTERMSIG, xdup2(), and xopen().
wait3()
static pid_t wait3 (int * status, int options, struct rusage * rusage) static
Definition at line 37 of file time.c.
 {
     return wait4(-1, status, options, rusage);
 }
References status, and wait4().
Referenced by resuse_end().
Variable Documentation
ALIGN1
const char long_format [] ALIGN1 = "real\t%E\nuser\t%u\nsys\t%T" static
Definition at line 55 of file time.c.
Referenced by parse_datestr().