Fennix: Userspace/apps/base/busybox/archival/libarchive/data_extract_to_command.c File Reference
data_extract_to_command.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Enumerations
enum {
TAR_MODE , TAR_FILENAME , TAR_REALNAME , TAR_SIZE ,
TAR_UID , TAR_GID , TAR_MAX
}
Functions
static void xputenv (char *str)
static void str2env (char *env[], int idx, const char *str)
static void dec2env (char *env[], int idx, unsigned long long val)
static void oct2env (char *env[], int idx, unsigned long val)
void FAST_FUNC data_extract_to_command (archive_handle_t *archive_handle)
Variables
static const char *const tar_var[] ALIGN_PTR
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TAR_MODE
TAR_FILENAME
TAR_REALNAME
TAR_SIZE
TAR_UID
TAR_GID
TAR_MAX
Definition at line 8 of file data_extract_to_command.c.
      {
     //TAR_FILETYPE,
     TAR_MODE,
     TAR_FILENAME,
     TAR_REALNAME,
 #if ENABLE_FEATURE_TAR_UNAME_GNAME
     TAR_UNAME,
     TAR_GNAME,
 #endif
     TAR_SIZE,
     TAR_UID,
     TAR_GID,
     TAR_MAX,
 };
Function Documentation
data_extract_to_command()
void FAST_FUNC data_extract_to_command (archive_handle_t * archive_handle)
Definition at line 61 of file data_extract_to_command.c.
 {
     file_header_t *file_header = archive_handle->file_header;
 #if 0 /* do we need this? ENABLE_FEATURE_TAR_SELINUX */
     char *sctx = archive_handle->tar__sctx[PAX_NEXT_FILE];
     if (!sctx)
         sctx = archive_handle->tar__sctx[PAX_GLOBAL];
     if (sctx) { /* setfscreatecon is 4 syscalls, avoid if possible */
         setfscreatecon(sctx);
         free(archive_handle->tar__sctx[PAX_NEXT_FILE]);
         archive_handle->tar__sctx[PAX_NEXT_FILE] = NULL;
     }
 #endif
     if ((file_header->mode & S_IFMT) == S_IFREG) {
         pid_t pid;
         int p[2], status;
         char *tar_env[TAR_MAX];
         memset(tar_env, 0, sizeof(tar_env));
         xpipe(p);
         pid = BB_MMU ? xfork() : xvfork();
         if (pid == 0) {
             /* Child */
             /* str2env(tar_env, TAR_FILETYPE, "f"); - parent should do it once */
             oct2env(tar_env, TAR_MODE, file_header->mode);
             str2env(tar_env, TAR_FILENAME, file_header->name);
             str2env(tar_env, TAR_REALNAME, file_header->name);
 #if ENABLE_FEATURE_TAR_UNAME_GNAME
             str2env(tar_env, TAR_UNAME, file_header->tar__uname);
             str2env(tar_env, TAR_GNAME, file_header->tar__gname);
 #endif
             dec2env(tar_env, TAR_SIZE, file_header->size);
             dec2env(tar_env, TAR_UID, file_header->uid);
             dec2env(tar_env, TAR_GID, file_header->gid);
             close(p[1]);
             xdup2(p[0], STDIN_FILENO);
             signal(SIGPIPE, SIG_DFL);
             execl(archive_handle->tar__to_command_shell,
                 archive_handle->tar__to_command_shell,
                 "-c",
                 archive_handle->tar__to_command,
                 (char *)0);
             bb_perror_msg_and_die("can't execute '%s'", archive_handle->tar__to_command_shell);
         }
         close(p[0]);
         /* Our caller is expected to do signal(SIGPIPE, SIG_IGN)
          * so that we don't die if child don't read all the input: */
         bb_copyfd_exact_size(archive_handle->src_fd, p[1], -file_header->size);
         close(p[1]);
         status = wait_for_exitstatus(pid);
         if (WIFEXITED(status) && WEXITSTATUS(status))
             bb_error_msg_and_die("'%s' returned status %d",
                 archive_handle->tar__to_command, WEXITSTATUS(status));
         if (WIFSIGNALED(status))
             bb_error_msg_and_die("'%s' terminated by signal %d",
                 archive_handle->tar__to_command, WTERMSIG(status));
         if (!BB_MMU) {
             int i;
             for (i = 0; i < TAR_MAX; i++) {
                 if (tar_env[i])
                     bb_unsetenv_and_free(tar_env[i]);
             }
         }
     }
 #if 0 /* ENABLE_FEATURE_TAR_SELINUX */
     if (sctx)
         /* reset the context after creating an entry */
         setfscreatecon(NULL);
 #endif
 }
References bb_copyfd_exact_size(), bb_error_msg_and_die(), BB_MMU, bb_perror_msg_and_die(), bb_unsetenv_and_free(), close(), dec2env(), execl(), archive_handle_t::file_header, free, file_header_t::gid, i, memset, file_header_t::mode, file_header_t::name, NULL, oct2env(), p, PAX_GLOBAL, PAX_NEXT_FILE, pid, S_IFMT, S_IFREG, SIG_DFL, signal, SIGPIPE, file_header_t::size, archive_handle_t::src_fd, status, STDIN_FILENO, str2env(), TAR_FILENAME, TAR_GID, TAR_MAX, TAR_MODE, TAR_REALNAME, TAR_SIZE, TAR_UID, file_header_t::uid, wait_for_exitstatus(), WEXITSTATUS, WIFEXITED, WIFSIGNALED, WTERMSIG, xdup2(), xfork(), xpipe(), and xvfork.
Referenced by tar_main().
dec2env()
static void dec2env (char * env[], int idx, unsigned long long val) static
Definition at line 49 of file data_extract_to_command.c.
 {
     env[idx] = xasprintf("TAR_%s=%llu", tar_var[idx], val);
     xputenv(env[idx]);
 }
References env, idx, val, xasprintf(), and xputenv().
Referenced by data_extract_to_command().
oct2env()
static void oct2env (char * env[], int idx, unsigned long val) static
Definition at line 55 of file data_extract_to_command.c.
 {
     env[idx] = xasprintf("TAR_%s=%lo", tar_var[idx], val);
     xputenv(env[idx]);
 }
References env, idx, val, xasprintf(), and xputenv().
Referenced by data_extract_to_command().
str2env()
static void str2env (char * env[], int idx, const char * str) static
Definition at line 43 of file data_extract_to_command.c.
 {
     env[idx] = xasprintf("TAR_%s=%s", tar_var[idx], str);
     xputenv(env[idx]);
 }
References env, idx, str, xasprintf(), and xputenv().
Referenced by data_extract_to_command().
xputenv()
static void xputenv (char * str) static
Definition at line 37 of file data_extract_to_command.c.
 {
     if (putenv(str))
         bb_die_memory_exhausted();
 }
References bb_die_memory_exhausted(), putenv(), and str.
Referenced by dec2env(), oct2env(), and str2env().
Variable Documentation
ALIGN_PTR
const char* const tar_var [] ALIGN_PTR static
Initial value:
= {
    "MODE",
    "FILENAME",
    "REALNAME",
    "SIZE",
    "UID",
    "GID",
}
Definition at line 23 of file data_extract_to_command.c.