Fennix Userspace: Userspace/libc/include/sys/wait.h File Reference
wait.h File Reference
#include <sys/types.h>
#include <bits/waitstatus.h>
Data Structures
struct siginfo_t
Macros
#define WCONTINUED 1
#define WNOHANG 2
#define WUNTRACED 4
#define WEXITED 8
#define WNOWAIT 16
#define WSTOPPED 32
#define WEXITSTATUS(status) __WEXITSTATUS(status)
Macro for extracting the exit status from a status value.
#define WTERMSIG(status) __WTERMSIG(status)
Macro for extracting the termination signal from a status value.
#define WSTOPSIG(status) __WSTOPSIG(status)
Macro for extracting the stop signal from a status value.
#define WIFEXITED(status) __WIFEXITED(status)
Macro for testing whether a process exited normally.
#define WIFSIGNALED(status) __WIFSIGNALED(status)
Macro for testing whether a process was terminated by a signal.
#define WIFSTOPPED(status) __WIFSTOPPED(status)
Macro for testing whether a process was stopped by a signal.
#define WIFCONTINUED(status) __WIFCONTINUED(status)
Macro for testing whether a stopped process was continued.
Enumerations
enum idtype_t {
P_ALL , P_PID , P_PGID , P_ALL = 0 ,
P_PID = 1 , P_PGID = 2 , P_PIDFD = 3
}
Functions
pid_t wait (int *wstatus)
pid_t waitpid (pid_t pid, int *wstatus, int options)
int waitid (idtype_t idtype, id_t id, siginfo_t *infop, int options)
Data Structure Documentation
siginfo_t
struct siginfo_t
Definition at line 13 of file wait.h.
Data Fields
int stub
Macro Definition Documentation
WCONTINUED
#define WCONTINUED 1
Definition at line 20 of file wait.h.
WEXITED
#define WEXITED 8
Definition at line 23 of file wait.h.
WEXITSTATUS
#define WEXITSTATUS (status) __WEXITSTATUS(status)
Macro for extracting the exit status from a status value.
If the child process terminated normally by calling exit(3) or _exit(2), the macro WEXITSTATUS() returns the low-order 8 bits of the status value.
Parameters
status The status value to extract the exit status from.
Returns
The exit status of the child process.
Definition at line 36 of file wait.h.
WIFCONTINUED
#define WIFCONTINUED (status) __WIFCONTINUED(status)
Macro for testing whether a stopped process was continued.
If the child process was stopped and has been resumed by delivery of SIGCONT, the macro WIFCONTINUED() returns a nonzero value. Otherwise, it returns 0.
Parameters
status The status value to test.
Returns
A nonzero value if the child process was continued, 0 otherwise.
Definition at line 102 of file wait.h.
WIFEXITED
#define WIFEXITED (status) __WIFEXITED(status)
Macro for testing whether a process exited normally.
If the child process terminated normally by calling exit(3) or _exit(2), the macro WIFEXITED() returns a nonzero value. Otherwise, it returns 0.
Parameters
status The status value to test.
Returns
A nonzero value if the child process exited normally, 0 otherwise.
Definition at line 69 of file wait.h.
WIFSIGNALED
#define WIFSIGNALED (status) __WIFSIGNALED(status)
Macro for testing whether a process was terminated by a signal.
If the child process was terminated by a signal, the macro WIFSIGNALED() returns a nonzero value. Otherwise, it returns 0.
Parameters
status The status value to test.
Returns
A nonzero value if the child process was terminated by a signal, 0 otherwise.
Definition at line 80 of file wait.h.
WIFSTOPPED
#define WIFSTOPPED (status) __WIFSTOPPED(status)
Macro for testing whether a process was stopped by a signal.
If the child process was stopped by a signal, the macro WIFSTOPPED() returns a nonzero value. Otherwise, it returns 0.
Parameters
status The status value to test.
Returns
A nonzero value if the child process was stopped by a signal, 0 otherwise.
Definition at line 91 of file wait.h.
WNOHANG
#define WNOHANG 2
Definition at line 21 of file wait.h.
WNOWAIT
#define WNOWAIT 16
Definition at line 24 of file wait.h.
WSTOPPED
#define WSTOPPED 32
Definition at line 25 of file wait.h.
WSTOPSIG
#define WSTOPSIG (status) __WSTOPSIG(status)
Macro for extracting the stop signal from a status value.
If the child process was stopped by a signal, the macro WSTOPSIG() returns the signal number of the stop signal.
Parameters
status The status value to extract the stop signal from.
Returns
The stop signal of the child process.
Definition at line 58 of file wait.h.
WTERMSIG
#define WTERMSIG (status) __WTERMSIG(status)
Macro for extracting the termination signal from a status value.
If the child process was terminated by a signal, the macro WTERMSIG() returns the signal number of the terminating signal.
Parameters
status The status value to extract the termination signal from.
Returns
The termination signal of the child process.
Definition at line 47 of file wait.h.
WUNTRACED
#define WUNTRACED 4
Definition at line 22 of file wait.h.
Enumeration Type Documentation
idtype_t
enum idtype_t
Enumerator
P_ALL
P_PID
P_PGID
P_ALL
P_PID
P_PGID
P_PIDFD
Definition at line 6 of file wait.h.
 {
     P_ALL, /* Wait for any child. */
     P_PID, /* Wait for specified process. */
     P_PGID /* Wait for members of process group. */
 } idtype_t;
Function Documentation
wait()
pid_t wait (int * wstatus)
Definition at line 3 of file wait.c.
 {
     return waitpid(-1, &wstatus, 0);
 }
References waitpid().
Referenced by check_errors_in_children(), main(), runsvdir_main(), setup_heredoc(), timeout_main(), and waitfor().
waitid()
int waitid (idtype_t idtype, id_t id, siginfo_t * infop, int options)
Definition at line 12 of file wait.c.
 {
 }
References syscall_cp, and type.
waitpid()
pid_t waitpid (pid_t pid, int * wstatus, int options)
Definition at line 8 of file wait.c.
 {
 }
Referenced by bootchartd_main(), check_completions(), checkjobs(), exec_conf(), exec_kernel_doc(), forkpty(), init_main(), pause_and_low_level_reboot(), posix_spawn(), reap(), safe_waitpid(), system(), wait_one(), and waitproc().