Fennix Kernel: Kernel/kshell/commands/lspci.cpp File Reference
lspci.cpp File Reference
#include "../cmds.hpp"
#include <filesystem.hpp>
#include "../../kernel.h"
Functions
void cmd_lspci (const char *args)
Function Documentation
cmd_lspci()
void cmd_lspci (const char * args)
Definition at line 26 of file lspci.cpp.
 {
     if (args)
     {
         if (IF_ARG("-i") || IF_ARG("--info"))
         {
             foreach (auto Device in PCIManager->GetDevices())
             {
                 const char *HdrType;
                 switch (Device.Header->HeaderType)
                 {
                 case 0:
                     HdrType = "Normal ";
                     break;
                 case 1:
                     HdrType = "PCI-PCI";
                     break;
                 case 2:
                     HdrType = "Cardbus";
                     break;
                 default:
                     HdrType = "Unknown";
                     break;
                 }
                 printf("%04x:%04x | %s:%03d | %02x:%02x.%d | %s:  %s  %s\n",
                        Device.Header->VendorID,
                        Device.Header->DeviceID,
                        HdrType, Device.Header->HeaderType,
                        Device.Bus,
                        Device.Device,
                        Device.Function,
                        PCI::Descriptors::GetSubclassName(Device.Header->Class,
                                                          Device.Header->Subclass),
                        PCI::Descriptors::GetVendorName(Device.Header->VendorID),
                        PCI::Descriptors::GetDeviceName(Device.Header->VendorID,
                                                        Device.Header->DeviceID));
             }
             return;
         }
     }
     foreach (auto Device in PCIManager->GetDevices())
     {
         printf("%02x:%02x.%d: %s:  %s  %s\n",
                Device.Bus,
                Device.Device,
                Device.Function,
                PCI::Descriptors::GetSubclassName(Device.Header->Class,
                                                  Device.Header->Subclass),
                PCI::Descriptors::GetVendorName(Device.Header->VendorID),
                PCI::Descriptors::GetDeviceName(Device.Header->VendorID,
                                                Device.Header->DeviceID));
     }
 }
References PCI::Descriptors::GetDeviceName(), PCI::Manager::GetDevices(), PCI::Descriptors::GetSubclassName(), PCI::Descriptors::GetVendorName(), IF_ARG, PCIManager, and printf.