Fennix Userspace: Userspace/musl/src/stdio/fseek.c File Reference
fseek.c File Reference
#include "stdio_impl.h"
#include <errno.h>
Functions
int __fseeko_unlocked (FILE *f, off_t off, int whence)
int __fseeko (FILE *f, off_t off, int whence)
int fseek (FILE *f, long off, int whence)
weak_alias (__fseeko, fseeko)
Function Documentation
__fseeko()
int __fseeko (FILE * f, off_t off, int whence)
Definition at line 34 of file fseek.c.
 {
     int result;
     FLOCK(f);
     result = __fseeko_unlocked(f, off, whence);
     FUNLOCK(f);
     return result;
 }
References __fseeko_unlocked(), f, FLOCK, FUNLOCK, mlibc::off, and mlibc::whence.
Referenced by fseek(), and fsetpos().
__fseeko_unlocked()
int __fseeko_unlocked (FILE * f, off_t off, int whence)
Definition at line 4 of file fseek.c.
 {
     /* Fail immediately for invalid whence argument. */
     if (whence != SEEK_CUR && whence != SEEK_SET && whence != SEEK_END) {
         errno = EINVAL;
         return -1;
     }
     /* Adjust relative offset for unread data in buffer, if any. */
     if (whence == SEEK_CUR && f->rend) off -= f->rend - f->rpos;
     /* Flush write buffer, and report error on failure. */
     if (f->wpos != f->wbase) {
         f->write(f, 0, 0);
         if (!f->wpos) return -1;
     }
     /* Leave writing mode */
     f->wpos = f->wbase = f->wend = 0;
     /* Perform the underlying seek. */
     if (f->seek(f, off, whence) < 0) return -1;
     /* If seek succeeded, file is seekable and we discard read buffer. */
     f->rpos = f->rend = 0;
     f->flags &= ~F_EOF;
     return 0;
 }
References EINVAL, errno, f, F_EOF, _IO_FILE::flags, mlibc::off, _IO_FILE::rend, _IO_FILE::rpos, _IO_FILE::seek, SEEK_CUR, SEEK_END, SEEK_SET, _IO_FILE::wbase, _IO_FILE::wend, mlibc::whence, _IO_FILE::wpos, and _IO_FILE::write.
Referenced by __fseeko(), and rewind().
fseek()
int fseek (FILE * f, long off, int whence)
Definition at line 43 of file fseek.c.
 {
     return __fseeko(f, off, whence);
 }
References __fseeko(), _IO_FILE::_fileno, _IO_FILE::_offset, EINVAL, errno, f, mlibc::new_offset, NULL, mlibc::off, offset, syscall3(), and mlibc::whence.
Referenced by addmntent(), M_FileLength(), main(), and W_StdC_Read().
weak_alias()
weak_alias (__fseeko , fseeko)