Fennix: anonymous_namespace{socket.cpp} Namespace Reference
anonymous_namespace{socket.cpp} Namespace Reference
Functions
int fcntl_helper (int fd, int request, int *result,...)
Function Documentation
fcntl_helper()
int anonymous_namespace{socket.cpp}::fcntl_helper (int fd, int request, int * result, ...)
Definition at line 15 of file socket.cpp.
{
     va_list args;
     va_start(args, result);
     if(!mlibc::sys_fcntl) {
         return ENOSYS;
     }
     int ret = mlibc::sys_fcntl(fd, request, args, result);
     va_end(args);
     return ret;
 }
References args, ENOSYS, fd, mlibc::request, ret, mlibc::sys_fcntl(), va_end(), and va_start().