Fennix Userspace: Userspace/mlibc/options/posix/include/sys/times.h File Reference
times.h File Reference
#include <time.h>
Data Structures
struct tms
Functions
clock_t times (struct tms *)
Data Structure Documentation
tms
struct tms
Definition at line 11 of file times.h.
Data Fields
clock_t tms_cstime
clock_t tms_cutime
clock_t tms_stime
clock_t tms_utime
Function Documentation
times()
clock_t times (struct tms * tms)
Definition at line 10 of file sys-times.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_times, -1);
     clock_t ret;
     if(int e = mlibc::sys_times(tms, &ret); e) {
         errno = e;
         return -1;
     }
     return ret;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, ret, and mlibc::sys_times().
Referenced by futimens(), mlibc::sys_utimensat(), utime(), utimensat(), and utimes().