Fennix: Userspace/apps/base/busybox/editors/cmp.c File Reference
cmp.c File Reference
#include "libbb.h"
Macros
#define OPT_STR "sln:+"
#define CMP_OPT_s (1<<0)
#define CMP_OPT_l (1<<1)
#define CMP_OPT_n (1<<2)
Functions
int cmp_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char fmt_eof[] ALIGN1 = "cmp: EOF on %s\n"
Macro Definition Documentation
CMP_OPT_l
#define CMP_OPT_l (1<<1)
Definition at line 41 of file cmp.c.
CMP_OPT_n
#define CMP_OPT_n (1<<2)
Definition at line 42 of file cmp.c.
CMP_OPT_s
#define CMP_OPT_s (1<<0)
Definition at line 40 of file cmp.c.
OPT_STR
#define OPT_STR "sln:+"
Definition at line 39 of file cmp.c.
Function Documentation
cmp_main()
int cmp_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 45 of file cmp.c.
 {
     FILE *fp1, *fp2, *outfile = stdout;
     const char *filename1, *filename2 = "-";
     off_t skip1 = 0, skip2 = 0, char_pos = 0;
     int line_pos = 1; /* Hopefully won't overflow... */
     const char *fmt;
     int c1, c2;
     unsigned opt;
     int retval = 0;
     int max_count = -1;
 #if !ENABLE_LONG_OPTS
     opt = getopt32(argv, "^"
             OPT_STR
             "\0" "-1"
             IF_DESKTOP(":?4")
             IF_NOT_DESKTOP(":?2")
             ":l--s:s--l",
             &max_count
     );
 #else
     static const char cmp_longopts[] ALIGN1 =
         "bytes\0"          Required_argument  "n"
         "quiet\0"          No_argument        "s"
         "silent\0"         No_argument        "s"
         "verbose\0"        No_argument        "l"
         ;
     opt = getopt32long(argv, "^"
             OPT_STR
             "\0" "-1"
             IF_DESKTOP(":?4")
             IF_NOT_DESKTOP(":?2")
             ":l--s:s--l",
             cmp_longopts,
             &max_count
     );
 #endif
     argv += optind;
     filename1 = *argv;
     if (*++argv) {
         filename2 = *argv;
         if (ENABLE_DESKTOP && *++argv) {
             skip1 = XATOOFF(*argv);
             if (*++argv) {
                 skip2 = XATOOFF(*argv);
             }
         }
     }
     xfunc_error_retval = 2;  /* missing file results in exitcode 2 */
     if (opt & CMP_OPT_s)
         logmode = 0;  /* -s suppresses open error messages */
     fp1 = xfopen_stdin(filename1);
     fp2 = xfopen_stdin(filename2);
     if (fp1 == fp2) {       /* Paranoia check... stdin == stdin? */
         /* Note that we don't bother reading stdin.  Neither does gnu wc.
          * But perhaps we should, so that other apps down the chain don't
          * get the input.  Consider 'echo hello | (cmp - - && cat -)'.
          */
         return 0;
     }
     logmode = LOGMODE_STDIO;
     if (opt & CMP_OPT_l)
         fmt = fmt_l_opt;
     else
         fmt = fmt_differ;
     if (ENABLE_DESKTOP) {
         while (skip1) { getc(fp1); skip1--; }
         while (skip2) { getc(fp2); skip2--; }
     }
     do {
         if (max_count >= 0 && --max_count < 0)
             break;
         c1 = getc(fp1);
         c2 = getc(fp2);
         ++char_pos;
         if (c1 != c2) {         /* Remember: a read error may have occurred. */
             retval = 1;     /* But assume the files are different for now. */
             if (c2 == EOF) {
                 /* We know that fp1 isn't at EOF or in an error state.  But to
                  * save space below, things are setup to expect an EOF in fp1
                  * if an EOF occurred.  So, swap things around.
                  */
                 fp1 = fp2;
                 filename1 = filename2;
                 c1 = c2;
             }
             if (c1 == EOF) {
                 die_if_ferror(fp1, filename1);
                 fmt = fmt_eof;  /* Well, no error, so it must really be EOF. */
                 outfile = stderr;
                 /* There may have been output to stdout (option -l), so
                  * make sure we fflush before writing to stderr. */
                 fflush_all();
             }
             if (!(opt & CMP_OPT_s)) {
                 if (opt & CMP_OPT_l) {
                     line_pos = c1;  /* line_pos is unused in the -l case. */
                 }
                 fprintf(outfile, fmt, filename1, filename2, char_pos, line_pos, c2);
                 if (opt) {  /* This must be -l since not -s. */
                     /* If we encountered an EOF,
                      * the while check will catch it. */
                     continue;
                 }
             }
             break;
         }
         if (c1 == '\n') {
             ++line_pos;
         }
     } while (c1 != EOF);
     die_if_ferror(fp1, filename1);
     die_if_ferror(fp2, filename2);
     fflush_stdout_and_exit(retval);
 }
References ALIGN1, argv, CMP_OPT_l, CMP_OPT_s, die_if_ferror(), EOF, fflush_all(), fflush_stdout_and_exit(), fprintf(), getc, getopt32(), getopt32long, IF_DESKTOP(), logmode, LOGMODE_STDIO, No_argument, off_t, opt, OPT_STR, optind, outfile, Required_argument, retval, stderr, stdout, XATOOFF, xfopen_stdin(), and xfunc_error_retval.
Variable Documentation
ALIGN1
const char fmt_l_opt [] ALIGN1 = "cmp: EOF on %s\n" static
Definition at line 34 of file cmp.c.
Referenced by cmp_main().