Fennix: Userspace/apps/base/busybox/modutils/modprobe.c File Reference
modprobe.c File Reference
#include "libbb.h"
#include "modutils.h"
#include <sys/utsname.h>
#include <fnmatch.h>
Data Structures
struct globals
Macros
#define DBG(...) ((void)0)
#define MODPROBE_OPTS "alrDb"
#define MODPROBE_COMPLEMENTARY "q-v:v-q:l--arD:r--alD:a--lr:D--rl"
#define MODULE_FLAG_LOADED 0x0001
#define MODULE_FLAG_NEED_DEPS 0x0002
#define MODULE_FLAG_FOUND_IN_MODDEP 0x0004
#define MODULE_FLAG_BLACKLISTED 0x0008
#define MODULE_FLAG_BUILTIN 0x0010
#define G (*ptr_to_globals)
#define INIT_G()
Enumerations
enum {
OPT_INSERT_ALL = (INSMOD_OPT_UNUSED << 0) , OPT_LIST_ONLY = (INSMOD_OPT_UNUSED << 1) , OPT_REMOVE = (INSMOD_OPT_UNUSED << 2) , OPT_SHOW_DEPS = (INSMOD_OPT_UNUSED << 3) ,
OPT_BLACKLIST = (INSMOD_OPT_UNUSED << 4) * ENABLE_FEATURE_MODPROBE_BLACKLIST
}
Functions
static int read_config (const char *path)
static char * gather_options_str (char *opts, const char *append)
static struct module_entry * get_or_add_modentry (const char *module)
static void add_probe (const char *name)
static int FAST_FUNC config_file_action (struct recursive_state *state, const char *filename, struct stat *statbuf UNUSED_PARAM)
static const char * humanly_readable_name (struct module_entry *m)
static char * strsep_quotes (char **stringp)
static char * parse_and_add_kcmdline_module_options (char *options, const char *modulename)
static int do_modprobe (struct module_entry *m)
static void load_modules_dep (void)
int modprobe_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
DBG
#define DBG (...) ((void)0)
Definition at line 40 of file modprobe.c.
G
#define G (*ptr_to_globals)
Definition at line 186 of file modprobe.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 187 of file modprobe.c.
MODPROBE_COMPLEMENTARY
#define MODPROBE_COMPLEMENTARY "q-v:v-q:l--arD:r--alD:a--lr:D--rl"
Definition at line 135 of file modprobe.c.
MODPROBE_OPTS
#define MODPROBE_OPTS "alrDb"
Definition at line 133 of file modprobe.c.
MODULE_FLAG_BLACKLISTED
#define MODULE_FLAG_BLACKLISTED 0x0008
Definition at line 172 of file modprobe.c.
MODULE_FLAG_BUILTIN
#define MODULE_FLAG_BUILTIN 0x0010
Definition at line 173 of file modprobe.c.
MODULE_FLAG_FOUND_IN_MODDEP
#define MODULE_FLAG_FOUND_IN_MODDEP 0x0004
Definition at line 171 of file modprobe.c.
MODULE_FLAG_LOADED
#define MODULE_FLAG_LOADED 0x0001
Definition at line 168 of file modprobe.c.
MODULE_FLAG_NEED_DEPS
#define MODULE_FLAG_NEED_DEPS 0x0002
Definition at line 169 of file modprobe.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_INSERT_ALL
OPT_LIST_ONLY
OPT_REMOVE
OPT_SHOW_DEPS
OPT_BLACKLIST
Definition at line 138 of file modprobe.c.
      {
     OPT_INSERT_ALL   = (INSMOD_OPT_UNUSED << 0), /* a */
     //OPT_DUMP_ONLY  = (INSMOD_OPT_UNUSED << x), /* c */
     //OPT_DIRNAME    = (INSMOD_OPT_UNUSED << x), /* d */
     OPT_LIST_ONLY    = (INSMOD_OPT_UNUSED << 1), /* l */
     //OPT_SHOW_ONLY  = (INSMOD_OPT_UNUSED << x), /* n */
     OPT_REMOVE       = (INSMOD_OPT_UNUSED << 2), /* r */
     //OPT_RESTRICT   = (INSMOD_OPT_UNUSED << x), /* t */
     //OPT_VERONLY    = (INSMOD_OPT_UNUSED << x), /* V */
     //OPT_CONFIGFILE = (INSMOD_OPT_UNUSED << x), /* C */
     OPT_SHOW_DEPS    = (INSMOD_OPT_UNUSED << 3), /* D */
     OPT_BLACKLIST    = (INSMOD_OPT_UNUSED << 4) * ENABLE_FEATURE_MODPROBE_BLACKLIST,
 };
Function Documentation
add_probe()
static void add_probe (const char * name) static
Definition at line 214 of file modprobe.c.
 {
     struct module_entry *m;
     m = get_or_add_modentry(name);
     if (!(option_mask32 & (OPT_REMOVE | OPT_SHOW_DEPS))
      && (m->flags & (MODULE_FLAG_LOADED | MODULE_FLAG_BUILTIN))
     ) {
         DBG("skipping %s, it is already loaded", name);
         return;
     }
     DBG("queuing %s", name);
     m->probed_name = name;
     m->flags |= MODULE_FLAG_NEED_DEPS;
     llist_add_to_end(&G.probes, m);
     G.num_unresolved_deps++;
     if (ENABLE_FEATURE_MODUTILS_SYMBOLS
      && is_prefixed_with(m->modname, "symbol:")
     ) {
         G.need_symbols = 1;
     }
 }
References DBG, G, get_or_add_modentry(), is_prefixed_with(), llist_add_to_end(), module_entry::modname, MODULE_FLAG_BUILTIN, MODULE_FLAG_LOADED, MODULE_FLAG_NEED_DEPS, module_entry::name, OPT_REMOVE, OPT_SHOW_DEPS, and option_mask32.
Referenced by modprobe_main().
config_file_action()
static int FAST_FUNC config_file_action (struct recursive_state * state, const char * filename, struct stat *statbuf UNUSED_PARAM) static
Definition at line 238 of file modprobe.c.
 {
     char *tokens[3];
     parser_t *p;
     struct module_entry *m;
     int rc = TRUE;
     const char *base;
     /* Skip files that begin with a "." */
     base = bb_basename(filename);
     if (base[0] == '.')
         goto error;
     /* "man modprobe.d" from kmod version 22 suggests
      * that we shouldn't recurse into /etc/modprobe.d/dir/
      * _subdirectories_:
      */
     if (state->depth > 1)
         return SKIP; /* stop recursing */
 //TODO: instead, can use dirAction in recursive_action() to SKIP dirs
 //on depth == 1 level. But that's more code...
     /* In dir recursion, skip files that do not end with a ".conf"
      * depth==0: read_config("modules.{symbols,alias}") must work,
      * "include FILE_NOT_ENDING_IN_CONF" must work too.
      */
     if (state->depth != 0) {
         if (!is_suffixed_with(base, ".conf"))
             goto error;
     }
     p = config_open2(filename, fopen_for_read);
     if (p == NULL) {
         rc = FALSE;
         goto error;
     }
     while (config_read(p, tokens, 3, 2, "# \t", PARSE_NORMAL)) {
 //Use index_in_strings?
         if (strcmp(tokens[0], "alias") == 0) {
             /* alias <wildcard> <modulename> */
             llist_t *l;
             char wildcard[MODULE_NAME_LEN];
             char *rmod;
             if (tokens[2] == NULL)
                 continue;
             filename2modname(tokens[1], wildcard);
             for (l = G.probes; l; l = l->link) {
                 m = (struct module_entry *) l->data;
                 if (fnmatch(wildcard, m->modname, 0) != 0)
                     continue;
                 rmod = filename2modname(tokens[2], NULL);
                 llist_add_to(&m->realnames, rmod);
                 if (m->flags & MODULE_FLAG_NEED_DEPS) {
                     m->flags &= ~MODULE_FLAG_NEED_DEPS;
                     G.num_unresolved_deps--;
                 }
                 m = get_or_add_modentry(rmod);
                 if (!(m->flags & MODULE_FLAG_NEED_DEPS)) {
                     m->flags |= MODULE_FLAG_NEED_DEPS;
                     G.num_unresolved_deps++;
                 }
             }
         } else if (strcmp(tokens[0], "options") == 0) {
             /* options <modulename> <option...> */
             if (tokens[2] == NULL)
                 continue;
             m = get_or_add_modentry(tokens[1]);
             m->options = gather_options_str(m->options, tokens[2]);
         } else if (strcmp(tokens[0], "include") == 0) {
             /* include <filename>/<dirname> (yes, directories also must work) */
             read_config(tokens[1]);
         } else if (ENABLE_FEATURE_MODPROBE_BLACKLIST
          && strcmp(tokens[0], "blacklist") == 0
         ) {
             /* blacklist <modulename> */
             get_or_add_modentry(tokens[1])->flags |= MODULE_FLAG_BLACKLISTED;
         }
     }
     config_close(p);
  error:
     return rc;
 }
References base, bb_basename(), config_close(), config_open2(), config_read, error, FALSE, filename, filename2modname(), fnmatch(), fopen_for_read(), G, gather_options_str(), get_or_add_modentry(), if(), is_suffixed_with(), l, llist_add_to(), module_entry::modname, MODULE_FLAG_BLACKLISTED, MODULE_FLAG_NEED_DEPS, MODULE_NAME_LEN, NULL, p, PARSE_NORMAL, rc, read_config(), SKIP, state, strcmp, and TRUE.
Referenced by read_config().
do_modprobe()
static int do_modprobe (struct module_entry * m) static
Definition at line 416 of file modprobe.c.
 {
     int rc, first;
     if (!(m->flags & MODULE_FLAG_FOUND_IN_MODDEP)) {
         if (!(option_mask32 & INSMOD_OPT_SILENT))
             bb_error_msg((m->flags & MODULE_FLAG_BUILTIN) ?
                      "module %s is builtin" :
                      "module %s not found in modules.dep",
                      humanly_readable_name(m));
         return -ENOENT;
     }
     DBG("do_modprob'ing %s", m->modname);
     if (!(option_mask32 & OPT_REMOVE))
         m->deps = llist_rev(m->deps);
     if (0) {
         llist_t *l;
         for (l = m->deps; l; l = l->link)
             DBG("dep: %s", l->data);
     }
     first = 1;
     rc = 0;
     while (m->deps) {
         struct module_entry *m2;
         char *fn, *options;
         rc = 0;
         fn = llist_pop(&m->deps); /* we leak it */
         m2 = get_or_add_modentry(bb_get_last_path_component_nostrip(fn));
         if (option_mask32 & OPT_REMOVE) {
             /* modprobe -r */
             if (m2->flags & MODULE_FLAG_LOADED) {
                 rc = bb_delete_module(m2->modname, O_EXCL);
                 if (rc) {
                     if (first) {
                         bb_perror_msg("can't unload module '%s'",
                             humanly_readable_name(m2));
                         break;
                     }
                 } else {
                     m2->flags &= ~MODULE_FLAG_LOADED;
                 }
             }
             /* do not error out if *deps* fail to unload */
             first = 0;
             continue;
         }
         options = m2->options;
         m2->options = NULL;
         options = parse_and_add_kcmdline_module_options(options, m2->modname);
 #if ENABLE_FEATURE_CMDLINE_MODULE_OPTIONS
         if (m == m2)
             options = gather_options_str(options, G.cmdline_mopts);
 #endif
         if (option_mask32 & OPT_SHOW_DEPS) {
             printf(options ? "insmod %s/%s/%s %s\n"
                     : "insmod %s/%s/%s\n",
                 CONFIG_DEFAULT_MODULES_DIR, G.uts.release, fn,
                 options);
             free(options);
             continue;
         }
         if (m2->flags & MODULE_FLAG_LOADED) {
             DBG("%s is already loaded, skipping", fn);
             free(options);
             continue;
         }
         rc = bb_init_module(fn, options);
         DBG("loaded %s '%s', rc:%d", fn, options, rc);
         if (rc == EEXIST)
             rc = 0;
         free(options);
         if (rc) {
             bb_error_msg("can't load module %s (%s): %s",
                 humanly_readable_name(m2),
                 fn,
                 moderror(rc)
             );
             break;
         }
         m2->flags |= MODULE_FLAG_LOADED;
     }
     return rc;
 }
References bb_delete_module(), bb_error_msg(), bb_get_last_path_component_nostrip(), bb_init_module(), bb_perror_msg(), DBG, module_entry::deps, EEXIST, ENOENT, first, free, G, gather_options_str(), get_or_add_modentry(), humanly_readable_name(), INSMOD_OPT_SILENT, l, llist_pop(), llist_rev(), moderror(), module_entry::modname, MODULE_FLAG_BUILTIN, MODULE_FLAG_FOUND_IN_MODDEP, MODULE_FLAG_LOADED, NULL, O_EXCL, OPT_REMOVE, OPT_SHOW_DEPS, option_mask32, options, parse_and_add_kcmdline_module_options(), printf, and rc.
Referenced by modprobe_main().
gather_options_str()
static char* gather_options_str (char * opts, const char * append) static
Definition at line 194 of file modprobe.c.
 {
     /* Speed-optimized. We call gather_options_str many times. */
     if (append) {
         if (opts == NULL) {
             opts = xstrdup(append);
         } else {
             int optlen = strlen(opts);
             opts = xrealloc(opts, optlen + strlen(append) + 2);
             sprintf(opts + optlen, " %s", append);
         }
     }
     return opts;
 }
References append(), NULL, sprintf(), strlen, xrealloc, and xstrdup().
Referenced by config_file_action(), do_modprobe(), and parse_and_add_kcmdline_module_options().
get_or_add_modentry()
static struct module_entry* get_or_add_modentry (const char * module) static
Definition at line 209 of file modprobe.c.
 {
     return moddb_get_or_create(&G.db, module);
 }
References G, and moddb_get_or_create().
Referenced by add_probe(), config_file_action(), do_modprobe(), and modprobe_main().
humanly_readable_name()
static const char* humanly_readable_name (struct module_entry * m) static
Definition at line 334 of file modprobe.c.
 {
     /* probed_name may be NULL. modname always exists. */
     return m->probed_name ? m->probed_name : m->modname;
 }
References module_entry::modname.
Referenced by do_modprobe().
load_modules_dep()
static void load_modules_dep (void) static
Definition at line 510 of file modprobe.c.
 {
     struct module_entry *m;
     char *colon, *tokens[2];
     parser_t *p;
     /* Modprobe does not work at all without modules.dep,
      * even if the full module name is given. Returning error here
      * was making us later confuse user with this message:
      * "module /full/path/to/existing/file/module.ko not found".
      * It's better to die immediately, with good message.
      * xfopen_for_read provides that. */
     p = config_open2(CONFIG_DEFAULT_DEPMOD_FILE, xfopen_for_read);
     while (G.num_unresolved_deps
      && config_read(p, tokens, 2, 1, "# \t", PARSE_NORMAL)
     ) {
         colon = last_char_is(tokens[0], ':');
         if (colon == NULL)
             continue;
         *colon = '\0';
         m = moddb_get(&G.db, bb_get_last_path_component_nostrip(tokens[0]));
         if (m == NULL)
             continue;
         /* Optimization... */
         if ((m->flags & MODULE_FLAG_LOADED)
          && !(option_mask32 & (OPT_REMOVE | OPT_SHOW_DEPS))
         ) {
             DBG("skip deps of %s, it's already loaded", tokens[0]);
             continue;
         }
         m->flags |= MODULE_FLAG_FOUND_IN_MODDEP;
         if ((m->flags & MODULE_FLAG_NEED_DEPS) && (m->deps == NULL)) {
             G.num_unresolved_deps--;
             llist_add_to(&m->deps, xstrdup(tokens[0]));
             if (tokens[1])
                 string_to_llist(tokens[1], &m->deps, " \t");
         } else
             DBG("skipping dep line");
     }
     config_close(p);
 }
References bb_get_last_path_component_nostrip(), colon, config_close(), config_open2(), config_read, DBG, module_entry::deps, G, last_char_is(), llist_add_to(), moddb_get(), MODULE_FLAG_FOUND_IN_MODDEP, MODULE_FLAG_LOADED, MODULE_FLAG_NEED_DEPS, NULL, OPT_REMOVE, OPT_SHOW_DEPS, option_mask32, p, PARSE_NORMAL, string_to_llist(), xfopen_for_read(), and xstrdup().
Referenced by modprobe_main().
modprobe_main()
int modprobe_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 557 of file modprobe.c.
 {
     int rc;
     unsigned opt;
     struct module_entry *me;
     INIT_G();
     opt = getopt32long(argv, "^" INSMOD_OPTS MODPROBE_OPTS "\0" MODPROBE_COMPLEMENTARY,
             modprobe_longopts
             INSMOD_ARGS
     );
     argv += optind;
     /* Goto modules location */
     xchdir(CONFIG_DEFAULT_MODULES_DIR);
     uname(&G.uts);
     xchdir(G.uts.release);
     if (opt & OPT_LIST_ONLY) {
         int i;
         char *colon, *tokens[2];
         parser_t *p = config_open2(CONFIG_DEFAULT_DEPMOD_FILE, xfopen_for_read);
         for (i = 0; argv[i]; i++)
             replace(argv[i], '-', '_');
         while (config_read(p, tokens, 2, 1, "# \t", PARSE_NORMAL)) {
             colon = last_char_is(tokens[0], ':');
             if (!colon)
                 continue;
             *colon = '\0';
             if (!argv[0])
                 puts(tokens[0]);
             else {
                 char name[MODULE_NAME_LEN];
                 filename2modname(
                     bb_get_last_path_component_nostrip(tokens[0]),
                     name
                 );
                 for (i = 0; argv[i]; i++) {
                     if (fnmatch(argv[i], name, 0) == 0) {
                         puts(tokens[0]);
                     }
                 }
             }
         }
         return EXIT_SUCCESS;
     }
     /* Yes, for some reason -l ignores -s... */
     if (opt & INSMOD_OPT_SYSLOG)
         logmode = LOGMODE_SYSLOG;
     if (!argv[0]) {
         if (opt & OPT_REMOVE) {
             /* "modprobe -r" (w/o params).
              * "If name is NULL, all unused modules marked
              * autoclean will be removed".
              */
             if (bb_delete_module(NULL, O_NONBLOCK | O_EXCL) != 0)
                 bb_perror_nomsg_and_die();
         }
         return EXIT_SUCCESS;
     }
     /* Retrieve module names of already loaded modules */
     {
         char *s;
         parser_t *parser = config_open2("/proc/modules", fopen_for_read);
         while (config_read(parser, &s, 1, 1, "# \t", PARSE_NORMAL & ~PARSE_GREEDY))
             get_or_add_modentry(s)->flags |= MODULE_FLAG_LOADED;
         config_close(parser);
         parser = config_open2("modules.builtin", fopen_for_read);
         /* this file contains lines like "kernel/fs/binfmt_script.ko" */
         while (config_read(parser, &s, 1, 1, "# \t", PARSE_NORMAL))
             get_or_add_modentry(bb_basename(s))->flags |= MODULE_FLAG_BUILTIN;
         config_close(parser);
     }
     if (opt & (OPT_INSERT_ALL | OPT_REMOVE)) {
         /* Each argument is a module name */
         do {
             DBG("adding module %s", *argv);
             add_probe(*argv++);
         } while (*argv);
     } else {
         /* First argument is module name, rest are parameters */
         DBG("probing just module %s", *argv);
         add_probe(argv[0]);
 #if ENABLE_FEATURE_CMDLINE_MODULE_OPTIONS
         G.cmdline_mopts = parse_cmdline_module_options(argv, /*quote_spaces:*/ 1);
 #endif
     }
     /* Happens if all requested modules are already loaded */
     if (G.probes == NULL)
         return EXIT_SUCCESS;
     read_config("/etc/modprobe.conf");
     read_config("/etc/modprobe.d");
     if (ENABLE_FEATURE_MODUTILS_SYMBOLS && G.need_symbols)
         read_config("modules.symbols");
     load_modules_dep();
     if (ENABLE_FEATURE_MODUTILS_ALIAS && G.num_unresolved_deps) {
         read_config("modules.alias");
         load_modules_dep();
     }
     /* Handle modprobe.blacklist=module1,module2,... */
     if (ENABLE_FEATURE_MODPROBE_BLACKLIST) {
         char *options;
         char *substr;
         options = parse_and_add_kcmdline_module_options(NULL, "modprobe");
         while ((substr = strsep(&options, " ")) != NULL) {
             char *fn = is_prefixed_with(substr, "blacklist=");
             if (!fn)
                 continue;
             while ((substr = strsep(&fn, ",")) != NULL) {
                 /* blacklist <modulename> */
                 get_or_add_modentry(substr)->flags |= MODULE_FLAG_BLACKLISTED;
                 DBG("blacklist: %s", substr);
             }
         }
         /*free(options); - WRONG, strsep may have advanced it */
     }
     rc = 0;
     while ((me = llist_pop(&G.probes)) != NULL) {
         if (me->realnames == NULL) {
             DBG("probing by module name");
             /* This is not an alias. Literal names are blacklisted
              * only if '-b' is given.
              */
             if (!(opt & OPT_BLACKLIST)
              || !(me->flags & MODULE_FLAG_BLACKLISTED)
             ) {
                 rc |= do_modprobe(me);
             }
             continue;
         }
         /* Probe all real names for the alias */
         do {
             char *realname = llist_pop(&me->realnames);
             struct module_entry *m2;
             DBG("probing alias %s by realname %s", me->modname, realname);
             m2 = get_or_add_modentry(realname);
             if (!(m2->flags & MODULE_FLAG_BLACKLISTED)
              && (!(m2->flags & MODULE_FLAG_LOADED)
                 || (opt & (OPT_REMOVE | OPT_SHOW_DEPS)))
             ) {
 //TODO: we can pass "me" as 2nd param to do_modprobe,
 //and make do_modprobe emit more meaningful error messages
 //with alias name included, not just module name alias resolves to.
                 rc |= do_modprobe(m2);
             }
             free(realname);
         } while (me->realnames != NULL);
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         moddb_free(&G.db);
     return (rc != 0);
 }
References add_probe(), argv, bb_basename(), bb_delete_module(), bb_get_last_path_component_nostrip(), bb_perror_nomsg_and_die(), colon, config_close(), config_open2(), config_read, DBG, do_modprobe(), EXIT_SUCCESS, filename2modname(), fnmatch(), fopen_for_read(), free, G, get_or_add_modentry(), getopt32long, i, INIT_G, INSMOD_ARGS, INSMOD_OPT_SYSLOG, INSMOD_OPTS, is_prefixed_with(), last_char_is(), llist_pop(), load_modules_dep(), logmode, LOGMODE_SYSLOG, me, moddb_free(), MODPROBE_COMPLEMENTARY, MODPROBE_OPTS, MODULE_FLAG_BLACKLISTED, MODULE_FLAG_BUILTIN, MODULE_FLAG_LOADED, MODULE_NAME_LEN, module_entry::name, NULL, O_EXCL, O_NONBLOCK, opt, OPT_BLACKLIST, OPT_INSERT_ALL, OPT_LIST_ONLY, OPT_REMOVE, OPT_SHOW_DEPS, optind, options, p, parse_and_add_kcmdline_module_options(), parse_cmdline_module_options, PARSE_GREEDY, PARSE_NORMAL, parser, puts(), rc, read_config(), replace, s, strsep(), uname(), xchdir(), and xfopen_for_read().
parse_and_add_kcmdline_module_options()
static char* parse_and_add_kcmdline_module_options (char * options, const char * modulename) static
Definition at line 372 of file modprobe.c.
 {
     char *kcmdline_buf;
     char *kcmdline;
     char *kptr;
     kcmdline_buf = xmalloc_open_read_close("/proc/cmdline", NULL);
     if (!kcmdline_buf)
         return options;
     kcmdline = kcmdline_buf;
     while ((kptr = strsep_quotes(&kcmdline)) != NULL) {
         char *after_modulename = is_prefixed_with(kptr, modulename);
         if (!after_modulename || *after_modulename != '.')
             continue;
         /* It is "modulename.xxxx" */
         kptr = after_modulename + 1;
         if (strchr(kptr, '=') != NULL) {
             /* It is "modulename.opt=[val]" */
             options = gather_options_str(options, kptr);
         }
     }
     free(kcmdline_buf);
     return options;
 }
References free, gather_options_str(), is_prefixed_with(), NULL, options, strchr(), strsep_quotes(), and xmalloc_open_read_close().
Referenced by do_modprobe(), and modprobe_main().
read_config()
static int read_config (const char * path) static
Definition at line 328 of file modprobe.c.
 {
     return recursive_action(path, ACTION_RECURSE | ACTION_QUIET,
                 config_file_action, NULL, NULL);
 }
References ACTION_QUIET, ACTION_RECURSE, config_file_action(), NULL, and recursive_action().
Referenced by config_file_action(), and modprobe_main().
strsep_quotes()
static char* strsep_quotes (char ** stringp) static
Definition at line 343 of file modprobe.c.
 {
     char *s, *start = *stringp;
     if (!start)
         return NULL;
     for (s = start; ; s++) {
         switch (*s) {
         case '"':
             s = strchrnul(s + 1, '"'); /* find trailing quote */
             if (*s != '\0')
                 s++; /* skip trailing quote */
             /* fall through */
         case '\0':
         case '\n':
         case '\t':
         case ' ':
             if (*s != '\0') {
                 *s = '\0';
                 *stringp = s + 1;
             } else {
                 *stringp = NULL;
             }
             return start;
         }
     }
 }
References NULL, s, start, and strchrnul().
Referenced by parse_and_add_kcmdline_module_options().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING