Fennix: Userspace/apps/base/busybox/libbb/bb_askpass.c File Reference
bb_askpass.c File Reference
#include "libbb.h"
Macros
#define MAX_LINE 0xfff
Functions
static void askpass_timeout (int UNUSED_PARAM ignore)
char *FAST_FUNC bb_ask_noecho (int fd, int timeout, const char *prompt)
char *FAST_FUNC bb_ask_noecho_stdin (const char *prompt)
Macro Definition Documentation
MAX_LINE
#define MAX_LINE 0xfff
Function Documentation
askpass_timeout()
static void askpass_timeout (int UNUSED_PARAM ignore) static
Definition at line 12 of file bb_askpass.c.
 {
 }
Referenced by bb_ask_noecho().
bb_ask_noecho()
char* FAST_FUNC bb_ask_noecho (int fd, int timeout, const char * prompt)
Definition at line 16 of file bb_askpass.c.
 {
 #define MAX_LINE 0xfff
     char *ret;
     int i;
     struct sigaction sa, oldsa;
     struct termios tio, oldtio;
     tcflush(fd, TCIFLUSH);
     /* Was buggy: was printing prompt *before* flushing input,
      * which was upsetting "expect" based scripts of some users.
      */
     fputs_stdout(prompt);
     fflush_all();
     tcgetattr(fd, &oldtio);
     tio = oldtio;
     /* Switch off echo. ECHOxyz meaning:
      * ECHO    echo input chars
      * ECHOE   echo BS-SP-BS on erase character
      * ECHOK   echo kill char specially, not as ^c (ECHOKE controls how exactly)
      * ECHOKE  erase all input via BS-SP-BS on kill char (else go to next line)
      * ECHOCTL Echo ctrl chars as ^c (else echo verbatim:
      *         e.g. up arrow emits "ESC-something" and thus moves cursor up!)
      * ECHONL  Echo NL even if ECHO is not set
      * ECHOPRT On erase, echo erased chars
      *         [qwe<BS><BS><BS> input looks like "qwe\ewq/" on screen]
      */
     tio.c_lflag &= ~(ECHO|ECHOE|ECHOK|ECHONL);
     tcsetattr(fd, TCSANOW, &tio);
     memset(&sa, 0, sizeof(sa));
     /* sa.sa_flags = 0; - no SA_RESTART! */
     /* SIGINT and SIGALRM will interrupt reads below */
     sa.sa_handler = askpass_timeout;
     sigaction(SIGINT, &sa, &oldsa);
     if (timeout) {
         sigaction_set(SIGALRM, &sa);
         alarm(timeout);
     }
     ret = NULL;
     i = 0;
     while (1) {
         int r;
         /* User input is uber-slow, no need to optimize reallocs.
          * Grow it on every char.
          */
         ret = xrealloc(ret, i + 2);
         r = read(fd, &ret[i], 1);
         if ((i == 0 && r == 0) /* EOF (^D) with no password */
          || r < 0 /* read is interrupted by timeout or ^C */
         ) {
             ret[i] = '\0'; /* paranoia */
             nuke_str(ret); /* paranoia */
             free(ret);
             ret = NULL;
             break;
         }
         if (r == 0 /* EOF */
          || ret[i] == '\r' || ret[i] == '\n' /* EOL */
          || ++i == MAX_LINE /* line limit */
         ) {
             ret[i] = '\0';
             break;
         }
     }
     if (timeout) {
         alarm(0);
     }
     sigaction_set(SIGINT, &oldsa);
     tcsetattr(fd, TCSANOW, &oldtio);
     bb_putchar('\n');
     fflush_all();
     return ret;
 }
References alarm(), askpass_timeout(), bb_putchar(), ECHO, ECHOE, ECHOK, ECHONL, fd, fflush_all(), fputs_stdout(), free, i, MAX_LINE, memset, nuke_str(), NULL, prompt, read(), sigaction_set(), SIGALRM, SIGINT, tcflush(), tcgetattr(), TCIFLUSH, TCSANOW, tcsetattr(), timeout(), tio, and xrealloc.
Referenced by ask_and_check_password_extended(), bb_ask_noecho_stdin(), and get_cred_or_die().
bb_ask_noecho_stdin()
char* FAST_FUNC bb_ask_noecho_stdin (const char * prompt)
Definition at line 96 of file bb_askpass.c.
 {
     return bb_ask_noecho(STDIN_FILENO, 0, prompt);
 }
References bb_ask_noecho(), prompt, and STDIN_FILENO.
Referenced by cryptpw_main(), and new_password().