Fennix Userspace: Userspace/musl/src/legacy/ulimit.c File Reference
ulimit.c File Reference
#include <sys/resource.h>
#include <ulimit.h>
#include <stdarg.h>
Functions
long ulimit (int cmd,...)
Function Documentation
ulimit()
long ulimit (int cmd, ...)
Definition at line 5 of file ulimit.c.
 {
     struct rlimit rl;
     getrlimit(RLIMIT_FSIZE, &rl);
     if (cmd == UL_SETFSIZE) {
         long val;
         va_list ap;
         va_start(ap, cmd);
         val = va_arg(ap, long);
         va_end(ap);
         rl.rlim_cur = 512ULL * val;
         if (setrlimit(RLIMIT_FSIZE, &rl)) return -1;
     }
     return rl.rlim_cur / 512;
 }
References ap, cmd, getrlimit(), rlimit::rlim_cur, RLIMIT_FSIZE, setrlimit(), UL_SETFSIZE, va_arg, va_end, va_start, and val.
Referenced by getdtablesize().