Fennix Userspace: Userspace/apps/base/busybox/procps/ps.c File Reference
ps.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Enumerations
enum { MAX_WIDTH = 2*1024 }
Functions
int ps_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
int ps_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAX_WIDTH
Definition at line 118 of file ps.c.
 { MAX_WIDTH = 2*1024 };
Function Documentation
ps_main() [1/2]
int ps_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 648 of file ps.c.
 {
     procps_status_t *p;
     int psscan_flags = PSSCAN_PID | PSSCAN_UIDGID
             | PSSCAN_STATE | PSSCAN_VSZ | PSSCAN_COMM;
     unsigned terminal_width IF_NOT_FEATURE_PS_WIDE(= 79);
     enum {
         OPT_Z = (1 << 0) * ENABLE_SELINUX,
         OPT_T = (1 << ENABLE_SELINUX) * ENABLE_FEATURE_SHOW_THREADS,
         OPT_l = (1 << ENABLE_SELINUX) * (1 << ENABLE_FEATURE_SHOW_THREADS) * ENABLE_FEATURE_PS_LONG,
     };
 #if ENABLE_FEATURE_PS_LONG
     time_t now = now; /* for compiler */
     unsigned long uptime = uptime;
 #endif
     /* If we support any options, parse argv */
 #if ENABLE_SELINUX || ENABLE_FEATURE_SHOW_THREADS || ENABLE_FEATURE_PS_WIDE || ENABLE_FEATURE_PS_LONG
     int opts = 0;
 # if ENABLE_FEATURE_PS_WIDE
     /* -w is a bit complicated */
     int w_count = 0;
     make_all_argv_opts(argv);
     opts = getopt32(argv, "^"
         IF_SELINUX("Z")IF_FEATURE_SHOW_THREADS("T")IF_FEATURE_PS_LONG("l")"w"
         "\0" "ww",
         &w_count
     );
     /* if w is given once, GNU ps sets the width to 132,
      * if w is given more than once, it is "unlimited"
      */
     if (w_count) {
         terminal_width = (w_count == 1) ? 132 : MAX_WIDTH;
     } else {
         terminal_width = get_terminal_width(0);
         /* Go one less... */
         if (--terminal_width > MAX_WIDTH)
             terminal_width = MAX_WIDTH;
     }
 # else
     /* -w is not supported, only -Z and/or -T */
     make_all_argv_opts(argv);
     opts = getopt32(argv, IF_SELINUX("Z")IF_FEATURE_SHOW_THREADS("T")IF_FEATURE_PS_LONG("l"));
 # endif
 # if ENABLE_SELINUX
     if ((opts & OPT_Z) && is_selinux_enabled()) {
         psscan_flags = PSSCAN_PID | PSSCAN_CONTEXT
                 | PSSCAN_STATE | PSSCAN_COMM;
         puts("  PID CONTEXT                          STAT COMMAND");
     } else
 # endif
     if (opts & OPT_l) {
         psscan_flags = PSSCAN_STATE | PSSCAN_UIDGID | PSSCAN_PID | PSSCAN_PPID
             | PSSCAN_TTY | PSSCAN_STIME | PSSCAN_UTIME | PSSCAN_COMM
             | PSSCAN_VSZ | PSSCAN_RSS;
 /* http://pubs.opengroup.org/onlinepubs/9699919799/utilities/ps.html
  * mandates for -l:
  * -F     Flags (?)
  * S      State
  * UID,PID,PPID
  * -C     CPU usage
  * -PRI   The priority of the process; higher numbers mean lower priority
  * -NI    Nice value
  * -ADDR  The address of the process (?)
  * SZ     The size in blocks of the core image
  * -WCHAN The event for which the process is waiting or sleeping
  * TTY
  * TIME   The cumulative execution time
  * CMD
  * We don't show fields marked with '-'.
  * We show VSZ and RSS instead of SZ.
  * We also show STIME (standard says that -f shows it, -l doesn't).
  */
         puts("S   UID   PID  PPID   VSZ   RSS TTY   STIME TIME     CMD");
 # if ENABLE_FEATURE_PS_LONG
         now = time(NULL);
         uptime = get_uptime();
 # endif
     }
     else {
         puts("  PID USER       VSZ STAT COMMAND");
     }
     if (opts & OPT_T) {
         psscan_flags |= PSSCAN_TASKS;
     }
 #endif
     p = NULL;
     while ((p = procps_scan(p, psscan_flags)) != NULL) {
         int len;
 #if ENABLE_SELINUX
         if (psscan_flags & PSSCAN_CONTEXT) {
             len = printf("%5u %-32.32s %s  ",
                     p->pid,
                     p->context ? p->context : "unknown",
                     p->state);
         } else
 #endif
         {
             char buf6[6];
             smart_ulltoa5(p->vsz, buf6, " mgtpezy")[0] = '\0';
 #if ENABLE_FEATURE_PS_LONG
             if (opts & OPT_l) {
                 char bufr[6], stime_str[6];
                 char tty[2 * sizeof(int)*3 + 2];
                 char *endp;
                 unsigned sut = (p->stime + p->utime) / 100;
                 unsigned elapsed = uptime - (p->start_time / 100);
                 time_t start = now - elapsed;
                 struct tm *tm = localtime(&start);
                 smart_ulltoa5(p->rss, bufr, " mgtpezy")[0] = '\0';
                 if (p->tty_major == 136)
                     /* It should be pts/N, not ptsN, but N > 9
                      * will overflow field width...
                      */
                     endp = stpcpy(tty, "pts");
                 else
                 if (p->tty_major == 4) {
                     endp = stpcpy(tty, "tty");
                     if (p->tty_minor >= 64) {
                         p->tty_minor -= 64;
                         *endp++ = 'S';
                     }
                 }
                 else
                     endp = tty + sprintf(tty, "%d:", p->tty_major);
                 strcpy(endp, utoa(p->tty_minor));
                 strftime(stime_str, 6, (elapsed >= (24 * 60 * 60)) ? "%b%d" : "%H:%M", tm);
                 stime_str[5] = '\0';
                 //            S  UID PID PPID VSZ RSS TTY STIME TIME        CMD
                 len = printf("%c %5u %5u %5u %5s %5s %-5s %s %02u:%02u:%02u ",
                     p->state[0], p->uid, p->pid, p->ppid, buf6, bufr, tty,
                     stime_str, sut / 3600, (sut % 3600) / 60, sut % 60);
             } else
 #endif
             {
                 const char *user = get_cached_username(p->uid);
                 len = printf("%5u %-8.8s %s %s  ",
                     p->pid, user, buf6, p->state);
             }
         }
         {
             int sz = terminal_width - len;
             if (sz >= 0) {
                 char buf[sz + 1];
                 read_cmdline(buf, sz, p->pid, p->comm);
                 puts(buf);
             }
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         clear_username_cache();
     return EXIT_SUCCESS;
 }
References argv, buf, clear_username_cache(), EXIT_SUCCESS, get_cached_username(), get_terminal_width(), get_uptime(), getopt32(), localtime(), make_all_argv_opts(), MAX_WIDTH, NULL, OPT_l, OPT_T, OPT_Z, p, printf(), procps_scan(), PSSCAN_COMM, PSSCAN_CONTEXT, PSSCAN_PID, PSSCAN_PPID, PSSCAN_RSS, PSSCAN_STATE, PSSCAN_STIME, PSSCAN_TASKS, PSSCAN_TTY, PSSCAN_UIDGID, PSSCAN_UTIME, PSSCAN_VSZ, puts(), read_cmdline(), smart_ulltoa5(), sprintf(), start, stpcpy(), strcpy(), strftime(), time(), and utoa().
ps_main() [2/2]
int ps_main (int argc, char ** argv)