Fennix Userspace: Userspace/musl/src/misc/mntent.c File Reference
mntent.c File Reference
#include <stdio.h>
#include <string.h>
#include <mntent.h>
#include <errno.h>
#include <limits.h>
Macros
#define SENTINEL (char *)&internal_buf
Functions
FILE * setmntent (const char *name, const char *mode)
int endmntent (FILE *f)
struct mntent * getmntent_r (FILE *f, struct mntent *mnt, char *linebuf, int buflen)
struct mntent * getmntent (FILE *f)
int addmntent (FILE *f, const struct mntent *mnt)
char * hasmntopt (const struct mntent *mnt, const char *opt)
Variables
static char * internal_buf
static size_t internal_bufsize
Macro Definition Documentation
SENTINEL
#define SENTINEL (char *)&internal_buf
Definition at line 10 of file mntent.c.
Function Documentation
addmntent()
int addmntent (FILE * f, const struct mntent * mnt)
Definition at line 72 of file mntent.c.
 {
     if (fseek(f, 0, SEEK_END)) return 1;
     return fprintf(f, "%s\t%s\t%s\t%s\t%d\t%d\n",
         mnt->mnt_fsname, mnt->mnt_dir, mnt->mnt_type, mnt->mnt_opts,
         mnt->mnt_freq, mnt->mnt_passno) < 0;
 }
References f, fprintf(), fseek(), mntent::mnt_dir, mntent::mnt_freq, mntent::mnt_fsname, mntent::mnt_opts, mntent::mnt_passno, mntent::mnt_type, and SEEK_END.
Referenced by mount_it_now().
endmntent()
int endmntent (FILE * f)
Definition at line 17 of file mntent.c.
 {
     if (f) fclose(f);
     return 1;
 }
References f, and fclose().
Referenced by df_main(), do_em_all_in_fstab(), find_mount_point(), load_fs_info(), mount_it_now(), mount_main(), and umount_main().
getmntent()
struct mntent* getmntent (FILE * f)
Definition at line 66 of file mntent.c.
 {
     static struct mntent mnt;
     return getmntent_r(f, &mnt, SENTINEL, 0);
 }
References f, getmntent_r(), and SENTINEL.
Referenced by df_main(), do_em_all_in_fstab(), and find_mount_point().
getmntent_r()
struct mntent* getmntent_r (FILE * f, struct mntent * mnt, char * linebuf, int buflen)
Definition at line 23 of file mntent.c.
 {
     int n[8], use_internal = (linebuf == SENTINEL);
     size_t len, i;
     mnt->mnt_freq = 0;
     mnt->mnt_passno = 0;
     do {
         if (use_internal) {
             getline(&internal_buf, &internal_bufsize, f);
             linebuf = internal_buf;
         } else {
             fgets(linebuf, buflen, f);
         }
         if (feof(f) || ferror(f)) return 0;
         if (!strchr(linebuf, '\n')) {
             fscanf(f, "%*[^\n]%*[\n]");
             errno = ERANGE;
             return 0;
         }
         len = strlen(linebuf);
         if (len > INT_MAX) continue;
         for (i = 0; i < sizeof n / sizeof *n; i++) n[i] = len;
         sscanf(linebuf, " %n%*s%n %n%*s%n %n%*s%n %n%*s%n %d %d",
             n, n+1, n+2, n+3, n+4, n+5, n+6, n+7,
             &mnt->mnt_freq, &mnt->mnt_passno);
     } while (linebuf[n[0]] == '#' || n[1]==len);
     linebuf[n[1]] = 0;
     linebuf[n[3]] = 0;
     linebuf[n[5]] = 0;
     linebuf[n[7]] = 0;
     mnt->mnt_fsname = linebuf+n[0];
     mnt->mnt_dir = linebuf+n[2];
     mnt->mnt_type = linebuf+n[4];
     mnt->mnt_opts = linebuf+n[6];
     return mnt;
 }
References buflen, ERANGE, errno, f, feof, ferror, fgets, fscanf(), getline(), i, INT_MAX, internal_buf, internal_bufsize, mntent::mnt_dir, mntent::mnt_freq, mntent::mnt_fsname, mntent::mnt_opts, mntent::mnt_passno, mntent::mnt_type, n, SENTINEL, sscanf(), strchr(), and strlen().
Referenced by getmntent(), load_fs_info(), mount_main(), and umount_main().
hasmntopt()
char* hasmntopt (const struct mntent * mnt, const char * opt)
Definition at line 80 of file mntent.c.
 {
     return strstr(mnt->mnt_opts, opt);
 }
References mntent::mnt_opts, opt, and strstr().
Referenced by do_em_all_in_fstab().
setmntent()
FILE* setmntent (const char * name, const char * mode)
Definition at line 12 of file mntent.c.
 {
     return fopen(name, mode);
 }
References fopen().
Referenced by df_main(), find_mount_point(), load_fs_info(), mount_it_now(), mount_main(), and umount_main().
Variable Documentation
internal_buf
char* internal_buf static
Definition at line 7 of file mntent.c.
Referenced by getmntent_r(), and vfprintf().
internal_bufsize
size_t internal_bufsize static
Definition at line 8 of file mntent.c.
Referenced by getmntent_r().