Fennix Userspace: Userspace/musl/src/linux/mount.c File Reference
mount.c File Reference
#include <sys/mount.h>
#include "syscall.h"
Functions
int mount (const char *special, const char *dir, const char *fstype, unsigned long flags, const void *data)
int umount (const char *special)
int umount2 (const char *special, int flags)
Function Documentation
mount()
int mount (const char * special, const char * dir, const char * fstype, unsigned long flags, const void * data)
Definition at line 4 of file mount.c.
 {
     return syscall(SYS_mount, special, dir, fstype, flags, data);
 }
References dir, flags, and syscall().
Referenced by make_tempdir(), mount_or_die(), switch_root_main(), and umount_main().
umount()
int umount (const char * special)
Definition at line 9 of file mount.c.
 {
     return syscall(SYS_umount2, special, 0);
 }
References syscall().
Referenced by umount_main().
umount2()
int umount2 (const char * special, int flags)
Definition at line 14 of file mount.c.
 {
     return syscall(SYS_umount2, special, flags);
 }
References flags, and syscall().
Referenced by make_tempdir(), and umount_main().