Fennix: Userspace/apps/base/busybox/util-linux/ipcs.c File Reference
ipcs.c File Reference
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/msg.h>
#include <sys/shm.h>
#include "libbb.h"
Data Structures
struct shm_info
union semun
Macros
#define SHM_DEST 01000 /* segment will be destroyed on last detach */
#define SHM_LOCKED 02000 /* segment will not be swapped */
#define MSG_STAT 11
#define MSG_INFO 12
#define SHM_STAT 13
#define SHM_INFO 14
#define SEM_STAT 18
#define SEM_INFO 19
#define IPC_INFO 3
#define KEY key
#define LIMITS 1
#define STATUS 2
#define CREATOR 3
#define TIME 4
#define PID 5
#define flag_msg (1<<2)
#define flag_sem (1<<3)
#define flag_shm (1<<4)
Functions
static void print_perms (int id, struct ipc_perm *ipcp)
static NOINLINE void do_shm (int format)
static NOINLINE void do_sem (int format)
static NOINLINE void do_msg (int format)
static void print_shm (int shmid)
static void print_msg (int msqid)
static void print_sem (int semid)
int ipcs_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
shm_info
struct shm_info
Definition at line 50 of file ipcs.c.
Data Fields
unsigned long __pad0
unsigned long __pad1
unsigned long __pad2
unsigned long __pad3
unsigned long __pad4
int __pad_ids
unsigned long __swap_attempts
unsigned long __swap_successes
int __used_ids
unsigned long shm_rss
unsigned long shm_swp
unsigned long shm_tot
unsigned long swap_attempts
unsigned long swap_successes
int used_ids
semun
union semun
Definition at line 35 of file ipcrm.c.
Data Fields
struct seminfo * __buf
unsigned short * array
struct semid_ds * buf
int val
Macro Definition Documentation
CREATOR
#define CREATOR 3
Definition at line 99 of file ipcs.c.
flag_msg
#define flag_msg (1<<2)
flag_sem
#define flag_sem (1<<3)
flag_shm
#define flag_shm (1<<4)
IPC_INFO
#define IPC_INFO 3
Definition at line 67 of file ipcs.c.
KEY
#define KEY key
Definition at line 94 of file ipcs.c.
LIMITS
#define LIMITS 1
Definition at line 97 of file ipcs.c.
MSG_INFO
#define MSG_INFO 12
Definition at line 44 of file ipcs.c.
MSG_STAT
#define MSG_STAT 11
Definition at line 43 of file ipcs.c.
PID
#define PID 5
Definition at line 101 of file ipcs.c.
SEM_INFO
#define SEM_INFO 19
Definition at line 62 of file ipcs.c.
SEM_STAT
#define SEM_STAT 18
Definition at line 61 of file ipcs.c.
SHM_DEST
#define SHM_DEST 01000 /* segment will be destroyed on last detach */
Definition at line 37 of file ipcs.c.
SHM_INFO
#define SHM_INFO 14
Definition at line 49 of file ipcs.c.
SHM_LOCKED
#define SHM_LOCKED 02000 /* segment will not be swapped */
Definition at line 38 of file ipcs.c.
SHM_STAT
#define SHM_STAT 13
Definition at line 48 of file ipcs.c.
STATUS
#define STATUS 2
Definition at line 98 of file ipcs.c.
TIME
#define TIME 4
Definition at line 100 of file ipcs.c.
Function Documentation
do_msg()
static NOINLINE void do_msg (int format) static
Definition at line 356 of file ipcs.c.
 {
     int maxid, msqid, id;
     struct msqid_ds msgque;
     struct msginfo msginfo;
     struct ipc_perm *ipcp = &msgque.msg_perm;
     struct passwd *pw;
     maxid = msgctl(0, MSG_INFO, (struct msqid_ds *) (void *) &msginfo);
     if (maxid < 0) {
         printf("kernel not configured for %s\n", "message queues");
         return;
     }
     switch (format) {
     case LIMITS:
         if ((msgctl(0, IPC_INFO, (struct msqid_ds *) (void *) &msginfo)) < 0)
             return;
         printf("------ Message%s --------\n", "s: Limits");
         printf("max queues system wide = %d\n"
                 "max size of message (bytes) = %d\n"
                 "default max size of queue (bytes) = %d\n",
                 msginfo.msgmni, msginfo.msgmax, msginfo.msgmnb);
         return;
     case STATUS:
         printf("------ Message%s --------\n", "s: Status");
         printf("allocated queues = %d\n"
                 "used headers = %d\n"
                 "used space = %d bytes\n",
                 msginfo.msgpool, msginfo.msgmap, msginfo.msgtql);
         return;
     case CREATOR:
         printf("------ Message%s --------\n", " Queues: Creators/Owners");
         printf("%-10s %-10s %-10s %-10s %-10s %-10s\n",
                 "msqid", "perms", "cuid", "cgid", "uid", "gid");
         break;
     case TIME:
         printf("------ Message%s --------\n", " Queues Send/Recv/Change Times");
         printf("%-8s %-10s %-20s %-20s %-20s\n",
                 "msqid", "owner", "send", "recv", "change");
         break;
     case PID:
         printf("------ Message%s --------\n", " Queues PIDs");
         printf("%-10s %-10s %-10s %-10s\n",
                 "msqid", "owner", "lspid", "lrpid");
         break;
     default:
         printf("------ Message%s --------\n", " Queues");
         printf("%-10s %-10s %-10s %-10s %-12s %-12s\n",
                 "key", "msqid", "owner", "perms", "used-bytes", "messages");
         break;
     }
     for (id = 0; id <= maxid; id++) {
         msqid = msgctl(id, MSG_STAT, &msgque);
         if (msqid < 0)
             continue;
         if (format == CREATOR) {
             print_perms(msqid, ipcp);
             continue;
         }
         pw = getpwuid(ipcp->uid);
         switch (format) {
         case TIME:
             if (pw)
                 printf("%-8d %-10.10s", msqid, pw->pw_name);
             else
                 printf("%-8d %-10d", msqid, ipcp->uid);
             printf(" %-20.16s", msgque.msg_stime
                     ? ctime(&msgque.msg_stime) + 4 : "Not set");
             printf(" %-20.16s", msgque.msg_rtime
                     ? ctime(&msgque.msg_rtime) + 4 : "Not set");
             printf(" %-20.16s\n", msgque.msg_ctime
                     ? ctime(&msgque.msg_ctime) + 4 : "Not set");
             break;
         case PID:
             if (pw)
                 printf("%-8d %-10.10s", msqid, pw->pw_name);
             else
                 printf("%-8d %-10d", msqid, ipcp->uid);
             printf("  %5d     %5d\n", msgque.msg_lspid, msgque.msg_lrpid);
             break;
         default:
             printf("0x%08x ", ipcp->KEY);
             if (pw)
                 printf("%-10d %-10.10s", msqid, pw->pw_name);
             else
                 printf("%-10d %-10d", msqid, ipcp->uid);
             printf(" %-10o %-12ld %-12ld\n", ipcp->mode & 0777,
                     /*
                      * glibc-2.1.3 and earlier has unsigned short;
                      * glibc-2.1.91 has variation between
                      * unsigned short, unsigned long
                      * Austin has msgqnum_t
                      */
                     (long) msgque.msg_cbytes, (long) msgque.msg_qnum);
             break;
         }
     }
 }
References CREATOR, ctime(), format(), getpwuid, IPC_INFO, LIMITS, ipc_perm::mode, msqid_ds::msg_cbytes, msqid_ds::msg_ctime, MSG_INFO, msqid_ds::msg_lrpid, msqid_ds::msg_lspid, msqid_ds::msg_perm, msqid_ds::msg_qnum, msqid_ds::msg_rtime, MSG_STAT, msqid_ds::msg_stime, msgctl(), msginfo::msgmap, msginfo::msgmax, msginfo::msgmnb, msginfo::msgmni, msginfo::msgpool, msginfo::msgtql, PID, print_perms(), printf, pw, passwd::pw_name, STATUS, TIME, and ipc_perm::uid.
Referenced by ipcs_main().
do_sem()
static NOINLINE void do_sem (int format) static
Definition at line 251 of file ipcs.c.
 {
     int maxid, semid, id;
     struct semid_ds semary;
     struct seminfo seminfo;
     struct ipc_perm *ipcp = &semary.sem_perm;
     struct passwd *pw;
     union semun arg;
     arg.array = (unsigned short *) (void *) &seminfo;
     maxid = semctl(0, 0, SEM_INFO, arg);
     if (maxid < 0) {
         printf("kernel not configured for %s\n", "semaphores");
         return;
     }
     switch (format) {
     case LIMITS:
         printf("------ Semaphore %s --------\n", "Limits");
         arg.array = (unsigned short *) (void *) &seminfo;   /* damn union */
         if ((semctl(0, 0, IPC_INFO, arg)) < 0)
             return;
         printf("max number of arrays = %d\n"
                 "max semaphores per array = %d\n"
                 "max semaphores system wide = %d\n"
                 "max ops per semop call = %d\n"
                 "semaphore max value = %d\n",
                 seminfo.semmni,
                 seminfo.semmsl,
                 seminfo.semmns, seminfo.semopm, seminfo.semvmx);
         return;
     case STATUS:
         printf("------ Semaphore %s --------\n", "Status");
         printf("used arrays = %d\n"
                 "allocated semaphores = %d\n",
                 seminfo.semusz, seminfo.semaem);
         return;
     case CREATOR:
         printf("------ Semaphore %s --------\n", "Arrays Creators/Owners");
         printf("%-10s %-10s %-10s %-10s %-10s %-10s\n",
                 "semid", "perms", "cuid", "cgid", "uid", "gid");
         break;
     case TIME:
         printf("------ Shared Memory %s --------\n", "Operation/Change Times");
         printf("%-8s %-10s %-26.24s %-26.24s\n",
                 "shmid", "owner", "last-op", "last-changed");
         break;
     case PID:
         break;
     default:
         printf("------ Semaphore %s --------\n", "Arrays");
         printf("%-10s %-10s %-10s %-10s %-10s\n",
                 "key", "semid", "owner", "perms", "nsems");
         break;
     }
     for (id = 0; id <= maxid; id++) {
         arg.buf = (struct semid_ds *) &semary;
         semid = semctl(id, 0, SEM_STAT, arg);
         if (semid < 0)
             continue;
         if (format == CREATOR) {
             print_perms(semid, ipcp);
             continue;
         }
         pw = getpwuid(ipcp->uid);
         switch (format) {
         case TIME:
             if (pw)
                 printf("%-8d %-10.10s", semid, pw->pw_name);
             else
                 printf("%-8d %-10d", semid, ipcp->uid);
             /* ctime uses static buffer: use separate calls */
             printf("  %-26.24s", semary.sem_otime
                     ? ctime(&semary.sem_otime) : "Not set");
             printf(" %-26.24s\n", semary.sem_ctime
                     ? ctime(&semary.sem_ctime) : "Not set");
             break;
         case PID:
             break;
         default:
             printf("0x%08x ", ipcp->KEY);
             if (pw)
                 printf("%-10d %-10.9s", semid, pw->pw_name);
             else
                 printf("%-10d %-9d", semid, ipcp->uid);
             printf(" %-10o %-10ld\n", ipcp->mode & 0777,
                     /*
                      * glibc-2.1.3 and earlier has unsigned short;
                      * glibc-2.1.91 has variation between
                      * unsigned short and unsigned long
                      * Austin prescribes unsigned short.
                      */
                     (long) semary.sem_nsems);
             break;
         }
     }
 }
References CREATOR, ctime(), format(), getpwuid, IPC_INFO, LIMITS, ipc_perm::mode, PID, print_perms(), printf, pw, passwd::pw_name, semid_ds::sem_ctime, SEM_INFO, semid_ds::sem_nsems, semid_ds::sem_otime, semid_ds::sem_perm, SEM_STAT, seminfo::semaem, semctl(), seminfo::semmni, seminfo::semmns, seminfo::semmsl, seminfo::semopm, seminfo::semusz, seminfo::semvmx, STATUS, TIME, and ipc_perm::uid.
Referenced by ipcs_main().
do_shm()
static NOINLINE void do_shm (int format) static
Definition at line 125 of file ipcs.c.
 {
     int maxid, shmid, id;
     struct shmid_ds shmseg;
     struct shm_info shm_info;
     struct shminfo shminfo;
     struct ipc_perm *ipcp = &shmseg.shm_perm;
     struct passwd *pw;
     maxid = shmctl(0, SHM_INFO, (struct shmid_ds *) (void *) &shm_info);
     if (maxid < 0) {
         printf("kernel not configured for %s\n", "shared memory");
         return;
     }
     switch (format) {
     case LIMITS:
         printf("------ Shared Memory %s --------\n", "Limits");
         if ((shmctl(0, IPC_INFO, (struct shmid_ds *) (void *) &shminfo)) < 0)
             return;
         /* glibc 2.1.3 and all earlier libc's have ints as fields
          * of struct shminfo; glibc 2.1.91 has unsigned long; ach */
         printf("max number of segments = %lu\n"
                 "max seg size (kbytes) = %lu\n"
                 "max total shared memory (pages) = %lu\n"
                 "min seg size (bytes) = %lu\n",
                 (unsigned long) shminfo.shmmni,
                 (unsigned long) (shminfo.shmmax >> 10),
                 (unsigned long) shminfo.shmall,
                 (unsigned long) shminfo.shmmin);
         return;
     case STATUS:
         printf("------ Shared Memory %s --------\n", "Status");
         printf("segments allocated %d\n"
                 "pages allocated %lu\n"
                 "pages resident  %lu\n"
                 "pages swapped   %lu\n"
                 "Swap performance: %lu attempts\t%lu successes\n",
                 shm_info.used_ids,
                 shm_info.shm_tot,
                 shm_info.shm_rss,
                 shm_info.shm_swp,
                 shm_info.swap_attempts, shm_info.swap_successes);
         return;
     case CREATOR:
         printf("------ Shared Memory %s --------\n", "Segment Creators/Owners");
         printf("%-10s %-10s %-10s %-10s %-10s %-10s\n",
                 "shmid", "perms", "cuid", "cgid", "uid", "gid");
         break;
     case TIME:
         printf("------ Shared Memory %s --------\n", "Attach/Detach/Change Times");
         printf("%-10s %-10s %-20s %-20s %-20s\n",
                 "shmid", "owner", "attached", "detached", "changed");
         break;
     case PID:
         printf("------ Shared Memory %s --------\n", "Creator/Last-op");
         printf("%-10s %-10s %-10s %-10s\n",
                 "shmid", "owner", "cpid", "lpid");
         break;
     default:
         printf("------ Shared Memory %s --------\n", "Segments");
         printf("%-10s %-10s %-10s %-10s %-10s %-10s %-12s\n",
                 "key", "shmid", "owner", "perms", "bytes", "nattch",
                 "status");
         break;
     }
     for (id = 0; id <= maxid; id++) {
         shmid = shmctl(id, SHM_STAT, &shmseg);
         if (shmid < 0)
             continue;
         if (format == CREATOR) {
             print_perms(shmid, ipcp);
             continue;
         }
         pw = getpwuid(ipcp->uid);
         switch (format) {
         case TIME:
             if (pw)
                 printf("%-10d %-10.10s", shmid, pw->pw_name);
             else
                 printf("%-10d %-10d", shmid, ipcp->uid);
             /* ctime uses static buffer: use separate calls */
             printf(" %-20.16s", shmseg.shm_atime
                     ? ctime(&shmseg.shm_atime) + 4 : "Not set");
             printf(" %-20.16s", shmseg.shm_dtime
                     ? ctime(&shmseg.shm_dtime) + 4 : "Not set");
             printf(" %-20.16s\n", shmseg.shm_ctime
                     ? ctime(&shmseg.shm_ctime) + 4 : "Not set");
             break;
         case PID:
             if (pw)
                 printf("%-10d %-10.10s", shmid, pw->pw_name);
             else
                 printf("%-10d %-10d", shmid, ipcp->uid);
             printf(" %-10d %-10d\n", shmseg.shm_cpid, shmseg.shm_lpid);
             break;
         default:
             printf("0x%08x ", ipcp->KEY);
             if (pw)
                 printf("%-10d %-10.10s", shmid, pw->pw_name);
             else
                 printf("%-10d %-10d", shmid, ipcp->uid);
             printf(" %-10o %-10lu %-10ld %-6s %-6s\n", ipcp->mode & 0777,
                     /*
                      * earlier: int, Austin has size_t
                      */
                     (unsigned long) shmseg.shm_segsz,
                     /*
                      * glibc-2.1.3 and earlier has unsigned short;
                      * Austin has shmatt_t
                      */
                     (long) shmseg.shm_nattch,
                     ipcp->mode & SHM_DEST ? "dest" : " ",
                     ipcp->mode & SHM_LOCKED ? "locked" : " ");
             break;
         }
     }
 }
References CREATOR, ctime(), format(), getpwuid, IPC_INFO, LIMITS, ipc_perm::mode, PID, print_perms(), printf, pw, passwd::pw_name, shmid_ds::shm_atime, shmid_ds::shm_cpid, shmid_ds::shm_ctime, SHM_DEST, shmid_ds::shm_dtime, SHM_INFO, SHM_LOCKED, shmid_ds::shm_lpid, shmid_ds::shm_nattch, shmid_ds::shm_perm, shm_info::shm_rss, shmid_ds::shm_segsz, SHM_STAT, shm_info::shm_swp, shm_info::shm_tot, shminfo::shmall, shmctl(), shminfo::shmmax, shminfo::shmmin, shminfo::shmmni, STATUS, shm_info::swap_attempts, shm_info::swap_successes, TIME, ipc_perm::uid, and shm_info::used_ids.
Referenced by ipcs_main().
ipcs_main()
int ipcs_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 581 of file ipcs.c.
 {
     int format = 0;
     unsigned opt;
     char *opt_i;
     opt = getopt32(argv, "i:aqsmtcplu", &opt_i);
 #define flag_msg (1<<2)
 #define flag_sem (1<<3)
 #define flag_shm (1<<4)
     if (opt & (1<<5)) format = TIME; // -t
     if (opt & (1<<6)) format = CREATOR; // -c
     if (opt & (1<<7)) format = PID; // -p
     if (opt & (1<<8)) format = LIMITS; // -l
     if (opt & (1<<9)) format = STATUS; // -u
     if (opt & (1<<0)) { // -i
         int id;
         id = xatoi(opt_i);
         if (opt & flag_shm) {
             print_shm(id);
             fflush_stdout_and_exit_SUCCESS();
         }
         if (opt & flag_sem) {
             print_sem(id);
             fflush_stdout_and_exit_SUCCESS();
         }
         if (opt & flag_msg) {
             print_msg(id);
             fflush_stdout_and_exit_SUCCESS();
         }
         bb_show_usage();
     }
     if ((opt & (1<<1)) // -a
      || !(opt & (flag_msg | flag_sem | flag_shm)) // none of -q,-s,-m == all
     ) {
         opt |= flag_msg | flag_sem | flag_shm;
     }
     bb_putchar('\n');
     if (opt & flag_msg) {
         do_msg(format);
         bb_putchar('\n');
     }
     if (opt & flag_shm) {
         do_shm(format);
         bb_putchar('\n');
     }
     if (opt & flag_sem) {
         do_sem(format);
         bb_putchar('\n');
     }
     fflush_stdout_and_exit_SUCCESS();
 }
References argv, bb_putchar(), bb_show_usage(), CREATOR, do_msg(), do_sem(), do_shm(), fflush_stdout_and_exit_SUCCESS(), flag_msg, flag_sem, flag_shm, format(), getopt32(), LIMITS, opt, PID, print_msg(), print_sem(), print_shm(), STATUS, and TIME.
print_msg()
static void print_msg (int msqid) static
Definition at line 489 of file ipcs.c.
 {
     struct msqid_ds buf;
     struct ipc_perm *ipcp = &buf.msg_perm;
     if (msgctl(msqid, IPC_STAT, &buf) == -1) {
         bb_simple_perror_msg("msgctl");
         return;
     }
     printf("\nMessage Queue msqid=%d\n"
             "uid=%d\tgid=%d\tcuid=%d\tcgid=%d\tmode=%#o\n"
             "cbytes=%ld\tqbytes=%ld\tqnum=%ld\tlspid=%d\tlrpid=%d\n",
             msqid, ipcp->uid, ipcp->gid, ipcp->cuid, ipcp->cgid, ipcp->mode,
             /*
              * glibc-2.1.3 and earlier has unsigned short;
              * glibc-2.1.91 has variation between
              * unsigned short, unsigned long
              * Austin has msgqnum_t (for msg_qbytes)
              */
             (long) buf.msg_cbytes, (long) buf.msg_qbytes,
             (long) buf.msg_qnum, buf.msg_lspid, buf.msg_lrpid);
     printf("send_time=%-26.24s\n",
             buf.msg_stime ? ctime(&buf.msg_stime) : "Not set");
     printf("rcv_time=%-26.24s\n",
             buf.msg_rtime ? ctime(&buf.msg_rtime) : "Not set");
     printf("change_time=%-26.24s\n\n",
             buf.msg_ctime ? ctime(&buf.msg_ctime) : "Not set");
 }
References bb_simple_perror_msg(), buf, ipc_perm::cgid, ctime(), ipc_perm::cuid, ipc_perm::gid, IPC_STAT, ipc_perm::mode, msgctl(), printf, and ipc_perm::uid.
Referenced by ipcs_main().
print_perms()
static void print_perms (int id, struct ipc_perm * ipcp) static
Definition at line 103 of file ipcs.c.
 {
     struct passwd *pw;
     struct group *gr;
     printf("%-10d %-10o", id, ipcp->mode & 0777);
     pw = getpwuid(ipcp->cuid);
     if (pw) printf(" %-10s", pw->pw_name);
     else    printf(" %-10d", ipcp->cuid);
     gr = getgrgid(ipcp->cgid);
     if (gr) printf(" %-10s", gr->gr_name);
     else    printf(" %-10d", ipcp->cgid);
     pw = getpwuid(ipcp->uid);
     if (pw) printf(" %-10s", pw->pw_name);
     else    printf(" %-10d", ipcp->uid);
     gr = getgrgid(ipcp->gid);
     if (gr) printf(" %-10s\n", gr->gr_name);
     else    printf(" %-10d\n", ipcp->gid);
 }
References ipc_perm::cgid, ipc_perm::cuid, getgrgid, getpwuid, ipc_perm::gid, gr, group::gr_name, ipc_perm::mode, printf, pw, passwd::pw_name, and ipc_perm::uid.
Referenced by do_msg(), do_sem(), and do_shm().
print_sem()
static void print_sem (int semid) static
Definition at line 520 of file ipcs.c.
 {
     struct semid_ds semds;
     struct ipc_perm *ipcp = &semds.sem_perm;
     union semun arg;
     unsigned int i;
     arg.buf = &semds;
     if (semctl(semid, 0, IPC_STAT, arg)) {
         bb_simple_perror_msg("semctl");
         return;
     }
     printf("\nSemaphore Array semid=%d\n"
             "uid=%d\t gid=%d\t cuid=%d\t cgid=%d\n"
             "mode=%#o, access_perms=%#o\n"
             "nsems = %ld\n"
             "otime = %-26.24s\n",
             semid,
             ipcp->uid, ipcp->gid, ipcp->cuid, ipcp->cgid,
             ipcp->mode, ipcp->mode & 0777,
             (long) semds.sem_nsems,
             semds.sem_otime ? ctime(&semds.sem_otime) : "Not set");
     printf("ctime = %-26.24s\n"
             "%-10s %-10s %-10s %-10s %-10s\n",
             ctime(&semds.sem_ctime),
             "semnum", "value", "ncount", "zcount", "pid");
     arg.val = 0;
     for (i = 0; i < semds.sem_nsems; i++) {
         int val, ncnt, zcnt, pid;
         val = semctl(semid, i, GETVAL, arg);
         ncnt = semctl(semid, i, GETNCNT, arg);
         zcnt = semctl(semid, i, GETZCNT, arg);
         pid = semctl(semid, i, GETPID, arg);
         if (val < 0 || ncnt < 0 || zcnt < 0 || pid < 0) {
             bb_simple_perror_msg_and_die("semctl");
         }
         printf("%-10u %-10d %-10d %-10d %-10d\n", i, val, ncnt, zcnt, pid);
     }
     bb_putchar('\n');
 }
References bb_putchar(), bb_simple_perror_msg(), bb_simple_perror_msg_and_die(), ipc_perm::cgid, ctime(), ipc_perm::cuid, GETNCNT, GETPID, GETVAL, GETZCNT, ipc_perm::gid, i, IPC_STAT, ipc_perm::mode, pid, printf, semid_ds::sem_ctime, semid_ds::sem_nsems, semid_ds::sem_otime, semid_ds::sem_perm, semctl(), ipc_perm::uid, and val.
Referenced by ipcs_main().
print_shm()
static void print_shm (int shmid) static
Definition at line 463 of file ipcs.c.
 {
     struct shmid_ds shmds;
     struct ipc_perm *ipcp = &shmds.shm_perm;
     if (shmctl(shmid, IPC_STAT, &shmds) == -1) {
         bb_simple_perror_msg("shmctl");
         return;
     }
     printf("\nShared memory Segment shmid=%d\n"
             "uid=%d\tgid=%d\tcuid=%d\tcgid=%d\n"
             "mode=%#o\taccess_perms=%#o\n"
             "bytes=%ld\tlpid=%d\tcpid=%d\tnattch=%ld\n",
             shmid,
             ipcp->uid, ipcp->gid, ipcp->cuid, ipcp->cgid,
             ipcp->mode, ipcp->mode & 0777,
             (long) shmds.shm_segsz, shmds.shm_lpid, shmds.shm_cpid,
             (long) shmds.shm_nattch);
     printf("att_time=%-26.24s\n",
             shmds.shm_atime ? ctime(&shmds.shm_atime) : "Not set");
     printf("det_time=%-26.24s\n",
             shmds.shm_dtime ? ctime(&shmds.shm_dtime) : "Not set");
     printf("change_time=%-26.24s\n\n", ctime(&shmds.shm_ctime));
 }
References bb_simple_perror_msg(), ipc_perm::cgid, ctime(), ipc_perm::cuid, ipc_perm::gid, IPC_STAT, ipc_perm::mode, printf, shmid_ds::shm_atime, shmid_ds::shm_cpid, shmid_ds::shm_ctime, shmid_ds::shm_dtime, shmid_ds::shm_lpid, shmid_ds::shm_nattch, shmid_ds::shm_perm, shmid_ds::shm_segsz, shmctl(), and ipc_perm::uid.
Referenced by ipcs_main().