Fennix: Kernel/core/driver/api.cpp File Reference
api.cpp File Reference
#include <driver.hpp>
#include <interface/driver.h>
#include <interface/fs.h>
#include <type_traits>
#include <interface/aip.h>
#include <interface/input.h>
#include <interface/pci.h>
#include "../../kernel.h"
Data Structures
struct APISymbols
Namespaces
v0
Macros
#define DEBUG_API
#define dbg_api(Format, ...) func(Format, ##__VA_ARGS__)
Typedefs
typedef int v0::CriticalState
Functions
void v0::KernelPrint (dev_t DriverID, const char *Format, va_list args)
void v0::KernelLog (dev_t DriverID, const char *Format, va_list args)
CriticalState v0::EnterCriticalSection (dev_t DriverID)
void v0::LeaveCriticalSection (dev_t DriverID, CriticalState PreviousState)
int v0::RegisterInterruptHandler (dev_t DriverID, uint8_t IRQ, void *Handler)
int v0::OverrideInterruptHandler (dev_t DriverID, uint8_t IRQ, void *Handler)
int v0::UnregisterInterruptHandler (dev_t DriverID, uint8_t IRQ, void *Handler)
int v0::UnregisterAllInterruptHandlers (dev_t DriverID, void *Handler)
dev_t v0::RegisterFileSystem (dev_t DriverID, FileSystemInfo *Info, struct Inode *Root)
int v0::UnregisterFileSystem (dev_t DriverID, dev_t Device)
pid_t v0::CreateKernelProcess (dev_t DriverID, const char *Name)
pid_t v0::CreateKernelThread (dev_t DriverID, pid_t pId, const char *Name, void *EntryPoint, void *Argument)
pid_t v0::GetCurrentProcess (dev_t DriverID)
int v0::KillProcess (dev_t DriverID, pid_t pId, int ExitCode)
int v0::KillThread (dev_t DriverID, pid_t tId, pid_t pId, int ExitCode)
void v0::Yield (dev_t DriverID)
void v0::Sleep (dev_t DriverID, uint64_t Milliseconds)
void v0::PIC_EOI (dev_t DriverID, uint8_t IRQ)
void v0::IRQ_MASK (dev_t DriverID, uint8_t IRQ)
void v0::IRQ_UNMASK (dev_t DriverID, uint8_t IRQ)
void v0::PS2Wait (dev_t DriverID, const bool Output)
void v0::PS2WriteCommand (dev_t DriverID, uint8_t Command)
void v0::PS2WriteData (dev_t DriverID, uint8_t Data)
uint8_t v0::PS2ReadData (dev_t DriverID)
uint8_t v0::PS2ReadStatus (dev_t DriverID)
uint8_t v0::PS2ReadAfterACK (dev_t DriverID)
void v0::PS2ClearOutputBuffer (dev_t DriverID)
int v0::PS2ACKTimeout (dev_t DriverID)
void * v0::AllocateMemory (dev_t DriverID, size_t Pages)
void v0::FreeMemory (dev_t DriverID, void *Pointer, size_t Pages)
void * v0::MemoryCopy (dev_t DriverID, void *Destination, const void *Source, size_t Length)
void * v0::MemorySet (dev_t DriverID, void *Destination, int Value, size_t Length)
void * v0::MemoryMove (dev_t DriverID, void *Destination, const void *Source, size_t Length)
size_t v0::StringLength (dev_t DriverID, const char String[])
char * v0::_strstr (dev_t DriverID, const char *Haystack, const char *Needle)
void v0::MapPages (dev_t MajorID, void *PhysicalAddress, void *VirtualAddress, size_t Pages, uint32_t Flags)
void v0::UnmapPages (dev_t MajorID, void *VirtualAddress, size_t Pages)
void v0::AppendMapFlag (dev_t MajorID, void *Address, PageMapFlags Flag)
void v0::RemoveMapFlag (dev_t MajorID, void *Address, PageMapFlags Flag)
void * v0::Znwm (size_t Size)
void v0::ZdlPvm (void *Pointer, size_t Size)
__PCIArray * v0::GetPCIDevices (dev_t DriverID, uint16_t _Vendors[], uint16_t _Devices[])
void v0::InitializePCI (dev_t DriverID, void *_Header)
uint32_t v0::GetBAR (dev_t DriverID, uint8_t i, void *_Header)
uint8_t v0::iLine (dev_t DriverID, PCIDevice *Device)
uint8_t v0::iPin (dev_t DriverID, PCIDevice *Device)
dev_t v0::RegisterDevice (dev_t DriverID, DeviceType Type, const InodeOperations *Operations)
int v0::UnregisterDevice (dev_t DriverID, dev_t Device)
int v0::ReportInputEvent (dev_t DriverID, InputReport *Report)
long __KernelUndefinedFunction (long arg0, long arg1, long arg2, long arg3, long arg4, long arg5, long arg6, long arg7)
void * GetSymbolByName (const char *Name, int Version)
Variables
static struct APISymbols APISymbols_v0 []
Data Structure Documentation
APISymbols
struct APISymbols
Definition at line 826 of file api.cpp.
Data Fields
void * Function
const char * Name
Macro Definition Documentation
dbg_api
#define dbg_api (Format, ...) func(Format, ##__VA_ARGS__)
Definition at line 31 of file api.cpp.
DEBUG_API
#define DEBUG_API
Definition at line 28 of file api.cpp.
Function Documentation
__KernelUndefinedFunction()
long __KernelUndefinedFunction (long arg0, long arg1, long arg2, long arg3, long arg4, long arg5, long arg6, long arg7)
Definition at line 892 of file api.cpp.
 {
     debug("%#lx, %#lx, %#lx, %#lx, %#lx, %#lx, %#lx, %#lx",
           arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
     assert(!"Undefined kernel driver API function called!");
     CPU::Stop();
 }
References assert, debug, and CPU::Stop().
Referenced by GetSymbolByName().
GetSymbolByName()
void* GetSymbolByName (const char * Name, int Version)
Definition at line 901 of file api.cpp.
 {
     switch (Version)
     {
     case 0:
     {
         for (auto sym : APISymbols_v0)
         {
             if (strcmp(Name, sym.Name) != 0)
                 continue;
             debug("Symbol %s found in API version %d", Name, Version);
             return sym.Function;
         }
         break;
     }
     default:
         assert(!"Invalid API version");
     }
     error("Symbol %s not found in API version %d", Name, Version);
     KPrint("Driver API symbol \"%s\" not found!", Name);
     return (void *)__KernelUndefinedFunction;
 }
References __KernelUndefinedFunction(), APISymbols_v0, assert, debug, error, KPrint(), Name, and strcmp.
Referenced by Driver::Manager::LoadDriverFile().
Variable Documentation
APISymbols_v0
struct APISymbols APISymbols_v0[] static
Definition at line 1 of file api.cpp.
Referenced by GetSymbolByName().