Fennix: Userspace/apps/base/busybox/miscutils/setserial.c File Reference
setserial.c File Reference
#include "libbb.h"
#include <assert.h>
Data Structures
struct serial_struct
Macros
#define PORT_UNKNOWN 0
#define PORT_8250 1
#define PORT_16450 2
#define PORT_16550 3
#define PORT_16550A 4
#define PORT_CIRRUS 5
#define PORT_16650 6
#define PORT_16650V2 7
#define PORT_16750 8
#define PORT_STARTECH 9
#define PORT_16C950 10
#define PORT_16654 11
#define PORT_16850 12
#define PORT_RSA 13
#define PORT_NS16550A 14
#define PORT_XSCALE 15
#define PORT_RM9000 16
#define PORT_OCTEON 17
#define PORT_AR7 18
#define PORT_U6_16550A 19
#define ASYNCB_HUP_NOTIFY 0
#define ASYNCB_FOURPORT 1
#define ASYNCB_SAK 2
#define ASYNCB_SPLIT_TERMIOS 3
#define ASYNCB_SPD_HI 4
#define ASYNCB_SPD_VHI 5
#define ASYNCB_SKIP_TEST 6
#define ASYNCB_AUTO_IRQ 7
#define ASYNCB_SESSION_LOCKOUT 8
#define ASYNCB_PGRP_LOCKOUT 9
#define ASYNCB_CALLOUT_NOHUP 10
#define ASYNCB_SPD_SHI 12
#define ASYNCB_LOW_LATENCY 13
#define ASYNCB_BUGGY_UART 14
#define ASYNC_HUP_NOTIFY (1U << ASYNCB_HUP_NOTIFY)
#define ASYNC_FOURPORT (1U << ASYNCB_FOURPORT)
#define ASYNC_SAK (1U << ASYNCB_SAK)
#define ASYNC_SPLIT_TERMIOS (1U << ASYNCB_SPLIT_TERMIOS)
#define ASYNC_SPD_HI (1U << ASYNCB_SPD_HI)
#define ASYNC_SPD_VHI (1U << ASYNCB_SPD_VHI)
#define ASYNC_SKIP_TEST (1U << ASYNCB_SKIP_TEST)
#define ASYNC_AUTO_IRQ (1U << ASYNCB_AUTO_IRQ)
#define ASYNC_SESSION_LOCKOUT (1U << ASYNCB_SESSION_LOCKOUT)
#define ASYNC_PGRP_LOCKOUT (1U << ASYNCB_PGRP_LOCKOUT)
#define ASYNC_CALLOUT_NOHUP (1U << ASYNCB_CALLOUT_NOHUP)
#define ASYNC_SPD_SHI (1U << ASYNCB_SPD_SHI)
#define ASYNC_LOW_LATENCY (1U << ASYNCB_LOW_LATENCY)
#define ASYNC_BUGGY_UART (1U << ASYNCB_BUGGY_UART)
#define ASYNC_SPD_CUST (ASYNC_SPD_HI|ASYNC_SPD_VHI)
#define ASYNC_SPD_WARP (ASYNC_SPD_HI|ASYNC_SPD_SHI)
#define ASYNC_SPD_MASK (ASYNC_SPD_HI|ASYNC_SPD_VHI|ASYNC_SPD_SHI)
#define ASYNC_CLOSING_WAIT_INF 0
#define ASYNC_CLOSING_WAIT_NONE 65535
#define OPT_PRINT_SUMMARY (1 << 0)
#define OPT_PRINT_FEDBACK (1 << 1)
#define OPT_PRINT_ALL (1 << 2)
#define OPT_VERBOSE (1 << 3)
#define OPT_ZERO (1 << 4)
#define OPT_LIST_OF_DEVS (1 << 5)
#define OPT_MODE_MASK (OPT_PRINT_ALL | OPT_PRINT_SUMMARY | OPT_PRINT_FEDBACK)
#define CTL_SET (1 << 0)
#define CTL_CONFIG (1 << 1)
#define CTL_GET (1 << 2)
#define CTL_CLOSE (1 << 3)
#define CTL_NODIE (1 << 4)
#define MAX_SERIAL_TYPE 19
#define ALL_SPD
#define ALL_FLAGS
#define STR_INFINITE "infinite"
#define STR_NONE "none"
Enumerations
enum print_mode { PRINT_NORMAL = 0 , PRINT_SUMMARY = (1 << 0) , PRINT_FEDBACK = (1 << 1) , PRINT_ALL = (1 << 2) }
enum {
CMD_SPD_NORMAL = 0 , CMD_SPD_HI , CMD_SPD_VHI , CMD_SPD_SHI ,
CMD_SPD_WARP , CMD_SPD_CUST , CMD_FLAG_SAK , CMD_FLAG_FOURPORT ,
CMD_FLAG_NUP_NOTIFY , CMD_FLAG_SKIP_TEST , CMD_FLAG_AUTO_IRQ , CMD_FLAG_SPLIT_TERMIOS ,
CMD_FLAG_SESSION_LOCKOUT , CMD_FLAG_PGRP_LOCKOUT , CMD_FLAG_CALLOUT_NOHUP , CMD_FLAG_LOW_LATENCY ,
CMD_PORT , CMD_IRQ , CMD_DIVISOR , CMD_UART ,
CMD_BASE , CMD_DELAY , CMD_WAIT , CMD_AUTOCONFIG ,
CMD_FLAG_FIRST = CMD_FLAG_SAK , CMD_FLAG_LAST = CMD_FLAG_LOW_LATENCY
}
Functions
static bool cmd_noprint (int cmd)
static bool cmd_is_flag (int cmd)
static bool cmd_needs_arg (int cmd)
static const char * uart_type (int type)
static int index_in_strings_case_insensitive (const char *strings, const char *key)
static int uart_id (const char *name)
static const char * get_spd (int flags, enum print_mode mode)
static int get_numeric (const char *arg)
static int get_wait (const char *arg)
static int get_uart (const char *arg)
static int serial_open (const char *dev, bool quiet)
static int serial_ctl (int fd, int ops, struct serial_struct *serinfo)
static void print_flag (const char **prefix, const char *flag)
static void print_serial_flags (int serial_flags, enum print_mode mode, const char *prefix, const char *postfix)
static void print_closing_wait (unsigned int closing_wait)
static void serial_get (const char *device, enum print_mode mode)
static int find_cmd (const char *cmd)
static void serial_set (char **arg, int opts)
int setserial_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char serial_types[] ALIGN1
static const uint16_t setbits[CMD_FLAG_LAST+1] ALIGN2
Data Structure Documentation
serial_struct
struct serial_struct
Definition at line 188 of file setserial.c.
Data Fields
int baud_base
unsigned short close_delay
unsigned short closing_wait
unsigned short closing_wait2
int custom_divisor
int flags
int hub6
char io_type
unsigned long iomap_base
unsigned char * iomem_base
unsigned short iomem_reg_shift
int irq
int line
unsigned int port
unsigned int port_high
int reserved[1]
char reserved_char[1]
int type
int xmit_fifo_size
Macro Definition Documentation
ALL_FLAGS
#define ALL_FLAGS
Value:
    ( \
    ASYNC_SAK | ASYNC_FOURPORT | ASYNC_HUP_NOTIFY | \
    ASYNC_SKIP_TEST | ASYNC_AUTO_IRQ | ASYNC_SPLIT_TERMIOS | \
    ASYNC_SESSION_LOCKOUT | ASYNC_PGRP_LOCKOUT | ASYNC_CALLOUT_NOHUP | \
    ASYNC_LOW_LATENCY \
    )
Definition at line 373 of file setserial.c.
ALL_SPD
#define ALL_SPD
Value:
    ( \
    ASYNC_SPD_HI | ASYNC_SPD_VHI | ASYNC_SPD_SHI | \
    ASYNC_SPD_WARP | ASYNC_SPD_CUST \
    )
Definition at line 368 of file setserial.c.
ASYNC_AUTO_IRQ
#define ASYNC_AUTO_IRQ (1U << ASYNCB_AUTO_IRQ)
Definition at line 149 of file setserial.c.
ASYNC_BUGGY_UART
#define ASYNC_BUGGY_UART (1U << ASYNCB_BUGGY_UART)
Definition at line 167 of file setserial.c.
ASYNC_CALLOUT_NOHUP
#define ASYNC_CALLOUT_NOHUP (1U << ASYNCB_CALLOUT_NOHUP)
Definition at line 158 of file setserial.c.
ASYNC_CLOSING_WAIT_INF
#define ASYNC_CLOSING_WAIT_INF 0
Definition at line 181 of file setserial.c.
ASYNC_CLOSING_WAIT_NONE
#define ASYNC_CLOSING_WAIT_NONE 65535
Definition at line 184 of file setserial.c.
ASYNC_FOURPORT
#define ASYNC_FOURPORT (1U << ASYNCB_FOURPORT)
Definition at line 131 of file setserial.c.
ASYNC_HUP_NOTIFY
#define ASYNC_HUP_NOTIFY (1U << ASYNCB_HUP_NOTIFY)
Definition at line 128 of file setserial.c.
ASYNC_LOW_LATENCY
#define ASYNC_LOW_LATENCY (1U << ASYNCB_LOW_LATENCY)
Definition at line 164 of file setserial.c.
ASYNC_PGRP_LOCKOUT
#define ASYNC_PGRP_LOCKOUT (1U << ASYNCB_PGRP_LOCKOUT)
Definition at line 155 of file setserial.c.
ASYNC_SAK
#define ASYNC_SAK (1U << ASYNCB_SAK)
Definition at line 134 of file setserial.c.
ASYNC_SESSION_LOCKOUT
#define ASYNC_SESSION_LOCKOUT (1U << ASYNCB_SESSION_LOCKOUT)
Definition at line 152 of file setserial.c.
ASYNC_SKIP_TEST
#define ASYNC_SKIP_TEST (1U << ASYNCB_SKIP_TEST)
Definition at line 146 of file setserial.c.
ASYNC_SPD_CUST
#define ASYNC_SPD_CUST (ASYNC_SPD_HI|ASYNC_SPD_VHI)
Definition at line 171 of file setserial.c.
ASYNC_SPD_HI
#define ASYNC_SPD_HI (1U << ASYNCB_SPD_HI)
Definition at line 140 of file setserial.c.
ASYNC_SPD_MASK
#define ASYNC_SPD_MASK (ASYNC_SPD_HI|ASYNC_SPD_VHI|ASYNC_SPD_SHI)
Definition at line 177 of file setserial.c.
ASYNC_SPD_SHI
#define ASYNC_SPD_SHI (1U << ASYNCB_SPD_SHI)
Definition at line 161 of file setserial.c.
ASYNC_SPD_VHI
#define ASYNC_SPD_VHI (1U << ASYNCB_SPD_VHI)
Definition at line 143 of file setserial.c.
ASYNC_SPD_WARP
#define ASYNC_SPD_WARP (ASYNC_SPD_HI|ASYNC_SPD_SHI)
Definition at line 174 of file setserial.c.
ASYNC_SPLIT_TERMIOS
#define ASYNC_SPLIT_TERMIOS (1U << ASYNCB_SPLIT_TERMIOS)
Definition at line 137 of file setserial.c.
ASYNCB_AUTO_IRQ
#define ASYNCB_AUTO_IRQ 7
Definition at line 106 of file setserial.c.
ASYNCB_BUGGY_UART
#define ASYNCB_BUGGY_UART 14
Definition at line 124 of file setserial.c.
ASYNCB_CALLOUT_NOHUP
#define ASYNCB_CALLOUT_NOHUP 10
Definition at line 115 of file setserial.c.
ASYNCB_FOURPORT
#define ASYNCB_FOURPORT 1
Definition at line 88 of file setserial.c.
ASYNCB_HUP_NOTIFY
#define ASYNCB_HUP_NOTIFY 0
Definition at line 85 of file setserial.c.
ASYNCB_LOW_LATENCY
#define ASYNCB_LOW_LATENCY 13
Definition at line 121 of file setserial.c.
ASYNCB_PGRP_LOCKOUT
#define ASYNCB_PGRP_LOCKOUT 9
Definition at line 112 of file setserial.c.
ASYNCB_SAK
#define ASYNCB_SAK 2
Definition at line 91 of file setserial.c.
ASYNCB_SESSION_LOCKOUT
#define ASYNCB_SESSION_LOCKOUT 8
Definition at line 109 of file setserial.c.
ASYNCB_SKIP_TEST
#define ASYNCB_SKIP_TEST 6
Definition at line 103 of file setserial.c.
ASYNCB_SPD_HI
#define ASYNCB_SPD_HI 4
Definition at line 97 of file setserial.c.
ASYNCB_SPD_SHI
#define ASYNCB_SPD_SHI 12
Definition at line 118 of file setserial.c.
ASYNCB_SPD_VHI
#define ASYNCB_SPD_VHI 5
Definition at line 100 of file setserial.c.
ASYNCB_SPLIT_TERMIOS
#define ASYNCB_SPLIT_TERMIOS 3
Definition at line 94 of file setserial.c.
CTL_CLOSE
#define CTL_CLOSE (1 << 3)
Definition at line 255 of file setserial.c.
CTL_CONFIG
#define CTL_CONFIG (1 << 1)
Definition at line 253 of file setserial.c.
CTL_GET
#define CTL_GET (1 << 2)
Definition at line 254 of file setserial.c.
CTL_NODIE
#define CTL_NODIE (1 << 4)
Definition at line 256 of file setserial.c.
CTL_SET
#define CTL_SET (1 << 0)
Definition at line 252 of file setserial.c.
MAX_SERIAL_TYPE
#define MAX_SERIAL_TYPE 19
Definition at line 284 of file setserial.c.
OPT_LIST_OF_DEVS
#define OPT_LIST_OF_DEVS (1 << 5)
Definition at line 238 of file setserial.c.
OPT_MODE_MASK
#define OPT_MODE_MASK (OPT_PRINT_ALL | OPT_PRINT_SUMMARY | OPT_PRINT_FEDBACK)
Definition at line 241 of file setserial.c.
OPT_PRINT_ALL
#define OPT_PRINT_ALL (1 << 2)
Definition at line 235 of file setserial.c.
OPT_PRINT_FEDBACK
#define OPT_PRINT_FEDBACK (1 << 1)
Definition at line 234 of file setserial.c.
OPT_PRINT_SUMMARY
#define OPT_PRINT_SUMMARY (1 << 0)
Definition at line 233 of file setserial.c.
OPT_VERBOSE
#define OPT_VERBOSE (1 << 3)
Definition at line 236 of file setserial.c.
OPT_ZERO
#define OPT_ZERO (1 << 4)
Definition at line 237 of file setserial.c.
PORT_16450
#define PORT_16450 2
Definition at line 30 of file setserial.c.
PORT_16550
#define PORT_16550 3
Definition at line 33 of file setserial.c.
PORT_16550A
#define PORT_16550A 4
Definition at line 36 of file setserial.c.
PORT_16650
#define PORT_16650 6
Definition at line 42 of file setserial.c.
PORT_16650V2
#define PORT_16650V2 7
Definition at line 45 of file setserial.c.
PORT_16654
#define PORT_16654 11
Definition at line 57 of file setserial.c.
PORT_16750
#define PORT_16750 8
Definition at line 48 of file setserial.c.
PORT_16850
#define PORT_16850 12
Definition at line 60 of file setserial.c.
PORT_16C950
#define PORT_16C950 10
Definition at line 54 of file setserial.c.
PORT_8250
#define PORT_8250 1
Definition at line 27 of file setserial.c.
PORT_AR7
#define PORT_AR7 18
Definition at line 78 of file setserial.c.
PORT_CIRRUS
#define PORT_CIRRUS 5
Definition at line 39 of file setserial.c.
PORT_NS16550A
#define PORT_NS16550A 14
Definition at line 66 of file setserial.c.
PORT_OCTEON
#define PORT_OCTEON 17
Definition at line 75 of file setserial.c.
PORT_RM9000
#define PORT_RM9000 16
Definition at line 72 of file setserial.c.
PORT_RSA
#define PORT_RSA 13
Definition at line 63 of file setserial.c.
PORT_STARTECH
#define PORT_STARTECH 9
Definition at line 51 of file setserial.c.
PORT_U6_16550A
#define PORT_U6_16550A 19
Definition at line 81 of file setserial.c.
PORT_UNKNOWN
#define PORT_UNKNOWN 0
Definition at line 24 of file setserial.c.
PORT_XSCALE
#define PORT_XSCALE 15
Definition at line 69 of file setserial.c.
STR_INFINITE
#define STR_INFINITE "infinite"
Definition at line 404 of file setserial.c.
STR_NONE
#define STR_NONE "none"
Definition at line 405 of file setserial.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CMD_SPD_NORMAL
CMD_SPD_HI
CMD_SPD_VHI
CMD_SPD_SHI
CMD_SPD_WARP
CMD_SPD_CUST
CMD_FLAG_SAK
CMD_FLAG_FOURPORT
CMD_FLAG_NUP_NOTIFY
CMD_FLAG_SKIP_TEST
CMD_FLAG_AUTO_IRQ
CMD_FLAG_SPLIT_TERMIOS
CMD_FLAG_SESSION_LOCKOUT
CMD_FLAG_PGRP_LOCKOUT
CMD_FLAG_CALLOUT_NOHUP
CMD_FLAG_LOW_LATENCY
CMD_PORT
CMD_IRQ
CMD_DIVISOR
CMD_UART
CMD_BASE
CMD_DELAY
CMD_WAIT
CMD_AUTOCONFIG
CMD_FLAG_FIRST
CMD_FLAG_LAST
Definition at line 319 of file setserial.c.
 {
     CMD_SPD_NORMAL = 0,
     CMD_SPD_HI,
     CMD_SPD_VHI,
     CMD_SPD_SHI,
     CMD_SPD_WARP,
     CMD_SPD_CUST,
     CMD_FLAG_SAK,
     CMD_FLAG_FOURPORT,
     CMD_FLAG_NUP_NOTIFY,
     CMD_FLAG_SKIP_TEST,
     CMD_FLAG_AUTO_IRQ,
     CMD_FLAG_SPLIT_TERMIOS,
     CMD_FLAG_SESSION_LOCKOUT,
     CMD_FLAG_PGRP_LOCKOUT,
     CMD_FLAG_CALLOUT_NOHUP,
     CMD_FLAG_LOW_LATENCY,
     CMD_PORT,
     CMD_IRQ,
     CMD_DIVISOR,
     CMD_UART,
     CMD_BASE,
     CMD_DELAY,
     CMD_WAIT,
     CMD_AUTOCONFIG,
     CMD_FLAG_FIRST = CMD_FLAG_SAK,
     CMD_FLAG_LAST  = CMD_FLAG_LOW_LATENCY,
 };
print_mode
enum print_mode
Enumerator
PRINT_NORMAL
PRINT_SUMMARY
PRINT_FEDBACK
PRINT_ALL
Definition at line 244 of file setserial.c.
 {
     PRINT_NORMAL  = 0,
     PRINT_SUMMARY = (1 << 0),
     PRINT_FEDBACK = (1 << 1),
     PRINT_ALL     = (1 << 2),
 };
Function Documentation
cmd_is_flag()
static bool cmd_is_flag (int cmd) static
Definition at line 358 of file setserial.c.
 {
     return (cmd >= CMD_FLAG_FIRST && cmd <= CMD_FLAG_LAST);
 }
References cmd, CMD_FLAG_FIRST, and CMD_FLAG_LAST.
Referenced by serial_set().
cmd_needs_arg()
static bool cmd_needs_arg (int cmd) static
Definition at line 363 of file setserial.c.
 {
     return (cmd >= CMD_PORT && cmd <= CMD_WAIT);
 }
References cmd, CMD_PORT, and CMD_WAIT.
Referenced by serial_set().
cmd_noprint()
static bool cmd_noprint (int cmd) static
Definition at line 353 of file setserial.c.
 {
     return (cmd >= CMD_FLAG_SKIP_TEST && cmd <= CMD_FLAG_CALLOUT_NOHUP);
 }
References cmd, CMD_FLAG_CALLOUT_NOHUP, and CMD_FLAG_SKIP_TEST.
Referenced by print_serial_flags().
find_cmd()
static int find_cmd (const char * cmd) static
Definition at line 638 of file setserial.c.
 {
     int idx;
     idx = index_in_strings_case_insensitive(commands, cmd);
     if (idx < 0)
         bb_error_msg_and_die("invalid flag: %s", cmd);
     return idx;
 }
References bb_error_msg_and_die(), cmd, commands, idx, and index_in_strings_case_insensitive().
Referenced by serial_set().
get_numeric()
static int get_numeric (const char * arg) static
Definition at line 464 of file setserial.c.
 {
     return bb_strtol(arg, NULL, 0);
 }
References bb_strtol(), and NULL.
Referenced by get_wait(), and serial_set().
get_spd()
static const char* get_spd (int flags, enum print_mode mode) static
Definition at line 435 of file setserial.c.
 {
     int idx;
     switch (flags & ASYNC_SPD_MASK) {
     case ASYNC_SPD_HI:
         idx = CMD_SPD_HI;
         break;
     case ASYNC_SPD_VHI:
         idx = CMD_SPD_VHI;
         break;
     case ASYNC_SPD_SHI:
         idx = CMD_SPD_SHI;
         break;
     case ASYNC_SPD_WARP:
         idx = CMD_SPD_WARP;
         break;
     case ASYNC_SPD_CUST:
         idx = CMD_SPD_CUST;
         break;
     default:
         if (mode < PRINT_FEDBACK)
             return NULL;
         idx = CMD_SPD_NORMAL;
     }
     return nth_string(commands, idx);
 }
References ASYNC_SPD_CUST, ASYNC_SPD_HI, ASYNC_SPD_MASK, ASYNC_SPD_SHI, ASYNC_SPD_VHI, ASYNC_SPD_WARP, CMD_SPD_CUST, CMD_SPD_HI, CMD_SPD_NORMAL, CMD_SPD_SHI, CMD_SPD_VHI, CMD_SPD_WARP, commands, flags, idx, nth_string(), NULL, and PRINT_FEDBACK.
Referenced by print_serial_flags().
get_uart()
static int get_uart (const char * arg) static
Definition at line 480 of file setserial.c.
 {
     int uart = uart_id(arg);
     if (uart < 0)
         bb_error_msg_and_die("illegal UART type: %s", arg);
     return uart;
 }
References bb_error_msg_and_die(), and uart_id().
Referenced by serial_set().
get_wait()
static int get_wait (const char * arg) static
Definition at line 469 of file setserial.c.
 {
     if (strcasecmp(arg, STR_NONE) == 0)
         return ASYNC_CLOSING_WAIT_NONE;
     if (strcasecmp(arg, STR_INFINITE) == 0)
         return ASYNC_CLOSING_WAIT_INF;
     return get_numeric(arg);
 }
References ASYNC_CLOSING_WAIT_INF, ASYNC_CLOSING_WAIT_NONE, get_numeric(), STR_INFINITE, STR_NONE, and strcasecmp.
Referenced by serial_set().
index_in_strings_case_insensitive()
static int index_in_strings_case_insensitive (const char * strings, const char * key) static
Definition at line 416 of file setserial.c.
 {
     int idx = 0;
     while (*strings) {
         if (strcasecmp(strings, key) == 0) {
             return idx;
         }
         strings += strlen(strings) + 1; /* skip NUL */
         idx++;
     }
     return -1;
 }
References idx, strcasecmp, strings, and strlen().
Referenced by find_cmd(), and uart_id().
print_closing_wait()
static void print_closing_wait (unsigned int closing_wait) static
Definition at line 570 of file setserial.c.
 {
     switch (closing_wait) {
     case ASYNC_CLOSING_WAIT_NONE:
         puts(STR_NONE);
         break;
     case ASYNC_CLOSING_WAIT_INF:
         puts(STR_INFINITE);
         break;
     default:
         printf("%u\n", closing_wait);
     }
 }
References ASYNC_CLOSING_WAIT_INF, ASYNC_CLOSING_WAIT_NONE, printf, puts(), STR_INFINITE, and STR_NONE.
Referenced by serial_get().
print_flag()
static void print_flag (const char ** prefix, const char * flag) static
Definition at line 541 of file setserial.c.
 {
     printf("%s%s", *prefix, flag);
     *prefix = " ";
 }
References prefix(), and printf.
Referenced by print_serial_flags().
print_serial_flags()
static void print_serial_flags (int serial_flags, enum print_mode mode, const char * prefix, const char * postfix) static
Definition at line 547 of file setserial.c.
 {
     int i;
     const char *spd, *pr;
     pr = prefix;
     spd = get_spd(serial_flags, mode);
     if (spd)
         print_flag(&pr, spd);
     for (i = CMD_FLAG_FIRST; i <= CMD_FLAG_LAST; i++) {
         if ((serial_flags & setbits[i])
          && (mode > PRINT_SUMMARY || !cmd_noprint(i))
         ) {
             print_flag(&pr, nth_string(commands, i));
         }
     }
     puts(pr == prefix ? "" : postfix);
 }
References CMD_FLAG_FIRST, CMD_FLAG_LAST, cmd_noprint(), commands, get_spd(), i, nth_string(), prefix(), print_flag(), PRINT_SUMMARY, and puts().
Referenced by serial_get().
serial_ctl()
static int serial_ctl (int fd, int ops, struct serial_struct * serinfo) static
Definition at line 501 of file setserial.c.
 {
     int ret = 0;
     const char *err;
     if (ops & CTL_SET) {
         ret = ioctl(fd, TIOCSSERIAL, serinfo);
         if (ret < 0) {
             err = "can't set serial info";
             goto fail;
         }
     }
     if (ops & CTL_CONFIG) {
         ret = ioctl(fd, TIOCSERCONFIG);
         if (ret < 0) {
             err = "can't autoconfigure port";
             goto fail;
         }
     }
     if (ops & CTL_GET) {
         ret = ioctl(fd, TIOCGSERIAL, serinfo);
         if (ret < 0) {
             err = "can't get serial info";
             goto fail;
         }
     }
  nodie:
     if (ops & CTL_CLOSE)
         close(fd);
     return ret;
  fail:
     bb_simple_perror_msg(err);
     if (ops & CTL_NODIE)
         goto nodie;
     exit(EXIT_FAILURE);
 }
References bb_simple_perror_msg(), close(), CTL_CLOSE, CTL_CONFIG, CTL_GET, CTL_NODIE, CTL_SET, err(), exit(), EXIT_FAILURE, fd, ioctl(), TIOCGSERIAL, TIOCSERCONFIG, and TIOCSSERIAL.
Referenced by serial_get(), and serial_set().
serial_get()
static void serial_get (const char * device, enum print_mode mode) static
Definition at line 584 of file setserial.c.
 {
     int fd, ret;
     const char *uart, *prefix, *postfix;
     struct serial_struct serinfo;
     fd = serial_open(device, /*quiet:*/ mode == PRINT_SUMMARY);
     if (fd < 0)
         return;
     ret = serial_ctl(fd, CTL_GET | CTL_CLOSE | CTL_NODIE, &serinfo);
     if (ret < 0)
         return;
     uart = uart_type(serinfo.type);
     prefix = ", Flags: ";
     postfix = "";
     switch (mode) {
     case PRINT_NORMAL:
         printf("%s, UART: %s, Port: 0x%.4x, IRQ: %d",
             device, uart, serinfo.port, serinfo.irq);
         break;
     case PRINT_SUMMARY:
         if (!serinfo.type)
             return;
         printf("%s at 0x%.4x (irq = %d) is a %s",
             device, serinfo.port, serinfo.irq, uart);
         prefix = " (";
         postfix = ")";
         break;
     case PRINT_FEDBACK:
         printf("%s uart %s port 0x%.4x irq %d baud_base %d", device,
             uart, serinfo.port, serinfo.irq, serinfo.baud_base);
         prefix = " ";
         break;
     case PRINT_ALL:
         printf("%s, Line %d, UART: %s, Port: 0x%.4x, IRQ: %d\n",
             device, serinfo.line, uart, serinfo.port, serinfo.irq);
         printf("\tBaud_base: %d, close_delay: %u, divisor: %d\n",
             serinfo.baud_base, serinfo.close_delay,
             serinfo.custom_divisor);
         printf("\tclosing_wait: ");
         print_closing_wait(serinfo.closing_wait);
         prefix = "\tFlags: ";
         postfix = "\n";
         break;
     default:
         assert(0);
     }
     print_serial_flags(serinfo.flags, mode, prefix, postfix);
 }
References assert, serial_struct::baud_base, serial_struct::close_delay, serial_struct::closing_wait, CTL_CLOSE, CTL_GET, CTL_NODIE, serial_struct::custom_divisor, device, fd, serial_struct::flags, serial_struct::irq, serial_struct::line, serial_struct::port, prefix(), PRINT_ALL, print_closing_wait(), PRINT_FEDBACK, PRINT_NORMAL, print_serial_flags(), PRINT_SUMMARY, printf, serial_ctl(), serial_open(), serial_struct::type, and uart_type().
Referenced by setserial_main().
serial_open()
static int serial_open (const char * dev, bool quiet) static
Definition at line 490 of file setserial.c.
 {
     int fd;
     fd = device_open(dev, O_RDWR | O_NONBLOCK);
     if (fd < 0 && !quiet)
         bb_simple_perror_msg(dev);
     return fd;
 }
References bb_simple_perror_msg(), device_open(), fd, O_NONBLOCK, and O_RDWR.
Referenced by serial_get(), and serial_set().
serial_set()
static void serial_set (char ** arg, int opts) static
Definition at line 649 of file setserial.c.
 {
     struct serial_struct serinfo;
     int fd;
     fd = serial_open(*arg, /*quiet:*/ false);
     if (fd < 0)
         exit(201);
     serial_ctl(fd, CTL_GET, &serinfo);
     if (opts & OPT_ZERO)
         serinfo.flags = 0;
     while (*++arg) {
         const char *word;
         int invert;
         int cmd;
         word = *arg;
         invert = (word[0] == '^');
         word += invert;
         cmd = find_cmd(word);
         if (cmd_needs_arg(cmd))
             if (*++arg == NULL)
                 bb_error_msg_and_die(bb_msg_requires_arg, word);
         if (invert && !cmd_is_flag(cmd))
             bb_error_msg_and_die("can't invert %s", word);
         switch (cmd) {
         case CMD_SPD_NORMAL:
         case CMD_SPD_HI:
         case CMD_SPD_VHI:
         case CMD_SPD_SHI:
         case CMD_SPD_WARP:
         case CMD_SPD_CUST:
             serinfo.flags &= ~ASYNC_SPD_MASK;
             /* fallthrough */
         case CMD_FLAG_SAK:
         case CMD_FLAG_FOURPORT:
         case CMD_FLAG_NUP_NOTIFY:
         case CMD_FLAG_SKIP_TEST:
         case CMD_FLAG_AUTO_IRQ:
         case CMD_FLAG_SPLIT_TERMIOS:
         case CMD_FLAG_SESSION_LOCKOUT:
         case CMD_FLAG_PGRP_LOCKOUT:
         case CMD_FLAG_CALLOUT_NOHUP:
         case CMD_FLAG_LOW_LATENCY:
             if (invert)
                 serinfo.flags &= ~setbits[cmd];
             else
                 serinfo.flags |= setbits[cmd];
             break;
         case CMD_PORT:
             serinfo.port = get_numeric(*arg);
             break;
         case CMD_IRQ:
             serinfo.irq = get_numeric(*arg);
             break;
         case CMD_DIVISOR:
             serinfo.custom_divisor = get_numeric(*arg);
             break;
         case CMD_UART:
             serinfo.type = get_uart(*arg);
             break;
         case CMD_BASE:
             serinfo.baud_base = get_numeric(*arg);
             break;
         case CMD_DELAY:
             serinfo.close_delay = get_numeric(*arg);
             break;
         case CMD_WAIT:
             serinfo.closing_wait = get_wait(*arg);
             break;
         case CMD_AUTOCONFIG:
             serial_ctl(fd, CTL_SET | CTL_CONFIG | CTL_GET, &serinfo);
             break;
         default:
             assert(0);
         }
     }
     serial_ctl(fd, CTL_SET | CTL_CLOSE, &serinfo);
 }
References assert, ASYNC_SPD_MASK, serial_struct::baud_base, bb_error_msg_and_die(), serial_struct::close_delay, serial_struct::closing_wait, cmd, CMD_AUTOCONFIG, CMD_BASE, CMD_DELAY, CMD_DIVISOR, CMD_FLAG_AUTO_IRQ, CMD_FLAG_CALLOUT_NOHUP, CMD_FLAG_FOURPORT, CMD_FLAG_LOW_LATENCY, CMD_FLAG_NUP_NOTIFY, CMD_FLAG_PGRP_LOCKOUT, CMD_FLAG_SAK, CMD_FLAG_SESSION_LOCKOUT, CMD_FLAG_SKIP_TEST, CMD_FLAG_SPLIT_TERMIOS, CMD_IRQ, cmd_is_flag(), cmd_needs_arg(), CMD_PORT, CMD_SPD_CUST, CMD_SPD_HI, CMD_SPD_NORMAL, CMD_SPD_SHI, CMD_SPD_VHI, CMD_SPD_WARP, CMD_UART, CMD_WAIT, CTL_CLOSE, CTL_CONFIG, CTL_GET, CTL_SET, serial_struct::custom_divisor, exit(), fd, find_cmd(), serial_struct::flags, get_numeric(), get_uart(), get_wait(), serial_struct::irq, NULL, OPT_ZERO, serial_struct::port, serial_ctl(), serial_open(), and serial_struct::type.
Referenced by setserial_main().
setserial_main()
int setserial_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 738 of file setserial.c.
 {
     int opts;
     opts = getopt32(argv, "^" "bGavzgq" "\0" "-1:b-aG:G-ab:a-bG");
     argv += optind;
     if (!argv[1]) /* one arg only? (nothing to change?) */
         opts |= OPT_LIST_OF_DEVS; /* force display */
     if (!(opts & OPT_LIST_OF_DEVS)) {
         serial_set(argv, opts);
         argv[1] = NULL;
     }
     /* -v effect: "after setting params, do not be silent, show them" */
     if (opts & (OPT_VERBOSE | OPT_LIST_OF_DEVS)) {
         do {
             serial_get(*argv, opts & OPT_MODE_MASK);
         } while (*++argv);
     }
     return EXIT_SUCCESS;
 }
References argv, EXIT_SUCCESS, getopt32(), NULL, OPT_LIST_OF_DEVS, OPT_MODE_MASK, OPT_VERBOSE, optind, serial_get(), and serial_set().
uart_id()
static int uart_id (const char * name) static
Definition at line 430 of file setserial.c.
 {
     return index_in_strings_case_insensitive(serial_types, name);
 }
References index_in_strings_case_insensitive().
Referenced by get_uart().
uart_type()
static const char* uart_type (int type) static
Definition at line 407 of file setserial.c.
 {
     if (type > MAX_SERIAL_TYPE)
         return "undefined";
     return nth_string(serial_types, type);
 }
References MAX_SERIAL_TYPE, nth_string(), and type.
Referenced by serial_get().
Variable Documentation
ALIGN1
const char commands [] ALIGN1 static
Initial value:
=
    "unknown\0"
    "8250\0"
    "16450\0"
    "16550\0"
    "16550A\0"
    "Cirrus\0"
    "16650\0"
    "16650V2\0"
    "16750\0"
    "16950\0"
    "16954\0"
    "16654\0"
    "16850\0"
    "RSA\0"
    "NS16550A\0"
    "XSCALE\0"
    "RM9000\0"
    "OCTEON\0"
    "AR7\0"
    "U6_16550A\0"
Definition at line 258 of file setserial.c.
ALIGN2
const uint16_t setbits [CMD_FLAG_LAST + 1] ALIGN2 static
Initial value:
= {
    0,
    ASYNC_SPD_HI,
    ASYNC_SPD_VHI,
    ASYNC_SPD_SHI,
    ASYNC_SPD_WARP,
    ASYNC_SPD_CUST,
    ASYNC_SAK,
    ASYNC_FOURPORT,
    ASYNC_HUP_NOTIFY,
    ASYNC_SKIP_TEST,
    ASYNC_AUTO_IRQ,
    ASYNC_SPLIT_TERMIOS,
    ASYNC_SESSION_LOCKOUT,
    ASYNC_PGRP_LOCKOUT,
    ASYNC_CALLOUT_NOHUP,
    ASYNC_LOW_LATENCY
}
Definition at line 384 of file setserial.c.