Fennix Userspace: Userspace/apps/base/busybox/util-linux/blkdiscard.c File Reference
blkdiscard.c File Reference
#include "libbb.h"
#include <linux/fs.h>
Macros
#define BLKDISCARD 0x1277
#define BLKSECDISCARD 0x127d
Functions
int blkdiscard_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
BLKDISCARD
#define BLKDISCARD 0x1277
Definition at line 35 of file blkdiscard.c.
BLKSECDISCARD
#define BLKSECDISCARD 0x127d
Definition at line 38 of file blkdiscard.c.
Function Documentation
blkdiscard_main()
int blkdiscard_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 42 of file blkdiscard.c.
 {
     unsigned opts;
     const char *offset_str = "0";
     const char *length_str;
     uint64_t offset; /* Leaving these two variables out does not  */
     uint64_t length; /* shrink code size and hampers readability. */
     uint64_t range[2];
     int fd;
     enum {
         OPT_OFFSET = (1 << 0),
         OPT_LENGTH = (1 << 1),
         OPT_SECURE = (1 << 2),
         OPT_FORCE  = (1 << 3), //nop
     };
     opts = getopt32(argv, "^" "o:l:sf" "\0" "=1", &offset_str, &length_str);
     argv += optind;
     fd = xopen(argv[0], O_RDWR|O_EXCL);
 //Why bother, BLK[SEC]DISCARD will fail on non-blockdevs anyway?
 //  xfstat(fd, &st);
 //  if (!S_ISBLK(st.st_mode))
 //      bb_error_msg_and_die("%s: not a block device", argv[0]);
     offset = xatoull_sfx(offset_str, kMG_suffixes);
     if (opts & OPT_LENGTH)
         length = xatoull_sfx(length_str, kMG_suffixes);
     else {
         xioctl(fd, BLKGETSIZE64, &length);
         length -= offset;
     }
     range[0] = offset;
     range[1] = length;
     ioctl_or_perror_and_die(fd,
             (opts & OPT_SECURE) ? BLKSECDISCARD : BLKDISCARD,
             &range,
             "%s: %s failed",
             argv[0],
             (opts & OPT_SECURE) ? "BLKSECDISCARD" : "BLKDISCARD"
     );
     if (ENABLE_FEATURE_CLEAN_UP)
         close(fd);
     return EXIT_SUCCESS;
 }
References argv, BLKDISCARD, BLKGETSIZE64, BLKSECDISCARD, close(), EXIT_SUCCESS, fd, getopt32(), ioctl_or_perror_and_die(), kMG_suffixes, O_EXCL, O_RDWR, offset, OPT_FORCE, optind, range, xioctl, and xopen().