Fennix Userspace: Userspace/apps/base/bash/lib/sh/strstr.c File Reference
strstr.c File Reference
#include <sys/types.h>
Typedefs
typedef unsigned chartype
Functions
char * strstr (const char *phaystack, const char *pneedle)
Typedef Documentation
chartype
typedef unsigned chartype
Definition at line 39 of file strstr.c.
Function Documentation
strstr()
char* strstr (const char * phaystack, const char * pneedle)
Definition at line 44 of file strstr.c.
 {
   register const unsigned char *haystack, *needle;
   register chartype b, c;
   haystack = (const unsigned char *) phaystack;
   needle = (const unsigned char *) pneedle;
   b = *needle;
   if (b != '\0')
     {
       haystack--;               /* possible ANSI violation */
       do
     {
       c = *++haystack;
       if (c == '\0')
         goto ret0;
     }
       while (c != b);
       c = *++needle;
       if (c == '\0')
     goto foundneedle;
       ++needle;
       goto jin;
       for (;;)
         {
           register chartype a;
       register const unsigned char *rhaystack, *rneedle;
       do
         {
           a = *++haystack;
           if (a == '\0')
         goto ret0;
           if (a == b)
         break;
           a = *++haystack;
           if (a == '\0')
         goto ret0;
 shloop:;    }
           while (a != b);
 jin:      a = *++haystack;
       if (a == '\0')
         goto ret0;
       if (a != c)
         goto shloop;
       rhaystack = haystack-- + 1;
       rneedle = needle;
       a = *rneedle;
       if (*rhaystack == a)
         do
           {
         if (a == '\0')
           goto foundneedle;
         ++rhaystack;
         a = *++needle;
         if (*rhaystack != a)
           break;
         if (a == '\0')
           goto foundneedle;
         ++rhaystack;
         a = *++needle;
           }
         while (*rhaystack == a);
       needle = rneedle;        /* took the register-poor approach */
       if (a == '\0')
         break;
         }
     }
 foundneedle:
   return (char*) haystack;
 ret0:
   return 0;
 }
References c.
Referenced by __get_resolv_conf(), __lookup_serv(), _nl_init_domain_conv(), add_links(), awk_getline(), count_strstr(), create_or_remember_link(), cut_out_ull_opt(), dump_procs(), exec_builtin(), find_action(), find_export_symbols(), get_irqs_from_interrupts(), getjob(), grep_file(), handle_incoming_and_exit(), hasmntopt(), index_status_file(), is_hpet_irq(), is_section_name(), M_StringReplace(), main(), make_device(), name_from_hosts(), nmeter_main(), nproc_main(), opt_in_list(), parse_url(), print_direc(), process_includes(), procnetdev_version(), rdval(), read_cstate_counts(), rl_history_search_internal(), scan_request(), scan_table(), send_file_and_exit(), singlemount(), strip_unsafe_prefix(), strrstr(), update_passwd(), wget_main(), write_status_file(), and xmalloc_substitute_string().