Fennix Userspace: Userspace/apps/base/busybox/coreutils/truncate.c File Reference
truncate.c File Reference
#include "libbb.h"
Macros
#define XATOU_SFX xatoul_sfx
Functions
int truncate_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
XATOU_SFX
#define XATOU_SFX xatoul_sfx
Definition at line 34 of file truncate.c.
Function Documentation
truncate_main()
int truncate_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 40 of file truncate.c.
 {
     unsigned opts;
     int flags = O_WRONLY | O_NONBLOCK;
     int ret = EXIT_SUCCESS;
     char *size_str;
     off_t size;
     enum {
         OPT_NOCREATE  = (1 << 0),
         OPT_SIZE = (1 << 1),
     };
     opts = getopt32(argv, "^" "cs:" "\0" "s:-1", &size_str);
     if (!(opts & OPT_NOCREATE))
         flags |= O_CREAT;
     // TODO: coreutils 8.17 also support "m" (lowercase) suffix
     // with truncate, but not with dd!
     // We share kMG_suffixes[], so we can't make both tools
     // compatible at once...
     size = XATOU_SFX(size_str, kMG_suffixes);
     argv += optind;
     while (*argv) {
         int fd = open(*argv, flags, 0666);
         if (fd < 0) {
             if (errno != ENOENT || !(opts & OPT_NOCREATE)) {
                 bb_perror_msg("%s: open", *argv);
                 ret = EXIT_FAILURE;
             }
             /* else: ENOENT && OPT_NOCREATE:
              * do not report error, exitcode is also 0.
              */
         } else {
             if (ftruncate(fd, size) == -1) {
                 bb_perror_msg("%s: truncate", *argv);
                 ret = EXIT_FAILURE;
             }
             xclose(fd);
         }
         ++argv;
     }
     return ret;
 }
References argv, bb_perror_msg(), ENOENT, errno, EXIT_FAILURE, EXIT_SUCCESS, fd, flags, ftruncate(), getopt32(), kMG_suffixes, O_CREAT, O_NONBLOCK, O_WRONLY, off_t, open(), OPT_SIZE, optind, size, XATOU_SFX, and xclose().