Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/hfs.c File Reference
hfs.c File Reference
#include "volume_id_internal.h"
Data Structures
struct hfs_finder_info
struct hfs_mdb
struct hfsplus_bnode_descriptor
struct hfsplus_bheader_record
struct hfsplus_catalog_key
struct hfsplus_extent
struct hfsplus_fork
struct hfsplus_vol_header
Macros
#define HFSPLUS_EXTENT_COUNT 8
#define HFS_SUPERBLOCK_OFFSET 0x400
#define HFS_NODE_LEAF 0xff
#define HFSPLUS_POR_CNID 1
#define hfs_id_len 8
Functions
static void FAST_FUNC hfs_set_uuid (struct volume_id *id, const uint8_t *hfs_id)
int FAST_FUNC volume_id_probe_hfs_hfsplus (struct volume_id *id)
Variables
struct hfs_finder_info PACKED
Data Structure Documentation
hfs_finder_info
struct hfs_finder_info
Definition at line 29 of file hfs.c.
Data Fields
uint32_t boot_folder
uint8_t id[8]
uint32_t open_folder
uint32_t os9_folder
uint32_t osx_folder
uint32_t reserved
uint32_t start_app
hfs_mdb
struct hfs_mdb
Definition at line 39 of file hfs.c.
Data Fields
uint16_t al_bl_st
uint32_t al_blk_size
uint16_t alloc_ptr
uint16_t atrb
uint32_t clp_size
uint32_t cr_date
uint32_t ct_clump_size
uint32_t dir_count
uint16_t embed_blockcount
uint8_t embed_sig[2]
uint16_t embed_startblock
uint32_t file_count
struct hfs_finder_info finder_info
uint16_t free_bks
uint8_t label[27]
uint8_t label_len
uint32_t ls_Mod
uint16_t nm_al_blks
uint16_t nm_fls
uint16_t num_root_dirs
uint32_t nxt_cnid
uint8_t signature[2]
uint16_t vbm_st
uint32_t vol_bkup
uint16_t vol_seq_num
uint32_t wr_cnt
uint32_t xt_clump_size
hfsplus_bnode_descriptor
struct hfsplus_bnode_descriptor
Definition at line 69 of file hfs.c.
Data Fields
uint8_t height
uint32_t next
uint16_t num_recs
uint32_t prev
uint16_t reserved
uint8_t type
hfsplus_bheader_record
struct hfsplus_bheader_record
Definition at line 78 of file hfs.c.
Data Fields
uint16_t depth
uint32_t leaf_count
uint32_t leaf_head
uint32_t leaf_tail
uint16_t node_size
uint32_t root
hfsplus_catalog_key
struct hfsplus_catalog_key
Definition at line 87 of file hfs.c.
Data Fields
uint16_t key_len
uint32_t parent_id
uint8_t unicode[255 *2]
uint16_t unicode_len
hfsplus_extent
struct hfsplus_extent
Definition at line 94 of file hfs.c.
Data Fields
uint32_t block_count
uint32_t start_block
hfsplus_fork
struct hfsplus_fork
Definition at line 100 of file hfs.c.
Data Fields
uint32_t clump_size
struct hfsplus_extent extents[HFSPLUS_EXTENT_COUNT]
uint32_t total_blocks
uint64_t total_size
hfsplus_vol_header
struct hfsplus_vol_header
Definition at line 107 of file hfs.c.
Data Fields
struct hfsplus_fork alloc_file
struct hfsplus_fork attr_file
uint32_t attributes
uint32_t backup_date
uint32_t blocksize
struct hfsplus_fork cat_file
uint32_t checked_date
uint32_t create_date
uint32_t data_clump_sz
uint64_t encodings_bmp
struct hfsplus_fork ext_file
uint32_t file_count
struct hfs_finder_info finder_info
uint32_t folder_count
uint32_t free_blocks
uint32_t last_mount_vers
uint32_t modify_date
uint32_t next_alloc
uint32_t next_cnid
uint32_t reserved
uint32_t rsrc_clump_sz
uint8_t signature[2]
struct hfsplus_fork start_file
uint32_t total_blocks
uint16_t version
uint32_t write_count
Macro Definition Documentation
hfs_id_len
#define hfs_id_len 8
HFS_NODE_LEAF
#define HFS_NODE_LEAF 0xff
Definition at line 137 of file hfs.c.
HFS_SUPERBLOCK_OFFSET
#define HFS_SUPERBLOCK_OFFSET 0x400
Definition at line 136 of file hfs.c.
HFSPLUS_EXTENT_COUNT
#define HFSPLUS_EXTENT_COUNT 8
Definition at line 99 of file hfs.c.
HFSPLUS_POR_CNID
#define HFSPLUS_POR_CNID 1
Definition at line 138 of file hfs.c.
Function Documentation
hfs_set_uuid()
static void FAST_FUNC hfs_set_uuid (struct volume_id * id, const uint8_t * hfs_id) static
Definition at line 140 of file hfs.c.
 {
 #define hfs_id_len 8
     md5_ctx_t md5c;
     uint8_t uuid[16];
     unsigned i;
     for (i = 0; i < hfs_id_len; i++)
         if (hfs_id[i] != 0)
             goto do_md5;
     return;
  do_md5:
     md5_begin(&md5c);
     md5_hash(&md5c, "\263\342\17\71\362\222\21\326\227\244\0\60\145\103\354\254", 16);
     md5_hash(&md5c, hfs_id, hfs_id_len);
     md5_end(&md5c, uuid);
     uuid[6] = 0x30 | (uuid[6] & 0x0f);
     uuid[8] = 0x80 | (uuid[8] & 0x3f);
     volume_id_set_uuid(id, uuid, UUID_DCE);
 }
References hfs_id_len, i, md5_begin(), md5_end(), md5_hash(), UUID_DCE, and volume_id_set_uuid().
Referenced by volume_id_probe_hfs_hfsplus().
volume_id_probe_hfs_hfsplus()
int FAST_FUNC volume_id_probe_hfs_hfsplus (struct volume_id * id)
Definition at line 161 of file hfs.c.
 {
     uint64_t off = 0;
     unsigned blocksize;
     unsigned cat_block;
     unsigned ext_block_start;
     unsigned ext_block_count;
     int ext;
     unsigned leaf_node_head;
     unsigned leaf_node_count;
     unsigned leaf_node_size;
     unsigned leaf_block;
     uint64_t leaf_off;
     unsigned alloc_block_size;
     unsigned alloc_first_block;
     unsigned embed_first_block;
     unsigned record_count;
     struct hfsplus_vol_header *hfsplus;
     struct hfsplus_bnode_descriptor *descr;
     struct hfsplus_bheader_record *bnode;
     struct hfsplus_catalog_key *key;
     unsigned label_len;
     struct hfsplus_extent extents[HFSPLUS_EXTENT_COUNT];
     struct hfs_mdb *hfs;
     const uint8_t *buf;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     buf = volume_id_get_buffer(id, off + HFS_SUPERBLOCK_OFFSET, 0x200);
     if (buf == NULL)
         return -1;
     hfs = (struct hfs_mdb *) buf;
     if (hfs->signature[0] != 'B' || hfs->signature[1] != 'D')
         goto checkplus;
     /* it may be just a hfs wrapper for hfs+ */
     if (hfs->embed_sig[0] == 'H' && hfs->embed_sig[1] == '+') {
         alloc_block_size = be32_to_cpu(hfs->al_blk_size);
         dbg("alloc_block_size 0x%x", alloc_block_size);
         alloc_first_block = be16_to_cpu(hfs->al_bl_st);
         dbg("alloc_first_block 0x%x", alloc_first_block);
         embed_first_block = be16_to_cpu(hfs->embed_startblock);
         dbg("embed_first_block 0x%x", embed_first_block);
         off += (alloc_first_block * 512) +
                (embed_first_block * alloc_block_size);
         dbg("hfs wrapped hfs+ found at offset 0x%llx", (unsigned long long) off);
         buf = volume_id_get_buffer(id, off + HFS_SUPERBLOCK_OFFSET, 0x200);
         if (buf == NULL)
             return -1;
         goto checkplus;
     }
     if (hfs->label_len > 0 && hfs->label_len < 28) {
 //      volume_id_set_label_raw(id, hfs->label, hfs->label_len);
         volume_id_set_label_string(id, hfs->label, hfs->label_len) ;
     }
     hfs_set_uuid(id, hfs->finder_info.id);
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "hfs";)
     return 0;
  checkplus:
     hfsplus = (struct hfsplus_vol_header *) buf;
     if (hfs->signature[0] == 'H')
         if (hfs->signature[1] == '+' || hfs->signature[1] == 'X')
             goto hfsplus;
     return -1;
  hfsplus:
     hfs_set_uuid(id, hfsplus->finder_info.id);
     blocksize = be32_to_cpu(hfsplus->blocksize);
     dbg("blocksize %u", blocksize);
     memcpy(extents, hfsplus->cat_file.extents, sizeof(extents));
     cat_block = be32_to_cpu(extents[0].start_block);
     dbg("catalog start block 0x%x", cat_block);
     buf = volume_id_get_buffer(id, off + (cat_block * blocksize), 0x2000);
     if (buf == NULL)
         goto found;
     bnode = (struct hfsplus_bheader_record *)
         &buf[sizeof(struct hfsplus_bnode_descriptor)];
     leaf_node_head = be32_to_cpu(bnode->leaf_head);
     dbg("catalog leaf node 0x%x", leaf_node_head);
     leaf_node_size = be16_to_cpu(bnode->node_size);
     dbg("leaf node size 0x%x", leaf_node_size);
     leaf_node_count = be32_to_cpu(bnode->leaf_count);
     dbg("leaf node count 0x%x", leaf_node_count);
     if (leaf_node_count == 0)
         goto found;
     leaf_block = (leaf_node_head * leaf_node_size) / blocksize;
     /* get physical location */
     for (ext = 0; ext < HFSPLUS_EXTENT_COUNT; ext++) {
         ext_block_start = be32_to_cpu(extents[ext].start_block);
         ext_block_count = be32_to_cpu(extents[ext].block_count);
         dbg("extent start block 0x%x, count 0x%x", ext_block_start, ext_block_count);
         if (ext_block_count == 0)
             goto found;
         /* this is our extent */
         if (leaf_block < ext_block_count)
             break;
         leaf_block -= ext_block_count;
     }
     if (ext == HFSPLUS_EXTENT_COUNT)
         goto found;
     dbg("found block in extent %i", ext);
     leaf_off = (ext_block_start + leaf_block) * blocksize;
     buf = volume_id_get_buffer(id, off + leaf_off, leaf_node_size);
     if (buf == NULL)
         goto found;
     descr = (struct hfsplus_bnode_descriptor *) buf;
     dbg("descriptor type 0x%x", descr->type);
     record_count = be16_to_cpu(descr->num_recs);
     dbg("number of records %u", record_count);
     if (record_count == 0)
         goto found;
     if (descr->type != HFS_NODE_LEAF)
         goto found;
     key = (struct hfsplus_catalog_key *)
         &buf[sizeof(struct hfsplus_bnode_descriptor)];
     dbg("parent id 0x%x", be32_to_cpu(key->parent_id));
     if (key->parent_id != cpu_to_be32(HFSPLUS_POR_CNID))
         goto found;
     label_len = be16_to_cpu(key->unicode_len) * 2;
     dbg("label unicode16 len %i", label_len);
 //  volume_id_set_label_raw(id, key->unicode, label_len);
     volume_id_set_label_unicode16(id, key->unicode, BE, label_len);
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "hfsplus";)
     return 0;
 }
References hfs_mdb::al_bl_st, hfs_mdb::al_blk_size, BE, be16_to_cpu, be32_to_cpu, hfsplus_vol_header::blocksize, buf, hfsplus_vol_header::cat_file, cpu_to_be32, dbg, hfs_mdb::embed_sig, hfs_mdb::embed_startblock, hfsplus_fork::extents, hfs_mdb::finder_info, hfsplus_vol_header::finder_info, found, HFS_NODE_LEAF, hfs_set_uuid(), HFS_SUPERBLOCK_OFFSET, HFSPLUS_EXTENT_COUNT, HFSPLUS_POR_CNID, hfs_finder_info::id, hfs_mdb::label, hfs_mdb::label_len, hfsplus_bheader_record::leaf_count, hfsplus_bheader_record::leaf_head, memcpy(), hfsplus_bheader_record::node_size, NULL, hfsplus_bnode_descriptor::num_recs, off, hfsplus_catalog_key::parent_id, hfs_mdb::signature, hfsplus_bnode_descriptor::type, hfsplus_catalog_key::unicode, hfsplus_catalog_key::unicode_len, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_label_unicode16().
Variable Documentation
PACKED
struct hfsplus_vol_header PACKED