Fennix Userspace: Userspace/mlibc/options/ansi/generic/complex/ctan.c File Reference
ctan.c File Reference
#include <complex.h>
#include <math.h>
#include "cephes_subr.h"
Functions
double complex ctan (double complex z)
Function Documentation
ctan()
double complex ctan (double complex z)
Definition at line 73 of file ctan.c.
 {
     double complex w;
     double d;
     d = cos(2.0 * creal(z)) + cosh(2.0 * cimag(z));
     if (fabs(d) < 0.25)
         d = __mlibc_ctans(z);
     if (d == 0.0) {
         /* mtherr ("ctan", OVERFLOW); */
         w = HUGE_VAL + HUGE_VAL * I;
         return w;
     }
     w = sin(2.0 * creal(z)) / d + (sinh(2.0 * cimag(z)) / d) * I;
     return w;
 }
References __mlibc_ctans(), cimag(), complex, cos(), cosh(), creal(), fabs(), HUGE_VAL, I, sin(), and sinh().