Fennix: Userspace/apps/base/busybox/util-linux/cal.c File Reference
cal.c File Reference
#include "libbb.h"
#include "unicode.h"
Macros
#define SUNDAY 0
#define MONDAY 1
#define THURSDAY 4 /* for reformation */
#define SATURDAY 6 /* 1 Jan 1 was a Saturday */
#define FIRST_MISSING_DAY 639787 /* 3 Sep 1752 */
#define NUMBER_MISSING_DAYS 11 /* 11 day correction */
#define MAXDAYS 42 /* max slots in a month array */
#define SPACE -1 /* used in day array */
#define julian ((unsigned)option_mask32)
#define centuries_since_1700(yr) ((yr) > 1700 ? (yr) / 100 - 17 : 0)
#define quad_centuries_since_1700(yr) ((yr) > 1600 ? ((yr) - 1600) / 400 : 0)
#define leap_years_since_year_1(yr) ((yr) / 4 - centuries_since_1700(yr) + quad_centuries_since_1700(yr))
#define DAY_LEN 3 /* 3 spaces per day */
#define J_DAY_LEN (DAY_LEN + 1)
#define WEEK_LEN 20 /* 7 * 3 - one space at the end */
#define J_WEEK_LEN (WEEK_LEN + 7)
#define HEAD_SEP 2 /* spaces between day headings */
Enumerations
enum { OPT_JULIAN = (1 << 0) , OPT_MONDAY = (1 << 1) , OPT_YEAR = (1 << 2) }
Functions
static int leap_year (unsigned yr)
static void center (char *, unsigned, unsigned)
static void day_array (unsigned, unsigned, unsigned, unsigned *)
static void trim_trailing_spaces_and_print (char *)
static void blank_string (char *buf, size_t buflen)
static char * build_row (char *p, unsigned *dp)
int cal_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const unsigned char days_in_month[] ALIGN1
Macro Definition Documentation
centuries_since_1700
#define centuries_since_1700 (yr) ((yr) > 1700 ? (yr) / 100 - 17 : 0)
Definition at line 75 of file cal.c.
DAY_LEN
#define DAY_LEN 3 /* 3 spaces per day */
Definition at line 93 of file cal.c.
FIRST_MISSING_DAY
#define FIRST_MISSING_DAY 639787 /* 3 Sep 1752 */
Definition at line 47 of file cal.c.
HEAD_SEP
#define HEAD_SEP 2 /* spaces between day headings */
Definition at line 97 of file cal.c.
J_DAY_LEN
#define J_DAY_LEN (DAY_LEN + 1)
Definition at line 94 of file cal.c.
J_WEEK_LEN
#define J_WEEK_LEN (WEEK_LEN + 7)
Definition at line 96 of file cal.c.
julian
#define julian ((unsigned)option_mask32)
Definition at line 64 of file cal.c.
leap_years_since_year_1
#define leap_years_since_year_1 (yr) ((yr) / 4 - centuries_since_1700(yr) + quad_centuries_since_1700(yr))
Definition at line 83 of file cal.c.
MAXDAYS
#define MAXDAYS 42 /* max slots in a month array */
Definition at line 50 of file cal.c.
MONDAY
#define MONDAY 1
Definition at line 43 of file cal.c.
NUMBER_MISSING_DAYS
#define NUMBER_MISSING_DAYS 11 /* 11 day correction */
Definition at line 48 of file cal.c.
quad_centuries_since_1700
#define quad_centuries_since_1700 (yr) ((yr) > 1600 ? ((yr) - 1600) / 400 : 0)
Definition at line 79 of file cal.c.
SATURDAY
#define SATURDAY 6 /* 1 Jan 1 was a Saturday */
Definition at line 45 of file cal.c.
SPACE
#define SPACE -1 /* used in day array */
Definition at line 51 of file cal.c.
SUNDAY
#define SUNDAY 0
Definition at line 42 of file cal.c.
THURSDAY
#define THURSDAY 4 /* for reformation */
Definition at line 44 of file cal.c.
WEEK_LEN
#define WEEK_LEN 20 /* 7 * 3 - one space at the end */
Definition at line 95 of file cal.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_JULIAN
OPT_MONDAY
OPT_YEAR
Definition at line 99 of file cal.c.
      {
     OPT_JULIAN = (1 << 0),
     OPT_MONDAY = (1 << 1),
     OPT_YEAR   = (1 << 2),
 };
Function Documentation
blank_string()
static void blank_string (char * buf, size_t buflen) static
Definition at line 335 of file cal.c.
 {
     memset(buf, ' ', buflen);
     buf[buflen-1] = '\0';
 }
References buf, buflen, and memset.
Referenced by cal_main().
build_row()
static char * build_row (char * p, unsigned * dp) static
Definition at line 341 of file cal.c.
 {
     unsigned col, val, day;
     memset(p, ' ', (julian + DAY_LEN) * 7);
     col = 0;
     do {
         day = *dp++;
         if (day != SPACE) {
             if (julian) {
                 ++p;
                 if (day >= 100) {
                     *p = '0';
                     p[-1] = (day / 100) + '0';
                     day %= 100;
                 }
             }
             val = day / 10;
             if (val > 0) {
                 *p = val + '0';
             }
             *++p = day % 10 + '0';
             p += 2;
         } else {
             p += DAY_LEN + julian;
         }
     } while (++col < 7);
     return p;
 }
References DAY_LEN, julian, memset, p, SPACE, and val.
Referenced by cal_main().
cal_main()
int cal_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 106 of file cal.c.
 {
     struct tm zero_tm;
     time_t now;
     unsigned month, year, flags, i, weekstart;
     char *month_names[12];
     /* normal heading: */
     /* "Su Mo Tu We Th Fr Sa" */
     /* -j heading: */
     /* " Su  Mo  Tu  We  Th  Fr  Sa" */
     char day_headings[ENABLE_UNICODE_SUPPORT ? 28 * 6 : 28];
     IF_UNICODE_SUPPORT(char *hp = day_headings;)
     char buf[40];
     init_unicode();
     flags = getopt32(argv, "jmy");
     /* This sets julian = flags & OPT_JULIAN: */
     option_mask32 &= OPT_JULIAN;
     month = 0;
     weekstart = (flags & OPT_MONDAY) ? MONDAY : SUNDAY;
     argv += optind;
     if (!argv[0]) {
         struct tm *ptm;
         time(&now);
         ptm = localtime(&now);
         year = ptm->tm_year + 1900;
         if (!(flags & OPT_YEAR)) { /* no -y */
             month = ptm->tm_mon + 1;
         }
     } else {
         if (argv[1]) {
             if (argv[2]) {
                 bb_show_usage();
             }
             if (!(flags & OPT_YEAR)) { /* no -y */
                 month = xatou_range(*argv, 1, 12);
             }
             argv++;
         }
         year = xatou_range(*argv, 1, 9999);
     }
     blank_string(day_headings, sizeof(day_headings) - 7 + 7*julian);
     i = 0;
     do {
         zero_tm.tm_mon = i;
         /* full month name according to locale */
         strftime(buf, sizeof(buf), "%B", &zero_tm);
         month_names[i] = xstrdup(buf);
         if (i < 7) {
             zero_tm.tm_wday = (i + weekstart) % 7;
             /* abbreviated weekday name according to locale */
             strftime(buf, sizeof(buf), "%a", &zero_tm);
 #if ENABLE_UNICODE_SUPPORT
             if (julian)
                 *hp++ = ' ';
             {
                 char *two_wchars = unicode_conv_to_printable_fixedwidth(/*NULL,*/ buf, 2);
                 strcpy(hp, two_wchars);
                 free(two_wchars);
             }
             hp += strlen(hp);
             *hp++ = ' ';
 #else
             strncpy(day_headings + i * (3+julian) + julian, buf, 2);
 #endif
         }
     } while (++i < 12);
     IF_UNICODE_SUPPORT(hp[-1] = '\0';)
     if (month) {
         unsigned row, len, days[MAXDAYS];
         unsigned *dp = days;
         char lineout[30];
         day_array(month, year, weekstart, dp);
         len = sprintf(lineout, "%s %u", month_names[month - 1], year);
         printf("%*s%s\n%s\n",
                 ((7*julian + WEEK_LEN) - len) / 2, "",
                 lineout, day_headings);
         for (row = 0; row < 6; row++) {
             build_row(lineout, dp)[0] = '\0';
             dp += 7;
             trim_trailing_spaces_and_print(lineout);
         }
     } else {
         unsigned row, which_cal, week_len, days[12][MAXDAYS];
         unsigned *dp;
         char lineout[80];
         sprintf(lineout, "%u", year);
         center(lineout,
                 (WEEK_LEN * 3 + HEAD_SEP * 2)
                 + julian * (J_WEEK_LEN * 2 + HEAD_SEP
                         - (WEEK_LEN * 3 + HEAD_SEP * 2)),
                 0
         );
         puts("\n");     /* two \n's */
         for (i = 0; i < 12; i++) {
             day_array(i + 1, year, weekstart, days[i]);
         }
         blank_string(lineout, sizeof(lineout));
         week_len = WEEK_LEN + julian * (J_WEEK_LEN - WEEK_LEN);
         for (month = 0; month < 12; month += 3-julian) {
             center(month_names[month], week_len, HEAD_SEP);
             if (!julian) {
                 center(month_names[month + 1], week_len, HEAD_SEP);
             }
             center(month_names[month + 2 - julian], week_len, 0);
             printf("\n%s%*s%s", day_headings, HEAD_SEP, "", day_headings);
             if (!julian) {
                 printf("%*s%s", HEAD_SEP, "", day_headings);
             }
             bb_putchar('\n');
             for (row = 0; row < (6*7); row += 7) {
                 for (which_cal = 0; which_cal < 3-julian; which_cal++) {
                     dp = days[month + which_cal] + row;
                     build_row(lineout + which_cal * (week_len + 2), dp);
                 }
                 /* blank_string took care of nul termination. */
                 trim_trailing_spaces_and_print(lineout);
             }
         }
     }
     fflush_stdout_and_exit_SUCCESS();
 }
References argv, bb_putchar(), bb_show_usage(), blank_string(), buf, build_row(), center(), day_array(), fflush_stdout_and_exit_SUCCESS(), flags, free, getopt32(), HEAD_SEP, i, init_unicode, J_WEEK_LEN, julian, len, localtime(), MAXDAYS, MONDAY, OPT_JULIAN, OPT_MONDAY, OPT_YEAR, optind, option_mask32, printf, puts(), sprintf(), strcpy, strftime(), strlen(), strncpy(), SUNDAY, time(), tm::tm_mon, tm::tm_wday, tm::tm_year, trim_trailing_spaces_and_print(), unicode_conv_to_printable_fixedwidth(), WEEK_LEN, and xstrdup().
center()
static void center (char * str, unsigned len, unsigned separate) static
Definition at line 328 of file cal.c.
 {
     unsigned n = strlen(str);
     len -= n;
     printf("%*s%*s", (len/2) + n, str, (len/2) + (len % 2) + separate, "");
 }
References len, n, printf, str, and strlen().
Referenced by cal_main(), and scan_table().
day_array()
static void day_array (unsigned month, unsigned year, unsigned weekstart, unsigned * days) static
Definition at line 246 of file cal.c.
 {
     unsigned long temp;
     unsigned i;
     unsigned day, dw, dm;
     memset(days, SPACE, MAXDAYS * sizeof(int));
     if ((month == 9) && (year == 1752)) {
         /* Assumes the Gregorian reformation eliminates
          * 3 Sep. 1752 through 13 Sep. 1752.
          */
         unsigned j_offset = julian * 244;
         size_t oday = 0;
         do {
             days[oday+2-weekstart] = sep1752[oday] + j_offset;
         } while (++oday < sizeof(sep1752));
         return;
     }
     /* day_in_year
      * return the 1 based day number within the year
      */
     day = 1;
     if ((month > 2) && leap_year(year)) {
         ++day;
     }
     i = month;
     while (i) {
         day += days_in_month[--i];
     }
     /* day_in_week
      * return the 0 based day number for any date from 1 Jan. 1 to
      * 31 Dec. 9999.  Assumes the Gregorian reformation eliminates
      * 3 Sep. 1752 through 13 Sep. 1752.  Returns Thursday for all
      * missing days.
      */
     temp = (long)(year - 1) * 365 + leap_years_since_year_1(year - 1) + day;
     if (temp < FIRST_MISSING_DAY) {
         dw = ((temp - 1 + SATURDAY) % 7);
     } else {
         dw = (((temp - 1 + SATURDAY) - NUMBER_MISSING_DAYS) % 7);
     }
     dw = (dw - weekstart + 7) % 7;
     if (!julian) {
         day = 1;
     }
     dm = days_in_month[month];
     if ((month == 2) && leap_year(year)) {
         ++dm;
     }
     do {
         days[dw++] = day++;
     } while (--dm);
 }
References days_in_month(), FIRST_MISSING_DAY, i, julian, leap_year(), leap_years_since_year_1, MAXDAYS, memset, NUMBER_MISSING_DAYS, SATURDAY, and SPACE.
Referenced by cal_main().
leap_year()
static int leap_year (unsigned yr) static
Definition at line 67 of file cal.c.
 {
     if (yr <= 1752)
         return !(yr % 4);
     return (!(yr % 4) && (yr % 100)) || !(yr % 400);
 }
Referenced by day_array().
trim_trailing_spaces_and_print()
static void trim_trailing_spaces_and_print (char * s) static
Definition at line 310 of file cal.c.
 {
     char *p = s;
     while (*p) {
         ++p;
     }
     while (p != s) {
         --p;
         if (!isspace(*p)) {
             p[1] = '\0';
             break;
         }
     }
     puts(s);
 }
References isspace, p, puts(), and s.
Referenced by cal_main().
Variable Documentation
ALIGN1
const unsigned char sep1752 [] ALIGN1 static
Initial value:
= {
    0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
}
Definition at line 53 of file cal.c.