Fennix Userspace: Userspace/musl/src/ctype/iswctype.c File Reference
iswctype.c File Reference
#include <wctype.h>
#include <string.h>
Macros
#define WCTYPE_ALNUM 1
#define WCTYPE_ALPHA 2
#define WCTYPE_BLANK 3
#define WCTYPE_CNTRL 4
#define WCTYPE_DIGIT 5
#define WCTYPE_GRAPH 6
#define WCTYPE_LOWER 7
#define WCTYPE_PRINT 8
#define WCTYPE_PUNCT 9
#define WCTYPE_SPACE 10
#define WCTYPE_UPPER 11
#define WCTYPE_XDIGIT 12
Functions
int iswctype (wint_t wc, wctype_t type)
wctype_t wctype (const char *s)
int __iswctype_l (wint_t c, wctype_t t, locale_t l)
wctype_t __wctype_l (const char *s, locale_t l)
weak_alias (__iswctype_l, iswctype_l)
weak_alias (__wctype_l, wctype_l)
Macro Definition Documentation
WCTYPE_ALNUM
#define WCTYPE_ALNUM 1
Definition at line 4 of file iswctype.c.
WCTYPE_ALPHA
#define WCTYPE_ALPHA 2
Definition at line 5 of file iswctype.c.
WCTYPE_BLANK
#define WCTYPE_BLANK 3
Definition at line 6 of file iswctype.c.
WCTYPE_CNTRL
#define WCTYPE_CNTRL 4
Definition at line 7 of file iswctype.c.
WCTYPE_DIGIT
#define WCTYPE_DIGIT 5
Definition at line 8 of file iswctype.c.
WCTYPE_GRAPH
#define WCTYPE_GRAPH 6
Definition at line 9 of file iswctype.c.
WCTYPE_LOWER
#define WCTYPE_LOWER 7
Definition at line 10 of file iswctype.c.
WCTYPE_PRINT
#define WCTYPE_PRINT 8
Definition at line 11 of file iswctype.c.
WCTYPE_PUNCT
#define WCTYPE_PUNCT 9
Definition at line 12 of file iswctype.c.
WCTYPE_SPACE
#define WCTYPE_SPACE 10
Definition at line 13 of file iswctype.c.
WCTYPE_UPPER
#define WCTYPE_UPPER 11
Definition at line 14 of file iswctype.c.
WCTYPE_XDIGIT
#define WCTYPE_XDIGIT 12
Definition at line 15 of file iswctype.c.
Function Documentation
__iswctype_l()
int __iswctype_l (wint_t c, wctype_t t, locale_t l)
Definition at line 64 of file iswctype.c.
 {
     return iswctype(c, t);
 }
References c, iswctype(), and t.
__wctype_l()
wctype_t __wctype_l (const char * s, locale_t l)
Definition at line 69 of file iswctype.c.
 {
     return wctype(s);
 }
References s, and wctype().
iswctype()
int iswctype (wint_t wc, wctype_t type)
Definition at line 17 of file iswctype.c.
 {
     switch (type) {
     case WCTYPE_ALNUM:
         return iswalnum(wc);
     case WCTYPE_ALPHA:
         return iswalpha(wc);
     case WCTYPE_BLANK:
         return iswblank(wc);
     case WCTYPE_CNTRL:
         return iswcntrl(wc);
     case WCTYPE_DIGIT:
         return iswdigit(wc);
     case WCTYPE_GRAPH:
         return iswgraph(wc);
     case WCTYPE_LOWER:
         return iswlower(wc);
     case WCTYPE_PRINT:
         return iswprint(wc);
     case WCTYPE_PUNCT:
         return iswpunct(wc);
     case WCTYPE_SPACE:
         return iswspace(wc);
     case WCTYPE_UPPER:
         return iswupper(wc);
     case WCTYPE_XDIGIT:
         return iswxdigit(wc);
     }
     return 0;
 }
References iswalnum, iswalpha(), iswblank(), iswcntrl(), iswdigit, iswgraph(), iswlower(), iswprint(), iswpunct(), iswspace(), iswupper(), iswxdigit(), type, WCTYPE_ALNUM, WCTYPE_ALPHA, WCTYPE_BLANK, WCTYPE_CNTRL, WCTYPE_DIGIT, WCTYPE_GRAPH, WCTYPE_LOWER, WCTYPE_PRINT, WCTYPE_PUNCT, WCTYPE_SPACE, WCTYPE_UPPER, and WCTYPE_XDIGIT.
Referenced by __iswctype_l(), and match_bracket().
wctype()
wctype_t wctype (const char * s)
Definition at line 48 of file iswctype.c.
 {
     int i;
     const char *p;
     /* order must match! */
     static const char names[] =
         "alnum\0" "alpha\0" "blank\0"
         "cntrl\0" "digit\0" "graph\0"
         "lower\0" "print\0" "punct\0"
         "space\0" "upper\0" "xdigit";
     for (i=1, p=names; *p; i++, p+=6)
         if (*s == *p && !strcmp(s, p))
             return i;
     return 0;
 }
References i, names, p, s, and strcmp.
Referenced by __wctype_l(), and match_bracket().
weak_alias() [1/2]
weak_alias (__iswctype_l , iswctype_l)
weak_alias() [2/2]
weak_alias (__wctype_l , wctype_l)