Fennix Userspace: Userspace/mlibc/tests/linux/malloc-usable-size.c File Reference
malloc-usable-size.c File Reference
#include <assert.h>
#include <malloc.h>
#include <stdio.h>
#include <stdlib.h>
Functions
int main ()
Function Documentation
main()
int main (void)
Definition at line 6 of file malloc-usable-size.c.
            {
     void *p1 = malloc(1023);
     fprintf(stderr, "size: %zu\n", malloc_usable_size(p1));
     assert(malloc_usable_size(p1) >= 1023);
     free(p1);
     return 0;
 }
References assert, fprintf(), free(), malloc(), malloc_usable_size(), and stderr.