Fennix: Userspace/apps/base/busybox/miscutils/setfattr.c File Reference
setfattr.c File Reference
#include <sys/xattr.h>
#include "libbb.h"
Functions
int setfattr_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
setfattr_main()
int setfattr_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 31 of file setfattr.c.
 {
     const char *name;
     const char *value = "";
     int status;
     int opt;
     enum {
         OPT_h = (1 << 0),
         OPT_x = (1 << 1),
     };
     opt = getopt32(argv, "^"
         "hx:n:v:"
         /* Min one arg, either -x or -n is a must, -x does not allow -v */
         "\0" "-1:x:n:n--x:x--nv:v--x"
         , &name, &name, &value
     );
     argv += optind;
     status = EXIT_SUCCESS;
     do {
         int r;
         if (opt & OPT_x)
             r = ((opt & OPT_h) ? lremovexattr : removexattr)(*argv, name);
         else {
             r = ((opt & OPT_h) ? lsetxattr : setxattr)(
                     *argv, name,
                     value, strlen(value), /*flags:*/ 0
             );
         }
         if (r) {
             bb_simple_perror_msg(*argv);
             status = EXIT_FAILURE;
         }
     } while (*++argv);
     return status;
 }
References argv, bb_simple_perror_msg(), EXIT_FAILURE, EXIT_SUCCESS, getopt32(), lremovexattr(), lsetxattr(), opt, OPT_h, OPT_x, optind, removexattr(), setxattr(), status, strlen(), and value.