Fennix Userspace: Userspace/apps/base/busybox/libbb/pw_encrypt.c File Reference
pw_encrypt.c File Reference
#include <crypt.h>
#include "libbb.h"
Functions
static int i64c (int i)
int FAST_FUNC crypt_make_salt (char *p, int cnt)
char *FAST_FUNC crypt_make_pw_salt (char salt[MAX_PW_SALT_LEN], const char *algo)
char *FAST_FUNC pw_encrypt (const char *clear, const char *salt, int cleanup)
Function Documentation
crypt_make_pw_salt()
char* FAST_FUNC crypt_make_pw_salt (char salt[MAX_PW_SALT_LEN], const char * algo)
Definition at line 55 of file pw_encrypt.c.
 {
     int len = 2/2;
     char *salt_ptr = salt;
     /* Standard chpasswd uses uppercase algos ("MD5", not "md5").
      * Need to be case-insensitive in the code below.
      */
     if ((algo[0]|0x20) != 'd') { /* not des */
         len = 8/2; /* so far assuming md5 */
         *salt_ptr++ = '$';
         *salt_ptr++ = '1';
         *salt_ptr++ = '$';
 #if !ENABLE_USE_BB_CRYPT || ENABLE_USE_BB_CRYPT_SHA
         if ((algo[0]|0x20) == 's') { /* sha */
             salt[1] = '5' + (strcasecmp(algo, "sha512") == 0);
             len = 16/2;
         }
 #endif
     }
     crypt_make_salt(salt_ptr, len);
     return salt_ptr;
 }
References crypt_make_salt(), and strcasecmp.
Referenced by chpasswd_main(), cryptpw_main(), and new_password().
crypt_make_salt()
int FAST_FUNC crypt_make_salt (char * p, int cnt)
Definition at line 34 of file pw_encrypt.c.
 {
     /* was: x += ... */
     unsigned x = getpid() + monotonic_us();
     do {
         /* x = (x*1664525 + 1013904223) % 2^32 generator is lame
          * (low-order bit is not "random", etc...),
          * but for our purposes it is good enough */
         x = x*1664525 + 1013904223;
         /* BTW, Park and Miller's "minimal standard generator" is
          * x = x*16807 % ((2^31)-1)
          * It has no problem with visibly alternating lowest bit
          * but is also weak in cryptographic sense + needs div,
          * which needs more code (and slower) on many CPUs */
         *p++ = i64c(x >> 16);
         *p++ = i64c(x >> 22);
     } while (--cnt);
     *p = '\0';
     return x;
 }
References cnt, getpid(), i64c(), monotonic_us(), p, and x.
Referenced by crypt_make_pw_salt(), and httpd_main().
i64c()
static int i64c (int i) static
Definition at line 20 of file pw_encrypt.c.
 {
     i &= 0x3f;
     if (i == 0)
         return '.';
     if (i == 1)
         return '/';
     if (i < 12)
         return ('0' - 2 + i);
     if (i < 38)
         return ('A' - 12 + i);
     return ('a' - 38 + i);
 }
References i.
Referenced by crypt_make_salt(), and to64_msb_first().
pw_encrypt()
char* FAST_FUNC pw_encrypt (const char * clear, const char * salt, int cleanup)
Definition at line 154 of file pw_encrypt.c.
 {
     char *encrypted;
     encrypted = crypt(clear, salt);
     /*
      * glibc used to return "" on malformed salts (for example, ""),
      * but since 2.17 it returns NULL.
      */
     if (!encrypted || !encrypted[0])
         bb_simple_error_msg_and_die("bad salt");
     return xstrdup(encrypted);
 }
References bb_simple_error_msg_and_die(), crypt(), and xstrdup().