Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/p_doors.c File Reference
p_doors.c File Reference
#include "z_zone.h"
#include "doomdef.h"
#include "deh_main.h"
#include "p_local.h"
#include "s_sound.h"
#include "doomstat.h"
#include "r_state.h"
#include "dstrings.h"
#include "sounds.h"
Functions
void T_VerticalDoor (vldoor_t *door)
int EV_DoLockedDoor (line_t *line, vldoor_e type, mobj_t *thing)
int EV_DoDoor (line_t *line, vldoor_e type)
void EV_VerticalDoor (line_t *line, mobj_t *thing)
void P_SpawnDoorCloseIn30 (sector_t *sec)
void P_SpawnDoorRaiseIn5Mins (sector_t *sec, int secnum)
Function Documentation
EV_DoDoor()
int EV_DoDoor (line_t * line, vldoor_e type)
Definition at line 252 of file p_doors.c.
 {
     int     secnum,rtn;
     sector_t*   sec;
     vldoor_t*   door;
     secnum = -1;
     rtn = 0;
     while ((secnum = P_FindSectorFromLineTag(line,secnum)) >= 0)
     {
     sec = &sectors[secnum];
     if (sec->specialdata)
         continue;
     // new door thinker
     rtn = 1;
     door = Z_Malloc (sizeof(*door), PU_LEVSPEC, 0);
     P_AddThinker (&door->thinker);
     sec->specialdata = door;
     door->thinker.function.acp1 = (actionf_p1) T_VerticalDoor;
     door->sector = sec;
     door->type = type;
     door->topwait = VDOORWAIT;
     door->speed = VDOORSPEED;
     switch(type)
     {
       case vld_blazeClose:
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         door->direction = -1;
         door->speed = VDOORSPEED * 4;
         S_StartSound(&door->sector->soundorg, sfx_bdcls);
         break;
       case vld_close:
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         door->direction = -1;
         S_StartSound(&door->sector->soundorg, sfx_dorcls);
         break;
       case vld_close30ThenOpen:
         door->topheight = sec->ceilingheight;
         door->direction = -1;
         S_StartSound(&door->sector->soundorg, sfx_dorcls);
         break;
       case vld_blazeRaise:
       case vld_blazeOpen:
         door->direction = 1;
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         door->speed = VDOORSPEED * 4;
         if (door->topheight != sec->ceilingheight)
         S_StartSound(&door->sector->soundorg, sfx_bdopn);
         break;
       case vld_normal:
       case vld_open:
         door->direction = 1;
         door->topheight = P_FindLowestCeilingSurrounding(sec);
         door->topheight -= 4*FRACUNIT;
         if (door->topheight != sec->ceilingheight)
         S_StartSound(&door->sector->soundorg, sfx_doropn);
         break;
       default:
         break;
     }
     }
     return rtn;
 }
References actionf_t::acp1, sector_t::ceilingheight, vldoor_t::direction, FRACUNIT, thinker_s::function, P_AddThinker(), P_FindLowestCeilingSurrounding(), P_FindSectorFromLineTag(), PU_LEVSPEC, S_StartSound(), vldoor_t::sector, sectors, sfx_bdcls, sfx_bdopn, sfx_dorcls, sfx_doropn, sector_t::soundorg, sector_t::specialdata, vldoor_t::speed, T_VerticalDoor(), vldoor_t::thinker, vldoor_t::topheight, vldoor_t::topwait, type, vldoor_t::type, VDOORSPEED, VDOORWAIT, vld_blazeClose, vld_blazeOpen, vld_blazeRaise, vld_close, vld_close30ThenOpen, vld_normal, vld_open, and Z_Malloc().
Referenced by A_BossDeath(), A_KeenDie(), EV_DoLockedDoor(), P_CrossSpecialLine(), P_ShootSpecialLine(), and P_UseSpecialLine().
EV_DoLockedDoor()
int EV_DoLockedDoor (line_t * line, vldoor_e type, mobj_t * thing)
Definition at line 195 of file p_doors.c.
 {
     player_t*   p;
     p = thing->player;
     if (!p)
     return 0;
     switch(line->special)
     {
       case 99:  // Blue Lock
       case 133:
     if ( !p )
         return 0;
     if (!p->cards[it_bluecard] && !p->cards[it_blueskull])
     {
         p->message = DEH_String(PD_BLUEO);
         S_StartSound(NULL,sfx_oof);
         return 0;
     }
     break;
       case 134: // Red Lock
       case 135:
     if ( !p )
         return 0;
     if (!p->cards[it_redcard] && !p->cards[it_redskull])
     {
         p->message = DEH_String(PD_REDO);
         S_StartSound(NULL,sfx_oof);
         return 0;
     }
     break;
       case 136: // Yellow Lock
       case 137:
     if ( !p )
         return 0;
     if (!p->cards[it_yellowcard] &&
         !p->cards[it_yellowskull])
     {
         p->message = DEH_String(PD_YELLOWO);
         S_StartSound(NULL,sfx_oof);
         return 0;
     }
     break;
     }
     return EV_DoDoor(line,type);
 }
References DEH_String, EV_DoDoor(), it_bluecard, it_blueskull, it_redcard, it_redskull, it_yellowcard, it_yellowskull, NULL, p, PD_BLUEO, PD_REDO, PD_YELLOWO, mobj_s::player, S_StartSound(), sfx_oof, line_s::special, and type.
Referenced by P_UseSpecialLine().
EV_VerticalDoor()
void EV_VerticalDoor (line_t * line, mobj_t * thing)
Definition at line 337 of file p_doors.c.
 {
     player_t*   player;
     sector_t*   sec;
     vldoor_t*   door;
     int     side;
     side = 0;   // only front sides can be used
     //  Check for locks
     player = thing->player;
     switch(line->special)
     {
       case 26: // Blue Lock
       case 32:
     if ( !player )
         return;
     if (!player->cards[it_bluecard] && !player->cards[it_blueskull])
     {
         player->message = DEH_String(PD_BLUEK);
         S_StartSound(NULL,sfx_oof);
         return;
     }
     break;
       case 27: // Yellow Lock
       case 34:
     if ( !player )
         return;
     if (!player->cards[it_yellowcard] &&
         !player->cards[it_yellowskull])
     {
         player->message = DEH_String(PD_YELLOWK);
         S_StartSound(NULL,sfx_oof);
         return;
     }
     break;
       case 28: // Red Lock
       case 33:
     if ( !player )
         return;
     if (!player->cards[it_redcard] && !player->cards[it_redskull])
     {
         player->message = DEH_String(PD_REDK);
         S_StartSound(NULL,sfx_oof);
         return;
     }
     break;
     }
     // if the sector has an active thinker, use it
     sec = sides[ line->sidenum[side^1]] .sector;
     if (sec->specialdata)
     {
     door = sec->specialdata;
     switch(line->special)
     {
       case  1: // ONLY FOR "RAISE" DOORS, NOT "OPEN"s
       case  26:
       case  27:
       case  28:
       case  117:
         if (door->direction == -1)
         door->direction = 1;    // go back up
         else
         {
         if (!thing->player)
             return;     // JDC: bad guys never close doors
                 // When is a door not a door?
                 // In Vanilla, door->direction is set, even though
                 // "specialdata" might not actually point at a door.
                 if (door->thinker.function.acp1 == (actionf_p1) T_VerticalDoor)
                 {
                     door->direction = -1;   // start going down immediately
                 }
                 else if (door->thinker.function.acp1 == (actionf_p1) T_PlatRaise)
                 {
                     // Erm, this is a plat, not a door.
                     // This notably causes a problem in ep1-0500.lmp where
                     // a plat and a door are cross-referenced; the door
                     // doesn't open on 64-bit.
                     // The direction field in vldoor_t corresponds to the wait
                     // field in plat_t.  Let's set that to -1 instead.
                     plat_t *plat;
                     plat = (plat_t *) door;
                     plat->wait = -1;
                 }
                 else
                 {
                     // This isn't a door OR a plat.  Now we're in trouble.
                     fprintf(stderr, "EV_VerticalDoor: Tried to close "
                                     "something that wasn't a door.\n");
                     // Try closing it anyway. At least it will work on 32-bit
                     // machines.
                     door->direction = -1;
                 }
         }
         return;
     }
     }
     // for proper sound
     switch(line->special)
     {
       case 117: // BLAZING DOOR RAISE
       case 118: // BLAZING DOOR OPEN
     S_StartSound(&sec->soundorg,sfx_bdopn);
     break;
       case 1:   // NORMAL DOOR SOUND
       case 31:
     S_StartSound(&sec->soundorg,sfx_doropn);
     break;
       default:  // LOCKED DOOR SOUND
     S_StartSound(&sec->soundorg,sfx_doropn);
     break;
     }
     // new door thinker
     door = Z_Malloc (sizeof(*door), PU_LEVSPEC, 0);
     P_AddThinker (&door->thinker);
     sec->specialdata = door;
     door->thinker.function.acp1 = (actionf_p1) T_VerticalDoor;
     door->sector = sec;
     door->direction = 1;
     door->speed = VDOORSPEED;
     door->topwait = VDOORWAIT;
     switch(line->special)
     {
       case 1:
       case 26:
       case 27:
       case 28:
     door->type = vld_normal;
     break;
       case 31:
       case 32:
       case 33:
       case 34:
     door->type = vld_open;
     line->special = 0;
     break;
       case 117: // blazing door raise
     door->type = vld_blazeRaise;
     door->speed = VDOORSPEED*4;
     break;
       case 118: // blazing door open
     door->type = vld_blazeOpen;
     line->special = 0;
     door->speed = VDOORSPEED*4;
     break;
     }
     // find the top and bottom of the movement range
     door->topheight = P_FindLowestCeilingSurrounding(sec);
     door->topheight -= 4*FRACUNIT;
 }
References actionf_t::acp1, player_s::cards, DEH_String, vldoor_t::direction, fprintf(), FRACUNIT, thinker_s::function, it_bluecard, it_blueskull, it_redcard, it_redskull, it_yellowcard, it_yellowskull, player_s::message, NULL, P_AddThinker(), P_FindLowestCeilingSurrounding(), PD_BLUEK, PD_REDK, PD_YELLOWK, mobj_s::player, PU_LEVSPEC, S_StartSound(), vldoor_t::sector, side_t::sector, sfx_bdopn, sfx_doropn, sfx_oof, line_s::sidenum, sides, sector_t::soundorg, line_s::special, sector_t::specialdata, vldoor_t::speed, stderr, T_PlatRaise(), T_VerticalDoor(), vldoor_t::thinker, vldoor_t::topheight, vldoor_t::topwait, vldoor_t::type, VDOORSPEED, VDOORWAIT, vld_blazeOpen, vld_blazeRaise, vld_normal, vld_open, plat_t::wait, and Z_Malloc().
Referenced by P_UseSpecialLine().
P_SpawnDoorCloseIn30()
void P_SpawnDoorCloseIn30 (sector_t * sec)
Definition at line 519 of file p_doors.c.
 {
     vldoor_t*   door;
     door = Z_Malloc ( sizeof(*door), PU_LEVSPEC, 0);
     P_AddThinker (&door->thinker);
     sec->specialdata = door;
     sec->special = 0;
     door->thinker.function.acp1 = (actionf_p1)T_VerticalDoor;
     door->sector = sec;
     door->direction = 0;
     door->type = vld_normal;
     door->speed = VDOORSPEED;
     door->topcountdown = 30 * TICRATE;
 }
References actionf_t::acp1, vldoor_t::direction, thinker_s::function, P_AddThinker(), PU_LEVSPEC, vldoor_t::sector, sector_t::special, sector_t::specialdata, vldoor_t::speed, T_VerticalDoor(), vldoor_t::thinker, TICRATE, vldoor_t::topcountdown, vldoor_t::type, VDOORSPEED, vld_normal, and Z_Malloc().
Referenced by P_SpawnSpecials().
P_SpawnDoorRaiseIn5Mins()
void P_SpawnDoorRaiseIn5Mins (sector_t * sec, int secnum)
Definition at line 542 of file p_doors.c.
 {
     vldoor_t*   door;
     door = Z_Malloc ( sizeof(*door), PU_LEVSPEC, 0);
     P_AddThinker (&door->thinker);
     sec->specialdata = door;
     sec->special = 0;
     door->thinker.function.acp1 = (actionf_p1)T_VerticalDoor;
     door->sector = sec;
     door->direction = 2;
     door->type = vld_raiseIn5Mins;
     door->speed = VDOORSPEED;
     door->topheight = P_FindLowestCeilingSurrounding(sec);
     door->topheight -= 4*FRACUNIT;
     door->topwait = VDOORWAIT;
     door->topcountdown = 5 * 60 * TICRATE;
 }
References actionf_t::acp1, vldoor_t::direction, FRACUNIT, thinker_s::function, P_AddThinker(), P_FindLowestCeilingSurrounding(), PU_LEVSPEC, vldoor_t::sector, sector_t::special, sector_t::specialdata, vldoor_t::speed, T_VerticalDoor(), vldoor_t::thinker, TICRATE, vldoor_t::topcountdown, vldoor_t::topheight, vldoor_t::topwait, vldoor_t::type, VDOORSPEED, VDOORWAIT, vld_raiseIn5Mins, and Z_Malloc().
Referenced by P_SpawnSpecials().
T_VerticalDoor()
void T_VerticalDoor (vldoor_t * door)
Definition at line 57 of file p_doors.c.
 {
     result_e    res;
     switch(door->direction)
     {
       case 0:
     // WAITING
     if (!--door->topcountdown)
     {
         switch(door->type)
         {
           case vld_blazeRaise:
         door->direction = -1; // time to go back down
         S_StartSound(&door->sector->soundorg, sfx_bdcls);
         break;
           case vld_normal:
         door->direction = -1; // time to go back down
         S_StartSound(&door->sector->soundorg, sfx_dorcls);
         break;
           case vld_close30ThenOpen:
         door->direction = 1;
         S_StartSound(&door->sector->soundorg, sfx_doropn);
         break;
           default:
         break;
         }
     }
     break;
       case 2:
     //  INITIAL WAIT
     if (!--door->topcountdown)
     {
         switch(door->type)
         {
           case vld_raiseIn5Mins:
         door->direction = 1;
         door->type = vld_normal;
         S_StartSound(&door->sector->soundorg, sfx_doropn);
         break;
           default:
         break;
         }
     }
     break;
       case -1:
     // DOWN
     res = T_MovePlane(door->sector,
               door->speed,
               door->sector->floorheight,
               false,1,door->direction);
     if (res == pastdest)
     {
         switch(door->type)
         {
           case vld_blazeRaise:
           case vld_blazeClose:
         door->sector->specialdata = NULL;
         P_RemoveThinker (&door->thinker);  // unlink and free
         S_StartSound(&door->sector->soundorg, sfx_bdcls);
         break;
           case vld_normal:
           case vld_close:
         door->sector->specialdata = NULL;
         P_RemoveThinker (&door->thinker);  // unlink and free
         break;
           case vld_close30ThenOpen:
         door->direction = 0;
         door->topcountdown = TICRATE*30;
         break;
           default:
         break;
         }
     }
     else if (res == crushed)
     {
         switch(door->type)
         {
           case vld_blazeClose:
           case vld_close:       // DO NOT GO BACK UP!
         break;
           default:
         door->direction = 1;
         S_StartSound(&door->sector->soundorg, sfx_doropn);
         break;
         }
     }
     break;
       case 1:
     // UP
     res = T_MovePlane(door->sector,
               door->speed,
               door->topheight,
               false,1,door->direction);
     if (res == pastdest)
     {
         switch(door->type)
         {
           case vld_blazeRaise:
           case vld_normal:
         door->direction = 0; // wait at top
         door->topcountdown = door->topwait;
         break;
           case vld_close30ThenOpen:
           case vld_blazeOpen:
           case vld_open:
         door->sector->specialdata = NULL;
         P_RemoveThinker (&door->thinker);  // unlink and free
         break;
           default:
         break;
         }
     }
     break;
     }
 }
References crushed, vldoor_t::direction, sector_t::floorheight, NULL, P_RemoveThinker(), pastdest, S_StartSound(), vldoor_t::sector, sfx_bdcls, sfx_dorcls, sfx_doropn, sector_t::soundorg, sector_t::specialdata, vldoor_t::speed, T_MovePlane(), vldoor_t::thinker, TICRATE, vldoor_t::topcountdown, vldoor_t::topheight, vldoor_t::topwait, vldoor_t::type, vld_blazeClose, vld_blazeOpen, vld_blazeRaise, vld_close, vld_close30ThenOpen, vld_normal, vld_open, and vld_raiseIn5Mins.
Referenced by EV_DoDoor(), EV_VerticalDoor(), P_ArchiveSpecials(), P_SpawnDoorCloseIn30(), P_SpawnDoorRaiseIn5Mins(), and P_UnArchiveSpecials().