Fennix: Userspace/apps/base/busybox/util-linux/fdisk.c File Reference
fdisk.c File Reference
#include <assert.h>
#include <sys/mount.h>
#include "libbb.h"
#include "unicode.h"
#include "fdisk_aix.c"
#include "fdisk_osf.c"
#include "fdisk_gpt.c"
#include "fdisk_sgi.c"
#include "fdisk_sun.c"
Data Structures
struct hd_geometry
struct partition
struct pte
struct globals
struct sun_partition
struct sun_partition::sun_info
struct sun_partition::sun_partinfo
Macros
#define _LARGEFILE64_SOURCE
#define BLKSSZGET _IO(0x12, 104)
#define BLKGETSIZE64 _IOR(0x12,114,size_t)
#define inline_if_little_endian /* nothing */
#define ENABLE_FEATURE_FDISK_BLKSIZE 0
#define IF_FEATURE_FDISK_BLKSIZE(a)
#define DEFAULT_SECTOR_SIZE 512
#define DEFAULT_SECTOR_SIZE_STR "512"
#define MAX_SECTOR_SIZE 2048
#define SECTOR_SIZE 512 /* still used in osf/sgi/sun code */
#define MAXIMUM_PARTS 60
#define ACTIVE_FLAG 0x80
#define EXTENDED 0x05
#define WIN98_EXTENDED 0x0f
#define LINUX_PARTITION 0x81
#define LINUX_SWAP 0x82
#define LINUX_NATIVE 0x83
#define LINUX_EXTENDED 0x85
#define LINUX_LVM 0x8e
#define LINUX_RAID 0xfd
#define HDIO_GETGEO 0x0301 /* get device geometry */
#define unable_to_open "can't open '%s'"
#define unable_to_read "can't read '%s'"
#define unable_to_seek "can't seek '%s'"
#define LABEL_IS_DOS (LABEL_DOS == current_label_type)
#define LABEL_IS_SUN 0
#define STATIC_SUN extern
#define LABEL_IS_SGI 0
#define STATIC_SGI extern
#define LABEL_IS_AIX 0
#define STATIC_AIX extern
#define LABEL_IS_OSF 0
#define STATIC_OSF extern
#define LABEL_IS_GPT 0
#define STATIC_GPT extern
#define G (*ptr_to_globals)
#define line_ptr (G.line_ptr)
#define disk_device (G.disk_device)
#define g_partitions (G.g_partitions)
#define units_per_sector (G.units_per_sector)
#define sector_size (G.sector_size)
#define user_set_sector_size (G.user_set_sector_size)
#define sector_offset (G.sector_offset)
#define g_heads (G.g_heads)
#define g_sectors (G.g_sectors)
#define g_cylinders (G.g_cylinders)
#define current_label_type (G.current_label_type)
#define display_in_cyl_units (G.display_in_cyl_units)
#define possibly_osf_label (G.possibly_osf_label)
#define listing (G.listing)
#define dos_compatible_flag (G.dos_compatible_flag)
#define nowarn (G.nowarn)
#define ext_index (G.ext_index)
#define user_cylinders (G.user_cylinders)
#define user_heads (G.user_heads)
#define user_sectors (G.user_sectors)
#define pt_heads (G.pt_heads)
#define pt_sectors (G.pt_sectors)
#define kern_heads (G.kern_heads)
#define kern_sectors (G.kern_sectors)
#define extended_offset (G.extended_offset)
#define total_number_of_sectors (G.total_number_of_sectors)
#define listingbuf (G.listingbuf)
#define line_buffer (G.line_buffer)
#define MBRbuffer (G.MBRbuffer)
#define ptes (G.ptes)
#define INIT_G()
#define IS_EXTENDED(i) ((i) == EXTENDED || (i) == WIN98_EXTENDED || (i) == LINUX_EXTENDED)
#define cround(n) (display_in_cyl_units ? ((n)/units_per_sector)+1 : (n))
#define scround(x) (((x)+units_per_sector-1)/units_per_sector)
#define pt_offset(b, n) ((struct partition *)((b) + 0x1be + (n) * sizeof(struct partition)))
#define sector(s) ((s) & 0x3f)
#define cylinder(s, c) ((c) | (((s) & 0xc0) << 2))
#define sunlabel ((sun_partition *)MBRbuffer)
#define get_sys_types() i386_sys_types
#define get_boot(what) get_boot()
#define SFMT SECT_FMT
Typedefs
typedef unsigned long long ullong
typedef uint32_t sector_t
typedef struct sun_partition sun_partition
Enumerations
enum {
OPT_b = 1 << 0 , OPT_C = 1 << 1 , OPT_H = 1 << 2 , OPT_l = 1 << 3 ,
OPT_S = 1 << 4 , OPT_u = 1 << 5 , OPT_s = (1 << 6) * ENABLE_FEATURE_FDISK_BLKSIZE
}
enum label_type {
LABEL_DOS , LABEL_SUN , LABEL_SGI , LABEL_AIX ,
LABEL_OSF , LABEL_GPT
}
enum action { OPEN_MAIN , TRY_ONLY , CREATE_EMPTY_DOS , CREATE_EMPTY_SUN }
enum { dev_fd = 3 }
Functions
static void update_units (void)
static const char * partition_type (unsigned char type)
static void get_geometry (void)
static void read_pte (struct pte *pe, sector_t offset)
static int get_boot (void)
static sector_t get_start_sect (const struct partition *p)
static sector_t get_nr_sects (const struct partition *p)
static sector_t bb_BLKGETSIZE_sectors (int fd)
static void close_dev_fd (void)
static const char * partname (const char *dev, int pno, int lth)
static ALWAYS_INLINE const char * str_units (void)
static int valid_part_table_flag (const char *mbuffer)
static void fdisk_fatal (const char *why)
static void seek_sector (sector_t secno)
STATIC_OSF void bsd_select (void)
STATIC_OSF void xbsd_print_disklabel (int)
STATIC_GPT void gpt_list_table (int xtra)
STATIC_SGI unsigned sgi_get_num_sectors (int i)
STATIC_SGI int sgi_get_sysid (int i)
STATIC_SGI void sgi_delete_partition (int i)
STATIC_SGI void sgi_change_sysid (int i, int sys)
STATIC_SGI void sgi_list_table (int xtra)
STATIC_SGI int verify_sgi (int verbose)
STATIC_SGI void sgi_add_partition (int n, int sys)
STATIC_SGI void sgi_set_swappartition (int i)
STATIC_SGI const char * sgi_get_bootfile (void)
STATIC_SGI void sgi_set_bootfile (const char *aFile)
STATIC_SGI void create_sgiinfo (void)
STATIC_SGI void sgi_write_table (void)
STATIC_SGI void sgi_set_bootpartition (int i)
STATIC_SUN void sun_delete_partition (int i)
STATIC_SUN void sun_change_sysid (int i, int sys)
STATIC_SUN void sun_list_table (int xtra)
STATIC_SUN void add_sun_partition (int n, int sys)
STATIC_SUN void toggle_sunflags (int i, unsigned char mask)
STATIC_SUN void verify_sun (void)
STATIC_SUN void sun_write_table (void)
static inline_if_little_endian unsigned read4_little_endian (const unsigned char *cp)
static sector_t get_partition_start_from_dev_start (const struct pte *pe)
static int is_cleared_partition (const struct partition *p)
static void clear_partition (struct partition *p)
static int warn_geometry (void)
static void read_extended (int ext)
static void get_sectorsize (void)
static void get_kernel_geometry (void)
static void get_partition_table_geometry (void)
static void linear2chs (unsigned ls, unsigned *c, unsigned *h, unsigned *s)
static void check_consistency (const struct partition *p, int partition)
static void list_disk_geometry (void)
static int wrong_p_order (int *prev)
static const char * chs_string11 (unsigned cyl, unsigned head, unsigned sect)
static void list_table (int xtra)
static int is_ide_cdrom_or_tape (const char *device)
static void open_list_and_close (const char *device, int user_specified)
static int is_whole_disk (const char *disk)
static void list_devs_in_proc_partititons (void)
int fdisk_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct partition PACKED
static const char *const i386_sys_types[] ALIGN_PTR
struct sun_partition FIX_ALIASING
STATIC_SGI const char *const sgi_sys_types []
STATIC_SUN const char *const sun_sys_types []
Data Structure Documentation
hd_geometry
struct hd_geometry
Definition at line 179 of file fdisk.c.
Data Fields
unsigned short cylinders
unsigned char heads
unsigned char sectors
unsigned long start
partition
struct partition
Definition at line 203 of file fdisk.c.
Data Fields
unsigned char boot_ind
unsigned char cyl
unsigned char end_cyl
unsigned char end_head
unsigned char end_sector
unsigned char head
unsigned char sector
unsigned char size4[4]
unsigned char start4[4]
unsigned char sys_ind
pte
struct pte
Definition at line 224 of file fdisk.c.
Data Fields
struct partition * ext_pointer
sector_t offset_from_dev_start
struct partition * part_table
char * sectorbuffer
sun_partition
struct sun_partition
Definition at line 726 of file fdisk.c.
Data Fields
unsigned short csum
unsigned short ilfact
unsigned char info[128]
struct sun_info infos[8]
unsigned short magic
unsigned short nacyl
unsigned short ncyl
unsigned short nsect
unsigned short ntrks
struct sun_partinfo partitions[8]
unsigned short pcylcount
unsigned short rspeed
unsigned char spare0[14]
unsigned char spare1[246]
unsigned char spare2[4]
unsigned char spare3[4]
unsigned short sparecyl
sun_partition::sun_info
struct sun_partition::sun_info
Definition at line 729 of file fdisk.c.
Data Fields
unsigned char flags
unsigned char id
unsigned char spare1
unsigned char spare2
sun_partition::sun_partinfo
struct sun_partition::sun_partinfo
Definition at line 746 of file fdisk.c.
Data Fields
uint32_t num_sectors
uint32_t start_cylinder
Macro Definition Documentation
_LARGEFILE64_SOURCE
#define _LARGEFILE64_SOURCE
Definition at line 111 of file fdisk.c.
ACTIVE_FLAG
#define ACTIVE_FLAG 0x80
Definition at line 143 of file fdisk.c.
BLKGETSIZE64
#define BLKGETSIZE64 _IOR(0x12,114,size_t)
Definition at line 119 of file fdisk.c.
BLKSSZGET
#define BLKSSZGET _IO(0x12, 104)
Definition at line 116 of file fdisk.c.
cround
#define cround (n) (display_in_cyl_units ? ((n)/units_per_sector)+1 : (n))
Definition at line 538 of file fdisk.c.
current_label_type
#define current_label_type (G.current_label_type)
Definition at line 464 of file fdisk.c.
cylinder
#define cylinder (s, c) ((c) | (((s) & 0xc0) << 2))
Definition at line 547 of file fdisk.c.
DEFAULT_SECTOR_SIZE
#define DEFAULT_SECTOR_SIZE 512
Definition at line 137 of file fdisk.c.
DEFAULT_SECTOR_SIZE_STR
#define DEFAULT_SECTOR_SIZE_STR "512"
Definition at line 138 of file fdisk.c.
disk_device
#define disk_device (G.disk_device)
Definition at line 455 of file fdisk.c.
display_in_cyl_units
#define display_in_cyl_units (G.display_in_cyl_units)
Definition at line 465 of file fdisk.c.
dos_compatible_flag
#define dos_compatible_flag (G.dos_compatible_flag)
Definition at line 468 of file fdisk.c.
ENABLE_FEATURE_FDISK_BLKSIZE
#define ENABLE_FEATURE_FDISK_BLKSIZE 0
Definition at line 133 of file fdisk.c.
ext_index
#define ext_index (G.ext_index)
Definition at line 470 of file fdisk.c.
EXTENDED
#define EXTENDED 0x05
Definition at line 145 of file fdisk.c.
extended_offset
#define extended_offset (G.extended_offset)
Definition at line 478 of file fdisk.c.
G
#define G (*ptr_to_globals)
Definition at line 453 of file fdisk.c.
g_cylinders
#define g_cylinders (G.g_cylinders)
Definition at line 463 of file fdisk.c.
g_heads
#define g_heads (G.g_heads)
Definition at line 461 of file fdisk.c.
g_partitions
#define g_partitions (G.g_partitions)
Definition at line 456 of file fdisk.c.
g_sectors
#define g_sectors (G.g_sectors)
Definition at line 462 of file fdisk.c.
get_boot
#define get_boot (what) get_boot()
get_sys_types
#define get_sys_types () i386_sys_types
Definition at line 1046 of file fdisk.c.
HDIO_GETGEO
#define HDIO_GETGEO 0x0301 /* get device geometry */
Definition at line 186 of file fdisk.c.
IF_FEATURE_FDISK_BLKSIZE
#define IF_FEATURE_FDISK_BLKSIZE (a)
Definition at line 134 of file fdisk.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
    sector_size = DEFAULT_SECTOR_SIZE; \
    sector_offset = 1; \
    g_partitions = 4; \
    units_per_sector = 1; \
    dos_compatible_flag = 1; \
} while (0)
Definition at line 484 of file fdisk.c.
inline_if_little_endian
#define inline_if_little_endian /* nothing */
Definition at line 127 of file fdisk.c.
IS_EXTENDED
#define IS_EXTENDED (i) ((i) == EXTENDED || (i) == WIN98_EXTENDED || (i) == LINUX_EXTENDED)
Definition at line 535 of file fdisk.c.
kern_heads
#define kern_heads (G.kern_heads)
Definition at line 476 of file fdisk.c.
kern_sectors
#define kern_sectors (G.kern_sectors)
Definition at line 477 of file fdisk.c.
LABEL_IS_AIX
#define LABEL_IS_AIX 0
Definition at line 264 of file fdisk.c.
LABEL_IS_DOS
#define LABEL_IS_DOS (LABEL_DOS == current_label_type)
Definition at line 242 of file fdisk.c.
LABEL_IS_GPT
#define LABEL_IS_GPT 0
Definition at line 280 of file fdisk.c.
LABEL_IS_OSF
#define LABEL_IS_OSF 0
Definition at line 272 of file fdisk.c.
LABEL_IS_SGI
#define LABEL_IS_SGI 0
Definition at line 256 of file fdisk.c.
LABEL_IS_SUN
#define LABEL_IS_SUN 0
Definition at line 248 of file fdisk.c.
line_buffer
#define line_buffer (G.line_buffer)
Definition at line 481 of file fdisk.c.
line_ptr
#define line_ptr (G.line_ptr)
Definition at line 454 of file fdisk.c.
LINUX_EXTENDED
#define LINUX_EXTENDED 0x85
Definition at line 150 of file fdisk.c.
LINUX_LVM
#define LINUX_LVM 0x8e
Definition at line 151 of file fdisk.c.
LINUX_NATIVE
#define LINUX_NATIVE 0x83
Definition at line 149 of file fdisk.c.
LINUX_PARTITION
#define LINUX_PARTITION 0x81
Definition at line 147 of file fdisk.c.
LINUX_RAID
#define LINUX_RAID 0xfd
Definition at line 152 of file fdisk.c.
LINUX_SWAP
#define LINUX_SWAP 0x82
Definition at line 148 of file fdisk.c.
listing
#define listing (G.listing)
Definition at line 467 of file fdisk.c.
listingbuf
#define listingbuf (G.listingbuf)
Definition at line 480 of file fdisk.c.
MAX_SECTOR_SIZE
#define MAX_SECTOR_SIZE 2048
Definition at line 139 of file fdisk.c.
MAXIMUM_PARTS
#define MAXIMUM_PARTS 60
Definition at line 141 of file fdisk.c.
MBRbuffer
#define MBRbuffer (G.MBRbuffer)
Definition at line 482 of file fdisk.c.
nowarn
#define nowarn (G.nowarn)
Definition at line 469 of file fdisk.c.
possibly_osf_label
#define possibly_osf_label (G.possibly_osf_label)
Definition at line 466 of file fdisk.c.
pt_heads
#define pt_heads (G.pt_heads)
Definition at line 474 of file fdisk.c.
pt_offset
#define pt_offset (b, n) ((struct partition *)((b) + 0x1be + (n) * sizeof(struct partition)))
Definition at line 542 of file fdisk.c.
pt_sectors
#define pt_sectors (G.pt_sectors)
Definition at line 475 of file fdisk.c.
ptes
#define ptes (G.ptes)
Definition at line 483 of file fdisk.c.
scround
#define scround (x) (((x)+units_per_sector-1)/units_per_sector)
Definition at line 540 of file fdisk.c.
sector
#define sector (s) ((s) & 0x3f)
Definition at line 545 of file fdisk.c.
sector_offset
#define sector_offset (G.sector_offset)
Definition at line 460 of file fdisk.c.
SECTOR_SIZE
#define SECTOR_SIZE 512 /* still used in osf/sgi/sun code */
Definition at line 140 of file fdisk.c.
sector_size
#define sector_size (G.sector_size)
Definition at line 458 of file fdisk.c.
SFMT
#define SFMT SECT_FMT
STATIC_AIX
#define STATIC_AIX extern
Definition at line 265 of file fdisk.c.
STATIC_GPT
#define STATIC_GPT extern
Definition at line 281 of file fdisk.c.
STATIC_OSF
#define STATIC_OSF extern
Definition at line 273 of file fdisk.c.
STATIC_SGI
#define STATIC_SGI extern
Definition at line 257 of file fdisk.c.
STATIC_SUN
#define STATIC_SUN extern
Definition at line 249 of file fdisk.c.
sunlabel
#define sunlabel ((sun_partition *)MBRbuffer)
Definition at line 754 of file fdisk.c.
total_number_of_sectors
#define total_number_of_sectors (G.total_number_of_sectors)
Definition at line 479 of file fdisk.c.
unable_to_open
#define unable_to_open "can't open '%s'"
Definition at line 234 of file fdisk.c.
unable_to_read
#define unable_to_read "can't read '%s'"
Definition at line 235 of file fdisk.c.
unable_to_seek
#define unable_to_seek "can't seek '%s'"
Definition at line 236 of file fdisk.c.
units_per_sector
#define units_per_sector (G.units_per_sector)
Definition at line 457 of file fdisk.c.
user_cylinders
#define user_cylinders (G.user_cylinders)
Definition at line 471 of file fdisk.c.
user_heads
#define user_heads (G.user_heads)
Definition at line 472 of file fdisk.c.
user_sectors
#define user_sectors (G.user_sectors)
Definition at line 473 of file fdisk.c.
user_set_sector_size
#define user_set_sector_size (G.user_set_sector_size)
Definition at line 459 of file fdisk.c.
WIN98_EXTENDED
#define WIN98_EXTENDED 0x0f
Definition at line 146 of file fdisk.c.
Typedef Documentation
sector_t
typedef uint32_t sector_t
Definition at line 170 of file fdisk.c.
sun_partition
typedef struct sun_partition sun_partition
Definition at line 622 of file fdisk.c.
ullong
typedef unsigned long long ullong
Definition at line 166 of file fdisk.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_b
OPT_C
OPT_H
OPT_l
OPT_S
OPT_u
OPT_s
Definition at line 155 of file fdisk.c.
      {
     OPT_b = 1 << 0,
     OPT_C = 1 << 1,
     OPT_H = 1 << 2,
     OPT_l = 1 << 3,
     OPT_S = 1 << 4,
     OPT_u = 1 << 5,
     OPT_s = (1 << 6) * ENABLE_FEATURE_FDISK_BLKSIZE,
 };
anonymous enum
anonymous enum
Enumerator
dev_fd
Definition at line 411 of file fdisk.c.
      {
     dev_fd = 3                  /* the disk */
 };
action
enum action
Enumerator
OPEN_MAIN
TRY_ONLY
CREATE_EMPTY_DOS
CREATE_EMPTY_SUN
Definition at line 284 of file fdisk.c.
 { OPEN_MAIN, TRY_ONLY, CREATE_EMPTY_DOS, CREATE_EMPTY_SUN };
label_type
enum label_type
Enumerator
LABEL_DOS
LABEL_SUN
LABEL_SGI
LABEL_AIX
LABEL_OSF
LABEL_GPT
Definition at line 238 of file fdisk.c.
                 {
     LABEL_DOS, LABEL_SUN, LABEL_SGI, LABEL_AIX, LABEL_OSF, LABEL_GPT
 };
Function Documentation
add_sun_partition()
STATIC_SUN void add_sun_partition (int n, int sys)
bb_BLKGETSIZE_sectors()
static sector_t bb_BLKGETSIZE_sectors (int fd) static
Definition at line 498 of file fdisk.c.
 {
     uint64_t v64;
     unsigned long longsectors;
     if (ioctl(fd, BLKGETSIZE64, &v64) == 0) {
         /* Got bytes, convert to 512 byte sectors */
         v64 >>= 9;
         if (v64 != (sector_t)v64) {
  ret_trunc:
             /* Not only DOS, but all other partition tables
              * we support can't record more than 32 bit
              * sector counts or offsets
              */
             bb_simple_error_msg("device has more than 2^32 sectors, can't use all of them");
             v64 = (uint32_t)-1L;
         }
         return v64;
     }
     /* Needs temp of type long */
     if (ioctl(fd, BLKGETSIZE, &longsectors)) {
         /* Perhaps this is a disk image */
         off_t sz = lseek(fd, 0, SEEK_END);
         longsectors = 0;
         if (sz > 0)
             longsectors = (uoff_t)sz / sector_size;
         lseek(fd, 0, SEEK_SET);
     }
     if (sizeof(long) > sizeof(sector_t)
      && longsectors != (sector_t)longsectors
     ) {
         goto ret_trunc;
     }
     return longsectors;
 }
References bb_simple_error_msg(), BLKGETSIZE, BLKGETSIZE64, fd, ioctl(), lseek(), sector_size, SEEK_END, and SEEK_SET.
Referenced by fdisk_main(), and get_geometry().
bsd_select()
STATIC_OSF void bsd_select (void)
Referenced by fdisk_main().
check_consistency()
static void check_consistency (const struct partition * p, int partition) static
Definition at line 1985 of file fdisk.c.
 {
     unsigned pbc, pbh, pbs;          /* physical beginning c, h, s */
     unsigned pec, peh, pes;          /* physical ending c, h, s */
     unsigned lbc, lbh, lbs;          /* logical beginning c, h, s */
     unsigned lec, leh, les;          /* logical ending c, h, s */
     if (!g_heads || !g_sectors || (partition >= 4))
         return;         /* do not check extended partitions */
 /* physical beginning c, h, s */
     pbc = cylinder(p->sector, p->cyl);
     pbh = p->head;
     pbs = sector(p->sector);
 /* physical ending c, h, s */
     pec = cylinder(p->end_sector, p->end_cyl);
     peh = p->end_head;
     pes = sector(p->end_sector);
 /* compute logical beginning (c, h, s) */
     linear2chs(get_start_sect(p), &lbc, &lbh, &lbs);
 /* compute logical ending (c, h, s) */
     linear2chs(get_start_sect(p) + get_nr_sects(p) - 1, &lec, &leh, &les);
 /* Same physical / logical beginning? */
     if (g_cylinders <= 1024 && (pbc != lbc || pbh != lbh || pbs != lbs)) {
         printf("Partition %u has different physical/logical "
             "start (non-Linux?):\n", partition + 1);
         printf("     phys=(%u,%u,%u) ", pbc, pbh, pbs);
         printf("logical=(%u,%u,%u)\n", lbc, lbh, lbs);
     }
 /* Same physical / logical ending? */
     if (g_cylinders <= 1024 && (pec != lec || peh != leh || pes != les)) {
         printf("Partition %u has different physical/logical "
             "end:\n", partition + 1);
         printf("     phys=(%u,%u,%u) ", pec, peh, pes);
         printf("logical=(%u,%u,%u)\n", lec, leh, les);
     }
 }
References cylinder, g_cylinders, g_heads, g_sectors, get_nr_sects(), get_start_sect(), linear2chs(), p, printf, and sector.
Referenced by list_table().
chs_string11()
static const char* chs_string11 (unsigned cyl, unsigned head, unsigned sect) static
Definition at line 2193 of file fdisk.c.
 {
     char *buf = auto_string(xzalloc(sizeof(int)*3 * 3));
     sprintf(buf, "%u,%u,%u", cylinder(sect,cyl), head, sector(sect));
     return buf;
 }
References auto_string(), buf, partition::cyl, cylinder, head, sector, sprintf(), and xzalloc().
Referenced by list_table().
clear_partition()
static void clear_partition (struct partition * p) static
Definition at line 1075 of file fdisk.c.
 {
     if (p)
         memset(p, 0, sizeof(*p));
 }
References memset, and p.
Referenced by read_extended().
close_dev_fd()
static void close_dev_fd (void) static
Definition at line 550 of file fdisk.c.
 {
     /* Not really closing, but making sure it is open, and to harmless place */
     xmove_fd(xopen(bb_dev_null, O_RDONLY), dev_fd);
 }
References bb_dev_null, dev_fd, O_RDONLY, xmove_fd(), and xopen().
Referenced by fdisk_fatal(), fdisk_main(), get_boot(), and open_list_and_close().
create_sgiinfo()
STATIC_SGI void create_sgiinfo (void)
Referenced by fdisk_main().
fdisk_fatal()
static void fdisk_fatal (const char * why) static
Definition at line 612 of file fdisk.c.
 {
     if (listing) {
         close_dev_fd();
         longjmp(listingbuf, 1);
     }
     bb_error_msg_and_die(why, disk_device);
 }
References bb_error_msg_and_die(), close_dev_fd(), disk_device, listing, listingbuf, and longjmp().
Referenced by get_boot(), read_pte(), and seek_sector().
fdisk_main()
int fdisk_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 3026 of file fdisk.c.
 {
     unsigned opt;
     /*
      *  fdisk -v
      *  fdisk -l [-b sectorsize] [-u] device ...
      *  fdisk -s [partition] ...
      *  fdisk [-b sectorsize] [-u] device
      *
      * Options -C, -H, -S set the geometry.
      */
     INIT_G();
     close_dev_fd(); /* needed: fd 3 must not stay closed */
     opt = getopt32(argv, "b:+C:+H:+lS:+u" IF_FEATURE_FDISK_BLKSIZE("s"),
                 &sector_size, &user_cylinders, &user_heads, &user_sectors);
     argv += optind;
     if (opt & OPT_b) {
         /* Ugly: this sector size is really per device,
          * so cannot be combined with multiple disks,
          * and the same goes for the C/H/S options.
          */
         if (sector_size < 512
          || sector_size > 0x10000
          || (sector_size & (sector_size-1)) /* not power of 2 */
         ) {
             bb_show_usage();
         }
         sector_offset = 2;
         user_set_sector_size = 1;
     }
     if (user_heads <= 0 || user_heads >= 256)
         user_heads = 0;
     if (user_sectors <= 0 || user_sectors >= 64)
         user_sectors = 0;
     if (opt & OPT_u)
         display_in_cyl_units = 0; // -u
 #if ENABLE_FEATURE_FDISK_WRITABLE
     if (opt & OPT_l) {
         nowarn = 1;
 #endif
         if (*argv) {
             listing = 1;
             do {
                 open_list_and_close(*argv, 1);
             } while (*++argv);
         } else {
             /* we don't have device names, */
             /* use /proc/partitions instead */
             list_devs_in_proc_partititons();
         }
         return 0;
 #if ENABLE_FEATURE_FDISK_WRITABLE
     }
 #endif
 #if ENABLE_FEATURE_FDISK_BLKSIZE
     if (opt & OPT_s) {
         int j;
         nowarn = 1;
         if (!argv[0])
             bb_show_usage();
         for (j = 0; argv[j]; j++) {
             unsigned long long size;
             fd = xopen(argv[j], O_RDONLY);
             size = bb_BLKGETSIZE_sectors(fd) / 2;
             close(fd);
             if (argv[1])
                 printf("%llu\n", size);
             else
                 printf("%s: %llu\n", argv[j], size);
         }
         return 0;
     }
 #endif
 #if ENABLE_FEATURE_FDISK_WRITABLE
     if (!argv[0] || argv[1])
         bb_show_usage();
     disk_device = argv[0];
     get_boot(OPEN_MAIN);
     if (LABEL_IS_OSF) {
         /* OSF label, and no DOS label */
         printf("Detected an OSF/1 disklabel on %s, entering "
             "disklabel mode\n", disk_device);
         bsd_select();
         /*Why do we do this?  It seems to be counter-intuitive*/
         current_label_type = LABEL_DOS;
         /* If we return we may want to make an empty DOS label? */
     }
     while (1) {
         int c;
         bb_putchar('\n');
         c = 0x20 | read_nonempty("Command (m for help): ");
         switch (c) {
         case 'a':
             if (LABEL_IS_DOS)
                 toggle_active(get_partition(1, g_partitions));
             else if (LABEL_IS_SUN)
                 toggle_sunflags(get_partition(1, g_partitions),
                         0x01);
             else if (LABEL_IS_SGI)
                 sgi_set_bootpartition(
                     get_partition(1, g_partitions));
             else
                 unknown_command(c);
             break;
         case 'b':
             if (LABEL_IS_SGI) {
                 printf("\nThe current boot file is: %s\n",
                     sgi_get_bootfile());
                 if (read_maybe_empty("Please enter the name of the "
                         "new boot file: ") == '\n')
                     puts("Boot file unchanged");
                 else
                     sgi_set_bootfile(line_ptr);
             }
 #if ENABLE_FEATURE_OSF_LABEL
             else
                 bsd_select();
 #endif
             break;
         case 'c':
             if (LABEL_IS_DOS)
                 toggle_dos_compatibility_flag();
             else if (LABEL_IS_SUN)
                 toggle_sunflags(get_partition(1, g_partitions),
                         0x10);
             else if (LABEL_IS_SGI)
                 sgi_set_swappartition(
                         get_partition(1, g_partitions));
             else
                 unknown_command(c);
             break;
         case 'd':
             {
                 int j;
             /* If sgi_label then don't use get_existing_partition,
                let the user select a partition, since
                get_existing_partition() only works for Linux-like
                partition tables */
                 if (!LABEL_IS_SGI) {
                     j = get_existing_partition(1, g_partitions);
                 } else {
                     j = get_partition(1, g_partitions);
                 }
                 if (j >= 0)
                     delete_partition(j);
             }
             break;
         case 'i':
             if (LABEL_IS_SGI)
                 create_sgiinfo();
             else
                 unknown_command(c);
         case 'l':
             list_types(get_sys_types());
             break;
         case 'm':
             menu();
             break;
         case 'n':
             new_partition();
             break;
         case 'o':
             create_doslabel();
             break;
         case 'p':
             list_table(0);
             break;
         case 'q':
             if (ENABLE_FEATURE_CLEAN_UP)
                 close_dev_fd();
             bb_putchar('\n');
             return 0;
         case 's':
 #if ENABLE_FEATURE_SUN_LABEL
             create_sunlabel();
 #endif
             break;
         case 't':
             change_sysid();
             break;
         case 'u':
             change_units();
             break;
         case 'v':
             verify();
             break;
         case 'w':
             write_table();  /* does not return */
             break;
 #if ENABLE_FEATURE_FDISK_ADVANCED
         case 'x':
             if (LABEL_IS_SGI) {
                 puts("\n\tSorry, no experts menu for SGI "
                     "partition tables available\n");
             } else
                 xselect();
             break;
 #endif
         default:
             unknown_command(c);
             menu();
         }
     }
     return 0;
 #endif /* FEATURE_FDISK_WRITABLE */
 }
References argv, bb_BLKGETSIZE_sectors(), bb_putchar(), bb_show_usage(), bsd_select(), c, close(), close_dev_fd(), create_sgiinfo(), current_label_type, disk_device, display_in_cyl_units, fd, g_partitions, get_boot, get_sys_types, getopt32(), IF_FEATURE_FDISK_BLKSIZE, INIT_G, j, LABEL_DOS, LABEL_IS_DOS, LABEL_IS_OSF, LABEL_IS_SGI, LABEL_IS_SUN, line_ptr, list_devs_in_proc_partititons(), list_table(), listing, nowarn, O_RDONLY, open_list_and_close(), OPEN_MAIN, opt, OPT_b, OPT_l, OPT_s, OPT_u, optind, printf, puts(), sector_offset, sector_size, sgi_get_bootfile(), sgi_set_bootfile(), sgi_set_bootpartition(), sgi_set_swappartition(), size, toggle_sunflags(), user_cylinders, user_heads, user_sectors, user_set_sector_size, verify, and xopen().
get_boot()
static int get_boot (void) static
Definition at line 1442 of file fdisk.c.
 {
     int i, fd;
     g_partitions = 4;
     for (i = 0; i < 4; i++) {
         struct pte *pe = &ptes[i];
         pe->part_table = pt_offset(MBRbuffer, i);
         pe->ext_pointer = NULL;
         pe->offset_from_dev_start = 0;
         pe->sectorbuffer = MBRbuffer;
 #if ENABLE_FEATURE_FDISK_WRITABLE
         pe->changed = (what == CREATE_EMPTY_DOS);
 #endif
     }
 #if ENABLE_FEATURE_FDISK_WRITABLE
 // ALERT! highly idiotic design!
 // We end up here when we call get_boot() recursively
 // via get_boot() [table is bad] -> create_doslabel() -> get_boot(CREATE_EMPTY_DOS).
 // or get_boot() [table is bad] -> create_sunlabel() -> get_boot(CREATE_EMPTY_SUN).
 // (just factor out re-init of ptes[0,1,2,3] in a separate fn instead?)
 // So skip opening device _again_...
     if (what == CREATE_EMPTY_DOS  IF_FEATURE_SUN_LABEL(|| what == CREATE_EMPTY_SUN))
         goto created_table;
     fd = open(disk_device, (option_mask32 & OPT_l) ? O_RDONLY : O_RDWR);
     if (fd < 0) {
         fd = open(disk_device, O_RDONLY);
         if (fd < 0) {
             if (what == TRY_ONLY)
                 return 1;
             fdisk_fatal(unable_to_open);
         }
         printf("'%s' is opened for read only\n", disk_device);
     }
     xmove_fd(fd, dev_fd);
     if (512 != full_read(dev_fd, MBRbuffer, 512)) {
         if (what == TRY_ONLY) {
             close_dev_fd();
             return 1;
         }
         fdisk_fatal(unable_to_read);
     }
 #else
     fd = open(disk_device, O_RDONLY);
     if (fd < 0)
         return 1;
     if (512 != full_read(fd, MBRbuffer, 512)) {
         close(fd);
         return 1;
     }
     xmove_fd(fd, dev_fd);
 #endif
     get_geometry();
     update_units();
 #if ENABLE_FEATURE_SUN_LABEL
     if (check_sun_label())
         return 0;
 #endif
 #if ENABLE_FEATURE_SGI_LABEL
     if (check_sgi_label())
         return 0;
 #endif
 #if ENABLE_FEATURE_AIX_LABEL
     if (check_aix_label())
         return 0;
 #endif
 #if ENABLE_FEATURE_GPT_LABEL
     if (check_gpt_label())
         return 0;
 #endif
 #if ENABLE_FEATURE_OSF_LABEL
     if (check_osf_label()) {
         possibly_osf_label = 1;
         if (!valid_part_table_flag(MBRbuffer)) {
             current_label_type = LABEL_OSF;
             return 0;
         }
         puts("This disk has both DOS and BSD magic.\n"
              "Give the 'b' command to go to BSD mode.");
     }
 #endif
 #if !ENABLE_FEATURE_FDISK_WRITABLE
     if (!valid_part_table_flag(MBRbuffer))
         return -1;
 #else
     if (!valid_part_table_flag(MBRbuffer)) {
         if (what == OPEN_MAIN) {
             puts("Device contains neither a valid DOS "
                  "partition table, nor Sun, SGI, OSF or GPT "
                  "disklabel");
 #ifdef __sparc__
             IF_FEATURE_SUN_LABEL(create_sunlabel();)
 #else
             create_doslabel();
 #endif
             return 0;
         }
         /* TRY_ONLY: */
         return -1;
     }
  created_table:
 #endif /* FEATURE_FDISK_WRITABLE */
     IF_FEATURE_FDISK_WRITABLE(warn_cylinders();)
     warn_geometry();
     for (i = 0; i < 4; i++) {
         if (IS_EXTENDED(ptes[i].part_table->sys_ind)) {
             if (g_partitions != 4)
                 printf("Ignoring extra extended "
                     "partition %u\n", i + 1);
             else
                 read_extended(i);
         }
     }
     for (i = 3; i < g_partitions; i++) {
         struct pte *pe = &ptes[i];
         if (!valid_part_table_flag(pe->sectorbuffer)) {
             printf("Warning: invalid flag 0x%02x,0x%02x of partition "
                 "table %u will be corrected by w(rite)\n",
                 pe->sectorbuffer[510],
                 pe->sectorbuffer[511],
                 i + 1);
             IF_FEATURE_FDISK_WRITABLE(pe->changed = 1;)
         }
     }
     return 0;
 }
References close(), close_dev_fd(), CREATE_EMPTY_DOS, CREATE_EMPTY_SUN, current_label_type, dev_fd, disk_device, pte::ext_pointer, fd, fdisk_fatal(), full_read(), g_partitions, get_geometry(), i, IS_EXTENDED, LABEL_OSF, MBRbuffer, NULL, O_RDONLY, O_RDWR, pte::offset_from_dev_start, open(), OPEN_MAIN, OPT_l, option_mask32, pte::part_table, possibly_osf_label, printf, pt_offset, ptes, puts(), read_extended(), pte::sectorbuffer, partition::sys_ind, TRY_ONLY, unable_to_open, unable_to_read, update_units(), valid_part_table_flag(), warn_geometry(), and xmove_fd().
get_geometry()
static void get_geometry (void) static
Definition at line 1387 of file fdisk.c.
 {
     int sec_fac;
     get_sectorsize();
     sec_fac = sector_size / 512;
 #if ENABLE_FEATURE_SUN_LABEL
     guess_device_type();
 #endif
     g_heads = g_cylinders = g_sectors = 0;
     kern_heads = kern_sectors = 0;
     pt_heads = pt_sectors = 0;
     get_kernel_geometry();
     get_partition_table_geometry();
     g_heads = user_heads ? user_heads :
         pt_heads ? pt_heads :
         kern_heads ? kern_heads : 255;
     g_sectors = user_sectors ? user_sectors :
         pt_sectors ? pt_sectors :
         kern_sectors ? kern_sectors : 63;
     total_number_of_sectors = bb_BLKGETSIZE_sectors(dev_fd);
     sector_offset = 1;
     if (dos_compatible_flag)
         sector_offset = g_sectors;
     g_cylinders = total_number_of_sectors / (g_heads * g_sectors * sec_fac);
     if (!g_cylinders)
         g_cylinders = user_cylinders;
 }
References bb_BLKGETSIZE_sectors(), dev_fd, dos_compatible_flag, g_cylinders, g_heads, g_sectors, get_kernel_geometry(), get_partition_table_geometry(), get_sectorsize(), kern_heads, kern_sectors, pt_heads, pt_sectors, sector_offset, sector_size, total_number_of_sectors, user_cylinders, user_heads, and user_sectors.
Referenced by get_boot().
get_kernel_geometry()
static void get_kernel_geometry (void) static
Definition at line 1342 of file fdisk.c.
 {
     struct hd_geometry geometry;
     if (!ioctl(dev_fd, HDIO_GETGEO, &geometry)) {
         kern_heads = geometry.heads;
         kern_sectors = geometry.sectors;
         /* never use geometry.cylinders - it is truncated */
     }
 }
References dev_fd, HDIO_GETGEO, hd_geometry::heads, ioctl(), kern_heads, kern_sectors, and hd_geometry::sectors.
Referenced by get_geometry().
get_nr_sects()
static sector_t get_nr_sects (const struct partition * p) static
Definition at line 832 of file fdisk.c.
 {
     return read4_little_endian(p->size4);
 }
References p, and read4_little_endian().
Referenced by check_consistency(), list_table(), and read_extended().
get_partition_start_from_dev_start()
static sector_t get_partition_start_from_dev_start (const struct pte * pe) static
Definition at line 877 of file fdisk.c.
 {
     return pe->offset_from_dev_start + get_start_sect(pe->part_table);
 }
References get_start_sect(), pte::offset_from_dev_start, and pte::part_table.
Referenced by list_table(), and wrong_p_order().
get_partition_table_geometry()
static void get_partition_table_geometry (void) static
Definition at line 1354 of file fdisk.c.
 {
     const unsigned char *bufp = (const unsigned char *)MBRbuffer;
     struct partition *p;
     int i, h, s, hh, ss;
     int first = 1;
     int bad = 0;
     if (!(valid_part_table_flag((char*)bufp)))
         return;
     hh = ss = 0;
     for (i = 0; i < 4; i++) {
         p = pt_offset(bufp, i);
         if (p->sys_ind != 0) {
             h = p->end_head + 1;
             s = (p->end_sector & 077);
             if (first) {
                 hh = h;
                 ss = s;
                 first = 0;
             } else if (hh != h || ss != s)
                 bad = 1;
         }
     }
     if (!first && !bad) {
         pt_heads = hh;
         pt_sectors = ss;
     }
 }
References first, h, i, MBRbuffer, p, pt_heads, pt_offset, pt_sectors, s, and valid_part_table_flag().
Referenced by get_geometry().
get_sectorsize()
static void get_sectorsize (void) static
Definition at line 1328 of file fdisk.c.
 {
     if (!user_set_sector_size) {
         int arg;
         if (ioctl(dev_fd, BLKSSZGET, &arg) == 0)
             sector_size = arg;
         if (sector_size != DEFAULT_SECTOR_SIZE)
             printf("Note: sector size is %u "
                 "(not " DEFAULT_SECTOR_SIZE_STR ")\n",
                 sector_size);
     }
 }
References BLKSSZGET, DEFAULT_SECTOR_SIZE, DEFAULT_SECTOR_SIZE_STR, dev_fd, ioctl(), printf, sector_size, and user_set_sector_size.
Referenced by get_geometry().
get_start_sect()
static sector_t get_start_sect (const struct partition * p) static
Definition at line 826 of file fdisk.c.
 {
     return read4_little_endian(p->start4);
 }
References p, and read4_little_endian().
Referenced by check_consistency(), get_partition_start_from_dev_start(), and read_extended().
gpt_list_table()
STATIC_GPT void gpt_list_table (int xtra)
Referenced by list_table().
is_cleared_partition()
static int is_cleared_partition (const struct partition * p) static
Definition at line 1063 of file fdisk.c.
 {
     /* We consider partition "cleared" only if it has only zeros */
     const char *cp = (const char *)p;
     int cnt = sizeof(*p);
     char bits = 0;
     while (--cnt >= 0)
         bits |= *cp++;
     return (bits == 0);
 }
References cnt, and p.
Referenced by list_table().
is_ide_cdrom_or_tape()
static int is_ide_cdrom_or_tape (const char * device) static
Definition at line 2889 of file fdisk.c.
 {
     FILE *procf;
     char buf[100];
     struct stat statbuf;
     int is_ide = 0;
     /* No device was given explicitly, and we are trying some
        likely things.  But opening /dev/hdc may produce errors like
        "hdc: tray open or drive not ready"
        if it happens to be a CD-ROM drive. It even happens that
        the process hangs on the attempt to read a music CD.
        So try to be careful. This only works since 2.1.73. */
     if (!is_prefixed_with(device, "/dev/hd"))
         return 0;
     snprintf(buf, sizeof(buf), "/proc/ide/%s/media", device+5);
     procf = fopen_for_read(buf);
     if (procf != NULL && fgets(buf, sizeof(buf), procf))
         is_ide = (is_prefixed_with(buf, "cdrom") ||
               is_prefixed_with(buf, "tape"));
     else
         /* Now when this proc file does not exist, skip the
            device when it is read-only. */
         if (stat(device, &statbuf) == 0)
             is_ide = ((statbuf.st_mode & 0222) == 0);
     if (procf)
         fclose(procf);
     return is_ide;
 }
References buf, device, fclose(), fgets, fopen_for_read(), is_prefixed_with(), NULL, snprintf(), stat::st_mode, and stat().
Referenced by open_list_and_close().
is_whole_disk()
static int is_whole_disk (const char * disk) static
Definition at line 2970 of file fdisk.c.
 {
     unsigned len;
     int fd = open(disk, O_RDONLY);
     if (fd != -1) {
         struct hd_geometry geometry;
         int err = ioctl(fd, HDIO_GETGEO, &geometry);
         close(fd);
         if (!err)
             return (geometry.start == 0);
     }
     /* Treat "nameN" as a partition name, not whole disk */
     /* note: mmcblk0 should work from the geometry check above */
     len = strlen(disk);
     if (len != 0 && isdigit(disk[len - 1]))
         return 0;
     return 1;
 }
References close(), err(), fd, HDIO_GETGEO, ioctl(), isdigit, len, O_RDONLY, open(), hd_geometry::start, and strlen.
Referenced by list_devs_in_proc_partititons().
linear2chs()
static void linear2chs (unsigned ls, unsigned * c, unsigned * h, unsigned * s) static
Definition at line 1974 of file fdisk.c.
 {
     int spc = g_heads * g_sectors;
     *c = ls / spc;
     ls = ls % spc;
     *h = ls / g_sectors;
     *s = ls % g_sectors + 1;  /* sectors count from 1 */
 }
References c, g_heads, g_sectors, h, and s.
Referenced by check_consistency().
list_devs_in_proc_partititons()
static void list_devs_in_proc_partititons (void) static
Definition at line 2995 of file fdisk.c.
 {
     FILE *procpt;
     char line[100], ptname[100], devname[120];
     int ma, mi, sz;
     procpt = fopen_or_warn("/proc/partitions", "r");
     while (fgets(line, sizeof(line), procpt)) {
         if (sscanf(line, " %u %u %u %[^\n ]",
                 &ma, &mi, &sz, ptname) != 4)
             continue;
         sprintf(devname, "/dev/%s", ptname);
         if (is_whole_disk(devname))
             open_list_and_close(devname, 0);
     }
 #if ENABLE_FEATURE_CLEAN_UP
     fclose(procpt);
 #endif
 }
References fclose(), fgets, fopen_or_warn(), is_whole_disk(), open_list_and_close(), sprintf(), and sscanf().
Referenced by fdisk_main().
list_disk_geometry()
static void list_disk_geometry (void) static
Definition at line 2029 of file fdisk.c.
 {
     ullong xbytes = total_number_of_sectors / (1024*1024 / 512);
     char x = 'M';
     if (xbytes >= 10000) {
         xbytes += 512; /* fdisk util-linux 2.28 does this */
         xbytes /= 1024;
         x = 'G';
     }
     printf("Disk %s: %llu %cB, %llu bytes, %"SECT_FMT"u sectors\n"
         "%u cylinders, %u heads, %u sectors/track\n"
         "Units: %ss of %u * %u = %u bytes\n"
         "\n",
         disk_device, xbytes, x,
         ((ullong)total_number_of_sectors * 512), total_number_of_sectors,
         g_cylinders, g_heads, g_sectors,
         str_units(),
         units_per_sector, sector_size, units_per_sector * sector_size
     );
 }
References disk_device, g_cylinders, g_heads, g_sectors, printf, sector_size, str_units(), total_number_of_sectors, units_per_sector, and x.
Referenced by list_table(), and open_list_and_close().
list_table()
static void list_table (int xtra) static
Definition at line 2201 of file fdisk.c.
 {
     int i, w;
     if (LABEL_IS_SUN) {
         sun_list_table(xtra);
         return;
     }
     if (LABEL_IS_SGI) {
         sgi_list_table(xtra);
         return;
     }
     if (LABEL_IS_GPT) {
         gpt_list_table(xtra);
         return;
     }
     list_disk_geometry();
     if (LABEL_IS_OSF) {
         xbsd_print_disklabel(xtra);
         return;
     }
     /* Heuristic: we list partition 3 of /dev/foo as /dev/foo3,
      * but if the device name ends in a digit, say /dev/foo1,
      * then the partition is called /dev/foo1p3.
      */
     w = strlen(disk_device);
     if (w && isdigit(disk_device[w-1]))
         w++;
     if (w < 7)
         w = 7;
     printf("%-*s Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type\n",
            w-1, "Device");
     for (i = 0; i < g_partitions; i++) {
         const struct partition *p;
         const struct pte *pe = &ptes[i];
         char boot4[4];
         char numstr6[6];
         sector_t start_sect;
         sector_t end_sect;
         sector_t nr_sects;
         p = pe->part_table;
         if (!p || is_cleared_partition(p))
             continue;
         sprintf(boot4, "%02x", p->boot_ind);
         if ((p->boot_ind & 0x7f) == 0) {
             /* 0x80 shown as '*', 0x00 is ' ' */
             boot4[0] = p->boot_ind ? '*' : ' ';
             boot4[1] = ' ';
         }
         start_sect = get_partition_start_from_dev_start(pe);
         end_sect = start_sect;
         nr_sects = get_nr_sects(p);
         if (nr_sects != 0)
             end_sect += nr_sects - 1;
         smart_ulltoa5((ullong)nr_sects * sector_size,
             numstr6, " KMGTPEZY")[0] = '\0';
 #define SFMT SECT_FMT
         //      Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type
         printf("%s%s %-11s"" %-11s"" %10"SFMT"u %10"SFMT"u %10"SFMT"u %s %2x %s\n",
             partname(disk_device, i+1, w+2),
             boot4,
             chs_string11(p->cyl, p->head, p->sector),
             chs_string11(p->end_cyl, p->end_head, p->end_sector),
             start_sect,
             end_sect,
             nr_sects,
             numstr6,
             p->sys_ind,
             partition_type(p->sys_ind)
         );
 #undef SFMT
         check_consistency(p, i);
     }
     /* Is partition table in disk order? It need not be, but... */
     /* partition table entries are not checked for correct order
      * if this is a sgi, sun or aix labeled disk... */
     if (LABEL_IS_DOS && wrong_p_order(NULL)) {
         /* FIXME */
         puts("\nPartition table entries are not in disk order");
     }
 }
References check_consistency(), chs_string11(), disk_device, g_partitions, get_nr_sects(), get_partition_start_from_dev_start(), gpt_list_table(), i, is_cleared_partition(), isdigit, LABEL_IS_DOS, LABEL_IS_GPT, LABEL_IS_OSF, LABEL_IS_SGI, LABEL_IS_SUN, list_disk_geometry(), NULL, p, pte::part_table, partition_type(), partname(), printf, ptes, puts(), sector_size, SFMT, sgi_list_table(), smart_ulltoa5(), sprintf(), strlen, sun_list_table(), w, wrong_p_order(), and xbsd_print_disklabel().
Referenced by fdisk_main(), and open_list_and_close().
open_list_and_close()
static void open_list_and_close (const char * device, int user_specified) static
Definition at line 2924 of file fdisk.c.
 {
     int gb;
     disk_device = device;
     if (setjmp(listingbuf))
         return;
     if (!user_specified)
         if (is_ide_cdrom_or_tape(device))
             return;
     /* Open disk_device, save file descriptor to dev_fd */
     errno = 0;
     gb = get_boot(TRY_ONLY);
     if (gb > 0) {   /* I/O error */
         /* Ignore other errors, since we try IDE
            and SCSI hard disks which may not be
            installed on the system. */
         if (user_specified || errno == EACCES)
             bb_perror_msg("can't open '%s'", device);
         return;
     }
     if (gb < 0) { /* no DOS signature */
         list_disk_geometry();
         if (LABEL_IS_AIX)
             goto ret;
 #if ENABLE_FEATURE_OSF_LABEL
         if (bsd_trydev(device) < 0)
 #endif
             printf("Disk %s doesn't contain a valid "
                 "partition table\n", device);
     } else {
         list_table(0);
 #if ENABLE_FEATURE_FDISK_WRITABLE
         if (!LABEL_IS_SUN && g_partitions > 4) {
             delete_partition(ext_index);
         }
 #endif
     }
  ret:
     close_dev_fd();
 }
References bb_perror_msg(), close_dev_fd(), device, disk_device, EACCES, errno, ext_index, g_partitions, get_boot, is_ide_cdrom_or_tape(), LABEL_IS_AIX, LABEL_IS_SUN, list_disk_geometry(), list_table(), listingbuf, printf, setjmp, and TRY_ONLY.
Referenced by fdisk_main(), and list_devs_in_proc_partititons().
partition_type()
static const char * partition_type (unsigned char type) static
Definition at line 1050 of file fdisk.c.
 {
     int i;
     const char *const *types = get_sys_types();
     for (i = 0; types[i]; i++)
         if ((unsigned char)types[i][0] == type)
             return types[i] + 1;
     return "Unknown";
 }
References get_sys_types, i, type, and types.
Referenced by list_table().
partname()
static const char* partname (const char * dev, int pno, int lth) static
Definition at line 558 of file fdisk.c.
 {
     const char *p;
     int w, wp;
     int bufsiz;
     char *bufp;
     bufp = auto_string(xzalloc(80));
     bufsiz = 80;
     w = strlen(dev);
     p = "";
     if (isdigit(dev[w-1]))
         p = "p";
     /* devfs kludge - note: fdisk partition names are not supposed
        to equal kernel names, so there is no reason to do this */
     if (strcmp(dev + w - 4, "disc") == 0) {
         w -= 4;
         p = "part";
     }
     wp = strlen(p);
     if (lth) {
         snprintf(bufp, bufsiz, "%*.*s%s%-2u",
             lth-wp-2, w, dev, p, pno);
     } else {
         snprintf(bufp, bufsiz, "%.*s%s%-2u", w, dev, p, pno);
     }
     return bufp;
 }
References auto_string(), isdigit, p, snprintf(), strcmp, strlen, w, and xzalloc().
Referenced by list_table().
read4_little_endian()
static inline_if_little_endian unsigned read4_little_endian (const unsigned char * cp) static
Definition at line 818 of file fdisk.c.
 {
     uint32_t v;
     move_from_unaligned32(v, cp);
     return SWAP_LE32(v);
 }
References move_from_unaligned32, and SWAP_LE32.
Referenced by get_nr_sects(), and get_start_sect().
read_extended()
static void read_extended (int ext) static
Definition at line 1214 of file fdisk.c.
 {
     int i;
     struct pte *pex;
     struct partition *p, *q;
     ext_index = ext;
     pex = &ptes[ext];
     pex->ext_pointer = pex->part_table;
     p = pex->part_table;
     if (!get_start_sect(p)) {
         puts("Bad offset in primary extended partition");
         return;
     }
     while (IS_EXTENDED(p->sys_ind)) {
         struct pte *pe = &ptes[g_partitions];
         if (g_partitions >= MAXIMUM_PARTS) {
             /* This is not a Linux restriction, but
                this program uses arrays of size MAXIMUM_PARTS.
                Do not try to 'improve' this test. */
             struct pte *pre = &ptes[g_partitions - 1];
 #if ENABLE_FEATURE_FDISK_WRITABLE
             printf("Warning: deleting partitions after %u\n",
                 g_partitions);
             pre->changed = 1;
 #endif
             clear_partition(pre->ext_pointer);
             return;
         }
         read_pte(pe, extended_offset + get_start_sect(p));
         if (!extended_offset)
             extended_offset = get_start_sect(p);
         q = p = pt_offset(pe->sectorbuffer, 0);
         for (i = 0; i < 4; i++, p++) if (get_nr_sects(p)) {
             if (IS_EXTENDED(p->sys_ind)) {
                 if (pe->ext_pointer)
                     printf("Warning: extra link "
                         "pointer in partition table"
                         " %u\n", g_partitions + 1);
                 else
                     pe->ext_pointer = p;
             } else if (p->sys_ind) {
                 if (pe->part_table)
                     printf("Warning: ignoring extra "
                           "data in partition table"
                           " %u\n", g_partitions + 1);
                 else
                     pe->part_table = p;
             }
         }
         /* very strange code here... */
         if (!pe->part_table) {
             if (q != pe->ext_pointer)
                 pe->part_table = q;
             else
                 pe->part_table = q + 1;
         }
         if (!pe->ext_pointer) {
             if (q != pe->part_table)
                 pe->ext_pointer = q;
             else
                 pe->ext_pointer = q + 1;
         }
         p = pe->ext_pointer;
         g_partitions++;
     }
 #if ENABLE_FEATURE_FDISK_WRITABLE
     /* remove empty links */
  remove:
     for (i = 4; i < g_partitions; i++) {
         struct pte *pe = &ptes[i];
         if (!get_nr_sects(pe->part_table)
          && (g_partitions > 5 || ptes[4].part_table->sys_ind)
         ) {
             printf("Omitting empty partition (%u)\n", i+1);
             delete_partition(i);
             goto remove;    /* numbering changed */
         }
     }
 #endif
 }
References clear_partition(), ext_index, pte::ext_pointer, extended_offset, g_partitions, get_nr_sects(), get_start_sect(), i, IS_EXTENDED, MAXIMUM_PARTS, p, pte::part_table, printf, pt_offset, ptes, puts(), read_pte(), remove(), and pte::sectorbuffer.
Referenced by get_boot().
read_pte()
static void read_pte (struct pte * pe, sector_t offset) static
Definition at line 862 of file fdisk.c.
 {
     pe->offset_from_dev_start = offset;
     pe->sectorbuffer = xzalloc(sector_size);
     seek_sector(offset);
     /* xread would make us abort - bad for fdisk -l */
     if (full_read(dev_fd, pe->sectorbuffer, sector_size) != sector_size)
         fdisk_fatal(unable_to_read);
 #if ENABLE_FEATURE_FDISK_WRITABLE
     pe->changed = 0;
 #endif
     pe->part_table = pe->ext_pointer = NULL;
 }
References dev_fd, pte::ext_pointer, fdisk_fatal(), full_read(), NULL, offset, pte::offset_from_dev_start, pte::part_table, sector_size, pte::sectorbuffer, seek_sector(), unable_to_read, and xzalloc().
Referenced by read_extended().
seek_sector()
static void seek_sector (sector_t secno) static
Definition at line 622 of file fdisk.c.
 {
 #if ENABLE_FDISK_SUPPORT_LARGE_DISKS
     off64_t off = (off64_t)secno * sector_size;
     if (lseek64(dev_fd, off, SEEK_SET) == (off64_t) -1)
         fdisk_fatal(unable_to_seek);
 #else
     uint64_t off = (uint64_t)secno * sector_size;
     if (off > MAXINT(off_t)
      || lseek(dev_fd, (off_t)off, SEEK_SET) == (off_t) -1
     ) {
         fdisk_fatal(unable_to_seek);
     }
 #endif
 }
References dev_fd, fdisk_fatal(), lseek(), MAXINT, off, sector_size, SEEK_SET, and unable_to_seek.
Referenced by read_pte().
sgi_add_partition()
STATIC_SGI void sgi_add_partition (int n, int sys)
sgi_change_sysid()
STATIC_SGI void sgi_change_sysid (int i, int sys)
sgi_delete_partition()
STATIC_SGI void sgi_delete_partition (int i)
sgi_get_bootfile()
STATIC_SGI const char* sgi_get_bootfile (void)
Referenced by fdisk_main().
sgi_get_num_sectors()
STATIC_SGI unsigned sgi_get_num_sectors (int i)
sgi_get_sysid()
STATIC_SGI int sgi_get_sysid (int i)
sgi_list_table()
STATIC_SGI void sgi_list_table (int xtra)
Referenced by list_table().
sgi_set_bootfile()
STATIC_SGI void sgi_set_bootfile (const char * aFile)
Referenced by fdisk_main().
sgi_set_bootpartition()
STATIC_SGI void sgi_set_bootpartition (int i)
Referenced by fdisk_main().
sgi_set_swappartition()
STATIC_SGI void sgi_set_swappartition (int i)
Referenced by fdisk_main().
sgi_write_table()
STATIC_SGI void sgi_write_table (void)
str_units()
static ALWAYS_INLINE const char* str_units (void) static
Definition at line 601 of file fdisk.c.
 {
     return display_in_cyl_units ? "cylinder" : "sector";
 }
References display_in_cyl_units.
Referenced by list_disk_geometry().
sun_change_sysid()
STATIC_SUN void sun_change_sysid (int i, int sys)
sun_delete_partition()
STATIC_SUN void sun_delete_partition (int i)
sun_list_table()
STATIC_SUN void sun_list_table (int xtra)
Referenced by list_table().
sun_write_table()
STATIC_SUN void sun_write_table (void)
toggle_sunflags()
STATIC_SUN void toggle_sunflags (int i, unsigned char mask)
Referenced by fdisk_main().
update_units()
static void update_units (void) static
Definition at line 1187 of file fdisk.c.
 {
     int cyl_units = g_heads * g_sectors;
     if (display_in_cyl_units && cyl_units)
         units_per_sector = cyl_units;
     else
         units_per_sector = 1;   /* in sectors */
 }
References display_in_cyl_units, g_heads, g_sectors, and units_per_sector.
Referenced by get_boot().
valid_part_table_flag()
static int valid_part_table_flag (const char * mbuffer) static
Definition at line 607 of file fdisk.c.
 {
     return (mbuffer[510] == 0x55 && (uint8_t)mbuffer[511] == 0xaa);
 }
Referenced by get_boot(), and get_partition_table_geometry().
verify_sgi()
STATIC_SGI int verify_sgi (int verbose)
verify_sun()
STATIC_SUN void verify_sun (void)
warn_geometry()
static int warn_geometry (void) static
Definition at line 1166 of file fdisk.c.
 {
     if (g_heads && g_sectors && g_cylinders)
         return 0;
     printf("Unknown value(s) for:");
     if (!g_heads)
         printf(" heads");
     if (!g_sectors)
         printf(" sectors");
     if (!g_cylinders)
         printf(" cylinders");
 #if ENABLE_FEATURE_FDISK_WRITABLE
     puts(" (settable in the extra functions menu)");
 #else
     bb_putchar('\n');
 #endif
     return 1;
 }
References bb_putchar(), g_cylinders, g_heads, g_sectors, printf, and puts().
Referenced by get_boot().
wrong_p_order()
static int wrong_p_order (int * prev) static
Definition at line 2057 of file fdisk.c.
 {
     const struct pte *pe;
     const struct partition *p;
     sector_t last_p_start_pos = 0, p_start_pos;
     unsigned i, last_i = 0;
     for (i = 0; i < g_partitions; i++) {
         if (i == 4) {
             last_i = 4;
             last_p_start_pos = 0;
         }
         pe = &ptes[i];
         p = pe->part_table;
         if (p->sys_ind) {
             p_start_pos = get_partition_start_from_dev_start(pe);
             if (last_p_start_pos > p_start_pos) {
                 if (prev)
                     *prev = last_i;
                 return i;
             }
             last_p_start_pos = p_start_pos;
             last_i = i;
         }
     }
     return 0;
 }
References g_partitions, get_partition_start_from_dev_start(), i, p, pte::part_table, and ptes.
Referenced by list_table().
xbsd_print_disklabel()
STATIC_OSF void xbsd_print_disklabel (int)
Referenced by list_table().
Variable Documentation
ALIGN_PTR
const char* const i386_sys_types [] ALIGN_PTR static
Definition at line 309 of file fdisk.c.
FIX_ALIASING
struct sun_partition FIX_ALIASING
PACKED
struct partition PACKED
sgi_sys_types
STATIC_SGI const char* const sgi_sys_types[]
Definition at line 779 of file fdisk.c.
sun_sys_types
STATIC_SUN const char* const sun_sys_types[]
Definition at line 798 of file fdisk.c.