Fennix: Userspace/musl/src/signal/sigaction.c File Reference
sigaction.c File Reference
#include <signal.h>
#include <errno.h>
#include <string.h>
#include "syscall.h"
#include "pthread_impl.h"
#include "libc.h"
#include "lock.h"
#include "ksigaction.h"
Functions
void __get_handler_set (sigset_t *set)
int __libc_sigaction (int sig, const struct sigaction *restrict sa, struct sigaction *restrict old)
int __sigaction (int sig, const struct sigaction *restrict sa, struct sigaction *restrict old)
weak_alias (__sigaction, sigaction)
Variables
static int unmask_done
static unsigned long handler_set [_NSIG/(8 *sizeof(long))]
volatile int __eintr_valid_flag
Function Documentation
__get_handler_set()
void __get_handler_set (sigset_t * set)
Definition at line 13 of file sigaction.c.
 {
     memcpy(set, handler_set, sizeof handler_set);
 }
References handler_set, and memcpy.
__libc_sigaction()
int __libc_sigaction (int sig, const struct sigaction *restrict sa, struct sigaction *restrict old)
Definition at line 20 of file sigaction.c.
 {
     struct k_sigaction ksa, ksa_old;
     if (sa) {
         if ((uintptr_t)sa->sa_handler > 1UL) {
             a_or_l(handler_set+(sig-1)/(8*sizeof(long)),
                 1UL<<(sig-1)%(8*sizeof(long)));
             /* If pthread_create has not yet been called,
              * implementation-internal signals might not
              * yet have been unblocked. They must be
              * unblocked before any signal handler is
              * installed, so that an application cannot
              * receive an illegal sigset_t (with them
              * blocked) as part of the ucontext_t passed
              * to the signal handler. */
             if (!libc.threaded && !unmask_done) {
                 __syscall(SYS_rt_sigprocmask, SIG_UNBLOCK,
                     SIGPT_SET, 0, _NSIG/8);
                 unmask_done = 1;
             }
             if (!(sa->sa_flags & SA_RESTART)) {
                 a_store(&__eintr_valid_flag, 1);
             }
         }
         ksa.handler = sa->sa_handler;
         ksa.flags = sa->sa_flags;
 #ifdef SA_RESTORER
         ksa.flags |= SA_RESTORER;
         ksa.restorer = (sa->sa_flags & SA_SIGINFO) ? __restore_rt : __restore;
 #endif
         memcpy(&ksa.mask, &sa->sa_mask, _NSIG/8);
     }
     int r = __syscall(SYS_rt_sigaction, sig, sa?&ksa:0, old?&ksa_old:0, _NSIG/8);
     if (old && !r) {
         old->sa_handler = ksa_old.handler;
         old->sa_flags = ksa_old.flags;
         memcpy(&old->sa_mask, &ksa_old.mask, _NSIG/8);
     }
     return __syscall_ret(r);
 }
References __eintr_valid_flag, __restore, __restore_rt, __syscall, __syscall_ret(), _NSIG, a_or_l, a_store, k_sigaction::flags, k_sigaction::handler, handler_set, libc, k_sigaction::mask, memcpy, r, k_sigaction::restorer, SA_RESTART, SA_RESTORER, SA_SIGINFO, SIG_UNBLOCK, SIGPT_SET, and unmask_done.
Referenced by __sigaction().
__sigaction()
int __sigaction (int sig, const struct sigaction *restrict sa, struct sigaction *restrict old)
Definition at line 63 of file sigaction.c.
 {
     unsigned long set[_NSIG/(8*sizeof(long))];
     if (sig-32U < 3 || sig-1U >= _NSIG-1) {
         errno = EINVAL;
         return -1;
     }
     /* Doing anything with the disposition of SIGABRT requires a lock,
      * so that it cannot be changed while abort is terminating the
      * process and so any change made by abort can't be observed. */
     if (sig == SIGABRT) {
         __block_all_sigs(&set);
         LOCK(__abort_lock);
     }
     int r = __libc_sigaction(sig, sa, old);
     if (sig == SIGABRT) {
         UNLOCK(__abort_lock);
         __restore_sigs(&set);
     }
     return r;
 }
References __abort_lock, __block_all_sigs(), __libc_sigaction(), __restore_sigs(), _NSIG, EINVAL, errno, LOCK, r, SIGABRT, and UNLOCK.
weak_alias()
weak_alias (__sigaction , sigaction)
Variable Documentation
__eintr_valid_flag
volatile int __eintr_valid_flag
Definition at line 18 of file sigaction.c.
Referenced by __libc_sigaction(), and __timedwait_cp().
handler_set
unsigned long handler_set[_NSIG/(8 *sizeof(long))] static
Definition at line 11 of file sigaction.c.
Referenced by __get_handler_set(), and __libc_sigaction().
unmask_done
int unmask_done static
Definition at line 10 of file sigaction.c.
Referenced by __libc_sigaction().