Fennix Userspace: Userspace/apps/base/bash/examples/loadables/print.c File Reference
print.c File Reference
#include "bashtypes.h"
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include "bashansi.h"
#include "shell.h"
#include "builtins.h"
#include "stdc.h"
#include "bashgetopt.h"
#include "builtext.h"
#include "common.h"
Macros
#define ISOPTION(s, c) (s[0] == '-' && s[2] == '\0' && s[1] == c)
Functions
int print_builtin ()
static int printargs ()
int print_builtin (WORD_LIST *list)
static int printargs (WORD_LIST *list, FILE *ofp)
Variables
int errno
static FILE * ofp
char * this_command_name
static char * print_doc []
struct builtin print_struct
Macro Definition Documentation
ISOPTION
#define ISOPTION (s, c) (s[0] == '-' && s[2] == '\0' && s[1] == c)
Definition at line 71 of file print.c.
Function Documentation
print_builtin() [1/2]
int print_builtin ()
print_builtin() [2/2]
int print_builtin (WORD_LIST * list)
Definition at line 75 of file print.c.
 {
   int c, r, nflag, raw, ofd, sflag;
   intmax_t lfd;
   char **v, *pfmt, *arg;
   WORD_LIST *l;
   nflag = raw = sflag = 0;
   ofd = 1;
   pfmt = 0;
   reset_internal_getopt ();
   while ((c = internal_getopt (list, "Rnprsu:f:")) != -1)
     {
       switch (c)
     {
     case 'R':
       raw = 2;
       loptend = lcurrent;
       if (loptend && ISOPTION (loptend->word->word, 'n'))
         {
           loptend = loptend->next;
           nflag = 1;
         }
       goto opt_end;
     case 'r':
       raw = 1;
       break;
     case 'n':
       nflag = 1;
       break;
     case 's':
       sflag = 1;
       break;
     case 'p':
       break;    /* NOP */
     case 'u':
       if (all_digits (list_optarg) && legal_number (list_optarg, &lfd) && lfd == (int)lfd)
         ofd = lfd;
       else
         {
           for (l = list; l->next && l->next != lcurrent; l = l->next);
           lcurrent = loptend = l;
           goto opt_end;
         }
       break;
     case 'f':
       pfmt = list_optarg;
       break;
     CASE_HELPOPT;
     default:
       builtin_usage ();
       return (EX_USAGE);
     }
     }
 opt_end:
   list = loptend;
   ofp = (ofd == 1) ? stdout : fdopen (dup (ofd), "w");
   if (pfmt)
     {
       WORD_DESC *w;
       WORD_LIST *nlist;
       w = make_word (pfmt);
       nlist = make_word_list (w, list);
       r = printf_builtin (nlist);
       nlist->next = (WORD_LIST *)NULL;
       dispose_words (nlist);
       return (r);
     }
   if (raw)
     {
       for (l = list; l; l = l->next)
     {
       fprintf (ofp, "%s", l->word->word);
       if (l->next)
         fprintf (ofp, " ");
     }
       if (nflag == 0)
     fprintf (ofp, "\n");
       fflush (ofp);
       return (0);
     }
   r = printargs (list, ofp);
   if (r && nflag == 0)
     fprintf (ofp, "\n");
   if (ofd != 1)
     fclose (ofp);
   return 0;
 }
References all_digits(), builtin_usage(), c, CASE_HELPOPT, dispose_words(), dup(), EX_USAGE, fclose(), fdopen(), fflush(), fprintf(), internal_getopt(), ISOPTION, lcurrent, legal_number(), list_optarg, loptend, make_word(), make_word_list(), word_list::next, NULL, ofp, opt_end, printargs(), r, reset_internal_getopt(), stdout, word_desc::word, and word_list::word.
printargs() [1/2]
static int printargs () static
Referenced by print_builtin().
printargs() [2/2]
static int printargs (WORD_LIST * list, FILE * ofp) static
Definition at line 173 of file print.c.
 {
   WORD_LIST *l;
   char *ostr;
   int sawc;
   for (sawc = 0, l = list; l; l = l->next)
     {
       ostr = ansicstr (l->word->word, strlen (l->word->word), 0, &sawc, (int *)0);
       if (ostr)
     fprintf (ofp, "%s", ostr);
       free (ostr);
       if (sawc)
         return (0);
       if (l->next)
         fprintf (ofp, " ");
     }
   return (1);
 }
References ansicstr(), fprintf(), free, word_list::next, ofp, strlen(), word_desc::word, and word_list::word.
Variable Documentation
errno
int errno extern
ofp
FILE* ofp static
Definition at line 48 of file print.c.
Referenced by print_builtin(), and printargs().
print_doc
char* print_doc[] static
Initial value:
= {
  "Display arguments.",
  "",
  "Output the arguments.  The -f option means to use the argument as a",
  "format string as would be supplied to printf(1).  The rest of the",
  "options are as in ksh.",
  (char *)NULL
}
Definition at line 52 of file print.c.
print_struct
struct builtin print_struct
Initial value:
= {
    "print",
    print_builtin,
    BUILTIN_ENABLED,
    print_doc,
    "print [-Rnprs] [-u unit] [-f format] [arguments]",
    (char *)0
}
Definition at line 52 of file print.c.
this_command_name
char* this_command_name extern
Definition at line 204 of file execute_cmd.c.