Fennix Userspace: Userspace/apps/base/busybox/networking/nameif.c File Reference
nameif.c File Reference
#include "libbb.h"
#include <syslog.h>
#include <net/if.h>
#include <netinet/ether.h>
#include <linux/sockios.h>
Data Structures
struct ethtable_s
Macros
#define IFNAMSIZ 16
#define SIOCSIFNAME 0x8923 /* set interface name */
#define ETH_ALEN 6
#define ifr_newname ifr_ifru.ifru_slave
Typedefs
typedef struct ethtable_s ethtable_t
Functions
static void nameif_parse_selector (ethtable_t *ch, char *selector)
static void prepend_new_eth_table (ethtable_t **clist, char *ifname, char *selector)
void delete_eth_table (ethtable_t *ch)
int nameif_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
ethtable_s
struct ethtable_s
Definition at line 94 of file nameif.c.
Data Fields
char * ifname
struct ether_addr * mac
struct ethtable_s * next
struct ethtable_s * prev
Macro Definition Documentation
ETH_ALEN
#define ETH_ALEN 6
Definition at line 88 of file nameif.c.
IFNAMSIZ
#define IFNAMSIZ 16
Definition at line 81 of file nameif.c.
ifr_newname
#define ifr_newname ifr_ifru.ifru_slave
Definition at line 91 of file nameif.c.
SIOCSIFNAME
#define SIOCSIFNAME 0x8923 /* set interface name */
Definition at line 85 of file nameif.c.
Typedef Documentation
ethtable_t
typedef struct ethtable_s ethtable_t
Function Documentation
delete_eth_table()
void delete_eth_table (ethtable_t * ch)
Referenced by nameif_main().
nameif_main()
int nameif_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 221 of file nameif.c.
 {
     ethtable_t *clist = NULL;
     const char *fname = "/etc/mactab";
     int ctl_sk;
     ethtable_t *ch;
     parser_t *parser;
     char *token[2];
     if (1 & getopt32(argv, "sc:", &fname)) {
         openlog(applet_name, 0, LOG_LOCAL0);
         /* Why not just "="? I assume logging to stderr
          * can't hurt. 2>/dev/null if you don't like it: */
         logmode |= LOGMODE_SYSLOG;
     }
     argv += optind;
     if (argv[0]) {
         do {
             if (!argv[1])
                 bb_show_usage();
             prepend_new_eth_table(&clist, argv[0], argv[1]);
             argv += 2;
         } while (*argv);
     } else {
         parser = config_open(fname);
         while (config_read(parser, token, 2, 2, "# \t", PARSE_NORMAL))
             prepend_new_eth_table(&clist, token[0], token[1]);
         config_close(parser);
     }
     ctl_sk = xsocket(PF_INET, SOCK_DGRAM, 0);
     parser = config_open2("/proc/net/dev", xfopen_for_read);
     while (clist && config_read(parser, token, 2, 2, "\0: \t", PARSE_NORMAL)) {
         struct ifreq ifr;
 #if  ENABLE_FEATURE_NAMEIF_EXTENDED
         struct ethtool_drvinfo drvinfo;
         struct ethtool_cmd eth_settings;
 #endif
         if (parser->lineno <= 2)
             continue; /* Skip the first two lines */
         /* Find the current interface name and copy it to ifr.ifr_name */
         memset(&ifr, 0, sizeof(struct ifreq));
         strncpy_IFNAMSIZ(ifr.ifr_name, token[0]);
 #if ENABLE_FEATURE_NAMEIF_EXTENDED
         /* Check for phy address */
         memset(&eth_settings, 0, sizeof(eth_settings));
         eth_settings.cmd = ETHTOOL_GSET;
         ifr.ifr_data = (caddr_t) &eth_settings;
         ioctl(ctl_sk, SIOCETHTOOL, &ifr);
         /* Check for driver etc. */
         memset(&drvinfo, 0, sizeof(drvinfo));
         drvinfo.cmd = ETHTOOL_GDRVINFO;
         ifr.ifr_data = (caddr_t) &drvinfo;
         /* Get driver and businfo first, so we have it in drvinfo */
         ioctl(ctl_sk, SIOCETHTOOL, &ifr);
 #endif
         ioctl(ctl_sk, SIOCGIFHWADDR, &ifr);
         /* Search the list for a matching device */
         for (ch = clist; ch; ch = ch->next) {
 #if ENABLE_FEATURE_NAMEIF_EXTENDED
             if (ch->bus_info && strcmp(ch->bus_info, drvinfo.bus_info) != 0)
                 continue;
             if (ch->driver && strcmp(ch->driver, drvinfo.driver) != 0)
                 continue;
             if (ch->phy_address != -1 && ch->phy_address != eth_settings.phy_address)
                 continue;
 #endif
             if (ch->mac && memcmp(ch->mac, ifr.ifr_hwaddr.sa_data, ETH_ALEN) != 0)
                 continue;
             /* if we came here, all selectors have matched */
             goto found;
         }
         /* Nothing found for current interface */
         continue;
  found:
         if (strcmp(ifr.ifr_name, ch->ifname) != 0) {
             strcpy(ifr.ifr_newname, ch->ifname);
             ioctl_or_perror_and_die(ctl_sk, SIOCSIFNAME, &ifr,
                     "can't change ifname %s to %s",
                     ifr.ifr_name, ch->ifname);
         }
         /* Remove list entry of renamed interface */
         if (ch->prev != NULL)
             ch->prev->next = ch->next;
         else
             clist = ch->next;
         if (ch->next != NULL)
             ch->next->prev = ch->prev;
         if (ENABLE_FEATURE_CLEAN_UP)
             delete_eth_table(ch);
     } /* while */
     if (ENABLE_FEATURE_CLEAN_UP) {
         ethtable_t *next;
         for (ch = clist; ch; ch = next) {
             next = ch->next;
             delete_eth_table(ch);
         }
         config_close(parser);
     };
     return 0;
 }
References applet_name, argv, bb_show_usage(), config_close(), config_open(), config_open2(), config_read, delete_eth_table(), ETH_ALEN, fname, found, getopt32(), ethtable_s::ifname, ifr, ioctl(), ioctl_or_perror_and_die(), LOG_LOCAL0, logmode, LOGMODE_SYSLOG, ethtable_s::mac, memcmp(), memset(), ethtable_s::next, next, NULL, openlog(), optind, PARSE_NORMAL, parser, PF_INET, prepend_new_eth_table(), ethtable_s::prev, SIOCGIFHWADDR, SIOCSIFNAME, SOCK_DGRAM, strcmp, strcpy(), strncpy_IFNAMSIZ(), xfopen_for_read(), and xsocket().
nameif_parse_selector()
static void nameif_parse_selector (ethtable_t * ch, char * selector) static
Definition at line 147 of file nameif.c.
 {
     struct ether_addr *lmac;
 #if ENABLE_FEATURE_NAMEIF_EXTENDED
     int found_selector = 0;
     while (*selector) {
         char *next;
 #endif
         selector = skip_whitespace(selector);
 #if ENABLE_FEATURE_NAMEIF_EXTENDED
         ch->phy_address = -1;
         if (*selector == '\0')
             break;
         /* Search for the end .... */
         next = skip_non_whitespace(selector);
         if (*next)
             *next++ = '\0';
         /* Check for selectors, mac= is assumed */
         if (is_prefixed_with(selector, "bus=")) {
             ch->bus_info = xstrdup(selector + 4);
             found_selector++;
         } else if (is_prefixed_with(selector, "driver=")) {
             ch->driver = xstrdup(selector + 7);
             found_selector++;
         } else if (is_prefixed_with(selector, "phyaddr=")) {
             ch->phy_address = xatoi_positive(selector + 8);
             found_selector++;
         } else {
 #endif
             lmac = xmalloc(ETH_ALEN);
             ch->mac = ether_aton_r(selector + (is_prefixed_with(selector, "mac=") ? 4 : 0), lmac);
             if (ch->mac == NULL)
                 bb_error_msg_and_die("can't parse %s", selector);
 #if  ENABLE_FEATURE_NAMEIF_EXTENDED
             found_selector++;
         };
         selector = next;
     }
     if (found_selector == 0)
         bb_error_msg_and_die("no selectors found for %s", ch->ifname);
 #endif
 }
References bb_error_msg_and_die(), ETH_ALEN, ether_aton_r(), ethtable_s::ifname, is_prefixed_with(), ethtable_s::mac, next, NULL, skip_non_whitespace(), skip_whitespace(), xatoi_positive(), xmalloc, and xstrdup().
Referenced by prepend_new_eth_table().
prepend_new_eth_table()
static void prepend_new_eth_table (ethtable_t ** clist, char * ifname, char * selector) static
Definition at line 191 of file nameif.c.
 {
     ethtable_t *ch;
     if (strlen(ifname) >= IFNAMSIZ)
         bb_error_msg_and_die("interface name '%s' too long", ifname);
     ch = xzalloc(sizeof(*ch));
     ch->ifname = xstrdup(ifname);
     nameif_parse_selector(ch, selector);
     ch->next = *clist;
     if (*clist)
         (*clist)->prev = ch;
     *clist = ch;
 }
References bb_error_msg_and_die(), ethtable_s::ifname, IFNAMSIZ, nameif_parse_selector(), ethtable_s::next, ethtable_s::prev, strlen(), xstrdup(), and xzalloc().
Referenced by nameif_main().