Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/st_stuff.c File Reference
st_stuff.c File Reference
#include <stdio.h>
#include "i_system.h"
#include "i_video.h"
#include "z_zone.h"
#include "m_misc.h"
#include "m_random.h"
#include "w_wad.h"
#include "deh_main.h"
#include "deh_misc.h"
#include "doomdef.h"
#include "doomkeys.h"
#include "g_game.h"
#include "st_stuff.h"
#include "st_lib.h"
#include "r_local.h"
#include "p_local.h"
#include "p_inter.h"
#include "am_map.h"
#include "m_cheat.h"
#include "s_sound.h"
#include "v_video.h"
#include "doomstat.h"
#include "dstrings.h"
#include "sounds.h"
Macros
#define STARTREDPALS 1
#define STARTBONUSPALS 9
#define NUMREDPALS 8
#define NUMBONUSPALS 4
#define RADIATIONPAL 13
#define ST_FACEPROBABILITY 96
#define ST_TOGGLECHAT KEY_ENTER
#define ST_X 0
#define ST_X2 104
#define ST_FX 143
#define ST_FY 169
#define ST_TALLNUMWIDTH (tallnum[0]->width)
#define ST_NUMPAINFACES 5
#define ST_NUMSTRAIGHTFACES 3
#define ST_NUMTURNFACES 2
#define ST_NUMSPECIALFACES 3
#define ST_FACESTRIDE (ST_NUMSTRAIGHTFACES+ST_NUMTURNFACES+ST_NUMSPECIALFACES)
#define ST_NUMEXTRAFACES 2
#define ST_NUMFACES (ST_FACESTRIDE*ST_NUMPAINFACES+ST_NUMEXTRAFACES)
#define ST_TURNOFFSET (ST_NUMSTRAIGHTFACES)
#define ST_OUCHOFFSET (ST_TURNOFFSET + ST_NUMTURNFACES)
#define ST_EVILGRINOFFSET (ST_OUCHOFFSET + 1)
#define ST_RAMPAGEOFFSET (ST_EVILGRINOFFSET + 1)
#define ST_GODFACE (ST_NUMPAINFACES*ST_FACESTRIDE)
#define ST_DEADFACE (ST_GODFACE+1)
#define ST_FACESX 143
#define ST_FACESY 168
#define ST_EVILGRINCOUNT (2*TICRATE)
#define ST_STRAIGHTFACECOUNT (TICRATE/2)
#define ST_TURNCOUNT (1*TICRATE)
#define ST_OUCHCOUNT (1*TICRATE)
#define ST_RAMPAGEDELAY (2*TICRATE)
#define ST_MUCHPAIN 20
#define ST_AMMOWIDTH 3
#define ST_AMMOX 44
#define ST_AMMOY 171
#define ST_HEALTHWIDTH 3
#define ST_HEALTHX 90
#define ST_HEALTHY 171
#define ST_ARMSX 111
#define ST_ARMSY 172
#define ST_ARMSBGX 104
#define ST_ARMSBGY 168
#define ST_ARMSXSPACE 12
#define ST_ARMSYSPACE 10
#define ST_FRAGSX 138
#define ST_FRAGSY 171
#define ST_FRAGSWIDTH 2
#define ST_ARMORWIDTH 3
#define ST_ARMORX 221
#define ST_ARMORY 171
#define ST_KEY0WIDTH 8
#define ST_KEY0HEIGHT 5
#define ST_KEY0X 239
#define ST_KEY0Y 171
#define ST_KEY1WIDTH ST_KEY0WIDTH
#define ST_KEY1X 239
#define ST_KEY1Y 181
#define ST_KEY2WIDTH ST_KEY0WIDTH
#define ST_KEY2X 239
#define ST_KEY2Y 191
#define ST_AMMO0WIDTH 3
#define ST_AMMO0HEIGHT 6
#define ST_AMMO0X 288
#define ST_AMMO0Y 173
#define ST_AMMO1WIDTH ST_AMMO0WIDTH
#define ST_AMMO1X 288
#define ST_AMMO1Y 179
#define ST_AMMO2WIDTH ST_AMMO0WIDTH
#define ST_AMMO2X 288
#define ST_AMMO2Y 191
#define ST_AMMO3WIDTH ST_AMMO0WIDTH
#define ST_AMMO3X 288
#define ST_AMMO3Y 185
#define ST_MAXAMMO0WIDTH 3
#define ST_MAXAMMO0HEIGHT 5
#define ST_MAXAMMO0X 314
#define ST_MAXAMMO0Y 173
#define ST_MAXAMMO1WIDTH ST_MAXAMMO0WIDTH
#define ST_MAXAMMO1X 314
#define ST_MAXAMMO1Y 179
#define ST_MAXAMMO2WIDTH ST_MAXAMMO0WIDTH
#define ST_MAXAMMO2X 314
#define ST_MAXAMMO2Y 191
#define ST_MAXAMMO3WIDTH ST_MAXAMMO0WIDTH
#define ST_MAXAMMO3X 314
#define ST_MAXAMMO3Y 185
#define ST_WEAPON0X 110
#define ST_WEAPON0Y 172
#define ST_WEAPON1X 122
#define ST_WEAPON1Y 172
#define ST_WEAPON2X 134
#define ST_WEAPON2Y 172
#define ST_WEAPON3X 110
#define ST_WEAPON3Y 181
#define ST_WEAPON4X 122
#define ST_WEAPON4Y 181
#define ST_WEAPON5X 134
#define ST_WEAPON5Y 181
#define ST_WPNSX 109
#define ST_WPNSY 191
#define ST_DETHX 109
#define ST_DETHY 191
#define ST_MSGTEXTX 0
#define ST_MSGTEXTY 0
#define ST_MSGWIDTH 52
#define ST_MSGHEIGHT 1
#define ST_OUTTEXTX 0
#define ST_OUTTEXTY 6
#define ST_OUTWIDTH 52
#define ST_OUTHEIGHT 1
#define ST_MAPTITLEX (SCREENWIDTH - ST_MAPWIDTH * ST_CHATFONTWIDTH)
#define ST_MAPTITLEY 0
#define ST_MAPHEIGHT 1
Typedefs
typedef void(* load_callback_t) (char *lumpname, patch_t **variable)
Functions
void ST_Stop (void)
void ST_refreshBackground (void)
boolean ST_Responder (event_t *ev)
int ST_calcPainOffset (void)
void ST_updateFaceWidget (void)
void ST_updateWidgets (void)
void ST_Ticker (void)
void ST_doPaletteStuff (void)
void ST_drawWidgets (boolean refresh)
void ST_doRefresh (void)
void ST_diffDraw (void)
void ST_Drawer (boolean fullscreen, boolean refresh)
static void ST_loadUnloadGraphics (load_callback_t callback)
static void ST_loadCallback (char *lumpname, patch_t **variable)
void ST_loadGraphics (void)
void ST_loadData (void)
static void ST_unloadCallback (char *lumpname, patch_t **variable)
void ST_unloadGraphics (void)
void ST_unloadData (void)
void ST_initData (void)
void ST_createWidgets (void)
void ST_Start (void)
void ST_Init (void)
Variables
byte * st_backing_screen
static player_t * plyr
static boolean st_firsttime
static int lu_palette
static unsigned int st_clock
static int st_msgcounter =0
static st_chatstateenum_t st_chatstate
static st_stateenum_t st_gamestate
static boolean st_statusbaron
static boolean st_chat
static boolean st_oldchat
static boolean st_cursoron
static boolean st_notdeathmatch
static boolean st_armson
static boolean st_fragson
static patch_t * sbar
static patch_t * tallnum [10]
static patch_t * tallpercent
static patch_t * shortnum [10]
static patch_t * keys [NUMCARDS]
static patch_t * faces [ST_NUMFACES]
static patch_t * faceback
static patch_t * armsbg
static patch_t * arms [6][2]
static st_number_t w_ready
static st_number_t w_frags
static st_percent_t w_health
static st_binicon_t w_armsbg
static st_multicon_t w_arms [6]
static st_multicon_t w_faces
static st_multicon_t w_keyboxes [3]
static st_percent_t w_armor
static st_number_t w_ammo [4]
static st_number_t w_maxammo [4]
static int st_fragscount
static int st_oldhealth = -1
static boolean oldweaponsowned [NUMWEAPONS]
static int st_facecount = 0
static int st_faceindex = 0
static int keyboxes [3]
static int st_randomnumber
cheatseq_t cheat_mus = CHEAT("idmus", 2)
cheatseq_t cheat_god = CHEAT("iddqd", 0)
cheatseq_t cheat_ammo = CHEAT("idkfa", 0)
cheatseq_t cheat_ammonokey = CHEAT("idfa", 0)
cheatseq_t cheat_noclip = CHEAT("idspispopd", 0)
cheatseq_t cheat_commercial_noclip = CHEAT("idclip", 0)
cheatseq_t cheat_powerup [7]
cheatseq_t cheat_choppers = CHEAT("idchoppers", 0)
cheatseq_t cheat_clev = CHEAT("idclev", 2)
cheatseq_t cheat_mypos = CHEAT("idmypos", 0)
static int st_palette = 0
static boolean st_stopped = true
Macro Definition Documentation
NUMBONUSPALS
#define NUMBONUSPALS 4
Definition at line 71 of file st_stuff.c.
NUMREDPALS
#define NUMREDPALS 8
Definition at line 70 of file st_stuff.c.
RADIATIONPAL
#define RADIATIONPAL 13
Definition at line 73 of file st_stuff.c.
ST_AMMO0HEIGHT
#define ST_AMMO0HEIGHT 6
Definition at line 176 of file st_stuff.c.
ST_AMMO0WIDTH
#define ST_AMMO0WIDTH 3
Definition at line 175 of file st_stuff.c.
ST_AMMO0X
#define ST_AMMO0X 288
Definition at line 177 of file st_stuff.c.
ST_AMMO0Y
#define ST_AMMO0Y 173
Definition at line 178 of file st_stuff.c.
ST_AMMO1WIDTH
#define ST_AMMO1WIDTH ST_AMMO0WIDTH
Definition at line 179 of file st_stuff.c.
ST_AMMO1X
#define ST_AMMO1X 288
Definition at line 180 of file st_stuff.c.
ST_AMMO1Y
#define ST_AMMO1Y 179
Definition at line 181 of file st_stuff.c.
ST_AMMO2WIDTH
#define ST_AMMO2WIDTH ST_AMMO0WIDTH
Definition at line 182 of file st_stuff.c.
ST_AMMO2X
#define ST_AMMO2X 288
Definition at line 183 of file st_stuff.c.
ST_AMMO2Y
#define ST_AMMO2Y 191
Definition at line 184 of file st_stuff.c.
ST_AMMO3WIDTH
#define ST_AMMO3WIDTH ST_AMMO0WIDTH
Definition at line 185 of file st_stuff.c.
ST_AMMO3X
#define ST_AMMO3X 288
Definition at line 186 of file st_stuff.c.
ST_AMMO3Y
#define ST_AMMO3Y 185
Definition at line 187 of file st_stuff.c.
ST_AMMOWIDTH
#define ST_AMMOWIDTH 3
Definition at line 135 of file st_stuff.c.
ST_AMMOX
#define ST_AMMOX 44
Definition at line 136 of file st_stuff.c.
ST_AMMOY
#define ST_AMMOY 171
Definition at line 137 of file st_stuff.c.
ST_ARMORWIDTH
#define ST_ARMORWIDTH 3
Definition at line 158 of file st_stuff.c.
ST_ARMORX
#define ST_ARMORX 221
Definition at line 159 of file st_stuff.c.
ST_ARMORY
#define ST_ARMORY 171
Definition at line 160 of file st_stuff.c.
ST_ARMSBGX
#define ST_ARMSBGX 104
Definition at line 147 of file st_stuff.c.
ST_ARMSBGY
#define ST_ARMSBGY 168
Definition at line 148 of file st_stuff.c.
ST_ARMSX
#define ST_ARMSX 111
Definition at line 145 of file st_stuff.c.
ST_ARMSXSPACE
#define ST_ARMSXSPACE 12
Definition at line 149 of file st_stuff.c.
ST_ARMSY
#define ST_ARMSY 172
Definition at line 146 of file st_stuff.c.
ST_ARMSYSPACE
#define ST_ARMSYSPACE 10
Definition at line 150 of file st_stuff.c.
ST_DEADFACE
#define ST_DEADFACE (ST_GODFACE+1)
Definition at line 112 of file st_stuff.c.
ST_DETHX
#define ST_DETHX 109
Definition at line 234 of file st_stuff.c.
ST_DETHY
#define ST_DETHY 191
Definition at line 235 of file st_stuff.c.
ST_EVILGRINCOUNT
#define ST_EVILGRINCOUNT (2*TICRATE)
Definition at line 117 of file st_stuff.c.
ST_EVILGRINOFFSET
#define ST_EVILGRINOFFSET (ST_OUCHOFFSET + 1)
Definition at line 109 of file st_stuff.c.
ST_FACEPROBABILITY
#define ST_FACEPROBABILITY 96
Definition at line 77 of file st_stuff.c.
ST_FACESTRIDE
#define ST_FACESTRIDE (ST_NUMSTRAIGHTFACES+ST_NUMTURNFACES+ST_NUMSPECIALFACES)
Definition at line 99 of file st_stuff.c.
ST_FACESX
#define ST_FACESX 143
Definition at line 114 of file st_stuff.c.
ST_FACESY
#define ST_FACESY 168
Definition at line 115 of file st_stuff.c.
ST_FRAGSWIDTH
#define ST_FRAGSWIDTH 2
Definition at line 155 of file st_stuff.c.
ST_FRAGSX
#define ST_FRAGSX 138
Definition at line 153 of file st_stuff.c.
ST_FRAGSY
#define ST_FRAGSY 171
Definition at line 154 of file st_stuff.c.
ST_FX
#define ST_FX 143
Definition at line 86 of file st_stuff.c.
ST_FY
#define ST_FY 169
Definition at line 87 of file st_stuff.c.
ST_GODFACE
#define ST_GODFACE (ST_NUMPAINFACES*ST_FACESTRIDE)
Definition at line 111 of file st_stuff.c.
ST_HEALTHWIDTH
#define ST_HEALTHWIDTH 3
Definition at line 140 of file st_stuff.c.
ST_HEALTHX
#define ST_HEALTHX 90
Definition at line 141 of file st_stuff.c.
ST_HEALTHY
#define ST_HEALTHY 171
Definition at line 142 of file st_stuff.c.
ST_KEY0HEIGHT
#define ST_KEY0HEIGHT 5
Definition at line 164 of file st_stuff.c.
ST_KEY0WIDTH
#define ST_KEY0WIDTH 8
Definition at line 163 of file st_stuff.c.
ST_KEY0X
#define ST_KEY0X 239
Definition at line 165 of file st_stuff.c.
ST_KEY0Y
#define ST_KEY0Y 171
Definition at line 166 of file st_stuff.c.
ST_KEY1WIDTH
#define ST_KEY1WIDTH ST_KEY0WIDTH
Definition at line 167 of file st_stuff.c.
ST_KEY1X
#define ST_KEY1X 239
Definition at line 168 of file st_stuff.c.
ST_KEY1Y
#define ST_KEY1Y 181
Definition at line 169 of file st_stuff.c.
ST_KEY2WIDTH
#define ST_KEY2WIDTH ST_KEY0WIDTH
Definition at line 170 of file st_stuff.c.
ST_KEY2X
#define ST_KEY2X 239
Definition at line 171 of file st_stuff.c.
ST_KEY2Y
#define ST_KEY2Y 191
Definition at line 172 of file st_stuff.c.
ST_MAPHEIGHT
#define ST_MAPHEIGHT 1
Definition at line 260 of file st_stuff.c.
ST_MAPTITLEX
#define ST_MAPTITLEX (SCREENWIDTH - ST_MAPWIDTH * ST_CHATFONTWIDTH)
Definition at line 256 of file st_stuff.c.
ST_MAPTITLEY
#define ST_MAPTITLEY 0
Definition at line 259 of file st_stuff.c.
ST_MAXAMMO0HEIGHT
#define ST_MAXAMMO0HEIGHT 5
Definition at line 192 of file st_stuff.c.
ST_MAXAMMO0WIDTH
#define ST_MAXAMMO0WIDTH 3
Definition at line 191 of file st_stuff.c.
ST_MAXAMMO0X
#define ST_MAXAMMO0X 314
Definition at line 193 of file st_stuff.c.
ST_MAXAMMO0Y
#define ST_MAXAMMO0Y 173
Definition at line 194 of file st_stuff.c.
ST_MAXAMMO1WIDTH
#define ST_MAXAMMO1WIDTH ST_MAXAMMO0WIDTH
Definition at line 195 of file st_stuff.c.
ST_MAXAMMO1X
#define ST_MAXAMMO1X 314
Definition at line 196 of file st_stuff.c.
ST_MAXAMMO1Y
#define ST_MAXAMMO1Y 179
Definition at line 197 of file st_stuff.c.
ST_MAXAMMO2WIDTH
#define ST_MAXAMMO2WIDTH ST_MAXAMMO0WIDTH
Definition at line 198 of file st_stuff.c.
ST_MAXAMMO2X
#define ST_MAXAMMO2X 314
Definition at line 199 of file st_stuff.c.
ST_MAXAMMO2Y
#define ST_MAXAMMO2Y 191
Definition at line 200 of file st_stuff.c.
ST_MAXAMMO3WIDTH
#define ST_MAXAMMO3WIDTH ST_MAXAMMO0WIDTH
Definition at line 201 of file st_stuff.c.
ST_MAXAMMO3X
#define ST_MAXAMMO3X 314
Definition at line 202 of file st_stuff.c.
ST_MAXAMMO3Y
#define ST_MAXAMMO3Y 185
Definition at line 203 of file st_stuff.c.
ST_MSGHEIGHT
#define ST_MSGHEIGHT 1
Definition at line 246 of file st_stuff.c.
ST_MSGTEXTX
#define ST_MSGTEXTX 0
Definition at line 241 of file st_stuff.c.
ST_MSGTEXTY
#define ST_MSGTEXTY 0
Definition at line 242 of file st_stuff.c.
ST_MSGWIDTH
#define ST_MSGWIDTH 52
Definition at line 244 of file st_stuff.c.
ST_MUCHPAIN
#define ST_MUCHPAIN 20
Definition at line 123 of file st_stuff.c.
ST_NUMEXTRAFACES
#define ST_NUMEXTRAFACES 2
Definition at line 102 of file st_stuff.c.
ST_NUMFACES
#define ST_NUMFACES (ST_FACESTRIDE*ST_NUMPAINFACES+ST_NUMEXTRAFACES)
Definition at line 104 of file st_stuff.c.
ST_NUMPAINFACES
#define ST_NUMPAINFACES 5
Definition at line 94 of file st_stuff.c.
ST_NUMSPECIALFACES
#define ST_NUMSPECIALFACES 3
Definition at line 97 of file st_stuff.c.
ST_NUMSTRAIGHTFACES
#define ST_NUMSTRAIGHTFACES 3
Definition at line 95 of file st_stuff.c.
ST_NUMTURNFACES
#define ST_NUMTURNFACES 2
Definition at line 96 of file st_stuff.c.
ST_OUCHCOUNT
#define ST_OUCHCOUNT (1*TICRATE)
Definition at line 120 of file st_stuff.c.
ST_OUCHOFFSET
#define ST_OUCHOFFSET (ST_TURNOFFSET + ST_NUMTURNFACES)
Definition at line 108 of file st_stuff.c.
ST_OUTHEIGHT
#define ST_OUTHEIGHT 1
Definition at line 254 of file st_stuff.c.
ST_OUTTEXTX
#define ST_OUTTEXTX 0
Definition at line 248 of file st_stuff.c.
ST_OUTTEXTY
#define ST_OUTTEXTY 6
Definition at line 249 of file st_stuff.c.
ST_OUTWIDTH
#define ST_OUTWIDTH 52
Definition at line 252 of file st_stuff.c.
ST_RAMPAGEDELAY
#define ST_RAMPAGEDELAY (2*TICRATE)
Definition at line 121 of file st_stuff.c.
ST_RAMPAGEOFFSET
#define ST_RAMPAGEOFFSET (ST_EVILGRINOFFSET + 1)
Definition at line 110 of file st_stuff.c.
ST_STRAIGHTFACECOUNT
#define ST_STRAIGHTFACECOUNT (TICRATE/2)
Definition at line 118 of file st_stuff.c.
ST_TALLNUMWIDTH
#define ST_TALLNUMWIDTH (tallnum[0]->width)
Definition at line 91 of file st_stuff.c.
ST_TOGGLECHAT
#define ST_TOGGLECHAT KEY_ENTER
Definition at line 80 of file st_stuff.c.
ST_TURNCOUNT
#define ST_TURNCOUNT (1*TICRATE)
Definition at line 119 of file st_stuff.c.
ST_TURNOFFSET
#define ST_TURNOFFSET (ST_NUMSTRAIGHTFACES)
Definition at line 107 of file st_stuff.c.
ST_WEAPON0X
#define ST_WEAPON0X 110
Definition at line 206 of file st_stuff.c.
ST_WEAPON0Y
#define ST_WEAPON0Y 172
Definition at line 207 of file st_stuff.c.
ST_WEAPON1X
#define ST_WEAPON1X 122
Definition at line 210 of file st_stuff.c.
ST_WEAPON1Y
#define ST_WEAPON1Y 172
Definition at line 211 of file st_stuff.c.
ST_WEAPON2X
#define ST_WEAPON2X 134
Definition at line 214 of file st_stuff.c.
ST_WEAPON2Y
#define ST_WEAPON2Y 172
Definition at line 215 of file st_stuff.c.
ST_WEAPON3X
#define ST_WEAPON3X 110
Definition at line 218 of file st_stuff.c.
ST_WEAPON3Y
#define ST_WEAPON3Y 181
Definition at line 219 of file st_stuff.c.
ST_WEAPON4X
#define ST_WEAPON4X 122
Definition at line 222 of file st_stuff.c.
ST_WEAPON4Y
#define ST_WEAPON4Y 181
Definition at line 223 of file st_stuff.c.
ST_WEAPON5X
#define ST_WEAPON5X 134
Definition at line 226 of file st_stuff.c.
ST_WEAPON5Y
#define ST_WEAPON5Y 181
Definition at line 227 of file st_stuff.c.
ST_WPNSX
#define ST_WPNSX 109
Definition at line 230 of file st_stuff.c.
ST_WPNSY
#define ST_WPNSY 191
Definition at line 231 of file st_stuff.c.
ST_X
#define ST_X 0
Definition at line 83 of file st_stuff.c.
ST_X2
#define ST_X2 104
Definition at line 84 of file st_stuff.c.
STARTBONUSPALS
#define STARTBONUSPALS 9
Definition at line 69 of file st_stuff.c.
STARTREDPALS
#define STARTREDPALS 1
Definition at line 68 of file st_stuff.c.
Typedef Documentation
load_callback_t
typedef void(* load_callback_t) (char *lumpname, patch_t **variable)
Definition at line 1071 of file st_stuff.c.
Function Documentation
ST_calcPainOffset()
int ST_calcPainOffset (void)
Definition at line 665 of file st_stuff.c.
 {
     int     health;
     static int  lastcalc;
     static int  oldhealth = -1;
     health = plyr->health > 100 ? 100 : plyr->health;
     if (health != oldhealth)
     {
     lastcalc = ST_FACESTRIDE * (((100 - health) * ST_NUMPAINFACES) / 101);
     oldhealth = health;
     }
     return lastcalc;
 }
References player_s::health, plyr, ST_FACESTRIDE, and ST_NUMPAINFACES.
Referenced by ST_updateFaceWidget().
ST_createWidgets()
void ST_createWidgets (void)
Definition at line 1227 of file st_stuff.c.
 {
     int i;
     // ready weapon ammo
     STlib_initNum(&w_ready,
           ST_AMMOX,
           ST_AMMOY,
           tallnum,
           &plyr->ammo[weaponinfo[plyr->readyweapon].ammo],
           &st_statusbaron,
           ST_AMMOWIDTH );
     // the last weapon type
     w_ready.data = plyr->readyweapon;
     // health percentage
     STlib_initPercent(&w_health,
               ST_HEALTHX,
               ST_HEALTHY,
               tallnum,
               &plyr->health,
               &st_statusbaron,
               tallpercent);
     // arms background
     STlib_initBinIcon(&w_armsbg,
               ST_ARMSBGX,
               ST_ARMSBGY,
               armsbg,
               &st_notdeathmatch,
               &st_statusbaron);
     // weapons owned
     for(i=0;i<6;i++)
     {
     STlib_initMultIcon(&w_arms[i],
                ST_ARMSX+(i%3)*ST_ARMSXSPACE,
                ST_ARMSY+(i/3)*ST_ARMSYSPACE,
                arms[i], (int *) &plyr->weaponowned[i+1],
                &st_armson);
     }
     // frags sum
     STlib_initNum(&w_frags,
           ST_FRAGSX,
           ST_FRAGSY,
           tallnum,
           &st_fragscount,
           &st_fragson,
           ST_FRAGSWIDTH);
     // faces
     STlib_initMultIcon(&w_faces,
                ST_FACESX,
                ST_FACESY,
                faces,
                &st_faceindex,
                &st_statusbaron);
     // armor percentage - should be colored later
     STlib_initPercent(&w_armor,
               ST_ARMORX,
               ST_ARMORY,
               tallnum,
               &plyr->armorpoints,
               &st_statusbaron, tallpercent);
     // keyboxes 0-2
     STlib_initMultIcon(&w_keyboxes[0],
                ST_KEY0X,
                ST_KEY0Y,
                keys,
                &keyboxes[0],
                &st_statusbaron);
     STlib_initMultIcon(&w_keyboxes[1],
                ST_KEY1X,
                ST_KEY1Y,
                keys,
                &keyboxes[1],
                &st_statusbaron);
     STlib_initMultIcon(&w_keyboxes[2],
                ST_KEY2X,
                ST_KEY2Y,
                keys,
                &keyboxes[2],
                &st_statusbaron);
     // ammo count (all four kinds)
     STlib_initNum(&w_ammo[0],
           ST_AMMO0X,
           ST_AMMO0Y,
           shortnum,
           &plyr->ammo[0],
           &st_statusbaron,
           ST_AMMO0WIDTH);
     STlib_initNum(&w_ammo[1],
           ST_AMMO1X,
           ST_AMMO1Y,
           shortnum,
           &plyr->ammo[1],
           &st_statusbaron,
           ST_AMMO1WIDTH);
     STlib_initNum(&w_ammo[2],
           ST_AMMO2X,
           ST_AMMO2Y,
           shortnum,
           &plyr->ammo[2],
           &st_statusbaron,
           ST_AMMO2WIDTH);
     STlib_initNum(&w_ammo[3],
           ST_AMMO3X,
           ST_AMMO3Y,
           shortnum,
           &plyr->ammo[3],
           &st_statusbaron,
           ST_AMMO3WIDTH);
     // max ammo count (all four kinds)
     STlib_initNum(&w_maxammo[0],
           ST_MAXAMMO0X,
           ST_MAXAMMO0Y,
           shortnum,
           &plyr->maxammo[0],
           &st_statusbaron,
           ST_MAXAMMO0WIDTH);
     STlib_initNum(&w_maxammo[1],
           ST_MAXAMMO1X,
           ST_MAXAMMO1Y,
           shortnum,
           &plyr->maxammo[1],
           &st_statusbaron,
           ST_MAXAMMO1WIDTH);
     STlib_initNum(&w_maxammo[2],
           ST_MAXAMMO2X,
           ST_MAXAMMO2Y,
           shortnum,
           &plyr->maxammo[2],
           &st_statusbaron,
           ST_MAXAMMO2WIDTH);
     STlib_initNum(&w_maxammo[3],
           ST_MAXAMMO3X,
           ST_MAXAMMO3Y,
           shortnum,
           &plyr->maxammo[3],
           &st_statusbaron,
           ST_MAXAMMO3WIDTH);
 }
References weaponinfo_t::ammo, player_s::ammo, player_s::armorpoints, arms, armsbg, st_number_t::data, faces, player_s::health, i, keyboxes, keys, player_s::maxammo, plyr, player_s::readyweapon, shortnum, ST_AMMO0WIDTH, ST_AMMO0X, ST_AMMO0Y, ST_AMMO1WIDTH, ST_AMMO1X, ST_AMMO1Y, ST_AMMO2WIDTH, ST_AMMO2X, ST_AMMO2Y, ST_AMMO3WIDTH, ST_AMMO3X, ST_AMMO3Y, ST_AMMOWIDTH, ST_AMMOX, ST_AMMOY, ST_ARMORX, ST_ARMORY, ST_ARMSBGX, ST_ARMSBGY, st_armson, ST_ARMSX, ST_ARMSXSPACE, ST_ARMSY, ST_ARMSYSPACE, st_faceindex, ST_FACESX, ST_FACESY, st_fragscount, st_fragson, ST_FRAGSWIDTH, ST_FRAGSX, ST_FRAGSY, ST_HEALTHX, ST_HEALTHY, ST_KEY0X, ST_KEY0Y, ST_KEY1X, ST_KEY1Y, ST_KEY2X, ST_KEY2Y, ST_MAXAMMO0WIDTH, ST_MAXAMMO0X, ST_MAXAMMO0Y, ST_MAXAMMO1WIDTH, ST_MAXAMMO1X, ST_MAXAMMO1Y, ST_MAXAMMO2WIDTH, ST_MAXAMMO2X, ST_MAXAMMO2Y, ST_MAXAMMO3WIDTH, ST_MAXAMMO3X, ST_MAXAMMO3Y, st_notdeathmatch, st_statusbaron, STlib_initBinIcon(), STlib_initMultIcon(), STlib_initNum(), STlib_initPercent(), tallnum, tallpercent, w_ammo, w_armor, w_arms, w_armsbg, w_faces, w_frags, w_health, w_keyboxes, w_maxammo, w_ready, weaponinfo, and player_s::weaponowned.
Referenced by ST_Start().
ST_diffDraw()
void ST_diffDraw (void)
Definition at line 1049 of file st_stuff.c.
 {
     // update all widgets
     ST_drawWidgets(false);
 }
References ST_drawWidgets().
Referenced by ST_Drawer().
ST_doPaletteStuff()
void ST_doPaletteStuff (void)
Definition at line 936 of file st_stuff.c.
 {
     int     palette;
     byte*   pal;
     int     cnt;
     int     bzc;
     cnt = plyr->damagecount;
     if (plyr->powers[pw_strength])
     {
     // slowly fade the berzerk out
     bzc = 12 - (plyr->powers[pw_strength]>>6);
     if (bzc > cnt)
         cnt = bzc;
     }
     if (cnt)
     {
     palette = (cnt+7)>>3;
     if (palette >= NUMREDPALS)
         palette = NUMREDPALS-1;
     palette += STARTREDPALS;
     }
     else if (plyr->bonuscount)
     {
     palette = (plyr->bonuscount+7)>>3;
     if (palette >= NUMBONUSPALS)
         palette = NUMBONUSPALS-1;
     palette += STARTBONUSPALS;
     }
     else if ( plyr->powers[pw_ironfeet] > 4*32
           || plyr->powers[pw_ironfeet]&8)
     palette = RADIATIONPAL;
     else
     palette = 0;
     // In Chex Quest, the player never sees red.  Instead, the
     // radiation suit palette is used to tint the screen green,
     // as though the player is being covered in goo by an
     // attacking flemoid.
     if (gameversion == exe_chex
      && palette >= STARTREDPALS && palette < STARTREDPALS + NUMREDPALS)
     {
         palette = RADIATIONPAL;
     }
     if (palette != st_palette)
     {
     st_palette = palette;
     pal = (byte *) W_CacheLumpNum (lu_palette, PU_CACHE)+palette*768;
     I_SetPalette (pal);
     }
 }
References player_s::bonuscount, cnt, player_s::damagecount, exe_chex, gameversion, I_SetPalette(), lu_palette, NUMBONUSPALS, NUMREDPALS, plyr, player_s::powers, PU_CACHE, pw_ironfeet, pw_strength, RADIATIONPAL, st_palette, STARTBONUSPALS, STARTREDPALS, and W_CacheLumpNum().
Referenced by ST_Drawer().
ST_doRefresh()
void ST_doRefresh (void)
Definition at line 1036 of file st_stuff.c.
 {
     st_firsttime = false;
     // draw status bar background to off-screen buff
     ST_refreshBackground();
     // and refresh all widgets
     ST_drawWidgets(true);
 }
References ST_drawWidgets(), st_firsttime, and ST_refreshBackground().
Referenced by ST_Drawer().
ST_Drawer()
void ST_Drawer (boolean fullscreen, boolean refresh)
Definition at line 1055 of file st_stuff.c.
 {
     st_statusbaron = (!fullscreen) || automapactive;
     st_firsttime = st_firsttime || refresh;
     // Do red-/gold-shifts from damage/items
     ST_doPaletteStuff();
     // If just after ST_Start(), refresh all
     if (st_firsttime) ST_doRefresh();
     // Otherwise, update as little as possible
     else ST_diffDraw();
 }
References automapactive, fullscreen, ST_diffDraw(), ST_doPaletteStuff(), ST_doRefresh(), st_firsttime, and st_statusbaron.
Referenced by D_Display().
ST_drawWidgets()
void ST_drawWidgets (boolean refresh)
Definition at line 1001 of file st_stuff.c.
 {
     int     i;
     // used by w_arms[] widgets
     st_armson = st_statusbaron && !deathmatch;
     // used by w_frags widget
     st_fragson = deathmatch && st_statusbaron;
     STlib_updateNum(&w_ready, refresh);
     for (i=0;i<4;i++)
     {
     STlib_updateNum(&w_ammo[i], refresh);
     STlib_updateNum(&w_maxammo[i], refresh);
     }
     STlib_updatePercent(&w_health, refresh);
     STlib_updatePercent(&w_armor, refresh);
     STlib_updateBinIcon(&w_armsbg, refresh);
     for (i=0;i<6;i++)
     STlib_updateMultIcon(&w_arms[i], refresh);
     STlib_updateMultIcon(&w_faces, refresh);
     for (i=0;i<3;i++)
     STlib_updateMultIcon(&w_keyboxes[i], refresh);
     STlib_updateNum(&w_frags, refresh);
 }
References deathmatch, i, st_armson, st_fragson, st_statusbaron, STlib_updateBinIcon(), STlib_updateMultIcon(), STlib_updateNum(), STlib_updatePercent(), w_ammo, w_armor, w_arms, w_armsbg, w_faces, w_frags, w_health, w_keyboxes, w_maxammo, and w_ready.
Referenced by ST_diffDraw(), and ST_doRefresh().
ST_Init()
void ST_Init (void)
Definition at line 1411 of file st_stuff.c.
 {
     ST_loadData();
     st_backing_screen = (byte *) Z_Malloc(ST_WIDTH * ST_HEIGHT, PU_STATIC, 0);
 }
References PU_STATIC, st_backing_screen, ST_HEIGHT, ST_loadData(), ST_WIDTH, and Z_Malloc().
Referenced by D_DoomMain().
ST_initData()
void ST_initData (void)
Definition at line 1194 of file st_stuff.c.
 {
     int     i;
     st_firsttime = true;
     plyr = &players[consoleplayer];
     st_clock = 0;
     st_chatstate = StartChatState;
     st_gamestate = FirstPersonState;
     st_statusbaron = true;
     st_oldchat = st_chat = false;
     st_cursoron = false;
     st_faceindex = 0;
     st_palette = -1;
     st_oldhealth = -1;
     for (i=0;i<NUMWEAPONS;i++)
     oldweaponsowned[i] = plyr->weaponowned[i];
     for (i=0;i<3;i++)
     keyboxes[i] = -1;
     STlib_init();
 }
References consoleplayer, FirstPersonState, for(), i, keyboxes, NUMWEAPONS, oldweaponsowned, players, plyr, st_chat, st_chatstate, st_clock, st_cursoron, st_faceindex, st_firsttime, st_gamestate, st_oldchat, st_oldhealth, st_palette, st_statusbaron, StartChatState, STlib_init(), and player_s::weaponowned.
Referenced by ST_Start().
ST_loadCallback()
static void ST_loadCallback (char * lumpname, patch_t ** variable) static
Definition at line 1162 of file st_stuff.c.
 {
     *variable = W_CacheLumpName(lumpname, PU_STATIC);
 }
References PU_STATIC, variable, and W_CacheLumpName().
Referenced by ST_loadGraphics().
ST_loadData()
void ST_loadData (void)
Definition at line 1172 of file st_stuff.c.
 {
     lu_palette = W_GetNumForName (DEH_String("PLAYPAL"));
     ST_loadGraphics();
 }
References DEH_String, lu_palette, ST_loadGraphics(), and W_GetNumForName().
Referenced by ST_Init().
ST_loadGraphics()
void ST_loadGraphics (void)
Definition at line 1167 of file st_stuff.c.
 {
     ST_loadUnloadGraphics(ST_loadCallback);
 }
References ST_loadCallback(), and ST_loadUnloadGraphics().
Referenced by ST_loadData().
ST_loadUnloadGraphics()
static void ST_loadUnloadGraphics (load_callback_t callback) static
Definition at line 1076 of file st_stuff.c.
 {
     int     i;
     int     j;
     int     facenum;
     char    namebuf[9];
     // Load the numbers, tall and short
     for (i=0;i<10;i++)
     {
     DEH_snprintf(namebuf, 9, "STTNUM%d", i);
         callback(namebuf, &tallnum[i]);
     DEH_snprintf(namebuf, 9, "STYSNUM%d", i);
         callback(namebuf, &shortnum[i]);
     }
     // Load percent key.
     //Note: why not load STMINUS here, too?
     callback(DEH_String("STTPRCNT"), &tallpercent);
     // key cards
     for (i=0;i<NUMCARDS;i++)
     {
         DEH_snprintf(namebuf, 9, "STKEYS%d", i);
         callback(namebuf, &keys[i]);
     }
     // arms background
     callback(DEH_String("STARMS"), &armsbg);
     // arms ownership widgets
     for (i=0; i<6; i++)
     {
         DEH_snprintf(namebuf, 9, "STGNUM%d", i+2);
         // gray #
         callback(namebuf, &arms[i][0]);
         // yellow #
         arms[i][1] = shortnum[i+2];
     }
     // face backgrounds for different color players
     DEH_snprintf(namebuf, 9, "STFB%d", consoleplayer);
     callback(namebuf, &faceback);
     // status bar background bits
     callback(DEH_String("STBAR"), &sbar);
     // face states
     facenum = 0;
     for (i=0; i<ST_NUMPAINFACES; i++)
     {
     for (j=0; j<ST_NUMSTRAIGHTFACES; j++)
     {
         DEH_snprintf(namebuf, 9, "STFST%d%d", i, j);
             callback(namebuf, &faces[facenum]);
             ++facenum;
     }
     DEH_snprintf(namebuf, 9, "STFTR%d0", i);    // turn right
         callback(namebuf, &faces[facenum]);
         ++facenum;
     DEH_snprintf(namebuf, 9, "STFTL%d0", i);    // turn left
         callback(namebuf, &faces[facenum]);
         ++facenum;
     DEH_snprintf(namebuf, 9, "STFOUCH%d", i);   // ouch!
         callback(namebuf, &faces[facenum]);
         ++facenum;
     DEH_snprintf(namebuf, 9, "STFEVL%d", i);    // evil grin ;)
         callback(namebuf, &faces[facenum]);
         ++facenum;
     DEH_snprintf(namebuf, 9, "STFKILL%d", i);   // pissed off
         callback(namebuf, &faces[facenum]);
         ++facenum;
     }
     callback(DEH_String("STFGOD0"), &faces[facenum]);
     ++facenum;
     callback(DEH_String("STFDEAD0"), &faces[facenum]);
     ++facenum;
 }
References arms, armsbg, callback(), consoleplayer, DEH_snprintf, DEH_String, faceback, faces, i, j, keys, NUMCARDS, sbar, shortnum, ST_NUMPAINFACES, ST_NUMSTRAIGHTFACES, tallnum, and tallpercent.
Referenced by ST_loadGraphics(), and ST_unloadGraphics().
ST_refreshBackground()
void ST_refreshBackground (void)
Definition at line 416 of file st_stuff.c.
 {
     if (st_statusbaron)
     {
         V_UseBuffer(st_backing_screen);
     V_DrawPatch(ST_X, 0, sbar);
     if (netgame)
         V_DrawPatch(ST_FX, 0, faceback);
         V_RestoreBuffer();
     V_CopyRect(ST_X, 0, st_backing_screen, ST_WIDTH, ST_HEIGHT, ST_X, ST_Y);
     }
 }
References faceback, netgame, sbar, st_backing_screen, ST_FX, ST_HEIGHT, st_statusbaron, ST_WIDTH, ST_X, ST_Y, V_CopyRect(), V_DrawPatch(), V_RestoreBuffer(), and V_UseBuffer().
Referenced by ST_doRefresh().
ST_Responder()
boolean ST_Responder (event_t * ev)
Definition at line 439 of file st_stuff.c.
 {
   int       i;
   // Filter automap on/off.
   if (ev->type == ev_keyup
       && ((ev->data1 & 0xffff0000) == AM_MSGHEADER))
   {
     switch(ev->data1)
     {
       case AM_MSGENTERED:
     st_gamestate = AutomapState;
     st_firsttime = true;
     break;
       case AM_MSGEXITED:
     //  fprintf(stderr, "AM exited\n");
     st_gamestate = FirstPersonState;
     break;
     }
   }
   // if a user keypress...
   else if (ev->type == ev_keydown)
   {
     if (!netgame && gameskill != sk_nightmare)
     {
       // 'dqd' cheat for toggleable god mode
       if (cht_CheckCheat(&cheat_god, ev->data2))
       {
     plyr->cheats ^= CF_GODMODE;
     if (plyr->cheats & CF_GODMODE)
     {
       if (plyr->mo)
         plyr->mo->health = 100;
       plyr->health = deh_god_mode_health;
       plyr->message = DEH_String(STSTR_DQDON);
     }
     else
       plyr->message = DEH_String(STSTR_DQDOFF);
       }
       // 'fa' cheat for killer fucking arsenal
       else if (cht_CheckCheat(&cheat_ammonokey, ev->data2))
       {
     plyr->armorpoints = deh_idfa_armor;
     plyr->armortype = deh_idfa_armor_class;
     for (i=0;i<NUMWEAPONS;i++)
       plyr->weaponowned[i] = true;
     for (i=0;i<NUMAMMO;i++)
       plyr->ammo[i] = plyr->maxammo[i];
     plyr->message = DEH_String(STSTR_FAADDED);
       }
       // 'kfa' cheat for key full ammo
       else if (cht_CheckCheat(&cheat_ammo, ev->data2))
       {
     plyr->armorpoints = deh_idkfa_armor;
     plyr->armortype = deh_idkfa_armor_class;
     for (i=0;i<NUMWEAPONS;i++)
       plyr->weaponowned[i] = true;
     for (i=0;i<NUMAMMO;i++)
       plyr->ammo[i] = plyr->maxammo[i];
     for (i=0;i<NUMCARDS;i++)
       plyr->cards[i] = true;
     plyr->message = DEH_String(STSTR_KFAADDED);
       }
       // 'mus' cheat for changing music
       else if (cht_CheckCheat(&cheat_mus, ev->data2))
       {
     char    buf[3];
     int     musnum;
     plyr->message = DEH_String(STSTR_MUS);
     cht_GetParam(&cheat_mus, buf);
         // Note: The original v1.9 had a bug that tried to play back
         // the Doom II music regardless of gamemode.  This was fixed
         // in the Ultimate Doom executable so that it would work for
         // the Doom 1 music as well.
     if (gamemode == commercial || gameversion < exe_ultimate)
     {
       musnum = mus_runnin + (buf[0]-'0')*10 + buf[1]-'0' - 1;
       if (((buf[0]-'0')*10 + buf[1]-'0') > 35)
         plyr->message = DEH_String(STSTR_NOMUS);
       else
         S_ChangeMusic(musnum, 1);
     }
     else
     {
       musnum = mus_e1m1 + (buf[0]-'1')*9 + (buf[1]-'1');
       if (((buf[0]-'1')*9 + buf[1]-'1') > 31)
         plyr->message = DEH_String(STSTR_NOMUS);
       else
         S_ChangeMusic(musnum, 1);
     }
       }
       else if ( (logical_gamemission == doom
                  && cht_CheckCheat(&cheat_noclip, ev->data2))
              || (logical_gamemission != doom
                  && cht_CheckCheat(&cheat_commercial_noclip,ev->data2)))
       {
         // Noclip cheat.
         // For Doom 1, use the idspipsopd cheat; for all others, use
         // idclip
     plyr->cheats ^= CF_NOCLIP;
     if (plyr->cheats & CF_NOCLIP)
       plyr->message = DEH_String(STSTR_NCON);
     else
       plyr->message = DEH_String(STSTR_NCOFF);
       }
       // 'behold?' power-up cheats
       for (i=0;i<6;i++)
       {
     if (cht_CheckCheat(&cheat_powerup[i], ev->data2))
     {
       if (!plyr->powers[i])
         P_GivePower( plyr, i);
       else if (i!=pw_strength)
         plyr->powers[i] = 1;
       else
         plyr->powers[i] = 0;
       plyr->message = DEH_String(STSTR_BEHOLDX);
     }
       }
       // 'behold' power-up menu
       if (cht_CheckCheat(&cheat_powerup[6], ev->data2))
       {
     plyr->message = DEH_String(STSTR_BEHOLD);
       }
       // 'choppers' invulnerability & chainsaw
       else if (cht_CheckCheat(&cheat_choppers, ev->data2))
       {
     plyr->weaponowned[wp_chainsaw] = true;
     plyr->powers[pw_invulnerability] = true;
     plyr->message = DEH_String(STSTR_CHOPPERS);
       }
       // 'mypos' for player position
       else if (cht_CheckCheat(&cheat_mypos, ev->data2))
       {
         static char buf[ST_MSGWIDTH];
         M_snprintf(buf, sizeof(buf), "ang=0x%x;x,y=(0x%x,0x%x)",
                    players[consoleplayer].mo->angle,
                    players[consoleplayer].mo->x,
                    players[consoleplayer].mo->y);
         plyr->message = buf;
       }
     }
     // 'clev' change-level cheat
     if (!netgame && cht_CheckCheat(&cheat_clev, ev->data2))
     {
       char      buf[3];
       int       epsd;
       int       map;
       cht_GetParam(&cheat_clev, buf);
       if (gamemode == commercial)
       {
     epsd = 1;
     map = (buf[0] - '0')*10 + buf[1] - '0';
       }
       else
       {
     epsd = buf[0] - '0';
     map = buf[1] - '0';
       }
       // Chex.exe always warps to episode 1.
       if (gameversion == exe_chex)
       {
         epsd = 1;
       }
       // Catch invalid maps.
       if (epsd < 1)
     return false;
       if (map < 1)
     return false;
       // Ohmygod - this is not going to work.
       if ((gamemode == retail)
       && ((epsd > 4) || (map > 9)))
     return false;
       if ((gamemode == registered)
       && ((epsd > 3) || (map > 9)))
     return false;
       if ((gamemode == shareware)
       && ((epsd > 1) || (map > 9)))
     return false;
       // The source release has this check as map > 34. However, Vanilla
       // Doom allows IDCLEV up to MAP40 even though it normally crashes.
       if ((gamemode == commercial)
     && (( epsd > 1) || (map > 40)))
     return false;
       // So be it.
       plyr->message = DEH_String(STSTR_CLEV);
       G_DeferedInitNew(gameskill, epsd, map);
     }
   }
   return false;
 }
References AM_MSGENTERED, AM_MSGEXITED, AM_MSGHEADER, player_s::ammo, player_s::armorpoints, player_s::armortype, AutomapState, buf, player_s::cards, CF_GODMODE, CF_NOCLIP, cheat_ammo, cheat_ammonokey, cheat_choppers, cheat_clev, cheat_commercial_noclip, cheat_god, cheat_mus, cheat_mypos, cheat_noclip, cheat_powerup, player_s::cheats, cht_CheckCheat(), cht_GetParam(), commercial, consoleplayer, event_t::data1, event_t::data2, deh_god_mode_health, deh_idfa_armor, deh_idfa_armor_class, deh_idkfa_armor, deh_idkfa_armor_class, DEH_String, doom, ev_keydown, ev_keyup, exe_chex, exe_ultimate, FirstPersonState, for(), G_DeferedInitNew(), gamemode, gameskill, gameversion, player_s::health, mobj_s::health, i, logical_gamemission, M_snprintf(), player_s::maxammo, player_s::message, player_s::mo, mus_e1m1, mus_runnin, netgame, NUMAMMO, NUMCARDS, NUMWEAPONS, P_GivePower(), players, plyr, player_s::powers, pw_invulnerability, pw_strength, registered, retail, S_ChangeMusic(), shareware, sk_nightmare, st_firsttime, st_gamestate, ST_MSGWIDTH, STSTR_BEHOLD, STSTR_BEHOLDX, STSTR_CHOPPERS, STSTR_CLEV, STSTR_DQDOFF, STSTR_DQDON, STSTR_FAADDED, STSTR_KFAADDED, STSTR_MUS, STSTR_NCOFF, STSTR_NCON, STSTR_NOMUS, event_t::type, player_s::weaponowned, wp_chainsaw, mobj_s::x, and mobj_s::y.
Referenced by AM_initVariables(), AM_Stop(), and G_Responder().
ST_Start()
void ST_Start (void)
Definition at line 1389 of file st_stuff.c.
 {
     if (!st_stopped)
     ST_Stop();
     ST_initData();
     ST_createWidgets();
     st_stopped = false;
 }
References ST_createWidgets(), ST_initData(), ST_Stop(), and st_stopped.
Referenced by P_SpawnPlayer().
ST_Stop()
void ST_Stop (void)
Definition at line 1401 of file st_stuff.c.
 {
     if (st_stopped)
     return;
     I_SetPalette (W_CacheLumpNum (lu_palette, PU_CACHE));
     st_stopped = true;
 }
References I_SetPalette(), lu_palette, PU_CACHE, st_stopped, and W_CacheLumpNum().
Referenced by ST_Start().
ST_Ticker()
void ST_Ticker (void)
Definition at line 924 of file st_stuff.c.
 {
     st_clock++;
     st_randomnumber = M_Random();
     ST_updateWidgets();
     st_oldhealth = plyr->health;
 }
References player_s::health, M_Random(), plyr, st_clock, st_oldhealth, st_randomnumber, and ST_updateWidgets().
Referenced by G_Ticker().
ST_unloadCallback()
static void ST_unloadCallback (char * lumpname, patch_t ** variable) static
Definition at line 1178 of file st_stuff.c.
 {
     W_ReleaseLumpName(lumpname);
     *variable = NULL;
 }
References NULL, variable, and W_ReleaseLumpName().
Referenced by ST_unloadGraphics().
ST_unloadData()
void ST_unloadData (void)
Definition at line 1189 of file st_stuff.c.
 {
     ST_unloadGraphics();
 }
References ST_unloadGraphics().
ST_unloadGraphics()
void ST_unloadGraphics (void)
Definition at line 1184 of file st_stuff.c.
 {
     ST_loadUnloadGraphics(ST_unloadCallback);
 }
References ST_loadUnloadGraphics(), and ST_unloadCallback().
Referenced by ST_unloadData().
ST_updateFaceWidget()
void ST_updateFaceWidget (void)
Definition at line 688 of file st_stuff.c.
 {
     int     i;
     angle_t badguyangle;
     angle_t diffang;
     static int  lastattackdown = -1;
     static int  priority = 0;
     boolean doevilgrin;
     if (priority < 10)
     {
     // dead
     if (!plyr->health)
     {
         priority = 9;
         st_faceindex = ST_DEADFACE;
         st_facecount = 1;
     }
     }
     if (priority < 9)
     {
     if (plyr->bonuscount)
     {
         // picking up bonus
         doevilgrin = false;
         for (i=0;i<NUMWEAPONS;i++)
         {
         if (oldweaponsowned[i] != plyr->weaponowned[i])
         {
             doevilgrin = true;
             oldweaponsowned[i] = plyr->weaponowned[i];
         }
         }
         if (doevilgrin)
         {
         // evil grin if just picked up weapon
         priority = 8;
         st_facecount = ST_EVILGRINCOUNT;
         st_faceindex = ST_calcPainOffset() + ST_EVILGRINOFFSET;
         }
     }
     }
     if (priority < 8)
     {
     if (plyr->damagecount
         && plyr->attacker
         && plyr->attacker != plyr->mo)
     {
         // being attacked
         priority = 7;
         if (plyr->health - st_oldhealth > ST_MUCHPAIN)
         {
         st_facecount = ST_TURNCOUNT;
         st_faceindex = ST_calcPainOffset() + ST_OUCHOFFSET;
         }
         else
         {
         badguyangle = R_PointToAngle2(plyr->mo->x,
                           plyr->mo->y,
                           plyr->attacker->x,
                           plyr->attacker->y);
         if (badguyangle > plyr->mo->angle)
         {
             // whether right or left
             diffang = badguyangle - plyr->mo->angle;
             i = diffang > ANG180;
         }
         else
         {
             // whether left or right
             diffang = plyr->mo->angle - badguyangle;
             i = diffang <= ANG180;
         } // confusing, aint it?
         st_facecount = ST_TURNCOUNT;
         st_faceindex = ST_calcPainOffset();
         if (diffang < ANG45)
         {
             // head-on
             st_faceindex += ST_RAMPAGEOFFSET;
         }
         else if (i)
         {
             // turn face right
             st_faceindex += ST_TURNOFFSET;
         }
         else
         {
             // turn face left
             st_faceindex += ST_TURNOFFSET+1;
         }
         }
     }
     }
     if (priority < 7)
     {
     // getting hurt because of your own damn stupidity
     if (plyr->damagecount)
     {
         if (plyr->health - st_oldhealth > ST_MUCHPAIN)
         {
         priority = 7;
         st_facecount = ST_TURNCOUNT;
         st_faceindex = ST_calcPainOffset() + ST_OUCHOFFSET;
         }
         else
         {
         priority = 6;
         st_facecount = ST_TURNCOUNT;
         st_faceindex = ST_calcPainOffset() + ST_RAMPAGEOFFSET;
         }
     }
     }
     if (priority < 6)
     {
     // rapid firing
     if (plyr->attackdown)
     {
         if (lastattackdown==-1)
         lastattackdown = ST_RAMPAGEDELAY;
         else if (!--lastattackdown)
         {
         priority = 5;
         st_faceindex = ST_calcPainOffset() + ST_RAMPAGEOFFSET;
         st_facecount = 1;
         lastattackdown = 1;
         }
     }
     else
         lastattackdown = -1;
     }
     if (priority < 5)
     {
     // invulnerability
     if ((plyr->cheats & CF_GODMODE)
         || plyr->powers[pw_invulnerability])
     {
         priority = 4;
         st_faceindex = ST_GODFACE;
         st_facecount = 1;
     }
     }
     // look left or look right if the facecount has timed out
     if (!st_facecount)
     {
     st_faceindex = ST_calcPainOffset() + (st_randomnumber % 3);
     st_facecount = ST_STRAIGHTFACECOUNT;
     priority = 0;
     }
     st_facecount--;
 }
References ANG180, ANG45, mobj_s::angle, player_s::attackdown, player_s::attacker, player_s::bonuscount, CF_GODMODE, player_s::cheats, player_s::damagecount, player_s::health, i, player_s::mo, NUMWEAPONS, oldweaponsowned, plyr, player_s::powers, pw_invulnerability, R_PointToAngle2(), ST_calcPainOffset(), ST_DEADFACE, ST_EVILGRINCOUNT, ST_EVILGRINOFFSET, st_facecount, st_faceindex, ST_GODFACE, ST_MUCHPAIN, st_oldhealth, ST_OUCHOFFSET, ST_RAMPAGEDELAY, ST_RAMPAGEOFFSET, st_randomnumber, ST_STRAIGHTFACECOUNT, ST_TURNCOUNT, ST_TURNOFFSET, player_s::weaponowned, mobj_s::x, and mobj_s::y.
Referenced by ST_updateWidgets().
ST_updateWidgets()
void ST_updateWidgets (void)
Definition at line 860 of file st_stuff.c.
 {
     static int  largeammo = 1994; // means "n/a"
     int     i;
     // must redirect the pointer if the ready weapon has changed.
     //  if (w_ready.data != plyr->readyweapon)
     //  {
     if (weaponinfo[plyr->readyweapon].ammo == am_noammo)
     w_ready.num = &largeammo;
     else
     w_ready.num = &plyr->ammo[weaponinfo[plyr->readyweapon].ammo];
     //{
     // static int tic=0;
     // static int dir=-1;
     // if (!(tic&15))
     //   plyr->ammo[weaponinfo[plyr->readyweapon].ammo]+=dir;
     // if (plyr->ammo[weaponinfo[plyr->readyweapon].ammo] == -100)
     //   dir = 1;
     // tic++;
     // }
     w_ready.data = plyr->readyweapon;
     // if (*w_ready.on)
     //  STlib_updateNum(&w_ready, true);
     // refresh weapon change
     //  }
     // update keycard multiple widgets
     for (i=0;i<3;i++)
     {
     keyboxes[i] = plyr->cards[i] ? i : -1;
     if (plyr->cards[i+3])
         keyboxes[i] = i+3;
     }
     // refresh everything if this is him coming back to life
     ST_updateFaceWidget();
     // used by the w_armsbg widget
     st_notdeathmatch = !deathmatch;
     // used by w_arms[] widgets
     st_armson = st_statusbaron && !deathmatch;
     // used by w_frags widget
     st_fragson = deathmatch && st_statusbaron;
     st_fragscount = 0;
     for (i=0 ; i<MAXPLAYERS ; i++)
     {
     if (i != consoleplayer)
         st_fragscount += plyr->frags[i];
     else
         st_fragscount -= plyr->frags[i];
     }
     // get rid of chat window if up because of message
     if (!--st_msgcounter)
     st_chat = st_oldchat;
 }
References am_noammo, weaponinfo_t::ammo, player_s::ammo, player_s::cards, consoleplayer, st_number_t::data, deathmatch, player_s::frags, i, keyboxes, MAXPLAYERS, st_number_t::num, plyr, player_s::readyweapon, st_armson, st_chat, st_fragscount, st_fragson, st_msgcounter, st_notdeathmatch, st_oldchat, st_statusbaron, ST_updateFaceWidget(), w_ready, and weaponinfo.
Referenced by ST_Ticker().
Variable Documentation
arms
patch_t* arms[6][2] static
Definition at line 332 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_loadUnloadGraphics().
armsbg
patch_t* armsbg static
Definition at line 329 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_loadUnloadGraphics().
cheat_ammo
cheatseq_t cheat_ammo = CHEAT("idkfa", 0)
Definition at line 390 of file st_stuff.c.
Referenced by ST_Responder().
cheat_ammonokey
cheatseq_t cheat_ammonokey = CHEAT("idfa", 0)
Definition at line 391 of file st_stuff.c.
Referenced by ST_Responder().
cheat_choppers
cheatseq_t cheat_choppers = CHEAT("idchoppers", 0)
Definition at line 406 of file st_stuff.c.
Referenced by ST_Responder().
cheat_clev
cheatseq_t cheat_clev = CHEAT("idclev", 2)
Definition at line 407 of file st_stuff.c.
Referenced by ST_Responder().
cheat_commercial_noclip
cheatseq_t cheat_commercial_noclip = CHEAT("idclip", 0)
Definition at line 393 of file st_stuff.c.
Referenced by ST_Responder().
cheat_god
cheatseq_t cheat_god = CHEAT("iddqd", 0)
Definition at line 389 of file st_stuff.c.
Referenced by ST_Responder().
cheat_mus
cheatseq_t cheat_mus = CHEAT("idmus", 2)
Definition at line 388 of file st_stuff.c.
Referenced by ST_Responder().
cheat_mypos
cheatseq_t cheat_mypos = CHEAT("idmypos", 0)
Definition at line 408 of file st_stuff.c.
Referenced by ST_Responder().
cheat_noclip
cheatseq_t cheat_noclip = CHEAT("idspispopd", 0)
Definition at line 392 of file st_stuff.c.
Referenced by ST_Responder().
cheat_powerup
cheatseq_t cheat_powerup[7]
Initial value:
=
{
    CHEAT("idbeholdv", 0),
    CHEAT("idbeholds", 0),
    CHEAT("idbeholdi", 0),
    CHEAT("idbeholdr", 0),
    CHEAT("idbeholda", 0),
    CHEAT("idbeholdl", 0),
    CHEAT("idbehold", 0),
}
Definition at line 395 of file st_stuff.c.
Referenced by ST_Responder().
faceback
patch_t* faceback static
Definition at line 326 of file st_stuff.c.
Referenced by ST_loadUnloadGraphics(), and ST_refreshBackground().
faces
patch_t* faces[ST_NUMFACES] static
Definition at line 323 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_loadUnloadGraphics().
keyboxes
int keyboxes[3] static
Definition at line 383 of file st_stuff.c.
Referenced by ST_createWidgets(), ST_initData(), and ST_updateWidgets().
keys
patch_t* keys[NUMCARDS] static
Definition at line 320 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_loadUnloadGraphics().
lu_palette
int lu_palette static
Definition at line 272 of file st_stuff.c.
Referenced by ST_doPaletteStuff(), ST_loadData(), and ST_Stop().
oldweaponsowned
boolean oldweaponsowned[NUMWEAPONS] static
Definition at line 374 of file st_stuff.c.
Referenced by ST_initData(), and ST_updateFaceWidget().
plyr
player_t* plyr static
Definition at line 266 of file st_stuff.c.
Referenced by ST_calcPainOffset(), ST_createWidgets(), ST_doPaletteStuff(), ST_initData(), ST_Responder(), ST_Ticker(), ST_updateFaceWidget(), and ST_updateWidgets().
sbar
patch_t* sbar static
Definition at line 308 of file st_stuff.c.
Referenced by ST_loadUnloadGraphics(), and ST_refreshBackground().
shortnum
patch_t* shortnum[10] static
Definition at line 317 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_loadUnloadGraphics().
st_armson
boolean st_armson static
Definition at line 302 of file st_stuff.c.
Referenced by ST_createWidgets(), ST_drawWidgets(), and ST_updateWidgets().
st_backing_screen
byte* st_backing_screen
Definition at line 263 of file st_stuff.c.
Referenced by ST_Init(), ST_refreshBackground(), STlib_drawNum(), STlib_updateBinIcon(), and STlib_updateMultIcon().
st_chat
boolean st_chat static
Definition at line 290 of file st_stuff.c.
Referenced by ST_initData(), and ST_updateWidgets().
st_chatstate
st_chatstateenum_t st_chatstate static
Definition at line 281 of file st_stuff.c.
Referenced by ST_initData().
st_clock
unsigned int st_clock static
Definition at line 275 of file st_stuff.c.
Referenced by ST_initData(), and ST_Ticker().
st_cursoron
boolean st_cursoron static
Definition at line 296 of file st_stuff.c.
Referenced by ST_initData().
st_facecount
int st_facecount = 0 static
Definition at line 377 of file st_stuff.c.
Referenced by ST_updateFaceWidget().
st_faceindex
int st_faceindex = 0 static
Definition at line 380 of file st_stuff.c.
Referenced by ST_createWidgets(), ST_initData(), and ST_updateFaceWidget().
st_firsttime
boolean st_firsttime static
Definition at line 269 of file st_stuff.c.
Referenced by ST_doRefresh(), ST_Drawer(), ST_initData(), and ST_Responder().
st_fragscount
int st_fragscount static
Definition at line 368 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_updateWidgets().
st_fragson
boolean st_fragson static
Definition at line 305 of file st_stuff.c.
Referenced by ST_createWidgets(), ST_drawWidgets(), and ST_updateWidgets().
st_gamestate
st_stateenum_t st_gamestate static
Definition at line 284 of file st_stuff.c.
Referenced by ST_initData(), and ST_Responder().
st_msgcounter
int st_msgcounter =0 static
Definition at line 278 of file st_stuff.c.
Referenced by ST_updateWidgets().
st_notdeathmatch
boolean st_notdeathmatch static
Definition at line 299 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_updateWidgets().
st_oldchat
boolean st_oldchat static
Definition at line 293 of file st_stuff.c.
Referenced by ST_initData(), and ST_updateWidgets().
st_oldhealth
int st_oldhealth = -1 static
Definition at line 371 of file st_stuff.c.
Referenced by ST_initData(), ST_Ticker(), and ST_updateFaceWidget().
st_palette
int st_palette = 0 static
Definition at line 934 of file st_stuff.c.
Referenced by ST_doPaletteStuff(), and ST_initData().
st_randomnumber
int st_randomnumber static
Definition at line 386 of file st_stuff.c.
Referenced by ST_Ticker(), and ST_updateFaceWidget().
st_statusbaron
boolean st_statusbaron static
Definition at line 287 of file st_stuff.c.
Referenced by ST_createWidgets(), ST_Drawer(), ST_drawWidgets(), ST_initData(), ST_refreshBackground(), and ST_updateWidgets().
st_stopped
boolean st_stopped = true static
Definition at line 1386 of file st_stuff.c.
Referenced by ST_Start(), and ST_Stop().
tallnum
patch_t* tallnum[10] static
Definition at line 311 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_loadUnloadGraphics().
tallpercent
patch_t* tallpercent static
Definition at line 314 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_loadUnloadGraphics().
w_ammo
st_number_t w_ammo[4] static
Definition at line 360 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_armor
st_percent_t w_armor static
Definition at line 357 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_arms
st_multicon_t w_arms[6] static
Definition at line 348 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_armsbg
st_binicon_t w_armsbg static
Definition at line 344 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_faces
st_multicon_t w_faces static
Definition at line 351 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_frags
st_number_t w_frags static
Definition at line 338 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_health
st_percent_t w_health static
Definition at line 341 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_keyboxes
st_multicon_t w_keyboxes[3] static
Definition at line 354 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_maxammo
st_number_t w_maxammo[4] static
Definition at line 363 of file st_stuff.c.
Referenced by ST_createWidgets(), and ST_drawWidgets().
w_ready
st_number_t w_ready static
Definition at line 335 of file st_stuff.c.
Referenced by ST_createWidgets(), ST_drawWidgets(), and ST_updateWidgets().