Fennix Userspace: Userspace/apps/base/busybox/libbb/chomp.c File Reference
chomp.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC chomp (char *s)
Function Documentation
chomp()
void FAST_FUNC chomp (char * s)
Definition at line 12 of file chomp.c.
 {
     char *lc = last_char_is(s, '\n');
     if (lc)
         *lc = '\0';
 }
References last_char_is(), and s.
Referenced by lpd_main(), process_irq_counts(), process_timer_stats(), show_clock(), unix_do_one(), and unzip_main().