Fennix Userspace: Userspace/musl/src/malloc/oldmalloc/malloc_impl.h File Reference
malloc_impl.h File Reference
#include <sys/mman.h>
#include "dynlink.h"
Data Structures
struct chunk
struct bin
Macros
#define SIZE_ALIGN (4*sizeof(size_t))
#define SIZE_MASK (-SIZE_ALIGN)
#define OVERHEAD (2*sizeof(size_t))
#define MMAP_THRESHOLD (0x1c00*SIZE_ALIGN)
#define DONTCARE 16
#define RECLAIM 163840
#define CHUNK_SIZE(c) ((c)->csize & -2)
#define CHUNK_PSIZE(c) ((c)->psize & -2)
#define PREV_CHUNK(c) ((struct chunk *)((char *)(c) - CHUNK_PSIZE(c)))
#define NEXT_CHUNK(c) ((struct chunk *)((char *)(c) + CHUNK_SIZE(c)))
#define MEM_TO_CHUNK(p) (struct chunk *)((char *)(p) - OVERHEAD)
#define CHUNK_TO_MEM(c) (void *)((char *)(c) + OVERHEAD)
#define BIN_TO_CHUNK(i) (MEM_TO_CHUNK(&mal.bins[i].head))
#define C_INUSE ((size_t)1)
#define IS_MMAPPED(c) !((c)->csize & (C_INUSE))
Functions
hidden void __bin_chunk (struct chunk *)
Data Structure Documentation
chunk
struct chunk
Definition at line 7 of file malloc_impl.h.
Data Fields
size_t csize
struct chunk * next
struct chunk * prev
size_t psize
bin
struct bin
Definition at line 12 of file malloc_impl.h.
Data Fields
struct chunk * head
volatile int lock[2]
struct chunk * tail
Macro Definition Documentation
BIN_TO_CHUNK
#define BIN_TO_CHUNK (i) (MEM_TO_CHUNK(&mal.bins[i].head))
Definition at line 31 of file malloc_impl.h.
C_INUSE
#define C_INUSE ((size_t)1)
Definition at line 33 of file malloc_impl.h.
CHUNK_PSIZE
#define CHUNK_PSIZE (c) ((c)->psize & -2)
Definition at line 26 of file malloc_impl.h.
CHUNK_SIZE
#define CHUNK_SIZE (c) ((c)->csize & -2)
Definition at line 25 of file malloc_impl.h.
CHUNK_TO_MEM
#define CHUNK_TO_MEM (c) (void *)((char *)(c) + OVERHEAD)
Definition at line 30 of file malloc_impl.h.
DONTCARE
#define DONTCARE 16
Definition at line 22 of file malloc_impl.h.
IS_MMAPPED
#define IS_MMAPPED (c) !((c)->csize & (C_INUSE))
Definition at line 35 of file malloc_impl.h.
MEM_TO_CHUNK
#define MEM_TO_CHUNK (p) (struct chunk *)((char *)(p) - OVERHEAD)
Definition at line 29 of file malloc_impl.h.
MMAP_THRESHOLD
#define MMAP_THRESHOLD (0x1c00*SIZE_ALIGN)
Definition at line 21 of file malloc_impl.h.
NEXT_CHUNK
#define NEXT_CHUNK (c) ((struct chunk *)((char *)(c) + CHUNK_SIZE(c)))
Definition at line 28 of file malloc_impl.h.
OVERHEAD
#define OVERHEAD (2*sizeof(size_t))
Definition at line 20 of file malloc_impl.h.
PREV_CHUNK
#define PREV_CHUNK (c) ((struct chunk *)((char *)(c) - CHUNK_PSIZE(c)))
Definition at line 27 of file malloc_impl.h.
RECLAIM
#define RECLAIM 163840
Definition at line 23 of file malloc_impl.h.
SIZE_ALIGN
#define SIZE_ALIGN (4*sizeof(size_t))
Definition at line 18 of file malloc_impl.h.
SIZE_MASK
#define SIZE_MASK (-SIZE_ALIGN)
Definition at line 19 of file malloc_impl.h.
Function Documentation
__bin_chunk()
hidden void __bin_chunk (struct chunk * self)
Definition at line 434 of file malloc.c.
 {
     struct chunk *next = NEXT_CHUNK(self);
     /* Crash on corrupted footer (likely from buffer overflow) */
     if (next->psize != self->csize) a_crash();
     lock(mal.split_merge_lock);
     size_t osize = CHUNK_SIZE(self), size = osize;
     /* Since we hold split_merge_lock, only transition from free to
      * in-use can race; in-use to free is impossible */
     size_t psize = self->psize & C_INUSE ? 0 : CHUNK_PSIZE(self);
     size_t nsize = next->csize & C_INUSE ? 0 : CHUNK_SIZE(next);
     if (psize) {
         int i = bin_index(psize);
         lock_bin(i);
         if (!(self->psize & C_INUSE)) {
             struct chunk *prev = PREV_CHUNK(self);
             unbin(prev, i);
             self = prev;
             size += psize;
         }
         unlock_bin(i);
     }
     if (nsize) {
         int i = bin_index(nsize);
         lock_bin(i);
         if (!(next->csize & C_INUSE)) {
             unbin(next, i);
             next = NEXT_CHUNK(next);
             size += nsize;
         }
         unlock_bin(i);
     }
     int i = bin_index(size);
     lock_bin(i);
     self->csize = size;
     next->psize = size;
     bin_chunk(self, i);
     unlock(mal.split_merge_lock);
     /* Replace middle of large chunks with fresh zero pages */
     if (size > RECLAIM && (size^(size-osize)) > size-osize) {
         uintptr_t a = (uintptr_t)self + SIZE_ALIGN+PAGE_SIZE-1 & -PAGE_SIZE;
         uintptr_t b = (uintptr_t)next - SIZE_ALIGN & -PAGE_SIZE;
         int e = errno;
 #if 1
         __madvise((void *)a, b-a, MADV_DONTNEED);
 #else
         __mmap((void *)a, b-a, PROT_READ|PROT_WRITE,
             MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0);
 #endif
         errno = e;
     }
     unlock_bin(i);
 }
References __madvise(), __mmap(), a_crash, b, bin_chunk(), bin_index(), C_INUSE, CHUNK_PSIZE, CHUNK_SIZE, chunk::csize, errno, i, lock(), lock_bin(), MADV_DONTNEED, mal, MAP_ANONYMOUS, MAP_FIXED, MAP_PRIVATE, chunk::next, NEXT_CHUNK, PAGE_SIZE, chunk::prev, PREV_CHUNK, PROT_READ, PROT_WRITE, chunk::psize, RECLAIM, size, SIZE_ALIGN, unbin(), unlock(), and unlock_bin().
Referenced by __malloc_donate(), aligned_alloc(), free(), and realloc().