Fennix: Userspace/apps/base/busybox/util-linux/lspci.c File Reference
lspci.c File Reference
#include "libbb.h"
Enumerations
enum { OPT_m = (1 << 0) , OPT_k = (1 << 1) }
Functions
static int FAST_FUNC fileAction (struct recursive_state *state UNUSED_PARAM, const char *fileName, struct stat *statbuf UNUSED_PARAM)
int lspci_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_m
OPT_k
Definition at line 32 of file lspci.c.
      {
     OPT_m = (1 << 0),
     OPT_k = (1 << 1),
 };
Function Documentation
fileAction()
static int FAST_FUNC fileAction (struct recursive_state *state UNUSED_PARAM, const char * fileName, struct stat *statbuf UNUSED_PARAM) static
Definition at line 40 of file lspci.c.
 {
     parser_t *parser;
     char *tokens[3];
     char *pci_slot_name = NULL, *driver = NULL;
     int pci_class = 0, pci_vid = 0, pci_did = 0;
     int pci_subsys_vid = 0, pci_subsys_did = 0;
     char *uevent_filename = concat_path_file(fileName, "/uevent");
     parser = config_open2(uevent_filename, fopen_for_read);
     free(uevent_filename);
     while (config_read(parser, tokens, 3, 2, "\0:=", PARSE_NORMAL)) {
         if (strcmp(tokens[0], "DRIVER") == 0) {
             driver = xstrdup(tokens[1]);
             continue;
         }
         if (strcmp(tokens[0], "PCI_CLASS") == 0) {
             pci_class = xstrtou(tokens[1], 16)>>8;
             continue;
         }
         if (strcmp(tokens[0], "PCI_ID") == 0) {
             pci_vid = xstrtou(tokens[1], 16);
             pci_did = xstrtou(tokens[2], 16);
             continue;
         }
         if (strcmp(tokens[0], "PCI_SUBSYS_ID") == 0) {
             pci_subsys_vid = xstrtou(tokens[1], 16);
             pci_subsys_did = xstrtou(tokens[2], 16);
             continue;
         }
         if (strcmp(tokens[0], "PCI_SLOT_NAME") == 0) {
             pci_slot_name = xstrdup(tokens[2]);
             continue;
         }
     }
     config_close(parser);
     if (option_mask32 & OPT_m) {
         printf("%s \"Class %04x\" \"%04x\" \"%04x\" \"%04x\" \"%04x\"",
             pci_slot_name, pci_class, pci_vid, pci_did,
             pci_subsys_vid, pci_subsys_did);
     } else {
         printf("%s Class %04x: %04x:%04x",
             pci_slot_name, pci_class, pci_vid, pci_did);
     }
     if ((option_mask32 & OPT_k) && driver) {
         if (option_mask32 & OPT_m) {
             printf(" \"%s\"", driver);
         } else {
             printf(" %s", driver);
         }
     }
     bb_putchar('\n');
     free(driver);
     free(pci_slot_name);
     return TRUE;
 }
References bb_putchar(), concat_path_file(), config_close(), config_open2(), config_read, fileName, fopen_for_read(), free, NULL, OPT_k, OPT_m, option_mask32, PARSE_NORMAL, parser, printf, strcmp, TRUE, xstrdup(), and xstrtou().
Referenced by lspci_main().
lspci_main()
int lspci_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 110 of file lspci.c.
 {
     getopt32(argv, "m" /*non-compat:*/ "k" /*ignored:*/ "nv");
     recursive_action("/sys/bus/pci/devices",
             ACTION_RECURSE,
             fileAction,
             NULL, /* dirAction */
             NULL /* userData */
     );
     return EXIT_SUCCESS;
 }
References ACTION_RECURSE, argv, EXIT_SUCCESS, fileAction(), getopt32(), NULL, and recursive_action().