Fennix: Userspace/mlibc/options/posix/include/spawn.h File Reference
spawn.h File Reference
#include <abi-bits/signal.h>
#include <abi-bits/mode_t.h>
#include <abi-bits/pid_t.h>
#include <sched.h>
Data Structures
struct posix_spawnattr_t
struct posix_spawn_file_actions_t
Macros
#define POSIX_SPAWN_RESETIDS 1
#define POSIX_SPAWN_SETPGROUP 2
#define POSIX_SPAWN_SETSIGDEF 4
#define POSIX_SPAWN_SETSIGMASK 8
#define POSIX_SPAWN_SETSCHEDPARAM 16
#define POSIX_SPAWN_SETSCHEDULER 32
#define POSIX_SPAWN_USEVFORK 64
#define POSIX_SPAWN_SETSID 128
Functions
int posix_spawn (pid_t *__restrict pid, const char *__restrict path, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *__restrict attrs, char *const argv[], char *const envp[])
int posix_spawnattr_init (posix_spawnattr_t *attr)
int posix_spawnattr_destroy (posix_spawnattr_t *attr)
int posix_spawnattr_setflags (posix_spawnattr_t *attr, short flags)
int posix_spawnattr_setsigdefault (posix_spawnattr_t *__restrict attr, const sigset_t *__restrict sigdefault)
int posix_spawnattr_setschedparam (posix_spawnattr_t *__restrict attr, const struct sched_param *__restrict schedparam)
int posix_spawnattr_setschedpolicy (posix_spawnattr_t *attr, int schedpolicy)
int posix_spawnattr_setsigmask (posix_spawnattr_t *__restrict attr, const sigset_t *__restrict sigmask)
int posix_spawnattr_setpgroup (posix_spawnattr_t *attr, pid_t pgroup)
int posix_spawn_file_actions_init (posix_spawn_file_actions_t *file_actions)
int posix_spawn_file_actions_destroy (posix_spawn_file_actions_t *file_actions)
int posix_spawn_file_actions_adddup2 (posix_spawn_file_actions_t *file_actions, int fildes, int newfildes)
int posix_spawn_file_actions_addclose (posix_spawn_file_actions_t *file_actions, int fildes)
int posix_spawn_file_actions_addopen (posix_spawn_file_actions_t *__restrict file_actions, int fildes, const char *__restrict path, int oflag, mode_t mode)
int posix_spawnp (pid_t *__restrict pid, const char *__restrict file, const posix_spawn_file_actions_t *file_actions, const posix_spawnattr_t *__restrict attrp, char *const argv[], char *const envp[])
Data Structure Documentation
posix_spawnattr_t
struct posix_spawnattr_t
Definition at line 14 of file spawn.h.
Data Fields
sigset_t __def
short int __flags
int __flags
void * __fn
sigset_t __mask
int __pad[16]
char __pad[64 - sizeof(void *)]
pid_t __pgrp
int __pol
int __policy
int __prio
sigset_t __sd
struct sched_param __sp
sigset_t __ss
posix_spawn_file_actions_t
struct posix_spawn_file_actions_t
Definition at line 25 of file spawn.h.
Data Fields
struct __spawn_action * __actions
void * __actions
int __allocated
int __pad[16]
int __pad0[2]
int __used
Macro Definition Documentation
POSIX_SPAWN_RESETIDS
#define POSIX_SPAWN_RESETIDS 1
Definition at line 33 of file spawn.h.
POSIX_SPAWN_SETPGROUP
#define POSIX_SPAWN_SETPGROUP 2
Definition at line 34 of file spawn.h.
POSIX_SPAWN_SETSCHEDPARAM
#define POSIX_SPAWN_SETSCHEDPARAM 16
Definition at line 37 of file spawn.h.
POSIX_SPAWN_SETSCHEDULER
#define POSIX_SPAWN_SETSCHEDULER 32
Definition at line 38 of file spawn.h.
POSIX_SPAWN_SETSID
#define POSIX_SPAWN_SETSID 128
Definition at line 40 of file spawn.h.
POSIX_SPAWN_SETSIGDEF
#define POSIX_SPAWN_SETSIGDEF 4
Definition at line 35 of file spawn.h.
POSIX_SPAWN_SETSIGMASK
#define POSIX_SPAWN_SETSIGMASK 8
Definition at line 36 of file spawn.h.
POSIX_SPAWN_USEVFORK
#define POSIX_SPAWN_USEVFORK 64
Definition at line 39 of file spawn.h.
Function Documentation
posix_spawn()
int posix_spawn (pid_t *__restrict pid, const char *__restrict path, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t *__restrict attrs, char *const argv[], char *const envp[])
Definition at line 191 of file spawn-stubs.cpp.
{
     pid_t pid;
     int ec = 0, cs;
     struct args args;
     const posix_spawnattr_t empty_attr = {};
     sigset_t full_sigset;
     sigfillset(&full_sigset);
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     args.path = path;
     args.fa = file_actions;
     args.attr = attrs ? attrs : &empty_attr;
     args.argv = argv;
     args.envp = envp;
     pthread_sigmask(SIG_BLOCK, &full_sigset, &args.oldmask);
     /* The lock guards both against seeing a SIGABRT disposition change
      * by abort and against leaking the pipe fd to fork-without-exec. */
     //LOCK(__abort_lock);
     if(pipe2(args.p, O_CLOEXEC)) {
         //UNLOCK(__abort_lock);
         ec = errno;
         goto fail;
     }
     /* Mlibc change: We use fork + execve, as clone is not implemented.
      * This yields the same result in the end. */
     //pid = clone(child, stack + sizeof stack, CLONE_VM | CLONE_VFORK | SIGCHLD, &args);
     pid = fork();
     if(!pid) {
         child(&args);
     }
     close(args.p[1]);
     //UNLOCK(__abort_lock);
     if(pid > 0) {
         if(read(args.p[0], &ec, sizeof ec) != sizeof ec)
             ec = 0;
         else
             waitpid(pid, 0, 0);
     } else {
         ec = -pid;
     }
     close(args.p[0]);
     if(!ec && res)
         *res = pid;
 fail:
     pthread_sigmask(SIG_SETMASK, &args.oldmask, 0);
     pthread_setcancelstate(cs, 0);
     return ec;
 }
References args::argv, args::attr, child(), close(), args::envp, errno, args::fa, fork(), O_CLOEXEC, args::oldmask, args::p, args::path, pipe2(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), pthread_sigmask(), read(), SIG_BLOCK, SIG_SETMASK, sigfillset(), and waitpid().
Referenced by posix_spawnp().
posix_spawn_file_actions_addclose()
int posix_spawn_file_actions_addclose (posix_spawn_file_actions_t * file_actions, int fildes)
Definition at line 335 of file spawn-stubs.cpp.
                     {
     struct fdop *op = (struct fdop *)malloc(sizeof *op);
     if(!op)
         return ENOMEM;
     op->cmd = FDOP_CLOSE;
     op->fd = fildes;
     if((op->next = (struct fdop *)file_actions->__actions))
         op->next->prev = op;
     op->prev = 0;
     file_actions->__actions = op;
     return 0;
 }
References posix_spawn_file_actions_t::__actions, fdop::cmd, ENOMEM, fdop::fd, FDOP_CLOSE, malloc(), fdop::next, and fdop::prev.
posix_spawn_file_actions_adddup2()
int posix_spawn_file_actions_adddup2 (posix_spawn_file_actions_t * file_actions, int fildes, int newfildes)
Definition at line 320 of file spawn-stubs.cpp.
{
     struct fdop *op = (struct fdop *)malloc(sizeof *op);
     if(!op)
         return ENOMEM;
     op->cmd = FDOP_DUP2;
     op->srcfd = fildes;
     op->fd = newfildes;
     if((op->next = (struct fdop *)file_actions->__actions))
         op->next->prev = op;
     op->prev = 0;
     file_actions->__actions = op;
     return 0;
 }
References posix_spawn_file_actions_t::__actions, fdop::cmd, ENOMEM, fdop::fd, FDOP_DUP2, malloc(), fdop::next, fdop::prev, and fdop::srcfd.
posix_spawn_file_actions_addopen()
int posix_spawn_file_actions_addopen (posix_spawn_file_actions_t *__restrict file_actions, int fildes, const char *__restrict path, int oflag, mode_t mode)
Definition at line 349 of file spawn-stubs.cpp.
{
     struct fdop *op = (struct fdop *)malloc(sizeof *op + strlen(path) + 1);
     if(!op)
         return ENOMEM;
     op->cmd = FDOP_OPEN;
     op->fd = fildes;
     op->oflag = oflag;
     op->mode = mode;
     strcpy(op->path, path);
     if((op->next = (struct fdop *)file_actions->__actions))
         op->next->prev = op;
     op->prev = 0;
     file_actions->__actions = op;
     return 0;
 }
References fdop::cmd, ENOMEM, fdop::fd, FDOP_OPEN, malloc(), fdop::mode, fdop::next, fdop::oflag, fdop::path, fdop::prev, strcpy, and strlen().
posix_spawn_file_actions_destroy()
int posix_spawn_file_actions_destroy (posix_spawn_file_actions_t * file_actions)
Definition at line 310 of file spawn-stubs.cpp.
{
     struct fdop *op = (struct fdop *)file_actions->__actions, *next;
     while(op) {
         next = op->next;
         free(op);
         op = next;
     }
     return 0;
 }
References posix_spawn_file_actions_t::__actions, free(), and fdop::next.
posix_spawn_file_actions_init()
int posix_spawn_file_actions_init (posix_spawn_file_actions_t * file_actions)
Definition at line 305 of file spawn-stubs.cpp.
{
     file_actions->__actions = 0;
     return 0;
 }
References posix_spawn_file_actions_t::__actions.
posix_spawnattr_destroy()
int posix_spawnattr_destroy (posix_spawnattr_t * attr)
Definition at line 257 of file spawn-stubs.cpp.
{
     return 0;
 }
posix_spawnattr_init()
int posix_spawnattr_init (posix_spawnattr_t * attr)
Definition at line 252 of file spawn-stubs.cpp.
{
     *attr = (posix_spawnattr_t){};
     return 0;
 }
References mlibc::attr.
posix_spawnattr_setflags()
int posix_spawnattr_setflags (posix_spawnattr_t * attr, short flags)
Definition at line 261 of file spawn-stubs.cpp.
{
     const unsigned all_flags =
             POSIX_SPAWN_RESETIDS |
             POSIX_SPAWN_SETPGROUP |
             POSIX_SPAWN_SETSIGDEF |
             POSIX_SPAWN_SETSIGMASK |
             POSIX_SPAWN_SETSCHEDPARAM |
             POSIX_SPAWN_SETSCHEDULER |
             POSIX_SPAWN_USEVFORK |
             POSIX_SPAWN_SETSID;
     if(flags & ~all_flags)
         return EINVAL;
     attr->__flags = flags;
     return 0;
 }
References mlibc::attr, EINVAL, mlibc::flags, POSIX_SPAWN_RESETIDS, POSIX_SPAWN_SETPGROUP, POSIX_SPAWN_SETSCHEDPARAM, POSIX_SPAWN_SETSCHEDULER, POSIX_SPAWN_SETSID, POSIX_SPAWN_SETSIGDEF, POSIX_SPAWN_SETSIGMASK, and POSIX_SPAWN_USEVFORK.
posix_spawnattr_setpgroup()
int posix_spawnattr_setpgroup (posix_spawnattr_t * attr, pid_t pgroup)
Definition at line 300 of file spawn-stubs.cpp.
{
     attr->__pgrp = pgroup;
     return 0;
 }
References mlibc::attr.
posix_spawnattr_setschedparam()
int posix_spawnattr_setschedparam (posix_spawnattr_t *__restrict attr, const struct sched_param *__restrict schedparam)
posix_spawnattr_setschedpolicy()
int posix_spawnattr_setschedpolicy (posix_spawnattr_t * attr, int schedpolicy)
Definition at line 289 of file spawn-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
posix_spawnattr_setsigdefault()
int posix_spawnattr_setsigdefault (posix_spawnattr_t *__restrict attr, const sigset_t *__restrict sigdefault)
Definition at line 277 of file spawn-stubs.cpp.
{
     attr->__def = *sigdefault;
     return 0;
 }
References mlibc::attr.
posix_spawnattr_setsigmask()
int posix_spawnattr_setsigmask (posix_spawnattr_t *__restrict attr, const sigset_t *__restrict sigmask)
Definition at line 294 of file spawn-stubs.cpp.
{
     attr->__mask = *sigmask;
     return 0;
 }
References mlibc::attr, and mlibc::sigmask.
posix_spawnp()
int posix_spawnp (pid_t *__restrict pid, const char *__restrict file, const posix_spawn_file_actions_t * file_actions, const posix_spawnattr_t *__restrict attrp, char *const argv[], char *const envp[])
Definition at line 366 of file spawn-stubs.cpp.
{
     posix_spawnattr_t spawnp_attr = {};
     if(attrp)
         spawnp_attr = *attrp;
     spawnp_attr.__fn = (void *)execvpe;
     return posix_spawn(pid, file, file_actions, &spawnp_attr, argv, envp);
 }
References posix_spawnattr_t::__fn, execvpe(), and posix_spawn().