Fennix Userspace: Userspace/apps/base/busybox/libbb/safe_strncpy.c File Reference
safe_strncpy.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC safe_strncpy (char *dst, const char *src, size_t size)
void FAST_FUNC overlapping_strcpy (char *dst, const char *src)
Function Documentation
overlapping_strcpy()
void FAST_FUNC overlapping_strcpy (char * dst, const char * src)
Definition at line 20 of file safe_strncpy.c.
 {
     /* Cheap optimization for dst == src case -
      * better to have it here than in many callers.
      */
     if (dst != src) {
         while ((*dst = *src) != '\0') {
             dst++;
             src++;
         }
     }
 }
References dst, and src.
Referenced by cttyhack_main(), cut_out_ull_opt(), display_process_list(), expand_string_to_string(), get_header_cpio(), get_header_tar(), klogd_main(), lpqr_main(), nmeter_main(), print_formatted(), process_files(), setlocalenv(), strip_ipv6_scope_id(), sysctl_handle_preload_file(), tokenize(), unzip_main(), update_passwd(), vgetopt32(), and xargs_main().
safe_strncpy()
char* FAST_FUNC safe_strncpy (char * dst, const char * src, size_t size)
Definition at line 12 of file safe_strncpy.c.
 {
     if (!size) return dst;
     dst[--size] = '\0';
     return strncpy(dst, src, size);
 }
References dst, size, src, and strncpy().
Referenced by add_lease(), arpping(), create_socket(), cryptpw_main(), evaluate_string(), find_block_device_in_dir(), get_cached(), get_irqs_from_interrupts(), get_uidgid(), handle_incoming_and_exit(), login_main(), lookupvar(), lsof_main(), mkfs_ext2_main(), mkfs_reiser_main(), mkswap_main(), new_init_action(), procps_scan(), reread_config_file(), rmmod_main(), set_loopdev_params(), show_entry(), str2sockaddr(), tune2fs_main(), update_utmp(), who_main(), write_new_utmp(), xgetpty(), and xmalloc_optname_optval().