Fennix Userspace: Userspace/apps/base/busybox/libbb/iterate_on_dir.c File Reference
iterate_on_dir.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC iterate_on_dir (const char *dir_name, int FAST_FUNC(*func)(const char *, struct dirent *, void *), void *private)
Function Documentation
iterate_on_dir()
int FAST_FUNC iterate_on_dir (const char * dir_name, int FAST_FUNC(*)(const char *, struct dirent *, void *) func, void * private)
Definition at line 12 of file iterate_on_dir.c.
 {
     DIR *dir;
     struct dirent *de;
     dir = opendir(dir_name);
     if (dir == NULL) {
         return -1;
     }
     while ((de = readdir(dir)) != NULL) {
         func(dir_name, de, private);
     }
     closedir(dir);
     return 0;
 }
References closedir(), dir, NULL, opendir(), and readdir().
Referenced by change_attributes(), delete_contents(), lsattr_args(), lsattr_dir_proc(), and taskset_main().