Fennix Userspace: Userspace/apps/base/busybox/runit/chpst.c File Reference
chpst.c File Reference
#include "libbb.h"
Enumerations
enum {
OPT_a = (1 << 0) * ENABLE_SOFTLIMIT , OPT_c = (1 << 1) * (ENABLE_SOFTLIMIT || ENABLE_CHPST) , OPT_d = (1 << 2) * (ENABLE_SOFTLIMIT || ENABLE_CHPST) , OPT_f = (1 << 3) * (ENABLE_SOFTLIMIT || ENABLE_CHPST) ,
OPT_l = (1 << 4) * ENABLE_SOFTLIMIT , OPT_m = (1 << 5) * (ENABLE_SOFTLIMIT || ENABLE_CHPST) , OPT_o = (1 << 6) * (ENABLE_SOFTLIMIT || ENABLE_CHPST) , OPT_p = (1 << 7) * (ENABLE_SOFTLIMIT || ENABLE_CHPST) ,
OPT_r = (1 << 8) * ENABLE_SOFTLIMIT , OPT_s = (1 << 9) * ENABLE_SOFTLIMIT , OPT_t = (1 << 10) * ENABLE_SOFTLIMIT , OPT_u = (1 << 11) * (ENABLE_CHPST || ENABLE_SETUIDGID) ,
OPT_U = (1 << 12) * (ENABLE_CHPST || ENABLE_ENVUIDGID) , OPT_e = (1 << 13) * (ENABLE_CHPST || ENABLE_ENVDIR) , OPT_root = (1 << 14) * ENABLE_CHPST , OPT_n = (1 << 15) * ENABLE_CHPST ,
OPT_v = (1 << 16) * ENABLE_CHPST , OPT_P = (1 << 17) * ENABLE_CHPST , OPT_0 = (1 << 18) * ENABLE_CHPST , OPT_1 = (1 << 19) * ENABLE_CHPST ,
OPT_2 = (1 << 20) * ENABLE_CHPST
}
Functions
static NOINLINE void edir (const char *directory_name)
static void limit (int what, long l)
int chpst_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_a
OPT_c
OPT_d
OPT_f
OPT_l
OPT_m
OPT_o
OPT_p
OPT_r
OPT_s
OPT_t
OPT_u
OPT_U
OPT_e
OPT_root
OPT_n
OPT_v
OPT_P
OPT_0
OPT_1
OPT_2
Definition at line 176 of file chpst.c.
      {
     OPT_a = (1 << 0) * ENABLE_SOFTLIMIT,
     OPT_c = (1 << 1) * (ENABLE_SOFTLIMIT || ENABLE_CHPST),
     OPT_d = (1 << 2) * (ENABLE_SOFTLIMIT || ENABLE_CHPST),
     OPT_f = (1 << 3) * (ENABLE_SOFTLIMIT || ENABLE_CHPST),
     OPT_l = (1 << 4) * ENABLE_SOFTLIMIT,
     OPT_m = (1 << 5) * (ENABLE_SOFTLIMIT || ENABLE_CHPST),
     OPT_o = (1 << 6) * (ENABLE_SOFTLIMIT || ENABLE_CHPST),
     OPT_p = (1 << 7) * (ENABLE_SOFTLIMIT || ENABLE_CHPST),
     OPT_r = (1 << 8) * ENABLE_SOFTLIMIT,
     OPT_s = (1 << 9) * ENABLE_SOFTLIMIT,
     OPT_t = (1 << 10) * ENABLE_SOFTLIMIT,
     OPT_u = (1 << 11) * (ENABLE_CHPST || ENABLE_SETUIDGID),
     OPT_U = (1 << 12) * (ENABLE_CHPST || ENABLE_ENVUIDGID),
     OPT_e = (1 << 13) * (ENABLE_CHPST || ENABLE_ENVDIR),
     OPT_root = (1 << 14) * ENABLE_CHPST,
     OPT_n = (1 << 15) * ENABLE_CHPST,
     OPT_v = (1 << 16) * ENABLE_CHPST,
     OPT_P = (1 << 17) * ENABLE_CHPST,
     OPT_0 = (1 << 18) * ENABLE_CHPST,
     OPT_1 = (1 << 19) * ENABLE_CHPST,
     OPT_2 = (1 << 20) * ENABLE_CHPST,
 };
Function Documentation
chpst_main()
int chpst_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 277 of file chpst.c.
 {
     struct bb_uidgid_t ugid;
     char *set_user = set_user; /* for compiler */
     char *env_dir = env_dir;
     char *root;
     char *nicestr;
     unsigned limita;
     unsigned limitc;
     unsigned limitd;
     unsigned limitf;
     unsigned limitl;
     unsigned limitm;
     unsigned limito;
     unsigned limitp;
     unsigned limitr;
     unsigned limits;
     unsigned limitt;
     unsigned opt;
     if ((ENABLE_CHPST && applet_name[0] == 'c')
      || (ENABLE_SOFTLIMIT && applet_name[1] == 'o')
     ) {
         // FIXME: can we live with int-sized limits?
         // can we live with 40000 days?
         // if yes -> getopt converts strings to numbers for us
         opt = getopt32(argv, "^+"
             "a:+c:+d:+f:+l:+m:+o:+p:+r:+s:+t:+u:U:e:"
             IF_CHPST("/:n:vP012")
             "\0" "-1",
             &limita, &limitc, &limitd, &limitf, &limitl,
             &limitm, &limito, &limitp, &limitr, &limits, &limitt,
             &set_user, &set_user, &env_dir
             IF_CHPST(, &root, &nicestr));
         argv += optind;
         if (opt & OPT_m) { // -m means -asld
             limita = limits = limitl = limitd = limitm;
             opt |= (OPT_s | OPT_l | OPT_a | OPT_d);
         }
     } else {
         option_mask32 = opt = 0;
         argv++;
         if (!*argv)
             bb_show_usage();
     }
     // envdir?
     if (ENABLE_ENVDIR && applet_name[3] == 'd') {
         env_dir = *argv++;
         opt |= OPT_e;
     }
     // setuidgid?
     if (ENABLE_SETUIDGID && applet_name[1] == 'e') {
         set_user = *argv++;
         opt |= OPT_u;
     }
     // envuidgid?
     if (ENABLE_ENVUIDGID && applet_name[0] == 'e' && applet_name[3] == 'u') {
         set_user = *argv++;
         opt |= OPT_U;
     }
     // we must have PROG [ARGS]
     if (!*argv)
         bb_show_usage();
     // set limits
     if (opt & OPT_d) {
 #ifdef RLIMIT_DATA
         limit(RLIMIT_DATA, limitd);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "DATA");
 #endif
     }
     if (opt & OPT_s) {
 #ifdef RLIMIT_STACK
         limit(RLIMIT_STACK, limits);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "STACK");
 #endif
     }
     if (opt & OPT_l) {
 #ifdef RLIMIT_MEMLOCK
         limit(RLIMIT_MEMLOCK, limitl);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "MEMLOCK");
 #endif
     }
     if (opt & OPT_a) {
 #ifdef RLIMIT_VMEM
         limit(RLIMIT_VMEM, limita);
 #else
 #ifdef RLIMIT_AS
         limit(RLIMIT_AS, limita);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "VMEM");
 #endif
 #endif
     }
     if (opt & OPT_o) {
 #ifdef RLIMIT_NOFILE
         limit(RLIMIT_NOFILE, limito);
 #else
 #ifdef RLIMIT_OFILE
         limit(RLIMIT_OFILE, limito);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "NOFILE");
 #endif
 #endif
     }
     if (opt & OPT_p) {
 #ifdef RLIMIT_NPROC
         limit(RLIMIT_NPROC, limitp);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "NPROC");
 #endif
     }
     if (opt & OPT_f) {
 #ifdef RLIMIT_FSIZE
         limit(RLIMIT_FSIZE, limitf);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "FSIZE");
 #endif
     }
     if (opt & OPT_c) {
 #ifdef RLIMIT_CORE
         limit(RLIMIT_CORE, limitc);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "CORE");
 #endif
     }
     if (opt & OPT_r) {
 #ifdef RLIMIT_RSS
         limit(RLIMIT_RSS, limitr);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "RSS");
 #endif
     }
     if (opt & OPT_t) {
 #ifdef RLIMIT_CPU
         limit(RLIMIT_CPU, limitt);
 #else
         if (opt & OPT_v)
             bb_error_msg("system does not support RLIMIT_%s",
                 "CPU");
 #endif
     }
     if (opt & OPT_P)
         setsid();
     if (opt & OPT_e)
         edir(env_dir);
     if (opt & (OPT_u|OPT_U))
         xget_uidgid(&ugid, set_user);
     // chrooted jail must have /etc/passwd if we move this after chroot.
     // OTOH chroot fails for non-roots.
     // Solution: cache uid/gid before chroot, apply uid/gid after.
     if (opt & OPT_U) {
         xsetenv("GID", utoa(ugid.gid));
         xsetenv("UID", utoa(ugid.uid));
     }
     if (opt & OPT_root) {
         xchroot(root);
     }
     /* nice should be done before xsetuid */
     if (opt & OPT_n) {
         errno = 0;
         if (nice(xatoi(nicestr)) == -1)
             bb_simple_perror_msg_and_die("nice");
     }
     if (opt & OPT_u) {
         if (setgroups(1, &ugid.gid) == -1)
             bb_simple_perror_msg_and_die("setgroups");
         xsetgid(ugid.gid);
         xsetuid(ugid.uid);
     }
     if (opt & OPT_0)
         close(STDIN_FILENO);
     if (opt & OPT_1)
         close(STDOUT_FILENO);
     if (opt & OPT_2)
         close(STDERR_FILENO);
     BB_EXECVP_or_die(argv);
 }
References applet_name, argv, bb_error_msg(), BB_EXECVP_or_die(), bb_show_usage(), bb_simple_perror_msg_and_die(), close(), edir(), errno, getopt32(), bb_uidgid_t::gid, limit(), nice(), opt, OPT_0, OPT_1, OPT_2, OPT_a, OPT_c, OPT_d, OPT_e, OPT_f, OPT_l, OPT_m, OPT_n, OPT_o, OPT_p, OPT_P, OPT_r, OPT_root, OPT_s, OPT_t, OPT_u, OPT_U, OPT_v, optind, option_mask32, RLIMIT_AS, RLIMIT_CORE, RLIMIT_CPU, RLIMIT_DATA, RLIMIT_FSIZE, RLIMIT_MEMLOCK, RLIMIT_NOFILE, RLIMIT_NPROC, RLIMIT_RSS, RLIMIT_STACK, setgroups(), setsid(), STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, bb_uidgid_t::uid, utoa(), xchroot(), xget_uidgid(), xsetenv(), xsetgid(), and xsetuid().
edir()
static NOINLINE void edir (const char * directory_name) static
Definition at line 201 of file chpst.c.
 {
     int wdir;
     DIR *dir;
     struct dirent *d;
     int fd;
     wdir = xopen(".", O_RDONLY | O_NDELAY);
     xchdir(directory_name);
     dir = xopendir(".");
     for (;;) {
         char buf[256];
         char *tail;
         int size;
         errno = 0;
         d = readdir(dir);
         if (!d) {
             if (errno)
                 bb_perror_msg_and_die("readdir %s",
                         directory_name);
             break;
         }
         if (d->d_name[0] == '.')
             continue;
         fd = open(d->d_name, O_RDONLY | O_NDELAY);
         if (fd < 0) {
             if ((errno == EISDIR) && directory_name) {
                 if (option_mask32 & OPT_v)
                     bb_perror_msg("warning: %s/%s is a directory",
                         directory_name, d->d_name);
                 continue;
             }
             bb_perror_msg_and_die("open %s/%s",
                         directory_name, d->d_name);
         }
         size = full_read(fd, buf, sizeof(buf)-1);
         close(fd);
         if (size < 0)
             bb_perror_msg_and_die("read %s/%s",
                     directory_name, d->d_name);
         if (size == 0) {
             unsetenv(d->d_name);
             continue;
         }
         buf[size] = '\n';
         tail = strchr(buf, '\n');
         /* skip trailing whitespace */
         while (1) {
             *tail = '\0';
             tail--;
             if (tail < buf || !isspace(*tail))
                 break;
         }
         xsetenv(d->d_name, buf);
     }
     closedir(dir);
     xfchdir(wdir);
     close(wdir);
 }
References bb_perror_msg(), bb_perror_msg_and_die(), buf, close(), closedir(), dirent::d_name, dir, EISDIR, errno, fd, full_read(), isspace, O_NDELAY, O_RDONLY, open(), OPT_v, option_mask32, readdir(), size, strchr(), tail, unsetenv(), xchdir(), xfchdir(), xopen(), xopendir(), and xsetenv().
Referenced by chpst_main().
limit()
static void limit (int what, long l) static
Definition at line 262 of file chpst.c.
 {
     struct rlimit r;
     /* Never fails under Linux (except if you pass it bad arguments) */
     getrlimit(what, &r);
     if ((l < 0) || (l > r.rlim_max))
         r.rlim_cur = r.rlim_max;
     else
         r.rlim_cur = l;
     if (setrlimit(what, &r) == -1)
         bb_simple_perror_msg_and_die("setrlimit");
 }
References bb_simple_perror_msg_and_die(), getrlimit(), l, rlimit::rlim_cur, rlimit::rlim_max, and setrlimit().
Referenced by _rl_isearch_dispatch(), chpst_main(), get_next_block(), history_search_internal(), longest_match(), lzma_len(), lzma_match(), nandwrite_main(), printlim(), pshared_barrier_wait(), pthread_barrier_wait(), rc_bittree(), rc_bittree_reverse(), rc_direct(), rl_display_match_list(), run(), shell_builtin_ulimit(), strlimitcpy(), and volume_id_probe_msdos_part_table().