Fennix: Userspace/apps/base/busybox/libbb/unicode.c File Reference
unicode.c File Reference
#include "libbb.h"
#include "unicode.h"
Macros
#define ERROR_WCHAR (~(wchar_t)0)
Functions
static size_t wcrtomb_internal (char *s, wchar_t wc)
size_t FAST_FUNC wcrtomb (char *s, wchar_t wc, mbstate_t *ps UNUSED_PARAM)
size_t FAST_FUNC wcstombs (char *dest, const wchar_t *src, size_t n)
static const char * mbstowc_internal (wchar_t *res, const char *src)
size_t FAST_FUNC mbstowcs (wchar_t *dest, const char *src, size_t n)
int FAST_FUNC iswspace (wint_t wc)
int FAST_FUNC iswalnum (wint_t wc)
int FAST_FUNC iswpunct (wint_t wc)
int FAST_FUNC wcwidth (unsigned ucs)
size_t FAST_FUNC unicode_strlen (const char *string)
size_t FAST_FUNC unicode_strwidth (const char *string)
static char *FAST_FUNC unicode_conv_to_printable2 (uni_stat_t *stats, const char *src, unsigned width, int flags)
char *FAST_FUNC unicode_conv_to_printable (uni_stat_t *stats, const char *src)
char *FAST_FUNC unicode_conv_to_printable_fixedwidth (const char *src, unsigned width)
Variables
uint8_t unicode_status
Macro Definition Documentation
ERROR_WCHAR
#define ERROR_WCHAR (~(wchar_t)0)
Definition at line 173 of file unicode.c.
Function Documentation
iswalnum()
int FAST_FUNC iswalnum (wint_t wc)
Definition at line 263 of file unicode.c.
 {
     return (unsigned)wc <= 0x7f && isalnum(wc);
 }
References isalnum.
iswpunct()
int FAST_FUNC iswpunct (wint_t wc)
Definition at line 268 of file unicode.c.
 {
     return (unsigned)wc <= 0x7f && ispunct(wc);
 }
References ispunct.
Referenced by iswctype().
iswspace()
int FAST_FUNC iswspace (wint_t wc)
Definition at line 258 of file unicode.c.
 {
     return (unsigned)wc <= 0x7f && isspace(wc);
 }
References isspace.
Referenced by iswctype(), iswgraph(), vfwscanf(), and wcstox().
mbstowc_internal()
static const char* mbstowc_internal (wchar_t * res, const char * src) static
Definition at line 175 of file unicode.c.
 {
     int bytes;
     unsigned c = (unsigned char) *src++;
     if (c <= 0x7f) {
         *res = c;
         return src;
     }
     /* 80-7FF -> 110yyyxx 10xxxxxx */
     /* 800-FFFF -> 1110yyyy 10yyyyxx 10xxxxxx */
     /* 10000-1FFFFF -> 11110zzz 10zzyyyy 10yyyyxx 10xxxxxx */
     /* 200000-3FFFFFF -> 111110tt 10zzzzzz 10zzyyyy 10yyyyxx 10xxxxxx */
     /* 4000000-FFFFFFFF -> 111111tt 10tttttt 10zzzzzz 10zzyyyy 10yyyyxx 10xxxxxx */
     bytes = 0;
     do {
         c <<= 1;
         bytes++;
     } while ((c & 0x80) && bytes < 6);
     if (bytes == 1) {
         /* A bare "continuation" byte. Say, 80 */
         *res = ERROR_WCHAR;
         return src;
     }
     c = (uint8_t)(c) >> bytes;
     while (--bytes) {
         unsigned ch = (unsigned char) *src;
         if ((ch & 0xc0) != 0x80) {
             /* Missing "continuation" byte. Example: e0 80 */
             *res = ERROR_WCHAR;
             return src;
         }
         c = (c << 6) + (ch & 0x3f);
         src++;
     }
     /* TODO */
     /* Need to check that c isn't produced by overlong encoding */
     /* Example: 11000000 10000000 converts to NUL */
     /* 11110000 10000000 10000100 10000000 converts to 0x100 */
     /* correct encoding: 11000100 10000000 */
     if (c <= 0x7f) { /* crude check */
         *res = ERROR_WCHAR;
         return src;
     }
     *res = c;
     return src;
 }
References c, ERROR_WCHAR, and src.
Referenced by mbstowcs(), and unicode_conv_to_printable2().
mbstowcs()
size_t FAST_FUNC mbstowcs (wchar_t * dest, const char * src, size_t n)
Definition at line 226 of file unicode.c.
 {
     size_t org_n = n;
     if (unicode_status != UNICODE_ON) {
         while (n) {
             unsigned char c = *src++;
             if (dest)
                 *dest++ = c;
             if (c == 0)
                 break;
             n--;
         }
         return org_n - n;
     }
     while (n) {
         wchar_t wc;
         src = mbstowc_internal(&wc, src);
         if (wc == ERROR_WCHAR) /* error */
             return (size_t) -1L;
         if (dest)
             *dest++ = wc;
         if (wc == 0) /* end-of-string */
             break;
         n--;
     }
     return org_n - n;
 }
References c, ERROR_WCHAR, mbstowc_internal(), n, src, UNICODE_ON, and unicode_status.
Referenced by __wcsftime_l(), cutchars(), is_valid_hostname(), rev_main(), string_extract_verbatim(), and unicode_strlen().
unicode_conv_to_printable()
char* FAST_FUNC unicode_conv_to_printable (uni_stat_t * stats, const char * src)
Definition at line 1143 of file unicode.c.
 {
     return unicode_conv_to_printable2(stats, src, INT_MAX, 0);
 }
References INT_MAX, src, and unicode_conv_to_printable2().
Referenced by df_main(), lsmod_main(), and printable_string2().
unicode_conv_to_printable2()
static char* FAST_FUNC unicode_conv_to_printable2 (uni_stat_t * stats, const char * src, unsigned width, int flags) static
Definition at line 1011 of file unicode.c.
 {
     char *dst;
     unsigned dst_len;
     unsigned uni_count;
     unsigned uni_width;
     if (unicode_status != UNICODE_ON) {
         char *d;
         if (flags & UNI_FLAG_PAD) {
             d = dst = xmalloc(width + 1);
             while ((int)--width >= 0) {
                 unsigned char c = *src;
                 if (c == '\0') {
                     do
                         *d++ = ' ';
                     while ((int)--width >= 0);
                     break;
                 }
                 *d++ = (c >= ' ' && c < 0x7f) ? c : '?';
                 src++;
             }
             *d = '\0';
         } else {
             d = dst = xstrndup(src, width);
             while (*d) {
                 unsigned char c = *d;
                 if (c < ' ' || c >= 0x7f)
                     *d = '?';
                 d++;
             }
         }
         if (stats) {
             stats->byte_count = (d - dst);
             stats->unicode_count = (d - dst);
             stats->unicode_width = (d - dst);
         }
         return dst;
     }
     dst = NULL;
     uni_count = uni_width = 0;
     dst_len = 0;
     while (1) {
         int w;
         wchar_t wc;
 #if ENABLE_UNICODE_USING_LOCALE
         {
             mbstate_t mbst = { 0 };
             ssize_t rc = mbsrtowcs(&wc, &src, 1, &mbst);
             /* If invalid sequence is seen: -1 is returned,
              * src points to the invalid sequence, errno = EILSEQ.
              * Else number of wchars (excluding terminating L'\0')
              * written to dest is returned.
              * If len (here: 1) non-L'\0' wchars stored at dest,
              * src points to the next char to be converted.
              * If string is completely converted: src = NULL.
              */
             if (rc == 0) /* end-of-string */
                 break;
             if (rc < 0) { /* error */
                 src++;
                 goto subst;
             }
             if (!iswprint(wc))
                 goto subst;
         }
 #else
         src = mbstowc_internal(&wc, src);
         /* src is advanced to next mb char
          * wc == ERROR_WCHAR: invalid sequence is seen
          * else: wc is set
          */
         if (wc == ERROR_WCHAR) /* error */
             goto subst;
         if (wc == 0) /* end-of-string */
             break;
 #endif
         if (CONFIG_LAST_SUPPORTED_WCHAR && wc > CONFIG_LAST_SUPPORTED_WCHAR)
             goto subst;
         w = wcwidth(wc);
         if ((ENABLE_UNICODE_COMBINING_WCHARS && w < 0) /* non-printable wchar */
          || (!ENABLE_UNICODE_COMBINING_WCHARS && w <= 0)
          || (!ENABLE_UNICODE_WIDE_WCHARS && w > 1)
         ) {
  subst:
             wc = CONFIG_SUBST_WCHAR;
             w = 1;
         }
         width -= w;
         /* Note: if width == 0, we still may add more chars,
          * they may be zero-width or combining ones */
         if ((int)width < 0) {
             /* can't add this wc, string would become longer than width */
             width += w;
             break;
         }
         uni_count++;
         uni_width += w;
         dst = xrealloc(dst, dst_len + MB_CUR_MAX);
 #if ENABLE_UNICODE_USING_LOCALE
         {
             mbstate_t mbst = { 0 };
             dst_len += wcrtomb(&dst[dst_len], wc, &mbst);
         }
 #else
         dst_len += wcrtomb_internal(&dst[dst_len], wc);
 #endif
     }
     /* Pad to remaining width */
     if (flags & UNI_FLAG_PAD) {
         dst = xrealloc(dst, dst_len + width + 1);
         uni_count += width;
         uni_width += width;
         while ((int)--width >= 0) {
             dst[dst_len++] = ' ';
         }
     }
     if (!dst) /* for example, if input was "" */
         dst = xzalloc(1);
     dst[dst_len] = '\0';
     if (stats) {
         stats->byte_count = dst_len;
         stats->unicode_count = uni_count;
         stats->unicode_width = uni_width;
     }
     return dst;
 }
References uni_stat_t::byte_count, c, dst, ERROR_WCHAR, flags, iswprint(), MB_CUR_MAX, mbsrtowcs(), mbstowc_internal(), NULL, rc, src, uni_stat_t::unicode_count, UNICODE_ON, unicode_status, uni_stat_t::unicode_width, w, wcrtomb(), wcrtomb_internal(), wcwidth(), width, xmalloc, xrealloc, xstrndup(), and xzalloc().
Referenced by unicode_conv_to_printable(), and unicode_conv_to_printable_fixedwidth().
unicode_conv_to_printable_fixedwidth()
char* FAST_FUNC unicode_conv_to_printable_fixedwidth (const char * src, unsigned width)
Definition at line 1147 of file unicode.c.
 {
     return unicode_conv_to_printable2(/*stats:*/ NULL, src, width, UNI_FLAG_PAD);
 }
References NULL, src, unicode_conv_to_printable2(), and width.
Referenced by bb_progress_init(), cal_main(), and dumpleases_main().
unicode_strlen()
size_t FAST_FUNC unicode_strlen (const char * string)
Definition at line 996 of file unicode.c.
 {
     size_t width = mbstowcs(NULL, string, INT_MAX);
     if (width == (size_t)-1L)
         return strlen(string);
     return width;
 }
References INT_MAX, mbstowcs(), NULL, strlen, and width.
Referenced by expand_one_var(), and varvalue().
unicode_strwidth()
size_t FAST_FUNC unicode_strwidth (const char * string)
Definition at line 1004 of file unicode.c.
 {
     uni_stat_t uni_stat;
     printable_string2(&uni_stat, string);
     return uni_stat.unicode_width;
 }
References printable_string2(), and uni_stat_t::unicode_width.
wcrtomb()
size_t FAST_FUNC wcrtomb (char * s, wchar_t wc, mbstate_t *ps UNUSED_PARAM)
Definition at line 124 of file unicode.c.
 {
     if (unicode_status != UNICODE_ON) {
         *s = wc;
         return 1;
     }
     return wcrtomb_internal(s, wc);
 }
References s, UNICODE_ON, unicode_status, and wcrtomb_internal().
Referenced by c16rtomb(), c32rtomb(), sh_modcase(), ungetwc(), unicode_conv_to_printable2(), wcsnrtombs(), wcsrtombs(), and wctomb().
wcrtomb_internal()
static size_t wcrtomb_internal (char * s, wchar_t wc) static
Definition at line 88 of file unicode.c.
 {
     int n, i;
     uint32_t v = wc;
     if (v <= 0x7f) {
         *s = v;
         return 1;
     }
     /* RFC 3629 says that Unicode ends at 10FFFF,
      * but we cover entire 32 bits */
     /* 4000000-FFFFFFFF -> 111111tt 10tttttt 10zzzzzz 10zzyyyy 10yyyyxx 10xxxxxx */
     /* 200000-3FFFFFF -> 111110tt 10zzzzzz 10zzyyyy 10yyyyxx 10xxxxxx */
     /* 10000-1FFFFF -> 11110zzz 10zzyyyy 10yyyyxx 10xxxxxx */
     /* 800-FFFF -> 1110yyyy 10yyyyxx 10xxxxxx */
     /* 80-7FF -> 110yyyxx 10xxxxxx */
     /* How many bytes do we need? */
     n = 2;
     /* (0x80000000+ would result in n = 7, limiting n to 6) */
     while (v >= 0x800 && n < 6) {
         v >>= 5;
         n++;
     }
     /* Fill bytes n-1..1 */
     i = n;
     while (--i) {
         s[i] = (wc & 0x3f) | 0x80;
         wc >>= 6;
     }
     /* Fill byte 0 */
     s[0] = wc | (uint8_t)(0x3f00 >> n);
     return n;
 }
References i, n, and s.
Referenced by unicode_conv_to_printable2(), wcrtomb(), and wcstombs().
wcstombs()
size_t FAST_FUNC wcstombs (char * dest, const wchar_t * src, size_t n)
Definition at line 133 of file unicode.c.
 {
     size_t org_n = n;
     if (unicode_status != UNICODE_ON) {
         while (n) {
             wchar_t c = *src++;
             *dest++ = c;
             if (c == 0)
                 break;
             n--;
         }
         return org_n - n;
     }
     while (n >= MB_CUR_MAX) {
         wchar_t wc = *src++;
         size_t len = wcrtomb_internal(dest, wc);
         if (wc == L'\0')
             return org_n - n;
         dest += len;
         n -= len;
     }
     while (n) {
         char tbuf[MB_CUR_MAX];
         wchar_t wc = *src++;
         size_t len = wcrtomb_internal(tbuf, wc);
         if (len > n)
             break;
         memcpy(dest, tbuf, len);
         if (wc == L'\0')
             return org_n - n;
         dest += len;
         n -= len;
     }
     return org_n - n;
 }
References c, L, len, MB_CUR_MAX, memcpy, n, src, UNICODE_ON, unicode_status, and wcrtomb_internal().
Referenced by cutchars(), and rev_main().
wcwidth()
int FAST_FUNC wcwidth (unsigned ucs)
Definition at line 454 of file unicode.c.
 {
 # if CONFIG_LAST_SUPPORTED_WCHAR >= 0x300
     /* sorted list of non-overlapping intervals of non-spacing characters */
     /* generated by "uniset +cat=Me +cat=Mn +cat=Cf -00AD +1160-11FF +200B c" */
 #  define BIG_(a,b) { a, b },
 #  define PAIR(a,b)
 #  define ARRAY /* PAIR if < 0x4000 and no more than 4 chars big */ \
         BIG_(0x0300, 0x036F) \
         PAIR(0x0483, 0x0486) \
         PAIR(0x0488, 0x0489) \
         BIG_(0x0591, 0x05BD) \
         PAIR(0x05BF, 0x05BF) \
         PAIR(0x05C1, 0x05C2) \
         PAIR(0x05C4, 0x05C5) \
         PAIR(0x05C7, 0x05C7) \
         PAIR(0x0600, 0x0603) \
         BIG_(0x0610, 0x0615) \
         BIG_(0x064B, 0x065E) \
         PAIR(0x0670, 0x0670) \
         BIG_(0x06D6, 0x06E4) \
         PAIR(0x06E7, 0x06E8) \
         PAIR(0x06EA, 0x06ED) \
         PAIR(0x070F, 0x070F) \
         PAIR(0x0711, 0x0711) \
         BIG_(0x0730, 0x074A) \
         BIG_(0x07A6, 0x07B0) \
         BIG_(0x07EB, 0x07F3) \
         PAIR(0x0901, 0x0902) \
         PAIR(0x093C, 0x093C) \
         BIG_(0x0941, 0x0948) \
         PAIR(0x094D, 0x094D) \
         PAIR(0x0951, 0x0954) \
         PAIR(0x0962, 0x0963) \
         PAIR(0x0981, 0x0981) \
         PAIR(0x09BC, 0x09BC) \
         PAIR(0x09C1, 0x09C4) \
         PAIR(0x09CD, 0x09CD) \
         PAIR(0x09E2, 0x09E3) \
         PAIR(0x0A01, 0x0A02) \
         PAIR(0x0A3C, 0x0A3C) \
         PAIR(0x0A41, 0x0A42) \
         PAIR(0x0A47, 0x0A48) \
         PAIR(0x0A4B, 0x0A4D) \
         PAIR(0x0A70, 0x0A71) \
         PAIR(0x0A81, 0x0A82) \
         PAIR(0x0ABC, 0x0ABC) \
         BIG_(0x0AC1, 0x0AC5) \
         PAIR(0x0AC7, 0x0AC8) \
         PAIR(0x0ACD, 0x0ACD) \
         PAIR(0x0AE2, 0x0AE3) \
         PAIR(0x0B01, 0x0B01) \
         PAIR(0x0B3C, 0x0B3C) \
         PAIR(0x0B3F, 0x0B3F) \
         PAIR(0x0B41, 0x0B43) \
         PAIR(0x0B4D, 0x0B4D) \
         PAIR(0x0B56, 0x0B56) \
         PAIR(0x0B82, 0x0B82) \
         PAIR(0x0BC0, 0x0BC0) \
         PAIR(0x0BCD, 0x0BCD) \
         PAIR(0x0C3E, 0x0C40) \
         PAIR(0x0C46, 0x0C48) \
         PAIR(0x0C4A, 0x0C4D) \
         PAIR(0x0C55, 0x0C56) \
         PAIR(0x0CBC, 0x0CBC) \
         PAIR(0x0CBF, 0x0CBF) \
         PAIR(0x0CC6, 0x0CC6) \
         PAIR(0x0CCC, 0x0CCD) \
         PAIR(0x0CE2, 0x0CE3) \
         PAIR(0x0D41, 0x0D43) \
         PAIR(0x0D4D, 0x0D4D) \
         PAIR(0x0DCA, 0x0DCA) \
         PAIR(0x0DD2, 0x0DD4) \
         PAIR(0x0DD6, 0x0DD6) \
         PAIR(0x0E31, 0x0E31) \
         BIG_(0x0E34, 0x0E3A) \
         BIG_(0x0E47, 0x0E4E) \
         PAIR(0x0EB1, 0x0EB1) \
         BIG_(0x0EB4, 0x0EB9) \
         PAIR(0x0EBB, 0x0EBC) \
         BIG_(0x0EC8, 0x0ECD) \
         PAIR(0x0F18, 0x0F19) \
         PAIR(0x0F35, 0x0F35) \
         PAIR(0x0F37, 0x0F37) \
         PAIR(0x0F39, 0x0F39) \
         BIG_(0x0F71, 0x0F7E) \
         BIG_(0x0F80, 0x0F84) \
         PAIR(0x0F86, 0x0F87) \
         PAIR(0x0FC6, 0x0FC6) \
         BIG_(0x0F90, 0x0F97) \
         BIG_(0x0F99, 0x0FBC) \
         PAIR(0x102D, 0x1030) \
         PAIR(0x1032, 0x1032) \
         PAIR(0x1036, 0x1037) \
         PAIR(0x1039, 0x1039) \
         PAIR(0x1058, 0x1059) \
         BIG_(0x1160, 0x11FF) \
         PAIR(0x135F, 0x135F) \
         PAIR(0x1712, 0x1714) \
         PAIR(0x1732, 0x1734) \
         PAIR(0x1752, 0x1753) \
         PAIR(0x1772, 0x1773) \
         PAIR(0x17B4, 0x17B5) \
         BIG_(0x17B7, 0x17BD) \
         PAIR(0x17C6, 0x17C6) \
         BIG_(0x17C9, 0x17D3) \
         PAIR(0x17DD, 0x17DD) \
         PAIR(0x180B, 0x180D) \
         PAIR(0x18A9, 0x18A9) \
         PAIR(0x1920, 0x1922) \
         PAIR(0x1927, 0x1928) \
         PAIR(0x1932, 0x1932) \
         PAIR(0x1939, 0x193B) \
         PAIR(0x1A17, 0x1A18) \
         PAIR(0x1B00, 0x1B03) \
         PAIR(0x1B34, 0x1B34) \
         BIG_(0x1B36, 0x1B3A) \
         PAIR(0x1B3C, 0x1B3C) \
         PAIR(0x1B42, 0x1B42) \
         BIG_(0x1B6B, 0x1B73) \
         BIG_(0x1DC0, 0x1DCA) \
         PAIR(0x1DFE, 0x1DFF) \
         BIG_(0x200B, 0x200F) \
         BIG_(0x202A, 0x202E) \
         PAIR(0x2060, 0x2063) \
         BIG_(0x206A, 0x206F) \
         BIG_(0x20D0, 0x20EF) \
         BIG_(0x302A, 0x302F) \
         PAIR(0x3099, 0x309A) \
         /* Too big to be packed in PAIRs: */ \
         BIG_(0xA806, 0xA806) \
         BIG_(0xA80B, 0xA80B) \
         BIG_(0xA825, 0xA826) \
         BIG_(0xFB1E, 0xFB1E) \
         BIG_(0xFE00, 0xFE0F) \
         BIG_(0xFE20, 0xFE23) \
         BIG_(0xFEFF, 0xFEFF) \
         BIG_(0xFFF9, 0xFFFB)
     static const struct interval combining[] ALIGN4 = { ARRAY };
 #  undef BIG_
 #  undef PAIR
 #  define BIG_(a,b)
 #  define PAIR(a,b) (a << 2) | (b-a),
     static const uint16_t combining1[] ALIGN2 = { ARRAY };
 #  undef BIG_
 #  undef PAIR
 #  define BIG_(a,b) char big_##a[b < 0x4000 && b-a <= 3 ? -1 : 1];
 #  define PAIR(a,b) char pair##a[b >= 0x4000 || b-a > 3 ? -1 : 1];
     struct CHECK { ARRAY };
 #  undef BIG_
 #  undef PAIR
 #  undef ARRAY
 # endif
     if (ucs == 0)
         return 0;
     /* Test for 8-bit control characters (00-1f, 80-9f, 7f) */
     if ((ucs & ~0x80) < 0x20 || ucs == 0x7f)
         return -1;
     /* Quick abort if it is an obviously invalid char */
     if (ucs > CONFIG_LAST_SUPPORTED_WCHAR)
         return -1;
     /* Optimization: no combining chars below 0x300 */
     if (CONFIG_LAST_SUPPORTED_WCHAR < 0x300 || ucs < 0x300)
         return 1;
 # if CONFIG_LAST_SUPPORTED_WCHAR >= 0x300
     /* Binary search in table of non-spacing characters */
     if (in_interval_table(ucs, combining, ARRAY_SIZE(combining) - 1))
         return 0;
     if (in_uint16_table(ucs, combining1, ARRAY_SIZE(combining1) - 1))
         return 0;
     /* Optimization: all chars below 0x1100 are not double-width */
     if (CONFIG_LAST_SUPPORTED_WCHAR < 0x1100 || ucs < 0x1100)
         return 1;
 #  if CONFIG_LAST_SUPPORTED_WCHAR >= 0x1100
     /* Invalid code points: */
     /* High (d800..dbff) and low (dc00..dfff) surrogates (valid only in UTF16) */
     /* Private Use Area (e000..f8ff) */
     /* Noncharacters fdd0..fdef */
     if ((CONFIG_LAST_SUPPORTED_WCHAR >= 0xd800 && ucs >= 0xd800 && ucs <= 0xf8ff)
      || (CONFIG_LAST_SUPPORTED_WCHAR >= 0xfdd0 && ucs >= 0xfdd0 && ucs <= 0xfdef)
     ) {
         return -1;
     }
     /* 0xfffe and 0xffff in every plane are invalid */
     if (CONFIG_LAST_SUPPORTED_WCHAR >= 0xfffe && ((ucs & 0xfffe) == 0xfffe)) {
         return -1;
     }
 #   if CONFIG_LAST_SUPPORTED_WCHAR >= 0x10000
     if (ucs >= 0x10000) {
         /* Combining chars in Supplementary Multilingual Plane 0x1xxxx */
         static const struct interval combining0x10000[] ALIGN4 = {
             { 0x0A01, 0x0A03 }, { 0x0A05, 0x0A06 }, { 0x0A0C, 0x0A0F },
             { 0x0A38, 0x0A3A }, { 0x0A3F, 0x0A3F }, { 0xD167, 0xD169 },
             { 0xD173, 0xD182 }, { 0xD185, 0xD18B }, { 0xD1AA, 0xD1AD },
             { 0xD242, 0xD244 }
         };
         /* Binary search in table of non-spacing characters in Supplementary Multilingual Plane */
         if (in_interval_table(ucs ^ 0x10000, combining0x10000, ARRAY_SIZE(combining0x10000) - 1))
             return 0;
         /* Check a few non-spacing chars in Supplementary Special-purpose Plane 0xExxxx */
         if (CONFIG_LAST_SUPPORTED_WCHAR >= 0xE0001
          && (  ucs == 0xE0001
             || (ucs >= 0xE0020 && ucs <= 0xE007F)
             || (ucs >= 0xE0100 && ucs <= 0xE01EF)
             )
         ) {
             return 0;
         }
     }
 #   endif
     /* If we arrive here, ucs is not a combining or C0/C1 control character.
      * Check whether it's 1 char or 2-shar wide.
      */
     return 1 +
         (  (/*ucs >= 0x1100 &&*/ ucs <= 0x115f) /* Hangul Jamo init. consonants */
         || ucs == 0x2329 /* left-pointing angle bracket; also CJK punct. char */
         || ucs == 0x232a /* right-pointing angle bracket; also CJK punct. char */
 #   if CONFIG_LAST_SUPPORTED_WCHAR >= 0x2e80
         || (ucs >= 0x2e80 && ucs <= 0xa4cf && ucs != 0x303f) /* CJK ... Yi */
 #   endif
 #   if CONFIG_LAST_SUPPORTED_WCHAR >= 0xac00
         || (ucs >= 0xac00 && ucs <= 0xd7a3) /* Hangul Syllables */
 #   endif
 #   if CONFIG_LAST_SUPPORTED_WCHAR >= 0xf900
         || (ucs >= 0xf900 && ucs <= 0xfaff) /* CJK Compatibility Ideographs */
         || (ucs >= 0xfe10 && ucs <= 0xfe19) /* Vertical forms */
         || (ucs >= 0xfe30 && ucs <= 0xfe6f) /* CJK Compatibility Forms */
         || (ucs >= 0xff00 && ucs <= 0xff60) /* Fullwidth Forms */
         || (ucs >= 0xffe0 && ucs <= 0xffe6)
 #   endif
 #   if CONFIG_LAST_SUPPORTED_WCHAR >= 0x20000
         || ((ucs >> 17) == (2 >> 1)) /* 20000..3ffff: Supplementary and Tertiary Ideographic Planes */
 #   endif
         );
 #  endif /* >= 0x1100 */
 # endif /* >= 0x300 */
 }
References ALIGN2, ALIGN4, and ARRAY_SIZE.
Referenced by unicode_conv_to_printable2(), and wcswidth().
Variable Documentation
unicode_status
uint8_t unicode_status
Definition at line 14 of file unicode.c.
Referenced by adjust_column(), mbstowcs(), tree_print(), unicode_conv_to_printable2(), varvalue(), wc_main(), wcrtomb(), and wcstombs().