Fennix: Userspace/musl/arch/i386/bits/io.h File Reference
io.h File Reference
Functions
static __inline void outb (unsigned char __val, unsigned short __port)
static __inline void outw (unsigned short __val, unsigned short __port)
static __inline void outl (unsigned int __val, unsigned short __port)
static __inline unsigned char inb (unsigned short __port)
static __inline unsigned short inw (unsigned short __port)
static __inline unsigned int inl (unsigned short __port)
static __inline void outsb (unsigned short __port, const void *__buf, unsigned long __n)
static __inline void outsw (unsigned short __port, const void *__buf, unsigned long __n)
static __inline void outsl (unsigned short __port, const void *__buf, unsigned long __n)
static __inline void insb (unsigned short __port, void *__buf, unsigned long __n)
static __inline void insw (unsigned short __port, void *__buf, unsigned long __n)
static __inline void insl (unsigned short __port, void *__buf, unsigned long __n)
Function Documentation
inb()
static __inline unsigned char inb (unsigned short __port) static
Definition at line 16 of file io.h.
 {
     unsigned char __val;
     __asm__ volatile ("inb %1,%0" : "=a" (__val) : "dN" (__port));
     return __val;
 }
References __asm__().
Referenced by AudioCodec97::CallbackHandler(), PS2Keyboard::CallbackHandler(), CrashHandler::CrashKeyboardDriver::CrashKeyboardDriver(), iconv(), AudioCodec97::InterruptCallback(), PS2Keyboard::InterruptCallback(), PS2Mouse::InterruptCallback(), VMwareMouse::InterruptCallback(), AdvancedTechnologyAttachment::IsATAPresent(), Main(), Interrupts::MainInterruptHandler(), PIC::PIT::PerformSleep(), PS2Mouse::Read(), VMwareMouse::Read(), Time::ReadClock(), Power::Power::Reboot(), CrashHandler::UserInput(), PS2Mouse::WaitRead(), VMwareMouse::WaitRead(), PS2Mouse::WaitWrite(), and VMwareMouse::WaitWrite().
inl()
static __inline unsigned int inl (unsigned short __port) static
Definition at line 30 of file io.h.
 {
     unsigned int __val;
     __asm__ volatile ("inl %1,%0" : "=a" (__val) : "dN" (__port));
     return __val;
 }
References __asm__().
Referenced by AudioCodec97::CallbackHandler().
insb()
static __inline void insb (unsigned short __port, void * __buf, unsigned long __n) static
Definition at line 58 of file io.h.
 {
     __asm__ volatile ("cld; rep; insb"
               : "+D" (__buf), "+c" (__n)
               : "d" (__port));
 }
References __asm__().
insl()
static __inline void insl (unsigned short __port, void * __buf, unsigned long __n) static
Definition at line 72 of file io.h.
 {
     __asm__ volatile ("cld; rep; insl"
               : "+D" (__buf), "+c" (__n)
               : "d" (__port));
 }
References __asm__().
insw()
static __inline void insw (unsigned short __port, void * __buf, unsigned long __n) static
Definition at line 65 of file io.h.
 {
     __asm__ volatile ("cld; rep; insw"
               : "+D" (__buf), "+c" (__n)
               : "d" (__port));
 }
References __asm__().
inw()
static __inline unsigned short inw (unsigned short __port) static
Definition at line 23 of file io.h.
 {
     unsigned short __val;
     __asm__ volatile ("inw %1,%0" : "=a" (__val) : "dN" (__port));
     return __val;
 }
References __asm__().
Referenced by ACPI::ACPI::ACPI(), AudioCodec97::CallbackHandler(), ACPI::DSDT::DSDT(), ACPI::if(), AudioCodec97::InterruptCallback(), and ACPI::DSDT::Shutdown().
outb()
static __inline void outb (unsigned char __val, unsigned short __port) static
Definition at line 1 of file io.h.
 {
     __asm__ volatile ("outb %0,%1" : : "a" (__val), "dN" (__port));
 }
References __asm__().
Referenced by ACPI::ACPI::ACPI(), APIC::APIC::APIC(), AudioCodec97::CallbackHandler(), PS2Keyboard::CallbackHandler(), PS2Mouse::CallbackHandler(), VMwareMouse::CallbackHandler(), CrashHandler::CrashKeyboardDriver::CrashKeyboardDriver(), iconv(), InterruptDescriptorTable::Init(), AudioCodec97::InterruptCallback(), AdvancedTechnologyAttachment::IsATAPresent(), PIC::PIC::Mask(), PIC::PIC::PIC(), PIC::PIT::PrepareSleep(), Time::ReadClock(), ACPI::DSDT::Reboot(), Power::Power::Reboot(), PIC::PIC::SendEOI(), PIC::PIC::Unmask(), PS2Mouse::Write(), VMwareMouse::Write(), and PIC::PIC::~PIC().
outl()
static __inline void outl (unsigned int __val, unsigned short __port) static
Definition at line 11 of file io.h.
 {
     __asm__ volatile ("outl %0,%1" : : "a" (__val), "dN" (__port));
 }
References __asm__().
Referenced by AudioCodec97::CallbackHandler(), and Power::Power::Shutdown().
outsb()
static __inline void outsb (unsigned short __port, const void * __buf, unsigned long __n) static
Definition at line 37 of file io.h.
 {
     __asm__ volatile ("cld; rep; outsb"
               : "+S" (__buf), "+c" (__n)
               : "d" (__port));
 }
References __asm__().
outsl()
static __inline void outsl (unsigned short __port, const void * __buf, unsigned long __n) static
Definition at line 51 of file io.h.
 {
     __asm__ volatile ("cld; rep; outsl"
               : "+S" (__buf), "+c"(__n)
               : "d" (__port));
 }
References __asm__().
outsw()
static __inline void outsw (unsigned short __port, const void * __buf, unsigned long __n) static
Definition at line 44 of file io.h.
 {
     __asm__ volatile ("cld; rep; outsw"
               : "+S" (__buf), "+c" (__n)
               : "d" (__port));
 }
References __asm__().
outw()
static __inline void outw (unsigned short __val, unsigned short __port) static
Definition at line 6 of file io.h.
 {
     __asm__ volatile ("outw %0,%1" : : "a" (__val), "dN" (__port));
 }
References __asm__().
Referenced by AudioCodec97::CallbackHandler(), ACPI::DSDT::DSDT(), ACPI::if(), AudioCodec97::InterruptCallback(), and ACPI::DSDT::Shutdown().