Fennix Userspace: Userspace/musl/src/unistd/getlogin_r.c File Reference
getlogin_r.c File Reference
#include <unistd.h>
#include <string.h>
#include <errno.h>
Functions
int getlogin_r (char *name, size_t size)
Function Documentation
getlogin_r()
int getlogin_r (char * name, size_t size)
Definition at line 5 of file getlogin_r.c.
 {
     char *logname = getlogin();
     if (!logname) return ENXIO; /* or...? */
     if (strlen(logname) >= size) return ERANGE;
     strcpy(name, logname);
     return 0;
 }
References ENXIO, ERANGE, getlogin(), name, size, strcpy(), and strlen().