Fennix: Userspace/mlibc/options/posix/generic/fcntl-stubs.cpp File Reference
fcntl-stubs.cpp File Reference
#include <errno.h>
#include <bits/ensure.h>
#include <fcntl.h>
#include <stdarg.h>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
Functions
int creat (const char *pathname, mode_t mode)
int fcntl (int fd, int command,...)
int openat (int dirfd, const char *pathname, int flags,...)
int posix_fadvise (int fd, off_t offset, off_t length, int advice)
int posix_fallocate (int fd, off_t offset, off_t size)
int name_to_handle_at (int, const char *, struct file_handle *, int *, int)
int open_by_handle_at (int, struct file_handle *, int)
int open (const char *pathname, int flags,...)
Function Documentation
creat()
int creat (const char * pathname, mode_t mode)
Definition at line 10 of file fcntl-stubs.cpp.
{
     return open(pathname, O_CREAT|O_WRONLY|O_TRUNC, mode);
 }
References O_CREAT, O_TRUNC, O_WRONLY, and open().
fcntl()
int fcntl (int fd, int command, ...)
Definition at line 14 of file fcntl-stubs.cpp.
{
     va_list args;
     va_start(args, command);
     int result;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_fcntl, -1);
     if(int e = mlibc::sys_fcntl(fd, command, args, &result); e) {
         errno = e;
         return -1;
     }
     va_end(args);
     return result;
 }
References args, errno, MLIBC_CHECK_OR_ENOSYS, mlibc::sys_fcntl(), va_end(), and va_start().
Referenced by __aio_get_queue(), accept4(), add_undo_redirect(), child(), do_redirection_internal(), do_wordexp(), dup2(), fdopen(), fdopendir(), getflags(), getmaxfd(), here_document_to_fd(), io_thread_func(), isastream(), lockf(), main(), move_to_high_fd(), popen(), redir_special_open(), rl_gather_tyi(), run_test(), setone(), sh_unset_nodelay_mode(), sh_validfd(), undoablefd(), and we_askshell().
name_to_handle_at()
int name_to_handle_at (int , const char * , struct file_handle * , int * , int)
Definition at line 65 of file fcntl-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
open()
int open (const char * pathname, int flags, ...)
Definition at line 75 of file fcntl-stubs.cpp.
{
     mode_t mode = 0;
     if ((flags & O_CREAT) || (flags & O_TMPFILE)) {
         va_list args;
         va_start(args, flags);
         mode = va_arg(args, mode_t);
         va_end(args);
     }
     int fd;
     if(int e = mlibc::sys_open(pathname, flags, mode, &fd); e) {
         errno = e;
         return -1;
     }
     return fd;
 }
References args, errno, flags, O_CREAT, O_TMPFILE, mlibc::sys_open(), va_arg, va_end(), and va_start().
Referenced by __dls3(), __mkostemps(), _evalfile(), _nl_load_domain(), _rl_read_file(), _vsyslog(), async_redirect_stdin(), cat_main(), check_dev_tty(), child(), creat(), cutfile(), daemon(), do_nftw(), extract_info(), update-syscall-list::fetch_kernel(), fmtmsg(), getpass(), getrandom(), getspnam_r(), here_document_to_fd(), history_do_write(), history_truncate_file(), initialize_job_control(), load_library(), main(), update-syscall-list::main(), noclobber_open(), open_redir_file(), open_shell_script(), opendir(), openpty(), parse_comsub(), parse_matched_pair(), path_open(), posix_openpt(), pthread_getname_np(), pthread_setname_np(), read_history_range(), redir_open(), redir_special_open(), sem_open(), sh_mktmpfd(), shm_open(), skip_matched_pair(), skip_to_delim(), tee_builtin(), tgetent(), and unquoted_glob_pattern_p().
open_by_handle_at()
int open_by_handle_at (int , struct file_handle * , int)
Definition at line 70 of file fcntl-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
openat()
int openat (int dirfd, const char * pathname, int flags, ...)
Definition at line 27 of file fcntl-stubs.cpp.
{
     va_list args;
     va_start(args, flags);
     mode_t mode = 0;
     int fd;
     if((flags & (O_CREAT | O_TMPFILE)))
         mode = va_arg(args, mode_t);
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_openat, -1);
     if(int e = mlibc::sys_openat(dirfd, pathname, flags, mode, &fd); e) {
         errno = e;
         return -1;
     }
     va_end(args);
     return fd;
 }
References args, dirfd, errno, flags, MLIBC_CHECK_OR_ENOSYS, O_CREAT, O_TMPFILE, mlibc::sys_openat(), va_arg, va_end(), and va_start().
posix_fadvise()
int posix_fadvise (int fd, off_t offset, off_t length, int advice)
Definition at line 45 of file fcntl-stubs.cpp.
{
     if(!mlibc::sys_fadvise) {
         mlibc::infoLogger() << "mlibc: fadvise() ignored due to missing sysdep" << frg::endlog;
         return 0;
     }
     // posix_fadvise() returns an error instead of setting errno.
     return mlibc::sys_fadvise(fd, offset, length, advice);
 }
References mlibc::infoLogger, mlibc::length, offset, and mlibc::sys_fadvise().
posix_fallocate()
int posix_fallocate (int fd, off_t offset, off_t size)
Definition at line 55 of file fcntl-stubs.cpp.
{
     // posix_fallocate() returns an error instead of setting errno.
     if(!mlibc::sys_fallocate) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     return mlibc::sys_fallocate(fd, offset, size);
 }
References ENOSYS, MLIBC_MISSING_SYSDEP, offset, size, and mlibc::sys_fallocate().