Fennix: Kernel/tasking/thread.cpp File Reference
thread.cpp File Reference
#include <task.hpp>
#include <filesystem/ioctl.hpp>
#include <dumper.hpp>
#include <convert.h>
#include <lock.hpp>
#include <printf.h>
#include <smp.hpp>
#include <io.h>
#include "../kernel.h"
Namespaces
Tasking
Macros
#define tskdbg(m, ...)
Functions
void ThreadDoExit ()
Tasking::__no_sanitize ("undefined") void TCB
Macro Definition Documentation
tskdbg
#define tskdbg (m, ...)
Definition at line 46 of file thread.cpp.
Function Documentation
ThreadDoExit()
void ThreadDoExit ()
Definition at line 50 of file thread.cpp.
 {
     CPUData *CPUData = GetCurrentCPU();
     Tasking::TCB *CurrentThread = CPUData->CurrentThread.load();
     CurrentThread->State = Tasking::TaskState::Terminated;
     debug("\"%s\"(%d) exited with code: %#lx",
           CurrentThread->Name,
           CurrentThread->ID,
           CurrentThread->ExitCode);
     CPU::Halt(true);
 }
References CurrentThread, CPUData::CurrentThread, debug, GetCurrentCPU(), Halt(), and Tasking::Terminated.
Referenced by Tasking::TCB::TCB().