Fennix: Module Namespace Reference
Module Namespace Reference
Data Structures
struct ModuleFile
struct BuiltInModuleInfo
class ModuleInterruptHook
class Module
Enumerations
enum ModuleCode {
ERROR , OK , NOT_IMPLEMENTED , NOT_FOUND ,
NOT_READY , NOT_AVAILABLE , NOT_AUTHORIZED , NOT_VALID ,
NOT_ACCEPTED , INVALID_PCI_BAR , INVALID_KERNEL_API , INVALID_MEMORY_ALLOCATION ,
INVALID_DATA , DEVICE_NOT_SUPPORTED , SYSTEM_NOT_SUPPORTED , KERNEL_API_VERSION_NOT_SUPPORTED ,
INVALID_FEX_HEADER , INVALID_MODULE_DATA , NOT_MODULE , MODULE_RETURNED_ERROR ,
UNKNOWN_MODULE_TYPE , UNKNOWN_MODULE_BIND_TYPE , PCI_DEVICE_NOT_FOUND , MODULE_CONFLICT
}
Functions
if (!this->Enabled)
if (!Handle.InterruptCallback)
int void (Handle.InterruptCallback))(&regs)
UNUSED (Frame)
Variables
CPURegisters regs
Enumeration Type Documentation
ModuleCode
enum Module::ModuleCode
Enumerator
ERROR
OK
NOT_IMPLEMENTED
NOT_FOUND
NOT_READY
NOT_AVAILABLE
NOT_AUTHORIZED
NOT_VALID
NOT_ACCEPTED
INVALID_PCI_BAR
INVALID_KERNEL_API
INVALID_MEMORY_ALLOCATION
INVALID_DATA
DEVICE_NOT_SUPPORTED
SYSTEM_NOT_SUPPORTED
KERNEL_API_VERSION_NOT_SUPPORTED
INVALID_FEX_HEADER
INVALID_MODULE_DATA
NOT_MODULE
MODULE_RETURNED_ERROR
UNKNOWN_MODULE_TYPE
UNKNOWN_MODULE_BIND_TYPE
PCI_DEVICE_NOT_FOUND
MODULE_CONFLICT
Definition at line 33 of file module.hpp.
     {
         /* This must be the same as in mapi.hpp ModuleReturnCode */
         ERROR,
         OK,
         NOT_IMPLEMENTED,
         NOT_FOUND,
         NOT_READY,
         NOT_AVAILABLE,
         NOT_AUTHORIZED,
         NOT_VALID,
         NOT_ACCEPTED,
         INVALID_PCI_BAR,
         INVALID_KERNEL_API,
         INVALID_MEMORY_ALLOCATION,
         INVALID_DATA,
         DEVICE_NOT_SUPPORTED,
         SYSTEM_NOT_SUPPORTED,
         KERNEL_API_VERSION_NOT_SUPPORTED,
         /* End of module-only errors */
         INVALID_FEX_HEADER,
         INVALID_MODULE_DATA,
         NOT_MODULE,
         MODULE_RETURNED_ERROR,
         UNKNOWN_MODULE_TYPE,
         UNKNOWN_MODULE_BIND_TYPE,
         PCI_DEVICE_NOT_FOUND,
         MODULE_CONFLICT
     };
Function Documentation
if() [1/2]
Module::if (!Handle. InterruptCallback)
Definition at line 278 of file module.cpp.
         {
 #if defined(a86)
             uint64_t IntNum = Frame->InterruptNumber - 32;
 #elif defined(aa64)
             uint64_t IntNum = Frame->InterruptNumber;
 #endif
             warn("Interrupt callback for %ld is not set for module %ld!",
                  IntNum, Handle.modUniqueID);
             return;
         }
References CrashHandler::Handle(), and warn.
if() [2/2]
Module::if (!this-> Enabled)
Definition at line 270 of file module.cpp.
         {
             debug("Interrupt hook is not enabled (%#lx, IRQ%d)",
                   Frame->InterruptNumber,
                   Frame->InterruptNumber - 32);
             return;
         }
References debug.
UNUSED()
Module::UNUSED (Frame)
Referenced by Module::Module::ModuleLoadBindInput(), and Module::Module::ModuleLoadBindProcess().
void()
int Module::void (Handle. InterruptCallback) &
Referenced by __funcs_on_exit(), __funcs_on_quick_exit(), __libc_exit_fini(), __pthread_exit(), __pthread_tsd_run_dtors(), _rl_reset_locale(), add_history(), botch(), call(), changepath(), decode_one_format(), decode_prompt_string(), do_init_fini(), dup2(), execute_command_internal(), get_stat_atime(), getcwd(), glob_vector(), VMwareMouse::InterruptCallback(), libc_exit_fini(), libc_start_init(), main(), mindist(), Xalloc::Block::operator new(), parse_params(), Tasking::PCB::PCB(), postprocess_matches(), putchar_wrapper(), reader_loop(), recv_from_to(), run_command(), send_to_from(), set_winsize(), sha_crypt(), start(), stty_main(), xbotch(), and yydestruct().
Variable Documentation
regs
CPURegisters Module::regs
Definition at line 289 of file module.cpp.