Fennix Userspace: Userspace/apps/base/busybox/libbb/vfork_daemon_rexec.c File Reference
vfork_daemon_rexec.c File Reference
#include "busybox.h"
#include "NUM_APPLETS.h"
Macros
#define NOFORK_SUPPORT ((NUM_APPLETS > 1) && (ENABLE_FEATURE_PREFER_APPLETS || ENABLE_FEATURE_SH_NOFORK))
#define NOEXEC_SUPPORT ((NUM_APPLETS > 1) && (ENABLE_FEATURE_PREFER_APPLETS || ENABLE_FEATURE_SH_STANDALONE))
Functions
pid_t FAST_FUNC spawn (char **argv)
pid_t FAST_FUNC xspawn (char **argv)
int FAST_FUNC spawn_and_wait (char **argv)
void FAST_FUNC re_exec (char **argv)
pid_t FAST_FUNC fork_or_rexec (char **argv)
void FAST_FUNC bb_daemonize_or_rexec (int flags, char **argv)
void FAST_FUNC bb_sanitize_stdio (void)
Macro Definition Documentation
NOEXEC_SUPPORT
#define NOEXEC_SUPPORT ((NUM_APPLETS > 1) && (ENABLE_FEATURE_PREFER_APPLETS || ENABLE_FEATURE_SH_STANDALONE))
Definition at line 21 of file vfork_daemon_rexec.c.
NOFORK_SUPPORT
#define NOFORK_SUPPORT ((NUM_APPLETS > 1) && (ENABLE_FEATURE_PREFER_APPLETS || ENABLE_FEATURE_SH_NOFORK))
Definition at line 20 of file vfork_daemon_rexec.c.
Function Documentation
bb_daemonize_or_rexec()
void FAST_FUNC bb_daemonize_or_rexec (int flags, char ** argv)
Definition at line 280 of file vfork_daemon_rexec.c.
 {
     int fd;
     if (flags & DAEMON_CHDIR_ROOT)
         xchdir("/");
     fd = open(bb_dev_null, O_RDWR);
     if (fd < 0) {
         /* NB: we can be called as bb_sanitize_stdio() from init
          * or mdev, and there /dev/null may legitimately not (yet) exist!
          * Do not use xopen above, but obtain _ANY_ open descriptor,
          * even bogus one as below. */
         fd = xopen("/", O_RDONLY); /* don't believe this can fail */
     }
     if (flags & DAEMON_DEVNULL_STDIO) {
         xdup2(fd, 0);
         xdup2(fd, 1);
         xdup2(fd, 2);
     } else {
         /* have 0,1,2 open at least to /dev/null */
         while ((unsigned)fd < 2)
             fd = dup(fd);
     }
     if (!(flags & DAEMON_ONLY_SANITIZE)) {
         /* fflush_all(); - add it in fork_or_rexec() if necessary */
         if (fork_or_rexec(argv))
             _exit_SUCCESS(); /* parent */
         /* if daemonizing, detach from stdio & ctty */
         setsid();
         dup2(fd, 0);
         dup2(fd, 1);
         dup2(fd, 2);
 //      if (flags & DAEMON_DOUBLE_FORK) {
 //          /* On Linux, session leader can acquire ctty
 //           * unknowingly, by opening a tty.
 //           * Prevent this: stop being a session leader.
 //           */
 //          if (fork_or_rexec(argv))
 //              _exit_SUCCESS(); /* parent */
 //      }
     }
     while (fd > 2) {
         close(fd--);
         if (!(flags & DAEMON_CLOSE_EXTRA_FDS))
             return;
         /* else close everything after fd#2 */
     }
 }
References _exit_SUCCESS(), argv, bb_dev_null, close(), DAEMON_CHDIR_ROOT, DAEMON_CLOSE_EXTRA_FDS, DAEMON_DEVNULL_STDIO, DAEMON_ONLY_SANITIZE, dup(), dup2(), fd, flags, fork_or_rexec(), O_RDONLY, O_RDWR, open(), setsid(), xchdir(), xdup2(), and xopen().
Referenced by bb_sanitize_stdio().
bb_sanitize_stdio()
void FAST_FUNC bb_sanitize_stdio (void)
Definition at line 334 of file vfork_daemon_rexec.c.
 {
     bb_daemonize_or_rexec(DAEMON_ONLY_SANITIZE, NULL);
 }
References bb_daemonize_or_rexec(), DAEMON_ONLY_SANITIZE, and NULL.
Referenced by console_init(), inetd_main(), mdev_main(), script_main(), tcpudpsvd_main(), traceroute_init(), and udhcp_sp_setup().
fork_or_rexec()
pid_t FAST_FUNC fork_or_rexec (char ** argv)
Definition at line 261 of file vfork_daemon_rexec.c.
 {
     pid_t pid;
     /* Maybe we are already re-execed and come here again? */
     if (re_execed)
         return 0;
     /* fflush_all(); ? - so far all callers had no buffered output to flush */
     pid = xvfork();
     if (pid) /* parent */
         return pid;
     /* child - re-exec ourself */
     re_exec(argv);
 }
References argv, pid, re_exec(), re_execed, and xvfork.
Referenced by bb_daemonize_or_rexec(), bootchartd_main(), and setsid_main().
re_exec()
void FAST_FUNC re_exec (char ** argv)
Definition at line 252 of file vfork_daemon_rexec.c.
 {
     /* high-order bit of first char in argv[0] is a hidden
      * "we have (already) re-execed, don't do it again" flag */
     argv[0][0] |= 0x80;
     execv(bb_busybox_exec_path, argv);
     bb_perror_msg_and_die("can't execute '%s'", bb_busybox_exec_path);
 }
References argv, bb_perror_msg_and_die(), and execv().
Referenced by fork_or_rexec(), and mini_httpd_nommu().
spawn()
pid_t FAST_FUNC spawn (char ** argv)
Definition at line 176 of file vfork_daemon_rexec.c.
 {
     /* Compiler should not optimize stores here */
     volatile int failed;
     pid_t pid;
     fflush_all();
     /* Be nice to nommu machines. */
     failed = 0;
     pid = vfork();
     if (pid < 0) /* error */
         return pid;
     if (!pid) { /* child */
         /* This macro is ok - it doesn't do NOEXEC/NOFORK tricks */
         BB_EXECVP(argv[0], argv);
         /* We are (maybe) sharing a stack with blocked parent,
          * let parent know we failed and then exit to unblock parent
          * (but don't run atexit() stuff, which would screw up parent.)
          */
         failed = errno;
         /* mount, for example, does not want the message */
         /*bb_perror_msg("can't execute '%s'", argv[0]);*/
         _exit(111);
     }
     /* parent */
     /* Unfortunately, this is not reliable: according to standards
      * vfork() can be equivalent to fork() and we won't see value
      * of 'failed'.
      * Interested party can wait on pid and learn exit code.
      * If 111 - then it (most probably) failed to exec */
     if (failed) {
         safe_waitpid(pid, NULL, 0); /* prevent zombie */
         errno = failed;
         return -1;
     }
     return pid;
 }
References _exit(), argv, BB_EXECVP, errno, fflush_all(), NULL, pid, safe_waitpid(), and vfork().
Referenced by execute(), P_LoadThings(), process_event(), run_script(), runsvdir_main(), spawn_and_wait(), xargs_exec(), and xspawn().
spawn_and_wait()
int FAST_FUNC spawn_and_wait (char ** argv)
Definition at line 225 of file vfork_daemon_rexec.c.
 {
     int rc;
 #if ENABLE_FEATURE_PREFER_APPLETS && (NUM_APPLETS > 1)
     int a = find_applet_by_name(argv[0]);
     if (a >= 0) {
         if (APPLET_IS_NOFORK(a))
             return run_nofork_applet(a, argv);
 # if BB_MMU /* NOEXEC needs fork(), thus this is done only on MMU machines: */
         if (APPLET_IS_NOEXEC(a)) {
             fflush_all();
             rc = fork();
             if (rc) /* parent or error */
                 return wait4pid(rc);
             /* child */
             run_noexec_applet_and_exit(a, argv[0], argv);
         }
 # endif
     }
 #endif
     rc = spawn(argv);
     return wait4pid(rc);
 }
References APPLET_IS_NOEXEC, APPLET_IS_NOFORK, argv, fflush_all(), find_applet_by_name(), fork(), rc, run_noexec_applet_and_exit(), run_nofork_applet(), spawn(), and wait4pid().
Referenced by action_execute(), action_modload(), addgroup_wrapper(), d4_run_script(), d6_run_script(), flock_main(), inotifyd_main(), install_main(), mount_it_now(), run(), run_parts_main(), run_script(), singlemount(), uevent_main(), write_leases(), and xargs_exec().
xspawn()
pid_t FAST_FUNC xspawn (char ** argv)
Definition at line 217 of file vfork_daemon_rexec.c.
 {
     pid_t pid = spawn(argv);
     if (pid < 0)
         bb_simple_perror_msg_and_die(*argv);
     return pid;
 }
References argv, bb_simple_perror_msg_and_die(), pid, and spawn().