Fennix: Userspace/apps/base/busybox/libbb/bb_getsockname.c File Reference
bb_getsockname.c File Reference
#include "libbb.h"
Functions
int FAST_FUNC bb_getsockname (int sockfd, void *addr, socklen_t addrlen)
Function Documentation
bb_getsockname()
int FAST_FUNC bb_getsockname (int sockfd, void * addr, socklen_t addrlen)
Definition at line 11 of file bb_getsockname.c.
 {
     /* The usefullness of this function is that for getsockname(),
      * addrlen must go on stack (to _have_ an address to be passed),
      * but many callers do not need its modified value.
      * By using this shim, they can avoid unnecessary stack spillage.
      */
     return getsockname(sockfd, (struct sockaddr *)addr, &addrlen);
 }
References addr, getsockname(), and sockfd.
Referenced by get_address(), and xrtnl_open().