Fennix: Userspace/apps/base/busybox/scripts/kconfig/lxdialog/menubox.c File Reference
menubox.c File Reference
#include "dialog.h"
Macros
#define print_item(index, choice, selected)
Functions
static void do_print_item (WINDOW *win, const char *item, int choice, int selected, int hotkey)
static void print_arrows (WINDOW *win, int item_no, int scroll, int y, int x, int height)
static void print_buttons (WINDOW *win, int height, int width, int selected)
static void do_scroll (WINDOW *win, int *scroll, int n)
int dialog_menu (const char *title, const char *prompt, int height, int width, int menu_height, const char *current, int item_no, const char *const *items)
Variables
static int menu_width
static int item_x
Macro Definition Documentation
print_item
#define print_item (index, choice, selected)
Value:
do {\
    int hotkey = (items[(index) * 2][0] != ':'); \
    do_print_item(menu, items[(index) * 2 + 1], choice, selected, hotkey); \
} while (0)
Definition at line 101 of file menubox.c.
Function Documentation
dialog_menu()
int dialog_menu (const char * title, const char * prompt, int height, int width, int menu_height, const char * current, int item_no, const char *const * items)
Definition at line 181 of file menubox.c.
 {
     int i, j, x, y, box_x, box_y;
     int key = 0, button = 0, scroll = 0, choice = 0;
     int first_item =  0, max_choice;
     WINDOW *dialog, *menu;
     FILE *f;
     max_choice = MIN(menu_height, item_no);
     /* center dialog box on screen */
     x = (COLS - width) / 2;
     y = (LINES - height) / 2;
     draw_shadow(stdscr, y, x, height, width);
     dialog = newwin(height, width, y, x);
     keypad(dialog, TRUE);
     draw_box(dialog, 0, 0, height, width, dialog_attr, border_attr);
     wattrset(dialog, border_attr);
     mvwaddch(dialog, height - 3, 0, ACS_LTEE);
     for (i = 0; i < width - 2; i++)
         waddch(dialog, ACS_HLINE);
     wattrset(dialog, dialog_attr);
     wbkgdset(dialog, dialog_attr & A_COLOR);
     waddch(dialog, ACS_RTEE);
     print_title(dialog, title, width);
     wattrset(dialog, dialog_attr);
     print_autowrap(dialog, prompt, width - 2, 1, 3);
     menu_width = width - 6;
     box_y = height - menu_height - 5;
     box_x = (width - menu_width) / 2 - 1;
     /* create new window for the menu */
     menu = subwin(dialog, menu_height, menu_width,
               y + box_y + 1, x + box_x + 1);
     keypad(menu, TRUE);
     /* draw a box around the menu items */
     draw_box(dialog, box_y, box_x, menu_height + 2, menu_width + 2,
          menubox_border_attr, menubox_attr);
     item_x = (menu_width - 70) / 2;
     /* Set choice to default item */
     for (i = 0; i < item_no; i++)
         if (strcmp(current, items[i * 2]) == 0)
             choice = i;
     /* get the scroll info from the temp file */
     if ((f = fopen("lxdialog.scrltmp", "r")) != NULL) {
         if ((fscanf(f, "%d\n", &scroll) == 1) && (scroll <= choice) &&
             (scroll + max_choice > choice) && (scroll >= 0) &&
             (scroll + max_choice <= item_no)) {
             first_item = scroll;
             choice = choice - scroll;
             fclose(f);
         } else {
             scroll = 0;
             remove("lxdialog.scrltmp");
             fclose(f);
             f = NULL;
         }
     }
     if ((choice >= max_choice) || (f == NULL && choice >= max_choice / 2)) {
         if (choice >= item_no - max_choice / 2)
             scroll = first_item = item_no - max_choice;
         else
             scroll = first_item = choice - max_choice / 2;
         choice = choice - scroll;
     }
     /* Print the menu */
     for (i = 0; i < max_choice; i++) {
         print_item(first_item + i, i, i == choice);
     }
     wnoutrefresh(menu);
     print_arrows(dialog, item_no, scroll,
              box_y, box_x + item_x + 1, menu_height);
     print_buttons(dialog, height, width, 0);
     wmove(menu, choice, item_x + 1);
     wrefresh(menu);
     while (key != ESC) {
         key = wgetch(menu);
         if (key < 256 && isalpha(key))
             key = tolower(key);
         if (strchr("ynmh", key))
             i = max_choice;
         else {
             for (i = choice + 1; i < max_choice; i++) {
                 j = first_alpha(items[(scroll + i) * 2 + 1], "YyNnMmHh");
                 if (key == tolower(items[(scroll + i) * 2 + 1][j]))
                     break;
             }
             if (i == max_choice)
                 for (i = 0; i < max_choice; i++) {
                     j = first_alpha(items [(scroll + i) * 2 + 1], "YyNnMmHh");
                     if (key == tolower(items[(scroll + i) * 2 + 1][j]))
                         break;
                 }
         }
         if (i < max_choice ||
             key == KEY_UP || key == KEY_DOWN ||
             key == '-' || key == '+' ||
             key == KEY_PPAGE || key == KEY_NPAGE) {
             /* Remove highligt of current item */
             print_item(scroll + choice, choice, FALSE);
             if (key == KEY_UP || key == '-') {
                 if (choice < 2 && scroll) {
                     /* Scroll menu down */
                     do_scroll(menu, &scroll, -1);
                     print_item(scroll, 0, FALSE);
                 } else
                     choice = MAX(choice - 1, 0);
             } else if (key == KEY_DOWN || key == '+') {
                 print_item(scroll+choice, choice, FALSE);
                 if ((choice > max_choice - 3) &&
                     (scroll + max_choice < item_no)) {
                     /* Scroll menu up */
                     do_scroll(menu, &scroll, 1);
                     print_item(scroll+max_choice - 1,
                            max_choice - 1, FALSE);
                 } else
                     choice = MIN(choice + 1, max_choice - 1);
             } else if (key == KEY_PPAGE) {
                 scrollok(menu, TRUE);
                 for (i = 0; (i < max_choice); i++) {
                     if (scroll > 0) {
                         do_scroll(menu, &scroll, -1);
                         print_item(scroll, 0, FALSE);
                     } else {
                         if (choice > 0)
                             choice--;
                     }
                 }
             } else if (key == KEY_NPAGE) {
                 for (i = 0; (i < max_choice); i++) {
                     if (scroll + max_choice < item_no) {
                         do_scroll(menu, &scroll, 1);
                         print_item(scroll+max_choice-1,
                                max_choice - 1, FALSE);
                     } else {
                         if (choice + 1 < max_choice)
                             choice++;
                     }
                 }
             } else
                 choice = i;
             print_item(scroll + choice, choice, TRUE);
             print_arrows(dialog, item_no, scroll,
                      box_y, box_x + item_x + 1, menu_height);
             wnoutrefresh(dialog);
             wrefresh(menu);
             continue;   /* wait for another key press */
         }
         switch (key) {
         case KEY_LEFT:
         case TAB:
         case KEY_RIGHT:
             button = ((key == KEY_LEFT ? --button : ++button) < 0)
                 ? 2 : (button > 2 ? 0 : button);
             print_buttons(dialog, height, width, button);
             wrefresh(menu);
             break;
         case ' ':
         case 's':
         case 'y':
         case 'n':
         case 'm':
         case '/':
             /* save scroll info */
             if ((f = fopen("lxdialog.scrltmp", "w")) != NULL) {
                 fprintf(f, "%d\n", scroll);
                 fclose(f);
             }
             delwin(dialog);
             fprintf(stderr, "%s\n", items[(scroll + choice) * 2]);
             switch (key) {
             case 's':
                 return 3;
             case 'y':
                 return 3;
             case 'n':
                 return 4;
             case 'm':
                 return 5;
             case ' ':
                 return 6;
             case '/':
                 return 7;
             }
             return 0;
         case 'h':
         case '?':
             button = 2;
         case '\n':
             delwin(dialog);
             if (button == 2)
                 fprintf(stderr, "%s \"%s\"\n",
                     items[(scroll + choice) * 2],
                     items[(scroll + choice) * 2 + 1] +
                     first_alpha(items [(scroll + choice) * 2 + 1], ""));
             else
                 fprintf(stderr, "%s\n",
                     items[(scroll + choice) * 2]);
             remove("lxdialog.scrltmp");
             return button;
         case 'e':
         case 'x':
             key = ESC;
         case ESC:
             break;
         }
     }
     delwin(dialog);
     remove("lxdialog.scrltmp");
     return -1;      /* ESC pressed */
 }
References ACS_HLINE, ACS_LTEE, ACS_RTEE, border_attr, current, dialog_attr, do_scroll(), draw_box(), draw_shadow(), ESC, f, FALSE, fclose(), first_alpha(), fopen(), fprintf(), fscanf(), height(), i, isalpha, item_x, items, j, MAX, menu_width, menubox_attr, menubox_border_attr, MIN, NULL, print_arrows(), print_autowrap(), print_buttons(), print_item, print_title(), prompt, remove(), stderr, strchr(), strcmp, TAB, title, tolower, TRUE, width, x, and y.
Referenced by j_menu().
do_print_item()
static void do_print_item (WINDOW * win, const char * item, int choice, int selected, int hotkey) static
Definition at line 66 of file menubox.c.
 {
     int j;
     char *menu_item = malloc(menu_width + 1);
     strncpy(menu_item, item, menu_width - item_x);
     menu_item[menu_width] = 0;
     j = first_alpha(menu_item, "YyNnMmHh");
     /* Clear 'residue' of last item */
     wattrset(win, menubox_attr);
     wmove(win, choice, 0);
 #if OLD_NCURSES
     {
         int i;
         for (i = 0; i < menu_width; i++)
             waddch(win, ' ');
     }
 #else
     wclrtoeol(win);
 #endif
     wattrset(win, selected ? item_selected_attr : item_attr);
     mvwaddstr(win, choice, item_x, menu_item);
     if (hotkey) {
         wattrset(win, selected ? tag_key_selected_attr : tag_key_attr);
         mvwaddch(win, choice, item_x + j, menu_item[j]);
     }
     if (selected) {
         wmove(win, choice, item_x + 1);
     }
     free(menu_item);
     wrefresh(win);
 }
References first_alpha(), free, i, item_attr, item_selected_attr, item_x, j, malloc, menu_width, menubox_attr, strncpy(), tag_key_attr, and tag_key_selected_attr.
do_scroll()
static void do_scroll (WINDOW * win, int * scroll, int n) static
Definition at line 168 of file menubox.c.
 {
     /* Scroll menu up */
     scrollok(win, TRUE);
     wscrl(win, n);
     scrollok(win, FALSE);
     *scroll = *scroll + n;
     wrefresh(win);
 }
References FALSE, n, and TRUE.
Referenced by dialog_menu().
print_arrows()
static void print_arrows (WINDOW * win, int item_no, int scroll, int y, int x, int height) static
Definition at line 110 of file menubox.c.
 {
     int cur_y, cur_x;
     getyx(win, cur_y, cur_x);
     wmove(win, y, x);
     if (scroll > 0) {
         wattrset(win, uarrow_attr);
         waddch(win, ACS_UARROW);
         waddstr(win, "(-)");
     } else {
         wattrset(win, menubox_attr);
         waddch(win, ACS_HLINE);
         waddch(win, ACS_HLINE);
         waddch(win, ACS_HLINE);
         waddch(win, ACS_HLINE);
     }
     y = y + height + 1;
     wmove(win, y, x);
     wrefresh(win);
     if ((height < item_no) && (scroll + height < item_no)) {
         wattrset(win, darrow_attr);
         waddch(win, ACS_DARROW);
         waddstr(win, "(+)");
     } else {
         wattrset(win, menubox_border_attr);
         waddch(win, ACS_HLINE);
         waddch(win, ACS_HLINE);
         waddch(win, ACS_HLINE);
         waddch(win, ACS_HLINE);
     }
     wmove(win, cur_y, cur_x);
     wrefresh(win);
 }
References ACS_DARROW, ACS_HLINE, ACS_UARROW, darrow_attr, height(), menubox_attr, menubox_border_attr, uarrow_attr, x, and y.
Referenced by dialog_menu().
print_buttons()
static void print_buttons (WINDOW * win, int height, int width, int selected) static
Definition at line 154 of file menubox.c.
 {
     int x = width / 2 - 16;
     int y = height - 2;
     print_button(win, "Select", y, x, selected == 0);
     print_button(win, " Exit ", y, x + 12, selected == 1);
     print_button(win, " Help ", y, x + 24, selected == 2);
     wmove(win, y, x + 1 + 12 * selected);
     wrefresh(win);
 }
References height(), print_button(), width, x, and y.
Referenced by dialog_menu().
Variable Documentation
item_x
int item_x static
Definition at line 61 of file menubox.c.
Referenced by dialog_menu(), and do_print_item().
menu_width
int menu_width static
Definition at line 61 of file menubox.c.
Referenced by dialog_menu(), and do_print_item().