Fennix Userspace: Userspace/mlibc/options/ansi/musl-generic-math/__cosdf.c File Reference
__cosdf.c File Reference
#include "libm.h"
Functions
float __cosdf (double x)
Variables
static const double C0 = -0x1ffffffd0c5e81.0p-54
static const double C1 = 0x155553e1053a42.0p-57
static const double C2 = -0x16c087e80f1e27.0p-62
static const double C3 = 0x199342e0ee5069.0p-68
Function Documentation
__cosdf()
float __cosdf (double x)
Definition at line 26 of file __cosdf.c.
 {
     double_t r, w, z;
     /* Try to optimize for parallel evaluation as in __tandf.c. */
     z = x*x;
     w = z*z;
     r = C2+z*C3;
     return ((1.0+z*C0) + w*C1) + (w*z)*r;
 }
References C0, C1, C2, C3, r, and x.
Referenced by cosf(), sin_pi(), sincosf(), and sinf().
Variable Documentation
C0
const double C0 = -0x1ffffffd0c5e81.0p-54 static
Definition at line 21 of file __cosdf.c.
Referenced by __cosdf().
C1
const double C1 = 0x155553e1053a42.0p-57 static
Definition at line 22 of file __cosdf.c.
Referenced by __cosdf().
C2
const double C2 = -0x16c087e80f1e27.0p-62 static
Definition at line 23 of file __cosdf.c.
Referenced by __cosdf().
C3
const double C3 = 0x199342e0ee5069.0p-68 static
Definition at line 24 of file __cosdf.c.
Referenced by __cosdf().