Fennix: Userspace/mlibc/tests/posix/pthread_cond.c File Reference
pthread_cond.c File Reference
#include <assert.h>
#include <errno.h>
#include <pthread.h>
#include <unistd.h>
Functions
static void * worker (void *arg)
static void test_broadcast_wakes_all ()
static void test_timedwait_timedout ()
static void test_attr ()
int main ()
Variables
_Atomic int waiting
_Atomic int should_exit
pthread_cond_t cond = PTHREAD_COND_INITIALIZER
pthread_mutex_t mtx = PTHREAD_MUTEX_INITIALIZER
Function Documentation
main()
int main (void)
Definition at line 102 of file pthread_cond.c.
            {
     test_attr();
     test_broadcast_wakes_all();
     test_timedwait_timedout();
 }
References test_attr(), test_broadcast_wakes_all(), and test_timedwait_timedout().
test_attr()
static void test_attr () static
Definition at line 74 of file pthread_cond.c.
{
     pthread_condattr_t attr;
     pthread_condattr_init(&attr);
     clockid_t clock;
     assert(!pthread_condattr_getclock(&attr, &clock));
     assert(clock == CLOCK_REALTIME);
     assert(!pthread_condattr_setclock(&attr, CLOCK_MONOTONIC));
     assert(!pthread_condattr_getclock(&attr, &clock));
     assert(clock == CLOCK_MONOTONIC);
     int pshared;
     assert(!pthread_condattr_getpshared(&attr, &pshared));
     assert(pshared == PTHREAD_PROCESS_PRIVATE);
     assert(!pthread_condattr_setpshared(&attr, PTHREAD_PROCESS_SHARED));
     assert(!pthread_condattr_getpshared(&attr, &pshared));
     assert(pshared == PTHREAD_PROCESS_SHARED);
     pthread_condattr_destroy(&attr);
     pthread_condattr_init(&attr);
     // Make sure that we can create a pthread_cond_t with an attr.
     pthread_cond_t cond;
     pthread_cond_init(&cond, &attr);
     pthread_cond_destroy(&cond);
     pthread_condattr_destroy(&attr);
 }
References assert, mlibc::attr, clock(), CLOCK_MONOTONIC, CLOCK_REALTIME, cond, pthread_cond_destroy(), pthread_cond_init(), pthread_condattr_destroy(), pthread_condattr_getclock(), pthread_condattr_getpshared(), pthread_condattr_init(), pthread_condattr_setclock(), pthread_condattr_setpshared(), PTHREAD_PROCESS_PRIVATE, and PTHREAD_PROCESS_SHARED.
Referenced by main().
test_broadcast_wakes_all()
static void test_broadcast_wakes_all () static
Definition at line 20 of file pthread_cond.c.
{
     pthread_t t1, t2;
     pthread_create(&t1, NULL, &worker, NULL);
     pthread_create(&t2, NULL, &worker, NULL);
     // Wait until the workers have actually entered the cond_wait
     // before doing a broadcast.
     while (waiting != 2 || pthread_mutex_trylock(&mtx) == EBUSY)
         usleep(150000); // 150ms
     should_exit = 1;
     assert(!pthread_cond_broadcast(&cond));
     pthread_mutex_unlock(&mtx);
     pthread_join(t1, NULL);
     pthread_join(t2, NULL);
 }
References assert, cond, EBUSY, mtx, NULL, pthread_cond_broadcast(), pthread_create(), pthread_join(), pthread_mutex_trylock(), pthread_mutex_unlock(), should_exit, t1, t2, usleep(), waiting, and worker().
Referenced by main().
test_timedwait_timedout()
static void test_timedwait_timedout () static
Definition at line 38 of file pthread_cond.c.
{
     // Use CLOCK_MONOTONIC.
     pthread_condattr_t attr;
     pthread_condattr_init(&attr);
     assert(!pthread_condattr_setclock(&attr, CLOCK_MONOTONIC));
     struct timespec before_now;
     assert(!clock_gettime(CLOCK_MONOTONIC, &before_now));
     before_now.tv_nsec -= 10000;
     pthread_mutex_lock(&mtx);
     int e = pthread_cond_timedwait(&cond, &mtx, &before_now);
     assert(e == ETIMEDOUT);
     pthread_mutex_unlock(&mtx);
     long nanos_per_second = 1000000000;
     struct timespec after_now;
     assert(!clock_gettime(CLOCK_MONOTONIC, &after_now));
     after_now.tv_nsec += nanos_per_second / 10; // 100ms
     if (after_now.tv_nsec >= nanos_per_second) {
         after_now.tv_nsec -= nanos_per_second;
         after_now.tv_sec++;
     }
     pthread_mutex_lock(&mtx);
     e = pthread_cond_timedwait(&cond, &mtx, &after_now);
     assert(e == ETIMEDOUT);
     pthread_mutex_unlock(&mtx);
     after_now.tv_nsec += nanos_per_second;
     pthread_mutex_lock(&mtx);
     e = pthread_cond_timedwait(&cond, &mtx, &after_now);
     assert(e == EINVAL);
     pthread_mutex_unlock(&mtx);
 }
References assert, mlibc::attr, clock_gettime(), CLOCK_MONOTONIC, cond, EINVAL, ETIMEDOUT, mtx, pthread_cond_timedwait(), pthread_condattr_init(), pthread_condattr_setclock(), pthread_mutex_lock(), pthread_mutex_unlock(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by main().
worker()
static void* worker (void * arg) static
Definition at line 10 of file pthread_cond.c.
{
     (void)arg;
     pthread_mutex_lock(&mtx);
     ++waiting;
     while (!should_exit)
         pthread_cond_wait(&cond, &mtx);
     pthread_mutex_unlock(&mtx);
     return NULL;
 }
References arg, cond, mtx, NULL, pthread_cond_wait(), pthread_mutex_lock(), pthread_mutex_unlock(), should_exit, Driver::void(), and waiting.
Referenced by test_broadcast_wakes_all().
Variable Documentation
cond
pthread_cond_t cond = PTHREAD_COND_INITIALIZER
Definition at line 7 of file pthread_cond.c.
Referenced by pthread_cond_broadcast(), pthread_cond_init(), pthread_cond_signal(), pthread_cond_timedwait(), pthread_cond_wait(), test_attr(), test_broadcast_wakes_all(), test_timedwait_timedout(), anonymous_namespace{grp-stubs.cpp}::walk_file(), and worker().
mtx
pthread_mutex_t mtx = PTHREAD_MUTEX_INITIALIZER
Definition at line 8 of file pthread_cond.c.
Referenced by test_broadcast_wakes_all(), test_timedwait_timedout(), and worker().
should_exit
_Atomic int should_exit
Definition at line 6 of file pthread_cond.c.
Referenced by test_broadcast_wakes_all(), and worker().
waiting
_Atomic int waiting
Definition at line 6 of file pthread_cond.c.
Referenced by test_broadcast_wakes_all(), and worker().