Fennix: Userspace/libc/include/stdio.h File Reference
stdio.h File Reference
#include <stdarg.h>
#include <stddef.h>
#include <sys/stat.h>
Data Structures
struct _IO_marker
struct _IO_FILE
Macros
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define EOF (-1)
EOF - End of file.
#define stdin stdin
#define stdout stdout
#define stderr stderr
Typedefs
typedef struct _IO_FILE FILE
Functions
FILE * freopen (const char *filename, const char *mode, FILE *stream)
FILE * fopen (const char *filename, const char *mode)
size_t fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
size_t fwrite (const void *ptr, size_t size, size_t nmemb, FILE *stream)
off_t fseek (FILE *stream, long offset, int whence)
long ftell (FILE *stream)
int fclose (FILE *fp)
int fflush (FILE *stream)
int fprintf (FILE *stream, const char *format,...)
int printf (const char *format,...)
void setbuf (FILE *stream, char *buf)
int vfprintf (FILE *stream, const char *format, va_list arg)
int vsscanf (const char *s, const char *format, va_list arg)
int sscanf (const char *s, const char *format,...)
int fputc (int c, FILE *stream)
int putc (int c, FILE *stream)
int fputs (const char *s, FILE *stream)
int puts (const char *s)
int putchar (int c)
int fgetc (FILE *stream)
Variables
FILE * stdin
FILE * stdout
FILE * stderr
Data Structure Documentation
_IO_marker
struct _IO_marker
Definition at line 19 of file stdio.h.
Data Fields
struct _IO_marker * _next
int _pos
struct _IO_FILE * _sbuf
Macro Definition Documentation
EOF
#define EOF (-1)
EOF - End of file.
The value returned by several functions to indicate the end of file.
Definition at line 17 of file stdio.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 9 of file stdio.h.
SEEK_END
#define SEEK_END 2
Definition at line 10 of file stdio.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 8 of file stdio.h.
stderr
#define stderr stderr
Definition at line 58 of file stdio.h.
stdin
#define stdin stdin
Definition at line 56 of file stdio.h.
stdout
#define stdout stdout
Definition at line 57 of file stdio.h.
Typedef Documentation
FILE
typedef struct _IO_FILE FILE
Definition at line 1 of file stdio.h.
Function Documentation
fclose()
int fclose (FILE * fp)
Definition at line 54 of file file.c.
 {
     if (fp == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     return syscall1(sc_close, fp->_fileno);
 }
References EINVAL, EOF, errno, NULL, sc_close, and syscall1().
fflush()
int fflush (FILE * stream)
Definition at line 85 of file file.c.
 {
     if (stream == NULL)
     {
         errno = EINVAL;
         return EOF;
     }
     errno = ENOSYS;
     return EOF;
 }
References EINVAL, ENOSYS, EOF, errno, and NULL.
Referenced by _flushlbf(), _rl_clean_up_for_exit(), _rl_erase_entire_line(), _rl_init_file_error(), _rl_internal_pager(), _rl_move_vert(), _rl_ttyflush(), _rl_update_final(), botch(), builtin_usage(), conf_askvalue(), conf_choice(), display_matches(), do_redirection_internal(), docfunctions(), download_one_url(), dprintf(), dump_file(), evaluate(), exec_kernel_doc(), execute_builtin_or_function(), execute_subshell_builtin_or_function(), exit_shell(), fclose(), fflush_all(), fflush_stdout_and_exit(), freopen(), ftpcmd(), hello_builtin(), hello_builtin_load(), hello_builtin_unload(), I_Error(), I_InitSquashTable(), I_InitStretchTables(), id_builtin(), inotifyd_main(), line_error(), logdir_close(), main(), necho_builtin(), newline_and_flush(), parse_file(), powertop_main(), print_builtin(), print_pipeline(), print_prompt(), printst(), programming_error(), reader_loop(), readline_internal_setup(), rl_deprep_terminal(), rl_ding(), rl_prep_terminal(), rl_print_last_kbd_macro(), rl_redisplay(), rl_show_char(), rotate(), sh_chkwrite(), subshell_exit(), throw_to_top_level(), update_passwd(), uuencode_main(), wait_for(), write_helpfiles(), xbotch(), xtrace_print_assignment(), xtrace_print_word_list(), and xtrace_reset().
fgetc()
int fgetc (FILE * stream)
Definition at line 7 of file get.c.
 {
 }
fopen()
FILE* fopen (const char * filename, const char * mode)
Definition at line 33 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     int fd = fdt->_open(pathname, ConvertFileFlags(mode), 0666);
     return fd;
 }
fprintf()
int fprintf (FILE * stream, const char * format, ...)
Definition at line 28 of file kernel_config.cpp.
 {
     va_list args;
     va_start(args, Format);
     vprintf(Format, args);
     va_end(args);
     UNUSED(stream);
 }
fputc()
int fputc (int c, FILE * stream)
Definition at line 7 of file put.c.
 {
     // FIXME
     // if (stream == NULL)
     // {
     //     errno = EBADF;
     //     return EOF;
     // }
     char str[2] = {c, '\0'};
     // return syscall3(sys_KernelCTL, KCTL_PRINT, str, 0);
 }
References c, and str.
fputs()
int fputs (const char * s, FILE * stream)
Definition at line 38 of file kernel_config.cpp.
 {
     printf("%s", s);
     UNUSED(stream);
 }
fread()
size_t fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 30 of file file.c.
 {
     if (ptr == NULL || stream == NULL || size == 0 || nmemb == 0)
     {
         errno = EINVAL;
         return 0;
     }
     syscall3(sc_lseek, stream->_fileno, stream->_offset, SEEK_SET);
     return syscall3(sc_read, (uint64_t)stream->_fileno, (uint64_t)ptr, size * nmemb);
 }
References EINVAL, errno, NULL, sc_lseek, sc_read, SEEK_SET, size, and syscall3().
freopen()
FILE* freopen (const char * filename, const char * mode, FILE * stream)
Definition at line 13 of file file.c.
 {
     errno = ENOSYS;
     return NULL;
 }
References ENOSYS, errno, and NULL.
Referenced by command_substitute(), do_piping(), main(), makemime_main(), next(), and xfreopen_write().
fseek()
off_t fseek (FILE * stream, long offset, int whence)
Definition at line 43 of file fseek.c.
 {
     return __fseeko(f, off, whence);
 }
References __fseeko(), f, and off.
Referenced by addmntent(), M_FileLength(), main(), and W_StdC_Read().
ftell()
long ftell (FILE * stream)
Definition at line 80 of file file.c.
 {
     return stream->_offset;
 }
Referenced by G_DoSaveGame(), M_FileLength(), saveg_read_pad(), and saveg_write_pad().
fwrite()
size_t fwrite (const void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 42 of file file.c.
 {
     if (ptr == NULL || stream == NULL || size == 0 || nmemb == 0)
     {
         errno = EINVAL;
         return 0;
     }
     syscall3(sc_lseek, stream->_fileno, stream->_offset, SEEK_SET);
     return syscall3(sc_write, (uint64_t)stream->_fileno, (uint64_t)ptr, size * nmemb);
 }
References EINVAL, errno, NULL, sc_lseek, sc_write, SEEK_SET, size, and syscall3().
printf()
int printf (const char * format, ...)
An implementation of the C standard's printf/vprintf
Note
you must implement a putchar_ function for using this function - it invokes putchar_ rather than directly performing any I/O (which insulates it from any dependence on the operating system and external libraries).
Parameters
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each %-specifier in format string
Returns
The number of characters written into s, not counting the terminating null character
Definition at line 1558 of file printf.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vprintf(format, args);
     va_end(args);
     return ret;
 }
putc()
int putc (int c, FILE * stream)
Definition at line 19 of file put.c.
 { return fputc(c, stream); }
References c, and fputc().
putchar()
int putchar (int c)
Definition at line 33 of file put.c.
 { return fputc(c, stdout); }
References c, fputc(), and stdout.
puts()
int puts (const char * s)
Definition at line 27 of file put.c.
 {
     for (int i = 0; s[i] != '\0'; i++)
         fputc(s[i], stdout);
 }
References fputc(), i, s, and stdout.
Referenced by ACTF(), add_remove_shell_main(), ask(), builtin_pwd(), cal_main(), check_all(), check_deps(), check_mail(), check_mount(), colon(), cpu_report(), cryptpw_main(), cttyhack_main(), cut_file(), date_main(), diff(), dirname_main(), display_boolean(), display_header(), display_verbose(), do_stop(), doCommands(), doit(), dumpleases_main(), encode_n_base64(), expr_main(), fatattr_main(), fdformat_main(), fdisk_main(), fetch(), fileAction(), findfs_main(), fsck_main(), fsck_minix_main(), get(), get_boot(), get_inode_common(), getenforce_main(), getopt_main(), getsebool_main(), grep_file(), header_list(), hostname_main(), httpd_main(), I_InitSquashTable(), I_InitStretchTables(), I_PrintBanner(), ipcrm_main(), ipneigh_list_or_flush(), kill_main(), list_packages(), list_table(), logical_getcwd(), login_main(), logname_main(), losetup_main(), lpd_main(), main(), makemime_main(), mesg_main(), mktemp_main(), modprobe_main(), new_password(), powertop_main(), preadfd(), print_ascii(), print_closing_wait(), print_host(), print_line(), print_login_issue(), print_matchpathcon(), print_numbered_lines(), print_serial_flags(), print_timestamp(), printenv_main(), printlim(), process_wait_result(), procps_get_maps(), ps_main(), pwd_main(), read_extended(), read_tables(), realpath_main(), recv_pack(), run_parts_main(), run_pipe(), runlevel_main(), scan_request(), sed_main(), show_help(), show_timerstats(), showkey_main(), sysctl_act_on_setting(), tar_main(), tree_print(), trim_trailing_spaces_and_print(), tsort_main(), tty_builtin(), tty_main(), tunctl_main(), uevent_main(), umaskcmd(), unzip_main(), usage(), vlock_main(), warn_geometry(), which_main(), who_main(), whoami_main(), write_block(), and writeline().
setbuf()
void setbuf (FILE * stream, char * buf)
Definition at line 112 of file file.c.
 {
 }
Referenced by fsck_main(), main(), mpstat_main(), open_next_file(), and tee_main().
sscanf()
int sscanf (const char * s, const char * format, ...)
Definition at line 125 of file file.c.
 {
     va_list args;
     va_start(args, format);
     const int ret = vsscanf(s, format, args);
     va_end(args);
     return ret;
 }
References args, format(), s, va_end, va_start, and vsscanf().
Referenced by action_compat(), arp_show(), build_ipv4_addr(), cap_name_to_number(), colon(), conf(), conf_choice(), depmod_main(), do_disk_statistics(), do_mktime(), do_tunnels_list(), fb_drawimage(), fuser_main(), get_cpu_count(), get_cpu_statistics(), get_dev_fields(), get_header_cpio(), get_irqs_from_stat(), get_num_from_file(), get_uptime(), get_wol_pw(), getmntent_r(), list_devs_in_proc_partititons(), ll_addr_a2n(), M_StrToInt(), main(), make_device(), name_to_dev_t(), parse_datestr(), parse_meminfo(), ParseIntParameter(), patch_main(), process_config_line(), procps_scan(), readprofile_main(), recover_mode(), scan_inet_proc_line(), scan_proc_net_or_maps(), ubi_devnum_from_devname(), ubi_tools_main(), and unix_do_one().
vfprintf()
int vfprintf (FILE * stream, const char * format, va_list arg)
Definition at line 116 of file file.c.
 {
     return 0;
 }
Referenced by _rl_init_file_error(), ash_vmsg(), builtin_error(), builtin_warning(), conf_warning(), dprintf(), fatal_error(), fprintf(), I_Error(), internal_debug(), internal_error(), internal_inform(), internal_warning(), menu_warn(), parser_error(), printf(), programming_error(), prop_warn(), report_error(), sys_error(), vdprintf(), vprintf(), vsnprintf(), vwarn(), and vwarnx().
vsscanf()
int vsscanf (const char * s, const char * format, va_list arg)
Definition at line 121 of file file.c.
 {
 }
Referenced by sscanf().
Variable Documentation
stderr
FILE* stderr extern
Definition at line 11 of file file.c.
stdin
FILE* stdin extern
Definition at line 9 of file file.c.
stdout
FILE* stdout extern
Definition at line 10 of file file.c.