Fennix Userspace: Userspace/musl/src/include/signal.h File Reference
signal.h File Reference
#include "../../include/signal.h"
Functions
hidden int __sigaction (int, const struct sigaction *, struct sigaction *)
hidden void __block_all_sigs (void *)
hidden void __block_app_sigs (void *)
hidden void __restore_sigs (void *)
hidden void __get_handler_set (sigset_t *)
Function Documentation
__block_all_sigs()
hidden void __block_all_sigs (void * set)
Definition at line 31 of file block.c.
 {
     __syscall(SYS_rt_sigprocmask, SIG_BLOCK, &all_mask, set, _NSIG/8);
 }
References __syscall, _NSIG, all_mask, and SIG_BLOCK.
Referenced by __pthread_exit(), __sigaction(), __synccall(), _Fork(), abort(), do_setgroups(), do_setxid(), do_wordexp(), faccessat(), and pthread_kill().
__block_app_sigs()
hidden void __block_app_sigs (void * set)
Definition at line 36 of file block.c.
 {
     __syscall(SYS_rt_sigprocmask, SIG_BLOCK, &app_mask, set, _NSIG/8);
 }
References __syscall, _NSIG, app_mask, and SIG_BLOCK.
Referenced by __membarrier(), __pthread_create(), __pthread_exit(), __pthread_key_delete(), __synccall(), fork(), install_new_tls(), pthread_getschedparam(), pthread_setschedparam(), pthread_setschedprio(), raise(), and sigqueue().
__get_handler_set()
hidden void __get_handler_set (sigset_t * set)
Definition at line 13 of file sigaction.c.
 {
     memcpy(set, handler_set, sizeof handler_set);
 }
References handler_set, and memcpy().
Referenced by child().
__restore_sigs()
hidden void __restore_sigs (void * set)
Definition at line 41 of file block.c.
 {
     __syscall(SYS_rt_sigprocmask, SIG_SETMASK, set, 0, _NSIG/8);
 }
References __syscall, _NSIG, and SIG_SETMASK.
Referenced by __membarrier(), __pthread_create(), __pthread_exit(), __pthread_key_delete(), __sigaction(), __synccall(), _Fork(), do_wordexp(), faccessat(), fork(), install_new_tls(), pthread_getschedparam(), pthread_kill(), pthread_setschedparam(), pthread_setschedprio(), raise(), and sigqueue().
__sigaction()
hidden int __sigaction (int , const struct sigaction * , struct sigaction *)