Fennix Userspace: Userspace/apps/base/busybox/runit/runsv.c File Reference
runsv.c File Reference
#include <sys/file.h>
#include "libbb.h"
#include "common_bufsiz.h"
#include "runit_lib.h"
Data Structures
struct svdir
struct globals
Macros
#define LESS(a, b) ((int)((unsigned)(b) - (unsigned)(a)) > 0)
#define S_DOWN 0
#define S_RUN 1
#define S_FINISH 2
#define C_NOOP 0
#define C_TERM 1
#define C_PAUSE 2
#define W_UP 0
#define W_DOWN 1
#define W_EXIT 2
#define G (*(struct globals*)bb_common_bufsiz1)
#define haslog (G.haslog)
#define sigterm (G.sigterm)
#define pidchanged (G.pidchanged)
#define selfpipe (G.selfpipe)
#define logpipe (G.logpipe)
#define dir (G.dir)
#define svd (G.svd)
#define INIT_G()
Functions
static void gettimeofday_ns (struct timespec *ts)
static void fatal2_cannot (const char *m1, const char *m2)
static void fatal_cannot (const char *m)
static void fatal2x_cannot (const char *m1, const char *m2)
static void warn2_cannot (const char *m1, const char *m2)
static void warn_cannot (const char *m)
static void s_chld_term (int sig_no)
static int open_trunc_or_warn (const char *name)
static void update_status (struct svdir *s)
static unsigned custom (struct svdir *s, char c)
static void stopservice (struct svdir *s)
static void startservice (struct svdir *s)
static int ctrl (struct svdir *s, char c)
static void open_control (const char *f, struct svdir *s)
int runsv_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Data Structure Documentation
svdir
struct svdir
Definition at line 93 of file runsv.c.
Data Fields
smallint ctrl
int fdcontrol
int fdcontrolwrite
int fdlock
smallint islog
int pid
smallint sd_want
struct timespec start
smallint state
int wstat
Macro Definition Documentation
C_NOOP
#define C_NOOP 0
Definition at line 85 of file runsv.c.
C_PAUSE
#define C_PAUSE 2
Definition at line 87 of file runsv.c.
C_TERM
#define C_TERM 1
Definition at line 86 of file runsv.c.
dir
#define dir (G.dir)
Definition at line 121 of file runsv.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 115 of file runsv.c.
haslog
#define haslog (G.haslog)
Definition at line 116 of file runsv.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    pidchanged = 1; \
} while (0)
Definition at line 123 of file runsv.c.
LESS
#define LESS (a, b) ((int)((unsigned)(b) - (unsigned)(a)) > 0)
Definition at line 78 of file runsv.c.
logpipe
#define logpipe (G.logpipe)
Definition at line 120 of file runsv.c.
pidchanged
#define pidchanged (G.pidchanged)
Definition at line 118 of file runsv.c.
S_DOWN
#define S_DOWN 0
Definition at line 81 of file runsv.c.
S_FINISH
#define S_FINISH 2
Definition at line 83 of file runsv.c.
S_RUN
#define S_RUN 1
Definition at line 82 of file runsv.c.
selfpipe
#define selfpipe (G.selfpipe)
Definition at line 119 of file runsv.c.
sigterm
#define sigterm (G.sigterm)
Definition at line 117 of file runsv.c.
svd
#define svd (G.svd)
Definition at line 122 of file runsv.c.
W_DOWN
#define W_DOWN 1
Definition at line 90 of file runsv.c.
W_EXIT
#define W_EXIT 2
Definition at line 91 of file runsv.c.
W_UP
#define W_UP 0
Definition at line 89 of file runsv.c.
Function Documentation
ctrl()
static int ctrl (struct svdir * s, char c) static
Definition at line 408 of file runsv.c.
 {
     int sig;
     switch (c) {
     case 'd': /* down */
         s->sd_want = W_DOWN;
         update_status(s);
         if (s->state == S_RUN)
             stopservice(s);
         break;
     case 'u': /* up */
         s->sd_want = W_UP;
         update_status(s);
         if (s->state == S_DOWN)
             startservice(s);
         break;
     case 'x': /* exit */
         if (s->islog)
             break;
         s->sd_want = W_EXIT;
         update_status(s);
         /* FALLTHROUGH */
     case 't': /* sig term */
         if (s->state == S_RUN)
             stopservice(s);
         break;
     case 'k': /* sig kill */
         if ((s->state == S_RUN) && !custom(s, c))
             kill(s->pid, SIGKILL);
         s->state = S_DOWN;
         break;
     case 'p': /* sig pause */
         if ((s->state == S_RUN) && !custom(s, c))
             kill(s->pid, SIGSTOP);
         s->ctrl |= C_PAUSE;
         update_status(s);
         break;
     case 'c': /* sig cont */
         if ((s->state == S_RUN) && !custom(s, c))
             kill(s->pid, SIGCONT);
         s->ctrl &= ~C_PAUSE;
         update_status(s);
         break;
     case 'o': /* once */
         s->sd_want = W_DOWN;
         update_status(s);
         if (s->state == S_DOWN)
             startservice(s);
         break;
     case 'a': /* sig alarm */
         sig = SIGALRM;
         goto sendsig;
     case 'h': /* sig hup */
         sig = SIGHUP;
         goto sendsig;
     case 'i': /* sig int */
         sig = SIGINT;
         goto sendsig;
     case 'q': /* sig quit */
         sig = SIGQUIT;
         goto sendsig;
     case '1': /* sig usr1 */
         sig = SIGUSR1;
         goto sendsig;
     case '2': /* sig usr2 */
         sig = SIGUSR2;
         goto sendsig;
     }
     return 1;
  sendsig:
     if ((s->state == S_RUN) && !custom(s, c))
         kill(s->pid, sig);
     return 1;
 }
References c, C_PAUSE, custom(), kill(), s, S_DOWN, S_RUN, SIGALRM, SIGCONT, SIGHUP, SIGINT, SIGKILL, SIGQUIT, SIGSTOP, SIGUSR1, SIGUSR2, startservice(), stopservice(), update_status(), W_DOWN, W_EXIT, and W_UP.
Referenced by ascii_main(), inetd_main(), and runsv_main().
custom()
static unsigned custom (struct svdir * s, char c) static
Definition at line 277 of file runsv.c.
 {
     pid_t pid;
     int w;
     char a[10];
     struct stat st;
     if (s->islog)
         return 0;
     strcpy(a, "control/?");
     a[8] = c; /* replace '?' */
     if (stat(a, &st) == 0) {
         if (st.st_mode & S_IXUSR) {
             pid = vfork();
             if (pid == -1) {
                 warn2_cannot("vfork for ", a);
                 return 0;
             }
             if (pid == 0) {
                 /* child */
                 if (haslog && dup2(logpipe.wr, 1) == -1)
                     warn2_cannot("setup stdout for ", a);
                 execl(a, a, (char *) NULL);
                 fatal2_cannot("run ", a);
             }
             /* parent */
             if (safe_waitpid(pid, &w, 0) == -1) {
                 warn2_cannot("wait for child ", a);
                 return 0;
             }
             return WEXITSTATUS(w) == 0;
         }
     } else {
         if (errno != ENOENT)
             warn2_cannot("stat ", a);
     }
     return 0;
 }
References c, dup2(), ENOENT, errno, execl(), fatal2_cannot(), haslog, logpipe, NULL, pid, s, S_IXUSR, safe_waitpid(), stat(), strcpy(), vfork(), w, warn2_cannot(), and WEXITSTATUS.
Referenced by ctrl(), startservice(), and stopservice().
fatal2_cannot()
static void fatal2_cannot (const char * m1, const char * m2) static
Definition at line 128 of file runsv.c.
 {
     bb_perror_msg_and_die("%s: fatal: can't %s%s", dir, m1, m2);
     /* was exiting 111 */
 }
References bb_perror_msg_and_die(), and dir.
Referenced by custom(), fatal_cannot(), open_control(), and startservice().
fatal2x_cannot()
static void fatal2x_cannot (const char * m1, const char * m2) static
Definition at line 138 of file runsv.c.
 {
     bb_error_msg_and_die("%s: fatal: can't %s%s", dir, m1, m2);
     /* was exiting 111 */
 }
References bb_error_msg_and_die(), and dir.
Referenced by runsv_main().
fatal_cannot()
static void fatal_cannot (const char * m) static
Definition at line 133 of file runsv.c.
 {
     fatal2_cannot(m, "");
     /* was exiting 111 */
 }
References fatal2_cannot().
Referenced by runsv_main().
gettimeofday_ns()
static void gettimeofday_ns (struct timespec * ts) static
Definition at line 59 of file runsv.c.
 {
     if (sizeof(struct timeval) == sizeof(struct timespec)
      && sizeof(((struct timeval*)ts)->tv_usec) == sizeof(ts->tv_nsec)
     ) {
         /* Cheat */
         xgettimeofday((void*)ts);
         ts->tv_nsec *= 1000;
     } else {
         /* For example, musl has "incompatible" layouts */
         struct timeval tv;
         xgettimeofday(&tv);
         ts->tv_sec = tv.tv_sec;
         ts->tv_nsec = tv.tv_usec * 1000;
     }
 }
References timespec::tv_nsec, timeval::tv_sec, timespec::tv_sec, timeval::tv_usec, and xgettimeofday().
Referenced by runsv_main(), and startservice().
open_control()
static void open_control (const char * f, struct svdir * s) static
Definition at line 484 of file runsv.c.
 {
     struct stat st;
     mkfifo(f, 0600);
     if (stat(f, &st) == -1)
         fatal2_cannot("stat ", f);
     if (!S_ISFIFO(st.st_mode))
         bb_error_msg_and_die("%s: fatal: %s exists but is not a fifo", dir, f);
     s->fdcontrol = xopen(f, O_RDONLY|O_NDELAY);
     close_on_exec_on(s->fdcontrol);
     s->fdcontrolwrite = xopen(f, O_WRONLY|O_NDELAY);
     close_on_exec_on(s->fdcontrolwrite);
     update_status(s);
 }
References bb_error_msg_and_die(), close_on_exec_on(), dir, f, fatal2_cannot(), mkfifo(), O_NDELAY, O_RDONLY, O_WRONLY, s, S_ISFIFO, stat(), update_status(), and xopen().
Referenced by runsv_main().
open_trunc_or_warn()
static int open_trunc_or_warn (const char * name) static
Definition at line 164 of file runsv.c.
 {
     /* Why O_NDELAY? */
     int fd = open(name, O_WRONLY | O_NDELAY | O_TRUNC | O_CREAT, 0644);
     if (fd < 0)
         bb_perror_msg("%s: warning: cannot open %s",
                 dir, name);
     return fd;
 }
References bb_perror_msg(), dir, fd, O_CREAT, O_NDELAY, O_TRUNC, O_WRONLY, and open().
Referenced by update_status().
runsv_main()
int runsv_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 500 of file runsv.c.
 {
     struct stat s;
     int fd;
     int r;
     char buf[256];
     INIT_G();
     dir = single_argv(argv);
     xpiped_pair(selfpipe);
     close_on_exec_on(selfpipe.rd);
     close_on_exec_on(selfpipe.wr);
     ndelay_on(selfpipe.rd);
     ndelay_on(selfpipe.wr);
     sig_block(SIGCHLD);
     sig_block(SIGTERM);
     /* No particular reason why we don't set SA_RESTART
      * (poll() wouldn't restart regardless of that flag),
      * we just follow what runit-2.1.2 does:
      */
     bb_signals_norestart(0
             + (1 << SIGCHLD)
             + (1 << SIGTERM)
             , s_chld_term);
     xchdir(dir);
     /* bss: svd[0].pid = 0; */
     if (S_DOWN) svd[0].state = S_DOWN; /* otherwise already 0 (bss) */
     if (C_NOOP) svd[0].ctrl = C_NOOP;
     if (W_UP) svd[0].sd_want = W_UP;
     /* bss: svd[0].islog = 0; */
     /* bss: svd[1].pid = 0; */
     gettimeofday_ns(&svd[0].start);
     if (stat("down", &s) != -1)
         svd[0].sd_want = W_DOWN;
     if (stat("log", &s) == -1) {
         if (errno != ENOENT)
             warn_cannot("stat ./log");
     } else {
         if (!S_ISDIR(s.st_mode)) {
             errno = 0;
             warn_cannot("stat log/down: log is not a directory");
         } else {
             haslog = 1;
             svd[1].state = S_DOWN;
             svd[1].ctrl = C_NOOP;
             svd[1].sd_want = W_UP;
             svd[1].islog = 1;
             gettimeofday_ns(&svd[1].start);
             if (stat("log/down", &s) != -1)
                 svd[1].sd_want = W_DOWN;
             xpiped_pair(logpipe);
             close_on_exec_on(logpipe.rd);
             close_on_exec_on(logpipe.wr);
         }
     }
     if (mkdir("supervise", 0700) == -1) {
         r = readlink("supervise", buf, sizeof(buf));
         if (r != -1) {
             if (r == sizeof(buf))
                 fatal2x_cannot("readlink ./supervise", ": name too long");
             buf[r] = 0;
             mkdir(buf, 0700);
         } else {
             if ((errno != ENOENT) && (errno != EINVAL))
                 fatal_cannot("readlink ./supervise");
         }
     }
     svd[0].fdlock = xopen3("log/supervise/lock"+4,
             O_WRONLY|O_NDELAY|O_APPEND|O_CREAT, 0600);
     if (flock(svd[0].fdlock, LOCK_EX | LOCK_NB) == -1)
         fatal_cannot("lock supervise/lock");
     close_on_exec_on(svd[0].fdlock);
     if (haslog) {
         if (mkdir("log/supervise", 0700) == -1) {
             r = readlink("log/supervise", buf, 256);
             if (r != -1) {
                 if (r == 256)
                     fatal2x_cannot("readlink ./log/supervise", ": name too long");
                 buf[r] = 0;
                 fd = xopen(".", O_RDONLY|O_NDELAY);
                 xchdir("./log");
                 mkdir(buf, 0700);
                 if (fchdir(fd) == -1)
                     fatal_cannot("change back to service directory");
                 close(fd);
             }
             else {
                 if ((errno != ENOENT) && (errno != EINVAL))
                     fatal_cannot("readlink ./log/supervise");
             }
         }
         svd[1].fdlock = xopen3("log/supervise/lock",
                 O_WRONLY|O_NDELAY|O_APPEND|O_CREAT, 0600);
         if (flock(svd[1].fdlock, LOCK_EX) == -1)
             fatal_cannot("lock log/supervise/lock");
         close_on_exec_on(svd[1].fdlock);
     }
     open_control("log/supervise/control"+4, &svd[0]);
     if (haslog) {
         open_control("log/supervise/control", &svd[1]);
     }
     mkfifo("log/supervise/ok"+4, 0600);
     fd = xopen("log/supervise/ok"+4, O_RDONLY|O_NDELAY);
     close_on_exec_on(fd);
     if (haslog) {
         mkfifo("log/supervise/ok", 0600);
         fd = xopen("log/supervise/ok", O_RDONLY|O_NDELAY);
         close_on_exec_on(fd);
     }
     for (;;) {
         struct pollfd x[3];
         unsigned deadline;
         char ch;
         if (haslog)
             if (!svd[1].pid && svd[1].sd_want == W_UP)
                 startservice(&svd[1]);
         if (!svd[0].pid)
             if (svd[0].sd_want == W_UP || svd[0].state == S_FINISH)
                 startservice(&svd[0]);
         x[0].fd = selfpipe.rd;
         x[0].events = POLLIN;
         x[1].fd = svd[0].fdcontrol;
         x[1].events = POLLIN;
         /* x[2] is used only if haslog == 1 */
         x[2].fd = svd[1].fdcontrol;
         x[2].events = POLLIN;
         sig_unblock(SIGTERM);
         sig_unblock(SIGCHLD);
         poll(x, 2 + haslog, 3600*1000);
         /* NB: signal handlers can trash errno of poll() */
         sig_block(SIGTERM);
         sig_block(SIGCHLD);
         while (read(selfpipe.rd, &ch, 1) == 1)
             continue;
         for (;;) {
             pid_t child;
             int wstat;
             child = wait_any_nohang(&wstat);
             if (!child)
                 break;
             if ((child == -1) && (errno != EINTR))
                 break;
             if (child == svd[0].pid) {
                 svd[0].wstat = wstat;
                 svd[0].pid = 0;
                 pidchanged = 1;
                 svd[0].ctrl &= ~C_TERM;
                 if (svd[0].state != S_FINISH) {
                     fd = open("finish", O_RDONLY|O_NDELAY);
                     if (fd != -1) {
                         close(fd);
                         svd[0].state = S_FINISH;
                         update_status(&svd[0]);
                         continue;
                     }
                 }
                 svd[0].state = S_DOWN;
                 deadline = svd[0].start.tv_sec + 1;
                 gettimeofday_ns(&svd[0].start);
                 update_status(&svd[0]);
                 if (LESS(svd[0].start.tv_sec, deadline))
                     sleep1();
             }
             if (haslog) {
                 if (child == svd[1].pid) {
                     svd[0].wstat = wstat;
                     svd[1].pid = 0;
                     pidchanged = 1;
                     svd[1].state = S_DOWN;
                     svd[1].ctrl &= ~C_TERM;
                     deadline = svd[1].start.tv_sec + 1;
                     gettimeofday_ns(&svd[1].start);
                     update_status(&svd[1]);
                     if (LESS(svd[1].start.tv_sec, deadline))
                         sleep1();
                 }
             }
         } /* for (;;) */
         if (read(svd[0].fdcontrol, &ch, 1) == 1)
             ctrl(&svd[0], ch);
         if (haslog)
             if (read(svd[1].fdcontrol, &ch, 1) == 1)
                 ctrl(&svd[1], ch);
         if (sigterm) {
             ctrl(&svd[0], 'x');
             sigterm = 0;
         }
         if (svd[0].sd_want == W_EXIT && svd[0].state == S_DOWN) {
             if (svd[1].pid == 0)
                 _exit_SUCCESS();
             if (svd[1].sd_want != W_EXIT) {
                 svd[1].sd_want = W_EXIT;
                 /* stopservice(&svd[1]); */
                 update_status(&svd[1]);
                 close(logpipe.wr);
                 close(logpipe.rd);
             }
         }
     } /* for (;;) */
     /* not reached */
     return 0;
 }
References _exit_SUCCESS(), argv, bb_signals_norestart(), buf, C_NOOP, C_TERM, child(), close(), close_on_exec_on(), ctrl(), dir, EINTR, EINVAL, ENOENT, errno, fatal2x_cannot(), fatal_cannot(), fchdir(), fd, flock(), gettimeofday_ns(), haslog, INIT_G, LESS, LOCK_EX, LOCK_NB, logpipe, mkdir(), mkfifo(), ndelay_on(), O_APPEND, O_CREAT, O_NDELAY, O_RDONLY, O_WRONLY, open(), open_control(), pid, pidchanged, poll(), POLLIN, read(), readlink(), s, s_chld_term(), S_DOWN, S_FINISH, S_ISDIR, selfpipe, sig_block(), sig_unblock(), SIGCHLD, sigterm, SIGTERM, single_argv(), sleep1(), start, startservice(), stat(), state, svd, update_status(), W_DOWN, W_EXIT, W_UP, wait_any_nohang(), warn_cannot(), wstat, x, xchdir(), xopen(), xopen3(), and xpiped_pair.
s_chld_term()
static void s_chld_term (int sig_no) static
Definition at line 157 of file runsv.c.
 {
     if (sig_no == SIGTERM)
         sigterm = 1;
     write(selfpipe.wr, "", 1);
 }
References selfpipe, sigterm, SIGTERM, and write().
Referenced by runsv_main().
startservice()
static void startservice (struct svdir * s) static
Definition at line 334 of file runsv.c.
 {
     int p;
     const char *arg[4];
     char exitcode[sizeof(int)*3 + 2];
     if (s->state == S_FINISH) {
 /* Two arguments are given to ./finish. The first one is ./run exit code,
  * or -1 if ./run didnt exit normally. The second one is
  * the least significant byte of the exit status as determined by waitpid;
  * for instance it is 0 if ./run exited normally, and the signal number
  * if ./run was terminated by a signal. If runsv cannot start ./run
  * for some reason, the exit code is 111 and the status is 0.
  */
         arg[0] = "./finish";
         arg[1] = "-1";
         if (WIFEXITED(s->wstat)) {
             *utoa_to_buf(WEXITSTATUS(s->wstat), exitcode, sizeof(exitcode)) = '\0';
             arg[1] = exitcode;
         }
         //arg[2] = "0";
         //if (WIFSIGNALED(s->wstat)) {
             arg[2] = utoa(WTERMSIG(s->wstat));
         //}
         arg[3] = NULL;
     } else {
         arg[0] = "./run";
         arg[1] = NULL;
         custom(s, 'u');
     }
     if (s->pid != 0)
         stopservice(s); /* should never happen */
     while ((p = vfork()) == -1) {
         warn_cannot("vfork, sleeping");
         sleep(5);
     }
     if (p == 0) {
         /* child */
         if (haslog) {
             /* NB: bug alert! right order is close, then dup2 */
             if (s->islog) {
                 xchdir("./log");
                 close(logpipe.wr);
                 xdup2(logpipe.rd, 0);
             } else {
                 close(logpipe.rd);
                 xdup2(logpipe.wr, 1);
             }
         }
         /* Non-ignored signals revert to SIG_DFL on exec.
          * But we can get signals BEFORE execl(), unlikely as that may be.
          * SIGCHLD is safe (would merely write to selfpipe),
          * but SIGTERM would set sigterm = 1 (with vfork, we affect parent).
          * Avoid that.
          */
         /*signal(SIGCHLD, SIG_DFL);*/
         signal(SIGTERM, SIG_DFL);
         sig_unblock(SIGCHLD);
         sig_unblock(SIGTERM);
         execv(arg[0], (char**) arg);
         fatal2_cannot(s->islog ? "start log/" : "start ", arg[0]);
     }
     /* parent */
     if (s->state != S_FINISH) {
         gettimeofday_ns(&s->start);
         s->state = S_RUN;
     }
     s->pid = p;
     pidchanged = 1;
     s->ctrl = C_NOOP;
     update_status(s);
 }
References C_NOOP, close(), custom(), execv(), exitcode, fatal2_cannot(), gettimeofday_ns(), haslog, logpipe, NULL, p, pidchanged, s, S_FINISH, S_RUN, SIG_DFL, sig_unblock(), SIGCHLD, signal, SIGTERM, sleep(), stopservice(), update_status(), utoa(), utoa_to_buf(), vfork(), warn_cannot(), WEXITSTATUS, WIFEXITED, WTERMSIG, xchdir(), and xdup2().
Referenced by ctrl(), and runsv_main().
stopservice()
static void stopservice (struct svdir * s) static
Definition at line 316 of file runsv.c.
 {
     if (s->pid && !custom(s, 't')) {
         kill(s->pid, SIGTERM);
         s->ctrl |= C_TERM;
         update_status(s);
     }
     if (s->sd_want == W_DOWN) {
         kill(s->pid, SIGCONT);
         custom(s, 'd');
         return;
     }
     if (s->sd_want == W_EXIT) {
         kill(s->pid, SIGCONT);
         custom(s, 'x');
     }
 }
References C_TERM, custom(), kill(), s, SIGCONT, SIGTERM, update_status(), W_DOWN, and W_EXIT.
Referenced by ctrl(), and startservice().
update_status()
static void update_status (struct svdir * s) static
Definition at line 174 of file runsv.c.
 {
     ssize_t sz;
     int fd;
     svstatus_t status;
     const char *fstatus ="log/supervise/status";
     const char *fstatusnew ="log/supervise/status.new";
     const char *f_stat ="log/supervise/stat";
     const char *fstatnew ="log/supervise/stat.new";
     const char *fpid ="log/supervise/pid";
     const char *fpidnew ="log/supervise/pid.new";
     if (!s->islog) {
         fstatus += 4;
         fstatusnew += 4;
         f_stat += 4;
         fstatnew += 4;
         fpid += 4;
         fpidnew += 4;
     }
     /* pid */
     if (pidchanged) {
         fd = open_trunc_or_warn(fpidnew);
         if (fd < 0)
             return;
         if (s->pid) {
             char spid[sizeof(int)*3 + 2];
             int size = sprintf(spid, "%u\n", (unsigned)s->pid);
             write(fd, spid, size);
         }
         close(fd);
         if (rename_or_warn(fpidnew, fpid))
             return;
         pidchanged = 0;
     }
     /* stat */
     fd = open_trunc_or_warn(fstatnew);
     if (fd < -1)
         return;
     {
         char stat_buf[sizeof("finish, paused, got TERM, want down\n")];
         char *p = stat_buf;
         switch (s->state) {
         case S_DOWN:
             p = stpcpy(p, "down");
             break;
         case S_RUN:
             p = stpcpy(p, "run");
             break;
         case S_FINISH:
             p = stpcpy(p, "finish");
             break;
         }
         if (s->ctrl & C_PAUSE)
             p = stpcpy(p, ", paused");
         if (s->ctrl & C_TERM)
             p = stpcpy(p, ", got TERM");
         if (s->state != S_DOWN)
             switch (s->sd_want) {
             case W_DOWN:
                 p = stpcpy(p, ", want down");
                 break;
             case W_EXIT:
                 p = stpcpy(p, ", want exit");
                 break;
             }
         *p++ = '\n';
         write(fd, stat_buf, p - stat_buf);
         close(fd);
     }
     rename_or_warn(fstatnew, f_stat);
     /* supervise compatibility */
     memset(&status, 0, sizeof(status));
     status.time_be64 = SWAP_BE64(s->start.tv_sec + 0x400000000000000aULL);
     status.time_nsec_be32 = SWAP_BE32(s->start.tv_nsec);
     status.pid_le32 = SWAP_LE32(s->pid);
     if (s->ctrl & C_PAUSE)
         status.paused = 1;
     if (s->sd_want == W_UP)
         status.want = 'u';
     else
         status.want = 'd';
     if (s->ctrl & C_TERM)
         status.got_term = 1;
     status.run_or_finish = s->state;
     fd = open_trunc_or_warn(fstatusnew);
     if (fd < 0)
         return;
     sz = write(fd, &status, sizeof(status));
     close(fd);
     if (sz != sizeof(status)) {
         warn2_cannot("write ", fstatusnew);
         unlink(fstatusnew);
         return;
     }
     rename_or_warn(fstatusnew, fstatus);
 }
References C_PAUSE, C_TERM, close(), fd, memset(), open_trunc_or_warn(), p, pidchanged, rename_or_warn(), s, S_DOWN, S_FINISH, S_RUN, size, sprintf(), status, stpcpy(), SWAP_BE32, SWAP_BE64, SWAP_LE32, unlink(), W_DOWN, W_EXIT, W_UP, warn2_cannot(), and write().
Referenced by ctrl(), open_control(), runsv_main(), startservice(), and stopservice().
warn2_cannot()
static void warn2_cannot (const char * m1, const char * m2) static
Definition at line 143 of file runsv.c.
 {
     bb_perror_msg("%s: warning: can't %s%s", dir, m1, m2);
 }
References bb_perror_msg(), and dir.
Referenced by custom(), update_status(), and warn_cannot().
warn_cannot()
static void warn_cannot (const char * m) static
Definition at line 147 of file runsv.c.
 {
     warn2_cannot(m, "");
 }
References warn2_cannot().
Referenced by runsv_main(), and startservice().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING