Fennix Userspace: Userspace/apps/base/bash/lib/sh/mktime.c File Reference
mktime.c File Reference
#include <sys/types.h>
#include <time.h>
#include "bashansi.h"
Macros
#define LEAP_SECONDS_POSSIBLE 1
#define PARAMS(args) ()
#define CHAR_BIT 8
#define INT_MIN (~0 << (sizeof (int) * CHAR_BIT - 1))
#define INT_MAX (~0 - INT_MIN)
#define TYPE_SIGNED(t) (! ((t) 0 < (t) -1))
#define TYPE_MINIMUM(t)
#define TYPE_MAXIMUM(t)
#define TIME_T_MIN TYPE_MINIMUM (time_t)
#define TIME_T_MAX TYPE_MAXIMUM (time_t)
#define TM_YEAR_BASE 1900
#define EPOCH_YEAR 1970
#define __isleap(year) ((year) % 4 == 0 && ((year) % 100 != 0 || (year) % 400 == 0))
Functions
static time_t ydhms_tm_diff PARAMS ((int, int, int, int, int, const struct tm *))
time_t __mktime_internal PARAMS ((struct tm *, struct tm *(*)(const time_t *, struct tm *), time_t *))
static struct tm *my_localtime_r PARAMS ((const time_t *, struct tm *))
static struct tm * my_localtime_r (time_t *t, struct tm *tp) const
static time_t ydhms_tm_diff (int year, int yday, int hour, int min, int sec, const struct tm *tp)
time_t mktime (struct tm *tp)
time_t __mktime_internal (struct tm *tp, struct tm **convert, time_t *offset)
Variables
const unsigned short int __mon_yday [2][13]
static time_t localtime_offset
Macro Definition Documentation
__isleap
#define __isleap (year) ((year) % 4 == 0 && ((year) % 100 != 0 || (year) % 400 == 0))
Definition at line 107 of file mktime.c.
CHAR_BIT
#define CHAR_BIT 8
Definition at line 68 of file mktime.c.
EPOCH_YEAR
#define EPOCH_YEAR 1970
Definition at line 102 of file mktime.c.
INT_MAX
#define INT_MAX (~0 - INT_MIN)
Definition at line 75 of file mktime.c.
INT_MIN
#define INT_MIN (~0 << (sizeof (int) * CHAR_BIT - 1))
Definition at line 72 of file mktime.c.
LEAP_SECONDS_POSSIBLE
#define LEAP_SECONDS_POSSIBLE 1
Definition at line 39 of file mktime.c.
PARAMS
#define PARAMS (args) ()
Definition at line 63 of file mktime.c.
TIME_T_MAX
#define TIME_T_MAX TYPE_MAXIMUM (time_t)
Definition at line 98 of file mktime.c.
TIME_T_MIN
#define TIME_T_MIN TYPE_MINIMUM (time_t)
Definition at line 95 of file mktime.c.
TM_YEAR_BASE
#define TM_YEAR_BASE 1900
Definition at line 101 of file mktime.c.
TYPE_MAXIMUM
#define TYPE_MAXIMUM (t)
Value:
  ((t) (! TYPE_SIGNED (t) \
    ? (t) -1 \
    : ((((t) 1 << (sizeof (t) * CHAR_BIT - 2)) - 1) * 2 + 1)))
Definition at line 89 of file mktime.c.
TYPE_MINIMUM
#define TYPE_MINIMUM (t)
Value:
  ((t) (! TYPE_SIGNED (t) \
    ? (t) 0 \
    : ~ TYPE_MAXIMUM (t)))
Definition at line 85 of file mktime.c.
TYPE_SIGNED
#define TYPE_SIGNED (t) (! ((t) 0 < (t) -1))
Definition at line 79 of file mktime.c.
Function Documentation
__mktime_internal()
time_t __mktime_internal (struct tm * tp, struct tm ** convert, time_t * offset)
Definition at line 194 of file mktime.c.
 {
   time_t t, dt, t0;
   struct tm tm;
   /* The maximum number of probes (calls to CONVERT) should be enough
      to handle any combinations of time zone rule changes, solar time,
      and leap seconds.  Posix.1 prohibits leap seconds, but some hosts
      have them anyway.  */
   int remaining_probes = 4;
   /* Time requested.  Copy it in case CONVERT modifies *TP; this can
      occur if TP is localtime's returned value and CONVERT is localtime.  */
   int sec = tp->tm_sec;
   int min = tp->tm_min;
   int hour = tp->tm_hour;
   int mday = tp->tm_mday;
   int mon = tp->tm_mon;
   int year_requested = tp->tm_year;
   int isdst = tp->tm_isdst;
   /* Ensure that mon is in range, and set year accordingly.  */
   int mon_remainder = mon % 12;
   int negative_mon_remainder = mon_remainder < 0;
   int mon_years = mon / 12 - negative_mon_remainder;
   int year = year_requested + mon_years;
   /* The other values need not be in range:
      the remaining code handles minor overflows correctly,
      assuming int and time_t arithmetic wraps around.
      Major overflows are caught at the end.  */
   /* Calculate day of year from year, month, and day of month.
      The result need not be in range.  */
   int yday = ((__mon_yday[__isleap (year + TM_YEAR_BASE)]
            [mon_remainder + 12 * negative_mon_remainder])
           + mday - 1);
 #if LEAP_SECONDS_POSSIBLE
   /* Handle out-of-range seconds specially,
      since ydhms_tm_diff assumes every minute has 60 seconds.  */
   int sec_requested = sec;
   if (sec < 0)
     sec = 0;
   if (59 < sec)
     sec = 59;
 #endif
   /* Invert CONVERT by probing.  First assume the same offset as last time.
      Then repeatedly use the error to improve the guess.  */
   tm.tm_year = EPOCH_YEAR - TM_YEAR_BASE;
   tm.tm_yday = tm.tm_hour = tm.tm_min = tm.tm_sec = 0;
   t0 = ydhms_tm_diff (year, yday, hour, min, sec, &tm);
   for (t = t0 + *offset;
        (dt = ydhms_tm_diff (year, yday, hour, min, sec, (*convert) (&t, &tm)));
        t += dt)
     if (--remaining_probes == 0)
       return -1;
   /* Check whether tm.tm_isdst has the requested value, if any.  */
   if (0 <= isdst && 0 <= tm.tm_isdst)
     {
       int dst_diff = (isdst != 0) - (tm.tm_isdst != 0);
       if (dst_diff)
     {
       /* Move two hours in the direction indicated by the disagreement,
          probe some more, and switch to a new time if found.
          The largest known fallback due to daylight savings is two hours:
          once, in Newfoundland, 1988-10-30 02:00 -> 00:00.  */
       time_t ot = t - 2 * 60 * 60 * dst_diff;
       while (--remaining_probes != 0)
         {
           struct tm otm;
           if (! (dt = ydhms_tm_diff (year, yday, hour, min, sec,
                      (*convert) (&ot, &otm))))
         {
           t = ot;
           tm = otm;
           break;
         }
           if ((ot += dt) == t)
         break;  /* Avoid a redundant probe.  */
         }
     }
     }
   *offset = t - t0;
 #if LEAP_SECONDS_POSSIBLE
   if (sec_requested != tm.tm_sec)
     {
       /* Adjust time to reflect the tm_sec requested, not the normalized value.
      Also, repair any damage from a false match due to a leap second.  */
       t += sec_requested - sec + (sec == 0 && tm.tm_sec == 60);
       (*convert) (&t, &tm);
     }
 #endif
   if (TIME_T_MAX / INT_MAX / 366 / 24 / 60 / 60 < 3)
     {
       /* time_t isn't large enough to rule out overflows in ydhms_tm_diff,
      so check for major overflows.  A gross check suffices,
      since if t has overflowed, it is off by a multiple of
      TIME_T_MAX - TIME_T_MIN + 1.  So ignore any component of
      the difference that is bounded by a small value.  */
       double dyear = (double) year_requested + mon_years - tm.tm_year;
       double dday = 366 * dyear + mday;
       double dsec = 60 * (60 * (24 * dday + hour) + min) + sec_requested;
       if (TIME_T_MAX / 3 - TIME_T_MIN / 3 < (dsec < 0 ? - dsec : dsec))
     return -1;
     }
   *tp = tm;
   return t;
 }
Referenced by mktime().
mktime()
time_t mktime (struct tm * tp)
Definition at line 175 of file mktime.c.
 {
 #ifdef _LIBC
   /* POSIX.1 8.1.1 requires that whenever mktime() is called, the
      time zone names contained in the external variable `tzname' shall
      be set as if the tzset() function had been called.  */
   __tzset ();
 #endif
   return __mktime_internal (tp, my_localtime_r, &localtime_offset);
 }
References __mktime_internal(), __tzset(), localtime_offset, my_localtime_r(), and tp.
Referenced by __mktime32(), and strftime().
my_localtime_r()
static struct tm* my_localtime_r (time_t * t, struct tm * tp) const static
Definition at line 128 of file mktime.c.
 {
   struct tm *l = localtime (t);
   if (! l)
     return 0;
   *tp = *l;
   return tp;
 }
References localtime(), t, and tp.
Referenced by mktime().
PARAMS() [1/3]
static struct tm* my_localtime_r PARAMS ((const time_t *, struct tm *)) static
PARAMS() [2/3]
static time_t ydhms_tm_diff PARAMS ((int, int, int, int, int, const struct tm *)) static
PARAMS() [3/3]
time_t __mktime_internal PARAMS ((struct tm *, struct tm *(*)(const time_t *, struct tm *), time_t *))
ydhms_tm_diff()
static time_t ydhms_tm_diff (int year, int yday, int hour, int min, int sec, const struct tm * tp) static
Definition at line 146 of file mktime.c.
 {
   /* Compute intervening leap days correctly even if year is negative.
      Take care to avoid int overflow.  time_t overflow is OK, since
      only the low order bits of the correct time_t answer are needed.
      Don't convert to time_t until after all divisions are done, since
      time_t might be unsigned.  */
   int a4 = (year >> 2) + (TM_YEAR_BASE >> 2) - ! (year & 3);
   int b4 = (tp->tm_year >> 2) + (TM_YEAR_BASE >> 2) - ! (tp->tm_year & 3);
   int a100 = a4 / 25 - (a4 % 25 < 0);
   int b100 = b4 / 25 - (b4 % 25 < 0);
   int a400 = a100 >> 2;
   int b400 = b100 >> 2;
   int intervening_leap_days = (a4 - b4) - (a100 - b100) + (a400 - b400);
   time_t years = year - (time_t) tp->tm_year;
   time_t days = (365 * years + intervening_leap_days
          + (yday - tp->tm_yday));
   return (60 * (60 * (24 * days + (hour - tp->tm_hour))
         + (min - tp->tm_min))
       + (sec - tp->tm_sec));
 }
References a4, b4, min(), TM_YEAR_BASE, and tp.
Variable Documentation
__mon_yday
const unsigned short int __mon_yday[2][13]
Initial value:
=
  {
    { 0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365 },
    { 0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335, 366 }
  }
Definition at line 112 of file mktime.c.
localtime_offset
time_t localtime_offset static
Definition at line 171 of file mktime.c.
Referenced by mktime().