Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/p_setup.c File Reference
p_setup.c File Reference
#include <math.h>
#include "z_zone.h"
#include "deh_main.h"
#include "i_swap.h"
#include "m_argv.h"
#include "m_bbox.h"
#include "g_game.h"
#include "i_system.h"
#include "w_wad.h"
#include "doomdef.h"
#include "p_local.h"
#include "s_sound.h"
#include "doomstat.h"
Macros
#define MAX_DEATHMATCH_STARTS 10
Functions
void P_SpawnMapThing (mapthing_t *mthing)
void P_LoadVertexes (int lump)
sector_t * GetSectorAtNullAddress (void)
void P_LoadSegs (int lump)
void P_LoadSubsectors (int lump)
void P_LoadSectors (int lump)
void P_LoadNodes (int lump)
void P_LoadThings (int lump)
void P_LoadLineDefs (int lump)
void P_LoadSideDefs (int lump)
void P_LoadBlockMap (int lump)
void P_GroupLines (void)
static void PadRejectArray (byte *array, unsigned int len)
static void P_LoadReject (int lumpnum)
void P_SetupLevel (int episode, int map, int playermask, skill_t skill)
void P_Init (void)
Variables
int numvertexes
vertex_t * vertexes
int numsegs
seg_t * segs
int numsectors
sector_t * sectors
int numsubsectors
subsector_t * subsectors
int numnodes
node_t * nodes
int numlines
line_t * lines
int numsides
side_t * sides
static int totallines
int bmapwidth
int bmapheight
short * blockmap
short * blockmaplump
fixed_t bmaporgx
fixed_t bmaporgy
mobj_t ** blocklinks
byte * rejectmatrix
mapthing_t deathmatchstarts [MAX_DEATHMATCH_STARTS]
mapthing_t * deathmatch_p
mapthing_t playerstarts [MAXPLAYERS]
Macro Definition Documentation
MAX_DEATHMATCH_STARTS
#define MAX_DEATHMATCH_STARTS 10
Definition at line 105 of file p_setup.c.
Function Documentation
GetSectorAtNullAddress()
sector_t* GetSectorAtNullAddress (void)
Definition at line 153 of file p_setup.c.
 {
     static boolean null_sector_is_initialized = false;
     static sector_t null_sector;
     if (!null_sector_is_initialized)
     {
         memset(&null_sector, 0, sizeof(null_sector));
         I_GetMemoryValue(0, &null_sector.floorheight, 4);
         I_GetMemoryValue(4, &null_sector.ceilingheight, 4);
         null_sector_is_initialized = true;
     }
     return &null_sector;
 }
References sector_t::ceilingheight, sector_t::floorheight, I_GetMemoryValue(), and memset().
Referenced by P_LoadSegs().
P_GroupLines()
void P_GroupLines (void)
Definition at line 545 of file p_setup.c.
 {
     line_t**        linebuffer;
     int         i;
     int         j;
     line_t*     li;
     sector_t*       sector;
     subsector_t*    ss;
     seg_t*      seg;
     fixed_t     bbox[4];
     int         block;
     // look up sector number for each subsector
     ss = subsectors;
     for (i=0 ; i<numsubsectors ; i++, ss++)
     {
     seg = &segs[ss->firstline];
     ss->sector = seg->sidedef->sector;
     }
     // count number of lines in each sector
     li = lines;
     totallines = 0;
     for (i=0 ; i<numlines ; i++, li++)
     {
     totallines++;
     li->frontsector->linecount++;
     if (li->backsector && li->backsector != li->frontsector)
     {
         li->backsector->linecount++;
         totallines++;
     }
     }
     // build line tables for each sector
     linebuffer = Z_Malloc (totallines*sizeof(line_t *), PU_LEVEL, 0);
     for (i=0; i<numsectors; ++i)
     {
         // Assign the line buffer for this sector
         sectors[i].lines = linebuffer;
         linebuffer += sectors[i].linecount;
         // Reset linecount to zero so in the next stage we can count
         // lines into the list.
         sectors[i].linecount = 0;
     }
     // Assign lines to sectors
     for (i=0; i<numlines; ++i)
     {
         li = &lines[i];
         if (li->frontsector != NULL)
         {
             sector = li->frontsector;
             sector->lines[sector->linecount] = li;
             ++sector->linecount;
         }
         if (li->backsector != NULL && li->frontsector != li->backsector)
         {
             sector = li->backsector;
             sector->lines[sector->linecount] = li;
             ++sector->linecount;
         }
     }
     // Generate bounding boxes for sectors
     sector = sectors;
     for (i=0 ; i<numsectors ; i++, sector++)
     {
     M_ClearBox (bbox);
     for (j=0 ; j<sector->linecount; j++)
     {
             li = sector->lines[j];
             M_AddToBox (bbox, li->v1->x, li->v1->y);
             M_AddToBox (bbox, li->v2->x, li->v2->y);
     }
     // set the degenmobj_t to the middle of the bounding box
     sector->soundorg.x = (bbox[BOXRIGHT]+bbox[BOXLEFT])/2;
     sector->soundorg.y = (bbox[BOXTOP]+bbox[BOXBOTTOM])/2;
     // adjust bounding box to map blocks
     block = (bbox[BOXTOP]-bmaporgy+MAXRADIUS)>>MAPBLOCKSHIFT;
     block = block >= bmapheight ? bmapheight-1 : block;
     sector->blockbox[BOXTOP]=block;
     block = (bbox[BOXBOTTOM]-bmaporgy-MAXRADIUS)>>MAPBLOCKSHIFT;
     block = block < 0 ? 0 : block;
     sector->blockbox[BOXBOTTOM]=block;
     block = (bbox[BOXRIGHT]-bmaporgx+MAXRADIUS)>>MAPBLOCKSHIFT;
     block = block >= bmapwidth ? bmapwidth-1 : block;
     sector->blockbox[BOXRIGHT]=block;
     block = (bbox[BOXLEFT]-bmaporgx-MAXRADIUS)>>MAPBLOCKSHIFT;
     block = block < 0 ? 0 : block;
     sector->blockbox[BOXLEFT]=block;
     }
 }
References line_s::backsector, bmapheight, bmaporgx, bmaporgy, bmapwidth, BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, subsector_s::firstline, line_s::frontsector, i, j, sector_t::linecount, lines, sector_t::lines, M_AddToBox(), M_ClearBox(), MAPBLOCKSHIFT, MAXRADIUS, NULL, numlines, numsectors, numsubsectors, PU_LEVEL, sector, side_t::sector, subsector_s::sector, sectors, segs, seg_t::sidedef, subsectors, totallines, line_s::v1, line_s::v2, vertex_t::x, vertex_t::y, and Z_Malloc().
Referenced by P_SetupLevel().
P_Init()
void P_Init (void)
Definition at line 847 of file p_setup.c.
 {
     P_InitSwitchList ();
     P_InitPicAnims ();
     R_InitSprites (sprnames);
 }
References P_InitPicAnims(), P_InitSwitchList(), R_InitSprites(), and sprnames.
Referenced by D_DoomMain().
P_LoadBlockMap()
void P_LoadBlockMap (int lump)
Definition at line 504 of file p_setup.c.
 {
     int i;
     int count;
     int lumplen;
     lumplen = W_LumpLength(lump);
     count = lumplen / 2;
     blockmaplump = Z_Malloc(lumplen, PU_LEVEL, NULL);
     W_ReadLump(lump, blockmaplump);
     blockmap = blockmaplump + 4;
     // Swap all short integers to native byte ordering.
     for (i=0; i<count; i++)
     {
     blockmaplump[i] = SHORT(blockmaplump[i]);
     }
     // Read the header
     bmaporgx = blockmaplump[0]<<FRACBITS;
     bmaporgy = blockmaplump[1]<<FRACBITS;
     bmapwidth = blockmaplump[2];
     bmapheight = blockmaplump[3];
     // Clear out mobj chains
     count = sizeof(*blocklinks) * bmapwidth * bmapheight;
     blocklinks = Z_Malloc(count, PU_LEVEL, 0);
     memset(blocklinks, 0, count);
 }
References blocklinks, blockmap, blockmaplump, bmapheight, bmaporgx, bmaporgy, bmapwidth, count, FRACBITS, i, memset(), NULL, PU_LEVEL, SHORT, W_LumpLength(), W_ReadLump(), and Z_Malloc().
Referenced by P_SetupLevel().
P_LoadLineDefs()
void P_LoadLineDefs (int lump)
Definition at line 392 of file p_setup.c.
 {
     byte*       data;
     int         i;
     maplinedef_t*   mld;
     line_t*     ld;
     vertex_t*       v1;
     vertex_t*       v2;
     numlines = W_LumpLength (lump) / sizeof(maplinedef_t);
     lines = Z_Malloc (numlines*sizeof(line_t),PU_LEVEL,0);
     memset (lines, 0, numlines*sizeof(line_t));
     data = W_CacheLumpNum (lump,PU_STATIC);
     mld = (maplinedef_t *)data;
     ld = lines;
     for (i=0 ; i<numlines ; i++, mld++, ld++)
     {
     ld->flags = SHORT(mld->flags);
     ld->special = SHORT(mld->special);
     ld->tag = SHORT(mld->tag);
     v1 = ld->v1 = &vertexes[SHORT(mld->v1)];
     v2 = ld->v2 = &vertexes[SHORT(mld->v2)];
     ld->dx = v2->x - v1->x;
     ld->dy = v2->y - v1->y;
     if (!ld->dx)
         ld->slopetype = ST_VERTICAL;
     else if (!ld->dy)
         ld->slopetype = ST_HORIZONTAL;
     else
     {
         if (FixedDiv (ld->dy , ld->dx) > 0)
         ld->slopetype = ST_POSITIVE;
         else
         ld->slopetype = ST_NEGATIVE;
     }
     if (v1->x < v2->x)
     {
         ld->bbox[BOXLEFT] = v1->x;
         ld->bbox[BOXRIGHT] = v2->x;
     }
     else
     {
         ld->bbox[BOXLEFT] = v2->x;
         ld->bbox[BOXRIGHT] = v1->x;
     }
     if (v1->y < v2->y)
     {
         ld->bbox[BOXBOTTOM] = v1->y;
         ld->bbox[BOXTOP] = v2->y;
     }
     else
     {
         ld->bbox[BOXBOTTOM] = v2->y;
         ld->bbox[BOXTOP] = v1->y;
     }
     ld->sidenum[0] = SHORT(mld->sidenum[0]);
     ld->sidenum[1] = SHORT(mld->sidenum[1]);
     if (ld->sidenum[0] != -1)
         ld->frontsector = sides[ld->sidenum[0]].sector;
     else
         ld->frontsector = 0;
     if (ld->sidenum[1] != -1)
         ld->backsector = sides[ld->sidenum[1]].sector;
     else
         ld->backsector = 0;
     }
     W_ReleaseLumpNum(lump);
 }
References line_s::backsector, line_s::bbox, BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, line_s::dx, line_s::dy, FixedDiv(), line_s::flags, line_s::frontsector, i, lines, memset(), numlines, PU_LEVEL, PU_STATIC, side_t::sector, SHORT, line_s::sidenum, sides, line_s::slopetype, line_s::special, ST_HORIZONTAL, ST_NEGATIVE, ST_POSITIVE, ST_VERTICAL, line_s::tag, line_s::v1, v1, line_s::v2, v2, vertexes, W_CacheLumpNum(), W_LumpLength(), W_ReleaseLumpNum(), and Z_Malloc().
Referenced by P_SetupLevel().
P_LoadNodes()
void P_LoadNodes (int lump)
Definition at line 298 of file p_setup.c.
 {
     byte*   data;
     int     i;
     int     j;
     int     k;
     mapnode_t*  mn;
     node_t* no;
     numnodes = W_LumpLength (lump) / sizeof(mapnode_t);
     nodes = Z_Malloc (numnodes*sizeof(node_t),PU_LEVEL,0);
     data = W_CacheLumpNum (lump,PU_STATIC);
     mn = (mapnode_t *)data;
     no = nodes;
     for (i=0 ; i<numnodes ; i++, no++, mn++)
     {
     no->x = SHORT(mn->x)<<FRACBITS;
     no->y = SHORT(mn->y)<<FRACBITS;
     no->dx = SHORT(mn->dx)<<FRACBITS;
     no->dy = SHORT(mn->dy)<<FRACBITS;
     for (j=0 ; j<2 ; j++)
     {
         no->children[j] = SHORT(mn->children[j]);
         for (k=0 ; k<4 ; k++)
         no->bbox[j][k] = SHORT(mn->bbox[j][k])<<FRACBITS;
     }
     }
     W_ReleaseLumpNum(lump);
 }
References FRACBITS, i, j, k, no, nodes, numnodes, PU_LEVEL, PU_STATIC, SHORT, W_CacheLumpNum(), W_LumpLength(), W_ReleaseLumpNum(), and Z_Malloc().
Referenced by P_SetupLevel().
P_LoadReject()
static void P_LoadReject (int lumpnum) static
Definition at line 712 of file p_setup.c.
 {
     int minlength;
     int lumplen;
     // Calculate the size that the REJECT lump *should* be.
     minlength = (numsectors * numsectors + 7) / 8;
     // If the lump meets the minimum length, it can be loaded directly.
     // Otherwise, we need to allocate a buffer of the correct size
     // and pad it with appropriate data.
     lumplen = W_LumpLength(lumpnum);
     if (lumplen >= minlength)
     {
         rejectmatrix = W_CacheLumpNum(lumpnum, PU_LEVEL);
     }
     else
     {
         rejectmatrix = Z_Malloc(minlength, PU_LEVEL, &rejectmatrix);
         W_ReadLump(lumpnum, rejectmatrix);
         PadRejectArray(rejectmatrix + lumplen, minlength - lumplen);
     }
 }
References numsectors, PadRejectArray(), PU_LEVEL, rejectmatrix, W_CacheLumpNum(), W_LumpLength(), W_ReadLump(), and Z_Malloc().
Referenced by P_SetupLevel().
P_LoadSectors()
void P_LoadSectors (int lump)
Definition at line 265 of file p_setup.c.
 {
     byte*       data;
     int         i;
     mapsector_t*    ms;
     sector_t*       ss;
     numsectors = W_LumpLength (lump) / sizeof(mapsector_t);
     sectors = Z_Malloc (numsectors*sizeof(sector_t),PU_LEVEL,0);
     memset (sectors, 0, numsectors*sizeof(sector_t));
     data = W_CacheLumpNum (lump,PU_STATIC);
     ms = (mapsector_t *)data;
     ss = sectors;
     for (i=0 ; i<numsectors ; i++, ss++, ms++)
     {
     ss->floorheight = SHORT(ms->floorheight)<<FRACBITS;
     ss->ceilingheight = SHORT(ms->ceilingheight)<<FRACBITS;
     ss->floorpic = R_FlatNumForName(ms->floorpic);
     ss->ceilingpic = R_FlatNumForName(ms->ceilingpic);
     ss->lightlevel = SHORT(ms->lightlevel);
     ss->special = SHORT(ms->special);
     ss->tag = SHORT(ms->tag);
     ss->thinglist = NULL;
     }
     W_ReleaseLumpNum(lump);
 }
References sector_t::ceilingheight, sector_t::ceilingpic, sector_t::floorheight, sector_t::floorpic, FRACBITS, i, sector_t::lightlevel, memset(), NULL, numsectors, PU_LEVEL, PU_STATIC, R_FlatNumForName(), sectors, SHORT, sector_t::special, sector_t::tag, sector_t::thinglist, W_CacheLumpNum(), W_LumpLength(), W_ReleaseLumpNum(), and Z_Malloc().
Referenced by P_SetupLevel().
P_LoadSegs()
void P_LoadSegs (int lump)
Definition at line 172 of file p_setup.c.
 {
     byte*       data;
     int         i;
     mapseg_t*       ml;
     seg_t*      li;
     line_t*     ldef;
     int         linedef;
     int         side;
     int                 sidenum;
     numsegs = W_LumpLength (lump) / sizeof(mapseg_t);
     segs = Z_Malloc (numsegs*sizeof(seg_t),PU_LEVEL,0);
     memset (segs, 0, numsegs*sizeof(seg_t));
     data = W_CacheLumpNum (lump,PU_STATIC);
     ml = (mapseg_t *)data;
     li = segs;
     for (i=0 ; i<numsegs ; i++, li++, ml++)
     {
     li->v1 = &vertexes[SHORT(ml->v1)];
     li->v2 = &vertexes[SHORT(ml->v2)];
     li->angle = (SHORT(ml->angle))<<16;
     li->offset = (SHORT(ml->offset))<<16;
     linedef = SHORT(ml->linedef);
     ldef = &lines[linedef];
     li->linedef = ldef;
     side = SHORT(ml->side);
     li->sidedef = &sides[ldef->sidenum[side]];
     li->frontsector = sides[ldef->sidenum[side]].sector;
         if (ldef-> flags & ML_TWOSIDED)
         {
             sidenum = ldef->sidenum[side ^ 1];
             // If the sidenum is out of range, this may be a "glass hack"
             // impassible window.  Point at side #0 (this may not be
             // the correct Vanilla behavior; however, it seems to work for
             // OTTAWAU.WAD, which is the one place I've seen this trick
             // used).
             if (sidenum < 0 || sidenum >= numsides)
             {
                 li->backsector = GetSectorAtNullAddress();
             }
             else
             {
                 li->backsector = sides[sidenum].sector;
             }
         }
         else
         {
         li->backsector = 0;
         }
     }
     W_ReleaseLumpNum(lump);
 }
References seg_t::angle, seg_t::backsector, flags, seg_t::frontsector, GetSectorAtNullAddress(), i, linedef, seg_t::linedef, lines, memset(), ml, ML_TWOSIDED, numsegs, numsides, seg_t::offset, PU_LEVEL, PU_STATIC, side_t::sector, segs, SHORT, seg_t::sidedef, line_s::sidenum, sides, seg_t::v1, seg_t::v2, vertexes, W_CacheLumpNum(), W_LumpLength(), W_ReleaseLumpNum(), and Z_Malloc().
Referenced by P_SetupLevel().
P_LoadSideDefs()
void P_LoadSideDefs (int lump)
Definition at line 473 of file p_setup.c.
 {
     byte*       data;
     int         i;
     mapsidedef_t*   msd;
     side_t*     sd;
     numsides = W_LumpLength (lump) / sizeof(mapsidedef_t);
     sides = Z_Malloc (numsides*sizeof(side_t),PU_LEVEL,0);
     memset (sides, 0, numsides*sizeof(side_t));
     data = W_CacheLumpNum (lump,PU_STATIC);
     msd = (mapsidedef_t *)data;
     sd = sides;
     for (i=0 ; i<numsides ; i++, msd++, sd++)
     {
     sd->textureoffset = SHORT(msd->textureoffset)<<FRACBITS;
     sd->rowoffset = SHORT(msd->rowoffset)<<FRACBITS;
     sd->toptexture = R_TextureNumForName(msd->toptexture);
     sd->bottomtexture = R_TextureNumForName(msd->bottomtexture);
     sd->midtexture = R_TextureNumForName(msd->midtexture);
     sd->sector = &sectors[SHORT(msd->sector)];
     }
     W_ReleaseLumpNum(lump);
 }
References side_t::bottomtexture, FRACBITS, i, memset(), side_t::midtexture, numsides, PU_LEVEL, PU_STATIC, R_TextureNumForName(), side_t::rowoffset, side_t::sector, sectors, SHORT, sides, side_t::textureoffset, side_t::toptexture, W_CacheLumpNum(), W_LumpLength(), W_ReleaseLumpNum(), and Z_Malloc().
Referenced by P_SetupLevel().
P_LoadSubsectors()
void P_LoadSubsectors (int lump)
Definition at line 236 of file p_setup.c.
 {
     byte*       data;
     int         i;
     mapsubsector_t* ms;
     subsector_t*    ss;
     numsubsectors = W_LumpLength (lump) / sizeof(mapsubsector_t);
     subsectors = Z_Malloc (numsubsectors*sizeof(subsector_t),PU_LEVEL,0);
     data = W_CacheLumpNum (lump,PU_STATIC);
     ms = (mapsubsector_t *)data;
     memset (subsectors,0, numsubsectors*sizeof(subsector_t));
     ss = subsectors;
     for (i=0 ; i<numsubsectors ; i++, ss++, ms++)
     {
     ss->numlines = SHORT(ms->numsegs);
     ss->firstline = SHORT(ms->firstseg);
     }
     W_ReleaseLumpNum(lump);
 }
References subsector_s::firstline, i, memset(), subsector_s::numlines, numsubsectors, PU_LEVEL, PU_STATIC, SHORT, subsectors, W_CacheLumpNum(), W_LumpLength(), W_ReleaseLumpNum(), and Z_Malloc().
Referenced by P_SetupLevel().
P_LoadThings()
void P_LoadThings (int lump)
Definition at line 335 of file p_setup.c.
 {
     byte               *data;
     int         i;
     mapthing_t         *mt;
     mapthing_t          spawnthing;
     int         numthings;
     boolean     spawn;
     data = W_CacheLumpNum (lump,PU_STATIC);
     numthings = W_LumpLength (lump) / sizeof(mapthing_t);
     mt = (mapthing_t *)data;
     for (i=0 ; i<numthings ; i++, mt++)
     {
     spawn = true;
     // Do not spawn cool, new monsters if !commercial
     if (gamemode != commercial)
     {
         switch (SHORT(mt->type))
         {
           case 68:  // Arachnotron
           case 64:  // Archvile
           case 88:  // Boss Brain
           case 89:  // Boss Shooter
           case 69:  // Hell Knight
           case 67:  // Mancubus
           case 71:  // Pain Elemental
           case 65:  // Former Human Commando
           case 66:  // Revenant
           case 84:  // Wolf SS
         spawn = false;
         break;
         }
     }
     if (spawn == false)
         break;
     // Do spawn all other stuff.
     spawnthing.x = SHORT(mt->x);
     spawnthing.y = SHORT(mt->y);
     spawnthing.angle = SHORT(mt->angle);
     spawnthing.type = SHORT(mt->type);
     spawnthing.options = SHORT(mt->options);
     P_SpawnMapThing(&spawnthing);
     }
     W_ReleaseLumpNum(lump);
 }
References commercial, gamemode, i, P_SpawnMapThing(), PU_STATIC, SHORT, spawn(), W_CacheLumpNum(), W_LumpLength(), and W_ReleaseLumpNum().
Referenced by P_SetupLevel().
P_LoadVertexes()
void P_LoadVertexes (int lump)
Definition at line 118 of file p_setup.c.
 {
     byte*       data;
     int         i;
     mapvertex_t*    ml;
     vertex_t*       li;
     // Determine number of lumps:
     //  total lump length / vertex record length.
     numvertexes = W_LumpLength (lump) / sizeof(mapvertex_t);
     // Allocate zone memory for buffer.
     vertexes = Z_Malloc (numvertexes*sizeof(vertex_t),PU_LEVEL,0);
     // Load data into cache.
     data = W_CacheLumpNum (lump, PU_STATIC);
     ml = (mapvertex_t *)data;
     li = vertexes;
     // Copy and convert vertex coordinates,
     // internal representation as fixed.
     for (i=0 ; i<numvertexes ; i++, li++, ml++)
     {
     li->x = SHORT(ml->x)<<FRACBITS;
     li->y = SHORT(ml->y)<<FRACBITS;
     }
     // Free buffer memory.
     W_ReleaseLumpNum(lump);
 }
References FRACBITS, i, ml, numvertexes, PU_LEVEL, PU_STATIC, SHORT, vertexes, W_CacheLumpNum(), W_LumpLength(), W_ReleaseLumpNum(), vertex_t::x, vertex_t::y, and Z_Malloc().
Referenced by P_SetupLevel().
P_SetupLevel()
void P_SetupLevel (int episode, int map, int playermask, skill_t skill)
Definition at line 744 of file p_setup.c.
 {
     int     i;
     char    lumpname[9];
     int     lumpnum;
     totalkills = totalitems = totalsecret = wminfo.maxfrags = 0;
     wminfo.partime = 180;
     for (i=0 ; i<MAXPLAYERS ; i++)
     {
     players[i].killcount = players[i].secretcount
         = players[i].itemcount = 0;
     }
     // Initial height of PointOfView
     // will be set by player think.
     players[consoleplayer].viewz = 1;
     // Make sure all sounds are stopped before Z_FreeTags.
     S_Start ();
     Z_FreeTags (PU_LEVEL, PU_PURGELEVEL-1);
     // UNUSED W_Profile ();
     P_InitThinkers ();
     // find map name
     if ( gamemode == commercial)
     {
     if (map<10)
         DEH_snprintf(lumpname, 9, "map0%i", map);
     else
         DEH_snprintf(lumpname, 9, "map%i", map);
     }
     else
     {
     lumpname[0] = 'E';
     lumpname[1] = '0' + episode;
     lumpname[2] = 'M';
     lumpname[3] = '0' + map;
     lumpname[4] = 0;
     }
     lumpnum = W_GetNumForName (lumpname);
     leveltime = 0;
     // note: most of this ordering is important
     P_LoadBlockMap (lumpnum+ML_BLOCKMAP);
     P_LoadVertexes (lumpnum+ML_VERTEXES);
     P_LoadSectors (lumpnum+ML_SECTORS);
     P_LoadSideDefs (lumpnum+ML_SIDEDEFS);
     P_LoadLineDefs (lumpnum+ML_LINEDEFS);
     P_LoadSubsectors (lumpnum+ML_SSECTORS);
     P_LoadNodes (lumpnum+ML_NODES);
     P_LoadSegs (lumpnum+ML_SEGS);
     P_GroupLines ();
     P_LoadReject (lumpnum+ML_REJECT);
     bodyqueslot = 0;
     deathmatch_p = deathmatchstarts;
     P_LoadThings (lumpnum+ML_THINGS);
     // if deathmatch, randomly spawn the active players
     if (deathmatch)
     {
     for (i=0 ; i<MAXPLAYERS ; i++)
         if (playeringame[i])
         {
         players[i].mo = NULL;
         G_DeathMatchSpawnPlayer (i);
         }
     }
     // clear special respawning que
     iquehead = iquetail = 0;
     // set up world state
     P_SpawnSpecials ();
     // build subsector connect matrix
     //  UNUSED P_ConnectSubsectors ();
     // preload graphics
     if (precache)
     R_PrecacheLevel ();
     //printf ("free memory: 0x%x\n", Z_FreeMemory());
 }
References bodyqueslot, commercial, consoleplayer, deathmatch, deathmatch_p, deathmatchstarts, DEH_snprintf, G_DeathMatchSpawnPlayer(), gamemode, i, iquehead, iquetail, player_s::itemcount, player_s::killcount, leveltime, map, wbstartstruct_t::maxfrags, MAXPLAYERS, ML_BLOCKMAP, ML_LINEDEFS, ML_NODES, ML_REJECT, ML_SECTORS, ML_SEGS, ML_SIDEDEFS, ML_SSECTORS, ML_THINGS, ML_VERTEXES, player_s::mo, NULL, P_GroupLines(), P_InitThinkers(), P_LoadBlockMap(), P_LoadLineDefs(), P_LoadNodes(), P_LoadReject(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_LoadThings(), P_LoadVertexes(), P_SpawnSpecials(), wbstartstruct_t::partime, playeringame, players, precache, PU_LEVEL, PU_PURGELEVEL, R_PrecacheLevel(), S_Start(), player_s::secretcount, totalitems, totalkills, totalsecret, player_s::viewz, W_GetNumForName(), wminfo, and Z_FreeTags().
Referenced by G_DoLoadLevel().
P_SpawnMapThing()
void P_SpawnMapThing (mapthing_t * mthing)
Definition at line 739 of file p_mobj.c.
 {
     int         i;
     int         bit;
     mobj_t*     mobj;
     fixed_t     x;
     fixed_t     y;
     fixed_t     z;
     // count deathmatch start positions
     if (mthing->type == 11)
     {
     if (deathmatch_p < &deathmatchstarts[10])
     {
         memcpy (deathmatch_p, mthing, sizeof(*mthing));
         deathmatch_p++;
     }
     return;
     }
     if (mthing->type <= 0)
     {
         // Thing type 0 is actually "player -1 start".
         // For some reason, Vanilla Doom accepts/ignores this.
         return;
     }
     // check for players specially
     if (mthing->type <= 4)
     {
     // save spots for respawning in network games
     playerstarts[mthing->type-1] = *mthing;
     if (!deathmatch)
         P_SpawnPlayer (mthing);
     return;
     }
     // check for apropriate skill level
     if (!netgame && (mthing->options & 16) )
     return;
     if (gameskill == sk_baby)
     bit = 1;
     else if (gameskill == sk_nightmare)
     bit = 4;
     else
     bit = 1<<(gameskill-1);
     if (!(mthing->options & bit) )
     return;
     // find which type to spawn
     for (i=0 ; i< NUMMOBJTYPES ; i++)
     if (mthing->type == mobjinfo[i].doomednum)
         break;
     if (i==NUMMOBJTYPES)
     I_Error ("P_SpawnMapThing: Unknown type %i at (%i, %i)",
          mthing->type,
          mthing->x, mthing->y);
     // don't spawn keycards and players in deathmatch
     if (deathmatch && mobjinfo[i].flags & MF_NOTDMATCH)
     return;
     // don't spawn any monsters if -nomonsters
     if (nomonsters
     && ( i == MT_SKULL
          || (mobjinfo[i].flags & MF_COUNTKILL)) )
     {
     return;
     }
     // spawn it
     x = mthing->x << FRACBITS;
     y = mthing->y << FRACBITS;
     if (mobjinfo[i].flags & MF_SPAWNCEILING)
     z = ONCEILINGZ;
     else
     z = ONFLOORZ;
     mobj = P_SpawnMobj (x,y,z, i);
     mobj->spawnpoint = *mthing;
     if (mobj->tics > 0)
     mobj->tics = 1 + (P_Random () % mobj->tics);
     if (mobj->flags & MF_COUNTKILL)
     totalkills++;
     if (mobj->flags & MF_COUNTITEM)
     totalitems++;
     mobj->angle = ANG45 * (mthing->angle/45);
     if (mthing->options & MTF_AMBUSH)
     mobj->flags |= MF_AMBUSH;
 }
References ANG45, mobj_s::angle, deathmatch, deathmatch_p, deathmatchstarts, mobjinfo_t::doomednum, flags, mobj_s::flags, FRACBITS, gameskill, i, I_Error(), memcpy(), MF_AMBUSH, MF_COUNTITEM, MF_COUNTKILL, MF_NOTDMATCH, MF_SPAWNCEILING, mobjinfo, MT_SKULL, MTF_AMBUSH, netgame, nomonsters, NUMMOBJTYPES, ONCEILINGZ, ONFLOORZ, P_Random(), P_SpawnMobj(), P_SpawnPlayer(), playerstarts, sk_baby, sk_nightmare, mobj_s::spawnpoint, mobj_s::tics, totalitems, totalkills, x, and y.
Referenced by P_LoadThings().
PadRejectArray()
static void PadRejectArray (byte * array, unsigned int len) static
Definition at line 661 of file p_setup.c.
 {
     unsigned int i;
     unsigned int byte_num;
     byte *dest;
     unsigned int padvalue;
     // Values to pad the REJECT array with:
     unsigned int rejectpad[4] =
     {
         ((totallines * 4 + 3) & ~3) + 24,     // Size
         0,                                    // Part of z_zone block header
         50,                                   // PU_LEVEL
         0x1d4a11                              // DOOM_CONST_ZONEID
     };
     // Copy values from rejectpad into the destination array.
     dest = array;
     for (i=0; i<len && i<sizeof(rejectpad); ++i)
     {
         byte_num = i % 4;
         *dest = (rejectpad[i / 4] >> (byte_num * 8)) & 0xff;
         ++dest;
     }
     // We only have a limited pad size.  Print a warning if the
     // REJECT lump is too small.
     if (len > sizeof(rejectpad))
     {
         fprintf(stderr, "PadRejectArray: REJECT lump too short to pad! (%i > %i)\n",
                         len, (int) sizeof(rejectpad));
         // Pad remaining space with 0 (or 0xff, if specified on command line).
         if (M_CheckParm("-reject_pad_with_ff"))
         {
             padvalue = 0xff;
         }
         else
         {
             padvalue = 0xf00;
         }
         memset(array + sizeof(rejectpad), padvalue, len - sizeof(rejectpad));
     }
 }
References fprintf(), i, M_CheckParm(), memset(), stderr, and totallines.
Referenced by P_LoadReject().
Variable Documentation
blocklinks
mobj_t** blocklinks
Definition at line 91 of file p_setup.c.
Referenced by P_BlockThingsIterator(), P_LoadBlockMap(), P_SetThingPosition(), and P_UnsetThingPosition().
blockmap
short* blockmap
Definition at line 84 of file p_setup.c.
Referenced by P_BlockLinesIterator(), and P_LoadBlockMap().
blockmaplump
short* blockmaplump
Definition at line 86 of file p_setup.c.
Referenced by P_BlockLinesIterator(), and P_LoadBlockMap().
bmapheight
int bmapheight
Definition at line 83 of file p_setup.c.
Referenced by P_BlockLinesIterator(), P_BlockThingsIterator(), P_GroupLines(), P_LoadBlockMap(), P_SetThingPosition(), and P_UnsetThingPosition().
bmaporgx
fixed_t bmaporgx
Definition at line 88 of file p_setup.c.
Referenced by A_VileChase(), AM_drawGrid(), P_CheckPosition(), P_GroupLines(), P_LoadBlockMap(), P_PathTraverse(), P_RadiusAttack(), P_SetThingPosition(), P_TeleportMove(), and P_UnsetThingPosition().
bmaporgy
fixed_t bmaporgy
Definition at line 89 of file p_setup.c.
Referenced by A_VileChase(), AM_drawGrid(), P_CheckPosition(), P_GroupLines(), P_LoadBlockMap(), P_PathTraverse(), P_RadiusAttack(), P_SetThingPosition(), P_TeleportMove(), and P_UnsetThingPosition().
bmapwidth
int bmapwidth
Definition at line 82 of file p_setup.c.
Referenced by P_BlockLinesIterator(), P_BlockThingsIterator(), P_GroupLines(), P_LoadBlockMap(), P_SetThingPosition(), and P_UnsetThingPosition().
deathmatch_p
mapthing_t* deathmatch_p
Definition at line 108 of file p_setup.c.
Referenced by G_DeathMatchSpawnPlayer(), P_SetupLevel(), and P_SpawnMapThing().
deathmatchstarts
mapthing_t deathmatchstarts[MAX_DEATHMATCH_STARTS]
Definition at line 107 of file p_setup.c.
Referenced by G_DeathMatchSpawnPlayer(), P_SetupLevel(), and P_SpawnMapThing().
lines
line_t* lines
Definition at line 67 of file p_setup.c.
Referenced by P_GroupLines(), P_LoadLineDefs(), and P_LoadSegs().
nodes
node_t* nodes
Definition at line 64 of file p_setup.c.
Referenced by P_CrossBSPNode(), P_LoadNodes(), R_PointInSubsector(), and R_RenderBSPNode().
numlines
int numlines
Definition at line 66 of file p_setup.c.
Referenced by AM_drawWalls(), P_ArchiveWorld(), P_GroupLines(), P_LoadLineDefs(), P_SpawnSpecials(), P_UnArchiveWorld(), shuf_main(), and shuffle_lines().
numnodes
int numnodes
Definition at line 63 of file p_setup.c.
Referenced by P_CheckSight(), P_LoadNodes(), R_PointInSubsector(), and R_RenderPlayerView().
numsectors
int numsectors
Definition at line 57 of file p_setup.c.
Referenced by AM_drawThings(), EV_LightTurnOn(), EV_Teleport(), EV_TurnTagLightsOff(), P_ArchiveWorld(), P_CheckSight(), P_FindSectorFromLineTag(), P_GroupLines(), P_LoadReject(), P_LoadSectors(), P_SpawnSpecials(), P_UnArchiveWorld(), and R_PrecacheLevel().
numsegs
int numsegs
Definition at line 54 of file p_setup.c.
Referenced by P_LoadSegs().
numsides
int numsides
Definition at line 69 of file p_setup.c.
Referenced by P_LoadSegs(), P_LoadSideDefs(), and R_PrecacheLevel().
numsubsectors
int numsubsectors
Definition at line 60 of file p_setup.c.
Referenced by P_CrossSubsector(), P_GroupLines(), P_LoadSubsectors(), and R_Subsector().
numvertexes
int numvertexes
Definition at line 51 of file p_setup.c.
Referenced by AM_findMinMaxBoundaries(), and P_LoadVertexes().
playerstarts
mapthing_t playerstarts[MAXPLAYERS]
Definition at line 109 of file p_setup.c.
Referenced by G_DeathMatchSpawnPlayer(), G_DoReborn(), and P_SpawnMapThing().
rejectmatrix
byte* rejectmatrix
Definition at line 101 of file p_setup.c.
Referenced by P_CheckSight(), and P_LoadReject().
sectors
sector_t* sectors
Definition at line 58 of file p_setup.c.
Referenced by AM_drawThings(), EV_BuildStairs(), EV_DoCeiling(), EV_DoDonut(), EV_DoDoor(), EV_DoFloor(), EV_DoPlat(), EV_LightTurnOn(), EV_StartLightStrobing(), EV_Teleport(), EV_TurnTagLightsOff(), flash_lock_unlock_main(), getSector(), getSide(), P_ArchiveWorld(), P_CheckSight(), P_FindSectorFromLineTag(), P_GroupLines(), P_LoadSectors(), P_LoadSideDefs(), P_SpawnSpecials(), P_UnArchiveWorld(), R_PrecacheLevel(), saveg_read_ceiling_t(), saveg_read_floormove_t(), saveg_read_glow_t(), saveg_read_lightflash_t(), saveg_read_plat_t(), saveg_read_strobe_t(), saveg_read_vldoor_t(), saveg_write_ceiling_t(), saveg_write_floormove_t(), saveg_write_glow_t(), saveg_write_lightflash_t(), saveg_write_plat_t(), saveg_write_strobe_t(), saveg_write_vldoor_t(), twoSided(), and volume_id_probe_promise_fasttrack_raid().
segs
seg_t* segs
Definition at line 55 of file p_setup.c.
Referenced by __fdpic_fixup(), _dlstart_c(), P_CrossSubsector(), P_GroupLines(), P_LoadSegs(), and R_Subsector().
sides
side_t* sides
Definition at line 70 of file p_setup.c.
Referenced by EV_DoPlat(), EV_VerticalDoor(), getSector(), getSide(), P_ArchiveWorld(), P_ChangeSwitchTexture(), P_LoadLineDefs(), P_LoadSegs(), P_LoadSideDefs(), P_RecursiveSound(), P_UnArchiveWorld(), P_UpdateSpecials(), and R_PrecacheLevel().
subsectors
subsector_t* subsectors
Definition at line 61 of file p_setup.c.
Referenced by P_CrossSubsector(), P_GroupLines(), P_LoadSubsectors(), R_PointInSubsector(), and R_Subsector().
totallines
int totallines static
Definition at line 72 of file p_setup.c.
Referenced by P_GroupLines(), and PadRejectArray().
vertexes
vertex_t* vertexes
Definition at line 52 of file p_setup.c.
Referenced by AM_findMinMaxBoundaries(), P_LoadLineDefs(), P_LoadSegs(), and P_LoadVertexes().