Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/m_config.c File Reference
m_config.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include "config.h"
#include "doomtype.h"
#include "doomkeys.h"
#include "doomfeatures.h"
#include "i_system.h"
#include "m_argv.h"
#include "m_misc.h"
#include "z_zone.h"
Data Structures
struct default_t
struct default_collection_t
Macros
#define CONFIG_VARIABLE_GENERIC(name, type) { #name, NULL, type, 0, 0, false }
#define CONFIG_VARIABLE_KEY(name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_KEY)
#define CONFIG_VARIABLE_INT(name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_INT)
#define CONFIG_VARIABLE_INT_HEX(name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_INT_HEX)
#define CONFIG_VARIABLE_FLOAT(name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_FLOAT)
#define CONFIG_VARIABLE_STRING(name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_STRING)
Enumerations
enum default_type_t {
DEFAULT_INT , DEFAULT_INT_HEX , DEFAULT_STRING , DEFAULT_FLOAT ,
DEFAULT_KEY
}
Functions
static default_t * SearchCollection (default_collection_t *collection, char *name)
static void SaveDefaultCollection (default_collection_t *collection)
static int ParseIntParameter (char *strparm)
static void SetVariable (default_t *def, char *value)
static void LoadDefaultCollection (default_collection_t *collection)
void M_SetConfigFilenames (char *main_config, char *extra_config)
void M_SaveDefaults (void)
void M_SaveDefaultsAlternate (char *main, char *extra)
void M_LoadDefaults (void)
static default_t * GetDefaultForName (char *name)
void M_BindVariable (char *name, void *location)
boolean M_SetVariable (char *name, char *value)
int M_GetIntVariable (char *name)
const char * M_GetStrVariable (char *name)
float M_GetFloatVariable (char *name)
static char * GetDefaultConfigDir (void)
void M_SetConfigDir (char *dir)
char * M_GetSaveGameDir (char *iwadname)
Variables
char * configdir
static char * default_main_config
static char * default_extra_config
static default_t doom_defaults_list []
@begin_config_file default
static default_collection_t doom_defaults
static default_t extra_defaults_list []
@begin_config_file extended
static default_collection_t extra_defaults
static const int scantokey [128]
Data Structure Documentation
default_t
struct default_t
Definition at line 61 of file m_config.c.
Data Fields
boolean bound
void * location
char * name
int original_translated
default_type_t type
int untranslated
default_collection_t
struct default_collection_t
Definition at line 88 of file m_config.c.
Data Fields
default_t * defaults
char * filename
int numdefaults
Macro Definition Documentation
CONFIG_VARIABLE_FLOAT
#define CONFIG_VARIABLE_FLOAT (name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_FLOAT)
Definition at line 104 of file m_config.c.
CONFIG_VARIABLE_GENERIC
#define CONFIG_VARIABLE_GENERIC (name, type) { #name, NULL, type, 0, 0, false }
Definition at line 95 of file m_config.c.
CONFIG_VARIABLE_INT
#define CONFIG_VARIABLE_INT (name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_INT)
Definition at line 100 of file m_config.c.
CONFIG_VARIABLE_INT_HEX
#define CONFIG_VARIABLE_INT_HEX (name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_INT_HEX)
Definition at line 102 of file m_config.c.
CONFIG_VARIABLE_KEY
#define CONFIG_VARIABLE_KEY (name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_KEY)
Definition at line 98 of file m_config.c.
CONFIG_VARIABLE_STRING
#define CONFIG_VARIABLE_STRING (name) CONFIG_VARIABLE_GENERIC(name, DEFAULT_STRING)
Definition at line 106 of file m_config.c.
Enumeration Type Documentation
default_type_t
enum default_type_t
Enumerator
DEFAULT_INT
DEFAULT_INT_HEX
DEFAULT_STRING
DEFAULT_FLOAT
DEFAULT_KEY
Definition at line 52 of file m_config.c.
 {
     DEFAULT_INT,
     DEFAULT_INT_HEX,
     DEFAULT_STRING,
     DEFAULT_FLOAT,
     DEFAULT_KEY,
 } default_type_t;
Function Documentation
GetDefaultConfigDir()
static char* GetDefaultConfigDir (void) static
Definition at line 2043 of file m_config.c.
 {
     char *result = (char *)malloc(2);
     result[0] = '.';
     result[1] = '\0';
     return result;
 }
References malloc(), and mlibc::result.
Referenced by M_SetConfigDir().
GetDefaultForName()
static default_t* GetDefaultForName (char * name) static
Definition at line 1937 of file m_config.c.
 {
     default_t *result;
     // Try the main list and the extras
     result = SearchCollection(&doom_defaults, name);
     if (result == NULL)
     {
         result = SearchCollection(&extra_defaults, name);
     }
     // Not found? Internal error.
     if (result == NULL)
     {
         I_Error("Unknown configuration variable: '%s'", name);
     }
     return result;
 }
References doom_defaults, extra_defaults, I_Error(), name, NULL, mlibc::result, and SearchCollection().
Referenced by M_BindVariable(), M_GetFloatVariable(), M_GetIntVariable(), M_GetStrVariable(), and M_SetVariable().
LoadDefaultCollection()
static void LoadDefaultCollection (default_collection_t * collection) static
Definition at line 1771 of file m_config.c.
 {
 #if ORIGCODE
     FILE *f;
     default_t *def;
     char defname[80];
     char strparm[100];
     // read the file in, overriding any set defaults
     f = fopen(collection->filename, "r");
     if (f == NULL)
     {
         // File not opened, but don't complain.
         // It's probably just the first time they ran the game.
         return;
     }
     while (!feof(f))
     {
         if (fscanf(f, "%79s %99[^\n]\n", defname, strparm) != 2)
         {
             // This line doesn't match
             continue;
         }
         // Find the setting in the list
         def = SearchCollection(collection, defname);
         if (def == NULL || !def->bound)
         {
             // Unknown variable?  Unbound variables are also treated
             // as unknown.
             continue;
         }
         // Strip off trailing non-printable characters (\r characters
         // from DOS text files)
         while (strlen(strparm) > 0 && !isprint(strparm[strlen(strparm)-1]))
         {
             strparm[strlen(strparm)-1] = '\0';
         }
         // Surrounded by quotes? If so, remove them.
         if (strlen(strparm) >= 2
          && strparm[0] == '"' && strparm[strlen(strparm) - 1] == '"')
         {
             strparm[strlen(strparm) - 1] = '\0';
             memmove(strparm, strparm + 1, sizeof(strparm) - 1);
         }
         SetVariable(def, strparm);
     }
     fclose (f);
 #endif
 }
References default_t::bound, fclose(), feof(), default_collection_t::filename, fopen(), fscanf(), isprint(), memmove(), NULL, SearchCollection(), SetVariable(), and strlen().
Referenced by M_LoadDefaults().
M_BindVariable()
void M_BindVariable (char * name, void * location)
Definition at line 1964 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     variable->location = location;
     variable->bound = true;
 }
References GetDefaultForName(), name, and variable.
Referenced by D_BindVariables(), I_BindJoystickVariables(), I_BindSoundVariables(), M_BindBaseControls(), M_BindChatControls(), M_BindHereticControls(), M_BindHexenControls(), M_BindMapControls(), M_BindMenuControls(), M_BindStrifeControls(), and M_BindWeaponControls().
M_GetFloatVariable()
float M_GetFloatVariable (char * name)
Definition at line 2025 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     if (variable == NULL || !variable->bound
      || variable->type != DEFAULT_FLOAT)
     {
         return 0;
     }
     return *((float *) variable->location);
 }
References DEFAULT_FLOAT, GetDefaultForName(), name, NULL, and variable.
M_GetIntVariable()
int M_GetIntVariable (char * name)
Definition at line 1995 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     if (variable == NULL || !variable->bound
      || (variable->type != DEFAULT_INT && variable->type != DEFAULT_INT_HEX))
     {
         return 0;
     }
     return *((int *) variable->location);
 }
References DEFAULT_INT, DEFAULT_INT_HEX, GetDefaultForName(), name, NULL, and variable.
M_GetSaveGameDir()
char* M_GetSaveGameDir (char * iwadname)
Definition at line 2087 of file m_config.c.
 {
     char *savegamedir;
 #if ORIGCODE
     char *topdir;
 #endif
     // If not "doing" a configuration directory (Windows), don't "do"
     // a savegame directory, either.
     if (!strcmp(configdir, ""))
     {
         savegamedir = strdup("");
     }
     else
     {
 #if ORIGCODE
         // ~/.chocolate-doom/savegames
         topdir = M_StringJoin(configdir, "savegame", NULL);
         M_MakeDirectory(topdir);
         // eg. ~/.chocolate-doom/savegames/doom2.wad/
         savegamedir = M_StringJoin(topdir, DIR_SEPARATOR_S, iwadname,
                                    DIR_SEPARATOR_S, NULL);
         M_MakeDirectory(savegamedir);
         free(topdir);
 #else
         savegamedir = M_StringJoin(configdir, DIR_SEPARATOR_S, ".savegame/", NULL);
         M_MakeDirectory(savegamedir);
         printf ("Using %s for savegames\n", savegamedir);
 #endif
     }
     return savegamedir;
 }
References configdir, DIR_SEPARATOR_S, free(), M_MakeDirectory(), M_StringJoin(), NULL, printf(), savegamedir, strcmp(), and strdup().
Referenced by D_DoomMain().
M_GetStrVariable()
const char* M_GetStrVariable (char * name)
Definition at line 2010 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     if (variable == NULL || !variable->bound
      || variable->type != DEFAULT_STRING)
     {
         return NULL;
     }
     return *((const char **) variable->location);
 }
References DEFAULT_STRING, GetDefaultForName(), name, NULL, and variable.
M_LoadDefaults()
void M_LoadDefaults (void)
Definition at line 1881 of file m_config.c.
 {
     int i;
     // check for a custom default file
     // @arg <file>
     // @vanilla
     //
     // Load main configuration from the specified file, instead of the
     // default.
     //
     i = M_CheckParmWithArgs("-config", 1);
     if (i)
     {
     doom_defaults.filename = myargv[i+1];
     printf ("   default file: %s\n",doom_defaults.filename);
     }
     else
     {
         doom_defaults.filename
             = M_StringJoin(configdir, default_main_config, NULL);
     }
     printf("saving config in %s\n", doom_defaults.filename);
     // @arg <file>
     //
     // Load additional configuration from the specified file, instead of
     // the default.
     //
     i = M_CheckParmWithArgs("-extraconfig", 1);
     if (i)
     {
         extra_defaults.filename = myargv[i+1];
         printf("        extra configuration file: %s\n",
                extra_defaults.filename);
     }
     else
     {
         extra_defaults.filename
             = M_StringJoin(configdir, default_extra_config, NULL);
     }
     LoadDefaultCollection(&doom_defaults);
     LoadDefaultCollection(&extra_defaults);
 }
References configdir, default_extra_config, default_main_config, doom_defaults, extra_defaults, default_collection_t::filename, i, LoadDefaultCollection(), M_CheckParmWithArgs(), M_StringJoin(), myargv, NULL, and printf().
Referenced by D_DoomMain().
M_SaveDefaults()
void M_SaveDefaults (void)
Definition at line 1846 of file m_config.c.
 {
     SaveDefaultCollection(&doom_defaults);
     SaveDefaultCollection(&extra_defaults);
 }
References doom_defaults, extra_defaults, and SaveDefaultCollection().
Referenced by D_DoomMain(), and M_SaveDefaultsAlternate().
M_SaveDefaultsAlternate()
void M_SaveDefaultsAlternate (char * main, char * extra)
Definition at line 1856 of file m_config.c.
 {
     char *orig_main;
     char *orig_extra;
     // Temporarily change the filenames
     orig_main = doom_defaults.filename;
     orig_extra = extra_defaults.filename;
     doom_defaults.filename = main;
     extra_defaults.filename = extra;
     M_SaveDefaults();
     // Restore normal filenames
     doom_defaults.filename = orig_main;
     extra_defaults.filename = orig_extra;
 }
References doom_defaults, extra_defaults, default_collection_t::filename, M_SaveDefaults(), and main().
M_SetConfigDir()
void M_SetConfigDir (char * dir)
Definition at line 2059 of file m_config.c.
 {
     // Use the directory that was passed, or find the default.
     if (dir != NULL)
     {
         configdir = dir;
     }
     else
     {
         configdir = GetDefaultConfigDir();
     }
     if (strcmp(configdir, "") != 0)
     {
         printf("Using %s for configuration and saves\n", configdir);
     }
     // Make the directory if it doesn't already exist:
     M_MakeDirectory(configdir);
 }
References configdir, GetDefaultConfigDir(), M_MakeDirectory(), NULL, printf(), and strcmp().
Referenced by D_DoomMain().
M_SetConfigFilenames()
void M_SetConfigFilenames (char * main_config, char * extra_config)
Definition at line 1836 of file m_config.c.
 {
     default_main_config = main_config;
     default_extra_config = extra_config;
 }
References default_extra_config, and default_main_config.
Referenced by D_DoomMain().
M_SetVariable()
boolean M_SetVariable (char * name, char * value)
Definition at line 1977 of file m_config.c.
 {
     default_t *variable;
     variable = GetDefaultForName(name);
     if (variable == NULL || !variable->bound)
     {
         return false;
     }
     SetVariable(variable, value);
     return true;
 }
References GetDefaultForName(), name, NULL, SetVariable(), value, and variable.
ParseIntParameter()
static int ParseIntParameter (char * strparm) static
Definition at line 1716 of file m_config.c.
 {
     int parm;
     if (strparm[0] == '0' && strparm[1] == 'x')
         sscanf(strparm+2, "%x", &parm);
     else
         sscanf(strparm, "%i", &parm);
     return parm;
 }
References sscanf().
Referenced by SetVariable().
SaveDefaultCollection()
static void SaveDefaultCollection (default_collection_t * collection) static
Definition at line 1609 of file m_config.c.
 {
 #if ORIGCODE
     default_t *defaults;
     int i, v;
     FILE *f;
     f = fopen (collection->filename, "w");
     if (!f)
     return; // can't write the file, but don't complain
     defaults = collection->defaults;
     for (i=0 ; i<collection->numdefaults ; i++)
     {
         int chars_written;
         // Ignore unbound variables
         if (!defaults[i].bound)
         {
             continue;
         }
         // Print the name and line up all values at 30 characters
         chars_written = fprintf(f, "%s ", defaults[i].name);
         for (; chars_written < 30; ++chars_written)
             fprintf(f, " ");
         // Print the value
         switch (defaults[i].type)
         {
             case DEFAULT_KEY:
                 // use the untranslated version if we can, to reduce
                 // the possibility of screwing up the user's config
                 // file
                 v = * (int *) defaults[i].location;
                 if (v == KEY_RSHIFT)
                 {
                     // Special case: for shift, force scan code for
                     // right shift, as this is what Vanilla uses.
                     // This overrides the change check below, to fix
                     // configuration files made by old versions that
                     // mistakenly used the scan code for left shift.
                     v = 54;
                 }
                 else if (defaults[i].untranslated
                       && v == defaults[i].original_translated)
                 {
                     // Has not been changed since the last time we
                     // read the config file.
                     v = defaults[i].untranslated;
                 }
                 else
                 {
                     // search for a reverse mapping back to a scancode
                     // in the scantokey table
                     int s;
                     for (s=0; s<128; ++s)
                     {
                         if (scantokey[s] == v)
{
                             v = s;
                             break;
                         }
                     }
                 }
             fprintf(f, "%i", v);
                 break;
             case DEFAULT_INT:
             fprintf(f, "%i", * (int *) defaults[i].location);
                 break;
             case DEFAULT_INT_HEX:
             fprintf(f, "0x%x", * (int *) defaults[i].location);
                 break;
             case DEFAULT_FLOAT:
                 fprintf(f, "%f", * (float *) defaults[i].location);
                 break;
             case DEFAULT_STRING:
             fprintf(f,"\"%s\"", * (char **) (defaults[i].location));
                 break;
         }
         fprintf(f, "\n");
     }
     fclose (f);
 #endif
 }
References DEFAULT_FLOAT, DEFAULT_INT, DEFAULT_INT_HEX, DEFAULT_KEY, DEFAULT_STRING, default_collection_t::defaults, fclose(), default_collection_t::filename, fopen(), fprintf(), i, KEY_RSHIFT, name, default_collection_t::numdefaults, scantokey, and default_t::untranslated.
Referenced by M_SaveDefaults().
SearchCollection()
static default_t* SearchCollection (default_collection_t * collection, char * name) static
Definition at line 1563 of file m_config.c.
 {
     int i;
     for (i=0; i<collection->numdefaults; ++i)
     {
         if (!strcmp(name, collection->defaults[i].name))
         {
             return &collection->defaults[i];
         }
     }
     return NULL;
 }
References default_collection_t::defaults, i, default_t::name, name, NULL, default_collection_t::numdefaults, and strcmp().
Referenced by GetDefaultForName(), and LoadDefaultCollection().
SetVariable()
static void SetVariable (default_t * def, char * value) static
Definition at line 1728 of file m_config.c.
 {
     int intparm;
     // parameter found
     switch (def->type)
     {
         case DEFAULT_STRING:
             * (char **) def->location = strdup(value);
             break;
         case DEFAULT_INT:
         case DEFAULT_INT_HEX:
             * (int *) def->location = ParseIntParameter(value);
             break;
         case DEFAULT_KEY:
             // translate scancodes read from config
             // file (save the old value in untranslated)
             intparm = ParseIntParameter(value);
             def->untranslated = intparm;
             if (intparm >= 0 && intparm < 128)
             {
                 intparm = scantokey[intparm];
             }
             else
             {
                 intparm = 0;
             }
             def->original_translated = intparm;
             * (int *) def->location = intparm;
             break;
         case DEFAULT_FLOAT:
             * (float *) def->location = (float) atof(value);
             break;
     }
 }
References atof(), DEFAULT_FLOAT, DEFAULT_INT, DEFAULT_INT_HEX, DEFAULT_KEY, DEFAULT_STRING, default_t::location, default_t::original_translated, ParseIntParameter(), scantokey, strdup(), default_t::type, default_t::untranslated, and value.
Referenced by LoadDefaultCollection(), and M_SetVariable().
Variable Documentation
configdir
char* configdir
Definition at line 45 of file m_config.c.
Referenced by D_DoomMain(), M_GetSaveGameDir(), M_LoadDefaults(), and M_SetConfigDir().
default_extra_config
char* default_extra_config static
Definition at line 50 of file m_config.c.
Referenced by M_LoadDefaults(), and M_SetConfigFilenames().
default_main_config
char* default_main_config static
Definition at line 49 of file m_config.c.
Referenced by M_LoadDefaults(), and M_SetConfigFilenames().
doom_defaults
default_collection_t doom_defaults static
Initial value:
=
{
    doom_defaults_list,
    arrlen(doom_defaults_list),
    NULL,
}
Definition at line 675 of file m_config.c.
Referenced by GetDefaultForName(), M_LoadDefaults(), M_SaveDefaults(), and M_SaveDefaultsAlternate().
doom_defaults_list
default_t doom_defaults_list[] static
@begin_config_file default
Definition at line 111 of file m_config.c.
extra_defaults
default_collection_t extra_defaults static
Initial value:
=
{
    extra_defaults_list,
    arrlen(extra_defaults_list),
    NULL,
}
Definition at line 1554 of file m_config.c.
Referenced by GetDefaultForName(), M_LoadDefaults(), M_SaveDefaults(), and M_SaveDefaultsAlternate().
extra_defaults_list
default_t extra_defaults_list[] static
@begin_config_file extended
Definition at line 684 of file m_config.c.
scantokey
const int scantokey[128] static
Initial value:
=
{
    0  ,    27,     '1',    '2',    '3',    '4',    '5',    '6',
    '7',    '8',    '9',    '0',    '-',    '=',    KEY_BACKSPACE, 9,
    'q',    'w',    'e',    'r',    't',    'y',    'u',    'i',
    'o',    'p',    '[',    ']',    13,     KEY_RCTRL, 'a',    's',
    'd',    'f',    'g',    'h',    'j',    'k',    'l',    ';',
    '\'',   '`',    KEY_RSHIFT,'\\',   'z',    'x',    'c',    'v',
    'b',    'n',    'm',    ',',    '.',    '/',    KEY_RSHIFT,KEYP_MULTIPLY,
    KEY_RALT,  ' ',  KEY_CAPSLOCK,KEY_F1,  KEY_F2,   KEY_F3,   KEY_F4,   KEY_F5,
    KEY_F6,   KEY_F7,   KEY_F8,   KEY_F9,   KEY_F10,  KEY_PAUSE,KEY_SCRLCK,KEY_HOME,
    KEY_UPARROW,KEY_PGUP,KEY_MINUS,KEY_LEFTARROW,KEYP_5,KEY_RIGHTARROW,KEYP_PLUS,KEY_END,
    KEY_DOWNARROW,KEY_PGDN,KEY_INS,KEY_DEL,0,   0,      0,      KEY_F11,
    KEY_F12,  0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      0,      0,
    0,      0,      0,      0,      0,      0,      KEY_PRTSCR, 0
}
Definition at line 1588 of file m_config.c.
Referenced by SaveDefaultCollection(), and SetVariable().