Fennix Userspace: Userspace/mlibc/options/elf/generic/phdr.cpp File Reference
phdr.cpp File Reference
#include <link.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
Functions
int __dlapi_iterate_phdr (int(*)(struct dl_phdr_info *, size_t, void *), void *)
int dl_iterate_phdr (int(*callback)(struct dl_phdr_info *, size_t, void *), void *data)
Function Documentation
__dlapi_iterate_phdr()
int __dlapi_iterate_phdr (int(*)(struct dl_phdr_info *, size_t, void *) callback, void * data)
Definition at line 657 of file main.cpp.
{
     int last_return = 0;
     for (auto object : initialRepository->loadedObjects) {
         struct dl_phdr_info info;
         info.dlpi_addr = object->baseAddress;
         info.dlpi_name = object->name.data();
         if(object->isMainObject) {
             info.dlpi_name = "";
         } else {
             info.dlpi_name = object->name.data();
         }
         info.dlpi_phdr = static_cast<ElfW(Phdr)*>(object->phdrPointer);
         info.dlpi_phnum = object->phdrCount;
         info.dlpi_adds = rtsCounter;
         info.dlpi_subs = 0; // TODO(geert): implement dlclose().
         if (object->tlsModel != TlsModel::null)
             info.dlpi_tls_modid = object->tlsIndex;
         else
             info.dlpi_tls_modid = 0;
         info.dlpi_tls_data = tryAccessDtv(object);
         last_return = callback(&info, sizeof(struct dl_phdr_info), data);
         if(last_return)
             return last_return;
     }
     return last_return;
 }
References callback, dl_phdr_info::dlpi_adds, dl_phdr_info::dlpi_name, dl_phdr_info::dlpi_subs, dl_phdr_info::dlpi_tls_data, dl_phdr_info::dlpi_tls_modid, ElfW(), initialRepository, SharedObject::isMainObject, null, rtsCounter, SharedObject::tlsModel, and tryAccessDtv().
Referenced by dl_iterate_phdr().
dl_iterate_phdr()
int dl_iterate_phdr (int(*)(struct dl_phdr_info *, size_t, void *) callback, void * data)
Definition at line 8 of file phdr.cpp.
{
     return __dlapi_iterate_phdr(callback, data);
 }
References __dlapi_iterate_phdr(), and callback.
Referenced by __gnu_Unwind_Find_exidx(), and main().