Fennix Userspace: Userspace/apps/base/bash/lib/sh/times.c File Reference
times.c File Reference
#include <config.h>
#include <sys/types.h>
#include <posixtime.h>
#include <systimes.h>
Macros
#define CONVTCK(r) (r.tv_sec * clk_tck + r.tv_usec / (1000000 / clk_tck))
Functions
long get_clk_tck PARAMS ((void))
clock_t times (struct tms *tms)
Macro Definition Documentation
CONVTCK
#define CONVTCK (r) (r.tv_sec * clk_tck + r.tv_usec / (1000000 / clk_tck))
Definition at line 35 of file times.c.
Function Documentation
PARAMS()
long get_clk_tck PARAMS ((void))
times()
clock_t times (struct tms * tms)
Definition at line 38 of file times.c.
 {
     clock_t rv;
     static long clk_tck = -1;
 #if defined (HAVE_GETRUSAGE)
     struct timeval tv;
     struct rusage ru;
     if (clk_tck == -1)
         clk_tck = get_clk_tck();
     if (getrusage(RUSAGE_SELF, &ru) < 0)
         return ((clock_t)-1);
     tms->tms_utime = CONVTCK(ru.ru_utime);
     tms->tms_stime = CONVTCK(ru.ru_stime);
     if (getrusage(RUSAGE_CHILDREN, &ru) < 0)
         return ((clock_t)-1);
     tms->tms_cutime = CONVTCK(ru.ru_utime);
     tms->tms_cstime = CONVTCK(ru.ru_stime);
     if (gettimeofday(&tv, NULL) < 0)
         return ((clock_t)-1);
     rv = (clock_t)(CONVTCK(tv));
 #else /* !HAVE_GETRUSAGE */
     if (clk_tck == -1)
         clk_tck = get_clk_tck();
     /* We can't do anything. */
     tms->tms_utime = tms->tms_stime = (clock_t)0;
     tms->tms_cutime = tms->tms_cstime = (clock_t)0;
     rv = (clock_t)time((time_t *)0) * clk_tck;
 # endif /* HAVE_GETRUSAGE */
     return rv;
 }
References CONVTCK, get_clk_tck(), getrusage(), gettimeofday(), NULL, mlibc::ru, rusage::ru_stime, rusage::ru_utime, RUSAGE_CHILDREN, RUSAGE_SELF, time(), tms::tms_cstime, tms::tms_cutime, tms::tms_stime, and tms::tms_utime.
Referenced by __futimesat(), futimens(), futimes(), lutimes(), shift_args(), mlibc::sys_utimensat(), utime(), utimensat(), and utimes().