Fennix Userspace: Userspace/musl/include/complex.h File Reference
complex.h File Reference
Macros
#define complex _Complex
#define _Complex_I (0.0f+1.0fi)
#define I _Complex_I
#define __CIMAG(x, t) (+(union { _Complex t __z; t __xy[2]; }){(_Complex t)(x)}.__xy[1])
#define creal(x) ((double)(x))
#define crealf(x) ((float)(x))
#define creall(x) ((long double)(x))
#define cimag(x) __CIMAG(x, double)
#define cimagf(x) __CIMAG(x, float)
#define cimagl(x) __CIMAG(x, long double)
Functions
double complex cacos (double complex)
float complex cacosf (float complex)
long double complex cacosl (long double complex)
double complex casin (double complex)
float complex casinf (float complex)
long double complex casinl (long double complex)
double complex catan (double complex)
float complex catanf (float complex)
long double complex catanl (long double complex)
double complex ccos (double complex)
float complex ccosf (float complex)
long double complex ccosl (long double complex)
double complex csin (double complex)
float complex csinf (float complex)
long double complex csinl (long double complex)
double complex ctan (double complex)
float complex ctanf (float complex)
long double complex ctanl (long double complex)
double complex cacosh (double complex)
float complex cacoshf (float complex)
long double complex cacoshl (long double complex)
double complex casinh (double complex)
float complex casinhf (float complex)
long double complex casinhl (long double complex)
double complex catanh (double complex)
float complex catanhf (float complex)
long double complex catanhl (long double complex)
double complex ccosh (double complex)
float complex ccoshf (float complex)
long double complex ccoshl (long double complex)
double complex csinh (double complex)
float complex csinhf (float complex)
long double complex csinhl (long double complex)
double complex ctanh (double complex)
float complex ctanhf (float complex)
long double complex ctanhl (long double complex)
double complex cexp (double complex)
float complex cexpf (float complex)
long double complex cexpl (long double complex)
double complex clog (double complex)
float complex clogf (float complex)
long double complex clogl (long double complex)
double cabs (double complex)
float cabsf (float complex)
long double cabsl (long double complex)
double complex cpow (double complex, double complex)
float complex cpowf (float complex, float complex)
long double complex cpowl (long double complex, long double complex)
double complex csqrt (double complex)
float complex csqrtf (float complex)
long double complex csqrtl (long double complex)
double carg (double complex)
float cargf (float complex)
long double cargl (long double complex)
double cimag (double complex)
float cimagf (float complex)
long double cimagl (long double complex)
double complex conj (double complex)
float complex conjf (float complex)
long double complex conjl (long double complex)
double complex cproj (double complex)
float complex cprojf (float complex)
long double complex cprojl (long double complex)
double creal (double complex)
float crealf (float complex)
long double creall (long double complex)
Macro Definition Documentation
__CIMAG
#define __CIMAG (x, t) (+(union { _Complex t __z; t __xy[2]; }){(_Complex t)(x)}.__xy[1])
Definition at line 105 of file complex.h.
_Complex_I
#define _Complex_I (0.0f+1.0fi)
Definition at line 12 of file complex.h.
cimag
#define cimag (x) __CIMAG(x, double)
Definition at line 112 of file complex.h.
cimagf
#define cimagf (x) __CIMAG(x, float)
Definition at line 113 of file complex.h.
cimagl
#define cimagl (x) __CIMAG(x, long double)
Definition at line 114 of file complex.h.
complex
#define complex _Complex
Definition at line 8 of file complex.h.
creal
#define creal (x) ((double)(x))
Definition at line 108 of file complex.h.
crealf
#define crealf (x) ((float)(x))
Definition at line 109 of file complex.h.
creall
#define creall (x) ((long double)(x))
Definition at line 110 of file complex.h.
I
#define I _Complex_I
Definition at line 14 of file complex.h.
Function Documentation
cabs()
double cabs (double complex)
Definition at line 3 of file cabs.c.
 {
     return hypot(creal(z), cimag(z));
 }
References cimag, creal, and hypot.
Referenced by clog().
cabsf()
float cabsf (float complex)
Definition at line 3 of file cabsf.c.
 {
     return hypotf(crealf(z), cimagf(z));
 }
References cimagf, crealf, and hypotf().
Referenced by clogf().
cabsl()
long double cabsl (long double complex)
Definition at line 9 of file cabsl.c.
 {
     return hypotl(creall(z), cimagl(z));
 }
References cimagl, creall, and hypotl().
Referenced by clogl().
cacos()
double complex cacos (double complex)
Definition at line 7 of file cacos.c.
 {
     z = casin(z);
     return CMPLX(M_PI_2 - creal(z), -cimag(z));
 }
References casin(), cimag, CMPLX, and creal.
Referenced by cacosh().
cacosf()
float complex cacosf (float complex)
Definition at line 7 of file cacosf.c.
 {
     z = casinf(z);
     return CMPLXF(float_pi_2 - crealf(z), -cimagf(z));
 }
References casinf(), cimagf, CMPLXF, crealf, and float_pi_2.
Referenced by cacoshf().
cacosh()
double complex cacosh (double complex)
Definition at line 5 of file cacosh.c.
 {
     int zineg = signbit(cimag(z));
     z = cacos(z);
     if (zineg) return CMPLX(cimag(z), -creal(z));
     else       return CMPLX(-cimag(z), creal(z));
 }
References cacos(), cimag, CMPLX, creal, and signbit.
cacoshf()
float complex cacoshf (float complex)
Definition at line 3 of file cacoshf.c.
 {
     int zineg = signbit(cimagf(z));
     z = cacosf(z);
     if (zineg) return CMPLXF(cimagf(z), -crealf(z));
     else       return CMPLXF(-cimagf(z), crealf(z));
 }
References cacosf(), cimagf, CMPLXF, crealf, and signbit.
cacoshl()
long double complex cacoshl (long double complex)
Definition at line 9 of file cacoshl.c.
 {
     int zineg = signbit(cimagl(z));
     z = cacosl(z);
     if (zineg) return CMPLXL(cimagl(z), -creall(z));
     else       return CMPLXL(-cimagl(z), creall(z));
 }
References cacosl(), cimagl, CMPLXL, creall, and signbit.
cacosl()
long double complex cacosl (long double complex)
Definition at line 11 of file cacosl.c.
 {
     z = casinl(z);
     return CMPLXL(PI_2 - creall(z), -cimagl(z));
 }
References casinl(), cimagl, CMPLXL, creall, and PI_2.
Referenced by cacoshl().
carg()
double carg (double complex)
Definition at line 3 of file carg.c.
 {
     return atan2(cimag(z), creal(z));
 }
References atan2, cimag, and creal.
cargf()
float cargf (float complex)
Definition at line 3 of file cargf.c.
 {
     return atan2f(cimagf(z), crealf(z));
 }
References atan2f(), cimagf, and crealf.
Referenced by clogf().
cargl()
long double cargl (long double complex)
Definition at line 9 of file cargl.c.
 {
     return atan2l(cimagl(z), creall(z));
 }
References atan2l(), cimagl, and creall.
Referenced by clogl().
casin()
double complex casin (double complex)
Definition at line 7 of file casin.c.
 {
     double complex w;
     double x, y;
     x = creal(z);
     y = cimag(z);
     w = CMPLX(1.0 - (x - y)*(x + y), -2.0*x*y);
     double complex r = clog(CMPLX(-y, x) + csqrt(w));
     return CMPLX(cimag(r), -creal(r));
 }
References cimag, clog(), CMPLX, complex, creal, csqrt(), x, and y.
Referenced by cacos(), and casinh().
casinf()
float complex casinf (float complex)
Definition at line 5 of file casinf.c.
 {
     float complex w;
     float x, y;
     x = crealf(z);
     y = cimagf(z);
     w = CMPLXF(1.0 - (x - y)*(x + y), -2.0*x*y);
     float complex r = clogf(CMPLXF(-y, x) + csqrtf(w));
     return CMPLXF(cimagf(r), -crealf(r));
 }
References cimagf, clogf(), CMPLXF, complex, crealf, csqrtf(), x, and y.
Referenced by cacosf(), and casinhf().
casinh()
double complex casinh (double complex)
Definition at line 5 of file casinh.c.
 {
     z = casin(CMPLX(-cimag(z), creal(z)));
     return CMPLX(cimag(z), -creal(z));
 }
References casin(), cimag, CMPLX, and creal.
casinhf()
float complex casinhf (float complex)
Definition at line 3 of file casinhf.c.
 {
     z = casinf(CMPLXF(-cimagf(z), crealf(z)));
     return CMPLXF(cimagf(z), -crealf(z));
 }
References casinf(), cimagf, CMPLXF, and crealf.
casinhl()
long double complex casinhl (long double complex)
Definition at line 9 of file casinhl.c.
 {
     z = casinl(CMPLXL(-cimagl(z), creall(z)));
     return CMPLXL(cimagl(z), -creall(z));
 }
References casinl(), cimagl, CMPLXL, and creall.
casinl()
long double complex casinl (long double complex)
Definition at line 10 of file casinl.c.
 {
     long double complex w;
     long double x, y;
     x = creall(z);
     y = cimagl(z);
     w = CMPLXL(1.0 - (x - y)*(x + y), -2.0*x*y);
     long double complex r = clogl(CMPLXL(-y, x) + csqrtl(w));
     return CMPLXL(cimagl(r), -creall(r));
 }
References cimagl, clogl(), CMPLXL, complex, creall, csqrtl(), x, and y.
Referenced by cacosl(), and casinhl().
catan()
double complex catan (double complex)
Definition at line 86 of file catan.c.
 {
     double complex w;
     double a, t, x, x2, y;
     x = creal(z);
     y = cimag(z);
     x2 = x * x;
     a = 1.0 - x2 - (y * y);
     t = 0.5 * atan2(2.0 * x, a);
     w = _redupi(t);
     t = y - 1.0;
     a = x2 + (t * t);
     t = y + 1.0;
     a = (x2 + t * t)/a;
     w = CMPLX(w, 0.25 * log(a));
     return w;
 }
References _redupi(), atan2, cimag, CMPLX, complex, creal, log, x, and y.
Referenced by catanh().
catanf()
float complex catanf (float complex)
Definition at line 84 of file catanf.c.
 {
     float complex w;
     float a, t, x, x2, y;
     x = crealf(z);
     y = cimagf(z);
     x2 = x * x;
     a = 1.0f - x2 - (y * y);
     t = 0.5f * atan2f(2.0f * x, a);
     w = _redupif(t);
     t = y - 1.0f;
     a = x2 + (t * t);
     t = y + 1.0f;
     a = (x2 + (t * t))/a;
     w = CMPLXF(w, 0.25f * logf(a));
     return w;
 }
References _redupif(), atan2f(), cimagf, CMPLXF, complex, crealf, logf(), x, and y.
Referenced by catanhf().
catanh()
double complex catanh (double complex)
Definition at line 5 of file catanh.c.
 {
     z = catan(CMPLX(-cimag(z), creal(z)));
     return CMPLX(cimag(z), -creal(z));
 }
References catan(), cimag, CMPLX, and creal.
catanhf()
float complex catanhf (float complex)
Definition at line 3 of file catanhf.c.
 {
     z = catanf(CMPLXF(-cimagf(z), crealf(z)));
     return CMPLXF(cimagf(z), -crealf(z));
 }
References catanf(), cimagf, CMPLXF, and crealf.
catanhl()
long double complex catanhl (long double complex)
Definition at line 9 of file catanhl.c.
 {
     z = catanl(CMPLXL(-cimagl(z), creall(z)));
     return CMPLXL(cimagl(z), -creall(z));
 }
References catanl(), cimagl, CMPLXL, and creall.
catanl()
long double complex catanl (long double complex)
Definition at line 92 of file catanl.c.
 {
     long double complex w;
     long double a, t, x, x2, y;
     x = creall(z);
     y = cimagl(z);
     x2 = x * x;
     a = 1.0L - x2 - (y * y);
     t = atan2l(2.0L * x, a) * 0.5L;
     w = redupil(t);
     t = y - 1.0L;
     a = x2 + (t * t);
     t = y + 1.0L;
     a = (x2 + (t * t)) / a;
     w = CMPLXF(w, 0.25L * logl(a));
     return w;
 }
References atan2l(), cimagl, CMPLXF, complex, creall, logl(), redupil(), x, and y.
Referenced by catanhl().
ccos()
double complex ccos (double complex)
Definition at line 5 of file ccos.c.
 {
     return ccosh(CMPLX(-cimag(z), creal(z)));
 }
References ccosh(), cimag, CMPLX, and creal.
ccosf()
float complex ccosf (float complex)
Definition at line 3 of file ccosf.c.
 {
     return ccoshf(CMPLXF(-cimagf(z), crealf(z)));
 }
References ccoshf(), cimagf, CMPLXF, and crealf.
ccosh()
double complex ccosh (double complex)
Definition at line 41 of file ccosh.c.
 {
     double x, y, h;
     int32_t hx, hy, ix, iy, lx, ly;
     x = creal(z);
     y = cimag(z);
     EXTRACT_WORDS(hx, lx, x);
     EXTRACT_WORDS(hy, ly, y);
     ix = 0x7fffffff & hx;
     iy = 0x7fffffff & hy;
     /* Handle the nearly-non-exceptional cases where x and y are finite. */
     if (ix < 0x7ff00000 && iy < 0x7ff00000) {
         if ((iy | ly) == 0)
             return CMPLX(cosh(x), x * y);
         if (ix < 0x40360000)    /* small x: normal case */
             return CMPLX(cosh(x) * cos(y), sinh(x) * sin(y));
         /* |x| >= 22, so cosh(x) ~= exp(|x|) */
         if (ix < 0x40862e42) {
             /* x < 710: exp(|x|) won't overflow */
             h = exp(fabs(x)) * 0.5;
             return CMPLX(h * cos(y), copysign(h, x) * sin(y));
         } else if (ix < 0x4096bbaa) {
             /* x < 1455: scale to avoid overflow */
             z = __ldexp_cexp(CMPLX(fabs(x), y), -1);
             return CMPLX(creal(z), cimag(z) * copysign(1, x));
         } else {
             /* x >= 1455: the result always overflows */
             h = huge * x;
             return CMPLX(h * h * cos(y), h * sin(y));
         }
     }
     /*
      * cosh(+-0 +- I Inf) = dNaN + I sign(d(+-0, dNaN))0.
      * The sign of 0 in the result is unspecified.  Choice = normally
      * the same as dNaN.  Raise the invalid floating-point exception.
      *
      * cosh(+-0 +- I NaN) = d(NaN) + I sign(d(+-0, NaN))0.
      * The sign of 0 in the result is unspecified.  Choice = normally
      * the same as d(NaN).
      */
     if ((ix | lx) == 0 && iy >= 0x7ff00000)
         return CMPLX(y - y, copysign(0, x * (y - y)));
     /*
      * cosh(+-Inf +- I 0) = +Inf + I (+-)(+-)0.
      *
      * cosh(NaN +- I 0)   = d(NaN) + I sign(d(NaN, +-0))0.
      * The sign of 0 in the result is unspecified.
      */
     if ((iy | ly) == 0 && ix >= 0x7ff00000) {
         if (((hx & 0xfffff) | lx) == 0)
             return CMPLX(x * x, copysign(0, x) * y);
         return CMPLX(x * x, copysign(0, (x + x) * y));
     }
     /*
      * cosh(x +- I Inf) = dNaN + I dNaN.
      * Raise the invalid floating-point exception for finite nonzero x.
      *
      * cosh(x + I NaN) = d(NaN) + I d(NaN).
      * Optionally raises the invalid floating-point exception for finite
      * nonzero x.  Choice = don't raise (except for signaling NaNs).
      */
     if (ix < 0x7ff00000 && iy >= 0x7ff00000)
         return CMPLX(y - y, x * (y - y));
     /*
      * cosh(+-Inf + I NaN)  = +Inf + I d(NaN).
      *
      * cosh(+-Inf +- I Inf) = +Inf + I dNaN.
      * The sign of Inf in the result is unspecified.  Choice = always +.
      * Raise the invalid floating-point exception.
      *
      * cosh(+-Inf + I y)   = +Inf cos(y) +- I Inf sin(y)
      */
     if (ix >= 0x7ff00000 && ((hx & 0xfffff) | lx) == 0) {
         if (iy >= 0x7ff00000)
             return CMPLX(x * x, x * (y - y));
         return CMPLX((x * x) * cos(y), x * sin(y));
     }
     /*
      * cosh(NaN + I NaN)  = d(NaN) + I d(NaN).
      *
      * cosh(NaN +- I Inf) = d(NaN) + I d(NaN).
      * Optionally raises the invalid floating-point exception.
      * Choice = raise.
      *
      * cosh(NaN + I y)    = d(NaN) + I d(NaN).
      * Optionally raises the invalid floating-point exception for finite
      * nonzero y.  Choice = don't raise (except for signaling NaNs).
      */
     return CMPLX((x * x) * (y - y), (x + x) * (y - y));
 }
References __ldexp_cexp(), cimag, CMPLX, copysign, cos, cosh, creal, exp, EXTRACT_WORDS, fabs, huge, sin, sinh, x, and y.
Referenced by ccos(), and ccoshl().
ccoshf()
float complex ccoshf (float complex)
Definition at line 35 of file ccoshf.c.
 {
     float x, y, h;
     int32_t hx, hy, ix, iy;
     x = crealf(z);
     y = cimagf(z);
     GET_FLOAT_WORD(hx, x);
     GET_FLOAT_WORD(hy, y);
     ix = 0x7fffffff & hx;
     iy = 0x7fffffff & hy;
     if (ix < 0x7f800000 && iy < 0x7f800000) {
         if (iy == 0)
             return CMPLXF(coshf(x), x * y);
         if (ix < 0x41100000)    /* small x: normal case */
             return CMPLXF(coshf(x) * cosf(y), sinhf(x) * sinf(y));
         /* |x| >= 9, so cosh(x) ~= exp(|x|) */
         if (ix < 0x42b17218) {
             /* x < 88.7: expf(|x|) won't overflow */
             h = expf(fabsf(x)) * 0.5f;
             return CMPLXF(h * cosf(y), copysignf(h, x) * sinf(y));
         } else if (ix < 0x4340b1e7) {
             /* x < 192.7: scale to avoid overflow */
             z = __ldexp_cexpf(CMPLXF(fabsf(x), y), -1);
             return CMPLXF(crealf(z), cimagf(z) * copysignf(1, x));
         } else {
             /* x >= 192.7: the result always overflows */
             h = huge * x;
             return CMPLXF(h * h * cosf(y), h * sinf(y));
         }
     }
     if (ix == 0 && iy >= 0x7f800000)
         return CMPLXF(y - y, copysignf(0, x * (y - y)));
     if (iy == 0 && ix >= 0x7f800000) {
         if ((hx & 0x7fffff) == 0)
             return CMPLXF(x * x, copysignf(0, x) * y);
         return CMPLXF(x * x, copysignf(0, (x + x) * y));
     }
     if (ix < 0x7f800000 && iy >= 0x7f800000)
         return CMPLXF(y - y, x * (y - y));
     if (ix >= 0x7f800000 && (hx & 0x7fffff) == 0) {
         if (iy >= 0x7f800000)
             return CMPLXF(x * x, x * (y - y));
         return CMPLXF((x * x) * cosf(y), x * sinf(y));
     }
     return CMPLXF((x * x) * (y - y), (x + x) * (y - y));
 }
References __ldexp_cexpf(), cimagf, CMPLXF, copysignf(), cosf(), coshf(), crealf, expf(), fabsf(), GET_FLOAT_WORD, huge, sinf(), sinhf(), x, and y.
Referenced by ccosf().
ccoshl()
long double complex ccoshl (long double complex)
Definition at line 4 of file ccoshl.c.
 {
     return ccosh(z);
 }
References ccosh().
Referenced by ccosl().
ccosl()
long double complex ccosl (long double complex)
Definition at line 9 of file ccosl.c.
 {
     return ccoshl(CMPLXL(-cimagl(z), creall(z)));
 }
References ccoshl(), cimagl, CMPLXL, and creall.
cexp()
double complex cexp (double complex)
Definition at line 34 of file cexp.c.
 {
     double x, y, exp_x;
     uint32_t hx, hy, lx, ly;
     x = creal(z);
     y = cimag(z);
     EXTRACT_WORDS(hy, ly, y);
     hy &= 0x7fffffff;
     /* cexp(x + I 0) = exp(x) + I 0 */
     if ((hy | ly) == 0)
         return CMPLX(exp(x), y);
     EXTRACT_WORDS(hx, lx, x);
     /* cexp(0 + I y) = cos(y) + I sin(y) */
     if (((hx & 0x7fffffff) | lx) == 0)
         return CMPLX(cos(y), sin(y));
     if (hy >= 0x7ff00000) {
         if (lx != 0 || (hx & 0x7fffffff) != 0x7ff00000) {
             /* cexp(finite|NaN +- I Inf|NaN) = NaN + I NaN */
             return CMPLX(y - y, y - y);
         } else if (hx & 0x80000000) {
             /* cexp(-Inf +- I Inf|NaN) = 0 + I 0 */
             return CMPLX(0.0, 0.0);
         } else {
             /* cexp(+Inf +- I Inf|NaN) = Inf + I NaN */
             return CMPLX(x, y - y);
         }
     }
     if (hx >= exp_ovfl && hx <= cexp_ovfl) {
         /*
          * x is between 709.7 and 1454.3, so we must scale to avoid
          * overflow in exp(x).
          */
         return __ldexp_cexp(z, 0);
     } else {
         /*
          * Cases covered here:
          *  -  x < exp_ovfl and exp(x) won't overflow (common case)
          *  -  x > cexp_ovfl, so exp(x) * s overflows for all s > 0
          *  -  x = +-Inf (generated by exp())
          *  -  x = NaN (spurious inexact exception from y)
          */
         exp_x = exp(x);
         return CMPLX(exp_x * cos(y), exp_x * sin(y));
     }
 }
References __ldexp_cexp(), cexp_ovfl, cimag, CMPLX, cos, creal, exp, exp_ovfl, EXTRACT_WORDS, sin, x, and y.
Referenced by cexpl(), and cpow().
cexpf()
float complex cexpf (float complex)
Definition at line 34 of file cexpf.c.
 {
     float x, y, exp_x;
     uint32_t hx, hy;
     x = crealf(z);
     y = cimagf(z);
     GET_FLOAT_WORD(hy, y);
     hy &= 0x7fffffff;
     /* cexp(x + I 0) = exp(x) + I 0 */
     if (hy == 0)
         return CMPLXF(expf(x), y);
     GET_FLOAT_WORD(hx, x);
     /* cexp(0 + I y) = cos(y) + I sin(y) */
     if ((hx & 0x7fffffff) == 0)
         return CMPLXF(cosf(y), sinf(y));
     if (hy >= 0x7f800000) {
         if ((hx & 0x7fffffff) != 0x7f800000) {
             /* cexp(finite|NaN +- I Inf|NaN) = NaN + I NaN */
             return CMPLXF(y - y, y - y);
         } else if (hx & 0x80000000) {
             /* cexp(-Inf +- I Inf|NaN) = 0 + I 0 */
             return CMPLXF(0.0, 0.0);
         } else {
             /* cexp(+Inf +- I Inf|NaN) = Inf + I NaN */
             return CMPLXF(x, y - y);
         }
     }
     if (hx >= exp_ovfl && hx <= cexp_ovfl) {
         /*
          * x is between 88.7 and 192, so we must scale to avoid
          * overflow in expf(x).
          */
         return __ldexp_cexpf(z, 0);
     } else {
         /*
          * Cases covered here:
          *  -  x < exp_ovfl and exp(x) won't overflow (common case)
          *  -  x > cexp_ovfl, so exp(x) * s overflows for all s > 0
          *  -  x = +-Inf (generated by exp())
          *  -  x = NaN (spurious inexact exception from y)
          */
         exp_x = expf(x);
         return CMPLXF(exp_x * cosf(y), exp_x * sinf(y));
     }
 }
References __ldexp_cexpf(), cexp_ovfl, cimagf, CMPLXF, cosf(), crealf, exp_ovfl, expf(), GET_FLOAT_WORD, sinf(), x, and y.
Referenced by cpowf().
cexpl()
long double complex cexpl (long double complex)
Definition at line 4 of file cexpl.c.
 {
     return cexp(z);
 }
References cexp().
Referenced by cpowl().
cimag()
double cimag (double complex)
Definition at line 3 of file cimag.c.
 {
     return cimag(z);
 }
References cimag().
Referenced by cimag().
cimagf()
float cimagf (float complex)
Definition at line 3 of file cimagf.c.
 {
     return cimagf(z);
 }
References cimagf().
Referenced by cimagf().
cimagl()
long double cimagl (long double complex)
Definition at line 3 of file cimagl.c.
 {
     return cimagl(z);
 }
References cimagl().
Referenced by cimagl().
clog()
double complex clog (double complex)
Definition at line 7 of file clog.c.
 {
     double r, phi;
     r = cabs(z);
     phi = carg(z);
     return CMPLX(log(r), phi);
 }
References cabs(), carg, CMPLX, and log.
Referenced by casin(), and cpow().
clogf()
float complex clogf (float complex)
Definition at line 5 of file clogf.c.
 {
     float r, phi;
     r = cabsf(z);
     phi = cargf(z);
     return CMPLXF(logf(r), phi);
 }
References cabsf(), cargf(), CMPLXF, and logf().
Referenced by casinf(), and cpowf().
clogl()
long double complex clogl (long double complex)
Definition at line 10 of file clogl.c.
 {
     long double r, phi;
     r = cabsl(z);
     phi = cargl(z);
     return CMPLXL(logl(r), phi);
 }
References cabsl(), cargl(), CMPLXL, and logl().
Referenced by casinl(), and cpowl().
conj()
double complex conj (double complex)
Definition at line 3 of file conj.c.
 {
     return CMPLX(creal(z), -cimag(z));
 }
References cimag, CMPLX, and creal.
conjf()
float complex conjf (float complex)
Definition at line 3 of file conjf.c.
 {
     return CMPLXF(crealf(z), -cimagf(z));
 }
References cimagf, CMPLXF, and crealf.
conjl()
long double complex conjl (long double complex)
Definition at line 3 of file conjl.c.
 {
     return CMPLXL(creall(z), -cimagl(z));
 }
References cimagl, CMPLXL, and creall.
cpow()
double complex cpow (double complex, double complex)
Definition at line 5 of file cpow.c.
 {
     return cexp(c * clog(z));
 }
References cexp(), and clog().
cpowf()
float complex cpowf (float complex, float complex)
Definition at line 3 of file cpowf.c.
 {
     return cexpf(c * clogf(z));
 }
References cexpf(), and clogf().
cpowl()
long double complex cpowl (long double complex, long double complex)
Definition at line 9 of file cpowl.c.
 {
     return cexpl(c * clogl(z));
 }
References cexpl(), and clogl().
cproj()
double complex cproj (double complex)
Definition at line 3 of file cproj.c.
 {
     if (isinf(creal(z)) || isinf(cimag(z)))
         return CMPLX(INFINITY, copysign(0.0, cimag(z)));
     return z;
 }
References cimag, CMPLX, copysign, creal, INFINITY, and isinf.
cprojf()
float complex cprojf (float complex)
Definition at line 3 of file cprojf.c.
 {
     if (isinf(crealf(z)) || isinf(cimagf(z)))
         return CMPLXF(INFINITY, copysignf(0.0, cimagf(z)));
     return z;
 }
References cimagf, CMPLXF, copysignf(), crealf, INFINITY, and isinf.
cprojl()
long double complex cprojl (long double complex)
Definition at line 9 of file cprojl.c.
 {
     if (isinf(creall(z)) || isinf(cimagl(z)))
         return CMPLXL(INFINITY, copysignl(0.0, cimagl(z)));
     return z;
 }
References cimagl, CMPLXL, copysignl(), creall, INFINITY, and isinf.
creal()
double creal (double complex)
Definition at line 3 of file creal.c.
 {
     return creal(z);
 }
References creal().
Referenced by creal().
crealf()
float crealf (float complex)
Definition at line 3 of file crealf.c.
 {
     return crealf(z);
 }
References crealf().
Referenced by crealf().
creall()
long double creall (long double complex)
Definition at line 3 of file creall.c.
 {
     return creall(z);
 }
References creall().
Referenced by creall().
csin()
double complex csin (double complex)
Definition at line 5 of file csin.c.
 {
     z = csinh(CMPLX(-cimag(z), creal(z)));
     return CMPLX(cimag(z), -creal(z));
 }
References cimag, CMPLX, creal, and csinh().
csinf()
float complex csinf (float complex)
Definition at line 3 of file csinf.c.
 {
     z = csinhf(CMPLXF(-cimagf(z), crealf(z)));
     return CMPLXF(cimagf(z), -crealf(z));
 }
References cimagf, CMPLXF, crealf, and csinhf().
csinh()
double complex csinh (double complex)
Definition at line 41 of file csinh.c.
 {
     double x, y, h;
     int32_t hx, hy, ix, iy, lx, ly;
     x = creal(z);
     y = cimag(z);
     EXTRACT_WORDS(hx, lx, x);
     EXTRACT_WORDS(hy, ly, y);
     ix = 0x7fffffff & hx;
     iy = 0x7fffffff & hy;
     /* Handle the nearly-non-exceptional cases where x and y are finite. */
     if (ix < 0x7ff00000 && iy < 0x7ff00000) {
         if ((iy | ly) == 0)
             return CMPLX(sinh(x), y);
         if (ix < 0x40360000)    /* small x: normal case */
             return CMPLX(sinh(x) * cos(y), cosh(x) * sin(y));
         /* |x| >= 22, so cosh(x) ~= exp(|x|) */
         if (ix < 0x40862e42) {
             /* x < 710: exp(|x|) won't overflow */
             h = exp(fabs(x)) * 0.5;
             return CMPLX(copysign(h, x) * cos(y), h * sin(y));
         } else if (ix < 0x4096bbaa) {
             /* x < 1455: scale to avoid overflow */
             z = __ldexp_cexp(CMPLX(fabs(x), y), -1);
             return CMPLX(creal(z) * copysign(1, x), cimag(z));
         } else {
             /* x >= 1455: the result always overflows */
             h = huge * x;
             return CMPLX(h * cos(y), h * h * sin(y));
         }
     }
     /*
      * sinh(+-0 +- I Inf) = sign(d(+-0, dNaN))0 + I dNaN.
      * The sign of 0 in the result is unspecified.  Choice = normally
      * the same as dNaN.  Raise the invalid floating-point exception.
      *
      * sinh(+-0 +- I NaN) = sign(d(+-0, NaN))0 + I d(NaN).
      * The sign of 0 in the result is unspecified.  Choice = normally
      * the same as d(NaN).
      */
     if ((ix | lx) == 0 && iy >= 0x7ff00000)
         return CMPLX(copysign(0, x * (y - y)), y - y);
     /*
      * sinh(+-Inf +- I 0) = +-Inf + I +-0.
      *
      * sinh(NaN +- I 0)   = d(NaN) + I +-0.
      */
     if ((iy | ly) == 0 && ix >= 0x7ff00000) {
         if (((hx & 0xfffff) | lx) == 0)
             return CMPLX(x, y);
         return CMPLX(x, copysign(0, y));
     }
     /*
      * sinh(x +- I Inf) = dNaN + I dNaN.
      * Raise the invalid floating-point exception for finite nonzero x.
      *
      * sinh(x + I NaN) = d(NaN) + I d(NaN).
      * Optionally raises the invalid floating-point exception for finite
      * nonzero x.  Choice = don't raise (except for signaling NaNs).
      */
     if (ix < 0x7ff00000 && iy >= 0x7ff00000)
         return CMPLX(y - y, x * (y - y));
     /*
      * sinh(+-Inf + I NaN)  = +-Inf + I d(NaN).
      * The sign of Inf in the result is unspecified.  Choice = normally
      * the same as d(NaN).
      *
      * sinh(+-Inf +- I Inf) = +Inf + I dNaN.
      * The sign of Inf in the result is unspecified.  Choice = always +.
      * Raise the invalid floating-point exception.
      *
      * sinh(+-Inf + I y)   = +-Inf cos(y) + I Inf sin(y)
      */
     if (ix >= 0x7ff00000 && ((hx & 0xfffff) | lx) == 0) {
         if (iy >= 0x7ff00000)
             return CMPLX(x * x, x * (y - y));
         return CMPLX(x * cos(y), INFINITY * sin(y));
     }
     /*
      * sinh(NaN + I NaN)  = d(NaN) + I d(NaN).
      *
      * sinh(NaN +- I Inf) = d(NaN) + I d(NaN).
      * Optionally raises the invalid floating-point exception.
      * Choice = raise.
      *
      * sinh(NaN + I y)    = d(NaN) + I d(NaN).
      * Optionally raises the invalid floating-point exception for finite
      * nonzero y.  Choice = don't raise (except for signaling NaNs).
      */
     return CMPLX((x * x) * (y - y), (x + x) * (y - y));
 }
References __ldexp_cexp(), cimag, CMPLX, copysign, cos, cosh, creal, exp, EXTRACT_WORDS, fabs, huge, INFINITY, sin, sinh, x, and y.
Referenced by csin(), and csinhl().
csinhf()
float complex csinhf (float complex)
Definition at line 35 of file csinhf.c.
 {
     float x, y, h;
     int32_t hx, hy, ix, iy;
     x = crealf(z);
     y = cimagf(z);
     GET_FLOAT_WORD(hx, x);
     GET_FLOAT_WORD(hy, y);
     ix = 0x7fffffff & hx;
     iy = 0x7fffffff & hy;
     if (ix < 0x7f800000 && iy < 0x7f800000) {
         if (iy == 0)
             return CMPLXF(sinhf(x), y);
         if (ix < 0x41100000)    /* small x: normal case */
             return CMPLXF(sinhf(x) * cosf(y), coshf(x) * sinf(y));
         /* |x| >= 9, so cosh(x) ~= exp(|x|) */
         if (ix < 0x42b17218) {
             /* x < 88.7: expf(|x|) won't overflow */
             h = expf(fabsf(x)) * 0.5f;
             return CMPLXF(copysignf(h, x) * cosf(y), h * sinf(y));
         } else if (ix < 0x4340b1e7) {
             /* x < 192.7: scale to avoid overflow */
             z = __ldexp_cexpf(CMPLXF(fabsf(x), y), -1);
             return CMPLXF(crealf(z) * copysignf(1, x), cimagf(z));
         } else {
             /* x >= 192.7: the result always overflows */
             h = huge * x;
             return CMPLXF(h * cosf(y), h * h * sinf(y));
         }
     }
     if (ix == 0 && iy >= 0x7f800000)
         return CMPLXF(copysignf(0, x * (y - y)), y - y);
     if (iy == 0 && ix >= 0x7f800000) {
         if ((hx & 0x7fffff) == 0)
             return CMPLXF(x, y);
         return CMPLXF(x, copysignf(0, y));
     }
     if (ix < 0x7f800000 && iy >= 0x7f800000)
         return CMPLXF(y - y, x * (y - y));
     if (ix >= 0x7f800000 && (hx & 0x7fffff) == 0) {
         if (iy >= 0x7f800000)
             return CMPLXF(x * x, x * (y - y));
         return CMPLXF(x * cosf(y), INFINITY * sinf(y));
     }
     return CMPLXF((x * x) * (y - y), (x + x) * (y - y));
 }
References __ldexp_cexpf(), cimagf, CMPLXF, copysignf(), cosf(), coshf(), crealf, expf(), fabsf(), GET_FLOAT_WORD, huge, INFINITY, sinf(), sinhf(), x, and y.
Referenced by csinf().
csinhl()
long double complex csinhl (long double complex)
Definition at line 4 of file csinhl.c.
 {
     return csinh(z);
 }
References csinh().
Referenced by csinl().
csinl()
long double complex csinl (long double complex)
Definition at line 9 of file csinl.c.
 {
     z = csinhl(CMPLXL(-cimagl(z), creall(z)));
     return CMPLXL(cimagl(z), -creall(z));
 }
References cimagl, CMPLXL, creall, and csinhl().
csqrt()
double complex csqrt (double complex)
Definition at line 42 of file csqrt.c.
 {
     double complex result;
     double a, b;
     double t;
     int scale;
     a = creal(z);
     b = cimag(z);
     /* Handle special cases. */
     if (z == 0)
         return CMPLX(0, b);
     if (isinf(b))
         return CMPLX(INFINITY, b);
     if (isnan(a)) {
         t = (b - b) / (b - b);  /* raise invalid if b is not a NaN */
         return CMPLX(a, t);   /* return NaN + NaN i */
     }
     if (isinf(a)) {
         /*
          * csqrt(inf + NaN i)  = inf +  NaN i
          * csqrt(inf + y i)    = inf +  0 i
          * csqrt(-inf + NaN i) = NaN +- inf i
          * csqrt(-inf + y i)   = 0   +  inf i
          */
         if (signbit(a))
             return CMPLX(fabs(b - b), copysign(a, b));
         else
             return CMPLX(a, copysign(b - b, b));
     }
     /*
      * The remaining special case (b is NaN) is handled just fine by
      * the normal code path below.
      */
     /* Scale to avoid overflow. */
     if (fabs(a) >= THRESH || fabs(b) >= THRESH) {
         a *= 0.25;
         b *= 0.25;
         scale = 1;
     } else {
         scale = 0;
     }
     /* Algorithm 312, CACM vol 10, Oct 1967. */
     if (a >= 0) {
         t = sqrt((a + hypot(a, b)) * 0.5);
         result = CMPLX(t, b / (2 * t));
     } else {
         t = sqrt((-a + hypot(a, b)) * 0.5);
         result = CMPLX(fabs(b) / (2 * t), copysign(t, b));
     }
     /* Rescale. */
     if (scale)
         result *= 2;
     return result;
 }
References cimag, CMPLX, complex, copysign, creal, fabs, hypot, INFINITY, isinf, isnan, signbit, sqrt, and THRESH.
Referenced by casin(), and csqrtl().
csqrtf()
float complex csqrtf (float complex)
Definition at line 39 of file csqrtf.c.
 {
     float a = crealf(z), b = cimagf(z);
     double t;
     /* Handle special cases. */
     if (z == 0)
         return CMPLXF(0, b);
     if (isinf(b))
         return CMPLXF(INFINITY, b);
     if (isnan(a)) {
         t = (b - b) / (b - b);  /* raise invalid if b is not a NaN */
         return CMPLXF(a, t);  /* return NaN + NaN i */
     }
     if (isinf(a)) {
         /*
          * csqrtf(inf + NaN i)  = inf +  NaN i
          * csqrtf(inf + y i)    = inf +  0 i
          * csqrtf(-inf + NaN i) = NaN +- inf i
          * csqrtf(-inf + y i)   = 0   +  inf i
          */
         if (signbit(a))
             return CMPLXF(fabsf(b - b), copysignf(a, b));
         else
             return CMPLXF(a, copysignf(b - b, b));
     }
     /*
      * The remaining special case (b is NaN) is handled just fine by
      * the normal code path below.
      */
     /*
      * We compute t in double precision to avoid overflow and to
      * provide correct rounding in nearly all cases.
      * This is Algorithm 312, CACM vol 10, Oct 1967.
      */
     if (a >= 0) {
         t = sqrt((a + hypot(a, b)) * 0.5);
         return CMPLXF(t, b / (2.0 * t));
     } else {
         t = sqrt((-a + hypot(a, b)) * 0.5);
         return CMPLXF(fabsf(b) / (2.0 * t), copysignf(t, b));
     }
 }
References cimagf, CMPLXF, copysignf(), crealf, fabsf(), hypot, INFINITY, isinf, isnan, signbit, and sqrt.
Referenced by casinf().
csqrtl()
long double complex csqrtl (long double complex)
Definition at line 4 of file csqrtl.c.
 {
     return csqrt(z);
 }
References csqrt().
Referenced by casinl().
ctan()
double complex ctan (double complex)
Definition at line 5 of file ctan.c.
 {
     z = ctanh(CMPLX(-cimag(z), creal(z)));
     return CMPLX(cimag(z), -creal(z));
 }
References cimag, CMPLX, creal, and ctanh().
ctanf()
float complex ctanf (float complex)
Definition at line 3 of file ctanf.c.
 {
     z = ctanhf(CMPLXF(-cimagf(z), crealf(z)));
     return CMPLXF(cimagf(z), -crealf(z));
 }
References cimagf, CMPLXF, crealf, and ctanhf().
ctanh()
double complex ctanh (double complex)
Definition at line 68 of file ctanh.c.
 {
     double x, y;
     double t, beta, s, rho, denom;
     uint32_t hx, ix, lx;
     x = creal(z);
     y = cimag(z);
     EXTRACT_WORDS(hx, lx, x);
     ix = hx & 0x7fffffff;
     /*
      * ctanh(NaN + i 0) = NaN + i 0
      *
      * ctanh(NaN + i y) = NaN + i NaN               for y != 0
      *
      * The imaginary part has the sign of x*sin(2*y), but there's no
      * special effort to get this right.
      *
      * ctanh(+-Inf +- i Inf) = +-1 +- 0
      *
      * ctanh(+-Inf + i y) = +-1 + 0 sin(2y)         for y finite
      *
      * The imaginary part of the sign is unspecified.  This special
      * case is only needed to avoid a spurious invalid exception when
      * y is infinite.
      */
     if (ix >= 0x7ff00000) {
         if ((ix & 0xfffff) | lx)        /* x is NaN */
             return CMPLX(x, (y == 0 ? y : x * y));
         SET_HIGH_WORD(x, hx - 0x40000000);      /* x = copysign(1, x) */
         return CMPLX(x, copysign(0, isinf(y) ? y : sin(y) * cos(y)));
     }
     /*
      * ctanh(+-0 + i NAN) = +-0 + i NaN
      * ctanh(+-0 +- i Inf) = +-0 + i NaN
      * ctanh(x + i NAN) = NaN + i NaN
      * ctanh(x +- i Inf) = NaN + i NaN
      */
     if (!isfinite(y))
         return CMPLX(x ? y - y : x, y - y);
     /*
      * ctanh(+-huge + i +-y) ~= +-1 +- i 2sin(2y)/exp(2x), using the
      * approximation sinh^2(huge) ~= exp(2*huge) / 4.
      * We use a modified formula to avoid spurious overflow.
      */
     if (ix >= 0x40360000) { /* x >= 22 */
         double exp_mx = exp(-fabs(x));
         return CMPLX(copysign(1, x), 4 * sin(y) * cos(y) * exp_mx * exp_mx);
     }
     /* Kahan's algorithm */
     t = tan(y);
     beta = 1.0 + t * t;     /* = 1 / cos^2(y) */
     s = sinh(x);
     rho = sqrt(1 + s * s);  /* = cosh(x) */
     denom = 1 + beta * s * s;
     return CMPLX((beta * rho * s) / denom, t / denom);
 }
References cimag, CMPLX, copysign, cos, creal, exp, EXTRACT_WORDS, fabs, isfinite, isinf, SET_HIGH_WORD, sin, sinh, sqrt, tan, x, and y.
Referenced by ctan(), and ctanhl().
ctanhf()
float complex ctanhf (float complex)
Definition at line 33 of file ctanhf.c.
 {
     float x, y;
     float t, beta, s, rho, denom;
     uint32_t hx, ix;
     x = crealf(z);
     y = cimagf(z);
     GET_FLOAT_WORD(hx, x);
     ix = hx & 0x7fffffff;
     if (ix >= 0x7f800000) {
         if (ix & 0x7fffff)
             return CMPLXF(x, (y == 0 ? y : x * y));
         SET_FLOAT_WORD(x, hx - 0x40000000);
         return CMPLXF(x, copysignf(0, isinf(y) ? y : sinf(y) * cosf(y)));
     }
     if (!isfinite(y))
         return CMPLXF(ix ? y - y : x, y - y);
     if (ix >= 0x41300000) { /* x >= 11 */
         float exp_mx = expf(-fabsf(x));
         return CMPLXF(copysignf(1, x), 4 * sinf(y) * cosf(y) * exp_mx * exp_mx);
     }
     t = tanf(y);
     beta = 1.0 + t * t;
     s = sinhf(x);
     rho = sqrtf(1 + s * s);
     denom = 1 + beta * s * s;
     return CMPLXF((beta * rho * s) / denom, t / denom);
 }
References cimagf, CMPLXF, copysignf(), cosf(), crealf, expf(), fabsf(), GET_FLOAT_WORD, isfinite, isinf, SET_FLOAT_WORD, sinf(), sinhf(), sqrtf(), tanf(), x, and y.
Referenced by ctanf().
ctanhl()
long double complex ctanhl (long double complex)
Definition at line 4 of file ctanhl.c.
 {
     return ctanh(z);
 }
References ctanh().
Referenced by ctanl().
ctanl()
long double complex ctanl (long double complex)
Definition at line 9 of file ctanl.c.
 {
     z = ctanhl(CMPLXL(-cimagl(z), creall(z)));
     return CMPLXL(cimagl(z), -creall(z));
 }
References cimagl, CMPLXL, creall, and ctanhl().