Fennix Userspace: Userspace/apps/base/busybox/e2fsprogs/e2fs_lib.c File Reference
e2fs_lib.c File Reference
#include "libbb.h"
#include "e2fs_lib.h"
Functions
void print_e2flags_long (unsigned flags)
void print_e2flags (unsigned flags)
Variables
const uint32_t e2attr_flags_value[] ALIGN4
const char e2attr_flags_sname[] ALIGN1
Function Documentation
print_e2flags()
void print_e2flags (unsigned flags)
Definition at line 96 of file e2fs_lib.c.
 {
     const uint32_t *fv;
     const char *fn;
     fv = e2attr_flags_value;
     fn = e2attr_flags_sname;
     do  {
         char c = '-';
         if (flags & *fv)
             c = *fn;
         putchar(c);
         fv++;
         fn++;
     } while (*fn);
 }
References c, e2attr_flags_sname, e2attr_flags_value, flags, and putchar.
Referenced by list_attributes().
print_e2flags_long()
void print_e2flags_long (unsigned flags)
Definition at line 74 of file e2fs_lib.c.
 {
     const uint32_t *fv;
     const char *fn;
     int first = 1;
     fv = e2attr_flags_value;
     fn = e2attr_flags_lname;
     do {
         if (flags & *fv) {
             if (!first)
                 fputs(", ", stdout);
             fputs(fn, stdout);
             first = 0;
         }
         fv++;
         fn += strlen(fn) + 1;
     } while (*fn);
     if (first)
         fputs("---", stdout);
 }
References e2attr_flags_value, first, flags, fputs, stdout, and strlen().
Referenced by list_attributes().
Variable Documentation
ALIGN1
const char e2attr_flags_lname [] ALIGN1
Initial value:
=
    "suSDiadAcEjItTeCFNPV"
Definition at line 40 of file e2fs_lib.c.
ALIGN4
const uint32_t e2attr_flags_value [] ALIGN4
Initial value:
= {
    EXT2_SECRM_FL,
    EXT2_UNRM_FL,
    EXT2_SYNC_FL,
    EXT2_DIRSYNC_FL,
    EXT2_IMMUTABLE_FL,
    EXT2_APPEND_FL,
    EXT2_NODUMP_FL,
    EXT2_NOATIME_FL,
    EXT2_COMPR_FL,
    EXT2_ECOMPR_FL,
    EXT3_JOURNAL_DATA_FL,
    EXT2_INDEX_FL,
    EXT2_NOTAIL_FL,
    EXT2_TOPDIR_FL,
    EXT2_EXTENT_FL,
    EXT2_NOCOW_FL,
    EXT2_CASEFOLD_FL,
    EXT2_INLINE_DATA_FL,
    EXT2_PROJINHERIT_FL,
    EXT2_VERITY_FL,
}
Definition at line 12 of file e2fs_lib.c.
Referenced by dnsd_main(), has_super(), and wcwidth().