Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/hu_lib.c File Reference
hu_lib.c File Reference
#include <ctype.h>
#include "doomdef.h"
#include "doomkeys.h"
#include "v_video.h"
#include "i_swap.h"
#include "hu_lib.h"
#include "r_local.h"
#include "r_draw.h"
Macros
#define noterased viewwindowx
Functions
void HUlib_init (void)
void HUlib_clearTextLine (hu_textline_t *t)
void HUlib_initTextLine (hu_textline_t *t, int x, int y, patch_t **f, int sc)
boolean HUlib_addCharToTextLine (hu_textline_t *t, char ch)
boolean HUlib_delCharFromTextLine (hu_textline_t *t)
void HUlib_drawTextLine (hu_textline_t *l, boolean drawcursor)
void HUlib_eraseTextLine (hu_textline_t *l)
void HUlib_initSText (hu_stext_t *s, int x, int y, int h, patch_t **font, int startchar, boolean *on)
void HUlib_addLineToSText (hu_stext_t *s)
void HUlib_addMessageToSText (hu_stext_t *s, char *prefix, char *msg)
void HUlib_drawSText (hu_stext_t *s)
void HUlib_eraseSText (hu_stext_t *s)
void HUlib_initIText (hu_itext_t *it, int x, int y, patch_t **font, int startchar, boolean *on)
void HUlib_delCharFromIText (hu_itext_t *it)
void HUlib_eraseLineFromIText (hu_itext_t *it)
void HUlib_resetIText (hu_itext_t *it)
void HUlib_addPrefixToIText (hu_itext_t *it, char *str)
boolean HUlib_keyInIText (hu_itext_t *it, unsigned char ch)
void HUlib_drawIText (hu_itext_t *it)
void HUlib_eraseIText (hu_itext_t *it)
Variables
boolean automapactive
Macro Definition Documentation
noterased
#define noterased viewwindowx
Definition at line 32 of file hu_lib.c.
Function Documentation
HUlib_addCharToTextLine()
boolean HUlib_addCharToTextLine (hu_textline_t * t, char ch)
Definition at line 63 of file hu_lib.c.
 {
     if (t->len == HU_MAXLINELENGTH)
     return false;
     else
     {
     t->l[t->len++] = ch;
     t->l[t->len] = 0;
     t->needsupdate = 4;
     return true;
     }
 }
References HU_MAXLINELENGTH, and t.
Referenced by HU_Start(), HUlib_addMessageToSText(), HUlib_addPrefixToIText(), and HUlib_keyInIText().
HUlib_addLineToSText()
void HUlib_addLineToSText (hu_stext_t * s)
Definition at line 192 of file hu_lib.c.
 {
     int i;
     // add a clear line
     if (++s->cl == s->h)
     s->cl = 0;
     HUlib_clearTextLine(&s->l[s->cl]);
     // everything needs updating
     for (i=0 ; i<s->h ; i++)
     s->l[i].needsupdate = 4;
 }
References hu_stext_t::cl, hu_stext_t::h, HUlib_clearTextLine(), i, hu_stext_t::l, and hu_textline_t::needsupdate.
Referenced by HUlib_addMessageToSText().
HUlib_addMessageToSText()
void HUlib_addMessageToSText (hu_stext_t * s, char * prefix, char * msg)
Definition at line 209 of file hu_lib.c.
 {
     HUlib_addLineToSText(s);
     if (prefix)
     while (*prefix)
         HUlib_addCharToTextLine(&s->l[s->cl], *(prefix++));
     while (*msg)
     HUlib_addCharToTextLine(&s->l[s->cl], *(msg++));
 }
References hu_stext_t::cl, HUlib_addCharToTextLine(), HUlib_addLineToSText(), and hu_stext_t::l.
Referenced by HU_Ticker().
HUlib_addPrefixToIText()
void HUlib_addPrefixToIText (hu_itext_t * it, char * str)
Definition at line 298 of file hu_lib.c.
 {
     while (*str)
     HUlib_addCharToTextLine(&it->l, *(str++));
     it->lm = it->l.len;
 }
References HUlib_addCharToTextLine(), hu_itext_t::l, hu_textline_t::len, hu_itext_t::lm, and str.
HUlib_clearTextLine()
void HUlib_clearTextLine (hu_textline_t * t)
Definition at line 40 of file hu_lib.c.
 {
     t->len = 0;
     t->l[0] = 0;
     t->needsupdate = true;
 }
References t.
Referenced by HUlib_addLineToSText(), HUlib_initTextLine(), and HUlib_resetIText().
HUlib_delCharFromIText()
void HUlib_delCharFromIText (hu_itext_t * it)
Definition at line 278 of file hu_lib.c.
 {
     if (it->l.len != it->lm)
     HUlib_delCharFromTextLine(&it->l);
 }
References HUlib_delCharFromTextLine(), hu_itext_t::l, hu_textline_t::len, and hu_itext_t::lm.
Referenced by HUlib_keyInIText().
HUlib_delCharFromTextLine()
boolean HUlib_delCharFromTextLine (hu_textline_t * t)
Definition at line 80 of file hu_lib.c.
 {
     if (!t->len) return false;
     else
     {
     t->l[--t->len] = 0;
     t->needsupdate = 4;
     return true;
     }
 }
References t.
Referenced by HUlib_delCharFromIText(), and HUlib_eraseLineFromIText().
HUlib_drawIText()
void HUlib_drawIText (hu_itext_t * it)
Definition at line 329 of file hu_lib.c.
 {
     hu_textline_t *l = &it->l;
     if (!*it->on)
     return;
     HUlib_drawTextLine(l, true); // draw the line w/ cursor
 }
References HUlib_drawTextLine(), hu_itext_t::l, and hu_itext_t::on.
Referenced by HU_Drawer().
HUlib_drawSText()
void HUlib_drawSText (hu_stext_t * s)
Definition at line 223 of file hu_lib.c.
 {
     int i, idx;
     hu_textline_t *l;
     if (!*s->on)
     return; // if not on, don't draw
     // draw everything
     for (i=0 ; i<s->h ; i++)
     {
     idx = s->cl - i;
     if (idx < 0)
         idx += s->h; // handle queue of lines
     l = &s->l[idx];
     // need a decision made here on whether to skip the draw
     HUlib_drawTextLine(l, false); // no cursor, please
     }
 }
References hu_stext_t::cl, hu_stext_t::h, HUlib_drawTextLine(), i, idx, hu_stext_t::l, and hu_stext_t::on.
Referenced by HU_Drawer().
HUlib_drawTextLine()
void HUlib_drawTextLine (hu_textline_t * l, boolean drawcursor)
Definition at line 94 of file hu_lib.c.
 {
     int         i;
     int         w;
     int         x;
     unsigned char   c;
     // draw the new stuff
     x = l->x;
     for (i=0;i<l->len;i++)
     {
     c = toupper((int)l->l[i]);
     if (c != ' '
         && c >= l->sc
         && c <= '_')
     {
         w = SHORT(l->f[c - l->sc]->width);
         if (x+w > SCREENWIDTH)
         break;
         V_DrawPatchDirect(x, l->y, l->f[c - l->sc]);
         x += w;
     }
     else
     {
         x += 4;
         if (x >= SCREENWIDTH)
         break;
     }
     }
     // draw the cursor if requested
     if (drawcursor
     && x + SHORT(l->f['_' - l->sc]->width) <= SCREENWIDTH)
     {
     V_DrawPatchDirect(x, l->y, l->f['_' - l->sc]);
     }
 }
References c, hu_textline_t::f, i, hu_textline_t::l, hu_textline_t::len, hu_textline_t::sc, SCREENWIDTH, SHORT, toupper, V_DrawPatchDirect(), hu_textline_t::x, x, and hu_textline_t::y.
Referenced by HU_Drawer(), HUlib_drawIText(), and HUlib_drawSText().
HUlib_eraseIText()
void HUlib_eraseIText (hu_itext_t * it)
Definition at line 340 of file hu_lib.c.
 {
     if (it->laston && !*it->on)
     it->l.needsupdate = 4;
     HUlib_eraseTextLine(&it->l);
     it->laston = *it->on;
 }
References HUlib_eraseTextLine(), hu_itext_t::l, hu_itext_t::laston, hu_textline_t::needsupdate, and hu_itext_t::on.
Referenced by HU_Erase().
HUlib_eraseLineFromIText()
void HUlib_eraseLineFromIText (hu_itext_t * it)
Definition at line 284 of file hu_lib.c.
 {
     while (it->lm != it->l.len)
     HUlib_delCharFromTextLine(&it->l);
 }
References HUlib_delCharFromTextLine(), hu_itext_t::l, hu_textline_t::len, and hu_itext_t::lm.
HUlib_eraseSText()
void HUlib_eraseSText (hu_stext_t * s)
Definition at line 246 of file hu_lib.c.
 {
     int i;
     for (i=0 ; i<s->h ; i++)
     {
     if (s->laston && !*s->on)
         s->l[i].needsupdate = 4;
     HUlib_eraseTextLine(&s->l[i]);
     }
     s->laston = *s->on;
 }
References hu_stext_t::h, HUlib_eraseTextLine(), i, hu_stext_t::l, hu_stext_t::laston, hu_textline_t::needsupdate, and hu_stext_t::on.
Referenced by HU_Erase().
HUlib_eraseTextLine()
void HUlib_eraseTextLine (hu_textline_t * l)
Definition at line 137 of file hu_lib.c.
 {
     int         lh;
     int         y;
     int         yoffset;
     // Only erases when NOT in automap and the screen is reduced,
     // and the text must either need updating or refreshing
     // (because of a recent change back from the automap)
     if (!automapactive &&
     viewwindowx && l->needsupdate)
     {
     lh = SHORT(l->f[0]->height) + 1;
     for (y=l->y,yoffset=y*SCREENWIDTH ; y<l->y+lh ; y++,yoffset+=SCREENWIDTH)
     {
         if (y < viewwindowy || y >= viewwindowy + viewheight)
         R_VideoErase(yoffset, SCREENWIDTH); // erase entire line
         else
         {
         R_VideoErase(yoffset, viewwindowx); // erase left border
         R_VideoErase(yoffset + viewwindowx + viewwidth, viewwindowx);
         // erase right border
         }
     }
     }
     if (l->needsupdate) l->needsupdate--;
 }
References automapactive, hu_textline_t::f, hu_textline_t::needsupdate, R_VideoErase(), SCREENWIDTH, SHORT, viewheight, viewwidth, viewwindowx, viewwindowy, y, and hu_textline_t::y.
Referenced by HU_Erase(), HUlib_eraseIText(), and HUlib_eraseSText().
HUlib_init()
void HUlib_init (void)
Definition at line 36 of file hu_lib.c.
 {
 }
HUlib_initIText()
void HUlib_initIText (hu_itext_t * it, int x, int y, patch_t ** font, int startchar, boolean * on)
Definition at line 262 of file hu_lib.c.
 {
     it->lm = 0; // default left margin is start of text
     it->on = on;
     it->laston = true;
     HUlib_initTextLine(&it->l, x, y, font, startchar);
 }
References HUlib_initTextLine(), hu_itext_t::l, hu_itext_t::laston, hu_itext_t::lm, hu_itext_t::on, x, and y.
Referenced by HU_Start().
HUlib_initSText()
void HUlib_initSText (hu_stext_t * s, int x, int y, int h, patch_t ** font, int startchar, boolean * on)
Definition at line 169 of file hu_lib.c.
 {
     int i;
     s->h = h;
     s->on = on;
     s->laston = true;
     s->cl = 0;
     for (i=0;i<h;i++)
     HUlib_initTextLine(&s->l[i],
                x, y - i*(SHORT(font[0]->height)+1),
                font, startchar);
 }
References hu_stext_t::cl, hu_stext_t::h, height, HUlib_initTextLine(), i, hu_stext_t::l, hu_stext_t::laston, hu_stext_t::on, x, and y.
Referenced by HU_Start().
HUlib_initTextLine()
void HUlib_initTextLine (hu_textline_t * t, int x, int y, patch_t ** f, int sc)
Definition at line 48 of file hu_lib.c.
 {
     t->x = x;
     t->y = y;
     t->f = f;
     t->sc = sc;
     HUlib_clearTextLine(t);
 }
References f, HUlib_clearTextLine(), t, x, and y.
Referenced by HU_Start(), HUlib_initIText(), and HUlib_initSText().
HUlib_keyInIText()
boolean HUlib_keyInIText (hu_itext_t * it, unsigned char ch)
Definition at line 310 of file hu_lib.c.
 {
     ch = toupper(ch);
     if (ch >= ' ' && ch <= '_')
     HUlib_addCharToTextLine(&it->l, (char) ch);
     else
     if (ch == KEY_BACKSPACE)
         HUlib_delCharFromIText(it);
     else
         if (ch != KEY_ENTER)
         return false; // did not eat key
     return true; // ate the key
 }
References HUlib_addCharToTextLine(), HUlib_delCharFromIText(), KEY_BACKSPACE, KEY_ENTER, hu_itext_t::l, and toupper.
Referenced by HU_Responder(), and HU_Ticker().
HUlib_resetIText()
void HUlib_resetIText (hu_itext_t * it)
Definition at line 291 of file hu_lib.c.
 {
     it->lm = 0;
     HUlib_clearTextLine(&it->l);
 }
References HUlib_clearTextLine(), hu_itext_t::l, and hu_itext_t::lm.
Referenced by HU_Responder(), and HU_Ticker().
Variable Documentation
automapactive
boolean automapactive extern
Definition at line 200 of file am_map.c.
Referenced by HUlib_eraseTextLine().