Fennix Userspace: Userspace/musl/src/passwd/getspnam_r.c File Reference
getspnam_r.c File Reference
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <ctype.h>
#include <pthread.h>
#include "pwf.h"
Functions
static long xatol (char **s)
int __parsespent (char *s, struct spwd *sp)
static void cleanup (void *p)
int getspnam_r (const char *name, struct spwd *sp, char *buf, size_t size, struct spwd **res)
Function Documentation
__parsespent()
int __parsespent (char * s, struct spwd * sp)
Definition at line 23 of file getspnam_r.c.
 {
     sp->sp_namp = s;
     if (!(s = strchr(s, ':'))) return -1;
     *s = 0;
     sp->sp_pwdp = ++s;
     if (!(s = strchr(s, ':'))) return -1;
     *s = 0;
     s++; sp->sp_lstchg = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_min = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_max = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_warn = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_inact = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_expire = xatol(&s);
     if (*s != ':') return -1;
     s++; sp->sp_flag = xatol(&s);
     if (*s != '\n') return -1;
     return 0;
 }
References spwd::sp_expire, spwd::sp_flag, spwd::sp_inact, spwd::sp_lstchg, spwd::sp_max, spwd::sp_min, spwd::sp_namp, spwd::sp_pwdp, spwd::sp_warn, strchr(), and xatol().
Referenced by fgetspent(), and getspnam_r().
cleanup()
static void cleanup (void * p) static
Definition at line 56 of file getspnam_r.c.
 {
     fclose(p);
 }
References fclose(), and p.
Referenced by getspnam_r().
getspnam_r()
int getspnam_r (const char * name, struct spwd * sp, char * buf, size_t size, struct spwd ** res)
Definition at line 61 of file getspnam_r.c.
 {
     char path[20+NAME_MAX];
     FILE *f = 0;
     int rv = 0;
     int fd;
     size_t k, l = strlen(name);
     int skip = 0;
     int cs;
     int orig_errno = errno;
     *res = 0;
     /* Disallow potentially-malicious user names */
     if (*name=='.' || strchr(name, '/') || !l)
         return errno = EINVAL;
     /* Buffer size must at least be able to hold name, plus some.. */
     if (size < l+100)
         return errno = ERANGE;
     /* Protect against truncation */
     if (snprintf(path, sizeof path, "/etc/tcb/%s/shadow", name) >= sizeof path)
         return errno = EINVAL;
     fd = open(path, O_RDONLY|O_NOFOLLOW|O_NONBLOCK|O_CLOEXEC);
     if (fd >= 0) {
         struct stat st = { 0 };
         errno = EINVAL;
         if (fstat(fd, &st) || !S_ISREG(st.st_mode) || !(f = fdopen(fd, "rb"))) {
             pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
             close(fd);
             pthread_setcancelstate(cs, 0);
             return errno;
         }
     } else {
         if (errno != ENOENT && errno != ENOTDIR)
             return errno;
         f = fopen("/etc/shadow", "rbe");
         if (!f) {
             if (errno != ENOENT && errno != ENOTDIR)
                 return errno;
             return 0;
         }
     }
     pthread_cleanup_push(cleanup, f);
     while (fgets(buf, size, f) && (k=strlen(buf))>0) {
         if (skip || strncmp(name, buf, l) || buf[l]!=':') {
             skip = buf[k-1] != '\n';
             continue;
         }
         if (buf[k-1] != '\n') {
             rv = ERANGE;
             break;
         }
         if (__parsespent(buf, sp) < 0) continue;
         *res = sp;
         break;
     }
     pthread_cleanup_pop(1);
     errno = rv ? rv : orig_errno;
     return rv;
 }
References __parsespent(), buf, cleanup(), close(), EINVAL, ENOENT, ENOTDIR, ERANGE, errno, f, fgets(), fopen(), fstat(), k, O_CLOEXEC, O_NOFOLLOW, O_NONBLOCK, O_RDONLY, open(), PTHREAD_CANCEL_DISABLE, pthread_cleanup_pop, pthread_cleanup_push, pthread_setcancelstate(), S_ISREG, size, snprintf(), strchr(), strlen(), and strncmp().
Referenced by getspnam().
xatol()
static long xatol (char ** s) static
Definition at line 15 of file getspnam_r.c.
 {
     long x;
     if (**s == ':' || **s == '\n') return -1;
     for (x=0; **s-'0'<10U; ++*s) x=10*x+(**s-'0');
     return x;
 }
References x.
Referenced by __parsespent().