Fennix Userspace: Userspace/mlibc/options/posix/include/bits/posix/posix_wctype.h File Reference
posix_wctype.h File Reference
#include <bits/posix/locale_t.h>
#include <bits/wint_t.h>
Functions
int iswalnum_l (wint_t, locale_t)
int iswblank_l (wint_t, locale_t)
int iswcntrl_l (wint_t, locale_t)
int iswdigit_l (wint_t, locale_t)
int iswgraph_l (wint_t, locale_t)
int iswlower_l (wint_t, locale_t)
int iswprint_l (wint_t, locale_t)
int iswpunct_l (wint_t, locale_t)
int iswspace_l (wint_t, locale_t)
int iswupper_l (wint_t, locale_t)
int iswxdigit_l (wint_t, locale_t)
int iswalpha_l (wint_t, locale_t)
wctype_t wctype_l (const char *)
int iswctype_l (wint_t, wctype_t)
wint_t towlower_l (wint_t, locale_t)
wint_t towupper_l (wint_t, locale_t)
wctrans_t wctrans_l (const char *, locale_t)
wint_t towctrans_l (wint_t, wctrans_t, locale_t)
Function Documentation
iswalnum_l()
int iswalnum_l (wint_t c, locale_t)
Definition at line 66 of file posix_ctype.cpp.
{
     return iswalnum(c);
 }
References c, and iswalnum().
iswalpha_l()
int iswalpha_l (wint_t c, locale_t)
Definition at line 110 of file posix_ctype.cpp.
{
     return iswalpha(c);
 }
References c, and iswalpha().
iswblank_l()
int iswblank_l (wint_t c, locale_t)
Definition at line 70 of file posix_ctype.cpp.
{
     return iswblank(c);
 }
References c, and iswblank().
iswcntrl_l()
int iswcntrl_l (wint_t c, locale_t)
Definition at line 74 of file posix_ctype.cpp.
{
     return iswcntrl(c);
 }
References c, and iswcntrl().
iswctype_l()
int iswctype_l (wint_t , wctype_t)
iswdigit_l()
int iswdigit_l (wint_t c, locale_t)
Definition at line 78 of file posix_ctype.cpp.
{
     return iswdigit(c);
 }
References c, and iswdigit().
iswgraph_l()
int iswgraph_l (wint_t c, locale_t)
Definition at line 82 of file posix_ctype.cpp.
{
     return iswgraph(c);
 }
References c, and iswgraph().
iswlower_l()
int iswlower_l (wint_t c, locale_t)
Definition at line 86 of file posix_ctype.cpp.
{
     return iswlower(c);
 }
References c, and iswlower().
iswprint_l()
int iswprint_l (wint_t c, locale_t)
Definition at line 90 of file posix_ctype.cpp.
{
     return iswprint(c);
 }
References c, and iswprint().
iswpunct_l()
int iswpunct_l (wint_t c, locale_t)
Definition at line 94 of file posix_ctype.cpp.
{
     return iswpunct(c);
 }
References c, and iswpunct().
iswspace_l()
int iswspace_l (wint_t c, locale_t)
Definition at line 98 of file posix_ctype.cpp.
{
     return iswspace(c);
 }
References c, and iswspace().
iswupper_l()
int iswupper_l (wint_t c, locale_t)
Definition at line 102 of file posix_ctype.cpp.
{
     return iswupper(c);
 }
References c, and iswupper().
iswxdigit_l()
int iswxdigit_l (wint_t c, locale_t)
Definition at line 106 of file posix_ctype.cpp.
{
     return iswxdigit(c);
 }
References c, and iswxdigit().
towctrans_l()
wint_t towctrans_l (wint_t c, wctrans_t desc, locale_t)
Definition at line 134 of file posix_ctype.cpp.
{
     return towctrans(c, desc);
 }
References c, and towctrans().
towlower_l()
wint_t towlower_l (wint_t c, locale_t)
Definition at line 122 of file posix_ctype.cpp.
{
     return towlower(c);
 }
References c, and towlower().
towupper_l()
wint_t towupper_l (wint_t c, locale_t)
Definition at line 126 of file posix_ctype.cpp.
{
     return towupper(c);
 }
References c, and towupper().
wctrans_l()
wctrans_t wctrans_l (const char * c, locale_t)
Definition at line 130 of file posix_ctype.cpp.
{
     return wctrans(c);
 }
References c, and wctrans().
wctype_l()
wctype_t wctype_l (const char *)