Fennix: Userspace/musl/src/malloc/mallocng/malloc_usable_size.c File Reference
malloc_usable_size.c File Reference
#include <stdlib.h>
#include "meta.h"
Functions
size_t malloc_usable_size (void *p)
Function Documentation
malloc_usable_size()
size_t malloc_usable_size (void * p)
Definition at line 4 of file malloc_usable_size.c.
 {
     if (!p) return 0;
     struct meta *g = get_meta(p);
     int idx = get_slot_index(p);
     size_t stride = get_stride(g);
     unsigned char *start = g->mem->storage + stride*idx;
     unsigned char *end = start + stride - IB;
     return get_nominal_size(p, end);
 }
References end, g, get_meta(), get_nominal_size(), get_slot_index(), get_stride(), IB, idx, p, and start.