Fennix: ResizePrinter Struct Reference
ResizePrinter Struct Reference
Public Member Functions
ResizePrinter ()
void expand ()
void append (char c)
void append (const char *str)
void append (const char *str, size_t n)
Data Fields
char * buffer
size_t limit
size_t count
Detailed Description
Definition at line 170 of file stdio-stubs.cpp.
Constructor & Destructor Documentation
ResizePrinter()
ResizePrinter::ResizePrinter () inline
Definition at line 171 of file stdio-stubs.cpp.
     : buffer(nullptr), limit(0), count(0) { }
Member Function Documentation
append() [1/3]
void ResizePrinter::append (char c) inline
Definition at line 187 of file stdio-stubs.cpp.
{
         expand();
         buffer[count] = c;
         count++;
     }
References buffer, c, count, and expand().
Referenced by append().
append() [2/3]
void ResizePrinter::append (const char * str) inline
Definition at line 193 of file stdio-stubs.cpp.
{
         for(size_t i = 0; str[i]; i++)
             append(str[i]);
     }
References append(), and i.
append() [3/3]
void ResizePrinter::append (const char * str, size_t n) inline
Definition at line 198 of file stdio-stubs.cpp.
{
         for(size_t i = 0; i < n; i++)
             append(str[i]);
     }
References append(), i, and n.
expand()
void ResizePrinter::expand () inline
Definition at line 174 of file stdio-stubs.cpp.
                   {
         if(count == limit) {
             auto new_limit = frg::max(2 * limit, size_t(16));
             auto new_buffer = reinterpret_cast<char *>(malloc(new_limit));
             __ensure(new_buffer);
             memcpy(new_buffer, buffer, count);
             free(buffer);
             buffer = new_buffer;
             limit = new_limit;
         }
         __ensure(count < limit);
     }
References __ensure, buffer, count, free(), limit, malloc(), and memcpy.
Referenced by append().
Field Documentation
buffer
char* ResizePrinter::buffer
Definition at line 203 of file stdio-stubs.cpp.
Referenced by append(), and expand().
count
size_t ResizePrinter::count
Definition at line 205 of file stdio-stubs.cpp.
Referenced by append(), and expand().
limit
size_t ResizePrinter::limit
Definition at line 204 of file stdio-stubs.cpp.
Referenced by expand().
The documentation for this struct was generated from the following file:
Userspace/mlibc/options/ansi/generic/stdio-stubs.cpp