Fennix: Userspace/musl/src/linux/prctl.c File Reference
prctl.c File Reference
#include <sys/prctl.h>
#include <stdarg.h>
#include "syscall.h"
Functions
int prctl (int op,...)
Function Documentation
prctl()
int prctl (int op, ...)
Definition at line 5 of file prctl.c.
 {
     unsigned long x[4];
     int i;
     va_list ap;
     va_start(ap, op);
     for (i=0; i<4; i++) x[i] = va_arg(ap, unsigned long);
     va_end(ap);
     return syscall(SYS_prctl, op, x[0], x[1], x[2], x[3]);
 }
References ap, i, syscall(), va_arg, va_end, va_start, and x.
Referenced by launch_helper(), pthread_getname_np(), pthread_setname_np(), and setpriv_main().