Fennix Userspace: Userspace/apps/base/busybox/coreutils/sort.c File Reference
sort.c File Reference
#include "libbb.h"
Macros
#define OPT_STR (sort_opt_str + 1)
#define GET_LINE(fp) xmalloc_fgetline(fp)
Enumerations
enum {
FLAG_n = 1 << 0 , FLAG_g = 1 << 1 , FLAG_h = 1 << 2 , FLAG_M = 1 << 3 ,
FLAG_V = 1 << 4 , FLAG_u = 1 << 5 , FLAG_c = 1 << 6 , FLAG_s = 1 << 7 ,
FLAG_z = 1 << 8 , FLAG_b = 1 << 9 , FLAG_r = 1 << 10 , FLAG_d = 1 << 11 ,
FLAG_f = 1 << 12 , FLAG_i = 1 << 13 , FLAG_m = 1 << 14 , FLAG_S = 1 << 15 ,
FLAG_T = 1 << 16 , FLAG_o = 1 << 17 , FLAG_k = 1 << 18 , FLAG_t = 1 << 19 ,
FLAG_bb = 0x80000000 , FLAG_no_tie_break = 0x40000000
}
Functions
static int compare_keys (const void *xarg, const void *yarg)
int sort_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char sort_opt_str[] ALIGN1
Macro Definition Documentation
GET_LINE
#define GET_LINE (fp) xmalloc_fgetline(fp)
Definition at line 255 of file sort.c.
OPT_STR
#define OPT_STR (sort_opt_str + 1)
Definition at line 129 of file sort.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FLAG_n
FLAG_g
FLAG_h
FLAG_M
FLAG_V
FLAG_u
FLAG_c
FLAG_s
FLAG_z
FLAG_b
FLAG_r
FLAG_d
FLAG_f
FLAG_i
FLAG_m
FLAG_S
FLAG_T
FLAG_o
FLAG_k
FLAG_t
FLAG_bb
FLAG_no_tie_break
Definition at line 95 of file sort.c.
      {
     FLAG_n  = 1 << 0,       /* Numeric sort */
     FLAG_g  = 1 << 1,       /* Sort using strtod() */
     FLAG_h  = 1 << 2,       /* Sort using strtod(), plus KMGT suffixes */
     FLAG_M  = 1 << 3,       /* Sort date */
     FLAG_V  = 1 << 4,       /* Sort version */
 /* ucsz apply to root level only, not keys.  b at root level implies bb */
     FLAG_u  = 1 << 5,       /* Unique */
     FLAG_c  = 1 << 6,       /* Check: no output, exit(!ordered) */
     FLAG_s  = 1 << 7,       /* Stable sort, no ascii fallback at end */
     FLAG_z  = 1 << 8,       /* Input and output is NUL terminated, not \n */
 /* These can be applied to search keys, the previous four can't */
     FLAG_b  = 1 << 9,       /* Ignore leading blanks */
     FLAG_r  = 1 << 10,      /* Reverse */
     FLAG_d  = 1 << 11,      /* Ignore !(isalnum()|isspace()) */
     FLAG_f  = 1 << 12,      /* Force uppercase */
     FLAG_i  = 1 << 13,      /* Ignore !isprint() */
     FLAG_m  = 1 << 14,      /* ignored: merge already sorted files; do not sort */
     FLAG_S  = 1 << 15,      /* ignored: -S, --buffer-size=SIZE */
     FLAG_T  = 1 << 16,      /* ignored: -T, --temporary-directory=DIR */
     FLAG_o  = 1 << 17,
     FLAG_k  = 1 << 18,
     FLAG_t  = 1 << 19,
     FLAG_bb = 0x80000000,   /* Ignore trailing blanks  */
     FLAG_no_tie_break = 0x40000000,
 };
Function Documentation
compare_keys()
static int compare_keys (const void * xarg, const void * yarg) static
Definition at line 278 of file sort.c.
 {
     int flags = option_mask32, retval = 0;
     char *x, *y;
 #if ENABLE_FEATURE_SORT_BIG
     struct sort_key *key;
     for (key = key_list; !retval && key; key = key->next_key) {
         flags = key->flags ? key->flags : option_mask32;
         /* Chop out and modify key chunks, handling -dfib */
         x = get_key(*(char **)xarg, key, flags);
         y = get_key(*(char **)yarg, key, flags);
 #else
     /* This curly bracket serves no purpose but to match the nesting
      * level of the for () loop we're not using */
     {
         x = *(char **)xarg;
         y = *(char **)yarg;
 #endif
         /* Perform actual comparison */
         switch (flags & (FLAG_n | FLAG_g | FLAG_h | FLAG_M | FLAG_V)) {
         default:
             bb_simple_error_msg_and_die("unknown sort type");
             break;
 #if defined(HAVE_STRVERSCMP) && HAVE_STRVERSCMP == 1
         case FLAG_V:
             retval = strverscmp(x, y);
             break;
 #endif
         /* Ascii sort */
         case 0:
 #if ENABLE_LOCALE_SUPPORT
             retval = strcoll(x, y);
 #else
             retval = strcmp(x, y);
 #endif
             break;
 #if ENABLE_FEATURE_SORT_BIG
         case FLAG_g:
         case FLAG_h: {
             char *xx, *yy;
 //TODO: needs setlocale(LC_NUMERIC, "C")?
             double dx = strtod(x, &xx);
             double dy = strtod(y, &yy);
             /* not numbers < NaN < -infinity < numbers < +infinity) */
             if (x == xx)
                 retval = (y == yy ? 0 : -1);
             else if (y == yy)
                 retval = 1;
             /* Check for isnan */
             else if (dx != dx)
                 retval = (dy != dy) ? 0 : -1;
             else if (dy != dy)
                 retval = 1;
             else {
                 if (flags & FLAG_h) {
                     int xs = scale_suffix(xx);
                     int ys = scale_suffix(yy);
                     if (xs != ys) {
                         retval = xs - ys;
                         break;
                     }
                 }
                 /* Check for infinity.  Could underflow, but it avoids libm. */
                 if (1.0 / dx == 0.0) {
                     if (dx < 0)
                         retval = (1.0 / dy == 0.0 && dy < 0) ? 0 : -1;
                     else
                         retval = (1.0 / dy == 0.0 && dy > 0) ? 0 : 1;
                 } else if (1.0 / dy == 0.0)
                     retval = (dy < 0) ? 1 : -1;
                 else
                     retval = (dx > dy) ? 1 : ((dx < dy) ? -1 : 0);
             }
             break;
         }
         case FLAG_M: {
             struct tm thyme;
             int dx;
             char *xx, *yy;
             xx = strptime(skip_whitespace(x), "%b", &thyme);
             dx = thyme.tm_mon;
             yy = strptime(skip_whitespace(y), "%b", &thyme);
             if (!xx)
                 retval = (!yy) ? 0 : -1;
             else if (!yy)
                 retval = 1;
             else
                 retval = dx - thyme.tm_mon;
             break;
         }
         /* Full floating point version of -n */
         case FLAG_n: {
             double dx = atof(x);
             double dy = atof(y);
             retval = (dx > dy) ? 1 : ((dx < dy) ? -1 : 0);
             break;
         }
         } /* switch */
         /* Free key copies. */
         if (x != *(char **)xarg) free(x);
         if (y != *(char **)yarg) free(y);
         /* if (retval) break; - done by for () anyway */
 #else
         /* Integer version of -n for tiny systems */
         case FLAG_n:
             retval = atoi(x) - atoi(y);
             break;
         } /* switch */
 #endif
     } /* for */
     if (retval == 0) {
         /* So far lines are "the same" */
         if (option_mask32 & FLAG_s) {
             /* "Stable sort": later line is "greater than",
              * IOW: do not allow qsort() to swap equal lines.
              */
             uint32_t *p32;
             uint32_t x32, y32;
             char *line;
             unsigned len;
             line = *(char**)xarg;
             len = (strlen(line) + 4) & (~3u);
             p32 = (void*)(line + len);
             x32 = *p32;
             line = *(char**)yarg;
             len = (strlen(line) + 4) & (~3u);
             p32 = (void*)(line + len);
             y32 = *p32;
             /* If x > y, 1, else -1 */
             retval = (x32 > y32) * 2 - 1;
             /* Here, -r has no effect! */
             return retval;
         }
         if (!(option_mask32 & FLAG_no_tie_break)) {
             /* fallback sort */
             flags = option_mask32;
             retval = strcmp(*(char **)xarg, *(char **)yarg);
         }
     }
     if (flags & FLAG_r)
         return -retval;
     return retval;
 }
References atof(), atoi(), bb_simple_error_msg_and_die(), FLAG_g, FLAG_h, FLAG_M, FLAG_n, FLAG_no_tie_break, FLAG_r, FLAG_s, FLAG_V, flags, free, line, option_mask32, retval, skip_whitespace(), strcmp, strcoll(), strlen(), strptime(), strtod(), strverscmp(), tm::tm_mon, x, xx, and y.
Referenced by sort_main().
sort_main()
int sort_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 445 of file sort.c.
 {
     char **lines;
     char *str_ignored, *str_o, *str_t;
     llist_t *lst_k = NULL;
     int i;
     int linecount;
     unsigned opts;
 #if ENABLE_FEATURE_SORT_OPTIMIZE_MEMORY
     bool can_drop_dups;
     size_t prev_len = 0;
     char *prev_line = (char*) "";
     /* Postpone optimizing if the input is small, < 16k lines:
      * even just free()ing duplicate lines takes time.
      */
     size_t count_to_optimize_dups = 0x3fff;
 #endif
     xfunc_error_retval = 2;
     /* Parse command line options */
     opts = getopt32(argv,
             sort_opt_str,
             &str_ignored, &str_ignored, &str_o, &lst_k, &str_t
     );
 #if ENABLE_FEATURE_SORT_OPTIMIZE_MEMORY
     /* Can drop dups only if -u but no "complicating" options,
      * IOW: if we do a full line compares. Safe options:
      * -o FILE Output to FILE
      * -z      Lines are terminated by NUL, not newline
      * -r      Reverse sort order
      * -s      Stable (don't sort ties alphabetically)
      * Not sure about these:
      * -b      Ignore leading blanks
      * -f      Ignore case
      * -i      Ignore unprintable characters
      * -d      Dictionary order (blank or alphanumeric only)
      * -n      Sort numbers
      * -g      General numerical sort
      * -M      Sort month
      */
     can_drop_dups = ((opts & ~(FLAG_o|FLAG_z|FLAG_r|FLAG_s)) == FLAG_u);
     /* Stable sort needs every line to be uniquely allocated,
      * disable optimization to reuse strings:
      */
     if (opts & FLAG_s)
         count_to_optimize_dups = (size_t)-1L;
 #endif
     /* global b strips leading and trailing spaces */
     if (opts & FLAG_b)
         option_mask32 |= FLAG_bb;
 #if ENABLE_FEATURE_SORT_BIG
     if (opts & FLAG_t) {
         if (!str_t[0] || str_t[1])
             bb_simple_error_msg_and_die("bad -t parameter");
         key_separator = str_t[0];
     }
     /* note: below this point we use option_mask32, not opts,
      * since that reduces register pressure and makes code smaller */
     /* Parse sort key */
     while (lst_k) {
         enum {
             FLAG_allowed_for_k =
                 FLAG_n | /* Numeric sort */
                 FLAG_g | /* Sort using strtod() */
                 FLAG_h | /* Sort using strtod(), plus KMGT suffixes */
                 FLAG_M | /* Sort date */
                 FLAG_b | /* Ignore leading blanks */
                 FLAG_r | /* Reverse */
                 FLAG_d | /* Ignore !(isalnum()|isspace()) */
                 FLAG_f | /* Force uppercase */
                 FLAG_i | /* Ignore !isprint() */
             0
         };
         struct sort_key *key = add_key();
         char *str_k = llist_pop(&lst_k);
         i = 0; /* i==0 before comma, 1 after (-k3,6) */
         while (*str_k) {
             /* Start of range */
             /* Cannot use bb_strtou - suffix can be a letter */
             key->range[2*i] = str2u(&str_k);
             if (*str_k == '.') {
                 str_k++;
                 key->range[2*i+1] = str2u(&str_k);
             }
             while (*str_k) {
                 int flag;
                 const char *idx;
                 if (*str_k == ',' && !i++) {
                     str_k++;
                     break;
                 } /* no else needed: fall through to syntax error
                     because comma isn't in OPT_STR */
                 idx = strchr(OPT_STR, *str_k);
                 if (!idx)
                     bb_simple_error_msg_and_die("unknown key option");
                 flag = 1 << (idx - OPT_STR);
                 if (flag & ~FLAG_allowed_for_k)
                     bb_simple_error_msg_and_die("unknown sort type");
                 /* b after ',' means strip _trailing_ space */
                 if (i && flag == FLAG_b)
                     flag = FLAG_bb;
                 key->flags |= flag;
                 str_k++;
             }
         }
     }
 #endif
     /* Open input files and read data */
     argv += optind;
     if (!*argv)
         *--argv = (char*)"-";
     linecount = 0;
     lines = NULL;
     do {
         /* coreutils 6.9 compat: abort on first open error,
          * do not continue to next file: */
         FILE *fp = xfopen_stdin(*argv);
         for (;;) {
             char *line = GET_LINE(fp);
             if (!line)
                 break;
 #if ENABLE_FEATURE_SORT_OPTIMIZE_MEMORY
             if (count_to_optimize_dups != 0)
                 count_to_optimize_dups--;
             if (count_to_optimize_dups == 0) {
                 size_t len;
                 char *new_line;
                 /* On kernel/linux/arch/ *.[ch] files,
                  * this reduces memory usage by 6%.
                  *  yes | head -99999999 | sort
                  * goes down from 1900Mb to 380 Mb.
                  */
                 len = strlen(line);
                 if (len <= prev_len) {
                     new_line = prev_line + (prev_len - len);
                     if (strcmp(line, new_line) == 0) {
                         /* it's a tail of the prev line */
                         if (can_drop_dups && prev_len == len) {
                             /* it's identical to prev line */
                             free(line);
                             continue;
                         }
                         free(line);
                         line = new_line;
                         /* continue using longer prev_line
                          * for future tail tests.
                          */
                         goto skip;
                     }
                 }
                 prev_len = len;
                 prev_line = line;
  skip: ;
             }
 #else
 //TODO: lighter version which only drops total dups if can_drop_dups == true
 #endif
             lines = xrealloc_vector(lines, 6, linecount);
             lines[linecount++] = line;
         }
         fclose_if_not_stdin(fp);
     } while (*++argv);
 #if ENABLE_FEATURE_SORT_BIG
     /* If no key, perform alphabetic sort */
     if (!key_list)
         add_key()->range[0] = 1;
     /* Handle -c */
     if (option_mask32 & FLAG_c) {
         int j = (option_mask32 & FLAG_u) ? -1 : 0;
         for (i = 1; i < linecount; i++) {
             if (compare_keys(&lines[i-1], &lines[i]) > j) {
                 fprintf(stderr, "Check line %u\n", i);
                 return EXIT_FAILURE;
             }
         }
         return EXIT_SUCCESS;
     }
 #endif
     /* For stable sort, store original line position beyond terminating NUL */
     if (option_mask32 & FLAG_s) {
         for (i = 0; i < linecount; i++) {
             uint32_t *p32;
             char *line;
             unsigned len;
             line = lines[i];
             len = (strlen(line) + 4) & (~3u);
             lines[i] = line = xrealloc(line, len + 4);
             p32 = (void*)(line + len);
             *p32 = i;
         }
         /*option_mask32 |= FLAG_no_tie_break;*/
         /* ^^^redundant: if FLAG_s, compare_keys() does no tie break */
     }
     /* Perform the actual sort */
     qsort(lines, linecount, sizeof(lines[0]), compare_keys);
     /* Handle -u */
     if (option_mask32 & FLAG_u) {
         int j = 0;
         /* coreutils 6.3 drop lines for which only key is the same:
          * - disabling last-resort compare, or else compare_keys()
          * will be the same only for completely identical lines
          * - disabling -s (same reasons)
          */
         option_mask32 = (option_mask32 | FLAG_no_tie_break) & (~FLAG_s);
         for (i = 1; i < linecount; i++) {
             if (compare_keys(&lines[j], &lines[i]) == 0)
                 free(lines[i]);
             else
                 lines[++j] = lines[i];
         }
         if (linecount)
             linecount = j+1;
     }
     /* Print it */
 #if ENABLE_FEATURE_SORT_BIG
     /* Open output file _after_ we read all input ones */
     if (option_mask32 & FLAG_o)
         xmove_fd(xopen(str_o, O_WRONLY|O_CREAT|O_TRUNC), STDOUT_FILENO);
 #endif
     {
         int ch = (option_mask32 & FLAG_z) ? '\0' : '\n';
         for (i = 0; i < linecount; i++)
             printf("%s%c", lines[i], ch);
     }
     fflush_stdout_and_exit_SUCCESS();
 }
References argv, bb_simple_error_msg_and_die(), compare_keys(), EXIT_FAILURE, EXIT_SUCCESS, fclose_if_not_stdin(), fflush_stdout_and_exit_SUCCESS(), FLAG_b, FLAG_bb, FLAG_c, FLAG_d, FLAG_f, FLAG_g, FLAG_h, FLAG_i, FLAG_M, FLAG_n, FLAG_no_tie_break, FLAG_o, FLAG_r, FLAG_s, FLAG_t, FLAG_u, FLAG_z, fprintf(), free, GET_LINE, getopt32(), i, idx, j, line, linecount, lines, llist_pop(), NULL, O_CREAT, O_TRUNC, O_WRONLY, OPT_STR, optind, option_mask32, prev_line(), printf(), qsort(), skip, stderr, STDOUT_FILENO, strchr(), strcmp, strlen(), xfopen_stdin(), xfunc_error_retval, xmove_fd(), xopen(), xrealloc, and xrealloc_vector.
Variable Documentation
ALIGN1
const char sort_opt_str [] ALIGN1 static
Initial value:
= "^"
            "nghMVucszbrdfimS:T:o:k:*t:"
            "\0" "o--o:t--t"
Definition at line 122 of file sort.c.