Fennix Userspace: Userspace/apps/base/busybox/util-linux/mesg.c File Reference
mesg.c File Reference
#include "libbb.h"
Macros
#define S_IWGRP_OR_S_IWOTH (S_IWGRP | S_IWOTH)
Functions
int mesg_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
S_IWGRP_OR_S_IWOTH
#define S_IWGRP_OR_S_IWOTH (S_IWGRP | S_IWOTH)
Definition at line 44 of file mesg.c.
Function Documentation
mesg_main()
int mesg_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 48 of file mesg.c.
 {
     struct stat sb;
     mode_t m;
     char c = 0;
     argv++;
     if (argv[0]
      && (argv[1] || ((c = argv[0][0]) != 'y' && c != 'n'))
     ) {
         bb_show_usage();
     }
     /* We are a NOFORK applet.
      * (Not that it's very useful, but code is trivially NOFORK-safe).
      * Play nice. Do not leak anything.
      */
     if (!isatty(STDIN_FILENO))
         bb_simple_error_msg_and_die("not a tty");
     xfstat(STDIN_FILENO, &sb, "stdin");
     if (c == 0) {
         puts((sb.st_mode & (S_IWGRP|S_IWOTH)) ? "is y" : "is n");
         return EXIT_SUCCESS;
     }
     m = (c == 'y') ? sb.st_mode | S_IWGRP_OR_S_IWOTH
                    : sb.st_mode & ~(S_IWGRP|S_IWOTH);
     if (fchmod(STDIN_FILENO, m) != 0)
         bb_perror_nomsg_and_die();
     return EXIT_SUCCESS;
 }
References argv, bb_perror_nomsg_and_die(), bb_show_usage(), bb_simple_error_msg_and_die(), c, EXIT_SUCCESS, fchmod(), isatty(), mode_t, puts(), S_IWGRP, S_IWGRP_OR_S_IWOTH, S_IWOTH, stat::st_mode, STDIN_FILENO, and xfstat().