Fennix: Userspace/apps/base/bash/support/bashversion.c File Reference
bashversion.c File Reference
#include "config.h"
#include "stdc.h"
#include <stdio.h>
#include "bashansi.h"
#include "version.h"
#include "conftypes.h"
Macros
#define RFLAG 0x0001
#define VFLAG 0x0002
#define MFLAG 0x0004
#define PFLAG 0x0008
#define SFLAG 0x0010
#define LFLAG 0x0020
#define XFLAG 0x0040
Functions
char *shell_version_string PARAMS ((void))
void show_shell_version PARAMS ((int))
static void usage ()
int main (int argc, char **argv)
Variables
int optind
char * optarg
char * dist_version
int patch_level
char * shell_name = "bash"
char * progname
Macro Definition Documentation
LFLAG
#define LFLAG 0x0020
Definition at line 41 of file bashversion.c.
MFLAG
#define MFLAG 0x0004
Definition at line 38 of file bashversion.c.
PFLAG
#define PFLAG 0x0008
Definition at line 39 of file bashversion.c.
RFLAG
#define RFLAG 0x0001
Definition at line 36 of file bashversion.c.
SFLAG
#define SFLAG 0x0010
Definition at line 40 of file bashversion.c.
VFLAG
#define VFLAG 0x0002
Definition at line 37 of file bashversion.c.
XFLAG
#define XFLAG 0x0040
Definition at line 42 of file bashversion.c.
Function Documentation
main()
int main (int argc , char ** argv)
Definition at line 63 of file bashversion.c.
 {
   int opt, oflags;
   char dv[128], *rv;
   if (progname = strrchr (argv[0], '/'))
     progname++;
   else
     progname = argv[0];
   oflags = 0;
   while ((opt = getopt(argc, argv, "hrvmpslx")) != EOF)
     {
       switch (opt)
     {
     case 'h':
       usage ();
       exit (0);
     case 'r':
       oflags |= RFLAG;  /* release */
       break;
     case 'v':
       oflags |= VFLAG;  /* version */
       break;
     case 'm':
       oflags |= MFLAG;  /* machtype */
       break;
     case 'p':
       oflags |= PFLAG;  /* patchlevel */
       break;
     case 's':       /* short version string */
       oflags |= SFLAG;
       break;
     case 'l':       /* long version string */
       oflags |= LFLAG;
       break;
     case 'x':       /* extended version information */
       oflags |= XFLAG;
       break;
     default:
       usage ();
       exit (2);
     }
     }
   argc -= optind;
   argv += optind;
   if (argc > 0)
     {
       usage ();
       exit (2);
     }
   /* default behavior */
   if (oflags == 0)
     oflags = SFLAG;
   if (oflags & (RFLAG|VFLAG))
     {
       strcpy (dv, dist_version);
       rv = strchr (dv, '.');
       if (rv)
         *rv++ = '\0';
       else
         rv = "00";
     }
   if (oflags & RFLAG)
     printf ("%s\n", dv);
   else if (oflags & VFLAG)
     printf ("%s\n", rv);
   else if (oflags & MFLAG)
     printf ("%s\n", MACHTYPE);
   else if (oflags & PFLAG)
     printf ("%d\n", patch_level);
   else if (oflags & SFLAG)
     printf ("%s\n", shell_version_string ());
   else if (oflags & LFLAG)
     show_shell_version (0);
   else if (oflags & XFLAG)
     show_shell_version (1);
   exit (0);
 }
References argc, argv, dist_version, EOF, exit(), getopt(), LFLAG, MACHTYPE, MFLAG, opt, optind, patch_level, PFLAG, printf, progname, RFLAG, SFLAG, shell_version_string(), show_shell_version(), strchr(), strcpy, strrchr(), usage(), VFLAG, and XFLAG.
PARAMS() [1/2]
void show_shell_version PARAMS ((int))
PARAMS() [2/2]
char* shell_version_string PARAMS ((void))
usage()
static void usage (void) static
Definition at line 57 of file bashversion.c.
 {
   fprintf(stderr, "%s: usage: %s [-hrvpmlsx]\n", progname, progname);
 }
References fprintf(), progname, and stderr.
Referenced by main().
Variable Documentation
dist_version
char* dist_version extern
Definition at line 36 of file version.c.
Referenced by main(), and shell_version_string().
optarg
char* optarg extern
Definition at line 10 of file getopt.c.
optind
int optind extern
Definition at line 11 of file getopt.c.
Referenced by main().
patch_level
int patch_level extern
Definition at line 127 of file shell.h.
Referenced by decode_prompt_string(), extract_filename(), main(), patch_main(), and shell_version_string().
progname
char* progname
Definition at line 54 of file bashversion.c.
Referenced by main(), and usage().
shell_name
char* shell_name = "bash"
Definition at line 53 of file bashversion.c.