Fennix: Userspace/apps/base/busybox/coreutils/libcoreutils/cp_mv_stat.c File Reference
cp_mv_stat.c File Reference
#include "libbb.h"
#include "coreutils.h"
Functions
int FAST_FUNC cp_mv_stat2 (const char *fn, struct stat *fn_stat, stat_func sf)
int FAST_FUNC cp_mv_stat (const char *fn, struct stat *fn_stat)
Function Documentation
cp_mv_stat()
int FAST_FUNC cp_mv_stat (const char * fn, struct stat * fn_stat)
Definition at line 45 of file cp_mv_stat.c.
 {
     return cp_mv_stat2(fn, fn_stat, stat);
 }
References cp_mv_stat2().
Referenced by cp_main(), and mv_main().
cp_mv_stat2()
int FAST_FUNC cp_mv_stat2 (const char * fn, struct stat * fn_stat, stat_func sf)
Definition at line 24 of file cp_mv_stat.c.
 {
     if (sf(fn, fn_stat) < 0) {
         if (errno != ENOENT) {
 #if ENABLE_FEATURE_VERBOSE_CP_MESSAGE
             if (errno == ENOTDIR) {
                 bb_error_msg("can't stat '%s': Path has non-directory component", fn);
                 return -1;
             }
 #endif
             bb_perror_msg("can't stat '%s'", fn);
             return -1;
         }
         return 0;
     }
     if (S_ISDIR(fn_stat->st_mode)) {
         return 3;
     }
     return 1;
 }
References bb_error_msg(), bb_perror_msg(), ENOENT, ENOTDIR, errno, S_ISDIR, and stat::st_mode.
Referenced by cp_main(), cp_mv_stat(), and mv_main().