Fennix: Userspace/apps/base/bash/lib/sh/itos.c File Reference
itos.c File Reference
#include <bashansi.h>
#include "shell.h"
Functions
char * inttostr (intmax_t i, char *buf, size_t len)
char * itos (intmax_t i)
char * mitos (intmax_t i)
char * uinttostr (uintmax_t i, char *buf, size_t len)
char * uitos (uintmax_t i)
Function Documentation
inttostr()
char* inttostr (intmax_t i, char * buf, size_t len)
Definition at line 33 of file itos.c.
 {
   return (fmtumax (i, 10, buf, len, 0));
 }
References buf, i, and len.
Referenced by cprintf(), set_ppid(), sh_set_lines_and_columns(), and uidset().
itos()
char* itos (intmax_t i)
Definition at line 44 of file itos.c.
 {
   char *p, lbuf[INT_STRLEN_BOUND(intmax_t) + 1];
   p = fmtumax (i, 10, lbuf, sizeof(lbuf), 0);
   return (savestring (p));
 }
References i, INT_STRLEN_BOUND, lbuf, p, and savestring().
Referenced by _evalfile(), decode_prompt_string(), error_token_from_token(), execute_function(), exp0(), expassign(), get_group_list(), get_mypid(), make_variable_value(), open_shell_script(), param_expand(), parameter_brace_expand(), parameter_brace_expand_length(), push_args(), redirection_error(), set_int_value(), statval(), and strerror().
mitos()
char* mitos (intmax_t i)
Definition at line 56 of file itos.c.
 {
   char *p, lbuf[INT_STRLEN_BOUND(intmax_t) + 1];
   p = fmtumax (i, 10, lbuf, sizeof(lbuf), 0);
   return (strdup (p));
 }
References i, INT_STRLEN_BOUND, lbuf, p, and strdup().
uinttostr()
char* uinttostr (uintmax_t i, char * buf, size_t len)
Definition at line 66 of file itos.c.
 {
   return (fmtumax (i, 10, buf, len, FL_UNSIGNED));
 }
References buf, FL_UNSIGNED, i, and len.
uitos()
char* uitos (uintmax_t i)
Definition at line 77 of file itos.c.
 {
   char *p, lbuf[INT_STRLEN_BOUND(uintmax_t) + 1];
   p = fmtumax (i, 10, lbuf, sizeof(lbuf), FL_UNSIGNED);
   return (savestring (p));
 }
References FL_UNSIGNED, i, INT_STRLEN_BOUND, lbuf, p, and savestring().