Fennix Kernel: NetworkIPv4 Namespace Reference
NetworkIPv4 Namespace Reference
Data Structures
struct IPv4Header
struct IPv4Packet
class IPv4
class IPv4Events
Enumerations
enum IPv4Protocols {
PROTOCOL_ICMP = 1 , PROTOCOL_IGMP = 2 , PROTOCOL_TCP = 6 , PROTOCOL_UDP = 17 ,
PROTOCOL_IPV6 = 41 , PROTOCOL_ROUTING = 43 , PROTOCOL_FRAGMENT = 44 , PROTOCOL_ESP = 50 ,
PROTOCOL_AH = 51 , PROTOCOL_ICMPV6 = 58 , PROTOCOL_NONE = 59 , PROTOCOL_DSTOPTS = 60 ,
PROTOCOL_ND = 77 , PROTOCOL_ICLFXBM = 78 , PROTOCOL_PIM = 103 , PROTOCOL_COMP = 108 ,
PROTOCOL_SCTP = 132 , PROTOCOL_UDPLITE = 136 , PROTOCOL_RAW = 255
}
Functions
__no_sanitize ("alignment") bool IPv4
Variables
std::vector< IPv4Events * > RegisteredEvents
Data Structure Documentation
NetworkIPv4::IPv4Header
struct NetworkIPv4::IPv4Header
Definition at line 28 of file ipv4.hpp.
Data Fields
uint32_t DestinationIP
uint8_t Flags
uint8_t FragmentOffset
uint16_t HeaderChecksum
uint16_t Identification
uint8_t IHL: 4
uint8_t Protocol
uint32_t SourceIP
uint8_t TimeToLive
uint16_t TotalLength
uint8_t TypeOfService
uint8_t Version: 4
NetworkIPv4::IPv4Packet
struct NetworkIPv4::IPv4Packet
Definition at line 59 of file ipv4.hpp.
Data Fields
uint8_t Data[]
IPv4Header Header
Enumeration Type Documentation
IPv4Protocols
enum NetworkIPv4::IPv4Protocols
Enumerator
PROTOCOL_ICMP
PROTOCOL_IGMP
PROTOCOL_TCP
PROTOCOL_UDP
PROTOCOL_IPV6
PROTOCOL_ROUTING
PROTOCOL_FRAGMENT
PROTOCOL_ESP
PROTOCOL_AH
PROTOCOL_ICMPV6
PROTOCOL_NONE
PROTOCOL_DSTOPTS
PROTOCOL_ND
PROTOCOL_ICLFXBM
PROTOCOL_PIM
PROTOCOL_COMP
PROTOCOL_SCTP
PROTOCOL_UDPLITE
PROTOCOL_RAW
Definition at line 65 of file ipv4.hpp.
     {
         PROTOCOL_ICMP = 1,
         PROTOCOL_IGMP = 2,
         PROTOCOL_TCP = 6,
         PROTOCOL_UDP = 17,
         PROTOCOL_IPV6 = 41,
         PROTOCOL_ROUTING = 43,
         PROTOCOL_FRAGMENT = 44,
         PROTOCOL_ESP = 50,
         PROTOCOL_AH = 51,
         PROTOCOL_ICMPV6 = 58,
         PROTOCOL_NONE = 59,
         PROTOCOL_DSTOPTS = 60,
         PROTOCOL_ND = 77,
         PROTOCOL_ICLFXBM = 78,
         PROTOCOL_PIM = 103,
         PROTOCOL_COMP = 108,
         PROTOCOL_SCTP = 132,
         PROTOCOL_UDPLITE = 136,
         PROTOCOL_RAW = 255
     };
Function Documentation
__no_sanitize()
NetworkIPv4::__no_sanitize ("alignment")
Definition at line 71 of file InternetProtocol.cpp.
     {
         IPv4Packet *Packet = (IPv4Packet *)Data;
         netdbg("Received %d bytes [Protocol %ld]", Length, Packet->Header.Protocol);
         if (Length < sizeof(IPv4Header))
         {
             warn("Packet too short");
             return false;
         }
         bool Reply = false;
         if (b32(Packet->Header.DestinationIP) == Ethernet->GetInterface()->IP.v4.ToHex() || b32(Packet->Header.DestinationIP) == 0xFFFFFFFF || Ethernet->GetInterface()->IP.v4.ToHex() == 0)
         {
             size_t TotalLength = Packet->Header.TotalLength;
             if (TotalLength > Length)
                 TotalLength = Length;
             foreach (auto Event in RegisteredEvents)
                 if (Packet->Header.Protocol == Event->GetProtocol())
                 {
                     InternetProtocol SourceIP;
                     InternetProtocol DestinationIP;
                     SourceIP.v4 = SourceIP.v4.FromHex(b32(Packet->Header.SourceIP));
                     DestinationIP.v4 = DestinationIP.v4.FromHex(b32(Packet->Header.DestinationIP));
                     if (Event->OnIPv4PacketReceived(SourceIP, DestinationIP, (uint8_t *)((uint64_t)Data + 4 * Packet->Header.IHL), TotalLength - 4 * Packet->Header.IHL))
                         Reply = true;
                 }
         }
         else
         {
             netdbg("Not for us. We are %s but this is for %s",
                    Ethernet->GetInterface()->IP.v4.ToHex(),
                    Packet->Header.DestinationIP);
         }
         if (Reply)
         {
             uint32_t SwapIP = Packet->Header.DestinationIP;
             Packet->Header.DestinationIP = Packet->Header.SourceIP;
             Packet->Header.SourceIP = SwapIP;
             Packet->Header.TimeToLive = 0x40;
             Packet->Header.HeaderChecksum = 0x0;
             Packet->Header.HeaderChecksum = CalculateChecksum((uint16_t *)Data, 4 * Packet->Header.TotalLength);
             NIManager->Send(Ethernet->GetInterface(), (uint8_t *)Data, Length);
         }
         return Reply;
     }
References b32, CalculateChecksum(), Data, InternetProtocol::Version4::FromHex(), Length, netdbg, NIManager, PS2Mouse::Packet, RegisteredEvents, NetworkInterfaceManager::NetworkInterface::Send(), InternetProtocol::v4, and warn.
Variable Documentation
RegisteredEvents
std::vector<IPv4Events *> NetworkIPv4::RegisteredEvents
Definition at line 69 of file InternetProtocol.cpp.
Referenced by __no_sanitize(), NetworkIPv4::IPv4Events::IPv4Events(), and NetworkIPv4::IPv4Events::~IPv4Events().