Fennix: CrashXHCIKeyboardDriver Class Reference
CrashXHCIKeyboardDriver Class Reference
#include <xhci.hpp>
Data Structures
struct HCExtCap
union HCExtCap.USBLEGCTLSTS
struct HCExtCap.USBLEGCTLSTS.__packed
union HCExtCap.USBLEGSUP
struct HCExtCap.USBLEGSUP.__packed
struct XHCIcap
union XHCIcap.HCCPARAMS1
struct XHCIcap.HCCPARAMS1.__packed
union XHCIdoorbell
struct XHCIdoorbell.__packed
struct XHCIop
union XHCIop.CRCR
struct XHCIop.CRCR.__packed
union XHCIop.USBCMD
struct XHCIop.USBCMD.__packed
union XHCIop.USBSTS
struct XHCIop.USBSTS.__packed
struct XHCIport
struct XHCIprotocol
struct XHCIruntime
Public Member Functions
bool Initialize ()
CrashXHCIKeyboardDriver (PCI::PCIDevice dev)
~CrashXHCIKeyboardDriver ()
Public Member Functions inherited from Interrupts::Handler
virtual void OnInterruptReceived (CPU::SchedulerFrame *Frame)
Private Member Functions
void OnInterruptReceived (CPU::TrapFrame *Frame)
bool TakeOwnership ()
Private Attributes
struct CrashXHCIKeyboardDriver::XHCIcap __packed
struct CrashXHCIKeyboardDriver::XHCIop __packed
struct CrashXHCIKeyboardDriver::XHCIport __packed
struct CrashXHCIKeyboardDriver::XHCIruntime __packed
union CrashXHCIKeyboardDriver::XHCIdoorbell * doorbell
struct CrashXHCIKeyboardDriver::HCExtCap __packed
struct CrashXHCIKeyboardDriver::XHCIprotocol __packed
PCI::PCIDeviceHeader * Header = nullptr
uintptr_t ExtendedCaps = 0
void * baseAddrArray = nullptr
std::vector< XHCIprotocol * > Protocols = {}
XHCIruntime::XHCIinterrupter * Interrupter = nullptr
Additional Inherited Members
Protected Member Functions inherited from Interrupts::Handler
void SetInterruptNumber (int InterruptNumber)
Set a new interrupt number.
int GetInterruptNumber ()
Handler (int InterruptNumber, bool Critical=false)
Create a new interrupt handler.
Handler (PCI::PCIDevice Device, bool Critical=false)
Handler ()
~Handler ()
Detailed Description
Definition at line 22 of file xhci.hpp.
Data Structure Documentation
CrashXHCIKeyboardDriver::HCExtCap
struct CrashXHCIKeyboardDriver::HCExtCap
Definition at line 202 of file xhci.hpp.
Data Fields
union HCExtCap USBLEGCTLSTS
union HCExtCap USBLEGSUP
CrashXHCIKeyboardDriver::HCExtCap.USBLEGCTLSTS
union CrashXHCIKeyboardDriver::HCExtCap.USBLEGCTLSTS
Definition at line 218 of file xhci.hpp.
Data Fields
USBLEGCTLSTS __packed
uint32_t raw
CrashXHCIKeyboardDriver::HCExtCap.USBLEGCTLSTS.__packed
struct CrashXHCIKeyboardDriver::HCExtCap.USBLEGCTLSTS.__packed
Definition at line 220 of file xhci.hpp.
Data Fields
uint32_t unknown: 32
CrashXHCIKeyboardDriver::HCExtCap.USBLEGSUP
union CrashXHCIKeyboardDriver::HCExtCap.USBLEGSUP
Definition at line 204 of file xhci.hpp.
Data Fields
USBLEGSUP __packed
uint32_t raw
CrashXHCIKeyboardDriver::HCExtCap.USBLEGSUP.__packed
struct CrashXHCIKeyboardDriver::HCExtCap.USBLEGSUP.__packed
Definition at line 206 of file xhci.hpp.
Data Fields
uint32_t __reserved0: 7
uint32_t __reserved1: 7
uint32_t BIOSOwnsHC: 1
uint32_t CapID: 8
uint32_t NextCapPtr: 8
uint32_t OSOwnsHC: 1
CrashXHCIKeyboardDriver::XHCIcap
struct CrashXHCIKeyboardDriver::XHCIcap
Definition at line 25 of file xhci.hpp.
Data Fields
uint8_t __reserved0
uint8_t CAPLENGTH
uint32_t DBOFF
union XHCIcap HCCPARAMS1
uint32_t HCCPARAMS2
uint16_t HCIVERSION
uint32_t HCSPARAMS1
uint32_t HCSPARAMS2
uint32_t HCSPARAMS3
uint32_t RTSOFF
CrashXHCIKeyboardDriver::XHCIcap.HCCPARAMS1
union CrashXHCIKeyboardDriver::XHCIcap.HCCPARAMS1
Definition at line 33 of file xhci.hpp.
Data Fields
HCCPARAMS1 __packed
uint32_t raw
CrashXHCIKeyboardDriver::XHCIcap.HCCPARAMS1.__packed
struct CrashXHCIKeyboardDriver::XHCIcap.HCCPARAMS1.__packed
Definition at line 35 of file xhci.hpp.
Data Fields
uint32_t AC64: 1
uint32_t BNC: 1
uint32_t CFC: 1
uint32_t CSZ: 1
uint32_t LHRC: 1
uint32_t LTC: 1
uint32_t MaxPSASize: 4
uint32_t NSS: 1
uint32_t PAE: 1
uint32_t PIND: 1
uint32_t PPC: 1
uint32_t SEC: 1
uint32_t SPC: 1
uint32_t xHCIExtendedCapacitiesPointer: 16
CrashXHCIKeyboardDriver::XHCIdoorbell
union CrashXHCIKeyboardDriver::XHCIdoorbell
Definition at line 191 of file xhci.hpp.
Data Fields
struct XHCIdoorbell __packed
uint32_t raw
CrashXHCIKeyboardDriver::XHCIdoorbell.__packed
struct CrashXHCIKeyboardDriver::XHCIdoorbell.__packed
Definition at line 193 of file xhci.hpp.
Data Fields
uint32_t __reserved: 8
uint32_t DBTarget: 8
uint32_t DBTaskID: 16
CrashXHCIKeyboardDriver::XHCIop
struct CrashXHCIKeyboardDriver::XHCIop
Definition at line 60 of file xhci.hpp.
Data Fields
uint8_t __reserved0[8]
uint8_t __reserved1[16]
uint32_t CONFIG
union XHCIop CRCR
uint64_t DCBAAP
uint32_t DNCTRL
uint32_t PAGESIZE
union XHCIop USBCMD
union XHCIop USBSTS
CrashXHCIKeyboardDriver::XHCIop.CRCR
union CrashXHCIKeyboardDriver::XHCIop.CRCR
Definition at line 108 of file xhci.hpp.
Data Fields
CRCR __packed
uint64_t raw
CrashXHCIKeyboardDriver::XHCIop.CRCR.__packed
struct CrashXHCIKeyboardDriver::XHCIop.CRCR.__packed
Definition at line 110 of file xhci.hpp.
Data Fields
uint64_t __reserved0: 2
uint64_t CA: 1
uint64_t CRP: 58
uint64_t CRR: 1
uint64_t CS: 1
uint64_t RCS: 1
CrashXHCIKeyboardDriver::XHCIop.USBCMD
union CrashXHCIKeyboardDriver::XHCIop.USBCMD
Definition at line 62 of file xhci.hpp.
Data Fields
USBCMD __packed
uint32_t raw
CrashXHCIKeyboardDriver::XHCIop.USBCMD.__packed
struct CrashXHCIKeyboardDriver::XHCIop.USBCMD.__packed
Definition at line 64 of file xhci.hpp.
Data Fields
uint32_t __reserved0: 3
uint32_t __reserved1: 1
uint32_t __reserved2: 15
uint32_t CME: 1
uint32_t CRS: 1
uint32_t CSS: 1
uint32_t ETE: 1
uint32_t EU3S: 1
uint32_t EWE: 1
uint32_t HCRST: 1
uint32_t HSEE: 1
uint32_t INTE: 1
uint32_t LHCRST: 1
uint32_t RS: 1
uint32_t TSCEN: 1
uint32_t VTIOEN: 1
CrashXHCIKeyboardDriver::XHCIop.USBSTS
union CrashXHCIKeyboardDriver::XHCIop.USBSTS
Definition at line 85 of file xhci.hpp.
Data Fields
USBSTS __packed
uint32_t raw
CrashXHCIKeyboardDriver::XHCIop.USBSTS.__packed
struct CrashXHCIKeyboardDriver::XHCIop.USBSTS.__packed
Definition at line 87 of file xhci.hpp.
Data Fields
uint32_t __reserved0: 1
uint32_t __reserved1: 3
uint32_t __reserved2: 18
uint32_t CNR: 1
uint32_t EINT: 1
uint32_t HCE: 1
uint32_t HCH: 1
uint32_t HSE: 1
uint32_t PCB: 1
uint32_t RSS: 1
uint32_t SRE: 1
uint32_t SSS: 1
CrashXHCIKeyboardDriver::XHCIport
struct CrashXHCIKeyboardDriver::XHCIport
Definition at line 126 of file xhci.hpp.
Data Fields
uint32_t PORTHLPMC
uint32_t PORTLI
uint32_t PORTMSC
uint32_t PORTSC
CrashXHCIKeyboardDriver::XHCIprotocol
struct CrashXHCIKeyboardDriver::XHCIprotocol
Definition at line 228 of file xhci.hpp.
Data Fields
uint32_t __reserved0: 28
uint8_t CAPID
uint8_t CompPortCount
uint8_t CompPortOffset
uint8_t Name[4]
uint8_t NextCapPtr
uint16_t ProtocolDefined: 12
uint8_t ProtocolSlotType: 4
uint8_t PSIC: 4
uint8_t RevisionMajor
uint8_t RevisionMinor
CrashXHCIKeyboardDriver::XHCIruntime
struct CrashXHCIKeyboardDriver::XHCIruntime
Definition at line 134 of file xhci.hpp.
Data Fields
struct XHCIinterrupter __packed[]
uint32_t __reserved0[7]
uint32_t MFINDEX
Constructor & Destructor Documentation
CrashXHCIKeyboardDriver()
nsa CrashXHCIKeyboardDriver::CrashXHCIKeyboardDriver (PCI::PCIDevice dev)
Definition at line 83 of file xhci.cpp.
     : Interrupts::Handler(xhci)
 {
     Header = (PCIDeviceHeader *)xhci.Header;
     switch (Header->HeaderType)
     {
     case 128:
     {
         ExPrint(ERROR_COLOR "Unknown header type %d! Guessing PCI Header 0\n" DEFAULT_COLOR,
                 Header->HeaderType);
         [[fallthrough]];
     }
     case 0: /* PCI Header 0 */
     {
         PCI::PCIHeader0 *hdr = (PCI::PCIHeader0 *)Header;
         uint32_t BAR[6];
         size_t BARsSize[6];
         BAR[0] = hdr->BAR0;
         BAR[1] = hdr->BAR1;
         BAR[2] = hdr->BAR2;
         BAR[3] = hdr->BAR3;
         BAR[4] = hdr->BAR4;
         BAR[5] = hdr->BAR5;
         /* BARs Size */
         for (short i = 0; i < 6; i++)
         {
             if (BAR[i] == 0)
                 continue;
             size_t size;
             if ((BAR[i] & 1) == 0) /* Memory Base */
             {
                 hdr->BAR0 = 0xFFFFFFFF;
                 size = hdr->BAR0;
                 hdr->BAR0 = BAR[i];
                 BARsSize[i] = size & (~15);
                 BARsSize[i] = ~BARsSize[i] + 1;
                 BARsSize[i] = BARsSize[i] & 0xFFFFFFFF;
                 debug("MEM BAR%d %#lx size: %d",
                       i, BAR[i], BARsSize[i]);
             }
             else if ((BAR[i] & 1) == 1) /* I/O Base */
             {
                 hdr->BAR1 = 0xFFFFFFFF;
                 size = hdr->BAR1;
                 hdr->BAR1 = BAR[i];
                 BARsSize[i] = size & (~3);
                 BARsSize[i] = ~BARsSize[i] + 1;
                 BARsSize[i] = BARsSize[i] & 0xFFFF;
                 debug("IO BAR%d %#lx size: %d",
                       i, BAR[i], BARsSize[i]);
             }
         }
         debug("IO %d 64-BIT %d", BAR[0] & 0x1, BAR[0] & 0x4);
         uintptr_t baseAddress = BAR[0];
         if (BAR[0] & 0x4)
             baseAddress |= (uintptr_t)BAR[1] << 32;
         if (baseAddress & 0x1)
             baseAddress &= 0xFFFFFFFFFFFFFFFC;
         else
             baseAddress &= 0xFFFFFFFFFFFFFFF0;
         debug("baseAddress: %#lx", baseAddress);
         Memory::Virtual vmm;
         vmm.Map((void *)baseAddress, (void *)baseAddress, BARsSize[0], Memory::RW);
         caps = (XHCIcap *)baseAddress;
         ops = (XHCIop *)(baseAddress + caps->CAPLENGTH);
         port = (XHCIport *)(baseAddress + caps->CAPLENGTH + 0x400);
         runtime = (XHCIruntime *)(baseAddress + (caps->RTSOFF & ~0x1F));
         doorbell = (XHCIdoorbell *)(baseAddress + (caps->DBOFF & ~0x3));
         uint16_t exCapOffset = caps->HCCPARAMS1.xHCIExtendedCapacitiesPointer << 2;
         ExtendedCaps = (uintptr_t)caps + exCapOffset;
         debug("ExtendedCaps: %#lx (%#lx + %#lx)", ExtendedCaps, caps, exCapOffset);
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Waddress-of-packed-member"
         Interrupter = &runtime->Interrupter[0];
 #pragma GCC diagnostic pop
         break;
     }
     case 1: /* PCI Header 1 (PCI-to-PCI Bridge) */
     {
         ExPrint(ERROR_COLOR "PCI-to-PCI Bridge not supported\n" DEFAULT_COLOR);
         break;
     }
     case 2: /* PCI Header 2 (PCI-to-CardBus Bridge) */
     {
         ExPrint(ERROR_COLOR "PCI-to-CardBus Bridge not supported\n" DEFAULT_COLOR);
         break;
     }
     default:
     {
         ExPrint(ERROR_COLOR "Invalid PCI header type\n" DEFAULT_COLOR);
         break;
     }
     }
 }
References PCI::PCIHeader0::BAR0, PCI::PCIHeader0::BAR1, PCI::PCIHeader0::BAR2, PCI::PCIHeader0::BAR3, PCI::PCIHeader0::BAR4, PCI::PCIHeader0::BAR5, debug, DEFAULT_COLOR, doorbell, ERROR_COLOR, ExPrint(), ExtendedCaps, Header, PCI::PCIDevice::Header, PCI::PCIDeviceHeader::HeaderType, i, Interrupter, Memory::Virtual::Map(), runtime, Memory::RW, and size.
~CrashXHCIKeyboardDriver()
CrashXHCIKeyboardDriver::~CrashXHCIKeyboardDriver () inline
Definition at line 256 of file xhci.hpp.
 {}
Member Function Documentation
Initialize()
nsa bool CrashXHCIKeyboardDriver::Initialize ()
Definition at line 69 of file xhci.cpp.
 {
     int timeout = 10;
     if (!TakeOwnership())
     {
         ExPrint(ERROR_COLOR "Failed to take ownership\n" DEFAULT_COLOR);
         return false;
     }
     stub;
     return false; /* FIXME: stub */
 }
References DEFAULT_COLOR, ERROR_COLOR, ExPrint(), and stub.
Referenced by DetectUSBKeyboard().
OnInterruptReceived()
nsa void CrashXHCIKeyboardDriver::OnInterruptReceived (CPU::TrapFrame * Frame) private virtual
Reimplemented from Interrupts::Handler.
Definition at line 188 of file xhci.cpp.
 {
     debug("Interrupt received");
     Interrupter->IMAN.IP = 1;
     if (!ops->USBSTS.EINT)
         debug("!USBSTS.EINT");
     // return;
     ops->USBSTS.EINT = 1;
     stub;
     Interrupter->IMAN.IP = 0;
     ops->USBSTS.EINT = 0;
 }
References debug, CrashXHCIKeyboardDriver::XHCIruntime::XHCIinterrupter::IMAN, Interrupter, and stub.
TakeOwnership()
nsa bool CrashXHCIKeyboardDriver::TakeOwnership () private
Definition at line 50 of file xhci.cpp.
 {
     HCExtCap *exCap = (HCExtCap *)(uintptr_t)this->ExtendedCaps;
     if (exCap->USBLEGSUP.CapID != 1)
         return true;
     if (exCap->USBLEGSUP.BIOSOwnsHC == 0)
         return true;
     exCap->USBLEGSUP.OSOwnsHC = 1;
     TimeManager->Sleep(200, Time::Milliseconds);
     if (exCap->USBLEGSUP.BIOSOwnsHC == 0)
         return true;
     ExPrint(ERROR_COLOR "BIOS owns the USB controller\n" DEFAULT_COLOR);
     return false;
 }
References DEFAULT_COLOR, ERROR_COLOR, ExPrint(), Time::Milliseconds, Time::time::Sleep(), TimeManager, and CrashXHCIKeyboardDriver::HCExtCap::USBLEGSUP.
Field Documentation
__packed [1/6]
struct CrashXHCIKeyboardDriver::XHCIcap CrashXHCIKeyboardDriver::__packed private
__packed [2/6]
struct CrashXHCIKeyboardDriver::XHCIop CrashXHCIKeyboardDriver::__packed private
__packed [3/6]
struct CrashXHCIKeyboardDriver::XHCIport CrashXHCIKeyboardDriver::__packed private
__packed [4/6]
struct CrashXHCIKeyboardDriver::XHCIruntime CrashXHCIKeyboardDriver::__packed private
__packed [5/6]
struct CrashXHCIKeyboardDriver::HCExtCap CrashXHCIKeyboardDriver::__packed private
__packed [6/6]
struct CrashXHCIKeyboardDriver::XHCIprotocol CrashXHCIKeyboardDriver::__packed private
baseAddrArray
void* CrashXHCIKeyboardDriver::baseAddrArray = nullptr private
Definition at line 245 of file xhci.hpp.
doorbell
union CrashXHCIKeyboardDriver::XHCIdoorbell * CrashXHCIKeyboardDriver::doorbell private
Referenced by CrashXHCIKeyboardDriver().
ExtendedCaps
uintptr_t CrashXHCIKeyboardDriver::ExtendedCaps = 0 private
Definition at line 244 of file xhci.hpp.
Referenced by CrashXHCIKeyboardDriver().
Header
PCI::PCIDeviceHeader* CrashXHCIKeyboardDriver::Header = nullptr private
Definition at line 243 of file xhci.hpp.
Referenced by CrashXHCIKeyboardDriver().
Interrupter
XHCIruntime::XHCIinterrupter* CrashXHCIKeyboardDriver::Interrupter = nullptr private
Definition at line 247 of file xhci.hpp.
Referenced by CrashXHCIKeyboardDriver(), and OnInterruptReceived().
Protocols
std::vector<XHCIprotocol *> CrashXHCIKeyboardDriver::Protocols = {} private
Definition at line 246 of file xhci.hpp.
The documentation for this class was generated from the following files:
Kernel/core/panic/kbd/xhci.hpp
Kernel/core/panic/kbd/xhci.cpp