Fennix: HDADevice Class Reference
HDADevice Class Reference
Public Member Functions
bool IsInitialized ()
size_t write (uint8_t *, size_t Size)
int ioctl (AudioIoctl, void *)
void OnInterruptReceived (TrapFrame *)
void Panic ()
HDADevice (PCIHeader0 *_Header)
~HDADevice ()
Private Attributes
PCIHeader0 * Header
bool Initialized = false
ControllerRegisters * CTL
uint32_t * CORB
uint64_t * RIRB
Detailed Description
Definition at line 27 of file hda.cpp.
Constructor & Destructor Documentation
HDADevice()
HDADevice::HDADevice (PCIHeader0 * _Header) inline
Definition at line 59 of file hda.cpp.
         : Header(_Header),
           CORB((uint32_t *)(uintptr_t)AllocateMemory(1)),
           RIRB((uint64_t *)AllocateMemory(1))
     {
         CTL = (ControllerRegisters *)(uintptr_t)Header->BAR0;
         Log("Unimplemented HDA driver");
         return;
         Initialized = true;
     }
References CTL, Header, Initialized, and Log().
~HDADevice()
HDADevice::~HDADevice () inline
Definition at line 70 of file hda.cpp.
     {
         if (!Initialized)
             return;
     }
References Initialized.
Member Function Documentation
ioctl()
int HDADevice::ioctl (AudioIoctl , void *) inline
Definition at line 46 of file hda.cpp.
     {
         return 0;
     }
Referenced by drvIoctl().
IsInitialized()
bool HDADevice::IsInitialized () inline
Definition at line 39 of file hda.cpp.
 { return Initialized; }
References Initialized.
OnInterruptReceived()
void HDADevice::OnInterruptReceived (TrapFrame *) inline
Definition at line 51 of file hda.cpp.
     {
     }
Panic()
void HDADevice::Panic () inline
Definition at line 55 of file hda.cpp.
     {
     }
Referenced by cxx_Panic().
write()
size_t HDADevice::write (uint8_t * , size_t Size) inline
Definition at line 41 of file hda.cpp.
     {
         return Size;
     }
References Size.
Referenced by drvWrite().
Field Documentation
CORB
uint32_t* HDADevice::CORB private
Definition at line 35 of file hda.cpp.
CTL
ControllerRegisters* HDADevice::CTL private
Definition at line 33 of file hda.cpp.
Referenced by HDADevice().
Header
PCIHeader0* HDADevice::Header private
Definition at line 30 of file hda.cpp.
Referenced by HDADevice().
Initialized
bool HDADevice::Initialized = false private
Definition at line 31 of file hda.cpp.
Referenced by HDADevice(), IsInitialized(), and ~HDADevice().
RIRB
uint64_t* HDADevice::RIRB private
Definition at line 36 of file hda.cpp.
The documentation for this class was generated from the following file:
Drivers/audio/hda/hda.cpp