Fennix: Userspace/musl/src/temp/mktemp.c File Reference
mktemp.c File Reference
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/stat.h>
Macros
#define _GNU_SOURCE
Functions
char * mktemp (char *template)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file mktemp.c.
Function Documentation
mktemp()
char* mktemp (char * template)
Definition at line 7 of file mktemp.c.
 {
     size_t l = strlen(template);
     int retries = 100;
     struct stat st;
     if (l < 6 || memcmp(template+l-6, "XXXXXX", 6)) {
         errno = EINVAL;
         *template = 0;
         return template;
     }
     do {
         __randname(template+l-6);
         if (stat(template, &st)) {
             if (errno != ENOENT) *template = 0;
             return template;
         }
     } while (--retries);
     *template = 0;
     errno = EEXIST;
     return template;
 }
References __randname(), EEXIST, EINVAL, ENOENT, errno, l, memcmp(), stat(), and strlen().
Referenced by mkdtemp(), mktemp_main(), and sh_mktmpname().