Fennix Userspace: Userspace/musl/src/thread/pthread_rwlock_unlock.c File Reference
pthread_rwlock_unlock.c File Reference
#include "pthread_impl.h"
Functions
int __pthread_rwlock_unlock (pthread_rwlock_t *rw)
weak_alias (__pthread_rwlock_unlock, pthread_rwlock_unlock)
Function Documentation
__pthread_rwlock_unlock()
int __pthread_rwlock_unlock (pthread_rwlock_t * rw)
Definition at line 3 of file pthread_rwlock_unlock.c.
 {
     int val, cnt, waiters, new, priv = rw->_rw_shared^128;
     do {
         val = rw->_rw_lock;
         cnt = val & 0x7fffffff;
         waiters = rw->_rw_waiters;
         new = (cnt == 0x7fffffff || cnt == 1) ? 0 : val-1;
     } while (a_cas(&rw->_rw_lock, val, new) != val);
     if (!new && (waiters || val<0))
         __wake(&rw->_rw_lock, cnt, priv);
     return 0;
 }
References __wake(), a_cas, cnt, and val.
Referenced by __pthread_key_atfork(), __pthread_key_create(), __pthread_key_delete(), and __pthread_tsd_run_dtors().
weak_alias()
weak_alias (__pthread_rwlock_unlock , pthread_rwlock_unlock)