Fennix Userspace: Userspace/musl/src/stdio/pclose.c File Reference
pclose.c File Reference
#include "stdio_impl.h"
#include <errno.h>
#include <unistd.h>
Functions
int pclose (FILE *f)
Function Documentation
pclose()
int pclose (FILE * f)
Definition at line 5 of file pclose.c.
 {
     int status, r;
     pid_t pid = f->pipe_pid;
     fclose(f);
     while ((r=__syscall(SYS_wait4, pid, &status, 0, 0)) == -EINTR);
     if (r<0) return __syscall_ret(r);
     return status;
 }
References __syscall, __syscall_ret(), EINTR, f, fclose(), pid, _IO_FILE::pipe_pid, and status.
Referenced by evaluate(), main(), and popmaildir_main().