Fennix Userspace: Userspace/apps/base/busybox/console-tools/loadkmap.c File Reference
loadkmap.c File Reference
#include "libbb.h"
Data Structures
struct kbentry
Macros
#define BINARY_KEYMAP_MAGIC "bkeymap"
#define KDSKBENT 0x4B47
#define NR_KEYS 128
#define MAX_NR_KEYMAPS 256
Functions
int loadkmap_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Data Structure Documentation
kbentry
struct kbentry
Definition at line 33 of file dumpkmap.c.
Data Fields
unsigned char kb_index
unsigned char kb_table
unsigned short kb_value
Macro Definition Documentation
BINARY_KEYMAP_MAGIC
#define BINARY_KEYMAP_MAGIC "bkeymap"
Definition at line 32 of file loadkmap.c.
KDSKBENT
#define KDSKBENT 0x4B47
Definition at line 41 of file loadkmap.c.
MAX_NR_KEYMAPS
#define MAX_NR_KEYMAPS 256
Definition at line 45 of file loadkmap.c.
NR_KEYS
#define NR_KEYS 128
Definition at line 44 of file loadkmap.c.
Function Documentation
loadkmap_main()
int loadkmap_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 48 of file loadkmap.c.
 {
     struct kbentry ke;
     int i, j, fd;
     uint16_t ibuff[NR_KEYS];
 /*  const char *tty_name = CURRENT_TTY; */
     RESERVE_CONFIG_BUFFER(flags, MAX_NR_KEYMAPS);
     /* When user accidentally runs "loadkmap FILE"
      * instead of "loadkmap <FILE", we end up waiting for input from tty.
      * Let's prevent it: */
     if (argv[1])
         bb_show_usage();
 /* bb_warn_ignoring_args(argv[1]); */
     fd = get_console_fd_or_die();
 /* or maybe:
     opt = getopt32(argv, "C:", &tty_name);
     fd = xopen_nonblocking(tty_name);
 */
     xread(STDIN_FILENO, flags, 7);
     if (!is_prefixed_with(flags, BINARY_KEYMAP_MAGIC))
         bb_simple_error_msg_and_die("not a valid binary keymap");
     xread(STDIN_FILENO, flags, MAX_NR_KEYMAPS);
     for (i = 0; i < MAX_NR_KEYMAPS; i++) {
         if (flags[i] != 1)
             continue;
         xread(STDIN_FILENO, ibuff, NR_KEYS * sizeof(uint16_t));
         for (j = 0; j < NR_KEYS; j++) {
             ke.kb_index = j;
             ke.kb_table = i;
             ke.kb_value = ibuff[j];
             /*
              * Note: table[idx:0] can contain special value
              * K_ALLOCATED (marks allocated tables in kernel).
              * dumpkmap saves the value as-is; but attempts
              * to load it here fail, since it isn't a valid
              * key value: it is K(KT_SPEC,126) == 2<<8 + 126,
              * whereas last valid KT_SPEC is
              * K_BARENUMLOCK == K(KT_SPEC,19).
              * So far we just ignore these errors:
              */
             ioctl(fd, KDSKBENT, &ke);
         }
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         close(fd);
         RELEASE_CONFIG_BUFFER(flags);
     }
     return EXIT_SUCCESS;
 }
References argv, bb_show_usage(), bb_simple_error_msg_and_die(), BINARY_KEYMAP_MAGIC, close(), EXIT_SUCCESS, fd, flags, get_console_fd_or_die(), i, ioctl(), is_prefixed_with(), j, kbentry::kb_index, kbentry::kb_table, kbentry::kb_value, KDSKBENT, MAX_NR_KEYMAPS, NR_KEYS, RELEASE_CONFIG_BUFFER, RESERVE_CONFIG_BUFFER, STDIN_FILENO, and xread().