Fennix: Drivers/library/aip.c File Reference
aip.c File Reference
#include <aip.h>
#include <errno.h>
#include <io.h>
Functions
void Log (const char *Format,...)
Print to the kernel logger.
void PIC_EOI (uint8_t IRQ)
void IRQ_MASK (uint8_t IRQ)
void IRQ_UNMASK (uint8_t IRQ)
void PS2Wait (const bool Output)
void PS2WriteCommand (uint8_t Command)
void PS2WriteData (uint8_t Data)
uint8_t PS2ReadData ()
uint8_t PS2ReadStatus ()
uint8_t PS2ReadAfterACK ()
void PS2ClearOutputBuffer ()
int PS2ACKTimeout ()
Function Documentation
IRQ_MASK()
void IRQ_MASK (uint8_t IRQ)
Definition at line 32 of file aip.c.
 {
     uint16_t port;
     uint8_t value;
     if (IRQ < 8)
         port = PIC1_DATA;
     else
     {
         port = PIC2_DATA;
         IRQ -= 8;
     }
     value = inb(port) | (1 << IRQ);
     outb(port, value);
 }
References inb(), outb(), PIC1_DATA, PIC2_DATA, port, and value.
IRQ_UNMASK()
void IRQ_UNMASK (uint8_t IRQ)
Definition at line 49 of file aip.c.
 {
     uint16_t port;
     uint8_t value;
     if (IRQ < 8)
         port = PIC1_DATA;
     else
     {
         port = PIC2_DATA;
         IRQ -= 8;
     }
     value = inb(port) & ~(1 << IRQ);
     outb(port, value);
 }
References inb(), outb(), PIC1_DATA, PIC2_DATA, port, and value.
Log()
void Log (const char * Format, ...)
Print to the kernel logger.
Parameters
Format The format string
... The arguments to the format string
Definition at line 125 of file base.c.
 {
     va_list Args;
     va_start(Args, Format);
     API->KernelLog(API->MajorID,
                    Format,
                    Args);
     va_end(Args);
 }
Referenced by PS2Wait().
PIC_EOI()
void PIC_EOI (uint8_t IRQ)
Definition at line 25 of file aip.c.
 {
     if (IRQ >= 8)
         outb(PIC2_CMD, _PIC_EOI);
     outb(PIC1_CMD, _PIC_EOI);
 }
References _PIC_EOI, outb(), PIC1_CMD, and PIC2_CMD.
PS2ACKTimeout()
int PS2ACKTimeout ()
Definition at line 136 of file aip.c.
 {
     int timeout = 0x500;
     while (timeout > 0)
     {
         if (PS2ReadData() == PS2_ACK)
             return 0;
         timeout--;
     }
     return -ETIMEDOUT;
 }
References ETIMEDOUT, PS2_ACK, PS2ReadData(), and timeout().
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), and InitializeKeyboard().
PS2ClearOutputBuffer()
void PS2ClearOutputBuffer ()
Definition at line 123 of file aip.c.
 {
     PS2_STATUSES Status;
     int timeout = 0x500;
     while (timeout--)
     {
         Status.Raw = inb(PS2_STATUS);
         if (Status.OutputBufferFull == 0)
             return;
         inb(PS2_DATA);
     }
 }
References inb(), PS2_DATA, PS2_STATUS, PS2_STATUSES::Raw, and timeout().
Referenced by DriverEntry(), and InitializeKeyboard().
PS2ReadAfterACK()
uint8_t PS2ReadAfterACK ()
Definition at line 112 of file aip.c.
 {
     uint8_t ret = PS2ReadData();
     while (ret == PS2_ACK)
     {
         WaitOutput;
         ret = inb(PS2_DATA);
     }
     return ret;
 }
References inb(), PS2_ACK, PS2_DATA, PS2ReadData(), and WaitOutput.
Referenced by InitializeKeyboard().
PS2ReadData()
uint8_t PS2ReadData ()
Definition at line 100 of file aip.c.
 {
     WaitOutput;
     return inb(PS2_DATA);
 }
References inb(), PS2_DATA, and WaitOutput.
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), DriverEntry(), InitializeMouse(), MouseSampleRate(), PS2ACKTimeout(), PS2MouseInterruptHandler(), and PS2ReadAfterACK().
PS2ReadStatus()
uint8_t PS2ReadStatus ()
Definition at line 106 of file aip.c.
 {
     WaitOutput;
     return inb(PS2_STATUS);
 }
References inb(), PS2_STATUS, and WaitOutput.
PS2Wait()
void PS2Wait (const bool Output)
Definition at line 66 of file aip.c.
 {
     int Timeout = 100000;
     PS2_STATUSES Status = {.Raw = inb(PS2_STATUS)};
     while (Timeout--)
     {
         if (!Output) /* FIXME: Reverse? */
         {
             if (Status.OutputBufferFull == 0)
                 return;
         }
         else
         {
             if (Status.InputBufferFull == 0)
                 return;
         }
         Status.Raw = inb(PS2_STATUS);
     }
     Log("PS/2 controller timeout! (Status: %#x, %d)", Status, Output);
 }
References inb(), Log(), PS2_STATUS, and PS2_STATUSES::Raw.
PS2WriteCommand()
void PS2WriteCommand (uint8_t Command)
Definition at line 88 of file aip.c.
 {
     WaitInput;
     outb(PS2_CMD, Command);
 }
References outb(), PS2_CMD, and WaitInput.
Referenced by DetectPS2Mouse(), DriverEntry(), DriverFinal(), DriverPanic(), FinalizeMouse(), InitializeMouse(), and MouseSampleRate().
PS2WriteData()
void PS2WriteData (uint8_t Data)
Definition at line 94 of file aip.c.
 {
     WaitInput;
     outb(PS2_DATA, Data);
 }
References Data, outb(), PS2_DATA, and WaitInput.
Referenced by DetectPS2Keyboard(), DetectPS2Mouse(), DriverEntry(), DriverFinal(), DriverPanic(), FinalizeMouse(), InitializeKeyboard(), InitializeMouse(), and MouseSampleRate().