Fennix: Userspace/musl/src/stat/fstatat.c File Reference
fstatat.c File Reference
#include <sys/stat.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <stdint.h>
#include <sys/sysmacros.h>
#include "syscall.h"
Data Structures
struct statx
struct statx.stx_atime
struct statx.stx_btime
struct statx.stx_ctime
struct statx.stx_mtime
Macros
#define _BSD_SOURCE
Functions
static int fstatat_statx (int fd, const char *restrict path, struct stat *restrict st, int flag)
int __fstatat (int fd, const char *restrict path, struct stat *restrict st, int flag)
weak_alias (__fstatat, fstatat)
Data Structure Documentation
statx
struct statx
Definition at line 10 of file fstatat.c.
Data Fields
uint16_t pad1
uint64_t spare[14]
struct statx stx_atime
uint64_t stx_attributes
uint64_t stx_attributes_mask
uint32_t stx_blksize
uint64_t stx_blocks
struct statx stx_btime
struct statx stx_ctime
uint32_t stx_dev_major
uint32_t stx_dev_minor
uint32_t stx_gid
uint64_t stx_ino
uint32_t stx_mask
uint16_t stx_mode
struct statx stx_mtime
uint32_t stx_nlink
uint32_t stx_rdev_major
uint32_t stx_rdev_minor
uint64_t stx_size
uint32_t stx_uid
statx.stx_atime
struct statx.stx_atime
Definition at line 23 of file fstatat.c.
Data Fields
int32_t pad
uint32_t tv_nsec
int64_t tv_sec
statx.stx_btime
struct statx.stx_btime
Definition at line 23 of file fstatat.c.
Data Fields
int32_t pad
uint32_t tv_nsec
int64_t tv_sec
statx.stx_ctime
struct statx.stx_ctime
Definition at line 23 of file fstatat.c.
Data Fields
int32_t pad
uint32_t tv_nsec
int64_t tv_sec
statx.stx_mtime
struct statx.stx_mtime
Definition at line 23 of file fstatat.c.
Data Fields
int32_t pad
uint32_t tv_nsec
int64_t tv_sec
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file fstatat.c.
Function Documentation
__fstatat()
int __fstatat (int fd, const char *restrict path, struct stat *restrict st, int flag)
Definition at line 138 of file fstatat.c.
 {
     int ret;
 #ifdef SYS_fstatat
     if (sizeof((struct kstat){0}.st_atime_sec) < sizeof(time_t)) {
         ret = fstatat_statx(fd, path, st, flag);
         if (ret!=-ENOSYS) return __syscall_ret(ret);
     }
     ret = fstatat_kstat(fd, path, st, flag);
 #else
     ret = fstatat_statx(fd, path, st, flag);
 #endif
     return __syscall_ret(ret);
 }
References __syscall_ret(), ENOSYS, fd, and fstatat_statx().
fstatat_statx()
static int fstatat_statx (int fd, const char *restrict path, struct stat *restrict st, int flag) static
Definition at line 35 of file fstatat.c.
 {
     struct statx stx;
     int ret = __syscall(SYS_statx, fd, path, flag, 0x7ff, &stx);
     if (ret) return ret;
     *st = (struct stat){
         .st_dev = makedev(stx.stx_dev_major, stx.stx_dev_minor),
         .st_ino = stx.stx_ino,
         .st_mode = stx.stx_mode,
         .st_nlink = stx.stx_nlink,
         .st_uid = stx.stx_uid,
         .st_gid = stx.stx_gid,
         .st_rdev = makedev(stx.stx_rdev_major, stx.stx_rdev_minor),
         .st_size = stx.stx_size,
         .st_blksize = stx.stx_blksize,
         .st_blocks = stx.stx_blocks,
         .st_atim.tv_sec = stx.stx_atime.tv_sec,
         .st_atim.tv_nsec = stx.stx_atime.tv_nsec,
         .st_mtim.tv_sec = stx.stx_mtime.tv_sec,
         .st_mtim.tv_nsec = stx.stx_mtime.tv_nsec,
         .st_ctim.tv_sec = stx.stx_ctime.tv_sec,
         .st_ctim.tv_nsec = stx.stx_ctime.tv_nsec,
 #if _REDIR_TIME64
         .__st_atim32.tv_sec = stx.stx_atime.tv_sec,
         .__st_atim32.tv_nsec = stx.stx_atime.tv_nsec,
         .__st_mtim32.tv_sec = stx.stx_mtime.tv_sec,
         .__st_mtim32.tv_nsec = stx.stx_mtime.tv_nsec,
         .__st_ctim32.tv_sec = stx.stx_ctime.tv_sec,
         .__st_ctim32.tv_nsec = stx.stx_ctime.tv_nsec,
 #endif
     };
     return 0;
 }
References __syscall, fd, makedev, statx::stx_atime, statx::stx_blksize, statx::stx_blocks, statx::stx_ctime, statx::stx_dev_major, statx::stx_dev_minor, statx::stx_gid, statx::stx_ino, statx::stx_mode, statx::stx_mtime, statx::stx_nlink, statx::stx_rdev_major, statx::stx_rdev_minor, statx::stx_size, and statx::stx_uid.
Referenced by __fstatat().
weak_alias()
weak_alias (__fstatat , fstatat)