Fennix: Userspace/apps/base/busybox/libpwdgrp/pwd_grp.c File Reference
pwd_grp.c File Reference
#include "libbb.h"
Data Structures
struct const_passdb
struct passdb
struct statics
Macros
#define PW_DEF "SsIIsss"
#define GR_DEF "SsIm"
#define SP_DEF "Ssllllllr"
#define S (*ptr_to_statics)
#define has_S (ptr_to_statics)
Functions
static struct statics * get_S (void)
static int tokenize (char *buffer, int ch)
static char * parse_common (FILE *fp, struct passdb *db, const char *key, int field_pos)
static char * parse_file (struct passdb *db, const char *key, int field_pos)
static void * convert_to_struct (struct passdb *db, char *buffer, void *result)
static int massage_data_for_r_func (struct passdb *db, char *buffer, size_t buflen, void **result, char *buf)
static void * massage_data_for_non_r_func (struct passdb *db, char *buf)
static int FAST_FUNC getXXnam_r (const char *name, uintptr_t db_and_field_pos, char *buffer, size_t buflen, void *result)
int FAST_FUNC getpwnam_r (const char *name, struct passwd *struct_buf, char *buffer, size_t buflen, struct passwd **result)
static void *FAST_FUNC getXXent (uintptr_t db_idx)
struct passwd *FAST_FUNC getpwent (void)
static void *FAST_FUNC getXXnam (const char *name, unsigned db_and_field_pos)
struct passwd *FAST_FUNC getpwnam (const char *name)
struct group *FAST_FUNC getgrnam (const char *name)
struct passwd *FAST_FUNC getpwuid (uid_t id)
struct group *FAST_FUNC getgrgid (gid_t id)
void FAST_FUNC endpwent (void)
void FAST_FUNC setpwent (void)
void FAST_FUNC endgrent (void)
static gid_t *FAST_FUNC getgrouplist_internal (int *ngroups_ptr, const char *user, gid_t gid)
int FAST_FUNC initgroups (const char *user, gid_t gid)
int FAST_FUNC getgrouplist (const char *user, gid_t gid, gid_t *groups, int *ngroups)
Variables
static const struct const_passdb const_pw_db
static const struct const_passdb const_gr_db
static struct statics * ptr_to_statics
Data Structure Documentation
const_passdb
struct const_passdb
Definition at line 34 of file pwd_grp.c.
Data Fields
char def[7+2 *ENABLE_USE_BB_SHADOW]
const char * filename
uint8_t numfields
uint8_t off[7+2 *ENABLE_USE_BB_SHADOW]
uint8_t size_of
passdb
struct passdb
Definition at line 41 of file pwd_grp.c.
Data Fields
char def[7+2 *ENABLE_USE_BB_SHADOW]
const char * filename
FILE * fp
char * malloced
uint8_t numfields
uint8_t off[7+2 *ENABLE_USE_BB_SHADOW]
uint8_t size_of
statics
struct statics
Definition at line 106 of file pwd_grp.c.
Data Fields
struct passdb db[2+ENABLE_USE_BB_SHADOW]
unsigned string_size
char * tokenize_end
Macro Definition Documentation
GR_DEF
#define GR_DEF "SsIm"
Definition at line 61 of file pwd_grp.c.
has_S
#define has_S (ptr_to_statics)
Definition at line 119 of file pwd_grp.c.
PW_DEF
#define PW_DEF "SsIIsss"
Definition at line 60 of file pwd_grp.c.
S
#define S (*ptr_to_statics)
Definition at line 118 of file pwd_grp.c.
SP_DEF
#define SP_DEF "Ssllllllr"
Definition at line 62 of file pwd_grp.c.
Function Documentation
convert_to_struct()
static void* convert_to_struct (struct passdb * db, char * buffer, void * result) static
Definition at line 262 of file pwd_grp.c.
 {
     const char *def = db->def;
     const uint8_t *off = db->off;
     /* For consistency, zero out all fields */
     memset(result, 0, db->size_of);
     for (;;) {
         void *member = (char*)result + (*off++);
         if ((*def | 0x20) == 's') { /* s or S */
             *(char **)member = (char*)buffer;
             if (!buffer[0] && (*def == 'S')) {
                 errno = EINVAL;
             }
         }
         if (*def == 'I') {
             *(int *)member = bb_strtou(buffer, NULL, 10);
         }
 #if ENABLE_USE_BB_SHADOW
         if (*def == 'l') {
             long n = -1;
             if (buffer[0])
                 n = bb_strtol(buffer, NULL, 10);
             *(long *)member = n;
         }
 #endif
         if (*def == 'm') {
             char **members;
             int i = tokenize(buffer, ',');
             /* Store members[] after buffer's end.
              * This is safe ONLY because there is a hack
              * in parse_common() which allocates additional space
              * at the end of malloced buffer!
              */
             members = (char **)
                 ( ((intptr_t)S.tokenize_end + sizeof(members[0]))
                 & -(intptr_t)sizeof(members[0])
                 );
             ((struct group *)result)->gr_mem = members;
             while (--i >= 0) {
                 if (buffer[0]) {
                     *members++ = buffer;
                     // bb_error_msg("member[]='%s'", buffer);
                 }
                 buffer += strlen(buffer) + 1;
             }
             *members = NULL;
         }
         /* def "r" does nothing */
         def++;
         if ((unsigned char)*def <= (unsigned char)' ')
             break;
         buffer += strlen(buffer) + 1;
     }
     if (errno)
         result = NULL;
     return result;
 }
References bb_strtol(), bb_strtou(), buffer, statics::db, passdb::def, EINVAL, errno, i, member, memset, n, NULL, passdb::off, off, S, passdb::size_of, strlen, and tokenize().
Referenced by getgrouplist_internal(), massage_data_for_non_r_func(), and massage_data_for_r_func().
endgrent()
void FAST_FUNC endgrent (void)
Definition at line 500 of file pwd_grp.c.
 {
     if (has_S && S.db[1].fp) {
         fclose(S.db[1].fp);
         S.db[1].fp = NULL;
     }
 }
References fclose(), has_S, NULL, and S.
Referenced by change_identity().
endpwent()
void FAST_FUNC endpwent (void)
Definition at line 487 of file pwd_grp.c.
 {
     if (has_S && S.db[0].fp) {
         fclose(S.db[0].fp);
         S.db[0].fp = NULL;
     }
 }
References fclose(), has_S, NULL, and S.
Referenced by get_current_user_info(), get_home_dir(), rl_username_completion_function(), sh_get_home_dir(), and tilde_expand_word().
get_S()
static struct statics* get_S (void) static
Definition at line 133 of file pwd_grp.c.
 {
     if (!ptr_to_statics) {
         ptr_to_statics = xzalloc(sizeof(S));
         memcpy(&S.db[0], &const_pw_db, sizeof(const_pw_db));
         memcpy(&S.db[1], &const_gr_db, sizeof(const_gr_db));
 #if ENABLE_USE_BB_SHADOW
         memcpy(&S.db[2], &const_sp_db, sizeof(const_sp_db));
 #endif
 #if ENABLE_FEATURE_CLEAN_UP
         atexit(free_static);
 #endif
     }
     return ptr_to_statics;
 }
References atexit, const_gr_db, const_pw_db, memcpy, ptr_to_statics, S, and xzalloc().
Referenced by getgrouplist_internal(), getXXent(), getXXnam(), and getXXnam_r().
getgrgid()
struct group* FAST_FUNC getgrgid (gid_t id)
Definition at line 480 of file pwd_grp.c.
 {
     return getXXnam(utoa(id), (1 << 2) + 2);
 }
getgrnam()
struct group* FAST_FUNC getgrnam (const char * name)
Definition at line 472 of file pwd_grp.c.
 {
     return getXXnam(name, (1 << 2) + 0);
 }
getgrouplist()
int FAST_FUNC getgrouplist (const char * user, gid_t gid, gid_t * groups, int * ngroups)
Definition at line 559 of file pwd_grp.c.
 {
     int ngroups_old = *ngroups;
     gid_t *group_list = getgrouplist_internal(ngroups, user, gid);
     if (*ngroups <= ngroups_old) {
         ngroups_old = *ngroups;
         memcpy(groups, group_list, ngroups_old * sizeof(groups[0]));
     } else {
         ngroups_old = -1;
     }
     free(group_list);
     return ngroups_old;
 }
getgrouplist_internal()
static gid_t* FAST_FUNC getgrouplist_internal (int * ngroups_ptr, const char * user, gid_t gid) static
Definition at line 510 of file pwd_grp.c.
 {
     FILE *fp;
     gid_t *group_list;
     int ngroups;
     /* We alloc space for 8 gids at a time. */
     group_list = xzalloc(8 * sizeof(group_list[0]));
     group_list[0] = gid;
     ngroups = 1;
     fp = fopen_for_read(_PATH_GROUP);
     if (fp) {
         struct passdb *db = &get_S()->db[1];
         char *buf;
         while ((buf = parse_common(fp, db, NULL, -1)) != NULL) {
             char **m;
             struct group group;
             if (!convert_to_struct(db, buf, &group))
                 goto next;
             if (group.gr_gid == gid)
                 goto next;
             for (m = group.gr_mem; *m; m++) {
                 if (strcmp(*m, user) != 0)
                     continue;
                 group_list = xrealloc_vector(group_list, /*8=2^3:*/ 3, ngroups);
                 group_list[ngroups++] = group.gr_gid;
                 goto next;
             }
  next:
             free(buf);
         }
         fclose(fp);
     }
     *ngroups_ptr = ngroups;
     return group_list;
 }
References _PATH_GROUP, buf, convert_to_struct(), statics::db, fclose(), fopen_for_read(), passdb::fp, free, get_S(), group::gr_gid, group::gr_mem, next, ngroups, NULL, parse_common(), strcmp, xrealloc_vector, and xzalloc().
Referenced by getgrouplist(), and initgroups().
getpwent()
struct passwd* FAST_FUNC getpwent (void)
Definition at line 452 of file pwd_grp.c.
 {
     return getXXent(0);
 }
References getXXent().
getpwnam()
struct passwd* FAST_FUNC getpwnam (const char * name)
Definition at line 468 of file pwd_grp.c.
 {
     return getXXnam(name, (0 << 2) + 0);
 }
getpwnam_r()
int FAST_FUNC getpwnam_r (const char * name, struct passwd * struct_buf, char * buffer, size_t buflen, struct passwd ** result)
Definition at line 382 of file pwd_grp.c.
 {
     /* Why the "store buffer address in result" trick?
      * This way, getXXnam_r has the same ABI signature as getpwnam_r,
      * hopefully compiler can optimize tail call better in this case.
      */
     *result = struct_buf;
     return getXXnam_r(name, (0 << 2) + 0, buffer, buflen, result);
 }
References buflen, and getXXnam_r().
getpwuid()
struct passwd* FAST_FUNC getpwuid (uid_t id)
Definition at line 476 of file pwd_grp.c.
 {
     return getXXnam(utoa(id), (0 << 2) + 2);
 }
getXXent()
static void* FAST_FUNC getXXent (uintptr_t db_idx) static
Definition at line 435 of file pwd_grp.c.
 {
     char *buf;
     struct passdb *db = &get_S()->db[db_idx];
     if (!db->fp) {
         db->fp = fopen_for_read(db->filename);
         if (!db->fp) {
             return NULL;
         }
         close_on_exec_on(fileno(db->fp));
     }
     buf = parse_common(db->fp, db, /*no search key:*/ NULL, -1);
     return massage_data_for_non_r_func(db, buf);
 }
References buf, close_on_exec_on(), statics::db, passdb::filename, fileno(), fopen_for_read(), passdb::fp, get_S(), massage_data_for_non_r_func(), NULL, and parse_common().
Referenced by getpwent().
getXXnam()
static void* FAST_FUNC getXXnam (const char * name, unsigned db_and_field_pos) static
Definition at line 459 of file pwd_grp.c.
 {
     char *buf;
     struct passdb *db = &get_S()->db[db_and_field_pos >> 2];
     buf = parse_file(db, name, db_and_field_pos & 3);
     return massage_data_for_non_r_func(db, buf);
 }
References buf, statics::db, get_S(), massage_data_for_non_r_func(), and parse_file().
Referenced by getgrgid(), getgrnam(), getpwnam(), and getpwuid().
getXXnam_r()
static int FAST_FUNC getXXnam_r (const char * name, uintptr_t db_and_field_pos, char * buffer, size_t buflen, void * result) static
Definition at line 368 of file pwd_grp.c.
 {
     char *buf;
     struct passdb *db = &get_S()->db[db_and_field_pos >> 2];
     buf = parse_file(db, name, 0 /*db_and_field_pos & 3*/);
     /* "db_and_field_pos & 3" is commented out since so far we don't implement
      * getXXXid_r() functions which would use that to pass 2 here */
     return massage_data_for_r_func(db, buffer, buflen, result, buf);
 }
References buf, buflen, statics::db, get_S(), massage_data_for_r_func(), and parse_file().
Referenced by getpwnam_r().
initgroups()
int FAST_FUNC initgroups (const char * user, gid_t gid)
Definition at line 549 of file pwd_grp.c.
 {
     int ngroups;
     gid_t *group_list = getgrouplist_internal(&ngroups, user, gid);
     ngroups = setgroups(ngroups, group_list);
     free(group_list);
     return ngroups;
 }
massage_data_for_non_r_func()
static void* massage_data_for_non_r_func (struct passdb * db, char * buf) static
Definition at line 350 of file pwd_grp.c.
 {
     if (!buf)
         return NULL;
     free(db->malloced);
     /* We enlarge buf and move string data up, freeing space
      * for struct passwd/group/spwd at the beginning. This way,
      * entire result of getXXnam is in a single malloced block.
      * This enables easy creation of xmalloc_getpwnam() API.
      */
     db->malloced = buf = xrealloc(buf, db->size_of + S.string_size);
     memmove(buf + db->size_of, buf, S.string_size);
     return convert_to_struct(db, buf + db->size_of, buf);
 }
References buf, convert_to_struct(), free, passdb::malloced, memmove, NULL, S, passdb::size_of, and xrealloc.
Referenced by getXXent(), and getXXnam().
massage_data_for_r_func()
static int massage_data_for_r_func (struct passdb * db, char * buffer, size_t buflen, void ** result, char * buf) static
Definition at line 327 of file pwd_grp.c.
 {
     void *result_buf = *result;
     *result = NULL;
     if (buf) {
         if (S.string_size > buflen) {
             errno = ERANGE;
         } else {
             memcpy(buffer, buf, S.string_size);
             *result = convert_to_struct(db, buffer, result_buf);
         }
         free(buf);
     }
     /* "The reentrant functions return zero on success.
      * In case of error, an error number is returned."
      * NB: not finding the record is also a "success" here:
      */
     return errno;
 }
References buf, buflen, convert_to_struct(), ERANGE, errno, free, memcpy, NULL, and S.
Referenced by getXXnam_r().
parse_common()
static char* parse_common (FILE * fp, struct passdb * db, const char * key, int field_pos) static
Definition at line 188 of file pwd_grp.c.
 {
     char *buf;
     while ((buf = xmalloc_fgetline(fp)) != NULL) {
         int n;
         char *field;
         /* Skip empty lines, comment lines */
         if (buf[0] == '\0' || buf[0] == '#')
             goto free_and_next;
         if (tokenize(buf, ':') != db->numfields) {
             /* number of fields is wrong */
             bb_error_msg("%s: bad record", db->filename);
             goto free_and_next;
         }
         if (field_pos == -1) {
             /* no key specified: sequential read, return a record */
             break;
         }
         /* Can't use nth_string() here, it does not allow empty strings
          * ("\0\0" terminates the list), and a valid passwd entry
          * "user::UID:GID..." would be mishandled */
         n = field_pos;
         field = buf;
         while (n) {
             n--;
             field += strlen(field) + 1;
         }
         if (strcmp(key, field) == 0) {
             /* record found */
             break;
         }
  free_and_next:
         free(buf);
     }
     S.string_size = S.tokenize_end - buf;
 /*
  * Ugly hack: group db requires additional buffer space
  * for members[] array. If there is only one group, we need space
  * for 3 pointers: alignment padding, group name, NULL.
  * +1 for every additional group.
  */
     if (buf && db->numfields == sizeof(GR_DEF)-1) { /* if we read group file... */
         int cnt = 3;
         char *p = buf;
         while (p < S.tokenize_end)
             if (*p++ == ',')
                 cnt++;
         S.string_size += cnt * sizeof(char*);
 //bb_error_msg("+%d words = %u key:%s buf:'%s'", cnt, S.string_size, key, buf);
         buf = xrealloc(buf, S.string_size);
     }
     return buf;
 }
References bb_error_msg(), buf, cnt, statics::db, passdb::filename, free, GR_DEF, n, NULL, passdb::numfields, p, S, strcmp, strlen, tokenize(), xmalloc_fgetline(), and xrealloc.
Referenced by getgrouplist_internal(), getXXent(), and parse_file().
parse_file()
static char* parse_file (struct passdb * db, const char * key, int field_pos) static
Definition at line 248 of file pwd_grp.c.
 {
     char *buf = NULL;
     FILE *fp = fopen_for_read(db->filename);
     if (fp) {
         buf = parse_common(fp, db, key, field_pos);
         fclose(fp);
     }
     return buf;
 }
References buf, statics::db, fclose(), passdb::filename, fopen_for_read(), NULL, and parse_common().
Referenced by getXXnam(), and getXXnam_r().
setpwent()
void FAST_FUNC setpwent (void)
Definition at line 494 of file pwd_grp.c.
 {
     if (has_S && S.db[0].fp) {
         rewind(S.db[0].fp);
     }
 }
References has_S, rewind(), and S.
tokenize()
static int tokenize (char * buffer, int ch) static
Definition at line 157 of file pwd_grp.c.
 {
     char *p = buffer;
     char *s = p;
     int num_fields = 0;
     for (;;) {
         if (isblank(*s)) {
             overlapping_strcpy(s, skip_whitespace(s));
         }
         if (*p == ch || *p == '\0') {
             char *end = p;
             while (p != s && isblank(p[-1]))
                 p--;
             if (p != end)
                 overlapping_strcpy(p, end);
             num_fields++;
             if (*end == '\0') {
                 S.tokenize_end = p + 1;
                 return num_fields;
             }
             *p = '\0';
             s = p + 1;
         }
         p++;
     }
 }
References buffer, end, isblank, overlapping_strcpy(), p, S, s, and skip_whitespace().
Referenced by convert_to_struct(), and parse_common().
Variable Documentation
const_gr_db
const struct const_passdb const_gr_db static
Initial value:
= {
    _PATH_GROUP, GR_DEF,
    {
        offsetof(struct group, gr_name),
        offsetof(struct group, gr_passwd),
        offsetof(struct group, gr_gid),
        offsetof(struct group, gr_mem)
    },
    sizeof(GR_DEF)-1, sizeof(struct group)
}
Definition at line 1 of file pwd_grp.c.
Referenced by get_S().
const_pw_db
const struct const_passdb const_pw_db static
Initial value:
= {
    _PATH_PASSWD, PW_DEF,
    {
        offsetof(struct passwd, pw_name),
        offsetof(struct passwd, pw_passwd),
        offsetof(struct passwd, pw_uid),
        offsetof(struct passwd, pw_gid),
        offsetof(struct passwd, pw_gecos),
        offsetof(struct passwd, pw_dir),
        offsetof(struct passwd, pw_shell)
    },
    sizeof(PW_DEF)-1, sizeof(struct passwd)
}
Definition at line 1 of file pwd_grp.c.
Referenced by get_S().
ptr_to_statics
struct statics* ptr_to_statics static
Definition at line 117 of file pwd_grp.c.
Referenced by get_S().