Fennix: Userspace/musl/src/exit/arm/__aeabi_atexit.c File Reference
__aeabi_atexit.c File Reference
Functions
int __cxa_atexit (void(*func)(void *), void *arg, void *dso)
int __aeabi_atexit (void *obj, void(*func)(void *), void *d)
Function Documentation
__aeabi_atexit()
int __aeabi_atexit (void * obj, void(*)(void *) func, void * d)
Definition at line 3 of file __aeabi_atexit.c.
 {
     return __cxa_atexit (func, obj, d);
 }
References __cxa_atexit(), and func().
__cxa_atexit()
int __cxa_atexit (void(*)(void *) f, void * objptr, void * dso)
Parameters
f The destructor
objptr The object to be destructed
dso The DSO from which the object was obtained (unused in our case)
Returns
Zero on success, non-zero on failure
Definition at line 44 of file cxxabi.cpp.
 {
     if (KernelSymbolTable)
     {
         debug("Registering atexit function for \"%s\" with destructor \"%s\"",
               KernelSymbolTable->GetSymbol((uintptr_t)objptr),
               KernelSymbolTable->GetSymbol((uintptr_t)f));
     }
     else
     {
         debug("Registering atexit function for %p with destructor %p",
               objptr, f);
     }
     if (__atexit_func_count >= ATEXIT_MAX_FUNCS)
         return -1;
     __atexit_funcs[__atexit_func_count].destructor_func = f;
     __atexit_funcs[__atexit_func_count].obj_ptr = objptr;
     __atexit_funcs[__atexit_func_count].dso_handle = dso;
     __atexit_func_count++;
     return 0;
 }
References __atexit_func_count, __atexit_funcs, fl::a, arg, ATEXIT_MAX_FUNCS, builtin, calloc, COUNT, debug, __cxxabiv1::atexit_func_entry_t::destructor_func, atexit_func_entry_t::destructor_func, __cxxabiv1::atexit_func_entry_t::dso_handle, atexit_func_entry_t::dso_handle, fl::f, f, func(), SymbolResolver::Symbols::GetSymbol(), head, KernelSymbolTable, LOCK, lock, fl::next, __cxxabiv1::atexit_func_entry_t::obj_ptr, atexit_func_entry_t::obj_ptr, printf(), slot, and UNLOCK.
Referenced by __aeabi_atexit(), and atexit().