Fennix: Userspace/musl/include/wordexp.h File Reference
wordexp.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct wordexp_t
Macros
#define __NEED_size_t
#define WRDE_DOOFFS 1
#define WRDE_APPEND 2
#define WRDE_NOCMD 4
#define WRDE_REUSE 8
#define WRDE_SHOWERR 16
#define WRDE_UNDEF 32
#define WRDE_NOSYS -1
#define WRDE_NOSPACE 1
#define WRDE_BADCHAR 2
#define WRDE_BADVAL 3
#define WRDE_CMDSUB 4
#define WRDE_SYNTAX 5
Functions
int wordexp (const char *__restrict, wordexp_t *__restrict, int)
void wordfree (wordexp_t *)
Data Structure Documentation
wordexp_t
struct wordexp_t
Definition at line 24 of file wordexp.h.
Data Fields
size_t we_nbytes
size_t we_offs
char * we_strings
size_t we_wordc
char ** we_wordv
Macro Definition Documentation
__NEED_size_t
#define __NEED_size_t
Definition at line 10 of file wordexp.h.
WRDE_APPEND
#define WRDE_APPEND 2
Definition at line 15 of file wordexp.h.
WRDE_BADCHAR
#define WRDE_BADCHAR 2
Definition at line 29 of file wordexp.h.
WRDE_BADVAL
#define WRDE_BADVAL 3
Definition at line 30 of file wordexp.h.
WRDE_CMDSUB
#define WRDE_CMDSUB 4
Definition at line 31 of file wordexp.h.
WRDE_DOOFFS
#define WRDE_DOOFFS 1
Definition at line 14 of file wordexp.h.
WRDE_NOCMD
#define WRDE_NOCMD 4
Definition at line 16 of file wordexp.h.
WRDE_NOSPACE
#define WRDE_NOSPACE 1
Definition at line 28 of file wordexp.h.
WRDE_NOSYS
#define WRDE_NOSYS -1
Definition at line 27 of file wordexp.h.
WRDE_REUSE
#define WRDE_REUSE 8
Definition at line 17 of file wordexp.h.
WRDE_SHOWERR
#define WRDE_SHOWERR 16
Definition at line 18 of file wordexp.h.
WRDE_SYNTAX
#define WRDE_SYNTAX 5
Definition at line 32 of file wordexp.h.
WRDE_UNDEF
#define WRDE_UNDEF 32
Definition at line 19 of file wordexp.h.
Function Documentation
wordexp()
int wordexp (const char * __restrict, wordexp_t * __restrict, int)
wordfree()
void wordfree (wordexp_t * we)
Definition at line 333 of file wordexp-stubs.cpp.
{
     if (we == NULL)
         return;
     free(we->we_wordv);
     free(we->we_strings);
     we->we_wordv = NULL;
     we->we_strings = NULL;
     we->we_nbytes = 0;
     we->we_wordc = 0;
 }
References free, i, NULL, wordexp_t::we_nbytes, wordexp_t::we_offs, wordexp_t::we_strings, wordexp_t::we_wordc, and wordexp_t::we_wordv.
Referenced by do_wordexp(), main(), and wordexp().