Fennix: Userspace/musl/src/network/netlink.h File Reference
netlink.h File Reference
#include <stdint.h>
Data Structures
struct nlmsghdr
struct rtattr
struct rtgenmsg
struct ifinfomsg
struct ifaddrmsg
Macros
#define NETLINK_ROUTE 0
#define NLM_F_REQUEST 1
#define NLM_F_MULTI 2
#define NLM_F_ACK 4
#define NLM_F_ROOT 0x100
#define NLM_F_MATCH 0x200
#define NLM_F_ATOMIC 0x400
#define NLM_F_DUMP (NLM_F_ROOT|NLM_F_MATCH)
#define NLMSG_NOOP 0x1
#define NLMSG_ERROR 0x2
#define NLMSG_DONE 0x3
#define NLMSG_OVERRUN 0x4
#define RTM_NEWLINK 16
#define RTM_GETLINK 18
#define RTM_NEWADDR 20
#define RTM_GETADDR 22
#define IFLA_ADDRESS 1
#define IFLA_BROADCAST 2
#define IFLA_IFNAME 3
#define IFLA_STATS 7
#define IFA_ADDRESS 1
#define IFA_LOCAL 2
#define IFA_LABEL 3
#define IFA_BROADCAST 4
#define NETLINK_ALIGN(len) (((len)+3) & ~3)
#define NLMSG_DATA(nlh) ((void*)((char*)(nlh)+sizeof(struct nlmsghdr)))
#define NLMSG_DATALEN(nlh) ((nlh)->nlmsg_len-sizeof(struct nlmsghdr))
#define NLMSG_DATAEND(nlh) ((char*)(nlh)+(nlh)->nlmsg_len)
#define NLMSG_NEXT(nlh) (struct nlmsghdr*)((char*)(nlh)+NETLINK_ALIGN((nlh)->nlmsg_len))
#define NLMSG_OK(nlh, end) ((char*)(end)-(char*)(nlh) >= sizeof(struct nlmsghdr))
#define RTA_DATA(rta) ((void*)((char*)(rta)+sizeof(struct rtattr)))
#define RTA_DATALEN(rta) ((rta)->rta_len-sizeof(struct rtattr))
#define RTA_DATAEND(rta) ((char*)(rta)+(rta)->rta_len)
#define RTA_NEXT(rta) (struct rtattr*)((char*)(rta)+NETLINK_ALIGN((rta)->rta_len))
#define RTA_OK(rta, end) ((char*)(end)-(char*)(rta) >= sizeof(struct rtattr))
#define NLMSG_RTA(nlh, len) ((void*)((char*)(nlh)+sizeof(struct nlmsghdr)+NETLINK_ALIGN(len)))
#define NLMSG_RTAOK(rta, nlh) RTA_OK(rta,NLMSG_DATAEND(nlh))
Functions
hidden int __rtnetlink_enumerate (int link_af, int addr_af, int(*cb)(void *ctx, struct nlmsghdr *h), void *ctx)
Data Structure Documentation
nlmsghdr
struct nlmsghdr
Definition at line 7 of file netlink.h.
Data Fields
uint16_t nlmsg_flags
uint32_t nlmsg_len
uint32_t nlmsg_pid
uint32_t nlmsg_seq
uint16_t nlmsg_type
rtattr
struct rtattr
Definition at line 36 of file netlink.h.
Data Fields
unsigned short rta_len
unsigned short rta_type
rtgenmsg
struct rtgenmsg
Definition at line 41 of file netlink.h.
Data Fields
unsigned char rtgen_family
ifinfomsg
struct ifinfomsg
Definition at line 45 of file netlink.h.
Data Fields
unsigned char __ifi_pad
unsigned ifi_change
unsigned char ifi_family
unsigned ifi_flags
int ifi_index
unsigned short ifi_type
ifaddrmsg
struct ifaddrmsg
Definition at line 63 of file netlink.h.
Data Fields
uint8_t ifa_family
uint8_t ifa_flags
uint32_t ifa_index
uint8_t ifa_prefixlen
uint8_t ifa_scope
Macro Definition Documentation
IFA_ADDRESS
#define IFA_ADDRESS 1
Definition at line 71 of file netlink.h.
IFA_BROADCAST
#define IFA_BROADCAST 4
Definition at line 74 of file netlink.h.
IFA_LABEL
#define IFA_LABEL 3
Definition at line 73 of file netlink.h.
IFA_LOCAL
#define IFA_LOCAL 2
Definition at line 72 of file netlink.h.
IFLA_ADDRESS
#define IFLA_ADDRESS 1
Definition at line 56 of file netlink.h.
IFLA_BROADCAST
#define IFLA_BROADCAST 2
Definition at line 57 of file netlink.h.
IFLA_IFNAME
#define IFLA_IFNAME 3
Definition at line 58 of file netlink.h.
IFLA_STATS
#define IFLA_STATS 7
Definition at line 59 of file netlink.h.
NETLINK_ALIGN
#define NETLINK_ALIGN (len) (((len)+3) & ~3)
Definition at line 78 of file netlink.h.
NETLINK_ROUTE
#define NETLINK_ROUTE 0
Definition at line 5 of file netlink.h.
NLM_F_ACK
#define NLM_F_ACK 4
Definition at line 17 of file netlink.h.
NLM_F_ATOMIC
#define NLM_F_ATOMIC 0x400
Definition at line 21 of file netlink.h.
NLM_F_DUMP
#define NLM_F_DUMP (NLM_F_ROOT|NLM_F_MATCH)
Definition at line 22 of file netlink.h.
NLM_F_MATCH
#define NLM_F_MATCH 0x200
Definition at line 20 of file netlink.h.
NLM_F_MULTI
#define NLM_F_MULTI 2
Definition at line 16 of file netlink.h.
NLM_F_REQUEST
#define NLM_F_REQUEST 1
Definition at line 15 of file netlink.h.
NLM_F_ROOT
#define NLM_F_ROOT 0x100
Definition at line 19 of file netlink.h.
NLMSG_DATA
#define NLMSG_DATA (nlh) ((void*)((char*)(nlh)+sizeof(struct nlmsghdr)))
Definition at line 79 of file netlink.h.
NLMSG_DATAEND
#define NLMSG_DATAEND (nlh) ((char*)(nlh)+(nlh)->nlmsg_len)
Definition at line 81 of file netlink.h.
NLMSG_DATALEN
#define NLMSG_DATALEN (nlh) ((nlh)->nlmsg_len-sizeof(struct nlmsghdr))
Definition at line 80 of file netlink.h.
NLMSG_DONE
#define NLMSG_DONE 0x3
Definition at line 26 of file netlink.h.
NLMSG_ERROR
#define NLMSG_ERROR 0x2
Definition at line 25 of file netlink.h.
NLMSG_NEXT
#define NLMSG_NEXT (nlh) (struct nlmsghdr*)((char*)(nlh)+NETLINK_ALIGN((nlh)->nlmsg_len))
Definition at line 82 of file netlink.h.
NLMSG_NOOP
#define NLMSG_NOOP 0x1
Definition at line 24 of file netlink.h.
NLMSG_OK
#define NLMSG_OK (nlh, end) ((char*)(end)-(char*)(nlh) >= sizeof(struct nlmsghdr))
Definition at line 83 of file netlink.h.
NLMSG_OVERRUN
#define NLMSG_OVERRUN 0x4
Definition at line 27 of file netlink.h.
NLMSG_RTA
#define NLMSG_RTA (nlh, len) ((void*)((char*)(nlh)+sizeof(struct nlmsghdr)+NETLINK_ALIGN(len)))
Definition at line 91 of file netlink.h.
NLMSG_RTAOK
#define NLMSG_RTAOK (rta, nlh) RTA_OK(rta,NLMSG_DATAEND(nlh))
Definition at line 92 of file netlink.h.
RTA_DATA
#define RTA_DATA (rta) ((void*)((char*)(rta)+sizeof(struct rtattr)))
Definition at line 85 of file netlink.h.
RTA_DATAEND
#define RTA_DATAEND (rta) ((char*)(rta)+(rta)->rta_len)
Definition at line 87 of file netlink.h.
RTA_DATALEN
#define RTA_DATALEN (rta) ((rta)->rta_len-sizeof(struct rtattr))
Definition at line 86 of file netlink.h.
RTA_NEXT
#define RTA_NEXT (rta) (struct rtattr*)((char*)(rta)+NETLINK_ALIGN((rta)->rta_len))
Definition at line 88 of file netlink.h.
RTA_OK
#define RTA_OK (rta, end) ((char*)(end)-(char*)(rta) >= sizeof(struct rtattr))
Definition at line 89 of file netlink.h.
RTM_GETADDR
#define RTM_GETADDR 22
Definition at line 34 of file netlink.h.
RTM_GETLINK
#define RTM_GETLINK 18
Definition at line 32 of file netlink.h.
RTM_NEWADDR
#define RTM_NEWADDR 20
Definition at line 33 of file netlink.h.
RTM_NEWLINK
#define RTM_NEWLINK 16
Definition at line 31 of file netlink.h.
Function Documentation
__rtnetlink_enumerate()
hidden int __rtnetlink_enumerate (int link_af, int addr_af, int(*)(void *ctx, struct nlmsghdr *h) cb, void * ctx)
Definition at line 42 of file netlink.c.
 {
     int fd, r;
     fd = socket(PF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE);
     if (fd < 0) return -1;
     r = __netlink_enumerate(fd, 1, RTM_GETLINK, link_af, cb, ctx);
     if (!r) r = __netlink_enumerate(fd, 2, RTM_GETADDR, addr_af, cb, ctx);
     __syscall(SYS_close,fd);
     return r;
 }
References __netlink_enumerate(), __syscall, fd, NETLINK_ROUTE, PF_NETLINK, RTM_GETADDR, RTM_GETLINK, SOCK_CLOEXEC, SOCK_RAW, and socket().
Referenced by getifaddrs(), and if_nameindex().