Fennix Userspace: Userspace/apps/base/busybox/util-linux/volume_id/util.c File Reference
util.c File Reference
#include "volume_id_internal.h"
Functions
void volume_id_set_unicode16 (char *str, size_t len, const uint8_t *buf, enum endian endianess, size_t count)
void volume_id_set_label_string (struct volume_id *id, const uint8_t *buf, size_t count)
void volume_id_set_label_unicode16 (struct volume_id *id, const uint8_t *buf, enum endian endianess, size_t count)
void volume_id_set_uuid (struct volume_id *id, const uint8_t *buf, enum uuid_format format)
void * volume_id_get_buffer (struct volume_id *id, uint64_t off, size_t len)
void volume_id_free_buffer (struct volume_id *id)
Function Documentation
volume_id_free_buffer()
void volume_id_free_buffer (struct volume_id * id)
Definition at line 256 of file util.c.
 {
     free(id->sbbuf);
     id->sbbuf = NULL;
     id->sbbuf_len = 0;
     free(id->seekbuf);
     id->seekbuf = NULL;
     id->seekbuf_len = 0;
     id->seekbuf_off = 0; /* paranoia */
 }
References free, NULL, volume_id::sbbuf, and volume_id::seekbuf.
Referenced by free_volume_id(), volume_id_get_buffer(), and volume_id_probe_all().
volume_id_get_buffer()
void* volume_id_get_buffer (struct volume_id * id, uint64_t off, size_t len)
Definition at line 179 of file util.c.
 {
     uint8_t *dst;
     unsigned small_off;
     ssize_t read_len;
     dbg("get buffer off 0x%llx(%llu), len 0x%zx",
         (unsigned long long) off, (unsigned long long) off, len);
     /* check if requested area fits in superblock buffer */
     if (off + len <= SB_BUFFER_SIZE
      /* && off <= SB_BUFFER_SIZE - want this paranoid overflow check? */
     ) {
         if (id->sbbuf == NULL) {
             id->sbbuf = xmalloc(SB_BUFFER_SIZE);
         }
         small_off = off;
         dst = id->sbbuf;
         /* check if we need to read */
         len += off;
         if (len <= id->sbbuf_len)
             goto ret; /* we already have it */
         dbg("read sbbuf len:0x%x", (unsigned) len);
         id->sbbuf_len = len;
         off = 0;
         goto do_read;
     }
     if (len > SEEK_BUFFER_SIZE) {
         dbg("seek buffer too small %d", SEEK_BUFFER_SIZE);
         return NULL;
     }
     dst = id->seekbuf;
     /* check if we need to read */
     if ((off >= id->seekbuf_off)
      && ((off + len) <= (id->seekbuf_off + id->seekbuf_len))
     ) {
         small_off = off - id->seekbuf_off; /* can't overflow */
         goto ret; /* we already have it */
     }
     id->seekbuf_off = off;
     id->seekbuf_len = len;
     id->seekbuf = xrealloc(id->seekbuf, len);
     small_off = 0;
     dst = id->seekbuf;
     dbg("read seekbuf off:0x%llx len:0x%zx",
                 (unsigned long long) off, len);
  do_read:
     if (lseek(id->fd, off, SEEK_SET) != off) {
         dbg("seek(0x%llx) failed", (unsigned long long) off);
         goto err;
     }
     read_len = full_read(id->fd, dst, len);
     if (read_len != len) {
         dbg("requested 0x%x bytes, got 0x%x bytes",
                 (unsigned) len, (unsigned) read_len);
  err:
         /* No filesystem can be this tiny. It's most likely
          * non-associated loop device, empty drive and so on.
          * Flag it, making it possible to short circuit future
          * accesses. Rationale:
          * users complained of slow blkid due to empty floppy drives.
          */
         if (off < 64*1024)
             id->error = 1;
         /* id->seekbuf_len or id->sbbuf_len is wrong now! Fixing. */
         volume_id_free_buffer(id);
         return NULL;
     }
  ret:
     return dst + small_off;
 }
References dbg, do_read(), dst, err(), volume_id::fd, full_read(), lseek(), NULL, off, SB_BUFFER_SIZE, volume_id::sbbuf, SEEK_BUFFER_SIZE, SEEK_SET, volume_id::seekbuf, volume_id::seekbuf_len, volume_id::seekbuf_off, volume_id_free_buffer(), xmalloc, and xrealloc.
Referenced by volume_id_probe_all(), volume_id_probe_bcache(), volume_id_probe_btrfs(), volume_id_probe_cramfs(), volume_id_probe_erofs(), volume_id_probe_exfat(), volume_id_probe_ext(), volume_id_probe_f2fs(), volume_id_probe_hfs_hfsplus(), volume_id_probe_highpoint_37x_raid(), volume_id_probe_highpoint_45x_raid(), volume_id_probe_hpfs(), volume_id_probe_intel_software_raid(), volume_id_probe_iso9660(), volume_id_probe_jfs(), volume_id_probe_lfs(), volume_id_probe_linux_raid(), volume_id_probe_linux_swap(), volume_id_probe_lsi_mega_raid(), volume_id_probe_luks(), volume_id_probe_lvm1(), volume_id_probe_lvm2(), volume_id_probe_mac_partition_map(), volume_id_probe_minix(), volume_id_probe_msdos_part_table(), volume_id_probe_nilfs(), volume_id_probe_ntfs(), volume_id_probe_nvidia_raid(), volume_id_probe_ocfs2(), volume_id_probe_promise_fasttrack_raid(), volume_id_probe_reiserfs(), volume_id_probe_romfs(), volume_id_probe_silicon_medley_raid(), volume_id_probe_squashfs(), volume_id_probe_sysv(), volume_id_probe_ubifs(), volume_id_probe_udf(), volume_id_probe_ufs(), volume_id_probe_vfat(), volume_id_probe_via_raid(), and volume_id_probe_xfs().
volume_id_set_label_string()
void volume_id_set_label_string (struct volume_id * id, const uint8_t * buf, size_t count)
Definition at line 115 of file util.c.
 {
     unsigned i;
     memcpy(id->label, buf, count);
     /* remove trailing whitespace */
     i = strnlen(id->label, count);
     while (i--) {
         if (!isspace(id->label[i]))
             break;
     }
     id->label[i+1] = '\0';
 }
References buf, count, i, isspace, volume_id::label, memcpy(), and strnlen().
Referenced by volume_id_probe_bcache(), volume_id_probe_btrfs(), volume_id_probe_cramfs(), volume_id_probe_erofs(), volume_id_probe_ext(), volume_id_probe_hfs_hfsplus(), volume_id_probe_iso9660(), volume_id_probe_jfs(), volume_id_probe_linux_swap(), volume_id_probe_nilfs(), volume_id_probe_ocfs2(), volume_id_probe_reiserfs(), volume_id_probe_romfs(), volume_id_probe_sysv(), volume_id_probe_udf(), volume_id_probe_vfat(), and volume_id_probe_xfs().
volume_id_set_label_unicode16()
void volume_id_set_label_unicode16 (struct volume_id * id, const uint8_t * buf, enum endian endianess, size_t count)
Definition at line 130 of file util.c.
 {
     volume_id_set_unicode16(id->label, sizeof(id->label), buf, endianess, count);
 }
References buf, count, volume_id::label, and volume_id_set_unicode16().
Referenced by volume_id_probe_exfat(), volume_id_probe_f2fs(), volume_id_probe_hfs_hfsplus(), volume_id_probe_ntfs(), and volume_id_probe_udf().
volume_id_set_unicode16()
void volume_id_set_unicode16 (char * str, size_t len, const uint8_t * buf, enum endian endianess, size_t count)
Definition at line 23 of file util.c.
 {
     unsigned i, j;
     unsigned c;
     j = 0;
     for (i = 0; i + 2 <= count; i += 2) {
         if (endianess == LE)
             c = (buf[i+1] << 8) | buf[i];
         else
             c = (buf[i] << 8) | buf[i+1];
         if (c == 0)
             break;
         if (j+1 >= len)
             break;
         if (c < 0x80) {
             /* 0xxxxxxx */
         } else {
             uint8_t topbits = 0xc0;
             if (j+2 >= len)
                 break;
             if (c < 0x800) {
                 /* 110yyyxx 10xxxxxx */
             } else {
                 if (j+3 >= len)
                     break;
                 /* 1110yyyy 10yyyyxx 10xxxxxx */
                 str[j++] = (uint8_t) (0xe0 | (c >> 12));
                 topbits = 0x80;
             }
             str[j++] = (uint8_t) (topbits | ((c >> 6) & 0x3f));
             c = 0x80 | (c & 0x3f);
         }
         str[j++] = (uint8_t) c;
     }
     str[j] = '\0';
 }
References buf, c, count, i, j, LE, and str.
Referenced by volume_id_probe_iso9660(), and volume_id_set_label_unicode16().
volume_id_set_uuid()
void volume_id_set_uuid (struct volume_id * id, const uint8_t * buf, enum uuid_format format)
Definition at line 135 of file util.c.
 {
     unsigned i;
     unsigned count = (format == UUID_DCE_STRING ? VOLUME_ID_UUID_SIZE : 4 << format);
 //  memcpy(id->uuid_raw, buf, count);
 //  id->uuid_raw_len = count;
     /* if set, create string in the same format, the native platform uses */
     for (i = 0; i < count; i++)
         if (buf[i] != 0)
             goto set;
     return; /* all bytes are zero, leave it empty ("") */
 set:
     switch (format) {
     case UUID_DOS:
         sprintf(id->uuid, "%02X%02X-%02X%02X",
             buf[3], buf[2], buf[1], buf[0]);
         break;
     case UUID_NTFS:
         sprintf(id->uuid, "%02X%02X%02X%02X%02X%02X%02X%02X",
             buf[7], buf[6], buf[5], buf[4],
             buf[3], buf[2], buf[1], buf[0]);
         break;
     case UUID_DCE:
         sprintf(id->uuid,
             "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",
             buf[0], buf[1], buf[2], buf[3],
             buf[4], buf[5],
             buf[6], buf[7],
             buf[8], buf[9],
             buf[10], buf[11], buf[12], buf[13], buf[14], buf[15]);
         break;
     case UUID_DCE_STRING:
         memcpy(id->uuid, buf, count);
         id->uuid[count] = '\0';
         break;
     }
 }
References buf, count, format(), i, memcpy(), sprintf(), volume_id::uuid, UUID_DCE, UUID_DCE_STRING, UUID_DOS, UUID_NTFS, and VOLUME_ID_UUID_SIZE.
Referenced by hfs_set_uuid(), volume_id_probe_bcache(), volume_id_probe_btrfs(), volume_id_probe_erofs(), volume_id_probe_exfat(), volume_id_probe_ext(), volume_id_probe_f2fs(), volume_id_probe_jfs(), volume_id_probe_linux_raid(), volume_id_probe_linux_swap(), volume_id_probe_luks(), volume_id_probe_nilfs(), volume_id_probe_ntfs(), volume_id_probe_ocfs2(), volume_id_probe_reiserfs(), volume_id_probe_ubifs(), volume_id_probe_vfat(), and volume_id_probe_xfs().