Fennix: Userspace/apps/base/busybox/e2fsprogs/e2fs_lib.h File Reference
e2fs_lib.h File Reference
#include "bb_e2fs_defs.h"
Macros
#define e2attr_flags_value_chattr (&e2attr_flags_value[1])
#define e2attr_flags_sname_chattr (&e2attr_flags_sname[1])
Functions
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN void print_e2flags_long (unsigned flags)
void print_e2flags (unsigned flags)
Variables
const uint32_t e2attr_flags_value []
const char e2attr_flags_sname []
Macro Definition Documentation
e2attr_flags_sname_chattr
#define e2attr_flags_sname_chattr (&e2attr_flags_sname[1])
Definition at line 28 of file e2fs_lib.h.
e2attr_flags_value_chattr
#define e2attr_flags_value_chattr (&e2attr_flags_value[1])
Definition at line 27 of file e2fs_lib.h.
Function Documentation
print_e2flags()
void print_e2flags (unsigned flags)
Definition at line 96 of file e2fs_lib.c.
 {
     const uint32_t *fv;
     const char *fn;
     fv = e2attr_flags_value;
     fn = e2attr_flags_sname;
     do  {
         char c = '-';
         if (flags & *fv)
             c = *fn;
         putchar(c);
         fv++;
         fn++;
     } while (*fn);
 }
References c, e2attr_flags_sname, e2attr_flags_value, flags, and putchar.
Referenced by list_attributes().
print_e2flags_long()
PUSH_AND_SET_FUNCTION_VISIBILITY_TO_HIDDEN void print_e2flags_long (unsigned flags)
Definition at line 74 of file e2fs_lib.c.
 {
     const uint32_t *fv;
     const char *fn;
     int first = 1;
     fv = e2attr_flags_value;
     fn = e2attr_flags_lname;
     do {
         if (flags & *fv) {
             if (!first)
                 fputs(", ", stdout);
             fputs(fn, stdout);
             first = 0;
         }
         fv++;
         fn += strlen(fn) + 1;
     } while (*fn);
     if (first)
         fputs("---", stdout);
 }
References e2attr_flags_value, first, flags, fputs, stdout, and strlen().
Referenced by list_attributes().
Variable Documentation
e2attr_flags_sname
const char e2attr_flags_sname[] extern
Referenced by print_e2flags().
e2attr_flags_value
const uint32_t e2attr_flags_value[] extern
Referenced by print_e2flags(), and print_e2flags_long().