Fennix: Userspace/mlibc/options/ansi/generic/complex/cargf.c File Reference
cargf.c File Reference
#include <complex.h>
#include <math.h>
Functions
float cargf (float complex z)
Function Documentation
cargf()
float cargf (float complex z)
Definition at line 15 of file cargf.c.
 {
     return atan2f( cimagf(z), crealf(z) );
 }
References atan2f(), cimagf(), and crealf().
Referenced by cpowf().