Fennix Lynx Bootloader: Lynx/FennixLoader/UniversalAsynchronousReceiverTransmitter.cpp File Reference
UniversalAsynchronousReceiverTransmitter.cpp File Reference
#include <uart.hpp>
#include <debug.h>
Namespaces
UniversalAsynchronousReceiverTransmitter
Macros
#define SERIAL_ENABLE_DLAB 0x80
#define SERIAL_RATE_115200_LO 0x01
#define SERIAL_RATE_115200_HI 0x00
#define SERIAL_RATE_57600_LO 0x02
#define SERIAL_RATE_57600_HI 0x00
#define SERIAL_RATE_38400_LO 0x03
#define SERIAL_RATE_38400_HI 0x00
#define SERIAL_BUFFER_EMPTY 0x20
Functions
__always_inline uint8_t inportb (uint16_t Port)
__always_inline void outportb (uint16_t Port, uint8_t Data)
Variables
volatile bool serialports [8] = {false, false, false, false, false, false, false, false}
Macro Definition Documentation
SERIAL_BUFFER_EMPTY
#define SERIAL_BUFFER_EMPTY 0x20
Definition at line 32 of file UniversalAsynchronousReceiverTransmitter.cpp.
SERIAL_ENABLE_DLAB
#define SERIAL_ENABLE_DLAB 0x80
Definition at line 25 of file UniversalAsynchronousReceiverTransmitter.cpp.
SERIAL_RATE_115200_HI
#define SERIAL_RATE_115200_HI 0x00
Definition at line 27 of file UniversalAsynchronousReceiverTransmitter.cpp.
SERIAL_RATE_115200_LO
#define SERIAL_RATE_115200_LO 0x01
Definition at line 26 of file UniversalAsynchronousReceiverTransmitter.cpp.
SERIAL_RATE_38400_HI
#define SERIAL_RATE_38400_HI 0x00
Definition at line 31 of file UniversalAsynchronousReceiverTransmitter.cpp.
SERIAL_RATE_38400_LO
#define SERIAL_RATE_38400_LO 0x03
Definition at line 30 of file UniversalAsynchronousReceiverTransmitter.cpp.
SERIAL_RATE_57600_HI
#define SERIAL_RATE_57600_HI 0x00
Definition at line 29 of file UniversalAsynchronousReceiverTransmitter.cpp.
SERIAL_RATE_57600_LO
#define SERIAL_RATE_57600_LO 0x02
Definition at line 28 of file UniversalAsynchronousReceiverTransmitter.cpp.
Function Documentation
inportb()
__always_inline uint8_t inportb (uint16_t Port) inline
Definition at line 7 of file UniversalAsynchronousReceiverTransmitter.cpp.
 {
     uint8_t Result;
     asm("in %%dx, %%al"
         : "=a"(Result)
         : "d"(Port));
     return Result;
 }
Referenced by UniversalAsynchronousReceiverTransmitter::UART::Read(), UniversalAsynchronousReceiverTransmitter::UART::UART(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
outportb()
__always_inline void outportb (uint16_t Port, uint8_t Data) inline
Definition at line 16 of file UniversalAsynchronousReceiverTransmitter.cpp.
 {
     asmv("out %%al, %%dx"
          :
          : "a"(Data), "d"(Port));
 }
References asmv.
Referenced by UniversalAsynchronousReceiverTransmitter::UART::UART(), and UniversalAsynchronousReceiverTransmitter::UART::Write().
Variable Documentation
serialports
volatile bool serialports[8] = {false, false, false, false, false, false, false, false}
Definition at line 4 of file UniversalAsynchronousReceiverTransmitter.cpp.
Referenced by UniversalAsynchronousReceiverTransmitter::UART::UART().