Fennix Userspace: Userspace/mlibc/options/ansi/generic/environment.cpp File Reference
environment.cpp File Reference
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <bits/ensure.h>
#include <mlibc/allocator.hpp>
#include <mlibc/debug.hpp>
#include <frg/string.hpp>
#include <frg/vector.hpp>
Namespaces
anonymous_namespace{environment.cpp}
mlibc
Functions
size_t anonymous_namespace{environment.cpp}::find_environ_index (frg::string_view name)
frg::vector< char *, MemoryAllocator > & anonymous_namespace{environment.cpp}::get_vector ()
void anonymous_namespace{environment.cpp}::update_vector ()
void anonymous_namespace{environment.cpp}::assign_variable (frg::string_view name, const char *string, bool overwrite)
void anonymous_namespace{environment.cpp}::unassign_variable (frg::string_view name)
char * getenv (const char *name)
int mlibc::putenv (char *string)
Variables
char * anonymous_namespace{environment.cpp}::empty_environment [] = { nullptr }
char ** environ = empty_environment
Function Documentation
getenv()
char* getenv (const char * name)
Definition at line 98 of file environment.cpp.
{
     auto k = find_environ_index(name);
     if(k == size_t(-1))
         return nullptr;
     frg::string_view view{environ[k]};
     size_t s = view.find_first('=');
     __ensure(s != size_t(-1));
     return const_cast<char *>(view.data() + s + 1);
 }
References __ensure, env, environ, anonymous_namespace{environment.cpp}::find_environ_index(), k, name, NULL, strlen(), and strncmp().
Referenced by BuildIWADDirList(), mlibc::envEnabled(), execvpe(), expand_tilde(), getlogin(), anonymous_namespace{getopt-stubs.cpp}::getopt_common(), M_TempFile(), main(), secure_getenv(), and we_askshell().
Variable Documentation
environ
char** environ = empty_environment
Definition at line 16 of file environment.cpp.
Referenced by __mlibc_entry(), anonymous_namespace{environment.cpp}::assign_variable(), execl(), execv(), execvp(), anonymous_namespace{environment.cpp}::find_environ_index(), getenv(), popen(), run_cmd(), system(), anonymous_namespace{environment.cpp}::unassign_variable(), and anonymous_namespace{environment.cpp}::update_vector().