Fennix: liballoc hooks
liballoc hooks
Macros
#define PREFIX(func) kliballoc_##func
#define PREFIX(func) kliballoc_##func
#define PREFIX(func) __##func
Functions
int liballoc_lock ()
int liballoc_unlock ()
void * liballoc_alloc (size_t)
int liballoc_free (void *, size_t)
void *PREFIX() malloc (size_t)
The standard function.
void *PREFIX() realloc (void *, size_t)
The standard function.
void *PREFIX() calloc (size_t, size_t)
The standard function.
void PREFIX() free (void *)
The standard function.
Detailed Description
These are the OS specific functions which need to be implemented on any platform that the library is expected to work on.
Macro Definition Documentation
PREFIX [1/3]
#define PREFIX (func) kliballoc_##func
#include <Kernel/Library/liballoc_1_1.h>
Definition at line 20 of file liballoc_1_1.h.
PREFIX [2/3]
#define PREFIX (func) kliballoc_##func
#include <Lynx/UEFI/src/Memory/liballoc_1_1.h>
Definition at line 36 of file liballoc_1_1.h.
PREFIX [3/3]
#define PREFIX (func) __##func
#include <Userspace/libc/src/mem/liballoc_1_1.h>
Definition at line 20 of file liballoc_1_1.h.
Function Documentation
calloc()
void* PREFIX() calloc (size_t nobj, size_t size)
#include <Kernel/Library/liballoc_1_1.h>
The standard function.
Definition at line 686 of file liballoc_1_1.c.
 {
     int real_size;
     void *p;
     real_size = nobj * size;
     p = PREFIX(malloc)(real_size);
     liballoc_memset(p, 0, real_size);
     return p;
 }
free()
void PREFIX() free (void * ptr)
#include <Kernel/Library/liballoc_1_1.h>
The standard function.
Definition at line 561 of file liballoc_1_1.c.
 {
     struct liballoc_minor *min;
     struct liballoc_major *maj;
     if (ptr == NULL)
     {
         l_warningCount += 1;
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
         printf("liballoc: WARNING: PREFIX(free)( NULL ) called from %lx\n",
                __builtin_return_address(0));
         FLUSH();
 #endif
         return;
     }
     UNALIGN(ptr);
     liballoc_lock(); // lockit
     min = (struct liballoc_minor *)((uintptr_t)ptr - sizeof(struct liballoc_minor));
     if (min->magic != LIBALLOC_MAGIC)
     {
         l_errorCount += 1;
         // Check for overrun errors. For all bytes of LIBALLOC_MAGIC
         if (
             ((min->magic & 0xFFFFFF) == (LIBALLOC_MAGIC & 0xFFFFFF)) ||
             ((min->magic & 0xFFFF) == (LIBALLOC_MAGIC & 0xFFFF)) ||
             ((min->magic & 0xFF) == (LIBALLOC_MAGIC & 0xFF)))
         {
             l_possibleOverruns += 1;
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: Possible 1-3 byte overrun for magic %lx != %lx\n",
                    min->magic,
                    LIBALLOC_MAGIC);
             FLUSH();
 #endif
         }
         if (min->magic == LIBALLOC_DEAD)
         {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: multiple PREFIX(free)() attempt on %lx from %lx.\n",
                    ptr,
                    __builtin_return_address(0));
             FLUSH();
 #endif
         }
         else
         {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: Bad PREFIX(free)( %lx ) called from %lx\n",
                    ptr,
                    __builtin_return_address(0));
             FLUSH();
 #endif
         }
         // being lied to...
         liballoc_unlock(); // release the lock
         return;
     }
 #ifdef LIBALLOCDEBUG
     printf("liballoc: %lx PREFIX(free)( %lx ): ",
            __builtin_return_address(0),
            ptr);
     FLUSH();
 #endif
     maj = min->block;
     l_inuse -= min->size;
     maj->usage -= (min->size + sizeof(struct liballoc_minor));
     min->magic = LIBALLOC_DEAD; // No mojo.
     if (min->next != NULL)
         min->next->prev = min->prev;
     if (min->prev != NULL)
         min->prev->next = min->next;
     if (min->prev == NULL)
         maj->first = min->next;
     // Might empty the block. This was the first
     // minor.
     // We need to clean up after the majors now....
     if (maj->first == NULL) // Block completely unused.
     {
         if (l_memRoot == maj)
             l_memRoot = maj->next;
         if (l_bestBet == maj)
             l_bestBet = NULL;
         if (maj->prev != NULL)
             maj->prev->next = maj->next;
         if (maj->next != NULL)
             maj->next->prev = maj->prev;
         l_allocated -= maj->size;
         liballoc_free(maj, maj->pages);
     }
     else
     {
         if (l_bestBet != NULL)
         {
             int bestSize = l_bestBet->size - l_bestBet->usage;
             int majSize = maj->size - maj->usage;
             if (majSize > bestSize)
                 l_bestBet = maj;
         }
     }
 #ifdef LIBALLOCDEBUG
     printf("OK\n");
     FLUSH();
 #endif
     liballoc_unlock(); // release the lock
 }
liballoc_alloc()
void * liballoc_alloc (size_t Pages)
#include <Kernel/Library/liballoc_1_1.h>
This is the hook into the local system which allocates pages. It accepts an integer parameter which is the number of pages required. The page size was set up in the liballoc_init function.
Returns
NULL if the pages were not allocated.
A pointer to the allocated memory.
Definition at line 9 of file liballocimpl.cpp.
 { return KernelAllocator.RequestPages(Pages); }
References _RequestPages, KernelAllocator, and syscall1().
Referenced by allocate_new_page().
liballoc_free()
int liballoc_free (void * Address, size_t Pages)
#include <Kernel/Library/liballoc_1_1.h>
This frees previously allocated memory. The void* parameter passed to the function is the exact same value returned from a previous liballoc_alloc call.
The integer value is the number of pages to free.
Returns
0 if the memory was successfully freed.
Definition at line 10 of file liballocimpl.cpp.
 {
     KernelAllocator.FreePages(Address, Pages);
     return 0;
 }
References _FreePages, Address, KernelAllocator, and syscall2().
Referenced by free().
liballoc_lock()
int liballoc_lock ()
#include <Kernel/Library/liballoc_1_1.h>
This function is supposed to lock the memory data structures. It could be as simple as disabling interrupts or acquiring a spinlock. It's up to you to decide.
Returns
0 if the lock was acquired successfully. Anything else is failure.
Definition at line 7 of file liballocimpl.cpp.
 { return liballocLock.Lock(__FUNCTION__); }
Referenced by free(), malloc(), and realloc().
liballoc_unlock()
int liballoc_unlock ()
#include <Kernel/Library/liballoc_1_1.h>
This function unlocks what was previously locked by the liballoc_lock function. If it disabled interrupts, it enables interrupts. If it had acquiried a spinlock, it releases the spinlock. etc.
Returns
0 if the lock was successfully released.
Definition at line 8 of file liballocimpl.cpp.
 { return liballocLock.Unlock(); }
Referenced by free(), malloc(), and realloc().
malloc()
void* PREFIX() malloc (size_t req_size)
#include <Kernel/Library/liballoc_1_1.h>
The standard function.
Definition at line 228 of file liballoc_1_1.c.
 {
     int startedBet = 0;
     unsigned long long bestSize = 0;
     void *p = NULL;
     uintptr_t diff;
     struct liballoc_major *maj;
     struct liballoc_minor *min;
     struct liballoc_minor *new_min;
     unsigned long size = req_size;
     // For alignment, we adjust size so there's enough space to align.
     if (ALIGNMENT > 1)
     {
         size += ALIGNMENT + ALIGN_INFO;
     }
     // So, ideally, we really want an alignment of 0 or 1 in order
     // to save space.
     liballoc_lock();
     if (size == 0)
     {
         l_warningCount += 1;
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
         printf("liballoc: WARNING: alloc( 0 ) called from %lx\n",
                __builtin_return_address(0));
         FLUSH();
 #endif
         liballoc_unlock();
         return PREFIX(malloc)(1);
     }
     if (l_memRoot == NULL)
     {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
 #ifdef LIBALLOCDEBUG
         printf("liballoc: initialization of liballoc " VERSION "\n");
 #endif
         atexit(liballoc_dump);
         FLUSH();
 #endif
         // This is the first time we are being used.
         l_memRoot = allocate_new_page(size);
         if (l_memRoot == NULL)
         {
             liballoc_unlock();
 #ifdef LIBALLOCDEBUG
             printf("liballoc: initial l_memRoot initialization failed\n", p);
             FLUSH();
 #endif
             return NULL;
         }
 #ifdef LIBALLOCDEBUG
         printf("liballoc: set up first memory major %lx\n", l_memRoot);
         FLUSH();
 #endif
     }
 #ifdef LIBALLOCDEBUG
     printf("liballoc: %lx PREFIX(malloc)( %i ): ",
            __builtin_return_address(0),
            size);
     FLUSH();
 #endif
     // Now we need to bounce through every major and find enough space....
     maj = l_memRoot;
     startedBet = 0;
     // Start at the best bet....
     if (l_bestBet != NULL)
     {
         bestSize = l_bestBet->size - l_bestBet->usage;
         if (bestSize > (size + sizeof(struct liballoc_minor)))
         {
             maj = l_bestBet;
             startedBet = 1;
         }
     }
     while (maj != NULL)
     {
         diff = maj->size - maj->usage;
         // free memory in the block
         if (bestSize < diff)
         {
             // Hmm.. this one has more memory then our bestBet. Remember!
             l_bestBet = maj;
             bestSize = diff;
         }
 #ifdef USE_CASE1
         // CASE 1:  There is not enough space in this major block.
         if (diff < (size + sizeof(struct liballoc_minor)))
         {
 #ifdef LIBALLOCDEBUG
             printf("CASE 1: Insufficient space in block %lx\n", maj);
             FLUSH();
 #endif
             // Another major block next to this one?
             if (maj->next != NULL)
             {
                 maj = maj->next; // Hop to that one.
                 continue;
             }
             if (startedBet == 1) // If we started at the best bet,
             {                    // let's start all over again.
                 maj = l_memRoot;
                 startedBet = 0;
                 continue;
             }
             // Create a new major block next to this one and...
             maj->next = allocate_new_page(size); // next one will be okay.
             if (maj->next == NULL)
                 break; // no more memory.
             maj->next->prev = maj;
             maj = maj->next;
             // .. fall through to CASE 2 ..
         }
 #endif
 #ifdef USE_CASE2
         // CASE 2: It's a brand new block.
         if (maj->first == NULL)
         {
             maj->first = (struct liballoc_minor *)((uintptr_t)maj + sizeof(struct liballoc_major));
             maj->first->magic = LIBALLOC_MAGIC;
             maj->first->prev = NULL;
             maj->first->next = NULL;
             maj->first->block = maj;
             maj->first->size = size;
             maj->first->req_size = req_size;
             maj->usage += size + sizeof(struct liballoc_minor);
             l_inuse += size;
             p = (void *)((uintptr_t)(maj->first) + sizeof(struct liballoc_minor));
             ALIGN(p);
 #ifdef LIBALLOCDEBUG
             printf("CASE 2: returning %lx\n", p);
             FLUSH();
 #endif
             liballoc_unlock(); // release the lock
             return p;
         }
 #endif
 #ifdef USE_CASE3
         // CASE 3: Block in use and enough space at the start of the block.
         diff = (uintptr_t)(maj->first);
         diff -= (uintptr_t)maj;
         diff -= sizeof(struct liballoc_major);
         if (diff >= (size + sizeof(struct liballoc_minor)))
         {
             // Yes, space in front. Squeeze in.
             maj->first->prev = (struct liballoc_minor *)((uintptr_t)maj + sizeof(struct liballoc_major));
             maj->first->prev->next = maj->first;
             maj->first = maj->first->prev;
             maj->first->magic = LIBALLOC_MAGIC;
             maj->first->prev = NULL;
             maj->first->block = maj;
             maj->first->size = size;
             maj->first->req_size = req_size;
             maj->usage += size + sizeof(struct liballoc_minor);
             l_inuse += size;
             p = (void *)((uintptr_t)(maj->first) + sizeof(struct liballoc_minor));
             ALIGN(p);
 #ifdef LIBALLOCDEBUG
             printf("CASE 3: returning %lx\n", p);
             FLUSH();
 #endif
             liballoc_unlock(); // release the lock
             return p;
         }
 #endif
 #ifdef USE_CASE4
         // CASE 4: There is enough space in this block. But is it contiguous?
         min = maj->first;
         // Looping within the block now...
         while (min != NULL)
         {
             // CASE 4.1: End of minors in a block. Space from last and end?
             if (min->next == NULL)
             {
                 // the rest of this block is free...  is it big enough?
                 diff = (uintptr_t)(maj) + maj->size;
                 diff -= (uintptr_t)min;
                 diff -= sizeof(struct liballoc_minor);
                 diff -= min->size;
                 // minus already existing usage..
                 if (diff >= (size + sizeof(struct liballoc_minor)))
                 {
                     // yay....
                     min->next = (struct liballoc_minor *)((uintptr_t)min + sizeof(struct liballoc_minor) + min->size);
                     min->next->prev = min;
                     min = min->next;
                     min->next = NULL;
                     min->magic = LIBALLOC_MAGIC;
                     min->block = maj;
                     min->size = size;
                     min->req_size = req_size;
                     maj->usage += size + sizeof(struct liballoc_minor);
                     l_inuse += size;
                     p = (void *)((uintptr_t)min + sizeof(struct liballoc_minor));
                     ALIGN(p);
 #ifdef LIBALLOCDEBUG
                     printf("CASE 4.1: returning %lx\n", p);
                     FLUSH();
 #endif
                     liballoc_unlock(); // release the lock
                     return p;
                 }
             }
             // CASE 4.2: Is there space between two minors?
             if (min->next != NULL)
             {
                 // is the difference between here and next big enough?
                 diff = (uintptr_t)(min->next);
                 diff -= (uintptr_t)min;
                 diff -= sizeof(struct liballoc_minor);
                 diff -= min->size;
                 // minus our existing usage.
                 if (diff >= (size + sizeof(struct liballoc_minor)))
                 {
                     // yay......
                     new_min = (struct liballoc_minor *)((uintptr_t)min + sizeof(struct liballoc_minor) + min->size);
                     new_min->magic = LIBALLOC_MAGIC;
                     new_min->next = min->next;
                     new_min->prev = min;
                     new_min->size = size;
                     new_min->req_size = req_size;
                     new_min->block = maj;
                     min->next->prev = new_min;
                     min->next = new_min;
                     maj->usage += size + sizeof(struct liballoc_minor);
                     l_inuse += size;
                     p = (void *)((uintptr_t)new_min + sizeof(struct liballoc_minor));
                     ALIGN(p);
 #ifdef LIBALLOCDEBUG
                     printf("CASE 4.2: returning %lx\n", p);
                     FLUSH();
 #endif
                     liballoc_unlock(); // release the lock
                     return p;
                 }
             } // min->next != NULL
             min = min->next;
         } // while min != NULL ...
 #endif
 #ifdef USE_CASE5
         // CASE 5: Block full! Ensure next block and loop.
         if (maj->next == NULL)
         {
 #ifdef LIBALLOCDEBUG
             printf("CASE 5: block full\n");
             FLUSH();
 #endif
             if (startedBet == 1)
             {
                 maj = l_memRoot;
                 startedBet = 0;
                 continue;
             }
             // we've run out. we need more...
             maj->next = allocate_new_page(size); // next one guaranteed to be okay
             if (maj->next == NULL)
                 break; //  uh oh,  no more memory.....
             maj->next->prev = maj;
         }
 #endif
         maj = maj->next;
     } // while (maj != NULL)
     liballoc_unlock(); // release the lock
 #ifdef LIBALLOCDEBUG
     printf("All cases exhausted. No memory available.\n");
     FLUSH();
 #endif
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
     printf("liballoc: WARNING: PREFIX(malloc)( %i ) returning NULL.\n", size);
     liballoc_dump();
     FLUSH();
 #endif
     return NULL;
 }
realloc()
void* PREFIX() realloc (void * p, size_t size)
#include <Kernel/Library/liballoc_1_1.h>
The standard function.
Definition at line 700 of file liballoc_1_1.c.
 {
     void *ptr;
     struct liballoc_minor *min;
     unsigned int real_size;
     // Honour the case of size == 0 => free old and return NULL
     if (size == 0)
     {
         PREFIX(free)
         (p);
         return NULL;
     }
     // In the case of a NULL pointer, return a simple malloc.
     if (p == NULL)
         return PREFIX(malloc)(size);
     // Unalign the pointer if required.
     ptr = p;
     UNALIGN(ptr);
     liballoc_lock(); // lockit
     min = (struct liballoc_minor *)((uintptr_t)ptr - sizeof(struct liballoc_minor));
     // Ensure it is a valid structure.
     if (min->magic != LIBALLOC_MAGIC)
     {
         l_errorCount += 1;
         // Check for overrun errors. For all bytes of LIBALLOC_MAGIC
         if (
             ((min->magic & 0xFFFFFF) == (LIBALLOC_MAGIC & 0xFFFFFF)) ||
             ((min->magic & 0xFFFF) == (LIBALLOC_MAGIC & 0xFFFF)) ||
             ((min->magic & 0xFF) == (LIBALLOC_MAGIC & 0xFF)))
         {
             l_possibleOverruns += 1;
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: Possible 1-3 byte overrun for magic %lx != %lx\n",
                    min->magic,
                    LIBALLOC_MAGIC);
             FLUSH();
 #endif
         }
         if (min->magic == LIBALLOC_DEAD)
         {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: multiple PREFIX(free)() attempt on %lx from %lx.\n",
                    ptr,
                    __builtin_return_address(0));
             FLUSH();
 #endif
         }
         else
         {
 #if defined LIBALLOCDEBUG || defined LIBALLOCINFO
             printf("liballoc: ERROR: Bad PREFIX(free)( %lx ) called from %lx\n",
                    ptr,
                    __builtin_return_address(0));
             FLUSH();
 #endif
         }
         // being lied to...
         liballoc_unlock(); // release the lock
         return NULL;
     }
     // Definitely a memory block.
     real_size = min->req_size;
     if (real_size >= size)
     {
         min->req_size = size;
         liballoc_unlock();
         return p;
     }
     liballoc_unlock();
     // If we got here then we're reallocating to a block bigger than us.
     ptr = PREFIX(malloc)(size); // We need to allocate new memory
     liballoc_memcpy(ptr, p, real_size);
     PREFIX(free)
     (p);
     return ptr;
 }