Fennix Userspace: Userspace/apps/base/bash/lib/readline/history.h File Reference
history.h File Reference
#include <time.h>
#include <readline/rlstdc.h>
#include <readline/rltypedefs.h>
Data Structures
struct _hist_entry
struct _hist_state
Macros
#define HS_HISTORY_VERSION 0x0802 /* History 8.2 */
#define HISTENT_BYTES(hs) (strlen ((hs)->line) + strlen ((hs)->timestamp))
#define HS_STIFLED 0x01
Typedefs
typedef char * histdata_t
typedef struct _hist_entry HIST_ENTRY
typedef struct _hist_state HISTORY_STATE
Functions
void using_history (void)
HISTORY_STATE * history_get_history_state (void)
void history_set_history_state (HISTORY_STATE *)
void add_history (const char *)
void add_history_time (const char *)
HIST_ENTRY * remove_history (int)
HIST_ENTRY ** remove_history_range (int, int)
HIST_ENTRY * alloc_history_entry (char *, char *)
HIST_ENTRY * copy_history_entry (HIST_ENTRY *)
histdata_t free_history_entry (HIST_ENTRY *)
HIST_ENTRY * replace_history_entry (int, const char *, histdata_t)
void clear_history (void)
void stifle_history (int)
int unstifle_history (void)
int history_is_stifled (void)
HIST_ENTRY ** history_list (void)
int where_history (void)
HIST_ENTRY * current_history (void)
HIST_ENTRY * history_get (int)
time_t history_get_time (HIST_ENTRY *)
int history_total_bytes (void)
int history_set_pos (int)
HIST_ENTRY * previous_history (void)
HIST_ENTRY * next_history (void)
int history_search (const char *, int)
int history_search_prefix (const char *, int)
int history_search_pos (const char *, int, int)
int read_history (const char *)
int read_history_range (const char *, int, int)
int write_history (const char *)
int append_history (int, const char *)
int history_truncate_file (const char *, int)
int history_expand (char *, char **)
char * history_arg_extract (int, int, const char *)
char * get_history_event (const char *, int *, int)
char ** history_tokenize (const char *)
Variables
int history_base
int history_length
int history_max_entries
int history_offset
int history_lines_read_from_file
int history_lines_written_to_file
char history_expansion_char
char history_subst_char
char * history_word_delimiters
char history_comment_char
char * history_no_expand_chars
char * history_search_delimiter_chars
int history_quotes_inhibit_expansion
int history_quoting_state
int history_write_timestamps
int history_multiline_entries
int history_file_version
int max_input_history
rl_linebuf_func_t * history_inhibit_expansion_function
Data Structure Documentation
_hist_entry
struct _hist_entry
Definition at line 51 of file history.h.
Data Fields
histdata_t data
char * line
char * timestamp
_hist_state
struct _hist_state
Definition at line 61 of file history.h.
Data Fields
HIST_ENTRY ** entries
int flags
int length
int offset
int size
Macro Definition Documentation
HISTENT_BYTES
#define HISTENT_BYTES (hs) (strlen ((hs)->line) + strlen ((hs)->timestamp))
Definition at line 58 of file history.h.
HS_HISTORY_VERSION
#define HS_HISTORY_VERSION 0x0802 /* History 8.2 */
Definition at line 47 of file history.h.
HS_STIFLED
#define HS_STIFLED 0x01
Definition at line 70 of file history.h.
Typedef Documentation
HIST_ENTRY
typedef struct _hist_entry HIST_ENTRY
histdata_t
typedef char* histdata_t
Definition at line 42 of file history.h.
HISTORY_STATE
typedef struct _hist_state HISTORY_STATE
Function Documentation
add_history()
void add_history (const char * string)
Definition at line 279 of file history.c.
 {
   HIST_ENTRY *temp;
   int new_length;
   if (history_stifled && (history_length == history_max_entries))
     {
       register int i;
       /* If the history is stifled, and history_length is zero,
      and it equals history_max_entries, we don't save items. */
       if (history_length == 0)
     return;
       /* If there is something in the slot, then remove it. */
       if (the_history[0])
     (void) free_history_entry (the_history[0]);
       /* Copy the rest of the entries, moving down one slot.  Copy includes
      trailing NULL.  */
       memmove (the_history, the_history + 1, history_length * sizeof (HIST_ENTRY *));
       new_length = history_length;
       history_base++;
     }
   else
     {
       if (history_size == 0)
     {
       if (history_stifled && history_max_entries > 0)
         history_size = (history_max_entries > MAX_HISTORY_INITIAL_SIZE)
                 ? MAX_HISTORY_INITIAL_SIZE
                 : history_max_entries + 2;
       else
         history_size = DEFAULT_HISTORY_INITIAL_SIZE;
       the_history = (HIST_ENTRY **)xmalloc (history_size * sizeof (HIST_ENTRY *));
       new_length = 1;
     }
       else
     {
       if (history_length == (history_size - 1))
         {
           history_size += DEFAULT_HISTORY_GROW_SIZE;
           the_history = (HIST_ENTRY **)
         xrealloc (the_history, history_size * sizeof (HIST_ENTRY *));
         }
       new_length = history_length + 1;
     }
     }
   temp = alloc_history_entry ((char *)string, hist_inittime ());
   the_history[new_length] = (HIST_ENTRY *)NULL;
   the_history[new_length - 1] = temp;
   history_length = new_length;
 }
References alloc_history_entry(), DEFAULT_HISTORY_GROW_SIZE, DEFAULT_HISTORY_INITIAL_SIZE, free_history_entry(), hist_inittime(), history_base, history_length, history_max_entries, history_size, history_stifled, i, MAX_HISTORY_INITIAL_SIZE, memmove(), NULL, the_history, xmalloc, and xrealloc.
Referenced by cb_linehandler(), history_expand(), main(), read_history_range(), and rl_gets().
add_history_time()
void add_history_time (const char * string)
Definition at line 338 of file history.c.
 {
   HIST_ENTRY *hs;
   if (string == 0 || history_length < 1)
     return;
   hs = the_history[history_length - 1];
   FREE (hs->timestamp);
   hs->timestamp = savestring (string);
 }
References FREE, history_length, savestring(), the_history, and _hist_entry::timestamp.
Referenced by read_history_range().
alloc_history_entry()
HIST_ENTRY* alloc_history_entry (char * string, char * ts)
Definition at line 227 of file history.c.
 {
   HIST_ENTRY *temp;
   temp = (HIST_ENTRY *)xmalloc (sizeof (HIST_ENTRY));
   temp->line = string ? savestring (string) : string;
   temp->data = (char *)NULL;
   temp->timestamp = ts;
   return temp;
 }
References _hist_entry::data, _hist_entry::line, NULL, savestring(), string, _hist_entry::timestamp, and xmalloc.
Referenced by add_history(), and copy_history_entry().
append_history()
int append_history (int nelements, const char * filename)
Definition at line 821 of file histfile.c.
 {
   return (history_do_write (filename, nelements, HISTORY_APPEND));
 }
References HISTORY_APPEND, and history_do_write().
clear_history()
void clear_history (void)
Definition at line 601 of file history.c.
 {
   register int i;
   /* This loses because we cannot free the data. */
   for (i = 0; i < history_length; i++)
     {
       free_history_entry (the_history[i]);
       the_history[i] = (HIST_ENTRY *)NULL;
     }
   history_offset = history_length = 0;
   history_base = 1;     /* reset history base to default */
 }
References free_history_entry(), history_base, history_length, history_offset, i, NULL, and the_history.
copy_history_entry()
HIST_ENTRY* copy_history_entry (HIST_ENTRY * hist)
Definition at line 366 of file history.c.
 {
   HIST_ENTRY *ret;
   char *ts;
   if (hist == 0)
     return hist;
   ret = alloc_history_entry (hist->line, (char *)NULL);
   ts = hist->timestamp ? savestring (hist->timestamp) : hist->timestamp;
   ret->timestamp = ts;
   ret->data = hist->data;
   return ret;
 }
References alloc_history_entry(), _hist_entry::data, _hist_entry::line, NULL, ret, savestring(), and _hist_entry::timestamp.
current_history()
HIST_ENTRY* current_history (void)
Definition at line 188 of file history.c.
 {
   return ((history_offset == history_length) || the_history == 0)
         ? (HIST_ENTRY *)NULL
         : the_history[history_offset];
 }
References history_length, history_offset, NULL, and the_history.
Referenced by _rl_revert_previous_lines(), get_history_event(), noninc_dosearch(), readline_internal_teardown(), rl_do_undo(), rl_free_line_state(), rl_history_search_internal(), rl_maybe_replace_line(), and rl_redisplay().
free_history_entry()
histdata_t free_history_entry (HIST_ENTRY * hist)
Definition at line 352 of file history.c.
 {
   histdata_t x;
   if (hist == 0)
     return ((histdata_t) 0);
   FREE (hist->line);
   FREE (hist->timestamp);
   x = hist->data;
   xfree (hist);
   return (x);
 }
References _hist_entry::data, FREE, _hist_entry::line, _hist_entry::timestamp, x, and xfree.
Referenced by add_history(), clear_history(), and stifle_history().
get_history_event()
char* get_history_event (const char * string, int * caller_index, int delimiting_quote)
Definition at line 139 of file histexpand.c.
 {
   register int i;
   register char c;
   HIST_ENTRY *entry;
   int which, sign, local_index, substring_okay;
   _hist_search_func_t *search_func;
   char *temp;
   /* The event can be specified in a number of ways.
      !!   the previous command
      !n   command line N
      !-n  current command-line minus N
      !str the most recent command starting with STR
      !?str[?]
       the most recent command containing STR
      All values N are determined via HISTORY_BASE. */
   i = *caller_index;
   if (string[i] != history_expansion_char)
     return ((char *)NULL);
   /* Move on to the specification. */
   i++;
   sign = 1;
   substring_okay = 0;
 #define RETURN_ENTRY(e, w) \
     return ((e = history_get (w)) ? e->line : (char *)NULL)
   /* Handle !! case. */
   if (string[i] == history_expansion_char)
     {
       i++;
       which = history_base + (history_length - 1);
       *caller_index = i;
       RETURN_ENTRY (entry, which);
     }
   /* Hack case of numeric line specification. */
   if (string[i] == '-' && _rl_digit_p (string[i+1]))
     {
       sign = -1;
       i++;
     }
   if (_rl_digit_p (string[i]))
     {
       /* Get the extent of the digits and compute the value. */
       for (which = 0; _rl_digit_p (string[i]); i++)
     which = (which * 10) + _rl_digit_value (string[i]);
       *caller_index = i;
       if (sign < 0)
     which = (history_length + history_base) - which;
       RETURN_ENTRY (entry, which);
     }
   /* This must be something to search for.  If the spec begins with
      a '?', then the string may be anywhere on the line.  Otherwise,
      the string must be found at the start of a line. */
   if (string[i] == '?')
     {
       substring_okay++;
       i++;
     }
   /* Only a closing `?' or a newline delimit a substring search string. */
   for (local_index = i; c = string[i]; i++)
     {
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       int v;
       mbstate_t ps;
       memset (&ps, 0, sizeof (mbstate_t));
       /* These produce warnings because we're passing a const string to a
          function that takes a non-const string. */
       _rl_adjust_point ((char *)string, i, &ps);
       if ((v = _rl_get_char_len ((char *)string + i, &ps)) > 1)
         {
           i += v - 1;
           continue;
         }
         }
 #endif /* HANDLE_MULTIBYTE */
       if ((!substring_okay &&
         (whitespace (c) || c == ':' ||
         (i > local_index && history_event_delimiter_chars && c == '-') ||
         (c != '-' && history_event_delimiter_chars && member (c, history_event_delimiter_chars)) ||
         (history_search_delimiter_chars && member (c, history_search_delimiter_chars)) ||
         string[i] == delimiting_quote)) ||
       string[i] == '\n' ||
       (substring_okay && string[i] == '?'))
     break;
     }
   which = i - local_index;
   temp = (char *)xmalloc (1 + which);
   if (which)
     strncpy (temp, string + local_index, which);
   temp[which] = '\0';
   if (substring_okay && string[i] == '?')
     i++;
   *caller_index = i;
 #define FAIL_SEARCH() \
   do { \
     history_offset = history_length; xfree (temp) ; return (char *)NULL; \
   } while (0)
   /* If there is no search string, try to use the previous search string,
      if one exists.  If not, fail immediately. */
   if (*temp == '\0' && substring_okay)
     {
       if (search_string)
         {
           xfree (temp);
           temp = savestring (search_string);
         }
       else
         FAIL_SEARCH ();
     }
   search_func = substring_okay ? history_search : history_search_prefix;
   while (1)
     {
       local_index = (*search_func) (temp, -1);
       if (local_index < 0)
     FAIL_SEARCH ();
       if (local_index == 0 || substring_okay)
     {
       entry = current_history ();
       if (entry == 0)
         FAIL_SEARCH ();
       history_offset = history_length;
       /* If this was a substring search, then remember the
          string that we matched for word substitution. */
       if (substring_okay)
         {
           FREE (search_string);
           search_string = temp;
           FREE (search_match);
           search_match = history_find_word (entry->line, local_index);
         }
       else
         xfree (temp);
       return (entry->line);
     }
       if (history_offset)
     history_offset--;
       else
     FAIL_SEARCH ();
     }
 #undef FAIL_SEARCH
 #undef RETURN_ENTRY
 }
References _rl_digit_p(), _rl_digit_value(), c, current_history(), FAIL_SEARCH, FREE, history_base, history_event_delimiter_chars, history_expansion_char, history_find_word(), history_length, history_offset, history_search(), history_search_delimiter_chars, history_search_prefix(), i, local_index, MB_CUR_MAX, member, memset(), NULL, RETURN_ENTRY, rl_byte_oriented, savestring(), search_match, search_string, strncpy(), whitespace, xfree, and xmalloc.
Referenced by history_expand_internal().
history_arg_extract()
char* history_arg_extract (int first, int last, const char * string)
Definition at line 1417 of file histexpand.c.
 {
   register int i, len;
   char *result;
   int size, offset;
   char **list;
   /* XXX - think about making history_tokenize return a struct array,
      each struct in array being a string and a length to avoid the
      calls to strlen below. */
   if ((list = history_tokenize (string)) == NULL)
     return ((char *)NULL);
   for (len = 0; list[len]; len++)
     ;
   if (last < 0)
     last = len + last - 1;
   if (first < 0)
     first = len + first - 1;
   if (last == '$')
     last = len - 1;
   if (first == '$')
     first = len - 1;
   last++;
   if (first >= len || last > len || first < 0 || last < 0 || first > last)
     result = ((char *)NULL);
   else
     {
       for (size = 0, i = first; i < last; i++)
     size += strlen (list[i]) + 1;
       result = (char *)xmalloc (size + 1);
       result[0] = '\0';
       for (i = first, offset = 0; i < last; i++)
     {
       strcpy (result + offset, list[i]);
       offset += strlen (list[i]);
       if (i + 1 < last)
         {
               result[offset++] = ' ';
           result[offset] = 0;
         }
     }
     }
   for (i = 0; i < len; i++)
     xfree (list[i]);
   xfree (list);
   return (result);
 }
References first, history_tokenize(), i, NULL, offset, size, strcpy(), strlen(), xfree, and xmalloc.
Referenced by get_history_word_specifier(), and rl_yank_nth_arg_internal().
history_expand()
int history_expand (char * hstring, char ** output)
Definition at line 907 of file histexpand.c.
 {
   register int j;
   int i, r, l, passc, cc, modified, eindex, only_printing, dquote, squote, flag;
   char *string;
   /* The output string, and its length. */
   int result_len;
   char *result;
 #if defined (HANDLE_MULTIBYTE)
   char mb[MB_LEN_MAX];
   mbstate_t ps;
 #endif
   /* Used when adding the string. */
   char *temp;
   if (output == 0)
     return 0;
   /* Setting the history expansion character to 0 inhibits all
      history expansion. */
   if (history_expansion_char == 0)
     {
       *output = savestring (hstring);
       return (0);
     }
   /* Prepare the buffer for printing error messages. */
   result = (char *)xmalloc (result_len = 256);
   result[0] = '\0';
   only_printing = modified = 0;
   l = strlen (hstring);
   /* Grovel the string.  Only backslash and single quotes can quote the
      history escape character.  We also handle arg specifiers. */
   /* Before we grovel forever, see if the history_expansion_char appears
      anywhere within the text. */
   /* The quick substitution character is a history expansion all right.  That
      is to say, "^this^that^" is equivalent to "!!:s^this^that^", and in fact,
      that is the substitution that we do. */
   if (hstring[0] == history_subst_char)
     {
       string = (char *)xmalloc (l + 5);
       string[0] = string[1] = history_expansion_char;
       string[2] = ':';
       string[3] = 's';
       strcpy (string + 4, hstring);
       l += 4;
     }
   else
     {
 #if defined (HANDLE_MULTIBYTE)
       memset (&ps, 0, sizeof (mbstate_t));
 #endif
       string = hstring;
       /* If not quick substitution, still maybe have to do expansion. */
       /* `!' followed by one of the characters in history_no_expand_chars
      is NOT an expansion. */
       dquote = history_quoting_state == '"';
       squote = history_quoting_state == '\'';
       /* If the calling application tells us we are already reading a
      single-quoted string, consume the rest of the string right now
      and then go on. */
       i = 0;
       if (squote && history_quotes_inhibit_expansion)
     {
       hist_string_extract_single_quoted (string, &i, 0);
       squote = 0;
       if (string[i])
         i++;
     }
       for ( ; string[i]; i++)
     {
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
         {
           int v;
           v = _rl_get_char_len (string + i, &ps);
           if (v > 1)
         {
           i += v - 1;
           continue;
         }
         }
 #endif /* HANDLE_MULTIBYTE */
       cc = string[i + 1];
       /* The history_comment_char, if set, appearing at the beginning
          of a word signifies that the rest of the line should not have
          history expansion performed on it.
          Skip the rest of the line and break out of the loop. */
       if (history_comment_char && string[i] == history_comment_char &&
           dquote == 0 &&
           (i == 0 || member (string[i - 1], history_word_delimiters)))
         {
           while (string[i])
         i++;
           break;
         }
       else if (string[i] == history_expansion_char)
         {
           if (cc == 0 || member (cc, history_no_expand_chars))
         continue;
           /* DQUOTE won't be set unless history_quotes_inhibit_expansion
          is set.  The idea here is to treat double-quoted strings the
          same as the word outside double quotes; in effect making the
          double quote part of history_no_expand_chars when DQUOTE is
          set. */
           else if (dquote && cc == '"')
         continue;
           /* If the calling application has set
          history_inhibit_expansion_function to a function that checks
          for special cases that should not be history expanded,
          call the function and skip the expansion if it returns a
          non-zero value. */
           else if (history_inhibit_expansion_function &&
             (*history_inhibit_expansion_function) (string, i))
         continue;
           else
         break;
         }
       /* Shell-like quoting: allow backslashes to quote double quotes
          inside a double-quoted string. */
       else if (dquote && string[i] == '\\' && cc == '"')
         i++;
       /* More shell-like quoting:  if we're paying attention to single
          quotes and letting them quote the history expansion character,
          then we need to pay attention to double quotes, because single
          quotes are not special inside double-quoted strings. */
       else if (history_quotes_inhibit_expansion && string[i] == '"')
         {
           dquote = 1 - dquote;
         }
       else if (dquote == 0 && history_quotes_inhibit_expansion && string[i] == '\'')
         {
           /* If this is bash, single quotes inhibit history expansion. */
           flag = (i > 0 && string[i - 1] == '$');
           i++;
           hist_string_extract_single_quoted (string, &i, flag);
         }
       else if (history_quotes_inhibit_expansion && string[i] == '\\')
         {
           /* If this is bash, allow backslashes to quote single
          quotes and the history expansion character. */
           if (cc == '\'' || cc == history_expansion_char)
         i++;
         }
     }
       if (string[i] != history_expansion_char)
     {
       xfree (result);
       *output = savestring (string);
       return (0);
     }
     }
   /* Extract and perform the substitution. */
   dquote = history_quoting_state == '"';
   squote = history_quoting_state == '\'';
   /* If the calling application tells us we are already reading a
      single-quoted string, consume the rest of the string right now
      and then go on. */
   i = j = 0;
   if (squote && history_quotes_inhibit_expansion)
     {
       int c;
       hist_string_extract_single_quoted (string, &i, 0);
       squote = 0;
       for (c = 0; c < i; c++)
     ADD_CHAR (string[c]);
       if (string[i])
     {
       ADD_CHAR (string[i]);
       i++;
     }
     }
   for (passc = 0; i < l; i++)
     {
       int qc, tchar = string[i];
       if (passc)
     {
       passc = 0;
       ADD_CHAR (tchar);
       continue;
     }
 #if defined (HANDLE_MULTIBYTE)
       if (MB_CUR_MAX > 1 && rl_byte_oriented == 0)
     {
       int k, c;
       c = tchar;
       memset (mb, 0, sizeof (mb));
       for (k = 0; k < MB_LEN_MAX; k++)
         {
           mb[k] = (char)c;
           memset (&ps, 0, sizeof (mbstate_t));
           if (_rl_get_char_len (mb, &ps) == -2)
         c = string[++i];
           else
         break;
         }
       if (strlen (mb) > 1)
         {
           ADD_STRING (mb);
           continue;
         }
     }
 #endif /* HANDLE_MULTIBYTE */
       if (tchar == history_expansion_char)
     tchar = -3;
       else if (tchar == history_comment_char)
     tchar = -2;
       switch (tchar)
     {
     default:
       ADD_CHAR (string[i]);
       break;
     case '\\':
       passc++;
       ADD_CHAR (tchar);
       break;
     case '"':
       dquote = 1 - dquote;
       ADD_CHAR (tchar);
       break;
     case '\'':
       {
         /* If history_quotes_inhibit_expansion is set, single quotes
            inhibit history expansion, otherwise they are treated like
            double quotes. */
         if (squote)
           {
             squote = 0;
             ADD_CHAR (tchar);
           }
         else if (dquote == 0 && history_quotes_inhibit_expansion)
           {
         int quote, slen;
         flag = (i > 0 && string[i - 1] == '$');
         quote = i++;
         hist_string_extract_single_quoted (string, &i, flag);
         slen = i - quote + 2;
         temp = (char *)xmalloc (slen);
         strncpy (temp, string + quote, slen);
         temp[slen - 1] = '\0';
         ADD_STRING (temp);
         xfree (temp);
           }
         else if (dquote == 0 && squote == 0 && history_quotes_inhibit_expansion == 0)
           {
             squote = 1;
             ADD_CHAR (string[i]);
           }
         else
           ADD_CHAR (string[i]);
         break;
       }
     case -2:        /* history_comment_char */
       if ((dquote == 0 || history_quotes_inhibit_expansion == 0) &&
           (i == 0 || member (string[i - 1], history_word_delimiters)))
         {
           temp = (char *)xmalloc (l - i + 1);
           strcpy (temp, string + i);
           ADD_STRING (temp);
           xfree (temp);
           i = l;
         }
       else
         ADD_CHAR (string[i]);
       break;
     case -3:        /* history_expansion_char */
       cc = string[i + 1];
       /* If the history_expansion_char is followed by one of the
          characters in history_no_expand_chars, then it is not a
          candidate for expansion of any kind. */
       if (cc == 0 || member (cc, history_no_expand_chars) ||
              (dquote && cc == '"'))
         {
           ADD_CHAR (string[i]);
           break;
         }
       /* If the application has defined a function to determine whether
          or not a history expansion should be performed, call it here. */
       /* We check against what we've expanded so far, with the current
          expansion appended, because that seems to be what csh does. We
          decide to expand based on what we have to this point, not what
          we started with. */
       if (history_inhibit_expansion_function)
         {
           int save_j, temp;
           save_j = j;
           ADD_CHAR (string[i]);
           ADD_CHAR (cc);
           temp = (*history_inhibit_expansion_function) (result, save_j);
           if (temp)
         {
           result[--j] = '\0';   /* `unadd' cc, leaving ADD_CHAR(string[i]) */
           break;
         }
           else
             result[j = save_j] = '\0';
         }
 #if defined (NO_BANG_HASH_MODIFIERS)
       /* There is something that is listed as a `word specifier' in csh
          documentation which means `the expanded text to this point'.
          That is not a word specifier, it is an event specifier.  If we
          don't want to allow modifiers with `!#', just stick the current
          output line in again. */
       if (cc == '#')
         {
           if (result)
         {
           temp = (char *)xmalloc (1 + strlen (result));
           strcpy (temp, result);
           ADD_STRING (temp);
           xfree (temp);
         }
           i++;
           break;
         }
 #endif
       qc = squote ? '\'' : (dquote ? '"' : 0);
       r = history_expand_internal (string, i, qc, &eindex, &temp, result);
       if (r < 0)
         {
           *output = temp;
           xfree (result);
           if (string != hstring)
         xfree (string);
           return -1;
         }
       else
         {
           if (temp)
         {
           modified++;
           if (*temp)
             ADD_STRING (temp);
           xfree (temp);
         }
           only_printing += r == 1;
           i = eindex;
         }
       break;
     }
     }
   *output = result;
   if (string != hstring)
     xfree (string);
   if (only_printing)
     {
 #if 0
       add_history (result);
 #endif
       return (2);
     }
   return (modified != 0);
 }
References ADD_CHAR, add_history(), ADD_STRING, c, hist_string_extract_single_quoted(), history_comment_char, history_expand_internal(), history_expansion_char, history_inhibit_expansion_function, history_no_expand_chars, history_quotes_inhibit_expansion, history_quoting_state, history_subst_char, history_word_delimiters, i, j, k, MB_CUR_MAX, MB_LEN_MAX, member, memset(), r, rl_byte_oriented, savestring(), strcpy(), string, strlen(), strncpy(), xfree, and xmalloc.
Referenced by main().
history_get()
HIST_ENTRY* history_get (int offset)
Definition at line 216 of file history.c.
 {
   int local_index;
   local_index = offset - history_base;
   return (local_index >= history_length || local_index < 0 || the_history == 0)
         ? (HIST_ENTRY *)NULL
         : the_history[local_index];
 }
References history_base, history_length, local_index, NULL, offset, and the_history.
history_get_history_state()
HISTORY_STATE* history_get_history_state (void)
Definition at line 100 of file history.c.
 {
   HISTORY_STATE *state;
   state = (HISTORY_STATE *)xmalloc (sizeof (HISTORY_STATE));
   state->entries = the_history;
   state->offset = history_offset;
   state->length = history_length;
   state->size = history_size;
   state->flags = 0;
   if (history_stifled)
     state->flags |= HS_STIFLED;
   return (state);
 }
References history_length, history_offset, history_size, history_stifled, HS_STIFLED, state, the_history, and xmalloc.
history_get_time()
time_t history_get_time (HIST_ENTRY * hist)
Definition at line 241 of file history.c.
 {
   char *ts;
   time_t t;
   if (hist == 0 || hist->timestamp == 0)
     return 0;
   ts = hist->timestamp;
   if (ts[0] != history_comment_char)
     return 0;
   errno = 0;
   t = (time_t) strtol (ts + 1, (char **)NULL, 10);      /* XXX - should use strtol() here */
   if (errno == ERANGE)
     return (time_t)0;
   return t;
 }
References ERANGE, errno, history_comment_char, NULL, strtol(), t, and _hist_entry::timestamp.
Referenced by main().
history_is_stifled()
int history_is_stifled (void)
Definition at line 595 of file history.c.
 {
   return (history_stifled);
 }
References history_stifled.
Referenced by _rl_get_string_variable_value().
history_list()
HIST_ENTRY** history_list (void)
Definition at line 180 of file history.c.
 {
   return (the_history);
 }
history_search()
int history_search (const char * string, int direction)
Definition at line 257 of file histsearch.c.
 {
   return (history_search_internal (string, direction, NON_ANCHORED_SEARCH));
 }
References history_search_internal(), and NON_ANCHORED_SEARCH.
Referenced by get_history_event(), history_search_pos(), and noninc_search_from_pos().
history_search_pos()
int history_search_pos (const char * string, int dir, int pos)
Definition at line 273 of file histsearch.c.
 {
   int ret, old;
   old = where_history ();
   history_set_pos (pos);
   if (history_search (string, dir) == -1)
     {
       history_set_pos (old);
       return (-1);
     }
   ret = where_history ();
   history_set_pos (old);
   return ret;
 }
References history_search(), history_set_pos(), pos, ret, and where_history().
history_search_prefix()
int history_search_prefix (const char * string, int direction)
Definition at line 264 of file histsearch.c.
 {
   return (history_search_internal (string, direction, ANCHORED_SEARCH));
 }
References ANCHORED_SEARCH, and history_search_internal().
Referenced by get_history_event(), and noninc_search_from_pos().
history_set_history_state()
void history_set_history_state (HISTORY_STATE * state)
Definition at line 118 of file history.c.
 {
   the_history = state->entries;
   history_offset = state->offset;
   history_length = state->length;
   history_size = state->size;
   if (state->flags & HS_STIFLED)
     history_stifled = 1;
 }
References history_length, history_offset, history_size, history_stifled, HS_STIFLED, state, and the_history.
history_set_pos()
int history_set_pos (int pos)
Definition at line 161 of file history.c.
 {
   if (pos > history_length || pos < 0 || !the_history)
     return (0);
   history_offset = pos;
   return (1);
 }
References history_length, history_offset, pos, and the_history.
Referenced by _rl_revert_all_lines(), _rl_revert_previous_lines(), history_search_pos(), noninc_dosearch(), noninc_search_from_pos(), rl_history_search_internal(), and rl_yank_nth_arg_internal().
history_tokenize()
char** history_tokenize (const char * string)
Definition at line 1680 of file histexpand.c.
 {
   return (history_tokenize_internal (string, -1, (int *)NULL));
 }
References history_tokenize_internal(), and NULL.
Referenced by history_arg_extract().
history_total_bytes()
int history_total_bytes (void)
Definition at line 140 of file history.c.
 {
   register int i, result;
   for (i = result = 0; the_history && the_history[i]; i++)
     result += HISTENT_BYTES (the_history[i]);
   return (result);
 }
References HISTENT_BYTES, i, and the_history.
history_truncate_file()
int history_truncate_file (const char * fname, int lines)
Definition at line 518 of file histfile.c.
 {
   char *buffer, *filename, *tempname, *bp, *bp1;        /* bp1 == bp+1 */
   int file, chars_read, rv, orig_lines, exists, r;
   struct stat finfo, nfinfo;
   size_t file_size;
   history_lines_written_to_file = 0;
   buffer = (char *)NULL;
   filename = history_filename (fname);
   tempname = 0;
   file = filename ? open (filename, O_RDONLY|O_BINARY, 0666) : -1;
   rv = exists = 0;
   /* Don't try to truncate non-regular files. */
   if (file == -1 || fstat (file, &finfo) == -1)
     {
       rv = errno;
       if (file != -1)
     close (file);
       goto truncate_exit;
     }
   exists = 1;
   nfinfo.st_uid = finfo.st_uid;
   nfinfo.st_gid = finfo.st_gid;
   if (S_ISREG (finfo.st_mode) == 0)
     {
       close (file);
 #ifdef EFTYPE
       rv = EFTYPE;
 #else
       rv = EINVAL;
 #endif
       goto truncate_exit;
     }
   file_size = (size_t)finfo.st_size;
   /* check for overflow on very large files */
   if (file_size != finfo.st_size || file_size + 1 < file_size)
     {
       close (file);
 #if defined (EFBIG)
       rv = errno = EFBIG;
 #elif defined (EOVERFLOW)
       rv = errno = EOVERFLOW;
 #else
       rv = errno = EINVAL;
 #endif
       goto truncate_exit;
     }
   buffer = (char *)malloc (file_size + 1);
   if (buffer == 0)
     {
       rv = errno;
       close (file);
       goto truncate_exit;
     }
   chars_read = read (file, buffer, file_size);
   close (file);
   if (chars_read <= 0)
     {
       rv = (chars_read < 0) ? errno : 0;
       goto truncate_exit;
     }
   orig_lines = lines;
   /* Count backwards from the end of buffer until we have passed
      LINES lines.  bp1 is set funny initially.  But since bp[1] can't
      be a comment character (since it's off the end) and *bp can't be
      both a newline and the history comment character, it should be OK. */
   for (bp1 = bp = buffer + chars_read - 1; lines && bp > buffer; bp--)
     {
       if (*bp == '\n' && HIST_TIMESTAMP_START(bp1) == 0)
     lines--;
       bp1 = bp;
     }
   /* If this is the first line, then the file contains exactly the
      number of lines we want to truncate to, so we don't need to do
      anything.  It's the first line if we don't find a newline between
      the current value of i and 0.  Otherwise, write from the start of
      this line until the end of the buffer. */
   for ( ; bp > buffer; bp--)
     {
       if (*bp == '\n' && HIST_TIMESTAMP_START(bp1) == 0)
         {
       bp++;
       break;
         }
       bp1 = bp;
     }
   /* Write only if there are more lines in the file than we want to
      truncate to. */
   if (bp <= buffer)
     {
       rv = 0;
       /* No-op if LINES == 0 at this point */
       history_lines_written_to_file = orig_lines - lines;
       goto truncate_exit;
     }
   tempname = history_tempfile (filename);
   if ((file = open (tempname, O_WRONLY|O_CREAT|O_TRUNC|O_BINARY, 0600)) != -1)
     {
       if (write (file, bp, chars_read - (bp - buffer)) < 0)
     rv = errno;
       if (fstat (file, &nfinfo) < 0 && rv == 0)
     rv = errno;
       if (close (file) < 0 && rv == 0)
     rv = errno;
     }
   else
     rv = errno;
  truncate_exit:
   FREE (buffer);
   history_lines_written_to_file = orig_lines - lines;
   if (rv == 0 && filename && tempname)
     rv = histfile_restore (tempname, filename);
   if (rv != 0)
     {
       rv = errno;
       if (tempname)
     unlink (tempname);
       history_lines_written_to_file = 0;
     }
 #if defined (HAVE_CHOWN)
   /* Make sure the new filename is owned by the same user as the old.  If one
      user is running this, it's a no-op.  If the shell is running after sudo
      with a shared history file, we don't want to leave the history file
      owned by root. */
   if (rv == 0 && exists && SHOULD_CHOWN (finfo, nfinfo))
     r = chown (filename, finfo.st_uid, finfo.st_gid);
 #endif
   xfree (filename);
   FREE (tempname);
   return rv;
 }
References bp, buffer, chown(), close(), EFBIG, EFTYPE, EINVAL, EOVERFLOW, errno, fname, FREE, fstat(), HIST_TIMESTAMP_START, histfile_restore(), history_filename(), history_lines_written_to_file, history_tempfile(), if(), lines, malloc, NULL, O_BINARY, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY, open(), r, read(), S_ISREG, SHOULD_CHOWN, stat::st_gid, stat::st_mode, stat::st_size, stat::st_uid, unlink(), write(), and xfree.
next_history()
HIST_ENTRY* next_history (void)
Definition at line 208 of file history.c.
 {
   return (history_offset == history_length) ? (HIST_ENTRY *)NULL : the_history[++history_offset];
 }
References history_length, history_offset, NULL, and the_history.
Referenced by rl_get_next_history().
previous_history()
HIST_ENTRY* previous_history (void)
Definition at line 199 of file history.c.
 {
   return history_offset ? the_history[--history_offset] : (HIST_ENTRY *)NULL;
 }
References history_offset, NULL, and the_history.
Referenced by _rl_revert_previous_lines(), rl_get_previous_history(), and rl_yank_nth_arg_internal().
read_history()
int read_history (const char * filename)
Definition at line 257 of file histfile.c.
 {
   return (read_history_range (filename, 0, -1));
 }
References read_history_range().
Referenced by main().
read_history_range()
int read_history_range (const char * filename, int from, int to)
Definition at line 268 of file histfile.c.
 {
   register char *line_start, *line_end, *p;
   char *input, *buffer, *bufend, *last_ts;
   int file, current_line, chars_read, has_timestamps, reset_comment_char;
   struct stat finfo;
   size_t file_size;
 #if defined (EFBIG)
   int overflow_errno = EFBIG;
 #elif defined (EOVERFLOW)
   int overflow_errno = EOVERFLOW;
 #else
   int overflow_errno = EIO;
 #endif
   history_lines_read_from_file = 0;
   buffer = last_ts = (char *)NULL;
   input = history_filename (filename);
   file = input ? open (input, O_RDONLY|O_BINARY, 0666) : -1;
   if ((file < 0) || (fstat (file, &finfo) == -1))
     goto error_and_exit;
   if (S_ISREG (finfo.st_mode) == 0)
     {
 #ifdef EFTYPE
       errno = EFTYPE;
 #else
       errno = EINVAL;
 #endif
       goto error_and_exit;
     }
   file_size = (size_t)finfo.st_size;
   /* check for overflow on very large files */
   if (file_size != finfo.st_size || file_size + 1 < file_size)
     {
       errno = overflow_errno;
       goto error_and_exit;
     }
   if (file_size == 0)
     {
       xfree (input);
       close (file);
       return 0; /* don't waste time if we don't have to */
     }
 #ifdef HISTORY_USE_MMAP
   /* We map read/write and private so we can change newlines to NULs without
      affecting the underlying object. */
   buffer = (char *)mmap (0, file_size, PROT_READ|PROT_WRITE, MAP_RFLAGS, file, 0);
   if ((void *)buffer == MAP_FAILED)
     {
       errno = overflow_errno;
       goto error_and_exit;
     }
   chars_read = file_size;
 #else
   buffer = (char *)malloc (file_size + 1);
   if (buffer == 0)
     {
       errno = overflow_errno;
       goto error_and_exit;
     }
   chars_read = read (file, buffer, file_size);
 #endif
   if (chars_read < 0)
     {
   error_and_exit:
       if (errno != 0)
     chars_read = errno;
       else
     chars_read = EIO;
       if (file >= 0)
     close (file);
       FREE (input);
 #ifndef HISTORY_USE_MMAP
       FREE (buffer);
 #endif
       return (chars_read);
     }
   close (file);
   /* Set TO to larger than end of file if negative. */
   if (to < 0)
     to = chars_read;
   /* Start at beginning of file, work to end. */
   bufend = buffer + chars_read;
   *bufend = '\0';       /* null-terminate buffer for timestamp checks */
   current_line = 0;
   /* Heuristic: the history comment character rarely changes, so assume we
      have timestamps if the buffer starts with `#[:digit:]' and temporarily
      set history_comment_char so timestamp parsing works right */
   reset_comment_char = 0;
   if (history_comment_char == '\0' && buffer[0] == '#' && isdigit ((unsigned char)buffer[1]))
     {
       history_comment_char = '#';
       reset_comment_char = 1;
     }
   has_timestamps = HIST_TIMESTAMP_START (buffer);
   history_multiline_entries += has_timestamps && history_write_timestamps;
   /* Skip lines until we are at FROM. */
   if (has_timestamps)
     last_ts = buffer;
   for (line_start = line_end = buffer; line_end < bufend && current_line < from; line_end++)
     if (*line_end == '\n')
       {
         p = line_end + 1;
         /* If we see something we think is a timestamp, continue with this
        line.  We should check more extensively here... */
     if (HIST_TIMESTAMP_START(p) == 0)
       current_line++;
     else
       last_ts = p;
     line_start = p;
     /* If we are at the last line (current_line == from) but we have
        timestamps (has_timestamps), then line_start points to the
        text of the last command, and we need to skip to its end. */
     if (current_line >= from && has_timestamps)
       {
         for (line_end = p; line_end < bufend && *line_end != '\n'; line_end++)
           ;
         line_start = (*line_end == '\n') ? line_end + 1 : line_end;
       }
       }
   /* If there are lines left to gobble, then gobble them now. */
   for (line_end = line_start; line_end < bufend; line_end++)
     if (*line_end == '\n')
       {
     /* Change to allow Windows-like \r\n end of line delimiter. */
     if (line_end > line_start && line_end[-1] == '\r')
       line_end[-1] = '\0';
     else
       *line_end = '\0';
     if (*line_start)
       {
         if (HIST_TIMESTAMP_START(line_start) == 0)
           {
             if (last_ts == NULL && history_length > 0 && history_multiline_entries)
           _hs_append_history_line (history_length - 1, line_start);
         else
           add_history (line_start);
         if (last_ts)
           {
             add_history_time (last_ts);
             last_ts = NULL;
           }
           }
         else
           {
         last_ts = line_start;
         current_line--;
           }
       }
     current_line++;
     if (current_line >= to)
       break;
     line_start = line_end + 1;
       }
   history_lines_read_from_file = current_line;
   if (reset_comment_char)
     history_comment_char = '\0';
   FREE (input);
 #ifndef HISTORY_USE_MMAP
   FREE (buffer);
 #else
   munmap (buffer, file_size);
 #endif
   return (0);
 }
References _hs_append_history_line(), add_history(), add_history_time(), buffer, close(), EFBIG, EFTYPE, EINVAL, EIO, EOVERFLOW, errno, FREE, fstat(), HIST_TIMESTAMP_START, history_comment_char, history_filename(), history_length, history_lines_read_from_file, history_multiline_entries, history_write_timestamps, if(), isdigit, malloc, MAP_FAILED, mmap, munmap(), NULL, O_BINARY, O_RDONLY, open(), p, PROT_READ, PROT_WRITE, read(), S_ISREG, stat::st_mode, stat::st_size, and xfree.
Referenced by read_history().
remove_history()
HIST_ENTRY* remove_history (int which)
Definition at line 486 of file history.c.
 {
   HIST_ENTRY *return_value;
   register int i;
 #if 1
   int nentries;
   HIST_ENTRY **start, **end;
 #endif
   if (which < 0 || which >= history_length || history_length ==  0 || the_history == 0)
     return ((HIST_ENTRY *)NULL);
   return_value = the_history[which];
 #if 1
   /* Copy the rest of the entries, moving down one slot.  Copy includes
      trailing NULL.  */
   nentries = history_length - which;
   start = the_history + which;
   end = start + 1;
   memmove (start, end, nentries * sizeof (HIST_ENTRY *));
 #else
   for (i = which; i < history_length; i++)
     the_history[i] = the_history[i + 1];
 #endif
   history_length--;
   return (return_value);
 }
References history_length, i, memmove(), NULL, start(), and the_history.
Referenced by main().
remove_history_range()
HIST_ENTRY** remove_history_range (int first, int last)
Definition at line 518 of file history.c.
 {
   HIST_ENTRY **return_value;
   register int i;
   int nentries;
   HIST_ENTRY **start, **end;
   if (the_history == 0 || history_length == 0)
     return ((HIST_ENTRY **)NULL);
   if (first < 0 || first >= history_length || last < 0 || last >= history_length)
     return ((HIST_ENTRY **)NULL);
   if (first > last)
     return (HIST_ENTRY **)NULL;
   nentries = last - first + 1;
   return_value = (HIST_ENTRY **)malloc ((nentries + 1) * sizeof (HIST_ENTRY *));
   if (return_value == 0)
     return return_value;
   /* Return all the deleted entries in a list */
   for (i = first ; i <= last; i++)
     return_value[i - first] = the_history[i];
   return_value[i - first] = (HIST_ENTRY *)NULL;
   /* Copy the rest of the entries, moving down NENTRIES slots.  Copy includes
      trailing NULL.  */
   start = the_history + first;
   end = the_history + last + 1;
   memmove (start, end, (history_length - last) * sizeof (HIST_ENTRY *));
   history_length -= nentries;
   return (return_value);
 }
References first, history_length, i, malloc, memmove(), NULL, start(), and the_history.
replace_history_entry()
HIST_ENTRY* replace_history_entry (int which, const char * line, histdata_t data)
Definition at line 388 of file history.c.
 {
   HIST_ENTRY *temp, *old_value;
   if (which < 0 || which >= history_length)
     return ((HIST_ENTRY *)NULL);
   temp = (HIST_ENTRY *)xmalloc (sizeof (HIST_ENTRY));
   old_value = the_history[which];
   temp->line = savestring (line);
   temp->data = data;
   temp->timestamp = old_value->timestamp ? savestring (old_value->timestamp) : 0;
   the_history[which] = temp;
   return (old_value);
 }
References _hist_entry::data, history_length, _hist_entry::line, line, NULL, savestring(), the_history, _hist_entry::timestamp, and xmalloc.
Referenced by readline_internal_teardown(), rl_do_undo(), and rl_maybe_replace_line().
stifle_history()
void stifle_history (int max)
Definition at line 555 of file history.c.
 {
   register int i, j;
   if (max < 0)
     max = 0;
   if (history_length > max)
     {
       /* This loses because we cannot free the data. */
       for (i = 0, j = history_length - max; i < j; i++)
     free_history_entry (the_history[i]);
       history_base = i;
       for (j = 0, i = history_length - max; j < max; i++, j++)
     the_history[j] = the_history[i];
       the_history[j] = (HIST_ENTRY *)NULL;
       history_length = j;
     }
   history_stifled = 1;
   max_input_history = history_max_entries = max;
 }
References free_history_entry(), history_base, history_length, history_max_entries, history_stifled, i, j, max, max_input_history, NULL, and the_history.
Referenced by sv_histsize().
unstifle_history()
int unstifle_history (void)
Definition at line 583 of file history.c.
 {
   if (history_stifled)
     {
       history_stifled = 0;
       return (history_max_entries);
     }
   else
     return (-history_max_entries);
 }
References history_max_entries, and history_stifled.
Referenced by sv_histsize().
using_history()
void using_history (void)
Definition at line 131 of file history.c.
 {
   history_offset = history_length;
 }
References history_length, and history_offset.
Referenced by _rl_revert_all_lines(), _rl_start_using_history(), main(), and rl_end_of_history().
where_history()
int where_history (void)
Definition at line 153 of file history.c.
 {
   return (history_offset);
 }
References history_offset.
Referenced by _rl_revert_all_lines(), _rl_revert_previous_lines(), _rl_scxt_alloc(), history_search_pos(), noninc_dosearch(), noninc_search_from_pos(), readline_internal_teardown(), rl_beginning_of_history(), rl_do_undo(), rl_fetch_history(), rl_history_search_internal(), rl_history_search_reinit(), rl_maybe_replace_line(), rl_operate_and_get_next(), rl_yank_nth_arg_internal(), and set_saved_history().
write_history()
int write_history (const char * filename)
Definition at line 830 of file histfile.c.
 {
   return (history_do_write (filename, history_length, HISTORY_OVERWRITE));
 }
References history_do_write(), history_length, and HISTORY_OVERWRITE.
Referenced by main().
Variable Documentation
history_base
int history_base extern
Definition at line 96 of file history.c.
Referenced by add_history(), clear_history(), get_history_event(), history_get(), main(), rl_display_search(), rl_fetch_history(), rl_operate_and_get_next(), set_saved_history(), and stifle_history().
history_comment_char
char history_comment_char extern
Definition at line 95 of file histexpand.c.
Referenced by hist_inittime(), history_expand(), history_get_time(), history_tokenize_internal(), and read_history_range().
history_expansion_char
char history_expansion_char extern
Definition at line 85 of file histexpand.c.
Referenced by get_history_event(), history_expand(), and history_expand_internal().
history_file_version
int history_file_version extern
Definition at line 118 of file histfile.c.
history_inhibit_expansion_function
rl_linebuf_func_t* history_inhibit_expansion_function extern
Definition at line 110 of file histexpand.c.
Referenced by history_expand().
history_length
int history_length extern
Definition at line 93 of file history.c.
Referenced by _hs_at_end_of_history(), _hs_replace_history_data(), _rl_revert_previous_lines(), add_history(), add_history_time(), clear_history(), current_history(), get_history_event(), history_do_write(), history_get(), history_get_history_state(), history_search_internal(), history_set_history_state(), history_set_pos(), next_history(), read_history_range(), remove_history(), remove_history_range(), replace_history_entry(), rl_clear_history(), stifle_history(), using_history(), and write_history().
history_lines_read_from_file
int history_lines_read_from_file extern
Definition at line 131 of file histfile.c.
Referenced by read_history_range().
history_lines_written_to_file
int history_lines_written_to_file extern
Definition at line 136 of file histfile.c.
Referenced by history_do_write(), and history_truncate_file().
history_max_entries
int history_max_entries extern
Definition at line 85 of file history.c.
Referenced by _rl_get_string_variable_value(), add_history(), stifle_history(), and unstifle_history().
history_multiline_entries
int history_multiline_entries extern
Definition at line 126 of file histfile.c.
Referenced by read_history_range().
history_no_expand_chars
char* history_no_expand_chars extern
Definition at line 99 of file histexpand.c.
Referenced by history_expand().
history_offset
int history_offset extern
Definition at line 90 of file history.c.
Referenced by _hs_at_end_of_history(), clear_history(), current_history(), get_history_event(), history_get_history_state(), history_search_internal(), history_set_history_state(), history_set_pos(), next_history(), previous_history(), rl_clear_history(), using_history(), and where_history().
history_quotes_inhibit_expansion
int history_quotes_inhibit_expansion extern
Definition at line 103 of file histexpand.c.
Referenced by history_expand().
history_quoting_state
int history_quoting_state extern
Definition at line 112 of file histexpand.c.
Referenced by history_expand(), and shell_getc().
history_search_delimiter_chars
char* history_search_delimiter_chars extern
Definition at line 52 of file histsearch.c.
Referenced by get_history_event().
history_subst_char
char history_subst_char extern
Definition at line 89 of file histexpand.c.
Referenced by history_expand().
history_word_delimiters
char* history_word_delimiters extern
Definition at line 106 of file histexpand.c.
Referenced by history_expand(), history_tokenize_internal(), and history_tokenize_word().
history_write_timestamps
int history_write_timestamps extern
Definition at line 121 of file histfile.c.
Referenced by history_do_write(), and read_history_range().
max_input_history
int max_input_history extern
Definition at line 86 of file history.c.
Referenced by stifle_history().