Fennix: Userspace/libs/include/sysbase.h File Reference
sysbase.h File Reference
#include <stddef.h>
Enumerations
enum KCtl {
KCTL_NULL , KCTL_GET_PID , KCTL_GET_TID , KCTL_GET_UID ,
KCTL_GET_GID , KCTL_GET_PAGE_SIZE , KCTL_NULL , KCTL_GET_PID ,
KCTL_GET_TID , KCTL_GET_UID , KCTL_GET_GID , KCTL_GET_PAGE_SIZE
}
Functions
long DoCtl (uint64_t Command, uint64_t Arg1, uint64_t Arg2, uint64_t Arg3, uint64_t Arg4)
uintptr_t KrnlRequestPages (size_t Count)
void KrnlFreePages (uintptr_t Address, size_t Count)
Enumeration Type Documentation
KCtl
enum KCtl
Enumerator
KCTL_NULL
KCTL_GET_PID
KCTL_GET_TID
KCTL_GET_UID
KCTL_GET_GID
KCTL_GET_PAGE_SIZE
KCTL_NULL
KCTL_GET_PID
KCTL_GET_TID
KCTL_GET_UID
KCTL_GET_GID
KCTL_GET_PAGE_SIZE
Definition at line 6 of file sysbase.h.
 {
     KCTL_NULL,
     KCTL_GET_PID,
     KCTL_GET_TID,
     KCTL_GET_UID,
     KCTL_GET_GID,
     KCTL_GET_PAGE_SIZE,
 };
Function Documentation
DoCtl()
long DoCtl (uint64_t Command, uint64_t Arg1, uint64_t Arg2, uint64_t Arg3, uint64_t Arg4)
Definition at line 5 of file Base.c.
 {
     return syscall5(_KernelCTL, Command, Arg1, Arg2, Arg3, Arg4);
 }
References _KernelCTL, Command, and syscall5().
Referenced by __FILE_GetPageSize().
KrnlFreePages()
void KrnlFreePages (uintptr_t Address, size_t Count)
Definition at line 15 of file Base.c.
 {
     syscall2(_FreePages, Address, Count);
 }
References _FreePages, Address, and syscall2().
Referenced by FileClose().
KrnlRequestPages()
uintptr_t KrnlRequestPages (size_t Count)
Definition at line 10 of file Base.c.
 {
     return syscall1(_RequestPages, Count);
 }
References _RequestPages, and syscall1().
Referenced by FileOpen().