Fennix Kernel: CPU::x86::AMD::CPUID0x00000001 Struct Reference
CPU::x86::AMD::CPUID0x00000001 Struct Reference
Additional CPU information.
#include <cpuid_amd.hpp>
Public Member Functions
__always_inline void Get ()
Data Fields
union {
struct {
uint32_t Stepping: 4
uint32_t BaseModel: 4
uint32_t BaseFamily: 4
uint32_t Reserved0: 4
uint32_t ExtModel: 4
uint32_t ExtFamily: 8
uint32_t Reserved1: 4
}
cpuid_t raw
} EAX
Family, Model, Stepping Identifiers.
union {
struct {
uint32_t BrandId: 8
uint32_t CLFlush: 8
uint32_t LogicalProcessorCount: 8
uint32_t LocalApicId: 8
}
cpuid_t raw
} EBX
LocalApicId, LogicalProcessorCount, CLFlush.
union {
struct {
uint32_t SSE3: 1
uint32_t PCLMULQDQ: 1
uint32_t Reserved0: 1
uint32_t MONITOR: 1
uint32_t Reserved1: 5
uint32_t SSSE3: 1
uint32_t Reserved2: 2
uint32_t FMA: 1
uint32_t CMPXCHG16B: 1
uint32_t Reserved3: 5
uint32_t SSE41: 1
uint32_t SSE42: 1
uint32_t x2APIC: 1
uint32_t MOVBE: 1
uint32_t POPCNT: 1
uint32_t Reserved4: 1
uint32_t AES: 1
uint32_t XSAVE: 1
uint32_t OSXSAVE: 1
uint32_t AVX: 1
uint32_t F16C: 1
uint32_t RDRAND: 1
uint32_t Hypervisor: 1
Reserved for use by hypervisor to indicate guest status.
}
cpuid_t raw
} ECX
Feature Identifiers.
union {
struct {
uint32_t FPU: 1
uint32_t VME: 1
uint32_t DE: 1
uint32_t PSE: 1
uint32_t TSC: 1
uint32_t MSR: 1
uint32_t PAE: 1
uint32_t MCE: 1
uint32_t CMPXCHG8B: 1
uint32_t APIC: 1
uint32_t Reserved0: 1
uint32_t SysEnterSysExit: 1
uint32_t MTRR: 1
uint32_t PGE: 1
uint32_t MCA: 1
uint32_t CMOV: 1
uint32_t PAT: 1
uint32_t PSE36: 1
uint32_t Reserved1: 1
uint32_t CLFSH: 1
uint32_t Reserved2: 3
uint32_t MMX: 1
uint32_t FXSR: 1
uint32_t SSE: 1
uint32_t SSE2: 1
uint32_t Reserved3: 1
uint32_t HTT: 1
uint32_t Reserved4: 3
}
cpuid_t raw
} EDX
Feature Identifiers.
Detailed Description
Additional CPU information.
Definition at line 92 of file cpuid_amd.hpp.
Member Function Documentation
Get()
__always_inline void CPU::x86::AMD::CPUID0x00000001::Get () inline
Definition at line 94 of file cpuid_amd.hpp.
                 {
 #if defined(a86)
                     asmv("cpuid"
                          : "=a"(EAX.raw), "=b"(EBX.raw), "=c"(ECX.raw), "=d"(EDX.raw)
                          : "a"(0x1));
 #endif // a64 || a32
                 }
References asmv(), EAX, EBX, ECX, and EDX.
Referenced by DetectByCPUID(), and CPU::InitializeFeatures().
Field Documentation
union { ... } CPU::x86::AMD::CPUID0x00000001::EAX
Family, Model, Stepping Identifiers.
Referenced by Get().
union { ... } CPU::x86::AMD::CPUID0x00000001::EBX
LocalApicId, LogicalProcessorCount, CLFlush.
Referenced by Get().
union { ... } CPU::x86::AMD::CPUID0x00000001::ECX
Feature Identifiers.
Referenced by DetectByCPUID(), and Get().
union { ... } CPU::x86::AMD::CPUID0x00000001::EDX
Feature Identifiers.
Referenced by Get(), and CPU::InitializeFeatures().
The documentation for this struct was generated from the following file:
Kernel/include/cpu/x86/cpuid_amd.hpp