Fennix Kernel: PCI::Manager Class Reference
PCI::Manager Class Reference
#include <pci.hpp>
Public Member Functions
std::list< PCIDevice > GetDevices ()
void MapPCIAddresses (PCIDevice Device, Memory::PageTable *Table)
void EnumerateFunction (uint64_t DeviceAddress, uint32_t Function, PCIDevice dev)
void EnumerateDevice (uint64_t BusAddress, uint32_t Device, PCIDevice dev)
void EnumerateBus (uint64_t BaseAddress, uint32_t Bus, PCIDevice dev)
std::list< PCIDevice > FindPCIDevice (uint8_t Class, uint8_t Subclass, uint8_t ProgIF)
std::list< PCIDevice > FindPCIDevice (uint16_t VendorID, uint16_t DeviceID)
std::list< PCIDevice > FindPCIDevice (std::list< uint16_t > VendorIDs, std::list< uint16_t > DeviceIDs)
Manager ()
~Manager ()
Private Attributes
std::list< PCIDevice > Devices
Detailed Description
Definition at line 227 of file pci.hpp.
Constructor & Destructor Documentation
Manager()
PCI::Manager::Manager ()
Definition at line 1101 of file pci.cpp.
     {
 #if defined(a86)
         if (!PowerManager->GetACPI())
         {
             error("ACPI not found");
             return;
         }
         if (!((ACPI::ACPI *)PowerManager->GetACPI())->MCFG)
         {
             error("MCFG not found");
             return;
         }
         int Entries = s_cst(int, ((((ACPI::ACPI *)PowerManager->GetACPI())->MCFG->Header.Length) - sizeof(ACPI::ACPI::MCFGHeader)) / sizeof(DeviceConfig));
         Memory::Virtual vmm(KernelPageTable);
         for (int t = 0; t < Entries; t++)
         {
             DeviceConfig *NewDeviceConfig = (DeviceConfig *)((uintptr_t)((ACPI::ACPI *)PowerManager->GetACPI())->MCFG + sizeof(ACPI::ACPI::MCFGHeader) + (sizeof(DeviceConfig) * t));
             vmm.Map((void *)NewDeviceConfig->BaseAddress, (void *)NewDeviceConfig->BaseAddress, Memory::PTFlag::RW);
             debug("PCI Entry %d Address:%p BUS:%#x-%#x", t, NewDeviceConfig->BaseAddress,
                   NewDeviceConfig->StartBus, NewDeviceConfig->EndBus);
             PCIDevice dev{};
             dev.Config = NewDeviceConfig;
             for (uint32_t Bus = NewDeviceConfig->StartBus; Bus < NewDeviceConfig->EndBus; Bus++)
                 EnumerateBus(NewDeviceConfig->BaseAddress, Bus, dev);
         }
 #elif defined(aa64)
         error("PCI not implemented on aarch64");
 #endif
     }
References PCI::DeviceConfig::BaseAddress, PCI::PCIDevice::Config, debug, PCI::DeviceConfig::EndBus, Entries, EnumerateBus(), error, Power::Power::GetACPI(), KernelPageTable, Memory::Virtual::Map(), PowerManager, Memory::RW, and PCI::DeviceConfig::StartBus.
~Manager()
PCI::Manager::~Manager ()
Definition at line 1135 of file pci.cpp.
 {}
Member Function Documentation
EnumerateBus()
void PCI::Manager::EnumerateBus (uint64_t BaseAddress, uint32_t Bus, PCIDevice dev)
Definition at line 1024 of file pci.cpp.
     {
         dev.Bus = Bus;
         uintptr_t Offset = Bus << 20;
         uint64_t BusAddress = BaseAddress + Offset;
         Memory::Virtual(KernelPageTable).Map((void *)BusAddress, (void *)BusAddress, Memory::PTFlag::RW);
         PCIDeviceHeader *PCIDeviceHdr = (PCIDeviceHeader *)BusAddress;
         if (Bus != 0) // TODO: VirtualBox workaround (UNTESTED ON REAL HARDWARE!)
         {
             if (PCIDeviceHdr->DeviceID == 0)
                 return;
             if (PCIDeviceHdr->DeviceID == 0xFFFF)
                 return;
         }
         debug("PCI Bus DeviceID:%#x VendorID:%#x BIST:%#x Cache:%#x Class:%#x Cmd:%#x HdrType:%#x LatencyTimer:%#x ProgIF:%#x RevID:%#x Status:%#x SubClass:%#x ",
               PCIDeviceHdr->DeviceID, PCIDeviceHdr->VendorID, PCIDeviceHdr->BIST,
               PCIDeviceHdr->CacheLineSize, PCIDeviceHdr->Class, PCIDeviceHdr->Command,
               PCIDeviceHdr->HeaderType, PCIDeviceHdr->LatencyTimer, PCIDeviceHdr->ProgIF,
               PCIDeviceHdr->RevisionID, PCIDeviceHdr->Status, PCIDeviceHdr->Subclass);
         for (uint32_t Device = 0; Device < 32; Device++)
             EnumerateDevice(BusAddress, Device, dev);
     }
References PCI::PCIDeviceHeader::BIST, PCI::PCIDevice::Bus, PCI::PCIDeviceHeader::CacheLineSize, PCI::PCIDeviceHeader::Class, PCI::PCIDeviceHeader::Command, debug, PCI::PCIDeviceHeader::DeviceID, EnumerateDevice(), PCI::PCIDeviceHeader::HeaderType, KernelPageTable, PCI::PCIDeviceHeader::LatencyTimer, Memory::Virtual::Map(), PCI::PCIDeviceHeader::ProgIF, PCI::PCIDeviceHeader::RevisionID, Memory::RW, PCI::PCIDeviceHeader::Status, PCI::PCIDeviceHeader::Subclass, and PCI::PCIDeviceHeader::VendorID.
Referenced by Manager().
EnumerateDevice()
void PCI::Manager::EnumerateDevice (uint64_t BusAddress, uint32_t Device, PCIDevice dev)
Definition at line 1006 of file pci.cpp.
     {
         dev.Device = Device;
         uintptr_t Offset = Device << 15;
         uint64_t DeviceAddress = BusAddress + Offset;
         Memory::Virtual(KernelPageTable).Map((void *)DeviceAddress, (void *)DeviceAddress, Memory::PTFlag::RW);
         PCIDeviceHeader *PCIDeviceHdr = (PCIDeviceHeader *)DeviceAddress;
         if (PCIDeviceHdr->DeviceID == 0)
             return;
         if (PCIDeviceHdr->DeviceID == 0xFFFF)
             return;
         for (uint32_t Function = 0; Function < 8; Function++)
             EnumerateFunction(DeviceAddress, Function, dev);
     }
References PCI::PCIDevice::Device, PCI::PCIDeviceHeader::DeviceID, EnumerateFunction(), KernelPageTable, Memory::Virtual::Map(), and Memory::RW.
Referenced by EnumerateBus().
EnumerateFunction()
void PCI::Manager::EnumerateFunction (uint64_t DeviceAddress, uint32_t Function, PCIDevice dev)
Definition at line 985 of file pci.cpp.
     {
         dev.Function = Function;
         uintptr_t Offset = Function << 12;
         uint64_t FunctionAddress = DeviceAddress + Offset;
         Memory::Virtual(KernelPageTable).Map((void *)FunctionAddress, (void *)FunctionAddress, Memory::PTFlag::RW);
         PCIDeviceHeader *PCIDeviceHdr = (PCIDeviceHeader *)FunctionAddress;
         dev.Header = PCIDeviceHdr;
         if (PCIDeviceHdr->DeviceID == 0)
             return;
         if (PCIDeviceHdr->DeviceID == 0xFFFF)
             return;
         Devices.push_back(dev);
 #ifdef DEBUG
         e(dev);
 #endif
     }
References PCI::PCIDeviceHeader::DeviceID, Devices, PCI::PCIDevice::Function, PCI::PCIDevice::Header, KernelPageTable, Memory::Virtual::Map(), and Memory::RW.
Referenced by EnumerateDevice().
FindPCIDevice() [1/3]
std::list< PCIDevice > PCI::Manager::FindPCIDevice (std::list< uint16_t > VendorIDs, std::list< uint16_t > DeviceIDs)
Definition at line 1080 of file pci.cpp.
     {
         std::list<PCIDevice> DeviceFound;
         foreach (auto dev in Devices)
         {
             foreach (auto VendorID in VendorIDs)
             {
                 foreach (auto DeviceID in DeviceIDs)
                 {
                     if (dev.Header->VendorID == VendorID &&
                         dev.Header->DeviceID == DeviceID)
                     {
                         DeviceFound.push_back(dev);
                     }
                 }
             }
         }
         return DeviceFound;
     }
References Devices.
FindPCIDevice() [2/3]
std::list< PCIDevice > PCI::Manager::FindPCIDevice (uint16_t VendorID, uint16_t DeviceID)
Definition at line 1066 of file pci.cpp.
     {
         std::list<PCIDevice> DeviceFound;
         foreach (auto dev in Devices)
         {
             if (dev.Header->VendorID == VendorID &&
                 dev.Header->DeviceID == DeviceID)
             {
                 DeviceFound.push_back(dev);
             }
         }
         return DeviceFound;
     }
References Devices.
FindPCIDevice() [3/3]
std::list< PCIDevice > PCI::Manager::FindPCIDevice (uint8_t Class, uint8_t Subclass, uint8_t ProgIF)
Definition at line 1051 of file pci.cpp.
     {
         std::list<PCIDevice> DeviceFound;
         foreach (auto dev in Devices)
         {
             if (dev.Header->Class == Class &&
                 dev.Header->Subclass == Subclass &&
                 dev.Header->ProgIF == ProgIF)
             {
                 DeviceFound.push_back(dev);
             }
         }
         return DeviceFound;
     }
References Devices.
Referenced by Driver::GetPCIDevices().
GetDevices()
std::list<PCIDevice> PCI::Manager::GetDevices () inline
Definition at line 233 of file pci.hpp.
 { return Devices; }
References Devices.
Referenced by cmd_lspci().
MapPCIAddresses()
void PCI::Manager::MapPCIAddresses (PCIDevice Device, Memory::PageTable * Table)
Definition at line 877 of file pci.cpp.
     {
         debug("Header Type: %d", Device.Header->HeaderType);
         switch (Device.Header->HeaderType)
         {
         case 128:
             warn("Unknown header type %d! Guessing PCI Header 0",
                  Device.Header->HeaderType);
             [[fallthrough]];
         case 0: /* PCI Header 0 */
         {
             PCIHeader0 *hdr0 = (PCIHeader0 *)Device.Header;
             uint32_t BAR[6];
             size_t BARsSize[6];
             BAR[0] = hdr0->BAR0;
             BAR[1] = hdr0->BAR1;
             BAR[2] = hdr0->BAR2;
             BAR[3] = hdr0->BAR3;
             BAR[4] = hdr0->BAR4;
             BAR[5] = hdr0->BAR5;
             debug("Type: %d; IOBase: %#lx; MemoryBase: %#lx",
                   BAR[0] & 1, BAR[1] & (~3), BAR[0] & (~15));
             /* BARs Size */
             for (short i = 0; i < 6; i++)
             {
                 if (BAR[i] == 0)
                     continue;
                 size_t size;
                 if ((BAR[i] & 1) == 0) /* Memory Base */
                 {
                     hdr0->BAR0 = 0xFFFFFFFF;
                     size = hdr0->BAR0;
                     hdr0->BAR0 = BAR[i];
                     BARsSize[i] = size & (~15);
                     BARsSize[i] = ~BARsSize[i] + 1;
                     BARsSize[i] = BARsSize[i] & 0xFFFFFFFF;
                     debug("BAR%d %#lx size: %d",
                           i, BAR[i], BARsSize[i]);
                 }
                 else if ((BAR[i] & 1) == 1) /* I/O Base */
                 {
                     hdr0->BAR1 = 0xFFFFFFFF;
                     size = hdr0->BAR1;
                     hdr0->BAR1 = BAR[i];
                     BARsSize[i] = size & (~3);
                     BARsSize[i] = ~BARsSize[i] + 1;
                     BARsSize[i] = BARsSize[i] & 0xFFFF;
                     debug("BAR%d %#lx size: %d",
                           i, BAR[i], BARsSize[i]);
                 }
             }
             /* Mapping the BARs */
             for (short i = 0; i < 6; i++)
             {
                 if (BAR[i] == 0)
                     continue;
                 if ((BAR[i] & 1) == 0) /* Memory Base */
                 {
                     uintptr_t BARBase = BAR[i] & (~15);
                     size_t BARSize = BARsSize[i];
                     debug("Mapping BAR%d %#lx-%#lx",
                           i, BARBase, BARBase + BARSize);
                     if (BARSize > 0)
                         Memory::Virtual(Table).Map((void *)BARBase, (void *)BARBase,
                                                    BARSize, Memory::RW | Memory::PWT);
                 }
                 else if ((BAR[i] & 1) == 1) /* I/O Base */
                 {
                     uintptr_t BARBase = BAR[i] & (~3);
                     size_t BARSize = BARsSize[i];
                     debug("Mapping BAR%d %#x-%#x",
                           i, BARBase, BARBase + BARSize);
                     if (BARSize > 0)
                         Memory::Virtual(Table).Map((void *)BARBase, (void *)BARBase,
                                                    BARSize, Memory::RW | Memory::PWT);
                 }
             }
             break;
         }
         case 1: /* PCI Header 1 (PCI-to-PCI Bridge) */
         {
             fixme("PCI Header 1 (PCI-to-PCI Bridge) not implemented yet");
             break;
         }
         case 2: /* PCI Header 2 (PCI-to-CardBus Bridge) */
         {
             fixme("PCI Header 2 (PCI-to-CardBus Bridge) not implemented yet");
             break;
         }
         default:
         {
             error("Unknown header type %d", Device.Header->HeaderType);
             break;
         }
         }
     }
References PCI::PCIHeader0::BAR0, PCI::PCIHeader0::BAR1, PCI::PCIHeader0::BAR2, PCI::PCIHeader0::BAR3, PCI::PCIHeader0::BAR4, PCI::PCIHeader0::BAR5, debug, error, fixme, PCI::PCIDevice::Header, PCI::PCIDeviceHeader::HeaderType, Memory::Virtual::Map(), Memory::PWT, Memory::RW, size, and warn.
Field Documentation
Devices
std::list<PCIDevice> PCI::Manager::Devices private
Definition at line 230 of file pci.hpp.
Referenced by EnumerateFunction(), FindPCIDevice(), and GetDevices().
The documentation for this class was generated from the following files:
Kernel/include/pci.hpp
Kernel/core/pci.cpp