Fennix: Tasking Namespace Reference
Tasking Namespace Reference
Data Structures
struct TaskInfo
struct gsTCB
class TCB
class PCB
class Task
struct TCB.Security
struct PCB.Security
struct PCB.Security.Real
struct PCB.Security.Effective
Typedefs
typedef __UINTPTR_TYPE__ IP
typedef int PID
typedef int TID
Enumerations
enum TaskArchitecture {
UnknownArchitecture , x32 , x64 , ARM32 ,
ARM64 , _ArchitectureMin = UnknownArchitecture , _ArchitectureMax = ARM64
}
enum TaskCompatibility {
UnknownPlatform , Native , Linux , Windows ,
_CompatibilityMin = UnknownPlatform , _CompatibilityMax = Windows
}
enum TaskExecutionMode {
UnknownExecutionMode , Kernel , System , User ,
_ExecuteModeMin = UnknownExecutionMode , _ExecuteModeMax = User
}
enum TaskStatus : int {
UnknownStatus , Ready , Running , Sleeping ,
Blocked , Zombie , Terminated , _StatusMin = UnknownStatus ,
_StatusMax = Terminated
}
enum TaskPriority {
UnknownPriority = 0 , Idle = 1 , Low = 2 , Normal = 5 ,
High = 8 , Critical = 10 , _PriorityMin = UnknownPriority , _PriorityMax = Critical
}
enum KillErrorCodes : int {
KILL_SCHEDULER_DESTRUCTION = -0xFFFF , KILL_CXXABI_EXCEPTION = -0xECE97 , KILL_BY_OTHER_PROCESS = -0x7A55 , KILL_SYSCALL = -0xCA11 ,
KILL_CRASH = -0xDEAD , KILL_OOM = -0x1008 , KILL_ERROR = -0x1 , KILL_SUCCESS = 0
}
Functions
__no_sanitize ("undefined") TCB
Data Structure Documentation
Tasking::TaskInfo
struct Tasking::TaskInfo
Definition at line 118 of file task.hpp.
Data Fields
bool Affinity[256]
TaskArchitecture Architecture
TaskCompatibility Compatibility
uint64_t Day
uint64_t Hour
uint64_t KernelTime
uint64_t LastUpdateTime
uint64_t Minute
uint64_t Month
uint64_t OldKernelTime
uint64_t OldUserTime
TaskPriority Priority
uint64_t Second
uint64_t SleepUntil
uint64_t SpawnTime
uint64_t UserTime
uint64_t Year
Tasking::gsTCB
struct Tasking::gsTCB
TCB struct for gs register
Definition at line 135 of file task.hpp.
Data Fields
uintptr_t SyscallStack
Used by syscall handler
gs+0x0
class TCB * t
The current thread class
uintptr_t TempStack
Used by syscall handler
gs+0x8
Tasking::TCB.Security
struct Tasking::TCB.Security
Definition at line 183 of file task.hpp.
Data Fields
TaskExecutionMode ExecutionMode
bool IsCritical
bool IsDebugEnabled
bool IsKernelDebugEnabled
Tasking::PCB.Security
struct Tasking::PCB.Security
Definition at line 236 of file task.hpp.
Data Fields
Security Effective
TaskExecutionMode ExecutionMode
bool IsCritical
bool IsDebugEnabled
bool IsKernelDebugEnabled
Security Real
Tasking::PCB.Security.Real
struct Tasking::PCB.Security.Real
Definition at line 242 of file task.hpp.
Data Fields
uint16_t GroupID
uint16_t UserID
Tasking::PCB.Security.Effective
struct Tasking::PCB.Security.Effective
Definition at line 242 of file task.hpp.
Data Fields
uint16_t GroupID
uint16_t UserID
Typedef Documentation
IP
typedef __UINTPTR_TYPE__ Tasking::IP
Instruction Pointer
Definition at line 39 of file task.hpp.
PID
typedef int Tasking::PID
Process ID
Definition at line 41 of file task.hpp.
TID
typedef int Tasking::TID
Thread ID
Definition at line 43 of file task.hpp.
Enumeration Type Documentation
KillErrorCodes
enum Tasking::KillErrorCodes : int
Enumerator
KILL_SCHEDULER_DESTRUCTION
KILL_CXXABI_EXCEPTION
KILL_BY_OTHER_PROCESS
KILL_SYSCALL
KILL_CRASH
KILL_OOM
KILL_ERROR
KILL_SUCCESS
Definition at line 106 of file task.hpp.
     {
         KILL_SCHEDULER_DESTRUCTION = -0xFFFF,
         KILL_CXXABI_EXCEPTION = -0xECE97,
         KILL_BY_OTHER_PROCESS = -0x7A55,
         KILL_SYSCALL = -0xCA11,
         KILL_CRASH = -0xDEAD,
         KILL_OOM = -0x1008,
         KILL_ERROR = -0x1,
         KILL_SUCCESS = 0,
     };
TaskArchitecture
enum Tasking::TaskArchitecture
Enumerator
UnknownArchitecture
x32
x64
ARM32
ARM64
_ArchitectureMin
_ArchitectureMax
Definition at line 45 of file task.hpp.
     {
         UnknownArchitecture,
         x32,
         x64,
         ARM32,
         ARM64,
         _ArchitectureMin = UnknownArchitecture,
         _ArchitectureMax = ARM64
     };
TaskCompatibility
enum Tasking::TaskCompatibility
Enumerator
UnknownPlatform
Native
Linux
Windows
_CompatibilityMin
_CompatibilityMax
Definition at line 57 of file task.hpp.
     {
         UnknownPlatform,
         Native,
         Linux,
         Windows,
         _CompatibilityMin = UnknownPlatform,
         _CompatibilityMax = Windows
     };
TaskExecutionMode
enum Tasking::TaskExecutionMode
Enumerator
UnknownExecutionMode
Kernel
System
User
_ExecuteModeMin
_ExecuteModeMax
Definition at line 68 of file task.hpp.
     {
         UnknownExecutionMode,
         Kernel,
         System,
         User,
         _ExecuteModeMin = UnknownExecutionMode,
         _ExecuteModeMax = User
     };
TaskPriority
enum Tasking::TaskPriority
Enumerator
UnknownPriority
Idle
Low
Normal
High
Critical
_PriorityMin
_PriorityMax
Definition at line 93 of file task.hpp.
     {
         UnknownPriority = 0,
         Idle = 1,
         Low = 2,
         Normal = 5,
         High = 8,
         Critical = 10,
         _PriorityMin = UnknownPriority,
         _PriorityMax = Critical
     };
TaskStatus
enum Tasking::TaskStatus : int
Enumerator
UnknownStatus
Ready
Running
Sleeping
Blocked
Zombie
Terminated
_StatusMin
_StatusMax
Definition at line 79 of file task.hpp.
     {
         UnknownStatus,
         Ready,
         Running,
         Sleeping,
         Blocked,
         Zombie,
         Terminated,
         _StatusMin = UnknownStatus,
         _StatusMax = Terminated
     };
Function Documentation
__no_sanitize()
Tasking::__no_sanitize ("undefined")
Definition at line 128 of file Thread.cpp.
     {
         assert(ctx != nullptr);
         assert(Architecture >= _ArchitectureMin);
         assert(Architecture <= _ArchitectureMax);
         assert(Compatibility >= _CompatibilityMin);
         assert(Compatibility <= _CompatibilityMax);
         if (Parent == nullptr)
         {
             this->Parent = ctx->GetCurrentProcess();
             assert(this->Parent != nullptr);
         }
         else
             this->Parent = Parent;
         this->ctx = ctx;
         this->ID = ctx->NextTID++;
         if (this->Name)
             delete[] this->Name;
         this->Name = new char[strlen(this->Parent->Name) + 1];
         strcpy((char *)this->Name, this->Parent->Name);
         this->EntryPoint = EntryPoint;
         this->ExitCode = KILL_CRASH;
         this->Info.Architecture = Architecture;
         this->Info.Compatibility = Compatibility;
         this->Security.ExecutionMode =
             this->Parent->Security.ExecutionMode;
         if (ThreadNotReady)
             this->Status = TaskStatus::Zombie;
         else
             this->Status = TaskStatus::Ready;
         this->Memory = new Memory::MemMgr(this->Parent->PageTable,
                                           this->Parent->memDirectory);
         std::size_t FXPgs = TO_PAGES(sizeof(CPU::x64::FXState) + 1);
         this->FPU = (CPU::x64::FXState *)this->Memory->RequestPages(FXPgs);
         memset(this->FPU, 0, sizeof(CPU::x64::FXState));
         // TODO: Is really a good idea to use the FPU in kernel mode?
         this->FPU->mxcsr = 0b0001111110000000;
         this->FPU->mxcsrmask = 0b1111111110111111;
         this->FPU->fcw = 0b0000001100111111;
         // CPU::x64::fxrstor(this->FPU);
         // uint16_t FCW = 0b1100111111;
         // asmv("fldcw %0"
         //      :
         //      : "m"(FCW)
         //      : "memory");
         // uint32_t MXCSR = 0b1111110000000;
         // asmv("ldmxcsr %0"
         //      :
         //      : "m"(MXCSR)
         //      : "memory");
         // CPU::x64::fxsave(this->FPU);
 #if defined(a64)
         this->Registers.rip = EntryPoint;
 #elif defined(a32)
         this->Registers.eip = EntryPoint;
 #elif defined(aa64)
         this->Registers.pc = EntryPoint;
 #endif
         switch (this->Parent->Security.ExecutionMode)
         {
         case TaskExecutionMode::System:
             fixme("System mode not supported.");
             [[fallthrough]];
         case TaskExecutionMode::Kernel:
         {
             this->Security.IsCritical = true;
             this->Stack = new Memory::StackGuard(false,
                                                  this->Parent->PageTable);
 #if defined(a64)
             this->ShadowGSBase =
                 CPU::x64::rdmsr(CPU::x64::MSRID::MSR_SHADOW_GS_BASE);
             this->GSBase = CPU::x64::rdmsr(CPU::x64::MSRID::MSR_GS_BASE);
             this->FSBase = CPU::x64::rdmsr(CPU::x64::MSRID::MSR_FS_BASE);
             this->Registers.cs = GDT_KERNEL_CODE;
             this->Registers.ss = GDT_KERNEL_DATA;
             this->Registers.rflags.AlwaysOne = 1;
             this->Registers.rflags.IF = 1;
             this->Registers.rflags.ID = 1;
             this->Registers.rsp = ((uintptr_t)this->Stack->GetStackTop());
             POKE(uintptr_t, this->Registers.rsp) = (uintptr_t)ThreadDoExit;
 #elif defined(a32)
 #elif defined(aa64)
 #endif
             break;
         }
         case TaskExecutionMode::User:
         {
             this->Stack = new Memory::StackGuard(true,
                                                  this->Parent->PageTable);
             gsTCB *gsT = (gsTCB *)this->Memory->RequestPages(TO_PAGES(sizeof(gsTCB)));
             gsT->SyscallStack =
                 (uintptr_t)this->Memory->RequestPages(TO_PAGES(STACK_SIZE)) +
                 STACK_SIZE - 0x10;
             gsT->TempStack = 0x0;
             gsT->t = this;
 #if defined(a64)
             this->ShadowGSBase = (uintptr_t)gsT;
             this->GSBase = 0;
             this->FSBase = 0;
             this->Registers.cs = GDT_USER_CODE;
             this->Registers.ss = GDT_USER_DATA;
             this->Registers.rflags.AlwaysOne = 1;
             this->Registers.rflags.IF = 1;
             this->Registers.rflags.ID = 1;
             /* We need to leave the libc's crt
                to make a syscall when the Thread
                is exited or we are going to get
                GPF or PF exception. */
 #pragma region
             size_t ArgvSize = 0;
             if (argv)
                 while (argv[ArgvSize] != nullptr)
                     ArgvSize++;
             size_t EnvpSize = 0;
             if (envp)
                 while (envp[EnvpSize] != nullptr)
                     EnvpSize++;
             debug("ArgvSize: %d", ArgvSize);
             debug("EnvpSize: %d", EnvpSize);
             /* https://articles.manugarg.com/aboutelfauxiliaryvectors.html */
             /* https://refspecs.linuxbase.org/elf/x86_64-abi-0.99.pdf#figure.3.9 */
             // rsp is the top of the stack
             char *Stack = (char *)this->Stack->GetStackPhysicalTop();
             // Temporary stack pointer for strings
             char *StackStrings = (char *)Stack;
             char *StackStringsVirtual = (char *)this->Stack->GetStackTop();
             // Store string pointers for later
             uintptr_t *ArgvStrings = nullptr;
             uintptr_t *EnvpStrings = nullptr;
             if (ArgvSize > 0)
                 ArgvStrings = new uintptr_t[ArgvSize];
             if (EnvpSize > 0)
                 EnvpStrings = new uintptr_t[EnvpSize];
             for (size_t i = 0; i < ArgvSize; i++)
             {
                 // Subtract the length of the string and the null terminator
                 StackStrings -= strlen(argv[i]) + 1;
                 StackStringsVirtual -= strlen(argv[i]) + 1;
                 // Store the pointer to the string
                 ArgvStrings[i] = (uintptr_t)StackStringsVirtual;
                 // Copy the string to the stack
                 strcpy(StackStrings, argv[i]);
                 debug("argv[%d]: %s", i, argv[i]);
             }
             for (size_t i = 0; i < EnvpSize; i++)
             {
                 // Subtract the length of the string and the null terminator
                 StackStrings -= strlen(envp[i]) + 1;
                 StackStringsVirtual -= strlen(envp[i]) + 1;
                 // Store the pointer to the string
                 EnvpStrings[i] = (uintptr_t)StackStringsVirtual;
                 // Copy the string to the stack
                 strcpy(StackStrings, envp[i]);
                 debug("envp[%d]: %s", i, envp[i]);
             }
             // Align the stack to 16 bytes
             StackStrings -= (uintptr_t)StackStrings & 0xF;
             // Set "Stack" to the new stack pointer
             Stack = (char *)StackStrings;
             // If argv and envp sizes are odd then we need to align the stack
             Stack -= (ArgvSize + EnvpSize) % 2;
             // We need 8 bit pointers for the stack from here
             uintptr_t *Stack64 = (uintptr_t *)Stack;
             // Store the null terminator
             Stack64--;
             *Stack64 = AT_NULL;
             // auxv_array is initialized with auxv elements. If the array is empty then we add a null terminator
             std::vector<AuxiliaryVector> auxv_array = auxv;
             if (auxv_array.size() == 0)
                 auxv_array.push_back({.archaux = {.a_type = AT_NULL, .a_un = {.a_val = 0}}});
             // Store auxillary vector
             foreach (AuxiliaryVector var in auxv_array)
             {
                 // Subtract the size of the auxillary vector
                 Stack64 -= sizeof(Elf64_auxv_t) / sizeof(uintptr_t);
                 // Store the auxillary vector
                 POKE(Elf64_auxv_t, Stack64) = var.archaux;
                 // TODO: Store strings to the stack
             }
             // Store the null terminator
             Stack64--;
             *Stack64 = AT_NULL;
             // Store EnvpStrings[] to the stack
             Stack64 -= EnvpSize; // (1 Stack64 = 8 bits; Stack64 = 8 * EnvpSize)
             for (size_t i = 0; i < EnvpSize; i++)
             {
                 *(Stack64 + i) = (uintptr_t)EnvpStrings[i];
                 debug("EnvpStrings[%d]: %#lx",
                       i, EnvpStrings[i]);
             }
             // Store the null terminator
             Stack64--;
             *Stack64 = AT_NULL;
             // Store ArgvStrings[] to the stack
             Stack64 -= ArgvSize; // (1 Stack64 = 8 bits; Stack64 = 8 * ArgvSize)
             for (size_t i = 0; i < ArgvSize; i++)
             {
                 *(Stack64 + i) = (uintptr_t)ArgvStrings[i];
                 debug("ArgvStrings[%d]: %#lx",
                       i, ArgvStrings[i]);
             }
             // Store the argc
             Stack64--;
             *Stack64 = ArgvSize;
             // Set "Stack" to the new stack pointer
             Stack = (char *)Stack64;
             /* We need the virtual address but because we are in the kernel we can't use the process page table.
                 So we modify the physical address and store how much we need to subtract to get the virtual address for RSP. */
             uintptr_t SubtractStack = (uintptr_t)this->Stack->GetStackPhysicalTop() - (uintptr_t)Stack;
             debug("SubtractStack: %#lx", SubtractStack);
             // Set the stack pointer to the new stack
             this->Registers.rsp = ((uintptr_t)this->Stack->GetStackTop() - SubtractStack);
             if (ArgvSize > 0)
                 delete[] ArgvStrings;
             if (EnvpSize > 0)
                 delete[] EnvpStrings;
 #ifdef DEBUG
             DumpData("Stack Data", (void *)((uintptr_t)this->Stack->GetStackPhysicalTop() - (uintptr_t)SubtractStack), SubtractStack);
 #endif
             this->Registers.rdi = (uintptr_t)ArgvSize;                                       // argc
             this->Registers.rsi = (uintptr_t)(this->Registers.rsp + 8);                      // argv
             this->Registers.rcx = (uintptr_t)EnvpSize;                                       // envc
             this->Registers.rdx = (uintptr_t)(this->Registers.rsp + 8 + (8 * ArgvSize) + 8); // envp
 #pragma endregion
 #elif defined(a32)
 #elif defined(aa64)
 #endif
 #ifdef DEBUG_TASKING
             DumpData(this->Name, this->Stack, STACK_SIZE);
 #endif
             break;
         }
         default:
             assert(false);
         }
         this->Info.SpawnTime = TimeManager->GetCounter();
 #ifdef DEBUG
 #ifdef a64
         debug("Thread EntryPoint: %#lx => RIP: %#lx",
               this->EntryPoint, this->Registers.rip);
         if (this->Parent->Security.ExecutionMode == TaskExecutionMode::User)
             debug("Thread stack region is %#lx-%#lx (U) and rsp is %#lx",
                   this->Stack->GetStackBottom(), this->Stack->GetStackTop(),
                   this->Registers.rsp);
         else
             debug("Thread stack region is %#lx-%#lx (K) and rsp is %#lx",
                   this->Stack->GetStackBottom(), this->Stack->GetStackTop(),
                   this->Registers.rsp);
 #elif defined(a32)
         debug("Thread EntryPoint: %#lx => RIP: %#lx",
               this->EntryPoint, this->Registers.eip);
         if (Parent->Security.ExecutionMode == TaskExecutionMode::User)
             debug("Thread stack region is %#lx-%#lx (U) and rsp is %#lx",
                   this->Stack->GetStackBottom(), this->Stack->GetStackTop(),
                   this->Registers.esp);
         else
             debug("Thread stack region is %#lx-%#lx (K) and rsp is %#lx",
                   this->Stack->GetStackBottom(), this->Stack->GetStackTop(),
                   this->Registers.esp);
 #elif defined(aa64)
 #endif
         debug("Created thread \"%s\"(%d) in process \"%s\"(%d)",
               this->Name, this->ID, this->Parent->Name,
               this->Parent->ID);
 #endif
         this->Parent->Threads.push_back(this);
         if (this->Parent->Threads.size() == 1 &&
             this->Parent->Status == Zombie &&
             ThreadNotReady == false)
         {
             this->Parent->Status = Ready;
         }
     }
References _ArchitectureMax, _ArchitectureMin, _CompatibilityMax, _CompatibilityMin, argv, assert, AT_NULL, ctx, debug, EntryPoint, fixme, GDT_KERNEL_CODE, GDT_KERNEL_DATA, GDT_USER_CODE, GDT_USER_DATA, i, ID, Info, Kernel, KILL_CRASH, memset, CPU::x32::MSR_FS_BASE, CPU::x32::MSR_GS_BASE, CPU::x32::MSR_SHADOW_GS_BASE, CPU::Name(), POKE, Ready, CPU::x86::Security, Stack, Status, strcpy, strlen(), Tasking::gsTCB::SyscallStack, System, Tasking::gsTCB::t, Tasking::gsTCB::TempStack, ThreadDoExit(), TO_PAGES, User, and Zombie.