Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/gusconf.h File Reference
gusconf.h File Reference
#include "doomtype.h"
Functions
boolean GUS_WriteConfig (char *path)
Variables
char * gus_patch_path
unsigned int gus_ram_kb
Function Documentation
GUS_WriteConfig()
boolean GUS_WriteConfig (char * path)
Definition at line 244 of file gusconf.c.
 {
     boolean result;
     char *dmxconf;
     gus_config_t config;
     if (!strcmp(gus_patch_path, ""))
     {
         printf("You haven't configured gus_patch_path.\n");
         printf("gus_patch_path needs to point to the location of "
                "your GUS patch set.\n"
                "To get a copy of the \"standard\" GUS patches, "
                "download a copy of dgguspat.zip.\n");
         return false;
     }
     dmxconf = ReadDMXConfig();
     ParseDMXConfig(dmxconf, &config);
     result = WriteTimidityConfig(path, &config);
     FreeDMXConfig(&config);
     Z_Free(dmxconf);
     return result;
 }
References FreeDMXConfig(), gus_patch_path, ParseDMXConfig(), printf(), ReadDMXConfig(), strcmp, WriteTimidityConfig(), and Z_Free().
Variable Documentation
gus_patch_path
char* gus_patch_path extern
Definition at line 40 of file gusconf.c.
Referenced by GUS_WriteConfig(), and WriteTimidityConfig().
gus_ram_kb
unsigned int gus_ram_kb extern
Definition at line 41 of file gusconf.c.
Referenced by MappingIndex().