Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/i_endoom.c File Reference
i_endoom.c File Reference
#include <stdio.h>
#include <string.h>
#include "config.h"
#include "doomtype.h"
#include "i_video.h"
Macros
#define ENDOOM_W 80
#define ENDOOM_H 25
Functions
void I_Endoom (byte *endoom_data)
Macro Definition Documentation
ENDOOM_H
#define ENDOOM_H 25
Definition at line 30 of file i_endoom.c.
ENDOOM_W
#define ENDOOM_W 80
Definition at line 29 of file i_endoom.c.
Function Documentation
I_Endoom()
void I_Endoom (byte * endoom_data)
Definition at line 36 of file i_endoom.c.
 {
 #ifdef ORIGCODE
     unsigned char *screendata;
     int y;
     int indent;
     // Set up text mode screen
     TXT_Init();
     I_InitWindowTitle();
     I_InitWindowIcon();
     // Write the data to the screen memory
     screendata = TXT_GetScreenData();
     indent = (ENDOOM_W - TXT_SCREEN_W) / 2;
     for (y=0; y<TXT_SCREEN_H; ++y)
     {
         memcpy(screendata + (y * TXT_SCREEN_W * 2),
                endoom_data + (y * ENDOOM_W + indent) * 2,
                TXT_SCREEN_W * 2);
     }
     // Wait for a keypress
     while (true)
     {
         TXT_UpdateScreen();
         if (TXT_GetChar() > 0)
         {
             break;
         }
         TXT_Sleep(0);
     }
     // Shut down text mode screen
     TXT_Shutdown();
 #endif
 }
References ENDOOM_W, I_InitWindowIcon(), I_InitWindowTitle(), indent(), memcpy(), and y.
Referenced by D_Endoom().