Fennix Userspace: Userspace/musl/include/sys/select.h File Reference
select.h File Reference
#include <features.h>
#include <bits/alltypes.h>
Data Structures
struct fd_set
Macros
#define __NEED_size_t
#define __NEED_time_t
#define __NEED_suseconds_t
#define __NEED_struct_timeval
#define __NEED_struct_timespec
#define __NEED_sigset_t
#define FD_SETSIZE 1024
#define FD_ZERO(s) do { int __i; unsigned long *__b=(s)->fds_bits; for(__i=sizeof (fd_set)/sizeof (long); __i; __i--) *__b++=0; } while(0)
#define FD_SET(d, s) ((s)->fds_bits[(d)/(8*sizeof(long))] |= (1UL<<((d)%(8*sizeof(long)))))
#define FD_CLR(d, s) ((s)->fds_bits[(d)/(8*sizeof(long))] &= ~(1UL<<((d)%(8*sizeof(long)))))
#define FD_ISSET(d, s) !!((s)->fds_bits[(d)/(8*sizeof(long))] & (1UL<<((d)%(8*sizeof(long)))))
Typedefs
typedef unsigned long fd_mask
Functions
int select (int, fd_set *__restrict, fd_set *__restrict, fd_set *__restrict, struct timeval *__restrict)
int pselect (int, fd_set *__restrict, fd_set *__restrict, fd_set *__restrict, const struct timespec *__restrict, const sigset_t *__restrict)
Data Structure Documentation
fd_set
struct fd_set
Definition at line 22 of file select.h.
Data Fields
unsigned long fds_bits[FD_SETSIZE/8/sizeof(long)]
Macro Definition Documentation
__NEED_sigset_t
#define __NEED_sigset_t
Definition at line 14 of file select.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 9 of file select.h.
__NEED_struct_timespec
#define __NEED_struct_timespec
Definition at line 13 of file select.h.
__NEED_struct_timeval
#define __NEED_struct_timeval
Definition at line 12 of file select.h.
__NEED_suseconds_t
#define __NEED_suseconds_t
Definition at line 11 of file select.h.
__NEED_time_t
#define __NEED_time_t
Definition at line 10 of file select.h.
FD_CLR
#define FD_CLR (d, s) ((s)->fds_bits[(d)/(8*sizeof(long))] &= ~(1UL<<((d)%(8*sizeof(long)))))
Definition at line 28 of file select.h.
FD_ISSET
#define FD_ISSET (d, s) !!((s)->fds_bits[(d)/(8*sizeof(long))] & (1UL<<((d)%(8*sizeof(long)))))
Definition at line 29 of file select.h.
FD_SET
#define FD_SET (d, s) ((s)->fds_bits[(d)/(8*sizeof(long))] |= (1UL<<((d)%(8*sizeof(long)))))
Definition at line 27 of file select.h.
FD_SETSIZE
#define FD_SETSIZE 1024
Definition at line 18 of file select.h.
FD_ZERO
#define FD_ZERO (s) do { int __i; unsigned long *__b=(s)->fds_bits; for(__i=sizeof (fd_set)/sizeof (long); __i; __i--) *__b++=0; } while(0)
Definition at line 26 of file select.h.
Typedef Documentation
fd_mask
typedef unsigned long fd_mask
Definition at line 20 of file select.h.
Function Documentation
pselect()
int pselect (int , fd_set * __restrict, fd_set * __restrict, fd_set * __restrict, const struct timespec * __restrict, const sigset_t * __restrict)
Referenced by __pselect_time32(), and nchars_avail().
select()
int select (int , fd_set * __restrict, fd_set * __restrict, fd_set * __restrict, struct timeval * __restrict)
Referenced by __select_time32(), _rl_input_available(), accept_builtin(), dhcprelay_main(), inetd_main(), input_avail(), isrv_run(), main(), nchars_avail(), rl_gather_tyi(), rl_insert_close(), and telnetd_main().