Fennix Userspace: Userspace/musl/src/conf/confstr.c File Reference
confstr.c File Reference
#include <unistd.h>
#include <stdio.h>
#include <errno.h>
Functions
size_t confstr (int name, char *buf, size_t len)
Function Documentation
confstr()
size_t confstr (int name, char * buf, size_t len)
Definition at line 5 of file confstr.c.
 {
     const char *s = "";
     if (!name) {
         s = "/bin:/usr/bin";
     } else if ((name&~4U)!=1 && name-_CS_POSIX_V6_ILP32_OFF32_CFLAGS>35U) {
         errno = EINVAL;
         return 0;
     }
     // snprintf is overkill but avoid wasting code size to implement
     // this completely useless function and its truncation semantics
     return snprintf(buf, len, "%s", s) + 1;
 }
References _CS_POSIX_V6_ILP32_OFF32_CFLAGS, buf, EINVAL, errno, s, and snprintf().
Referenced by conf_standard_path(), and getconf_print().