Fennix Kernel: Tasking::TCB Class Reference
Tasking::TCB Class Reference
#include <task.hpp>
Public Member Functions
class Task * GetContext ()
int SendSignal (int sig)
void SetState (TaskState state)
void SetExitCode (int code)
void Rename (const char *name)
void SetPriority (TaskPriority priority)
int GetExitCode ()
void SetCritical (bool Critical)
void SetDebugMode (bool Enable)
void SetKernelDebugMode (bool Enable)
size_t GetSize ()
void Block ()
void Unblock ()
void SYSV_ABI_Call (uintptr_t Arg1=0, uintptr_t Arg2=0, uintptr_t Arg3=0, uintptr_t Arg4=0, uintptr_t Arg5=0, uintptr_t Arg6=0, void *Function=nullptr)
TCB (class Task *ctx, PCB *Parent, IP EntryPoint, const char **argv=nullptr, const char **envp=nullptr, const std::vector< AuxiliaryVector > &auxv=std::vector< AuxiliaryVector >(), TaskArchitecture Architecture=TaskArchitecture::x64, TaskCompatibility Compatibility=TaskCompatibility::Native, bool ThreadNotReady=false)
~TCB ()
Data Fields
TID ID = -1
const char * Name = nullptr
class PCB * Parent = nullptr
IP EntryPoint = 0
std::atomic_int ExitCode
std::atomic< TaskState > State = TaskState::Waiting
int ErrorNumber
Memory::VirtualMemoryArea * vma
Memory::StackGuard * Stack
struct {
TaskExecutionMode ExecutionMode = UnknownExecutionMode
bool IsCritical = false
bool IsDebugEnabled = false
bool IsKernelDebugEnabled = false
} Security
TaskInfo Info {}
ThreadLocalStorage TLS {}
struct {
int * set_child_tid {}
int * clear_child_tid {}
} Linux
Private Member Functions
void SetupUserStack_x86_64 (const char **argv, const char **envp, const std::vector< AuxiliaryVector > &auxv)
void SetupUserStack_x86_32 (const char **argv, const char **envp, const std::vector< AuxiliaryVector > &auxv)
void SetupUserStack_aarch64 (const char **argv, const char **envp, const std::vector< AuxiliaryVector > &auxv)
void SetupThreadLocalStorage ()
Private Attributes
class Task * ctx = nullptr
size_t AllocatedMemory = 0
Detailed Description
Definition at line 266 of file task.hpp.
Constructor & Destructor Documentation
TCB()
Tasking::TCB::TCB (class Task * ctx, PCB * Parent, IP EntryPoint, const char ** argv = nullptr, const char ** envp = nullptr, const std::vector< AuxiliaryVector > & auxv = std::vector<AuxiliaryVector>(), TaskArchitecture Architecture = TaskArchitecture::x64, TaskCompatibility Compatibility = TaskCompatibility::Native, bool ThreadNotReady = false)
Definition at line 405 of file thread.cpp.
     {
         debug("+ %#lx", this);
         assert(ctx != nullptr);
         assert(Architecture >= _ArchitectureMin);
         assert(Architecture <= _ArchitectureMax);
         assert(Compatibility >= _CompatibilityMin);
         assert(Compatibility <= _CompatibilityMax);
         if (Parent == nullptr)
         {
             this->Parent = ctx->GetCurrentProcess();
             assert(this->Parent != nullptr);
         }
         else
             this->Parent = Parent;
         this->ctx = ctx;
         this->ID = ctx->NextTID++;
         if (this->Name)
             delete[] this->Name;
         this->Name = new char[strlen(this->Parent->Name) + 1];
         strcpy((char *)this->Name, this->Parent->Name);
         this->EntryPoint = EntryPoint;
         this->ExitCode = KILL_CRASH;
         if (ThreadNotReady)
             this->SetState(Waiting);
         else
             this->SetState(Ready);
         this->vma = new Memory::VirtualMemoryArea(this->Parent->PageTable);
 #if defined(a64)
         this->Registers.rip = EntryPoint;
 #elif defined(a32)
         this->Registers.eip = EntryPoint;
 #elif defined(aa64)
         this->Registers.pc = EntryPoint;
 #endif
         switch (this->Parent->Security.ExecutionMode)
         {
         case TaskExecutionMode::System:
             fixme("System mode not supported.");
             [[fallthrough]];
         case TaskExecutionMode::Kernel:
         {
             this->Security.IsCritical = true;
             this->Stack = new Memory::StackGuard(false, this->vma);
 #if defined(a64)
             this->ShadowGSBase =
                 CPU::x64::rdmsr(CPU::x64::MSRID::MSR_SHADOW_GS_BASE);
             this->GSBase = CPU::x64::rdmsr(CPU::x64::MSRID::MSR_GS_BASE);
             this->FSBase = CPU::x64::rdmsr(CPU::x64::MSRID::MSR_FS_BASE);
             this->Registers.cs = GDT_KERNEL_CODE;
             this->Registers.ss = GDT_KERNEL_DATA;
             this->Registers.rflags.AlwaysOne = 1;
             this->Registers.rflags.IF = 1;
             this->Registers.rflags.ID = 1;
             this->Registers.rsp = ((uintptr_t)this->Stack->GetStackTop());
             POKE(uintptr_t, this->Registers.rsp) = (uintptr_t)ThreadDoExit;
 #elif defined(a32)
             this->Registers.cs = GDT_KERNEL_CODE;
             this->Registers.r3_ss = GDT_KERNEL_DATA;
             this->Registers.eflags.AlwaysOne = 1;
             this->Registers.eflags.IF = 1;
             this->Registers.eflags.ID = 1;
             this->Registers.esp = ((uintptr_t)this->Stack->GetStackTop());
             POKE(uintptr_t, this->Registers.esp) = (uintptr_t)ThreadDoExit;
 #elif defined(aa64)
             this->Registers.pc = EntryPoint;
             this->Registers.sp = ((uintptr_t)this->Stack->GetStackTop());
             POKE(uintptr_t, this->Registers.sp) = (uintptr_t)ThreadDoExit;
 #endif
             break;
         }
         case TaskExecutionMode::User:
         {
             this->Stack = new Memory::StackGuard(true, this->vma);
             gsTCB *gsT = (gsTCB *)this->vma->RequestPages(TO_PAGES(sizeof(gsTCB)));
             gsT->ScPages = TO_PAGES(STACK_SIZE);
             gsT->SyscallStackBase = this->vma->RequestPages(gsT->ScPages);
             gsT->SyscallStack = (uintptr_t)gsT->SyscallStackBase + STACK_SIZE - 0x10;
             debug("New syscall stack created: %#lx (base: %#lx) with gs base at %#lx",
                   gsT->SyscallStack, gsT->SyscallStackBase, gsT);
             gsT->TempStack = 0x0;
             gsT->t = this;
 #if defined(a64)
             this->ShadowGSBase = (uintptr_t)gsT;
             this->GSBase = 0;
             this->FSBase = 0;
             this->Registers.cs = GDT_USER_CODE;
             this->Registers.ss = GDT_USER_DATA;
             this->Registers.rflags.AlwaysOne = 1;
             this->Registers.rflags.IF = 1;
             this->Registers.rflags.ID = 1;
             /* We need to leave the libc's crt
                to make a syscall when the Thread
                is exited or we are going to get
                an exception. */
             this->SetupUserStack_x86_64(argv, envp, auxv);
 #elif defined(a32)
             this->Registers.cs = GDT_USER_CODE;
             this->Registers.r3_ss = GDT_USER_DATA;
             this->Registers.eflags.AlwaysOne = 1;
             this->Registers.eflags.IF = 1;
             this->Registers.eflags.ID = 1;
             /* We need to leave the libc's crt
                to make a syscall when the Thread
                is exited or we are going to get
                an exception. */
             this->SetupUserStack_x86_32(argv, envp, auxv);
 #elif defined(aa64)
             this->SetupUserStack_aarch64(argv, envp, auxv);
 #endif
 #ifdef DEBUG_TASKING
             DumpData(this->Name, this->Stack, STACK_SIZE);
 #endif
             break;
         }
         default:
             assert(false);
         }
         SetupThreadLocalStorage();
         this->Info.Architecture = Architecture;
         this->Info.Compatibility = Compatibility;
         this->Security.ExecutionMode =
             this->Parent->Security.ExecutionMode;
         if (this->Parent->Threads.size() == 0)
         {
             this->Parent->Info.Architecture = this->Info.Architecture;
             this->Parent->Info.Compatibility = this->Info.Compatibility;
         }
         // TODO: Is really a good idea to use the FPU in kernel mode?
         this->FPU.mxcsr = 0b0001111110000000;
         this->FPU.mxcsrmask = 0b1111111110111111;
         this->FPU.fcw = 0b0000001100111111;
 #ifdef DEBUG
 #ifdef a64
         debug("Thread EntryPoint: %#lx => RIP: %#lx",
               this->EntryPoint, this->Registers.rip);
         if (this->Parent->Security.ExecutionMode == TaskExecutionMode::User)
             debug("Thread stack region is %#lx-%#lx (U) and rsp is %#lx",
                   this->Stack->GetStackBottom(), this->Stack->GetStackTop(),
                   this->Registers.rsp);
         else
             debug("Thread stack region is %#lx-%#lx (K) and rsp is %#lx",
                   this->Stack->GetStackBottom(), this->Stack->GetStackTop(),
                   this->Registers.rsp);
 #elif defined(a32)
         debug("Thread EntryPoint: %#lx => RIP: %#lx",
               this->EntryPoint, this->Registers.eip);
         if (Parent->Security.ExecutionMode == TaskExecutionMode::User)
             debug("Thread stack region is %#lx-%#lx (U) and rsp is %#lx",
                   this->Stack->GetStackBottom(), this->Stack->GetStackTop(),
                   this->Registers.esp);
         else
             debug("Thread stack region is %#lx-%#lx (K) and rsp is %#lx",
                   this->Stack->GetStackBottom(), this->Stack->GetStackTop(),
                   this->Registers.esp);
 #elif defined(aa64)
 #endif
         debug("Created %s thread \"%s\"(%d) in process \"%s\"(%d)",
               this->Security.ExecutionMode == TaskExecutionMode::User ? "user" : "kernel",
               this->Name, this->ID, this->Parent->Name,
               this->Parent->ID);
 #endif
         this->AllocatedMemory += sizeof(TCB);
         this->AllocatedMemory += strlen(this->Parent->Name) + 1;
         this->AllocatedMemory += sizeof(Memory::StackGuard);
         this->Info.SpawnTime = TimeManager->GetCounter();
         this->Parent->Threads.push_back(this);
         if (this->Parent->Threads.size() == 1 &&
             this->Parent->State == Waiting &&
             ThreadNotReady == false)
         {
             this->Parent->SetState(Ready);
             debug("Setting process \"%s\"(%d) to ready",
                   this->Parent->Name, this->Parent->ID);
         }
     }
References Tasking::_ArchitectureMax, Tasking::_ArchitectureMin, Tasking::_CompatibilityMax, Tasking::_CompatibilityMin, AllocatedMemory, Tasking::TaskInfo::Architecture, assert, Compatibility, Tasking::TaskInfo::Compatibility, ctx, debug, DumpData(), EntryPoint, ExitCode, fixme, FSBase, GDT_KERNEL_CODE, GDT_KERNEL_DATA, GDT_USER_CODE, GDT_USER_DATA, Time::time::GetCounter(), Tasking::Task::GetCurrentProcess(), Memory::StackGuard::GetStackBottom(), Memory::StackGuard::GetStackTop(), GSBase, ID, Info, Tasking::PCB::Info, Tasking::Kernel, Tasking::KILL_CRASH, CPU::x32::MSR_FS_BASE, CPU::x32::MSR_GS_BASE, CPU::x32::MSR_SHADOW_GS_BASE, Name, Tasking::PCB::Name, Tasking::Task::NextTID, Tasking::PCB::PageTable, Parent, POKE, Tasking::Ready, Memory::VirtualMemoryArea::RequestPages(), Tasking::gsTCB::ScPages, Security, Tasking::PCB::Security, SetState(), Tasking::PCB::SetState(), SetupThreadLocalStorage(), SetupUserStack_aarch64(), SetupUserStack_x86_32(), SetupUserStack_x86_64(), Tasking::TaskInfo::SpawnTime, Stack, STACK_SIZE, Tasking::PCB::State, strcpy, strlen(), Tasking::gsTCB::SyscallStack, Tasking::gsTCB::SyscallStackBase, Tasking::System, Tasking::gsTCB::t, Tasking::gsTCB::TempStack, ThreadDoExit(), Tasking::PCB::Threads, TimeManager, TO_PAGES, Tasking::User, vma, and Tasking::Waiting.
~TCB()
Tasking::TCB::~TCB ()
Definition at line 611 of file thread.cpp.
     {
         debug("- %#lx", this);
         /* Remove us from the process list so we
             don't get scheduled anymore */
         std::list<Tasking::TCB *> &Threads = this->Parent->Threads;
         Threads.erase(std::find(Threads.begin(),
                                 Threads.end(),
                                 this));
         /* Free CPU Stack */
         delete this->Stack;
         /* Free all allocated memory */
         delete this->vma;
         /* Free Name */
         delete[] this->Name;
         debug("Thread \"%s\"(%d) destroyed",
               this->Name, this->ID);
     }
References debug, ID, Name, Parent, Stack, Tasking::PCB::Threads, and vma.
Member Function Documentation
Block()
void Tasking::TCB::Block () inline
Definition at line 359 of file task.hpp.
 { State.store(TaskState::Blocked); }
References Tasking::Blocked, and State.
GetContext()
class Task* Tasking::TCB::GetContext () inline
Definition at line 302 of file task.hpp.
 { return ctx; }
References ctx.
Referenced by linux_exit(), and sys_exit().
GetExitCode()
int Tasking::TCB::GetExitCode () inline
Definition at line 354 of file task.hpp.
 { return ExitCode.load(); }
References ExitCode.
Referenced by KernelMainThread().
GetSize()
size_t Tasking::TCB::GetSize ()
Definition at line 147 of file thread.cpp.
     {
         size_t ret = this->AllocatedMemory;
         ret += this->vma->GetAllocatedMemorySize();
         ret += this->Stack->GetSize();
         return ret;
     }
References AllocatedMemory, Memory::VirtualMemoryArea::GetAllocatedMemorySize(), Memory::StackGuard::GetSize(), Stack, and vma.
Rename()
void Tasking::TCB::Rename (const char * name)
Definition at line 84 of file thread.cpp.
     {
         assert(name != nullptr);
         assert(strlen(name) > 0);
         trace("Renaming thread %s to %s",
               this->Name, name);
         if (this->Name)
         {
             this->AllocatedMemory -= strlen(this->Name) + 1;
             delete[] this->Name;
         }
         this->Name = new char[strlen(name) + 1];
         this->AllocatedMemory += strlen(name) + 1;
         strcpy((char *)this->Name, name);
     }
References AllocatedMemory, assert, Name, strcpy, strlen(), and trace.
Referenced by Driver::CreateKernelThread(), KernelMainThread(), linux_fork(), NetworkInterfaceManager::NetworkInterface::StartService(), sys_fork(), and Tasking::Task::Task().
SendSignal()
int Tasking::TCB::SendSignal (int sig)
Definition at line 65 of file thread.cpp.
     {
         return this->Parent->Signals->SendSignal(sig);
     }
References Parent, Tasking::Signal::SendSignal(), and Tasking::PCB::Signals.
SetCritical()
void Tasking::TCB::SetCritical (bool Critical)
Definition at line 114 of file thread.cpp.
     {
         trace("Setting criticality of thread %s to %s",
               this->Name, Critical ? "true" : "false");
         Security.IsCritical = Critical;
         if (this->Parent->Threads.size() == 1)
             this->Parent->Security.IsCritical = Critical;
     }
References Tasking::Critical, Name, Parent, Security, Tasking::PCB::Security, Tasking::PCB::Threads, and trace.
Referenced by Execute::Spawn().
SetDebugMode()
void Tasking::TCB::SetDebugMode (bool Enable)
Definition at line 125 of file thread.cpp.
     {
         trace("Setting debug mode of thread %s to %s",
               this->Name, Enable ? "true" : "false");
         Security.IsDebugEnabled = Enable;
         if (this->Parent->Threads.size() == 1)
             this->Parent->Security.IsDebugEnabled = Enable;
     }
References CPU::Enable, Name, Parent, Security, Tasking::PCB::Security, Tasking::PCB::Threads, and trace.
SetExitCode()
void Tasking::TCB::SetExitCode (int code)
Definition at line 77 of file thread.cpp.
     {
         this->ExitCode.store(code);
         if (this->Parent->Threads.size() == 1)
             this->Parent->ExitCode.store(code);
     }
References ExitCode, Tasking::PCB::ExitCode, Parent, and Tasking::PCB::Threads.
Referenced by Tasking::Task::KillThread(), linux_exit(), and sys_exit().
SetKernelDebugMode()
void Tasking::TCB::SetKernelDebugMode (bool Enable)
Definition at line 136 of file thread.cpp.
     {
         trace("Setting kernel debug mode of thread %s to %s",
               this->Name, Enable ? "true" : "false");
         Security.IsKernelDebugEnabled = Enable;
         if (this->Parent->Threads.size() == 1)
             this->Parent->Security.IsKernelDebugEnabled = Enable;
     }
References CPU::Enable, Name, Parent, Security, Tasking::PCB::Security, Tasking::PCB::Threads, and trace.
SetPriority()
void Tasking::TCB::SetPriority (TaskPriority priority)
Definition at line 103 of file thread.cpp.
     {
         assert(priority >= _PriorityMin);
         // assert(priority <= _PriorityMax);
         trace("Setting priority of thread %s to %d",
               this->Name, priority);
         Info.Priority = priority;
     }
References Tasking::_PriorityMin, assert, Info, Name, Tasking::TaskInfo::Priority, and trace.
Referenced by Tasking::Task::Task().
SetState()
void Tasking::TCB::SetState (TaskState state)
Definition at line 70 of file thread.cpp.
     {
         this->State.store(state);
         if (this->Parent->Threads.size() == 1)
             this->Parent->State.store(state);
     }
References Parent, State, Tasking::PCB::State, and Tasking::PCB::Threads.
Referenced by Tasking::Task::KillThread(), linux_exit(), linux_fork(), Tasking::Task::Sleep(), sys_exit(), sys_fork(), TCB(), and UserModeExceptionHandler().
SetupThreadLocalStorage()
void Tasking::TCB::SetupThreadLocalStorage () private
This function should be called after GS and FS are set up
Definition at line 363 of file thread.cpp.
     {
         if (Parent->TLS.pBase == 0x0)
             return;
         this->TLS = Parent->TLS;
         debug("msz: %ld fsz: %ld",
               this->TLS.Size, this->TLS.fSize);
         // size_t pOffset = this->TLS.vBase - std::tolower(this->TLS.vBase);
         size_t tlsFullSize = sizeof(uintptr_t) + this->TLS.Size;
         /* 2 guard pages */
         size_t tlsPages = 1 + TO_PAGES(tlsFullSize) + 1;
         void *opTLS = this->vma->RequestPages(tlsPages);
         void *pTLS = (void *)(PAGE_SIZE + uintptr_t(opTLS));
         this->TLS.pBase = uintptr_t(pTLS);
         memcpy(pTLS, (void *)this->TLS.pBase,
                this->TLS.Size);
         size_t restBytes = this->TLS.Size - this->TLS.fSize;
         if (restBytes)
         {
             memset((void *)(uintptr_t(pTLS) + this->TLS.Size),
                    0, restBytes);
         }
         Memory::Virtual vmm(this->Parent->PageTable);
         /* Map guard pages */
         vmm.Remap((void *)(uintptr_t(pTLS) - PAGE_SIZE), opTLS, Memory::P);
         vmm.Remap((void *)(uintptr_t(pTLS) + this->TLS.Size), opTLS, Memory::P);
         /* Map TLS */
         vmm.Map(pTLS, pTLS, this->TLS.Size, Memory::RW | Memory::US);
         uintptr_t *pTLSPointer = (uintptr_t *)this->TLS.pBase + this->TLS.Size;
         *pTLSPointer = this->TLS.pBase + this->TLS.Size;
         this->GSBase = r_cst(uintptr_t, pTLSPointer);
         this->FSBase = r_cst(uintptr_t, pTLSPointer);
     }
References debug, FSBase, Tasking::ThreadLocalStorage::fSize, Memory::Virtual::Map(), memcpy(), memset(), Memory::P, PAGE_SIZE, Tasking::PCB::PageTable, Parent, Tasking::ThreadLocalStorage::pBase, Memory::Virtual::Remap(), Memory::VirtualMemoryArea::RequestPages(), Memory::RW, Tasking::ThreadLocalStorage::Size, TLS, Tasking::PCB::TLS, TO_PAGES, Memory::US, and vma.
Referenced by TCB().
SetupUserStack_aarch64()
void Tasking::TCB::SetupUserStack_aarch64 (const char ** argv, const char ** envp, const std::vector< AuxiliaryVector > & auxv) private
Definition at line 356 of file thread.cpp.
     {
         fixme("Not implemented");
     }
References fixme.
Referenced by TCB().
SetupUserStack_x86_32()
void Tasking::TCB::SetupUserStack_x86_32 (const char ** argv, const char ** envp, const std::vector< AuxiliaryVector > & auxv) private
Definition at line 349 of file thread.cpp.
     {
         fixme("Not implemented");
     }
References fixme.
Referenced by TCB().
SetupUserStack_x86_64()
void Tasking::TCB::SetupUserStack_x86_64 (const char ** argv, const char ** envp, const std::vector< AuxiliaryVector > & auxv) private
Referenced by TCB().
SYSV_ABI_Call()
void Tasking::TCB::SYSV_ABI_Call (uintptr_t Arg1 = 0, uintptr_t Arg2 = 0, uintptr_t Arg3 = 0, uintptr_t Arg4 = 0, uintptr_t Arg5 = 0, uintptr_t Arg6 = 0, void * Function = nullptr)
Definition at line 155 of file thread.cpp.
     {
 #if defined(a64)
         this->Registers.rdi = Arg1;
         this->Registers.rsi = Arg2;
         this->Registers.rdx = Arg3;
         this->Registers.rcx = Arg4;
         this->Registers.r8 = Arg5;
         this->Registers.r9 = Arg6;
         if (Function != nullptr)
             this->Registers.rip = (uint64_t)Function;
 #elif defined(a32)
         this->Registers.eax = Arg1;
         this->Registers.ebx = Arg2;
         this->Registers.ecx = Arg3;
         this->Registers.edx = Arg4;
         this->Registers.esi = Arg5;
         this->Registers.edi = Arg6;
         if (Function != nullptr)
             this->Registers.eip = (uint32_t)Function;
 #else
 #warning "SYSV ABI not implemented for this architecture"
 #endif
     }
Referenced by Driver::CreateKernelThread().
Unblock()
void Tasking::TCB::Unblock () inline
Definition at line 360 of file task.hpp.
 { State.store(TaskState::Ready); }
References Tasking::Ready, and State.
Field Documentation
AllocatedMemory
size_t Tasking::TCB::AllocatedMemory = 0 private
This variable is used to store the amount of allocated memory for the process. This includes the memory allocated for the class itself, etc...
Note
Allocated memory is not the same as used memory.
Definition at line 281 of file task.hpp.
Referenced by GetSize(), Rename(), and TCB().
ctx
class Task* Tasking::TCB::ctx = nullptr private
Definition at line 269 of file task.hpp.
Referenced by GetContext(), and TCB().
EntryPoint
IP Tasking::TCB::EntryPoint = 0
Definition at line 308 of file task.hpp.
Referenced by TCB().
ErrorNumber
int Tasking::TCB::ErrorNumber
Definition at line 313 of file task.hpp.
ExitCode
std::atomic_int Tasking::TCB::ExitCode
Definition at line 311 of file task.hpp.
Referenced by GetExitCode(), SetExitCode(), and TCB().
ID
TID Tasking::TCB::ID = -1
Definition at line 305 of file task.hpp.
Referenced by Driver::CreateKernelThread(), DisplayDetailsScreen(), Tasking::Task::KillThread(), linux_exit(), linux_fork(), linux_set_tid_address(), Tasking::Task::RemoveThread(), Execute::Spawn(), sys_exit(), sys_fork(), TCB(), UserModeExceptionHandler(), Tasking::Task::WaitForThread(), Tasking::Task::WaitForThreadStatus(), and ~TCB().
Info
TaskInfo Tasking::TCB::Info {}
Definition at line 339 of file task.hpp.
Referenced by linux_fork(), SetPriority(), Tasking::Task::Sleep(), sys_fork(), Tasking::Task::Task(), and TCB().
struct { ... } Tasking::TCB::Linux
Referenced by linux_set_tid_address().
Name
const char* Tasking::TCB::Name = nullptr
Definition at line 306 of file task.hpp.
Referenced by DisplayDetailsScreen(), Tasking::Task::KillThread(), linux_exit(), linux_fork(), Tasking::Task::RemoveThread(), Rename(), SetCritical(), SetDebugMode(), SetKernelDebugMode(), SetPriority(), sys_exit(), sys_fork(), Tasking::Task::Task(), TCB(), UserModeExceptionHandler(), Tasking::Task::WaitForThread(), Tasking::Task::WaitForThreadStatus(), and ~TCB().
Parent
class PCB* Tasking::TCB::Parent = nullptr
Definition at line 307 of file task.hpp.
Referenced by linux_fork(), linux_tgkill(), Tasking::Task::RemoveThread(), SendSignal(), SetCritical(), SetDebugMode(), SetExitCode(), SetKernelDebugMode(), SetState(), SetupThreadLocalStorage(), Tasking::Task::Sleep(), TCB(), and ~TCB().
__aligned { ... } Tasking::TCB::Security
Referenced by linux_fork(), SetCritical(), SetDebugMode(), SetKernelDebugMode(), sys_fork(), and TCB().
Stack
Memory::StackGuard* Tasking::TCB::Stack
Definition at line 317 of file task.hpp.
Referenced by GetSize(), linux_fork(), sys_fork(), TCB(), UserModeExceptionHandler(), and ~TCB().
State
std::atomic<TaskState> Tasking::TCB::State = TaskState::Waiting
Definition at line 312 of file task.hpp.
Referenced by Block(), Tasking::Task::RemoveProcess(), SetState(), Unblock(), Tasking::Task::WaitForThread(), and Tasking::Task::WaitForThreadStatus().
TLS
ThreadLocalStorage Tasking::TCB::TLS {}
Definition at line 340 of file task.hpp.
Referenced by SetupThreadLocalStorage().
vma
Memory::VirtualMemoryArea* Tasking::TCB::vma
Definition at line 316 of file task.hpp.
Referenced by GetSize(), SetupThreadLocalStorage(), TCB(), and ~TCB().
The documentation for this class was generated from the following files:
Kernel/include/task.hpp
Kernel/tasking/thread.cpp