Fennix: Userspace/musl/src/stdio/ftell.c File Reference
ftell.c File Reference
#include "stdio_impl.h"
#include <limits.h>
#include <errno.h>
Functions
off_t __ftello_unlocked (FILE *f)
off_t __ftello (FILE *f)
long ftell (FILE *f)
weak_alias (__ftello, ftello)
Function Documentation
__ftello()
off_t __ftello (FILE * f)
Definition at line 20 of file ftell.c.
 {
     off_t pos;
     FLOCK(f);
     pos = __ftello_unlocked(f);
     FUNLOCK(f);
     return pos;
 }
References __ftello_unlocked(), f, FLOCK, FUNLOCK, and pos.
Referenced by fgetpos(), and ftell().
__ftello_unlocked()
off_t __ftello_unlocked (FILE * f)
Definition at line 5 of file ftell.c.
 {
     off_t pos = f->seek(f, 0,
         (f->flags & F_APP) && f->wpos != f->wbase
         ? SEEK_END : SEEK_CUR);
     if (pos < 0) return pos;
     /* Adjust for data in buffer. */
     if (f->rend)
         pos += f->rpos - f->rend;
     else if (f->wbase)
         pos += f->wpos - f->wbase;
     return pos;
 }
References f, F_APP, pos, SEEK_CUR, and SEEK_END.
Referenced by __ftello().
ftell()
long ftell (FILE * f)
Definition at line 29 of file ftell.c.
 {
     off_t pos = __ftello(f);
     if (pos > LONG_MAX) {
         errno = EOVERFLOW;
         return -1;
     }
     return pos;
 }
References __ftello(), EOVERFLOW, errno, f, LONG_MAX, and pos.
Referenced by G_DoSaveGame(), M_FileLength(), saveg_read_pad(), and saveg_write_pad().
weak_alias()
weak_alias (__ftello , ftello)