Fennix Userspace: Userspace/apps/base/busybox/coreutils/date.c File Reference
date.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
Macros
#define date_buf bb_common_bufsiz1
Enumerations
enum {
OPT_RFC2822 = (1 << 0) , OPT_SET = (1 << 1) , OPT_UTC = (1 << 2) , OPT_DATE = (1 << 3) ,
OPT_REFERENCE = (1 << 4) , OPT_ISO8601 = (1 << 5) * ENABLE_FEATURE_DATE_ISOFMT , OPT_STR2DT = (1 << 6) * ENABLE_FEATURE_DATE_ISOFMT
}
Functions
int date_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
date_buf
#define date_buf bb_common_bufsiz1
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_RFC2822
OPT_SET
OPT_UTC
OPT_DATE
OPT_REFERENCE
OPT_ISO8601
OPT_STR2DT
Definition at line 133 of file date.c.
      {
     OPT_RFC2822   = (1 << 0), /* R */
     OPT_SET       = (1 << 1), /* s */
     OPT_UTC       = (1 << 2), /* u */
     OPT_DATE      = (1 << 3), /* d */
     OPT_REFERENCE = (1 << 4), /* r */
     OPT_ISO8601   = (1 << 5) * ENABLE_FEATURE_DATE_ISOFMT, /* I */
     OPT_STR2DT    = (1 << 6) * ENABLE_FEATURE_DATE_ISOFMT, /* D */
 };
Function Documentation
date_main()
int date_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 163 of file date.c.
 {
     struct timespec ts;
     struct tm tm_time;
     char buf_fmt_dt2str[64];
     unsigned opt;
     int isofmt = -1;
     char *date_str;
     char *fmt_dt2str;
     char *fmt_str2dt;
     char *filename;
     char *isofmt_arg = NULL;
     opt = getopt32long(argv, "^"
             "Rs:ud:r:"
             IF_FEATURE_DATE_ISOFMT("I::D:")
             "\0"
             "d--s:s--d"
             IF_FEATURE_DATE_ISOFMT(":R--I:I--R"),
             date_longopts,
             &date_str, &date_str, &filename
             IF_FEATURE_DATE_ISOFMT(, &isofmt_arg, &fmt_str2dt)
     );
     argv += optind;
     if (opt & OPT_UTC)
         putenv((char*)"TZ=UTC0");
     if (ENABLE_FEATURE_DATE_ISOFMT && (opt & OPT_ISO8601)) {
         isofmt = 0; /* default is date */
         if (isofmt_arg) {
             static const char isoformats[] ALIGN1 =
                 "date\0""hours\0""minutes\0""seconds\0ns\0";
             isofmt = index_in_substrings(isoformats, isofmt_arg);
             if (isofmt < 0)
                 bb_show_usage();
         }
     }
     fmt_dt2str = NULL;
     if (argv[0] && argv[0][0] == '+') {
         fmt_dt2str = &argv[0][1]; /* skip over the '+' */
         argv++;
     }
     if (!(opt & (OPT_SET | OPT_DATE))) { /* neither -s TIME nor -d TIME? */
         opt |= OPT_SET;
         date_str = argv[0]; /* can be NULL */
         if (date_str) {
 #if ENABLE_FEATURE_DATE_COMPAT
             int len = strspn(date_str, "0123456789");
             if (date_str[len] == '\0'
              || (date_str[len] == '.'
                 && isdigit(date_str[len+1])
                 && isdigit(date_str[len+2])
                 && date_str[len+3] == '\0'
                 )
             ) {
                 /* Dreaded MMDDhhmm[[CC]YY][.ss] format!
                  * It does not match -d or -s format.
                  * Some users actually do use it.
                  */
                 len -= 8;
                 if (len < 0 || len > 4 || (len & 1))
                     bb_error_msg_and_die(bb_msg_invalid_date, date_str);
                 if (len != 0) { /* move YY or CCYY to front */
                     char buf[4];
                     memcpy(buf, date_str + 8, len);
                     memmove(date_str + len, date_str, 8);
                     memcpy(date_str, buf, len);
                 }
             }
 #endif
             argv++;
         }
     }
     if (*argv)
         bb_show_usage();
     /* Now we have parsed all the information except the date format
      * which depends on whether the clock is being set or read */
     if (opt & OPT_REFERENCE) {
         struct stat statbuf;
         xstat(filename, &statbuf);
         ts.tv_sec = statbuf.st_mtime;
 #if ENABLE_FEATURE_DATE_NANO
         ts.tv_nsec = statbuf.st_mtim.tv_nsec;
         /* Some toolchains use .st_mtimensec instead of st_mtim.tv_nsec.
          * If you need #define _SVID_SOURCE 1 to enable st_mtim.tv_nsec,
          * drop a mail to project mailing list please
          */
 #endif
     } else {
 #if ENABLE_FEATURE_DATE_NANO
         clock_gettime(CLOCK_REALTIME, &ts);
 #else
         time(&ts.tv_sec);
 #endif
     }
 #if !ENABLE_FEATURE_DATE_NANO
     ts.tv_nsec = 0;
 #endif
     localtime_r(&ts.tv_sec, &tm_time);
     /* If date string is given, update tm_time, and maybe set date */
     if (date_str != NULL) {
         int check_dst = 1;
         /* Zero out fields - take her back to midnight! */
         tm_time.tm_sec = 0;
         tm_time.tm_min = 0;
         tm_time.tm_hour = 0;
         /* Process any date input to UNIX time since 1 Jan 1970 */
         if (ENABLE_FEATURE_DATE_ISOFMT && (opt & OPT_STR2DT)) {
             if (strptime(date_str, fmt_str2dt, &tm_time) == NULL)
                 bb_error_msg_and_die(bb_msg_invalid_date, date_str);
         } else {
             check_dst = parse_datestr(date_str, &tm_time);
         }
         /* Correct any day of week and day of year etc. fields */
         /* Be sure to recheck dst (but not if date is UTC) */
         if (check_dst)
             tm_time.tm_isdst = -1;
         ts.tv_sec = validate_tm_time(date_str, &tm_time);
         ts.tv_nsec = 0;
         /* if setting time, set it */
         if ((opt & OPT_SET) && clock_settime(CLOCK_REALTIME, &ts) < 0) {
             bb_simple_perror_msg("can't set date");
         }
     }
     /* Display output */
     /* Deal with format string */
     if (fmt_dt2str == NULL) {
         int i;
         fmt_dt2str = buf_fmt_dt2str;
         if (ENABLE_FEATURE_DATE_ISOFMT && isofmt >= 0) {
             /* -I[SPEC]: 0:date 1:hours 2:minutes 3:seconds 4:ns*/
             strcpy(fmt_dt2str, "%Y-%m-%dT%H:%M:%S");
             i = 8 + 3 * isofmt;
             if (isofmt != 0) {
                 int n;
                 if (isofmt == 4) {
                     i -= 3;
                     i += sprintf(&fmt_dt2str[i], ",%09u", (unsigned)ts.tv_nsec);
                 }
                 /* %z prints "+hhmm" timezone, but coreutils-8.30 prints "+hh:mm"! */
                 /* ...therefore this atrocity: */
                 n = strftime(&fmt_dt2str[i], 8, "%z", &tm_time);
                 i += n;
                 if (n == 5 && (fmt_dt2str[i-5] == '+' || fmt_dt2str[i-5] == '-')) {
                     /* "mm" -> ":mm" */
                     fmt_dt2str[i    ] = fmt_dt2str[i - 1];
                     fmt_dt2str[i - 1] = fmt_dt2str[i - 2];
                     fmt_dt2str[i - 2] = ':';
                     i++;
                 }
             }
             fmt_dt2str[i] = '\0';
         } else if (opt & OPT_RFC2822) {
             /* -R. undo busybox.c setlocale */
             if (ENABLE_LOCALE_SUPPORT)
                 setlocale(LC_TIME, "C");
             fmt_dt2str = (char*)"%a, %d %b %Y %H:%M:%S %z";
         } else { /* default case */
             fmt_dt2str = (char*)"%a %b %e %H:%M:%S %Z %Y";
         }
     }
 #if ENABLE_FEATURE_DATE_NANO
     else {
         /* User-specified fmt_dt2str */
         /* Search for and process "%N" */
         char *p = fmt_dt2str;
         while ((p = strchr(p, '%')) != NULL) {
             int n, m;
             unsigned pres, scale;
             p++;
             if (*p == '%') {
                 p++;
                 continue;
             }
             n = strspn(p, "0123456789");
             if (p[n] != 'N') {
                 p += n;
                 continue;
             }
             /* We have "%[nnn]N" */
             p[-1] = '\0';
             p[n] = '\0';
             scale = 1;
             pres = 9;
             if (n) {
                 pres = xatoi_positive(p);
                 if (pres == 0)
                     pres = 9;
                 m = 9 - pres;
                 while (--m >= 0)
                     scale *= 10;
             }
             m = p - fmt_dt2str;
             p += n + 1;
             fmt_dt2str = xasprintf("%s%0*u%s", fmt_dt2str, pres, (unsigned)ts.tv_nsec / scale, p);
             p = fmt_dt2str + m;
         }
     }
 #endif
 #define date_buf bb_common_bufsiz1
     setup_common_bufsiz();
     if (*fmt_dt2str == '\0') {
         /* With no format string, just print a blank line */
         date_buf[0] = '\0';
     } else {
         /* Generate output string */
         strftime(date_buf, COMMON_BUFSIZE, fmt_dt2str, &tm_time);
     }
     puts(date_buf);
     return EXIT_SUCCESS;
 }
References ALIGN1, argv, bb_error_msg_and_die(), bb_show_usage(), bb_simple_perror_msg(), buf, clock_settime(), date_buf, date_str, EXIT_SUCCESS, filename, getopt32long, i, index_in_substrings(), isdigit, LC_TIME, memcpy(), memmove(), n, NULL, opt, OPT_DATE, OPT_ISO8601, OPT_REFERENCE, OPT_RFC2822, OPT_SET, OPT_STR2DT, OPT_UTC, optind, p, parse_datestr(), putenv(), puts(), scale, setlocale, sprintf(), stat::st_mtim, strchr(), strcpy(), strftime(), strptime(), strspn(), time(), tm::tm_hour, tm::tm_isdst, tm::tm_min, tm::tm_sec, timespec::tv_nsec, timespec::tv_sec, validate_tm_time(), xasprintf(), xatoi_positive(), and xstat().