Fennix: Userspace/mlibc/tests/posix/posix_spawn.c File Reference
posix_spawn.c File Reference
#include <stdlib.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <spawn.h>
#include <sys/wait.h>
Functions
void run_cmd (char *cmd)
int main ()
Variables
char ** environ
Function Documentation
main()
int main (void)
Definition at line 35 of file posix_spawn.c.
            {
     run_cmd(":");
     return 0;
 }
References run_cmd().
run_cmd()
void run_cmd (char * cmd)
Definition at line 12 of file posix_spawn.c.
 {
     pid_t pid;
     char *argv[] = {"sh", "-c", cmd, NULL};
     int status;
     printf("Run command: %s\n", cmd);
     status = posix_spawn(&pid, "/bin/sh", NULL, NULL, argv, environ);
     if(status == 0) {
         printf("Child pid: %i\n", pid);
         if(waitpid(pid, &status, 0) != -1) {
             printf("Child exited with status %i\n", status);
         printf("Child exit status: %i\n", WEXITSTATUS(status));
         assert(WEXITSTATUS(status) == 0);
         } else {
             perror("waitpid");
         assert(0 == 1);
         }
     } else {
         printf("posix_spawn: %s\n", strerror(status));
     assert(0 == 1);
     }
 }
References assert, environ, NULL, perror(), posix_spawn(), printf, mlibc::status, strerror(), waitpid(), and WEXITSTATUS.
Referenced by main().
Variable Documentation
environ
char** environ extern
Definition at line 41 of file lib.c.
Referenced by anonymous_namespace{environment.cpp}::assign_variable(), execl(), execv(), execvp(), anonymous_namespace{environment.cpp}::find_environ_index(), getenv(), popen(), run_cmd(), anonymous_namespace{environment.cpp}::unassign_variable(), and anonymous_namespace{environment.cpp}::update_vector().