Fennix Userspace: Userspace/apps/base/busybox/coreutils/realpath.c File Reference
realpath.c File Reference
#include "libbb.h"
Functions
int realpath_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
realpath_main()
int realpath_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 31 of file realpath.c.
 {
     int retval = EXIT_SUCCESS;
     if (!*++argv) {
         bb_show_usage();
     }
     do {
         /* NOFORK: only one alloc is allowed; must free */
         char *resolved_path = xmalloc_realpath_coreutils(*argv);
         if (resolved_path != NULL) {
             puts(resolved_path);
             free(resolved_path);
         } else {
             retval = EXIT_FAILURE;
             bb_simple_perror_msg(*argv);
         }
     } while (*++argv);
     fflush_stdout_and_exit(retval);
 }
References argv, bb_show_usage(), bb_simple_perror_msg(), EXIT_FAILURE, EXIT_SUCCESS, fflush_stdout_and_exit(), free, NULL, puts(), retval, and xmalloc_realpath_coreutils().