Fennix Userspace: Userspace/apps/base/busybox/util-linux/mdev.c File Reference
mdev.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include "xregex.h"
#include <linux/netlink.h>
#include <syslog.h>
Data Structures
struct envmatch
struct rule
struct globals
Macros
#define DEBUG_LVL 2
#define dbg1(...) do { if (G.verbose) bb_error_msg(__VA_ARGS__); } while(0)
#define dbg1s(msg) do { if (G.verbose) bb_simple_error_msg(msg); } while(0)
#define dbg2(...) do { if (G.verbose >= 2) bb_error_msg(__VA_ARGS__); } while(0)
#define dbg2s(msg) do { if (G.verbose >= 2) bb_simple_error_msg(msg); } while(0)
#define dbg3(...) ((void)0)
#define dbg3s(msg) ((void)0)
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define MAX_SYSFS_DEPTH 3
#define SCRATCH_SIZE 128
#define next_rule() (&G.cur_rule)
Enumerations
enum { OP_add , OP_remove }
Functions
static void mkdir_recursive (char *name)
static char * build_alias (char *alias, const char *device_name)
static void make_device (char *device_name, char *path, int operation)
static ssize_t readlink2 (char *buf, size_t bufsize)
static int FAST_FUNC fileAction (struct recursive_state *state, const char *fileName, struct stat *statbuf UNUSED_PARAM)
static int FAST_FUNC dirAction (struct recursive_state *state, const char *fileName UNUSED_PARAM, struct stat *statbuf UNUSED_PARAM)
static void load_firmware (const char *firmware, const char *sysfs_path)
static char * curtime (void)
static void open_mdev_log (const char *seq, unsigned my_pid)
static int wait_for_seqfile (unsigned expected_seq)
static void signal_mdevs (unsigned my_pid)
static void process_action (char *temp, unsigned my_pid)
static void initial_scan (char *temp)
int mdev_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const char keywords[] ALIGN1 = "add\0remove\0"
struct globals FIX_ALIASING
Data Structure Documentation
envmatch
struct envmatch
Definition at line 278 of file mdev.c.
Data Fields
char * envname
regex_t match
struct envmatch * next
rule
struct rule
Definition at line 284 of file mdev.c.
Data Fields
struct envmatch * envmatch
char * envvar
bool keep_matching
int maj
regex_t match
int min0
int min1
mode_t mode
bool regex_compiled
char * ren_mov
struct bb_uidgid_t ugid
Macro Definition Documentation
dbg1
#define dbg1 (...) do { if (G.verbose) bb_error_msg(__VA_ARGS__); } while(0)
Definition at line 254 of file mdev.c.
dbg1s
#define dbg1s (msg) do { if (G.verbose) bb_simple_error_msg(msg); } while(0)
Definition at line 255 of file mdev.c.
dbg2
#define dbg2 (...) do { if (G.verbose >= 2) bb_error_msg(__VA_ARGS__); } while(0)
Definition at line 261 of file mdev.c.
dbg2s
#define dbg2s (msg) do { if (G.verbose >= 2) bb_simple_error_msg(msg); } while(0)
Definition at line 262 of file mdev.c.
dbg3
#define dbg3 (...) ((void)0)
Definition at line 271 of file mdev.c.
dbg3s
#define dbg3s (msg) ((void)0)
Definition at line 272 of file mdev.c.
DEBUG_LVL
#define DEBUG_LVL 2
Definition at line 251 of file mdev.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 311 of file mdev.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    IF_NOT_FEATURE_MDEV_CONF(G.cur_rule.maj = -1;) \
    IF_NOT_FEATURE_MDEV_CONF(G.cur_rule.mode = 0660;) \
} while (0)
Definition at line 312 of file mdev.c.
MAX_SYSFS_DEPTH
#define MAX_SYSFS_DEPTH 3
Definition at line 320 of file mdev.c.
next_rule
#define next_rule () (&G.cur_rule)
Definition at line 525 of file mdev.c.
SCRATCH_SIZE
#define SCRATCH_SIZE 128
Definition at line 323 of file mdev.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OP_add
OP_remove
Definition at line 276 of file mdev.c.
 { OP_add, OP_remove };
Function Documentation
build_alias()
static char* build_alias (char * alias, const char * device_name) static
Definition at line 545 of file mdev.c.
 {
     char *dest;
     /* ">bar/": rename to bar/device_name */
     /* ">bar[/]baz": rename to bar[/]baz */
     dest = strrchr(alias, '/');
     if (dest) { /* ">bar/[baz]" ? */
         *dest = '\0'; /* mkdir bar */
         mkdir_recursive(alias);
         *dest = '/';
         if (dest[1] == '\0') { /* ">bar/" => ">bar/device_name" */
             dest = alias;
             alias = concat_path_file(alias, device_name);
             free(dest);
         }
     }
     return alias;
 }
References concat_path_file(), device_name, free, mkdir_recursive(), and strrchr().
Referenced by make_device().
curtime()
static char* curtime (void) static
Definition at line 963 of file mdev.c.
 {
     struct timeval tv;
     xgettimeofday(&tv);
     sprintf(
         strftime_HHMMSS(G.timestr, sizeof(G.timestr), &tv.tv_sec),
         ".%06u",
         (unsigned)tv.tv_usec
     );
     return G.timestr;
 }
References G, sprintf(), strftime_HHMMSS(), timeval::tv_sec, timeval::tv_usec, and xgettimeofday().
Referenced by mdev_main(), process_action(), and wait_for_seqfile().
dirAction()
static int FAST_FUNC dirAction (struct recursive_state * state, const char *fileName UNUSED_PARAM, struct stat *statbuf UNUSED_PARAM) static
Definition at line 889 of file mdev.c.
 {
     return (state->depth >= MAX_SYSFS_DEPTH ? SKIP : TRUE);
 }
References MAX_SYSFS_DEPTH, SKIP, state, and TRUE.
Referenced by initial_scan(), and recursive_action().
fileAction()
static int FAST_FUNC fileAction (struct recursive_state * state, const char * fileName, struct stat *statbuf UNUSED_PARAM) static
Definition at line 847 of file mdev.c.
 {
     size_t len = strlen(fileName) - 4; /* can't underflow */
     char *path = state->userData;   /* char array[PATH_MAX + SCRATCH_SIZE] */
     char subsys[PATH_MAX];
     int res;
     /* Is it a ".../dev" file? (len check is for paranoid reasons) */
     if (strcmp(fileName + len, "/dev") != 0 || len >= PATH_MAX - 32)
         return FALSE; /* not .../dev */
     strcpy(path, fileName);
     path[len] = '\0';
     /* Read ".../subsystem" symlink in the same directory where ".../dev" is */
     strcpy(subsys, path);
     strcpy(subsys + len, "/subsystem");
     res = readlink2(subsys, sizeof(subsys)-1);
     if (res > 0) {
         subsys[res] = '\0';
         free(G.subsystem);
         if (G.subsys_env) {
             bb_unsetenv_and_free(G.subsys_env);
             G.subsys_env = NULL;
         }
         /* Set G.subsystem and $SUBSYSTEM from symlink's last component */
         G.subsystem = strrchr(subsys, '/');
         if (G.subsystem) {
             G.subsystem = xstrdup(G.subsystem + 1);
             G.subsys_env = xasprintf("%s=%s", "SUBSYSTEM", G.subsystem);
             putenv(G.subsys_env);
         }
     }
     make_device(/*DEVNAME:*/ NULL, path, OP_add);
     return TRUE;
 }
References bb_unsetenv_and_free(), FALSE, fileName, free, G, make_device(), NULL, OP_add, PATH_MAX, putenv(), readlink2(), state, strcmp, strcpy(), strlen(), strrchr(), TRUE, xasprintf(), and xstrdup().
Referenced by initial_scan().
initial_scan()
static void initial_scan (char * temp) static
Definition at line 1136 of file mdev.c.
 {
     struct stat st;
     xstat("/", &st);
     G.root_major = major(st.st_dev);
     G.root_minor = minor(st.st_dev);
     putenv((char*)"ACTION=add");
     /* Create all devices from /sys/dev hierarchy */
     recursive_action("/sys/dev",
              ACTION_RECURSE | ACTION_FOLLOWLINKS,
              fileAction, dirAction, temp);
 }
References ACTION_FOLLOWLINKS, ACTION_RECURSE, dirAction(), fileAction(), G, major, minor, putenv(), recursive_action(), and xstat().
Referenced by mdev_main().
load_firmware()
static void load_firmware (const char * firmware, const char * sysfs_path) static
Definition at line 907 of file mdev.c.
 {
     int cnt;
     int firmware_fd, loading_fd;
     /* check for /lib/firmware/$FIRMWARE */
     firmware_fd = -1;
     if (chdir("/lib/firmware") == 0)
         firmware_fd = open(firmware, O_RDONLY); /* can fail */
     /* check for /sys/$DEVPATH/loading ... give 30 seconds to appear */
     xchdir(sysfs_path);
     for (cnt = 0; cnt < 30; ++cnt) {
         loading_fd = open("loading", O_WRONLY);
         if (loading_fd >= 0)
             goto loading;
         sleep1();
     }
     goto out;
  loading:
     cnt = 0;
     if (firmware_fd >= 0) {
         int data_fd;
         /* tell kernel we're loading by "echo 1 > /sys/$DEVPATH/loading" */
         if (full_write(loading_fd, "1", 1) != 1)
             goto out;
         /* load firmware into /sys/$DEVPATH/data */
         data_fd = open("data", O_WRONLY);
         if (data_fd < 0)
             goto out;
         cnt = bb_copyfd_eof(firmware_fd, data_fd);
         if (ENABLE_FEATURE_CLEAN_UP)
             close(data_fd);
     }
     /* Tell kernel result by "echo [0|-1] > /sys/$DEVPATH/loading"
      * Note: we emit -1 also if firmware file wasn't found.
      * There are cases when otherwise kernel would wait for minutes
      * before timing out.
      */
     if (cnt > 0)
         full_write(loading_fd, "0", 1);
     else
         full_write(loading_fd, "-1", 2);
  out:
     xchdir("/dev");
     if (ENABLE_FEATURE_CLEAN_UP) {
         close(firmware_fd);
         close(loading_fd);
     }
 }
References bb_copyfd_eof(), chdir(), close(), cnt, full_write(), O_RDONLY, O_WRONLY, open(), out(), sleep1(), and xchdir().
Referenced by process_action().
make_device()
static void make_device (char * device_name, char * path, int operation) static
Definition at line 574 of file mdev.c.
 {
     int major, minor, type, len;
     char *path_end = path + strlen(path);
     /* Try to read major/minor string.  Note that the kernel puts \n after
      * the data, so we don't need to worry about null terminating the string
      * because sscanf() will stop at the first nondigit, which \n is.
      * We also depend on path having writeable space after it.
      */
     major = -1;
     if (operation == OP_add) {
         strcpy(path_end, "/dev");
         len = open_read_close(path, path_end + 1, SCRATCH_SIZE - 1);
         *path_end = '\0';
         if (len < 1) {
             if (!ENABLE_FEATURE_MDEV_EXEC)
                 return;
             /* no "dev" file, but we can still run scripts
              * based on device name */
         } else if (sscanf(path_end + 1, "%u:%u", &major, &minor) == 2) {
             dbg1("dev %u,%u", major, minor);
         } else {
             major = -1;
         }
     }
     /* else: for delete, -1 still deletes the node, but < -1 suppresses that */
     /* Determine device name */
     if (!device_name) {
         /*
          * There was no $DEVNAME envvar (for example, mdev -s never has).
          * But it is very useful: it contains the *path*, not only basename,
          * Thankfully, uevent file has it.
          * Example of .../sound/card0/controlC0/uevent file on Linux-3.7.7:
          * MAJOR=116
          * MINOR=7
          * DEVNAME=snd/controlC0
          */
         strcpy(path_end, "/uevent");
         len = open_read_close(path, path_end + 1, SCRATCH_SIZE - 1);
         if (len < 0)
             len = 0;
         *path_end = '\0';
         path_end[1 + len] = '\0';
         device_name = strstr(path_end + 1, "\nDEVNAME=");
         if (device_name) {
             device_name += sizeof("\nDEVNAME=")-1;
             strchrnul(device_name, '\n')[0] = '\0';
         } else {
             /* Fall back to just basename */
             device_name = (char*) bb_basename(path);
         }
     }
     /* Determine device type */
     /*
      * http://kernel.org/doc/pending/hotplug.txt says that only
      * "/sys/block/..." is for block devices. "/sys/bus" etc is not.
      * But since 2.6.25 block devices are also in /sys/class/block.
      * We use strstr("/block/") to forestall future surprises.
      */
     type = S_IFCHR;
     if (strstr(path, "/block/") || (G.subsystem && is_prefixed_with(G.subsystem, "block")))
         type = S_IFBLK;
 #if ENABLE_FEATURE_MDEV_CONF
     G.rule_idx = 0; /* restart from the beginning (think mdev -s) */
 #endif
     for (;;) {
         const char *str_to_match;
         regmatch_t off[1 + 9 * ENABLE_FEATURE_MDEV_RENAME_REGEXP];
         char *command;
         char *alias;
         char aliaslink = aliaslink; /* for compiler */
         char *node_name;
         const struct rule *rule;
         str_to_match = device_name;
         rule = next_rule();
 #if ENABLE_FEATURE_MDEV_CONF
         if (!env_matches(rule->envmatch))
             continue;
         if (rule->maj >= 0) {  /* @maj,min rule */
             if (major != rule->maj)
                 continue;
             if (minor < rule->min0 || minor > rule->min1)
                 continue;
             memset(off, 0, sizeof(off));
             goto rule_matches;
         }
         if (rule->envvar) { /* $envvar=regex rule */
             str_to_match = getenv(rule->envvar);
             dbg3("getenv('%s'):'%s'", rule->envvar, str_to_match);
             if (!str_to_match)
                 continue;
         }
         /* else: str_to_match = device_name */
         if (rule->regex_compiled) {
             int regex_match = regexec(&rule->match, str_to_match, ARRAY_SIZE(off), off, 0);
             dbg3("regex_match for '%s':%d", str_to_match, regex_match);
             //bb_error_msg("matches:");
             //for (int i = 0; i < ARRAY_SIZE(off); i++) {
             //  if (off[i].rm_so < 0) continue;
             //  bb_error_msg("match %d: '%.*s'\n", i,
             //      (int)(off[i].rm_eo - off[i].rm_so),
             //      device_name + off[i].rm_so);
             //}
             if (regex_match != 0
             /* regexec returns whole pattern as "range" 0 */
              || off[0].rm_so != 0
              || (int)off[0].rm_eo != (int)strlen(str_to_match)
             ) {
                 continue; /* this rule doesn't match */
             }
         }
         /* else: it's final implicit "match-all" rule */
  rule_matches:
         dbg2("rule matched, line %d", G.parser ? G.parser->lineno : -1);
 #endif
         /* Build alias name */
         alias = NULL;
         if (ENABLE_FEATURE_MDEV_RENAME && rule->ren_mov) {
             aliaslink = rule->ren_mov[0];
             if (aliaslink == '!') {
                 /* "!": suppress node creation/deletion */
                 major = -2;
             }
             else if (aliaslink == '>' || aliaslink == '=') {
                 if (ENABLE_FEATURE_MDEV_RENAME_REGEXP) {
                     char *s;
                     char *p;
                     unsigned n;
                     /* substitute %1..9 with off[1..9], if any */
                     n = 0;
                     s = rule->ren_mov;
                     while (*s)
                         if (*s++ == '%')
                             n++;
                     p = alias = xzalloc(strlen(rule->ren_mov) + n * strlen(str_to_match));
                     s = rule->ren_mov + 1;
                     while (*s) {
                         *p = *s;
                         if ('%' == *s) {
                             unsigned i = (s[1] - '0');
                             if (i <= 9 && off[i].rm_so >= 0) {
                                 n = off[i].rm_eo - off[i].rm_so;
                                 strncpy(p, str_to_match + off[i].rm_so, n);
                                 p += n - 1;
                                 s++;
                             }
                         }
                         p++;
                         s++;
                     }
                 } else {
                     alias = xstrdup(rule->ren_mov + 1);
                 }
             }
         }
         dbg3("alias:'%s'", alias);
         command = NULL;
         IF_FEATURE_MDEV_EXEC(command = rule->r_cmd;)
         if (command) {
             /* Are we running this command now?
              * Run @cmd on create, $cmd on delete, *cmd on any
              */
             if ((command[0] == '@' && operation == OP_add)
              || (command[0] == '$' && operation == OP_remove)
              || (command[0] == '*')
             ) {
                 command++;
             } else {
                 command = NULL;
             }
         }
         dbg3("command:'%s'", command);
         /* "Execute" the line we found */
         node_name = device_name;
         if (ENABLE_FEATURE_MDEV_RENAME && alias) {
             node_name = alias = build_alias(alias, device_name);
             dbg3("alias2:'%s'", alias);
         }
         if (operation == OP_add && major >= 0) {
             char *slash = strrchr(node_name, '/');
             if (slash) {
                 *slash = '\0';
                 mkdir_recursive(node_name);
                 *slash = '/';
             }
             if (ENABLE_FEATURE_MDEV_CONF) {
                 dbg1("mknod %s (%d,%d) %o"
                     " %u:%u",
                     node_name, major, minor, rule->mode | type,
                     rule->ugid.uid, rule->ugid.gid
                 );
             } else {
                 dbg1("mknod %s (%d,%d) %o",
                     node_name, major, minor, rule->mode | type
                 );
             }
             if (mknod(node_name, rule->mode | type, makedev(major, minor)) && errno != EEXIST)
                 bb_perror_msg("can't create '%s'", node_name);
             if (ENABLE_FEATURE_MDEV_CONF) {
                 chmod(node_name, rule->mode);
                 chown(node_name, rule->ugid.uid, rule->ugid.gid);
             }
             if (major == G.root_major && minor == G.root_minor)
                 symlink(node_name, "root");
             if (ENABLE_FEATURE_MDEV_RENAME && alias) {
                 if (aliaslink == '>') {
 //TODO: on devtmpfs, device_name already exists and symlink() fails.
 //End result is that instead of symlink, we have two nodes.
 //What should be done?
                     dbg1("symlink: %s", device_name);
                     symlink(node_name, device_name);
                 }
             }
         }
         if (ENABLE_FEATURE_MDEV_EXEC && command) {
             /* setenv will leak memory, use putenv/unsetenv/free */
             char *s = xasprintf("%s=%s", "MDEV", node_name);
             putenv(s);
             dbg1("running: %s", command);
             if (system(command) == -1)
                 bb_perror_msg("can't run '%s'", command);
             bb_unsetenv_and_free(s);
         }
         if (operation == OP_remove && major >= -1) {
             if (ENABLE_FEATURE_MDEV_RENAME && alias) {
                 if (aliaslink == '>') {
                     dbg1("unlink: %s", device_name);
                     unlink(device_name);
                 }
             }
             dbg1("unlink: %s", node_name);
             unlink(node_name);
         }
         if (ENABLE_FEATURE_MDEV_RENAME)
             free(alias);
         /* We found matching line.
          * Stop unless it was prefixed with '-'
          */
         if (!ENABLE_FEATURE_MDEV_CONF || !rule->keep_matching)
             break;
     } /* for (;;) */
 }
References ARRAY_SIZE, bb_basename(), bb_perror_msg(), bb_unsetenv_and_free(), build_alias(), chmod(), chown(), dbg1, dbg2, dbg3, device_name, EEXIST, rule::envmatch, rule::envvar, errno, free, G, getenv, bb_uidgid_t::gid, i, is_prefixed_with(), rule::keep_matching, rule::maj, major, makedev, rule::match, memset(), rule::min0, rule::min1, minor, mkdir_recursive(), mknod(), rule::mode, n, next_rule, NULL, off, OP_add, OP_remove, open_read_close(), p, putenv(), rule::regex_compiled, regexec, rule::ren_mov, s, S_IFBLK, S_IFCHR, SCRATCH_SIZE, sscanf(), strchrnul(), strcpy(), strlen(), strncpy(), strrchr(), strstr(), symlink(), system(), type, rule::ugid, bb_uidgid_t::uid, unlink(), xasprintf(), xstrdup(), and xzalloc().
Referenced by fileAction(), and process_action().
mdev_main()
int mdev_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1239 of file mdev.c.
 {
     enum {
         MDEV_OPT_SCAN       = 1 << 0,
         MDEV_OPT_SYSLOG     = 1 << 1,
         MDEV_OPT_DAEMON     = 1 << 2,
         MDEV_OPT_FOREGROUND = 1 << 3,
     };
     int opt;
     RESERVE_CONFIG_BUFFER(temp, PATH_MAX + SCRATCH_SIZE);
     INIT_G();
     /* We can be called as hotplug helper */
     /* Kernel cannot provide suitable stdio fds for us, do it ourself */
     bb_sanitize_stdio();
     /* Force the configuration file settings exactly */
     umask(0);
     xchdir("/dev");
     opt = getopt32(argv, "^"
         "sS" IF_FEATURE_MDEV_DAEMON("df") "v"
         "\0"
         "vv",
         &G.verbose);
 #if ENABLE_FEATURE_MDEV_CONF
     G.filename = "/etc/mdev.conf";
     if (opt & (MDEV_OPT_SCAN|MDEV_OPT_DAEMON)) {
         /* Same as xrealloc_vector(NULL, 4, 0): */
         G.rule_vec = xzalloc((1 << 4) * sizeof(*G.rule_vec));
     }
 #endif
     if (opt & MDEV_OPT_SYSLOG) {
         openlog(applet_name, LOG_PID, LOG_DAEMON);
         logmode |= LOGMODE_SYSLOG;
     }
 #if ENABLE_FEATURE_MDEV_DAEMON
     if (opt & MDEV_OPT_DAEMON) {
         /* Daemon mode listening on uevent netlink socket. Fork away
          * after initial scan so that caller can be sure everything
          * is up-to-date when mdev process returns.
          */
         int fd = daemon_init(temp);
         if (!(opt & MDEV_OPT_FOREGROUND)) {
             /* there is no point in logging to /dev/null */
             logmode &= ~LOGMODE_STDIO;
             bb_daemonize_or_rexec(0, argv);
         }
         daemon_loop(temp, fd);
     }
 #endif
     if (opt & MDEV_OPT_SCAN) {
         /*
          * Scan: mdev -s
          */
         initial_scan(temp);
     } else {
         process_action(temp, getpid());
         dbg1("%s exiting", curtime());
     }
     if (ENABLE_FEATURE_CLEAN_UP)
         RELEASE_CONFIG_BUFFER(temp);
     return EXIT_SUCCESS;
 }
References applet_name, argv, bb_daemonize_or_rexec, bb_sanitize_stdio(), curtime(), dbg1, EXIT_SUCCESS, fd, G, getopt32(), getpid(), INIT_G, initial_scan(), LOG_DAEMON, LOG_PID, logmode, LOGMODE_STDIO, LOGMODE_SYSLOG, openlog(), opt, PATH_MAX, process_action(), RELEASE_CONFIG_BUFFER, RESERVE_CONFIG_BUFFER, SCRATCH_SIZE, umask(), xchdir(), and xzalloc().
mkdir_recursive()
static void mkdir_recursive (char * name) static
Definition at line 529 of file mdev.c.
 {
     /* if name has many levels ("dir1/dir2"),
      * bb_make_directory() will create dir1 according to umask,
      * not according to its "mode" parameter.
      * Since we run with umask=0, need to temporarily switch it.
      */
     umask(022); /* "dir1" (if any) will be 0755 too */
     bb_make_directory(name, 0755, FILEUTILS_RECUR);
     umask(0);
 }
References bb_make_directory(), FILEUTILS_RECUR, and umask().
Referenced by build_alias(), and make_device().
open_mdev_log()
static void open_mdev_log (const char * seq, unsigned my_pid) static
Definition at line 975 of file mdev.c.
 {
     int logfd = open("mdev.log", O_WRONLY | O_APPEND);
     if (logfd >= 0) {
         xmove_fd(logfd, STDERR_FILENO);
         G.verbose = 2;
         applet_name = xasprintf("%s[%s]", applet_name, seq ? seq : utoa(my_pid));
     }
 }
References applet_name, G, O_APPEND, O_WRONLY, open(), seq, STDERR_FILENO, utoa(), xasprintf(), and xmove_fd().
Referenced by process_action().
process_action()
static void process_action (char * temp, unsigned my_pid) static
Definition at line 1071 of file mdev.c.
 {
     char *fw;
     char *seq;
     char *action;
     char *env_devname;
     char *env_devpath;
     unsigned seqnum = seqnum; /* for compiler */
     int seq_fd;
     smalluint op;
     /* Hotplug:
      * env ACTION=... DEVPATH=... SUBSYSTEM=... [SEQNUM=...] mdev
      * ACTION can be "add", "remove", "change"
      * DEVPATH is like "/block/sda" or "/class/input/mice"
      */
     env_devname = getenv("DEVNAME"); /* can be NULL */
     G.subsystem = getenv("SUBSYSTEM");
     action = getenv("ACTION");
     env_devpath = getenv("DEVPATH");
     if (!action || !env_devpath /*|| !G.subsystem*/)
         bb_show_usage();
     fw = getenv("FIRMWARE");
     seq = getenv("SEQNUM");
     op = index_in_strings(keywords, action);
     if (my_pid)
         open_mdev_log(seq, my_pid);
     seq_fd = -1;
     if (my_pid && seq) {
         seqnum = atoll(seq);
         seq_fd = wait_for_seqfile(seqnum);
     }
     dbg1("%s "
         "ACTION:%s SEQNUM:%s SUBSYSTEM:%s DEVNAME:%s DEVPATH:%s"
         "%s%s",
         curtime(),
         action, seq, G.subsystem, env_devname, env_devpath,
         fw ? " FW:" : "", fw ? fw : ""
     );
     snprintf(temp, PATH_MAX, "/sys%s", env_devpath);
     if (op == OP_remove) {
         /* Ignoring "remove firmware". It was reported
          * to happen and to cause erroneous deletion
          * of device nodes. */
         if (!fw)
             make_device(env_devname, temp, op);
     }
     else {
         make_device(env_devname, temp, op);
         if (ENABLE_FEATURE_MDEV_LOAD_FIRMWARE) {
             if (op == OP_add && fw)
                 load_firmware(fw, temp);
         }
     }
     if (seq_fd >= 0) {
         xwrite_str(seq_fd, utoa(seqnum + 1));
         signal_mdevs(my_pid);
     }
 }
References atoll(), bb_show_usage(), curtime(), dbg1, G, getenv, index_in_strings(), load_firmware(), make_device(), OP_add, OP_remove, open_mdev_log(), PATH_MAX, seq, signal_mdevs(), snprintf(), utoa(), wait_for_seqfile(), and xwrite_str().
Referenced by mdev_main().
readlink2()
static ssize_t readlink2 (char * buf, size_t bufsize) static
Definition at line 834 of file mdev.c.
 {
     // Grr... gcc 8.1.1:
     // "passing argument 2 to restrict-qualified parameter aliases with argument 1"
     // dance around that...
     char *obuf FIX_ALIASING;
     obuf = buf;
     return readlink(buf, obuf, bufsize);
 }
References buf, FIX_ALIASING, obuf, and readlink().
Referenced by fileAction().
signal_mdevs()
static void signal_mdevs (unsigned my_pid) static
Definition at line 1058 of file mdev.c.
 {
     procps_status_t* p = NULL;
     while ((p = procps_scan(p, PSSCAN_ARGV0)) != NULL) {
         if (p->pid != my_pid
          && p->argv0
          && strcmp(bb_basename(p->argv0), "mdev") == 0
         ) {
             kill(p->pid, SIGCHLD);
         }
     }
 }
References bb_basename(), kill(), NULL, p, procps_scan(), PSSCAN_ARGV0, SIGCHLD, and strcmp.
Referenced by process_action().
wait_for_seqfile()
static int wait_for_seqfile (unsigned expected_seq) static
Definition at line 991 of file mdev.c.
 {
     /* We time out after 2 sec */
     static const struct timespec ts = { 0, 32*1000*1000 };
     int timeout = 2000 / 32;
     int seq_fd = -1;
     int do_once = 1;
     sigset_t set_CHLD;
     sigemptyset(&set_CHLD);
     sigaddset(&set_CHLD, SIGCHLD);
     sigprocmask(SIG_BLOCK, &set_CHLD, NULL);
     for (;;) {
         int seqlen;
         char seqbuf[sizeof(long)*3 + 2];
         unsigned seqbufnum;
         if (seq_fd < 0) {
             seq_fd = open("mdev.seq", O_RDWR);
             if (seq_fd < 0)
                 break;
             close_on_exec_on(seq_fd);
         }
         seqlen = pread(seq_fd, seqbuf, sizeof(seqbuf) - 1, 0);
         if (seqlen < 0) {
             close(seq_fd);
             seq_fd = -1;
             break;
         }
         seqbuf[seqlen] = '\0';
         if (seqbuf[0] == '\n' || seqbuf[0] == '\0') {
             /* seed file: write out seq ASAP */
             xwrite_str(seq_fd, utoa(expected_seq));
             xlseek(seq_fd, 0, SEEK_SET);
             dbg2s("first seq written");
             break;
         }
         seqbufnum = atoll(seqbuf);
         if (seqbufnum == expected_seq) {
             /* correct idx */
             break;
         }
         if (seqbufnum > expected_seq) {
             /* a later mdev runs already (this was seen by users to happen) */
             /* do not overwrite seqfile on exit */
             close(seq_fd);
             seq_fd = -1;
             break;
         }
         if (do_once) {
             dbg2("%s mdev.seq='%s', need '%u'", curtime(), seqbuf, expected_seq);
             do_once = 0;
         }
         if (sigtimedwait(&set_CHLD, NULL, &ts) >= 0) {
             dbg3("woken up");
             continue; /* don't decrement timeout! */
         }
         if (--timeout == 0) {
             dbg1("%s mdev.seq='%s'", "timed out", seqbuf);
             break;
         }
     }
     sigprocmask(SIG_UNBLOCK, &set_CHLD, NULL);
     return seq_fd;
 }
References atoll(), close(), close_on_exec_on(), curtime(), dbg1, dbg2, dbg2s, dbg3, NULL, O_RDWR, open(), pread(), SEEK_SET, SIG_BLOCK, sigaddset(), SIGCHLD, sigemptyset(), sigprocmask(), sigtimedwait(), timeout(), utoa(), xlseek(), and xwrite_str().
Referenced by process_action().
Variable Documentation
ALIGN1
const char keywords [] ALIGN1 = "add\0remove\0" static
Definition at line 275 of file mdev.c.
FIX_ALIASING
struct globals FIX_ALIASING
Referenced by readlink2().