Fennix Userspace: Userspace/mlibc/options/posix/generic/sys-select-stubs.cpp File Reference
sys-select-stubs.cpp File Reference
#include <string.h>
#include <sys/select.h>
#include <unistd.h>
#include <errno.h>
#include <bits/ensure.h>
#include <mlibc-config.h>
#include <mlibc/posix-sysdeps.hpp>
Functions
void __FD_CLR (int fd, fd_set *set)
int __FD_ISSET (int fd, fd_set *set)
void __FD_SET (int fd, fd_set *set)
void __FD_ZERO (fd_set *set)
int select (int num_fds, fd_set *__restrict read_set, fd_set *__restrict write_set, fd_set *__restrict except_set, struct timeval *__restrict timeout)
int pselect (int num_fds, fd_set *read_set, fd_set *write_set, fd_set *except_set, const struct timespec *timeout, const sigset_t *sigmask)
Function Documentation
__FD_CLR()
void __FD_CLR (int fd, fd_set * set)
Definition at line 12 of file sys-select-stubs.cpp.
{
     __ensure(fd < FD_SETSIZE);
     set->__mlibc_elems[fd / 8] &= ~(1 << (fd % 8));
 }
References __ensure, and FD_SETSIZE.
__FD_ISSET()
int __FD_ISSET (int fd, fd_set * set)
Definition at line 16 of file sys-select-stubs.cpp.
{
     __ensure(fd < FD_SETSIZE);
     return set->__mlibc_elems[fd / 8] & (1 << (fd % 8));
 }
References __ensure, and FD_SETSIZE.
__FD_SET()
void __FD_SET (int fd, fd_set * set)
Definition at line 20 of file sys-select-stubs.cpp.
{
     __ensure(fd < FD_SETSIZE);
     set->__mlibc_elems[fd / 8] |= 1 << (fd % 8);
 }
References __ensure, and FD_SETSIZE.
__FD_ZERO()
void __FD_ZERO (fd_set * set)
Definition at line 24 of file sys-select-stubs.cpp.
{
     memset(set->__mlibc_elems, 0, sizeof(fd_set));
 }
References memset().
pselect()
int pselect (int num_fds, fd_set * read_set, fd_set * write_set, fd_set * except_set, const struct timespec * timeout, const sigset_t * sigmask)
Definition at line 48 of file sys-select-stubs.cpp.
{
     int num_events = 0;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pselect, -1);
     if(int e = mlibc::sys_pselect(num_fds, read_set, write_set, except_set,
                 timeout, sigmask, &num_events); e) {
         errno = e;
         return -1;
     }
     return num_events;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, sigmask, and mlibc::sys_pselect().
Referenced by __pselect_time32(), and nchars_avail().
select()
int select (int num_fds, fd_set *__restrict read_set, fd_set *__restrict write_set, fd_set *__restrict except_set, struct timeval *__restrict timeout)
Definition at line 28 of file sys-select-stubs.cpp.
{
     int num_events = 0;
     struct timespec timeouts = {};
     struct timespec *timeout_ptr = NULL;
     if (timeout) {
         timeouts.tv_sec = timeout->tv_sec;
         timeouts.tv_nsec = timeout->tv_usec * 1000;
         timeout_ptr = &timeouts;
     }
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_pselect, -1);
     if(int e = mlibc::sys_pselect(num_fds, read_set, write_set, except_set,
                 timeout_ptr, NULL, &num_events); e) {
         errno = e;
         return -1;
     }
     return num_events;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, NULL, mlibc::sys_pselect(), timespec::tv_nsec, and timespec::tv_sec.
Referenced by __select_time32(), _rl_input_available(), accept_builtin(), input_avail(), main(), nchars_avail(), rl_gather_tyi(), rl_insert_close(), and scandir().