Fennix Userspace: Userspace/musl/src/search/tsearch.h File Reference
tsearch.h File Reference
#include <search.h>
#include <features.h>
Data Structures
struct node
Macros
#define MAXH (sizeof(void*)*8*3/2)
Functions
hidden int __tsearch_balance (void **)
Data Structure Documentation
node
struct node
Definition at line 33 of file tsort.c.
Data Fields
void * a[2]
int h
unsigned in_count
const void * key
char name[1]
struct narg narg
struct nbinary nbinary
struct ncase ncase
struct nclist nclist
struct ncmd ncmd
struct ndefun ndefun
struct ndup ndup
struct node * next
struct nfile nfile
struct nfor nfor
struct nhere nhere
struct nif nif
struct nnot nnot
struct npipe npipe
struct nredir nredir
struct node ** out
unsigned out_count
struct node * prev
smallint type
Macro Definition Documentation
MAXH
#define MAXH (sizeof(void*)*8*3/2)
Definition at line 5 of file tsearch.h.
Function Documentation
__tsearch_balance()
hidden int __tsearch_balance (void ** p)
Definition at line 49 of file tsearch.c.
 {
     struct node *n = *p;
     int h0 = height(n->a[0]);
     int h1 = height(n->a[1]);
     if (h0 - h1 + 1u < 3u) {
         int old = n->h;
         n->h = h0<h1 ? h1+1 : h0+1;
         return n->h - old;
     }
     return rot(p, n, h0<h1);
 }
References height(), n, old, p, and rot().
Referenced by tdelete(), and tsearch().