Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/p_switch.c File Reference
p_switch.c File Reference
#include <stdio.h>
#include "i_system.h"
#include "deh_main.h"
#include "doomdef.h"
#include "p_local.h"
#include "g_game.h"
#include "s_sound.h"
#include "sounds.h"
#include "doomstat.h"
#include "r_state.h"
Functions
void P_InitSwitchList (void)
void P_StartButton (line_t *line, bwhere_e w, int texture, int time)
void P_ChangeSwitchTexture (line_t *line, int useAgain)
boolean P_UseSpecialLine (mobj_t *thing, line_t *line, int side)
Variables
switchlist_t alphSwitchList []
int switchlist [MAXSWITCHES *2]
int numswitches
button_t buttonlist [MAXBUTTONS]
Function Documentation
P_ChangeSwitchTexture()
void P_ChangeSwitchTexture (line_t * line, int useAgain)
Definition at line 195 of file p_switch.c.
 {
     int     texTop;
     int     texMid;
     int     texBot;
     int     i;
     int     sound;
     if (!useAgain)
     line->special = 0;
     texTop = sides[line->sidenum[0]].toptexture;
     texMid = sides[line->sidenum[0]].midtexture;
     texBot = sides[line->sidenum[0]].bottomtexture;
     sound = sfx_swtchn;
     // EXIT SWITCH?
     if (line->special == 11)
     sound = sfx_swtchx;
     for (i = 0;i < numswitches*2;i++)
     {
     if (switchlist[i] == texTop)
     {
         S_StartSound(buttonlist->soundorg,sound);
         sides[line->sidenum[0]].toptexture = switchlist[i^1];
         if (useAgain)
         P_StartButton(line,top,switchlist[i],BUTTONTIME);
         return;
     }
     else
     {
         if (switchlist[i] == texMid)
         {
         S_StartSound(buttonlist->soundorg,sound);
         sides[line->sidenum[0]].midtexture = switchlist[i^1];
         if (useAgain)
             P_StartButton(line, middle,switchlist[i],BUTTONTIME);
         return;
         }
         else
         {
         if (switchlist[i] == texBot)
         {
             S_StartSound(buttonlist->soundorg,sound);
             sides[line->sidenum[0]].bottomtexture = switchlist[i^1];
             if (useAgain)
             P_StartButton(line, bottom,switchlist[i],BUTTONTIME);
             return;
         }
         }
     }
     }
 }
References bottom, side_t::bottomtexture, buttonlist, BUTTONTIME, i, middle, side_t::midtexture, numswitches, P_StartButton(), S_StartSound(), sfx_swtchn, sfx_swtchx, sides, button_t::soundorg, switchlist, top, and side_t::toptexture.
Referenced by P_ShootSpecialLine(), and P_UseSpecialLine().
P_InitSwitchList()
void P_InitSwitchList (void)
Definition at line 101 of file p_switch.c.
 {
     int     i;
     int     index;
     int     episode;
     episode = 1;
     if (gamemode == registered || gamemode == retail)
     episode = 2;
     else
     if ( gamemode == commercial )
         episode = 3;
     for (index = 0,i = 0;i < MAXSWITCHES;i++)
     {
     if (!alphSwitchList[i].episode)
     {
         numswitches = index/2;
         switchlist[index] = -1;
         break;
     }
     if (alphSwitchList[i].episode <= episode)
     {
 #if 0   // UNUSED - debug?
         int     value;
         if (R_CheckTextureNumForName(alphSwitchList[i].name1) < 0)
         {
         I_Error("Can't find switch texture '%s'!",
             alphSwitchList[i].name1);
         continue;
         }
         value = R_TextureNumForName(alphSwitchList[i].name1);
 #endif
         switchlist[index++] = R_TextureNumForName(DEH_String(alphSwitchList[i].name1));
         switchlist[index++] = R_TextureNumForName(DEH_String(alphSwitchList[i].name2));
     }
     }
 }
References alphSwitchList, commercial, DEH_String, gamemode, i, I_Error(), index(), MAXSWITCHES, numswitches, R_CheckTextureNumForName(), R_TextureNumForName(), registered, retail, switchlist, and value.
Referenced by P_Init().
P_StartButton()
void P_StartButton (line_t * line, bwhere_e w, int texture, int time)
Definition at line 149 of file p_switch.c.
 {
     int     i;
     // See if button is already pressed
     for (i = 0;i < MAXBUTTONS;i++)
     {
     if (buttonlist[i].btimer
         && buttonlist[i].line == line)
     {
         return;
     }
     }
     for (i = 0;i < MAXBUTTONS;i++)
     {
     if (!buttonlist[i].btimer)
     {
         buttonlist[i].line = line;
         buttonlist[i].where = w;
         buttonlist[i].btexture = texture;
         buttonlist[i].btimer = time;
         buttonlist[i].soundorg = &line->frontsector->soundorg;
         return;
     }
     }
     I_Error("P_StartButton: no button slots left!");
 }
References button_t::btexture, button_t::btimer, buttonlist, i, I_Error(), line, button_t::line, MAXBUTTONS, button_t::soundorg, time(), w, and button_t::where.
Referenced by P_ChangeSwitchTexture().
P_UseSpecialLine()
boolean P_UseSpecialLine (mobj_t * thing, line_t * line, int side)
Definition at line 270 of file p_switch.c.
 {
     // Err...
     // Use the back sides of VERY SPECIAL lines...
     if (side)
     {
     switch(line->special)
     {
       case 124:
         // Sliding door open&close
         // UNUSED?
         break;
       default:
         return false;
         break;
     }
     }
     // Switches that other things can activate.
     if (!thing->player)
     {
     // never open secret doors
     if (line->flags & ML_SECRET)
         return false;
     switch(line->special)
     {
       case 1:   // MANUAL DOOR RAISE
       case 32:  // MANUAL BLUE
       case 33:  // MANUAL RED
       case 34:  // MANUAL YELLOW
         break;
       default:
         return false;
         break;
     }
     }
     // do something
     switch (line->special)
     {
     // MANUALS
       case 1:       // Vertical Door
       case 26:      // Blue Door/Locked
       case 27:      // Yellow Door /Locked
       case 28:      // Red Door /Locked
       case 31:      // Manual door open
       case 32:      // Blue locked door open
       case 33:      // Red locked door open
       case 34:      // Yellow locked door open
       case 117:     // Blazing door raise
       case 118:     // Blazing door open
     EV_VerticalDoor (line, thing);
     break;
     //UNUSED - Door Slide Open&Close
     // case 124:
     // EV_SlidingDoor (line, thing);
     // break;
     // SWITCHES
       case 7:
     // Build Stairs
     if (EV_BuildStairs(line,build8))
         P_ChangeSwitchTexture(line,0);
     break;
       case 9:
     // Change Donut
     if (EV_DoDonut(line))
         P_ChangeSwitchTexture(line,0);
     break;
       case 11:
     // Exit level
     P_ChangeSwitchTexture(line,0);
     G_ExitLevel ();
     break;
       case 14:
     // Raise Floor 32 and change texture
     if (EV_DoPlat(line,raiseAndChange,32))
         P_ChangeSwitchTexture(line,0);
     break;
       case 15:
     // Raise Floor 24 and change texture
     if (EV_DoPlat(line,raiseAndChange,24))
         P_ChangeSwitchTexture(line,0);
     break;
       case 18:
     // Raise Floor to next highest floor
     if (EV_DoFloor(line, raiseFloorToNearest))
         P_ChangeSwitchTexture(line,0);
     break;
       case 20:
     // Raise Plat next highest floor and change texture
     if (EV_DoPlat(line,raiseToNearestAndChange,0))
         P_ChangeSwitchTexture(line,0);
     break;
       case 21:
     // PlatDownWaitUpStay
     if (EV_DoPlat(line,downWaitUpStay,0))
         P_ChangeSwitchTexture(line,0);
     break;
       case 23:
     // Lower Floor to Lowest
     if (EV_DoFloor(line,lowerFloorToLowest))
         P_ChangeSwitchTexture(line,0);
     break;
       case 29:
     // Raise Door
     if (EV_DoDoor(line,vld_normal))
         P_ChangeSwitchTexture(line,0);
     break;
       case 41:
     // Lower Ceiling to Floor
     if (EV_DoCeiling(line,lowerToFloor))
         P_ChangeSwitchTexture(line,0);
     break;
       case 71:
     // Turbo Lower Floor
     if (EV_DoFloor(line,turboLower))
         P_ChangeSwitchTexture(line,0);
     break;
       case 49:
     // Ceiling Crush And Raise
     if (EV_DoCeiling(line,crushAndRaise))
         P_ChangeSwitchTexture(line,0);
     break;
       case 50:
     // Close Door
     if (EV_DoDoor(line,vld_close))
         P_ChangeSwitchTexture(line,0);
     break;
       case 51:
     // Secret EXIT
     P_ChangeSwitchTexture(line,0);
     G_SecretExitLevel ();
     break;
       case 55:
     // Raise Floor Crush
     if (EV_DoFloor(line,raiseFloorCrush))
         P_ChangeSwitchTexture(line,0);
     break;
       case 101:
     // Raise Floor
     if (EV_DoFloor(line,raiseFloor))
         P_ChangeSwitchTexture(line,0);
     break;
       case 102:
     // Lower Floor to Surrounding floor height
     if (EV_DoFloor(line,lowerFloor))
         P_ChangeSwitchTexture(line,0);
     break;
       case 103:
     // Open Door
     if (EV_DoDoor(line,vld_open))
         P_ChangeSwitchTexture(line,0);
     break;
       case 111:
     // Blazing Door Raise (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeRaise))
         P_ChangeSwitchTexture(line,0);
     break;
       case 112:
     // Blazing Door Open (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeOpen))
         P_ChangeSwitchTexture(line,0);
     break;
       case 113:
     // Blazing Door Close (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeClose))
         P_ChangeSwitchTexture(line,0);
     break;
       case 122:
     // Blazing PlatDownWaitUpStay
     if (EV_DoPlat(line,blazeDWUS,0))
         P_ChangeSwitchTexture(line,0);
     break;
       case 127:
     // Build Stairs Turbo 16
     if (EV_BuildStairs(line,turbo16))
         P_ChangeSwitchTexture(line,0);
     break;
       case 131:
     // Raise Floor Turbo
     if (EV_DoFloor(line,raiseFloorTurbo))
         P_ChangeSwitchTexture(line,0);
     break;
       case 133:
     // BlzOpenDoor BLUE
       case 135:
     // BlzOpenDoor RED
       case 137:
     // BlzOpenDoor YELLOW
     if (EV_DoLockedDoor (line,vld_blazeOpen,thing))
         P_ChangeSwitchTexture(line,0);
     break;
       case 140:
     // Raise Floor 512
     if (EV_DoFloor(line,raiseFloor512))
         P_ChangeSwitchTexture(line,0);
     break;
     // BUTTONS
       case 42:
     // Close Door
     if (EV_DoDoor(line,vld_close))
         P_ChangeSwitchTexture(line,1);
     break;
       case 43:
     // Lower Ceiling to Floor
     if (EV_DoCeiling(line,lowerToFloor))
         P_ChangeSwitchTexture(line,1);
     break;
       case 45:
     // Lower Floor to Surrounding floor height
     if (EV_DoFloor(line,lowerFloor))
         P_ChangeSwitchTexture(line,1);
     break;
       case 60:
     // Lower Floor to Lowest
     if (EV_DoFloor(line,lowerFloorToLowest))
         P_ChangeSwitchTexture(line,1);
     break;
       case 61:
     // Open Door
     if (EV_DoDoor(line,vld_open))
         P_ChangeSwitchTexture(line,1);
     break;
       case 62:
     // PlatDownWaitUpStay
     if (EV_DoPlat(line,downWaitUpStay,1))
         P_ChangeSwitchTexture(line,1);
     break;
       case 63:
     // Raise Door
     if (EV_DoDoor(line,vld_normal))
         P_ChangeSwitchTexture(line,1);
     break;
       case 64:
     // Raise Floor to ceiling
     if (EV_DoFloor(line,raiseFloor))
         P_ChangeSwitchTexture(line,1);
     break;
       case 66:
     // Raise Floor 24 and change texture
     if (EV_DoPlat(line,raiseAndChange,24))
         P_ChangeSwitchTexture(line,1);
     break;
       case 67:
     // Raise Floor 32 and change texture
     if (EV_DoPlat(line,raiseAndChange,32))
         P_ChangeSwitchTexture(line,1);
     break;
       case 65:
     // Raise Floor Crush
     if (EV_DoFloor(line,raiseFloorCrush))
         P_ChangeSwitchTexture(line,1);
     break;
       case 68:
     // Raise Plat to next highest floor and change texture
     if (EV_DoPlat(line,raiseToNearestAndChange,0))
         P_ChangeSwitchTexture(line,1);
     break;
       case 69:
     // Raise Floor to next highest floor
     if (EV_DoFloor(line, raiseFloorToNearest))
         P_ChangeSwitchTexture(line,1);
     break;
       case 70:
     // Turbo Lower Floor
     if (EV_DoFloor(line,turboLower))
         P_ChangeSwitchTexture(line,1);
     break;
       case 114:
     // Blazing Door Raise (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeRaise))
         P_ChangeSwitchTexture(line,1);
     break;
       case 115:
     // Blazing Door Open (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeOpen))
         P_ChangeSwitchTexture(line,1);
     break;
       case 116:
     // Blazing Door Close (faster than TURBO!)
     if (EV_DoDoor (line,vld_blazeClose))
         P_ChangeSwitchTexture(line,1);
     break;
       case 123:
     // Blazing PlatDownWaitUpStay
     if (EV_DoPlat(line,blazeDWUS,0))
         P_ChangeSwitchTexture(line,1);
     break;
       case 132:
     // Raise Floor Turbo
     if (EV_DoFloor(line,raiseFloorTurbo))
         P_ChangeSwitchTexture(line,1);
     break;
       case 99:
     // BlzOpenDoor BLUE
       case 134:
     // BlzOpenDoor RED
       case 136:
     // BlzOpenDoor YELLOW
     if (EV_DoLockedDoor (line,vld_blazeOpen,thing))
         P_ChangeSwitchTexture(line,1);
     break;
       case 138:
     // Light Turn On
     EV_LightTurnOn(line,255);
     P_ChangeSwitchTexture(line,1);
     break;
       case 139:
     // Light Turn Off
     EV_LightTurnOn(line,35);
     P_ChangeSwitchTexture(line,1);
     break;
     }
     return true;
 }
References blazeDWUS, build8, crushAndRaise, downWaitUpStay, EV_BuildStairs(), EV_DoCeiling(), EV_DoDonut(), EV_DoDoor(), EV_DoFloor(), EV_DoLockedDoor(), EV_DoPlat(), EV_LightTurnOn(), EV_VerticalDoor(), G_ExitLevel(), G_SecretExitLevel(), lowerFloor, lowerFloorToLowest, lowerToFloor, ML_SECRET, P_ChangeSwitchTexture(), mobj_s::player, raiseAndChange, raiseFloor, raiseFloor512, raiseFloorCrush, raiseFloorToNearest, raiseFloorTurbo, raiseToNearestAndChange, turbo16, turboLower, vld_blazeClose, vld_blazeOpen, vld_blazeRaise, vld_close, vld_normal, and vld_open.
Referenced by P_Move(), and PTR_UseTraverse().
Variable Documentation
alphSwitchList
switchlist_t alphSwitchList[]
Definition at line 42 of file p_switch.c.
Referenced by P_InitSwitchList().
buttonlist
button_t buttonlist[MAXBUTTONS]
Definition at line 95 of file p_switch.c.
Referenced by P_ChangeSwitchTexture(), P_SpawnSpecials(), P_StartButton(), and P_UpdateSpecials().
numswitches
int numswitches
Definition at line 94 of file p_switch.c.
Referenced by P_ChangeSwitchTexture(), and P_InitSwitchList().
switchlist
int switchlist[MAXSWITCHES *2]
Definition at line 93 of file p_switch.c.
Referenced by P_ChangeSwitchTexture(), and P_InitSwitchList().