Fennix: Userspace/apps/base/cross_test/linux_glibc.c File Reference
linux_glibc.c File Reference
#include <stdint.h>
#include <stdio.h>
#include <unistd.h>
#include <limits.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <pty.h>
#include <termios.h>
#include <sys/ioctl.h>
Macros
#define _POSIX_SOURCE
#define _DEFAULT_SOURCE
#define __GLIBC__ 0
#define __GLIBC_MINOR__ 0
Functions
int ptmx_test ()
int main (int argc, char *argv[], char *envp[])
Macro Definition Documentation
__GLIBC__
#define __GLIBC__ 0
Definition at line 23 of file linux_glibc.c.
__GLIBC_MINOR__
#define __GLIBC_MINOR__ 0
Definition at line 27 of file linux_glibc.c.
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
Definition at line 2 of file linux_glibc.c.
_POSIX_SOURCE
#define _POSIX_SOURCE
Definition at line 1 of file linux_glibc.c.
Function Documentation
main()
int main (int argc, char * argv[], char * envp[])
Definition at line 91 of file linux_glibc.c.
 {
     printf("glibc %d.%d: Hello, World!\n", __GLIBC__, __GLIBC_MINOR__);
     fflush(stdout);
     ptmx_test();
     return 0;
 }
References __GLIBC__, __GLIBC_MINOR__, fflush(), printf, ptmx_test(), and stdout.
Referenced by __libc_start_main(), libc_start_main_stage2(), and M_SaveDefaultsAlternate().
ptmx_test()
int ptmx_test ()
Definition at line 30 of file linux_glibc.c.
 {
     int masterFD;
     int slaveFD;
     char slaveName[100];
     masterFD = open("/dev/ptmx", O_RDWR | O_NOCTTY);
     if (masterFD < 0)
     {
         perror("Failed to open /dev/ptmx");
         return 1;
     }
     if (grantpt(masterFD) < 0)
     {
         perror("Failed to grantpt");
         return 1;
     }
     if (unlockpt(masterFD) < 0)
     {
         perror("Failed to unlockpt");
         return 1;
     }
     if (ptsname_r(masterFD, slaveName, sizeof(slaveName)) != 0)
     {
         perror("Failed to get slave name");
         return 1;
     }
     printf("Slave terminal: %s\n", slaveName);
     slaveFD = open(slaveName, O_RDWR | O_NOCTTY);
     if (slaveFD < 0)
     {
         perror("Failed to open slave terminal");
         return 1;
     }
     struct termios t;
     tcgetattr(slaveFD, &t);
     cfmakeraw(&t);
     tcsetattr(slaveFD, TCSANOW, &t);
     char *message = "Hello from master!\n";
     write(masterFD, message, strlen(message));
     char buffer[100];
     int len = read(slaveFD, buffer, sizeof(buffer) - 1);
     if (len > 0)
     {
         buffer[len] = '\0';
         printf("Received from slave: %s\n", buffer);
     }
     close(masterFD);
     close(slaveFD);
     return 0;
 }
References cfmakeraw(), close(), grantpt(), len, O_NOCTTY, O_RDWR, open(), perror(), printf, read(), strlen, tcgetattr(), TCSANOW, tcsetattr(), unlockpt(), and write().
Referenced by main().