Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/p_setup.h File Reference
p_setup.h File Reference
Functions
void P_SetupLevel (int episode, int map, int playermask, skill_t skill)
void P_Init (void)
Function Documentation
P_Init()
void P_Init (void)
Definition at line 847 of file p_setup.c.
 {
     P_InitSwitchList ();
     P_InitPicAnims ();
     R_InitSprites (sprnames);
 }
References P_InitPicAnims(), P_InitSwitchList(), R_InitSprites(), and sprnames.
Referenced by D_DoomMain().
P_SetupLevel()
void P_SetupLevel (int episode, int map, int playermask, skill_t skill)
Definition at line 744 of file p_setup.c.
 {
     int     i;
     char    lumpname[9];
     int     lumpnum;
     totalkills = totalitems = totalsecret = wminfo.maxfrags = 0;
     wminfo.partime = 180;
     for (i=0 ; i<MAXPLAYERS ; i++)
     {
     players[i].killcount = players[i].secretcount
         = players[i].itemcount = 0;
     }
     // Initial height of PointOfView
     // will be set by player think.
     players[consoleplayer].viewz = 1;
     // Make sure all sounds are stopped before Z_FreeTags.
     S_Start ();
     Z_FreeTags (PU_LEVEL, PU_PURGELEVEL-1);
     // UNUSED W_Profile ();
     P_InitThinkers ();
     // find map name
     if ( gamemode == commercial)
     {
     if (map<10)
         DEH_snprintf(lumpname, 9, "map0%i", map);
     else
         DEH_snprintf(lumpname, 9, "map%i", map);
     }
     else
     {
     lumpname[0] = 'E';
     lumpname[1] = '0' + episode;
     lumpname[2] = 'M';
     lumpname[3] = '0' + map;
     lumpname[4] = 0;
     }
     lumpnum = W_GetNumForName (lumpname);
     leveltime = 0;
     // note: most of this ordering is important
     P_LoadBlockMap (lumpnum+ML_BLOCKMAP);
     P_LoadVertexes (lumpnum+ML_VERTEXES);
     P_LoadSectors (lumpnum+ML_SECTORS);
     P_LoadSideDefs (lumpnum+ML_SIDEDEFS);
     P_LoadLineDefs (lumpnum+ML_LINEDEFS);
     P_LoadSubsectors (lumpnum+ML_SSECTORS);
     P_LoadNodes (lumpnum+ML_NODES);
     P_LoadSegs (lumpnum+ML_SEGS);
     P_GroupLines ();
     P_LoadReject (lumpnum+ML_REJECT);
     bodyqueslot = 0;
     deathmatch_p = deathmatchstarts;
     P_LoadThings (lumpnum+ML_THINGS);
     // if deathmatch, randomly spawn the active players
     if (deathmatch)
     {
     for (i=0 ; i<MAXPLAYERS ; i++)
         if (playeringame[i])
         {
         players[i].mo = NULL;
         G_DeathMatchSpawnPlayer (i);
         }
     }
     // clear special respawning que
     iquehead = iquetail = 0;
     // set up world state
     P_SpawnSpecials ();
     // build subsector connect matrix
     //  UNUSED P_ConnectSubsectors ();
     // preload graphics
     if (precache)
     R_PrecacheLevel ();
     //printf ("free memory: 0x%x\n", Z_FreeMemory());
 }
References bodyqueslot, commercial, consoleplayer, deathmatch, deathmatch_p, deathmatchstarts, DEH_snprintf, G_DeathMatchSpawnPlayer(), gamemode, i, iquehead, iquetail, player_s::itemcount, player_s::killcount, leveltime, wbstartstruct_t::maxfrags, MAXPLAYERS, ML_BLOCKMAP, ML_LINEDEFS, ML_NODES, ML_REJECT, ML_SECTORS, ML_SEGS, ML_SIDEDEFS, ML_SSECTORS, ML_THINGS, ML_VERTEXES, player_s::mo, NULL, P_GroupLines(), P_InitThinkers(), P_LoadBlockMap(), P_LoadLineDefs(), P_LoadNodes(), P_LoadReject(), P_LoadSectors(), P_LoadSegs(), P_LoadSideDefs(), P_LoadSubsectors(), P_LoadThings(), P_LoadVertexes(), P_SpawnSpecials(), wbstartstruct_t::partime, playeringame, players, precache, PU_LEVEL, PU_PURGELEVEL, R_PrecacheLevel(), S_Start(), player_s::secretcount, totalitems, totalkills, totalsecret, player_s::viewz, W_GetNumForName(), wminfo, and Z_FreeTags().
Referenced by G_DoLoadLevel().