Fennix Userspace: Userspace/apps/base/busybox/coreutils/ln.c File Reference
ln.c File Reference
#include "libbb.h"
Macros
#define LN_SYMLINK (1 << 0)
#define LN_FORCE (1 << 1)
#define LN_NODEREFERENCE (1 << 2)
#define LN_BACKUP (1 << 3)
#define LN_SUFFIX (1 << 4)
#define LN_VERBOSE (1 << 5)
#define LN_LINKFILE (1 << 6)
Functions
int ln_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
LN_BACKUP
#define LN_BACKUP (1 << 3)
Definition at line 47 of file ln.c.
LN_FORCE
#define LN_FORCE (1 << 1)
Definition at line 45 of file ln.c.
LN_LINKFILE
#define LN_LINKFILE (1 << 6)
Definition at line 50 of file ln.c.
LN_NODEREFERENCE
#define LN_NODEREFERENCE (1 << 2)
Definition at line 46 of file ln.c.
LN_SUFFIX
#define LN_SUFFIX (1 << 4)
Definition at line 48 of file ln.c.
LN_SYMLINK
#define LN_SYMLINK (1 << 0)
Definition at line 44 of file ln.c.
LN_VERBOSE
#define LN_VERBOSE (1 << 5)
Definition at line 49 of file ln.c.
Function Documentation
ln_main()
int ln_main (int argc, char ** argv)
Definition at line 53 of file ln.c.
 {
     int status = EXIT_SUCCESS;
     int opts;
     char *last;
     char *src_name;
     char *src;
     char *suffix = (char*)"~";
     struct stat statbuf;
     int (*link_func)(const char *, const char *);
     opts = getopt32(argv, "^" "sfnbS:vT" "\0" "-1", &suffix);
 /*
     -s, --symbolic      make symbolic links instead of hard links
     -f, --force     remove existing destination files
     -n, --no-dereference    treat LINK_NAME as a normal file if it is a symbolic link to a directory
     -b          like --backup but does not accept an argument
     --backup[=CONTROL]  make a backup of each existing destination file
     -S, --suffix=SUFFIX override the usual backup suffix
     -v, --verbose
     -T, --no-target-directory
     -d, -F, --directory allow the superuser to attempt to hard link directories
     -i, --interactive   prompt whether to remove destinations
     -L, --logical       dereference TARGETs that are symbolic links
     -P, --physical      make hard links directly to symbolic links
     -r, --relative      create symbolic links relative to link location
     -t, --target-directory=DIRECTORY    specify the DIRECTORY in which to create the links
  */
     last = argv[argc - 1];
     argv += optind;
     argc -= optind;
     if ((opts & LN_LINKFILE) && argc > 2) {
         bb_simple_error_msg_and_die("-T accepts 2 args max");
     }
     if (!argv[1]) {
         /* "ln PATH/TO/FILE" -> "ln PATH/TO/FILE FILE" */
         *--argv = last;
         /* xstrdup is needed: "ln -s PATH/TO/FILE/" is equivalent to
          * "ln -s PATH/TO/FILE/ FILE", not "ln -s PATH/TO/FILE FILE"
          */
         last = bb_get_last_path_component_strip(xstrdup(last));
     }
     do {
         src_name = NULL;
         src = last;
         if (is_directory(src,
                 /*followlinks:*/ !(opts & (LN_NODEREFERENCE|LN_LINKFILE))
                 /* Why LN_LINKFILE does not follow links:
                  * -T/--no-target-directory implies -n/--no-dereference
                  */
                 )
         ) {
             if (opts & LN_LINKFILE) {
                 bb_error_msg_and_die("'%s' is a directory", src);
             }
             src_name = xstrdup(*argv);
             src = concat_path_file(src, bb_get_last_path_component_strip(src_name));
             free(src_name);
             src_name = src;
         }
         if (!(opts & LN_SYMLINK) && stat(*argv, &statbuf)) {
             // coreutils: "ln dangling_symlink new_hardlink" works
             if (lstat(*argv, &statbuf) || !S_ISLNK(statbuf.st_mode)) {
                 bb_simple_perror_msg(*argv);
                 status = EXIT_FAILURE;
                 free(src_name);
                 continue;
             }
         }
         if (opts & LN_BACKUP) {
             char *backup;
             backup = xasprintf("%s%s", src, suffix);
             if (rename(src, backup) < 0 && errno != ENOENT) {
                 bb_simple_perror_msg(src);
                 status = EXIT_FAILURE;
                 free(backup);
                 continue;
             }
             free(backup);
             /*
              * When the source and dest are both hard links to the same
              * inode, a rename may succeed even though nothing happened.
              * Therefore, always unlink().
              */
             unlink(src);
         } else if (opts & LN_FORCE) {
             unlink(src);
         }
         link_func = link;
         if (opts & LN_SYMLINK) {
             link_func = symlink;
         }
         if (opts & LN_VERBOSE) {
             printf("'%s' -> '%s'\n", src, *argv);
         }
         if (link_func(*argv, src) != 0) {
             bb_simple_perror_msg(src);
             status = EXIT_FAILURE;
         }
         free(src_name);
     } while ((++argv)[1]);
     return status;
 }
References argc, argv, bb_error_msg_and_die(), bb_get_last_path_component_strip(), bb_simple_error_msg_and_die(), bb_simple_perror_msg(), concat_path_file(), ENOENT, errno, EXIT_FAILURE, EXIT_SUCCESS, free, getopt32(), is_directory(), last, link(), LN_BACKUP, LN_FORCE, LN_LINKFILE, LN_NODEREFERENCE, LN_SYMLINK, LN_VERBOSE, lstat, NULL, optind, printf(), rename(), S_ISLNK, src, stat::st_mode, stat(), status, symlink(), unlink(), xasprintf(), and xstrdup().