Fennix Userspace: Userspace/apps/base/busybox/init/init.c File Reference
init.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <syslog.h>
#include "reboot.h"
Data Structures
struct init_action
struct globals
Macros
#define DEBUG_SEGV_HANDLER 0
#define DEBUG_INIT 0
#define CONSOLE_NAME_SIZE 32
#define INIT_SCRIPT "/etc/init.d/rcS"
#define SYSINIT 0x01
#define WAIT 0x02
#define ONCE 0x04
#define RESPAWN 0x08
#define ASKFIRST 0x10
#define CTRLALTDEL 0x20
#define SHUTDOWN 0x40
#define RESTART 0x80
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G()
#define dbg_message(...) do { if (DEBUG_INIT) message(__VA_ARGS__); } while (0)
#define CBAUD 0
#define CBAUDEX 0
#define CRTSCTS 0
Enumerations
enum { L_LOG = 0x1 , L_CONSOLE = 0x2 }
Functions
static void message (int where, const char *fmt,...) __attribute__((format(printf
static void console_init (void)
static void set_sane_term (void)
static int open_stdio_to_tty (const char *tty_name)
static void reset_sighandlers_and_unblock_sigs (void)
static void init_exec (const char *command)
static pid_t run (const struct init_action *a)
static struct init_action * mark_terminated (pid_t pid)
static void waitfor (pid_t pid)
static void run_actions (int action_type)
static void new_init_action (uint8_t action_type, const char *command, const char *cons)
static void parse_inittab (void)
static void pause_and_low_level_reboot (unsigned magic) NORETURN
static void run_shutdown_and_kill_processes (void)
static void halt_reboot_pwoff (int sig) NORETURN
static void exec_restart_action (void)
static void stop_handler (int sig UNUSED_PARAM)
static void check_delayed_sigs (struct timespec *ts)
static void sleep_much (void)
int init_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Data Structure Documentation
init_action
struct init_action
Definition at line 200 of file init.c.
Data Fields
uint8_t action_type
char command[1]
struct init_action * next
pid_t pid
char terminal[CONSOLE_NAME_SIZE]
Macro Definition Documentation
ASKFIRST
#define ASKFIRST 0x10
Definition at line 177 of file init.c.
CBAUD
#define CBAUD 0
CBAUDEX
#define CBAUDEX 0
CONSOLE_NAME_SIZE
#define CONSOLE_NAME_SIZE 32
Definition at line 152 of file init.c.
CRTSCTS
#define CRTSCTS 0
CTRLALTDEL
#define CTRLALTDEL 0x20
Definition at line 183 of file init.c.
dbg_message
#define dbg_message (...) do { if (DEBUG_INIT) message(__VA_ARGS__); } while (0)
Definition at line 231 of file init.c.
DEBUG_INIT
#define DEBUG_INIT 0
Definition at line 150 of file init.c.
DEBUG_SEGV_HANDLER
#define DEBUG_SEGV_HANDLER 0
Definition at line 128 of file init.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 216 of file init.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    IF_NOT_FEATURE_INIT_SYSLOG(G.log_console = VC_5;) \
} while (0)
Definition at line 217 of file init.c.
INIT_SCRIPT
#define INIT_SCRIPT "/etc/init.d/rcS"
Definition at line 156 of file init.c.
ONCE
#define ONCE 0x04
Definition at line 167 of file init.c.
RESPAWN
#define RESPAWN 0x08
Definition at line 175 of file init.c.
RESTART
#define RESTART 0x80
Definition at line 197 of file init.c.
SHUTDOWN
#define SHUTDOWN 0x40
Definition at line 190 of file init.c.
SYSINIT
#define SYSINIT 0x01
Definition at line 163 of file init.c.
WAIT
#define WAIT 0x02
Definition at line 165 of file init.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
L_LOG
L_CONSOLE
Definition at line 222 of file init.c.
      {
     L_LOG = 0x1,
     L_CONSOLE = 0x2,
 };
Function Documentation
check_delayed_sigs()
static void check_delayed_sigs (struct timespec * ts) static
Definition at line 976 of file init.c.
 {
     int sig = sigtimedwait(&G.delayed_sigset, /* siginfo_t */ NULL, ts);
     if (sig <= 0)
         return;
     /* The signal "sig" was caught */
 #if ENABLE_FEATURE_USE_INITTAB
     if (sig == SIGHUP)
         reload_inittab();
 #endif
     if (sig == SIGINT)
         run_actions(CTRLALTDEL);
     if (sig == SIGQUIT) {
         exec_restart_action();
         /* returns only if no restart action defined */
     }
     if ((1 << sig) & (0
 #ifdef SIGPWR
         | (1 << SIGPWR)
 #endif
         | (1 << SIGUSR1)
         | (1 << SIGUSR2)
         | (1 << SIGTERM)
     )) {
         halt_reboot_pwoff(sig);
     }
     /* if (sig == SIGCHLD) do nothing */
 }
References CTRLALTDEL, exec_restart_action(), G, halt_reboot_pwoff(), NULL, run_actions(), SIGHUP, SIGINT, SIGPWR, SIGQUIT, SIGTERM, sigtimedwait(), SIGUSR1, and SIGUSR2.
Referenced by init_main().
console_init()
static void console_init (void) static
Definition at line 290 of file init.c.
 {
 #ifdef VT_OPENQRY
     int vtno;
 #endif
     char *s;
     s = getenv("CONSOLE");
     if (!s)
         s = getenv("console");
 #if defined(__FreeBSD__) || defined(__FreeBSD_kernel__)
     /* BSD people say their kernels do not open fd 0,1,2; they need this: */
     if (!s)
         s = (char*)"/dev/console";
 #endif
     if (s) {
         int fd = open(s, O_RDWR | O_NONBLOCK | O_NOCTTY);
         if (fd >= 0) {
             dup2(fd, STDIN_FILENO);
             dup2(fd, STDOUT_FILENO);
             xmove_fd(fd, STDERR_FILENO);
         }
         dbg_message(L_LOG, "console='%s'", s);
     } else {
         /* Make sure fd 0,1,2 are not closed
          * (so that they won't be used by future opens) */
         bb_sanitize_stdio();
 // Users report problems
 //      /* Make sure init can't be blocked by writing to stderr */
 //      fcntl(STDERR_FILENO, F_SETFL, fcntl(STDERR_FILENO, F_GETFL) | O_NONBLOCK);
     }
     s = getenv("TERM");
 #ifdef VT_OPENQRY
     if (ioctl(STDIN_FILENO, VT_OPENQRY, &vtno) != 0) {
         /* Not a linux terminal, probably serial console.
          * Force the TERM setting to vt102
          * if TERM is set to linux (the default) */
         if (!s || strcmp(s, "linux") == 0)
             putenv((char*)"TERM=vt102");
 # if !ENABLE_FEATURE_INIT_SYSLOG
         G.log_console = NULL;
 # endif
     } else
 #endif
     if (!s)
         putenv((char*)"TERM=" CONFIG_INIT_TERMINAL_TYPE);
 }
References bb_sanitize_stdio(), dbg_message, dup2(), fd, G, getenv, ioctl(), L_LOG, NULL, O_NOCTTY, O_NONBLOCK, O_RDWR, open(), putenv(), s, STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, strcmp, and xmove_fd().
Referenced by init_main().
exec_restart_action()
static void exec_restart_action (void) static
Definition at line 842 of file init.c.
 {
     struct init_action *a;
     for (a = G.init_action_list; a; a = a->next) {
         if (!(a->action_type & RESTART))
             continue;
         /* Starting from here, we won't return.
          * Thus don't need to worry about preserving errno
          * and such.
          */
         reset_sighandlers_and_unblock_sigs();
         run_shutdown_and_kill_processes();
 #ifdef RB_ENABLE_CAD
         /* Allow Ctrl-Alt-Del to reboot the system.
          * This is how kernel sets it up for init, we follow suit.
          */
         reboot(RB_ENABLE_CAD); /* misnomer */
 #endif
         if (open_stdio_to_tty(a->terminal)) {
             dbg_message(L_CONSOLE, "Trying to re-exec %s", a->command);
             /* Theoretically should be safe.
              * But in practice, kernel bugs may leave
              * unkillable processes, and wait() may block forever.
              * Oh well. Hoping "new" init won't be too surprised
              * by having children it didn't create.
              */
             //while (wait(NULL) > 0)
             //  continue;
             init_exec(a->command);
         }
         /* Open or exec failed */
         pause_and_low_level_reboot(RB_HALT_SYSTEM);
         /* not reached */
     }
 }
References init_action::action_type, init_action::command, dbg_message, G, init_exec(), L_CONSOLE, init_action::next, open_stdio_to_tty(), pause_and_low_level_reboot(), RB_ENABLE_CAD, RB_HALT_SYSTEM, reboot(), reset_sighandlers_and_unblock_sigs(), RESTART, run_shutdown_and_kill_processes(), and init_action::terminal.
Referenced by check_delayed_sigs().
halt_reboot_pwoff()
static void halt_reboot_pwoff (int sig) static
Definition at line 811 of file init.c.
 {
     const char *m;
     unsigned rb;
     /* We may call run() and it unmasks signals,
      * including the one masked inside this signal handler.
      * Testcase which would start multiple reboot scripts:
      *  while true; do reboot; done
      * Preventing it:
      */
     reset_sighandlers_and_unblock_sigs();
     run_shutdown_and_kill_processes();
     m = "halt";
     rb = RB_HALT_SYSTEM;
     if (sig == SIGTERM) {
         m = "reboot";
         rb = RB_AUTOBOOT;
     } else if (sig == SIGUSR2) {
         m = "poweroff";
         rb = RB_POWER_OFF;
     }
     message(L_CONSOLE, "Requesting system %s", m);
     pause_and_low_level_reboot(rb);
     /* not reached */
 }
References L_CONSOLE, message(), pause_and_low_level_reboot(), RB_AUTOBOOT, RB_HALT_SYSTEM, RB_POWER_OFF, reset_sighandlers_and_unblock_sigs(), run_shutdown_and_kill_processes(), SIGTERM, and SIGUSR2.
Referenced by check_delayed_sigs().
init_exec()
static void init_exec (const char * command) static
Definition at line 429 of file init.c.
 {
     /* +8 allows to write VLA sizes below more efficiently: */
     unsigned command_size = strlen(command) + 8;
     /* strlen(command) + strlen("exec ")+1: */
     char buf[command_size];
     /* strlen(command) / 2 + 4: */
     char *cmd[command_size / 2];
     int dash;
     dash = (command[0] == '-' /* maybe? && command[1] == '/' */);
     command += dash;
     /* See if any special /bin/sh requiring characters are present */
     if (strpbrk(command, "~`!$^&*()=|\\{}[];\"'<>?") != NULL) {
         sprintf(buf, "exec %s", command); /* excluding "-" */
         /* NB: LIBBB_DEFAULT_LOGIN_SHELL define has leading dash */
         cmd[0] = (char*)(LIBBB_DEFAULT_LOGIN_SHELL + !dash);
         cmd[1] = (char*)"-c";
         cmd[2] = buf;
         cmd[3] = NULL;
         command = LIBBB_DEFAULT_LOGIN_SHELL + 1;
     } else {
         /* Convert command (char*) into cmd (char**, one word per string) */
         char *word, *next;
         int i = 0;
         next = strcpy(buf, command - dash); /* command including "-" */
         command = next + dash;
         while ((word = strsep(&next, " \t")) != NULL) {
             if (*word != '\0') { /* not two spaces/tabs together? */
                 cmd[i] = word;
                 i++;
             }
         }
         cmd[i] = NULL;
     }
     /* If we saw leading "-", it is interactive shell.
      * Try harder to give it a controlling tty.
      */
     if (ENABLE_FEATURE_INIT_SCTTY && dash) {
         /* _Attempt_ to make stdin a controlling tty. */
         ioctl(STDIN_FILENO, TIOCSCTTY, 0 /*only try, don't steal*/);
     }
     /* Here command never contains the dash, cmd[0] might */
     BB_EXECVP(command, cmd);
     message(L_LOG | L_CONSOLE, "can't run '%s': "STRERROR_FMT, command STRERROR_ERRNO);
     /* returns if execvp fails */
 }
References BB_EXECVP, buf, cmd, i, ioctl(), L_CONSOLE, L_LOG, LIBBB_DEFAULT_LOGIN_SHELL, message(), next, NULL, sprintf(), STDIN_FILENO, strcpy(), STRERROR_ERRNO, STRERROR_FMT, strlen(), strpbrk(), strsep(), and TIOCSCTTY.
Referenced by exec_restart_action(), and run().
init_main()
int init_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 1039 of file init.c.
 {
     struct sigaction sa;
     INIT_G();
     /* Some users send poweroff signals to init VERY early.
      * To handle this, mask signals early.
      */
     /* sigemptyset(&G.delayed_sigset); - done by INIT_G() */
     sigaddset(&G.delayed_sigset, SIGINT);  /* Ctrl-Alt-Del */
     sigaddset(&G.delayed_sigset, SIGQUIT); /* re-exec another init */
 #ifdef SIGPWR
     sigaddset(&G.delayed_sigset, SIGPWR);  /* halt */
 #endif
     sigaddset(&G.delayed_sigset, SIGUSR1); /* halt */
     sigaddset(&G.delayed_sigset, SIGTERM); /* reboot */
     sigaddset(&G.delayed_sigset, SIGUSR2); /* poweroff */
 #if ENABLE_FEATURE_USE_INITTAB
     sigaddset(&G.delayed_sigset, SIGHUP);  /* reread /etc/inittab */
 #endif
     sigaddset(&G.delayed_sigset, SIGCHLD); /* make sigtimedwait() exit on SIGCHLD */
     sigprocmask(SIG_BLOCK, &G.delayed_sigset, NULL);
 #if DEBUG_SEGV_HANDLER
     memset(&sa, 0, sizeof(sa));
     sa.sa_sigaction = handle_sigsegv;
     sa.sa_flags = SA_SIGINFO;
     sigaction_set(SIGSEGV, &sa);
     sigaction_set(SIGILL, &sa);
     sigaction_set(SIGFPE, &sa);
     sigaction_set(SIGBUS, &sa);
 #endif
     if (argv[1] && strcmp(argv[1], "-q") == 0) {
         return kill(1, SIGHUP);
     }
 #if !DEBUG_INIT
     /* Expect to be invoked as init with PID=1 or be invoked as linuxrc */
     if (getpid() != 1
      && (!ENABLE_LINUXRC || applet_name[0] != 'l') /* not linuxrc? */
     ) {
         bb_simple_error_msg_and_die("must be run as PID 1");
     }
 # ifdef RB_DISABLE_CAD
     /* Turn off rebooting via CTL-ALT-DEL - we get a
      * SIGINT on CAD so we can shut things down gracefully... */
     reboot(RB_DISABLE_CAD); /* misnomer */
 # endif
 #endif
     /* If, say, xmalloc would ever die, we don't want to oops kernel
      * by exiting.
      * NB: we set die_func *after* PID 1 check and bb_show_usage.
      * Otherwise, for example, "init u" ("please rexec yourself"
      * command for sysvinit) will show help text (which isn't too bad),
      * *and sleep forever* (which is bad!)
      */
     die_func = sleep_much;
     /* Figure out where the default console should be */
     console_init();
     set_sane_term();
     xchdir("/");
     setsid();
     /* Make sure environs is set to something sane */
     putenv((char *) bb_PATH_root_path);
     putenv((char *) "SHELL=/bin/sh");
     putenv((char *) "USER=root"); /* needed? why? */
     /* Linux kernel sets HOME="/" when execing init,
      * and it can be overridden (but not unset?) on kernel's command line.
      * We used to set it to "/" here, but now we do not:
      */
     //putenv((char *) "HOME=/");
     if (argv[1])
         xsetenv("RUNLEVEL", argv[1]);
 #if !ENABLE_FEATURE_INIT_QUIET
     /* Hello world */
     message(L_CONSOLE | L_LOG, "init started: %s", bb_banner);
 #endif
     /* Check if we are supposed to be in single user mode */
     if (argv[1]
      && (strcmp(argv[1], "single") == 0 || strcmp(argv[1], "-s") == 0 || LONE_CHAR(argv[1], '1'))
     ) {
         /* ??? shouldn't we set RUNLEVEL="b" here? */
         /* Start a shell on console */
         new_init_action(RESPAWN, bb_default_login_shell, "");
     } else {
         /* Not in single user mode - see what inittab says */
         /* NOTE that if CONFIG_FEATURE_USE_INITTAB is NOT defined,
          * then parse_inittab() simply adds in some default
          * actions (i.e., INIT_SCRIPT and a pair
          * of "askfirst" shells) */
         parse_inittab();
     }
 #if ENABLE_SELINUX
     if (getenv("SELINUX_INIT") == NULL) {
         int enforce = 0;
         putenv((char*)"SELINUX_INIT=YES");
         if (selinux_init_load_policy(&enforce) == 0) {
             BB_EXECVP(argv[0], argv);
         } else if (enforce > 0) {
             /* SELinux in enforcing mode but load_policy failed */
             message(L_CONSOLE, "can't load SELinux Policy. "
                 "Machine is in enforcing mode. Halting now.");
             return EXIT_FAILURE;
         }
     }
 #endif
 #if ENABLE_FEATURE_INIT_MODIFY_CMDLINE
     /* Make the command line just say "init"  - that's all, nothing else */
     strncpy(argv[0], "init", strlen(argv[0]));
     /* Wipe argv[1]-argv[N] so they don't clutter the ps listing */
     while (*++argv)
         nuke_str(*argv);
 #endif
     /* Set up STOP signal handlers */
     /* Stop handler must allow only SIGCONT inside itself */
     memset(&sa, 0, sizeof(sa));
     sigfillset(&sa.sa_mask);
     sigdelset(&sa.sa_mask, SIGCONT);
     sa.sa_handler = stop_handler;
     sa.sa_flags = SA_RESTART;
     sigaction_set(SIGTSTP, &sa); /* pause */
     /* Does not work as intended, at least in 2.6.20.
      * SIGSTOP is simply ignored by init
      * (NB: behavior might differ under strace):
      */
     sigaction_set(SIGSTOP, &sa); /* pause */
     /* Now run everything that needs to be run */
     /* First run the sysinit command */
     run_actions(SYSINIT);
     check_delayed_sigs(&G.zero_ts);
     /* Next run anything that wants to block */
     run_actions(WAIT);
     check_delayed_sigs(&G.zero_ts);
     /* Next run anything to be run only once */
     run_actions(ONCE);
     /* Now run the looping stuff for the rest of forever */
     while (1) {
         /* (Re)run the respawn/askfirst stuff */
         run_actions(RESPAWN | ASKFIRST);
         /* Wait for any signal (typically it's SIGCHLD) */
         check_delayed_sigs(NULL); /* NULL timespec makes it wait */
         /* Wait for any child process(es) to exit */
         while (1) {
             pid_t wpid;
             struct init_action *a;
             wpid = waitpid(-1, NULL, WNOHANG);
             if (wpid <= 0)
                 break;
             a = mark_terminated(wpid);
             if (a) {
                 message(L_LOG, "process '%s' (pid %u) exited. "
                         "Scheduling for restart.",
                         a->command, (unsigned)wpid);
             }
         }
         /* Don't consume all CPU time - sleep a bit */
         sleep1();
     } /* while (1) */
 }
References applet_name, argv, ASKFIRST, BB_EXECVP, bb_simple_error_msg_and_die(), check_delayed_sigs(), init_action::command, console_init(), die_func, EXIT_FAILURE, G, getenv, getpid(), INIT_G, kill(), L_CONSOLE, L_LOG, LONE_CHAR, mark_terminated(), memset(), message(), new_init_action(), nuke_str(), NULL, ONCE, parse_inittab(), putenv(), RB_DISABLE_CAD, reboot(), RESPAWN, run_actions(), SA_RESTART, set_sane_term(), setsid(), SIG_BLOCK, sigaction_set(), sigaddset(), SIGBUS, SIGCHLD, SIGCONT, sigdelset(), sigfillset(), SIGFPE, SIGHUP, SIGILL, SIGINT, sigprocmask(), SIGPWR, SIGQUIT, SIGSEGV, SIGSTOP, SIGTERM, SIGTSTP, SIGUSR1, SIGUSR2, sleep1(), sleep_much(), stop_handler(), strcmp, strlen(), strncpy(), SYSINIT, waitpid(), WNOHANG, xchdir(), and xsetenv().
mark_terminated()
static struct init_action* mark_terminated (pid_t pid) static
Definition at line 556 of file init.c.
 {
     struct init_action *a;
     if (pid > 0) {
         update_utmp_DEAD_PROCESS(pid);
         for (a = G.init_action_list; a; a = a->next) {
             if (a->pid == pid) {
                 a->pid = 0;
                 return a;
             }
         }
     }
     return NULL;
 }
References G, init_action::next, NULL, init_action::pid, pid, and update_utmp_DEAD_PROCESS().
Referenced by init_main(), stop_handler(), and waitfor().
message()
static void static void message (int where, const char * fmt, ...) static
Definition at line 234 of file init.c.
 {
     va_list arguments;
     unsigned l;
     char msg[128];
     msg[0] = '\r';
     va_start(arguments, fmt);
     l = 1 + vsnprintf(msg + 1, sizeof(msg) - 2, fmt, arguments);
     if (l > sizeof(msg) - 2)
         l = sizeof(msg) - 2;
     va_end(arguments);
 #if ENABLE_FEATURE_INIT_SYSLOG
     msg[l] = '\0';
     if (where & L_LOG) {
         /* Log the message to syslogd */
         openlog(applet_name, 0, LOG_DAEMON);
         /* don't print "\r" */
         syslog(LOG_INFO, "%s", msg + 1);
         closelog();
     }
     msg[l++] = '\n';
     msg[l] = '\0';
 #else
     msg[l++] = '\n';
     msg[l] = '\0';
     if (where & L_LOG) {
         /* Take full control of the log tty, and never close it.
          * It's mine, all mine!  Muhahahaha! */
         static int log_fd = -1;
         if (log_fd < 0) {
             log_fd = STDERR_FILENO;
             if (G.log_console) {
                 log_fd = device_open(G.log_console, O_WRONLY | O_NONBLOCK | O_NOCTTY);
                 if (log_fd < 0) {
                     bb_error_msg("can't log to %s", G.log_console);
                     where = L_CONSOLE;
                 } else {
                     close_on_exec_on(log_fd);
                 }
             }
         }
         full_write(log_fd, msg, l);
         if (log_fd == STDERR_FILENO)
             return; /* don't print dup messages */
     }
 #endif
     if (where & L_CONSOLE) {
         /* Send console messages to console so people will see them. */
         full_write(STDERR_FILENO, msg, l);
     }
 }
References applet_name, bb_error_msg(), close_on_exec_on(), closelog(), device_open(), full_write(), G, l, L_CONSOLE, L_LOG, LOG_DAEMON, log_fd, LOG_INFO, O_NOCTTY, O_NONBLOCK, O_WRONLY, openlog(), STDERR_FILENO, syslog(), va_end, va_start, and vsnprintf().
Referenced by check_mail(), halt_reboot_pwoff(), I_Error(), init_exec(), init_main(), open_stdio_to_tty(), parse_inittab(), rl_display_search(), run(), run_shutdown_and_kill_processes(), text_insert_msg(), and udhcpc_main().
new_init_action()
static void new_init_action (uint8_t action_type, const char * command, const char * cons) static
Definition at line 617 of file init.c.
 {
     struct init_action *a, **nextp;
     /* Scenario:
      * old inittab:
      * ::shutdown:umount -a -r
      * ::shutdown:swapoff -a
      * new inittab:
      * ::shutdown:swapoff -a
      * ::shutdown:umount -a -r
      * On reload, we must ensure entries end up in correct order.
      * To achieve that, if we find a matching entry, we move it
      * to the end.
      */
     nextp = &G.init_action_list;
     while ((a = *nextp) != NULL) {
         /* Don't enter action if it's already in the list.
          * This prevents losing running RESPAWNs.
          */
         if (strcmp(a->command, command) == 0
          && strcmp(a->terminal, cons) == 0
         ) {
             /* Remove from list */
             *nextp = a->next;
             /* Find the end of the list */
             while (*nextp != NULL)
                 nextp = &(*nextp)->next;
             a->next = NULL;
             goto append;
         }
         nextp = &a->next;
     }
     a = xzalloc(sizeof(*a) + strlen(command));
     /* Append to the end of the list */
  append:
     *nextp = a;
     a->action_type = action_type;
     strcpy(a->command, command);
     safe_strncpy(a->terminal, cons, sizeof(a->terminal));
     dbg_message(L_LOG | L_CONSOLE, "command='%s' action=%x tty='%s'\n",
         a->command, a->action_type, a->terminal);
 }
References init_action::action_type, append(), init_action::command, dbg_message, G, L_CONSOLE, L_LOG, init_action::next, NULL, safe_strncpy(), strcmp, strcpy(), strlen(), init_action::terminal, and xzalloc().
Referenced by init_main(), and parse_inittab().
open_stdio_to_tty()
static int open_stdio_to_tty (const char * tty_name) static
Definition at line 390 of file init.c.
 {
     /* empty tty_name means "use init's tty", else... */
     if (tty_name[0]) {
         int fd;
         close(STDIN_FILENO);
         /* fd can be only < 0 or 0: */
         fd = device_open(tty_name, O_RDWR);
         if (fd) {
             message(L_LOG | L_CONSOLE, "can't open %s: "STRERROR_FMT,
                 tty_name
                 STRERROR_ERRNO
             );
             return 0; /* failure */
         }
         dup2(STDIN_FILENO, STDOUT_FILENO);
         dup2(STDIN_FILENO, STDERR_FILENO);
     }
     set_sane_term();
     return 1; /* success */
 }
References close(), device_open(), dup2(), fd, L_CONSOLE, L_LOG, message(), O_RDWR, set_sane_term(), STDERR_FILENO, STDIN_FILENO, STDOUT_FILENO, STRERROR_ERRNO, and STRERROR_FMT.
Referenced by exec_restart_action(), and run().
parse_inittab()
static void parse_inittab (void) static
Definition at line 670 of file init.c.
 {
 #if ENABLE_FEATURE_USE_INITTAB
     char *token[4];
     parser_t *parser = config_open2("/etc/inittab", fopen_for_read);
     if (parser == NULL)
 #endif
     {
         /* No inittab file - set up some default behavior */
         /* Sysinit */
         new_init_action(SYSINIT, INIT_SCRIPT, "");
         /* Askfirst shell on tty1-4 */
         new_init_action(ASKFIRST, bb_default_login_shell, "");
 //TODO: VC_1 instead of ""? "" is console -> ctty problems -> angry users
         new_init_action(ASKFIRST, bb_default_login_shell, VC_2);
         new_init_action(ASKFIRST, bb_default_login_shell, VC_3);
         new_init_action(ASKFIRST, bb_default_login_shell, VC_4);
         /* Reboot on Ctrl-Alt-Del */
         new_init_action(CTRLALTDEL, "reboot", "");
         /* Umount all filesystems on halt/reboot */
         new_init_action(SHUTDOWN, "umount -a -r", "");
         /* Swapoff on halt/reboot */
         new_init_action(SHUTDOWN, "swapoff -a", "");
         /* Restart init when a QUIT is received */
         new_init_action(RESTART, "init", "");
         return;
     }
 #if ENABLE_FEATURE_USE_INITTAB
     /* optional_tty:ignored_runlevel:action:command
      * Delims are not to be collapsed and need exactly 4 tokens
      */
     while (config_read(parser, token, 4, 0, "#:",
                 PARSE_NORMAL & ~(PARSE_TRIM | PARSE_COLLAPSE))) {
         /* order must correspond to SYSINIT..RESTART constants */
         static const char actions[] ALIGN1 =
             "sysinit\0""wait\0""once\0""respawn\0""askfirst\0"
             "ctrlaltdel\0""shutdown\0""restart\0";
         int action;
         char *tty = token[0];
         if (!token[3]) /* less than 4 tokens */
             goto bad_entry;
         action = index_in_strings(actions, token[2]);
         if (action < 0 || !token[3][0]) /* token[3]: command */
             goto bad_entry;
         /* turn .*TTY -> /dev/TTY */
         if (tty[0]) {
             tty = concat_path_file("/dev/", skip_dev_pfx(tty));
         }
         new_init_action(1 << action, token[3], tty);
         if (tty[0])
             free(tty);
         continue;
  bad_entry:
         message(L_LOG | L_CONSOLE, "Bad inittab entry at line %d",
                 parser->lineno);
     }
     config_close(parser);
 #endif
 }
References ALIGN1, ASKFIRST, concat_path_file(), config_close(), config_open2(), config_read, CTRLALTDEL, fopen_for_read(), free, index_in_strings(), INIT_SCRIPT, L_CONSOLE, L_LOG, message(), new_init_action(), NULL, PARSE_COLLAPSE, PARSE_NORMAL, PARSE_TRIM, parser, RESTART, SHUTDOWN, skip_dev_pfx(), SYSINIT, VC_2, VC_3, and VC_4.
Referenced by init_main().
pause_and_low_level_reboot()
static void pause_and_low_level_reboot (unsigned magic) static
Definition at line 734 of file init.c.
 {
     pid_t pid;
     /* Allow time for last message to reach serial console, etc */
     sleep1();
     /* We have to fork here, since the kernel calls do_exit(EXIT_SUCCESS)
      * in linux/kernel/sys.c, which can cause the machine to panic when
      * the init process exits... */
     pid = vfork();
     if (pid == 0) { /* child */
         reboot(magic);
         _exit_SUCCESS();
     }
     /* Used to have "while (1) sleep(1)" here.
      * However, in containers reboot() call is ignored, and with that loop
      * we would eternally sleep here - not what we want.
      */
     waitpid(pid, NULL, 0);
     sleep1(); /* paranoia */
     _exit_SUCCESS();
 }
References _exit_SUCCESS(), NULL, pid, reboot(), sleep1(), vfork(), and waitpid().
Referenced by exec_restart_action(), and halt_reboot_pwoff().
reset_sighandlers_and_unblock_sigs()
static void reset_sighandlers_and_unblock_sigs (void) static
Definition at line 413 of file init.c.
 {
     bb_signals(0
         | (1 << SIGTSTP)
         | (1 << SIGSTOP)
         , SIG_DFL);
     sigprocmask_allsigs(SIG_UNBLOCK);
 }
References bb_signals(), SIG_DFL, sigprocmask_allsigs(), SIGSTOP, and SIGTSTP.
Referenced by exec_restart_action(), halt_reboot_pwoff(), and run().
run()
static pid_t run (const struct init_action * a) static
Definition at line 479 of file init.c.
 {
     pid_t pid;
     if (BB_MMU && (a->action_type & ASKFIRST))
         pid = fork();
     else
         pid = vfork();
     if (pid) {
         if (pid < 0)
             message(L_LOG | L_CONSOLE, "can't fork");
         return pid; /* Parent or error */
     }
     /* Child */
     /* Reset signal handlers that were set by the parent process */
     reset_sighandlers_and_unblock_sigs();
     /* Create a new session and make ourself the process group leader */
     setsid();
     /* Open the new terminal device */
     if (!open_stdio_to_tty(a->terminal))
         _exit(EXIT_FAILURE);
     /* NB: on NOMMU we can't wait for input in child, so
      * "askfirst" will work the same as "respawn". */
     if (BB_MMU && (a->action_type & ASKFIRST)) {
         static const char press_enter[] ALIGN1 =
 #ifdef CUSTOMIZED_BANNER
 #include CUSTOMIZED_BANNER
 #endif
             "\nPlease press Enter to activate this console. ";
         char c;
         /*
          * Save memory by not exec-ing anything large (like a shell)
          * before the user wants it. This is critical if swap is not
          * enabled and the system has low memory. Generally this will
          * be run on the second virtual console, and the first will
          * be allowed to start a shell or whatever an init script
          * specifies.
          */
         dbg_message(L_LOG, "waiting for enter to start '%s'"
                     "(pid %d, tty '%s')\n",
                 a->command, getpid(), a->terminal);
         full_write(STDOUT_FILENO, press_enter, sizeof(press_enter) - 1);
         while (safe_read(STDIN_FILENO, &c, 1) == 1 && c != '\n')
             continue;
     }
     /*
      * When a file named /.init_enable_core exists, setrlimit is called
      * before processes are spawned to set core file size as unlimited.
      * This is for debugging only.  Don't use this is production, unless
      * you want core dumps lying about....
      */
     if (ENABLE_FEATURE_INIT_COREDUMPS) {
         if (access("/.init_enable_core", F_OK) == 0) {
             struct rlimit limit;
             limit.rlim_cur = RLIM_INFINITY;
             limit.rlim_max = RLIM_INFINITY;
             setrlimit(RLIMIT_CORE, &limit);
         }
     }
     /* Log the process name and args */
     message(L_LOG, "starting pid %u, tty '%s': '%s'",
             (int)getpid(), a->terminal, a->command);
     /* Now run it.  The new program will take over this PID,
      * so nothing further in init.c should be run. */
     init_exec(a->command);
     /* We're still here?  Some error happened. */
     _exit(-1);
 }
References _exit(), access(), init_action::action_type, ALIGN1, ASKFIRST, BB_MMU, c, init_action::command, dbg_message, EXIT_FAILURE, F_OK, fork(), full_write(), getpid(), init_exec(), L_CONSOLE, L_LOG, limit(), message(), open_stdio_to_tty(), pid, reset_sighandlers_and_unblock_sigs(), RLIM_INFINITY, RLIMIT_CORE, safe_read(), setrlimit(), setsid(), STDIN_FILENO, STDOUT_FILENO, init_action::terminal, and vfork().
Referenced by _pthread_cleanup_pop(), generateMTFValues(), run_actions(), and runsvdir_main().
run_actions()
static void run_actions (int action_type) static
Definition at line 594 of file init.c.
 {
     struct init_action *a;
     for (a = G.init_action_list; a; a = a->next) {
         if (!(a->action_type & action_type))
             continue;
         if (a->action_type & (SYSINIT | WAIT | ONCE | CTRLALTDEL | SHUTDOWN)) {
             pid_t pid = run(a);
             if (a->action_type & (SYSINIT | WAIT | CTRLALTDEL | SHUTDOWN))
                 waitfor(pid);
         }
         if (a->action_type & (RESPAWN | ASKFIRST)) {
             /* Only run stuff with pid == 0. If pid != 0,
              * it is already running
              */
             if (a->pid == 0)
                 a->pid = run(a);
         }
     }
 }
References init_action::action_type, ASKFIRST, CTRLALTDEL, G, init_action::next, ONCE, init_action::pid, pid, RESPAWN, run(), SHUTDOWN, SYSINIT, and waitfor().
Referenced by check_delayed_sigs(), init_main(), and run_shutdown_and_kill_processes().
run_shutdown_and_kill_processes()
static void run_shutdown_and_kill_processes (void) static
Definition at line 758 of file init.c.
 {
     /* Run everything to be run at "shutdown".  This is done _prior_
      * to killing everything, in case people wish to use scripts to
      * shut things down gracefully... */
     run_actions(SHUTDOWN);
     message(L_CONSOLE | L_LOG, "The system is going down NOW!");
     /* Send signals to every process _except_ pid 1 */
     kill(-1, SIGTERM);
     message(L_CONSOLE, "Sent SIG%s to all processes", "TERM");
     sync();
     sleep1();
     kill(-1, SIGKILL);
     message(L_CONSOLE, "Sent SIG%s to all processes", "KILL");
     sync();
     /*sleep1(); - callers take care about making a pause */
 }
References kill(), L_CONSOLE, L_LOG, message(), run_actions(), SHUTDOWN, SIGKILL, SIGTERM, sleep1(), and sync().
Referenced by exec_restart_action(), and halt_reboot_pwoff().
set_sane_term()
static void set_sane_term (void) static
Definition at line 341 of file init.c.
 {
     struct termios tty;
     if (tcgetattr(STDIN_FILENO, &tty) != 0)
         return;
     /* set control chars */
     tty.c_cc[VINTR] = 3;    /* C-c */
     tty.c_cc[VQUIT] = 28;   /* C-\ */
     tty.c_cc[VERASE] = 127; /* C-? */
     tty.c_cc[VKILL] = 21;   /* C-u */
     tty.c_cc[VEOF] = 4; /* C-d */
     tty.c_cc[VSTART] = 17;  /* C-q */
     tty.c_cc[VSTOP] = 19;   /* C-s */
     tty.c_cc[VSUSP] = 26;   /* C-z */
 #ifdef __linux__
     /* use line discipline 0 */
     tty.c_line = 0;
 #endif
     /* Make it be sane */
 /* On systems where the baud rate is stored in a separate field, we can safely disable these. */
 #ifndef CBAUD
 # define CBAUD 0
 # define CBAUDEX 0
 #endif
 /* Added CRTSCTS to fix Debian bug 528560 */
 #ifndef CRTSCTS
 # define CRTSCTS 0
 #endif
     tty.c_cflag &= CBAUD | CBAUDEX | CSIZE | CSTOPB | PARENB | PARODD | CRTSCTS;
     tty.c_cflag |= CREAD | HUPCL | CLOCAL;
     /* input modes */
     tty.c_iflag = ICRNL | IXON | IXOFF;
     /* output modes */
     tty.c_oflag = OPOST | ONLCR;
     /* local modes */
     tty.c_lflag = ISIG | ICANON | ECHO | ECHOE | ECHOK | ECHOCTL | ECHOKE | IEXTEN;
     tcsetattr_stdin_TCSANOW(&tty);
 }
References termios::c_cc, termios::c_cflag, termios::c_iflag, termios::c_lflag, termios::c_line, termios::c_oflag, CBAUD, CBAUDEX, CLOCAL, CREAD, CRTSCTS, CSIZE, CSTOPB, ECHO, ECHOCTL, ECHOE, ECHOK, ECHOKE, HUPCL, ICANON, ICRNL, IEXTEN, ISIG, IXOFF, IXON, ONLCR, OPOST, PARENB, PARODD, STDIN_FILENO, tcgetattr(), tcsetattr_stdin_TCSANOW(), VEOF, VERASE, VINTR, VKILL, VQUIT, VSTART, VSTOP, and VSUSP.
Referenced by init_main(), and open_stdio_to_tty().
sleep_much()
static void sleep_much (void) static
Definition at line 1033 of file init.c.
 {
     sleep(30 * 24*60*60);
 }
References sleep().
Referenced by init_main().
stop_handler()
static void stop_handler (int sig UNUSED_PARAM) static
Definition at line 888 of file init.c.
 {
     int saved_errno = errno;
     bb_got_signal = 0;
     signal(SIGCONT, record_signo);
     while (1) {
         pid_t wpid;
         if (bb_got_signal == SIGCONT)
             break;
         /* NB: this can accidentally wait() for a process
          * which we waitfor() elsewhere! waitfor() must have
          * code which is resilient against this.
          */
         wpid = wait_any_nohang(NULL);
         mark_terminated(wpid);
         if (wpid <= 0) /* no processes exited? sleep a bit */
             sleep1();
     }
     signal(SIGCONT, SIG_DFL);
     errno = saved_errno;
 }
References bb_got_signal, errno, mark_terminated(), NULL, record_signo(), saved_errno, SIG_DFL, SIGCONT, signal, sleep1(), and wait_any_nohang().
Referenced by init_main().
waitfor()
static void waitfor (pid_t pid) static
Definition at line 572 of file init.c.
 {
     /* waitfor(run(x)): protect against failed fork inside run() */
     if (pid <= 0)
         return;
     /* Wait for any child (prevent zombies from exiting orphaned processes)
      * but exit the loop only when specified one has exited. */
     while (1) {
         pid_t wpid = wait(NULL);
         mark_terminated(wpid);
         if (wpid == pid) /* this was the process we waited for */
             break;
         /* The above is not reliable enough: SIGTSTP handler might have
          * wait'ed it already. Double check, exit if process is gone:
          */
         if (kill(pid, 0))
             break;
     }
 }
References kill(), mark_terminated(), NULL, pid, and wait().
Referenced by run_actions().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING