Fennix Userspace: Userspace/apps/base/busybox/networking/httpd_ssi.c File Reference
httpd_ssi.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>
#include <dirent.h>
#include <time.h>
Macros
#define INCLUDE "<!--#include"
Functions
static char * skip_whitespace (char *s)
static void process_includes (const char *filename)
int main (int argc, char **argv)
Variables
static char line [64 *1024]
Macro Definition Documentation
INCLUDE
#define INCLUDE "<!--#include"
Function Documentation
main()
int main (int argc , char ** argv)
Definition at line 146 of file httpd_ssi.c.
 {
     if (!argv[1])
         return 1;
     /* Seen from busybox.net's Apache:
      * HTTP/1.1 200 OK
      * Date: Thu, 10 Sep 2009 18:23:28 GMT
      * Server: Apache
      * Accept-Ranges: bytes
      * Connection: close
      * Content-Type: text/html
      */
     fputs(
         /* "Date: Thu, 10 Sep 2009 18:23:28 GMT\r\n" */
         /* "Server: Apache\r\n" */
         /* "Accept-Ranges: bytes\r\n" - do we really accept bytes?! */
         "Connection: close\r\n"
         "Content-Type: text/html\r\n"
         "\r\n",
         stdout
     );
     process_includes(argv[1]);
     return 0;
 }
References argv, fputs, process_includes(), and stdout.
process_includes()
static void process_includes (const char * filename) static
Definition at line 62 of file httpd_ssi.c.
 {
     int curdir_fd;
     char *end;
     FILE *fp = fopen(filename, "r");
     if (!fp)
         exit(1);
     /* Ensure that nested includes are relative:
      * if we include a/1.htm and it includes b/2.htm,
      * we need to include a/b/2.htm, not b/2.htm
      */
     curdir_fd = -1;
     end = strrchr(filename, '/');
     if (end) {
         curdir_fd = open(".", O_RDONLY);
         /* *end = '\0' would mishandle "/file.htm" */
         end[1] = '\0';
         chdir(filename);
     }
 #define INCLUDE "<!--#include"
     while (fgets(line, sizeof(line), fp)) {
         unsigned preceding_len;
         char *include_directive;
         include_directive = strstr(line, INCLUDE);
         if (!include_directive) {
             fputs(line, stdout);
             continue;
         }
         preceding_len = include_directive - line;
         if (memchr(line, '\"', preceding_len)
          || memchr(line, '\'', preceding_len)
         ) {
             /* INCLUDE string may be inside "str" or 'str',
              * ignore it */
             fputs(line, stdout);
             continue;
         }
         /* Small bug: we accept #includefile="file" too */
         include_directive = skip_whitespace(include_directive + sizeof(INCLUDE)-1);
         if (strncmp(include_directive, "file=\"", 6) != 0) {
             /* "<!--#include virtual=..."? - not supported */
             fputs(line, stdout);
             continue;
         }
         include_directive += 6; /* now it points to file name */
         end = strchr(include_directive, '\"');
         if (!end) {
             fputs(line, stdout);
             continue;
         }
         /* We checked that this is a valid include directive */
         /* Print everything before directive */
         if (preceding_len) {
             line[preceding_len] = '\0';
             fputs(line, stdout);
         }
         /* Save everything after directive */
         *end++ = '\0';
         end = strchr(end, '>');
         if (end)
             end = strdup(end + 1);
         /* FIXME:
          * (1) are relative paths with /../ etc ok?
          * (2) what to do with absolute paths?
          * are they relative to doc root or to real root?
          */
         process_includes(include_directive);
         /* Print everything after directive */
         if (end) {
             fputs(end, stdout);
             free(end);
         }
     }
     if (curdir_fd >= 0)
         fchdir(curdir_fd);
     fclose(fp);
 }
References chdir(), end, exit(), fchdir(), fclose(), fgets, filename, fopen(), fputs, free, INCLUDE, line, memchr(), O_RDONLY, open(), skip_whitespace(), stdout, strchr(), strdup(), strncmp(), strrchr(), and strstr().
Referenced by main().
skip_whitespace()
static char* skip_whitespace (char * s) static
Definition at line 53 of file httpd_ssi.c.
 {
     while (*s == ' ' || *s == '\t') ++s;
     return s;
 }
References s.
Referenced by process_includes().
Variable Documentation
line
char line[64 *1024] static
Definition at line 60 of file httpd_ssi.c.
Referenced by process_includes().