Fennix Userspace: Userspace/apps/base/busybox/libbb/fgets_str.c File Reference
fgets_str.c File Reference
#include "libbb.h"
Functions
static char * xmalloc_fgets_internal (FILE *file, const char *terminating_string, int chop_off, size_t *maxsz_p)
char *FAST_FUNC xmalloc_fgets_str (FILE *file, const char *terminating_string)
char *FAST_FUNC xmalloc_fgets_str_len (FILE *file, const char *terminating_string, size_t *maxsz_p)
char *FAST_FUNC xmalloc_fgetline_str (FILE *file, const char *terminating_string)
Function Documentation
xmalloc_fgetline_str()
char* FAST_FUNC xmalloc_fgetline_str (FILE * file, const char * terminating_string)
Definition at line 75 of file fgets_str.c.
 {
     return xmalloc_fgets_internal(file, terminating_string, 1, NULL);
 }
References NULL, and xmalloc_fgets_internal().
Referenced by index_status_file(), and write_status_file().
xmalloc_fgets_internal()
static char* xmalloc_fgets_internal (FILE * file, const char * terminating_string, int chop_off, size_t * maxsz_p) static
Definition at line 12 of file fgets_str.c.
 {
     char *linebuf = NULL;
     const int term_length = strlen(terminating_string);
     int end_string_offset;
     int linebufsz = 0;
     int idx = 0;
     int ch;
     size_t maxsz = maxsz_p ? *maxsz_p : INT_MAX - 4095;
     while (1) {
         ch = fgetc(file);
         if (ch == EOF) {
             if (idx == 0)
                 return linebuf; /* NULL */
             break;
         }
         if (idx >= linebufsz) {
             linebufsz += 200;
             linebuf = xrealloc(linebuf, linebufsz);
             if (idx >= maxsz) {
                 linebuf[idx] = ch;
                 idx++;
                 break;
             }
         }
         linebuf[idx] = ch;
         idx++;
         /* Check for terminating string */
         end_string_offset = idx - term_length;
         if (end_string_offset >= 0
          && memcmp(&linebuf[end_string_offset], terminating_string, term_length) == 0
         ) {
             if (chop_off)
                 idx -= term_length;
             break;
         }
     }
     /* Grow/shrink *first*, then store NUL */
     linebuf = xrealloc(linebuf, idx + 1);
     linebuf[idx] = '\0';
     if (maxsz_p)
         *maxsz_p = idx;
     return linebuf;
 }
References EOF, fgetc, idx, INT_MAX, memcmp(), NULL, strlen(), and xrealloc.
Referenced by xmalloc_fgetline_str(), xmalloc_fgets_str(), and xmalloc_fgets_str_len().
xmalloc_fgets_str()
char* FAST_FUNC xmalloc_fgets_str (FILE * file, const char * terminating_string)
Definition at line 65 of file fgets_str.c.
 {
     return xmalloc_fgets_internal(file, terminating_string, 0, NULL);
 }
References NULL, and xmalloc_fgets_internal().
Referenced by do_info(), and popmaildir_main().
xmalloc_fgets_str_len()
char* FAST_FUNC xmalloc_fgets_str_len (FILE * file, const char * terminating_string, size_t * maxsz_p)
Definition at line 70 of file fgets_str.c.
 {
     return xmalloc_fgets_internal(file, terminating_string, 0, maxsz_p);
 }
References xmalloc_fgets_internal().
Referenced by cmdio_get_cmd_and_arg().