Fennix Userspace: Userspace/apps/base/busybox/util-linux/findfs.c File Reference
findfs.c File Reference
#include "libbb.h"
#include "volume_id.h"
Functions
int findfs_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
findfs_main()
int findfs_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 34 of file findfs.c.
 {
     char *dev = *++argv;
     if (!dev)
         bb_show_usage();
     if (is_prefixed_with(dev, "/dev/")) {
         /* Just pass any /dev/xxx name right through.
          * This might aid in some scripts being able
          * to call this unconditionally */
         dev = NULL;
     } else {
         /* Otherwise, handle LABEL=xxx and UUID=xxx,
          * fail on anything else */
         if (!resolve_mount_spec(argv))
             bb_show_usage();
     }
     if (*argv != dev) {
         puts(*argv);
         return 0;
     }
     return 1;
 }
References argv, bb_show_usage(), is_prefixed_with(), NULL, puts(), and resolve_mount_spec.