Fennix: Userspace/musl/src/env/unsetenv.c File Reference
unsetenv.c File Reference
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
Functions
static void dummy (char *old, char *new)
weak_alias (dummy, __env_rm_add)
int unsetenv (const char *name)
Function Documentation
dummy()
static void dummy (char * old, char * new) static
Definition at line 6 of file unsetenv.c.
 {}
unsetenv()
int unsetenv (const char * name)
Definition at line 9 of file unsetenv.c.
 {
     size_t l = __strchrnul(name, '=') - name;
     if (!l || name[l]) {
         errno = EINVAL;
         return -1;
     }
     if (__environ) {
         char **e = __environ, **eo = e;
         for (; *e; e++)
             if (!strncmp(name, *e, l) && l[*e] == '=')
                 __env_rm_add(*e, 0);
             else if (eo != e)
                 *eo++ = *e;
             else
                 eo++;
         if (eo != e) *eo = 0;
     }
     return 0;
 }
References __env_rm_add(), __environ, __strchrnul(), EINVAL, errno, l, and strncmp().
Referenced by bb_unsetenv(), edir(), hush_main(), popmaildir_main(), putenv(), rtc_tm2time(), run_script(), sanitize_env_if_suid(), and set_local_var().
weak_alias()
weak_alias (dummy , __env_rm_add)