Fennix Userspace: Userspace/musl/src/string/strerror_r.c File Reference
strerror_r.c File Reference
#include <string.h>
#include <errno.h>
Functions
int strerror_r (int err, char *buf, size_t buflen)
weak_alias (strerror_r, __xpg_strerror_r)
Function Documentation
strerror_r()
int strerror_r (int err, char * buf, size_t buflen)
Definition at line 4 of file strerror_r.c.
 {
     char *msg = strerror(err);
     size_t l = strlen(msg);
     if (l >= buflen) {
         if (buflen) {
             memcpy(buf, msg, buflen-1);
             buf[buflen-1] = 0;
         }
         return ERANGE;
     }
     memcpy(buf, msg, l+1);
     return 0;
 }
References buf, buflen, ERANGE, err(), l, memcpy(), strerror(), and strlen().
weak_alias()
weak_alias (strerror_r , __xpg_strerror_r)