Fennix: Userspace/apps/base/busybox/loginutils/chpasswd.c File Reference
chpasswd.c File Reference
#include "libbb.h"
Macros
#define OPT_ENC 1
#define OPT_MD5 2
Functions
int chpasswd_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
OPT_ENC
#define OPT_ENC 1
Definition at line 46 of file chpasswd.c.
OPT_MD5
#define OPT_MD5 2
Definition at line 47 of file chpasswd.c.
Function Documentation
chpasswd_main()
int chpasswd_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 50 of file chpasswd.c.
 {
     char *name;
     const char *algo = CONFIG_FEATURE_DEFAULT_PASSWD_ALGO;
     const char *root = NULL;
     int opt;
     if (getuid() != 0)
         bb_simple_error_msg_and_die(bb_msg_perm_denied_are_you_root);
     opt = getopt32long(argv, "^" "emc:R:" "\0" "m--ec:e--mc:c--em",
             chpasswd_longopts,
             &algo, &root
     );
     if (root) {
         xchroot(root);
     }
     while ((name = xmalloc_fgetline(stdin)) != NULL) {
         char *free_me;
         char *pass;
         int rc;
         pass = strchr(name, ':');
         if (!pass)
             bb_simple_error_msg_and_die("missing new password");
         *pass++ = '\0';
         xuname2uid(name); /* dies if there is no such user */
         free_me = NULL;
         if (!(opt & OPT_ENC)) {
             char salt[MAX_PW_SALT_LEN];
             if (opt & OPT_MD5) {
                 /* Force MD5 if the -m flag is set */
                 algo = "md5";
             }
             crypt_make_pw_salt(salt, algo);
             free_me = pass = pw_encrypt(pass, salt, 0);
         }
         /* This is rather complex: if user is not found in /etc/shadow,
          * we try to find & change his passwd in /etc/passwd */
 #if ENABLE_FEATURE_SHADOWPASSWDS
         rc = update_passwd(bb_path_shadow_file, name, pass, NULL);
         if (rc > 0) /* password in /etc/shadow was updated */
             pass = (char*)"x";
         if (rc >= 0)
             /* 0 = /etc/shadow missing (not an error), >0 = passwd changed in /etc/shadow */
 #endif
             rc = update_passwd(bb_path_passwd_file, name, pass, NULL);
         /* LOGMODE_BOTH logs to syslog also */
         logmode = LOGMODE_BOTH;
         if (rc < 0)
             bb_error_msg_and_die("an error occurred updating password for %s", name);
         if (rc)
             bb_info_msg("password for '%s' changed", name);
         logmode = LOGMODE_STDIO;
         free(name);
         free(free_me);
     }
     return EXIT_SUCCESS;
 }
References argv, bb_error_msg_and_die(), bb_info_msg, bb_path_passwd_file, bb_path_shadow_file, bb_simple_error_msg_and_die(), crypt_make_pw_salt(), EXIT_SUCCESS, free, getopt32long, getuid, logmode, LOGMODE_BOTH, LOGMODE_STDIO, MAX_PW_SALT_LEN, NULL, opt, OPT_ENC, OPT_MD5, pw_encrypt, rc, stdin, strchr(), update_passwd, xchroot(), xmalloc_fgetline(), and xuname2uid().