Fennix: Userspace/mlibc/options/ansi/include/wctype.h File Reference
wctype.h File Reference
#include <mlibc-config.h>
#include <bits/wint_t.h>
Typedefs
typedef unsigned long wctype_t
typedef unsigned long wctrans_t
Functions
int iswalnum (wint_t)
int iswalpha (wint_t)
int iswblank (wint_t)
int iswcntrl (wint_t)
int iswdigit (wint_t)
int iswgraph (wint_t)
int iswlower (wint_t)
int iswprint (wint_t)
int iswpunct (wint_t)
int iswspace (wint_t)
int iswupper (wint_t)
int iswxdigit (wint_t)
wctype_t wctype (const char *)
int iswctype (wint_t, wctype_t)
wint_t towlower (wint_t)
wint_t towupper (wint_t)
wctrans_t wctrans (const char *)
wint_t towctrans (wint_t, wctrans_t)
Typedef Documentation
wctrans_t
typedef unsigned long wctrans_t
Definition at line 12 of file wctype.h.
wctype_t
typedef unsigned long wctype_t
Definition at line 11 of file wctype.h.
Function Documentation
iswalnum()
int iswalnum (wint_t nc)
Definition at line 144 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_alnum(cp);
 }
iswalpha()
int iswalpha (wint_t nc)
Definition at line 120 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_alpha(cp);
 }
iswblank()
int iswblank (wint_t nc)
Definition at line 168 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_blank(cp);
 }
iswcntrl()
int iswcntrl (wint_t nc)
Definition at line 208 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::generic_is_control(cp);
 }
iswctype()
int iswctype (wint_t wc, wctype_t type)
Definition at line 257 of file ctype-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
iswdigit()
int iswdigit (wint_t nc)
Definition at line 128 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_digit(cp);
 }
iswgraph()
int iswgraph (wint_t nc)
Definition at line 160 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_graph(cp);
 }
iswlower()
int iswlower (wint_t nc)
Definition at line 192 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_lower(cp);
 }
iswprint()
int iswprint (wint_t nc)
Definition at line 184 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_print(cp);
 }
iswpunct()
int iswpunct (wint_t nc)
Definition at line 152 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_punct(cp);
 }
iswspace()
int iswspace (wint_t nc)
Definition at line 176 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_space(cp);
 }
iswupper()
int iswupper (wint_t nc)
Definition at line 200 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_upper(cp);
 }
iswxdigit()
int iswxdigit (wint_t nc)
Definition at line 136 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(nc, cp); e != mlibc::charcode_error::null)
         return 0;
     return mlibc::current_charset()->is_xdigit(cp);
 }
towctrans()
wint_t towctrans (wint_t wc, wctrans_t trans)
Definition at line 11 of file wctrans.c.
 {
     if (trans == (wctrans_t)1) return towupper(wc);
     if (trans == (wctrans_t)2) return towlower(wc);
     return wc;
 }
References towlower(), towupper(), and trans.
Referenced by towctrans_l().
towlower()
wint_t towlower (wint_t wc)
Definition at line 286 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(wc, cp); e != mlibc::charcode_error::null)
         return wc;
     return mlibc::current_charset()->to_lower(cp);
 }
towupper()
wint_t towupper (wint_t wc)
Definition at line 294 of file ctype-stubs.cpp.
{
     auto cc = mlibc::platform_wide_charcode();
     mlibc::codepoint cp;
     if(auto e = cc->promote(wc, cp); e != mlibc::charcode_error::null)
         return wc;
     return mlibc::current_charset()->to_upper(cp);
 }
wctrans()
wctrans_t wctrans (const char * class)
Definition at line 4 of file wctrans.c.
 {
     if (!strcmp(class, "toupper")) return (wctrans_t)1;
     if (!strcmp(class, "tolower")) return (wctrans_t)2;
     return 0;
 }
References strcmp.
wctype()
wctype_t wctype (const char * cs)
Definition at line 239 of file ctype-stubs.cpp.
{
     frg::string_view s{cs};
     if(s == "alnum") return ct_alnum;
     if(s == "alpha") return ct_alpha;
     if(s == "blank") return ct_blank;
     if(s == "cntrl") return ct_cntrl;
     if(s == "digit") return ct_digit;
     if(s == "graph") return ct_graph;
     if(s == "lower") return ct_lower;
     if(s == "print") return ct_print;
     if(s == "punct") return ct_punct;
     if(s == "space") return ct_space;
     if(s == "upper") return ct_upper;
     if(s == "xdigit") return ct_xdigit;
     mlibc::infoLogger() << "mlibc: wctype(\"" << cs << "\") is not supported" << frg::endlog;
     return ct_null;
 }