Fennix: Userspace/musl/src/errno/strerror.c File Reference
strerror.c File Reference
#include <errno.h>
#include <stddef.h>
#include <string.h>
#include "locale_impl.h"
#include "__strerror.h"
Data Structures
struct errmsgstr_t
Macros
#define E(n, s) char str##n[sizeof(s)];
#define E(n, s) s,
#define E(n, s) [n] = offsetof(struct errmsgstr_t, str##n),
Functions
char * __strerror_l (int e, locale_t loc)
char * strerror (int e)
weak_alias (__strerror_l, strerror_l)
Variables
static const struct errmsgstr_t errmsgstr
static const unsigned short errmsgidx []
Data Structure Documentation
errmsgstr_t
struct errmsgstr_t
Definition at line 14 of file strerror.c.
Macro Definition Documentation
E [1/3]
#define E (n, s) char str##n[sizeof(s)];
Definition at line 15 of file strerror.c.
E [2/3]
#define E (n, s) s,
Definition at line 15 of file strerror.c.
E [3/3]
#define E (n, s) [n] = offsetof(struct errmsgstr_t, str##n),
Definition at line 15 of file strerror.c.
Function Documentation
__strerror_l()
char* __strerror_l (int e, locale_t loc)
Definition at line 30 of file strerror.c.
 {
     const char *s;
 #ifdef EDQUOT_ORIG
     if (e==EDQUOT) e=0;
     else if (e==EDQUOT_ORIG) e=EDQUOT;
 #endif
     if (e >= sizeof errmsgidx / sizeof *errmsgidx) e = 0;
     s = (char *)&errmsgstr + errmsgidx[e];
     return (char *)LCTRANS(s, LC_MESSAGES, loc);
 }
References EDQUOT, errmsgidx, errmsgstr, LC_MESSAGES, LCTRANS, and s.
Referenced by strerror().
strerror()
char* strerror (int e)
Definition at line 42 of file strerror.c.
 {
     return __strerror_l(e, CURRENT_LOCALE);
 }
References __strerror_l(), CURRENT_LOCALE, E2BIG, EACCES, EADDRINUSE, EADDRNOTAVAIL, EADV, EAFNOSUPPORT, EAGAIN, EALREADY, EBADE, EBADF, EBADFD, EBADMSG, EBADR, EBADRQC, EBADSLT, EBFONT, EBUSY, ECANCELED, ECHILD, ECHRNG, ECOMM, ECONNABORTED, ECONNREFUSED, ECONNRESET, EDEADLK, EDESTADDRREQ, EDOM, EDOTDOT, EDQUOT, EEXIST, EFAULT, EFBIG, EHOSTDOWN, EHOSTUNREACH, EIDRM, EILSEQ, EINPROGRESS, EINTR, EINVAL, EIO, EISCONN, EISDIR, EISNAM, EKEYEXPIRED, EKEYREJECTED, EKEYREVOKED, EL2HLT, EL2NSYNC, EL3HLT, EL3RST, ELIBACC, ELIBBAD, ELIBEXEC, ELIBMAX, ELIBSCN, ELNRNG, ELOOP, EMEDIUMTYPE, EMFILE, EMLINK, EMSGSIZE, EMULTIHOP, ENAMETOOLONG, ENAVAIL, ENETDOWN, ENETRESET, ENETUNREACH, ENFILE, ENOANO, ENOBUFS, ENOCSI, ENODATA, ENODEV, ENOENT, ENOEXEC, ENOKEY, ENOLCK, ENOLINK, ENOMEDIUM, ENOMEM, ENOMSG, ENONET, ENOPKG, ENOPROTOOPT, ENOSPC, ENOSR, ENOSTR, ENOSYS, ENOTBLK, ENOTCONN, ENOTDIR, ENOTEMPTY, ENOTNAM, ENOTRECOVERABLE, ENOTSOCK, ENOTTY, ENOTUNIQ, ENXIO, EOPNOTSUPP, EOVERFLOW, EOWNERDEAD, EPERM, EPFNOSUPPORT, EPIPE, EPROTO, EPROTONOSUPPORT, EPROTOTYPE, ERANGE, EREMCHG, EREMOTE, EREMOTEIO, ERESTART, EROFS, ESHUTDOWN, ESOCKTNOSUPPORT, ESPIPE, ESRCH, ESRMNT, ESTALE, ESTRPIPE, ETIME, ETIMEDOUT, ETOOMANYREFS, ETXTBSY, EUCLEAN, EUNATCH, EUSERS, EXDEV, and EXFULL.
Referenced by __dls3(), _remove_directory(), accept_builtin(), async_redirect_stdin(), awk_main(), bb_perror_msg(), bb_perror_msg_and_die(), cmd_modinfo(), do_if_fetch(), dolink(), errmsg(), fdflags_builtin(), file_error(), file_head(), get_working_directory(), Execute::GetBinaryType(), getconf_print(), getflags(), getfloatmax(), getstat(), head_builtin(), ioctl_or_perror(), ioctl_or_perror_and_die(), Driver::Manager::LoadAllDrivers(), logname_builtin(), main(), make_path(), Driver::Manager::Manager(), mkdir_builtin(), mkfifo_builtin(), moderror(), perror(), printf_core(), printsome(), push_builtin(), pwdx_main(), realpath_builtin(), redirection_error(), rm_file(), rmdir_builtin(), set_locale_var(), setone(), setpgid_builtin(), sh_ttyerror(), sh_wrerror(), shell_execve(), StartKernelShell(), stat_builtin(), stdcat(), strerror_r(), sys_error(), uname_builtin(), unlink_builtin(), Driver::Manager::UnloadAllDrivers(), wait_for(), wprintf_core(), WriteDiagDataToNode(), and xmalloc_readlink_or_warn().
weak_alias()
weak_alias (__strerror_l , strerror_l)
Variable Documentation
errmsgidx
const unsigned short errmsgidx[] static
Initial value:
= {
#define E(n, s)
}
Definition at line 24 of file strerror.c.
Referenced by __strerror_l().
errmsgstr
const struct errmsgstr_t errmsgstr static
Initial value:
= {
#define E(n, s)
}
Referenced by __strerror_l().