Fennix Userspace: Userspace/apps/base/bash/sig.c File Reference
sig.c File Reference
#include "config.h"
#include "bashtypes.h"
#include <stdio.h>
#include <signal.h>
#include "bashintl.h"
#include "shell.h"
#include "execute_cmd.h"
#include "siglist.h"
#include "sig.h"
#include "trap.h"
#include "builtins/common.h"
#include "builtins/builtext.h"
Data Structures
struct termsig
Macros
#define NULL_HANDLER (SigHandler *)SIG_DFL
#define TERMSIGS_LENGTH (sizeof (terminating_signals) / sizeof (struct termsig))
#define XSIG(x) (terminating_signals[x].signum)
#define XHANDLER(x) (terminating_signals[x].orig_handler)
#define XSAFLAGS(x) (terminating_signals[x].orig_flags)
#define XCOREDUMP(x) (terminating_signals[x].core_dump)
Functions
void initialize_siglist PARAMS ((void))
void set_original_signal PARAMS ((int, SigHandler *))
static void kill_shell PARAMS ((int))
void initialize_signals (int reinit)
void initialize_terminating_signals ()
static void initialize_shell_signals ()
void reset_terminating_signals ()
void top_level_cleanup ()
void throw_to_top_level ()
void jump_to_top_level (int value)
void restore_sigmask ()
sighandler termsig_sighandler (int sig)
void termsig_handler (int sig)
static void kill_shell (int sig)
sighandler sigint_sighandler (int sig)
void set_sigwinch_handler ()
void unset_sigwinch_handler ()
sighandler sigterm_sighandler (int sig)
sigprocmask (int operation, int *newset, int *oldset)
Variables
volatile sig_atomic_t interrupt_state = 0
volatile sig_atomic_t sigwinch_received = 0
volatile sig_atomic_t sigterm_received = 0
volatile sig_atomic_t terminating_signal = 0
procenv_t top_level
int interrupt_immediately = 0
int terminate_immediately = 0
static struct termsig terminating_signals []
static int termsigs_initialized = 0
static int handling_termsig = 0
Data Structure Documentation
termsig
struct termsig
Definition at line 114 of file sig.c.
Data Fields
int core_dump
int orig_flags
SigHandler * orig_handler
int signum
Macro Definition Documentation
NULL_HANDLER
#define NULL_HANDLER (SigHandler *)SIG_DFL
Definition at line 121 of file sig.c.
TERMSIGS_LENGTH
#define TERMSIGS_LENGTH (sizeof (terminating_signals) / sizeof (struct termsig))
Definition at line 216 of file sig.c.
XCOREDUMP
#define XCOREDUMP (x) (terminating_signals[x].core_dump)
Definition at line 221 of file sig.c.
XHANDLER
#define XHANDLER (x) (terminating_signals[x].orig_handler)
Definition at line 219 of file sig.c.
XSAFLAGS
#define XSAFLAGS (x) (terminating_signals[x].orig_flags)
Definition at line 220 of file sig.c.
XSIG
#define XSIG (x) (terminating_signals[x].signum)
Definition at line 218 of file sig.c.
Function Documentation
initialize_shell_signals()
static void initialize_shell_signals () static
Definition at line 310 of file sig.c.
 {
   if (interactive)
     initialize_terminating_signals ();
 #if defined (JOB_CONTROL) || defined (HAVE_POSIX_SIGNALS)
   /* All shells use the signal mask they inherit, and pass it along
      to child processes.  Children will never block SIGCHLD, though. */
   sigemptyset (&top_level_mask);
   sigprocmask (SIG_BLOCK, (sigset_t *)NULL, &top_level_mask);
 #  if defined (SIGCHLD)
   if (sigismember (&top_level_mask, SIGCHLD))
     {
       sigdelset (&top_level_mask, SIGCHLD);
       sigprocmask (SIG_SETMASK, &top_level_mask, (sigset_t *)NULL);
     }
 #  endif
 #endif /* JOB_CONTROL || HAVE_POSIX_SIGNALS */
   /* And, some signals that are specifically ignored by the shell. */
   set_signal_handler (SIGQUIT, SIG_IGN);
   if (interactive)
     {
       set_signal_handler (SIGINT, sigint_sighandler);
       get_original_signal (SIGTERM);
       set_signal_handler (SIGTERM, SIG_IGN);
       set_sigwinch_handler ();
     }
 }
References get_original_signal(), initialize_terminating_signals(), interactive, NULL, set_signal_handler, set_sigwinch_handler(), SIG_BLOCK, SIG_IGN, SIG_SETMASK, SIGCHLD, sigdelset, sigemptyset, SIGINT, sigint_sighandler(), sigismember, sigprocmask(), SIGQUIT, and SIGTERM.
Referenced by initialize_signals().
initialize_signals()
void initialize_signals (int reinit)
Definition at line 100 of file sig.c.
 {
   initialize_shell_signals ();
   initialize_job_signals ();
 #if !defined (HAVE_SYS_SIGLIST) && !defined (HAVE_UNDER_SYS_SIGLIST) && !defined (HAVE_STRSIGNAL)
   if (reinit == 0)
     initialize_siglist ();
 #endif /* !HAVE_SYS_SIGLIST && !HAVE_UNDER_SYS_SIGLIST && !HAVE_STRSIGNAL */
 }
References initialize_job_signals(), initialize_shell_signals(), and initialize_siglist().
Referenced by shell_initialize().
initialize_terminating_signals()
void initialize_terminating_signals ()
Definition at line 230 of file sig.c.
 {
   register int i;
 #if defined (HAVE_POSIX_SIGNALS)
   struct sigaction act, oact;
 #endif
   if (termsigs_initialized)
     return;
   /* The following code is to avoid an expensive call to
      set_signal_handler () for each terminating_signals.  Fortunately,
      this is possible in Posix.  Unfortunately, we have to call signal ()
      on non-Posix systems for each signal in terminating_signals. */
 #if defined (HAVE_POSIX_SIGNALS)
   act.sa_handler = termsig_sighandler;
   act.sa_flags = 0;
   sigemptyset (&act.sa_mask);
   sigemptyset (&oact.sa_mask);
   for (i = 0; i < TERMSIGS_LENGTH; i++)
     sigaddset (&act.sa_mask, XSIG (i));
   for (i = 0; i < TERMSIGS_LENGTH; i++)
     {
       /* If we've already trapped it, don't do anything. */
       if (signal_is_trapped (XSIG (i)))
     continue;
       sigaction (XSIG (i), &act, &oact);
       XHANDLER(i) = oact.sa_handler;
       XSAFLAGS(i) = oact.sa_flags;
 #if 0
       set_original_signal (XSIG(i), XHANDLER(i));   /* optimization */
 #else
       set_original_signal (XSIG(i), act.sa_handler);    /* optimization */
 #endif
       /* Don't do anything with signals that are ignored at shell entry
      if the shell is not interactive. */
       /* XXX - should we do this for interactive shells, too? */
       if (interactive_shell == 0 && XHANDLER (i) == SIG_IGN)
     {
       sigaction (XSIG (i), &oact, &act);
       set_signal_hard_ignored (XSIG (i));
     }
 #if defined (SIGPROF) && !defined (_MINIX)
       if (XSIG (i) == SIGPROF && XHANDLER (i) != SIG_DFL && XHANDLER (i) != SIG_IGN)
     sigaction (XSIG (i), &oact, (struct sigaction *)NULL);
 #endif /* SIGPROF && !_MINIX */
     }
 #else /* !HAVE_POSIX_SIGNALS */
   for (i = 0; i < TERMSIGS_LENGTH; i++)
     {
       /* If we've already trapped it, don't do anything. */
       if (signal_is_trapped (XSIG (i)))
     continue;
       XHANDLER(i) = signal (XSIG (i), termsig_sighandler);
       XSAFLAGS(i) = 0;
       /* Don't do anything with signals that are ignored at shell entry
      if the shell is not interactive. */
       /* XXX - should we do this for interactive shells, too? */
       if (interactive_shell == 0 && XHANDLER (i) == SIG_IGN)
     {
       signal (XSIG (i), SIG_IGN);
       set_signal_hard_ignored (XSIG (i));
     }
 #ifdef SIGPROF
       if (XSIG (i) == SIGPROF && XHANDLER (i) != SIG_DFL && XHANDLER (i) != SIG_IGN)
     signal (XSIG (i), XHANDLER (i));
 #endif
     }
 #endif /* !HAVE_POSIX_SIGNALS */
   termsigs_initialized = 1;
 }
References i, interactive_shell, NULL, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, set_original_signal(), set_signal_hard_ignored(), SIG_DFL, SIG_IGN, sigaction(), sigaddset, sigemptyset, signal, signal_is_trapped(), SIGPROF, termsig_sighandler(), termsigs_initialized, TERMSIGS_LENGTH, XHANDLER, XSAFLAGS, and XSIG.
Referenced by initialize_shell_signals(), and set_signal().
jump_to_top_level()
void jump_to_top_level (int value)
Definition at line 476 of file sig.c.
 {
   sh_longjmp (top_level, value);
 }
References sh_longjmp, top_level, and value.
Referenced by _evalfile(), alrm_catcher(), command_substitute(), execute_builtin(), execute_command_internal(), execute_connection(), execute_for_command(), execute_function(), execute_intern_function(), execute_simple_command(), exp_jump_to_top_level(), expr_streval(), get_numeric_arg(), make_variable_value(), no_args(), parse_and_execute(), parse_compound_assignment(), parse_comsub(), parse_string(), parse_string_to_command(), parse_string_to_word_list(), run_pending_traps(), throw_to_top_level(), and xparse_dolparen().
kill_shell()
static void kill_shell (int sig) static
Definition at line 628 of file sig.c.
 {
   int i, core;
   sigset_t mask;
   /* We don't change the set of blocked signals. If a user starts the shell
      with a terminating signal blocked, we won't get here (and if by some
      magic chance we do, we'll exit below). What we do is to restore the
      top-level signal mask, in case this is called from a terminating signal
      handler context, in which case the signal is blocked. */
   restore_sigmask ();
   set_signal_handler (sig, SIG_DFL);
   kill (getpid (), sig);
   if (dollar_dollar_pid != 1)
     exit (128+sig);     /* just in case the kill fails? */
   /* We get here only under extraordinary circumstances. */
   /* We are PID 1, and the kill above failed to kill the process. We assume
      this means that we are running as an init process in a pid namespace
      on Linux. In this case, we can't send ourselves a fatal signal, so we
      determine whether or not we should have generated a core dump with the
      kill call and attempt to trick the kernel into generating one if
      necessary. */
   sigprocmask (SIG_SETMASK, (sigset_t *)NULL, &mask);
   for (i = core = 0; i < TERMSIGS_LENGTH; i++)
     {
       set_signal_handler (XSIG (i), SIG_DFL);
       sigdelset (&mask, XSIG (i));
       if (sig == XSIG (i))
     core = XCOREDUMP (i);
     }
   sigprocmask (SIG_SETMASK, &mask, (sigset_t *)NULL);
   if (core)
     *((volatile unsigned long *) NULL) = 0xdead0000 + sig;  /* SIGSEGV */
   exit (128+sig);
 }
References dollar_dollar_pid, exit(), getpid(), i, kill(), NULL, restore_sigmask(), set_signal_handler, SIG_DFL, SIG_SETMASK, sigdelset, sigprocmask(), TERMSIGS_LENGTH, XCOREDUMP, and XSIG.
Referenced by termsig_handler(), and termsig_sighandler().
PARAMS() [1/3]
static void kill_shell PARAMS ((int)) static
PARAMS() [2/3]
void set_original_signal PARAMS ((int, SigHandler *))
PARAMS() [3/3]
void initialize_siglist PARAMS ((void))
reset_terminating_signals()
void reset_terminating_signals ()
Definition at line 342 of file sig.c.
 {
   register int i;
 #if defined (HAVE_POSIX_SIGNALS)
   struct sigaction act;
 #endif
   if (termsigs_initialized == 0)
     return;
 #if defined (HAVE_POSIX_SIGNALS)
   act.sa_flags = 0;
   sigemptyset (&act.sa_mask);
   for (i = 0; i < TERMSIGS_LENGTH; i++)
     {
       /* Skip a signal if it's trapped or handled specially, because the
      trap code will restore the correct value. */
       if (signal_is_trapped (XSIG (i)) || signal_is_special (XSIG (i)))
     continue;
       act.sa_handler = XHANDLER (i);
       act.sa_flags = XSAFLAGS (i);
       sigaction (XSIG (i), &act, (struct sigaction *) NULL);
     }
 #else /* !HAVE_POSIX_SIGNALS */
   for (i = 0; i < TERMSIGS_LENGTH; i++)
     {
       if (signal_is_trapped (XSIG (i)) || signal_is_special (XSIG (i)))
     continue;
       signal (XSIG (i), XHANDLER (i));
     }
 #endif /* !HAVE_POSIX_SIGNALS */
   termsigs_initialized = 0;
 }
References i, NULL, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), sigemptyset, signal, signal_is_special(), signal_is_trapped(), termsigs_initialized, TERMSIGS_LENGTH, XHANDLER, XSAFLAGS, and XSIG.
Referenced by execute_disk_command(), and execute_in_subshell().
restore_sigmask()
void restore_sigmask ()
Definition at line 483 of file sig.c.
 {
 #if defined (JOB_CONTROL) || defined (HAVE_POSIX_SIGNALS)
   sigprocmask (SIG_SETMASK, &top_level_mask, (sigset_t *)NULL);
 #endif
 }
References NULL, SIG_SETMASK, and sigprocmask().
Referenced by kill_shell(), make_child(), reader_loop(), and throw_to_top_level().
set_sigwinch_handler()
void set_sigwinch_handler ()
Definition at line 735 of file sig.c.
 {
 #if defined (SIGWINCH)
  old_winch = set_signal_handler (SIGWINCH, sigwinch_sighandler);
 #endif
 }
References set_signal_handler, and SIGWINCH.
Referenced by initialize_shell_signals().
sigint_sighandler()
sighandler sigint_sighandler (int sig)
Definition at line 675 of file sig.c.
 {
 #if defined (MUST_REINSTALL_SIGHANDLERS)
   signal (sig, sigint_sighandler);
 #endif
   /* interrupt_state needs to be set for the stack of interrupts to work
      right.  Should it be set unconditionally? */
   if (interrupt_state == 0)
     ADDINTERRUPT;
   /* We will get here in interactive shells with job control active; allow
      an interactive wait to be interrupted.  wait_intr_flag is only set during
      the execution of the wait builtin and when wait_intr_buf is valid. */
   if (wait_intr_flag)
     {
       last_command_exit_value = 128 + sig;
       set_pipestatus_from_exit (last_command_exit_value);
       wait_signal_received = sig;
       SIGRETURN (0);
     }
   /* In interactive shells, we will get here instead of trap_handler() so
      note that we have a trap pending. */
   if (signal_is_trapped (sig))
     set_trap_state (sig);
   /* This is no longer used, but this code block remains as a reminder. */
   if (interrupt_immediately)
     {
       interrupt_immediately = 0;
       set_exit_status (128 + sig);
       throw_to_top_level ();
     }
 #if defined (READLINE)
   /* Set the event hook so readline will call it after the signal handlers
      finish executing, so if this interrupted character input we can get
      quick response. */
   else if (RL_ISSTATE (RL_STATE_SIGHANDLER))
     bashline_set_event_hook ();
 #endif
   SIGRETURN (0);
 }
References ADDINTERRUPT, interrupt_immediately, interrupt_state, last_command_exit_value, RL_ISSTATE, RL_STATE_SIGHANDLER, set_exit_status(), set_pipestatus_from_exit(), set_trap_state(), signal, signal_is_trapped(), SIGRETURN, throw_to_top_level(), wait_intr_flag, and wait_signal_received.
Referenced by initialize_job_signals(), initialize_shell_signals(), reader_loop(), and set_sigint_handler().
sigprocmask()
sigprocmask (int operation, int * newset, int * oldset)
Definition at line 762 of file sig.c.
 {
   int old, new;
   if (newset)
     new = *newset;
   else
     new = 0;
   switch (operation)
     {
     case SIG_BLOCK:
       old = sigblock (new);
       break;
     case SIG_SETMASK:
       old = sigsetmask (new);
       break;
     default:
       internal_error (_("sigprocmask: %d: invalid operation"), operation);
     }
   if (oldset)
     *oldset = old;
 }
References _, internal_error(), SIG_BLOCK, and SIG_SETMASK.
Referenced by _rl_block_sigwinch(), _rl_handle_signal(), _rl_release_sigwinch(), give_terminal_to(), initialize_shell_signals(), kill_shell(), make_child(), nchars_avail(), notify_of_job_status(), parse_and_execute(), parse_string(), pthread_setcancelstate(), restore_sigmask(), rl_getc(), rl_set_signals(), sighold(), sigpause(), sigrelse(), sigstat(), system(), trap_handler(), and we_askshell().
sigterm_sighandler()
sighandler sigterm_sighandler (int sig)
Definition at line 751 of file sig.c.
 {
   sigterm_received = 1;     /* XXX - counter? */
   SIGRETURN (0);
 }
References SIGRETURN, and sigterm_received.
termsig_handler()
void termsig_handler (int sig)
Definition at line 575 of file sig.c.
 {
   /* Simple semaphore to keep this function from being executed multiple
      times.  Since we no longer are running as a signal handler, we don't
      block multiple occurrences of the terminating signals while running. */
   if (handling_termsig)
     return;
   handling_termsig = terminating_signal;    /* for termsig_sighandler */
   terminating_signal = 0;   /* keep macro from re-testing true. */
   /* I don't believe this condition ever tests true. */
   if (sig == SIGINT && signal_is_trapped (SIGINT))
     run_interrupt_trap (0);
 #if defined (HISTORY)
   /* If we don't do something like this, the history will not be saved when
      an interactive shell is running in a terminal window that gets closed
      with the `close' button.  We can't test for RL_STATE_READCMD because
      readline no longer handles SIGTERM synchronously.  */
   if (interactive_shell && interactive && (sig == SIGHUP || sig == SIGTERM) && remember_on_history)
     maybe_save_shell_history ();
 #endif /* HISTORY */
   if (this_shell_builtin == read_builtin)
     read_tty_cleanup ();
 #if defined (JOB_CONTROL)
   if (sig == SIGHUP && (interactive || (subshell_environment & (SUBSHELL_COMSUB|SUBSHELL_PROCSUB))))
     hangup_all_jobs ();
   if ((subshell_environment & (SUBSHELL_COMSUB|SUBSHELL_PROCSUB)) == 0)
     end_job_control ();
 #endif /* JOB_CONTROL */
 #if defined (PROCESS_SUBSTITUTION)
   unlink_all_fifos ();
 #  if defined (JOB_CONTROL)
   procsub_clear ();
 #  endif
 #endif /* PROCESS_SUBSTITUTION */
   /* Reset execution context */
   loop_level = continuing = breaking = funcnest = 0;
   executing_list = comsub_ignore_return = return_catch_flag = wait_intr_flag = 0;
   run_exit_trap (); /* XXX - run exit trap possibly in signal context? */
   kill_shell (sig);
 }
References breaking, comsub_ignore_return, continuing, end_job_control(), executing_list, funcnest, handling_termsig, hangup_all_jobs(), interactive, interactive_shell, kill_shell(), loop_level, remember_on_history, return_catch_flag, run_exit_trap(), run_interrupt_trap(), SIGHUP, SIGINT, signal_is_trapped(), SIGTERM, SUBSHELL_COMSUB, subshell_environment, SUBSHELL_PROCSUB, terminating_signal, this_shell_builtin, and wait_intr_flag.
Referenced by set_job_status_and_cleanup(), termsig_sighandler(), and wait_for().
termsig_sighandler()
sighandler termsig_sighandler (int sig)
Definition at line 493 of file sig.c.
 {
   /* If we get called twice with the same signal before handling it,
      terminate right away. */
   if (
 #ifdef SIGHUP
     sig != SIGHUP &&
 #endif
 #ifdef SIGINT
     sig != SIGINT &&
 #endif
 #ifdef SIGDANGER
     sig != SIGDANGER &&
 #endif
 #ifdef SIGPIPE
     sig != SIGPIPE &&
 #endif
 #ifdef SIGALRM
     sig != SIGALRM &&
 #endif
 #ifdef SIGTERM
     sig != SIGTERM &&
 #endif
 #ifdef SIGXCPU
     sig != SIGXCPU &&
 #endif
 #ifdef SIGXFSZ
     sig != SIGXFSZ &&
 #endif
 #ifdef SIGVTALRM
     sig != SIGVTALRM &&
 #endif
 #ifdef SIGLOST
     sig != SIGLOST &&
 #endif
 #ifdef SIGUSR1
     sig != SIGUSR1 &&
 #endif
 #ifdef SIGUSR2
    sig != SIGUSR2 &&
 #endif
    sig == terminating_signal)
     terminate_immediately = 1;
   /* If we are currently handling a terminating signal, we have a couple of
      choices here. We can ignore this second terminating signal and let the
      shell exit from the first one, or we can exit immediately by killing
      the shell with this signal. This code implements the latter; to implement
      the former, replace the kill_shell(sig) with return. */
   if (handling_termsig)
     kill_shell (sig);       /* just short-circuit now */
   terminating_signal = sig;
   if (terminate_immediately)
     {
 #if defined (HISTORY)
       /* XXX - will inhibit history file being written */
 #  if defined (READLINE)
       if (interactive_shell == 0 || interactive == 0 || (sig != SIGHUP && sig != SIGTERM) || no_line_editing || (RL_ISSTATE (RL_STATE_READCMD) == 0))
 #  endif
         history_lines_this_session = 0;
 #endif
       terminate_immediately = 0;
       termsig_handler (sig);
     }
 #if defined (READLINE)
   /* Set the event hook so readline will call it after the signal handlers
      finish executing, so if this interrupted character input we can get
      quick response.  If readline is active or has modified the terminal we
      need to set this no matter what the signal is, though the check for
      RL_STATE_TERMPREPPED is possibly redundant. */
   if (RL_ISSTATE (RL_STATE_SIGHANDLER) || RL_ISSTATE (RL_STATE_TERMPREPPED))
     bashline_set_event_hook ();
 #endif
   SIGRETURN (0);
 }
References handling_termsig, history_lines_this_session, interactive, interactive_shell, kill_shell(), no_line_editing, RL_ISSTATE, RL_STATE_READCMD, RL_STATE_SIGHANDLER, RL_STATE_TERMPREPPED, SIGALRM, SIGHUP, SIGINT, SIGPIPE, SIGRETURN, SIGTERM, SIGUSR1, SIGUSR2, SIGVTALRM, SIGXCPU, SIGXFSZ, terminate_immediately, terminating_signal, and termsig_handler().
Referenced by initialize_terminating_signals(), and set_sigint_handler().
throw_to_top_level()
void throw_to_top_level ()
Definition at line 401 of file sig.c.
 {
   int print_newline = 0;
   if (interrupt_state)
     {
       if (last_command_exit_value < 128)
     last_command_exit_value = 128 + SIGINT;
       set_pipestatus_from_exit (last_command_exit_value);
       print_newline = 1;
       DELINTERRUPT;
     }
   if (interrupt_state)
     return;
   last_command_exit_signal = (last_command_exit_value > 128) ?
                 (last_command_exit_value - 128) : 0;
   last_command_exit_value |= 128;
   set_pipestatus_from_exit (last_command_exit_value);
   /* Run any traps set on SIGINT, mostly for interactive shells */
   if (signal_is_trapped (SIGINT) && signal_is_pending (SIGINT))
     run_interrupt_trap (1);
   /* Clean up string parser environment. */
   while (parse_and_execute_level)
     parse_and_execute_cleanup (-1);
   if (running_trap > 0)
     {
       run_trap_cleanup (running_trap - 1);
       running_trap = 0;
     }
 #if defined (JOB_CONTROL)
   give_terminal_to (shell_pgrp, 0);
 #endif /* JOB_CONTROL */
   /* This needs to stay because jobs.c:make_child() uses it without resetting
      the signal mask. */
   restore_sigmask ();
   reset_parser ();
 #if defined (READLINE)
   if (interactive)
     bashline_reset ();
 #endif /* READLINE */
 #if defined (PROCESS_SUBSTITUTION)
   unlink_fifo_list ();
 #endif /* PROCESS_SUBSTITUTION */
   run_unwind_protects ();
   loop_level = continuing = breaking = funcnest = 0;
   executing_list = comsub_ignore_return = return_catch_flag = wait_intr_flag = 0;
   if (interactive && print_newline)
     {
       fflush (stdout);
       fprintf (stderr, "\n");
       fflush (stderr);
     }
   /* An interrupted `wait' command in a script does not exit the script. */
   if (interactive || (interactive_shell && !shell_initialized) ||
       (print_newline && signal_is_trapped (SIGINT)))
     jump_to_top_level (DISCARD);
   else
     jump_to_top_level (EXITPROG);
 }
References breaking, comsub_ignore_return, continuing, DELINTERRUPT, DISCARD, executing_list, EXITPROG, fflush(), fprintf(), funcnest, give_terminal_to(), interactive, interactive_shell, interrupt_state, jump_to_top_level(), last_command_exit_signal, last_command_exit_value, loop_level, parse_and_execute_cleanup(), parse_and_execute_level, reset_parser(), restore_sigmask(), return_catch_flag, run_interrupt_trap(), run_trap_cleanup(), run_unwind_protects(), running_trap, set_pipestatus_from_exit(), shell_initialized, shell_pgrp, SIGINT, signal_is_pending(), signal_is_trapped(), stderr, stdout, and wait_intr_flag.
Referenced by execute_pipeline(), get_numeric_arg(), make_child(), parse_and_execute(), and sigint_sighandler().
top_level_cleanup()
void top_level_cleanup ()
Definition at line 384 of file sig.c.
 {
   /* Clean up string parser environment. */
   while (parse_and_execute_level)
     parse_and_execute_cleanup (-1);
 #if defined (PROCESS_SUBSTITUTION)
   unlink_fifo_list ();
 #endif /* PROCESS_SUBSTITUTION */
   run_unwind_protects ();
   loop_level = continuing = breaking = funcnest = 0;
   executing_list = comsub_ignore_return = return_catch_flag = wait_intr_flag = 0;
 }
References breaking, comsub_ignore_return, continuing, executing_list, funcnest, loop_level, parse_and_execute_cleanup(), parse_and_execute_level, return_catch_flag, run_unwind_protects(), and wait_intr_flag.
Referenced by exp_jump_to_top_level(), expr_streval(), get_numeric_arg(), make_variable_value(), no_args(), and parse_string().
unset_sigwinch_handler()
void unset_sigwinch_handler ()
Definition at line 743 of file sig.c.
 {
 #if defined (SIGWINCH)
   set_signal_handler (SIGWINCH, old_winch);
 #endif
 }
References set_signal_handler, and SIGWINCH.
Variable Documentation
handling_termsig
int handling_termsig = 0 static
Definition at line 490 of file sig.c.
Referenced by termsig_handler(), and termsig_sighandler().
interrupt_immediately
int interrupt_immediately = 0
Definition at line 87 of file sig.c.
Referenced by sigint_sighandler(), and tee_builtin().
interrupt_state
volatile sig_atomic_t interrupt_state = 0
Definition at line 66 of file sig.c.
Referenced by _run_trap_internal(), getc_with_restart(), glob_vector(), make_child(), parse_and_execute(), parse_string(), sigint_sighandler(), and throw_to_top_level().
sigterm_received
volatile sig_atomic_t sigterm_received = 0
Definition at line 72 of file sig.c.
Referenced by sigterm_sighandler().
sigwinch_received
volatile sig_atomic_t sigwinch_received = 0
Definition at line 69 of file sig.c.
terminate_immediately
int terminate_immediately = 0
Definition at line 90 of file sig.c.
Referenced by termsig_sighandler().
terminating_signal
volatile sig_atomic_t terminating_signal = 0
Definition at line 75 of file sig.c.
Referenced by termsig_handler(), and termsig_sighandler().
terminating_signals
struct termsig terminating_signals[] static
Definition at line 100 of file sig.c.
termsigs_initialized
int termsigs_initialized = 0 static
Definition at line 223 of file sig.c.
Referenced by initialize_terminating_signals(), and reset_terminating_signals().
top_level
procenv_t top_level
Definition at line 79 of file sig.c.
Referenced by command_substitute(), execute_in_subshell(), execute_subshell_builtin_or_function(), jump_to_top_level(), main(), parse_and_execute(), parse_prologue(), parse_string(), pretty_print_loop(), reader_loop(), and run_exit_trap().