Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/w_file_stdc.c File Reference
w_file_stdc.c File Reference
#include <stdio.h>
#include "m_misc.h"
#include "w_file.h"
#include "z_zone.h"
Data Structures
struct stdc_wad_file_t
Functions
static wad_file_t * W_StdC_OpenFile (char *path)
static void W_StdC_CloseFile (wad_file_t *wad)
size_t W_StdC_Read (wad_file_t *wad, unsigned int offset, void *buffer, size_t buffer_len)
Variables
wad_file_class_t stdc_wad_file
Data Structure Documentation
stdc_wad_file_t
struct stdc_wad_file_t
Definition at line 25 of file w_file_stdc.c.
Data Fields
FILE * fstream
wad_file_t wad
Function Documentation
W_StdC_CloseFile()
static void W_StdC_CloseFile (wad_file_t * wad) static
Definition at line 56 of file w_file_stdc.c.
 {
     stdc_wad_file_t *stdc_wad;
     stdc_wad = (stdc_wad_file_t *) wad;
     fclose(stdc_wad->fstream);
     Z_Free(stdc_wad);
 }
References fclose(), stdc_wad_file_t::fstream, and Z_Free().
W_StdC_OpenFile()
static wad_file_t* W_StdC_OpenFile (char * path) static
Definition at line 33 of file w_file_stdc.c.
 {
     stdc_wad_file_t *result;
     FILE *fstream;
     fstream = fopen(path, "rb");
     if (fstream == NULL)
     {
         return NULL;
     }
     // Create a new stdc_wad_file_t to hold the file handle.
     result = Z_Malloc(sizeof(stdc_wad_file_t), PU_STATIC, 0);
     result->wad.file_class = &stdc_wad_file;
     result->wad.mapped = NULL;
     result->wad.length = M_FileLength(fstream);
     result->fstream = fstream;
     return &result->wad;
 }
References fopen(), M_FileLength(), NULL, PU_STATIC, mlibc::result, stdc_wad_file, and Z_Malloc().
W_StdC_Read()
size_t W_StdC_Read (wad_file_t * wad, unsigned int offset, void * buffer, size_t buffer_len)
Definition at line 69 of file w_file_stdc.c.
 {
     stdc_wad_file_t *stdc_wad;
     size_t result;
     stdc_wad = (stdc_wad_file_t *) wad;
     // Jump to the specified position in the file.
     fseek(stdc_wad->fstream, offset, SEEK_SET);
     // Read into the buffer.
     result = fread(buffer, 1, buffer_len, stdc_wad->fstream);
     return result;
 }
References fread(), fseek(), stdc_wad_file_t::fstream, offset, mlibc::result, and SEEK_SET.
Variable Documentation
stdc_wad_file
wad_file_class_t stdc_wad_file
Initial value:
=
{
    W_StdC_OpenFile,
    W_StdC_CloseFile,
    W_StdC_Read,
}
Definition at line 89 of file w_file_stdc.c.
Referenced by W_OpenFile(), and W_StdC_OpenFile().