Fennix: Userspace/apps/base/busybox/util-linux/scriptreplay.c File Reference
scriptreplay.c File Reference
#include "libbb.h"
Functions
int scriptreplay_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
scriptreplay_main()
int scriptreplay_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 28 of file scriptreplay.c.
 {
     const char *script = "typescript";
     double delay, factor = 1000000.0;
     int fd;
     unsigned long count;
     FILE *tfp;
     if (!argv[1])
         bb_show_usage();
     if (argv[2]) {
         script = argv[2];
         if (argv[3])
             factor /= atof(argv[3]);
     }
     tfp = xfopen_for_read(argv[1]);
     fd = xopen(script, O_RDONLY);
     while (fscanf(tfp, "%lf %lu\n", &delay, &count) == 2) {
         usleep(delay * factor);
         bb_copyfd_exact_size(fd, STDOUT_FILENO, count);
     }
     if (ENABLE_FEATURE_CLEAN_UP) {
         close(fd);
         fclose(tfp);
     }
     return EXIT_SUCCESS;
 }
References argv, atof(), bb_copyfd_exact_size(), bb_show_usage(), close(), count, EXIT_SUCCESS, fclose(), fd, fscanf(), O_RDONLY, STDOUT_FILENO, usleep(), xfopen_for_read(), and xopen().