Fennix Userspace: Userspace/mlibc/options/posix/include/termios.h File Reference
termios.h File Reference
#include <abi-bits/pid_t.h>
#include <abi-bits/termios.h>
Data Structures
struct winsize
Macros
#define B0 0
#define B50 1
#define B75 2
#define B110 3
#define B134 4
#define B150 5
#define B200 6
#define B300 7
#define B600 8
#define B1200 9
#define B1800 10
#define B2400 11
#define B4800 12
#define B9600 13
#define B19200 14
#define B38400 15
#define B57600 16
#define B115200 17
#define B230400 18
#define TCSANOW 1
#define TCSADRAIN 2
#define TCSAFLUSH 3
#define TCIFLUSH 1
#define TCIOFLUSH 2
#define TCOFLUSH 3
#define TCIOFF 1
#define TCION 2
#define TCOOFF 3
#define TCOON 4
#define TIOCM_DTR 0x002
#define TIOCM_RTS 0x004
#define TIOCGPGRP 0x540F
#define TIOCSPGRP 0x5410
#define TIOCGWINSZ 0x5413
#define TIOCSWINSZ 0x5414
#define TIOCGSID 0x5429
#define ECHOCTL 0001000
#define FLUSHO 0010000
#define IMAXBEL 0020000
#define ECHOKE 0040000
#define IUCLC 0001000
#define IUTF8 0040000
Functions
speed_t cfgetispeed (const struct termios *)
speed_t cfgetospeed (const struct termios *)
int cfsetispeed (struct termios *, speed_t)
int cfsetospeed (struct termios *, speed_t)
void cfmakeraw (struct termios *)
int tcdrain (int)
int tcflow (int, int)
int tcflush (int, int)
int tcgetattr (int fd, struct termios *attr)
pid_t tcgetsid (int)
int tcsendbreak (int, int)
int tcsetattr (int, int, const struct termios *)
Data Structure Documentation
winsize
struct winsize
Definition at line 77 of file termios.h.
Data Fields
unsigned short ws_col
unsigned short ws_row
unsigned short ws_xpixel
unsigned short ws_ypixel
Macro Definition Documentation
B0
#define B0 0
Definition at line 13 of file termios.h.
B110
#define B110 3
Definition at line 16 of file termios.h.
B115200
#define B115200 17
Definition at line 30 of file termios.h.
B1200
#define B1200 9
Definition at line 22 of file termios.h.
B134
#define B134 4
Definition at line 17 of file termios.h.
B150
#define B150 5
Definition at line 18 of file termios.h.
B1800
#define B1800 10
Definition at line 23 of file termios.h.
B19200
#define B19200 14
Definition at line 27 of file termios.h.
B200
#define B200 6
Definition at line 19 of file termios.h.
B230400
#define B230400 18
Definition at line 31 of file termios.h.
B2400
#define B2400 11
Definition at line 24 of file termios.h.
B300
#define B300 7
Definition at line 20 of file termios.h.
B38400
#define B38400 15
Definition at line 28 of file termios.h.
B4800
#define B4800 12
Definition at line 25 of file termios.h.
B50
#define B50 1
Definition at line 14 of file termios.h.
B57600
#define B57600 16
Definition at line 29 of file termios.h.
B600
#define B600 8
Definition at line 21 of file termios.h.
B75
#define B75 2
Definition at line 15 of file termios.h.
B9600
#define B9600 13
Definition at line 26 of file termios.h.
ECHOCTL
#define ECHOCTL 0001000
Definition at line 84 of file termios.h.
ECHOKE
#define ECHOKE 0040000
Definition at line 87 of file termios.h.
FLUSHO
#define FLUSHO 0010000
Definition at line 85 of file termios.h.
IMAXBEL
#define IMAXBEL 0020000
Definition at line 86 of file termios.h.
IUCLC
#define IUCLC 0001000
Definition at line 89 of file termios.h.
IUTF8
#define IUTF8 0040000
Definition at line 90 of file termios.h.
TCIFLUSH
#define TCIFLUSH 1
Definition at line 39 of file termios.h.
TCIOFF
#define TCIOFF 1
Definition at line 44 of file termios.h.
TCIOFLUSH
#define TCIOFLUSH 2
Definition at line 40 of file termios.h.
TCION
#define TCION 2
Definition at line 45 of file termios.h.
TCOFLUSH
#define TCOFLUSH 3
Definition at line 41 of file termios.h.
TCOOFF
#define TCOOFF 3
Definition at line 46 of file termios.h.
TCOON
#define TCOON 4
Definition at line 47 of file termios.h.
TCSADRAIN
#define TCSADRAIN 2
Definition at line 35 of file termios.h.
TCSAFLUSH
#define TCSAFLUSH 3
Definition at line 36 of file termios.h.
TCSANOW
#define TCSANOW 1
Definition at line 34 of file termios.h.
TIOCGPGRP
#define TIOCGPGRP 0x540F
Definition at line 71 of file termios.h.
TIOCGSID
#define TIOCGSID 0x5429
Definition at line 75 of file termios.h.
TIOCGWINSZ
#define TIOCGWINSZ 0x5413
Definition at line 73 of file termios.h.
TIOCM_DTR
#define TIOCM_DTR 0x002
Definition at line 49 of file termios.h.
TIOCM_RTS
#define TIOCM_RTS 0x004
Definition at line 50 of file termios.h.
TIOCSPGRP
#define TIOCSPGRP 0x5410
Definition at line 72 of file termios.h.
TIOCSWINSZ
#define TIOCSWINSZ 0x5414
Definition at line 74 of file termios.h.
Function Documentation
cfgetispeed()
speed_t cfgetispeed (const struct termios * tios)
Definition at line 9 of file termios-stubs.cpp.
{
     return tios->ibaud;
 }
References termios::ibaud.
cfgetospeed()
speed_t cfgetospeed (const struct termios * tios)
Definition at line 12 of file termios-stubs.cpp.
{
     return tios->obaud;
 }
References termios::obaud.
cfmakeraw()
void cfmakeraw (struct termios * t)
Definition at line 24 of file termios-stubs.cpp.
{
     t->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | ISTRIP | INLCR | IGNCR | ICRNL | IXON);
     t->c_oflag &= ~OPOST;
     t->c_lflag &= ~(ECHO | ECHONL | ICANON | ISIG | IEXTEN);
     t->c_cflag &= ~(CSIZE | PARENB);
     t->c_cflag |= CS8;
     t->c_cc[VMIN] = 1;
     t->c_cc[VTIME] = 0;
 }
References BRKINT, termios::c_cc, termios::c_cflag, termios::c_iflag, termios::c_lflag, termios::c_oflag, CS8, CSIZE, ECHO, ECHONL, ICANON, ICRNL, IEXTEN, IGNBRK, IGNCR, INLCR, ISIG, ISTRIP, IXON, OPOST, PARENB, PARMRK, VMIN, and VTIME.
cfsetispeed()
int cfsetispeed (struct termios * , speed_t)
Definition at line 15 of file termios-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
cfsetospeed()
int cfsetospeed (struct termios * , speed_t)
Definition at line 19 of file termios-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
tcdrain()
int tcdrain (int fd)
Definition at line 34 of file termios-stubs.cpp.
                     {
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcdrain, -1);
     if(int e = mlibc::sys_tcdrain(fd); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcdrain().
Referenced by getpass().
tcflow()
int tcflow (int fd, int action)
Definition at line 43 of file termios-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcflow, -1);
     if(int e = mlibc::sys_tcflow(fd, action); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcflow().
tcflush()
int tcflush (int fd, int queue_selector)
Definition at line 52 of file termios-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcflush, -1);
     if(int e = mlibc::sys_tcflush(fd, queue_selector); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcflush().
tcgetattr()
int tcgetattr (int fd, struct termios * attr)
Definition at line 61 of file termios-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcgetattr, -1);
     if(int e = mlibc::sys_tcgetattr(fd, attr); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References mlibc::attr, errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcgetattr().
Referenced by getpass().
tcgetsid()
pid_t tcgetsid (int fd)
Definition at line 70 of file termios-stubs.cpp.
{
     int sid;
     if(ioctl(fd, TIOCGSID, &sid) < 0) {
         return -1;
     }
     return sid;
 }
References fd, ioctl(), and TIOCGSID.
tcsendbreak()
int tcsendbreak (int , int)
Definition at line 78 of file termios-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
tcsetattr()
int tcsetattr (int fd, int opts, const struct termios * attr)
Definition at line 83 of file termios-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_tcsetattr, -1);
     if(int e = mlibc::sys_tcsetattr(fd, opts, attr); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References mlibc::attr, errno, fd, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_tcsetattr().
Referenced by getpass().