Fennix: Userspace/apps/base/busybox/libbb/bbunit.c File Reference
bbunit.c File Reference
#include "libbb.h"
Functions
void bbunit_registertest (struct bbunit_listelem *test)
void bbunit_settestfailed (void)
int unit_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM) MAIN_EXTERNALLY_VISIBLE
Variables
static llist_t * tests = NULL
static unsigned tests_registered = 0
static int test_retval
Function Documentation
bbunit_registertest()
void bbunit_registertest (struct bbunit_listelem * test)
Definition at line 24 of file bbunit.c.
 {
     llist_add_to_end(&tests, test);
     tests_registered++;
 }
References llist_add_to_end(), test, tests, and tests_registered.
bbunit_settestfailed()
void bbunit_settestfailed (void)
Definition at line 30 of file bbunit.c.
 {
     test_retval = -1;
 }
References test_retval.
unit_main()
int unit_main (int argc UNUSED_PARAM, char **argv UNUSED_PARAM)
Definition at line 36 of file bbunit.c.
 {
     unsigned tests_run = 0;
     unsigned tests_failed = 0;
     bb_error_msg("Running %d test(s)...", tests_registered);
     for (;;) {
         struct bbunit_listelem* el = llist_pop(&tests);
         if (!el)
             break;
         bb_error_msg("Case: [%s]", el->name);
         test_retval = 0;
         el->testfunc();
         if (test_retval < 0) {
             bb_error_msg("[ERROR] [%s]: TEST FAILED", el->name);
             tests_failed++;
         }
         tests_run++;
     }
     if (tests_failed > 0) {
         bb_error_msg("[ERROR] %u test(s) FAILED", tests_failed);
         return EXIT_FAILURE;
     }
     bb_simple_error_msg("All tests passed");
     return EXIT_SUCCESS;
 }
References bb_error_msg(), bb_simple_error_msg(), EXIT_FAILURE, EXIT_SUCCESS, llist_pop(), bbunit_listelem::name, test_retval, bbunit_listelem::testfunc, tests, and tests_registered.
Variable Documentation
test_retval
int test_retval static
Definition at line 22 of file bbunit.c.
Referenced by bbunit_settestfailed(), and unit_main().
tests
llist_t* tests = NULL static
Definition at line 20 of file bbunit.c.
Referenced by bbunit_registertest(), and unit_main().
tests_registered
unsigned tests_registered = 0 static
Definition at line 21 of file bbunit.c.
Referenced by bbunit_registertest(), and unit_main().