Fennix Userspace: Userspace/musl/arch/aarch64/crt_arch.h File Reference
crt_arch.h File Reference
Functions
__asm__ (".text \n" ".global " START "\n" ".type " START ",%function\n" START ":\n" " mov x29, #0\n" " mov x30, #0\n" " mov x0, sp\n" ".weak _DYNAMIC\n" ".hidden _DYNAMIC\n" " adrp x1, _DYNAMIC\n" " add x1, x1, #:lo12:_DYNAMIC\n" " and sp, x0, #-16\n" " b " START "_c\n")
Function Documentation
__asm__()
__asm__ (".text \n" ".global " START "\n" ".type " START " , %function\n" START ":\n" " mov x29, #0\n" " mov x30, #0\n" " mov x0, sp\n" ".weak _DYNAMIC\n" ".hidden _DYNAMIC\n" " adrp x1, _DYNAMIC\n" " add x1, x1 , #:lo12:_DYNAMIC\n" " and sp, x0 , #-16\n" " b " START "_c\n")
Referenced by __attribute__(), __get_tp(), __libc_start_main(), __lseek(), __lsysinfo(), __set_thread_area(), __syscall0(), __syscall1(), __syscall2(), __syscall3(), __syscall4(), __syscall5(), __syscall6(), __syscall7(), _exit(), a_and(), a_and_64(), a_cas(), a_cas_p(), a_clz_32(), a_clz_64(), a_ctz_32(), a_ctz_64(), a_dec(), a_fetch_add(), a_inc(), a_ll(), a_ll_p(), a_or(), a_or_64(), a_sc(), a_sc_p(), a_store(), a_swap(), ceil(), ceilf(), explicit_bzero(), fabs(), fabsf(), fabsl(), floor(), floorf(), fma(), fmaf(), fmax(), fmaxf(), fmin(), fminf(), fmod(), fmodf(), fmodl(), fp_barrier(), fp_barrierf(), fp_force_eval(), fp_force_evalf(), get_fpc(), get_fpscr_f(), inb(), inl(), insb(), insl(), insw(), inw(), llrint(), llrintf(), llrintl(), llround(), llroundf(), lrint(), lrintf(), lrintl(), lround(), lroundf(), nearbyint(), nearbyintf(), outb(), outl(), outsb(), outsl(), outsw(), outw(), putchar_wrapper_libint(), PutCharToKernelConsole(), remainder(), remainderf(), remainderl(), remquol(), rint(), rintf(), rintl(), round(), roundf(), set_fpc(), set_fpscr_f(), sqrt(), sqrtf(), sqrtl(), trunc(), and truncf().