Fennix Userspace: Userspace/musl/include/dirent.h File Reference
dirent.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/dirent.h>
Macros
#define __NEED_ino_t
#define __NEED_off_t
#define d_fileno d_ino
Typedefs
typedef struct __dirstream DIR
Functions
int closedir (DIR *)
DIR * fdopendir (int)
DIR * opendir (const char *)
struct dirent * readdir (DIR *)
int readdir_r (DIR *__restrict, struct dirent *__restrict, struct dirent **__restrict)
void rewinddir (DIR *)
int dirfd (DIR *)
int alphasort (const struct dirent **, const struct dirent **)
int scandir (const char *, struct dirent ***, int(*)(const struct dirent *), int(*)(const struct dirent **, const struct dirent **))
Macro Definition Documentation
__NEED_ino_t
#define __NEED_ino_t
Definition at line 10 of file dirent.h.
__NEED_off_t
#define __NEED_off_t
Definition at line 11 of file dirent.h.
d_fileno
#define d_fileno d_ino
Definition at line 22 of file dirent.h.
Typedef Documentation
DIR
typedef struct __dirstream DIR
Definition at line 1 of file dirent.h.
Function Documentation
alphasort()
int alphasort (const struct dirent ** a, const struct dirent ** b)
Definition at line 4 of file alphasort.c.
 {
     return strcoll((*a)->d_name, (*b)->d_name);
 }
References strcoll().
closedir()
int closedir (DIR * dir)
Definition at line 6 of file closedir.c.
 {
     int ret = close(dir->fd);
     free(dir);
     return ret;
 }
References close(), __dirstream::fd, and free.
Referenced by do_glob(), do_nftw(), scandir(), and test_dirent().
dirfd()
int dirfd (DIR * d)
Definition at line 4 of file dirfd.c.
 {
     return d->fd;
 }
References __dirstream::fd.
fdopendir()
DIR* fdopendir (int fd)
Definition at line 8 of file fdopendir.c.
 {
     DIR *dir;
     struct stat st;
     if (fstat(fd, &st) < 0) {
         return 0;
     }
     if (fcntl(fd, F_GETFL) & O_PATH) {
         errno = EBADF;
         return 0;
     }
     if (!S_ISDIR(st.st_mode)) {
         errno = ENOTDIR;
         return 0;
     }
     if (!(dir = calloc(1, sizeof *dir))) {
         return 0;
     }
     fcntl(fd, F_SETFD, FD_CLOEXEC);
     dir->fd = fd;
     return dir;
 }
References calloc, EBADF, ENOTDIR, errno, F_GETFL, F_SETFD, fcntl(), __dirstream::fd, FD_CLOEXEC, fstat(), O_PATH, and S_ISDIR.
Referenced by do_nftw().
opendir()
DIR* opendir (const char * name)
Definition at line 8 of file opendir.c.
 {
     int fd;
     DIR *dir;
     if ((fd = open(name, O_RDONLY|O_DIRECTORY|O_CLOEXEC)) < 0)
         return 0;
     if (!(dir = calloc(1, sizeof *dir))) {
         __syscall(SYS_close, fd);
         return 0;
     }
     dir->fd = fd;
     return dir;
 }
References __syscall, calloc, __dirstream::fd, O_CLOEXEC, O_DIRECTORY, O_RDONLY, and open().
Referenced by do_glob(), scandir(), and test_dirent().
readdir()
struct dirent* readdir (DIR * dir)
Definition at line 10 of file readdir.c.
 {
     struct dirent *de;
     if (dir->buf_pos >= dir->buf_end) {
         int len = __syscall(SYS_getdents, dir->fd, dir->buf, sizeof dir->buf);
         if (len <= 0) {
             if (len < 0 && len != -ENOENT) errno = -len;
             return 0;
         }
         dir->buf_end = len;
         dir->buf_pos = 0;
     }
     de = (void *)(dir->buf + dir->buf_pos);
     dir->buf_pos += de->d_reclen;
     dir->tell = de->d_off;
     return de;
 }
References __syscall, __dirstream::buf, __dirstream::buf_end, __dirstream::buf_pos, dirent::d_off, dirent::d_reclen, ENOENT, errno, __dirstream::fd, and __dirstream::tell.
Referenced by do_glob(), do_nftw(), readdir_r(), scandir(), and test_dirent().
readdir_r()
int readdir_r (DIR * __restrict, struct dirent * __restrict, struct dirent ** __restrict)
rewinddir()
void rewinddir (DIR * dir)
Definition at line 6 of file rewinddir.c.
 {
     LOCK(dir->lock);
     lseek(dir->fd, 0, SEEK_SET);
     dir->buf_pos = dir->buf_end = 0;
     dir->tell = 0;
     UNLOCK(dir->lock);
 }
References __dirstream::buf_end, __dirstream::buf_pos, __dirstream::fd, LOCK, __dirstream::lock, lseek(), SEEK_SET, __dirstream::tell, and UNLOCK.
scandir()
int scandir (const char * path, struct dirent *** res, int(*)(const struct dirent *) sel, int(*)(const struct dirent **, const struct dirent **) cmp)
Definition at line 8 of file scandir.c.
 {
     DIR *d = opendir(path);
     struct dirent *de, **names=0, **tmp;
     size_t cnt=0, len=0;
     int old_errno = errno;
     if (!d) return -1;
     while ((errno=0), (de = readdir(d))) {
         if (sel && !sel(de)) continue;
         if (cnt >= len) {
             len = 2*len+1;
             if (len > SIZE_MAX/sizeof *names) break;
             tmp = realloc(names, len * sizeof *names);
             if (!tmp) break;
             names = tmp;
         }
         names[cnt] = malloc(de->d_reclen);
         if (!names[cnt]) break;
         memcpy(names[cnt++], de, de->d_reclen);
     }
     closedir(d);
     if (errno) {
         if (names) while (cnt-->0) free(names[cnt]);
         free(names);
         return -1;
     }
     errno = old_errno;
     if (cmp) qsort(names, cnt, sizeof *names, (int (*)(const void *, const void *))cmp);
     *res = names;
     return cnt;
 }
References closedir(), cmp(), cnt, dirent::d_reclen, errno, free, malloc, memcpy(), opendir(), qsort(), readdir(), realloc, and SIZE_MAX.