Fennix Userspace: Userspace/apps/base/busybox/selinux/runcon.c File Reference
runcon.c File Reference
#include <selinux/context.h>
#include "libbb.h"
Macros
#define SECCLASS_PROCESS 2
#define OPTS_ROLE (1<<0) /* r */
#define OPTS_TYPE (1<<1) /* t */
#define OPTS_USER (1<<2) /* u */
#define OPTS_RANGE (1<<3) /* l */
#define OPTS_COMPUTE (1<<4) /* c */
#define OPTS_HELP (1<<5) /* h */
#define OPTS_CONTEXT_COMPONENT (OPTS_ROLE | OPTS_TYPE | OPTS_USER | OPTS_RANGE)
Functions
static context_t runcon_compute_new_context (char *user, char *role, char *type, char *range, char *command, int compute_trans)
int runcon_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
OPTS_COMPUTE
#define OPTS_COMPUTE (1<<4) /* c */
Definition at line 112 of file runcon.c.
OPTS_CONTEXT_COMPONENT
#define OPTS_CONTEXT_COMPONENT (OPTS_ROLE | OPTS_TYPE | OPTS_USER | OPTS_RANGE)
Definition at line 114 of file runcon.c.
OPTS_HELP
#define OPTS_HELP (1<<5) /* h */
Definition at line 113 of file runcon.c.
OPTS_RANGE
#define OPTS_RANGE (1<<3) /* l */
Definition at line 111 of file runcon.c.
OPTS_ROLE
#define OPTS_ROLE (1<<0) /* r */
Definition at line 108 of file runcon.c.
OPTS_TYPE
#define OPTS_TYPE (1<<1) /* t */
Definition at line 109 of file runcon.c.
OPTS_USER
#define OPTS_USER (1<<2) /* u */
Definition at line 110 of file runcon.c.
SECCLASS_PROCESS
#define SECCLASS_PROCESS 2
Definition at line 57 of file runcon.c.
Function Documentation
runcon_compute_new_context()
static context_t runcon_compute_new_context (char * user, char * role, char * type, char * range, char * command, int compute_trans) static
Definition at line 61 of file runcon.c.
 {
     context_t con;
     security_context_t cur_context;
     if (getcon(&cur_context))
         bb_simple_error_msg_and_die("can't get current context");
     if (compute_trans) {
         security_context_t file_context, new_context;
         if (getfilecon(command, &file_context) < 0)
             bb_error_msg_and_die("can't retrieve attributes of '%s'",
                     command);
         if (security_compute_create(cur_context, file_context,
                     SECCLASS_PROCESS, &new_context))
             bb_simple_error_msg_and_die("unable to compute a new context");
         cur_context = new_context;
     }
     con = context_new(cur_context);
     if (!con)
         bb_error_msg_and_die("'%s' is not a valid context", cur_context);
     if (user && context_user_set(con, user))
         bb_error_msg_and_die("can't set new user '%s'", user);
     if (type && context_type_set(con, type))
         bb_error_msg_and_die("can't set new type '%s'", type);
     if (range && context_range_set(con, range))
         bb_error_msg_and_die("can't set new range '%s'", range);
     if (role && context_role_set(con, role))
         bb_error_msg_and_die("can't set new role '%s'", role);
     return con;
 }
References bb_error_msg_and_die(), bb_simple_error_msg_and_die(), range, role, SECCLASS_PROCESS, and type.
Referenced by runcon_main().
runcon_main()
int runcon_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 117 of file runcon.c.
 {
     char *role = NULL;
     char *range = NULL;
     char *user = NULL;
     char *type = NULL;
     char *context = NULL;
     unsigned opts;
     context_t con;
     selinux_or_die();
     opts = getopt32long(argv, "^"
             "r:t:u:l:ch"
             "\0" "-1",
             runcon_longopts,
             &role, &type, &user, &range
     );
     argv += optind;
     if (!(opts & OPTS_CONTEXT_COMPONENT)) {
         context = *argv++;
         if (!argv[0])
             bb_simple_error_msg_and_die("no command given");
     }
     if (context) {
         con = context_new(context);
         if (!con)
             bb_error_msg_and_die("'%s' is not a valid context", context);
     } else {
         con = runcon_compute_new_context(user, role, type, range,
                 argv[0], opts & OPTS_COMPUTE);
     }
     if (security_check_context(context_str(con)))
         bb_error_msg_and_die("'%s' is not a valid context",
                 context_str(con));
     if (setexeccon(context_str(con)))
         bb_error_msg_and_die("can't set up security context '%s'",
                 context_str(con));
     BB_EXECVP_or_die(argv);
 }
References argv, bb_error_msg_and_die(), BB_EXECVP_or_die(), bb_simple_error_msg_and_die(), context, getopt32long, NULL, optind, OPTS_COMPUTE, OPTS_CONTEXT_COMPONENT, range, role, runcon_compute_new_context(), selinux_or_die(), and type.