Fennix: Userspace/mlibc/sysdeps/managarm/include/mlibc/thread-entry.hpp File Reference
thread-entry.hpp File Reference
#include <mlibc/tcb.hpp>
Namespaces
mlibc
Functions
void __mlibc_start_thread (void)
void __mlibc_enter_thread (void *entry, void *user_arg, Tcb *tcb)
void * mlibc::prepare_stack (void *entry, void *user_arg, void *tcb)
Function Documentation
__mlibc_enter_thread()
void __mlibc_enter_thread (void * entry, void * user_arg, Tcb * tcb)
Definition at line 12 of file thread.cpp.
{
     // Wait until our parent sets up the TID:
     while (!__atomic_load_n(&tcb->tid, __ATOMIC_RELAXED))
         mlibc::sys_futex_wait(&tcb->tid, 0, nullptr);
     if (mlibc::sys_tcb_set(tcb))
         __ensure(!"sys_tcb_set() failed");
     void *(*func)(void *) = reinterpret_cast<void *(*)(void *)>(entry);
     auto result = func(user_arg);
     auto self = reinterpret_cast<Tcb *>(tcb);
     self->returnValue = result;
     __atomic_store_n(&self->didExit, 1, __ATOMIC_RELEASE);
     mlibc::sys_futex_wake(&self->didExit);
     mlibc::sys_thread_exit();
 }
References __ensure, Tcb::returnValue, mlibc::sys_futex_wait(), mlibc::sys_futex_wake(), mlibc::sys_tcb_set(), mlibc::sys_thread_exit(), and Tcb::tid.
__mlibc_start_thread()
void __mlibc_start_thread (void)