Fennix Userspace: Userspace/apps/base/busybox/libbb/perror_nomsg_and_die.c File Reference
perror_nomsg_and_die.c File Reference
#include "platform.h"
Functions
void bb_perror_msg_and_die (const char *s,...) FAST_FUNC
void FAST_FUNC bb_perror_nomsg_and_die (void)
Function Documentation
bb_perror_msg_and_die()
void bb_perror_msg_and_die (const char * s, ...)
Definition at line 21 of file perror_msg.c.
 {
     va_list p;
     va_start(p, s);
     /* Guard against "<error message>: Success" */
     bb_verror_msg(s, p, errno ? strerror(errno) : NULL);
     va_end(p);
     xfunc_die();
 }
References bb_verror_msg(), errno, NULL, p, s, strerror(), va_end, va_start, and xfunc_die().
Referenced by add_remove_shell_main(), BB_EXECVP_or_die(), bb_init_module_24(), bb_perror_nomsg_and_die(), bb_simple_perror_msg_and_die(), bb_xioctl(), bootchartd_main(), brctl_main(), change_active(), chcon_main(), chrt_main(), create_or_remember_link(), data_extract_all(), data_extract_to_command(), do_pidfile(), edir(), edit_file(), exec_shell(), fallocate_main(), fatal2_cannot(), fbset_main(), flashcp_main(), flock_main(), fork_transformer(), get_aff(), get_drv_info(), get_lstat_mode(), get_num_from_file(), halt_main(), i2c_dev_open(), inotifyd_main(), ionice_main(), link_main(), logread_main(), make_tempdir(), matchpathcon_main(), microcom_main(), mount_main(), mount_or_die(), nc_main(), new_get_kernel_symbols(), new_init_module(), nice_main(), nsenter_main(), open_new_state_file(), parse_params(), perror_on_device_and_die(), process_pid_str(), processorstart(), re_exec(), read_interfaces(), read_new_seed(), recv_and_process_peer_pkt(), rmmod_main(), rpm_gettags(), seed_from_file_if_exists(), seedrng_main(), send_probe(), setarch_main(), setfscreatecon_or_die(), setpriv_main(), start_stop_daemon_main(), switch_root_main(), tar_main(), tcpudpsvd_main(), tls_xread_record(), traceroute_init(), ubi_tools_main(), unshare_main(), xchroot(), xconnect(), xfopen(), xfreopen_write(), xlseek(), xmalloc_xopen_read_close(), xmkpath(), xmkstemp(), xopen3(), xopendir(), xrename(), xsocket(), xstat(), and xunlink().
bb_perror_nomsg_and_die()
void FAST_FUNC bb_perror_nomsg_and_die (void)
Definition at line 19 of file perror_nomsg_and_die.c.
 {
     bb_perror_msg_and_die(0);
 }
References bb_perror_msg_and_die().
Referenced by adjtimex_main(), convert(), flock_main(), ftp_login(), halt_main(), mesg_main(), mktemp_main(), modprobe_main(), pivot_root_main(), pscan_main(), tail_xprint_header(), and yes_main().