Fennix: Userspace/apps/base/busybox/util-linux/volume_id/volume_id_internal.h File Reference
volume_id_internal.h File Reference
#include "libbb.h"
#include "volume_id.h"
Data Structures
struct volume_id
Macros
#define dbg(...) ((void)0)
#define VOLUME_ID_VERSION 48
#define VOLUME_ID_LABEL_SIZE 64
#define VOLUME_ID_UUID_SIZE 36
#define VOLUME_ID_FORMAT_SIZE 32
#define VOLUME_ID_PARTITIONS_MAX 256
#define SB_BUFFER_SIZE 0x11000
#define SEEK_BUFFER_SIZE 0x10000
#define le16_to_cpu(x) (uint16_t)(bswap_16(x))
#define le32_to_cpu(x) (uint32_t)(bswap_32(x))
#define le64_to_cpu(x) (uint64_t)(bb_bswap_64(x))
#define be16_to_cpu(x) (uint16_t)(x)
#define be32_to_cpu(x) (uint32_t)(x)
#define cpu_to_le16(x) (uint16_t)(bswap_16(x))
#define cpu_to_le32(x) (uint32_t)(bswap_32(x))
#define cpu_to_be32(x) (uint32_t)(x)
Enumerations
enum volume_id_usage {
VOLUME_ID_UNUSED , VOLUME_ID_UNPROBED , VOLUME_ID_OTHER , VOLUME_ID_FILESYSTEM ,
VOLUME_ID_PARTITIONTABLE , VOLUME_ID_RAID , VOLUME_ID_DISKLABEL , VOLUME_ID_CRYPTO
}
enum uuid_format { UUID_DOS = 0 , UUID_NTFS = 1 , UUID_DCE = 2 , UUID_DCE_STRING = 3 }
enum endian { LE = 0 , BE = 1 }
Functions
struct volume_id *FAST_FUNC volume_id_open_node (int fd)
int FAST_FUNC volume_id_probe_all (struct volume_id *id, uint64_t size)
void FAST_FUNC free_volume_id (struct volume_id *id)
void volume_id_set_unicode16 (char *str, size_t len, const uint8_t *buf, enum endian endianess, size_t count)
void volume_id_set_label_string (struct volume_id *id, const uint8_t *buf, size_t count)
void volume_id_set_label_unicode16 (struct volume_id *id, const uint8_t *buf, enum endian endianess, size_t count)
void volume_id_set_uuid (struct volume_id *id, const uint8_t *buf, enum uuid_format format)
void * volume_id_get_buffer (struct volume_id *id, uint64_t off, size_t len)
void volume_id_free_buffer (struct volume_id *id)
int FAST_FUNC volume_id_probe_linux_raid (struct volume_id *id, uint64_t size)
int FAST_FUNC volume_id_probe_bcache (struct volume_id *id)
int FAST_FUNC volume_id_probe_btrfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_cramfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_ext (struct volume_id *id)
int FAST_FUNC volume_id_probe_vfat (struct volume_id *id)
int FAST_FUNC volume_id_probe_hfs_hfsplus (struct volume_id *id)
int FAST_FUNC volume_id_probe_iso9660 (struct volume_id *id)
int FAST_FUNC volume_id_probe_jfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_lfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_linux_swap (struct volume_id *id)
int FAST_FUNC volume_id_probe_luks (struct volume_id *id)
int FAST_FUNC volume_id_probe_minix (struct volume_id *id)
int FAST_FUNC volume_id_probe_f2fs (struct volume_id *id)
int FAST_FUNC volume_id_probe_nilfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_ntfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_exfat (struct volume_id *id)
int FAST_FUNC volume_id_probe_ocfs2 (struct volume_id *id)
int FAST_FUNC volume_id_probe_reiserfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_romfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_squashfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_erofs (struct volume_id *id)
int FAST_FUNC volume_id_probe_sysv (struct volume_id *id)
int FAST_FUNC volume_id_probe_udf (struct volume_id *id)
int FAST_FUNC volume_id_probe_xfs (struct volume_id *id)
int FAST_FUNC volume_id_probe_ubifs (struct volume_id *id)
Data Structure Documentation
volume_id
struct volume_id
Definition at line 60 of file volume_id_internal.h.
Data Fields
int error
int fd
char label[VOLUME_ID_LABEL_SIZE+1]
uint8_t * sbbuf
size_t sbbuf_len
uint8_t * seekbuf
size_t seekbuf_len
uint64_t seekbuf_off
char uuid[VOLUME_ID_UUID_SIZE+1]
Macro Definition Documentation
be16_to_cpu
#define be16_to_cpu (x) (uint16_t)(x)
Definition at line 112 of file volume_id_internal.h.
be32_to_cpu
#define be32_to_cpu (x) (uint32_t)(x)
Definition at line 113 of file volume_id_internal.h.
cpu_to_be32
#define cpu_to_be32 (x) (uint32_t)(x)
Definition at line 116 of file volume_id_internal.h.
cpu_to_le16
#define cpu_to_le16 (x) (uint16_t)(bswap_16(x))
Definition at line 114 of file volume_id_internal.h.
cpu_to_le32
#define cpu_to_le32 (x) (uint32_t)(bswap_32(x))
Definition at line 115 of file volume_id_internal.h.
dbg
#define dbg (...) ((void)0)
Definition at line 26 of file volume_id_internal.h.
le16_to_cpu
#define le16_to_cpu (x) (uint16_t)(bswap_16(x))
Definition at line 109 of file volume_id_internal.h.
le32_to_cpu
#define le32_to_cpu (x) (uint32_t)(bswap_32(x))
Definition at line 110 of file volume_id_internal.h.
le64_to_cpu
#define le64_to_cpu (x) (uint64_t)(bb_bswap_64(x))
Definition at line 111 of file volume_id_internal.h.
SB_BUFFER_SIZE
#define SB_BUFFER_SIZE 0x11000
Definition at line 95 of file volume_id_internal.h.
SEEK_BUFFER_SIZE
#define SEEK_BUFFER_SIZE 0x10000
Definition at line 97 of file volume_id_internal.h.
VOLUME_ID_FORMAT_SIZE
#define VOLUME_ID_FORMAT_SIZE 32
Definition at line 35 of file volume_id_internal.h.
VOLUME_ID_LABEL_SIZE
#define VOLUME_ID_LABEL_SIZE 64
Definition at line 33 of file volume_id_internal.h.
VOLUME_ID_PARTITIONS_MAX
#define VOLUME_ID_PARTITIONS_MAX 256
Definition at line 36 of file volume_id_internal.h.
VOLUME_ID_UUID_SIZE
#define VOLUME_ID_UUID_SIZE 36
Definition at line 34 of file volume_id_internal.h.
VOLUME_ID_VERSION
#define VOLUME_ID_VERSION 48
Definition at line 31 of file volume_id_internal.h.
Enumeration Type Documentation
endian
enum endian
Enumerator
LE
BE
Definition at line 130 of file volume_id_internal.h.
             {
     LE = 0,
     BE = 1
 };
uuid_format
enum uuid_format
Enumerator
UUID_DOS
UUID_NTFS
UUID_DCE
UUID_DCE_STRING
Definition at line 123 of file volume_id_internal.h.
                  {
     UUID_DOS = 0,       /* 4 bytes */
     UUID_NTFS = 1,      /* 8 bytes */
     UUID_DCE = 2,       /* 16 bytes */
     UUID_DCE_STRING = 3,    /* 36 bytes (VOLUME_ID_UUID_SIZE) */
 };
volume_id_usage
enum volume_id_usage
Enumerator
VOLUME_ID_UNUSED
VOLUME_ID_UNPROBED
VOLUME_ID_OTHER
VOLUME_ID_FILESYSTEM
VOLUME_ID_PARTITIONTABLE
VOLUME_ID_RAID
VOLUME_ID_DISKLABEL
VOLUME_ID_CRYPTO
Definition at line 38 of file volume_id_internal.h.
                      {
     VOLUME_ID_UNUSED,
     VOLUME_ID_UNPROBED,
     VOLUME_ID_OTHER,
     VOLUME_ID_FILESYSTEM,
     VOLUME_ID_PARTITIONTABLE,
     VOLUME_ID_RAID,
     VOLUME_ID_DISKLABEL,
     VOLUME_ID_CRYPTO,
 };
Function Documentation
free_volume_id()
void FAST_FUNC free_volume_id (struct volume_id * id)
Definition at line 259 of file volume_id.c.
 {
     if (id == NULL)
         return;
     //if (id->fd_close != 0) - always true
         close(id->fd);
     volume_id_free_buffer(id);
 #ifdef UNUSED_PARTITION_CODE
     free(id->partitions);
 #endif
     free(id);
 }
References close(), volume_id::fd, free, NULL, and volume_id_free_buffer().
Referenced by get_label_uuid().
volume_id_free_buffer()
void volume_id_free_buffer (struct volume_id * id)
Definition at line 256 of file util.c.
 {
     free(id->sbbuf);
     id->sbbuf = NULL;
     id->sbbuf_len = 0;
     free(id->seekbuf);
     id->seekbuf = NULL;
     id->seekbuf_len = 0;
     id->seekbuf_off = 0; /* paranoia */
 }
References free, NULL, volume_id::sbbuf, and volume_id::seekbuf.
Referenced by free_volume_id(), volume_id_get_buffer(), and volume_id_probe_all().
volume_id_get_buffer()
void* volume_id_get_buffer (struct volume_id * id, uint64_t off, size_t len)
Definition at line 179 of file util.c.
 {
     uint8_t *dst;
     unsigned small_off;
     ssize_t read_len;
     dbg("get buffer off 0x%llx(%llu), len 0x%zx",
         (unsigned long long) off, (unsigned long long) off, len);
     /* check if requested area fits in superblock buffer */
     if (off + len <= SB_BUFFER_SIZE
      /* && off <= SB_BUFFER_SIZE - want this paranoid overflow check? */
     ) {
         if (id->sbbuf == NULL) {
             id->sbbuf = xmalloc(SB_BUFFER_SIZE);
         }
         small_off = off;
         dst = id->sbbuf;
         /* check if we need to read */
         len += off;
         if (len <= id->sbbuf_len)
             goto ret; /* we already have it */
         dbg("read sbbuf len:0x%x", (unsigned) len);
         id->sbbuf_len = len;
         off = 0;
         goto do_read;
     }
     if (len > SEEK_BUFFER_SIZE) {
         dbg("seek buffer too small %d", SEEK_BUFFER_SIZE);
         return NULL;
     }
     dst = id->seekbuf;
     /* check if we need to read */
     if ((off >= id->seekbuf_off)
      && ((off + len) <= (id->seekbuf_off + id->seekbuf_len))
     ) {
         small_off = off - id->seekbuf_off; /* can't overflow */
         goto ret; /* we already have it */
     }
     id->seekbuf_off = off;
     id->seekbuf_len = len;
     id->seekbuf = xrealloc(id->seekbuf, len);
     small_off = 0;
     dst = id->seekbuf;
     dbg("read seekbuf off:0x%llx len:0x%zx",
                 (unsigned long long) off, len);
  do_read:
     if (lseek(id->fd, off, SEEK_SET) != off) {
         dbg("seek(0x%llx) failed", (unsigned long long) off);
         goto err;
     }
     read_len = full_read(id->fd, dst, len);
     if (read_len != len) {
         dbg("requested 0x%x bytes, got 0x%x bytes",
                 (unsigned) len, (unsigned) read_len);
  err:
         /* No filesystem can be this tiny. It's most likely
          * non-associated loop device, empty drive and so on.
          * Flag it, making it possible to short circuit future
          * accesses. Rationale:
          * users complained of slow blkid due to empty floppy drives.
          */
         if (off < 64*1024)
             id->error = 1;
         /* id->seekbuf_len or id->sbbuf_len is wrong now! Fixing. */
         volume_id_free_buffer(id);
         return NULL;
     }
  ret:
     return dst + small_off;
 }
References dbg, do_read(), dst, err(), volume_id::fd, full_read(), len, lseek(), NULL, off, SB_BUFFER_SIZE, volume_id::sbbuf, SEEK_BUFFER_SIZE, SEEK_SET, volume_id::seekbuf, volume_id::seekbuf_len, volume_id::seekbuf_off, volume_id_free_buffer(), xmalloc, and xrealloc.
Referenced by volume_id_probe_all(), volume_id_probe_bcache(), volume_id_probe_btrfs(), volume_id_probe_cramfs(), volume_id_probe_erofs(), volume_id_probe_exfat(), volume_id_probe_ext(), volume_id_probe_f2fs(), volume_id_probe_hfs_hfsplus(), volume_id_probe_highpoint_37x_raid(), volume_id_probe_highpoint_45x_raid(), volume_id_probe_hpfs(), volume_id_probe_intel_software_raid(), volume_id_probe_iso9660(), volume_id_probe_jfs(), volume_id_probe_lfs(), volume_id_probe_linux_raid(), volume_id_probe_linux_swap(), volume_id_probe_lsi_mega_raid(), volume_id_probe_luks(), volume_id_probe_lvm1(), volume_id_probe_lvm2(), volume_id_probe_mac_partition_map(), volume_id_probe_minix(), volume_id_probe_msdos_part_table(), volume_id_probe_nilfs(), volume_id_probe_ntfs(), volume_id_probe_nvidia_raid(), volume_id_probe_ocfs2(), volume_id_probe_promise_fasttrack_raid(), volume_id_probe_reiserfs(), volume_id_probe_romfs(), volume_id_probe_silicon_medley_raid(), volume_id_probe_squashfs(), volume_id_probe_sysv(), volume_id_probe_ubifs(), volume_id_probe_udf(), volume_id_probe_ufs(), volume_id_probe_vfat(), volume_id_probe_via_raid(), and volume_id_probe_xfs().
volume_id_open_node()
struct volume_id* FAST_FUNC volume_id_open_node (int fd)
close fd on device close *‍/
Definition at line 226 of file volume_id.c.
 {
     struct volume_id *id;
     id = xzalloc(sizeof(struct volume_id));
     id->fd = fd;
     //id->fd_close = 1;
     return id;
 }
References fd, and xzalloc().
Referenced by get_label_uuid().
volume_id_probe_all()
int FAST_FUNC volume_id_probe_all (struct volume_id * id, uint64_t size)
Definition at line 181 of file volume_id.c.
 {
     unsigned i;
     /* probe for raid first, cause fs probes may be successful on raid members */
     if (size) {
         for (i = 0; i < ARRAY_SIZE(raid1); i++) {
             if (raid1[i](id, /*off,*/ size) == 0)
                 goto ret;
             if (id->error)
                 goto ret;
         }
     }
     for (i = 0; i < ARRAY_SIZE(raid2); i++) {
         if (raid2[i](id /*,off*/) == 0)
             goto ret;
         if (id->error)
             goto ret;
     }
     /* signature in the first block, only small buffer needed */
     for (i = 0; i < ARRAY_SIZE(fs1); i++) {
         if (fs1[i](id /*,off*/) == 0)
             goto ret;
         if (id->error)
             goto ret;
     }
     /* fill buffer with maximum */
     volume_id_get_buffer(id, 0, SB_BUFFER_SIZE);
     for (i = 0; i < ARRAY_SIZE(fs2); i++) {
         if (fs2[i](id /*,off*/) == 0)
             goto ret;
         if (id->error)
             goto ret;
     }
  ret:
     volume_id_free_buffer(id);
     return (- id->error); /* 0 or -1 */
 }
References ARRAY_SIZE, volume_id::error, i, SB_BUFFER_SIZE, size, volume_id_free_buffer(), and volume_id_get_buffer().
Referenced by get_label_uuid().
volume_id_probe_bcache()
int FAST_FUNC volume_id_probe_bcache (struct volume_id * id)
Definition at line 89 of file bcache.c.
 {
     struct bcache_super_block *sb;
     sb = volume_id_get_buffer(id, BCACHE_SB_OFF, sizeof(*sb));
     if (sb == NULL)
         return -1;
     if (memcmp(sb->magic, BCACHE_SB_MAGIC, BCACHE_SB_MAGIC_LEN) != 0)
         return -1;
     volume_id_set_label_string(id, sb->label, SB_LABEL_SIZE);
     volume_id_set_uuid(id, sb->uuid, UUID_DCE);
     IF_FEATURE_BLKID_TYPE(id->type = "bcache";)
     return 0;
 }
References BCACHE_SB_MAGIC, BCACHE_SB_MAGIC_LEN, BCACHE_SB_OFF, bcache_super_block::label, bcache_super_block::magic, memcmp(), NULL, SB_LABEL_SIZE, bcache_super_block::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_probe_btrfs()
int FAST_FUNC volume_id_probe_btrfs (struct volume_id * id)
Definition at line 87 of file btrfs.c.
 {
     // btrfs has superblocks at 64K, 64M and 256G
     // minimum btrfs size is 256M
     // so we never step out the device if we analyze
     // the first and the second superblocks
     struct btrfs_super_block *sb;
     unsigned off = 64;
     while (off < 64*1024*1024) {
         off *= 1024;
         dbg("btrfs: probing at offset 0x%x", off);
         sb = volume_id_get_buffer(id, off, sizeof(*sb));
         if (sb == NULL)
             return -1;
         if (memcmp(sb->magic, BTRFS_MAGIC, 8) != 0)
             return -1;
     }
     // N.B.: btrfs natively supports 256 (>VOLUME_ID_LABEL_SIZE) size labels
     volume_id_set_label_string(id, sb->label, VOLUME_ID_LABEL_SIZE);
     volume_id_set_uuid(id, sb->fsid, UUID_DCE);
     IF_FEATURE_BLKID_TYPE(id->type = "btrfs";)
     return 0;
 }
References BTRFS_MAGIC, dbg, btrfs_super_block::fsid, btrfs_super_block::label, btrfs_super_block::magic, memcmp(), NULL, off, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_probe_cramfs()
int FAST_FUNC volume_id_probe_cramfs (struct volume_id * id)
Definition at line 44 of file cramfs.c.
 {
 #define off ((uint64_t)0)
     struct cramfs_super *cs;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     cs = volume_id_get_buffer(id, off, 0x200);
     if (cs == NULL)
         return -1;
     if (cs->magic == cpu_to_be32(0x453dcd28)) {
 //      volume_id_set_label_raw(id, cs->name, 16);
         volume_id_set_label_string(id, cs->name, 16);
 //      volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
         IF_FEATURE_BLKID_TYPE(id->type = "cramfs";)
         return 0;
     }
     return -1;
 }
References cpu_to_be32, dbg, cramfs_super::magic, cramfs_super::name, NULL, off, volume_id_get_buffer(), and volume_id_set_label_string().
volume_id_probe_erofs()
int FAST_FUNC volume_id_probe_erofs (struct volume_id * id)
Definition at line 45 of file erofs.c.
 {
     struct erofs_super_block *sb;
     BUILD_BUG_ON(sizeof(struct erofs_super_block) != 128);
     dbg("erofs: probing at offset 0x%llx", EROFS_SUPER_OFFSET);
     sb = volume_id_get_buffer(id, EROFS_SUPER_OFFSET, sizeof(*sb));
     if (!sb)
         return -1;
     if (sb->magic != cpu_to_le32(EROFS_SUPER_MAGIC_V1))
         return -1;
     IF_FEATURE_BLKID_TYPE(id->type = "erofs");
     volume_id_set_label_string(id, sb->volume_name,
         MIN(sizeof(sb->volume_name), VOLUME_ID_LABEL_SIZE));
     volume_id_set_uuid(id, sb->uuid, UUID_DCE);
     return 0;
 }
References BUILD_BUG_ON, cpu_to_le32, dbg, EROFS_SUPER_MAGIC_V1, EROFS_SUPER_OFFSET, erofs_super_block::magic, MIN, erofs_super_block::uuid, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_string(), volume_id_set_uuid(), and erofs_super_block::volume_name.
volume_id_probe_exfat()
int FAST_FUNC volume_id_probe_exfat (struct volume_id * id)
Definition at line 75 of file exfat.c.
 {
     struct exfat_super_block *sb;
     struct exfat_dir_entry *de;
     unsigned    sector_sz;
     unsigned    cluster_sz;
     uint64_t    root_dir_off;
     unsigned    count;
     unsigned    need_lbl_guid;
     // Primary super block
     dbg("exFAT: probing at offset 0x%x", EXFAT_SB_OFFSET);
     sb = volume_id_get_buffer(id, EXFAT_SB_OFFSET, sizeof(*sb));
     if (!sb)
         return -1;
     if (memcmp(sb->fs_name, "EXFAT   ", 8) != 0)
         return -1;
     sector_sz = 1 << sb->bytes_per_sector;
     cluster_sz = sector_sz << sb->sectors_per_cluster;
     // There are no clusters 0 and 1, so the first cluster is 2.
     root_dir_off = (uint64_t)EXFAT_SB_OFFSET +
         // Hmm... should we cast sector_sz/cluster_sz to uint64_t?
         (le32_to_cpu(sb->cluster_heap_offset)) * sector_sz +
         (le32_to_cpu(sb->root_dir) - 2) * cluster_sz;
     dbg("exFAT: sector size 0x%x bytes", sector_sz);
     dbg("exFAT: cluster size 0x%x bytes", cluster_sz);
     dbg("exFAT: root dir is at 0x%llx", (long long)root_dir_off);
     // Use DOS uuid as fallback, if no GUID set
     volume_id_set_uuid(id, sb->vol_serial_nr, UUID_DOS);
     // EXFAT_MAX_DIR_ENTRIES is used as a safety belt.
     // The Root Directory may hold an unlimited number of entries,
     // so we do not want to check all. Usually label and GUID
     // are in the beginning, but there are no guarantees.
     need_lbl_guid = (1 << 0) | (1 << 1);
     for (count = 0; count < EXFAT_MAX_DIR_ENTRIES; count++) {
         de = volume_id_get_buffer(id, root_dir_off + (count * EXFAT_DIR_ENTRY_SZ), EXFAT_DIR_ENTRY_SZ);
         if (de == NULL)
             break;
         if (de->entry_type == 0x00) {
             // End of Directory Marker
             dbg("exFAT: End of root directory reached after %u entries", count);
             break;
         }
         if (de->entry_type == 0x83) {
             // Volume Label Directory Entry
             volume_id_set_label_unicode16(id, (uint8_t *)de->type.label.vol_label,
                         LE, 2 * de->type.label.char_count);
             need_lbl_guid &= ~(1 << 0);
         }
         if (de->entry_type == 0xA0) {
             // Volume GUID Directory Entry
             volume_id_set_uuid(id, de->type.guid.vol_guid, UUID_DCE);
             need_lbl_guid &= ~(1 << 1);
         }
         if (!need_lbl_guid)
             break;
     }
     IF_FEATURE_BLKID_TYPE(id->type = "exfat";)
     return 0;
 }
References exfat_super_block::bytes_per_sector, exfat_super_block::cluster_heap_offset, count, dbg, exfat_dir_entry::entry_type, EXFAT_DIR_ENTRY_SZ, EXFAT_MAX_DIR_ENTRIES, EXFAT_SB_OFFSET, exfat_super_block::fs_name, LE, le32_to_cpu, memcmp(), NULL, exfat_super_block::root_dir, exfat_super_block::sectors_per_cluster, exfat_dir_entry::type, UUID_DCE, UUID_DOS, exfat_super_block::vol_serial_nr, volume_id_get_buffer(), volume_id_set_label_unicode16(), and volume_id_set_uuid().
volume_id_probe_ext()
int FAST_FUNC volume_id_probe_ext (struct volume_id * id)
Definition at line 32 of file ext.c.
 {
 #define off ((uint64_t)0)
     struct ext2_super_block *es;
     dbg("ext: probing at offset 0x%llx", (unsigned long long) off);
     es = volume_id_get_buffer(id, off + EXT_SUPERBLOCK_OFFSET, 0x200);
     if (es == NULL)
         return -1;
     if (es->s_magic != cpu_to_le16(EXT2_SUPER_MAGIC)) {
         dbg("ext: no magic found");
         return -1;
     }
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
 //  volume_id_set_label_raw(id, es->volume_name, 16);
     volume_id_set_label_string(id, (void*)es->s_volume_name, 16);
     volume_id_set_uuid(id, es->s_uuid, UUID_DCE);
     dbg("ext: label '%s' uuid '%s'", id->label, id->uuid);
 #if ENABLE_FEATURE_BLKID_TYPE
     if ((es->s_feature_ro_compat & cpu_to_le32(EXT4_FEATURE_RO_COMPAT_HUGE_FILE | EXT4_FEATURE_RO_COMPAT_DIR_NLINK))
      || (es->s_feature_incompat & cpu_to_le32(EXT4_FEATURE_INCOMPAT_EXTENTS | EXT4_FEATURE_INCOMPAT_64BIT))
     ) {
         id->type = "ext4";
     }
     else if (es->s_feature_compat & cpu_to_le32(EXT3_FEATURE_COMPAT_HAS_JOURNAL))
         id->type = "ext3";
     else
         id->type = "ext2";
 #endif
     return 0;
 }
References cpu_to_le16, cpu_to_le32, dbg, EXT2_SUPER_MAGIC, EXT3_FEATURE_COMPAT_HAS_JOURNAL, EXT4_FEATURE_INCOMPAT_64BIT, EXT4_FEATURE_INCOMPAT_EXTENTS, EXT4_FEATURE_RO_COMPAT_DIR_NLINK, EXT4_FEATURE_RO_COMPAT_HUGE_FILE, EXT_SUPERBLOCK_OFFSET, volume_id::label, NULL, off, ext2_super_block::s_feature_compat, ext2_super_block::s_feature_incompat, ext2_super_block::s_feature_ro_compat, ext2_super_block::s_magic, ext2_super_block::s_uuid, ext2_super_block::s_volume_name, volume_id::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_probe_f2fs()
int FAST_FUNC volume_id_probe_f2fs (struct volume_id * id)
Definition at line 66 of file f2fs.c.
 {
     struct f2fs_super_block *sb;
     // Go for primary super block (ignore second sb)
     dbg("f2fs: probing at offset 0x%x", F2FS_SB1_OFFSET);
     sb = volume_id_get_buffer(id, F2FS_SB1_OFFSET, sizeof(*sb));
     if (!sb)
         return -1;
     if (sb->magic != cpu_to_le32(F2FS_MAGIC))
         return -1;
     IF_FEATURE_BLKID_TYPE(id->type = "f2fs");
     // For version 1.0 we don't know sb structure and can't set label/uuid
     if (sb->major_ver == cpu_to_le16(1) && sb->minor_ver == cpu_to_le16(0))
         return 0;
     volume_id_set_label_unicode16(id, (uint8_t *)sb->volume_name,
                       LE, MIN(F2FS_LABEL_BYTES, VOLUME_ID_LABEL_SIZE));
     volume_id_set_uuid(id, sb->uuid, UUID_DCE);
     return 0;
 }
References cpu_to_le16, cpu_to_le32, dbg, F2FS_LABEL_BYTES, F2FS_MAGIC, F2FS_SB1_OFFSET, LE, f2fs_super_block::magic, f2fs_super_block::major_ver, MIN, f2fs_super_block::minor_ver, f2fs_super_block::uuid, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_unicode16(), volume_id_set_uuid(), and f2fs_super_block::volume_name.
volume_id_probe_hfs_hfsplus()
int FAST_FUNC volume_id_probe_hfs_hfsplus (struct volume_id * id)
Definition at line 161 of file hfs.c.
 {
     uint64_t off = 0;
     unsigned blocksize;
     unsigned cat_block;
     unsigned ext_block_start;
     unsigned ext_block_count;
     int ext;
     unsigned leaf_node_head;
     unsigned leaf_node_count;
     unsigned leaf_node_size;
     unsigned leaf_block;
     uint64_t leaf_off;
     unsigned alloc_block_size;
     unsigned alloc_first_block;
     unsigned embed_first_block;
     unsigned record_count;
     struct hfsplus_vol_header *hfsplus;
     struct hfsplus_bnode_descriptor *descr;
     struct hfsplus_bheader_record *bnode;
     struct hfsplus_catalog_key *key;
     unsigned label_len;
     struct hfsplus_extent extents[HFSPLUS_EXTENT_COUNT];
     struct hfs_mdb *hfs;
     const uint8_t *buf;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     buf = volume_id_get_buffer(id, off + HFS_SUPERBLOCK_OFFSET, 0x200);
     if (buf == NULL)
         return -1;
     hfs = (struct hfs_mdb *) buf;
     if (hfs->signature[0] != 'B' || hfs->signature[1] != 'D')
         goto checkplus;
     /* it may be just a hfs wrapper for hfs+ */
     if (hfs->embed_sig[0] == 'H' && hfs->embed_sig[1] == '+') {
         alloc_block_size = be32_to_cpu(hfs->al_blk_size);
         dbg("alloc_block_size 0x%x", alloc_block_size);
         alloc_first_block = be16_to_cpu(hfs->al_bl_st);
         dbg("alloc_first_block 0x%x", alloc_first_block);
         embed_first_block = be16_to_cpu(hfs->embed_startblock);
         dbg("embed_first_block 0x%x", embed_first_block);
         off += (alloc_first_block * 512) +
                (embed_first_block * alloc_block_size);
         dbg("hfs wrapped hfs+ found at offset 0x%llx", (unsigned long long) off);
         buf = volume_id_get_buffer(id, off + HFS_SUPERBLOCK_OFFSET, 0x200);
         if (buf == NULL)
             return -1;
         goto checkplus;
     }
     if (hfs->label_len > 0 && hfs->label_len < 28) {
 //      volume_id_set_label_raw(id, hfs->label, hfs->label_len);
         volume_id_set_label_string(id, hfs->label, hfs->label_len) ;
     }
     hfs_set_uuid(id, hfs->finder_info.id);
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "hfs";)
     return 0;
  checkplus:
     hfsplus = (struct hfsplus_vol_header *) buf;
     if (hfs->signature[0] == 'H')
         if (hfs->signature[1] == '+' || hfs->signature[1] == 'X')
             goto hfsplus;
     return -1;
  hfsplus:
     hfs_set_uuid(id, hfsplus->finder_info.id);
     blocksize = be32_to_cpu(hfsplus->blocksize);
     dbg("blocksize %u", blocksize);
     memcpy(extents, hfsplus->cat_file.extents, sizeof(extents));
     cat_block = be32_to_cpu(extents[0].start_block);
     dbg("catalog start block 0x%x", cat_block);
     buf = volume_id_get_buffer(id, off + (cat_block * blocksize), 0x2000);
     if (buf == NULL)
         goto found;
     bnode = (struct hfsplus_bheader_record *)
         &buf[sizeof(struct hfsplus_bnode_descriptor)];
     leaf_node_head = be32_to_cpu(bnode->leaf_head);
     dbg("catalog leaf node 0x%x", leaf_node_head);
     leaf_node_size = be16_to_cpu(bnode->node_size);
     dbg("leaf node size 0x%x", leaf_node_size);
     leaf_node_count = be32_to_cpu(bnode->leaf_count);
     dbg("leaf node count 0x%x", leaf_node_count);
     if (leaf_node_count == 0)
         goto found;
     leaf_block = (leaf_node_head * leaf_node_size) / blocksize;
     /* get physical location */
     for (ext = 0; ext < HFSPLUS_EXTENT_COUNT; ext++) {
         ext_block_start = be32_to_cpu(extents[ext].start_block);
         ext_block_count = be32_to_cpu(extents[ext].block_count);
         dbg("extent start block 0x%x, count 0x%x", ext_block_start, ext_block_count);
         if (ext_block_count == 0)
             goto found;
         /* this is our extent */
         if (leaf_block < ext_block_count)
             break;
         leaf_block -= ext_block_count;
     }
     if (ext == HFSPLUS_EXTENT_COUNT)
         goto found;
     dbg("found block in extent %i", ext);
     leaf_off = (ext_block_start + leaf_block) * blocksize;
     buf = volume_id_get_buffer(id, off + leaf_off, leaf_node_size);
     if (buf == NULL)
         goto found;
     descr = (struct hfsplus_bnode_descriptor *) buf;
     dbg("descriptor type 0x%x", descr->type);
     record_count = be16_to_cpu(descr->num_recs);
     dbg("number of records %u", record_count);
     if (record_count == 0)
         goto found;
     if (descr->type != HFS_NODE_LEAF)
         goto found;
     key = (struct hfsplus_catalog_key *)
         &buf[sizeof(struct hfsplus_bnode_descriptor)];
     dbg("parent id 0x%x", be32_to_cpu(key->parent_id));
     if (key->parent_id != cpu_to_be32(HFSPLUS_POR_CNID))
         goto found;
     label_len = be16_to_cpu(key->unicode_len) * 2;
     dbg("label unicode16 len %i", label_len);
 //  volume_id_set_label_raw(id, key->unicode, label_len);
     volume_id_set_label_unicode16(id, key->unicode, BE, label_len);
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "hfsplus";)
     return 0;
 }
References hfs_mdb::al_bl_st, hfs_mdb::al_blk_size, BE, be16_to_cpu, be32_to_cpu, hfsplus_vol_header::blocksize, buf, hfsplus_vol_header::cat_file, cpu_to_be32, dbg, hfs_mdb::embed_sig, hfs_mdb::embed_startblock, hfsplus_fork::extents, hfs_mdb::finder_info, hfsplus_vol_header::finder_info, found, HFS_NODE_LEAF, hfs_set_uuid(), HFS_SUPERBLOCK_OFFSET, HFSPLUS_EXTENT_COUNT, HFSPLUS_POR_CNID, hfs_finder_info::id, hfs_mdb::label, hfs_mdb::label_len, hfsplus_bheader_record::leaf_count, hfsplus_bheader_record::leaf_head, memcpy, hfsplus_bheader_record::node_size, NULL, hfsplus_bnode_descriptor::num_recs, off, hfsplus_catalog_key::parent_id, hfs_mdb::signature, hfsplus_bnode_descriptor::type, hfsplus_catalog_key::unicode, hfsplus_catalog_key::unicode_len, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_label_unicode16().
volume_id_probe_iso9660()
int FAST_FUNC volume_id_probe_iso9660 (struct volume_id * id)
Definition at line 56 of file iso9660.c.
 {
 #define off ((uint64_t)0)
     uint8_t *buf;
     struct iso_volume_descriptor *is;
     struct high_sierra_volume_descriptor *hs;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     buf = volume_id_get_buffer(id, off + ISO_SUPERBLOCK_OFFSET, 0x200);
     if (buf == NULL)
         return -1;
     is = (struct iso_volume_descriptor *) buf;
     if (memcmp(is->vd_id, "CD001", 5) == 0) {
         int vd_offset;
         int i;
         dbg("read label from PVD");
 //      volume_id_set_label_raw(id, is->volume_id, 32);
         volume_id_set_label_string(id, is->volume_id, 32);
         dbg("looking for SVDs");
         vd_offset = ISO_VD_OFFSET;
         for (i = 0; i < ISO_VD_MAX; i++) {
             uint8_t svd_label[64];
             is = volume_id_get_buffer(id, off + vd_offset, 0x200);
             if (is == NULL || is->vd_type == ISO_VD_END)
                 break;
             if (is->vd_type != ISO_VD_SUPPLEMENTARY)
                 continue;
             dbg("found SVD at offset 0x%llx", (unsigned long long) (off + vd_offset));
             if (memcmp(is->escape_sequences, "%/@", 3) == 0
              || memcmp(is->escape_sequences, "%/C", 3) == 0
              || memcmp(is->escape_sequences, "%/E", 3) == 0
             ) {
                 dbg("Joliet extension found");
                 volume_id_set_unicode16((char *)svd_label, sizeof(svd_label), is->volume_id, BE, 32);
                 if (memcmp(id->label, svd_label, 16) == 0) {
                     dbg("SVD label is identical, use the possibly longer PVD one");
                     break;
                 }
 //              volume_id_set_label_raw(id, is->volume_id, 32);
                 volume_id_set_label_string(id, svd_label, 32);
 //              strcpy(id->type_version, "Joliet Extension");
                 goto found;
             }
             vd_offset += ISO_SECTOR_SIZE;
         }
         goto found;
     }
     hs = (struct high_sierra_volume_descriptor *) buf;
     if (memcmp(hs->id, "CDROM", 5) == 0) {
 //      strcpy(id->type_version, "High Sierra");
         goto found;
     }
     return -1;
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "iso9660";)
     return 0;
 }
References BE, buf, dbg, iso_volume_descriptor::escape_sequences, found, i, high_sierra_volume_descriptor::id, ISO_SECTOR_SIZE, ISO_SUPERBLOCK_OFFSET, ISO_VD_END, ISO_VD_MAX, ISO_VD_OFFSET, ISO_VD_SUPPLEMENTARY, volume_id::label, memcmp(), NULL, off, iso_volume_descriptor::vd_id, iso_volume_descriptor::vd_type, iso_volume_descriptor::volume_id, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_unicode16().
volume_id_probe_jfs()
int FAST_FUNC volume_id_probe_jfs (struct volume_id * id)
Definition at line 44 of file jfs.c.
 {
 #define off ((uint64_t)0)
     struct jfs_super_block *js;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     js = volume_id_get_buffer(id, off + JFS_SUPERBLOCK_OFFSET, 0x200);
     if (js == NULL)
         return -1;
     if (memcmp(js->magic, "JFS1", 4) != 0)
         return -1;
 //  volume_id_set_label_raw(id, js->label, 16);
     volume_id_set_label_string(id, js->label, 16);
     volume_id_set_uuid(id, js->uuid, UUID_DCE);
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "jfs";)
     return 0;
 }
References dbg, JFS_SUPERBLOCK_OFFSET, js, memcmp(), NULL, off, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_probe_lfs()
int FAST_FUNC volume_id_probe_lfs (struct volume_id * id)
Definition at line 45 of file lfs.c.
 {
     struct lfs_super_block *sb;
     // Go for primary super block (ignore second sb)
     dbg("lfs: probing at offset 0x%x", LFS_SB1_OFFSET);
     sb = volume_id_get_buffer(id, LFS_SB1_OFFSET, sizeof(*sb));
     if (!sb)
         return -1;
     if (memcmp(sb->magic, LFS_MAGIC_NAME, LFS_MAGIC_LEN) != 0)
         return -1;
     IF_FEATURE_BLKID_TYPE(id->type = LFS_MAGIC_NAME);
     return 0;
 }
References dbg, LFS_MAGIC_LEN, LFS_MAGIC_NAME, LFS_SB1_OFFSET, lfs_super_block::magic, memcmp(), and volume_id_get_buffer().
volume_id_probe_linux_raid()
int FAST_FUNC volume_id_probe_linux_raid (struct volume_id * id, uint64_t size)
Definition at line 51 of file linux_raid.c.
 {
     typedef uint32_t aliased_uint32_t FIX_ALIASING;
 #define off ((uint64_t)0)
     uint64_t sboff;
     uint8_t uuid[16];
     struct mdp_super_block *mdp;
     dbg("probing at offset 0x%llx, size 0x%llx",
         (unsigned long long) off, (unsigned long long) size);
     if (size < 0x10000)
         return -1;
     sboff = (size & ~(MD_RESERVED_BYTES - 1)) - MD_RESERVED_BYTES;
     mdp = volume_id_get_buffer(id, off + sboff, 0x800);
     if (mdp == NULL)
         return -1;
     if (mdp->md_magic != cpu_to_le32(MD_MAGIC))
         return -1;
     *(aliased_uint32_t*)uuid = mdp->set_uuid0;
     memcpy(&uuid[4], &mdp->set_uuid1, 12);
     volume_id_set_uuid(id, uuid, UUID_DCE);
 //  snprintf(id->type_version, sizeof(id->type_version)-1, "%u.%u.%u",
 //      le32_to_cpu(mdp->major_version),
 //      le32_to_cpu(mdp->minor_version),
 //      le32_to_cpu(mdp->patch_version));
     dbg("found raid signature");
 //  volume_id_set_usage(id, VOLUME_ID_RAID);
     IF_FEATURE_BLKID_TYPE(id->type = "linux_raid_member";)
     return 0;
 }
References cpu_to_le32, dbg, FIX_ALIASING, mdp_super_block::md_magic, MD_MAGIC, MD_RESERVED_BYTES, memcpy, NULL, off, mdp_super_block::set_uuid0, mdp_super_block::set_uuid1, size, UUID_DCE, volume_id_get_buffer(), and volume_id_set_uuid().
volume_id_probe_linux_swap()
int FAST_FUNC volume_id_probe_linux_swap (struct volume_id * id)
Definition at line 40 of file linux_swap.c.
 {
 #define off ((uint64_t)0)
     struct swap_header_v1_2 *sw;
     const uint8_t *buf;
     unsigned page;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     /* the swap signature is at the end of the PAGE_SIZE */
     for (page = 0x1000; page <= LARGEST_PAGESIZE; page <<= 1) {
             buf = volume_id_get_buffer(id, off + page-10, 10);
             if (buf == NULL)
                 return -1;
             if (memcmp(buf, "SWAP-SPACE", 10) == 0) {
 //              id->type_version[0] = '1';
 //              id->type_version[1] = '\0';
                 goto found;
             }
             if (memcmp(buf, "SWAPSPACE2", 10) == 0
              || memcmp(buf, "S1SUSPEND", 9) == 0
              || memcmp(buf, "S2SUSPEND", 9) == 0
              || memcmp(buf, "ULSUSPEND", 9) == 0
             ) {
                 sw = volume_id_get_buffer(id, off, sizeof(struct swap_header_v1_2));
                 if (sw == NULL)
                     return -1;
 //              id->type_version[0] = '2';
 //              id->type_version[1] = '\0';
 //              volume_id_set_label_raw(id, sw->volume_name, 16);
                 volume_id_set_label_string(id, sw->volume_name, 16);
                 volume_id_set_uuid(id, sw->uuid, UUID_DCE);
                 goto found;
             }
     }
     return -1;
 found:
 //  volume_id_set_usage(id, VOLUME_ID_OTHER);
     IF_FEATURE_BLKID_TYPE(id->type = "swap";)
     return 0;
 }
References buf, dbg, found, LARGEST_PAGESIZE, memcmp(), NULL, off, page, swap_header_v1_2::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), volume_id_set_uuid(), and swap_header_v1_2::volume_name.
volume_id_probe_luks()
int FAST_FUNC volume_id_probe_luks (struct volume_id * id)
Definition at line 89 of file luks.c.
 {
 #define off ((uint64_t)0)
     struct luks_phdr *header;
     header = volume_id_get_buffer(id, off, sizeof(*header));
     if (header == NULL)
         return -1;
     if (memcmp(header->magic, LUKS_MAGIC, LUKS_MAGIC_L))
         return -1;
 //  volume_id_set_usage(id, VOLUME_ID_CRYPTO);
     volume_id_set_uuid(id, header->uuid, UUID_DCE_STRING);
     IF_FEATURE_BLKID_TYPE(id->type = "crypto_LUKS";)
     return 0;
 }
References LUKS_MAGIC_L, memcmp(), NULL, off, UUID_DCE_STRING, volume_id_get_buffer(), and volume_id_set_uuid().
volume_id_probe_minix()
int FAST_FUNC volume_id_probe_minix (struct volume_id * id)
Definition at line 61 of file minix.c.
 {
 #define off ((uint64_t)0)
     struct minix_super_block *ms;
     struct minix3_super_block *ms3;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     ms = volume_id_get_buffer(id, off + MINIX_SUPERBLOCK_OFFSET, 0x200);
     if (ms == NULL)
         return -1;
     if (ms->s_magic == cpu_to_le16(0x137F)) /* minix V1 fs, 14 char names */
         goto found;
     if (ms->s_magic == cpu_to_le16(0x138F)) /* minix V1 fs, 30 char names */
         goto found;
     if (ms->s_magic == cpu_to_le16(0x2468)) /* minix V2 fs, 14 char names */
         goto found;
     if (ms->s_magic == cpu_to_le16(0x2478)) /* minix V2 fs, 30 char names */
         goto found;
     ms3 = (void*)ms;
     if (ms3->s_magic == cpu_to_le16(0x4d5a)) /* minix V3 fs, 60 char names */
         goto found;
     return -1;
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "minix";)
     return 0;
 }
References cpu_to_le16, dbg, found, MINIX_SUPERBLOCK_OFFSET, NULL, off, minix_super_block::s_magic, minix3_super_block::s_magic, and volume_id_get_buffer().
volume_id_probe_nilfs()
int FAST_FUNC volume_id_probe_nilfs (struct volume_id * id)
Definition at line 87 of file nilfs.c.
 {
     struct nilfs2_super_block *sb;
     // Primary super block
     dbg("nilfs: probing at offset 0x%x", NILFS_SB1_OFFSET);
     sb = volume_id_get_buffer(id, NILFS_SB1_OFFSET, sizeof(*sb));
     if (sb == NULL)
         return -1;
     if (sb->s_magic != NILFS_MAGIC)
         return -1;
     // The secondary superblock is not always used, so ignore it for now.
     // When used it is at 4K from the end of the partition (sb->s_dev_size - NILFS_SB2_OFFSET).
     volume_id_set_label_string(id, sb->s_volume_name, NILFS_LABEL_SIZE < VOLUME_ID_LABEL_SIZE ?
                 NILFS_LABEL_SIZE : VOLUME_ID_LABEL_SIZE);
     volume_id_set_uuid(id, sb->s_uuid, UUID_DCE);
     if (sb->s_rev_level == 2)
         IF_FEATURE_BLKID_TYPE(id->type = "nilfs2");
     return 0;
 }
References dbg, NILFS_LABEL_SIZE, NILFS_MAGIC, NILFS_SB1_OFFSET, NULL, nilfs2_super_block::s_magic, nilfs2_super_block::s_rev_level, nilfs2_super_block::s_uuid, nilfs2_super_block::s_volume_name, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_probe_ntfs()
int FAST_FUNC volume_id_probe_ntfs (struct volume_id * id)
Definition at line 93 of file ntfs.c.
 {
 #define off ((uint64_t)0)
     unsigned sector_size;
     unsigned cluster_size;
     uint64_t mft_cluster;
     uint64_t mft_off;
     unsigned mft_record_size;
     unsigned attr_type;
     unsigned attr_off;
     unsigned attr_len;
     unsigned val_off;
     unsigned val_len;
     struct master_file_table_record *mftr;
     struct ntfs_super_block *ns;
     const uint8_t *buf;
     const uint8_t *val;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     ns = volume_id_get_buffer(id, off, 0x200);
     if (ns == NULL)
         return -1;
     if (memcmp(ns->oem_id, "NTFS", 4) != 0)
         return -1;
     volume_id_set_uuid(id, ns->volume_serial, UUID_NTFS);
     sector_size = le16_to_cpu(ns->bytes_per_sector);
     cluster_size = ns->sectors_per_cluster * sector_size;
     mft_cluster = le64_to_cpu(ns->mft_cluster_location);
     mft_off = mft_cluster * cluster_size;
     if (ns->cluster_per_mft_record < 0)
         /* size = -log2(mft_record_size); normally 1024 Bytes */
         mft_record_size = 1 << -ns->cluster_per_mft_record;
     else
         mft_record_size = ns->cluster_per_mft_record * cluster_size;
     dbg("sectorsize  0x%x", sector_size);
     dbg("clustersize 0x%x", cluster_size);
     dbg("mftcluster  %llu", (unsigned long long) mft_cluster);
     dbg("mftoffset  0x%llx", (unsigned long long) mft_off);
     dbg("cluster per mft_record  %i", ns->cluster_per_mft_record);
     dbg("mft record size  %i", mft_record_size);
     buf = volume_id_get_buffer(id, off + mft_off + (MFT_RECORD_VOLUME * mft_record_size),
             mft_record_size);
     if (buf == NULL)
         goto found;
     mftr = (struct master_file_table_record*) buf;
     dbg("mftr->magic '%c%c%c%c'", mftr->magic[0], mftr->magic[1], mftr->magic[2], mftr->magic[3]);
     if (memcmp(mftr->magic, "FILE", 4) != 0)
         goto found;
     attr_off = le16_to_cpu(mftr->attrs_offset);
     dbg("file $Volume's attributes are at offset %i", attr_off);
     while (1) {
         struct file_attribute *attr;
         attr = (struct file_attribute*) &buf[attr_off];
         attr_type = le32_to_cpu(attr->type);
         attr_len = le32_to_cpu(attr->len);
         val_off = le16_to_cpu(attr->value_offset);
         val_len = le32_to_cpu(attr->value_len);
         attr_off += attr_len;
         if (attr_len == 0)
             break;
         if (attr_off >= mft_record_size)
             break;
         if (attr_type == MFT_RECORD_ATTR_END)
             break;
         dbg("found attribute type 0x%x, len %i, at offset %i",
             attr_type, attr_len, attr_off);
 //      if (attr_type == MFT_RECORD_ATTR_VOLUME_INFO) {
 //          struct volume_info *info;
 //          dbg("found info, len %i", val_len);
 //          info = (struct volume_info*) (((uint8_t *) attr) + val_off);
 //          snprintf(id->type_version, sizeof(id->type_version)-1,
 //               "%u.%u", info->major_ver, info->minor_ver);
 //      }
         if (attr_type == MFT_RECORD_ATTR_VOLUME_NAME) {
             dbg("found label, len %i", val_len);
             if (val_len > VOLUME_ID_LABEL_SIZE)
                 val_len = VOLUME_ID_LABEL_SIZE;
             val = ((uint8_t *) attr) + val_off;
 //          volume_id_set_label_raw(id, val, val_len);
             volume_id_set_label_unicode16(id, val, LE, val_len);
         }
     }
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "ntfs";)
     return 0;
 }
References master_file_table_record::attrs_offset, buf, ntfs_super_block::bytes_per_sector, ntfs_super_block::cluster_per_mft_record, dbg, found, LE, le16_to_cpu, le32_to_cpu, le64_to_cpu, file_attribute::len, master_file_table_record::magic, memcmp(), ntfs_super_block::mft_cluster_location, MFT_RECORD_ATTR_END, MFT_RECORD_ATTR_VOLUME_NAME, MFT_RECORD_VOLUME, NULL, ntfs_super_block::oem_id, off, sector_size, ntfs_super_block::sectors_per_cluster, file_attribute::type, UUID_NTFS, val, file_attribute::value_len, file_attribute::value_offset, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_unicode16(), volume_id_set_uuid(), and ntfs_super_block::volume_serial.
volume_id_probe_ocfs2()
int FAST_FUNC volume_id_probe_ocfs2 (struct volume_id * id)
Definition at line 89 of file ocfs2.c.
 {
 #define off ((uint64_t)0)
     struct ocfs2_super_block *os;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     os = volume_id_get_buffer(id, off + OCFS2_SUPERBLOCK_OFFSET, 0x200);
     if (os == NULL)
         return -1;
     if (memcmp(os->i_signature, "OCFSV2", 6) != 0) {
         return -1;
     }
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
 //  volume_id_set_label_raw(id, os->s_label, OCFS2_MAX_VOL_LABEL_LEN < VOLUME_ID_LABEL_SIZE ?
 //                  OCFS2_MAX_VOL_LABEL_LEN : VOLUME_ID_LABEL_SIZE);
     volume_id_set_label_string(id, os->s_label, OCFS2_MAX_VOL_LABEL_LEN < VOLUME_ID_LABEL_SIZE ?
                     OCFS2_MAX_VOL_LABEL_LEN : VOLUME_ID_LABEL_SIZE);
     volume_id_set_uuid(id, os->s_uuid, UUID_DCE);
     IF_FEATURE_BLKID_TYPE(id->type = "ocfs2";)
     return 0;
 }
References dbg, ocfs2_super_block::i_signature, memcmp(), NULL, OCFS2_MAX_VOL_LABEL_LEN, OCFS2_SUPERBLOCK_OFFSET, off, ocfs2_super_block::s_label, ocfs2_super_block::s_uuid, UUID_DCE, volume_id_get_buffer(), VOLUME_ID_LABEL_SIZE, volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_probe_reiserfs()
int FAST_FUNC volume_id_probe_reiserfs (struct volume_id * id)
Definition at line 57 of file reiserfs.c.
 {
 #define off ((uint64_t)0)
     struct reiserfs_super_block *rs;
     struct reiser4_super_block *rs4;
     dbg("reiserfs: probing at offset 0x%llx", (unsigned long long) off);
     rs = volume_id_get_buffer(id, off + REISERFS_SUPERBLOCK_OFFSET, 0x200);
     if (rs == NULL)
         return -1;
     if (memcmp(rs->magic, "ReIsErFs", 8) == 0) {
         dbg("reiserfs: ReIsErFs, no label");
 //      strcpy(id->type_version, "3.5");
         goto found;
     }
     if (memcmp(rs->magic, "ReIsEr2Fs", 9) == 0) {
         dbg("reiserfs: ReIsEr2Fs");
 //      strcpy(id->type_version, "3.6");
         goto found_label;
     }
     if (memcmp(rs->magic, "ReIsEr3Fs", 9) == 0) {
         dbg("reiserfs: ReIsEr3Fs");
 //      strcpy(id->type_version, "JR");
         goto found_label;
     }
     rs4 = (struct reiser4_super_block *) rs;
     if (memcmp(rs4->magic, "ReIsEr4", 7) == 0) {
 //      strcpy(id->type_version, "4");
 //      volume_id_set_label_raw(id, rs4->label, 16);
         volume_id_set_label_string(id, rs4->label, 16);
         volume_id_set_uuid(id, rs4->uuid, UUID_DCE);
         dbg("reiserfs: ReIsEr4, label '%s' uuid '%s'", id->label, id->uuid);
         goto found;
     }
     rs = volume_id_get_buffer(id, off + REISERFS1_SUPERBLOCK_OFFSET, 0x200);
     if (rs == NULL)
         return -1;
     if (memcmp(rs->magic, "ReIsErFs", 8) == 0) {
         dbg("reiserfs: ReIsErFs, no label");
 //      strcpy(id->type_version, "3.5");
         goto found;
     }
     dbg("reiserfs: no signature found");
     return -1;
  found_label:
 //  volume_id_set_label_raw(id, rs->label, 16);
     volume_id_set_label_string(id, rs->label, 16);
     volume_id_set_uuid(id, rs->uuid, UUID_DCE);
     dbg("reiserfs: label '%s' uuid '%s'", id->label, id->uuid);
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "reiserfs";)
     return 0;
 }
References dbg, found, reiserfs_super_block::label, reiser4_super_block::label, volume_id::label, reiserfs_super_block::magic, reiser4_super_block::magic, memcmp(), NULL, off, REISERFS1_SUPERBLOCK_OFFSET, REISERFS_SUPERBLOCK_OFFSET, reiserfs_super_block::uuid, reiser4_super_block::uuid, volume_id::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_probe_romfs()
int FAST_FUNC volume_id_probe_romfs (struct volume_id * id)
Definition at line 36 of file romfs.c.
 {
 #define off ((uint64_t)0)
     struct romfs_super *rfs;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     rfs = volume_id_get_buffer(id, off, 0x200);
     if (rfs == NULL)
         return -1;
     if (memcmp(rfs->magic, "-rom1fs-", 4) == 0) {
         size_t len = strlen((char *)rfs->name);
         if (len) {
 //          volume_id_set_label_raw(id, rfs->name, len);
             volume_id_set_label_string(id, rfs->name, len);
         }
 //      volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
         IF_FEATURE_BLKID_TYPE(id->type = "romfs";)
         return 0;
     }
     return -1;
 }
References dbg, len, romfs_super::magic, memcmp(), romfs_super::name, NULL, off, strlen, volume_id_get_buffer(), and volume_id_set_label_string().
volume_id_probe_squashfs()
int FAST_FUNC volume_id_probe_squashfs (struct volume_id * id)
Definition at line 31 of file squashfs.c.
 {
 #define off ((uint64_t)0)
     struct squashfs_superblock *sb;
     dbg("SquashFS: probing at offset 0x%llx", (unsigned long long) off);
     sb = volume_id_get_buffer(id, off, 0x200);
     if (!sb)
         return -1;
     // Old SquashFS (pre 4.0) can be both big and little endian, so test for both.
     // Likewise, it is commonly used in firwmare with some non-standard signatures.
 #define pack(a,b,c,d) ( (uint32_t)((a * 256 + b) * 256 + c) * 256 + d )
 #define SIG1 pack('s','q','s','h')
 #define SIG2 pack('h','s','q','s')
 #define SIG3 pack('s','h','s','q')
 #define SIG4 pack('q','s','h','s')
     if (sb->magic == SIG1
      || sb->magic == SIG2
      || sb->magic == SIG3
      || sb->magic == SIG4
     ) {
         IF_FEATURE_BLKID_TYPE(id->type = "squashfs";)
         return 0;
     }
     return -1;
 }
References dbg, squashfs_superblock::magic, off, SIG1, SIG2, SIG3, SIG4, and volume_id_get_buffer().
volume_id_probe_sysv()
int FAST_FUNC volume_id_probe_sysv (struct volume_id * id)
Definition at line 91 of file sysv.c.
 {
 #define off ((uint64_t)0)
     struct sysv_super *vs;
     struct xenix_super *xs;
     unsigned boff;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     for (boff = 0x200; boff <= SYSV_MAX_BLOCKSIZE; boff <<= 1) {
         vs = volume_id_get_buffer(id, off + (boff * SYSV_SUPERBLOCK_BLOCK), 0x200);
         if (vs == NULL)
             return -1;
         if (vs->s_magic == cpu_to_le32(SYSV_MAGIC) || vs->s_magic == cpu_to_be32(SYSV_MAGIC)) {
 //          volume_id_set_label_raw(id, vs->s_fname, 6);
             volume_id_set_label_string(id, vs->s_fname, 6);
             IF_FEATURE_BLKID_TYPE(id->type = "sysv");
             goto found;
         }
     }
     for (boff = 0x200; boff <= SYSV_MAX_BLOCKSIZE; boff <<= 1) {
         xs = volume_id_get_buffer(id, off + (boff + XENIX_SUPERBLOCK_BLOCK), 0x200);
         if (xs == NULL)
             return -1;
         if (xs->s_magic == cpu_to_le32(XENIX_MAGIC) || xs->s_magic == cpu_to_be32(XENIX_MAGIC)) {
 //          volume_id_set_label_raw(id, xs->s_fname, 6);
             volume_id_set_label_string(id, xs->s_fname, 6);
             IF_FEATURE_BLKID_TYPE(id->type = "xenix";)
             goto found;
         }
     }
     return -1;
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     return 0;
 }
References cpu_to_be32, cpu_to_le32, dbg, found, NULL, off, sysv_super::s_fname, xenix_super::s_fname, sysv_super::s_magic, xenix_super::s_magic, SYSV_MAGIC, SYSV_MAX_BLOCKSIZE, SYSV_SUPERBLOCK_BLOCK, volume_id_get_buffer(), volume_id_set_label_string(), XENIX_MAGIC, and XENIX_SUPERBLOCK_BLOCK.
volume_id_probe_ubifs()
int FAST_FUNC volume_id_probe_ubifs (struct volume_id * id)
Definition at line 105 of file ubifs.c.
 {
 #define off ((uint64_t)0)
     struct ubifs_sb_node *sb;
     dbg("UBIFS: probing at offset 0x%llx", (unsigned long long) off);
     sb = volume_id_get_buffer(id, off, sizeof(struct ubifs_sb_node));
     if (!sb)
         return -1;
     if (le32_to_cpu(sb->ch.magic) != UBIFS_NODE_MAGIC)
         return -1;
     IF_FEATURE_BLKID_TYPE(id->type = "ubifs";)
     volume_id_set_uuid(id, sb->uuid, UUID_DCE);
     return 0;
 }
References ubifs_sb_node::ch, dbg, le32_to_cpu, ubifs_ch::magic, off, UBIFS_NODE_MAGIC, ubifs_sb_node::uuid, UUID_DCE, volume_id_get_buffer(), and volume_id_set_uuid().
volume_id_probe_udf()
int FAST_FUNC volume_id_probe_udf (struct volume_id * id)
Definition at line 64 of file udf.c.
 {
 #define off ((uint64_t)0)
     struct volume_descriptor *vd;
     struct volume_structure_descriptor *vsd;
     unsigned bs;
     unsigned b;
     unsigned type;
     unsigned count;
     unsigned loc;
     unsigned clen;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     vsd = volume_id_get_buffer(id, off + UDF_VSD_OFFSET, 0x200);
     if (vsd == NULL)
         return -1;
     if (memcmp(vsd->id, "NSR02", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "NSR03", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "BEA01", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "BOOT2", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "CD001", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "CDW02", 5) == 0)
         goto blocksize;
     if (memcmp(vsd->id, "TEA03", 5) == 0)
         goto blocksize;
     return -1;
 blocksize:
     /* search the next VSD to get the logical block size of the volume */
     for (bs = 0x800; bs < 0x8000; bs += 0x800) {
         vsd = volume_id_get_buffer(id, off + UDF_VSD_OFFSET + bs, 0x800);
         if (vsd == NULL)
             return -1;
         dbg("test for blocksize: 0x%x", bs);
         if (vsd->id[0] != '\0')
             goto nsr;
     }
     return -1;
 nsr:
     /* search the list of VSDs for a NSR descriptor */
     for (b = 0; b < 64; b++) {
         vsd = volume_id_get_buffer(id, off + UDF_VSD_OFFSET + (b * bs), 0x800);
         if (vsd == NULL)
             return -1;
         dbg("vsd: %c%c%c%c%c",
             vsd->id[0], vsd->id[1], vsd->id[2], vsd->id[3], vsd->id[4]);
         if (vsd->id[0] == '\0')
             return -1;
         if (memcmp(vsd->id, "NSR02", 5) == 0)
             goto anchor;
         if (memcmp(vsd->id, "NSR03", 5) == 0)
             goto anchor;
     }
     return -1;
 anchor:
     /* read anchor volume descriptor */
     vd = volume_id_get_buffer(id, off + (256 * bs), 0x200);
     if (vd == NULL)
         return -1;
     type = le16_to_cpu(vd->tag.id);
     if (type != 2) /* TAG_ID_AVDP */
         goto found;
     /* get descriptor list address and block count */
     count = le32_to_cpu(vd->type.anchor.length) / bs;
     loc = le32_to_cpu(vd->type.anchor.location);
     dbg("0x%x descriptors starting at logical secor 0x%x", count, loc);
     /* pick the primary descriptor from the list */
     for (b = 0; b < count; b++) {
         vd = volume_id_get_buffer(id, off + ((loc + b) * bs), 0x200);
         if (vd == NULL)
             return -1;
         type = le16_to_cpu(vd->tag.id);
         dbg("descriptor type %i", type);
         /* check validity */
         if (type == 0)
             goto found;
         if (le32_to_cpu(vd->tag.location) != loc + b)
             goto found;
         if (type == 1) /* TAG_ID_PVD */
             goto pvd;
     }
     goto found;
  pvd:
 //  volume_id_set_label_raw(id, &(vd->type.primary.ident.clen), 32);
     clen = vd->type.primary.ident.clen;
     dbg("label string charsize=%i bit", clen);
     if (clen == 8)
         volume_id_set_label_string(id, vd->type.primary.ident.c, 31);
     else if (clen == 16)
         volume_id_set_label_unicode16(id, vd->type.primary.ident.c, BE, 31);
  found:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "udf";)
     return 0;
 }
References BE, count, dbg, found, volume_descriptor::descriptor_tag::id, volume_structure_descriptor::id, le16_to_cpu, le32_to_cpu, volume_descriptor::descriptor_tag::location, memcmp(), NULL, off, volume_descriptor::tag, type, volume_descriptor::type, UDF_VSD_OFFSET, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_label_unicode16().
volume_id_probe_vfat()
int FAST_FUNC volume_id_probe_vfat (struct volume_id * id)
Definition at line 128 of file fat.c.
 {
 #define fat_partition_off ((uint64_t)0)
     struct vfat_super_block *vs;
     struct vfat_dir_entry *dir;
     uint16_t sector_size_bytes;
     uint16_t dir_entries;
     uint32_t sect_count;
     uint16_t reserved_sct;
     uint32_t fat_size_sct;
     uint32_t root_cluster;
     uint32_t dir_size_sct;
     uint32_t cluster_count;
     uint64_t root_start_off;
     uint32_t start_data_sct;
     uint8_t *buf;
     uint32_t buf_size;
     uint8_t *label = NULL;
     uint32_t next_cluster;
     int maxloop;
     dbg("probing at offset 0x%llx", (unsigned long long) fat_partition_off);
     vs = volume_id_get_buffer(id, fat_partition_off, 0x200);
     if (vs == NULL)
         return -1;
     /* believe only that's fat, don't trust the version
      * the cluster_count will tell us
      */
     if (memcmp(vs->sysid, "NTFS", 4) == 0)
         return -1;
     if (memcmp(vs->type.fat32.magic, "MSWIN", 5) == 0)
         goto valid;
     if (memcmp(vs->type.fat32.magic, "FAT32   ", 8) == 0)
         goto valid;
     if (memcmp(vs->type.fat.magic, "FAT16   ", 8) == 0)
         goto valid;
     if (memcmp(vs->type.fat.magic, "MSDOS", 5) == 0)
         goto valid;
     if (memcmp(vs->type.fat.magic, "FAT12   ", 8) == 0)
         goto valid;
     /*
      * There are old floppies out there without a magic, so we check
      * for well known values and guess if it's a fat volume
      */
     /* boot jump address check */
     if ((vs->boot_jump[0] != 0xeb || vs->boot_jump[2] != 0x90)
      && vs->boot_jump[0] != 0xe9
     ) {
         return -1;
     }
     /* heads check */
     if (vs->heads == 0)
         return -1;
     /* cluster size check */
     if (vs->sectors_per_cluster == 0
      || (vs->sectors_per_cluster & (vs->sectors_per_cluster-1))
     ) {
         return -1;
     }
     /* media check */
     if (vs->media < 0xf8 && vs->media != 0xf0)
         return -1;
     /* fat count*/
     if (vs->fats != 2)
         return -1;
  valid:
     /* sector size check */
     sector_size_bytes = le16_to_cpu(vs->sector_size_bytes);
     if (sector_size_bytes != 0x200 && sector_size_bytes != 0x400
      && sector_size_bytes != 0x800 && sector_size_bytes != 0x1000
     ) {
         return -1;
     }
     dbg("sector_size_bytes 0x%x", sector_size_bytes);
     dbg("sectors_per_cluster 0x%x", vs->sectors_per_cluster);
     reserved_sct = le16_to_cpu(vs->reserved_sct);
     dbg("reserved_sct 0x%x", reserved_sct);
     sect_count = le16_to_cpu(vs->sectors);
     if (sect_count == 0)
         sect_count = le32_to_cpu(vs->total_sect);
     dbg("sect_count 0x%x", sect_count);
     fat_size_sct = le16_to_cpu(vs->fat_length);
     if (fat_size_sct == 0)
         fat_size_sct = le32_to_cpu(vs->type.fat32.fat32_length);
     fat_size_sct *= vs->fats;
     dbg("fat_size_sct 0x%x", fat_size_sct);
     dir_entries = le16_to_cpu(vs->dir_entries);
     dir_size_sct = ((dir_entries * sizeof(struct vfat_dir_entry)) +
             (sector_size_bytes-1)) / sector_size_bytes;
     dbg("dir_size_sct 0x%x", dir_size_sct);
     cluster_count = sect_count - (reserved_sct + fat_size_sct + dir_size_sct);
     cluster_count /= vs->sectors_per_cluster;
     dbg("cluster_count 0x%x", cluster_count);
 //  if (cluster_count < FAT12_MAX) {
 //      strcpy(id->type_version, "FAT12");
 //  } else if (cluster_count < FAT16_MAX) {
 //      strcpy(id->type_version, "FAT16");
 //  } else {
 //      strcpy(id->type_version, "FAT32");
 //      goto fat32;
 //  }
     if (cluster_count > FAT16_MAX)
         goto fat32;
     /* the label may be an attribute in the root directory */
     root_start_off = (reserved_sct + fat_size_sct) * sector_size_bytes;
     dbg("root dir start 0x%llx", (unsigned long long) root_start_off);
     dbg("expected entries 0x%x", dir_entries);
     buf_size = dir_entries * sizeof(struct vfat_dir_entry);
     buf = volume_id_get_buffer(id, fat_partition_off + root_start_off, buf_size);
     if (buf == NULL)
         goto ret;
     label = get_attr_volume_id((struct vfat_dir_entry*) buf, dir_entries);
     vs = volume_id_get_buffer(id, fat_partition_off, 0x200);
     if (vs == NULL)
         return -1;
     if (label != NULL && memcmp(label, "NO NAME    ", 11) != 0) {
 //      volume_id_set_label_raw(id, label, 11);
         volume_id_set_label_string(id, label, 11);
     } else if (memcmp(vs->type.fat.label, "NO NAME    ", 11) != 0) {
 //      volume_id_set_label_raw(id, vs->type.fat.label, 11);
         volume_id_set_label_string(id, vs->type.fat.label, 11);
     }
     volume_id_set_uuid(id, vs->type.fat.serno, UUID_DOS);
     goto ret;
  fat32:
     /* FAT32 root dir is a cluster chain like any other directory */
     buf_size = vs->sectors_per_cluster * sector_size_bytes;
     root_cluster = le32_to_cpu(vs->type.fat32.root_cluster);
     start_data_sct = reserved_sct + fat_size_sct;
     next_cluster = root_cluster;
     maxloop = 100;
     while (--maxloop) {
         uint64_t next_off_sct;
         uint64_t next_off;
         uint64_t fat_entry_off;
         int count;
         dbg("next_cluster 0x%x", (unsigned)next_cluster);
         next_off_sct = (uint64_t)(next_cluster - 2) * vs->sectors_per_cluster;
         next_off = (start_data_sct + next_off_sct) * sector_size_bytes;
         dbg("cluster offset 0x%llx", (unsigned long long) next_off);
         /* get cluster */
         buf = volume_id_get_buffer(id, fat_partition_off + next_off, buf_size);
         if (buf == NULL)
             goto ret;
         dir = (struct vfat_dir_entry*) buf;
         count = buf_size / sizeof(struct vfat_dir_entry);
         dbg("expected entries 0x%x", count);
         label = get_attr_volume_id(dir, count);
         if (label)
             break;
         /* get FAT entry */
         fat_entry_off = (reserved_sct * sector_size_bytes) + (next_cluster * sizeof(uint32_t));
         dbg("fat_entry_off 0x%llx", (unsigned long long)fat_entry_off);
         buf = volume_id_get_buffer(id, fat_partition_off + fat_entry_off, buf_size);
         if (buf == NULL)
             goto ret;
         /* set next cluster */
         next_cluster = le32_to_cpu(*(uint32_t*)buf) & 0x0fffffff;
         if (next_cluster < 2 || next_cluster > FAT32_MAX)
             break;
     }
     if (maxloop == 0)
         dbg("reached maximum follow count of root cluster chain, give up");
     vs = volume_id_get_buffer(id, fat_partition_off, 0x200);
     if (vs == NULL)
         return -1;
     if (label != NULL && memcmp(label, "NO NAME    ", 11) != 0) {
 //      volume_id_set_label_raw(id, label, 11);
         volume_id_set_label_string(id, label, 11);
     } else if (memcmp(vs->type.fat32.label, "NO NAME    ", 11) != 0) {
 //      volume_id_set_label_raw(id, vs->type.fat32.label, 11);
         volume_id_set_label_string(id, vs->type.fat32.label, 11);
     }
     volume_id_set_uuid(id, vs->type.fat32.serno, UUID_DOS);
  ret:
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "vfat";)
     return 0;
 }
References vfat_super_block::boot_jump, buf, count, dbg, dir, vfat_super_block::dir_entries, FAT16_MAX, FAT32_MAX, vfat_super_block::fat_length, fat_partition_off, vfat_super_block::fats, get_attr_volume_id(), vfat_super_block::heads, label, le16_to_cpu, le32_to_cpu, vfat_super_block::media, memcmp(), NULL, vfat_super_block::reserved_sct, vfat_super_block::sector_size_bytes, vfat_super_block::sectors, vfat_super_block::sectors_per_cluster, vfat_super_block::sysid, vfat_super_block::total_sect, vfat_super_block::type, UUID_DOS, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_probe_xfs()
int FAST_FUNC volume_id_probe_xfs (struct volume_id * id)
Definition at line 44 of file xfs.c.
 {
 #define off ((uint64_t)0)
     struct xfs_super_block *xs;
     dbg("probing at offset 0x%llx", (unsigned long long) off);
     xs = volume_id_get_buffer(id, off, 0x200);
     if (xs == NULL)
         return -1;
     if (memcmp(xs->magic, "XFSB", 4) != 0)
         return -1;
 //  volume_id_set_label_raw(id, xs->fname, 12);
     volume_id_set_label_string(id, xs->fname, 12);
     volume_id_set_uuid(id, xs->uuid, UUID_DCE);
 //  volume_id_set_usage(id, VOLUME_ID_FILESYSTEM);
     IF_FEATURE_BLKID_TYPE(id->type = "xfs";)
     return 0;
 }
References dbg, xfs_super_block::fname, xfs_super_block::magic, memcmp(), NULL, off, xfs_super_block::uuid, UUID_DCE, volume_id_get_buffer(), volume_id_set_label_string(), and volume_id_set_uuid().
volume_id_set_label_string()
void volume_id_set_label_string (struct volume_id * id, const uint8_t * buf, size_t count)
Definition at line 115 of file util.c.
 {
     unsigned i;
     memcpy(id->label, buf, count);
     /* remove trailing whitespace */
     i = strnlen(id->label, count);
     while (i--) {
         if (!isspace(id->label[i]))
             break;
     }
     id->label[i+1] = '\0';
 }
References buf, count, i, isspace, volume_id::label, memcpy, and strnlen().
Referenced by volume_id_probe_bcache(), volume_id_probe_btrfs(), volume_id_probe_cramfs(), volume_id_probe_erofs(), volume_id_probe_ext(), volume_id_probe_hfs_hfsplus(), volume_id_probe_iso9660(), volume_id_probe_jfs(), volume_id_probe_linux_swap(), volume_id_probe_nilfs(), volume_id_probe_ocfs2(), volume_id_probe_reiserfs(), volume_id_probe_romfs(), volume_id_probe_sysv(), volume_id_probe_udf(), volume_id_probe_vfat(), and volume_id_probe_xfs().
volume_id_set_label_unicode16()
void volume_id_set_label_unicode16 (struct volume_id * id, const uint8_t * buf, enum endian endianess, size_t count)
Definition at line 130 of file util.c.
 {
     volume_id_set_unicode16(id->label, sizeof(id->label), buf, endianess, count);
 }
References buf, count, volume_id::label, and volume_id_set_unicode16().
Referenced by volume_id_probe_exfat(), volume_id_probe_f2fs(), volume_id_probe_hfs_hfsplus(), volume_id_probe_ntfs(), and volume_id_probe_udf().
volume_id_set_unicode16()
void volume_id_set_unicode16 (char * str, size_t len, const uint8_t * buf, enum endian endianess, size_t count)
Definition at line 23 of file util.c.
 {
     unsigned i, j;
     unsigned c;
     j = 0;
     for (i = 0; i + 2 <= count; i += 2) {
         if (endianess == LE)
             c = (buf[i+1] << 8) | buf[i];
         else
             c = (buf[i] << 8) | buf[i+1];
         if (c == 0)
             break;
         if (j+1 >= len)
             break;
         if (c < 0x80) {
             /* 0xxxxxxx */
         } else {
             uint8_t topbits = 0xc0;
             if (j+2 >= len)
                 break;
             if (c < 0x800) {
                 /* 110yyyxx 10xxxxxx */
             } else {
                 if (j+3 >= len)
                     break;
                 /* 1110yyyy 10yyyyxx 10xxxxxx */
                 str[j++] = (uint8_t) (0xe0 | (c >> 12));
                 topbits = 0x80;
             }
             str[j++] = (uint8_t) (topbits | ((c >> 6) & 0x3f));
             c = 0x80 | (c & 0x3f);
         }
         str[j++] = (uint8_t) c;
     }
     str[j] = '\0';
 }
References buf, c, count, i, j, LE, len, and str.
Referenced by volume_id_probe_iso9660(), and volume_id_set_label_unicode16().
volume_id_set_uuid()
void volume_id_set_uuid (struct volume_id * id, const uint8_t * buf, enum uuid_format format)
Definition at line 135 of file util.c.
 {
     unsigned i;
     unsigned count = (format == UUID_DCE_STRING ? VOLUME_ID_UUID_SIZE : 4 << format);
 //  memcpy(id->uuid_raw, buf, count);
 //  id->uuid_raw_len = count;
     /* if set, create string in the same format, the native platform uses */
     for (i = 0; i < count; i++)
         if (buf[i] != 0)
             goto set;
     return; /* all bytes are zero, leave it empty ("") */
 set:
     switch (format) {
     case UUID_DOS:
         sprintf(id->uuid, "%02X%02X-%02X%02X",
             buf[3], buf[2], buf[1], buf[0]);
         break;
     case UUID_NTFS:
         sprintf(id->uuid, "%02X%02X%02X%02X%02X%02X%02X%02X",
             buf[7], buf[6], buf[5], buf[4],
             buf[3], buf[2], buf[1], buf[0]);
         break;
     case UUID_DCE:
         sprintf(id->uuid,
             "%02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x",
             buf[0], buf[1], buf[2], buf[3],
             buf[4], buf[5],
             buf[6], buf[7],
             buf[8], buf[9],
             buf[10], buf[11], buf[12], buf[13], buf[14], buf[15]);
         break;
     case UUID_DCE_STRING:
         memcpy(id->uuid, buf, count);
         id->uuid[count] = '\0';
         break;
     }
 }
References buf, count, format(), i, memcpy, sprintf(), volume_id::uuid, UUID_DCE, UUID_DCE_STRING, UUID_DOS, UUID_NTFS, and VOLUME_ID_UUID_SIZE.
Referenced by hfs_set_uuid(), volume_id_probe_bcache(), volume_id_probe_btrfs(), volume_id_probe_erofs(), volume_id_probe_exfat(), volume_id_probe_ext(), volume_id_probe_f2fs(), volume_id_probe_jfs(), volume_id_probe_linux_raid(), volume_id_probe_linux_swap(), volume_id_probe_luks(), volume_id_probe_nilfs(), volume_id_probe_ntfs(), volume_id_probe_ocfs2(), volume_id_probe_reiserfs(), volume_id_probe_ubifs(), volume_id_probe_vfat(), and volume_id_probe_xfs().