Fennix: Userspace/musl/include/unistd.h File Reference
unistd.h File Reference
#include <features.h>
#include <bits/alltypes.h>
#include <bits/posix.h>
Macros
#define STDIN_FILENO 0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_DATA 3
#define SEEK_HOLE 4
#define NULL ((void*)0)
#define __NEED_size_t
#define __NEED_ssize_t
#define __NEED_uid_t
#define __NEED_gid_t
#define __NEED_off_t
#define __NEED_pid_t
#define __NEED_intptr_t
#define __NEED_useconds_t
#define F_OK 0
#define R_OK 4
#define W_OK 2
#define X_OK 1
#define POSIX_CLOSE_RESTART 0
#define _XOPEN_VERSION 700
#define _XOPEN_UNIX 1
#define _XOPEN_ENH_I18N 1
#define _POSIX_VERSION 200809L
#define _POSIX2_VERSION _POSIX_VERSION
#define _POSIX_ADVISORY_INFO _POSIX_VERSION
#define _POSIX_CHOWN_RESTRICTED 1
#define _POSIX_IPV6 _POSIX_VERSION
#define _POSIX_JOB_CONTROL 1
#define _POSIX_MAPPED_FILES _POSIX_VERSION
#define _POSIX_MEMLOCK _POSIX_VERSION
#define _POSIX_MEMLOCK_RANGE _POSIX_VERSION
#define _POSIX_MEMORY_PROTECTION _POSIX_VERSION
#define _POSIX_MESSAGE_PASSING _POSIX_VERSION
#define _POSIX_FSYNC _POSIX_VERSION
#define _POSIX_NO_TRUNC 1
#define _POSIX_RAW_SOCKETS _POSIX_VERSION
#define _POSIX_REALTIME_SIGNALS _POSIX_VERSION
#define _POSIX_REGEXP 1
#define _POSIX_SAVED_IDS 1
#define _POSIX_SHELL 1
#define _POSIX_SPAWN _POSIX_VERSION
#define _POSIX_VDISABLE 0
#define _POSIX_THREADS _POSIX_VERSION
#define _POSIX_THREAD_PROCESS_SHARED _POSIX_VERSION
#define _POSIX_THREAD_SAFE_FUNCTIONS _POSIX_VERSION
#define _POSIX_THREAD_ATTR_STACKADDR _POSIX_VERSION
#define _POSIX_THREAD_ATTR_STACKSIZE _POSIX_VERSION
#define _POSIX_THREAD_PRIORITY_SCHEDULING _POSIX_VERSION
#define _POSIX_THREAD_CPUTIME _POSIX_VERSION
#define _POSIX_TIMERS _POSIX_VERSION
#define _POSIX_TIMEOUTS _POSIX_VERSION
#define _POSIX_MONOTONIC_CLOCK _POSIX_VERSION
#define _POSIX_CPUTIME _POSIX_VERSION
#define _POSIX_CLOCK_SELECTION _POSIX_VERSION
#define _POSIX_BARRIERS _POSIX_VERSION
#define _POSIX_SPIN_LOCKS _POSIX_VERSION
#define _POSIX_READER_WRITER_LOCKS _POSIX_VERSION
#define _POSIX_ASYNCHRONOUS_IO _POSIX_VERSION
#define _POSIX_SEMAPHORES _POSIX_VERSION
#define _POSIX_SHARED_MEMORY_OBJECTS _POSIX_VERSION
#define _POSIX2_C_BIND _POSIX_VERSION
#define _PC_LINK_MAX 0
#define _PC_MAX_CANON 1
#define _PC_MAX_INPUT 2
#define _PC_NAME_MAX 3
#define _PC_PATH_MAX 4
#define _PC_PIPE_BUF 5
#define _PC_CHOWN_RESTRICTED 6
#define _PC_NO_TRUNC 7
#define _PC_VDISABLE 8
#define _PC_SYNC_IO 9
#define _PC_ASYNC_IO 10
#define _PC_PRIO_IO 11
#define _PC_SOCK_MAXBUF 12
#define _PC_FILESIZEBITS 13
#define _PC_REC_INCR_XFER_SIZE 14
#define _PC_REC_MAX_XFER_SIZE 15
#define _PC_REC_MIN_XFER_SIZE 16
#define _PC_REC_XFER_ALIGN 17
#define _PC_ALLOC_SIZE_MIN 18
#define _PC_SYMLINK_MAX 19
#define _PC_2_SYMLINKS 20
#define _SC_ARG_MAX 0
#define _SC_CHILD_MAX 1
#define _SC_CLK_TCK 2
#define _SC_NGROUPS_MAX 3
#define _SC_OPEN_MAX 4
#define _SC_STREAM_MAX 5
#define _SC_TZNAME_MAX 6
#define _SC_JOB_CONTROL 7
#define _SC_SAVED_IDS 8
#define _SC_REALTIME_SIGNALS 9
#define _SC_PRIORITY_SCHEDULING 10
#define _SC_TIMERS 11
#define _SC_ASYNCHRONOUS_IO 12
#define _SC_PRIORITIZED_IO 13
#define _SC_SYNCHRONIZED_IO 14
#define _SC_FSYNC 15
#define _SC_MAPPED_FILES 16
#define _SC_MEMLOCK 17
#define _SC_MEMLOCK_RANGE 18
#define _SC_MEMORY_PROTECTION 19
#define _SC_MESSAGE_PASSING 20
#define _SC_SEMAPHORES 21
#define _SC_SHARED_MEMORY_OBJECTS 22
#define _SC_AIO_LISTIO_MAX 23
#define _SC_AIO_MAX 24
#define _SC_AIO_PRIO_DELTA_MAX 25
#define _SC_DELAYTIMER_MAX 26
#define _SC_MQ_OPEN_MAX 27
#define _SC_MQ_PRIO_MAX 28
#define _SC_VERSION 29
#define _SC_PAGE_SIZE 30
#define _SC_PAGESIZE 30 /* !! */
#define _SC_RTSIG_MAX 31
#define _SC_SEM_NSEMS_MAX 32
#define _SC_SEM_VALUE_MAX 33
#define _SC_SIGQUEUE_MAX 34
#define _SC_TIMER_MAX 35
#define _SC_BC_BASE_MAX 36
#define _SC_BC_DIM_MAX 37
#define _SC_BC_SCALE_MAX 38
#define _SC_BC_STRING_MAX 39
#define _SC_COLL_WEIGHTS_MAX 40
#define _SC_EXPR_NEST_MAX 42
#define _SC_LINE_MAX 43
#define _SC_RE_DUP_MAX 44
#define _SC_2_VERSION 46
#define _SC_2_C_BIND 47
#define _SC_2_C_DEV 48
#define _SC_2_FORT_DEV 49
#define _SC_2_FORT_RUN 50
#define _SC_2_SW_DEV 51
#define _SC_2_LOCALEDEF 52
#define _SC_UIO_MAXIOV 60 /* !! */
#define _SC_IOV_MAX 60
#define _SC_THREADS 67
#define _SC_THREAD_SAFE_FUNCTIONS 68
#define _SC_GETGR_R_SIZE_MAX 69
#define _SC_GETPW_R_SIZE_MAX 70
#define _SC_LOGIN_NAME_MAX 71
#define _SC_TTY_NAME_MAX 72
#define _SC_THREAD_DESTRUCTOR_ITERATIONS 73
#define _SC_THREAD_KEYS_MAX 74
#define _SC_THREAD_STACK_MIN 75
#define _SC_THREAD_THREADS_MAX 76
#define _SC_THREAD_ATTR_STACKADDR 77
#define _SC_THREAD_ATTR_STACKSIZE 78
#define _SC_THREAD_PRIORITY_SCHEDULING 79
#define _SC_THREAD_PRIO_INHERIT 80
#define _SC_THREAD_PRIO_PROTECT 81
#define _SC_THREAD_PROCESS_SHARED 82
#define _SC_NPROCESSORS_CONF 83
#define _SC_NPROCESSORS_ONLN 84
#define _SC_PHYS_PAGES 85
#define _SC_AVPHYS_PAGES 86
#define _SC_ATEXIT_MAX 87
#define _SC_PASS_MAX 88
#define _SC_XOPEN_VERSION 89
#define _SC_XOPEN_XCU_VERSION 90
#define _SC_XOPEN_UNIX 91
#define _SC_XOPEN_CRYPT 92
#define _SC_XOPEN_ENH_I18N 93
#define _SC_XOPEN_SHM 94
#define _SC_2_CHAR_TERM 95
#define _SC_2_UPE 97
#define _SC_XOPEN_XPG2 98
#define _SC_XOPEN_XPG3 99
#define _SC_XOPEN_XPG4 100
#define _SC_NZERO 109
#define _SC_XBS5_ILP32_OFF32 125
#define _SC_XBS5_ILP32_OFFBIG 126
#define _SC_XBS5_LP64_OFF64 127
#define _SC_XBS5_LPBIG_OFFBIG 128
#define _SC_XOPEN_LEGACY 129
#define _SC_XOPEN_REALTIME 130
#define _SC_XOPEN_REALTIME_THREADS 131
#define _SC_ADVISORY_INFO 132
#define _SC_BARRIERS 133
#define _SC_CLOCK_SELECTION 137
#define _SC_CPUTIME 138
#define _SC_THREAD_CPUTIME 139
#define _SC_MONOTONIC_CLOCK 149
#define _SC_READER_WRITER_LOCKS 153
#define _SC_SPIN_LOCKS 154
#define _SC_REGEXP 155
#define _SC_SHELL 157
#define _SC_SPAWN 159
#define _SC_SPORADIC_SERVER 160
#define _SC_THREAD_SPORADIC_SERVER 161
#define _SC_TIMEOUTS 164
#define _SC_TYPED_MEMORY_OBJECTS 165
#define _SC_2_PBS 168
#define _SC_2_PBS_ACCOUNTING 169
#define _SC_2_PBS_LOCATE 170
#define _SC_2_PBS_MESSAGE 171
#define _SC_2_PBS_TRACK 172
#define _SC_SYMLOOP_MAX 173
#define _SC_STREAMS 174
#define _SC_2_PBS_CHECKPOINT 175
#define _SC_V6_ILP32_OFF32 176
#define _SC_V6_ILP32_OFFBIG 177
#define _SC_V6_LP64_OFF64 178
#define _SC_V6_LPBIG_OFFBIG 179
#define _SC_HOST_NAME_MAX 180
#define _SC_TRACE 181
#define _SC_TRACE_EVENT_FILTER 182
#define _SC_TRACE_INHERIT 183
#define _SC_TRACE_LOG 184
#define _SC_IPV6 235
#define _SC_RAW_SOCKETS 236
#define _SC_V7_ILP32_OFF32 237
#define _SC_V7_ILP32_OFFBIG 238
#define _SC_V7_LP64_OFF64 239
#define _SC_V7_LPBIG_OFFBIG 240
#define _SC_SS_REPL_MAX 241
#define _SC_TRACE_EVENT_NAME_MAX 242
#define _SC_TRACE_NAME_MAX 243
#define _SC_TRACE_SYS_MAX 244
#define _SC_TRACE_USER_EVENT_MAX 245
#define _SC_XOPEN_STREAMS 246
#define _SC_THREAD_ROBUST_PRIO_INHERIT 247
#define _SC_THREAD_ROBUST_PRIO_PROTECT 248
#define _SC_MINSIGSTKSZ 249
#define _SC_SIGSTKSZ 250
#define _CS_PATH 0
#define _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS 1
#define _CS_GNU_LIBC_VERSION 2
#define _CS_GNU_LIBPTHREAD_VERSION 3
#define _CS_POSIX_V5_WIDTH_RESTRICTED_ENVS 4
#define _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS 5
#define _CS_POSIX_V6_ILP32_OFF32_CFLAGS 1116
#define _CS_POSIX_V6_ILP32_OFF32_LDFLAGS 1117
#define _CS_POSIX_V6_ILP32_OFF32_LIBS 1118
#define _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS 1119
#define _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS 1120
#define _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS 1121
#define _CS_POSIX_V6_ILP32_OFFBIG_LIBS 1122
#define _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS 1123
#define _CS_POSIX_V6_LP64_OFF64_CFLAGS 1124
#define _CS_POSIX_V6_LP64_OFF64_LDFLAGS 1125
#define _CS_POSIX_V6_LP64_OFF64_LIBS 1126
#define _CS_POSIX_V6_LP64_OFF64_LINTFLAGS 1127
#define _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS 1128
#define _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS 1129
#define _CS_POSIX_V6_LPBIG_OFFBIG_LIBS 1130
#define _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS 1131
#define _CS_POSIX_V7_ILP32_OFF32_CFLAGS 1132
#define _CS_POSIX_V7_ILP32_OFF32_LDFLAGS 1133
#define _CS_POSIX_V7_ILP32_OFF32_LIBS 1134
#define _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS 1135
#define _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS 1136
#define _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS 1137
#define _CS_POSIX_V7_ILP32_OFFBIG_LIBS 1138
#define _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS 1139
#define _CS_POSIX_V7_LP64_OFF64_CFLAGS 1140
#define _CS_POSIX_V7_LP64_OFF64_LDFLAGS 1141
#define _CS_POSIX_V7_LP64_OFF64_LIBS 1142
#define _CS_POSIX_V7_LP64_OFF64_LINTFLAGS 1143
#define _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS 1144
#define _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS 1145
#define _CS_POSIX_V7_LPBIG_OFFBIG_LIBS 1146
#define _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS 1147
#define _CS_V6_ENV 1148
#define _CS_V7_ENV 1149
#define _CS_POSIX_V7_THREADS_CFLAGS 1150
#define _CS_POSIX_V7_THREADS_LDFLAGS 1151
Functions
int pipe (int[2])
int pipe2 (int[2], int)
int close (int)
int posix_close (int, int)
int dup (int)
int dup2 (int, int)
int dup3 (int, int, int)
off_t lseek (int, off_t, int)
int fsync (int)
int fdatasync (int)
ssize_t read (int, void *, size_t)
ssize_t write (int, const void *, size_t)
ssize_t pread (int, void *, size_t, off_t)
ssize_t pwrite (int, const void *, size_t, off_t)
int chown (const char *, uid_t, gid_t)
int fchown (int, uid_t, gid_t)
int lchown (const char *, uid_t, gid_t)
int fchownat (int, const char *, uid_t, gid_t, int)
int link (const char *, const char *)
int linkat (int, const char *, int, const char *, int)
int symlink (const char *, const char *)
int symlinkat (const char *, int, const char *)
ssize_t readlink (const char *__restrict, char *__restrict, size_t)
ssize_t readlinkat (int, const char *__restrict, char *__restrict, size_t)
int unlink (const char *)
int unlinkat (int, const char *, int)
int rmdir (const char *)
int truncate (const char *, off_t)
int ftruncate (int, off_t)
int access (const char *, int)
int faccessat (int, const char *, int, int)
int chdir (const char *)
int fchdir (int)
char * getcwd (char *, size_t)
unsigned alarm (unsigned)
unsigned sleep (unsigned)
int pause (void)
pid_t fork (void)
pid_t _Fork (void)
int execve (const char *, char *const [], char *const [])
int execv (const char *, char *const [])
int execle (const char *, const char *,...)
int execl (const char *, const char *,...)
int execvp (const char *, char *const [])
int execlp (const char *, const char *,...)
int fexecve (int, char *const [], char *const [])
_Noreturn void _exit (int)
pid_t getpid (void)
pid_t getppid (void)
pid_t getpgrp (void)
pid_t getpgid (pid_t)
int setpgid (pid_t, pid_t)
pid_t setsid (void)
pid_t getsid (pid_t)
char * ttyname (int)
int ttyname_r (int, char *, size_t)
int isatty (int)
pid_t tcgetpgrp (int)
int tcsetpgrp (int, pid_t)
uid_t getuid (void)
uid_t geteuid (void)
gid_t getgid (void)
gid_t getegid (void)
int getgroups (int, gid_t[])
int setuid (uid_t)
int seteuid (uid_t)
int setgid (gid_t)
int setegid (gid_t)
char * getlogin (void)
int getlogin_r (char *, size_t)
int gethostname (char *, size_t)
char * ctermid (char *)
int getopt (int, char *const [], const char *)
long pathconf (const char *, int)
long fpathconf (int, int)
long sysconf (int)
size_t confstr (int, char *, size_t)
Variables
char * optarg
int optind
int opterr
int optopt
Macro Definition Documentation
__NEED_gid_t
#define __NEED_gid_t
Definition at line 31 of file unistd.h.
__NEED_intptr_t
#define __NEED_intptr_t
Definition at line 34 of file unistd.h.
__NEED_off_t
#define __NEED_off_t
Definition at line 32 of file unistd.h.
__NEED_pid_t
#define __NEED_pid_t
Definition at line 33 of file unistd.h.
__NEED_size_t
#define __NEED_size_t
Definition at line 28 of file unistd.h.
__NEED_ssize_t
#define __NEED_ssize_t
Definition at line 29 of file unistd.h.
__NEED_uid_t
#define __NEED_uid_t
Definition at line 30 of file unistd.h.
__NEED_useconds_t
#define __NEED_useconds_t
Definition at line 35 of file unistd.h.
_CS_GNU_LIBC_VERSION
#define _CS_GNU_LIBC_VERSION 2
Definition at line 433 of file unistd.h.
_CS_GNU_LIBPTHREAD_VERSION
#define _CS_GNU_LIBPTHREAD_VERSION 3
Definition at line 434 of file unistd.h.
_CS_PATH
#define _CS_PATH 0
Definition at line 431 of file unistd.h.
_CS_POSIX_V5_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V5_WIDTH_RESTRICTED_ENVS 4
Definition at line 435 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_CFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_CFLAGS 1116
Definition at line 438 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LDFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_LDFLAGS 1117
Definition at line 439 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LIBS
#define _CS_POSIX_V6_ILP32_OFF32_LIBS 1118
Definition at line 440 of file unistd.h.
_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS
#define _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS 1119
Definition at line 441 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS 1120
Definition at line 442 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS 1121
Definition at line 443 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LIBS
#define _CS_POSIX_V6_ILP32_OFFBIG_LIBS 1122
Definition at line 444 of file unistd.h.
_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS
#define _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS 1123
Definition at line 445 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_CFLAGS
#define _CS_POSIX_V6_LP64_OFF64_CFLAGS 1124
Definition at line 446 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LDFLAGS
#define _CS_POSIX_V6_LP64_OFF64_LDFLAGS 1125
Definition at line 447 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LIBS
#define _CS_POSIX_V6_LP64_OFF64_LIBS 1126
Definition at line 448 of file unistd.h.
_CS_POSIX_V6_LP64_OFF64_LINTFLAGS
#define _CS_POSIX_V6_LP64_OFF64_LINTFLAGS 1127
Definition at line 449 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS 1128
Definition at line 450 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS 1129
Definition at line 451 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LIBS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LIBS 1130
Definition at line 452 of file unistd.h.
_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS
#define _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS 1131
Definition at line 453 of file unistd.h.
_CS_POSIX_V6_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS 1
Definition at line 432 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_CFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_CFLAGS 1132
Definition at line 454 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LDFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_LDFLAGS 1133
Definition at line 455 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LIBS
#define _CS_POSIX_V7_ILP32_OFF32_LIBS 1134
Definition at line 456 of file unistd.h.
_CS_POSIX_V7_ILP32_OFF32_LINTFLAGS
#define _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS 1135
Definition at line 457 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS 1136
Definition at line 458 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS 1137
Definition at line 459 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LIBS
#define _CS_POSIX_V7_ILP32_OFFBIG_LIBS 1138
Definition at line 460 of file unistd.h.
_CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS
#define _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS 1139
Definition at line 461 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_CFLAGS
#define _CS_POSIX_V7_LP64_OFF64_CFLAGS 1140
Definition at line 462 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LDFLAGS
#define _CS_POSIX_V7_LP64_OFF64_LDFLAGS 1141
Definition at line 463 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LIBS
#define _CS_POSIX_V7_LP64_OFF64_LIBS 1142
Definition at line 464 of file unistd.h.
_CS_POSIX_V7_LP64_OFF64_LINTFLAGS
#define _CS_POSIX_V7_LP64_OFF64_LINTFLAGS 1143
Definition at line 465 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS 1144
Definition at line 466 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS 1145
Definition at line 467 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LIBS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LIBS 1146
Definition at line 468 of file unistd.h.
_CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS
#define _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS 1147
Definition at line 469 of file unistd.h.
_CS_POSIX_V7_THREADS_CFLAGS
#define _CS_POSIX_V7_THREADS_CFLAGS 1150
Definition at line 472 of file unistd.h.
_CS_POSIX_V7_THREADS_LDFLAGS
#define _CS_POSIX_V7_THREADS_LDFLAGS 1151
Definition at line 473 of file unistd.h.
_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS
#define _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS 5
Definition at line 436 of file unistd.h.
_CS_V6_ENV
#define _CS_V6_ENV 1148
Definition at line 470 of file unistd.h.
_CS_V7_ENV
#define _CS_V7_ENV 1149
Definition at line 471 of file unistd.h.
_PC_2_SYMLINKS
#define _PC_2_SYMLINKS 20
Definition at line 284 of file unistd.h.
_PC_ALLOC_SIZE_MIN
#define _PC_ALLOC_SIZE_MIN 18
Definition at line 282 of file unistd.h.
_PC_ASYNC_IO
#define _PC_ASYNC_IO 10
Definition at line 274 of file unistd.h.
_PC_CHOWN_RESTRICTED
#define _PC_CHOWN_RESTRICTED 6
Definition at line 270 of file unistd.h.
_PC_FILESIZEBITS
#define _PC_FILESIZEBITS 13
Definition at line 277 of file unistd.h.
_PC_LINK_MAX
#define _PC_LINK_MAX 0
Definition at line 264 of file unistd.h.
_PC_MAX_CANON
#define _PC_MAX_CANON 1
Definition at line 265 of file unistd.h.
_PC_MAX_INPUT
#define _PC_MAX_INPUT 2
Definition at line 266 of file unistd.h.
_PC_NAME_MAX
#define _PC_NAME_MAX 3
Definition at line 267 of file unistd.h.
_PC_NO_TRUNC
#define _PC_NO_TRUNC 7
Definition at line 271 of file unistd.h.
_PC_PATH_MAX
#define _PC_PATH_MAX 4
Definition at line 268 of file unistd.h.
_PC_PIPE_BUF
#define _PC_PIPE_BUF 5
Definition at line 269 of file unistd.h.
_PC_PRIO_IO
#define _PC_PRIO_IO 11
Definition at line 275 of file unistd.h.
_PC_REC_INCR_XFER_SIZE
#define _PC_REC_INCR_XFER_SIZE 14
Definition at line 278 of file unistd.h.
_PC_REC_MAX_XFER_SIZE
#define _PC_REC_MAX_XFER_SIZE 15
Definition at line 279 of file unistd.h.
_PC_REC_MIN_XFER_SIZE
#define _PC_REC_MIN_XFER_SIZE 16
Definition at line 280 of file unistd.h.
_PC_REC_XFER_ALIGN
#define _PC_REC_XFER_ALIGN 17
Definition at line 281 of file unistd.h.
_PC_SOCK_MAXBUF
#define _PC_SOCK_MAXBUF 12
Definition at line 276 of file unistd.h.
_PC_SYMLINK_MAX
#define _PC_SYMLINK_MAX 19
Definition at line 283 of file unistd.h.
_PC_SYNC_IO
#define _PC_SYNC_IO 9
Definition at line 273 of file unistd.h.
_PC_VDISABLE
#define _PC_VDISABLE 8
Definition at line 272 of file unistd.h.
_POSIX2_C_BIND
#define _POSIX2_C_BIND _POSIX_VERSION
Definition at line 258 of file unistd.h.
_POSIX2_VERSION
#define _POSIX2_VERSION _POSIX_VERSION
Definition at line 218 of file unistd.h.
_POSIX_ADVISORY_INFO
#define _POSIX_ADVISORY_INFO _POSIX_VERSION
Definition at line 220 of file unistd.h.
_POSIX_ASYNCHRONOUS_IO
#define _POSIX_ASYNCHRONOUS_IO _POSIX_VERSION
Definition at line 254 of file unistd.h.
_POSIX_BARRIERS
#define _POSIX_BARRIERS _POSIX_VERSION
Definition at line 251 of file unistd.h.
_POSIX_CHOWN_RESTRICTED
#define _POSIX_CHOWN_RESTRICTED 1
Definition at line 221 of file unistd.h.
_POSIX_CLOCK_SELECTION
#define _POSIX_CLOCK_SELECTION _POSIX_VERSION
Definition at line 250 of file unistd.h.
_POSIX_CPUTIME
#define _POSIX_CPUTIME _POSIX_VERSION
Definition at line 249 of file unistd.h.
_POSIX_FSYNC
#define _POSIX_FSYNC _POSIX_VERSION
Definition at line 229 of file unistd.h.
_POSIX_IPV6
#define _POSIX_IPV6 _POSIX_VERSION
Definition at line 222 of file unistd.h.
_POSIX_JOB_CONTROL
#define _POSIX_JOB_CONTROL 1
Definition at line 223 of file unistd.h.
_POSIX_MAPPED_FILES
#define _POSIX_MAPPED_FILES _POSIX_VERSION
Definition at line 224 of file unistd.h.
_POSIX_MEMLOCK
#define _POSIX_MEMLOCK _POSIX_VERSION
Definition at line 225 of file unistd.h.
_POSIX_MEMLOCK_RANGE
#define _POSIX_MEMLOCK_RANGE _POSIX_VERSION
Definition at line 226 of file unistd.h.
_POSIX_MEMORY_PROTECTION
#define _POSIX_MEMORY_PROTECTION _POSIX_VERSION
Definition at line 227 of file unistd.h.
_POSIX_MESSAGE_PASSING
#define _POSIX_MESSAGE_PASSING _POSIX_VERSION
Definition at line 228 of file unistd.h.
_POSIX_MONOTONIC_CLOCK
#define _POSIX_MONOTONIC_CLOCK _POSIX_VERSION
Definition at line 248 of file unistd.h.
_POSIX_NO_TRUNC
#define _POSIX_NO_TRUNC 1
Definition at line 230 of file unistd.h.
_POSIX_RAW_SOCKETS
#define _POSIX_RAW_SOCKETS _POSIX_VERSION
Definition at line 231 of file unistd.h.
_POSIX_READER_WRITER_LOCKS
#define _POSIX_READER_WRITER_LOCKS _POSIX_VERSION
Definition at line 253 of file unistd.h.
_POSIX_REALTIME_SIGNALS
#define _POSIX_REALTIME_SIGNALS _POSIX_VERSION
Definition at line 232 of file unistd.h.
_POSIX_REGEXP
#define _POSIX_REGEXP 1
Definition at line 233 of file unistd.h.
_POSIX_SAVED_IDS
#define _POSIX_SAVED_IDS 1
Definition at line 234 of file unistd.h.
_POSIX_SEMAPHORES
#define _POSIX_SEMAPHORES _POSIX_VERSION
Definition at line 255 of file unistd.h.
_POSIX_SHARED_MEMORY_OBJECTS
#define _POSIX_SHARED_MEMORY_OBJECTS _POSIX_VERSION
Definition at line 256 of file unistd.h.
_POSIX_SHELL
#define _POSIX_SHELL 1
Definition at line 235 of file unistd.h.
_POSIX_SPAWN
#define _POSIX_SPAWN _POSIX_VERSION
Definition at line 236 of file unistd.h.
_POSIX_SPIN_LOCKS
#define _POSIX_SPIN_LOCKS _POSIX_VERSION
Definition at line 252 of file unistd.h.
_POSIX_THREAD_ATTR_STACKADDR
#define _POSIX_THREAD_ATTR_STACKADDR _POSIX_VERSION
Definition at line 242 of file unistd.h.
_POSIX_THREAD_ATTR_STACKSIZE
#define _POSIX_THREAD_ATTR_STACKSIZE _POSIX_VERSION
Definition at line 243 of file unistd.h.
_POSIX_THREAD_CPUTIME
#define _POSIX_THREAD_CPUTIME _POSIX_VERSION
Definition at line 245 of file unistd.h.
_POSIX_THREAD_PRIORITY_SCHEDULING
#define _POSIX_THREAD_PRIORITY_SCHEDULING _POSIX_VERSION
Definition at line 244 of file unistd.h.
_POSIX_THREAD_PROCESS_SHARED
#define _POSIX_THREAD_PROCESS_SHARED _POSIX_VERSION
Definition at line 240 of file unistd.h.
_POSIX_THREAD_SAFE_FUNCTIONS
#define _POSIX_THREAD_SAFE_FUNCTIONS _POSIX_VERSION
Definition at line 241 of file unistd.h.
_POSIX_THREADS
#define _POSIX_THREADS _POSIX_VERSION
Definition at line 239 of file unistd.h.
_POSIX_TIMEOUTS
#define _POSIX_TIMEOUTS _POSIX_VERSION
Definition at line 247 of file unistd.h.
_POSIX_TIMERS
#define _POSIX_TIMERS _POSIX_VERSION
Definition at line 246 of file unistd.h.
_POSIX_VDISABLE
#define _POSIX_VDISABLE 0
Definition at line 237 of file unistd.h.
_POSIX_VERSION
#define _POSIX_VERSION 200809L
Definition at line 217 of file unistd.h.
_SC_2_C_BIND
#define _SC_2_C_BIND 47
Definition at line 332 of file unistd.h.
_SC_2_C_DEV
#define _SC_2_C_DEV 48
Definition at line 333 of file unistd.h.
_SC_2_CHAR_TERM
#define _SC_2_CHAR_TERM 95
Definition at line 368 of file unistd.h.
_SC_2_FORT_DEV
#define _SC_2_FORT_DEV 49
Definition at line 334 of file unistd.h.
_SC_2_FORT_RUN
#define _SC_2_FORT_RUN 50
Definition at line 335 of file unistd.h.
_SC_2_LOCALEDEF
#define _SC_2_LOCALEDEF 52
Definition at line 337 of file unistd.h.
_SC_2_PBS
#define _SC_2_PBS 168
Definition at line 396 of file unistd.h.
_SC_2_PBS_ACCOUNTING
#define _SC_2_PBS_ACCOUNTING 169
Definition at line 397 of file unistd.h.
_SC_2_PBS_CHECKPOINT
#define _SC_2_PBS_CHECKPOINT 175
Definition at line 403 of file unistd.h.
_SC_2_PBS_LOCATE
#define _SC_2_PBS_LOCATE 170
Definition at line 398 of file unistd.h.
_SC_2_PBS_MESSAGE
#define _SC_2_PBS_MESSAGE 171
Definition at line 399 of file unistd.h.
_SC_2_PBS_TRACK
#define _SC_2_PBS_TRACK 172
Definition at line 400 of file unistd.h.
_SC_2_SW_DEV
#define _SC_2_SW_DEV 51
Definition at line 336 of file unistd.h.
_SC_2_UPE
#define _SC_2_UPE 97
Definition at line 369 of file unistd.h.
_SC_2_VERSION
#define _SC_2_VERSION 46
Definition at line 331 of file unistd.h.
_SC_ADVISORY_INFO
#define _SC_ADVISORY_INFO 132
Definition at line 381 of file unistd.h.
_SC_AIO_LISTIO_MAX
#define _SC_AIO_LISTIO_MAX 23
Definition at line 309 of file unistd.h.
_SC_AIO_MAX
#define _SC_AIO_MAX 24
Definition at line 310 of file unistd.h.
_SC_AIO_PRIO_DELTA_MAX
#define _SC_AIO_PRIO_DELTA_MAX 25
Definition at line 311 of file unistd.h.
_SC_ARG_MAX
#define _SC_ARG_MAX 0
Definition at line 286 of file unistd.h.
_SC_ASYNCHRONOUS_IO
#define _SC_ASYNCHRONOUS_IO 12
Definition at line 298 of file unistd.h.
_SC_ATEXIT_MAX
#define _SC_ATEXIT_MAX 87
Definition at line 360 of file unistd.h.
_SC_AVPHYS_PAGES
#define _SC_AVPHYS_PAGES 86
Definition at line 359 of file unistd.h.
_SC_BARRIERS
#define _SC_BARRIERS 133
Definition at line 382 of file unistd.h.
_SC_BC_BASE_MAX
#define _SC_BC_BASE_MAX 36
Definition at line 323 of file unistd.h.
_SC_BC_DIM_MAX
#define _SC_BC_DIM_MAX 37
Definition at line 324 of file unistd.h.
_SC_BC_SCALE_MAX
#define _SC_BC_SCALE_MAX 38
Definition at line 325 of file unistd.h.
_SC_BC_STRING_MAX
#define _SC_BC_STRING_MAX 39
Definition at line 326 of file unistd.h.
_SC_CHILD_MAX
#define _SC_CHILD_MAX 1
Definition at line 287 of file unistd.h.
_SC_CLK_TCK
#define _SC_CLK_TCK 2
Definition at line 288 of file unistd.h.
_SC_CLOCK_SELECTION
#define _SC_CLOCK_SELECTION 137
Definition at line 383 of file unistd.h.
_SC_COLL_WEIGHTS_MAX
#define _SC_COLL_WEIGHTS_MAX 40
Definition at line 327 of file unistd.h.
_SC_CPUTIME
#define _SC_CPUTIME 138
Definition at line 384 of file unistd.h.
_SC_DELAYTIMER_MAX
#define _SC_DELAYTIMER_MAX 26
Definition at line 312 of file unistd.h.
_SC_EXPR_NEST_MAX
#define _SC_EXPR_NEST_MAX 42
Definition at line 328 of file unistd.h.
_SC_FSYNC
#define _SC_FSYNC 15
Definition at line 301 of file unistd.h.
_SC_GETGR_R_SIZE_MAX
#define _SC_GETGR_R_SIZE_MAX 69
Definition at line 342 of file unistd.h.
_SC_GETPW_R_SIZE_MAX
#define _SC_GETPW_R_SIZE_MAX 70
Definition at line 343 of file unistd.h.
_SC_HOST_NAME_MAX
#define _SC_HOST_NAME_MAX 180
Definition at line 408 of file unistd.h.
_SC_IOV_MAX
#define _SC_IOV_MAX 60
Definition at line 339 of file unistd.h.
_SC_IPV6
#define _SC_IPV6 235
Definition at line 414 of file unistd.h.
_SC_JOB_CONTROL
#define _SC_JOB_CONTROL 7
Definition at line 293 of file unistd.h.
_SC_LINE_MAX
#define _SC_LINE_MAX 43
Definition at line 329 of file unistd.h.
_SC_LOGIN_NAME_MAX
#define _SC_LOGIN_NAME_MAX 71
Definition at line 344 of file unistd.h.
_SC_MAPPED_FILES
#define _SC_MAPPED_FILES 16
Definition at line 302 of file unistd.h.
_SC_MEMLOCK
#define _SC_MEMLOCK 17
Definition at line 303 of file unistd.h.
_SC_MEMLOCK_RANGE
#define _SC_MEMLOCK_RANGE 18
Definition at line 304 of file unistd.h.
_SC_MEMORY_PROTECTION
#define _SC_MEMORY_PROTECTION 19
Definition at line 305 of file unistd.h.
_SC_MESSAGE_PASSING
#define _SC_MESSAGE_PASSING 20
Definition at line 306 of file unistd.h.
_SC_MINSIGSTKSZ
#define _SC_MINSIGSTKSZ 249
Definition at line 428 of file unistd.h.
_SC_MONOTONIC_CLOCK
#define _SC_MONOTONIC_CLOCK 149
Definition at line 386 of file unistd.h.
_SC_MQ_OPEN_MAX
#define _SC_MQ_OPEN_MAX 27
Definition at line 313 of file unistd.h.
_SC_MQ_PRIO_MAX
#define _SC_MQ_PRIO_MAX 28
Definition at line 314 of file unistd.h.
_SC_NGROUPS_MAX
#define _SC_NGROUPS_MAX 3
Definition at line 289 of file unistd.h.
_SC_NPROCESSORS_CONF
#define _SC_NPROCESSORS_CONF 83
Definition at line 356 of file unistd.h.
_SC_NPROCESSORS_ONLN
#define _SC_NPROCESSORS_ONLN 84
Definition at line 357 of file unistd.h.
_SC_NZERO
#define _SC_NZERO 109
Definition at line 373 of file unistd.h.
_SC_OPEN_MAX
#define _SC_OPEN_MAX 4
Definition at line 290 of file unistd.h.
_SC_PAGE_SIZE
#define _SC_PAGE_SIZE 30
Definition at line 316 of file unistd.h.
_SC_PAGESIZE
#define _SC_PAGESIZE 30 /* !! */
Definition at line 317 of file unistd.h.
_SC_PASS_MAX
#define _SC_PASS_MAX 88
Definition at line 361 of file unistd.h.
_SC_PHYS_PAGES
#define _SC_PHYS_PAGES 85
Definition at line 358 of file unistd.h.
_SC_PRIORITIZED_IO
#define _SC_PRIORITIZED_IO 13
Definition at line 299 of file unistd.h.
_SC_PRIORITY_SCHEDULING
#define _SC_PRIORITY_SCHEDULING 10
Definition at line 296 of file unistd.h.
_SC_RAW_SOCKETS
#define _SC_RAW_SOCKETS 236
Definition at line 415 of file unistd.h.
_SC_RE_DUP_MAX
#define _SC_RE_DUP_MAX 44
Definition at line 330 of file unistd.h.
_SC_READER_WRITER_LOCKS
#define _SC_READER_WRITER_LOCKS 153
Definition at line 387 of file unistd.h.
_SC_REALTIME_SIGNALS
#define _SC_REALTIME_SIGNALS 9
Definition at line 295 of file unistd.h.
_SC_REGEXP
#define _SC_REGEXP 155
Definition at line 389 of file unistd.h.
_SC_RTSIG_MAX
#define _SC_RTSIG_MAX 31
Definition at line 318 of file unistd.h.
_SC_SAVED_IDS
#define _SC_SAVED_IDS 8
Definition at line 294 of file unistd.h.
_SC_SEM_NSEMS_MAX
#define _SC_SEM_NSEMS_MAX 32
Definition at line 319 of file unistd.h.
_SC_SEM_VALUE_MAX
#define _SC_SEM_VALUE_MAX 33
Definition at line 320 of file unistd.h.
_SC_SEMAPHORES
#define _SC_SEMAPHORES 21
Definition at line 307 of file unistd.h.
_SC_SHARED_MEMORY_OBJECTS
#define _SC_SHARED_MEMORY_OBJECTS 22
Definition at line 308 of file unistd.h.
_SC_SHELL
#define _SC_SHELL 157
Definition at line 390 of file unistd.h.
_SC_SIGQUEUE_MAX
#define _SC_SIGQUEUE_MAX 34
Definition at line 321 of file unistd.h.
_SC_SIGSTKSZ
#define _SC_SIGSTKSZ 250
Definition at line 429 of file unistd.h.
_SC_SPAWN
#define _SC_SPAWN 159
Definition at line 391 of file unistd.h.
_SC_SPIN_LOCKS
#define _SC_SPIN_LOCKS 154
Definition at line 388 of file unistd.h.
_SC_SPORADIC_SERVER
#define _SC_SPORADIC_SERVER 160
Definition at line 392 of file unistd.h.
_SC_SS_REPL_MAX
#define _SC_SS_REPL_MAX 241
Definition at line 420 of file unistd.h.
_SC_STREAM_MAX
#define _SC_STREAM_MAX 5
Definition at line 291 of file unistd.h.
_SC_STREAMS
#define _SC_STREAMS 174
Definition at line 402 of file unistd.h.
_SC_SYMLOOP_MAX
#define _SC_SYMLOOP_MAX 173
Definition at line 401 of file unistd.h.
_SC_SYNCHRONIZED_IO
#define _SC_SYNCHRONIZED_IO 14
Definition at line 300 of file unistd.h.
_SC_THREAD_ATTR_STACKADDR
#define _SC_THREAD_ATTR_STACKADDR 77
Definition at line 350 of file unistd.h.
_SC_THREAD_ATTR_STACKSIZE
#define _SC_THREAD_ATTR_STACKSIZE 78
Definition at line 351 of file unistd.h.
_SC_THREAD_CPUTIME
#define _SC_THREAD_CPUTIME 139
Definition at line 385 of file unistd.h.
_SC_THREAD_DESTRUCTOR_ITERATIONS
#define _SC_THREAD_DESTRUCTOR_ITERATIONS 73
Definition at line 346 of file unistd.h.
_SC_THREAD_KEYS_MAX
#define _SC_THREAD_KEYS_MAX 74
Definition at line 347 of file unistd.h.
_SC_THREAD_PRIO_INHERIT
#define _SC_THREAD_PRIO_INHERIT 80
Definition at line 353 of file unistd.h.
_SC_THREAD_PRIO_PROTECT
#define _SC_THREAD_PRIO_PROTECT 81
Definition at line 354 of file unistd.h.
_SC_THREAD_PRIORITY_SCHEDULING
#define _SC_THREAD_PRIORITY_SCHEDULING 79
Definition at line 352 of file unistd.h.
_SC_THREAD_PROCESS_SHARED
#define _SC_THREAD_PROCESS_SHARED 82
Definition at line 355 of file unistd.h.
_SC_THREAD_ROBUST_PRIO_INHERIT
#define _SC_THREAD_ROBUST_PRIO_INHERIT 247
Definition at line 426 of file unistd.h.
_SC_THREAD_ROBUST_PRIO_PROTECT
#define _SC_THREAD_ROBUST_PRIO_PROTECT 248
Definition at line 427 of file unistd.h.
_SC_THREAD_SAFE_FUNCTIONS
#define _SC_THREAD_SAFE_FUNCTIONS 68
Definition at line 341 of file unistd.h.
_SC_THREAD_SPORADIC_SERVER
#define _SC_THREAD_SPORADIC_SERVER 161
Definition at line 393 of file unistd.h.
_SC_THREAD_STACK_MIN
#define _SC_THREAD_STACK_MIN 75
Definition at line 348 of file unistd.h.
_SC_THREAD_THREADS_MAX
#define _SC_THREAD_THREADS_MAX 76
Definition at line 349 of file unistd.h.
_SC_THREADS
#define _SC_THREADS 67
Definition at line 340 of file unistd.h.
_SC_TIMEOUTS
#define _SC_TIMEOUTS 164
Definition at line 394 of file unistd.h.
_SC_TIMER_MAX
#define _SC_TIMER_MAX 35
Definition at line 322 of file unistd.h.
_SC_TIMERS
#define _SC_TIMERS 11
Definition at line 297 of file unistd.h.
_SC_TRACE
#define _SC_TRACE 181
Definition at line 409 of file unistd.h.
_SC_TRACE_EVENT_FILTER
#define _SC_TRACE_EVENT_FILTER 182
Definition at line 410 of file unistd.h.
_SC_TRACE_EVENT_NAME_MAX
#define _SC_TRACE_EVENT_NAME_MAX 242
Definition at line 421 of file unistd.h.
_SC_TRACE_INHERIT
#define _SC_TRACE_INHERIT 183
Definition at line 411 of file unistd.h.
_SC_TRACE_LOG
#define _SC_TRACE_LOG 184
Definition at line 412 of file unistd.h.
_SC_TRACE_NAME_MAX
#define _SC_TRACE_NAME_MAX 243
Definition at line 422 of file unistd.h.
_SC_TRACE_SYS_MAX
#define _SC_TRACE_SYS_MAX 244
Definition at line 423 of file unistd.h.
_SC_TRACE_USER_EVENT_MAX
#define _SC_TRACE_USER_EVENT_MAX 245
Definition at line 424 of file unistd.h.
_SC_TTY_NAME_MAX
#define _SC_TTY_NAME_MAX 72
Definition at line 345 of file unistd.h.
_SC_TYPED_MEMORY_OBJECTS
#define _SC_TYPED_MEMORY_OBJECTS 165
Definition at line 395 of file unistd.h.
_SC_TZNAME_MAX
#define _SC_TZNAME_MAX 6
Definition at line 292 of file unistd.h.
_SC_UIO_MAXIOV
#define _SC_UIO_MAXIOV 60 /* !! */
Definition at line 338 of file unistd.h.
_SC_V6_ILP32_OFF32
#define _SC_V6_ILP32_OFF32 176
Definition at line 404 of file unistd.h.
_SC_V6_ILP32_OFFBIG
#define _SC_V6_ILP32_OFFBIG 177
Definition at line 405 of file unistd.h.
_SC_V6_LP64_OFF64
#define _SC_V6_LP64_OFF64 178
Definition at line 406 of file unistd.h.
_SC_V6_LPBIG_OFFBIG
#define _SC_V6_LPBIG_OFFBIG 179
Definition at line 407 of file unistd.h.
_SC_V7_ILP32_OFF32
#define _SC_V7_ILP32_OFF32 237
Definition at line 416 of file unistd.h.
_SC_V7_ILP32_OFFBIG
#define _SC_V7_ILP32_OFFBIG 238
Definition at line 417 of file unistd.h.
_SC_V7_LP64_OFF64
#define _SC_V7_LP64_OFF64 239
Definition at line 418 of file unistd.h.
_SC_V7_LPBIG_OFFBIG
#define _SC_V7_LPBIG_OFFBIG 240
Definition at line 419 of file unistd.h.
_SC_VERSION
#define _SC_VERSION 29
Definition at line 315 of file unistd.h.
_SC_XBS5_ILP32_OFF32
#define _SC_XBS5_ILP32_OFF32 125
Definition at line 374 of file unistd.h.
_SC_XBS5_ILP32_OFFBIG
#define _SC_XBS5_ILP32_OFFBIG 126
Definition at line 375 of file unistd.h.
_SC_XBS5_LP64_OFF64
#define _SC_XBS5_LP64_OFF64 127
Definition at line 376 of file unistd.h.
_SC_XBS5_LPBIG_OFFBIG
#define _SC_XBS5_LPBIG_OFFBIG 128
Definition at line 377 of file unistd.h.
_SC_XOPEN_CRYPT
#define _SC_XOPEN_CRYPT 92
Definition at line 365 of file unistd.h.
_SC_XOPEN_ENH_I18N
#define _SC_XOPEN_ENH_I18N 93
Definition at line 366 of file unistd.h.
_SC_XOPEN_LEGACY
#define _SC_XOPEN_LEGACY 129
Definition at line 378 of file unistd.h.
_SC_XOPEN_REALTIME
#define _SC_XOPEN_REALTIME 130
Definition at line 379 of file unistd.h.
_SC_XOPEN_REALTIME_THREADS
#define _SC_XOPEN_REALTIME_THREADS 131
Definition at line 380 of file unistd.h.
_SC_XOPEN_SHM
#define _SC_XOPEN_SHM 94
Definition at line 367 of file unistd.h.
_SC_XOPEN_STREAMS
#define _SC_XOPEN_STREAMS 246
Definition at line 425 of file unistd.h.
_SC_XOPEN_UNIX
#define _SC_XOPEN_UNIX 91
Definition at line 364 of file unistd.h.
_SC_XOPEN_VERSION
#define _SC_XOPEN_VERSION 89
Definition at line 362 of file unistd.h.
_SC_XOPEN_XCU_VERSION
#define _SC_XOPEN_XCU_VERSION 90
Definition at line 363 of file unistd.h.
_SC_XOPEN_XPG2
#define _SC_XOPEN_XPG2 98
Definition at line 370 of file unistd.h.
_SC_XOPEN_XPG3
#define _SC_XOPEN_XPG3 99
Definition at line 371 of file unistd.h.
_SC_XOPEN_XPG4
#define _SC_XOPEN_XPG4 100
Definition at line 372 of file unistd.h.
_XOPEN_ENH_I18N
#define _XOPEN_ENH_I18N 1
Definition at line 215 of file unistd.h.
_XOPEN_UNIX
#define _XOPEN_UNIX 1
Definition at line 214 of file unistd.h.
_XOPEN_VERSION
#define _XOPEN_VERSION 700
Definition at line 213 of file unistd.h.
F_OK
#define F_OK 0
Definition at line 72 of file unistd.h.
NULL
#define NULL ((void*)0)
Definition at line 25 of file unistd.h.
POSIX_CLOSE_RESTART
#define POSIX_CLOSE_RESTART 0
Definition at line 211 of file unistd.h.
R_OK
#define R_OK 4
Definition at line 73 of file unistd.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 15 of file unistd.h.
SEEK_DATA
#define SEEK_DATA 3
Definition at line 17 of file unistd.h.
SEEK_END
#define SEEK_END 2
Definition at line 16 of file unistd.h.
SEEK_HOLE
#define SEEK_HOLE 4
Definition at line 18 of file unistd.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 14 of file unistd.h.
STDERR_FILENO
#define STDERR_FILENO 2
Definition at line 12 of file unistd.h.
STDIN_FILENO
#define STDIN_FILENO 0
Definition at line 10 of file unistd.h.
STDOUT_FILENO
#define STDOUT_FILENO 1
Definition at line 11 of file unistd.h.
W_OK
#define W_OK 2
Definition at line 74 of file unistd.h.
X_OK
#define X_OK 1
Definition at line 75 of file unistd.h.
Function Documentation
_exit()
_Noreturn void _exit (int Code)
Definition at line 28 of file ldstart.c.
 {
     __asm__ __volatile__("syscall"
                          :
                          : "a"(0), "D"(Code)
                          : "rcx", "r11", "memory");
     while (1)
         ;
 }
References __asm__(), __libc_fini_array(), __libc_fini_std(), _Exit(), Code, sc_exit, status, and syscall1().
Referenced by __attribute__(), __dls3(), _exit_SUCCESS(), child(), daemon(), do_wordexp(), doit(), exec_builtin(), exec_conf(), execvp_or_die(), exit(), fork_transformer(), forkpty(), ftpd_main(), gotsig(), handle_incoming_and_exit(), hush_exit(), hush_main(), inetd_main(), kill_myself_with_sig(), log_and_exit(), make_new_session(), onintr(), popen_ls(), processorstart(), pseudo_exec(), run(), run_pipe(), setup_heredoc(), spawn(), and xvfork_parent_waits_and_exits().
_Fork()
pid_t _Fork (void)
Definition at line 12 of file _Fork.c.
 {
     pid_t ret;
     sigset_t set;
     __block_all_sigs(&set);
     LOCK(__abort_lock);
 #ifdef SYS_fork
     ret = __syscall(SYS_fork);
 #else
     ret = __syscall(SYS_clone, SIGCHLD, 0);
 #endif
     if (!ret) {
         pthread_t self = __pthread_self();
         self->tid = __syscall(SYS_gettid);
         self->robust_list.off = 0;
         self->robust_list.pending = 0;
         self->next = self->prev = self;
         __thread_list_lock = 0;
         libc.threads_minus_1 = 0;
         if (libc.need_locks) libc.need_locks = -1;
     }
     UNLOCK(__abort_lock);
     if (!ret) __aio_atfork(1);
     __restore_sigs(&set);
     return __syscall_ret(ret);
 }
References __abort_lock, __aio_atfork(), __block_all_sigs(), __pthread_self, __restore_sigs(), __syscall, __syscall_ret(), __thread_list_lock, libc, LOCK, SIGCHLD, and UNLOCK.
Referenced by fork().
access()
int access (const char * filename, int amode)
Definition at line 5 of file access.c.
 {
 #ifdef SYS_access
     return syscall(SYS_access, filename, amode);
 #else
     return syscall(SYS_faccessat, AT_FDCWD, filename, amode, 0);
 #endif
 }
References AT_FDCWD, filename, and syscall().
Referenced by act(), dir_ok(), examine_file(), file_insert(), file_is_executable(), file_status(), find_in_path(), fuser_main(), handle_incoming_and_exit(), login_main(), mv_main(), remove_file(), run(), run_package_script_or_die(), run_pipe(), sem_open(), send_headers(), sh_eaccess(), stat_char(), switch_root_main(), sysctl_dots_to_slashes(), and touch().
alarm()
unsigned alarm (unsigned seconds)
Definition at line 5 of file alarm.c.
 {
     struct itimerval it = { .it_value.tv_sec = seconds }, old = { 0 };
     setitimer(ITIMER_REAL, &it, &old);
     return old.it_value.tv_sec + !!old.it_value.tv_usec;
 }
References itimerval::it_value, ITIMER_REAL, old, setitimer(), and timeval::tv_sec.
Referenced by alarm_handler(), alarm_intr(), arm(), askremotedate(), bb_ask_noecho(), catcher(), chat_main(), check_blocks(), cmdio_get_cmd_and_arg(), common_ping_main(), do_syslogd(), falarm(), get_line(), getty_main(), handle_incoming_and_exit(), inetd_mode(), init_tty_attrs(), login_main(), nc_main(), ntp_init(), ntpd_main(), pop3_checkr(), read_byte(), read_command(), rearm_alarm(), reset_alarm(), resize_main(), send_mail_command(), set_alarm(), showkey_main(), smtp_checkp(), timeout_handler(), and unarm().
chdir()
int chdir (const char * path)
Definition at line 4 of file chdir.c.
 {
     return syscall(SYS_chdir, path);
 }
References syscall().
Referenced by builtin_cd(), chdir_or_warn(), com_cd(), daemon(), docd(), handle_cwd(), load_firmware(), lpd_main(), lsscsi_main(), main(), process_includes(), and runsvdir_main().
chown()
int chown (const char * path, uid_t uid, gid_t gid)
Definition at line 5 of file chown.c.
 {
 #ifdef SYS_chown
     return syscall(SYS_chown, path, uid, gid);
 #else
     return syscall(SYS_fchownat, AT_FDCWD, path, uid, gid, 0);
 #endif
 }
References AT_FDCWD, and syscall().
Referenced by action_permissions(), adduser_main(), copy_file(), copy_inode(), data_extract_all(), history_do_write(), history_truncate_file(), and make_device().
close()
int close (int fd)
Definition at line 13 of file close.c.
 {
     fd = __aio_close(fd);
     int r = __syscall_cp(SYS_close, fd);
     if (r == -EINTR) r = 0;
     return __syscall_ret(r);
 }
References __aio_close(), __syscall_cp, __syscall_ret(), EINTR, and fd.
Referenced by __dls3(), __lookup_name(), __nscd_query(), __res_msend_rc(), _evalfile(), _nl_load_domain(), _rl_read_file(), _vsyslog(), accept_builtin(), acpid_main(), archivefile(), arpping(), askremotedate(), async_redirect_stdin(), awk_main(), bb_cat(), bb_daemonize_or_rexec(), bb_init_module(), beep_main(), blkdiscard_main(), blockdev_main(), brctl_main(), cat_file(), cat_main(), change_attributes(), change_listen_mode(), chat_main(), check_dev_tty(), check_mount(), child(), chpst_main(), cksum_main(), clean_up_and_exit(), cleanup(), close_fd_bitmap(), close_pipes(), closedir(), closelog(), closescript(), command_substitute(), common_ping_main(), ConfigMainWindow::ConfigMainWindow(), conspy_main(), copy_file(), copy_inode(), create_cdev_if_doesnt_exist(), crontab_main(), cttyhack_main(), cutfile(), d6_read_interface(), d6_send_kernel_packet_from_client_data_ifindex(), d6_send_raw_packet_from_client_data_ifindex(), daemon(), data_extract_all(), data_extract_to_command(), deb_extract_control_file_to_buffer(), del_loop(), delete_tempfile(), devmem_main(), dialog_textbox(), diffreg(), do_add_ioctl(), do_changename(), do_chflags(), do_config_file(), do_del_ioctl(), do_get_ioctl(), do_io_until_eof_and_exit(), do_ioctl_get_ifindex(), do_ioctl_get_ifname(), do_ioctl_get_iftype(), do_logging(), do_nftw(), do_piping(), do_redirection_internal(), do_syslogd(), do_wordexp(), dolisten(), download_one_url(), dpkg_deb_main(), dprintf(), dump_file(), dump_procs(), dumpkmap_main(), dup2(), edir(), eject_main(), ether_wake_main(), evalbackcmd(), evalpipe(), exec_conf(), execute_pipeline(), expbackq(), extract_info(), fail_hunk(), fatattr_main(), fb_open(), fbset_main(), fdformat_main(), fdisk_main(), file_insert(), file_write(), filter_rename_config(), flash_eraseall_main(), fmtmsg(), fork_transformer(), forkchild(), forkpty(), free_volume_id(), freeramdisk_main(), from_sys_clock(), fstrim_main(), ftpd_main(), get_address(), get_boot(), get_console_fd_or_die(), get_free_loop(), get_terminal_width_height(), getaddrinfo(), getpass(), getspnam_r(), getty_main(), handle_dir_common(), handle_retr(), hash_file(), here_document_to_fd(), hfclose(), history_do_write(), history_truncate_file(), if_fetch(), if_readconf(), ifconfig_main(), INET_setroute(), inetd_main(), iproute_flush_cache(), is_whole_disk(), isrv_close_fd(), kbd_mode_main(), klogd_close(), last_main(), launch_helper(), list_attributes(), load_firmware(), load_library(), loadkmap_main(), log_locally(), logdir_close(), login_tty(), lpd_main(), lpqr_main(), make_new_session(), maybe_close(), microcom_main(), mini_httpd_nommu(), mkfs_ext2_main(), mkfs_vfat_main(), mkswap_main(), mktemp_builtin(), motd(), move_to_high_fd(), nandwrite_main(), nbdclient_main(), nc_main(), noclobber_open(), nohup_main(), nsenter_main(), ntpd_main(), open_shell_script(), open_stdio_to_tty(), open_tty(), openhere(), openpty(), openredirect(), openvt_main(), optimize_cat_file(), parse(), parse_comsub(), parse_matched_pair(), partprobe_main(), patch_main(), popen_ls(), popfile(), popredir(), port_pasv_cleanup(), posix_close(), posix_spawn(), prepare_socket_fd(), print_deps(), print_queuelen(), processorstart(), pscan_main(), pthread_getname_np(), pthread_setname_np(), pump_data_and_QUIT(), query_loop(), read_close(), read_history_range(), read_leases(), read_new_seed(), read_rtc(), read_to_buf(), readahead_main(), readfile_z(), readLines(), readprofile_main(), readwrite(), recv_and_process_peer_pkt(), redirect(), refill_HFILE_and_getc(), restart_job_control(), restore_redirects(), restore_state_and_exit(), restore_stdin(), rtcwake_main(), run_pipe(), runsv_main(), rx_main(), savefd(), scan_proc_net_or_maps(), screen_read_close(), script_main(), scriptreplay_main(), seed_from_file_if_exists(), sem_open(), send_query_to_peer(), serial_ctl(), set_address(), set_loop(), set_mtu(), set_qlen(), setup_heredoc(), setup_redirects(), sh_closepipe(), sh_mktmpfp(), show_textbox(), shutdown_watchdog(), singlemount(), skip_matched_pair(), start(), start_shell_in_child(), start_tcp(), startservice(), step_time(), sulogin_main(), sum_file(), sysctl_act_on_setting(), tar_main(), tcpudpsvd_main(), tee_builtin(), telnetd_main(), tgetent(), touch(), tsort_main(), ubi_tools_main(), udhcp_read_interface(), udhcp_send_kernel_packet(), udhcp_send_raw_packet(), udhcpd_main(), uevent_main(), uniq_main(), unshare_main(), unzip_main(), update_status(), urandom_close(), volname_main(), wait_for_seqfile(), wall_main(), watch_main(), write_leases(), write_pidfile(), writeLines(), xclose(), xconnect(), xdup_CLOEXEC_and_close(), xmalloc_open_read_close(), xmove_fd(), xopen_xwrite_close(), xsendto(), and xtrace_reset().
confstr()
size_t confstr (int name, char * buf, size_t len)
Definition at line 5 of file confstr.c.
 {
     const char *s = "";
     if (!name) {
         s = "/bin:/usr/bin";
     } else if ((name&~4U)!=1 && name-_CS_POSIX_V6_ILP32_OFF32_CFLAGS>35U) {
         errno = EINVAL;
         return 0;
     }
     // snprintf is overkill but avoid wasting code size to implement
     // this completely useless function and its truncation semantics
     return snprintf(buf, len, "%s", s) + 1;
 }
References _CS_POSIX_V6_ILP32_OFF32_CFLAGS, buf, EINVAL, errno, len, s, and snprintf().
Referenced by conf_standard_path(), and getconf_print().
ctermid()
char* ctermid (char * s)
Definition at line 4 of file ctermid.c.
 {
     return s ? strcpy(s, "/dev/tty") : "/dev/tty";
 }
References s, and strcpy.
dup()
int dup (int fd)
Definition at line 4 of file dup.c.
 {
     return syscall(SYS_dup, fd);
 }
References fd, and syscall().
Referenced by bb_daemonize_or_rexec(), dprintf(), hush_main(), initialize_job_control(), popen_ls(), print_builtin(), sulogin_main(), tre_make_trans(), and xargs_main().
dup2()
int dup2 (int fd1, int fd2)
Definition at line 88 of file oslib.c.
 {
   int saved_errno, r;
   /* If FD1 is not a valid file descriptor, then return immediately with
      an error. */
   if (fcntl (fd1, F_GETFL, 0) == -1)
     return (-1);
   if (fd2 < 0 || fd2 >= getdtablesize ())
     {
       errno = EBADF;
       return (-1);
     }
   if (fd1 == fd2)
     return (0);
   saved_errno = errno;
   (void) close (fd2);
   r = fcntl (fd1, F_DUPFD, fd2);
   if (r >= 0)
     errno = saved_errno;
   else
     if (errno == EINVAL)
       errno = EBADF;
   /* Force the new file descriptor to remain open across exec () calls. */
   SET_OPEN_ON_EXEC (fd2);
   return (r);
 }
References __syscall, __syscall_ret(), close(), EBADF, EBUSY, EINVAL, errno, F_DUPFD, F_GETFD, F_GETFL, fcntl(), getdtablesize(), old, saved_errno, SET_OPEN_ON_EXEC, and Module::void().
Referenced by async_redirect_stdin(), bb_daemonize_or_rexec(), command_substitute(), console_init(), cttyhack_main(), custom(), daemon(), do_piping(), do_redirection_internal(), do_wordexp(), doexec(), dup2_or_raise(), evalpipe(), exec_conf(), login_tty(), main(), move_to_high_fd(), nohup_main(), open_shell_script(), open_stdio_to_tty(), restore_stdin(), runsvdir_main(), and xdup2().
dup3()
int dup3 (int , int , int)
execl()
int execl (const char * pathname, const char * arg, ...)
Definition at line 6 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ap, argc, argv, execv(), i, NULL, va_arg, va_end, and va_start.
execle()
int execle (const char * pathname, const char * arg, ...)
Definition at line 18 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ap, argc, argv, execve(), i, va_arg, va_end, and va_start.
execlp()
int execlp (const char * file, const char * arg, ...)
Definition at line 12 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References ap, argc, argv, execvp(), i, NULL, va_arg, va_end, and va_start.
execv()
int execv (const char * pathname, char * const argv[])
Definition at line 24 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References __environ, argv, and execve().
execve()
int execve (const char * pathname, char * const argv[], char * const envp[])
Definition at line 42 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References argv, and syscall().
execvp()
int execvp (const char * file, char * const argv[])
Definition at line 30 of file exe.c.
 {
     errno = ENOSYS;
     return -1;
 }
References __environ, __execvpe(), and argv.
faccessat()
int faccessat (int fd, const char * filename, int amode, int flag)
Definition at line 26 of file faccessat.c.
 {
     if (flag) {
         int ret = __syscall(SYS_faccessat2, fd, filename, amode, flag);
         if (ret != -ENOSYS) return __syscall_ret(ret);
     }
     if (flag & ~AT_EACCESS)
         return __syscall_ret(-EINVAL);
     if (!flag || (getuid()==geteuid() && getgid()==getegid()))
         return syscall(SYS_faccessat, fd, filename, amode);
     char stack[1024];
     sigset_t set;
     pid_t pid;
     int status;
     int ret, p[2];
     if (pipe2(p, O_CLOEXEC)) return __syscall_ret(-EBUSY);
     struct ctx c = { .fd = fd, .filename = filename, .amode = amode, .p = p[1] };
     __block_all_sigs(&set);
     pid = __clone(checker, stack+sizeof stack, 0, &c);
     __syscall(SYS_close, p[1]);
     if (pid<0 || __syscall(SYS_read, p[0], &ret, sizeof ret) != sizeof(ret))
         ret = -EBUSY;
     __syscall(SYS_close, p[0]);
     __syscall(SYS_wait4, pid, &status, __WCLONE, 0);
     __restore_sigs(&set);
     return __syscall_ret(ret);
 }
References __block_all_sigs(), __clone(), __restore_sigs(), __syscall, __syscall_ret(), __WCLONE, ctx::amode, AT_EACCESS, c, checker(), EBUSY, EINVAL, ENOSYS, fd, filename, getegid, geteuid, getgid, getuid, O_CLOEXEC, p, pid, pipe2(), ctx::ret, stack, status, and syscall().
Referenced by euidaccess(), and sh_eaccess().
fchdir()
int fchdir (int fd)
Definition at line 6 of file fchdir.c.
 {
     int ret = __syscall(SYS_fchdir, fd);
     if (ret != -EBADF || __syscall(SYS_fcntl, fd, F_GETFD) < 0)
         return __syscall_ret(ret);
     char buf[15+3*sizeof(int)];
     __procfdname(buf, fd);
     return syscall(SYS_chdir, buf);
 }
References __procfdname(), __syscall, __syscall_ret(), buf, EBADF, F_GETFD, fd, and syscall().
Referenced by buffer_pwrite(), ftpd_main(), logdir_open(), popen_ls(), process_includes(), processorstop(), rotate(), runsv_main(), runsvdir_main(), and xfchdir().
fchown()
int fchown (int fd, uid_t uid, gid_t gid)
Definition at line 6 of file fchown.c.
 {
     int ret = __syscall(SYS_fchown, fd, uid, gid);
     if (ret != -EBADF || __syscall(SYS_fcntl, fd, F_GETFD) < 0)
         return __syscall_ret(ret);
     char buf[15+3*sizeof(int)];
     __procfdname(buf, fd);
 #ifdef SYS_chown
     return syscall(SYS_chown, buf, uid, gid);
 #else
     return syscall(SYS_fchownat, AT_FDCWD, buf, uid, gid, 0);
 #endif
 }
References __procfdname(), __syscall, __syscall_ret(), AT_FDCWD, buf, EBADF, F_GETFD, fd, and syscall().
Referenced by convert(), crontab_main(), login_main(), open_tty(), sed_main(), and update_passwd().
fchownat()
int fchownat (int fd, const char * path, uid_t uid, gid_t gid, int flag)
Definition at line 4 of file fchownat.c.
 {
     return syscall(SYS_fchownat, fd, path, uid, gid, flag);
 }
References fd, and syscall().
fdatasync()
int fdatasync (int fd)
Definition at line 4 of file fdatasync.c.
 {
     return syscall_cp(SYS_fdatasync, fd);
 }
References fd, and syscall_cp.
Referenced by io_thread_func(), and shred_main().
fexecve()
int fexecve (int fd, char * const argv[], char * const envp[])
Definition at line 7 of file fexecve.c.
 {
     int r = __syscall(SYS_execveat, fd, "", argv, envp, AT_EMPTY_PATH);
     if (r != -ENOSYS) return __syscall_ret(r);
     char buf[15 + 3*sizeof(int)];
     __procfdname(buf, fd);
     execve(buf, argv, envp);
     if (errno == ENOENT) errno = EBADF;
     return -1;
 }
References __procfdname(), __syscall, __syscall_ret(), argv, buf, EBADF, ENOENT, ENOSYS, errno, execve(), and fd.
fork()
pid_t fork (void)
Definition at line 48 of file exe.c.
 {
     return syscall0(sc_fork);
 }
References __aio_atfork(), __block_app_sigs(), __fork_handler(), __inhibit_ptc(), __ldso_atfork(), __malloc_atfork(), __pthread_key_atfork(), __pthread_self, __release_ptc(), __restore_sigs(), __tl_lock(), __tl_unlock(), __vmlock_lockptr, _Fork(), atfork_locks, errno, i, if(), libc, LOCK, next, td, and UNLOCK.
Referenced by daemon(), do_wordexp(), exec_conf(), exec_kernel_doc(), forkpty(), forkshell(), inetd_main(), main(), make_child(), nbdclient_main(), run(), run_pipe(), and spawn_and_wait().
fpathconf()
long fpathconf (int fd, int name)
Definition at line 5 of file fpathconf.c.
 {
     static const short values[] = {
         [_PC_LINK_MAX] = _POSIX_LINK_MAX,
         [_PC_MAX_CANON] = _POSIX_MAX_CANON,
         [_PC_MAX_INPUT] = _POSIX_MAX_INPUT,
         [_PC_NAME_MAX] = NAME_MAX,
         [_PC_PATH_MAX] = PATH_MAX,
         [_PC_PIPE_BUF] = PIPE_BUF,
         [_PC_CHOWN_RESTRICTED] = 1,
         [_PC_NO_TRUNC] = 1,
         [_PC_VDISABLE] = 0,
         [_PC_SYNC_IO] = 1,
         [_PC_ASYNC_IO] = -1,
         [_PC_PRIO_IO] = -1,
         [_PC_SOCK_MAXBUF] = -1,
         [_PC_FILESIZEBITS] = FILESIZEBITS,
         [_PC_REC_INCR_XFER_SIZE] = 4096,
         [_PC_REC_MAX_XFER_SIZE] = 4096,
         [_PC_REC_MIN_XFER_SIZE] = 4096,
         [_PC_REC_XFER_ALIGN] = 4096,
         [_PC_ALLOC_SIZE_MIN] = 4096,
         [_PC_SYMLINK_MAX] = -1,
         [_PC_2_SYMLINKS] = 1
     };
     if (name >= sizeof(values)/sizeof(values[0])) {
         errno = EINVAL;
         return -1;
     }
     return values[name];
 }
References _PC_2_SYMLINKS, _PC_ALLOC_SIZE_MIN, _PC_ASYNC_IO, _PC_CHOWN_RESTRICTED, _PC_FILESIZEBITS, _PC_LINK_MAX, _PC_MAX_CANON, _PC_MAX_INPUT, _PC_NAME_MAX, _PC_NO_TRUNC, _PC_PATH_MAX, _PC_PIPE_BUF, _PC_PRIO_IO, _PC_REC_INCR_XFER_SIZE, _PC_REC_MAX_XFER_SIZE, _PC_REC_MIN_XFER_SIZE, _PC_REC_XFER_ALIGN, _PC_SOCK_MAXBUF, _PC_SYMLINK_MAX, _PC_SYNC_IO, _PC_VDISABLE, _POSIX_LINK_MAX, _POSIX_MAX_CANON, _POSIX_MAX_INPUT, EINVAL, errno, NAME_MAX, PATH_MAX, and PIPE_BUF.
Referenced by pathconf().
fsync()
int fsync (int fd)
Definition at line 4 of file fsync.c.
 {
     return syscall_cp(SYS_fsync, fd);
 }
References fd, and syscall_cp.
Referenced by io_thread_func(), logdir_close(), mkswap_main(), rotate(), seed_from_file_if_exists(), seedrng_main(), and update_passwd().
ftruncate()
int ftruncate (int fd, off_t length)
Definition at line 4 of file ftruncate.c.
 {
     return syscall(SYS_ftruncate, fd, __SYSCALL_LL_O(length));
 }
References __SYSCALL_LL_O, fd, and syscall().
Referenced by dd_main(), file_write(), hexedit_main(), history_do_write(), retrieve_file_data(), shred_main(), and truncate_main().
getcwd()
char* getcwd (char * buf, size_t size)
Definition at line 110 of file getcwd.c.
 {
   static const char dots[]
     = "../../../../../../../../../../../../../../../../../../../../../../../\
 ../../../../../../../../../../../../../../../../../../../../../../../../../../\
 ../../../../../../../../../../../../../../../../../../../../../../../../../..";
   const char *dotp, *dotlist;
   size_t dotsize;
   dev_t rootdev, thisdev;
   ino_t rootino, thisino;
   char path[PATH_MAX + 1];
   register char *pathp;
   char *pathbuf;
   size_t pathsize;
   struct stat st;
   int saved_errno;
   if (buf != NULL && size == 0)
     {
       errno = EINVAL;
       return ((char *)NULL);
     }
   pathsize = sizeof (path);
   pathp = &path[pathsize];
   *--pathp = '\0';
   pathbuf = path;
   if (stat (".", &st) < 0)
     return ((char *)NULL);
   thisdev = st.st_dev;
   thisino = st.st_ino;
   if (stat ("/", &st) < 0)
     return ((char *)NULL);
   rootdev = st.st_dev;
   rootino = st.st_ino;
   saved_errno = 0;
   dotsize = sizeof (dots) - 1;
   dotp = &dots[sizeof (dots)];
   dotlist = dots;
   while (!(thisdev == rootdev && thisino == rootino))
     {
       register DIR *dirstream;
       register struct dirent *d;
       dev_t dotdev;
       ino_t dotino;
       char mount_point;
       int namlen;
       /* Look at the parent directory.  */
       if (dotp == dotlist)
     {
       /* My, what a deep directory tree you have, Grandma.  */
       char *new;
       if (dotlist == dots)
         {
           new = (char *)malloc (dotsize * 2 + 1);
           if (new == NULL)
         goto lose;
           memcpy (new, dots, dotsize);
         }
       else
         {
           new = (char *)realloc ((PTR_T) dotlist, dotsize * 2 + 1);
           if (new == NULL)
         goto lose;
         }
       memcpy (&new[dotsize], new, dotsize);
       dotp = &new[dotsize];
       dotsize *= 2;
       new[dotsize] = '\0';
       dotlist = new;
     }
       dotp -= 3;
       /* Figure out if this directory is a mount point.  */
       if (stat (dotp, &st) < 0)
     goto lose;
       dotdev = st.st_dev;
       dotino = st.st_ino;
       mount_point = dotdev != thisdev;
       /* Search for the last directory.  */
       dirstream = opendir (dotp);
       if (dirstream == NULL)
     goto lose;
       while ((d = readdir (dirstream)) != NULL)
     {
       if (d->d_name[0] == '.' &&
           (d->d_name[1] == '\0' ||
         (d->d_name[1] == '.' && d->d_name[2] == '\0')))
         continue;
 #if defined (D_FILENO_AVAILABLE)
       if (mount_point || d->d_fileno == thisino)
 #else
       if (mount_point || _path_checkino (dotp, d->d_name, thisino))
 #endif
         {
           char *name;
           namlen = D_NAMLEN(d);
           name = (char *)
         alloca (dotlist + dotsize - dotp + 1 + namlen + 1);
           memcpy (name, dotp, dotlist + dotsize - dotp);
           name[dotlist + dotsize - dotp] = '/';
           memcpy (&name[dotlist + dotsize - dotp + 1],
               d->d_name, namlen + 1);
           if (lstat (name, &st) < 0)
         {
 #if 0
           int save = errno;
           (void) closedir (dirstream);
           errno = save;
           goto lose;
 #else
           saved_errno = errno;
 #endif
         }
           if (st.st_dev == thisdev && st.st_ino == thisino)
         break;
         }
     }
       if (d == NULL)
     {
 #if 0
       int save = errno;
 #else
       int save = errno ? errno : saved_errno;
 #endif
       (void) closedir (dirstream);
       errno = save;
       goto lose;
     }
       else
     {
       size_t space;
       while ((space = pathp - pathbuf) <= namlen)
         {
           char *new;
           if (pathbuf == path)
         {
           new = (char *)malloc (pathsize * 2);
           if (!new)
             goto lose;
         }
           else
         {
           new = (char *)realloc ((PTR_T) pathbuf, (pathsize * 2));
           if (!new)
             goto lose;
           pathp = new + space;
         }
           (void) memcpy (new + pathsize + space, pathp, pathsize - space);
           pathp = new + pathsize + space;
           pathbuf = new;
           pathsize *= 2;
         }
       pathp -= namlen;
       (void) memcpy (pathp, d->d_name, namlen);
       *--pathp = '/';
       (void) closedir (dirstream);
     }
       thisdev = dotdev;
       thisino = dotino;
     }
   if (pathp == &path[sizeof(path) - 1])
     *--pathp = '/';
   if (dotlist != dots)
     free ((PTR_T) dotlist);
   {
     size_t len = pathbuf + pathsize - pathp;
     if (buf == NULL && size <= 0)
       size = len;
     if ((size_t) size < len)
       {
     errno = ERANGE;
     goto lose2;
       }
     if (buf == NULL)
       {
     buf = (char *) malloc (size);
     if (buf == NULL)
       goto lose2;
       }
     (void) memcpy((PTR_T) buf, (PTR_T) pathp, len);
   }
   if (pathbuf != path)
     free (pathbuf);
   return (buf);
  lose:
   if ((dotlist != dots) && dotlist)
     {
       int e = errno;
       free ((PTR_T) dotlist);
       errno = e;
     }
  lose2:
   if ((pathbuf != path) && pathbuf)
     {
       int e = errno;
       free ((PTR_T) pathbuf);
       errno = e;
     }
   return ((char *)NULL);
 }
References _path_checkino(), alloca, buf, closedir(), dirent::d_name, D_NAMLEN, dev_t, EINVAL, ENOENT, ERANGE, errno, free, ino_t, len, lstat, malloc, memcpy, mount_point, NULL, opendir(), PATH_MAX, PTR_T, readdir(), realloc, saved_errno, size, strdup(), syscall(), and Module::void().
getegid()
gid_t getegid (void)
Definition at line 4 of file getegid.c.
 {
     return __syscall(SYS_getegid);
 }
References __syscall.
geteuid()
uid_t geteuid (void)
Definition at line 4 of file geteuid.c.
 {
     return __syscall(SYS_geteuid);
 }
References __syscall.
getgid()
gid_t getgid (void)
Definition at line 4 of file getgid.c.
 {
     return __syscall(SYS_getgid);
 }
References __syscall.
getgroups()
int getgroups (int count, gid_t list[])
Definition at line 4 of file getgroups.c.
 {
     return syscall(SYS_getgroups, count, list);
 }
References count, list(), and syscall().
Referenced by bb_getgroups(), get_groups(), and initialize_group_array().
gethostname()
int gethostname (char * name, size_t namelen)
Definition at line 215 of file oslib.c.
 {
   strncpy (name, "unknown", namelen);
   name[namelen] = '\0';
   return 0;
 }
References i, len, namelen, utsname::nodename, strncpy(), and uname().
Referenced by shell_initialize().
getlogin()
char* getlogin (void)
Definition at line 4 of file getlogin.c.
 {
     return getenv("LOGNAME");
 }
References getenv.
Referenced by get_current_user_info(), getlogin_r(), logname_builtin(), and sh_get_home_dir().
getlogin_r()
int getlogin_r (char * name, size_t size)
Definition at line 5 of file getlogin_r.c.
 {
     char *logname = getlogin();
     if (!logname) return ENXIO; /* or...? */
     if (strlen(logname) >= size) return ERANGE;
     strcpy(name, logname);
     return 0;
 }
References ENXIO, ERANGE, getlogin(), size, strcpy, and strlen().
Referenced by logname_main(), and su_main().
getopt()
int getopt (int argc, char * const argv[], const char * optstring)
Definition at line 28 of file getopt.c.
 {
     int i;
     wchar_t c, d;
     int k, l;
     char *optchar;
     if (!optind || __optreset) {
         __optreset = 0;
         __optpos = 0;
         optind = 1;
     }
     if (optind >= argc || !argv[optind])
         return -1;
     if (argv[optind][0] != '-') {
         if (optstring[0] == '-') {
             optarg = argv[optind++];
             return 1;
         }
         return -1;
     }
     if (!argv[optind][1])
         return -1;
     if (argv[optind][1] == '-' && !argv[optind][2])
         return optind++, -1;
     if (!optpos) optpos++;
     if ((k = mbtowc(&c, argv[optind]+optpos, MB_LEN_MAX)) < 0) {
         k = 1;
         c = 0xfffd; /* replacement char */
     }
     optchar = argv[optind]+optpos;
     optpos += k;
     if (!argv[optind][optpos]) {
         optind++;
         optpos = 0;
     }
     if (optstring[0] == '-' || optstring[0] == '+')
         optstring++;
     i = 0;
     d = 0;
     do {
         l = mbtowc(&d, optstring+i, MB_LEN_MAX);
         if (l>0) i+=l; else i++;
     } while (l && d != c);
     if (d != c || c == ':') {
         optopt = c;
         if (optstring[0] != ':' && opterr)
             __getopt_msg(argv[0], ": unrecognized option: ", optchar, k);
         return '?';
     }
     if (optstring[i] == ':') {
         optarg = 0;
         if (optstring[i+1] != ':' || optpos) {
             optarg = argv[optind++];
             if (optpos) optarg += optpos;
             optpos = 0;
         }
         if (optind > argc) {
             optopt = c;
             if (optstring[0] == ':') return ':';
             if (opterr) __getopt_msg(argv[0],
                 ": option requires an argument: ",
                 optchar, k);
             return '?';
         }
     }
     return c;
 }
Referenced by generate_output().
getpgid()
pid_t getpgid (pid_t pid)
Definition at line 4 of file getpgid.c.
 {
     return syscall(SYS_getpgid, pid);
 }
References pid, and syscall().
getpgrp()
pid_t getpgrp (void)
Definition at line 4 of file getpgrp.c.
 {
     return __syscall(SYS_getpgid, 0);
 }
getpid()
pid_t getpid (void)
Definition at line 4 of file getpid.c.
 {
     return __syscall(SYS_getpid);
 }
References __syscall.
Referenced by _rl_handle_signal(), _vsyslog(), ash_main(), assign_random(), bootchartd_main(), builtin_exec(), cleanup(), command_substitute(), common_ping_main(), conf_write(), crontab_main(), crypt_make_salt(), data_extract_all(), expand_variable(), forkchild(), free_pipe(), ftpd_main(), generate_uuid(), genseed(), get_bashpid(), get_mypid(), get_random_number(), get_tty_state(), getty_main(), give_terminal_to(), history_tempfile(), hush_main(), init_main(), initialize_job_control(), initialize_shell_variables(), kill_main(), kill_shell(), lockf(), login_main(), lpqr_main(), lsof_main(), main(), make_child(), make_new_session(), maybe_give_terminal_to(), mdev_main(), microcom_main(), next_random(), notify_signal(), ntp_init(), parse(), pgrep_main(), popmaildir_main(), push_builtin(), re_execute_shell(), run(), run_pending_traps(), run_pipe(), runsvdir_main(), set_tty_state(), sh_seedrand(), sigcont_sighandler(), sigqueue(), sigstop_sighandler(), start_shell_in_child(), sulogin_main(), switch_root_main(), tcpudpsvd_main(), tls_run_copy_loop(), traceroute_init(), trap_handler(), unshare_main(), vi_main(), wait_for(), wait_sigint_handler(), and write_pidfile().
getppid()
pid_t getppid (void)
Definition at line 4 of file getppid.c.
 {
     return __syscall(SYS_getppid);
 }
References __syscall.
Referenced by do_logging(), genseed(), hush_main(), init(), pidof_main(), set_ppid(), and timeout_main().
getsid()
pid_t getsid (pid_t pid)
Definition at line 4 of file getsid.c.
 {
     return syscall(SYS_getsid, pid);
 }
References pid, and syscall().
Referenced by getty_main(), kill_main(), and pgrep_main().
getuid()
uid_t getuid (void)
Definition at line 4 of file getuid.c.
 {
     return __syscall(SYS_getuid);
 }
References __syscall.
isatty()
int isatty (int fd)
Definition at line 6 of file isatty.c.
 {
     struct winsize wsz;
     unsigned long r = syscall(SYS_ioctl, fd, TIOCGWINSZ, &wsz);
     if (r == 0) return 1;
     if (errno != EBADF) errno = ENOTTY;
     return 0;
 }
References EBADF, ENOTTY, errno, fd, syscall(), and TIOCGWINSZ.
Referenced by _rl_input_available(), bb_progress_update(), bbunpack(), check_mount(), cryptpw_main(), fsck_minix_main(), get_cred_or_die(), get_terminal_width_height(), hdparm_main(), hush_main(), I_ConsoleStdout(), initialize_job_control(), isnetconn(), less_main(), login_main(), ls_main(), main(), man_main(), mesg_main(), microcom_main(), more_main(), mv_main(), nohup_main(), open_shell_script(), primary(), procargs(), remove_file(), reset_main(), rl_gather_tyi(), rl_getc(), shell_builtin_read(), ttyname_r(), and unary_test().
lchown()
int lchown (const char * path, uid_t uid, gid_t gid)
Definition at line 5 of file lchown.c.
 {
 #ifdef SYS_lchown
     return syscall(SYS_lchown, path, uid, gid);
 #else
     return syscall(SYS_fchownat, AT_FDCWD, path, uid, gid, AT_SYMLINK_NOFOLLOW);
 #endif
 }
References AT_FDCWD, AT_SYMLINK_NOFOLLOW, and syscall().
Referenced by copy_file(), and install_main().
link()
int link (const char * existing, const char * new)
Definition at line 5 of file link.c.
 {
 #ifdef SYS_link
     return syscall(SYS_link, existing, new);
 #else
     return syscall(SYS_linkat, AT_FDCWD, existing, AT_FDCWD, new, 0);
 #endif
 }
References AT_FDCWD, and syscall().
Referenced by copy_file(), create_links_from_list(), link_main(), ln_builtin(), ln_main(), P_SetThingPosition(), rename(), sem_open(), and update_passwd().
linkat()
int linkat (int fd1, const char * existing, int fd2, const char * new, int flag)
Definition at line 4 of file linkat.c.
 {
     return syscall(SYS_linkat, fd1, existing, fd2, new, flag);
 }
References syscall().
lseek()
off_t lseek (int fd, off_t offset, int whence)
Definition at line 88 of file kernel_io.cpp.
 {
     if (!CheckForScheduler())
         return -ENOSYS;
     PCB *pcb = thisProcess;
     FileDescriptorTable *fdt = pcb->FileDescriptors;
     off_t r = fdt->_lseek(fd, offset, whence);
     return r;
 }
pathconf()
long pathconf (const char * path, int name)
Definition at line 3 of file pathconf.c.
 {
     return fpathconf(-1, name);
 }
References fpathconf().
Referenced by get_tmpdir(), and getconf_print().
pause()
int pause (void)
Definition at line 4 of file pause.c.
 {
 #ifdef SYS_pause
     return syscall_cp(SYS_pause);
 #else
     return syscall_cp(SYS_ppoll, 0, 0, 0, 0);
 #endif
 }
References SYS_ppoll, and syscall_cp.
Referenced by dialog_msgbox(), and main_loop().
pipe()
int pipe (int fd[2])
Definition at line 4 of file pipe.c.
 {
 #ifdef SYS_pipe
     return syscall(SYS_pipe, fd);
 #else
     return syscall(SYS_pipe2, fd, 0);
 #endif
 }
References fd, and syscall().
Referenced by evalbackcmd(), evalpipe(), exec_conf(), openhere(), pipe2(), and xpipe().
pipe2()
int pipe2 (int fd[2], int flag)
Definition at line 6 of file pipe2.c.
 {
     if (!flag) return pipe(fd);
     int ret = __syscall(SYS_pipe2, fd, flag);
     if (ret != -ENOSYS) return __syscall_ret(ret);
     if (flag & ~(O_CLOEXEC|O_NONBLOCK)) return __syscall_ret(-EINVAL);
     ret = pipe(fd);
     if (ret) return ret;
     if (flag & O_CLOEXEC) {
         __syscall(SYS_fcntl, fd[0], F_SETFD, FD_CLOEXEC);
         __syscall(SYS_fcntl, fd[1], F_SETFD, FD_CLOEXEC);
     }
     if (flag & O_NONBLOCK) {
         __syscall(SYS_fcntl, fd[0], F_SETFL, O_NONBLOCK);
         __syscall(SYS_fcntl, fd[1], F_SETFL, O_NONBLOCK);
     }
     return 0;
 }
References __syscall, __syscall_ret(), EINVAL, ENOSYS, F_SETFD, F_SETFL, fd, FD_CLOEXEC, O_CLOEXEC, O_NONBLOCK, and pipe().
Referenced by do_wordexp(), faccessat(), forkpty(), popen(), and posix_spawn().
posix_close()
int posix_close (int fd, int flags)
Definition at line 3 of file posix_close.c.
 {
     return close(fd);
 }
References close(), and fd.
pread()
ssize_t pread (int fd, void * buf, size_t size, off_t ofs)
Definition at line 4 of file pread.c.
 {
     return syscall_cp(SYS_pread, fd, buf, size, __SYSCALL_LL_PRW(ofs));
 }
References __SYSCALL_LL_PRW, buf, fd, size, and syscall_cp.
Referenced by io_thread_func(), map_library(), and wait_for_seqfile().
pwrite()
ssize_t pwrite (int fd, const void * buf, size_t size, off_t ofs)
Definition at line 4 of file pwrite.c.
 {
     return syscall_cp(SYS_pwrite, fd, buf, size, __SYSCALL_LL_PRW(ofs));
 }
References __SYSCALL_LL_PRW, buf, fd, size, and syscall_cp.
Referenced by io_thread_func().
read()
ssize_t read (int fd, void * buf, size_t count)
Definition at line 4 of file read.c.
 {
     return syscall_cp(SYS_read, fd, buf, count);
 }
References buf, count, fd, and syscall_cp.
Referenced by _evalfile(), _nl_load_domain(), _rl_read_file(), back_lines(), bb_ask_noecho(), con_escape(), conspy_main(), dialog_textbox(), do_check(), do_io_until_eof_and_exit(), do_servicing(), do_syslogd(), eventfd_read(), exec_conf(), expbackq(), extract_info(), fcopy(), forkpty(), get_bits(), get_header_ar(), get_line(), get_logname(), get_rawline(), getc_with_restart(), getpass(), getrandom(), gobble_line(), history_truncate_file(), io_thread_func(), klogd_read(), map_library(), mkfs_vfat_main(), mmap_fixed(), open_shell_script(), posix_spawn(), pthread_getname_np(), read_byte(), read_history_range(), read_key(), read_loop(), read_tables(), read_to_buf(), readfile_z(), readwrite(), rl_gather_tyi(), rl_getc(), runsv_main(), runsvdir_main(), safe_read(), shell_builtin_read(), showkey_main(), tee_builtin(), unshare_main(), vswscanf(), zread(), zreadintr(), and zreadretry().
readlink()
ssize_t readlink (const char * __restrict, char * __restrict, size_t)
Referenced by _path_readlink(), copy_inode(), fixup_rpath(), histfile_backup(), histfile_restore(), history_backupfile(), history_tempfile(), printsome(), readlink2(), realpath(), runsv_main(), statlink(), ttyname_r(), and xmalloc_readlink().
readlinkat()
ssize_t readlinkat (int , const char * __restrict, char * __restrict, size_t)
rmdir()
int rmdir (const char * path)
Definition at line 5 of file rmdir.c.
 {
 #ifdef SYS_rmdir
     return syscall(SYS_rmdir, path);
 #else
     return syscall(SYS_unlinkat, AT_FDCWD, path, AT_REMOVEDIR);
 #endif
 }
References AT_FDCWD, AT_REMOVEDIR, and syscall().
Referenced by _remove_directory(), finalize(), mktemp_builtin(), remove_file(), remove_file_array(), rmdir_builtin(), and rmdir_main().
setegid()
int setegid (gid_t egid)
Definition at line 5 of file setegid.c.
 {
     return __setxid(SYS_setresgid, -1, egid, -1);
 }
References __setxid(), and egid.
Referenced by xsetegid().
seteuid()
int seteuid (uid_t euid)
Definition at line 5 of file seteuid.c.
 {
     return __setxid(SYS_setresuid, -1, euid, -1);
 }
References __setxid(), and euid.
Referenced by xseteuid().
setgid()
int setgid (gid_t gid)
Definition at line 5 of file setgid.c.
 {
     return __setxid(SYS_setgid, gid, 0, 0);
 }
References __setxid().
Referenced by disable_priv_mode(), and xsetgid().
setpgid()
int setpgid (pid_t pid, pid_t pgid)
Definition at line 4 of file setpgid.c.
 {
     return syscall(SYS_setpgid, pid, pgid);
 }
References pid, and syscall().
setsid()
pid_t setsid (void)
Definition at line 4 of file setsid.c.
 {
     return syscall(SYS_setsid);
 }
References syscall().
Referenced by bb_daemonize_or_rexec(), chpst_main(), daemon(), getty_main(), inetd_main(), init_main(), login_tty(), make_new_session(), run(), runsv(), script_main(), setsid_main(), start_shell_in_child(), start_stop_daemon_main(), sulogin_main(), and vfork_child().
setuid()
int setuid (uid_t uid)
Definition at line 5 of file setuid.c.
 {
     return __setxid(SYS_setuid, uid, 0, 0);
 }
References __setxid().
Referenced by disable_priv_mode(), and xsetuid().
sleep()
unsigned sleep (unsigned seconds)
Definition at line 4 of file sleep.c.
 {
     struct timespec tv = { .tv_sec = seconds, .tv_nsec = 0 };
     if (nanosleep(&tv, &tv))
         return tv.tv_sec;
     return 0;
 }
References nanosleep(), and timespec::tv_sec.
symlink()
int symlink (const char * existing, const char * new)
Definition at line 5 of file symlink.c.
 {
 #ifdef SYS_symlink
     return syscall(SYS_symlink, existing, new);
 #else
     return syscall(SYS_symlinkat, existing, AT_FDCWD, new);
 #endif
 }
References AT_FDCWD, and syscall().
Referenced by copy_file(), copy_inode(), create_links_from_list(), create_or_remember_link(), devfsd_main(), ln_builtin(), ln_main(), make_device(), and mksymlink().
symlinkat()
int symlinkat (const char * existing, int fd, const char * new)
Definition at line 4 of file symlinkat.c.
 {
     return syscall(SYS_symlinkat, existing, fd, new);
 }
References fd, and syscall().
sysconf()
long sysconf (int name)
Definition at line 28 of file sysconf.c.
 {
     static const short values[] = {
         [_SC_ARG_MAX] = JT_ARG_MAX,
         [_SC_CHILD_MAX] = RLIM(NPROC),
         [_SC_CLK_TCK] = 100,
         [_SC_NGROUPS_MAX] = 32,
         [_SC_OPEN_MAX] = RLIM(NOFILE),
         [_SC_STREAM_MAX] = -1,
         [_SC_TZNAME_MAX] = TZNAME_MAX,
         [_SC_JOB_CONTROL] = 1,
         [_SC_SAVED_IDS] = 1,
         [_SC_REALTIME_SIGNALS] = VER,
         [_SC_PRIORITY_SCHEDULING] = -1,
         [_SC_TIMERS] = VER,
         [_SC_ASYNCHRONOUS_IO] = VER,
         [_SC_PRIORITIZED_IO] = -1,
         [_SC_SYNCHRONIZED_IO] = -1,
         [_SC_FSYNC] = VER,
         [_SC_MAPPED_FILES] = VER,
         [_SC_MEMLOCK] = VER,
         [_SC_MEMLOCK_RANGE] = VER,
         [_SC_MEMORY_PROTECTION] = VER,
         [_SC_MESSAGE_PASSING] = VER,
         [_SC_SEMAPHORES] = VER,
         [_SC_SHARED_MEMORY_OBJECTS] = VER,
         [_SC_AIO_LISTIO_MAX] = -1,
         [_SC_AIO_MAX] = -1,
         [_SC_AIO_PRIO_DELTA_MAX] = JT_ZERO, /* ?? */
         [_SC_DELAYTIMER_MAX] = JT_DELAYTIMER_MAX,
         [_SC_MQ_OPEN_MAX] = -1,
         [_SC_MQ_PRIO_MAX] = JT_MQ_PRIO_MAX,
         [_SC_VERSION] = VER,
         [_SC_PAGE_SIZE] = JT_PAGE_SIZE,
         [_SC_RTSIG_MAX] = _NSIG - 1 - 31 - 3,
         [_SC_SEM_NSEMS_MAX] = SEM_NSEMS_MAX,
         [_SC_SEM_VALUE_MAX] = JT_SEM_VALUE_MAX,
         [_SC_SIGQUEUE_MAX] = -1,
         [_SC_TIMER_MAX] = -1,
         [_SC_BC_BASE_MAX] = _POSIX2_BC_BASE_MAX,
         [_SC_BC_DIM_MAX] = _POSIX2_BC_DIM_MAX,
         [_SC_BC_SCALE_MAX] = _POSIX2_BC_SCALE_MAX,
         [_SC_BC_STRING_MAX] = _POSIX2_BC_STRING_MAX,
         [_SC_COLL_WEIGHTS_MAX] = COLL_WEIGHTS_MAX,
         [_SC_EXPR_NEST_MAX] = -1,
         [_SC_LINE_MAX] = -1,
         [_SC_RE_DUP_MAX] = RE_DUP_MAX,
         [_SC_2_VERSION] = VER,
         [_SC_2_C_BIND] = VER,
         [_SC_2_C_DEV] = -1,
         [_SC_2_FORT_DEV] = -1,
         [_SC_2_FORT_RUN] = -1,
         [_SC_2_SW_DEV] = -1,
         [_SC_2_LOCALEDEF] = -1,
         [_SC_IOV_MAX] = IOV_MAX,
         [_SC_THREADS] = VER,
         [_SC_THREAD_SAFE_FUNCTIONS] = VER,
         [_SC_GETGR_R_SIZE_MAX] = -1,
         [_SC_GETPW_R_SIZE_MAX] = -1,
         [_SC_LOGIN_NAME_MAX] = 256,
         [_SC_TTY_NAME_MAX] = TTY_NAME_MAX,
         [_SC_THREAD_DESTRUCTOR_ITERATIONS] = PTHREAD_DESTRUCTOR_ITERATIONS,
         [_SC_THREAD_KEYS_MAX] = PTHREAD_KEYS_MAX,
         [_SC_THREAD_STACK_MIN] = PTHREAD_STACK_MIN,
         [_SC_THREAD_THREADS_MAX] = -1,
         [_SC_THREAD_ATTR_STACKADDR] = VER,
         [_SC_THREAD_ATTR_STACKSIZE] = VER,
         [_SC_THREAD_PRIORITY_SCHEDULING] = VER,
         [_SC_THREAD_PRIO_INHERIT] = -1,
         [_SC_THREAD_PRIO_PROTECT] = -1,
         [_SC_THREAD_PROCESS_SHARED] = VER,
         [_SC_NPROCESSORS_CONF] = JT_NPROCESSORS_CONF,
         [_SC_NPROCESSORS_ONLN] = JT_NPROCESSORS_ONLN,
         [_SC_PHYS_PAGES] = JT_PHYS_PAGES,
         [_SC_AVPHYS_PAGES] = JT_AVPHYS_PAGES,
         [_SC_ATEXIT_MAX] = -1,
         [_SC_PASS_MAX] = -1,
         [_SC_XOPEN_VERSION] = _XOPEN_VERSION,
         [_SC_XOPEN_XCU_VERSION] = _XOPEN_VERSION,
         [_SC_XOPEN_UNIX] = 1,
         [_SC_XOPEN_CRYPT] = -1,
         [_SC_XOPEN_ENH_I18N] = 1,
         [_SC_XOPEN_SHM] = 1,
         [_SC_2_CHAR_TERM] = -1,
         [_SC_2_UPE] = -1,
         [_SC_XOPEN_XPG2] = -1,
         [_SC_XOPEN_XPG3] = -1,
         [_SC_XOPEN_XPG4] = -1,
         [_SC_NZERO] = NZERO,
         [_SC_XBS5_ILP32_OFF32] = -1,
         [_SC_XBS5_ILP32_OFFBIG] = sizeof(long)==4 ? 1 : -1,
         [_SC_XBS5_LP64_OFF64] = sizeof(long)==8 ? 1 : -1,
         [_SC_XBS5_LPBIG_OFFBIG] = -1,
         [_SC_XOPEN_LEGACY] = -1,
         [_SC_XOPEN_REALTIME] = -1,
         [_SC_XOPEN_REALTIME_THREADS] = -1,
         [_SC_ADVISORY_INFO] = VER,
         [_SC_BARRIERS] = VER,
         [_SC_CLOCK_SELECTION] = VER,
         [_SC_CPUTIME] = VER,
         [_SC_THREAD_CPUTIME] = VER,
         [_SC_MONOTONIC_CLOCK] = VER,
         [_SC_READER_WRITER_LOCKS] = VER,
         [_SC_SPIN_LOCKS] = VER,
         [_SC_REGEXP] = 1,
         [_SC_SHELL] = 1,
         [_SC_SPAWN] = VER,
         [_SC_SPORADIC_SERVER] = -1,
         [_SC_THREAD_SPORADIC_SERVER] = -1,
         [_SC_TIMEOUTS] = VER,
         [_SC_TYPED_MEMORY_OBJECTS] = -1,
         [_SC_2_PBS] = -1,
         [_SC_2_PBS_ACCOUNTING] = -1,
         [_SC_2_PBS_LOCATE] = -1,
         [_SC_2_PBS_MESSAGE] = -1,
         [_SC_2_PBS_TRACK] = -1,
         [_SC_SYMLOOP_MAX] = SYMLOOP_MAX,
         [_SC_STREAMS] = JT_ZERO,
         [_SC_2_PBS_CHECKPOINT] = -1,
         [_SC_V6_ILP32_OFF32] = -1,
         [_SC_V6_ILP32_OFFBIG] = sizeof(long)==4 ? 1 : -1,
         [_SC_V6_LP64_OFF64] = sizeof(long)==8 ? 1 : -1,
         [_SC_V6_LPBIG_OFFBIG] = -1,
         [_SC_HOST_NAME_MAX] = HOST_NAME_MAX,
         [_SC_TRACE] = -1,
         [_SC_TRACE_EVENT_FILTER] = -1,
         [_SC_TRACE_INHERIT] = -1,
         [_SC_TRACE_LOG] = -1,
         [_SC_IPV6] = VER,
         [_SC_RAW_SOCKETS] = VER,
         [_SC_V7_ILP32_OFF32] = -1,
         [_SC_V7_ILP32_OFFBIG] = sizeof(long)==4 ? 1 : -1,
         [_SC_V7_LP64_OFF64] = sizeof(long)==8 ? 1 : -1,
         [_SC_V7_LPBIG_OFFBIG] = -1,
         [_SC_SS_REPL_MAX] = -1,
         [_SC_TRACE_EVENT_NAME_MAX] = -1,
         [_SC_TRACE_NAME_MAX] = -1,
         [_SC_TRACE_SYS_MAX] = -1,
         [_SC_TRACE_USER_EVENT_MAX] = -1,
         [_SC_XOPEN_STREAMS] = JT_ZERO,
         [_SC_THREAD_ROBUST_PRIO_INHERIT] = -1,
         [_SC_THREAD_ROBUST_PRIO_PROTECT] = -1,
         [_SC_MINSIGSTKSZ] = JT_MINSIGSTKSZ,
         [_SC_SIGSTKSZ] = JT_SIGSTKSZ,
     };
     if (name >= sizeof(values)/sizeof(values[0]) || !values[name]) {
         errno = EINVAL;
         return -1;
     } else if (values[name] >= -1) {
         return values[name];
     } else if (values[name] < -256) {
         struct rlimit lim;
         getrlimit(values[name]&16383, &lim);
         if (lim.rlim_cur == RLIM_INFINITY)
             return -1;
         return lim.rlim_cur > LONG_MAX ? LONG_MAX : lim.rlim_cur;
     }
     switch ((unsigned char)values[name]) {
     case VER & 255:
         return _POSIX_VERSION;
     case JT_ARG_MAX & 255:
         return ARG_MAX;
     case JT_MQ_PRIO_MAX & 255:
         return MQ_PRIO_MAX;
     case JT_PAGE_SIZE & 255:
         return PAGE_SIZE;
     case JT_SEM_VALUE_MAX & 255:
         return SEM_VALUE_MAX;
     case JT_DELAYTIMER_MAX & 255:
         return DELAYTIMER_MAX;
     case JT_NPROCESSORS_CONF & 255:
     case JT_NPROCESSORS_ONLN & 255: ;
         unsigned char set[128] = {1};
         int i, cnt;
         __syscall(SYS_sched_getaffinity, 0, sizeof set, set);
         for (i=cnt=0; i<sizeof set; i++)
             for (; set[i]; set[i]&=set[i]-1, cnt++);
         return cnt;
     case JT_PHYS_PAGES & 255:
     case JT_AVPHYS_PAGES & 255: ;
         unsigned long long mem;
         struct sysinfo si;
         __lsysinfo(&si);
         if (!si.mem_unit) si.mem_unit = 1;
         if (name==_SC_PHYS_PAGES) mem = si.totalram;
         else mem = si.freeram + si.bufferram;
         mem *= si.mem_unit;
         mem /= PAGE_SIZE;
         return (mem > LONG_MAX) ? LONG_MAX : mem;
     case JT_MINSIGSTKSZ & 255:
     case JT_SIGSTKSZ & 255: ;
         long val = __getauxval(AT_MINSIGSTKSZ);
         if (val < MINSIGSTKSZ) val = MINSIGSTKSZ;
         if (values[name] == JT_SIGSTKSZ)
             val += SIGSTKSZ - MINSIGSTKSZ;
         return val;
     case JT_ZERO & 255:
         return 0;
     }
     return values[name];
 }
References __getauxval(), __lsysinfo(), __syscall, _NSIG, _POSIX2_BC_BASE_MAX, _POSIX2_BC_DIM_MAX, _POSIX2_BC_SCALE_MAX, _POSIX2_BC_STRING_MAX, _POSIX_VERSION, _SC_2_C_BIND, _SC_2_C_DEV, _SC_2_CHAR_TERM, _SC_2_FORT_DEV, _SC_2_FORT_RUN, _SC_2_LOCALEDEF, _SC_2_PBS, _SC_2_PBS_ACCOUNTING, _SC_2_PBS_CHECKPOINT, _SC_2_PBS_LOCATE, _SC_2_PBS_MESSAGE, _SC_2_PBS_TRACK, _SC_2_SW_DEV, _SC_2_UPE, _SC_2_VERSION, _SC_ADVISORY_INFO, _SC_AIO_LISTIO_MAX, _SC_AIO_MAX, _SC_AIO_PRIO_DELTA_MAX, _SC_ARG_MAX, _SC_ASYNCHRONOUS_IO, _SC_ATEXIT_MAX, _SC_AVPHYS_PAGES, _SC_BARRIERS, _SC_BC_BASE_MAX, _SC_BC_DIM_MAX, _SC_BC_SCALE_MAX, _SC_BC_STRING_MAX, _SC_CHILD_MAX, _SC_CLK_TCK, _SC_CLOCK_SELECTION, _SC_COLL_WEIGHTS_MAX, _SC_CPUTIME, _SC_DELAYTIMER_MAX, _SC_EXPR_NEST_MAX, _SC_FSYNC, _SC_GETGR_R_SIZE_MAX, _SC_GETPW_R_SIZE_MAX, _SC_HOST_NAME_MAX, _SC_IOV_MAX, _SC_IPV6, _SC_JOB_CONTROL, _SC_LINE_MAX, _SC_LOGIN_NAME_MAX, _SC_MAPPED_FILES, _SC_MEMLOCK, _SC_MEMLOCK_RANGE, _SC_MEMORY_PROTECTION, _SC_MESSAGE_PASSING, _SC_MINSIGSTKSZ, _SC_MONOTONIC_CLOCK, _SC_MQ_OPEN_MAX, _SC_MQ_PRIO_MAX, _SC_NGROUPS_MAX, _SC_NPROCESSORS_CONF, _SC_NPROCESSORS_ONLN, _SC_NZERO, _SC_OPEN_MAX, _SC_PAGE_SIZE, _SC_PASS_MAX, _SC_PHYS_PAGES, _SC_PRIORITIZED_IO, _SC_PRIORITY_SCHEDULING, _SC_RAW_SOCKETS, _SC_RE_DUP_MAX, _SC_READER_WRITER_LOCKS, _SC_REALTIME_SIGNALS, _SC_REGEXP, _SC_RTSIG_MAX, _SC_SAVED_IDS, _SC_SEM_NSEMS_MAX, _SC_SEM_VALUE_MAX, _SC_SEMAPHORES, _SC_SHARED_MEMORY_OBJECTS, _SC_SHELL, _SC_SIGQUEUE_MAX, _SC_SIGSTKSZ, _SC_SPAWN, _SC_SPIN_LOCKS, _SC_SPORADIC_SERVER, _SC_SS_REPL_MAX, _SC_STREAM_MAX, _SC_STREAMS, _SC_SYMLOOP_MAX, _SC_SYNCHRONIZED_IO, _SC_THREAD_ATTR_STACKADDR, _SC_THREAD_ATTR_STACKSIZE, _SC_THREAD_CPUTIME, _SC_THREAD_DESTRUCTOR_ITERATIONS, _SC_THREAD_KEYS_MAX, _SC_THREAD_PRIO_INHERIT, _SC_THREAD_PRIO_PROTECT, _SC_THREAD_PRIORITY_SCHEDULING, _SC_THREAD_PROCESS_SHARED, _SC_THREAD_ROBUST_PRIO_INHERIT, _SC_THREAD_ROBUST_PRIO_PROTECT, _SC_THREAD_SAFE_FUNCTIONS, _SC_THREAD_SPORADIC_SERVER, _SC_THREAD_STACK_MIN, _SC_THREAD_THREADS_MAX, _SC_THREADS, _SC_TIMEOUTS, _SC_TIMER_MAX, _SC_TIMERS, _SC_TRACE, _SC_TRACE_EVENT_FILTER, _SC_TRACE_EVENT_NAME_MAX, _SC_TRACE_INHERIT, _SC_TRACE_LOG, _SC_TRACE_NAME_MAX, _SC_TRACE_SYS_MAX, _SC_TRACE_USER_EVENT_MAX, _SC_TTY_NAME_MAX, _SC_TYPED_MEMORY_OBJECTS, _SC_TZNAME_MAX, _SC_V6_ILP32_OFF32, _SC_V6_ILP32_OFFBIG, _SC_V6_LP64_OFF64, _SC_V6_LPBIG_OFFBIG, _SC_V7_ILP32_OFF32, _SC_V7_ILP32_OFFBIG, _SC_V7_LP64_OFF64, _SC_V7_LPBIG_OFFBIG, _SC_VERSION, _SC_XBS5_ILP32_OFF32, _SC_XBS5_ILP32_OFFBIG, _SC_XBS5_LP64_OFF64, _SC_XBS5_LPBIG_OFFBIG, _SC_XOPEN_CRYPT, _SC_XOPEN_ENH_I18N, _SC_XOPEN_LEGACY, _SC_XOPEN_REALTIME, _SC_XOPEN_REALTIME_THREADS, _SC_XOPEN_SHM, _SC_XOPEN_STREAMS, _SC_XOPEN_UNIX, _SC_XOPEN_VERSION, _SC_XOPEN_XCU_VERSION, _SC_XOPEN_XPG2, _SC_XOPEN_XPG3, _SC_XOPEN_XPG4, _XOPEN_VERSION, AT_MINSIGSTKSZ, sysinfo::bufferram, cnt, EINVAL, errno, sysinfo::freeram, getrlimit(), i, JT_ARG_MAX, JT_AVPHYS_PAGES, JT_DELAYTIMER_MAX, JT_MINSIGSTKSZ, JT_MQ_PRIO_MAX, JT_NPROCESSORS_CONF, JT_NPROCESSORS_ONLN, JT_PAGE_SIZE, JT_PHYS_PAGES, JT_SEM_VALUE_MAX, JT_SIGSTKSZ, JT_ZERO, LONG_MAX, mem, sysinfo::mem_unit, NOFILE, PAGE_SIZE, RLIM, rlimit::rlim_cur, RLIM_INFINITY, sysinfo::totalram, val, and VER.
Referenced by bb_arg_max(), bb_clk_tck(), get_avphys_pages(), get_clk_tck(), get_nprocs(), get_nprocs_conf(), get_phys_pages(), getconf_print(), getdtablesize(), getmaxchild(), and getmaxgroups().
tcgetpgrp()
pid_t tcgetpgrp (int fd)
Definition at line 358 of file jobs.c.
 {
   pid_t pgrp;
   /* ioctl will handle setting errno correctly. */
   if (ioctl (fd, TIOCGPGRP, &pgrp) < 0)
     return (-1);
   return (pgrp);
 }
References fd, ioctl(), and TIOCGPGRP.
Referenced by hush_main(), initialize_job_control(), maybe_give_terminal_to(), and set_job_control().
tcsetpgrp()
int tcsetpgrp (int fd, pid_t pgrp)
Definition at line 5 of file tcsetpgrp.c.
 {
     int pgrp_int = pgrp;
     return ioctl(fd, TIOCSPGRP, &pgrp_int);
 }
References fd, ioctl(), and TIOCSPGRP.
truncate()
int truncate (const char * path, off_t length)
Definition at line 4 of file truncate.c.
 {
     return syscall(SYS_truncate, path, __SYSCALL_LL_O(length));
 }
References __SYSCALL_LL_O, and syscall().
ttyname()
char* ttyname (int fd)
Definition at line 5 of file ttyname.c.
 {
     static char buf[TTY_NAME_MAX];
     int result;
     if ((result = ttyname_r(fd, buf, sizeof buf))) {
         errno = result;
         return NULL;
     }
     return buf;
 }
References buf, errno, fd, NULL, and ttyname_r().
ttyname_r()
int ttyname_r (int fd, char * buf, size_t buflen)
Definition at line 211 of file platform.c.
 {
     int r;
     char path[sizeof("/proc/self/fd/%d") + sizeof(int)*3];
     if (!isatty(fd))
         return errno == EINVAL ? ENOTTY : errno;
     sprintf(path, "/proc/self/fd/%d", fd);
     r = readlink(path, buf, buflen);
     if (r < 0)
         return errno;
     if (r >= buflen)
         return ERANGE;
     buf[r] = '\0';
     return 0;
 }
References __procfdname(), buf, buflen, EINVAL, ENODEV, ENOTTY, ERANGE, errno, fd, fstat(), isatty(), l, readlink(), size, sprintf(), stat::st_dev, stat::st_ino, and stat().
Referenced by ttyname(), and xmalloc_ttyname().
unlink()
int unlink (const char * path)
Definition at line 5 of file unlink.c.
 {
 #ifdef SYS_unlink
     return syscall(SYS_unlink, path);
 #else
     return syscall(SYS_unlinkat, AT_FDCWD, path, 0);
 #endif
 }
References AT_FDCWD, and syscall().
Referenced by action_compat(), ask_and_unlink(), bbunpack(), buffer_pwrite(), clean_up_and_exit(), cleanup_outname(), conf(), conf_cleanup(), convert(), copy_inode(), create_socket(), crontab_main(), data_extract_all(), delete_contents(), delete_tempfile(), diffreg(), dolink(), fail_hunk(), finalize(), here_document_to_fd(), history_do_write(), history_truncate_file(), ln_main(), log_locally(), lpd_main(), lpqr_main(), make_device(), microcom_main(), mktemp_builtin(), mv_main(), patch_main(), prepare_socket_fd(), process_cron_update_file(), processorstop(), remove_file(), remove_file_array(), remove_pidfile_std_path_and_ext(), rename(), reread_config_file(), rescan_crontab_dir(), rm_file(), rmoldest(), sem_open(), shm_unlink(), show_textbox(), unlink_builtin(), update_passwd(), update_status(), and xunlink().
unlinkat()
int unlinkat (int fd, const char * path, int flag)
Definition at line 4 of file unlinkat.c.
 {
     return syscall(SYS_unlinkat, fd, path, flag);
 }
References fd, and syscall().
write()
ssize_t write (int fd, const void * buf, size_t count)
Definition at line 4 of file write.c.
 {
     return syscall_cp(SYS_write, fd, buf, count);
 }
References buf, count, fd, and syscall_cp.
Referenced by alrm_catcher(), bb_putchar_stderr(), cat_main(), dumpkmap_main(), eventfd_write(), fcopy(), forkpty(), guarantee(), heredoc_write(), history_do_write(), history_truncate_file(), io_thread_func(), iproute_flush_cache(), lpqr_main(), main(), memory_out(), microcom_main(), preadfd(), printLines(), pscan_main(), pthread_setname_np(), readwrite(), rtnl_send_check(), runsvdir_main(), s_chld_term(), safe_write(), sem_open(), setup_heredoc(), show_textbox(), shutdown_watchdog(), signal_handler(), stunalloc(), tee_builtin(), update_status(), watchdog_main(), write_tables(), and zwrite().
Variable Documentation
optarg
char* optarg extern
Definition at line 10 of file getopt.c.
Referenced by generate_output(), and getopt().
opterr
int opterr
Definition at line 129 of file unistd.h.
optind
int optind extern
Definition at line 11 of file getopt.c.
Referenced by generate_output(), getopt(), and getopt_main().
optopt
int optopt
Definition at line 129 of file unistd.h.