Fennix Userspace: Userspace/musl/src/mman/mmap.c File Reference
mmap.c File Reference
#include <unistd.h>
#include <sys/mman.h>
#include <errno.h>
#include <stdint.h>
#include <limits.h>
#include "syscall.h"
Macros
#define UNIT SYSCALL_MMAP2_UNIT
#define OFF_MASK ((-0x2000ULL << (8*sizeof(syscall_arg_t)-1)) | (UNIT-1))
Functions
static void dummy (void)
weak_alias (dummy, __vm_wait)
void * __mmap (void *start, size_t len, int prot, int flags, int fd, off_t off)
weak_alias (__mmap, mmap)
Macro Definition Documentation
OFF_MASK
#define OFF_MASK ((-0x2000ULL << (8*sizeof(syscall_arg_t)-1)) | (UNIT-1))
Definition at line 12 of file mmap.c.
UNIT
#define UNIT SYSCALL_MMAP2_UNIT
Definition at line 11 of file mmap.c.
Function Documentation
__mmap()
void* __mmap (void * start, size_t len, int prot, int flags, int fd, off_t off)
Definition at line 14 of file mmap.c.
 {
     long ret;
     if (off & OFF_MASK) {
         errno = EINVAL;
         return MAP_FAILED;
     }
     if (len >= PTRDIFF_MAX) {
         errno = ENOMEM;
         return MAP_FAILED;
     }
     if (flags & MAP_FIXED) {
         __vm_wait();
     }
 #ifdef SYS_mmap2
     ret = __syscall(SYS_mmap2, start, len, prot, flags, fd, off/UNIT);
 #else
     ret = __syscall(SYS_mmap, start, len, prot, flags, fd, off);
 #endif
     /* Fixup incorrect EPERM from kernel. */
     if (ret == -EPERM && !start && (flags&MAP_ANON) && !(flags&MAP_FIXED))
         ret = -ENOMEM;
     return (void *)__syscall_ret(ret);
 }
References __syscall, __syscall_ret(), __vm_wait(), EINVAL, ENOMEM, EPERM, errno, fd, flags, MAP_ANON, MAP_FAILED, MAP_FIXED, off, OFF_MASK, PTRDIFF_MAX, start, SYS_mmap2, and UNIT.
Referenced by __bin_chunk(), __expand_heap(), __map_file(), __pthread_create(), __simple_malloc(), and malloc().
dummy()
static void dummy (void) static
Definition at line 8 of file mmap.c.
 { }
weak_alias() [1/2]
weak_alias (__mmap , mmap)
weak_alias() [2/2]
weak_alias (dummy , __vm_wait)