Fennix: Userspace/musl/src/stdio/snprintf.c File Reference
snprintf.c File Reference
#include <stdio.h>
#include <stdarg.h>
Functions
int snprintf (char *restrict s, size_t n, const char *restrict fmt,...)
Function Documentation
snprintf()
int snprintf (char *restrict s, size_t n, const char *restrict fmt, ...)
Definition at line 4 of file snprintf.c.
 {
     int ret;
     va_list ap;
     va_start(ap, fmt);
     ret = vsnprintf(s, n, fmt, ap);
     va_end(ap);
     return ret;
 }
References fmt, n, ret, va_end(), va_start(), and vsnprintf().