Fennix: Userspace/apps/base/busybox/archival/rpm.c File Reference
rpm.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include "bb_archive.h"
#include "rpm.h"
Data Structures
struct rpm_index
struct globals
Macros
#define RPM_CHAR_TYPE 1
#define RPM_INT8_TYPE 2
#define RPM_INT16_TYPE 3
#define RPM_INT32_TYPE 4
#define RPM_STRING_TYPE 6
#define RPM_BIN_TYPE 7
#define RPM_STRING_ARRAY_TYPE 8
#define RPM_I18NSTRING_TYPE 9
#define TAG_NAME 1000
#define TAG_VERSION 1001
#define TAG_RELEASE 1002
#define TAG_SUMMARY 1004
#define TAG_DESCRIPTION 1005
#define TAG_BUILDTIME 1006
#define TAG_BUILDHOST 1007
#define TAG_SIZE 1009
#define TAG_VENDOR 1011
#define TAG_LICENSE 1014
#define TAG_PACKAGER 1015
#define TAG_GROUP 1016
#define TAG_URL 1020
#define TAG_PREIN 1023
#define TAG_POSTIN 1024
#define TAG_FILEFLAGS 1037
#define TAG_FILEUSERNAME 1039
#define TAG_FILEGROUPNAME 1040
#define TAG_SOURCERPM 1044
#define TAG_PREINPROG 1085
#define TAG_POSTINPROG 1086
#define TAG_PREFIXS 1098
#define TAG_DIRINDEXES 1116
#define TAG_BASENAMES 1117
#define TAG_DIRNAMES 1118
#define TAG_PAYLOADCOMPRESSOR 1125
#define RPMFILE_CONFIG (1 << 0)
#define RPMFILE_DOC (1 << 1)
#define G_pagesize cached_pagesize(G.pagesize)
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
Enumerations
enum rpm_functions_e {
rpm_query = 1 , rpm_install = 2 , rpm_query_info = 4 , rpm_query_package = 8 ,
rpm_query_list = 16 , rpm_query_list_doc = 32 , rpm_query_list_config = 64
}
Functions
static int rpm_gettags (const char *filename)
static int bsearch_rpmtag (const void *key, const void *item)
static char * rpm_getstr (int tag, int itemindex)
static char * rpm_getstr0 (int tag)
Variables
struct globals FIX_ALIASING
Data Structure Documentation
rpm_index
struct rpm_index
Definition at line 75 of file rpm.c.
Data Fields
uint32_t count
uint32_t offset
uint32_t tag
uint32_t type
Macro Definition Documentation
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 90 of file rpm.c.
G_pagesize
#define G_pagesize cached_pagesize(G.pagesize)
Definition at line 88 of file rpm.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 91 of file rpm.c.
RPM_BIN_TYPE
#define RPM_BIN_TYPE 7
Definition at line 30 of file rpm.c.
RPM_CHAR_TYPE
#define RPM_CHAR_TYPE 1
Definition at line 24 of file rpm.c.
RPM_I18NSTRING_TYPE
#define RPM_I18NSTRING_TYPE 9
Definition at line 32 of file rpm.c.
RPM_INT16_TYPE
#define RPM_INT16_TYPE 3
Definition at line 26 of file rpm.c.
RPM_INT32_TYPE
#define RPM_INT32_TYPE 4
Definition at line 27 of file rpm.c.
RPM_INT8_TYPE
#define RPM_INT8_TYPE 2
Definition at line 25 of file rpm.c.
RPM_STRING_ARRAY_TYPE
#define RPM_STRING_ARRAY_TYPE 8
Definition at line 31 of file rpm.c.
RPM_STRING_TYPE
#define RPM_STRING_TYPE 6
Definition at line 29 of file rpm.c.
RPMFILE_CONFIG
#define RPMFILE_CONFIG (1 << 0)
Definition at line 62 of file rpm.c.
RPMFILE_DOC
#define RPMFILE_DOC (1 << 1)
Definition at line 63 of file rpm.c.
TAG_BASENAMES
#define TAG_BASENAMES 1117
Definition at line 57 of file rpm.c.
TAG_BUILDHOST
#define TAG_BUILDHOST 1007
Definition at line 40 of file rpm.c.
TAG_BUILDTIME
#define TAG_BUILDTIME 1006
Definition at line 39 of file rpm.c.
TAG_DESCRIPTION
#define TAG_DESCRIPTION 1005
Definition at line 38 of file rpm.c.
TAG_DIRINDEXES
#define TAG_DIRINDEXES 1116
Definition at line 56 of file rpm.c.
TAG_DIRNAMES
#define TAG_DIRNAMES 1118
Definition at line 58 of file rpm.c.
TAG_FILEFLAGS
#define TAG_FILEFLAGS 1037
Definition at line 49 of file rpm.c.
TAG_FILEGROUPNAME
#define TAG_FILEGROUPNAME 1040
Definition at line 51 of file rpm.c.
TAG_FILEUSERNAME
#define TAG_FILEUSERNAME 1039
Definition at line 50 of file rpm.c.
TAG_GROUP
#define TAG_GROUP 1016
Definition at line 45 of file rpm.c.
TAG_LICENSE
#define TAG_LICENSE 1014
Definition at line 43 of file rpm.c.
TAG_NAME
#define TAG_NAME 1000
Definition at line 34 of file rpm.c.
TAG_PACKAGER
#define TAG_PACKAGER 1015
Definition at line 44 of file rpm.c.
TAG_PAYLOADCOMPRESSOR
#define TAG_PAYLOADCOMPRESSOR 1125
Definition at line 59 of file rpm.c.
TAG_POSTIN
#define TAG_POSTIN 1024
Definition at line 48 of file rpm.c.
TAG_POSTINPROG
#define TAG_POSTINPROG 1086
Definition at line 54 of file rpm.c.
TAG_PREFIXS
#define TAG_PREFIXS 1098
Definition at line 55 of file rpm.c.
TAG_PREIN
#define TAG_PREIN 1023
Definition at line 47 of file rpm.c.
TAG_PREINPROG
#define TAG_PREINPROG 1085
Definition at line 53 of file rpm.c.
TAG_RELEASE
#define TAG_RELEASE 1002
Definition at line 36 of file rpm.c.
TAG_SIZE
#define TAG_SIZE 1009
Definition at line 41 of file rpm.c.
TAG_SOURCERPM
#define TAG_SOURCERPM 1044
Definition at line 52 of file rpm.c.
TAG_SUMMARY
#define TAG_SUMMARY 1004
Definition at line 37 of file rpm.c.
TAG_URL
#define TAG_URL 1020
Definition at line 46 of file rpm.c.
TAG_VENDOR
#define TAG_VENDOR 1011
Definition at line 42 of file rpm.c.
TAG_VERSION
#define TAG_VERSION 1001
Definition at line 35 of file rpm.c.
Enumeration Type Documentation
rpm_functions_e
enum rpm_functions_e
Enumerator
rpm_query
rpm_install
rpm_query_info
rpm_query_package
rpm_query_list
rpm_query_list_doc
rpm_query_list_config
Definition at line 65 of file rpm.c.
                      {
     rpm_query = 1,
     rpm_install = 2,
     rpm_query_info = 4,
     rpm_query_package = 8,
     rpm_query_list = 16,
     rpm_query_list_doc = 32,
     rpm_query_list_config = 64
 };
Function Documentation
bsearch_rpmtag()
static int bsearch_rpmtag (const void * key, const void * item) static
Definition at line 157 of file rpm.c.
 {
     int *tag = (int *)key;
     rpm_index *tmp = (rpm_index *) item;
     return (*tag - tmp->tag);
 }
References rpm_index::tag.
Referenced by rpm_getstr().
rpm_getstr()
static char* rpm_getstr (int tag, int itemindex) static
Definition at line 164 of file rpm.c.
 {
     rpm_index *found;
     found = bsearch(&tag, G.mytags, G.tagcount, sizeof(G.mytags[0]), bsearch_rpmtag);
     if (!found || itemindex >= found->count)
         return NULL;
     if (found->type == RPM_STRING_TYPE
      || found->type == RPM_I18NSTRING_TYPE
      || found->type == RPM_STRING_ARRAY_TYPE
     ) {
         int n;
         char *tmpstr = (char *) G.map + found->offset;
         for (n = 0; n < itemindex; n++)
             tmpstr = tmpstr + strlen(tmpstr) + 1;
         return tmpstr;
     }
     return NULL;
 }
References bsearch(), bsearch_rpmtag(), for(), found, G, n, NULL, RPM_I18NSTRING_TYPE, RPM_STRING_ARRAY_TYPE, RPM_STRING_TYPE, and strlen().
Referenced by rpm_getstr0().
rpm_getstr0()
static char* rpm_getstr0 (int tag) static
Definition at line 182 of file rpm.c.
 {
     return rpm_getstr(tag, 0);
 }
References rpm_getstr().
rpm_gettags()
static int rpm_gettags (const char * filename) static
Definition at line 93 of file rpm.c.
 {
     rpm_index *tags;
     int fd;
     unsigned pass, idx;
     unsigned storepos;
     if (!filename) { /* rpm2cpio w/o filename? */
         filename = bb_msg_standard_output;
         fd = 0;
     } else {
         fd = xopen(filename, O_RDONLY);
     }
     storepos = xlseek(fd, 96, SEEK_CUR); /* Seek past the unused lead */
     G.tagcount = 0;
     tags = NULL;
     idx = 0;
     /* 1st pass is the signature headers, 2nd is the main stuff */
     for (pass = 0; pass < 2; pass++) {
         struct rpm_header header;
         unsigned cnt;
         xread(fd, &header, sizeof(header));
         if (header.magic_and_ver != htonl(RPM_HEADER_MAGICnVER))
             bb_error_msg_and_die("invalid RPM header magic in '%s'", filename);
         header.size = ntohl(header.size);
         cnt = ntohl(header.entries);
         storepos += sizeof(header) + cnt * 16;
         G.tagcount += cnt;
         tags = xrealloc(tags, sizeof(tags[0]) * G.tagcount);
         xread(fd, &tags[idx], sizeof(tags[0]) * cnt);
         while (cnt--) {
             rpm_index *tag = &tags[idx];
             tag->tag = ntohl(tag->tag);
             tag->type = ntohl(tag->type);
             tag->count = ntohl(tag->count);
             tag->offset = storepos + ntohl(tag->offset);
             if (pass == 0)
                 tag->tag -= 743;
             idx++;
         }
         /* Skip padding to 8 byte boundary after reading signature headers */
         if (pass == 0)
             while (header.size & 7)
                 header.size++;
         /* Seek past store */
         storepos = xlseek(fd, header.size, SEEK_CUR);
     }
     G.mytags = tags;
     /* Map the store */
     storepos = (storepos + G_pagesize) & -(int)G_pagesize;
     /* remember size for munmap */
     G.mapsize = storepos;
     /* some NOMMU systems prefer MAP_PRIVATE over MAP_SHARED */
     G.map = mmap_read(fd, storepos);
     if (G.map == MAP_FAILED)
         bb_perror_msg_and_die("mmap '%s'", filename);
     return fd;
 }
References bb_error_msg_and_die(), bb_perror_msg_and_die(), cnt, rpm_index::count, fd, filename, G, G_pagesize, htonl(), idx, MAP_FAILED, mmap_read(), ntohl(), NULL, O_RDONLY, rpm_index::offset, RPM_HEADER_MAGICnVER, SEEK_CUR, rpm_index::tag, rpm_index::type, xlseek(), xopen(), xread(), and xrealloc.
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING