Fennix: Userspace/musl/src/malloc/oldmalloc/malloc_usable_size.c File Reference
malloc_usable_size.c File Reference
#include <malloc.h>
#include "malloc_impl.h"
Functions
size_t malloc_usable_size (void *p)
Variables
hidden void *(*const __realloc_dep)(void *, size_t) = realloc
Function Documentation
malloc_usable_size()
size_t malloc_usable_size (void * p)
Definition at line 6 of file malloc_usable_size.c.
 {
     return p ? CHUNK_SIZE(MEM_TO_CHUNK(p)) - OVERHEAD : 0;
 }
References CHUNK_SIZE, get_meta(), get_nominal_size(), get_slot_index(), get_stride(), IB, idx, meta::mem, MEM_TO_CHUNK, OVERHEAD, p, start(), and group::storage.
Variable Documentation
__realloc_dep
hidden void*(*const __realloc_dep) (void *, size_t) (void * , size_t) = realloc
Definition at line 4 of file malloc_usable_size.c.