Fennix Userspace: Userspace/musl/src/locale/strcoll.c File Reference
strcoll.c File Reference
#include <string.h>
#include <locale.h>
#include "locale_impl.h"
Functions
int __strcoll_l (const char *l, const char *r, locale_t loc)
int strcoll (const char *l, const char *r)
weak_alias (__strcoll_l, strcoll_l)
Function Documentation
__strcoll_l()
int __strcoll_l (const char * l, const char * r, locale_t loc)
Definition at line 5 of file strcoll.c.
 {
     return strcmp(l, r);
 }
References l, and strcmp.
Referenced by strcoll().
strcoll()
int strcoll (const char * l, const char * r)
Definition at line 10 of file strcoll.c.
 {
     return __strcoll_l(l, r, CURRENT_LOCALE);
 }
References __strcoll_l(), CURRENT_LOCALE, and l.
Referenced by _rl_qsort_string_compare(), alphasort(), binary_test(), compare(), compare_keys(), strvec_posixcmp(), and strvec_strcmp().
weak_alias()
weak_alias (__strcoll_l , strcoll_l)