Fennix Userspace: Userspace/apps/base/busybox/networking/isrv.c File Reference
isrv.c File Reference
#include "libbb.h"
#include "isrv.h"
Data Structures
struct isrv_state_t
Macros
#define DEBUG 0
#define DPRINTF(args...) ((void)0)
#define FD2PEER (state->fd2peer)
#define PARAM_TBL (state->param_tbl)
#define TIMEO_TBL (state->timeo_tbl)
#define CURTIME (state->curtime)
#define TIMEOUT (state->timeout)
#define FD_COUNT (state->fd_count)
#define PEER_COUNT (state->peer_count)
#define WR_COUNT (state->wr_count)
Functions
void isrv_want_rd (isrv_state_t *state, int fd)
void isrv_want_wr (isrv_state_t *state, int fd)
void isrv_dont_want_rd (isrv_state_t *state, int fd)
void isrv_dont_want_wr (isrv_state_t *state, int fd)
int isrv_register_fd (isrv_state_t *state, int peer, int fd)
void isrv_close_fd (isrv_state_t *state, int fd)
int isrv_register_peer (isrv_state_t *state, void *param)
static void remove_peer (isrv_state_t *state, int peer)
static void handle_accept (isrv_state_t *state, int fd)
static void handle_fd_set (isrv_state_t *state, fd_set *fds, int(*h)(int, void **))
static void handle_timeout (isrv_state_t *state, int(*do_timeout)(void **))
void isrv_run (int listen_fd, int(*new_peer)(isrv_state_t *state, int fd), int(*do_rd)(int fd, void **), int(*do_wr)(int fd, void **), int(*do_timeout)(void **), int timeout, int linger_timeout)
Macro Definition Documentation
CURTIME
#define CURTIME (state->curtime)
Definition at line 43 of file isrv.c.
DEBUG
#define DEBUG 0
Definition at line 14 of file isrv.c.
DPRINTF
#define DPRINTF (args...) ((void)0)
Definition at line 19 of file isrv.c.
FD2PEER
#define FD2PEER (state->fd2peer)
Definition at line 40 of file isrv.c.
FD_COUNT
#define FD_COUNT (state->fd_count)
Definition at line 45 of file isrv.c.
PARAM_TBL
#define PARAM_TBL (state->param_tbl)
Definition at line 41 of file isrv.c.
PEER_COUNT
#define PEER_COUNT (state->peer_count)
Definition at line 46 of file isrv.c.
TIMEO_TBL
#define TIMEO_TBL (state->timeo_tbl)
Definition at line 42 of file isrv.c.
TIMEOUT
#define TIMEOUT (state->timeout)
Definition at line 44 of file isrv.c.
WR_COUNT
#define WR_COUNT (state->wr_count)
Definition at line 47 of file isrv.c.
Function Documentation
handle_accept()
static void handle_accept (isrv_state_t * state, int fd) static
Definition at line 175 of file isrv.c.
 {
     int n, newfd;
     /* suppress gcc warning "cast from ptr to int of different size" */
     fcntl(fd, F_SETFL, (int)(ptrdiff_t)(PARAM_TBL[0]) | O_NONBLOCK);
     newfd = accept(fd, NULL, 0);
     fcntl(fd, F_SETFL, (int)(ptrdiff_t)(PARAM_TBL[0]));
     if (newfd < 0) {
         if (errno == EAGAIN) return;
         /* Most probably someone gave us wrong fd type
          * (for example, non-socket). Don't want
          * to loop forever. */
         bb_simple_perror_msg_and_die("accept");
     }
     DPRINTF("new_peer(%d)", newfd);
     n = state->new_peer(state, newfd);
     if (n)
         remove_peer(state, n); /* unsuccessful peer start */
 }
References accept(), bb_simple_perror_msg_and_die(), DPRINTF, EAGAIN, errno, F_SETFL, fcntl(), fd, n, NULL, O_NONBLOCK, PARAM_TBL, remove_peer(), and state.
Referenced by handle_fd_set().
handle_fd_set()
static void handle_fd_set (isrv_state_t * state, fd_set * fds, int(*)(int, void **) h) static
Definition at line 197 of file isrv.c.
 {
     enum { LONG_CNT = sizeof(fd_set) / sizeof(long) };
     int fds_pos;
     int fd, peer;
     /* need to know value at _the beginning_ of this routine */
     int fd_cnt = FD_COUNT;
     BUILD_BUG_ON(LONG_CNT * sizeof(long) != sizeof(fd_set));
     fds_pos = 0;
     while (1) {
         /* Find next nonzero bit */
         while (fds_pos < LONG_CNT) {
             if (((long*)fds)[fds_pos] == 0) {
                 fds_pos++;
                 continue;
             }
             /* Found non-zero word */
             fd = fds_pos * sizeof(long)*8; /* word# -> bit# */
             while (1) {
                 if (FD_ISSET(fd, fds)) {
                     FD_CLR(fd, fds);
                     goto found_fd;
                 }
                 fd++;
             }
         }
         break; /* all words are zero */
  found_fd:
         if (fd >= fd_cnt) { /* paranoia */
             DPRINTF("handle_fd_set: fd > fd_cnt?? (%d > %d)",
                     fd, fd_cnt);
             break;
         }
         DPRINTF("handle_fd_set: fd %d is active", fd);
         peer = FD2PEER[fd];
         if (peer < 0)
             continue; /* peer is already gone */
         if (peer == 0) {
             handle_accept(state, fd);
             continue;
         }
         DPRINTF("h(fd:%d)", fd);
         if (h(fd, &PARAM_TBL[peer])) {
             /* this peer is gone */
             remove_peer(state, peer);
         } else if (TIMEOUT) {
             TIMEO_TBL[peer] = monotonic_sec();
         }
     }
 }
References BUILD_BUG_ON, DPRINTF, fd, FD2PEER, FD_CLR, FD_COUNT, FD_ISSET, h, handle_accept(), monotonic_sec(), PARAM_TBL, peer, remove_peer(), state, TIMEO_TBL, and TIMEOUT.
Referenced by isrv_run().
handle_timeout()
static void handle_timeout (isrv_state_t * state, int(*)(void **) do_timeout) static
Definition at line 250 of file isrv.c.
 {
     int n, peer;
     peer = PEER_COUNT-1;
     /* peer 0 is not checked */
     while (peer > 0) {
         DPRINTF("peer %d: time diff %d", peer,
                 (int)(CURTIME - TIMEO_TBL[peer]));
         if ((CURTIME - TIMEO_TBL[peer]) >= TIMEOUT) {
             DPRINTF("peer %d: do_timeout()", peer);
             n = do_timeout(&PARAM_TBL[peer]);
             if (n)
                 remove_peer(state, peer);
         }
         peer--;
     }
 }
References CURTIME, do_timeout(), DPRINTF, n, PARAM_TBL, peer, PEER_COUNT, remove_peer(), state, TIMEO_TBL, and TIMEOUT.
Referenced by isrv_run().
isrv_close_fd()
void isrv_close_fd (isrv_state_t * state, int fd)
Definition at line 104 of file isrv.c.
 {
     DPRINTF("close_fd(%d)", fd);
     close(fd);
     isrv_dont_want_rd(state, fd);
     if (WR_COUNT) isrv_dont_want_wr(state, fd);
     FD2PEER[fd] = -1;
     if (fd == FD_COUNT-1) {
         do fd--; while (fd >= 0 && FD2PEER[fd] == -1);
         FD_COUNT = fd + 1;
         DPRINTF("close_fd: FD_COUNT %d", FD_COUNT);
         FD2PEER = xrealloc(FD2PEER, FD_COUNT * sizeof(FD2PEER[0]));
     }
 }
References close(), DPRINTF, fd, FD2PEER, FD_COUNT, isrv_dont_want_rd(), isrv_dont_want_wr(), state, WR_COUNT, and xrealloc.
Referenced by remove_peer().
isrv_dont_want_rd()
void isrv_dont_want_rd (isrv_state_t * state, int fd)
Definition at line 65 of file isrv.c.
 {
     FD_CLR(fd, &state->rd);
 }
References fd, FD_CLR, and state.
Referenced by isrv_close_fd().
isrv_dont_want_wr()
void isrv_dont_want_wr (isrv_state_t * state, int fd)
Definition at line 71 of file isrv.c.
 {
     if (FD_ISSET(fd, &state->wr)) {
         WR_COUNT--;
         FD_CLR(fd, &state->wr);
     }
 }
References fd, FD_CLR, FD_ISSET, state, and WR_COUNT.
Referenced by isrv_close_fd().
isrv_register_fd()
int isrv_register_fd (isrv_state_t * state, int peer, int fd)
Definition at line 80 of file isrv.c.
 {
     int n;
     DPRINTF("register_fd(peer:%d,fd:%d)", peer, fd);
     if (FD_COUNT >= FD_SETSIZE) return -1;
     if (FD_COUNT <= fd) {
         n = FD_COUNT;
         FD_COUNT = fd + 1;
         DPRINTF("register_fd: FD_COUNT %d", FD_COUNT);
         FD2PEER = xrealloc(FD2PEER, FD_COUNT * sizeof(FD2PEER[0]));
         while (n < fd) FD2PEER[n++] = -1;
     }
     DPRINTF("register_fd: FD2PEER[%d] = %d", fd, peer);
     FD2PEER[fd] = peer;
     return 0;
 }
References DPRINTF, fd, FD2PEER, FD_COUNT, FD_SETSIZE, n, peer, and xrealloc.
Referenced by isrv_run(), and new_peer().
isrv_register_peer()
int isrv_register_peer (isrv_state_t * state, void * param)
Definition at line 124 of file isrv.c.
 {
     int n;
     if (PEER_COUNT >= FD_SETSIZE) return -1;
     n = PEER_COUNT++;
     DPRINTF("register_peer: PEER_COUNT %d", PEER_COUNT);
     PARAM_TBL = xrealloc(PARAM_TBL, PEER_COUNT * sizeof(PARAM_TBL[0]));
     PARAM_TBL[n] = param;
     if (TIMEOUT) {
         TIMEO_TBL = xrealloc(TIMEO_TBL, PEER_COUNT * sizeof(TIMEO_TBL[0]));
         TIMEO_TBL[n] = CURTIME;
     }
     return n;
 }
References CURTIME, DPRINTF, FD_SETSIZE, n, param, PARAM_TBL, PEER_COUNT, TIMEO_TBL, TIMEOUT, and xrealloc.
Referenced by isrv_run(), and new_peer().
isrv_run()
void isrv_run (int listen_fd, int(*)(isrv_state_t *state, int fd) new_peer, int(*)(int fd, void **) do_rd, int(*)(int fd, void **) do_wr, int(*)(void **) do_timeout, int timeout, int linger_timeout)
Definition at line 269 of file isrv.c.
 {
     isrv_state_t *state = xzalloc(sizeof(*state));
     state->new_peer = new_peer;
     state->timeout  = timeout;
     /* register "peer" #0 - it will accept new connections */
     isrv_register_peer(state, NULL);
     isrv_register_fd(state, /*peer:*/ 0, listen_fd);
     isrv_want_rd(state, listen_fd);
     /* remember flags to make blocking<->nonblocking switch faster */
     /* (suppress gcc warning "cast from ptr to int of different size") */
     PARAM_TBL[0] = (void*)(ptrdiff_t)(fcntl(listen_fd, F_GETFL));
     while (1) {
         struct timeval tv;
         fd_set rd;
         fd_set wr;
         fd_set *wrp = NULL;
         int n;
         tv.tv_sec = timeout;
         if (PEER_COUNT <= 1)
             tv.tv_sec = linger_timeout;
         tv.tv_usec = 0;
         rd = state->rd;
         if (WR_COUNT) {
             wr = state->wr;
             wrp = &wr;
         }
         DPRINTF("run: select(FD_COUNT:%d,timeout:%d)...",
                 FD_COUNT, (int)tv.tv_sec);
         n = select(FD_COUNT, &rd, wrp, NULL, tv.tv_sec ? &tv : NULL);
         DPRINTF("run: ...select:%d", n);
         if (n < 0) {
             if (errno != EINTR)
                 bb_simple_perror_msg("select");
             continue;
         }
         if (n == 0 && linger_timeout && PEER_COUNT <= 1)
             break;
         if (timeout) {
             time_t t = monotonic_sec();
             if (t != CURTIME) {
                 CURTIME = t;
                 handle_timeout(state, do_timeout);
             }
         }
         if (n > 0) {
             handle_fd_set(state, &rd, do_rd);
             if (wrp)
                 handle_fd_set(state, wrp, do_wr);
         }
     }
     DPRINTF("run: bailout");
     /* NB: accept socket is not closed. Caller is to decide what to do */
 }
References bb_simple_perror_msg(), CURTIME, do_rd(), do_timeout(), DPRINTF, EINTR, errno, F_GETFL, fcntl(), FD_COUNT, handle_fd_set(), handle_timeout(), isrv_register_fd(), isrv_register_peer(), isrv_want_rd(), monotonic_sec(), n, new_peer(), NULL, PARAM_TBL, PEER_COUNT, rd, select(), state, t, timeout(), timeval::tv_sec, timeval::tv_usec, WR_COUNT, and xzalloc().
Referenced by fakeidentd_main().
isrv_want_rd()
void isrv_want_rd (isrv_state_t * state, int fd)
Definition at line 50 of file isrv.c.
 {
     FD_SET(fd, &state->rd);
 }
References fd, FD_SET, and state.
Referenced by isrv_run(), and new_peer().
isrv_want_wr()
void isrv_want_wr (isrv_state_t * state, int fd)
Definition at line 56 of file isrv.c.
 {
     if (!FD_ISSET(fd, &state->wr)) {
         WR_COUNT++;
         FD_SET(fd, &state->wr);
     }
 }
References fd, FD_ISSET, FD_SET, state, and WR_COUNT.
remove_peer()
static void remove_peer (isrv_state_t * state, int peer) static
Definition at line 142 of file isrv.c.
 {
     int movesize;
     int fd;
     DPRINTF("remove_peer(%d)", peer);
     fd = FD_COUNT - 1;
     while (fd >= 0) {
         if (FD2PEER[fd] == peer) {
             isrv_close_fd(state, fd);
             fd--;
             continue;
         }
         if (FD2PEER[fd] > peer)
             FD2PEER[fd]--;
         fd--;
     }
     PEER_COUNT--;
     DPRINTF("remove_peer: PEER_COUNT %d", PEER_COUNT);
     movesize = (PEER_COUNT - peer) * sizeof(void*);
     if (movesize > 0) {
         memcpy(&PARAM_TBL[peer], &PARAM_TBL[peer+1], movesize);
         if (TIMEOUT)
             memcpy(&TIMEO_TBL[peer], &TIMEO_TBL[peer+1], movesize);
     }
     PARAM_TBL = xrealloc(PARAM_TBL, PEER_COUNT * sizeof(PARAM_TBL[0]));
     if (TIMEOUT)
         TIMEO_TBL = xrealloc(TIMEO_TBL, PEER_COUNT * sizeof(TIMEO_TBL[0]));
 }
References DPRINTF, fd, FD2PEER, FD_COUNT, isrv_close_fd(), memcpy(), PARAM_TBL, peer, PEER_COUNT, state, TIMEO_TBL, TIMEOUT, and xrealloc.
Referenced by handle_accept(), handle_fd_set(), and handle_timeout().