Fennix Userspace: Userspace/musl/include/sys/file.h File Reference
file.h File Reference
Macros
#define LOCK_SH 1
#define LOCK_EX 2
#define LOCK_NB 4
#define LOCK_UN 8
#define L_SET 0
#define L_INCR 1
#define L_XTND 2
Functions
int flock (int, int)
Macro Definition Documentation
L_INCR
#define L_INCR 1
Definition at line 13 of file file.h.
L_SET
#define L_SET 0
Definition at line 12 of file file.h.
L_XTND
#define L_XTND 2
Definition at line 14 of file file.h.
LOCK_EX
#define LOCK_EX 2
Definition at line 8 of file file.h.
LOCK_NB
#define LOCK_NB 4
Definition at line 9 of file file.h.
LOCK_SH
#define LOCK_SH 1
Definition at line 7 of file file.h.
LOCK_UN
#define LOCK_UN 8
Definition at line 10 of file file.h.
Function Documentation
flock()
int flock (int fd, int op)
Definition at line 4 of file flock.c.
 {
     return syscall(SYS_flock, fd, op);
 }
References fd, and syscall().
Referenced by flock_main(), runsv_main(), and seedrng_main().