Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/d_main.c File Reference
d_main.c File Reference
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "config.h"
#include "deh_main.h"
#include "doomdef.h"
#include "doomstat.h"
#include "dstrings.h"
#include "doomfeatures.h"
#include "sounds.h"
#include "d_iwad.h"
#include "z_zone.h"
#include "w_main.h"
#include "w_wad.h"
#include "s_sound.h"
#include "v_video.h"
#include "f_finale.h"
#include "f_wipe.h"
#include "m_argv.h"
#include "m_config.h"
#include "m_controls.h"
#include "m_misc.h"
#include "m_menu.h"
#include "p_saveg.h"
#include "i_endoom.h"
#include "i_joystick.h"
#include "i_system.h"
#include "i_timer.h"
#include "i_video.h"
#include "g_game.h"
#include "hu_stuff.h"
#include "wi_stuff.h"
#include "st_stuff.h"
#include "am_map.h"
#include "net_client.h"
#include "net_dedicated.h"
#include "net_query.h"
#include "p_setup.h"
#include "r_local.h"
#include "statdump.h"
#include "d_main.h"
Functions
void D_DoomLoop (void)
void D_ConnectNetGame (void)
void D_CheckNetGame (void)
void D_ProcessEvents (void)
void R_ExecuteSetViewSize (void)
void D_Display (void)
void D_BindVariables (void)
boolean D_GrabMouseCallback (void)
void doomgeneric_Tick ()
void D_PageTicker (void)
void D_PageDrawer (void)
void D_AdvanceDemo (void)
void D_DoAdvanceDemo (void)
void D_StartTitle (void)
static char * GetGameName (char *gamename)
static void SetMissionForPackName (char *pack_name)
void D_IdentifyVersion (void)
void D_SetGameDescription (void)
static boolean D_AddFile (char *filename)
void PrintDehackedBanners (void)
static void InitGameVersion (void)
void PrintGameVersion (void)
static void D_Endoom (void)
void D_DoomMain (void)
Variables
char * savegamedir
char * iwadfile
boolean devparm
boolean nomonsters
boolean respawnparm
boolean fastparm
boolean inhelpscreens
skill_t startskill
int startepisode
int startmap
boolean autostart
int startloadgame
boolean advancedemo
boolean storedemo
boolean bfgedition
boolean main_loop_started = false
char wadfile [1024]
char mapdir [1024]
int show_endoom = 1
gamestate_t wipegamestate = GS_DEMOSCREEN
boolean setsizeneeded
int showMessages
int demosequence
int pagetic
char * pagename
static char * banners []
char title [128]
static char * copyright_banners []
struct {
char * description
char * cmdline
GameVersion_t version
} gameversions []
Function Documentation
D_AddFile()
static boolean D_AddFile (char * filename) static
Definition at line 868 of file d_main.c.
 {
     wad_file_t *handle;
     printf(" adding %s\n", filename);
     handle = W_AddFile(filename);
     return handle != NULL;
 }
References NULL, printf(), and W_AddFile().
Referenced by D_DoomMain().
D_AdvanceDemo()
void D_AdvanceDemo (void)
Definition at line 496 of file d_main.c.
 {
     advancedemo = true;
 }
References advancedemo.
Referenced by D_PageTicker(), D_StartTitle(), and G_CheckDemoStatus().
D_BindVariables()
void D_BindVariables (void)
Definition at line 335 of file d_main.c.
 {
     int i;
     M_ApplyPlatformDefaults();
     I_BindVideoVariables();
     I_BindJoystickVariables();
     I_BindSoundVariables();
     M_BindBaseControls();
     M_BindWeaponControls();
     M_BindMapControls();
     M_BindMenuControls();
     M_BindChatControls(MAXPLAYERS);
     key_multi_msgplayer[0] = HUSTR_KEYGREEN;
     key_multi_msgplayer[1] = HUSTR_KEYINDIGO;
     key_multi_msgplayer[2] = HUSTR_KEYBROWN;
     key_multi_msgplayer[3] = HUSTR_KEYRED;
 #ifdef FEATURE_MULTIPLAYER
     NET_BindVariables();
 #endif
     M_BindVariable("mouse_sensitivity",      &mouseSensitivity);
     M_BindVariable("sfx_volume",             &sfxVolume);
     M_BindVariable("music_volume",           &musicVolume);
     M_BindVariable("show_messages",          &showMessages);
     M_BindVariable("screenblocks",           &screenblocks);
     M_BindVariable("detaillevel",            &detailLevel);
     M_BindVariable("snd_channels",           &snd_channels);
     M_BindVariable("vanilla_savegame_limit", &vanilla_savegame_limit);
     M_BindVariable("vanilla_demo_limit",     &vanilla_demo_limit);
     M_BindVariable("show_endoom",            &show_endoom);
     // Multiplayer chat macros
     for (i=0; i<10; ++i)
     {
         char buf[12];
         M_snprintf(buf, sizeof(buf), "chatmacro%i", i);
         M_BindVariable(buf, &chat_macros[i]);
     }
 }
References buf, chat_macros, detailLevel, HUSTR_KEYBROWN, HUSTR_KEYGREEN, HUSTR_KEYINDIGO, HUSTR_KEYRED, i, I_BindJoystickVariables(), I_BindSoundVariables(), I_BindVideoVariables(), key_multi_msgplayer, M_ApplyPlatformDefaults(), M_BindBaseControls(), M_BindChatControls(), M_BindMapControls(), M_BindMenuControls(), M_BindVariable(), M_BindWeaponControls(), M_snprintf(), MAXPLAYERS, mouseSensitivity, musicVolume, NET_BindVariables(), screenblocks, sfxVolume, show_endoom, showMessages, snd_channels, vanilla_demo_limit, and vanilla_savegame_limit.
Referenced by D_DoomMain().
D_CheckNetGame()
void D_CheckNetGame (void)
Definition at line 240 of file d_net.c.
 {
     net_gamesettings_t settings;
     if (netgame)
     {
         autostart = true;
     }
     D_RegisterLoopCallbacks(&doom_loop_interface);
     SaveGameSettings(&settings);
     D_StartNetGame(&settings, NULL);
     LoadGameSettings(&settings);
     DEH_printf("startskill %i  deathmatch: %i  startmap: %i  startepisode: %i\n",
                startskill, deathmatch, startmap, startepisode);
     DEH_printf("player %i of %i (%i nodes)\n",
                consoleplayer+1, settings.num_players, settings.num_players);
     // Show players here; the server might have specified a time limit
     if (timelimit > 0 && deathmatch)
     {
         // Gross hack to work like Vanilla:
         if (timelimit == 20 && M_CheckParm("-avg"))
         {
             DEH_printf("Austin Virtual Gaming: Levels will end "
                            "after 20 minutes\n");
         }
         else
         {
             DEH_printf("Levels will end after %d minute", timelimit);
             if (timelimit > 1)
                 printf("s");
             printf(".\n");
         }
     }
 }
References autostart, consoleplayer, D_RegisterLoopCallbacks(), D_StartNetGame(), deathmatch, DEH_printf, doom_loop_interface, LoadGameSettings(), M_CheckParm(), netgame, NULL, net_gamesettings_t::num_players, printf(), SaveGameSettings(), startepisode, startmap, startskill, and timelimit.
Referenced by D_DoomMain().
D_ConnectNetGame()
void D_ConnectNetGame (void)
Definition at line 215 of file d_net.c.
 {
     net_connect_data_t connect_data;
     InitConnectData(&connect_data);
     netgame = D_InitNetGame(&connect_data);
     // @category net
     //
     // Start the game playing as though in a netgame with a single
     // player.  This can also be used to play back single player netgame
     // demos.
     //
     if (M_CheckParm("-solo-net") > 0)
     {
         netgame = true;
     }
 }
References D_InitNetGame(), InitConnectData(), M_CheckParm(), and netgame.
Referenced by D_DoomMain().
D_Display()
void D_Display (void)
Definition at line 169 of file d_main.c.
 {
     static  boolean     viewactivestate = false;
     static  boolean     menuactivestate = false;
     static  boolean     inhelpscreensstate = false;
     static  boolean     fullscreen = false;
     static  gamestate_t     oldgamestate = -1;
     static  int         borderdrawcount;
     int             nowtime;
     int             tics;
     int             wipestart;
     int             y;
     boolean         done;
     boolean         wipe;
     boolean         redrawsbar;
     if (nodrawers)
         return;                    // for comparative timing / profiling
     redrawsbar = false;
     // change the view size if needed
     if (setsizeneeded)
     {
         R_ExecuteSetViewSize ();
         oldgamestate = -1;                      // force background redraw
         borderdrawcount = 3;
     }
     // save the current screen if about to wipe
     if (gamestate != wipegamestate)
         {
         wipe = true;
         wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
     }
     else
         wipe = false;
     if (gamestate == GS_LEVEL && gametic)
         HU_Erase();
     // do buffered drawing
     switch (gamestate)
     {
       case GS_LEVEL:
         if (!gametic)
             break;
         if (automapactive)
             AM_Drawer ();
         if (wipe || (viewheight != 200 && fullscreen) )
             redrawsbar = true;
         if (inhelpscreensstate && !inhelpscreens)
             redrawsbar = true;              // just put away the help screen
         ST_Drawer (viewheight == 200, redrawsbar );
         fullscreen = viewheight == 200;
         break;
       case GS_INTERMISSION:
         WI_Drawer ();
         break;
       case GS_FINALE:
         F_Drawer ();
         break;
       case GS_DEMOSCREEN:
         D_PageDrawer ();
         break;
     }
     // draw buffered stuff to screen
     I_UpdateNoBlit ();
     // draw the view directly
     if (gamestate == GS_LEVEL && !automapactive && gametic)
         R_RenderPlayerView (&players[displayplayer]);
     if (gamestate == GS_LEVEL && gametic)
         HU_Drawer ();
     // clean up border stuff
     if (gamestate != oldgamestate && gamestate != GS_LEVEL)
         I_SetPalette (W_CacheLumpName (DEH_String("PLAYPAL"),PU_CACHE));
     // see if the border needs to be initially drawn
     if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
     {
         viewactivestate = false;        // view was not active
         R_FillBackScreen ();    // draw the pattern into the back screen
     }
     // see if the border needs to be updated to the screen
     if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != 320)
     {
         if (menuactive || menuactivestate || !viewactivestate)
             borderdrawcount = 3;
         if (borderdrawcount)
         {
             R_DrawViewBorder ();    // erase old menu stuff
             borderdrawcount--;
         }
     }
     if (testcontrols)
     {
         // Box showing current mouse speed
         V_DrawMouseSpeedBox(testcontrols_mousespeed);
     }
     menuactivestate = menuactive;
     viewactivestate = viewactive;
     inhelpscreensstate = inhelpscreens;
     oldgamestate = wipegamestate = gamestate;
     // draw pause pic
     if (paused)
     {
         if (automapactive)
             y = 4;
         else
             y = viewwindowy+4;
         V_DrawPatchDirect(viewwindowx + (scaledviewwidth - 68) / 2, y,
                               W_CacheLumpName (DEH_String("M_PAUSE"), PU_CACHE));
     }
     // menus go directly to the screen
     M_Drawer ();          // menu is drawn even on top of everything
     NetUpdate ();         // send out any new accumulation
     // normal update
     if (!wipe)
     {
     I_FinishUpdate ();              // page flip or blit buffer
     return;
     }
     // wipe update
     wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
     wipestart = I_GetTime () - 1;
     do
     {
     do
     {
         nowtime = I_GetTime ();
         tics = nowtime - wipestart;
             I_Sleep(1);
     } while (tics <= 0);
     wipestart = nowtime;
     done = wipe_ScreenWipe(wipe_Melt
                    , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
     I_UpdateNoBlit ();
     M_Drawer ();                            // menu is drawn even on top of wipes
     I_FinishUpdate ();                      // page flip or blit buffer
     } while (!done);
 }
References AM_Drawer(), automapactive, D_PageDrawer(), DEH_String, displayplayer, F_Drawer(), fullscreen, gamestate, gametic, GS_DEMOSCREEN, GS_FINALE, GS_INTERMISSION, GS_LEVEL, HU_Drawer(), HU_Erase(), I_FinishUpdate(), I_GetTime(), I_SetPalette(), I_Sleep(), I_UpdateNoBlit(), inhelpscreens, M_Drawer(), menuactive, NetUpdate(), nodrawers, oldgamestate, paused, players, PU_CACHE, R_DrawViewBorder(), R_ExecuteSetViewSize(), R_FillBackScreen(), R_RenderPlayerView(), scaledviewwidth, SCREENHEIGHT, SCREENWIDTH, setsizeneeded, ST_Drawer(), testcontrols, testcontrols_mousespeed, V_DrawMouseSpeedBox(), V_DrawPatchDirect(), viewactive, viewheight, viewwindowx, viewwindowy, W_CacheLumpName(), WI_Drawer(), wipe_EndScreen(), wipe_Melt, wipe_ScreenWipe(), wipe_StartScreen(), wipegamestate, and y.
Referenced by doomgeneric_Tick().
D_DoAdvanceDemo()
void D_DoAdvanceDemo (void)
Definition at line 506 of file d_main.c.
 {
     players[consoleplayer].playerstate = PST_LIVE;  // not reborn
     advancedemo = false;
     usergame = false;               // no save / end game here
     paused = false;
     gameaction = ga_nothing;
     // The Ultimate Doom executable changed the demo sequence to add
     // a DEMO4 demo.  Final Doom was based on Ultimate, so also
     // includes this change; however, the Final Doom IWADs do not
     // include a DEMO4 lump, so the game bombs out with an error
     // when it reaches this point in the demo sequence.
     // However! There is an alternate version of Final Doom that
     // includes a fixed executable.
     if (gameversion == exe_ultimate || gameversion == exe_final)
       demosequence = (demosequence+1)%7;
     else
       demosequence = (demosequence+1)%6;
     switch (demosequence)
     {
       case 0:
     if ( gamemode == commercial )
         pagetic = TICRATE * 11;
     else
         pagetic = 170;
     gamestate = GS_DEMOSCREEN;
     pagename = DEH_String("TITLEPIC");
     if ( gamemode == commercial )
       S_StartMusic(mus_dm2ttl);
     else
       S_StartMusic (mus_intro);
     break;
       case 1:
     G_DeferedPlayDemo(DEH_String("demo1"));
     break;
       case 2:
     pagetic = 200;
     gamestate = GS_DEMOSCREEN;
     pagename = DEH_String("CREDIT");
     break;
       case 3:
     G_DeferedPlayDemo(DEH_String("demo2"));
     break;
       case 4:
     gamestate = GS_DEMOSCREEN;
     if ( gamemode == commercial)
     {
         pagetic = TICRATE * 11;
         pagename = DEH_String("TITLEPIC");
         S_StartMusic(mus_dm2ttl);
     }
     else
     {
         pagetic = 200;
         if ( gamemode == retail )
           pagename = DEH_String("CREDIT");
         else
           pagename = DEH_String("HELP2");
     }
     break;
       case 5:
     G_DeferedPlayDemo(DEH_String("demo3"));
     break;
         // THE DEFINITIVE DOOM Special Edition demo
       case 6:
     G_DeferedPlayDemo(DEH_String("demo4"));
     break;
     }
     // The Doom 3: BFG Edition version of doom2.wad does not have a
     // TITLETPIC lump. Use INTERPIC instead as a workaround.
     if (bfgedition && !strcasecmp(pagename, "TITLEPIC")
         && W_CheckNumForName("titlepic") < 0)
     {
         pagename = DEH_String("INTERPIC");
     }
 }
References advancedemo, bfgedition, commercial, consoleplayer, DEH_String, demosequence, exe_final, exe_ultimate, G_DeferedPlayDemo(), ga_nothing, gameaction, gamemode, gamestate, gameversion, GS_DEMOSCREEN, mus_dm2ttl, mus_intro, pagename, pagetic, paused, players, player_s::playerstate, PST_LIVE, retail, S_StartMusic(), strcasecmp(), TICRATE, usergame, and W_CheckNumForName().
Referenced by RunTic().
D_DoomLoop()
void D_DoomLoop (void)
Definition at line 424 of file d_main.c.
 {
     if (bfgedition &&
         (demorecording || (gameaction == ga_playdemo) || netgame))
     {
         printf(" WARNING: You are playing using one of the Doom Classic\n"
                " IWAD files shipped with the Doom 3: BFG Edition. These are\n"
                " known to be incompatible with the regular IWAD files and\n"
                " may cause demos and network games to get out of sync.\n");
     }
     if (demorecording)
         G_BeginRecording ();
     main_loop_started = true;
     TryRunTics();
     I_SetWindowTitle(gamedescription);
     I_GraphicsCheckCommandLine();
     I_SetGrabMouseCallback(D_GrabMouseCallback);
     I_InitGraphics();
     I_EnableLoadingDisk();
     V_RestoreBuffer();
     R_ExecuteSetViewSize();
     D_StartGameLoop();
     if (testcontrols)
     {
         wipegamestate = gamestate;
     }
     doomgeneric_Tick();
 }
References bfgedition, D_GrabMouseCallback(), D_StartGameLoop(), demorecording, doomgeneric_Tick(), G_BeginRecording(), ga_playdemo, gameaction, gamedescription, gamestate, I_EnableLoadingDisk(), I_GraphicsCheckCommandLine(), I_InitGraphics(), I_SetGrabMouseCallback(), I_SetWindowTitle(), main_loop_started, netgame, printf(), R_ExecuteSetViewSize(), testcontrols, TryRunTics(), V_RestoreBuffer(), and wipegamestate.
Referenced by D_DoomMain().
D_DoomMain()
void D_DoomMain (void)
Definition at line 1163 of file d_main.c.
 {
     int p;
     char file[256];
     char demolumpname[9];
 #if ORIGCODE
     int numiwadlumps;
 #endif
     I_AtExit(D_Endoom, false);
     // print banner
     I_PrintBanner(PACKAGE_STRING);
     DEH_printf("Z_Init: Init zone memory allocation daemon. \n");
     Z_Init ();
 #ifdef FEATURE_MULTIPLAYER
     // @category net
     //
     // Start a dedicated server, routing packets but not participating
     // in the game itself.
     //
     if (M_CheckParm("-dedicated") > 0)
     {
         printf("Dedicated server mode.\n");
         NET_DedicatedServer();
         // Never returns
     }
     // @category net
     //
     // Query the Internet master server for a global list of active
     // servers.
     //
     if (M_CheckParm("-search"))
     {
         NET_MasterQuery();
         exit(0);
     }
     // @arg <address>
     // @category net
     //
     // Query the status of the server running on the given IP
     // address.
     //
     p = M_CheckParmWithArgs("-query", 1);
     if (p)
     {
         NET_QueryAddress(myargv[p+1]);
         exit(0);
     }
     // @category net
     //
     // Search the local LAN for running servers.
     //
     if (M_CheckParm("-localsearch"))
     {
         NET_LANQuery();
         exit(0);
     }
 #endif
     // @vanilla
     //
     // Disable monsters.
     //
     nomonsters = M_CheckParm ("-nomonsters");
     // @vanilla
     //
     // Monsters respawn after being killed.
     //
     respawnparm = M_CheckParm ("-respawn");
     // @vanilla
     //
     // Monsters move faster.
     //
     fastparm = M_CheckParm ("-fast");
     // @vanilla
     //
     // Developer mode.  F1 saves a screenshot in the current working
     // directory.
     //
     devparm = M_CheckParm ("-devparm");
     I_DisplayFPSDots(devparm);
     // @category net
     // @vanilla
     //
     // Start a deathmatch game.
     //
     if (M_CheckParm ("-deathmatch"))
     deathmatch = 1;
     // @category net
     // @vanilla
     //
     // Start a deathmatch 2.0 game.  Weapons do not stay in place and
     // all items respawn after 30 seconds.
     //
     if (M_CheckParm ("-altdeath"))
     deathmatch = 2;
     if (devparm)
     DEH_printf(D_DEVSTR);
     // find which dir to use for config files
 #ifdef _WIN32
     // @platform windows
     // @vanilla
     //
     // Save configuration data and savegames in c:\doomdata,
     // allowing play from CD.
     //
     if (M_ParmExists("-cdrom"))
     {
         printf(D_CDROM);
         M_SetConfigDir("c:\\doomdata\\");
     }
     else
 #endif
     {
         // Auto-detect the configuration dir.
         M_SetConfigDir(NULL);
     }
     // @arg <x>
     // @vanilla
     //
     // Turbo mode.  The player's speed is multiplied by x%.  If unspecified,
     // x defaults to 200.  Values are rounded up to 10 and down to 400.
     //
     if ( (p=M_CheckParm ("-turbo")) )
     {
     int     scale = 200;
     extern int forwardmove[2];
     extern int sidemove[2];
     if (p<myargc-1)
         scale = atoi (myargv[p+1]);
     if (scale < 10)
         scale = 10;
     if (scale > 400)
         scale = 400;
         DEH_printf("turbo scale: %i%%\n", scale);
     forwardmove[0] = forwardmove[0]*scale/100;
     forwardmove[1] = forwardmove[1]*scale/100;
     sidemove[0] = sidemove[0]*scale/100;
     sidemove[1] = sidemove[1]*scale/100;
     }
     // init subsystems
     DEH_printf("V_Init: allocate screens.\n");
     V_Init ();
     // Load configuration files before initialising other subsystems.
     DEH_printf("M_LoadDefaults: Load system defaults.\n");
     M_SetConfigFilenames("default.cfg", PROGRAM_PREFIX "doom.cfg");
     D_BindVariables();
     M_LoadDefaults();
     // Save configuration at exit.
     I_AtExit(M_SaveDefaults, false);
     // Find main IWAD file and load it.
     iwadfile = D_FindIWAD(IWAD_MASK_DOOM, &gamemission);
     // None found?
     if (iwadfile == NULL)
     {
         I_Error("Game mode indeterminate.  No IWAD file was found.  Try\n"
                 "specifying one with the '-iwad' command line parameter.\n");
     }
     modifiedgame = false;
     DEH_printf("W_Init: Init WADfiles.\n");
     D_AddFile(iwadfile);
 #if ORIGCODE
     numiwadlumps = numlumps;
 #endif
     W_CheckCorrectIWAD(doom);
     // Now that we've loaded the IWAD, we can figure out what gamemission
     // we're playing and which version of Vanilla Doom we need to emulate.
     D_IdentifyVersion();
     InitGameVersion();
 #if ORIGCODE
     // @category mod
     //
     // Disable automatic loading of Dehacked patches for certain
     // IWAD files.
     //
     if (!M_ParmExists("-nodeh"))
     {
         // Some IWADs have dehacked patches that need to be loaded for
         // them to be played properly.
         LoadIwadDeh();
     }
 #endif
     // Doom 3: BFG Edition includes modified versions of the classic
     // IWADs which can be identified by an additional DMENUPIC lump.
     // Furthermore, the M_GDHIGH lumps have been modified in a way that
     // makes them incompatible to Vanilla Doom and the modified version
     // of doom2.wad is missing the TITLEPIC lump.
     // We specifically check for DMENUPIC here, before PWADs have been
     // loaded which could probably include a lump of that name.
     if (W_CheckNumForName("dmenupic") >= 0)
     {
         printf("BFG Edition: Using workarounds as needed.\n");
         bfgedition = true;
         // BFG Edition changes the names of the secret levels to
         // censor the Wolfenstein references. It also has an extra
         // secret level (MAP33). In Vanilla Doom (meaning the DOS
         // version), MAP33 overflows into the Plutonia level names
         // array, so HUSTR_33 is actually PHUSTR_1.
         DEH_AddStringReplacement(HUSTR_31, "level 31: idkfa");
         DEH_AddStringReplacement(HUSTR_32, "level 32: keen");
         DEH_AddStringReplacement(PHUSTR_1, "level 33: betray");
         // The BFG edition doesn't have the "low detail" menu option (fair
         // enough). But bizarrely, it reuses the M_GDHIGH patch as a label
         // for the options menu (says "Fullscreen:"). Why the perpetrators
         // couldn't just add a new graphic lump and had to reuse this one,
         // I don't know.
         //
         // The end result is that M_GDHIGH is too wide and causes the game
         // to crash. As a workaround to get a minimum level of support for
         // the BFG edition IWADs, use the "ON"/"OFF" graphics instead.
         DEH_AddStringReplacement("M_GDHIGH", "M_MSGON");
         DEH_AddStringReplacement("M_GDLOW", "M_MSGOFF");
     }
 #ifdef FEATURE_DEHACKED
     // Load Dehacked patches specified on the command line with -deh.
     // Note that there's a very careful and deliberate ordering to how
     // Dehacked patches are loaded. The order we use is:
     //  1. IWAD dehacked patches.
     //  2. Command line dehacked patches specified with -deh.
     //  3. PWAD dehacked patches in DEHACKED lumps.
     DEH_ParseCommandLine();
 #endif
     // Load PWAD files.
     modifiedgame = W_ParseCommandLine();
     // Debug:
 //    W_PrintDirectory();
     // @arg <demo>
     // @category demo
     // @vanilla
     //
     // Play back the demo named demo.lmp.
     //
     p = M_CheckParmWithArgs ("-playdemo", 1);
     if (!p)
     {
         // @arg <demo>
         // @category demo
         // @vanilla
         //
         // Play back the demo named demo.lmp, determining the framerate
         // of the screen.
         //
     p = M_CheckParmWithArgs("-timedemo", 1);
     }
     if (p)
     {
         // With Vanilla you have to specify the file without extension,
         // but make that optional.
         if (M_StringEndsWith(myargv[p + 1], ".lmp"))
         {
             M_StringCopy(file, myargv[p + 1], sizeof(file));
         }
         else
         {
             DEH_snprintf(file, sizeof(file), "%s.lmp", myargv[p+1]);
         }
         if (D_AddFile(file))
         {
             M_StringCopy(demolumpname, lumpinfo[numlumps - 1].name,
                          sizeof(demolumpname));
         }
         else
         {
             // If file failed to load, still continue trying to play
             // the demo in the same way as Vanilla Doom.  This makes
             // tricks like "-playdemo demo1" possible.
             M_StringCopy(demolumpname, myargv[p + 1], sizeof(demolumpname));
         }
         printf("Playing demo %s.\n", file);
     }
     I_AtExit((atexit_func_t) G_CheckDemoStatus, true);
     // Generate the WAD hash table.  Speed things up a bit.
     W_GenerateHashTable();
     // Load DEHACKED lumps from WAD files - but only if we give the right
     // command line parameter.
 #if ORIGCODE
     // @category mod
     //
     // Load Dehacked patches from DEHACKED lumps contained in one of the
     // loaded PWAD files.
     //
     if (M_ParmExists("-dehlump"))
     {
         int i, loaded = 0;
         for (i = numiwadlumps; i < numlumps; ++i)
         {
             if (!strncmp(lumpinfo[i].name, "DEHACKED", 8))
             {
                 DEH_LoadLump(i, false, false);
                 loaded++;
             }
         }
         printf("  loaded %i DEHACKED lumps from PWAD files.\n", loaded);
     }
 #endif
     // Set the gamedescription string. This is only possible now that
     // we've finished loading Dehacked patches.
     D_SetGameDescription();
 #ifdef _WIN32
     // In -cdrom mode, we write savegames to c:\doomdata as well as configs.
     if (M_ParmExists("-cdrom"))
     {
         savegamedir = configdir;
     }
     else
 #endif
     {
         savegamedir = M_GetSaveGameDir(D_SaveGameIWADName(gamemission));
     }
     // Check for -file in shareware
     if (modifiedgame)
     {
     // These are the lumps that will be checked in IWAD,
     // if any one is not present, execution will be aborted.
     char name[23][8]=
     {
         "e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
         "e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
         "dphoof","bfgga0","heada1","cybra1","spida1d1"
     };
     int i;
     if ( gamemode == shareware)
         I_Error(DEH_String("\nYou cannot -file with the shareware "
                    "version. Register!"));
     // Check for fake IWAD with right name,
     // but w/o all the lumps of the registered version.
     if (gamemode == registered)
         for (i = 0;i < 23; i++)
         if (W_CheckNumForName(name[i])<0)
             I_Error(DEH_String("\nThis is not the registered version."));
     }
     if (W_CheckNumForName("SS_START") >= 0
      || W_CheckNumForName("FF_END") >= 0)
     {
         I_PrintDivider();
         printf(" WARNING: The loaded WAD file contains modified sprites or\n"
                " floor textures.  You may want to use the '-merge' command\n"
                " line option instead of '-file'.\n");
     }
     I_PrintStartupBanner(gamedescription);
     PrintDehackedBanners();
     // Freedoom's IWADs are Boom-compatible, which means they usually
     // don't work in Vanilla (though FreeDM is okay). Show a warning
     // message and give a link to the website.
     if (W_CheckNumForName("FREEDOOM") >= 0 && W_CheckNumForName("FREEDM") < 0)
     {
         printf(" WARNING: You are playing using one of the Freedoom IWAD\n"
                " files, which might not work in this port. See this page\n"
                " for more information on how to play using Freedoom:\n"
                "   http://www.chocolate-doom.org/wiki/index.php/Freedoom\n");
         I_PrintDivider();
     }
     DEH_printf("I_Init: Setting up machine state.\n");
     I_CheckIsScreensaver();
     I_InitTimer();
     I_InitJoystick();
     I_InitSound(true);
     I_InitMusic();
 #ifdef FEATURE_MULTIPLAYER
     printf ("NET_Init: Init network subsystem.\n");
     NET_Init ();
 #endif
     // Initial netgame startup. Connect to server etc.
     D_ConnectNetGame();
     // get skill / episode / map from parms
     startskill = sk_medium;
     startepisode = 1;
     startmap = 1;
     autostart = false;
     // @arg <skill>
     // @vanilla
     //
     // Set the game skill, 1-5 (1: easiest, 5: hardest).  A skill of
     // 0 disables all monsters.
     //
     p = M_CheckParmWithArgs("-skill", 1);
     if (p)
     {
     startskill = myargv[p+1][0]-'1';
     autostart = true;
     }
     // @arg <n>
     // @vanilla
     //
     // Start playing on episode n (1-4)
     //
     p = M_CheckParmWithArgs("-episode", 1);
     if (p)
     {
     startepisode = myargv[p+1][0]-'0';
     startmap = 1;
     autostart = true;
     }
     timelimit = 0;
     // @arg <n>
     // @category net
     // @vanilla
     //
     // For multiplayer games: exit each level after n minutes.
     //
     p = M_CheckParmWithArgs("-timer", 1);
     if (p)
     {
     timelimit = atoi(myargv[p+1]);
     }
     // @category net
     // @vanilla
     //
     // Austin Virtual Gaming: end levels after 20 minutes.
     //
     p = M_CheckParm ("-avg");
     if (p)
     {
     timelimit = 20;
     }
     // @arg [<x> <y> | <xy>]
     // @vanilla
     //
     // Start a game immediately, warping to ExMy (Doom 1) or MAPxy
     // (Doom 2)
     //
     p = M_CheckParmWithArgs("-warp", 1);
     if (p)
     {
         if (gamemode == commercial)
             startmap = atoi (myargv[p+1]);
         else
         {
             startepisode = myargv[p+1][0]-'0';
             if (p + 2 < myargc)
             {
                 startmap = myargv[p+2][0]-'0';
             }
             else
             {
                 startmap = 1;
             }
         }
         autostart = true;
     }
     // Undocumented:
     // Invoked by setup to test the controls.
     p = M_CheckParm("-testcontrols");
     if (p > 0)
     {
         startepisode = 1;
         startmap = 1;
         autostart = true;
         testcontrols = true;
     }
     // Check for load game parameter
     // We do this here and save the slot number, so that the network code
     // can override it or send the load slot to other players.
     // @arg <s>
     // @vanilla
     //
     // Load the game in slot s.
     //
     p = M_CheckParmWithArgs("-loadgame", 1);
     if (p)
     {
         startloadgame = atoi(myargv[p+1]);
     }
     else
     {
         // Not loading a game
         startloadgame = -1;
     }
     DEH_printf("M_Init: Init miscellaneous info.\n");
     M_Init ();
     DEH_printf("R_Init: Init DOOM refresh daemon - ");
     R_Init ();
     DEH_printf("\nP_Init: Init Playloop state.\n");
     P_Init ();
     DEH_printf("S_Init: Setting up sound.\n");
     S_Init (sfxVolume * 8, musicVolume * 8);
     DEH_printf("D_CheckNetGame: Checking network game status.\n");
     D_CheckNetGame ();
     PrintGameVersion();
     DEH_printf("HU_Init: Setting up heads up display.\n");
     HU_Init ();
     DEH_printf("ST_Init: Init status bar.\n");
     ST_Init ();
     // If Doom II without a MAP01 lump, this is a store demo.
     // Moved this here so that MAP01 isn't constantly looked up
     // in the main loop.
     if (gamemode == commercial && W_CheckNumForName("map01") < 0)
         storedemo = true;
     if (M_CheckParmWithArgs("-statdump", 1))
     {
         I_AtExit(StatDump, true);
         DEH_printf("External statistics registered.\n");
     }
     // @arg <x>
     // @category demo
     // @vanilla
     //
     // Record a demo named x.lmp.
     //
     p = M_CheckParmWithArgs("-record", 1);
     if (p)
     {
         G_RecordDemo (myargv[p+1]);
         autostart = true;
     }
     p = M_CheckParmWithArgs("-playdemo", 1);
     if (p)
     {
         singledemo = true;              // quit after one demo
         G_DeferedPlayDemo (demolumpname);
         D_DoomLoop ();
         return;
     }
     p = M_CheckParmWithArgs("-timedemo", 1);
     if (p)
     {
         G_TimeDemo (demolumpname);
         D_DoomLoop ();
         return;
     }
     if (startloadgame >= 0)
     {
         M_StringCopy(file, P_SaveGameFile(startloadgame), sizeof(file));
         G_LoadGame(file);
     }
     if (gameaction != ga_loadgame )
     {
         if (autostart || netgame)
             G_InitNew (startskill, startepisode, startmap);
         else
             D_StartTitle ();                // start up intro loop
     }
     D_DoomLoop ();
 }
References atoi(), autostart, bfgedition, commercial, configdir, D_AddFile(), D_BindVariables(), D_CDROM, D_CheckNetGame(), D_ConnectNetGame(), D_DEVSTR, D_DoomLoop(), D_Endoom(), D_FindIWAD(), D_IdentifyVersion(), D_SaveGameIWADName(), D_SetGameDescription(), D_StartTitle(), deathmatch, DEH_AddStringReplacement, DEH_LoadLump(), DEH_ParseCommandLine(), DEH_printf, DEH_snprintf, DEH_String, devparm, doom, exit(), fastparm, forwardmove, G_CheckDemoStatus(), G_DeferedPlayDemo(), G_InitNew(), G_LoadGame(), G_RecordDemo(), G_TimeDemo(), ga_loadgame, gameaction, gamedescription, gamemission, gamemode, HU_Init(), HUSTR_31, HUSTR_32, i, I_AtExit(), I_CheckIsScreensaver(), I_DisplayFPSDots(), I_Error(), I_InitJoystick(), I_InitMusic(), I_InitSound(), I_InitTimer(), I_PrintBanner(), I_PrintDivider(), I_PrintStartupBanner(), InitGameVersion(), IWAD_MASK_DOOM, iwadfile, lumpinfo, M_CheckParm(), M_CheckParmWithArgs(), M_GetSaveGameDir(), M_Init(), M_LoadDefaults(), M_ParmExists(), M_SaveDefaults(), M_SetConfigDir(), M_SetConfigFilenames(), M_StringCopy(), M_StringEndsWith(), modifiedgame, musicVolume, myargc, myargv, name, NET_DedicatedServer(), NET_Init(), NET_LANQuery(), NET_MasterQuery(), NET_QueryAddress(), netgame, nomonsters, NULL, numlumps, p, P_Init(), P_SaveGameFile(), PACKAGE_STRING, PHUSTR_1, PrintDehackedBanners(), printf(), PrintGameVersion(), PROGRAM_PREFIX, R_Init(), registered, respawnparm, S_Init(), savegamedir, sfxVolume, shareware, sidemove, singledemo, sk_medium, ST_Init(), startepisode, startloadgame, startmap, startskill, StatDump(), storedemo, strncmp(), testcontrols, timelimit, V_Init(), W_CheckCorrectIWAD(), W_CheckNumForName(), W_GenerateHashTable(), W_ParseCommandLine(), and Z_Init().
Referenced by doomgeneric_Create().
D_Endoom()
static void D_Endoom (void) static
Definition at line 1067 of file d_main.c.
 {
     byte *endoom;
     // Don't show ENDOOM if we have it disabled, or we're running
     // in screensaver or control test mode. Only show it once the
     // game has actually started.
     if (!show_endoom || !main_loop_started
      || screensaver_mode || M_CheckParm("-testcontrols") > 0)
     {
         return;
     }
     endoom = W_CacheLumpName(DEH_String("ENDOOM"), PU_STATIC);
     I_Endoom(endoom);
     exit(0);
 }
References DEH_String, exit(), I_Endoom(), M_CheckParm(), main_loop_started, PU_STATIC, screensaver_mode, show_endoom, and W_CacheLumpName().
Referenced by D_DoomMain().
D_GrabMouseCallback()
boolean D_GrabMouseCallback (void)
Definition at line 388 of file d_main.c.
 {
     // Drone players don't need mouse focus
     if (drone)
         return false;
     // when menu is active or game is paused, release the mouse
     if (menuactive || paused)
         return false;
     // only grab mouse when playing levels (but not demos)
     return (gamestate == GS_LEVEL) && !demoplayback && !advancedemo;
 }
References advancedemo, demoplayback, drone, gamestate, GS_LEVEL, menuactive, and paused.
Referenced by D_DoomLoop().
D_IdentifyVersion()
void D_IdentifyVersion (void)
Definition at line 722 of file d_main.c.
 {
     // gamemission is set up by the D_FindIWAD function.  But if
     // we specify '-iwad', we have to identify using
     // IdentifyIWADByName.  However, if the iwad does not match
     // any known IWAD name, we may have a dilemma.  Try to
     // identify by its contents.
     if (gamemission == none)
     {
         unsigned int i;
         for (i=0; i<numlumps; ++i)
         {
             if (!strncasecmp(lumpinfo[i].name, "MAP01", 8))
             {
                 gamemission = doom2;
                 break;
             }
             else if (!strncasecmp(lumpinfo[i].name, "E1M1", 8))
             {
                 gamemission = doom;
                 break;
             }
         }
         if (gamemission == none)
         {
             // Still no idea.  I don't think this is going to work.
             I_Error("Unknown or invalid IWAD file.");
         }
     }
     // Make sure gamemode is set up correctly
     if (logical_gamemission == doom)
     {
         // Doom 1.  But which version?
         if (W_CheckNumForName("E4M1") > 0)
         {
             // Ultimate Doom
             gamemode = retail;
         }
         else if (W_CheckNumForName("E3M1") > 0)
         {
             gamemode = registered;
         }
         else
         {
             gamemode = shareware;
         }
     }
     else
     {
         int p;
         // Doom 2 of some kind.
         gamemode = commercial;
         // We can manually override the gamemission that we got from the
         // IWAD detection code. This allows us to eg. play Plutonia 2
         // with Freedoom and get the right level names.
         // @arg <pack>
         //
         // Explicitly specify a Doom II "mission pack" to run as, instead of
         // detecting it based on the filename. Valid values are: "doom2",
         // "tnt" and "plutonia".
         //
         p = M_CheckParmWithArgs("-pack", 1);
         if (p > 0)
         {
             SetMissionForPackName(myargv[p + 1]);
         }
     }
 }
References commercial, doom, doom2, gamemission, gamemode, i, I_Error(), logical_gamemission, lumpinfo, M_CheckParmWithArgs(), myargv, name, none, numlumps, p, registered, retail, SetMissionForPackName(), shareware, mlibc::strncasecmp(), and W_CheckNumForName().
Referenced by D_DoomMain().
D_PageDrawer()
void D_PageDrawer (void)
Definition at line 486 of file d_main.c.
 {
     V_DrawPatch (0, 0, W_CacheLumpName(pagename, PU_CACHE));
 }
References pagename, PU_CACHE, V_DrawPatch(), and W_CacheLumpName().
Referenced by D_Display().
D_PageTicker()
void D_PageTicker (void)
Definition at line 475 of file d_main.c.
 {
     if (--pagetic < 0)
     D_AdvanceDemo ();
 }
References D_AdvanceDemo(), and pagetic.
Referenced by G_Ticker().
D_ProcessEvents()
void D_ProcessEvents (void)
Definition at line 139 of file d_main.c.
 {
     event_t*    ev;
     // IF STORE DEMO, DO NOT ACCEPT INPUT
     if (storedemo)
         return;
     while ((ev = D_PopEvent()) != NULL)
     {
     if (M_Responder (ev))
         continue;               // menu ate the event
     G_Responder (ev);
     }
 }
References D_PopEvent(), G_Responder(), M_Responder(), NULL, and storedemo.
D_SetGameDescription()
void D_SetGameDescription (void)
Definition at line 805 of file d_main.c.
 {
     boolean is_freedoom = W_CheckNumForName("FREEDOOM") >= 0,
             is_freedm = W_CheckNumForName("FREEDM") >= 0;
     gamedescription = "Unknown";
     if (logical_gamemission == doom)
     {
         // Doom 1.  But which version?
         if (is_freedoom)
         {
             gamedescription = GetGameName("Freedoom: Phase 1");
         }
         else if (gamemode == retail)
         {
             // Ultimate Doom
             gamedescription = GetGameName("The Ultimate DOOM");
         }
         else if (gamemode == registered)
         {
             gamedescription = GetGameName("DOOM Registered");
         }
         else if (gamemode == shareware)
         {
             gamedescription = GetGameName("DOOM Shareware");
         }
     }
     else
     {
         // Doom 2 of some kind.  But which mission?
         if (is_freedoom)
         {
             if (is_freedm)
             {
                 gamedescription = GetGameName("FreeDM");
             }
             else
             {
                 gamedescription = GetGameName("Freedoom: Phase 2");
             }
         }
         else if (logical_gamemission == doom2)
         {
             gamedescription = GetGameName("DOOM 2: Hell on Earth");
         }
         else if (logical_gamemission == pack_plut)
         {
             gamedescription = GetGameName("DOOM 2: Plutonia Experiment");
         }
         else if (logical_gamemission == pack_tnt)
         {
             gamedescription = GetGameName("DOOM 2: TNT - Evilution");
         }
     }
 }
References doom, doom2, gamedescription, gamemode, GetGameName(), logical_gamemission, pack_plut, pack_tnt, registered, retail, shareware, and W_CheckNumForName().
Referenced by D_DoomMain().
D_StartTitle()
void D_StartTitle (void)
Definition at line 594 of file d_main.c.
 {
     gameaction = ga_nothing;
     demosequence = -1;
     D_AdvanceDemo ();
 }
References D_AdvanceDemo(), demosequence, ga_nothing, and gameaction.
Referenced by D_DoomMain(), and M_EndGameResponse().
doomgeneric_Tick()
void doomgeneric_Tick ()
Definition at line 405 of file d_main.c.
 {
     // frame syncronous IO operations
     I_StartFrame ();
     TryRunTics (); // will run at least one tic
     S_UpdateSounds (players[consoleplayer].mo);// move positional sounds
     // Update display, next frame, with current state.
     if (screenvisible)
     {
         D_Display ();
     }
 }
References consoleplayer, D_Display(), I_StartFrame(), players, S_UpdateSounds(), screenvisible, and TryRunTics().
Referenced by D_DoomLoop(), and main().
GetGameName()
static char* GetGameName (char * gamename) static
Definition at line 643 of file d_main.c.
 {
     size_t i;
     char *deh_sub;
     for (i=0; i<arrlen(banners); ++i)
     {
         // Has the banner been replaced?
         deh_sub = DEH_String(banners[i]);
         if (deh_sub != banners[i])
         {
             size_t gamename_size;
             int version;
             // Has been replaced.
             // We need to expand via printf to include the Doom version number
             // We also need to cut off spaces to get the basic name
             gamename_size = strlen(deh_sub) + 10;
             gamename = Z_Malloc(gamename_size, PU_STATIC, 0);
             version = G_VanillaVersionCode();
             M_snprintf(gamename, gamename_size, deh_sub,
                        version / 100, version % 100);
             while (gamename[0] != '\0' && isspace((int)gamename[0]))
             {
                 memmove(gamename, gamename + 1, gamename_size - 1);
             }
             while (gamename[0] != '\0' && isspace((int)gamename[strlen(gamename)-1]))
             {
                 gamename[strlen(gamename) - 1] = '\0';
             }
             return gamename;
         }
     }
     return gamename;
 }
References arrlen, banners, DEH_String, G_VanillaVersionCode(), i, isspace(), M_snprintf(), memmove(), PU_STATIC, strlen(), and Z_Malloc().
Referenced by D_SetGameDescription().
InitGameVersion()
static void InitGameVersion (void) static
Definition at line 948 of file d_main.c.
 {
     int p;
     int i;
     // @arg <version>
     // @category compat
     //
     // Emulate a specific version of Doom.  Valid values are "1.9",
     // "ultimate", "final", "final2", "hacx" and "chex".
     //
     p = M_CheckParmWithArgs("-gameversion", 1);
     if (p)
     {
         for (i=0; gameversions[i].description != NULL; ++i)
         {
             if (!strcmp(myargv[p+1], gameversions[i].cmdline))
             {
                 gameversion = gameversions[i].version;
                 break;
             }
         }
         if (gameversions[i].description == NULL)
         {
             printf("Supported game versions:\n");
             for (i=0; gameversions[i].description != NULL; ++i)
             {
                 printf("\t%s (%s)\n", gameversions[i].cmdline,
                         gameversions[i].description);
             }
             I_Error("Unknown game version '%s'", myargv[p+1]);
         }
     }
     else
     {
         // Determine automatically
         if (gamemission == pack_chex)
         {
             // chex.exe - identified by iwad filename
             gameversion = exe_chex;
         }
         else if (gamemission == pack_hacx)
         {
             // hacx.exe: identified by iwad filename
             gameversion = exe_hacx;
         }
         else if (gamemode == shareware || gamemode == registered)
         {
             // original
             gameversion = exe_doom_1_9;
             // TODO: Detect IWADs earlier than Doom v1.9.
         }
         else if (gamemode == retail)
         {
             gameversion = exe_ultimate;
         }
         else if (gamemode == commercial)
         {
             if (gamemission == doom2)
             {
                 gameversion = exe_doom_1_9;
             }
             else
             {
                 // Final Doom: tnt or plutonia
                 // Defaults to emulating the first Final Doom executable,
                 // which has the crash in the demo loop; however, having
                 // this as the default should mean that it plays back
                 // most demos correctly.
                 gameversion = exe_final;
             }
         }
     }
     // The original exe does not support retail - 4th episode not supported
     if (gameversion < exe_ultimate && gamemode == retail)
     {
         gamemode = registered;
     }
     // EXEs prior to the Final Doom exes do not support Final Doom.
     if (gameversion < exe_final && gamemode == commercial
      && (gamemission == pack_tnt || gamemission == pack_plut))
     {
         gamemission = doom2;
     }
 }
References commercial, doom2, exe_chex, exe_doom_1_9, exe_final, exe_hacx, exe_ultimate, gamemission, gamemode, gameversion, gameversions, i, I_Error(), M_CheckParmWithArgs(), myargv, NULL, p, pack_chex, pack_hacx, pack_plut, pack_tnt, printf(), registered, retail, shareware, and strcmp().
Referenced by D_DoomMain().
PrintDehackedBanners()
void PrintDehackedBanners (void)
Definition at line 903 of file d_main.c.
 {
     size_t i;
     for (i=0; i<arrlen(copyright_banners); ++i)
     {
         char *deh_s;
         deh_s = DEH_String(copyright_banners[i]);
         if (deh_s != copyright_banners[i])
         {
             printf("%s", deh_s);
             // Make sure the modified banner always ends in a newline character.
             // If it doesn't, add a newline.  This fixes av.wad.
             if (deh_s[strlen(deh_s) - 1] != '\n')
             {
                 printf("\n");
             }
         }
     }
 }
References arrlen, copyright_banners, DEH_String, i, printf(), and strlen().
Referenced by D_DoomMain().
PrintGameVersion()
void PrintGameVersion (void)
Definition at line 1050 of file d_main.c.
 {
     int i;
     for (i=0; gameversions[i].description != NULL; ++i)
     {
         if (gameversions[i].version == gameversion)
         {
             printf("Emulating the behavior of the "
                    "'%s' executable.\n", gameversions[i].description);
             break;
         }
     }
 }
References gameversion, gameversions, i, NULL, and printf().
Referenced by D_DoomMain().
R_ExecuteSetViewSize()
void R_ExecuteSetViewSize (void)
Definition at line 667 of file r_main.c.
 {
     fixed_t cosadj;
     fixed_t dy;
     int     i;
     int     j;
     int     level;
     int     startmap;
     setsizeneeded = false;
     if (setblocks == 11)
     {
     scaledviewwidth = SCREENWIDTH;
     viewheight = SCREENHEIGHT;
     }
     else
     {
     scaledviewwidth = setblocks*32;
     viewheight = (setblocks*168/10)&~7;
     }
     detailshift = setdetail;
     viewwidth = scaledviewwidth>>detailshift;
     centery = viewheight/2;
     centerx = viewwidth/2;
     centerxfrac = centerx<<FRACBITS;
     centeryfrac = centery<<FRACBITS;
     projection = centerxfrac;
     if (!detailshift)
     {
     colfunc = basecolfunc = R_DrawColumn;
     fuzzcolfunc = R_DrawFuzzColumn;
     transcolfunc = R_DrawTranslatedColumn;
     spanfunc = R_DrawSpan;
     }
     else
     {
     colfunc = basecolfunc = R_DrawColumnLow;
     fuzzcolfunc = R_DrawFuzzColumnLow;
     transcolfunc = R_DrawTranslatedColumnLow;
     spanfunc = R_DrawSpanLow;
     }
     R_InitBuffer (scaledviewwidth, viewheight);
     R_InitTextureMapping ();
     // psprite scales
     pspritescale = FRACUNIT*viewwidth/SCREENWIDTH;
     pspriteiscale = FRACUNIT*SCREENWIDTH/viewwidth;
     // thing clipping
     for (i=0 ; i<viewwidth ; i++)
     screenheightarray[i] = viewheight;
     // planes
     for (i=0 ; i<viewheight ; i++)
     {
     dy = ((i-viewheight/2)<<FRACBITS)+FRACUNIT/2;
     dy = abs(dy);
     yslope[i] = FixedDiv ( (viewwidth<<detailshift)/2*FRACUNIT, dy);
     }
     for (i=0 ; i<viewwidth ; i++)
     {
     cosadj = abs(finecosine[xtoviewangle[i]>>ANGLETOFINESHIFT]);
     distscale[i] = FixedDiv (FRACUNIT,cosadj);
     }
     // Calculate the light levels to use
     //  for each level / scale combination.
     for (i=0 ; i< LIGHTLEVELS ; i++)
     {
     startmap = ((LIGHTLEVELS-1-i)*2)*NUMCOLORMAPS/LIGHTLEVELS;
     for (j=0 ; j<MAXLIGHTSCALE ; j++)
     {
         level = startmap - j*SCREENWIDTH/(viewwidth<<detailshift)/DISTMAP;
         if (level < 0)
         level = 0;
         if (level >= NUMCOLORMAPS)
         level = NUMCOLORMAPS-1;
         scalelight[i][j] = colormaps + level*256;
     }
     }
 }
References abs(), ANGLETOFINESHIFT, basecolfunc, centerx, centerxfrac, centery, centeryfrac, colfunc, colormaps, detailshift, DISTMAP, distscale, finecosine, FixedDiv(), FRACBITS, FRACUNIT, fuzzcolfunc, i, j, update-syscall-list::level, LIGHTLEVELS, MAXLIGHTSCALE, NUMCOLORMAPS, projection, pspriteiscale, pspritescale, R_DrawColumn(), R_DrawColumnLow(), R_DrawFuzzColumn(), R_DrawFuzzColumnLow(), R_DrawSpan(), R_DrawSpanLow(), R_DrawTranslatedColumn(), R_DrawTranslatedColumnLow(), R_InitBuffer(), R_InitTextureMapping(), scaledviewwidth, scalelight, SCREENHEIGHT, screenheightarray, SCREENWIDTH, setblocks, setdetail, setsizeneeded, spanfunc, startmap, transcolfunc, viewheight, viewwidth, xtoviewangle, and yslope.
Referenced by D_Display(), and D_DoomLoop().
SetMissionForPackName()
static void SetMissionForPackName (char * pack_name) static
Definition at line 686 of file d_main.c.
 {
     int i;
     static const struct
     {
         char *name;
         int mission;
     } packs[] = {
         { "doom2",    doom2 },
         { "tnt",      pack_tnt },
         { "plutonia", pack_plut },
     };
     for (i = 0; i < arrlen(packs); ++i)
     {
         if (!strcasecmp(pack_name, packs[i].name))
         {
             gamemission = packs[i].mission;
             return;
         }
     }
     printf("Valid mission packs are:\n");
     for (i = 0; i < arrlen(packs); ++i)
     {
         printf("\t%s\n", packs[i].name);
     }
     I_Error("Unknown mission pack name: %s", pack_name);
 }
References arrlen, doom2, gamemission, i, I_Error(), name, pack_plut, pack_tnt, printf(), and strcasecmp().
Referenced by D_IdentifyVersion().
Variable Documentation
advancedemo
boolean advancedemo
Definition at line 114 of file d_main.c.
Referenced by D_AdvanceDemo(), D_DoAdvanceDemo(), D_GrabMouseCallback(), and RunTic().
autostart
boolean autostart
Definition at line 111 of file d_main.c.
Referenced by D_CheckNetGame(), and D_DoomMain().
banners
char* banners[] static
Definition at line 606 of file d_main.c.
Referenced by GetGameName().
bfgedition
boolean bfgedition
Definition at line 120 of file d_main.c.
Referenced by D_DoAdvanceDemo(), D_DoomLoop(), and D_DoomMain().
copyright_banners
char* copyright_banners[] static
Initial value:
=
{
    "===========================================================================\n"
    "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
    "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
    "        You will not receive technical support for modified games.\n"
    "                      press enter to continue\n"
    "===========================================================================\n",
    "===========================================================================\n"
    "                 Commercial product - do not distribute!\n"
    "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
    "===========================================================================\n",
    "===========================================================================\n"
    "                                Shareware!\n"
    "===========================================================================\n"
}
Definition at line 882 of file d_main.c.
Referenced by PrintDehackedBanners().
demosequence
int demosequence
Definition at line 466 of file d_main.c.
Referenced by D_DoAdvanceDemo(), and D_StartTitle().
devparm
boolean devparm
Definition at line 97 of file d_main.c.
Referenced by D_DoomMain(), G_Responder(), and M_Responder().
fastparm
boolean fastparm
Definition at line 100 of file d_main.c.
Referenced by A_Chase(), D_DoomMain(), G_BeginRecording(), G_CheckDemoStatus(), G_DoNewGame(), G_DoPlayDemo(), G_InitNew(), LoadGameSettings(), and SaveGameSettings().
struct { ... } gameversions[]
Initial value:
= {
    {"Doom 1.666",           "1.666",      exe_doom_1_666},
    {"Doom 1.7/1.7a",        "1.7",        exe_doom_1_7},
    {"Doom 1.8",             "1.8",        exe_doom_1_8},
    {"Doom 1.9",             "1.9",        exe_doom_1_9},
    {"Hacx",                 "hacx",       exe_hacx},
    {"Ultimate Doom",        "ultimate",   exe_ultimate},
    {"Final Doom",           "final",      exe_final},
    {"Final Doom (alt)",     "final2",     exe_final2},
    {"Chex Quest",           "chex",       exe_chex},
    { NULL,                  NULL,         0},
}
Referenced by InitGameVersion(), and PrintGameVersion().
inhelpscreens
boolean inhelpscreens extern
Definition at line 117 of file m_menu.c.
Referenced by D_Display(), M_Drawer(), M_DrawReadThis1(), and M_DrawReadThis2().
iwadfile
char* iwadfile
Definition at line 94 of file d_main.c.
Referenced by D_DoomMain(), and D_FindIWAD().
main_loop_started
boolean main_loop_started = false
Definition at line 123 of file d_main.c.
Referenced by D_DoomLoop(), and D_Endoom().
mapdir
char mapdir[1024]
Definition at line 126 of file d_main.c.
nomonsters
boolean nomonsters
Definition at line 98 of file d_main.c.
Referenced by D_DoomMain(), G_BeginRecording(), G_CheckDemoStatus(), G_DoNewGame(), G_DoPlayDemo(), LoadGameSettings(), P_SpawnMapThing(), and SaveGameSettings().
pagename
char* pagename
Definition at line 468 of file d_main.c.
Referenced by D_DoAdvanceDemo(), and D_PageDrawer().
pagetic
int pagetic
Definition at line 467 of file d_main.c.
Referenced by D_DoAdvanceDemo(), and D_PageTicker().
respawnparm
boolean respawnparm
Definition at line 99 of file d_main.c.
Referenced by D_DoomMain(), G_BeginRecording(), G_CheckDemoStatus(), G_DoNewGame(), G_DoPlayDemo(), G_InitNew(), LoadGameSettings(), and SaveGameSettings().
savegamedir
char* savegamedir
Definition at line 90 of file d_main.c.
Referenced by D_DoomMain(), M_GetSaveGameDir(), P_SaveGameFile(), and P_TempSaveGameFile().
setsizeneeded
boolean setsizeneeded extern
Definition at line 648 of file r_main.c.
Referenced by D_Display().
show_endoom
int show_endoom = 1
Definition at line 128 of file d_main.c.
Referenced by D_BindVariables(), and D_Endoom().
showMessages
int showMessages extern
Definition at line 73 of file m_menu.c.
Referenced by D_BindVariables().
startepisode
int startepisode
Definition at line 109 of file d_main.c.
Referenced by D_CheckNetGame(), D_DoomMain(), LoadGameSettings(), and SaveGameSettings().
startloadgame
int startloadgame
Definition at line 112 of file d_main.c.
Referenced by D_DoomMain(), LoadGameSettings(), and SaveGameSettings().
startmap
int startmap
Definition at line 110 of file d_main.c.
Referenced by D_CheckNetGame(), D_DoomMain(), LoadGameSettings(), R_ExecuteSetViewSize(), R_InitLightTables(), and SaveGameSettings().
startskill
skill_t startskill
Definition at line 108 of file d_main.c.
Referenced by D_CheckNetGame(), D_DoomMain(), LoadGameSettings(), and SaveGameSettings().
storedemo
boolean storedemo
Definition at line 117 of file d_main.c.
Referenced by D_DoomMain(), and D_ProcessEvents().
title
char title[128]
Definition at line 866 of file d_main.c.
Referenced by I_SetWindowTitle().
wadfile
char wadfile[1024]
Definition at line 125 of file d_main.c.
wipegamestate
gamestate_t wipegamestate = GS_DEMOSCREEN
Definition at line 164 of file d_main.c.
Referenced by D_Display(), D_DoomLoop(), F_StartCast(), F_Ticker(), and G_DoLoadLevel().