Fennix: Userspace/musl/include/setjmp.h File Reference
setjmp.h File Reference
#include <features.h>
#include <bits/setjmp.h>
Data Structures
struct __jmp_buf_tag
Macros
#define __setjmp_attr
#define setjmp setjmp
Typedefs
typedef struct __jmp_buf_tag jmp_buf[1]
Functions
int setjmp (jmp_buf) __setjmp_attr
_Noreturn void longjmp (jmp_buf, int)
Data Structure Documentation
__jmp_buf_tag
struct __jmp_buf_tag
Definition at line 12 of file setjmp.h.
Data Fields
unsigned long __fl
__jmp_buf __jb
unsigned long __ss[128/sizeof(long)]
Macro Definition Documentation
__setjmp_attr
#define __setjmp_attr
Definition at line 21 of file setjmp.h.
setjmp
#define setjmp setjmp
Definition at line 41 of file setjmp.h.
Typedef Documentation
jmp_buf
typedef struct __jmp_buf_tag jmp_buf[1]
Function Documentation
longjmp()
_Noreturn void longjmp (jmp_buf , int)
Referenced by abort_unzip(), binop(), cleanup_fromsig(), do_relocs(), evalcommand(), evalstring(), evaltree(), exitshell(), expandstr(), extend_bfs_deps(), fdisk_fatal(), get_bits(), load_direct_deps(), makefuncdescs(), prepare_lazy(), queue_ctors(), redirectsafe(), reloc_all(), siglongjmp(), syntax(), and tmtravel().
setjmp()
int setjmp (jmp_buf env)
Definition at line 3 of file setjmp.c.
 {
     return 0;
 }