Fennix: Userspace/musl/src/linux/adjtime.c File Reference
adjtime.c File Reference
#include <sys/time.h>
#include <sys/timex.h>
#include <errno.h>
#include "syscall.h"
Macros
#define _GNU_SOURCE
Functions
int adjtime (const struct timeval *in, struct timeval *out)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 1 of file adjtime.c.
Function Documentation
adjtime()
int adjtime (const struct timeval * in, struct timeval * out)
Definition at line 7 of file adjtime.c.
 {
     struct timex tx = { 0 };
     if (in) {
         if (in->tv_sec > 1000 || in->tv_usec > 1000000000) {
             errno = EINVAL;
             return -1;
         }
         tx.offset = in->tv_sec*1000000 + in->tv_usec;
         tx.modes = ADJ_OFFSET_SINGLESHOT;
     }
     if (adjtimex(&tx) < 0) return -1;
     if (out) {
         out->tv_sec = tx.offset / 1000000;
         if ((out->tv_usec = tx.offset % 1000000) < 0) {
             out->tv_sec--;
             out->tv_usec += 1000000;
         }
     }
     return 0;
 }
References ADJ_OFFSET_SINGLESHOT, adjtimex(), EINVAL, errno, timex::modes, timex::offset, out(), timeval::tv_sec, and timeval::tv_usec.
Referenced by __adjtime32().