Fennix Userspace: Userspace/mlibc/options/elf/include/elf.h File Reference
elf.h File Reference
#include <stdint.h>
#include <bits/inline-definition.h>
#include <abi-bits/auxv.h>
Data Structures
struct Elf32_Ehdr
struct Elf64_Ehdr
struct Elf32_Verdef
struct Elf64_Verdef
struct Elf32_Verdaux
struct Elf64_Verdaux
struct Elf64_Verneed
struct Elf64_Vernaux
struct Elf64_Move
struct Elf64_Lib
struct Elf32_Sym
struct Elf64_Sym
struct Elf64_Syminfo
struct Elf64_Rel
struct Elf64_Rela
struct Elf32_Phdr
struct Elf64_Phdr
struct Elf32_Dyn
struct Elf64_Dyn
struct Elf32_Shdr
struct Elf64_Shdr
struct Elf64_auxv_t
struct Elf32_auxv_t
struct Elf32_Nhdr
struct Elf64_Nhdr
union Elf32_Dyn.d_un
union Elf64_Dyn.d_un
union Elf32_auxv_t.a_un
union Elf64_auxv_t.a_un
Macros
#define ELFCLASS64 2
#define ELFDATA2LSB 1
#define ELFOSABI_SYSV 0
#define EM_X86_64 62
#define SHF_WRITE 1
#define SHF_ALLOC 2
#define SHF_EXECINSTR 4
#define SHF_STRINGS 16
#define SHF_TLS 512
#define EI_NIDENT (16)
#define NT_PRSTATUS 1
#define NT_FPREGSET 2
#define NT_PRPSINFO 3
#define NT_GNU_BUILD_ID 3
#define STT_NOTYPE 0
#define STT_OBJECT 1
#define STT_FUNC 2
#define STT_SECTION 3
#define STT_FILE 4
#define STB_LOCAL 0
#define STB_GLOBAL 1
#define STB_WEAK 2
#define SHT_NULL 0
#define SHT_PROGBITS 1
#define SHT_SYMTAB 2
#define SHT_STRTAB 3
#define SHT_RELA 4
#define SHT_HASH 5
#define SHT_DYNAMIC 6
#define SHT_NOTE 7
#define SHT_NOBITS 8
#define SHT_REL 9
#define SHT_DYNSYM 11
#define SHT_INIT_ARRAY 14
#define SHT_FINI_ARRAY 15
#define SHT_SYMTAB_SHNDX 18
#define SHN_UNDEF 0
#define SHN_LORESERVE 0xff00
#define SHN_COMMON 0xfff2
#define SHN_XINDEX 0xffff
#define SHN_HIRESERVE 0xff00
#define EM_NONE 0
#define EM_SPARC 2
#define EM_386 3
#define EM_MIPS 8
#define EM_PPC 20
#define EM_PPC64 21
#define EM_S390 22
#define EM_ARM 40
#define EM_SH 42
#define EM_SPARCV9 43
#define EM_IA_64 50
#define EM_X86_64 62
#define EM_BLACKFIN 106
#define EM_AARCH64 183
#define EV_NONE 0
#define EV_CURRENT 1
#define EV_NUM 2
#define EI_MAG0 0
#define ELFMAG0 0x7f
#define EI_MAG1 1
#define ELFMAG1 'E'
#define EI_MAG2 2
#define ELFMAG2 'L'
#define EI_MAG3 3
#define ELFMAG3 'F'
#define ELFMAG "\177ELF"
#define SELFMAG 4
#define EI_CLASS 4
#define ELFCLASSNONE 0
#define ELFCLASS32 1
#define ELFCLASS64 2
#define ELFCLASSNUM 3
#define EI_DATA 5
#define ELFDATANONE 0
#define ELFDATA2LSB 1
#define ELFDATA2MSB 2
#define ELFDATANUM 3
#define EI_VERSION 6
#define EI_OSABI 7
#define ELFOSABI_HPUX 1
#define ELFOSABI_NETBSD 2
#define ELFOSABI_GNU 3
#define ELFOSABI_LINUX ELFOSABI_GNU
#define ELFOSABI_SOLARIS 6
#define ELFOSABI_AIX 7
#define ELFOSABI_IRIX 8
#define ELFOSABI_FREEBSD 9
#define ELFOSABI_OPENBSD 12
#define EI_ABIVERSION 8
#define ELF_NOTE_GNU "GNU"
#define AT_NULL 0
#define AT_IGNORE 1
#define AT_EXECFD 2
#define AT_PHDR 3
#define AT_PHENT 4
#define AT_PHNUM 5
#define AT_PAGESZ 6
#define AT_BASE 7
#define AT_FLAGS 8
#define AT_ENTRY 9
#define AT_NOTELF 10
#define AT_UID 11
#define AT_EUID 12
#define AT_GID 13
#define AT_EGID 14
Typedefs
typedef uint64_t Elf64_Addr
typedef uint64_t Elf64_Off
typedef uint16_t Elf64_Half
typedef uint32_t Elf64_Word
typedef int32_t Elf64_Sword
typedef uint64_t Elf64_Xword
typedef int64_t Elf64_Sxword
typedef uint16_t Elf64_Section
typedef Elf64_Half Elf64_Versym
typedef uint32_t Elf32_Addr
typedef uint32_t Elf32_Off
typedef uint16_t Elf32_Half
typedef uint32_t Elf32_Word
typedef int32_t Elf32_Sword
typedef uint64_t Elf32_Xword
typedef int64_t Elf32_Sxword
typedef uint16_t Elf32_Section
typedef Elf32_Half Elf32_Versym
Enumerations
enum {
ET_NONE = 0 , ET_REL = 1 , ET_EXEC = 2 , ET_DYN = 3 ,
ET_CORE = 4
}
enum { SHN_UNDEF = 0 , SHN_ABS = 0xFFF1 }
enum { STN_UNDEF = 0 }
enum {
STB_GLOBAL = 1 , STB_WEAK = 2 , STB_GNU_UNIQUE = 10 , STB_LOPROC = 13 ,
STB_HIPROC = 15
}
enum {
STT_OBJECT = 1 , STT_FUNC = 2 , STT_TLS = 6 , STT_LOPROC = 13 ,
STT_HIPROC = 15
}
enum {
R_X86_64_NONE = 0 , R_X86_64_64 = 1 , R_X86_64_COPY = 5 , R_X86_64_GLOB_DAT = 6 ,
R_X86_64_JUMP_SLOT = 7 , R_X86_64_RELATIVE = 8 , R_X86_64_DTPMOD64 = 16 , R_X86_64_DTPOFF64 = 17 ,
R_X86_64_TPOFF64 = 18
}
enum {
R_AARCH64_ABS64 = 257 , R_AARCH64_COPY = 1024 , R_AARCH64_GLOB_DAT = 1025 , R_AARCH64_JUMP_SLOT = 1026 ,
R_AARCH64_RELATIVE = 1027 , R_AARCH64_TLS_TPREL = 1030 , R_AARCH64_TLSDESC = 1031
}
enum {
R_RISCV_NONE = 0 , R_RISCV_32 = 1 , R_RISCV_64 = 2 , R_RISCV_RELATIVE = 3 ,
R_RISCV_COPY = 4 , R_RISCV_JUMP_SLOT = 5 , R_RISCV_TLS_DTPMOD32 = 6 , R_RISCV_TLS_DTPMOD64 = 7 ,
R_RISCV_TLS_DTPREL32 = 8 , R_RISCV_TLS_DTPREL64 = 9 , R_RISCV_TLS_TPREL32 = 10 , R_RISCV_TLS_TPREL64 = 11 ,
R_RISCV_IRELATIVE = 58
}
enum {
PT_NULL = 0 , PT_LOAD = 1 , PT_DYNAMIC = 2 , PT_INTERP = 3 ,
PT_NOTE = 4 , PT_PHDR = 6 , PT_TLS = 7 , PT_GNU_EH_FRAME = 0x6474E550 ,
PT_GNU_STACK = 0x6474E551 , PT_GNU_RELRO = 0x6474E552 , PT_GNU_PROPERTY = 0x6474E553 , PT_RISCV_ATTRIBUTES = 0x70000003
}
enum { PF_X = 1 , PF_W = 2 , PF_R = 4 }
enum {
DT_NULL = 0 , DT_NEEDED = 1 , DT_PLTRELSZ = 2 , DT_PLTGOT = 3 ,
DT_HASH = 4 , DT_STRTAB = 5 , DT_SYMTAB = 6 , DT_RELA = 7 ,
DT_RELASZ = 8 , DT_RELAENT = 9 , DT_STRSZ = 10 , DT_SYMENT = 11 ,
DT_INIT = 12 , DT_FINI = 13 , DT_SONAME = 14 , DT_RPATH = 15 ,
DT_SYMBOLIC = 16 , DT_REL = 17 , DT_TEXTREL = 22 , DT_BIND_NOW = 24 ,
DT_INIT_ARRAY = 25 , DT_FINI_ARRAY = 26 , DT_INIT_ARRAYSZ = 27 , DT_FINI_ARRAYSZ = 28 ,
DT_RUNPATH = 29 , DT_PLTREL = 20 , DT_DEBUG = 21 , DT_JMPREL = 23 ,
DT_FLAGS = 30 , DT_PREINIT_ARRAY = 32 , DT_PREINIT_ARRAYSZ = 33 , DT_GNU_HASH = 0x6ffffef5 ,
DT_TLSDESC_PLT = 0x6ffffef6 , DT_TLSDESC_GOT = 0x6ffffef7 , DT_VERSYM = 0x6ffffff0 , DT_RELACOUNT = 0x6ffffff9 ,
DT_FLAGS_1 = 0x6ffffffb , DT_VERDEF = 0x6ffffffc , DT_VERDEFNUM = 0x6ffffffd , DT_VERNEED = 0x6ffffffe ,
DT_VERNEEDNUM = 0x6fffffff
}
enum {
DF_SYMBOLIC = 0x02 , DF_TEXTREL = 0x04 , DF_BIND_NOW = 0x08 , DF_STATIC_TLS = 0x10 ,
DF_1_NOW = 0x00000001 , DF_1_NODELETE = 0x00000008 , DF_1_PIE = 0x08000000
}
Functions
__MLIBC_INLINE_DEFINITION unsigned char ELF64_ST_BIND (unsigned char info)
__MLIBC_INLINE_DEFINITION unsigned char ELF64_ST_TYPE (unsigned char info)
__MLIBC_INLINE_DEFINITION unsigned char ELF64_ST_INFO (unsigned char bind, unsigned char type)
__MLIBC_INLINE_DEFINITION unsigned char ELF32_ST_BIND (unsigned char info)
__MLIBC_INLINE_DEFINITION unsigned char ELF32_ST_TYPE (unsigned char info)
__MLIBC_INLINE_DEFINITION unsigned char ELF32_ST_INFO (unsigned char bind, unsigned char type)
__MLIBC_INLINE_DEFINITION Elf64_Xword ELF64_R_SYM (Elf64_Xword info)
__MLIBC_INLINE_DEFINITION Elf64_Xword ELF64_R_TYPE (Elf64_Xword info)
Data Structure Documentation
Elf32_Ehdr
struct Elf32_Ehdr
Definition at line 47 of file elf.h.
Data Fields
Elf32_Half e_ehsize
Elf32_Addr e_entry
Elf32_Word e_flags
unsigned char e_ident[EI_NIDENT]
Elf32_Half e_machine
Elf32_Half e_phentsize
Elf32_Half e_phnum
Elf32_Off e_phoff
Elf32_Half e_shentsize
Elf32_Half e_shnum
Elf32_Off e_shoff
Elf32_Half e_shstrndx
Elf32_Half e_type
Elf32_Word e_version
Elf64_Ehdr
struct Elf64_Ehdr
Definition at line 64 of file elf.h.
Data Fields
Elf64_Half e_ehsize
Elf64_Addr e_entry
Elf64_Word e_flags
unsigned char e_ident[EI_NIDENT]
Elf64_Half e_machine
Elf64_Half e_phentsize
Elf64_Half e_phnum
Elf64_Off e_phoff
Elf64_Half e_shentsize
Elf64_Half e_shnum
Elf64_Off e_shoff
Elf64_Half e_shstrndx
Elf64_Half e_type
Elf64_Word e_version
Elf32_Verdef
struct Elf32_Verdef
Definition at line 81 of file elf.h.
Data Fields
Elf32_Word vd_aux
Elf32_Half vd_cnt
Elf32_Half vd_flags
Elf32_Word vd_hash
Elf32_Half vd_ndx
Elf32_Word vd_next
Elf32_Half vd_version
Elf64_Verdef
struct Elf64_Verdef
Definition at line 91 of file elf.h.
Data Fields
Elf64_Word vd_aux
Elf64_Half vd_cnt
Elf64_Half vd_flags
Elf64_Word vd_hash
Elf64_Half vd_ndx
Elf64_Word vd_next
Elf64_Half vd_version
Elf32_Verdaux
struct Elf32_Verdaux
Definition at line 101 of file elf.h.
Data Fields
Elf32_Word vda_name
Elf32_Word vda_next
Elf64_Verdaux
struct Elf64_Verdaux
Definition at line 106 of file elf.h.
Data Fields
Elf64_Word vda_name
Elf64_Word vda_next
Elf64_Verneed
struct Elf64_Verneed
Definition at line 111 of file elf.h.
Data Fields
Elf64_Word vn_aux
Elf64_Half vn_cnt
Elf64_Word vn_file
Elf64_Word vn_next
Elf64_Half vn_version
Elf64_Vernaux
struct Elf64_Vernaux
Definition at line 119 of file elf.h.
Data Fields
Elf64_Half vna_flags
Elf64_Word vna_hash
Elf64_Word vna_name
Elf64_Word vna_next
Elf64_Half vna_other
Elf64_Move
struct Elf64_Move
Definition at line 127 of file elf.h.
Data Fields
Elf64_Xword m_info
Elf64_Xword m_poffset
Elf64_Half m_repeat
Elf64_Half m_stride
Elf64_Xword m_value
Elf64_Lib
struct Elf64_Lib
Definition at line 135 of file elf.h.
Data Fields
Elf64_Word l_checksum
Elf64_Word l_flags
Elf64_Word l_name
Elf64_Word l_time_stamp
Elf64_Word l_version
Elf32_Sym
struct Elf32_Sym
Definition at line 160 of file elf.h.
Data Fields
unsigned char st_info
Elf32_Word st_name
unsigned char st_other
Elf32_Section st_shndx
Elf32_Word st_size
Elf32_Addr st_value
Elf64_Sym
struct Elf64_Sym
Definition at line 169 of file elf.h.
Data Fields
unsigned char st_info
Elf64_Word st_name
unsigned char st_other
Elf64_Half st_shndx
Elf64_Xword st_size
Elf64_Addr st_value
Elf64_Syminfo
struct Elf64_Syminfo
Definition at line 188 of file elf.h.
Data Fields
Elf64_Half si_boundto
Elf64_Half si_flags
Elf64_Rel
struct Elf64_Rel
Definition at line 257 of file elf.h.
Data Fields
uint64_t r_info
Elf64_Addr r_offset
Elf64_Rela
struct Elf64_Rela
Definition at line 279 of file elf.h.
Data Fields
Elf64_Sxword r_addend
Elf64_Xword r_info
Elf64_Addr r_offset
Elf32_Phdr
struct Elf32_Phdr
Definition at line 296 of file elf.h.
Data Fields
Elf32_Word p_align
Elf32_Word p_filesz
Elf32_Word p_flags
Elf32_Word p_memsz
Elf32_Off p_offset
Elf32_Addr p_paddr
Elf32_Word p_type
Elf32_Addr p_vaddr
Elf64_Phdr
struct Elf64_Phdr
Definition at line 267 of file elf.h.
Data Fields
Elf64_Xword p_align
Elf64_Xword p_filesz
Elf64_Word p_flags
Elf64_Xword p_memsz
Elf64_Off p_offset
Elf64_Addr p_paddr
Elf64_Word p_type
Elf64_Addr p_vaddr
Elf32_Dyn
struct Elf32_Dyn
Definition at line 247 of file elf.h.
Data Fields
Elf32_Sword d_tag
union Elf32_Dyn d_un
union Elf32_Dyn d_un
Elf64_Dyn
struct Elf64_Dyn
Definition at line 257 of file elf.h.
Data Fields
Elf64_Sxword d_tag
union Elf64_Dyn d_un
union Elf64_Dyn d_un
Elf32_Shdr
struct Elf32_Shdr
Definition at line 399 of file elf.h.
Data Fields
Elf32_Addr sh_addr
Elf32_Word sh_addralign
Elf32_Word sh_entsize
Elf32_Word sh_flags
Elf32_Word sh_info
Elf32_Word sh_link
Elf32_Word sh_name
Elf32_Off sh_offset
Elf32_Word sh_size
Elf32_Word sh_type
Elf64_Shdr
struct Elf64_Shdr
Definition at line 412 of file elf.h.
Data Fields
Elf64_Addr sh_addr
Elf64_Xword sh_addralign
Elf64_Xword sh_entsize
Elf64_Xword sh_flags
Elf64_Word sh_info
Elf64_Word sh_link
Elf64_Word sh_name
Elf64_Off sh_offset
Elf64_Xword sh_size
Elf64_Word sh_type
Elf64_auxv_t
struct Elf64_auxv_t
Definition at line 54 of file aux.h.
Data Fields
uint64_t a_type
union Elf64_auxv_t a_un
union Elf64_auxv_t a_un
Elf32_auxv_t
struct Elf32_auxv_t
Definition at line 45 of file aux.h.
Data Fields
uint32_t a_type
union Elf32_auxv_t a_un
union Elf32_auxv_t a_un
Elf32_Nhdr
struct Elf32_Nhdr
Definition at line 439 of file elf.h.
Data Fields
Elf32_Word n_descsz
Elf32_Word n_namesz
Elf32_Word n_type
Elf64_Nhdr
struct Elf64_Nhdr
Definition at line 445 of file elf.h.
Data Fields
Elf64_Word n_descsz
Elf64_Word n_namesz
Elf64_Word n_type
Elf32_Dyn.d_un
union Elf32_Dyn.d_un
Definition at line 385 of file elf.h.
Data Fields
Elf32_Addr d_ptr
Elf32_Addr d_ptr
Elf32_Word d_val
Elf32_Word d_val
Elf64_Dyn.d_un
union Elf64_Dyn.d_un
Definition at line 393 of file elf.h.
Data Fields
Elf64_Addr d_ptr
Elf64_Addr d_ptr
Elf64_Xword d_val
Elf64_Xword d_val
Elf32_auxv_t.a_un
union Elf32_auxv_t.a_un
Definition at line 434 of file elf.h.
Data Fields
uint32_t a_val
uint32_t a_val
Elf64_auxv_t.a_un
union Elf64_auxv_t.a_un
Definition at line 427 of file elf.h.
Data Fields
uint64_t a_val
uint64_t a_val
Macro Definition Documentation
AT_BASE
#define AT_BASE 7
Definition at line 563 of file elf.h.
AT_EGID
#define AT_EGID 14
Definition at line 570 of file elf.h.
AT_ENTRY
#define AT_ENTRY 9
Definition at line 565 of file elf.h.
AT_EUID
#define AT_EUID 12
Definition at line 568 of file elf.h.
AT_EXECFD
#define AT_EXECFD 2
Definition at line 558 of file elf.h.
AT_FLAGS
#define AT_FLAGS 8
Definition at line 564 of file elf.h.
AT_GID
#define AT_GID 13
Definition at line 569 of file elf.h.
AT_IGNORE
#define AT_IGNORE 1
Definition at line 557 of file elf.h.
AT_NOTELF
#define AT_NOTELF 10
Definition at line 566 of file elf.h.
AT_NULL
#define AT_NULL 0
Definition at line 556 of file elf.h.
AT_PAGESZ
#define AT_PAGESZ 6
Definition at line 562 of file elf.h.
AT_PHDR
#define AT_PHDR 3
Definition at line 559 of file elf.h.
AT_PHENT
#define AT_PHENT 4
Definition at line 560 of file elf.h.
AT_PHNUM
#define AT_PHNUM 5
Definition at line 561 of file elf.h.
AT_UID
#define AT_UID 11
Definition at line 567 of file elf.h.
EI_ABIVERSION
#define EI_ABIVERSION 8
Definition at line 548 of file elf.h.
EI_CLASS
#define EI_CLASS 4
Definition at line 523 of file elf.h.
EI_DATA
#define EI_DATA 5
Definition at line 529 of file elf.h.
EI_MAG0
#define EI_MAG0 0
Definition at line 508 of file elf.h.
EI_MAG1
#define EI_MAG1 1
Definition at line 511 of file elf.h.
EI_MAG2
#define EI_MAG2 2
Definition at line 514 of file elf.h.
EI_MAG3
#define EI_MAG3 3
Definition at line 517 of file elf.h.
EI_NIDENT
#define EI_NIDENT (16)
Definition at line 45 of file elf.h.
EI_OSABI
#define EI_OSABI 7
Definition at line 537 of file elf.h.
EI_VERSION
#define EI_VERSION 6
Definition at line 535 of file elf.h.
ELF_NOTE_GNU
#define ELF_NOTE_GNU "GNU"
Definition at line 550 of file elf.h.
ELFCLASS32
#define ELFCLASS32 1
Definition at line 525 of file elf.h.
ELFCLASS64 [1/2]
#define ELFCLASS64 2
Definition at line 526 of file elf.h.
ELFCLASS64 [2/2]
#define ELFCLASS64 2
Definition at line 526 of file elf.h.
ELFCLASSNONE
#define ELFCLASSNONE 0
Definition at line 524 of file elf.h.
ELFCLASSNUM
#define ELFCLASSNUM 3
Definition at line 527 of file elf.h.
ELFDATA2LSB [1/2]
#define ELFDATA2LSB 1
Definition at line 531 of file elf.h.
ELFDATA2LSB [2/2]
#define ELFDATA2LSB 1
Definition at line 531 of file elf.h.
ELFDATA2MSB
#define ELFDATA2MSB 2
Definition at line 532 of file elf.h.
ELFDATANONE
#define ELFDATANONE 0
Definition at line 530 of file elf.h.
ELFDATANUM
#define ELFDATANUM 3
Definition at line 533 of file elf.h.
ELFMAG
#define ELFMAG "\177ELF"
Definition at line 520 of file elf.h.
ELFMAG0
#define ELFMAG0 0x7f
Definition at line 509 of file elf.h.
ELFMAG1
#define ELFMAG1 'E'
Definition at line 512 of file elf.h.
ELFMAG2
#define ELFMAG2 'L'
Definition at line 515 of file elf.h.
ELFMAG3
#define ELFMAG3 'F'
Definition at line 518 of file elf.h.
ELFOSABI_AIX
#define ELFOSABI_AIX 7
Definition at line 543 of file elf.h.
ELFOSABI_FREEBSD
#define ELFOSABI_FREEBSD 9
Definition at line 545 of file elf.h.
ELFOSABI_GNU
#define ELFOSABI_GNU 3
Definition at line 540 of file elf.h.
ELFOSABI_HPUX
#define ELFOSABI_HPUX 1
Definition at line 538 of file elf.h.
ELFOSABI_IRIX
#define ELFOSABI_IRIX 8
Definition at line 544 of file elf.h.
ELFOSABI_LINUX
#define ELFOSABI_LINUX ELFOSABI_GNU
Definition at line 541 of file elf.h.
ELFOSABI_NETBSD
#define ELFOSABI_NETBSD 2
Definition at line 539 of file elf.h.
ELFOSABI_OPENBSD
#define ELFOSABI_OPENBSD 12
Definition at line 546 of file elf.h.
ELFOSABI_SOLARIS
#define ELFOSABI_SOLARIS 6
Definition at line 542 of file elf.h.
ELFOSABI_SYSV
#define ELFOSABI_SYSV 0
Definition at line 16 of file elf.h.
EM_386
#define EM_386 3
Definition at line 489 of file elf.h.
EM_AARCH64
#define EM_AARCH64 183
Definition at line 500 of file elf.h.
EM_ARM
#define EM_ARM 40
Definition at line 494 of file elf.h.
EM_BLACKFIN
#define EM_BLACKFIN 106
Definition at line 499 of file elf.h.
EM_IA_64
#define EM_IA_64 50
Definition at line 497 of file elf.h.
EM_MIPS
#define EM_MIPS 8
Definition at line 490 of file elf.h.
EM_NONE
#define EM_NONE 0
Definition at line 487 of file elf.h.
EM_PPC
#define EM_PPC 20
Definition at line 491 of file elf.h.
EM_PPC64
#define EM_PPC64 21
Definition at line 492 of file elf.h.
EM_S390
#define EM_S390 22
Definition at line 493 of file elf.h.
EM_SH
#define EM_SH 42
Definition at line 495 of file elf.h.
EM_SPARC
#define EM_SPARC 2
Definition at line 488 of file elf.h.
EM_SPARCV9
#define EM_SPARCV9 43
Definition at line 496 of file elf.h.
EM_X86_64 [1/2]
#define EM_X86_64 62
Definition at line 498 of file elf.h.
EM_X86_64 [2/2]
#define EM_X86_64 62
Definition at line 498 of file elf.h.
EV_CURRENT
#define EV_CURRENT 1
Definition at line 504 of file elf.h.
EV_NONE
#define EV_NONE 0
Definition at line 503 of file elf.h.
EV_NUM
#define EV_NUM 2
Definition at line 505 of file elf.h.
NT_FPREGSET
#define NT_FPREGSET 2
Definition at line 377 of file elf.h.
NT_GNU_BUILD_ID
#define NT_GNU_BUILD_ID 3
Definition at line 381 of file elf.h.
NT_PRPSINFO
#define NT_PRPSINFO 3
Definition at line 378 of file elf.h.
NT_PRSTATUS
#define NT_PRSTATUS 1
Definition at line 376 of file elf.h.
SELFMAG
#define SELFMAG 4
Definition at line 521 of file elf.h.
SHF_ALLOC
#define SHF_ALLOC 2
Definition at line 20 of file elf.h.
SHF_EXECINSTR
#define SHF_EXECINSTR 4
Definition at line 21 of file elf.h.
SHF_STRINGS
#define SHF_STRINGS 16
Definition at line 22 of file elf.h.
SHF_TLS
#define SHF_TLS 512
Definition at line 23 of file elf.h.
SHF_WRITE
#define SHF_WRITE 1
Definition at line 19 of file elf.h.
SHN_COMMON
#define SHN_COMMON 0xfff2
Definition at line 482 of file elf.h.
SHN_HIRESERVE
#define SHN_HIRESERVE 0xff00
Definition at line 484 of file elf.h.
SHN_LORESERVE
#define SHN_LORESERVE 0xff00
Definition at line 481 of file elf.h.
SHN_UNDEF
#define SHN_UNDEF 0
Definition at line 480 of file elf.h.
SHN_XINDEX
#define SHN_XINDEX 0xffff
Definition at line 483 of file elf.h.
SHT_DYNAMIC
#define SHT_DYNAMIC 6
Definition at line 470 of file elf.h.
SHT_DYNSYM
#define SHT_DYNSYM 11
Definition at line 474 of file elf.h.
SHT_FINI_ARRAY
#define SHT_FINI_ARRAY 15
Definition at line 476 of file elf.h.
SHT_HASH
#define SHT_HASH 5
Definition at line 469 of file elf.h.
SHT_INIT_ARRAY
#define SHT_INIT_ARRAY 14
Definition at line 475 of file elf.h.
SHT_NOBITS
#define SHT_NOBITS 8
Definition at line 472 of file elf.h.
SHT_NOTE
#define SHT_NOTE 7
Definition at line 471 of file elf.h.
SHT_NULL
#define SHT_NULL 0
Definition at line 464 of file elf.h.
SHT_PROGBITS
#define SHT_PROGBITS 1
Definition at line 465 of file elf.h.
SHT_REL
#define SHT_REL 9
Definition at line 473 of file elf.h.
SHT_RELA
#define SHT_RELA 4
Definition at line 468 of file elf.h.
SHT_STRTAB
#define SHT_STRTAB 3
Definition at line 467 of file elf.h.
SHT_SYMTAB
#define SHT_SYMTAB 2
Definition at line 466 of file elf.h.
SHT_SYMTAB_SHNDX
#define SHT_SYMTAB_SHNDX 18
Definition at line 477 of file elf.h.
STB_GLOBAL
#define STB_GLOBAL 1
Definition at line 460 of file elf.h.
STB_LOCAL
#define STB_LOCAL 0
Definition at line 459 of file elf.h.
STB_WEAK
#define STB_WEAK 2
Definition at line 461 of file elf.h.
STT_FILE
#define STT_FILE 4
Definition at line 456 of file elf.h.
STT_FUNC
#define STT_FUNC 2
Definition at line 454 of file elf.h.
STT_NOTYPE
#define STT_NOTYPE 0
Definition at line 452 of file elf.h.
STT_OBJECT
#define STT_OBJECT 1
Definition at line 453 of file elf.h.
STT_SECTION
#define STT_SECTION 3
Definition at line 455 of file elf.h.
Typedef Documentation
Elf32_Addr
typedef uint32_t Elf32_Addr
Definition at line 35 of file elf.h.
Elf32_Half
typedef uint16_t Elf32_Half
Definition at line 37 of file elf.h.
Elf32_Off
typedef uint32_t Elf32_Off
Definition at line 36 of file elf.h.
Elf32_Section
typedef uint16_t Elf32_Section
Definition at line 42 of file elf.h.
Elf32_Sword
typedef int32_t Elf32_Sword
Definition at line 39 of file elf.h.
Elf32_Sxword
typedef int64_t Elf32_Sxword
Definition at line 41 of file elf.h.
Elf32_Versym
typedef Elf32_Half Elf32_Versym
Definition at line 43 of file elf.h.
Elf32_Word
typedef uint32_t Elf32_Word
Definition at line 38 of file elf.h.
Elf32_Xword
typedef uint64_t Elf32_Xword
Definition at line 40 of file elf.h.
Elf64_Addr
typedef uint64_t Elf64_Addr
Definition at line 25 of file elf.h.
Elf64_Half
typedef uint16_t Elf64_Half
Definition at line 27 of file elf.h.
Elf64_Off
typedef uint64_t Elf64_Off
Definition at line 26 of file elf.h.
Elf64_Section
typedef uint16_t Elf64_Section
Definition at line 32 of file elf.h.
Elf64_Sword
typedef int32_t Elf64_Sword
Definition at line 29 of file elf.h.
Elf64_Sxword
typedef int64_t Elf64_Sxword
Definition at line 31 of file elf.h.
Elf64_Versym
typedef Elf64_Half Elf64_Versym
Definition at line 33 of file elf.h.
Elf64_Word
typedef uint32_t Elf64_Word
Definition at line 28 of file elf.h.
Elf64_Xword
typedef uint64_t Elf64_Xword
Definition at line 30 of file elf.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ET_NONE
ET_REL
ET_EXEC
ET_DYN
ET_CORE
Definition at line 143 of file elf.h.
      {
     ET_NONE = 0,
     ET_REL = 1,
     ET_EXEC = 2,
     ET_DYN = 3,
     ET_CORE = 4,
 };
anonymous enum
anonymous enum
Enumerator
SHN_UNDEF
SHN_ABS
Definition at line 151 of file elf.h.
      {
     SHN_UNDEF = 0,
     SHN_ABS = 0xFFF1
 };
anonymous enum
anonymous enum
Enumerator
STN_UNDEF
Definition at line 156 of file elf.h.
      {
     STN_UNDEF = 0,
 };
anonymous enum
anonymous enum
Enumerator
STB_GLOBAL
STB_WEAK
STB_GNU_UNIQUE
STB_LOPROC
STB_HIPROC
Definition at line 203 of file elf.h.
      {
     STB_GLOBAL = 1,
     STB_WEAK = 2,
     STB_GNU_UNIQUE = 10,
     STB_LOPROC = 13,
     STB_HIPROC = 15
 };
anonymous enum
anonymous enum
Enumerator
STT_OBJECT
STT_FUNC
STT_TLS
STT_LOPROC
STT_HIPROC
Definition at line 211 of file elf.h.
      {
     STT_OBJECT = 1,
     STT_FUNC = 2,
     STT_TLS = 6,
     STT_LOPROC = 13,
     STT_HIPROC = 15
 };
anonymous enum
anonymous enum
Enumerator
R_X86_64_NONE
R_X86_64_64
R_X86_64_COPY
R_X86_64_GLOB_DAT
R_X86_64_JUMP_SLOT
R_X86_64_RELATIVE
R_X86_64_DTPMOD64
R_X86_64_DTPOFF64
R_X86_64_TPOFF64
Definition at line 219 of file elf.h.
      {
     R_X86_64_NONE = 0,
     R_X86_64_64 = 1,
     R_X86_64_COPY = 5,
     R_X86_64_GLOB_DAT = 6,
     R_X86_64_JUMP_SLOT = 7,
     R_X86_64_RELATIVE = 8,
     R_X86_64_DTPMOD64 = 16,
     R_X86_64_DTPOFF64 = 17,
     R_X86_64_TPOFF64 = 18,
 };
anonymous enum
anonymous enum
Enumerator
R_AARCH64_ABS64
R_AARCH64_COPY
R_AARCH64_GLOB_DAT
R_AARCH64_JUMP_SLOT
R_AARCH64_RELATIVE
R_AARCH64_TLS_TPREL
R_AARCH64_TLSDESC
Definition at line 231 of file elf.h.
      {
     R_AARCH64_ABS64 = 257,
     R_AARCH64_COPY = 1024,
     R_AARCH64_GLOB_DAT = 1025,
     R_AARCH64_JUMP_SLOT = 1026,
     R_AARCH64_RELATIVE = 1027,
     R_AARCH64_TLS_TPREL = 1030,
     R_AARCH64_TLSDESC = 1031
 };
anonymous enum
anonymous enum
Enumerator
R_RISCV_NONE
R_RISCV_32
R_RISCV_64
R_RISCV_RELATIVE
R_RISCV_COPY
R_RISCV_JUMP_SLOT
R_RISCV_TLS_DTPMOD32
R_RISCV_TLS_DTPMOD64
R_RISCV_TLS_DTPREL32
R_RISCV_TLS_DTPREL64
R_RISCV_TLS_TPREL32
R_RISCV_TLS_TPREL64
R_RISCV_IRELATIVE
Definition at line 241 of file elf.h.
      {
     R_RISCV_NONE = 0,
     R_RISCV_32 = 1,
     R_RISCV_64 = 2,
     R_RISCV_RELATIVE = 3,
     R_RISCV_COPY = 4,
     R_RISCV_JUMP_SLOT = 5,
     R_RISCV_TLS_DTPMOD32 = 6,
     R_RISCV_TLS_DTPMOD64 = 7,
     R_RISCV_TLS_DTPREL32 = 8,
     R_RISCV_TLS_DTPREL64 = 9,
     R_RISCV_TLS_TPREL32 = 10,
     R_RISCV_TLS_TPREL64 = 11,
     R_RISCV_IRELATIVE = 58
 };
anonymous enum
anonymous enum
Enumerator
PT_NULL
PT_LOAD
PT_DYNAMIC
PT_INTERP
PT_NOTE
PT_PHDR
PT_TLS
PT_GNU_EH_FRAME
PT_GNU_STACK
PT_GNU_RELRO
PT_GNU_PROPERTY
PT_RISCV_ATTRIBUTES
Definition at line 275 of file elf.h.
      {
     PT_NULL = 0,
     PT_LOAD = 1,
     PT_DYNAMIC = 2,
     PT_INTERP = 3,
     PT_NOTE = 4,
     PT_PHDR = 6,
     PT_TLS = 7,
     PT_GNU_EH_FRAME = 0x6474E550,
     PT_GNU_STACK = 0x6474E551,
     PT_GNU_RELRO = 0x6474E552,
     PT_GNU_PROPERTY = 0x6474E553,
     PT_RISCV_ATTRIBUTES = 0x70000003,
 };
anonymous enum
anonymous enum
Enumerator
PF_X
PF_W
PF_R
Definition at line 290 of file elf.h.
      {
     PF_X = 1,
     PF_W = 2,
     PF_R = 4
 };
anonymous enum
anonymous enum
Enumerator
DT_NULL
DT_NEEDED
DT_PLTRELSZ
DT_PLTGOT
DT_HASH
DT_STRTAB
DT_SYMTAB
DT_RELA
DT_RELASZ
DT_RELAENT
DT_STRSZ
DT_SYMENT
DT_INIT
DT_FINI
DT_SONAME
DT_RPATH
DT_SYMBOLIC
DT_REL
DT_TEXTREL
DT_BIND_NOW
DT_INIT_ARRAY
DT_FINI_ARRAY
DT_INIT_ARRAYSZ
DT_FINI_ARRAYSZ
DT_RUNPATH
DT_PLTREL
DT_DEBUG
DT_JMPREL
DT_FLAGS
DT_PREINIT_ARRAY
DT_PREINIT_ARRAYSZ
DT_GNU_HASH
DT_TLSDESC_PLT
DT_TLSDESC_GOT
DT_VERSYM
DT_RELACOUNT
DT_FLAGS_1
DT_VERDEF
DT_VERDEFNUM
DT_VERNEED
DT_VERNEEDNUM
Definition at line 318 of file elf.h.
      {
     DT_NULL = 0,
     DT_NEEDED = 1,
     DT_PLTRELSZ = 2,
     DT_PLTGOT = 3,
     DT_HASH = 4,
     DT_STRTAB = 5,
     DT_SYMTAB = 6,
     DT_RELA = 7,
     DT_RELASZ = 8,
     DT_RELAENT = 9,
     DT_STRSZ = 10,
     DT_SYMENT = 11,
     DT_INIT = 12,
     DT_FINI = 13,
     DT_SONAME = 14,
     DT_RPATH = 15,
     DT_SYMBOLIC = 16,
     DT_REL = 17,
     DT_TEXTREL = 22,
     DT_BIND_NOW = 24,
     DT_INIT_ARRAY = 25,
     DT_FINI_ARRAY = 26,
     DT_INIT_ARRAYSZ = 27,
     DT_FINI_ARRAYSZ = 28,
     DT_RUNPATH = 29,
     DT_PLTREL = 20,
     DT_DEBUG = 21,
     DT_JMPREL = 23,
     DT_FLAGS = 30,
     DT_PREINIT_ARRAY = 32,
     DT_PREINIT_ARRAYSZ = 33,
     DT_GNU_HASH = 0x6ffffef5,
     DT_TLSDESC_PLT = 0x6ffffef6,
     DT_TLSDESC_GOT = 0x6ffffef7,
     DT_VERSYM = 0x6ffffff0,
     DT_RELACOUNT = 0x6ffffff9,
     DT_FLAGS_1 = 0x6ffffffb,
     DT_VERDEF = 0x6ffffffc,
     DT_VERDEFNUM = 0x6ffffffd,
     DT_VERNEED = 0x6ffffffe,
     DT_VERNEEDNUM = 0x6fffffff
 };
anonymous enum
anonymous enum
Enumerator
DF_SYMBOLIC
DF_TEXTREL
DF_BIND_NOW
DF_STATIC_TLS
DF_1_NOW
DF_1_NODELETE
DF_1_PIE
Definition at line 362 of file elf.h.
      {
     // For DT_FLAGS.
     DF_SYMBOLIC = 0x02,
     DF_TEXTREL = 0x04,
     DF_BIND_NOW = 0x08,
     DF_STATIC_TLS = 0x10,
     // For DT_FLAGS_1.
     DF_1_NOW = 0x00000001,
     DF_1_NODELETE = 0x00000008,
     DF_1_PIE = 0x08000000
 };
Function Documentation
ELF32_ST_BIND()
__MLIBC_INLINE_DEFINITION unsigned char ELF32_ST_BIND (unsigned char info)
Definition at line 193 of file elf.h.
{
     return info >> 4;
 }
ELF32_ST_INFO()
__MLIBC_INLINE_DEFINITION unsigned char ELF32_ST_INFO (unsigned char bind, unsigned char type)
Definition at line 199 of file elf.h.
{
     return (bind << 4) | (type & 0xF);
 }
References bind().
ELF32_ST_TYPE()
__MLIBC_INLINE_DEFINITION unsigned char ELF32_ST_TYPE (unsigned char info)
Definition at line 196 of file elf.h.
{
     return info & 0xF;
 }
ELF64_R_SYM()
__MLIBC_INLINE_DEFINITION Elf64_Xword ELF64_R_SYM (Elf64_Xword info)
Definition at line 268 of file elf.h.
{
     return info >> 32;
 }
Referenced by Loader::_processLazyRelocations(), Loader::_processRela(), lazyRelocate(), processCopyRela(), and relocateSelf().
ELF64_R_TYPE()
__MLIBC_INLINE_DEFINITION Elf64_Xword ELF64_R_TYPE (Elf64_Xword info)
Definition at line 271 of file elf.h.
{
     return info & 0xFFFFFFFF;
 }
Referenced by Loader::_processLazyRelocations(), Loader::_processRela(), lazyRelocate(), processCopyRela(), and relocateSelf().
ELF64_ST_BIND()
__MLIBC_INLINE_DEFINITION unsigned char ELF64_ST_BIND (unsigned char info)
Definition at line 178 of file elf.h.
{
     return info >> 4;
 }
Referenced by Loader::_processLazyRelocations(), Loader::_processRela(), resolveInObject(), and ObjectSymbol::virtualAddress().
ELF64_ST_INFO()
__MLIBC_INLINE_DEFINITION unsigned char ELF64_ST_INFO (unsigned char bind, unsigned char type)
Definition at line 184 of file elf.h.
{
     return (bind << 4) | type;
 }
References bind().
ELF64_ST_TYPE()
__MLIBC_INLINE_DEFINITION unsigned char ELF64_ST_TYPE (unsigned char info)
Definition at line 181 of file elf.h.
{
     return info & 0x0F;
 }