Fennix: Userspace/musl/src/stdio/fmemopen.c File Reference
fmemopen.c File Reference
#include "stdio_impl.h"
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <stddef.h>
#include <inttypes.h>
#include "libc.h"
Data Structures
struct cookie
struct mem_FILE
Functions
static off_t mseek (FILE *f, off_t off, int whence)
static size_t mread (FILE *f, unsigned char *buf, size_t len)
static size_t mwrite (FILE *f, const unsigned char *buf, size_t len)
static int mclose (FILE *m)
FILE * fmemopen (void *restrict buf, size_t size, const char *restrict mode)
Data Structure Documentation
cookie
struct cookie
Definition at line 9 of file fmemopen.c.
Data Fields
unsigned char * buf
char * buf
wchar_t * buf
char ** bufp
wchar_t ** bufp
size_t l
size_t len
mbstate_t mbs
int mode
size_t n
size_t pos
char * s
size_t size
size_t * sizep
size_t space
wchar_t * ws
mem_FILE
struct mem_FILE
Definition at line 15 of file fmemopen.c.
Data Fields
unsigned char buf[UNGET+BUFSIZ]
unsigned char buf2[]
struct cookie c
FILE f
Function Documentation
fmemopen()
FILE* fmemopen (void *restrict buf, size_t size, const char *restrict mode)
Definition at line 82 of file fmemopen.c.
 {
     struct mem_FILE *f;
     int plus = !!strchr(mode, '+');
     if (!strchr("rwa", *mode)) {
         errno = EINVAL;
         return 0;
     }
     if (!buf && size > PTRDIFF_MAX) {
         errno = ENOMEM;
         return 0;
     }
     f = malloc(sizeof *f + (buf?0:size));
     if (!f) return 0;
     memset(f, 0, offsetof(struct mem_FILE, buf));
     f->f.cookie = &f->c;
     f->f.fd = -1;
     f->f.lbf = EOF;
     f->f.buf = f->buf + UNGET;
     f->f.buf_size = sizeof f->buf - UNGET;
     if (!buf) {
         buf = f->buf2;
         memset(buf, 0, size);
     }
     f->c.buf = buf;
     f->c.size = size;
     f->c.mode = *mode;
     if (!plus) f->f.flags = (*mode == 'r') ? F_NOWR : F_NORD;
     if (*mode == 'r') f->c.len = size;
     else if (*mode == 'a') f->c.len = f->c.pos = strnlen(buf, size);
     else if (plus) *f->c.buf = 0;
     f->f.read = mread;
     f->f.write = mwrite;
     f->f.seek = mseek;
     f->f.close = mclose;
     if (!libc.threaded) f->f.lock = -1;
     return __ofl_add(&f->f);
 }
References __ofl_add(), buf, EINVAL, ENOMEM, EOF, errno, f, F_NORD, F_NOWR, libc, malloc, mclose(), memset, mread(), mseek(), mwrite(), offsetof, PTRDIFF_MAX, size, strchr(), strnlen(), and UNGET.
Referenced by setusershell().
mclose()
static int mclose (FILE * m) static
Definition at line 77 of file fmemopen.c.
 {
     return 0;
 }
Referenced by fmemopen().
mread()
static size_t mread (FILE * f, unsigned char * buf, size_t len) static
Definition at line 35 of file fmemopen.c.
 {
     struct cookie *c = f->cookie;
     size_t rem = c->len - c->pos;
     if (c->pos > c->len) rem = 0;
     if (len > rem) {
         len = rem;
         f->flags |= F_EOF;
     }
     memcpy(buf, c->buf+c->pos, len);
     c->pos += len;
     rem -= len;
     if (rem > f->buf_size) rem = f->buf_size;
     f->rpos = f->buf;
     f->rend = f->buf + rem;
     memcpy(f->rpos, c->buf+c->pos, rem);
     c->pos += rem;
     return len;
 }
References buf, c, f, F_EOF, len, and memcpy.
Referenced by fmemopen().
mseek()
static off_t mseek (FILE * f, off_t off, int whence) static
Definition at line 21 of file fmemopen.c.
 {
     ssize_t base;
     struct cookie *c = f->cookie;
     if (whence>2U) {
 fail:
         errno = EINVAL;
         return -1;
     }
     base = (size_t [3]){0, c->pos, c->len}[whence];
     if (off < -base || off > (ssize_t)c->size-base) goto fail;
     return c->pos = base+off;
 }
References base, c, EINVAL, errno, f, and off.
Referenced by fmemopen().
mwrite()
static size_t mwrite (FILE * f, const unsigned char * buf, size_t len) static
Definition at line 55 of file fmemopen.c.
 {
     struct cookie *c = f->cookie;
     size_t rem;
     size_t len2 = f->wpos - f->wbase;
     if (len2) {
         f->wpos = f->wbase;
         if (mwrite(f, f->wpos, len2) < len2) return 0;
     }
     if (c->mode == 'a') c->pos = c->len;
     rem = c->size - c->pos;
     if (len > rem) len = rem;
     memcpy(c->buf+c->pos, buf, len);
     c->pos += len;
     if (c->pos > c->len) {
         c->len = c->pos;
         if (c->len < c->size) c->buf[c->len] = 0;
         else if ((f->flags&F_NORD) && c->size) c->buf[c->size-1] = 0;
     }
     return len;
 }
References buf, c, f, F_NORD, len, and memcpy.
Referenced by fmemopen().