Fennix: Userspace/apps/base/busybox/loginutils/getty.c File Reference
getty.c File Reference
#include "libbb.h"
#include <syslog.h>
Data Structures
struct globals
Macros
#define IUCLC 0
#define ENABLE_FEATURE_UTMP 0
#define ENABLE_FEATURE_WTMP 0
#define debug(...) ((void)0)
#define _PATH_LOGIN "/bin/login"
#define ISSUE "/etc/issue"
#define CTL(x) ((x) ^ 0100)
#define MAX_SPEED 10 /* max. nr. of baud rates */
#define G (*ptr_to_globals)
#define INIT_G()
#define OPT_STR "I:LH:f:hil:mt:+wn"
#define F_INITSTRING (1 << 0) /* -I */
#define F_LOCAL (1 << 1) /* -L */
#define F_FAKEHOST (1 << 2) /* -H */
#define F_CUSTISSUE (1 << 3) /* -f */
#define F_RTSCTS (1 << 4) /* -h */
#define F_NOISSUE (1 << 5) /* -i */
#define F_LOGIN (1 << 6) /* -l */
#define F_PARSE (1 << 7) /* -m */
#define F_TIMEOUT (1 << 8) /* -t */
#define F_WAITCRLF (1 << 9) /* -w */
#define F_NOPROMPT (1 << 10) /* -n */
Functions
static int bcode (const char *s)
static void parse_speeds (char *arg)
static void parse_args (char **argv)
static void open_tty (void)
static void set_tty_attrs (void)
static void init_tty_attrs (int speed)
static void finalize_tty_attrs (void)
static void auto_baud (void)
static char * get_logname (void)
static void alarm_handler (int sig UNUSED_PARAM)
static void sleep10 (void)
int getty_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
_PATH_LOGIN
#define _PATH_LOGIN "/bin/login"
Definition at line 79 of file getty.c.
CTL
#define CTL (x) ((x) ^ 0100)
Definition at line 89 of file getty.c.
debug
#define debug (...) ((void)0)
Definition at line 67 of file getty.c.
ENABLE_FEATURE_UTMP
#define ENABLE_FEATURE_UTMP 0
Definition at line 56 of file getty.c.
ENABLE_FEATURE_WTMP
#define ENABLE_FEATURE_WTMP 0
Definition at line 57 of file getty.c.
F_CUSTISSUE
#define F_CUSTISSUE (1 << 3) /* -f */
Definition at line 138 of file getty.c.
F_FAKEHOST
#define F_FAKEHOST (1 << 2) /* -H */
Definition at line 137 of file getty.c.
F_INITSTRING
#define F_INITSTRING (1 << 0) /* -I */
Definition at line 135 of file getty.c.
F_LOCAL
#define F_LOCAL (1 << 1) /* -L */
Definition at line 136 of file getty.c.
F_LOGIN
#define F_LOGIN (1 << 6) /* -l */
Definition at line 141 of file getty.c.
F_NOISSUE
#define F_NOISSUE (1 << 5) /* -i */
Definition at line 140 of file getty.c.
F_NOPROMPT
#define F_NOPROMPT (1 << 10) /* -n */
Definition at line 145 of file getty.c.
F_PARSE
#define F_PARSE (1 << 7) /* -m */
Definition at line 142 of file getty.c.
F_RTSCTS
#define F_RTSCTS (1 << 4) /* -h */
Definition at line 139 of file getty.c.
F_TIMEOUT
#define F_TIMEOUT (1 << 8) /* -t */
Definition at line 143 of file getty.c.
F_WAITCRLF
#define F_WAITCRLF (1 << 9) /* -w */
Definition at line 144 of file getty.c.
G
#define G (*ptr_to_globals)
Definition at line 111 of file getty.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    SET_PTR_TO_GLOBALS(xzalloc(sizeof(G))); \
} while (0)
Definition at line 112 of file getty.c.
ISSUE
#define ISSUE "/etc/issue"
Definition at line 86 of file getty.c.
IUCLC
#define IUCLC 0
Definition at line 50 of file getty.c.
MAX_SPEED
#define MAX_SPEED 10 /* max. nr. of baud rates */
Definition at line 95 of file getty.c.
OPT_STR
#define OPT_STR "I:LH:f:hil:mt:+wn"
Definition at line 134 of file getty.c.
Function Documentation
alarm_handler()
static void alarm_handler (int sig UNUSED_PARAM) static
Definition at line 538 of file getty.c.
 {
     finalize_tty_attrs();
     _exit_SUCCESS();
 }
References _exit_SUCCESS(), and finalize_tty_attrs().
Referenced by getty_main(), and wget_main().
auto_baud()
static void auto_baud (void) static
Definition at line 411 of file getty.c.
 {
     int nread;
     /*
      * This works only if the modem produces its status code AFTER raising
      * the DCD line, and if the computer is fast enough to set the proper
      * baud rate before the message has gone by. We expect a message of the
      * following format:
      *
      * <junk><number><junk>
      *
      * The number is interpreted as the baud rate of the incoming call. If the
      * modem does not tell us the baud rate within one second, we will keep
      * using the current baud rate. It is advisable to enable BREAK
      * processing (comma-separated list of baud rates) if the processing of
      * modem status messages is enabled.
      */
     G.tty_attrs.c_cc[VMIN] = 0; /* don't block reads (min read is 0 chars) */
     set_tty_attrs();
     /*
      * Wait for a while, then read everything the modem has said so far and
      * try to extract the speed of the dial-in call.
      */
     sleep1();
     nread = safe_read(STDIN_FILENO, G.line_buf, sizeof(G.line_buf) - 1);
     if (nread > 0) {
         int speed;
         char *bp;
         G.line_buf[nread] = '\0';
         for (bp = G.line_buf; bp < G.line_buf + nread; bp++) {
             if (isdigit(*bp)) {
                 speed = bcode(bp);
                 if (speed > 0)
                     cfsetspeed(&G.tty_attrs, speed);
                 break;
             }
         }
     }
     /* Restore terminal settings */
     G.tty_attrs.c_cc[VMIN] = 1; /* restore to value set by init_tty_attrs */
     set_tty_attrs();
 }
References bcode(), bp, G, isdigit, safe_read(), set_tty_attrs(), sleep1(), STDIN_FILENO, and VMIN.
Referenced by getty_main().
bcode()
static int bcode (const char * s) static
Definition at line 149 of file getty.c.
 {
     int value = bb_strtou(s, NULL, 10); /* yes, int is intended! */
     if (value < 0) /* bad terminating char, overflow, etc */
         return value;
     return tty_value_to_baud(value);
 }
References bb_strtou(), NULL, s, tty_value_to_baud(), and value.
Referenced by auto_baud(), and parse_speeds().
finalize_tty_attrs()
static void finalize_tty_attrs (void) static
Definition at line 331 of file getty.c.
 {
     /* software flow control on output (stop sending if XOFF is recvd);
      * and on input (send XOFF when buffer is full)
      */
     G.tty_attrs.c_iflag |= IXON | IXOFF;
     if (G.eol == '\r') {
         G.tty_attrs.c_iflag |= ICRNL; /* map CR on input to NL */
     }
     /* Other bits in c_iflag:
      * IXANY   Any recvd char enables output (any char is also a XON)
      * INPCK   Enable parity check
      * IGNPAR  Ignore parity errors (drop bad bytes)
      * PARMRK  Mark parity errors with 0xff, 0x00 prefix
      *         (else bad byte is received as 0x00)
      * ISTRIP  Strip parity bit
      * IGNBRK  Ignore break condition
      * BRKINT  Send SIGINT on break - maybe set this?
      * INLCR   Map NL to CR
      * IGNCR   Ignore CR
      * ICRNL   Map CR to NL
      * IUCLC   Map uppercase to lowercase
      * IMAXBEL Echo BEL on input line too long
      * IUTF8   Appears to affect tty's idea of char widths,
      *         observed to improve backspacing through Unicode chars
      */
     /* ICANON  line buffered input (NL or EOL or EOF chars end a line);
      * ISIG    recognize INT/QUIT/SUSP chars;
      * ECHO    echo input chars;
      * ECHOE   echo BS-SP-BS on erase character;
      * ECHOK   echo kill char specially, not as ^c (ECHOKE controls how exactly);
      * ECHOKE  erase all input via BS-SP-BS on kill char (else go to next line)
      * ECHOCTL Echo ctrl chars as ^c (else echo verbatim:
      *         e.g. up arrow emits "ESC-something" and thus moves cursor up!)
      */
     G.tty_attrs.c_lflag |= ICANON | ISIG | ECHO | ECHOE | ECHOK | ECHOKE | ECHOCTL;
     /* Other bits in c_lflag:
      * XCASE   Map uppercase to \lowercase [tried, doesn't work]
      * ECHONL  Echo NL even if ECHO is not set
      * ECHOPRT On erase, echo erased chars
      *         [qwe<BS><BS><BS> input looks like "qwe\ewq/" on screen]
      * NOFLSH  Don't flush input buffer after interrupt or quit chars
      * IEXTEN  Enable extended functions (??)
      *         [glibc says it enables c_cc[LNEXT] "enter literal char"
      *         and c_cc[VDISCARD] "toggle discard buffered output" chars]
      * FLUSHO  Output being flushed (c_cc[VDISCARD] is in effect)
      * PENDIN  Retype pending input at next read or input char
      *         (c_cc[VREPRINT] is being processed)
      * TOSTOP  Send SIGTTOU for background output
      *         (why "stty sane" unsets this bit?)
      */
     G.tty_attrs.c_cc[VINTR] = CTL('C');
     G.tty_attrs.c_cc[VQUIT] = CTL('\\');
     G.tty_attrs.c_cc[VEOF] = CTL('D');
     G.tty_attrs.c_cc[VEOL] = '\n';
 #ifdef VSWTC
     G.tty_attrs.c_cc[VSWTC] = 0;
 #endif
 #ifdef VSWTCH
     G.tty_attrs.c_cc[VSWTCH] = 0;
 #endif
     G.tty_attrs.c_cc[VKILL] = CTL('U');
     /* Other control chars:
      * VEOL2
      * VERASE, VWERASE - (word) erase. we may set VERASE in get_logname
      * VREPRINT - reprint current input buffer
      * VLNEXT, VDISCARD, VSTATUS
      * VSUSP, VDSUSP - send (delayed) SIGTSTP
      * VSTART, VSTOP - chars used for IXON/IXOFF
      */
     set_tty_attrs();
     /* Now the newline character should be properly written */
     full_write1_str("\n");
 }
References CTL, ECHO, ECHOCTL, ECHOE, ECHOK, ECHOKE, full_write1_str(), G, ICANON, ICRNL, ISIG, IXOFF, IXON, set_tty_attrs(), VEOF, VEOL, VINTR, VKILL, VQUIT, VSWTC, and VSWTCH.
Referenced by alarm_handler(), get_logname(), and getty_main().
get_logname()
static char* get_logname (void) static
Definition at line 461 of file getty.c.
 {
     char *bp;
     char c;
     /* Flush pending input (esp. after parsing or switching the baud rate) */
     usleep(100*1000); /* 0.1 sec */
     tcflush(STDIN_FILENO, TCIFLUSH);
     /* Prompt for and read a login name */
     do {
         /* Write issue file and prompt */
 #ifdef ISSUE
         if (!(option_mask32 & F_NOISSUE))
             print_login_issue(G.issue, G.tty_name);
 #endif
         print_login_prompt();
         /* Read name, watch for break, erase, kill, end-of-line */
         bp = G.line_buf;
         while (1) {
             /* Do not report trivial EINTR/EIO errors */
             errno = EINTR; /* make read of 0 bytes be silent too */
             if (read(STDIN_FILENO, &c, 1) < 1) {
                 finalize_tty_attrs();
                 if (errno == EINTR || errno == EIO)
                     exit_SUCCESS();
                 bb_simple_perror_msg_and_die(bb_msg_read_error);
             }
             switch (c) {
             case '\r':
             case '\n':
                 *bp = '\0';
                 G.eol = c;
                 goto got_logname;
             case CTL('H'):
             case 0x7f:
                 G.tty_attrs.c_cc[VERASE] = c;
                 if (bp > G.line_buf) {
                     full_write1_str("\010 \010");
                     bp--;
                 }
                 break;
             case CTL('U'):
                 while (bp > G.line_buf) {
                     full_write1_str("\010 \010");
                     bp--;
                 }
                 break;
             case CTL('C'):
             case CTL('D'):
                 finalize_tty_attrs();
                 exit_SUCCESS();
             case '\0':
                 /* BREAK. If we have speeds to try,
                  * return NULL (will switch speeds and return here) */
                 if (G.numspeed > 1)
                     return NULL;
                 /* fall through and ignore it */
             default:
                 if ((unsigned char)c < ' ') {
                     /* ignore garbage characters */
                 } else if ((int)(bp - G.line_buf) < sizeof(G.line_buf) - 1) {
                     /* echo and store the character */
                     full_write(STDOUT_FILENO, &c, 1);
                     *bp++ = c;
                 }
                 break;
             }
         } /* end of get char loop */
  got_logname: ;
     } while (G.line_buf[0] == '\0');  /* while logname is empty */
     return G.line_buf;
 }
References bb_msg_read_error, bb_simple_perror_msg_and_die(), bp, c, CTL, EINTR, EIO, errno, exit_SUCCESS(), F_NOISSUE, finalize_tty_attrs(), full_write(), full_write1_str(), G, NULL, option_mask32, print_login_issue(), print_login_prompt(), read(), STDIN_FILENO, STDOUT_FILENO, tcflush(), TCIFLUSH, usleep(), and VERASE.
Referenced by getty_main().
getty_main()
int getty_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 550 of file getty.c.
 {
     int n;
     pid_t pid, tsid;
     char *logname;
     INIT_G();
     G.login = _PATH_LOGIN;    /* default login program */
 #ifdef ISSUE
     G.issue = ISSUE;          /* default issue file */
 #endif
     G.eol = '\r';
     /* Parse command-line arguments */
     parse_args(argv);
     /* Create new session and pgrp, lose controlling tty */
     pid = setsid();  /* this also gives us our pid :) */
     if (pid < 0) {
         int fd;
         /* :(
          * docs/ctty.htm says:
          * "This is allowed only when the current process
          *  is not a process group leader".
          * Thus, setsid() will fail if we _already_ are
          * a session leader - which is quite possible for getty!
          */
         pid = getpid();
         if (getsid(0) != pid) {
             //for debugging:
             //bb_perror_msg_and_die("setsid failed:"
             //  " pid %d ppid %d"
             //  " sid %d pgid %d",
             //  pid, getppid(),
             //  getsid(0), getpgid(0));
             bb_simple_perror_msg_and_die("setsid");
             /*
              * When we can end up here?
              * Example: setsid() fails when run alone in interactive shell:
              *  # getty 115200 /dev/tty2
              * because shell's child (getty) is put in a new process group.
              * But doesn't fail if shell is not interactive
              * (and therefore doesn't create process groups for pipes),
              * or if getty is not the first process in the process group:
              *  # true | getty 115200 /dev/tty2
              */
         }
         /* Looks like we are already a session leader.
          * In this case (setsid failed) we may still have ctty,
          * and it may be different from tty we need to control!
          * If we still have ctty, on Linux ioctl(TIOCSCTTY)
          * (which we are going to use a bit later) always fails -
          * even if we try to take ctty which is already ours!
          * Try to drop old ctty now to prevent that.
          * Use O_NONBLOCK: old ctty may be a serial line.
          */
         fd = open("/dev/tty", O_RDWR | O_NONBLOCK);
         if (fd >= 0) {
             /* TIOCNOTTY sends SIGHUP to the foreground
              * process group - which may include us!
              * Make sure to not die on it:
              */
             sighandler_t old = signal(SIGHUP, SIG_IGN);
             ioctl(fd, TIOCNOTTY);
             close(fd);
             signal(SIGHUP, old);
         }
     }
     /* Close stdio, and stray descriptors, just in case */
     n = xopen(bb_dev_null, O_RDWR);
     /* dup2(n, 0); - no, we need to handle "getty - 9600" too */
     xdup2(n, 1);
     xdup2(n, 2);
     while (n > 2)
         close(n--);
     /* Logging. We want special flavor of error_msg_and_die */
     die_func = sleep10;
     msg_eol = "\r\n";
     /* most likely will internally use fd #3 in CLOEXEC mode: */
     openlog(applet_name, LOG_PID, LOG_AUTH);
     logmode = LOGMODE_BOTH;
 #ifdef DEBUGGING
     dbf = xfopen_for_write(DEBUGTERM);
     for (n = 1; argv[n]; n++) {
         debug(argv[n]);
         debug("\n");
     }
 #endif
     /* Open the tty as standard input, if it is not "-" */
     debug("calling open_tty\n");
     open_tty();
     ndelay_off(STDIN_FILENO);
     debug("duping\n");
     xdup2(STDIN_FILENO, 1);
     xdup2(STDIN_FILENO, 2);
     /* Steal ctty if we don't have it yet */
     tsid = tcgetsid(STDIN_FILENO);
     if (tsid < 0 || pid != tsid) {
         if (ioctl(STDIN_FILENO, TIOCSCTTY, /*force:*/ (long)1) < 0)
             bb_simple_perror_msg_and_die("TIOCSCTTY");
     }
 #ifdef __linux__
     /* Make ourself a foreground process group within our session */
     if (tcsetpgrp(STDIN_FILENO, pid) < 0)
         bb_simple_perror_msg_and_die("tcsetpgrp");
 #endif
     /*
      * The following ioctl will fail if stdin is not a tty, but also when
      * there is noise on the modem control lines. In the latter case, the
      * common course of action is (1) fix your cables (2) give the modem more
      * time to properly reset after hanging up. SunOS users can achieve (2)
      * by patching the SunOS kernel variable "zsadtrlow" to a larger value;
      * 5 seconds seems to be a good value.
      */
     if (tcgetattr(STDIN_FILENO, &G.tty_attrs) < 0)
         bb_simple_perror_msg_and_die("tcgetattr");
     /* Update the utmp file. This tty is ours now! */
     update_utmp(pid, LOGIN_PROCESS, G.tty_name, "LOGIN", G.fakehost);
     /* Initialize tty attrs (raw mode, eight-bit, blocking i/o) */
     debug("calling init_tty_attrs\n");
     init_tty_attrs(G.speeds[0]);
     /* Write the modem init string and DON'T flush the buffers */
     if (option_mask32 & F_INITSTRING) {
         debug("writing init string\n");
         full_write1_str(G.initstring);
     }
     /* Optionally detect the baud rate from the modem status message */
     debug("before autobaud\n");
     if (option_mask32 & F_PARSE)
         auto_baud();
     /* Set the optional timer */
     signal(SIGALRM, alarm_handler);
     alarm(G.timeout); /* if 0, alarm is not set */
     /* Optionally wait for CR or LF before writing /etc/issue */
     if (option_mask32 & F_WAITCRLF) {
         char ch;
         debug("waiting for cr-lf\n");
         while (safe_read(STDIN_FILENO, &ch, 1) == 1) {
             debug("read %x\n", (unsigned char)ch);
             if (ch == '\n' || ch == '\r')
                 break;
         }
     }
     logname = NULL;
     if (!(option_mask32 & F_NOPROMPT)) {
         /* NB: init_tty_attrs already set line speed
          * to G.speeds[0] */
         int baud_index = 0;
         while (1) {
             /* Read the login name */
             debug("reading login name\n");
             logname = get_logname();
             if (logname)
                 break;
             /* We are here only if G.numspeed > 1 */
             baud_index = (baud_index + 1) % G.numspeed;
             cfsetspeed(&G.tty_attrs, G.speeds[baud_index]);
             set_tty_attrs();
         }
     }
     /* Disable timer */
     alarm(0);
     finalize_tty_attrs();
     /* Let the login program take care of password validation */
     /* We use PATH because we trust that root doesn't set "bad" PATH,
      * and getty is not suid-root applet */
     /* With -n, logname == NULL, and login will ask for username instead */
     BB_EXECLP(G.login, G.login, "--", logname, (char *)0);
     bb_error_msg_and_die("can't execute '%s'", G.login);
 }
References _PATH_LOGIN, alarm(), alarm_handler(), applet_name, argv, auto_baud(), bb_dev_null, bb_error_msg_and_die(), BB_EXECLP, bb_simple_perror_msg_and_die(), close(), debug, die_func, F_INITSTRING, F_NOPROMPT, F_PARSE, F_WAITCRLF, fd, finalize_tty_attrs(), full_write1_str(), G, get_logname(), getpid(), getsid(), INIT_G, init_tty_attrs(), ioctl(), ISSUE, LOG_AUTH, LOG_PID, LOGIN_PROCESS, logmode, LOGMODE_BOTH, msg_eol, n, ndelay_off(), NULL, O_NONBLOCK, O_RDWR, old, open(), open_tty(), openlog(), option_mask32, parse_args(), pid, safe_read(), set_tty_attrs(), setsid(), SIG_IGN, SIGALRM, SIGHUP, signal, sleep10(), STDIN_FILENO, tcgetattr(), tcgetsid(), tcsetpgrp, TIOCNOTTY, TIOCSCTTY, update_utmp(), xdup2(), xfopen_for_write(), and xopen().
init_tty_attrs()
static void init_tty_attrs (int speed) static
Definition at line 256 of file getty.c.
 {
     /* Try to drain output buffer, with 5 sec timeout.
      * Added on request from users of ~600 baud serial interface
      * with biggish buffer on a 90MHz CPU.
      * They were losing hundreds of bytes of buffered output
      * on tcflush.
      */
     signal_no_SA_RESTART_empty_mask(SIGALRM, record_signo);
     alarm(5);
     tcdrain(STDIN_FILENO);
     alarm(0);
     /* Flush input and output queues, important for modems! */
     tcflush(STDIN_FILENO, TCIOFLUSH);
     /* Set speed if it wasn't specified as "0" on command line */
     if (speed != B0)
         cfsetspeed(&G.tty_attrs, speed);
     /* Initial settings: 8-bit characters, raw mode, blocking i/o.
      * Special characters are set after we have read the login name; all
      * reads will be done in raw mode anyway.
      */
     /* Clear all bits except: */
     G.tty_attrs.c_cflag &= (0
         /* 2 stop bits (1 otherwise)
          * Enable parity bit (both on input and output)
          * Odd parity (else even)
          */
         | CSTOPB | PARENB | PARODD
 #ifdef CMSPAR
         | CMSPAR  /* mark or space parity */
 #endif
 #ifdef CBAUD
         | CBAUD   /* (output) baud rate */
 #endif
 #ifdef CBAUDEX
         | CBAUDEX /* (output) baud rate */
 #endif
 #ifdef CIBAUD
         | CIBAUD   /* input baud rate */
 #endif
     );
     /* Set: 8 bits; hang up (drop DTR) on last close; enable receive */
     G.tty_attrs.c_cflag |= CS8 | HUPCL | CREAD;
     if (option_mask32 & F_LOCAL) {
         /* ignore Carrier Detect pin:
          * opens don't block when CD is low,
          * losing CD doesn't hang up processes whose ctty is this tty
          */
         G.tty_attrs.c_cflag |= CLOCAL;
     }
 #ifdef CRTSCTS
     if (option_mask32 & F_RTSCTS)
         G.tty_attrs.c_cflag |= CRTSCTS; /* flow control using RTS/CTS pins */
 #endif
     G.tty_attrs.c_iflag = 0;
     G.tty_attrs.c_lflag = 0;
     /* non-raw output; add CR to each NL */
     G.tty_attrs.c_oflag = OPOST | ONLCR;
     /* reads will block only if < 1 char is available */
     G.tty_attrs.c_cc[VMIN] = 1;
     /* no timeout (reads block forever) */
     G.tty_attrs.c_cc[VTIME] = 0;
 #ifdef __linux__
     G.tty_attrs.c_line = 0;
 #endif
     set_tty_attrs();
     debug("term_io 2\n");
 }
References alarm(), B0, CBAUD, CBAUDEX, CIBAUD, CLOCAL, CMSPAR, CREAD, CRTSCTS, CS8, CSTOPB, debug, F_LOCAL, F_RTSCTS, G, HUPCL, ONLCR, OPOST, option_mask32, PARENB, PARODD, record_signo(), set_tty_attrs(), SIGALRM, signal_no_SA_RESTART_empty_mask(), STDIN_FILENO, tcdrain(), tcflush(), TCIOFLUSH, VMIN, and VTIME.
Referenced by getty_main().
open_tty()
static void open_tty (void) static
Definition at line 211 of file getty.c.
 {
     /* Set up new standard input, unless we are given an already opened port */
     if (NOT_LONE_DASH(G.tty_name)) {
         if (G.tty_name[0] != '/')
             G.tty_name = xasprintf("/dev/%s", G.tty_name); /* will leak it */
         /* Open the tty as standard input */
         debug("open(2)\n");
         close(0);
         xopen(G.tty_name, O_RDWR | O_NONBLOCK); /* uses fd 0 */
         /* Set proper protections and ownership */
         fchown(0, 0, 0);        /* 0:0 */
         fchmod(0, 0620);        /* crw--w---- */
     } else {
         char *n;
         /*
          * Standard input should already be connected to an open port.
          * Make sure it is open for read/write.
          */
         if ((fcntl(0, F_GETFL) & (O_RDWR|O_RDONLY|O_WRONLY)) != O_RDWR)
             bb_simple_error_msg_and_die("stdin is not open for read/write");
         /* Try to get real tty name instead of "-" */
         n = xmalloc_ttyname(0);
         if (n)
             G.tty_name = n;
     }
     applet_name = xasprintf("getty: %s", skip_dev_pfx(G.tty_name));
 }
References applet_name, bb_simple_error_msg_and_die(), close(), debug, F_GETFL, fchmod(), fchown(), fcntl(), G, n, NOT_LONE_DASH, O_NONBLOCK, O_RDONLY, O_RDWR, O_WRONLY, skip_dev_pfx(), xasprintf(), xmalloc_ttyname(), and xopen().
Referenced by getty_main().
parse_args()
static void parse_args (char ** argv) static
Definition at line 177 of file getty.c.
 {
     char *ts;
     int flags;
     flags = getopt32(argv, "^" OPT_STR "\0" "-2"/* at least 2 args*/,
         &G.initstring, &G.fakehost, &G.issue,
         &G.login, &G.timeout
     );
     if (flags & F_INITSTRING) {
         G.initstring = xstrdup(G.initstring);
         /* decode \ddd octal codes into chars */
         strcpy_and_process_escape_sequences(G.initstring, G.initstring);
     }
     argv += optind;
     debug("after getopt\n");
     /* We loosen up a bit and accept both "baudrate tty" and "tty baudrate" */
     G.tty_name = argv[0];
     ts = argv[1];            /* baud rate(s) */
     if (isdigit(argv[0][0])) {
         /* A number first, assume it's a speed (BSD style) */
         G.tty_name = ts; /* tty name is in argv[1] */
         ts = argv[0];    /* baud rate(s) */
     }
     parse_speeds(ts);
     if (argv[2])
         xsetenv("TERM", argv[2]);
     debug("exiting parse_args\n");
 }
References argv, debug, F_INITSTRING, flags, G, getopt32(), isdigit, OPT_STR, optind, parse_speeds(), strcpy_and_process_escape_sequences(), xsetenv(), and xstrdup().
Referenced by getty_main().
parse_speeds()
static void parse_speeds (char * arg) static
Definition at line 158 of file getty.c.
 {
     char *cp;
     /* NB: at least one iteration is always done */
     debug("entered parse_speeds\n");
     while ((cp = strsep(&arg, ",")) != NULL) {
         G.speeds[G.numspeed] = bcode(cp);
         if (G.speeds[G.numspeed] < 0)
             bb_error_msg_and_die("bad speed: %s", cp);
         /* note: arg "0" turns into speed B0 */
         G.numspeed++;
         if (G.numspeed > MAX_SPEED)
             bb_simple_error_msg_and_die("too many alternate speeds");
     }
     debug("exiting parse_speeds\n");
 }
References bb_error_msg_and_die(), bb_simple_error_msg_and_die(), bcode(), debug, G, MAX_SPEED, NULL, and strsep().
Referenced by parse_args().
set_tty_attrs()
static void set_tty_attrs (void) static
Definition at line 243 of file getty.c.
 {
     if (tcsetattr_stdin_TCSANOW(&G.tty_attrs) < 0)
         bb_simple_perror_msg_and_die("tcsetattr");
 }
References bb_simple_perror_msg_and_die(), G, and tcsetattr_stdin_TCSANOW().
Referenced by auto_baud(), finalize_tty_attrs(), getty_main(), and init_tty_attrs().
sleep10()
static void sleep10 (void) static
Definition at line 544 of file getty.c.
 {
     sleep(10);
 }
References sleep().
Referenced by getty_main().