Fennix Kernel: Execute Namespace Reference
Execute Namespace Reference
Data Structures
struct InterpreterIPCDataLibrary
struct InterpreterIPCData
struct SpawnData
struct SharedLibraries
struct ELFBaseLoad
struct MmImage
Enumerations
enum BinaryType {
BinTypeInvalid , BinTypeFex , BinTypeELF , BinTypePE ,
BinTypeNE , BinTypeMZ , BinTypeUnknown
}
enum ExStatus {
Unknown , OK , Unsupported , GenericError ,
InvalidFile , InvalidFileFormat , InvalidFileHeader , InvalidFileData ,
InvalidFileEntryPoint , InvalidFilePath
}
Functions
void ELFInterpreterIPCThread (PCB *Process, char *Path, void *MemoryImage, void *ElfFile, std::vector< const char * > NeededLibraries)
void ELFInterpreterThreadWrapper ()
ELFBaseLoad ELFLoad (char *Path, const char **argv, const char **envp, Tasking::TaskCompatibility Compatibility)
ELFBaseLoad ELFLoadDyn (void *BaseImage, VirtualFileSystem::File &ExFile, Tasking::PCB *Process)
ELFBaseLoad ELFLoadExec (void *ElfFile, VirtualFileSystem::File &ExFile, Tasking::PCB *Process)
Elf64_Shdr * GetELFSheader (Elf64_Ehdr *Header)
Elf64_Shdr * GetELFSection (Elf64_Ehdr *Header, uint64_t Index)
char * GetELFStringTable (Elf64_Ehdr *Header)
char * ELFLookupString (Elf64_Ehdr *Header, uintptr_t Offset)
Elf64_Sym * ELFLookupSymbol (Elf64_Ehdr *Header, const char *Name)
uintptr_t ELFGetSymbolValue (Elf64_Ehdr *Header, uint64_t Table, uint64_t Index)
Elf64_Dyn * ELFGetDynamicTag (void *ElfFile, enum DynamicArrayTags Tag)
MmImage ELFCreateMemoryImage (Memory::MemMgr *mem, Memory::Virtual &pV, void *ElfFile, size_t Length)
Create a ELF Memory Image.
uintptr_t LoadELFInterpreter (Memory::MemMgr *mem, Memory::Virtual &pV, const char *Interpreter)
ELFBaseLoad ELFLoadRel (void *BaseImage, VirtualFileSystem::File &ExFile, Tasking::PCB *Process)
void StartExecuteService ()
bool AddLibrary (char *Identifier, void *ElfImage, size_t Length, const Memory::Virtual &pV)
void SearchLibrary (char *Identifier)
SharedLibraries GetLibrary (char *Identifier)
void FEXLoad ()
BinaryType GetBinaryType (void *Image)
BinaryType GetBinaryType (char *Path)
SpawnData Spawn (char *Path, const char **argv, const char **envp)
Variables
PCB * InterpreterTargetProcess
std::string * InterpreterTargetPath
void * InterpreterMemoryImage
void * InterpreterElfFile
std::vector< const char * > InterpreterNeededLibraries
Memory::MemMgr * mem = nullptr
std::vector< SharedLibraries > Libs
Data Structure Documentation
Execute::InterpreterIPCDataLibrary
struct Execute::InterpreterIPCDataLibrary
Definition at line 37 of file BaseLoad.cpp.
Data Fields
char Name[128]
Execute::InterpreterIPCData
struct Execute::InterpreterIPCData
Definition at line 42 of file BaseLoad.cpp.
Data Fields
void * ElfFile
struct InterpreterIPCDataLibrary Libraries[64]
void * MemoryImage
char Path[256]
Execute::SpawnData
struct Execute::SpawnData
Definition at line 55 of file exec.hpp.
Data Fields
PCB * Process
ExStatus Status
TCB * Thread
Execute::SharedLibraries
struct Execute::SharedLibraries
Definition at line 62 of file exec.hpp.
Data Fields
uintptr_t Address
char Identifier[64]
size_t Length
uintptr_t MemoryImage
int RefCount
uint64_t Timeout
Execute::ELFBaseLoad
struct Execute::ELFBaseLoad
Definition at line 73 of file exec.hpp.
Data Fields
vector< AuxiliaryVector > auxv
IP InstructionPointer
bool Interpreter
void * MemoryImage
vector< const char * > NeededLibraries
SpawnData sd
bool Success
MemMgr * TmpMem
void * VirtualMemoryImage
Execute::MmImage
struct Execute::MmImage
Definition at line 92 of file exec.hpp.
Data Fields
void * Physical
void * Virtual
Enumeration Type Documentation
BinaryType
enum Execute::BinaryType
Enumerator
BinTypeInvalid
BinTypeFex
BinTypeELF
BinTypePE
BinTypeNE
BinTypeMZ
BinTypeUnknown
Definition at line 30 of file exec.hpp.
     {
         BinTypeInvalid,
         BinTypeFex,
         BinTypeELF,
         BinTypePE,
         BinTypeNE,
         BinTypeMZ,
         BinTypeUnknown
     };
ExStatus
enum Execute::ExStatus
Enumerator
Unknown
OK
Unsupported
GenericError
InvalidFile
InvalidFileFormat
InvalidFileHeader
InvalidFileData
InvalidFileEntryPoint
InvalidFilePath
Definition at line 41 of file exec.hpp.
     {
         Unknown,
         OK,
         Unsupported,
         GenericError,
         InvalidFile,
         InvalidFileFormat,
         InvalidFileHeader,
         InvalidFileData,
         InvalidFileEntryPoint,
         InvalidFilePath
     };
Function Documentation
AddLibrary()
bool Execute::AddLibrary (char * Identifier, void * ElfImage, size_t Length, const Memory::Virtual & pV)
Definition at line 75 of file SharedObjects.cpp.
     {
         SmartLock(ExecuteServiceLock);
         SharedLibraries sl;
         foreach (auto lib in Libs)
         {
             if (strcmp(lib.Identifier, Identifier) == 0)
             {
                 debug("Library %s already loaded", Identifier);
                 lib.RefCount++;
                 return true;
             }
         }
         strcpy(sl.Identifier, Identifier);
         sl.Timeout = TimeManager->CalculateTarget(10, Time::Units::Minutes);
         sl.RefCount = 0;
         void *LibFile = mem->RequestPages(TO_PAGES(Length + 1), true);
         debug("LibFile: %#lx", LibFile);
         memcpy(LibFile, (void *)ElfImage, Length);
         Memory::Virtual().Map(LibFile, LibFile, Length, Memory::RW | Memory::US | Memory::G);
         Memory::Virtual ncpV = pV;
         sl.MemoryImage = r_cst(uint64_t, ELFCreateMemoryImage(mem, ncpV, LibFile, Length).Physical);
         debug("MemoryImage: %#lx", sl.MemoryImage);
         uintptr_t BaseAddress = UINTPTR_MAX;
         {
 #if defined(a64)
             Elf64_Phdr ItrProgramHeader;
             for (Elf64_Half i = 0; i < ((Elf64_Ehdr *)LibFile)->e_phnum; i++)
             {
                 memcpy(&ItrProgramHeader, (uint8_t *)LibFile + ((Elf64_Ehdr *)LibFile)->e_phoff + ((Elf64_Ehdr *)LibFile)->e_phentsize * i, sizeof(Elf64_Phdr));
                 BaseAddress = MIN(BaseAddress, ItrProgramHeader.p_vaddr);
             }
             for (Elf64_Half i = 0; i < ((Elf64_Ehdr *)LibFile)->e_phnum; i++)
             {
                 memcpy(&ItrProgramHeader, (uint8_t *)LibFile + ((Elf64_Ehdr *)LibFile)->e_phoff + ((Elf64_Ehdr *)LibFile)->e_phentsize * i, sizeof(Elf64_Phdr));
                 if (ItrProgramHeader.p_type != PT_LOAD)
                     continue;
                 debug("PT_LOAD - Offset: %#lx, VirtAddr: %#lx, FileSiz: %ld, MemSiz: %ld, Align: %#lx",
                       ItrProgramHeader.p_offset, ItrProgramHeader.p_vaddr,
                       ItrProgramHeader.p_filesz, ItrProgramHeader.p_memsz, ItrProgramHeader.p_align);
                 uintptr_t MAddr = (ItrProgramHeader.p_vaddr - BaseAddress) + (uintptr_t)sl.MemoryImage;
                 fixme("Address: %#lx %s%s%s", MAddr,
                       (ItrProgramHeader.p_flags & PF_R) ? "R" : "",
                       (ItrProgramHeader.p_flags & PF_W) ? "W" : "",
                       (ItrProgramHeader.p_flags & PF_X) ? "X" : "");
                 memcpy((void *)MAddr, (uint8_t *)LibFile + ItrProgramHeader.p_offset, ItrProgramHeader.p_filesz);
                 debug("memcpy: %#lx => %#lx (%ld bytes)", (uint8_t *)LibFile + ItrProgramHeader.p_offset, (uintptr_t)MAddr, ItrProgramHeader.p_filesz);
                 break;
 #elif defined(a32)
 #endif
             }
 #if defined(a64)
             struct Elf64_Dyn *JmpRel = ELFGetDynamicTag((void *)LibFile, DT_JMPREL);
             struct Elf64_Dyn *SymTab = ELFGetDynamicTag((void *)LibFile, DT_SYMTAB);
             struct Elf64_Dyn *StrTab = ELFGetDynamicTag((void *)LibFile, DT_STRTAB);
             if (!JmpRel)
             {
                 debug("No DT_JMPREL");
             }
             if (!SymTab)
             {
                 debug("No DT_SYMTAB");
             }
             if (!StrTab)
             {
                 debug("No DT_STRTAB");
             }
             if (JmpRel && SymTab && StrTab)
             {
                 debug("JmpRel: %#lx, SymTab: %#lx, StrTab: %#lx", JmpRel->d_un.d_ptr, SymTab->d_un.d_ptr, StrTab->d_un.d_ptr);
                 Elf64_Rela *_JmpRel = (Elf64_Rela *)(sl.MemoryImage + (JmpRel->d_un.d_ptr - BaseAddress));
                 Elf64_Sym *_SymTab = (Elf64_Sym *)(sl.MemoryImage + (SymTab->d_un.d_ptr - BaseAddress));
                 char *_DynStr = (char *)(sl.MemoryImage + (StrTab->d_un.d_ptr - BaseAddress));
                 Elf64_Shdr *gotSection = nullptr;
                 for (Elf64_Half i = 0; i < ((Elf64_Ehdr *)LibFile)->e_shnum; i++)
                 {
                     Elf64_Shdr *shdr = (Elf64_Shdr *)((uint8_t *)LibFile + ((Elf64_Ehdr *)LibFile)->e_shoff + i * sizeof(Elf64_Shdr));
                     if (shdr->sh_type == SHT_PROGBITS && (shdr->sh_flags & SHF_WRITE) && (shdr->sh_flags & SHF_ALLOC))
                     {
                         gotSection = shdr;
                         break;
                     }
                 }
                 debug("LIB_DBG");
                 if (gotSection)
                 {
                     Elf64_Xword numEntries = gotSection->sh_size / sizeof(Elf64_Addr);
                     for (Elf64_Xword i = 0; i < numEntries - 3; i++)
                     {
                         Elf64_Rela *Rel = _JmpRel + i;
                         Elf64_Addr *GOTEntry = (Elf64_Addr *)(Rel->r_offset + sl.MemoryImage);
                         Elf64_Xword RelType = ELF64_R_TYPE(Rel->r_info);
                         debug("r_offset: %#lx RelType: %d", Rel->r_offset, RelType);
                         switch (RelType)
{
                         case R_X86_64_NONE:
                             break;
                         case R_X86_64_JUMP_SLOT:
{
                             Elf64_Xword SymIndex = ELF64_R_SYM(Rel->r_info);
                             Elf64_Sym *Sym = _SymTab + SymIndex;
                             if (Sym->st_name)
{
                                 char *SymName = _DynStr + Sym->st_name;
                                 debug("SymName: %s", SymName);
                                 Elf64_Sym *LibSym = ELFLookupSymbol((Elf64_Ehdr *)LibFile, SymName);
                                 if (LibSym)
{
                                     *GOTEntry = (Elf64_Addr)(sl.MemoryImage + LibSym->st_value);
                                     debug("GOT[%ld]: %#lx + %#lx = %#lx", i, sl.MemoryImage, LibSym->st_value, *GOTEntry);
                                 }
                             }
                             break;
                         }
                         default:
{
                             fixme("RelType %d not supported", RelType);
                             break;
                         }
                         }
                         debug("GOT[%ld](%#lx): %#lx", i, GOTEntry, *GOTEntry);
                     }
                 }
                 else
                 {
                     debug("GOT section not found");
                 }
             }
         }
         sl.Address = r_cst(uint64_t, LibFile);
         debug("Casted LibFile %#lx -> %#lx", LibFile, sl.Address);
         sl.Length = Length;
         debug("Library %s loaded at %#lx (full file: %#lx)", Identifier, sl.MemoryImage, LibFile);
         Libs.push_back(sl);
         return true;
 #elif defined(a32)
         return false;
 #endif
     }
References Time::time::CalculateTarget(), Elf64_Dyn::d_un, debug, DT_JMPREL, DT_STRTAB, DT_SYMTAB, ELF64_R_SYM, ELF64_R_TYPE, ELFCreateMemoryImage(), ELFGetDynamicTag(), ELFLookupSymbol(), fixme, G(), Length, Libs, mem, memcpy(), MIN, Time::Minutes, Elf64_Phdr::p_align, Elf64_Phdr::p_filesz, Elf64_Phdr::p_flags, Elf64_Phdr::p_memsz, Elf64_Phdr::p_offset, Elf64_Phdr::p_type, Elf64_Phdr::p_vaddr, PF_R, PF_W, PF_X, APIC::Physical, PT_LOAD, Elf64_Rela::r_info, Elf64_Rela::r_offset, R_X86_64_JUMP_SLOT, R_X86_64_NONE, elf64_shdr::sh_flags, elf64_shdr::sh_size, elf64_shdr::sh_type, SHF_ALLOC, SHF_WRITE, SHT_PROGBITS, elf64_sym::st_name, elf64_sym::st_value, strcmp(), strcpy, TimeManager, and UINTPTR_MAX.
Referenced by sys_kernelctl().
ELFCreateMemoryImage()
MmImage Execute::ELFCreateMemoryImage (Memory::MemMgr * mem, Memory::Virtual & pV, void * ElfFile, size_t Length)
Create a ELF Memory Image.
Parameters
mem The memory manager to use
pV Memory::Virtual object to use
ElfFile ELF file loaded in memory (FULL FILE)
Length Length of ElfFile
Returns
The Memory Image (Physical and Virtual)
Definition at line 175 of file Parse.cpp.
     {
 #if defined(a64)
         void *MemoryImage = nullptr;
         Elf64_Ehdr *ELFHeader = (Elf64_Ehdr *)ElfFile;
         bool IsPIC = ELFHeader->e_type == ET_DYN;
         UNUSED(IsPIC);
         debug("Elf %s PIC", IsPIC ? "is" : "is not");
         /* TODO: Not sure what I am supposed to do with this.
          * It is supposed to detect if it's PIC or not but I
          * don't know if it's right. */
         if (ELFGetDynamicTag(ElfFile, DT_TEXTREL))
         {
             fixme("Text relocation is not(?) tested yet!");
             MemoryImage = (uint8_t *)mem->RequestPages(TO_PAGES(Length + 1), true);
             memset(MemoryImage, 0, Length);
             return {MemoryImage, 0x0};
         }
         Elf64_Phdr ItrPhdr;
         uintptr_t FirstProgramHeaderVirtualAddress = 0x0;
         bool FirstProgramHeader = false;
         for (Elf64_Half i = 0; i < ELFHeader->e_phnum; i++)
         {
             memcpy(&ItrPhdr,
                    (uint8_t *)ElfFile + ELFHeader->e_phoff + ELFHeader->e_phentsize * i,
                    sizeof(Elf64_Phdr));
             if (ItrPhdr.p_type == PT_LOAD && !FirstProgramHeader)
             {
                 FirstProgramHeaderVirtualAddress = ItrPhdr.p_vaddr;
                 FirstProgramHeader = true;
             }
             if (ItrPhdr.p_type == PT_LOAD && ItrPhdr.p_vaddr == 0)
             {
                 debug("p_vaddr is 0, allocating %ld pages for image (size: %#lx)", TO_PAGES(Length), Length);
                 MemoryImage = mem->RequestPages(TO_PAGES(Length), true);
                 debug("MemoryImage: %#lx-%#lx", MemoryImage, (uintptr_t)MemoryImage + Length);
                 memset(MemoryImage, 0, Length);
                 return {MemoryImage, (void *)FirstProgramHeaderVirtualAddress};
             }
         }
         debug("Allocating %ld pages for image (size: %#lx)", TO_PAGES(Length), Length);
         MemoryImage = mem->RequestPages(TO_PAGES(Length));
         debug("MemoryImage: %#lx-%#lx", MemoryImage, (uintptr_t)MemoryImage + Length);
         memset(MemoryImage, 0, Length);
         if (FirstProgramHeaderVirtualAddress != 0)
             FirstProgramHeaderVirtualAddress &= 0xFFFFFFFFFFFFF000;
         else
             FirstProgramHeaderVirtualAddress = (uintptr_t)MemoryImage;
         for (size_t i = 0; i < TO_PAGES(Length); i++)
         {
             pV.Remap((void *)((uintptr_t)FirstProgramHeaderVirtualAddress + (i * PAGE_SIZE)), (void *)((uintptr_t)MemoryImage + (i * PAGE_SIZE)), Memory::PTFlag::RW | Memory::PTFlag::US);
             debug("Remapped: %#lx -> %#lx", (uintptr_t)FirstProgramHeaderVirtualAddress + (i * PAGE_SIZE), (uintptr_t)MemoryImage + (i * PAGE_SIZE));
         }
         return {MemoryImage, (void *)FirstProgramHeaderVirtualAddress};
 #elif defined(a32)
         return {};
 #endif
     }
References debug, DT_TEXTREL, elf64_hdr::e_phentsize, elf64_hdr::e_phnum, elf64_hdr::e_phoff, elf64_hdr::e_type, ELFGetDynamicTag(), ET_DYN, fixme, Length, mem, memcpy(), memset(), Elf64_Phdr::p_type, Elf64_Phdr::p_vaddr, PT_LOAD, and UNUSED.
Referenced by AddLibrary(), and ELFLoadExec().
ELFGetDynamicTag()
Elf64_Dyn * Execute::ELFGetDynamicTag (void * ElfFile, enum DynamicArrayTags Tag)
Definition at line 141 of file Parse.cpp.
     {
 #if defined(a64)
         Elf64_Ehdr *ELFHeader = (Elf64_Ehdr *)ElfFile;
         Elf64_Phdr ItrPhdr;
         for (Elf64_Half i = 0; i < ELFHeader->e_phnum; i++)
         {
             memcpy(&ItrPhdr, (uint8_t *)ElfFile + ELFHeader->e_phoff + ELFHeader->e_phentsize * i, sizeof(Elf64_Phdr));
             if (ItrPhdr.p_type == PT_DYNAMIC)
             {
                 Elf64_Dyn *Dynamic = (Elf64_Dyn *)((uint8_t *)ElfFile + ItrPhdr.p_offset);
                 for (size_t i = 0; i < ItrPhdr.p_filesz / sizeof(Elf64_Dyn); i++)
                 {
                     if (Dynamic[i].d_tag == Tag)
                     {
                         debug("Found dynamic tag %d at %#lx [d_val: %#lx].", Tag, &Dynamic[i], Dynamic[i].d_un.d_val);
                         return &Dynamic[i];
                     }
                     if (Dynamic[i].d_tag == DT_NULL)
                     {
                         debug("Reached end of dynamic tag list for tag %d.", Tag);
                         return nullptr;
                     }
                 }
             }
         }
         debug("Dynamic tag %d not found.", Tag);
         return nullptr;
 #elif defined(a32)
         return nullptr;
 #endif
     }
References debug, DT_NULL, elf64_hdr::e_phentsize, elf64_hdr::e_phnum, elf64_hdr::e_phoff, memcpy(), Elf64_Phdr::p_filesz, Elf64_Phdr::p_offset, Elf64_Phdr::p_type, and PT_DYNAMIC.
Referenced by AddLibrary(), and ELFCreateMemoryImage().
ELFGetSymbolValue()
uintptr_t Execute::ELFGetSymbolValue (Elf64_Ehdr * Header, uint64_t Table, uint64_t Index)
Definition at line 93 of file Parse.cpp.
     {
 #if defined(a64)
         if (Table == SHN_UNDEF || Index == SHN_UNDEF)
             return 0;
         Elf64_Shdr *SymbolTable = GetELFSection(Header, Table);
         uint64_t STEntries = SymbolTable->sh_size / SymbolTable->sh_entsize;
         if (Index >= STEntries)
         {
             error("Symbol index out of range %d-%u.", Table, Index);
             return 0xdead;
         }
         uint64_t SymbolAddress = (uint64_t)Header + SymbolTable->sh_offset;
         Elf64_Sym *Symbol = &((Elf64_Sym *)SymbolAddress)[Index];
         if (Symbol->st_shndx == SHN_UNDEF)
         {
             Elf64_Shdr *StringTable = GetELFSection(Header, SymbolTable->sh_link);
             const char *Name = (const char *)Header + StringTable->sh_offset + Symbol->st_name;
             void *Target = (void *)ELFLookupSymbol(Header, Name)->st_value;
             if (Target == nullptr)
             {
                 if (ELF64_ST_BIND(Symbol->st_info) & STB_WEAK)
                     return 0;
                 else
                 {
                     error("Undefined external symbol \"%s\".", Name);
                     return 0xdead;
                 }
             }
             else
                 return (uintptr_t)Target;
         }
         else if (Symbol->st_shndx == SHN_ABS)
             return Symbol->st_value;
         else
         {
             Elf64_Shdr *Target = GetELFSection(Header, Symbol->st_shndx);
             return (uintptr_t)Header + Symbol->st_value + Target->sh_offset;
         }
 #elif defined(a32)
         return 0;
 #endif
     }
References ELF64_ST_BIND, ELFLookupSymbol(), error, GetELFSection(), CPU::Name(), elf64_shdr::sh_entsize, elf64_shdr::sh_link, elf64_shdr::sh_offset, elf64_shdr::sh_size, SHN_ABS, SHN_UNDEF, elf64_sym::st_value, and STB_WEAK.
Referenced by ELFLoadRel().
ELFInterpreterIPCThread()
void Execute::ELFInterpreterIPCThread (PCB * Process, char * Path, void * MemoryImage, void * ElfFile, std::vector< const char * > NeededLibraries)
Definition at line 51 of file BaseLoad.cpp.
     {
         debug("Interpreter thread started for %s", Path);
         // Interpreter will create an IPC with token "LOAD".
         char UniqueToken[16] = {'L', 'O', 'A', 'D', '\0'};
         InterProcessCommunication::IPCHandle *Handle = nullptr;
         while (Handle == nullptr)
         {
             debug("Searching for IPC with token %s", UniqueToken);
             Handle = Process->IPC->SearchByToken(UniqueToken);
             if (Handle == nullptr)
             {
                 debug("Failed");
             }
             TaskManager->Sleep(200);
             if (Handle == nullptr)
             {
                 debug("Retrying...");
             }
         }
         debug("IPC found, sending data...");
         InterpreterIPCData *TmpBuffer = new InterpreterIPCData;
         strcpy(TmpBuffer->Path, Path);
         TmpBuffer->ElfFile = ElfFile;
         TmpBuffer->MemoryImage = MemoryImage;
         if (NeededLibraries.size() > 256)
             warn("Too many libraries! (max 256)");
         for (size_t i = 0; i < NeededLibraries.size(); i++)
         {
             strcpy(TmpBuffer->Libraries[i].Name, NeededLibraries[i]);
         }
 #ifdef DEBUG
         debug("OUTSIDE DATA");
         debug("Path: %s", Path);
         debug("ElfFile: %p", ElfFile);
         debug("MemoryImage: %p", MemoryImage);
         for (size_t i = 0; i < NeededLibraries.size(); i++)
         {
             debug("Library: %s", NeededLibraries[i]);
         }
         debug("INSIDE DATA");
         debug("Path: %s", TmpBuffer->Path);
         debug("ElfFile: %p", TmpBuffer->ElfFile);
         debug("MemoryImage: %p", TmpBuffer->MemoryImage);
         for (size_t i = 0; i < NeededLibraries.size(); i++)
         {
             debug("Library: %s", TmpBuffer->Libraries[i].Name);
         }
 #endif
     RetryIPCWrite:
         InterProcessCommunication::IPCErrorCode ret = Process->IPC->Write(Handle->ID, TmpBuffer, sizeof(InterpreterIPCData));
         debug("Write returned %d", ret);
         if (ret == InterProcessCommunication::IPCErrorCode::IPCNotListening)
         {
             debug("IPC not listening, retrying...");
             TaskManager->Sleep(100);
             goto RetryIPCWrite;
         }
         delete TmpBuffer;
         /* Prevent race condition, maybe a
            better idea is to watch when the
            IPC is destroyed. */
         TaskManager->Sleep(5000);
         TEXIT(0);
     }
References debug, Execute::InterpreterIPCData::ElfFile, Tasking::PCB::IPC, InterProcessCommunication::IPCNotListening, Execute::InterpreterIPCData::Libraries, Execute::InterpreterIPCData::MemoryImage, Execute::InterpreterIPCDataLibrary::Name, Execute::InterpreterIPCData::Path, InterProcessCommunication::IPC::SearchByToken(), std::vector< T >::size(), Tasking::Task::Sleep(), strcpy, TaskManager, TEXIT, warn, and InterProcessCommunication::IPC::Write().
Referenced by ELFInterpreterThreadWrapper().
ELFInterpreterThreadWrapper()
void Execute::ELFInterpreterThreadWrapper ()
Definition at line 125 of file BaseLoad.cpp.
     {
         ELFInterpreterIPCThread(InterpreterTargetProcess, (char *)InterpreterTargetPath->c_str(), InterpreterMemoryImage, InterpreterElfFile, InterpreterNeededLibraries);
         delete InterpreterTargetPath, InterpreterTargetPath = nullptr;
     }
References std::string::c_str(), ELFInterpreterIPCThread(), InterpreterElfFile, InterpreterMemoryImage, InterpreterNeededLibraries, InterpreterTargetPath, and InterpreterTargetProcess.
Referenced by ELFLoad().
ELFLoad()
ELFBaseLoad Execute::ELFLoad (char * Path, const char ** argv, const char ** envp, Tasking::TaskCompatibility Compatibility)
Definition at line 131 of file BaseLoad.cpp.
     {
         /* We get the base name ("app.elf") */
         const char *BaseName;
         cwk_path_get_basename(Path, &BaseName, nullptr);
         TaskArchitecture Arch = TaskArchitecture::UnknownArchitecture;
         File ExFile = vfs->Open(Path);
         if (ExFile.Status != FileStatus::OK)
         {
             vfs->Close(ExFile);
             error("Failed to open file: %s", Path);
             return {};
         }
         else
         {
             if (ExFile.node->Flags != NodeFlags::FILE)
             {
                 vfs->Close(ExFile);
                 error("Invalid file path: %s", Path);
                 return {};
             }
             else if (GetBinaryType(Path) != BinaryType::BinTypeELF)
             {
                 vfs->Close(ExFile);
                 error("Invalid file type: %s", Path);
                 return {};
             }
         }
         size_t ExFileSize = ExFile.node->Length;
         /* Allocate elf in memory */
         void *ElfFile = KernelAllocator.RequestPages(TO_PAGES(ExFileSize + 1));
         /* Copy the file to the allocated memory */
         memcpy(ElfFile, (void *)ExFile.node->Address, ExFileSize);
         debug("Elf file: %#lx - %#lx (length: %ld)", ElfFile, (uintptr_t)ElfFile + ExFileSize, ExFileSize);
         Elf64_Ehdr *ELFHeader = (Elf64_Ehdr *)ElfFile;
         switch (ELFHeader->e_machine)
         {
         case EM_386:
             Arch = TaskArchitecture::x32;
             break;
         case EM_X86_64:
             Arch = TaskArchitecture::x64;
             break;
         case EM_ARM:
             Arch = TaskArchitecture::ARM32;
             break;
         case EM_AARCH64:
             Arch = TaskArchitecture::ARM64;
             break;
         default:
             break;
         }
         // TODO: This shouldn't be ignored
         if (ELFHeader->e_ident[EI_CLASS] == ELFCLASS32)
         {
             if (ELFHeader->e_ident[EI_DATA] == ELFDATA2LSB)
                 fixme("ELF32 LSB");
             else if (ELFHeader->e_ident[EI_DATA] == ELFDATA2MSB)
                 fixme("ELF32 MSB");
             else
                 fixme("ELF32 Unknown");
         }
         else if (ELFHeader->e_ident[EI_CLASS] == ELFCLASS64)
         {
             if (ELFHeader->e_ident[EI_DATA] == ELFDATA2LSB)
                 fixme("ELF64 LSB");
             else if (ELFHeader->e_ident[EI_DATA] == ELFDATA2MSB)
                 fixme("ELF64 MSB");
             else
                 fixme("ELF64 Unknown");
         }
         else
             fixme("Unknown ELF");
         /* ------------------------------------------------------------------------------------------------------------------------------ */
         PCB *Process = TaskManager->CreateProcess(TaskManager->GetCurrentProcess(), BaseName, TaskTrustLevel::User, ElfFile);
         Process->SetWorkingDirectory(vfs->GetNodeFromPath(Path)->Parent);
         Memory::Virtual pV = Memory::Virtual(Process->PageTable);
         for (size_t i = 0; i < TO_PAGES(ExFileSize); i++)
             pV.Remap((void *)((uintptr_t)ElfFile + (i * PAGE_SIZE)), (void *)((uintptr_t)ElfFile + (i * PAGE_SIZE)), Memory::PTFlag::RW | Memory::PTFlag::US);
         // for (size_t i = 0; i < TO_PAGES(ElfLazyResolverSize); i++)
         // pV.Remap((void *)((uintptr_t)ElfLazyResolver + (i * PAGE_SIZE)), (void *)((uintptr_t)ElfLazyResolver + (i * PAGE_SIZE)), Memory::PTFlag::RW | Memory::PTFlag::US);
         ELFBaseLoad bl;
         switch (ELFHeader->e_type)
         {
         case ET_REL:
             bl = ELFLoadRel(ElfFile, ExFile, Process);
             break;
         case ET_EXEC:
             bl = ELFLoadExec(ElfFile, ExFile, Process);
             break;
         case ET_DYN:
             bl = ELFLoadDyn(ElfFile, ExFile, Process);
             break;
         case ET_CORE:
         {
             fixme("ET_CORE not implemented");
             TaskManager->RevertProcessCreation(Process);
             vfs->Close(ExFile);
             return {};
         }
         case ET_NONE:
         default:
         {
             error("Unknown ELF Type: %d", ELFHeader->e_type);
             vfs->Close(ExFile);
             TaskManager->RevertProcessCreation(Process);
             return {};
         }
         }
         if (bl.Interpreter)
         {
             debug("ElfFile: %p ELFHeader: %p", ElfFile, ELFHeader);
             InterpreterTargetProcess = Process;
             InterpreterTargetPath = new std::string(Path); /* We store in a String because Path may get changed while outside ELFLoad(). */
             InterpreterMemoryImage = bl.VirtualMemoryImage;
             InterpreterElfFile = ElfFile;
             InterpreterNeededLibraries = bl.NeededLibraries;
             __sync;
             TCB *InterpreterIPCThread = TaskManager->CreateThread(TaskManager->GetCurrentProcess(), (IP)ELFInterpreterThreadWrapper);
             InterpreterIPCThread->Rename("ELF Interpreter IPC Thread");
             InterpreterIPCThread->SetPriority(TaskPriority::Low);
         }
         TCB *Thread = TaskManager->CreateThread(Process,
                                                 bl.InstructionPointer,
                                                 argv, envp, bl.auxv,
                                                 (IPOffset)0 /* ProgramHeader->p_offset */, // I guess I don't need this
                                                 Arch,
                                                 Compatibility);
         foreach (Memory::MemMgr::AllocatedPages p in bl.TmpMem->GetAllocatedPagesList())
         {
             Thread->Memory->Add(p.Address, p.PageCount);
             bl.TmpMem->DetachAddress(p.Address);
         }
         delete bl.TmpMem, bl.TmpMem = nullptr;
         bl.sd.Process = Process;
         bl.sd.Thread = Thread;
         bl.sd.Status = ExStatus::OK;
         vfs->Close(ExFile);
         return bl;
     }
References __sync, VirtualFileSystem::Node::Address, Tasking::ARM32, Tasking::ARM64, Execute::ELFBaseLoad::auxv, BinTypeELF, VirtualFileSystem::Virtual::Close(), Tasking::Task::CreateProcess(), Tasking::Task::CreateThread(), cwk_path_get_basename(), debug, elf64_hdr::e_ident, elf64_hdr::e_machine, elf64_hdr::e_type, EI_CLASS, EI_DATA, ELFCLASS32, ELFCLASS64, ELFDATA2LSB, ELFDATA2MSB, ELFInterpreterThreadWrapper(), ELFLoadDyn(), ELFLoadExec(), ELFLoadRel(), EM_386, EM_AARCH64, EM_ARM, EM_X86_64, error, ET_CORE, ET_DYN, ET_EXEC, ET_NONE, ET_REL, fixme, VirtualFileSystem::Node::Flags, GetBinaryType(), Tasking::Task::GetCurrentProcess(), VirtualFileSystem::Virtual::GetNodeFromPath(), Execute::ELFBaseLoad::InstructionPointer, Execute::ELFBaseLoad::Interpreter, InterpreterElfFile, InterpreterMemoryImage, InterpreterNeededLibraries, InterpreterTargetPath, InterpreterTargetProcess, KernelAllocator, VirtualFileSystem::Node::Length, Tasking::Low, memcpy(), Tasking::TCB::Memory, Execute::ELFBaseLoad::NeededLibraries, VirtualFileSystem::File::node, OK, VirtualFileSystem::Virtual::Open(), Tasking::PCB::PageTable, VirtualFileSystem::Node::Parent, Tasking::TCB::Rename(), Tasking::Task::RevertProcessCreation(), Tasking::TCB::SetPriority(), Tasking::PCB::SetWorkingDirectory(), VirtualFileSystem::File::Status, TaskManager, Tasking::UnknownArchitecture, Tasking::User, vfs, Execute::ELFBaseLoad::VirtualMemoryImage, Tasking::x32, and Tasking::x64.
Referenced by Spawn().
ELFLoadDyn()
ELFBaseLoad Execute::ELFLoadDyn (void * BaseImage, VirtualFileSystem::File & ExFile, Tasking::PCB * Process)
Definition at line 34 of file Dyn.cpp.
     {
         UNUSED(BaseImage);
         UNUSED(ExFile);
         UNUSED(Process);
         fixme("Not implemented");
         return {};
     }
References fixme, and UNUSED.
Referenced by ELFLoad().
ELFLoadExec()
ELFBaseLoad Execute::ELFLoadExec (void * ElfFile, VirtualFileSystem::File & ExFile, Tasking::PCB * Process)
Definition at line 34 of file Exec.cpp.
     {
 #if defined(a64)
         debug("Executable");
         ELFBaseLoad ELFBase = {};
         /* This should be deleted inside BaseLoad.cpp */
         ELFBase.TmpMem = new Memory::MemMgr(Process->PageTable);
         Elf64_Ehdr *ELFHeader = (Elf64_Ehdr *)ElfFile;
         Memory::Virtual pV(Process->PageTable);
         uintptr_t BaseAddress = UINTPTR_MAX;
         uint64_t ElfAppSize = 0;
         uintptr_t EntryPoint = ELFHeader->e_entry;
         debug("%s's entry point is %#lx", ExFile.Name, EntryPoint);
         Elf64_Phdr ItrPhdr;
         /* Get base address */
         for (Elf64_Half i = 0; i < ELFHeader->e_phnum; i++)
         {
             memcpy(&ItrPhdr,
                    (uint8_t *)ElfFile + ELFHeader->e_phoff + ELFHeader->e_phentsize * i,
                    sizeof(Elf64_Phdr));
             BaseAddress = MIN(BaseAddress, ItrPhdr.p_vaddr);
         }
         /* Get size */
         for (Elf64_Half i = 0; i < ELFHeader->e_phnum; i++)
         {
             memcpy(&ItrPhdr,
                    (uint8_t *)ElfFile + ELFHeader->e_phoff + ELFHeader->e_phentsize * i,
                    sizeof(Elf64_Phdr));
             uintptr_t SegmentEnd;
             SegmentEnd = ItrPhdr.p_vaddr - BaseAddress + ItrPhdr.p_memsz;
             ElfAppSize = MAX(ElfAppSize, SegmentEnd);
         }
         debug("BaseAddress: %#lx | ElfAppSize: %#lx (%ld, %ld KB)", BaseAddress, ElfAppSize, ElfAppSize, TO_KB(ElfAppSize));
         /* If required, MemoryImage will be at virtual address. (unless has PIE)
          *
          * tl;dr this is where the code is stored. */
         MmImage MemoryImage = ELFCreateMemoryImage(ELFBase.TmpMem, pV, ElfFile, ElfAppSize);
         debug("Solving symbols for address: %#llx", (uintptr_t)ElfFile);
         Elf64_Shdr *ElfSections = (Elf64_Shdr *)((uintptr_t)ElfFile + ELFHeader->e_shoff);
         Elf64_Shdr *DynamicString = nullptr;
         Elf64_Shdr *StringTable = nullptr;
         for (Elf64_Half i = 0; i < ELFHeader->e_shnum; i++)
         {
             char *DynamicStringTable = (char *)((uintptr_t)ElfFile + ElfSections[ELFHeader->e_shstrndx].sh_offset + ElfSections[i].sh_name);
             if (strcmp(DynamicStringTable, ".dynstr") == 0)
             {
                 DynamicString = &ElfSections[i];
                 debug("Found .dynstr");
             }
             else if (strcmp(DynamicStringTable, ".strtab") == 0)
             {
                 StringTable = &ElfSections[i];
                 debug("Found .strtab");
             }
         }
         if (!DynamicString)
             DynamicString = StringTable;
         /* Calculate entry point */
         memcpy(&ItrPhdr, (uint8_t *)ElfFile + ELFHeader->e_phoff, sizeof(Elf64_Phdr));
         if (ItrPhdr.p_vaddr == 0)
             EntryPoint += (uintptr_t)MemoryImage.Virtual;
         char InterpreterPath[256] = {'\0'};
         for (Elf64_Half i = 0; i < ELFHeader->e_phnum; i++)
         {
             memcpy(&ItrPhdr,
                    (uint8_t *)ElfFile + ELFHeader->e_phoff + ELFHeader->e_phentsize * i,
                    sizeof(Elf64_Phdr));
             switch (ItrPhdr.p_type)
             {
             case PT_NULL:
                 fixme("PT_NULL");
                 break;
             case PT_LOAD:
             {
                 debug("PT_LOAD - Offset: %#lx, VirtAddr: %#lx, FileSiz: %ld, MemSiz: %ld, Align: %#lx",
                       ItrPhdr.p_offset, ItrPhdr.p_vaddr,
                       ItrPhdr.p_filesz, ItrPhdr.p_memsz, ItrPhdr.p_align);
                 uintptr_t MAddr = (ItrPhdr.p_vaddr - BaseAddress) + (uintptr_t)MemoryImage.Physical;
                 fixme("Address: %#lx %s%s%s", MAddr,
                       (ItrPhdr.p_flags & PF_R) ? "R" : "",
                       (ItrPhdr.p_flags & PF_W) ? "W" : "",
                       (ItrPhdr.p_flags & PF_X) ? "X" : "");
                 memcpy((void *)MAddr, (uint8_t *)ElfFile + ItrPhdr.p_offset, ItrPhdr.p_filesz);
                 debug("memcpy: %#lx => %#lx (%ld bytes)", (uint8_t *)ElfFile + ItrPhdr.p_offset, MAddr, ItrPhdr.p_filesz);
                 break;
             }
             case PT_DYNAMIC:
             {
                 debug("PT_DYNAMIC - Offset: %#lx VirtAddr: %#lx FileSiz: %ld MemSiz: %ld Align: %#lx",
                       ItrPhdr.p_offset, ItrPhdr.p_vaddr,
                       ItrPhdr.p_filesz, ItrPhdr.p_memsz, ItrPhdr.p_align);
                 Elf64_Dyn *Dynamic = (Elf64_Dyn *)((uint8_t *)ElfFile + ItrPhdr.p_offset);
                 for (size_t i = 0; i < ItrPhdr.p_filesz / sizeof(Elf64_Dyn); i++)
                 {
                     if (Dynamic[i].d_tag == DT_NEEDED)
                     {
                         if (!DynamicString)
{
                             error("DynamicString is null");
                             break;
                         }
                         const char *ReqLib = (const char *)((uintptr_t)ElfFile + DynamicString->sh_offset + Dynamic[i].d_un.d_val);
                         debug("DT_NEEDED - Name[%ld]: %s", i, ReqLib);
                         ELFBase.NeededLibraries.push_back(ReqLib);
                     }
                     else if (Dynamic[i].d_tag == DT_NULL)
                         break;
                 }
                 break;
             }
             case PT_INTERP:
             {
                 debug("PT_INTERP - Offset: %#lx VirtAddr: %#lx FileSiz: %ld MemSiz: %ld Align: %#lx",
                       ItrPhdr.p_offset, ItrPhdr.p_vaddr,
                       ItrPhdr.p_filesz, ItrPhdr.p_memsz, ItrPhdr.p_align);
                 memcpy((void *)InterpreterPath, (uint8_t *)ElfFile + ItrPhdr.p_offset, 256);
                 debug("Interpreter: %s", InterpreterPath);
                 VirtualFileSystem::File InterpreterFile = vfs->Open(InterpreterPath);
                 if (!InterpreterFile.IsOK())
                     warn("Failed to open interpreter file: %s", InterpreterPath);
                 vfs->Close(InterpreterFile);
                 break;
             }
             /* ... */
             case PT_PHDR:
             {
                 fixme("PT_PHDR - Offset: %#lx VirtAddr: %#lx FileSiz: %ld MemSiz: %ld Align: %#lx",
                       ItrPhdr.p_offset, ItrPhdr.p_vaddr,
                       ItrPhdr.p_filesz, ItrPhdr.p_memsz, ItrPhdr.p_align);
                 break;
             }
             default:
             {
                 warn("Unknown or unsupported program header type: %d", ItrPhdr.p_type);
                 break;
             }
             }
         }
         if (strlen(InterpreterPath) > 1)
         {
             EntryPoint = LoadELFInterpreter(ELFBase.TmpMem, pV, InterpreterPath);
             ELFBase.Interpreter = true;
         }
         debug("Entry Point: %#lx", EntryPoint);
         char *aux_platform = (char *)ELFBase.TmpMem->RequestPages(1, true);
         strcpy(aux_platform, "x86_64");
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_NULL, .a_un = {.a_val = 0}}});
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_EXECFN, .a_un = {.a_val = (uint64_t)vfs->GetPathFromNode(ExFile.node).get()}}});
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_PLATFORM, .a_un = {.a_val = (uint64_t)aux_platform}}});
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_ENTRY, .a_un = {.a_val = (uint64_t)EntryPoint}}});
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_BASE, .a_un = {.a_val = (uint64_t)MemoryImage.Virtual}}});
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_PAGESZ, .a_un = {.a_val = (uint64_t)PAGE_SIZE}}});
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_PHNUM, .a_un = {.a_val = (uint64_t)ELFHeader->e_phnum}}});
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_PHENT, .a_un = {.a_val = (uint64_t)ELFHeader->e_phentsize}}});
         ELFBase.auxv.push_back({.archaux = {.a_type = AT_PHDR, .a_un = {.a_val = (uint64_t)ELFHeader->e_phoff}}});
         ELFBase.InstructionPointer = EntryPoint;
         ELFBase.MemoryImage = MemoryImage.Physical;
         ELFBase.VirtualMemoryImage = MemoryImage.Virtual;
         ELFBase.Success = true;
         return ELFBase;
 #elif defined(a32)
         return {};
 #endif
     }
References debug, elf64_hdr::e_entry, elf64_hdr::e_phentsize, elf64_hdr::e_phnum, elf64_hdr::e_phoff, elf64_hdr::e_shnum, elf64_hdr::e_shoff, elf64_hdr::e_shstrndx, ELFCreateMemoryImage(), EntryPoint, MAX, memcpy(), MIN, VirtualFileSystem::File::Name, Elf64_Phdr::p_memsz, Elf64_Phdr::p_vaddr, Tasking::PCB::PageTable, elf64_shdr::sh_name, elf64_shdr::sh_offset, strcmp(), Execute::ELFBaseLoad::TmpMem, UINTPTR_MAX, and Execute::MmImage::Virtual.
Referenced by ELFLoad().
ELFLoadRel()
ELFBaseLoad Execute::ELFLoadRel (void * BaseImage, VirtualFileSystem::File & ExFile, Tasking::PCB * Process)
Definition at line 29 of file Rel.cpp.
     {
 #if defined(a64)
         UNUSED(ExFile);
         debug("Relocatable");
         /* TODO: I have to fully implement this, but for now I will leave it as it is now. */
         warn("Relocatable ELF is not fully supported yet");
         /* This should be deleted after with kfree */
         ELFBaseLoad ELFBase = {};
         /* This should be deleted inside BaseLoad.cpp */
         ELFBase.TmpMem = new Memory::MemMgr(Process->PageTable);
         Elf64_Shdr *shdr = GetELFSheader(((Elf64_Ehdr *)BaseImage));
         for (Elf64_Half i = 0; i < ((Elf64_Ehdr *)BaseImage)->e_shnum; i++)
         {
             Elf64_Shdr *Section = &shdr[i];
             if (Section->sh_type == SHT_NOBITS)
             {
                 if (!Section->sh_size)
                     continue;
                 if (Section->sh_flags & SHF_ALLOC)
                 {
                     void *Buffer = KernelAllocator.RequestPages(TO_PAGES(Section->sh_size + 1));
                     memset(Buffer, 0, Section->sh_size);
                     Memory::Virtual(Process->PageTable).Map((void *)Buffer, (void *)Buffer, Section->sh_size, Memory::PTFlag::RW | Memory::PTFlag::US);
                     Section->sh_offset = (uintptr_t)Buffer - (uintptr_t)BaseImage;
                     debug("Section %ld", Section->sh_size);
                 }
             }
         }
         for (Elf64_Half i = 0; i < ((Elf64_Ehdr *)BaseImage)->e_shnum; i++)
         {
             Elf64_Shdr *Section = &shdr[i];
             if (Section->sh_type == SHT_REL)
             {
                 for (size_t Index = 0; Index < Section->sh_size / Section->sh_entsize; Index++)
                 {
                     Elf64_Rel *RelTable = &((Elf64_Rel *)((uintptr_t)BaseImage + Section->sh_offset))[Index];
                     Elf64_Shdr *Target = GetELFSection(((Elf64_Ehdr *)BaseImage), Section->sh_info);
                     uintptr_t *RelAddress = (uintptr_t *)(((uintptr_t)BaseImage + Target->sh_offset) + RelTable->r_offset);
                     uint64_t SymbolValue = 0;
                     if (ELF64_R_SYM(RelTable->r_info) != SHN_UNDEF)
                     {
                         SymbolValue = ELFGetSymbolValue(((Elf64_Ehdr *)BaseImage), Section->sh_link, ELF64_R_SYM(RelTable->r_info));
                         if (SymbolValue == 0xdead)
{
                             delete ELFBase.TmpMem, ELFBase.TmpMem = nullptr;
                             return {};
                         }
                     }
                     switch (ELF64_R_TYPE(RelTable->r_info))
                     {
                     case R_386_NONE:
                         break;
                     case R_386_32:
                         *RelAddress = DO_64_64(SymbolValue, *RelAddress);
                         break;
                     case R_386_PC32:
                         *RelAddress = DO_64_PC32(SymbolValue, *RelAddress, (uintptr_t)RelAddress);
                         break;
                     default:
                     {
                         error("Unsupported relocation type: %d", ELF64_R_TYPE(RelTable->r_info));
                         delete ELFBase.TmpMem, ELFBase.TmpMem = nullptr;
                         return {};
                     }
                     }
                     debug("Symbol value: %#lx", SymbolValue);
                 }
             }
         }
         return ELFBase;
 #elif defined(a32)
         return {};
 #endif
     }
References debug, DO_64_64, DO_64_PC32, ELF64_R_SYM, ELF64_R_TYPE, ELFGetSymbolValue(), error, GetELFSection(), GetELFSheader(), KernelAllocator, memset(), Tasking::PCB::PageTable, R_386_32, R_386_NONE, R_386_PC32, elf64_rel::r_info, elf64_rel::r_offset, elf64_shdr::sh_entsize, elf64_shdr::sh_flags, elf64_shdr::sh_info, elf64_shdr::sh_link, elf64_shdr::sh_offset, elf64_shdr::sh_size, elf64_shdr::sh_type, SHF_ALLOC, SHN_UNDEF, SHT_NOBITS, SHT_REL, Execute::ELFBaseLoad::TmpMem, UNUSED, and warn.
Referenced by ELFLoad().
ELFLookupString()
char * Execute::ELFLookupString (Elf64_Ehdr * Header, uintptr_t Offset)
Definition at line 46 of file Parse.cpp.
     {
         char *StringTable = GetELFStringTable(Header);
         if (StringTable == nullptr)
             return nullptr;
         return StringTable + Offset;
     }
References GetELFStringTable().
ELFLookupSymbol()
Elf64_Sym * Execute::ELFLookupSymbol (Elf64_Ehdr * Header, const char * Name)
Definition at line 54 of file Parse.cpp.
     {
 #if defined(a64)
         Elf64_Shdr *SymbolTable = nullptr;
         Elf64_Shdr *StringTable = nullptr;
         Elf64_Sym *Symbol = nullptr;
         char *String = nullptr;
         for (Elf64_Half i = 0; i < Header->e_shnum; i++)
         {
             Elf64_Shdr *shdr = GetELFSection(Header, i);
             switch (shdr->sh_type)
             {
             case SHT_SYMTAB:
                 SymbolTable = shdr;
                 StringTable = GetELFSection(Header, shdr->sh_link);
                 break;
             default:
             {
                 break;
             }
             }
         }
         if (SymbolTable == nullptr || StringTable == nullptr)
             return nullptr;
         for (size_t i = 0; i < (SymbolTable->sh_size / sizeof(Elf64_Sym)); i++)
         {
             Symbol = (Elf64_Sym *)((uintptr_t)Header + SymbolTable->sh_offset + (i * sizeof(Elf64_Sym)));
             String = (char *)((uintptr_t)Header + StringTable->sh_offset + Symbol->st_name);
             if (strcmp(String, Name) == 0)
                 return Symbol;
         }
 #elif defined(a32)
 #endif
         return nullptr;
     }
References elf64_hdr::e_shnum, GetELFSection(), CPU::Name(), elf64_shdr::sh_link, elf64_shdr::sh_offset, elf64_shdr::sh_size, elf64_shdr::sh_type, SHT_SYMTAB, elf64_sym::st_name, and strcmp().
Referenced by AddLibrary(), and ELFGetSymbolValue().
FEXLoad()
void Execute::FEXLoad ()
Definition at line 34 of file BaseLoad.cpp.
     {
     }
GetBinaryType() [1/2]
BinaryType Execute::GetBinaryType (char * Path)
Definition at line 88 of file Parse.cpp.
     {
         BinaryType Type = BinaryType::BinTypeInvalid;
         VirtualFileSystem::File ExFile = vfs->Open(Path);
         if (ExFile.IsOK())
         {
             debug("File opened: %s", Path);
             Type = GetBinaryType((void *)ExFile.node->Address);
         }
         vfs->Close(ExFile);
         return Type;
     }
References VirtualFileSystem::Node::Address, BinTypeInvalid, VirtualFileSystem::Virtual::Close(), debug, GetBinaryType(), VirtualFileSystem::File::IsOK(), VirtualFileSystem::File::node, VirtualFileSystem::Virtual::Open(), Type, and vfs.
GetBinaryType() [2/2]
BinaryType Execute::GetBinaryType (void * Image)
Definition at line 27 of file Parse.cpp.
     {
         Fex *FexHdr = (Fex *)Image;
         /* Elf64_Ehdr and Elf32_Ehdr are very similar (Elf64_Half and
            Elf32_Half are the same size type) so we can use directly Elf64_Ehdr. */
         Elf64_Ehdr *ELFHeader = (Elf64_Ehdr *)Image;
         IMAGE_DOS_HEADER *MZHeader = (IMAGE_DOS_HEADER *)Image;
         /* Check Fex magic */
         if (FexHdr->Magic[0] == 'F' && FexHdr->Magic[1] == 'E' && FexHdr->Magic[2] == 'X' && FexHdr->Magic[3] == '\0')
         {
             /* If the fex type is driver, we shouldn't return as Fex. */
             if (FexHdr->Type == FexFormatType::FexFormatType_Executable)
             {
                 debug("Image - Fex");
                 return BinaryType::BinTypeFex;
             }
             else if (FexHdr->Type == FexFormatType::FexFormatType_Driver)
             {
                 debug("Fex Driver is not supposed to be executed.");
             }
         }
         /* Check ELF magic. */
         else if (ELFHeader->e_ident[EI_MAG0] == ELFMAG0 &&
                  ELFHeader->e_ident[EI_MAG1] == ELFMAG1 &&
                  ELFHeader->e_ident[EI_MAG2] == ELFMAG2 &&
                  ELFHeader->e_ident[EI_MAG3] == ELFMAG3)
         {
             debug("Image - ELF");
             return BinaryType::BinTypeELF;
         }
         /* Every Windows executable starts with MZ header. */
         else if (MZHeader->e_magic == IMAGE_DOS_SIGNATURE)
         {
             IMAGE_NT_HEADERS *PEHeader = (IMAGE_NT_HEADERS *)(((char *)Image) + MZHeader->e_lfanew);
             IMAGE_OS2_HEADER *NEHeader = (IMAGE_OS2_HEADER *)(((char *)Image) + MZHeader->e_lfanew);
             /* TODO: LE, EDOS */
             if (PEHeader->Signature == IMAGE_NT_SIGNATURE)
             {
                 debug("Image - PE");
                 return BinaryType::BinTypePE;
             }
             else if (NEHeader->ne_magic == IMAGE_OS2_SIGNATURE)
             {
                 debug("Image - NE");
                 return BinaryType::BinTypeNE;
             }
             else
             {
                 debug("Image - MZ");
                 return BinaryType::BinTypeMZ;
             }
         }
         /* ... */
         return BinaryType::BinTypeUnknown;
     }
References BinTypeELF, BinTypeFex, BinTypeMZ, BinTypeNE, BinTypePE, BinTypeUnknown, debug, elf64_hdr::e_ident, _IMAGE_DOS_HEADER::e_lfanew, _IMAGE_DOS_HEADER::e_magic, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, ELFMAG0, ELFMAG1, ELFMAG2, ELFMAG3, FexFormatType_Driver, FexFormatType_Executable, IMAGE_DOS_SIGNATURE, IMAGE_NT_SIGNATURE, IMAGE_OS2_SIGNATURE, Fex::Magic, _IMAGE_OS2_HEADER::ne_magic, _IMAGE_NT_HEADERS::Signature, and Fex::Type.
Referenced by ELFLoad(), GetBinaryType(), LoadELFInterpreter(), and Spawn().
GetELFSection()
Elf64_Shdr * Execute::GetELFSection (Elf64_Ehdr * Header, uint64_t Index)
Definition at line 34 of file Parse.cpp.
     {
         return &GetELFSheader(Header)[Index];
     }
References GetELFSheader().
Referenced by ELFGetSymbolValue(), ELFLoadRel(), ELFLookupSymbol(), and GetELFStringTable().
GetELFSheader()
Elf64_Shdr * Execute::GetELFSheader (Elf64_Ehdr * Header)
Definition at line 29 of file Parse.cpp.
     {
         return (Elf64_Shdr *)((uintptr_t)Header + Header->e_shoff);
     }
References elf64_hdr::e_shoff.
Referenced by ELFLoadRel(), and GetELFSection().
GetELFStringTable()
char * Execute::GetELFStringTable (Elf64_Ehdr * Header)
Definition at line 39 of file Parse.cpp.
     {
         if (Header->e_shstrndx == SHN_UNDEF)
             return nullptr;
         return (char *)Header + GetELFSection(Header, Header->e_shstrndx)->sh_offset;
     }
References elf64_hdr::e_shstrndx, GetELFSection(), elf64_shdr::sh_offset, and SHN_UNDEF.
Referenced by ELFLookupString().
GetLibrary()
SharedLibraries Execute::GetLibrary (char * Identifier)
Definition at line 248 of file SharedObjects.cpp.
     {
         SmartLock(ExecuteServiceLock);
         foreach (auto Lib in Libs)
         {
             if (strcmp(Lib.Identifier, Identifier) == 0)
             {
                 Lib.RefCount++;
                 debug("Library %s found (%#lx %#lx)", Identifier, Lib.Address, Lib.MemoryImage);
                 return Lib;
             }
         }
         // throw std::runtime_error("Library not found");
         return SharedLibraries();
     }
References debug, Libs, and strcmp().
Referenced by sys_kernelctl().
LoadELFInterpreter()
uintptr_t Execute::LoadELFInterpreter (Memory::MemMgr * mem, Memory::Virtual & pV, const char * Interpreter)
Definition at line 242 of file Parse.cpp.
     {
         if (GetBinaryType((char *)Interpreter) != BinaryType::BinTypeELF)
         {
             error("Interpreter \"%s\" is not an ELF file.", Interpreter);
             return 0;
         }
         /* No need to check if it's valid, the GetBinaryType() call above does that. */
         VirtualFileSystem::File File = vfs->Open(Interpreter);
 #if defined(a64)
         Elf64_Ehdr *ELFHeader = (Elf64_Ehdr *)File.node->Address;
 #ifdef DEBUG
         const char *InterpreterType[6] = {
             "ET_NONE",
             "ET_REL",
             "ET_EXEC",
             "ET_DYN",
             "ET_CORE",
             "ET_LOPROC - ET_HIPROC"};
         Elf64_Half IntType = ELFHeader->e_type;
         if (IntType > 5)
             IntType = 5;
         debug("Interpreter type: %s - %#x", InterpreterType[IntType], ELFHeader->e_type);
 #endif
         uintptr_t BaseAddress = UINTPTR_MAX;
         uint64_t ElfAppSize = 0;
         Elf64_Phdr ItrPhdr;
         /* Get base address */
         for (Elf64_Half i = 0; i < ELFHeader->e_phnum; i++)
         {
             memcpy(&ItrPhdr,
                    (uint8_t *)File.node->Address + ELFHeader->e_phoff + ELFHeader->e_phentsize * i,
                    sizeof(Elf64_Phdr));
             BaseAddress = MIN(BaseAddress, ItrPhdr.p_vaddr);
         }
         /* Get size */
         for (Elf64_Half i = 0; i < ELFHeader->e_phnum; i++)
         {
             memcpy(&ItrPhdr,
                    (uint8_t *)File.node->Address + ELFHeader->e_phoff + ELFHeader->e_phentsize * i,
                    sizeof(Elf64_Phdr));
             uintptr_t SegmentEnd;
             SegmentEnd = ItrPhdr.p_vaddr - BaseAddress + ItrPhdr.p_memsz;
             ElfAppSize = MAX(ElfAppSize, SegmentEnd);
         }
         MmImage MemoryImage = ELFCreateMemoryImage(mem, pV, (void *)File.node->Address, ElfAppSize);
         for (Elf64_Half i = 0; i < ELFHeader->e_phnum; i++)
         {
             memcpy(&ItrPhdr,
                    (uint8_t *)File.node->Address + ELFHeader->e_phoff + ELFHeader->e_phentsize * i,
                    sizeof(Elf64_Phdr));
             if (ItrPhdr.p_type == PT_LOAD)
             {
                 debug("PT_LOAD - Offset: %#lx, VirtAddr: %#lx, FileSiz: %ld, MemSiz: %ld, Align: %#lx",
                       ItrPhdr.p_offset, ItrPhdr.p_vaddr,
                       ItrPhdr.p_filesz, ItrPhdr.p_memsz, ItrPhdr.p_align);
                 uintptr_t MAddr = (ItrPhdr.p_vaddr - BaseAddress) + (uintptr_t)MemoryImage.Physical;
                 fixme("Address: %#lx %s%s%s", MAddr,
                       (ItrPhdr.p_flags & PF_R) ? "R" : "",
                       (ItrPhdr.p_flags & PF_W) ? "W" : "",
                       (ItrPhdr.p_flags & PF_X) ? "X" : "");
                 memcpy((void *)MAddr, (uint8_t *)File.node->Address + ItrPhdr.p_offset, ItrPhdr.p_filesz);
                 debug("memcpy: %#lx => %#lx (%ld bytes)", (uint8_t *)File.node->Address + ItrPhdr.p_offset, MAddr, ItrPhdr.p_filesz);
             }
         }
         vfs->Close(File);
         debug("Interpreter entry point: %#lx (%#lx + %#lx)", (uintptr_t)MemoryImage.Physical + ELFHeader->e_entry,
               (uintptr_t)MemoryImage.Physical, ELFHeader->e_entry);
         return (uintptr_t)MemoryImage.Physical + ELFHeader->e_entry;
 #elif defined(a32)
         vfs->Close(File);
         return 0;
 #endif
     }
References VirtualFileSystem::Node::Address, BinTypeELF, error, GetBinaryType(), VirtualFileSystem::File::node, VirtualFileSystem::Virtual::Open(), and vfs.
SearchLibrary()
void Execute::SearchLibrary (char * Identifier)
Definition at line 242 of file SharedObjects.cpp.
     {
         UNUSED(Identifier);
         SmartLock(ExecuteServiceLock);
     }
References UNUSED.
Spawn()
SpawnData Execute::Spawn (char * Path, const char ** argv, const char ** envp)
Definition at line 34 of file Spawn.cpp.
     {
         SpawnData ret = {.Status = ExStatus::Unknown,
                          .Process = nullptr,
                          .Thread = nullptr};
         VirtualFileSystem::File ExFile = vfs->Open(Path);
         if (ExFile.IsOK())
         {
             if (ExFile.node->Flags != VirtualFileSystem::NodeFlags::FILE)
             {
                 ret.Status = ExStatus::InvalidFilePath;
                 goto Exit;
             }
             switch (GetBinaryType(Path))
             {
             case BinaryType::BinTypeFex:
             {
                 Fex *FexHdr = (Fex *)ExFile.node->Address;
                 if (FexHdr->Type == FexFormatType::FexFormatType_Executable)
                 {
                     const char *BaseName;
                     cwk_path_get_basename(Path, &BaseName, nullptr);
                     PCB *Process = TaskManager->CreateProcess(TaskManager->GetCurrentProcess(), BaseName, TaskTrustLevel::User);
                     void *BaseImage = KernelAllocator.RequestPages(TO_PAGES(ExFile.node->Length + 1));
                     memcpy(BaseImage, (void *)ExFile.node->Address, ExFile.node->Length);
                     Memory::Virtual(Process->PageTable).Map((void *)BaseImage, (void *)BaseImage, ExFile.node->Length, Memory::PTFlag::RW | Memory::PTFlag::US);
                     std::vector<AuxiliaryVector> auxv; // TODO!
                     TCB *Thread = TaskManager->CreateThread(Process,
                                                             (IP)FexHdr->EntryPoint,
                                                             argv, envp, auxv,
                                                             (IPOffset)BaseImage,
                                                             TaskArchitecture::x64,
                                                             TaskCompatibility::Native);
                     ret.Process = Process;
                     ret.Thread = Thread;
                     ret.Status = ExStatus::OK;
                 }
                 ret.Status = ExStatus::InvalidFileHeader;
                 goto Exit;
             }
             case BinaryType::BinTypeELF:
             {
                 ELFBaseLoad bl = ELFLoad(Path, argv, envp);
                 if (!bl.Success)
                 {
                     ret.Status = ExStatus::GenericError;
                     goto Exit;
                 }
                 ret = bl.sd;
                 goto Exit;
             }
             default:
             {
                 ret.Status = ExStatus::Unsupported;
                 goto Exit;
             }
             }
         }
         else if (ExFile.Status == VirtualFileSystem::FileStatus::NotFound)
             ret.Status = ExStatus::InvalidFilePath;
         else
             ret.Status = ExStatus::InvalidFile;
     Exit:
         vfs->Close(ExFile);
         return ret;
     }
References VirtualFileSystem::Node::Address, BinTypeELF, BinTypeFex, VirtualFileSystem::Virtual::Close(), Tasking::Task::CreateProcess(), Tasking::Task::CreateThread(), cwk_path_get_basename(), ELFLoad(), Fex::EntryPoint, FexFormatType_Executable, VirtualFileSystem::Node::Flags, GenericError, GetBinaryType(), Tasking::Task::GetCurrentProcess(), if(), InvalidFile, InvalidFileHeader, InvalidFilePath, VirtualFileSystem::File::IsOK(), KernelAllocator, VirtualFileSystem::Node::Length, memcpy(), Tasking::Native, VirtualFileSystem::File::node, VirtualFileSystem::NotFound, OK, VirtualFileSystem::Virtual::Open(), Tasking::PCB::PageTable, Execute::SpawnData::Process, Execute::ELFBaseLoad::sd, Execute::SpawnData::Status, VirtualFileSystem::File::Status, Execute::ELFBaseLoad::Success, TaskManager, Execute::SpawnData::Thread, Fex::Type, Unknown, Unsupported, Tasking::User, vfs, and Tasking::x64.
Referenced by SpawnInit().
StartExecuteService()
void Execute::StartExecuteService ()
Definition at line 43 of file SharedObjects.cpp.
     {
         mem = new Memory::MemMgr;
         while (true)
         {
             {
                 SmartLock(ExecuteServiceLock);
                 foreach (auto &Lib in Libs)
                 {
                     if (Lib.RefCount > 0)
                     {
                         Lib.Timeout = TimeManager->CalculateTarget(10, Time::Units::Minutes);
                         debug("Reset timeout for %s", Lib.Identifier);
                         continue;
                     }
                     if (Lib.Timeout < TimeManager->GetCounter())
                     {
                         // TODO: Remove
                         fixme("Removed library %s because of timeout", Lib.Identifier);
                     }
                     else
                     {
                         debug("Timeout for %s is %ld", Lib.Identifier, Lib.Timeout);
                     }
                 }
                 debug("Waiting 10 seconds...");
             }
             TaskManager->Sleep(10000);
         }
     }
References Time::time::CalculateTarget(), debug, fixme, Time::time::GetCounter(), Libs, mem, Time::Minutes, Tasking::Task::Sleep(), TaskManager, and TimeManager.
Referenced by KernelMainThread().
Variable Documentation
InterpreterElfFile
void* Execute::InterpreterElfFile
Definition at line 123 of file BaseLoad.cpp.
Referenced by ELFInterpreterThreadWrapper(), and ELFLoad().
InterpreterMemoryImage
void* Execute::InterpreterMemoryImage
Definition at line 122 of file BaseLoad.cpp.
Referenced by ELFInterpreterThreadWrapper(), and ELFLoad().
InterpreterNeededLibraries
std::vector<const char *> Execute::InterpreterNeededLibraries
Definition at line 124 of file BaseLoad.cpp.
Referenced by ELFInterpreterThreadWrapper(), and ELFLoad().
InterpreterTargetPath
std::string* Execute::InterpreterTargetPath
Definition at line 121 of file BaseLoad.cpp.
Referenced by ELFInterpreterThreadWrapper(), and ELFLoad().
InterpreterTargetProcess
PCB* Execute::InterpreterTargetProcess
Definition at line 120 of file BaseLoad.cpp.
Referenced by ELFInterpreterThreadWrapper(), and ELFLoad().
Libs
std::vector<SharedLibraries> Execute::Libs
Definition at line 41 of file SharedObjects.cpp.
Referenced by AddLibrary(), GetLibrary(), and StartExecuteService().
mem
Memory::MemMgr* Execute::mem = nullptr
Definition at line 40 of file SharedObjects.cpp.
Referenced by AddLibrary(), Driver::Driver::BindInputAudio(), Driver::Driver::BindInputDisplay(), Driver::Driver::BindInputFileSystem(), Driver::Driver::BindInputGeneric(), Driver::Driver::BindInputInput(), Driver::Driver::BindInputNetwork(), Driver::Driver::BindInputStorage(), Driver::Driver::BindInterruptAudio(), Driver::Driver::BindInterruptDisplay(), Driver::Driver::BindInterruptFileSystem(), Driver::Driver::BindInterruptGeneric(), Driver::Driver::BindInterruptInput(), Driver::Driver::BindInterruptNetwork(), Driver::Driver::BindInterruptStorage(), Driver::Driver::BindPCIAudio(), Driver::Driver::BindPCIDisplay(), Driver::Driver::BindPCIFileSystem(), Driver::Driver::BindPCIGeneric(), Driver::Driver::BindPCIInput(), Driver::Driver::BindPCINetwork(), Driver::Driver::BindPCIStorage(), Driver::Driver::BindProcessAudio(), Driver::Driver::BindProcessDisplay(), Driver::Driver::BindProcessFileSystem(), Driver::Driver::BindProcessGeneric(), Driver::Driver::BindProcessInput(), Driver::Driver::BindProcessNetwork(), Driver::Driver::BindProcessStorage(), Driver::Driver::DriverLoadBindInput(), Driver::Driver::DriverLoadBindInterrupt(), Driver::Driver::DriverLoadBindPCI(), ELFCreateMemoryImage(), and StartExecuteService().