Fennix: Userspace/musl/src/network/lookup.h File Reference
lookup.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <features.h>
#include <netinet/in.h>
#include <netdb.h>
Data Structures
struct aibuf
union aibuf::sa
struct address
struct service
struct resolvconf
Macros
#define MAXNS 3
#define MAXADDRS 48
#define MAXSERVS 2
Functions
hidden int __lookup_serv (struct service buf[static MAXSERVS], const char *name, int proto, int socktype, int flags)
hidden int __lookup_name (struct address buf[static MAXADDRS], char canon[static 256], const char *name, int family, int flags)
hidden int __lookup_ipliteral (struct address buf[static 1], const char *name, int family)
hidden int __get_resolv_conf (struct resolvconf *, char *, size_t)
hidden int __res_msend_rc (int, const unsigned char *const *, const int *, unsigned char *const *, int *, int, const struct resolvconf *)
hidden int __dns_parse (const unsigned char *, int, int(*)(void *, int, const void *, int, const void *, int), void *)
Data Structure Documentation
aibuf
struct aibuf
Definition at line 10 of file lookup.h.
Data Fields
struct addrinfo ai
volatile int lock[1]
short ref
union sa sa
short slot
aibuf::sa
union aibuf::sa
Definition at line 12 of file lookup.h.
Data Fields
struct sockaddr_in sin
struct sockaddr_in6 sin6
address
struct address
Definition at line 20 of file lookup.h.
Data Fields
uint8_t addr[16]
int family
unsigned scopeid
int sortkey
service
struct service
Definition at line 27 of file lookup.h.
Data Fields
uint16_t port
unsigned char proto
unsigned char socktype
resolvconf
struct resolvconf
Definition at line 34 of file lookup.h.
Data Fields
unsigned attempts
unsigned ndots
unsigned nns
struct address ns[MAXNS]
unsigned timeout
Macro Definition Documentation
MAXADDRS
#define MAXADDRS 48
Definition at line 43 of file lookup.h.
MAXNS
#define MAXNS 3
Definition at line 32 of file lookup.h.
MAXSERVS
#define MAXSERVS 2
Definition at line 44 of file lookup.h.
Function Documentation
__dns_parse()
hidden int __dns_parse (const unsigned char * r, int rlen, int(*)(void *, int, const void *, int, const void *, int) callback, void * ctx)
Definition at line 4 of file dns_parse.c.
 {
     int qdcount, ancount;
     const unsigned char *p;
     int len;
     if (rlen<12) return -1;
     if ((r[3]&15)) return 0;
     p = r+12;
     qdcount = r[4]*256 + r[5];
     ancount = r[6]*256 + r[7];
     if (qdcount+ancount > 64) return -1;
     while (qdcount--) {
         while (p-r < rlen && *p-1U < 127) p++;
         if (p>r+rlen-6 || *p>193 || (*p==193 && p[1]>254))
             return -1;
         p += 5 + !!*p;
     }
     while (ancount--) {
         while (p-r < rlen && *p-1U < 127) p++;
         if (p>r+rlen-12 || *p>193 || (*p==193 && p[1]>254))
             return -1;
         p += 1 + !!*p;
         len = p[8]*256 + p[9];
         if (len+10 > r+rlen-p) return -1;
         if (callback(ctx, p[1], p+10, len, r, rlen) < 0) return -1;
         p += 10 + len;
     }
     return 0;
 }
References callback, len, and p.
Referenced by getnameinfo(), and name_from_dns().
__get_resolv_conf()
hidden int __get_resolv_conf (struct resolvconf * conf, char * search, size_t search_sz)
Definition at line 9 of file resolvconf.c.
 {
     char line[256];
     unsigned char _buf[256];
     FILE *f, _f;
     int nns = 0;
     conf->ndots = 1;
     conf->timeout = 5;
     conf->attempts = 2;
     if (search) *search = 0;
     f = __fopen_rb_ca("/etc/resolv.conf", &_f, _buf, sizeof _buf);
     if (!f) switch (errno) {
     case ENOENT:
     case ENOTDIR:
     case EACCES:
         goto no_resolv_conf;
     default:
         return -1;
     }
     while (fgets(line, sizeof line, f)) {
         char *p, *z;
         if (!strchr(line, '\n') && !feof(f)) {
             /* Ignore lines that get truncated rather than
              * potentially misinterpreting them. */
             int c;
             do c = getc(f);
             while (c != '\n' && c != EOF);
             continue;
         }
         if (!strncmp(line, "options", 7) && isspace(line[7])) {
             p = strstr(line, "ndots:");
             if (p && isdigit(p[6])) {
                 p += 6;
                 unsigned long x = strtoul(p, &z, 10);
                 if (z != p) conf->ndots = x > 15 ? 15 : x;
             }
             p = strstr(line, "attempts:");
             if (p && isdigit(p[9])) {
                 p += 9;
                 unsigned long x = strtoul(p, &z, 10);
                 if (z != p) conf->attempts = x > 10 ? 10 : x;
             }
             p = strstr(line, "timeout:");
             if (p && (isdigit(p[8]) || p[8]=='.')) {
                 p += 8;
                 unsigned long x = strtoul(p, &z, 10);
                 if (z != p) conf->timeout = x > 60 ? 60 : x;
             }
             continue;
         }
         if (!strncmp(line, "nameserver", 10) && isspace(line[10])) {
             if (nns >= MAXNS) continue;
             for (p=line+11; isspace(*p); p++);
             for (z=p; *z && !isspace(*z); z++);
             *z=0;
             if (__lookup_ipliteral(conf->ns+nns, p, AF_UNSPEC) > 0)
                 nns++;
             continue;
         }
         if (!search) continue;
         if ((strncmp(line, "domain", 6) && strncmp(line, "search", 6))
             || !isspace(line[6]))
             continue;
         for (p=line+7; isspace(*p); p++);
         size_t l = strlen(p);
         /* This can never happen anyway with chosen buffer sizes. */
         if (l >= search_sz) continue;
         memcpy(search, p, l+1);
     }
     __fclose_ca(f);
 no_resolv_conf:
     if (!nns) {
         __lookup_ipliteral(conf->ns, "127.0.0.1", AF_UNSPEC);
         nns = 1;
     }
     conf->nns = nns;
     return 0;
 }
References __fclose_ca(), __fopen_rb_ca(), __lookup_ipliteral(), AF_UNSPEC, resolvconf::attempts, EACCES, ENOENT, ENOTDIR, EOF, errno, f, feof, fgets(), getc(), isdigit, isspace, line, MAXNS, memcpy, resolvconf::ndots, resolvconf::nns, resolvconf::ns, p, strchr(), strlen, strncmp(), strstr(), strtoul(), resolvconf::timeout, and x.
Referenced by __res_msend(), and name_from_dns_search().
__lookup_ipliteral()
hidden int __lookup_ipliteral (struct address buf[static 1], const char * name, int family)
Definition at line 12 of file lookup_ipliteral.c.
 {
     struct in_addr a4;
     struct in6_addr a6;
     if (__inet_aton(name, &a4) > 0) {
         if (family == AF_INET6) /* wrong family */
             return EAI_NODATA;
         memcpy(&buf[0].addr, &a4, sizeof a4);
         buf[0].family = AF_INET;
         buf[0].scopeid = 0;
         return 1;
     }
     char tmp[64];
     char *p = strchr(name, '%'), *z;
     unsigned long long scopeid = 0;
     if (p && p-name < 64) {
         memcpy(tmp, name, p-name);
         tmp[p-name] = 0;
         name = tmp;
     }
     if (inet_pton(AF_INET6, name, &a6) <= 0)
         return 0;
     if (family == AF_INET) /* wrong family */
         return EAI_NODATA;
     memcpy(&buf[0].addr, &a6, sizeof a6);
     buf[0].family = AF_INET6;
     if (p) {
         if (isdigit(*++p)) scopeid = strtoull(p, &z, 10);
         else z = p-1;
         if (*z) {
             if (!IN6_IS_ADDR_LINKLOCAL(&a6) &&
                 !IN6_IS_ADDR_MC_LINKLOCAL(&a6))
                 return EAI_NONAME;
             scopeid = if_nametoindex(p);
             if (!scopeid) return EAI_NONAME;
         }
         if (scopeid > UINT_MAX) return EAI_NONAME;
     }
     buf[0].scopeid = scopeid;
     return 1;
 }
References __inet_aton(), a4, a6, addr, AF_INET, AF_INET6, buf, EAI_NODATA, EAI_NONAME, if_nametoindex(), IN6_IS_ADDR_LINKLOCAL, IN6_IS_ADDR_MC_LINKLOCAL, inet_pton(), isdigit, memcpy, p, strchr(), strtoull(), and UINT_MAX.
Referenced by __get_resolv_conf(), name_from_numeric(), and reverse_hosts().
__lookup_name()
hidden int __lookup_name (struct address buf[static MAXADDRS], char canon[static 256], const char * name, int family, int flags)
Definition at line 308 of file lookup_name.c.
 {
     int cnt = 0, i, j;
     *canon = 0;
     if (name) {
         /* reject empty name and check len so it fits into temp bufs */
         size_t l = strnlen(name, 255);
         if (l-1 >= 254)
             return EAI_NONAME;
         memcpy(canon, name, l+1);
     }
     /* Procedurally, a request for v6 addresses with the v4-mapped
      * flag set is like a request for unspecified family, followed
      * by filtering of the results. */
     if (flags & AI_V4MAPPED) {
         if (family == AF_INET6) family = AF_UNSPEC;
         else flags -= AI_V4MAPPED;
     }
     /* Try each backend until there's at least one result. */
     cnt = name_from_null(buf, name, family, flags);
     if (!cnt) cnt = name_from_numeric(buf, name, family);
     if (!cnt && !(flags & AI_NUMERICHOST)) {
         cnt = name_from_hosts(buf, canon, name, family);
         if (!cnt) cnt = name_from_dns_search(buf, canon, name, family);
     }
     if (cnt<=0) return cnt ? cnt : EAI_NONAME;
     /* Filter/transform results for v4-mapped lookup, if requested. */
     if (flags & AI_V4MAPPED) {
         if (!(flags & AI_ALL)) {
             /* If any v6 results exist, remove v4 results. */
             for (i=0; i<cnt && buf[i].family != AF_INET6; i++);
             if (i<cnt) {
                 for (j=0; i<cnt; i++) {
                     if (buf[i].family == AF_INET6)
                         buf[j++] = buf[i];
                 }
                 cnt = i = j;
             }
         }
         /* Translate any remaining v4 results to v6 */
         for (i=0; i<cnt; i++) {
             if (buf[i].family != AF_INET) continue;
             memcpy(buf[i].addr+12, buf[i].addr, 4);
             memcpy(buf[i].addr, "\0\0\0\0\0\0\0\0\0\0\xff\xff", 12);
             buf[i].family = AF_INET6;
         }
     }
     /* No further processing is needed if there are fewer than 2
      * results or if there are only IPv4 results. */
     if (cnt<2 || family==AF_INET) return cnt;
     for (i=0; i<cnt; i++) if (buf[i].family != AF_INET) break;
     if (i==cnt) return cnt;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     /* The following implements a subset of RFC 3484/6724 destination
      * address selection by generating a single 31-bit sort key for
      * each address. Rules 3, 4, and 7 are omitted for having
      * excessive runtime and code size cost and dubious benefit.
      * So far the label/precedence table cannot be customized. */
     for (i=0; i<cnt; i++) {
         int family = buf[i].family;
         int key = 0;
         struct sockaddr_in6 sa6 = { 0 }, da6 = {
             .sin6_family = AF_INET6,
             .sin6_scope_id = buf[i].scopeid,
             .sin6_port = 65535
         };
         struct sockaddr_in sa4 = { 0 }, da4 = {
             .sin_family = AF_INET,
             .sin_port = 65535
         };
         void *sa, *da;
         socklen_t salen, dalen;
         if (family == AF_INET6) {
             memcpy(da6.sin6_addr.s6_addr, buf[i].addr, 16);
             da = &da6; dalen = sizeof da6;
             sa = &sa6; salen = sizeof sa6;
         } else {
             memcpy(sa6.sin6_addr.s6_addr,
                 "\0\0\0\0\0\0\0\0\0\0\xff\xff", 12);
             memcpy(da6.sin6_addr.s6_addr+12, buf[i].addr, 4);
             memcpy(da6.sin6_addr.s6_addr,
                 "\0\0\0\0\0\0\0\0\0\0\xff\xff", 12);
             memcpy(da6.sin6_addr.s6_addr+12, buf[i].addr, 4);
             memcpy(&da4.sin_addr, buf[i].addr, 4);
             da = &da4; dalen = sizeof da4;
             sa = &sa4; salen = sizeof sa4;
         }
         const struct policy *dpolicy = policyof(&da6.sin6_addr);
         int dscope = scopeof(&da6.sin6_addr);
         int dlabel = dpolicy->label;
         int dprec = dpolicy->prec;
         int prefixlen = 0;
         int fd = socket(family, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_UDP);
         if (fd >= 0) {
             if (!connect(fd, da, dalen)) {
                 key |= DAS_USABLE;
                 if (!getsockname(fd, sa, &salen)) {
                     if (family == AF_INET) memcpy(
                         sa6.sin6_addr.s6_addr+12,
                         &sa4.sin_addr, 4);
                     if (dscope == scopeof(&sa6.sin6_addr))
                         key |= DAS_MATCHINGSCOPE;
                     if (dlabel == labelof(&sa6.sin6_addr))
                         key |= DAS_MATCHINGLABEL;
                     prefixlen = prefixmatch(&sa6.sin6_addr,
                         &da6.sin6_addr);
                 }
             }
             close(fd);
         }
         key |= dprec << DAS_PREC_SHIFT;
         key |= (15-dscope) << DAS_SCOPE_SHIFT;
         key |= prefixlen << DAS_PREFIX_SHIFT;
         key |= (MAXADDRS-i) << DAS_ORDER_SHIFT;
         buf[i].sortkey = key;
     }
     qsort(buf, cnt, sizeof *buf, addrcmp);
     pthread_setcancelstate(cs, 0);
     return cnt;
 }
References addr, addrcmp(), AF_INET, AF_INET6, AF_UNSPEC, AI_ALL, AI_NUMERICHOST, AI_V4MAPPED, buf, close(), cnt, connect(), DAS_MATCHINGLABEL, DAS_MATCHINGSCOPE, DAS_ORDER_SHIFT, DAS_PREC_SHIFT, DAS_PREFIX_SHIFT, DAS_SCOPE_SHIFT, DAS_USABLE, EAI_NONAME, address::family, fd, getsockname(), i, IPPROTO_UDP, j, policy::label, labelof(), MAXADDRS, memcpy, name_from_dns_search(), name_from_hosts(), name_from_null(), name_from_numeric(), policyof(), policy::prec, prefixmatch(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), qsort(), sa4, sa6, scopeof(), SOCK_CLOEXEC, SOCK_DGRAM, socket(), and strnlen().
Referenced by getaddrinfo(), and gethostbyname2_r().
__lookup_serv()
hidden int __lookup_serv (struct service buf[static MAXSERVS], const char * name, int proto, int socktype, int flags)
Definition at line 12 of file lookup_serv.c.
 {
     char line[128];
     int cnt = 0;
     char *p, *z = "";
     unsigned long port = 0;
     switch (socktype) {
     case SOCK_STREAM:
         switch (proto) {
         case 0:
             proto = IPPROTO_TCP;
         case IPPROTO_TCP:
             break;
         default:
             return EAI_SERVICE;
         }
         break;
     case SOCK_DGRAM:
         switch (proto) {
         case 0:
             proto = IPPROTO_UDP;
         case IPPROTO_UDP:
             break;
         default:
             return EAI_SERVICE;
         }
     case 0:
         break;
     default:
         if (name) return EAI_SERVICE;
         buf[0].port = 0;
         buf[0].proto = proto;
         buf[0].socktype = socktype;
         return 1;
     }
     if (name) {
         if (!*name) return EAI_SERVICE;
         port = strtoul(name, &z, 10);
     }
     if (!*z) {
         if (port > 65535) return EAI_SERVICE;
         if (proto != IPPROTO_UDP) {
             buf[cnt].port = port;
             buf[cnt].socktype = SOCK_STREAM;
             buf[cnt++].proto = IPPROTO_TCP;
         }
         if (proto != IPPROTO_TCP) {
             buf[cnt].port = port;
             buf[cnt].socktype = SOCK_DGRAM;
             buf[cnt++].proto = IPPROTO_UDP;
         }
         return cnt;
     }
     if (flags & AI_NUMERICSERV) return EAI_NONAME;
     size_t l = strlen(name);
     unsigned char _buf[1032];
     FILE _f, *f = __fopen_rb_ca("/etc/services", &_f, _buf, sizeof _buf);
     if (!f) switch (errno) {
     case ENOENT:
     case ENOTDIR:
     case EACCES:
         return EAI_SERVICE;
     default:
         return EAI_SYSTEM;
     }
     while (fgets(line, sizeof line, f) && cnt < MAXSERVS) {
         if ((p=strchr(line, '#'))) *p++='\n', *p=0;
         /* Find service name */
         for(p=line; (p=strstr(p, name)); p++) {
             if (p>line && !isspace(p[-1])) continue;
             if (p[l] && !isspace(p[l])) continue;
             break;
         }
         if (!p) continue;
         /* Skip past canonical name at beginning of line */
         for (p=line; *p && !isspace(*p); p++);
         port = strtoul(p, &z, 10);
         if (port > 65535 || z==p) continue;
         if (!strncmp(z, "/udp", 4)) {
             if (proto == IPPROTO_TCP) continue;
             buf[cnt].port = port;
             buf[cnt].socktype = SOCK_DGRAM;
             buf[cnt++].proto = IPPROTO_UDP;
         }
         if (!strncmp(z, "/tcp", 4)) {
             if (proto == IPPROTO_UDP) continue;
             buf[cnt].port = port;
             buf[cnt].socktype = SOCK_STREAM;
             buf[cnt++].proto = IPPROTO_TCP;
         }
     }
     __fclose_ca(f);
     return cnt > 0 ? cnt : EAI_SERVICE;
 }
References __fclose_ca(), __fopen_rb_ca(), AI_NUMERICSERV, buf, cnt, EACCES, EAI_NONAME, EAI_SERVICE, EAI_SYSTEM, ENOENT, ENOTDIR, errno, f, fgets(), IPPROTO_TCP, IPPROTO_UDP, isspace, line, MAXSERVS, p, SOCK_DGRAM, SOCK_STREAM, strchr(), strlen, strncmp(), strstr(), and strtoul().
Referenced by getaddrinfo(), and getservbyname_r().
__res_msend_rc()
hidden int __res_msend_rc (int nqueries, const unsigned char *const * queries, const int * qlens, unsigned char *const * answers, int * alens, int asize, const struct resolvconf * conf)
Definition at line 79 of file res_msend.c.
 {
     int fd;
     int timeout, attempts, retry_interval, servfail_retry;
     union {
         struct sockaddr_in sin;
         struct sockaddr_in6 sin6;
     } sa = {0}, ns[MAXNS] = {{0}};
     socklen_t sl = sizeof sa.sin;
     int nns = 0;
     int family = AF_INET;
     int rlen;
     int next;
     int i, j;
     int cs;
     struct pollfd pfd[nqueries+2];
     int qpos[nqueries], apos[nqueries];
     unsigned char alen_buf[nqueries][2];
     int r;
     unsigned long t0, t1, t2;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     timeout = 1000*conf->timeout;
     attempts = conf->attempts;
     for (nns=0; nns<conf->nns; nns++) {
         const struct address *iplit = &conf->ns[nns];
         if (iplit->family == AF_INET) {
             memcpy(&ns[nns].sin.sin_addr, iplit->addr, 4);
             ns[nns].sin.sin_port = htons(53);
             ns[nns].sin.sin_family = AF_INET;
         } else {
             sl = sizeof sa.sin6;
             memcpy(&ns[nns].sin6.sin6_addr, iplit->addr, 16);
             ns[nns].sin6.sin6_port = htons(53);
             ns[nns].sin6.sin6_scope_id = iplit->scopeid;
             ns[nns].sin6.sin6_family = family = AF_INET6;
         }
     }
     /* Get local address and open/bind a socket */
     fd = socket(family, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0);
     /* Handle case where system lacks IPv6 support */
     if (fd < 0 && family == AF_INET6 && errno == EAFNOSUPPORT) {
         for (i=0; i<nns && conf->ns[nns].family == AF_INET6; i++);
         if (i==nns) {
             pthread_setcancelstate(cs, 0);
             return -1;
         }
         fd = socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0);
         family = AF_INET;
         sl = sizeof sa.sin;
     }
     /* Convert any IPv4 addresses in a mixed environment to v4-mapped */
     if (fd >= 0 && family == AF_INET6) {
         setsockopt(fd, IPPROTO_IPV6, IPV6_V6ONLY, &(int){0}, sizeof 0);
         for (i=0; i<nns; i++) {
             if (ns[i].sin.sin_family != AF_INET) continue;
             memcpy(ns[i].sin6.sin6_addr.s6_addr+12,
                 &ns[i].sin.sin_addr, 4);
             memcpy(ns[i].sin6.sin6_addr.s6_addr,
                 "\0\0\0\0\0\0\0\0\0\0\xff\xff", 12);
             ns[i].sin6.sin6_family = AF_INET6;
             ns[i].sin6.sin6_flowinfo = 0;
             ns[i].sin6.sin6_scope_id = 0;
         }
     }
     sa.sin.sin_family = family;
     if (fd < 0 || bind(fd, (void *)&sa, sl) < 0) {
         if (fd >= 0) close(fd);
         pthread_setcancelstate(cs, 0);
         return -1;
     }
     /* Past this point, there are no errors. Each individual query will
      * yield either no reply (indicated by zero length) or an answer
      * packet which is up to the caller to interpret. */
     for (i=0; i<nqueries; i++) pfd[i].fd = -1;
     pfd[nqueries].fd = fd;
     pfd[nqueries].events = POLLIN;
     pfd[nqueries+1].fd = -2;
     pthread_cleanup_push(cleanup, pfd);
     pthread_setcancelstate(cs, 0);
     memset(alens, 0, sizeof *alens * nqueries);
     retry_interval = timeout / attempts;
     next = 0;
     t0 = t2 = mtime();
     t1 = t2 - retry_interval;
     for (; t2-t0 < timeout; t2=mtime()) {
         /* This is the loop exit condition: that all queries
          * have an accepted answer. */
         for (i=0; i<nqueries && alens[i]>0; i++);
         if (i==nqueries) break;
         if (t2-t1 >= retry_interval) {
             /* Query all configured namservers in parallel */
             for (i=0; i<nqueries; i++)
                 if (!alens[i])
                     for (j=0; j<nns; j++)
                         sendto(fd, queries[i],
                             qlens[i], MSG_NOSIGNAL,
                             (void *)&ns[j], sl);
             t1 = t2;
             servfail_retry = 2 * nqueries;
         }
         /* Wait for a response, or until time to retry */
         if (poll(pfd, nqueries+1, t1+retry_interval-t2) <= 0) continue;
         while (next < nqueries) {
             struct msghdr mh = {
                 .msg_name = (void *)&sa,
                 .msg_namelen = sl,
                 .msg_iovlen = 1,
                 .msg_iov = (struct iovec []){
                     { .iov_base = (void *)answers[next],
                       .iov_len = asize }
                 }
             };
             rlen = recvmsg(fd, &mh, 0);
             if (rlen < 0) break;
             /* Ignore non-identifiable packets */
             if (rlen < 4) continue;
             /* Ignore replies from addresses we didn't send to */
             for (j=0; j<nns && memcmp(ns+j, &sa, sl); j++);
             if (j==nns) continue;
             /* Find which query this answer goes with, if any */
             for (i=next; i<nqueries && (
                 answers[next][0] != queries[i][0] ||
                 answers[next][1] != queries[i][1] ); i++);
             if (i==nqueries) continue;
             if (alens[i]) continue;
             /* Only accept positive or negative responses;
              * retry immediately on server failure, and ignore
              * all other codes such as refusal. */
             switch (answers[next][3] & 15) {
             case 0:
             case 3:
                 break;
             case 2:
                 if (servfail_retry && servfail_retry--)
                     sendto(fd, queries[i],
                         qlens[i], MSG_NOSIGNAL,
                         (void *)&ns[j], sl);
             default:
                 continue;
             }
             /* Store answer in the right slot, or update next
              * available temp slot if it's already in place. */
             alens[i] = rlen;
             if (i == next)
                 for (; next<nqueries && alens[next]; next++);
             else
                 memcpy(answers[i], answers[next], rlen);
             /* Ignore further UDP if all slots full or TCP-mode */
             if (next == nqueries) pfd[nqueries].events = 0;
             /* If answer is truncated (TC bit), fallback to TCP */
             if ((answers[i][2] & 2) || (mh.msg_flags & MSG_TRUNC)) {
                 alens[i] = -1;
                 pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, 0);
                 r = start_tcp(pfd+i, family, ns+j, sl, queries[i], qlens[i]);
                 pthread_setcancelstate(cs, 0);
                 if (r >= 0) {
                     qpos[i] = r;
                     apos[i] = 0;
                 }
                 continue;
             }
         }
         for (i=0; i<nqueries; i++) if (pfd[i].revents & POLLOUT) {
             struct msghdr mh = {
                 .msg_iovlen = 2,
                 .msg_iov = (struct iovec [2]){
                     { .iov_base = (uint8_t[]){ qlens[i]>>8, qlens[i] }, .iov_len = 2 },
                     { .iov_base = (void *)queries[i], .iov_len = qlens[i] } }
             };
             step_mh(&mh, qpos[i]);
             r = sendmsg(pfd[i].fd, &mh, MSG_NOSIGNAL);
             if (r < 0) goto out;
             qpos[i] += r;
             if (qpos[i] == qlens[i]+2)
                 pfd[i].events = POLLIN;
         }
         for (i=0; i<nqueries; i++) if (pfd[i].revents & POLLIN) {
             struct msghdr mh = {
                 .msg_iovlen = 2,
                 .msg_iov = (struct iovec [2]){
                     { .iov_base = alen_buf[i], .iov_len = 2 },
                     { .iov_base = answers[i], .iov_len = asize } }
             };
             step_mh(&mh, apos[i]);
             r = recvmsg(pfd[i].fd, &mh, 0);
             if (r <= 0) goto out;
             apos[i] += r;
             if (apos[i] < 2) continue;
             int alen = alen_buf[i][0]*256 + alen_buf[i][1];
             if (alen < 13) goto out;
             if (apos[i] < alen+2 && apos[i] < asize+2)
                 continue;
             int rcode = answers[i][3] & 15;
             if (rcode != 0 && rcode != 3)
                 goto out;
             /* Storing the length here commits the accepted answer.
              * Immediately close TCP socket so as not to consume
              * resources we no longer need. */
             alens[i] = alen;
             __syscall(SYS_close, pfd[i].fd);
             pfd[i].fd = -1;
         }
     }
 out:
     pthread_cleanup_pop(1);
     /* Disregard any incomplete TCP results */
     for (i=0; i<nqueries; i++) if (alens[i]<0) alens[i] = 0;
     return 0;
 }
References __syscall, address::addr, AF_INET, AF_INET6, resolvconf::attempts, bind(), cleanup(), close(), EAFNOSUPPORT, errno, pollfd::events, address::family, fd, pollfd::fd, htons(), i, iovec::iov_base, iovec::iov_len, IPPROTO_IPV6, IPV6_V6ONLY, j, MAXNS, memcmp(), memcpy, memset, msghdr::msg_flags, msghdr::msg_iov, msghdr::msg_iovlen, msghdr::msg_name, msghdr::msg_namelen, MSG_NOSIGNAL, MSG_TRUNC, mtime(), resolvconf::nns, resolvconf::ns, out(), poll(), POLLIN, POLLOUT, PTHREAD_CANCEL_DISABLE, pthread_cleanup_pop, pthread_cleanup_push, pthread_setcancelstate(), recvmsg(), address::scopeid, sendmsg(), sendto(), setsockopt(), sin, SOCK_CLOEXEC, SOCK_DGRAM, SOCK_NONBLOCK, socket(), start_tcp(), step_mh(), t0, t1, t2, and resolvconf::timeout.
Referenced by __res_msend(), and name_from_dns().