Fennix Userspace: Userspace/apps/base/busybox/sysklogd/logread.c File Reference
logread.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/shm.h>
Data Structures
struct shbuf_ds
struct globals
Macros
#define DEBUG 0
#define G (*(struct globals*)bb_common_bufsiz1)
#define SMrup (G.SMrup)
#define SMrdn (G.SMrdn)
#define shbuf (G.shbuf)
#define INIT_G()
#define error_exit(str) bb_simple_perror_msg_and_die(str)
Enumerations
enum { KEY_ID = 0x414e4547 }
Functions
static void sem_up (int semid)
static void interrupted (int sig)
int logread_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
static const struct sembuf init_sem [3]
struct globals FIX_ALIASING
Data Structure Documentation
shbuf_ds
struct shbuf_ds
Definition at line 56 of file logread.c.
Data Fields
char data[1]
int32_t size
int32_t tail
Macro Definition Documentation
DEBUG
#define DEBUG 0
Definition at line 51 of file logread.c.
error_exit
#define error_exit (str) bb_simple_perror_msg_and_die(str)
Definition at line 91 of file logread.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 72 of file logread.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    memcpy(SMrup, init_sem, sizeof(init_sem)); \
} while (0)
Definition at line 76 of file logread.c.
shbuf
#define shbuf (G.shbuf)
Definition at line 75 of file logread.c.
SMrdn
#define SMrdn (G.SMrdn)
Definition at line 74 of file logread.c.
SMrup
#define SMrup (G.SMrup)
Definition at line 73 of file logread.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
KEY_ID
Definition at line 54 of file logread.c.
 { KEY_ID = 0x414e4547 }; /* "GENA" */
Function Documentation
interrupted()
static void interrupted (int sig) static
Definition at line 103 of file logread.c.
 {
     /* shmdt(shbuf); - on Linux, shmdt is not mandatory on exit */
     kill_myself_with_sig(sig);
 }
References kill_myself_with_sig().
Referenced by logread_main().
logread_main()
int logread_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 110 of file logread.c.
 {
     unsigned cur;
     int log_semid; /* ipc semaphore id */
     int log_shmid; /* ipc shared memory id */
     int follow = getopt32(argv, "fF");
     INIT_G();
     log_shmid = shmget(KEY_ID, 0, 0);
     if (log_shmid == -1)
         bb_perror_msg_and_die("can't %s syslogd buffer", "find");
     /* Attach shared memory to our char* */
     shbuf = shmat(log_shmid, NULL, SHM_RDONLY);
     if (shbuf == NULL)
         bb_perror_msg_and_die("can't %s syslogd buffer", "access");
     log_semid = semget(KEY_ID, 0, 0);
     if (log_semid == -1)
         error_exit("can't get access to semaphores for syslogd buffer");
     bb_signals(BB_FATAL_SIGS, interrupted);
     /* Suppose atomic memory read */
     /* Max possible value for tail is shbuf->size - 1 */
     cur = shbuf->tail;
     /* Loop for -f or -F, one pass otherwise */
     do {
         unsigned shbuf_size;
         unsigned shbuf_tail;
         const char *shbuf_data;
 #if ENABLE_FEATURE_LOGREAD_REDUCED_LOCKING
         int i;
         int len_first_part;
         int len_total = len_total; /* for gcc */
         char *copy = copy; /* for gcc */
 #endif
         if (semop(log_semid, SMrdn, 2) == -1)
             error_exit("semop[SMrdn]");
         /* Copy the info, helps gcc to realize that it doesn't change */
         shbuf_size = shbuf->size;
         shbuf_tail = shbuf->tail;
         shbuf_data = shbuf->data; /* pointer! */
         if (DEBUG)
             printf("cur:%u tail:%u size:%u\n",
                     cur, shbuf_tail, shbuf_size);
         if (!(follow & 1)) { /* not -f */
             /* if -F, "convert" it to -f, so that we don't
              * dump the entire buffer on each iteration
              */
             follow >>= 1;
             /* advance to oldest complete message */
             /* find NUL */
             cur += strlen(shbuf_data + cur);
             if (cur >= shbuf_size) { /* last byte in buffer? */
                 cur = strnlen(shbuf_data, shbuf_tail);
                 if (cur == shbuf_tail)
                     goto unlock; /* no complete messages */
             }
             /* advance to first byte of the message */
             cur++;
             if (cur >= shbuf_size) /* last byte in buffer? */
                 cur = 0;
         } else { /* -f */
             if (cur == shbuf_tail) {
                 sem_up(log_semid);
                 fflush_all();
                 sleep1(); /* TODO: replace me with a sleep_on */
                 continue;
             }
         }
         /* Read from cur to tail */
 #if ENABLE_FEATURE_LOGREAD_REDUCED_LOCKING
         len_first_part = len_total = shbuf_tail - cur;
         if (len_total < 0) {
             /* message wraps: */
             /* [SECOND PART.........FIRST PART] */
             /*  ^data      ^tail    ^cur      ^size */
             len_total += shbuf_size;
         }
         copy = xmalloc(len_total + 1);
         if (len_first_part < 0) {
             /* message wraps (see above) */
             len_first_part = shbuf_size - cur;
             memcpy(copy + len_first_part, shbuf_data, shbuf_tail);
         }
         memcpy(copy, shbuf_data + cur, len_first_part);
         copy[len_total] = '\0';
         cur = shbuf_tail;
 #else
         while (cur != shbuf_tail) {
             fputs_stdout(shbuf_data + cur);
             cur += strlen(shbuf_data + cur) + 1;
             if (cur >= shbuf_size)
                 cur = 0;
         }
 #endif
  unlock:
         /* release the lock on the log chain */
         sem_up(log_semid);
 #if ENABLE_FEATURE_LOGREAD_REDUCED_LOCKING
         for (i = 0; i < len_total; i += strlen(copy + i) + 1) {
             fputs_stdout(copy + i);
         }
         free(copy);
 #endif
         fflush_all();
     } while (follow);
     /* shmdt(shbuf); - on Linux, shmdt is not mandatory on exit */
     fflush_stdout_and_exit_SUCCESS();
 }
References argv, BB_FATAL_SIGS, bb_perror_msg_and_die(), bb_signals(), cur, DEBUG, error_exit, fflush_all(), fflush_stdout_and_exit_SUCCESS(), fputs_stdout(), free, getopt32(), i, INIT_G, interrupted(), KEY_ID, memcpy(), NULL, printf(), sem_up(), semget(), semop(), shbuf, SHM_RDONLY, shmat(), shmget(), sleep1(), SMrdn, strlen(), strnlen(), unlock(), and xmalloc.
sem_up()
static void sem_up (int semid) static
Definition at line 97 of file logread.c.
 {
     if (semop(semid, SMrup, 1) == -1)
         error_exit("semop[SMrup]");
 }
References error_exit, semop(), and SMrup.
Referenced by logread_main().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING
init_sem
const struct sembuf init_sem[3] static
Initial value:
= {
    {0, -1, IPC_NOWAIT | SEM_UNDO},
    {1, 0}, {0, +1, SEM_UNDO}
}
Definition at line 1 of file logread.c.