Fennix: Memory::Physical Class Reference
Memory::Physical Class Reference
#include <physical.hpp>
Public Member Functions
Bitmap GetPageBitmap ()
uint64_t GetTotalMemory ()
Get Total Memory.
uint64_t GetFreeMemory ()
Get Free Memory.
uint64_t GetReservedMemory ()
Get Reserved Memory.
uint64_t GetUsedMemory ()
Get Used Memory.
bool SwapPage (void *Address)
Swap page.
bool SwapPages (void *Address, size_t PageCount)
Swap pages.
bool UnswapPage (void *Address)
Unswap page.
bool UnswapPages (void *Address, size_t PageCount)
Unswap pages.
void LockPage (void *Address)
Lock page.
void LockPages (void *Address, size_t PageCount)
Lock pages.
void ReservePage (void *Address)
void ReservePages (void *Address, size_t PageCount)
void UnreservePage (void *Address)
void UnreservePages (void *Address, size_t PageCount)
void * RequestPage ()
Request page.
void * RequestPages (std::size_t Count)
Request pages.
void FreePage (void *Address)
Free page.
void FreePages (void *Address, size_t Count)
Free pages.
void Init ()
Do not use.
Physical ()
Do not use.
~Physical ()
Do not use.
Private Member Functions
NewLock (MemoryLock)
void ReserveEssentials ()
void FindBitmapRegion (uintptr_t &BitmapAddress, size_t &BitmapAddressSize)
Private Attributes
std::atomic_uint64_t TotalMemory = 0
std::atomic_uint64_t FreeMemory = 0
std::atomic_uint64_t ReservedMemory = 0
std::atomic_uint64_t UsedMemory = 0
uint64_t PageBitmapIndex = 0
Bitmap PageBitmap
Detailed Description
Definition at line 28 of file physical.hpp.
Constructor & Destructor Documentation
Physical()
Memory::Physical::Physical ()
Do not use.
Definition at line 350 of file pmm.cpp.
 {}
~Physical()
Memory::Physical::~Physical ()
Do not use.
Definition at line 351 of file pmm.cpp.
 {}
Member Function Documentation
FindBitmapRegion()
void Memory::Physical::FindBitmapRegion (uintptr_t & BitmapAddress, size_t & BitmapAddressSize) private
Referenced by Init().
FreePage()
void Memory::Physical::FreePage (void * Address)
Free page.
Parameters
Address Address of the page
Definition at line 167 of file pmm.cpp.
     {
         SmartLock(this->MemoryLock);
         if (unlikely(Address == nullptr))
         {
             warn("Null pointer passed to FreePage.");
             return;
         }
         size_t Index = (size_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == false))
         {
             warn("Tried to free an already free page. (%p)",
                  Address);
             return;
         }
         if (PageBitmap.Set(Index, false))
         {
             FreeMemory += PAGE_SIZE;
             UsedMemory -= PAGE_SIZE;
             if (PageBitmapIndex > Index)
                 PageBitmapIndex = Index;
         }
     }
References Address, FreeMemory, PAGE_SIZE, PageBitmap, PageBitmapIndex, Bitmap::Set(), unlikely, UsedMemory, and warn.
Referenced by free(), and FreePages().
FreePages()
void Memory::Physical::FreePages (void * Address, size_t Count)
Free pages.
Parameters
Address Address of the pages
PageCount Number of pages
Definition at line 195 of file pmm.cpp.
     {
         if (unlikely(Address == nullptr || Count == 0))
         {
             warn("%s%s%s passed to FreePages.", Address == nullptr ? "Null pointer " : "", Address == nullptr && Count == 0 ? "and " : "", Count == 0 ? "Zero count" : "");
             return;
         }
         for (size_t t = 0; t < Count; t++)
             this->FreePage((void *)((uintptr_t)Address + (t * PAGE_SIZE)));
     }
References Address, FreePage(), PAGE_SIZE, t, unlikely, and warn.
Referenced by liballoc_free().
GetFreeMemory()
uint64_t Memory::Physical::GetFreeMemory ()
Get Free Memory.
Returns
uint64_t
Definition at line 36 of file pmm.cpp.
     {
         return this->FreeMemory.load();
     }
References FreeMemory.
GetPageBitmap()
Bitmap Memory::Physical::GetPageBitmap () inline
Definition at line 45 of file physical.hpp.
 { return PageBitmap; }
References PageBitmap.
GetReservedMemory()
uint64_t Memory::Physical::GetReservedMemory ()
Get Reserved Memory.
Returns
uint64_t
Definition at line 41 of file pmm.cpp.
     {
         return this->ReservedMemory.load();
     }
References ReservedMemory.
Referenced by InitializeMemoryManagement().
GetTotalMemory()
uint64_t Memory::Physical::GetTotalMemory ()
Get Total Memory.
Returns
uint64_t
Definition at line 31 of file pmm.cpp.
     {
         return this->TotalMemory.load();
     }
References TotalMemory.
Referenced by InitializeMemoryManagement().
GetUsedMemory()
uint64_t Memory::Physical::GetUsedMemory ()
Get Used Memory.
Returns
uint64_t
Definition at line 46 of file pmm.cpp.
     {
         return this->UsedMemory.load();
     }
References UsedMemory.
Referenced by InitializeMemoryManagement().
Init()
void Memory::Physical::Init ()
Do not use.
Definition at line 316 of file pmm.cpp.
     {
         SmartLock(this->MemoryLock);
         uint64_t MemorySize = bInfo.Memory.Size;
         debug("Memory size: %lld bytes (%ld pages)",
               MemorySize, TO_PAGES(MemorySize));
         TotalMemory = MemorySize;
         FreeMemory = MemorySize;
         size_t BitmapSize = (size_t)(MemorySize / PAGE_SIZE) / 8 + 1;
         uintptr_t BitmapAddress = 0x0;
         size_t BitmapAddressSize = 0;
         FindBitmapRegion(BitmapAddress, BitmapAddressSize);
         if (BitmapAddress == 0x0)
         {
             error("No free memory found!");
             CPU::Stop();
         }
         debug("Initializing Bitmap at %p-%p (%d Bytes)",
               BitmapAddress,
               (void *)(BitmapAddress + BitmapSize),
               BitmapSize);
         PageBitmap.Size = BitmapSize;
         PageBitmap.Buffer = (uint8_t *)BitmapAddress;
         for (size_t i = 0; i < BitmapSize; i++)
             *(uint8_t *)(PageBitmap.Buffer + i) = 0;
         ReserveEssentials();
     }
References bInfo, Bitmap::Buffer, debug, error, FindBitmapRegion(), FreeMemory, i, BootInfo::Memory, PAGE_SIZE, PageBitmap, ReserveEssentials(), Bitmap::Size, BootInfo::MemoryInfo::Size, TO_PAGES, and TotalMemory.
Referenced by InitializeMemoryManagement().
LockPage()
void Memory::Physical::LockPage (void * Address)
Lock page.
Parameters
Address Address of the page
Definition at line 206 of file pmm.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to lock null address.");
         uintptr_t Index = (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == true))
             return;
         if (PageBitmap.Set(Index, true))
         {
             FreeMemory -= PAGE_SIZE;
             UsedMemory += PAGE_SIZE;
         }
     }
References Address, FreeMemory, PAGE_SIZE, PageBitmap, Bitmap::Set(), unlikely, UsedMemory, and warn.
Referenced by InitializeMemoryManagement(), LockPages(), and RequestPage().
LockPages()
void Memory::Physical::LockPages (void * Address, size_t PageCount)
Lock pages.
Parameters
Address Address of the pages
PageCount Number of pages
Definition at line 223 of file pmm.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to lock %s%s.",
                  Address ? "null address" : "",
                  PageCount ? "0 pages" : "");
         for (size_t i = 0; i < PageCount; i++)
             this->LockPage((void *)((uintptr_t)Address + (i * PAGE_SIZE)));
     }
References Address, i, LockPage(), PAGE_SIZE, unlikely, and warn.
Referenced by RequestPages().
NewLock()
Memory::Physical::NewLock (MemoryLock) private
RequestPage()
void * Memory::Physical::RequestPage ()
Request page.
Returns
void* Allocated page address
Definition at line 83 of file pmm.cpp.
     {
         SmartLock(this->MemoryLock);
         for (; PageBitmapIndex < PageBitmap.Size * 8; PageBitmapIndex++)
         {
             if (PageBitmap[PageBitmapIndex] == true)
                 continue;
             this->LockPage((void *)(PageBitmapIndex * PAGE_SIZE));
             return (void *)(PageBitmapIndex * PAGE_SIZE);
         }
         if (this->SwapPage((void *)(PageBitmapIndex * PAGE_SIZE)))
         {
             this->LockPage((void *)(PageBitmapIndex * PAGE_SIZE));
             return (void *)(PageBitmapIndex * PAGE_SIZE);
         }
         if (TaskManager && !TaskManager->IsPanic())
         {
             error("Out of memory! Killing current process...");
             TaskManager->KillProcess(thisProcess, Tasking::KILL_OOM);
             TaskManager->Yield();
         }
         error("Out of memory! (Free: %ld MiB; Used: %ld MiB; Reserved: %ld MiB)",
               TO_MiB(FreeMemory), TO_MiB(UsedMemory), TO_MiB(ReservedMemory));
         KPrint("Out of memory! (Free: %ld MiB; Used: %ld MiB; Reserved: %ld MiB)",
                TO_MiB(FreeMemory), TO_MiB(UsedMemory), TO_MiB(ReservedMemory));
         CPU::Stop();
         __builtin_unreachable();
     }
References error, FreeMemory, Tasking::Task::IsPanic(), Tasking::KILL_OOM, Tasking::Task::KillProcess(), KPrint(), LockPage(), PAGE_SIZE, PageBitmap, PageBitmapIndex, ReservedMemory, Bitmap::Size, SwapPage(), TaskManager, thisProcess, TO_MiB, UsedMemory, and Tasking::Task::Yield().
Referenced by InitializeMemoryManagement().
RequestPages()
void * Memory::Physical::RequestPages (std::size_t Count)
Request pages.
Parameters
PageCount Number of pages
Returns
void* Allocated pages address
Definition at line 117 of file pmm.cpp.
     {
         SmartLock(this->MemoryLock);
         for (; PageBitmapIndex < PageBitmap.Size * 8; PageBitmapIndex++)
         {
             if (PageBitmap[PageBitmapIndex] == true)
                 continue;
             for (uint64_t Index = PageBitmapIndex; Index < PageBitmap.Size * 8; Index++)
             {
                 if (PageBitmap[Index] == true)
                     continue;
                 for (size_t i = 0; i < Count; i++)
                 {
                     if (PageBitmap[Index + i] == true)
                         goto NextPage;
                 }
                 this->LockPages((void *)(Index * PAGE_SIZE), Count);
                 return (void *)(Index * PAGE_SIZE);
             NextPage:
                 Index += Count;
                 continue;
             }
         }
         if (this->SwapPages((void *)(PageBitmapIndex * PAGE_SIZE), Count))
         {
             this->LockPages((void *)(PageBitmapIndex * PAGE_SIZE), Count);
             return (void *)(PageBitmapIndex * PAGE_SIZE);
         }
         if (TaskManager && !TaskManager->IsPanic())
         {
             error("Out of memory! Killing current process...");
             TaskManager->KillProcess(thisProcess, Tasking::KILL_OOM);
             TaskManager->Yield();
         }
         error("Out of memory! (Free: %ld MiB; Used: %ld MiB; Reserved: %ld MiB)",
               TO_MiB(FreeMemory), TO_MiB(UsedMemory), TO_MiB(ReservedMemory));
         KPrint("Out of memory! (Free: %ld MiB; Used: %ld MiB; Reserved: %ld MiB)",
                TO_MiB(FreeMemory), TO_MiB(UsedMemory), TO_MiB(ReservedMemory));
         CPU::Halt(true);
         __builtin_unreachable();
     }
References error, FreeMemory, Halt(), i, Tasking::Task::IsPanic(), Tasking::KILL_OOM, Tasking::Task::KillProcess(), KPrint(), LockPages(), PAGE_SIZE, PageBitmap, PageBitmapIndex, ReservedMemory, Bitmap::Size, SwapPages(), TaskManager, thisProcess, TO_MiB, UsedMemory, and Tasking::Task::Yield().
Referenced by calloc(), InitializeMemoryManagement(), liballoc_alloc(), malloc(), and realloc().
ReserveEssentials()
void Memory::Physical::ReserveEssentials () private
Referenced by Init().
ReservePage()
void Memory::Physical::ReservePage (void * Address)
Definition at line 234 of file pmm.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to reserve null address.");
         uintptr_t Index = (Address == NULL) ? 0 : (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == true))
             return;
         if (PageBitmap.Set(Index, true))
         {
             FreeMemory -= PAGE_SIZE;
             ReservedMemory += PAGE_SIZE;
         }
     }
References Address, FreeMemory, NULL, PAGE_SIZE, PageBitmap, ReservedMemory, Bitmap::Set(), unlikely, and warn.
Referenced by MapKernel().
ReservePages()
void Memory::Physical::ReservePages (void * Address, size_t PageCount)
Definition at line 251 of file pmm.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to reserve %s%s.",
                  Address ? "null address" : "",
                  PageCount ? "0 pages" : "");
         for (size_t t = 0; t < PageCount; t++)
         {
             uintptr_t Index = ((uintptr_t)Address + (t * PAGE_SIZE)) / PAGE_SIZE;
             if (unlikely(PageBitmap[Index] == true))
                 return;
             if (PageBitmap.Set(Index, true))
             {
                 FreeMemory -= PAGE_SIZE;
                 ReservedMemory += PAGE_SIZE;
             }
         }
     }
References Address, FreeMemory, PAGE_SIZE, PageBitmap, ReservedMemory, Bitmap::Set(), t, unlikely, and warn.
SwapPage()
bool Memory::Physical::SwapPage (void * Address)
Swap page.
Parameters
Address Address of the page
Returns
true if swap was successful
false if swap was unsuccessful
Definition at line 51 of file pmm.cpp.
     {
         fixme("%p", Address);
         return false;
     }
References fixme.
Referenced by RequestPage(), and SwapPages().
SwapPages()
bool Memory::Physical::SwapPages (void * Address, size_t PageCount)
Swap pages.
Parameters
Address Address of the pages
PageCount Number of pages
Returns
true if swap was successful
false if swap was unsuccessful
Definition at line 57 of file pmm.cpp.
     {
         for (size_t i = 0; i < PageCount; i++)
         {
             if (!this->SwapPage((void *)((uintptr_t)Address + (i * PAGE_SIZE))))
                 return false;
         }
         return false;
     }
References Address, i, PAGE_SIZE, and SwapPage().
Referenced by RequestPages().
UnreservePage()
void Memory::Physical::UnreservePage (void * Address)
Definition at line 273 of file pmm.cpp.
     {
         if (unlikely(Address == nullptr))
             warn("Trying to unreserve null address.");
         uintptr_t Index = (Address == NULL) ? 0 : (uintptr_t)Address / PAGE_SIZE;
         if (unlikely(PageBitmap[Index] == false))
             return;
         if (PageBitmap.Set(Index, false))
         {
             FreeMemory += PAGE_SIZE;
             ReservedMemory -= PAGE_SIZE;
             if (PageBitmapIndex > Index)
                 PageBitmapIndex = Index;
         }
     }
References Address, FreeMemory, NULL, PAGE_SIZE, PageBitmap, PageBitmapIndex, ReservedMemory, Bitmap::Set(), unlikely, and warn.
UnreservePages()
void Memory::Physical::UnreservePages (void * Address, size_t PageCount)
Definition at line 292 of file pmm.cpp.
     {
         if (unlikely(Address == nullptr || PageCount == 0))
             warn("Trying to unreserve %s%s.",
                  Address ? "null address" : "",
                  PageCount ? "0 pages" : "");
         for (size_t t = 0; t < PageCount; t++)
         {
             uintptr_t Index = ((uintptr_t)Address + (t * PAGE_SIZE)) / PAGE_SIZE;
             if (unlikely(PageBitmap[Index] == false))
                 return;
             if (PageBitmap.Set(Index, false))
             {
                 FreeMemory += PAGE_SIZE;
                 ReservedMemory -= PAGE_SIZE;
                 if (PageBitmapIndex > Index)
                     PageBitmapIndex = Index;
             }
         }
     }
References Address, FreeMemory, PAGE_SIZE, PageBitmap, PageBitmapIndex, ReservedMemory, Bitmap::Set(), t, unlikely, and warn.
UnswapPage()
bool Memory::Physical::UnswapPage (void * Address)
Unswap page.
Parameters
Address Address of the page
Returns
true if unswap was successful
false if unswap was unsuccessful
Definition at line 67 of file pmm.cpp.
     {
         fixme("%p", Address);
         return false;
     }
References Address, and fixme.
Referenced by UnswapPages().
UnswapPages()
bool Memory::Physical::UnswapPages (void * Address, size_t PageCount)
Unswap pages.
Parameters
Address Address of the pages
PageCount Number of pages
Returns
true if unswap was successful
false if unswap was unsuccessful
Definition at line 73 of file pmm.cpp.
     {
         for (size_t i = 0; i < PageCount; i++)
         {
             if (!this->UnswapPage((void *)((uintptr_t)Address + (i * PAGE_SIZE))))
                 return false;
         }
         return false;
     }
References Address, i, PAGE_SIZE, and UnswapPage().
Field Documentation
FreeMemory
std::atomic_uint64_t Memory::Physical::FreeMemory = 0 private
Definition at line 34 of file physical.hpp.
Referenced by FreePage(), GetFreeMemory(), Init(), LockPage(), RequestPage(), RequestPages(), ReservePage(), ReservePages(), UnreservePage(), and UnreservePages().
PageBitmap
Bitmap Memory::Physical::PageBitmap private
Definition at line 38 of file physical.hpp.
Referenced by FreePage(), GetPageBitmap(), Init(), LockPage(), RequestPage(), RequestPages(), ReservePage(), ReservePages(), UnreservePage(), and UnreservePages().
PageBitmapIndex
uint64_t Memory::Physical::PageBitmapIndex = 0 private
Definition at line 37 of file physical.hpp.
Referenced by FreePage(), RequestPage(), RequestPages(), UnreservePage(), and UnreservePages().
ReservedMemory
std::atomic_uint64_t Memory::Physical::ReservedMemory = 0 private
Definition at line 35 of file physical.hpp.
Referenced by GetReservedMemory(), RequestPage(), RequestPages(), ReservePage(), ReservePages(), UnreservePage(), and UnreservePages().
TotalMemory
std::atomic_uint64_t Memory::Physical::TotalMemory = 0 private
Definition at line 33 of file physical.hpp.
Referenced by GetTotalMemory(), and Init().
UsedMemory
std::atomic_uint64_t Memory::Physical::UsedMemory = 0 private
Definition at line 36 of file physical.hpp.
Referenced by FreePage(), GetUsedMemory(), LockPage(), RequestPage(), and RequestPages().
The documentation for this class was generated from the following files:
Kernel/include/memory/physical.hpp
Kernel/core/memory/pmm.cpp
Lynx/UEFI/src/Memory/PhysicalMemoryManager.cpp