Fennix: Userspace/mlibc/options/glibc/generic/err.cpp File Reference
err.cpp File Reference
#include <err.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
Functions
void vwarn (const char *fmt, va_list params)
void vwarnx (const char *fmt, va_list params)
__attribute__ ((noreturn)) void verr(int status
exit (status)
void warn (const char *fmt,...)
void warnx (const char *fmt,...)
const char va_start (params, fmt)
verr (status, fmt, params)
va_end (params)
verrx (status, fmt, params)
Variables
const char * fmt
const char va_list params
Function Documentation
__attribute__()
__attribute__ ((noreturn))
Definition at line 68 of file setjmp.c.
 {
     _exit(value);
 }
exit()
exit (status)
va_end()
va_end (params)
Referenced by __dl_seterr(), __dl_vseterr(), __mremap(), _rl_init_file_error(), arg_n(), asprintf(), builtin_error(), builtin_warning(), clone(), cprintf(), dprintf(), Driversprintf(), CrashHandler::EHPrint(), err(), error_impl(), errx(), execl(), execle(), execlp(), fatal_error(), fcntl(), fctprintf(), fctprintf_libinit(), fprintf(), fscanf(), fwprintf(), fwscanf(), I_Error(), init_log(), internal_debug(), internal_error(), internal_inform(), internal_warning(), ioctl(), KPrint(), SysDbg::LockedWrite(), SysDbg::LockedWriteLine(), M_snprintf(), M_StringJoin(), mq_open(), open(), openat(), parser_error(), prctl(), printf(), printf_(), printf_libinit(), programming_error(), ptrace(), report_error(), scanf(), sem_open(), semctl(), snprintf(), snprintf_(), snprintf_libinit(), sprintf(), sprintf_(), sprintf_libinit(), sscanf(), strfmon(), strfmon_l(), swprintf(), swscanf(), sys_error(), syscall(), SysDbgLockedWrite(), SysDbgLockedWriteLine(), SysDbgWrite(), SysDbgWriteLine(), syslog(), ulimit(), vasprintf(), vfprintf(), vfwprintf(), warn(), warnx(), wprintf(), SysDbg::Write(), SysDbg::WriteLine(), WriteRaw(), and wscanf().
va_start()
const char va_start (params , fmt)
Initial value:
{
    va_list params
Referenced by __dl_seterr(), __mremap(), _rl_init_file_error(), asprintf(), clone(), dprintf(), Driversprintf(), CrashHandler::EHPrint(), err(), error_impl(), errx(), execl(), execle(), execlp(), fcntl(), fctprintf(), fctprintf_libinit(), fprintf(), fscanf(), fwprintf(), fwscanf(), I_Error(), init_log(), ioctl(), KPrint(), SysDbg::LockedWrite(), SysDbg::LockedWriteLine(), M_snprintf(), M_StringJoin(), mq_open(), open(), openat(), prctl(), printf(), printf_(), printf_libinit(), ptrace(), scanf(), sem_open(), semctl(), snprintf(), snprintf_(), snprintf_libinit(), sprintf(), sprintf_(), sprintf_libinit(), sscanf(), strfmon(), strfmon_l(), swprintf(), swscanf(), syscall(), SysDbgLockedWrite(), SysDbgLockedWriteLine(), SysDbgWrite(), SysDbgWriteLine(), syslog(), ulimit(), warn(), warnx(), wprintf(), SysDbg::Write(), SysDbg::WriteLine(), WriteRaw(), and wscanf().
verr()
verr (status , fmt , params)
verrx()
verrx (status , fmt , params)
vwarn()
void vwarn (const char * fmt, va_list params)
Definition at line 9 of file err.cpp.
{
     fprintf(stderr, "%s: ", program_invocation_short_name);
     if (fmt) {
         vfprintf(stderr, fmt, params);
                 fwrite(": ", 1, 2, stderr);
     }
     perror(NULL);
 }
References fmt, fprintf(), fwrite(), NULL, params, perror(), program_invocation_short_name, stderr, and vfprintf().
Referenced by warn().
vwarnx()
void vwarnx (const char * fmt, va_list params)
Definition at line 18 of file err.cpp.
{
     fprintf(stderr, "%s: ", program_invocation_short_name);
     if (fmt) {
         vfprintf(stderr, fmt, params);
     }
     putc('\n', stderr);
 }
References fmt, fprintf(), params, program_invocation_short_name, putc(), stderr, and vfprintf().
Referenced by warnx().
warn()
void warn (const char * fmt, ...)
Definition at line 38 of file err.cpp.
{
     va_list params;
     va_start(params, fmt);
     vwarn(fmt, params);
     va_end(params);
 }
References fmt, params, va_end(), va_start(), and vwarn().
warnx()
void warnx (const char * fmt, ...)
Definition at line 45 of file err.cpp.
{
     va_list params;
     va_start(params, fmt);
     vwarnx(fmt, params);
     va_end(params);
 }
References fmt, params, va_end(), va_start(), and vwarnx().
Variable Documentation
fmt
const char * fmt
Definition at line 26 of file err.cpp.
Referenced by __dl_seterr(), __dl_vseterr(), __strftime_fmt_1(), asprintf(), do_scanf(), dprintf(), err(), error_impl(), errx(), fprintf(), fscanf(), fwprintf(), fwscanf(), getdate(), init_log(), loadstat(), long_double_format(), print_fltseq(), printf(), printf_core(), scanf(), snprintf(), sprintf(), sscanf(), stattime(), statval(), strfmon(), strfmon_l(), swprintf(), swscanf(), vasprintf(), vdprintf(), verr(), verrx(), vfprintf(), vfscanf(), vfwprintf(), vfwscanf(), vprintf(), vscanf(), vsnprintf(), vsprintf(), vsscanf(), vstrfmon_l(), vswprintf(), vswscanf(), vwarn(), vwarnx(), vwprintf(), vwscanf(), warn(), warnx(), wprintf(), wprintf_core(), and wscanf().
params
const char va_list params
Initial value:
{
    vwarn(fmt, params)
Definition at line 26 of file err.cpp.
Referenced by create_slice(), CrashHandler::DisplayMainScreen(), PageFaultExceptionHandler(), pos_params(), pos_params_modcase(), pos_params_pat_subst(), Queue::Queue(), Queue::recreateQueue(), UserModeExceptionHandler(), vwarn(), vwarnx(), warn(), and warnx().