Fennix: Kernel/include/printf.h File Reference
printf.h File Reference
#include <types.h>
Macros
#define ATTR_PRINTF((one_based_format_index) , (first_arg))
Small stand-alone implementation of the printf family of functions ((v)printf, (v)s(n)printf etc., geared towards use on embedded systems with a very limited resources.
#define ATTR_VPRINTF(one_based_format_index)
#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES 0
#define PRINTF_VISIBILITY
Functions
PRINTF_VISIBILITY int fctprintf (void(*out)(char c, void *extra_arg), void *extra_arg, const char *format,...) ATTR_PRINTF(3
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vfctprintf (void(*out)(char c, void *extra_arg), void *extra_arg, const char *format, va_list arg) ATTR_VPRINTF(3)
PRINTF_VISIBILITY int printf (const char *format,...) ATTR_PRINTF(1
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vprintf (const char *format, va_list arg) ATTR_VPRINTF(1)
PRINTF_VISIBILITY int sprintf (char *s, const char *format,...) ATTR_PRINTF(2
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vsprintf (char *s, const char *format, va_list arg) ATTR_VPRINTF(2)
PRINTF_VISIBILITY int snprintf (char *s, size_t count, const char *format,...) ATTR_PRINTF(3
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vsnprintf (char *s, size_t count, const char *format, va_list arg) ATTR_VPRINTF(3)
Macro Definition Documentation
ATTR_PRINTF
#define ATTR_PRINTF () , (first_arg))
Small stand-alone implementation of the printf family of functions ((v)printf, (v)s(n)printf etc., geared towards use on embedded systems with a very limited resources.
Author
(c) Eyal Rozenberg eyalr.nosp@m.oz1@.nosp@m.gmx.c.nosp@m.om 2021-2022, Haifa, Palestine/Israel
(c) Marco Paland (info@.nosp@m.pala.nosp@m.nd.co.nosp@m.m) 2014-2019, PALANDesign Hannover, Germany
Note
Others have made smaller contributions to this file: see the contributors page at https://github.com/eyalroz/printf/graphs/contributors or ask one of the authors.
the implementations are thread-safe; re-entrant; use no functions from the standard library; and do not dynamically allocate any memory.
@license The MIT License (MIT)
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 97 of file printf.h.
ATTR_VPRINTF
#define ATTR_VPRINTF (one_based_format_index)
PRINTF_ALIAS_STANDARD_FUNCTION_NAMES
#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES 0
PRINTF_VISIBILITY
#define PRINTF_VISIBILITY
Function Documentation
fctprintf()
PRINTF_VISIBILITY int fctprintf (void(*)(char c, void *extra_arg) out, void * extra_arg, const char * format, ...)
printf/vprintf with user-specified output function
An alternative to printf, in which the output function is specified dynamically (rather than putchar_ being used)
Parameters
out An output function which takes one character and a type-erased additional parameters
extra_arg The type-erased argument to pass to the output function out with each call
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters for which the output f unction was invoked, not counting the terminating null character
Referenced by __cyg_profile_func_enter(), __cyg_profile_func_exit(), Driver::KernelLog(), and WritePrefix().
printf()
PRINTF_VISIBILITY int printf (const char * format, ...)
An implementation of the C standard's printf/vprintf
Note
you must implement a putchar_ function for using this function - it invokes putchar_ rather than directly performing any I/O (which insulates it from any dependence on the operating system and external libraries).
Parameters
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each %-specifier in format string
Returns
The number of characters written into s, not counting the terminating null character
snprintf()
PRINTF_VISIBILITY int snprintf (char * s, size_t count, const char * format, ...)
An implementation of the C standard's snprintf/vsnprintf
Parameters
s An array in which to store the formatted string. It must be large enough to fit either the entire formatted output, or at least n characters. Alternatively, it can be NULL, in which case nothing will be printed, and only the number of characters which could have been printed is tallied and returned.
n The maximum number of characters to write to the array, including a terminating null character
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters that COULD have been written into s, not counting the terminating null character. A value equal or larger than n indicates truncation. Only when the returned value is non-negative and less than n, the null-terminated string has been fully and successfully printed.
Referenced by __asctime_r(), __dlsym_redir_time64(), __ptsname_r(), __strftime_fmt_1(), _remove_directory(), _vsyslog(), action_compat(), action_copy(), action_execute(), confstr(), copy_inode(), dcngettext(), display_header(), display_process_list(), fmt_num(), format_edit_status(), genformat(), get_epochrealtime(), getspnam_r(), hist_inittime(), inet_ntoa(), inet_ntop(), is_ide_cdrom_or_tape(), j_strsignal(), ll_addr_n2a(), ll_proto_n2a(), load_library(), main(), may_wakeup(), octalperms(), open_by_path_or_target(), openpty(), parse_fac_prio_20(), partname(), path_open(), print_intseq(), print_rate(), printable_job_status(), process_action(), pthread_getname_np(), pthread_setname_np(), read_cmdline(), regerror(), remove_pidfile_std_path_and_ext(), sem_open(), send_headers(), service(), shell_version_string(), show_entry(), statperms(), vfwscanf(), vstrfmon_l(), wprintf_core(), and write_pidfile_std_path_and_ext().
sprintf()
PRINTF_VISIBILITY int sprintf (char * s, const char * format, ...)
An implementation of the C standard's sprintf/vsprintf
Note
For security considerations (the potential for exceeding the buffer bounds), please consider using the size-constrained variant, snprintf / vsnprintf , instead.
Parameters
s An array in which to store the formatted string. It must be large enough to fit the formatted output!
format A string specifying the format of the output, with %-marked specifiers of how to interpret additional arguments.
arg Additional arguments to the function, one for each specifier in format
Returns
The number of characters written into s, not counting the terminating null character
Referenced by _rl_get_string_variable_value(), action_compat(), add_to_index(), archivejoin(), arith_apply(), awk_printf(), cal_main(), cdesc(), chksum_and_xwrite_tar_header(), chs_string11(), collect_tv(), com_list(), com_view(), conf_get_default_confname(), conf_write(), conspy_main(), conv_c(), cprintf(), create_directory(), create_file(), cttyhack_main(), curtime(), date_main(), decode_prompt_string(), dfallback(), display_process_list(), dump_procs(), dump_tree(), ecvt(), ether_ntoa_r(), execute_all(), expand_variable(), expand_vars_to_list(), expbackq(), expr_print(), fcvt(), Disk::Manager::FetchDisks(), fill_envp(), filter_rename_config(), fmt_time_human_30nul(), format_line(), gather_options_str(), gcvt(), genformat(), get_local_var_value(), get_next_free_loop(), get_old_name(), get_prompt(), handle_size_or_mdtm(), header_verbose_list(), hist_inittime(), human_time(), i2c_dev_open(), idle_string(), init_exec(), init_main_window(), init_signames(), initialize_siglist(), initialize_signames(), iso_8601_2000_year(), j_strsignal(), list_devs_in_proc_partititons(), list_table(), ll_type_n2a(), locale_charset(), log_locally(), logger_main(), losetup_main(), lsof_main(), mailstat(), main(), maybe_up_new_iface(), mkfs_vfat_main(), mkptr4(), mount_namespaces(), nbdclient_main(), openvt_main(), out_args(), parse(), parse_conf(), parse_conf_file(), pid_is_exec(), pid_is_name(), pid_is_user(), place_cursor(), powertop_main(), print_addrinfo(), process_irq_counts(), process_timer_stats(), procps_scan(), ps_main(), purge_package(), push_filename(), pwdx_main(), raise_error_unexpected_syntax(), re_execute_shell(), read_cmdline(), read_cstate_counts(), Driver::MasterDeviceFile::Register(), remove_package(), rfkill_main(), rl_display_search(), rl_invoking_keyseqs_in_map(), rl_message(), rl_redisplay(), rtnl_tab_initialize(), scan_request(), scan_table(), send_file_and_exit(), send_headers(), sh_mktmpdir(), sh_mktmpfd(), sh_mktmpname(), sh_set_lines_and_columns(), sha256crypt(), sha512crypt(), sha_crypt(), shell_version_string(), show_entry(), sprint_nip(), sprint_nip6(), strerror(), strftime(), string_var_assignment(), sym_validate_range(), Tasking::Task::Task(), timestamp_and_log(), tokname(), MediaAccessControl::ToString(), InternetProtocol::Version4::ToStringBigEndian(), InternetProtocol::Version6::ToStringBigEndian(), InternetProtocol::Version4::ToStringLittleEndian(), InternetProtocol::Version6::ToStringLittleEndian(), ttyname_r(), ubi_get_volid_by_name(), ubi_tools_main(), unshare_main(), UNSPEC_print(), unzip_main(), update_status(), volume_id_set_uuid(), wget_main(), write_helpfiles(), write_longdocs(), write_old_sd_name(), writeheader(), xmalloc_optname_optval(), and xxd_main().
vfctprintf()
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vfctprintf (void(*)(char c, void *extra_arg) out, void * extra_arg, const char * format, va_list arg)
Definition at line 1552 of file printf.c.
 {
     output_gadget_t gadget = function_gadget(out, extra_arg);
     return vsnprintf_impl(&gadget, format, arg);
 }
References format(), function_gadget(), out(), and vsnprintf_impl().
Referenced by CrashHandler::EHPrint(), Driver::KernelLog(), KPrint(), SysDbg::LockedWrite(), SysDbg::LockedWriteLine(), SysDbgLockedWrite(), SysDbgLockedWriteLine(), SysDbgWrite(), SysDbgWriteLine(), vprintf_dumper(), SysDbg::Write(), SysDbg::WriteLine(), and WritePrefix().
vprintf()
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vprintf (const char * format, va_list arg)
Definition at line 1535 of file printf.c.
 {
     output_gadget_t gadget = extern_putchar_gadget();
     return vsnprintf_impl(&gadget, format, arg);
 }
References extern_putchar_gadget(), format(), and vsnprintf_impl().
Referenced by _KPrint(), fprintf(), and out1fmt().
vsnprintf()
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vsnprintf (char * s, size_t count, const char * format, va_list arg)
Definition at line 1541 of file printf.c.
 {
     output_gadget_t gadget = buffer_gadget(s, n);
     return vsnprintf_impl(&gadget, format, arg);
 }
References buffer_gadget(), format(), n, s, and vsnprintf_impl().
Referenced by __dl_vseterr(), _vsyslog(), bb_verror_msg(), die(), fmtstr(), M_vsnprintf(), message(), say(), status_line(), status_line_bold(), str_printf(), vasprintf(), vsprintf(), and wrapf().
vsprintf()
PRINTF_VISIBILITY int PRINTF_VISIBILITY int vsprintf (char * s, const char * format, va_list arg)
Definition at line 1547 of file printf.c.
 {
     return vsnprintf(s, PRINTF_MAX_POSSIBLE_BUFFER_SIZE, format, arg);
 }
References format(), PRINTF_MAX_POSSIBLE_BUFFER_SIZE, s, and vsnprintf().
Referenced by cprint(), cprint1(), and sprintf().