Fennix: Userspace/musl/src/thread/pthread_rwlock_timedwrlock.c File Reference
pthread_rwlock_timedwrlock.c File Reference
#include "pthread_impl.h"
Functions
int __pthread_rwlock_timedwrlock (pthread_rwlock_t *restrict rw, const struct timespec *restrict at)
weak_alias (__pthread_rwlock_timedwrlock, pthread_rwlock_timedwrlock)
Function Documentation
__pthread_rwlock_timedwrlock()
int __pthread_rwlock_timedwrlock (pthread_rwlock_t *restrict rw, const struct timespec *restrict at)
Definition at line 3 of file pthread_rwlock_timedwrlock.c.
 {
     int r, t;
     r = pthread_rwlock_trywrlock(rw);
     if (r != EBUSY) return r;
     int spins = 100;
     while (spins-- && rw->_rw_lock && !rw->_rw_waiters) a_spin();
     while ((r=__pthread_rwlock_trywrlock(rw))==EBUSY) {
         if (!(r=rw->_rw_lock)) continue;
         t = r | 0x80000000;
         a_inc(&rw->_rw_waiters);
         a_cas(&rw->_rw_lock, r, t);
         r = __timedwait(&rw->_rw_lock, t, CLOCK_REALTIME, at, rw->_rw_shared^128);
         a_dec(&rw->_rw_waiters);
         if (r && r != EINTR) return r;
     }
     return r;
 }
References __pthread_rwlock_trywrlock(), __timedwait(), a_cas, a_dec, a_inc, a_spin, EBUSY, EINTR, pthread_rwlock_trywrlock(), and t.
weak_alias()
weak_alias (__pthread_rwlock_timedwrlock , pthread_rwlock_timedwrlock)