Fennix: Userspace/apps/base/bash/lib/sh/dprintf.c File Reference
dprintf.c File Reference
#include <stdc.h>
#include <varargs.h>
#include <stdio.h>
Functions
int dprintf (int fd, const char *format, va_alist)
Function Documentation
dprintf()
int dprintf (int fd, const char * format, va_alist)
Definition at line 43 of file dprintf.c.
 {
   FILE *fp;
   int fd2, rc, r2;
   va_list args;
   if ((fd2 = dup(fd)) < 0)
     return -1;
   fp = fdopen (fd2, "w");
   if (fp == 0)
     {
       close (fd2);
       return -1;
     }
   SH_VA_START (args, format);
   rc = vfprintf (fp, format, args);
   fflush (fp);
   va_end (args);
   r2 = fclose (fp); /* check here */
   return rc;
 }
References args, close(), dup(), fclose(), fdopen(), fflush(), format, r2, SH_VA_START, va_end(), and vfprintf().
Referenced by __attribute__(), __dls3(), _vsyslog(), error_impl(), fmtmsg(), getpass(), load_library(), main(), preInit1(), and preInit2().