Fennix Userspace: Userspace/musl/src/termios/cfgetospeed.c File Reference
cfgetospeed.c File Reference
#include <termios.h>
#include <sys/ioctl.h>
Macros
#define _BSD_SOURCE
Functions
speed_t cfgetospeed (const struct termios *tio)
speed_t cfgetispeed (const struct termios *tio)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 1 of file cfgetospeed.c.
Function Documentation
cfgetispeed()
speed_t cfgetispeed (const struct termios * tio)
Definition at line 10 of file cfgetospeed.c.
 {
     return cfgetospeed(tio);
 }
References cfgetospeed(), and tio.
Referenced by display_speed(), and slattach_main().
cfgetospeed()
speed_t cfgetospeed (const struct termios * tio)
Definition at line 5 of file cfgetospeed.c.
 {
     return tio->c_cflag & CBAUD;
 }
References CBAUD, and tio.
Referenced by cfgetispeed(), display_speed(), and slattach_main().