Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/m_menu.c File Reference
m_menu.c File Reference
#include <stdlib.h>
#include <ctype.h>
#include "doomdef.h"
#include "doomkeys.h"
#include "dstrings.h"
#include "d_main.h"
#include "deh_main.h"
#include "i_swap.h"
#include "i_system.h"
#include "i_timer.h"
#include "i_video.h"
#include "m_misc.h"
#include "v_video.h"
#include "w_wad.h"
#include "z_zone.h"
#include "r_local.h"
#include "hu_stuff.h"
#include "g_game.h"
#include "m_argv.h"
#include "m_controls.h"
#include "p_saveg.h"
#include "s_sound.h"
#include "doomstat.h"
#include "sounds.h"
#include "m_menu.h"
Data Structures
struct menuitem_t
struct menu_s
Macros
#define SKULLXOFF -32
#define LINEHEIGHT 16
Typedefs
typedef struct menu_s menu_t
Enumerations
enum {
newgame = 0 , options , loadgame , savegame ,
readthis , quitdoom , main_end
}
enum {
ep1 , ep2 , ep3 , ep4 ,
ep_end
}
enum {
killthings , toorough , hurtme , violence ,
nightmare , newg_end
}
enum {
endgame , messages , detail , scrnsize ,
option_empty1 , mousesens , option_empty2 , soundvol ,
opt_end
}
enum { rdthsempty1 , read1_end }
enum { rdthsempty2 , read2_end }
enum {
sfx_vol , sfx_empty1 , music_vol , sfx_empty2 ,
sound_end
}
enum {
load1 , load2 , load3 , load4 ,
load5 , load6 , load_end
}
Functions
void M_NewGame (int choice)
void M_Episode (int choice)
void M_ChooseSkill (int choice)
void M_LoadGame (int choice)
void M_SaveGame (int choice)
void M_Options (int choice)
void M_EndGame (int choice)
void M_ReadThis (int choice)
void M_ReadThis2 (int choice)
void M_QuitDOOM (int choice)
void M_ChangeMessages (int choice)
void M_ChangeSensitivity (int choice)
void M_SfxVol (int choice)
void M_MusicVol (int choice)
void M_ChangeDetail (int choice)
void M_SizeDisplay (int choice)
void M_StartGame (int choice)
void M_Sound (int choice)
void M_FinishReadThis (int choice)
void M_LoadSelect (int choice)
void M_SaveSelect (int choice)
void M_ReadSaveStrings (void)
void M_QuickSave (void)
void M_QuickLoad (void)
void M_DrawMainMenu (void)
void M_DrawReadThis1 (void)
void M_DrawReadThis2 (void)
void M_DrawNewGame (void)
void M_DrawEpisode (void)
void M_DrawOptions (void)
void M_DrawSound (void)
void M_DrawLoad (void)
void M_DrawSave (void)
void M_DrawSaveLoadBorder (int x, int y)
void M_SetupNextMenu (menu_t *menudef)
void M_DrawThermo (int x, int y, int thermWidth, int thermDot)
void M_DrawEmptyCell (menu_t *menu, int item)
void M_DrawSelCell (menu_t *menu, int item)
void M_WriteText (int x, int y, char *string)
int M_StringWidth (char *string)
int M_StringHeight (char *string)
void M_StartMessage (char *string, void *routine, boolean input)
void M_StopMessage (void)
void M_ClearMenus (void)
void M_DoSave (int slot)
void M_QuickSaveResponse (int key)
void M_QuickLoadResponse (int key)
void M_VerifyNightmare (int key)
void M_EndGameResponse (int key)
void M_QuitResponse (int key)
static char * M_SelectEndMessage (void)
static boolean IsNullKey (int key)
boolean M_Responder (event_t *ev)
void M_StartControlPanel (void)
void M_Drawer (void)
void M_Ticker (void)
void M_Init (void)
Variables
patch_t * hu_font [HU_FONTSIZE]
boolean message_dontfuckwithme
boolean chat_on
int mouseSensitivity = 5
int showMessages = 1
int detailLevel = 0
int screenblocks = 10
int screenSize
int quickSaveSlot
int messageToPrint
char * messageString
int messx
int messy
int messageLastMenuActive
boolean messageNeedsInput
void(* messageRoutine)(int response)
char gammamsg [5][26]
int saveStringEnter
int saveSlot
int saveCharIndex
char saveOldString [SAVESTRINGSIZE]
boolean inhelpscreens
boolean menuactive
boolean sendpause
char savegamestrings [10][SAVESTRINGSIZE]
char endstring [160]
short itemOn
short skullAnimCounter
short whichSkull
char * skullName [2] = {"M_SKULL1","M_SKULL2"}
menu_t * currentMenu
enum { ... } main_e
menuitem_t MainMenu []
menu_t MainDef
enum { ... } episodes_e
menuitem_t EpisodeMenu []
menu_t EpiDef
enum { ... } newgame_e
menuitem_t NewGameMenu []
menu_t NewDef
enum { ... } options_e
menuitem_t OptionsMenu []
menu_t OptionsDef
enum { ... } read_e
menuitem_t ReadMenu1 []
menu_t ReadDef1
enum { ... } read_e2
menuitem_t ReadMenu2 []
menu_t ReadDef2
enum { ... } sound_e
menuitem_t SoundMenu []
menu_t SoundDef
enum { ... } load_e
menuitem_t LoadMenu []
menu_t LoadDef
menuitem_t SaveMenu []
menu_t SaveDef
char tempstring [80]
int epi
static char * detailNames [2] = {"M_GDHIGH","M_GDLOW"}
static char * msgNames [2] = {"M_MSGOFF","M_MSGON"}
int quitsounds [8]
int quitsounds2 [8]
Macro Definition Documentation
LINEHEIGHT
#define LINEHEIGHT 16
Definition at line 121 of file m_menu.c.
SKULLXOFF
#define SKULLXOFF -32
Definition at line 120 of file m_menu.c.
Typedef Documentation
menu_t
typedef struct menu_s menu_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
endgame
messages
detail
scrnsize
option_empty1
mousesens
option_empty2
soundvol
opt_end
Definition at line 331 of file m_menu.c.
 {
     endgame,
     messages,
     detail,
     scrnsize,
     option_empty1,
     mousesens,
     option_empty2,
     soundvol,
     opt_end
 } options_e;
anonymous enum
anonymous enum
Enumerator
rdthsempty1
read1_end
Definition at line 369 of file m_menu.c.
 {
     rdthsempty1,
     read1_end
 } read_e;
anonymous enum
anonymous enum
Enumerator
rdthsempty2
read2_end
Definition at line 390 of file m_menu.c.
 {
     rdthsempty2,
     read2_end
 } read_e2;
anonymous enum
anonymous enum
Enumerator
sfx_vol
sfx_empty1
music_vol
sfx_empty2
sound_end
Definition at line 414 of file m_menu.c.
 {
     sfx_vol,
     sfx_empty1,
     music_vol,
     sfx_empty2,
     sound_end
 } sound_e;
anonymous enum
anonymous enum
Enumerator
load1
load2
load3
load4
load5
load6
load_end
Definition at line 444 of file m_menu.c.
 {
     load1,
     load2,
     load3,
     load4,
     load5,
     load6,
     load_end
 } load_e;
anonymous enum
anonymous enum
Enumerator
newgame
options
loadgame
savegame
readthis
quitdoom
main_end
Definition at line 231 of file m_menu.c.
 {
     newgame = 0,
     options,
     loadgame,
     savegame,
     readthis,
     quitdoom,
     main_end
 } main_e;
anonymous enum
anonymous enum
Enumerator
ep1
ep2
ep3
ep4
ep_end
Definition at line 267 of file m_menu.c.
 {
     ep1,
     ep2,
     ep3,
     ep4,
     ep_end
 } episodes_e;
anonymous enum
anonymous enum
Enumerator
killthings
toorough
hurtme
violence
nightmare
newg_end
Definition at line 297 of file m_menu.c.
 {
     killthings,
     toorough,
     hurtme,
     violence,
     nightmare,
     newg_end
 } newgame_e;
Function Documentation
IsNullKey()
static boolean IsNullKey (int key) static
Definition at line 1403 of file m_menu.c.
 {
     return key == KEY_PAUSE || key == KEY_CAPSLOCK
         || key == KEY_SCRLCK || key == KEY_NUMLOCK;
 }
References KEY_CAPSLOCK, KEY_NUMLOCK, KEY_PAUSE, and KEY_SCRLCK.
Referenced by M_Responder().
M_ChangeDetail()
void M_ChangeDetail (int choice)
Definition at line 1197 of file m_menu.c.
 {
     choice = 0;
     detailLevel = 1 - detailLevel;
     R_SetViewSize (screenblocks, detailLevel);
     if (!detailLevel)
     players[consoleplayer].message = DEH_String(DETAILHI);
     else
     players[consoleplayer].message = DEH_String(DETAILLO);
 }
References consoleplayer, DEH_String, DETAILHI, detailLevel, DETAILLO, player_s::message, players, R_SetViewSize(), and screenblocks.
Referenced by M_Responder().
M_ChangeMessages()
void M_ChangeMessages (int choice)
Definition at line 1017 of file m_menu.c.
 {
     // warning: unused parameter `int choice'
     choice = 0;
     showMessages = 1 - showMessages;
     if (!showMessages)
     players[consoleplayer].message = DEH_String(MSGOFF);
     else
     players[consoleplayer].message = DEH_String(MSGON);
     message_dontfuckwithme = true;
 }
References consoleplayer, DEH_String, player_s::message, message_dontfuckwithme, MSGOFF, MSGON, players, and showMessages.
Referenced by M_Responder().
M_ChangeSensitivity()
void M_ChangeSensitivity (int choice)
Definition at line 1179 of file m_menu.c.
 {
     switch(choice)
     {
       case 0:
     if (mouseSensitivity)
         mouseSensitivity--;
     break;
       case 1:
     if (mouseSensitivity < 9)
         mouseSensitivity++;
     break;
     }
 }
References mouseSensitivity.
M_ChooseSkill()
void M_ChooseSkill (int choice)
Definition at line 944 of file m_menu.c.
 {
     if (choice == nightmare)
     {
     M_StartMessage(DEH_String(NIGHTMARE),M_VerifyNightmare,true);
     return;
     }
     G_DeferedInitNew(choice,epi+1,1);
     M_ClearMenus ();
 }
References DEH_String, epi, G_DeferedInitNew(), M_ClearMenus(), M_StartMessage(), M_VerifyNightmare(), NIGHTMARE, and nightmare.
M_ClearMenus()
void M_ClearMenus (void)
Definition at line 2041 of file m_menu.c.
 {
     menuactive = 0;
     // if (!netgame && usergame && paused)
     //       sendpause = true;
 }
References menuactive.
Referenced by M_ChooseSkill(), M_DoSave(), M_EndGameResponse(), M_LoadSelect(), M_Responder(), and M_VerifyNightmare().
M_DoSave()
void M_DoSave (int slot)
Definition at line 622 of file m_menu.c.
 {
     G_SaveGame (slot,savegamestrings[slot]);
     M_ClearMenus ();
     // PICK QUICKSAVE SLOT YET?
     if (quickSaveSlot == -2)
     quickSaveSlot = slot;
 }
References G_SaveGame(), M_ClearMenus(), quickSaveSlot, and savegamestrings.
Referenced by M_QuickSaveResponse(), and M_Responder().
M_DrawEmptyCell()
void M_DrawEmptyCell (menu_t * menu, int item)
Definition at line 1270 of file m_menu.c.
 {
     V_DrawPatchDirect(menu->x - 10, menu->y + item * LINEHEIGHT - 1,
                       W_CacheLumpName(DEH_String("M_CELL1"), PU_CACHE));
 }
References DEH_String, LINEHEIGHT, PU_CACHE, V_DrawPatchDirect(), W_CacheLumpName(), menu_s::x, and menu_s::y.
M_DrawEpisode()
void M_DrawEpisode (void)
Definition at line 930 of file m_menu.c.
 {
     V_DrawPatchDirect(54, 38, W_CacheLumpName(DEH_String("M_EPISOD"), PU_CACHE));
 }
References DEH_String, PU_CACHE, V_DrawPatchDirect(), and W_CacheLumpName().
M_Drawer()
void M_Drawer (void)
Definition at line 1951 of file m_menu.c.
 {
     static short    x;
     static short    y;
     unsigned int    i;
     unsigned int    max;
     char        string[80];
     char               *name;
     int         start;
     inhelpscreens = false;
     // Horiz. & Vertically center string and print it.
     if (messageToPrint)
     {
     start = 0;
     y = SCREENHEIGHT/2 - M_StringHeight(messageString) / 2;
     while (messageString[start] != '\0')
     {
         int foundnewline = 0;
             for (i = 0; i < strlen(messageString + start); i++)
             {
                 if (messageString[start + i] == '\n')
                 {
                     M_StringCopy(string, messageString + start,
                                  sizeof(string));
                     if (i < sizeof(string))
                     {
                         string[i] = '\0';
                     }
                     foundnewline = 1;
                     start += i + 1;
                     break;
                 }
             }
             if (!foundnewline)
             {
                 M_StringCopy(string, messageString + start, sizeof(string));
                 start += strlen(string);
             }
         x = SCREENWIDTH/2 - M_StringWidth(string) / 2;
         M_WriteText(x, y, string);
         y += SHORT(hu_font[0]->height);
     }
     return;
     }
     //if (opldev)
     //{
     //    M_DrawOPLDev();
     //}
     if (!menuactive)
     return;
     if (currentMenu->routine)
     currentMenu->routine();         // call Draw routine
     // DRAW MENU
     x = currentMenu->x;
     y = currentMenu->y;
     max = currentMenu->numitems;
     for (i=0;i<max;i++)
     {
         name = DEH_String(currentMenu->menuitems[i].name);
     if (name[0])
     {
         V_DrawPatchDirect (x, y, W_CacheLumpName(name, PU_CACHE));
     }
     y += LINEHEIGHT;
     }
     // DRAW SKULL
     V_DrawPatchDirect(x + SKULLXOFF, currentMenu->y - 5 + itemOn*LINEHEIGHT,
               W_CacheLumpName(DEH_String(skullName[whichSkull]),
                       PU_CACHE));
 }
References currentMenu, DEH_String, anonymous_namespace{search.cpp}::height(), hu_font, i, inhelpscreens, itemOn, LINEHEIGHT, M_StringCopy(), M_StringHeight(), M_StringWidth(), M_WriteText(), menuactive, menu_s::menuitems, messageString, messageToPrint, menuitem_t::name, name, menu_s::numitems, PU_CACHE, menu_s::routine, SCREENHEIGHT, SCREENWIDTH, SHORT, skullName, SKULLXOFF, strlen(), V_DrawPatchDirect(), W_CacheLumpName(), whichSkull, menu_s::x, x, y, and menu_s::y.
Referenced by D_Display().
M_DrawLoad()
void M_DrawLoad (void)
Definition at line 530 of file m_menu.c.
 {
     int             i;
     V_DrawPatchDirect(72, 28,
                       W_CacheLumpName(DEH_String("M_LOADG"), PU_CACHE));
     for (i = 0;i < load_end; i++)
     {
     M_DrawSaveLoadBorder(LoadDef.x,LoadDef.y+LINEHEIGHT*i);
     M_WriteText(LoadDef.x,LoadDef.y+LINEHEIGHT*i,savegamestrings[i]);
     }
 }
References DEH_String, i, LINEHEIGHT, load_end, LoadDef, M_DrawSaveLoadBorder(), M_WriteText(), PU_CACHE, savegamestrings, V_DrawPatchDirect(), W_CacheLumpName(), menu_s::x, and menu_s::y.
M_DrawMainMenu()
void M_DrawMainMenu (void)
Definition at line 890 of file m_menu.c.
 {
     V_DrawPatchDirect(94, 2,
                       W_CacheLumpName(DEH_String("M_DOOM"), PU_CACHE));
 }
References DEH_String, PU_CACHE, V_DrawPatchDirect(), and W_CacheLumpName().
M_DrawNewGame()
void M_DrawNewGame (void)
Definition at line 902 of file m_menu.c.
 {
     V_DrawPatchDirect(96, 14, W_CacheLumpName(DEH_String("M_NEWG"), PU_CACHE));
     V_DrawPatchDirect(54, 38, W_CacheLumpName(DEH_String("M_SKILL"), PU_CACHE));
 }
References DEH_String, PU_CACHE, V_DrawPatchDirect(), and W_CacheLumpName().
M_DrawOptions()
void M_DrawOptions (void)
Definition at line 987 of file m_menu.c.
 {
     V_DrawPatchDirect(108, 15, W_CacheLumpName(DEH_String("M_OPTTTL"),
                                                PU_CACHE));
     V_DrawPatchDirect(OptionsDef.x + 175, OptionsDef.y + LINEHEIGHT * detail,
               W_CacheLumpName(DEH_String(detailNames[detailLevel]),
                           PU_CACHE));
     V_DrawPatchDirect(OptionsDef.x + 120, OptionsDef.y + LINEHEIGHT * messages,
                       W_CacheLumpName(DEH_String(msgNames[showMessages]),
                                       PU_CACHE));
     M_DrawThermo(OptionsDef.x, OptionsDef.y + LINEHEIGHT * (mousesens + 1),
          10, mouseSensitivity);
     M_DrawThermo(OptionsDef.x,OptionsDef.y+LINEHEIGHT*(scrnsize+1),
          9,screenSize);
 }
References DEH_String, detail, detailLevel, detailNames, LINEHEIGHT, M_DrawThermo(), messages, mousesens, mouseSensitivity, msgNames, OptionsDef, PU_CACHE, screenSize, scrnsize, showMessages, V_DrawPatchDirect(), W_CacheLumpName(), menu_s::x, and menu_s::y.
M_DrawReadThis1()
void M_DrawReadThis1 (void)
Definition at line 743 of file m_menu.c.
 {
     char *lumpname = "CREDIT";
     int skullx = 330, skully = 175;
     inhelpscreens = true;
     // Different versions of Doom 1.9 work differently
     switch (gameversion)
     {
         case exe_doom_1_666:
         case exe_doom_1_7:
         case exe_doom_1_8:
         case exe_doom_1_9:
         case exe_hacx:
             if (gamemode == commercial)
             {
                 // Doom 2
                 lumpname = "HELP";
                 skullx = 330;
                 skully = 165;
             }
             else
             {
                 // Doom 1
                 // HELP2 is the first screen shown in Doom 1
                 lumpname = "HELP2";
                 skullx = 280;
                 skully = 185;
             }
             break;
         case exe_ultimate:
         case exe_chex:
             // Ultimate Doom always displays "HELP1".
             // Chex Quest version also uses "HELP1", even though it is based
             // on Final Doom.
             lumpname = "HELP1";
             break;
         case exe_final:
         case exe_final2:
             // Final Doom always displays "HELP".
             lumpname = "HELP";
             break;
         default:
             I_Error("Unhandled game version");
             break;
     }
     lumpname = DEH_String(lumpname);
     V_DrawPatchDirect (0, 0, W_CacheLumpName(lumpname, PU_CACHE));
     ReadDef1.x = skullx;
     ReadDef1.y = skully;
 }
References commercial, DEH_String, exe_chex, exe_doom_1_666, exe_doom_1_7, exe_doom_1_8, exe_doom_1_9, exe_final, exe_final2, exe_hacx, exe_ultimate, gamemode, gameversion, I_Error(), inhelpscreens, PU_CACHE, ReadDef1, V_DrawPatchDirect(), W_CacheLumpName(), menu_s::x, and menu_s::y.
M_DrawReadThis2()
void M_DrawReadThis2 (void)
Definition at line 820 of file m_menu.c.
 {
     inhelpscreens = true;
     // We only ever draw the second page if this is
     // gameversion == exe_doom_1_9 and gamemode == registered
     V_DrawPatchDirect(0, 0, W_CacheLumpName(DEH_String("HELP1"), PU_CACHE));
 }
References DEH_String, inhelpscreens, PU_CACHE, V_DrawPatchDirect(), and W_CacheLumpName().
M_DrawSave()
void M_DrawSave (void)
Definition at line 601 of file m_menu.c.
 {
     int             i;
     V_DrawPatchDirect(72, 28, W_CacheLumpName(DEH_String("M_SAVEG"), PU_CACHE));
     for (i = 0;i < load_end; i++)
     {
     M_DrawSaveLoadBorder(LoadDef.x,LoadDef.y+LINEHEIGHT*i);
     M_WriteText(LoadDef.x,LoadDef.y+LINEHEIGHT*i,savegamestrings[i]);
     }
     if (saveStringEnter)
     {
     i = M_StringWidth(savegamestrings[saveSlot]);
     M_WriteText(LoadDef.x + i,LoadDef.y+LINEHEIGHT*saveSlot,"_");
     }
 }
References DEH_String, i, LINEHEIGHT, load_end, LoadDef, M_DrawSaveLoadBorder(), M_StringWidth(), M_WriteText(), PU_CACHE, savegamestrings, saveSlot, saveStringEnter, V_DrawPatchDirect(), W_CacheLumpName(), menu_s::x, and menu_s::y.
M_DrawSaveLoadBorder()
void M_DrawSaveLoadBorder (int x, int y)
Definition at line 549 of file m_menu.c.
 {
     int             i;
     V_DrawPatchDirect(x - 8, y + 7,
                       W_CacheLumpName(DEH_String("M_LSLEFT"), PU_CACHE));
     for (i = 0;i < 24;i++)
     {
     V_DrawPatchDirect(x, y + 7,
                           W_CacheLumpName(DEH_String("M_LSCNTR"), PU_CACHE));
     x += 8;
     }
     V_DrawPatchDirect(x, y + 7,
                       W_CacheLumpName(DEH_String("M_LSRGHT"), PU_CACHE));
 }
References DEH_String, i, PU_CACHE, V_DrawPatchDirect(), W_CacheLumpName(), x, and y.
Referenced by M_DrawLoad(), and M_DrawSave().
M_DrawSelCell()
void M_DrawSelCell (menu_t * menu, int item)
Definition at line 1279 of file m_menu.c.
 {
     V_DrawPatchDirect(menu->x - 10, menu->y + item * LINEHEIGHT - 1,
                       W_CacheLumpName(DEH_String("M_CELL2"), PU_CACHE));
 }
References DEH_String, LINEHEIGHT, PU_CACHE, V_DrawPatchDirect(), W_CacheLumpName(), menu_s::x, and menu_s::y.
M_DrawSound()
void M_DrawSound (void)
Definition at line 834 of file m_menu.c.
 {
     V_DrawPatchDirect (60, 38, W_CacheLumpName(DEH_String("M_SVOL"), PU_CACHE));
     M_DrawThermo(SoundDef.x,SoundDef.y+LINEHEIGHT*(sfx_vol+1),
          16,sfxVolume);
     M_DrawThermo(SoundDef.x,SoundDef.y+LINEHEIGHT*(music_vol+1),
          16,musicVolume);
 }
References DEH_String, LINEHEIGHT, M_DrawThermo(), music_vol, musicVolume, PU_CACHE, sfx_vol, sfxVolume, SoundDef, V_DrawPatchDirect(), W_CacheLumpName(), menu_s::x, and menu_s::y.
M_DrawThermo()
void M_DrawThermo (int x, int y, int thermWidth, int thermDot)
Definition at line 1244 of file m_menu.c.
 {
     int     xx;
     int     i;
     xx = x;
     V_DrawPatchDirect(xx, y, W_CacheLumpName(DEH_String("M_THERML"), PU_CACHE));
     xx += 8;
     for (i=0;i<thermWidth;i++)
     {
     V_DrawPatchDirect(xx, y, W_CacheLumpName(DEH_String("M_THERMM"), PU_CACHE));
     xx += 8;
     }
     V_DrawPatchDirect(xx, y, W_CacheLumpName(DEH_String("M_THERMR"), PU_CACHE));
     V_DrawPatchDirect((x + 8) + thermDot * 8, y,
               W_CacheLumpName(DEH_String("M_THERMO"), PU_CACHE));
 }
References DEH_String, i, PU_CACHE, V_DrawPatchDirect(), W_CacheLumpName(), x, and y.
Referenced by M_DrawOptions(), and M_DrawSound().
M_EndGame()
void M_EndGame (int choice)
Definition at line 1045 of file m_menu.c.
 {
     choice = 0;
     if (!usergame)
     {
     S_StartSound(NULL,sfx_oof);
     return;
     }
     if (netgame)
     {
     M_StartMessage(DEH_String(NETEND),NULL,false);
     return;
     }
     M_StartMessage(DEH_String(ENDGAME),M_EndGameResponse,true);
 }
References DEH_String, ENDGAME, M_EndGameResponse(), M_StartMessage(), NETEND, netgame, NULL, S_StartSound(), sfx_oof, and usergame.
Referenced by M_Responder().
M_EndGameResponse()
void M_EndGameResponse (int key)
Definition at line 1035 of file m_menu.c.
 {
     if (key != key_menu_confirm)
     return;
     currentMenu->lastOn = itemOn;
     M_ClearMenus ();
     D_StartTitle ();
 }
References currentMenu, D_StartTitle(), itemOn, key_menu_confirm, menu_s::lastOn, and M_ClearMenus().
Referenced by M_EndGame().
M_Episode()
void M_Episode (int choice)
Definition at line 956 of file m_menu.c.
 {
     if ( (gamemode == shareware)
      && choice)
     {
     M_StartMessage(DEH_String(SWSTRING),NULL,false);
     M_SetupNextMenu(&ReadDef1);
     return;
     }
     // Yet another hack...
     if ( (gamemode == registered)
      && (choice > 2))
     {
       fprintf( stderr,
            "M_Episode: 4th episode requires UltimateDOOM\n");
       choice = 0;
     }
     epi = choice;
     M_SetupNextMenu(&NewDef);
 }
References DEH_String, epi, fprintf(), gamemode, M_SetupNextMenu(), M_StartMessage(), NewDef, NULL, ReadDef1, registered, shareware, stderr, and SWSTRING.
M_FinishReadThis()
void M_FinishReadThis (int choice)
Definition at line 1093 of file m_menu.c.
 {
     choice = 0;
     M_SetupNextMenu(&MainDef);
 }
References M_SetupNextMenu(), and MainDef.
Referenced by M_ReadThis2().
M_Init()
void M_Init (void)
Definition at line 2077 of file m_menu.c.
 {
     currentMenu = &MainDef;
     menuactive = 0;
     itemOn = currentMenu->lastOn;
     whichSkull = 0;
     skullAnimCounter = 10;
     screenSize = screenblocks - 3;
     messageToPrint = 0;
     messageString = NULL;
     messageLastMenuActive = menuactive;
     quickSaveSlot = -1;
     // Here we could catch other version dependencies,
     //  like HELP1/2, and four episodes.
     switch ( gamemode )
     {
       case commercial:
         // Commercial has no "read this" entry.
     MainMenu[readthis] = MainMenu[quitdoom];
     MainDef.numitems--;
     MainDef.y += 8;
     NewDef.prevMenu = &MainDef;
     break;
       case shareware:
     // Episode 2 and 3 are handled,
     //  branching to an ad screen.
       case registered:
     break;
       case retail:
     // We are fine.
       default:
     break;
     }
     // Versions of doom.exe before the Ultimate Doom release only had
     // three episodes; if we're emulating one of those then don't try
     // to show episode four. If we are, then do show episode four
     // (should crash if missing).
     if (gameversion < exe_ultimate)
     {
     EpiDef.numitems--;
     }
     //opldev = M_CheckParm("-opldev") > 0;
 }
References commercial, currentMenu, EpiDef, exe_ultimate, gamemode, gameversion, itemOn, menu_s::lastOn, MainDef, MainMenu, menuactive, messageLastMenuActive, messageString, messageToPrint, NewDef, NULL, menu_s::numitems, menu_s::prevMenu, quickSaveSlot, quitdoom, readthis, registered, retail, screenblocks, screenSize, shareware, skullAnimCounter, whichSkull, and menu_s::y.
Referenced by D_DoomMain().
M_LoadGame()
void M_LoadGame (int choice)
Definition at line 585 of file m_menu.c.
 {
     if (netgame)
     {
     M_StartMessage(DEH_String(LOADNET),NULL,false);
     return;
     }
     M_SetupNextMenu(&LoadDef);
     M_ReadSaveStrings();
 }
References DEH_String, LoadDef, LOADNET, M_ReadSaveStrings(), M_SetupNextMenu(), M_StartMessage(), netgame, and NULL.
Referenced by M_Responder().
M_LoadSelect()
void M_LoadSelect (int choice)
Definition at line 572 of file m_menu.c.
 {
     char    name[256];
     M_StringCopy(name, P_SaveGameFile(choice), sizeof(name));
     G_LoadGame (name);
     M_ClearMenus ();
 }
References G_LoadGame(), M_ClearMenus(), M_StringCopy(), name, and P_SaveGameFile().
Referenced by M_QuickLoadResponse().
M_MusicVol()
void M_MusicVol (int choice)
Definition at line 867 of file m_menu.c.
 {
     switch(choice)
     {
       case 0:
     if (musicVolume)
         musicVolume--;
     break;
       case 1:
     if (musicVolume < 15)
         musicVolume++;
     break;
     }
     S_SetMusicVolume(musicVolume * 8);
 }
References musicVolume, and S_SetMusicVolume().
M_NewGame()
void M_NewGame (int choice)
Definition at line 908 of file m_menu.c.
 {
     if (netgame && !demoplayback)
     {
     M_StartMessage(DEH_String(NEWGAME),NULL,false);
     return;
     }
     // Chex Quest disabled the episode select screen, as did Doom II.
     if (gamemode == commercial || gameversion == exe_chex)
     M_SetupNextMenu(&NewDef);
     else
     M_SetupNextMenu(&EpiDef);
 }
References commercial, DEH_String, demoplayback, EpiDef, exe_chex, gamemode, gameversion, M_SetupNextMenu(), M_StartMessage(), netgame, NewDef, NEWGAME, and NULL.
M_Options()
void M_Options (int choice)
Definition at line 1007 of file m_menu.c.
 {
     M_SetupNextMenu(&OptionsDef);
 }
References M_SetupNextMenu(), and OptionsDef.
M_QuickLoad()
void M_QuickLoad (void)
Definition at line 719 of file m_menu.c.
 {
     if (netgame)
     {
     M_StartMessage(DEH_String(QLOADNET),NULL,false);
     return;
     }
     if (quickSaveSlot < 0)
     {
     M_StartMessage(DEH_String(QSAVESPOT),NULL,false);
     return;
     }
     DEH_snprintf(tempstring, 80, QLPROMPT, savegamestrings[quickSaveSlot]);
     M_StartMessage(tempstring,M_QuickLoadResponse,true);
 }
References DEH_snprintf, DEH_String, M_QuickLoadResponse(), M_StartMessage(), netgame, NULL, QLOADNET, QLPROMPT, QSAVESPOT, quickSaveSlot, savegamestrings, and tempstring.
Referenced by M_Responder().
M_QuickLoadResponse()
void M_QuickLoadResponse (int key)
Definition at line 709 of file m_menu.c.
 {
     if (key == key_menu_confirm)
     {
     M_LoadSelect(quickSaveSlot);
     S_StartSound(NULL,sfx_swtchx);
     }
 }
References key_menu_confirm, M_LoadSelect(), NULL, quickSaveSlot, S_StartSound(), and sfx_swtchx.
Referenced by M_QuickLoad().
M_QuickSave()
void M_QuickSave (void)
Definition at line 681 of file m_menu.c.
 {
     if (!usergame)
     {
     S_StartSound(NULL,sfx_oof);
     return;
     }
     if (gamestate != GS_LEVEL)
     return;
     if (quickSaveSlot < 0)
     {
     M_StartControlPanel();
     M_ReadSaveStrings();
     M_SetupNextMenu(&SaveDef);
     quickSaveSlot = -2; // means to pick a slot now
     return;
     }
     DEH_snprintf(tempstring, 80, QSPROMPT, savegamestrings[quickSaveSlot]);
     M_StartMessage(tempstring,M_QuickSaveResponse,true);
 }
References DEH_snprintf, gamestate, GS_LEVEL, M_QuickSaveResponse(), M_ReadSaveStrings(), M_SetupNextMenu(), M_StartControlPanel(), M_StartMessage(), NULL, QSPROMPT, quickSaveSlot, S_StartSound(), SaveDef, savegamestrings, sfx_oof, tempstring, and usergame.
Referenced by M_Responder().
M_QuickSaveResponse()
void M_QuickSaveResponse (int key)
Definition at line 672 of file m_menu.c.
 {
     if (key == key_menu_confirm)
     {
     M_DoSave(quickSaveSlot);
     S_StartSound(NULL,sfx_swtchx);
     }
 }
References key_menu_confirm, M_DoSave(), NULL, quickSaveSlot, S_StartSound(), and sfx_swtchx.
Referenced by M_QuickSave().
M_QuitDOOM()
void M_QuitDOOM (int choice)
Definition at line 1168 of file m_menu.c.
 {
     DEH_snprintf(endstring, sizeof(endstring), "%s\n\n" DOSY,
                  DEH_String(M_SelectEndMessage()));
     M_StartMessage(endstring,M_QuitResponse,true);
 }
References DEH_snprintf, DEH_String, DOSY, endstring, M_QuitResponse(), M_SelectEndMessage(), and M_StartMessage().
Referenced by M_Responder().
M_QuitResponse()
void M_QuitResponse (int key)
Definition at line 1131 of file m_menu.c.
 {
     if (key != key_menu_confirm)
     return;
     if (!netgame)
     {
     if (gamemode == commercial)
         S_StartSound(NULL,quitsounds2[(gametic>>2)&7]);
     else
         S_StartSound(NULL,quitsounds[(gametic>>2)&7]);
     I_WaitVBL(105);
     }
     I_Quit ();
 }
References commercial, gamemode, gametic, I_Quit(), I_WaitVBL(), key_menu_confirm, netgame, NULL, quitsounds, quitsounds2, and S_StartSound().
Referenced by M_QuitDOOM(), and M_Responder().
M_ReadSaveStrings()
void M_ReadSaveStrings (void)
Definition at line 503 of file m_menu.c.
 {
     FILE   *handle;
     int     i;
     char    name[256];
     for (i = 0;i < load_end;i++)
     {
         M_StringCopy(name, P_SaveGameFile(i), sizeof(name));
     handle = fopen(name, "rb");
         if (handle == NULL)
         {
             M_StringCopy(savegamestrings[i], EMPTYSTRING, SAVESTRINGSIZE);
             LoadMenu[i].status = 0;
             continue;
         }
     fread(&savegamestrings[i], 1, SAVESTRINGSIZE, handle);
     fclose(handle);
     LoadMenu[i].status = 1;
     }
 }
References EMPTYSTRING, fclose(), fopen(), fread(), i, load_end, LoadMenu, M_StringCopy(), name, NULL, P_SaveGameFile(), savegamestrings, SAVESTRINGSIZE, and menuitem_t::status.
Referenced by M_LoadGame(), M_QuickSave(), and M_SaveGame().
M_ReadThis()
void M_ReadThis (int choice)
Definition at line 1069 of file m_menu.c.
 {
     choice = 0;
     M_SetupNextMenu(&ReadDef1);
 }
References M_SetupNextMenu(), and ReadDef1.
M_ReadThis2()
void M_ReadThis2 (int choice)
Definition at line 1075 of file m_menu.c.
 {
     // Doom 1.9 had two menus when playing Doom 1
     // All others had only one
     if (gameversion <= exe_doom_1_9 && gamemode != commercial)
     {
         choice = 0;
         M_SetupNextMenu(&ReadDef2);
     }
     else
     {
         // Close the menu
         M_FinishReadThis(0);
     }
 }
References commercial, exe_doom_1_9, gamemode, gameversion, M_FinishReadThis(), M_SetupNextMenu(), and ReadDef2.
M_Responder()
boolean M_Responder (event_t * ev)
Definition at line 1416 of file m_menu.c.
 {
     int             ch;
     int             key;
     int             i;
     static  int     joywait = 0;
     static  int     mousewait = 0;
     static  int     mousey = 0;
     static  int     lasty = 0;
     static  int     mousex = 0;
     static  int     lastx = 0;
     // In testcontrols mode, none of the function keys should do anything
     // - the only key is escape to quit.
     if (testcontrols)
     {
         if (ev->type == ev_quit
          || (ev->type == ev_keydown
           && (ev->data1 == key_menu_activate || ev->data1 == key_menu_quit)))
         {
             I_Quit();
             return true;
         }
         return false;
     }
     // "close" button pressed on window?
     if (ev->type == ev_quit)
     {
         // First click on close button = bring up quit confirm message.
         // Second click on close button = confirm quit
         if (menuactive && messageToPrint && messageRoutine == M_QuitResponse)
         {
             M_QuitResponse(key_menu_confirm);
         }
         else
         {
             S_StartSound(NULL,sfx_swtchn);
             M_QuitDOOM(0);
         }
         return true;
     }
     // key is the key pressed, ch is the actual character typed
     ch = 0;
     key = -1;
     if (ev->type == ev_joystick && joywait < I_GetTime())
     {
     if (ev->data3 < 0)
     {
         key = key_menu_up;
         joywait = I_GetTime() + 5;
     }
     else if (ev->data3 > 0)
     {
         key = key_menu_down;
         joywait = I_GetTime() + 5;
     }
     if (ev->data2 < 0)
     {
         key = key_menu_left;
         joywait = I_GetTime() + 2;
     }
     else if (ev->data2 > 0)
     {
         key = key_menu_right;
         joywait = I_GetTime() + 2;
     }
     if (ev->data1&1)
     {
         key = key_menu_forward;
         joywait = I_GetTime() + 5;
     }
     if (ev->data1&2)
     {
         key = key_menu_back;
         joywait = I_GetTime() + 5;
     }
         if (joybmenu >= 0 && (ev->data1 & (1 << joybmenu)) != 0)
         {
             key = key_menu_activate;
         joywait = I_GetTime() + 5;
         }
     }
     else
     {
     if (ev->type == ev_mouse && mousewait < I_GetTime())
     {
         mousey += ev->data3;
         if (mousey < lasty-30)
         {
         key = key_menu_down;
         mousewait = I_GetTime() + 5;
         mousey = lasty -= 30;
         }
         else if (mousey > lasty+30)
         {
         key = key_menu_up;
         mousewait = I_GetTime() + 5;
         mousey = lasty += 30;
         }
         mousex += ev->data2;
         if (mousex < lastx-30)
         {
         key = key_menu_left;
         mousewait = I_GetTime() + 5;
         mousex = lastx -= 30;
         }
         else if (mousex > lastx+30)
         {
         key = key_menu_right;
         mousewait = I_GetTime() + 5;
         mousex = lastx += 30;
         }
         if (ev->data1&1)
         {
         key = key_menu_forward;
         mousewait = I_GetTime() + 15;
         }
         if (ev->data1&2)
         {
         key = key_menu_back;
         mousewait = I_GetTime() + 15;
         }
     }
     else
     {
         if (ev->type == ev_keydown)
         {
         key = ev->data1;
         ch = ev->data2;
         }
     }
     }
     if (key == -1)
     return false;
     // Save Game string input
     if (saveStringEnter)
     {
     switch(key)
     {
       case KEY_BACKSPACE:
         if (saveCharIndex > 0)
         {
         saveCharIndex--;
         savegamestrings[saveSlot][saveCharIndex] = 0;
         }
         break;
           case KEY_ESCAPE:
             saveStringEnter = 0;
             M_StringCopy(savegamestrings[saveSlot], saveOldString,
                          SAVESTRINGSIZE);
             break;
       case KEY_ENTER:
         saveStringEnter = 0;
         if (savegamestrings[saveSlot][0])
         M_DoSave(saveSlot);
         break;
       default:
             // This is complicated.
             // Vanilla has a bug where the shift key is ignored when entering
             // a savegame name. If vanilla_keyboard_mapping is on, we want
             // to emulate this bug by using 'data1'. But if it's turned off,
             // it implies the user doesn't care about Vanilla emulation: just
             // use the correct 'data2'.
             if (vanilla_keyboard_mapping)
             {
                 ch = key;
             }
             ch = toupper(ch);
             if (ch != ' '
              && (ch - HU_FONTSTART < 0 || ch - HU_FONTSTART >= HU_FONTSIZE))
             {
                 break;
             }
         if (ch >= 32 && ch <= 127 &&
         saveCharIndex < SAVESTRINGSIZE-1 &&
         M_StringWidth(savegamestrings[saveSlot]) <
         (SAVESTRINGSIZE-2)*8)
         {
         savegamestrings[saveSlot][saveCharIndex++] = ch;
         savegamestrings[saveSlot][saveCharIndex] = 0;
         }
         break;
     }
     return true;
     }
     // Take care of any messages that need input
     if (messageToPrint)
     {
     if (messageNeedsInput)
         {
             if (key != ' ' && key != KEY_ESCAPE
              && key != key_menu_confirm && key != key_menu_abort)
             {
                 return false;
             }
     }
     menuactive = messageLastMenuActive;
     messageToPrint = 0;
     if (messageRoutine)
         messageRoutine(key);
     menuactive = false;
     S_StartSound(NULL,sfx_swtchx);
     return true;
     }
     if ((devparm && key == key_menu_help) ||
         (key != 0 && key == key_menu_screenshot))
     {
     G_ScreenShot ();
     return true;
     }
     // F-Keys
     if (!menuactive)
     {
     if (key == key_menu_decscreen)      // Screen size down
         {
         if (automapactive || chat_on)
         return false;
         M_SizeDisplay(0);
         S_StartSound(NULL,sfx_stnmov);
         return true;
     }
         else if (key == key_menu_incscreen) // Screen size up
         {
         if (automapactive || chat_on)
         return false;
         M_SizeDisplay(1);
         S_StartSound(NULL,sfx_stnmov);
         return true;
     }
         else if (key == key_menu_help)     // Help key
         {
         M_StartControlPanel ();
         if ( gamemode == retail )
           currentMenu = &ReadDef2;
         else
           currentMenu = &ReadDef1;
         itemOn = 0;
         S_StartSound(NULL,sfx_swtchn);
         return true;
     }
         else if (key == key_menu_save)     // Save
         {
         M_StartControlPanel();
         S_StartSound(NULL,sfx_swtchn);
         M_SaveGame(0);
         return true;
         }
         else if (key == key_menu_load)     // Load
         {
         M_StartControlPanel();
         S_StartSound(NULL,sfx_swtchn);
         M_LoadGame(0);
         return true;
         }
         else if (key == key_menu_volume)   // Sound Volume
         {
         M_StartControlPanel ();
         currentMenu = &SoundDef;
         itemOn = sfx_vol;
         S_StartSound(NULL,sfx_swtchn);
         return true;
     }
         else if (key == key_menu_detail)   // Detail toggle
         {
         M_ChangeDetail(0);
         S_StartSound(NULL,sfx_swtchn);
         return true;
         }
         else if (key == key_menu_qsave)    // Quicksave
         {
         S_StartSound(NULL,sfx_swtchn);
         M_QuickSave();
         return true;
         }
         else if (key == key_menu_endgame)  // End game
         {
         S_StartSound(NULL,sfx_swtchn);
         M_EndGame(0);
         return true;
         }
         else if (key == key_menu_messages) // Toggle messages
         {
         M_ChangeMessages(0);
         S_StartSound(NULL,sfx_swtchn);
         return true;
         }
         else if (key == key_menu_qload)    // Quickload
         {
         S_StartSound(NULL,sfx_swtchn);
         M_QuickLoad();
         return true;
         }
         else if (key == key_menu_quit)     // Quit DOOM
         {
         S_StartSound(NULL,sfx_swtchn);
         M_QuitDOOM(0);
         return true;
         }
         else if (key == key_menu_gamma)    // gamma toggle
         {
         usegamma++;
         if (usegamma > 4)
         usegamma = 0;
         players[consoleplayer].message = DEH_String(gammamsg[usegamma]);
             I_SetPalette (W_CacheLumpName (DEH_String("PLAYPAL"),PU_CACHE));
         return true;
     }
     }
     // Pop-up menu?
     if (!menuactive)
     {
     if (key == key_menu_activate)
     {
         M_StartControlPanel ();
         S_StartSound(NULL,sfx_swtchn);
         return true;
     }
     return false;
     }
     // Keys usable within menu
     if (key == key_menu_down)
     {
         // Move down to next item
         do
     {
         if (itemOn+1 > currentMenu->numitems-1)
         itemOn = 0;
         else itemOn++;
         S_StartSound(NULL,sfx_pstop);
     } while(currentMenu->menuitems[itemOn].status==-1);
     return true;
     }
     else if (key == key_menu_up)
     {
         // Move back up to previous item
     do
     {
         if (!itemOn)
         itemOn = currentMenu->numitems-1;
         else itemOn--;
         S_StartSound(NULL,sfx_pstop);
     } while(currentMenu->menuitems[itemOn].status==-1);
     return true;
     }
     else if (key == key_menu_left)
     {
         // Slide slider left
     if (currentMenu->menuitems[itemOn].routine &&
         currentMenu->menuitems[itemOn].status == 2)
     {
         S_StartSound(NULL,sfx_stnmov);
         currentMenu->menuitems[itemOn].routine(0);
     }
     return true;
     }
     else if (key == key_menu_right)
     {
         // Slide slider right
     if (currentMenu->menuitems[itemOn].routine &&
         currentMenu->menuitems[itemOn].status == 2)
     {
         S_StartSound(NULL,sfx_stnmov);
         currentMenu->menuitems[itemOn].routine(1);
     }
     return true;
     }
     else if (key == key_menu_forward)
     {
         // Activate menu item
     if (currentMenu->menuitems[itemOn].routine &&
         currentMenu->menuitems[itemOn].status)
     {
         currentMenu->lastOn = itemOn;
         if (currentMenu->menuitems[itemOn].status == 2)
         {
         currentMenu->menuitems[itemOn].routine(1);      // right arrow
         S_StartSound(NULL,sfx_stnmov);
         }
         else
         {
         currentMenu->menuitems[itemOn].routine(itemOn);
         S_StartSound(NULL,sfx_pistol);
         }
     }
     return true;
     }
     else if (key == key_menu_activate)
     {
         // Deactivate menu
     currentMenu->lastOn = itemOn;
     M_ClearMenus ();
     S_StartSound(NULL,sfx_swtchx);
     return true;
     }
     else if (key == key_menu_back)
     {
         // Go back to previous menu
     currentMenu->lastOn = itemOn;
     if (currentMenu->prevMenu)
     {
         currentMenu = currentMenu->prevMenu;
         itemOn = currentMenu->lastOn;
         S_StartSound(NULL,sfx_swtchn);
     }
     return true;
     }
     // Keyboard shortcut?
     // Vanilla Doom has a weird behavior where it jumps to the scroll bars
     // when the certain keys are pressed, so emulate this.
     else if (ch != 0 || IsNullKey(key))
     {
     for (i = itemOn+1;i < currentMenu->numitems;i++)
         {
         if (currentMenu->menuitems[i].alphaKey == ch)
         {
         itemOn = i;
         S_StartSound(NULL,sfx_pstop);
         return true;
         }
         }
     for (i = 0;i <= itemOn;i++)
         {
         if (currentMenu->menuitems[i].alphaKey == ch)
         {
         itemOn = i;
         S_StartSound(NULL,sfx_pstop);
         return true;
         }
         }
     }
     return false;
 }
References menuitem_t::alphaKey, automapactive, chat_on, consoleplayer, currentMenu, event_t::data1, event_t::data2, event_t::data3, DEH_String, devparm, ev_joystick, ev_keydown, ev_mouse, ev_quit, G_ScreenShot(), gamemode, gammamsg, HU_FONTSIZE, i, I_GetTime(), I_Quit(), I_SetPalette(), IsNullKey(), itemOn, joybmenu, KEY_BACKSPACE, KEY_ENTER, KEY_ESCAPE, key_menu_abort, key_menu_activate, key_menu_back, key_menu_confirm, key_menu_decscreen, key_menu_detail, key_menu_down, key_menu_endgame, key_menu_forward, key_menu_gamma, key_menu_help, key_menu_incscreen, key_menu_left, key_menu_load, key_menu_messages, key_menu_qload, key_menu_qsave, key_menu_quit, key_menu_right, key_menu_save, key_menu_screenshot, key_menu_up, key_menu_volume, menu_s::lastOn, M_ChangeDetail(), M_ChangeMessages(), M_ClearMenus(), M_DoSave(), M_EndGame(), M_LoadGame(), M_QuickLoad(), M_QuickSave(), M_QuitDOOM(), M_QuitResponse(), M_SaveGame(), M_SizeDisplay(), M_StartControlPanel(), M_StringCopy(), M_StringWidth(), menuactive, menu_s::menuitems, player_s::message, messageLastMenuActive, messageNeedsInput, messageRoutine, messageToPrint, mousex, mousey, NULL, menu_s::numitems, players, menu_s::prevMenu, PU_CACHE, ReadDef1, ReadDef2, retail, menuitem_t::routine, S_StartSound(), saveCharIndex, savegamestrings, saveOldString, saveSlot, saveStringEnter, SAVESTRINGSIZE, sfx_pistol, sfx_pstop, sfx_stnmov, sfx_swtchn, sfx_swtchx, sfx_vol, SoundDef, menuitem_t::status, testcontrols, toupper, event_t::type, usegamma, vanilla_keyboard_mapping, and W_CacheLumpName().
Referenced by D_ProcessEvents().
M_SaveGame()
void M_SaveGame (int choice)
Definition at line 650 of file m_menu.c.
 {
     if (!usergame)
     {
     M_StartMessage(DEH_String(SAVEDEAD),NULL,false);
     return;
     }
     if (gamestate != GS_LEVEL)
     return;
     M_SetupNextMenu(&SaveDef);
     M_ReadSaveStrings();
 }
References DEH_String, gamestate, GS_LEVEL, M_ReadSaveStrings(), M_SetupNextMenu(), M_StartMessage(), NULL, SAVEDEAD, SaveDef, and usergame.
Referenced by M_Responder().
M_SaveSelect()
void M_SaveSelect (int choice)
Definition at line 635 of file m_menu.c.
 {
     // we are going to be intercepting all chars
     saveStringEnter = 1;
     saveSlot = choice;
     M_StringCopy(saveOldString,savegamestrings[choice], SAVESTRINGSIZE);
     if (!strcmp(savegamestrings[choice], EMPTYSTRING))
     savegamestrings[choice][0] = 0;
     saveCharIndex = strlen(savegamestrings[choice]);
 }
References EMPTYSTRING, M_StringCopy(), saveCharIndex, savegamestrings, saveOldString, saveSlot, saveStringEnter, SAVESTRINGSIZE, strcmp(), and strlen().
M_SelectEndMessage()
static char* M_SelectEndMessage (void) static
Definition at line 1147 of file m_menu.c.
 {
     char **endmsg;
     if (logical_gamemission == doom)
     {
         // Doom 1
         endmsg = doom1_endmsg;
     }
     else
     {
         // Doom 2
         endmsg = doom2_endmsg;
     }
     return endmsg[gametic % NUM_QUITMESSAGES];
 }
References doom, doom1_endmsg, doom2_endmsg, gametic, logical_gamemission, and NUM_QUITMESSAGES.
Referenced by M_QuitDOOM().
M_SetupNextMenu()
void M_SetupNextMenu (menu_t * menudef)
Definition at line 2054 of file m_menu.c.
 {
     currentMenu = menudef;
     itemOn = currentMenu->lastOn;
 }
References currentMenu, itemOn, and menu_s::lastOn.
Referenced by M_Episode(), M_FinishReadThis(), M_LoadGame(), M_NewGame(), M_Options(), M_QuickSave(), M_ReadThis(), M_ReadThis2(), M_SaveGame(), and M_Sound().
M_SfxVol()
void M_SfxVol (int choice)
Definition at line 850 of file m_menu.c.
 {
     switch(choice)
     {
       case 0:
     if (sfxVolume)
         sfxVolume--;
     break;
       case 1:
     if (sfxVolume < 15)
         sfxVolume++;
     break;
     }
     S_SetSfxVolume(sfxVolume * 8);
 }
References S_SetSfxVolume(), and sfxVolume.
M_SizeDisplay()
void M_SizeDisplay (int choice)
Definition at line 1213 of file m_menu.c.
 {
     switch(choice)
     {
       case 0:
     if (screenSize > 0)
     {
         screenblocks--;
         screenSize--;
     }
     break;
       case 1:
     if (screenSize < 8)
     {
         screenblocks++;
         screenSize++;
     }
     break;
     }
     R_SetViewSize (screenblocks, detailLevel);
 }
References detailLevel, R_SetViewSize(), screenblocks, and screenSize.
Referenced by M_Responder().
M_Sound()
void M_Sound (int choice)
Definition at line 845 of file m_menu.c.
 {
     M_SetupNextMenu(&SoundDef);
 }
References M_SetupNextMenu(), and SoundDef.
M_StartControlPanel()
void M_StartControlPanel (void)
Definition at line 1899 of file m_menu.c.
 {
     // intro might call this repeatedly
     if (menuactive)
     return;
     menuactive = 1;
     currentMenu = &MainDef;         // JDC
     itemOn = currentMenu->lastOn;   // JDC
 }
References currentMenu, itemOn, menu_s::lastOn, MainDef, and menuactive.
Referenced by G_Responder(), M_QuickSave(), and M_Responder().
M_StartGame()
void M_StartGame (int choice)
M_StartMessage()
void M_StartMessage (char * string, void * routine, boolean input)
Definition at line 1289 of file m_menu.c.
 {
     messageLastMenuActive = menuactive;
     messageToPrint = 1;
     messageString = string;
     messageRoutine = routine;
     messageNeedsInput = input;
     menuactive = true;
     return;
 }
References menuactive, messageLastMenuActive, messageNeedsInput, messageRoutine, messageString, messageToPrint, and menu_s::routine.
Referenced by M_ChooseSkill(), M_EndGame(), M_Episode(), M_LoadGame(), M_NewGame(), M_QuickLoad(), M_QuickSave(), M_QuitDOOM(), and M_SaveGame().
M_StopMessage()
void M_StopMessage (void)
Definition at line 1304 of file m_menu.c.
 {
     menuactive = messageLastMenuActive;
     messageToPrint = 0;
 }
References menuactive, messageLastMenuActive, and messageToPrint.
M_StringHeight()
int M_StringHeight (char * string)
Definition at line 1338 of file m_menu.c.
 {
     size_t             i;
     int             h;
     int             height = SHORT(hu_font[0]->height);
     h = height;
     for (i = 0;i < strlen(string);i++)
     if (string[i] == '\n')
         h += height;
     return h;
 }
References anonymous_namespace{search.cpp}::height(), hu_font, i, SHORT, and strlen().
Referenced by M_Drawer().
M_StringWidth()
int M_StringWidth (char * string)
Definition at line 1315 of file m_menu.c.
 {
     size_t             i;
     int             w = 0;
     int             c;
     for (i = 0;i < strlen(string);i++)
     {
     c = toupper(string[i]) - HU_FONTSTART;
     if (c < 0 || c >= HU_FONTSIZE)
         w += 4;
     else
         w += SHORT (hu_font[c]->width);
     }
     return w;
 }
References c, hu_font, HU_FONTSIZE, HU_FONTSTART, i, SHORT, strlen(), and toupper.
Referenced by M_Drawer(), M_DrawSave(), and M_Responder().
M_Ticker()
void M_Ticker (void)
Definition at line 2064 of file m_menu.c.
 {
     if (--skullAnimCounter <= 0)
     {
     whichSkull ^= 1;
     skullAnimCounter = 8;
     }
 }
References skullAnimCounter, and whichSkull.
M_VerifyNightmare()
void M_VerifyNightmare (int key)
Definition at line 935 of file m_menu.c.
 {
     if (key != key_menu_confirm)
     return;
     G_DeferedInitNew(nightmare,epi+1,1);
     M_ClearMenus ();
 }
References epi, G_DeferedInitNew(), key_menu_confirm, M_ClearMenus(), and nightmare.
Referenced by M_ChooseSkill().
M_WriteText()
void M_WriteText (int x, int y, char * string)
Definition at line 1357 of file m_menu.c.
 {
     int     w;
     char*   ch;
     int     c;
     int     cx;
     int     cy;
     ch = string;
     cx = x;
     cy = y;
     while(1)
     {
     c = *ch++;
     if (!c)
         break;
     if (c == '\n')
     {
         cx = x;
         cy += 12;
         continue;
     }
     c = toupper(c) - HU_FONTSTART;
     if (c < 0 || c>= HU_FONTSIZE)
     {
         cx += 4;
         continue;
     }
     w = SHORT (hu_font[c]->width);
     if (cx+w > SCREENWIDTH)
         break;
     V_DrawPatchDirect(cx, cy, hu_font[c]);
     cx+=w;
     }
 }
References c, hu_font, HU_FONTSIZE, HU_FONTSTART, SCREENWIDTH, SHORT, toupper, V_DrawPatchDirect(), x, and y.
Referenced by M_Drawer(), M_DrawLoad(), and M_DrawSave().
Variable Documentation
chat_on
boolean chat_on extern
Definition at line 90 of file hu_stuff.c.
Referenced by HU_Responder(), HU_Start(), and M_Responder().
currentMenu
menu_t* currentMenu
Definition at line 171 of file m_menu.c.
Referenced by M_Drawer(), M_EndGameResponse(), M_Init(), M_Responder(), M_SetupNextMenu(), and M_StartControlPanel().
detailLevel
int detailLevel = 0
Definition at line 77 of file m_menu.c.
Referenced by D_BindVariables(), M_ChangeDetail(), M_DrawOptions(), M_SizeDisplay(), and R_Init().
detailNames
char* detailNames[2] = {"M_GDHIGH","M_GDLOW"} static
Definition at line 984 of file m_menu.c.
Referenced by M_DrawOptions().
endstring
char endstring[160]
Definition at line 126 of file m_menu.c.
Referenced by M_QuitDOOM().
epi
int epi
Definition at line 928 of file m_menu.c.
Referenced by M_ChooseSkill(), M_Episode(), and M_VerifyNightmare().
EpiDef
menu_t EpiDef
Initial value:
=
{
    ep_end,
    &MainDef,
    EpisodeMenu,
    M_DrawEpisode,
    48,63,
    ep1
}
Definition at line 284 of file m_menu.c.
Referenced by M_Init(), and M_NewGame().
EpisodeMenu
menuitem_t EpisodeMenu[]
Initial value:
=
{
    {1,"M_EPI1", M_Episode,'k'},
    {1,"M_EPI2", M_Episode,'t'},
    {1,"M_EPI3", M_Episode,'i'},
    {1,"M_EPI4", M_Episode,'t'}
}
Definition at line 276 of file m_menu.c.
enum { ... } episodes_e
gammamsg
char gammamsg[5][26]
Initial value:
=
{
    GAMMALVL0,
    GAMMALVL1,
    GAMMALVL2,
    GAMMALVL3,
    GAMMALVL4
}
Definition at line 101 of file m_menu.c.
Referenced by M_Responder().
hu_font
patch_t* hu_font[HU_FONTSIZE] extern
Definition at line 88 of file hu_stuff.c.
Referenced by HU_Init(), HU_Start(), M_Drawer(), M_StringHeight(), M_StringWidth(), and M_WriteText().
inhelpscreens
boolean inhelpscreens
Definition at line 117 of file m_menu.c.
Referenced by D_Display(), M_Drawer(), M_DrawReadThis1(), and M_DrawReadThis2().
itemOn
short itemOn
Definition at line 162 of file m_menu.c.
Referenced by M_Drawer(), M_EndGameResponse(), M_Init(), M_Responder(), M_SetupNextMenu(), and M_StartControlPanel().
enum { ... } load_e
LoadDef
menu_t LoadDef
Initial value:
=
{
    load_end,
    &MainDef,
    LoadMenu,
    M_DrawLoad,
    80,54,
    0
}
Definition at line 465 of file m_menu.c.
Referenced by M_DrawLoad(), M_DrawSave(), and M_LoadGame().
LoadMenu
menuitem_t LoadMenu[]
Initial value:
=
{
    {1,"", M_LoadSelect,'1'},
    {1,"", M_LoadSelect,'2'},
    {1,"", M_LoadSelect,'3'},
    {1,"", M_LoadSelect,'4'},
    {1,"", M_LoadSelect,'5'},
    {1,"", M_LoadSelect,'6'}
}
Definition at line 455 of file m_menu.c.
Referenced by M_ReadSaveStrings().
enum { ... } main_e
MainDef
menu_t MainDef
Initial value:
=
{
    main_end,
    NULL,
    MainMenu,
    M_DrawMainMenu,
    97,64,
    0
}
Definition at line 253 of file m_menu.c.
Referenced by M_FinishReadThis(), M_Init(), and M_StartControlPanel().
MainMenu
menuitem_t MainMenu[]
Initial value:
=
{
    {1,"M_NGAME",M_NewGame,'n'},
    {1,"M_OPTION",M_Options,'o'},
    {1,"M_LOADG",M_LoadGame,'l'},
    {1,"M_SAVEG",M_SaveGame,'s'},
    {1,"M_RDTHIS",M_ReadThis,'r'},
    {1,"M_QUITG",M_QuitDOOM,'q'}
}
Definition at line 242 of file m_menu.c.
Referenced by M_Init().
menuactive
boolean menuactive
Definition at line 118 of file m_menu.c.
Referenced by D_Display(), D_GrabMouseCallback(), M_ClearMenus(), M_Drawer(), M_Init(), M_Responder(), M_StartControlPanel(), M_StartMessage(), M_StopMessage(), and P_Ticker().
message_dontfuckwithme
boolean message_dontfuckwithme extern
Definition at line 97 of file hu_stuff.c.
Referenced by HU_Start(), HU_Ticker(), and M_ChangeMessages().
messageLastMenuActive
int messageLastMenuActive
Definition at line 94 of file m_menu.c.
Referenced by M_Init(), M_Responder(), M_StartMessage(), and M_StopMessage().
messageNeedsInput
boolean messageNeedsInput
Definition at line 97 of file m_menu.c.
Referenced by M_Responder(), and M_StartMessage().
messageRoutine
void(* messageRoutine) (int response) (int response)
Definition at line 99 of file m_menu.c.
Referenced by M_Responder(), and M_StartMessage().
messageString
char* messageString
Definition at line 89 of file m_menu.c.
Referenced by M_Drawer(), M_Init(), and M_StartMessage().
messageToPrint
int messageToPrint
Definition at line 87 of file m_menu.c.
Referenced by M_Drawer(), M_Init(), M_Responder(), M_StartMessage(), and M_StopMessage().
messx
int messx
Definition at line 92 of file m_menu.c.
messy
int messy
Definition at line 93 of file m_menu.c.
mouseSensitivity
int mouseSensitivity = 5
Definition at line 70 of file m_menu.c.
Referenced by D_BindVariables(), G_Responder(), M_ChangeSensitivity(), and M_DrawOptions().
msgNames
char* msgNames[2] = {"M_MSGOFF","M_MSGON"} static
Definition at line 985 of file m_menu.c.
Referenced by M_DrawOptions().
NewDef
menu_t NewDef
Initial value:
=
{
    newg_end,
    &EpiDef,
    NewGameMenu,
    M_DrawNewGame,
    48,63,
    hurtme
}
Definition at line 316 of file m_menu.c.
Referenced by M_Episode(), M_Init(), and M_NewGame().
enum { ... } newgame_e
NewGameMenu
menuitem_t NewGameMenu[]
Initial value:
=
{
    {1,"M_JKILL",   M_ChooseSkill, 'i'},
    {1,"M_ROUGH",   M_ChooseSkill, 'h'},
    {1,"M_HURT",    M_ChooseSkill, 'h'},
    {1,"M_ULTRA",   M_ChooseSkill, 'u'},
    {1,"M_NMARE",   M_ChooseSkill, 'n'}
}
Definition at line 307 of file m_menu.c.
enum { ... } options_e
OptionsDef
menu_t OptionsDef
Initial value:
=
{
    opt_end,
    &MainDef,
    OptionsMenu,
    M_DrawOptions,
    60,37,
    0
}
Definition at line 356 of file m_menu.c.
Referenced by M_DrawOptions(), and M_Options().
OptionsMenu
menuitem_t OptionsMenu[]
Initial value:
=
{
    {1,"M_ENDGAM",  M_EndGame,'e'},
    {1,"M_MESSG",   M_ChangeMessages,'m'},
    {1,"M_DETAIL",  M_ChangeDetail,'g'},
    {2,"M_SCRNSZ",  M_SizeDisplay,'s'},
    {-1,"",0,'\0'},
    {2,"M_MSENS",   M_ChangeSensitivity,'m'},
    {-1,"",0,'\0'},
    {1,"M_SVOL",    M_Sound,'s'}
}
Definition at line 344 of file m_menu.c.
quickSaveSlot
int quickSaveSlot
Definition at line 84 of file m_menu.c.
Referenced by M_DoSave(), M_Init(), M_QuickLoad(), M_QuickLoadResponse(), M_QuickSave(), and M_QuickSaveResponse().
quitsounds
int quitsounds[8]
Initial value:
=
{
    sfx_pldeth,
    sfx_dmpain,
    sfx_popain,
    sfx_slop,
    sfx_telept,
    sfx_posit1,
    sfx_posit3,
    sfx_sgtatk
}
Definition at line 1105 of file m_menu.c.
Referenced by M_QuitResponse().
quitsounds2
int quitsounds2[8]
Initial value:
=
{
    sfx_vilact,
    sfx_getpow,
    sfx_boscub,
    sfx_slop,
    sfx_skeswg,
    sfx_kntdth,
    sfx_bspact,
    sfx_sgtatk
}
Definition at line 1117 of file m_menu.c.
Referenced by M_QuitResponse().
enum { ... } read_e
enum { ... } read_e2
ReadDef1
menu_t ReadDef1
Initial value:
=
{
    read1_end,
    &MainDef,
    ReadMenu1,
    M_DrawReadThis1,
    280,185,
    0
}
Definition at line 380 of file m_menu.c.
Referenced by M_DrawReadThis1(), M_Episode(), M_ReadThis(), and M_Responder().
ReadDef2
menu_t ReadDef2
Initial value:
=
{
    read2_end,
    &ReadDef1,
    ReadMenu2,
    M_DrawReadThis2,
    330,175,
    0
}
Definition at line 401 of file m_menu.c.
Referenced by M_ReadThis2(), and M_Responder().
ReadMenu1
menuitem_t ReadMenu1[]
Initial value:
=
{
    {1,"",M_ReadThis2,0}
}
Definition at line 375 of file m_menu.c.
ReadMenu2
menuitem_t ReadMenu2[]
Initial value:
=
{
    {1,"",M_FinishReadThis,0}
}
Definition at line 396 of file m_menu.c.
saveCharIndex
int saveCharIndex
Definition at line 113 of file m_menu.c.
Referenced by M_Responder(), and M_SaveSelect().
SaveDef
menu_t SaveDef
Initial value:
=
{
    load_end,
    &MainDef,
    SaveMenu,
    M_DrawSave,
    80,54,
    0
}
Definition at line 488 of file m_menu.c.
Referenced by M_QuickSave(), and M_SaveGame().
savegamestrings
char savegamestrings[10][SAVESTRINGSIZE]
Definition at line 124 of file m_menu.c.
Referenced by M_DoSave(), M_DrawLoad(), M_DrawSave(), M_QuickLoad(), M_QuickSave(), M_ReadSaveStrings(), M_Responder(), and M_SaveSelect().
SaveMenu
menuitem_t SaveMenu[]
Initial value:
=
{
    {1,"", M_SaveSelect,'1'},
    {1,"", M_SaveSelect,'2'},
    {1,"", M_SaveSelect,'3'},
    {1,"", M_SaveSelect,'4'},
    {1,"", M_SaveSelect,'5'},
    {1,"", M_SaveSelect,'6'}
}
Definition at line 478 of file m_menu.c.
saveOldString
char saveOldString[SAVESTRINGSIZE]
Definition at line 115 of file m_menu.c.
Referenced by M_Responder(), and M_SaveSelect().
saveSlot
int saveSlot
Definition at line 112 of file m_menu.c.
Referenced by M_DrawSave(), M_Responder(), and M_SaveSelect().
saveStringEnter
int saveStringEnter
Definition at line 111 of file m_menu.c.
Referenced by M_DrawSave(), M_Responder(), and M_SaveSelect().
screenblocks
int screenblocks = 10
Definition at line 78 of file m_menu.c.
Referenced by D_BindVariables(), M_ChangeDetail(), M_Init(), M_SizeDisplay(), and R_Init().
screenSize
int screenSize
Definition at line 81 of file m_menu.c.
Referenced by M_DrawOptions(), M_Init(), and M_SizeDisplay().
sendpause
boolean sendpause extern
Definition at line 108 of file g_game.c.
Referenced by G_BuildTiccmd(), G_DoLoadLevel(), and G_Responder().
showMessages
int showMessages = 1
Definition at line 73 of file m_menu.c.
Referenced by D_BindVariables(), HU_Ticker(), M_ChangeMessages(), and M_DrawOptions().
skullAnimCounter
short skullAnimCounter
Definition at line 163 of file m_menu.c.
Referenced by M_Init(), and M_Ticker().
skullName
char* skullName[2] = {"M_SKULL1","M_SKULL2"}
Definition at line 168 of file m_menu.c.
Referenced by M_Drawer().
enum { ... } sound_e
SoundDef
menu_t SoundDef
Initial value:
=
{
    sound_end,
    &OptionsDef,
    SoundMenu,
    M_DrawSound,
    80,64,
    0
}
Definition at line 431 of file m_menu.c.
Referenced by M_DrawSound(), M_Responder(), and M_Sound().
SoundMenu
menuitem_t SoundMenu[]
Initial value:
=
{
    {2,"M_SFXVOL",M_SfxVol,'s'},
    {-1,"",0,'\0'},
    {2,"M_MUSVOL",M_MusicVol,'m'},
    {-1,"",0,'\0'}
}
Definition at line 423 of file m_menu.c.
tempstring
char tempstring[80]
Definition at line 670 of file m_menu.c.
Referenced by M_QuickLoad(), and M_QuickSave().
whichSkull
short whichSkull
Definition at line 164 of file m_menu.c.
Referenced by M_Drawer(), M_Init(), and M_Ticker().