Fennix Userspace: Userspace/apps/base/busybox/networking/slattach.c File Reference
slattach.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include "libiproute/utils.h"
Data Structures
struct globals
Macros
#define G (*(struct globals*)bb_common_bufsiz1)
#define INIT_G() do { setup_common_bufsiz(); } while (0)
#define serial_fd 3
Functions
static int tcsetattr_serial_or_warn (struct termios *state)
static void restore_state_and_exit (int exitcode) NORETURN
static void sig_handler (int signo UNUSED_PARAM)
int slattach_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
Macro Definition Documentation
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 47 of file slattach.c.
INIT_G
#define INIT_G () do { setup_common_bufsiz(); } while (0)
Definition at line 48 of file slattach.c.
serial_fd
#define serial_fd 3
Definition at line 50 of file slattach.c.
Function Documentation
restore_state_and_exit()
static void restore_state_and_exit (int exitcode) static
Definition at line 65 of file slattach.c.
 {
     struct termios state;
     /* Restore line discipline */
     if (ioctl_or_warn(serial_fd, TIOCSETD, &G.saved_disc)) {
         exitcode = 1;
     }
     /* Hangup */
     memcpy(&state, &G.saved_state, sizeof(state));
     cfsetispeed(&state, B0);
     cfsetospeed(&state, B0);
     exitcode |= tcsetattr_serial_or_warn(&state);
     sleep1();
     /* Restore line status */
     if (tcsetattr_serial_or_warn(&G.saved_state))
         exit(EXIT_FAILURE);
     if (ENABLE_FEATURE_CLEAN_UP)
         close(serial_fd);
     exit(exitcode);
 }
References B0, cfsetispeed(), cfsetospeed(), close(), exit(), EXIT_FAILURE, exitcode, G, ioctl_or_warn, memcpy(), serial_fd, sleep1(), state, tcsetattr_serial_or_warn(), and TIOCSETD.
Referenced by sig_handler(), and slattach_main().
sig_handler()
static void sig_handler (int signo UNUSED_PARAM) static
Definition at line 91 of file slattach.c.
 {
     restore_state_and_exit(EXIT_SUCCESS);
 }
References EXIT_SUCCESS, and restore_state_and_exit().
Referenced by powertop_main(), and slattach_main().
slattach_main()
int slattach_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 97 of file slattach.c.
 {
     /* Line discipline code table */
     static const char proto_names[] ALIGN1 =
         "slip\0"        /* 0 */
         "cslip\0"       /* 1 */
         "slip6\0"       /* 2 */
         "cslip6\0"      /* 3 */
         "adaptive\0"    /* 8 */
         ;
     static const int int_N_SLIP = N_SLIP;
     int encap, opt, fd;
     struct termios state;
     const char *proto = "cslip";
     const char *extcmd;   /* Command to execute after hangup */
     const char *baud_str;
     int baud_code = baud_code; /* for compiler */
     enum {
         OPT_p_proto  = 1 << 0,
         OPT_s_baud   = 1 << 1,
         OPT_c_extcmd = 1 << 2,
         OPT_e_quit   = 1 << 3,
         OPT_h_watch  = 1 << 4,
         OPT_m_nonraw = 1 << 5,
         OPT_L_local  = 1 << 6,
         OPT_F_noflow = 1 << 7
     };
     INIT_G();
     /* Parse command line options */
     opt = getopt32(argv, "^" "p:s:c:ehmLF" "\0" "=1",
                 &proto, &baud_str, &extcmd
     );
     /*argc -= optind;*/
     argv += optind;
     encap = index_in_strings(proto_names, proto);
     if (encap < 0)
         invarg_1_to_2(proto, "protocol");
     if (encap > 3)
         encap = 8;
     /* We want to know if the baud rate is valid before we start touching the ttys */
     if (opt & OPT_s_baud) {
         baud_code = tty_value_to_baud(xatoi(baud_str));
         if (baud_code < 0)
             invarg_1_to_2(baud_str, "baud rate");
     }
     /* Open tty */
     fd = open(*argv, O_RDWR | O_NDELAY);
     if (fd < 0) {
         char *buf = concat_path_file("/dev", *argv);
         fd = xopen(buf, O_RDWR | O_NDELAY);
         /* maybe if (ENABLE_FEATURE_CLEAN_UP) ?? */
         free(buf);
     }
     xmove_fd(fd, serial_fd);
     /* Save current tty state */
     if (tcgetattr(serial_fd, &G.saved_state) != 0)
         bb_simple_perror_msg_and_die("tcgetattr");
     /* Save line discipline */
     xioctl(serial_fd, TIOCGETD, &G.saved_disc);
     /* Trap signals in order to restore tty states upon exit */
     if (!(opt & OPT_e_quit)) {
         bb_signals(0
             + (1 << SIGHUP)
             + (1 << SIGINT)
             + (1 << SIGQUIT)
             + (1 << SIGTERM)
             , sig_handler);
     }
     /* Configure tty */
     memcpy(&state, &G.saved_state, sizeof(state));
     if (!(opt & OPT_m_nonraw)) { /* raw not suppressed */
         memset(&state.c_cc, 0, sizeof(state.c_cc));
         state.c_cc[VMIN] = 1;
         state.c_iflag = IGNBRK | IGNPAR;
         /*state.c_oflag = 0;*/
         /*state.c_lflag = 0;*/
         state.c_cflag = CS8 | HUPCL | CREAD
                       | ((opt & OPT_L_local) ? CLOCAL : 0)
                       | ((opt & OPT_F_noflow) ? 0 : CRTSCTS);
         cfsetispeed(&state, cfgetispeed(&G.saved_state));
         cfsetospeed(&state, cfgetospeed(&G.saved_state));
     }
     if (opt & OPT_s_baud) {
         cfsetispeed(&state, baud_code);
         cfsetospeed(&state, baud_code);
     }
     /* Set line status */
     if (tcsetattr_serial_or_warn(&state))
         goto bad;
     /* Set line disclipline (N_SLIP always) */
     if (ioctl_or_warn(serial_fd, TIOCSETD, (void*)&int_N_SLIP))
         goto bad;
     /* Set encapsulation (SLIP, CSLIP, etc) */
     if (ioctl_or_warn(serial_fd, SIOCSIFENCAP, &encap))
         goto bad;
     /* Exit now if option -e was passed */
     if (opt & OPT_e_quit)
         return EXIT_SUCCESS;
     /* If we're not requested to watch, just keep descriptor open
      * until we are killed */
     if (!(opt & OPT_h_watch))
         while (1)
             sleep(24*60*60);
     /* Watch line for hangup */
     while (1) {
         int modem_stat;
         if (ioctl(serial_fd, TIOCMGET, &modem_stat))
             break;
         if (!(modem_stat & TIOCM_CAR))
             break;
         sleep(15);
     }
     /* Execute command on hangup */
     if (opt & OPT_c_extcmd)
         system(extcmd);
     /* Restore states and exit */
     restore_state_and_exit(EXIT_SUCCESS);
  bad:
     restore_state_and_exit(EXIT_FAILURE);
 }
References ALIGN1, argv, bb_signals(), bb_simple_perror_msg_and_die(), buf, cfgetispeed(), cfgetospeed(), cfsetispeed(), cfsetospeed(), CLOCAL, concat_path_file(), CREAD, CRTSCTS, CS8, EXIT_FAILURE, EXIT_SUCCESS, fd, free, G, getopt32(), HUPCL, IGNBRK, IGNPAR, index_in_strings(), INIT_G, invarg_1_to_2(), ioctl(), ioctl_or_warn, memcpy(), memset(), N_SLIP, O_NDELAY, O_RDWR, open(), opt, optind, restore_state_and_exit(), serial_fd, sig_handler(), SIGHUP, SIGINT, SIGQUIT, SIGTERM, SIOCSIFENCAP, sleep(), state, system(), tcgetattr(), tcsetattr_serial_or_warn(), TIOCGETD, TIOCM_CAR, TIOCMGET, TIOCSETD, tty_value_to_baud(), VMIN, xioctl, xmove_fd(), and xopen().
tcsetattr_serial_or_warn()
static int tcsetattr_serial_or_warn (struct termios * state) static
Definition at line 52 of file slattach.c.
 {
     int ret;
     ret = tcsetattr(serial_fd, TCSANOW, state);
     if (ret != 0) {
         bb_simple_perror_msg("tcsetattr");
         return 1; /* used as exitcode */
     }
     return ret; /* 0 */
 }
References bb_simple_perror_msg(), serial_fd, state, TCSANOW, and tcsetattr().
Referenced by restore_state_and_exit(), and slattach_main().
Variable Documentation
FIX_ALIASING
struct globals FIX_ALIASING