Fennix: Userspace/mlibc/options/posix/include/sys/mman.h File Reference
mman.h File Reference
#include <mlibc-config.h>
#include <abi-bits/mode_t.h>
#include <abi-bits/vm-flags.h>
#include <bits/off_t.h>
#include <bits/size_t.h>
Functions
void * mmap (void *, size_t, int, int, int, off_t)
int mprotect (void *, size_t, int)
int munmap (void *, size_t)
int mlock (const void *, size_t)
int mlockall (int)
int munlock (const void *, size_t)
int munlockall (void)
int posix_madvise (void *, size_t, int)
int msync (void *, size_t, int)
int shm_open (const char *, int, mode_t)
int shm_unlink (const char *)
void * mremap (void *, size_t, size_t, int,...)
int remap_file_pages (void *, size_t, int, size_t, int)
Function Documentation
mlock()
int mlock (const void * addr, size_t len)
Definition at line 21 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mlock, -1);
     if(int e = mlibc::sys_mlock(addr, len); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mlock().
mlockall()
int mlockall (int flags)
Definition at line 30 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_mlockall, -1);
     if(int e = mlibc::sys_mlockall(flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_mlockall().
mmap()
void* mmap (void * hint, size_t size, int prot, int flags, int fd, off_t offset)
Definition at line 82 of file sys-mman-stubs.cpp.
{
     void *window;
     if(int e = mlibc::sys_vm_map(hint, size, prot, flags, fd, offset, &window); e) {
         errno = e;
         return (void *)-1;
     }
     return window;
 }
References errno, fd, mlibc::flags, offset, mlibc::prot, size, mlibc::sys_vm_map(), and mlibc::window.
Referenced by ProcessMB2(), mlibc::sys_prepare_stack(), and test_stackaddr().
mprotect()
int mprotect (void * pointer, size_t size, int prot)
Definition at line 12 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_vm_protect, -1);
     if(int e = mlibc::sys_vm_protect(pointer, size, prot); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, mlibc::prot, size, and mlibc::sys_vm_protect().
mremap()
void* mremap (void * pointer, size_t size, size_t new_size, int flags, ...)
Definition at line 65 of file sys-mman-stubs.cpp.
{
     __ensure(flags == MREMAP_MAYMOVE);
     void *window;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_vm_remap, (void *)-1);
     if(int e = mlibc::sys_vm_remap(pointer, size, new_size, &window); e) {
         errno = e;
         return (void *)-1;
     }
     return window;
 }
References __ensure, errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, MREMAP_MAYMOVE, size, mlibc::sys_vm_remap(), and mlibc::window.
msync()
int msync (void * addr, size_t length, int flags)
Definition at line 56 of file sys-mman-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_msync, -1);
     if(int e = mlibc::sys_msync(addr, length, flags); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, mlibc::flags, MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_msync().
munlock()
int munlock (const void * , size_t)
Definition at line 39 of file sys-mman-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
munlockall()
int munlockall (void)
Definition at line 44 of file sys-mman-stubs.cpp.
                      {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
munmap()
int munmap (void * pointer, size_t size)
Definition at line 91 of file sys-mman-stubs.cpp.
{
     if(int e = mlibc::sys_vm_unmap(pointer, size); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, size, and mlibc::sys_vm_unmap().
posix_madvise()
int posix_madvise (void * , size_t , int)
Definition at line 50 of file sys-mman-stubs.cpp.
{
     mlibc::infoLogger() << "\e[31m" "mlibc: posix_madvise() fails unconditionally" "\e[39m"
             << frg::endlog;
     return ENOSYS;
 }
References ENOSYS, and mlibc::infoLogger.
remap_file_pages()
int remap_file_pages (void * , size_t , int , size_t , int)
Definition at line 77 of file sys-mman-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
shm_open()
int shm_open (const char * name, int flags, mode_t mode)
Definition at line 120 of file sys-mman-stubs.cpp.
{
     int cs;
     char buf[NAME_MAX + 10];
     if(!(name = shm_mapname(name, buf)))
         return -1;
     pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cs);
     int fd = open(name, flags | O_NOFOLLOW | O_CLOEXEC | O_NONBLOCK, mode);
     pthread_setcancelstate(cs, 0);
     return fd;
 }
References buf, fd, mlibc::flags, name, NAME_MAX, O_CLOEXEC, O_NOFOLLOW, O_NONBLOCK, open(), PTHREAD_CANCEL_DISABLE, pthread_setcancelstate(), and anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname().
shm_unlink()
int shm_unlink (const char * name)
Definition at line 131 of file sys-mman-stubs.cpp.
{
     char buf[NAME_MAX + 10];
     if(!(name = shm_mapname(name, buf)))
         return -1;
     return unlink(name);
 }
References buf, name, NAME_MAX, anonymous_namespace{sys-mman-stubs.cpp}::shm_mapname(), and unlink().