Fennix Kernel: Kernel/include/net/net.hpp File Reference
net.hpp File Reference
#include <types.h>
#include <printf.h>
Data Structures
struct MediaAccessControl
struct InternetProtocol
struct InternetProtocol::Version4
struct InternetProtocol::Version6
Macros
#define netdbg(m, ...)
#define b4(x) ((x & 0x0F) << 4 | (x & 0xF0) >> 4)
#define b8(x) ((x)&0xFF)
#define b16(x) __builtin_bswap16(x)
#define b32(x) __builtin_bswap32(x)
#define b48(x) (((((x)&0x0000000000ff) << 40) | (((x)&0x00000000ff00) << 24) | (((x)&0x000000ff0000) << 8) | (((x)&0x0000ff000000) >> 8) | (((x)&0x00ff00000000) >> 24) | (((x)&0xff0000000000) >> 40)))
#define b64(x) __builtin_bswap64(x)
Typedefs
typedef __UINT64_TYPE__ uint48_t
Enumerations
enum Endianness { LITTLE_ENDIAN , BIG_ENDIAN }
Functions
static void DbgNetwork ()
static void DbgDumpData (const char *Description, void *Address, unsigned long Length)
uint16_t CalculateChecksum (uint16_t *Data, uint64_t Length)
Data Structure Documentation
InternetProtocol
struct InternetProtocol
Definition at line 118 of file net.hpp.
Data Fields
struct Version4 v4
struct Version6 v6
Macro Definition Documentation
b16
#define b16 (x) __builtin_bswap16(x)
Definition at line 24 of file net.hpp.
b32
#define b32 (x) __builtin_bswap32(x)
Definition at line 25 of file net.hpp.
b4
#define b4 (x) ((x & 0x0F) << 4 | (x & 0xF0) >> 4)
Definition at line 22 of file net.hpp.
b48
#define b48 (x) (((((x)&0x0000000000ff) << 40) | (((x)&0x00000000ff00) << 24) | (((x)&0x000000ff0000) << 8) | (((x)&0x0000ff000000) >> 8) | (((x)&0x00ff00000000) >> 24) | (((x)&0xff0000000000) >> 40)))
Definition at line 26 of file net.hpp.
b64
#define b64 (x) __builtin_bswap64(x)
Definition at line 27 of file net.hpp.
b8
#define b8 (x) ((x)&0xFF)
Definition at line 23 of file net.hpp.
netdbg
#define netdbg (m, ...)
Definition at line 14 of file net.hpp.
Typedef Documentation
uint48_t
typedef __UINT64_TYPE__ uint48_t
Definition at line 20 of file net.hpp.
Enumeration Type Documentation
Endianness
enum Endianness
Enumerator
LITTLE_ENDIAN
BIG_ENDIAN
Definition at line 29 of file net.hpp.
 {
     LITTLE_ENDIAN,
     BIG_ENDIAN
 };
Function Documentation
CalculateChecksum()
uint16_t CalculateChecksum (uint16_t * Data, uint64_t Length)
Definition at line 3 of file Checksum.cpp.
 {
     uint16_t *Data16 = (uint16_t *)Data;
     uint64_t Checksum = 0;
     for (uint64_t i = 0; i < Length / 2; i++)
         Checksum += ((Data16[i] & 0xFF00) >> 8) | ((Data16[i] & 0x00FF) << 8);
     if (Length % 2)
         Checksum += ((uint16_t)((char *)Data16)[Length - 1]) << 8;
     while (Checksum & 0xFFFF0000)
         Checksum = (Checksum & 0xFFFF) + (Checksum >> 16);
     return (uint16_t)(((~Checksum & 0xFF00) >> 8) | ((~Checksum & 0x00FF) << 8));
 }
References Checksum, Data, and Length.
Referenced by NetworkIPv4::IPv4::OnEthernetPacketReceived(), NetworkICMPv4::ICMPv4::Receive(), and NetworkIPv4::IPv4::Send().
DbgDumpData()
static void DbgDumpData (const char * Description, void * Address, unsigned long Length) inline static
Definition at line 16 of file net.hpp.
 { return; }
DbgNetwork()
static void DbgNetwork () inline static
Definition at line 15 of file net.hpp.
 { return; }
Referenced by NetworkInterfaceManager::NetworkInterface::NetworkInterface().