Fennix Userspace: wad_file_class_t Struct Reference
wad_file_class_t Struct Reference
#include <w_file.h>
Data Fields
wad_file_t *(* OpenFile)(char *path)
void(* CloseFile)(wad_file_t *file)
size_t(* Read)(wad_file_t *file, unsigned int offset, void *buffer, size_t buffer_len)
Detailed Description
Definition at line 28 of file w_file.h.
Field Documentation
CloseFile
void(* wad_file_class_t::CloseFile) (wad_file_t *file)
Definition at line 36 of file w_file.h.
Referenced by W_CloseFile().
OpenFile
wad_file_t*(* wad_file_class_t::OpenFile) (char *path)
Definition at line 32 of file w_file.h.
Referenced by W_OpenFile().
Read
size_t(* wad_file_class_t::Read) (wad_file_t *file, unsigned int offset, void *buffer, size_t buffer_len)
Definition at line 41 of file w_file.h.
Referenced by W_Read().
The documentation for this struct was generated from the following file:
Userspace/apps/user/games/doomgeneric/doomgeneric/w_file.h