Fennix Userspace: Userspace/apps/base/busybox/archival/bbunzip.c File Reference
bbunzip.c File Reference
#include "libbb.h"
#include "bb_archive.h"
Functions
static int open_to_or_warn (int to_fd, const char *filename, int flags, int mode)
char *FAST_FUNC append_ext (char *filename, const char *expected_ext)
int FAST_FUNC bbunpack (char **argv, IF_DESKTOP(long long) int FAST_FUNC(*unpacker)(transformer_state_t *xstate), char *FAST_FUNC(*make_new_name)(char *filename, const char *expected_ext), const char *expected_ext)
Function Documentation
append_ext()
char* FAST_FUNC append_ext (char * filename, const char * expected_ext)
Definition at line 35 of file bbunzip.c.
 {
     return xasprintf("%s.%s", filename, expected_ext);
 }
References filename, and xasprintf().
Referenced by bzip2_main(), and gzip_main().
bbunpack()
int FAST_FUNC bbunpack (char ** argv, IF_DESKTOP(long long) int FAST_FUNC(*)(transformer_state_t *xstate) unpacker, char *FAST_FUNC(*)(char *filename, const char *expected_ext) make_new_name, const char * expected_ext)
Definition at line 40 of file bbunzip.c.
 {
     struct stat stat_buf;
     IF_DESKTOP(long long) int status = 0;
     char *filename, *new_name;
     smallint exitcode = 0;
     transformer_state_t xstate;
     do {
         /* NB: new_name is *maybe* malloc'ed! */
         new_name = NULL;
         filename = *argv; /* can be NULL - 'streaming' bunzip2 */
         if (filename && LONE_DASH(filename))
             filename = NULL;
         /* Open src */
         if (filename) {
             if (!(option_mask32 & BBUNPK_SEAMLESS_MAGIC)) {
                 if (stat(filename, &stat_buf) != 0) {
  err_name:
                     bb_simple_perror_msg(filename);
  err:
                     exitcode = 1;
                     goto free_name;
                 }
                 if (open_to_or_warn(STDIN_FILENO, filename, O_RDONLY, 0))
                     goto err;
             } else {
                 /* "clever zcat" with FILE */
                 /* fail_if_not_compressed because zcat refuses uncompressed input */
                 int fd = open_zipped(filename, /*fail_if_not_compressed:*/ 1);
                 if (fd < 0)
                     goto err_name;
                 xmove_fd(fd, STDIN_FILENO);
             }
         } else
         if (option_mask32 & BBUNPK_SEAMLESS_MAGIC) {
             /* "clever zcat" on stdin */
             if (setup_unzip_on_fd(STDIN_FILENO, /*fail_if_not_compressed*/ 1))
                 goto err;
         }
         /* Special cases: test, stdout */
         if (option_mask32 & (BBUNPK_OPT_STDOUT|BBUNPK_OPT_TEST)) {
             if (option_mask32 & BBUNPK_OPT_TEST)
                 if (open_to_or_warn(STDOUT_FILENO, bb_dev_null, O_WRONLY, 0))
                     xfunc_die();
             filename = NULL;
         }
         /* Open dst if we are going to unpack to file */
         if (filename) {
             new_name = make_new_name(filename, expected_ext);
             if (!new_name) {
                 bb_error_msg("%s: unknown suffix - ignored", filename);
                 goto err;
             }
             /* -f: overwrite existing output files */
             if (option_mask32 & BBUNPK_OPT_FORCE) {
                 unlink(new_name);
             }
             /* O_EXCL: "real" bunzip2 doesn't overwrite files */
             /* GNU gunzip does not bail out, but goes to next file */
             if (open_to_or_warn(STDOUT_FILENO, new_name, O_WRONLY | O_CREAT | O_EXCL,
                     stat_buf.st_mode))
                 goto err;
         }
         /* Check that the input is sane */
         if (!(option_mask32 & BBUNPK_OPT_FORCE) && isatty(STDIN_FILENO)) {
             bb_simple_error_msg_and_die("compressed data not read from terminal, "
                     "use -f to force it");
         }
         if (!(option_mask32 & BBUNPK_SEAMLESS_MAGIC)) {
             init_transformer_state(&xstate);
             /*xstate.signature_skipped = 0; - already is */
             /*xstate.src_fd = STDIN_FILENO; - already is */
             xstate.dst_fd = STDOUT_FILENO;
             status = unpacker(&xstate);
             if (status < 0)
                 exitcode = 1;
         } else {
             if (bb_copyfd_eof(STDIN_FILENO, STDOUT_FILENO) < 0)
                 /* Disk full, tty closed, etc. No point in continuing */
                 xfunc_die();
         }
         if (!(option_mask32 & BBUNPK_OPT_STDOUT))
             xclose(STDOUT_FILENO); /* with error check! */
         if (filename) {
             char *del = new_name;
             if (status >= 0) {
                 unsigned new_name_len;
                 /* TODO: restore other things? */
                 if (xstate.mtime != 0) {
                     struct timeval times[2];
                     times[1].tv_sec = times[0].tv_sec = xstate.mtime;
                     times[1].tv_usec = times[0].tv_usec = 0;
                     /* Note: we closed it first.
                      * On some systems calling utimes
                      * then closing resets the mtime
                      * back to current time. */
                     utimes(new_name, times); /* ignoring errors */
                 }
                 if (ENABLE_DESKTOP)
                     new_name_len = strlen(new_name);
                 /* Restore source filename (unless tgz -> tar case) */
                 if (new_name == filename) {
                     new_name_len = strlen(filename);
                     filename[new_name_len] = '.';
                 }
                 /* Extreme bloat for gunzip compat */
                 /* Some users do want this info... */
                 if (ENABLE_DESKTOP && (option_mask32 & BBUNPK_OPT_VERBOSE)) {
                     unsigned percent = status
                         ? ((uoff_t)stat_buf.st_size * 100u / (unsigned long long)status)
                         : 0;
                     fprintf(stderr, "%s: %u%% - replaced with %.*s\n",
                         filename,
                         100u - percent,
                         new_name_len, new_name
                     );
                 }
                 /* Delete _source_ file */
                 del = filename;
                 if (option_mask32 & BBUNPK_OPT_KEEP) /* ... unless -k */
                     del = NULL;
             }
             if (del)
                 xunlink(del);
  free_name:
             if (new_name != filename)
                 free(new_name);
         }
     } while (*argv && *++argv);
     if (option_mask32 & BBUNPK_OPT_STDOUT)
         xclose(STDOUT_FILENO); /* with error check! */
     return exitcode;
 }
References argv, bb_copyfd_eof(), bb_dev_null, bb_error_msg(), bb_simple_error_msg_and_die(), bb_simple_perror_msg(), BBUNPK_OPT_FORCE, BBUNPK_OPT_KEEP, BBUNPK_OPT_STDOUT, BBUNPK_OPT_TEST, BBUNPK_OPT_VERBOSE, BBUNPK_SEAMLESS_MAGIC, transformer_state_t::dst_fd, err(), exitcode, fd, filename, fprintf(), free, IF_DESKTOP(), init_transformer_state(), isatty(), LONE_DASH, transformer_state_t::mtime, NULL, O_CREAT, O_EXCL, O_RDONLY, O_WRONLY, open_to_or_warn(), open_zipped, option_mask32, percent, setup_unzip_on_fd, stat::st_mode, stat::st_size, stat(), status, stderr, STDIN_FILENO, STDOUT_FILENO, strlen(), times(), unlink(), utimes(), xclose(), xfunc_die(), xmove_fd(), and xunlink().
Referenced by bzip2_main(), gzip_main(), and lzop_main().
open_to_or_warn()
static int open_to_or_warn (int to_fd, const char * filename, int flags, int mode) static
Definition at line 25 of file bbunzip.c.
 {
     int fd = open3_or_warn(filename, flags, mode);
     if (fd < 0) {
         return 1;
     }
     xmove_fd(fd, to_fd);
     return 0;
 }
References fd, filename, flags, open3_or_warn(), and xmove_fd().
Referenced by bbunpack().