Fennix: Kernel/virtualization/detect.cpp File Reference
detect.cpp File Reference
#include <vm.hpp>
#include <acpi.hpp>
#include <cpu.hpp>
#include <debug.h>
#include "../kernel.h"
Macros
#define VMWARE_MAGIC 0x564D5868 /* hXMV */
#define VMWARE_PORT 0x5658
#define CMD_GETVERSION 0xA
Functions
bool DetectByHypervisor ()
bool IsVMwareBackdoorAvailable ()
bool DetectByCPUID ()
bool DetectByHPET ()
bool IsVirtualizedEnvironment ()
Macro Definition Documentation
CMD_GETVERSION
#define CMD_GETVERSION 0xA
VMWARE_MAGIC
#define VMWARE_MAGIC 0x564D5868 /* hXMV */
VMWARE_PORT
#define VMWARE_PORT 0x5658
Function Documentation
DetectByCPUID()
bool DetectByCPUID ()
Definition at line 118 of file detect.cpp.
 {
     bool IsVM = false;
     if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_INTEL) == 0)
     {
         CPU::x86::Intel::CPUID0x00000001 cpuid00000001;
         cpuid00000001.Get();
         if (cpuid00000001.ECX.Hypervisor == 1)
         {
             debug("Intel: Hypervisor: %d",
                   cpuid00000001.ECX.Hypervisor);
             IsVM = true;
         }
     }
     else if (strcmp(CPU::Vendor(), x86_CPUID_VENDOR_AMD) == 0)
     {
         CPU::x86::AMD::CPUID0x00000001 cpuid00000001;
         cpuid00000001.Get();
         if (cpuid00000001.ECX.Hypervisor == 1)
         {
             debug("AMD: Hypervisor: %d",
                   cpuid00000001.ECX.Hypervisor);
             IsVM = true;
         }
     }
     return IsVM;
 }
References debug, CPU::x86::AMD::CPUID0x00000001::ECX, CPU::x86::Intel::CPUID0x00000001::ECX, CPU::x86::AMD::CPUID0x00000001::Get(), CPU::x86::Intel::CPUID0x00000001::Get(), strcmp, CPU::Vendor(), x86_CPUID_VENDOR_AMD, and x86_CPUID_VENDOR_INTEL.
Referenced by IsVirtualizedEnvironment().
DetectByHPET()
bool DetectByHPET ()
Definition at line 148 of file detect.cpp.
 {
     assert(PowerManager != nullptr);
     void *acpi = PowerManager->GetACPI();
     if (!acpi)
         return false;
     void *hpet = ((ACPI::ACPI *)acpi)->HPET;
     if (!hpet)
         return false;
     ACPI::ACPI::HPETHeader *HPET = (ACPI::ACPI::HPETHeader *)hpet;
     if (strstr((const char *)HPET->Header.OEMID, "BOCHS BXPC") != NULL)
         goto Yes;
     if (strstr((const char *)HPET->Header.OEMID, "VBOX") != NULL)
         goto Yes;
     if (strstr((const char *)HPET->Header.OEMID, "VMWAREVMW") != NULL)
         goto Yes;
     return false;
 Yes:
     debug("HPET: %s", HPET->Header.OEMID);
     return true;
 }
References assert, debug, Power::Power::GetACPI(), ACPI::ACPI::HPETHeader::Header, NULL, ACPI::ACPI::ACPIHeader::OEMID, PowerManager, and strstr().
Referenced by IsVirtualizedEnvironment().
DetectByHypervisor()
bool DetectByHypervisor ()
Definition at line 26 of file detect.cpp.
 {
     const char *Hypervisor = CPU::Hypervisor();
     if (strcmp(Hypervisor, "None") == 0)
         return false;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_VMWARE) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_XENHVM) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_MICROSOFT_HV) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_MICROSOFT_XTA) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_PARALLELS) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_KVM) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_VIRTUALBOX) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_TCG) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_BHYVE) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_ACRN) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_QNX) == 0)
         goto Yes;
     else if (strcmp(Hypervisor, x86_CPUID_VENDOR_APPLE) == 0)
         goto Yes;
     return false;
 Yes:
     debug("Hypervisor: %s", Hypervisor);
     return true;
 }
References debug, CPU::Hypervisor(), strcmp, x86_CPUID_VENDOR_ACRN, x86_CPUID_VENDOR_APPLE, x86_CPUID_VENDOR_BHYVE, x86_CPUID_VENDOR_KVM, x86_CPUID_VENDOR_MICROSOFT_HV, x86_CPUID_VENDOR_MICROSOFT_XTA, x86_CPUID_VENDOR_PARALLELS, x86_CPUID_VENDOR_QNX, x86_CPUID_VENDOR_TCG, x86_CPUID_VENDOR_VIRTUALBOX, x86_CPUID_VENDOR_VMWARE, and x86_CPUID_VENDOR_XENHVM.
Referenced by IsVirtualizedEnvironment().
IsVirtualizedEnvironment()
bool IsVirtualizedEnvironment ()
Detects if the system is running in a virtualized environment.
Returns
true if the system is running in a virtualized environment, false otherwise.
Definition at line 178 of file detect.cpp.
 {
     static bool IsVM = false;
     static int vm_check = 0;
     if (vm_check++)
     {
         debug("Virtualized environment: %s",
               IsVM ? "Yes" : "No");
         return IsVM;
     }
     debug("Detecting virtualized environment...");
     if (DetectByHypervisor())
         IsVM = true;
     if (IsVMwareBackdoorAvailable())
         IsVM = true;
     if (DetectByCPUID())
         IsVM = true;
     if (DetectByHPET())
         IsVM = true;
     /* TODO: Add more detection methods */
     debug("Virtualized environment: %s",
           IsVM ? "Yes" : "No");
     return IsVM;
 }
References debug, DetectByCPUID(), DetectByHPET(), DetectByHypervisor(), and IsVMwareBackdoorAvailable().
Referenced by KernelMainThread().
IsVMwareBackdoorAvailable()
bool IsVMwareBackdoorAvailable ()
Definition at line 62 of file detect.cpp.
 {
     struct
     {
         union
         {
             uint32_t ax;
             uint32_t magic;
         };
         union
         {
             uint32_t bx;
             size_t size;
         };
         union
         {
             uint32_t cx;
             uint16_t command;
         };
         union
         {
             uint32_t dx;
             uint16_t port;
         };
         uint32_t si;
         uint32_t di;
     } cmd{};
 #define VMWARE_MAGIC 0x564D5868 /* hXMV */
 #define VMWARE_PORT 0x5658
 #define CMD_GETVERSION 0xA
     cmd.bx = ~VMWARE_MAGIC;
     cmd.command = CMD_GETVERSION;
     cmd.magic = VMWARE_MAGIC;
     cmd.port = VMWARE_PORT;
     asmv("in %%dx, %0"
          : "+a"(cmd.ax),
            "+b"(cmd.bx),
            "+c"(cmd.cx),
            "+d"(cmd.dx),
            "+S"(cmd.si),
            "+D"(cmd.di));
     if (cmd.bx != VMWARE_MAGIC || cmd.ax == 0xFFFFFFFF)
         return false;
     debug("VMware backdoor version: %d.%d.%d",
           cmd.ax >> 16,
           (cmd.ax >> 8) & 0xFF,
           cmd.ax & 0xFF);
     return true;
 }
References asmv(), cmd, CMD_GETVERSION, debug, port, size, VMWARE_MAGIC, and VMWARE_PORT.
Referenced by DriverProbe(), and IsVirtualizedEnvironment().