Fennix: Userspace/musl/src/ctype/iswprint.c File Reference
iswprint.c File Reference
#include <wctype.h>
Functions
int iswprint (wint_t wc)
int __iswprint_l (wint_t c, locale_t l)
weak_alias (__iswprint_l, iswprint_l)
Function Documentation
__iswprint_l()
int __iswprint_l (wint_t c, locale_t l)
Definition at line 21 of file iswprint.c.
 {
     return iswprint(c);
 }
References c, and iswprint().
iswprint()
int iswprint (wint_t wc)
Definition at line 10 of file iswprint.c.
 {
     if (wc < 0xffU)
         return (wc+1 & 0x7f) >= 0x21;
     if (wc < 0x2028U || wc-0x202aU < 0xd800-0x202a || wc-0xe000U < 0xfff9-0xe000)
         return 1;
     if (wc-0xfffcU > 0x10ffff-0xfffc || (wc&0xfffe)==0xfffe)
         return 0;
     return 1;
 }
Referenced by __iswprint_l(), ansic_quote(), iswctype(), iswgraph(), and unicode_conv_to_printable2().
weak_alias()
weak_alias (__iswprint_l , iswprint_l)