Fennix: Userspace/mlibc/options/posix/generic/grp-stubs.cpp File Reference
grp-stubs.cpp File Reference
#include <grp.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <mlibc/posix-sysdeps.hpp>
Namespaces
anonymous_namespace{grp-stubs.cpp}
Functions
bool anonymous_namespace{grp-stubs.cpp}::open_global_file ()
void anonymous_namespace{grp-stubs.cpp}::close_global_file ()
template<typename F >
void anonymous_namespace{grp-stubs.cpp}::walk_segments (frg::string_view line, char delimiter, F fn)
bool anonymous_namespace{grp-stubs.cpp}::extract_entry (frg::string_view line, group *entry)
void anonymous_namespace{grp-stubs.cpp}::clear_entry (group *entry)
template<typename C >
int anonymous_namespace{grp-stubs.cpp}::walk_file (struct group *entry, C cond)
int anonymous_namespace{grp-stubs.cpp}::copy_to_buffer (struct group *grp, char *buffer, size_t size)
void endgrent (void)
struct group * getgrent (void)
struct group * getgrgid (gid_t gid)
int getgrgid_r (gid_t gid, struct group *grp, char *buffer, size_t size, struct group **result)
struct group * getgrnam (const char *name)
int getgrnam_r (const char *name, struct group *grp, char *buffer, size_t size, struct group **result)
void setgrent (void)
int setgroups (size_t size, const gid_t *list)
int initgroups (const char *, gid_t)
int putgrent (const struct group *, FILE *)
struct group * fgetgrent (FILE *)
int getgrouplist (const char *, gid_t, gid_t *, int *)
Variables
FILE * anonymous_namespace{grp-stubs.cpp}::global_file
Function Documentation
endgrent()
void endgrent (void)
Definition at line 185 of file grp-stubs.cpp.
                     {
     close_global_file();
 }
References anonymous_namespace{grp-stubs.cpp}::close_global_file().
Referenced by main().
fgetgrent()
struct group* fgetgrent (FILE *)
Definition at line 308 of file grp-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
getgrent()
struct group* getgrent (void)
Definition at line 189 of file grp-stubs.cpp.
{
     static group entry;
     char line[512];
     if(!open_global_file()) {
         return nullptr;
     }
     if(fgets(line, 512, global_file)) {
         clear_entry(&entry);
         if(!extract_entry(line, &entry)) {
             errno = EINVAL;
             return nullptr;
         }
         return &entry;
     }
     if(ferror(global_file)) {
         errno = EIO;
     }
     return nullptr;
 }
References anonymous_namespace{grp-stubs.cpp}::clear_entry(), EINVAL, EIO, errno, anonymous_namespace{grp-stubs.cpp}::extract_entry(), ferror(), fgets(), anonymous_namespace{grp-stubs.cpp}::global_file, and anonymous_namespace{grp-stubs.cpp}::open_global_file().
Referenced by main().
getgrgid()
struct group* getgrgid (gid_t gid)
Definition at line 213 of file grp-stubs.cpp.
{
     static group entry;
     int err = walk_file(&entry, [&] (group *entry) {
         return entry->gr_gid == gid;
     });
     if (err) {
         errno = err;
         return nullptr;
     }
     return &entry;
 }
References errno, group::gr_gid, and anonymous_namespace{grp-stubs.cpp}::walk_file().
Referenced by main().
getgrgid_r()
int getgrgid_r (gid_t gid, struct group * grp, char * buffer, size_t size, struct group ** result)
Definition at line 228 of file grp-stubs.cpp.
{
     *result = nullptr;
     int err = walk_file(grp, [&] (group *entry) {
         return entry->gr_gid == gid;
     });
     if (err) {
         return err;
     }
     err = copy_to_buffer(grp, buffer, size);
     if (err) {
         return err;
     }
     *result = grp;
     return 0;
 }
References anonymous_namespace{grp-stubs.cpp}::copy_to_buffer(), group::gr_gid, size, and anonymous_namespace{grp-stubs.cpp}::walk_file().
Referenced by main().
getgrnam()
struct group* getgrnam (const char * name)
Definition at line 247 of file grp-stubs.cpp.
{
     static group entry;
     int err = walk_file(&entry, [&] (group *entry) {
         return !strcmp(entry->gr_name, name);
     });
     if (err) {
         errno = err;
         return nullptr;
     }
     return &entry;
 }
References errno, group::gr_name, name, strcmp(), and anonymous_namespace{grp-stubs.cpp}::walk_file().
Referenced by main().
getgrnam_r()
int getgrnam_r (const char * name, struct group * grp, char * buffer, size_t size, struct group ** result)
Definition at line 262 of file grp-stubs.cpp.
{
     *result = nullptr;
     int err = walk_file(grp, [&] (group *entry) {
         return !strcmp(entry->gr_name, name);
     });
     if (err) {
         return err;
     }
     err = copy_to_buffer(grp, buffer, size);
     if (err) {
         return err;
     }
     *result = grp;
     return 0;
 }
References anonymous_namespace{grp-stubs.cpp}::copy_to_buffer(), group::gr_name, name, size, strcmp(), and anonymous_namespace{grp-stubs.cpp}::walk_file().
Referenced by main().
getgrouplist()
int getgrouplist (const char * , gid_t , gid_t * , int *)
Definition at line 313 of file grp-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: getgrouplist is a stub" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
initgroups()
int initgroups (const char * user, gid_t group)
Definition at line 298 of file grp-stubs.cpp.
{
     mlibc::infoLogger() << "mlibc: initgroups is a stub" << frg::endlog;
     return 0;
 }
References mlibc::infoLogger.
putgrent()
int putgrent (const struct group * , FILE *)
Definition at line 303 of file grp-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
setgrent()
void setgrent (void)
Definition at line 282 of file grp-stubs.cpp.
                     {
     if(!open_global_file()) {
         return;
     }
     rewind(global_file);
 }
References anonymous_namespace{grp-stubs.cpp}::global_file, anonymous_namespace{grp-stubs.cpp}::open_global_file(), and rewind().
Referenced by main().
setgroups()
int setgroups (size_t size, const gid_t * list)
Definition at line 289 of file grp-stubs.cpp.
{
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_setgroups, -1);
     if(int e = mlibc::sys_setgroups(size, list); e) {
         errno = e;
         return -1;
     }
     return 0;
 }
References errno, MLIBC_CHECK_OR_ENOSYS, size, and mlibc::sys_setgroups().