Fennix: sound_module_t Struct Reference
sound_module_t Struct Reference
#include <i_sound.h>
Data Fields
snddevice_t * sound_devices
int num_sound_devices
boolean(* Init)(boolean use_sfx_prefix)
void(* Shutdown)(void)
int(* GetSfxLumpNum)(sfxinfo_t *sfxinfo)
void(* Update)(void)
void(* UpdateSoundParams)(int channel, int vol, int sep)
int(* StartSound)(sfxinfo_t *sfxinfo, int channel, int vol, int sep)
void(* StopSound)(int channel)
boolean(* SoundIsPlaying)(int channel)
void(* CacheSounds)(sfxinfo_t *sounds, int num_sounds)
Detailed Description
Definition at line 105 of file i_sound.h.
Field Documentation
CacheSounds
void(* sound_module_t::CacheSounds) (sfxinfo_t *sounds, int num_sounds)
Definition at line 148 of file i_sound.h.
Referenced by I_PrecacheSounds().
GetSfxLumpNum
int(* sound_module_t::GetSfxLumpNum) (sfxinfo_t *sfxinfo)
Definition at line 123 of file i_sound.h.
Referenced by I_GetSfxLumpNum().
Init
boolean(* sound_module_t::Init) (boolean use_sfx_prefix)
Definition at line 115 of file i_sound.h.
num_sound_devices
int sound_module_t::num_sound_devices
Definition at line 110 of file i_sound.h.
Shutdown
void(* sound_module_t::Shutdown) (void)
Definition at line 119 of file i_sound.h.
Referenced by I_ShutdownSound().
sound_devices
snddevice_t* sound_module_t::sound_devices
Definition at line 109 of file i_sound.h.
SoundIsPlaying
boolean(* sound_module_t::SoundIsPlaying) (int channel)
Definition at line 144 of file i_sound.h.
Referenced by I_SoundIsPlaying().
StartSound
int(* sound_module_t::StartSound) (sfxinfo_t *sfxinfo, int channel, int vol, int sep)
Definition at line 136 of file i_sound.h.
Referenced by I_StartSound().
StopSound
void(* sound_module_t::StopSound) (int channel)
Definition at line 140 of file i_sound.h.
Referenced by I_StopSound().
Update
void(* sound_module_t::Update) (void)
Definition at line 127 of file i_sound.h.
Referenced by I_UpdateSound().
UpdateSoundParams
void(* sound_module_t::UpdateSoundParams) (int channel, int vol, int sep)
Definition at line 131 of file i_sound.h.
Referenced by I_UpdateSoundParams().
The documentation for this struct was generated from the following file:
Userspace/apps/user/games/doomgeneric/doomgeneric/i_sound.h