Fennix: Userspace/apps/base/busybox/libbb/xfunc_die.c File Reference
xfunc_die.c File Reference
#include "libbb.h"
Functions
void FAST_FUNC xfunc_die (void)
Variables
void(* die_func)(void)
Function Documentation
xfunc_die()
void FAST_FUNC xfunc_die (void)
Definition at line 16 of file xfunc_die.c.
 {
     if (die_func)
         die_func();
     exit(xfunc_error_retval);
 }
References die_func, exit(), and xfunc_error_retval.
Referenced by add_squirrel(), bad_record_die(), bb_copyfd_exact_size(), bb_error_msg_and_die(), bb_herror_msg_and_die(), bb_perror_msg_and_die(), bb_show_usage(), bbunpack(), config_read(), d6_listen_socket(), die_if_script(), diffreg(), fflush_stdout_and_exit(), find_key_in_der_cert(), get_der_len(), get_response_or_say_and_die(), hash_file(), ioctl_or_perror_and_die(), ipneigh_list_or_flush(), ntp_init(), paste_main(), print_route(), run_parts_main(), save_fd_on_redirect(), set_master(), set_netns(), start_bunzip(), str2sockaddr(), tls_get_outbuf(), tls_get_random(), udhcp_listen_socket(), unzip_create_leading_dirs(), unzip_main(), up_iface(), xchdir(), xdup_CLOEXEC_and_close(), xfopen_stdin(), xopen_stdin(), xprint_and_close_file(), and xtransformer_write().
Variable Documentation
die_func
void(* die_func) (void) (void)
Definition at line 14 of file xfunc_die.c.
Referenced by getty_main(), hush_main(), init_main(), powertop_main(), sed_main(), top_main(), and xfunc_die().