Fennix Kernel: RTL8139 Namespace Reference
RTL8139 Namespace Reference
Data Structures
struct BARData
Functions
void RTLOB (uint16_t Address, uint8_t Value)
void RTLOW (uint16_t Address, uint16_t Value)
void RTLOL (uint16_t Address, uint32_t Value)
uint8_t RTLIB (uint16_t Address)
uint16_t RTLIW (uint16_t Address)
uint32_t RTLIL (uint16_t Address)
MediaAccessControl GetMAC ()
int DriverEntry (void *Data)
int CallbackHandler (KernelCallback *Data)
int InterruptCallback (CPURegisters *)
Variables
KernelAPI KAPI
PCIDeviceHeader * PCIBaseAddress
BARData BAR
uint8_t * RXBuffer
int TXCurrent
uint16_t CurrentPacket
MediaAccessControl MAC
InternetProtocol::Version4 IP
uint8_t TSAD [4] = {0x20, 0x24, 0x28, 0x2C}
uint8_t TSD [4] = {0x10, 0x14, 0x18, 0x1C}
Data Structure Documentation
RTL8139::BARData
struct RTL8139::BARData
Definition at line 26 of file rtl8139.hpp.
Data Fields
uint16_t IOBase
uint64_t MemoryBase
uint8_t Type
Function Documentation
CallbackHandler()
int RTL8139::CallbackHandler (KernelCallback * Data)
Definition at line 102 of file RTL8139.cpp.
     {
         switch (Data->Reason)
         {
         case AcknowledgeReason:
         {
             debug("Kernel acknowledged the driver.");
             break;
         }
         case ConfigurationReason:
         {
             debug("Driver received configuration data.");
             PCIBaseAddress = reinterpret_cast<PCIDeviceHeader *>(Data->RawPtr);
             if (PCIBaseAddress->VendorID == 0x10EC && PCIBaseAddress->DeviceID == 0x8139)
             {
                 trace("Found RTL-8139.");
                 PCIBaseAddress->Command |= PCI_COMMAND_MASTER | PCI_COMMAND_IO | PCI_COMMAND_MEMORY;
                 uint32_t PCIBAR0 = ((PCIHeader0 *)PCIBaseAddress)->BAR0;
                 uint32_t PCIBAR1 = ((PCIHeader0 *)PCIBaseAddress)->BAR1;
                 BAR.Type = PCIBAR1 & 1;
                 BAR.IOBase = (uint16_t)(PCIBAR0 & (~3));
                 BAR.MemoryBase = PCIBAR1 & (~15);
                 RXBuffer = (uint8_t *)KAPI.Memory.RequestPage(2);
                 RTLOB(0x52, 0x0);
                 RTLOB(0x37, (1 << 4));
                 while ((RTLIB(0x37) & (1 << 4)))
                     ;
                 RTLOL(0x30, static_cast<uint32_t>(reinterpret_cast<uint64_t>(RXBuffer)));
                 RTLOW(0x3C, ((1 << 0) | (1 << 1) | (1 << 2) | (1 << 3) |
                              (1 << 4) | (1 << 5) | (1 << 6) | (1 << 13) |
                              (1 << 14) | (1 << 15)));
                 RTLOL(0x44, ((1 << 0) | (1 << 1) | (1 << 2) | (1 << 3) | (1 << 7)));
                 RTLOB(0x37, 0x0C);
                 MAC = GetMAC();
             }
             else
                 return DEVICE_NOT_SUPPORTED;
             break;
         }
         case FetchReason:
         {
             memcpy(Data->NetworkCallback.Fetch.Name, (void *)"RTL-8139", 9);
             Data->NetworkCallback.Fetch.MAC = MAC.ToHex();
             break;
         }
         case SendReason:
         {
             RTLOL(TSAD[TXCurrent], static_cast<uint32_t>(reinterpret_cast<uint64_t>(Data->NetworkCallback.Send.Data)));
             RTLOL(TSD[TXCurrent++], (uint32_t)Data->NetworkCallback.Send.Length);
             if (TXCurrent > 3)
                 TXCurrent = 0;
             break;
         }
         case StopReason:
         {
             // TODO: Stop the driver.
             debug("Driver stopped.");
             break;
         }
         default:
         {
             warn("Unknown reason.");
             break;
         }
         }
         return OK;
     }
References AcknowledgeReason, BAR, PCI::PCIDeviceHeader::Command, ConfigurationReason, Data, debug, DEVICE_NOT_SUPPORTED, PCI::PCIDeviceHeader::DeviceID, FetchReason, GetMAC(), RTL8139::BARData::IOBase, KAPI, MAC, memcpy(), KernelAPI::Memory, RTL8139::BARData::MemoryBase, OK, PCI::PCI_COMMAND_IO, PCI::PCI_COMMAND_MASTER, PCI::PCI_COMMAND_MEMORY, PCIBaseAddress, KernelAPI::KAPIMemory::RequestPage, RTLIB(), RTLOB(), RTLOL(), RTLOW(), RXBuffer, SendReason, StopReason, MediaAccessControl::ToHex(), trace, TSAD, TSD, TXCurrent, RTL8139::BARData::Type, PCI::PCIDeviceHeader::VendorID, and warn.
DriverEntry()
int RTL8139::DriverEntry (void * Data)
Definition at line 92 of file RTL8139.cpp.
     {
         if (!Data)
             return INVALID_KERNEL_API;
         KAPI = *(KernelAPI *)Data;
         if (KAPI.Version.Major < 0 || KAPI.Version.Minor < 0 || KAPI.Version.Patch < 0)
             return KERNEL_API_VERSION_NOT_SUPPORTED;
         return OK;
     }
References Data, INVALID_KERNEL_API, KAPI, KERNEL_API_VERSION_NOT_SUPPORTED, KernelAPI::KAPIVersion::Major, KernelAPI::KAPIVersion::Minor, OK, KernelAPI::KAPIVersion::Patch, and KernelAPI::Version.
Referenced by StartRTL8139().
GetMAC()
MediaAccessControl RTL8139::GetMAC ()
Definition at line 78 of file RTL8139.cpp.
     {
         uint32_t MAC1 = RTLIL(0x0);
         uint16_t MAC2 = RTLIW(0x4);
         MediaAccessControl mac = {
             mac.Address[0] = (uint8_t)MAC1,
             mac.Address[1] = (uint8_t)(MAC1 >> 8),
             mac.Address[2] = (uint8_t)(MAC1 >> 16),
             mac.Address[3] = (uint8_t)(MAC1 >> 24),
             mac.Address[4] = (uint8_t)MAC2,
             mac.Address[5] = (uint8_t)(MAC2 >> 8)};
         return mac;
     }
References MediaAccessControl::Address, RTLIL(), and RTLIW().
Referenced by CallbackHandler().
InterruptCallback()
int RTL8139::InterruptCallback (CPURegisters *)
Definition at line 173 of file RTL8139.cpp.
     {
         uint16_t Status = RTLIW(0x3E);
         UNUSED(Status);
         uint16_t *Data = (uint16_t *)(RXBuffer + CurrentPacket);
         uint16_t DataLength = *(Data + 1);
         Data = Data + 2;
         KAPI.Command.Network.ReceivePacket(KAPI.Info.DriverUID, (uint8_t *)Data, DataLength);
         CurrentPacket = (uint16_t)((CurrentPacket + DataLength + 4 + 3) & (~3));
         if (CurrentPacket > 8192)
             CurrentPacket -= 8192;
         RTLOW(0x38, CurrentPacket - 0x10);
         RTLOW(0x3E, (1 << 0) | (1 << 2));
         return OK;
     }
References KernelAPI::Command, CurrentPacket, Data, KernelAPI::KAPIInfo::DriverUID, KernelAPI::Info, KAPI, KernelAPI::KAPIDriverTalk::Network, OK, RTLIW(), RTLOW(), RXBuffer, Status, and UNUSED.
RTLIB()
uint8_t RTL8139::RTLIB (uint16_t Address)
Definition at line 54 of file RTL8139.cpp.
     {
         if (BAR.Type == 0)
             return mminb(reinterpret_cast<void *>(BAR.MemoryBase + Address));
         else
             return inportb(BAR.IOBase + Address);
     }
References Address, BAR, RTL8139::BARData::IOBase, RTL8139::BARData::MemoryBase, and RTL8139::BARData::Type.
Referenced by CallbackHandler().
RTLIL()
uint32_t RTL8139::RTLIL (uint16_t Address)
Definition at line 70 of file RTL8139.cpp.
     {
         if (BAR.Type == 0)
             return mminl(reinterpret_cast<void *>(BAR.MemoryBase + Address));
         else
             return inportl(BAR.IOBase + Address);
     }
References Address, BAR, RTL8139::BARData::IOBase, RTL8139::BARData::MemoryBase, and RTL8139::BARData::Type.
Referenced by GetMAC().
RTLIW()
uint16_t RTL8139::RTLIW (uint16_t Address)
Definition at line 62 of file RTL8139.cpp.
     {
         if (BAR.Type == 0)
             return mminw(reinterpret_cast<void *>(BAR.MemoryBase + Address));
         else
             return inportw(BAR.IOBase + Address);
     }
References Address, BAR, RTL8139::BARData::IOBase, RTL8139::BARData::MemoryBase, and RTL8139::BARData::Type.
Referenced by GetMAC(), and InterruptCallback().
RTLOB()
void RTL8139::RTLOB (uint16_t Address, uint8_t Value)
Definition at line 30 of file RTL8139.cpp.
     {
         if (BAR.Type == 0)
             mmoutb(reinterpret_cast<void *>(BAR.MemoryBase + Address), Value);
         else
             outportb(BAR.IOBase + Address, Value);
     }
References Address, BAR, RTL8139::BARData::IOBase, RTL8139::BARData::MemoryBase, and RTL8139::BARData::Type.
Referenced by CallbackHandler().
RTLOL()
void RTL8139::RTLOL (uint16_t Address, uint32_t Value)
Definition at line 46 of file RTL8139.cpp.
     {
         if (BAR.Type == 0)
             mmoutl(reinterpret_cast<void *>(BAR.MemoryBase + Address), Value);
         else
             outportl(BAR.IOBase + Address, Value);
     }
References Address, BAR, RTL8139::BARData::IOBase, RTL8139::BARData::MemoryBase, and RTL8139::BARData::Type.
Referenced by CallbackHandler().
RTLOW()
void RTL8139::RTLOW (uint16_t Address, uint16_t Value)
Definition at line 38 of file RTL8139.cpp.
     {
         if (BAR.Type == 0)
             mmoutw(reinterpret_cast<void *>(BAR.MemoryBase + Address), Value);
         else
             outportw(BAR.IOBase + Address, Value);
     }
References Address, BAR, RTL8139::BARData::IOBase, RTL8139::BARData::MemoryBase, and RTL8139::BARData::Type.
Referenced by CallbackHandler(), and InterruptCallback().
Variable Documentation
BAR
BARData RTL8139::BAR
Definition at line 18 of file RTL8139.cpp.
Referenced by CallbackHandler(), RTLIB(), RTLIL(), RTLIW(), RTLOB(), RTLOL(), and RTLOW().
CurrentPacket
uint16_t RTL8139::CurrentPacket
Definition at line 22 of file RTL8139.cpp.
Referenced by InterruptCallback().
IP
InternetProtocol::Version4 RTL8139::IP
Definition at line 25 of file RTL8139.cpp.
KAPI
KernelAPI RTL8139::KAPI
Definition at line 15 of file RTL8139.cpp.
Referenced by CallbackHandler(), DriverEntry(), and InterruptCallback().
MAC
MediaAccessControl RTL8139::MAC
Definition at line 24 of file RTL8139.cpp.
Referenced by CallbackHandler().
PCIBaseAddress
PCIDeviceHeader* RTL8139::PCIBaseAddress
Definition at line 17 of file RTL8139.cpp.
Referenced by CallbackHandler().
RXBuffer
uint8_t* RTL8139::RXBuffer
Definition at line 20 of file RTL8139.cpp.
Referenced by CallbackHandler(), and InterruptCallback().
TSAD
uint8_t RTL8139::TSAD[4] = {0x20, 0x24, 0x28, 0x2C}
Definition at line 27 of file RTL8139.cpp.
Referenced by CallbackHandler().
TSD
uint8_t RTL8139::TSD[4] = {0x10, 0x14, 0x18, 0x1C}
Definition at line 28 of file RTL8139.cpp.
Referenced by CallbackHandler().
TXCurrent
int RTL8139::TXCurrent
Definition at line 21 of file RTL8139.cpp.
Referenced by CallbackHandler().