Fennix: Userspace/apps/base/busybox/miscutils/hdparm.c File Reference
hdparm.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include <linux/hdreg.h>
#include <sys/mount.h>
Data Structures
struct globals
Macros
#define BLKGETSIZE64 _IOR(0x12,114,size_t)
#define NO_DEV 0xffff
#define ATA_DEV 0x0000
#define ATAPI_DEV 0x0001
#define GEN_CONFIG 0 /* general configuration */
#define LCYLS 1 /* number of logical cylinders */
#define CONFIG 2 /* specific configuration */
#define LHEADS 3 /* number of logical heads */
#define TRACK_BYTES 4 /* number of bytes/track (ATA-1) */
#define SECT_BYTES 5 /* number of bytes/sector (ATA-1) */
#define LSECTS 6 /* number of logical sectors/track */
#define START_SERIAL 10 /* ASCII serial number */
#define LENGTH_SERIAL 10 /* 10 words (20 bytes or characters) */
#define BUF_TYPE 20 /* buffer type (ATA-1) */
#define BUFFER__SIZE 21 /* buffer size (ATA-1) */
#define RW_LONG 22 /* extra bytes in R/W LONG cmd (< ATA-4)*/
#define START_FW_REV 23 /* ASCII firmware revision */
#define LENGTH_FW_REV 4 /* 4 words (8 bytes or characters) */
#define START_MODEL 27 /* ASCII model number */
#define LENGTH_MODEL 20 /* 20 words (40 bytes or characters) */
#define SECTOR_XFER_MAX 47 /* r/w multiple: max sectors xfered */
#define DWORD_IO 48 /* can do double-word IO (ATA-1 only) */
#define CAPAB_0 49 /* capabilities */
#define CAPAB_1 50
#define PIO_MODE 51 /* max PIO mode supported (obsolete)*/
#define DMA_MODE 52 /* max Singleword DMA mode supported (obs)*/
#define WHATS_VALID 53 /* what fields are valid */
#define LCYLS_CUR 54 /* current logical cylinders */
#define LHEADS_CUR 55 /* current logical heads */
#define LSECTS_CUR 56 /* current logical sectors/track */
#define CAPACITY_LSB 57 /* current capacity in sectors */
#define CAPACITY_MSB 58
#define SECTOR_XFER_CUR 59 /* r/w multiple: current sectors xfered */
#define LBA_SECTS_LSB 60 /* LBA: total number of user */
#define LBA_SECTS_MSB 61 /* addressable sectors */
#define SINGLE_DMA 62 /* singleword DMA modes */
#define MULTI_DMA 63 /* multiword DMA modes */
#define ADV_PIO_MODES 64 /* advanced PIO modes supported */
#define DMA_TIME_MIN 65 /* - minimum */
#define DMA_TIME_NORM 66 /* - manufacturer's recommended */
#define PIO_NO_FLOW 67 /* - without flow control */
#define PIO_FLOW 68 /* - with IORDY flow control */
#define PKT_REL 71 /* typical #ns from PKT cmd to bus rel */
#define SVC_NBSY 72 /* typical #ns from SERVICE cmd to !BSY */
#define CDR_MAJOR 73 /* CD ROM: major version number */
#define CDR_MINOR 74 /* CD ROM: minor version number */
#define QUEUE_DEPTH 75 /* queue depth */
#define MAJOR 80 /* major version number */
#define MINOR 81 /* minor version number */
#define CMDS_SUPP_0 82 /* command/feature set(s) supported */
#define CMDS_SUPP_1 83
#define CMDS_SUPP_2 84
#define CMDS_EN_0 85 /* command/feature set(s) enabled */
#define CMDS_EN_1 86
#define CMDS_EN_2 87
#define ULTRA_DMA 88 /* ultra DMA modes */
#define ERASE_TIME 89 /* - ordinary */
#define ENH_ERASE_TIME 90 /* - enhanced */
#define ADV_PWR
#define PSWD_CODE 92 /* master password revision code */
#define HWRST_RSLT 93 /* hardware reset result */
#define ACOUSTIC 94 /* acoustic mgmt values (>= ATA-6) */
#define LBA_LSB 100 /* LBA: maximum. Currently only 48 */
#define LBA_MID 101 /* bits are used, but addr 103 */
#define LBA_48_MSB 102 /* has been reserved for LBA in */
#define LBA_64_MSB 103 /* the future. */
#define RM_STAT 127 /* removable media status notification feature set support */
#define SECU_STATUS 128 /* security status */
#define CFA_PWR_MODE 160 /* CFA power mode 1 */
#define START_MEDIA 176 /* media serial number */
#define LENGTH_MEDIA 20 /* 20 words (40 bytes or characters)*/
#define START_MANUF 196 /* media manufacturer I.D. */
#define LENGTH_MANUF 10 /* 10 words (20 bytes or characters) */
#define INTEGRITY 255 /* integrity word */
#define VALID 0xc000
#define VALID_VAL 0x4000
#define NOVAL_0 0x0000
#define NOVAL_1 0xffff
#define NOT_ATA 0x8000
#define NOT_ATAPI 0x4000 /* (check only if bit 15 == 1) */
#define MEDIA_REMOVABLE 0x0080
#define DRIVE_NOT_REMOVABLE 0x0040 /* bit obsoleted in ATA 6 */
#define INCOMPLETE 0x0004
#define CFA_SUPPORT_VAL 0x848a /* 848a=CFA feature set support */
#define DRQ_RESPONSE_TIME 0x0060
#define DRQ_3MS_VAL 0x0000
#define DRQ_INTR_VAL 0x0020
#define DRQ_50US_VAL 0x0040
#define PKT_SIZE_SUPPORTED 0x0003
#define PKT_SIZE_12_VAL 0x0000
#define PKT_SIZE_16_VAL 0x0001
#define EQPT_TYPE 0x1f00
#define SHIFT_EQPT 8
#define CDROM 0x0005
#define LCYLS_MAX 0x3fff /* maximum allowable value */
#define STBY_NID_VAL 0x37c8 /* (a) and (b) */
#define STBY_ID_VAL 0x738c /* (a) and not (b) */
#define PWRD_NID_VAL 0x8c73 /* not (a) and (b) */
#define PWRD_ID_VAL 0xc837 /* not (a) and not (b) */
#define SECTOR_XFER 0x00ff /* sectors xfered on r/w multiple cmds*/
#define MULTIPLE_SETTING_VALID 0x0100 /* 1=multiple sector setting is valid */
#define STD_STBY 0x2000 /* 1=standard values supported (ATA); 0=vendor specific values */
#define IORDY_SUP 0x0800 /* 1=support; 0=may be supported */
#define IORDY_OFF 0x0400 /* 1=may be disabled */
#define LBA_SUP 0x0200 /* 1=Logical Block Address support */
#define DMA_SUP 0x0100 /* 1=Direct Memory Access support */
#define DMA_IL_SUP 0x8000 /* 1=interleaved DMA support (ATAPI) */
#define CMD_Q_SUP 0x4000 /* 1=command queuing support (ATAPI) */
#define OVLP_SUP 0x2000 /* 1=overlap operation support (ATAPI) */
#define SWRST_REQ 0x1000 /* 1=ATA SW reset required (ATAPI, obsolete */
#define MIN_STANDBY_TIMER 0x0001 /* 1=device specific standby timer value minimum */
#define MODE 0xff00 /* the mode is in the MSBs */
#define OK_W88 0x0004 /* the ultra_dma info is valid */
#define OK_W64_70 0x0002 /* see above for word descriptions */
#define OK_W54_58 0x0001 /* current cyl, head, sector, cap. info valid */
#define MODE_MAX
#define PIO_SUP 0x00ff /* only bits 0 & 1 are used so far, */
#define PIO_MODE_MAX 8 /* but all 8 bits are defined */
#define DEPTH_BITS 0x001f /* bits used for queue depth */
#define MINOR_MAX 0x22
#define CMDS_W82 0x77ff /* word 82: defined command locations*/
#define CMDS_W83 0x3fff /* word 83: defined command locations*/
#define CMDS_W84 0x002f /* word 83: defined command locations*/
#define SUPPORT_48_BIT 0x0400
#define NUM_CMD_FEAT_STR 48
#define ERASE_BITS 0x00ff
#define CBLID 0x2000 /* CBLID status */
#define RST0 0x0001 /* 1=reset to device #0 */
#define DEV_DET 0x0006 /* how device num determined */
#define JUMPER_VAL 0x0002 /* device num determined by jumper */
#define CSEL_VAL 0x0004 /* device num determined by CSEL_VAL */
#define RM_STAT_BITS 0x0003
#define RM_STAT_SUP 0x0001
#define SECU_ENABLED 0x0002
#define SECU_LEVEL 0x0010
#define NUM_SECU_STR 6
#define VALID_W160 0x8000 /* 1=word valid */
#define PWR_MODE_REQ 0x2000 /* 1=CFA power mode req'd by some cmds*/
#define PWR_MODE_OFF 0x1000 /* 1=CFA power moded disabled */
#define MAX_AMPS 0x0fff /* value = max current in ma */
#define SIG 0x00ff /* signature location */
#define SIG_VAL 0x00a5 /* signature value */
#define TIMING_BUF_MB 1
#define TIMING_BUF_BYTES (TIMING_BUF_MB * 1024 * 1024)
#define IS_GET 1
#define IS_SET 2
#define G (*(struct globals*)bb_common_bufsiz1)
#define get_identity (G.get_identity)
#define get_geom (G.get_geom)
#define do_flush (G.do_flush)
#define do_ctimings (G.do_ctimings)
#define do_timings (G.do_timings)
#define reread_partn (G.reread_partn)
#define set_piomode (G.set_piomode)
#define noisy_piomode (G.noisy_piomode)
#define getset_readahead (G.getset_readahead)
#define getset_readonly (G.getset_readonly)
#define getset_unmask (G.getset_unmask)
#define getset_mult (G.getset_mult)
#define getset_dma_q (G.getset_dma_q)
#define getset_nowerr (G.getset_nowerr)
#define getset_keep (G.getset_keep)
#define getset_io32bit (G.getset_io32bit)
#define piomode (G.piomode)
#define Xreadahead (G.Xreadahead)
#define readonly (G.readonly)
#define unmask (G.unmask)
#define mult (G.mult)
#define dma_q (G.dma_q)
#define nowerr (G.nowerr)
#define keep (G.keep)
#define io32bit (G.io32bit)
#define dma (G.dma)
#define getset_dma (G.getset_dma)
#define set_xfermode (G.set_xfermode)
#define get_xfermode (G.get_xfermode)
#define getset_dkeep (G.getset_dkeep)
#define getset_standby (G.getset_standby)
#define getset_lookahead (G.getset_lookahead)
#define getset_prefetch (G.getset_prefetch)
#define getset_defects (G.getset_defects)
#define getset_wcache (G.getset_wcache)
#define getset_doorlock (G.getset_doorlock)
#define set_seagate (G.set_seagate)
#define set_standbynow (G.set_standbynow)
#define set_sleepnow (G.set_sleepnow)
#define get_powermode (G.get_powermode)
#define getset_apmmode (G.getset_apmmode)
#define xfermode_requested (G.xfermode_requested)
#define dkeep (G.dkeep)
#define standby_requested (G.standby_requested)
#define lookahead (G.lookahead)
#define prefetch (G.prefetch)
#define defects (G.defects)
#define wcache (G.wcache)
#define doorlock (G.doorlock)
#define apmmode (G.apmmode)
#define get_IDentity (G.get_IDentity)
#define getset_busstate (G.getset_busstate)
#define perform_reset (G.perform_reset)
#define perform_tristate (G.perform_tristate)
#define unregister_hwif (G.unregister_hwif)
#define scan_hwif (G.scan_hwif)
#define busstate (G.busstate)
#define tristate (G.tristate)
#define hwif (G.hwif)
#define hwif_data (G.hwif_data)
#define hwif_ctrl (G.hwif_ctrl)
#define hwif_irq (G.hwif_irq)
#define INIT_G()
#define ioctl_alt_or_warn(cmd, args, alt) ioctl_alt_func(cmd,args,alt)
Enumerations
enum { fd = 3 }
Functions
static int ioctl_alt_func (int cmd, unsigned char *args, int alt)
static void on_off (int value)
static void print_flag_on_off (int get_arg, const char *s, unsigned long arg)
static void print_value_on_off (const char *str, unsigned long argp)
static void flush_buffer_cache (void)
static void seek_to_zero (void)
static void read_big_block (char *buf)
static unsigned dev_size_mb (void)
static void print_timing (unsigned m, unsigned elapsed_us)
static void do_time (int cache)
static void print_flag (int flag, const char *s, unsigned long value)
static void process_dev (char *devname)
void identify_from_stdin (void)
static int parse_opts (unsigned long *value, int min, int max)
static int parse_opts_0_max (unsigned long *value, int max)
static int parse_opts_0_1 (unsigned long *value)
static int parse_opts_0_INTMAX (unsigned long *value)
static void parse_xfermode (int flag, smallint *get, smallint *set, int *value)
int hdparm_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Variables
struct globals FIX_ALIASING
static const char hdparm_options[] ALIGN1
Macro Definition Documentation
ACOUSTIC
#define ACOUSTIC 94 /* acoustic mgmt values (>= ATA-6) */
Definition at line 202 of file hdparm.c.
ADV_PIO_MODES
#define ADV_PIO_MODES 64 /* advanced PIO modes supported */
Definition at line 175 of file hdparm.c.
ADV_PWR
#define ADV_PWR
Value:
                       91  /* current advanced power management level
                       in low byte, 0x40 in high byte. */
Definition at line 199 of file hdparm.c.
apmmode
#define apmmode (G.apmmode)
Definition at line 478 of file hdparm.c.
ATA_DEV
#define ATA_DEV 0x0000
Definition at line 137 of file hdparm.c.
ATAPI_DEV
#define ATAPI_DEV 0x0001
Definition at line 138 of file hdparm.c.
BLKGETSIZE64
#define BLKGETSIZE64 _IOR(0x12,114,size_t)
Definition at line 131 of file hdparm.c.
BUF_TYPE
#define BUF_TYPE 20 /* buffer type (ATA-1) */
Definition at line 151 of file hdparm.c.
BUFFER__SIZE
#define BUFFER__SIZE 21 /* buffer size (ATA-1) */
Definition at line 152 of file hdparm.c.
busstate
#define busstate (G.busstate)
Definition at line 485 of file hdparm.c.
CAPAB_0
#define CAPAB_0 49 /* capabilities */
Definition at line 160 of file hdparm.c.
CAPAB_1
#define CAPAB_1 50
Definition at line 161 of file hdparm.c.
CAPACITY_LSB
#define CAPACITY_LSB 57 /* current capacity in sectors */
Definition at line 168 of file hdparm.c.
CAPACITY_MSB
#define CAPACITY_MSB 58
Definition at line 169 of file hdparm.c.
CBLID
#define CBLID 0x2000 /* CBLID status */
Definition at line 317 of file hdparm.c.
CDR_MAJOR
#define CDR_MAJOR 73 /* CD ROM: major version number */
Definition at line 184 of file hdparm.c.
CDR_MINOR
#define CDR_MINOR 74 /* CD ROM: minor version number */
Definition at line 185 of file hdparm.c.
CDROM
#define CDROM 0x0005
Definition at line 243 of file hdparm.c.
CFA_PWR_MODE
#define CFA_PWR_MODE 160 /* CFA power mode 1 */
Definition at line 209 of file hdparm.c.
CFA_SUPPORT_VAL
#define CFA_SUPPORT_VAL 0x848a /* 848a=CFA feature set support */
Definition at line 232 of file hdparm.c.
CMD_Q_SUP
#define CMD_Q_SUP 0x4000 /* 1=command queuing support (ATAPI) */
Definition at line 268 of file hdparm.c.
CMDS_EN_0
#define CMDS_EN_0 85 /* command/feature set(s) enabled */
Definition at line 192 of file hdparm.c.
CMDS_EN_1
#define CMDS_EN_1 86
Definition at line 193 of file hdparm.c.
CMDS_EN_2
#define CMDS_EN_2 87
Definition at line 194 of file hdparm.c.
CMDS_SUPP_0
#define CMDS_SUPP_0 82 /* command/feature set(s) supported */
Definition at line 189 of file hdparm.c.
CMDS_SUPP_1
#define CMDS_SUPP_1 83
Definition at line 190 of file hdparm.c.
CMDS_SUPP_2
#define CMDS_SUPP_2 84
Definition at line 191 of file hdparm.c.
CMDS_W82
#define CMDS_W82 0x77ff /* word 82: defined command locations*/
Definition at line 299 of file hdparm.c.
CMDS_W83
#define CMDS_W83 0x3fff /* word 83: defined command locations*/
Definition at line 300 of file hdparm.c.
CMDS_W84
#define CMDS_W84 0x002f /* word 83: defined command locations*/
Definition at line 301 of file hdparm.c.
CONFIG
#define CONFIG 2 /* specific configuration */
Definition at line 144 of file hdparm.c.
CSEL_VAL
#define CSEL_VAL 0x0004 /* device num determined by CSEL_VAL */
Definition at line 321 of file hdparm.c.
defects
#define defects (G.defects)
Definition at line 475 of file hdparm.c.
DEPTH_BITS
#define DEPTH_BITS 0x001f /* bits used for queue depth */
Definition at line 291 of file hdparm.c.
DEV_DET
#define DEV_DET 0x0006 /* how device num determined */
Definition at line 319 of file hdparm.c.
dkeep
#define dkeep (G.dkeep)
Definition at line 471 of file hdparm.c.
dma
#define dma (G.dma)
Definition at line 454 of file hdparm.c.
DMA_IL_SUP
#define DMA_IL_SUP 0x8000 /* 1=interleaved DMA support (ATAPI) */
Definition at line 267 of file hdparm.c.
DMA_MODE
#define DMA_MODE 52 /* max Singleword DMA mode supported (obs)*/
Definition at line 163 of file hdparm.c.
dma_q
#define dma_q (G.dma_q)
Definition at line 450 of file hdparm.c.
DMA_SUP
#define DMA_SUP 0x0100 /* 1=Direct Memory Access support */
Definition at line 266 of file hdparm.c.
DMA_TIME_MIN
#define DMA_TIME_MIN 65 /* - minimum */
Definition at line 177 of file hdparm.c.
DMA_TIME_NORM
#define DMA_TIME_NORM 66 /* - manufacturer's recommended */
Definition at line 178 of file hdparm.c.
do_ctimings
#define do_ctimings (G.do_ctimings)
Definition at line 432 of file hdparm.c.
do_flush
#define do_flush (G.do_flush)
Definition at line 431 of file hdparm.c.
do_timings
#define do_timings (G.do_timings)
Definition at line 433 of file hdparm.c.
doorlock
#define doorlock (G.doorlock)
Definition at line 477 of file hdparm.c.
DRIVE_NOT_REMOVABLE
#define DRIVE_NOT_REMOVABLE 0x0040 /* bit obsoleted in ATA 6 */
Definition at line 230 of file hdparm.c.
DRQ_3MS_VAL
#define DRQ_3MS_VAL 0x0000
Definition at line 234 of file hdparm.c.
DRQ_50US_VAL
#define DRQ_50US_VAL 0x0040
Definition at line 236 of file hdparm.c.
DRQ_INTR_VAL
#define DRQ_INTR_VAL 0x0020
Definition at line 235 of file hdparm.c.
DRQ_RESPONSE_TIME
#define DRQ_RESPONSE_TIME 0x0060
Definition at line 233 of file hdparm.c.
DWORD_IO
#define DWORD_IO 48 /* can do double-word IO (ATA-1 only) */
Definition at line 159 of file hdparm.c.
ENH_ERASE_TIME
#define ENH_ERASE_TIME 90 /* - enhanced */
Definition at line 198 of file hdparm.c.
EQPT_TYPE
#define EQPT_TYPE 0x1f00
Definition at line 240 of file hdparm.c.
ERASE_BITS
#define ERASE_BITS 0x00ff
Definition at line 311 of file hdparm.c.
ERASE_TIME
#define ERASE_TIME 89 /* - ordinary */
Definition at line 197 of file hdparm.c.
G
#define G (*(struct globals*)bb_common_bufsiz1)
Definition at line 428 of file hdparm.c.
GEN_CONFIG
#define GEN_CONFIG 0 /* general configuration */
Definition at line 142 of file hdparm.c.
get_geom
#define get_geom (G.get_geom)
Definition at line 430 of file hdparm.c.
get_identity
#define get_identity (G.get_identity)
Definition at line 429 of file hdparm.c.
get_IDentity
#define get_IDentity (G.get_IDentity)
Definition at line 479 of file hdparm.c.
get_powermode
#define get_powermode (G.get_powermode)
Definition at line 468 of file hdparm.c.
get_xfermode
#define get_xfermode (G.get_xfermode)
Definition at line 457 of file hdparm.c.
getset_apmmode
#define getset_apmmode (G.getset_apmmode)
Definition at line 469 of file hdparm.c.
getset_busstate
#define getset_busstate (G.getset_busstate)
Definition at line 480 of file hdparm.c.
getset_defects
#define getset_defects (G.getset_defects)
Definition at line 462 of file hdparm.c.
getset_dkeep
#define getset_dkeep (G.getset_dkeep)
Definition at line 458 of file hdparm.c.
getset_dma
#define getset_dma (G.getset_dma)
Definition at line 455 of file hdparm.c.
getset_dma_q
#define getset_dma_q (G.getset_dma_q)
Definition at line 441 of file hdparm.c.
getset_doorlock
#define getset_doorlock (G.getset_doorlock)
Definition at line 464 of file hdparm.c.
getset_io32bit
#define getset_io32bit (G.getset_io32bit)
Definition at line 444 of file hdparm.c.
getset_keep
#define getset_keep (G.getset_keep)
Definition at line 443 of file hdparm.c.
getset_lookahead
#define getset_lookahead (G.getset_lookahead)
Definition at line 460 of file hdparm.c.
getset_mult
#define getset_mult (G.getset_mult)
Definition at line 440 of file hdparm.c.
getset_nowerr
#define getset_nowerr (G.getset_nowerr)
Definition at line 442 of file hdparm.c.
getset_prefetch
#define getset_prefetch (G.getset_prefetch)
Definition at line 461 of file hdparm.c.
getset_readahead
#define getset_readahead (G.getset_readahead)
Definition at line 437 of file hdparm.c.
getset_readonly
#define getset_readonly (G.getset_readonly)
Definition at line 438 of file hdparm.c.
getset_standby
#define getset_standby (G.getset_standby)
Definition at line 459 of file hdparm.c.
getset_unmask
#define getset_unmask (G.getset_unmask)
Definition at line 439 of file hdparm.c.
getset_wcache
#define getset_wcache (G.getset_wcache)
Definition at line 463 of file hdparm.c.
hwif
#define hwif (G.hwif)
Definition at line 487 of file hdparm.c.
hwif_ctrl
#define hwif_ctrl (G.hwif_ctrl)
Definition at line 489 of file hdparm.c.
hwif_data
#define hwif_data (G.hwif_data)
Definition at line 488 of file hdparm.c.
hwif_irq
#define hwif_irq (G.hwif_irq)
Definition at line 490 of file hdparm.c.
HWRST_RSLT
#define HWRST_RSLT 93 /* hardware reset result */
Definition at line 201 of file hdparm.c.
INCOMPLETE
#define INCOMPLETE 0x0004
Definition at line 231 of file hdparm.c.
INIT_G
#define INIT_G ()
Value:
    do { \
    setup_common_bufsiz(); \
    BUILD_BUG_ON(sizeof(G) > COMMON_BUFSIZE); \
} while (0)
Definition at line 491 of file hdparm.c.
INTEGRITY
#define INTEGRITY 255 /* integrity word */
Definition at line 214 of file hdparm.c.
io32bit
#define io32bit (G.io32bit)
Definition at line 453 of file hdparm.c.
ioctl_alt_or_warn
#define ioctl_alt_or_warn (cmd, args, alt) ioctl_alt_func(cmd,args,alt)
Definition at line 515 of file hdparm.c.
IORDY_OFF
#define IORDY_OFF 0x0400 /* 1=may be disabled */
Definition at line 264 of file hdparm.c.
IORDY_SUP
#define IORDY_SUP 0x0800 /* 1=support; 0=may be supported */
Definition at line 263 of file hdparm.c.
IS_GET
#define IS_GET 1
Definition at line 348 of file hdparm.c.
IS_SET
#define IS_SET 2
Definition at line 349 of file hdparm.c.
JUMPER_VAL
#define JUMPER_VAL 0x0002 /* device num determined by jumper */
Definition at line 320 of file hdparm.c.
keep
#define keep (G.keep)
Definition at line 452 of file hdparm.c.
LBA_48_MSB
#define LBA_48_MSB 102 /* has been reserved for LBA in */
Definition at line 205 of file hdparm.c.
LBA_64_MSB
#define LBA_64_MSB 103 /* the future. */
Definition at line 206 of file hdparm.c.
LBA_LSB
#define LBA_LSB 100 /* LBA: maximum. Currently only 48 */
Definition at line 203 of file hdparm.c.
LBA_MID
#define LBA_MID 101 /* bits are used, but addr 103 */
Definition at line 204 of file hdparm.c.
LBA_SECTS_LSB
#define LBA_SECTS_LSB 60 /* LBA: total number of user */
Definition at line 171 of file hdparm.c.
LBA_SECTS_MSB
#define LBA_SECTS_MSB 61 /* addressable sectors */
Definition at line 172 of file hdparm.c.
LBA_SUP
#define LBA_SUP 0x0200 /* 1=Logical Block Address support */
Definition at line 265 of file hdparm.c.
LCYLS
#define LCYLS 1 /* number of logical cylinders */
Definition at line 143 of file hdparm.c.
LCYLS_CUR
#define LCYLS_CUR 54 /* current logical cylinders */
Definition at line 165 of file hdparm.c.
LCYLS_MAX
#define LCYLS_MAX 0x3fff /* maximum allowable value */
Definition at line 246 of file hdparm.c.
LENGTH_FW_REV
#define LENGTH_FW_REV 4 /* 4 words (8 bytes or characters) */
Definition at line 155 of file hdparm.c.
LENGTH_MANUF
#define LENGTH_MANUF 10 /* 10 words (20 bytes or characters) */
Definition at line 213 of file hdparm.c.
LENGTH_MEDIA
#define LENGTH_MEDIA 20 /* 20 words (40 bytes or characters)*/
Definition at line 211 of file hdparm.c.
LENGTH_MODEL
#define LENGTH_MODEL 20 /* 20 words (40 bytes or characters) */
Definition at line 157 of file hdparm.c.
LENGTH_SERIAL
#define LENGTH_SERIAL 10 /* 10 words (20 bytes or characters) */
Definition at line 150 of file hdparm.c.
LHEADS
#define LHEADS 3 /* number of logical heads */
Definition at line 145 of file hdparm.c.
LHEADS_CUR
#define LHEADS_CUR 55 /* current logical heads */
Definition at line 166 of file hdparm.c.
lookahead
#define lookahead (G.lookahead)
Definition at line 473 of file hdparm.c.
LSECTS
#define LSECTS 6 /* number of logical sectors/track */
Definition at line 148 of file hdparm.c.
LSECTS_CUR
#define LSECTS_CUR 56 /* current logical sectors/track */
Definition at line 167 of file hdparm.c.
MAJOR
#define MAJOR 80 /* major version number */
Definition at line 187 of file hdparm.c.
MAX_AMPS
#define MAX_AMPS 0x0fff /* value = max current in ma */
Definition at line 336 of file hdparm.c.
MEDIA_REMOVABLE
#define MEDIA_REMOVABLE 0x0080
Definition at line 229 of file hdparm.c.
MIN_STANDBY_TIMER
#define MIN_STANDBY_TIMER 0x0001 /* 1=device specific standby timer value minimum */
Definition at line 273 of file hdparm.c.
MINOR
#define MINOR 81 /* minor version number */
Definition at line 188 of file hdparm.c.
MINOR_MAX
#define MINOR_MAX 0x22
Definition at line 297 of file hdparm.c.
MODE
#define MODE 0xff00 /* the mode is in the MSBs */
Definition at line 276 of file hdparm.c.
MODE_MAX
#define MODE_MAX
Value:
                     7  /* bit definitions force udma <=7 (when
                     * udma >=8 comes out it'll have to be
                     * defined in a new dma_mode word!) */
Definition at line 284 of file hdparm.c.
mult
#define mult (G.mult)
Definition at line 449 of file hdparm.c.
MULTI_DMA
#define MULTI_DMA 63 /* multiword DMA modes */
Definition at line 174 of file hdparm.c.
MULTIPLE_SETTING_VALID
#define MULTIPLE_SETTING_VALID 0x0100 /* 1=multiple sector setting is valid */
Definition at line 259 of file hdparm.c.
NO_DEV
#define NO_DEV 0xffff
Definition at line 136 of file hdparm.c.
noisy_piomode
#define noisy_piomode (G.noisy_piomode)
Definition at line 436 of file hdparm.c.
NOT_ATA
#define NOT_ATA 0x8000
Definition at line 227 of file hdparm.c.
NOT_ATAPI
#define NOT_ATAPI 0x4000 /* (check only if bit 15 == 1) */
Definition at line 228 of file hdparm.c.
NOVAL_0
#define NOVAL_0 0x0000
Definition at line 223 of file hdparm.c.
NOVAL_1
#define NOVAL_1 0xffff
Definition at line 224 of file hdparm.c.
nowerr
#define nowerr (G.nowerr)
Definition at line 451 of file hdparm.c.
NUM_CMD_FEAT_STR
#define NUM_CMD_FEAT_STR 48
Definition at line 303 of file hdparm.c.
NUM_SECU_STR
#define NUM_SECU_STR 6
Definition at line 330 of file hdparm.c.
OK_W54_58
#define OK_W54_58 0x0001 /* current cyl, head, sector, cap. info valid */
Definition at line 281 of file hdparm.c.
OK_W64_70
#define OK_W64_70 0x0002 /* see above for word descriptions */
Definition at line 280 of file hdparm.c.
OK_W88
#define OK_W88 0x0004 /* the ultra_dma info is valid */
Definition at line 279 of file hdparm.c.
OVLP_SUP
#define OVLP_SUP 0x2000 /* 1=overlap operation support (ATAPI) */
Definition at line 269 of file hdparm.c.
perform_reset
#define perform_reset (G.perform_reset)
Definition at line 481 of file hdparm.c.
perform_tristate
#define perform_tristate (G.perform_tristate)
Definition at line 482 of file hdparm.c.
PIO_FLOW
#define PIO_FLOW 68 /* - with IORDY flow control */
Definition at line 181 of file hdparm.c.
PIO_MODE
#define PIO_MODE 51 /* max PIO mode supported (obsolete)*/
Definition at line 162 of file hdparm.c.
PIO_MODE_MAX
#define PIO_MODE_MAX 8 /* but all 8 bits are defined */
Definition at line 288 of file hdparm.c.
PIO_NO_FLOW
#define PIO_NO_FLOW 67 /* - without flow control */
Definition at line 180 of file hdparm.c.
PIO_SUP
#define PIO_SUP 0x00ff /* only bits 0 & 1 are used so far, */
Definition at line 287 of file hdparm.c.
piomode
#define piomode (G.piomode)
Definition at line 445 of file hdparm.c.
PKT_REL
#define PKT_REL 71 /* typical #ns from PKT cmd to bus rel */
Definition at line 182 of file hdparm.c.
PKT_SIZE_12_VAL
#define PKT_SIZE_12_VAL 0x0000
Definition at line 238 of file hdparm.c.
PKT_SIZE_16_VAL
#define PKT_SIZE_16_VAL 0x0001
Definition at line 239 of file hdparm.c.
PKT_SIZE_SUPPORTED
#define PKT_SIZE_SUPPORTED 0x0003
Definition at line 237 of file hdparm.c.
prefetch
#define prefetch (G.prefetch)
Definition at line 474 of file hdparm.c.
PSWD_CODE
#define PSWD_CODE 92 /* master password revision code */
Definition at line 200 of file hdparm.c.
PWR_MODE_OFF
#define PWR_MODE_OFF 0x1000 /* 1=CFA power moded disabled */
Definition at line 335 of file hdparm.c.
PWR_MODE_REQ
#define PWR_MODE_REQ 0x2000 /* 1=CFA power mode req'd by some cmds*/
Definition at line 334 of file hdparm.c.
PWRD_ID_VAL
#define PWRD_ID_VAL 0xc837 /* not (a) and not (b) */
Definition at line 255 of file hdparm.c.
PWRD_NID_VAL
#define PWRD_NID_VAL 0x8c73 /* not (a) and (b) */
Definition at line 254 of file hdparm.c.
QUEUE_DEPTH
#define QUEUE_DEPTH 75 /* queue depth */
Definition at line 186 of file hdparm.c.
readonly
#define readonly (G.readonly)
Definition at line 447 of file hdparm.c.
reread_partn
#define reread_partn (G.reread_partn)
Definition at line 434 of file hdparm.c.
RM_STAT
#define RM_STAT 127 /* removable media status notification feature set support */
Definition at line 207 of file hdparm.c.
RM_STAT_BITS
#define RM_STAT_BITS 0x0003
Definition at line 324 of file hdparm.c.
RM_STAT_SUP
#define RM_STAT_SUP 0x0001
Definition at line 325 of file hdparm.c.
RST0
#define RST0 0x0001 /* 1=reset to device #0 */
Definition at line 318 of file hdparm.c.
RW_LONG
#define RW_LONG 22 /* extra bytes in R/W LONG cmd (< ATA-4)*/
Definition at line 153 of file hdparm.c.
scan_hwif
#define scan_hwif (G.scan_hwif)
Definition at line 484 of file hdparm.c.
SECT_BYTES
#define SECT_BYTES 5 /* number of bytes/sector (ATA-1) */
Definition at line 147 of file hdparm.c.
SECTOR_XFER
#define SECTOR_XFER 0x00ff /* sectors xfered on r/w multiple cmds*/
Definition at line 258 of file hdparm.c.
SECTOR_XFER_CUR
#define SECTOR_XFER_CUR 59 /* r/w multiple: current sectors xfered */
Definition at line 170 of file hdparm.c.
SECTOR_XFER_MAX
#define SECTOR_XFER_MAX 47 /* r/w multiple: max sectors xfered */
Definition at line 158 of file hdparm.c.
SECU_ENABLED
#define SECU_ENABLED 0x0002
Definition at line 328 of file hdparm.c.
SECU_LEVEL
#define SECU_LEVEL 0x0010
Definition at line 329 of file hdparm.c.
SECU_STATUS
#define SECU_STATUS 128 /* security status */
Definition at line 208 of file hdparm.c.
set_piomode
#define set_piomode (G.set_piomode)
Definition at line 435 of file hdparm.c.
set_seagate
#define set_seagate (G.set_seagate)
Definition at line 465 of file hdparm.c.
set_sleepnow
#define set_sleepnow (G.set_sleepnow)
Definition at line 467 of file hdparm.c.
set_standbynow
#define set_standbynow (G.set_standbynow)
Definition at line 466 of file hdparm.c.
set_xfermode
#define set_xfermode (G.set_xfermode)
Definition at line 456 of file hdparm.c.
SHIFT_EQPT
#define SHIFT_EQPT 8
Definition at line 241 of file hdparm.c.
SIG
#define SIG 0x00ff /* signature location */
Definition at line 339 of file hdparm.c.
SIG_VAL
#define SIG_VAL 0x00a5 /* signature value */
Definition at line 340 of file hdparm.c.
SINGLE_DMA
#define SINGLE_DMA 62 /* singleword DMA modes */
Definition at line 173 of file hdparm.c.
standby_requested
#define standby_requested (G.standby_requested)
Definition at line 472 of file hdparm.c.
START_FW_REV
#define START_FW_REV 23 /* ASCII firmware revision */
Definition at line 154 of file hdparm.c.
START_MANUF
#define START_MANUF 196 /* media manufacturer I.D. */
Definition at line 212 of file hdparm.c.
START_MEDIA
#define START_MEDIA 176 /* media serial number */
Definition at line 210 of file hdparm.c.
START_MODEL
#define START_MODEL 27 /* ASCII model number */
Definition at line 156 of file hdparm.c.
START_SERIAL
#define START_SERIAL 10 /* ASCII serial number */
Definition at line 149 of file hdparm.c.
STBY_ID_VAL
#define STBY_ID_VAL 0x738c /* (a) and not (b) */
Definition at line 253 of file hdparm.c.
STBY_NID_VAL
#define STBY_NID_VAL 0x37c8 /* (a) and (b) */
Definition at line 252 of file hdparm.c.
STD_STBY
#define STD_STBY 0x2000 /* 1=standard values supported (ATA); 0=vendor specific values */
Definition at line 262 of file hdparm.c.
SUPPORT_48_BIT
#define SUPPORT_48_BIT 0x0400
Definition at line 302 of file hdparm.c.
SVC_NBSY
#define SVC_NBSY 72 /* typical #ns from SERVICE cmd to !BSY */
Definition at line 183 of file hdparm.c.
SWRST_REQ
#define SWRST_REQ 0x1000 /* 1=ATA SW reset required (ATAPI, obsolete */
Definition at line 270 of file hdparm.c.
TIMING_BUF_BYTES
#define TIMING_BUF_BYTES (TIMING_BUF_MB * 1024 * 1024)
Definition at line 343 of file hdparm.c.
TIMING_BUF_MB
#define TIMING_BUF_MB 1
Definition at line 342 of file hdparm.c.
TRACK_BYTES
#define TRACK_BYTES 4 /* number of bytes/track (ATA-1) */
Definition at line 146 of file hdparm.c.
tristate
#define tristate (G.tristate)
Definition at line 486 of file hdparm.c.
ULTRA_DMA
#define ULTRA_DMA 88 /* ultra DMA modes */
Definition at line 195 of file hdparm.c.
unmask
#define unmask (G.unmask)
Definition at line 448 of file hdparm.c.
unregister_hwif
#define unregister_hwif (G.unregister_hwif)
Definition at line 483 of file hdparm.c.
VALID
#define VALID 0xc000
Definition at line 220 of file hdparm.c.
VALID_VAL
#define VALID_VAL 0x4000
Definition at line 221 of file hdparm.c.
VALID_W160
#define VALID_W160 0x8000 /* 1=word valid */
Definition at line 333 of file hdparm.c.
wcache
#define wcache (G.wcache)
Definition at line 476 of file hdparm.c.
WHATS_VALID
#define WHATS_VALID 53 /* what fields are valid */
Definition at line 164 of file hdparm.c.
xfermode_requested
#define xfermode_requested (G.xfermode_requested)
Definition at line 470 of file hdparm.c.
Xreadahead
#define Xreadahead (G.Xreadahead)
Definition at line 446 of file hdparm.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
fd
Definition at line 352 of file hdparm.c.
 { fd = 3 };
Function Documentation
dev_size_mb()
static unsigned dev_size_mb (void) static
Definition at line 1461 of file hdparm.c.
 {
     union {
         unsigned long long blksize64;
         unsigned blksize32;
     } u;
     if (0 == ioctl(fd, BLKGETSIZE64, &u.blksize64)) { // bytes
         u.blksize64 /= (1024 * 1024);
     } else {
         xioctl(fd, BLKGETSIZE, &u.blksize32); // sectors
         u.blksize64 = u.blksize32 / (2 * 1024);
     }
     if (u.blksize64 > UINT_MAX)
do_time()
static void do_time (int cache) static
Definition at line 1493 of file hdparm.c.
 {
     unsigned max_iterations, iterations;
     unsigned start; /* doesn't need to be long long */
     unsigned elapsed, elapsed2;
     unsigned total_MB;
     char *buf = xmalloc(TIMING_BUF_BYTES);
     if (mlock(buf, TIMING_BUF_BYTES))
         bb_simple_perror_msg_and_die("mlock");
     /* Clear out the device request queues & give them time to complete.
      * NB: *small* delay. User is expected to have a clue and to not run
      * heavy io in parallel with measurements. */
     sync();
     sleep1();
     if (cache) { /* Time cache */
         seek_to_zero();
         read_big_block(buf);
         printf("Timing buffer-cache reads: ");
     } else { /* Time device */
         printf("Timing buffered disk reads:");
     }
     fflush_all();
     /* Now do the timing */
     iterations = 0;
     /* Max time to run (small for cache, avoids getting
      * huge total_MB which can overlow unsigned type) */
     elapsed2 = 510000; /* cache */
     max_iterations = UINT_MAX;
     if (!cache) {
         elapsed2 = 3000000; /* not cache */
         /* Don't want to read past the end! */
         max_iterations = dev_size_mb() / TIMING_BUF_MB;
     }
     start = monotonic_us();
     do {
         if (cache)
             seek_to_zero();
         read_big_block(buf);
         elapsed = (unsigned)monotonic_us() - start;
         ++iterations;
     } while (elapsed < elapsed2 && iterations < max_iterations);
     total_MB = iterations * TIMING_BUF_MB;
     //printf(" elapsed:%u iterations:%u ", elapsed, iterations);
     if (cache) {
         /* Cache: remove lseek() and monotonic_us() overheads
          * from elapsed */
         start = monotonic_us();
         do {
             seek_to_zero();
             elapsed2 = (unsigned)monotonic_us() - start;
         } while (--iterations);
         //printf(" elapsed2:%u ", elapsed2);
         elapsed -= elapsed2;
         total_MB *= 2; // BUFCACHE_FACTOR (why?)
         flush_buffer_cache();
     }
     print_timing(total_MB, elapsed);
flush_buffer_cache()
static void flush_buffer_cache (void) static
Definition at line 1431 of file hdparm.c.
 {
     fsync(fd);              /* flush buffers */
     ioctl_or_warn(fd, BLKFLSBUF, NULL); /* do it again, big time */
 #ifdef HDIO_DRIVE_CMD
     sleep1();
     if (ioctl(fd, HDIO_DRIVE_CMD, NULL) && errno != EINVAL) {   /* await completion */
         if (ENABLE_IOCTL_HEX2STR_ERROR) /* To be coherent with ioctl_or_warn */
             bb_simple_perror_msg("HDIO_DRIVE_CMD");
         else
             bb_perror_msg("ioctl %#x failed", HDIO_DRIVE_CMD);
hdparm_main()
int hdparm_main (int argc, char ** argv)
Definition at line 2116 of file hdparm.c.
 {
     int c;
     int flagcount = 0;
     INIT_G();
     while ((c = getopt(argc, argv, hdparm_options)) >= 0) {
         flagcount++;
         IF_FEATURE_HDPARM_GET_IDENTITY(get_IDentity |= (c == 'I'));
         IF_FEATURE_HDPARM_GET_IDENTITY(get_identity |= (c == 'i'));
         get_geom |= (c == 'g');
         do_flush |= (c == 'f');
         if (c == 'u') getset_unmask    = parse_opts_0_1(&unmask);
     IF_FEATURE_HDPARM_HDIO_GETSET_DMA(
         if (c == 'd') getset_dma       = parse_opts_0_max(&dma, 9);
     )
         if (c == 'n') getset_nowerr    = parse_opts_0_1(&nowerr);
         parse_xfermode((c == 'p'), &noisy_piomode, &set_piomode, &piomode);
         if (c == 'r') getset_readonly  = parse_opts_0_1(&readonly);
         if (c == 'm') getset_mult      = parse_opts_0_INTMAX(&mult /*32*/);
         if (c == 'c') getset_io32bit   = parse_opts_0_INTMAX(&io32bit /*8*/);
         if (c == 'k') getset_keep      = parse_opts_0_1(&keep);
         if (c == 'a') getset_readahead = parse_opts_0_INTMAX(&Xreadahead);
         if (c == 'B') getset_apmmode   = parse_opts(&apmmode, 1, 255);
         do_flush |= do_timings |= (c == 't');
         do_flush |= do_ctimings |= (c == 'T');
 #ifdef HDIO_DRIVE_CMD
         if (c == 'S') getset_standby  = parse_opts_0_max(&standby_requested, 255);
         if (c == 'D') getset_defects  = parse_opts_0_INTMAX(&defects);
         if (c == 'P') getset_prefetch = parse_opts_0_INTMAX(&prefetch);
         parse_xfermode((c == 'X'), &get_xfermode, &set_xfermode, &xfermode_requested);
         if (c == 'K') getset_dkeep     = parse_opts_0_1(&prefetch);
         if (c == 'A') getset_lookahead = parse_opts_0_1(&lookahead);
         if (c == 'L') getset_doorlock  = parse_opts_0_1(&doorlock);
         if (c == 'W') getset_wcache    = parse_opts_0_1(&wcache);
         get_powermode |= (c == 'C');
         set_standbynow |= (c == 'y');
         set_sleepnow |= (c == 'Y');
         reread_partn |= (c == 'z');
         set_seagate |= (c == 'Z');
 #endif
         IF_FEATURE_HDPARM_HDIO_UNREGISTER_HWIF(if (c == 'U') unregister_hwif = parse_opts_0_INTMAX(&hwif));
 #ifdef HDIO_GET_QDMA
         if (c == 'Q') {
             getset_dma_q = parse_opts_0_INTMAX(&dma_q);
         }
 #endif
         IF_FEATURE_HDPARM_HDIO_DRIVE_RESET(perform_reset = (c == 'r'));
         IF_FEATURE_HDPARM_HDIO_TRISTATE_HWIF(if (c == 'x') perform_tristate = parse_opts_0_1(&tristate));
         IF_FEATURE_HDPARM_HDIO_TRISTATE_HWIF(if (c == 'b') getset_busstate = parse_opts_0_max(&busstate, 2));
 #if ENABLE_FEATURE_HDPARM_HDIO_SCAN_HWIF
         if (c == 'R') {
             scan_hwif = parse_opts_0_INTMAX(&hwif_data);
             hwif_ctrl = xatoi_positive((argv[optind]) ? argv[optind] : "");
             hwif_irq  = xatoi_positive((argv[optind+1]) ? argv[optind+1] : "");
             /* Move past the 2 additional arguments */
             argv += 2;
             argc -= 2;
         }
 #endif
     }
     /* When no flags are given (flagcount = 0), -acdgkmnru is assumed. */
     if (!flagcount) {
         getset_mult = getset_io32bit = getset_unmask = getset_keep = getset_readonly = getset_readahead = get_geom = IS_GET;
         IF_FEATURE_HDPARM_HDIO_GETSET_DMA(getset_dma = IS_GET);
     }
     argv += optind;
     if (!*argv) {
         if (ENABLE_FEATURE_HDPARM_GET_IDENTITY && !isatty(STDIN_FILENO))
             identify_from_stdin(); /* EXIT */
         bb_show_usage();
     }
     do {
         process_dev(*argv++);
     } while (*argv);
References apmmode, argc, argv, bb_show_usage(), busstate, c, defects, dma, dma_q, do_ctimings, do_flush, do_timings, doorlock, EXIT_SUCCESS, get_geom, get_identity, get_IDentity, get_powermode, get_xfermode, getopt(), getset_apmmode, getset_busstate, getset_defects, getset_dkeep, getset_dma, getset_dma_q, getset_doorlock, getset_io32bit, getset_keep, getset_lookahead, getset_mult, getset_nowerr, getset_prefetch, getset_readahead, getset_readonly, getset_standby, getset_unmask, getset_wcache, hwif, hwif_ctrl, hwif_data, hwif_irq, identify_from_stdin(), INIT_G, io32bit, IS_GET, isatty(), keep, lookahead, mult, noisy_piomode, nowerr, optind, parse_opts(), parse_opts_0_1(), parse_opts_0_INTMAX(), parse_opts_0_max(), parse_xfermode(), perform_reset, perform_tristate, piomode, prefetch, process_dev(), readonly, reread_partn, scan_hwif, set_piomode, set_seagate, set_sleepnow, set_standbynow, set_xfermode, standby_requested, STDIN_FILENO, unmask, unregister_hwif, wcache, xatoi_positive(), xfermode_requested, and Xreadahead.
identify_from_stdin()
void identify_from_stdin (void)
Referenced by hdparm_main().
ioctl_alt_func()
static int ioctl_alt_func (int cmd, unsigned char * args, int alt) static
Definition at line 508 of file hdparm.c.
 {
     if (!ioctl(fd, cmd, args))
         return 0;
on_off()
static void on_off (int value) static
Definition at line 518 of file hdparm.c.
 {
Referenced by do_set(), and vgetopt32().
parse_opts()
static int parse_opts (unsigned long * value, int min, int max) static
Definition at line 2061 of file hdparm.c.
 {
     if (optarg) {
         *value = xatol_range(optarg, min, max);
         return IS_SET;
References IS_SET, max, min, optarg, and value.
Referenced by hdparm_main(), parse_opts_0_1(), and parse_opts_0_INTMAX().
parse_opts_0_1()
static int parse_opts_0_1 (unsigned long * value) static
Definition at line 2073 of file hdparm.c.
 {
     return parse_opts(value, 0, max);
 }
 static int parse_opts_0_1(unsigned long *value)
References max, parse_opts(), and value.
Referenced by hdparm_main().
parse_opts_0_INTMAX()
static int parse_opts_0_INTMAX (unsigned long * value) static
Definition at line 2077 of file hdparm.c.
 {
     return parse_opts(value, 0, 1);
 }
 static int parse_opts_0_INTMAX(unsigned long *value)
References parse_opts(), and value.
Referenced by hdparm_main().
parse_opts_0_max()
static int parse_opts_0_max (unsigned long * value, int max) static
Definition at line 2069 of file hdparm.c.
 {
Referenced by hdparm_main().
parse_xfermode()
static void parse_xfermode (int flag, smallint * get, smallint * set, int * value) static
Definition at line 2082 of file hdparm.c.
 {
     if (flag) {
         *get = IS_GET;
         if (optarg) {
             *value = translate_xfermode(optarg);
             *set = (*value > -1);
Referenced by hdparm_main().
print_flag()
static void print_flag (int flag, const char * s, unsigned long value) static
Definition at line 1647 of file hdparm.c.
 {
print_flag_on_off()
static void print_flag_on_off (int get_arg, const char * s, unsigned long arg) static
Definition at line 523 of file hdparm.c.
                          : " (off)");
 }
 static void print_flag_on_off(int get_arg, const char *s, unsigned long arg)
 {
     if (get_arg) {
         printf(" setting %s to %lu", s, arg);
print_timing()
static void print_timing (unsigned m, unsigned elapsed_us) static
Definition at line 1479 of file hdparm.c.
 {
     unsigned sec = elapsed_us / 1000000;
     unsigned hs = (elapsed_us % 1000000) / 10000;
     printf("%5u MB in %u.%02u seconds = %u kB/s\n",
         m, sec, hs,
         /* "| 1" prevents div-by-0 */
         (unsigned) ((unsigned long long)m * (1024 * 1000000) / (elapsed_us | 1))
         // ~= (m * 1024) / (elapsed_us / 1000000)
print_value_on_off()
static void print_value_on_off (const char * str, unsigned long argp) static
Definition at line 531 of file hdparm.c.
 {
process_dev()
static void process_dev (char * devname) static
Definition at line 1653 of file hdparm.c.
 {
     /*int fd;*/
     long parm, multcount;
 #ifndef HDIO_DRIVE_CMD
     int force_operation = 0;
 #endif
     /* Please restore args[n] to these values after each ioctl
        except for args[2] */
     unsigned char args[4] = { WIN_SETFEATURES, 0, 0, 0 };
     const char *fmt = " %s\t= %2ld";
     /*fd = xopen_nonblocking(devname);*/
     xmove_fd(xopen_nonblocking(devname), fd);
     printf("\n%s:\n", devname);
     if (getset_readahead == IS_SET) {
         print_flag(getset_readahead, "fs readahead", Xreadahead);
         ioctl_or_warn(fd, BLKRASET, (int *)Xreadahead);
     }
 #if ENABLE_FEATURE_HDPARM_HDIO_UNREGISTER_HWIF
     if (unregister_hwif) {
         printf(" attempting to unregister hwif#%lu\n", hwif);
         ioctl_or_warn(fd, HDIO_UNREGISTER_HWIF, (int *)(unsigned long)hwif);
     }
 #endif
 #if ENABLE_FEATURE_HDPARM_HDIO_SCAN_HWIF
     if (scan_hwif == IS_SET) {
         printf(" attempting to scan hwif (0x%lx, 0x%lx, %lu)\n", hwif_data, hwif_ctrl, hwif_irq);
         args[0] = hwif_data;
         args[1] = hwif_ctrl;
         args[2] = hwif_irq;
         ioctl_or_warn(fd, HDIO_SCAN_HWIF, args);
         args[0] = WIN_SETFEATURES;
         args[1] = 0;
     }
 #endif
     if (set_piomode) {
         if (noisy_piomode) {
             printf(" attempting to ");
             if (piomode == 255)
                 puts("auto-tune PIO mode");
             else if (piomode < 100)
                 printf("set PIO mode to %d\n", piomode);
             else if (piomode < 200)
                 printf("set MDMA mode to %d\n", (piomode-100));
             else
                 printf("set UDMA mode to %d\n", (piomode-200));
         }
         ioctl_or_warn(fd, HDIO_SET_PIO_MODE, (int *)(unsigned long)piomode);
     }
     if (getset_io32bit == IS_SET) {
         print_flag(getset_io32bit, "32-bit IO_support flag", io32bit);
         ioctl_or_warn(fd, HDIO_SET_32BIT, (int *)io32bit);
     }
     if (getset_mult == IS_SET) {
         print_flag(getset_mult, "multcount", mult);
 #ifdef HDIO_DRIVE_CMD
         ioctl_or_warn(fd, HDIO_SET_MULTCOUNT, (void *)mult);
 #else
         force_operation |= (!ioctl_or_warn(fd, HDIO_SET_MULTCOUNT, (void *)mult));
 #endif
     }
     if (getset_readonly == IS_SET) {
         print_flag_on_off(getset_readonly, "readonly", readonly);
         ioctl_or_warn(fd, BLKROSET, &readonly);
     }
     if (getset_unmask == IS_SET) {
         print_flag_on_off(getset_unmask, "unmaskirq", unmask);
         ioctl_or_warn(fd, HDIO_SET_UNMASKINTR, (int *)unmask);
     }
 #if ENABLE_FEATURE_HDPARM_HDIO_GETSET_DMA
     if (getset_dma == IS_SET) {
         print_flag_on_off(getset_dma, "using_dma", dma);
         ioctl_or_warn(fd, HDIO_SET_DMA, (int *)dma);
     }
 #endif /* FEATURE_HDPARM_HDIO_GETSET_DMA */
 #ifdef HDIO_SET_QDMA
     if (getset_dma_q == IS_SET) {
         print_flag_on_off(getset_dma_q, "DMA queue_depth", dma_q);
         ioctl_or_warn(fd, HDIO_SET_QDMA, (int *)dma_q);
     }
 #endif
     if (getset_nowerr == IS_SET) {
         print_flag_on_off(getset_nowerr, "nowerr", nowerr);
         ioctl_or_warn(fd, HDIO_SET_NOWERR, (int *)nowerr);
     }
     if (getset_keep == IS_SET) {
         print_flag_on_off(getset_keep, "keep_settings", keep);
         ioctl_or_warn(fd, HDIO_SET_KEEPSETTINGS, (int *)keep);
     }
 #ifdef HDIO_DRIVE_CMD
     if (getset_doorlock == IS_SET) {
         args[0] = doorlock ? WIN_DOORLOCK : WIN_DOORUNLOCK;
         args[2] = 0;
         print_flag_on_off(getset_doorlock, "drive doorlock", doorlock);
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
         args[0] = WIN_SETFEATURES;
     }
     if (getset_dkeep == IS_SET) {
         /* lock/unlock the drive's "feature" settings */
         print_flag_on_off(getset_dkeep, "drive keep features", dkeep);
         args[2] = dkeep ? 0x66 : 0xcc;
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
     }
     if (getset_defects == IS_SET) {
         args[2] = defects ? 0x04 : 0x84;
         print_flag(getset_defects, "drive defect-mgmt", defects);
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
     }
     if (getset_prefetch == IS_SET) {
         args[1] = prefetch;
         args[2] = 0xab;
         print_flag(getset_prefetch, "drive prefetch", prefetch);
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
         args[1] = 0;
     }
     if (set_xfermode) {
         args[1] = xfermode_requested;
         args[2] = 3;
         print_flag(1, "xfermode", xfermode_requested);
         interpret_xfermode(xfermode_requested);
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
         args[1] = 0;
     }
     if (getset_lookahead == IS_SET) {
         args[2] = lookahead ? 0xaa : 0x55;
         print_flag_on_off(getset_lookahead, "drive read-lookahead", lookahead);
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
     }
     if (getset_apmmode == IS_SET) {
         /* feature register */
         args[2] = (apmmode == 255) ? 0x85 /* disable */ : 0x05 /* set */;
         args[1] = apmmode; /* sector count register 1-255 */
         printf(" setting APM level to %s 0x%02lX (%ld)\n",
             (apmmode == 255) ? "disabled" : "",
             apmmode, apmmode);
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
         args[1] = 0;
     }
     if (getset_wcache == IS_SET) {
 #ifdef DO_FLUSHCACHE
 #ifndef WIN_FLUSHCACHE
 #define WIN_FLUSHCACHE 0xe7
 #endif
 #endif /* DO_FLUSHCACHE */
         args[2] = wcache ? 0x02 : 0x82;
         print_flag_on_off(getset_wcache, "drive write-caching", wcache);
 #ifdef DO_FLUSHCACHE
         if (!wcache)
             ioctl_or_warn(fd, HDIO_DRIVE_CMD, &flushcache);
 #endif /* DO_FLUSHCACHE */
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
 #ifdef DO_FLUSHCACHE
         if (!wcache)
             ioctl_or_warn(fd, HDIO_DRIVE_CMD, &flushcache);
 #endif /* DO_FLUSHCACHE */
     }
     /* In code below, we do not preserve args[0], but the rest
        is preserved, including args[2] */
     args[2] = 0;
     if (set_standbynow) {
 #ifndef WIN_STANDBYNOW1
 #define WIN_STANDBYNOW1 0xE0
 #endif
 #ifndef WIN_STANDBYNOW2
 #define WIN_STANDBYNOW2 0x94
 #endif
         puts(" issuing standby command");
         args[0] = WIN_STANDBYNOW1;
         ioctl_alt_or_warn(HDIO_DRIVE_CMD, args, WIN_STANDBYNOW2);
     }
     if (set_sleepnow) {
 #ifndef WIN_SLEEPNOW1
 #define WIN_SLEEPNOW1 0xE6
 #endif
 #ifndef WIN_SLEEPNOW2
 #define WIN_SLEEPNOW2 0x99
 #endif
         puts(" issuing sleep command");
         args[0] = WIN_SLEEPNOW1;
         ioctl_alt_or_warn(HDIO_DRIVE_CMD, args, WIN_SLEEPNOW2);
     }
     if (set_seagate) {
         args[0] = 0xfb;
         puts(" disabling Seagate auto powersaving mode");
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
     }
     if (getset_standby == IS_SET) {
         args[0] = WIN_SETIDLE1;
         args[1] = standby_requested;
         print_flag(1, "standby", standby_requested);
         interpret_standby(standby_requested);
         ioctl_or_warn(fd, HDIO_DRIVE_CMD, &args);
         args[1] = 0;
     }
 #else   /* HDIO_DRIVE_CMD */
     if (force_operation) {
         char buf[512];
         flush_buffer_cache();
         if (-1 == read(fd, buf, sizeof(buf)))
             bb_simple_perror_msg("read of 512 bytes failed");
     }
 #endif  /* HDIO_DRIVE_CMD */
     if (getset_mult || get_identity) {
         multcount = -1;
         if (ioctl(fd, HDIO_GET_MULTCOUNT, &multcount)) {
             /* To be coherent with ioctl_or_warn. */
             if (getset_mult && ENABLE_IOCTL_HEX2STR_ERROR)
                 bb_simple_perror_msg("HDIO_GET_MULTCOUNT");
             else
                 bb_perror_msg("ioctl %#x failed", HDIO_GET_MULTCOUNT);
         } else if (getset_mult) {
             printf(fmt, "multcount", multcount);
             on_off(multcount != 0);
         }
     }
     if (getset_io32bit) {
         if (!ioctl_or_warn(fd, HDIO_GET_32BIT, &parm)) {
             printf(" IO_support\t=%3ld (", parm);
             if (parm == 0)
                 puts("default 16-bit)");
             else if (parm == 2)
                 puts("16-bit)");
             else if (parm == 1)
                 puts("32-bit)");
             else if (parm == 3)
                 puts("32-bit w/sync)");
             else if (parm == 8)
                 puts("Request-Queue-Bypass)");
             else
                 puts("\?\?\?)");
         }
     }
     if (getset_unmask) {
         if (!ioctl_or_warn(fd, HDIO_GET_UNMASKINTR, &parm))
             print_value_on_off("unmaskirq", parm);
     }
 #if ENABLE_FEATURE_HDPARM_HDIO_GETSET_DMA
     if (getset_dma) {
         if (!ioctl_or_warn(fd, HDIO_GET_DMA, &parm)) {
             printf(fmt, "using_dma", parm);
             if (parm == 8)
                 puts(" (DMA-Assisted-PIO)");
             else
                 on_off(parm != 0);
         }
     }
 #endif
 #ifdef HDIO_GET_QDMA
     if (getset_dma_q) {
         if (!ioctl_or_warn(fd, HDIO_GET_QDMA, &parm))
             print_value_on_off("queue_depth", parm);
     }
 #endif
     if (getset_keep) {
         if (!ioctl_or_warn(fd, HDIO_GET_KEEPSETTINGS, &parm))
             print_value_on_off("keepsettings", parm);
     }
     if (getset_nowerr) {
         if (!ioctl_or_warn(fd, HDIO_GET_NOWERR, &parm))
             print_value_on_off("nowerr", parm);
     }
     if (getset_readonly) {
         if (!ioctl_or_warn(fd, BLKROGET, &parm))
             print_value_on_off("readonly", parm);
     }
     if (getset_readahead) {
         if (!ioctl_or_warn(fd, BLKRAGET, &parm))
             print_value_on_off("readahead", parm);
     }
     if (get_geom) {
         if (!ioctl_or_warn(fd, BLKGETSIZE, &parm)) {
             struct hd_geometry g;
             if (!ioctl_or_warn(fd, HDIO_GETGEO, &g))
                 printf(" geometry\t= %u/%u/%u, sectors = %ld, start = %ld\n",
                     g.cylinders, g.heads, g.sectors, parm, g.start);
         }
     }
 #ifdef HDIO_DRIVE_CMD
     if (get_powermode) {
 #ifndef WIN_CHECKPOWERMODE1
 #define WIN_CHECKPOWERMODE1 0xE5
 #endif
 #ifndef WIN_CHECKPOWERMODE2
 #define WIN_CHECKPOWERMODE2 0x98
 #endif
         const char *state;
         args[0] = WIN_CHECKPOWERMODE1;
         if (ioctl_alt_or_warn(HDIO_DRIVE_CMD, args, WIN_CHECKPOWERMODE2)) {
             if (errno != EIO || args[0] != 0 || args[1] != 0)
                 state = "unknown";
             else
                 state = "sleeping";
         } else
             state = (args[2] == 255) ? "active/idle" : "standby";
         args[1] = args[2] = 0;
         printf(" drive state is:  %s\n", state);
     }
 #endif
 #if ENABLE_FEATURE_HDPARM_HDIO_DRIVE_RESET
     if (perform_reset) {
         ioctl_or_warn(fd, HDIO_DRIVE_RESET, NULL);
     }
 #endif /* FEATURE_HDPARM_HDIO_DRIVE_RESET */
 #if ENABLE_FEATURE_HDPARM_HDIO_TRISTATE_HWIF
     if (perform_tristate) {
         args[0] = 0;
         args[1] = tristate;
         ioctl_or_warn(fd, HDIO_TRISTATE_HWIF, &args);
     }
 #endif /* FEATURE_HDPARM_HDIO_TRISTATE_HWIF */
 #if ENABLE_FEATURE_HDPARM_GET_IDENTITY
     if (get_identity) {
         struct hd_driveid id;
         if (!ioctl(fd, HDIO_GET_IDENTITY, &id)) {
             if (multcount != -1) {
                 id.multsect = multcount;
                 id.multsect_valid |= 1;
             } else
                 id.multsect_valid &= ~1;
             dump_identity(&id);
         } else if (errno == -ENOMSG)
             puts(" no identification info available");
         else if (ENABLE_IOCTL_HEX2STR_ERROR)  /* To be coherent with ioctl_or_warn */
             bb_simple_perror_msg("HDIO_GET_IDENTITY");
         else
             bb_perror_msg("ioctl %#x failed", HDIO_GET_IDENTITY);
     }
     if (get_IDentity) {
         unsigned char args1[4+512]; /* = { ... } will eat 0.5k of rodata! */
         memset(args1, 0, sizeof(args1));
         args1[0] = WIN_IDENTIFY;
         args1[3] = 1;
         if (!ioctl_alt_or_warn(HDIO_DRIVE_CMD, args1, WIN_PIDENTIFY))
             identify((void *)(args1 + 4));
     }
 #endif
 #if ENABLE_FEATURE_HDPARM_HDIO_TRISTATE_HWIF
     if (getset_busstate == IS_SET) {
         print_flag(1, "bus state", busstate);
         bus_state_value(busstate);
         ioctl_or_warn(fd, HDIO_SET_BUSSTATE, (int *)(unsigned long)busstate);
     }
     if (getset_busstate) {
         if (!ioctl_or_warn(fd, HDIO_GET_BUSSTATE, &parm)) {
             printf(fmt, "bus state", parm);
             bus_state_value(parm);
         }
     }
 #endif
     if (reread_partn)
         ioctl_or_warn(fd, BLKRRPART, NULL);
     if (do_ctimings)
         do_time(1 /*,fd*/); /* time cache */
     if (do_timings)
         do_time(0 /*,fd*/); /* time device */
     if (do_flush)
Referenced by hdparm_main().
read_big_block()
static void read_big_block (char * buf) static
Definition at line 1451 of file hdparm.c.
 {
     int i;
     xread(fd, buf, TIMING_BUF_BYTES);
     /* access all sectors of buf to ensure the read fully completed */
seek_to_zero()
static void seek_to_zero (void) static
Definition at line 1446 of file hdparm.c.
 {
Variable Documentation
ALIGN1
const char hdparm_options [] ALIGN1 static
Initial value:
=
    "gfu::n::p:r::m::c::k::a::B:tT"
    IF_FEATURE_HDPARM_HDIO_SCAN_HWIF("R:")
Definition at line 2094 of file hdparm.c.
FIX_ALIASING
struct globals FIX_ALIASING