Fennix Kernel: Kernel/FileSystem/Mounts/Null.cpp File Reference
Null.cpp File Reference
#include <filesystem.hpp>
#include <errno.h>
#include "../../kernel.h"
Functions
ReadFSFunction (Null_Read)
ReadFSFunction (Null_Write)
void Init_Null (Virtual *vfs_ctx)
Variables
FileSystemOperations null_op
Function Documentation
Init_Null()
void Init_Null (Virtual * vfs_ctx)
Definition at line 45 of file Null.cpp.
 {
     Node *n = vfs_ctx->Create("null", CHARDEVICE, DevFS);
     n->Operator = &null_op;
 }
References VirtualFileSystem::CHARDEVICE, VirtualFileSystem::Virtual::Create(), DevFS, null_op, and VirtualFileSystem::Node::Operator.
Referenced by Main().
ReadFSFunction() [1/2]
ReadFSFunction (Null_Read)
Definition at line 25 of file Null.cpp.
 {
     if (Size <= 0)
         return 0;
     memset(Buffer, 0, Size);
     return Size;
 }
References memset(), and Size.
ReadFSFunction() [2/2]
ReadFSFunction (Null_Write)
Definition at line 34 of file Null.cpp.
 {
     return Size;
 }
References Size.
Variable Documentation
null_op
FileSystemOperations null_op
Initial value:
= {
    .Name = "Null",
    .Read = Null_Read,
    .Write = Null_Write,
}
Definition at line 39 of file Null.cpp.
Referenced by Init_Null(), and Main().