Fennix Userspace: Userspace/musl/src/include/sys/time.h File Reference
time.h File Reference
#include "../../../include/sys/time.h"
Functions
hidden int __futimesat (int, const char *, const struct timeval[2])
Function Documentation
__futimesat()
hidden int __futimesat (int dirfd, const char * pathname, const struct timeval times[2])
Definition at line 7 of file futimesat.c.
 {
     struct timespec ts[2];
     if (times) {
         int i;
         for (i=0; i<2; i++) {
             if (times[i].tv_usec >= 1000000ULL)
                 return __syscall_ret(-EINVAL);
             ts[i].tv_sec = times[i].tv_sec;
             ts[i].tv_nsec = times[i].tv_usec * 1000;
         }
     }
     return utimensat(dirfd, pathname, times ? ts : 0, 0);
 }
References __syscall_ret(), dirfd, EINVAL, i, times(), timespec::tv_nsec, timespec::tv_sec, and utimensat().
Referenced by utimes().