Fennix Userspace: Userspace/musl/src/unistd/fchdir.c File Reference
fchdir.c File Reference
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include "syscall.h"
Functions
int fchdir (int fd)
Function Documentation
fchdir()
int fchdir (int fd)
Definition at line 6 of file fchdir.c.
 {
     int ret = __syscall(SYS_fchdir, fd);
     if (ret != -EBADF || __syscall(SYS_fcntl, fd, F_GETFD) < 0)
         return __syscall_ret(ret);
     char buf[15+3*sizeof(int)];
     __procfdname(buf, fd);
     return syscall(SYS_chdir, buf);
 }
References __procfdname(), __syscall, __syscall_ret(), buf, EBADF, F_GETFD, fd, and syscall().
Referenced by buffer_pwrite(), ftpd_main(), logdir_open(), popen_ls(), process_includes(), processorstop(), rotate(), runsv_main(), runsvdir_main(), and xfchdir().