Fennix: RTL8139Device Class Reference
RTL8139Device Class Reference
Data Structures
struct BARData
Public Member Functions
bool IsInitialized ()
size_t write (uint8_t *Buffer, size_t Size)
MediaAccessControl GetMAC ()
int ioctl (NetIoctl req, void *)
void OnInterruptReceived (TrapFrame *)
void Panic ()
RTL8139Device (PCIHeader0 *_Header)
~RTL8139Device ()
Data Fields
dev_t ID
Private Attributes
PCIHeader0 * Header
bool Initialized = false
struct RTL8139Device::BARData BAR
const int BaseBufferSize = 8192
const int WRAPBytes = 1500
const int AdditionalBytes = 16
const int BufferSize
uint8_t * RXBuffer = nullptr
int TXCurrent = 0
uint16_t CurrentPacket = 0
uint8_t TSAD [4] = {0x20, 0x24, 0x28, 0x2C}
uint8_t TSD [4] = {0x10, 0x14, 0x18, 0x1C}
Detailed Description
Definition at line 28 of file rtl8139.cpp.
Data Structure Documentation
RTL8139Device::BARData
struct RTL8139Device::BARData
Definition at line 34 of file rtl8139.cpp.
Data Fields
uint16_t IOBase
uint64_t MemoryBase
uint8_t Type
Constructor & Destructor Documentation
RTL8139Device()
RTL8139Device::RTL8139Device (PCIHeader0 * _Header) inline
Definition at line 120 of file rtl8139.cpp.
         : Header(_Header)
     {
         uint32_t PCIBAR0 = Header->BAR0;
         uint32_t PCIBAR1 = Header->BAR1;
         BAR.Type = PCIBAR0 & 1;
         BAR.IOBase = (uint16_t)(PCIBAR0 & (~3));
         BAR.MemoryBase = PCIBAR1 & (~15);
         RXBuffer = (uint8_t *)AllocateMemory(TO_PAGES(BufferSize));
         /* Power on */
         outb(RegCONFIG1, 0x0);
         /* Software Reset */
         outb(RegCMD, 0x10);
         while (inb(RegCMD) & 0x10)
             Yield();
         /* Initialize receive buffer */
         outl(RegRBSTART, (uint32_t)(reinterpret_cast<uintptr_t>(RXBuffer)));
         /* Configure interrupt mask register */
         outw(RegIMR, (RecOK | RecBad | SendOK | SendBad));
         outl(regRCR, (RcAB | RcAM | RcAPM | RcAAP) | RcWRAP);
         /* Enable receive and transmit */
         outb(RegCMD, 0xC); /* 0xC = RE and TE bit */
         uint32_t MAC1 = inl(RegMAC);
         uint16_t MAC2 = inw(RegMAR);
         MediaAccessControl mac = {
             mac.Address[0] = (uint8_t)MAC1,
             mac.Address[1] = (uint8_t)(MAC1 >> 8),
             mac.Address[2] = (uint8_t)(MAC1 >> 16),
             mac.Address[3] = (uint8_t)(MAC1 >> 24),
             mac.Address[4] = (uint8_t)MAC2,
             mac.Address[5] = (uint8_t)(MAC2 >> 8)};
         Initialized = true;
     }
References MediaAccessControl::Address, AllocateMemory(), BAR, BufferSize, Header, inb(), Initialized, inl(), inw(), RTL8139Device::BARData::IOBase, RTL8139Device::BARData::MemoryBase, outb(), outl(), outw(), RcAAP, RcAB, RcAM, RcAPM, RcWRAP, RecBad, RecOK, RegCMD, RegCONFIG1, RegIMR, RegMAC, RegMAR, RegRBSTART, regRCR, RXBuffer, SendBad, SendOK, TO_PAGES, RTL8139Device::BARData::Type, and Driver::Yield().
~RTL8139Device()
RTL8139Device::~RTL8139Device () inline
Definition at line 162 of file rtl8139.cpp.
     {
         if (!Initialized)
             return;
         /* FIXME: Shutdown code */
     }
References Initialized.
Member Function Documentation
GetMAC()
MediaAccessControl RTL8139Device::GetMAC () inline
Definition at line 69 of file rtl8139.cpp.
     {
         return MediaAccessControl();
     }
ioctl()
int RTL8139Device::ioctl (NetIoctl req, void *) inline
Definition at line 74 of file rtl8139.cpp.
     {
         switch (req)
         {
         case IOCTL_NET_GET_MAC:
         {
             return -ENOSYS;
         }
         default:
             return -EINVAL;
         }
         return 0;
     }
References EINVAL, ENOSYS, and IOCTL_NET_GET_MAC.
Referenced by drvIoctl().
IsInitialized()
bool RTL8139Device::IsInitialized () inline
Definition at line 58 of file rtl8139.cpp.
 { return Initialized; }
References Initialized.
OnInterruptReceived()
void RTL8139Device::OnInterruptReceived (TrapFrame *) inline
Definition at line 88 of file rtl8139.cpp.
     {
         /* Acknowledge interrupt */
         uint16_t status = inw(RegISR);
         DebugLog("%#lx", status);
         /* Read status */
         if (status & RecOK)
         {
             /* Get the current packet */
             uint16_t *data = (uint16_t *)(RXBuffer + CurrentPacket);
             uint16_t dataSz = *(data + 1);
             data += 2;
             ReportNetworkPacket(ID, data, dataSz);
             /* Update CAPR */
 #define RX_READ_PTR_MASK (~0x3)
             CurrentPacket = (uint16_t)((CurrentPacket + dataSz + 4 + 3) & RX_READ_PTR_MASK);
             if (CurrentPacket > BufferSize)
                 CurrentPacket -= uint16_t(BufferSize);
             outw(RegCAPR, CurrentPacket - 0x10);
         }
         /* Clear interrupt */
         outw(RegISR, (RecOK | RecBad | SendOK | SendBad));
     }
References BufferSize, CurrentPacket, DebugLog, ID, inw(), outw(), RecBad, RecOK, RegCAPR, RegISR, Driver::ReportNetworkPacket(), RX_READ_PTR_MASK, RXBuffer, SendBad, SendOK, and status.
Panic()
void RTL8139Device::Panic () inline
Definition at line 116 of file rtl8139.cpp.
     {
     }
Referenced by cxx_Panic().
write()
size_t RTL8139Device::write (uint8_t * Buffer, size_t Size) inline
Definition at line 60 of file rtl8139.cpp.
     {
         outl(TSAD[TXCurrent], (uint32_t)(reinterpret_cast<uint64_t>(Buffer)));
         outl(TSD[TXCurrent++], (uint32_t)Size);
         if (TXCurrent > 3)
             TXCurrent = 0;
         return Size;
     }
References Buffer, outl(), Size, TSAD, TSD, and TXCurrent.
Referenced by drvWrite().
Field Documentation
AdditionalBytes
const int RTL8139Device::AdditionalBytes = 16 private
Definition at line 43 of file rtl8139.cpp.
BAR
struct RTL8139Device::BARData RTL8139Device::BAR private
Referenced by RTL8139Device().
BaseBufferSize
const int RTL8139Device::BaseBufferSize = 8192 private
Definition at line 41 of file rtl8139.cpp.
BufferSize
const int RTL8139Device::BufferSize private
Initial value:
= BaseBufferSize +
                           WRAPBytes +
                           AdditionalBytes
Definition at line 44 of file rtl8139.cpp.
Referenced by OnInterruptReceived(), and RTL8139Device().
CurrentPacket
uint16_t RTL8139Device::CurrentPacket = 0 private
Definition at line 50 of file rtl8139.cpp.
Referenced by OnInterruptReceived().
Header
PCIHeader0* RTL8139Device::Header private
Definition at line 31 of file rtl8139.cpp.
Referenced by RTL8139Device().
ID
dev_t RTL8139Device::ID
Definition at line 56 of file rtl8139.cpp.
Referenced by cxx_Initialize(), and OnInterruptReceived().
Initialized
bool RTL8139Device::Initialized = false private
Definition at line 32 of file rtl8139.cpp.
Referenced by IsInitialized(), RTL8139Device(), and ~RTL8139Device().
RXBuffer
uint8_t* RTL8139Device::RXBuffer = nullptr private
Definition at line 48 of file rtl8139.cpp.
Referenced by OnInterruptReceived(), and RTL8139Device().
TSAD
uint8_t RTL8139Device::TSAD[4] = {0x20, 0x24, 0x28, 0x2C} private
Definition at line 52 of file rtl8139.cpp.
Referenced by write().
TSD
uint8_t RTL8139Device::TSD[4] = {0x10, 0x14, 0x18, 0x1C} private
Definition at line 53 of file rtl8139.cpp.
Referenced by write().
TXCurrent
int RTL8139Device::TXCurrent = 0 private
Definition at line 49 of file rtl8139.cpp.
Referenced by write().
WRAPBytes
const int RTL8139Device::WRAPBytes = 1500 private
Definition at line 42 of file rtl8139.cpp.
The documentation for this class was generated from the following file:
Drivers/network/rtl8139/rtl8139.cpp