Fennix: Userspace/musl/src/stdio/putc.h File Reference
putc.h File Reference
#include "stdio_impl.h"
#include "pthread_impl.h"
Functions
static int locking_putc (int c, FILE *f)
static int do_putc (int c, FILE *f)
Function Documentation
do_putc()
static int do_putc (int c, FILE * f) inline static
Definition at line 16 of file putc.h.
 {
     int l = f->lock;
     if (l < 0 || l && (l & ~MAYBE_WAITERS) == __pthread_self()->tid)
         return putc_unlocked(c, f);
     return locking_putc(c, f);
 }
References __pthread_self, c, f, l, locking_putc(), MAYBE_WAITERS, and putc_unlocked().
Referenced by fputc(), putc(), and putchar().
locking_putc()
static int locking_putc (int c, FILE * f) static
Definition at line 7 of file putc.h.
 {
     if (a_cas(&f->lock, 0, MAYBE_WAITERS-1)) __lockfile(f);
     c = putc_unlocked(c, f);
     if (a_swap(&f->lock, 0) & MAYBE_WAITERS)
         __wake(&f->lock, 1, 1);
     return c;
 }
References __lockfile(), __wake(), a_cas, a_swap, c, f, MAYBE_WAITERS, and putc_unlocked().
Referenced by do_putc().