Fennix: Userspace/apps/base/busybox/sysklogd/logger.c File Reference
logger.c File Reference
Macros
#define strbuf bb_common_bufsiz1
Functions
static int decode (char *name, const CODE *codetab)
static int pencode (char *s)
int logger_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
strbuf
#define strbuf bb_common_bufsiz1
Definition at line 93 of file logger.c.
Function Documentation
decode()
static int decode (char * name, const CODE * codetab) static
Definition at line 49 of file logger.c.
 {
     const CODE *c;
     if (isdigit(*name))
         return atoi(name);
     for (c = codetab; c->c_name; c++) {
         if (!strcasecmp(name, c->c_name)) {
             return c->c_val;
         }
     }
     return -1;
 }
References atoi(), c, isdigit, and strcasecmp.
Referenced by pencode().
logger_main()
int logger_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 96 of file logger.c.
 {
     char *str_p, *str_t;
     int opt;
     int i = 0;
     setup_common_bufsiz();
     /* Fill out the name string early (may be overwritten later) */
     str_t = uid2uname_utoa(geteuid());
     /* Parse any options */
     opt = getopt32(argv, "p:st:", &str_p, &str_t);
     if (opt & 0x2) /* -s */
         i |= LOG_PERROR;
     //if (opt & 0x4) /* -t */
     openlog(str_t, i, 0);
     i = LOG_USER | LOG_NOTICE;
     if (opt & 0x1) /* -p */
         i = pencode(str_p);
     argv += optind;
     if (!argv[0]) {
         while (fgets(strbuf, COMMON_BUFSIZE, stdin)) {
             if (strbuf[0]
              && NOT_LONE_CHAR(strbuf, '\n')
             ) {
                 /* Neither "" nor "\n" */
                 syslog(i, "%s", strbuf);
             }
         }
     } else {
         char *message = NULL;
         int len = 0;
         int pos = 0;
         do {
             len += strlen(*argv) + 1;
             message = xrealloc(message, len + 1);
             sprintf(message + pos, " %s", *argv),
             pos = len;
         } while (*++argv);
         syslog(i, "%s", message + 1); /* skip leading " " */
     }
     closelog();
     return EXIT_SUCCESS;
 }
References argv, closelog(), EXIT_SUCCESS, fgets, geteuid, getopt32(), i, len, LOG_NOTICE, LOG_PERROR, LOG_USER, NOT_LONE_CHAR, NULL, openlog(), opt, optind, pencode(), pos, sprintf(), stdin, strlen(), syslog(), uid2uname_utoa(), and xrealloc.
pencode()
static int pencode (char * s) static
Definition at line 71 of file logger.c.
 {
     char *save;
     int lev, fac = LOG_USER;
     for (save = s; *s && *s != '.'; ++s)
         ;
     if (*s) {
         *s = '\0';
         fac = decode(save, bb_facilitynames);
         if (fac < 0)
             bb_error_msg_and_die("unknown %s name: %s", "facility", save);
         *s++ = '.';
     } else {
         s = save;
     }
     lev = decode(s, bb_prioritynames);
     if (lev < 0)
         bb_error_msg_and_die("unknown %s name: %s", "priority", save);
     return ((lev & LOG_PRIMASK) | (fac & LOG_FACMASK));
 }
References bb_error_msg_and_die(), bb_facilitynames, bb_prioritynames, decode(), LOG_FACMASK, LOG_PRIMASK, LOG_USER, and s.
Referenced by logger_main().