Fennix Userspace: Userspace/mlibc/options/posix/generic/dirent-stubs.cpp File Reference
dirent-stubs.cpp File Reference
#include <errno.h>
#include <dirent.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <stdlib.h>
#include <bits/ensure.h>
#include <frg/allocation.hpp>
#include <mlibc/allocator.hpp>
#include <mlibc/posix-sysdeps.hpp>
#include <mlibc/debug.hpp>
Functions
int alphasort (const struct dirent **a, const struct dirent **b)
int closedir (DIR *dir)
int dirfd (DIR *dir)
DIR * fdopendir (int fd)
DIR * opendir (const char *path)
struct dirent * readdir (DIR *dir)
int readdir_r (DIR *dir, struct dirent *entry, struct dirent **result)
void rewinddir (DIR *dir)
int scandir (const char *path, struct dirent ***res, int(*select)(const struct dirent *), int(*compare)(const struct dirent **, const struct dirent **))
void seekdir (DIR *, long)
long telldir (DIR *)
int versionsort (const struct dirent **a, const struct dirent **b)
Function Documentation
alphasort()
int alphasort (const struct dirent ** a, const struct dirent ** b)
Definition at line 16 of file dirent-stubs.cpp.
{
     return strcoll((*a)->d_name, (*b)->d_name);
 }
References strcoll().
closedir()
int closedir (DIR * dir)
Definition at line 20 of file dirent-stubs.cpp.
{
     // TODO: Deallocate the dir structure.
     close(dir->__handle);
     return 0;
 }
References __mlibc_dir_struct::__handle, and close().
Referenced by do_glob().
dirfd()
int dirfd (DIR * dir)
Definition at line 25 of file dirent-stubs.cpp.
                     {
     return dir->__handle;
 }
References __mlibc_dir_struct::__handle.
Referenced by faccessat(), fchmodat(), fstatat(), mkdirat(), mkfifoat(), mknodat(), openat(), symlinkat(), mlibc::sys_faccessat(), mlibc::sys_fchownat(), mlibc::sys_mkdirat(), mlibc::sys_mkfifoat(), mlibc::sys_mknodat(), mlibc::sys_openat(), mlibc::sys_symlinkat(), mlibc::sys_utimensat(), and utimensat().
fdopendir()
DIR* fdopendir (int fd)
Definition at line 28 of file dirent-stubs.cpp.
{
     struct stat st;
     if(fstat(fd, &st) < 0) {
         return nullptr;
     }
     // Musl implements this, but O_PATH is only declared on the linux abi
     /*if(fcntl(fd, F_GETFL) & O_PATH) {
         errno = EBADF;
         return nullptr;
     }*/
     if(!S_ISDIR(st.st_mode)) {
         errno = ENOTDIR;
         return nullptr;
     }
     auto dir = frg::construct<__mlibc_dir_struct>(getAllocator());
     __ensure(dir);
     dir->__ent_next = 0;
     dir->__ent_limit = 0;
     int flags = fcntl(fd, F_GETFD);
     fcntl(fd, F_SETFD, flags | FD_CLOEXEC);
     dir->__handle = fd;
     return dir;
 }
References __ensure, ENOTDIR, errno, F_GETFD, F_SETFD, fcntl(), fd, FD_CLOEXEC, mlibc::flags, fstat(), getAllocator(), S_ISDIR, and stat::st_mode.
opendir()
DIR* opendir (const char * path)
Definition at line 52 of file dirent-stubs.cpp.
{
     auto dir = frg::construct<__mlibc_dir_struct>(getAllocator());
     __ensure(dir);
     dir->__ent_next = 0;
     dir->__ent_limit = 0;
     MLIBC_CHECK_OR_ENOSYS(mlibc::sys_open_dir, nullptr);
     if(int e = mlibc::sys_open_dir(path, &dir->__handle); e) {
         errno = e;
         frg::destruct(getAllocator(), dir);
         return nullptr;
     }else{
         return dir;
     }
 }
References __ensure, errno, getAllocator(), MLIBC_CHECK_OR_ENOSYS, and mlibc::sys_open_dir().
Referenced by do_glob(), and scandir().
readdir()
struct dirent* readdir (DIR * dir)
Definition at line 67 of file dirent-stubs.cpp.
{
     __ensure(dir->__ent_next <= dir->__ent_limit);
     if(dir->__ent_next == dir->__ent_limit) {
         MLIBC_CHECK_OR_ENOSYS(mlibc::sys_read_entries, nullptr);
         if(int e = mlibc::sys_read_entries(dir->__handle, dir->__ent_buffer, 2048, &dir->__ent_limit); e)
             __ensure(!"mlibc::sys_read_entries() failed");
         dir->__ent_next = 0;
         if(!dir->__ent_limit)
             return nullptr;
     }
     auto entp = reinterpret_cast<struct dirent *>(dir->__ent_buffer + dir->__ent_next);
     // We only copy as many bytes as we need to avoid buffer-overflows.
     memcpy(&dir->__current, entp, offsetof(struct dirent, d_name) + strlen(entp->d_name) + 1);
     dir->__ent_next += entp->d_reclen;
     return &dir->__current;
 }
References __mlibc_dir_struct::__current, __ensure, __mlibc_dir_struct::__ent_buffer, __mlibc_dir_struct::__ent_limit, __mlibc_dir_struct::__ent_next, __mlibc_dir_struct::__handle, dirent::d_name, memcpy(), MLIBC_CHECK_OR_ENOSYS, offsetof, strlen(), and mlibc::sys_read_entries().
Referenced by do_glob(), and scandir().
readdir_r()
int readdir_r (DIR * dir, struct dirent * entry, struct dirent ** result)
Definition at line 84 of file dirent-stubs.cpp.
{
     if(!mlibc::sys_read_entries) {
         MLIBC_MISSING_SYSDEP();
         return ENOSYS;
     }
     __ensure(dir->__ent_next <= dir->__ent_limit);
     if(dir->__ent_next == dir->__ent_limit) {
         if(int e = mlibc::sys_read_entries(dir->__handle, dir->__ent_buffer, 2048, &dir->__ent_limit); e)
             __ensure(!"mlibc::sys_read_entries() failed");
         dir->__ent_next = 0;
         if(!dir->__ent_limit) {
             *result = NULL;
             return 0;
         }
     }
     auto entp = reinterpret_cast<struct dirent *>(dir->__ent_buffer + dir->__ent_next);
     // We only copy as many bytes as we need to avoid buffer-overflows.
     memcpy(entry, entp, offsetof(struct dirent, d_name) + strlen(entp->d_name) + 1);
     dir->__ent_next += entp->d_reclen;
     *result = entry;
     return 0;
 }
References __ensure, __mlibc_dir_struct::__ent_buffer, __mlibc_dir_struct::__ent_limit, __mlibc_dir_struct::__ent_next, __mlibc_dir_struct::__handle, dirent::d_name, ENOSYS, memcpy(), MLIBC_MISSING_SYSDEP, NULL, offsetof, strlen(), and mlibc::sys_read_entries().
rewinddir()
void rewinddir (DIR * dir)
Definition at line 109 of file dirent-stubs.cpp.
{
     lseek(dir->__handle, 0, SEEK_SET);
     dir->__ent_next = 0;
 }
References __mlibc_dir_struct::__ent_next, __mlibc_dir_struct::__handle, lseek(), and SEEK_SET.
scandir()
int scandir (const char * path, struct dirent *** res, int(*)(const struct dirent *) select, int(*)(const struct dirent **, const struct dirent **) compare)
Definition at line 114 of file dirent-stubs.cpp.
{
     DIR *dir = opendir(path);
     if (!dir)
         return -1; // errno will be set by opendir()
     // we should save the errno
     int old_errno = errno;
     errno = 0;
     struct dirent *dir_ent;
     struct dirent **array = nullptr, **tmp = nullptr;
     int length = 0;
     int count = 0;
     while((dir_ent = readdir(dir)) && !errno) {
         if(select && !select(dir_ent))
             continue;
         if(count >= length) {
             length = 2*length + 1;
             tmp = static_cast<struct dirent**>(realloc(array,
                         length * sizeof(struct dirent*)));
             // we need to check the call actually goes through
             // before we overwrite array so that we can
             // deallocate the already written entries should realloc()
             // have failed
             if(!tmp)
                 break;
             array = tmp;
         }
         array[count] = static_cast<struct dirent*>(malloc(dir_ent->d_reclen));
         if(!array[count])
             break;
         memcpy(array[count], dir_ent, dir_ent->d_reclen);
         count++;
     }
     if(errno) {
         if(array)
             while(count-- > 0)
                 free(array[count]);
         free(array);
         return -1;
     }
     // from here we can set the old errno back
     errno = old_errno;
     if(compare)
         qsort(array, count, sizeof(struct dirent*),
                 (int (*)(const void *, const void *)) compare);
     *res = array;
     return count;
 }
References compare(), mlibc::count, dirent::d_reclen, errno, free(), malloc(), memcpy(), opendir(), qsort(), readdir(), realloc(), and select().
seekdir()
void seekdir (DIR * , long)
Definition at line 169 of file dirent-stubs.cpp.
{
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
telldir()
long telldir (DIR *)
Definition at line 173 of file dirent-stubs.cpp.
                     {
     __ensure(!"Not implemented");
     __builtin_unreachable();
 }
References __ensure.
versionsort()
int versionsort (const struct dirent ** a, const struct dirent ** b)
Definition at line 178 of file dirent-stubs.cpp.
{
     return strverscmp((*a)->d_name, (*b)->d_name);
 }
References strverscmp().