Fennix: Userspace/mlibc/options/ansi/musl-generic-math/expf.c File Reference
expf.c File Reference
#include "libm.h"
Functions
float expf (float x)
Variables
static const float half [2] = {0.5,-0.5}
static const float ln2hi = 6.9314575195e-1f
static const float ln2lo = 1.4286067653e-6f
static const float invln2 = 1.4426950216e+0f
static const float P1 = 1.6666625440e-1f
static const float P2 = -2.7667332906e-3f
Function Documentation
expf()
float expf (float x)
Definition at line 30 of file expf.c.
 {
     float_t hi, lo, c, xx, y;
     int k, sign;
     uint32_t hx;
     GET_FLOAT_WORD(hx, x);
     sign = hx >> 31;   /* sign bit of x */
     hx &= 0x7fffffff;  /* high word of |x| */
     /* special cases */
     if (hx >= 0x42aeac50) {  /* if |x| >= -87.33655f or NaN */
         if (hx > 0x7f800000) /* NaN */
             return x;
         if (hx >= 0x42b17218 && !sign) {  /* x >= 88.722839f */
             /* overflow */
             x *= 0x1p127f;
             return x;
         }
         if (sign) {
             /* underflow */
             FORCE_EVAL(-0x1p-149f/x);
             if (hx >= 0x42cff1b5)  /* x <= -103.972084f */
                 return 0;
         }
     }
     /* argument reduction */
     if (hx > 0x3eb17218) {  /* if |x| > 0.5 ln2 */
         if (hx > 0x3f851592)  /* if |x| > 1.5 ln2 */
             k = invln2*x + half[sign];
         else
             k = 1 - sign - sign;
         hi = x - k*ln2hi;  /* k*ln2hi is exact here */
         lo = k*ln2lo;
         x = hi - lo;
     } else if (hx > 0x39000000) {  /* |x| > 2**-14 */
         k = 0;
         hi = x;
         lo = 0;
     } else {
         /* raise inexact */
         FORCE_EVAL(0x1p127f + x);
         return 1 + x;
     }
     /* x is now in primary range */
     xx = x*x;
     c = x - xx*(P1+xx*P2);
     y = 1 + (x*c/(2-c) - lo + hi);
     if (k == 0)
         return y;
     return scalbnf(y, k);
 }
References c, FORCE_EVAL, GET_FLOAT_WORD, half, invln2, k, ln2hi, ln2lo, P1, P2, scalbnf(), x, and y.
Referenced by __expo2f(), __mlibc_cchshf(), cexpf(), coshf(), cpowf(), and erfc2().
Variable Documentation
half
const float half[2] = {0.5,-0.5} static
Definition at line 19 of file expf.c.
Referenced by expf().
invln2
const float invln2 = 1.4426950216e+0f static
Definition at line 22 of file expf.c.
Referenced by expf().
ln2hi
const float ln2hi = 6.9314575195e-1f static
Definition at line 20 of file expf.c.
Referenced by expf().
ln2lo
const float ln2lo = 1.4286067653e-6f static
Definition at line 21 of file expf.c.
Referenced by expf().
P1
const float P1 = 1.6666625440e-1f static
Definition at line 27 of file expf.c.
Referenced by expf().
P2
const float P2 = -2.7667332906e-3f static
Definition at line 28 of file expf.c.
Referenced by expf().