Fennix: Userspace/apps/base/busybox/selinux/matchpathcon.c File Reference
matchpathcon.c File Reference
#include "libbb.h"
Macros
#define OPT_NOT_PRINT (1<<0) /* -n */
#define OPT_NOT_TRANS (1<<1) /* -N */
#define OPT_FCONTEXT (1<<2) /* -f */
#define OPT_PREFIX (1<<3) /* -p */
#define OPT_VERIFY (1<<4) /* -V */
Functions
static int print_matchpathcon (char *path, int noprint)
int matchpathcon_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
OPT_FCONTEXT
#define OPT_FCONTEXT (1<<2) /* -f */
Definition at line 50 of file matchpathcon.c.
OPT_NOT_PRINT
#define OPT_NOT_PRINT (1<<0) /* -n */
Definition at line 48 of file matchpathcon.c.
OPT_NOT_TRANS
#define OPT_NOT_TRANS (1<<1) /* -N */
Definition at line 49 of file matchpathcon.c.
OPT_PREFIX
#define OPT_PREFIX (1<<3) /* -p */
Definition at line 51 of file matchpathcon.c.
OPT_VERIFY
#define OPT_VERIFY (1<<4) /* -V */
Definition at line 52 of file matchpathcon.c.
Function Documentation
matchpathcon_main()
int matchpathcon_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 55 of file matchpathcon.c.
 {
     int error = 0;
     unsigned opts;
     char *fcontext, *prefix, *path;
     opts = getopt32(argv, "^"
             "nNf:p:V"
             "\0"
             "-1" /* at least one param reqd */
             ":?:f--p:p--f" /* mutually exclusive */
             , &fcontext, &prefix
     );
     argv += optind;
     if (opts & OPT_NOT_TRANS) {
         set_matchpathcon_flags(MATCHPATHCON_NOTRANS);
     }
     if (opts & OPT_FCONTEXT) {
         if (matchpathcon_init(fcontext))
             bb_perror_msg_and_die("error while processing %s", fcontext);
     }
     if (opts & OPT_PREFIX) {
         if (matchpathcon_init_prefix(NULL, prefix))
             bb_perror_msg_and_die("error while processing %s", prefix);
     }
     while ((path = *argv++) != NULL) {
         security_context_t con;
         int rc;
         if (!(opts & OPT_VERIFY)) {
             error += print_matchpathcon(path, opts & OPT_NOT_PRINT);
             continue;
         }
         if (selinux_file_context_verify(path, 0)) {
             printf("%s verified\n", path);
             continue;
         }
         if (opts & OPT_NOT_TRANS)
             rc = lgetfilecon_raw(path, &con);
         else
             rc = lgetfilecon(path, &con);
         if (rc >= 0) {
             printf("%s has context %s, should be ", path, con);
             error += print_matchpathcon(path, 1);
             freecon(con);
             continue;
         }
         printf("actual context unknown: "STRERROR_FMT", should be " STRERROR_ERRNO);
         error += print_matchpathcon(path, 1);
     }
     matchpathcon_fini();
     return error;
 }
References argv, bb_perror_msg_and_die(), error, getopt32(), NULL, OPT_FCONTEXT, OPT_NOT_PRINT, OPT_NOT_TRANS, OPT_PREFIX, OPT_VERIFY, optind, prefix(), print_matchpathcon(), printf, rc, STRERROR_ERRNO, and STRERROR_FMT.
print_matchpathcon()
static int print_matchpathcon (char * path, int noprint) static
Definition at line 31 of file matchpathcon.c.
 {
     char *buf;
     int rc = matchpathcon(path, 0, &buf);
     if (rc < 0) {
         bb_perror_msg("matchpathcon(%s) failed", path);
         return 1;
     }
     if (!noprint)
         printf("%s\t%s\n", path, buf);
     else
         puts(buf);
     freecon(buf);
     return 0;
 }
References bb_perror_msg(), buf, printf, puts(), and rc.
Referenced by matchpathcon_main().