Fennix: Userspace/apps/base/busybox/networking/ssl_helper/ssl_helper.c File Reference
ssl_helper.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdarg.h>
#include <fcntl.h>
#include <stdio.h>
#include <time.h>
#include <poll.h>
#include <sys/socket.h>
#include "matrixssl/matrixsslApi.h"
#include "sampleCerts/RSA/ALL_RSA_CAS.h"
#include "sampleCerts/RSA/2048_RSA.h"
#include "sampleCerts/RSA/2048_RSA_KEY.h"
Macros
#define ID_RSA /* RSA Certificate and Key */
#define USE_HEADER_KEYS
#define EXAMPLE_RSA_KEYS
#define dbg(...) ((void)0)
#define STDIN pfd[0]
#define NETWORK pfd[1]
#define STDIN_READY() (pfd[0].revents & (POLLIN|POLLERR|POLLHUP))
#define NETWORK_READY() (pfd[1].revents & (POLLIN|POLLERR|POLLHUP))
Functions
static ssize_t safe_write (int fd, const void *buf, size_t count)
static ssize_t full_write (int fd, const void *buf, size_t len)
static void say (const char *s,...)
static void die (const char *s,...)
static int wait_for_input (void)
static int32 certCb (ssl_t *ssl, psX509Cert_t *cert, int32 alert)
static void close_conn_and_exit (ssl_t *ssl, int fd)
static int encode_data (ssl_t *ssl, const void *data, int len)
static void flush_to_net (ssl_t *ssl, int fd)
static void do_io_until_eof_and_exit (int fd, sslKeys_t *keys)
static sslKeys_t * make_keys (void)
int main (int argc, char **argv)
Variables
static struct pollfd pfd [2]
Macro Definition Documentation
dbg
#define dbg (...) ((void)0)
Definition at line 122 of file ssl_helper.c.
EXAMPLE_RSA_KEYS
#define EXAMPLE_RSA_KEYS
Definition at line 50 of file ssl_helper.c.
ID_RSA
#define ID_RSA /* RSA Certificate and Key */
Definition at line 40 of file ssl_helper.c.
NETWORK
#define NETWORK pfd[1]
Definition at line 130 of file ssl_helper.c.
NETWORK_READY
#define NETWORK_READY () (pfd[1].revents & (POLLIN|POLLERR|POLLHUP))
Definition at line 132 of file ssl_helper.c.
STDIN
#define STDIN pfd[0]
Definition at line 129 of file ssl_helper.c.
STDIN_READY
#define STDIN_READY () (pfd[0].revents & (POLLIN|POLLERR|POLLHUP))
Definition at line 131 of file ssl_helper.c.
USE_HEADER_KEYS
#define USE_HEADER_KEYS
Definition at line 42 of file ssl_helper.c.
Function Documentation
certCb()
static int32 certCb (ssl_t * ssl, psX509Cert_t * cert, int32 alert) static
Definition at line 143 of file ssl_helper.c.
 {
     /* Example to allow anonymous connections based on a define */
     if (alert > 0) {
         return SSL_ALLOW_ANON_CONNECTION; // = 254
     }
 #if 0
     /* Validate the 'not before' and 'not after' dates, etc */
     return PS_FAILURE; /* if we don't like this cert */
 #endif
     return PS_SUCCESS;
 }
References PS_FAILURE, and PS_SUCCESS.
Referenced by do_io_until_eof_and_exit().
close_conn_and_exit()
static void close_conn_and_exit (ssl_t * ssl, int fd) static
Definition at line 156 of file ssl_helper.c.
 {
     unsigned char *buf;
     int len;
     fcntl(fd, F_SETFL, fcntl(fd, F_GETFL) | O_NONBLOCK);
     /* Quick attempt to send a closure alert, don't worry about failure */
     if (matrixSslEncodeClosureAlert(ssl) >= 0) {
         len = matrixSslGetOutdata(ssl, &buf);
         if (len > 0) {
             len = safe_write(fd, buf, len);
             //if (len > 0) {
             //  matrixSslSentData(ssl, len);
             //}
         }
     }
     //matrixSslDeleteSession(ssl);
     shutdown(fd, SHUT_WR);
     exit(0);
 }
References buf, exit(), F_GETFL, F_SETFL, fcntl(), fd, len, O_NONBLOCK, safe_write(), SHUT_WR, and shutdown().
Referenced by do_io_until_eof_and_exit().
die()
static void die (const char * s, ...) static
Definition at line 106 of file ssl_helper.c.
 {
     char buf[256];
     va_list p;
     int sz;
     va_start(p, s);
     sz = vsnprintf(buf, sizeof(buf), s, p);
     full_write(STDERR_FILENO, buf, sz >= 0 && sz < sizeof(buf) ? sz : strlen(buf));
     exit(1);
     va_end(p);
 }
References buf, exit(), full_write(), p, s, STDERR_FILENO, strlen(), va_end, va_start, and vsnprintf().
Referenced by do_io_until_eof_and_exit(), encode_data(), flush_to_net(), main(), and make_keys().
do_io_until_eof_and_exit()
static void do_io_until_eof_and_exit (int fd, sslKeys_t * keys) static
Definition at line 209 of file ssl_helper.c.
 {
     int rc;
     int len;
     uint32_t len32u;
     sslSessionId_t *sid;
     ssl_t *ssl;
     unsigned char *buf;
     NETWORK.fd = fd;
     /* Note! STDIN.fd is disabled (-1) until SSL handshake is over:
      * we do not attempt to feed any user data to MatrixSSL
      * before it is ready.
      */
     matrixSslNewSessionId(&sid);
     rc = matrixSslNewClientSession(&ssl, keys, sid, 0, certCb, NULL, NULL, 0);
 dbg("matrixSslNewClientSession:rc=%d\n", rc);
     if (rc != MATRIXSSL_REQUEST_SEND)
         die("matrixSslNewClientSession\n");
     len = 0; /* only to suppress compiler warning */
  again:
     switch (rc) {
     case MATRIXSSL_REQUEST_SEND:
         dbg("MATRIXSSL_REQUEST_SEND\n");
         flush_to_net(ssl, fd);
         goto poll_input;
     case 0:
         dbg("rc==0\n");
         flush_to_net(ssl, fd);
         goto poll_input;
     case MATRIXSSL_REQUEST_CLOSE:
         /* what does this mean if we are here? */
         dbg("MATRIXSSL_REQUEST_CLOSE\n");
         close_conn_and_exit(ssl, fd);
     case MATRIXSSL_HANDSHAKE_COMPLETE:
         dbg("MATRIXSSL_HANDSHAKE_COMPLETE\n");
         /* Init complete, can start reading local user's data: */
         STDIN.fd = STDIN_FILENO;
  poll_input:
         wait_for_input();
         if (STDIN_READY()) {
             char ibuf[4 * 1024];
             dbg("reading stdin\n");
             len = read(STDIN_FILENO, ibuf, sizeof(ibuf));
             if (len < 0)
                 die("read error on stdin\n");
             if (len == 0)
                 STDIN.fd = -1;
             else {
                 len = encode_data(ssl, ibuf, len);
                 if (len) {
                     rc = MATRIXSSL_REQUEST_SEND;
 dbg("rc=%d\n", rc);
                     goto again;
                 }
             }
         }
  read_network:
         if (NETWORK_READY()) {
             dbg("%s%s%s\n",
                 (pfd[1].revents & POLLIN)  ? "POLLIN"  : "",
                 (pfd[1].revents & POLLERR) ? "|POLLERR" : "",
                 (pfd[1].revents & POLLHUP) ? "|POLLHUP" : ""
             );
             len = matrixSslGetReadbuf(ssl, &buf);
             if (len <= 0)
                 die("matrixSslGetReadbuf\n");
             dbg("reading net up to %d\n", len);
             len = read(fd, buf, len);
             dbg("reading net:%d\n", len);
             if (len < 0)
                 die("read error on network\n");
             if (len == 0) /*eof*/
                 NETWORK.fd = -1;
             len32u = len;
             rc = matrixSslReceivedData(ssl, len, &buf, &len32u);
 dbg("matrixSslReceivedData:rc=%d\n", rc);
             len = len32u;
             if (rc < 0)
                 die("matrixSslReceivedData\n");
         }
         goto again;
     case MATRIXSSL_APP_DATA:
         dbg("MATRIXSSL_APP_DATA: writing stdout\n");
         do {
             if (full_write(STDOUT_FILENO, buf, len) != len)
                 die("write to stdout\n");
             len32u = len;
             rc = matrixSslProcessedData(ssl, &buf, &len32u);
 //this was seen returning rc=0:
 dbg("matrixSslProcessedData:rc=%d\n", rc);
             len = len32u;
         } while (rc == MATRIXSSL_APP_DATA);
         if (pfd[1].fd == -1) {
             /* Already saw EOF on network, and we processed
              * and wrote out all ssl data. Signal it:
              */
             close(STDOUT_FILENO);
         }
         goto again;
     case MATRIXSSL_REQUEST_RECV:
         dbg("MATRIXSSL_REQUEST_RECV\n");
         wait_for_input();
         goto read_network;
     case MATRIXSSL_RECEIVED_ALERT:
         dbg("MATRIXSSL_RECEIVED_ALERT\n");
         /* The first byte of the buffer is the level */
         /* The second byte is the description */
         if (buf[0] == SSL_ALERT_LEVEL_FATAL)
             die("Fatal alert\n");
         /* Closure alert is normal (and best) way to close */
         if (buf[1] == SSL_ALERT_CLOSE_NOTIFY)
             close_conn_and_exit(ssl, fd);
         die("Warning alert\n");
         len32u = len;
         rc = matrixSslProcessedData(ssl, &buf, &len32u);
 dbg("matrixSslProcessedData:rc=%d\n", rc);
         len = len32u;
         goto again;
     default:
         /* If rc < 0 it is an error */
         die("bad rc:%d\n", rc);
     }
 }
References buf, certCb(), close(), close_conn_and_exit(), dbg, die(), encode_data(), fd, flush_to_net(), full_write(), keys, len, NETWORK, NETWORK_READY, NULL, pfd, POLLERR, POLLHUP, POLLIN, rc, read(), pollfd::revents, STDIN, STDIN_FILENO, STDIN_READY, STDOUT_FILENO, and wait_for_input().
Referenced by main().
encode_data()
static int encode_data (ssl_t * ssl, const void * data, int len) static
Definition at line 177 of file ssl_helper.c.
 {
     unsigned char *buf;
     int available;
     available = matrixSslGetWritebuf(ssl, &buf, len);
     if (available < 0)
         die("matrixSslGetWritebuf\n");
     if (len > available)
         die("len > available\n");
     memcpy(buf, data, len);
     if (matrixSslEncodeWritebuf(ssl, len) < 0)
         die("matrixSslEncodeWritebuf\n");
     return len;
 }
References buf, die(), len, and memcpy.
Referenced by do_io_until_eof_and_exit().
flush_to_net()
static void flush_to_net (ssl_t * ssl, int fd) static
Definition at line 193 of file ssl_helper.c.
 {
     int rc;
     int len;
     unsigned char *buf;
     while ((len = matrixSslGetOutdata(ssl, &buf)) > 0) {
         dbg("writing net %d bytes\n", len);
         if (full_write(fd, buf, len) != len)
             die("write to network\n");
         rc = matrixSslSentData(ssl, len);
         if (rc < 0)
             die("matrixSslSentData\n");
     }
 }
References buf, dbg, die(), fd, full_write(), len, and rc.
Referenced by do_io_until_eof_and_exit().
full_write()
static ssize_t full_write (int fd, const void * buf, size_t len) static
Definition at line 67 of file ssl_helper.c.
 {
     ssize_t cc;
     ssize_t total;
     total = 0;
     while (len) {
         cc = safe_write(fd, buf, len);
         if (cc < 0) {
             if (total) {
                 /* we already wrote some! */
                 /* user can do another write to know the error code */
                 return total;
             }
             return cc;  /* write() returns -1 on failure. */
         }
         total += cc;
         buf = ((const char *)buf) + cc;
         len -= cc;
     }
     return total;
 }
References buf, fd, len, safe_write(), and total.
Referenced by die(), do_io_until_eof_and_exit(), flush_to_net(), and say().
main()
int main (int argc , char ** argv)
Definition at line 378 of file ssl_helper.c.
 {
     int fd;
     char *fd_str;
     if (!argv[1])
         die("Syntax error\n");
     if (argv[1][0] != '-')
         die("Syntax error\n");
     if (argv[1][1] != 'd')
         die("Syntax error\n");
     fd_str = argv[1] + 2;
     if (!fd_str[0])
         fd_str = argv[2];
     if (!fd_str || fd_str[0] < '0' || fd_str[0] > '9')
         die("Syntax error\n");
     fd = atoi(fd_str);
     if (fd < 3)
         die("Syntax error\n");
     if (matrixSslOpen() < 0)
         die("matrixSslOpen\n");
     do_io_until_eof_and_exit(fd, make_keys());
     /* does not return */
     return 0;
 }
References argv, atoi(), die(), do_io_until_eof_and_exit(), fd, and make_keys().
make_keys()
static sslKeys_t* make_keys (void) static
Definition at line 343 of file ssl_helper.c.
 {
     int rc, CAstreamLen;
     char *CAstream;
     sslKeys_t *keys;
     if (matrixSslNewKeys(&keys) < 0)
         die("matrixSslNewKeys\n");
 #ifdef USE_HEADER_KEYS
     /*
      * In-memory based keys
      * Build the CA list first for potential client auth usage
      */
     CAstream = NULL;
     CAstreamLen = sizeof(RSACAS);
     if (CAstreamLen > 0) {
         CAstream = psMalloc(NULL, CAstreamLen);
         memcpy(CAstream, RSACAS, sizeof(RSACAS));
     }
  #ifdef ID_RSA
     rc = matrixSslLoadRsaKeysMem(keys, RSA2048, sizeof(RSA2048),
             RSA2048KEY, sizeof(RSA2048KEY), (unsigned char*)CAstream,
             CAstreamLen);
     if (rc < 0)
         die("matrixSslLoadRsaKeysMem\n");
  #endif
     if (CAstream)
         psFree(CAstream);
 #endif /* USE_HEADER_KEYS */
     return keys;
 }
References die(), keys, memcpy, NULL, psFree, and rc.
Referenced by main().
safe_write()
static ssize_t safe_write (int fd, const void * buf, size_t count) static
Definition at line 56 of file ssl_helper.c.
 {
     ssize_t n;
     do {
         n = write(fd, buf, count);
     } while (n < 0 && errno == EINTR);
     return n;
 }
References buf, count, EINTR, errno, fd, n, and write().
Referenced by close_conn_and_exit(), and full_write().
say()
static void say (const char * s, ...) static
Definition at line 94 of file ssl_helper.c.
 {
     char buf[256];
     va_list p;
     int sz;
     va_start(p, s);
     sz = vsnprintf(buf, sizeof(buf), s, p);
     full_write(STDERR_FILENO, buf, sz >= 0 && sz < sizeof(buf) ? sz : strlen(buf));
     va_end(p);
 }
References buf, full_write(), p, s, STDERR_FILENO, strlen(), va_end, va_start, and vsnprintf().
wait_for_input()
static int wait_for_input (void) static
Definition at line 134 of file ssl_helper.c.
 {
     if (STDIN.fd == NETWORK.fd) /* means both are -1 */
         exit(0);
     dbg("polling\n");
     STDIN.revents = NETWORK.revents = 0;
     return poll(pfd, 2, -1);
 }
References dbg, exit(), NETWORK, pfd, poll(), and STDIN.
Referenced by do_io_until_eof_and_exit().
Variable Documentation
pfd
struct pollfd pfd[2] static
Initial value:
= {
    { -1, POLLIN|POLLERR|POLLHUP, 0 },
    { -1, POLLIN|POLLERR|POLLHUP, 0 },
}
Definition at line 106 of file ssl_helper.c.
Referenced by do_io_until_eof_and_exit(), and wait_for_input().