Fennix: Userspace/apps/user/games/doomgeneric/doomgeneric/m_argv.c File Reference
m_argv.c File Reference
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "doomtype.h"
#include "i_system.h"
#include "m_misc.h"
#include "m_argv.h"
Macros
#define MAXARGVS 100
Functions
int M_CheckParmWithArgs (char *check, int num_args)
boolean M_ParmExists (char *check)
int M_CheckParm (char *check)
static void LoadResponseFile (int argv_index)
void M_FindResponseFile (void)
char * M_GetExecutableName (void)
Variables
int myargc
char ** myargv
Macro Definition Documentation
MAXARGVS
#define MAXARGVS 100
Definition at line 73 of file m_argv.c.
Function Documentation
LoadResponseFile()
static void LoadResponseFile (int argv_index) static
Definition at line 75 of file m_argv.c.
 {
 #if ORIGCODE
     FILE *handle;
     int size;
     char *infile;
     char *file;
     char *response_filename;
     char **newargv;
     int newargc;
     int i, k;
     response_filename = myargv[argv_index] + 1;
     // Read the response file into memory
     handle = fopen(response_filename, "rb");
     if (handle == NULL)
     {
         printf ("\nNo such response file!");
 #if ORIGCODE
         exit(1);
 #endif
     }
     printf("Found response file %s!\n", response_filename);
     size = M_FileLength(handle);
     // Read in the entire file
     // Allocate one byte extra - this is in case there is an argument
     // at the end of the response file, in which case a '\0' will be
     // needed.
     file = malloc(size + 1);
     i = 0;
     while (i < size)
     {
         k = fread(file + i, 1, size - i, handle);
         if (k < 0)
         {
             I_Error("Failed to read full contents of '%s'", response_filename);
         }
         i += k;
     }
     fclose(handle);
     // Create new arguments list array
     newargv = malloc(sizeof(char *) * MAXARGVS);
     newargc = 0;
     memset(newargv, 0, sizeof(char *) * MAXARGVS);
     // Copy all the arguments in the list up to the response file
     for (i=0; i<argv_index; ++i)
     {
         newargv[i] = myargv[i];
         ++newargc;
     }
     infile = file;
     k = 0;
     while(k < size)
     {
         // Skip past space characters to the next argument
         while(k < size && isspace((int)infile[k]))
         {
             ++k;
         }
         if (k >= size)
         {
             break;
         }
         // If the next argument is enclosed in quote marks, treat
         // the contents as a single argument.  This allows long filenames
         // to be specified.
         if (infile[k] == '\"')
         {
             // Skip the first character(")
             ++k;
             newargv[newargc++] = &infile[k];
             // Read all characters between quotes
             while (k < size && infile[k] != '\"' && infile[k] != '\n')
             {
                 ++k;
             }
             if (k >= size || infile[k] == '\n')
             {
                 I_Error("Quotes unclosed in response file '%s'",
                         response_filename);
             }
             // Cut off the string at the closing quote
             infile[k] = '\0';
             ++k;
         }
         else
         {
             // Read in the next argument until a space is reached
             newargv[newargc++] = &infile[k];
             while(k < size && !isspace((int)infile[k]))
             {
                 ++k;
             }
             // Cut off the end of the argument at the first space
             infile[k] = '\0';
             ++k;
         }
     }
     // Add arguments following the response file argument
     for (i=argv_index + 1; i<myargc; ++i)
     {
         newargv[newargc] = myargv[i];
         ++newargc;
     }
     myargv = newargv;
     myargc = newargc;
 #if 0
     // Disabled - Vanilla Doom does not do this.
     // Display arguments
     printf("%d command-line args:\n", myargc);
     for (k=1; k<myargc; k++)
     {
         printf("'%s'\n", myargv[k]);
     }
 #endif
 #endif
 }
References exit(), fclose(), fopen(), fread(), i, I_Error(), isspace(), k, M_FileLength(), malloc(), MAXARGVS, memset, myargc, myargv, NULL, printf, and size.
Referenced by M_FindResponseFile().
M_CheckParm()
int M_CheckParm (char * check)
Definition at line 68 of file m_argv.c.
 {
     return M_CheckParmWithArgs(check, 0);
 }
References M_CheckParmWithArgs().
Referenced by D_CheckNetGame(), D_ConnectNetGame(), D_DoomMain(), D_Endoom(), D_InitNetGame(), D_StartNetGame(), G_BeginRecording(), G_DoPlayDemo(), G_TimeDemo(), I_InitSound(), I_Stretch5x(), InitConnectData(), M_ParmExists(), PadRejectArray(), SaveGameSettings(), and W_OpenFile().
M_CheckParmWithArgs()
int M_CheckParmWithArgs (char * check, int num_args)
Definition at line 43 of file m_argv.c.
 {
     int i;
     for (i = 1; i < myargc - num_args; i++)
     {
     if (!strcasecmp(check, myargv[i]))
         return i;
     }
     return 0;
 }
References i, myargc, myargv, and strcasecmp().
Referenced by D_DoomMain(), D_FindIWAD(), D_IdentifyVersion(), D_InitNetGame(), D_StartNetGame(), DonutOverrun(), G_RecordDemo(), I_GetMemoryValue(), I_InitGraphics(), I_ZoneBase(), InitGameVersion(), M_CheckParm(), M_LoadDefaults(), SpechitOverrun(), StatDump(), and W_ParseCommandLine().
M_FindResponseFile()
void M_FindResponseFile (void)
Definition at line 235 of file m_argv.c.
 {
     int             i;
     for (i = 1; i < myargc; i++)
     {
         if (myargv[i][0] == '@')
         {
             LoadResponseFile(i);
         }
     }
 }
References i, LoadResponseFile(), myargc, and myargv.
Referenced by doomgeneric_Create().
M_GetExecutableName()
char* M_GetExecutableName (void)
Definition at line 250 of file m_argv.c.
 {
     char *sep;
     sep = strrchr(myargv[0], DIR_SEPARATOR);
     if (sep == NULL)
     {
         return myargv[0];
     }
     else
     {
         return sep + 1;
     }
 }
References DIR_SEPARATOR, myargv, NULL, and strrchr().
M_ParmExists()
boolean M_ParmExists (char * check)
Definition at line 63 of file m_argv.c.
 {
     return M_CheckParm(check) != 0;
 }
References M_CheckParm().
Referenced by D_DoomMain(), I_Error(), and StatCopy().
Variable Documentation
myargc
int myargc
Definition at line 29 of file m_argv.c.
Referenced by D_DoomMain(), doomgeneric_Create(), I_GetMemoryValue(), LoadResponseFile(), M_CheckParmWithArgs(), M_FindResponseFile(), and W_ParseCommandLine().
myargv
char** myargv
Definition at line 30 of file m_argv.c.
Referenced by D_DoomMain(), D_FindIWAD(), D_IdentifyVersion(), D_InitNetGame(), D_StartNetGame(), DonutOverrun(), doomgeneric_Create(), G_RecordDemo(), I_GetMemoryValue(), I_InitGraphics(), I_ZoneBase(), InitGameVersion(), LoadResponseFile(), M_CheckParmWithArgs(), M_FindResponseFile(), M_GetExecutableName(), M_LoadDefaults(), SpechitOverrun(), StatDump(), and W_ParseCommandLine().