Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/mus2mid.h File Reference
mus2mid.h File Reference
#include "doomtype.h"
#include "memio.h"
Functions
boolean mus2mid (MEMFILE *musinput, MEMFILE *midioutput)
Function Documentation
mus2mid()
boolean mus2mid (MEMFILE * musinput, MEMFILE * midioutput)
Definition at line 444 of file mus2mid.c.
 {
     // Header for the MUS file
     musheader musfileheader;
     // Descriptor for the current MUS event
     byte eventdescriptor;
     int channel; // Channel number
     musevent event;
     // Bunch of vars read from MUS lump
     byte key;
     byte controllernumber;
     byte controllervalue;
     // Buffer used for MIDI track size record
     byte tracksizebuffer[4];
     // Flag for when the score end marker is hit.
     int hitscoreend = 0;
     // Temp working byte
     byte working;
     // Used in building up time delays
     unsigned int timedelay;
     // Initialise channel map to mark all channels as unused.
     for (channel=0; channel<NUM_CHANNELS; ++channel)
     {
         channel_map[channel] = -1;
     }
     // Grab the header
     if (!ReadMusHeader(musinput, &musfileheader))
     {
         return true;
     }
 // [crispy] enable MUS format header check
 #define CHECK_MUS_HEADER
 #ifdef CHECK_MUS_HEADER
     // Check MUS header
     if (musfileheader.id[0] != 'M'
      || musfileheader.id[1] != 'U'
      || musfileheader.id[2] != 'S'
      || musfileheader.id[3] != 0x1A)
     {
         return true;
     }
 #endif
     // Seek to where the data is held
     if (mem_fseek(musinput, (long)musfileheader.scorestart,
                   MEM_SEEK_SET) != 0)
     {
         return true;
     }
     // So, we can assume the MUS file is faintly legit. Let's start
     // writing MIDI data...
     mem_fwrite(midiheader, 1, sizeof(midiheader), midioutput);
     tracksize = 0;
     // Now, process the MUS file:
     while (!hitscoreend)
     {
         // Handle a block of events:
         while (!hitscoreend)
         {
             // Fetch channel number and event code:
             if (mem_fread(&eventdescriptor, 1, 1, musinput) != 1)
             {
                 return true;
             }
             channel = GetMIDIChannel(eventdescriptor & 0x0F, midioutput);
             event = eventdescriptor & 0x70;
             switch (event)
             {
                 case mus_releasekey:
                     if (mem_fread(&key, 1, 1, musinput) != 1)
                     {
                         return true;
                     }
                     if (WriteReleaseKey(channel, key, midioutput))
                     {
                         return true;
                     }
                     break;
                 case mus_presskey:
                     if (mem_fread(&key, 1, 1, musinput) != 1)
                     {
                         return true;
                     }
                     if (key & 0x80)
                     {
                         if (mem_fread(&channelvelocities[channel], 1, 1, musinput) != 1)
{
                             return true;
                         }
                         channelvelocities[channel] &= 0x7F;
                     }
                     if (WritePressKey(channel, key,
                                       channelvelocities[channel], midioutput))
                     {
                         return true;
                     }
                     break;
                 case mus_pitchwheel:
                     if (mem_fread(&key, 1, 1, musinput) != 1)
                     {
                         break;
                     }
                     if (WritePitchWheel(channel, (short)(key * 64), midioutput))
                     {
                         return true;
                     }
                     break;
                 case mus_systemevent:
                     if (mem_fread(&controllernumber, 1, 1, musinput) != 1)
                     {
                         return true;
                     }
                     if (controllernumber < 10 || controllernumber > 14)
                     {
                         return true;
                     }
                     if (WriteChangeController_Valueless(channel,
                                                         controller_map[controllernumber],
                                                         midioutput))
                     {
                         return true;
                     }
                     break;
                 case mus_changecontroller:
                     if (mem_fread(&controllernumber, 1, 1, musinput) != 1)
                     {
                         return true;
                     }
                     if (mem_fread(&controllervalue, 1, 1, musinput) != 1)
                     {
                         return true;
                     }
                     if (controllernumber == 0)
                     {
                         if (WriteChangePatch(channel, controllervalue,
                                              midioutput))
{
                             return true;
                         }
                     }
                     else
                     {
                         if (controllernumber < 1 || controllernumber > 9)
{
                             return true;
                         }
                         if (WriteChangeController_Valued(channel,
                                                          controller_map[controllernumber],
                                                          controllervalue,
                                                          midioutput))
{
                             return true;
                         }
                     }
                     break;
                 case mus_scoreend:
                     hitscoreend = 1;
                     break;
                 default:
                     return true;
                     break;
             }
             if (eventdescriptor & 0x80)
             {
                 break;
             }
         }
         // Now we need to read the time code:
         if (!hitscoreend)
         {
             timedelay = 0;
             for (;;)
             {
                 if (mem_fread(&working, 1, 1, musinput) != 1)
                 {
                     return true;
                 }
                 timedelay = timedelay * 128 + (working & 0x7F);
                 if ((working & 0x80) == 0)
                 {
                     break;
                 }
             }
             queuedtime += timedelay;
         }
     }
     // End of track
     if (WriteEndTrack(midioutput))
     {
         return true;
     }
     // Write the track size into the stream
     if (mem_fseek(midioutput, 18, MEM_SEEK_SET))
     {
         return true;
     }
     tracksizebuffer[0] = (tracksize >> 24) & 0xff;
     tracksizebuffer[1] = (tracksize >> 16) & 0xff;
     tracksizebuffer[2] = (tracksize >> 8) & 0xff;
     tracksizebuffer[3] = tracksize & 0xff;
     if (mem_fwrite(tracksizebuffer, 1, 4, midioutput) != 4)
     {
         return true;
     }
     return false;
 }
References channel_map, channelvelocities, controller_map, GetMIDIChannel(), musheader::id, mem_fread(), mem_fseek(), mem_fwrite(), MEM_SEEK_SET, midiheader, mus_changecontroller, mus_pitchwheel, mus_presskey, mus_releasekey, mus_scoreend, mus_systemevent, NUM_CHANNELS, queuedtime, ReadMusHeader(), musheader::scorestart, tracksize, WriteChangeController_Valued(), WriteChangeController_Valueless(), WriteChangePatch(), WriteEndTrack(), WritePitchWheel(), WritePressKey(), and WriteReleaseKey().