Fennix: Userspace/apps/base/busybox/miscutils/tree.c File Reference
tree.c File Reference
#include "libbb.h"
#include "common_bufsiz.h"
#include "unicode.h"
Macros
#define prefix_buf bb_common_bufsiz1
Functions
static void tree_print (unsigned count[2], const char *directory_name, char *prefix_pos)
int tree_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
prefix_buf
#define prefix_buf bb_common_bufsiz1
Definition at line 24 of file tree.c.
Function Documentation
tree_main()
int tree_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 113 of file tree.c.
 {
     unsigned count[2] = { 0, 0 };
     setup_common_bufsiz();
     init_unicode();
     if (!argv[1])
         *argv-- = (char*)".";
     // list directories given as command line arguments
     while (*(++argv))
         tree_print(count, *argv, prefix_buf);
     // print statistic
     printf("\n%u directories, %u files\n", count[0], count[1]);
     return EXIT_SUCCESS;
 }
References argv, count, EXIT_SUCCESS, init_unicode, prefix_buf, printf, and tree_print().
tree_print()
static void tree_print (unsigned count[2], const char * directory_name, char * prefix_pos) static
Definition at line 26 of file tree.c.
 {
     struct dirent **entries;
     int index, size;
     const char *bar = "|   ";
     const char *mid = "|-- ";
     const char *end = "`-- ";
 #if ENABLE_UNICODE_SUPPORT
     if (unicode_status == UNICODE_ON) {
         bar = "│   ";
         mid = "├── ";
         end = "└── ";
     }
 #endif
     // read directory entries
     size = scandir(directory_name, &entries, NULL, alphasort);
     if (size < 0) {
         fputs_stdout(directory_name);
         puts(" [error opening dir]");
         return;
     }
     // print directory name
     puts(directory_name);
     // switch to sub directory
     xchdir(directory_name);
     // print all directory entries
     for (index = 0; index < size;) {
         struct dirent *dirent = entries[index++];
         // filter hidden files and directories
         if (dirent->d_name[0] != '.') {
             int status;
             struct stat statBuf;
 //TODO: when -l is implemented, use stat, not lstat, if -l
             status = lstat(dirent->d_name, &statBuf);
             if (index == size) {
                 strcpy(prefix_pos, end);
             } else {
                 strcpy(prefix_pos, mid);
             }
             fputs_stdout(prefix_buf);
             if (status == 0 && S_ISLNK(statBuf.st_mode)) {
                 // handle symlink
                 char* symlink_path = xmalloc_readlink(dirent->d_name);
                 printf("%s -> %s\n", dirent->d_name, symlink_path);
                 free(symlink_path);
                 count[1]++;
             } else if (status == 0 && S_ISDIR(statBuf.st_mode)
              && (prefix_pos - prefix_buf) < (COMMON_BUFSIZE - 16)
             ) {
                 // handle directory
                 char* pos;
                 if (index == size) {
                     pos = stpcpy(prefix_pos, "    ");
                 } else {
                     pos = stpcpy(prefix_pos, bar);
                 }
                 tree_print(count, dirent->d_name, pos);
                 count[0]++;
             } else {
                 // handle file
                 puts(dirent->d_name);
                 count[1]++;
             }
         }
         // release directory entry
         free(dirent);
     }
     // release directory array
     free(entries);
     // switch to parent directory
     xchdir("..");
 }
References alphasort(), bar, count, dirent::d_name, end, fputs_stdout(), free, index(), lstat, NULL, pos, prefix_buf, printf, puts(), S_ISDIR, S_ISLNK, scandir(), size, stat::st_mode, status, stpcpy(), strcpy, UNICODE_ON, unicode_status, xchdir(), and xmalloc_readlink().
Referenced by tree_main().