Fennix: Userspace/musl/src/thread/vmlock.c File Reference
vmlock.c File Reference
#include "pthread_impl.h"
#include "fork_impl.h"
Functions
void __vm_wait ()
void __vm_lock ()
void __vm_unlock ()
Variables
static volatile int vmlock [2]
volatile int *const __vmlock_lockptr = vmlock
Function Documentation
__vm_lock()
void __vm_lock (void)
Definition at line 14 of file vmlock.c.
 {
     a_inc(vmlock);
 }
References a_inc, and vmlock.
Referenced by __pthread_exit(), __pthread_mutex_unlock(), and pshared_barrier_wait().
__vm_unlock()
void __vm_unlock (void)
Definition at line 19 of file vmlock.c.
 {
     if (a_fetch_add(vmlock, -1)==1 && vmlock[1])
         __wake(vmlock, -1, 1);
 }
References __wake(), a_fetch_add, and vmlock.
Referenced by __pthread_exit(), __pthread_mutex_unlock(), and pshared_barrier_wait().
__vm_wait()
void __vm_wait (void)
Definition at line 7 of file vmlock.c.
 {
     int tmp;
     while ((tmp=vmlock[0]))
         __wait(vmlock, vmlock+1, tmp, 1);
 }
References __wait(), and vmlock.
Referenced by __mmap(), __mremap(), __munmap(), __pthread_exit(), pthread_barrier_destroy(), and pthread_mutex_destroy().
Variable Documentation
__vmlock_lockptr
volatile int* const __vmlock_lockptr = vmlock
Definition at line 5 of file vmlock.c.
Referenced by fork().
vmlock
volatile int vmlock[2] static
Definition at line 4 of file vmlock.c.
Referenced by __vm_lock(), __vm_unlock(), and __vm_wait().