Fennix Userspace: Userspace/mlibc/options/ansi/generic/locale-stubs.cpp File Reference
locale-stubs.cpp File Reference
#include <limits.h>
#include <locale.h>
#include <string.h>
#include <bits/ensure.h>
#include <mlibc/debug.hpp>
#include <frg/optional.hpp>
Data Structures
struct mlibc::locale_description
Namespaces
anonymous_namespace{locale-stubs.cpp}
mlibc
Functions
const locale_description * mlibc::query_locale_description (const char *name)
void __mlibc_initLocale ()
char * setlocale (int category, const char *name)
struct lconv * localeconv (void)
Variables
constexpr lconv anonymous_namespace{locale-stubs.cpp}::c_lconv
constinit const locale_description mlibc::c_locale
constinit const locale_description mlibc::posix_locale
const locale_description * mlibc::collate_facet
const locale_description * mlibc::ctype_facet
const locale_description * mlibc::monetary_facet
const locale_description * mlibc::numeric_facet
const locale_description * mlibc::time_facet
const locale_description * mlibc::messages_facet
lconv anonymous_namespace{locale-stubs.cpp}::effective_lc
Data Structure Documentation
mlibc::locale_description
struct mlibc::locale_description
Definition at line 42 of file locale-stubs.cpp.
Data Fields
lconv lc
const char * name
Function Documentation
__mlibc_initLocale()
void __mlibc_initLocale ()
Definition at line 74 of file locale-stubs.cpp.
{
     mlibc::collate_facet = &mlibc::c_locale;
     mlibc::ctype_facet = &mlibc::c_locale;
     mlibc::monetary_facet = &mlibc::c_locale;
     mlibc::numeric_facet = &mlibc::c_locale;
     mlibc::time_facet = &mlibc::c_locale;
     mlibc::messages_facet = &mlibc::c_locale;
 }
References mlibc::c_locale, mlibc::collate_facet, mlibc::ctype_facet, mlibc::messages_facet, mlibc::monetary_facet, mlibc::numeric_facet, and mlibc::time_facet.
Referenced by LibraryGuard::LibraryGuard().
localeconv()
struct lconv* localeconv (void)
Definition at line 163 of file locale-stubs.cpp.
{
     // Numeric locale.
     const auto &numeric_lc = mlibc::numeric_facet->lc;
     effective_lc.decimal_point = numeric_lc.decimal_point;
     effective_lc.thousands_sep = numeric_lc.thousands_sep;
     effective_lc.grouping = numeric_lc.grouping;
     // Monetary locale.
     const auto &monetary_lc = mlibc::monetary_facet->lc;
     effective_lc.mon_decimal_point = monetary_lc.mon_decimal_point;
     effective_lc.mon_thousands_sep = monetary_lc.mon_thousands_sep;
     effective_lc.mon_grouping = monetary_lc.mon_grouping;
     effective_lc.positive_sign = monetary_lc.positive_sign;
     effective_lc.negative_sign = monetary_lc.negative_sign;
     effective_lc.currency_symbol = monetary_lc.currency_symbol;
     effective_lc.frac_digits = monetary_lc.frac_digits;
     effective_lc.p_cs_precedes = monetary_lc.p_cs_precedes;
     effective_lc.n_cs_precedes = monetary_lc.n_cs_precedes;
     effective_lc.p_sep_by_space = monetary_lc.p_sep_by_space;
     effective_lc.n_sep_by_space = monetary_lc.n_sep_by_space;
     effective_lc.p_sign_posn = monetary_lc.p_sign_posn;
     effective_lc.n_sign_posn = monetary_lc.n_sign_posn;
     effective_lc.int_curr_symbol = monetary_lc.int_curr_symbol;
     effective_lc.int_frac_digits = monetary_lc.int_frac_digits;
     effective_lc.int_p_cs_precedes = monetary_lc.int_p_cs_precedes;
     effective_lc.int_n_cs_precedes = monetary_lc.int_n_cs_precedes;
     effective_lc.int_p_sep_by_space = monetary_lc.int_p_sep_by_space;
     effective_lc.int_n_sep_by_space = monetary_lc.int_n_sep_by_space;
     effective_lc.int_p_sign_posn = monetary_lc.int_p_sign_posn;
     effective_lc.int_n_sign_posn = monetary_lc.int_n_sign_posn;
     return &effective_lc;
 }
References lconv::currency_symbol, lconv::decimal_point, anonymous_namespace{locale-stubs.cpp}::effective_lc, lconv::frac_digits, lconv::grouping, lconv::int_curr_symbol, lconv::int_frac_digits, lconv::int_n_cs_precedes, lconv::int_n_sep_by_space, lconv::int_n_sign_posn, lconv::int_p_cs_precedes, lconv::int_p_sep_by_space, lconv::int_p_sign_posn, mlibc::locale_description::lc, lconv::mon_decimal_point, lconv::mon_grouping, lconv::mon_thousands_sep, mlibc::monetary_facet, lconv::n_cs_precedes, lconv::n_sep_by_space, lconv::n_sign_posn, lconv::negative_sign, mlibc::numeric_facet, lconv::p_cs_precedes, lconv::p_sep_by_space, lconv::p_sign_posn, lconv::positive_sign, and lconv::thousands_sep.
setlocale()
char* setlocale (int category, const char * name)
Definition at line 83 of file locale-stubs.cpp.
{
     if(category == LC_ALL) {
         // ´TODO: Implement correct return value when categories differ.
         auto current_desc = mlibc::collate_facet;
         __ensure(current_desc == mlibc::ctype_facet);
         __ensure(current_desc == mlibc::monetary_facet);
         __ensure(current_desc == mlibc::numeric_facet);
         __ensure(current_desc == mlibc::time_facet);
         __ensure(current_desc == mlibc::messages_facet);
         if(name) {
             // Our default C locale is the C locale.
             if(!strlen(name))
                 name = "C";
             auto new_desc = mlibc::query_locale_description(name);
             if(!new_desc) {
                 mlibc::infoLogger() << "mlibc: Locale " << name
                         << " is not supported" << frg::endlog;
                 return nullptr;
             }
             mlibc::collate_facet = new_desc;
             mlibc::ctype_facet = new_desc;
             mlibc::monetary_facet = new_desc;
             mlibc::numeric_facet = new_desc;
             mlibc::time_facet = new_desc;
             mlibc::messages_facet = new_desc;
         }
         return const_cast<char *>(current_desc->name);
     }else{
         const mlibc::locale_description **facet_ptr;
         switch(category) {
         case LC_COLLATE:
             facet_ptr = &mlibc::collate_facet;
             break;
         case LC_CTYPE:
             facet_ptr = &mlibc::ctype_facet;
             break;
         case LC_MONETARY:
             facet_ptr = &mlibc::monetary_facet;
             break;
         case LC_NUMERIC:
             facet_ptr = &mlibc::numeric_facet;
             break;
         case LC_TIME:
             facet_ptr = &mlibc::time_facet;
             break;
         case LC_MESSAGES:
             facet_ptr = &mlibc::messages_facet;
             break;
         default:
             mlibc::infoLogger() << "mlibc: Unexpected value " << category
                     << " for category in setlocale()" << frg::endlog;
             return nullptr;
         }
         auto current_desc = *facet_ptr;
         if(name) {
             // Our default C locale is the C locale.
             if(!strlen(name))
                 name = "C";
             auto new_desc = mlibc::query_locale_description(name);
             if(!new_desc) {
                 mlibc::infoLogger() << "mlibc: Locale " << name
                         << " is not supported" << frg::endlog;
                 return nullptr;
             }
             *facet_ptr = new_desc;
         }
         return const_cast<char *>(current_desc->name);
     }
 }
References __ensure, mlibc::collate_facet, mlibc::ctype_facet, mlibc::infoLogger, LC_ALL, LC_COLLATE, LC_CTYPE, LC_MESSAGES, LC_MONETARY, LC_NUMERIC, LC_TIME, mlibc::messages_facet, mlibc::monetary_facet, name, mlibc::numeric_facet, mlibc::query_locale_description(), strlen(), and mlibc::time_facet.
Referenced by main().