Fennix Userspace: Userspace/musl/src/math/nearbyintf.c File Reference
nearbyintf.c File Reference
#include <fenv.h>
#include <math.h>
Functions
float nearbyintf (float x)
Function Documentation
nearbyintf()
float nearbyintf (float x)
Definition at line 4 of file nearbyintf.c.
 {
 #ifdef FE_INEXACT
     #pragma STDC FENV_ACCESS ON
     int e;
     e = fetestexcept(FE_INEXACT);
 #endif
     x = rintf(x);
 #ifdef FE_INEXACT
     if (!e)
         feclearexcept(FE_INEXACT);
 #endif
     return x;
 }
References __asm__(), FE_INEXACT, feclearexcept(), fetestexcept(), rintf(), and x.