Fennix: Userspace/musl/src/string/strncasecmp.c File Reference
strncasecmp.c File Reference
#include <strings.h>
#include <ctype.h>
Functions
int strncasecmp (const char *_l, const char *_r, size_t n)
int __strncasecmp_l (const char *l, const char *r, size_t n, locale_t loc)
weak_alias (__strncasecmp_l, strncasecmp_l)
Function Documentation
__strncasecmp_l()
int __strncasecmp_l (const char * l, const char * r, size_t n, locale_t loc)
Definition at line 12 of file strncasecmp.c.
 {
     return strncasecmp(l, r, n);
 }
References n, and strncasecmp().
strncasecmp()
int strncasecmp (const char * _l, const char * _r, size_t n)
Definition at line 4 of file strncasecmp.c.
 {
     const unsigned char *l=(void *)_l, *r=(void *)_r;
     if (!n--) return 0;
     for (; *l && *r && n && (*l == *r || tolower(*l) == tolower(*r)); l++, r++, n--);
     return tolower(*l) - tolower(*r);
 }
References count, n, and tolower.
Referenced by __strncasecmp_l(), D_IdentifyVersion(), M_StrCaseStr(), R_CheckTextureNumForName(), R_InitSpriteDefs(), strcasestr(), strptime(), and W_CheckNumForName().
weak_alias()
weak_alias (__strncasecmp_l , strncasecmp_l)