Fennix: Lynx/FennixLoader/include/memory.hpp File Reference
memory.hpp File Reference
#include <bitmap.hpp>
#include <binfo.h>
#include <debug.h>
#include <types.h>
Data Structures
union Memory32::PageTableEntry
struct Memory32::PageTableEntryPtr
union Memory32::PageDirectoryEntry
struct Memory32::PageTable
class Memory32::Physical
class Memory32::Virtual
class Memory32::Virtual::PageMapIndexer
union Memory64::PageTableEntry
struct Memory64::PageTableEntryPtr
union Memory64::PageDirectoryEntry
struct Memory64::PageDirectoryEntryPtr
union Memory64::PageDirectoryPointerTableEntry
struct Memory64::PageDirectoryPointerTableEntryPtr
union Memory64::PageMapLevel4
struct Memory64::PageTable
class Memory64::Physical
class Memory64::Virtual
class Memory64::Virtual::PageMapIndexer
struct Memory32::PageTableEntry.__unnamed839__
struct Memory32::PageDirectoryEntry.__unnamed841__
struct Memory64::PageTableEntry.__unnamed843__
struct Memory64::PageDirectoryEntry.__unnamed845__
struct Memory64::PageDirectoryEntry.TwoMB
struct Memory64::PageDirectoryPointerTableEntry.__unnamed850__
struct Memory64::PageDirectoryPointerTableEntry.OneGB
struct Memory64::PageMapLevel4.__unnamed858__
Namespaces
Memory32
Memory64
Macros
#define TO_KB(d) ((d) / 1024)
#define TO_MB(d) ((d) / 1024 / 1024)
#define TO_GB(d) ((d) / 1024 / 1024 / 1024)
#define PAGE_SIZE 0x1000
#define PAGE_SIZE_4K PAGE_SIZE
#define PAGE_SIZE_2M 0x200000
#define PAGE_SIZE_4M 0x400000
#define PAGE_SIZE_1G 0x40000000
#define TO_PAGES(d) (((d) + PAGE_SIZE - 1) / PAGE_SIZE)
#define FROM_PAGES(d) ((d)*PAGE_SIZE)
Enumerations
enum PTFlag {
P = 1 << 0 , RW = 1 << 1 , US = 1 << 2 , PWT = 1 << 3 ,
PCD = 1 << 4 , A = 1 << 5 , D = 1 << 6 , PS = 1 << 7 ,
G = 1 << 8 , AVL0 = 1 << 9 , AVL1 = 1 << 10 , AVL2 = 1 << 11 ,
PAT = 1 << 12 , AVL3 = (uint64_t)1 << 52 , AVL4 = (uint64_t)1 << 53 , AVL5 = (uint64_t)1 << 54 ,
AVL6 = (uint64_t)1 << 55 , AVL7 = (uint64_t)1 << 56 , AVL8 = (uint64_t)1 << 57 , AVL9 = (uint64_t)1 << 58 ,
PK0 = (uint64_t)1 << 59 , PK1 = (uint64_t)1 << 60 , PK2 = (uint64_t)1 << 61 , PK3 = (uint64_t)1 << 62 ,
XD = (uint64_t)1 << 63
}
Functions
struct Memory32::PageTable Memory32::__aligned (0x1000)
struct Memory64::PageTable Memory64::__aligned (0x1000)
void Update ()
Update CR3 with this PageTable.
void * memcpy (void *dest, const void *src, size_t n)
void * memset (void *s, int c, size_t n)
void InitializeMemoryManagement (BootInfo *Info, bool is32)
Variables
uintptr_t _kernel_start
uintptr_t _kernel_end
PageDirectoryEntry Entries [1024]
class Memory32::Physical Memory32::__aligned
class Memory64::Physical Memory64::__aligned
Memory32::Physical KernelAllocator32
Memory32::PageTable * KernelPageTable32
Memory64::Physical KernelAllocator64
Memory64::PageTable * KernelPageTable64
Data Structure Documentation
Memory32::PageTableEntryPtr
struct Memory32::PageTableEntryPtr
Definition at line 138 of file memory.hpp.
Data Fields
PageTableEntry Entries[1024]
Memory32::PageTable
struct Memory32::PageTable
Definition at line 173 of file memory.hpp.
Data Fields
PageDirectoryEntry Entries[1024]
Memory64::PageTableEntryPtr
struct Memory64::PageTableEntryPtr
Definition at line 276 of file memory.hpp.
Data Fields
PageTableEntry Entries[511]
Memory64::PageDirectoryEntryPtr
struct Memory64::PageDirectoryEntryPtr
Definition at line 336 of file memory.hpp.
Data Fields
PageDirectoryEntry Entries[511]
Memory64::PageDirectoryPointerTableEntryPtr
struct Memory64::PageDirectoryPointerTableEntryPtr
Definition at line 396 of file memory.hpp.
Data Fields
PageDirectoryPointerTableEntry Entries[511]
Memory32::PageTableEntry.__unnamed839__
struct Memory32::PageTableEntry.__unnamed839__
Definition at line 109 of file memory.hpp.
Data Fields
uint32_t Accessed: 1
uint32_t Address: 20
uint32_t Available0: 3
uint32_t CacheDisable: 1
uint32_t Dirty: 1
uint32_t Global: 1
uint32_t PageAttributeTable: 1
uint32_t Present: 1
uint32_t ReadWrite: 1
uint32_t UserSupervisor: 1
uint32_t WriteThrough: 1
Memory32::PageDirectoryEntry.__unnamed841__
struct Memory32::PageDirectoryEntry.__unnamed841__
Definition at line 145 of file memory.hpp.
Data Fields
uint32_t Accessed: 1
uint32_t Address: 20
uint32_t Available0: 1
uint32_t Available1: 4
uint32_t CacheDisable: 1
uint32_t PageSize: 1
uint32_t Present: 1
uint32_t ReadWrite: 1
uint32_t UserSupervisor: 1
uint32_t WriteThrough: 1
Memory64::PageTableEntry.__unnamed843__
struct Memory64::PageTableEntry.__unnamed843__
Definition at line 242 of file memory.hpp.
Data Fields
uint64_t Accessed: 1
uint64_t Address: 40
uint64_t Available0: 3
uint64_t Available1: 7
uint64_t CacheDisable: 1
uint64_t Dirty: 1
uint64_t ExecuteDisable: 1
uint64_t Global: 1
uint64_t PageAttributeTable: 1
uint64_t Present: 1
uint64_t ProtectionKey: 4
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
Memory64::PageDirectoryEntry.__unnamed845__
struct Memory64::PageDirectoryEntry.__unnamed845__
Definition at line 283 of file memory.hpp.
Data Fields
uint64_t Accessed: 1
uint64_t Address: 40
uint64_t Available0: 1
uint64_t Available1: 4
uint64_t Available2: 11
uint64_t CacheDisable: 1
uint64_t ExecuteDisable: 1
uint64_t PageSize: 1
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
Memory64::PageDirectoryEntry.TwoMB
struct Memory64::PageDirectoryEntry.TwoMB
Definition at line 299 of file memory.hpp.
Data Fields
uint64_t Accessed: 1
uint64_t Address: 31
uint64_t Available0: 3
uint64_t Available1: 7
uint64_t CacheDisable: 1
uint64_t Dirty: 1
uint64_t ExecuteDisable: 1
uint64_t Global: 1
uint64_t PageAttributeTable: 1
uint64_t PageSize: 1
uint64_t Present: 1
uint64_t ProtectionKey: 4
uint64_t ReadWrite: 1
uint64_t Reserved0: 8
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
Memory64::PageDirectoryPointerTableEntry.__unnamed850__
struct Memory64::PageDirectoryPointerTableEntry.__unnamed850__
Definition at line 343 of file memory.hpp.
Data Fields
uint64_t Accessed: 1
uint64_t Address: 40
uint64_t Available0: 1
uint64_t Available1: 4
uint64_t Available2: 11
uint64_t CacheDisable: 1
uint64_t ExecuteDisable: 1
uint64_t PageSize: 1
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
Memory64::PageDirectoryPointerTableEntry.OneGB
struct Memory64::PageDirectoryPointerTableEntry.OneGB
Definition at line 359 of file memory.hpp.
Data Fields
uint64_t Accessed: 1
uint64_t Address: 22
uint64_t Available0: 3
uint64_t Available1: 7
uint64_t CacheDisable: 1
uint64_t Dirty: 1
uint64_t ExecuteDisable: 1
uint64_t Global: 1
uint64_t PageAttributeTable: 1
uint64_t PageSize: 1
uint64_t Present: 1
uint64_t ProtectionKey: 4
uint64_t ReadWrite: 1
uint64_t Reserved0: 17
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
Memory64::PageMapLevel4.__unnamed858__
struct Memory64::PageMapLevel4.__unnamed858__
Definition at line 403 of file memory.hpp.
Data Fields
uint64_t Accessed: 1
uint64_t Address: 40
uint64_t Available0: 1
uint64_t Available1: 4
uint64_t Available2: 11
uint64_t CacheDisable: 1
uint64_t ExecuteDisable: 1
uint64_t Present: 1
uint64_t ReadWrite: 1
uint64_t Reserved0: 1
uint64_t UserSupervisor: 1
uint64_t WriteThrough: 1
Macro Definition Documentation
FROM_PAGES
#define FROM_PAGES (d) ((d)*PAGE_SIZE)
Definition at line 25 of file memory.hpp.
PAGE_SIZE
#define PAGE_SIZE 0x1000
Definition at line 16 of file memory.hpp.
PAGE_SIZE_1G
#define PAGE_SIZE_1G 0x40000000
Definition at line 20 of file memory.hpp.
PAGE_SIZE_2M
#define PAGE_SIZE_2M 0x200000
Definition at line 18 of file memory.hpp.
PAGE_SIZE_4K
#define PAGE_SIZE_4K PAGE_SIZE
Definition at line 17 of file memory.hpp.
PAGE_SIZE_4M
#define PAGE_SIZE_4M 0x400000
Definition at line 19 of file memory.hpp.
TO_GB
#define TO_GB (d) ((d) / 1024 / 1024 / 1024)
Definition at line 14 of file memory.hpp.
TO_KB
#define TO_KB (d) ((d) / 1024)
Definition at line 10 of file memory.hpp.
TO_MB
#define TO_MB (d) ((d) / 1024 / 1024)
Definition at line 12 of file memory.hpp.
TO_PAGES
#define TO_PAGES (d) (((d) + PAGE_SIZE - 1) / PAGE_SIZE)
Definition at line 23 of file memory.hpp.
Enumeration Type Documentation
PTFlag
enum PTFlag
Enumerator
P
Present.
RW
Read/Write.
US
User/Supervisor.
PWT
Write-Through.
PCD
Cache Disable.
A
Accessed.
D
Dirty.
PS
Page Size.
G
Global.
AVL0
Available 0.
AVL1
Available 1.
AVL2
Available 2.
PAT
Page Attribute Table.
AVL3
Available 3.
AVL4
Available 4.
AVL5
Available 5.
AVL6
Available 6.
AVL7
Available 7.
AVL8
Available 8.
AVL9
Available 9.
PK0
Protection Key 0.
PK1
Protection Key 1.
PK2
Protection Key 2.
PK3
Protection Key 3.
XD
Execute Disable.
Definition at line 27 of file memory.hpp.
 {
     P = 1 << 0,
     RW = 1 << 1,
     US = 1 << 2,
     PWT = 1 << 3,
     PCD = 1 << 4,
     A = 1 << 5,
     D = 1 << 6,
     PS = 1 << 7,
     G = 1 << 8,
     AVL0 = 1 << 9,
     AVL1 = 1 << 10,
     AVL2 = 1 << 11,
     PAT = 1 << 12,
     AVL3 = (uint64_t)1 << 52,
     AVL4 = (uint64_t)1 << 53,
     AVL5 = (uint64_t)1 << 54,
     AVL6 = (uint64_t)1 << 55,
     AVL7 = (uint64_t)1 << 56,
     AVL8 = (uint64_t)1 << 57,
     AVL9 = (uint64_t)1 << 58,
     PK0 = (uint64_t)1 << 59,
     PK1 = (uint64_t)1 << 60,
     PK2 = (uint64_t)1 << 61,
     PK3 = (uint64_t)1 << 62,
     XD = (uint64_t)1 << 63
 };
Function Documentation
InitializeMemoryManagement()
void InitializeMemoryManagement (BootInfo * Info, bool is32)
Definition at line 9 of file Memory.cpp.
 {
     if (is32)
     {
         trace("Initializing Physical Memory Manager");
         // KernelAllocator32 = Physical(); <- Already called in the constructor
         KernelAllocator32.Init(Info);
         info("Memory Info: %lldMB / %lldMB (%lldMB reserved)",
               TO_MB(KernelAllocator32.UsedMemory),
               TO_MB(KernelAllocator32.TotalMemory),
               TO_MB(KernelAllocator32.ReservedMemory));
         trace("Initializing Virtual Memory Manager");
         KernelPageTable32 = (Memory32::PageTable *)KernelAllocator32.RequestPages(TO_PAGES(PAGE_SIZE + 1));
         memset(KernelPageTable32, 0, PAGE_SIZE);
         {
             Memory32::Virtual va = Memory32::Virtual(KernelPageTable32);
             debug("Mapping from 0x0 to %#llx", Info->Memory.Size);
             size_t MemSize = Info->Memory.Size;
             va.Map((void *)0, (void *)0, MemSize, PTFlag::RW);
             debug("Mapping Framebuffer");
             int itrfb = 0;
             while (true)
             {
                 if (!Info->Framebuffer[itrfb].BaseAddress)
                     break;
                 va.Map((void *)Info->Framebuffer[itrfb].BaseAddress,
                        (void *)Info->Framebuffer[itrfb].BaseAddress,
                        Info->Framebuffer[itrfb].Pitch * Info->Framebuffer[itrfb].Height,
                        PTFlag::RW | PTFlag::US | PTFlag::G);
                 itrfb++;
             }
         }
         trace("Applying new page table from address %#lx", KernelPageTable32);
         asmv("mov %0, %%cr3" ::"r"(KernelPageTable32));
     }
 }
References asmv(), debug, G, Info, info, Memory32::Physical::Init(), KernelAllocator32, KernelPageTable32, Memory32::Virtual::Map(), memset(), PAGE_SIZE, Memory32::Physical::RequestPages(), Memory32::Physical::ReservedMemory, RW, TO_MB, TO_PAGES, Memory32::Physical::TotalMemory, trace, US, and Memory32::Physical::UsedMemory.
memcpy()
void* memcpy (void * dest, const void * src, size_t n)
Definition at line 1030 of file Convert.cpp.
 {
     void *ret = __memcpy_chk(dest, src, len, __builtin_object_size(dest, 0));
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "!memcpy( %p %p %ld )=%p~%p\n\r",
                 dest, src, len,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
memset()
void* memset (void * s, int c, size_t n)
Definition at line 1057 of file Convert.cpp.
 {
     void *ret = __memset_chk(dest, val, len, __builtin_object_size(dest, 0));
 #ifdef DEBUG
     if (EnableExternalMemoryTracer)
     {
         char LockTmpStr[64];
         strcpy_unsafe(LockTmpStr, __FUNCTION__);
         strcat_unsafe(LockTmpStr, "_memTrk");
         mExtTrkLock.TimeoutLock(LockTmpStr, 10000);
         sprintf(mExtTrkLog, "!memset( %p %d %ld )=%p~%p\n\r",
                 dest, val, len,
                 ret, __builtin_return_address(0));
         UniversalAsynchronousReceiverTransmitter::UART mTrkUART = UniversalAsynchronousReceiverTransmitter::UART(UniversalAsynchronousReceiverTransmitter::COM3);
         for (short i = 0; i < MEM_TRK_MAX_SIZE; i++)
         {
             if (mExtTrkLog[i] == '\r')
                 break;
             mTrkUART.Write(mExtTrkLog[i]);
         }
         mExtTrkLock.Unlock();
     }
 #endif
     return ret;
 }
Update()
void __aligned::Update ()
Update CR3 with this PageTable.
Definition at line 5 of file memory.hpp.
 {
Variable Documentation
_kernel_end
uintptr_t _kernel_end
Definition at line 7 of file memory.hpp.
_kernel_start
uintptr_t _kernel_start extern
Entries
PageMapLevel4 Entries[511]
Definition at line 0 of file memory.hpp.
KernelAllocator32
Memory32::Physical KernelAllocator32 extern
Definition at line 3 of file Memory.cpp.
Referenced by __cxa_allocate_exception(), InitializeMemoryManagement(), LoadElfInMemory(), and Memory32::Virtual::Map().
KernelAllocator64
Memory64::Physical KernelAllocator64 extern
Definition at line 6 of file Memory.cpp.
Referenced by Memory64::Virtual::Map().
KernelPageTable32
Memory32::PageTable* KernelPageTable32 extern
Definition at line 4 of file Memory.cpp.
Referenced by InitializeMemoryManagement().
KernelPageTable64
Memory64::PageTable* KernelPageTable64 extern
Definition at line 7 of file Memory.cpp.