Fennix: Userspace/apps/base/busybox/util-linux/getopt.c File Reference
getopt.c File Reference
#include "libbb.h"
Macros
#define alternative (option_mask32 & OPT_a)
#define quiet_errors (option_mask32 & OPT_q)
#define quiet_output (option_mask32 & OPT_Q)
#define quote (!(option_mask32 & OPT_u))
#define shell_TCSH (option_mask32 & SHELL_IS_TCSH)
#define generate_output(argv, argc, optstr, longopts) generate_output(argv,argc,optstr)
Enumerations
enum { NON_OPT = 1 }
enum {
OPT_o = 0x1 , OPT_n = 0x2 , OPT_q = 0x4 , OPT_Q = 0x8 ,
OPT_s = 0x10 , OPT_T = 0x20 , OPT_u = 0x40 , SHELL_IS_TCSH = 0x8000
}
Functions
static const char * normalize (const char *arg)
static int generate_output (char **argv, int argc, const char *optstr, const struct option *longopts)
static void set_shell (const char *new_shell)
int getopt_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Macro Definition Documentation
alternative
#define alternative (option_mask32 & OPT_a)
Definition at line 140 of file getopt.c.
generate_output
#define generate_output (argv, argc, optstr, longopts) generate_output(argv,argc,optstr)
Definition at line 207 of file getopt.c.
quiet_errors
#define quiet_errors (option_mask32 & OPT_q)
Definition at line 142 of file getopt.c.
quiet_output
#define quiet_output (option_mask32 & OPT_Q)
Definition at line 143 of file getopt.c.
quote
#define quote (!(option_mask32 & OPT_u))
Definition at line 144 of file getopt.c.
shell_TCSH
#define shell_TCSH (option_mask32 & SHELL_IS_TCSH)
Definition at line 145 of file getopt.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NON_OPT
Definition at line 115 of file getopt.c.
      {
     NON_OPT = 1,
 #if ENABLE_FEATURE_GETOPT_LONG
 /* LONG_OPT is the code that is returned when a long option is found. */
     LONG_OPT = 2
 #endif
 };
anonymous enum
anonymous enum
Enumerator
OPT_o
OPT_n
OPT_q
OPT_Q
OPT_s
OPT_T
OPT_u
SHELL_IS_TCSH
Definition at line 124 of file getopt.c.
      {
     OPT_o   = 0x1,  // -o
     OPT_n   = 0x2,  // -n
     OPT_q   = 0x4,  // -q
     OPT_Q   = 0x8,  // -Q
     OPT_s   = 0x10, // -s
     OPT_T   = 0x20, // -T
     OPT_u   = 0x40, // -u
 #if ENABLE_FEATURE_GETOPT_LONG
     OPT_a   = 0x80, // -a
     OPT_l   = 0x100, // -l
 #endif
     SHELL_IS_TCSH = 0x8000, /* hijack this bit for other purposes */
 };
Function Documentation
generate_output()
static int generate_output (char ** argv, int argc, const char * optstr, const struct option * longopts) static
Definition at line 210 of file getopt.c.
 {
     int exit_code = 0; /* We assume everything will be OK */
     if (quiet_errors) /* No error reporting from getopt(3) */
         opterr = 0;
     /* We used it already in main() in getopt32(),
      * we *must* reset getopt(3): */
     GETOPT_RESET();
     while (1) {
 #if ENABLE_FEATURE_GETOPT_LONG
         int longindex;
         int opt = alternative
             ? getopt_long_only(argc, argv, optstr, longopts, &longindex)
             : getopt_long(argc, argv, optstr, longopts, &longindex)
         ;
 #else
         int opt = getopt(argc, argv, optstr);
 #endif
         if (opt == -1)
             break;
         if (opt == '?' || opt == ':' )
             exit_code = 1;
         else if (!quiet_output) {
 #if ENABLE_FEATURE_GETOPT_LONG
             if (opt == LONG_OPT) {
                 printf(" --%s", longopts[longindex].name);
                 if (longopts[longindex].has_arg)
                     printf(" %s",
                         normalize(optarg ? optarg : ""));
             } else
 #endif
             if (opt == NON_OPT)
                 printf(" %s", normalize(optarg));
             else {
                 const char *charptr;
                 printf(" -%c", opt);
                 charptr = strchr(optstr, opt);
                 if (charptr && *++charptr == ':')
                     printf(" %s",
                         normalize(optarg ? optarg : ""));
             }
         }
     }
     if (!quiet_output) {
         unsigned idx;
         printf(" --");
         idx = optind;
         while (argv[idx])
             printf(" %s", normalize(argv[idx++]));
         bb_putchar('\n');
     }
     return exit_code;
 }
References alternative, argc, argv, bb_putchar(), getopt(), getopt_long(), getopt_long_only(), GETOPT_RESET, idx, NON_OPT, normalize(), opt, optarg, opterr, optind, printf, quiet_errors, quiet_output, and strchr().
getopt_main()
int getopt_main (int argc, char ** argv)
Definition at line 354 of file getopt.c.
 {
     int n;
     char *optstr = NULL;
     char *name = NULL;
     unsigned opt;
     const char *compatible;
     char *s_arg;
 #if ENABLE_FEATURE_GETOPT_LONG
     struct option *long_options = NULL;
     llist_t *l_arg = NULL;
 #endif
     compatible = getenv("GETOPT_COMPATIBLE"); /* used as yes/no flag */
     if (!argv[1]) {
         if (compatible) {
             /* For some reason, the original getopt gave no error
              * when there were no arguments. */
             puts(" --");
             return 0;
         }
         bb_simple_error_msg_and_die("missing optstring argument");
     }
     if (argv[1][0] != '-' || compatible) {
         char *s = argv[1];
         option_mask32 |= OPT_u; /* quoting off */
         s = xstrdup(s + strspn(s, "-+"));
         argv[1] = argv[0];
         return generate_output(argv+1, argc-1, s, long_options);
     }
 #if !ENABLE_FEATURE_GETOPT_LONG
     opt = getopt32(argv, "+o:n:qQs:Tu", &optstr, &name, &s_arg);
 #else
     opt = getopt32long(argv, "+o:n:qQs:Tual:*", getopt_longopts,
                     &optstr, &name, &s_arg, &l_arg);
     /* Effectuate the read options for the applet itself */
     while (l_arg) {
         long_options = add_long_options(long_options, llist_pop(&l_arg));
     }
 #endif
     if (opt & OPT_s) {
         set_shell(s_arg);
     }
     if (opt & OPT_T) {
         return 4;
     }
     /* All options controlling the applet have now been parsed */
     n = optind - 1;
     if (!optstr) {
         optstr = argv[++n];
         if (!optstr)
             bb_simple_error_msg_and_die("missing optstring argument");
     }
     argv[n] = name ? name : argv[0];
     return generate_output(argv + n, argc - n, optstr, long_options);
 }
References argc, argv, bb_simple_error_msg_and_die(), generate_output, getenv, getopt32(), getopt32long, llist_pop(), n, option::name, NULL, opt, OPT_s, OPT_T, OPT_u, optind, option_mask32, puts(), s, set_shell(), strspn(), and xstrdup().
normalize()
static const char* normalize (const char * arg) static
Definition at line 156 of file getopt.c.
 {
     char *bufptr;
     char *BUFFER;
     if (!quote) { /* Just return arg */
         return arg;
     }
     /* Each character in arg may take up to four characters in the result:
        For a quote we need a closing quote, a backslash, a quote and an
        opening quote! We need also the global opening and closing quote,
        and one extra character for '\0'. */
     BUFFER = auto_string(xmalloc(strlen(arg)*4 + 3));
     bufptr = BUFFER;
     *bufptr ++= '\'';
     while (*arg) {
         if (shell_TCSH && *arg == '\n') {
             /* Newline: replace it with: \n */
             *bufptr++ = '\\';
             *bufptr++ = 'n';
         } else
         if ((shell_TCSH && (*arg == '!' || isspace(*arg)))
          || *arg == '\''
         ) {
             /* Quote exclamation marks, non-NL whitespace and quotes */
             *bufptr++ = '\'';
             *bufptr++ = '\\';
             *bufptr++ = *arg;
             *bufptr++ = '\'';
         } else {
             /* Just copy */
             *bufptr ++= *arg;
         }
         arg++;
     }
     *bufptr++ = '\'';
     *bufptr++ = '\0';
     return BUFFER;
 }
References auto_string(), bufptr, isspace, quote, shell_TCSH, strlen(), and xmalloc.
Referenced by generate_output().
set_shell()
static void set_shell (const char * new_shell) static
Definition at line 314 of file getopt.c.
 {
     switch (index_in_strings("bash\0sh\0tcsh\0csh\0", new_shell)) {
     case 0:
     case 1:
         break;
     case 2:
     case 3:
         option_mask32 |= SHELL_IS_TCSH;
         break;
     default:
         bb_error_msg("unknown shell '%s', assuming bash", new_shell);
         break;
     }
 }
References bb_error_msg(), index_in_strings(), option_mask32, and SHELL_IS_TCSH.
Referenced by getopt_main().