Fennix Userspace: Userspace/musl/src/time/getdate.c File Reference
getdate.c File Reference
#include <time.h>
#include <pthread.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
Functions
struct tm * getdate (const char *s)
Variables
int getdate_err
Function Documentation
getdate()
struct tm* getdate (const char * s)
Definition at line 9 of file getdate.c.
 {
     static struct tm tmbuf;
     struct tm *ret = 0;
     char *datemsk = getenv("DATEMSK");
     FILE *f = 0;
     char fmt[100], *p;
     int cs;
     pthread_setcancelstate(PTHREAD_CANCEL_DEFERRED, &cs);
     if (!datemsk) {
         getdate_err = 1;
         goto out;
     }
     f = fopen(datemsk, "rbe");
     if (!f) {
         if (errno == ENOMEM) getdate_err = 6;
         else getdate_err = 2;
         goto out;
     }
     while (fgets(fmt, sizeof fmt, f)) {
         p = strptime(s, fmt, &tmbuf);
         if (p && !*p) {
             ret = &tmbuf;
             goto out;
         }
     }
     if (ferror(f)) getdate_err = 5;
     else getdate_err = 7;
 out:
     if (f) fclose(f);
     pthread_setcancelstate(cs, 0);
     return ret;
 }
References ENOMEM, errno, f, fclose(), ferror, fgets(), fopen(), getdate_err, getenv(), out(), p, PTHREAD_CANCEL_DEFERRED, pthread_setcancelstate(), and strptime().
Variable Documentation
getdate_err
int getdate_err
Definition at line 7 of file getdate.c.
Referenced by getdate().