Fennix: Userspace/apps/base/busybox/shell/ash_test/printenv.c File Reference
printenv.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
int main (int argc, char **argv)
Variables
char ** environ
Function Documentation
main()
int main (int argc , char ** argv)
Definition at line 34 of file printenv.c.
 {
   register char **envp, *eval;
   int len;
   argv++;
   argc--;
   /* printenv */
   if (argc == 0)
     {
       for (envp = environ; *envp; envp++)
     puts (*envp);
       exit(EXIT_SUCCESS);
     }
   /* printenv varname */
   len = strlen (*argv);
   for (envp = environ; *envp; envp++)
     {
       if (**argv == **envp && strncmp (*envp, *argv, len) == 0)
     {
       eval = *envp + len;
       /* If the environment variable doesn't have an '=', ignore it. */
       if (*eval == '=')
         {
           puts (eval + 1);
           exit(EXIT_SUCCESS);
         }
     }
     }
   exit(EXIT_FAILURE);
 }
References argc, argv, environ, eval(), exit(), EXIT_FAILURE, EXIT_SUCCESS, len, puts(), strlen, and strncmp().
Variable Documentation
environ
char** environ extern
Definition at line 42 of file lib.c.