Fennix: Userspace/apps/base/busybox/scripts/kconfig/expr.c File Reference
expr.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lkc.h"
Macros
#define LKC_DIRECT_LINK
#define DEBUG_EXPR 0
#define e1 (*ep1)
#define e2 (*ep2)
#define e1 (*ep1)
#define e2 (*ep2)
#define e1 (*ep1)
#define e2 (*ep2)
#define e1 (*ep1)
#define e2 (*ep2)
Functions
struct expr * expr_alloc_symbol (struct symbol *sym)
struct expr * expr_alloc_one (enum expr_type type, struct expr *ce)
struct expr * expr_alloc_two (enum expr_type type, struct expr *e1, struct expr *e2)
struct expr * expr_alloc_comp (enum expr_type type, struct symbol *s1, struct symbol *s2)
struct expr * expr_alloc_and (struct expr *e1, struct expr *e2)
struct expr * expr_alloc_or (struct expr *e1, struct expr *e2)
struct expr * expr_copy (struct expr *org)
void expr_free (struct expr *e)
static void __expr_eliminate_eq (enum expr_type type, struct expr **ep1, struct expr **ep2)
void expr_eliminate_eq (struct expr **ep1, struct expr **ep2)
int expr_eq (struct expr *e1, struct expr *e2)
struct expr * expr_eliminate_yn (struct expr *e)
struct expr * expr_trans_bool (struct expr *e)
struct expr * expr_join_or (struct expr *e1, struct expr *e2)
struct expr * expr_join_and (struct expr *e1, struct expr *e2)
static void expr_eliminate_dups1 (enum expr_type type, struct expr **ep1, struct expr **ep2)
static void expr_eliminate_dups2 (enum expr_type type, struct expr **ep1, struct expr **ep2)
struct expr * expr_eliminate_dups (struct expr *e)
struct expr * expr_transform (struct expr *e)
int expr_contains_symbol (struct expr *dep, struct symbol *sym)
bool expr_depends_symbol (struct expr *dep, struct symbol *sym)
struct expr * expr_extract_eq_and (struct expr **ep1, struct expr **ep2)
struct expr * expr_extract_eq_or (struct expr **ep1, struct expr **ep2)
void expr_extract_eq (enum expr_type type, struct expr **ep, struct expr **ep1, struct expr **ep2)
struct expr * expr_trans_compare (struct expr *e, enum expr_type type, struct symbol *sym)
tristate expr_calc_value (struct expr *e)
int expr_compare_type (enum expr_type t1, enum expr_type t2)
void expr_print (struct expr *e, void(*fn)(void *, const char *), void *data, int prevtoken)
static void expr_print_file_helper (void *data, const char *str)
void expr_fprint (struct expr *e, FILE *out)
static void expr_print_gstr_helper (void *data, const char *str)
void expr_gstr_print (struct expr *e, struct gstr *gs)
Variables
static int trans_count
Macro Definition Documentation
DEBUG_EXPR
#define DEBUG_EXPR 0
Definition at line 13 of file expr.c.
e1 [1/4]
#define e1 (*ep1)
Definition at line 132 of file expr.c.
e1 [2/4]
#define e1 (*ep1)
Definition at line 132 of file expr.c.
e1 [3/4]
#define e1 (*ep1)
Definition at line 132 of file expr.c.
e1 [4/4]
#define e1 (*ep1)
Definition at line 132 of file expr.c.
e2 [1/4]
#define e2 (*ep2)
Definition at line 133 of file expr.c.
e2 [2/4]
#define e2 (*ep2)
Definition at line 133 of file expr.c.
e2 [3/4]
#define e2 (*ep2)
Definition at line 133 of file expr.c.
e2 [4/4]
#define e2 (*ep2)
Definition at line 133 of file expr.c.
LKC_DIRECT_LINK
#define LKC_DIRECT_LINK
Definition at line 10 of file expr.c.
Function Documentation
__expr_eliminate_eq()
static void __expr_eliminate_eq (enum expr_type type, struct expr ** ep1, struct expr ** ep2) static
Definition at line 135 of file expr.c.
 {
     if (e1->type == type) {
         __expr_eliminate_eq(type, &e1->left.expr, &e2);
         __expr_eliminate_eq(type, &e1->right.expr, &e2);
         return;
     }
     if (e2->type == type) {
         __expr_eliminate_eq(type, &e1, &e2->left.expr);
         __expr_eliminate_eq(type, &e1, &e2->right.expr);
         return;
     }
     if (e1->type == E_SYMBOL && e2->type == E_SYMBOL &&
         e1->left.sym == e2->left.sym && (e1->left.sym->flags & (SYMBOL_YES|SYMBOL_NO)))
         return;
     if (!expr_eq(e1, e2))
         return;
     trans_count++;
     expr_free(e1); expr_free(e2);
     switch (type) {
     case E_OR:
         e1 = expr_alloc_symbol(&symbol_no);
         e2 = expr_alloc_symbol(&symbol_no);
         break;
     case E_AND:
         e1 = expr_alloc_symbol(&symbol_yes);
         e2 = expr_alloc_symbol(&symbol_yes);
         break;
     default:
         ;
     }
 }
References e1, e2, E_AND, E_OR, E_SYMBOL, expr_alloc_symbol(), expr_eq(), expr_free(), SYMBOL_NO, symbol_no, SYMBOL_YES, symbol_yes, trans_count, and type.
Referenced by expr_eliminate_eq().
expr_alloc_and()
struct expr* expr_alloc_and (struct expr * e1, struct expr * e2)
Definition at line 53 of file expr.c.
 {
     if (!e1)
         return e2;
     return e2 ? expr_alloc_two(E_AND, e1, e2) : e1;
 }
References e1, e2, E_AND, and expr_alloc_two().
Referenced by menu_add_dep(), menu_check_dep(), and menu_finalize().
expr_alloc_comp()
struct expr* expr_alloc_comp (enum expr_type type, struct symbol * s1, struct symbol * s2)
Definition at line 43 of file expr.c.
 {
     struct expr *e = malloc(sizeof(*e));
     memset(e, 0, sizeof(*e));
     e->type = type;
     e->left.sym = s1;
     e->right.sym = s2;
     return e;
 }
References malloc, memset, expr::right, s1, s2, expr_data::sym, type, and expr::type.
Referenced by expr_join_and(), expr_join_or(), and expr_trans_compare().
expr_alloc_one()
struct expr* expr_alloc_one (enum expr_type type, struct expr * ce)
Definition at line 24 of file expr.c.
 {
     struct expr *e = malloc(sizeof(*e));
     memset(e, 0, sizeof(*e));
     e->type = type;
     e->left.expr = ce;
     return e;
 }
References malloc, memset, type, and expr::type.
Referenced by expr_eliminate_dups2(), expr_trans_compare(), expr_transform(), and menu_finalize().
expr_alloc_or()
struct expr* expr_alloc_or (struct expr * e1, struct expr * e2)
Definition at line 60 of file expr.c.
 {
     if (!e1)
         return e2;
     return e2 ? expr_alloc_two(E_OR, e1, e2) : e1;
 }
References e1, e2, E_OR, and expr_alloc_two().
Referenced by menu_finalize().
expr_alloc_symbol()
struct expr* expr_alloc_symbol (struct symbol * sym)
Definition at line 15 of file expr.c.
 {
     struct expr *e = malloc(sizeof(*e));
     memset(e, 0, sizeof(*e));
     e->type = E_SYMBOL;
     e->left.sym = sym;
     return e;
 }
References E_SYMBOL, malloc, memset, and expr::type.
Referenced by __expr_eliminate_eq(), expr_eliminate_dups1(), expr_eliminate_dups2(), expr_extract_eq(), expr_join_and(), expr_join_or(), expr_trans_compare(), expr_transform(), menu_add_symbol(), menu_check_dep(), menu_finalize(), and sym_add_default().
expr_alloc_two()
struct expr* expr_alloc_two (enum expr_type type, struct expr * e1, struct expr * e2)
Definition at line 33 of file expr.c.
 {
     struct expr *e = malloc(sizeof(*e));
     memset(e, 0, sizeof(*e));
     e->type = type;
     e->left.expr = e1;
     e->right.expr = e2;
     return e;
 }
References e1, e2, expr_data::expr, malloc, memset, expr::right, type, and expr::type.
Referenced by expr_alloc_and(), expr_alloc_or(), expr_extract_eq(), and expr_trans_compare().
expr_calc_value()
tristate expr_calc_value (struct expr * e)
Definition at line 942 of file expr.c.
 {
     tristate val1, val2;
     const char *str1, *str2;
     if (!e)
         return yes;
     switch (e->type) {
     case E_SYMBOL:
         sym_calc_value(e->left.sym);
         return e->left.sym->curr.tri;
     case E_AND:
         val1 = expr_calc_value(e->left.expr);
         val2 = expr_calc_value(e->right.expr);
         return E_AND(val1, val2);
     case E_OR:
         val1 = expr_calc_value(e->left.expr);
         val2 = expr_calc_value(e->right.expr);
         return E_OR(val1, val2);
     case E_NOT:
         val1 = expr_calc_value(e->left.expr);
         return E_NOT(val1);
     case E_EQUAL:
         sym_calc_value(e->left.sym);
         sym_calc_value(e->right.sym);
         str1 = sym_get_string_value(e->left.sym);
         str2 = sym_get_string_value(e->right.sym);
         return !strcmp(str1, str2) ? yes : no;
     case E_UNEQUAL:
         sym_calc_value(e->left.sym);
         sym_calc_value(e->right.sym);
         str1 = sym_get_string_value(e->left.sym);
         str2 = sym_get_string_value(e->right.sym);
         return !strcmp(str1, str2) ? no : yes;
     default:
         printf("expr_calc_value: %d?\n", e->type);
         return no;
     }
 }
References E_AND, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, no, printf, expr::right, strcmp, expr_data::sym, sym_calc_value(), sym_get_string_value(), expr::type, and yes.
Referenced by menu_is_visible(), sym_calc_choice(), sym_calc_value(), sym_calc_visibility(), sym_get_default_prop(), and sym_get_range_prop().
expr_compare_type()
int expr_compare_type (enum expr_type t1, enum expr_type t2)
Definition at line 983 of file expr.c.
 {
 #if 0
     return 1;
 #else
     if (t1 == t2)
         return 0;
     switch (t1) {
     case E_EQUAL:
     case E_UNEQUAL:
         if (t2 == E_NOT)
             return 1;
     case E_NOT:
         if (t2 == E_AND)
             return 1;
     case E_AND:
         if (t2 == E_OR)
             return 1;
     case E_OR:
         if (t2 == E_CHOICE)
             return 1;
     case E_CHOICE:
         if (t2 == 0)
             return 1;
     default:
         return -1;
     }
     printf("[%dgt%d?]", t1, t2);
     return 0;
 #endif
 }
References E_AND, E_CHOICE, E_EQUAL, E_NOT, E_OR, E_UNEQUAL, printf, t1, and t2.
Referenced by expr_print().
expr_contains_symbol()
int expr_contains_symbol (struct expr * dep, struct symbol * sym)
Definition at line 777 of file expr.c.
 {
     if (!dep)
         return 0;
     switch (dep->type) {
     case E_AND:
     case E_OR:
         return expr_contains_symbol(dep->left.expr, sym) ||
                expr_contains_symbol(dep->right.expr, sym);
     case E_SYMBOL:
         return dep->left.sym == sym;
     case E_EQUAL:
     case E_UNEQUAL:
         return dep->left.sym == sym ||
                dep->right.sym == sym;
     case E_NOT:
         return expr_contains_symbol(dep->left.expr, sym);
     default:
         ;
     }
     return 0;
 }
References E_AND, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr::right, expr_data::sym, and expr::type.
Referenced by menu_finalize().
expr_copy()
struct expr* expr_copy (struct expr * org)
Definition at line 67 of file expr.c.
 {
     struct expr *e;
     if (!org)
         return NULL;
     e = malloc(sizeof(*org));
     memcpy(e, org, sizeof(*org));
     switch (org->type) {
     case E_SYMBOL:
         e->left = org->left;
         break;
     case E_NOT:
         e->left.expr = expr_copy(org->left.expr);
         break;
     case E_EQUAL:
     case E_UNEQUAL:
         e->left.sym = org->left.sym;
         e->right.sym = org->right.sym;
         break;
     case E_AND:
     case E_OR:
     case E_CHOICE:
         e->left.expr = expr_copy(org->left.expr);
         e->right.expr = expr_copy(org->right.expr);
         break;
     default:
         printf("can't copy type %d\n", e->type);
         free(e);
         e = NULL;
         break;
     }
     return e;
 }
References E_AND, E_CHOICE, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, free, malloc, memcpy, NULL, printf, expr::right, expr_data::sym, and expr::type.
Referenced by expr_eliminate_dups2(), expr_eq(), expr_join_and(), expr_join_or(), expr_trans_compare(), and menu_finalize().
expr_depends_symbol()
bool expr_depends_symbol (struct expr * dep, struct symbol * sym)
Definition at line 801 of file expr.c.
 {
     if (!dep)
         return false;
     switch (dep->type) {
     case E_AND:
         return expr_depends_symbol(dep->left.expr, sym) ||
                expr_depends_symbol(dep->right.expr, sym);
     case E_SYMBOL:
         return dep->left.sym == sym;
     case E_EQUAL:
         if (dep->left.sym == sym) {
             if (dep->right.sym == &symbol_yes || dep->right.sym == &symbol_mod)
                 return true;
         }
         break;
     case E_UNEQUAL:
         if (dep->left.sym == sym) {
             if (dep->right.sym == &symbol_no)
                 return true;
         }
         break;
     default:
         ;
     }
     return false;
 }
References E_AND, E_EQUAL, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr::right, expr_data::sym, symbol_mod, symbol_no, symbol_yes, and expr::type.
Referenced by menu_finalize().
expr_eliminate_dups()
struct expr* expr_eliminate_dups (struct expr * e)
Definition at line 616 of file expr.c.
 {
     int oldcount;
     if (!e)
         return e;
     oldcount = trans_count;
     while (1) {
         trans_count = 0;
         switch (e->type) {
         case E_OR: case E_AND:
             expr_eliminate_dups1(e->type, &e, &e);
             expr_eliminate_dups2(e->type, &e, &e);
         default:
             ;
         }
         if (!trans_count)
             break;
         e = expr_eliminate_yn(e);
     }
     trans_count = oldcount;
     return e;
 }
References E_AND, E_OR, expr_eliminate_dups1(), expr_eliminate_dups2(), expr_eliminate_yn(), trans_count, and expr::type.
Referenced by menu_finalize().
expr_eliminate_dups1()
static void expr_eliminate_dups1 (enum expr_type type, struct expr ** ep1, struct expr ** ep2) static
Definition at line 508 of file expr.c.
 {
 #define e1 (*ep1)
 #define e2 (*ep2)
     struct expr *tmp;
     if (e1->type == type) {
         expr_eliminate_dups1(type, &e1->left.expr, &e2);
         expr_eliminate_dups1(type, &e1->right.expr, &e2);
         return;
     }
     if (e2->type == type) {
         expr_eliminate_dups1(type, &e1, &e2->left.expr);
         expr_eliminate_dups1(type, &e1, &e2->right.expr);
         return;
     }
     if (e1 == e2)
         return;
     switch (e1->type) {
     case E_OR: case E_AND:
         expr_eliminate_dups1(e1->type, &e1, &e1);
     default:
         ;
     }
     switch (type) {
     case E_OR:
         tmp = expr_join_or(e1, e2);
         if (tmp) {
             expr_free(e1); expr_free(e2);
             e1 = expr_alloc_symbol(&symbol_no);
             e2 = tmp;
             trans_count++;
         }
         break;
     case E_AND:
         tmp = expr_join_and(e1, e2);
         if (tmp) {
             expr_free(e1); expr_free(e2);
             e1 = expr_alloc_symbol(&symbol_yes);
             e2 = tmp;
             trans_count++;
         }
         break;
     default:
         ;
     }
 #undef e1
 #undef e2
 }
References e1, e2, E_AND, E_OR, expr_alloc_symbol(), expr_free(), expr_join_and(), expr_join_or(), symbol_no, symbol_yes, trans_count, and type.
Referenced by expr_eliminate_dups().
expr_eliminate_dups2()
static void expr_eliminate_dups2 (enum expr_type type, struct expr ** ep1, struct expr ** ep2) static
Definition at line 560 of file expr.c.
 {
 #define e1 (*ep1)
 #define e2 (*ep2)
     struct expr *tmp, *tmp1, *tmp2;
     if (e1->type == type) {
         expr_eliminate_dups2(type, &e1->left.expr, &e2);
         expr_eliminate_dups2(type, &e1->right.expr, &e2);
         return;
     }
     if (e2->type == type) {
         expr_eliminate_dups2(type, &e1, &e2->left.expr);
         expr_eliminate_dups2(type, &e1, &e2->right.expr);
     }
     if (e1 == e2)
         return;
     switch (e1->type) {
     case E_OR:
         expr_eliminate_dups2(e1->type, &e1, &e1);
         // (FOO || BAR) && (!FOO && !BAR) -> n
         tmp1 = expr_transform(expr_alloc_one(E_NOT, expr_copy(e1)));
         tmp2 = expr_copy(e2);
         tmp = expr_extract_eq_and(&tmp1, &tmp2);
         if (expr_is_yes(tmp1)) {
             expr_free(e1);
             e1 = expr_alloc_symbol(&symbol_no);
             trans_count++;
         }
         expr_free(tmp2);
         expr_free(tmp1);
         expr_free(tmp);
         break;
     case E_AND:
         expr_eliminate_dups2(e1->type, &e1, &e1);
         // (FOO && BAR) || (!FOO || !BAR) -> y
         tmp1 = expr_transform(expr_alloc_one(E_NOT, expr_copy(e1)));
         tmp2 = expr_copy(e2);
         tmp = expr_extract_eq_or(&tmp1, &tmp2);
         if (expr_is_no(tmp1)) {
             expr_free(e1);
             e1 = expr_alloc_symbol(&symbol_yes);
             trans_count++;
         }
         expr_free(tmp2);
         expr_free(tmp1);
         expr_free(tmp);
         break;
     default:
         ;
     }
 #undef e1
 #undef e2
 }
References e1, e2, E_AND, E_NOT, E_OR, expr_alloc_one(), expr_alloc_symbol(), expr_copy(), expr_extract_eq_and(), expr_extract_eq_or(), expr_free(), expr_is_no(), expr_is_yes(), expr_transform(), symbol_no, symbol_yes, trans_count, and type.
Referenced by expr_eliminate_dups().
expr_eliminate_eq()
void expr_eliminate_eq (struct expr ** ep1, struct expr ** ep2)
Definition at line 168 of file expr.c.
 {
     if (!e1 || !e2)
         return;
     switch (e1->type) {
     case E_OR:
     case E_AND:
         __expr_eliminate_eq(e1->type, ep1, ep2);
     default:
         ;
     }
     if (e1->type != e2->type) switch (e2->type) {
     case E_OR:
     case E_AND:
         __expr_eliminate_eq(e2->type, ep1, ep2);
     default:
         ;
     }
     e1 = expr_eliminate_yn(e1);
     e2 = expr_eliminate_yn(e2);
 }
References __expr_eliminate_eq(), e1, e2, E_AND, E_OR, ep1, ep2, and expr_eliminate_yn().
Referenced by expr_eq(), and menu_finalize().
expr_eliminate_yn()
struct expr* expr_eliminate_yn (struct expr * e)
Definition at line 235 of file expr.c.
 {
     struct expr *tmp;
     if (e) switch (e->type) {
     case E_AND:
         e->left.expr = expr_eliminate_yn(e->left.expr);
         e->right.expr = expr_eliminate_yn(e->right.expr);
         if (e->left.expr->type == E_SYMBOL) {
             if (e->left.expr->left.sym == &symbol_no) {
                 expr_free(e->left.expr);
                 expr_free(e->right.expr);
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_no;
                 e->right.expr = NULL;
                 return e;
             } else if (e->left.expr->left.sym == &symbol_yes) {
                 free(e->left.expr);
                 tmp = e->right.expr;
                 *e = *(e->right.expr);
                 free(tmp);
                 return e;
             }
         }
         if (e->right.expr->type == E_SYMBOL) {
             if (e->right.expr->left.sym == &symbol_no) {
                 expr_free(e->left.expr);
                 expr_free(e->right.expr);
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_no;
                 e->right.expr = NULL;
                 return e;
             } else if (e->right.expr->left.sym == &symbol_yes) {
                 free(e->right.expr);
                 tmp = e->left.expr;
                 *e = *(e->left.expr);
                 free(tmp);
                 return e;
             }
         }
         break;
     case E_OR:
         e->left.expr = expr_eliminate_yn(e->left.expr);
         e->right.expr = expr_eliminate_yn(e->right.expr);
         if (e->left.expr->type == E_SYMBOL) {
             if (e->left.expr->left.sym == &symbol_no) {
                 free(e->left.expr);
                 tmp = e->right.expr;
                 *e = *(e->right.expr);
                 free(tmp);
                 return e;
             } else if (e->left.expr->left.sym == &symbol_yes) {
                 expr_free(e->left.expr);
                 expr_free(e->right.expr);
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_yes;
                 e->right.expr = NULL;
                 return e;
             }
         }
         if (e->right.expr->type == E_SYMBOL) {
             if (e->right.expr->left.sym == &symbol_no) {
                 free(e->right.expr);
                 tmp = e->left.expr;
                 *e = *(e->left.expr);
                 free(tmp);
                 return e;
             } else if (e->right.expr->left.sym == &symbol_yes) {
                 expr_free(e->left.expr);
                 expr_free(e->right.expr);
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_yes;
                 e->right.expr = NULL;
                 return e;
             }
         }
         break;
     default:
         ;
     }
     return e;
 }
References E_AND, E_OR, E_SYMBOL, expr_data::expr, expr_free(), free, NULL, expr::right, symbol_no, symbol_yes, and expr::type.
Referenced by expr_eliminate_dups(), expr_eliminate_eq(), expr_extract_eq_and(), and expr_extract_eq_or().
expr_eq()
int expr_eq (struct expr * e1, struct expr * e2)
Definition at line 193 of file expr.c.
 {
     int res, old_count;
     if (e1->type != e2->type)
         return 0;
     switch (e1->type) {
     case E_EQUAL:
     case E_UNEQUAL:
         return e1->left.sym == e2->left.sym && e1->right.sym == e2->right.sym;
     case E_SYMBOL:
         return e1->left.sym == e2->left.sym;
     case E_NOT:
         return expr_eq(e1->left.expr, e2->left.expr);
     case E_AND:
     case E_OR:
         e1 = expr_copy(e1);
         e2 = expr_copy(e2);
         old_count = trans_count;
         expr_eliminate_eq(&e1, &e2);
         res = (e1->type == E_SYMBOL && e2->type == E_SYMBOL &&
                e1->left.sym == e2->left.sym);
         expr_free(e1);
         expr_free(e2);
         trans_count = old_count;
         return res;
     case E_CHOICE:
     case E_RANGE:
     case E_NONE:
         /* panic */;
     }
     if (DEBUG_EXPR) {
         expr_fprint(e1, stdout);
         printf(" = ");
         expr_fprint(e2, stdout);
         printf(" ?\n");
     }
     return 0;
 }
References DEBUG_EXPR, e1, e2, E_AND, E_CHOICE, E_EQUAL, E_NONE, E_NOT, E_OR, E_RANGE, E_SYMBOL, E_UNEQUAL, expr_copy(), expr_eliminate_eq(), expr_fprint(), expr_free(), printf, stdout, and trans_count.
Referenced by __expr_eliminate_eq(), expr_extract_eq(), expr_join_and(), and expr_join_or().
expr_extract_eq()
void expr_extract_eq (enum expr_type type, struct expr ** ep, struct expr ** ep1, struct expr ** ep2)
Definition at line 852 of file expr.c.
 {
 #define e1 (*ep1)
 #define e2 (*ep2)
     if (e1->type == type) {
         expr_extract_eq(type, ep, &e1->left.expr, &e2);
         expr_extract_eq(type, ep, &e1->right.expr, &e2);
         return;
     }
     if (e2->type == type) {
         expr_extract_eq(type, ep, ep1, &e2->left.expr);
         expr_extract_eq(type, ep, ep1, &e2->right.expr);
         return;
     }
     if (expr_eq(e1, e2)) {
         *ep = *ep ? expr_alloc_two(type, *ep, e1) : e1;
         expr_free(e2);
         if (type == E_AND) {
             e1 = expr_alloc_symbol(&symbol_yes);
             e2 = expr_alloc_symbol(&symbol_yes);
         } else if (type == E_OR) {
             e1 = expr_alloc_symbol(&symbol_no);
             e2 = expr_alloc_symbol(&symbol_no);
         }
     }
 #undef e1
 #undef e2
 }
References e1, e2, E_AND, E_OR, ep1, expr_alloc_symbol(), expr_alloc_two(), expr_eq(), expr_free(), symbol_no, symbol_yes, and type.
Referenced by expr_extract_eq_and(), and expr_extract_eq_or().
expr_extract_eq_and()
struct expr* expr_extract_eq_and (struct expr ** ep1, struct expr ** ep2)
Definition at line 830 of file expr.c.
 {
     struct expr *tmp = NULL;
     expr_extract_eq(E_AND, &tmp, ep1, ep2);
     if (tmp) {
         *ep1 = expr_eliminate_yn(*ep1);
         *ep2 = expr_eliminate_yn(*ep2);
     }
     return tmp;
 }
References E_AND, ep1, ep2, expr_eliminate_yn(), expr_extract_eq(), and NULL.
Referenced by expr_eliminate_dups2().
expr_extract_eq_or()
struct expr* expr_extract_eq_or (struct expr ** ep1, struct expr ** ep2)
Definition at line 841 of file expr.c.
 {
     struct expr *tmp = NULL;
     expr_extract_eq(E_OR, &tmp, ep1, ep2);
     if (tmp) {
         *ep1 = expr_eliminate_yn(*ep1);
         *ep2 = expr_eliminate_yn(*ep2);
     }
     return tmp;
 }
References E_OR, ep1, ep2, expr_eliminate_yn(), expr_extract_eq(), and NULL.
Referenced by expr_eliminate_dups2().
expr_fprint()
void expr_fprint (struct expr * e, FILE * out)
Definition at line 1086 of file expr.c.
 {
     expr_print(e, expr_print_file_helper, out, E_NONE);
 }
References E_NONE, expr_print(), expr_print_file_helper(), and out().
Referenced by expr_eq(), expr_join_and(), and expr_join_or().
expr_free()
void expr_free (struct expr * e)
Definition at line 104 of file expr.c.
 {
     if (!e)
         return;
     switch (e->type) {
     case E_SYMBOL:
         break;
     case E_NOT:
         expr_free(e->left.expr);
         return;
     case E_EQUAL:
     case E_UNEQUAL:
         break;
     case E_OR:
     case E_AND:
         expr_free(e->left.expr);
         expr_free(e->right.expr);
         break;
     default:
         printf("how to free type %d?\n", e->type);
         break;
     }
     free(e);
 }
References E_AND, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, free, printf, expr::right, and expr::type.
Referenced by __expr_eliminate_eq(), expr_eliminate_dups1(), expr_eliminate_dups2(), expr_eliminate_yn(), expr_eq(), expr_extract_eq(), and menu_finalize().
expr_gstr_print()
void expr_gstr_print (struct expr * e, struct gstr * gs)
Definition at line 1096 of file expr.c.
 {
     expr_print(e, expr_print_gstr_helper, gs, E_NONE);
 }
References E_NONE, expr_print(), and expr_print_gstr_helper().
Referenced by get_prompt_str(), and get_relations_str().
expr_join_and()
struct expr* expr_join_and (struct expr * e1, struct expr * e2)
Definition at line 414 of file expr.c.
 {
     struct expr *tmp;
     struct symbol *sym1, *sym2;
     if (expr_eq(e1, e2))
         return expr_copy(e1);
     if (e1->type != E_EQUAL && e1->type != E_UNEQUAL && e1->type != E_SYMBOL && e1->type != E_NOT)
         return NULL;
     if (e2->type != E_EQUAL && e2->type != E_UNEQUAL && e2->type != E_SYMBOL && e2->type != E_NOT)
         return NULL;
     if (e1->type == E_NOT) {
         tmp = e1->left.expr;
         if (tmp->type != E_EQUAL && tmp->type != E_UNEQUAL && tmp->type != E_SYMBOL)
             return NULL;
         sym1 = tmp->left.sym;
     } else
         sym1 = e1->left.sym;
     if (e2->type == E_NOT) {
         if (e2->left.expr->type != E_SYMBOL)
             return NULL;
         sym2 = e2->left.expr->left.sym;
     } else
         sym2 = e2->left.sym;
     if (sym1 != sym2)
         return NULL;
     if (sym1->type != S_BOOLEAN && sym1->type != S_TRISTATE)
         return NULL;
     if ((e1->type == E_SYMBOL && e2->type == E_EQUAL && e2->right.sym == &symbol_yes) ||
         (e2->type == E_SYMBOL && e1->type == E_EQUAL && e1->right.sym == &symbol_yes))
         // (a) && (a='y') -> (a='y')
         return expr_alloc_comp(E_EQUAL, sym1, &symbol_yes);
     if ((e1->type == E_SYMBOL && e2->type == E_UNEQUAL && e2->right.sym == &symbol_no) ||
         (e2->type == E_SYMBOL && e1->type == E_UNEQUAL && e1->right.sym == &symbol_no))
         // (a) && (a!='n') -> (a)
         return expr_alloc_symbol(sym1);
     if ((e1->type == E_SYMBOL && e2->type == E_UNEQUAL && e2->right.sym == &symbol_mod) ||
         (e2->type == E_SYMBOL && e1->type == E_UNEQUAL && e1->right.sym == &symbol_mod))
         // (a) && (a!='m') -> (a='y')
         return expr_alloc_comp(E_EQUAL, sym1, &symbol_yes);
     if (sym1->type == S_TRISTATE) {
         if (e1->type == E_EQUAL && e2->type == E_UNEQUAL) {
             // (a='b') && (a!='c') -> 'b'='c' ? 'n' : a='b'
             sym2 = e1->right.sym;
             if ((e2->right.sym->flags & SYMBOL_CONST) && (sym2->flags & SYMBOL_CONST))
                 return sym2 != e2->right.sym ? expr_alloc_comp(E_EQUAL, sym1, sym2)
                                  : expr_alloc_symbol(&symbol_no);
         }
         if (e1->type == E_UNEQUAL && e2->type == E_EQUAL) {
             // (a='b') && (a!='c') -> 'b'='c' ? 'n' : a='b'
             sym2 = e2->right.sym;
             if ((e1->right.sym->flags & SYMBOL_CONST) && (sym2->flags & SYMBOL_CONST))
                 return sym2 != e1->right.sym ? expr_alloc_comp(E_EQUAL, sym1, sym2)
                                  : expr_alloc_symbol(&symbol_no);
         }
         if (e1->type == E_UNEQUAL && e2->type == E_UNEQUAL &&
                ((e1->right.sym == &symbol_yes && e2->right.sym == &symbol_no) ||
                 (e1->right.sym == &symbol_no && e2->right.sym == &symbol_yes)))
             // (a!='y') && (a!='n') -> (a='m')
             return expr_alloc_comp(E_EQUAL, sym1, &symbol_mod);
         if (e1->type == E_UNEQUAL && e2->type == E_UNEQUAL &&
                ((e1->right.sym == &symbol_yes && e2->right.sym == &symbol_mod) ||
                 (e1->right.sym == &symbol_mod && e2->right.sym == &symbol_yes)))
             // (a!='y') && (a!='m') -> (a='n')
             return expr_alloc_comp(E_EQUAL, sym1, &symbol_no);
         if (e1->type == E_UNEQUAL && e2->type == E_UNEQUAL &&
                ((e1->right.sym == &symbol_mod && e2->right.sym == &symbol_no) ||
                 (e1->right.sym == &symbol_no && e2->right.sym == &symbol_mod)))
             // (a!='m') && (a!='n') -> (a='m')
             return expr_alloc_comp(E_EQUAL, sym1, &symbol_yes);
         if ((e1->type == E_SYMBOL && e2->type == E_EQUAL && e2->right.sym == &symbol_mod) ||
             (e2->type == E_SYMBOL && e1->type == E_EQUAL && e1->right.sym == &symbol_mod) ||
             (e1->type == E_SYMBOL && e2->type == E_UNEQUAL && e2->right.sym == &symbol_yes) ||
             (e2->type == E_SYMBOL && e1->type == E_UNEQUAL && e1->right.sym == &symbol_yes))
             return NULL;
     }
     if (DEBUG_EXPR) {
         printf("optimize (");
         expr_fprint(e1, stdout);
         printf(") && (");
         expr_fprint(e2, stdout);
         printf(")?\n");
     }
     return NULL;
 }
References DEBUG_EXPR, e1, e2, E_EQUAL, E_NOT, E_SYMBOL, E_UNEQUAL, expr_alloc_comp(), expr_alloc_symbol(), expr_copy(), expr_eq(), expr_fprint(), symbol::flags, NULL, printf, S_BOOLEAN, S_TRISTATE, stdout, SYMBOL_CONST, symbol_mod, symbol_no, symbol_yes, expr::type, and symbol::type.
Referenced by expr_eliminate_dups1().
expr_join_or()
struct expr* expr_join_or (struct expr * e1, struct expr * e2)
Definition at line 350 of file expr.c.
 {
     struct expr *tmp;
     struct symbol *sym1, *sym2;
     if (expr_eq(e1, e2))
         return expr_copy(e1);
     if (e1->type != E_EQUAL && e1->type != E_UNEQUAL && e1->type != E_SYMBOL && e1->type != E_NOT)
         return NULL;
     if (e2->type != E_EQUAL && e2->type != E_UNEQUAL && e2->type != E_SYMBOL && e2->type != E_NOT)
         return NULL;
     if (e1->type == E_NOT) {
         tmp = e1->left.expr;
         if (tmp->type != E_EQUAL && tmp->type != E_UNEQUAL && tmp->type != E_SYMBOL)
             return NULL;
         sym1 = tmp->left.sym;
     } else
         sym1 = e1->left.sym;
     if (e2->type == E_NOT) {
         if (e2->left.expr->type != E_SYMBOL)
             return NULL;
         sym2 = e2->left.expr->left.sym;
     } else
         sym2 = e2->left.sym;
     if (sym1 != sym2)
         return NULL;
     if (sym1->type != S_BOOLEAN && sym1->type != S_TRISTATE)
         return NULL;
     if (sym1->type == S_TRISTATE) {
         if (e1->type == E_EQUAL && e2->type == E_EQUAL &&
             ((e1->right.sym == &symbol_yes && e2->right.sym == &symbol_mod) ||
              (e1->right.sym == &symbol_mod && e2->right.sym == &symbol_yes))) {
             // (a='y') || (a='m') -> (a!='n')
             return expr_alloc_comp(E_UNEQUAL, sym1, &symbol_no);
         }
         if (e1->type == E_EQUAL && e2->type == E_EQUAL &&
             ((e1->right.sym == &symbol_yes && e2->right.sym == &symbol_no) ||
              (e1->right.sym == &symbol_no && e2->right.sym == &symbol_yes))) {
             // (a='y') || (a='n') -> (a!='m')
             return expr_alloc_comp(E_UNEQUAL, sym1, &symbol_mod);
         }
         if (e1->type == E_EQUAL && e2->type == E_EQUAL &&
             ((e1->right.sym == &symbol_mod && e2->right.sym == &symbol_no) ||
              (e1->right.sym == &symbol_no && e2->right.sym == &symbol_mod))) {
             // (a='m') || (a='n') -> (a!='y')
             return expr_alloc_comp(E_UNEQUAL, sym1, &symbol_yes);
         }
     }
     if (sym1->type == S_BOOLEAN && sym1 == sym2) {
         if ((e1->type == E_NOT && e1->left.expr->type == E_SYMBOL && e2->type == E_SYMBOL) ||
             (e2->type == E_NOT && e2->left.expr->type == E_SYMBOL && e1->type == E_SYMBOL))
             return expr_alloc_symbol(&symbol_yes);
     }
     if (DEBUG_EXPR) {
         printf("optimize (");
         expr_fprint(e1, stdout);
         printf(") || (");
         expr_fprint(e2, stdout);
         printf(")?\n");
     }
     return NULL;
 }
References DEBUG_EXPR, e1, e2, E_EQUAL, E_NOT, E_SYMBOL, E_UNEQUAL, expr_alloc_comp(), expr_alloc_symbol(), expr_copy(), expr_eq(), expr_fprint(), NULL, printf, S_BOOLEAN, S_TRISTATE, stdout, symbol_mod, symbol_no, symbol_yes, expr::type, and symbol::type.
Referenced by expr_eliminate_dups1().
expr_print()
void expr_print (struct expr * e, void(*)(void *, const char *) fn, void * data, int prevtoken)
Definition at line 1015 of file expr.c.
 {
     if (!e) {
         fn(data, "y");
         return;
     }
     if (expr_compare_type(prevtoken, e->type) > 0)
         fn(data, "(");
     switch (e->type) {
     case E_SYMBOL:
         if (e->left.sym->name)
             fn(data, e->left.sym->name);
         else
             fn(data, "<choice>");
         break;
     case E_NOT:
         fn(data, "!");
         expr_print(e->left.expr, fn, data, E_NOT);
         break;
     case E_EQUAL:
         fn(data, e->left.sym->name);
         fn(data, "=");
         fn(data, e->right.sym->name);
         break;
     case E_UNEQUAL:
         fn(data, e->left.sym->name);
         fn(data, "!=");
         fn(data, e->right.sym->name);
         break;
     case E_OR:
         expr_print(e->left.expr, fn, data, E_OR);
         fn(data, " || ");
         expr_print(e->right.expr, fn, data, E_OR);
         break;
     case E_AND:
         expr_print(e->left.expr, fn, data, E_AND);
         fn(data, " && ");
         expr_print(e->right.expr, fn, data, E_AND);
         break;
     case E_CHOICE:
         fn(data, e->right.sym->name);
         if (e->left.expr) {
             fn(data, " ^ ");
             expr_print(e->left.expr, fn, data, E_CHOICE);
         }
         break;
     case E_RANGE:
         fn(data, "[");
         fn(data, e->left.sym->name);
         fn(data, " ");
         fn(data, e->right.sym->name);
         fn(data, "]");
         break;
     default:
       {
         char buf[32];
         sprintf(buf, "<unknown type %d>", e->type);
         fn(data, buf);
         break;
       }
     }
     if (expr_compare_type(prevtoken, e->type) > 0)
         fn(data, ")");
 }
References buf, E_AND, E_CHOICE, E_EQUAL, E_NOT, E_OR, E_RANGE, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr_compare_type(), symbol::name, expr::right, sprintf(), expr_data::sym, and expr::type.
Referenced by expr_fprint(), expr_gstr_print(), and ConfigMainWindow::setHelp().
expr_print_file_helper()
static void expr_print_file_helper (void * data, const char * str) static
Definition at line 1081 of file expr.c.
 {
     fwrite(str, strlen(str), 1, data);
 }
References fwrite(), str, and strlen().
Referenced by expr_fprint().
expr_print_gstr_helper()
static void expr_print_gstr_helper (void * data, const char * str) static
Definition at line 1091 of file expr.c.
 {
     str_append((struct gstr*)data, str);
 }
References str, and str_append().
Referenced by expr_gstr_print().
expr_trans_bool()
struct expr* expr_trans_bool (struct expr * e)
Definition at line 321 of file expr.c.
 {
     if (!e)
         return NULL;
     switch (e->type) {
     case E_AND:
     case E_OR:
     case E_NOT:
         e->left.expr = expr_trans_bool(e->left.expr);
         e->right.expr = expr_trans_bool(e->right.expr);
         break;
     case E_UNEQUAL:
         // FOO!=n -> FOO
         if (e->left.sym->type == S_TRISTATE) {
             if (e->right.sym == &symbol_no) {
                 e->type = E_SYMBOL;
                 e->right.sym = NULL;
             }
         }
         break;
     default:
         ;
     }
     return e;
 }
References E_AND, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, NULL, expr::right, S_TRISTATE, expr_data::sym, symbol_no, and expr::type.
Referenced by menu_finalize().
expr_trans_compare()
struct expr* expr_trans_compare (struct expr * e, enum expr_type type, struct symbol * sym)
Definition at line 881 of file expr.c.
 {
     struct expr *e1, *e2;
     if (!e) {
         e = expr_alloc_symbol(sym);
         if (type == E_UNEQUAL)
             e = expr_alloc_one(E_NOT, e);
         return e;
     }
     switch (e->type) {
     case E_AND:
         e1 = expr_trans_compare(e->left.expr, E_EQUAL, sym);
         e2 = expr_trans_compare(e->right.expr, E_EQUAL, sym);
         if (sym == &symbol_yes)
             e = expr_alloc_two(E_AND, e1, e2);
         if (sym == &symbol_no)
             e = expr_alloc_two(E_OR, e1, e2);
         if (type == E_UNEQUAL)
             e = expr_alloc_one(E_NOT, e);
         return e;
     case E_OR:
         e1 = expr_trans_compare(e->left.expr, E_EQUAL, sym);
         e2 = expr_trans_compare(e->right.expr, E_EQUAL, sym);
         if (sym == &symbol_yes)
             e = expr_alloc_two(E_OR, e1, e2);
         if (sym == &symbol_no)
             e = expr_alloc_two(E_AND, e1, e2);
         if (type == E_UNEQUAL)
             e = expr_alloc_one(E_NOT, e);
         return e;
     case E_NOT:
         return expr_trans_compare(e->left.expr, type == E_EQUAL ? E_UNEQUAL : E_EQUAL, sym);
     case E_UNEQUAL:
     case E_EQUAL:
         if (type == E_EQUAL) {
             if (sym == &symbol_yes)
                 return expr_copy(e);
             if (sym == &symbol_mod)
                 return expr_alloc_symbol(&symbol_no);
             if (sym == &symbol_no)
                 return expr_alloc_one(E_NOT, expr_copy(e));
         } else {
             if (sym == &symbol_yes)
                 return expr_alloc_one(E_NOT, expr_copy(e));
             if (sym == &symbol_mod)
                 return expr_alloc_symbol(&symbol_yes);
             if (sym == &symbol_no)
                 return expr_copy(e);
         }
         break;
     case E_SYMBOL:
         return expr_alloc_comp(type, e->left.sym, sym);
     case E_CHOICE:
     case E_RANGE:
     case E_NONE:
         /* panic */;
     }
     return NULL;
 }
References e1, e2, E_AND, E_CHOICE, E_EQUAL, E_NONE, E_NOT, E_OR, E_RANGE, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr_alloc_comp(), expr_alloc_one(), expr_alloc_symbol(), expr_alloc_two(), expr_copy(), NULL, expr::right, symbol_mod, symbol_no, symbol_yes, type, and expr::type.
Referenced by menu_finalize().
expr_transform()
struct expr* expr_transform (struct expr * e)
Definition at line 640 of file expr.c.
 {
     struct expr *tmp;
     if (!e)
         return NULL;
     switch (e->type) {
     case E_EQUAL:
     case E_UNEQUAL:
     case E_SYMBOL:
     case E_CHOICE:
         break;
     default:
         e->left.expr = expr_transform(e->left.expr);
         e->right.expr = expr_transform(e->right.expr);
     }
     switch (e->type) {
     case E_EQUAL:
         if (e->left.sym->type != S_BOOLEAN)
             break;
         if (e->right.sym == &symbol_no) {
             e->type = E_NOT;
             e->left.expr = expr_alloc_symbol(e->left.sym);
             e->right.sym = NULL;
             break;
         }
         if (e->right.sym == &symbol_mod) {
             printf("boolean symbol %s tested for 'm'? test forced to 'n'\n", e->left.sym->name);
             e->type = E_SYMBOL;
             e->left.sym = &symbol_no;
             e->right.sym = NULL;
             break;
         }
         if (e->right.sym == &symbol_yes) {
             e->type = E_SYMBOL;
             e->right.sym = NULL;
             break;
         }
         break;
     case E_UNEQUAL:
         if (e->left.sym->type != S_BOOLEAN)
             break;
         if (e->right.sym == &symbol_no) {
             e->type = E_SYMBOL;
             e->right.sym = NULL;
             break;
         }
         if (e->right.sym == &symbol_mod) {
             printf("boolean symbol %s tested for 'm'? test forced to 'y'\n", e->left.sym->name);
             e->type = E_SYMBOL;
             e->left.sym = &symbol_yes;
             e->right.sym = NULL;
             break;
         }
         if (e->right.sym == &symbol_yes) {
             e->type = E_NOT;
             e->left.expr = expr_alloc_symbol(e->left.sym);
             e->right.sym = NULL;
             break;
         }
         break;
     case E_NOT:
         switch (e->left.expr->type) {
         case E_NOT:
             // !!a -> a
             tmp = e->left.expr->left.expr;
             free(e->left.expr);
             free(e);
             e = tmp;
             e = expr_transform(e);
             break;
         case E_EQUAL:
         case E_UNEQUAL:
             // !a='x' -> a!='x'
             tmp = e->left.expr;
             free(e);
             e = tmp;
             e->type = e->type == E_EQUAL ? E_UNEQUAL : E_EQUAL;
             break;
         case E_OR:
             // !(a || b) -> !a && !b
             tmp = e->left.expr;
             e->type = E_AND;
             e->right.expr = expr_alloc_one(E_NOT, tmp->right.expr);
             tmp->type = E_NOT;
             tmp->right.expr = NULL;
             e = expr_transform(e);
             break;
         case E_AND:
             // !(a && b) -> !a || !b
             tmp = e->left.expr;
             e->type = E_OR;
             e->right.expr = expr_alloc_one(E_NOT, tmp->right.expr);
             tmp->type = E_NOT;
             tmp->right.expr = NULL;
             e = expr_transform(e);
             break;
         case E_SYMBOL:
             if (e->left.expr->left.sym == &symbol_yes) {
                 // !'y' -> 'n'
                 tmp = e->left.expr;
                 free(e);
                 e = tmp;
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_no;
                 break;
             }
             if (e->left.expr->left.sym == &symbol_mod) {
                 // !'m' -> 'm'
                 tmp = e->left.expr;
                 free(e);
                 e = tmp;
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_mod;
                 break;
             }
             if (e->left.expr->left.sym == &symbol_no) {
                 // !'n' -> 'y'
                 tmp = e->left.expr;
                 free(e);
                 e = tmp;
                 e->type = E_SYMBOL;
                 e->left.sym = &symbol_yes;
                 break;
             }
             break;
         default:
             ;
         }
         break;
     default:
         ;
     }
     return e;
 }
References E_AND, E_CHOICE, E_EQUAL, E_NOT, E_OR, E_SYMBOL, E_UNEQUAL, expr_data::expr, expr_alloc_one(), expr_alloc_symbol(), free, NULL, printf, expr::right, S_BOOLEAN, expr_data::sym, symbol_mod, symbol_no, symbol_yes, and expr::type.
Referenced by expr_eliminate_dups2(), and menu_finalize().
Variable Documentation
trans_count
int trans_count static
Definition at line 130 of file expr.c.
Referenced by __expr_eliminate_eq(), expr_eliminate_dups(), expr_eliminate_dups1(), expr_eliminate_dups2(), and expr_eq().