Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/p_local.h File Reference
p_local.h File Reference
#include "r_local.h"
#include "p_spec.h"
Data Structures
struct divline_t
struct intercept_t
union intercept_t.d
Macros
#define FLOATSPEED (FRACUNIT*4)
#define MAXHEALTH 100
#define VIEWHEIGHT (41*FRACUNIT)
#define MAPBLOCKUNITS 128
#define MAPBLOCKSIZE (MAPBLOCKUNITS*FRACUNIT)
#define MAPBLOCKSHIFT (FRACBITS+7)
#define MAPBMASK (MAPBLOCKSIZE-1)
#define MAPBTOFRAC (MAPBLOCKSHIFT-FRACBITS)
#define PLAYERRADIUS 16*FRACUNIT
#define MAXRADIUS 32*FRACUNIT
#define GRAVITY FRACUNIT
#define MAXMOVE (30*FRACUNIT)
#define USERANGE (64*FRACUNIT)
#define MELEERANGE (64*FRACUNIT)
#define MISSILERANGE (32*64*FRACUNIT)
#define BASETHRESHOLD 100
#define ONFLOORZ (-__INT_MAX__ - 1)
#define ONCEILINGZ __INT_MAX__
#define ITEMQUESIZE 128
#define MAXINTERCEPTS_ORIGINAL 128
#define MAXINTERCEPTS (MAXINTERCEPTS_ORIGINAL + 61)
#define PT_ADDLINES 1
#define PT_ADDTHINGS 2
#define PT_EARLYOUT 4
#define MAXSPECIALCROSS 20
#define MAXSPECIALCROSS_ORIGINAL 8
Typedefs
typedef boolean(* traverser_t) (intercept_t *in)
Functions
void P_InitThinkers (void)
void P_AddThinker (thinker_t *thinker)
void P_RemoveThinker (thinker_t *thinker)
void P_SetupPsprites (player_t *curplayer)
void P_MovePsprites (player_t *curplayer)
void P_DropWeapon (player_t *player)
void P_PlayerThink (player_t *player)
void P_RespawnSpecials (void)
mobj_t * P_SpawnMobj (fixed_t x, fixed_t y, fixed_t z, mobjtype_t type)
void P_RemoveMobj (mobj_t *th)
mobj_t * P_SubstNullMobj (mobj_t *th)
boolean P_SetMobjState (mobj_t *mobj, statenum_t state)
void P_MobjThinker (mobj_t *mobj)
void P_SpawnPuff (fixed_t x, fixed_t y, fixed_t z)
void P_SpawnBlood (fixed_t x, fixed_t y, fixed_t z, int damage)
mobj_t * P_SpawnMissile (mobj_t *source, mobj_t *dest, mobjtype_t type)
void P_SpawnPlayerMissile (mobj_t *source, mobjtype_t type)
void P_NoiseAlert (mobj_t *target, mobj_t *emmiter)
fixed_t P_AproxDistance (fixed_t dx, fixed_t dy)
int P_PointOnLineSide (fixed_t x, fixed_t y, line_t *line)
int P_PointOnDivlineSide (fixed_t x, fixed_t y, divline_t *line)
void P_MakeDivline (line_t *li, divline_t *dl)
fixed_t P_InterceptVector (divline_t *v2, divline_t *v1)
int P_BoxOnLineSide (fixed_t *tmbox, line_t *ld)
void P_LineOpening (line_t *linedef)
boolean P_BlockLinesIterator (int x, int y, boolean(*func)(line_t *))
boolean P_BlockThingsIterator (int x, int y, boolean(*func)(mobj_t *))
boolean P_PathTraverse (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2, int flags, boolean(*trav)(intercept_t *))
void P_UnsetThingPosition (mobj_t *thing)
void P_SetThingPosition (mobj_t *thing)
boolean P_CheckPosition (mobj_t *thing, fixed_t x, fixed_t y)
boolean P_TryMove (mobj_t *thing, fixed_t x, fixed_t y)
boolean P_TeleportMove (mobj_t *thing, fixed_t x, fixed_t y)
void P_SlideMove (mobj_t *mo)
boolean P_CheckSight (mobj_t *t1, mobj_t *t2)
void P_UseLines (player_t *player)
boolean P_ChangeSector (sector_t *sector, boolean crunch)
fixed_t P_AimLineAttack (mobj_t *t1, angle_t angle, fixed_t distance)
void P_LineAttack (mobj_t *t1, angle_t angle, fixed_t distance, fixed_t slope, int damage)
void P_RadiusAttack (mobj_t *spot, mobj_t *source, int damage)
void P_TouchSpecialThing (mobj_t *special, mobj_t *toucher)
void P_DamageMobj (mobj_t *target, mobj_t *inflictor, mobj_t *source, int damage)
Variables
thinker_t thinkercap
mapthing_t itemrespawnque [ITEMQUESIZE]
int itemrespawntime [ITEMQUESIZE]
int iquehead
int iquetail
intercept_t intercepts [MAXINTERCEPTS]
intercept_t * intercept_p
fixed_t opentop
fixed_t openbottom
fixed_t openrange
fixed_t lowfloor
divline_t trace
boolean floatok
fixed_t tmfloorz
fixed_t tmceilingz
line_t * ceilingline
line_t * spechit [MAXSPECIALCROSS]
int numspechit
mobj_t * linetarget
byte * rejectmatrix
short * blockmaplump
short * blockmap
int bmapwidth
int bmapheight
fixed_t bmaporgx
fixed_t bmaporgy
mobj_t ** blocklinks
int maxammo [NUMAMMO]
int clipammo [NUMAMMO]
Data Structure Documentation
divline_t
struct divline_t
Definition at line 133 of file p_local.h.
Data Fields
fixed_t dx
fixed_t dy
fixed_t x
fixed_t y
intercept_t
struct intercept_t
Definition at line 142 of file p_local.h.
Data Fields
union intercept_t d
fixed_t frac
boolean isaline
intercept_t.d
union intercept_t.d
Definition at line 146 of file p_local.h.
Data Fields
line_t * line
mobj_t * thing
Macro Definition Documentation
BASETHRESHOLD
#define BASETHRESHOLD 100
Definition at line 58 of file p_local.h.
FLOATSPEED
#define FLOATSPEED (FRACUNIT*4)
Definition at line 27 of file p_local.h.
GRAVITY
#define GRAVITY FRACUNIT
Definition at line 50 of file p_local.h.
ITEMQUESIZE
#define ITEMQUESIZE 128
Definition at line 96 of file p_local.h.
MAPBLOCKSHIFT
#define MAPBLOCKSHIFT (FRACBITS+7)
Definition at line 37 of file p_local.h.
MAPBLOCKSIZE
#define MAPBLOCKSIZE (MAPBLOCKUNITS*FRACUNIT)
Definition at line 36 of file p_local.h.
MAPBLOCKUNITS
#define MAPBLOCKUNITS 128
Definition at line 35 of file p_local.h.
MAPBMASK
#define MAPBMASK (MAPBLOCKSIZE-1)
Definition at line 38 of file p_local.h.
MAPBTOFRAC
#define MAPBTOFRAC (MAPBLOCKSHIFT-FRACBITS)
Definition at line 39 of file p_local.h.
MAXHEALTH
#define MAXHEALTH 100
Definition at line 30 of file p_local.h.
MAXINTERCEPTS
#define MAXINTERCEPTS (MAXINTERCEPTS_ORIGINAL + 61)
Definition at line 155 of file p_local.h.
MAXINTERCEPTS_ORIGINAL
#define MAXINTERCEPTS_ORIGINAL 128
Definition at line 154 of file p_local.h.
MAXMOVE
#define MAXMOVE (30*FRACUNIT)
Definition at line 51 of file p_local.h.
MAXRADIUS
#define MAXRADIUS 32*FRACUNIT
Definition at line 48 of file p_local.h.
MAXSPECIALCROSS
#define MAXSPECIALCROSS 20
Definition at line 219 of file p_local.h.
MAXSPECIALCROSS_ORIGINAL
#define MAXSPECIALCROSS_ORIGINAL 8
Definition at line 220 of file p_local.h.
MELEERANGE
#define MELEERANGE (64*FRACUNIT)
Definition at line 54 of file p_local.h.
MISSILERANGE
#define MISSILERANGE (32*64*FRACUNIT)
Definition at line 55 of file p_local.h.
ONCEILINGZ
#define ONCEILINGZ __INT_MAX__
Definition at line 93 of file p_local.h.
ONFLOORZ
#define ONFLOORZ (-__INT_MAX__ - 1)
Definition at line 92 of file p_local.h.
PLAYERRADIUS
#define PLAYERRADIUS 16*FRACUNIT
Definition at line 43 of file p_local.h.
PT_ADDLINES
#define PT_ADDLINES 1
Definition at line 179 of file p_local.h.
PT_ADDTHINGS
#define PT_ADDTHINGS 2
Definition at line 180 of file p_local.h.
PT_EARLYOUT
#define PT_EARLYOUT 4
Definition at line 181 of file p_local.h.
USERANGE
#define USERANGE (64*FRACUNIT)
Definition at line 53 of file p_local.h.
VIEWHEIGHT
#define VIEWHEIGHT (41*FRACUNIT)
Definition at line 31 of file p_local.h.
Typedef Documentation
traverser_t
typedef boolean(* traverser_t) (intercept_t *in)
Definition at line 160 of file p_local.h.
Function Documentation
P_AddThinker()
void P_AddThinker (thinker_t * thinker)
Definition at line 58 of file p_tick.c.
 {
     thinkercap.prev->next = thinker;
     thinker->next = &thinkercap;
     thinker->prev = thinkercap.prev;
     thinkercap.prev = thinker;
 }
References thinker_s::next, thinker_s::prev, and thinkercap.
Referenced by EV_BuildStairs(), EV_DoCeiling(), EV_DoDonut(), EV_DoDoor(), EV_DoFloor(), EV_DoPlat(), EV_VerticalDoor(), P_SpawnDoorCloseIn30(), P_SpawnDoorRaiseIn5Mins(), P_SpawnFireFlicker(), P_SpawnGlowingLight(), P_SpawnLightFlash(), P_SpawnMobj(), P_SpawnStrobeFlash(), P_UnArchiveSpecials(), and P_UnArchiveThinkers().
P_AimLineAttack()
fixed_t P_AimLineAttack (mobj_t * t1, angle_t angle, fixed_t distance)
Definition at line 1068 of file p_map.c.
 {
     fixed_t x2;
     fixed_t y2;
     t1 = P_SubstNullMobj(t1);
     angle >>= ANGLETOFINESHIFT;
     shootthing = t1;
     x2 = t1->x + (distance>>FRACBITS)*finecosine[angle];
     y2 = t1->y + (distance>>FRACBITS)*finesine[angle];
     shootz = t1->z + (t1->height>>1) + 8*FRACUNIT;
     // can't shoot outside view angles
     topslope = 100*FRACUNIT/160;
     bottomslope = -100*FRACUNIT/160;
     attackrange = distance;
     linetarget = NULL;
     P_PathTraverse ( t1->x, t1->y,
              x2, y2,
              PT_ADDLINES|PT_ADDTHINGS,
              PTR_AimTraverse );
     if (linetarget)
     return aimslope;
     return 0;
 }
References aimslope, ANGLETOFINESHIFT, attackrange, bottomslope, finecosine, finesine, FRACBITS, FRACUNIT, linetarget, NULL, P_PathTraverse(), P_SubstNullMobj(), PT_ADDLINES, PT_ADDTHINGS, PTR_AimTraverse(), shootthing, shootz, t1, and topslope.
Referenced by A_BFGSpray(), A_CPosAttack(), A_PosAttack(), A_Punch(), A_Saw(), A_SPosAttack(), P_BulletSlope(), and P_SpawnPlayerMissile().
P_AproxDistance()
fixed_t P_AproxDistance (fixed_t dx, fixed_t dy)
Definition at line 44 of file p_maputl.c.
 {
     dx = abs(dx);
     dy = abs(dy);
     if (dx < dy)
     return dx+dy-(dx>>1);
     return dx+dy-(dy>>1);
 }
References abs().
Referenced by A_SkullAttack(), A_Tracer(), P_CheckMeleeRange(), P_CheckMissileRange(), P_HitSlideLine(), P_LookForPlayers(), P_SpawnMissile(), and P_ZMovement().
P_BlockLinesIterator()
boolean P_BlockLinesIterator (int x, int y, boolean(*)(line_t *) func)
Definition at line 467 of file p_maputl.c.
 {
     int         offset;
     short*      list;
     line_t*     ld;
     if (x<0
     || y<0
     || x>=bmapwidth
     || y>=bmapheight)
     {
     return true;
     }
     offset = y*bmapwidth+x;
     offset = *(blockmap+offset);
     for ( list = blockmaplump+offset ; *list != -1 ; list++)
     {
     ld = &lines[*list];
     if (ld->validcount == validcount)
         continue;   // line has already been checked
     ld->validcount = validcount;
     if ( !func(ld) )
         return false;
     }
     return true;    // everything was checked
 }
References blockmap, blockmaplump, bmapheight, bmapwidth, lines, line_s::validcount, validcount, x, and y.
Referenced by P_CheckPosition(), and P_PathTraverse().
P_BlockThingsIterator()
boolean P_BlockThingsIterator (int x, int y, boolean(*)(mobj_t *) func)
Definition at line 508 of file p_maputl.c.
 {
     mobj_t*     mobj;
     if ( x<0
      || y<0
      || x>=bmapwidth
      || y>=bmapheight)
     {
     return true;
     }
     for (mobj = blocklinks[y*bmapwidth+x] ;
      mobj ;
      mobj = mobj->bnext)
     {
     if (!func( mobj ) )
         return false;
     }
     return true;
 }
References blocklinks, bmapheight, bmapwidth, mobj_s::bnext, x, and y.
Referenced by A_VileChase(), P_ChangeSector(), P_CheckPosition(), P_PathTraverse(), P_RadiusAttack(), and P_TeleportMove().
P_BoxOnLineSide()
int P_BoxOnLineSide (fixed_t * tmbox, line_t * ld)
Definition at line 105 of file p_maputl.c.
 {
     int     p1 = 0;
     int     p2 = 0;
     switch (ld->slopetype)
     {
       case ST_HORIZONTAL:
     p1 = tmbox[BOXTOP] > ld->v1->y;
     p2 = tmbox[BOXBOTTOM] > ld->v1->y;
     if (ld->dx < 0)
     {
         p1 ^= 1;
         p2 ^= 1;
     }
     break;
       case ST_VERTICAL:
     p1 = tmbox[BOXRIGHT] < ld->v1->x;
     p2 = tmbox[BOXLEFT] < ld->v1->x;
     if (ld->dy < 0)
     {
         p1 ^= 1;
         p2 ^= 1;
     }
     break;
       case ST_POSITIVE:
     p1 = P_PointOnLineSide (tmbox[BOXLEFT], tmbox[BOXTOP], ld);
     p2 = P_PointOnLineSide (tmbox[BOXRIGHT], tmbox[BOXBOTTOM], ld);
     break;
       case ST_NEGATIVE:
     p1 = P_PointOnLineSide (tmbox[BOXRIGHT], tmbox[BOXTOP], ld);
     p2 = P_PointOnLineSide (tmbox[BOXLEFT], tmbox[BOXBOTTOM], ld);
     break;
     }
     if (p1 == p2)
     return p1;
     return -1;
 }
References BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, line_s::dx, line_s::dy, P_PointOnLineSide(), line_s::slopetype, ST_HORIZONTAL, ST_NEGATIVE, ST_POSITIVE, ST_VERTICAL, line_s::v1, vertex_t::x, and vertex_t::y.
Referenced by PIT_CheckLine().
P_ChangeSector()
boolean P_ChangeSector (sector_t * sector, boolean crunch)
Definition at line 1368 of file p_map.c.
 {
     int     x;
     int     y;
     nofit = false;
     crushchange = crunch;
     // re-check heights for all things near the moving sector
     for (x=sector->blockbox[BOXLEFT] ; x<= sector->blockbox[BOXRIGHT] ; x++)
     for (y=sector->blockbox[BOXBOTTOM];y<= sector->blockbox[BOXTOP] ; y++)
         P_BlockThingsIterator (x, y, PIT_ChangeSector);
     return nofit;
 }
References sector_t::blockbox, BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, crushchange, nofit, P_BlockThingsIterator(), PIT_ChangeSector(), x, and y.
Referenced by T_MovePlane().
P_CheckPosition()
boolean P_CheckPosition (mobj_t * thing, fixed_t x, fixed_t y)
Definition at line 402 of file p_map.c.
 {
     int         xl;
     int         xh;
     int         yl;
     int         yh;
     int         bx;
     int         by;
     subsector_t*    newsubsec;
     tmthing = thing;
     tmflags = thing->flags;
     tmx = x;
     tmy = y;
     tmbbox[BOXTOP] = y + tmthing->radius;
     tmbbox[BOXBOTTOM] = y - tmthing->radius;
     tmbbox[BOXRIGHT] = x + tmthing->radius;
     tmbbox[BOXLEFT] = x - tmthing->radius;
     newsubsec = R_PointInSubsector (x,y);
     ceilingline = NULL;
     // The base floor / ceiling is from the subsector
     // that contains the point.
     // Any contacted lines the step closer together
     // will adjust them.
     tmfloorz = tmdropoffz = newsubsec->sector->floorheight;
     tmceilingz = newsubsec->sector->ceilingheight;
     validcount++;
     numspechit = 0;
     if ( tmflags & MF_NOCLIP )
     return true;
     // Check things first, possibly picking things up.
     // The bounding box is extended by MAXRADIUS
     // because mobj_ts are grouped into mapblocks
     // based on their origin point, and can overlap
     // into adjacent blocks by up to MAXRADIUS units.
     xl = (tmbbox[BOXLEFT] - bmaporgx - MAXRADIUS)>>MAPBLOCKSHIFT;
     xh = (tmbbox[BOXRIGHT] - bmaporgx + MAXRADIUS)>>MAPBLOCKSHIFT;
     yl = (tmbbox[BOXBOTTOM] - bmaporgy - MAXRADIUS)>>MAPBLOCKSHIFT;
     yh = (tmbbox[BOXTOP] - bmaporgy + MAXRADIUS)>>MAPBLOCKSHIFT;
     for (bx=xl ; bx<=xh ; bx++)
     for (by=yl ; by<=yh ; by++)
         if (!P_BlockThingsIterator(bx,by,PIT_CheckThing))
         return false;
     // check lines
     xl = (tmbbox[BOXLEFT] - bmaporgx)>>MAPBLOCKSHIFT;
     xh = (tmbbox[BOXRIGHT] - bmaporgx)>>MAPBLOCKSHIFT;
     yl = (tmbbox[BOXBOTTOM] - bmaporgy)>>MAPBLOCKSHIFT;
     yh = (tmbbox[BOXTOP] - bmaporgy)>>MAPBLOCKSHIFT;
     for (bx=xl ; bx<=xh ; bx++)
     for (by=yl ; by<=yh ; by++)
         if (!P_BlockLinesIterator (bx,by,PIT_CheckLine))
         return false;
     return true;
 }
References bmaporgx, bmaporgy, BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, sector_t::ceilingheight, ceilingline, mobj_s::flags, sector_t::floorheight, MAPBLOCKSHIFT, MAXRADIUS, MF_NOCLIP, NULL, numspechit, P_BlockLinesIterator(), P_BlockThingsIterator(), PIT_CheckLine(), PIT_CheckThing(), R_PointInSubsector(), mobj_s::radius, subsector_s::sector, tmbbox, tmceilingz, tmdropoffz, tmflags, tmfloorz, tmthing, tmx, tmy, validcount, x, and y.
Referenced by G_CheckSpot(), P_NightmareRespawn(), P_ThingHeightClip(), P_TryMove(), and PIT_VileCheck().
P_CheckSight()
boolean P_CheckSight (mobj_t * t1, mobj_t * t2)
Definition at line 301 of file p_sight.c.
 {
     int     s1;
     int     s2;
     int     pnum;
     int     bytenum;
     int     bitnum;
     // First check for trivial rejection.
     // Determine subsector entries in REJECT table.
     s1 = (t1->subsector->sector - sectors);
     s2 = (t2->subsector->sector - sectors);
     pnum = s1*numsectors + s2;
     bytenum = pnum>>3;
     bitnum = 1 << (pnum&7);
     // Check in REJECT table.
     if (rejectmatrix[bytenum]&bitnum)
     {
     sightcounts[0]++;
     // can't possibly be connected
     return false;
     }
     // An unobstructed LOS is possible.
     // Now look from eyes of t1 to any part of t2.
     sightcounts[1]++;
     validcount++;
     sightzstart = t1->z + t1->height - (t1->height>>2);
     topslope = (t2->z+t2->height) - sightzstart;
     bottomslope = (t2->z) - sightzstart;
     strace.x = t1->x;
     strace.y = t1->y;
     t2x = t2->x;
     t2y = t2->y;
     strace.dx = t2->x - t1->x;
     strace.dy = t2->y - t1->y;
     // the head node is the last node output
     return P_CrossBSPNode (numnodes-1);
 }
References bottomslope, divline_t::dx, divline_t::dy, numnodes, numsectors, P_CrossBSPNode(), rejectmatrix, s1, s2, sectors, sightcounts, sightzstart, strace, t1, t2, t2x, t2y, topslope, validcount, divline_t::x, and divline_t::y.
Referenced by A_Chase(), A_CPosRefire(), A_Fire(), A_Look(), A_SpidRefire(), A_VileAttack(), P_CheckMeleeRange(), P_CheckMissileRange(), P_LookForPlayers(), and PIT_RadiusAttack().
P_DamageMobj()
void P_DamageMobj (mobj_t * target, mobj_t * inflictor, mobj_t * source, int damage)
Definition at line 779 of file p_inter.c.
 {
     unsigned    ang;
     int     saved;
     player_t*   player;
     fixed_t thrust;
     int     temp;
     if ( !(target->flags & MF_SHOOTABLE) )
     return; // shouldn't happen...
     if (target->health <= 0)
     return;
     if ( target->flags & MF_SKULLFLY )
     {
     target->momx = target->momy = target->momz = 0;
     }
     player = target->player;
     if (player && gameskill == sk_baby)
     damage >>= 1;   // take half damage in trainer mode
     // Some close combat weapons should not
     // inflict thrust and push the victim out of reach,
     // thus kick away unless using the chainsaw.
     if (inflictor
     && !(target->flags & MF_NOCLIP)
     && (!source
         || !source->player
         || source->player->readyweapon != wp_chainsaw))
     {
     ang = R_PointToAngle2 ( inflictor->x,
                 inflictor->y,
                 target->x,
                 target->y);
     thrust = damage*(FRACUNIT>>3)*100/target->info->mass;
     // make fall forwards sometimes
     if ( damage < 40
          && damage > target->health
          && target->z - inflictor->z > 64*FRACUNIT
          && (P_Random ()&1) )
     {
         ang += ANG180;
         thrust *= 4;
     }
     ang >>= ANGLETOFINESHIFT;
     target->momx += FixedMul (thrust, finecosine[ang]);
     target->momy += FixedMul (thrust, finesine[ang]);
     }
     // player specific
     if (player)
     {
     // end of game hell hack
     if (target->subsector->sector->special == 11
         && damage >= target->health)
     {
         damage = target->health - 1;
     }
     // Below certain threshold,
     // ignore damage in GOD mode, or with INVUL power.
     if ( damage < 1000
          && ( (player->cheats&CF_GODMODE)
           || player->powers[pw_invulnerability] ) )
     {
         return;
     }
     if (player->armortype)
     {
         if (player->armortype == 1)
         saved = damage/3;
         else
         saved = damage/2;
         if (player->armorpoints <= saved)
         {
         // armor is used up
         saved = player->armorpoints;
         player->armortype = 0;
         }
         player->armorpoints -= saved;
         damage -= saved;
     }
     player->health -= damage;   // mirror mobj health here for Dave
     if (player->health < 0)
         player->health = 0;
     player->attacker = source;
     player->damagecount += damage;  // add damage after armor / invuln
     if (player->damagecount > 100)
         player->damagecount = 100;  // teleport stomp does 10k points...
     temp = damage < 100 ? damage : 100;
     if (player == &players[consoleplayer])
         I_Tactile (40,10,40+temp*2);
     }
     // do the damage
     target->health -= damage;
     if (target->health <= 0)
     {
     P_KillMobj (source, target);
     return;
     }
     if ( (P_Random () < target->info->painchance)
      && !(target->flags&MF_SKULLFLY) )
     {
     target->flags |= MF_JUSTHIT;    // fight back!
     P_SetMobjState (target, target->info->painstate);
     }
     target->reactiontime = 0;       // we're awake now...
     if ( (!target->threshold || target->type == MT_VILE)
      && source && source != target
      && source->type != MT_VILE)
     {
     // if not intent on another player,
     // chase after this one
     target->target = source;
     target->threshold = BASETHRESHOLD;
     if (target->state == &states[target->info->spawnstate]
         && target->info->seestate != S_NULL)
         P_SetMobjState (target, target->info->seestate);
     }
 }
References ANG180, ANGLETOFINESHIFT, player_s::armorpoints, player_s::armortype, player_s::attacker, BASETHRESHOLD, CF_GODMODE, player_s::cheats, consoleplayer, player_s::damagecount, finecosine, finesine, FixedMul(), mobj_s::flags, FRACUNIT, gameskill, player_s::health, mobj_s::health, I_Tactile(), mobj_s::info, mobjinfo_t::mass, MF_JUSTHIT, MF_NOCLIP, MF_SHOOTABLE, MF_SKULLFLY, mobj_s::momx, mobj_s::momy, mobj_s::momz, MT_VILE, P_KillMobj(), P_Random(), P_SetMobjState(), mobjinfo_t::painchance, mobjinfo_t::painstate, mobj_s::player, players, player_s::powers, pw_invulnerability, R_PointToAngle2(), mobj_s::reactiontime, player_s::readyweapon, S_NULL, subsector_s::sector, mobjinfo_t::seestate, sk_baby, mobjinfo_t::spawnstate, sector_t::special, mobj_s::state, states, mobj_s::subsector, mobj_s::target, mobj_s::threshold, mobj_s::type, wp_chainsaw, mobj_s::x, mobj_s::y, and mobj_s::z.
Referenced by A_BFGSpray(), A_BruisAttack(), A_HeadAttack(), A_PainShootSkull(), A_SargAttack(), A_SkelFist(), A_TroopAttack(), A_VileAttack(), P_PlayerInSpecialSector(), PIT_ChangeSector(), PIT_CheckThing(), PIT_RadiusAttack(), PIT_StompThing(), and PTR_ShootTraverse().
P_DropWeapon()
void P_DropWeapon (player_t * player)
Definition at line 256 of file p_pspr.c.
 {
     P_SetPsprite (player,
           ps_weapon,
           weaponinfo[player->readyweapon].downstate);
 }
References weaponinfo_t::downstate, P_SetPsprite(), ps_weapon, player_s::readyweapon, and weaponinfo.
Referenced by P_KillMobj().
P_InitThinkers()
void P_InitThinkers (void)
Definition at line 46 of file p_tick.c.
 {
     thinkercap.prev = thinkercap.next  = &thinkercap;
 }
References thinker_s::next, thinker_s::prev, and thinkercap.
Referenced by P_SetupLevel(), and P_UnArchiveThinkers().
P_InterceptVector()
fixed_t P_InterceptVector (divline_t * v2, divline_t * v1)
Definition at line 226 of file p_maputl.c.
 {
 #if 1
     fixed_t frac;
     fixed_t num;
     fixed_t den;
     den = FixedMul (v1->dy>>8,v2->dx) - FixedMul(v1->dx>>8,v2->dy);
     if (den == 0)
     return 0;
     //  I_Error ("P_InterceptVector: parallel");
     num =
     FixedMul ( (v1->x - v2->x)>>8 ,v1->dy )
     +FixedMul ( (v2->y - v1->y)>>8, v1->dx );
     frac = FixedDiv (num , den);
     return frac;
 #else   // UNUSED, float debug.
     float   frac;
     float   num;
     float   den;
     float   v1x;
     float   v1y;
     float   v1dx;
     float   v1dy;
     float   v2x;
     float   v2y;
     float   v2dx;
     float   v2dy;
     v1x = (float)v1->x/FRACUNIT;
     v1y = (float)v1->y/FRACUNIT;
     v1dx = (float)v1->dx/FRACUNIT;
     v1dy = (float)v1->dy/FRACUNIT;
     v2x = (float)v2->x/FRACUNIT;
     v2y = (float)v2->y/FRACUNIT;
     v2dx = (float)v2->dx/FRACUNIT;
     v2dy = (float)v2->dy/FRACUNIT;
     den = v1dy*v2dx - v1dx*v2dy;
     if (den == 0)
     return 0;   // parallel
     num = (v1x - v2x)*v1dy + (v2y - v1y)*v1dx;
     frac = num / den;
     return frac*FRACUNIT;
 #endif
 }
References FixedDiv(), FixedMul(), FRACUNIT, num, v1, and v2.
Referenced by PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
P_LineAttack()
void P_LineAttack (mobj_t * t1, angle_t angle, fixed_t distance, fixed_t slope, int damage)
Definition at line 1110 of file p_map.c.
 {
     fixed_t x2;
     fixed_t y2;
     angle >>= ANGLETOFINESHIFT;
     shootthing = t1;
     la_damage = damage;
     x2 = t1->x + (distance>>FRACBITS)*finecosine[angle];
     y2 = t1->y + (distance>>FRACBITS)*finesine[angle];
     shootz = t1->z + (t1->height>>1) + 8*FRACUNIT;
     attackrange = distance;
     aimslope = slope;
     P_PathTraverse ( t1->x, t1->y,
              x2, y2,
              PT_ADDLINES|PT_ADDTHINGS,
              PTR_ShootTraverse );
 }
References aimslope, ANGLETOFINESHIFT, attackrange, finecosine, finesine, FRACBITS, FRACUNIT, la_damage, P_PathTraverse(), PT_ADDLINES, PT_ADDTHINGS, PTR_ShootTraverse(), shootthing, shootz, and t1.
Referenced by A_CPosAttack(), A_FireShotgun2(), A_PosAttack(), A_Punch(), A_Saw(), A_SPosAttack(), and P_GunShot().
P_LineOpening()
void P_LineOpening (line_t * linedef)
Definition at line 295 of file p_maputl.c.
 {
     sector_t*   front;
     sector_t*   back;
     if (linedef->sidenum[1] == -1)
     {
     // single sided line
     openrange = 0;
     return;
     }
     front = linedef->frontsector;
     back = linedef->backsector;
     if (front->ceilingheight < back->ceilingheight)
     opentop = front->ceilingheight;
     else
     opentop = back->ceilingheight;
     if (front->floorheight > back->floorheight)
     {
     openbottom = front->floorheight;
     lowfloor = back->floorheight;
     }
     else
     {
     openbottom = back->floorheight;
     lowfloor = front->floorheight;
     }
     openrange = opentop - openbottom;
 }
References line_s::backsector, sector_t::ceilingheight, sector_t::floorheight, line_s::frontsector, linedef, lowfloor, openbottom, openrange, opentop, and line_s::sidenum.
Referenced by P_RecursiveSound(), PIT_CheckLine(), PTR_AimTraverse(), PTR_ShootTraverse(), PTR_SlideTraverse(), and PTR_UseTraverse().
P_MakeDivline()
void P_MakeDivline (line_t * li, divline_t * dl)
Definition at line 206 of file p_maputl.c.
 {
     dl->x = li->v1->x;
     dl->y = li->v1->y;
     dl->dx = li->dx;
     dl->dy = li->dy;
 }
References divline_t::dx, line_s::dx, divline_t::dy, line_s::dy, line_s::v1, divline_t::x, vertex_t::x, divline_t::y, and vertex_t::y.
Referenced by PIT_AddLineIntercepts().
P_MobjThinker()
void P_MobjThinker (mobj_t * mobj)
Definition at line 441 of file p_mobj.c.
 {
     // momentum movement
     if (mobj->momx
     || mobj->momy
     || (mobj->flags&MF_SKULLFLY) )
     {
     P_XYMovement (mobj);
     // FIXME: decent NOP/NULL/Nil function pointer please.
     if (mobj->thinker.function.acv == (actionf_v) (-1))
         return;     // mobj was removed
     }
     if ( (mobj->z != mobj->floorz)
      || mobj->momz )
     {
     P_ZMovement (mobj);
     // FIXME: decent NOP/NULL/Nil function pointer please.
     if (mobj->thinker.function.acv == (actionf_v) (-1))
         return;     // mobj was removed
     }
     // cycle through states,
     // calling action functions at transitions
     if (mobj->tics != -1)
     {
     mobj->tics--;
     // you can cycle through multiple states in a tic
     if (!mobj->tics)
         if (!P_SetMobjState (mobj, mobj->state->nextstate) )
         return;     // freed itself
     }
     else
     {
     // check for nightmare respawn
     if (! (mobj->flags & MF_COUNTKILL) )
         return;
     if (!respawnmonsters)
         return;
     mobj->movecount++;
     if (mobj->movecount < 12*TICRATE)
         return;
     if ( leveltime&31 )
         return;
     if (P_Random () > 4)
         return;
     P_NightmareRespawn (mobj);
     }
 }
References actionf_t::acv, mobj_s::flags, mobj_s::floorz, thinker_s::function, leveltime, MF_COUNTKILL, MF_SKULLFLY, mobj_s::momx, mobj_s::momy, mobj_s::momz, mobj_s::movecount, state_t::nextstate, P_NightmareRespawn(), P_Random(), P_SetMobjState(), P_XYMovement(), P_ZMovement(), respawnmonsters, mobj_s::state, mobj_s::thinker, TICRATE, mobj_s::tics, and mobj_s::z.
Referenced by A_BossDeath(), A_BrainAwake(), A_KeenDie(), A_PainShootSkull(), EV_Teleport(), P_ArchiveThinkers(), P_SpawnMobj(), P_UnArchiveThinkers(), and R_PrecacheLevel().
P_MovePsprites()
void P_MovePsprites (player_t * curplayer)
Definition at line 860 of file p_pspr.c.
 {
     int     i;
     pspdef_t*   psp;
     state_t*    state;
     psp = &player->psprites[0];
     for (i=0 ; i<NUMPSPRITES ; i++, psp++)
     {
     // a null state means not active
     if ( (state = psp->state) )
     {
         // drop tic count and possibly change state
         // a -1 tic count never changes
         if (psp->tics != -1)
         {
         psp->tics--;
         if (!psp->tics)
             P_SetPsprite (player, i, psp->state->nextstate);
         }
     }
     }
     player->psprites[ps_flash].sx = player->psprites[ps_weapon].sx;
     player->psprites[ps_flash].sy = player->psprites[ps_weapon].sy;
 }
References i, state_t::nextstate, NUMPSPRITES, P_SetPsprite(), ps_flash, ps_weapon, player_s::psprites, pspdef_t::state, state, pspdef_t::sx, pspdef_t::sy, and pspdef_t::tics.
Referenced by P_DeathThink(), and P_PlayerThink().
P_NoiseAlert()
void P_NoiseAlert (mobj_t * target, mobj_t * emmiter)
Definition at line 152 of file p_enemy.c.
 {
     soundtarget = target;
     validcount++;
     P_RecursiveSound (emmiter->subsector->sector, 0);
 }
References P_RecursiveSound(), subsector_s::sector, soundtarget, mobj_s::subsector, and validcount.
Referenced by P_FireWeapon().
P_PathTraverse()
boolean P_PathTraverse (fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2, int flags, boolean(*)(intercept_t *) trav)
Definition at line 861 of file p_maputl.c.
 {
     fixed_t xt1;
     fixed_t yt1;
     fixed_t xt2;
     fixed_t yt2;
     fixed_t xstep;
     fixed_t ystep;
     fixed_t partial;
     fixed_t xintercept;
     fixed_t yintercept;
     int     mapx;
     int     mapy;
     int     mapxstep;
     int     mapystep;
     int     count;
     earlyout = flags & PT_EARLYOUT;
     validcount++;
     intercept_p = intercepts;
     if ( ((x1-bmaporgx)&(MAPBLOCKSIZE-1)) == 0)
     x1 += FRACUNIT; // don't side exactly on a line
     if ( ((y1-bmaporgy)&(MAPBLOCKSIZE-1)) == 0)
     y1 += FRACUNIT; // don't side exactly on a line
     trace.x = x1;
     trace.y = y1;
     trace.dx = x2 - x1;
     trace.dy = y2 - y1;
     x1 -= bmaporgx;
     y1 -= bmaporgy;
     xt1 = x1>>MAPBLOCKSHIFT;
     yt1 = y1>>MAPBLOCKSHIFT;
     x2 -= bmaporgx;
     y2 -= bmaporgy;
     xt2 = x2>>MAPBLOCKSHIFT;
     yt2 = y2>>MAPBLOCKSHIFT;
     if (xt2 > xt1)
     {
     mapxstep = 1;
     partial = FRACUNIT - ((x1>>MAPBTOFRAC)&(FRACUNIT-1));
     ystep = FixedDiv (y2-y1,abs(x2-x1));
     }
     else if (xt2 < xt1)
     {
     mapxstep = -1;
     partial = (x1>>MAPBTOFRAC)&(FRACUNIT-1);
     ystep = FixedDiv (y2-y1,abs(x2-x1));
     }
     else
     {
     mapxstep = 0;
     partial = FRACUNIT;
     ystep = 256*FRACUNIT;
     }
     yintercept = (y1>>MAPBTOFRAC) + FixedMul (partial, ystep);
     if (yt2 > yt1)
     {
     mapystep = 1;
     partial = FRACUNIT - ((y1>>MAPBTOFRAC)&(FRACUNIT-1));
     xstep = FixedDiv (x2-x1,abs(y2-y1));
     }
     else if (yt2 < yt1)
     {
     mapystep = -1;
     partial = (y1>>MAPBTOFRAC)&(FRACUNIT-1);
     xstep = FixedDiv (x2-x1,abs(y2-y1));
     }
     else
     {
     mapystep = 0;
     partial = FRACUNIT;
     xstep = 256*FRACUNIT;
     }
     xintercept = (x1>>MAPBTOFRAC) + FixedMul (partial, xstep);
     // Step through map blocks.
     // Count is present to prevent a round off error
     // from skipping the break.
     mapx = xt1;
     mapy = yt1;
     for (count = 0 ; count < 64 ; count++)
     {
     if (flags & PT_ADDLINES)
     {
         if (!P_BlockLinesIterator (mapx, mapy,PIT_AddLineIntercepts))
         return false;   // early out
     }
     if (flags & PT_ADDTHINGS)
     {
         if (!P_BlockThingsIterator (mapx, mapy,PIT_AddThingIntercepts))
         return false;   // early out
     }
     if (mapx == xt2
         && mapy == yt2)
     {
         break;
     }
     if ( (yintercept >> FRACBITS) == mapy)
     {
         yintercept += ystep;
         mapx += mapxstep;
     }
     else if ( (xintercept >> FRACBITS) == mapx)
     {
         xintercept += xstep;
         mapy += mapystep;
     }
     }
     // go through the sorted list
     return P_TraverseIntercepts ( trav, FRACUNIT );
 }
References abs(), bmaporgx, bmaporgy, count, divline_t::dx, divline_t::dy, earlyout, FixedDiv(), FixedMul(), FRACBITS, FRACUNIT, intercept_p, intercepts, MAPBLOCKSHIFT, MAPBLOCKSIZE, MAPBTOFRAC, P_BlockLinesIterator(), P_BlockThingsIterator(), P_TraverseIntercepts(), PIT_AddLineIntercepts(), PIT_AddThingIntercepts(), PT_ADDLINES, PT_ADDTHINGS, PT_EARLYOUT, trace, validcount, divline_t::x, divline_t::y, and y1().
Referenced by P_AimLineAttack(), P_LineAttack(), P_SlideMove(), and P_UseLines().
P_PlayerThink()
void P_PlayerThink (player_t * player)
Definition at line 229 of file p_user.c.
 {
     ticcmd_t*       cmd;
     weapontype_t    newweapon;
     // fixme: do this in the cheat code
     if (player->cheats & CF_NOCLIP)
     player->mo->flags |= MF_NOCLIP;
     else
     player->mo->flags &= ~MF_NOCLIP;
     // chain saw run forward
     cmd = &player->cmd;
     if (player->mo->flags & MF_JUSTATTACKED)
     {
     cmd->angleturn = 0;
     cmd->forwardmove = 0xc800/512;
     cmd->sidemove = 0;
     player->mo->flags &= ~MF_JUSTATTACKED;
     }
     if (player->playerstate == PST_DEAD)
     {
     P_DeathThink (player);
     return;
     }
     // Move around.
     // Reactiontime is used to prevent movement
     //  for a bit after a teleport.
     if (player->mo->reactiontime)
     player->mo->reactiontime--;
     else
     P_MovePlayer (player);
     P_CalcHeight (player);
     if (player->mo->subsector->sector->special)
     P_PlayerInSpecialSector (player);
     // Check for weapon change.
     // A special event has no other buttons.
     if (cmd->buttons & BT_SPECIAL)
     cmd->buttons = 0;
     if (cmd->buttons & BT_CHANGE)
     {
     // The actual changing of the weapon is done
     //  when the weapon psprite can do it
     //  (read: not in the middle of an attack).
     newweapon = (cmd->buttons&BT_WEAPONMASK)>>BT_WEAPONSHIFT;
     if (newweapon == wp_fist
         && player->weaponowned[wp_chainsaw]
         && !(player->readyweapon == wp_chainsaw
          && player->powers[pw_strength]))
     {
         newweapon = wp_chainsaw;
     }
     if ( (gamemode == commercial)
         && newweapon == wp_shotgun
         && player->weaponowned[wp_supershotgun]
         && player->readyweapon != wp_supershotgun)
     {
         newweapon = wp_supershotgun;
     }
     if (player->weaponowned[newweapon]
         && newweapon != player->readyweapon)
     {
         // Do not go to plasma or BFG in shareware,
         //  even if cheated.
         if ((newweapon != wp_plasma
          && newweapon != wp_bfg)
         || (gamemode != shareware) )
         {
         player->pendingweapon = newweapon;
         }
     }
     }
     // check for use
     if (cmd->buttons & BT_USE)
     {
     if (!player->usedown)
     {
         P_UseLines (player);
         player->usedown = true;
     }
     }
     else
     player->usedown = false;
     // cycle psprites
     P_MovePsprites (player);
     // Counters, time dependend power ups.
     // Strength counts up to diminish fade.
     if (player->powers[pw_strength])
     player->powers[pw_strength]++;
     if (player->powers[pw_invulnerability])
     player->powers[pw_invulnerability]--;
     if (player->powers[pw_invisibility])
     if (! --player->powers[pw_invisibility] )
         player->mo->flags &= ~MF_SHADOW;
     if (player->powers[pw_infrared])
     player->powers[pw_infrared]--;
     if (player->powers[pw_ironfeet])
     player->powers[pw_ironfeet]--;
     if (player->damagecount)
     player->damagecount--;
     if (player->bonuscount)
     player->bonuscount--;
     // Handling colormaps.
     if (player->powers[pw_invulnerability])
     {
     if (player->powers[pw_invulnerability] > 4*32
         || (player->powers[pw_invulnerability]&8) )
         player->fixedcolormap = INVERSECOLORMAP;
     else
         player->fixedcolormap = 0;
     }
     else if (player->powers[pw_infrared])
     {
     if (player->powers[pw_infrared] > 4*32
         || (player->powers[pw_infrared]&8) )
     {
         // almost full bright
         player->fixedcolormap = 1;
     }
     else
         player->fixedcolormap = 0;
     }
     else
     player->fixedcolormap = 0;
 }
References ticcmd_t::angleturn, player_s::bonuscount, BT_CHANGE, BT_SPECIAL, BT_USE, BT_WEAPONMASK, BT_WEAPONSHIFT, ticcmd_t::buttons, CF_NOCLIP, player_s::cheats, player_s::cmd, commercial, player_s::damagecount, player_s::fixedcolormap, mobj_s::flags, ticcmd_t::forwardmove, gamemode, INVERSECOLORMAP, MF_JUSTATTACKED, MF_NOCLIP, MF_SHADOW, player_s::mo, P_CalcHeight(), P_DeathThink(), P_MovePlayer(), P_MovePsprites(), P_PlayerInSpecialSector(), P_UseLines(), player_s::pendingweapon, player_s::playerstate, player_s::powers, PST_DEAD, pw_infrared, pw_invisibility, pw_invulnerability, pw_ironfeet, pw_strength, mobj_s::reactiontime, player_s::readyweapon, subsector_s::sector, shareware, ticcmd_t::sidemove, sector_t::special, mobj_s::subsector, player_s::usedown, player_s::weaponowned, wp_bfg, wp_chainsaw, wp_fist, wp_plasma, wp_shotgun, and wp_supershotgun.
Referenced by P_Ticker().
P_PointOnDivlineSide()
int P_PointOnDivlineSide (fixed_t x, fixed_t y, divline_t * line)
Definition at line 156 of file p_maputl.c.
 {
     fixed_t dx;
     fixed_t dy;
     fixed_t left;
     fixed_t right;
     if (!line->dx)
     {
     if (x <= line->x)
         return line->dy > 0;
     return line->dy < 0;
     }
     if (!line->dy)
     {
     if (y <= line->y)
         return line->dx < 0;
     return line->dx > 0;
     }
     dx = (x - line->x);
     dy = (y - line->y);
     // try to quickly decide by looking at sign bits
     if ( (line->dy ^ line->dx ^ dx ^ dy)&0x80000000 )
     {
     if ( (line->dy ^ dx) & 0x80000000 )
         return 1;       // (left is negative)
     return 0;
     }
     left = FixedMul ( line->dy>>8, dx>>8 );
     right = FixedMul ( dy>>8 , line->dx>>8 );
     if (right < left)
     return 0;       // front side
     return 1;           // back side
 }
References FixedMul(), line, x, and y.
Referenced by PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
P_PointOnLineSide()
int P_PointOnLineSide (fixed_t x, fixed_t y, line_t * line)
Definition at line 61 of file p_maputl.c.
 {
     fixed_t dx;
     fixed_t dy;
     fixed_t left;
     fixed_t right;
     if (!line->dx)
     {
     if (x <= line->v1->x)
         return line->dy > 0;
     return line->dy < 0;
     }
     if (!line->dy)
     {
     if (y <= line->v1->y)
         return line->dx < 0;
     return line->dx > 0;
     }
     dx = (x - line->v1->x);
     dy = (y - line->v1->y);
     left = FixedMul ( line->dy>>FRACBITS , dx );
     right = FixedMul ( dy , line->dx>>FRACBITS );
     if (right < left)
     return 0;       // front side
     return 1;           // back side
 }
References FixedMul(), FRACBITS, line, v1, x, and y.
Referenced by P_BoxOnLineSide(), P_HitSlideLine(), P_TryMove(), PIT_AddLineIntercepts(), PTR_SlideTraverse(), and PTR_UseTraverse().
P_RadiusAttack()
void P_RadiusAttack (mobj_t * spot, mobj_t * source, int damage)
Definition at line 1253 of file p_map.c.
 {
     int     x;
     int     y;
     int     xl;
     int     xh;
     int     yl;
     int     yh;
     fixed_t dist;
     dist = (damage+MAXRADIUS)<<FRACBITS;
     yh = (spot->y + dist - bmaporgy)>>MAPBLOCKSHIFT;
     yl = (spot->y - dist - bmaporgy)>>MAPBLOCKSHIFT;
     xh = (spot->x + dist - bmaporgx)>>MAPBLOCKSHIFT;
     xl = (spot->x - dist - bmaporgx)>>MAPBLOCKSHIFT;
     bombspot = spot;
     bombsource = source;
     bombdamage = damage;
     for (y=yl ; y<=yh ; y++)
     for (x=xl ; x<=xh ; x++)
         P_BlockThingsIterator (x, y, PIT_RadiusAttack );
 }
References bmaporgx, bmaporgy, bombdamage, bombsource, bombspot, FRACBITS, MAPBLOCKSHIFT, MAXRADIUS, P_BlockThingsIterator(), PIT_RadiusAttack(), mobj_s::x, x, y, and mobj_s::y.
Referenced by A_Explode(), and A_VileAttack().
P_RemoveMobj()
void P_RemoveMobj (mobj_t * th)
Definition at line 572 of file p_mobj.c.
 {
     if ((mobj->flags & MF_SPECIAL)
     && !(mobj->flags & MF_DROPPED)
     && (mobj->type != MT_INV)
     && (mobj->type != MT_INS))
     {
     itemrespawnque[iquehead] = mobj->spawnpoint;
     itemrespawntime[iquehead] = leveltime;
     iquehead = (iquehead+1)&(ITEMQUESIZE-1);
     // lose one off the end?
     if (iquehead == iquetail)
         iquetail = (iquetail+1)&(ITEMQUESIZE-1);
     }
     // unlink from sector and block lists
     P_UnsetThingPosition (mobj);
     // stop any playing sound
     S_StopSound (mobj);
     // free block
     P_RemoveThinker ((thinker_t*)mobj);
 }
References mobj_s::flags, iquehead, iquetail, ITEMQUESIZE, itemrespawnque, itemrespawntime, leveltime, MF_DROPPED, MF_SPECIAL, MT_INS, MT_INV, P_RemoveThinker(), P_UnsetThingPosition(), S_StopSound(), mobj_s::spawnpoint, and mobj_s::type.
Referenced by A_SpawnFly(), G_CheckSpot(), P_NightmareRespawn(), P_SetMobjState(), P_TouchSpecialThing(), P_UnArchiveThinkers(), P_XYMovement(), and PIT_ChangeSector().
P_RemoveThinker()
void P_RemoveThinker (thinker_t * thinker)
Definition at line 73 of file p_tick.c.
 {
   // FIXME: NOP.
   thinker->function.acv = (actionf_v)(-1);
 }
References actionf_t::acv, and thinker_s::function.
Referenced by P_RemoveActiveCeiling(), P_RemoveActivePlat(), P_RemoveMobj(), T_MoveFloor(), and T_VerticalDoor().
P_RespawnSpecials()
void P_RespawnSpecials (void)
Definition at line 604 of file p_mobj.c.
 {
     fixed_t     x;
     fixed_t     y;
     fixed_t     z;
     subsector_t*    ss;
     mobj_t*     mo;
     mapthing_t*     mthing;
     int         i;
     // only respawn items in deathmatch
     if (deathmatch != 2)
     return; //
     // nothing left to respawn?
     if (iquehead == iquetail)
     return;
     // wait at least 30 seconds
     if (leveltime - itemrespawntime[iquetail] < 30*TICRATE)
     return;
     mthing = &itemrespawnque[iquetail];
     x = mthing->x << FRACBITS;
     y = mthing->y << FRACBITS;
     // spawn a teleport fog at the new spot
     ss = R_PointInSubsector (x,y);
     mo = P_SpawnMobj (x, y, ss->sector->floorheight , MT_IFOG);
     S_StartSound (mo, sfx_itmbk);
     // find which type to spawn
     for (i=0 ; i< NUMMOBJTYPES ; i++)
     {
     if (mthing->type == mobjinfo[i].doomednum)
         break;
     }
     // spawn it
     if (mobjinfo[i].flags & MF_SPAWNCEILING)
     z = ONCEILINGZ;
     else
     z = ONFLOORZ;
     mo = P_SpawnMobj (x,y,z, i);
     mo->spawnpoint = *mthing;
     mo->angle = ANG45 * (mthing->angle/45);
     // pull it from the que
     iquetail = (iquetail+1)&(ITEMQUESIZE-1);
 }
References ANG45, mobj_s::angle, deathmatch, mobjinfo_t::doomednum, sector_t::floorheight, FRACBITS, i, iquehead, iquetail, ITEMQUESIZE, itemrespawnque, itemrespawntime, leveltime, MF_SPAWNCEILING, mobjinfo, MT_IFOG, NUMMOBJTYPES, ONCEILINGZ, ONFLOORZ, P_SpawnMobj(), R_PointInSubsector(), S_StartSound(), subsector_s::sector, sfx_itmbk, mobj_s::spawnpoint, TICRATE, x, and y.
Referenced by P_Ticker().
P_SetMobjState()
boolean P_SetMobjState (mobj_t * mobj, statenum_t state)
Definition at line 48 of file p_mobj.c.
 {
     state_t*    st;
     do
     {
     if (state == S_NULL)
     {
         mobj->state = (state_t *) S_NULL;
         P_RemoveMobj (mobj);
         return false;
     }
     st = &states[state];
     mobj->state = st;
     mobj->tics = st->tics;
     mobj->sprite = st->sprite;
     mobj->frame = st->frame;
     // Modified handling.
     // Call action functions when the state is set
     if (st->action.acp1)
         st->action.acp1(mobj);
     state = st->nextstate;
     } while (!mobj->tics);
     return true;
 }
References mobj_s::frame, P_RemoveMobj(), S_NULL, mobj_s::sprite, mobj_s::state, state, states, and mobj_s::tics.
Referenced by A_BrainExplode(), A_BrainScream(), A_Chase(), A_CPosRefire(), A_FireCGun(), A_FirePistol(), A_FireShotgun(), A_FireShotgun2(), A_GunFlash(), A_Look(), A_SpawnFly(), A_SpidRefire(), A_VileChase(), A_WeaponReady(), P_DamageMobj(), P_ExplodeMissile(), P_FireWeapon(), P_KillMobj(), P_MobjThinker(), P_MovePlayer(), P_SpawnBlood(), P_SpawnPuff(), P_XYMovement(), PIT_ChangeSector(), and PIT_CheckThing().
P_SetThingPosition()
void P_SetThingPosition (mobj_t * thing)
Definition at line 391 of file p_maputl.c.
 {
     subsector_t*    ss;
     sector_t*       sec;
     int         blockx;
     int         blocky;
     mobj_t**        link;
     // link into subsector
     ss = R_PointInSubsector (thing->x,thing->y);
     thing->subsector = ss;
     if ( ! (thing->flags & MF_NOSECTOR) )
     {
     // invisible things don't go into the sector links
     sec = ss->sector;
     thing->sprev = NULL;
     thing->snext = sec->thinglist;
     if (sec->thinglist)
         sec->thinglist->sprev = thing;
     sec->thinglist = thing;
     }
     // link into blockmap
     if ( ! (thing->flags & MF_NOBLOCKMAP) )
     {
     // inert things don't need to be in blockmap
     blockx = (thing->x - bmaporgx)>>MAPBLOCKSHIFT;
     blocky = (thing->y - bmaporgy)>>MAPBLOCKSHIFT;
     if (blockx>=0
         && blockx < bmapwidth
         && blocky>=0
         && blocky < bmapheight)
     {
         link = &blocklinks[blocky*bmapwidth+blockx];
         thing->bprev = NULL;
         thing->bnext = *link;
         if (*link)
         (*link)->bprev = thing;
         *link = thing;
     }
     else
     {
         // thing is off the map
         thing->bnext = thing->bprev = NULL;
     }
     }
 }
References blocklinks, bmapheight, bmaporgx, bmaporgy, bmapwidth, mobj_s::bnext, mobj_s::bprev, mobj_s::flags, link(), MAPBLOCKSHIFT, MF_NOBLOCKMAP, MF_NOSECTOR, NULL, R_PointInSubsector(), subsector_s::sector, mobj_s::snext, mobj_s::sprev, mobj_s::subsector, sector_t::thinglist, mobj_s::x, and mobj_s::y.
Referenced by A_Fire(), P_SpawnMobj(), P_TeleportMove(), P_TryMove(), and P_UnArchiveThinkers().
P_SetupPsprites()
void P_SetupPsprites (player_t * curplayer)
Definition at line 840 of file p_pspr.c.
 {
     int i;
     // remove all psprites
     for (i=0 ; i<NUMPSPRITES ; i++)
     player->psprites[i].state = NULL;
     // spawn the gun
     player->pendingweapon = player->readyweapon;
     P_BringUpWeapon (player);
 }
References i, NULL, NUMPSPRITES, P_BringUpWeapon(), player_s::pendingweapon, player_s::psprites, player_s::readyweapon, and pspdef_t::state.
Referenced by P_SpawnPlayer().
P_SlideMove()
void P_SlideMove (mobj_t * mo)
Definition at line 722 of file p_map.c.
 {
     fixed_t     leadx;
     fixed_t     leady;
     fixed_t     trailx;
     fixed_t     traily;
     fixed_t     newx;
     fixed_t     newy;
     int         hitcount;
     slidemo = mo;
     hitcount = 0;
   retry:
     if (++hitcount == 3)
     goto stairstep;     // don't loop forever
     // trace along the three leading corners
     if (mo->momx > 0)
     {
     leadx = mo->x + mo->radius;
     trailx = mo->x - mo->radius;
     }
     else
     {
     leadx = mo->x - mo->radius;
     trailx = mo->x + mo->radius;
     }
     if (mo->momy > 0)
     {
     leady = mo->y + mo->radius;
     traily = mo->y - mo->radius;
     }
     else
     {
     leady = mo->y - mo->radius;
     traily = mo->y + mo->radius;
     }
     bestslidefrac = FRACUNIT+1;
     P_PathTraverse ( leadx, leady, leadx+mo->momx, leady+mo->momy,
              PT_ADDLINES, PTR_SlideTraverse );
     P_PathTraverse ( trailx, leady, trailx+mo->momx, leady+mo->momy,
              PT_ADDLINES, PTR_SlideTraverse );
     P_PathTraverse ( leadx, traily, leadx+mo->momx, traily+mo->momy,
              PT_ADDLINES, PTR_SlideTraverse );
     // move up to the wall
     if (bestslidefrac == FRACUNIT+1)
     {
     // the move most have hit the middle, so stairstep
       stairstep:
     if (!P_TryMove (mo, mo->x, mo->y + mo->momy))
         P_TryMove (mo, mo->x + mo->momx, mo->y);
     return;
     }
     // fudge a bit to make sure it doesn't hit
     bestslidefrac -= 0x800;
     if (bestslidefrac > 0)
     {
     newx = FixedMul (mo->momx, bestslidefrac);
     newy = FixedMul (mo->momy, bestslidefrac);
     if (!P_TryMove (mo, mo->x+newx, mo->y+newy))
         goto stairstep;
     }
     // Now continue along the wall.
     // First calculate remainder.
     bestslidefrac = FRACUNIT-(bestslidefrac+0x800);
     if (bestslidefrac > FRACUNIT)
     bestslidefrac = FRACUNIT;
     if (bestslidefrac <= 0)
     return;
     tmxmove = FixedMul (mo->momx, bestslidefrac);
     tmymove = FixedMul (mo->momy, bestslidefrac);
     P_HitSlideLine (bestslideline); // clip the moves
     mo->momx = tmxmove;
     mo->momy = tmymove;
     if (!P_TryMove (mo, mo->x+tmxmove, mo->y+tmymove))
     {
     goto retry;
     }
 }
References bestslidefrac, bestslideline, FixedMul(), FRACUNIT, mobj_s::momx, mobj_s::momy, P_HitSlideLine(), P_PathTraverse(), P_TryMove(), PT_ADDLINES, PTR_SlideTraverse(), mobj_s::radius, slidemo, tmxmove, tmymove, mobj_s::x, and mobj_s::y.
Referenced by P_XYMovement().
P_SpawnBlood()
void P_SpawnBlood (fixed_t x, fixed_t y, fixed_t z, int damage)
Definition at line 878 of file p_mobj.c.
 {
     mobj_t* th;
     z += ((P_Random()-P_Random())<<10);
     th = P_SpawnMobj (x,y,z, MT_BLOOD);
     th->momz = FRACUNIT*2;
     th->tics -= P_Random()&3;
     if (th->tics < 1)
     th->tics = 1;
     if (damage <= 12 && damage >= 9)
     P_SetMobjState (th,S_BLOOD2);
     else if (damage < 9)
     P_SetMobjState (th,S_BLOOD3);
 }
References FRACUNIT, mobj_s::momz, MT_BLOOD, P_Random(), P_SetMobjState(), P_SpawnMobj(), S_BLOOD2, S_BLOOD3, mobj_s::tics, x, and y.
Referenced by PTR_ShootTraverse().
P_SpawnMissile()
mobj_t* P_SpawnMissile (mobj_t * source, mobj_t * dest, mobjtype_t type)
Definition at line 950 of file p_mobj.c.
 {
     mobj_t* th;
     angle_t an;
     int     dist;
     th = P_SpawnMobj (source->x,
               source->y,
               source->z + 4*8*FRACUNIT, type);
     if (th->info->seesound)
     S_StartSound (th, th->info->seesound);
     th->target = source;    // where it came from
     an = R_PointToAngle2 (source->x, source->y, dest->x, dest->y);
     // fuzzy player
     if (dest->flags & MF_SHADOW)
     an += (P_Random()-P_Random())<<20;
     th->angle = an;
     an >>= ANGLETOFINESHIFT;
     th->momx = FixedMul (th->info->speed, finecosine[an]);
     th->momy = FixedMul (th->info->speed, finesine[an]);
     dist = P_AproxDistance (dest->x - source->x, dest->y - source->y);
     dist = dist / th->info->speed;
     if (dist < 1)
     dist = 1;
     th->momz = (dest->z - source->z) / dist;
     P_CheckMissileSpawn (th);
     return th;
 }
References mobj_s::angle, ANGLETOFINESHIFT, finecosine, finesine, FixedMul(), mobj_s::flags, FRACUNIT, mobj_s::info, MF_SHADOW, mobj_s::momx, mobj_s::momy, mobj_s::momz, P_AproxDistance(), P_CheckMissileSpawn(), P_Random(), P_SpawnMobj(), R_PointToAngle2(), S_StartSound(), mobjinfo_t::seesound, mobjinfo_t::speed, mobj_s::target, mobj_s::x, mobj_s::y, and mobj_s::z.
Referenced by A_BrainSpit(), A_BruisAttack(), A_BspiAttack(), A_CyberAttack(), A_FatAttack1(), A_FatAttack2(), A_FatAttack3(), A_HeadAttack(), A_SkelMissile(), and A_TroopAttack().
P_SpawnMobj()
mobj_t* P_SpawnMobj (fixed_t x, fixed_t y, fixed_t z, mobjtype_t type)
Definition at line 506 of file p_mobj.c.
 {
     mobj_t* mobj;
     state_t*    st;
     mobjinfo_t* info;
     mobj = Z_Malloc (sizeof(*mobj), PU_LEVEL, NULL);
     memset (mobj, 0, sizeof (*mobj));
     info = &mobjinfo[type];
     mobj->type = type;
     mobj->info = info;
     mobj->x = x;
     mobj->y = y;
     mobj->radius = info->radius;
     mobj->height = info->height;
     mobj->flags = info->flags;
     mobj->health = info->spawnhealth;
     if (gameskill != sk_nightmare)
     mobj->reactiontime = info->reactiontime;
     mobj->lastlook = P_Random () % MAXPLAYERS;
     // do not set the state with P_SetMobjState,
     // because action routines can not be called yet
     st = &states[info->spawnstate];
     mobj->state = st;
     mobj->tics = st->tics;
     mobj->sprite = st->sprite;
     mobj->frame = st->frame;
     // set subsector and/or block links
     P_SetThingPosition (mobj);
     mobj->floorz = mobj->subsector->sector->floorheight;
     mobj->ceilingz = mobj->subsector->sector->ceilingheight;
     if (z == ONFLOORZ)
     mobj->z = mobj->floorz;
     else if (z == ONCEILINGZ)
     mobj->z = mobj->ceilingz - mobj->info->height;
     else
     mobj->z = z;
     mobj->thinker.function.acp1 = (actionf_p1)P_MobjThinker;
     P_AddThinker (&mobj->thinker);
     return mobj;
 }
References actionf_t::acp1, sector_t::ceilingheight, mobj_s::ceilingz, mobjinfo_t::flags, mobj_s::flags, sector_t::floorheight, mobj_s::floorz, mobj_s::frame, thinker_s::function, gameskill, mobj_s::health, mobjinfo_t::height, mobj_s::height, mobj_s::info, mobj_s::lastlook, MAXPLAYERS, memset(), mobjinfo, NULL, ONCEILINGZ, ONFLOORZ, P_AddThinker(), P_MobjThinker(), P_Random(), P_SetThingPosition(), PU_LEVEL, mobjinfo_t::radius, mobj_s::radius, mobjinfo_t::reactiontime, mobj_s::reactiontime, subsector_s::sector, sk_nightmare, mobjinfo_t::spawnhealth, mobjinfo_t::spawnstate, mobj_s::sprite, mobj_s::state, states, mobj_s::subsector, mobj_s::thinker, mobj_s::tics, mobj_s::type, mobj_s::x, x, y, mobj_s::y, mobj_s::z, and Z_Malloc().
Referenced by A_BFGSpray(), A_BrainExplode(), A_BrainScream(), A_PainShootSkull(), A_SpawnFly(), A_Tracer(), A_VileTarget(), EV_Teleport(), G_CheckSpot(), P_KillMobj(), P_NightmareRespawn(), P_RespawnSpecials(), P_SpawnBlood(), P_SpawnMapThing(), P_SpawnMissile(), P_SpawnPlayer(), P_SpawnPlayerMissile(), P_SpawnPuff(), and PIT_ChangeSector().
P_SpawnPlayerMissile()
void P_SpawnPlayerMissile (mobj_t * source, mobjtype_t type)
Definition at line 996 of file p_mobj.c.
 {
     mobj_t* th;
     angle_t an;
     fixed_t x;
     fixed_t y;
     fixed_t z;
     fixed_t slope;
     // see which target is to be aimed at
     an = source->angle;
     slope = P_AimLineAttack (source, an, 16*64*FRACUNIT);
     if (!linetarget)
     {
     an += 1<<26;
     slope = P_AimLineAttack (source, an, 16*64*FRACUNIT);
     if (!linetarget)
     {
         an -= 2<<26;
         slope = P_AimLineAttack (source, an, 16*64*FRACUNIT);
     }
     if (!linetarget)
     {
         an = source->angle;
         slope = 0;
     }
     }
     x = source->x;
     y = source->y;
     z = source->z + 4*8*FRACUNIT;
     th = P_SpawnMobj (x,y,z, type);
     if (th->info->seesound)
     S_StartSound (th, th->info->seesound);
     th->target = source;
     th->angle = an;
     th->momx = FixedMul( th->info->speed,
              finecosine[an>>ANGLETOFINESHIFT]);
     th->momy = FixedMul( th->info->speed,
              finesine[an>>ANGLETOFINESHIFT]);
     th->momz = FixedMul( th->info->speed, slope);
     P_CheckMissileSpawn (th);
 }
References mobj_s::angle, ANGLETOFINESHIFT, finecosine, finesine, FixedMul(), FRACUNIT, mobj_s::info, linetarget, mobj_s::momx, mobj_s::momy, mobj_s::momz, P_AimLineAttack(), P_CheckMissileSpawn(), P_SpawnMobj(), S_StartSound(), mobjinfo_t::seesound, mobjinfo_t::speed, mobj_s::target, mobj_s::x, x, y, mobj_s::y, and mobj_s::z.
Referenced by A_FireBFG(), A_FireMissile(), and A_FirePlasma().
P_SpawnPuff()
void P_SpawnPuff (fixed_t x, fixed_t y, fixed_t z)
Definition at line 851 of file p_mobj.c.
 {
     mobj_t* th;
     z += ((P_Random()-P_Random())<<10);
     th = P_SpawnMobj (x,y,z, MT_PUFF);
     th->momz = FRACUNIT;
     th->tics -= P_Random()&3;
     if (th->tics < 1)
     th->tics = 1;
     // don't make punches spark on the wall
     if (attackrange == MELEERANGE)
     P_SetMobjState (th, S_PUFF3);
 }
References attackrange, FRACUNIT, MELEERANGE, mobj_s::momz, MT_PUFF, P_Random(), P_SetMobjState(), P_SpawnMobj(), S_PUFF3, mobj_s::tics, x, and y.
Referenced by A_Tracer(), and PTR_ShootTraverse().
P_SubstNullMobj()
mobj_t* P_SubstNullMobj (mobj_t * th)
Definition at line 929 of file p_mobj.c.
 {
     if (mobj == NULL)
     {
         static mobj_t dummy_mobj;
         dummy_mobj.x = 0;
         dummy_mobj.y = 0;
         dummy_mobj.z = 0;
         dummy_mobj.flags = 0;
         mobj = &dummy_mobj;
     }
     return mobj;
 }
References mobj_s::flags, NULL, mobj_s::x, mobj_s::y, and mobj_s::z.
Referenced by A_FatAttack1(), A_FatAttack2(), A_FatAttack3(), A_Fire(), A_SpawnFly(), and P_AimLineAttack().
P_TeleportMove()
boolean P_TeleportMove (mobj_t * thing, fixed_t x, fixed_t y)
Definition at line 131 of file p_map.c.
 {
     int         xl;
     int         xh;
     int         yl;
     int         yh;
     int         bx;
     int         by;
     subsector_t*    newsubsec;
     // kill anything occupying the position
     tmthing = thing;
     tmflags = thing->flags;
     tmx = x;
     tmy = y;
     tmbbox[BOXTOP] = y + tmthing->radius;
     tmbbox[BOXBOTTOM] = y - tmthing->radius;
     tmbbox[BOXRIGHT] = x + tmthing->radius;
     tmbbox[BOXLEFT] = x - tmthing->radius;
     newsubsec = R_PointInSubsector (x,y);
     ceilingline = NULL;
     // The base floor/ceiling is from the subsector
     // that contains the point.
     // Any contacted lines the step closer together
     // will adjust them.
     tmfloorz = tmdropoffz = newsubsec->sector->floorheight;
     tmceilingz = newsubsec->sector->ceilingheight;
     validcount++;
     numspechit = 0;
     // stomp on any things contacted
     xl = (tmbbox[BOXLEFT] - bmaporgx - MAXRADIUS)>>MAPBLOCKSHIFT;
     xh = (tmbbox[BOXRIGHT] - bmaporgx + MAXRADIUS)>>MAPBLOCKSHIFT;
     yl = (tmbbox[BOXBOTTOM] - bmaporgy - MAXRADIUS)>>MAPBLOCKSHIFT;
     yh = (tmbbox[BOXTOP] - bmaporgy + MAXRADIUS)>>MAPBLOCKSHIFT;
     for (bx=xl ; bx<=xh ; bx++)
     for (by=yl ; by<=yh ; by++)
         if (!P_BlockThingsIterator(bx,by,PIT_StompThing))
         return false;
     // the move is ok,
     // so link the thing into its new position
     P_UnsetThingPosition (thing);
     thing->floorz = tmfloorz;
     thing->ceilingz = tmceilingz;
     thing->x = x;
     thing->y = y;
     P_SetThingPosition (thing);
     return true;
 }
References bmaporgx, bmaporgy, BOXBOTTOM, BOXLEFT, BOXRIGHT, BOXTOP, sector_t::ceilingheight, ceilingline, mobj_s::ceilingz, mobj_s::flags, sector_t::floorheight, mobj_s::floorz, MAPBLOCKSHIFT, MAXRADIUS, NULL, numspechit, P_BlockThingsIterator(), P_SetThingPosition(), P_UnsetThingPosition(), PIT_StompThing(), R_PointInSubsector(), mobj_s::radius, subsector_s::sector, tmbbox, tmceilingz, tmdropoffz, tmflags, tmfloorz, tmthing, tmx, tmy, validcount, mobj_s::x, x, y, and mobj_s::y.
Referenced by A_SpawnFly(), and EV_Teleport().
P_TouchSpecialThing()
void P_TouchSpecialThing (mobj_t * special, mobj_t * toucher)
Definition at line 333 of file p_inter.c.
 {
     player_t*   player;
     int     i;
     fixed_t delta;
     int     sound;
     delta = special->z - toucher->z;
     if (delta > toucher->height
     || delta < -8*FRACUNIT)
     {
     // out of reach
     return;
     }
     sound = sfx_itemup;
     player = toucher->player;
     // Dead thing touching.
     // Can happen with a sliding player corpse.
     if (toucher->health <= 0)
     return;
     // Identify by sprite.
     switch (special->sprite)
     {
     // armor
       case SPR_ARM1:
     if (!P_GiveArmor (player, deh_green_armor_class))
         return;
     player->message = DEH_String(GOTARMOR);
     break;
       case SPR_ARM2:
     if (!P_GiveArmor (player, deh_blue_armor_class))
         return;
     player->message = DEH_String(GOTMEGA);
     break;
     // bonus items
       case SPR_BON1:
     player->health++;       // can go over 100%
     if (player->health > deh_max_health)
         player->health = deh_max_health;
     player->mo->health = player->health;
     player->message = DEH_String(GOTHTHBONUS);
     break;
       case SPR_BON2:
     player->armorpoints++;      // can go over 100%
     if (player->armorpoints > deh_max_armor)
         player->armorpoints = deh_max_armor;
         // deh_green_armor_class only applies to the green armor shirt;
         // for the armor helmets, armortype 1 is always used.
     if (!player->armortype)
         player->armortype = 1;
     player->message = DEH_String(GOTARMBONUS);
     break;
       case SPR_SOUL:
     player->health += deh_soulsphere_health;
     if (player->health > deh_max_soulsphere)
         player->health = deh_max_soulsphere;
     player->mo->health = player->health;
     player->message = DEH_String(GOTSUPER);
     sound = sfx_getpow;
     break;
       case SPR_MEGA:
     if (gamemode != commercial)
         return;
     player->health = deh_megasphere_health;
     player->mo->health = player->health;
         // We always give armor type 2 for the megasphere; dehacked only
         // affects the MegaArmor.
     P_GiveArmor (player, 2);
     player->message = DEH_String(GOTMSPHERE);
     sound = sfx_getpow;
     break;
     // cards
     // leave cards for everyone
       case SPR_BKEY:
     if (!player->cards[it_bluecard])
         player->message = DEH_String(GOTBLUECARD);
     P_GiveCard (player, it_bluecard);
     if (!netgame)
         break;
     return;
       case SPR_YKEY:
     if (!player->cards[it_yellowcard])
         player->message = DEH_String(GOTYELWCARD);
     P_GiveCard (player, it_yellowcard);
     if (!netgame)
         break;
     return;
       case SPR_RKEY:
     if (!player->cards[it_redcard])
         player->message = DEH_String(GOTREDCARD);
     P_GiveCard (player, it_redcard);
     if (!netgame)
         break;
     return;
       case SPR_BSKU:
     if (!player->cards[it_blueskull])
         player->message = DEH_String(GOTBLUESKUL);
     P_GiveCard (player, it_blueskull);
     if (!netgame)
         break;
     return;
       case SPR_YSKU:
     if (!player->cards[it_yellowskull])
         player->message = DEH_String(GOTYELWSKUL);
     P_GiveCard (player, it_yellowskull);
     if (!netgame)
         break;
     return;
       case SPR_RSKU:
     if (!player->cards[it_redskull])
         player->message = DEH_String(GOTREDSKULL);
     P_GiveCard (player, it_redskull);
     if (!netgame)
         break;
     return;
     // medikits, heals
       case SPR_STIM:
     if (!P_GiveBody (player, 10))
         return;
     player->message = DEH_String(GOTSTIM);
     break;
       case SPR_MEDI:
     if (!P_GiveBody (player, 25))
         return;
     if (player->health < 25)
         player->message = DEH_String(GOTMEDINEED);
     else
         player->message = DEH_String(GOTMEDIKIT);
     break;
     // power ups
       case SPR_PINV:
     if (!P_GivePower (player, pw_invulnerability))
         return;
     player->message = DEH_String(GOTINVUL);
     sound = sfx_getpow;
     break;
       case SPR_PSTR:
     if (!P_GivePower (player, pw_strength))
         return;
     player->message = DEH_String(GOTBERSERK);
     if (player->readyweapon != wp_fist)
         player->pendingweapon = wp_fist;
     sound = sfx_getpow;
     break;
       case SPR_PINS:
     if (!P_GivePower (player, pw_invisibility))
         return;
     player->message = DEH_String(GOTINVIS);
     sound = sfx_getpow;
     break;
       case SPR_SUIT:
     if (!P_GivePower (player, pw_ironfeet))
         return;
     player->message = DEH_String(GOTSUIT);
     sound = sfx_getpow;
     break;
       case SPR_PMAP:
     if (!P_GivePower (player, pw_allmap))
         return;
     player->message = DEH_String(GOTMAP);
     sound = sfx_getpow;
     break;
       case SPR_PVIS:
     if (!P_GivePower (player, pw_infrared))
         return;
     player->message = DEH_String(GOTVISOR);
     sound = sfx_getpow;
     break;
     // ammo
       case SPR_CLIP:
     if (special->flags & MF_DROPPED)
     {
         if (!P_GiveAmmo (player,am_clip,0))
         return;
     }
     else
     {
         if (!P_GiveAmmo (player,am_clip,1))
         return;
     }
     player->message = DEH_String(GOTCLIP);
     break;
       case SPR_AMMO:
     if (!P_GiveAmmo (player, am_clip,5))
         return;
     player->message = DEH_String(GOTCLIPBOX);
     break;
       case SPR_ROCK:
     if (!P_GiveAmmo (player, am_misl,1))
         return;
     player->message = DEH_String(GOTROCKET);
     break;
       case SPR_BROK:
     if (!P_GiveAmmo (player, am_misl,5))
         return;
     player->message = DEH_String(GOTROCKBOX);
     break;
       case SPR_CELL:
     if (!P_GiveAmmo (player, am_cell,1))
         return;
     player->message = DEH_String(GOTCELL);
     break;
       case SPR_CELP:
     if (!P_GiveAmmo (player, am_cell,5))
         return;
     player->message = DEH_String(GOTCELLBOX);
     break;
       case SPR_SHEL:
     if (!P_GiveAmmo (player, am_shell,1))
         return;
     player->message = DEH_String(GOTSHELLS);
     break;
       case SPR_SBOX:
     if (!P_GiveAmmo (player, am_shell,5))
         return;
     player->message = DEH_String(GOTSHELLBOX);
     break;
       case SPR_BPAK:
     if (!player->backpack)
     {
         for (i=0 ; i<NUMAMMO ; i++)
         player->maxammo[i] *= 2;
         player->backpack = true;
     }
     for (i=0 ; i<NUMAMMO ; i++)
         P_GiveAmmo (player, i, 1);
     player->message = DEH_String(GOTBACKPACK);
     break;
     // weapons
       case SPR_BFUG:
     if (!P_GiveWeapon (player, wp_bfg, false) )
         return;
     player->message = DEH_String(GOTBFG9000);
     sound = sfx_wpnup;
     break;
       case SPR_MGUN:
     if (!P_GiveWeapon (player, wp_chaingun, (special->flags&MF_DROPPED) != 0) )
         return;
     player->message = DEH_String(GOTCHAINGUN);
     sound = sfx_wpnup;
     break;
       case SPR_CSAW:
     if (!P_GiveWeapon (player, wp_chainsaw, false) )
         return;
     player->message = DEH_String(GOTCHAINSAW);
     sound = sfx_wpnup;
     break;
       case SPR_LAUN:
     if (!P_GiveWeapon (player, wp_missile, false) )
         return;
     player->message = DEH_String(GOTLAUNCHER);
     sound = sfx_wpnup;
     break;
       case SPR_PLAS:
     if (!P_GiveWeapon (player, wp_plasma, false) )
         return;
     player->message = DEH_String(GOTPLASMA);
     sound = sfx_wpnup;
     break;
       case SPR_SHOT:
     if (!P_GiveWeapon (player, wp_shotgun, (special->flags&MF_DROPPED) != 0 ) )
         return;
     player->message = DEH_String(GOTSHOTGUN);
     sound = sfx_wpnup;
     break;
       case SPR_SGN2:
     if (!P_GiveWeapon (player, wp_supershotgun, (special->flags&MF_DROPPED) != 0 ) )
         return;
     player->message = DEH_String(GOTSHOTGUN2);
     sound = sfx_wpnup;
     break;
       default:
     I_Error ("P_SpecialThing: Unknown gettable thing");
     }
     if (special->flags & MF_COUNTITEM)
     player->itemcount++;
     P_RemoveMobj (special);
     player->bonuscount += BONUSADD;
     if (player == &players[consoleplayer])
     S_StartSound (NULL, sound);
 }
References am_cell, am_clip, am_misl, am_shell, player_s::armorpoints, player_s::armortype, player_s::backpack, BONUSADD, player_s::bonuscount, player_s::cards, commercial, consoleplayer, deh_blue_armor_class, deh_green_armor_class, deh_max_armor, deh_max_health, deh_max_soulsphere, deh_megasphere_health, deh_soulsphere_health, DEH_String, mobj_s::flags, FRACUNIT, gamemode, GOTARMBONUS, GOTARMOR, GOTBACKPACK, GOTBERSERK, GOTBFG9000, GOTBLUECARD, GOTBLUESKUL, GOTCELL, GOTCELLBOX, GOTCHAINGUN, GOTCHAINSAW, GOTCLIP, GOTCLIPBOX, GOTHTHBONUS, GOTINVIS, GOTINVUL, GOTLAUNCHER, GOTMAP, GOTMEDIKIT, GOTMEDINEED, GOTMEGA, GOTMSPHERE, GOTPLASMA, GOTREDCARD, GOTREDSKULL, GOTROCKBOX, GOTROCKET, GOTSHELLBOX, GOTSHELLS, GOTSHOTGUN, GOTSHOTGUN2, GOTSTIM, GOTSUIT, GOTSUPER, GOTVISOR, GOTYELWCARD, GOTYELWSKUL, player_s::health, mobj_s::health, mobj_s::height, i, I_Error(), it_bluecard, it_blueskull, it_redcard, it_redskull, it_yellowcard, it_yellowskull, player_s::itemcount, player_s::maxammo, player_s::message, MF_COUNTITEM, MF_DROPPED, player_s::mo, netgame, NULL, NUMAMMO, P_GiveAmmo(), P_GiveArmor(), P_GiveBody(), P_GiveCard(), P_GivePower(), P_GiveWeapon(), P_RemoveMobj(), player_s::pendingweapon, mobj_s::player, players, pw_allmap, pw_infrared, pw_invisibility, pw_invulnerability, pw_ironfeet, pw_strength, player_s::readyweapon, S_StartSound(), sfx_getpow, sfx_itemup, sfx_wpnup, SPR_AMMO, SPR_ARM1, SPR_ARM2, SPR_BFUG, SPR_BKEY, SPR_BON1, SPR_BON2, SPR_BPAK, SPR_BROK, SPR_BSKU, SPR_CELL, SPR_CELP, SPR_CLIP, SPR_CSAW, SPR_LAUN, SPR_MEDI, SPR_MEGA, SPR_MGUN, SPR_PINS, SPR_PINV, SPR_PLAS, SPR_PMAP, SPR_PSTR, SPR_PVIS, SPR_RKEY, SPR_ROCK, SPR_RSKU, SPR_SBOX, SPR_SGN2, SPR_SHEL, SPR_SHOT, SPR_SOUL, SPR_STIM, SPR_SUIT, SPR_YKEY, SPR_YSKU, mobj_s::sprite, wp_bfg, wp_chaingun, wp_chainsaw, wp_fist, wp_missile, wp_plasma, wp_shotgun, wp_supershotgun, and mobj_s::z.
Referenced by PIT_CheckThing().
P_TryMove()
boolean P_TryMove (mobj_t * thing, fixed_t x, fixed_t y)
Definition at line 478 of file p_map.c.
 {
     fixed_t oldx;
     fixed_t oldy;
     int     side;
     int     oldside;
     line_t* ld;
     floatok = false;
     if (!P_CheckPosition (thing, x, y))
     return false;       // solid wall or thing
     if ( !(thing->flags & MF_NOCLIP) )
     {
     if (tmceilingz - tmfloorz < thing->height)
         return false;   // doesn't fit
     floatok = true;
     if ( !(thing->flags&MF_TELEPORT)
          &&tmceilingz - thing->z < thing->height)
         return false;   // mobj must lower itself to fit
     if ( !(thing->flags&MF_TELEPORT)
          && tmfloorz - thing->z > 24*FRACUNIT )
         return false;   // too big a step up
     if ( !(thing->flags&(MF_DROPOFF|MF_FLOAT))
          && tmfloorz - tmdropoffz > 24*FRACUNIT )
         return false;   // don't stand over a dropoff
     }
     // the move is ok,
     // so link the thing into its new position
     P_UnsetThingPosition (thing);
     oldx = thing->x;
     oldy = thing->y;
     thing->floorz = tmfloorz;
     thing->ceilingz = tmceilingz;
     thing->x = x;
     thing->y = y;
     P_SetThingPosition (thing);
     // if any special lines were hit, do the effect
     if (! (thing->flags&(MF_TELEPORT|MF_NOCLIP)) )
     {
     while (numspechit--)
     {
         // see if the line was crossed
         ld = spechit[numspechit];
         side = P_PointOnLineSide (thing->x, thing->y, ld);
         oldside = P_PointOnLineSide (oldx, oldy, ld);
         if (side != oldside)
         {
         if (ld->special)
             P_CrossSpecialLine (ld-lines, oldside, thing);
         }
     }
     }
     return true;
 }
References mobj_s::ceilingz, mobj_s::flags, floatok, mobj_s::floorz, FRACUNIT, mobj_s::height, height(), lines, MF_DROPOFF, MF_FLOAT, MF_NOCLIP, MF_TELEPORT, numspechit, P_CheckPosition(), P_CrossSpecialLine(), P_PointOnLineSide(), P_SetThingPosition(), P_UnsetThingPosition(), spechit, line_s::special, tmceilingz, tmdropoffz, tmfloorz, mobj_s::x, x, y, mobj_s::y, and mobj_s::z.
Referenced by A_PainShootSkull(), P_CheckMissileSpawn(), P_Move(), P_SlideMove(), and P_XYMovement().
P_UnsetThingPosition()
void P_UnsetThingPosition (mobj_t * thing)
Definition at line 342 of file p_maputl.c.
 {
     int     blockx;
     int     blocky;
     if ( ! (thing->flags & MF_NOSECTOR) )
     {
     // inert things don't need to be in blockmap?
     // unlink from subsector
     if (thing->snext)
         thing->snext->sprev = thing->sprev;
     if (thing->sprev)
         thing->sprev->snext = thing->snext;
     else
         thing->subsector->sector->thinglist = thing->snext;
     }
     if ( ! (thing->flags & MF_NOBLOCKMAP) )
     {
     // inert things don't need to be in blockmap
     // unlink from block map
     if (thing->bnext)
         thing->bnext->bprev = thing->bprev;
     if (thing->bprev)
         thing->bprev->bnext = thing->bnext;
     else
     {
         blockx = (thing->x - bmaporgx)>>MAPBLOCKSHIFT;
         blocky = (thing->y - bmaporgy)>>MAPBLOCKSHIFT;
         if (blockx>=0 && blockx < bmapwidth
         && blocky>=0 && blocky <bmapheight)
         {
         blocklinks[blocky*bmapwidth+blockx] = thing->bnext;
         }
     }
     }
 }
References blocklinks, bmapheight, bmaporgx, bmaporgy, bmapwidth, mobj_s::bnext, mobj_s::bprev, mobj_s::flags, MAPBLOCKSHIFT, MF_NOBLOCKMAP, MF_NOSECTOR, subsector_s::sector, mobj_s::snext, mobj_s::sprev, mobj_s::subsector, sector_t::thinglist, mobj_s::x, and mobj_s::y.
Referenced by A_Fire(), P_RemoveMobj(), P_TeleportMove(), and P_TryMove().
P_UseLines()
void P_UseLines (player_t * player)
Definition at line 1177 of file p_map.c.
 {
     int     angle;
     fixed_t x1;
     fixed_t y1;
     fixed_t x2;
     fixed_t y2;
     usething = player->mo;
     angle = player->mo->angle >> ANGLETOFINESHIFT;
     x1 = player->mo->x;
     y1 = player->mo->y;
     x2 = x1 + (USERANGE>>FRACBITS)*finecosine[angle];
     y2 = y1 + (USERANGE>>FRACBITS)*finesine[angle];
     P_PathTraverse ( x1, y1, x2, y2, PT_ADDLINES, PTR_UseTraverse );
 }
References mobj_s::angle, ANGLETOFINESHIFT, finecosine, finesine, FRACBITS, player_s::mo, P_PathTraverse(), PT_ADDLINES, PTR_UseTraverse(), USERANGE, usething, mobj_s::x, mobj_s::y, and y1().
Referenced by P_PlayerThink().
Variable Documentation
blocklinks
mobj_t** blocklinks extern
Definition at line 91 of file p_setup.c.
Referenced by P_BlockThingsIterator(), P_LoadBlockMap(), P_SetThingPosition(), and P_UnsetThingPosition().
blockmap
short* blockmap extern
Definition at line 84 of file p_setup.c.
Referenced by P_BlockLinesIterator(), and P_LoadBlockMap().
blockmaplump
short* blockmaplump extern
Definition at line 86 of file p_setup.c.
Referenced by P_BlockLinesIterator(), and P_LoadBlockMap().
bmapheight
int bmapheight extern
Definition at line 83 of file p_setup.c.
Referenced by P_BlockLinesIterator(), P_BlockThingsIterator(), P_GroupLines(), P_LoadBlockMap(), P_SetThingPosition(), and P_UnsetThingPosition().
bmaporgx
fixed_t bmaporgx extern
Definition at line 88 of file p_setup.c.
Referenced by A_VileChase(), AM_drawGrid(), P_CheckPosition(), P_GroupLines(), P_LoadBlockMap(), P_PathTraverse(), P_RadiusAttack(), P_SetThingPosition(), P_TeleportMove(), and P_UnsetThingPosition().
bmaporgy
fixed_t bmaporgy extern
Definition at line 89 of file p_setup.c.
Referenced by A_VileChase(), AM_drawGrid(), P_CheckPosition(), P_GroupLines(), P_LoadBlockMap(), P_PathTraverse(), P_RadiusAttack(), P_SetThingPosition(), P_TeleportMove(), and P_UnsetThingPosition().
bmapwidth
int bmapwidth extern
Definition at line 82 of file p_setup.c.
Referenced by P_BlockLinesIterator(), P_BlockThingsIterator(), P_GroupLines(), P_LoadBlockMap(), P_SetThingPosition(), and P_UnsetThingPosition().
ceilingline
line_t* ceilingline extern
Definition at line 80 of file p_map.c.
Referenced by P_CheckPosition(), P_TeleportMove(), P_XYMovement(), and PIT_CheckLine().
clipammo
int clipammo[NUMAMMO] extern
Definition at line 51 of file p_inter.c.
Referenced by P_GiveAmmo().
floatok
boolean floatok extern
Definition at line 72 of file p_map.c.
Referenced by P_Move(), and P_TryMove().
intercept_p
intercept_t* intercept_p extern
Definition at line 540 of file p_maputl.c.
Referenced by P_PathTraverse(), P_TraverseIntercepts(), PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
intercepts
intercept_t intercepts[MAXINTERCEPTS] extern
Definition at line 539 of file p_maputl.c.
Referenced by P_PathTraverse(), P_TraverseIntercepts(), PIT_AddLineIntercepts(), and PIT_AddThingIntercepts().
iquehead
int iquehead extern
Definition at line 568 of file p_mobj.c.
Referenced by P_RemoveMobj(), P_RespawnSpecials(), and P_SetupLevel().
iquetail
int iquetail extern
Definition at line 569 of file p_mobj.c.
Referenced by P_RemoveMobj(), P_RespawnSpecials(), and P_SetupLevel().
itemrespawnque
mapthing_t itemrespawnque[ITEMQUESIZE] extern
Definition at line 566 of file p_mobj.c.
Referenced by P_RemoveMobj(), and P_RespawnSpecials().
itemrespawntime
int itemrespawntime[ITEMQUESIZE] extern
Definition at line 567 of file p_mobj.c.
Referenced by P_RemoveMobj(), and P_RespawnSpecials().
linetarget
mobj_t* linetarget extern
Definition at line 821 of file p_map.c.
Referenced by A_BFGSpray(), A_Punch(), A_Saw(), P_AimLineAttack(), P_BulletSlope(), P_SpawnPlayerMissile(), and PTR_AimTraverse().
lowfloor
fixed_t lowfloor extern
Definition at line 292 of file p_maputl.c.
Referenced by P_LineOpening(), and PIT_CheckLine().
maxammo
int maxammo[NUMAMMO] extern
Definition at line 50 of file p_inter.c.
Referenced by G_PlayerReborn().
numspechit
int numspechit extern
Definition at line 86 of file p_map.c.
Referenced by P_CheckPosition(), P_Move(), P_TeleportMove(), P_TryMove(), PIT_CheckLine(), and SpechitOverrun().
openbottom
fixed_t openbottom extern
Definition at line 290 of file p_maputl.c.
Referenced by P_CrossSubsector(), P_LineOpening(), PIT_CheckLine(), PTR_AimTraverse(), PTR_ShootTraverse(), and PTR_SlideTraverse().
openrange
fixed_t openrange extern
Definition at line 291 of file p_maputl.c.
Referenced by P_LineOpening(), P_RecursiveSound(), and PTR_UseTraverse().
opentop
fixed_t opentop extern
Definition at line 289 of file p_maputl.c.
Referenced by P_CrossSubsector(), P_LineOpening(), PIT_CheckLine(), PTR_AimTraverse(), PTR_ShootTraverse(), and PTR_SlideTraverse().
rejectmatrix
byte* rejectmatrix extern
Definition at line 101 of file p_setup.c.
Referenced by P_CheckSight(), and P_LoadReject().
spechit
line_t* spechit[MAXSPECIALCROSS] extern
Definition at line 85 of file p_map.c.
Referenced by P_Move(), P_TryMove(), and PIT_CheckLine().
thinkercap
thinker_t thinkercap extern
Definition at line 40 of file p_tick.c.
Referenced by A_BossDeath(), A_BrainAwake(), A_KeenDie(), A_PainShootSkull(), EV_Teleport(), P_AddThinker(), P_ArchiveSpecials(), P_ArchiveThinkers(), P_InitThinkers(), P_RunThinkers(), P_UnArchiveThinkers(), and R_PrecacheLevel().
tmceilingz
fixed_t tmceilingz extern
Definition at line 75 of file p_map.c.
Referenced by P_CheckPosition(), P_TeleportMove(), P_ThingHeightClip(), P_TryMove(), and PIT_CheckLine().
tmfloorz
fixed_t tmfloorz extern
Definition at line 74 of file p_map.c.
Referenced by P_CheckPosition(), P_Move(), P_TeleportMove(), P_ThingHeightClip(), P_TryMove(), and PIT_CheckLine().
trace
divline_t trace extern
Definition at line 542 of file p_maputl.c.
Referenced by P_PathTraverse(), PIT_AddLineIntercepts(), PIT_AddThingIntercepts(), and PTR_ShootTraverse().