Fennix: Userspace/apps/base/busybox/coreutils/timeout.c File Reference
timeout.c File Reference
#include "libbb.h"
Functions
static NOINLINE int timeout_wait (int timeout, pid_t pid)
int timeout_main (int argc, char **argv) MAIN_EXTERNALLY_VISIBLE
Function Documentation
timeout_main()
int timeout_main (int argc UNUSED_PARAM, char ** argv)
Definition at line 66 of file timeout.c.
 {
     int signo;
     int status;
     int parent = 0;
     int timeout;
     int kill_timeout;
     pid_t pid;
 #if !BB_MMU
     char *sv1, *sv2;
 #endif
     const char *opt_s = "TERM";
     char *opt_k = NULL;
     /* -p option is not documented, it is needed to support NOMMU. */
     /* -t SECONDS; -p PARENT_PID */
     /* '+': stop at first non-option */
     getopt32(argv, "+s:k:" USE_FOR_NOMMU("p:+"), &opt_s, &opt_k, &parent);
     /*argv += optind; - no, wait for bb_daemonize_or_rexec! */
     signo = get_signum(opt_s);
     if (signo < 0)
         bb_error_msg_and_die("unknown signal '%s'", opt_s);
     kill_timeout = 0;
     if (opt_k)
         kill_timeout = parse_duration_str(opt_k);
     if (!argv[optind])
         bb_show_usage();
     timeout = parse_duration_str(argv[optind++]);
     if (!argv[optind]) /* no PROG? */
         bb_show_usage();
     /* We want to create a grandchild which will watch
      * and kill the grandparent. Other methods:
      * making parent watch child disrupts parent<->child link
      * (example: "tcpsvd 0.0.0.0 1234 timeout service_prog" -
      * it's better if service_prog is a child of tcpsvd!),
      * making child watch parent results in programs having
      * unexpected children. */
     if (parent) /* we were re-execed, already grandchild */
         goto grandchild;
 #if !BB_MMU
     sv1 = argv[optind];
     sv2 = argv[optind + 1];
 #endif
     pid = xvfork();
     if (pid == 0) {
         /* Child: spawn grandchild and exit */
         parent = getppid();
 #if !BB_MMU
         argv[optind] = xasprintf("-p%u", parent);
         argv[optind + 1] = NULL;
 #endif
         /* NB: exits with nonzero on error: */
         bb_daemonize_or_rexec(0, argv);
         /* Here we are grandchild. Sleep, then kill grandparent */
  grandchild:
         if (timeout_wait(timeout, parent) == EXIT_SUCCESS)
             return EXIT_SUCCESS;
         kill(parent, signo);
         if (kill_timeout > 0) {
             if (timeout_wait(kill_timeout, parent) == EXIT_SUCCESS)
                 return EXIT_SUCCESS;
             kill(parent, SIGKILL);
         }
         return EXIT_SUCCESS;
     }
     /* Parent */
     wait(&status); /* wait for child to die */
     /* Did intermediate [v]fork or exec fail? */
     if (!WIFEXITED(status) || WEXITSTATUS(status) != 0)
         return EXIT_FAILURE;
     /* Ok, exec a program as requested */
     argv += optind;
 #if !BB_MMU
     argv[0] = sv1;
     argv[1] = sv2;
 #endif
     BB_EXECVP_or_die(argv);
 }
References argv, bb_daemonize_or_rexec, bb_error_msg_and_die(), BB_EXECVP_or_die(), bb_show_usage(), EXIT_FAILURE, EXIT_SUCCESS, get_signum(), getopt32(), getppid(), kill(), NULL, optind, parent, parse_duration_str(), pid, SIGKILL, status, timeout(), timeout_wait(), USE_FOR_NOMMU, wait(), WEXITSTATUS, WIFEXITED, xasprintf(), and xvfork.
timeout_wait()
static NOINLINE int timeout_wait (int timeout, pid_t pid) static
Definition at line 50 of file timeout.c.
 {
     /* Just sleep(HUGE_NUM); kill(parent) may kill wrong process! */
     while (1) {
         sleep1();
         if (--timeout <= 0)
             break;
         if (kill(pid, 0)) {
             /* process is gone */
             return EXIT_SUCCESS;
         }
     }
     return EXIT_FAILURE;
 }
References EXIT_FAILURE, EXIT_SUCCESS, kill(), pid, sleep1(), and timeout().
Referenced by timeout_main().