Fennix Userspace: Userspace/apps/user/games/doomgeneric/doomgeneric/i_timer.c File Reference
i_timer.c File Reference
#include "i_timer.h"
#include "doomtype.h"
#include "doomgeneric.h"
#include <stdarg.h>
Functions
int I_GetTicks (void)
int I_GetTime (void)
int I_GetTimeMS (void)
void I_Sleep (int ms)
void I_WaitVBL (int count)
void I_InitTimer (void)
Variables
static uint32_t basetime = 0
Function Documentation
I_GetTicks()
int I_GetTicks (void)
Definition at line 38 of file i_timer.c.
 {
     return DG_GetTicksMs();
 }
References DG_GetTicksMs().
Referenced by I_GetTime(), and I_GetTimeMS().
I_GetTime()
int I_GetTime (void)
Definition at line 43 of file i_timer.c.
 {
     uint32_t ticks;
     ticks = I_GetTicks();
     if (basetime == 0)
         basetime = ticks;
     ticks -= basetime;
     return (ticks * TICRATE) / 1000;
 }
References basetime, I_GetTicks(), and TICRATE.
Referenced by D_Display(), G_CheckDemoStatus(), G_DoPlayDemo(), M_Responder(), and TryRunTics().
I_GetTimeMS()
int I_GetTimeMS (void)
Definition at line 62 of file i_timer.c.
 {
     uint32_t ticks;
     ticks = I_GetTicks();
     if (basetime == 0)
         basetime = ticks;
     return ticks - basetime;
 }
References basetime, and I_GetTicks().
Referenced by GetAdjustedTime().
I_InitTimer()
void I_InitTimer (void)
Definition at line 90 of file i_timer.c.
 {
     // initialize timer
     //SDL_Init(SDL_INIT_TIMER);
 }
Referenced by D_DoomMain().
I_Sleep()
void I_Sleep (int ms)
Definition at line 76 of file i_timer.c.
 {
     //SDL_Delay(ms);
     //usleep (ms * 1000);
     DG_SleepMs(ms);
 }
References DG_SleepMs().
Referenced by D_Display(), and TryRunTics().
I_WaitVBL()
void I_WaitVBL (int count)
Definition at line 84 of file i_timer.c.
 {
     //I_Sleep((count * 1000) / 70);
 }
Referenced by M_QuitResponse().
Variable Documentation
basetime
uint32_t basetime = 0 static
Definition at line 35 of file i_timer.c.
Referenced by I_GetTime(), and I_GetTimeMS().