Fennix: Userspace/apps/base/busybox/libbb/ubi.c File Reference
ubi.c File Reference
#include "libbb.h"
Macros
#define UBI_MAX_VOLUME_NAME 127
#define UBI_MAX_VOLUMES 128
Functions
unsigned FAST_FUNC ubi_devnum_from_devname (const char *str)
int FAST_FUNC ubi_get_volid_by_name (unsigned ubi_devnum, const char *vol_name)
Macro Definition Documentation
UBI_MAX_VOLUME_NAME
#define UBI_MAX_VOLUME_NAME 127
Definition at line 14 of file ubi.c.
UBI_MAX_VOLUMES
#define UBI_MAX_VOLUMES 128
Definition at line 15 of file ubi.c.
Function Documentation
ubi_devnum_from_devname()
unsigned FAST_FUNC ubi_devnum_from_devname (const char * str)
Definition at line 17 of file ubi.c.
 {
     unsigned ubi_devnum;
     if (sscanf(str, "/dev/ubi%u", &ubi_devnum) != 1)
         bb_error_msg_and_die("not an UBI device: '%s'", str);
     return ubi_devnum;
 }
References bb_error_msg_and_die(), sscanf(), and str.
Referenced by ubi_tools_main(), and ubirename_main().
ubi_get_volid_by_name()
int FAST_FUNC ubi_get_volid_by_name (unsigned ubi_devnum, const char * vol_name)
Definition at line 26 of file ubi.c.
 {
     unsigned i;
     for (i = 0; i < UBI_MAX_VOLUMES; i++) {
         char buf[UBI_MAX_VOLUME_NAME + 1];
         char fname[sizeof("/sys/class/ubi/ubi%u_%u/name") + 2 * sizeof(int)*3];
         sprintf(fname, "/sys/class/ubi/ubi%u_%u/name", ubi_devnum, i);
         if (open_read_close(fname, buf, sizeof(buf)) <= 0)
             continue;
         buf[UBI_MAX_VOLUME_NAME] = '\0';
         strchrnul(buf, '\n')[0] = '\0';
         if (strcmp(vol_name, buf) == 0)
             return i;
     }
     bb_error_msg_and_die("volume '%s' not found", vol_name);
 }
References bb_error_msg_and_die(), buf, fname, i, open_read_close(), sprintf(), strchrnul(), strcmp, UBI_MAX_VOLUME_NAME, and UBI_MAX_VOLUMES.
Referenced by ubi_tools_main(), and ubirename_main().