Fennix Userspace: Userspace/apps/base/busybox/libbb/get_last_path_component.c File Reference
get_last_path_component.c File Reference
#include "libbb.h"
Functions
const char *FAST_FUNC bb_basename (const char *name)
char *FAST_FUNC bb_get_last_path_component_nostrip (const char *path)
char *FAST_FUNC bb_get_last_path_component_strip (char *path)
Function Documentation
bb_basename()
const char* FAST_FUNC bb_basename (const char * name)
Definition at line 11 of file get_last_path_component.c.
 {
     const char *cp = strrchr(name, '/');
     if (cp)
         return cp + 1;
     return name;
 }
References strrchr().
Referenced by action_compat(), bb_init_module_24(), comm_match(), config_file_action(), display_verbose(), find_pid_by_name(), get_old_name(), handle_incoming_and_exit(), install_main(), invalid_name(), main(), make_device(), microcom_main(), mktemp_main(), modinfo_main(), modprobe_main(), read_cmdline(), rmmod_main(), scan_one_dir(), sestatus_main(), signal_mdevs(), test_main(), unzip_main(), and uuidcache_check_device().
bb_get_last_path_component_nostrip()
char* FAST_FUNC bb_get_last_path_component_nostrip (const char * path)
Definition at line 25 of file get_last_path_component.c.
 {
     char *slash = strrchr(path, '/');
     if (!slash || (slash == path && !slash[1]))
         return (char*)path;
     return slash + 1;
 }
References strrchr().
Referenced by bb_get_last_path_component_strip(), do_modprobe(), download_one_url(), exec_shell(), load_modules_dep(), modprobe_main(), and parse_module().
bb_get_last_path_component_strip()
char* FAST_FUNC bb_get_last_path_component_strip (char * path)
Definition at line 41 of file get_last_path_component.c.
 {
     char *slash = last_char_is(path, '/');
     if (slash)
         while (*slash == '/' && slash != path)
             *slash-- = '\0';
     return bb_get_last_path_component_nostrip(path);
 }
References bb_get_last_path_component_nostrip(), and last_char_is().
Referenced by basename_main(), cp_main(), ln_main(), makemime_main(), mv_main(), nuke_main(), parse(), rm_main(), and xmalloc_follow_symlinks().