Fennix Userspace: Userspace/apps/base/busybox/libbb/last_char_is.c File Reference
last_char_is.c File Reference
#include "libbb.h"
Functions
char *FAST_FUNC last_char_is (const char *s, int c)
Function Documentation
last_char_is()
char* FAST_FUNC last_char_is (const char * s, int c)
Definition at line 12 of file last_char_is.c.
 {
     if (!s[0])
         return NULL;
     while (s[1])
         s++;
     return (*s == (char)c) ? (char *) s : NULL;
 }
References c, NULL, and s.
Referenced by bb_get_last_path_component_strip(), chomp(), concat_path_file(), get_header_tar(), load_modules_dep(), modinfo_main(), modprobe_main(), parse_one_line(), read_interfaces(), tar_main(), udhcp_str2optset(), unzip_main(), and update_passwd().